AAAA
0.324;2805.0
5AAA
0.234;988.1
9AAA
0.243;1455.6
KAAA
0.312;1923.1
4A(2A)
0.253;-531.2
(2A)(7A)
0.265;584.4
A(2TA)
0.197;170.0
QA(2A)
0.319;403.8
2A(4A)
0.237;-531.2
26AA
0.234;-1062.5
AA(29)
0.208;53.1
2A(QA)
0.256;403.8
A(34A)
0.206;-414.4
6A(3A)
0.188;-180.6
(3A)(9A)
0.286;935.0
A(3QA)
0.250;520.6
AA(34)
0.197;-414.4
3A(7A)
0.229;-63.7
39AA
0.216;-595.0
AA(3Q)
0.324;520.6
(4A)(5A)
0.245;584.4
A(48A)
0.233;170.0
TA(4A)
0.242;403.8
(4A)(KA)
0.263;1519.4
46AA
0.201;-828.7
AA(49)
0.248;286.9
4A(QA)
0.244;637.5
A(56A)
0.278;53.1
8A(5A)
0.252;286.9
(5A)(JA)
0.308;1402.5
55AA
0.284;-63.7
AA(58)
0.248;286.9
5A(JA)
0.238;637.5
5KAA
0.277;106.2
8A(6A)
0.322;403.8
(6A)(JA)
0.317;1519.4
66AA
0.277;170.0
AA(69)
0.291;520.6
6A(QA)
0.306;871.2
A(78A)
0.244;520.6
TA(7A)
0.287;754.4
(7A)(KA)
0.387;1870.0
79AA
0.274;-127.5
AA(7Q)
0.286;988.1
(8A)(9A)
0.366;1519.4
A(8QA)
0.311;1105.0
AA(89)
0.233;754.4
8A(QA)
0.241;1105.0
A(9TA)
0.293;988.1
QA(9A)
0.278;1221.9
9A(JA)
0.275;1105.0
9KAA
0.278;573.8
QA(TA)
0.266;1338.7
TA(QA)
0.277;1338.7
A(JQA)
0.253;1455.6
AA(JQ)
0.321;1455.6
(QA)(KA)
0.292;2454.4
KKAA
0.298;1806.3
2(25A)
0.235;-1816.9
27(2A)
0.210;-1583.1
(2T)(2A)
0.292;-467.5
2(2KA)
0.192;-881.9
(236A)
0.154;-2348.1
(23TA)
0.198;-1880.6
33(2A)
0.218;-1933.7
(36)(2A)
0.241;-1583.1
3(29A)
0.220;-1997.5
3J(2A)
0.188;-1763.8
(245A)
0.133;-2348.1
(249A)
0.216;-1880.6
(24KA)
0.206;-1413.1
46(2A)
0.152;-2231.2
(49)(2A)
0.222;-1115.6
4(2QA)
0.238;-1530.0
6(25A)
0.150;-2114.4
T(25A)
0.187;-1646.9
5(26A)
0.172;-2114.4
58(2A)
0.180;-1880.6
(5J)(2A)
0.182;-765.0
6(26A)
0.154;-1232.5
T(26A)
0.169;-1530.0
6(27A)
0.215;-1880.6
69(2A)
0.200;-1646.9
(6Q)(2A)
0.269;-531.3
(279A)
0.173;-1530.0
(27KA)
0.170;-1062.5
79(2A)
0.178;-1530.0
(7Q)(2A)
0.220;-414.4
(28TA)
0.174;-1296.2
88(2A)
0.197;-765.0
(8J)(2A)
0.265;-414.4
9(29A)
0.209;-531.2
K(29A)
0.211;-828.7
9(2QA)
0.206;-945.6
J(2TA)
0.212;-945.6
TJ(2A)
0.198;-945.6
(2JQA)
0.196;-711.9
J(2KA)
0.213;-595.0
(QK)(2A)
0.253;286.9
22(4A)
0.147;-1933.7
226A
0.203;-2465.0
2A(29)
0.215;-1349.4
22(QA)
0.219;-998.7
2(34A)
0.194;-2581.9
26(3A)
0.194;-2348.1
(29)(3A)
0.197;-1232.5
2(3QA)
0.151;-1646.9
A(234)
0.157;-2581.9
(23)(7A)
0.254;-1466.2
9A(23)
0.166;-1997.5
A(23Q)
0.152;-1646.9
2A(34)
0.158;-2581.9
2A(36)
0.149;-2348.1
2A(38)
0.186;-2114.4
2A(3T)
0.151;-1880.6
2A(3Q)
0.164;-1646.9
2(45A)
0.144;-2348.1
27(4A)
0.170;-2114.4
(2T)(4A)
0.229;-998.7
2(4KA)
0.219;-1413.1
A(246)
0.179;-2231.2
(24)(9A)
0.198;-1115.6
JA(24)
0.173;-1646.9
24(5A)
0.190;-2348.1
24(7A)
0.211;-2114.4
24(9A)
0.185;-1880.6
24(JA)
0.208;-1646.9
24(KA)
0.192;-1413.1
26(5A)
0.230;-2114.4
(29)(5A)
0.201;-998.7
2(5QA)
0.168;-1413.1
A(256)
0.181;-2114.4
(25)(9A)
0.186;-998.7
JA(25)
0.209;-1530.0
25(6A)
0.150;-2114.4
25(8A)
0.168;-1880.6
25(TA)
0.169;-1646.9
25(QA)
0.168;-1413.1
(26)(6A)
0.207;-467.5
2(69A)
0.210;-1646.9
2J(6A)
0.194;-1413.1
(26)(7A)
0.164;-1115.6
9A(26)
0.156;-1646.9
A(26Q)
0.179;-1296.2
2A(67)
0.238;-1880.6
2A(69)
0.225;-1646.9
2A(6J)
0.203;-1413.1
2A(6K)
0.204;-1179.4
(29)(7A)
0.224;-765.0
2(7QA)
0.240;-1179.4
A(278)
0.149;-1646.9
(27)(JA)
0.242;-531.3
KA(27)
0.222;-1062.5
2A(79)
0.197;-1530.0
2A(7J)
0.194;-1296.2
2A(7K)
0.179;-1062.5
(2T)(8A)
0.282;-531.3
2(8KA)
0.221;-945.6
A(28T)
0.180;-1296.2
(28)(KA)
0.239;-180.6
28(TA)
0.164;-1296.2
28(QA)
0.213;-1062.5
(29)(9A)
0.277;233.8
2(9QA)
0.173;-945.6
A(29T)
0.268;-1179.4
(29)(KA)
0.212;-63.7
29(JA)
0.220;-1062.5
29(KA)
0.243;-828.7
2J(TA)
0.248;-945.6
(2T)(JA)
0.237;-180.6
KA(2T)
0.272;-711.9
2A(TQ)
0.274;-828.7
2(JQA)
0.183;-711.9
A(2JQ)
0.194;-711.9
2A(JQ)
0.232;-711.9
2(QKA)
0.247;-478.1
2Q(KA)
0.228;-478.1
33(3A)
0.177;-1051.9
(36)(3A)
0.191;-701.2
3(39A)
0.203;-1115.6
3J(3A)
0.210;-881.9
(345A)
0.188;-2231.2
(349A)
0.198;-1763.8
(34KA)
0.257;-1296.2
46(3A)
0.193;-2114.4
(49)(3A)
0.215;-998.7
4(3QA)
0.169;-1413.1
6(35A)
0.181;-1997.5
T(35A)
0.186;-1530.0
5(36A)
0.155;-1997.5
58(3A)
0.182;-1763.8
(5J)(3A)
0.206;-648.1
6(36A)
0.213;-1115.6
T(36A)
0.228;-1413.1
6(37A)
0.189;-1763.8
69(3A)
0.190;-1530.0
(6Q)(3A)
0.232;-414.4
(379A)
0.200;-1413.1
(37KA)
0.195;-945.6
79(3A)
0.243;-1413.1
(7Q)(3A)
0.209;-297.5
(38TA)
0.260;-1179.4
88(3A)
0.239;-648.1
(8J)(3A)
0.255;-297.5
9(39A)
0.236;-414.4
K(39A)
0.175;-711.9
9(3QA)
0.198;-828.7
J(3TA)
0.231;-828.7
TJ(3A)
0.252;-828.7
(3JQA)
0.170;-595.0
J(3KA)
0.224;-478.1
(QK)(3A)
0.312;403.8
33(5A)
0.170;-1583.1
337A
0.197;-2114.4
3A(3T)
0.204;-998.7
33(KA)
0.230;-648.1
3(46A)
0.206;-2114.4
38(4A)
0.155;-1880.6
(3J)(4A)
0.207;-765.0
4A(34)
0.224;-1583.1
A(347)
0.173;-1997.5
(34)(TA)
0.176;-881.9
QA(34)
0.168;-1413.1
345A
0.154;-2996.2
347A
0.204;-2762.5
349A
0.170;-2528.8
34JA
0.161;-2295.0
34KA
0.164;-2061.2
37(5A)
0.197;-1880.6
(3T)(5A)
0.217;-765.0
3(5KA)
0.236;-1179.4
A(357)
0.212;-1880.6
(35)(TA)
0.245;-765.0
QA(35)
0.199;-1296.2
356A
0.116;-2762.5
358A
0.228;-2528.8
35TA
0.159;-2295.0
35QA
0.204;-2061.2
(37)(6A)
0.235;-998.7
3(6TA)
0.199;-1413.1
3Q(6A)
0.248;-1179.4
(36)(8A)
0.165;-881.9
TA(36)
0.246;-1413.1
A(36K)
0.176;-1062.5
6A(38)
0.154;-1646.9
6A(3T)
0.212;-1413.1
6A(3Q)
0.227;-1179.4
37(7A)
0.224;-881.9
(3T)(7A)
0.190;-531.3
3(7KA)
0.205;-945.6
A(379)
0.191;-1413.1
(37)(QA)
0.212;-297.5
7A(38)
0.205;-1530.0
7A(3T)
0.207;-1296.2
7A(3Q)
0.263;-1062.5
38(8A)
0.209;-648.1
(3J)(8A)
0.271;-297.5
8A(38)
0.174;-648.1
A(38J)
0.188;-1062.5
388A
0.202;-1413.1
38TA
0.180;-1944.4
38QA
0.217;-1710.6
(3T)(9A)
0.236;-297.5
3(9KA)
0.214;-711.9
A(39J)
0.244;-945.6
399A
0.191;-1179.4
39JA
0.155;-1710.6
39KA
0.187;-1476.9
3Q(TA)
0.219;-711.9
(3T)(QA)
0.267;53.1
TA(3J)
0.195;-828.7
TA(3K)
0.197;-595.0
3(JKA)
0.248;-478.1
A(3JK)
0.273;-478.1
JA(3K)
0.208;-478.1
QA(3Q)
0.310;286.9
3QKA
0.198;-1126.2
45(4A)
0.189;-1349.4
(48)(4A)
0.229;-233.8
4(4JA)
0.260;-648.1
4K(4A)
0.218;-414.4
(459A)
0.244;-1530.0
(45KA)
0.195;-1062.5
57(4A)
0.153;-1763.8
(5T)(4A)
0.270;-648.1
5(4KA)
0.198;-1062.5
(469A)
0.183;-1413.1
(46KA)
0.205;-945.6
68(4A)
0.200;-1530.0
(6J)(4A)
0.232;-414.4
7(47A)
0.244;-765.0
J(47A)
0.207;-1062.5
78(4A)
0.153;-1413.1
(7J)(4A)
0.182;-297.5
8(48A)
0.211;-531.2
Q(48A)
0.207;-828.7
(8T)(4A)
0.238;-297.5
8(4KA)
0.188;-711.9
(49QA)
0.200;-711.9
9(4JA)
0.249;-828.7
9K(4A)
0.268;-595.0
TT(4A)
0.242;-63.7
(TK)(4A)
0.307;286.9
J(4QA)
0.173;-478.1
K(4QA)
0.180;-244.4
44(5A)
0.198;-1349.4
447A
0.156;-1880.6
4A(4T)
0.223;-765.0
44(KA)
0.249;-414.4
4(57A)
0.199;-1763.8
49(5A)
0.255;-1530.0
(4Q)(5A)
0.275;-414.4
6A(45)
0.200;-1880.6
A(459)
0.144;-1530.0
(45)(QA)
0.222;-414.4
5A(46)
0.184;-1880.6
5A(48)
0.216;-1646.9
5A(4T)
0.200;-1413.1
5A(4Q)
0.232;-1179.4
46(6A)
0.240;-998.7
(49)(6A)
0.215;-648.1
4(6QA)
0.240;-1062.5
A(467)
0.195;-1646.9
(46)(TA)
0.262;-531.3
QA(46)
0.179;-1062.5
467A
0.148;-2411.9
469A
0.165;-2178.1
46JA
0.191;-1944.4
46KA
0.207;-1710.6
49(7A)
0.197;-1296.2
(4Q)(7A)
0.223;-180.6
8A(47)
0.227;-1413.1
A(47J)
0.194;-1062.5
477A
0.223;-1530.0
479A
0.198;-2061.2
47JA
0.216;-1827.5
47KA
0.205;-1593.8
4T(8A)
0.177;-1062.5
(4K)(8A)
0.248;53.1
TA(48)
0.184;-1062.5
A(48K)
0.236;-711.9
8A(4T)
0.185;-1062.5
8A(4Q)
0.266;-828.7
49(9A)
0.233;-297.5
(4Q)(9A)
0.252;53.1
TA(49)
0.235;-945.6
A(49K)
0.281;-595.0
9A(4J)
0.228;-828.7
9A(4K)
0.254;-595.0
4(TQA)
0.192;-595.0
A(4TJ)
0.198;-711.9
4TTA
0.211;-828.7
4TQA
0.259;-1360.0
(4Q)(JA)
0.245;286.9
QA(4J)
0.244;-478.1
4JQA
0.168;-1243.1
(4K)(QA)
0.324;520.6
QA(4K)
0.219;-244.4
5(56A)
0.217;-998.7
58(5A)
0.204;-765.0
(5J)(5A)
0.267;350.6
6(56A)
0.236;-881.9
T(56A)
0.240;-1179.4
6(57A)
0.247;-1530.0
69(5A)
0.265;-1296.2
(6Q)(5A)
0.273;-180.6
(579A)
0.174;-1179.4
(57KA)
0.219;-711.9
79(5A)
0.250;-1179.4
(7Q)(5A)
0.214;-63.7
(58TA)
0.198;-945.6
88(5A)
0.287;-414.4
(8J)(5A)
0.291;-63.7
9(59A)
0.238;-180.6
K(59A)
0.247;-478.1
9(5QA)
0.225;-595.0
J(5TA)
0.223;-595.0
TJ(5A)
0.188;-595.0
(5JQA)
0.186;-361.2
J(5KA)
0.280;-244.4
(QK)(5A)
0.266;637.5
55(7A)
0.209;-881.9
559A
0.210;-1413.1
5A(5Q)
0.249;-297.5
(57)(6A)
0.190;-765.0
5(6TA)
0.237;-1179.4
5Q(6A)
0.261;-945.6
(56)(8A)
0.242;-648.1
TA(56)
0.232;-1179.4
A(56K)
0.175;-828.7
6A(58)
0.263;-1413.1
6A(5T)
0.240;-1179.4
6A(5Q)
0.219;-945.6
57(7A)
0.200;-648.1
(5T)(7A)
0.194;-297.5
5(7KA)
0.230;-711.9
A(579)
0.206;-1179.4
(57)(QA)
0.308;-63.7
7A(58)
0.172;-1296.2
7A(5T)
0.184;-1062.5
7A(5Q)
0.225;-828.7
58(8A)
0.180;-414.4
(5J)(8A)
0.313;-63.7
8A(58)
0.256;-414.4
A(58J)
0.268;-828.7
588A
0.235;-1179.4
58TA
0.205;-1710.6
58QA
0.194;-1476.9
(5T)(9A)
0.229;-63.7
5(9KA)
0.219;-478.1
A(59J)
0.199;-711.9
599A
0.206;-945.6
59JA
0.178;-1476.9
59KA
0.210;-1243.1
5Q(TA)
0.240;-478.1
(5T)(QA)
0.291;286.9
TA(5J)
0.231;-595.0
TA(5K)
0.233;-361.2
5(JKA)
0.181;-244.4
A(5JK)
0.248;-244.4
JA(5K)
0.258;-244.4
QA(5Q)
0.255;520.6
5QKA
0.184;-892.5
67(6A)
0.229;-648.1
(6T)(6A)
0.249;467.5
6(6KA)
0.297;53.1
(67TA)
0.201;-945.6
77(6A)
0.196;-531.2
(7T)(6A)
0.270;-180.6
7(6KA)
0.191;-595.0
(68JA)
0.202;-711.9
(89)(6A)
0.240;-180.6
8(6QA)
0.221;-595.0
T(69A)
0.187;-711.9
9(6TA)
0.216;-711.9
9Q(6A)
0.240;-478.1
Q(6TA)
0.292;-361.2
(TQ)(6A)
0.263;403.8
(6JKA)
0.249;-127.5
JK(6A)
0.206;-127.5
K(6KA)
0.258;871.2
668A
0.192;-1296.2
6A(6J)
0.248;-180.6
(67)(7A)
0.313;233.8
6(7TA)
0.195;-945.6
6Q(7A)
0.209;-711.9
(67)(9A)
0.244;-297.5
JA(67)
0.174;-828.7
67(8A)
0.216;-1179.4
67(TA)
0.193;-945.6
67(QA)
0.232;-711.9
(68)(8A)
0.230;467.5
6(8JA)
0.234;-711.9
6K(8A)
0.285;-478.1
(68)(JA)
0.248;53.1
KA(68)
0.243;-478.1
6A(8T)
0.223;-828.7
6A(8Q)
0.232;-595.0
6(9TA)
0.234;-711.9
6Q(9A)
0.176;-478.1
(69)(JA)
0.205;170.0
KA(69)
0.217;-361.2
6A(9J)
0.210;-595.0
6A(9K)
0.214;-361.2
(6Q)(TA)
0.244;403.8
JA(6T)
0.255;-478.1
6T(JA)
0.254;-478.1
6T(KA)
0.207;-244.4
6Q(JA)
0.227;-244.4
(6J)(KA)
0.214;637.5
6J(KA)
0.199;-127.5
6K(QA)
0.229;-10.6
6A(QK)
0.249;-10.6
(78)(7A)
0.257;467.5
7(7JA)
0.213;53.1
7K(7A)
0.272;286.9
(78QA)
0.205;-478.1
8(7TA)
0.269;-711.9
8Q(7A)
0.233;-478.1
J(79A)
0.207;-478.1
9T(7A)
0.193;-595.0
(9K)(7A)
0.236;520.6
K(7TA)
0.239;-127.5
T(7KA)
0.303;-127.5
JJ(7A)
0.248;520.6
(7QKA)
0.246;106.2
777A
0.243;-414.4
7A(7T)
0.248;-63.7
77(KA)
0.213;286.9
7(8TA)
0.223;-711.9
7Q(8A)
0.240;-478.1
(78)(TA)
0.237;53.1
QA(78)
0.173;-478.1
789A
0.206;-1593.8
78JA
0.208;-1360.0
78KA
0.160;-1126.2
7J(9A)
0.275;-478.1
(79)(TA)
0.287;170.0
QA(79)
0.209;-361.2
79TA
0.234;-1360.0
79QA
0.262;-1126.2
(7J)(TA)
0.208;403.8
TA(7T)
0.203;286.9
A(7TK)
0.271;-127.5
TA(7Q)
0.253;-244.4
7J(JA)
0.243;520.6
(7J)(QA)
0.263;637.5
JA(7Q)
0.229;-127.5
7Q(QA)
0.241;754.4
7QQA
0.258;-10.6
7KKA
0.204;223.1
8(8JA)
0.223;286.9
8K(8A)
0.260;520.6
(89KA)
0.269;-127.5
9J(8A)
0.227;-361.2
(8TJA)
0.302;-244.4
(TJ)(8A)
0.234;520.6
J(8JA)
0.213;637.5
JQ(8A)
0.241;-10.6
Q(8KA)
0.234;223.1
889A
0.237;-711.9
8A(8Q)
0.315;403.8
(8T)(9A)
0.198;286.9
8(9KA)
0.252;-127.5
A(89J)
0.249;-361.2
899A
0.206;-595.0
89JA
0.237;-1126.2
89KA
0.172;-892.5
8Q(TA)
0.212;-127.5
(8T)(QA)
0.269;637.5
TA(8J)
0.239;-244.4
TA(8K)
0.257;-10.6
8(JKA)
0.250;106.2
A(8JK)
0.210;106.2
JA(8K)
0.232;106.2
QA(8Q)
0.298;871.2
8QKA
0.235;-541.9
9T(9A)
0.291;403.8
(9K)(9A)
0.321;1519.4
K(9TA)
0.220;106.2
T(9KA)
0.254;106.2
JJ(9A)
0.208;754.4
(9QKA)
0.233;340.0
999A
0.275;286.9
9A(9Q)
0.243;637.5
(9J)(TA)
0.339;637.5
TA(9T)
0.306;520.6
A(9TK)
0.245;106.2
TA(9Q)
0.245;-10.6
9J(JA)
0.270;754.4
(9J)(QA)
0.264;871.3
JA(9Q)
0.323;106.2
9Q(QA)
0.250;988.1
9QQA
0.237;223.1
9KKA
0.318;456.9
T(TKA)
0.248;988.1
JJ(TA)
0.228;871.2
(TQKA)
0.299;456.9
TTTA
0.250;637.5
TA(TK)
0.306;988.1
(TK)(JA)
0.302;1105.0
KA(TJ)
0.248;340.0
TA(JK)
0.238;340.0
(TQ)(KA)
0.325;1221.9
(TK)(KA)
0.319;2103.8
J(JKA)
0.248;1221.9
(QK)(JA)
0.295;1338.8
JJ(KA)
0.272;1221.9
QA(JQ)
0.314;1221.9
JQKA
0.207;-191.2
QK(QA)
0.323;1455.6
QK(KA)
0.304;1572.5
22(24)
0.175;-2571.2
22(28)
0.232;-2103.8
22(2Q)
0.201;-1636.2
24(23)
0.119;-3219.4
(23)(27)
0.160;-2103.8
2(23T)
0.175;-2518.1
2Q(23)
0.173;-2284.4
23(25)
0.159;-3102.5
2237
0.180;-3633.8
22(3T)
0.159;-2518.1
23(2K)
0.211;-2167.5
2(246)
0.146;-2868.8
28(24)
0.136;-2635.0
(24)(2J)
0.185;-1519.4
2244
0.125;-3102.5
22(47)
0.220;-2751.9
24(2T)
0.195;-2401.2
224Q
0.189;-2932.5
26(25)
0.207;-2751.9
(25)(29)
0.183;-1636.2
2(25Q)
0.167;-2050.6
22(56)
0.158;-2751.9
25(29)
0.208;-2401.2
225J
0.152;-2932.5
26(26)
0.205;-1870.0
(26)(29)
0.217;-1519.4
2(26Q)
0.230;-1933.7
22(67)
0.174;-2518.1
26(2T)
0.155;-2167.5
226Q
0.146;-2698.8
28(27)
0.184;-2284.4
(27)(2J)
0.182;-1168.8
2277
0.177;-2401.2
22(7T)
0.144;-2050.6
27(2K)
0.200;-1700.0
2(28T)
0.193;-1933.7
2Q(28)
0.152;-1700.0
28(2T)
0.142;-1933.7
228Q
0.144;-2465.0
2T(29)
0.184;-1816.9
(29)(2K)
0.255;-701.2
229J
0.207;-2465.0
2T(2T)
0.213;-935.0
(2T)(2K)
0.240;-584.4
22TQ
0.207;-2231.2
2Q(2J)
0.230;-1349.4
2J(2K)
0.196;-1232.5
22QQ
0.188;-1232.5
3(234)
0.213;-3102.5
36(23)
0.185;-2868.8
(23)(39)
0.182;-1753.1
3(23Q)
0.214;-2167.5
5(234)
0.173;-3633.8
9(234)
0.137;-3166.3
K(234)
0.146;-2698.8
4(237)
0.136;-3400.0
49(23)
0.152;-3166.3
(23)(4Q)
0.180;-2050.6
(2357)
0.144;-3283.1
(235J)
0.183;-2815.6
(23)(56)
0.192;-2635.0
5(239)
0.195;-3049.4
5J(23)
0.152;-2815.6
(2367)
0.153;-3166.3
(236J)
0.129;-2698.8
(23)(67)
0.160;-2401.2
6(23T)
0.151;-2815.6
6Q(23)
0.201;-2581.9
9(237)
0.159;-2815.6
K(237)
0.187;-2348.1
7(23T)
0.202;-2698.8
7Q(23)
0.150;-2465.0
T(238)
0.143;-2581.9
8(239)
0.156;-2698.8
8J(23)
0.189;-2465.0
(239T)
0.162;-2465.0
99(23)
0.161;-1816.9
(23)(9Q)
0.194;-1466.2
(23TQ)
0.178;-2114.4
T(23Q)
0.182;-2114.4
Q(23J)
0.166;-1997.5
(23)(JK)
0.180;-1115.6
QK(23)
0.177;-1763.8
23(35)
0.154;-2985.6
33(28)
0.157;-2635.0
233T
0.161;-3166.3
23(3K)
0.179;-2050.6
(24)(36)
0.170;-2751.9
3(249)
0.197;-3166.3
3J(24)
0.172;-2932.5
(34)(25)
0.177;-2868.8
27(34)
0.112;-3400.0
2(34T)
0.175;-3049.4
(34)(2K)
0.184;-1933.7
34(26)
0.152;-3516.9
34(28)
0.147;-3283.1
34(2T)
0.174;-3049.4
34(2Q)
0.161;-2815.6
(25)(35)
0.237;-1986.9
3(258)
0.124;-3166.3
3T(25)
0.162;-2932.5
(25)(3K)
0.180;-1816.9
27(35)
0.134;-3283.1
2(35T)
0.132;-2932.5
(35)(2K)
0.162;-1816.9
35(27)
0.197;-3283.1
35(29)
0.203;-3049.4
35(2J)
0.193;-2815.6
35(2K)
0.194;-2581.9
37(26)
0.128;-3166.3
(26)(3T)
0.198;-2050.6
3(26K)
0.177;-2465.0
2(368)
0.183;-3049.4
(36)(2J)
0.223;-1933.7
2K(36)
0.201;-2465.0
23(68)
0.116;-3049.4
23(6T)
0.223;-2815.6
23(6Q)
0.202;-2581.9
3(278)
0.147;-2932.5
3T(27)
0.191;-2698.8
(27)(3K)
0.204;-1583.1
29(37)
0.202;-2815.6
2(37Q)
0.141;-2465.0
23(78)
0.152;-2932.5
23(7T)
0.136;-2698.8
23(7Q)
0.165;-2465.0
3(289)
0.136;-2698.8
3J(28)
0.178;-2465.0
(38)(29)
0.171;-1933.7
2J(38)
0.151;-2465.0
38(29)
0.200;-2698.8
38(2J)
0.196;-2465.0
38(2K)
0.218;-2231.2
3T(29)
0.130;-2465.0
(29)(3K)
0.198;-1349.4
2J(39)
0.165;-2348.1
39(2T)
0.135;-2465.0
39(2Q)
0.168;-2231.2
(2T)(3T)
0.204;-818.1
3(2TK)
0.216;-1997.5
2(3TQ)
0.139;-2114.4
23(TJ)
0.147;-2231.2
23(TK)
0.205;-1997.5
(2J)(3K)
0.179;-1115.6
2K(3J)
0.194;-1880.6
23(JK)
0.187;-1880.6
(3Q)(2K)
0.262;-998.7
(2K)(3K)
0.255;-116.9
4(246)
0.163;-2635.0
48(24)
0.179;-2401.2
(24)(4J)
0.249;-1285.6
5(245)
0.144;-2635.0
9(245)
0.148;-2932.5
K(245)
0.165;-2465.0
5(248)
0.160;-3049.4
5T(24)
0.159;-2815.6
(24)(5K)
0.205;-1700.0
9(246)
0.162;-2815.6
K(246)
0.145;-2348.1
6(249)
0.145;-2815.6
6J(24)
0.174;-2581.9
(2478)
0.173;-2815.6
(247Q)
0.162;-2348.1
7(249)
0.182;-2698.8
7J(24)
0.143;-2465.0
(2489)
0.161;-2581.9
(248K)
0.207;-2114.4
8T(24)
0.159;-2465.0
(24)(8K)
0.205;-1349.4
Q(249)
0.200;-2114.4
(24)(9J)
0.212;-1466.2
T(24T)
0.206;-1466.2
T(24J)
0.219;-2114.4
TK(24)
0.186;-1880.6
(24)(JQ)
0.222;-1115.6
QQ(24)
0.215;-998.7
24(45)
0.128;-2751.9
44(28)
0.174;-2401.2
244T
0.149;-2932.5
24(4K)
0.227;-1816.9
(25)(47)
0.174;-2401.2
4(25T)
0.143;-2815.6
4Q(25)
0.149;-2581.9
(45)(27)
0.192;-2401.2
29(45)
0.195;-2932.5
2(45Q)
0.167;-2581.9
24(56)
0.141;-3283.1
24(58)
0.153;-3049.4
24(5T)
0.122;-2815.6
24(5Q)
0.128;-2581.9
4(267)
0.146;-3049.4
49(26)
0.148;-2815.6
(26)(4Q)
0.187;-1700.0
27(46)
0.168;-3049.4
2(46T)
0.178;-2698.8
(46)(2K)
0.211;-1583.1
46(28)
0.172;-2932.5
46(2T)
0.155;-2698.8
46(2Q)
0.189;-2465.0
(27)(47)
0.251;-1402.5
4(27T)
0.153;-2581.9
4Q(27)
0.177;-2348.1
(47)(29)
0.194;-1933.7
2J(47)
0.155;-2465.0
47(28)
0.146;-2815.6
47(2T)
0.152;-2581.9
47(2Q)
0.171;-2348.1
(28)(48)
0.199;-1168.8
4(28J)
0.204;-2348.1
4K(28)
0.185;-2114.4
(48)(2J)
0.226;-1583.1
2K(48)
0.168;-2114.4
24(8T)
0.153;-2465.0
24(8Q)
0.166;-2231.2
4(29T)
0.172;-2348.1
4Q(29)
0.136;-2114.4
(49)(2J)
0.200;-1466.2
2K(49)
0.192;-1997.5
24(9J)
0.177;-2231.2
24(9K)
0.198;-1997.5
(2T)(4Q)
0.200;-1232.5
2J(4T)
0.213;-2114.4
4T(2J)
0.228;-2114.4
4T(2K)
0.242;-1880.6
4Q(2J)
0.143;-1880.6
(4J)(2K)
0.235;-998.7
4J(2K)
0.183;-1763.8
4K(2Q)
0.196;-1646.9
24(QK)
0.183;-1646.9
(25)(56)
0.212;-1636.2
5(259)
0.177;-2050.6
5J(25)
0.171;-1816.9
(2567)
0.192;-2932.5
(256J)
0.172;-2465.0
(25)(67)
0.185;-2167.5
6(25T)
0.163;-2581.9
6Q(25)
0.213;-2348.1
9(257)
0.197;-2581.9
K(257)
0.174;-2114.4
7(25T)
0.177;-2465.0
7Q(25)
0.186;-2231.2
T(258)
0.162;-2348.1
8(259)
0.172;-2465.0
8J(25)
0.172;-2231.2
(259T)
0.190;-2231.2
99(25)
0.228;-1583.1
(25)(9Q)
0.183;-1232.5
(25TQ)
0.198;-1880.6
T(25Q)
0.159;-1880.6
Q(25J)
0.165;-1763.8
(25)(JK)
0.222;-881.9
QK(25)
0.250;-1530.0
25(57)
0.202;-2284.4
55(2T)
0.189;-1933.7
255Q
0.169;-2465.0
57(26)
0.175;-2932.5
(26)(5T)
0.212;-1816.9
5(26K)
0.157;-2231.2
2(568)
0.168;-2815.6
(56)(2J)
0.200;-1700.0
2K(56)
0.192;-2231.2
25(68)
0.159;-2815.6
25(6T)
0.209;-2581.9
25(6Q)
0.156;-2348.1
5(278)
0.157;-2698.8
5T(27)
0.152;-2465.0
(27)(5K)
0.230;-1349.4
29(57)
0.131;-2581.9
2(57Q)
0.162;-2231.2
25(78)
0.179;-2698.8
25(7T)
0.142;-2465.0
25(7Q)
0.161;-2231.2
5(289)
0.213;-2465.0
5J(28)
0.165;-2231.2
(58)(29)
0.171;-1700.0
2J(58)
0.197;-2231.2
58(29)
0.164;-2465.0
58(2J)
0.199;-2231.2
58(2K)
0.186;-1997.5
5T(29)
0.187;-2231.2
(29)(5K)
0.214;-1115.6
2J(59)
0.158;-2114.4
59(2T)
0.188;-2231.2
59(2Q)
0.175;-1997.5
(2T)(5T)
0.239;-584.4
5(2TK)
0.208;-1763.8
2(5TQ)
0.141;-1880.6
25(TJ)
0.160;-1997.5
25(TK)
0.205;-1763.8
(2J)(5K)
0.186;-881.9
2K(5J)
0.180;-1646.9
25(JK)
0.188;-1646.9
(5Q)(2K)
0.199;-765.0
(2K)(5K)
0.308;116.9
6(268)
0.206;-1933.7
6T(26)
0.229;-1700.0
(26)(6K)
0.296;-584.4
T(267)
0.150;-2348.1
7(268)
0.167;-2581.9
7T(26)
0.152;-2348.1
(26)(7K)
0.204;-1232.5
J(268)
0.231;-2114.4
89(26)
0.174;-2348.1
(26)(8Q)
0.166;-1232.5
(269J)
0.169;-1997.5
(26)(9T)
0.168;-1349.4
9(26K)
0.149;-1763.8
(26TK)
0.185;-1646.9
TQ(26)
0.173;-1763.8
K(26J)
0.216;-1530.0
Q(26Q)
0.221;-765.0
KK(26)
0.261;-531.2
66(29)
0.160;-1816.9
266J
0.151;-2348.1
67(27)
0.178;-1933.7
(27)(6T)
0.190;-1583.1
6(27K)
0.202;-1997.5
2(679)
0.178;-2465.0
(67)(2Q)
0.235;-1349.4
27(68)
0.154;-2581.9
27(6T)
0.199;-2348.1
27(6Q)
0.206;-2114.4
68(28)
0.180;-1700.0
(28)(6J)
0.226;-1349.4
28(68)
0.166;-1700.0
2(68J)
0.164;-2114.4
2688
0.174;-2465.0
268T
0.154;-2996.2
268Q
0.191;-2762.5
(29)(6T)
0.188;-1349.4
6(29K)
0.200;-1763.8
2(69J)
0.190;-1997.5
2699
0.175;-2231.2
269J
0.166;-2762.5
269K
0.150;-2528.8
6Q(2T)
0.179;-1763.8
(6T)(2Q)
0.233;-998.7
2T(6J)
0.141;-1880.6
2T(6K)
0.166;-1646.9
6(2JK)
0.220;-1530.0
2(6JK)
0.228;-1530.0
2J(6K)
0.167;-1530.0
2Q(6Q)
0.207;-765.0
26QK
0.157;-2178.1
78(27)
0.185;-1700.0
(27)(7J)
0.268;-584.4
8(278)
0.183;-1583.1
Q(278)
0.227;-1880.6
(27)(8T)
0.165;-1349.4
8(27K)
0.227;-1763.8
(279Q)
0.210;-1763.8
9(27J)
0.205;-1880.6
9K(27)
0.238;-1646.9
TT(27)
0.193;-1115.6
(27)(TK)
0.288;-765.0
J(27Q)
0.211;-1530.0
K(27Q)
0.234;-1296.2
77(28)
0.197;-1700.0
277T
0.152;-2231.2
27(7K)
0.241;-1115.6
(28)(7T)
0.238;-1349.4
7(28K)
0.189;-1763.8
2(78T)
0.158;-2114.4
(78)(2K)
0.223;-998.7
78(2T)
0.181;-2114.4
78(2Q)
0.147;-1880.6
(29)(79)
0.254;-584.4
7(29Q)
0.166;-1763.8
2(79T)
0.148;-1997.5
(79)(2K)
0.190;-881.9
79(2J)
0.180;-1880.6
79(2K)
0.175;-1646.9
7J(2T)
0.179;-1763.8
(7T)(2J)
0.188;-998.7
2K(7T)
0.219;-1530.0
27(TQ)
0.171;-1646.9
7(2JQ)
0.198;-1530.0
2(7JQ)
0.191;-1530.0
27(JQ)
0.176;-1530.0
7(2QK)
0.258;-1296.2
7Q(2K)
0.205;-1296.2
88(28)
0.215;-701.2
(28)(8J)
0.253;-350.6
9(289)
0.184;-1232.5
K(289)
0.232;-1530.0
9(28Q)
0.200;-1646.9
J(28T)
0.246;-1646.9
TJ(28)
0.187;-1646.9
(28JQ)
0.227;-1413.1
J(28K)
0.204;-1296.2
(28)(QK)
0.271;-414.4
88(2T)
0.187;-1232.5
288Q
0.189;-1763.8
8T(29)
0.208;-1880.6
(29)(8K)
0.238;-765.0
2J(89)
0.181;-1763.8
89(2T)
0.213;-1880.6
89(2Q)
0.178;-1646.9
(2T)(8T)
0.236;-233.8
8(2TK)
0.216;-1413.1
2(8TQ)
0.211;-1530.0
28(TJ)
0.196;-1646.9
28(TK)
0.200;-1413.1
(2J)(8K)
0.232;-531.3
2K(8J)
0.243;-1296.2
28(JK)
0.184;-1296.2
(8Q)(2K)
0.228;-414.4
(2K)(8K)
0.275;467.5
9(29J)
0.211;-881.9
9K(29)
0.223;-648.1
TT(29)
0.213;-881.9
(29)(TK)
0.215;-531.3
J(29Q)
0.211;-1296.2
K(29Q)
0.203;-1062.5
99(2T)
0.259;-998.7
299Q
0.209;-1530.0
9J(2T)
0.182;-1530.0
(9T)(2J)
0.183;-765.0
2K(9T)
0.222;-1296.2
29(TQ)
0.177;-1413.1
9(2JQ)
0.256;-1296.2
2(9JQ)
0.214;-1296.2
29(JQ)
0.231;-1296.2
9(2QK)
0.239;-1062.5
9Q(2K)
0.226;-1062.5
TT(2T)
0.228;0.0
(2T)(TK)
0.306;350.6
J(2TQ)
0.209;-1179.4
K(2TQ)
0.238;-945.6
TT(2J)
0.277;-648.1
2TTK
0.176;-1179.4
TK(2J)
0.260;-1062.5
2TJJ
0.191;-1296.2
2TJK
0.163;-1827.5
2(TQK)
0.229;-945.6
TK(2K)
0.229;-63.7
(2J)(JK)
0.246;584.4
QK(2J)
0.176;-828.7
2J(JK)
0.285;-180.6
(JQ)(2K)
0.238;-63.7
(2K)(JK)
0.291;818.1
K(2QK)
0.252;170.0
2K(QK)
0.196;170.0
3335
0.150;-2868.8
3339
0.169;-2401.2
333K
0.198;-1933.7
36(34)
0.184;-2635.0
(34)(39)
0.191;-1519.4
3(34Q)
0.218;-1933.7
33(45)
0.169;-2751.9
34(38)
0.150;-2401.2
334T
0.195;-2932.5
33(4K)
0.165;-1816.9
(35)(37)
0.168;-1636.2
3(35T)
0.162;-2050.6
3Q(35)
0.193;-1816.9
35(37)
0.164;-2401.2
3359
0.136;-2932.5
33(5Q)
0.193;-1816.9
(36)(37)
0.218;-1519.4
3(36T)
0.189;-1933.7
3Q(36)
0.189;-1700.0
36(38)
0.171;-2167.5
336T
0.143;-2698.8
33(6K)
0.182;-1583.1
(37)(39)
0.162;-1168.8
3(37Q)
0.168;-1583.1
33(78)
0.167;-2050.6
37(3J)
0.202;-1700.0
337K
0.176;-2231.2
3T(38)
0.149;-1700.0
(38)(3K)
0.213;-584.4
338T
0.178;-2465.0
33(8K)
0.250;-1349.4
(39)(3J)
0.186;-701.2
3399
0.181;-1700.0
33(9Q)
0.241;-1349.4
(3T)(3J)
0.284;-584.4
33TT
0.184;-1466.2
33(TK)
0.195;-1115.6
(3J)(3K)
0.248;-233.8
33JK
0.168;-1763.8
33(QK)
0.214;-881.9
45(34)
0.172;-2635.0
(34)(48)
0.173;-1519.4
4(34J)
0.171;-1933.7
4K(34)
0.216;-1700.0
(3459)
0.149;-2815.6
(345K)
0.189;-2348.1
57(34)
0.207;-3049.4
(34)(5T)
0.184;-1933.7
5(34K)
0.146;-2348.1
(3469)
0.162;-2698.8
(346K)
0.189;-2231.2
68(34)
0.171;-2815.6
(34)(6J)
0.174;-1700.0
7(347)
0.151;-2050.6
J(347)
0.164;-2348.1
78(34)
0.155;-2698.8
(34)(7J)
0.177;-1583.1
8(348)
0.166;-1816.9
Q(348)
0.192;-2114.4
(34)(8T)
0.146;-1583.1
8(34K)
0.196;-1997.5
(349Q)
0.226;-1997.5
9(34J)
0.176;-2114.4
9K(34)
0.221;-1880.6
TT(34)
0.185;-1349.4
(34)(TK)
0.177;-998.7
J(34Q)
0.183;-1763.8
K(34Q)
0.196;-1530.0
44(35)
0.134;-2635.0
3447
0.177;-3166.3
34(4T)
0.162;-2050.6
44(3K)
0.181;-1700.0
4(357)
0.130;-3049.4
49(35)
0.166;-2815.6
(35)(4Q)
0.220;-1700.0
36(45)
0.136;-3166.3
3(459)
0.198;-2815.6
(45)(3Q)
0.216;-1700.0
35(46)
0.144;-3166.3
35(48)
0.181;-2932.5
35(4T)
0.183;-2698.8
35(4Q)
0.130;-2465.0
46(36)
0.169;-2284.4
(36)(49)
0.176;-1933.7
4(36Q)
0.190;-2348.1
3(467)
0.168;-2932.5
(46)(3T)
0.211;-1816.9
3Q(46)
0.150;-2348.1
3467
0.119;-3697.5
3469
0.136;-3463.8
346J
0.157;-3230.0
346K
0.194;-2996.2
49(37)
0.176;-2581.9
(37)(4Q)
0.230;-1466.2
38(47)
0.156;-2698.8
3(47J)
0.179;-2348.1
3477
0.165;-2815.6
3479
0.111;-3346.9
347J
0.126;-3113.1
347K
0.171;-2879.4
4T(38)
0.190;-2348.1
(38)(4K)
0.200;-1232.5
3T(48)
0.176;-2348.1
3(48K)
0.209;-1997.5
38(4T)
0.174;-2348.1
38(4Q)
0.222;-2114.4
49(39)
0.196;-1583.1
(39)(4Q)
0.211;-1232.5
3T(49)
0.166;-2231.2
3(49K)
0.210;-1880.6
39(4J)
0.159;-2114.4
39(4K)
0.167;-1880.6
4(3TQ)
0.195;-1880.6
3(4TJ)
0.174;-1997.5
34TT
0.220;-2114.4
34TQ
0.171;-2645.6
(3J)(4Q)
0.177;-998.7
3Q(4J)
0.196;-1763.8
34JQ
0.164;-2528.8
(3Q)(4K)
0.223;-765.0
3Q(4K)
0.194;-1530.0
5(356)
0.132;-2284.4
58(35)
0.181;-2050.6
(35)(5J)
0.236;-935.0
6(356)
0.201;-2167.5
T(356)
0.160;-2465.0
6(357)
0.120;-2815.6
69(35)
0.182;-2581.9
(35)(6Q)
0.194;-1466.2
(3579)
0.163;-2465.0
(357K)
0.144;-1997.5
79(35)
0.162;-2465.0
(35)(7Q)
0.231;-1349.4
(358T)
0.215;-2231.2
88(35)
0.215;-1700.0
(35)(8J)
0.227;-1349.4
9(359)
0.192;-1466.2
K(359)
0.248;-1763.8
9(35Q)
0.173;-1880.6
J(35T)
0.199;-1880.6
TJ(35)
0.217;-1880.6
(35JQ)
0.172;-1646.9
J(35K)
0.236;-1530.0
(35)(QK)
0.272;-648.1
55(37)
0.166;-2167.5
3559
0.141;-2698.8
35(5Q)
0.176;-1583.1
(36)(57)
0.165;-2050.6
5(36T)
0.212;-2465.0
5Q(36)
0.178;-2231.2
(56)(38)
0.194;-1933.7
3T(56)
0.167;-2465.0
3(56K)
0.176;-2114.4
36(58)
0.201;-2698.8
36(5T)
0.202;-2465.0
36(5Q)
0.137;-2231.2
57(37)
0.234;-1933.7
(37)(5T)
0.207;-1583.1
5(37K)
0.185;-1997.5
3(579)
0.190;-2465.0
(57)(3Q)
0.183;-1349.4
37(58)
0.164;-2581.9
37(5T)
0.172;-2348.1
37(5Q)
0.165;-2114.4
58(38)
0.199;-1700.0
(38)(5J)
0.162;-1349.4
38(58)
0.220;-1700.0
3(58J)
0.165;-2114.4
3588
0.180;-2465.0
358T
0.159;-2996.2
358Q
0.211;-2762.5
(39)(5T)
0.221;-1349.4
5(39K)
0.176;-1763.8
3(59J)
0.196;-1997.5
3599
0.177;-2231.2
359J
0.159;-2762.5
359K
0.180;-2528.8
5Q(3T)
0.199;-1763.8
(5T)(3Q)
0.206;-998.7
3T(5J)
0.148;-1880.6
3T(5K)
0.151;-1646.9
5(3JK)
0.229;-1530.0
3(5JK)
0.204;-1530.0
3J(5K)
0.160;-1530.0
3Q(5Q)
0.238;-765.0
35QK
0.159;-2178.1
67(36)
0.163;-1933.7
(36)(6T)
0.269;-818.1
6(36K)
0.174;-1232.5
(367T)
0.162;-2231.2
77(36)
0.182;-1816.9
(36)(7T)
0.207;-1466.2
7(36K)
0.178;-1880.6
(368J)
0.185;-1997.5
(36)(89)
0.183;-1466.2
8(36Q)
0.184;-1880.6
T(369)
0.227;-1997.5
9(36T)
0.192;-1997.5
9Q(36)
0.227;-1763.8
Q(36T)
0.194;-1646.9
(36)(TQ)
0.199;-881.9
(36JK)
0.189;-1413.1
JK(36)
0.226;-1413.1
K(36K)
0.229;-414.4
3668
0.168;-2581.9
36(6J)
0.218;-1466.2
(37)(67)
0.250;-1051.9
6(37T)
0.169;-2231.2
6Q(37)
0.196;-1997.5
(67)(39)
0.236;-1583.1
3J(67)
0.225;-2114.4
67(38)
0.194;-2465.0
67(3T)
0.188;-2231.2
67(3Q)
0.213;-1997.5
(38)(68)
0.227;-818.1
6(38J)
0.171;-1997.5
6K(38)
0.214;-1763.8
(68)(3J)
0.205;-1232.5
3K(68)
0.202;-1763.8
36(8T)
0.174;-2114.4
36(8Q)
0.173;-1880.6
6(39T)
0.169;-1997.5
6Q(39)
0.183;-1763.8
(69)(3J)
0.242;-1115.6
3K(69)
0.157;-1646.9
36(9J)
0.180;-1880.6
36(9K)
0.212;-1646.9
(3T)(6Q)
0.227;-881.9
3J(6T)
0.221;-1763.8
6T(3J)
0.230;-1763.8
6T(3K)
0.168;-1530.0
6Q(3J)
0.206;-1530.0
(6J)(3K)
0.194;-648.1
6J(3K)
0.209;-1413.1
6K(3Q)
0.173;-1296.2
36(QK)
0.225;-1296.2
(37)(78)
0.226;-818.1
7(37J)
0.251;-1232.5
7K(37)
0.244;-998.7
(378Q)
0.198;-1763.8
8(37T)
0.178;-1997.5
8Q(37)
0.200;-1763.8
J(379)
0.234;-1763.8
9T(37)
0.187;-1880.6
(37)(9K)
0.198;-765.0
K(37T)
0.166;-1413.1
T(37K)
0.233;-1413.1
JJ(37)
0.246;-765.0
(37QK)
0.213;-1179.4
3777
0.201;-1700.0
37(7T)
0.192;-1349.4
77(3K)
0.251;-998.7
7(38T)
0.189;-1997.5
7Q(38)
0.144;-1763.8
(78)(3T)
0.197;-1232.5
3Q(78)
0.159;-1763.8
3789
0.151;-2879.4
378J
0.143;-2645.6
378K
0.147;-2411.9
7J(39)
0.176;-1763.8
(79)(3T)
0.186;-1115.6
3Q(79)
0.210;-1646.9
379T
0.187;-2645.6
379Q
0.156;-2411.9
(3T)(7J)
0.208;-881.9
3T(7T)
0.169;-998.7
3(7TK)
0.197;-1413.1
3T(7Q)
0.228;-1530.0
7J(3J)
0.241;-765.0
(7J)(3Q)
0.224;-648.1
3J(7Q)
0.232;-1413.1
7Q(3Q)
0.228;-531.2
37QQ
0.263;-1296.2
37KK
0.186;-1062.5
8(38J)
0.240;-998.7
8K(38)
0.226;-765.0
(389K)
0.176;-1413.1
9J(38)
0.219;-1646.9
(38TJ)
0.194;-1530.0
(38)(TJ)
0.274;-765.0
J(38J)
0.214;-648.1
JQ(38)
0.243;-1296.2
Q(38K)
0.215;-1062.5
3889
0.167;-1997.5
38(8Q)
0.276;-881.9
(39)(8T)
0.219;-998.7
8(39K)
0.205;-1413.1
3(89J)
0.154;-1646.9
3899
0.171;-1880.6
389J
0.136;-2411.9
389K
0.181;-2178.1
8Q(3T)
0.180;-1413.1
(8T)(3Q)
0.252;-648.1
3T(8J)
0.219;-1530.0
3T(8K)
0.244;-1296.2
8(3JK)
0.190;-1179.4
3(8JK)
0.161;-1179.4
3J(8K)
0.189;-1179.4
3Q(8Q)
0.216;-414.4
38QK
0.193;-1827.5
9T(39)
0.220;-881.9
(39)(9K)
0.250;233.8
K(39T)
0.195;-1179.4
T(39K)
0.211;-1179.4
JJ(39)
0.229;-531.2
(39QK)
0.191;-945.6
3999
0.224;-998.7
39(9Q)
0.242;-648.1
(3T)(9J)
0.217;-648.1
3T(9T)
0.232;-765.0
3(9TK)
0.205;-1179.4
3T(9Q)
0.194;-1296.2
9J(3J)
0.203;-531.2
(9J)(3Q)
0.209;-414.4
3J(9Q)
0.227;-1179.4
9Q(3Q)
0.252;-297.5
39QQ
0.201;-1062.5
39KK
0.243;-828.7
T(3TK)
0.195;-297.5
JJ(3T)
0.186;-414.4
(3TQK)
0.208;-828.7
3TTT
0.261;-648.1
3T(TK)
0.265;-297.5
(3J)(TK)
0.234;-180.6
3K(TJ)
0.214;-945.6
3T(JK)
0.253;-945.6
(TQ)(3K)
0.222;-63.7
(3K)(TK)
0.306;818.1
J(3JK)
0.216;-63.7
(3J)(QK)
0.239;53.1
JJ(3K)
0.258;-63.7
3Q(JQ)
0.224;-63.7
3JQK
0.172;-1476.9
QK(3Q)
0.214;170.0
QK(3K)
0.239;286.9
44(46)
0.218;-1636.2
44(4T)
0.252;-1168.7
(45)(45)
0.235;-871.3
4(458)
0.153;-2050.6
4T(45)
0.234;-1816.9
(45)(4K)
0.197;-701.2
4457
0.176;-2932.5
44(5T)
0.174;-1816.9
45(4K)
0.245;-1466.2
4(468)
0.166;-1933.7
4T(46)
0.228;-1700.0
(46)(4K)
0.205;-584.4
4468
0.193;-2698.8
44(6J)
0.166;-1583.1
(47)(47)
0.249;-403.7
4(47T)
0.188;-1583.1
4Q(47)
0.195;-1349.4
47(49)
0.251;-1700.0
447J
0.146;-2231.2
48(48)
0.267;-935.0
(48)(4J)
0.275;-584.4
4488
0.158;-1700.0
44(8J)
0.202;-1349.4
(49)(49)
0.220;63.7
4(49Q)
0.252;-1115.6
44(9T)
0.223;-1349.4
49(4K)
0.252;-998.7
4(4TQ)
0.221;-998.7
44(TJ)
0.247;-1115.6
(4J)(4J)
0.255;531.3
44JJ
0.172;-998.7
4Q(4Q)
0.235;0.0
(4K)(4K)
0.231;998.7
(45)(57)
0.255;-1285.6
5(45T)
0.175;-1700.0
5Q(45)
0.188;-1466.2
8(456)
0.209;-2581.9
Q(456)
0.166;-2114.4
(45)(68)
0.211;-1816.9
6(45J)
0.215;-2231.2
6K(45)
0.176;-1997.5
(457J)
0.174;-2114.4
(45)(78)
0.182;-1700.0
7(45J)
0.238;-2114.4
7K(45)
0.251;-1880.6
(458Q)
0.211;-1880.6
8(45T)
0.149;-2114.4
8Q(45)
0.180;-1880.6
J(459)
0.168;-1880.6
9T(45)
0.194;-1997.5
(45)(9K)
0.232;-881.9
K(45T)
0.198;-1530.0
T(45K)
0.195;-1530.0
JJ(45)
0.166;-881.9
(45QK)
0.231;-1296.2
4555
0.162;-2284.4
45(58)
0.163;-1933.7
55(4J)
0.194;-1583.1
455K
0.149;-2114.4
58(46)
0.190;-2581.9
(46)(5J)
0.205;-1466.2
46(56)
0.173;-2050.6
4(569)
0.175;-2465.0
(56)(4Q)
0.174;-1349.4
46(57)
0.139;-2698.8
46(59)
0.173;-2465.0
46(5J)
0.174;-2231.2
46(5K)
0.143;-1997.5
5(479)
0.155;-2348.1
5J(47)
0.166;-2114.4
(57)(48)
0.191;-1700.0
4T(57)
0.192;-2231.2
4(57K)
0.236;-1880.6
47(59)
0.140;-2348.1
47(5J)
0.186;-2114.4
47(5K)
0.154;-1880.6
5(48T)
0.178;-2114.4
5Q(48)
0.191;-1880.6
(58)(4T)
0.188;-1349.4
4Q(58)
0.172;-1880.6
4589
0.140;-2996.2
458J
0.175;-2762.5
458K
0.206;-2528.8
5J(49)
0.186;-1880.6
(59)(4T)
0.181;-1232.5
4Q(59)
0.188;-1763.8
459T
0.205;-2762.5
459Q
0.163;-2528.8
(4T)(5J)
0.228;-998.7
4T(5T)
0.203;-1115.6
4(5TK)
0.191;-1530.0
4T(5Q)
0.214;-1646.9
5J(4J)
0.255;-881.9
(5J)(4Q)
0.230;-765.0
4J(5Q)
0.171;-1530.0
5Q(4Q)
0.214;-648.1
45QQ
0.201;-1413.1
45KK
0.240;-1179.4
6(469)
0.199;-1583.1
6J(46)
0.206;-1349.4
(4678)
0.178;-2348.1
(467Q)
0.193;-1880.6
7(469)
0.169;-2231.2
7J(46)
0.211;-1997.5
(4689)
0.218;-2114.4
(468K)
0.202;-1646.9
8T(46)
0.173;-1997.5
(46)(8K)
0.242;-881.9
Q(469)
0.193;-1646.9
(46)(9J)
0.233;-998.7
T(46T)
0.157;-998.7
T(46J)
0.201;-1646.9
TK(46)
0.202;-1413.1
(46)(JQ)
0.194;-648.1
QQ(46)
0.217;-531.2
46(67)
0.211;-1816.9
66(4T)
0.207;-1466.2
466Q
0.186;-1997.5
68(47)
0.220;-2348.1
(47)(6J)
0.206;-1232.5
47(67)
0.163;-1700.0
4(67T)
0.180;-2114.4
(67)(4K)
0.193;-998.7
67(49)
0.162;-2231.2
67(4J)
0.173;-1997.5
67(4K)
0.161;-1763.8
69(48)
0.230;-2114.4
(48)(6Q)
0.223;-998.7
49(68)
0.175;-2114.4
4(68Q)
0.174;-1763.8
46(89)
0.162;-2114.4
46(8J)
0.184;-1880.6
46(8K)
0.226;-1646.9
(49)(6J)
0.249;-998.7
49(69)
0.254;-1232.5
4(69Q)
0.183;-1646.9
46(9T)
0.218;-1880.6
46(9Q)
0.172;-1646.9
6(4TJ)
0.149;-1646.9
6K(4T)
0.162;-1413.1
(6T)(4K)
0.169;-648.1
6T(4Q)
0.195;-1530.0
(4J)(6J)
0.213;0.0
4J(6J)
0.223;-765.0
6J(4Q)
0.228;-1413.1
(4Q)(6Q)
0.261;233.8
4K(6Q)
0.166;-1179.4
4K(6K)
0.219;-297.5
79(47)
0.166;-1349.4
(47)(7Q)
0.217;-233.8
(478T)
0.195;-1880.6
88(47)
0.194;-1349.4
(47)(8J)
0.241;-998.7
9(479)
0.186;-1115.6
K(479)
0.166;-1413.1
9(47Q)
0.190;-1530.0
J(47T)
0.171;-1530.0
TJ(47)
0.197;-1530.0
(47JQ)
0.198;-1296.2
J(47K)
0.202;-1179.4
(47)(QK)
0.208;-297.5
77(49)
0.168;-1349.4
477J
0.195;-1880.6
78(48)
0.197;-1349.4
(48)(7J)
0.211;-998.7
48(78)
0.233;-1349.4
4(78J)
0.241;-1763.8
4788
0.224;-2114.4
478T
0.163;-2645.6
478Q
0.168;-2411.9
(49)(7T)
0.191;-998.7
7(49K)
0.188;-1413.1
4(79J)
0.191;-1646.9
4799
0.238;-1880.6
479J
0.172;-2411.9
479K
0.147;-2178.1
7Q(4T)
0.220;-1413.1
(7T)(4Q)
0.250;-648.1
4T(7J)
0.211;-1530.0
4T(7K)
0.157;-1296.2
7(4JK)
0.192;-1179.4
4(7JK)
0.205;-1179.4
4J(7K)
0.203;-1179.4
4Q(7Q)
0.186;-414.4
47QK
0.164;-1827.5
89(48)
0.190;-1115.6
(48)(8Q)
0.219;0.0
(489J)
0.202;-1530.0
(48)(9T)
0.208;-881.9
9(48K)
0.228;-1296.2
(48TK)
0.232;-1179.4
TQ(48)
0.250;-1296.2
K(48J)
0.182;-1062.5
Q(48Q)
0.189;-297.5
KK(48)
0.214;-63.7
88(4J)
0.237;-881.9
488K
0.230;-1413.1
8J(49)
0.227;-1530.0
(89)(4T)
0.223;-881.9
4Q(89)
0.236;-1413.1
489T
0.162;-2411.9
489Q
0.196;-2178.1
(4T)(8J)
0.225;-648.1
4T(8T)
0.192;-765.0
4(8TK)
0.216;-1179.4
4T(8Q)
0.193;-1296.2
8J(4J)
0.249;-531.2
(8J)(4Q)
0.277;-414.4
4J(8Q)
0.182;-1179.4
8Q(4Q)
0.237;-297.5
48QQ
0.228;-1062.5
48KK
0.189;-828.7
9(49Q)
0.231;-531.2
J(49T)
0.170;-1296.2
TJ(49)
0.190;-1296.2
(49JQ)
0.251;-1062.5
J(49K)
0.189;-945.6
(49)(QK)
0.240;-63.7
99(4J)
0.241;-648.1
499K
0.213;-1179.4
9Q(4T)
0.214;-1179.4
(9T)(4Q)
0.205;-414.4
4T(9J)
0.195;-1296.2
4T(9K)
0.193;-1062.5
9(4JK)
0.233;-945.6
4(9JK)
0.177;-945.6
4J(9K)
0.192;-945.6
4Q(9Q)
0.253;-180.6
49QK
0.165;-1593.8
TJ(4T)
0.245;-414.4
(4TJQ)
0.216;-945.6
J(4TK)
0.159;-828.7
(4T)(QK)
0.267;53.1
TT(4Q)
0.290;-297.5
T(4JQ)
0.226;-945.6
4(TJQ)
0.216;-945.6
4T(JQ)
0.187;-945.6
T(4QK)
0.235;-711.9
TQ(4K)
0.206;-711.9
JJ(4J)
0.231;584.4
(4JQK)
0.167;-595.0
4JJJ
0.274;-180.6
JQ(4Q)
0.249;53.1
4JQQ
0.266;-711.9
4JKK
0.275;-478.1
QQ(4K)
0.258;286.9
4KKK
0.263;520.6
55(59)
0.221;-935.0
55(5K)
0.212;-467.5
(56)(58)
0.265;-935.0
5(56J)
0.176;-1349.4
5K(56)
0.201;-1115.6
56(59)
0.203;-1583.1
556J
0.181;-2114.4
57(57)
0.242;-935.0
(57)(5T)
0.219;-584.4
5(57K)
0.211;-998.7
55(79)
0.211;-1466.2
57(5Q)
0.218;-1115.6
5(589)
0.208;-1349.4
5J(58)
0.184;-1115.6
58(59)
0.210;-1349.4
558J
0.227;-1880.6
59(59)
0.232;-467.5
(59)(5Q)
0.241;-116.9
559T
0.144;-1880.6
55(9K)
0.207;-765.0
(5T)(5Q)
0.270;0.0
55TJ
0.162;-1646.9
5J(5J)
0.290;0.0
5J(5Q)
0.226;-648.1
5(5QK)
0.252;-414.4
5K(5K)
0.230;467.5
68(56)
0.170;-1583.1
(56)(6J)
0.204;-467.5
7(567)
0.194;-1583.1
J(567)
0.187;-1880.6
78(56)
0.174;-2231.2
(56)(7J)
0.177;-1115.6
8(568)
0.228;-1349.4
Q(568)
0.200;-1646.9
(56)(8T)
0.233;-1115.6
8(56K)
0.208;-1530.0
(569Q)
0.196;-1530.0
9(56J)
0.231;-1646.9
9K(56)
0.213;-1413.1
TT(56)
0.196;-881.9
(56)(TK)
0.234;-531.3
J(56Q)
0.181;-1296.2
K(56Q)
0.238;-1062.5
66(57)
0.203;-1700.0
5669
0.178;-2231.2
56(6Q)
0.173;-1115.6
(57)(68)
0.190;-1466.2
6(57J)
0.182;-1880.6
6K(57)
0.155;-1646.9
(67)(5T)
0.189;-1232.5
5Q(67)
0.192;-1763.8
5678
0.170;-2996.2
567T
0.190;-2762.5
567Q
0.145;-2528.8
(58)(69)
0.225;-1232.5
6(58Q)
0.208;-1646.9
5(689)
0.231;-1997.5
(68)(5Q)
0.205;-881.9
58(69)
0.178;-1997.5
58(6J)
0.197;-1763.8
58(6K)
0.215;-1530.0
6(59J)
0.183;-1646.9
6K(59)
0.221;-1413.1
(69)(5Q)
0.288;-765.0
59(6T)
0.195;-1763.8
59(6Q)
0.231;-1530.0
6T(5T)
0.208;-881.9
(5T)(6K)
0.255;-531.3
5Q(6T)
0.248;-1413.1
56TJ
0.182;-2295.0
56TK
0.160;-2061.2
6K(5J)
0.228;-1179.4
56JJ
0.197;-1413.1
56JK
0.179;-1944.4
5(6QK)
0.230;-1062.5
6K(5K)
0.255;-180.6
(57)(79)
0.212;-467.5
7(57Q)
0.216;-881.9
9(578)
0.173;-1880.6
K(578)
0.210;-1413.1
8(57J)
0.192;-1646.9
8K(57)
0.249;-1413.1
(579K)
0.168;-1296.2
9J(57)
0.171;-1530.0
(57TJ)
0.190;-1413.1
(57)(TJ)
0.221;-648.1
J(57J)
0.240;-531.2
JQ(57)
0.202;-1179.4
Q(57K)
0.221;-945.6
5778
0.163;-2114.4
57(7J)
0.177;-998.7
(58)(78)
0.285;-467.5
7(58J)
0.203;-1646.9
7K(58)
0.202;-1413.1
(78)(5J)
0.175;-881.9
5K(78)
0.197;-1413.1
57(8T)
0.225;-1763.8
57(8Q)
0.228;-1530.0
7(59T)
0.181;-1646.9
7Q(59)
0.200;-1413.1
(79)(5J)
0.273;-765.0
5K(79)
0.240;-1296.2
57(9J)
0.200;-1530.0
57(9K)
0.216;-1296.2
(5T)(7Q)
0.257;-531.3
5J(7T)
0.226;-1413.1
7T(5J)
0.207;-1413.1
7T(5K)
0.187;-1179.4
7Q(5J)
0.205;-1179.4
(7J)(5K)
0.230;-297.5
7J(5K)
0.222;-1062.5
7K(5Q)
0.172;-945.6
57(QK)
0.254;-945.6
(58)(89)
0.233;-233.8
8(58Q)
0.252;-648.1
T(589)
0.225;-1530.0
9(58T)
0.197;-1530.0
9Q(58)
0.207;-1296.2
Q(58T)
0.223;-1179.4
(58)(TQ)
0.263;-414.4
(58JK)
0.229;-945.6
JK(58)
0.193;-945.6
K(58K)
0.279;53.1
588T
0.210;-1646.9
58(8K)
0.244;-531.2
(59)(8J)
0.219;-648.1
59(89)
0.221;-881.9
5(89Q)
0.218;-1296.2
58(9T)
0.163;-1530.0
58(9Q)
0.194;-1296.2
8(5TJ)
0.239;-1296.2
8K(5T)
0.255;-1062.5
(8T)(5K)
0.243;-297.5
8T(5Q)
0.209;-1179.4
(5J)(8J)
0.228;350.6
5J(8J)
0.256;-414.4
8J(5Q)
0.181;-1062.5
(5Q)(8Q)
0.272;584.4
5K(8Q)
0.190;-828.7
5K(8K)
0.227;53.1
9J(59)
0.180;-531.2
(59TJ)
0.207;-1179.4
(59)(TJ)
0.208;-414.4
J(59J)
0.222;-297.5
JQ(59)
0.246;-945.6
Q(59K)
0.209;-711.9
599T
0.249;-1413.1
59(9K)
0.208;-297.5
(5T)(9Q)
0.248;-297.5
5J(9T)
0.189;-1179.4
9T(5J)
0.231;-1179.4
9T(5K)
0.247;-945.6
9Q(5J)
0.236;-945.6
(9J)(5K)
0.239;-63.7
9J(5K)
0.231;-828.7
9K(5Q)
0.238;-711.9
59(QK)
0.238;-711.9
(5T)(TJ)
0.233;467.5
J(5TJ)
0.232;-180.6
JQ(5T)
0.198;-828.7
Q(5TK)
0.235;-595.0
5TTJ
0.213;-1062.5
TJ(5J)
0.249;-180.6
(TJ)(5Q)
0.244;-63.7
5J(TQ)
0.228;-828.7
TQ(5Q)
0.259;53.1
5TQQ
0.191;-711.9
5TKK
0.288;-478.1
Q(5JQ)
0.282;170.0
KK(5J)
0.255;403.8
(5Q)(JQ)
0.250;935.0
5K(JQ)
0.208;-478.1
5K(JK)
0.222;403.8
5QQQ
0.254;286.9
KK(5K)
0.251;1402.5
6669
0.231;-1349.4
666K
0.271;-881.9
69(67)
0.210;-1232.5
(67)(6Q)
0.286;-116.9
6678
0.157;-2114.4
66(7J)
0.237;-998.7
(68)(68)
0.205;297.5
6(68J)
0.221;-881.9
6K(68)
0.229;-648.1
68(6J)
0.207;-881.9
668K
0.191;-1413.1
6J(69)
0.185;-765.0
69(6T)
0.190;-881.9
669Q
0.238;-1413.1
6J(6T)
0.247;-648.1
6T(6J)
0.223;-648.1
66TK
0.229;-1179.4
6K(6J)
0.231;-297.5
(6Q)(6Q)
0.291;1232.5
66QK
0.184;-945.6
7(679)
0.186;-1115.6
7J(67)
0.190;-881.9
(6789)
0.175;-1763.8
(678K)
0.158;-1296.2
8T(67)
0.223;-1646.9
(67)(8K)
0.223;-531.3
Q(679)
0.195;-1296.2
(67)(9J)
0.240;-648.1
T(67T)
0.245;-648.1
T(67J)
0.200;-1296.2
TK(67)
0.205;-1062.5
(67)(JQ)
0.223;-297.5
QQ(67)
0.226;-180.6
67(78)
0.253;-1232.5
77(6J)
0.234;-881.9
677K
0.177;-1413.1
7T(68)
0.219;-1646.9
(68)(7K)
0.234;-531.3
6T(78)
0.143;-1646.9
6(78K)
0.193;-1296.2
68(7T)
0.210;-1646.9
68(7Q)
0.189;-1413.1
79(69)
0.226;-881.9
(69)(7Q)
0.252;-531.3
6T(79)
0.204;-1530.0
6(79K)
0.194;-1179.4
69(7J)
0.220;-1413.1
69(7K)
0.187;-1179.4
7(6TQ)
0.217;-1179.4
6(7TJ)
0.180;-1296.2
67TT
0.150;-1413.1
67TQ
0.203;-1944.4
(6J)(7Q)
0.248;-297.5
6Q(7J)
0.182;-1062.5
67JQ
0.231;-1827.5
(6Q)(7K)
0.245;-63.7
6Q(7K)
0.245;-828.7
8(689)
0.245;-881.9
8J(68)
0.253;-648.1
(689T)
0.161;-1413.1
99(68)
0.204;-765.0
(68)(9Q)
0.203;-414.4
(68TQ)
0.199;-1062.5
T(68Q)
0.240;-1062.5
Q(68J)
0.203;-945.6
(68)(JK)
0.273;-63.7
QK(68)
0.223;-711.9
68(8T)
0.241;-765.0
88(6K)
0.209;-414.4
8(69J)
0.220;-1296.2
8K(69)
0.238;-1062.5
(89)(6Q)
0.190;-414.4
69(8T)
0.199;-1413.1
69(8Q)
0.232;-1179.4
8T(6T)
0.211;-531.2
(6T)(8K)
0.228;-180.6
6Q(8T)
0.265;-1062.5
68TJ
0.154;-1944.4
68TK
0.171;-1710.6
8K(6J)
0.182;-828.7
68JJ
0.223;-1062.5
68JK
0.218;-1593.8
6(8QK)
0.239;-711.9
8K(6K)
0.215;170.0
(69)(9J)
0.291;350.6
T(69T)
0.248;-414.4
T(69J)
0.215;-1062.5
TK(69)
0.262;-828.7
(69)(JQ)
0.222;-63.7
QQ(69)
0.316;53.1
69(9T)
0.225;-531.2
99(6K)
0.223;-180.6
9(6TQ)
0.216;-945.6
6(9TJ)
0.180;-1062.5
69TT
0.220;-1179.4
69TQ
0.148;-1710.6
(6J)(9Q)
0.263;-63.7
6Q(9J)
0.266;-828.7
69JQ
0.204;-1593.8
(6Q)(9K)
0.241;170.0
6Q(9K)
0.252;-595.0
T(6TJ)
0.274;-180.6
TK(6T)
0.241;53.1
(6T)(JQ)
0.232;53.1
QQ(6T)
0.234;170.0
6T(TJ)
0.288;-180.6
(6J)(TJ)
0.261;701.2
6J(TJ)
0.247;-63.7
TJ(6Q)
0.209;-711.9
(6Q)(TQ)
0.271;935.0
6K(TQ)
0.215;-478.1
6K(TK)
0.234;403.8
JK(6J)
0.260;286.9
K(6JK)
0.280;520.6
6JJK
0.203;-478.1
6(JQK)
0.242;-361.2
JK(6K)
0.322;520.6
KK(6Q)
0.285;637.5
6QKK
0.231;-127.5
77(7T)
0.232;-116.9
(78)(78)
0.270;531.3
7(78J)
0.231;-648.1
7K(78)
0.220;-414.4
78(7J)
0.242;-648.1
778K
0.238;-1179.4
7J(79)
0.279;-531.2
79(7T)
0.221;-648.1
779Q
0.235;-1179.4
7J(7T)
0.185;-414.4
7T(7J)
0.203;-414.4
77TK
0.228;-945.6
7K(7J)
0.296;-63.7
(7Q)(7Q)
0.323;1466.3
77QK
0.215;-711.9
8(78T)
0.191;-648.1
8Q(78)
0.208;-414.4
J(789)
0.157;-1179.4
9T(78)
0.214;-1296.2
(78)(9K)
0.206;-180.6
K(78T)
0.261;-828.7
T(78K)
0.182;-828.7
JJ(78)
0.253;-180.6
(78QK)
0.210;-595.0
7888
0.198;-881.9
78(8J)
0.186;-531.2
(79)(89)
0.255;116.9
8(79Q)
0.214;-1062.5
7(89T)
0.190;-1296.2
(89)(7K)
0.246;-180.6
89(7J)
0.172;-1179.4
89(7K)
0.168;-945.6
8J(7T)
0.211;-1062.5
(8T)(7J)
0.237;-297.5
7K(8T)
0.251;-828.7
78(TQ)
0.190;-945.6
8(7JQ)
0.233;-828.7
7(8JQ)
0.232;-828.7
78(JQ)
0.181;-828.7
8(7QK)
0.224;-595.0
8Q(7K)
0.266;-595.0
99(79)
0.252;233.7
(79)(9Q)
0.236;584.4
(79TQ)
0.233;-828.7
T(79Q)
0.168;-828.7
Q(79J)
0.210;-711.9
(79)(JK)
0.278;170.0
QK(79)
0.213;-478.1
79(9J)
0.220;-297.5
(7T)(9T)
0.220;467.5
9(7TK)
0.181;-711.9
7(9TQ)
0.270;-828.7
79(TJ)
0.216;-945.6
79(TK)
0.218;-711.9
(7J)(9K)
0.279;170.0
7K(9J)
0.232;-595.0
79(JK)
0.274;-595.0
(9Q)(7K)
0.229;286.9
(7K)(9K)
0.322;1168.8
T(7TQ)
0.300;53.1
Q(7TJ)
0.231;-595.0
(7T)(JK)
0.232;286.9
QK(7T)
0.178;-361.2
7T(TQ)
0.289;53.1
(7J)(TQ)
0.248;170.0
7Q(TJ)
0.170;-595.0
7TJQ
0.173;-1360.0
(7Q)(TK)
0.273;403.8
7Q(TK)
0.187;-361.2
J(7JQ)
0.237;286.9
K(7JQ)
0.240;-244.4
JJ(7Q)
0.307;286.9
J(7QK)
0.180;-244.4
JQ(7K)
0.244;-244.4
QQ(7Q)
0.270;1285.6
7Q(QK)
0.224;637.5
8888
0.210;0.0
888Q
0.211;-297.5
8(89J)
0.213;-297.5
8K(89)
0.183;-63.7
89(8Q)
0.249;-180.6
8(8TJ)
0.255;-180.6
8K(8T)
0.255;53.1
8T(8K)
0.268;53.1
8(8JK)
0.290;170.0
88(JK)
0.206;170.0
8Q(8K)
0.227;286.9
(89)(9T)
0.304;467.5
9(89K)
0.266;53.1
(89TK)
0.216;-595.0
TQ(89)
0.232;-711.9
K(89J)
0.289;-478.1
Q(89Q)
0.265;286.9
KK(89)
0.235;520.6
99(8Q)
0.250;-63.7
9(8TJ)
0.215;-828.7
9K(8T)
0.223;-595.0
(9T)(8K)
0.221;170.0
9T(8Q)
0.236;-711.9
(8J)(9J)
0.315;818.1
8J(9J)
0.281;53.1
9J(8Q)
0.230;-595.0
(8Q)(9Q)
0.265;1051.9
8K(9Q)
0.188;-361.2
8K(9K)
0.305;520.6
TQ(8T)
0.287;170.0
K(8TJ)
0.235;-361.2
Q(8TQ)
0.249;403.8
KK(8T)
0.278;637.5
