AAAA
0.428;495.0
5AAA
0.344;174.4
9AAA
0.397;256.9
KAAA
0.311;339.4
4A(2A)
0.353;-93.7
(2A)(7A)
0.379;103.1
A(2TA)
0.340;30.0
QA(2A)
0.336;71.3
2A(4A)
0.295;-93.7
26AA
0.307;-187.5
AA(29)
0.308;9.4
2A(QA)
0.352;71.3
A(34A)
0.286;-73.1
6A(3A)
0.340;-31.9
(3A)(9A)
0.381;165.0
A(3QA)
0.345;91.9
AA(34)
0.315;-73.1
3A(7A)
0.309;-11.2
39AA
0.273;-105.0
AA(3Q)
0.362;91.9
(4A)(5A)
0.334;103.1
A(48A)
0.276;30.0
TA(4A)
0.315;71.3
(4A)(KA)
0.400;268.1
46AA
0.313;-146.2
AA(49)
0.302;50.6
4A(QA)
0.355;112.5
A(56A)
0.293;9.4
8A(5A)
0.346;50.6
(5A)(JA)
0.338;247.5
55AA
0.352;-11.2
AA(58)
0.356;50.6
5A(JA)
0.340;112.5
5KAA
0.339;18.7
8A(6A)
0.377;71.3
(6A)(JA)
0.356;268.1
66AA
0.348;30.0
AA(69)
0.324;91.9
6A(QA)
0.327;153.7
A(78A)
0.344;91.9
TA(7A)
0.291;133.1
(7A)(KA)
0.411;330.0
79AA
0.297;-22.5
AA(7Q)
0.397;174.4
(8A)(9A)
0.312;268.1
A(8QA)
0.409;195.0
AA(89)
0.361;133.1
8A(QA)
0.399;195.0
A(9TA)
0.407;174.4
QA(9A)
0.381;215.6
9A(JA)
0.428;195.0
9KAA
0.297;101.3
QA(TA)
0.399;236.2
TA(QA)
0.427;236.2
A(JQA)
0.336;256.9
AA(JQ)
0.324;256.9
(QA)(KA)
0.424;433.1
KKAA
0.387;318.8
2(25A)
0.259;-320.6
27(2A)
0.313;-279.4
(2T)(2A)
0.390;-82.5
2(2KA)
0.367;-155.6
(236A)
0.312;-414.4
(23TA)
0.271;-331.9
33(2A)
0.237;-341.2
(36)(2A)
0.301;-279.4
3(29A)
0.300;-352.5
3J(2A)
0.257;-311.2
(245A)
0.301;-414.4
(249A)
0.268;-331.9
(24KA)
0.323;-249.4
46(2A)
0.296;-393.8
(49)(2A)
0.278;-196.9
4(2QA)
0.269;-270.0
6(25A)
0.291;-373.1
T(25A)
0.293;-290.6
5(26A)
0.342;-373.1
58(2A)
0.280;-331.9
(5J)(2A)
0.267;-135.0
6(26A)
0.288;-217.5
T(26A)
0.337;-270.0
6(27A)
0.296;-331.9
69(2A)
0.305;-290.6
(6Q)(2A)
0.333;-93.8
(279A)
0.305;-270.0
(27KA)
0.274;-187.5
79(2A)
0.355;-270.0
(7Q)(2A)
0.332;-73.1
(28TA)
0.337;-228.7
88(2A)
0.331;-135.0
(8J)(2A)
0.357;-73.1
9(29A)
0.288;-93.7
K(29A)
0.307;-146.2
9(2QA)
0.330;-166.9
J(2TA)
0.254;-166.9
TJ(2A)
0.345;-166.9
(2JQA)
0.329;-125.6
J(2KA)
0.377;-105.0
(QK)(2A)
0.357;50.6
22(4A)
0.266;-341.2
226A
0.264;-435.0
2A(29)
0.315;-238.1
22(QA)
0.349;-176.2
2(34A)
0.297;-455.6
26(3A)
0.228;-414.4
(29)(3A)
0.320;-217.5
2(3QA)
0.326;-290.6
A(234)
0.257;-455.6
(23)(7A)
0.292;-258.8
9A(23)
0.296;-352.5
A(23Q)
0.332;-290.6
2A(34)
0.306;-455.6
2A(36)
0.344;-414.4
2A(38)
0.329;-373.1
2A(3T)
0.331;-331.9
2A(3Q)
0.265;-290.6
2(45A)
0.345;-414.4
27(4A)
0.284;-373.1
(2T)(4A)
0.351;-176.2
2(4KA)
0.295;-249.4
A(246)
0.261;-393.8
(24)(9A)
0.260;-196.9
JA(24)
0.280;-290.6
24(5A)
0.237;-414.4
24(7A)
0.264;-373.1
24(9A)
0.255;-331.9
24(JA)
0.329;-290.6
24(KA)
0.348;-249.4
26(5A)
0.285;-373.1
(29)(5A)
0.303;-176.2
2(5QA)
0.323;-249.4
A(256)
0.227;-373.1
(25)(9A)
0.292;-176.2
JA(25)
0.380;-270.0
25(6A)
0.261;-373.1
25(8A)
0.267;-331.9
25(TA)
0.286;-290.6
25(QA)
0.276;-249.4
(26)(6A)
0.377;-82.5
2(69A)
0.249;-290.6
2J(6A)
0.266;-249.4
(26)(7A)
0.332;-196.9
9A(26)
0.237;-290.6
A(26Q)
0.279;-228.7
2A(67)
0.334;-331.9
2A(69)
0.321;-290.6
2A(6J)
0.361;-249.4
2A(6K)
0.261;-208.1
(29)(7A)
0.293;-135.0
2(7QA)
0.269;-208.1
A(278)
0.274;-290.6
(27)(JA)
0.366;-93.8
KA(27)
0.320;-187.5
2A(79)
0.368;-270.0
2A(7J)
0.314;-228.7
2A(7K)
0.312;-187.5
(2T)(8A)
0.371;-93.8
2(8KA)
0.343;-166.9
A(28T)
0.303;-228.7
(28)(KA)
0.313;-31.9
28(TA)
0.262;-228.7
28(QA)
0.271;-187.5
(29)(9A)
0.399;41.3
2(9QA)
0.327;-166.9
A(29T)
0.354;-208.1
(29)(KA)
0.290;-11.2
29(JA)
0.311;-187.5
29(KA)
0.301;-146.2
2J(TA)
0.337;-166.9
(2T)(JA)
0.340;-31.9
KA(2T)
0.259;-125.6
2A(TQ)
0.323;-146.2
2(JQA)
0.252;-125.6
A(2JQ)
0.372;-125.6
2A(JQ)
0.331;-125.6
2(QKA)
0.297;-84.4
2Q(KA)
0.289;-84.4
33(3A)
0.304;-185.6
(36)(3A)
0.314;-123.7
3(39A)
0.391;-196.9
3J(3A)
0.391;-155.6
(345A)
0.279;-393.8
(349A)
0.278;-311.2
(34KA)
0.248;-228.7
46(3A)
0.315;-373.1
(49)(3A)
0.335;-176.2
4(3QA)
0.321;-249.4
6(35A)
0.283;-352.5
T(35A)
0.289;-270.0
5(36A)
0.284;-352.5
58(3A)
0.316;-311.2
(5J)(3A)
0.322;-114.4
6(36A)
0.303;-196.9
T(36A)
0.315;-249.4
6(37A)
0.235;-311.2
69(3A)
0.355;-270.0
(6Q)(3A)
0.334;-73.1
(379A)
0.337;-249.4
(37KA)
0.273;-166.9
79(3A)
0.297;-249.4
(7Q)(3A)
0.303;-52.5
(38TA)
0.256;-208.1
88(3A)
0.364;-114.4
(8J)(3A)
0.406;-52.5
9(39A)
0.365;-73.1
K(39A)
0.334;-125.6
9(3QA)
0.345;-146.2
J(3TA)
0.365;-146.2
TJ(3A)
0.296;-146.2
(3JQA)
0.366;-105.0
J(3KA)
0.366;-84.4
(QK)(3A)
0.429;71.3
33(5A)
0.327;-279.4
337A
0.270;-373.1
3A(3T)
0.326;-176.2
33(KA)
0.358;-114.4
3(46A)
0.269;-373.1
38(4A)
0.285;-331.9
(3J)(4A)
0.315;-135.0
4A(34)
0.329;-279.4
A(347)
0.320;-352.5
(34)(TA)
0.270;-155.6
QA(34)
0.299;-249.4
345A
0.298;-528.7
347A
0.262;-487.5
349A
0.284;-446.2
34JA
0.244;-405.0
34KA
0.284;-363.7
37(5A)
0.237;-331.9
(3T)(5A)
0.286;-135.0
3(5KA)
0.288;-208.1
A(357)
0.296;-331.9
(35)(TA)
0.311;-135.0
QA(35)
0.296;-228.7
356A
0.228;-487.5
358A
0.273;-446.2
35TA
0.241;-405.0
35QA
0.216;-363.7
(37)(6A)
0.337;-176.2
3(6TA)
0.356;-249.4
3Q(6A)
0.330;-208.1
(36)(8A)
0.295;-155.6
TA(36)
0.320;-249.4
A(36K)
0.361;-187.5
6A(38)
0.278;-290.6
6A(3T)
0.309;-249.4
6A(3Q)
0.330;-208.1
37(7A)
0.364;-155.6
(3T)(7A)
0.274;-93.8
3(7KA)
0.369;-166.9
A(379)
0.291;-249.4
(37)(QA)
0.359;-52.5
7A(38)
0.264;-270.0
7A(3T)
0.335;-228.7
7A(3Q)
0.353;-187.5
38(8A)
0.310;-114.4
(3J)(8A)
0.349;-52.5
8A(38)
0.332;-114.4
A(38J)
0.336;-187.5
388A
0.269;-249.4
38TA
0.260;-343.1
38QA
0.249;-301.9
(3T)(9A)
0.331;-52.5
3(9KA)
0.310;-125.6
A(39J)
0.347;-166.9
399A
0.341;-208.1
39JA
0.300;-301.9
39KA
0.243;-260.6
3Q(TA)
0.308;-125.6
(3T)(QA)
0.318;9.4
TA(3J)
0.315;-146.2
TA(3K)
0.326;-105.0
3(JKA)
0.298;-84.4
A(3JK)
0.358;-84.4
JA(3K)
0.301;-84.4
QA(3Q)
0.406;50.6
3QKA
0.362;-198.7
45(4A)
0.314;-238.1
(48)(4A)
0.354;-41.3
4(4JA)
0.359;-114.4
4K(4A)
0.267;-73.1
(459A)
0.324;-270.0
(45KA)
0.316;-187.5
57(4A)
0.242;-311.2
(5T)(4A)
0.295;-114.4
5(4KA)
0.313;-187.5
(469A)
0.354;-249.4
(46KA)
0.296;-166.9
68(4A)
0.268;-270.0
(6J)(4A)
0.293;-73.1
7(47A)
0.354;-135.0
J(47A)
0.317;-187.5
78(4A)
0.275;-249.4
(7J)(4A)
0.334;-52.5
8(48A)
0.288;-93.7
Q(48A)
0.279;-146.2
(8T)(4A)
0.359;-52.5
8(4KA)
0.306;-125.6
(49QA)
0.323;-125.6
9(4JA)
0.297;-146.2
9K(4A)
0.345;-105.0
TT(4A)
0.355;-11.2
(TK)(4A)
0.287;50.6
J(4QA)
0.366;-84.4
K(4QA)
0.337;-43.1
44(5A)
0.324;-238.1
447A
0.276;-331.9
4A(4T)
0.291;-135.0
44(KA)
0.301;-73.1
4(57A)
0.291;-311.2
49(5A)
0.311;-270.0
(4Q)(5A)
0.403;-73.1
6A(45)
0.287;-331.9
A(459)
0.300;-270.0
(45)(QA)
0.371;-73.1
5A(46)
0.291;-331.9
5A(48)
0.267;-290.6
5A(4T)
0.306;-249.4
5A(4Q)
0.277;-208.1
46(6A)
0.320;-176.2
(49)(6A)
0.282;-114.4
4(6QA)
0.324;-187.5
A(467)
0.320;-290.6
(46)(TA)
0.306;-93.8
QA(46)
0.341;-187.5
467A
0.262;-425.6
469A
0.274;-384.4
46JA
0.312;-343.1
46KA
0.239;-301.9
49(7A)
0.312;-228.7
(4Q)(7A)
0.369;-31.9
8A(47)
0.353;-249.4
A(47J)
0.332;-187.5
477A
0.286;-270.0
479A
0.276;-363.7
47JA
0.274;-322.5
47KA
0.273;-281.2
4T(8A)
0.280;-187.5
(4K)(8A)
0.337;9.4
TA(48)
0.280;-187.5
A(48K)
0.323;-125.6
8A(4T)
0.351;-187.5
8A(4Q)
0.360;-146.2
49(9A)
0.325;-52.5
(4Q)(9A)
0.284;9.4
TA(49)
0.293;-166.9
A(49K)
0.382;-105.0
9A(4J)
0.344;-146.2
9A(4K)
0.288;-105.0
4(TQA)
0.303;-105.0
A(4TJ)
0.366;-125.6
4TTA
0.329;-146.2
4TQA
0.269;-240.0
(4Q)(JA)
0.321;50.6
QA(4J)
0.253;-84.4
4JQA
0.359;-219.4
(4K)(QA)
0.340;91.9
QA(4K)
0.326;-43.1
5(56A)
0.313;-176.2
58(5A)
0.285;-135.0
(5J)(5A)
0.347;61.9
6(56A)
0.334;-155.6
T(56A)
0.315;-208.1
6(57A)
0.240;-270.0
69(5A)
0.298;-228.7
(6Q)(5A)
0.340;-31.9
(579A)
0.303;-208.1
(57KA)
0.349;-125.6
79(5A)
0.252;-208.1
(7Q)(5A)
0.363;-11.2
(58TA)
0.266;-166.9
88(5A)
0.319;-73.1
(8J)(5A)
0.302;-11.2
9(59A)
0.308;-31.9
K(59A)
0.318;-84.4
9(5QA)
0.272;-105.0
J(5TA)
0.272;-105.0
TJ(5A)
0.324;-105.0
(5JQA)
0.301;-63.7
J(5KA)
0.299;-43.1
(QK)(5A)
0.391;112.5
55(7A)
0.306;-155.6
559A
0.365;-249.4
5A(5Q)
0.382;-52.5
(57)(6A)
0.357;-135.0
5(6TA)
0.232;-208.1
5Q(6A)
0.292;-166.9
(56)(8A)
0.314;-114.4
TA(56)
0.304;-208.1
A(56K)
0.300;-146.2
6A(58)
0.266;-249.4
6A(5T)
0.306;-208.1
6A(5Q)
0.305;-166.9
57(7A)
0.312;-114.4
(5T)(7A)
0.299;-52.5
5(7KA)
0.383;-125.6
A(579)
0.244;-208.1
(57)(QA)
0.307;-11.2
7A(58)
0.251;-228.7
7A(5T)
0.280;-187.5
7A(5Q)
0.265;-146.2
58(8A)
0.327;-73.1
(5J)(8A)
0.388;-11.2
8A(58)
0.323;-73.1
A(58J)
0.354;-146.2
588A
0.279;-208.1
58TA
0.357;-301.9
58QA
0.321;-260.6
(5T)(9A)
0.296;-11.2
5(9KA)
0.353;-84.4
A(59J)
0.336;-125.6
599A
0.254;-166.9
59JA
0.240;-260.6
59KA
0.289;-219.4
5Q(TA)
0.391;-84.4
(5T)(QA)
0.345;50.6
TA(5J)
0.309;-105.0
TA(5K)
0.340;-63.7
5(JKA)
0.287;-43.1
A(5JK)
0.321;-43.1
JA(5K)
0.328;-43.1
QA(5Q)
0.342;91.9
5QKA
0.291;-157.5
67(6A)
0.341;-114.4
(6T)(6A)
0.380;82.5
6(6KA)
0.318;9.4
(67TA)
0.284;-166.9
77(6A)
0.266;-93.7
(7T)(6A)
0.389;-31.9
7(6KA)
0.311;-105.0
(68JA)
0.312;-125.6
(89)(6A)
0.344;-31.9
8(6QA)
0.311;-105.0
T(69A)
0.312;-125.6
9(6TA)
0.277;-125.6
9Q(6A)
0.321;-84.4
Q(6TA)
0.359;-63.7
(TQ)(6A)
0.325;71.3
(6JKA)
0.293;-22.5
JK(6A)
0.381;-22.5
K(6KA)
0.321;153.7
668A
0.236;-228.7
6A(6J)
0.352;-31.9
(67)(7A)
0.293;41.3
6(7TA)
0.291;-166.9
6Q(7A)
0.297;-125.6
(67)(9A)
0.345;-52.5
JA(67)
0.301;-146.2
67(8A)
0.314;-208.1
67(TA)
0.327;-166.9
67(QA)
0.351;-125.6
(68)(8A)
0.357;82.5
6(8JA)
0.323;-125.6
6K(8A)
0.349;-84.4
(68)(JA)
0.284;9.4
KA(68)
0.299;-84.4
6A(8T)
0.286;-146.2
6A(8Q)
0.308;-105.0
6(9TA)
0.358;-125.6
6Q(9A)
0.285;-84.4
(69)(JA)
0.290;30.0
KA(69)
0.368;-63.7
6A(9J)
0.296;-105.0
6A(9K)
0.313;-63.7
(6Q)(TA)
0.330;71.3
JA(6T)
0.318;-84.4
6T(JA)
0.309;-84.4
6T(KA)
0.401;-43.1
6Q(JA)
0.334;-43.1
(6J)(KA)
0.329;112.5
6J(KA)
0.371;-22.5
6K(QA)
0.318;-1.9
6A(QK)
0.373;-1.9
(78)(7A)
0.369;82.5
7(7JA)
0.361;9.4
7K(7A)
0.348;50.6
(78QA)
0.276;-84.4
8(7TA)
0.326;-125.6
8Q(7A)
0.331;-84.4
J(79A)
0.274;-84.4
9T(7A)
0.302;-105.0
(9K)(7A)
0.414;91.9
K(7TA)
0.357;-22.5
T(7KA)
0.316;-22.5
JJ(7A)
0.295;91.9
(7QKA)
0.340;18.7
777A
0.321;-73.1
7A(7T)
0.362;-11.2
77(KA)
0.334;50.6
7(8TA)
0.300;-125.6
7Q(8A)
0.320;-84.4
(78)(TA)
0.330;9.4
QA(78)
0.337;-84.4
789A
0.311;-281.2
78JA
0.300;-240.0
78KA
0.281;-198.7
7J(9A)
0.367;-84.4
(79)(TA)
0.353;30.0
QA(79)
0.326;-63.7
79TA
0.238;-240.0
79QA
0.285;-198.7
(7J)(TA)
0.397;71.3
TA(7T)
0.397;50.6
A(7TK)
0.402;-22.5
TA(7Q)
0.286;-43.1
7J(JA)
0.361;91.9
(7J)(QA)
0.371;112.5
JA(7Q)
0.312;-22.5
7Q(QA)
0.337;133.1
7QQA
0.299;-1.9
7KKA
0.296;39.4
8(8JA)
0.349;50.6
8K(8A)
0.374;91.9
(89KA)
0.360;-22.5
9J(8A)
0.367;-63.7
(8TJA)
0.314;-43.1
(TJ)(8A)
0.357;91.9
J(8JA)
0.321;112.5
JQ(8A)
0.353;-1.9
Q(8KA)
0.309;39.4
889A
0.380;-125.6
8A(8Q)
0.277;71.3
(8T)(9A)
0.342;50.6
8(9KA)
0.331;-22.5
A(89J)
0.305;-63.7
899A
0.393;-105.0
89JA
0.334;-198.7
89KA
0.265;-157.5
8Q(TA)
0.349;-22.5
(8T)(QA)
0.360;112.5
TA(8J)
0.361;-43.1
TA(8K)
0.338;-1.9
8(JKA)
0.326;18.7
A(8JK)
0.337;18.7
JA(8K)
0.365;18.7
QA(8Q)
0.295;153.7
8QKA
0.363;-95.6
9T(9A)
0.394;71.3
(9K)(9A)
0.330;268.1
K(9TA)
0.390;18.7
T(9KA)
0.320;18.7
JJ(9A)
0.337;133.1
(9QKA)
0.340;60.0
999A
0.349;50.6
9A(9Q)
0.361;112.5
(9J)(TA)
0.312;112.5
TA(9T)
0.359;91.9
A(9TK)
0.337;18.7
TA(9Q)
0.334;-1.9
9J(JA)
0.370;133.1
(9J)(QA)
0.377;153.8
JA(9Q)
0.419;18.7
9Q(QA)
0.392;174.4
9QQA
0.397;39.4
9KKA
0.295;80.6
T(TKA)
0.429;174.4
JJ(TA)
0.309;153.7
(TQKA)
0.310;80.6
TTTA
0.373;112.5
TA(TK)
0.388;174.4
(TK)(JA)
0.362;195.0
KA(TJ)
0.288;60.0
TA(JK)
0.344;60.0
(TQ)(KA)
0.371;215.6
(TK)(KA)
0.387;371.3
J(JKA)
0.351;215.6
(QK)(JA)
0.327;236.3
JJ(KA)
0.395;215.6
QA(JQ)
0.300;215.6
JQKA
0.346;-33.7
QK(QA)
0.404;256.9
QK(KA)
0.445;277.5
22(24)
0.277;-453.8
22(28)
0.298;-371.2
22(2Q)
0.294;-288.7
24(23)
0.203;-568.1
(23)(27)
0.264;-371.3
2(23T)
0.270;-444.4
2Q(23)
0.239;-403.1
23(25)
0.292;-547.5
2237
0.200;-641.2
22(3T)
0.310;-444.4
23(2K)
0.234;-382.5
2(246)
0.239;-506.2
28(24)
0.305;-465.0
(24)(2J)
0.324;-268.1
2244
0.208;-547.5
22(47)
0.300;-485.6
24(2T)
0.230;-423.8
224Q
0.276;-517.5
26(25)
0.250;-485.6
(25)(29)
0.269;-288.7
2(25Q)
0.303;-361.9
22(56)
0.222;-485.6
25(29)
0.261;-423.8
225J
0.262;-517.5
26(26)
0.298;-330.0
(26)(29)
0.346;-268.1
2(26Q)
0.285;-341.2
22(67)
0.259;-444.4
26(2T)
0.231;-382.5
226Q
0.259;-476.2
28(27)
0.294;-403.1
(27)(2J)
0.326;-206.3
2277
0.272;-423.8
22(7T)
0.257;-361.9
27(2K)
0.234;-300.0
2(28T)
0.320;-341.2
2Q(28)
0.340;-300.0
28(2T)
0.263;-341.2
228Q
0.225;-435.0
2T(29)
0.312;-320.6
(29)(2K)
0.330;-123.7
229J
0.267;-435.0
2T(2T)
0.259;-165.0
(2T)(2K)
0.315;-103.1
22TQ
0.279;-393.8
2Q(2J)
0.319;-238.1
2J(2K)
0.287;-217.5
22QQ
0.236;-217.5
3(234)
0.218;-547.5
36(23)
0.235;-506.2
(23)(39)
0.275;-309.4
3(23Q)
0.309;-382.5
5(234)
0.213;-641.2
9(234)
0.289;-558.8
K(234)
0.196;-476.2
4(237)
0.241;-600.0
49(23)
0.216;-558.8
(23)(4Q)
0.240;-361.9
(2357)
0.254;-579.4
(235J)
0.228;-496.9
(23)(56)
0.213;-465.0
5(239)
0.241;-538.1
5J(23)
0.258;-496.9
(2367)
0.222;-558.8
(236J)
0.300;-476.2
(23)(67)
0.241;-423.8
6(23T)
0.250;-496.9
6Q(23)
0.241;-455.6
9(237)
0.252;-496.9
K(237)
0.324;-414.4
7(23T)
0.278;-476.2
7Q(23)
0.260;-435.0
T(238)
0.244;-455.6
8(239)
0.258;-476.2
8J(23)
0.283;-435.0
(239T)
0.279;-435.0
99(23)
0.298;-320.6
(23)(9Q)
0.318;-258.8
(23TQ)
0.275;-373.1
T(23Q)
0.274;-373.1
Q(23J)
0.310;-352.5
(23)(JK)
0.317;-196.9
QK(23)
0.344;-311.2
23(35)
0.248;-526.9
33(28)
0.251;-465.0
233T
0.199;-558.8
23(3K)
0.227;-361.9
(24)(36)
0.255;-485.6
3(249)
0.236;-558.8
3J(24)
0.256;-517.5
(34)(25)
0.242;-506.2
27(34)
0.216;-600.0
2(34T)
0.193;-538.1
(34)(2K)
0.268;-341.2
34(26)
0.260;-620.6
34(28)
0.212;-579.4
34(2T)
0.263;-538.1
34(2Q)
0.205;-496.9
(25)(35)
0.282;-350.6
3(258)
0.237;-558.8
3T(25)
0.305;-517.5
(25)(3K)
0.280;-320.6
27(35)
0.265;-579.4
2(35T)
0.266;-517.5
(35)(2K)
0.294;-320.6
35(27)
0.244;-579.4
35(29)
0.279;-538.1
35(2J)
0.239;-496.9
35(2K)
0.215;-455.6
37(26)
0.241;-558.8
(26)(3T)
0.272;-361.9
3(26K)
0.277;-435.0
2(368)
0.245;-538.1
(36)(2J)
0.348;-341.2
2K(36)
0.299;-435.0
23(68)
0.294;-538.1
23(6T)
0.290;-496.9
23(6Q)
0.276;-455.6
3(278)
0.210;-517.5
3T(27)
0.217;-476.2
(27)(3K)
0.299;-279.4
29(37)
0.259;-496.9
2(37Q)
0.302;-435.0
23(78)
0.229;-517.5
23(7T)
0.213;-476.2
23(7Q)
0.237;-435.0
3(289)
0.273;-476.2
3J(28)
0.215;-435.0
(38)(29)
0.269;-341.2
2J(38)
0.246;-435.0
38(29)
0.208;-476.2
38(2J)
0.334;-435.0
38(2K)
0.219;-393.8
3T(29)
0.322;-435.0
(29)(3K)
0.374;-238.1
2J(39)
0.302;-414.4
39(2T)
0.282;-435.0
39(2Q)
0.252;-393.8
(2T)(3T)
0.278;-144.4
3(2TK)
0.334;-352.5
2(3TQ)
0.320;-373.1
23(TJ)
0.289;-393.8
23(TK)
0.299;-352.5
(2J)(3K)
0.296;-196.9
2K(3J)
0.331;-331.9
23(JK)
0.262;-331.9
(3Q)(2K)
0.316;-176.2
(2K)(3K)
0.272;-20.6
4(246)
0.236;-465.0
48(24)
0.322;-423.8
(24)(4J)
0.262;-226.9
5(245)
0.261;-465.0
9(245)
0.199;-517.5
K(245)
0.247;-435.0
5(248)
0.282;-538.1
5T(24)
0.197;-496.9
(24)(5K)
0.255;-300.0
9(246)
0.317;-496.9
K(246)
0.275;-414.4
6(249)
0.228;-496.9
6J(24)
0.257;-455.6
(2478)
0.256;-496.9
(247Q)
0.309;-414.4
7(249)
0.231;-476.2
7J(24)
0.261;-435.0
(2489)
0.328;-455.6
(248K)
0.287;-373.1
8T(24)
0.285;-435.0
(24)(8K)
0.284;-238.1
Q(249)
0.226;-373.1
(24)(9J)
0.276;-258.8
T(24T)
0.326;-258.8
T(24J)
0.266;-373.1
TK(24)
0.298;-331.9
(24)(JQ)
0.257;-196.9
QQ(24)
0.366;-176.2
24(45)
0.282;-485.6
44(28)
0.238;-423.8
244T
0.241;-517.5
24(4K)
0.360;-320.6
(25)(47)
0.226;-423.8
4(25T)
0.220;-496.9
4Q(25)
0.256;-455.6
(45)(27)
0.333;-423.8
29(45)
0.275;-517.5
2(45Q)
0.209;-455.6
24(56)
0.260;-579.4
24(58)
0.307;-538.1
24(5T)
0.255;-496.9
24(5Q)
0.314;-455.6
4(267)
0.226;-538.1
49(26)
0.244;-496.9
(26)(4Q)
0.366;-300.0
27(46)
0.245;-538.1
2(46T)
0.257;-476.2
(46)(2K)
0.254;-279.4
46(28)
0.289;-517.5
46(2T)
0.232;-476.2
46(2Q)
0.326;-435.0
(27)(47)
0.279;-247.5
4(27T)
0.240;-455.6
4Q(27)
0.255;-414.4
(47)(29)
0.284;-341.2
2J(47)
0.279;-435.0
47(28)
0.207;-496.9
47(2T)
0.214;-455.6
47(2Q)
0.239;-414.4
(28)(48)
0.322;-206.3
4(28J)
0.252;-414.4
4K(28)
0.305;-373.1
(48)(2J)
0.284;-279.4
2K(48)
0.318;-373.1
24(8T)
0.232;-435.0
24(8Q)
0.264;-393.8
4(29T)
0.216;-414.4
4Q(29)
0.245;-373.1
(49)(2J)
0.279;-258.8
2K(49)
0.263;-352.5
24(9J)
0.310;-393.8
24(9K)
0.282;-352.5
(2T)(4Q)
0.320;-217.5
2J(4T)
0.277;-373.1
4T(2J)
0.220;-373.1
4T(2K)
0.302;-331.9
4Q(2J)
0.312;-331.9
(4J)(2K)
0.372;-176.2
4J(2K)
0.277;-311.2
4K(2Q)
0.304;-290.6
24(QK)
0.335;-290.6
(25)(56)
0.290;-288.7
5(259)
0.293;-361.9
5J(25)
0.323;-320.6
(2567)
0.252;-517.5
(256J)
0.251;-435.0
(25)(67)
0.294;-382.5
6(25T)
0.238;-455.6
6Q(25)
0.339;-414.4
9(257)
0.231;-455.6
K(257)
0.271;-373.1
7(25T)
0.255;-435.0
7Q(25)
0.305;-393.8
T(258)
0.273;-414.4
8(259)
0.307;-435.0
8J(25)
0.275;-393.8
(259T)
0.342;-393.8
99(25)
0.344;-279.4
(25)(9Q)
0.301;-217.5
(25TQ)
0.294;-331.9
T(25Q)
0.299;-331.9
Q(25J)
0.318;-311.2
(25)(JK)
0.251;-155.6
QK(25)
0.271;-270.0
25(57)
0.272;-403.1
55(2T)
0.230;-341.2
255Q
0.284;-435.0
57(26)
0.228;-517.5
(26)(5T)
0.303;-320.6
5(26K)
0.234;-393.8
2(568)
0.278;-496.9
(56)(2J)
0.288;-300.0
2K(56)
0.288;-393.8
25(68)
0.289;-496.9
25(6T)
0.260;-455.6
25(6Q)
0.239;-414.4
5(278)
0.288;-476.2
5T(27)
0.213;-435.0
(27)(5K)
0.323;-238.1
29(57)
0.229;-455.6
2(57Q)
0.265;-393.8
25(78)
0.227;-476.2
25(7T)
0.253;-435.0
25(7Q)
0.310;-393.8
5(289)
0.296;-435.0
5J(28)
0.297;-393.8
(58)(29)
0.340;-300.0
2J(58)
0.245;-393.8
58(29)
0.246;-435.0
58(2J)
0.286;-393.8
58(2K)
0.319;-352.5
5T(29)
0.320;-393.8
(29)(5K)
0.289;-196.9
2J(59)
0.215;-373.1
59(2T)
0.295;-393.8
59(2Q)
0.340;-352.5
(2T)(5T)
0.303;-103.1
5(2TK)
0.293;-311.2
2(5TQ)
0.256;-331.9
25(TJ)
0.265;-352.5
25(TK)
0.325;-311.2
(2J)(5K)
0.274;-155.6
2K(5J)
0.276;-290.6
25(JK)
0.289;-290.6
(5Q)(2K)
0.298;-135.0
(2K)(5K)
0.311;20.6
6(268)
0.287;-341.2
6T(26)
0.314;-300.0
(26)(6K)
0.331;-103.1
T(267)
0.285;-414.4
7(268)
0.266;-455.6
7T(26)
0.248;-414.4
(26)(7K)
0.296;-217.5
J(268)
0.257;-373.1
89(26)
0.231;-414.4
(26)(8Q)
0.328;-217.5
(269J)
0.293;-352.5
(26)(9T)
0.244;-238.1
9(26K)
0.295;-311.2
(26TK)
0.298;-290.6
TQ(26)
0.285;-311.2
K(26J)
0.364;-270.0
Q(26Q)
0.319;-135.0
KK(26)
0.302;-93.7
66(29)
0.320;-320.6
266J
0.263;-414.4
67(27)
0.312;-341.2
(27)(6T)
0.264;-279.4
6(27K)
0.282;-352.5
2(679)
0.320;-435.0
(67)(2Q)
0.300;-238.1
27(68)
0.245;-455.6
27(6T)
0.310;-414.4
27(6Q)
0.213;-373.1
68(28)
0.237;-300.0
(28)(6J)
0.246;-238.1
28(68)
0.321;-300.0
2(68J)
0.286;-373.1
2688
0.265;-435.0
268T
0.240;-528.7
268Q
0.253;-487.5
(29)(6T)
0.316;-238.1
6(29K)
0.334;-311.2
2(69J)
0.304;-352.5
2699
0.295;-393.8
269J
0.324;-487.5
269K
0.233;-446.2
6Q(2T)
0.334;-311.2
(6T)(2Q)
0.331;-176.2
2T(6J)
0.320;-331.9
2T(6K)
0.271;-290.6
6(2JK)
0.322;-270.0
2(6JK)
0.361;-270.0
2J(6K)
0.237;-270.0
2Q(6Q)
0.301;-135.0
26QK
0.244;-384.4
78(27)
0.300;-300.0
(27)(7J)
0.302;-103.1
8(278)
0.255;-279.4
Q(278)
0.335;-331.9
(27)(8T)
0.272;-238.1
8(27K)
0.246;-311.2
(279Q)
0.257;-311.2
9(27J)
0.302;-331.9
9K(27)
0.320;-290.6
TT(27)
0.350;-196.9
(27)(TK)
0.322;-135.0
J(27Q)
0.282;-270.0
K(27Q)
0.276;-228.7
77(28)
0.289;-300.0
277T
0.285;-393.8
27(7K)
0.332;-196.9
(28)(7T)
0.329;-238.1
7(28K)
0.334;-311.2
2(78T)
0.288;-373.1
(78)(2K)
0.282;-176.2
78(2T)
0.304;-373.1
78(2Q)
0.314;-331.9
(29)(79)
0.354;-103.1
7(29Q)
0.267;-311.2
2(79T)
0.310;-352.5
(79)(2K)
0.312;-155.6
79(2J)
0.284;-331.9
79(2K)
0.340;-290.6
7J(2T)
0.255;-311.2
(7T)(2J)
0.277;-176.2
2K(7T)
0.296;-270.0
27(TQ)
0.307;-290.6
7(2JQ)
0.322;-270.0
2(7JQ)
0.246;-270.0
27(JQ)
0.281;-270.0
7(2QK)
0.332;-228.7
7Q(2K)
0.294;-228.7
88(28)
0.316;-123.7
(28)(8J)
0.334;-61.9
9(289)
0.391;-217.5
K(289)
0.307;-270.0
9(28Q)
0.287;-290.6
J(28T)
0.336;-290.6
TJ(28)
0.259;-290.6
(28JQ)
0.298;-249.4
J(28K)
0.241;-228.7
(28)(QK)
0.326;-73.1
88(2T)
0.308;-217.5
288Q
0.261;-311.2
8T(29)
0.267;-331.9
(29)(8K)
0.386;-135.0
2J(89)
0.284;-311.2
89(2T)
0.319;-331.9
89(2Q)
0.276;-290.6
(2T)(8T)
0.339;-41.3
8(2TK)
0.293;-249.4
2(8TQ)
0.329;-270.0
28(TJ)
0.309;-290.6
28(TK)
0.321;-249.4
(2J)(8K)
0.297;-93.8
2K(8J)
0.288;-228.7
28(JK)
0.309;-228.7
(8Q)(2K)
0.346;-73.1
(2K)(8K)
0.394;82.5
9(29J)
0.315;-155.6
9K(29)
0.302;-114.4
TT(29)
0.327;-155.6
(29)(TK)
0.290;-93.8
J(29Q)
0.313;-228.7
K(29Q)
0.325;-187.5
99(2T)
0.322;-176.2
299Q
0.266;-270.0
9J(2T)
0.296;-270.0
(9T)(2J)
0.239;-135.0
2K(9T)
0.349;-228.7
29(TQ)
0.260;-249.4
9(2JQ)
0.260;-228.7
2(9JQ)
0.362;-228.7
29(JQ)
0.303;-228.7
9(2QK)
0.241;-187.5
9Q(2K)
0.313;-187.5
TT(2T)
0.340;0.0
(2T)(TK)
0.289;61.9
J(2TQ)
0.297;-208.1
K(2TQ)
0.274;-166.9
TT(2J)
0.277;-114.4
2TTK
0.268;-208.1
TK(2J)
0.349;-187.5
2TJJ
0.327;-228.7
2TJK
0.295;-322.5
2(TQK)
0.334;-166.9
TK(2K)
0.330;-11.2
(2J)(JK)
0.349;103.1
QK(2J)
0.336;-146.2
2J(JK)
0.331;-31.9
(JQ)(2K)
0.313;-11.2
(2K)(JK)
0.333;144.4
K(2QK)
0.288;30.0
2K(QK)
0.321;30.0
3335
0.245;-506.2
3339
0.274;-423.8
333K
0.282;-341.2
36(34)
0.258;-465.0
(34)(39)
0.268;-268.1
3(34Q)
0.309;-341.2
33(45)
0.314;-485.6
34(38)
0.224;-423.8
334T
0.260;-517.5
33(4K)
0.290;-320.6
(35)(37)
0.327;-288.7
3(35T)
0.349;-361.9
3Q(35)
0.254;-320.6
35(37)
0.288;-423.8
3359
0.278;-517.5
33(5Q)
0.247;-320.6
(36)(37)
0.319;-268.1
3(36T)
0.253;-341.2
3Q(36)
0.287;-300.0
36(38)
0.277;-382.5
336T
0.289;-476.2
33(6K)
0.309;-279.4
(37)(39)
0.360;-206.3
3(37Q)
0.256;-279.4
33(78)
0.301;-361.9
37(3J)
0.302;-300.0
337K
0.255;-393.8
3T(38)
0.283;-300.0
(38)(3K)
0.328;-103.1
338T
0.255;-435.0
33(8K)
0.334;-238.1
(39)(3J)
0.368;-123.7
3399
0.312;-300.0
33(9Q)
0.315;-238.1
(3T)(3J)
0.375;-103.1
33TT
0.305;-258.8
33(TK)
0.303;-196.9
(3J)(3K)
0.348;-41.3
33JK
0.294;-311.2
33(QK)
0.332;-155.6
45(34)
0.312;-465.0
(34)(48)
0.318;-268.1
4(34J)
0.307;-341.2
4K(34)
0.283;-300.0
(3459)
0.285;-496.9
(345K)
0.254;-414.4
57(34)
0.280;-538.1
(34)(5T)
0.260;-341.2
5(34K)
0.287;-414.4
(3469)
0.309;-476.2
(346K)
0.313;-393.8
68(34)
0.281;-496.9
(34)(6J)
0.252;-300.0
7(347)
0.226;-361.9
J(347)
0.286;-414.4
78(34)
0.270;-476.2
(34)(7J)
0.297;-279.4
8(348)
0.233;-320.6
Q(348)
0.228;-373.1
(34)(8T)
0.307;-279.4
8(34K)
0.285;-352.5
(349Q)
0.248;-352.5
9(34J)
0.269;-373.1
9K(34)
0.240;-331.9
TT(34)
0.365;-238.1
(34)(TK)
0.357;-176.2
J(34Q)
0.324;-311.2
K(34Q)
0.306;-270.0
44(35)
0.211;-465.0
3447
0.260;-558.8
34(4T)
0.294;-361.9
44(3K)
0.291;-300.0
4(357)
0.279;-538.1
49(35)
0.318;-496.9
(35)(4Q)
0.281;-300.0
36(45)
0.277;-558.8
3(459)
0.238;-496.9
(45)(3Q)
0.346;-300.0
35(46)
0.193;-558.8
35(48)
0.246;-517.5
35(4T)
0.257;-476.2
35(4Q)
0.272;-435.0
46(36)
0.326;-403.1
(36)(49)
0.247;-341.2
4(36Q)
0.261;-414.4
3(467)
0.258;-517.5
(46)(3T)
0.259;-320.6
3Q(46)
0.271;-414.4
3467
0.208;-652.5
3469
0.246;-611.2
346J
0.252;-570.0
346K
0.288;-528.7
49(37)
0.289;-455.6
(37)(4Q)
0.320;-258.8
38(47)
0.252;-476.2
3(47J)
0.265;-414.4
3477
0.262;-496.9
3479
0.287;-590.6
347J
0.244;-549.4
347K
0.320;-508.1
4T(38)
0.275;-414.4
(38)(4K)
0.306;-217.5
3T(48)
0.208;-414.4
3(48K)
0.349;-352.5
38(4T)
0.280;-414.4
38(4Q)
0.295;-373.1
49(39)
0.269;-279.4
(39)(4Q)
0.312;-217.5
3T(49)
0.312;-393.8
3(49K)
0.230;-331.9
39(4J)
0.309;-373.1
39(4K)
0.331;-331.9
4(3TQ)
0.342;-331.9
3(4TJ)
0.280;-352.5
34TT
0.323;-373.1
34TQ
0.241;-466.9
(3J)(4Q)
0.297;-176.2
3Q(4J)
0.304;-311.2
34JQ
0.223;-446.2
(3Q)(4K)
0.344;-135.0
3Q(4K)
0.314;-270.0
5(356)
0.222;-403.1
58(35)
0.342;-361.9
(35)(5J)
0.340;-165.0
6(356)
0.267;-382.5
T(356)
0.288;-435.0
6(357)
0.223;-496.9
69(35)
0.268;-455.6
(35)(6Q)
0.315;-258.8
(3579)
0.272;-435.0
(357K)
0.346;-352.5
79(35)
0.282;-435.0
(35)(7Q)
0.278;-238.1
(358T)
0.257;-393.8
88(35)
0.293;-300.0
(35)(8J)
0.285;-238.1
9(359)
0.296;-258.8
K(359)
0.336;-311.2
9(35Q)
0.275;-331.9
J(35T)
0.248;-331.9
TJ(35)
0.270;-331.9
(35JQ)
0.251;-290.6
J(35K)
0.350;-270.0
(35)(QK)
0.282;-114.4
55(37)
0.266;-382.5
3559
0.265;-476.2
35(5Q)
0.311;-279.4
(36)(57)
0.293;-361.9
5(36T)
0.270;-435.0
5Q(36)
0.274;-393.8
(56)(38)
0.265;-341.2
3T(56)
0.204;-435.0
3(56K)
0.359;-373.1
36(58)
0.288;-476.2
36(5T)
0.264;-435.0
36(5Q)
0.204;-393.8
57(37)
0.277;-341.2
(37)(5T)
0.279;-279.4
5(37K)
0.243;-352.5
3(579)
0.310;-435.0
(57)(3Q)
0.302;-238.1
37(58)
0.221;-455.6
37(5T)
0.271;-414.4
37(5Q)
0.259;-373.1
58(38)
0.266;-300.0
(38)(5J)
0.340;-238.1
38(58)
0.246;-300.0
3(58J)
0.283;-373.1
3588
0.228;-435.0
358T
0.250;-528.7
358Q
0.257;-487.5
(39)(5T)
0.277;-238.1
5(39K)
0.335;-311.2
3(59J)
0.249;-352.5
3599
0.318;-393.8
359J
0.257;-487.5
359K
0.245;-446.2
5Q(3T)
0.331;-311.2
(5T)(3Q)
0.275;-176.2
3T(5J)
0.270;-331.9
3T(5K)
0.263;-290.6
5(3JK)
0.301;-270.0
3(5JK)
0.295;-270.0
3J(5K)
0.301;-270.0
3Q(5Q)
0.270;-135.0
35QK
0.286;-384.4
67(36)
0.246;-341.2
(36)(6T)
0.305;-144.4
6(36K)
0.241;-217.5
(367T)
0.284;-393.8
77(36)
0.257;-320.6
(36)(7T)
0.319;-258.8
7(36K)
0.282;-331.9
(368J)
0.244;-352.5
(36)(89)
0.285;-258.8
8(36Q)
0.265;-331.9
T(369)
0.245;-352.5
9(36T)
0.232;-352.5
9Q(36)
0.259;-311.2
Q(36T)
0.296;-290.6
(36)(TQ)
0.272;-155.6
(36JK)
0.323;-249.4
JK(36)
0.287;-249.4
K(36K)
0.308;-73.1
3668
0.238;-455.6
36(6J)
0.269;-258.8
(37)(67)
0.287;-185.6
6(37T)
0.323;-393.8
6Q(37)
0.311;-352.5
(67)(39)
0.351;-279.4
3J(67)
0.265;-373.1
67(38)
0.252;-435.0
67(3T)
0.349;-393.8
67(3Q)
0.274;-352.5
(38)(68)
0.354;-144.4
6(38J)
0.238;-352.5
6K(38)
0.255;-311.2
(68)(3J)
0.308;-217.5
3K(68)
0.286;-311.2
36(8T)
0.286;-373.1
36(8Q)
0.263;-331.9
6(39T)
0.300;-352.5
6Q(39)
0.285;-311.2
(69)(3J)
0.295;-196.9
3K(69)
0.272;-290.6
36(9J)
0.349;-331.9
36(9K)
0.289;-290.6
(3T)(6Q)
0.316;-155.6
3J(6T)
0.306;-311.2
6T(3J)
0.318;-311.2
6T(3K)
0.339;-270.0
6Q(3J)
0.351;-270.0
(6J)(3K)
0.310;-114.4
6J(3K)
0.304;-249.4
6K(3Q)
0.306;-228.7
36(QK)
0.353;-228.7
(37)(78)
0.362;-144.4
7(37J)
0.346;-217.5
7K(37)
0.319;-176.2
(378Q)
0.251;-311.2
8(37T)
0.292;-352.5
8Q(37)
0.318;-311.2
J(379)
0.311;-311.2
9T(37)
0.270;-331.9
(37)(9K)
0.350;-135.0
K(37T)
0.352;-249.4
T(37K)
0.307;-249.4
JJ(37)
0.279;-135.0
(37QK)
0.241;-208.1
3777
0.331;-300.0
37(7T)
0.318;-238.1
77(3K)
0.349;-176.2
7(38T)
0.341;-352.5
7Q(38)
0.291;-311.2
(78)(3T)
0.250;-217.5
3Q(78)
0.315;-311.2
3789
0.258;-508.1
378J
0.232;-466.9
378K
0.273;-425.6
7J(39)
0.319;-311.2
(79)(3T)
0.304;-196.9
3Q(79)
0.326;-290.6
379T
0.286;-466.9
379Q
0.271;-425.6
(3T)(7J)
0.316;-155.6
3T(7T)
0.333;-176.2
3(7TK)
0.284;-249.4
3T(7Q)
0.286;-270.0
7J(3J)
0.346;-135.0
(7J)(3Q)
0.321;-114.4
3J(7Q)
0.288;-249.4
7Q(3Q)
0.287;-93.7
37QQ
0.328;-228.7
37KK
0.305;-187.5
8(38J)
0.336;-176.2
8K(38)
0.340;-135.0
(389K)
0.314;-249.4
9J(38)
0.257;-290.6
(38TJ)
0.249;-270.0
(38)(TJ)
0.273;-135.0
J(38J)
0.302;-114.4
JQ(38)
0.356;-228.7
Q(38K)
0.361;-187.5
3889
0.258;-352.5
38(8Q)
0.317;-155.6
(39)(8T)
0.308;-176.2
8(39K)
0.232;-249.4
3(89J)
0.240;-290.6
3899
0.282;-331.9
389J
0.261;-425.6
389K
0.233;-384.4
8Q(3T)
0.307;-249.4
(8T)(3Q)
0.357;-114.4
3T(8J)
0.337;-270.0
3T(8K)
0.256;-228.7
8(3JK)
0.280;-208.1
3(8JK)
0.346;-208.1
3J(8K)
0.314;-208.1
3Q(8Q)
0.335;-73.1
38QK
0.287;-322.5
9T(39)
0.300;-155.6
(39)(9K)
0.344;41.3
K(39T)
0.321;-208.1
T(39K)
0.324;-208.1
JJ(39)
0.327;-93.7
(39QK)
0.269;-166.9
3999
0.327;-176.2
39(9Q)
0.322;-114.4
(3T)(9J)
0.347;-114.4
3T(9T)
0.381;-135.0
3(9TK)
0.301;-208.1
3T(9Q)
0.354;-228.7
9J(3J)
0.330;-93.7
(9J)(3Q)
0.366;-73.1
3J(9Q)
0.348;-208.1
9Q(3Q)
0.331;-52.5
39QQ
0.294;-187.5
39KK
0.251;-146.2
T(3TK)
0.342;-52.5
JJ(3T)
0.284;-73.1
(3TQK)
0.349;-146.2
3TTT
0.308;-114.4
3T(TK)
0.341;-52.5
(3J)(TK)
0.337;-31.9
3K(TJ)
0.324;-166.9
3T(JK)
0.312;-166.9
(TQ)(3K)
0.324;-11.2
(3K)(TK)
0.310;144.4
J(3JK)
0.276;-11.2
(3J)(QK)
0.370;9.4
JJ(3K)
0.355;-11.2
3Q(JQ)
0.285;-11.2
3JQK
0.329;-260.6
QK(3Q)
0.311;30.0
QK(3K)
0.389;50.6
44(46)
0.303;-288.7
44(4T)
0.266;-206.2
(45)(45)
0.307;-153.8
4(458)
0.272;-361.9
4T(45)
0.329;-320.6
(45)(4K)
0.312;-123.7
4457
0.268;-517.5
44(5T)
0.346;-320.6
45(4K)
0.271;-258.8
4(468)
0.265;-341.2
4T(46)
0.270;-300.0
(46)(4K)
0.357;-103.1
4468
0.246;-476.2
44(6J)
0.294;-279.4
(47)(47)
0.327;-71.2
4(47T)
0.305;-279.4
4Q(47)
0.274;-238.1
47(49)
0.264;-300.0
447J
0.329;-393.8
48(48)
0.329;-165.0
(48)(4J)
0.299;-103.1
4488
0.264;-300.0
44(8J)
0.316;-238.1
(49)(49)
0.349;11.2
4(49Q)
0.282;-196.9
44(9T)
0.345;-238.1
49(4K)
0.254;-176.2
4(4TQ)
0.261;-176.2
44(TJ)
0.312;-196.9
(4J)(4J)
0.323;93.8
44JJ
0.293;-176.2
4Q(4Q)
0.303;0.0
(4K)(4K)
0.369;176.2
(45)(57)
0.294;-226.9
5(45T)
0.355;-300.0
5Q(45)
0.265;-258.8
8(456)
0.301;-455.6
Q(456)
0.311;-373.1
(45)(68)
0.225;-320.6
6(45J)
0.241;-393.8
6K(45)
0.310;-352.5
(457J)
0.226;-373.1
(45)(78)
0.357;-300.0
7(45J)
0.237;-373.1
7K(45)
0.287;-331.9
(458Q)
0.250;-331.9
8(45T)
0.252;-373.1
8Q(45)
0.245;-331.9
J(459)
0.275;-331.9
9T(45)
0.265;-352.5
(45)(9K)
0.318;-155.6
K(45T)
0.325;-270.0
T(45K)
0.257;-270.0
JJ(45)
0.305;-155.6
(45QK)
0.246;-228.7
4555
0.227;-403.1
45(58)
0.275;-341.2
55(4J)
0.292;-279.4
455K
0.280;-373.1
58(46)
0.244;-455.6
(46)(5J)
0.295;-258.8
46(56)
0.348;-361.9
4(569)
0.273;-435.0
(56)(4Q)
0.336;-238.1
46(57)
0.285;-476.2
46(59)
0.254;-435.0
46(5J)
0.320;-393.8
46(5K)
0.301;-352.5
5(479)
0.239;-414.4
5J(47)
0.272;-373.1
(57)(48)
0.329;-300.0
4T(57)
0.259;-393.8
4(57K)
0.265;-331.9
47(59)
0.303;-414.4
47(5J)
0.297;-373.1
47(5K)
0.294;-331.9
5(48T)
0.215;-373.1
5Q(48)
0.323;-331.9
(58)(4T)
0.342;-238.1
4Q(58)
0.298;-331.9
4589
0.196;-528.7
458J
0.244;-487.5
458K
0.249;-446.2
5J(49)
0.288;-331.9
(59)(4T)
0.273;-217.5
4Q(59)
0.325;-311.2
459T
0.279;-487.5
459Q
0.262;-446.2
(4T)(5J)
0.316;-176.2
4T(5T)
0.309;-196.9
4(5TK)
0.278;-270.0
4T(5Q)
0.294;-290.6
5J(4J)
0.312;-155.6
(5J)(4Q)
0.327;-135.0
4J(5Q)
0.286;-270.0
5Q(4Q)
0.334;-114.4
45QQ
0.360;-249.4
45KK
0.368;-208.1
6(469)
0.304;-279.4
6J(46)
0.335;-238.1
(4678)
0.280;-414.4
(467Q)
0.229;-331.9
7(469)
0.255;-393.8
7J(46)
0.274;-352.5
(4689)
0.295;-373.1
(468K)
0.251;-290.6
8T(46)
0.277;-352.5
(46)(8K)
0.305;-155.6
Q(469)
0.294;-290.6
(46)(9J)
0.314;-176.2
T(46T)
0.323;-176.2
T(46J)
0.277;-290.6
TK(46)
0.307;-249.4
(46)(JQ)
0.327;-114.4
QQ(46)
0.359;-93.7
46(67)
0.260;-320.6
66(4T)
0.288;-258.8
466Q
0.272;-352.5
68(47)
0.242;-414.4
(47)(6J)
0.379;-217.5
47(67)
0.273;-300.0
4(67T)
0.253;-373.1
(67)(4K)
0.299;-176.2
67(49)
0.283;-393.8
67(4J)
0.268;-352.5
67(4K)
0.269;-311.2
69(48)
0.242;-373.1
(48)(6Q)
0.308;-176.2
49(68)
0.289;-373.1
4(68Q)
0.281;-311.2
46(89)
0.245;-373.1
46(8J)
0.276;-331.9
46(8K)
0.308;-290.6
(49)(6J)
0.268;-176.2
49(69)
0.317;-217.5
4(69Q)
0.241;-290.6
46(9T)
0.368;-331.9
46(9Q)
0.308;-290.6
6(4TJ)
0.271;-290.6
6K(4T)
0.282;-249.4
(6T)(4K)
0.327;-114.4
6T(4Q)
0.338;-270.0
(4J)(6J)
0.326;0.0
4J(6J)
0.332;-135.0
6J(4Q)
0.270;-249.4
(4Q)(6Q)
0.338;41.3
4K(6Q)
0.382;-208.1
4K(6K)
0.318;-52.5
79(47)
0.347;-238.1
(47)(7Q)
0.329;-41.3
(478T)
0.287;-331.9
88(47)
0.327;-238.1
(47)(8J)
0.300;-176.2
9(479)
0.263;-196.9
K(479)
0.337;-249.4
9(47Q)
0.329;-270.0
J(47T)
0.256;-270.0
TJ(47)
0.323;-270.0
(47JQ)
0.272;-228.7
J(47K)
0.244;-208.1
(47)(QK)
0.296;-52.5
77(49)
0.270;-238.1
477J
0.303;-331.9
78(48)
0.276;-238.1
(48)(7J)
0.274;-176.2
48(78)
0.333;-238.1
4(78J)
0.275;-311.2
4788
0.284;-373.1
478T
0.248;-466.9
478Q
0.281;-425.6
(49)(7T)
0.354;-176.2
7(49K)
0.343;-249.4
4(79J)
0.274;-290.6
4799
0.307;-331.9
479J
0.267;-425.6
479K
0.297;-384.4
7Q(4T)
0.318;-249.4
(7T)(4Q)
0.331;-114.4
4T(7J)
0.304;-270.0
4T(7K)
0.272;-228.7
7(4JK)
0.291;-208.1
4(7JK)
0.323;-208.1
4J(7K)
0.269;-208.1
4Q(7Q)
0.290;-73.1
47QK
0.266;-322.5
89(48)
0.314;-196.9
(48)(8Q)
0.423;0.0
(489J)
0.307;-270.0
(48)(9T)
0.325;-155.6
9(48K)
0.300;-228.7
(48TK)
0.328;-208.1
TQ(48)
0.296;-228.7
K(48J)
0.263;-187.5
Q(48Q)
0.309;-52.5
KK(48)
0.350;-11.2
88(4J)
0.324;-155.6
488K
0.289;-249.4
8J(49)
0.256;-270.0
(89)(4T)
0.333;-155.6
4Q(89)
0.272;-249.4
489T
0.245;-425.6
489Q
0.217;-384.4
(4T)(8J)
0.336;-114.4
4T(8T)
0.290;-135.0
4(8TK)
0.288;-208.1
4T(8Q)
0.370;-228.7
8J(4J)
0.361;-93.7
(8J)(4Q)
0.336;-73.1
4J(8Q)
0.355;-208.1
8Q(4Q)
0.275;-52.5
48QQ
0.316;-187.5
48KK
0.297;-146.2
9(49Q)
0.312;-93.7
J(49T)
0.295;-228.7
TJ(49)
0.254;-228.7
(49JQ)
0.266;-187.5
J(49K)
0.333;-166.9
(49)(QK)
0.280;-11.2
99(4J)
0.326;-114.4
499K
0.306;-208.1
9Q(4T)
0.320;-208.1
(9T)(4Q)
0.346;-73.1
4T(9J)
0.251;-228.7
4T(9K)
0.289;-187.5
9(4JK)
0.273;-166.9
4(9JK)
0.371;-166.9
4J(9K)
0.302;-166.9
4Q(9Q)
0.386;-31.9
49QK
0.311;-281.2
TJ(4T)
0.324;-73.1
(4TJQ)
0.308;-166.9
J(4TK)
0.333;-146.2
(4T)(QK)
0.322;9.4
TT(4Q)
0.314;-52.5
T(4JQ)
0.319;-166.9
4(TJQ)
0.315;-166.9
4T(JQ)
0.348;-166.9
T(4QK)
0.304;-125.6
TQ(4K)
0.323;-125.6
JJ(4J)
0.328;103.1
(4JQK)
0.349;-105.0
4JJJ
0.292;-31.9
JQ(4Q)
0.341;9.4
4JQQ
0.363;-125.6
4JKK
0.375;-84.4
QQ(4K)
0.390;50.6
4KKK
0.322;91.9
55(59)
0.353;-165.0
55(5K)
0.357;-82.5
(56)(58)
0.394;-165.0
5(56J)
0.370;-238.1
5K(56)
0.329;-196.9
56(59)
0.275;-279.4
556J
0.268;-373.1
57(57)
0.297;-165.0
(57)(5T)
0.315;-103.1
5(57K)
0.256;-176.2
55(79)
0.284;-258.8
57(5Q)
0.305;-196.9
5(589)
0.246;-238.1
5J(58)
0.301;-196.9
58(59)
0.296;-238.1
558J
0.324;-331.9
59(59)
0.333;-82.5
(59)(5Q)
0.315;-20.6
559T
0.306;-331.9
55(9K)
0.368;-135.0
(5T)(5Q)
0.323;0.0
55TJ
0.335;-290.6
5J(5J)
0.315;0.0
5J(5Q)
0.280;-114.4
5(5QK)
0.345;-73.1
5K(5K)
0.423;82.5
68(56)
0.238;-279.4
(56)(6J)
0.314;-82.5
7(567)
0.269;-279.4
J(567)
0.333;-331.9
78(56)
0.224;-393.8
(56)(7J)
0.308;-196.9
8(568)
0.253;-238.1
Q(568)
0.278;-290.6
(56)(8T)
0.309;-196.9
8(56K)
0.280;-270.0
(569Q)
0.314;-270.0
9(56J)
0.251;-290.6
9K(56)
0.265;-249.4
TT(56)
0.294;-155.6
(56)(TK)
0.382;-93.8
J(56Q)
0.381;-228.7
K(56Q)
0.281;-187.5
66(57)
0.318;-300.0
5669
0.292;-393.8
56(6Q)
0.376;-196.9
(57)(68)
0.298;-258.8
6(57J)
0.250;-331.9
6K(57)
0.303;-290.6
(67)(5T)
0.345;-217.5
5Q(67)
0.278;-311.2
5678
0.251;-528.7
567T
0.235;-487.5
567Q
0.274;-446.2
(58)(69)
0.292;-217.5
6(58Q)
0.306;-290.6
5(689)
0.259;-352.5
(68)(5Q)
0.293;-155.6
58(69)
0.301;-352.5
58(6J)
0.264;-311.2
58(6K)
0.271;-270.0
6(59J)
0.253;-290.6
6K(59)
0.331;-249.4
(69)(5Q)
0.306;-135.0
59(6T)
0.266;-311.2
59(6Q)
0.272;-270.0
6T(5T)
0.364;-155.6
(5T)(6K)
0.291;-93.8
5Q(6T)
0.278;-249.4
56TJ
0.230;-405.0
56TK
0.292;-363.7
6K(5J)
0.326;-208.1
56JJ
0.258;-249.4
56JK
0.300;-343.1
5(6QK)
0.308;-187.5
6K(5K)
0.335;-31.9
(57)(79)
0.343;-82.5
7(57Q)
0.322;-155.6
9(578)
0.306;-331.9
K(578)
0.244;-249.4
8(57J)
0.277;-290.6
8K(57)
0.305;-249.4
(579K)
0.342;-228.7
9J(57)
0.312;-270.0
(57TJ)
0.307;-249.4
(57)(TJ)
0.328;-114.4
J(57J)
0.365;-93.7
JQ(57)
0.295;-208.1
Q(57K)
0.297;-166.9
5778
0.226;-373.1
57(7J)
0.290;-176.2
(58)(78)
0.373;-82.5
7(58J)
0.328;-290.6
7K(58)
0.256;-249.4
(78)(5J)
0.315;-155.6
5K(78)
0.282;-249.4
57(8T)
0.316;-311.2
57(8Q)
0.317;-270.0
7(59T)
0.336;-290.6
7Q(59)
0.299;-249.4
(79)(5J)
0.277;-135.0
5K(79)
0.288;-228.7
57(9J)
0.339;-270.0
57(9K)
0.271;-228.7
(5T)(7Q)
0.360;-93.8
5J(7T)
0.302;-249.4
7T(5J)
0.292;-249.4
7T(5K)
0.306;-208.1
7Q(5J)
0.278;-208.1
(7J)(5K)
0.318;-52.5
7J(5K)
0.356;-187.5
7K(5Q)
0.304;-166.9
57(QK)
0.296;-166.9
(58)(89)
0.279;-41.3
8(58Q)
0.361;-114.4
T(589)
0.294;-270.0
9(58T)
0.294;-270.0
9Q(58)
0.277;-228.7
Q(58T)
0.279;-208.1
(58)(TQ)
0.323;-73.1
(58JK)
0.279;-166.9
JK(58)
0.263;-166.9
K(58K)
0.430;9.4
588T
0.292;-290.6
58(8K)
0.324;-93.7
(59)(8J)
0.283;-114.4
59(89)
0.246;-155.6
5(89Q)
0.284;-228.7
58(9T)
0.253;-270.0
58(9Q)
0.342;-228.7
8(5TJ)
0.312;-228.7
8K(5T)
0.287;-187.5
(8T)(5K)
0.360;-52.5
8T(5Q)
0.271;-208.1
(5J)(8J)
0.403;61.9
5J(8J)
0.335;-73.1
8J(5Q)
0.282;-187.5
(5Q)(8Q)
0.370;103.1
5K(8Q)
0.289;-146.2
5K(8K)
0.283;9.4
9J(59)
0.307;-93.7
(59TJ)
0.342;-208.1
(59)(TJ)
0.329;-73.1
J(59J)
0.326;-52.5
JQ(59)
0.358;-166.9
Q(59K)
0.318;-125.6
599T
0.358;-249.4
59(9K)
0.321;-52.5
(5T)(9Q)
0.303;-52.5
5J(9T)
0.291;-208.1
9T(5J)
0.280;-208.1
9T(5K)
0.335;-166.9
9Q(5J)
0.318;-166.9
(9J)(5K)
0.391;-11.2
9J(5K)
0.293;-146.2
9K(5Q)
0.297;-125.6
59(QK)
0.341;-125.6
(5T)(TJ)
0.377;82.5
J(5TJ)
0.363;-31.9
JQ(5T)
0.291;-146.2
Q(5TK)
0.383;-105.0
5TTJ
0.280;-187.5
TJ(5J)
0.380;-31.9
(TJ)(5Q)
0.372;-11.2
5J(TQ)
0.274;-146.2
TQ(5Q)
0.368;9.4
5TQQ
0.275;-125.6
5TKK
0.274;-84.4
Q(5JQ)
0.389;30.0
KK(5J)
0.347;71.3
(5Q)(JQ)
0.359;165.0
5K(JQ)
0.299;-84.4
5K(JK)
0.323;71.3
5QQQ
0.283;50.6
KK(5K)
0.303;247.5
6669
0.261;-238.1
666K
0.358;-155.6
69(67)
0.294;-217.5
(67)(6Q)
0.276;-20.6
6678
0.326;-373.1
66(7J)
0.293;-176.2
(68)(68)
0.412;52.5
6(68J)
0.296;-155.6
6K(68)
0.312;-114.4
68(6J)
0.282;-155.6
668K
0.351;-249.4
6J(69)
0.276;-135.0
69(6T)
0.345;-155.6
669Q
0.315;-249.4
6J(6T)
0.391;-114.4
6T(6J)
0.287;-114.4
66TK
0.265;-208.1
6K(6J)
0.308;-52.5
(6Q)(6Q)
0.351;217.5
66QK
0.298;-166.9
7(679)
0.358;-196.9
7J(67)
0.367;-155.6
(6789)
0.299;-311.2
(678K)
0.355;-228.7
8T(67)
0.322;-290.6
(67)(8K)
0.333;-93.8
Q(679)
0.278;-228.7
(67)(9J)
0.373;-114.4
T(67T)
0.359;-114.4
T(67J)
0.320;-228.7
TK(67)
0.273;-187.5
(67)(JQ)
0.306;-52.5
QQ(67)
0.296;-31.9
67(78)
0.321;-217.5
77(6J)
0.318;-155.6
677K
0.269;-249.4
7T(68)
0.252;-290.6
(68)(7K)
0.313;-93.8
6T(78)
0.246;-290.6
6(78K)
0.300;-228.7
68(7T)
0.313;-290.6
68(7Q)
0.296;-249.4
79(69)
0.271;-155.6
(69)(7Q)
0.319;-93.8
6T(79)
0.365;-270.0
6(79K)
0.323;-208.1
69(7J)
0.320;-249.4
69(7K)
0.311;-208.1
7(6TQ)
0.277;-208.1
6(7TJ)
0.312;-228.7
67TT
0.259;-249.4
67TQ
0.279;-343.1
(6J)(7Q)
0.325;-52.5
6Q(7J)
0.299;-187.5
67JQ
0.292;-322.5
(6Q)(7K)
0.402;-11.2
6Q(7K)
0.387;-146.2
8(689)
0.321;-155.6
8J(68)
0.298;-114.4
(689T)
0.307;-249.4
99(68)
0.314;-135.0
(68)(9Q)
0.334;-73.1
(68TQ)
0.328;-187.5
T(68Q)
0.332;-187.5
Q(68J)
0.359;-166.9
(68)(JK)
0.312;-11.2
QK(68)
0.289;-125.6
68(8T)
0.280;-135.0
88(6K)
0.376;-73.1
8(69J)
0.278;-228.7
8K(69)
0.325;-187.5
(89)(6Q)
0.387;-73.1
69(8T)
0.244;-249.4
69(8Q)
0.245;-208.1
8T(6T)
0.316;-93.7
(6T)(8K)
0.325;-31.9
6Q(8T)
0.276;-187.5
68TJ
0.250;-343.1
68TK
0.266;-301.9
8K(6J)
0.342;-146.2
68JJ
0.269;-187.5
68JK
0.261;-281.2
6(8QK)
0.318;-125.6
8K(6K)
0.340;30.0
(69)(9J)
0.379;61.9
T(69T)
0.361;-73.1
T(69J)
0.295;-187.5
TK(69)
0.340;-146.2
(69)(JQ)
0.306;-11.2
QQ(69)
0.382;9.4
69(9T)
0.260;-93.7
99(6K)
0.270;-31.9
9(6TQ)
0.333;-166.9
6(9TJ)
0.355;-187.5
69TT
0.279;-208.1
69TQ
0.294;-301.9
(6J)(9Q)
0.283;-11.2
6Q(9J)
0.306;-146.2
69JQ
0.346;-281.2
(6Q)(9K)
0.347;30.0
6Q(9K)
0.322;-105.0
T(6TJ)
0.391;-31.9
TK(6T)
0.287;9.4
(6T)(JQ)
0.390;9.4
QQ(6T)
0.352;30.0
6T(TJ)
0.323;-31.9
(6J)(TJ)
0.372;123.7
6J(TJ)
0.325;-11.2
TJ(6Q)
0.317;-125.6
(6Q)(TQ)
0.365;165.0
6K(TQ)
0.300;-84.4
6K(TK)
0.417;71.3
JK(6J)
0.355;50.6
K(6JK)
0.306;91.9
6JJK
0.277;-84.4
6(JQK)
0.311;-63.7
JK(6K)
0.356;91.9
KK(6Q)
0.342;112.5
6QKK
0.392;-22.5
77(7T)
0.338;-20.6
(78)(78)
0.363;93.8
7(78J)
0.263;-114.4
7K(78)
0.326;-73.1
78(7J)
0.311;-114.4
778K
0.283;-208.1
7J(79)
0.364;-93.7
79(7T)
0.336;-114.4
779Q
0.261;-208.1
7J(7T)
0.328;-73.1
7T(7J)
0.336;-73.1
77TK
0.308;-166.9
7K(7J)
0.374;-11.2
(7Q)(7Q)
0.368;258.8
77QK
0.274;-125.6
8(78T)
0.292;-114.4
8Q(78)
0.315;-73.1
J(789)
0.278;-208.1
9T(78)
0.327;-228.7
(78)(9K)
0.296;-31.9
K(78T)
0.304;-146.2
T(78K)
0.325;-146.2
JJ(78)
0.371;-31.9
(78QK)
0.387;-105.0
7888
0.340;-155.6
78(8J)
0.259;-93.7
(79)(89)
0.289;20.6
8(79Q)
0.236;-187.5
7(89T)
0.237;-228.7
(89)(7K)
0.347;-31.9
89(7J)
0.297;-208.1
89(7K)
0.334;-166.9
8J(7T)
0.300;-187.5
(8T)(7J)
0.358;-52.5
7K(8T)
0.319;-146.2
78(TQ)
0.331;-166.9
8(7JQ)
0.305;-146.2
7(8JQ)
0.361;-146.2
78(JQ)
0.275;-146.2
8(7QK)
0.262;-105.0
8Q(7K)
0.333;-105.0
99(79)
0.276;41.2
(79)(9Q)
0.373;103.1
(79TQ)
0.263;-146.2
T(79Q)
0.364;-146.2
Q(79J)
0.364;-125.6
(79)(JK)
0.326;30.0
QK(79)
0.353;-84.4
79(9J)
0.369;-52.5
(7T)(9T)
0.327;82.5
9(7TK)
0.341;-125.6
7(9TQ)
0.310;-146.2
79(TJ)
0.279;-166.9
79(TK)
0.298;-125.6
(7J)(9K)
0.416;30.0
7K(9J)
0.397;-105.0
79(JK)
0.351;-105.0
(9Q)(7K)
0.335;50.6
(7K)(9K)
0.413;206.3
T(7TQ)
0.402;9.4
Q(7TJ)
0.312;-105.0
(7T)(JK)
0.319;50.6
QK(7T)
0.259;-63.7
7T(TQ)
0.303;9.4
(7J)(TQ)
0.324;30.0
7Q(TJ)
0.290;-105.0
7TJQ
0.340;-240.0
(7Q)(TK)
0.328;71.3
7Q(TK)
0.341;-63.7
J(7JQ)
0.327;50.6
K(7JQ)
0.368;-43.1
JJ(7Q)
0.328;50.6
J(7QK)
0.283;-43.1
JQ(7K)
0.270;-43.1
QQ(7Q)
0.358;226.9
7Q(QK)
0.336;112.5
8888
0.291;0.0
888Q
0.295;-52.5
8(89J)
0.293;-52.5
8K(89)
0.370;-11.2
89(8Q)
0.273;-31.9
8(8TJ)
0.316;-31.9
8K(8T)
0.340;9.4
8T(8K)
0.312;9.4
8(8JK)
0.387;30.0
88(JK)
0.362;30.0
8Q(8K)
0.345;50.6
(89)(9T)
0.363;82.5
9(89K)
0.374;9.4
(89TK)
0.374;-105.0
TQ(89)
0.371;-125.6
K(89J)
0.322;-84.4
Q(89Q)
0.297;50.6
KK(89)
0.381;91.9
99(8Q)
0.355;-11.2
9(8TJ)
0.279;-146.2
9K(8T)
0.283;-105.0
(9T)(8K)
0.291;30.0
9T(8Q)
0.358;-125.6
(8J)(9J)
0.381;144.4
8J(9J)
0.303;9.4
9J(8Q)
0.338;-105.0
(8Q)(9Q)
0.433;185.6
8K(9Q)
0.283;-63.7
8K(9K)
0.306;91.9
TQ(8T)
0.406;30.0
K(8TJ)
0.310;-63.7
Q(8TQ)
0.333;71.3
KK(8T)
0.388;112.5
