AAAA
0.329;495.0
5AAA
0.292;174.4
9AAA
0.286;256.9
KAAA
0.343;339.4
4A(2A)
0.200;-93.7
(2A)(7A)
0.341;103.1
A(2TA)
0.241;30.0
QA(2A)
0.239;71.3
2A(4A)
0.261;-93.7
26AA
0.229;-187.5
AA(29)
0.278;9.4
2A(QA)
0.217;71.3
A(34A)
0.229;-73.1
6A(3A)
0.269;-31.9
(3A)(9A)
0.307;165.0
A(3QA)
0.297;91.9
AA(34)
0.232;-73.1
3A(7A)
0.236;-11.2
39AA
0.219;-105.0
AA(3Q)
0.249;91.9
(4A)(5A)
0.268;103.1
A(48A)
0.207;30.0
TA(4A)
0.257;71.3
(4A)(KA)
0.290;268.1
46AA
0.172;-146.2
AA(49)
0.294;50.6
4A(QA)
0.204;112.5
A(56A)
0.282;9.4
8A(5A)
0.274;50.6
(5A)(JA)
0.302;247.5
55AA
0.218;-11.2
AA(58)
0.227;50.6
5A(JA)
0.257;112.5
5KAA
0.291;18.7
8A(6A)
0.318;71.3
(6A)(JA)
0.315;268.1
66AA
0.264;30.0
AA(69)
0.268;91.9
6A(QA)
0.249;153.7
A(78A)
0.294;91.9
TA(7A)
0.300;133.1
(7A)(KA)
0.324;330.0
79AA
0.282;-22.5
AA(7Q)
0.308;174.4
(8A)(9A)
0.288;268.1
A(8QA)
0.311;195.0
AA(89)
0.291;133.1
8A(QA)
0.333;195.0
A(9TA)
0.242;174.4
QA(9A)
0.263;215.6
9A(JA)
0.339;195.0
9KAA
0.296;101.3
QA(TA)
0.243;236.2
TA(QA)
0.309;236.2
A(JQA)
0.289;256.9
AA(JQ)
0.299;256.9
(QA)(KA)
0.387;433.1
KKAA
0.279;318.8
2(25A)
0.195;-320.6
27(2A)
0.174;-279.4
(2T)(2A)
0.229;-82.5
2(2KA)
0.236;-155.6
(236A)
0.173;-414.4
(23TA)
0.191;-331.9
33(2A)
0.176;-341.2
(36)(2A)
0.215;-279.4
3(29A)
0.185;-352.5
3J(2A)
0.179;-311.2
(245A)
0.178;-414.4
(249A)
0.191;-331.9
(24KA)
0.157;-249.4
46(2A)
0.196;-393.8
(49)(2A)
0.277;-196.9
4(2QA)
0.159;-270.0
6(25A)
0.138;-373.1
T(25A)
0.171;-290.6
5(26A)
0.146;-373.1
58(2A)
0.177;-331.9
(5J)(2A)
0.220;-135.0
6(26A)
0.231;-217.5
T(26A)
0.205;-270.0
6(27A)
0.229;-331.9
69(2A)
0.231;-290.6
(6Q)(2A)
0.248;-93.8
(279A)
0.180;-270.0
(27KA)
0.211;-187.5
79(2A)
0.168;-270.0
(7Q)(2A)
0.234;-73.1
(28TA)
0.256;-228.7
88(2A)
0.266;-135.0
(8J)(2A)
0.225;-73.1
9(29A)
0.194;-93.7
K(29A)
0.193;-146.2
9(2QA)
0.248;-166.9
J(2TA)
0.225;-166.9
TJ(2A)
0.204;-166.9
(2JQA)
0.283;-125.6
J(2KA)
0.238;-105.0
(QK)(2A)
0.302;50.6
22(4A)
0.216;-341.2
226A
0.194;-435.0
2A(29)
0.165;-238.1
22(QA)
0.206;-176.2
2(34A)
0.139;-455.6
26(3A)
0.167;-414.4
(29)(3A)
0.242;-217.5
2(3QA)
0.157;-290.6
A(234)
0.137;-455.6
(23)(7A)
0.200;-258.8
9A(23)
0.168;-352.5
A(23Q)
0.207;-290.6
2A(34)
0.173;-455.6
2A(36)
0.173;-414.4
2A(38)
0.166;-373.1
2A(3T)
0.223;-331.9
2A(3Q)
0.184;-290.6
2(45A)
0.205;-414.4
27(4A)
0.145;-373.1
(2T)(4A)
0.207;-176.2
2(4KA)
0.229;-249.4
A(246)
0.153;-393.8
(24)(9A)
0.188;-196.9
JA(24)
0.209;-290.6
24(5A)
0.154;-414.4
24(7A)
0.144;-373.1
24(9A)
0.203;-331.9
24(JA)
0.186;-290.6
24(KA)
0.212;-249.4
26(5A)
0.224;-373.1
(29)(5A)
0.165;-176.2
2(5QA)
0.226;-249.4
A(256)
0.199;-373.1
(25)(9A)
0.238;-176.2
JA(25)
0.203;-270.0
25(6A)
0.211;-373.1
25(8A)
0.197;-331.9
25(TA)
0.146;-290.6
25(QA)
0.210;-249.4
(26)(6A)
0.244;-82.5
2(69A)
0.218;-290.6
2J(6A)
0.198;-249.4
(26)(7A)
0.196;-196.9
9A(26)
0.210;-290.6
A(26Q)
0.166;-228.7
2A(67)
0.177;-331.9
2A(69)
0.168;-290.6
2A(6J)
0.150;-249.4
2A(6K)
0.233;-208.1
(29)(7A)
0.281;-135.0
2(7QA)
0.193;-208.1
A(278)
0.203;-290.6
(27)(JA)
0.228;-93.8
KA(27)
0.247;-187.5
2A(79)
0.196;-270.0
2A(7J)
0.222;-228.7
2A(7K)
0.239;-187.5
(2T)(8A)
0.224;-93.8
2(8KA)
0.213;-166.9
A(28T)
0.234;-228.7
(28)(KA)
0.202;-31.9
28(TA)
0.230;-228.7
28(QA)
0.216;-187.5
(29)(9A)
0.262;41.3
2(9QA)
0.226;-166.9
A(29T)
0.216;-208.1
(29)(KA)
0.198;-11.2
29(JA)
0.244;-187.5
29(KA)
0.188;-146.2
2J(TA)
0.218;-166.9
(2T)(JA)
0.215;-31.9
KA(2T)
0.191;-125.6
2A(TQ)
0.192;-146.2
2(JQA)
0.250;-125.6
A(2JQ)
0.262;-125.6
2A(JQ)
0.233;-125.6
2(QKA)
0.284;-84.4
2Q(KA)
0.228;-84.4
33(3A)
0.226;-185.6
(36)(3A)
0.222;-123.7
3(39A)
0.215;-196.9
3J(3A)
0.217;-155.6
(345A)
0.143;-393.8
(349A)
0.151;-311.2
(34KA)
0.196;-228.7
46(3A)
0.135;-373.1
(49)(3A)
0.227;-176.2
4(3QA)
0.218;-249.4
6(35A)
0.148;-352.5
T(35A)
0.209;-270.0
5(36A)
0.190;-352.5
58(3A)
0.219;-311.2
(5J)(3A)
0.225;-114.4
6(36A)
0.247;-196.9
T(36A)
0.172;-249.4
6(37A)
0.174;-311.2
69(3A)
0.177;-270.0
(6Q)(3A)
0.269;-73.1
(379A)
0.230;-249.4
(37KA)
0.193;-166.9
79(3A)
0.192;-249.4
(7Q)(3A)
0.214;-52.5
(38TA)
0.197;-208.1
88(3A)
0.218;-114.4
(8J)(3A)
0.256;-52.5
9(39A)
0.239;-73.1
K(39A)
0.186;-125.6
9(3QA)
0.231;-146.2
J(3TA)
0.183;-146.2
TJ(3A)
0.211;-146.2
(3JQA)
0.183;-105.0
J(3KA)
0.210;-84.4
(QK)(3A)
0.307;71.3
33(5A)
0.199;-279.4
337A
0.186;-373.1
3A(3T)
0.187;-176.2
33(KA)
0.252;-114.4
3(46A)
0.189;-373.1
38(4A)
0.212;-331.9
(3J)(4A)
0.212;-135.0
4A(34)
0.227;-279.4
A(347)
0.219;-352.5
(34)(TA)
0.223;-155.6
QA(34)
0.192;-249.4
345A
0.175;-528.7
347A
0.152;-487.5
349A
0.171;-446.2
34JA
0.173;-405.0
34KA
0.205;-363.7
37(5A)
0.170;-331.9
(3T)(5A)
0.212;-135.0
3(5KA)
0.207;-208.1
A(357)
0.211;-331.9
(35)(TA)
0.252;-135.0
QA(35)
0.174;-228.7
356A
0.134;-487.5
358A
0.182;-446.2
35TA
0.160;-405.0
35QA
0.216;-363.7
(37)(6A)
0.202;-176.2
3(6TA)
0.207;-249.4
3Q(6A)
0.165;-208.1
(36)(8A)
0.242;-155.6
TA(36)
0.243;-249.4
A(36K)
0.229;-187.5
6A(38)
0.170;-290.6
6A(3T)
0.165;-249.4
6A(3Q)
0.195;-208.1
37(7A)
0.177;-155.6
(3T)(7A)
0.226;-93.8
3(7KA)
0.176;-166.9
A(379)
0.176;-249.4
(37)(QA)
0.254;-52.5
7A(38)
0.166;-270.0
7A(3T)
0.158;-228.7
7A(3Q)
0.207;-187.5
38(8A)
0.192;-114.4
(3J)(8A)
0.224;-52.5
8A(38)
0.247;-114.4
A(38J)
0.228;-187.5
388A
0.199;-249.4
38TA
0.180;-343.1
38QA
0.171;-301.9
(3T)(9A)
0.204;-52.5
3(9KA)
0.190;-125.6
A(39J)
0.248;-166.9
399A
0.213;-208.1
39JA
0.162;-301.9
39KA
0.169;-260.6
3Q(TA)
0.271;-125.6
(3T)(QA)
0.207;9.4
TA(3J)
0.173;-146.2
TA(3K)
0.234;-105.0
3(JKA)
0.228;-84.4
A(3JK)
0.281;-84.4
JA(3K)
0.251;-84.4
QA(3Q)
0.266;50.6
3QKA
0.178;-198.7
45(4A)
0.205;-238.1
(48)(4A)
0.239;-41.3
4(4JA)
0.219;-114.4
4K(4A)
0.226;-73.1
(459A)
0.237;-270.0
(45KA)
0.279;-187.5
57(4A)
0.203;-311.2
(5T)(4A)
0.215;-114.4
5(4KA)
0.227;-187.5
(469A)
0.178;-249.4
(46KA)
0.171;-166.9
68(4A)
0.208;-270.0
(6J)(4A)
0.216;-73.1
7(47A)
0.200;-135.0
J(47A)
0.203;-187.5
78(4A)
0.241;-249.4
(7J)(4A)
0.224;-52.5
8(48A)
0.228;-93.7
Q(48A)
0.179;-146.2
(8T)(4A)
0.230;-52.5
8(4KA)
0.188;-125.6
(49QA)
0.257;-125.6
9(4JA)
0.185;-146.2
9K(4A)
0.246;-105.0
TT(4A)
0.206;-11.2
(TK)(4A)
0.246;50.6
J(4QA)
0.245;-84.4
K(4QA)
0.227;-43.1
44(5A)
0.240;-238.1
447A
0.197;-331.9
4A(4T)
0.232;-135.0
44(KA)
0.251;-73.1
4(57A)
0.227;-311.2
49(5A)
0.199;-270.0
(4Q)(5A)
0.261;-73.1
6A(45)
0.163;-331.9
A(459)
0.245;-270.0
(45)(QA)
0.214;-73.1
5A(46)
0.201;-331.9
5A(48)
0.193;-290.6
5A(4T)
0.220;-249.4
5A(4Q)
0.226;-208.1
46(6A)
0.184;-176.2
(49)(6A)
0.210;-114.4
4(6QA)
0.211;-187.5
A(467)
0.186;-290.6
(46)(TA)
0.260;-93.8
QA(46)
0.214;-187.5
467A
0.167;-425.6
469A
0.191;-384.4
46JA
0.207;-343.1
46KA
0.248;-301.9
49(7A)
0.159;-228.7
(4Q)(7A)
0.270;-31.9
8A(47)
0.237;-249.4
A(47J)
0.207;-187.5
477A
0.233;-270.0
479A
0.163;-363.7
47JA
0.176;-322.5
47KA
0.179;-281.2
4T(8A)
0.262;-187.5
(4K)(8A)
0.248;9.4
TA(48)
0.225;-187.5
A(48K)
0.201;-125.6
8A(4T)
0.212;-187.5
8A(4Q)
0.235;-146.2
49(9A)
0.217;-52.5
(4Q)(9A)
0.262;9.4
TA(49)
0.215;-166.9
A(49K)
0.262;-105.0
9A(4J)
0.225;-146.2
9A(4K)
0.230;-105.0
4(TQA)
0.175;-105.0
A(4TJ)
0.208;-125.6
4TTA
0.176;-146.2
4TQA
0.230;-240.0
(4Q)(JA)
0.238;50.6
QA(4J)
0.237;-84.4
4JQA
0.182;-219.4
(4K)(QA)
0.260;91.9
QA(4K)
0.254;-43.1
5(56A)
0.231;-176.2
58(5A)
0.247;-135.0
(5J)(5A)
0.237;61.9
6(56A)
0.237;-155.6
T(56A)
0.186;-208.1
6(57A)
0.219;-270.0
69(5A)
0.195;-228.7
(6Q)(5A)
0.242;-31.9
(579A)
0.211;-208.1
(57KA)
0.213;-125.6
79(5A)
0.223;-208.1
(7Q)(5A)
0.225;-11.2
(58TA)
0.220;-166.9
88(5A)
0.185;-73.1
(8J)(5A)
0.284;-11.2
9(59A)
0.307;-31.9
K(59A)
0.222;-84.4
9(5QA)
0.206;-105.0
J(5TA)
0.230;-105.0
TJ(5A)
0.224;-105.0
(5JQA)
0.266;-63.7
J(5KA)
0.278;-43.1
(QK)(5A)
0.236;112.5
55(7A)
0.209;-155.6
559A
0.259;-249.4
5A(5Q)
0.234;-52.5
(57)(6A)
0.189;-135.0
5(6TA)
0.212;-208.1
5Q(6A)
0.223;-166.9
(56)(8A)
0.246;-114.4
TA(56)
0.155;-208.1
A(56K)
0.182;-146.2
6A(58)
0.159;-249.4
6A(5T)
0.179;-208.1
6A(5Q)
0.189;-166.9
57(7A)
0.253;-114.4
(5T)(7A)
0.231;-52.5
5(7KA)
0.177;-125.6
A(579)
0.219;-208.1
(57)(QA)
0.215;-11.2
7A(58)
0.191;-228.7
7A(5T)
0.170;-187.5
7A(5Q)
0.208;-146.2
58(8A)
0.194;-73.1
(5J)(8A)
0.296;-11.2
8A(58)
0.249;-73.1
A(58J)
0.204;-146.2
588A
0.213;-208.1
58TA
0.160;-301.9
58QA
0.211;-260.6
(5T)(9A)
0.276;-11.2
5(9KA)
0.238;-84.4
A(59J)
0.202;-125.6
599A
0.203;-166.9
59JA
0.195;-260.6
59KA
0.162;-219.4
5Q(TA)
0.262;-84.4
(5T)(QA)
0.256;50.6
TA(5J)
0.211;-105.0
TA(5K)
0.261;-63.7
5(JKA)
0.236;-43.1
A(5JK)
0.266;-43.1
JA(5K)
0.254;-43.1
QA(5Q)
0.296;91.9
5QKA
0.259;-157.5
67(6A)
0.281;-114.4
(6T)(6A)
0.221;82.5
6(6KA)
0.254;9.4
(67TA)
0.197;-166.9
77(6A)
0.264;-93.7
(7T)(6A)
0.207;-31.9
7(6KA)
0.174;-105.0
(68JA)
0.219;-125.6
(89)(6A)
0.209;-31.9
8(6QA)
0.217;-105.0
T(69A)
0.233;-125.6
9(6TA)
0.192;-125.6
9Q(6A)
0.233;-84.4
Q(6TA)
0.218;-63.7
(TQ)(6A)
0.282;71.3
(6JKA)
0.206;-22.5
JK(6A)
0.254;-22.5
K(6KA)
0.228;153.7
668A
0.150;-228.7
6A(6J)
0.241;-31.9
(67)(7A)
0.297;41.3
6(7TA)
0.279;-166.9
6Q(7A)
0.211;-125.6
(67)(9A)
0.193;-52.5
JA(67)
0.244;-146.2
67(8A)
0.175;-208.1
67(TA)
0.240;-166.9
67(QA)
0.250;-125.6
(68)(8A)
0.246;82.5
6(8JA)
0.225;-125.6
6K(8A)
0.292;-84.4
(68)(JA)
0.243;9.4
KA(68)
0.231;-84.4
6A(8T)
0.247;-146.2
6A(8Q)
0.251;-105.0
6(9TA)
0.242;-125.6
6Q(9A)
0.199;-84.4
(69)(JA)
0.215;30.0
KA(69)
0.248;-63.7
6A(9J)
0.193;-105.0
6A(9K)
0.254;-63.7
(6Q)(TA)
0.281;71.3
JA(6T)
0.200;-84.4
6T(JA)
0.246;-84.4
6T(KA)
0.184;-43.1
6Q(JA)
0.220;-43.1
(6J)(KA)
0.250;112.5
6J(KA)
0.264;-22.5
6K(QA)
0.218;-1.9
6A(QK)
0.243;-1.9
(78)(7A)
0.277;82.5
7(7JA)
0.228;9.4
7K(7A)
0.239;50.6
(78QA)
0.233;-84.4
8(7TA)
0.247;-125.6
8Q(7A)
0.274;-84.4
J(79A)
0.225;-84.4
9T(7A)
0.211;-105.0
(9K)(7A)
0.232;91.9
K(7TA)
0.253;-22.5
T(7KA)
0.270;-22.5
JJ(7A)
0.320;91.9
(7QKA)
0.212;18.7
777A
0.251;-73.1
7A(7T)
0.263;-11.2
77(KA)
0.224;50.6
7(8TA)
0.255;-125.6
7Q(8A)
0.203;-84.4
(78)(TA)
0.257;9.4
QA(78)
0.256;-84.4
789A
0.241;-281.2
78JA
0.206;-240.0
78KA
0.203;-198.7
7J(9A)
0.244;-84.4
(79)(TA)
0.285;30.0
QA(79)
0.238;-63.7
79TA
0.149;-240.0
79QA
0.255;-198.7
(7J)(TA)
0.293;71.3
TA(7T)
0.273;50.6
A(7TK)
0.236;-22.5
TA(7Q)
0.272;-43.1
7J(JA)
0.307;91.9
(7J)(QA)
0.251;112.5
JA(7Q)
0.250;-22.5
7Q(QA)
0.299;133.1
7QQA
0.207;-1.9
7KKA
0.305;39.4
8(8JA)
0.277;50.6
8K(8A)
0.227;91.9
(89KA)
0.300;-22.5
9J(8A)
0.281;-63.7
(8TJA)
0.298;-43.1
(TJ)(8A)
0.257;91.9
J(8JA)
0.303;112.5
JQ(8A)
0.272;-1.9
Q(8KA)
0.230;39.4
889A
0.234;-125.6
8A(8Q)
0.235;71.3
(8T)(9A)
0.255;50.6
8(9KA)
0.265;-22.5
A(89J)
0.229;-63.7
899A
0.216;-105.0
89JA
0.223;-198.7
89KA
0.260;-157.5
8Q(TA)
0.184;-22.5
(8T)(QA)
0.249;112.5
TA(8J)
0.193;-43.1
TA(8K)
0.217;-1.9
8(JKA)
0.301;18.7
A(8JK)
0.202;18.7
JA(8K)
0.221;18.7
QA(8Q)
0.269;153.7
8QKA
0.272;-95.6
9T(9A)
0.262;71.3
(9K)(9A)
0.263;268.1
K(9TA)
0.229;18.7
T(9KA)
0.221;18.7
JJ(9A)
0.292;133.1
(9QKA)
0.252;60.0
999A
0.207;50.6
9A(9Q)
0.238;112.5
(9J)(TA)
0.311;112.5
TA(9T)
0.246;91.9
A(9TK)
0.241;18.7
TA(9Q)
0.214;-1.9
9J(JA)
0.239;133.1
(9J)(QA)
0.227;153.8
JA(9Q)
0.291;18.7
9Q(QA)
0.276;174.4
9QQA
0.266;39.4
9KKA
0.296;80.6
T(TKA)
0.339;174.4
JJ(TA)
0.235;153.7
(TQKA)
0.251;80.6
TTTA
0.282;112.5
TA(TK)
0.231;174.4
(TK)(JA)
0.283;195.0
KA(TJ)
0.233;60.0
TA(JK)
0.230;60.0
(TQ)(KA)
0.251;215.6
(TK)(KA)
0.310;371.3
J(JKA)
0.290;215.6
(QK)(JA)
0.286;236.3
JJ(KA)
0.262;215.6
QA(JQ)
0.269;215.6
JQKA
0.219;-33.7
QK(QA)
0.328;256.9
QK(KA)
0.317;277.5
22(24)
0.218;-453.8
22(28)
0.178;-371.2
22(2Q)
0.154;-288.7
24(23)
0.163;-568.1
(23)(27)
0.194;-371.3
2(23T)
0.194;-444.4
2Q(23)
0.164;-403.1
23(25)
0.140;-547.5
2237
0.138;-641.2
22(3T)
0.159;-444.4
23(2K)
0.168;-382.5
2(246)
0.161;-506.2
28(24)
0.174;-465.0
(24)(2J)
0.211;-268.1
2244
0.141;-547.5
22(47)
0.155;-485.6
24(2T)
0.183;-423.8
224Q
0.144;-517.5
26(25)
0.214;-485.6
(25)(29)
0.185;-288.7
2(25Q)
0.161;-361.9
22(56)
0.153;-485.6
25(29)
0.161;-423.8
225J
0.212;-517.5
26(26)
0.151;-330.0
(26)(29)
0.216;-268.1
2(26Q)
0.193;-341.2
22(67)
0.183;-444.4
26(2T)
0.168;-382.5
226Q
0.172;-476.2
28(27)
0.197;-403.1
(27)(2J)
0.224;-206.3
2277
0.198;-423.8
22(7T)
0.164;-361.9
27(2K)
0.192;-300.0
2(28T)
0.215;-341.2
2Q(28)
0.205;-300.0
28(2T)
0.180;-341.2
228Q
0.140;-435.0
2T(29)
0.189;-320.6
(29)(2K)
0.255;-123.7
229J
0.151;-435.0
2T(2T)
0.245;-165.0
(2T)(2K)
0.239;-103.1
22TQ
0.167;-393.8
2Q(2J)
0.181;-238.1
2J(2K)
0.230;-217.5
22QQ
0.202;-217.5
3(234)
0.144;-547.5
36(23)
0.171;-506.2
(23)(39)
0.188;-309.4
3(23Q)
0.198;-382.5
5(234)
0.144;-641.2
9(234)
0.161;-558.8
K(234)
0.153;-476.2
4(237)
0.129;-600.0
49(23)
0.163;-558.8
(23)(4Q)
0.155;-361.9
(2357)
0.176;-579.4
(235J)
0.184;-496.9
(23)(56)
0.195;-465.0
5(239)
0.145;-538.1
5J(23)
0.126;-496.9
(2367)
0.173;-558.8
(236J)
0.188;-476.2
(23)(67)
0.168;-423.8
6(23T)
0.167;-496.9
6Q(23)
0.169;-455.6
9(237)
0.133;-496.9
K(237)
0.186;-414.4
7(23T)
0.165;-476.2
7Q(23)
0.176;-435.0
T(238)
0.160;-455.6
8(239)
0.194;-476.2
8J(23)
0.151;-435.0
(239T)
0.184;-435.0
99(23)
0.143;-320.6
(23)(9Q)
0.233;-258.8
(23TQ)
0.190;-373.1
T(23Q)
0.172;-373.1
Q(23J)
0.191;-352.5
(23)(JK)
0.230;-196.9
QK(23)
0.196;-311.2
23(35)
0.147;-526.9
33(28)
0.176;-465.0
233T
0.143;-558.8
23(3K)
0.144;-361.9
(24)(36)
0.188;-485.6
3(249)
0.174;-558.8
3J(24)
0.161;-517.5
(34)(25)
0.159;-506.2
27(34)
0.141;-600.0
2(34T)
0.156;-538.1
(34)(2K)
0.188;-341.2
34(26)
0.182;-620.6
34(28)
0.190;-579.4
34(2T)
0.154;-538.1
34(2Q)
0.188;-496.9
(25)(35)
0.151;-350.6
3(258)
0.155;-558.8
3T(25)
0.159;-517.5
(25)(3K)
0.181;-320.6
27(35)
0.135;-579.4
2(35T)
0.125;-517.5
(35)(2K)
0.199;-320.6
35(27)
0.152;-579.4
35(29)
0.128;-538.1
35(2J)
0.126;-496.9
35(2K)
0.181;-455.6
37(26)
0.157;-558.8
(26)(3T)
0.176;-361.9
3(26K)
0.184;-435.0
2(368)
0.119;-538.1
(36)(2J)
0.182;-341.2
2K(36)
0.158;-435.0
23(68)
0.169;-538.1
23(6T)
0.124;-496.9
23(6Q)
0.155;-455.6
3(278)
0.131;-517.5
3T(27)
0.137;-476.2
(27)(3K)
0.153;-279.4
29(37)
0.149;-496.9
2(37Q)
0.149;-435.0
23(78)
0.145;-517.5
23(7T)
0.184;-476.2
23(7Q)
0.152;-435.0
3(289)
0.147;-476.2
3J(28)
0.159;-435.0
(38)(29)
0.165;-341.2
2J(38)
0.151;-435.0
38(29)
0.174;-476.2
38(2J)
0.159;-435.0
38(2K)
0.156;-393.8
3T(29)
0.202;-435.0
(29)(3K)
0.164;-238.1
2J(39)
0.227;-414.4
39(2T)
0.148;-435.0
39(2Q)
0.150;-393.8
(2T)(3T)
0.168;-144.4
3(2TK)
0.183;-352.5
2(3TQ)
0.224;-373.1
23(TJ)
0.185;-393.8
23(TK)
0.190;-352.5
(2J)(3K)
0.192;-196.9
2K(3J)
0.156;-331.9
23(JK)
0.217;-331.9
(3Q)(2K)
0.187;-176.2
(2K)(3K)
0.197;-20.6
4(246)
0.164;-465.0
48(24)
0.189;-423.8
(24)(4J)
0.219;-226.9
5(245)
0.134;-465.0
9(245)
0.137;-517.5
K(245)
0.173;-435.0
5(248)
0.155;-538.1
5T(24)
0.130;-496.9
(24)(5K)
0.230;-300.0
9(246)
0.174;-496.9
K(246)
0.223;-414.4
6(249)
0.176;-496.9
6J(24)
0.170;-455.6
(2478)
0.137;-496.9
(247Q)
0.195;-414.4
7(249)
0.176;-476.2
7J(24)
0.202;-435.0
(2489)
0.175;-455.6
(248K)
0.162;-373.1
8T(24)
0.194;-435.0
(24)(8K)
0.185;-238.1
Q(249)
0.176;-373.1
(24)(9J)
0.198;-258.8
T(24T)
0.198;-258.8
T(24J)
0.223;-373.1
TK(24)
0.156;-331.9
(24)(JQ)
0.201;-196.9
QQ(24)
0.235;-176.2
24(45)
0.166;-485.6
44(28)
0.135;-423.8
244T
0.201;-517.5
24(4K)
0.157;-320.6
(25)(47)
0.207;-423.8
4(25T)
0.161;-496.9
4Q(25)
0.140;-455.6
(45)(27)
0.172;-423.8
29(45)
0.213;-517.5
2(45Q)
0.175;-455.6
24(56)
0.108;-579.4
24(58)
0.124;-538.1
24(5T)
0.164;-496.9
24(5Q)
0.198;-455.6
4(267)
0.148;-538.1
49(26)
0.169;-496.9
(26)(4Q)
0.147;-300.0
27(46)
0.152;-538.1
2(46T)
0.132;-476.2
(46)(2K)
0.182;-279.4
46(28)
0.152;-517.5
46(2T)
0.137;-476.2
46(2Q)
0.193;-435.0
(27)(47)
0.174;-247.5
4(27T)
0.150;-455.6
4Q(27)
0.155;-414.4
(47)(29)
0.209;-341.2
2J(47)
0.175;-435.0
47(28)
0.155;-496.9
47(2T)
0.143;-455.6
47(2Q)
0.179;-414.4
(28)(48)
0.214;-206.3
4(28J)
0.177;-414.4
4K(28)
0.181;-373.1
(48)(2J)
0.178;-279.4
2K(48)
0.206;-373.1
24(8T)
0.185;-435.0
24(8Q)
0.141;-393.8
4(29T)
0.189;-414.4
4Q(29)
0.186;-373.1
(49)(2J)
0.214;-258.8
2K(49)
0.163;-352.5
24(9J)
0.148;-393.8
24(9K)
0.181;-352.5
(2T)(4Q)
0.200;-217.5
2J(4T)
0.194;-373.1
4T(2J)
0.194;-373.1
4T(2K)
0.197;-331.9
4Q(2J)
0.169;-331.9
(4J)(2K)
0.232;-176.2
4J(2K)
0.184;-311.2
4K(2Q)
0.187;-290.6
24(QK)
0.155;-290.6
(25)(56)
0.192;-288.7
5(259)
0.217;-361.9
5J(25)
0.239;-320.6
(2567)
0.149;-517.5
(256J)
0.228;-435.0
(25)(67)
0.166;-382.5
6(25T)
0.162;-455.6
6Q(25)
0.171;-414.4
9(257)
0.168;-455.6
K(257)
0.197;-373.1
7(25T)
0.187;-435.0
7Q(25)
0.166;-393.8
T(258)
0.154;-414.4
8(259)
0.175;-435.0
8J(25)
0.186;-393.8
(259T)
0.127;-393.8
99(25)
0.192;-279.4
(25)(9Q)
0.176;-217.5
(25TQ)
0.176;-331.9
T(25Q)
0.193;-331.9
Q(25J)
0.181;-311.2
(25)(JK)
0.202;-155.6
QK(25)
0.211;-270.0
25(57)
0.159;-403.1
55(2T)
0.225;-341.2
255Q
0.131;-435.0
57(26)
0.146;-517.5
(26)(5T)
0.206;-320.6
5(26K)
0.198;-393.8
2(568)
0.167;-496.9
(56)(2J)
0.172;-300.0
2K(56)
0.179;-393.8
25(68)
0.171;-496.9
25(6T)
0.166;-455.6
25(6Q)
0.165;-414.4
5(278)
0.151;-476.2
5T(27)
0.141;-435.0
(27)(5K)
0.195;-238.1
29(57)
0.157;-455.6
2(57Q)
0.199;-393.8
25(78)
0.145;-476.2
25(7T)
0.196;-435.0
25(7Q)
0.193;-393.8
5(289)
0.194;-435.0
5J(28)
0.197;-393.8
(58)(29)
0.164;-300.0
2J(58)
0.163;-393.8
58(29)
0.170;-435.0
58(2J)
0.185;-393.8
58(2K)
0.164;-352.5
5T(29)
0.159;-393.8
(29)(5K)
0.189;-196.9
2J(59)
0.188;-373.1
59(2T)
0.182;-393.8
59(2Q)
0.177;-352.5
(2T)(5T)
0.278;-103.1
5(2TK)
0.218;-311.2
2(5TQ)
0.229;-331.9
25(TJ)
0.190;-352.5
25(TK)
0.161;-311.2
(2J)(5K)
0.249;-155.6
2K(5J)
0.206;-290.6
25(JK)
0.193;-290.6
(5Q)(2K)
0.269;-135.0
(2K)(5K)
0.260;20.6
6(268)
0.168;-341.2
6T(26)
0.156;-300.0
(26)(6K)
0.231;-103.1
T(267)
0.179;-414.4
7(268)
0.141;-455.6
7T(26)
0.178;-414.4
(26)(7K)
0.197;-217.5
J(268)
0.217;-373.1
89(26)
0.171;-414.4
(26)(8Q)
0.237;-217.5
(269J)
0.165;-352.5
(26)(9T)
0.178;-238.1
9(26K)
0.185;-311.2
(26TK)
0.187;-290.6
TQ(26)
0.143;-311.2
K(26J)
0.160;-270.0
Q(26Q)
0.262;-135.0
KK(26)
0.224;-93.7
66(29)
0.223;-320.6
266J
0.181;-414.4
67(27)
0.177;-341.2
(27)(6T)
0.177;-279.4
6(27K)
0.168;-352.5
2(679)
0.160;-435.0
(67)(2Q)
0.181;-238.1
27(68)
0.193;-455.6
27(6T)
0.203;-414.4
27(6Q)
0.237;-373.1
68(28)
0.155;-300.0
(28)(6J)
0.203;-238.1
28(68)
0.158;-300.0
2(68J)
0.228;-373.1
2688
0.192;-435.0
268T
0.133;-528.7
268Q
0.173;-487.5
(29)(6T)
0.220;-238.1
6(29K)
0.193;-311.2
2(69J)
0.212;-352.5
2699
0.169;-393.8
269J
0.169;-487.5
269K
0.199;-446.2
6Q(2T)
0.185;-311.2
(6T)(2Q)
0.177;-176.2
2T(6J)
0.176;-331.9
2T(6K)
0.187;-290.6
6(2JK)
0.154;-270.0
2(6JK)
0.211;-270.0
2J(6K)
0.198;-270.0
2Q(6Q)
0.219;-135.0
26QK
0.162;-384.4
78(27)
0.216;-300.0
(27)(7J)
0.184;-103.1
8(278)
0.182;-279.4
Q(278)
0.184;-331.9
(27)(8T)
0.176;-238.1
8(27K)
0.150;-311.2
(279Q)
0.170;-311.2
9(27J)
0.210;-331.9
9K(27)
0.180;-290.6
TT(27)
0.195;-196.9
(27)(TK)
0.242;-135.0
J(27Q)
0.227;-270.0
K(27Q)
0.230;-228.7
77(28)
0.198;-300.0
277T
0.179;-393.8
27(7K)
0.188;-196.9
(28)(7T)
0.225;-238.1
7(28K)
0.193;-311.2
2(78T)
0.191;-373.1
(78)(2K)
0.196;-176.2
78(2T)
0.177;-373.1
78(2Q)
0.196;-331.9
(29)(79)
0.261;-103.1
7(29Q)
0.173;-311.2
2(79T)
0.180;-352.5
(79)(2K)
0.207;-155.6
79(2J)
0.174;-331.9
79(2K)
0.170;-290.6
7J(2T)
0.203;-311.2
(7T)(2J)
0.195;-176.2
2K(7T)
0.223;-270.0
27(TQ)
0.150;-290.6
7(2JQ)
0.241;-270.0
2(7JQ)
0.187;-270.0
27(JQ)
0.214;-270.0
7(2QK)
0.204;-228.7
7Q(2K)
0.196;-228.7
88(28)
0.204;-123.7
(28)(8J)
0.195;-61.9
9(289)
0.194;-217.5
K(289)
0.207;-270.0
9(28Q)
0.176;-290.6
J(28T)
0.150;-290.6
TJ(28)
0.218;-290.6
(28JQ)
0.206;-249.4
J(28K)
0.235;-228.7
(28)(QK)
0.229;-73.1
88(2T)
0.169;-217.5
288Q
0.197;-311.2
8T(29)
0.168;-331.9
(29)(8K)
0.270;-135.0
2J(89)
0.204;-311.2
89(2T)
0.216;-331.9
89(2Q)
0.181;-290.6
(2T)(8T)
0.268;-41.3
8(2TK)
0.195;-249.4
2(8TQ)
0.216;-270.0
28(TJ)
0.173;-290.6
28(TK)
0.200;-249.4
(2J)(8K)
0.250;-93.8
2K(8J)
0.179;-228.7
28(JK)
0.198;-228.7
(8Q)(2K)
0.195;-73.1
(2K)(8K)
0.249;82.5
9(29J)
0.192;-155.6
9K(29)
0.191;-114.4
TT(29)
0.192;-155.6
(29)(TK)
0.230;-93.8
J(29Q)
0.252;-228.7
K(29Q)
0.277;-187.5
99(2T)
0.269;-176.2
299Q
0.182;-270.0
9J(2T)
0.183;-270.0
(9T)(2J)
0.203;-135.0
2K(9T)
0.223;-228.7
29(TQ)
0.146;-249.4
9(2JQ)
0.199;-228.7
2(9JQ)
0.200;-228.7
29(JQ)
0.200;-228.7
9(2QK)
0.163;-187.5
9Q(2K)
0.225;-187.5
TT(2T)
0.232;0.0
(2T)(TK)
0.245;61.9
J(2TQ)
0.219;-208.1
K(2TQ)
0.184;-166.9
TT(2J)
0.199;-114.4
2TTK
0.199;-208.1
TK(2J)
0.260;-187.5
2TJJ
0.209;-228.7
2TJK
0.218;-322.5
2(TQK)
0.217;-166.9
TK(2K)
0.196;-11.2
(2J)(JK)
0.258;103.1
QK(2J)
0.231;-146.2
2J(JK)
0.254;-31.9
(JQ)(2K)
0.221;-11.2
(2K)(JK)
0.245;144.4
K(2QK)
0.249;30.0
2K(QK)
0.268;30.0
3335
0.120;-506.2
3339
0.137;-423.8
333K
0.165;-341.2
36(34)
0.223;-465.0
(34)(39)
0.165;-268.1
3(34Q)
0.160;-341.2
33(45)
0.179;-485.6
34(38)
0.189;-423.8
334T
0.148;-517.5
33(4K)
0.146;-320.6
(35)(37)
0.182;-288.7
3(35T)
0.188;-361.9
3Q(35)
0.189;-320.6
35(37)
0.180;-423.8
3359
0.199;-517.5
33(5Q)
0.194;-320.6
(36)(37)
0.172;-268.1
3(36T)
0.167;-341.2
3Q(36)
0.164;-300.0
36(38)
0.189;-382.5
336T
0.142;-476.2
33(6K)
0.170;-279.4
(37)(39)
0.230;-206.3
3(37Q)
0.199;-279.4
33(78)
0.195;-361.9
37(3J)
0.168;-300.0
337K
0.157;-393.8
3T(38)
0.166;-300.0
(38)(3K)
0.187;-103.1
338T
0.176;-435.0
33(8K)
0.153;-238.1
(39)(3J)
0.197;-123.7
3399
0.213;-300.0
33(9Q)
0.222;-238.1
(3T)(3J)
0.269;-103.1
33TT
0.201;-258.8
33(TK)
0.185;-196.9
(3J)(3K)
0.201;-41.3
33JK
0.220;-311.2
33(QK)
0.189;-155.6
45(34)
0.193;-465.0
(34)(48)
0.205;-268.1
4(34J)
0.164;-341.2
4K(34)
0.205;-300.0
(3459)
0.157;-496.9
(345K)
0.174;-414.4
57(34)
0.195;-538.1
(34)(5T)
0.207;-341.2
5(34K)
0.185;-414.4
(3469)
0.186;-476.2
(346K)
0.209;-393.8
68(34)
0.123;-496.9
(34)(6J)
0.184;-300.0
7(347)
0.173;-361.9
J(347)
0.168;-414.4
78(34)
0.163;-476.2
(34)(7J)
0.185;-279.4
8(348)
0.174;-320.6
Q(348)
0.177;-373.1
(34)(8T)
0.183;-279.4
8(34K)
0.166;-352.5
(349Q)
0.148;-352.5
9(34J)
0.219;-373.1
9K(34)
0.189;-331.9
TT(34)
0.166;-238.1
(34)(TK)
0.258;-176.2
J(34Q)
0.189;-311.2
K(34Q)
0.192;-270.0
44(35)
0.198;-465.0
3447
0.165;-558.8
34(4T)
0.160;-361.9
44(3K)
0.174;-300.0
4(357)
0.162;-538.1
49(35)
0.139;-496.9
(35)(4Q)
0.214;-300.0
36(45)
0.134;-558.8
3(459)
0.134;-496.9
(45)(3Q)
0.226;-300.0
35(46)
0.182;-558.8
35(48)
0.135;-517.5
35(4T)
0.165;-476.2
35(4Q)
0.198;-435.0
46(36)
0.189;-403.1
(36)(49)
0.147;-341.2
4(36Q)
0.207;-414.4
3(467)
0.170;-517.5
(46)(3T)
0.165;-320.6
3Q(46)
0.155;-414.4
3467
0.139;-652.5
3469
0.117;-611.2
346J
0.148;-570.0
346K
0.162;-528.7
49(37)
0.179;-455.6
(37)(4Q)
0.224;-258.8
38(47)
0.153;-476.2
3(47J)
0.133;-414.4
3477
0.179;-496.9
3479
0.170;-590.6
347J
0.157;-549.4
347K
0.141;-508.1
4T(38)
0.195;-414.4
(38)(4K)
0.219;-217.5
3T(48)
0.202;-414.4
3(48K)
0.208;-352.5
38(4T)
0.196;-414.4
38(4Q)
0.174;-373.1
49(39)
0.235;-279.4
(39)(4Q)
0.221;-217.5
3T(49)
0.201;-393.8
3(49K)
0.204;-331.9
39(4J)
0.189;-373.1
39(4K)
0.158;-331.9
4(3TQ)
0.229;-331.9
3(4TJ)
0.170;-352.5
34TT
0.163;-373.1
34TQ
0.139;-466.9
(3J)(4Q)
0.212;-176.2
3Q(4J)
0.149;-311.2
34JQ
0.140;-446.2
(3Q)(4K)
0.189;-135.0
3Q(4K)
0.167;-270.0
5(356)
0.132;-403.1
58(35)
0.182;-361.9
(35)(5J)
0.174;-165.0
6(356)
0.184;-382.5
T(356)
0.189;-435.0
6(357)
0.169;-496.9
69(35)
0.145;-455.6
(35)(6Q)
0.203;-258.8
(3579)
0.188;-435.0
(357K)
0.171;-352.5
79(35)
0.171;-435.0
(35)(7Q)
0.219;-238.1
(358T)
0.149;-393.8
88(35)
0.222;-300.0
(35)(8J)
0.226;-238.1
9(359)
0.192;-258.8
K(359)
0.200;-311.2
9(35Q)
0.165;-331.9
J(35T)
0.174;-331.9
TJ(35)
0.229;-331.9
(35JQ)
0.201;-290.6
J(35K)
0.213;-270.0
(35)(QK)
0.229;-114.4
55(37)
0.230;-382.5
3559
0.181;-476.2
35(5Q)
0.178;-279.4
(36)(57)
0.192;-361.9
5(36T)
0.165;-435.0
5Q(36)
0.199;-393.8
(56)(38)
0.149;-341.2
3T(56)
0.163;-435.0
3(56K)
0.190;-373.1
36(58)
0.176;-476.2
36(5T)
0.183;-435.0
36(5Q)
0.189;-393.8
57(37)
0.174;-341.2
(37)(5T)
0.217;-279.4
5(37K)
0.191;-352.5
3(579)
0.172;-435.0
(57)(3Q)
0.170;-238.1
37(58)
0.140;-455.6
37(5T)
0.194;-414.4
37(5Q)
0.150;-373.1
58(38)
0.212;-300.0
(38)(5J)
0.187;-238.1
38(58)
0.189;-300.0
3(58J)
0.200;-373.1
3588
0.163;-435.0
358T
0.157;-528.7
358Q
0.176;-487.5
(39)(5T)
0.170;-238.1
5(39K)
0.173;-311.2
3(59J)
0.222;-352.5
3599
0.162;-393.8
359J
0.153;-487.5
359K
0.171;-446.2
5Q(3T)
0.193;-311.2
(5T)(3Q)
0.192;-176.2
3T(5J)
0.198;-331.9
3T(5K)
0.183;-290.6
5(3JK)
0.221;-270.0
3(5JK)
0.225;-270.0
3J(5K)
0.221;-270.0
3Q(5Q)
0.267;-135.0
35QK
0.204;-384.4
67(36)
0.177;-341.2
(36)(6T)
0.179;-144.4
6(36K)
0.241;-217.5
(367T)
0.176;-393.8
77(36)
0.176;-320.6
(36)(7T)
0.192;-258.8
7(36K)
0.187;-331.9
(368J)
0.211;-352.5
(36)(89)
0.188;-258.8
8(36Q)
0.193;-331.9
T(369)
0.215;-352.5
9(36T)
0.205;-352.5
9Q(36)
0.156;-311.2
Q(36T)
0.186;-290.6
(36)(TQ)
0.267;-155.6
(36JK)
0.220;-249.4
JK(36)
0.179;-249.4
K(36K)
0.206;-73.1
3668
0.210;-455.6
36(6J)
0.234;-258.8
(37)(67)
0.220;-185.6
6(37T)
0.177;-393.8
6Q(37)
0.224;-352.5
(67)(39)
0.151;-279.4
3J(67)
0.182;-373.1
67(38)
0.159;-435.0
67(3T)
0.159;-393.8
67(3Q)
0.163;-352.5
(38)(68)
0.239;-144.4
6(38J)
0.183;-352.5
6K(38)
0.198;-311.2
(68)(3J)
0.187;-217.5
3K(68)
0.199;-311.2
36(8T)
0.191;-373.1
36(8Q)
0.218;-331.9
6(39T)
0.163;-352.5
6Q(39)
0.204;-311.2
(69)(3J)
0.251;-196.9
3K(69)
0.169;-290.6
36(9J)
0.183;-331.9
36(9K)
0.194;-290.6
(3T)(6Q)
0.199;-155.6
3J(6T)
0.191;-311.2
6T(3J)
0.194;-311.2
6T(3K)
0.167;-270.0
6Q(3J)
0.161;-270.0
(6J)(3K)
0.223;-114.4
6J(3K)
0.192;-249.4
6K(3Q)
0.233;-228.7
36(QK)
0.205;-228.7
(37)(78)
0.228;-144.4
7(37J)
0.175;-217.5
7K(37)
0.195;-176.2
(378Q)
0.198;-311.2
8(37T)
0.200;-352.5
8Q(37)
0.178;-311.2
J(379)
0.157;-311.2
9T(37)
0.201;-331.9
(37)(9K)
0.216;-135.0
K(37T)
0.223;-249.4
T(37K)
0.219;-249.4
JJ(37)
0.217;-135.0
(37QK)
0.243;-208.1
3777
0.168;-300.0
37(7T)
0.210;-238.1
77(3K)
0.216;-176.2
7(38T)
0.194;-352.5
7Q(38)
0.214;-311.2
(78)(3T)
0.219;-217.5
3Q(78)
0.240;-311.2
3789
0.156;-508.1
378J
0.135;-466.9
378K
0.210;-425.6
7J(39)
0.203;-311.2
(79)(3T)
0.197;-196.9
3Q(79)
0.163;-290.6
379T
0.150;-466.9
379Q
0.153;-425.6
(3T)(7J)
0.178;-155.6
3T(7T)
0.272;-176.2
3(7TK)
0.225;-249.4
3T(7Q)
0.211;-270.0
7J(3J)
0.252;-135.0
(7J)(3Q)
0.260;-114.4
3J(7Q)
0.194;-249.4
7Q(3Q)
0.225;-93.7
37QQ
0.217;-228.7
37KK
0.184;-187.5
8(38J)
0.204;-176.2
8K(38)
0.196;-135.0
(389K)
0.165;-249.4
9J(38)
0.221;-290.6
(38TJ)
0.194;-270.0
(38)(TJ)
0.168;-135.0
J(38J)
0.248;-114.4
JQ(38)
0.218;-228.7
Q(38K)
0.176;-187.5
3889
0.143;-352.5
38(8Q)
0.257;-155.6
(39)(8T)
0.194;-176.2
8(39K)
0.210;-249.4
3(89J)
0.192;-290.6
3899
0.173;-331.9
389J
0.190;-425.6
389K
0.180;-384.4
8Q(3T)
0.159;-249.4
(8T)(3Q)
0.250;-114.4
3T(8J)
0.182;-270.0
3T(8K)
0.205;-228.7
8(3JK)
0.215;-208.1
3(8JK)
0.209;-208.1
3J(8K)
0.177;-208.1
3Q(8Q)
0.261;-73.1
38QK
0.175;-322.5
9T(39)
0.194;-155.6
(39)(9K)
0.235;41.3
K(39T)
0.235;-208.1
T(39K)
0.206;-208.1
JJ(39)
0.246;-93.7
(39QK)
0.260;-166.9
3999
0.215;-176.2
39(9Q)
0.291;-114.4
(3T)(9J)
0.193;-114.4
3T(9T)
0.196;-135.0
3(9TK)
0.246;-208.1
3T(9Q)
0.174;-228.7
9J(3J)
0.232;-93.7
(9J)(3Q)
0.217;-73.1
3J(9Q)
0.204;-208.1
9Q(3Q)
0.249;-52.5
39QQ
0.224;-187.5
39KK
0.226;-146.2
T(3TK)
0.222;-52.5
JJ(3T)
0.175;-73.1
(3TQK)
0.236;-146.2
3TTT
0.215;-114.4
3T(TK)
0.240;-52.5
(3J)(TK)
0.241;-31.9
3K(TJ)
0.224;-166.9
3T(JK)
0.243;-166.9
(TQ)(3K)
0.182;-11.2
(3K)(TK)
0.274;144.4
J(3JK)
0.269;-11.2
(3J)(QK)
0.279;9.4
JJ(3K)
0.232;-11.2
3Q(JQ)
0.234;-11.2
3JQK
0.225;-260.6
QK(3Q)
0.234;30.0
QK(3K)
0.224;50.6
44(46)
0.259;-288.7
44(4T)
0.207;-206.2
(45)(45)
0.267;-153.8
4(458)
0.148;-361.9
4T(45)
0.152;-320.6
(45)(4K)
0.207;-123.7
4457
0.181;-517.5
44(5T)
0.203;-320.6
45(4K)
0.194;-258.8
4(468)
0.160;-341.2
4T(46)
0.204;-300.0
(46)(4K)
0.201;-103.1
4468
0.160;-476.2
44(6J)
0.206;-279.4
(47)(47)
0.193;-71.2
4(47T)
0.195;-279.4
4Q(47)
0.219;-238.1
47(49)
0.196;-300.0
447J
0.142;-393.8
48(48)
0.232;-165.0
(48)(4J)
0.209;-103.1
4488
0.185;-300.0
44(8J)
0.205;-238.1
(49)(49)
0.240;11.2
4(49Q)
0.214;-196.9
44(9T)
0.165;-238.1
49(4K)
0.271;-176.2
4(4TQ)
0.209;-176.2
44(TJ)
0.212;-196.9
(4J)(4J)
0.219;93.8
44JJ
0.251;-176.2
4Q(4Q)
0.235;0.0
(4K)(4K)
0.244;176.2
(45)(57)
0.249;-226.9
5(45T)
0.231;-300.0
5Q(45)
0.190;-258.8
8(456)
0.193;-455.6
Q(456)
0.204;-373.1
(45)(68)
0.171;-320.6
6(45J)
0.229;-393.8
6K(45)
0.203;-352.5
(457J)
0.173;-373.1
(45)(78)
0.180;-300.0
7(45J)
0.142;-373.1
7K(45)
0.178;-331.9
(458Q)
0.143;-331.9
8(45T)
0.151;-373.1
8Q(45)
0.164;-331.9
J(459)
0.233;-331.9
9T(45)
0.167;-352.5
(45)(9K)
0.211;-155.6
K(45T)
0.202;-270.0
T(45K)
0.148;-270.0
JJ(45)
0.244;-155.6
(45QK)
0.179;-228.7
4555
0.179;-403.1
45(58)
0.240;-341.2
55(4J)
0.173;-279.4
455K
0.240;-373.1
58(46)
0.158;-455.6
(46)(5J)
0.224;-258.8
46(56)
0.208;-361.9
4(569)
0.200;-435.0
(56)(4Q)
0.190;-238.1
46(57)
0.131;-476.2
46(59)
0.178;-435.0
46(5J)
0.173;-393.8
46(5K)
0.212;-352.5
5(479)
0.164;-414.4
5J(47)
0.194;-373.1
(57)(48)
0.198;-300.0
4T(57)
0.186;-393.8
4(57K)
0.179;-331.9
47(59)
0.139;-414.4
47(5J)
0.166;-373.1
47(5K)
0.177;-331.9
5(48T)
0.176;-373.1
5Q(48)
0.200;-331.9
(58)(4T)
0.247;-238.1
4Q(58)
0.218;-331.9
4589
0.150;-528.7
458J
0.175;-487.5
458K
0.150;-446.2
5J(49)
0.219;-331.9
(59)(4T)
0.215;-217.5
4Q(59)
0.180;-311.2
459T
0.147;-487.5
459Q
0.179;-446.2
(4T)(5J)
0.175;-176.2
4T(5T)
0.210;-196.9
4(5TK)
0.242;-270.0
4T(5Q)
0.206;-290.6
5J(4J)
0.186;-155.6
(5J)(4Q)
0.207;-135.0
4J(5Q)
0.207;-270.0
5Q(4Q)
0.200;-114.4
45QQ
0.149;-249.4
45KK
0.214;-208.1
6(469)
0.196;-279.4
6J(46)
0.215;-238.1
(4678)
0.180;-414.4
(467Q)
0.196;-331.9
7(469)
0.184;-393.8
7J(46)
0.195;-352.5
(4689)
0.211;-373.1
(468K)
0.175;-290.6
8T(46)
0.171;-352.5
(46)(8K)
0.239;-155.6
Q(469)
0.178;-290.6
(46)(9J)
0.217;-176.2
T(46T)
0.226;-176.2
T(46J)
0.173;-290.6
TK(46)
0.192;-249.4
(46)(JQ)
0.169;-114.4
QQ(46)
0.250;-93.7
46(67)
0.202;-320.6
66(4T)
0.218;-258.8
466Q
0.169;-352.5
68(47)
0.191;-414.4
(47)(6J)
0.204;-217.5
47(67)
0.224;-300.0
4(67T)
0.160;-373.1
(67)(4K)
0.173;-176.2
67(49)
0.166;-393.8
67(4J)
0.223;-352.5
67(4K)
0.146;-311.2
69(48)
0.150;-373.1
(48)(6Q)
0.204;-176.2
49(68)
0.191;-373.1
4(68Q)
0.196;-311.2
46(89)
0.145;-373.1
46(8J)
0.166;-331.9
46(8K)
0.178;-290.6
(49)(6J)
0.234;-176.2
49(69)
0.248;-217.5
4(69Q)
0.196;-290.6
46(9T)
0.147;-331.9
46(9Q)
0.192;-290.6
6(4TJ)
0.192;-290.6
6K(4T)
0.238;-249.4
(6T)(4K)
0.217;-114.4
6T(4Q)
0.170;-270.0
(4J)(6J)
0.307;0.0
4J(6J)
0.201;-135.0
6J(4Q)
0.245;-249.4
(4Q)(6Q)
0.227;41.3
4K(6Q)
0.236;-208.1
4K(6K)
0.214;-52.5
79(47)
0.180;-238.1
(47)(7Q)
0.237;-41.3
(478T)
0.166;-331.9
88(47)
0.190;-238.1
(47)(8J)
0.238;-176.2
9(479)
0.261;-196.9
K(479)
0.214;-249.4
9(47Q)
0.248;-270.0
J(47T)
0.219;-270.0
TJ(47)
0.211;-270.0
(47JQ)
0.229;-228.7
J(47K)
0.161;-208.1
(47)(QK)
0.245;-52.5
77(49)
0.216;-238.1
477J
0.217;-331.9
78(48)
0.228;-238.1
(48)(7J)
0.166;-176.2
48(78)
0.224;-238.1
4(78J)
0.207;-311.2
4788
0.188;-373.1
478T
0.180;-466.9
478Q
0.170;-425.6
(49)(7T)
0.256;-176.2
7(49K)
0.223;-249.4
4(79J)
0.180;-290.6
4799
0.146;-331.9
479J
0.147;-425.6
479K
0.160;-384.4
7Q(4T)
0.180;-249.4
(7T)(4Q)
0.210;-114.4
4T(7J)
0.176;-270.0
4T(7K)
0.203;-228.7
7(4JK)
0.262;-208.1
4(7JK)
0.207;-208.1
4J(7K)
0.173;-208.1
4Q(7Q)
0.278;-73.1
47QK
0.158;-322.5
89(48)
0.169;-196.9
(48)(8Q)
0.237;0.0
(489J)
0.226;-270.0
(48)(9T)
0.227;-155.6
9(48K)
0.173;-228.7
(48TK)
0.208;-208.1
TQ(48)
0.256;-228.7
K(48J)
0.195;-187.5
Q(48Q)
0.260;-52.5
KK(48)
0.236;-11.2
88(4J)
0.223;-155.6
488K
0.190;-249.4
8J(49)
0.223;-270.0
(89)(4T)
0.197;-155.6
4Q(89)
0.192;-249.4
489T
0.200;-425.6
489Q
0.172;-384.4
(4T)(8J)
0.253;-114.4
4T(8T)
0.223;-135.0
4(8TK)
0.185;-208.1
4T(8Q)
0.192;-228.7
8J(4J)
0.256;-93.7
(8J)(4Q)
0.288;-73.1
4J(8Q)
0.189;-208.1
8Q(4Q)
0.205;-52.5
48QQ
0.253;-187.5
48KK
0.212;-146.2
9(49Q)
0.208;-93.7
J(49T)
0.198;-228.7
TJ(49)
0.212;-228.7
(49JQ)
0.222;-187.5
J(49K)
0.192;-166.9
(49)(QK)
0.243;-11.2
99(4J)
0.177;-114.4
499K
0.167;-208.1
9Q(4T)
0.220;-208.1
(9T)(4Q)
0.276;-73.1
4T(9J)
0.177;-228.7
4T(9K)
0.185;-187.5
9(4JK)
0.159;-166.9
4(9JK)
0.277;-166.9
4J(9K)
0.198;-166.9
4Q(9Q)
0.261;-31.9
49QK
0.175;-281.2
TJ(4T)
0.191;-73.1
(4TJQ)
0.191;-166.9
J(4TK)
0.220;-146.2
(4T)(QK)
0.236;9.4
TT(4Q)
0.189;-52.5
T(4JQ)
0.198;-166.9
4(TJQ)
0.229;-166.9
4T(JQ)
0.277;-166.9
T(4QK)
0.247;-125.6
TQ(4K)
0.215;-125.6
JJ(4J)
0.285;103.1
(4JQK)
0.186;-105.0
4JJJ
0.246;-31.9
JQ(4Q)
0.289;9.4
4JQQ
0.223;-125.6
4JKK
0.265;-84.4
QQ(4K)
0.255;50.6
4KKK
0.226;91.9
55(59)
0.225;-165.0
55(5K)
0.188;-82.5
(56)(58)
0.215;-165.0
5(56J)
0.184;-238.1
5K(56)
0.201;-196.9
56(59)
0.190;-279.4
556J
0.176;-373.1
57(57)
0.196;-165.0
(57)(5T)
0.237;-103.1
5(57K)
0.232;-176.2
55(79)
0.175;-258.8
57(5Q)
0.230;-196.9
5(589)
0.203;-238.1
5J(58)
0.203;-196.9
58(59)
0.230;-238.1
558J
0.179;-331.9
59(59)
0.252;-82.5
(59)(5Q)
0.228;-20.6
559T
0.213;-331.9
55(9K)
0.235;-135.0
(5T)(5Q)
0.186;0.0
55TJ
0.199;-290.6
5J(5J)
0.228;0.0
5J(5Q)
0.203;-114.4
5(5QK)
0.235;-73.1
5K(5K)
0.293;82.5
68(56)
0.241;-279.4
(56)(6J)
0.238;-82.5
7(567)
0.221;-279.4
J(567)
0.191;-331.9
78(56)
0.160;-393.8
(56)(7J)
0.164;-196.9
8(568)
0.221;-238.1
Q(568)
0.241;-290.6
(56)(8T)
0.206;-196.9
8(56K)
0.189;-270.0
(569Q)
0.193;-270.0
9(56J)
0.192;-290.6
9K(56)
0.227;-249.4
TT(56)
0.228;-155.6
(56)(TK)
0.263;-93.8
J(56Q)
0.216;-228.7
K(56Q)
0.210;-187.5
66(57)
0.171;-300.0
5669
0.158;-393.8
56(6Q)
0.209;-196.9
(57)(68)
0.199;-258.8
6(57J)
0.223;-331.9
6K(57)
0.192;-290.6
(67)(5T)
0.256;-217.5
5Q(67)
0.181;-311.2
5678
0.168;-528.7
567T
0.188;-487.5
567Q
0.178;-446.2
(58)(69)
0.183;-217.5
6(58Q)
0.220;-290.6
5(689)
0.197;-352.5
(68)(5Q)
0.190;-155.6
58(69)
0.183;-352.5
58(6J)
0.174;-311.2
58(6K)
0.200;-270.0
6(59J)
0.146;-290.6
6K(59)
0.172;-249.4
(69)(5Q)
0.233;-135.0
59(6T)
0.192;-311.2
59(6Q)
0.213;-270.0
6T(5T)
0.210;-155.6
(5T)(6K)
0.183;-93.8
5Q(6T)
0.199;-249.4
56TJ
0.209;-405.0
56TK
0.145;-363.7
6K(5J)
0.275;-208.1
56JJ
0.222;-249.4
56JK
0.181;-343.1
5(6QK)
0.233;-187.5
6K(5K)
0.298;-31.9
(57)(79)
0.207;-82.5
7(57Q)
0.203;-155.6
9(578)
0.201;-331.9
K(578)
0.174;-249.4
8(57J)
0.165;-290.6
8K(57)
0.233;-249.4
(579K)
0.204;-228.7
9J(57)
0.169;-270.0
(57TJ)
0.194;-249.4
(57)(TJ)
0.217;-114.4
J(57J)
0.226;-93.7
JQ(57)
0.221;-208.1
Q(57K)
0.196;-166.9
5778
0.181;-373.1
57(7J)
0.227;-176.2
(58)(78)
0.231;-82.5
7(58J)
0.228;-290.6
7K(58)
0.179;-249.4
(78)(5J)
0.221;-155.6
5K(78)
0.210;-249.4
57(8T)
0.158;-311.2
57(8Q)
0.194;-270.0
7(59T)
0.209;-290.6
7Q(59)
0.215;-249.4
(79)(5J)
0.189;-135.0
5K(79)
0.189;-228.7
57(9J)
0.168;-270.0
57(9K)
0.185;-228.7
(5T)(7Q)
0.244;-93.8
5J(7T)
0.229;-249.4
7T(5J)
0.242;-249.4
7T(5K)
0.190;-208.1
7Q(5J)
0.152;-208.1
(7J)(5K)
0.233;-52.5
7J(5K)
0.183;-187.5
7K(5Q)
0.205;-166.9
57(QK)
0.200;-166.9
(58)(89)
0.222;-41.3
8(58Q)
0.235;-114.4
T(589)
0.193;-270.0
9(58T)
0.194;-270.0
9Q(58)
0.246;-228.7
Q(58T)
0.177;-208.1
(58)(TQ)
0.216;-73.1
(58JK)
0.221;-166.9
JK(58)
0.281;-166.9
K(58K)
0.206;9.4
588T
0.204;-290.6
58(8K)
0.211;-93.7
(59)(8J)
0.234;-114.4
59(89)
0.274;-155.6
5(89Q)
0.196;-228.7
58(9T)
0.213;-270.0
58(9Q)
0.178;-228.7
8(5TJ)
0.167;-228.7
8K(5T)
0.224;-187.5
(8T)(5K)
0.230;-52.5
8T(5Q)
0.220;-208.1
(5J)(8J)
0.236;61.9
5J(8J)
0.235;-73.1
8J(5Q)
0.236;-187.5
(5Q)(8Q)
0.264;103.1
5K(8Q)
0.183;-146.2
5K(8K)
0.289;9.4
9J(59)
0.243;-93.7
(59TJ)
0.215;-208.1
(59)(TJ)
0.275;-73.1
J(59J)
0.255;-52.5
JQ(59)
0.210;-166.9
Q(59K)
0.211;-125.6
599T
0.191;-249.4
59(9K)
0.253;-52.5
(5T)(9Q)
0.212;-52.5
5J(9T)
0.214;-208.1
9T(5J)
0.211;-208.1
9T(5K)
0.226;-166.9
9Q(5J)
0.208;-166.9
(9J)(5K)
0.211;-11.2
9J(5K)
0.263;-146.2
9K(5Q)
0.181;-125.6
59(QK)
0.187;-125.6
(5T)(TJ)
0.242;82.5
J(5TJ)
0.188;-31.9
JQ(5T)
0.202;-146.2
Q(5TK)
0.223;-105.0
5TTJ
0.201;-187.5
TJ(5J)
0.242;-31.9
(TJ)(5Q)
0.286;-11.2
5J(TQ)
0.216;-146.2
TQ(5Q)
0.304;9.4
5TQQ
0.227;-125.6
5TKK
0.237;-84.4
Q(5JQ)
0.304;30.0
KK(5J)
0.250;71.3
(5Q)(JQ)
0.304;165.0
5K(JQ)
0.217;-84.4
5K(JK)
0.315;71.3
5QQQ
0.196;50.6
KK(5K)
0.304;247.5
6669
0.224;-238.1
666K
0.252;-155.6
69(67)
0.206;-217.5
(67)(6Q)
0.296;-20.6
6678
0.161;-373.1
66(7J)
0.263;-176.2
(68)(68)
0.244;52.5
6(68J)
0.216;-155.6
6K(68)
0.218;-114.4
68(6J)
0.156;-155.6
668K
0.157;-249.4
6J(69)
0.221;-135.0
69(6T)
0.178;-155.6
669Q
0.189;-249.4
6J(6T)
0.220;-114.4
6T(6J)
0.236;-114.4
66TK
0.264;-208.1
6K(6J)
0.193;-52.5
(6Q)(6Q)
0.244;217.5
66QK
0.211;-166.9
7(679)
0.188;-196.9
7J(67)
0.176;-155.6
(6789)
0.184;-311.2
(678K)
0.161;-228.7
8T(67)
0.197;-290.6
(67)(8K)
0.242;-93.8
Q(679)
0.216;-228.7
(67)(9J)
0.241;-114.4
T(67T)
0.231;-114.4
T(67J)
0.172;-228.7
TK(67)
0.225;-187.5
(67)(JQ)
0.184;-52.5
QQ(67)
0.266;-31.9
67(78)
0.229;-217.5
77(6J)
0.212;-155.6
677K
0.249;-249.4
7T(68)
0.208;-290.6
(68)(7K)
0.201;-93.8
6T(78)
0.195;-290.6
6(78K)
0.238;-228.7
68(7T)
0.209;-290.6
68(7Q)
0.240;-249.4
79(69)
0.265;-155.6
(69)(7Q)
0.220;-93.8
6T(79)
0.158;-270.0
6(79K)
0.200;-208.1
69(7J)
0.163;-249.4
69(7K)
0.220;-208.1
7(6TQ)
0.192;-208.1
6(7TJ)
0.185;-228.7
67TT
0.196;-249.4
67TQ
0.185;-343.1
(6J)(7Q)
0.214;-52.5
6Q(7J)
0.198;-187.5
67JQ
0.169;-322.5
(6Q)(7K)
0.281;-11.2
6Q(7K)
0.263;-146.2
8(689)
0.215;-155.6
8J(68)
0.225;-114.4
(689T)
0.193;-249.4
99(68)
0.256;-135.0
(68)(9Q)
0.226;-73.1
(68TQ)
0.167;-187.5
T(68Q)
0.215;-187.5
Q(68J)
0.212;-166.9
(68)(JK)
0.285;-11.2
QK(68)
0.168;-125.6
68(8T)
0.200;-135.0
88(6K)
0.229;-73.1
8(69J)
0.204;-228.7
8K(69)
0.217;-187.5
(89)(6Q)
0.217;-73.1
69(8T)
0.230;-249.4
69(8Q)
0.161;-208.1
8T(6T)
0.260;-93.7
(6T)(8K)
0.241;-31.9
6Q(8T)
0.240;-187.5
68TJ
0.175;-343.1
68TK
0.155;-301.9
8K(6J)
0.220;-146.2
68JJ
0.225;-187.5
68JK
0.189;-281.2
6(8QK)
0.290;-125.6
8K(6K)
0.285;30.0
(69)(9J)
0.252;61.9
T(69T)
0.199;-73.1
T(69J)
0.189;-187.5
TK(69)
0.221;-146.2
(69)(JQ)
0.250;-11.2
QQ(69)
0.287;9.4
69(9T)
0.240;-93.7
99(6K)
0.226;-31.9
9(6TQ)
0.213;-166.9
6(9TJ)
0.201;-187.5
69TT
0.264;-208.1
69TQ
0.153;-301.9
(6J)(9Q)
0.232;-11.2
6Q(9J)
0.222;-146.2
69JQ
0.199;-281.2
(6Q)(9K)
0.305;30.0
6Q(9K)
0.250;-105.0
T(6TJ)
0.252;-31.9
TK(6T)
0.297;9.4
(6T)(JQ)
0.238;9.4
QQ(6T)
0.281;30.0
6T(TJ)
0.244;-31.9
(6J)(TJ)
0.251;123.7
6J(TJ)
0.284;-11.2
TJ(6Q)
0.206;-125.6
(6Q)(TQ)
0.262;165.0
6K(TQ)
0.192;-84.4
6K(TK)
0.255;71.3
JK(6J)
0.303;50.6
K(6JK)
0.213;91.9
6JJK
0.220;-84.4
6(JQK)
0.254;-63.7
JK(6K)
0.295;91.9
KK(6Q)
0.254;112.5
6QKK
0.222;-22.5
77(7T)
0.237;-20.6
(78)(78)
0.222;93.8
7(78J)
0.200;-114.4
7K(78)
0.242;-73.1
78(7J)
0.289;-114.4
778K
0.237;-208.1
7J(79)
0.203;-93.7
79(7T)
0.196;-114.4
779Q
0.231;-208.1
7J(7T)
0.244;-73.1
7T(7J)
0.260;-73.1
77TK
0.194;-166.9
7K(7J)
0.207;-11.2
(7Q)(7Q)
0.257;258.8
77QK
0.234;-125.6
8(78T)
0.260;-114.4
8Q(78)
0.219;-73.1
J(789)
0.204;-208.1
9T(78)
0.185;-228.7
(78)(9K)
0.222;-31.9
K(78T)
0.190;-146.2
T(78K)
0.212;-146.2
JJ(78)
0.254;-31.9
(78QK)
0.232;-105.0
7888
0.187;-155.6
78(8J)
0.252;-93.7
(79)(89)
0.292;20.6
8(79Q)
0.243;-187.5
7(89T)
0.221;-228.7
(89)(7K)
0.227;-31.9
89(7J)
0.194;-208.1
89(7K)
0.178;-166.9
8J(7T)
0.195;-187.5
(8T)(7J)
0.232;-52.5
7K(8T)
0.216;-146.2
78(TQ)
0.225;-166.9
8(7JQ)
0.245;-146.2
7(8JQ)
0.221;-146.2
78(JQ)
0.205;-146.2
8(7QK)
0.197;-105.0
8Q(7K)
0.195;-105.0
99(79)
0.277;41.2
(79)(9Q)
0.316;103.1
(79TQ)
0.240;-146.2
T(79Q)
0.231;-146.2
Q(79J)
0.218;-125.6
(79)(JK)
0.217;30.0
QK(79)
0.227;-84.4
79(9J)
0.213;-52.5
(7T)(9T)
0.276;82.5
9(7TK)
0.232;-125.6
7(9TQ)
0.214;-146.2
79(TJ)
0.201;-166.9
79(TK)
0.239;-125.6
(7J)(9K)
0.248;30.0
7K(9J)
0.232;-105.0
79(JK)
0.229;-105.0
(9Q)(7K)
0.219;50.6
(7K)(9K)
0.309;206.3
T(7TQ)
0.273;9.4
Q(7TJ)
0.245;-105.0
(7T)(JK)
0.275;50.6
QK(7T)
0.257;-63.7
7T(TQ)
0.271;9.4
(7J)(TQ)
0.259;30.0
7Q(TJ)
0.198;-105.0
7TJQ
0.210;-240.0
(7Q)(TK)
0.298;71.3
7Q(TK)
0.176;-63.7
J(7JQ)
0.243;50.6
K(7JQ)
0.256;-43.1
JJ(7Q)
0.243;50.6
J(7QK)
0.258;-43.1
JQ(7K)
0.215;-43.1
QQ(7Q)
0.254;226.9
7Q(QK)
0.248;112.5
8888
0.274;0.0
888Q
0.218;-52.5
8(89J)
0.252;-52.5
8K(89)
0.268;-11.2
89(8Q)
0.201;-31.9
8(8TJ)
0.234;-31.9
8K(8T)
0.240;9.4
8T(8K)
0.269;9.4
8(8JK)
0.253;30.0
88(JK)
0.237;30.0
8Q(8K)
0.219;50.6
(89)(9T)
0.260;82.5
9(89K)
0.214;9.4
(89TK)
0.272;-105.0
TQ(89)
0.205;-125.6
K(89J)
0.199;-84.4
Q(89Q)
0.228;50.6
KK(89)
0.270;91.9
99(8Q)
0.208;-11.2
9(8TJ)
0.233;-146.2
9K(8T)
0.255;-105.0
(9T)(8K)
0.237;30.0
9T(8Q)
0.218;-125.6
(8J)(9J)
0.333;144.4
8J(9J)
0.309;9.4
9J(8Q)
0.225;-105.0
(8Q)(9Q)
0.291;185.6
8K(9Q)
0.206;-63.7
8K(9K)
0.267;91.9
TQ(8T)
0.230;30.0
K(8TJ)
0.274;-63.7
Q(8TQ)
0.222;71.3
KK(8T)
0.341;112.5
