AAAA
0.279;-7160.0
5AAA
0.253;-17420.0
9AAA
0.200;-14780.0
KAAA
0.274;-12140.0
4A(2A)
0.171;-26000.0
(2A)(7A)
0.179;-19700.0
A(2TA)
0.160;-22040.0
QA(2A)
0.244;-20720.0
2A(4A)
0.194;-26000.0
26AA
0.150;-29000.0
AA(29)
0.175;-22700.0
2A(QA)
0.190;-20720.0
A(34A)
0.142;-25340.0
6A(3A)
0.187;-24020.0
(3A)(9A)
0.206;-17720.0
A(3QA)
0.217;-20060.0
AA(34)
0.181;-25340.0
3A(7A)
0.192;-23360.0
39AA
0.216;-26360.0
AA(3Q)
0.253;-20060.0
(4A)(5A)
0.169;-19700.0
A(48A)
0.191;-22040.0
TA(4A)
0.229;-20720.0
(4A)(KA)
0.235;-14420.0
46AA
0.224;-27680.0
AA(49)
0.205;-21380.0
4A(QA)
0.195;-19400.0
A(56A)
0.155;-22700.0
8A(5A)
0.199;-21380.0
(5A)(JA)
0.208;-15080.0
55AA
0.147;-23360.0
AA(58)
0.215;-21380.0
5A(JA)
0.221;-19400.0
5KAA
0.168;-22400.0
8A(6A)
0.210;-20720.0
(6A)(JA)
0.211;-14420.0
66AA
0.145;-22040.0
AA(69)
0.167;-20060.0
6A(QA)
0.222;-18080.0
A(78A)
0.224;-20060.0
TA(7A)
0.183;-18740.0
(7A)(KA)
0.220;-12440.0
79AA
0.235;-23720.0
AA(7Q)
0.262;-17420.0
(8A)(9A)
0.245;-14420.0
A(8QA)
0.223;-16760.0
AA(89)
0.212;-18740.0
8A(QA)
0.237;-16760.0
A(9TA)
0.186;-17420.0
QA(9A)
0.272;-16100.0
9A(JA)
0.279;-16760.0
9KAA
0.202;-19760.0
QA(TA)
0.185;-15440.0
TA(QA)
0.252;-15440.0
A(JQA)
0.299;-14780.0
AA(JQ)
0.264;-14780.0
(QA)(KA)
0.251;-9140.0
KKAA
0.321;-12800.0
2(25A)
0.146;-33260.0
27(2A)
0.164;-31940.0
(2T)(2A)
0.152;-25640.0
2(2KA)
0.149;-27980.0
(236A)
0.129;-36260.0
(23TA)
0.142;-33620.0
33(2A)
0.140;-33920.0
(36)(2A)
0.169;-31940.0
3(29A)
0.102;-34280.0
3J(2A)
0.167;-32960.0
(245A)
0.172;-36260.0
(249A)
0.121;-33620.0
(24KA)
0.112;-30980.0
46(2A)
0.114;-35600.0
(49)(2A)
0.149;-29300.0
4(2QA)
0.125;-31640.0
6(25A)
0.118;-34940.0
T(25A)
0.152;-32300.0
5(26A)
0.164;-34940.0
58(2A)
0.108;-33620.0
(5J)(2A)
0.167;-27320.0
6(26A)
0.153;-29960.0
T(26A)
0.184;-31640.0
6(27A)
0.135;-33620.0
69(2A)
0.136;-32300.0
(6Q)(2A)
0.140;-26000.0
(279A)
0.174;-31640.0
(27KA)
0.145;-29000.0
79(2A)
0.158;-31640.0
(7Q)(2A)
0.212;-25340.0
(28TA)
0.154;-30320.0
88(2A)
0.165;-27320.0
(8J)(2A)
0.177;-25340.0
9(29A)
0.149;-26000.0
K(29A)
0.160;-27680.0
9(2QA)
0.169;-28340.0
J(2TA)
0.163;-28340.0
TJ(2A)
0.172;-28340.0
(2JQA)
0.171;-27020.0
J(2KA)
0.177;-26360.0
(QK)(2A)
0.193;-21380.0
22(4A)
0.163;-33920.0
226A
0.136;-36920.0
2A(29)
0.139;-30620.0
22(QA)
0.148;-28640.0
2(34A)
0.130;-37580.0
26(3A)
0.129;-36260.0
(29)(3A)
0.159;-29960.0
2(3QA)
0.142;-32300.0
A(234)
0.112;-37580.0
(23)(7A)
0.194;-31280.0
9A(23)
0.152;-34280.0
A(23Q)
0.156;-32300.0
2A(34)
0.123;-37580.0
2A(36)
0.126;-36260.0
2A(38)
0.125;-34940.0
2A(3T)
0.160;-33620.0
2A(3Q)
0.108;-32300.0
2(45A)
0.144;-36260.0
27(4A)
0.105;-34940.0
(2T)(4A)
0.175;-28640.0
2(4KA)
0.146;-30980.0
A(246)
0.130;-35600.0
(24)(9A)
0.143;-29300.0
JA(24)
0.149;-32300.0
24(5A)
0.136;-36260.0
24(7A)
0.144;-34940.0
24(9A)
0.150;-33620.0
24(JA)
0.145;-32300.0
24(KA)
0.160;-30980.0
26(5A)
0.144;-34940.0
(29)(5A)
0.138;-28640.0
2(5QA)
0.134;-30980.0
A(256)
0.132;-34940.0
(25)(9A)
0.163;-28640.0
JA(25)
0.148;-31640.0
25(6A)
0.103;-34940.0
25(8A)
0.172;-33620.0
25(TA)
0.148;-32300.0
25(QA)
0.150;-30980.0
(26)(6A)
0.180;-25640.0
2(69A)
0.108;-32300.0
2J(6A)
0.141;-30980.0
(26)(7A)
0.150;-29300.0
9A(26)
0.133;-32300.0
A(26Q)
0.163;-30320.0
2A(67)
0.168;-33620.0
2A(69)
0.153;-32300.0
2A(6J)
0.180;-30980.0
2A(6K)
0.182;-29660.0
(29)(7A)
0.154;-27320.0
2(7QA)
0.141;-29660.0
A(278)
0.182;-32300.0
(27)(JA)
0.181;-26000.0
KA(27)
0.128;-29000.0
2A(79)
0.142;-31640.0
2A(7J)
0.155;-30320.0
2A(7K)
0.138;-29000.0
(2T)(8A)
0.135;-26000.0
2(8KA)
0.190;-28340.0
A(28T)
0.137;-30320.0
(28)(KA)
0.158;-24020.0
28(TA)
0.148;-30320.0
28(QA)
0.145;-29000.0
(29)(9A)
0.158;-21680.0
2(9QA)
0.146;-28340.0
A(29T)
0.172;-29660.0
(29)(KA)
0.199;-23360.0
29(JA)
0.120;-29000.0
29(KA)
0.178;-27680.0
2J(TA)
0.168;-28340.0
(2T)(JA)
0.220;-24020.0
KA(2T)
0.151;-27020.0
2A(TQ)
0.185;-27680.0
2(JQA)
0.180;-27020.0
A(2JQ)
0.165;-27020.0
2A(JQ)
0.138;-27020.0
2(QKA)
0.157;-25700.0
2Q(KA)
0.175;-25700.0
33(3A)
0.175;-28940.0
(36)(3A)
0.155;-26960.0
3(39A)
0.173;-29300.0
3J(3A)
0.163;-27980.0
(345A)
0.137;-35600.0
(349A)
0.157;-32960.0
(34KA)
0.189;-30320.0
46(3A)
0.109;-34940.0
(49)(3A)
0.159;-28640.0
4(3QA)
0.131;-30980.0
6(35A)
0.178;-34280.0
T(35A)
0.141;-31640.0
5(36A)
0.127;-34280.0
58(3A)
0.109;-32960.0
(5J)(3A)
0.199;-26660.0
6(36A)
0.126;-29300.0
T(36A)
0.157;-30980.0
6(37A)
0.141;-32960.0
69(3A)
0.126;-31640.0
(6Q)(3A)
0.161;-25340.0
(379A)
0.182;-30980.0
(37KA)
0.138;-28340.0
79(3A)
0.143;-30980.0
(7Q)(3A)
0.208;-24680.0
(38TA)
0.138;-29660.0
88(3A)
0.178;-26660.0
(8J)(3A)
0.151;-24680.0
9(39A)
0.207;-25340.0
K(39A)
0.178;-27020.0
9(3QA)
0.154;-27680.0
J(3TA)
0.155;-27680.0
TJ(3A)
0.175;-27680.0
(3JQA)
0.164;-26360.0
J(3KA)
0.154;-25700.0
(QK)(3A)
0.233;-20720.0
33(5A)
0.118;-31940.0
337A
0.107;-34940.0
3A(3T)
0.161;-28640.0
33(KA)
0.156;-26660.0
3(46A)
0.164;-34940.0
38(4A)
0.130;-33620.0
(3J)(4A)
0.180;-27320.0
4A(34)
0.146;-31940.0
A(347)
0.126;-34280.0
(34)(TA)
0.175;-27980.0
QA(34)
0.175;-30980.0
345A
0.134;-39920.0
347A
0.104;-38600.0
349A
0.129;-37280.0
34JA
0.099;-35960.0
34KA
0.133;-34640.0
37(5A)
0.130;-33620.0
(3T)(5A)
0.161;-27320.0
3(5KA)
0.128;-29660.0
A(357)
0.110;-33620.0
(35)(TA)
0.149;-27320.0
QA(35)
0.160;-30320.0
356A
0.108;-38600.0
358A
0.126;-37280.0
35TA
0.143;-35960.0
35QA
0.150;-34640.0
(37)(6A)
0.128;-28640.0
3(6TA)
0.162;-30980.0
3Q(6A)
0.155;-29660.0
(36)(8A)
0.146;-27980.0
TA(36)
0.165;-30980.0
A(36K)
0.169;-29000.0
6A(38)
0.119;-32300.0
6A(3T)
0.156;-30980.0
6A(3Q)
0.173;-29660.0
37(7A)
0.154;-27980.0
(3T)(7A)
0.165;-26000.0
3(7KA)
0.136;-28340.0
A(379)
0.162;-30980.0
(37)(QA)
0.179;-24680.0
7A(38)
0.155;-31640.0
7A(3T)
0.135;-30320.0
7A(3Q)
0.168;-29000.0
38(8A)
0.170;-26660.0
(3J)(8A)
0.197;-24680.0
8A(38)
0.178;-26660.0
A(38J)
0.176;-29000.0
388A
0.187;-30980.0
38TA
0.142;-33980.0
38QA
0.125;-32660.0
(3T)(9A)
0.152;-24680.0
3(9KA)
0.149;-27020.0
A(39J)
0.162;-28340.0
399A
0.148;-29660.0
39JA
0.182;-32660.0
39KA
0.135;-31340.0
3Q(TA)
0.187;-27020.0
(3T)(QA)
0.226;-22700.0
TA(3J)
0.124;-27680.0
TA(3K)
0.145;-26360.0
3(JKA)
0.205;-25700.0
A(3JK)
0.179;-25700.0
JA(3K)
0.174;-25700.0
QA(3Q)
0.213;-21380.0
3QKA
0.209;-29360.0
45(4A)
0.180;-30620.0
(48)(4A)
0.179;-24320.0
4(4JA)
0.178;-26660.0
4K(4A)
0.202;-25340.0
(459A)
0.135;-31640.0
(45KA)
0.144;-29000.0
57(4A)
0.176;-32960.0
(5T)(4A)
0.132;-26660.0
5(4KA)
0.145;-29000.0
(469A)
0.133;-30980.0
(46KA)
0.131;-28340.0
68(4A)
0.128;-31640.0
(6J)(4A)
0.179;-25340.0
7(47A)
0.150;-27320.0
J(47A)
0.170;-29000.0
78(4A)
0.123;-30980.0
(7J)(4A)
0.187;-24680.0
8(48A)
0.195;-26000.0
Q(48A)
0.196;-27680.0
(8T)(4A)
0.157;-24680.0
8(4KA)
0.159;-27020.0
(49QA)
0.149;-27020.0
9(4JA)
0.192;-27680.0
9K(4A)
0.167;-26360.0
TT(4A)
0.177;-23360.0
(TK)(4A)
0.178;-21380.0
J(4QA)
0.150;-25700.0
K(4QA)
0.202;-24380.0
44(5A)
0.131;-30620.0
447A
0.131;-33620.0
4A(4T)
0.157;-27320.0
44(KA)
0.198;-25340.0
4(57A)
0.124;-32960.0
49(5A)
0.133;-31640.0
(4Q)(5A)
0.146;-25340.0
6A(45)
0.126;-33620.0
A(459)
0.153;-31640.0
(45)(QA)
0.196;-25340.0
5A(46)
0.112;-33620.0
5A(48)
0.151;-32300.0
5A(4T)
0.163;-30980.0
5A(4Q)
0.155;-29660.0
46(6A)
0.141;-28640.0
(49)(6A)
0.219;-26660.0
4(6QA)
0.208;-29000.0
A(467)
0.154;-32300.0
(46)(TA)
0.170;-26000.0
QA(46)
0.178;-29000.0
467A
0.136;-36620.0
469A
0.134;-35300.0
46JA
0.149;-33980.0
46KA
0.106;-32660.0
49(7A)
0.143;-30320.0
(4Q)(7A)
0.202;-24020.0
8A(47)
0.152;-30980.0
A(47J)
0.149;-29000.0
477A
0.133;-31640.0
479A
0.135;-34640.0
47JA
0.163;-33320.0
47KA
0.134;-32000.0
4T(8A)
0.152;-29000.0
(4K)(8A)
0.209;-22700.0
TA(48)
0.149;-29000.0
A(48K)
0.142;-27020.0
8A(4T)
0.149;-29000.0
8A(4Q)
0.161;-27680.0
49(9A)
0.200;-24680.0
(4Q)(9A)
0.187;-22700.0
TA(49)
0.173;-28340.0
A(49K)
0.132;-26360.0
9A(4J)
0.157;-27680.0
9A(4K)
0.129;-26360.0
4(TQA)
0.166;-26360.0
A(4TJ)
0.162;-27020.0
4TTA
0.147;-27680.0
4TQA
0.172;-30680.0
(4Q)(JA)
0.234;-21380.0
QA(4J)
0.192;-25700.0
4JQA
0.194;-30020.0
(4K)(QA)
0.250;-20060.0
QA(4K)
0.191;-24380.0
5(56A)
0.146;-28640.0
58(5A)
0.146;-27320.0
(5J)(5A)
0.202;-21020.0
6(56A)
0.175;-27980.0
T(56A)
0.160;-29660.0
6(57A)
0.136;-31640.0
69(5A)
0.194;-30320.0
(6Q)(5A)
0.194;-24020.0
(579A)
0.155;-29660.0
(57KA)
0.187;-27020.0
79(5A)
0.162;-29660.0
(7Q)(5A)
0.149;-23360.0
(58TA)
0.206;-28340.0
88(5A)
0.213;-25340.0
(8J)(5A)
0.197;-23360.0
9(59A)
0.168;-24020.0
K(59A)
0.144;-25700.0
9(5QA)
0.182;-26360.0
J(5TA)
0.166;-26360.0
TJ(5A)
0.190;-26360.0
(5JQA)
0.231;-25040.0
J(5KA)
0.202;-24380.0
(QK)(5A)
0.246;-19400.0
55(7A)
0.140;-27980.0
559A
0.130;-30980.0
5A(5Q)
0.164;-24680.0
(57)(6A)
0.152;-27320.0
5(6TA)
0.136;-29660.0
5Q(6A)
0.171;-28340.0
(56)(8A)
0.177;-26660.0
TA(56)
0.153;-29660.0
A(56K)
0.202;-27680.0
6A(58)
0.178;-30980.0
6A(5T)
0.177;-29660.0
6A(5Q)
0.197;-28340.0
57(7A)
0.182;-26660.0
(5T)(7A)
0.191;-24680.0
5(7KA)
0.145;-27020.0
A(579)
0.186;-29660.0
(57)(QA)
0.202;-23360.0
7A(58)
0.125;-30320.0
7A(5T)
0.125;-29000.0
7A(5Q)
0.190;-27680.0
58(8A)
0.195;-25340.0
(5J)(8A)
0.191;-23360.0
8A(58)
0.188;-25340.0
A(58J)
0.177;-27680.0
588A
0.168;-29660.0
58TA
0.132;-32660.0
58QA
0.147;-31340.0
(5T)(9A)
0.192;-23360.0
5(9KA)
0.228;-25700.0
A(59J)
0.125;-27020.0
599A
0.206;-28340.0
59JA
0.162;-31340.0
59KA
0.111;-30020.0
5Q(TA)
0.172;-25700.0
(5T)(QA)
0.208;-21380.0
TA(5J)
0.156;-26360.0
TA(5K)
0.190;-25040.0
5(JKA)
0.146;-24380.0
A(5JK)
0.147;-24380.0
JA(5K)
0.197;-24380.0
QA(5Q)
0.210;-20060.0
5QKA
0.163;-28040.0
67(6A)
0.182;-26660.0
(6T)(6A)
0.181;-20360.0
6(6KA)
0.206;-22700.0
(67TA)
0.136;-28340.0
77(6A)
0.153;-26000.0
(7T)(6A)
0.162;-24020.0
7(6KA)
0.170;-26360.0
(68JA)
0.141;-27020.0
(89)(6A)
0.181;-24020.0
8(6QA)
0.214;-26360.0
T(69A)
0.200;-27020.0
9(6TA)
0.165;-27020.0
9Q(6A)
0.130;-25700.0
Q(6TA)
0.200;-25040.0
(TQ)(6A)
0.198;-20720.0
(6JKA)
0.179;-23720.0
JK(6A)
0.157;-23720.0
K(6KA)
0.179;-18080.0
668A
0.157;-30320.0
6A(6J)
0.245;-24020.0
(67)(7A)
0.189;-21680.0
6(7TA)
0.197;-28340.0
6Q(7A)
0.185;-27020.0
(67)(9A)
0.173;-24680.0
JA(67)
0.136;-27680.0
67(8A)
0.133;-29660.0
67(TA)
0.129;-28340.0
67(QA)
0.205;-27020.0
(68)(8A)
0.174;-20360.0
6(8JA)
0.203;-27020.0
6K(8A)
0.166;-25700.0
(68)(JA)
0.192;-22700.0
KA(68)
0.143;-25700.0
6A(8T)
0.147;-27680.0
6A(8Q)
0.145;-26360.0
6(9TA)
0.196;-27020.0
6Q(9A)
0.131;-25700.0
(69)(JA)
0.219;-22040.0
KA(69)
0.176;-25040.0
6A(9J)
0.168;-26360.0
6A(9K)
0.175;-25040.0
(6Q)(TA)
0.219;-20720.0
JA(6T)
0.190;-25700.0
6T(JA)
0.169;-25700.0
6T(KA)
0.155;-24380.0
6Q(JA)
0.154;-24380.0
(6J)(KA)
0.249;-19400.0
6J(KA)
0.175;-23720.0
6K(QA)
0.181;-23060.0
6A(QK)
0.196;-23060.0
(78)(7A)
0.209;-20360.0
7(7JA)
0.196;-22700.0
7K(7A)
0.191;-21380.0
(78QA)
0.195;-25700.0
8(7TA)
0.174;-27020.0
8Q(7A)
0.162;-25700.0
J(79A)
0.192;-25700.0
9T(7A)
0.167;-26360.0
(9K)(7A)
0.180;-20060.0
K(7TA)
0.194;-23720.0
T(7KA)
0.202;-23720.0
JJ(7A)
0.160;-20060.0
(7QKA)
0.167;-22400.0
777A
0.144;-25340.0
7A(7T)
0.157;-23360.0
77(KA)
0.202;-21380.0
7(8TA)
0.161;-27020.0
7Q(8A)
0.164;-25700.0
(78)(TA)
0.165;-22700.0
QA(78)
0.187;-25700.0
789A
0.166;-32000.0
78JA
0.120;-30680.0
78KA
0.199;-29360.0
7J(9A)
0.161;-25700.0
(79)(TA)
0.183;-22040.0
QA(79)
0.160;-25040.0
79TA
0.168;-30680.0
79QA
0.134;-29360.0
(7J)(TA)
0.188;-20720.0
TA(7T)
0.170;-21380.0
A(7TK)
0.216;-23720.0
TA(7Q)
0.189;-24380.0
7J(JA)
0.173;-20060.0
(7J)(QA)
0.202;-19400.0
JA(7Q)
0.198;-23720.0
7Q(QA)
0.180;-18740.0
7QQA
0.250;-23060.0
7KKA
0.157;-21740.0
8(8JA)
0.189;-21380.0
8K(8A)
0.189;-20060.0
(89KA)
0.189;-23720.0
9J(8A)
0.191;-25040.0
(8TJA)
0.169;-24380.0
(TJ)(8A)
0.206;-20060.0
J(8JA)
0.200;-19400.0
JQ(8A)
0.161;-23060.0
Q(8KA)
0.159;-21740.0
889A
0.169;-27020.0
8A(8Q)
0.175;-20720.0
(8T)(9A)
0.149;-21380.0
8(9KA)
0.185;-23720.0
A(89J)
0.148;-25040.0
899A
0.190;-26360.0
89JA
0.123;-29360.0
89KA
0.208;-28040.0
8Q(TA)
0.213;-23720.0
(8T)(QA)
0.216;-19400.0
TA(8J)
0.198;-24380.0
TA(8K)
0.176;-23060.0
8(JKA)
0.154;-22400.0
A(8JK)
0.194;-22400.0
JA(8K)
0.164;-22400.0
QA(8Q)
0.184;-18080.0
8QKA
0.172;-26060.0
9T(9A)
0.155;-20720.0
(9K)(9A)
0.253;-14420.0
K(9TA)
0.179;-22400.0
T(9KA)
0.154;-22400.0
JJ(9A)
0.163;-18740.0
(9QKA)
0.153;-21080.0
999A
0.201;-21380.0
9A(9Q)
0.200;-19400.0
(9J)(TA)
0.184;-19400.0
TA(9T)
0.184;-20060.0
A(9TK)
0.189;-22400.0
TA(9Q)
0.191;-23060.0
9J(JA)
0.185;-18740.0
(9J)(QA)
0.227;-18080.0
JA(9Q)
0.204;-22400.0
9Q(QA)
0.243;-17420.0
9QQA
0.175;-21740.0
9KKA
0.256;-20420.0
T(TKA)
0.249;-17420.0
JJ(TA)
0.202;-18080.0
(TQKA)
0.209;-20420.0
TTTA
0.219;-19400.0
TA(TK)
0.218;-17420.0
(TK)(JA)
0.220;-16760.0
KA(TJ)
0.213;-21080.0
TA(JK)
0.221;-21080.0
(TQ)(KA)
0.233;-16100.0
(TK)(KA)
0.276;-11120.0
J(JKA)
0.193;-16100.0
(QK)(JA)
0.253;-15440.0
JJ(KA)
0.230;-16100.0
QA(JQ)
0.248;-16100.0
JQKA
0.200;-24080.0
QK(QA)
0.197;-14780.0
QK(KA)
0.263;-14120.0
22(24)
0.147;-37520.0
22(28)
0.159;-34880.0
22(2Q)
0.111;-32240.0
24(23)
0.101;-41180.0
(23)(27)
0.139;-34880.0
2(23T)
0.125;-37220.0
2Q(23)
0.158;-35900.0
23(25)
0.117;-40520.0
2237
0.118;-43520.0
22(3T)
0.106;-37220.0
23(2K)
0.127;-35240.0
2(246)
0.127;-39200.0
28(24)
0.150;-37880.0
(24)(2J)
0.175;-31580.0
2244
0.146;-40520.0
22(47)
0.122;-38540.0
24(2T)
0.111;-36560.0
224Q
0.148;-39560.0
26(25)
0.092;-38540.0
(25)(29)
0.177;-32240.0
2(25Q)
0.125;-34580.0
22(56)
0.103;-38540.0
25(29)
0.127;-36560.0
225J
0.135;-39560.0
26(26)
0.126;-33560.0
(26)(29)
0.122;-31580.0
2(26Q)
0.114;-33920.0
22(67)
0.134;-37220.0
26(2T)
0.127;-35240.0
226Q
0.112;-38240.0
28(27)
0.105;-35900.0
(27)(2J)
0.137;-29600.0
2277
0.139;-36560.0
22(7T)
0.120;-34580.0
27(2K)
0.112;-32600.0
2(28T)
0.120;-33920.0
2Q(28)
0.111;-32600.0
28(2T)
0.183;-33920.0
228Q
0.130;-36920.0
2T(29)
0.104;-33260.0
(29)(2K)
0.144;-26960.0
229J
0.155;-36920.0
2T(2T)
0.203;-28280.0
(2T)(2K)
0.150;-26300.0
22TQ
0.103;-35600.0
2Q(2J)
0.126;-30620.0
2J(2K)
0.152;-29960.0
22QQ
0.130;-29960.0
3(234)
0.139;-40520.0
36(23)
0.119;-39200.0
(23)(39)
0.140;-32900.0
3(23Q)
0.127;-35240.0
5(234)
0.092;-43520.0
9(234)
0.132;-40880.0
K(234)
0.097;-38240.0
4(237)
0.120;-42200.0
49(23)
0.122;-40880.0
(23)(4Q)
0.099;-34580.0
(2357)
0.115;-41540.0
(235J)
0.104;-38900.0
(23)(56)
0.112;-37880.0
5(239)
0.098;-40220.0
5J(23)
0.158;-38900.0
(2367)
0.089;-40880.0
(236J)
0.105;-38240.0
(23)(67)
0.152;-36560.0
6(23T)
0.108;-38900.0
6Q(23)
0.119;-37580.0
9(237)
0.132;-38900.0
K(237)
0.147;-36260.0
7(23T)
0.150;-38240.0
7Q(23)
0.120;-36920.0
T(238)
0.096;-37580.0
8(239)
0.100;-38240.0
8J(23)
0.135;-36920.0
(239T)
0.134;-36920.0
99(23)
0.134;-33260.0
(23)(9Q)
0.150;-31280.0
(23TQ)
0.131;-34940.0
T(23Q)
0.129;-34940.0
Q(23J)
0.115;-34280.0
(23)(JK)
0.187;-29300.0
QK(23)
0.189;-32960.0
23(35)
0.136;-39860.0
33(28)
0.087;-37880.0
233T
0.113;-40880.0
23(3K)
0.123;-34580.0
(24)(36)
0.123;-38540.0
3(249)
0.090;-40880.0
3J(24)
0.152;-39560.0
(34)(25)
0.119;-39200.0
27(34)
0.112;-42200.0
2(34T)
0.122;-40220.0
(34)(2K)
0.120;-33920.0
34(26)
0.096;-42860.0
34(28)
0.103;-41540.0
34(2T)
0.116;-40220.0
34(2Q)
0.115;-38900.0
(25)(35)
0.163;-34220.0
3(258)
0.110;-40880.0
3T(25)
0.117;-39560.0
(25)(3K)
0.151;-33260.0
27(35)
0.098;-41540.0
2(35T)
0.122;-39560.0
(35)(2K)
0.133;-33260.0
35(27)
0.100;-41540.0
35(29)
0.098;-40220.0
35(2J)
0.143;-38900.0
35(2K)
0.132;-37580.0
37(26)
0.102;-40880.0
(26)(3T)
0.140;-34580.0
3(26K)
0.130;-36920.0
2(368)
0.124;-40220.0
(36)(2J)
0.124;-33920.0
2K(36)
0.129;-36920.0
23(68)
0.124;-40220.0
23(6T)
0.117;-38900.0
23(6Q)
0.142;-37580.0
3(278)
0.090;-39560.0
3T(27)
0.126;-38240.0
(27)(3K)
0.125;-31940.0
29(37)
0.135;-38900.0
2(37Q)
0.129;-36920.0
23(78)
0.148;-39560.0
23(7T)
0.154;-38240.0
23(7Q)
0.129;-36920.0
3(289)
0.085;-38240.0
3J(28)
0.142;-36920.0
(38)(29)
0.170;-33920.0
2J(38)
0.120;-36920.0
38(29)
0.150;-38240.0
38(2J)
0.120;-36920.0
38(2K)
0.126;-35600.0
3T(29)
0.137;-36920.0
(29)(3K)
0.194;-30620.0
2J(39)
0.102;-36260.0
39(2T)
0.132;-36920.0
39(2Q)
0.101;-35600.0
(2T)(3T)
0.167;-27620.0
3(2TK)
0.141;-34280.0
2(3TQ)
0.108;-34940.0
23(TJ)
0.111;-35600.0
23(TK)
0.186;-34280.0
(2J)(3K)
0.191;-29300.0
2K(3J)
0.135;-33620.0
23(JK)
0.109;-33620.0
(3Q)(2K)
0.166;-28640.0
(2K)(3K)
0.207;-23660.0
4(246)
0.126;-37880.0
48(24)
0.094;-36560.0
(24)(4J)
0.136;-30260.0
5(245)
0.128;-37880.0
9(245)
0.128;-39560.0
K(245)
0.121;-36920.0
5(248)
0.107;-40220.0
5T(24)
0.102;-38900.0
(24)(5K)
0.114;-32600.0
9(246)
0.103;-38900.0
K(246)
0.106;-36260.0
6(249)
0.153;-38900.0
6J(24)
0.129;-37580.0
(2478)
0.118;-38900.0
(247Q)
0.150;-36260.0
7(249)
0.136;-38240.0
7J(24)
0.105;-36920.0
(2489)
0.123;-37580.0
(248K)
0.123;-34940.0
8T(24)
0.100;-36920.0
(24)(8K)
0.139;-30620.0
Q(249)
0.116;-34940.0
(24)(9J)
0.150;-31280.0
T(24T)
0.190;-31280.0
T(24J)
0.144;-34940.0
TK(24)
0.114;-33620.0
(24)(JQ)
0.117;-29300.0
QQ(24)
0.128;-28640.0
24(45)
0.138;-38540.0
44(28)
0.100;-36560.0
244T
0.109;-39560.0
24(4K)
0.127;-33260.0
(25)(47)
0.101;-36560.0
4(25T)
0.128;-38900.0
4Q(25)
0.094;-37580.0
(45)(27)
0.126;-36560.0
29(45)
0.116;-39560.0
2(45Q)
0.127;-37580.0
24(56)
0.107;-41540.0
24(58)
0.118;-40220.0
24(5T)
0.122;-38900.0
24(5Q)
0.088;-37580.0
4(267)
0.118;-40220.0
49(26)
0.115;-38900.0
(26)(4Q)
0.109;-32600.0
27(46)
0.115;-40220.0
2(46T)
0.104;-38240.0
(46)(2K)
0.170;-31940.0
46(28)
0.122;-39560.0
46(2T)
0.141;-38240.0
46(2Q)
0.140;-36920.0
(27)(47)
0.152;-30920.0
4(27T)
0.108;-37580.0
4Q(27)
0.116;-36260.0
(47)(29)
0.135;-33920.0
2J(47)
0.088;-36920.0
47(28)
0.118;-38900.0
47(2T)
0.116;-37580.0
47(2Q)
0.104;-36260.0
(28)(48)
0.161;-29600.0
4(28J)
0.120;-36260.0
4K(28)
0.106;-34940.0
(48)(2J)
0.147;-31940.0
2K(48)
0.123;-34940.0
24(8T)
0.132;-36920.0
24(8Q)
0.122;-35600.0
4(29T)
0.112;-36260.0
4Q(29)
0.117;-34940.0
(49)(2J)
0.141;-31280.0
2K(49)
0.139;-34280.0
24(9J)
0.145;-35600.0
24(9K)
0.137;-34280.0
(2T)(4Q)
0.149;-29960.0
2J(4T)
0.101;-34940.0
4T(2J)
0.157;-34940.0
4T(2K)
0.146;-33620.0
4Q(2J)
0.115;-33620.0
(4J)(2K)
0.121;-28640.0
4J(2K)
0.139;-32960.0
4K(2Q)
0.165;-32300.0
24(QK)
0.133;-32300.0
(25)(56)
0.138;-32240.0
5(259)
0.136;-34580.0
5J(25)
0.129;-33260.0
(2567)
0.124;-39560.0
(256J)
0.157;-36920.0
(25)(67)
0.121;-35240.0
6(25T)
0.161;-37580.0
6Q(25)
0.139;-36260.0
9(257)
0.115;-37580.0
K(257)
0.135;-34940.0
7(25T)
0.126;-36920.0
7Q(25)
0.132;-35600.0
T(258)
0.145;-36260.0
8(259)
0.124;-36920.0
8J(25)
0.116;-35600.0
(259T)
0.115;-35600.0
99(25)
0.144;-31940.0
(25)(9Q)
0.139;-29960.0
(25TQ)
0.163;-33620.0
T(25Q)
0.110;-33620.0
Q(25J)
0.156;-32960.0
(25)(JK)
0.185;-27980.0
QK(25)
0.170;-31640.0
25(57)
0.139;-35900.0
55(2T)
0.170;-33920.0
255Q
0.129;-36920.0
57(26)
0.133;-39560.0
(26)(5T)
0.149;-33260.0
5(26K)
0.132;-35600.0
2(568)
0.126;-38900.0
(56)(2J)
0.114;-32600.0
2K(56)
0.146;-35600.0
25(68)
0.111;-38900.0
25(6T)
0.133;-37580.0
25(6Q)
0.109;-36260.0
5(278)
0.134;-38240.0
5T(27)
0.119;-36920.0
(27)(5K)
0.146;-30620.0
29(57)
0.143;-37580.0
2(57Q)
0.138;-35600.0
25(78)
0.140;-38240.0
25(7T)
0.149;-36920.0
25(7Q)
0.120;-35600.0
5(289)
0.124;-36920.0
5J(28)
0.127;-35600.0
(58)(29)
0.116;-32600.0
2J(58)
0.161;-35600.0
58(29)
0.145;-36920.0
58(2J)
0.144;-35600.0
58(2K)
0.128;-34280.0
5T(29)
0.174;-35600.0
(29)(5K)
0.168;-29300.0
2J(59)
0.129;-34940.0
59(2T)
0.115;-35600.0
59(2Q)
0.148;-34280.0
(2T)(5T)
0.170;-26300.0
5(2TK)
0.141;-32960.0
2(5TQ)
0.117;-33620.0
25(TJ)
0.121;-34280.0
25(TK)
0.130;-32960.0
(2J)(5K)
0.197;-27980.0
2K(5J)
0.155;-32300.0
25(JK)
0.156;-32300.0
(5Q)(2K)
0.158;-27320.0
(2K)(5K)
0.161;-22340.0
6(268)
0.128;-33920.0
6T(26)
0.160;-32600.0
(26)(6K)
0.169;-26300.0
T(267)
0.129;-36260.0
7(268)
0.102;-37580.0
7T(26)
0.158;-36260.0
(26)(7K)
0.136;-29960.0
J(268)
0.129;-34940.0
89(26)
0.123;-36260.0
(26)(8Q)
0.164;-29960.0
(269J)
0.122;-34280.0
(26)(9T)
0.143;-30620.0
9(26K)
0.166;-32960.0
(26TK)
0.152;-32300.0
TQ(26)
0.157;-32960.0
K(26J)
0.202;-31640.0
Q(26Q)
0.185;-27320.0
KK(26)
0.164;-26000.0
66(29)
0.119;-33260.0
266J
0.152;-36260.0
67(27)
0.124;-33920.0
(27)(6T)
0.141;-31940.0
6(27K)
0.162;-34280.0
2(679)
0.141;-36920.0
(67)(2Q)
0.164;-30620.0
27(68)
0.148;-37580.0
27(6T)
0.146;-36260.0
27(6Q)
0.160;-34940.0
68(28)
0.108;-32600.0
(28)(6J)
0.129;-30620.0
28(68)
0.155;-32600.0
2(68J)
0.140;-34940.0
2688
0.162;-36920.0
268T
0.121;-39920.0
268Q
0.164;-38600.0
(29)(6T)
0.195;-30620.0
6(29K)
0.140;-32960.0
2(69J)
0.146;-34280.0
2699
0.140;-35600.0
269J
0.108;-38600.0
269K
0.116;-37280.0
6Q(2T)
0.135;-32960.0
(6T)(2Q)
0.170;-28640.0
2T(6J)
0.116;-33620.0
2T(6K)
0.148;-32300.0
6(2JK)
0.116;-31640.0
2(6JK)
0.159;-31640.0
2J(6K)
0.164;-31640.0
2Q(6Q)
0.167;-27320.0
26QK
0.153;-35300.0
78(27)
0.169;-32600.0
(27)(7J)
0.166;-26300.0
8(278)
0.159;-31940.0
Q(278)
0.105;-33620.0
(27)(8T)
0.190;-30620.0
8(27K)
0.158;-32960.0
(279Q)
0.151;-32960.0
9(27J)
0.162;-33620.0
9K(27)
0.159;-32300.0
TT(27)
0.182;-29300.0
(27)(TK)
0.197;-27320.0
J(27Q)
0.196;-31640.0
K(27Q)
0.149;-30320.0
77(28)
0.126;-32600.0
277T
0.100;-35600.0
27(7K)
0.160;-29300.0
(28)(7T)
0.148;-30620.0
7(28K)
0.145;-32960.0
2(78T)
0.103;-34940.0
(78)(2K)
0.164;-28640.0
78(2T)
0.125;-34940.0
78(2Q)
0.133;-33620.0
(29)(79)
0.173;-26300.0
7(29Q)
0.151;-32960.0
2(79T)
0.122;-34280.0
(79)(2K)
0.153;-27980.0
79(2J)
0.192;-33620.0
79(2K)
0.174;-32300.0
7J(2T)
0.100;-32960.0
(7T)(2J)
0.155;-28640.0
2K(7T)
0.155;-31640.0
27(TQ)
0.175;-32300.0
7(2JQ)
0.126;-31640.0
2(7JQ)
0.134;-31640.0
27(JQ)
0.120;-31640.0
7(2QK)
0.131;-30320.0
7Q(2K)
0.150;-30320.0
88(28)
0.180;-26960.0
(28)(8J)
0.178;-24980.0
9(289)
0.124;-29960.0
K(289)
0.141;-31640.0
9(28Q)
0.150;-32300.0
J(28T)
0.154;-32300.0
TJ(28)
0.158;-32300.0
(28JQ)
0.126;-30980.0
J(28K)
0.117;-30320.0
(28)(QK)
0.195;-25340.0
88(2T)
0.123;-29960.0
288Q
0.119;-32960.0
8T(29)
0.111;-33620.0
(29)(8K)
0.174;-27320.0
2J(89)
0.128;-32960.0
89(2T)
0.137;-33620.0
89(2Q)
0.133;-32300.0
(2T)(8T)
0.220;-24320.0
8(2TK)
0.163;-30980.0
2(8TQ)
0.121;-31640.0
28(TJ)
0.109;-32300.0
28(TK)
0.135;-30980.0
(2J)(8K)
0.153;-26000.0
2K(8J)
0.134;-30320.0
28(JK)
0.117;-30320.0
(8Q)(2K)
0.157;-25340.0
(2K)(8K)
0.257;-20360.0
9(29J)
0.145;-27980.0
9K(29)
0.177;-26660.0
TT(29)
0.151;-27980.0
(29)(TK)
0.154;-26000.0
J(29Q)
0.179;-30320.0
K(29Q)
0.126;-29000.0
99(2T)
0.161;-28640.0
299Q
0.148;-31640.0
9J(2T)
0.126;-31640.0
(9T)(2J)
0.185;-27320.0
2K(9T)
0.128;-30320.0
29(TQ)
0.122;-30980.0
9(2JQ)
0.140;-30320.0
2(9JQ)
0.139;-30320.0
29(JQ)
0.157;-30320.0
9(2QK)
0.176;-29000.0
9Q(2K)
0.175;-29000.0
TT(2T)
0.204;-23000.0
(2T)(TK)
0.171;-21020.0
J(2TQ)
0.156;-29660.0
K(2TQ)
0.178;-28340.0
TT(2J)
0.187;-26660.0
2TTK
0.156;-29660.0
TK(2J)
0.159;-29000.0
2TJJ
0.123;-30320.0
2TJK
0.171;-33320.0
2(TQK)
0.156;-28340.0
TK(2K)
0.183;-23360.0
(2J)(JK)
0.191;-19700.0
QK(2J)
0.177;-27680.0
2J(JK)
0.145;-24020.0
(JQ)(2K)
0.146;-23360.0
(2K)(JK)
0.189;-18380.0
K(2QK)
0.219;-22040.0
2K(QK)
0.168;-22040.0
3335
0.131;-39200.0
3339
0.144;-36560.0
333K
0.132;-33920.0
36(34)
0.128;-37880.0
(34)(39)
0.131;-31580.0
3(34Q)
0.171;-33920.0
33(45)
0.108;-38540.0
34(38)
0.156;-36560.0
334T
0.127;-39560.0
33(4K)
0.123;-33260.0
(35)(37)
0.130;-32240.0
3(35T)
0.132;-34580.0
3Q(35)
0.165;-33260.0
35(37)
0.145;-36560.0
3359
0.122;-39560.0
33(5Q)
0.159;-33260.0
(36)(37)
0.170;-31580.0
3(36T)
0.138;-33920.0
3Q(36)
0.179;-32600.0
36(38)
0.114;-35240.0
336T
0.127;-38240.0
33(6K)
0.163;-31940.0
(37)(39)
0.155;-29600.0
3(37Q)
0.126;-31940.0
33(78)
0.136;-34580.0
37(3J)
0.152;-32600.0
337K
0.124;-35600.0
3T(38)
0.142;-32600.0
(38)(3K)
0.170;-26300.0
338T
0.118;-36920.0
33(8K)
0.150;-30620.0
(39)(3J)
0.155;-26960.0
3399
0.175;-32600.0
33(9Q)
0.119;-30620.0
(3T)(3J)
0.168;-26300.0
33TT
0.120;-31280.0
33(TK)
0.192;-29300.0
(3J)(3K)
0.147;-24320.0
33JK
0.143;-32960.0
33(QK)
0.212;-27980.0
45(34)
0.132;-37880.0
(34)(48)
0.139;-31580.0
4(34J)
0.147;-33920.0
4K(34)
0.173;-32600.0
(3459)
0.118;-38900.0
(345K)
0.148;-36260.0
57(34)
0.110;-40220.0
(34)(5T)
0.167;-33920.0
5(34K)
0.115;-36260.0
(3469)
0.105;-38240.0
(346K)
0.144;-35600.0
68(34)
0.154;-38900.0
(34)(6J)
0.127;-32600.0
7(347)
0.107;-34580.0
J(347)
0.111;-36260.0
78(34)
0.092;-38240.0
(34)(7J)
0.183;-31940.0
8(348)
0.176;-33260.0
Q(348)
0.138;-34940.0
(34)(8T)
0.117;-31940.0
8(34K)
0.107;-34280.0
(349Q)
0.142;-34280.0
9(34J)
0.162;-34940.0
9K(34)
0.108;-33620.0
TT(34)
0.177;-30620.0
(34)(TK)
0.141;-28640.0
J(34Q)
0.127;-32960.0
K(34Q)
0.126;-31640.0
44(35)
0.113;-37880.0
3447
0.102;-40880.0
34(4T)
0.144;-34580.0
44(3K)
0.131;-32600.0
4(357)
0.113;-40220.0
49(35)
0.128;-38900.0
(35)(4Q)
0.129;-32600.0
36(45)
0.148;-40880.0
3(459)
0.116;-38900.0
(45)(3Q)
0.134;-32600.0
35(46)
0.084;-40880.0
35(48)
0.130;-39560.0
35(4T)
0.113;-38240.0
35(4Q)
0.128;-36920.0
46(36)
0.115;-35900.0
(36)(49)
0.136;-33920.0
4(36Q)
0.099;-36260.0
3(467)
0.096;-39560.0
(46)(3T)
0.148;-33260.0
3Q(46)
0.148;-36260.0
3467
0.113;-43880.0
3469
0.111;-42560.0
346J
0.114;-41240.0
346K
0.115;-39920.0
49(37)
0.118;-37580.0
(37)(4Q)
0.160;-31280.0
38(47)
0.132;-38240.0
3(47J)
0.131;-36260.0
3477
0.116;-38900.0
3479
0.104;-41900.0
347J
0.086;-40580.0
347K
0.131;-39260.0
4T(38)
0.111;-36260.0
(38)(4K)
0.137;-29960.0
3T(48)
0.097;-36260.0
3(48K)
0.107;-34280.0
38(4T)
0.120;-36260.0
38(4Q)
0.138;-34940.0
49(39)
0.163;-31940.0
(39)(4Q)
0.149;-29960.0
3T(49)
0.117;-35600.0
3(49K)
0.152;-33620.0
39(4J)
0.143;-34940.0
39(4K)
0.144;-33620.0
4(3TQ)
0.139;-33620.0
3(4TJ)
0.125;-34280.0
34TT
0.149;-34940.0
34TQ
0.094;-37940.0
(3J)(4Q)
0.178;-28640.0
3Q(4J)
0.125;-32960.0
34JQ
0.138;-37280.0
(3Q)(4K)
0.190;-27320.0
3Q(4K)
0.113;-31640.0
5(356)
0.102;-35900.0
58(35)
0.123;-34580.0
(35)(5J)
0.171;-28280.0
6(356)
0.143;-35240.0
T(356)
0.125;-36920.0
6(357)
0.157;-38900.0
69(35)
0.130;-37580.0
(35)(6Q)
0.155;-31280.0
(3579)
0.129;-36920.0
(357K)
0.133;-34280.0
79(35)
0.118;-36920.0
(35)(7Q)
0.151;-30620.0
(358T)
0.144;-35600.0
88(35)
0.139;-32600.0
(35)(8J)
0.204;-30620.0
9(359)
0.109;-31280.0
K(359)
0.151;-32960.0
9(35Q)
0.106;-33620.0
J(35T)
0.132;-33620.0
TJ(35)
0.110;-33620.0
(35JQ)
0.143;-32300.0
J(35K)
0.182;-31640.0
(35)(QK)
0.153;-26660.0
55(37)
0.148;-35240.0
3559
0.116;-38240.0
35(5Q)
0.136;-31940.0
(36)(57)
0.122;-34580.0
5(36T)
0.148;-36920.0
5Q(36)
0.115;-35600.0
(56)(38)
0.156;-33920.0
3T(56)
0.148;-36920.0
3(56K)
0.115;-34940.0
36(58)
0.143;-38240.0
36(5T)
0.127;-36920.0
36(5Q)
0.175;-35600.0
57(37)
0.130;-33920.0
(37)(5T)
0.133;-31940.0
5(37K)
0.180;-34280.0
3(579)
0.147;-36920.0
(57)(3Q)
0.161;-30620.0
37(58)
0.118;-37580.0
37(5T)
0.119;-36260.0
37(5Q)
0.125;-34940.0
58(38)
0.131;-32600.0
(38)(5J)
0.147;-30620.0
38(58)
0.124;-32600.0
3(58J)
0.143;-34940.0
3588
0.137;-36920.0
358T
0.137;-39920.0
358Q
0.134;-38600.0
(39)(5T)
0.118;-30620.0
5(39K)
0.144;-32960.0
3(59J)
0.148;-34280.0
3599
0.107;-35600.0
359J
0.148;-38600.0
359K
0.152;-37280.0
5Q(3T)
0.180;-32960.0
(5T)(3Q)
0.193;-28640.0
3T(5J)
0.137;-33620.0
3T(5K)
0.107;-32300.0
5(3JK)
0.161;-31640.0
3(5JK)
0.145;-31640.0
3J(5K)
0.131;-31640.0
3Q(5Q)
0.188;-27320.0
35QK
0.141;-35300.0
67(36)
0.119;-33920.0
(36)(6T)
0.160;-27620.0
6(36K)
0.119;-29960.0
(367T)
0.141;-35600.0
77(36)
0.134;-33260.0
(36)(7T)
0.149;-31280.0
7(36K)
0.144;-33620.0
(368J)
0.171;-34280.0
(36)(89)
0.119;-31280.0
8(36Q)
0.137;-33620.0
T(369)
0.112;-34280.0
9(36T)
0.114;-34280.0
9Q(36)
0.136;-32960.0
Q(36T)
0.144;-32300.0
(36)(TQ)
0.133;-27980.0
(36JK)
0.131;-30980.0
JK(36)
0.115;-30980.0
K(36K)
0.191;-25340.0
3668
0.130;-37580.0
36(6J)
0.151;-31280.0
(37)(67)
0.127;-28940.0
6(37T)
0.098;-35600.0
6Q(37)
0.125;-34280.0
(67)(39)
0.133;-31940.0
3J(67)
0.154;-34940.0
67(38)
0.099;-36920.0
67(3T)
0.132;-35600.0
67(3Q)
0.153;-34280.0
(38)(68)
0.183;-27620.0
6(38J)
0.113;-34280.0
6K(38)
0.178;-32960.0
(68)(3J)
0.156;-29960.0
3K(68)
0.181;-32960.0
36(8T)
0.146;-34940.0
36(8Q)
0.113;-33620.0
6(39T)
0.143;-34280.0
6Q(39)
0.148;-32960.0
(69)(3J)
0.134;-29300.0
3K(69)
0.120;-32300.0
36(9J)
0.116;-33620.0
36(9K)
0.143;-32300.0
(3T)(6Q)
0.203;-27980.0
3J(6T)
0.167;-32960.0
6T(3J)
0.148;-32960.0
6T(3K)
0.144;-31640.0
6Q(3J)
0.125;-31640.0
(6J)(3K)
0.182;-26660.0
6J(3K)
0.167;-30980.0
6K(3Q)
0.150;-30320.0
36(QK)
0.125;-30320.0
(37)(78)
0.193;-27620.0
7(37J)
0.158;-29960.0
7K(37)
0.160;-28640.0
(378Q)
0.175;-32960.0
8(37T)
0.117;-34280.0
8Q(37)
0.158;-32960.0
J(379)
0.107;-32960.0
9T(37)
0.137;-33620.0
(37)(9K)
0.163;-27320.0
K(37T)
0.139;-30980.0
T(37K)
0.156;-30980.0
JJ(37)
0.144;-27320.0
(37QK)
0.181;-29660.0
3777
0.139;-32600.0
37(7T)
0.134;-30620.0
77(3K)
0.149;-28640.0
7(38T)
0.166;-34280.0
7Q(38)
0.146;-32960.0
(78)(3T)
0.158;-29960.0
3Q(78)
0.160;-32960.0
3789
0.136;-39260.0
378J
0.134;-37940.0
378K
0.102;-36620.0
7J(39)
0.149;-32960.0
(79)(3T)
0.132;-29300.0
3Q(79)
0.163;-32300.0
379T
0.114;-37940.0
379Q
0.141;-36620.0
(3T)(7J)
0.151;-27980.0
3T(7T)
0.145;-28640.0
3(7TK)
0.117;-30980.0
3T(7Q)
0.136;-31640.0
7J(3J)
0.155;-27320.0
(7J)(3Q)
0.221;-26660.0
3J(7Q)
0.137;-30980.0
7Q(3Q)
0.162;-26000.0
37QQ
0.130;-30320.0
37KK
0.202;-29000.0
8(38J)
0.174;-28640.0
8K(38)
0.166;-27320.0
(389K)
0.155;-30980.0
9J(38)
0.153;-32300.0
(38TJ)
0.141;-31640.0
(38)(TJ)
0.139;-27320.0
J(38J)
0.168;-26660.0
JQ(38)
0.153;-30320.0
Q(38K)
0.183;-29000.0
3889
0.113;-34280.0
38(8Q)
0.160;-27980.0
(39)(8T)
0.187;-28640.0
8(39K)
0.146;-30980.0
3(89J)
0.152;-32300.0
3899
0.114;-33620.0
389J
0.145;-36620.0
389K
0.127;-35300.0
8Q(3T)
0.111;-30980.0
(8T)(3Q)
0.187;-26660.0
3T(8J)
0.139;-31640.0
3T(8K)
0.132;-30320.0
8(3JK)
0.142;-29660.0
3(8JK)
0.134;-29660.0
3J(8K)
0.147;-29660.0
3Q(8Q)
0.176;-25340.0
38QK
0.134;-33320.0
9T(39)
0.141;-27980.0
(39)(9K)
0.170;-21680.0
K(39T)
0.170;-29660.0
T(39K)
0.179;-29660.0
JJ(39)
0.214;-26000.0
(39QK)
0.125;-28340.0
3999
0.156;-28640.0
39(9Q)
0.204;-26660.0
(3T)(9J)
0.207;-26660.0
3T(9T)
0.135;-27320.0
3(9TK)
0.170;-29660.0
3T(9Q)
0.155;-30320.0
9J(3J)
0.175;-26000.0
(9J)(3Q)
0.178;-25340.0
3J(9Q)
0.121;-29660.0
9Q(3Q)
0.204;-24680.0
39QQ
0.212;-29000.0
39KK
0.118;-27680.0
T(3TK)
0.168;-24680.0
JJ(3T)
0.136;-25340.0
(3TQK)
0.174;-27680.0
3TTT
0.195;-26660.0
3T(TK)
0.225;-24680.0
(3J)(TK)
0.175;-24020.0
3K(TJ)
0.168;-28340.0
3T(JK)
0.203;-28340.0
(TQ)(3K)
0.177;-23360.0
(3K)(TK)
0.191;-18380.0
J(3JK)
0.218;-23360.0
(3J)(QK)
0.243;-22700.0
JJ(3K)
0.154;-23360.0
3Q(JQ)
0.177;-23360.0
3JQK
0.149;-31340.0
QK(3Q)
0.206;-22040.0
QK(3K)
0.203;-21380.0
44(46)
0.129;-32240.0
44(4T)
0.149;-29600.0
(45)(45)
0.149;-27920.0
4(458)
0.144;-34580.0
4T(45)
0.136;-33260.0
(45)(4K)
0.143;-26960.0
4457
0.119;-39560.0
44(5T)
0.159;-33260.0
45(4K)
0.128;-31280.0
4(468)
0.114;-33920.0
4T(46)
0.112;-32600.0
(46)(4K)
0.220;-26300.0
4468
0.130;-38240.0
44(6J)
0.159;-31940.0
(47)(47)
0.141;-25280.0
4(47T)
0.169;-31940.0
4Q(47)
0.160;-30620.0
47(49)
0.161;-32600.0
447J
0.127;-35600.0
48(48)
0.143;-28280.0
(48)(4J)
0.169;-26300.0
4488
0.179;-32600.0
44(8J)
0.107;-30620.0
(49)(49)
0.172;-22640.0
4(49Q)
0.160;-29300.0
44(9T)
0.162;-30620.0
49(4K)
0.173;-28640.0
4(4TQ)
0.147;-28640.0
44(TJ)
0.171;-29300.0
(4J)(4J)
0.198;-20000.0
44JJ
0.166;-28640.0
4Q(4Q)
0.180;-23000.0
(4K)(4K)
0.223;-17360.0
(45)(57)
0.173;-30260.0
5(45T)
0.123;-32600.0
5Q(45)
0.149;-31280.0
8(456)
0.114;-37580.0
Q(456)
0.110;-34940.0
(45)(68)
0.143;-33260.0
6(45J)
0.112;-35600.0
6K(45)
0.123;-34280.0
(457J)
0.103;-34940.0
(45)(78)
0.143;-32600.0
7(45J)
0.151;-34940.0
7K(45)
0.125;-33620.0
(458Q)
0.147;-33620.0
8(45T)
0.143;-34940.0
8Q(45)
0.116;-33620.0
J(459)
0.123;-33620.0
9T(45)
0.115;-34280.0
(45)(9K)
0.132;-27980.0
K(45T)
0.130;-31640.0
T(45K)
0.133;-31640.0
JJ(45)
0.168;-27980.0
(45QK)
0.136;-30320.0
4555
0.111;-35900.0
45(58)
0.118;-33920.0
55(4J)
0.155;-31940.0
455K
0.122;-34940.0
58(46)
0.103;-37580.0
(46)(5J)
0.164;-31280.0
46(56)
0.148;-34580.0
4(569)
0.098;-36920.0
(56)(4Q)
0.132;-30620.0
46(57)
0.125;-38240.0
46(59)
0.105;-36920.0
46(5J)
0.116;-35600.0
46(5K)
0.158;-34280.0
5(479)
0.135;-36260.0
5J(47)
0.143;-34940.0
(57)(48)
0.129;-32600.0
4T(57)
0.131;-35600.0
4(57K)
0.120;-33620.0
47(59)
0.135;-36260.0
47(5J)
0.132;-34940.0
47(5K)
0.130;-33620.0
5(48T)
0.144;-34940.0
5Q(48)
0.119;-33620.0
(58)(4T)
0.132;-30620.0
4Q(58)
0.127;-33620.0
4589
0.093;-39920.0
458J
0.120;-38600.0
458K
0.130;-37280.0
5J(49)
0.133;-33620.0
(59)(4T)
0.131;-29960.0
4Q(59)
0.125;-32960.0
459T
0.118;-38600.0
459Q
0.130;-37280.0
(4T)(5J)
0.170;-28640.0
4T(5T)
0.195;-29300.0
4(5TK)
0.148;-31640.0
4T(5Q)
0.111;-32300.0
5J(4J)
0.158;-27980.0
(5J)(4Q)
0.186;-27320.0
4J(5Q)
0.160;-31640.0
5Q(4Q)
0.178;-26660.0
45QQ
0.132;-30980.0
45KK
0.137;-29660.0
6(469)
0.152;-31940.0
6J(46)
0.145;-30620.0
(4678)
0.171;-36260.0
(467Q)
0.128;-33620.0
7(469)
0.126;-35600.0
7J(46)
0.112;-34280.0
(4689)
0.158;-34940.0
(468K)
0.150;-32300.0
8T(46)
0.113;-34280.0
(46)(8K)
0.191;-27980.0
Q(469)
0.151;-32300.0
(46)(9J)
0.139;-28640.0
T(46T)
0.149;-28640.0
T(46J)
0.138;-32300.0
TK(46)
0.147;-30980.0
(46)(JQ)
0.184;-26660.0
QQ(46)
0.200;-26000.0
46(67)
0.183;-33260.0
66(4T)
0.119;-31280.0
466Q
0.108;-34280.0
68(47)
0.117;-36260.0
(47)(6J)
0.153;-29960.0
47(67)
0.151;-32600.0
4(67T)
0.133;-34940.0
(67)(4K)
0.124;-28640.0
67(49)
0.125;-35600.0
67(4J)
0.125;-34280.0
67(4K)
0.138;-32960.0
69(48)
0.152;-34940.0
(48)(6Q)
0.145;-28640.0
49(68)
0.154;-34940.0
4(68Q)
0.140;-32960.0
46(89)
0.119;-34940.0
46(8J)
0.108;-33620.0
46(8K)
0.122;-32300.0
(49)(6J)
0.121;-28640.0
49(69)
0.167;-29960.0
4(69Q)
0.142;-32300.0
46(9T)
0.147;-33620.0
46(9Q)
0.134;-32300.0
6(4TJ)
0.140;-32300.0
6K(4T)
0.150;-30980.0
(6T)(4K)
0.169;-26660.0
6T(4Q)
0.154;-31640.0
(4J)(6J)
0.186;-23000.0
4J(6J)
0.154;-27320.0
6J(4Q)
0.130;-30980.0
(4Q)(6Q)
0.204;-21680.0
4K(6Q)
0.185;-29660.0
4K(6K)
0.176;-24680.0
79(47)
0.118;-30620.0
(47)(7Q)
0.202;-24320.0
(478T)
0.152;-33620.0
88(47)
0.191;-30620.0
(47)(8J)
0.135;-28640.0
9(479)
0.159;-29300.0
K(479)
0.165;-30980.0
9(47Q)
0.162;-31640.0
J(47T)
0.150;-31640.0
TJ(47)
0.147;-31640.0
(47JQ)
0.181;-30320.0
J(47K)
0.125;-29660.0
(47)(QK)
0.223;-24680.0
77(49)
0.109;-30620.0
477J
0.145;-33620.0
78(48)
0.160;-30620.0
(48)(7J)
0.158;-28640.0
48(78)
0.186;-30620.0
4(78J)
0.137;-32960.0
4788
0.152;-34940.0
478T
0.157;-37940.0
478Q
0.155;-36620.0
(49)(7T)
0.162;-28640.0
7(49K)
0.129;-30980.0
4(79J)
0.137;-32300.0
4799
0.177;-33620.0
479J
0.114;-36620.0
479K
0.134;-35300.0
7Q(4T)
0.123;-30980.0
(7T)(4Q)
0.198;-26660.0
4T(7J)
0.141;-31640.0
4T(7K)
0.188;-30320.0
7(4JK)
0.182;-29660.0
4(7JK)
0.172;-29660.0
4J(7K)
0.156;-29660.0
4Q(7Q)
0.217;-25340.0
47QK
0.140;-33320.0
89(48)
0.132;-29300.0
(48)(8Q)
0.216;-23000.0
(489J)
0.142;-31640.0
(48)(9T)
0.198;-27980.0
9(48K)
0.138;-30320.0
(48TK)
0.145;-29660.0
TQ(48)
0.120;-30320.0
K(48J)
0.142;-29000.0
Q(48Q)
0.178;-24680.0
KK(48)
0.205;-23360.0
88(4J)
0.154;-27980.0
488K
0.135;-30980.0
8J(49)
0.131;-31640.0
(89)(4T)
0.182;-27980.0
4Q(89)
0.143;-30980.0
489T
0.124;-36620.0
489Q
0.115;-35300.0
(4T)(8J)
0.140;-26660.0
4T(8T)
0.144;-27320.0
4(8TK)
0.126;-29660.0
4T(8Q)
0.157;-30320.0
8J(4J)
0.172;-26000.0
(8J)(4Q)
0.171;-25340.0
4J(8Q)
0.178;-29660.0
8Q(4Q)
0.178;-24680.0
48QQ
0.127;-29000.0
48KK
0.182;-27680.0
9(49Q)
0.164;-26000.0
J(49T)
0.162;-30320.0
TJ(49)
0.160;-30320.0
(49JQ)
0.149;-29000.0
J(49K)
0.160;-28340.0
(49)(QK)
0.189;-23360.0
99(4J)
0.143;-26660.0
499K
0.120;-29660.0
9Q(4T)
0.171;-29660.0
(9T)(4Q)
0.149;-25340.0
4T(9J)
0.152;-30320.0
4T(9K)
0.146;-29000.0
9(4JK)
0.163;-28340.0
4(9JK)
0.198;-28340.0
4J(9K)
0.136;-28340.0
4Q(9Q)
0.209;-24020.0
49QK
0.108;-32000.0
TJ(4T)
0.154;-25340.0
(4TJQ)
0.172;-28340.0
J(4TK)
0.142;-27680.0
(4T)(QK)
0.186;-22700.0
TT(4Q)
0.198;-24680.0
T(4JQ)
0.181;-28340.0
4(TJQ)
0.187;-28340.0
4T(JQ)
0.177;-28340.0
T(4QK)
0.173;-27020.0
TQ(4K)
0.203;-27020.0
JJ(4J)
0.202;-19700.0
(4JQK)
0.168;-26360.0
4JJJ
0.170;-24020.0
JQ(4Q)
0.165;-22700.0
4JQQ
0.145;-27020.0
4JKK
0.168;-25700.0
QQ(4K)
0.193;-21380.0
4KKK
0.160;-20060.0
55(59)
0.195;-28280.0
55(5K)
0.191;-25640.0
(56)(58)
0.194;-28280.0
5(56J)
0.186;-30620.0
5K(56)
0.173;-29300.0
56(59)
0.174;-31940.0
556J
0.143;-34940.0
57(57)
0.206;-28280.0
(57)(5T)
0.136;-26300.0
5(57K)
0.188;-28640.0
55(79)
0.151;-31280.0
57(5Q)
0.191;-29300.0
5(589)
0.171;-30620.0
5J(58)
0.119;-29300.0
58(59)
0.134;-30620.0
558J
0.170;-33620.0
59(59)
0.167;-25640.0
(59)(5Q)
0.193;-23660.0
559T
0.128;-33620.0
55(9K)
0.157;-27320.0
(5T)(5Q)
0.175;-23000.0
55TJ
0.163;-32300.0
5J(5J)
0.157;-23000.0
5J(5Q)
0.186;-26660.0
5(5QK)
0.181;-25340.0
5K(5K)
0.210;-20360.0
68(56)
0.148;-31940.0
(56)(6J)
0.176;-25640.0
7(567)
0.155;-31940.0
J(567)
0.148;-33620.0
78(56)
0.133;-35600.0
(56)(7J)
0.171;-29300.0
8(568)
0.156;-30620.0
Q(568)
0.136;-32300.0
(56)(8T)
0.139;-29300.0
8(56K)
0.144;-31640.0
(569Q)
0.151;-31640.0
9(56J)
0.152;-32300.0
9K(56)
0.119;-30980.0
TT(56)
0.198;-27980.0
(56)(TK)
0.200;-26000.0
J(56Q)
0.145;-30320.0
K(56Q)
0.131;-29000.0
66(57)
0.120;-32600.0
5669
0.142;-35600.0
56(6Q)
0.134;-29300.0
(57)(68)
0.124;-31280.0
6(57J)
0.146;-33620.0
6K(57)
0.166;-32300.0
(67)(5T)
0.174;-29960.0
5Q(67)
0.116;-32960.0
5678
0.101;-39920.0
567T
0.101;-38600.0
567Q
0.128;-37280.0
(58)(69)
0.184;-29960.0
6(58Q)
0.164;-32300.0
5(689)
0.145;-34280.0
(68)(5Q)
0.136;-27980.0
58(69)
0.166;-34280.0
58(6J)
0.144;-32960.0
58(6K)
0.186;-31640.0
6(59J)
0.137;-32300.0
6K(59)
0.176;-30980.0
(69)(5Q)
0.124;-27320.0
59(6T)
0.134;-32960.0
59(6Q)
0.189;-31640.0
6T(5T)
0.139;-27980.0
(5T)(6K)
0.213;-26000.0
5Q(6T)
0.121;-30980.0
56TJ
0.122;-35960.0
56TK
0.139;-34640.0
6K(5J)
0.126;-29660.0
56JJ
0.164;-30980.0
56JK
0.161;-33980.0
5(6QK)
0.167;-29000.0
6K(5K)
0.187;-24020.0
(57)(79)
0.168;-25640.0
7(57Q)
0.166;-27980.0
9(578)
0.133;-33620.0
K(578)
0.152;-30980.0
8(57J)
0.167;-32300.0
8K(57)
0.164;-30980.0
(579K)
0.147;-30320.0
9J(57)
0.138;-31640.0
(57TJ)
0.135;-30980.0
(57)(TJ)
0.185;-26660.0
J(57J)
0.137;-26000.0
JQ(57)
0.158;-29660.0
Q(57K)
0.198;-28340.0
5778
0.122;-34940.0
57(7J)
0.148;-28640.0
(58)(78)
0.145;-25640.0
7(58J)
0.160;-32300.0
7K(58)
0.144;-30980.0
(78)(5J)
0.189;-27980.0
5K(78)
0.109;-30980.0
57(8T)
0.128;-32960.0
57(8Q)
0.131;-31640.0
7(59T)
0.149;-32300.0
7Q(59)
0.157;-30980.0
(79)(5J)
0.125;-27320.0
5K(79)
0.140;-30320.0
57(9J)
0.127;-31640.0
57(9K)
0.148;-30320.0
(5T)(7Q)
0.175;-26000.0
5J(7T)
0.128;-30980.0
7T(5J)
0.154;-30980.0
7T(5K)
0.155;-29660.0
7Q(5J)
0.199;-29660.0
(7J)(5K)
0.158;-24680.0
7J(5K)
0.154;-29000.0
7K(5Q)
0.118;-28340.0
57(QK)
0.179;-28340.0
(58)(89)
0.208;-24320.0
8(58Q)
0.177;-26660.0
T(589)
0.164;-31640.0
9(58T)
0.133;-31640.0
9Q(58)
0.156;-30320.0
Q(58T)
0.150;-29660.0
(58)(TQ)
0.169;-25340.0
(58JK)
0.135;-28340.0
JK(58)
0.177;-28340.0
K(58K)
0.254;-22700.0
588T
0.136;-32300.0
58(8K)
0.181;-26000.0
(59)(8J)
0.138;-26660.0
59(89)
0.204;-27980.0
5(89Q)
0.202;-30320.0
58(9T)
0.171;-31640.0
58(9Q)
0.115;-30320.0
8(5TJ)
0.155;-30320.0
8K(5T)
0.133;-29000.0
(8T)(5K)
0.234;-24680.0
8T(5Q)
0.160;-29660.0
(5J)(8J)
0.159;-21020.0
5J(8J)
0.219;-25340.0
8J(5Q)
0.144;-29000.0
(5Q)(8Q)
0.210;-19700.0
5K(8Q)
0.170;-27680.0
5K(8K)
0.206;-22700.0
9J(59)
0.174;-26000.0
(59TJ)
0.197;-29660.0
(59)(TJ)
0.177;-25340.0
J(59J)
0.154;-24680.0
JQ(59)
0.155;-28340.0
Q(59K)
0.163;-27020.0
599T
0.160;-30980.0
59(9K)
0.192;-24680.0
(5T)(9Q)
0.214;-24680.0
5J(9T)
0.142;-29660.0
9T(5J)
0.148;-29660.0
9T(5K)
0.138;-28340.0
9Q(5J)
0.144;-28340.0
(9J)(5K)
0.202;-23360.0
9J(5K)
0.189;-27680.0
9K(5Q)
0.162;-27020.0
59(QK)
0.178;-27020.0
(5T)(TJ)
0.202;-20360.0
J(5TJ)
0.139;-24020.0
JQ(5T)
0.166;-27680.0
Q(5TK)
0.181;-26360.0
5TTJ
0.159;-29000.0
TJ(5J)
0.182;-24020.0
(TJ)(5Q)
0.187;-23360.0
5J(TQ)
0.172;-27680.0
TQ(5Q)
0.236;-22700.0
5TQQ
0.134;-27020.0
5TKK
0.178;-25700.0
Q(5JQ)
0.220;-22040.0
KK(5J)
0.169;-20720.0
(5Q)(JQ)
0.212;-17720.0
5K(JQ)
0.174;-25700.0
5K(JK)
0.195;-20720.0
5QQQ
0.184;-21380.0
KK(5K)
0.206;-15080.0
6669
0.152;-30620.0
666K
0.123;-27980.0
69(67)
0.169;-29960.0
(67)(6Q)
0.177;-23660.0
6678
0.169;-34940.0
66(7J)
0.150;-28640.0
(68)(68)
0.220;-21320.0
6(68J)
0.180;-27980.0
6K(68)
0.192;-26660.0
68(6J)
0.165;-27980.0
668K
0.131;-30980.0
6J(69)
0.190;-27320.0
69(6T)
0.134;-27980.0
669Q
0.175;-30980.0
6J(6T)
0.140;-26660.0
6T(6J)
0.145;-26660.0
66TK
0.146;-29660.0
6K(6J)
0.188;-24680.0
(6Q)(6Q)
0.231;-16040.0
66QK
0.188;-28340.0
7(679)
0.180;-29300.0
7J(67)
0.161;-27980.0
(6789)
0.147;-32960.0
(678K)
0.172;-30320.0
8T(67)
0.134;-32300.0
(67)(8K)
0.211;-26000.0
Q(679)
0.150;-30320.0
(67)(9J)
0.168;-26660.0
T(67T)
0.173;-26660.0
T(67J)
0.114;-30320.0
TK(67)
0.126;-29000.0
(67)(JQ)
0.158;-24680.0
QQ(67)
0.158;-24020.0
67(78)
0.150;-29960.0
77(6J)
0.132;-27980.0
677K
0.141;-30980.0
7T(68)
0.145;-32300.0
(68)(7K)
0.185;-26000.0
6T(78)
0.129;-32300.0
6(78K)
0.156;-30320.0
68(7T)
0.146;-32300.0
68(7Q)
0.161;-30980.0
79(69)
0.123;-27980.0
(69)(7Q)
0.180;-26000.0
6T(79)
0.140;-31640.0
6(79K)
0.141;-29660.0
69(7J)
0.136;-30980.0
69(7K)
0.153;-29660.0
7(6TQ)
0.136;-29660.0
6(7TJ)
0.114;-30320.0
67TT
0.156;-30980.0
67TQ
0.160;-33980.0
(6J)(7Q)
0.154;-24680.0
6Q(7J)
0.182;-29000.0
67JQ
0.129;-33320.0
(6Q)(7K)
0.181;-23360.0
6Q(7K)
0.147;-27680.0
8(689)
0.166;-27980.0
8J(68)
0.191;-26660.0
(689T)
0.157;-30980.0
99(68)
0.132;-27320.0
(68)(9Q)
0.173;-25340.0
(68TQ)
0.163;-29000.0
T(68Q)
0.123;-29000.0
Q(68J)
0.152;-28340.0
(68)(JK)
0.188;-23360.0
QK(68)
0.195;-27020.0
68(8T)
0.198;-27320.0
88(6K)
0.205;-25340.0
8(69J)
0.122;-30320.0
8K(69)
0.151;-29000.0
(89)(6Q)
0.153;-25340.0
69(8T)
0.173;-30980.0
69(8Q)
0.204;-29660.0
8T(6T)
0.163;-26000.0
(6T)(8K)
0.151;-24020.0
6Q(8T)
0.157;-29000.0
68TJ
0.136;-33980.0
68TK
0.180;-32660.0
8K(6J)
0.183;-27680.0
68JJ
0.134;-29000.0
68JK
0.119;-32000.0
6(8QK)
0.146;-27020.0
8K(6K)
0.193;-22040.0
(69)(9J)
0.201;-21020.0
T(69T)
0.190;-25340.0
T(69J)
0.157;-29000.0
TK(69)
0.154;-27680.0
(69)(JQ)
0.187;-23360.0
QQ(69)
0.169;-22700.0
69(9T)
0.160;-26000.0
99(6K)
0.237;-24020.0
9(6TQ)
0.186;-28340.0
6(9TJ)
0.176;-29000.0
69TT
0.128;-29660.0
69TQ
0.129;-32660.0
(6J)(9Q)
0.190;-23360.0
6Q(9J)
0.180;-27680.0
69JQ
0.123;-32000.0
(6Q)(9K)
0.179;-22040.0
6Q(9K)
0.167;-26360.0
T(6TJ)
0.207;-24020.0
TK(6T)
0.173;-22700.0
(6T)(JQ)
0.159;-22700.0
QQ(6T)
0.188;-22040.0
6T(TJ)
0.155;-24020.0
(6J)(TJ)
0.204;-19040.0
6J(TJ)
0.156;-23360.0
TJ(6Q)
0.124;-27020.0
(6Q)(TQ)
0.201;-17720.0
6K(TQ)
0.161;-25700.0
6K(TK)
0.160;-20720.0
JK(6J)
0.206;-21380.0
K(6JK)
0.197;-20060.0
6JJK
0.172;-25700.0
6(JQK)
0.138;-25040.0
JK(6K)
0.217;-20060.0
KK(6Q)
0.171;-19400.0
6QKK
0.156;-23720.0
77(7T)
0.181;-23660.0
(78)(78)
0.202;-20000.0
7(78J)
0.139;-26660.0
7K(78)
0.141;-25340.0
78(7J)
0.173;-26660.0
778K
0.172;-29660.0
7J(79)
0.187;-26000.0
79(7T)
0.151;-26660.0
779Q
0.186;-29660.0
7J(7T)
0.182;-25340.0
7T(7J)
0.160;-25340.0
77TK
0.191;-28340.0
7K(7J)
0.192;-23360.0
(7Q)(7Q)
0.264;-14720.0
77QK
0.130;-27020.0
8(78T)
0.160;-26660.0
8Q(78)
0.198;-25340.0
J(789)
0.147;-29660.0
9T(78)
0.164;-30320.0
(78)(9K)
0.236;-24020.0
K(78T)
0.180;-27680.0
T(78K)
0.204;-27680.0
JJ(78)
0.170;-24020.0
(78QK)
0.207;-26360.0
7888
0.189;-27980.0
78(8J)
0.228;-26000.0
(79)(89)
0.165;-22340.0
8(79Q)
0.118;-29000.0
7(89T)
0.202;-30320.0
(89)(7K)
0.202;-24020.0
89(7J)
0.176;-29660.0
89(7K)
0.151;-28340.0
8J(7T)
0.145;-29000.0
(8T)(7J)
0.165;-24680.0
7K(8T)
0.145;-27680.0
78(TQ)
0.122;-28340.0
8(7JQ)
0.130;-27680.0
7(8JQ)
0.161;-27680.0
78(JQ)
0.155;-27680.0
8(7QK)
0.158;-26360.0
8Q(7K)
0.164;-26360.0
99(79)
0.228;-21680.0
(79)(9Q)
0.207;-19700.0
(79TQ)
0.170;-27680.0
T(79Q)
0.171;-27680.0
Q(79J)
0.156;-27020.0
(79)(JK)
0.186;-22040.0
QK(79)
0.180;-25700.0
79(9J)
0.162;-24680.0
(7T)(9T)
0.163;-20360.0
9(7TK)
0.154;-27020.0
7(9TQ)
0.164;-27680.0
79(TJ)
0.188;-28340.0
79(TK)
0.161;-27020.0
(7J)(9K)
0.176;-22040.0
7K(9J)
0.203;-26360.0
79(JK)
0.171;-26360.0
(9Q)(7K)
0.158;-21380.0
(7K)(9K)
0.232;-16400.0
T(7TQ)
0.178;-22700.0
Q(7TJ)
0.137;-26360.0
(7T)(JK)
0.206;-21380.0
QK(7T)
0.228;-25040.0
7T(TQ)
0.198;-22700.0
(7J)(TQ)
0.214;-22040.0
7Q(TJ)
0.206;-26360.0
7TJQ
0.186;-30680.0
(7Q)(TK)
0.193;-20720.0
7Q(TK)
0.204;-25040.0
J(7JQ)
0.188;-21380.0
K(7JQ)
0.185;-24380.0
JJ(7Q)
0.250;-21380.0
J(7QK)
0.195;-24380.0
JQ(7K)
0.169;-24380.0
QQ(7Q)
0.205;-15740.0
7Q(QK)
0.162;-19400.0
8888
0.189;-23000.0
888Q
0.220;-24680.0
8(89J)
0.210;-24680.0
8K(89)
0.196;-23360.0
89(8Q)
0.142;-24020.0
8(8TJ)
0.185;-24020.0
8K(8T)
0.193;-22700.0
8T(8K)
0.180;-22700.0
8(8JK)
0.186;-22040.0
88(JK)
0.186;-22040.0
8Q(8K)
0.244;-21380.0
(89)(9T)
0.181;-20360.0
9(89K)
0.228;-22700.0
(89TK)
0.126;-26360.0
TQ(89)
0.164;-27020.0
K(89J)
0.172;-25700.0
Q(89Q)
0.237;-21380.0
KK(89)
0.204;-20060.0
99(8Q)
0.159;-23360.0
9(8TJ)
0.179;-27680.0
9K(8T)
0.164;-26360.0
(9T)(8K)
0.216;-22040.0
9T(8Q)
0.165;-27020.0
(8J)(9J)
0.252;-18380.0
8J(9J)
0.176;-22700.0
9J(8Q)
0.170;-26360.0
(8Q)(9Q)
0.217;-17060.0
8K(9Q)
0.178;-25040.0
8K(9K)
0.215;-20060.0
TQ(8T)
0.178;-22040.0
K(8TJ)
0.179;-25040.0
Q(8TQ)
0.211;-20720.0
KK(8T)
0.171;-19400.0
