AAAA
0.281;-7150.0
5AAA
0.235;-16768.7
9AAA
0.268;-14293.7
KAAA
0.230;-11818.7
4A(2A)
0.208;-24812.5
(2A)(7A)
0.166;-18906.3
A(2TA)
0.155;-21100.0
QA(2A)
0.203;-19862.5
2A(4A)
0.162;-24812.5
26AA
0.134;-27625.0
AA(29)
0.176;-21718.7
2A(QA)
0.212;-19862.5
A(34A)
0.209;-24193.7
6A(3A)
0.181;-22956.2
(3A)(9A)
0.207;-17050.0
A(3QA)
0.173;-19243.8
AA(34)
0.175;-24193.7
3A(7A)
0.219;-22337.5
39AA
0.206;-25150.0
AA(3Q)
0.184;-19243.8
(4A)(5A)
0.181;-18906.3
A(48A)
0.225;-21100.0
TA(4A)
0.231;-19862.5
(4A)(KA)
0.228;-13956.2
46AA
0.149;-26387.5
AA(49)
0.193;-20481.2
4A(QA)
0.262;-18625.0
A(56A)
0.194;-21718.7
8A(5A)
0.249;-20481.2
(5A)(JA)
0.234;-14575.0
55AA
0.166;-22337.5
AA(58)
0.239;-20481.2
5A(JA)
0.195;-18625.0
5KAA
0.199;-21437.5
8A(6A)
0.160;-19862.5
(6A)(JA)
0.219;-13956.2
66AA
0.200;-21100.0
AA(69)
0.167;-19243.8
6A(QA)
0.164;-17387.5
A(78A)
0.235;-19243.8
TA(7A)
0.223;-18006.2
(7A)(KA)
0.216;-12100.0
79AA
0.196;-22675.0
AA(7Q)
0.269;-16768.8
(8A)(9A)
0.278;-13956.2
A(8QA)
0.241;-16150.0
AA(89)
0.237;-18006.2
8A(QA)
0.240;-16150.0
A(9TA)
0.232;-16768.8
QA(9A)
0.221;-15531.3
9A(JA)
0.227;-16150.0
9KAA
0.169;-18962.5
QA(TA)
0.211;-14912.5
TA(QA)
0.181;-14912.5
A(JQA)
0.251;-14293.8
AA(JQ)
0.208;-14293.8
(QA)(KA)
0.301;-9006.3
KKAA
0.244;-12437.5
2(25A)
0.112;-31618.8
27(2A)
0.112;-30381.2
(2T)(2A)
0.224;-24475.0
2(2KA)
0.167;-26668.8
(236A)
0.132;-34431.2
(23TA)
0.167;-31956.2
33(2A)
0.111;-32237.5
(36)(2A)
0.117;-30381.2
3(29A)
0.127;-32575.0
3J(2A)
0.132;-31337.5
(245A)
0.115;-34431.2
(249A)
0.137;-31956.2
(24KA)
0.125;-29481.2
46(2A)
0.137;-33812.5
(49)(2A)
0.149;-27906.2
4(2QA)
0.160;-30100.0
6(25A)
0.127;-33193.8
T(25A)
0.190;-30718.8
5(26A)
0.138;-33193.8
58(2A)
0.128;-31956.2
(5J)(2A)
0.138;-26050.0
6(26A)
0.178;-28525.0
T(26A)
0.138;-30100.0
6(27A)
0.151;-31956.2
69(2A)
0.113;-30718.8
(6Q)(2A)
0.209;-24812.5
(279A)
0.157;-30100.0
(27KA)
0.135;-27625.0
79(2A)
0.150;-30100.0
(7Q)(2A)
0.156;-24193.8
(28TA)
0.173;-28862.5
88(2A)
0.180;-26050.0
(8J)(2A)
0.176;-24193.8
9(29A)
0.139;-24812.5
K(29A)
0.144;-26387.5
9(2QA)
0.169;-27006.2
J(2TA)
0.158;-27006.2
TJ(2A)
0.128;-27006.2
(2JQA)
0.146;-25768.7
J(2KA)
0.138;-25150.0
(QK)(2A)
0.197;-20481.2
22(4A)
0.123;-32237.5
226A
0.162;-35050.0
2A(29)
0.125;-29143.7
22(QA)
0.155;-27287.5
2(34A)
0.115;-35668.8
26(3A)
0.132;-34431.2
(29)(3A)
0.158;-28525.0
2(3QA)
0.164;-30718.8
A(234)
0.123;-35668.8
(23)(7A)
0.147;-29762.5
9A(23)
0.136;-32575.0
A(23Q)
0.123;-30718.8
2A(34)
0.116;-35668.8
2A(36)
0.115;-34431.2
2A(38)
0.096;-33193.8
2A(3T)
0.103;-31956.2
2A(3Q)
0.148;-30718.8
2(45A)
0.122;-34431.2
27(4A)
0.152;-33193.8
(2T)(4A)
0.166;-27287.5
2(4KA)
0.131;-29481.2
A(246)
0.131;-33812.5
(24)(9A)
0.141;-27906.2
JA(24)
0.148;-30718.8
24(5A)
0.128;-34431.2
24(7A)
0.112;-33193.8
24(9A)
0.167;-31956.2
24(JA)
0.139;-30718.8
24(KA)
0.176;-29481.2
26(5A)
0.160;-33193.8
(29)(5A)
0.184;-27287.5
2(5QA)
0.166;-29481.2
A(256)
0.164;-33193.8
(25)(9A)
0.145;-27287.5
JA(25)
0.163;-30100.0
25(6A)
0.108;-33193.8
25(8A)
0.131;-31956.2
25(TA)
0.138;-30718.8
25(QA)
0.152;-29481.2
(26)(6A)
0.188;-24475.0
2(69A)
0.148;-30718.8
2J(6A)
0.129;-29481.2
(26)(7A)
0.122;-27906.2
9A(26)
0.141;-30718.8
A(26Q)
0.132;-28862.5
2A(67)
0.186;-31956.2
2A(69)
0.141;-30718.8
2A(6J)
0.120;-29481.2
2A(6K)
0.159;-28243.8
(29)(7A)
0.194;-26050.0
2(7QA)
0.166;-28243.8
A(278)
0.126;-30718.8
(27)(JA)
0.205;-24812.5
KA(27)
0.179;-27625.0
2A(79)
0.156;-30100.0
2A(7J)
0.183;-28862.5
2A(7K)
0.185;-27625.0
(2T)(8A)
0.134;-24812.5
2(8KA)
0.156;-27006.2
A(28T)
0.154;-28862.5
(28)(KA)
0.181;-22956.2
28(TA)
0.117;-28862.5
28(QA)
0.167;-27625.0
(29)(9A)
0.193;-20762.5
2(9QA)
0.167;-27006.2
A(29T)
0.141;-28243.8
(29)(KA)
0.166;-22337.5
29(JA)
0.161;-27625.0
29(KA)
0.167;-26387.5
2J(TA)
0.179;-27006.2
(2T)(JA)
0.217;-22956.2
KA(2T)
0.145;-25768.7
2A(TQ)
0.164;-26387.5
2(JQA)
0.179;-25768.7
A(2JQ)
0.163;-25768.7
2A(JQ)
0.144;-25768.7
2(QKA)
0.206;-24531.2
2Q(KA)
0.147;-24531.2
33(3A)
0.166;-27568.7
(36)(3A)
0.183;-25712.5
3(39A)
0.133;-27906.2
3J(3A)
0.159;-26668.8
(345A)
0.168;-33812.5
(349A)
0.142;-31337.5
(34KA)
0.115;-28862.5
46(3A)
0.148;-33193.8
(49)(3A)
0.124;-27287.5
4(3QA)
0.114;-29481.2
6(35A)
0.118;-32575.0
T(35A)
0.133;-30100.0
5(36A)
0.156;-32575.0
58(3A)
0.143;-31337.5
(5J)(3A)
0.165;-25431.2
6(36A)
0.161;-27906.2
T(36A)
0.126;-29481.2
6(37A)
0.119;-31337.5
69(3A)
0.143;-30100.0
(6Q)(3A)
0.188;-24193.8
(379A)
0.154;-29481.2
(37KA)
0.122;-27006.2
79(3A)
0.112;-29481.2
(7Q)(3A)
0.161;-23575.0
(38TA)
0.121;-28243.8
88(3A)
0.194;-25431.2
(8J)(3A)
0.241;-23575.0
9(39A)
0.150;-24193.7
K(39A)
0.172;-25768.7
9(3QA)
0.199;-26387.5
J(3TA)
0.161;-26387.5
TJ(3A)
0.191;-26387.5
(3JQA)
0.186;-25150.0
J(3KA)
0.181;-24531.2
(QK)(3A)
0.184;-19862.5
33(5A)
0.114;-30381.2
337A
0.113;-33193.8
3A(3T)
0.185;-27287.5
33(KA)
0.216;-25431.2
3(46A)
0.151;-33193.8
38(4A)
0.163;-31956.2
(3J)(4A)
0.148;-26050.0
4A(34)
0.155;-30381.2
A(347)
0.144;-32575.0
(34)(TA)
0.136;-26668.8
QA(34)
0.131;-29481.2
345A
0.119;-37862.5
347A
0.099;-36625.0
349A
0.154;-35387.5
34JA
0.099;-34150.0
34KA
0.116;-32912.5
37(5A)
0.150;-31956.2
(3T)(5A)
0.151;-26050.0
3(5KA)
0.124;-28243.8
A(357)
0.110;-31956.2
(35)(TA)
0.176;-26050.0
QA(35)
0.123;-28862.5
356A
0.113;-36625.0
358A
0.112;-35387.5
35TA
0.119;-34150.0
35QA
0.130;-32912.5
(37)(6A)
0.125;-27287.5
3(6TA)
0.108;-29481.2
3Q(6A)
0.163;-28243.8
(36)(8A)
0.151;-26668.8
TA(36)
0.145;-29481.2
A(36K)
0.143;-27625.0
6A(38)
0.147;-30718.8
6A(3T)
0.157;-29481.2
6A(3Q)
0.173;-28243.8
37(7A)
0.158;-26668.8
(3T)(7A)
0.168;-24812.5
3(7KA)
0.128;-27006.2
A(379)
0.152;-29481.2
(37)(QA)
0.187;-23575.0
7A(38)
0.164;-30100.0
7A(3T)
0.153;-28862.5
7A(3Q)
0.180;-27625.0
38(8A)
0.196;-25431.2
(3J)(8A)
0.168;-23575.0
8A(38)
0.146;-25431.2
A(38J)
0.179;-27625.0
388A
0.160;-29481.2
38TA
0.141;-32293.8
38QA
0.123;-31056.2
(3T)(9A)
0.176;-23575.0
3(9KA)
0.182;-25768.7
A(39J)
0.181;-27006.2
399A
0.130;-28243.8
39JA
0.145;-31056.2
39KA
0.136;-29818.7
3Q(TA)
0.158;-25768.7
(3T)(QA)
0.228;-21718.7
TA(3J)
0.178;-26387.5
TA(3K)
0.214;-25150.0
3(JKA)
0.169;-24531.2
A(3JK)
0.176;-24531.2
JA(3K)
0.196;-24531.2
QA(3Q)
0.182;-20481.2
3QKA
0.159;-27962.5
45(4A)
0.152;-29143.7
(48)(4A)
0.185;-23237.5
4(4JA)
0.179;-25431.2
4K(4A)
0.197;-24193.7
(459A)
0.196;-30100.0
(45KA)
0.124;-27625.0
57(4A)
0.143;-31337.5
(5T)(4A)
0.166;-25431.2
5(4KA)
0.153;-27625.0
(469A)
0.147;-29481.2
(46KA)
0.174;-27006.2
68(4A)
0.154;-30100.0
(6J)(4A)
0.179;-24193.8
7(47A)
0.141;-26050.0
J(47A)
0.148;-27625.0
78(4A)
0.160;-29481.2
(7J)(4A)
0.186;-23575.0
8(48A)
0.137;-24812.5
Q(48A)
0.208;-26387.5
(8T)(4A)
0.203;-23575.0
8(4KA)
0.167;-25768.7
(49QA)
0.148;-25768.7
9(4JA)
0.170;-26387.5
9K(4A)
0.189;-25150.0
TT(4A)
0.241;-22337.5
(TK)(4A)
0.233;-20481.2
J(4QA)
0.187;-24531.2
K(4QA)
0.185;-23293.8
44(5A)
0.131;-29143.7
447A
0.139;-31956.2
4A(4T)
0.180;-26050.0
44(KA)
0.194;-24193.7
4(57A)
0.128;-31337.5
49(5A)
0.128;-30100.0
(4Q)(5A)
0.170;-24193.8
6A(45)
0.151;-31956.2
A(459)
0.150;-30100.0
(45)(QA)
0.211;-24193.8
5A(46)
0.115;-31956.2
5A(48)
0.148;-30718.8
5A(4T)
0.109;-29481.2
5A(4Q)
0.186;-28243.8
46(6A)
0.158;-27287.5
(49)(6A)
0.145;-25431.2
4(6QA)
0.138;-27625.0
A(467)
0.152;-30718.8
(46)(TA)
0.171;-24812.5
QA(46)
0.184;-27625.0
467A
0.146;-34768.8
469A
0.142;-33531.2
46JA
0.117;-32293.8
46KA
0.127;-31056.2
49(7A)
0.116;-28862.5
(4Q)(7A)
0.186;-22956.2
8A(47)
0.118;-29481.2
A(47J)
0.155;-27625.0
477A
0.193;-30100.0
479A
0.135;-32912.5
47JA
0.137;-31675.0
47KA
0.113;-30437.5
4T(8A)
0.156;-27625.0
(4K)(8A)
0.151;-21718.7
TA(48)
0.170;-27625.0
A(48K)
0.154;-25768.7
8A(4T)
0.137;-27625.0
8A(4Q)
0.129;-26387.5
49(9A)
0.195;-23575.0
(4Q)(9A)
0.177;-21718.7
TA(49)
0.167;-27006.2
A(49K)
0.185;-25150.0
9A(4J)
0.178;-26387.5
9A(4K)
0.210;-25150.0
4(TQA)
0.173;-25150.0
A(4TJ)
0.161;-25768.7
4TTA
0.181;-26387.5
4TQA
0.175;-29200.0
(4Q)(JA)
0.211;-20481.2
QA(4J)
0.151;-24531.2
4JQA
0.160;-28581.2
(4K)(QA)
0.172;-19243.8
QA(4K)
0.156;-23293.8
5(56A)
0.192;-27287.5
58(5A)
0.186;-26050.0
(5J)(5A)
0.259;-20143.7
6(56A)
0.181;-26668.8
T(56A)
0.213;-28243.8
6(57A)
0.131;-30100.0
69(5A)
0.127;-28862.5
(6Q)(5A)
0.176;-22956.2
(579A)
0.177;-28243.8
(57KA)
0.142;-25768.7
79(5A)
0.122;-28243.8
(7Q)(5A)
0.191;-22337.5
(58TA)
0.212;-27006.2
88(5A)
0.194;-24193.7
(8J)(5A)
0.225;-22337.5
9(59A)
0.149;-22956.2
K(59A)
0.148;-24531.2
9(5QA)
0.170;-25150.0
J(5TA)
0.171;-25150.0
TJ(5A)
0.190;-25150.0
(5JQA)
0.158;-23912.5
J(5KA)
0.174;-23293.8
(QK)(5A)
0.194;-18625.0
55(7A)
0.176;-26668.8
559A
0.120;-29481.2
5A(5Q)
0.180;-23575.0
(57)(6A)
0.177;-26050.0
5(6TA)
0.129;-28243.8
5Q(6A)
0.186;-27006.2
(56)(8A)
0.144;-25431.2
TA(56)
0.165;-28243.8
A(56K)
0.163;-26387.5
6A(58)
0.153;-29481.2
6A(5T)
0.154;-28243.8
6A(5Q)
0.171;-27006.2
57(7A)
0.155;-25431.2
(5T)(7A)
0.188;-23575.0
5(7KA)
0.162;-25768.7
A(579)
0.182;-28243.8
(57)(QA)
0.158;-22337.5
7A(58)
0.122;-28862.5
7A(5T)
0.152;-27625.0
7A(5Q)
0.165;-26387.5
58(8A)
0.152;-24193.7
(5J)(8A)
0.182;-22337.5
8A(58)
0.146;-24193.7
A(58J)
0.193;-26387.5
588A
0.130;-28243.8
58TA
0.161;-31056.2
58QA
0.147;-29818.7
(5T)(9A)
0.202;-22337.5
5(9KA)
0.189;-24531.2
A(59J)
0.218;-25768.7
599A
0.158;-27006.2
59JA
0.135;-29818.7
59KA
0.156;-28581.2
5Q(TA)
0.185;-24531.2
(5T)(QA)
0.148;-20481.2
TA(5J)
0.146;-25150.0
TA(5K)
0.195;-23912.5
5(JKA)
0.171;-23293.8
A(5JK)
0.234;-23293.8
JA(5K)
0.150;-23293.8
QA(5Q)
0.176;-19243.8
5QKA
0.135;-26725.0
67(6A)
0.190;-25431.2
(6T)(6A)
0.201;-19525.0
6(6KA)
0.151;-21718.7
(67TA)
0.158;-27006.2
77(6A)
0.173;-24812.5
(7T)(6A)
0.236;-22956.2
7(6KA)
0.176;-25150.0
(68JA)
0.188;-25768.7
(89)(6A)
0.161;-22956.2
8(6QA)
0.168;-25150.0
T(69A)
0.160;-25768.7
9(6TA)
0.222;-25768.7
9Q(6A)
0.179;-24531.2
Q(6TA)
0.199;-23912.5
(TQ)(6A)
0.216;-19862.5
(6JKA)
0.180;-22675.0
JK(6A)
0.171;-22675.0
K(6KA)
0.268;-17387.5
668A
0.119;-28862.5
6A(6J)
0.174;-22956.2
(67)(7A)
0.210;-20762.5
6(7TA)
0.147;-27006.2
6Q(7A)
0.153;-25768.7
(67)(9A)
0.177;-23575.0
JA(67)
0.196;-26387.5
67(8A)
0.122;-28243.8
67(TA)
0.145;-27006.2
67(QA)
0.125;-25768.7
(68)(8A)
0.214;-19525.0
6(8JA)
0.163;-25768.7
6K(8A)
0.218;-24531.2
(68)(JA)
0.203;-21718.7
KA(68)
0.163;-24531.2
6A(8T)
0.151;-26387.5
6A(8Q)
0.194;-25150.0
6(9TA)
0.185;-25768.7
6Q(9A)
0.148;-24531.2
(69)(JA)
0.194;-21100.0
KA(69)
0.156;-23912.5
6A(9J)
0.147;-25150.0
6A(9K)
0.192;-23912.5
(6Q)(TA)
0.167;-19862.5
JA(6T)
0.192;-24531.2
6T(JA)
0.192;-24531.2
6T(KA)
0.173;-23293.8
6Q(JA)
0.204;-23293.8
(6J)(KA)
0.208;-18625.0
6J(KA)
0.166;-22675.0
6K(QA)
0.174;-22056.2
6A(QK)
0.199;-22056.2
(78)(7A)
0.189;-19525.0
7(7JA)
0.160;-21718.7
7K(7A)
0.190;-20481.2
(78QA)
0.153;-24531.2
8(7TA)
0.173;-25768.7
8Q(7A)
0.163;-24531.2
J(79A)
0.214;-24531.2
9T(7A)
0.164;-25150.0
(9K)(7A)
0.195;-19243.8
K(7TA)
0.208;-22675.0
T(7KA)
0.205;-22675.0
JJ(7A)
0.248;-19243.8
(7QKA)
0.229;-21437.5
777A
0.135;-24193.8
7A(7T)
0.164;-22337.5
77(KA)
0.157;-20481.2
7(8TA)
0.152;-25768.7
7Q(8A)
0.167;-24531.2
(78)(TA)
0.207;-21718.7
QA(78)
0.143;-24531.2
789A
0.146;-30437.5
78JA
0.119;-29200.0
78KA
0.155;-27962.5
7J(9A)
0.175;-24531.2
(79)(TA)
0.228;-21100.0
QA(79)
0.180;-23912.5
79TA
0.136;-29200.0
79QA
0.132;-27962.5
(7J)(TA)
0.227;-19862.5
TA(7T)
0.211;-20481.2
A(7TK)
0.170;-22675.0
TA(7Q)
0.157;-23293.8
7J(JA)
0.168;-19243.8
(7J)(QA)
0.228;-18625.0
JA(7Q)
0.202;-22675.0
7Q(QA)
0.224;-18006.2
7QQA
0.204;-22056.2
7KKA
0.236;-20818.8
8(8JA)
0.214;-20481.2
8K(8A)
0.254;-19243.8
(89KA)
0.157;-22675.0
9J(8A)
0.166;-23912.5
(8TJA)
0.157;-23293.8
(TJ)(8A)
0.225;-19243.8
J(8JA)
0.273;-18625.0
JQ(8A)
0.166;-22056.2
Q(8KA)
0.195;-20818.8
889A
0.138;-25768.7
8A(8Q)
0.225;-19862.5
(8T)(9A)
0.219;-20481.2
8(9KA)
0.173;-22675.0
A(89J)
0.179;-23912.5
899A
0.155;-25150.0
89JA
0.185;-27962.5
89KA
0.207;-26725.0
8Q(TA)
0.174;-22675.0
(8T)(QA)
0.222;-18625.0
TA(8J)
0.193;-23293.8
TA(8K)
0.173;-22056.2
8(JKA)
0.196;-21437.5
A(8JK)
0.206;-21437.5
JA(8K)
0.169;-21437.5
QA(8Q)
0.224;-17387.5
8QKA
0.173;-24868.8
9T(9A)
0.209;-19862.5
(9K)(9A)
0.222;-13956.2
K(9TA)
0.211;-21437.5
T(9KA)
0.168;-21437.5
JJ(9A)
0.245;-18006.2
(9QKA)
0.216;-20200.0
999A
0.199;-20481.2
9A(9Q)
0.259;-18625.0
(9J)(TA)
0.188;-18625.0
TA(9T)
0.262;-19243.8
A(9TK)
0.212;-21437.5
TA(9Q)
0.201;-22056.2
9J(JA)
0.200;-18006.2
(9J)(QA)
0.230;-17387.5
JA(9Q)
0.164;-21437.5
9Q(QA)
0.207;-16768.8
9QQA
0.172;-20818.8
9KKA
0.205;-19581.2
T(TKA)
0.192;-16768.8
JJ(TA)
0.247;-17387.5
(TQKA)
0.236;-19581.2
TTTA
0.213;-18625.0
TA(TK)
0.266;-16768.8
(TK)(JA)
0.237;-16150.0
KA(TJ)
0.191;-20200.0
TA(JK)
0.196;-20200.0
(TQ)(KA)
0.208;-15531.3
(TK)(KA)
0.295;-10862.5
J(JKA)
0.226;-15531.3
(QK)(JA)
0.237;-14912.5
JJ(KA)
0.233;-15531.3
QA(JQ)
0.202;-15531.3
JQKA
0.185;-23012.5
QK(QA)
0.284;-14293.8
QK(KA)
0.247;-13675.0
22(24)
0.110;-35612.5
22(28)
0.112;-33137.5
22(2Q)
0.115;-30662.5
24(23)
0.087;-39043.8
(23)(27)
0.142;-33137.5
2(23T)
0.129;-35331.2
2Q(23)
0.163;-34093.8
23(25)
0.093;-38425.0
2237
0.084;-41237.5
22(3T)
0.109;-35331.2
23(2K)
0.111;-33475.0
2(246)
0.149;-37187.5
28(24)
0.106;-35950.0
(24)(2J)
0.159;-30043.7
2244
0.102;-38425.0
22(47)
0.120;-36568.8
24(2T)
0.142;-34712.5
224Q
0.087;-37525.0
26(25)
0.124;-36568.8
(25)(29)
0.153;-30662.5
2(25Q)
0.129;-32856.2
22(56)
0.125;-36568.8
25(29)
0.113;-34712.5
225J
0.136;-37525.0
26(26)
0.163;-31900.0
(26)(29)
0.171;-30043.7
2(26Q)
0.173;-32237.5
22(67)
0.121;-35331.2
26(2T)
0.134;-33475.0
226Q
0.114;-36287.5
28(27)
0.140;-34093.8
(27)(2J)
0.203;-28187.5
2277
0.130;-34712.5
22(7T)
0.153;-32856.2
27(2K)
0.124;-31000.0
2(28T)
0.181;-32237.5
2Q(28)
0.139;-31000.0
28(2T)
0.122;-32237.5
228Q
0.136;-35050.0
2T(29)
0.123;-31618.8
(29)(2K)
0.166;-25712.5
229J
0.127;-35050.0
2T(2T)
0.198;-26950.0
(2T)(2K)
0.146;-25093.7
22TQ
0.115;-33812.5
2Q(2J)
0.185;-29143.7
2J(2K)
0.163;-28525.0
22QQ
0.135;-28525.0
3(234)
0.132;-38425.0
36(23)
0.133;-37187.5
(23)(39)
0.138;-31281.2
3(23Q)
0.134;-33475.0
5(234)
0.092;-41237.5
9(234)
0.120;-38762.5
K(234)
0.132;-36287.5
4(237)
0.110;-40000.0
49(23)
0.133;-38762.5
(23)(4Q)
0.154;-32856.2
(2357)
0.118;-39381.2
(235J)
0.094;-36906.2
(23)(56)
0.111;-35950.0
5(239)
0.102;-38143.8
5J(23)
0.147;-36906.2
(2367)
0.139;-38762.5
(236J)
0.139;-36287.5
(23)(67)
0.100;-34712.5
6(23T)
0.115;-36906.2
6Q(23)
0.146;-35668.8
9(237)
0.093;-36906.2
K(237)
0.122;-34431.2
7(23T)
0.137;-36287.5
7Q(23)
0.099;-35050.0
T(238)
0.160;-35668.8
8(239)
0.114;-36287.5
8J(23)
0.115;-35050.0
(239T)
0.123;-35050.0
99(23)
0.157;-31618.8
(23)(9Q)
0.144;-29762.5
(23TQ)
0.162;-33193.8
T(23Q)
0.106;-33193.8
Q(23J)
0.125;-32575.0
(23)(JK)
0.202;-27906.2
QK(23)
0.119;-31337.5
23(35)
0.147;-37806.2
33(28)
0.141;-35950.0
233T
0.130;-38762.5
23(3K)
0.103;-32856.2
(24)(36)
0.099;-36568.8
3(249)
0.083;-38762.5
3J(24)
0.130;-37525.0
(34)(25)
0.127;-37187.5
27(34)
0.110;-40000.0
2(34T)
0.098;-38143.8
(34)(2K)
0.102;-32237.5
34(26)
0.099;-40618.8
34(28)
0.120;-39381.2
34(2T)
0.106;-38143.8
34(2Q)
0.095;-36906.2
(25)(35)
0.159;-32518.8
3(258)
0.107;-38762.5
3T(25)
0.131;-37525.0
(25)(3K)
0.120;-31618.8
27(35)
0.119;-39381.2
2(35T)
0.131;-37525.0
(35)(2K)
0.147;-31618.8
35(27)
0.102;-39381.2
35(29)
0.095;-38143.8
35(2J)
0.134;-36906.2
35(2K)
0.165;-35668.8
37(26)
0.098;-38762.5
(26)(3T)
0.121;-32856.2
3(26K)
0.134;-35050.0
2(368)
0.094;-38143.8
(36)(2J)
0.150;-32237.5
2K(36)
0.103;-35050.0
23(68)
0.139;-38143.8
23(6T)
0.091;-36906.2
23(6Q)
0.101;-35668.8
3(278)
0.086;-37525.0
3T(27)
0.129;-36287.5
(27)(3K)
0.186;-30381.2
29(37)
0.105;-36906.2
2(37Q)
0.122;-35050.0
23(78)
0.121;-37525.0
23(7T)
0.130;-36287.5
23(7Q)
0.136;-35050.0
3(289)
0.163;-36287.5
3J(28)
0.158;-35050.0
(38)(29)
0.142;-32237.5
2J(38)
0.124;-35050.0
38(29)
0.138;-36287.5
38(2J)
0.118;-35050.0
38(2K)
0.130;-33812.5
3T(29)
0.124;-35050.0
(29)(3K)
0.160;-29143.8
2J(39)
0.119;-34431.2
39(2T)
0.090;-35050.0
39(2Q)
0.166;-33812.5
(2T)(3T)
0.138;-26331.2
3(2TK)
0.126;-32575.0
2(3TQ)
0.144;-33193.8
23(TJ)
0.156;-33812.5
23(TK)
0.122;-32575.0
(2J)(3K)
0.204;-27906.2
2K(3J)
0.184;-31956.2
23(JK)
0.140;-31956.2
(3Q)(2K)
0.144;-27287.5
(2K)(3K)
0.206;-22618.8
4(246)
0.119;-35950.0
48(24)
0.112;-34712.5
(24)(4J)
0.177;-28806.3
5(245)
0.110;-35950.0
9(245)
0.136;-37525.0
K(245)
0.128;-35050.0
5(248)
0.112;-38143.8
5T(24)
0.142;-36906.2
(24)(5K)
0.150;-31000.0
9(246)
0.149;-36906.2
K(246)
0.094;-34431.2
6(249)
0.111;-36906.2
6J(24)
0.096;-35668.8
(2478)
0.118;-36906.2
(247Q)
0.149;-34431.2
7(249)
0.129;-36287.5
7J(24)
0.110;-35050.0
(2489)
0.111;-35668.8
(248K)
0.163;-33193.8
8T(24)
0.149;-35050.0
(24)(8K)
0.120;-29143.8
Q(249)
0.138;-33193.8
(24)(9J)
0.123;-29762.5
T(24T)
0.151;-29762.5
T(24J)
0.161;-33193.8
TK(24)
0.123;-31956.2
(24)(JQ)
0.167;-27906.2
QQ(24)
0.158;-27287.5
24(45)
0.127;-36568.8
44(28)
0.117;-34712.5
244T
0.116;-37525.0
24(4K)
0.169;-31618.8
(25)(47)
0.152;-34712.5
4(25T)
0.110;-36906.2
4Q(25)
0.111;-35668.8
(45)(27)
0.171;-34712.5
29(45)
0.123;-37525.0
2(45Q)
0.129;-35668.8
24(56)
0.099;-39381.2
24(58)
0.096;-38143.8
24(5T)
0.141;-36906.2
24(5Q)
0.160;-35668.8
4(267)
0.113;-38143.8
49(26)
0.141;-36906.2
(26)(4Q)
0.126;-31000.0
27(46)
0.102;-38143.8
2(46T)
0.106;-36287.5
(46)(2K)
0.127;-30381.2
46(28)
0.138;-37525.0
46(2T)
0.098;-36287.5
46(2Q)
0.111;-35050.0
(27)(47)
0.155;-29425.0
4(27T)
0.102;-35668.8
4Q(27)
0.120;-34431.2
(47)(29)
0.151;-32237.5
2J(47)
0.108;-35050.0
47(28)
0.107;-36906.2
47(2T)
0.116;-35668.8
47(2Q)
0.130;-34431.2
(28)(48)
0.177;-28187.5
4(28J)
0.106;-34431.2
4K(28)
0.124;-33193.8
(48)(2J)
0.147;-30381.2
2K(48)
0.103;-33193.8
24(8T)
0.102;-35050.0
24(8Q)
0.138;-33812.5
4(29T)
0.095;-34431.2
4Q(29)
0.122;-33193.8
(49)(2J)
0.129;-29762.5
2K(49)
0.171;-32575.0
24(9J)
0.136;-33812.5
24(9K)
0.179;-32575.0
(2T)(4Q)
0.172;-28525.0
2J(4T)
0.123;-33193.8
4T(2J)
0.160;-33193.8
4T(2K)
0.129;-31956.2
4Q(2J)
0.147;-31956.2
(4J)(2K)
0.155;-27287.5
4J(2K)
0.107;-31337.5
4K(2Q)
0.153;-30718.8
24(QK)
0.183;-30718.8
(25)(56)
0.146;-30662.5
5(259)
0.157;-32856.2
5J(25)
0.122;-31618.8
(2567)
0.105;-37525.0
(256J)
0.130;-35050.0
(25)(67)
0.143;-33475.0
6(25T)
0.120;-35668.8
6Q(25)
0.146;-34431.2
9(257)
0.129;-35668.8
K(257)
0.122;-33193.8
7(25T)
0.118;-35050.0
7Q(25)
0.147;-33812.5
T(258)
0.108;-34431.2
8(259)
0.110;-35050.0
8J(25)
0.144;-33812.5
(259T)
0.122;-33812.5
99(25)
0.163;-30381.2
(25)(9Q)
0.178;-28525.0
(25TQ)
0.171;-31956.2
T(25Q)
0.127;-31956.2
Q(25J)
0.169;-31337.5
(25)(JK)
0.149;-26668.8
QK(25)
0.118;-30100.0
25(57)
0.138;-34093.8
55(2T)
0.108;-32237.5
255Q
0.135;-35050.0
57(26)
0.105;-37525.0
(26)(5T)
0.146;-31618.8
5(26K)
0.129;-33812.5
2(568)
0.129;-36906.2
(56)(2J)
0.108;-31000.0
2K(56)
0.104;-33812.5
25(68)
0.122;-36906.2
25(6T)
0.118;-35668.8
25(6Q)
0.125;-34431.2
5(278)
0.133;-36287.5
5T(27)
0.120;-35050.0
(27)(5K)
0.149;-29143.8
29(57)
0.114;-35668.8
2(57Q)
0.165;-33812.5
25(78)
0.106;-36287.5
25(7T)
0.112;-35050.0
25(7Q)
0.100;-33812.5
5(289)
0.124;-35050.0
5J(28)
0.147;-33812.5
(58)(29)
0.135;-31000.0
2J(58)
0.113;-33812.5
58(29)
0.132;-35050.0
58(2J)
0.116;-33812.5
58(2K)
0.110;-32575.0
5T(29)
0.160;-33812.5
(29)(5K)
0.161;-27906.2
2J(59)
0.176;-33193.8
59(2T)
0.121;-33812.5
59(2Q)
0.116;-32575.0
(2T)(5T)
0.129;-25093.7
5(2TK)
0.101;-31337.5
2(5TQ)
0.173;-31956.2
25(TJ)
0.163;-32575.0
25(TK)
0.143;-31337.5
(2J)(5K)
0.146;-26668.8
2K(5J)
0.150;-30718.8
25(JK)
0.152;-30718.8
(5Q)(2K)
0.199;-26050.0
(2K)(5K)
0.215;-21381.2
6(268)
0.129;-32237.5
6T(26)
0.172;-31000.0
(26)(6K)
0.166;-25093.7
T(267)
0.130;-34431.2
7(268)
0.115;-35668.8
7T(26)
0.119;-34431.2
(26)(7K)
0.140;-28525.0
J(268)
0.119;-33193.8
89(26)
0.118;-34431.2
(26)(8Q)
0.154;-28525.0
(269J)
0.125;-32575.0
(26)(9T)
0.159;-29143.8
9(26K)
0.111;-31337.5
(26TK)
0.147;-30718.8
TQ(26)
0.140;-31337.5
K(26J)
0.134;-30100.0
Q(26Q)
0.148;-26050.0
KK(26)
0.211;-24812.5
66(29)
0.141;-31618.8
266J
0.099;-34431.2
67(27)
0.117;-32237.5
(27)(6T)
0.140;-30381.2
6(27K)
0.145;-32575.0
2(679)
0.118;-35050.0
(67)(2Q)
0.149;-29143.8
27(68)
0.111;-35668.8
27(6T)
0.166;-34431.2
27(6Q)
0.162;-33193.8
68(28)
0.145;-31000.0
(28)(6J)
0.156;-29143.8
28(68)
0.148;-31000.0
2(68J)
0.139;-33193.8
2688
0.123;-35050.0
268T
0.089;-37862.5
268Q
0.128;-36625.0
(29)(6T)
0.148;-29143.8
6(29K)
0.156;-31337.5
2(69J)
0.135;-32575.0
2699
0.160;-33812.5
269J
0.148;-36625.0
269K
0.115;-35387.5
6Q(2T)
0.159;-31337.5
(6T)(2Q)
0.141;-27287.5
2T(6J)
0.149;-31956.2
2T(6K)
0.141;-30718.8
6(2JK)
0.125;-30100.0
2(6JK)
0.131;-30100.0
2J(6K)
0.151;-30100.0
2Q(6Q)
0.125;-26050.0
26QK
0.125;-33531.2
78(27)
0.119;-31000.0
(27)(7J)
0.140;-25093.7
8(278)
0.164;-30381.2
Q(278)
0.150;-31956.2
(27)(8T)
0.177;-29143.8
8(27K)
0.179;-31337.5
(279Q)
0.114;-31337.5
9(27J)
0.108;-31956.2
9K(27)
0.132;-30718.8
TT(27)
0.150;-27906.2
(27)(TK)
0.223;-26050.0
J(27Q)
0.149;-30100.0
K(27Q)
0.121;-28862.5
77(28)
0.115;-31000.0
277T
0.137;-33812.5
27(7K)
0.130;-27906.2
(28)(7T)
0.142;-29143.8
7(28K)
0.146;-31337.5
2(78T)
0.144;-33193.8
(78)(2K)
0.129;-27287.5
78(2T)
0.109;-33193.8
78(2Q)
0.161;-31956.2
(29)(79)
0.179;-25093.7
7(29Q)
0.124;-31337.5
2(79T)
0.125;-32575.0
(79)(2K)
0.179;-26668.8
79(2J)
0.107;-31956.2
79(2K)
0.144;-30718.8
7J(2T)
0.177;-31337.5
(7T)(2J)
0.172;-27287.5
2K(7T)
0.140;-30100.0
27(TQ)
0.165;-30718.8
7(2JQ)
0.168;-30100.0
2(7JQ)
0.174;-30100.0
27(JQ)
0.140;-30100.0
7(2QK)
0.138;-28862.5
7Q(2K)
0.123;-28862.5
88(28)
0.134;-25712.5
(28)(8J)
0.137;-23856.2
9(289)
0.144;-28525.0
K(289)
0.136;-30100.0
9(28Q)
0.134;-30718.8
J(28T)
0.153;-30718.8
TJ(28)
0.149;-30718.8
(28JQ)
0.183;-29481.2
J(28K)
0.137;-28862.5
(28)(QK)
0.178;-24193.8
88(2T)
0.177;-28525.0
288Q
0.130;-31337.5
8T(29)
0.151;-31956.2
(29)(8K)
0.213;-26050.0
2J(89)
0.132;-31337.5
89(2T)
0.119;-31956.2
89(2Q)
0.170;-30718.8
(2T)(8T)
0.175;-23237.5
8(2TK)
0.150;-29481.2
2(8TQ)
0.145;-30100.0
28(TJ)
0.118;-30718.8
28(TK)
0.156;-29481.2
(2J)(8K)
0.128;-24812.5
2K(8J)
0.131;-28862.5
28(JK)
0.127;-28862.5
(8Q)(2K)
0.204;-24193.8
(2K)(8K)
0.175;-19525.0
9(29J)
0.164;-26668.8
9K(29)
0.182;-25431.2
TT(29)
0.179;-26668.8
(29)(TK)
0.173;-24812.5
J(29Q)
0.168;-28862.5
K(29Q)
0.156;-27625.0
99(2T)
0.171;-27287.5
299Q
0.143;-30100.0
9J(2T)
0.148;-30100.0
(9T)(2J)
0.149;-26050.0
2K(9T)
0.161;-28862.5
29(TQ)
0.147;-29481.2
9(2JQ)
0.156;-28862.5
2(9JQ)
0.145;-28862.5
29(JQ)
0.204;-28862.5
9(2QK)
0.158;-27625.0
9Q(2K)
0.173;-27625.0
TT(2T)
0.178;-22000.0
(2T)(TK)
0.223;-20143.7
J(2TQ)
0.189;-28243.8
K(2TQ)
0.163;-27006.2
TT(2J)
0.141;-25431.2
2TTK
0.143;-28243.8
TK(2J)
0.155;-27625.0
2TJJ
0.133;-28862.5
2TJK
0.134;-31675.0
2(TQK)
0.169;-27006.2
TK(2K)
0.189;-22337.5
(2J)(JK)
0.249;-18906.3
QK(2J)
0.170;-26387.5
2J(JK)
0.177;-22956.2
(JQ)(2K)
0.183;-22337.5
(2K)(JK)
0.276;-17668.7
K(2QK)
0.162;-21100.0
2K(QK)
0.230;-21100.0
3335
0.132;-37187.5
3339
0.136;-34712.5
333K
0.139;-32237.5
36(34)
0.110;-35950.0
(34)(39)
0.145;-30043.7
3(34Q)
0.118;-32237.5
33(45)
0.119;-36568.8
34(38)
0.116;-34712.5
334T
0.138;-37525.0
33(4K)
0.158;-31618.8
(35)(37)
0.155;-30662.5
3(35T)
0.160;-32856.2
3Q(35)
0.152;-31618.8
35(37)
0.126;-34712.5
3359
0.101;-37525.0
33(5Q)
0.159;-31618.8
(36)(37)
0.138;-30043.7
3(36T)
0.097;-32237.5
3Q(36)
0.156;-31000.0
36(38)
0.145;-33475.0
336T
0.118;-36287.5
33(6K)
0.183;-30381.2
(37)(39)
0.129;-28187.5
3(37Q)
0.133;-30381.2
33(78)
0.152;-32856.2
37(3J)
0.124;-31000.0
337K
0.138;-33812.5
3T(38)
0.155;-31000.0
(38)(3K)
0.142;-25093.7
338T
0.144;-35050.0
33(8K)
0.184;-29143.7
(39)(3J)
0.171;-25712.5
3399
0.141;-31000.0
33(9Q)
0.131;-29143.7
(3T)(3J)
0.179;-25093.7
33TT
0.131;-29762.5
33(TK)
0.186;-27906.2
(3J)(3K)
0.134;-23237.5
33JK
0.159;-31337.5
33(QK)
0.145;-26668.8
45(34)
0.111;-35950.0
(34)(48)
0.172;-30043.7
4(34J)
0.121;-32237.5
4K(34)
0.134;-31000.0
(3459)
0.118;-36906.2
(345K)
0.131;-34431.2
57(34)
0.121;-38143.8
(34)(5T)
0.150;-32237.5
5(34K)
0.113;-34431.2
(3469)
0.107;-36287.5
(346K)
0.120;-33812.5
68(34)
0.111;-36906.2
(34)(6J)
0.131;-31000.0
7(347)
0.129;-32856.2
J(347)
0.135;-34431.2
78(34)
0.109;-36287.5
(34)(7J)
0.147;-30381.2
8(348)
0.102;-31618.8
Q(348)
0.108;-33193.8
(34)(8T)
0.140;-30381.2
8(34K)
0.125;-32575.0
(349Q)
0.168;-32575.0
9(34J)
0.129;-33193.8
9K(34)
0.156;-31956.2
TT(34)
0.146;-29143.7
(34)(TK)
0.130;-27287.5
J(34Q)
0.134;-31337.5
K(34Q)
0.141;-30100.0
44(35)
0.115;-35950.0
3447
0.124;-38762.5
34(4T)
0.173;-32856.2
44(3K)
0.178;-31000.0
4(357)
0.103;-38143.8
49(35)
0.111;-36906.2
(35)(4Q)
0.139;-31000.0
36(45)
0.111;-38762.5
3(459)
0.131;-36906.2
(45)(3Q)
0.138;-31000.0
35(46)
0.113;-38762.5
35(48)
0.126;-37525.0
35(4T)
0.116;-36287.5
35(4Q)
0.113;-35050.0
46(36)
0.143;-34093.8
(36)(49)
0.132;-32237.5
4(36Q)
0.169;-34431.2
3(467)
0.119;-37525.0
(46)(3T)
0.163;-31618.8
3Q(46)
0.139;-34431.2
3467
0.108;-41575.0
3469
0.098;-40337.5
346J
0.094;-39100.0
346K
0.117;-37862.5
49(37)
0.170;-35668.8
(37)(4Q)
0.156;-29762.5
38(47)
0.127;-36287.5
3(47J)
0.124;-34431.2
3477
0.123;-36906.2
3479
0.101;-39718.8
347J
0.103;-38481.2
347K
0.092;-37243.8
4T(38)
0.111;-34431.2
(38)(4K)
0.154;-28525.0
3T(48)
0.154;-34431.2
3(48K)
0.160;-32575.0
38(4T)
0.096;-34431.2
38(4Q)
0.145;-33193.8
49(39)
0.155;-30381.2
(39)(4Q)
0.120;-28525.0
3T(49)
0.116;-33812.5
3(49K)
0.108;-31956.2
39(4J)
0.152;-33193.8
39(4K)
0.167;-31956.2
4(3TQ)
0.101;-31956.2
3(4TJ)
0.156;-32575.0
34TT
0.135;-33193.8
34TQ
0.119;-36006.2
(3J)(4Q)
0.180;-27287.5
3Q(4J)
0.154;-31337.5
34JQ
0.115;-35387.5
(3Q)(4K)
0.190;-26050.0
3Q(4K)
0.160;-30100.0
5(356)
0.128;-34093.8
58(35)
0.124;-32856.2
(35)(5J)
0.166;-26950.0
6(356)
0.128;-33475.0
T(356)
0.103;-35050.0
6(357)
0.098;-36906.2
69(35)
0.121;-35668.8
(35)(6Q)
0.121;-29762.5
(3579)
0.141;-35050.0
(357K)
0.147;-32575.0
79(35)
0.149;-35050.0
(35)(7Q)
0.192;-29143.8
(358T)
0.152;-33812.5
88(35)
0.123;-31000.0
(35)(8J)
0.126;-29143.8
9(359)
0.111;-29762.5
K(359)
0.133;-31337.5
9(35Q)
0.117;-31956.2
J(35T)
0.140;-31956.2
TJ(35)
0.111;-31956.2
(35JQ)
0.189;-30718.8
J(35K)
0.124;-30100.0
(35)(QK)
0.159;-25431.2
55(37)
0.163;-33475.0
3559
0.147;-36287.5
35(5Q)
0.150;-30381.2
(36)(57)
0.105;-32856.2
5(36T)
0.093;-35050.0
5Q(36)
0.136;-33812.5
(56)(38)
0.157;-32237.5
3T(56)
0.131;-35050.0
3(56K)
0.103;-33193.8
36(58)
0.097;-36287.5
36(5T)
0.116;-35050.0
36(5Q)
0.122;-33812.5
57(37)
0.143;-32237.5
(37)(5T)
0.136;-30381.2
5(37K)
0.114;-32575.0
3(579)
0.134;-35050.0
(57)(3Q)
0.125;-29143.8
37(58)
0.145;-35668.8
37(5T)
0.141;-34431.2
37(5Q)
0.111;-33193.8
58(38)
0.129;-31000.0
(38)(5J)
0.155;-29143.8
38(58)
0.162;-31000.0
3(58J)
0.127;-33193.8
3588
0.140;-35050.0
358T
0.124;-37862.5
358Q
0.124;-36625.0
(39)(5T)
0.178;-29143.8
5(39K)
0.158;-31337.5
3(59J)
0.140;-32575.0
3599
0.121;-33812.5
359J
0.109;-36625.0
359K
0.127;-35387.5
5Q(3T)
0.157;-31337.5
(5T)(3Q)
0.162;-27287.5
3T(5J)
0.139;-31956.2
3T(5K)
0.122;-30718.8
5(3JK)
0.137;-30100.0
3(5JK)
0.146;-30100.0
3J(5K)
0.177;-30100.0
3Q(5Q)
0.154;-26050.0
35QK
0.121;-33531.2
67(36)
0.120;-32237.5
(36)(6T)
0.152;-26331.2
6(36K)
0.149;-28525.0
(367T)
0.130;-33812.5
77(36)
0.150;-31618.8
(36)(7T)
0.142;-29762.5
7(36K)
0.136;-31956.2
(368J)
0.168;-32575.0
(36)(89)
0.166;-29762.5
8(36Q)
0.177;-31956.2
T(369)
0.150;-32575.0
9(36T)
0.141;-32575.0
9Q(36)
0.166;-31337.5
Q(36T)
0.171;-30718.8
(36)(TQ)
0.150;-26668.8
(36JK)
0.155;-29481.2
JK(36)
0.160;-29481.2
K(36K)
0.157;-24193.7
3668
0.118;-35668.8
36(6J)
0.131;-29762.5
(37)(67)
0.138;-27568.8
6(37T)
0.114;-33812.5
6Q(37)
0.178;-32575.0
(67)(39)
0.116;-30381.2
3J(67)
0.100;-33193.8
67(38)
0.126;-35050.0
67(3T)
0.139;-33812.5
67(3Q)
0.106;-32575.0
(38)(68)
0.217;-26331.2
6(38J)
0.112;-32575.0
6K(38)
0.147;-31337.5
(68)(3J)
0.195;-28525.0
3K(68)
0.119;-31337.5
36(8T)
0.178;-33193.8
36(8Q)
0.100;-31956.2
6(39T)
0.114;-32575.0
6Q(39)
0.117;-31337.5
(69)(3J)
0.144;-27906.2
3K(69)
0.128;-30718.8
36(9J)
0.111;-31956.2
36(9K)
0.115;-30718.8
(3T)(6Q)
0.148;-26668.8
3J(6T)
0.149;-31337.5
6T(3J)
0.144;-31337.5
6T(3K)
0.128;-30100.0
6Q(3J)
0.144;-30100.0
(6J)(3K)
0.147;-25431.2
6J(3K)
0.171;-29481.2
6K(3Q)
0.157;-28862.5
36(QK)
0.153;-28862.5
(37)(78)
0.168;-26331.2
7(37J)
0.155;-28525.0
7K(37)
0.135;-27287.5
(378Q)
0.142;-31337.5
8(37T)
0.134;-32575.0
8Q(37)
0.163;-31337.5
J(379)
0.150;-31337.5
9T(37)
0.130;-31956.2
(37)(9K)
0.167;-26050.0
K(37T)
0.199;-29481.2
T(37K)
0.131;-29481.2
JJ(37)
0.179;-26050.0
(37QK)
0.164;-28243.8
3777
0.141;-31000.0
37(7T)
0.134;-29143.7
77(3K)
0.169;-27287.5
7(38T)
0.103;-32575.0
7Q(38)
0.161;-31337.5
(78)(3T)
0.151;-28525.0
3Q(78)
0.137;-31337.5
3789
0.145;-37243.8
378J
0.145;-36006.2
378K
0.126;-34768.8
7J(39)
0.125;-31337.5
(79)(3T)
0.157;-27906.2
3Q(79)
0.128;-30718.8
379T
0.127;-36006.2
379Q
0.099;-34768.8
(3T)(7J)
0.146;-26668.8
3T(7T)
0.149;-27287.5
3(7TK)
0.159;-29481.2
3T(7Q)
0.150;-30100.0
7J(3J)
0.157;-26050.0
(7J)(3Q)
0.172;-25431.2
3J(7Q)
0.154;-29481.2
7Q(3Q)
0.189;-24812.5
37QQ
0.200;-28862.5
37KK
0.135;-27625.0
8(38J)
0.192;-27287.5
8K(38)
0.178;-26050.0
(389K)
0.118;-29481.2
9J(38)
0.145;-30718.8
(38TJ)
0.150;-30100.0
(38)(TJ)
0.165;-26050.0
J(38J)
0.148;-25431.2
JQ(38)
0.139;-28862.5
Q(38K)
0.171;-27625.0
3889
0.139;-32575.0
38(8Q)
0.198;-26668.8
(39)(8T)
0.132;-27287.5
8(39K)
0.132;-29481.2
3(89J)
0.146;-30718.8
3899
0.125;-31956.2
389J
0.101;-34768.8
389K
0.145;-33531.2
8Q(3T)
0.133;-29481.2
(8T)(3Q)
0.160;-25431.2
3T(8J)
0.127;-30100.0
3T(8K)
0.145;-28862.5
8(3JK)
0.122;-28243.8
3(8JK)
0.157;-28243.8
3J(8K)
0.164;-28243.8
3Q(8Q)
0.161;-24193.7
38QK
0.155;-31675.0
9T(39)
0.173;-26668.8
(39)(9K)
0.219;-20762.5
K(39T)
0.149;-28243.8
T(39K)
0.192;-28243.8
JJ(39)
0.184;-24812.5
(39QK)
0.154;-27006.2
3999
0.150;-27287.5
39(9Q)
0.179;-25431.2
(3T)(9J)
0.162;-25431.2
3T(9T)
0.183;-26050.0
3(9TK)
0.137;-28243.8
3T(9Q)
0.121;-28862.5
9J(3J)
0.172;-24812.5
(9J)(3Q)
0.202;-24193.8
3J(9Q)
0.136;-28243.8
9Q(3Q)
0.213;-23575.0
39QQ
0.203;-27625.0
39KK
0.158;-26387.5
T(3TK)
0.184;-23575.0
JJ(3T)
0.174;-24193.7
(3TQK)
0.135;-26387.5
3TTT
0.199;-25431.2
3T(TK)
0.153;-23575.0
(3J)(TK)
0.191;-22956.2
3K(TJ)
0.193;-27006.2
3T(JK)
0.155;-27006.2
(TQ)(3K)
0.182;-22337.5
(3K)(TK)
0.174;-17668.7
J(3JK)
0.158;-22337.5
(3J)(QK)
0.217;-21718.7
JJ(3K)
0.206;-22337.5
3Q(JQ)
0.145;-22337.5
3JQK
0.135;-29818.7
QK(3Q)
0.160;-21100.0
QK(3K)
0.191;-20481.2
44(46)
0.122;-30662.5
44(4T)
0.178;-28187.5
(45)(45)
0.189;-26612.5
4(458)
0.146;-32856.2
4T(45)
0.124;-31618.8
(45)(4K)
0.155;-25712.5
4457
0.125;-37525.0
44(5T)
0.136;-31618.8
45(4K)
0.133;-29762.5
4(468)
0.149;-32237.5
4T(46)
0.147;-31000.0
(46)(4K)
0.192;-25093.7
4468
0.088;-36287.5
44(6J)
0.141;-30381.2
(47)(47)
0.174;-24137.5
4(47T)
0.116;-30381.2
4Q(47)
0.176;-29143.7
47(49)
0.164;-31000.0
447J
0.133;-33812.5
48(48)
0.195;-26950.0
(48)(4J)
0.127;-25093.7
4488
0.108;-31000.0
44(8J)
0.170;-29143.7
(49)(49)
0.204;-21662.5
4(49Q)
0.127;-27906.2
44(9T)
0.193;-29143.7
49(4K)
0.165;-27287.5
4(4TQ)
0.169;-27287.5
44(TJ)
0.170;-27906.2
(4J)(4J)
0.224;-19187.5
44JJ
0.150;-27287.5
4Q(4Q)
0.201;-22000.0
(4K)(4K)
0.210;-16712.5
(45)(57)
0.130;-28806.3
5(45T)
0.160;-31000.0
5Q(45)
0.160;-29762.5
8(456)
0.142;-35668.8
Q(456)
0.129;-33193.8
(45)(68)
0.147;-31618.8
6(45J)
0.160;-33812.5
6K(45)
0.154;-32575.0
(457J)
0.115;-33193.8
(45)(78)
0.141;-31000.0
7(45J)
0.138;-33193.8
7K(45)
0.110;-31956.2
(458Q)
0.184;-31956.2
8(45T)
0.129;-33193.8
8Q(45)
0.190;-31956.2
J(459)
0.120;-31956.2
9T(45)
0.150;-32575.0
(45)(9K)
0.131;-26668.8
K(45T)
0.142;-30100.0
T(45K)
0.141;-30100.0
JJ(45)
0.197;-26668.8
(45QK)
0.142;-28862.5
4555
0.112;-34093.8
45(58)
0.144;-32237.5
55(4J)
0.133;-30381.2
455K
0.113;-33193.8
58(46)
0.145;-35668.8
(46)(5J)
0.114;-29762.5
46(56)
0.122;-32856.2
4(569)
0.136;-35050.0
(56)(4Q)
0.179;-29143.8
46(57)
0.126;-36287.5
46(59)
0.103;-35050.0
46(5J)
0.156;-33812.5
46(5K)
0.164;-32575.0
5(479)
0.118;-34431.2
5J(47)
0.105;-33193.8
(57)(48)
0.177;-31000.0
4T(57)
0.116;-33812.5
4(57K)
0.159;-31956.2
47(59)
0.153;-34431.2
47(5J)
0.135;-33193.8
47(5K)
0.139;-31956.2
5(48T)
0.133;-33193.8
5Q(48)
0.140;-31956.2
(58)(4T)
0.136;-29143.8
4Q(58)
0.132;-31956.2
4589
0.151;-37862.5
458J
0.143;-36625.0
458K
0.117;-35387.5
5J(49)
0.174;-31956.2
(59)(4T)
0.135;-28525.0
4Q(59)
0.147;-31337.5
459T
0.101;-36625.0
459Q
0.104;-35387.5
(4T)(5J)
0.151;-27287.5
4T(5T)
0.168;-27906.2
4(5TK)
0.147;-30100.0
4T(5Q)
0.152;-30718.8
5J(4J)
0.144;-26668.8
(5J)(4Q)
0.157;-26050.0
4J(5Q)
0.159;-30100.0
5Q(4Q)
0.153;-25431.2
45QQ
0.147;-29481.2
45KK
0.152;-28243.8
6(469)
0.146;-30381.2
6J(46)
0.157;-29143.7
(4678)
0.137;-34431.2
(467Q)
0.146;-31956.2
7(469)
0.146;-33812.5
7J(46)
0.128;-32575.0
(4689)
0.179;-33193.8
(468K)
0.162;-30718.8
8T(46)
0.147;-32575.0
(46)(8K)
0.202;-26668.8
Q(469)
0.140;-30718.8
(46)(9J)
0.137;-27287.5
T(46T)
0.171;-27287.5
T(46J)
0.116;-30718.8
TK(46)
0.128;-29481.2
(46)(JQ)
0.163;-25431.2
QQ(46)
0.180;-24812.5
46(67)
0.110;-31618.8
66(4T)
0.197;-29762.5
466Q
0.158;-32575.0
68(47)
0.092;-34431.2
(47)(6J)
0.134;-28525.0
47(67)
0.138;-31000.0
4(67T)
0.151;-33193.8
(67)(4K)
0.166;-27287.5
67(49)
0.162;-33812.5
67(4J)
0.123;-32575.0
67(4K)
0.133;-31337.5
69(48)
0.128;-33193.8
(48)(6Q)
0.210;-27287.5
49(68)
0.139;-33193.8
4(68Q)
0.124;-31337.5
46(89)
0.123;-33193.8
46(8J)
0.173;-31956.2
46(8K)
0.167;-30718.8
(49)(6J)
0.131;-27287.5
49(69)
0.128;-28525.0
4(69Q)
0.144;-30718.8
46(9T)
0.158;-31956.2
46(9Q)
0.183;-30718.8
6(4TJ)
0.167;-30718.8
6K(4T)
0.154;-29481.2
(6T)(4K)
0.222;-25431.2
6T(4Q)
0.126;-30100.0
(4J)(6J)
0.197;-22000.0
4J(6J)
0.146;-26050.0
6J(4Q)
0.149;-29481.2
(4Q)(6Q)
0.178;-20762.5
4K(6Q)
0.163;-28243.8
4K(6K)
0.169;-23575.0
79(47)
0.143;-29143.7
(47)(7Q)
0.229;-23237.5
(478T)
0.137;-31956.2
88(47)
0.158;-29143.7
(47)(8J)
0.157;-27287.5
9(479)
0.169;-27906.2
K(479)
0.158;-29481.2
9(47Q)
0.174;-30100.0
J(47T)
0.170;-30100.0
TJ(47)
0.154;-30100.0
(47JQ)
0.167;-28862.5
J(47K)
0.158;-28243.8
(47)(QK)
0.178;-23575.0
77(49)
0.136;-29143.7
477J
0.158;-31956.2
78(48)
0.132;-29143.7
(48)(7J)
0.185;-27287.5
48(78)
0.132;-29143.7
4(78J)
0.116;-31337.5
4788
0.131;-33193.8
478T
0.153;-36006.2
478Q
0.166;-34768.8
(49)(7T)
0.217;-27287.5
7(49K)
0.136;-29481.2
4(79J)
0.178;-30718.8
4799
0.121;-31956.2
479J
0.117;-34768.8
479K
0.124;-33531.2
7Q(4T)
0.163;-29481.2
(7T)(4Q)
0.185;-25431.2
4T(7J)
0.148;-30100.0
4T(7K)
0.152;-28862.5
7(4JK)
0.181;-28243.8
4(7JK)
0.160;-28243.8
4J(7K)
0.193;-28243.8
4Q(7Q)
0.172;-24193.7
47QK
0.159;-31675.0
89(48)
0.142;-27906.2
(48)(8Q)
0.254;-22000.0
(489J)
0.166;-30100.0
(48)(9T)
0.173;-26668.8
9(48K)
0.150;-28862.5
(48TK)
0.152;-28243.8
TQ(48)
0.178;-28862.5
K(48J)
0.172;-27625.0
Q(48Q)
0.184;-23575.0
KK(48)
0.181;-22337.5
88(4J)
0.150;-26668.8
488K
0.138;-29481.2
8J(49)
0.124;-30100.0
(89)(4T)
0.141;-26668.8
4Q(89)
0.144;-29481.2
489T
0.119;-34768.8
489Q
0.125;-33531.2
(4T)(8J)
0.205;-25431.2
4T(8T)
0.158;-26050.0
4(8TK)
0.153;-28243.8
4T(8Q)
0.186;-28862.5
8J(4J)
0.147;-24812.5
(8J)(4Q)
0.148;-24193.8
4J(8Q)
0.143;-28243.8
8Q(4Q)
0.167;-23575.0
48QQ
0.169;-27625.0
48KK
0.138;-26387.5
9(49Q)
0.214;-24812.5
J(49T)
0.124;-28862.5
TJ(49)
0.171;-28862.5
(49JQ)
0.194;-27625.0
J(49K)
0.120;-27006.2
(49)(QK)
0.236;-22337.5
99(4J)
0.152;-25431.2
499K
0.165;-28243.8
9Q(4T)
0.182;-28243.8
(9T)(4Q)
0.197;-24193.8
4T(9J)
0.123;-28862.5
4T(9K)
0.168;-27625.0
9(4JK)
0.154;-27006.2
4(9JK)
0.144;-27006.2
4J(9K)
0.164;-27006.2
4Q(9Q)
0.181;-22956.2
49QK
0.108;-30437.5
TJ(4T)
0.154;-24193.7
(4TJQ)
0.158;-27006.2
J(4TK)
0.139;-26387.5
(4T)(QK)
0.212;-21718.7
TT(4Q)
0.182;-23575.0
T(4JQ)
0.143;-27006.2
4(TJQ)
0.135;-27006.2
4T(JQ)
0.132;-27006.2
T(4QK)
0.150;-25768.7
TQ(4K)
0.170;-25768.7
JJ(4J)
0.217;-18906.3
(4JQK)
0.166;-25150.0
4JJJ
0.193;-22956.2
JQ(4Q)
0.210;-21718.7
4JQQ
0.134;-25768.7
4JKK
0.186;-24531.2
QQ(4K)
0.220;-20481.2
4KKK
0.224;-19243.8
55(59)
0.168;-26950.0
55(5K)
0.217;-24475.0
(56)(58)
0.130;-26950.0
5(56J)
0.146;-29143.7
5K(56)
0.161;-27906.2
56(59)
0.127;-30381.2
556J
0.142;-33193.8
57(57)
0.195;-26950.0
(57)(5T)
0.177;-25093.7
5(57K)
0.154;-27287.5
55(79)
0.175;-29762.5
57(5Q)
0.126;-27906.2
5(589)
0.144;-29143.7
5J(58)
0.132;-27906.2
58(59)
0.139;-29143.7
558J
0.133;-31956.2
59(59)
0.170;-24475.0
(59)(5Q)
0.173;-22618.8
559T
0.156;-31956.2
55(9K)
0.149;-26050.0
(5T)(5Q)
0.230;-22000.0
55TJ
0.163;-30718.8
5J(5J)
0.181;-22000.0
5J(5Q)
0.174;-25431.2
5(5QK)
0.183;-24193.7
5K(5K)
0.210;-19525.0
68(56)
0.134;-30381.2
(56)(6J)
0.218;-24475.0
7(567)
0.124;-30381.2
J(567)
0.168;-31956.2
78(56)
0.106;-33812.5
(56)(7J)
0.162;-27906.2
8(568)
0.137;-29143.7
Q(568)
0.102;-30718.8
(56)(8T)
0.126;-27906.2
8(56K)
0.149;-30100.0
(569Q)
0.158;-30100.0
9(56J)
0.159;-30718.8
9K(56)
0.186;-29481.2
TT(56)
0.168;-26668.8
(56)(TK)
0.170;-24812.5
J(56Q)
0.137;-28862.5
K(56Q)
0.172;-27625.0
66(57)
0.122;-31000.0
5669
0.134;-33812.5
56(6Q)
0.129;-27906.2
(57)(68)
0.136;-29762.5
6(57J)
0.137;-31956.2
6K(57)
0.131;-30718.8
(67)(5T)
0.129;-28525.0
5Q(67)
0.144;-31337.5
5678
0.104;-37862.5
567T
0.130;-36625.0
567Q
0.140;-35387.5
(58)(69)
0.126;-28525.0
6(58Q)
0.119;-30718.8
5(689)
0.113;-32575.0
(68)(5Q)
0.160;-26668.8
58(69)
0.138;-32575.0
58(6J)
0.157;-31337.5
58(6K)
0.172;-30100.0
6(59J)
0.143;-30718.8
6K(59)
0.132;-29481.2
(69)(5Q)
0.167;-26050.0
59(6T)
0.157;-31337.5
59(6Q)
0.130;-30100.0
6T(5T)
0.209;-26668.8
(5T)(6K)
0.176;-24812.5
5Q(6T)
0.178;-29481.2
56TJ
0.119;-34150.0
56TK
0.117;-32912.5
6K(5J)
0.148;-28243.8
56JJ
0.137;-29481.2
56JK
0.112;-32293.8
5(6QK)
0.170;-27625.0
6K(5K)
0.236;-22956.2
(57)(79)
0.138;-24475.0
7(57Q)
0.174;-26668.8
9(578)
0.146;-31956.2
K(578)
0.165;-29481.2
8(57J)
0.164;-30718.8
8K(57)
0.150;-29481.2
(579K)
0.165;-28862.5
9J(57)
0.140;-30100.0
(57TJ)
0.154;-29481.2
(57)(TJ)
0.203;-25431.2
J(57J)
0.143;-24812.5
JQ(57)
0.133;-28243.8
Q(57K)
0.213;-27006.2
5778
0.143;-33193.8
57(7J)
0.173;-27287.5
(58)(78)
0.181;-24475.0
7(58J)
0.119;-30718.8
7K(58)
0.168;-29481.2
(78)(5J)
0.153;-26668.8
5K(78)
0.183;-29481.2
57(8T)
0.130;-31337.5
57(8Q)
0.123;-30100.0
7(59T)
0.107;-30718.8
7Q(59)
0.147;-29481.2
(79)(5J)
0.165;-26050.0
5K(79)
0.144;-28862.5
57(9J)
0.120;-30100.0
57(9K)
0.145;-28862.5
(5T)(7Q)
0.206;-24812.5
5J(7T)
0.126;-29481.2
7T(5J)
0.153;-29481.2
7T(5K)
0.162;-28243.8
7Q(5J)
0.127;-28243.8
(7J)(5K)
0.206;-23575.0
7J(5K)
0.158;-27625.0
7K(5Q)
0.152;-27006.2
57(QK)
0.163;-27006.2
(58)(89)
0.214;-23237.5
8(58Q)
0.173;-25431.2
T(589)
0.157;-30100.0
9(58T)
0.117;-30100.0
9Q(58)
0.152;-28862.5
Q(58T)
0.134;-28243.8
(58)(TQ)
0.218;-24193.8
(58JK)
0.137;-27006.2
JK(58)
0.172;-27006.2
K(58K)
0.187;-21718.7
588T
0.117;-30718.8
58(8K)
0.183;-24812.5
(59)(8J)
0.148;-25431.2
59(89)
0.135;-26668.8
5(89Q)
0.135;-28862.5
58(9T)
0.131;-30100.0
58(9Q)
0.132;-28862.5
8(5TJ)
0.182;-28862.5
8K(5T)
0.177;-27625.0
(8T)(5K)
0.230;-23575.0
8T(5Q)
0.141;-28243.8
(5J)(8J)
0.151;-20143.7
5J(8J)
0.177;-24193.7
8J(5Q)
0.161;-27625.0
(5Q)(8Q)
0.228;-18906.3
5K(8Q)
0.188;-26387.5
5K(8K)
0.187;-21718.7
9J(59)
0.190;-24812.5
(59TJ)
0.182;-28243.8
(59)(TJ)
0.184;-24193.8
J(59J)
0.209;-23575.0
JQ(59)
0.196;-27006.2
Q(59K)
0.185;-25768.7
599T
0.145;-29481.2
59(9K)
0.179;-23575.0
(5T)(9Q)
0.164;-23575.0
5J(9T)
0.139;-28243.8
9T(5J)
0.160;-28243.8
9T(5K)
0.144;-27006.2
9Q(5J)
0.183;-27006.2
(9J)(5K)
0.199;-22337.5
9J(5K)
0.178;-26387.5
9K(5Q)
0.161;-25768.7
59(QK)
0.158;-25768.7
(5T)(TJ)
0.179;-19525.0
J(5TJ)
0.156;-22956.2
JQ(5T)
0.210;-26387.5
Q(5TK)
0.158;-25150.0
5TTJ
0.206;-27625.0
TJ(5J)
0.141;-22956.2
(TJ)(5Q)
0.182;-22337.5
5J(TQ)
0.159;-26387.5
TQ(5Q)
0.188;-21718.7
5TQQ
0.148;-25768.7
5TKK
0.186;-24531.2
Q(5JQ)
0.165;-21100.0
KK(5J)
0.208;-19862.5
(5Q)(JQ)
0.241;-17050.0
5K(JQ)
0.168;-24531.2
5K(JK)
0.209;-19862.5
5QQQ
0.181;-20481.2
KK(5K)
0.296;-14575.0
6669
0.175;-29143.8
666K
0.170;-26668.8
69(67)
0.165;-28525.0
(67)(6Q)
0.220;-22618.8
6678
0.112;-33193.8
66(7J)
0.156;-27287.5
(68)(68)
0.161;-20425.0
6(68J)
0.190;-26668.8
6K(68)
0.143;-25431.2
68(6J)
0.157;-26668.8
668K
0.105;-29481.2
6J(69)
0.189;-26050.0
69(6T)
0.166;-26668.8
669Q
0.194;-29481.2
6J(6T)
0.210;-25431.2
6T(6J)
0.153;-25431.2
66TK
0.184;-28243.8
6K(6J)
0.186;-23575.0
(6Q)(6Q)
0.262;-15475.0
66QK
0.137;-27006.2
7(679)
0.160;-27906.2
7J(67)
0.198;-26668.8
(6789)
0.148;-31337.5
(678K)
0.184;-28862.5
8T(67)
0.128;-30718.8
(67)(8K)
0.178;-24812.5
Q(679)
0.121;-28862.5
(67)(9J)
0.156;-25431.2
T(67T)
0.190;-25431.2
T(67J)
0.129;-28862.5
TK(67)
0.139;-27625.0
(67)(JQ)
0.185;-23575.0
QQ(67)
0.174;-22956.2
67(78)
0.167;-28525.0
77(6J)
0.171;-26668.8
677K
0.138;-29481.2
7T(68)
0.144;-30718.8
(68)(7K)
0.162;-24812.5
6T(78)
0.177;-30718.8
6(78K)
0.130;-28862.5
68(7T)
0.111;-30718.8
68(7Q)
0.121;-29481.2
79(69)
0.188;-26668.8
(69)(7Q)
0.154;-24812.5
6T(79)
0.169;-30100.0
6(79K)
0.156;-28243.8
69(7J)
0.133;-29481.2
69(7K)
0.135;-28243.8
7(6TQ)
0.200;-28243.8
6(7TJ)
0.184;-28862.5
67TT
0.157;-29481.2
67TQ
0.127;-32293.8
(6J)(7Q)
0.193;-23575.0
6Q(7J)
0.177;-27625.0
67JQ
0.150;-31675.0
(6Q)(7K)
0.189;-22337.5
6Q(7K)
0.183;-26387.5
8(689)
0.176;-26668.8
8J(68)
0.124;-25431.2
(689T)
0.161;-29481.2
99(68)
0.160;-26050.0
(68)(9Q)
0.164;-24193.8
(68TQ)
0.187;-27625.0
T(68Q)
0.163;-27625.0
Q(68J)
0.178;-27006.2
(68)(JK)
0.142;-22337.5
QK(68)
0.155;-25768.7
68(8T)
0.224;-26050.0
88(6K)
0.143;-24193.7
8(69J)
0.164;-28862.5
8K(69)
0.162;-27625.0
(89)(6Q)
0.217;-24193.8
69(8T)
0.128;-29481.2
69(8Q)
0.136;-28243.8
8T(6T)
0.172;-24812.5
(6T)(8K)
0.175;-22956.2
6Q(8T)
0.124;-27625.0
68TJ
0.136;-32293.8
68TK
0.155;-31056.2
8K(6J)
0.171;-26387.5
68JJ
0.163;-27625.0
68JK
0.121;-30437.5
6(8QK)
0.183;-25768.7
8K(6K)
0.191;-21100.0
(69)(9J)
0.232;-20143.7
T(69T)
0.183;-24193.7
T(69J)
0.170;-27625.0
TK(69)
0.153;-26387.5
(69)(JQ)
0.177;-22337.5
QQ(69)
0.185;-21718.7
69(9T)
0.162;-24812.5
99(6K)
0.189;-22956.2
9(6TQ)
0.175;-27006.2
6(9TJ)
0.208;-27625.0
69TT
0.141;-28243.8
69TQ
0.124;-31056.2
(6J)(9Q)
0.181;-22337.5
6Q(9J)
0.176;-26387.5
69JQ
0.160;-30437.5
(6Q)(9K)
0.191;-21100.0
6Q(9K)
0.203;-25150.0
T(6TJ)
0.173;-22956.2
TK(6T)
0.162;-21718.7
(6T)(JQ)
0.191;-21718.7
QQ(6T)
0.201;-21100.0
6T(TJ)
0.231;-22956.2
(6J)(TJ)
0.204;-18287.5
6J(TJ)
0.212;-22337.5
TJ(6Q)
0.166;-25768.7
(6Q)(TQ)
0.218;-17050.0
6K(TQ)
0.139;-24531.2
6K(TK)
0.167;-19862.5
JK(6J)
0.219;-20481.2
K(6JK)
0.188;-19243.8
6JJK
0.151;-24531.2
6(JQK)
0.193;-23912.5
JK(6K)
0.193;-19243.8
KK(6Q)
0.216;-18625.0
6QKK
0.163;-22675.0
77(7T)
0.146;-22618.8
(78)(78)
0.216;-19187.5
7(78J)
0.161;-25431.2
7K(78)
0.155;-24193.7
78(7J)
0.199;-25431.2
778K
0.182;-28243.8
7J(79)
0.180;-24812.5
79(7T)
0.127;-25431.2
779Q
0.141;-28243.8
7J(7T)
0.165;-24193.7
7T(7J)
0.157;-24193.7
77TK
0.172;-27006.2
7K(7J)
0.186;-22337.5
(7Q)(7Q)
0.281;-14237.5
77QK
0.178;-25768.7
8(78T)
0.217;-25431.2
8Q(78)
0.156;-24193.7
J(789)
0.160;-28243.8
9T(78)
0.151;-28862.5
(78)(9K)
0.190;-22956.2
K(78T)
0.170;-26387.5
T(78K)
0.143;-26387.5
JJ(78)
0.199;-22956.2
(78QK)
0.157;-25150.0
7888
0.184;-26668.8
78(8J)
0.167;-24812.5
(79)(89)
0.170;-21381.2
8(79Q)
0.147;-27625.0
7(89T)
0.134;-28862.5
(89)(7K)
0.206;-22956.2
89(7J)
0.171;-28243.8
89(7K)
0.143;-27006.2
8J(7T)
0.174;-27625.0
(8T)(7J)
0.189;-23575.0
7K(8T)
0.178;-26387.5
78(TQ)
0.147;-27006.2
8(7JQ)
0.174;-26387.5
7(8JQ)
0.167;-26387.5
78(JQ)
0.146;-26387.5
8(7QK)
0.210;-25150.0
8Q(7K)
0.199;-25150.0
99(79)
0.195;-20762.5
(79)(9Q)
0.179;-18906.3
(79TQ)
0.166;-26387.5
T(79Q)
0.171;-26387.5
Q(79J)
0.146;-25768.7
(79)(JK)
0.160;-21100.0
QK(79)
0.142;-24531.2
79(9J)
0.132;-23575.0
(7T)(9T)
0.179;-19525.0
9(7TK)
0.167;-25768.7
7(9TQ)
0.138;-26387.5
79(TJ)
0.158;-27006.2
79(TK)
0.153;-25768.7
(7J)(9K)
0.156;-21100.0
7K(9J)
0.145;-25150.0
79(JK)
0.157;-25150.0
(9Q)(7K)
0.188;-20481.2
(7K)(9K)
0.220;-15812.5
T(7TQ)
0.219;-21718.7
Q(7TJ)
0.158;-25150.0
(7T)(JK)
0.213;-20481.2
QK(7T)
0.234;-23912.5
7T(TQ)
0.159;-21718.7
(7J)(TQ)
0.164;-21100.0
7Q(TJ)
0.152;-25150.0
7TJQ
0.131;-29200.0
(7Q)(TK)
0.217;-19862.5
7Q(TK)
0.152;-23912.5
J(7JQ)
0.173;-20481.2
K(7JQ)
0.192;-23293.8
JJ(7Q)
0.219;-20481.2
J(7QK)
0.182;-23293.8
JQ(7K)
0.149;-23293.8
QQ(7Q)
0.276;-15193.8
7Q(QK)
0.216;-18625.0
8888
0.150;-22000.0
888Q
0.145;-23575.0
8(89J)
0.219;-23575.0
8K(89)
0.201;-22337.5
89(8Q)
0.198;-22956.2
8(8TJ)
0.177;-22956.2
8K(8T)
0.185;-21718.7
8T(8K)
0.222;-21718.7
8(8JK)
0.177;-21100.0
88(JK)
0.190;-21100.0
8Q(8K)
0.223;-20481.2
(89)(9T)
0.180;-19525.0
9(89K)
0.210;-21718.7
(89TK)
0.136;-25150.0
TQ(89)
0.157;-25768.7
K(89J)
0.181;-24531.2
Q(89Q)
0.145;-20481.2
KK(89)
0.271;-19243.8
99(8Q)
0.175;-22337.5
9(8TJ)
0.132;-26387.5
9K(8T)
0.164;-25150.0
(9T)(8K)
0.158;-21100.0
9T(8Q)
0.213;-25768.7
(8J)(9J)
0.281;-17668.7
8J(9J)
0.195;-21718.7
9J(8Q)
0.152;-25150.0
(8Q)(9Q)
0.266;-16431.2
8K(9Q)
0.219;-23912.5
8K(9K)
0.207;-19243.8
TQ(8T)
0.198;-21100.0
K(8TJ)
0.161;-23912.5
Q(8TQ)
0.204;-19862.5
KK(8T)
0.191;-18625.0
