AAAA
0.330;-5520.0
5AAA
0.192;-17490.0
9AAA
0.186;-14410.0
KAAA
0.246;-11330.0
4A(2A)
0.177;-27500.0
(2A)(7A)
0.221;-20150.0
A(2TA)
0.153;-22880.0
QA(2A)
0.174;-21340.0
2A(4A)
0.226;-27500.0
26AA
0.167;-31000.0
AA(29)
0.179;-23650.0
2A(QA)
0.185;-21340.0
A(34A)
0.137;-26730.0
6A(3A)
0.132;-25190.0
(3A)(9A)
0.236;-17840.0
A(3QA)
0.209;-20570.0
AA(34)
0.158;-26730.0
3A(7A)
0.200;-24420.0
39AA
0.158;-27920.0
AA(3Q)
0.174;-20570.0
(4A)(5A)
0.212;-20150.0
A(48A)
0.179;-22880.0
TA(4A)
0.209;-21340.0
(4A)(KA)
0.243;-13990.0
46AA
0.157;-29460.0
AA(49)
0.212;-22110.0
4A(QA)
0.220;-19800.0
A(56A)
0.190;-23650.0
8A(5A)
0.150;-22110.0
(5A)(JA)
0.281;-14760.0
55AA
0.176;-24420.0
AA(58)
0.164;-22110.0
5A(JA)
0.187;-19800.0
5KAA
0.186;-23300.0
8A(6A)
0.222;-21340.0
(6A)(JA)
0.220;-13990.0
66AA
0.236;-22880.0
AA(69)
0.156;-20570.0
6A(QA)
0.201;-18260.0
A(78A)
0.217;-20570.0
TA(7A)
0.265;-19030.0
(7A)(KA)
0.202;-11680.0
79AA
0.193;-24840.0
AA(7Q)
0.202;-17490.0
(8A)(9A)
0.215;-13990.0
A(8QA)
0.249;-16720.0
AA(89)
0.200;-19030.0
8A(QA)
0.270;-16720.0
A(9TA)
0.217;-17490.0
QA(9A)
0.261;-15950.0
9A(JA)
0.190;-16720.0
9KAA
0.223;-20220.0
QA(TA)
0.248;-15180.0
TA(QA)
0.203;-15180.0
A(JQA)
0.215;-14410.0
AA(JQ)
0.253;-14410.0
(QA)(KA)
0.249;-7830.0
KKAA
0.250;-12100.0
2(25A)
0.165;-35970.0
27(2A)
0.154;-34430.0
(2T)(2A)
0.182;-27080.0
2(2KA)
0.162;-29810.0
(236A)
0.115;-39470.0
(23TA)
0.175;-36390.0
33(2A)
0.127;-36740.0
(36)(2A)
0.162;-34430.0
3(29A)
0.135;-37160.0
3J(2A)
0.167;-35620.0
(245A)
0.095;-39470.0
(249A)
0.116;-36390.0
(24KA)
0.133;-33310.0
46(2A)
0.173;-38700.0
(49)(2A)
0.154;-31350.0
4(2QA)
0.143;-34080.0
6(25A)
0.129;-37930.0
T(25A)
0.139;-34850.0
5(26A)
0.135;-37930.0
58(2A)
0.129;-36390.0
(5J)(2A)
0.154;-29040.0
6(26A)
0.127;-32120.0
T(26A)
0.137;-34080.0
6(27A)
0.127;-36390.0
69(2A)
0.145;-34850.0
(6Q)(2A)
0.171;-27500.0
(279A)
0.167;-34080.0
(27KA)
0.161;-31000.0
79(2A)
0.159;-34080.0
(7Q)(2A)
0.168;-26730.0
(28TA)
0.143;-32540.0
88(2A)
0.145;-29040.0
(8J)(2A)
0.191;-26730.0
9(29A)
0.148;-27500.0
K(29A)
0.202;-29460.0
9(2QA)
0.170;-30230.0
J(2TA)
0.126;-30230.0
TJ(2A)
0.152;-30230.0
(2JQA)
0.146;-28690.0
J(2KA)
0.158;-27920.0
(QK)(2A)
0.177;-22110.0
22(4A)
0.135;-36740.0
226A
0.135;-40240.0
2A(29)
0.174;-32890.0
22(QA)
0.117;-30580.0
2(34A)
0.107;-41010.0
26(3A)
0.097;-39470.0
(29)(3A)
0.163;-32120.0
2(3QA)
0.127;-34850.0
A(234)
0.114;-41010.0
(23)(7A)
0.138;-33660.0
9A(23)
0.137;-37160.0
A(23Q)
0.166;-34850.0
2A(34)
0.094;-41010.0
2A(36)
0.130;-39470.0
2A(38)
0.131;-37930.0
2A(3T)
0.156;-36390.0
2A(3Q)
0.151;-34850.0
2(45A)
0.135;-39470.0
27(4A)
0.138;-37930.0
(2T)(4A)
0.140;-30580.0
2(4KA)
0.156;-33310.0
A(246)
0.116;-38700.0
(24)(9A)
0.195;-31350.0
JA(24)
0.133;-34850.0
24(5A)
0.147;-39470.0
24(7A)
0.143;-37930.0
24(9A)
0.119;-36390.0
24(JA)
0.129;-34850.0
24(KA)
0.107;-33310.0
26(5A)
0.119;-37930.0
(29)(5A)
0.135;-30580.0
2(5QA)
0.152;-33310.0
A(256)
0.129;-37930.0
(25)(9A)
0.186;-30580.0
JA(25)
0.128;-34080.0
25(6A)
0.156;-37930.0
25(8A)
0.128;-36390.0
25(TA)
0.153;-34850.0
25(QA)
0.152;-33310.0
(26)(6A)
0.179;-27080.0
2(69A)
0.148;-34850.0
2J(6A)
0.120;-33310.0
(26)(7A)
0.166;-31350.0
9A(26)
0.175;-34850.0
A(26Q)
0.131;-32540.0
2A(67)
0.173;-36390.0
2A(69)
0.126;-34850.0
2A(6J)
0.145;-33310.0
2A(6K)
0.173;-31770.0
(29)(7A)
0.130;-29040.0
2(7QA)
0.178;-31770.0
A(278)
0.129;-34850.0
(27)(JA)
0.192;-27500.0
KA(27)
0.176;-31000.0
2A(79)
0.140;-34080.0
2A(7J)
0.151;-32540.0
2A(7K)
0.185;-31000.0
(2T)(8A)
0.218;-27500.0
2(8KA)
0.211;-30230.0
A(28T)
0.151;-32540.0
(28)(KA)
0.166;-25190.0
28(TA)
0.160;-32540.0
28(QA)
0.142;-31000.0
(29)(9A)
0.149;-22460.0
2(9QA)
0.184;-30230.0
A(29T)
0.135;-31770.0
(29)(KA)
0.164;-24420.0
29(JA)
0.148;-31000.0
29(KA)
0.170;-29460.0
2J(TA)
0.125;-30230.0
(2T)(JA)
0.165;-25190.0
KA(2T)
0.163;-28690.0
2A(TQ)
0.202;-29460.0
2(JQA)
0.183;-28690.0
A(2JQ)
0.195;-28690.0
2A(JQ)
0.152;-28690.0
2(QKA)
0.162;-27150.0
2Q(KA)
0.223;-27150.0
33(3A)
0.153;-30930.0
(36)(3A)
0.181;-28620.0
3(39A)
0.148;-31350.0
3J(3A)
0.190;-29810.0
(345A)
0.133;-38700.0
(349A)
0.136;-35620.0
(34KA)
0.114;-32540.0
46(3A)
0.166;-37930.0
(49)(3A)
0.198;-30580.0
4(3QA)
0.152;-33310.0
6(35A)
0.135;-37160.0
T(35A)
0.185;-34080.0
5(36A)
0.121;-37160.0
58(3A)
0.128;-35620.0
(5J)(3A)
0.180;-28270.0
6(36A)
0.155;-31350.0
T(36A)
0.160;-33310.0
6(37A)
0.162;-35620.0
69(3A)
0.154;-34080.0
(6Q)(3A)
0.160;-26730.0
(379A)
0.167;-33310.0
(37KA)
0.207;-30230.0
79(3A)
0.135;-33310.0
(7Q)(3A)
0.234;-25960.0
(38TA)
0.143;-31770.0
88(3A)
0.182;-28270.0
(8J)(3A)
0.198;-25960.0
9(39A)
0.131;-26730.0
K(39A)
0.145;-28690.0
9(3QA)
0.154;-29460.0
J(3TA)
0.158;-29460.0
TJ(3A)
0.206;-29460.0
(3JQA)
0.160;-27920.0
J(3KA)
0.149;-27150.0
(QK)(3A)
0.228;-21340.0
33(5A)
0.161;-34430.0
337A
0.118;-37930.0
3A(3T)
0.140;-30580.0
33(KA)
0.176;-28270.0
3(46A)
0.128;-37930.0
38(4A)
0.181;-36390.0
(3J)(4A)
0.151;-29040.0
4A(34)
0.178;-34430.0
A(347)
0.148;-37160.0
(34)(TA)
0.165;-29810.0
QA(34)
0.156;-33310.0
345A
0.111;-43740.0
347A
0.093;-42200.0
349A
0.132;-40660.0
34JA
0.105;-39120.0
34KA
0.126;-37580.0
37(5A)
0.133;-36390.0
(3T)(5A)
0.146;-29040.0
3(5KA)
0.167;-31770.0
A(357)
0.171;-36390.0
(35)(TA)
0.131;-29040.0
QA(35)
0.193;-32540.0
356A
0.121;-42200.0
358A
0.106;-40660.0
35TA
0.131;-39120.0
35QA
0.166;-37580.0
(37)(6A)
0.160;-30580.0
3(6TA)
0.146;-33310.0
3Q(6A)
0.186;-31770.0
(36)(8A)
0.211;-29810.0
TA(36)
0.190;-33310.0
A(36K)
0.166;-31000.0
6A(38)
0.118;-34850.0
6A(3T)
0.136;-33310.0
6A(3Q)
0.133;-31770.0
37(7A)
0.156;-29810.0
(3T)(7A)
0.148;-27500.0
3(7KA)
0.170;-30230.0
A(379)
0.142;-33310.0
(37)(QA)
0.197;-25960.0
7A(38)
0.157;-34080.0
7A(3T)
0.137;-32540.0
7A(3Q)
0.167;-31000.0
38(8A)
0.177;-28270.0
(3J)(8A)
0.172;-25960.0
8A(38)
0.161;-28270.0
A(38J)
0.177;-31000.0
388A
0.149;-33310.0
38TA
0.127;-36810.0
38QA
0.123;-35270.0
(3T)(9A)
0.157;-25960.0
3(9KA)
0.172;-28690.0
A(39J)
0.137;-30230.0
399A
0.157;-31770.0
39JA
0.124;-35270.0
39KA
0.174;-33730.0
3Q(TA)
0.163;-28690.0
(3T)(QA)
0.216;-23650.0
TA(3J)
0.171;-29460.0
TA(3K)
0.208;-27920.0
3(JKA)
0.163;-27150.0
A(3JK)
0.138;-27150.0
JA(3K)
0.127;-27150.0
QA(3Q)
0.247;-22110.0
3QKA
0.168;-31420.0
45(4A)
0.158;-32890.0
(48)(4A)
0.210;-25540.0
4(4JA)
0.162;-28270.0
4K(4A)
0.177;-26730.0
(459A)
0.147;-34080.0
(45KA)
0.144;-31000.0
57(4A)
0.130;-35620.0
(5T)(4A)
0.212;-28270.0
5(4KA)
0.155;-31000.0
(469A)
0.151;-33310.0
(46KA)
0.146;-30230.0
68(4A)
0.183;-34080.0
(6J)(4A)
0.175;-26730.0
7(47A)
0.141;-29040.0
J(47A)
0.158;-31000.0
78(4A)
0.179;-33310.0
(7J)(4A)
0.174;-25960.0
8(48A)
0.207;-27500.0
Q(48A)
0.141;-29460.0
(8T)(4A)
0.165;-25960.0
8(4KA)
0.137;-28690.0
(49QA)
0.178;-28690.0
9(4JA)
0.154;-29460.0
9K(4A)
0.153;-27920.0
TT(4A)
0.232;-24420.0
(TK)(4A)
0.215;-22110.0
J(4QA)
0.192;-27150.0
K(4QA)
0.143;-25610.0
44(5A)
0.136;-32890.0
447A
0.137;-36390.0
4A(4T)
0.197;-29040.0
44(KA)
0.153;-26730.0
4(57A)
0.136;-35620.0
49(5A)
0.175;-34080.0
(4Q)(5A)
0.176;-26730.0
6A(45)
0.150;-36390.0
A(459)
0.118;-34080.0
(45)(QA)
0.190;-26730.0
5A(46)
0.149;-36390.0
5A(48)
0.184;-34850.0
5A(4T)
0.185;-33310.0
5A(4Q)
0.130;-31770.0
46(6A)
0.210;-30580.0
(49)(6A)
0.141;-28270.0
4(6QA)
0.159;-31000.0
A(467)
0.136;-34850.0
(46)(TA)
0.183;-27500.0
QA(46)
0.135;-31000.0
467A
0.125;-39890.0
469A
0.136;-38350.0
46JA
0.128;-36810.0
46KA
0.127;-35270.0
49(7A)
0.120;-32540.0
(4Q)(7A)
0.157;-25190.0
8A(47)
0.152;-33310.0
A(47J)
0.193;-31000.0
477A
0.111;-34080.0
479A
0.133;-37580.0
47JA
0.145;-36040.0
47KA
0.173;-34500.0
4T(8A)
0.173;-31000.0
(4K)(8A)
0.212;-23650.0
TA(48)
0.168;-31000.0
A(48K)
0.176;-28690.0
8A(4T)
0.136;-31000.0
8A(4Q)
0.134;-29460.0
49(9A)
0.220;-25960.0
(4Q)(9A)
0.160;-23650.0
TA(49)
0.185;-30230.0
A(49K)
0.179;-27920.0
9A(4J)
0.145;-29460.0
9A(4K)
0.218;-27920.0
4(TQA)
0.170;-27920.0
A(4TJ)
0.170;-28690.0
4TTA
0.187;-29460.0
4TQA
0.132;-32960.0
(4Q)(JA)
0.177;-22110.0
QA(4J)
0.197;-27150.0
4JQA
0.190;-32190.0
(4K)(QA)
0.192;-20570.0
QA(4K)
0.221;-25610.0
5(56A)
0.116;-30580.0
58(5A)
0.169;-29040.0
(5J)(5A)
0.198;-21690.0
6(56A)
0.136;-29810.0
T(56A)
0.165;-31770.0
6(57A)
0.113;-34080.0
69(5A)
0.134;-32540.0
(6Q)(5A)
0.154;-25190.0
(579A)
0.182;-31770.0
(57KA)
0.152;-28690.0
79(5A)
0.155;-31770.0
(7Q)(5A)
0.176;-24420.0
(58TA)
0.165;-30230.0
88(5A)
0.196;-26730.0
(8J)(5A)
0.216;-24420.0
9(59A)
0.198;-25190.0
K(59A)
0.170;-27150.0
9(5QA)
0.212;-27920.0
J(5TA)
0.126;-27920.0
TJ(5A)
0.195;-27920.0
(5JQA)
0.172;-26380.0
J(5KA)
0.158;-25610.0
(QK)(5A)
0.221;-19800.0
55(7A)
0.153;-29810.0
559A
0.147;-33310.0
5A(5Q)
0.188;-25960.0
(57)(6A)
0.130;-29040.0
5(6TA)
0.178;-31770.0
5Q(6A)
0.152;-30230.0
(56)(8A)
0.131;-28270.0
TA(56)
0.137;-31770.0
A(56K)
0.189;-29460.0
6A(58)
0.152;-33310.0
6A(5T)
0.176;-31770.0
6A(5Q)
0.206;-30230.0
57(7A)
0.229;-28270.0
(5T)(7A)
0.146;-25960.0
5(7KA)
0.216;-28690.0
A(579)
0.184;-31770.0
(57)(QA)
0.169;-24420.0
7A(58)
0.128;-32540.0
7A(5T)
0.191;-31000.0
7A(5Q)
0.166;-29460.0
58(8A)
0.200;-26730.0
(5J)(8A)
0.157;-24420.0
8A(58)
0.155;-26730.0
A(58J)
0.166;-29460.0
588A
0.138;-31770.0
58TA
0.133;-35270.0
58QA
0.136;-33730.0
(5T)(9A)
0.173;-24420.0
5(9KA)
0.186;-27150.0
A(59J)
0.191;-28690.0
599A
0.159;-30230.0
59JA
0.136;-33730.0
59KA
0.151;-32190.0
5Q(TA)
0.155;-27150.0
(5T)(QA)
0.198;-22110.0
TA(5J)
0.176;-27920.0
TA(5K)
0.168;-26380.0
5(JKA)
0.150;-25610.0
A(5JK)
0.164;-25610.0
JA(5K)
0.165;-25610.0
QA(5Q)
0.184;-20570.0
5QKA
0.145;-29880.0
67(6A)
0.185;-28270.0
(6T)(6A)
0.229;-20920.0
6(6KA)
0.181;-23650.0
(67TA)
0.164;-30230.0
77(6A)
0.162;-27500.0
(7T)(6A)
0.236;-25190.0
7(6KA)
0.162;-27920.0
(68JA)
0.128;-28690.0
(89)(6A)
0.145;-25190.0
8(6QA)
0.131;-27920.0
T(69A)
0.208;-28690.0
9(6TA)
0.188;-28690.0
9Q(6A)
0.212;-27150.0
Q(6TA)
0.201;-26380.0
(TQ)(6A)
0.177;-21340.0
(6JKA)
0.163;-24840.0
JK(6A)
0.183;-24840.0
K(6KA)
0.228;-18260.0
668A
0.148;-32540.0
6A(6J)
0.189;-25190.0
(67)(7A)
0.178;-22460.0
6(7TA)
0.199;-30230.0
6Q(7A)
0.138;-28690.0
(67)(9A)
0.154;-25960.0
JA(67)
0.148;-29460.0
67(8A)
0.171;-31770.0
67(TA)
0.120;-30230.0
67(QA)
0.172;-28690.0
(68)(8A)
0.193;-20920.0
6(8JA)
0.175;-28690.0
6K(8A)
0.167;-27150.0
(68)(JA)
0.199;-23650.0
KA(68)
0.188;-27150.0
6A(8T)
0.155;-29460.0
6A(8Q)
0.177;-27920.0
6(9TA)
0.218;-28690.0
6Q(9A)
0.196;-27150.0
(69)(JA)
0.228;-22880.0
KA(69)
0.152;-26380.0
6A(9J)
0.145;-27920.0
6A(9K)
0.169;-26380.0
(6Q)(TA)
0.184;-21340.0
JA(6T)
0.135;-27150.0
6T(JA)
0.192;-27150.0
6T(KA)
0.168;-25610.0
6Q(JA)
0.154;-25610.0
(6J)(KA)
0.172;-19800.0
6J(KA)
0.234;-24840.0
6K(QA)
0.197;-24070.0
6A(QK)
0.184;-24070.0
(78)(7A)
0.196;-20920.0
7(7JA)
0.195;-23650.0
7K(7A)
0.226;-22110.0
(78QA)
0.158;-27150.0
8(7TA)
0.173;-28690.0
8Q(7A)
0.156;-27150.0
J(79A)
0.176;-27150.0
9T(7A)
0.171;-27920.0
(9K)(7A)
0.196;-20570.0
K(7TA)
0.220;-24840.0
T(7KA)
0.178;-24840.0
JJ(7A)
0.217;-20570.0
(7QKA)
0.194;-23300.0
777A
0.194;-26730.0
7A(7T)
0.169;-24420.0
77(KA)
0.227;-22110.0
7(8TA)
0.148;-28690.0
7Q(8A)
0.205;-27150.0
(78)(TA)
0.173;-23650.0
QA(78)
0.156;-27150.0
789A
0.131;-34500.0
78JA
0.149;-32960.0
78KA
0.179;-31420.0
7J(9A)
0.130;-27150.0
(79)(TA)
0.190;-22880.0
QA(79)
0.180;-26380.0
79TA
0.159;-32960.0
79QA
0.163;-31420.0
(7J)(TA)
0.185;-21340.0
TA(7T)
0.206;-22110.0
A(7TK)
0.235;-24840.0
TA(7Q)
0.175;-25610.0
7J(JA)
0.208;-20570.0
(7J)(QA)
0.222;-19800.0
JA(7Q)
0.208;-24840.0
7Q(QA)
0.206;-19030.0
7QQA
0.203;-24070.0
7KKA
0.173;-22530.0
8(8JA)
0.172;-22110.0
8K(8A)
0.222;-20570.0
(89KA)
0.203;-24840.0
9J(8A)
0.197;-26380.0
(8TJA)
0.162;-25610.0
(TJ)(8A)
0.166;-20570.0
J(8JA)
0.201;-19800.0
JQ(8A)
0.188;-24070.0
Q(8KA)
0.169;-22530.0
889A
0.167;-28690.0
8A(8Q)
0.228;-21340.0
(8T)(9A)
0.256;-22110.0
8(9KA)
0.167;-24840.0
A(89J)
0.211;-26380.0
899A
0.184;-27920.0
89JA
0.178;-31420.0
89KA
0.172;-29880.0
8Q(TA)
0.189;-24840.0
(8T)(QA)
0.224;-19800.0
TA(8J)
0.179;-25610.0
TA(8K)
0.200;-24070.0
8(JKA)
0.195;-23300.0
A(8JK)
0.161;-23300.0
JA(8K)
0.211;-23300.0
QA(8Q)
0.212;-18260.0
8QKA
0.135;-27570.0
9T(9A)
0.157;-21340.0
(9K)(9A)
0.256;-13990.0
K(9TA)
0.237;-23300.0
T(9KA)
0.174;-23300.0
JJ(9A)
0.254;-19030.0
(9QKA)
0.193;-21760.0
999A
0.204;-22110.0
9A(9Q)
0.202;-19800.0
(9J)(TA)
0.226;-19800.0
TA(9T)
0.206;-20570.0
A(9TK)
0.216;-23300.0
TA(9Q)
0.192;-24070.0
9J(JA)
0.235;-19030.0
(9J)(QA)
0.203;-18260.0
JA(9Q)
0.149;-23300.0
9Q(QA)
0.218;-17490.0
9QQA
0.188;-22530.0
9KKA
0.238;-20990.0
T(TKA)
0.222;-17490.0
JJ(TA)
0.225;-18260.0
(TQKA)
0.234;-20990.0
TTTA
0.207;-19800.0
TA(TK)
0.186;-17490.0
(TK)(JA)
0.201;-16720.0
KA(TJ)
0.208;-21760.0
TA(JK)
0.195;-21760.0
(TQ)(KA)
0.247;-15950.0
(TK)(KA)
0.294;-10140.0
J(JKA)
0.264;-15950.0
(QK)(JA)
0.217;-15180.0
JJ(KA)
0.200;-15950.0
QA(JQ)
0.220;-15950.0
JQKA
0.196;-25260.0
QK(QA)
0.274;-14410.0
QK(KA)
0.206;-13640.0
22(24)
0.090;-40940.0
22(28)
0.147;-37860.0
22(2Q)
0.126;-34780.0
24(23)
0.121;-45210.0
(23)(27)
0.129;-37860.0
2(23T)
0.144;-40590.0
2Q(23)
0.167;-39050.0
23(25)
0.135;-44440.0
2237
0.087;-47940.0
22(3T)
0.120;-40590.0
23(2K)
0.137;-38280.0
2(246)
0.143;-42900.0
28(24)
0.119;-41360.0
(24)(2J)
0.124;-34010.0
2244
0.117;-44440.0
22(47)
0.108;-42130.0
24(2T)
0.146;-39820.0
224Q
0.111;-43320.0
26(25)
0.087;-42130.0
(25)(29)
0.161;-34780.0
2(25Q)
0.125;-37510.0
22(56)
0.124;-42130.0
25(29)
0.128;-39820.0
225J
0.114;-43320.0
26(26)
0.142;-36320.0
(26)(29)
0.167;-34010.0
2(26Q)
0.150;-36740.0
22(67)
0.129;-40590.0
26(2T)
0.129;-38280.0
226Q
0.127;-41780.0
28(27)
0.115;-39050.0
(27)(2J)
0.203;-31700.0
2277
0.138;-39820.0
22(7T)
0.132;-37510.0
27(2K)
0.138;-35200.0
2(28T)
0.144;-36740.0
2Q(28)
0.171;-35200.0
28(2T)
0.107;-36740.0
228Q
0.121;-40240.0
2T(29)
0.115;-35970.0
(29)(2K)
0.189;-28620.0
229J
0.146;-40240.0
2T(2T)
0.156;-30160.0
(2T)(2K)
0.157;-27850.0
22TQ
0.161;-38700.0
2Q(2J)
0.141;-32890.0
2J(2K)
0.128;-32120.0
22QQ
0.189;-32120.0
3(234)
0.113;-44440.0
36(23)
0.141;-42900.0
(23)(39)
0.127;-35550.0
3(23Q)
0.143;-38280.0
5(234)
0.073;-47940.0
9(234)
0.099;-44860.0
K(234)
0.110;-41780.0
4(237)
0.096;-46400.0
49(23)
0.137;-44860.0
(23)(4Q)
0.145;-37510.0
(2357)
0.125;-45630.0
(235J)
0.091;-42550.0
(23)(56)
0.127;-41360.0
5(239)
0.105;-44090.0
5J(23)
0.126;-42550.0
(2367)
0.119;-44860.0
(236J)
0.128;-41780.0
(23)(67)
0.142;-39820.0
6(23T)
0.117;-42550.0
6Q(23)
0.105;-41010.0
9(237)
0.134;-42550.0
K(237)
0.157;-39470.0
7(23T)
0.113;-41780.0
7Q(23)
0.144;-40240.0
T(238)
0.102;-41010.0
8(239)
0.121;-41780.0
8J(23)
0.142;-40240.0
(239T)
0.127;-40240.0
99(23)
0.131;-35970.0
(23)(9Q)
0.159;-33660.0
(23TQ)
0.161;-37930.0
T(23Q)
0.136;-37930.0
Q(23J)
0.110;-37160.0
(23)(JK)
0.152;-31350.0
QK(23)
0.112;-35620.0
23(35)
0.108;-43670.0
33(28)
0.111;-41360.0
233T
0.145;-44860.0
23(3K)
0.142;-37510.0
(24)(36)
0.125;-42130.0
3(249)
0.117;-44860.0
3J(24)
0.129;-43320.0
(34)(25)
0.120;-42900.0
27(34)
0.091;-46400.0
2(34T)
0.104;-44090.0
(34)(2K)
0.135;-36740.0
34(26)
0.102;-47170.0
34(28)
0.098;-45630.0
34(2T)
0.090;-44090.0
34(2Q)
0.114;-42550.0
(25)(35)
0.137;-37090.0
3(258)
0.138;-44860.0
3T(25)
0.163;-43320.0
(25)(3K)
0.120;-35970.0
27(35)
0.090;-45630.0
2(35T)
0.113;-43320.0
(35)(2K)
0.148;-35970.0
35(27)
0.140;-45630.0
35(29)
0.123;-44090.0
35(2J)
0.107;-42550.0
35(2K)
0.123;-41010.0
37(26)
0.146;-44860.0
(26)(3T)
0.100;-37510.0
3(26K)
0.123;-40240.0
2(368)
0.105;-44090.0
(36)(2J)
0.116;-36740.0
2K(36)
0.136;-40240.0
23(68)
0.121;-44090.0
23(6T)
0.117;-42550.0
23(6Q)
0.113;-41010.0
3(278)
0.107;-43320.0
3T(27)
0.127;-41780.0
(27)(3K)
0.155;-34430.0
29(37)
0.124;-42550.0
2(37Q)
0.145;-40240.0
23(78)
0.137;-43320.0
23(7T)
0.136;-41780.0
23(7Q)
0.127;-40240.0
3(289)
0.122;-41780.0
3J(28)
0.113;-40240.0
(38)(29)
0.146;-36740.0
2J(38)
0.114;-40240.0
38(29)
0.143;-41780.0
38(2J)
0.125;-40240.0
38(2K)
0.146;-38700.0
3T(29)
0.119;-40240.0
(29)(3K)
0.161;-32890.0
2J(39)
0.132;-39470.0
39(2T)
0.128;-40240.0
39(2Q)
0.115;-38700.0
(2T)(3T)
0.118;-29390.0
3(2TK)
0.142;-37160.0
2(3TQ)
0.152;-37930.0
23(TJ)
0.092;-38700.0
23(TK)
0.143;-37160.0
(2J)(3K)
0.159;-31350.0
2K(3J)
0.126;-36390.0
23(JK)
0.151;-36390.0
(3Q)(2K)
0.136;-30580.0
(2K)(3K)
0.181;-24770.0
4(246)
0.104;-41360.0
48(24)
0.123;-39820.0
(24)(4J)
0.148;-32470.0
5(245)
0.162;-41360.0
9(245)
0.134;-43320.0
K(245)
0.112;-40240.0
5(248)
0.123;-44090.0
5T(24)
0.112;-42550.0
(24)(5K)
0.148;-35200.0
9(246)
0.092;-42550.0
K(246)
0.151;-39470.0
6(249)
0.106;-42550.0
6J(24)
0.124;-41010.0
(2478)
0.138;-42550.0
(247Q)
0.101;-39470.0
7(249)
0.115;-41780.0
7J(24)
0.160;-40240.0
(2489)
0.129;-41010.0
(248K)
0.125;-37930.0
8T(24)
0.106;-40240.0
(24)(8K)
0.144;-32890.0
Q(249)
0.136;-37930.0
(24)(9J)
0.167;-33660.0
T(24T)
0.146;-33660.0
T(24J)
0.142;-37930.0
TK(24)
0.118;-36390.0
(24)(JQ)
0.160;-31350.0
QQ(24)
0.126;-30580.0
24(45)
0.121;-42130.0
44(28)
0.101;-39820.0
244T
0.107;-43320.0
24(4K)
0.135;-35970.0
(25)(47)
0.127;-39820.0
4(25T)
0.122;-42550.0
4Q(25)
0.100;-41010.0
(45)(27)
0.136;-39820.0
29(45)
0.106;-43320.0
2(45Q)
0.136;-41010.0
24(56)
0.120;-45630.0
24(58)
0.086;-44090.0
24(5T)
0.131;-42550.0
24(5Q)
0.145;-41010.0
4(267)
0.109;-44090.0
49(26)
0.154;-42550.0
(26)(4Q)
0.113;-35200.0
27(46)
0.121;-44090.0
2(46T)
0.105;-41780.0
(46)(2K)
0.157;-34430.0
46(28)
0.145;-43320.0
46(2T)
0.117;-41780.0
46(2Q)
0.113;-40240.0
(27)(47)
0.145;-33240.0
4(27T)
0.095;-41010.0
4Q(27)
0.125;-39470.0
(47)(29)
0.140;-36740.0
2J(47)
0.100;-40240.0
47(28)
0.104;-42550.0
47(2T)
0.135;-41010.0
47(2Q)
0.118;-39470.0
(28)(48)
0.164;-31700.0
4(28J)
0.122;-39470.0
4K(28)
0.117;-37930.0
(48)(2J)
0.160;-34430.0
2K(48)
0.116;-37930.0
24(8T)
0.132;-40240.0
24(8Q)
0.151;-38700.0
4(29T)
0.137;-39470.0
4Q(29)
0.138;-37930.0
(49)(2J)
0.157;-33660.0
2K(49)
0.153;-37160.0
24(9J)
0.109;-38700.0
24(9K)
0.133;-37160.0
(2T)(4Q)
0.159;-32120.0
2J(4T)
0.153;-37930.0
4T(2J)
0.133;-37930.0
4T(2K)
0.136;-36390.0
4Q(2J)
0.120;-36390.0
(4J)(2K)
0.129;-30580.0
4J(2K)
0.170;-35620.0
4K(2Q)
0.161;-34850.0
24(QK)
0.124;-34850.0
(25)(56)
0.152;-34780.0
5(259)
0.142;-37510.0
5J(25)
0.170;-35970.0
(2567)
0.123;-43320.0
(256J)
0.106;-40240.0
(25)(67)
0.130;-38280.0
6(25T)
0.118;-41010.0
6Q(25)
0.140;-39470.0
9(257)
0.120;-41010.0
K(257)
0.113;-37930.0
7(25T)
0.131;-40240.0
7Q(25)
0.156;-38700.0
T(258)
0.125;-39470.0
8(259)
0.124;-40240.0
8J(25)
0.130;-38700.0
(259T)
0.113;-38700.0
99(25)
0.135;-34430.0
(25)(9Q)
0.159;-32120.0
(25TQ)
0.164;-36390.0
T(25Q)
0.176;-36390.0
Q(25J)
0.175;-35620.0
(25)(JK)
0.180;-29810.0
QK(25)
0.145;-34080.0
25(57)
0.136;-39050.0
55(2T)
0.147;-36740.0
255Q
0.147;-40240.0
57(26)
0.124;-43320.0
(26)(5T)
0.147;-35970.0
5(26K)
0.129;-38700.0
2(568)
0.097;-42550.0
(56)(2J)
0.162;-35200.0
2K(56)
0.148;-38700.0
25(68)
0.099;-42550.0
25(6T)
0.123;-41010.0
25(6Q)
0.144;-39470.0
5(278)
0.104;-41780.0
5T(27)
0.137;-40240.0
(27)(5K)
0.160;-32890.0
29(57)
0.143;-41010.0
2(57Q)
0.117;-38700.0
25(78)
0.116;-41780.0
25(7T)
0.127;-40240.0
25(7Q)
0.118;-38700.0
5(289)
0.160;-40240.0
5J(28)
0.157;-38700.0
(58)(29)
0.121;-35200.0
2J(58)
0.119;-38700.0
58(29)
0.133;-40240.0
58(2J)
0.107;-38700.0
58(2K)
0.130;-37160.0
5T(29)
0.109;-38700.0
(29)(5K)
0.134;-31350.0
2J(59)
0.159;-37930.0
59(2T)
0.119;-38700.0
59(2Q)
0.131;-37160.0
(2T)(5T)
0.138;-27850.0
5(2TK)
0.142;-35620.0
2(5TQ)
0.121;-36390.0
25(TJ)
0.180;-37160.0
25(TK)
0.111;-35620.0
(2J)(5K)
0.216;-29810.0
2K(5J)
0.114;-34850.0
25(JK)
0.124;-34850.0
(5Q)(2K)
0.169;-29040.0
(2K)(5K)
0.245;-23230.0
6(268)
0.134;-36740.0
6T(26)
0.145;-35200.0
(26)(6K)
0.158;-27850.0
T(267)
0.097;-39470.0
7(268)
0.093;-41010.0
7T(26)
0.127;-39470.0
(26)(7K)
0.134;-32120.0
J(268)
0.129;-37930.0
89(26)
0.100;-39470.0
(26)(8Q)
0.175;-32120.0
(269J)
0.137;-37160.0
(26)(9T)
0.150;-32890.0
9(26K)
0.144;-35620.0
(26TK)
0.158;-34850.0
TQ(26)
0.140;-35620.0
K(26J)
0.151;-34080.0
Q(26Q)
0.199;-29040.0
KK(26)
0.166;-27500.0
66(29)
0.136;-35970.0
266J
0.103;-39470.0
67(27)
0.115;-36740.0
(27)(6T)
0.116;-34430.0
6(27K)
0.128;-37160.0
2(679)
0.133;-40240.0
(67)(2Q)
0.129;-32890.0
27(68)
0.116;-41010.0
27(6T)
0.150;-39470.0
27(6Q)
0.175;-37930.0
68(28)
0.111;-35200.0
(28)(6J)
0.143;-32890.0
28(68)
0.183;-35200.0
2(68J)
0.124;-37930.0
2688
0.144;-40240.0
268T
0.122;-43740.0
268Q
0.098;-42200.0
(29)(6T)
0.138;-32890.0
6(29K)
0.117;-35620.0
2(69J)
0.140;-37160.0
2699
0.123;-38700.0
269J
0.111;-42200.0
269K
0.141;-40660.0
6Q(2T)
0.128;-35620.0
(6T)(2Q)
0.144;-30580.0
2T(6J)
0.137;-36390.0
2T(6K)
0.162;-34850.0
6(2JK)
0.125;-34080.0
2(6JK)
0.170;-34080.0
2J(6K)
0.124;-34080.0
2Q(6Q)
0.157;-29040.0
26QK
0.141;-38350.0
78(27)
0.169;-35200.0
(27)(7J)
0.194;-27850.0
8(278)
0.146;-34430.0
Q(278)
0.132;-36390.0
(27)(8T)
0.160;-32890.0
8(27K)
0.163;-35620.0
(279Q)
0.154;-35620.0
9(27J)
0.176;-36390.0
9K(27)
0.113;-34850.0
TT(27)
0.152;-31350.0
(27)(TK)
0.152;-29040.0
J(27Q)
0.128;-34080.0
K(27Q)
0.144;-32540.0
77(28)
0.168;-35200.0
277T
0.138;-38700.0
27(7K)
0.170;-31350.0
(28)(7T)
0.131;-32890.0
7(28K)
0.130;-35620.0
2(78T)
0.115;-37930.0
(78)(2K)
0.199;-30580.0
78(2T)
0.153;-37930.0
78(2Q)
0.122;-36390.0
(29)(79)
0.157;-27850.0
7(29Q)
0.117;-35620.0
2(79T)
0.137;-37160.0
(79)(2K)
0.161;-29810.0
79(2J)
0.148;-36390.0
79(2K)
0.155;-34850.0
7J(2T)
0.193;-35620.0
(7T)(2J)
0.129;-30580.0
2K(7T)
0.135;-34080.0
27(TQ)
0.135;-34850.0
7(2JQ)
0.163;-34080.0
2(7JQ)
0.133;-34080.0
27(JQ)
0.125;-34080.0
7(2QK)
0.135;-32540.0
7Q(2K)
0.180;-32540.0
88(28)
0.188;-28620.0
(28)(8J)
0.176;-26310.0
9(289)
0.110;-32120.0
K(289)
0.176;-34080.0
9(28Q)
0.115;-34850.0
J(28T)
0.150;-34850.0
TJ(28)
0.131;-34850.0
(28JQ)
0.141;-33310.0
J(28K)
0.145;-32540.0
(28)(QK)
0.192;-26730.0
88(2T)
0.160;-32120.0
288Q
0.150;-35620.0
8T(29)
0.111;-36390.0
(29)(8K)
0.154;-29040.0
2J(89)
0.154;-35620.0
89(2T)
0.156;-36390.0
89(2Q)
0.131;-34850.0
(2T)(8T)
0.219;-25540.0
8(2TK)
0.154;-33310.0
2(8TQ)
0.185;-34080.0
28(TJ)
0.142;-34850.0
28(TK)
0.115;-33310.0
(2J)(8K)
0.196;-27500.0
2K(8J)
0.156;-32540.0
28(JK)
0.155;-32540.0
(8Q)(2K)
0.213;-26730.0
(2K)(8K)
0.218;-20920.0
9(29J)
0.150;-29810.0
9K(29)
0.165;-28270.0
TT(29)
0.134;-29810.0
(29)(TK)
0.163;-27500.0
J(29Q)
0.175;-32540.0
K(29Q)
0.176;-31000.0
99(2T)
0.149;-30580.0
299Q
0.148;-34080.0
9J(2T)
0.167;-34080.0
(9T)(2J)
0.136;-29040.0
2K(9T)
0.169;-32540.0
29(TQ)
0.132;-33310.0
9(2JQ)
0.117;-32540.0
2(9JQ)
0.163;-32540.0
29(JQ)
0.184;-32540.0
9(2QK)
0.169;-31000.0
9Q(2K)
0.150;-31000.0
TT(2T)
0.227;-24000.0
(2T)(TK)
0.181;-21690.0
J(2TQ)
0.195;-31770.0
K(2TQ)
0.194;-30230.0
TT(2J)
0.149;-28270.0
2TTK
0.176;-31770.0
TK(2J)
0.154;-31000.0
2TJJ
0.203;-32540.0
2TJK
0.106;-36040.0
2(TQK)
0.131;-30230.0
TK(2K)
0.197;-24420.0
(2J)(JK)
0.174;-20150.0
QK(2J)
0.158;-29460.0
2J(JK)
0.187;-25190.0
(JQ)(2K)
0.163;-24420.0
(2K)(JK)
0.196;-18610.0
K(2QK)
0.171;-22880.0
2K(QK)
0.142;-22880.0
3335
0.146;-42900.0
3339
0.110;-39820.0
333K
0.147;-36740.0
36(34)
0.122;-41360.0
(34)(39)
0.145;-34010.0
3(34Q)
0.112;-36740.0
33(45)
0.102;-42130.0
34(38)
0.129;-39820.0
334T
0.108;-43320.0
33(4K)
0.169;-35970.0
(35)(37)
0.148;-34780.0
3(35T)
0.132;-37510.0
3Q(35)
0.166;-35970.0
35(37)
0.132;-39820.0
3359
0.134;-43320.0
33(5Q)
0.167;-35970.0
(36)(37)
0.149;-34010.0
3(36T)
0.155;-36740.0
3Q(36)
0.147;-35200.0
36(38)
0.161;-38280.0
336T
0.112;-41780.0
33(6K)
0.143;-34430.0
(37)(39)
0.157;-31700.0
3(37Q)
0.143;-34430.0
33(78)
0.123;-37510.0
37(3J)
0.163;-35200.0
337K
0.155;-38700.0
3T(38)
0.140;-35200.0
(38)(3K)
0.162;-27850.0
338T
0.108;-40240.0
33(8K)
0.146;-32890.0
(39)(3J)
0.163;-28620.0
3399
0.112;-35200.0
33(9Q)
0.169;-32890.0
(3T)(3J)
0.148;-27850.0
33TT
0.144;-33660.0
33(TK)
0.121;-31350.0
(3J)(3K)
0.152;-25540.0
33JK
0.140;-35620.0
33(QK)
0.160;-29810.0
45(34)
0.096;-41360.0
(34)(48)
0.158;-34010.0
4(34J)
0.154;-36740.0
4K(34)
0.155;-35200.0
(3459)
0.104;-42550.0
(345K)
0.119;-39470.0
57(34)
0.115;-44090.0
(34)(5T)
0.164;-36740.0
5(34K)
0.174;-39470.0
(3469)
0.092;-41780.0
(346K)
0.108;-38700.0
68(34)
0.125;-42550.0
(34)(6J)
0.120;-35200.0
7(347)
0.174;-37510.0
J(347)
0.150;-39470.0
78(34)
0.102;-41780.0
(34)(7J)
0.162;-34430.0
8(348)
0.120;-35970.0
Q(348)
0.110;-37930.0
(34)(8T)
0.162;-34430.0
8(34K)
0.127;-37160.0
(349Q)
0.128;-37160.0
9(34J)
0.142;-37930.0
9K(34)
0.108;-36390.0
TT(34)
0.141;-32890.0
(34)(TK)
0.174;-30580.0
J(34Q)
0.161;-35620.0
K(34Q)
0.143;-34080.0
44(35)
0.143;-41360.0
3447
0.102;-44860.0
34(4T)
0.107;-37510.0
44(3K)
0.119;-35200.0
4(357)
0.125;-44090.0
49(35)
0.128;-42550.0
(35)(4Q)
0.156;-35200.0
36(45)
0.103;-44860.0
3(459)
0.138;-42550.0
(45)(3Q)
0.141;-35200.0
35(46)
0.100;-44860.0
35(48)
0.110;-43320.0
35(4T)
0.123;-41780.0
35(4Q)
0.108;-40240.0
46(36)
0.106;-39050.0
(36)(49)
0.153;-36740.0
4(36Q)
0.126;-39470.0
3(467)
0.103;-43320.0
(46)(3T)
0.137;-35970.0
3Q(46)
0.156;-39470.0
3467
0.109;-48360.0
3469
0.082;-46820.0
346J
0.119;-45280.0
346K
0.147;-43740.0
49(37)
0.143;-41010.0
(37)(4Q)
0.129;-33660.0
38(47)
0.154;-41780.0
3(47J)
0.120;-39470.0
3477
0.115;-42550.0
3479
0.084;-46050.0
347J
0.121;-44510.0
347K
0.121;-42970.0
4T(38)
0.091;-39470.0
(38)(4K)
0.198;-32120.0
3T(48)
0.147;-39470.0
3(48K)
0.128;-37160.0
38(4T)
0.129;-39470.0
38(4Q)
0.145;-37930.0
49(39)
0.151;-34430.0
(39)(4Q)
0.114;-32120.0
3T(49)
0.149;-38700.0
3(49K)
0.125;-36390.0
39(4J)
0.142;-37930.0
39(4K)
0.170;-36390.0
4(3TQ)
0.183;-36390.0
3(4TJ)
0.168;-37160.0
34TT
0.125;-37930.0
34TQ
0.149;-41430.0
(3J)(4Q)
0.149;-30580.0
3Q(4J)
0.135;-35620.0
34JQ
0.133;-40660.0
(3Q)(4K)
0.146;-29040.0
3Q(4K)
0.130;-34080.0
5(356)
0.100;-39050.0
58(35)
0.129;-37510.0
(35)(5J)
0.150;-30160.0
6(356)
0.140;-38280.0
T(356)
0.122;-40240.0
6(357)
0.148;-42550.0
69(35)
0.111;-41010.0
(35)(6Q)
0.137;-33660.0
(3579)
0.111;-40240.0
(357K)
0.129;-37160.0
79(35)
0.117;-40240.0
(35)(7Q)
0.158;-32890.0
(358T)
0.131;-38700.0
88(35)
0.128;-35200.0
(35)(8J)
0.141;-32890.0
9(359)
0.167;-33660.0
K(359)
0.130;-35620.0
9(35Q)
0.102;-36390.0
J(35T)
0.143;-36390.0
TJ(35)
0.156;-36390.0
(35JQ)
0.194;-34850.0
J(35K)
0.133;-34080.0
(35)(QK)
0.139;-28270.0
55(37)
0.116;-38280.0
3559
0.123;-41780.0
35(5Q)
0.151;-34430.0
(36)(57)
0.113;-37510.0
5(36T)
0.152;-40240.0
5Q(36)
0.159;-38700.0
(56)(38)
0.157;-36740.0
3T(56)
0.100;-40240.0
3(56K)
0.113;-37930.0
36(58)
0.106;-41780.0
36(5T)
0.129;-40240.0
36(5Q)
0.122;-38700.0
57(37)
0.142;-36740.0
(37)(5T)
0.167;-34430.0
5(37K)
0.120;-37160.0
3(579)
0.144;-40240.0
(57)(3Q)
0.142;-32890.0
37(58)
0.143;-41010.0
37(5T)
0.139;-39470.0
37(5Q)
0.120;-37930.0
58(38)
0.144;-35200.0
(38)(5J)
0.192;-32890.0
38(58)
0.132;-35200.0
3(58J)
0.133;-37930.0
3588
0.105;-40240.0
358T
0.104;-43740.0
358Q
0.138;-42200.0
(39)(5T)
0.135;-32890.0
5(39K)
0.120;-35620.0
3(59J)
0.116;-37160.0
3599
0.134;-38700.0
359J
0.133;-42200.0
359K
0.103;-40660.0
5Q(3T)
0.112;-35620.0
(5T)(3Q)
0.137;-30580.0
3T(5J)
0.151;-36390.0
3T(5K)
0.141;-34850.0
5(3JK)
0.137;-34080.0
3(5JK)
0.191;-34080.0
3J(5K)
0.141;-34080.0
3Q(5Q)
0.154;-29040.0
35QK
0.140;-38350.0
67(36)
0.152;-36740.0
(36)(6T)
0.142;-29390.0
6(36K)
0.166;-32120.0
(367T)
0.121;-38700.0
77(36)
0.163;-35970.0
(36)(7T)
0.167;-33660.0
7(36K)
0.164;-36390.0
(368J)
0.143;-37160.0
(36)(89)
0.151;-33660.0
8(36Q)
0.122;-36390.0
T(369)
0.141;-37160.0
9(36T)
0.157;-37160.0
9Q(36)
0.154;-35620.0
Q(36T)
0.179;-34850.0
(36)(TQ)
0.179;-29810.0
(36JK)
0.149;-33310.0
JK(36)
0.173;-33310.0
K(36K)
0.183;-26730.0
3668
0.119;-41010.0
36(6J)
0.150;-33660.0
(37)(67)
0.169;-30930.0
6(37T)
0.119;-38700.0
6Q(37)
0.157;-37160.0
(67)(39)
0.120;-34430.0
3J(67)
0.127;-37930.0
67(38)
0.131;-40240.0
67(3T)
0.129;-38700.0
67(3Q)
0.124;-37160.0
(38)(68)
0.194;-29390.0
6(38J)
0.151;-37160.0
6K(38)
0.127;-35620.0
(68)(3J)
0.180;-32120.0
3K(68)
0.152;-35620.0
36(8T)
0.141;-37930.0
36(8Q)
0.129;-36390.0
6(39T)
0.136;-37160.0
6Q(39)
0.141;-35620.0
(69)(3J)
0.176;-31350.0
3K(69)
0.133;-34850.0
36(9J)
0.169;-36390.0
36(9K)
0.130;-34850.0
(3T)(6Q)
0.182;-29810.0
3J(6T)
0.141;-35620.0
6T(3J)
0.134;-35620.0
6T(3K)
0.136;-34080.0
6Q(3J)
0.144;-34080.0
(6J)(3K)
0.200;-28270.0
6J(3K)
0.156;-33310.0
6K(3Q)
0.207;-32540.0
36(QK)
0.199;-32540.0
(37)(78)
0.177;-29390.0
7(37J)
0.144;-32120.0
7K(37)
0.153;-30580.0
(378Q)
0.158;-35620.0
8(37T)
0.114;-37160.0
8Q(37)
0.161;-35620.0
J(379)
0.155;-35620.0
9T(37)
0.107;-36390.0
(37)(9K)
0.186;-29040.0
K(37T)
0.148;-33310.0
T(37K)
0.146;-33310.0
JJ(37)
0.192;-29040.0
(37QK)
0.201;-31770.0
3777
0.162;-35200.0
37(7T)
0.131;-32890.0
77(3K)
0.124;-30580.0
7(38T)
0.180;-37160.0
7Q(38)
0.152;-35620.0
(78)(3T)
0.151;-32120.0
3Q(78)
0.177;-35620.0
3789
0.141;-42970.0
378J
0.120;-41430.0
378K
0.118;-39890.0
7J(39)
0.156;-35620.0
(79)(3T)
0.160;-31350.0
3Q(79)
0.152;-34850.0
379T
0.136;-41430.0
379Q
0.127;-39890.0
(3T)(7J)
0.149;-29810.0
3T(7T)
0.159;-30580.0
3(7TK)
0.117;-33310.0
3T(7Q)
0.183;-34080.0
7J(3J)
0.149;-29040.0
(7J)(3Q)
0.150;-28270.0
3J(7Q)
0.195;-33310.0
7Q(3Q)
0.183;-27500.0
37QQ
0.124;-32540.0
37KK
0.173;-31000.0
8(38J)
0.180;-30580.0
8K(38)
0.152;-29040.0
(389K)
0.175;-33310.0
9J(38)
0.177;-34850.0
(38TJ)
0.169;-34080.0
(38)(TJ)
0.152;-29040.0
J(38J)
0.174;-28270.0
JQ(38)
0.119;-32540.0
Q(38K)
0.180;-31000.0
3889
0.142;-37160.0
38(8Q)
0.174;-29810.0
(39)(8T)
0.173;-30580.0
8(39K)
0.179;-33310.0
3(89J)
0.128;-34850.0
3899
0.133;-36390.0
389J
0.123;-39890.0
389K
0.128;-38350.0
8Q(3T)
0.136;-33310.0
(8T)(3Q)
0.195;-28270.0
3T(8J)
0.175;-34080.0
3T(8K)
0.129;-32540.0
8(3JK)
0.194;-31770.0
3(8JK)
0.180;-31770.0
3J(8K)
0.199;-31770.0
3Q(8Q)
0.147;-26730.0
38QK
0.128;-36040.0
9T(39)
0.163;-29810.0
(39)(9K)
0.175;-22460.0
K(39T)
0.164;-31770.0
T(39K)
0.179;-31770.0
JJ(39)
0.170;-27500.0
(39QK)
0.144;-30230.0
3999
0.164;-30580.0
39(9Q)
0.149;-28270.0
(3T)(9J)
0.168;-28270.0
3T(9T)
0.205;-29040.0
3(9TK)
0.172;-31770.0
3T(9Q)
0.153;-32540.0
9J(3J)
0.196;-27500.0
(9J)(3Q)
0.199;-26730.0
3J(9Q)
0.130;-31770.0
9Q(3Q)
0.175;-25960.0
39QQ
0.176;-31000.0
39KK
0.150;-29460.0
T(3TK)
0.182;-25960.0
JJ(3T)
0.222;-26730.0
(3TQK)
0.186;-29460.0
3TTT
0.136;-28270.0
3T(TK)
0.208;-25960.0
(3J)(TK)
0.176;-25190.0
3K(TJ)
0.144;-30230.0
3T(JK)
0.185;-30230.0
(TQ)(3K)
0.226;-24420.0
(3K)(TK)
0.220;-18610.0
J(3JK)
0.188;-24420.0
(3J)(QK)
0.232;-23650.0
JJ(3K)
0.195;-24420.0
3Q(JQ)
0.176;-24420.0
3JQK
0.138;-33730.0
QK(3Q)
0.146;-22880.0
QK(3K)
0.213;-22110.0
44(46)
0.143;-34780.0
44(4T)
0.146;-31700.0
(45)(45)
0.171;-29740.0
4(458)
0.132;-37510.0
4T(45)
0.164;-35970.0
(45)(4K)
0.187;-28620.0
4457
0.086;-43320.0
44(5T)
0.123;-35970.0
45(4K)
0.163;-33660.0
4(468)
0.151;-36740.0
4T(46)
0.138;-35200.0
(46)(4K)
0.213;-27850.0
4468
0.111;-41780.0
44(6J)
0.175;-34430.0
(47)(47)
0.196;-26660.0
4(47T)
0.149;-34430.0
4Q(47)
0.159;-32890.0
47(49)
0.151;-35200.0
447J
0.140;-38700.0
48(48)
0.146;-30160.0
(48)(4J)
0.149;-27850.0
4488
0.153;-35200.0
44(8J)
0.155;-32890.0
(49)(49)
0.163;-23580.0
4(49Q)
0.130;-31350.0
44(9T)
0.186;-32890.0
49(4K)
0.161;-30580.0
4(4TQ)
0.121;-30580.0
44(TJ)
0.160;-31350.0
(4J)(4J)
0.220;-20500.0
44JJ
0.136;-30580.0
4Q(4Q)
0.211;-24000.0
(4K)(4K)
0.228;-17420.0
(45)(57)
0.142;-32470.0
5(45T)
0.160;-35200.0
5Q(45)
0.132;-33660.0
8(456)
0.100;-41010.0
Q(456)
0.138;-37930.0
(45)(68)
0.164;-35970.0
6(45J)
0.122;-38700.0
6K(45)
0.124;-37160.0
(457J)
0.148;-37930.0
(45)(78)
0.154;-35200.0
7(45J)
0.138;-37930.0
7K(45)
0.130;-36390.0
(458Q)
0.152;-36390.0
8(45T)
0.147;-37930.0
8Q(45)
0.131;-36390.0
J(459)
0.144;-36390.0
9T(45)
0.157;-37160.0
(45)(9K)
0.194;-29810.0
K(45T)
0.180;-34080.0
T(45K)
0.121;-34080.0
JJ(45)
0.168;-29810.0
(45QK)
0.172;-32540.0
4555
0.153;-39050.0
45(58)
0.128;-36740.0
55(4J)
0.127;-34430.0
455K
0.149;-37930.0
58(46)
0.104;-41010.0
(46)(5J)
0.140;-33660.0
46(56)
0.134;-37510.0
4(569)
0.128;-40240.0
(56)(4Q)
0.137;-32890.0
46(57)
0.104;-41780.0
46(59)
0.144;-40240.0
46(5J)
0.101;-38700.0
46(5K)
0.151;-37160.0
5(479)
0.163;-39470.0
5J(47)
0.126;-37930.0
(57)(48)
0.163;-35200.0
4T(57)
0.143;-38700.0
4(57K)
0.183;-36390.0
47(59)
0.135;-39470.0
47(5J)
0.138;-37930.0
47(5K)
0.150;-36390.0
5(48T)
0.132;-37930.0
5Q(48)
0.176;-36390.0
(58)(4T)
0.201;-32890.0
4Q(58)
0.135;-36390.0
4589
0.098;-43740.0
458J
0.099;-42200.0
458K
0.131;-40660.0
5J(49)
0.143;-36390.0
(59)(4T)
0.156;-32120.0
4Q(59)
0.157;-35620.0
459T
0.102;-42200.0
459Q
0.153;-40660.0
(4T)(5J)
0.160;-30580.0
4T(5T)
0.162;-31350.0
4(5TK)
0.140;-34080.0
4T(5Q)
0.129;-34850.0
5J(4J)
0.170;-29810.0
(5J)(4Q)
0.207;-29040.0
4J(5Q)
0.170;-34080.0
5Q(4Q)
0.132;-28270.0
45QQ
0.163;-33310.0
45KK
0.128;-31770.0
6(469)
0.141;-34430.0
6J(46)
0.170;-32890.0
(4678)
0.108;-39470.0
(467Q)
0.169;-36390.0
7(469)
0.144;-38700.0
7J(46)
0.137;-37160.0
(4689)
0.146;-37930.0
(468K)
0.130;-34850.0
8T(46)
0.172;-37160.0
(46)(8K)
0.131;-29810.0
Q(469)
0.130;-34850.0
(46)(9J)
0.125;-30580.0
T(46T)
0.151;-30580.0
T(46J)
0.148;-34850.0
TK(46)
0.153;-33310.0
(46)(JQ)
0.209;-28270.0
QQ(46)
0.180;-27500.0
46(67)
0.165;-35970.0
66(4T)
0.161;-33660.0
466Q
0.131;-37160.0
68(47)
0.128;-39470.0
(47)(6J)
0.134;-32120.0
47(67)
0.192;-35200.0
4(67T)
0.129;-37930.0
(67)(4K)
0.158;-30580.0
67(49)
0.144;-38700.0
67(4J)
0.165;-37160.0
67(4K)
0.115;-35620.0
69(48)
0.129;-37930.0
(48)(6Q)
0.148;-30580.0
49(68)
0.115;-37930.0
4(68Q)
0.150;-35620.0
46(89)
0.158;-37930.0
46(8J)
0.147;-36390.0
46(8K)
0.135;-34850.0
(49)(6J)
0.216;-30580.0
49(69)
0.179;-32120.0
4(69Q)
0.130;-34850.0
46(9T)
0.142;-36390.0
46(9Q)
0.149;-34850.0
6(4TJ)
0.182;-34850.0
6K(4T)
0.144;-33310.0
(6T)(4K)
0.178;-28270.0
6T(4Q)
0.130;-34080.0
(4J)(6J)
0.219;-24000.0
4J(6J)
0.134;-29040.0
6J(4Q)
0.177;-33310.0
(4Q)(6Q)
0.189;-22460.0
4K(6Q)
0.156;-31770.0
4K(6K)
0.156;-25960.0
79(47)
0.153;-32890.0
(47)(7Q)
0.147;-25540.0
(478T)
0.142;-36390.0
88(47)
0.141;-32890.0
(47)(8J)
0.174;-30580.0
9(479)
0.137;-31350.0
K(479)
0.154;-33310.0
9(47Q)
0.138;-34080.0
J(47T)
0.118;-34080.0
TJ(47)
0.143;-34080.0
(47JQ)
0.148;-32540.0
J(47K)
0.132;-31770.0
(47)(QK)
0.191;-25960.0
77(49)
0.204;-32890.0
477J
0.143;-36390.0
78(48)
0.142;-32890.0
(48)(7J)
0.133;-30580.0
48(78)
0.138;-32890.0
4(78J)
0.133;-35620.0
4788
0.116;-37930.0
478T
0.154;-41430.0
478Q
0.148;-39890.0
(49)(7T)
0.158;-30580.0
7(49K)
0.161;-33310.0
4(79J)
0.102;-34850.0
4799
0.173;-36390.0
479J
0.150;-39890.0
479K
0.138;-38350.0
7Q(4T)
0.125;-33310.0
(7T)(4Q)
0.179;-28270.0
4T(7J)
0.148;-34080.0
4T(7K)
0.175;-32540.0
7(4JK)
0.161;-31770.0
4(7JK)
0.140;-31770.0
4J(7K)
0.162;-31770.0
4Q(7Q)
0.185;-26730.0
47QK
0.111;-36040.0
89(48)
0.115;-31350.0
(48)(8Q)
0.186;-24000.0
(489J)
0.119;-34080.0
(48)(9T)
0.155;-29810.0
9(48K)
0.163;-32540.0
(48TK)
0.158;-31770.0
TQ(48)
0.187;-32540.0
K(48J)
0.165;-31000.0
Q(48Q)
0.209;-25960.0
KK(48)
0.212;-24420.0
88(4J)
0.170;-29810.0
488K
0.150;-33310.0
8J(49)
0.135;-34080.0
(89)(4T)
0.176;-29810.0
4Q(89)
0.157;-33310.0
489T
0.123;-39890.0
489Q
0.114;-38350.0
(4T)(8J)
0.159;-28270.0
4T(8T)
0.203;-29040.0
4(8TK)
0.177;-31770.0
4T(8Q)
0.138;-32540.0
8J(4J)
0.159;-27500.0
(8J)(4Q)
0.184;-26730.0
4J(8Q)
0.110;-31770.0
8Q(4Q)
0.169;-25960.0
48QQ
0.130;-31000.0
48KK
0.157;-29460.0
9(49Q)
0.173;-27500.0
J(49T)
0.145;-32540.0
TJ(49)
0.129;-32540.0
(49JQ)
0.132;-31000.0
J(49K)
0.136;-30230.0
(49)(QK)
0.178;-24420.0
99(4J)
0.185;-28270.0
499K
0.131;-31770.0
9Q(4T)
0.169;-31770.0
(9T)(4Q)
0.186;-26730.0
4T(9J)
0.147;-32540.0
4T(9K)
0.133;-31000.0
9(4JK)
0.169;-30230.0
4(9JK)
0.155;-30230.0
4J(9K)
0.196;-30230.0
4Q(9Q)
0.167;-25190.0
49QK
0.125;-34500.0
TJ(4T)
0.168;-26730.0
(4TJQ)
0.189;-30230.0
J(4TK)
0.208;-29460.0
(4T)(QK)
0.192;-23650.0
TT(4Q)
0.195;-25960.0
T(4JQ)
0.162;-30230.0
4(TJQ)
0.125;-30230.0
4T(JQ)
0.160;-30230.0
T(4QK)
0.149;-28690.0
TQ(4K)
0.177;-28690.0
JJ(4J)
0.234;-20150.0
(4JQK)
0.181;-27920.0
4JJJ
0.188;-25190.0
JQ(4Q)
0.187;-23650.0
4JQQ
0.161;-28690.0
4JKK
0.180;-27150.0
QQ(4K)
0.195;-22110.0
4KKK
0.261;-20570.0
55(59)
0.143;-30160.0
55(5K)
0.136;-27080.0
(56)(58)
0.155;-30160.0
5(56J)
0.197;-32890.0
5K(56)
0.154;-31350.0
56(59)
0.137;-34430.0
556J
0.132;-37930.0
57(57)
0.183;-30160.0
(57)(5T)
0.157;-27850.0
5(57K)
0.198;-30580.0
55(79)
0.144;-33660.0
57(5Q)
0.167;-31350.0
5(589)
0.168;-32890.0
5J(58)
0.162;-31350.0
58(59)
0.139;-32890.0
558J
0.139;-36390.0
59(59)
0.170;-27080.0
(59)(5Q)
0.148;-24770.0
559T
0.147;-36390.0
55(9K)
0.168;-29040.0
(5T)(5Q)
0.152;-24000.0
55TJ
0.158;-34850.0
5J(5J)
0.188;-24000.0
5J(5Q)
0.181;-28270.0
5(5QK)
0.204;-26730.0
5K(5K)
0.207;-20920.0
68(56)
0.140;-34430.0
(56)(6J)
0.173;-27080.0
7(567)
0.147;-34430.0
J(567)
0.131;-36390.0
78(56)
0.136;-38700.0
(56)(7J)
0.166;-31350.0
8(568)
0.140;-32890.0
Q(568)
0.139;-34850.0
(56)(8T)
0.164;-31350.0
8(56K)
0.154;-34080.0
(569Q)
0.156;-34080.0
9(56J)
0.140;-34850.0
9K(56)
0.140;-33310.0
TT(56)
0.158;-29810.0
(56)(TK)
0.184;-27500.0
J(56Q)
0.147;-32540.0
K(56Q)
0.130;-31000.0
66(57)
0.129;-35200.0
5669
0.126;-38700.0
56(6Q)
0.164;-31350.0
(57)(68)
0.123;-33660.0
6(57J)
0.163;-36390.0
6K(57)
0.109;-34850.0
(67)(5T)
0.113;-32120.0
5Q(67)
0.141;-35620.0
5678
0.083;-43740.0
567T
0.137;-42200.0
567Q
0.106;-40660.0
(58)(69)
0.171;-32120.0
6(58Q)
0.194;-34850.0
5(689)
0.116;-37160.0
(68)(5Q)
0.159;-29810.0
58(69)
0.129;-37160.0
58(6J)
0.115;-35620.0
58(6K)
0.131;-34080.0
6(59J)
0.173;-34850.0
6K(59)
0.148;-33310.0
(69)(5Q)
0.168;-29040.0
59(6T)
0.129;-35620.0
59(6Q)
0.146;-34080.0
6T(5T)
0.200;-29810.0
(5T)(6K)
0.194;-27500.0
5Q(6T)
0.156;-33310.0
56TJ
0.135;-39120.0
56TK
0.137;-37580.0
6K(5J)
0.191;-31770.0
56JJ
0.118;-33310.0
56JK
0.108;-36810.0
5(6QK)
0.130;-31000.0
6K(5K)
0.168;-25190.0
(57)(79)
0.154;-27080.0
7(57Q)
0.162;-29810.0
9(578)
0.181;-36390.0
K(578)
0.162;-33310.0
8(57J)
0.140;-34850.0
8K(57)
0.187;-33310.0
(579K)
0.169;-32540.0
9J(57)
0.186;-34080.0
(57TJ)
0.132;-33310.0
(57)(TJ)
0.206;-28270.0
J(57J)
0.165;-27500.0
JQ(57)
0.135;-31770.0
Q(57K)
0.133;-30230.0
5778
0.142;-37930.0
57(7J)
0.180;-30580.0
(58)(78)
0.178;-27080.0
7(58J)
0.124;-34850.0
7K(58)
0.169;-33310.0
(78)(5J)
0.164;-29810.0
5K(78)
0.152;-33310.0
57(8T)
0.114;-35620.0
57(8Q)
0.153;-34080.0
7(59T)
0.125;-34850.0
7Q(59)
0.133;-33310.0
(79)(5J)
0.163;-29040.0
5K(79)
0.165;-32540.0
57(9J)
0.154;-34080.0
57(9K)
0.155;-32540.0
(5T)(7Q)
0.154;-27500.0
5J(7T)
0.163;-33310.0
7T(5J)
0.153;-33310.0
7T(5K)
0.144;-31770.0
7Q(5J)
0.162;-31770.0
(7J)(5K)
0.180;-25960.0
7J(5K)
0.134;-31000.0
7K(5Q)
0.177;-30230.0
57(QK)
0.155;-30230.0
(58)(89)
0.179;-25540.0
8(58Q)
0.142;-28270.0
T(589)
0.130;-34080.0
9(58T)
0.129;-34080.0
9Q(58)
0.138;-32540.0
Q(58T)
0.144;-31770.0
(58)(TQ)
0.185;-26730.0
(58JK)
0.184;-30230.0
JK(58)
0.211;-30230.0
K(58K)
0.177;-23650.0
588T
0.177;-34850.0
58(8K)
0.205;-27500.0
(59)(8J)
0.174;-28270.0
59(89)
0.165;-29810.0
5(89Q)
0.168;-32540.0
58(9T)
0.152;-34080.0
58(9Q)
0.170;-32540.0
8(5TJ)
0.178;-32540.0
8K(5T)
0.143;-31000.0
(8T)(5K)
0.163;-25960.0
8T(5Q)
0.143;-31770.0
(5J)(8J)
0.179;-21690.0
5J(8J)
0.168;-26730.0
8J(5Q)
0.152;-31000.0
(5Q)(8Q)
0.194;-20150.0
5K(8Q)
0.164;-29460.0
5K(8K)
0.163;-23650.0
9J(59)
0.168;-27500.0
(59TJ)
0.182;-31770.0
(59)(TJ)
0.167;-26730.0
J(59J)
0.138;-25960.0
JQ(59)
0.165;-30230.0
Q(59K)
0.132;-28690.0
599T
0.158;-33310.0
59(9K)
0.194;-25960.0
(5T)(9Q)
0.165;-25960.0
5J(9T)
0.147;-31770.0
9T(5J)
0.147;-31770.0
9T(5K)
0.136;-30230.0
9Q(5J)
0.199;-30230.0
(9J)(5K)
0.181;-24420.0
9J(5K)
0.157;-29460.0
9K(5Q)
0.143;-28690.0
59(QK)
0.199;-28690.0
(5T)(TJ)
0.217;-20920.0
J(5TJ)
0.156;-25190.0
JQ(5T)
0.217;-29460.0
Q(5TK)
0.173;-27920.0
5TTJ
0.162;-31000.0
TJ(5J)
0.205;-25190.0
(TJ)(5Q)
0.170;-24420.0
5J(TQ)
0.146;-29460.0
TQ(5Q)
0.213;-23650.0
5TQQ
0.128;-28690.0
5TKK
0.175;-27150.0
Q(5JQ)
0.200;-22880.0
KK(5J)
0.172;-21340.0
(5Q)(JQ)
0.253;-17840.0
5K(JQ)
0.208;-27150.0
5K(JK)
0.180;-21340.0
5QQQ
0.169;-22110.0
KK(5K)
0.230;-14760.0
6669
0.181;-32890.0
666K
0.171;-29810.0
69(67)
0.144;-32120.0
(67)(6Q)
0.207;-24770.0
6678
0.125;-37930.0
66(7J)
0.154;-30580.0
(68)(68)
0.188;-22040.0
6(68J)
0.180;-29810.0
6K(68)
0.153;-28270.0
68(6J)
0.176;-29810.0
668K
0.162;-33310.0
6J(69)
0.165;-29040.0
69(6T)
0.143;-29810.0
669Q
0.174;-33310.0
6J(6T)
0.144;-28270.0
6T(6J)
0.131;-28270.0
66TK
0.180;-31770.0
6K(6J)
0.187;-25960.0
(6Q)(6Q)
0.227;-15880.0
66QK
0.174;-30230.0
7(679)
0.171;-31350.0
7J(67)
0.149;-29810.0
(6789)
0.126;-35620.0
(678K)
0.129;-32540.0
8T(67)
0.177;-34850.0
(67)(8K)
0.178;-27500.0
Q(679)
0.185;-32540.0
(67)(9J)
0.152;-28270.0
T(67T)
0.121;-28270.0
T(67J)
0.135;-32540.0
TK(67)
0.155;-31000.0
(67)(JQ)
0.183;-25960.0
QQ(67)
0.134;-25190.0
67(78)
0.173;-32120.0
77(6J)
0.139;-29810.0
677K
0.168;-33310.0
7T(68)
0.144;-34850.0
(68)(7K)
0.188;-27500.0
6T(78)
0.111;-34850.0
6(78K)
0.147;-32540.0
68(7T)
0.122;-34850.0
68(7Q)
0.122;-33310.0
79(69)
0.173;-29810.0
(69)(7Q)
0.229;-27500.0
6T(79)
0.162;-34080.0
6(79K)
0.183;-31770.0
69(7J)
0.179;-33310.0
69(7K)
0.158;-31770.0
7(6TQ)
0.168;-31770.0
6(7TJ)
0.155;-32540.0
67TT
0.196;-33310.0
67TQ
0.147;-36810.0
(6J)(7Q)
0.232;-25960.0
6Q(7J)
0.125;-31000.0
67JQ
0.155;-36040.0
(6Q)(7K)
0.198;-24420.0
6Q(7K)
0.169;-29460.0
8(689)
0.158;-29810.0
8J(68)
0.164;-28270.0
(689T)
0.122;-33310.0
99(68)
0.139;-29040.0
(68)(9Q)
0.171;-26730.0
(68TQ)
0.185;-31000.0
T(68Q)
0.142;-31000.0
Q(68J)
0.119;-30230.0
(68)(JK)
0.220;-24420.0
QK(68)
0.171;-28690.0
68(8T)
0.152;-29040.0
88(6K)
0.174;-26730.0
8(69J)
0.176;-32540.0
8K(69)
0.181;-31000.0
(89)(6Q)
0.173;-26730.0
69(8T)
0.118;-33310.0
69(8Q)
0.129;-31770.0
8T(6T)
0.145;-27500.0
(6T)(8K)
0.194;-25190.0
6Q(8T)
0.139;-31000.0
68TJ
0.149;-36810.0
68TK
0.126;-35270.0
8K(6J)
0.153;-29460.0
68JJ
0.212;-31000.0
68JK
0.135;-34500.0
6(8QK)
0.174;-28690.0
8K(6K)
0.160;-22880.0
(69)(9J)
0.224;-21690.0
T(69T)
0.163;-26730.0
T(69J)
0.161;-31000.0
TK(69)
0.157;-29460.0
(69)(JQ)
0.149;-24420.0
QQ(69)
0.151;-23650.0
69(9T)
0.161;-27500.0
99(6K)
0.181;-25190.0
9(6TQ)
0.151;-30230.0
6(9TJ)
0.120;-31000.0
69TT
0.166;-31770.0
69TQ
0.165;-35270.0
(6J)(9Q)
0.180;-24420.0
6Q(9J)
0.167;-29460.0
69JQ
0.161;-34500.0
(6Q)(9K)
0.209;-22880.0
6Q(9K)
0.207;-27920.0
T(6TJ)
0.190;-25190.0
TK(6T)
0.177;-23650.0
(6T)(JQ)
0.205;-23650.0
QQ(6T)
0.168;-22880.0
6T(TJ)
0.164;-25190.0
(6J)(TJ)
0.208;-19380.0
6J(TJ)
0.200;-24420.0
TJ(6Q)
0.147;-28690.0
(6Q)(TQ)
0.267;-17840.0
6K(TQ)
0.139;-27150.0
6K(TK)
0.221;-21340.0
JK(6J)
0.193;-22110.0
K(6JK)
0.213;-20570.0
6JJK
0.159;-27150.0
6(JQK)
0.206;-26380.0
JK(6K)
0.224;-20570.0
KK(6Q)
0.227;-19800.0
6QKK
0.217;-24840.0
77(7T)
0.202;-24770.0
(78)(78)
0.205;-20500.0
7(78J)
0.158;-28270.0
7K(78)
0.154;-26730.0
78(7J)
0.160;-28270.0
778K
0.128;-31770.0
7J(79)
0.195;-27500.0
79(7T)
0.173;-28270.0
779Q
0.158;-31770.0
7J(7T)
0.164;-26730.0
7T(7J)
0.143;-26730.0
77TK
0.160;-30230.0
7K(7J)
0.196;-24420.0
(7Q)(7Q)
0.223;-14340.0
77QK
0.185;-28690.0
8(78T)
0.151;-28270.0
8Q(78)
0.195;-26730.0
J(789)
0.151;-31770.0
9T(78)
0.143;-32540.0
(78)(9K)
0.152;-25190.0
K(78T)
0.171;-29460.0
T(78K)
0.179;-29460.0
JJ(78)
0.167;-25190.0
(78QK)
0.209;-27920.0
7888
0.144;-29810.0
78(8J)
0.154;-27500.0
(79)(89)
0.165;-23230.0
8(79Q)
0.156;-31000.0
7(89T)
0.162;-32540.0
(89)(7K)
0.142;-25190.0
89(7J)
0.175;-31770.0
89(7K)
0.158;-30230.0
8J(7T)
0.135;-31000.0
(8T)(7J)
0.183;-25960.0
7K(8T)
0.143;-29460.0
78(TQ)
0.189;-30230.0
8(7JQ)
0.162;-29460.0
7(8JQ)
0.156;-29460.0
78(JQ)
0.152;-29460.0
8(7QK)
0.137;-27920.0
8Q(7K)
0.180;-27920.0
99(79)
0.182;-22460.0
(79)(9Q)
0.251;-20150.0
(79TQ)
0.140;-29460.0
T(79Q)
0.200;-29460.0
Q(79J)
0.125;-28690.0
(79)(JK)
0.155;-22880.0
QK(79)
0.179;-27150.0
79(9J)
0.200;-25960.0
(7T)(9T)
0.235;-20920.0
9(7TK)
0.160;-28690.0
7(9TQ)
0.188;-29460.0
79(TJ)
0.154;-30230.0
79(TK)
0.159;-28690.0
(7J)(9K)
0.222;-22880.0
7K(9J)
0.205;-27920.0
79(JK)
0.166;-27920.0
(9Q)(7K)
0.211;-22110.0
(7K)(9K)
0.199;-16300.0
T(7TQ)
0.177;-23650.0
Q(7TJ)
0.172;-27920.0
(7T)(JK)
0.163;-22110.0
QK(7T)
0.179;-26380.0
7T(TQ)
0.198;-23650.0
(7J)(TQ)
0.203;-22880.0
7Q(TJ)
0.151;-27920.0
7TJQ
0.149;-32960.0
(7Q)(TK)
0.211;-21340.0
7Q(TK)
0.189;-26380.0
J(7JQ)
0.207;-22110.0
K(7JQ)
0.221;-25610.0
JJ(7Q)
0.189;-22110.0
J(7QK)
0.165;-25610.0
JQ(7K)
0.134;-25610.0
QQ(7Q)
0.217;-15530.0
7Q(QK)
0.195;-19800.0
8888
0.162;-24000.0
888Q
0.149;-25960.0
8(89J)
0.165;-25960.0
8K(89)
0.165;-24420.0
89(8Q)
0.163;-25190.0
8(8TJ)
0.208;-25190.0
8K(8T)
0.186;-23650.0
8T(8K)
0.188;-23650.0
8(8JK)
0.193;-22880.0
88(JK)
0.177;-22880.0
8Q(8K)
0.220;-22110.0
(89)(9T)
0.191;-20920.0
9(89K)
0.185;-23650.0
(89TK)
0.190;-27920.0
TQ(89)
0.155;-28690.0
K(89J)
0.142;-27150.0
Q(89Q)
0.220;-22110.0
KK(89)
0.227;-20570.0
99(8Q)
0.211;-24420.0
9(8TJ)
0.174;-29460.0
9K(8T)
0.176;-27920.0
(9T)(8K)
0.169;-22880.0
9T(8Q)
0.134;-28690.0
(8J)(9J)
0.187;-18610.0
8J(9J)
0.166;-23650.0
9J(8Q)
0.183;-27920.0
(8Q)(9Q)
0.235;-17070.0
8K(9Q)
0.173;-26380.0
8K(9K)
0.187;-20570.0
TQ(8T)
0.163;-22880.0
K(8TJ)
0.174;-26380.0
Q(8TQ)
0.211;-21340.0
KK(8T)
0.195;-19800.0
