AAAA
0.390;1650.0
5AAA
0.332;581.3
9AAA
0.335;856.3
KAAA
0.380;1131.3
4A(2A)
0.251;-312.5
(2A)(7A)
0.366;343.7
A(2TA)
0.312;100.0
QA(2A)
0.380;237.5
2A(4A)
0.351;-312.5
26AA
0.224;-625.0
AA(29)
0.327;31.3
2A(QA)
0.367;237.5
A(34A)
0.296;-243.7
6A(3A)
0.301;-106.2
(3A)(9A)
0.332;550.0
A(3QA)
0.391;306.2
AA(34)
0.295;-243.7
3A(7A)
0.290;-37.5
39AA
0.313;-350.0
AA(3Q)
0.380;306.2
(4A)(5A)
0.291;343.7
A(48A)
0.326;100.0
TA(4A)
0.363;237.5
(4A)(KA)
0.401;893.8
46AA
0.271;-487.5
AA(49)
0.278;168.8
4A(QA)
0.302;375.0
A(56A)
0.347;31.3
8A(5A)
0.247;168.8
(5A)(JA)
0.298;825.0
55AA
0.283;-37.5
AA(58)
0.326;168.8
5A(JA)
0.331;375.0
5KAA
0.319;62.5
8A(6A)
0.343;237.5
(6A)(JA)
0.326;893.8
66AA
0.281;100.0
AA(69)
0.298;306.2
6A(QA)
0.355;512.5
A(78A)
0.325;306.2
TA(7A)
0.311;443.8
(7A)(KA)
0.349;1100.0
79AA
0.294;-75.0
AA(7Q)
0.362;581.2
(8A)(9A)
0.374;893.8
A(8QA)
0.356;650.0
AA(89)
0.313;443.8
8A(QA)
0.321;650.0
A(9TA)
0.313;581.2
QA(9A)
0.406;718.7
9A(JA)
0.310;650.0
9KAA
0.306;337.5
QA(TA)
0.310;787.5
TA(QA)
0.379;787.5
A(JQA)
0.333;856.2
AA(JQ)
0.354;856.2
(QA)(KA)
0.318;1443.7
KKAA
0.311;1062.5
2(25A)
0.207;-1068.7
27(2A)
0.284;-931.2
(2T)(2A)
0.250;-275.0
2(2KA)
0.265;-518.7
(236A)
0.273;-1381.2
(23TA)
0.274;-1106.2
33(2A)
0.205;-1137.5
(36)(2A)
0.216;-931.2
3(29A)
0.276;-1175.0
3J(2A)
0.267;-1037.5
(245A)
0.198;-1381.2
(249A)
0.306;-1106.2
(24KA)
0.260;-831.2
46(2A)
0.293;-1312.5
(49)(2A)
0.286;-656.2
4(2QA)
0.267;-900.0
6(25A)
0.265;-1243.8
T(25A)
0.250;-968.7
5(26A)
0.259;-1243.8
58(2A)
0.288;-1106.2
(5J)(2A)
0.331;-450.0
6(26A)
0.308;-725.0
T(26A)
0.222;-900.0
6(27A)
0.221;-1106.2
69(2A)
0.230;-968.7
(6Q)(2A)
0.317;-312.5
(279A)
0.251;-900.0
(27KA)
0.316;-625.0
79(2A)
0.303;-900.0
(7Q)(2A)
0.267;-243.8
(28TA)
0.236;-762.5
88(2A)
0.265;-450.0
(8J)(2A)
0.363;-243.8
9(29A)
0.290;-312.5
K(29A)
0.268;-487.5
9(2QA)
0.253;-556.2
J(2TA)
0.244;-556.2
TJ(2A)
0.268;-556.2
(2JQA)
0.276;-418.7
J(2KA)
0.329;-350.0
(QK)(2A)
0.308;168.8
22(4A)
0.241;-1137.5
226A
0.258;-1450.0
2A(29)
0.294;-793.7
22(QA)
0.240;-587.5
2(34A)
0.238;-1518.8
26(3A)
0.252;-1381.2
(29)(3A)
0.304;-725.0
2(3QA)
0.309;-968.7
A(234)
0.228;-1518.8
(23)(7A)
0.282;-862.5
9A(23)
0.225;-1175.0
A(23Q)
0.269;-968.7
2A(34)
0.220;-1518.8
2A(36)
0.262;-1381.2
2A(38)
0.209;-1243.8
2A(3T)
0.217;-1106.2
2A(3Q)
0.268;-968.7
2(45A)
0.302;-1381.2
27(4A)
0.193;-1243.8
(2T)(4A)
0.322;-587.5
2(4KA)
0.254;-831.2
A(246)
0.187;-1312.5
(24)(9A)
0.279;-656.2
JA(24)
0.254;-968.7
24(5A)
0.299;-1381.2
24(7A)
0.241;-1243.8
24(9A)
0.247;-1106.2
24(JA)
0.288;-968.7
24(KA)
0.290;-831.2
26(5A)
0.283;-1243.8
(29)(5A)
0.258;-587.5
2(5QA)
0.327;-831.2
A(256)
0.206;-1243.8
(25)(9A)
0.292;-587.5
JA(25)
0.296;-900.0
25(6A)
0.286;-1243.8
25(8A)
0.268;-1106.2
25(TA)
0.278;-968.7
25(QA)
0.241;-831.2
(26)(6A)
0.289;-275.0
2(69A)
0.298;-968.7
2J(6A)
0.294;-831.2
(26)(7A)
0.212;-656.2
9A(26)
0.226;-968.7
A(26Q)
0.258;-762.5
2A(67)
0.293;-1106.2
2A(69)
0.245;-968.7
2A(6J)
0.272;-831.2
2A(6K)
0.262;-693.7
(29)(7A)
0.357;-450.0
2(7QA)
0.282;-693.7
A(278)
0.217;-968.7
(27)(JA)
0.257;-312.5
KA(27)
0.344;-625.0
2A(79)
0.329;-900.0
2A(7J)
0.215;-762.5
2A(7K)
0.262;-625.0
(2T)(8A)
0.343;-312.5
2(8KA)
0.317;-556.2
A(28T)
0.302;-762.5
(28)(KA)
0.295;-106.2
28(TA)
0.257;-762.5
28(QA)
0.332;-625.0
(29)(9A)
0.295;137.5
2(9QA)
0.240;-556.2
A(29T)
0.282;-693.7
(29)(KA)
0.321;-37.5
29(JA)
0.299;-625.0
29(KA)
0.288;-487.5
2J(TA)
0.350;-556.2
(2T)(JA)
0.320;-106.2
KA(2T)
0.262;-418.7
2A(TQ)
0.274;-487.5
2(JQA)
0.282;-418.7
A(2JQ)
0.253;-418.7
2A(JQ)
0.333;-418.7
2(QKA)
0.322;-281.2
2Q(KA)
0.268;-281.2
33(3A)
0.290;-618.7
(36)(3A)
0.270;-412.5
3(39A)
0.231;-656.2
3J(3A)
0.270;-518.7
(345A)
0.207;-1312.5
(349A)
0.291;-1037.5
(34KA)
0.258;-762.5
46(3A)
0.300;-1243.8
(49)(3A)
0.296;-587.5
4(3QA)
0.244;-831.2
6(35A)
0.256;-1175.0
T(35A)
0.248;-900.0
5(36A)
0.248;-1175.0
58(3A)
0.276;-1037.5
(5J)(3A)
0.274;-381.2
6(36A)
0.288;-656.2
T(36A)
0.285;-831.2
6(37A)
0.253;-1037.5
69(3A)
0.255;-900.0
(6Q)(3A)
0.309;-243.8
(379A)
0.270;-831.2
(37KA)
0.330;-556.2
79(3A)
0.261;-831.2
(7Q)(3A)
0.235;-175.0
(38TA)
0.256;-693.7
88(3A)
0.324;-381.2
(8J)(3A)
0.335;-175.0
9(39A)
0.303;-243.7
K(39A)
0.255;-418.7
9(3QA)
0.260;-487.5
J(3TA)
0.256;-487.5
TJ(3A)
0.287;-487.5
(3JQA)
0.241;-350.0
J(3KA)
0.290;-281.2
(QK)(3A)
0.272;237.5
33(5A)
0.269;-931.2
337A
0.255;-1243.8
3A(3T)
0.280;-587.5
33(KA)
0.272;-381.2
3(46A)
0.232;-1243.8
38(4A)
0.267;-1106.2
(3J)(4A)
0.252;-450.0
4A(34)
0.259;-931.2
A(347)
0.202;-1175.0
(34)(TA)
0.246;-518.7
QA(34)
0.243;-831.2
345A
0.241;-1762.5
347A
0.260;-1625.0
349A
0.233;-1487.5
34JA
0.212;-1350.0
34KA
0.203;-1212.5
37(5A)
0.224;-1106.2
(3T)(5A)
0.316;-450.0
3(5KA)
0.237;-693.7
A(357)
0.273;-1106.2
(35)(TA)
0.293;-450.0
QA(35)
0.248;-762.5
356A
0.174;-1625.0
358A
0.218;-1487.5
35TA
0.224;-1350.0
35QA
0.201;-1212.5
(37)(6A)
0.293;-587.5
3(6TA)
0.205;-831.2
3Q(6A)
0.252;-693.7
(36)(8A)
0.268;-518.7
TA(36)
0.257;-831.2
A(36K)
0.277;-625.0
6A(38)
0.257;-968.7
6A(3T)
0.240;-831.2
6A(3Q)
0.335;-693.7
37(7A)
0.313;-518.7
(3T)(7A)
0.304;-312.5
3(7KA)
0.287;-556.2
A(379)
0.226;-831.2
(37)(QA)
0.259;-175.0
7A(38)
0.302;-900.0
7A(3T)
0.222;-762.5
7A(3Q)
0.285;-625.0
38(8A)
0.345;-381.2
(3J)(8A)
0.265;-175.0
8A(38)
0.310;-381.2
A(38J)
0.275;-625.0
388A
0.251;-831.2
38TA
0.220;-1143.8
38QA
0.230;-1006.3
(3T)(9A)
0.268;-175.0
3(9KA)
0.342;-418.7
A(39J)
0.250;-556.2
399A
0.246;-693.7
39JA
0.275;-1006.3
39KA
0.252;-868.7
3Q(TA)
0.323;-418.7
(3T)(QA)
0.318;31.3
TA(3J)
0.288;-487.5
TA(3K)
0.333;-350.0
3(JKA)
0.270;-281.2
A(3JK)
0.335;-281.2
JA(3K)
0.270;-281.2
QA(3Q)
0.311;168.8
3QKA
0.338;-662.5
45(4A)
0.271;-793.7
(48)(4A)
0.353;-137.5
4(4JA)
0.257;-381.2
4K(4A)
0.351;-243.7
(459A)
0.214;-900.0
(45KA)
0.246;-625.0
57(4A)
0.271;-1037.5
(5T)(4A)
0.298;-381.2
5(4KA)
0.268;-625.0
(469A)
0.277;-831.2
(46KA)
0.309;-556.2
68(4A)
0.227;-900.0
(6J)(4A)
0.328;-243.8
7(47A)
0.310;-450.0
J(47A)
0.236;-625.0
78(4A)
0.247;-831.2
(7J)(4A)
0.308;-175.0
8(48A)
0.253;-312.5
Q(48A)
0.296;-487.5
(8T)(4A)
0.245;-175.0
8(4KA)
0.262;-418.7
(49QA)
0.231;-418.7
9(4JA)
0.290;-487.5
9K(4A)
0.222;-350.0
TT(4A)
0.344;-37.5
(TK)(4A)
0.297;168.8
J(4QA)
0.289;-281.2
K(4QA)
0.333;-143.7
44(5A)
0.300;-793.7
447A
0.257;-1106.2
4A(4T)
0.324;-450.0
44(KA)
0.336;-243.7
4(57A)
0.277;-1037.5
49(5A)
0.262;-900.0
(4Q)(5A)
0.304;-243.8
6A(45)
0.277;-1106.2
A(459)
0.271;-900.0
(45)(QA)
0.276;-243.8
5A(46)
0.249;-1106.2
5A(48)
0.229;-968.7
5A(4T)
0.240;-831.2
5A(4Q)
0.251;-693.7
46(6A)
0.267;-587.5
(49)(6A)
0.283;-381.2
4(6QA)
0.307;-625.0
A(467)
0.290;-968.7
(46)(TA)
0.314;-312.5
QA(46)
0.295;-625.0
467A
0.222;-1418.7
469A
0.231;-1281.2
46JA
0.217;-1143.8
46KA
0.282;-1006.3
49(7A)
0.299;-762.5
(4Q)(7A)
0.293;-106.2
8A(47)
0.317;-831.2
A(47J)
0.273;-625.0
477A
0.264;-900.0
479A
0.242;-1212.5
47JA
0.219;-1075.0
47KA
0.227;-937.5
4T(8A)
0.268;-625.0
(4K)(8A)
0.281;31.3
TA(48)
0.305;-625.0
A(48K)
0.362;-418.7
8A(4T)
0.340;-625.0
8A(4Q)
0.338;-487.5
49(9A)
0.253;-175.0
(4Q)(9A)
0.325;31.3
TA(49)
0.337;-556.2
A(49K)
0.284;-350.0
9A(4J)
0.245;-487.5
9A(4K)
0.324;-350.0
4(TQA)
0.302;-350.0
A(4TJ)
0.368;-418.7
4TTA
0.246;-487.5
4TQA
0.280;-800.0
(4Q)(JA)
0.317;168.8
QA(4J)
0.300;-281.2
4JQA
0.255;-731.2
(4K)(QA)
0.282;306.2
QA(4K)
0.335;-143.7
5(56A)
0.292;-587.5
58(5A)
0.251;-450.0
(5J)(5A)
0.374;206.3
6(56A)
0.221;-518.7
T(56A)
0.246;-693.7
6(57A)
0.275;-900.0
69(5A)
0.293;-762.5
(6Q)(5A)
0.329;-106.2
(579A)
0.229;-693.7
(57KA)
0.298;-418.7
79(5A)
0.264;-693.7
(7Q)(5A)
0.274;-37.5
(58TA)
0.315;-556.2
88(5A)
0.293;-243.7
(8J)(5A)
0.285;-37.5
9(59A)
0.335;-106.2
K(59A)
0.273;-281.2
9(5QA)
0.364;-350.0
J(5TA)
0.257;-350.0
TJ(5A)
0.228;-350.0
(5JQA)
0.299;-212.5
J(5KA)
0.230;-143.7
(QK)(5A)
0.326;375.0
55(7A)
0.296;-518.7
559A
0.234;-831.2
5A(5Q)
0.369;-175.0
(57)(6A)
0.326;-450.0
5(6TA)
0.309;-693.7
5Q(6A)
0.296;-556.2
(56)(8A)
0.241;-381.2
TA(56)
0.308;-693.7
A(56K)
0.278;-487.5
6A(58)
0.261;-831.2
6A(5T)
0.243;-693.7
6A(5Q)
0.306;-556.2
57(7A)
0.338;-381.2
(5T)(7A)
0.272;-175.0
5(7KA)
0.278;-418.7
A(579)
0.279;-693.7
(57)(QA)
0.287;-37.5
7A(58)
0.240;-762.5
7A(5T)
0.286;-625.0
7A(5Q)
0.260;-487.5
58(8A)
0.293;-243.7
(5J)(8A)
0.384;-37.5
8A(58)
0.293;-243.7
A(58J)
0.351;-487.5
588A
0.275;-693.7
58TA
0.218;-1006.3
58QA
0.277;-868.7
(5T)(9A)
0.277;-37.5
5(9KA)
0.237;-281.2
A(59J)
0.330;-418.7
599A
0.319;-556.2
59JA
0.278;-868.7
59KA
0.322;-731.2
5Q(TA)
0.291;-281.2
(5T)(QA)
0.376;168.8
TA(5J)
0.285;-350.0
TA(5K)
0.310;-212.5
5(JKA)
0.289;-143.7
A(5JK)
0.301;-143.7
JA(5K)
0.271;-143.7
QA(5Q)
0.339;306.2
5QKA
0.352;-525.0
67(6A)
0.290;-381.2
(6T)(6A)
0.302;275.0
6(6KA)
0.312;31.3
(67TA)
0.259;-556.2
77(6A)
0.298;-312.5
(7T)(6A)
0.296;-106.2
7(6KA)
0.294;-350.0
(68JA)
0.256;-418.7
(89)(6A)
0.294;-106.2
8(6QA)
0.269;-350.0
T(69A)
0.285;-418.7
9(6TA)
0.270;-418.7
9Q(6A)
0.284;-281.2
Q(6TA)
0.325;-212.5
(TQ)(6A)
0.353;237.5
(6JKA)
0.256;-75.0
JK(6A)
0.299;-75.0
K(6KA)
0.308;512.5
668A
0.297;-762.5
6A(6J)
0.340;-106.2
(67)(7A)
0.316;137.5
6(7TA)
0.304;-556.2
6Q(7A)
0.325;-418.7
(67)(9A)
0.336;-175.0
JA(67)
0.307;-487.5
67(8A)
0.304;-693.7
67(TA)
0.231;-556.2
67(QA)
0.345;-418.7
(68)(8A)
0.340;275.0
6(8JA)
0.301;-418.7
6K(8A)
0.282;-281.2
(68)(JA)
0.326;31.3
KA(68)
0.246;-281.2
6A(8T)
0.334;-487.5
6A(8Q)
0.317;-350.0
6(9TA)
0.299;-418.7
6Q(9A)
0.235;-281.2
(69)(JA)
0.335;100.0
KA(69)
0.348;-212.5
6A(9J)
0.325;-350.0
6A(9K)
0.268;-212.5
(6Q)(TA)
0.300;237.5
JA(6T)
0.348;-281.2
6T(JA)
0.278;-281.2
6T(KA)
0.346;-143.7
6Q(JA)
0.294;-143.7
(6J)(KA)
0.321;375.0
6J(KA)
0.272;-75.0
6K(QA)
0.309;-6.2
6A(QK)
0.328;-6.2
(78)(7A)
0.319;275.0
7(7JA)
0.257;31.3
7K(7A)
0.291;168.8
(78QA)
0.289;-281.2
8(7TA)
0.344;-418.7
8Q(7A)
0.338;-281.2
J(79A)
0.305;-281.2
9T(7A)
0.271;-350.0
(9K)(7A)
0.284;306.2
K(7TA)
0.249;-75.0
T(7KA)
0.258;-75.0
JJ(7A)
0.327;306.2
(7QKA)
0.327;62.5
777A
0.363;-243.8
7A(7T)
0.311;-37.5
77(KA)
0.302;168.8
7(8TA)
0.268;-418.7
7Q(8A)
0.316;-281.2
(78)(TA)
0.272;31.3
QA(78)
0.319;-281.2
789A
0.245;-937.5
78JA
0.243;-800.0
78KA
0.315;-662.5
7J(9A)
0.309;-281.2
(79)(TA)
0.347;100.0
QA(79)
0.282;-212.5
79TA
0.238;-800.0
79QA
0.238;-662.5
(7J)(TA)
0.330;237.5
TA(7T)
0.312;168.8
A(7TK)
0.321;-75.0
TA(7Q)
0.297;-143.7
7J(JA)
0.335;306.2
(7J)(QA)
0.339;375.0
JA(7Q)
0.346;-75.0
7Q(QA)
0.313;443.8
7QQA
0.373;-6.2
7KKA
0.285;131.2
8(8JA)
0.294;168.8
8K(8A)
0.361;306.2
(89KA)
0.366;-75.0
9J(8A)
0.290;-212.5
(8TJA)
0.317;-143.7
(TJ)(8A)
0.264;306.2
J(8JA)
0.338;375.0
JQ(8A)
0.295;-6.2
Q(8KA)
0.334;131.2
889A
0.336;-418.7
8A(8Q)
0.332;237.5
(8T)(9A)
0.315;168.8
8(9KA)
0.374;-75.0
A(89J)
0.333;-212.5
899A
0.246;-350.0
89JA
0.277;-662.5
89KA
0.279;-525.0
8Q(TA)
0.305;-75.0
(8T)(QA)
0.336;375.0
TA(8J)
0.304;-143.7
TA(8K)
0.308;-6.2
8(JKA)
0.374;62.5
A(8JK)
0.334;62.5
JA(8K)
0.330;62.5
QA(8Q)
0.309;512.5
8QKA
0.298;-318.7
9T(9A)
0.331;237.5
(9K)(9A)
0.365;893.8
K(9TA)
0.325;62.5
T(9KA)
0.334;62.5
JJ(9A)
0.316;443.8
(9QKA)
0.318;200.0
999A
0.317;168.8
9A(9Q)
0.282;375.0
(9J)(TA)
0.324;375.0
TA(9T)
0.342;306.2
A(9TK)
0.249;62.5
TA(9Q)
0.358;-6.2
9J(JA)
0.297;443.8
(9J)(QA)
0.371;512.5
JA(9Q)
0.376;62.5
9Q(QA)
0.264;581.2
9QQA
0.339;131.2
9KKA
0.306;268.8
T(TKA)
0.369;581.2
JJ(TA)
0.353;512.5
(TQKA)
0.314;268.8
TTTA
0.351;375.0
TA(TK)
0.337;581.2
(TK)(JA)
0.341;650.0
KA(TJ)
0.340;200.0
TA(JK)
0.285;200.0
(TQ)(KA)
0.371;718.7
(TK)(KA)
0.392;1237.5
J(JKA)
0.382;718.7
(QK)(JA)
0.371;787.5
JJ(KA)
0.388;718.7
QA(JQ)
0.384;718.7
JQKA
0.370;-112.5
QK(QA)
0.351;856.2
QK(KA)
0.328;925.0
22(24)
0.192;-1512.5
22(28)
0.266;-1237.5
22(2Q)
0.266;-962.5
24(23)
0.232;-1893.7
(23)(27)
0.254;-1237.5
2(23T)
0.246;-1481.2
2Q(23)
0.206;-1343.7
23(25)
0.212;-1825.0
2237
0.169;-2137.5
22(3T)
0.240;-1481.2
23(2K)
0.260;-1275.0
2(246)
0.260;-1687.5
28(24)
0.256;-1550.0
(24)(2J)
0.210;-893.7
2244
0.238;-1825.0
22(47)
0.243;-1618.8
24(2T)
0.277;-1412.5
224Q
0.215;-1725.0
26(25)
0.220;-1618.8
(25)(29)
0.217;-962.5
2(25Q)
0.210;-1206.2
22(56)
0.265;-1618.8
25(29)
0.214;-1412.5
225J
0.213;-1725.0
26(26)
0.281;-1100.0
(26)(29)
0.295;-893.7
2(26Q)
0.301;-1137.5
22(67)
0.229;-1481.2
26(2T)
0.269;-1275.0
226Q
0.172;-1587.5
28(27)
0.250;-1343.7
(27)(2J)
0.254;-687.5
2277
0.209;-1412.5
22(7T)
0.199;-1206.2
27(2K)
0.233;-1000.0
2(28T)
0.293;-1137.5
2Q(28)
0.229;-1000.0
28(2T)
0.199;-1137.5
228Q
0.301;-1450.0
2T(29)
0.251;-1068.7
(29)(2K)
0.304;-412.5
229J
0.284;-1450.0
2T(2T)
0.309;-550.0
(2T)(2K)
0.274;-343.7
22TQ
0.204;-1312.5
2Q(2J)
0.265;-793.7
2J(2K)
0.259;-725.0
22QQ
0.242;-725.0
3(234)
0.197;-1825.0
36(23)
0.218;-1687.5
(23)(39)
0.247;-1031.2
3(23Q)
0.272;-1275.0
5(234)
0.202;-2137.5
9(234)
0.164;-1862.5
K(234)
0.254;-1587.5
4(237)
0.170;-2000.0
49(23)
0.225;-1862.5
(23)(4Q)
0.277;-1206.2
(2357)
0.218;-1931.2
(235J)
0.226;-1656.3
(23)(56)
0.226;-1550.0
5(239)
0.205;-1793.7
5J(23)
0.245;-1656.3
(2367)
0.199;-1862.5
(236J)
0.190;-1587.5
(23)(67)
0.240;-1412.5
6(23T)
0.215;-1656.3
6Q(23)
0.221;-1518.8
9(237)
0.209;-1656.3
K(237)
0.217;-1381.2
7(23T)
0.193;-1587.5
7Q(23)
0.244;-1450.0
T(238)
0.218;-1518.8
8(239)
0.204;-1587.5
8J(23)
0.289;-1450.0
(239T)
0.214;-1450.0
99(23)
0.222;-1068.7
(23)(9Q)
0.293;-862.5
(23TQ)
0.234;-1243.8
T(23Q)
0.248;-1243.8
Q(23J)
0.238;-1175.0
(23)(JK)
0.230;-656.2
QK(23)
0.300;-1037.5
23(35)
0.242;-1756.2
33(28)
0.183;-1550.0
233T
0.217;-1862.5
23(3K)
0.311;-1206.2
(24)(36)
0.240;-1618.8
3(249)
0.244;-1862.5
3J(24)
0.189;-1725.0
(34)(25)
0.219;-1687.5
27(34)
0.228;-2000.0
2(34T)
0.233;-1793.7
(34)(2K)
0.205;-1137.5
34(26)
0.187;-2068.7
34(28)
0.207;-1931.2
34(2T)
0.178;-1793.7
34(2Q)
0.189;-1656.3
(25)(35)
0.195;-1168.8
3(258)
0.248;-1862.5
3T(25)
0.241;-1725.0
(25)(3K)
0.266;-1068.7
27(35)
0.198;-1931.2
2(35T)
0.226;-1725.0
(35)(2K)
0.281;-1068.7
35(27)
0.240;-1931.2
35(29)
0.197;-1793.7
35(2J)
0.212;-1656.3
35(2K)
0.179;-1518.8
37(26)
0.254;-1862.5
(26)(3T)
0.235;-1206.2
3(26K)
0.193;-1450.0
2(368)
0.248;-1793.7
(36)(2J)
0.294;-1137.5
2K(36)
0.270;-1450.0
23(68)
0.203;-1793.7
23(6T)
0.185;-1656.3
23(6Q)
0.210;-1518.8
3(278)
0.254;-1725.0
3T(27)
0.249;-1587.5
(27)(3K)
0.249;-931.2
29(37)
0.256;-1656.3
2(37Q)
0.188;-1450.0
23(78)
0.199;-1725.0
23(7T)
0.181;-1587.5
23(7Q)
0.181;-1450.0
3(289)
0.278;-1587.5
3J(28)
0.202;-1450.0
(38)(29)
0.266;-1137.5
2J(38)
0.241;-1450.0
38(29)
0.233;-1587.5
38(2J)
0.251;-1450.0
38(2K)
0.257;-1312.5
3T(29)
0.211;-1450.0
(29)(3K)
0.240;-793.8
2J(39)
0.253;-1381.2
39(2T)
0.221;-1450.0
39(2Q)
0.196;-1312.5
(2T)(3T)
0.309;-481.2
3(2TK)
0.207;-1175.0
2(3TQ)
0.234;-1243.8
23(TJ)
0.212;-1312.5
23(TK)
0.212;-1175.0
(2J)(3K)
0.236;-656.2
2K(3J)
0.201;-1106.2
23(JK)
0.243;-1106.2
(3Q)(2K)
0.308;-587.5
(2K)(3K)
0.341;-68.8
4(246)
0.236;-1550.0
48(24)
0.292;-1412.5
(24)(4J)
0.232;-756.3
5(245)
0.218;-1550.0
9(245)
0.195;-1725.0
K(245)
0.256;-1450.0
5(248)
0.218;-1793.7
5T(24)
0.245;-1656.3
(24)(5K)
0.251;-1000.0
9(246)
0.297;-1656.3
K(246)
0.285;-1381.2
6(249)
0.166;-1656.3
6J(24)
0.224;-1518.8
(2478)
0.226;-1656.3
(247Q)
0.199;-1381.2
7(249)
0.269;-1587.5
7J(24)
0.221;-1450.0
(2489)
0.235;-1518.8
(248K)
0.207;-1243.8
8T(24)
0.228;-1450.0
(24)(8K)
0.323;-793.8
Q(249)
0.251;-1243.8
(24)(9J)
0.282;-862.5
T(24T)
0.271;-862.5
T(24J)
0.268;-1243.8
TK(24)
0.200;-1106.2
(24)(JQ)
0.303;-656.2
QQ(24)
0.334;-587.5
24(45)
0.248;-1618.8
44(28)
0.263;-1412.5
244T
0.262;-1725.0
24(4K)
0.243;-1068.7
(25)(47)
0.192;-1412.5
4(25T)
0.195;-1656.3
4Q(25)
0.173;-1518.8
(45)(27)
0.224;-1412.5
29(45)
0.267;-1725.0
2(45Q)
0.259;-1518.8
24(56)
0.220;-1931.2
24(58)
0.176;-1793.7
24(5T)
0.184;-1656.3
24(5Q)
0.271;-1518.8
4(267)
0.212;-1793.7
49(26)
0.199;-1656.3
(26)(4Q)
0.251;-1000.0
27(46)
0.214;-1793.7
2(46T)
0.264;-1587.5
(46)(2K)
0.280;-931.2
46(28)
0.232;-1725.0
46(2T)
0.235;-1587.5
46(2Q)
0.194;-1450.0
(27)(47)
0.330;-825.0
4(27T)
0.265;-1518.8
4Q(27)
0.200;-1381.2
(47)(29)
0.295;-1137.5
2J(47)
0.182;-1450.0
47(28)
0.228;-1656.3
47(2T)
0.219;-1518.8
47(2Q)
0.263;-1381.2
(28)(48)
0.284;-687.5
4(28J)
0.255;-1381.2
4K(28)
0.229;-1243.8
(48)(2J)
0.261;-931.2
2K(48)
0.255;-1243.8
24(8T)
0.215;-1450.0
24(8Q)
0.252;-1312.5
4(29T)
0.232;-1381.2
4Q(29)
0.232;-1243.8
(49)(2J)
0.293;-862.5
2K(49)
0.273;-1175.0
24(9J)
0.235;-1312.5
24(9K)
0.284;-1175.0
(2T)(4Q)
0.294;-725.0
2J(4T)
0.255;-1243.8
4T(2J)
0.279;-1243.8
4T(2K)
0.262;-1106.2
4Q(2J)
0.257;-1106.2
(4J)(2K)
0.323;-587.5
4J(2K)
0.244;-1037.5
4K(2Q)
0.259;-968.7
24(QK)
0.249;-968.7
(25)(56)
0.256;-962.5
5(259)
0.228;-1206.2
5J(25)
0.215;-1068.7
(2567)
0.287;-1725.0
(256J)
0.200;-1450.0
(25)(67)
0.273;-1275.0
6(25T)
0.230;-1518.8
6Q(25)
0.231;-1381.2
9(257)
0.283;-1518.8
K(257)
0.265;-1243.8
7(25T)
0.275;-1450.0
7Q(25)
0.254;-1312.5
T(258)
0.276;-1381.2
8(259)
0.210;-1450.0
8J(25)
0.232;-1312.5
(259T)
0.239;-1312.5
99(25)
0.269;-931.2
(25)(9Q)
0.294;-725.0
(25TQ)
0.189;-1106.2
T(25Q)
0.211;-1106.2
Q(25J)
0.219;-1037.5
(25)(JK)
0.286;-518.7
QK(25)
0.300;-900.0
25(57)
0.205;-1343.7
55(2T)
0.223;-1137.5
255Q
0.207;-1450.0
57(26)
0.237;-1725.0
(26)(5T)
0.236;-1068.7
5(26K)
0.252;-1312.5
2(568)
0.175;-1656.3
(56)(2J)
0.251;-1000.0
2K(56)
0.252;-1312.5
25(68)
0.223;-1656.3
25(6T)
0.289;-1518.8
25(6Q)
0.213;-1381.2
5(278)
0.230;-1587.5
5T(27)
0.286;-1450.0
(27)(5K)
0.253;-793.8
29(57)
0.194;-1518.8
2(57Q)
0.286;-1312.5
25(78)
0.289;-1587.5
25(7T)
0.261;-1450.0
25(7Q)
0.216;-1312.5
5(289)
0.243;-1450.0
5J(28)
0.219;-1312.5
(58)(29)
0.289;-1000.0
2J(58)
0.225;-1312.5
58(29)
0.253;-1450.0
58(2J)
0.205;-1312.5
58(2K)
0.258;-1175.0
5T(29)
0.206;-1312.5
(29)(5K)
0.213;-656.2
2J(59)
0.259;-1243.8
59(2T)
0.304;-1312.5
59(2Q)
0.267;-1175.0
(2T)(5T)
0.283;-343.7
5(2TK)
0.247;-1037.5
2(5TQ)
0.270;-1106.2
25(TJ)
0.262;-1175.0
25(TK)
0.228;-1037.5
(2J)(5K)
0.252;-518.7
2K(5J)
0.285;-968.7
25(JK)
0.286;-968.7
(5Q)(2K)
0.269;-450.0
(2K)(5K)
0.317;68.8
6(268)
0.264;-1137.5
6T(26)
0.272;-1000.0
(26)(6K)
0.319;-343.7
T(267)
0.213;-1381.2
7(268)
0.248;-1518.8
7T(26)
0.302;-1381.2
(26)(7K)
0.261;-725.0
J(268)
0.250;-1243.8
89(26)
0.232;-1381.2
(26)(8Q)
0.299;-725.0
(269J)
0.276;-1175.0
(26)(9T)
0.286;-793.8
9(26K)
0.280;-1037.5
(26TK)
0.212;-968.7
TQ(26)
0.269;-1037.5
K(26J)
0.260;-900.0
Q(26Q)
0.323;-450.0
KK(26)
0.318;-312.5
66(29)
0.285;-1068.7
266J
0.252;-1381.2
67(27)
0.262;-1137.5
(27)(6T)
0.260;-931.2
6(27K)
0.208;-1175.0
2(679)
0.293;-1450.0
(67)(2Q)
0.279;-793.8
27(68)
0.222;-1518.8
27(6T)
0.231;-1381.2
27(6Q)
0.284;-1243.8
68(28)
0.269;-1000.0
(28)(6J)
0.280;-793.8
28(68)
0.204;-1000.0
2(68J)
0.240;-1243.8
2688
0.240;-1450.0
268T
0.245;-1762.5
268Q
0.250;-1625.0
(29)(6T)
0.214;-793.8
6(29K)
0.258;-1037.5
2(69J)
0.328;-1175.0
2699
0.236;-1312.5
269J
0.248;-1625.0
269K
0.243;-1487.5
6Q(2T)
0.206;-1037.5
(6T)(2Q)
0.270;-587.5
2T(6J)
0.241;-1106.2
2T(6K)
0.258;-968.7
6(2JK)
0.270;-900.0
2(6JK)
0.279;-900.0
2J(6K)
0.283;-900.0
2Q(6Q)
0.278;-450.0
26QK
0.216;-1281.2
78(27)
0.277;-1000.0
(27)(7J)
0.256;-343.7
8(278)
0.266;-931.2
Q(278)
0.249;-1106.2
(27)(8T)
0.234;-793.8
8(27K)
0.306;-1037.5
(279Q)
0.290;-1037.5
9(27J)
0.253;-1106.2
9K(27)
0.279;-968.7
TT(27)
0.311;-656.2
(27)(TK)
0.300;-450.0
J(27Q)
0.295;-900.0
K(27Q)
0.225;-762.5
77(28)
0.234;-1000.0
277T
0.273;-1312.5
27(7K)
0.241;-656.2
(28)(7T)
0.314;-793.8
7(28K)
0.213;-1037.5
2(78T)
0.205;-1243.8
(78)(2K)
0.267;-587.5
78(2T)
0.259;-1243.8
78(2Q)
0.295;-1106.2
(29)(79)
0.264;-343.7
7(29Q)
0.250;-1037.5
2(79T)
0.268;-1175.0
(79)(2K)
0.251;-518.7
79(2J)
0.303;-1106.2
79(2K)
0.290;-968.7
7J(2T)
0.276;-1037.5
(7T)(2J)
0.220;-587.5
2K(7T)
0.210;-900.0
27(TQ)
0.267;-968.7
7(2JQ)
0.256;-900.0
2(7JQ)
0.228;-900.0
27(JQ)
0.261;-900.0
7(2QK)
0.259;-762.5
7Q(2K)
0.277;-762.5
88(28)
0.252;-412.5
(28)(8J)
0.278;-206.2
9(289)
0.268;-725.0
K(289)
0.216;-900.0
9(28Q)
0.210;-968.7
J(28T)
0.216;-968.7
TJ(28)
0.204;-968.7
(28JQ)
0.264;-831.2
J(28K)
0.296;-762.5
(28)(QK)
0.339;-243.8
88(2T)
0.329;-725.0
288Q
0.287;-1037.5
8T(29)
0.284;-1106.2
(29)(8K)
0.299;-450.0
2J(89)
0.221;-1037.5
89(2T)
0.244;-1106.2
89(2Q)
0.224;-968.7
(2T)(8T)
0.310;-137.5
8(2TK)
0.255;-831.2
2(8TQ)
0.245;-900.0
28(TJ)
0.292;-968.7
28(TK)
0.213;-831.2
(2J)(8K)
0.261;-312.5
2K(8J)
0.283;-762.5
28(JK)
0.230;-762.5
(8Q)(2K)
0.332;-243.8
(2K)(8K)
0.347;275.0
9(29J)
0.230;-518.7
9K(29)
0.291;-381.2
TT(29)
0.265;-518.7
(29)(TK)
0.299;-312.5
J(29Q)
0.241;-762.5
K(29Q)
0.362;-625.0
99(2T)
0.329;-587.5
299Q
0.246;-900.0
9J(2T)
0.270;-900.0
(9T)(2J)
0.295;-450.0
2K(9T)
0.248;-762.5
29(TQ)
0.283;-831.2
9(2JQ)
0.265;-762.5
2(9JQ)
0.293;-762.5
29(JQ)
0.252;-762.5
9(2QK)
0.304;-625.0
9Q(2K)
0.326;-625.0
TT(2T)
0.333;0.0
(2T)(TK)
0.276;206.3
J(2TQ)
0.253;-693.7
K(2TQ)
0.275;-556.2
TT(2J)
0.360;-381.2
2TTK
0.264;-693.7
TK(2J)
0.294;-625.0
2TJJ
0.216;-762.5
2TJK
0.307;-1075.0
2(TQK)
0.252;-556.2
TK(2K)
0.342;-37.5
(2J)(JK)
0.272;343.7
QK(2J)
0.270;-487.5
2J(JK)
0.350;-106.2
(JQ)(2K)
0.307;-37.5
(2K)(JK)
0.328;481.3
K(2QK)
0.313;100.0
2K(QK)
0.291;100.0
3335
0.215;-1687.5
3339
0.226;-1412.5
333K
0.213;-1137.5
36(34)
0.209;-1550.0
(34)(39)
0.222;-893.7
3(34Q)
0.187;-1137.5
33(45)
0.288;-1618.8
34(38)
0.283;-1412.5
334T
0.211;-1725.0
33(4K)
0.202;-1068.7
(35)(37)
0.325;-962.5
3(35T)
0.248;-1206.2
3Q(35)
0.248;-1068.7
35(37)
0.189;-1412.5
3359
0.224;-1725.0
33(5Q)
0.264;-1068.7
(36)(37)
0.301;-893.7
3(36T)
0.194;-1137.5
3Q(36)
0.221;-1000.0
36(38)
0.271;-1275.0
336T
0.202;-1587.5
33(6K)
0.222;-931.2
(37)(39)
0.242;-687.5
3(37Q)
0.273;-931.2
33(78)
0.265;-1206.2
37(3J)
0.237;-1000.0
337K
0.194;-1312.5
3T(38)
0.261;-1000.0
(38)(3K)
0.304;-343.7
338T
0.206;-1450.0
33(8K)
0.257;-793.7
(39)(3J)
0.275;-412.5
3399
0.274;-1000.0
33(9Q)
0.276;-793.7
(3T)(3J)
0.295;-343.7
33TT
0.299;-862.5
33(TK)
0.287;-656.2
(3J)(3K)
0.320;-137.5
33JK
0.242;-1037.5
33(QK)
0.319;-518.7
45(34)
0.235;-1550.0
(34)(48)
0.215;-893.7
4(34J)
0.207;-1137.5
4K(34)
0.220;-1000.0
(3459)
0.191;-1656.3
(345K)
0.213;-1381.2
57(34)
0.282;-1793.7
(34)(5T)
0.226;-1137.5
5(34K)
0.257;-1381.2
(3469)
0.219;-1587.5
(346K)
0.276;-1312.5
68(34)
0.211;-1656.3
(34)(6J)
0.260;-1000.0
7(347)
0.238;-1206.2
J(347)
0.204;-1381.2
78(34)
0.188;-1587.5
(34)(7J)
0.245;-931.2
8(348)
0.252;-1068.7
Q(348)
0.251;-1243.8
(34)(8T)
0.261;-931.2
8(34K)
0.300;-1175.0
(349Q)
0.256;-1175.0
9(34J)
0.213;-1243.8
9K(34)
0.254;-1106.2
TT(34)
0.290;-793.7
(34)(TK)
0.291;-587.5
J(34Q)
0.276;-1037.5
K(34Q)
0.275;-900.0
44(35)
0.299;-1550.0
3447
0.216;-1862.5
34(4T)
0.247;-1206.2
44(3K)
0.312;-1000.0
4(357)
0.211;-1793.7
49(35)
0.218;-1656.3
(35)(4Q)
0.250;-1000.0
36(45)
0.239;-1862.5
3(459)
0.233;-1656.3
(45)(3Q)
0.205;-1000.0
35(46)
0.232;-1862.5
35(48)
0.225;-1725.0
35(4T)
0.248;-1587.5
35(4Q)
0.283;-1450.0
46(36)
0.251;-1343.7
(36)(49)
0.300;-1137.5
4(36Q)
0.226;-1381.2
3(467)
0.202;-1725.0
(46)(3T)
0.285;-1068.7
3Q(46)
0.252;-1381.2
3467
0.234;-2175.0
3469
0.170;-2037.5
346J
0.244;-1900.0
346K
0.266;-1762.5
49(37)
0.239;-1518.8
(37)(4Q)
0.269;-862.5
38(47)
0.229;-1587.5
3(47J)
0.226;-1381.2
3477
0.244;-1656.3
3479
0.201;-1968.8
347J
0.205;-1831.2
347K
0.225;-1693.7
4T(38)
0.206;-1381.2
(38)(4K)
0.287;-725.0
3T(48)
0.260;-1381.2
3(48K)
0.252;-1175.0
38(4T)
0.217;-1381.2
38(4Q)
0.281;-1243.8
49(39)
0.205;-931.2
(39)(4Q)
0.273;-725.0
3T(49)
0.268;-1312.5
3(49K)
0.224;-1106.2
39(4J)
0.243;-1243.8
39(4K)
0.291;-1106.2
4(3TQ)
0.254;-1106.2
3(4TJ)
0.236;-1175.0
34TT
0.265;-1243.8
34TQ
0.243;-1556.2
(3J)(4Q)
0.263;-587.5
3Q(4J)
0.281;-1037.5
34JQ
0.216;-1487.5
(3Q)(4K)
0.269;-450.0
3Q(4K)
0.260;-900.0
5(356)
0.297;-1343.7
58(35)
0.267;-1206.2
(35)(5J)
0.276;-550.0
6(356)
0.307;-1275.0
T(356)
0.257;-1450.0
6(357)
0.222;-1656.3
69(35)
0.235;-1518.8
(35)(6Q)
0.264;-862.5
(3579)
0.234;-1450.0
(357K)
0.316;-1175.0
79(35)
0.226;-1450.0
(35)(7Q)
0.280;-793.8
(358T)
0.251;-1312.5
88(35)
0.193;-1000.0
(35)(8J)
0.270;-793.8
9(359)
0.240;-862.5
K(359)
0.233;-1037.5
9(35Q)
0.192;-1106.2
J(35T)
0.282;-1106.2
TJ(35)
0.257;-1106.2
(35JQ)
0.303;-968.7
J(35K)
0.265;-900.0
(35)(QK)
0.343;-381.2
55(37)
0.254;-1275.0
3559
0.224;-1587.5
35(5Q)
0.294;-931.2
(36)(57)
0.202;-1206.2
5(36T)
0.216;-1450.0
5Q(36)
0.260;-1312.5
(56)(38)
0.298;-1137.5
3T(56)
0.233;-1450.0
3(56K)
0.211;-1243.8
36(58)
0.253;-1587.5
36(5T)
0.220;-1450.0
36(5Q)
0.231;-1312.5
57(37)
0.262;-1137.5
(37)(5T)
0.274;-931.2
5(37K)
0.233;-1175.0
3(579)
0.256;-1450.0
(57)(3Q)
0.325;-793.8
37(58)
0.219;-1518.8
37(5T)
0.286;-1381.2
37(5Q)
0.221;-1243.8
58(38)
0.321;-1000.0
(38)(5J)
0.260;-793.8
38(58)
0.272;-1000.0
3(58J)
0.212;-1243.8
3588
0.227;-1450.0
358T
0.270;-1762.5
358Q
0.193;-1625.0
(39)(5T)
0.257;-793.8
5(39K)
0.232;-1037.5
3(59J)
0.233;-1175.0
3599
0.250;-1312.5
359J
0.210;-1625.0
359K
0.229;-1487.5
5Q(3T)
0.198;-1037.5
(5T)(3Q)
0.255;-587.5
3T(5J)
0.247;-1106.2
3T(5K)
0.229;-968.7
5(3JK)
0.224;-900.0
3(5JK)
0.249;-900.0
3J(5K)
0.209;-900.0
3Q(5Q)
0.269;-450.0
35QK
0.303;-1281.2
67(36)
0.269;-1137.5
(36)(6T)
0.264;-481.2
6(36K)
0.337;-725.0
(367T)
0.241;-1312.5
77(36)
0.192;-1068.7
(36)(7T)
0.233;-862.5
7(36K)
0.221;-1106.2
(368J)
0.227;-1175.0
(36)(89)
0.291;-862.5
8(36Q)
0.252;-1106.2
T(369)
0.230;-1175.0
9(36T)
0.236;-1175.0
9Q(36)
0.275;-1037.5
Q(36T)
0.310;-968.7
(36)(TQ)
0.254;-518.7
(36JK)
0.325;-831.2
JK(36)
0.271;-831.2
K(36K)
0.373;-243.7
3668
0.230;-1518.8
36(6J)
0.257;-862.5
(37)(67)
0.346;-618.8
6(37T)
0.234;-1312.5
6Q(37)
0.210;-1175.0
(67)(39)
0.323;-931.2
3J(67)
0.198;-1243.8
67(38)
0.190;-1450.0
67(3T)
0.225;-1312.5
67(3Q)
0.249;-1175.0
(38)(68)
0.261;-481.2
6(38J)
0.243;-1175.0
6K(38)
0.259;-1037.5
(68)(3J)
0.234;-725.0
3K(68)
0.270;-1037.5
36(8T)
0.285;-1243.8
36(8Q)
0.232;-1106.2
6(39T)
0.260;-1175.0
6Q(39)
0.252;-1037.5
(69)(3J)
0.272;-656.2
3K(69)
0.282;-968.7
36(9J)
0.290;-1106.2
36(9K)
0.295;-968.7
(3T)(6Q)
0.242;-518.7
3J(6T)
0.241;-1037.5
6T(3J)
0.268;-1037.5
6T(3K)
0.298;-900.0
6Q(3J)
0.264;-900.0
(6J)(3K)
0.272;-381.2
6J(3K)
0.272;-831.2
6K(3Q)
0.270;-762.5
36(QK)
0.265;-762.5
(37)(78)
0.291;-481.2
7(37J)
0.296;-725.0
7K(37)
0.292;-587.5
(378Q)
0.212;-1037.5
8(37T)
0.258;-1175.0
8Q(37)
0.239;-1037.5
J(379)
0.260;-1037.5
9T(37)
0.280;-1106.2
(37)(9K)
0.240;-450.0
K(37T)
0.238;-831.2
T(37K)
0.293;-831.2
JJ(37)
0.297;-450.0
(37QK)
0.216;-693.7
3777
0.257;-1000.0
37(7T)
0.308;-793.7
77(3K)
0.267;-587.5
7(38T)
0.251;-1175.0
7Q(38)
0.248;-1037.5
(78)(3T)
0.282;-725.0
3Q(78)
0.259;-1037.5
3789
0.273;-1693.7
378J
0.225;-1556.2
378K
0.246;-1418.7
7J(39)
0.275;-1037.5
(79)(3T)
0.298;-656.2
3Q(79)
0.252;-968.7
379T
0.256;-1556.2
379Q
0.259;-1418.7
(3T)(7J)
0.267;-518.7
3T(7T)
0.305;-587.5
3(7TK)
0.271;-831.2
3T(7Q)
0.277;-900.0
7J(3J)
0.316;-450.0
(7J)(3Q)
0.306;-381.2
3J(7Q)
0.300;-831.2
7Q(3Q)
0.298;-312.5
37QQ
0.258;-762.5
37KK
0.286;-625.0
8(38J)
0.289;-587.5
8K(38)
0.331;-450.0
(389K)
0.321;-831.2
9J(38)
0.233;-968.7
(38TJ)
0.288;-900.0
(38)(TJ)
0.315;-450.0
J(38J)
0.295;-381.2
JQ(38)
0.333;-762.5
Q(38K)
0.271;-625.0
3889
0.291;-1175.0
38(8Q)
0.298;-518.7
(39)(8T)
0.267;-587.5
8(39K)
0.302;-831.2
3(89J)
0.287;-968.7
3899
0.265;-1106.2
389J
0.244;-1418.7
389K
0.270;-1281.2
8Q(3T)
0.225;-831.2
(8T)(3Q)
0.281;-381.2
3T(8J)
0.277;-900.0
3T(8K)
0.241;-762.5
8(3JK)
0.263;-693.7
3(8JK)
0.297;-693.7
3J(8K)
0.279;-693.7
3Q(8Q)
0.345;-243.7
38QK
0.238;-1075.0
9T(39)
0.359;-518.7
(39)(9K)
0.257;137.5
K(39T)
0.347;-693.7
T(39K)
0.236;-693.7
JJ(39)
0.334;-312.5
(39QK)
0.260;-556.2
3999
0.284;-587.5
39(9Q)
0.308;-381.2
(3T)(9J)
0.282;-381.2
3T(9T)
0.283;-450.0
3(9TK)
0.284;-693.7
3T(9Q)
0.214;-762.5
9J(3J)
0.328;-312.5
(9J)(3Q)
0.337;-243.8
3J(9Q)
0.259;-693.7
9Q(3Q)
0.293;-175.0
39QQ
0.324;-625.0
39KK
0.269;-487.5
T(3TK)
0.277;-175.0
JJ(3T)
0.298;-243.7
(3TQK)
0.257;-487.5
3TTT
0.290;-381.2
3T(TK)
0.271;-175.0
(3J)(TK)
0.299;-106.2
3K(TJ)
0.292;-556.2
3T(JK)
0.259;-556.2
(TQ)(3K)
0.304;-37.5
(3K)(TK)
0.301;481.3
J(3JK)
0.316;-37.5
(3J)(QK)
0.298;31.3
JJ(3K)
0.270;-37.5
3Q(JQ)
0.363;-37.5
3JQK
0.232;-868.7
QK(3Q)
0.305;100.0
QK(3K)
0.303;168.8
44(46)
0.297;-962.5
44(4T)
0.325;-687.5
(45)(45)
0.297;-512.5
4(458)
0.230;-1206.2
4T(45)
0.259;-1068.7
(45)(4K)
0.344;-412.5
4457
0.233;-1725.0
44(5T)
0.258;-1068.7
45(4K)
0.328;-862.5
4(468)
0.261;-1137.5
4T(46)
0.267;-1000.0
(46)(4K)
0.259;-343.7
4468
0.258;-1587.5
44(6J)
0.248;-931.2
(47)(47)
0.322;-237.5
4(47T)
0.312;-931.2
4Q(47)
0.256;-793.7
47(49)
0.220;-1000.0
447J
0.248;-1312.5
48(48)
0.316;-550.0
(48)(4J)
0.263;-343.7
4488
0.244;-1000.0
44(8J)
0.227;-793.7
(49)(49)
0.253;37.5
4(49Q)
0.286;-656.2
44(9T)
0.267;-793.7
49(4K)
0.257;-587.5
4(4TQ)
0.280;-587.5
44(TJ)
0.247;-656.2
(4J)(4J)
0.369;312.5
44JJ
0.322;-587.5
4Q(4Q)
0.330;0.0
(4K)(4K)
0.298;587.5
(45)(57)
0.234;-756.3
5(45T)
0.219;-1000.0
5Q(45)
0.310;-862.5
8(456)
0.237;-1518.8
Q(456)
0.231;-1243.8
(45)(68)
0.309;-1068.7
6(45J)
0.286;-1312.5
6K(45)
0.236;-1175.0
(457J)
0.270;-1243.8
(45)(78)
0.313;-1000.0
7(45J)
0.193;-1243.8
7K(45)
0.268;-1106.2
(458Q)
0.237;-1106.2
8(45T)
0.214;-1243.8
8Q(45)
0.239;-1106.2
J(459)
0.221;-1106.2
9T(45)
0.223;-1175.0
(45)(9K)
0.363;-518.7
K(45T)
0.293;-900.0
T(45K)
0.219;-900.0
JJ(45)
0.228;-518.7
(45QK)
0.271;-762.5
4555
0.227;-1343.8
45(58)
0.228;-1137.5
55(4J)
0.253;-931.2
455K
0.240;-1243.8
58(46)
0.195;-1518.8
(46)(5J)
0.244;-862.5
46(56)
0.208;-1206.2
4(569)
0.195;-1450.0
(56)(4Q)
0.212;-793.8
46(57)
0.179;-1587.5
46(59)
0.267;-1450.0
46(5J)
0.242;-1312.5
46(5K)
0.241;-1175.0
5(479)
0.248;-1381.2
5J(47)
0.199;-1243.8
(57)(48)
0.212;-1000.0
4T(57)
0.248;-1312.5
4(57K)
0.250;-1106.2
47(59)
0.254;-1381.2
47(5J)
0.228;-1243.8
47(5K)
0.234;-1106.2
5(48T)
0.268;-1243.8
5Q(48)
0.268;-1106.2
(58)(4T)
0.230;-793.8
4Q(58)
0.221;-1106.2
4589
0.253;-1762.5
458J
0.268;-1625.0
458K
0.281;-1487.5
5J(49)
0.207;-1106.2
(59)(4T)
0.261;-725.0
4Q(59)
0.289;-1037.5
459T
0.221;-1625.0
459Q
0.282;-1487.5
(4T)(5J)
0.260;-587.5
4T(5T)
0.290;-656.2
4(5TK)
0.250;-900.0
4T(5Q)
0.274;-968.7
5J(4J)
0.235;-518.7
(5J)(4Q)
0.279;-450.0
4J(5Q)
0.209;-900.0
5Q(4Q)
0.291;-381.2
45QQ
0.254;-831.2
45KK
0.287;-693.7
6(469)
0.282;-931.2
6J(46)
0.251;-793.7
(4678)
0.244;-1381.2
(467Q)
0.268;-1106.2
7(469)
0.249;-1312.5
7J(46)
0.246;-1175.0
(4689)
0.230;-1243.8
(468K)
0.258;-968.7
8T(46)
0.284;-1175.0
(46)(8K)
0.267;-518.7
Q(469)
0.243;-968.7
(46)(9J)
0.276;-587.5
T(46T)
0.293;-587.5
T(46J)
0.289;-968.7
TK(46)
0.262;-831.2
(46)(JQ)
0.262;-381.2
QQ(46)
0.291;-312.5
46(67)
0.302;-1068.7
66(4T)
0.256;-862.5
466Q
0.245;-1175.0
68(47)
0.284;-1381.2
(47)(6J)
0.236;-725.0
47(67)
0.199;-1000.0
4(67T)
0.250;-1243.8
(67)(4K)
0.294;-587.5
67(49)
0.260;-1312.5
67(4J)
0.191;-1175.0
67(4K)
0.225;-1037.5
69(48)
0.205;-1243.8
(48)(6Q)
0.238;-587.5
49(68)
0.230;-1243.8
4(68Q)
0.254;-1037.5
46(89)
0.215;-1243.8
46(8J)
0.331;-1106.2
46(8K)
0.288;-968.7
(49)(6J)
0.266;-587.5
49(69)
0.282;-725.0
4(69Q)
0.232;-968.7
46(9T)
0.251;-1106.2
46(9Q)
0.252;-968.7
6(4TJ)
0.212;-968.7
6K(4T)
0.260;-831.2
(6T)(4K)
0.340;-381.2
6T(4Q)
0.239;-900.0
(4J)(6J)
0.322;0.0
4J(6J)
0.294;-450.0
6J(4Q)
0.262;-831.2
(4Q)(6Q)
0.354;137.5
4K(6Q)
0.278;-693.7
4K(6K)
0.246;-175.0
79(47)
0.325;-793.7
(47)(7Q)
0.321;-137.5
(478T)
0.216;-1106.2
88(47)
0.227;-793.7
(47)(8J)
0.322;-587.5
9(479)
0.236;-656.2
K(479)
0.290;-831.2
9(47Q)
0.316;-900.0
J(47T)
0.262;-900.0
TJ(47)
0.301;-900.0
(47JQ)
0.244;-762.5
J(47K)
0.299;-693.7
(47)(QK)
0.373;-175.0
77(49)
0.267;-793.7
477J
0.294;-1106.2
78(48)
0.245;-793.7
(48)(7J)
0.278;-587.5
48(78)
0.317;-793.7
4(78J)
0.258;-1037.5
4788
0.264;-1243.8
478T
0.189;-1556.2
478Q
0.230;-1418.7
(49)(7T)
0.263;-587.5
7(49K)
0.288;-831.2
4(79J)
0.283;-968.7
4799
0.203;-1106.2
479J
0.187;-1418.7
479K
0.263;-1281.2
7Q(4T)
0.305;-831.2
(7T)(4Q)
0.329;-381.2
4T(7J)
0.240;-900.0
4T(7K)
0.267;-762.5
7(4JK)
0.254;-693.7
4(7JK)
0.269;-693.7
4J(7K)
0.258;-693.7
4Q(7Q)
0.351;-243.7
47QK
0.253;-1075.0
89(48)
0.259;-656.2
(48)(8Q)
0.282;0.0
(489J)
0.306;-900.0
(48)(9T)
0.256;-518.7
9(48K)
0.330;-762.5
(48TK)
0.226;-693.7
TQ(48)
0.270;-762.5
K(48J)
0.302;-625.0
Q(48Q)
0.354;-175.0
KK(48)
0.295;-37.5
88(4J)
0.282;-518.7
488K
0.280;-831.2
8J(49)
0.313;-900.0
(89)(4T)
0.262;-518.7
4Q(89)
0.262;-831.2
489T
0.295;-1418.7
489Q
0.247;-1281.2
(4T)(8J)
0.257;-381.2
4T(8T)
0.311;-450.0
4(8TK)
0.226;-693.7
4T(8Q)
0.278;-762.5
8J(4J)
0.278;-312.5
(8J)(4Q)
0.319;-243.8
4J(8Q)
0.279;-693.7
8Q(4Q)
0.280;-175.0
48QQ
0.217;-625.0
48KK
0.333;-487.5
9(49Q)
0.264;-312.5
J(49T)
0.285;-762.5
TJ(49)
0.315;-762.5
(49JQ)
0.260;-625.0
J(49K)
0.279;-556.2
(49)(QK)
0.350;-37.5
99(4J)
0.305;-381.2
499K
0.248;-693.7
9Q(4T)
0.295;-693.7
(9T)(4Q)
0.317;-243.8
4T(9J)
0.261;-762.5
4T(9K)
0.275;-625.0
9(4JK)
0.259;-556.2
4(9JK)
0.230;-556.2
4J(9K)
0.286;-556.2
4Q(9Q)
0.274;-106.2
49QK
0.248;-937.5
TJ(4T)
0.321;-243.7
(4TJQ)
0.243;-556.2
J(4TK)
0.317;-487.5
(4T)(QK)
0.320;31.3
TT(4Q)
0.295;-175.0
T(4JQ)
0.258;-556.2
4(TJQ)
0.232;-556.2
4T(JQ)
0.237;-556.2
T(4QK)
0.283;-418.7
TQ(4K)
0.322;-418.7
JJ(4J)
0.354;343.7
(4JQK)
0.297;-350.0
4JJJ
0.334;-106.2
JQ(4Q)
0.341;31.3
4JQQ
0.328;-418.7
4JKK
0.268;-281.2
QQ(4K)
0.305;168.8
4KKK
0.290;306.2
55(59)
0.292;-550.0
55(5K)
0.331;-275.0
(56)(58)
0.242;-550.0
5(56J)
0.268;-793.7
5K(56)
0.292;-656.2
56(59)
0.250;-931.2
556J
0.263;-1243.8
57(57)
0.292;-550.0
(57)(5T)
0.259;-343.7
5(57K)
0.330;-587.5
55(79)
0.270;-862.5
57(5Q)
0.306;-656.2
5(589)
0.221;-793.7
5J(58)
0.306;-656.2
58(59)
0.272;-793.7
558J
0.262;-1106.2
59(59)
0.300;-275.0
(59)(5Q)
0.306;-68.8
559T
0.257;-1106.2
55(9K)
0.281;-450.0
(5T)(5Q)
0.313;0.0
55TJ
0.264;-968.7
5J(5J)
0.319;0.0
5J(5Q)
0.342;-381.2
5(5QK)
0.297;-243.7
5K(5K)
0.380;275.0
68(56)
0.315;-931.2
(56)(6J)
0.324;-275.0
7(567)
0.256;-931.2
J(567)
0.259;-1106.2
78(56)
0.188;-1312.5
(56)(7J)
0.315;-656.2
8(568)
0.223;-793.7
Q(568)
0.208;-968.7
(56)(8T)
0.242;-656.2
8(56K)
0.279;-900.0
(569Q)
0.320;-900.0
9(56J)
0.225;-968.7
9K(56)
0.238;-831.2
TT(56)
0.277;-518.7
(56)(TK)
0.260;-312.5
J(56Q)
0.322;-762.5
K(56Q)
0.248;-625.0
66(57)
0.303;-1000.0
5669
0.246;-1312.5
56(6Q)
0.227;-656.2
(57)(68)
0.302;-862.5
6(57J)
0.262;-1106.2
6K(57)
0.251;-968.7
(67)(5T)
0.233;-725.0
5Q(67)
0.247;-1037.5
5678
0.188;-1762.5
567T
0.267;-1625.0
567Q
0.235;-1487.5
(58)(69)
0.323;-725.0
6(58Q)
0.266;-968.7
5(689)
0.237;-1175.0
(68)(5Q)
0.256;-518.7
58(69)
0.272;-1175.0
58(6J)
0.232;-1037.5
58(6K)
0.239;-900.0
6(59J)
0.214;-968.7
6K(59)
0.331;-831.2
(69)(5Q)
0.319;-450.0
59(6T)
0.282;-1037.5
59(6Q)
0.257;-900.0
6T(5T)
0.277;-518.7
(5T)(6K)
0.350;-312.5
5Q(6T)
0.291;-831.2
56TJ
0.286;-1350.0
56TK
0.233;-1212.5
6K(5J)
0.269;-693.7
56JJ
0.328;-831.2
56JK
0.248;-1143.8
5(6QK)
0.265;-625.0
6K(5K)
0.289;-106.2
(57)(79)
0.289;-275.0
7(57Q)
0.271;-518.7
9(578)
0.273;-1106.2
K(578)
0.268;-831.2
8(57J)
0.252;-968.7
8K(57)
0.309;-831.2
(579K)
0.337;-762.5
9J(57)
0.243;-900.0
(57TJ)
0.304;-831.2
(57)(TJ)
0.259;-381.2
J(57J)
0.263;-312.5
JQ(57)
0.334;-693.7
Q(57K)
0.321;-556.2
5778
0.258;-1243.8
57(7J)
0.292;-587.5
(58)(78)
0.328;-275.0
7(58J)
0.280;-968.7
7K(58)
0.257;-831.2
(78)(5J)
0.338;-518.7
5K(78)
0.272;-831.2
57(8T)
0.287;-1037.5
57(8Q)
0.267;-900.0
7(59T)
0.281;-968.7
7Q(59)
0.259;-831.2
(79)(5J)
0.331;-450.0
5K(79)
0.291;-762.5
57(9J)
0.309;-900.0
57(9K)
0.224;-762.5
(5T)(7Q)
0.314;-312.5
5J(7T)
0.234;-831.2
7T(5J)
0.257;-831.2
7T(5K)
0.218;-693.7
7Q(5J)
0.234;-693.7
(7J)(5K)
0.240;-175.0
7J(5K)
0.339;-625.0
7K(5Q)
0.303;-556.2
57(QK)
0.247;-556.2
(58)(89)
0.271;-137.5
8(58Q)
0.321;-381.2
T(589)
0.225;-900.0
9(58T)
0.261;-900.0
9Q(58)
0.232;-762.5
Q(58T)
0.316;-693.7
(58)(TQ)
0.264;-243.8
(58JK)
0.307;-556.2
JK(58)
0.258;-556.2
K(58K)
0.320;31.3
588T
0.196;-968.7
58(8K)
0.292;-312.5
(59)(8J)
0.270;-381.2
59(89)
0.282;-518.7
5(89Q)
0.267;-762.5
58(9T)
0.304;-900.0
58(9Q)
0.241;-762.5
8(5TJ)
0.273;-762.5
8K(5T)
0.311;-625.0
(8T)(5K)
0.289;-175.0
8T(5Q)
0.271;-693.7
(5J)(8J)
0.314;206.3
5J(8J)
0.290;-243.7
8J(5Q)
0.257;-625.0
(5Q)(8Q)
0.317;343.7
5K(8Q)
0.313;-487.5
5K(8K)
0.289;31.3
9J(59)
0.292;-312.5
(59TJ)
0.330;-693.7
(59)(TJ)
0.291;-243.8
J(59J)
0.314;-175.0
JQ(59)
0.289;-556.2
Q(59K)
0.288;-418.7
599T
0.259;-831.2
59(9K)
0.279;-175.0
(5T)(9Q)
0.360;-175.0
5J(9T)
0.245;-693.7
9T(5J)
0.282;-693.7
9T(5K)
0.221;-556.2
9Q(5J)
0.261;-556.2
(9J)(5K)
0.257;-37.5
9J(5K)
0.301;-487.5
9K(5Q)
0.299;-418.7
59(QK)
0.262;-418.7
(5T)(TJ)
0.359;275.0
J(5TJ)
0.332;-106.2
JQ(5T)
0.332;-487.5
Q(5TK)
0.298;-350.0
5TTJ
0.338;-625.0
TJ(5J)
0.281;-106.2
(TJ)(5Q)
0.343;-37.5
5J(TQ)
0.299;-487.5
TQ(5Q)
0.376;31.3
5TQQ
0.306;-418.7
5TKK
0.302;-281.2
Q(5JQ)
0.266;100.0
KK(5J)
0.375;237.5
(5Q)(JQ)
0.358;550.0
5K(JQ)
0.309;-281.2
5K(JK)
0.341;237.5
5QQQ
0.339;168.8
KK(5K)
0.362;825.0
6669
0.311;-793.8
666K
0.304;-518.7
69(67)
0.305;-725.0
(67)(6Q)
0.367;-68.8
6678
0.238;-1243.8
66(7J)
0.244;-587.5
(68)(68)
0.315;175.0
6(68J)
0.263;-518.7
6K(68)
0.290;-381.2
68(6J)
0.282;-518.7
668K
0.257;-831.2
6J(69)
0.264;-450.0
69(6T)
0.338;-518.7
669Q
0.246;-831.2
6J(6T)
0.264;-381.2
6T(6J)
0.299;-381.2
66TK
0.288;-693.7
6K(6J)
0.281;-175.0
(6Q)(6Q)
0.364;725.0
66QK
0.249;-556.2
7(679)
0.289;-656.2
7J(67)
0.304;-518.7
(6789)
0.310;-1037.5
(678K)
0.249;-762.5
8T(67)
0.282;-968.7
(67)(8K)
0.310;-312.5
Q(679)
0.219;-762.5
(67)(9J)
0.291;-381.2
T(67T)
0.254;-381.2
T(67J)
0.285;-762.5
TK(67)
0.334;-625.0
(67)(JQ)
0.360;-175.0
QQ(67)
0.345;-106.2
67(78)
0.297;-725.0
77(6J)
0.237;-518.7
677K
0.229;-831.2
7T(68)
0.261;-968.7
(68)(7K)
0.245;-312.5
6T(78)
0.259;-968.7
6(78K)
0.231;-762.5
68(7T)
0.296;-968.7
68(7Q)
0.231;-831.2
79(69)
0.274;-518.7
(69)(7Q)
0.350;-312.5
6T(79)
0.314;-900.0
6(79K)
0.286;-693.7
69(7J)
0.222;-831.2
69(7K)
0.218;-693.7
7(6TQ)
0.296;-693.7
6(7TJ)
0.331;-762.5
67TT
0.313;-831.2
67TQ
0.302;-1143.8
(6J)(7Q)
0.361;-175.0
6Q(7J)
0.351;-625.0
67JQ
0.207;-1075.0
(6Q)(7K)
0.369;-37.5
6Q(7K)
0.280;-487.5
8(689)
0.258;-518.7
8J(68)
0.272;-381.2
(689T)
0.211;-831.2
99(68)
0.280;-450.0
(68)(9Q)
0.310;-243.8
(68TQ)
0.265;-625.0
T(68Q)
0.280;-625.0
Q(68J)
0.289;-556.2
(68)(JK)
0.364;-37.5
QK(68)
0.252;-418.7
68(8T)
0.311;-450.0
88(6K)
0.305;-243.7
8(69J)
0.260;-762.5
8K(69)
0.328;-625.0
(89)(6Q)
0.314;-243.8
69(8T)
0.251;-831.2
69(8Q)
0.317;-693.7
8T(6T)
0.339;-312.5
(6T)(8K)
0.296;-106.2
6Q(8T)
0.325;-625.0
68TJ
0.198;-1143.8
68TK
0.274;-1006.3
8K(6J)
0.288;-487.5
68JJ
0.350;-625.0
68JK
0.288;-937.5
6(8QK)
0.279;-418.7
8K(6K)
0.332;100.0
(69)(9J)
0.329;206.3
T(69T)
0.306;-243.7
T(69J)
0.233;-625.0
TK(69)
0.308;-487.5
(69)(JQ)
0.316;-37.5
QQ(69)
0.374;31.3
69(9T)
0.276;-312.5
99(6K)
0.306;-106.2
9(6TQ)
0.284;-556.2
6(9TJ)
0.277;-625.0
69TT
0.231;-693.7
69TQ
0.214;-1006.3
(6J)(9Q)
0.332;-37.5
6Q(9J)
0.275;-487.5
69JQ
0.233;-937.5
(6Q)(9K)
0.293;100.0
6Q(9K)
0.323;-350.0
T(6TJ)
0.245;-106.2
TK(6T)
0.354;31.3
(6T)(JQ)
0.311;31.3
QQ(6T)
0.369;100.0
6T(TJ)
0.311;-106.2
(6J)(TJ)
0.315;412.5
6J(TJ)
0.283;-37.5
TJ(6Q)
0.280;-418.7
(6Q)(TQ)
0.267;550.0
6K(TQ)
0.287;-281.2
6K(TK)
0.259;237.5
JK(6J)
0.328;168.8
K(6JK)
0.314;306.2
6JJK
0.371;-281.2
6(JQK)
0.294;-212.5
JK(6K)
0.338;306.2
KK(6Q)
0.355;375.0
6QKK
0.299;-75.0
77(7T)
0.330;-68.7
(78)(78)
0.332;312.5
7(78J)
0.270;-381.2
7K(78)
0.252;-243.7
78(7J)
0.313;-381.2
778K
0.234;-693.7
7J(79)
0.338;-312.5
79(7T)
0.284;-381.2
779Q
0.304;-693.7
7J(7T)
0.370;-243.7
7T(7J)
0.265;-243.7
77TK
0.298;-556.2
7K(7J)
0.301;-37.5
(7Q)(7Q)
0.386;862.5
77QK
0.298;-418.7
8(78T)
0.283;-381.2
8Q(78)
0.251;-243.7
J(789)
0.282;-693.7
9T(78)
0.238;-762.5
(78)(9K)
0.353;-106.2
K(78T)
0.307;-487.5
T(78K)
0.236;-487.5
JJ(78)
0.298;-106.2
(78QK)
0.295;-350.0
7888
0.289;-518.7
78(8J)
0.289;-312.5
(79)(89)
0.311;68.8
8(79Q)
0.218;-625.0
7(89T)
0.248;-762.5
(89)(7K)
0.341;-106.2
89(7J)
0.318;-693.7
89(7K)
0.312;-556.2
8J(7T)
0.266;-625.0
(8T)(7J)
0.272;-175.0
7K(8T)
0.295;-487.5
78(TQ)
0.301;-556.2
8(7JQ)
0.324;-487.5
7(8JQ)
0.326;-487.5
78(JQ)
0.262;-487.5
8(7QK)
0.264;-350.0
8Q(7K)
0.262;-350.0
99(79)
0.366;137.5
(79)(9Q)
0.397;343.7
(79TQ)
0.275;-487.5
T(79Q)
0.258;-487.5
Q(79J)
0.237;-418.7
(79)(JK)
0.248;100.0
QK(79)
0.333;-281.2
79(9J)
0.258;-175.0
(7T)(9T)
0.349;275.0
9(7TK)
0.357;-418.7
7(9TQ)
0.333;-487.5
79(TJ)
0.333;-556.2
79(TK)
0.369;-418.7
(7J)(9K)
0.266;100.0
7K(9J)
0.270;-350.0
79(JK)
0.294;-350.0
(9Q)(7K)
0.260;168.8
(7K)(9K)
0.346;687.5
T(7TQ)
0.344;31.3
Q(7TJ)
0.338;-350.0
(7T)(JK)
0.289;168.8
QK(7T)
0.303;-212.5
7T(TQ)
0.321;31.3
(7J)(TQ)
0.272;100.0
7Q(TJ)
0.230;-350.0
7TJQ
0.275;-800.0
(7Q)(TK)
0.267;237.5
7Q(TK)
0.261;-212.5
J(7JQ)
0.315;168.8
K(7JQ)
0.277;-143.7
JJ(7Q)
0.302;168.8
J(7QK)
0.375;-143.7
JQ(7K)
0.236;-143.7
QQ(7Q)
0.340;756.2
7Q(QK)
0.320;375.0
8888
0.370;0.0
888Q
0.324;-175.0
8(89J)
0.283;-175.0
8K(89)
0.352;-37.5
89(8Q)
0.314;-106.2
8(8TJ)
0.349;-106.2
8K(8T)
0.318;31.3
8T(8K)
0.343;31.3
8(8JK)
0.313;100.0
88(JK)
0.352;100.0
8Q(8K)
0.312;168.8
(89)(9T)
0.370;275.0
9(89K)
0.344;31.3
(89TK)
0.318;-350.0
TQ(89)
0.262;-418.7
K(89J)
0.308;-281.2
Q(89Q)
0.323;168.8
KK(89)
0.324;306.2
99(8Q)
0.291;-37.5
9(8TJ)
0.267;-487.5
9K(8T)
0.336;-350.0
(9T)(8K)
0.319;100.0
9T(8Q)
0.274;-418.7
(8J)(9J)
0.341;481.3
8J(9J)
0.291;31.3
9J(8Q)
0.334;-350.0
(8Q)(9Q)
0.295;618.8
8K(9Q)
0.229;-212.5
8K(9K)
0.311;306.2
TQ(8T)
0.285;100.0
K(8TJ)
0.306;-212.5
Q(8TQ)
0.275;237.5
KK(8T)
0.336;375.0
