AAAA
0.149;1505.0
5AAA
0.089;-5228.1
9AAA
0.095;-3495.6
KAAA
0.124;-1763.1
4A(2A)
0.036;-10858.8
(2A)(7A)
0.061;-6724.4
A(2TA)
0.040;-8260.0
QA(2A)
0.062;-7393.7
2A(4A)
0.047;-10858.8
26AA
0.028;-12827.5
AA(29)
0.054;-8693.1
2A(QA)
0.067;-7393.7
A(34A)
0.045;-10425.6
6A(3A)
0.050;-9559.4
(3A)(9A)
0.091;-5425.0
A(3QA)
0.064;-6960.6
AA(34)
0.043;-10425.6
3A(7A)
0.057;-9126.2
39AA
0.039;-11095.0
AA(3Q)
0.070;-6960.6
(4A)(5A)
0.062;-6724.4
A(48A)
0.060;-8260.0
TA(4A)
0.054;-7393.7
(4A)(KA)
0.105;-3259.4
46AA
0.030;-11961.3
AA(49)
0.053;-7826.9
4A(QA)
0.084;-6527.5
A(56A)
0.059;-8693.1
8A(5A)
0.080;-7826.9
(5A)(JA)
0.091;-3692.5
55AA
0.040;-9126.2
AA(58)
0.047;-7826.9
5A(JA)
0.062;-6527.5
5KAA
0.049;-8496.3
8A(6A)
0.070;-7393.7
(6A)(JA)
0.075;-3259.4
66AA
0.065;-8260.0
AA(69)
0.054;-6960.6
6A(QA)
0.090;-5661.3
A(78A)
0.066;-6960.6
TA(7A)
0.053;-6094.4
(7A)(KA)
0.090;-1960.0
79AA
0.055;-9362.5
AA(7Q)
0.072;-5228.1
(8A)(9A)
0.074;-3259.4
A(8QA)
0.091;-4795.0
AA(89)
0.071;-6094.4
8A(QA)
0.090;-4795.0
A(9TA)
0.061;-5228.1
QA(9A)
0.087;-4361.9
9A(JA)
0.080;-4795.0
9KAA
0.083;-6763.8
QA(TA)
0.096;-3928.8
TA(QA)
0.099;-3928.8
A(JQA)
0.068;-3495.6
AA(JQ)
0.101;-3495.6
(QA)(KA)
0.162;205.6
KKAA
0.118;-2196.2
2(25A)
0.018;-15623.1
27(2A)
0.021;-14756.9
(2T)(2A)
0.041;-10622.5
2(2KA)
0.039;-12158.1
(236A)
0.012;-17591.9
(23TA)
0.019;-15859.4
33(2A)
0.015;-16056.3
(36)(2A)
0.021;-14756.9
3(29A)
0.013;-16292.5
3J(2A)
0.018;-15426.3
(245A)
0.013;-17591.9
(249A)
0.016;-15859.4
(24KA)
0.022;-14126.9
46(2A)
0.012;-17158.8
(49)(2A)
0.024;-13024.4
4(2QA)
0.024;-14560.0
6(25A)
0.017;-16725.6
T(25A)
0.022;-14993.1
5(26A)
0.018;-16725.6
58(2A)
0.019;-15859.4
(5J)(2A)
0.033;-11725.0
6(26A)
0.028;-13457.5
T(26A)
0.021;-14560.0
6(27A)
0.021;-15859.4
69(2A)
0.022;-14993.1
(6Q)(2A)
0.032;-10858.8
(279A)
0.020;-14560.0
(27KA)
0.032;-12827.5
79(2A)
0.025;-14560.0
(7Q)(2A)
0.052;-10425.6
(28TA)
0.021;-13693.8
88(2A)
0.033;-11725.0
(8J)(2A)
0.039;-10425.6
9(29A)
0.044;-10858.8
K(29A)
0.030;-11961.3
9(2QA)
0.033;-12394.4
J(2TA)
0.029;-12394.4
TJ(2A)
0.024;-12394.4
(2JQA)
0.032;-11528.1
J(2KA)
0.047;-11095.0
(QK)(2A)
0.056;-7826.9
22(4A)
0.018;-16056.3
226A
0.013;-18025.0
2A(29)
0.026;-13890.6
22(QA)
0.031;-12591.3
2(34A)
0.009;-18458.1
26(3A)
0.011;-17591.9
(29)(3A)
0.025;-13457.5
2(3QA)
0.023;-14993.1
A(234)
0.010;-18458.1
(23)(7A)
0.021;-14323.8
9A(23)
0.016;-16292.5
A(23Q)
0.025;-14993.1
2A(34)
0.013;-18458.1
2A(36)
0.014;-17591.9
2A(38)
0.014;-16725.6
2A(3T)
0.017;-15859.4
2A(3Q)
0.018;-14993.1
2(45A)
0.014;-17591.9
27(4A)
0.015;-16725.6
(2T)(4A)
0.035;-12591.3
2(4KA)
0.026;-14126.9
A(246)
0.011;-17158.8
(24)(9A)
0.036;-13024.4
JA(24)
0.016;-14993.1
24(5A)
0.013;-17591.9
24(7A)
0.015;-16725.6
24(9A)
0.018;-15859.4
24(JA)
0.024;-14993.1
24(KA)
0.030;-14126.9
26(5A)
0.018;-16725.6
(29)(5A)
0.024;-12591.3
2(5QA)
0.021;-14126.9
A(256)
0.015;-16725.6
(25)(9A)
0.030;-12591.3
JA(25)
0.022;-14560.0
25(6A)
0.017;-16725.6
25(8A)
0.018;-15859.4
25(TA)
0.022;-14993.1
25(QA)
0.026;-14126.9
(26)(6A)
0.040;-10622.5
2(69A)
0.023;-14993.1
2J(6A)
0.028;-14126.9
(26)(7A)
0.025;-13024.4
9A(26)
0.020;-14993.1
A(26Q)
0.022;-13693.8
2A(67)
0.023;-15859.4
2A(69)
0.019;-14993.1
2A(6J)
0.026;-14126.9
2A(6K)
0.033;-13260.6
(29)(7A)
0.030;-11725.0
2(7QA)
0.025;-13260.6
A(278)
0.020;-14993.1
(27)(JA)
0.034;-10858.8
KA(27)
0.025;-12827.5
2A(79)
0.019;-14560.0
2A(7J)
0.030;-13693.8
2A(7K)
0.025;-12827.5
(2T)(8A)
0.038;-10858.8
2(8KA)
0.030;-12394.4
A(28T)
0.024;-13693.8
(28)(KA)
0.054;-9559.4
28(TA)
0.024;-13693.8
28(QA)
0.027;-12827.5
(29)(9A)
0.046;-8023.8
2(9QA)
0.022;-12394.4
A(29T)
0.026;-13260.6
(29)(KA)
0.042;-9126.2
29(JA)
0.024;-12827.5
29(KA)
0.040;-11961.3
2J(TA)
0.034;-12394.4
(2T)(JA)
0.048;-9559.4
KA(2T)
0.040;-11528.1
2A(TQ)
0.035;-11961.3
2(JQA)
0.038;-11528.1
A(2JQ)
0.044;-11528.1
2A(JQ)
0.046;-11528.1
2(QKA)
0.043;-10661.9
2Q(KA)
0.036;-10661.9
33(3A)
0.026;-12788.1
(36)(3A)
0.038;-11488.8
3(39A)
0.031;-13024.4
3J(3A)
0.025;-12158.1
(345A)
0.016;-17158.8
(349A)
0.024;-15426.3
(34KA)
0.035;-13693.8
46(3A)
0.012;-16725.6
(49)(3A)
0.033;-12591.3
4(3QA)
0.023;-14126.9
6(35A)
0.019;-16292.5
T(35A)
0.017;-14560.0
5(36A)
0.016;-16292.5
58(3A)
0.021;-15426.3
(5J)(3A)
0.031;-11291.9
6(36A)
0.031;-13024.4
T(36A)
0.021;-14126.9
6(37A)
0.021;-15426.3
69(3A)
0.021;-14560.0
(6Q)(3A)
0.037;-10425.6
(379A)
0.021;-14126.9
(37KA)
0.034;-12394.4
79(3A)
0.019;-14126.9
(7Q)(3A)
0.040;-9992.5
(38TA)
0.020;-13260.6
88(3A)
0.036;-11291.9
(8J)(3A)
0.052;-9992.5
9(39A)
0.047;-10425.6
K(39A)
0.034;-11528.1
9(3QA)
0.035;-11961.3
J(3TA)
0.029;-11961.3
TJ(3A)
0.027;-11961.3
(3JQA)
0.032;-11095.0
J(3KA)
0.037;-10661.9
(QK)(3A)
0.051;-7393.7
33(5A)
0.019;-14756.9
337A
0.016;-16725.6
3A(3T)
0.032;-12591.3
33(KA)
0.028;-11291.9
3(46A)
0.013;-16725.6
38(4A)
0.017;-15859.4
(3J)(4A)
0.036;-11725.0
4A(34)
0.016;-14756.9
A(347)
0.017;-16292.5
(34)(TA)
0.037;-12158.1
QA(34)
0.029;-14126.9
345A
0.006;-19993.8
347A
0.012;-19127.5
349A
0.014;-18261.3
34JA
0.013;-17395.0
34KA
0.016;-16528.8
37(5A)
0.020;-15859.4
(3T)(5A)
0.038;-11725.0
3(5KA)
0.023;-13260.6
A(357)
0.019;-15859.4
(35)(TA)
0.040;-11725.0
QA(35)
0.022;-13693.8
356A
0.010;-19127.5
358A
0.012;-18261.3
35TA
0.016;-17395.0
35QA
0.013;-16528.8
(37)(6A)
0.033;-12591.3
3(6TA)
0.020;-14126.9
3Q(6A)
0.030;-13260.6
(36)(8A)
0.033;-12158.1
TA(36)
0.029;-14126.9
A(36K)
0.035;-12827.5
6A(38)
0.022;-14993.1
6A(3T)
0.025;-14126.9
6A(3Q)
0.027;-13260.6
37(7A)
0.028;-12158.1
(3T)(7A)
0.055;-10858.8
3(7KA)
0.030;-12394.4
A(379)
0.026;-14126.9
(37)(QA)
0.050;-9992.5
7A(38)
0.021;-14560.0
7A(3T)
0.022;-13693.8
7A(3Q)
0.024;-12827.5
38(8A)
0.041;-11291.9
(3J)(8A)
0.036;-9992.5
8A(38)
0.032;-11291.9
A(38J)
0.031;-12827.5
388A
0.023;-14126.9
38TA
0.018;-16095.6
38QA
0.021;-15229.4
(3T)(9A)
0.045;-9992.5
3(9KA)
0.032;-11528.1
A(39J)
0.035;-12394.4
399A
0.032;-13260.6
39JA
0.019;-15229.4
39KA
0.019;-14363.1
3Q(TA)
0.038;-11528.1
(3T)(QA)
0.065;-8693.1
TA(3J)
0.036;-11961.3
TA(3K)
0.040;-11095.0
3(JKA)
0.034;-10661.9
A(3JK)
0.048;-10661.9
JA(3K)
0.049;-10661.9
QA(3Q)
0.067;-7826.9
3QKA
0.034;-13063.7
45(4A)
0.024;-13890.6
(48)(4A)
0.046;-9756.3
4(4JA)
0.043;-11291.9
4K(4A)
0.041;-10425.6
(459A)
0.026;-14560.0
(45KA)
0.035;-12827.5
57(4A)
0.020;-15426.3
(5T)(4A)
0.029;-11291.9
5(4KA)
0.028;-12827.5
(469A)
0.022;-14126.9
(46KA)
0.033;-12394.4
68(4A)
0.021;-14560.0
(6J)(4A)
0.033;-10425.6
7(47A)
0.035;-11725.0
J(47A)
0.039;-12827.5
78(4A)
0.027;-14126.9
(7J)(4A)
0.036;-9992.5
8(48A)
0.044;-10858.8
Q(48A)
0.038;-11961.3
(8T)(4A)
0.035;-9992.5
8(4KA)
0.037;-11528.1
(49QA)
0.044;-11528.1
9(4JA)
0.036;-11961.3
9K(4A)
0.040;-11095.0
TT(4A)
0.055;-9126.2
(TK)(4A)
0.052;-7826.9
J(4QA)
0.044;-10661.9
K(4QA)
0.046;-9795.6
44(5A)
0.026;-13890.6
447A
0.020;-15859.4
4A(4T)
0.032;-11725.0
44(KA)
0.032;-10425.6
4(57A)
0.020;-15426.3
49(5A)
0.020;-14560.0
(4Q)(5A)
0.050;-10425.6
6A(45)
0.016;-15859.4
A(459)
0.023;-14560.0
(45)(QA)
0.037;-10425.6
5A(46)
0.017;-15859.4
5A(48)
0.018;-14993.1
5A(4T)
0.028;-14126.9
5A(4Q)
0.029;-13260.6
46(6A)
0.027;-12591.3
(49)(6A)
0.035;-11291.9
4(6QA)
0.029;-12827.5
A(467)
0.022;-14993.1
(46)(TA)
0.040;-10858.8
QA(46)
0.028;-12827.5
467A
0.016;-17828.1
469A
0.016;-16961.9
46JA
0.017;-16095.6
46KA
0.018;-15229.4
49(7A)
0.026;-13693.8
(4Q)(7A)
0.047;-9559.4
8A(47)
0.021;-14126.9
A(47J)
0.023;-12827.5
477A
0.026;-14560.0
479A
0.014;-16528.8
47JA
0.018;-15662.5
47KA
0.018;-14796.2
4T(8A)
0.032;-12827.5
(4K)(8A)
0.055;-8693.1
TA(48)
0.030;-12827.5
A(48K)
0.031;-11528.1
8A(4T)
0.030;-12827.5
8A(4Q)
0.031;-11961.3
49(9A)
0.040;-9992.5
(4Q)(9A)
0.044;-8693.1
TA(49)
0.027;-12394.4
A(49K)
0.040;-11095.0
9A(4J)
0.036;-11961.3
9A(4K)
0.043;-11095.0
4(TQA)
0.034;-11095.0
A(4TJ)
0.038;-11528.1
4TTA
0.035;-11961.3
4TQA
0.025;-13930.0
(4Q)(JA)
0.056;-7826.9
QA(4J)
0.037;-10661.9
4JQA
0.021;-13496.9
(4K)(QA)
0.069;-6960.6
QA(4K)
0.046;-9795.6
5(56A)
0.033;-12591.3
58(5A)
0.031;-11725.0
(5J)(5A)
0.066;-7590.6
6(56A)
0.040;-12158.1
T(56A)
0.031;-13260.6
6(57A)
0.020;-14560.0
69(5A)
0.027;-13693.8
(6Q)(5A)
0.053;-9559.4
(579A)
0.030;-13260.6
(57KA)
0.042;-11528.1
79(5A)
0.026;-13260.6
(7Q)(5A)
0.047;-9126.2
(58TA)
0.033;-12394.4
88(5A)
0.048;-10425.6
(8J)(5A)
0.050;-9126.2
9(59A)
0.045;-9559.4
K(59A)
0.048;-10661.9
9(5QA)
0.049;-11095.0
J(5TA)
0.031;-11095.0
TJ(5A)
0.027;-11095.0
(5JQA)
0.046;-10228.8
J(5KA)
0.045;-9795.6
(QK)(5A)
0.070;-6527.5
55(7A)
0.027;-12158.1
559A
0.025;-14126.9
5A(5Q)
0.037;-9992.5
(57)(6A)
0.031;-11725.0
5(6TA)
0.020;-13260.6
5Q(6A)
0.034;-12394.4
(56)(8A)
0.032;-11291.9
TA(56)
0.023;-13260.6
A(56K)
0.034;-11961.3
6A(58)
0.023;-14126.9
6A(5T)
0.025;-13260.6
6A(5Q)
0.029;-12394.4
57(7A)
0.037;-11291.9
(5T)(7A)
0.041;-9992.5
5(7KA)
0.037;-11528.1
A(579)
0.033;-13260.6
(57)(QA)
0.044;-9126.2
7A(58)
0.025;-13693.8
7A(5T)
0.032;-12827.5
7A(5Q)
0.033;-11961.3
58(8A)
0.040;-10425.6
(5J)(8A)
0.046;-9126.2
8A(58)
0.044;-10425.6
A(58J)
0.030;-11961.3
588A
0.025;-13260.6
58TA
0.020;-15229.4
58QA
0.025;-14363.1
(5T)(9A)
0.054;-9126.2
5(9KA)
0.039;-10661.9
A(59J)
0.043;-11528.1
599A
0.029;-12394.4
59JA
0.021;-14363.1
59KA
0.033;-13496.9
5Q(TA)
0.037;-10661.9
(5T)(QA)
0.054;-7826.9
TA(5J)
0.030;-11095.0
TA(5K)
0.053;-10228.8
5(JKA)
0.051;-9795.6
A(5JK)
0.059;-9795.6
JA(5K)
0.041;-9795.6
QA(5Q)
0.058;-6960.6
5QKA
0.031;-12197.5
67(6A)
0.042;-11291.9
(6T)(6A)
0.046;-7157.5
6(6KA)
0.062;-8693.1
(67TA)
0.030;-12394.4
77(6A)
0.036;-10858.8
(7T)(6A)
0.051;-9559.4
7(6KA)
0.039;-11095.0
(68JA)
0.040;-11528.1
(89)(6A)
0.041;-9559.4
8(6QA)
0.033;-11095.0
T(69A)
0.044;-11528.1
9(6TA)
0.026;-11528.1
9Q(6A)
0.037;-10661.9
Q(6TA)
0.041;-10228.8
(TQ)(6A)
0.061;-7393.7
(6JKA)
0.051;-9362.5
JK(6A)
0.051;-9362.5
K(6KA)
0.056;-5661.3
668A
0.026;-13693.8
6A(6J)
0.048;-9559.4
(67)(7A)
0.047;-8023.8
6(7TA)
0.033;-12394.4
6Q(7A)
0.034;-11528.1
(67)(9A)
0.036;-9992.5
JA(67)
0.031;-11961.3
67(8A)
0.026;-13260.6
67(TA)
0.040;-12394.4
67(QA)
0.044;-11528.1
(68)(8A)
0.071;-7157.5
6(8JA)
0.036;-11528.1
6K(8A)
0.034;-10661.9
(68)(JA)
0.057;-8693.1
KA(68)
0.037;-10661.9
6A(8T)
0.028;-11961.3
6A(8Q)
0.034;-11095.0
6(9TA)
0.035;-11528.1
6Q(9A)
0.043;-10661.9
(69)(JA)
0.064;-8260.0
KA(69)
0.037;-10228.8
6A(9J)
0.031;-11095.0
6A(9K)
0.038;-10228.8
(6Q)(TA)
0.059;-7393.7
JA(6T)
0.036;-10661.9
6T(JA)
0.043;-10661.9
6T(KA)
0.052;-9795.6
6Q(JA)
0.050;-9795.6
(6J)(KA)
0.083;-6527.5
6J(KA)
0.043;-9362.5
6K(QA)
0.048;-8929.4
6A(QK)
0.059;-8929.4
(78)(7A)
0.074;-7157.5
7(7JA)
0.058;-8693.1
7K(7A)
0.056;-7826.9
(78QA)
0.038;-10661.9
8(7TA)
0.040;-11528.1
8Q(7A)
0.038;-10661.9
J(79A)
0.036;-10661.9
9T(7A)
0.035;-11095.0
(9K)(7A)
0.051;-6960.6
K(7TA)
0.035;-9362.5
T(7KA)
0.054;-9362.5
JJ(7A)
0.056;-6960.6
(7QKA)
0.054;-8496.3
777A
0.041;-10425.6
7A(7T)
0.050;-9126.2
77(KA)
0.076;-7826.9
7(8TA)
0.031;-11528.1
7Q(8A)
0.030;-10661.9
(78)(TA)
0.057;-8693.1
QA(78)
0.041;-10661.9
789A
0.026;-14796.2
78JA
0.023;-13930.0
78KA
0.021;-13063.7
7J(9A)
0.038;-10661.9
(79)(TA)
0.055;-8260.0
QA(79)
0.055;-10228.8
79TA
0.023;-13930.0
79QA
0.033;-13063.7
(7J)(TA)
0.075;-7393.7
TA(7T)
0.065;-7826.9
A(7TK)
0.050;-9362.5
TA(7Q)
0.049;-9795.6
7J(JA)
0.050;-6960.6
(7J)(QA)
0.067;-6527.5
JA(7Q)
0.054;-9362.5
7Q(QA)
0.080;-6094.4
7QQA
0.050;-8929.4
7KKA
0.067;-8063.1
8(8JA)
0.052;-7826.9
8K(8A)
0.053;-6960.6
(89KA)
0.053;-9362.5
9J(8A)
0.042;-10228.8
(8TJA)
0.057;-9795.6
(TJ)(8A)
0.056;-6960.6
J(8JA)
0.062;-6527.5
JQ(8A)
0.042;-8929.4
Q(8KA)
0.063;-8063.1
889A
0.029;-11528.1
8A(8Q)
0.053;-7393.7
(8T)(9A)
0.063;-7826.9
8(9KA)
0.035;-9362.5
A(89J)
0.054;-10228.8
899A
0.043;-11095.0
89JA
0.026;-13063.7
89KA
0.034;-12197.5
8Q(TA)
0.042;-9362.5
(8T)(QA)
0.058;-6527.5
TA(8J)
0.050;-9795.6
TA(8K)
0.052;-8929.4
8(JKA)
0.047;-8496.3
A(8JK)
0.050;-8496.3
JA(8K)
0.053;-8496.3
QA(8Q)
0.065;-5661.3
8QKA
0.039;-10898.1
9T(9A)
0.056;-7393.7
(9K)(9A)
0.086;-3259.4
K(9TA)
0.067;-8496.3
T(9KA)
0.045;-8496.3
JJ(9A)
0.084;-6094.4
(9QKA)
0.061;-7630.0
999A
0.064;-7826.9
9A(9Q)
0.051;-6527.5
(9J)(TA)
0.069;-6527.5
TA(9T)
0.055;-6960.6
A(9TK)
0.044;-8496.3
TA(9Q)
0.052;-8929.4
9J(JA)
0.063;-6094.4
(9J)(QA)
0.073;-5661.3
JA(9Q)
0.049;-8496.3
9Q(QA)
0.085;-5228.1
9QQA
0.075;-8063.1
9KKA
0.047;-7196.9
T(TKA)
0.076;-5228.1
JJ(TA)
0.072;-5661.3
(TQKA)
0.074;-7196.9
TTTA
0.061;-6527.5
TA(TK)
0.067;-5228.1
(TK)(JA)
0.073;-4795.0
KA(TJ)
0.064;-7630.0
TA(JK)
0.067;-7630.0
(TQ)(KA)
0.064;-4361.9
(TK)(KA)
0.107;-1093.8
J(JKA)
0.101;-4361.9
(QK)(JA)
0.105;-3928.7
JJ(KA)
0.065;-4361.9
QA(JQ)
0.072;-4361.9
JQKA
0.051;-9598.7
QK(QA)
0.086;-3495.6
QK(KA)
0.087;-3062.5
22(24)
0.008;-18418.8
22(28)
0.014;-16686.2
22(2Q)
0.020;-14953.8
24(23)
0.005;-20820.6
(23)(27)
0.014;-16686.2
2(23T)
0.012;-18221.9
2Q(23)
0.012;-17355.6
23(25)
0.005;-20387.5
2237
0.004;-22356.3
22(3T)
0.012;-18221.9
23(2K)
0.014;-16922.5
2(246)
0.007;-19521.3
28(24)
0.010;-18655.0
(24)(2J)
0.025;-14520.6
2244
0.006;-20387.5
22(47)
0.011;-19088.1
24(2T)
0.016;-17788.8
224Q
0.008;-19757.5
26(25)
0.007;-19088.1
(25)(29)
0.022;-14953.8
2(25Q)
0.018;-16489.4
22(56)
0.008;-19088.1
25(29)
0.009;-17788.8
225J
0.009;-19757.5
26(26)
0.021;-15820.0
(26)(29)
0.025;-14520.6
2(26Q)
0.017;-16056.3
22(67)
0.010;-18221.9
26(2T)
0.011;-16922.5
226Q
0.010;-18891.3
28(27)
0.017;-17355.6
(27)(2J)
0.021;-13221.3
2277
0.012;-17788.8
22(7T)
0.014;-16489.4
27(2K)
0.021;-15190.0
2(28T)
0.015;-16056.3
2Q(28)
0.022;-15190.0
28(2T)
0.012;-16056.3
228Q
0.013;-18025.0
2T(29)
0.017;-15623.1
(29)(2K)
0.031;-11488.8
229J
0.011;-18025.0
2T(2T)
0.031;-12355.0
(2T)(2K)
0.036;-11055.6
22TQ
0.014;-17158.8
2Q(2J)
0.024;-13890.6
2J(2K)
0.028;-13457.5
22QQ
0.022;-13457.5
3(234)
0.005;-20387.5
36(23)
0.008;-19521.3
(23)(39)
0.017;-15386.9
3(23Q)
0.015;-16922.5
5(234)
0.003;-22356.3
9(234)
0.006;-20623.8
K(234)
0.008;-18891.3
4(237)
0.005;-21490.0
49(23)
0.005;-20623.8
(23)(4Q)
0.015;-16489.4
(2357)
0.005;-21056.9
(235J)
0.008;-19324.4
(23)(56)
0.009;-18655.0
5(239)
0.009;-20190.6
5J(23)
0.010;-19324.4
(2367)
0.005;-20623.8
(236J)
0.008;-18891.3
(23)(67)
0.012;-17788.8
6(23T)
0.008;-19324.4
6Q(23)
0.010;-18458.1
9(237)
0.009;-19324.4
K(237)
0.013;-17591.9
7(23T)
0.009;-18891.3
7Q(23)
0.010;-18025.0
T(238)
0.009;-18458.1
8(239)
0.011;-18891.3
8J(23)
0.009;-18025.0
(239T)
0.012;-18025.0
99(23)
0.016;-15623.1
(23)(9Q)
0.027;-14323.8
(23TQ)
0.011;-16725.6
T(23Q)
0.017;-16725.6
Q(23J)
0.017;-16292.5
(23)(JK)
0.023;-13024.4
QK(23)
0.020;-15426.3
23(35)
0.007;-19954.4
33(28)
0.009;-18655.0
233T
0.004;-20623.8
23(3K)
0.019;-16489.4
(24)(36)
0.009;-19088.1
3(249)
0.006;-20623.8
3J(24)
0.006;-19757.5
(34)(25)
0.007;-19521.3
27(34)
0.005;-21490.0
2(34T)
0.006;-20190.6
(34)(2K)
0.018;-16056.3
34(26)
0.003;-21923.1
34(28)
0.005;-21056.9
34(2T)
0.008;-20190.6
34(2Q)
0.008;-19324.4
(25)(35)
0.016;-16253.1
3(258)
0.006;-20623.8
3T(25)
0.007;-19757.5
(25)(3K)
0.020;-15623.1
27(35)
0.005;-21056.9
2(35T)
0.008;-19757.5
(35)(2K)
0.015;-15623.1
35(27)
0.005;-21056.9
35(29)
0.007;-20190.6
35(2J)
0.012;-19324.4
35(2K)
0.008;-18458.1
37(26)
0.005;-20623.8
(26)(3T)
0.016;-16489.4
3(26K)
0.009;-18025.0
2(368)
0.005;-20190.6
(36)(2J)
0.021;-16056.3
2K(36)
0.010;-18025.0
23(68)
0.007;-20190.6
23(6T)
0.011;-19324.4
23(6Q)
0.011;-18458.1
3(278)
0.008;-19757.5
3T(27)
0.008;-18891.3
(27)(3K)
0.027;-14756.9
29(37)
0.007;-19324.4
2(37Q)
0.015;-18025.0
23(78)
0.010;-19757.5
23(7T)
0.008;-18891.3
23(7Q)
0.011;-18025.0
3(289)
0.010;-18891.3
3J(28)
0.010;-18025.0
(38)(29)
0.019;-16056.3
2J(38)
0.016;-18025.0
38(29)
0.009;-18891.3
38(2J)
0.011;-18025.0
38(2K)
0.018;-17158.8
3T(29)
0.014;-18025.0
(29)(3K)
0.026;-13890.6
2J(39)
0.011;-17591.9
39(2T)
0.011;-18025.0
39(2Q)
0.011;-17158.8
(2T)(3T)
0.025;-11921.9
3(2TK)
0.018;-16292.5
2(3TQ)
0.018;-16725.6
23(TJ)
0.014;-17158.8
23(TK)
0.017;-16292.5
(2J)(3K)
0.029;-13024.4
2K(3J)
0.017;-15859.4
23(JK)
0.022;-15859.4
(3Q)(2K)
0.032;-12591.3
(2K)(3K)
0.057;-9323.1
4(246)
0.011;-18655.0
48(24)
0.013;-17788.8
(24)(4J)
0.032;-13654.4
5(245)
0.010;-18655.0
9(245)
0.008;-19757.5
K(245)
0.014;-18025.0
5(248)
0.006;-20190.6
5T(24)
0.008;-19324.4
(24)(5K)
0.021;-15190.0
9(246)
0.008;-19324.4
K(246)
0.015;-17591.9
6(249)
0.007;-19324.4
6J(24)
0.008;-18458.1
(2478)
0.006;-19324.4
(247Q)
0.012;-17591.9
7(249)
0.009;-18891.3
7J(24)
0.015;-18025.0
(2489)
0.009;-18458.1
(248K)
0.018;-16725.6
8T(24)
0.013;-18025.0
(24)(8K)
0.020;-13890.6
Q(249)
0.017;-16725.6
(24)(9J)
0.022;-14323.8
T(24T)
0.026;-14323.8
T(24J)
0.017;-16725.6
TK(24)
0.019;-15859.4
(24)(JQ)
0.026;-13024.4
QQ(24)
0.030;-12591.3
24(45)
0.011;-19088.1
44(28)
0.011;-17788.8
244T
0.007;-19757.5
24(4K)
0.022;-15623.1
(25)(47)
0.015;-17788.8
4(25T)
0.006;-19324.4
4Q(25)
0.010;-18458.1
(45)(27)
0.009;-17788.8
29(45)
0.007;-19757.5
2(45Q)
0.013;-18458.1
24(56)
0.005;-21056.9
24(58)
0.006;-20190.6
24(5T)
0.008;-19324.4
24(5Q)
0.011;-18458.1
4(267)
0.005;-20190.6
49(26)
0.007;-19324.4
(26)(4Q)
0.024;-15190.0
27(46)
0.007;-20190.6
2(46T)
0.009;-18891.3
(46)(2K)
0.019;-14756.9
46(28)
0.008;-19757.5
46(2T)
0.008;-18891.3
46(2Q)
0.011;-18025.0
(27)(47)
0.019;-14087.5
4(27T)
0.010;-18458.1
4Q(27)
0.012;-17591.9
(47)(29)
0.016;-16056.3
2J(47)
0.013;-18025.0
47(28)
0.009;-19324.4
47(2T)
0.009;-18458.1
47(2Q)
0.010;-17591.9
(28)(48)
0.032;-13221.3
4(28J)
0.012;-17591.9
4K(28)
0.014;-16725.6
(48)(2J)
0.024;-14756.9
2K(48)
0.015;-16725.6
24(8T)
0.010;-18025.0
24(8Q)
0.019;-17158.8
4(29T)
0.013;-17591.9
4Q(29)
0.019;-16725.6
(49)(2J)
0.029;-14323.8
2K(49)
0.014;-16292.5
24(9J)
0.013;-17158.8
24(9K)
0.012;-16292.5
(2T)(4Q)
0.027;-13457.5
2J(4T)
0.014;-16725.6
4T(2J)
0.017;-16725.6
4T(2K)
0.020;-15859.4
4Q(2J)
0.015;-15859.4
(4J)(2K)
0.028;-12591.3
4J(2K)
0.018;-15426.3
4K(2Q)
0.026;-14993.1
24(QK)
0.019;-14993.1
(25)(56)
0.025;-14953.8
5(259)
0.018;-16489.4
5J(25)
0.022;-15623.1
(2567)
0.007;-19757.5
(256J)
0.012;-18025.0
(25)(67)
0.014;-16922.5
6(25T)
0.010;-18458.1
6Q(25)
0.011;-17591.9
9(257)
0.009;-18458.1
K(257)
0.013;-16725.6
7(25T)
0.010;-18025.0
7Q(25)
0.016;-17158.8
T(258)
0.009;-17591.9
8(259)
0.011;-18025.0
8J(25)
0.013;-17158.8
(259T)
0.012;-17158.8
99(25)
0.019;-14756.9
(25)(9Q)
0.026;-13457.5
(25TQ)
0.021;-15859.4
T(25Q)
0.022;-15859.4
Q(25J)
0.027;-15426.3
(25)(JK)
0.028;-12158.1
QK(25)
0.022;-14560.0
25(57)
0.014;-17355.6
55(2T)
0.020;-16056.3
255Q
0.009;-18025.0
57(26)
0.009;-19757.5
(26)(5T)
0.018;-15623.1
5(26K)
0.012;-17158.8
2(568)
0.010;-19324.4
(56)(2J)
0.026;-15190.0
2K(56)
0.013;-17158.8
25(68)
0.009;-19324.4
25(6T)
0.010;-18458.1
25(6Q)
0.013;-17591.9
5(278)
0.008;-18891.3
5T(27)
0.012;-18025.0
(27)(5K)
0.029;-13890.6
29(57)
0.010;-18458.1
2(57Q)
0.011;-17158.8
25(78)
0.008;-18891.3
25(7T)
0.011;-18025.0
25(7Q)
0.015;-17158.8
5(289)
0.008;-18025.0
5J(28)
0.012;-17158.8
(58)(29)
0.019;-15190.0
2J(58)
0.012;-17158.8
58(29)
0.012;-18025.0
58(2J)
0.011;-17158.8
58(2K)
0.017;-16292.5
5T(29)
0.014;-17158.8
(29)(5K)
0.036;-13024.4
2J(59)
0.013;-16725.6
59(2T)
0.014;-17158.8
59(2Q)
0.015;-16292.5
(2T)(5T)
0.037;-11055.6
5(2TK)
0.026;-15426.3
2(5TQ)
0.017;-15859.4
25(TJ)
0.016;-16292.5
25(TK)
0.025;-15426.3
(2J)(5K)
0.033;-12158.1
2K(5J)
0.021;-14993.1
25(JK)
0.026;-14993.1
(5Q)(2K)
0.035;-11725.0
(2K)(5K)
0.064;-8456.9
6(268)
0.013;-16056.3
6T(26)
0.020;-15190.0
(26)(6K)
0.042;-11055.6
T(267)
0.011;-17591.9
7(268)
0.013;-18458.1
7T(26)
0.010;-17591.9
(26)(7K)
0.023;-13457.5
J(268)
0.019;-16725.6
89(26)
0.010;-17591.9
(26)(8Q)
0.030;-13457.5
(269J)
0.015;-16292.5
(26)(9T)
0.028;-13890.6
9(26K)
0.019;-15426.3
(26TK)
0.021;-14993.1
TQ(26)
0.025;-15426.3
K(26J)
0.023;-14560.0
Q(26Q)
0.032;-11725.0
KK(26)
0.038;-10858.8
66(29)
0.020;-15623.1
266J
0.017;-17591.9
67(27)
0.018;-16056.3
(27)(6T)
0.025;-14756.9
6(27K)
0.016;-16292.5
2(679)
0.015;-18025.0
(67)(2Q)
0.028;-13890.6
27(68)
0.009;-18458.1
27(6T)
0.011;-17591.9
27(6Q)
0.012;-16725.6
68(28)
0.022;-15190.0
(28)(6J)
0.027;-13890.6
28(68)
0.025;-15190.0
2(68J)
0.017;-16725.6
2688
0.011;-18025.0
268T
0.008;-19993.8
268Q
0.008;-19127.5
(29)(6T)
0.023;-13890.6
6(29K)
0.018;-15426.3
2(69J)
0.016;-16292.5
2699
0.013;-17158.8
269J
0.007;-19127.5
269K
0.011;-18261.3
6Q(2T)
0.022;-15426.3
(6T)(2Q)
0.042;-12591.3
2T(6J)
0.015;-15859.4
2T(6K)
0.022;-14993.1
6(2JK)
0.018;-14560.0
2(6JK)
0.018;-14560.0
2J(6K)
0.021;-14560.0
2Q(6Q)
0.045;-11725.0
26QK
0.014;-16961.9
78(27)
0.026;-15190.0
(27)(7J)
0.043;-11055.6
8(278)
0.029;-14756.9
Q(278)
0.018;-15859.4
(27)(8T)
0.022;-13890.6
8(27K)
0.018;-15426.3
(279Q)
0.018;-15426.3
9(27J)
0.019;-15859.4
9K(27)
0.019;-14993.1
TT(27)
0.029;-13024.4
(27)(TK)
0.037;-11725.0
J(27Q)
0.017;-14560.0
K(27Q)
0.026;-13693.8
77(28)
0.020;-15190.0
277T
0.013;-17158.8
27(7K)
0.029;-13024.4
(28)(7T)
0.024;-13890.6
7(28K)
0.023;-15426.3
2(78T)
0.016;-16725.6
(78)(2K)
0.031;-12591.3
78(2T)
0.015;-16725.6
78(2Q)
0.018;-15859.4
(29)(79)
0.043;-11055.6
7(29Q)
0.020;-15426.3
2(79T)
0.019;-16292.5
(79)(2K)
0.036;-12158.1
79(2J)
0.019;-15859.4
79(2K)
0.021;-14993.1
7J(2T)
0.020;-15426.3
(7T)(2J)
0.027;-12591.3
2K(7T)
0.024;-14560.0
27(TQ)
0.023;-14993.1
7(2JQ)
0.028;-14560.0
2(7JQ)
0.019;-14560.0
27(JQ)
0.020;-14560.0
7(2QK)
0.030;-13693.8
7Q(2K)
0.029;-13693.8
88(28)
0.034;-11488.8
(28)(8J)
0.059;-10189.4
9(289)
0.022;-13457.5
K(289)
0.022;-14560.0
9(28Q)
0.023;-14993.1
J(28T)
0.018;-14993.1
TJ(28)
0.023;-14993.1
(28JQ)
0.034;-14126.9
J(28K)
0.026;-13693.8
(28)(QK)
0.038;-10425.6
88(2T)
0.028;-13457.5
288Q
0.019;-15426.3
8T(29)
0.016;-15859.4
(29)(8K)
0.032;-11725.0
2J(89)
0.021;-15426.3
89(2T)
0.017;-15859.4
89(2Q)
0.024;-14993.1
(2T)(8T)
0.050;-9756.3
8(2TK)
0.023;-14126.9
2(8TQ)
0.021;-14560.0
28(TJ)
0.016;-14993.1
28(TK)
0.023;-14126.9
(2J)(8K)
0.036;-10858.8
2K(8J)
0.026;-13693.8
28(JK)
0.027;-13693.8
(8Q)(2K)
0.045;-10425.6
(2K)(8K)
0.065;-7157.5
9(29J)
0.030;-12158.1
9K(29)
0.038;-11291.9
TT(29)
0.032;-12158.1
(29)(TK)
0.045;-10858.8
J(29Q)
0.026;-13693.8
K(29Q)
0.030;-12827.5
99(2T)
0.030;-12591.3
299Q
0.024;-14560.0
9J(2T)
0.028;-14560.0
(9T)(2J)
0.032;-11725.0
2K(9T)
0.025;-13693.8
29(TQ)
0.023;-14126.9
9(2JQ)
0.025;-13693.8
2(9JQ)
0.028;-13693.8
29(JQ)
0.026;-13693.8
9(2QK)
0.031;-12827.5
9Q(2K)
0.025;-12827.5
TT(2T)
0.043;-8890.0
(2T)(TK)
0.057;-7590.6
J(2TQ)
0.030;-13260.6
K(2TQ)
0.037;-12394.4
TT(2J)
0.050;-11291.9
2TTK
0.031;-13260.6
TK(2J)
0.032;-12827.5
2TJJ
0.027;-13693.8
2TJK
0.018;-15662.5
2(TQK)
0.034;-12394.4
TK(2K)
0.045;-9126.2
(2J)(JK)
0.076;-6724.4
QK(2J)
0.038;-11961.3
2J(JK)
0.035;-9559.4
(JQ)(2K)
0.041;-9126.2
(2K)(JK)
0.063;-5858.1
K(2QK)
0.047;-8260.0
2K(QK)
0.057;-8260.0
3335
0.008;-19521.3
3339
0.009;-17788.8
333K
0.016;-16056.3
36(34)
0.010;-18655.0
(34)(39)
0.020;-14520.6
3(34Q)
0.015;-16056.3
33(45)
0.009;-19088.1
34(38)
0.012;-17788.8
334T
0.006;-19757.5
33(4K)
0.020;-15623.1
(35)(37)
0.021;-14953.8
3(35T)
0.013;-16489.4
3Q(35)
0.018;-15623.1
35(37)
0.009;-17788.8
3359
0.009;-19757.5
33(5Q)
0.018;-15623.1
(36)(37)
0.023;-14520.6
3(36T)
0.016;-16056.3
3Q(36)
0.018;-15190.0
36(38)
0.011;-16922.5
336T
0.010;-18891.3
33(6K)
0.019;-14756.9
(37)(39)
0.020;-13221.3
3(37Q)
0.027;-14756.9
33(78)
0.015;-16489.4
37(3J)
0.021;-15190.0
337K
0.014;-17158.8
3T(38)
0.017;-15190.0
(38)(3K)
0.032;-11055.6
338T
0.010;-18025.0
33(8K)
0.021;-13890.6
(39)(3J)
0.046;-11488.8
3399
0.023;-15190.0
33(9Q)
0.029;-13890.6
(3T)(3J)
0.036;-11055.6
33TT
0.027;-14323.8
33(TK)
0.026;-13024.4
(3J)(3K)
0.037;-9756.3
33JK
0.022;-15426.3
33(QK)
0.031;-12158.1
45(34)
0.010;-18655.0
(34)(48)
0.019;-14520.6
4(34J)
0.020;-16056.3
4K(34)
0.023;-15190.0
(3459)
0.010;-19324.4
(345K)
0.014;-17591.9
57(34)
0.005;-20190.6
(34)(5T)
0.017;-16056.3
5(34K)
0.015;-17591.9
(3469)
0.012;-18891.3
(346K)
0.014;-17158.8
68(34)
0.009;-19324.4
(34)(6J)
0.017;-15190.0
7(347)
0.017;-16489.4
J(347)
0.010;-17591.9
78(34)
0.010;-18891.3
(34)(7J)
0.025;-14756.9
8(348)
0.019;-15623.1
Q(348)
0.021;-16725.6
(34)(8T)
0.018;-14756.9
8(34K)
0.017;-16292.5
(349Q)
0.016;-16292.5
9(34J)
0.020;-16725.6
9K(34)
0.019;-15859.4
TT(34)
0.024;-13890.6
(34)(TK)
0.034;-12591.3
J(34Q)
0.019;-15426.3
K(34Q)
0.021;-14560.0
44(35)
0.009;-18655.0
3447
0.005;-20623.8
34(4T)
0.014;-16489.4
44(3K)
0.016;-15190.0
4(357)
0.006;-20190.6
49(35)
0.009;-19324.4
(35)(4Q)
0.019;-15190.0
36(45)
0.006;-20623.8
3(459)
0.010;-19324.4
(45)(3Q)
0.021;-15190.0
35(46)
0.007;-20623.8
35(48)
0.006;-19757.5
35(4T)
0.010;-18891.3
35(4Q)
0.011;-18025.0
46(36)
0.017;-17355.6
(36)(49)
0.014;-16056.3
4(36Q)
0.012;-17591.9
3(467)
0.007;-19757.5
(46)(3T)
0.017;-15623.1
3Q(46)
0.011;-17591.9
3467
0.003;-22592.5
3469
0.005;-21726.3
346J
0.005;-20860.0
346K
0.007;-19993.8
49(37)
0.011;-18458.1
(37)(4Q)
0.030;-14323.8
38(47)
0.012;-18891.3
3(47J)
0.012;-17591.9
3477
0.010;-19324.4
3479
0.005;-21293.1
347J
0.006;-20426.9
347K
0.008;-19560.6
4T(38)
0.011;-17591.9
(38)(4K)
0.027;-13457.5
3T(48)
0.012;-17591.9
3(48K)
0.014;-16292.5
38(4T)
0.013;-17591.9
38(4Q)
0.013;-16725.6
49(39)
0.019;-14756.9
(39)(4Q)
0.027;-13457.5
3T(49)
0.012;-17158.8
3(49K)
0.020;-15859.4
39(4J)
0.014;-16725.6
39(4K)
0.015;-15859.4
4(3TQ)
0.015;-15859.4
3(4TJ)
0.017;-16292.5
34TT
0.013;-16725.6
34TQ
0.010;-18694.4
(3J)(4Q)
0.023;-12591.3
3Q(4J)
0.021;-15426.3
34JQ
0.013;-18261.3
(3Q)(4K)
0.036;-11725.0
3Q(4K)
0.016;-14560.0
5(356)
0.015;-17355.6
58(35)
0.017;-16489.4
(35)(5J)
0.029;-12355.0
6(356)
0.015;-16922.5
T(356)
0.010;-18025.0
6(357)
0.008;-19324.4
69(35)
0.009;-18458.1
(35)(6Q)
0.026;-14323.8
(3579)
0.013;-18025.0
(357K)
0.014;-16292.5
79(35)
0.015;-18025.0
(35)(7Q)
0.028;-13890.6
(358T)
0.013;-17158.8
88(35)
0.018;-15190.0
(35)(8J)
0.027;-13890.6
9(359)
0.026;-14323.8
K(359)
0.019;-15426.3
9(35Q)
0.015;-15859.4
J(35T)
0.019;-15859.4
TJ(35)
0.017;-15859.4
(35JQ)
0.014;-14993.1
J(35K)
0.017;-14560.0
(35)(QK)
0.027;-11291.9
55(37)
0.012;-16922.5
3559
0.010;-18891.3
35(5Q)
0.028;-14756.9
(36)(57)
0.015;-16489.4
5(36T)
0.012;-18025.0
5Q(36)
0.015;-17158.8
(56)(38)
0.015;-16056.3
3T(56)
0.012;-18025.0
3(56K)
0.015;-16725.6
36(58)
0.011;-18891.3
36(5T)
0.014;-18025.0
36(5Q)
0.016;-17158.8
57(37)
0.014;-16056.3
(37)(5T)
0.019;-14756.9
5(37K)
0.013;-16292.5
3(579)
0.011;-18025.0
(57)(3Q)
0.024;-13890.6
37(58)
0.014;-18458.1
37(5T)
0.015;-17591.9
37(5Q)
0.015;-16725.6
58(38)
0.015;-15190.0
(38)(5J)
0.026;-13890.6
38(58)
0.022;-15190.0
3(58J)
0.018;-16725.6
3588
0.009;-18025.0
358T
0.009;-19993.8
358Q
0.009;-19127.5
(39)(5T)
0.019;-13890.6
5(39K)
0.019;-15426.3
3(59J)
0.015;-16292.5
3599
0.012;-17158.8
359J
0.010;-19127.5
359K
0.015;-18261.3
5Q(3T)
0.017;-15426.3
(5T)(3Q)
0.026;-12591.3
3T(5J)
0.018;-15859.4
3T(5K)
0.021;-14993.1
5(3JK)
0.028;-14560.0
3(5JK)
0.021;-14560.0
3J(5K)
0.026;-14560.0
3Q(5Q)
0.034;-11725.0
35QK
0.018;-16961.9
67(36)
0.021;-16056.3
(36)(6T)
0.027;-11921.9
6(36K)
0.026;-13457.5
(367T)
0.013;-17158.8
77(36)
0.016;-15623.1
(36)(7T)
0.022;-14323.8
7(36K)
0.017;-15859.4
(368J)
0.016;-16292.5
(36)(89)
0.022;-14323.8
8(36Q)
0.020;-15859.4
T(369)
0.012;-16292.5
9(36T)
0.015;-16292.5
9Q(36)
0.023;-15426.3
Q(36T)
0.022;-14993.1
(36)(TQ)
0.038;-12158.1
(36JK)
0.026;-14126.9
JK(36)
0.023;-14126.9
K(36K)
0.055;-10425.6
3668
0.007;-18458.1
36(6J)
0.025;-14323.8
(37)(67)
0.026;-12788.1
6(37T)
0.016;-17158.8
6Q(37)
0.016;-16292.5
(67)(39)
0.019;-14756.9
3J(67)
0.020;-16725.6
67(38)
0.009;-18025.0
67(3T)
0.012;-17158.8
67(3Q)
0.016;-16292.5
(38)(68)
0.029;-11921.9
6(38J)
0.013;-16292.5
6K(38)
0.022;-15426.3
(68)(3J)
0.034;-13457.5
3K(68)
0.017;-15426.3
36(8T)
0.016;-16725.6
36(8Q)
0.016;-15859.4
6(39T)
0.015;-16292.5
6Q(39)
0.026;-15426.3
(69)(3J)
0.026;-13024.4
3K(69)
0.022;-14993.1
36(9J)
0.015;-15859.4
36(9K)
0.021;-14993.1
(3T)(6Q)
0.026;-12158.1
3J(6T)
0.023;-15426.3
6T(3J)
0.021;-15426.3
6T(3K)
0.026;-14560.0
6Q(3J)
0.023;-14560.0
(6J)(3K)
0.034;-11291.9
6J(3K)
0.022;-14126.9
6K(3Q)
0.026;-13693.8
36(QK)
0.024;-13693.8
(37)(78)
0.031;-11921.9
7(37J)
0.031;-13457.5
7K(37)
0.034;-12591.3
(378Q)
0.022;-15426.3
8(37T)
0.018;-16292.5
8Q(37)
0.022;-15426.3
J(379)
0.022;-15426.3
9T(37)
0.019;-15859.4
(37)(9K)
0.038;-11725.0
K(37T)
0.023;-14126.9
T(37K)
0.028;-14126.9
JJ(37)
0.029;-11725.0
(37QK)
0.025;-13260.6
3777
0.021;-15190.0
37(7T)
0.026;-13890.6
77(3K)
0.031;-12591.3
7(38T)
0.021;-16292.5
7Q(38)
0.019;-15426.3
(78)(3T)
0.028;-13457.5
3Q(78)
0.014;-15426.3
3789
0.009;-19560.6
378J
0.009;-18694.4
378K
0.011;-17828.1
7J(39)
0.025;-15426.3
(79)(3T)
0.030;-13024.4
3Q(79)
0.020;-14993.1
379T
0.009;-18694.4
379Q
0.010;-17828.1
(3T)(7J)
0.039;-12158.1
3T(7T)
0.027;-12591.3
3(7TK)
0.024;-14126.9
3T(7Q)
0.024;-14560.0
7J(3J)
0.044;-11725.0
(7J)(3Q)
0.036;-11291.9
3J(7Q)
0.029;-14126.9
7Q(3Q)
0.043;-10858.8
37QQ
0.023;-13693.8
37KK
0.030;-12827.5
8(38J)
0.029;-12591.3
8K(38)
0.041;-11725.0
(389K)
0.021;-14126.9
9J(38)
0.020;-14993.1
(38TJ)
0.028;-14560.0
(38)(TJ)
0.027;-11725.0
J(38J)
0.037;-11291.9
JQ(38)
0.028;-13693.8
Q(38K)
0.024;-12827.5
3889
0.021;-16292.5
38(8Q)
0.031;-12158.1
(39)(8T)
0.026;-12591.3
8(39K)
0.033;-14126.9
3(89J)
0.021;-14993.1
3899
0.016;-15859.4
389J
0.013;-17828.1
389K
0.015;-16961.9
8Q(3T)
0.026;-14126.9
(8T)(3Q)
0.042;-11291.9
3T(8J)
0.019;-14560.0
3T(8K)
0.032;-13693.8
8(3JK)
0.032;-13260.6
3(8JK)
0.034;-13260.6
3J(8K)
0.020;-13260.6
3Q(8Q)
0.046;-10425.6
38QK
0.019;-15662.5
9T(39)
0.037;-12158.1
(39)(9K)
0.063;-8023.8
K(39T)
0.028;-13260.6
T(39K)
0.029;-13260.6
JJ(39)
0.029;-10858.8
(39QK)
0.027;-12394.4
3999
0.028;-12591.3
39(9Q)
0.035;-11291.9
(3T)(9J)
0.038;-11291.9
3T(9T)
0.040;-11725.0
3(9TK)
0.036;-13260.6
3T(9Q)
0.026;-13693.8
9J(3J)
0.046;-10858.8
(9J)(3Q)
0.036;-10425.6
3J(9Q)
0.026;-13260.6
9Q(3Q)
0.046;-9992.5
39QQ
0.031;-12827.5
39KK
0.038;-11961.3
T(3TK)
0.041;-9992.5
JJ(3T)
0.037;-10425.6
(3TQK)
0.032;-11961.3
3TTT
0.042;-11291.9
3T(TK)
0.048;-9992.5
(3J)(TK)
0.036;-9559.4
3K(TJ)
0.033;-12394.4
3T(JK)
0.028;-12394.4
(TQ)(3K)
0.037;-9126.2
(3K)(TK)
0.072;-5858.1
J(3JK)
0.056;-9126.2
(3J)(QK)
0.045;-8693.1
JJ(3K)
0.051;-9126.2
3Q(JQ)
0.041;-9126.2
3JQK
0.022;-14363.1
QK(3Q)
0.043;-8260.0
QK(3K)
0.044;-7826.9
44(46)
0.028;-14953.8
44(4T)
0.026;-13221.3
(45)(45)
0.030;-12118.8
4(458)
0.013;-16489.4
4T(45)
0.020;-15623.1
(45)(4K)
0.032;-11488.8
4457
0.009;-19757.5
44(5T)
0.019;-15623.1
45(4K)
0.022;-14323.8
4(468)
0.018;-16056.3
4T(46)
0.017;-15190.0
(46)(4K)
0.047;-11055.6
4468
0.012;-18891.3
44(6J)
0.018;-14756.9
(47)(47)
0.046;-10386.2
4(47T)
0.018;-14756.9
4Q(47)
0.019;-13890.6
47(49)
0.023;-15190.0
447J
0.017;-17158.8
48(48)
0.035;-12355.0
(48)(4J)
0.037;-11055.6
4488
0.022;-15190.0
44(8J)
0.029;-13890.6
(49)(49)
0.047;-8653.8
4(49Q)
0.026;-13024.4
44(9T)
0.027;-13890.6
49(4K)
0.027;-12591.3
4(4TQ)
0.040;-12591.3
44(TJ)
0.021;-13024.4
(4J)(4J)
0.072;-6921.3
44JJ
0.035;-12591.3
4Q(4Q)
0.054;-8890.0
(4K)(4K)
0.106;-5188.8
(45)(57)
0.018;-13654.4
5(45T)
0.022;-15190.0
5Q(45)
0.024;-14323.8
8(456)
0.009;-18458.1
Q(456)
0.015;-16725.6
(45)(68)
0.021;-15623.1
6(45J)
0.013;-17158.8
6K(45)
0.013;-16292.5
(457J)
0.013;-16725.6
(45)(78)
0.021;-15190.0
7(45J)
0.013;-16725.6
7K(45)
0.017;-15859.4
(458Q)
0.023;-15859.4
8(45T)
0.015;-16725.6
8Q(45)
0.021;-15859.4
J(459)
0.018;-15859.4
9T(45)
0.014;-16292.5
(45)(9K)
0.026;-12158.1
K(45T)
0.022;-14560.0
T(45K)
0.024;-14560.0
JJ(45)
0.029;-12158.1
(45QK)
0.024;-13693.8
4555
0.011;-17355.6
45(58)
0.018;-16056.3
55(4J)
0.023;-14756.9
455K
0.012;-16725.6
58(46)
0.011;-18458.1
(46)(5J)
0.027;-14323.8
46(56)
0.016;-16489.4
4(569)
0.009;-18025.0
(56)(4Q)
0.026;-13890.6
46(57)
0.008;-18891.3
46(59)
0.009;-18025.0
46(5J)
0.016;-17158.8
46(5K)
0.016;-16292.5
5(479)
0.010;-17591.9
5J(47)
0.014;-16725.6
(57)(48)
0.016;-15190.0
4T(57)
0.015;-17158.8
4(57K)
0.015;-15859.4
47(59)
0.015;-17591.9
47(5J)
0.014;-16725.6
47(5K)
0.017;-15859.4
5(48T)
0.017;-16725.6
5Q(48)
0.019;-15859.4
(58)(4T)
0.023;-13890.6
4Q(58)
0.018;-15859.4
4589
0.007;-19993.8
458J
0.010;-19127.5
458K
0.012;-18261.3
5J(49)
0.015;-15859.4
(59)(4T)
0.034;-13457.5
4Q(59)
0.021;-15426.3
459T
0.010;-19127.5
459Q
0.010;-18261.3
(4T)(5J)
0.031;-12591.3
4T(5T)
0.029;-13024.4
4(5TK)
0.022;-14560.0
4T(5Q)
0.023;-14993.1
5J(4J)
0.033;-12158.1
(5J)(4Q)
0.033;-11725.0
4J(5Q)
0.021;-14560.0
5Q(4Q)
0.036;-11291.9
45QQ
0.029;-14126.9
45KK
0.024;-13260.6
6(469)
0.015;-14756.9
6J(46)
0.025;-13890.6
(4678)
0.015;-17591.9
(467Q)
0.016;-15859.4
7(469)
0.014;-17158.8
7J(46)
0.015;-16292.5
(4689)
0.011;-16725.6
(468K)
0.021;-14993.1
8T(46)
0.016;-16292.5
(46)(8K)
0.033;-12158.1
Q(469)
0.019;-14993.1
(46)(9J)
0.023;-12591.3
T(46T)
0.033;-12591.3
T(46J)
0.023;-14993.1
TK(46)
0.026;-14126.9
(46)(JQ)
0.036;-11291.9
QQ(46)
0.034;-10858.8
46(67)
0.019;-15623.1
66(4T)
0.023;-14323.8
466Q
0.016;-16292.5
68(47)
0.010;-17591.9
(47)(6J)
0.026;-13457.5
47(67)
0.019;-15190.0
4(67T)
0.014;-16725.6
(67)(4K)
0.032;-12591.3
67(49)
0.014;-17158.8
67(4J)
0.022;-16292.5
67(4K)
0.017;-15426.3
69(48)
0.016;-16725.6
(48)(6Q)
0.029;-12591.3
49(68)
0.014;-16725.6
4(68Q)
0.025;-15426.3
46(89)
0.013;-16725.6
46(8J)
0.020;-15859.4
46(8K)
0.020;-14993.1
(49)(6J)
0.028;-12591.3
49(69)
0.026;-13457.5
4(69Q)
0.021;-14993.1
46(9T)
0.015;-15859.4
46(9Q)
0.022;-14993.1
6(4TJ)
0.019;-14993.1
6K(4T)
0.028;-14126.9
(6T)(4K)
0.033;-11291.9
6T(4Q)
0.023;-14560.0
(4J)(6J)
0.055;-8890.0
4J(6J)
0.028;-11725.0
6J(4Q)
0.023;-14126.9
(4Q)(6Q)
0.051;-8023.8
4K(6Q)
0.028;-13260.6
4K(6K)
0.046;-9992.5
79(47)
0.025;-13890.6
(47)(7Q)
0.045;-9756.3
(478T)
0.018;-15859.4
88(47)
0.024;-13890.6
(47)(8J)
0.033;-12591.3
9(479)
0.033;-13024.4
K(479)
0.017;-14126.9
9(47Q)
0.024;-14560.0
J(47T)
0.019;-14560.0
TJ(47)
0.022;-14560.0
(47JQ)
0.026;-13693.8
J(47K)
0.030;-13260.6
(47)(QK)
0.039;-9992.5
77(49)
0.019;-13890.6
477J
0.022;-15859.4
78(48)
0.022;-13890.6
(48)(7J)
0.030;-12591.3
48(78)
0.020;-13890.6
4(78J)
0.021;-15426.3
4788
0.017;-16725.6
478T
0.009;-18694.4
478Q
0.014;-17828.1
(49)(7T)
0.032;-12591.3
7(49K)
0.027;-14126.9
4(79J)
0.016;-14993.1
4799
0.017;-15859.4
479J
0.010;-17828.1
479K
0.013;-16961.9
7Q(4T)
0.021;-14126.9
(7T)(4Q)
0.036;-11291.9
4T(7J)
0.017;-14560.0
4T(7K)
0.033;-13693.8
7(4JK)
0.029;-13260.6
4(7JK)
0.029;-13260.6
4J(7K)
0.031;-13260.6
4Q(7Q)
0.035;-10425.6
47QK
0.020;-15662.5
89(48)
0.028;-13024.4
(48)(8Q)
0.047;-8890.0
(489J)
0.019;-14560.0
(48)(9T)
0.032;-12158.1
9(48K)
0.027;-13693.8
(48TK)
0.027;-13260.6
TQ(48)
0.029;-13693.8
K(48J)
0.026;-12827.5
Q(48Q)
0.048;-9992.5
KK(48)
0.047;-9126.2
88(4J)
0.031;-12158.1
488K
0.023;-14126.9
8J(49)
0.025;-14560.0
(89)(4T)
0.026;-12158.1
4Q(89)
0.029;-14126.9
489T
0.013;-17828.1
489Q
0.014;-16961.9
(4T)(8J)
0.036;-11291.9
4T(8T)
0.027;-11725.0
4(8TK)
0.029;-13260.6
4T(8Q)
0.025;-13693.8
8J(4J)
0.041;-10858.8
(8J)(4Q)
0.041;-10425.6
4J(8Q)
0.034;-13260.6
8Q(4Q)
0.049;-9992.5
48QQ
0.032;-12827.5
48KK
0.041;-11961.3
9(49Q)
0.038;-10858.8
J(49T)
0.025;-13693.8
TJ(49)
0.036;-13693.8
(49JQ)
0.028;-12827.5
J(49K)
0.023;-12394.4
(49)(QK)
0.063;-9126.2
99(4J)
0.046;-11291.9
499K
0.024;-13260.6
9Q(4T)
0.030;-13260.6
(9T)(4Q)
0.045;-10425.6
4T(9J)
0.027;-13693.8
4T(9K)
0.032;-12827.5
9(4JK)
0.034;-12394.4
4(9JK)
0.034;-12394.4
4J(9K)
0.032;-12394.4
4Q(9Q)
0.049;-9559.4
49QK
0.022;-14796.2
TJ(4T)
0.049;-10425.6
(4TJQ)
0.029;-12394.4
J(4TK)
0.036;-11961.3
(4T)(QK)
0.051;-8693.1
TT(4Q)
0.050;-9992.5
T(4JQ)
0.027;-12394.4
4(TJQ)
0.026;-12394.4
4T(JQ)
0.034;-12394.4
T(4QK)
0.034;-11528.1
TQ(4K)
0.044;-11528.1
JJ(4J)
0.075;-6724.4
(4JQK)
0.033;-11095.0
4JJJ
0.061;-9559.4
JQ(4Q)
0.047;-8693.1
4JQQ
0.042;-11528.1
4JKK
0.033;-10661.9
QQ(4K)
0.054;-7826.9
4KKK
0.054;-6960.6
55(59)
0.024;-12355.0
55(5K)
0.036;-10622.5
(56)(58)
0.032;-12355.0
5(56J)
0.026;-13890.6
5K(56)
0.038;-13024.4
56(59)
0.023;-14756.9
556J
0.013;-16725.6
57(57)
0.024;-12355.0
(57)(5T)
0.035;-11055.6
5(57K)
0.028;-12591.3
55(79)
0.024;-14323.8
57(5Q)
0.026;-13024.4
5(589)
0.024;-13890.6
5J(58)
0.034;-13024.4
58(59)
0.023;-13890.6
558J
0.018;-15859.4
59(59)
0.032;-10622.5
(59)(5Q)
0.047;-9323.1
559T
0.015;-15859.4
55(9K)
0.037;-11725.0
(5T)(5Q)
0.041;-8890.0
55TJ
0.020;-14993.1
5J(5J)
0.058;-8890.0
5J(5Q)
0.036;-11291.9
5(5QK)
0.044;-10425.6
5K(5K)
0.050;-7157.5
68(56)
0.016;-14756.9
(56)(6J)
0.048;-10622.5
7(567)
0.024;-14756.9
J(567)
0.014;-15859.4
78(56)
0.010;-17158.8
(56)(7J)
0.033;-13024.4
8(568)
0.026;-13890.6
Q(568)
0.023;-14993.1
(56)(8T)
0.031;-13024.4
8(56K)
0.018;-14560.0
(569Q)
0.021;-14560.0
9(56J)
0.021;-14993.1
9K(56)
0.026;-14126.9
TT(56)
0.036;-12158.1
(56)(TK)
0.036;-10858.8
J(56Q)
0.029;-13693.8
K(56Q)
0.025;-12827.5
66(57)
0.021;-15190.0
5669
0.019;-17158.8
56(6Q)
0.028;-13024.4
(57)(68)
0.019;-14323.8
6(57J)
0.017;-15859.4
6K(57)
0.024;-14993.1
(67)(5T)
0.022;-13457.5
5Q(67)
0.018;-15426.3
5678
0.007;-19993.8
567T
0.007;-19127.5
567Q
0.010;-18261.3
(58)(69)
0.020;-13457.5
6(58Q)
0.019;-14993.1
5(689)
0.020;-16292.5
(68)(5Q)
0.031;-12158.1
58(69)
0.015;-16292.5
58(6J)
0.015;-15426.3
58(6K)
0.022;-14560.0
6(59J)
0.020;-14993.1
6K(59)
0.022;-14126.9
(69)(5Q)
0.036;-11725.0
59(6T)
0.017;-15426.3
59(6Q)
0.022;-14560.0
6T(5T)
0.041;-12158.1
(5T)(6K)
0.046;-10858.8
5Q(6T)
0.027;-14126.9
56TJ
0.013;-17395.0
56TK
0.013;-16528.8
6K(5J)
0.035;-13260.6
56JJ
0.026;-14126.9
56JK
0.015;-16095.6
5(6QK)
0.034;-12827.5
6K(5K)
0.040;-9559.4
(57)(79)
0.032;-10622.5
7(57Q)
0.034;-12158.1
9(578)
0.023;-15859.4
K(578)
0.022;-14126.9
8(57J)
0.018;-14993.1
8K(57)
0.021;-14126.9
(579K)
0.027;-13693.8
9J(57)
0.021;-14560.0
(57TJ)
0.031;-14126.9
(57)(TJ)
0.043;-11291.9
J(57J)
0.035;-10858.8
JQ(57)
0.028;-13260.6
Q(57K)
0.028;-12394.4
5778
0.019;-16725.6
57(7J)
0.030;-12591.3
(58)(78)
0.045;-10622.5
7(58J)
0.018;-14993.1
7K(58)
0.021;-14126.9
(78)(5J)
0.033;-12158.1
5K(78)
0.031;-14126.9
57(8T)
0.015;-15426.3
57(8Q)
0.019;-14560.0
7(59T)
0.018;-14993.1
7Q(59)
0.019;-14126.9
(79)(5J)
0.036;-11725.0
5K(79)
0.023;-13693.8
57(9J)
0.019;-14560.0
57(9K)
0.026;-13693.8
(5T)(7Q)
0.046;-10858.8
5J(7T)
0.023;-14126.9
7T(5J)
0.027;-14126.9
7T(5K)
0.028;-13260.6
7Q(5J)
0.027;-13260.6
(7J)(5K)
0.039;-9992.5
7J(5K)
0.029;-12827.5
7K(5Q)
0.030;-12394.4
57(QK)
0.030;-12394.4
(58)(89)
0.055;-9756.3
8(58Q)
0.036;-11291.9
T(589)
0.024;-14560.0
9(58T)
0.021;-14560.0
9Q(58)
0.034;-13693.8
Q(58T)
0.025;-13260.6
(58)(TQ)
0.038;-10425.6
(58JK)
0.031;-12394.4
JK(58)
0.036;-12394.4
K(58K)
0.052;-8693.1
588T
0.022;-14993.1
58(8K)
0.038;-10858.8
(59)(8J)
0.044;-11291.9
59(89)
0.029;-12158.1
5(89Q)
0.025;-13693.8
58(9T)
0.022;-14560.0
58(9Q)
0.024;-13693.8
8(5TJ)
0.020;-13693.8
8K(5T)
0.026;-12827.5
(8T)(5K)
0.037;-9992.5
8T(5Q)
0.025;-13260.6
(5J)(8J)
0.061;-7590.6
5J(8J)
0.033;-10425.6
8J(5Q)
0.034;-12827.5
(5Q)(8Q)
0.073;-6724.4
5K(8Q)
0.038;-11961.3
5K(8K)
0.064;-8693.1
9J(59)
0.034;-10858.8
(59TJ)
0.025;-13260.6
(59)(TJ)
0.040;-10425.6
J(59J)
0.034;-9992.5
JQ(59)
0.029;-12394.4
Q(59K)
0.034;-11528.1
599T
0.025;-14126.9
59(9K)
0.040;-9992.5
(5T)(9Q)
0.047;-9992.5
5J(9T)
0.030;-13260.6
9T(5J)
0.021;-13260.6
9T(5K)
0.035;-12394.4
9Q(5J)
0.037;-12394.4
(9J)(5K)
0.040;-9126.2
9J(5K)
0.036;-11961.3
9K(5Q)
0.039;-11528.1
59(QK)
0.035;-11528.1
(5T)(TJ)
0.053;-7157.5
J(5TJ)
0.048;-9559.4
JQ(5T)
0.028;-11961.3
Q(5TK)
0.040;-11095.0
5TTJ
0.022;-12827.5
TJ(5J)
0.042;-9559.4
(TJ)(5Q)
0.057;-9126.2
5J(TQ)
0.035;-11961.3
TQ(5Q)
0.050;-8693.1
5TQQ
0.041;-11528.1
5TKK
0.035;-10661.9
Q(5JQ)
0.058;-8260.0
KK(5J)
0.064;-7393.7
(5Q)(JQ)
0.069;-5425.0
5K(JQ)
0.048;-10661.9
5K(JK)
0.063;-7393.7
5QQQ
0.054;-7826.9
KK(5K)
0.087;-3692.5
6669
0.021;-13890.6
666K
0.036;-12158.1
69(67)
0.032;-13457.5
(67)(6Q)
0.045;-9323.1
6678
0.016;-16725.6
66(7J)
0.034;-12591.3
(68)(68)
0.053;-7787.5
6(68J)
0.044;-12158.1
6K(68)
0.032;-11291.9
68(6J)
0.035;-12158.1
668K
0.023;-14126.9
6J(69)
0.036;-11725.0
69(6T)
0.041;-12158.1
669Q
0.023;-14126.9
6J(6T)
0.039;-11291.9
6T(6J)
0.033;-11291.9
66TK
0.027;-13260.6
6K(6J)
0.038;-9992.5
(6Q)(6Q)
0.085;-4322.5
66QK
0.039;-12394.4
7(679)
0.025;-13024.4
7J(67)
0.029;-12158.1
(6789)
0.017;-15426.3
(678K)
0.024;-13693.8
8T(67)
0.021;-14993.1
(67)(8K)
0.037;-10858.8
Q(679)
0.028;-13693.8
(67)(9J)
0.043;-11291.9
T(67T)
0.032;-11291.9
T(67J)
0.028;-13693.8
TK(67)
0.035;-12827.5
(67)(JQ)
0.039;-9992.5
QQ(67)
0.040;-9559.4
67(78)
0.022;-13457.5
77(6J)
0.035;-12158.1
677K
0.031;-14126.9
7T(68)
0.019;-14993.1
(68)(7K)
0.032;-10858.8
6T(78)
0.017;-14993.1
6(78K)
0.031;-13693.8
68(7T)
0.020;-14993.1
68(7Q)
0.019;-14126.9
79(69)
0.037;-12158.1
(69)(7Q)
0.031;-10858.8
6T(79)
0.028;-14560.0
6(79K)
0.022;-13260.6
69(7J)
0.020;-14126.9
69(7K)
0.023;-13260.6
7(6TQ)
0.024;-13260.6
6(7TJ)
0.030;-13693.8
67TT
0.019;-14126.9
67TQ
0.020;-16095.6
(6J)(7Q)
0.042;-9992.5
6Q(7J)
0.032;-12827.5
67JQ
0.021;-15662.5
(6Q)(7K)
0.053;-9126.2
6Q(7K)
0.029;-11961.3
8(689)
0.041;-12158.1
8J(68)
0.028;-11291.9
(689T)
0.025;-14126.9
99(68)
0.031;-11725.0
(68)(9Q)
0.038;-10425.6
(68TQ)
0.029;-12827.5
T(68Q)
0.025;-12827.5
Q(68J)
0.035;-12394.4
(68)(JK)
0.043;-9126.2
QK(68)
0.027;-11528.1
68(8T)
0.029;-11725.0
88(6K)
0.036;-10425.6
8(69J)
0.029;-13693.8
8K(69)
0.023;-12827.5
(89)(6Q)
0.041;-10425.6
69(8T)
0.029;-14126.9
69(8Q)
0.027;-13260.6
8T(6T)
0.042;-10858.8
(6T)(8K)
0.048;-9559.4
6Q(8T)
0.026;-12827.5
68TJ
0.016;-16095.6
68TK
0.019;-15229.4
8K(6J)
0.035;-11961.3
68JJ
0.026;-12827.5
68JK
0.018;-14796.2
6(8QK)
0.032;-11528.1
8K(6K)
0.052;-8260.0
(69)(9J)
0.064;-7590.6
T(69T)
0.045;-10425.6
T(69J)
0.037;-12827.5
TK(69)
0.028;-11961.3
(69)(JQ)
0.060;-9126.2
QQ(69)
0.046;-8693.1
69(9T)
0.032;-10858.8
99(6K)
0.043;-9559.4
9(6TQ)
0.028;-12394.4
6(9TJ)
0.028;-12827.5
69TT
0.029;-13260.6
69TQ
0.022;-15229.4
(6J)(9Q)
0.039;-9126.2
6Q(9J)
0.027;-11961.3
69JQ
0.027;-14796.2
(6Q)(9K)
0.060;-8260.0
6Q(9K)
0.044;-11095.0
T(6TJ)
0.056;-9559.4
TK(6T)
0.045;-8693.1
(6T)(JQ)
0.047;-8693.1
QQ(6T)
0.054;-8260.0
6T(TJ)
0.058;-9559.4
(6J)(TJ)
0.063;-6291.3
6J(TJ)
0.040;-9126.2
TJ(6Q)
0.030;-11528.1
(6Q)(TQ)
0.067;-5425.0
6K(TQ)
0.035;-10661.9
6K(TK)
0.064;-7393.7
JK(6J)
0.054;-7826.9
K(6JK)
0.061;-6960.6
6JJK
0.036;-10661.9
6(JQK)
0.046;-10228.8
JK(6K)
0.079;-6960.6
KK(6Q)
0.078;-6527.5
6QKK
0.048;-9362.5
77(7T)
0.047;-9323.1
(78)(78)
0.070;-6921.3
7(78J)
0.032;-11291.9
7K(78)
0.037;-10425.6
78(7J)
0.035;-11291.9
778K
0.028;-13260.6
7J(79)
0.046;-10858.8
79(7T)
0.031;-11291.9
779Q
0.020;-13260.6
7J(7T)
0.039;-10425.6
7T(7J)
0.050;-10425.6
77TK
0.030;-12394.4
7K(7J)
0.049;-9126.2
(7Q)(7Q)
0.097;-3456.2
77QK
0.047;-11528.1
8(78T)
0.037;-11291.9
8Q(78)
0.035;-10425.6
J(789)
0.030;-13260.6
9T(78)
0.023;-13693.8
(78)(9K)
0.054;-9559.4
K(78T)
0.027;-11961.3
T(78K)
0.032;-11961.3
JJ(78)
0.050;-9559.4
(78QK)
0.034;-11095.0
7888
0.038;-12158.1
78(8J)
0.050;-10858.8
(79)(89)
0.064;-8456.9
8(79Q)
0.032;-12827.5
7(89T)
0.025;-13693.8
(89)(7K)
0.049;-9559.4
89(7J)
0.030;-13260.6
89(7K)
0.032;-12394.4
8J(7T)
0.030;-12827.5
(8T)(7J)
0.037;-9992.5
7K(8T)
0.035;-11961.3
78(TQ)
0.030;-12394.4
8(7JQ)
0.032;-11961.3
7(8JQ)
0.037;-11961.3
78(JQ)
0.026;-11961.3
8(7QK)
0.039;-11095.0
8Q(7K)
0.034;-11095.0
99(79)
0.049;-8023.8
(79)(9Q)
0.059;-6724.4
(79TQ)
0.037;-11961.3
T(79Q)
0.038;-11961.3
Q(79J)
0.032;-11528.1
(79)(JK)
0.068;-8260.0
QK(79)
0.034;-10661.9
79(9J)
0.037;-9992.5
(7T)(9T)
0.066;-7157.5
9(7TK)
0.043;-11528.1
7(9TQ)
0.032;-11961.3
79(TJ)
0.034;-12394.4
79(TK)
0.044;-11528.1
(7J)(9K)
0.058;-8260.0
7K(9J)
0.035;-11095.0
79(JK)
0.048;-11095.0
(9Q)(7K)
0.058;-7826.9
(7K)(9K)
0.071;-4558.8
T(7TQ)
0.042;-8693.1
Q(7TJ)
0.033;-11095.0
(7T)(JK)
0.078;-7826.9
QK(7T)
0.039;-10228.8
7T(TQ)
0.065;-8693.1
(7J)(TQ)
0.055;-8260.0
7Q(TJ)
0.040;-11095.0
7TJQ
0.032;-13930.0
(7Q)(TK)
0.058;-7393.7
7Q(TK)
0.055;-10228.8
J(7JQ)
0.077;-7826.9
K(7JQ)
0.040;-9795.6
JJ(7Q)
0.060;-7826.9
J(7QK)
0.047;-9795.6
JQ(7K)
0.041;-9795.6
QQ(7Q)
0.097;-4125.6
7Q(QK)
0.057;-6527.5
8888
0.044;-8890.0
888Q
0.042;-9992.5
8(89J)
0.047;-9992.5
8K(89)
0.054;-9126.2
89(8Q)
0.039;-9559.4
8(8TJ)
0.044;-9559.4
8K(8T)
0.046;-8693.1
8T(8K)
0.054;-8693.1
8(8JK)
0.065;-8260.0
88(JK)
0.059;-8260.0
8Q(8K)
0.052;-7826.9
(89)(9T)
0.072;-7157.5
9(89K)
0.055;-8693.1
(89TK)
0.035;-11095.0
TQ(89)
0.040;-11528.1
K(89J)
0.036;-10661.9
Q(89Q)
0.054;-7826.9
KK(89)
0.058;-6960.6
99(8Q)
0.043;-9126.2
9(8TJ)
0.035;-11961.3
9K(8T)
0.038;-11095.0
(9T)(8K)
0.049;-8260.0
9T(8Q)
0.043;-11528.1
(8J)(9J)
0.082;-5858.1
8J(9J)
0.051;-8693.1
9J(8Q)
0.047;-11095.0
(8Q)(9Q)
0.065;-4991.9
8K(9Q)
0.040;-10228.8
8K(9K)
0.075;-6960.6
TQ(8T)
0.042;-8260.0
K(8TJ)
0.045;-10228.8
Q(8TQ)
0.065;-7393.7
KK(8T)
0.069;-6527.5
