AAAA
0.149;-1190.0
5AAA
0.076;-1831.2
9AAA
0.102;-1666.2
KAAA
0.135;-1501.2
4A(2A)
0.038;-2367.5
(2A)(7A)
0.098;-1973.8
A(2TA)
0.074;-2120.0
QA(2A)
0.073;-2037.5
2A(4A)
0.054;-2367.5
26AA
0.039;-2555.0
AA(29)
0.079;-2161.2
2A(QA)
0.073;-2037.5
A(34A)
0.056;-2326.2
6A(3A)
0.050;-2243.8
(3A)(9A)
0.096;-1850.0
A(3QA)
0.082;-1996.3
AA(34)
0.046;-2326.2
3A(7A)
0.061;-2202.5
39AA
0.047;-2390.0
AA(3Q)
0.084;-1996.3
(4A)(5A)
0.068;-1973.8
A(48A)
0.054;-2120.0
TA(4A)
0.082;-2037.5
(4A)(KA)
0.112;-1643.7
46AA
0.041;-2472.5
AA(49)
0.083;-2078.8
4A(QA)
0.066;-1955.0
A(56A)
0.063;-2161.2
8A(5A)
0.083;-2078.8
(5A)(JA)
0.088;-1685.0
55AA
0.051;-2202.5
AA(58)
0.094;-2078.8
5A(JA)
0.071;-1955.0
5KAA
0.086;-2142.5
8A(6A)
0.061;-2037.5
(6A)(JA)
0.106;-1643.7
66AA
0.052;-2120.0
AA(69)
0.073;-1996.3
6A(QA)
0.102;-1872.5
A(78A)
0.086;-1996.3
TA(7A)
0.069;-1913.8
(7A)(KA)
0.116;-1520.0
79AA
0.074;-2225.0
AA(7Q)
0.107;-1831.3
(8A)(9A)
0.117;-1643.7
A(8QA)
0.091;-1790.0
AA(89)
0.100;-1913.8
8A(QA)
0.090;-1790.0
A(9TA)
0.105;-1831.3
QA(9A)
0.088;-1748.8
9A(JA)
0.107;-1790.0
9KAA
0.075;-1977.5
QA(TA)
0.104;-1707.5
TA(QA)
0.116;-1707.5
A(JQA)
0.129;-1666.3
AA(JQ)
0.103;-1666.3
(QA)(KA)
0.119;-1313.8
KKAA
0.156;-1542.5
2(25A)
0.026;-2821.2
27(2A)
0.026;-2738.8
(2T)(2A)
0.056;-2345.0
2(2KA)
0.036;-2491.2
(236A)
0.016;-3008.8
(23TA)
0.023;-2843.8
33(2A)
0.020;-2862.5
(36)(2A)
0.028;-2738.8
3(29A)
0.015;-2885.0
3J(2A)
0.025;-2802.5
(245A)
0.015;-3008.8
(249A)
0.023;-2843.8
(24KA)
0.029;-2678.8
46(2A)
0.023;-2967.5
(49)(2A)
0.030;-2573.8
4(2QA)
0.033;-2720.0
6(25A)
0.016;-2926.2
T(25A)
0.027;-2761.2
5(26A)
0.022;-2926.2
58(2A)
0.018;-2843.8
(5J)(2A)
0.038;-2450.0
6(26A)
0.041;-2615.0
T(26A)
0.031;-2720.0
6(27A)
0.024;-2843.8
69(2A)
0.029;-2761.2
(6Q)(2A)
0.060;-2367.5
(279A)
0.022;-2720.0
(27KA)
0.041;-2555.0
79(2A)
0.028;-2720.0
(7Q)(2A)
0.057;-2326.3
(28TA)
0.032;-2637.5
88(2A)
0.034;-2450.0
(8J)(2A)
0.050;-2326.3
9(29A)
0.044;-2367.5
K(29A)
0.047;-2472.5
9(2QA)
0.041;-2513.8
J(2TA)
0.036;-2513.8
TJ(2A)
0.043;-2513.8
(2JQA)
0.041;-2431.2
J(2KA)
0.046;-2390.0
(QK)(2A)
0.076;-2078.8
22(4A)
0.020;-2862.5
226A
0.015;-3050.0
2A(29)
0.040;-2656.2
22(QA)
0.050;-2532.5
2(34A)
0.013;-3091.2
26(3A)
0.019;-3008.8
(29)(3A)
0.030;-2615.0
2(3QA)
0.027;-2761.2
A(234)
0.011;-3091.2
(23)(7A)
0.030;-2697.5
9A(23)
0.019;-2885.0
A(23Q)
0.025;-2761.2
2A(34)
0.018;-3091.2
2A(36)
0.013;-3008.8
2A(38)
0.018;-2926.2
2A(3T)
0.018;-2843.8
2A(3Q)
0.022;-2761.2
2(45A)
0.014;-3008.8
27(4A)
0.020;-2926.2
(2T)(4A)
0.036;-2532.5
2(4KA)
0.025;-2678.8
A(246)
0.014;-2967.5
(24)(9A)
0.035;-2573.8
JA(24)
0.033;-2761.2
24(5A)
0.014;-3008.8
24(7A)
0.021;-2926.2
24(9A)
0.024;-2843.8
24(JA)
0.031;-2761.2
24(KA)
0.034;-2678.8
26(5A)
0.015;-2926.2
(29)(5A)
0.051;-2532.5
2(5QA)
0.030;-2678.8
A(256)
0.018;-2926.2
(25)(9A)
0.038;-2532.5
JA(25)
0.026;-2720.0
25(6A)
0.022;-2926.2
25(8A)
0.021;-2843.8
25(TA)
0.021;-2761.2
25(QA)
0.024;-2678.8
(26)(6A)
0.052;-2345.0
2(69A)
0.028;-2761.2
2J(6A)
0.035;-2678.8
(26)(7A)
0.031;-2573.8
9A(26)
0.029;-2761.2
A(26Q)
0.025;-2637.5
2A(67)
0.028;-2843.8
2A(69)
0.022;-2761.2
2A(6J)
0.040;-2678.8
2A(6K)
0.037;-2596.2
(29)(7A)
0.035;-2450.0
2(7QA)
0.026;-2596.2
A(278)
0.023;-2761.2
(27)(JA)
0.045;-2367.5
KA(27)
0.043;-2555.0
2A(79)
0.029;-2720.0
2A(7J)
0.031;-2637.5
2A(7K)
0.033;-2555.0
(2T)(8A)
0.039;-2367.5
2(8KA)
0.039;-2513.8
A(28T)
0.025;-2637.5
(28)(KA)
0.062;-2243.8
28(TA)
0.034;-2637.5
28(QA)
0.030;-2555.0
(29)(9A)
0.062;-2097.5
2(9QA)
0.033;-2513.8
A(29T)
0.034;-2596.2
(29)(KA)
0.068;-2202.5
29(JA)
0.032;-2555.0
29(KA)
0.045;-2472.5
2J(TA)
0.041;-2513.8
(2T)(JA)
0.064;-2243.8
KA(2T)
0.044;-2431.2
2A(TQ)
0.035;-2472.5
2(JQA)
0.050;-2431.2
A(2JQ)
0.043;-2431.2
2A(JQ)
0.053;-2431.2
2(QKA)
0.046;-2348.8
2Q(KA)
0.052;-2348.8
33(3A)
0.034;-2551.2
(36)(3A)
0.057;-2427.5
3(39A)
0.044;-2573.8
3J(3A)
0.038;-2491.2
(345A)
0.016;-2967.5
(349A)
0.026;-2802.5
(34KA)
0.029;-2637.5
46(3A)
0.017;-2926.2
(49)(3A)
0.035;-2532.5
4(3QA)
0.033;-2678.8
6(35A)
0.022;-2885.0
T(35A)
0.033;-2720.0
5(36A)
0.026;-2885.0
58(3A)
0.024;-2802.5
(5J)(3A)
0.038;-2408.8
6(36A)
0.037;-2573.8
T(36A)
0.024;-2678.8
6(37A)
0.020;-2802.5
69(3A)
0.034;-2720.0
(6Q)(3A)
0.054;-2326.3
(379A)
0.029;-2678.8
(37KA)
0.034;-2513.8
79(3A)
0.029;-2678.8
(7Q)(3A)
0.042;-2285.0
(38TA)
0.033;-2596.2
88(3A)
0.046;-2408.8
(8J)(3A)
0.055;-2285.0
9(39A)
0.060;-2326.2
K(39A)
0.046;-2431.2
9(3QA)
0.031;-2472.5
J(3TA)
0.048;-2472.5
TJ(3A)
0.047;-2472.5
(3JQA)
0.043;-2390.0
J(3KA)
0.041;-2348.8
(QK)(3A)
0.075;-2037.5
33(5A)
0.023;-2738.8
337A
0.019;-2926.2
3A(3T)
0.042;-2532.5
33(KA)
0.057;-2408.8
3(46A)
0.016;-2926.2
38(4A)
0.022;-2843.8
(3J)(4A)
0.042;-2450.0
4A(34)
0.034;-2738.8
A(347)
0.021;-2885.0
(34)(TA)
0.033;-2491.2
QA(34)
0.031;-2678.8
345A
0.007;-3237.5
347A
0.010;-3155.0
349A
0.013;-3072.5
34JA
0.015;-2990.0
34KA
0.021;-2907.5
37(5A)
0.026;-2843.8
(3T)(5A)
0.035;-2450.0
3(5KA)
0.042;-2596.2
A(357)
0.023;-2843.8
(35)(TA)
0.030;-2450.0
QA(35)
0.040;-2637.5
356A
0.008;-3155.0
358A
0.014;-3072.5
35TA
0.015;-2990.0
35QA
0.022;-2907.5
(37)(6A)
0.044;-2532.5
3(6TA)
0.030;-2678.8
3Q(6A)
0.029;-2596.2
(36)(8A)
0.042;-2491.2
TA(36)
0.033;-2678.8
A(36K)
0.036;-2555.0
6A(38)
0.024;-2761.2
6A(3T)
0.027;-2678.8
6A(3Q)
0.032;-2596.2
37(7A)
0.040;-2491.2
(3T)(7A)
0.043;-2367.5
3(7KA)
0.048;-2513.8
A(379)
0.030;-2678.8
(37)(QA)
0.062;-2285.0
7A(38)
0.023;-2720.0
7A(3T)
0.035;-2637.5
7A(3Q)
0.047;-2555.0
38(8A)
0.056;-2408.8
(3J)(8A)
0.064;-2285.0
8A(38)
0.046;-2408.8
A(38J)
0.027;-2555.0
388A
0.032;-2678.8
38TA
0.022;-2866.2
38QA
0.020;-2783.8
(3T)(9A)
0.057;-2285.0
3(9KA)
0.043;-2431.2
A(39J)
0.046;-2513.8
399A
0.032;-2596.2
39JA
0.023;-2783.8
39KA
0.030;-2701.2
3Q(TA)
0.038;-2431.2
(3T)(QA)
0.070;-2161.2
TA(3J)
0.048;-2472.5
TA(3K)
0.040;-2390.0
3(JKA)
0.069;-2348.8
A(3JK)
0.052;-2348.8
JA(3K)
0.054;-2348.8
QA(3Q)
0.096;-2078.8
3QKA
0.031;-2577.5
45(4A)
0.026;-2656.2
(48)(4A)
0.056;-2262.5
4(4JA)
0.052;-2408.8
4K(4A)
0.043;-2326.2
(459A)
0.029;-2720.0
(45KA)
0.046;-2555.0
57(4A)
0.024;-2802.5
(5T)(4A)
0.049;-2408.8
5(4KA)
0.047;-2555.0
(469A)
0.032;-2678.8
(46KA)
0.031;-2513.8
68(4A)
0.039;-2720.0
(6J)(4A)
0.047;-2326.3
7(47A)
0.039;-2450.0
J(47A)
0.029;-2555.0
78(4A)
0.036;-2678.8
(7J)(4A)
0.044;-2285.0
8(48A)
0.054;-2367.5
Q(48A)
0.031;-2472.5
(8T)(4A)
0.050;-2285.0
8(4KA)
0.048;-2431.2
(49QA)
0.047;-2431.2
9(4JA)
0.035;-2472.5
9K(4A)
0.046;-2390.0
TT(4A)
0.053;-2202.5
(TK)(4A)
0.055;-2078.8
J(4QA)
0.055;-2348.8
K(4QA)
0.048;-2266.2
44(5A)
0.037;-2656.2
447A
0.020;-2843.8
4A(4T)
0.044;-2450.0
44(KA)
0.056;-2326.2
4(57A)
0.027;-2802.5
49(5A)
0.034;-2720.0
(4Q)(5A)
0.050;-2326.3
6A(45)
0.017;-2843.8
A(459)
0.031;-2720.0
(45)(QA)
0.055;-2326.3
5A(46)
0.021;-2843.8
5A(48)
0.025;-2761.2
5A(4T)
0.034;-2678.8
5A(4Q)
0.042;-2596.2
46(6A)
0.043;-2532.5
(49)(6A)
0.052;-2408.8
4(6QA)
0.043;-2555.0
A(467)
0.032;-2761.2
(46)(TA)
0.052;-2367.5
QA(46)
0.032;-2555.0
467A
0.014;-3031.2
469A
0.016;-2948.8
46JA
0.018;-2866.2
46KA
0.024;-2783.8
49(7A)
0.029;-2637.5
(4Q)(7A)
0.049;-2243.8
8A(47)
0.035;-2678.8
A(47J)
0.035;-2555.0
477A
0.036;-2720.0
479A
0.016;-2907.5
47JA
0.029;-2825.0
47KA
0.026;-2742.5
4T(8A)
0.034;-2555.0
(4K)(8A)
0.065;-2161.2
TA(48)
0.032;-2555.0
A(48K)
0.043;-2431.2
8A(4T)
0.040;-2555.0
8A(4Q)
0.032;-2472.5
49(9A)
0.048;-2285.0
(4Q)(9A)
0.054;-2161.2
TA(49)
0.039;-2513.8
A(49K)
0.042;-2390.0
9A(4J)
0.040;-2472.5
9A(4K)
0.054;-2390.0
4(TQA)
0.062;-2390.0
A(4TJ)
0.043;-2431.2
4TTA
0.051;-2472.5
4TQA
0.028;-2660.0
(4Q)(JA)
0.085;-2078.8
QA(4J)
0.052;-2348.8
4JQA
0.034;-2618.8
(4K)(QA)
0.101;-1996.3
QA(4K)
0.047;-2266.2
5(56A)
0.038;-2532.5
58(5A)
0.047;-2450.0
(5J)(5A)
0.069;-2056.2
6(56A)
0.040;-2491.2
T(56A)
0.030;-2596.2
6(57A)
0.028;-2720.0
69(5A)
0.034;-2637.5
(6Q)(5A)
0.054;-2243.8
(579A)
0.041;-2596.2
(57KA)
0.049;-2431.2
79(5A)
0.025;-2596.2
(7Q)(5A)
0.074;-2202.5
(58TA)
0.032;-2513.8
88(5A)
0.046;-2326.2
(8J)(5A)
0.060;-2202.5
9(59A)
0.048;-2243.8
K(59A)
0.064;-2348.8
9(5QA)
0.040;-2390.0
J(5TA)
0.038;-2390.0
TJ(5A)
0.039;-2390.0
(5JQA)
0.055;-2307.5
J(5KA)
0.053;-2266.2
(QK)(5A)
0.081;-1955.0
55(7A)
0.047;-2491.2
559A
0.033;-2678.8
5A(5Q)
0.053;-2285.0
(57)(6A)
0.052;-2450.0
5(6TA)
0.030;-2596.2
5Q(6A)
0.038;-2513.8
(56)(8A)
0.058;-2408.8
TA(56)
0.034;-2596.2
A(56K)
0.041;-2472.5
6A(58)
0.022;-2678.8
6A(5T)
0.038;-2596.2
6A(5Q)
0.033;-2513.8
57(7A)
0.050;-2408.8
(5T)(7A)
0.058;-2285.0
5(7KA)
0.043;-2431.2
A(579)
0.030;-2596.2
(57)(QA)
0.053;-2202.5
7A(58)
0.034;-2637.5
7A(5T)
0.037;-2555.0
7A(5Q)
0.036;-2472.5
58(8A)
0.040;-2326.2
(5J)(8A)
0.047;-2202.5
8A(58)
0.050;-2326.2
A(58J)
0.037;-2472.5
588A
0.037;-2596.2
58TA
0.019;-2783.8
58QA
0.023;-2701.2
(5T)(9A)
0.059;-2202.5
5(9KA)
0.063;-2348.8
A(59J)
0.035;-2431.2
599A
0.030;-2513.8
59JA
0.037;-2701.2
59KA
0.035;-2618.8
5Q(TA)
0.050;-2348.8
(5T)(QA)
0.058;-2078.8
TA(5J)
0.051;-2390.0
TA(5K)
0.060;-2307.5
5(JKA)
0.059;-2266.2
A(5JK)
0.040;-2266.2
JA(5K)
0.050;-2266.2
QA(5Q)
0.085;-1996.3
5QKA
0.042;-2495.0
67(6A)
0.042;-2408.8
(6T)(6A)
0.061;-2015.0
6(6KA)
0.047;-2161.2
(67TA)
0.038;-2513.8
77(6A)
0.049;-2367.5
(7T)(6A)
0.045;-2243.8
7(6KA)
0.046;-2390.0
(68JA)
0.045;-2431.2
(89)(6A)
0.050;-2243.8
8(6QA)
0.050;-2390.0
T(69A)
0.034;-2431.2
9(6TA)
0.046;-2431.2
9Q(6A)
0.047;-2348.8
Q(6TA)
0.048;-2307.5
(TQ)(6A)
0.062;-2037.5
(6JKA)
0.066;-2225.0
JK(6A)
0.061;-2225.0
K(6KA)
0.105;-1872.5
668A
0.030;-2637.5
6A(6J)
0.064;-2243.8
(67)(7A)
0.066;-2097.5
6(7TA)
0.034;-2513.8
6Q(7A)
0.051;-2431.2
(67)(9A)
0.044;-2285.0
JA(67)
0.057;-2472.5
67(8A)
0.030;-2596.2
67(TA)
0.039;-2513.8
67(QA)
0.047;-2431.2
(68)(8A)
0.097;-2015.0
6(8JA)
0.041;-2431.2
6K(8A)
0.054;-2348.8
(68)(JA)
0.059;-2161.2
KA(68)
0.040;-2348.8
6A(8T)
0.042;-2472.5
6A(8Q)
0.043;-2390.0
6(9TA)
0.043;-2431.2
6Q(9A)
0.049;-2348.8
(69)(JA)
0.060;-2120.0
KA(69)
0.036;-2307.5
6A(9J)
0.057;-2390.0
6A(9K)
0.060;-2307.5
(6Q)(TA)
0.092;-2037.5
JA(6T)
0.046;-2348.8
6T(JA)
0.049;-2348.8
6T(KA)
0.063;-2266.2
6Q(JA)
0.065;-2266.2
(6J)(KA)
0.067;-1955.0
6J(KA)
0.061;-2225.0
6K(QA)
0.068;-2183.8
6A(QK)
0.068;-2183.8
(78)(7A)
0.082;-2015.0
7(7JA)
0.066;-2161.2
7K(7A)
0.080;-2078.8
(78QA)
0.056;-2348.8
8(7TA)
0.041;-2431.2
8Q(7A)
0.044;-2348.8
J(79A)
0.058;-2348.8
9T(7A)
0.044;-2390.0
(9K)(7A)
0.068;-1996.3
K(7TA)
0.051;-2225.0
T(7KA)
0.050;-2225.0
JJ(7A)
0.089;-1996.3
(7QKA)
0.062;-2142.5
777A
0.059;-2326.3
7A(7T)
0.059;-2202.5
77(KA)
0.070;-2078.8
7(8TA)
0.050;-2431.2
7Q(8A)
0.063;-2348.8
(78)(TA)
0.065;-2161.2
QA(78)
0.049;-2348.8
789A
0.033;-2742.5
78JA
0.031;-2660.0
78KA
0.034;-2577.5
7J(9A)
0.059;-2348.8
(79)(TA)
0.068;-2120.0
QA(79)
0.058;-2307.5
79TA
0.026;-2660.0
79QA
0.037;-2577.5
(7J)(TA)
0.081;-2037.5
TA(7T)
0.055;-2078.8
A(7TK)
0.048;-2225.0
TA(7Q)
0.064;-2266.2
7J(JA)
0.088;-1996.3
(7J)(QA)
0.084;-1955.0
JA(7Q)
0.064;-2225.0
7Q(QA)
0.092;-1913.8
7QQA
0.052;-2183.8
7KKA
0.082;-2101.3
8(8JA)
0.068;-2078.8
8K(8A)
0.072;-1996.3
(89KA)
0.059;-2225.0
9J(8A)
0.054;-2307.5
(8TJA)
0.060;-2266.2
(TJ)(8A)
0.089;-1996.3
J(8JA)
0.079;-1955.0
JQ(8A)
0.051;-2183.8
Q(8KA)
0.067;-2101.3
889A
0.053;-2431.2
8A(8Q)
0.060;-2037.5
(8T)(9A)
0.062;-2078.8
8(9KA)
0.068;-2225.0
A(89J)
0.056;-2307.5
899A
0.046;-2390.0
89JA
0.027;-2577.5
89KA
0.042;-2495.0
8Q(TA)
0.051;-2225.0
(8T)(QA)
0.089;-1955.0
TA(8J)
0.048;-2266.2
TA(8K)
0.053;-2183.8
8(JKA)
0.067;-2142.5
A(8JK)
0.068;-2142.5
JA(8K)
0.088;-2142.5
QA(8Q)
0.089;-1872.5
8QKA
0.056;-2371.2
9T(9A)
0.072;-2037.5
(9K)(9A)
0.100;-1643.7
K(9TA)
0.061;-2142.5
T(9KA)
0.048;-2142.5
JJ(9A)
0.091;-1913.8
(9QKA)
0.080;-2060.0
999A
0.056;-2078.8
9A(9Q)
0.066;-1955.0
(9J)(TA)
0.085;-1955.0
TA(9T)
0.066;-1996.3
A(9TK)
0.067;-2142.5
TA(9Q)
0.063;-2183.8
9J(JA)
0.095;-1913.8
(9J)(QA)
0.079;-1872.5
JA(9Q)
0.055;-2142.5
9Q(QA)
0.079;-1831.3
9QQA
0.075;-2101.3
9KKA
0.084;-2018.8
T(TKA)
0.082;-1831.3
JJ(TA)
0.088;-1872.5
(TQKA)
0.066;-2018.8
TTTA
0.090;-1955.0
TA(TK)
0.073;-1831.3
(TK)(JA)
0.133;-1790.0
KA(TJ)
0.071;-2060.0
TA(JK)
0.069;-2060.0
(TQ)(KA)
0.093;-1748.8
(TK)(KA)
0.130;-1437.5
J(JKA)
0.086;-1748.8
(QK)(JA)
0.124;-1707.5
JJ(KA)
0.102;-1748.8
QA(JQ)
0.108;-1748.8
JQKA
0.056;-2247.5
QK(QA)
0.111;-1666.3
QK(KA)
0.087;-1625.0
22(24)
0.013;-3087.5
22(28)
0.018;-2922.5
22(2Q)
0.031;-2757.5
24(23)
0.008;-3316.2
(23)(27)
0.017;-2922.5
2(23T)
0.012;-3068.8
2Q(23)
0.018;-2986.2
23(25)
0.007;-3275.0
2237
0.004;-3462.5
22(3T)
0.013;-3068.8
23(2K)
0.022;-2945.0
2(246)
0.008;-3192.5
28(24)
0.010;-3110.0
(24)(2J)
0.030;-2716.2
2244
0.010;-3275.0
22(47)
0.008;-3151.2
24(2T)
0.012;-3027.5
224Q
0.011;-3215.0
26(25)
0.011;-3151.2
(25)(29)
0.024;-2757.5
2(25Q)
0.018;-2903.8
22(56)
0.010;-3151.2
25(29)
0.016;-3027.5
225J
0.008;-3215.0
26(26)
0.018;-2840.0
(26)(29)
0.022;-2716.2
2(26Q)
0.017;-2862.5
22(67)
0.016;-3068.8
26(2T)
0.018;-2945.0
226Q
0.013;-3132.5
28(27)
0.015;-2986.2
(27)(2J)
0.037;-2592.5
2277
0.013;-3027.5
22(7T)
0.023;-2903.8
27(2K)
0.027;-2780.0
2(28T)
0.017;-2862.5
2Q(28)
0.024;-2780.0
28(2T)
0.020;-2862.5
228Q
0.013;-3050.0
2T(29)
0.021;-2821.2
(29)(2K)
0.044;-2427.5
229J
0.020;-3050.0
2T(2T)
0.052;-2510.0
(2T)(2K)
0.042;-2386.2
22TQ
0.015;-2967.5
2Q(2J)
0.034;-2656.2
2J(2K)
0.037;-2615.0
22QQ
0.029;-2615.0
3(234)
0.010;-3275.0
36(23)
0.013;-3192.5
(23)(39)
0.021;-2798.8
3(23Q)
0.017;-2945.0
5(234)
0.004;-3462.5
9(234)
0.007;-3297.5
K(234)
0.012;-3132.5
4(237)
0.005;-3380.0
49(23)
0.007;-3297.5
(23)(4Q)
0.021;-2903.8
(2357)
0.005;-3338.8
(235J)
0.010;-3173.8
(23)(56)
0.014;-3110.0
5(239)
0.010;-3256.2
5J(23)
0.009;-3173.8
(2367)
0.008;-3297.5
(236J)
0.010;-3132.5
(23)(67)
0.013;-3027.5
6(23T)
0.009;-3173.8
6Q(23)
0.012;-3091.2
9(237)
0.010;-3173.8
K(237)
0.022;-3008.8
7(23T)
0.009;-3132.5
7Q(23)
0.013;-3050.0
T(238)
0.013;-3091.2
8(239)
0.012;-3132.5
8J(23)
0.011;-3050.0
(239T)
0.014;-3050.0
99(23)
0.021;-2821.2
(23)(9Q)
0.023;-2697.5
(23TQ)
0.016;-2926.2
T(23Q)
0.016;-2926.2
Q(23J)
0.026;-2885.0
(23)(JK)
0.040;-2573.8
QK(23)
0.020;-2802.5
23(35)
0.009;-3233.8
33(28)
0.013;-3110.0
233T
0.007;-3297.5
23(3K)
0.021;-2903.8
(24)(36)
0.012;-3151.2
3(249)
0.009;-3297.5
3J(24)
0.011;-3215.0
(34)(25)
0.012;-3192.5
27(34)
0.006;-3380.0
2(34T)
0.010;-3256.2
(34)(2K)
0.023;-2862.5
34(26)
0.005;-3421.2
34(28)
0.006;-3338.8
34(2T)
0.009;-3256.2
34(2Q)
0.014;-3173.8
(25)(35)
0.025;-2881.3
3(258)
0.008;-3297.5
3T(25)
0.007;-3215.0
(25)(3K)
0.018;-2821.2
27(35)
0.007;-3338.8
2(35T)
0.012;-3215.0
(35)(2K)
0.024;-2821.2
35(27)
0.007;-3338.8
35(29)
0.009;-3256.2
35(2J)
0.009;-3173.8
35(2K)
0.016;-3091.2
37(26)
0.008;-3297.5
(26)(3T)
0.017;-2903.8
3(26K)
0.014;-3050.0
2(368)
0.011;-3256.2
(36)(2J)
0.023;-2862.5
2K(36)
0.014;-3050.0
23(68)
0.008;-3256.2
23(6T)
0.011;-3173.8
23(6Q)
0.014;-3091.2
3(278)
0.010;-3215.0
3T(27)
0.012;-3132.5
(27)(3K)
0.034;-2738.8
29(37)
0.012;-3173.8
2(37Q)
0.013;-3050.0
23(78)
0.011;-3215.0
23(7T)
0.010;-3132.5
23(7Q)
0.014;-3050.0
3(289)
0.012;-3132.5
3J(28)
0.016;-3050.0
(38)(29)
0.023;-2862.5
2J(38)
0.014;-3050.0
38(29)
0.013;-3132.5
38(2J)
0.016;-3050.0
38(2K)
0.017;-2967.5
3T(29)
0.018;-3050.0
(29)(3K)
0.028;-2656.3
2J(39)
0.012;-3008.8
39(2T)
0.014;-3050.0
39(2Q)
0.013;-2967.5
(2T)(3T)
0.048;-2468.8
3(2TK)
0.023;-2885.0
2(3TQ)
0.025;-2926.2
23(TJ)
0.019;-2967.5
23(TK)
0.015;-2885.0
(2J)(3K)
0.037;-2573.8
2K(3J)
0.016;-2843.8
23(JK)
0.028;-2843.8
(3Q)(2K)
0.049;-2532.5
(2K)(3K)
0.078;-2221.3
4(246)
0.015;-3110.0
48(24)
0.016;-3027.5
(24)(4J)
0.031;-2633.8
5(245)
0.012;-3110.0
9(245)
0.010;-3215.0
K(245)
0.016;-3050.0
5(248)
0.009;-3256.2
5T(24)
0.010;-3173.8
(24)(5K)
0.021;-2780.0
9(246)
0.012;-3173.8
K(246)
0.014;-3008.8
6(249)
0.011;-3173.8
6J(24)
0.013;-3091.2
(2478)
0.010;-3173.8
(247Q)
0.012;-3008.8
7(249)
0.011;-3132.5
7J(24)
0.015;-3050.0
(2489)
0.018;-3091.2
(248K)
0.024;-2926.2
8T(24)
0.013;-3050.0
(24)(8K)
0.029;-2656.3
Q(249)
0.018;-2926.2
(24)(9J)
0.031;-2697.5
T(24T)
0.033;-2697.5
T(24J)
0.015;-2926.2
TK(24)
0.026;-2843.8
(24)(JQ)
0.034;-2573.8
QQ(24)
0.035;-2532.5
24(45)
0.010;-3151.2
44(28)
0.012;-3027.5
244T
0.010;-3215.0
24(4K)
0.025;-2821.2
(25)(47)
0.016;-3027.5
4(25T)
0.010;-3173.8
4Q(25)
0.015;-3091.2
(45)(27)
0.016;-3027.5
29(45)
0.010;-3215.0
2(45Q)
0.011;-3091.2
24(56)
0.007;-3338.8
24(58)
0.009;-3256.2
24(5T)
0.010;-3173.8
24(5Q)
0.011;-3091.2
4(267)
0.006;-3256.2
49(26)
0.013;-3173.8
(26)(4Q)
0.030;-2780.0
27(46)
0.008;-3256.2
2(46T)
0.012;-3132.5
(46)(2K)
0.038;-2738.8
46(28)
0.007;-3215.0
46(2T)
0.010;-3132.5
46(2Q)
0.013;-3050.0
(27)(47)
0.031;-2675.0
4(27T)
0.011;-3091.2
4Q(27)
0.021;-3008.8
(47)(29)
0.020;-2862.5
2J(47)
0.012;-3050.0
47(28)
0.013;-3173.8
47(2T)
0.013;-3091.2
47(2Q)
0.014;-3008.8
(28)(48)
0.030;-2592.5
4(28J)
0.019;-3008.8
4K(28)
0.016;-2926.2
(48)(2J)
0.027;-2738.8
2K(48)
0.021;-2926.2
24(8T)
0.014;-3050.0
24(8Q)
0.021;-2967.5
4(29T)
0.012;-3008.8
4Q(29)
0.019;-2926.2
(49)(2J)
0.032;-2697.5
2K(49)
0.020;-2885.0
24(9J)
0.020;-2967.5
24(9K)
0.021;-2885.0
(2T)(4Q)
0.036;-2615.0
2J(4T)
0.016;-2926.2
4T(2J)
0.019;-2926.2
4T(2K)
0.023;-2843.8
4Q(2J)
0.025;-2843.8
(4J)(2K)
0.049;-2532.5
4J(2K)
0.019;-2802.5
4K(2Q)
0.030;-2761.2
24(QK)
0.023;-2761.2
(25)(56)
0.029;-2757.5
5(259)
0.019;-2903.8
5J(25)
0.025;-2821.2
(2567)
0.008;-3215.0
(256J)
0.014;-3050.0
(25)(67)
0.014;-2945.0
6(25T)
0.010;-3091.2
6Q(25)
0.014;-3008.8
9(257)
0.015;-3091.2
K(257)
0.018;-2926.2
7(25T)
0.017;-3050.0
7Q(25)
0.015;-2967.5
T(258)
0.013;-3008.8
8(259)
0.013;-3050.0
8J(25)
0.016;-2967.5
(259T)
0.013;-2967.5
99(25)
0.019;-2738.8
(25)(9Q)
0.035;-2615.0
(25TQ)
0.016;-2843.8
T(25Q)
0.024;-2843.8
Q(25J)
0.024;-2802.5
(25)(JK)
0.041;-2491.2
QK(25)
0.029;-2720.0
25(57)
0.014;-2986.2
55(2T)
0.028;-2862.5
255Q
0.014;-3050.0
57(26)
0.008;-3215.0
(26)(5T)
0.018;-2821.2
5(26K)
0.015;-2967.5
2(568)
0.009;-3173.8
(56)(2J)
0.028;-2780.0
2K(56)
0.015;-2967.5
25(68)
0.012;-3173.8
25(6T)
0.012;-3091.2
25(6Q)
0.014;-3008.8
5(278)
0.009;-3132.5
5T(27)
0.015;-3050.0
(27)(5K)
0.033;-2656.3
29(57)
0.011;-3091.2
2(57Q)
0.017;-2967.5
25(78)
0.010;-3132.5
25(7T)
0.013;-3050.0
25(7Q)
0.018;-2967.5
5(289)
0.016;-3050.0
5J(28)
0.017;-2967.5
(58)(29)
0.033;-2780.0
2J(58)
0.019;-2967.5
58(29)
0.020;-3050.0
58(2J)
0.021;-2967.5
58(2K)
0.017;-2885.0
5T(29)
0.018;-2967.5
(29)(5K)
0.037;-2573.8
2J(59)
0.019;-2926.2
59(2T)
0.016;-2967.5
59(2Q)
0.022;-2885.0
(2T)(5T)
0.051;-2386.2
5(2TK)
0.026;-2802.5
2(5TQ)
0.022;-2843.8
25(TJ)
0.020;-2885.0
25(TK)
0.029;-2802.5
(2J)(5K)
0.029;-2491.2
2K(5J)
0.019;-2761.2
25(JK)
0.027;-2761.2
(5Q)(2K)
0.050;-2450.0
(2K)(5K)
0.057;-2138.8
6(268)
0.024;-2862.5
6T(26)
0.024;-2780.0
(26)(6K)
0.044;-2386.2
T(267)
0.017;-3008.8
7(268)
0.015;-3091.2
7T(26)
0.017;-3008.8
(26)(7K)
0.031;-2615.0
J(268)
0.020;-2926.2
89(26)
0.018;-3008.8
(26)(8Q)
0.026;-2615.0
(269J)
0.018;-2885.0
(26)(9T)
0.032;-2656.3
9(26K)
0.031;-2802.5
(26TK)
0.027;-2761.2
TQ(26)
0.031;-2802.5
K(26J)
0.028;-2720.0
Q(26Q)
0.050;-2450.0
KK(26)
0.057;-2367.5
66(29)
0.019;-2821.2
266J
0.013;-3008.8
67(27)
0.023;-2862.5
(27)(6T)
0.026;-2738.8
6(27K)
0.019;-2885.0
2(679)
0.014;-3050.0
(67)(2Q)
0.028;-2656.3
27(68)
0.014;-3091.2
27(6T)
0.019;-3008.8
27(6Q)
0.019;-2926.2
68(28)
0.028;-2780.0
(28)(6J)
0.027;-2656.3
28(68)
0.022;-2780.0
2(68J)
0.013;-2926.2
2688
0.011;-3050.0
268T
0.009;-3237.5
268Q
0.012;-3155.0
(29)(6T)
0.023;-2656.3
6(29K)
0.024;-2802.5
2(69J)
0.019;-2885.0
2699
0.016;-2967.5
269J
0.010;-3155.0
269K
0.012;-3072.5
6Q(2T)
0.020;-2802.5
(6T)(2Q)
0.041;-2532.5
2T(6J)
0.024;-2843.8
2T(6K)
0.029;-2761.2
6(2JK)
0.030;-2720.0
2(6JK)
0.029;-2720.0
2J(6K)
0.025;-2720.0
2Q(6Q)
0.038;-2450.0
26QK
0.021;-2948.8
78(27)
0.024;-2780.0
(27)(7J)
0.056;-2386.2
8(278)
0.026;-2738.8
Q(278)
0.022;-2843.8
(27)(8T)
0.040;-2656.3
8(27K)
0.023;-2802.5
(279Q)
0.025;-2802.5
9(27J)
0.020;-2843.8
9K(27)
0.023;-2761.2
TT(27)
0.042;-2573.8
(27)(TK)
0.047;-2450.0
J(27Q)
0.028;-2720.0
K(27Q)
0.033;-2637.5
77(28)
0.021;-2780.0
277T
0.018;-2967.5
27(7K)
0.039;-2573.8
(28)(7T)
0.032;-2656.3
7(28K)
0.028;-2802.5
2(78T)
0.016;-2926.2
(78)(2K)
0.041;-2532.5
78(2T)
0.017;-2926.2
78(2Q)
0.022;-2843.8
(29)(79)
0.063;-2386.2
7(29Q)
0.024;-2802.5
2(79T)
0.024;-2885.0
(79)(2K)
0.038;-2491.2
79(2J)
0.021;-2843.8
79(2K)
0.029;-2761.2
7J(2T)
0.023;-2802.5
(7T)(2J)
0.048;-2532.5
2K(7T)
0.022;-2720.0
27(TQ)
0.023;-2761.2
7(2JQ)
0.029;-2720.0
2(7JQ)
0.029;-2720.0
27(JQ)
0.029;-2720.0
7(2QK)
0.027;-2637.5
7Q(2K)
0.037;-2637.5
88(28)
0.050;-2427.5
(28)(8J)
0.047;-2303.8
9(289)
0.034;-2615.0
K(289)
0.026;-2720.0
9(28Q)
0.024;-2761.2
J(28T)
0.023;-2761.2
TJ(28)
0.022;-2761.2
(28JQ)
0.036;-2678.8
J(28K)
0.037;-2637.5
(28)(QK)
0.051;-2326.3
88(2T)
0.039;-2615.0
288Q
0.029;-2802.5
8T(29)
0.016;-2843.8
(29)(8K)
0.038;-2450.0
2J(89)
0.026;-2802.5
89(2T)
0.023;-2843.8
89(2Q)
0.021;-2761.2
(2T)(8T)
0.053;-2262.5
8(2TK)
0.026;-2678.8
2(8TQ)
0.024;-2720.0
28(TJ)
0.022;-2761.2
28(TK)
0.024;-2678.8
(2J)(8K)
0.049;-2367.5
2K(8J)
0.039;-2637.5
28(JK)
0.030;-2637.5
(8Q)(2K)
0.054;-2326.3
(2K)(8K)
0.061;-2015.0
9(29J)
0.050;-2491.2
9K(29)
0.037;-2408.8
TT(29)
0.049;-2491.2
(29)(TK)
0.038;-2367.5
J(29Q)
0.027;-2637.5
K(29Q)
0.030;-2555.0
99(2T)
0.032;-2532.5
299Q
0.027;-2720.0
9J(2T)
0.025;-2720.0
(9T)(2J)
0.048;-2450.0
2K(9T)
0.025;-2637.5
29(TQ)
0.036;-2678.8
9(2JQ)
0.038;-2637.5
2(9JQ)
0.031;-2637.5
29(JQ)
0.028;-2637.5
9(2QK)
0.038;-2555.0
9Q(2K)
0.032;-2555.0
TT(2T)
0.058;-2180.0
(2T)(TK)
0.088;-2056.2
J(2TQ)
0.033;-2596.2
K(2TQ)
0.028;-2513.8
TT(2J)
0.040;-2408.8
2TTK
0.034;-2596.2
TK(2J)
0.047;-2555.0
2TJJ
0.028;-2637.5
2TJK
0.022;-2825.0
2(TQK)
0.048;-2513.8
TK(2K)
0.055;-2202.5
(2J)(JK)
0.071;-1973.8
QK(2J)
0.051;-2472.5
2J(JK)
0.077;-2243.8
(JQ)(2K)
0.048;-2202.5
(2K)(JK)
0.083;-1891.2
K(2QK)
0.051;-2120.0
2K(QK)
0.061;-2120.0
3335
0.009;-3192.5
3339
0.020;-3027.5
333K
0.021;-2862.5
36(34)
0.015;-3110.0
(34)(39)
0.024;-2716.2
3(34Q)
0.020;-2862.5
33(45)
0.011;-3151.2
34(38)
0.015;-3027.5
334T
0.007;-3215.0
33(4K)
0.019;-2821.2
(35)(37)
0.027;-2757.5
3(35T)
0.017;-2903.8
3Q(35)
0.025;-2821.2
35(37)
0.012;-3027.5
3359
0.010;-3215.0
33(5Q)
0.022;-2821.2
(36)(37)
0.026;-2716.2
3(36T)
0.019;-2862.5
3Q(36)
0.021;-2780.0
36(38)
0.025;-2945.0
336T
0.010;-3132.5
33(6K)
0.036;-2738.8
(37)(39)
0.030;-2592.5
3(37Q)
0.028;-2738.8
33(78)
0.017;-2903.8
37(3J)
0.019;-2780.0
337K
0.020;-2967.5
3T(38)
0.030;-2780.0
(38)(3K)
0.047;-2386.2
338T
0.015;-3050.0
33(8K)
0.032;-2656.2
(39)(3J)
0.044;-2427.5
3399
0.022;-2780.0
33(9Q)
0.029;-2656.2
(3T)(3J)
0.045;-2386.2
33TT
0.028;-2697.5
33(TK)
0.039;-2573.8
(3J)(3K)
0.072;-2262.5
33JK
0.027;-2802.5
33(QK)
0.039;-2491.2
45(34)
0.011;-3110.0
(34)(48)
0.034;-2716.2
4(34J)
0.023;-2862.5
4K(34)
0.031;-2780.0
(3459)
0.009;-3173.8
(345K)
0.014;-3008.8
57(34)
0.009;-3256.2
(34)(5T)
0.018;-2862.5
5(34K)
0.018;-3008.8
(3469)
0.012;-3132.5
(346K)
0.020;-2967.5
68(34)
0.011;-3173.8
(34)(6J)
0.020;-2780.0
7(347)
0.017;-2903.8
J(347)
0.019;-3008.8
78(34)
0.009;-3132.5
(34)(7J)
0.031;-2738.8
8(348)
0.018;-2821.2
Q(348)
0.019;-2926.2
(34)(8T)
0.030;-2738.8
8(34K)
0.020;-2885.0
(349Q)
0.025;-2885.0
9(34J)
0.024;-2926.2
9K(34)
0.022;-2843.8
TT(34)
0.028;-2656.2
(34)(TK)
0.034;-2532.5
J(34Q)
0.024;-2802.5
K(34Q)
0.027;-2720.0
44(35)
0.012;-3110.0
3447
0.007;-3297.5
34(4T)
0.019;-2903.8
44(3K)
0.028;-2780.0
4(357)
0.008;-3256.2
49(35)
0.008;-3173.8
(35)(4Q)
0.020;-2780.0
36(45)
0.006;-3297.5
3(459)
0.010;-3173.8
(45)(3Q)
0.023;-2780.0
35(46)
0.008;-3297.5
35(48)
0.009;-3215.0
35(4T)
0.012;-3132.5
35(4Q)
0.010;-3050.0
46(36)
0.015;-2986.2
(36)(49)
0.019;-2862.5
4(36Q)
0.014;-3008.8
3(467)
0.011;-3215.0
(46)(3T)
0.023;-2821.2
3Q(46)
0.015;-3008.8
3467
0.003;-3485.0
3469
0.005;-3402.5
346J
0.006;-3320.0
346K
0.007;-3237.5
49(37)
0.017;-3091.2
(37)(4Q)
0.023;-2697.5
38(47)
0.012;-3132.5
3(47J)
0.012;-3008.8
3477
0.011;-3173.8
3479
0.007;-3361.2
347J
0.008;-3278.8
347K
0.009;-3196.2
4T(38)
0.017;-3008.8
(38)(4K)
0.029;-2615.0
3T(48)
0.012;-3008.8
3(48K)
0.027;-2885.0
38(4T)
0.019;-3008.8
38(4Q)
0.018;-2926.2
49(39)
0.031;-2738.8
(39)(4Q)
0.028;-2615.0
3T(49)
0.014;-2967.5
3(49K)
0.021;-2843.8
39(4J)
0.022;-2926.2
39(4K)
0.024;-2843.8
4(3TQ)
0.019;-2843.8
3(4TJ)
0.022;-2885.0
34TT
0.019;-2926.2
34TQ
0.013;-3113.8
(3J)(4Q)
0.037;-2532.5
3Q(4J)
0.023;-2802.5
34JQ
0.012;-3072.5
(3Q)(4K)
0.031;-2450.0
3Q(4K)
0.024;-2720.0
5(356)
0.016;-2986.2
58(35)
0.019;-2903.8
(35)(5J)
0.047;-2510.0
6(356)
0.020;-2945.0
T(356)
0.011;-3050.0
6(357)
0.013;-3173.8
69(35)
0.013;-3091.2
(35)(6Q)
0.025;-2697.5
(3579)
0.015;-3050.0
(357K)
0.019;-2885.0
79(35)
0.013;-3050.0
(35)(7Q)
0.035;-2656.3
(358T)
0.013;-2967.5
88(35)
0.029;-2780.0
(35)(8J)
0.031;-2656.3
9(359)
0.021;-2697.5
K(359)
0.021;-2802.5
9(35Q)
0.022;-2843.8
J(35T)
0.018;-2843.8
TJ(35)
0.023;-2843.8
(35JQ)
0.026;-2761.2
J(35K)
0.037;-2720.0
(35)(QK)
0.054;-2408.8
55(37)
0.017;-2945.0
3559
0.012;-3132.5
35(5Q)
0.030;-2738.8
(36)(57)
0.025;-2903.8
5(36T)
0.012;-3050.0
5Q(36)
0.019;-2967.5
(56)(38)
0.017;-2862.5
3T(56)
0.017;-3050.0
3(56K)
0.020;-2926.2
36(58)
0.009;-3132.5
36(5T)
0.015;-3050.0
36(5Q)
0.015;-2967.5
57(37)
0.018;-2862.5
(37)(5T)
0.021;-2738.8
5(37K)
0.023;-2885.0
3(579)
0.011;-3050.0
(57)(3Q)
0.025;-2656.3
37(58)
0.010;-3091.2
37(5T)
0.016;-3008.8
37(5Q)
0.016;-2926.2
58(38)
0.026;-2780.0
(38)(5J)
0.033;-2656.3
38(58)
0.029;-2780.0
3(58J)
0.022;-2926.2
3588
0.014;-3050.0
358T
0.009;-3237.5
358Q
0.010;-3155.0
(39)(5T)
0.032;-2656.3
5(39K)
0.025;-2802.5
3(59J)
0.019;-2885.0
3599
0.017;-2967.5
359J
0.014;-3155.0
359K
0.015;-3072.5
5Q(3T)
0.027;-2802.5
(5T)(3Q)
0.045;-2532.5
3T(5J)
0.022;-2843.8
3T(5K)
0.028;-2761.2
5(3JK)
0.025;-2720.0
3(5JK)
0.023;-2720.0
3J(5K)
0.023;-2720.0
3Q(5Q)
0.047;-2450.0
35QK
0.014;-2948.8
67(36)
0.021;-2862.5
(36)(6T)
0.042;-2468.8
6(36K)
0.034;-2615.0
(367T)
0.021;-2967.5
77(36)
0.017;-2821.2
(36)(7T)
0.021;-2697.5
7(36K)
0.020;-2843.8
(368J)
0.020;-2885.0
(36)(89)
0.030;-2697.5
8(36Q)
0.020;-2843.8
T(369)
0.028;-2885.0
9(36T)
0.019;-2885.0
9Q(36)
0.020;-2802.5
Q(36T)
0.024;-2761.2
(36)(TQ)
0.045;-2491.2
(36JK)
0.029;-2678.8
JK(36)
0.034;-2678.8
K(36K)
0.051;-2326.2
3668
0.017;-3091.2
36(6J)
0.033;-2697.5
(37)(67)
0.043;-2551.3
6(37T)
0.018;-2967.5
6Q(37)
0.018;-2885.0
(67)(39)
0.030;-2738.8
3J(67)
0.023;-2926.2
67(38)
0.014;-3050.0
67(3T)
0.016;-2967.5
67(3Q)
0.019;-2885.0
(38)(68)
0.033;-2468.8
6(38J)
0.020;-2885.0
6K(38)
0.020;-2802.5
(68)(3J)
0.029;-2615.0
3K(68)
0.027;-2802.5
36(8T)
0.020;-2926.2
36(8Q)
0.018;-2843.8
6(39T)
0.021;-2885.0
6Q(39)
0.025;-2802.5
(69)(3J)
0.030;-2573.8
3K(69)
0.030;-2761.2
36(9J)
0.023;-2843.8
36(9K)
0.022;-2761.2
(3T)(6Q)
0.036;-2491.2
3J(6T)
0.018;-2802.5
6T(3J)
0.019;-2802.5
6T(3K)
0.027;-2720.0
6Q(3J)
0.035;-2720.0
(6J)(3K)
0.044;-2408.8
6J(3K)
0.030;-2678.8
6K(3Q)
0.036;-2637.5
36(QK)
0.033;-2637.5
(37)(78)
0.045;-2468.8
7(37J)
0.033;-2615.0
7K(37)
0.039;-2532.5
(378Q)
0.022;-2802.5
8(37T)
0.020;-2885.0
8Q(37)
0.027;-2802.5
J(379)
0.019;-2802.5
9T(37)
0.024;-2843.8
(37)(9K)
0.053;-2450.0
K(37T)
0.024;-2678.8
T(37K)
0.028;-2678.8
JJ(37)
0.041;-2450.0
(37QK)
0.038;-2596.2
3777
0.027;-2780.0
37(7T)
0.040;-2656.2
77(3K)
0.033;-2532.5
7(38T)
0.015;-2885.0
7Q(38)
0.021;-2802.5
(78)(3T)
0.034;-2615.0
3Q(78)
0.023;-2802.5
3789
0.011;-3196.2
378J
0.012;-3113.8
378K
0.018;-3031.2
7J(39)
0.024;-2802.5
(79)(3T)
0.034;-2573.8
3Q(79)
0.026;-2761.2
379T
0.013;-3113.8
379Q
0.018;-3031.2
(3T)(7J)
0.039;-2491.2
3T(7T)
0.030;-2532.5
3(7TK)
0.039;-2678.8
3T(7Q)
0.027;-2720.0
7J(3J)
0.044;-2450.0
(7J)(3Q)
0.041;-2408.8
3J(7Q)
0.031;-2678.8
7Q(3Q)
0.047;-2367.5
37QQ
0.030;-2637.5
37KK
0.037;-2555.0
8(38J)
0.031;-2532.5
8K(38)
0.052;-2450.0
(389K)
0.026;-2678.8
9J(38)
0.027;-2761.2
(38TJ)
0.026;-2720.0
(38)(TJ)
0.044;-2450.0
J(38J)
0.059;-2408.8
JQ(38)
0.038;-2637.5
Q(38K)
0.035;-2555.0
3889
0.018;-2885.0
38(8Q)
0.033;-2491.2
(39)(8T)
0.037;-2532.5
8(39K)
0.028;-2678.8
3(89J)
0.027;-2761.2
3899
0.021;-2843.8
389J
0.014;-3031.2
389K
0.017;-2948.8
8Q(3T)
0.034;-2678.8
(8T)(3Q)
0.037;-2408.8
3T(8J)
0.022;-2720.0
3T(8K)
0.034;-2637.5
8(3JK)
0.027;-2596.2
3(8JK)
0.036;-2596.2
3J(8K)
0.027;-2596.2
3Q(8Q)
0.047;-2326.2
38QK
0.030;-2825.0
9T(39)
0.043;-2491.2
(39)(9K)
0.063;-2097.5
K(39T)
0.034;-2596.2
T(39K)
0.034;-2596.2
JJ(39)
0.051;-2367.5
(39QK)
0.030;-2513.8
3999
0.038;-2532.5
39(9Q)
0.048;-2408.8
(3T)(9J)
0.043;-2408.8
3T(9T)
0.038;-2450.0
3(9TK)
0.034;-2596.2
3T(9Q)
0.032;-2637.5
9J(3J)
0.049;-2367.5
(9J)(3Q)
0.046;-2326.3
3J(9Q)
0.026;-2596.2
9Q(3Q)
0.054;-2285.0
39QQ
0.037;-2555.0
39KK
0.049;-2472.5
T(3TK)
0.053;-2285.0
JJ(3T)
0.054;-2326.2
(3TQK)
0.049;-2472.5
3TTT
0.054;-2408.8
3T(TK)
0.060;-2285.0
(3J)(TK)
0.059;-2243.8
3K(TJ)
0.043;-2513.8
3T(JK)
0.049;-2513.8
(TQ)(3K)
0.057;-2202.5
(3K)(TK)
0.079;-1891.2
J(3JK)
0.058;-2202.5
(3J)(QK)
0.051;-2161.2
JJ(3K)
0.063;-2202.5
3Q(JQ)
0.063;-2202.5
3JQK
0.027;-2701.2
QK(3Q)
0.081;-2120.0
QK(3K)
0.059;-2078.8
44(46)
0.029;-2757.5
44(4T)
0.034;-2592.5
(45)(45)
0.047;-2487.5
4(458)
0.019;-2903.8
4T(45)
0.021;-2821.2
(45)(4K)
0.053;-2427.5
4457
0.010;-3215.0
44(5T)
0.032;-2821.2
45(4K)
0.028;-2697.5
4(468)
0.027;-2862.5
4T(46)
0.019;-2780.0
(46)(4K)
0.054;-2386.2
4468
0.009;-3132.5
44(6J)
0.025;-2738.8
(47)(47)
0.045;-2322.5
4(47T)
0.027;-2738.8
4Q(47)
0.029;-2656.2
47(49)
0.025;-2780.0
447J
0.015;-2967.5
48(48)
0.031;-2510.0
(48)(4J)
0.052;-2386.2
4488
0.021;-2780.0
44(8J)
0.028;-2656.2
(49)(49)
0.086;-2157.5
4(49Q)
0.026;-2573.8
44(9T)
0.022;-2656.2
49(4K)
0.041;-2532.5
4(4TQ)
0.046;-2532.5
44(TJ)
0.038;-2573.8
(4J)(4J)
0.092;-1992.5
44JJ
0.030;-2532.5
4Q(4Q)
0.055;-2180.0
(4K)(4K)
0.076;-1827.5
(45)(57)
0.028;-2633.8
5(45T)
0.032;-2780.0
5Q(45)
0.024;-2697.5
8(456)
0.013;-3091.2
Q(456)
0.018;-2926.2
(45)(68)
0.024;-2821.2
6(45J)
0.016;-2967.5
6K(45)
0.023;-2885.0
(457J)
0.017;-2926.2
(45)(78)
0.029;-2780.0
7(45J)
0.017;-2926.2
7K(45)
0.019;-2843.8
(458Q)
0.023;-2843.8
8(45T)
0.021;-2926.2
8Q(45)
0.028;-2843.8
J(459)
0.017;-2843.8
9T(45)
0.019;-2885.0
(45)(9K)
0.041;-2491.2
K(45T)
0.029;-2720.0
T(45K)
0.036;-2720.0
JJ(45)
0.035;-2491.2
(45QK)
0.032;-2637.5
4555
0.020;-2986.2
45(58)
0.023;-2862.5
55(4J)
0.031;-2738.8
455K
0.021;-2926.2
58(46)
0.015;-3091.2
(46)(5J)
0.037;-2697.5
46(56)
0.024;-2903.8
4(569)
0.011;-3050.0
(56)(4Q)
0.024;-2656.3
46(57)
0.012;-3132.5
46(59)
0.011;-3050.0
46(5J)
0.017;-2967.5
46(5K)
0.018;-2885.0
5(479)
0.014;-3008.8
5J(47)
0.017;-2926.2
(57)(48)
0.027;-2780.0
4T(57)
0.015;-2967.5
4(57K)
0.018;-2843.8
47(59)
0.015;-3008.8
47(5J)
0.023;-2926.2
47(5K)
0.023;-2843.8
5(48T)
0.018;-2926.2
5Q(48)
0.016;-2843.8
(58)(4T)
0.024;-2656.3
4Q(58)
0.023;-2843.8
4589
0.008;-3237.5
458J
0.010;-3155.0
458K
0.014;-3072.5
5J(49)
0.024;-2843.8
(59)(4T)
0.039;-2615.0
4Q(59)
0.023;-2802.5
459T
0.012;-3155.0
459Q
0.012;-3072.5
(4T)(5J)
0.031;-2532.5
4T(5T)
0.039;-2573.8
4(5TK)
0.030;-2720.0
4T(5Q)
0.022;-2761.2
5J(4J)
0.043;-2491.2
(5J)(4Q)
0.046;-2450.0
4J(5Q)
0.034;-2720.0
5Q(4Q)
0.052;-2408.8
45QQ
0.028;-2678.8
45KK
0.029;-2596.2
6(469)
0.023;-2738.8
6J(46)
0.033;-2656.2
(4678)
0.016;-3008.8
(467Q)
0.017;-2843.8
7(469)
0.015;-2967.5
7J(46)
0.022;-2885.0
(4689)
0.022;-2926.2
(468K)
0.028;-2761.2
8T(46)
0.021;-2885.0
(46)(8K)
0.043;-2491.2
Q(469)
0.020;-2761.2
(46)(9J)
0.032;-2532.5
T(46T)
0.044;-2532.5
T(46J)
0.020;-2761.2
TK(46)
0.032;-2678.8
(46)(JQ)
0.040;-2408.8
QQ(46)
0.059;-2367.5
46(67)
0.024;-2821.2
66(4T)
0.029;-2697.5
466Q
0.016;-2885.0
68(47)
0.013;-3008.8
(47)(6J)
0.034;-2615.0
47(67)
0.033;-2780.0
4(67T)
0.019;-2926.2
(67)(4K)
0.041;-2532.5
67(49)
0.014;-2967.5
67(4J)
0.021;-2885.0
67(4K)
0.022;-2802.5
69(48)
0.020;-2926.2
(48)(6Q)
0.035;-2532.5
49(68)
0.022;-2926.2
4(68Q)
0.025;-2802.5
46(89)
0.016;-2926.2
46(8J)
0.021;-2843.8
46(8K)
0.028;-2761.2
(49)(6J)
0.043;-2532.5
49(69)
0.036;-2615.0
4(69Q)
0.023;-2761.2
46(9T)
0.022;-2843.8
46(9Q)
0.023;-2761.2
6(4TJ)
0.025;-2761.2
6K(4T)
0.026;-2678.8
(6T)(4K)
0.056;-2408.8
6T(4Q)
0.028;-2720.0
(4J)(6J)
0.066;-2180.0
4J(6J)
0.040;-2450.0
6J(4Q)
0.027;-2678.8
(4Q)(6Q)
0.058;-2097.5
4K(6Q)
0.027;-2596.2
4K(6K)
0.061;-2285.0
79(47)
0.029;-2656.2
(47)(7Q)
0.056;-2262.5
(478T)
0.023;-2843.8
88(47)
0.027;-2656.2
(47)(8J)
0.030;-2532.5
9(479)
0.033;-2573.8
K(479)
0.030;-2678.8
9(47Q)
0.032;-2720.0
J(47T)
0.022;-2720.0
TJ(47)
0.029;-2720.0
(47JQ)
0.040;-2637.5
J(47K)
0.033;-2596.2
(47)(QK)
0.042;-2285.0
77(49)
0.023;-2656.2
477J
0.021;-2843.8
78(48)
0.033;-2656.2
(48)(7J)
0.031;-2532.5
48(78)
0.032;-2656.2
4(78J)
0.024;-2802.5
4788
0.016;-2926.2
478T
0.011;-3113.8
478Q
0.011;-3031.2
(49)(7T)
0.040;-2532.5
7(49K)
0.029;-2678.8
4(79J)
0.026;-2761.2
4799
0.017;-2843.8
479J
0.012;-3031.2
479K
0.018;-2948.8
7Q(4T)
0.034;-2678.8
(7T)(4Q)
0.055;-2408.8
4T(7J)
0.032;-2720.0
4T(7K)
0.031;-2637.5
7(4JK)
0.028;-2596.2
4(7JK)
0.041;-2596.2
4J(7K)
0.030;-2596.2
4Q(7Q)
0.044;-2326.2
47QK
0.025;-2825.0
89(48)
0.038;-2573.8
(48)(8Q)
0.056;-2180.0
(489J)
0.032;-2720.0
(48)(9T)
0.030;-2491.2
9(48K)
0.034;-2637.5
(48TK)
0.030;-2596.2
TQ(48)
0.031;-2637.5
K(48J)
0.031;-2555.0
Q(48Q)
0.056;-2285.0
KK(48)
0.060;-2202.5
88(4J)
0.046;-2491.2
488K
0.038;-2678.8
8J(49)
0.023;-2720.0
(89)(4T)
0.041;-2491.2
4Q(89)
0.032;-2678.8
489T
0.011;-3031.2
489Q
0.018;-2948.8
(4T)(8J)
0.045;-2408.8
4T(8T)
0.048;-2450.0
4(8TK)
0.036;-2596.2
4T(8Q)
0.036;-2637.5
8J(4J)
0.052;-2367.5
(8J)(4Q)
0.049;-2326.3
4J(8Q)
0.030;-2596.2
8Q(4Q)
0.060;-2285.0
48QQ
0.040;-2555.0
48KK
0.034;-2472.5
9(49Q)
0.043;-2367.5
J(49T)
0.033;-2637.5
TJ(49)
0.032;-2637.5
(49JQ)
0.041;-2555.0
J(49K)
0.046;-2513.8
(49)(QK)
0.060;-2202.5
99(4J)
0.038;-2408.8
499K
0.043;-2596.2
9Q(4T)
0.040;-2596.2
(9T)(4Q)
0.044;-2326.3
4T(9J)
0.033;-2637.5
4T(9K)
0.039;-2555.0
9(4JK)
0.044;-2513.8
4(9JK)
0.034;-2513.8
4J(9K)
0.042;-2513.8
4Q(9Q)
0.044;-2243.8
49QK
0.028;-2742.5
TJ(4T)
0.054;-2326.2
(4TJQ)
0.033;-2513.8
J(4TK)
0.043;-2472.5
(4T)(QK)
0.049;-2161.2
TT(4Q)
0.057;-2285.0
T(4JQ)
0.040;-2513.8
4(TJQ)
0.038;-2513.8
4T(JQ)
0.039;-2513.8
T(4QK)
0.041;-2431.2
TQ(4K)
0.045;-2431.2
JJ(4J)
0.066;-1973.8
(4JQK)
0.046;-2390.0
4JJJ
0.059;-2243.8
JQ(4Q)
0.065;-2161.2
4JQQ
0.039;-2431.2
4JKK
0.059;-2348.8
QQ(4K)
0.061;-2078.8
4KKK
0.068;-1996.3
55(59)
0.031;-2510.0
55(5K)
0.057;-2345.0
(56)(58)
0.035;-2510.0
5(56J)
0.027;-2656.2
5K(56)
0.031;-2573.8
56(59)
0.024;-2738.8
556J
0.023;-2926.2
57(57)
0.041;-2510.0
(57)(5T)
0.038;-2386.2
5(57K)
0.050;-2532.5
55(79)
0.027;-2697.5
57(5Q)
0.039;-2573.8
5(589)
0.031;-2656.2
5J(58)
0.037;-2573.8
58(59)
0.026;-2656.2
558J
0.018;-2843.8
59(59)
0.053;-2345.0
(59)(5Q)
0.061;-2221.3
559T
0.019;-2843.8
55(9K)
0.044;-2450.0
(5T)(5Q)
0.068;-2180.0
55TJ
0.019;-2761.2
5J(5J)
0.060;-2180.0
5J(5Q)
0.037;-2408.8
5(5QK)
0.057;-2326.2
5K(5K)
0.066;-2015.0
68(56)
0.030;-2738.8
(56)(6J)
0.052;-2345.0
7(567)
0.027;-2738.8
J(567)
0.022;-2843.8
78(56)
0.016;-2967.5
(56)(7J)
0.040;-2573.8
8(568)
0.028;-2656.2
Q(568)
0.025;-2761.2
(56)(8T)
0.036;-2573.8
8(56K)
0.023;-2720.0
(569Q)
0.027;-2720.0
9(56J)
0.024;-2761.2
9K(56)
0.035;-2678.8
TT(56)
0.033;-2491.2
(56)(TK)
0.042;-2367.5
J(56Q)
0.034;-2637.5
K(56Q)
0.043;-2555.0
66(57)
0.021;-2780.0
5669
0.014;-2967.5
56(6Q)
0.036;-2573.8
(57)(68)
0.035;-2697.5
6(57J)
0.023;-2843.8
6K(57)
0.030;-2761.2
(67)(5T)
0.030;-2615.0
5Q(67)
0.030;-2802.5
5678
0.009;-3237.5
567T
0.012;-3155.0
567Q
0.011;-3072.5
(58)(69)
0.039;-2615.0
6(58Q)
0.019;-2761.2
5(689)
0.017;-2885.0
(68)(5Q)
0.033;-2491.2
58(69)
0.020;-2885.0
58(6J)
0.023;-2802.5
58(6K)
0.029;-2720.0
6(59J)
0.028;-2761.2
6K(59)
0.024;-2678.8
(69)(5Q)
0.034;-2450.0
59(6T)
0.025;-2802.5
59(6Q)
0.024;-2720.0
6T(5T)
0.047;-2491.2
(5T)(6K)
0.039;-2367.5
5Q(6T)
0.030;-2678.8
56TJ
0.017;-2990.0
56TK
0.016;-2907.5
6K(5J)
0.033;-2596.2
56JJ
0.033;-2678.8
56JK
0.015;-2866.2
5(6QK)
0.027;-2555.0
6K(5K)
0.063;-2243.8
(57)(79)
0.047;-2345.0
7(57Q)
0.039;-2491.2
9(578)
0.020;-2843.8
K(578)
0.032;-2678.8
8(57J)
0.025;-2761.2
8K(57)
0.036;-2678.8
(579K)
0.030;-2637.5
9J(57)
0.036;-2720.0
(57TJ)
0.037;-2678.8
(57)(TJ)
0.054;-2408.8
J(57J)
0.056;-2367.5
JQ(57)
0.040;-2596.2
Q(57K)
0.042;-2513.8
5778
0.023;-2926.2
57(7J)
0.032;-2532.5
(58)(78)
0.057;-2345.0
7(58J)
0.025;-2761.2
7K(58)
0.028;-2678.8
(78)(5J)
0.029;-2491.2
5K(78)
0.031;-2678.8
57(8T)
0.025;-2802.5
57(8Q)
0.031;-2720.0
7(59T)
0.029;-2761.2
7Q(59)
0.030;-2678.8
(79)(5J)
0.039;-2450.0
5K(79)
0.030;-2637.5
57(9J)
0.028;-2720.0
57(9K)
0.032;-2637.5
(5T)(7Q)
0.060;-2367.5
5J(7T)
0.030;-2678.8
7T(5J)
0.026;-2678.8
7T(5K)
0.030;-2596.2
7Q(5J)
0.039;-2596.2
(7J)(5K)
0.045;-2285.0
7J(5K)
0.029;-2555.0
7K(5Q)
0.042;-2513.8
57(QK)
0.033;-2513.8
(58)(89)
0.057;-2262.5
8(58Q)
0.040;-2408.8
T(589)
0.038;-2720.0
9(58T)
0.026;-2720.0
9Q(58)
0.025;-2637.5
Q(58T)
0.038;-2596.2
(58)(TQ)
0.044;-2326.3
(58JK)
0.041;-2513.8
JK(58)
0.050;-2513.8
K(58K)
0.069;-2161.2
588T
0.023;-2761.2
58(8K)
0.056;-2367.5
(59)(8J)
0.048;-2408.8
59(89)
0.033;-2491.2
5(89Q)
0.041;-2637.5
58(9T)
0.034;-2720.0
58(9Q)
0.029;-2637.5
8(5TJ)
0.029;-2637.5
8K(5T)
0.033;-2555.0
(8T)(5K)
0.049;-2285.0
8T(5Q)
0.041;-2596.2
(5J)(8J)
0.080;-2056.2
5J(8J)
0.059;-2326.2
8J(5Q)
0.040;-2555.0
(5Q)(8Q)
0.070;-1973.8
5K(8Q)
0.038;-2472.5
5K(8K)
0.062;-2161.2
9J(59)
0.036;-2367.5
(59TJ)
0.040;-2596.2
(59)(TJ)
0.046;-2326.3
J(59J)
0.041;-2285.0
JQ(59)
0.037;-2513.8
Q(59K)
0.035;-2431.2
599T
0.028;-2678.8
59(9K)
0.057;-2285.0
(5T)(9Q)
0.055;-2285.0
5J(9T)
0.040;-2596.2
9T(5J)
0.030;-2596.2
9T(5K)
0.036;-2513.8
9Q(5J)
0.053;-2513.8
(9J)(5K)
0.071;-2202.5
9J(5K)
0.041;-2472.5
9K(5Q)
0.040;-2431.2
59(QK)
0.058;-2431.2
(5T)(TJ)
0.079;-2015.0
J(5TJ)
0.059;-2243.8
JQ(5T)
0.030;-2472.5
Q(5TK)
0.054;-2390.0
5TTJ
0.037;-2555.0
TJ(5J)
0.068;-2243.8
(TJ)(5Q)
0.064;-2202.5
5J(TQ)
0.042;-2472.5
TQ(5Q)
0.050;-2161.2
5TQQ
0.048;-2431.2
5TKK
0.048;-2348.8
Q(5JQ)
0.079;-2120.0
KK(5J)
0.076;-2037.5
(5Q)(JQ)
0.087;-1850.0
5K(JQ)
0.041;-2348.8
5K(JK)
0.061;-2037.5
5QQQ
0.089;-2078.8
KK(5K)
0.103;-1685.0
6669
0.030;-2656.3
666K
0.038;-2491.2
69(67)
0.026;-2615.0
(67)(6Q)
0.063;-2221.3
6678
0.017;-2926.2
66(7J)
0.041;-2532.5
(68)(68)
0.068;-2075.0
6(68J)
0.046;-2491.2
6K(68)
0.041;-2408.8
68(6J)
0.041;-2491.2
668K
0.028;-2678.8
6J(69)
0.038;-2450.0
69(6T)
0.041;-2491.2
669Q
0.035;-2678.8
6J(6T)
0.047;-2408.8
6T(6J)
0.057;-2408.8
66TK
0.030;-2596.2
6K(6J)
0.049;-2285.0
(6Q)(6Q)
0.106;-1745.0
66QK
0.034;-2513.8
7(679)
0.037;-2573.8
7J(67)
0.049;-2491.2
(6789)
0.023;-2802.5
(678K)
0.024;-2637.5
8T(67)
0.023;-2761.2
(67)(8K)
0.049;-2367.5
Q(679)
0.026;-2637.5
(67)(9J)
0.055;-2408.8
T(67T)
0.046;-2408.8
T(67J)
0.032;-2637.5
TK(67)
0.035;-2555.0
(67)(JQ)
0.047;-2285.0
QQ(67)
0.057;-2243.8
67(78)
0.037;-2615.0
77(6J)
0.037;-2491.2
677K
0.027;-2678.8
7T(68)
0.032;-2761.2
(68)(7K)
0.052;-2367.5
6T(78)
0.026;-2761.2
6(78K)
0.030;-2637.5
68(7T)
0.024;-2761.2
68(7Q)
0.030;-2678.8
79(69)
0.040;-2491.2
(69)(7Q)
0.040;-2367.5
6T(79)
0.027;-2720.0
6(79K)
0.031;-2596.2
69(7J)
0.036;-2678.8
69(7K)
0.043;-2596.2
7(6TQ)
0.032;-2596.2
6(7TJ)
0.036;-2637.5
67TT
0.032;-2678.8
67TQ
0.021;-2866.2
(6J)(7Q)
0.055;-2285.0
6Q(7J)
0.039;-2555.0
67JQ
0.023;-2825.0
(6Q)(7K)
0.071;-2202.5
6Q(7K)
0.041;-2472.5
8(689)
0.029;-2491.2
8J(68)
0.045;-2408.8
(689T)
0.030;-2678.8
99(68)
0.051;-2450.0
(68)(9Q)
0.057;-2326.3
(68TQ)
0.040;-2555.0
T(68Q)
0.033;-2555.0
Q(68J)
0.039;-2513.8
(68)(JK)
0.060;-2202.5
QK(68)
0.046;-2431.2
68(8T)
0.038;-2450.0
88(6K)
0.041;-2326.2
8(69J)
0.042;-2637.5
8K(69)
0.038;-2555.0
(89)(6Q)
0.046;-2326.3
69(8T)
0.028;-2678.8
69(8Q)
0.036;-2596.2
8T(6T)
0.053;-2367.5
(6T)(8K)
0.059;-2243.8
6Q(8T)
0.031;-2555.0
68TJ
0.020;-2866.2
68TK
0.018;-2783.8
8K(6J)
0.045;-2472.5
68JJ
0.038;-2555.0
68JK
0.024;-2742.5
6(8QK)
0.041;-2431.2
8K(6K)
0.072;-2120.0
(69)(9J)
0.058;-2056.2
T(69T)
0.051;-2326.2
T(69J)
0.038;-2555.0
TK(69)
0.045;-2472.5
(69)(JQ)
0.070;-2202.5
QQ(69)
0.087;-2161.2
69(9T)
0.050;-2367.5
99(6K)
0.071;-2243.8
9(6TQ)
0.030;-2513.8
6(9TJ)
0.036;-2555.0
69TT
0.043;-2596.2
69TQ
0.024;-2783.8
(6J)(9Q)
0.059;-2202.5
6Q(9J)
0.033;-2472.5
69JQ
0.028;-2742.5
(6Q)(9K)
0.067;-2120.0
6Q(9K)
0.040;-2390.0
T(6TJ)
0.058;-2243.8
TK(6T)
0.062;-2161.2
(6T)(JQ)
0.076;-2161.2
QQ(6T)
0.072;-2120.0
6T(TJ)
0.051;-2243.8
(6J)(TJ)
0.079;-1932.5
6J(TJ)
0.053;-2202.5
TJ(6Q)
0.048;-2431.2
(6Q)(TQ)
0.067;-1850.0
6K(TQ)
0.045;-2348.8
6K(TK)
0.074;-2037.5
JK(6J)
0.057;-2078.8
K(6JK)
0.067;-1996.3
6JJK
0.059;-2348.8
6(JQK)
0.059;-2307.5
JK(6K)
0.077;-1996.3
KK(6Q)
0.086;-1955.0
6QKK
0.054;-2225.0
77(7T)
0.054;-2221.2
(78)(78)
0.072;-1992.5
7(78J)
0.042;-2408.8
7K(78)
0.057;-2326.2
78(7J)
0.058;-2408.8
778K
0.037;-2596.2
7J(79)
0.046;-2367.5
79(7T)
0.051;-2408.8
779Q
0.030;-2596.2
7J(7T)
0.066;-2326.2
7T(7J)
0.065;-2326.2
77TK
0.042;-2513.8
7K(7J)
0.051;-2202.5
(7Q)(7Q)
0.103;-1662.5
77QK
0.041;-2431.2
8(78T)
0.041;-2408.8
8Q(78)
0.047;-2326.2
J(789)
0.031;-2596.2
9T(78)
0.024;-2637.5
(78)(9K)
0.045;-2243.8
K(78T)
0.051;-2472.5
T(78K)
0.047;-2472.5
JJ(78)
0.042;-2243.8
(78QK)
0.039;-2390.0
7888
0.034;-2491.2
78(8J)
0.042;-2367.5
(79)(89)
0.053;-2138.8
8(79Q)
0.035;-2555.0
7(89T)
0.027;-2637.5
(89)(7K)
0.069;-2243.8
89(7J)
0.032;-2596.2
89(7K)
0.044;-2513.8
8J(7T)
0.040;-2555.0
(8T)(7J)
0.063;-2285.0
7K(8T)
0.037;-2472.5
78(TQ)
0.031;-2513.8
8(7JQ)
0.045;-2472.5
7(8JQ)
0.048;-2472.5
78(JQ)
0.037;-2472.5
8(7QK)
0.054;-2390.0
8Q(7K)
0.048;-2390.0
99(79)
0.066;-2097.5
(79)(9Q)
0.093;-1973.8
(79TQ)
0.031;-2472.5
T(79Q)
0.040;-2472.5
Q(79J)
0.040;-2431.2
(79)(JK)
0.056;-2120.0
QK(79)
0.046;-2348.8
79(9J)
0.047;-2285.0
(7T)(9T)
0.081;-2015.0
9(7TK)
0.034;-2431.2
7(9TQ)
0.044;-2472.5
79(TJ)
0.038;-2513.8
79(TK)
0.036;-2431.2
(7J)(9K)
0.060;-2120.0
7K(9J)
0.044;-2390.0
79(JK)
0.056;-2390.0
(9Q)(7K)
0.058;-2078.8
(7K)(9K)
0.081;-1767.5
T(7TQ)
0.063;-2161.2
Q(7TJ)
0.050;-2390.0
(7T)(JK)
0.067;-2078.8
QK(7T)
0.063;-2307.5
7T(TQ)
0.065;-2161.2
(7J)(TQ)
0.069;-2120.0
7Q(TJ)
0.042;-2390.0
7TJQ
0.031;-2660.0
(7Q)(TK)
0.057;-2037.5
7Q(TK)
0.051;-2307.5
J(7JQ)
0.084;-2078.8
K(7JQ)
0.053;-2266.2
JJ(7Q)
0.063;-2078.8
J(7QK)
0.068;-2266.2
JQ(7K)
0.056;-2266.2
QQ(7Q)
0.134;-1726.3
7Q(QK)
0.077;-1955.0
8888
0.064;-2180.0
888Q
0.056;-2285.0
8(89J)
0.054;-2285.0
8K(89)
0.068;-2202.5
89(8Q)
0.055;-2243.8
8(8TJ)
0.073;-2243.8
8K(8T)
0.078;-2161.2
8T(8K)
0.061;-2161.2
8(8JK)
0.066;-2120.0
88(JK)
0.051;-2120.0
8Q(8K)
0.077;-2078.8
(89)(9T)
0.070;-2015.0
9(89K)
0.078;-2161.2
(89TK)
0.051;-2390.0
TQ(89)
0.036;-2431.2
K(89J)
0.040;-2348.8
Q(89Q)
0.060;-2078.8
KK(89)
0.074;-1996.3
99(8Q)
0.061;-2202.5
9(8TJ)
0.044;-2472.5
9K(8T)
0.044;-2390.0
(9T)(8K)
0.063;-2120.0
9T(8Q)
0.048;-2431.2
(8J)(9J)
0.090;-1891.2
8J(9J)
0.060;-2161.2
9J(8Q)
0.035;-2390.0
(8Q)(9Q)
0.105;-1808.8
8K(9Q)
0.046;-2307.5
8K(9K)
0.090;-1996.3
TQ(8T)
0.080;-2120.0
K(8TJ)
0.050;-2307.5
Q(8TQ)
0.070;-2037.5
KK(8T)
0.096;-1955.0
