AAAA
0.410;495.0
5AAA
0.319;174.4
9AAA
0.401;256.9
KAAA
0.366;339.4
4A(2A)
0.382;-93.7
(2A)(7A)
0.392;103.1
A(2TA)
0.376;30.0
QA(2A)
0.370;71.3
2A(4A)
0.324;-93.7
26AA
0.376;-187.5
AA(29)
0.415;9.4
2A(QA)
0.415;71.3
A(34A)
0.360;-73.1
6A(3A)
0.337;-31.9
(3A)(9A)
0.333;165.0
A(3QA)
0.333;91.9
AA(34)
0.322;-73.1
3A(7A)
0.344;-11.2
39AA
0.354;-105.0
AA(3Q)
0.420;91.9
(4A)(5A)
0.358;103.1
A(48A)
0.384;30.0
TA(4A)
0.381;71.3
(4A)(KA)
0.378;268.1
46AA
0.355;-146.2
AA(49)
0.387;50.6
4A(QA)
0.344;112.5
A(56A)
0.326;9.4
8A(5A)
0.336;50.6
(5A)(JA)
0.381;247.5
55AA
0.411;-11.2
AA(58)
0.368;50.6
5A(JA)
0.418;112.5
5KAA
0.443;18.7
8A(6A)
0.322;71.3
(6A)(JA)
0.361;268.1
66AA
0.433;30.0
AA(69)
0.335;91.9
6A(QA)
0.433;153.7
A(78A)
0.341;91.9
TA(7A)
0.375;133.1
(7A)(KA)
0.394;330.0
79AA
0.355;-22.5
AA(7Q)
0.354;174.4
(8A)(9A)
0.315;268.1
A(8QA)
0.427;195.0
AA(89)
0.333;133.1
8A(QA)
0.471;195.0
A(9TA)
0.365;174.4
QA(9A)
0.411;215.6
9A(JA)
0.391;195.0
9KAA
0.344;101.3
QA(TA)
0.397;236.2
TA(QA)
0.339;236.2
A(JQA)
0.376;256.9
AA(JQ)
0.381;256.9
(QA)(KA)
0.342;433.1
KKAA
0.405;318.8
2(25A)
0.361;-320.6
27(2A)
0.302;-279.4
(2T)(2A)
0.412;-82.5
2(2KA)
0.335;-155.6
(236A)
0.288;-414.4
(23TA)
0.313;-331.9
33(2A)
0.322;-341.2
(36)(2A)
0.378;-279.4
3(29A)
0.322;-352.5
3J(2A)
0.329;-311.2
(245A)
0.258;-414.4
(249A)
0.335;-331.9
(24KA)
0.344;-249.4
46(2A)
0.362;-393.8
(49)(2A)
0.399;-196.9
4(2QA)
0.324;-270.0
6(25A)
0.278;-373.1
T(25A)
0.262;-290.6
5(26A)
0.373;-373.1
58(2A)
0.341;-331.9
(5J)(2A)
0.306;-135.0
6(26A)
0.343;-217.5
T(26A)
0.357;-270.0
6(27A)
0.272;-331.9
69(2A)
0.358;-290.6
(6Q)(2A)
0.372;-93.8
(279A)
0.327;-270.0
(27KA)
0.361;-187.5
79(2A)
0.348;-270.0
(7Q)(2A)
0.414;-73.1
(28TA)
0.339;-228.7
88(2A)
0.334;-135.0
(8J)(2A)
0.412;-73.1
9(29A)
0.384;-93.7
K(29A)
0.342;-146.2
9(2QA)
0.331;-166.9
J(2TA)
0.305;-166.9
TJ(2A)
0.345;-166.9
(2JQA)
0.398;-125.6
J(2KA)
0.361;-105.0
(QK)(2A)
0.334;50.6
22(4A)
0.314;-341.2
226A
0.331;-435.0
2A(29)
0.305;-238.1
22(QA)
0.296;-176.2
2(34A)
0.320;-455.6
26(3A)
0.352;-414.4
(29)(3A)
0.305;-217.5
2(3QA)
0.372;-290.6
A(234)
0.299;-455.6
(23)(7A)
0.296;-258.8
9A(23)
0.362;-352.5
A(23Q)
0.332;-290.6
2A(34)
0.335;-455.6
2A(36)
0.269;-414.4
2A(38)
0.332;-373.1
2A(3T)
0.343;-331.9
2A(3Q)
0.318;-290.6
2(45A)
0.325;-414.4
27(4A)
0.384;-373.1
(2T)(4A)
0.320;-176.2
2(4KA)
0.368;-249.4
A(246)
0.313;-393.8
(24)(9A)
0.335;-196.9
JA(24)
0.359;-290.6
24(5A)
0.317;-414.4
24(7A)
0.294;-373.1
24(9A)
0.314;-331.9
24(JA)
0.304;-290.6
24(KA)
0.341;-249.4
26(5A)
0.314;-373.1
(29)(5A)
0.362;-176.2
2(5QA)
0.326;-249.4
A(256)
0.352;-373.1
(25)(9A)
0.398;-176.2
JA(25)
0.297;-270.0
25(6A)
0.318;-373.1
25(8A)
0.364;-331.9
25(TA)
0.268;-290.6
25(QA)
0.326;-249.4
(26)(6A)
0.425;-82.5
2(69A)
0.350;-290.6
2J(6A)
0.281;-249.4
(26)(7A)
0.345;-196.9
9A(26)
0.315;-290.6
A(26Q)
0.348;-228.7
2A(67)
0.259;-331.9
2A(69)
0.328;-290.6
2A(6J)
0.343;-249.4
2A(6K)
0.367;-208.1
(29)(7A)
0.331;-135.0
2(7QA)
0.289;-208.1
A(278)
0.303;-290.6
(27)(JA)
0.367;-93.8
KA(27)
0.322;-187.5
2A(79)
0.314;-270.0
2A(7J)
0.292;-228.7
2A(7K)
0.301;-187.5
(2T)(8A)
0.339;-93.8
2(8KA)
0.354;-166.9
A(28T)
0.400;-228.7
(28)(KA)
0.384;-31.9
28(TA)
0.373;-228.7
28(QA)
0.362;-187.5
(29)(9A)
0.346;41.3
2(9QA)
0.296;-166.9
A(29T)
0.350;-208.1
(29)(KA)
0.387;-11.2
29(JA)
0.419;-187.5
29(KA)
0.338;-146.2
2J(TA)
0.346;-166.9
(2T)(JA)
0.404;-31.9
KA(2T)
0.294;-125.6
2A(TQ)
0.326;-146.2
2(JQA)
0.349;-125.6
A(2JQ)
0.368;-125.6
2A(JQ)
0.363;-125.6
2(QKA)
0.302;-84.4
2Q(KA)
0.316;-84.4
33(3A)
0.319;-185.6
(36)(3A)
0.337;-123.7
3(39A)
0.297;-196.9
3J(3A)
0.374;-155.6
(345A)
0.365;-393.8
(349A)
0.309;-311.2
(34KA)
0.356;-228.7
46(3A)
0.309;-373.1
(49)(3A)
0.307;-176.2
4(3QA)
0.369;-249.4
6(35A)
0.326;-352.5
T(35A)
0.350;-270.0
5(36A)
0.314;-352.5
58(3A)
0.398;-311.2
(5J)(3A)
0.308;-114.4
6(36A)
0.407;-196.9
T(36A)
0.357;-249.4
6(37A)
0.289;-311.2
69(3A)
0.305;-270.0
(6Q)(3A)
0.343;-73.1
(379A)
0.373;-249.4
(37KA)
0.312;-166.9
79(3A)
0.377;-249.4
(7Q)(3A)
0.336;-52.5
(38TA)
0.385;-208.1
88(3A)
0.338;-114.4
(8J)(3A)
0.377;-52.5
9(39A)
0.364;-73.1
K(39A)
0.339;-125.6
9(3QA)
0.329;-146.2
J(3TA)
0.326;-146.2
TJ(3A)
0.394;-146.2
(3JQA)
0.397;-105.0
J(3KA)
0.404;-84.4
(QK)(3A)
0.377;71.3
33(5A)
0.339;-279.4
337A
0.328;-373.1
3A(3T)
0.370;-176.2
33(KA)
0.320;-114.4
3(46A)
0.259;-373.1
38(4A)
0.353;-331.9
(3J)(4A)
0.409;-135.0
4A(34)
0.379;-279.4
A(347)
0.312;-352.5
(34)(TA)
0.295;-155.6
QA(34)
0.317;-249.4
345A
0.245;-528.7
347A
0.290;-487.5
349A
0.342;-446.2
34JA
0.310;-405.0
34KA
0.353;-363.7
37(5A)
0.373;-331.9
(3T)(5A)
0.394;-135.0
3(5KA)
0.302;-208.1
A(357)
0.376;-331.9
(35)(TA)
0.322;-135.0
QA(35)
0.361;-228.7
356A
0.328;-487.5
358A
0.315;-446.2
35TA
0.394;-405.0
35QA
0.284;-363.7
(37)(6A)
0.355;-176.2
3(6TA)
0.352;-249.4
3Q(6A)
0.288;-208.1
(36)(8A)
0.318;-155.6
TA(36)
0.321;-249.4
A(36K)
0.321;-187.5
6A(38)
0.374;-290.6
6A(3T)
0.350;-249.4
6A(3Q)
0.319;-208.1
37(7A)
0.284;-155.6
(3T)(7A)
0.321;-93.8
3(7KA)
0.353;-166.9
A(379)
0.348;-249.4
(37)(QA)
0.312;-52.5
7A(38)
0.366;-270.0
7A(3T)
0.346;-228.7
7A(3Q)
0.346;-187.5
38(8A)
0.313;-114.4
(3J)(8A)
0.384;-52.5
8A(38)
0.366;-114.4
A(38J)
0.367;-187.5
388A
0.334;-249.4
38TA
0.318;-343.1
38QA
0.365;-301.9
(3T)(9A)
0.430;-52.5
3(9KA)
0.299;-125.6
A(39J)
0.364;-166.9
399A
0.299;-208.1
39JA
0.383;-301.9
39KA
0.347;-260.6
3Q(TA)
0.308;-125.6
(3T)(QA)
0.306;9.4
TA(3J)
0.313;-146.2
TA(3K)
0.303;-105.0
3(JKA)
0.380;-84.4
A(3JK)
0.363;-84.4
JA(3K)
0.307;-84.4
QA(3Q)
0.393;50.6
3QKA
0.350;-198.7
45(4A)
0.364;-238.1
(48)(4A)
0.378;-41.3
4(4JA)
0.324;-114.4
4K(4A)
0.276;-73.1
(459A)
0.378;-270.0
(45KA)
0.327;-187.5
57(4A)
0.334;-311.2
(5T)(4A)
0.297;-114.4
5(4KA)
0.319;-187.5
(469A)
0.359;-249.4
(46KA)
0.324;-166.9
68(4A)
0.359;-270.0
(6J)(4A)
0.332;-73.1
7(47A)
0.352;-135.0
J(47A)
0.377;-187.5
78(4A)
0.338;-249.4
(7J)(4A)
0.337;-52.5
8(48A)
0.357;-93.7
Q(48A)
0.369;-146.2
(8T)(4A)
0.397;-52.5
8(4KA)
0.375;-125.6
(49QA)
0.357;-125.6
9(4JA)
0.331;-146.2
9K(4A)
0.291;-105.0
TT(4A)
0.337;-11.2
(TK)(4A)
0.320;50.6
J(4QA)
0.365;-84.4
K(4QA)
0.324;-43.1
44(5A)
0.280;-238.1
447A
0.360;-331.9
4A(4T)
0.384;-135.0
44(KA)
0.281;-73.1
4(57A)
0.330;-311.2
49(5A)
0.321;-270.0
(4Q)(5A)
0.403;-73.1
6A(45)
0.356;-331.9
A(459)
0.325;-270.0
(45)(QA)
0.415;-73.1
5A(46)
0.343;-331.9
5A(48)
0.353;-290.6
5A(4T)
0.305;-249.4
5A(4Q)
0.295;-208.1
46(6A)
0.321;-176.2
(49)(6A)
0.317;-114.4
4(6QA)
0.326;-187.5
A(467)
0.334;-290.6
(46)(TA)
0.363;-93.8
QA(46)
0.358;-187.5
467A
0.267;-425.6
469A
0.328;-384.4
46JA
0.340;-343.1
46KA
0.330;-301.9
49(7A)
0.296;-228.7
(4Q)(7A)
0.339;-31.9
8A(47)
0.392;-249.4
A(47J)
0.303;-187.5
477A
0.358;-270.0
479A
0.377;-363.7
47JA
0.275;-322.5
47KA
0.381;-281.2
4T(8A)
0.367;-187.5
(4K)(8A)
0.390;9.4
TA(48)
0.363;-187.5
A(48K)
0.333;-125.6
8A(4T)
0.281;-187.5
8A(4Q)
0.342;-146.2
49(9A)
0.429;-52.5
(4Q)(9A)
0.346;9.4
TA(49)
0.325;-166.9
A(49K)
0.344;-105.0
9A(4J)
0.366;-146.2
9A(4K)
0.343;-105.0
4(TQA)
0.301;-105.0
A(4TJ)
0.376;-125.6
4TTA
0.291;-146.2
4TQA
0.298;-240.0
(4Q)(JA)
0.363;50.6
QA(4J)
0.359;-84.4
4JQA
0.377;-219.4
(4K)(QA)
0.355;91.9
QA(4K)
0.346;-43.1
5(56A)
0.325;-176.2
58(5A)
0.314;-135.0
(5J)(5A)
0.376;61.9
6(56A)
0.399;-155.6
T(56A)
0.331;-208.1
6(57A)
0.395;-270.0
69(5A)
0.301;-228.7
(6Q)(5A)
0.432;-31.9
(579A)
0.364;-208.1
(57KA)
0.373;-125.6
79(5A)
0.315;-208.1
(7Q)(5A)
0.386;-11.2
(58TA)
0.354;-166.9
88(5A)
0.358;-73.1
(8J)(5A)
0.318;-11.2
9(59A)
0.370;-31.9
K(59A)
0.318;-84.4
9(5QA)
0.362;-105.0
J(5TA)
0.376;-105.0
TJ(5A)
0.363;-105.0
(5JQA)
0.409;-63.7
J(5KA)
0.330;-43.1
(QK)(5A)
0.420;112.5
55(7A)
0.367;-155.6
559A
0.377;-249.4
5A(5Q)
0.419;-52.5
(57)(6A)
0.325;-135.0
5(6TA)
0.304;-208.1
5Q(6A)
0.398;-166.9
(56)(8A)
0.375;-114.4
TA(56)
0.427;-208.1
A(56K)
0.358;-146.2
6A(58)
0.354;-249.4
6A(5T)
0.323;-208.1
6A(5Q)
0.357;-166.9
57(7A)
0.357;-114.4
(5T)(7A)
0.405;-52.5
5(7KA)
0.431;-125.6
A(579)
0.365;-208.1
(57)(QA)
0.371;-11.2
7A(58)
0.323;-228.7
7A(5T)
0.305;-187.5
7A(5Q)
0.369;-146.2
58(8A)
0.342;-73.1
(5J)(8A)
0.377;-11.2
8A(58)
0.339;-73.1
A(58J)
0.359;-146.2
588A
0.284;-208.1
58TA
0.352;-301.9
58QA
0.387;-260.6
(5T)(9A)
0.390;-11.2
5(9KA)
0.403;-84.4
A(59J)
0.382;-125.6
599A
0.338;-166.9
59JA
0.327;-260.6
59KA
0.382;-219.4
5Q(TA)
0.368;-84.4
(5T)(QA)
0.329;50.6
TA(5J)
0.387;-105.0
TA(5K)
0.365;-63.7
5(JKA)
0.400;-43.1
A(5JK)
0.323;-43.1
JA(5K)
0.301;-43.1
QA(5Q)
0.363;91.9
5QKA
0.356;-157.5
67(6A)
0.304;-114.4
(6T)(6A)
0.348;82.5
6(6KA)
0.369;9.4
(67TA)
0.367;-166.9
77(6A)
0.339;-93.7
(7T)(6A)
0.374;-31.9
7(6KA)
0.390;-105.0
(68JA)
0.342;-125.6
(89)(6A)
0.331;-31.9
8(6QA)
0.308;-105.0
T(69A)
0.405;-125.6
9(6TA)
0.373;-125.6
9Q(6A)
0.326;-84.4
Q(6TA)
0.386;-63.7
(TQ)(6A)
0.361;71.3
(6JKA)
0.349;-22.5
JK(6A)
0.438;-22.5
K(6KA)
0.392;153.7
668A
0.334;-228.7
6A(6J)
0.422;-31.9
(67)(7A)
0.359;41.3
6(7TA)
0.416;-166.9
6Q(7A)
0.428;-125.6
(67)(9A)
0.333;-52.5
JA(67)
0.353;-146.2
67(8A)
0.354;-208.1
67(TA)
0.325;-166.9
67(QA)
0.410;-125.6
(68)(8A)
0.412;82.5
6(8JA)
0.419;-125.6
6K(8A)
0.373;-84.4
(68)(JA)
0.360;9.4
KA(68)
0.341;-84.4
6A(8T)
0.333;-146.2
6A(8Q)
0.356;-105.0
6(9TA)
0.436;-125.6
6Q(9A)
0.306;-84.4
(69)(JA)
0.370;30.0
KA(69)
0.325;-63.7
6A(9J)
0.342;-105.0
6A(9K)
0.367;-63.7
(6Q)(TA)
0.425;71.3
JA(6T)
0.368;-84.4
6T(JA)
0.339;-84.4
6T(KA)
0.366;-43.1
6Q(JA)
0.348;-43.1
(6J)(KA)
0.402;112.5
6J(KA)
0.342;-22.5
6K(QA)
0.403;-1.9
6A(QK)
0.374;-1.9
(78)(7A)
0.377;82.5
7(7JA)
0.322;9.4
7K(7A)
0.382;50.6
(78QA)
0.348;-84.4
8(7TA)
0.409;-125.6
8Q(7A)
0.402;-84.4
J(79A)
0.333;-84.4
9T(7A)
0.301;-105.0
(9K)(7A)
0.330;91.9
K(7TA)
0.319;-22.5
T(7KA)
0.360;-22.5
JJ(7A)
0.422;91.9
(7QKA)
0.381;18.7
777A
0.366;-73.1
7A(7T)
0.364;-11.2
77(KA)
0.429;50.6
7(8TA)
0.364;-125.6
7Q(8A)
0.413;-84.4
(78)(TA)
0.361;9.4
QA(78)
0.360;-84.4
789A
0.379;-281.2
78JA
0.273;-240.0
78KA
0.362;-198.7
7J(9A)
0.354;-84.4
(79)(TA)
0.384;30.0
QA(79)
0.385;-63.7
79TA
0.363;-240.0
79QA
0.357;-198.7
(7J)(TA)
0.358;71.3
TA(7T)
0.369;50.6
A(7TK)
0.367;-22.5
TA(7Q)
0.388;-43.1
7J(JA)
0.368;91.9
(7J)(QA)
0.415;112.5
JA(7Q)
0.359;-22.5
7Q(QA)
0.383;133.1
7QQA
0.410;-1.9
7KKA
0.328;39.4
8(8JA)
0.383;50.6
8K(8A)
0.375;91.9
(89KA)
0.393;-22.5
9J(8A)
0.349;-63.7
(8TJA)
0.419;-43.1
(TJ)(8A)
0.405;91.9
J(8JA)
0.356;112.5
JQ(8A)
0.360;-1.9
Q(8KA)
0.345;39.4
889A
0.378;-125.6
8A(8Q)
0.343;71.3
(8T)(9A)
0.387;50.6
8(9KA)
0.317;-22.5
A(89J)
0.333;-63.7
899A
0.361;-105.0
89JA
0.345;-198.7
89KA
0.385;-157.5
8Q(TA)
0.379;-22.5
(8T)(QA)
0.360;112.5
TA(8J)
0.437;-43.1
TA(8K)
0.332;-1.9
8(JKA)
0.407;18.7
A(8JK)
0.320;18.7
JA(8K)
0.391;18.7
QA(8Q)
0.353;153.7
8QKA
0.301;-95.6
9T(9A)
0.401;71.3
(9K)(9A)
0.426;268.1
K(9TA)
0.343;18.7
T(9KA)
0.443;18.7
JJ(9A)
0.385;133.1
(9QKA)
0.396;60.0
999A
0.361;50.6
9A(9Q)
0.341;112.5
(9J)(TA)
0.346;112.5
TA(9T)
0.341;91.9
A(9TK)
0.380;18.7
TA(9Q)
0.318;-1.9
9J(JA)
0.382;133.1
(9J)(QA)
0.407;153.8
JA(9Q)
0.376;18.7
9Q(QA)
0.445;174.4
9QQA
0.319;39.4
9KKA
0.309;80.6
T(TKA)
0.381;174.4
JJ(TA)
0.323;153.7
(TQKA)
0.336;80.6
TTTA
0.426;112.5
TA(TK)
0.435;174.4
(TK)(JA)
0.447;195.0
KA(TJ)
0.368;60.0
TA(JK)
0.441;60.0
(TQ)(KA)
0.370;215.6
(TK)(KA)
0.360;371.3
J(JKA)
0.360;215.6
(QK)(JA)
0.385;236.3
JJ(KA)
0.399;215.6
QA(JQ)
0.360;215.6
JQKA
0.365;-33.7
QK(QA)
0.404;256.9
QK(KA)
0.457;277.5
22(24)
0.353;-453.8
22(28)
0.348;-371.2
22(2Q)
0.330;-288.7
24(23)
0.269;-568.1
(23)(27)
0.336;-371.3
2(23T)
0.324;-444.4
2Q(23)
0.325;-403.1
23(25)
0.307;-547.5
2237
0.251;-641.2
22(3T)
0.329;-444.4
23(2K)
0.317;-382.5
2(246)
0.269;-506.2
28(24)
0.258;-465.0
(24)(2J)
0.341;-268.1
2244
0.283;-547.5
22(47)
0.238;-485.6
24(2T)
0.306;-423.8
224Q
0.227;-517.5
26(25)
0.326;-485.6
(25)(29)
0.344;-288.7
2(25Q)
0.350;-361.9
22(56)
0.373;-485.6
25(29)
0.309;-423.8
225J
0.295;-517.5
26(26)
0.299;-330.0
(26)(29)
0.340;-268.1
2(26Q)
0.362;-341.2
22(67)
0.302;-444.4
26(2T)
0.382;-382.5
226Q
0.327;-476.2
28(27)
0.359;-403.1
(27)(2J)
0.347;-206.3
2277
0.324;-423.8
22(7T)
0.329;-361.9
27(2K)
0.324;-300.0
2(28T)
0.385;-341.2
2Q(28)
0.396;-300.0
28(2T)
0.320;-341.2
228Q
0.282;-435.0
2T(29)
0.277;-320.6
(29)(2K)
0.350;-123.7
229J
0.310;-435.0
2T(2T)
0.338;-165.0
(2T)(2K)
0.322;-103.1
22TQ
0.294;-393.8
2Q(2J)
0.368;-238.1
2J(2K)
0.300;-217.5
22QQ
0.351;-217.5
3(234)
0.321;-547.5
36(23)
0.305;-506.2
(23)(39)
0.308;-309.4
3(23Q)
0.282;-382.5
5(234)
0.306;-641.2
9(234)
0.241;-558.8
K(234)
0.259;-476.2
4(237)
0.273;-600.0
49(23)
0.296;-558.8
(23)(4Q)
0.272;-361.9
(2357)
0.267;-579.4
(235J)
0.270;-496.9
(23)(56)
0.287;-465.0
5(239)
0.254;-538.1
5J(23)
0.313;-496.9
(2367)
0.240;-558.8
(236J)
0.350;-476.2
(23)(67)
0.268;-423.8
6(23T)
0.312;-496.9
6Q(23)
0.333;-455.6
9(237)
0.312;-496.9
K(237)
0.334;-414.4
7(23T)
0.300;-476.2
7Q(23)
0.297;-435.0
T(238)
0.320;-455.6
8(239)
0.345;-476.2
8J(23)
0.343;-435.0
(239T)
0.284;-435.0
99(23)
0.283;-320.6
(23)(9Q)
0.284;-258.8
(23TQ)
0.282;-373.1
T(23Q)
0.332;-373.1
Q(23J)
0.351;-352.5
(23)(JK)
0.280;-196.9
QK(23)
0.281;-311.2
23(35)
0.304;-526.9
33(28)
0.306;-465.0
233T
0.290;-558.8
23(3K)
0.325;-361.9
(24)(36)
0.316;-485.6
3(249)
0.281;-558.8
3J(24)
0.296;-517.5
(34)(25)
0.318;-506.2
27(34)
0.322;-600.0
2(34T)
0.329;-538.1
(34)(2K)
0.285;-341.2
34(26)
0.258;-620.6
34(28)
0.314;-579.4
34(2T)
0.295;-538.1
34(2Q)
0.311;-496.9
(25)(35)
0.398;-350.6
3(258)
0.289;-558.8
3T(25)
0.361;-517.5
(25)(3K)
0.291;-320.6
27(35)
0.290;-579.4
2(35T)
0.287;-517.5
(35)(2K)
0.324;-320.6
35(27)
0.262;-579.4
35(29)
0.315;-538.1
35(2J)
0.312;-496.9
35(2K)
0.272;-455.6
37(26)
0.342;-558.8
(26)(3T)
0.352;-361.9
3(26K)
0.332;-435.0
2(368)
0.331;-538.1
(36)(2J)
0.349;-341.2
2K(36)
0.326;-435.0
23(68)
0.229;-538.1
23(6T)
0.271;-496.9
23(6Q)
0.320;-455.6
3(278)
0.358;-517.5
3T(27)
0.327;-476.2
(27)(3K)
0.397;-279.4
29(37)
0.320;-496.9
2(37Q)
0.309;-435.0
23(78)
0.308;-517.5
23(7T)
0.348;-476.2
23(7Q)
0.336;-435.0
3(289)
0.306;-476.2
3J(28)
0.342;-435.0
(38)(29)
0.402;-341.2
2J(38)
0.281;-435.0
38(29)
0.323;-476.2
38(2J)
0.322;-435.0
38(2K)
0.320;-393.8
3T(29)
0.318;-435.0
(29)(3K)
0.310;-238.1
2J(39)
0.293;-414.4
39(2T)
0.298;-435.0
39(2Q)
0.311;-393.8
(2T)(3T)
0.344;-144.4
3(2TK)
0.287;-352.5
2(3TQ)
0.309;-373.1
23(TJ)
0.361;-393.8
23(TK)
0.397;-352.5
(2J)(3K)
0.317;-196.9
2K(3J)
0.345;-331.9
23(JK)
0.307;-331.9
(3Q)(2K)
0.336;-176.2
(2K)(3K)
0.369;-20.6
4(246)
0.284;-465.0
48(24)
0.339;-423.8
(24)(4J)
0.318;-226.9
5(245)
0.344;-465.0
9(245)
0.278;-517.5
K(245)
0.326;-435.0
5(248)
0.288;-538.1
5T(24)
0.307;-496.9
(24)(5K)
0.375;-300.0
9(246)
0.278;-496.9
K(246)
0.288;-414.4
6(249)
0.310;-496.9
6J(24)
0.333;-455.6
(2478)
0.303;-496.9
(247Q)
0.283;-414.4
7(249)
0.271;-476.2
7J(24)
0.383;-435.0
(2489)
0.280;-455.6
(248K)
0.331;-373.1
8T(24)
0.304;-435.0
(24)(8K)
0.343;-238.1
Q(249)
0.339;-373.1
(24)(9J)
0.309;-258.8
T(24T)
0.336;-258.8
T(24J)
0.317;-373.1
TK(24)
0.256;-331.9
(24)(JQ)
0.364;-196.9
QQ(24)
0.326;-176.2
24(45)
0.294;-485.6
44(28)
0.286;-423.8
244T
0.345;-517.5
24(4K)
0.315;-320.6
(25)(47)
0.287;-423.8
4(25T)
0.309;-496.9
4Q(25)
0.319;-455.6
(45)(27)
0.319;-423.8
29(45)
0.373;-517.5
2(45Q)
0.341;-455.6
24(56)
0.259;-579.4
24(58)
0.258;-538.1
24(5T)
0.292;-496.9
24(5Q)
0.372;-455.6
4(267)
0.253;-538.1
49(26)
0.306;-496.9
(26)(4Q)
0.308;-300.0
27(46)
0.276;-538.1
2(46T)
0.255;-476.2
(46)(2K)
0.390;-279.4
46(28)
0.357;-517.5
46(2T)
0.333;-476.2
46(2Q)
0.308;-435.0
(27)(47)
0.354;-247.5
4(27T)
0.292;-455.6
4Q(27)
0.363;-414.4
(47)(29)
0.334;-341.2
2J(47)
0.352;-435.0
47(28)
0.340;-496.9
47(2T)
0.345;-455.6
47(2Q)
0.281;-414.4
(28)(48)
0.311;-206.3
4(28J)
0.291;-414.4
4K(28)
0.367;-373.1
(48)(2J)
0.349;-279.4
2K(48)
0.368;-373.1
24(8T)
0.280;-435.0
24(8Q)
0.303;-393.8
4(29T)
0.369;-414.4
4Q(29)
0.338;-373.1
(49)(2J)
0.307;-258.8
2K(49)
0.279;-352.5
24(9J)
0.327;-393.8
24(9K)
0.385;-352.5
(2T)(4Q)
0.306;-217.5
2J(4T)
0.319;-373.1
4T(2J)
0.331;-373.1
4T(2K)
0.304;-331.9
4Q(2J)
0.386;-331.9
(4J)(2K)
0.321;-176.2
4J(2K)
0.264;-311.2
4K(2Q)
0.314;-290.6
24(QK)
0.380;-290.6
(25)(56)
0.413;-288.7
5(259)
0.288;-361.9
5J(25)
0.352;-320.6
(2567)
0.350;-517.5
(256J)
0.286;-435.0
(25)(67)
0.248;-382.5
6(25T)
0.320;-455.6
6Q(25)
0.384;-414.4
9(257)
0.265;-455.6
K(257)
0.351;-373.1
7(25T)
0.287;-435.0
7Q(25)
0.257;-393.8
T(258)
0.296;-414.4
8(259)
0.292;-435.0
8J(25)
0.314;-393.8
(259T)
0.317;-393.8
99(25)
0.339;-279.4
(25)(9Q)
0.340;-217.5
(25TQ)
0.345;-331.9
T(25Q)
0.367;-331.9
Q(25J)
0.364;-311.2
(25)(JK)
0.356;-155.6
QK(25)
0.341;-270.0
25(57)
0.349;-403.1
55(2T)
0.337;-341.2
255Q
0.340;-435.0
57(26)
0.359;-517.5
(26)(5T)
0.329;-320.6
5(26K)
0.279;-393.8
2(568)
0.282;-496.9
(56)(2J)
0.386;-300.0
2K(56)
0.306;-393.8
25(68)
0.360;-496.9
25(6T)
0.260;-455.6
25(6Q)
0.294;-414.4
5(278)
0.366;-476.2
5T(27)
0.290;-435.0
(27)(5K)
0.375;-238.1
29(57)
0.275;-455.6
2(57Q)
0.333;-393.8
25(78)
0.284;-476.2
25(7T)
0.313;-435.0
25(7Q)
0.329;-393.8
5(289)
0.373;-435.0
5J(28)
0.299;-393.8
(58)(29)
0.302;-300.0
2J(58)
0.341;-393.8
58(29)
0.330;-435.0
58(2J)
0.315;-393.8
58(2K)
0.354;-352.5
5T(29)
0.304;-393.8
(29)(5K)
0.339;-196.9
2J(59)
0.288;-373.1
59(2T)
0.330;-393.8
59(2Q)
0.359;-352.5
(2T)(5T)
0.355;-103.1
5(2TK)
0.282;-311.2
2(5TQ)
0.382;-331.9
25(TJ)
0.315;-352.5
25(TK)
0.279;-311.2
(2J)(5K)
0.325;-155.6
2K(5J)
0.284;-290.6
25(JK)
0.378;-290.6
(5Q)(2K)
0.289;-135.0
(2K)(5K)
0.369;20.6
6(268)
0.366;-341.2
6T(26)
0.365;-300.0
(26)(6K)
0.338;-103.1
T(267)
0.318;-414.4
7(268)
0.345;-455.6
7T(26)
0.246;-414.4
(26)(7K)
0.360;-217.5
J(268)
0.320;-373.1
89(26)
0.336;-414.4
(26)(8Q)
0.330;-217.5
(269J)
0.353;-352.5
(26)(9T)
0.329;-238.1
9(26K)
0.279;-311.2
(26TK)
0.291;-290.6
TQ(26)
0.328;-311.2
K(26J)
0.347;-270.0
Q(26Q)
0.343;-135.0
KK(26)
0.358;-93.7
66(29)
0.338;-320.6
266J
0.255;-414.4
67(27)
0.343;-341.2
(27)(6T)
0.334;-279.4
6(27K)
0.340;-352.5
2(679)
0.306;-435.0
(67)(2Q)
0.366;-238.1
27(68)
0.347;-455.6
27(6T)
0.277;-414.4
27(6Q)
0.253;-373.1
68(28)
0.331;-300.0
(28)(6J)
0.317;-238.1
28(68)
0.313;-300.0
2(68J)
0.345;-373.1
2688
0.279;-435.0
268T
0.258;-528.7
268Q
0.281;-487.5
(29)(6T)
0.386;-238.1
6(29K)
0.342;-311.2
2(69J)
0.321;-352.5
2699
0.349;-393.8
269J
0.246;-487.5
269K
0.286;-446.2
6Q(2T)
0.348;-311.2
(6T)(2Q)
0.334;-176.2
2T(6J)
0.318;-331.9
2T(6K)
0.340;-290.6
6(2JK)
0.364;-270.0
2(6JK)
0.363;-270.0
2J(6K)
0.358;-270.0
2Q(6Q)
0.294;-135.0
26QK
0.273;-384.4
78(27)
0.335;-300.0
(27)(7J)
0.397;-103.1
8(278)
0.367;-279.4
Q(278)
0.296;-331.9
(27)(8T)
0.340;-238.1
8(27K)
0.345;-311.2
(279Q)
0.353;-311.2
9(27J)
0.273;-331.9
9K(27)
0.338;-290.6
TT(27)
0.325;-196.9
(27)(TK)
0.354;-135.0
J(27Q)
0.299;-270.0
K(27Q)
0.322;-228.7
77(28)
0.354;-300.0
277T
0.305;-393.8
27(7K)
0.327;-196.9
(28)(7T)
0.360;-238.1
7(28K)
0.322;-311.2
2(78T)
0.366;-373.1
(78)(2K)
0.367;-176.2
78(2T)
0.331;-373.1
78(2Q)
0.305;-331.9
(29)(79)
0.349;-103.1
7(29Q)
0.327;-311.2
2(79T)
0.291;-352.5
(79)(2K)
0.332;-155.6
79(2J)
0.311;-331.9
79(2K)
0.335;-290.6
7J(2T)
0.299;-311.2
(7T)(2J)
0.348;-176.2
2K(7T)
0.288;-270.0
27(TQ)
0.281;-290.6
7(2JQ)
0.346;-270.0
2(7JQ)
0.363;-270.0
27(JQ)
0.353;-270.0
7(2QK)
0.346;-228.7
7Q(2K)
0.357;-228.7
88(28)
0.356;-123.7
(28)(8J)
0.384;-61.9
9(289)
0.370;-217.5
K(289)
0.330;-270.0
9(28Q)
0.397;-290.6
J(28T)
0.348;-290.6
TJ(28)
0.326;-290.6
(28JQ)
0.342;-249.4
J(28K)
0.399;-228.7
(28)(QK)
0.342;-73.1
88(2T)
0.340;-217.5
288Q
0.341;-311.2
8T(29)
0.274;-331.9
(29)(8K)
0.296;-135.0
2J(89)
0.316;-311.2
89(2T)
0.284;-331.9
89(2Q)
0.317;-290.6
(2T)(8T)
0.350;-41.3
8(2TK)
0.384;-249.4
2(8TQ)
0.311;-270.0
28(TJ)
0.320;-290.6
28(TK)
0.361;-249.4
(2J)(8K)
0.364;-93.8
2K(8J)
0.355;-228.7
28(JK)
0.358;-228.7
(8Q)(2K)
0.371;-73.1
(2K)(8K)
0.376;82.5
9(29J)
0.349;-155.6
9K(29)
0.295;-114.4
TT(29)
0.357;-155.6
(29)(TK)
0.316;-93.8
J(29Q)
0.311;-228.7
K(29Q)
0.337;-187.5
99(2T)
0.390;-176.2
299Q
0.327;-270.0
9J(2T)
0.409;-270.0
(9T)(2J)
0.374;-135.0
2K(9T)
0.340;-228.7
29(TQ)
0.376;-249.4
9(2JQ)
0.328;-228.7
2(9JQ)
0.330;-228.7
29(JQ)
0.303;-228.7
9(2QK)
0.306;-187.5
9Q(2K)
0.312;-187.5
TT(2T)
0.365;0.0
(2T)(TK)
0.364;61.9
J(2TQ)
0.380;-208.1
K(2TQ)
0.322;-166.9
TT(2J)
0.337;-114.4
2TTK
0.312;-208.1
TK(2J)
0.376;-187.5
2TJJ
0.326;-228.7
2TJK
0.289;-322.5
2(TQK)
0.308;-166.9
TK(2K)
0.391;-11.2
(2J)(JK)
0.379;103.1
QK(2J)
0.355;-146.2
2J(JK)
0.361;-31.9
(JQ)(2K)
0.383;-11.2
(2K)(JK)
0.359;144.4
K(2QK)
0.372;30.0
2K(QK)
0.366;30.0
3335
0.309;-506.2
3339
0.328;-423.8
333K
0.261;-341.2
36(34)
0.337;-465.0
(34)(39)
0.348;-268.1
3(34Q)
0.301;-341.2
33(45)
0.277;-485.6
34(38)
0.352;-423.8
334T
0.259;-517.5
33(4K)
0.345;-320.6
(35)(37)
0.310;-288.7
3(35T)
0.298;-361.9
3Q(35)
0.320;-320.6
35(37)
0.311;-423.8
3359
0.264;-517.5
33(5Q)
0.312;-320.6
(36)(37)
0.333;-268.1
3(36T)
0.380;-341.2
3Q(36)
0.316;-300.0
36(38)
0.375;-382.5
336T
0.347;-476.2
33(6K)
0.375;-279.4
(37)(39)
0.348;-206.3
3(37Q)
0.334;-279.4
33(78)
0.380;-361.9
37(3J)
0.319;-300.0
337K
0.350;-393.8
3T(38)
0.333;-300.0
(38)(3K)
0.352;-103.1
338T
0.330;-435.0
33(8K)
0.323;-238.1
(39)(3J)
0.300;-123.7
3399
0.332;-300.0
33(9Q)
0.364;-238.1
(3T)(3J)
0.340;-103.1
33TT
0.278;-258.8
33(TK)
0.408;-196.9
(3J)(3K)
0.400;-41.3
33JK
0.333;-311.2
33(QK)
0.399;-155.6
45(34)
0.282;-465.0
(34)(48)
0.383;-268.1
4(34J)
0.271;-341.2
4K(34)
0.282;-300.0
(3459)
0.277;-496.9
(345K)
0.273;-414.4
57(34)
0.281;-538.1
(34)(5T)
0.283;-341.2
5(34K)
0.284;-414.4
(3469)
0.300;-476.2
(346K)
0.321;-393.8
68(34)
0.320;-496.9
(34)(6J)
0.402;-300.0
7(347)
0.269;-361.9
J(347)
0.300;-414.4
78(34)
0.298;-476.2
(34)(7J)
0.338;-279.4
8(348)
0.270;-320.6
Q(348)
0.361;-373.1
(34)(8T)
0.305;-279.4
8(34K)
0.360;-352.5
(349Q)
0.278;-352.5
9(34J)
0.247;-373.1
9K(34)
0.375;-331.9
TT(34)
0.425;-238.1
(34)(TK)
0.370;-176.2
J(34Q)
0.313;-311.2
K(34Q)
0.370;-270.0
44(35)
0.351;-465.0
3447
0.324;-558.8
34(4T)
0.325;-361.9
44(3K)
0.332;-300.0
4(357)
0.264;-538.1
49(35)
0.282;-496.9
(35)(4Q)
0.358;-300.0
36(45)
0.265;-558.8
3(459)
0.340;-496.9
(45)(3Q)
0.383;-300.0
35(46)
0.266;-558.8
35(48)
0.329;-517.5
35(4T)
0.247;-476.2
35(4Q)
0.325;-435.0
46(36)
0.267;-403.1
(36)(49)
0.360;-341.2
4(36Q)
0.350;-414.4
3(467)
0.318;-517.5
(46)(3T)
0.361;-320.6
3Q(46)
0.375;-414.4
3467
0.313;-652.5
3469
0.236;-611.2
346J
0.276;-570.0
346K
0.293;-528.7
49(37)
0.319;-455.6
(37)(4Q)
0.348;-258.8
38(47)
0.316;-476.2
3(47J)
0.326;-414.4
3477
0.312;-496.9
3479
0.303;-590.6
347J
0.309;-549.4
347K
0.375;-508.1
4T(38)
0.320;-414.4
(38)(4K)
0.384;-217.5
3T(48)
0.261;-414.4
3(48K)
0.358;-352.5
38(4T)
0.269;-414.4
38(4Q)
0.348;-373.1
49(39)
0.342;-279.4
(39)(4Q)
0.341;-217.5
3T(49)
0.328;-393.8
3(49K)
0.313;-331.9
39(4J)
0.294;-373.1
39(4K)
0.280;-331.9
4(3TQ)
0.289;-331.9
3(4TJ)
0.371;-352.5
34TT
0.322;-373.1
34TQ
0.304;-466.9
(3J)(4Q)
0.318;-176.2
3Q(4J)
0.376;-311.2
34JQ
0.293;-446.2
(3Q)(4K)
0.404;-135.0
3Q(4K)
0.338;-270.0
5(356)
0.330;-403.1
58(35)
0.392;-361.9
(35)(5J)
0.406;-165.0
6(356)
0.310;-382.5
T(356)
0.285;-435.0
6(357)
0.311;-496.9
69(35)
0.348;-455.6
(35)(6Q)
0.334;-258.8
(3579)
0.282;-435.0
(357K)
0.367;-352.5
79(35)
0.313;-435.0
(35)(7Q)
0.380;-238.1
(358T)
0.336;-393.8
88(35)
0.392;-300.0
(35)(8J)
0.355;-238.1
9(359)
0.311;-258.8
K(359)
0.264;-311.2
9(35Q)
0.277;-331.9
J(35T)
0.349;-331.9
TJ(35)
0.321;-331.9
(35JQ)
0.347;-290.6
J(35K)
0.370;-270.0
(35)(QK)
0.343;-114.4
55(37)
0.394;-382.5
3559
0.275;-476.2
35(5Q)
0.308;-279.4
(36)(57)
0.308;-361.9
5(36T)
0.254;-435.0
5Q(36)
0.285;-393.8
(56)(38)
0.310;-341.2
3T(56)
0.293;-435.0
3(56K)
0.296;-373.1
36(58)
0.274;-476.2
36(5T)
0.325;-435.0
36(5Q)
0.329;-393.8
57(37)
0.299;-341.2
(37)(5T)
0.364;-279.4
5(37K)
0.292;-352.5
3(579)
0.290;-435.0
(57)(3Q)
0.342;-238.1
37(58)
0.287;-455.6
37(5T)
0.284;-414.4
37(5Q)
0.279;-373.1
58(38)
0.324;-300.0
(38)(5J)
0.340;-238.1
38(58)
0.301;-300.0
3(58J)
0.307;-373.1
3588
0.296;-435.0
358T
0.321;-528.7
358Q
0.274;-487.5
(39)(5T)
0.310;-238.1
5(39K)
0.361;-311.2
3(59J)
0.382;-352.5
3599
0.334;-393.8
359J
0.262;-487.5
359K
0.254;-446.2
5Q(3T)
0.393;-311.2
(5T)(3Q)
0.380;-176.2
3T(5J)
0.314;-331.9
3T(5K)
0.340;-290.6
5(3JK)
0.388;-270.0
3(5JK)
0.325;-270.0
3J(5K)
0.362;-270.0
3Q(5Q)
0.313;-135.0
35QK
0.324;-384.4
67(36)
0.368;-341.2
(36)(6T)
0.310;-144.4
6(36K)
0.276;-217.5
(367T)
0.295;-393.8
77(36)
0.330;-320.6
(36)(7T)
0.289;-258.8
7(36K)
0.399;-331.9
(368J)
0.257;-352.5
(36)(89)
0.299;-258.8
8(36Q)
0.367;-331.9
T(369)
0.329;-352.5
9(36T)
0.356;-352.5
9Q(36)
0.321;-311.2
Q(36T)
0.359;-290.6
(36)(TQ)
0.420;-155.6
(36JK)
0.308;-249.4
JK(36)
0.295;-249.4
K(36K)
0.355;-73.1
3668
0.312;-455.6
36(6J)
0.387;-258.8
(37)(67)
0.421;-185.6
6(37T)
0.301;-393.8
6Q(37)
0.319;-352.5
(67)(39)
0.311;-279.4
3J(67)
0.350;-373.1
67(38)
0.305;-435.0
67(3T)
0.301;-393.8
67(3Q)
0.259;-352.5
(38)(68)
0.324;-144.4
6(38J)
0.300;-352.5
6K(38)
0.334;-311.2
(68)(3J)
0.328;-217.5
3K(68)
0.304;-311.2
36(8T)
0.311;-373.1
36(8Q)
0.292;-331.9
6(39T)
0.291;-352.5
6Q(39)
0.290;-311.2
(69)(3J)
0.362;-196.9
3K(69)
0.262;-290.6
36(9J)
0.276;-331.9
36(9K)
0.305;-290.6
(3T)(6Q)
0.362;-155.6
3J(6T)
0.290;-311.2
6T(3J)
0.363;-311.2
6T(3K)
0.390;-270.0
6Q(3J)
0.381;-270.0
(6J)(3K)
0.375;-114.4
6J(3K)
0.287;-249.4
6K(3Q)
0.311;-228.7
36(QK)
0.346;-228.7
(37)(78)
0.376;-144.4
7(37J)
0.297;-217.5
7K(37)
0.340;-176.2
(378Q)
0.287;-311.2
8(37T)
0.307;-352.5
8Q(37)
0.337;-311.2
J(379)
0.281;-311.2
9T(37)
0.276;-331.9
(37)(9K)
0.374;-135.0
K(37T)
0.290;-249.4
T(37K)
0.346;-249.4
JJ(37)
0.338;-135.0
(37QK)
0.345;-208.1
3777
0.333;-300.0
37(7T)
0.338;-238.1
77(3K)
0.357;-176.2
7(38T)
0.329;-352.5
7Q(38)
0.321;-311.2
(78)(3T)
0.358;-217.5
3Q(78)
0.313;-311.2
3789
0.321;-508.1
378J
0.353;-466.9
378K
0.338;-425.6
7J(39)
0.315;-311.2
(79)(3T)
0.364;-196.9
3Q(79)
0.291;-290.6
379T
0.344;-466.9
379Q
0.377;-425.6
(3T)(7J)
0.313;-155.6
3T(7T)
0.337;-176.2
3(7TK)
0.326;-249.4
3T(7Q)
0.276;-270.0
7J(3J)
0.333;-135.0
(7J)(3Q)
0.381;-114.4
3J(7Q)
0.287;-249.4
7Q(3Q)
0.351;-93.7
37QQ
0.413;-228.7
37KK
0.352;-187.5
8(38J)
0.399;-176.2
8K(38)
0.405;-135.0
(389K)
0.382;-249.4
9J(38)
0.284;-290.6
(38TJ)
0.321;-270.0
(38)(TJ)
0.387;-135.0
J(38J)
0.384;-114.4
JQ(38)
0.393;-228.7
Q(38K)
0.374;-187.5
3889
0.281;-352.5
38(8Q)
0.339;-155.6
(39)(8T)
0.391;-176.2
8(39K)
0.408;-249.4
3(89J)
0.280;-290.6
3899
0.315;-331.9
389J
0.267;-425.6
389K
0.343;-384.4
8Q(3T)
0.343;-249.4
(8T)(3Q)
0.275;-114.4
3T(8J)
0.271;-270.0
3T(8K)
0.275;-228.7
8(3JK)
0.304;-208.1
3(8JK)
0.312;-208.1
3J(8K)
0.330;-208.1
3Q(8Q)
0.383;-73.1
38QK
0.324;-322.5
9T(39)
0.341;-155.6
(39)(9K)
0.351;41.3
K(39T)
0.401;-208.1
T(39K)
0.279;-208.1
JJ(39)
0.347;-93.7
(39QK)
0.371;-166.9
3999
0.279;-176.2
39(9Q)
0.347;-114.4
(3T)(9J)
0.372;-114.4
3T(9T)
0.393;-135.0
3(9TK)
0.313;-208.1
3T(9Q)
0.334;-228.7
9J(3J)
0.344;-93.7
(9J)(3Q)
0.331;-73.1
3J(9Q)
0.341;-208.1
9Q(3Q)
0.331;-52.5
39QQ
0.332;-187.5
39KK
0.364;-146.2
T(3TK)
0.306;-52.5
JJ(3T)
0.362;-73.1
(3TQK)
0.354;-146.2
3TTT
0.280;-114.4
3T(TK)
0.356;-52.5
(3J)(TK)
0.418;-31.9
3K(TJ)
0.284;-166.9
3T(JK)
0.355;-166.9
(TQ)(3K)
0.340;-11.2
(3K)(TK)
0.366;144.4
J(3JK)
0.329;-11.2
(3J)(QK)
0.401;9.4
JJ(3K)
0.385;-11.2
3Q(JQ)
0.335;-11.2
3JQK
0.276;-260.6
QK(3Q)
0.324;30.0
QK(3K)
0.404;50.6
44(46)
0.358;-288.7
44(4T)
0.409;-206.2
(45)(45)
0.355;-153.8
4(458)
0.292;-361.9
4T(45)
0.277;-320.6
(45)(4K)
0.379;-123.7
4457
0.309;-517.5
44(5T)
0.292;-320.6
45(4K)
0.308;-258.8
4(468)
0.351;-341.2
4T(46)
0.296;-300.0
(46)(4K)
0.353;-103.1
4468
0.268;-476.2
44(6J)
0.259;-279.4
(47)(47)
0.370;-71.2
4(47T)
0.342;-279.4
4Q(47)
0.328;-238.1
47(49)
0.372;-300.0
447J
0.291;-393.8
48(48)
0.331;-165.0
(48)(4J)
0.357;-103.1
4488
0.345;-300.0
44(8J)
0.390;-238.1
(49)(49)
0.396;11.2
4(49Q)
0.306;-196.9
44(9T)
0.299;-238.1
49(4K)
0.394;-176.2
4(4TQ)
0.337;-176.2
44(TJ)
0.370;-196.9
(4J)(4J)
0.348;93.8
44JJ
0.411;-176.2
4Q(4Q)
0.321;0.0
(4K)(4K)
0.322;176.2
(45)(57)
0.305;-226.9
5(45T)
0.296;-300.0
5Q(45)
0.362;-258.8
8(456)
0.333;-455.6
Q(456)
0.270;-373.1
(45)(68)
0.317;-320.6
6(45J)
0.362;-393.8
6K(45)
0.317;-352.5
(457J)
0.376;-373.1
(45)(78)
0.296;-300.0
7(45J)
0.347;-373.1
7K(45)
0.304;-331.9
(458Q)
0.337;-331.9
8(45T)
0.293;-373.1
8Q(45)
0.281;-331.9
J(459)
0.337;-331.9
9T(45)
0.285;-352.5
(45)(9K)
0.367;-155.6
K(45T)
0.267;-270.0
T(45K)
0.385;-270.0
JJ(45)
0.313;-155.6
(45QK)
0.262;-228.7
4555
0.311;-403.1
45(58)
0.347;-341.2
55(4J)
0.305;-279.4
455K
0.382;-373.1
58(46)
0.305;-455.6
(46)(5J)
0.346;-258.8
46(56)
0.272;-361.9
4(569)
0.259;-435.0
(56)(4Q)
0.356;-238.1
46(57)
0.265;-476.2
46(59)
0.301;-435.0
46(5J)
0.285;-393.8
46(5K)
0.383;-352.5
5(479)
0.294;-414.4
5J(47)
0.295;-373.1
(57)(48)
0.404;-300.0
4T(57)
0.369;-393.8
4(57K)
0.324;-331.9
47(59)
0.339;-414.4
47(5J)
0.285;-373.1
47(5K)
0.392;-331.9
5(48T)
0.286;-373.1
5Q(48)
0.398;-331.9
(58)(4T)
0.319;-238.1
4Q(58)
0.342;-331.9
4589
0.324;-528.7
458J
0.287;-487.5
458K
0.313;-446.2
5J(49)
0.291;-331.9
(59)(4T)
0.413;-217.5
4Q(59)
0.256;-311.2
459T
0.275;-487.5
459Q
0.241;-446.2
(4T)(5J)
0.353;-176.2
4T(5T)
0.392;-196.9
4(5TK)
0.312;-270.0
4T(5Q)
0.407;-290.6
5J(4J)
0.350;-155.6
(5J)(4Q)
0.398;-135.0
4J(5Q)
0.328;-270.0
5Q(4Q)
0.314;-114.4
45QQ
0.357;-249.4
45KK
0.332;-208.1
6(469)
0.364;-279.4
6J(46)
0.301;-238.1
(4678)
0.321;-414.4
(467Q)
0.307;-331.9
7(469)
0.344;-393.8
7J(46)
0.335;-352.5
(4689)
0.341;-373.1
(468K)
0.300;-290.6
8T(46)
0.297;-352.5
(46)(8K)
0.388;-155.6
Q(469)
0.327;-290.6
(46)(9J)
0.365;-176.2
T(46T)
0.395;-176.2
T(46J)
0.344;-290.6
TK(46)
0.328;-249.4
(46)(JQ)
0.345;-114.4
QQ(46)
0.344;-93.7
46(67)
0.305;-320.6
66(4T)
0.278;-258.8
466Q
0.313;-352.5
68(47)
0.296;-414.4
(47)(6J)
0.398;-217.5
47(67)
0.385;-300.0
4(67T)
0.327;-373.1
(67)(4K)
0.385;-176.2
67(49)
0.336;-393.8
67(4J)
0.373;-352.5
67(4K)
0.325;-311.2
69(48)
0.353;-373.1
(48)(6Q)
0.371;-176.2
49(68)
0.321;-373.1
4(68Q)
0.347;-311.2
46(89)
0.335;-373.1
46(8J)
0.298;-331.9
46(8K)
0.347;-290.6
(49)(6J)
0.287;-176.2
49(69)
0.358;-217.5
4(69Q)
0.293;-290.6
46(9T)
0.361;-331.9
46(9Q)
0.292;-290.6
6(4TJ)
0.369;-290.6
6K(4T)
0.370;-249.4
(6T)(4K)
0.392;-114.4
6T(4Q)
0.277;-270.0
(4J)(6J)
0.420;0.0
4J(6J)
0.302;-135.0
6J(4Q)
0.338;-249.4
(4Q)(6Q)
0.349;41.3
4K(6Q)
0.344;-208.1
4K(6K)
0.388;-52.5
79(47)
0.327;-238.1
(47)(7Q)
0.375;-41.3
(478T)
0.275;-331.9
88(47)
0.408;-238.1
(47)(8J)
0.320;-176.2
9(479)
0.296;-196.9
K(479)
0.383;-249.4
9(47Q)
0.364;-270.0
J(47T)
0.320;-270.0
TJ(47)
0.356;-270.0
(47JQ)
0.324;-228.7
J(47K)
0.407;-208.1
(47)(QK)
0.293;-52.5
77(49)
0.403;-238.1
477J
0.340;-331.9
78(48)
0.326;-238.1
(48)(7J)
0.339;-176.2
48(78)
0.379;-238.1
4(78J)
0.395;-311.2
4788
0.315;-373.1
478T
0.245;-466.9
478Q
0.344;-425.6
(49)(7T)
0.304;-176.2
7(49K)
0.338;-249.4
4(79J)
0.351;-290.6
4799
0.360;-331.9
479J
0.278;-425.6
479K
0.283;-384.4
7Q(4T)
0.332;-249.4
(7T)(4Q)
0.394;-114.4
4T(7J)
0.298;-270.0
4T(7K)
0.345;-228.7
7(4JK)
0.366;-208.1
4(7JK)
0.302;-208.1
4J(7K)
0.346;-208.1
4Q(7Q)
0.350;-73.1
47QK
0.306;-322.5
89(48)
0.307;-196.9
(48)(8Q)
0.369;0.0
(489J)
0.369;-270.0
(48)(9T)
0.387;-155.6
9(48K)
0.329;-228.7
(48TK)
0.300;-208.1
TQ(48)
0.321;-228.7
K(48J)
0.327;-187.5
Q(48Q)
0.355;-52.5
KK(48)
0.405;-11.2
88(4J)
0.393;-155.6
488K
0.388;-249.4
8J(49)
0.391;-270.0
(89)(4T)
0.341;-155.6
4Q(89)
0.399;-249.4
489T
0.268;-425.6
489Q
0.356;-384.4
(4T)(8J)
0.349;-114.4
4T(8T)
0.338;-135.0
4(8TK)
0.370;-208.1
4T(8Q)
0.282;-228.7
8J(4J)
0.363;-93.7
(8J)(4Q)
0.361;-73.1
4J(8Q)
0.344;-208.1
8Q(4Q)
0.397;-52.5
48QQ
0.359;-187.5
48KK
0.376;-146.2
9(49Q)
0.400;-93.7
J(49T)
0.369;-228.7
TJ(49)
0.368;-228.7
(49JQ)
0.352;-187.5
J(49K)
0.387;-166.9
(49)(QK)
0.400;-11.2
99(4J)
0.377;-114.4
499K
0.355;-208.1
9Q(4T)
0.400;-208.1
(9T)(4Q)
0.372;-73.1
4T(9J)
0.349;-228.7
4T(9K)
0.377;-187.5
9(4JK)
0.312;-166.9
4(9JK)
0.394;-166.9
4J(9K)
0.348;-166.9
4Q(9Q)
0.365;-31.9
49QK
0.295;-281.2
TJ(4T)
0.405;-73.1
(4TJQ)
0.322;-166.9
J(4TK)
0.353;-146.2
(4T)(QK)
0.422;9.4
TT(4Q)
0.300;-52.5
T(4JQ)
0.403;-166.9
4(TJQ)
0.387;-166.9
4T(JQ)
0.356;-166.9
T(4QK)
0.390;-125.6
TQ(4K)
0.336;-125.6
JJ(4J)
0.343;103.1
(4JQK)
0.350;-105.0
4JJJ
0.384;-31.9
JQ(4Q)
0.400;9.4
4JQQ
0.335;-125.6
4JKK
0.415;-84.4
QQ(4K)
0.422;50.6
4KKK
0.389;91.9
55(59)
0.345;-165.0
55(5K)
0.291;-82.5
(56)(58)
0.313;-165.0
5(56J)
0.291;-238.1
5K(56)
0.332;-196.9
56(59)
0.301;-279.4
556J
0.279;-373.1
57(57)
0.371;-165.0
(57)(5T)
0.415;-103.1
5(57K)
0.418;-176.2
55(79)
0.315;-258.8
57(5Q)
0.332;-196.9
5(589)
0.325;-238.1
5J(58)
0.362;-196.9
58(59)
0.324;-238.1
558J
0.353;-331.9
59(59)
0.383;-82.5
(59)(5Q)
0.327;-20.6
559T
0.261;-331.9
55(9K)
0.303;-135.0
(5T)(5Q)
0.433;0.0
55TJ
0.339;-290.6
5J(5J)
0.359;0.0
5J(5Q)
0.360;-114.4
5(5QK)
0.327;-73.1
5K(5K)
0.356;82.5
68(56)
0.303;-279.4
(56)(6J)
0.420;-82.5
7(567)
0.339;-279.4
J(567)
0.373;-331.9
78(56)
0.345;-393.8
(56)(7J)
0.369;-196.9
8(568)
0.378;-238.1
Q(568)
0.312;-290.6
(56)(8T)
0.351;-196.9
8(56K)
0.287;-270.0
(569Q)
0.288;-270.0
9(56J)
0.362;-290.6
9K(56)
0.342;-249.4
TT(56)
0.360;-155.6
(56)(TK)
0.346;-93.8
J(56Q)
0.340;-228.7
K(56Q)
0.364;-187.5
66(57)
0.314;-300.0
5669
0.307;-393.8
56(6Q)
0.285;-196.9
(57)(68)
0.372;-258.8
6(57J)
0.292;-331.9
6K(57)
0.345;-290.6
(67)(5T)
0.297;-217.5
5Q(67)
0.372;-311.2
5678
0.294;-528.7
567T
0.259;-487.5
567Q
0.389;-446.2
(58)(69)
0.404;-217.5
6(58Q)
0.338;-290.6
5(689)
0.283;-352.5
(68)(5Q)
0.303;-155.6
58(69)
0.365;-352.5
58(6J)
0.321;-311.2
58(6K)
0.277;-270.0
6(59J)
0.323;-290.6
6K(59)
0.343;-249.4
(69)(5Q)
0.352;-135.0
59(6T)
0.332;-311.2
59(6Q)
0.263;-270.0
6T(5T)
0.276;-155.6
(5T)(6K)
0.438;-93.8
5Q(6T)
0.339;-249.4
56TJ
0.272;-405.0
56TK
0.269;-363.7
6K(5J)
0.295;-208.1
56JJ
0.336;-249.4
56JK
0.332;-343.1
5(6QK)
0.347;-187.5
6K(5K)
0.401;-31.9
(57)(79)
0.334;-82.5
7(57Q)
0.379;-155.6
9(578)
0.371;-331.9
K(578)
0.379;-249.4
8(57J)
0.345;-290.6
8K(57)
0.413;-249.4
(579K)
0.299;-228.7
9J(57)
0.318;-270.0
(57TJ)
0.327;-249.4
(57)(TJ)
0.382;-114.4
J(57J)
0.329;-93.7
JQ(57)
0.339;-208.1
Q(57K)
0.297;-166.9
5778
0.258;-373.1
57(7J)
0.394;-176.2
(58)(78)
0.388;-82.5
7(58J)
0.331;-290.6
7K(58)
0.301;-249.4
(78)(5J)
0.413;-155.6
5K(78)
0.283;-249.4
57(8T)
0.270;-311.2
57(8Q)
0.300;-270.0
7(59T)
0.327;-290.6
7Q(59)
0.291;-249.4
(79)(5J)
0.284;-135.0
5K(79)
0.343;-228.7
57(9J)
0.320;-270.0
57(9K)
0.310;-228.7
(5T)(7Q)
0.441;-93.8
5J(7T)
0.306;-249.4
7T(5J)
0.321;-249.4
7T(5K)
0.317;-208.1
7Q(5J)
0.367;-208.1
(7J)(5K)
0.402;-52.5
7J(5K)
0.413;-187.5
7K(5Q)
0.367;-166.9
57(QK)
0.380;-166.9
(58)(89)
0.333;-41.3
8(58Q)
0.282;-114.4
T(589)
0.348;-270.0
9(58T)
0.320;-270.0
9Q(58)
0.349;-228.7
Q(58T)
0.377;-208.1
(58)(TQ)
0.344;-73.1
(58JK)
0.331;-166.9
JK(58)
0.321;-166.9
K(58K)
0.349;9.4
588T
0.291;-290.6
58(8K)
0.348;-93.7
(59)(8J)
0.399;-114.4
59(89)
0.348;-155.6
5(89Q)
0.363;-228.7
58(9T)
0.381;-270.0
58(9Q)
0.320;-228.7
8(5TJ)
0.356;-228.7
8K(5T)
0.354;-187.5
(8T)(5K)
0.393;-52.5
8T(5Q)
0.310;-208.1
(5J)(8J)
0.405;61.9
5J(8J)
0.338;-73.1
8J(5Q)
0.346;-187.5
(5Q)(8Q)
0.342;103.1
5K(8Q)
0.361;-146.2
5K(8K)
0.340;9.4
9J(59)
0.358;-93.7
(59TJ)
0.386;-208.1
(59)(TJ)
0.425;-73.1
J(59J)
0.402;-52.5
JQ(59)
0.417;-166.9
Q(59K)
0.338;-125.6
599T
0.321;-249.4
59(9K)
0.339;-52.5
(5T)(9Q)
0.363;-52.5
5J(9T)
0.391;-208.1
9T(5J)
0.362;-208.1
9T(5K)
0.355;-166.9
9Q(5J)
0.327;-166.9
(9J)(5K)
0.349;-11.2
9J(5K)
0.405;-146.2
9K(5Q)
0.338;-125.6
59(QK)
0.326;-125.6
(5T)(TJ)
0.413;82.5
J(5TJ)
0.323;-31.9
JQ(5T)
0.343;-146.2
Q(5TK)
0.374;-105.0
5TTJ
0.382;-187.5
TJ(5J)
0.305;-31.9
(TJ)(5Q)
0.361;-11.2
5J(TQ)
0.359;-146.2
TQ(5Q)
0.373;9.4
5TQQ
0.407;-125.6
5TKK
0.327;-84.4
Q(5JQ)
0.378;30.0
KK(5J)
0.400;71.3
(5Q)(JQ)
0.356;165.0
5K(JQ)
0.369;-84.4
5K(JK)
0.337;71.3
5QQQ
0.350;50.6
KK(5K)
0.380;247.5
6669
0.333;-238.1
666K
0.379;-155.6
69(67)
0.342;-217.5
(67)(6Q)
0.347;-20.6
6678
0.391;-373.1
66(7J)
0.334;-176.2
(68)(68)
0.385;52.5
6(68J)
0.350;-155.6
6K(68)
0.318;-114.4
68(6J)
0.396;-155.6
668K
0.365;-249.4
6J(69)
0.389;-135.0
69(6T)
0.417;-155.6
669Q
0.288;-249.4
6J(6T)
0.372;-114.4
6T(6J)
0.393;-114.4
66TK
0.342;-208.1
6K(6J)
0.352;-52.5
(6Q)(6Q)
0.365;217.5
66QK
0.392;-166.9
7(679)
0.322;-196.9
7J(67)
0.342;-155.6
(6789)
0.275;-311.2
(678K)
0.327;-228.7
8T(67)
0.336;-290.6
(67)(8K)
0.293;-93.8
Q(679)
0.375;-228.7
(67)(9J)
0.383;-114.4
T(67T)
0.308;-114.4
T(67J)
0.366;-228.7
TK(67)
0.312;-187.5
(67)(JQ)
0.393;-52.5
QQ(67)
0.324;-31.9
67(78)
0.377;-217.5
77(6J)
0.377;-155.6
677K
0.368;-249.4
7T(68)
0.289;-290.6
(68)(7K)
0.288;-93.8
6T(78)
0.277;-290.6
6(78K)
0.368;-228.7
68(7T)
0.309;-290.6
68(7Q)
0.343;-249.4
79(69)
0.288;-155.6
(69)(7Q)
0.313;-93.8
6T(79)
0.303;-270.0
6(79K)
0.348;-208.1
69(7J)
0.384;-249.4
69(7K)
0.356;-208.1
7(6TQ)
0.343;-208.1
6(7TJ)
0.314;-228.7
67TT
0.293;-249.4
67TQ
0.296;-343.1
(6J)(7Q)
0.335;-52.5
6Q(7J)
0.362;-187.5
67JQ
0.280;-322.5
(6Q)(7K)
0.323;-11.2
6Q(7K)
0.414;-146.2
8(689)
0.333;-155.6
8J(68)
0.327;-114.4
(689T)
0.307;-249.4
99(68)
0.357;-135.0
(68)(9Q)
0.379;-73.1
(68TQ)
0.380;-187.5
T(68Q)
0.313;-187.5
Q(68J)
0.326;-166.9
(68)(JK)
0.324;-11.2
QK(68)
0.332;-125.6
68(8T)
0.369;-135.0
88(6K)
0.368;-73.1
8(69J)
0.365;-228.7
8K(69)
0.380;-187.5
(89)(6Q)
0.402;-73.1
69(8T)
0.365;-249.4
69(8Q)
0.316;-208.1
8T(6T)
0.426;-93.7
(6T)(8K)
0.363;-31.9
6Q(8T)
0.363;-187.5
68TJ
0.355;-343.1
68TK
0.345;-301.9
8K(6J)
0.365;-146.2
68JJ
0.323;-187.5
68JK
0.389;-281.2
6(8QK)
0.320;-125.6
8K(6K)
0.375;30.0
(69)(9J)
0.362;61.9
T(69T)
0.364;-73.1
T(69J)
0.329;-187.5
TK(69)
0.351;-146.2
(69)(JQ)
0.322;-11.2
QQ(69)
0.394;9.4
69(9T)
0.319;-93.7
99(6K)
0.346;-31.9
9(6TQ)
0.365;-166.9
6(9TJ)
0.368;-187.5
69TT
0.335;-208.1
69TQ
0.298;-301.9
(6J)(9Q)
0.399;-11.2
6Q(9J)
0.311;-146.2
69JQ
0.315;-281.2
(6Q)(9K)
0.387;30.0
6Q(9K)
0.355;-105.0
T(6TJ)
0.371;-31.9
TK(6T)
0.343;9.4
(6T)(JQ)
0.342;9.4
QQ(6T)
0.314;30.0
6T(TJ)
0.419;-31.9
(6J)(TJ)
0.401;123.7
6J(TJ)
0.338;-11.2
TJ(6Q)
0.407;-125.6
(6Q)(TQ)
0.346;165.0
6K(TQ)
0.388;-84.4
6K(TK)
0.350;71.3
JK(6J)
0.303;50.6
K(6JK)
0.401;91.9
6JJK
0.372;-84.4
6(JQK)
0.365;-63.7
JK(6K)
0.330;91.9
KK(6Q)
0.323;112.5
6QKK
0.390;-22.5
77(7T)
0.382;-20.6
(78)(78)
0.441;93.8
7(78J)
0.365;-114.4
7K(78)
0.431;-73.1
78(7J)
0.381;-114.4
778K
0.371;-208.1
7J(79)
0.368;-93.7
79(7T)
0.381;-114.4
779Q
0.332;-208.1
7J(7T)
0.351;-73.1
7T(7J)
0.360;-73.1
77TK
0.312;-166.9
7K(7J)
0.385;-11.2
(7Q)(7Q)
0.420;258.8
77QK
0.345;-125.6
8(78T)
0.353;-114.4
8Q(78)
0.360;-73.1
J(789)
0.336;-208.1
9T(78)
0.390;-228.7
(78)(9K)
0.308;-31.9
K(78T)
0.331;-146.2
T(78K)
0.304;-146.2
JJ(78)
0.326;-31.9
(78QK)
0.320;-105.0
7888
0.331;-155.6
78(8J)
0.312;-93.7
(79)(89)
0.326;20.6
8(79Q)
0.352;-187.5
7(89T)
0.345;-228.7
(89)(7K)
0.331;-31.9
89(7J)
0.328;-208.1
89(7K)
0.298;-166.9
8J(7T)
0.378;-187.5
(8T)(7J)
0.306;-52.5
7K(8T)
0.303;-146.2
78(TQ)
0.341;-166.9
8(7JQ)
0.329;-146.2
7(8JQ)
0.285;-146.2
78(JQ)
0.319;-146.2
8(7QK)
0.361;-105.0
8Q(7K)
0.283;-105.0
99(79)
0.373;41.2
(79)(9Q)
0.329;103.1
(79TQ)
0.360;-146.2
T(79Q)
0.344;-146.2
Q(79J)
0.300;-125.6
(79)(JK)
0.345;30.0
QK(79)
0.356;-84.4
79(9J)
0.334;-52.5
(7T)(9T)
0.363;82.5
9(7TK)
0.398;-125.6
7(9TQ)
0.397;-146.2
79(TJ)
0.356;-166.9
79(TK)
0.365;-125.6
(7J)(9K)
0.371;30.0
7K(9J)
0.349;-105.0
79(JK)
0.374;-105.0
(9Q)(7K)
0.364;50.6
(7K)(9K)
0.356;206.3
T(7TQ)
0.371;9.4
Q(7TJ)
0.319;-105.0
(7T)(JK)
0.375;50.6
QK(7T)
0.369;-63.7
7T(TQ)
0.371;9.4
(7J)(TQ)
0.363;30.0
7Q(TJ)
0.297;-105.0
7TJQ
0.370;-240.0
(7Q)(TK)
0.311;71.3
7Q(TK)
0.353;-63.7
J(7JQ)
0.392;50.6
K(7JQ)
0.385;-43.1
JJ(7Q)
0.414;50.6
J(7QK)
0.383;-43.1
JQ(7K)
0.365;-43.1
QQ(7Q)
0.331;226.9
7Q(QK)
0.326;112.5
8888
0.316;0.0
888Q
0.401;-52.5
8(89J)
0.332;-52.5
8K(89)
0.316;-11.2
89(8Q)
0.387;-31.9
8(8TJ)
0.305;-31.9
8K(8T)
0.342;9.4
8T(8K)
0.441;9.4
8(8JK)
0.430;30.0
88(JK)
0.389;30.0
8Q(8K)
0.365;50.6
(89)(9T)
0.365;82.5
9(89K)
0.303;9.4
(89TK)
0.313;-105.0
TQ(89)
0.348;-125.6
K(89J)
0.306;-84.4
Q(89Q)
0.319;50.6
KK(89)
0.357;91.9
99(8Q)
0.341;-11.2
9(8TJ)
0.383;-146.2
9K(8T)
0.299;-105.0
(9T)(8K)
0.381;30.0
9T(8Q)
0.419;-125.6
(8J)(9J)
0.391;144.4
8J(9J)
0.391;9.4
9J(8Q)
0.329;-105.0
(8Q)(9Q)
0.385;185.6
8K(9Q)
0.388;-63.7
8K(9K)
0.356;91.9
TQ(8T)
0.421;30.0
K(8TJ)
0.367;-63.7
Q(8TQ)
0.373;71.3
KK(8T)
0.330;112.5
