AAAA
0.292;-1720.0
5AAA
0.262;-5140.0
9AAA
0.347;-4260.0
KAAA
0.328;-3380.0
4A(2A)
0.248;-8000.0
(2A)(7A)
0.259;-5900.0
A(2TA)
0.197;-6680.0
QA(2A)
0.248;-6240.0
2A(4A)
0.251;-8000.0
26AA
0.260;-9000.0
AA(29)
0.295;-6900.0
2A(QA)
0.281;-6240.0
A(34A)
0.270;-7780.0
6A(3A)
0.254;-7340.0
(3A)(9A)
0.224;-5240.0
A(3QA)
0.253;-6020.0
AA(34)
0.220;-7780.0
3A(7A)
0.235;-7120.0
39AA
0.225;-8120.0
AA(3Q)
0.223;-6020.0
(4A)(5A)
0.257;-5900.0
A(48A)
0.278;-6680.0
TA(4A)
0.248;-6240.0
(4A)(KA)
0.329;-4140.0
46AA
0.238;-8560.0
AA(49)
0.284;-6460.0
4A(QA)
0.257;-5800.0
A(56A)
0.277;-6900.0
8A(5A)
0.201;-6460.0
(5A)(JA)
0.327;-4360.0
55AA
0.206;-7120.0
AA(58)
0.263;-6460.0
5A(JA)
0.233;-5800.0
5KAA
0.277;-6800.0
8A(6A)
0.292;-6240.0
(6A)(JA)
0.334;-4140.0
66AA
0.265;-6680.0
AA(69)
0.248;-6020.0
6A(QA)
0.304;-5360.0
A(78A)
0.245;-6020.0
TA(7A)
0.242;-5580.0
(7A)(KA)
0.289;-3480.0
79AA
0.273;-7240.0
AA(7Q)
0.353;-5140.0
(8A)(9A)
0.351;-4140.0
A(8QA)
0.292;-4920.0
AA(89)
0.339;-5580.0
8A(QA)
0.348;-4920.0
A(9TA)
0.225;-5140.0
QA(9A)
0.299;-4700.0
9A(JA)
0.353;-4920.0
9KAA
0.295;-5920.0
QA(TA)
0.301;-4480.0
TA(QA)
0.318;-4480.0
A(JQA)
0.284;-4260.0
AA(JQ)
0.271;-4260.0
(QA)(KA)
0.296;-2380.0
KKAA
0.345;-3600.0
2(25A)
0.172;-10420.0
27(2A)
0.192;-9980.0
(2T)(2A)
0.204;-7880.0
2(2KA)
0.198;-8660.0
(236A)
0.198;-11420.0
(23TA)
0.186;-10540.0
33(2A)
0.205;-10640.0
(36)(2A)
0.206;-9980.0
3(29A)
0.190;-10760.0
3J(2A)
0.181;-10320.0
(245A)
0.166;-11420.0
(249A)
0.223;-10540.0
(24KA)
0.163;-9660.0
46(2A)
0.232;-11200.0
(49)(2A)
0.197;-9100.0
4(2QA)
0.161;-9880.0
6(25A)
0.178;-10980.0
T(25A)
0.217;-10100.0
5(26A)
0.197;-10980.0
58(2A)
0.156;-10540.0
(5J)(2A)
0.167;-8440.0
6(26A)
0.212;-9320.0
T(26A)
0.188;-9880.0
6(27A)
0.168;-10540.0
69(2A)
0.204;-10100.0
(6Q)(2A)
0.256;-8000.0
(279A)
0.145;-9880.0
(27KA)
0.225;-9000.0
79(2A)
0.196;-9880.0
(7Q)(2A)
0.234;-7780.0
(28TA)
0.168;-9440.0
88(2A)
0.254;-8440.0
(8J)(2A)
0.254;-7780.0
9(29A)
0.226;-8000.0
K(29A)
0.229;-8560.0
9(2QA)
0.225;-8780.0
J(2TA)
0.228;-8780.0
TJ(2A)
0.214;-8780.0
(2JQA)
0.221;-8340.0
J(2KA)
0.185;-8120.0
(QK)(2A)
0.261;-6460.0
22(4A)
0.180;-10640.0
226A
0.186;-11640.0
2A(29)
0.173;-9540.0
22(QA)
0.187;-8880.0
2(34A)
0.141;-11860.0
26(3A)
0.181;-11420.0
(29)(3A)
0.245;-9320.0
2(3QA)
0.184;-10100.0
A(234)
0.140;-11860.0
(23)(7A)
0.199;-9760.0
9A(23)
0.169;-10760.0
A(23Q)
0.210;-10100.0
2A(34)
0.177;-11860.0
2A(36)
0.141;-11420.0
2A(38)
0.226;-10980.0
2A(3T)
0.195;-10540.0
2A(3Q)
0.177;-10100.0
2(45A)
0.177;-11420.0
27(4A)
0.179;-10980.0
(2T)(4A)
0.235;-8880.0
2(4KA)
0.220;-9660.0
A(246)
0.159;-11200.0
(24)(9A)
0.207;-9100.0
JA(24)
0.154;-10100.0
24(5A)
0.153;-11420.0
24(7A)
0.204;-10980.0
24(9A)
0.184;-10540.0
24(JA)
0.192;-10100.0
24(KA)
0.226;-9660.0
26(5A)
0.164;-10980.0
(29)(5A)
0.192;-8880.0
2(5QA)
0.218;-9660.0
A(256)
0.178;-10980.0
(25)(9A)
0.186;-8880.0
JA(25)
0.197;-9880.0
25(6A)
0.191;-10980.0
25(8A)
0.141;-10540.0
25(TA)
0.211;-10100.0
25(QA)
0.207;-9660.0
(26)(6A)
0.243;-7880.0
2(69A)
0.190;-10100.0
2J(6A)
0.238;-9660.0
(26)(7A)
0.213;-9100.0
9A(26)
0.246;-10100.0
A(26Q)
0.210;-9440.0
2A(67)
0.225;-10540.0
2A(69)
0.212;-10100.0
2A(6J)
0.211;-9660.0
2A(6K)
0.258;-9220.0
(29)(7A)
0.238;-8440.0
2(7QA)
0.255;-9220.0
A(278)
0.217;-10100.0
(27)(JA)
0.229;-8000.0
KA(27)
0.192;-9000.0
2A(79)
0.157;-9880.0
2A(7J)
0.231;-9440.0
2A(7K)
0.194;-9000.0
(2T)(8A)
0.237;-8000.0
2(8KA)
0.241;-8780.0
A(28T)
0.197;-9440.0
(28)(KA)
0.235;-7340.0
28(TA)
0.270;-9440.0
28(QA)
0.219;-9000.0
(29)(9A)
0.233;-6560.0
2(9QA)
0.189;-8780.0
A(29T)
0.270;-9220.0
(29)(KA)
0.248;-7120.0
29(JA)
0.200;-9000.0
29(KA)
0.194;-8560.0
2J(TA)
0.227;-8780.0
(2T)(JA)
0.287;-7340.0
KA(2T)
0.245;-8340.0
2A(TQ)
0.228;-8560.0
2(JQA)
0.225;-8340.0
A(2JQ)
0.176;-8340.0
2A(JQ)
0.196;-8340.0
2(QKA)
0.214;-7900.0
2Q(KA)
0.221;-7900.0
33(3A)
0.161;-8980.0
(36)(3A)
0.257;-8320.0
3(39A)
0.210;-9100.0
3J(3A)
0.238;-8660.0
(345A)
0.184;-11200.0
(349A)
0.175;-10320.0
(34KA)
0.211;-9440.0
46(3A)
0.186;-10980.0
(49)(3A)
0.233;-8880.0
4(3QA)
0.165;-9660.0
6(35A)
0.181;-10760.0
T(35A)
0.208;-9880.0
5(36A)
0.171;-10760.0
58(3A)
0.164;-10320.0
(5J)(3A)
0.278;-8220.0
6(36A)
0.270;-9100.0
T(36A)
0.232;-9660.0
6(37A)
0.227;-10320.0
69(3A)
0.199;-9880.0
(6Q)(3A)
0.255;-7780.0
(379A)
0.208;-9660.0
(37KA)
0.194;-8780.0
79(3A)
0.199;-9660.0
(7Q)(3A)
0.191;-7560.0
(38TA)
0.262;-9220.0
88(3A)
0.284;-8220.0
(8J)(3A)
0.279;-7560.0
9(39A)
0.248;-7780.0
K(39A)
0.275;-8340.0
9(3QA)
0.232;-8560.0
J(3TA)
0.211;-8560.0
TJ(3A)
0.254;-8560.0
(3JQA)
0.212;-8120.0
J(3KA)
0.212;-7900.0
(QK)(3A)
0.228;-6240.0
33(5A)
0.209;-9980.0
337A
0.225;-10980.0
3A(3T)
0.223;-8880.0
33(KA)
0.203;-8220.0
3(46A)
0.183;-10980.0
38(4A)
0.160;-10540.0
(3J)(4A)
0.217;-8440.0
4A(34)
0.181;-9980.0
A(347)
0.205;-10760.0
(34)(TA)
0.206;-8660.0
QA(34)
0.163;-9660.0
345A
0.153;-12640.0
347A
0.145;-12200.0
349A
0.169;-11760.0
34JA
0.167;-11320.0
34KA
0.157;-10880.0
37(5A)
0.192;-10540.0
(3T)(5A)
0.244;-8440.0
3(5KA)
0.179;-9220.0
A(357)
0.207;-10540.0
(35)(TA)
0.200;-8440.0
QA(35)
0.183;-9440.0
356A
0.174;-12200.0
358A
0.155;-11760.0
35TA
0.157;-11320.0
35QA
0.186;-10880.0
(37)(6A)
0.258;-8880.0
3(6TA)
0.185;-9660.0
3Q(6A)
0.185;-9220.0
(36)(8A)
0.239;-8660.0
TA(36)
0.226;-9660.0
A(36K)
0.205;-9000.0
6A(38)
0.150;-10100.0
6A(3T)
0.211;-9660.0
6A(3Q)
0.238;-9220.0
37(7A)
0.239;-8660.0
(3T)(7A)
0.238;-8000.0
3(7KA)
0.165;-8780.0
A(379)
0.192;-9660.0
(37)(QA)
0.250;-7560.0
7A(38)
0.209;-9880.0
7A(3T)
0.182;-9440.0
7A(3Q)
0.213;-9000.0
38(8A)
0.222;-8220.0
(3J)(8A)
0.237;-7560.0
8A(38)
0.251;-8220.0
A(38J)
0.202;-9000.0
388A
0.220;-9660.0
38TA
0.223;-10660.0
38QA
0.163;-10220.0
(3T)(9A)
0.249;-7560.0
3(9KA)
0.191;-8340.0
A(39J)
0.226;-8780.0
399A
0.200;-9220.0
39JA
0.183;-10220.0
39KA
0.165;-9780.0
3Q(TA)
0.192;-8340.0
(3T)(QA)
0.241;-6900.0
TA(3J)
0.249;-8560.0
TA(3K)
0.224;-8120.0
3(JKA)
0.285;-7900.0
A(3JK)
0.173;-7900.0
JA(3K)
0.216;-7900.0
QA(3Q)
0.280;-6460.0
3QKA
0.184;-9120.0
45(4A)
0.194;-9540.0
(48)(4A)
0.264;-7440.0
4(4JA)
0.270;-8220.0
4K(4A)
0.271;-7780.0
(459A)
0.165;-9880.0
(45KA)
0.215;-9000.0
57(4A)
0.167;-10320.0
(5T)(4A)
0.231;-8220.0
5(4KA)
0.161;-9000.0
(469A)
0.186;-9660.0
(46KA)
0.237;-8780.0
68(4A)
0.168;-9880.0
(6J)(4A)
0.200;-7780.0
7(47A)
0.212;-8440.0
J(47A)
0.248;-9000.0
78(4A)
0.209;-9660.0
(7J)(4A)
0.228;-7560.0
8(48A)
0.211;-8000.0
Q(48A)
0.199;-8560.0
(8T)(4A)
0.222;-7560.0
8(4KA)
0.248;-8340.0
(49QA)
0.229;-8340.0
9(4JA)
0.212;-8560.0
9K(4A)
0.189;-8120.0
TT(4A)
0.221;-7120.0
(TK)(4A)
0.278;-6460.0
J(4QA)
0.229;-7900.0
K(4QA)
0.254;-7460.0
44(5A)
0.185;-9540.0
447A
0.184;-10540.0
4A(4T)
0.226;-8440.0
44(KA)
0.279;-7780.0
4(57A)
0.190;-10320.0
49(5A)
0.178;-9880.0
(4Q)(5A)
0.255;-7780.0
6A(45)
0.208;-10540.0
A(459)
0.217;-9880.0
(45)(QA)
0.240;-7780.0
5A(46)
0.176;-10540.0
5A(48)
0.171;-10100.0
5A(4T)
0.213;-9660.0
5A(4Q)
0.166;-9220.0
46(6A)
0.230;-8880.0
(49)(6A)
0.222;-8220.0
4(6QA)
0.201;-9000.0
A(467)
0.154;-10100.0
(46)(TA)
0.186;-8000.0
QA(46)
0.188;-9000.0
467A
0.187;-11540.0
469A
0.176;-11100.0
46JA
0.175;-10660.0
46KA
0.187;-10220.0
49(7A)
0.234;-9440.0
(4Q)(7A)
0.234;-7340.0
8A(47)
0.208;-9660.0
A(47J)
0.240;-9000.0
477A
0.215;-9880.0
479A
0.198;-10880.0
47JA
0.179;-10440.0
47KA
0.162;-10000.0
4T(8A)
0.221;-9000.0
(4K)(8A)
0.237;-6900.0
TA(48)
0.230;-9000.0
A(48K)
0.228;-8340.0
8A(4T)
0.227;-9000.0
8A(4Q)
0.208;-8560.0
49(9A)
0.240;-7560.0
(4Q)(9A)
0.301;-6900.0
TA(49)
0.213;-8780.0
A(49K)
0.183;-8120.0
9A(4J)
0.207;-8560.0
9A(4K)
0.192;-8120.0
4(TQA)
0.227;-8120.0
A(4TJ)
0.224;-8340.0
4TTA
0.201;-8560.0
4TQA
0.189;-9560.0
(4Q)(JA)
0.232;-6460.0
QA(4J)
0.196;-7900.0
4JQA
0.246;-9340.0
(4K)(QA)
0.254;-6020.0
QA(4K)
0.220;-7460.0
5(56A)
0.244;-8880.0
58(5A)
0.186;-8440.0
(5J)(5A)
0.272;-6340.0
6(56A)
0.169;-8660.0
T(56A)
0.215;-9220.0
6(57A)
0.191;-9880.0
69(5A)
0.166;-9440.0
(6Q)(5A)
0.230;-7340.0
(579A)
0.251;-9220.0
(57KA)
0.277;-8340.0
79(5A)
0.164;-9220.0
(7Q)(5A)
0.247;-7120.0
(58TA)
0.181;-8780.0
88(5A)
0.248;-7780.0
(8J)(5A)
0.251;-7120.0
9(59A)
0.263;-7340.0
K(59A)
0.196;-7900.0
9(5QA)
0.261;-8120.0
J(5TA)
0.188;-8120.0
TJ(5A)
0.283;-8120.0
(5JQA)
0.194;-7680.0
J(5KA)
0.201;-7460.0
(QK)(5A)
0.297;-5800.0
55(7A)
0.224;-8660.0
559A
0.183;-9660.0
5A(5Q)
0.229;-7560.0
(57)(6A)
0.216;-8440.0
5(6TA)
0.237;-9220.0
5Q(6A)
0.192;-8780.0
(56)(8A)
0.276;-8220.0
TA(56)
0.207;-9220.0
A(56K)
0.216;-8560.0
6A(58)
0.250;-9660.0
6A(5T)
0.207;-9220.0
6A(5Q)
0.165;-8780.0
57(7A)
0.205;-8220.0
(5T)(7A)
0.257;-7560.0
5(7KA)
0.248;-8340.0
A(579)
0.202;-9220.0
(57)(QA)
0.295;-7120.0
7A(58)
0.210;-9440.0
7A(5T)
0.209;-9000.0
7A(5Q)
0.188;-8560.0
58(8A)
0.244;-7780.0
(5J)(8A)
0.219;-7120.0
8A(58)
0.235;-7780.0
A(58J)
0.277;-8560.0
588A
0.253;-9220.0
58TA
0.166;-10220.0
58QA
0.161;-9780.0
(5T)(9A)
0.264;-7120.0
5(9KA)
0.254;-7900.0
A(59J)
0.207;-8340.0
599A
0.223;-8780.0
59JA
0.203;-9780.0
59KA
0.191;-9340.0
5Q(TA)
0.225;-7900.0
(5T)(QA)
0.194;-6460.0
TA(5J)
0.216;-8120.0
TA(5K)
0.193;-7680.0
5(JKA)
0.269;-7460.0
A(5JK)
0.192;-7460.0
JA(5K)
0.286;-7460.0
QA(5Q)
0.231;-6020.0
5QKA
0.216;-8680.0
67(6A)
0.201;-8220.0
(6T)(6A)
0.264;-6120.0
6(6KA)
0.215;-6900.0
(67TA)
0.210;-8780.0
77(6A)
0.285;-8000.0
(7T)(6A)
0.229;-7340.0
7(6KA)
0.255;-8120.0
(68JA)
0.203;-8340.0
(89)(6A)
0.277;-7340.0
8(6QA)
0.260;-8120.0
T(69A)
0.247;-8340.0
9(6TA)
0.231;-8340.0
9Q(6A)
0.279;-7900.0
Q(6TA)
0.236;-7680.0
(TQ)(6A)
0.248;-6240.0
(6JKA)
0.207;-7240.0
JK(6A)
0.237;-7240.0
K(6KA)
0.287;-5360.0
668A
0.180;-9440.0
6A(6J)
0.186;-7340.0
(67)(7A)
0.244;-6560.0
6(7TA)
0.247;-8780.0
6Q(7A)
0.215;-8340.0
(67)(9A)
0.245;-7560.0
JA(67)
0.213;-8560.0
67(8A)
0.213;-9220.0
67(TA)
0.222;-8780.0
67(QA)
0.251;-8340.0
(68)(8A)
0.321;-6120.0
6(8JA)
0.239;-8340.0
6K(8A)
0.208;-7900.0
(68)(JA)
0.227;-6900.0
KA(68)
0.255;-7900.0
6A(8T)
0.208;-8560.0
6A(8Q)
0.256;-8120.0
6(9TA)
0.207;-8340.0
6Q(9A)
0.263;-7900.0
(69)(JA)
0.291;-6680.0
KA(69)
0.244;-7680.0
6A(9J)
0.214;-8120.0
6A(9K)
0.253;-7680.0
(6Q)(TA)
0.258;-6240.0
JA(6T)
0.235;-7900.0
6T(JA)
0.171;-7900.0
6T(KA)
0.225;-7460.0
6Q(JA)
0.310;-7460.0
(6J)(KA)
0.273;-5800.0
6J(KA)
0.195;-7240.0
6K(QA)
0.270;-7020.0
6A(QK)
0.261;-7020.0
(78)(7A)
0.252;-6120.0
7(7JA)
0.213;-6900.0
7K(7A)
0.253;-6460.0
(78QA)
0.264;-7900.0
8(7TA)
0.255;-8340.0
8Q(7A)
0.209;-7900.0
J(79A)
0.296;-7900.0
9T(7A)
0.204;-8120.0
(9K)(7A)
0.264;-6020.0
K(7TA)
0.182;-7240.0
T(7KA)
0.238;-7240.0
JJ(7A)
0.298;-6020.0
(7QKA)
0.215;-6800.0
777A
0.220;-7780.0
7A(7T)
0.212;-7120.0
77(KA)
0.303;-6460.0
7(8TA)
0.199;-8340.0
7Q(8A)
0.238;-7900.0
(78)(TA)
0.280;-6900.0
QA(78)
0.220;-7900.0
789A
0.208;-10000.0
78JA
0.238;-9560.0
78KA
0.213;-9120.0
7J(9A)
0.276;-7900.0
(79)(TA)
0.215;-6680.0
QA(79)
0.206;-7680.0
79TA
0.175;-9560.0
79QA
0.177;-9120.0
(7J)(TA)
0.293;-6240.0
TA(7T)
0.299;-6460.0
A(7TK)
0.247;-7240.0
TA(7Q)
0.243;-7460.0
7J(JA)
0.237;-6020.0
(7J)(QA)
0.271;-5800.0
JA(7Q)
0.289;-7240.0
7Q(QA)
0.276;-5580.0
7QQA
0.252;-7020.0
7KKA
0.309;-6580.0
8(8JA)
0.288;-6460.0
8K(8A)
0.243;-6020.0
(89KA)
0.287;-7240.0
9J(8A)
0.237;-7680.0
(8TJA)
0.234;-7460.0
(TJ)(8A)
0.305;-6020.0
J(8JA)
0.271;-5800.0
JQ(8A)
0.245;-7020.0
Q(8KA)
0.279;-6580.0
889A
0.228;-8340.0
8A(8Q)
0.254;-6240.0
(8T)(9A)
0.258;-6460.0
8(9KA)
0.215;-7240.0
A(89J)
0.247;-7680.0
899A
0.267;-8120.0
89JA
0.170;-9120.0
89KA
0.220;-8680.0
8Q(TA)
0.290;-7240.0
(8T)(QA)
0.303;-5800.0
TA(8J)
0.264;-7460.0
TA(8K)
0.232;-7020.0
8(JKA)
0.253;-6800.0
A(8JK)
0.261;-6800.0
JA(8K)
0.219;-6800.0
QA(8Q)
0.313;-5360.0
8QKA
0.185;-8020.0
9T(9A)
0.258;-6240.0
(9K)(9A)
0.273;-4140.0
K(9TA)
0.257;-6800.0
T(9KA)
0.276;-6800.0
JJ(9A)
0.254;-5580.0
(9QKA)
0.246;-6360.0
999A
0.234;-6460.0
9A(9Q)
0.291;-5800.0
(9J)(TA)
0.256;-5800.0
TA(9T)
0.259;-6020.0
A(9TK)
0.232;-6800.0
TA(9Q)
0.280;-7020.0
9J(JA)
0.256;-5580.0
(9J)(QA)
0.265;-5360.0
JA(9Q)
0.224;-6800.0
9Q(QA)
0.280;-5140.0
9QQA
0.245;-6580.0
9KKA
0.302;-6140.0
T(TKA)
0.252;-5140.0
JJ(TA)
0.223;-5360.0
(TQKA)
0.244;-6140.0
TTTA
0.242;-5800.0
TA(TK)
0.293;-5140.0
(TK)(JA)
0.260;-4920.0
KA(TJ)
0.277;-6360.0
TA(JK)
0.216;-6360.0
(TQ)(KA)
0.263;-4700.0
(TK)(KA)
0.351;-3040.0
J(JKA)
0.269;-4700.0
(QK)(JA)
0.282;-4480.0
JJ(KA)
0.347;-4700.0
QA(JQ)
0.340;-4700.0
JQKA
0.211;-7360.0
QK(QA)
0.303;-4260.0
QK(KA)
0.343;-4040.0
22(24)
0.164;-11840.0
22(28)
0.178;-10960.0
22(2Q)
0.213;-10080.0
24(23)
0.168;-13060.0
(23)(27)
0.166;-10960.0
2(23T)
0.218;-11740.0
2Q(23)
0.214;-11300.0
23(25)
0.119;-12840.0
2237
0.153;-13840.0
22(3T)
0.177;-11740.0
23(2K)
0.218;-11080.0
2(246)
0.197;-12400.0
28(24)
0.161;-11960.0
(24)(2J)
0.203;-9860.0
2244
0.147;-12840.0
22(47)
0.141;-12180.0
24(2T)
0.198;-11520.0
224Q
0.155;-12520.0
26(25)
0.178;-12180.0
(25)(29)
0.215;-10080.0
2(25Q)
0.180;-10860.0
22(56)
0.174;-12180.0
25(29)
0.190;-11520.0
225J
0.123;-12520.0
26(26)
0.218;-10520.0
(26)(29)
0.213;-9860.0
2(26Q)
0.147;-10640.0
22(67)
0.221;-11740.0
26(2T)
0.188;-11080.0
226Q
0.209;-12080.0
28(27)
0.187;-11300.0
(27)(2J)
0.259;-9200.0
2277
0.148;-11520.0
22(7T)
0.212;-10860.0
27(2K)
0.234;-10200.0
2(28T)
0.187;-10640.0
2Q(28)
0.201;-10200.0
28(2T)
0.181;-10640.0
228Q
0.200;-11640.0
2T(29)
0.205;-10420.0
(29)(2K)
0.239;-8320.0
229J
0.199;-11640.0
2T(2T)
0.251;-8760.0
(2T)(2K)
0.298;-8100.0
22TQ
0.155;-11200.0
2Q(2J)
0.266;-9540.0
2J(2K)
0.201;-9320.0
22QQ
0.204;-9320.0
3(234)
0.173;-12840.0
36(23)
0.168;-12400.0
(23)(39)
0.228;-10300.0
3(23Q)
0.210;-11080.0
5(234)
0.110;-13840.0
9(234)
0.143;-12960.0
K(234)
0.147;-12080.0
4(237)
0.198;-13400.0
49(23)
0.153;-12960.0
(23)(4Q)
0.170;-10860.0
(2357)
0.152;-13180.0
(235J)
0.183;-12300.0
(23)(56)
0.167;-11960.0
5(239)
0.156;-12740.0
5J(23)
0.171;-12300.0
(2367)
0.143;-12960.0
(236J)
0.191;-12080.0
(23)(67)
0.147;-11520.0
6(23T)
0.184;-12300.0
6Q(23)
0.183;-11860.0
9(237)
0.141;-12300.0
K(237)
0.174;-11420.0
7(23T)
0.188;-12080.0
7Q(23)
0.188;-11640.0
T(238)
0.194;-11860.0
8(239)
0.164;-12080.0
8J(23)
0.149;-11640.0
(239T)
0.222;-11640.0
99(23)
0.192;-10420.0
(23)(9Q)
0.216;-9760.0
(23TQ)
0.168;-10980.0
T(23Q)
0.165;-10980.0
Q(23J)
0.170;-10760.0
(23)(JK)
0.252;-9100.0
QK(23)
0.214;-10320.0
23(35)
0.201;-12620.0
33(28)
0.198;-11960.0
233T
0.124;-12960.0
23(3K)
0.182;-10860.0
(24)(36)
0.176;-12180.0
3(249)
0.146;-12960.0
3J(24)
0.168;-12520.0
(34)(25)
0.153;-12400.0
27(34)
0.146;-13400.0
2(34T)
0.156;-12740.0
(34)(2K)
0.219;-10640.0
34(26)
0.135;-13620.0
34(28)
0.125;-13180.0
34(2T)
0.146;-12740.0
34(2Q)
0.184;-12300.0
(25)(35)
0.241;-10740.0
3(258)
0.171;-12960.0
3T(25)
0.152;-12520.0
(25)(3K)
0.179;-10420.0
27(35)
0.133;-13180.0
2(35T)
0.123;-12520.0
(35)(2K)
0.221;-10420.0
35(27)
0.131;-13180.0
35(29)
0.176;-12740.0
35(2J)
0.146;-12300.0
35(2K)
0.183;-11860.0
37(26)
0.131;-12960.0
(26)(3T)
0.168;-10860.0
3(26K)
0.177;-11640.0
2(368)
0.141;-12740.0
(36)(2J)
0.172;-10640.0
2K(36)
0.182;-11640.0
23(68)
0.126;-12740.0
23(6T)
0.210;-12300.0
23(6Q)
0.168;-11860.0
3(278)
0.176;-12520.0
3T(27)
0.191;-12080.0
(27)(3K)
0.198;-9980.0
29(37)
0.143;-12300.0
2(37Q)
0.198;-11640.0
23(78)
0.159;-12520.0
23(7T)
0.193;-12080.0
23(7Q)
0.144;-11640.0
3(289)
0.162;-12080.0
3J(28)
0.201;-11640.0
(38)(29)
0.154;-10640.0
2J(38)
0.155;-11640.0
38(29)
0.142;-12080.0
38(2J)
0.161;-11640.0
38(2K)
0.140;-11200.0
3T(29)
0.200;-11640.0
(29)(3K)
0.212;-9540.0
2J(39)
0.169;-11420.0
39(2T)
0.178;-11640.0
39(2Q)
0.171;-11200.0
(2T)(3T)
0.187;-8540.0
3(2TK)
0.194;-10760.0
2(3TQ)
0.177;-10980.0
23(TJ)
0.184;-11200.0
23(TK)
0.204;-10760.0
(2J)(3K)
0.219;-9100.0
2K(3J)
0.230;-10540.0
23(JK)
0.177;-10540.0
(3Q)(2K)
0.184;-8880.0
(2K)(3K)
0.239;-7220.0
4(246)
0.174;-11960.0
48(24)
0.202;-11520.0
(24)(4J)
0.211;-9420.0
5(245)
0.159;-11960.0
9(245)
0.148;-12520.0
K(245)
0.197;-11640.0
5(248)
0.125;-12740.0
5T(24)
0.142;-12300.0
(24)(5K)
0.176;-10200.0
9(246)
0.150;-12300.0
K(246)
0.206;-11420.0
6(249)
0.151;-12300.0
6J(24)
0.130;-11860.0
(2478)
0.158;-12300.0
(247Q)
0.133;-11420.0
7(249)
0.148;-12080.0
7J(24)
0.153;-11640.0
(2489)
0.172;-11860.0
(248K)
0.194;-10980.0
8T(24)
0.165;-11640.0
(24)(8K)
0.194;-9540.0
Q(249)
0.167;-10980.0
(24)(9J)
0.203;-9760.0
T(24T)
0.183;-9760.0
T(24J)
0.140;-10980.0
TK(24)
0.164;-10540.0
(24)(JQ)
0.166;-9100.0
QQ(24)
0.216;-8880.0
24(45)
0.169;-12180.0
44(28)
0.193;-11520.0
244T
0.146;-12520.0
24(4K)
0.205;-10420.0
(25)(47)
0.180;-11520.0
4(25T)
0.201;-12300.0
4Q(25)
0.184;-11860.0
(45)(27)
0.136;-11520.0
29(45)
0.132;-12520.0
2(45Q)
0.205;-11860.0
24(56)
0.157;-13180.0
24(58)
0.161;-12740.0
24(5T)
0.156;-12300.0
24(5Q)
0.190;-11860.0
4(267)
0.121;-12740.0
49(26)
0.164;-12300.0
(26)(4Q)
0.220;-10200.0
27(46)
0.116;-12740.0
2(46T)
0.207;-12080.0
(46)(2K)
0.194;-9980.0
46(28)
0.208;-12520.0
46(2T)
0.210;-12080.0
46(2Q)
0.174;-11640.0
(27)(47)
0.240;-9640.0
4(27T)
0.179;-11860.0
4Q(27)
0.177;-11420.0
(47)(29)
0.204;-10640.0
2J(47)
0.202;-11640.0
47(28)
0.184;-12300.0
47(2T)
0.148;-11860.0
47(2Q)
0.187;-11420.0
(28)(48)
0.189;-9200.0
4(28J)
0.162;-11420.0
4K(28)
0.143;-10980.0
(48)(2J)
0.231;-9980.0
2K(48)
0.152;-10980.0
24(8T)
0.177;-11640.0
24(8Q)
0.212;-11200.0
4(29T)
0.192;-11420.0
4Q(29)
0.200;-10980.0
(49)(2J)
0.241;-9760.0
2K(49)
0.200;-10760.0
24(9J)
0.152;-11200.0
24(9K)
0.195;-10760.0
(2T)(4Q)
0.183;-9320.0
2J(4T)
0.216;-10980.0
4T(2J)
0.142;-10980.0
4T(2K)
0.229;-10540.0
4Q(2J)
0.141;-10540.0
(4J)(2K)
0.241;-8880.0
4J(2K)
0.192;-10320.0
4K(2Q)
0.201;-10100.0
24(QK)
0.175;-10100.0
(25)(56)
0.200;-10080.0
5(259)
0.164;-10860.0
5J(25)
0.209;-10420.0
(2567)
0.198;-12520.0
(256J)
0.207;-11640.0
(25)(67)
0.179;-11080.0
6(25T)
0.138;-11860.0
6Q(25)
0.190;-11420.0
9(257)
0.159;-11860.0
K(257)
0.170;-10980.0
7(25T)
0.200;-11640.0
7Q(25)
0.195;-11200.0
T(258)
0.154;-11420.0
8(259)
0.167;-11640.0
8J(25)
0.150;-11200.0
(259T)
0.218;-11200.0
99(25)
0.200;-9980.0
(25)(9Q)
0.179;-9320.0
(25TQ)
0.221;-10540.0
T(25Q)
0.192;-10540.0
Q(25J)
0.160;-10320.0
(25)(JK)
0.169;-8660.0
QK(25)
0.194;-9880.0
25(57)
0.215;-11300.0
55(2T)
0.221;-10640.0
255Q
0.160;-11640.0
57(26)
0.182;-12520.0
(26)(5T)
0.186;-10420.0
5(26K)
0.190;-11200.0
2(568)
0.206;-12300.0
(56)(2J)
0.166;-10200.0
2K(56)
0.162;-11200.0
25(68)
0.175;-12300.0
25(6T)
0.138;-11860.0
25(6Q)
0.185;-11420.0
5(278)
0.130;-12080.0
5T(27)
0.188;-11640.0
(27)(5K)
0.206;-9540.0
29(57)
0.194;-11860.0
2(57Q)
0.129;-11200.0
25(78)
0.177;-12080.0
25(7T)
0.144;-11640.0
25(7Q)
0.169;-11200.0
5(289)
0.152;-11640.0
5J(28)
0.177;-11200.0
(58)(29)
0.181;-10200.0
2J(58)
0.236;-11200.0
58(29)
0.176;-11640.0
58(2J)
0.180;-11200.0
58(2K)
0.156;-10760.0
5T(29)
0.208;-11200.0
(29)(5K)
0.211;-9100.0
2J(59)
0.161;-10980.0
59(2T)
0.205;-11200.0
59(2Q)
0.200;-10760.0
(2T)(5T)
0.217;-8100.0
5(2TK)
0.188;-10320.0
2(5TQ)
0.192;-10540.0
25(TJ)
0.178;-10760.0
25(TK)
0.188;-10320.0
(2J)(5K)
0.225;-8660.0
2K(5J)
0.229;-10100.0
25(JK)
0.194;-10100.0
(5Q)(2K)
0.266;-8440.0
(2K)(5K)
0.247;-6780.0
6(268)
0.181;-10640.0
6T(26)
0.188;-10200.0
(26)(6K)
0.219;-8100.0
T(267)
0.168;-11420.0
7(268)
0.159;-11860.0
7T(26)
0.172;-11420.0
(26)(7K)
0.204;-9320.0
J(268)
0.208;-10980.0
89(26)
0.188;-11420.0
(26)(8Q)
0.238;-9320.0
(269J)
0.213;-10760.0
(26)(9T)
0.172;-9540.0
9(26K)
0.198;-10320.0
(26TK)
0.199;-10100.0
TQ(26)
0.186;-10320.0
K(26J)
0.201;-9880.0
Q(26Q)
0.217;-8440.0
KK(26)
0.209;-8000.0
66(29)
0.190;-10420.0
266J
0.132;-11420.0
67(27)
0.176;-10640.0
(27)(6T)
0.212;-9980.0
6(27K)
0.145;-10760.0
2(679)
0.146;-11640.0
(67)(2Q)
0.181;-9540.0
27(68)
0.155;-11860.0
27(6T)
0.130;-11420.0
27(6Q)
0.214;-10980.0
68(28)
0.230;-10200.0
(28)(6J)
0.189;-9540.0
28(68)
0.189;-10200.0
2(68J)
0.164;-10980.0
2688
0.198;-11640.0
268T
0.144;-12640.0
268Q
0.188;-12200.0
(29)(6T)
0.186;-9540.0
6(29K)
0.191;-10320.0
2(69J)
0.186;-10760.0
2699
0.157;-11200.0
269J
0.130;-12200.0
269K
0.157;-11760.0
6Q(2T)
0.239;-10320.0
(6T)(2Q)
0.256;-8880.0
2T(6J)
0.184;-10540.0
2T(6K)
0.186;-10100.0
6(2JK)
0.228;-9880.0
2(6JK)
0.198;-9880.0
2J(6K)
0.231;-9880.0
2Q(6Q)
0.236;-8440.0
26QK
0.168;-11100.0
78(27)
0.185;-10200.0
(27)(7J)
0.231;-8100.0
8(278)
0.177;-9980.0
Q(278)
0.162;-10540.0
(27)(8T)
0.219;-9540.0
8(27K)
0.174;-10320.0
(279Q)
0.171;-10320.0
9(27J)
0.189;-10540.0
9K(27)
0.217;-10100.0
TT(27)
0.232;-9100.0
(27)(TK)
0.210;-8440.0
J(27Q)
0.161;-9880.0
K(27Q)
0.229;-9440.0
77(28)
0.153;-10200.0
277T
0.179;-11200.0
27(7K)
0.168;-9100.0
(28)(7T)
0.207;-9540.0
7(28K)
0.207;-10320.0
2(78T)
0.192;-10980.0
(78)(2K)
0.216;-8880.0
78(2T)
0.155;-10980.0
78(2Q)
0.160;-10540.0
(29)(79)
0.207;-8100.0
7(29Q)
0.192;-10320.0
2(79T)
0.173;-10760.0
(79)(2K)
0.268;-8660.0
79(2J)
0.198;-10540.0
79(2K)
0.153;-10100.0
7J(2T)
0.175;-10320.0
(7T)(2J)
0.198;-8880.0
2K(7T)
0.201;-9880.0
27(TQ)
0.196;-10100.0
7(2JQ)
0.203;-9880.0
2(7JQ)
0.193;-9880.0
27(JQ)
0.246;-9880.0
7(2QK)
0.213;-9440.0
7Q(2K)
0.182;-9440.0
88(28)
0.232;-8320.0
(28)(8J)
0.249;-7660.0
9(289)
0.201;-9320.0
K(289)
0.151;-9880.0
9(28Q)
0.208;-10100.0
J(28T)
0.206;-10100.0
TJ(28)
0.197;-10100.0
(28JQ)
0.200;-9660.0
J(28K)
0.211;-9440.0
(28)(QK)
0.268;-7780.0
88(2T)
0.220;-9320.0
288Q
0.163;-10320.0
8T(29)
0.154;-10540.0
(29)(8K)
0.240;-8440.0
2J(89)
0.167;-10320.0
89(2T)
0.179;-10540.0
89(2Q)
0.237;-10100.0
(2T)(8T)
0.300;-7440.0
8(2TK)
0.170;-9660.0
2(8TQ)
0.231;-9880.0
28(TJ)
0.209;-10100.0
28(TK)
0.199;-9660.0
(2J)(8K)
0.207;-8000.0
2K(8J)
0.230;-9440.0
28(JK)
0.160;-9440.0
(8Q)(2K)
0.238;-7780.0
(2K)(8K)
0.267;-6120.0
9(29J)
0.182;-8660.0
9K(29)
0.212;-8220.0
TT(29)
0.192;-8660.0
(29)(TK)
0.254;-8000.0
J(29Q)
0.197;-9440.0
K(29Q)
0.203;-9000.0
99(2T)
0.274;-8880.0
299Q
0.152;-9880.0
9J(2T)
0.164;-9880.0
(9T)(2J)
0.204;-8440.0
2K(9T)
0.236;-9440.0
29(TQ)
0.220;-9660.0
9(2JQ)
0.232;-9440.0
2(9JQ)
0.245;-9440.0
29(JQ)
0.196;-9440.0
9(2QK)
0.254;-9000.0
9Q(2K)
0.219;-9000.0
TT(2T)
0.208;-7000.0
(2T)(TK)
0.228;-6340.0
J(2TQ)
0.226;-9220.0
K(2TQ)
0.198;-8780.0
TT(2J)
0.175;-8220.0
2TTK
0.191;-9220.0
TK(2J)
0.245;-9000.0
2TJJ
0.171;-9440.0
2TJK
0.159;-10440.0
2(TQK)
0.182;-8780.0
TK(2K)
0.262;-7120.0
(2J)(JK)
0.265;-5900.0
QK(2J)
0.177;-8560.0
2J(JK)
0.230;-7340.0
(JQ)(2K)
0.253;-7120.0
(2K)(JK)
0.241;-5460.0
K(2QK)
0.258;-6680.0
2K(QK)
0.260;-6680.0
3335
0.152;-12400.0
3339
0.136;-11520.0
333K
0.175;-10640.0
36(34)
0.203;-11960.0
(34)(39)
0.147;-9860.0
3(34Q)
0.164;-10640.0
33(45)
0.151;-12180.0
34(38)
0.214;-11520.0
334T
0.146;-12520.0
33(4K)
0.197;-10420.0
(35)(37)
0.181;-10080.0
3(35T)
0.229;-10860.0
3Q(35)
0.223;-10420.0
35(37)
0.231;-11520.0
3359
0.149;-12520.0
33(5Q)
0.165;-10420.0
(36)(37)
0.190;-9860.0
3(36T)
0.218;-10640.0
3Q(36)
0.229;-10200.0
36(38)
0.171;-11080.0
336T
0.191;-12080.0
33(6K)
0.150;-9980.0
(37)(39)
0.178;-9200.0
3(37Q)
0.181;-9980.0
33(78)
0.241;-10860.0
37(3J)
0.210;-10200.0
337K
0.193;-11200.0
3T(38)
0.171;-10200.0
(38)(3K)
0.232;-8100.0
338T
0.181;-11640.0
33(8K)
0.253;-9540.0
(39)(3J)
0.218;-8320.0
3399
0.239;-10200.0
33(9Q)
0.197;-9540.0
(3T)(3J)
0.217;-8100.0
33TT
0.167;-9760.0
33(TK)
0.221;-9100.0
(3J)(3K)
0.241;-7440.0
33JK
0.204;-10320.0
33(QK)
0.226;-8660.0
45(34)
0.192;-11960.0
(34)(48)
0.207;-9860.0
4(34J)
0.232;-10640.0
4K(34)
0.173;-10200.0
(3459)
0.175;-12300.0
(345K)
0.165;-11420.0
57(34)
0.147;-12740.0
(34)(5T)
0.203;-10640.0
5(34K)
0.186;-11420.0
(3469)
0.144;-12080.0
(346K)
0.156;-11200.0
68(34)
0.142;-12300.0
(34)(6J)
0.156;-10200.0
7(347)
0.229;-10860.0
J(347)
0.177;-11420.0
78(34)
0.181;-12080.0
(34)(7J)
0.239;-9980.0
8(348)
0.224;-10420.0
Q(348)
0.193;-10980.0
(34)(8T)
0.155;-9980.0
8(34K)
0.203;-10760.0
(349Q)
0.195;-10760.0
9(34J)
0.174;-10980.0
9K(34)
0.193;-10540.0
TT(34)
0.234;-9540.0
(34)(TK)
0.249;-8880.0
J(34Q)
0.239;-10320.0
K(34Q)
0.187;-9880.0
44(35)
0.131;-11960.0
3447
0.165;-12960.0
34(4T)
0.161;-10860.0
44(3K)
0.241;-10200.0
4(357)
0.135;-12740.0
49(35)
0.201;-12300.0
(35)(4Q)
0.152;-10200.0
36(45)
0.154;-12960.0
3(459)
0.164;-12300.0
(45)(3Q)
0.188;-10200.0
35(46)
0.129;-12960.0
35(48)
0.118;-12520.0
35(4T)
0.150;-12080.0
35(4Q)
0.161;-11640.0
46(36)
0.155;-11300.0
(36)(49)
0.229;-10640.0
4(36Q)
0.184;-11420.0
3(467)
0.187;-12520.0
(46)(3T)
0.164;-10420.0
3Q(46)
0.211;-11420.0
3467
0.120;-13960.0
3469
0.159;-13520.0
346J
0.167;-13080.0
346K
0.151;-12640.0
49(37)
0.161;-11860.0
(37)(4Q)
0.230;-9760.0
38(47)
0.149;-12080.0
3(47J)
0.151;-11420.0
3477
0.165;-12300.0
3479
0.141;-13300.0
347J
0.153;-12860.0
347K
0.152;-12420.0
4T(38)
0.207;-11420.0
(38)(4K)
0.217;-9320.0
3T(48)
0.183;-11420.0
3(48K)
0.160;-10760.0
38(4T)
0.157;-11420.0
38(4Q)
0.176;-10980.0
49(39)
0.177;-9980.0
(39)(4Q)
0.230;-9320.0
3T(49)
0.167;-11200.0
3(49K)
0.178;-10540.0
39(4J)
0.179;-10980.0
39(4K)
0.237;-10540.0
4(3TQ)
0.162;-10540.0
3(4TJ)
0.143;-10760.0
34TT
0.199;-10980.0
34TQ
0.165;-11980.0
(3J)(4Q)
0.197;-8880.0
3Q(4J)
0.207;-10320.0
34JQ
0.194;-11760.0
(3Q)(4K)
0.196;-8440.0
3Q(4K)
0.218;-9880.0
5(356)
0.151;-11300.0
58(35)
0.192;-10860.0
(35)(5J)
0.228;-8760.0
6(356)
0.164;-11080.0
T(356)
0.154;-11640.0
6(357)
0.145;-12300.0
69(35)
0.153;-11860.0
(35)(6Q)
0.166;-9760.0
(3579)
0.201;-11640.0
(357K)
0.221;-10760.0
79(35)
0.165;-11640.0
(35)(7Q)
0.229;-9540.0
(358T)
0.194;-11200.0
88(35)
0.180;-10200.0
(35)(8J)
0.203;-9540.0
9(359)
0.213;-9760.0
K(359)
0.200;-10320.0
9(35Q)
0.152;-10540.0
J(35T)
0.165;-10540.0
TJ(35)
0.184;-10540.0
(35JQ)
0.175;-10100.0
J(35K)
0.168;-9880.0
(35)(QK)
0.228;-8220.0
55(37)
0.194;-11080.0
3559
0.182;-12080.0
35(5Q)
0.180;-9980.0
(36)(57)
0.179;-10860.0
5(36T)
0.151;-11640.0
5Q(36)
0.203;-11200.0
(56)(38)
0.156;-10640.0
3T(56)
0.164;-11640.0
3(56K)
0.229;-10980.0
36(58)
0.194;-12080.0
36(5T)
0.182;-11640.0
36(5Q)
0.184;-11200.0
57(37)
0.175;-10640.0
(37)(5T)
0.230;-9980.0
5(37K)
0.222;-10760.0
3(579)
0.173;-11640.0
(57)(3Q)
0.200;-9540.0
37(58)
0.167;-11860.0
37(5T)
0.212;-11420.0
37(5Q)
0.147;-10980.0
58(38)
0.184;-10200.0
(38)(5J)
0.169;-9540.0
38(58)
0.211;-10200.0
3(58J)
0.196;-10980.0
3588
0.155;-11640.0
358T
0.155;-12640.0
358Q
0.165;-12200.0
(39)(5T)
0.234;-9540.0
5(39K)
0.180;-10320.0
3(59J)
0.185;-10760.0
3599
0.183;-11200.0
359J
0.197;-12200.0
359K
0.220;-11760.0
5Q(3T)
0.204;-10320.0
(5T)(3Q)
0.233;-8880.0
3T(5J)
0.153;-10540.0
3T(5K)
0.196;-10100.0
5(3JK)
0.207;-9880.0
3(5JK)
0.204;-9880.0
3J(5K)
0.181;-9880.0
3Q(5Q)
0.223;-8440.0
35QK
0.191;-11100.0
67(36)
0.160;-10640.0
(36)(6T)
0.185;-8540.0
6(36K)
0.183;-9320.0
(367T)
0.184;-11200.0
77(36)
0.173;-10420.0
(36)(7T)
0.258;-9760.0
7(36K)
0.206;-10540.0
(368J)
0.180;-10760.0
(36)(89)
0.230;-9760.0
8(36Q)
0.191;-10540.0
T(369)
0.174;-10760.0
9(36T)
0.168;-10760.0
9Q(36)
0.238;-10320.0
Q(36T)
0.178;-10100.0
(36)(TQ)
0.224;-8660.0
(36JK)
0.205;-9660.0
JK(36)
0.191;-9660.0
K(36K)
0.235;-7780.0
3668
0.188;-11860.0
36(6J)
0.162;-9760.0
(37)(67)
0.235;-8980.0
6(37T)
0.160;-11200.0
6Q(37)
0.181;-10760.0
(67)(39)
0.187;-9980.0
3J(67)
0.163;-10980.0
67(38)
0.146;-11640.0
67(3T)
0.164;-11200.0
67(3Q)
0.203;-10760.0
(38)(68)
0.202;-8540.0
6(38J)
0.215;-10760.0
6K(38)
0.217;-10320.0
(68)(3J)
0.224;-9320.0
3K(68)
0.170;-10320.0
36(8T)
0.235;-10980.0
36(8Q)
0.207;-10540.0
6(39T)
0.158;-10760.0
6Q(39)
0.189;-10320.0
(69)(3J)
0.212;-9100.0
3K(69)
0.222;-10100.0
36(9J)
0.187;-10540.0
36(9K)
0.183;-10100.0
(3T)(6Q)
0.227;-8660.0
3J(6T)
0.194;-10320.0
6T(3J)
0.194;-10320.0
6T(3K)
0.206;-9880.0
6Q(3J)
0.214;-9880.0
(6J)(3K)
0.193;-8220.0
6J(3K)
0.185;-9660.0
6K(3Q)
0.263;-9440.0
36(QK)
0.207;-9440.0
(37)(78)
0.162;-8540.0
7(37J)
0.252;-9320.0
7K(37)
0.179;-8880.0
(378Q)
0.200;-10320.0
8(37T)
0.158;-10760.0
8Q(37)
0.200;-10320.0
J(379)
0.174;-10320.0
9T(37)
0.178;-10540.0
(37)(9K)
0.261;-8440.0
K(37T)
0.249;-9660.0
T(37K)
0.173;-9660.0
JJ(37)
0.229;-8440.0
(37QK)
0.205;-9220.0
3777
0.157;-10200.0
37(7T)
0.213;-9540.0
77(3K)
0.178;-8880.0
7(38T)
0.151;-10760.0
7Q(38)
0.176;-10320.0
(78)(3T)
0.181;-9320.0
3Q(78)
0.178;-10320.0
3789
0.138;-12420.0
378J
0.199;-11980.0
378K
0.176;-11540.0
7J(39)
0.187;-10320.0
(79)(3T)
0.210;-9100.0
3Q(79)
0.229;-10100.0
379T
0.182;-11980.0
379Q
0.139;-11540.0
(3T)(7J)
0.244;-8660.0
3T(7T)
0.170;-8880.0
3(7TK)
0.254;-9660.0
3T(7Q)
0.228;-9880.0
7J(3J)
0.235;-8440.0
(7J)(3Q)
0.219;-8220.0
3J(7Q)
0.195;-9660.0
7Q(3Q)
0.278;-8000.0
37QQ
0.181;-9440.0
37KK
0.208;-9000.0
8(38J)
0.193;-8880.0
8K(38)
0.209;-8440.0
(389K)
0.205;-9660.0
9J(38)
0.234;-10100.0
(38TJ)
0.260;-9880.0
(38)(TJ)
0.239;-8440.0
J(38J)
0.230;-8220.0
JQ(38)
0.207;-9440.0
Q(38K)
0.229;-9000.0
3889
0.152;-10760.0
38(8Q)
0.224;-8660.0
(39)(8T)
0.204;-8880.0
8(39K)
0.165;-9660.0
3(89J)
0.164;-10100.0
3899
0.233;-10540.0
389J
0.124;-11540.0
389K
0.211;-11100.0
8Q(3T)
0.173;-9660.0
(8T)(3Q)
0.253;-8220.0
3T(8J)
0.206;-9880.0
3T(8K)
0.231;-9440.0
8(3JK)
0.181;-9220.0
3(8JK)
0.189;-9220.0
3J(8K)
0.213;-9220.0
3Q(8Q)
0.227;-7780.0
38QK
0.149;-10440.0
9T(39)
0.227;-8660.0
(39)(9K)
0.285;-6560.0
K(39T)
0.246;-9220.0
T(39K)
0.270;-9220.0
JJ(39)
0.232;-8000.0
(39QK)
0.247;-8780.0
3999
0.238;-8880.0
39(9Q)
0.226;-8220.0
(3T)(9J)
0.243;-8220.0
3T(9T)
0.216;-8440.0
3(9TK)
0.191;-9220.0
3T(9Q)
0.218;-9440.0
9J(3J)
0.262;-8000.0
(9J)(3Q)
0.200;-7780.0
3J(9Q)
0.171;-9220.0
9Q(3Q)
0.207;-7560.0
39QQ
0.240;-9000.0
39KK
0.193;-8560.0
T(3TK)
0.242;-7560.0
JJ(3T)
0.234;-7780.0
(3TQK)
0.168;-8560.0
3TTT
0.219;-8220.0
3T(TK)
0.246;-7560.0
(3J)(TK)
0.244;-7340.0
3K(TJ)
0.195;-8780.0
3T(JK)
0.227;-8780.0
(TQ)(3K)
0.254;-7120.0
(3K)(TK)
0.310;-5460.0
J(3JK)
0.277;-7120.0
(3J)(QK)
0.287;-6900.0
JJ(3K)
0.195;-7120.0
3Q(JQ)
0.250;-7120.0
3JQK
0.218;-9780.0
QK(3Q)
0.263;-6680.0
QK(3K)
0.265;-6460.0
44(46)
0.158;-10080.0
44(4T)
0.162;-9200.0
(45)(45)
0.240;-8640.0
4(458)
0.207;-10860.0
4T(45)
0.187;-10420.0
(45)(4K)
0.250;-8320.0
4457
0.151;-12520.0
44(5T)
0.162;-10420.0
45(4K)
0.194;-9760.0
4(468)
0.165;-10640.0
4T(46)
0.180;-10200.0
(46)(4K)
0.222;-8100.0
4468
0.160;-12080.0
44(6J)
0.200;-9980.0
(47)(47)
0.213;-7760.0
4(47T)
0.197;-9980.0
4Q(47)
0.201;-9540.0
47(49)
0.150;-10200.0
447J
0.164;-11200.0
48(48)
0.213;-8760.0
(48)(4J)
0.205;-8100.0
4488
0.161;-10200.0
44(8J)
0.187;-9540.0
(49)(49)
0.254;-6880.0
4(49Q)
0.224;-9100.0
44(9T)
0.184;-9540.0
49(4K)
0.214;-8880.0
4(4TQ)
0.168;-8880.0
44(TJ)
0.241;-9100.0
(4J)(4J)
0.317;-6000.0
44JJ
0.221;-8880.0
4Q(4Q)
0.260;-7000.0
(4K)(4K)
0.260;-5120.0
(45)(57)
0.221;-9420.0
5(45T)
0.185;-10200.0
5Q(45)
0.197;-9760.0
8(456)
0.197;-11860.0
Q(456)
0.227;-10980.0
(45)(68)
0.189;-10420.0
6(45J)
0.186;-11200.0
6K(45)
0.151;-10760.0
(457J)
0.149;-10980.0
(45)(78)
0.206;-10200.0
7(45J)
0.184;-10980.0
7K(45)
0.219;-10540.0
(458Q)
0.183;-10540.0
8(45T)
0.154;-10980.0
8Q(45)
0.170;-10540.0
J(459)
0.188;-10540.0
9T(45)
0.173;-10760.0
(45)(9K)
0.216;-8660.0
K(45T)
0.227;-9880.0
T(45K)
0.235;-9880.0
JJ(45)
0.230;-8660.0
(45QK)
0.214;-9440.0
4555
0.209;-11300.0
45(58)
0.193;-10640.0
55(4J)
0.164;-9980.0
455K
0.181;-10980.0
58(46)
0.181;-11860.0
(46)(5J)
0.201;-9760.0
46(56)
0.202;-10860.0
4(569)
0.157;-11640.0
(56)(4Q)
0.154;-9540.0
46(57)
0.142;-12080.0
46(59)
0.174;-11640.0
46(5J)
0.155;-11200.0
46(5K)
0.232;-10760.0
5(479)
0.166;-11420.0
5J(47)
0.167;-10980.0
(57)(48)
0.248;-10200.0
4T(57)
0.172;-11200.0
4(57K)
0.187;-10540.0
47(59)
0.176;-11420.0
47(5J)
0.199;-10980.0
47(5K)
0.215;-10540.0
5(48T)
0.147;-10980.0
5Q(48)
0.184;-10540.0
(58)(4T)
0.230;-9540.0
4Q(58)
0.172;-10540.0
4589
0.186;-12640.0
458J
0.182;-12200.0
458K
0.176;-11760.0
5J(49)
0.171;-10540.0
(59)(4T)
0.202;-9320.0
4Q(59)
0.189;-10320.0
459T
0.192;-12200.0
459Q
0.162;-11760.0
(4T)(5J)
0.256;-8880.0
4T(5T)
0.204;-9100.0
4(5TK)
0.155;-9880.0
4T(5Q)
0.227;-10100.0
5J(4J)
0.201;-8660.0
(5J)(4Q)
0.280;-8440.0
4J(5Q)
0.216;-9880.0
5Q(4Q)
0.196;-8220.0
45QQ
0.193;-9660.0
45KK
0.152;-9220.0
6(469)
0.177;-9980.0
6J(46)
0.179;-9540.0
(4678)
0.145;-11420.0
(467Q)
0.172;-10540.0
7(469)
0.191;-11200.0
7J(46)
0.217;-10760.0
(4689)
0.170;-10980.0
(468K)
0.197;-10100.0
8T(46)
0.187;-10760.0
(46)(8K)
0.236;-8660.0
Q(469)
0.200;-10100.0
(46)(9J)
0.247;-8880.0
T(46T)
0.191;-8880.0
T(46J)
0.165;-10100.0
TK(46)
0.186;-9660.0
(46)(JQ)
0.238;-8220.0
QQ(46)
0.232;-8000.0
46(67)
0.187;-10420.0
66(4T)
0.210;-9760.0
466Q
0.181;-10760.0
68(47)
0.150;-11420.0
(47)(6J)
0.209;-9320.0
47(67)
0.184;-10200.0
4(67T)
0.209;-10980.0
(67)(4K)
0.190;-8880.0
67(49)
0.238;-11200.0
67(4J)
0.217;-10760.0
67(4K)
0.179;-10320.0
69(48)
0.203;-10980.0
(48)(6Q)
0.194;-8880.0
49(68)
0.210;-10980.0
4(68Q)
0.162;-10320.0
46(89)
0.201;-10980.0
46(8J)
0.163;-10540.0
46(8K)
0.174;-10100.0
(49)(6J)
0.252;-8880.0
49(69)
0.184;-9320.0
4(69Q)
0.189;-10100.0
46(9T)
0.181;-10540.0
46(9Q)
0.175;-10100.0
6(4TJ)
0.157;-10100.0
6K(4T)
0.256;-9660.0
(6T)(4K)
0.214;-8220.0
6T(4Q)
0.197;-9880.0
(4J)(6J)
0.206;-7000.0
4J(6J)
0.262;-8440.0
6J(4Q)
0.190;-9660.0
(4Q)(6Q)
0.228;-6560.0
4K(6Q)
0.190;-9220.0
4K(6K)
0.190;-7560.0
79(47)
0.207;-9540.0
(47)(7Q)
0.281;-7440.0
(478T)
0.239;-10540.0
88(47)
0.229;-9540.0
(47)(8J)
0.210;-8880.0
9(479)
0.183;-9100.0
K(479)
0.220;-9660.0
9(47Q)
0.180;-9880.0
J(47T)
0.230;-9880.0
TJ(47)
0.163;-9880.0
(47JQ)
0.201;-9440.0
J(47K)
0.269;-9220.0
(47)(QK)
0.242;-7560.0
77(49)
0.205;-9540.0
477J
0.163;-10540.0
78(48)
0.156;-9540.0
(48)(7J)
0.199;-8880.0
48(78)
0.218;-9540.0
4(78J)
0.216;-10320.0
4788
0.158;-10980.0
478T
0.149;-11980.0
478Q
0.192;-11540.0
(49)(7T)
0.218;-8880.0
7(49K)
0.264;-9660.0
4(79J)
0.176;-10100.0
4799
0.193;-10540.0
479J
0.165;-11540.0
479K
0.212;-11100.0
7Q(4T)
0.216;-9660.0
(7T)(4Q)
0.242;-8220.0
4T(7J)
0.158;-9880.0
4T(7K)
0.176;-9440.0
7(4JK)
0.196;-9220.0
4(7JK)
0.219;-9220.0
4J(7K)
0.193;-9220.0
4Q(7Q)
0.232;-7780.0
47QK
0.153;-10440.0
89(48)
0.166;-9100.0
(48)(8Q)
0.255;-7000.0
(489J)
0.226;-9880.0
(48)(9T)
0.190;-8660.0
9(48K)
0.228;-9440.0
(48TK)
0.223;-9220.0
TQ(48)
0.199;-9440.0
K(48J)
0.191;-9000.0
Q(48Q)
0.233;-7560.0
KK(48)
0.275;-7120.0
88(4J)
0.205;-8660.0
488K
0.216;-9660.0
8J(49)
0.237;-9880.0
(89)(4T)
0.226;-8660.0
4Q(89)
0.249;-9660.0
489T
0.163;-11540.0
489Q
0.157;-11100.0
(4T)(8J)
0.178;-8220.0
4T(8T)
0.220;-8440.0
4(8TK)
0.224;-9220.0
4T(8Q)
0.227;-9440.0
8J(4J)
0.212;-8000.0
(8J)(4Q)
0.197;-7780.0
4J(8Q)
0.232;-9220.0
8Q(4Q)
0.198;-7560.0
48QQ
0.192;-9000.0
48KK
0.220;-8560.0
9(49Q)
0.224;-8000.0
J(49T)
0.190;-9440.0
TJ(49)
0.196;-9440.0
(49JQ)
0.253;-9000.0
J(49K)
0.187;-8780.0
(49)(QK)
0.283;-7120.0
99(4J)
0.185;-8220.0
499K
0.206;-9220.0
9Q(4T)
0.191;-9220.0
(9T)(4Q)
0.235;-7780.0
4T(9J)
0.214;-9440.0
4T(9K)
0.209;-9000.0
9(4JK)
0.164;-8780.0
4(9JK)
0.216;-8780.0
4J(9K)
0.215;-8780.0
4Q(9Q)
0.282;-7340.0
49QK
0.181;-10000.0
TJ(4T)
0.233;-7780.0
(4TJQ)
0.191;-8780.0
J(4TK)
0.223;-8560.0
(4T)(QK)
0.225;-6900.0
TT(4Q)
0.225;-7560.0
T(4JQ)
0.278;-8780.0
4(TJQ)
0.223;-8780.0
4T(JQ)
0.200;-8780.0
T(4QK)
0.204;-8340.0
TQ(4K)
0.197;-8340.0
JJ(4J)
0.275;-5900.0
(4JQK)
0.192;-8120.0
4JJJ
0.219;-7340.0
JQ(4Q)
0.276;-6900.0
4JQQ
0.237;-8340.0
4JKK
0.260;-7900.0
QQ(4K)
0.332;-6460.0
4KKK
0.249;-6020.0
55(59)
0.224;-8760.0
55(5K)
0.226;-7880.0
(56)(58)
0.186;-8760.0
5(56J)
0.215;-9540.0
5K(56)
0.229;-9100.0
56(59)
0.199;-9980.0
556J
0.221;-10980.0
57(57)
0.218;-8760.0
(57)(5T)
0.178;-8100.0
5(57K)
0.217;-8880.0
55(79)
0.248;-9760.0
57(5Q)
0.185;-9100.0
5(589)
0.237;-9540.0
5J(58)
0.230;-9100.0
58(59)
0.169;-9540.0
558J
0.177;-10540.0
59(59)
0.220;-7880.0
(59)(5Q)
0.309;-7220.0
559T
0.177;-10540.0
55(9K)
0.288;-8440.0
(5T)(5Q)
0.275;-7000.0
55TJ
0.165;-10100.0
5J(5J)
0.237;-7000.0
5J(5Q)
0.201;-8220.0
5(5QK)
0.239;-7780.0
5K(5K)
0.257;-6120.0
68(56)
0.211;-9980.0
(56)(6J)
0.273;-7880.0
7(567)
0.233;-9980.0
J(567)
0.175;-10540.0
78(56)
0.170;-11200.0
(56)(7J)
0.182;-9100.0
8(568)
0.199;-9540.0
Q(568)
0.224;-10100.0
(56)(8T)
0.188;-9100.0
8(56K)
0.173;-9880.0
(569Q)
0.194;-9880.0
9(56J)
0.199;-10100.0
9K(56)
0.198;-9660.0
TT(56)
0.233;-8660.0
(56)(TK)
0.200;-8000.0
J(56Q)
0.197;-9440.0
K(56Q)
0.246;-9000.0
66(57)
0.177;-10200.0
5669
0.155;-11200.0
56(6Q)
0.203;-9100.0
(57)(68)
0.218;-9760.0
6(57J)
0.176;-10540.0
6K(57)
0.216;-10100.0
(67)(5T)
0.157;-9320.0
5Q(67)
0.185;-10320.0
5678
0.160;-12640.0
567T
0.148;-12200.0
567Q
0.164;-11760.0
(58)(69)
0.170;-9320.0
6(58Q)
0.146;-10100.0
5(689)
0.209;-10760.0
(68)(5Q)
0.259;-8660.0
58(69)
0.210;-10760.0
58(6J)
0.221;-10320.0
58(6K)
0.158;-9880.0
6(59J)
0.174;-10100.0
6K(59)
0.255;-9660.0
(69)(5Q)
0.234;-8440.0
59(6T)
0.181;-10320.0
59(6Q)
0.208;-9880.0
6T(5T)
0.214;-8660.0
(5T)(6K)
0.208;-8000.0
5Q(6T)
0.187;-9660.0
56TJ
0.224;-11320.0
56TK
0.175;-10880.0
6K(5J)
0.156;-9220.0
56JJ
0.207;-9660.0
56JK
0.160;-10660.0
5(6QK)
0.202;-9000.0
6K(5K)
0.192;-7340.0
(57)(79)
0.221;-7880.0
7(57Q)
0.222;-8660.0
9(578)
0.240;-10540.0
K(578)
0.207;-9660.0
8(57J)
0.197;-10100.0
8K(57)
0.176;-9660.0
(579K)
0.194;-9440.0
9J(57)
0.184;-9880.0
(57TJ)
0.179;-9660.0
(57)(TJ)
0.257;-8220.0
J(57J)
0.247;-8000.0
JQ(57)
0.206;-9220.0
Q(57K)
0.231;-8780.0
5778
0.190;-10980.0
57(7J)
0.186;-8880.0
(58)(78)
0.253;-7880.0
7(58J)
0.177;-10100.0
7K(58)
0.245;-9660.0
(78)(5J)
0.234;-8660.0
5K(78)
0.202;-9660.0
57(8T)
0.227;-10320.0
57(8Q)
0.244;-9880.0
7(59T)
0.199;-10100.0
7Q(59)
0.232;-9660.0
(79)(5J)
0.176;-8440.0
5K(79)
0.173;-9440.0
57(9J)
0.169;-9880.0
57(9K)
0.211;-9440.0
(5T)(7Q)
0.186;-8000.0
5J(7T)
0.230;-9660.0
7T(5J)
0.194;-9660.0
7T(5K)
0.201;-9220.0
7Q(5J)
0.205;-9220.0
(7J)(5K)
0.253;-7560.0
7J(5K)
0.221;-9000.0
7K(5Q)
0.215;-8780.0
57(QK)
0.198;-8780.0
(58)(89)
0.267;-7440.0
8(58Q)
0.238;-8220.0
T(589)
0.214;-9880.0
9(58T)
0.228;-9880.0
9Q(58)
0.236;-9440.0
Q(58T)
0.225;-9220.0
(58)(TQ)
0.241;-7780.0
(58JK)
0.221;-8780.0
JK(58)
0.201;-8780.0
K(58K)
0.243;-6900.0
588T
0.212;-10100.0
58(8K)
0.241;-8000.0
(59)(8J)
0.203;-8220.0
59(89)
0.216;-8660.0
5(89Q)
0.208;-9440.0
58(9T)
0.151;-9880.0
58(9Q)
0.223;-9440.0
8(5TJ)
0.163;-9440.0
8K(5T)
0.207;-9000.0
(8T)(5K)
0.263;-7560.0
8T(5Q)
0.191;-9220.0
(5J)(8J)
0.211;-6340.0
5J(8J)
0.235;-7780.0
8J(5Q)
0.271;-9000.0
(5Q)(8Q)
0.233;-5900.0
5K(8Q)
0.219;-8560.0
5K(8K)
0.306;-6900.0
9J(59)
0.232;-8000.0
(59TJ)
0.198;-9220.0
(59)(TJ)
0.220;-7780.0
J(59J)
0.266;-7560.0
JQ(59)
0.172;-8780.0
Q(59K)
0.187;-8340.0
599T
0.182;-9660.0
59(9K)
0.244;-7560.0
(5T)(9Q)
0.217;-7560.0
5J(9T)
0.191;-9220.0
9T(5J)
0.202;-9220.0
9T(5K)
0.207;-8780.0
9Q(5J)
0.219;-8780.0
(9J)(5K)
0.235;-7120.0
9J(5K)
0.179;-8560.0
9K(5Q)
0.249;-8340.0
59(QK)
0.247;-8340.0
(5T)(TJ)
0.261;-6120.0
J(5TJ)
0.195;-7340.0
JQ(5T)
0.226;-8560.0
Q(5TK)
0.209;-8120.0
5TTJ
0.209;-9000.0
TJ(5J)
0.277;-7340.0
(TJ)(5Q)
0.224;-7120.0
5J(TQ)
0.233;-8560.0
TQ(5Q)
0.251;-6900.0
5TQQ
0.167;-8340.0
5TKK
0.217;-7900.0
Q(5JQ)
0.215;-6680.0
KK(5J)
0.248;-6240.0
(5Q)(JQ)
0.249;-5240.0
5K(JQ)
0.291;-7900.0
5K(JK)
0.331;-6240.0
5QQQ
0.271;-6460.0
KK(5K)
0.314;-4360.0
6669
0.213;-9540.0
666K
0.174;-8660.0
69(67)
0.181;-9320.0
(67)(6Q)
0.255;-7220.0
6678
0.166;-10980.0
66(7J)
0.216;-8880.0
(68)(68)
0.317;-6440.0
6(68J)
0.257;-8660.0
6K(68)
0.192;-8220.0
68(6J)
0.182;-8660.0
668K
0.168;-9660.0
6J(69)
0.173;-8440.0
69(6T)
0.219;-8660.0
669Q
0.220;-9660.0
6J(6T)
0.254;-8220.0
6T(6J)
0.245;-8220.0
66TK
0.231;-9220.0
6K(6J)
0.179;-7560.0
(6Q)(6Q)
0.277;-4680.0
66QK
0.242;-8780.0
7(679)
0.235;-9100.0
7J(67)
0.271;-8660.0
(6789)
0.245;-10320.0
(678K)
0.233;-9440.0
8T(67)
0.214;-10100.0
(67)(8K)
0.255;-8000.0
Q(679)
0.218;-9440.0
(67)(9J)
0.252;-8220.0
T(67T)
0.193;-8220.0
T(67J)
0.155;-9440.0
TK(67)
0.244;-9000.0
(67)(JQ)
0.234;-7560.0
QQ(67)
0.237;-7340.0
67(78)
0.244;-9320.0
77(6J)
0.271;-8660.0
677K
0.166;-9660.0
7T(68)
0.191;-10100.0
(68)(7K)
0.236;-8000.0
6T(78)
0.212;-10100.0
6(78K)
0.228;-9440.0
68(7T)
0.205;-10100.0
68(7Q)
0.193;-9660.0
79(69)
0.217;-8660.0
(69)(7Q)
0.212;-8000.0
6T(79)
0.196;-9880.0
6(79K)
0.191;-9220.0
69(7J)
0.151;-9660.0
69(7K)
0.226;-9220.0
7(6TQ)
0.221;-9220.0
6(7TJ)
0.255;-9440.0
67TT
0.203;-9660.0
67TQ
0.181;-10660.0
(6J)(7Q)
0.204;-7560.0
6Q(7J)
0.234;-9000.0
67JQ
0.196;-10440.0
(6Q)(7K)
0.275;-7120.0
6Q(7K)
0.195;-8560.0
8(689)
0.191;-8660.0
8J(68)
0.205;-8220.0
(689T)
0.222;-9660.0
99(68)
0.187;-8440.0
(68)(9Q)
0.203;-7780.0
(68TQ)
0.164;-9000.0
T(68Q)
0.174;-9000.0
Q(68J)
0.221;-8780.0
(68)(JK)
0.240;-7120.0
QK(68)
0.219;-8340.0
68(8T)
0.230;-8440.0
88(6K)
0.250;-7780.0
8(69J)
0.217;-9440.0
8K(69)
0.155;-9000.0
(89)(6Q)
0.254;-7780.0
69(8T)
0.184;-9660.0
69(8Q)
0.212;-9220.0
8T(6T)
0.193;-8000.0
(6T)(8K)
0.197;-7340.0
6Q(8T)
0.217;-9000.0
68TJ
0.191;-10660.0
68TK
0.211;-10220.0
8K(6J)
0.192;-8560.0
68JJ
0.207;-9000.0
68JK
0.211;-10000.0
6(8QK)
0.219;-8340.0
8K(6K)
0.288;-6680.0
(69)(9J)
0.232;-6340.0
T(69T)
0.233;-7780.0
T(69J)
0.177;-9000.0
TK(69)
0.212;-8560.0
(69)(JQ)
0.247;-7120.0
QQ(69)
0.258;-6900.0
69(9T)
0.226;-8000.0
99(6K)
0.241;-7340.0
9(6TQ)
0.240;-8780.0
6(9TJ)
0.240;-9000.0
69TT
0.211;-9220.0
69TQ
0.199;-10220.0
(6J)(9Q)
0.244;-7120.0
6Q(9J)
0.216;-8560.0
69JQ
0.210;-10000.0
(6Q)(9K)
0.244;-6680.0
6Q(9K)
0.199;-8120.0
T(6TJ)
0.207;-7340.0
TK(6T)
0.274;-6900.0
(6T)(JQ)
0.242;-6900.0
QQ(6T)
0.242;-6680.0
6T(TJ)
0.271;-7340.0
(6J)(TJ)
0.255;-5680.0
6J(TJ)
0.249;-7120.0
TJ(6Q)
0.234;-8340.0
(6Q)(TQ)
0.251;-5240.0
6K(TQ)
0.244;-7900.0
6K(TK)
0.253;-6240.0
JK(6J)
0.231;-6460.0
K(6JK)
0.216;-6020.0
6JJK
0.220;-7900.0
6(JQK)
0.248;-7680.0
JK(6K)
0.281;-6020.0
KK(6Q)
0.213;-5800.0
6QKK
0.251;-7240.0
77(7T)
0.249;-7220.0
(78)(78)
0.287;-6000.0
7(78J)
0.232;-8220.0
7K(78)
0.200;-7780.0
78(7J)
0.213;-8220.0
778K
0.203;-9220.0
7J(79)
0.247;-8000.0
79(7T)
0.257;-8220.0
779Q
0.184;-9220.0
7J(7T)
0.239;-7780.0
7T(7J)
0.222;-7780.0
77TK
0.188;-8780.0
7K(7J)
0.308;-7120.0
(7Q)(7Q)
0.228;-4240.0
77QK
0.239;-8340.0
8(78T)
0.246;-8220.0
8Q(78)
0.287;-7780.0
J(789)
0.204;-9220.0
9T(78)
0.194;-9440.0
(78)(9K)
0.215;-7340.0
K(78T)
0.231;-8560.0
T(78K)
0.228;-8560.0
JJ(78)
0.224;-7340.0
(78QK)
0.209;-8120.0
7888
0.218;-8660.0
78(8J)
0.292;-8000.0
(79)(89)
0.263;-6780.0
8(79Q)
0.217;-9000.0
7(89T)
0.184;-9440.0
(89)(7K)
0.212;-7340.0
89(7J)
0.207;-9220.0
89(7K)
0.190;-8780.0
8J(7T)
0.175;-9000.0
(8T)(7J)
0.296;-7560.0
7K(8T)
0.234;-8560.0
78(TQ)
0.230;-8780.0
8(7JQ)
0.229;-8560.0
7(8JQ)
0.244;-8560.0
78(JQ)
0.262;-8560.0
8(7QK)
0.280;-8120.0
8Q(7K)
0.228;-8120.0
99(79)
0.263;-6560.0
(79)(9Q)
0.281;-5900.0
(79TQ)
0.162;-8560.0
T(79Q)
0.241;-8560.0
Q(79J)
0.194;-8340.0
(79)(JK)
0.245;-6680.0
QK(79)
0.272;-7900.0
79(9J)
0.192;-7560.0
(7T)(9T)
0.280;-6120.0
9(7TK)
0.210;-8340.0
7(9TQ)
0.206;-8560.0
79(TJ)
0.198;-8780.0
79(TK)
0.245;-8340.0
(7J)(9K)
0.284;-6680.0
7K(9J)
0.219;-8120.0
79(JK)
0.231;-8120.0
(9Q)(7K)
0.208;-6460.0
(7K)(9K)
0.296;-4800.0
T(7TQ)
0.318;-6900.0
Q(7TJ)
0.243;-8120.0
(7T)(JK)
0.313;-6460.0
QK(7T)
0.278;-7680.0
7T(TQ)
0.193;-6900.0
(7J)(TQ)
0.286;-6680.0
7Q(TJ)
0.206;-8120.0
7TJQ
0.167;-9560.0
(7Q)(TK)
0.229;-6240.0
7Q(TK)
0.222;-7680.0
J(7JQ)
0.268;-6460.0
K(7JQ)
0.212;-7460.0
JJ(7Q)
0.196;-6460.0
J(7QK)
0.186;-7460.0
JQ(7K)
0.198;-7460.0
QQ(7Q)
0.334;-4580.0
7Q(QK)
0.308;-5800.0
8888
0.250;-7000.0
888Q
0.239;-7560.0
8(89J)
0.199;-7560.0
8K(89)
0.243;-7120.0
89(8Q)
0.228;-7340.0
8(8TJ)
0.241;-7340.0
8K(8T)
0.219;-6900.0
8T(8K)
0.222;-6900.0
8(8JK)
0.259;-6680.0
88(JK)
0.254;-6680.0
8Q(8K)
0.249;-6460.0
(89)(9T)
0.318;-6120.0
9(89K)
0.266;-6900.0
(89TK)
0.226;-8120.0
TQ(89)
0.215;-8340.0
K(89J)
0.299;-7900.0
Q(89Q)
0.318;-6460.0
KK(89)
0.329;-6020.0
99(8Q)
0.274;-7120.0
9(8TJ)
0.186;-8560.0
9K(8T)
0.273;-8120.0
(9T)(8K)
0.306;-6680.0
9T(8Q)
0.259;-8340.0
(8J)(9J)
0.282;-5460.0
8J(9J)
0.250;-6900.0
9J(8Q)
0.204;-8120.0
(8Q)(9Q)
0.308;-5020.0
8K(9Q)
0.225;-7680.0
8K(9K)
0.242;-6020.0
TQ(8T)
0.221;-6680.0
K(8TJ)
0.234;-7680.0
Q(8TQ)
0.250;-6240.0
KK(8T)
0.252;-5800.0
