AAAA
0.162;25.0
5AAA
0.092;-1578.1
9AAA
0.118;-1165.6
KAAA
0.114;-753.1
4A(2A)
0.048;-2918.8
(2A)(7A)
0.076;-1934.4
A(2TA)
0.074;-2300.0
QA(2A)
0.087;-2093.7
2A(4A)
0.045;-2918.8
26AA
0.045;-3387.5
AA(29)
0.059;-2403.1
2A(QA)
0.069;-2093.7
A(34A)
0.061;-2815.6
6A(3A)
0.053;-2609.4
(3A)(9A)
0.091;-1625.0
A(3QA)
0.066;-1990.6
AA(34)
0.054;-2815.6
3A(7A)
0.077;-2506.2
39AA
0.043;-2975.0
AA(3Q)
0.085;-1990.6
(4A)(5A)
0.087;-1934.4
A(48A)
0.061;-2300.0
TA(4A)
0.094;-2093.7
(4A)(KA)
0.140;-1109.4
46AA
0.045;-3181.3
AA(49)
0.070;-2196.9
4A(QA)
0.073;-1887.5
A(56A)
0.073;-2403.1
8A(5A)
0.077;-2196.9
(5A)(JA)
0.086;-1212.5
55AA
0.064;-2506.2
AA(58)
0.074;-2196.9
5A(JA)
0.087;-1887.5
5KAA
0.057;-2356.3
8A(6A)
0.063;-2093.7
(6A)(JA)
0.089;-1109.4
66AA
0.080;-2300.0
AA(69)
0.080;-1990.6
6A(QA)
0.096;-1681.3
A(78A)
0.084;-1990.6
TA(7A)
0.087;-1784.4
(7A)(KA)
0.101;-800.0
79AA
0.045;-2562.5
AA(7Q)
0.092;-1578.1
(8A)(9A)
0.114;-1109.4
A(8QA)
0.121;-1475.0
AA(89)
0.077;-1784.4
8A(QA)
0.112;-1475.0
A(9TA)
0.102;-1578.1
QA(9A)
0.101;-1371.9
9A(JA)
0.086;-1475.0
9KAA
0.075;-1943.8
QA(TA)
0.119;-1268.8
TA(QA)
0.119;-1268.8
A(JQA)
0.133;-1165.6
AA(JQ)
0.097;-1165.6
(QA)(KA)
0.193;-284.4
KKAA
0.097;-856.2
2(25A)
0.021;-4053.1
27(2A)
0.021;-3846.9
(2T)(2A)
0.056;-2862.5
2(2KA)
0.040;-3228.1
(236A)
0.014;-4521.9
(23TA)
0.020;-4109.4
33(2A)
0.016;-4156.2
(36)(2A)
0.026;-3846.9
3(29A)
0.021;-4212.5
3J(2A)
0.023;-4006.3
(245A)
0.016;-4521.9
(249A)
0.020;-4109.4
(24KA)
0.034;-3696.9
46(2A)
0.017;-4418.8
(49)(2A)
0.047;-3434.4
4(2QA)
0.030;-3800.0
6(25A)
0.019;-4315.6
T(25A)
0.030;-3903.1
5(26A)
0.015;-4315.6
58(2A)
0.019;-4109.4
(5J)(2A)
0.034;-3125.0
6(26A)
0.034;-3537.5
T(26A)
0.020;-3800.0
6(27A)
0.018;-4109.4
69(2A)
0.024;-3903.1
(6Q)(2A)
0.040;-2918.8
(279A)
0.027;-3800.0
(27KA)
0.034;-3387.5
79(2A)
0.036;-3800.0
(7Q)(2A)
0.054;-2815.6
(28TA)
0.030;-3593.8
88(2A)
0.060;-3125.0
(8J)(2A)
0.044;-2815.6
9(29A)
0.041;-2918.8
K(29A)
0.046;-3181.3
9(2QA)
0.048;-3284.4
J(2TA)
0.041;-3284.4
TJ(2A)
0.037;-3284.4
(2JQA)
0.041;-3078.1
J(2KA)
0.049;-2975.0
(QK)(2A)
0.068;-2196.9
22(4A)
0.019;-4156.2
226A
0.013;-4625.0
2A(29)
0.037;-3640.6
22(QA)
0.036;-3331.3
2(34A)
0.010;-4728.1
26(3A)
0.016;-4521.9
(29)(3A)
0.033;-3537.5
2(3QA)
0.032;-3903.1
A(234)
0.012;-4728.1
(23)(7A)
0.029;-3743.8
9A(23)
0.019;-4212.5
A(23Q)
0.032;-3903.1
2A(34)
0.016;-4728.1
2A(36)
0.016;-4521.9
2A(38)
0.015;-4315.6
2A(3T)
0.027;-4109.4
2A(3Q)
0.022;-3903.1
2(45A)
0.014;-4521.9
27(4A)
0.018;-4315.6
(2T)(4A)
0.047;-3331.3
2(4KA)
0.026;-3696.9
A(246)
0.021;-4418.8
(24)(9A)
0.035;-3434.4
JA(24)
0.022;-3903.1
24(5A)
0.019;-4521.9
24(7A)
0.018;-4315.6
24(9A)
0.018;-4109.4
24(JA)
0.025;-3903.1
24(KA)
0.033;-3696.9
26(5A)
0.019;-4315.6
(29)(5A)
0.037;-3331.3
2(5QA)
0.031;-3696.9
A(256)
0.019;-4315.6
(25)(9A)
0.029;-3331.3
JA(25)
0.023;-3800.0
25(6A)
0.024;-4315.6
25(8A)
0.028;-4109.4
25(TA)
0.023;-3903.1
25(QA)
0.023;-3696.9
(26)(6A)
0.053;-2862.5
2(69A)
0.028;-3903.1
2J(6A)
0.030;-3696.9
(26)(7A)
0.028;-3434.4
9A(26)
0.032;-3903.1
A(26Q)
0.033;-3593.8
2A(67)
0.026;-4109.4
2A(69)
0.029;-3903.1
2A(6J)
0.029;-3696.9
2A(6K)
0.032;-3490.6
(29)(7A)
0.041;-3125.0
2(7QA)
0.030;-3490.6
A(278)
0.028;-3903.1
(27)(JA)
0.051;-2918.8
KA(27)
0.040;-3387.5
2A(79)
0.024;-3800.0
2A(7J)
0.031;-3593.8
2A(7K)
0.030;-3387.5
(2T)(8A)
0.040;-2918.8
2(8KA)
0.037;-3284.4
A(28T)
0.033;-3593.8
(28)(KA)
0.052;-2609.4
28(TA)
0.032;-3593.8
28(QA)
0.035;-3387.5
(29)(9A)
0.085;-2243.8
2(9QA)
0.036;-3284.4
A(29T)
0.035;-3490.6
(29)(KA)
0.064;-2506.2
29(JA)
0.035;-3387.5
29(KA)
0.050;-3181.3
2J(TA)
0.037;-3284.4
(2T)(JA)
0.048;-2609.4
KA(2T)
0.048;-3078.1
2A(TQ)
0.043;-3181.3
2(JQA)
0.049;-3078.1
A(2JQ)
0.033;-3078.1
2A(JQ)
0.035;-3078.1
2(QKA)
0.052;-2871.9
2Q(KA)
0.056;-2871.9
33(3A)
0.038;-3378.1
(36)(3A)
0.052;-3068.8
3(39A)
0.034;-3434.4
3J(3A)
0.051;-3228.1
(345A)
0.013;-4418.8
(349A)
0.017;-4006.3
(34KA)
0.029;-3593.8
46(3A)
0.016;-4315.6
(49)(3A)
0.036;-3331.3
4(3QA)
0.035;-3696.9
6(35A)
0.021;-4212.5
T(35A)
0.030;-3800.0
5(36A)
0.025;-4212.5
58(3A)
0.020;-4006.3
(5J)(3A)
0.050;-3021.9
6(36A)
0.038;-3434.4
T(36A)
0.033;-3696.9
6(37A)
0.032;-4006.3
69(3A)
0.027;-3800.0
(6Q)(3A)
0.038;-2815.6
(379A)
0.037;-3696.9
(37KA)
0.035;-3284.4
79(3A)
0.026;-3696.9
(7Q)(3A)
0.054;-2712.5
(38TA)
0.039;-3490.6
88(3A)
0.039;-3021.9
(8J)(3A)
0.053;-2712.5
9(39A)
0.062;-2815.6
K(39A)
0.054;-3078.1
9(3QA)
0.045;-3181.3
J(3TA)
0.044;-3181.3
TJ(3A)
0.052;-3181.3
(3JQA)
0.036;-2975.0
J(3KA)
0.054;-2871.9
(QK)(3A)
0.079;-2093.7
33(5A)
0.027;-3846.9
337A
0.017;-4315.6
3A(3T)
0.033;-3331.3
33(KA)
0.035;-3021.9
3(46A)
0.018;-4315.6
38(4A)
0.022;-4109.4
(3J)(4A)
0.039;-3125.0
4A(34)
0.030;-3846.9
A(347)
0.024;-4212.5
(34)(TA)
0.042;-3228.1
QA(34)
0.037;-3696.9
345A
0.010;-5093.8
347A
0.010;-4887.5
349A
0.014;-4681.2
34JA
0.018;-4475.0
34KA
0.014;-4268.8
37(5A)
0.024;-4109.4
(3T)(5A)
0.037;-3125.0
3(5KA)
0.044;-3490.6
A(357)
0.023;-4109.4
(35)(TA)
0.051;-3125.0
QA(35)
0.034;-3593.8
356A
0.012;-4887.5
358A
0.014;-4681.2
35TA
0.012;-4475.0
35QA
0.020;-4268.8
(37)(6A)
0.038;-3331.3
3(6TA)
0.031;-3696.9
3Q(6A)
0.034;-3490.6
(36)(8A)
0.038;-3228.1
TA(36)
0.033;-3696.9
A(36K)
0.029;-3387.5
6A(38)
0.020;-3903.1
6A(3T)
0.029;-3696.9
6A(3Q)
0.035;-3490.6
37(7A)
0.039;-3228.1
(3T)(7A)
0.056;-2918.8
3(7KA)
0.035;-3284.4
A(379)
0.028;-3696.9
(37)(QA)
0.046;-2712.5
7A(38)
0.033;-3800.0
7A(3T)
0.044;-3593.8
7A(3Q)
0.039;-3387.5
38(8A)
0.050;-3021.9
(3J)(8A)
0.054;-2712.5
8A(38)
0.033;-3021.9
A(38J)
0.026;-3387.5
388A
0.024;-3696.9
38TA
0.022;-4165.6
38QA
0.019;-3959.4
(3T)(9A)
0.059;-2712.5
3(9KA)
0.044;-3078.1
A(39J)
0.038;-3284.4
399A
0.040;-3490.6
39JA
0.021;-3959.4
39KA
0.027;-3753.1
3Q(TA)
0.045;-3078.1
(3T)(QA)
0.060;-2403.1
TA(3J)
0.045;-3181.3
TA(3K)
0.060;-2975.0
3(JKA)
0.063;-2871.9
A(3JK)
0.053;-2871.9
JA(3K)
0.047;-2871.9
QA(3Q)
0.069;-2196.9
3QKA
0.034;-3443.7
45(4A)
0.023;-3640.6
(48)(4A)
0.050;-2656.3
4(4JA)
0.050;-3021.9
4K(4A)
0.047;-2815.6
(459A)
0.026;-3800.0
(45KA)
0.038;-3387.5
57(4A)
0.029;-4006.3
(5T)(4A)
0.042;-3021.9
5(4KA)
0.043;-3387.5
(469A)
0.027;-3696.9
(46KA)
0.033;-3284.4
68(4A)
0.029;-3800.0
(6J)(4A)
0.050;-2815.6
7(47A)
0.041;-3125.0
J(47A)
0.040;-3387.5
78(4A)
0.030;-3696.9
(7J)(4A)
0.055;-2712.5
8(48A)
0.049;-2918.8
Q(48A)
0.041;-3181.3
(8T)(4A)
0.052;-2712.5
8(4KA)
0.040;-3078.1
(49QA)
0.049;-3078.1
9(4JA)
0.042;-3181.3
9K(4A)
0.050;-2975.0
TT(4A)
0.060;-2506.2
(TK)(4A)
0.086;-2196.9
J(4QA)
0.057;-2871.9
K(4QA)
0.062;-2665.6
44(5A)
0.038;-3640.6
447A
0.028;-4109.4
4A(4T)
0.044;-3125.0
44(KA)
0.065;-2815.6
4(57A)
0.019;-4006.3
49(5A)
0.028;-3800.0
(4Q)(5A)
0.051;-2815.6
6A(45)
0.024;-4109.4
A(459)
0.026;-3800.0
(45)(QA)
0.057;-2815.6
5A(46)
0.020;-4109.4
5A(48)
0.031;-3903.1
5A(4T)
0.034;-3696.9
5A(4Q)
0.029;-3490.6
46(6A)
0.035;-3331.3
(49)(6A)
0.045;-3021.9
4(6QA)
0.040;-3387.5
A(467)
0.027;-3903.1
(46)(TA)
0.044;-2918.8
QA(46)
0.028;-3387.5
467A
0.014;-4578.1
469A
0.022;-4371.9
46JA
0.015;-4165.6
46KA
0.022;-3959.4
49(7A)
0.039;-3593.8
(4Q)(7A)
0.051;-2609.4
8A(47)
0.034;-3696.9
A(47J)
0.043;-3387.5
477A
0.026;-3800.0
479A
0.019;-4268.8
47JA
0.020;-4062.5
47KA
0.025;-3856.2
4T(8A)
0.030;-3387.5
(4K)(8A)
0.082;-2403.1
TA(48)
0.036;-3387.5
A(48K)
0.046;-3078.1
8A(4T)
0.038;-3387.5
8A(4Q)
0.040;-3181.3
49(9A)
0.053;-2712.5
(4Q)(9A)
0.080;-2403.1
TA(49)
0.029;-3284.4
A(49K)
0.051;-2975.0
9A(4J)
0.042;-3181.3
9A(4K)
0.046;-2975.0
4(TQA)
0.045;-2975.0
A(4TJ)
0.044;-3078.1
4TTA
0.048;-3181.3
4TQA
0.033;-3650.0
(4Q)(JA)
0.071;-2196.9
QA(4J)
0.045;-2871.9
4JQA
0.035;-3546.9
(4K)(QA)
0.087;-1990.6
QA(4K)
0.042;-2665.6
5(56A)
0.048;-3331.3
58(5A)
0.043;-3125.0
(5J)(5A)
0.079;-2140.6
6(56A)
0.035;-3228.1
T(56A)
0.037;-3490.6
6(57A)
0.029;-3800.0
69(5A)
0.028;-3593.8
(6Q)(5A)
0.055;-2609.4
(579A)
0.029;-3490.6
(57KA)
0.038;-3078.1
79(5A)
0.034;-3490.6
(7Q)(5A)
0.050;-2506.2
(58TA)
0.034;-3284.4
88(5A)
0.051;-2815.6
(8J)(5A)
0.063;-2506.2
9(59A)
0.052;-2609.4
K(59A)
0.049;-2871.9
9(5QA)
0.060;-2975.0
J(5TA)
0.046;-2975.0
TJ(5A)
0.045;-2975.0
(5JQA)
0.041;-2768.8
J(5KA)
0.070;-2665.6
(QK)(5A)
0.086;-1887.5
55(7A)
0.037;-3228.1
559A
0.028;-3696.9
5A(5Q)
0.055;-2712.5
(57)(6A)
0.034;-3125.0
5(6TA)
0.035;-3490.6
5Q(6A)
0.050;-3284.4
(56)(8A)
0.039;-3021.9
TA(56)
0.030;-3490.6
A(56K)
0.042;-3181.3
6A(58)
0.036;-3696.9
6A(5T)
0.037;-3490.6
6A(5Q)
0.038;-3284.4
57(7A)
0.037;-3021.9
(5T)(7A)
0.057;-2712.5
5(7KA)
0.050;-3078.1
A(579)
0.034;-3490.6
(57)(QA)
0.064;-2506.2
7A(58)
0.040;-3593.8
7A(5T)
0.035;-3387.5
7A(5Q)
0.036;-3181.3
58(8A)
0.049;-2815.6
(5J)(8A)
0.059;-2506.2
8A(58)
0.057;-2815.6
A(58J)
0.036;-3181.3
588A
0.038;-3490.6
58TA
0.026;-3959.4
58QA
0.031;-3753.1
(5T)(9A)
0.066;-2506.2
5(9KA)
0.036;-2871.9
A(59J)
0.046;-3078.1
599A
0.032;-3284.4
59JA
0.026;-3753.1
59KA
0.031;-3546.9
5Q(TA)
0.043;-2871.9
(5T)(QA)
0.079;-2196.9
TA(5J)
0.043;-2975.0
TA(5K)
0.060;-2768.8
5(JKA)
0.056;-2665.6
A(5JK)
0.047;-2665.6
JA(5K)
0.060;-2665.6
QA(5Q)
0.088;-1990.6
5QKA
0.040;-3237.5
67(6A)
0.044;-3021.9
(6T)(6A)
0.061;-2037.5
6(6KA)
0.059;-2403.1
(67TA)
0.036;-3284.4
77(6A)
0.044;-2918.8
(7T)(6A)
0.051;-2609.4
7(6KA)
0.043;-2975.0
(68JA)
0.046;-3078.1
(89)(6A)
0.066;-2609.4
8(6QA)
0.045;-2975.0
T(69A)
0.037;-3078.1
9(6TA)
0.035;-3078.1
9Q(6A)
0.050;-2871.9
Q(6TA)
0.044;-2768.8
(TQ)(6A)
0.086;-2093.7
(6JKA)
0.049;-2562.5
JK(6A)
0.057;-2562.5
K(6KA)
0.080;-1681.3
668A
0.029;-3593.8
6A(6J)
0.062;-2609.4
(67)(7A)
0.063;-2243.8
6(7TA)
0.043;-3284.4
6Q(7A)
0.042;-3078.1
(67)(9A)
0.052;-2712.5
JA(67)
0.042;-3181.3
67(8A)
0.029;-3490.6
67(TA)
0.036;-3284.4
67(QA)
0.041;-3078.1
(68)(8A)
0.081;-2037.5
6(8JA)
0.043;-3078.1
6K(8A)
0.055;-2871.9
(68)(JA)
0.060;-2403.1
KA(68)
0.054;-2871.9
6A(8T)
0.043;-3181.3
6A(8Q)
0.045;-2975.0
6(9TA)
0.054;-3078.1
6Q(9A)
0.041;-2871.9
(69)(JA)
0.078;-2300.0
KA(69)
0.045;-2768.8
6A(9J)
0.054;-2975.0
6A(9K)
0.038;-2768.8
(6Q)(TA)
0.055;-2093.7
JA(6T)
0.052;-2871.9
6T(JA)
0.057;-2871.9
6T(KA)
0.053;-2665.6
6Q(JA)
0.055;-2665.6
(6J)(KA)
0.081;-1887.5
6J(KA)
0.063;-2562.5
6K(QA)
0.077;-2459.4
6A(QK)
0.054;-2459.4
(78)(7A)
0.082;-2037.5
7(7JA)
0.075;-2403.1
7K(7A)
0.061;-2196.9
(78QA)
0.056;-2871.9
8(7TA)
0.030;-3078.1
8Q(7A)
0.059;-2871.9
J(79A)
0.051;-2871.9
9T(7A)
0.033;-2975.0
(9K)(7A)
0.080;-1990.6
K(7TA)
0.074;-2562.5
T(7KA)
0.060;-2562.5
JJ(7A)
0.080;-1990.6
(7QKA)
0.048;-2356.3
777A
0.045;-2815.6
7A(7T)
0.065;-2506.2
77(KA)
0.081;-2196.9
7(8TA)
0.044;-3078.1
7Q(8A)
0.050;-2871.9
(78)(TA)
0.057;-2403.1
QA(78)
0.061;-2871.9
789A
0.031;-3856.2
78JA
0.032;-3650.0
78KA
0.041;-3443.7
7J(9A)
0.047;-2871.9
(79)(TA)
0.077;-2300.0
QA(79)
0.055;-2768.8
79TA
0.028;-3650.0
79QA
0.030;-3443.7
(7J)(TA)
0.071;-2093.7
TA(7T)
0.071;-2196.9
A(7TK)
0.050;-2562.5
TA(7Q)
0.051;-2665.6
7J(JA)
0.088;-1990.6
(7J)(QA)
0.073;-1887.5
JA(7Q)
0.066;-2562.5
7Q(QA)
0.092;-1784.4
7QQA
0.078;-2459.4
7KKA
0.073;-2253.1
8(8JA)
0.082;-2196.9
8K(8A)
0.058;-1990.6
(89KA)
0.066;-2562.5
9J(8A)
0.051;-2768.8
(8TJA)
0.055;-2665.6
(TJ)(8A)
0.064;-1990.6
J(8JA)
0.092;-1887.5
JQ(8A)
0.058;-2459.4
Q(8KA)
0.066;-2253.1
889A
0.057;-3078.1
8A(8Q)
0.072;-2093.7
(8T)(9A)
0.083;-2196.9
8(9KA)
0.059;-2562.5
A(89J)
0.048;-2768.8
899A
0.047;-2975.0
89JA
0.044;-3443.7
89KA
0.039;-3237.5
8Q(TA)
0.045;-2562.5
(8T)(QA)
0.092;-1887.5
TA(8J)
0.051;-2665.6
TA(8K)
0.064;-2459.4
8(JKA)
0.064;-2356.3
A(8JK)
0.049;-2356.3
JA(8K)
0.068;-2356.3
QA(8Q)
0.103;-1681.3
8QKA
0.043;-2928.1
9T(9A)
0.091;-2093.7
(9K)(9A)
0.102;-1109.4
K(9TA)
0.058;-2356.3
T(9KA)
0.067;-2356.3
JJ(9A)
0.109;-1784.4
(9QKA)
0.063;-2150.0
999A
0.079;-2196.9
9A(9Q)
0.083;-1887.5
(9J)(TA)
0.069;-1887.5
TA(9T)
0.085;-1990.6
A(9TK)
0.076;-2356.3
TA(9Q)
0.049;-2459.4
9J(JA)
0.108;-1784.4
(9J)(QA)
0.077;-1681.3
JA(9Q)
0.077;-2356.3
9Q(QA)
0.090;-1578.1
9QQA
0.064;-2253.1
9KKA
0.076;-2046.9
T(TKA)
0.090;-1578.1
JJ(TA)
0.090;-1681.3
(TQKA)
0.085;-2046.9
TTTA
0.066;-1887.5
TA(TK)
0.089;-1578.1
(TK)(JA)
0.082;-1475.0
KA(TJ)
0.072;-2150.0
TA(JK)
0.073;-2150.0
(TQ)(KA)
0.084;-1371.9
(TK)(KA)
0.133;-593.8
J(JKA)
0.117;-1371.9
(QK)(JA)
0.100;-1268.7
JJ(KA)
0.090;-1371.9
QA(JQ)
0.087;-1371.9
JQKA
0.050;-2618.8
QK(QA)
0.099;-1165.6
QK(KA)
0.105;-1062.5
22(24)
0.015;-4718.8
22(28)
0.015;-4306.2
22(2Q)
0.032;-3893.8
24(23)
0.007;-5290.6
(23)(27)
0.026;-4306.2
2(23T)
0.016;-4671.9
2Q(23)
0.017;-4465.6
23(25)
0.007;-5187.5
2237
0.005;-5656.3
22(3T)
0.012;-4671.9
23(2K)
0.019;-4362.5
2(246)
0.010;-4981.3
28(24)
0.010;-4775.0
(24)(2J)
0.030;-3790.6
2244
0.008;-5187.5
22(47)
0.011;-4878.1
24(2T)
0.013;-4568.8
224Q
0.011;-5037.5
26(25)
0.014;-4878.1
(25)(29)
0.029;-3893.8
2(25Q)
0.020;-4259.4
22(56)
0.011;-4878.1
25(29)
0.014;-4568.8
225J
0.009;-5037.5
26(26)
0.021;-4100.0
(26)(29)
0.025;-3790.6
2(26Q)
0.020;-4156.2
22(67)
0.012;-4671.9
26(2T)
0.019;-4362.5
226Q
0.011;-4831.3
28(27)
0.023;-4465.6
(27)(2J)
0.032;-3481.3
2277
0.012;-4568.8
22(7T)
0.019;-4259.4
27(2K)
0.027;-3950.0
2(28T)
0.017;-4156.2
2Q(28)
0.020;-3950.0
28(2T)
0.019;-4156.2
228Q
0.011;-4625.0
2T(29)
0.023;-4053.1
(29)(2K)
0.047;-3068.8
229J
0.014;-4625.0
2T(2T)
0.040;-3275.0
(2T)(2K)
0.044;-2965.6
22TQ
0.017;-4418.8
2Q(2J)
0.037;-3640.6
2J(2K)
0.034;-3537.5
22QQ
0.029;-3537.5
3(234)
0.007;-5187.5
36(23)
0.009;-4981.3
(23)(39)
0.021;-3996.9
3(23Q)
0.017;-4362.5
5(234)
0.004;-5656.3
9(234)
0.009;-5243.8
K(234)
0.012;-4831.3
4(237)
0.007;-5450.0
49(23)
0.006;-5243.8
(23)(4Q)
0.018;-4259.4
(2357)
0.005;-5346.9
(235J)
0.010;-4934.4
(23)(56)
0.016;-4775.0
5(239)
0.007;-5140.6
5J(23)
0.010;-4934.4
(2367)
0.006;-5243.8
(236J)
0.013;-4831.3
(23)(67)
0.013;-4568.8
6(23T)
0.010;-4934.4
6Q(23)
0.012;-4728.1
9(237)
0.011;-4934.4
K(237)
0.014;-4521.9
7(23T)
0.012;-4831.3
7Q(23)
0.013;-4625.0
T(238)
0.015;-4728.1
8(239)
0.011;-4831.3
8J(23)
0.017;-4625.0
(239T)
0.012;-4625.0
99(23)
0.022;-4053.1
(23)(9Q)
0.027;-3743.8
(23TQ)
0.016;-4315.6
T(23Q)
0.018;-4315.6
Q(23J)
0.021;-4212.5
(23)(JK)
0.039;-3434.4
QK(23)
0.020;-4006.3
23(35)
0.010;-5084.4
33(28)
0.009;-4775.0
233T
0.008;-5243.8
23(3K)
0.022;-4259.4
(24)(36)
0.011;-4878.1
3(249)
0.007;-5243.8
3J(24)
0.008;-5037.5
(34)(25)
0.008;-4981.3
27(34)
0.004;-5450.0
2(34T)
0.009;-5140.6
(34)(2K)
0.023;-4156.2
34(26)
0.005;-5553.1
34(28)
0.006;-5346.9
34(2T)
0.010;-5140.6
34(2Q)
0.010;-4934.4
(25)(35)
0.019;-4203.1
3(258)
0.010;-5243.8
3T(25)
0.008;-5037.5
(25)(3K)
0.022;-4053.1
27(35)
0.007;-5346.9
2(35T)
0.009;-5037.5
(35)(2K)
0.021;-4053.1
35(27)
0.006;-5346.9
35(29)
0.009;-5140.6
35(2J)
0.009;-4934.4
35(2K)
0.016;-4728.1
37(26)
0.007;-5243.8
(26)(3T)
0.017;-4259.4
3(26K)
0.014;-4625.0
2(368)
0.007;-5140.6
(36)(2J)
0.019;-4156.2
2K(36)
0.017;-4625.0
23(68)
0.007;-5140.6
23(6T)
0.012;-4934.4
23(6Q)
0.014;-4728.1
3(278)
0.012;-5037.5
3T(27)
0.010;-4831.3
(27)(3K)
0.027;-3846.9
29(37)
0.010;-4934.4
2(37Q)
0.016;-4625.0
23(78)
0.011;-5037.5
23(7T)
0.014;-4831.3
23(7Q)
0.014;-4625.0
3(289)
0.010;-4831.3
3J(28)
0.015;-4625.0
(38)(29)
0.025;-4156.2
2J(38)
0.013;-4625.0
38(29)
0.012;-4831.3
38(2J)
0.015;-4625.0
38(2K)
0.018;-4418.8
3T(29)
0.015;-4625.0
(29)(3K)
0.032;-3640.6
2J(39)
0.022;-4521.9
39(2T)
0.021;-4625.0
39(2Q)
0.017;-4418.8
(2T)(3T)
0.050;-3171.9
3(2TK)
0.020;-4212.5
2(3TQ)
0.017;-4315.6
23(TJ)
0.020;-4418.8
23(TK)
0.021;-4212.5
(2J)(3K)
0.033;-3434.4
2K(3J)
0.021;-4109.4
23(JK)
0.017;-4109.4
(3Q)(2K)
0.034;-3331.3
(2K)(3K)
0.049;-2553.1
4(246)
0.012;-4775.0
48(24)
0.014;-4568.8
(24)(4J)
0.027;-3584.4
5(245)
0.012;-4775.0
9(245)
0.008;-5037.5
K(245)
0.016;-4625.0
5(248)
0.008;-5140.6
5T(24)
0.009;-4934.4
(24)(5K)
0.024;-3950.0
9(246)
0.013;-4934.4
K(246)
0.018;-4521.9
6(249)
0.011;-4934.4
6J(24)
0.013;-4728.1
(2478)
0.010;-4934.4
(247Q)
0.013;-4521.9
7(249)
0.014;-4831.3
7J(24)
0.020;-4625.0
(2489)
0.015;-4728.1
(248K)
0.017;-4315.6
8T(24)
0.013;-4625.0
(24)(8K)
0.030;-3640.6
Q(249)
0.015;-4315.6
(24)(9J)
0.027;-3743.8
T(24T)
0.032;-3743.8
T(24J)
0.017;-4315.6
TK(24)
0.019;-4109.4
(24)(JQ)
0.031;-3434.4
QQ(24)
0.033;-3331.3
24(45)
0.013;-4878.1
44(28)
0.013;-4568.8
244T
0.009;-5037.5
24(4K)
0.022;-4053.1
(25)(47)
0.014;-4568.8
4(25T)
0.012;-4934.4
4Q(25)
0.013;-4728.1
(45)(27)
0.013;-4568.8
29(45)
0.009;-5037.5
2(45Q)
0.011;-4728.1
24(56)
0.007;-5346.9
24(58)
0.008;-5140.6
24(5T)
0.009;-4934.4
24(5Q)
0.014;-4728.1
4(267)
0.009;-5140.6
49(26)
0.008;-4934.4
(26)(4Q)
0.025;-3950.0
27(46)
0.010;-5140.6
2(46T)
0.010;-4831.3
(46)(2K)
0.022;-3846.9
46(28)
0.008;-5037.5
46(2T)
0.011;-4831.3
46(2Q)
0.014;-4625.0
(27)(47)
0.029;-3687.5
4(27T)
0.010;-4728.1
4Q(27)
0.011;-4521.9
(47)(29)
0.023;-4156.2
2J(47)
0.015;-4625.0
47(28)
0.009;-4934.4
47(2T)
0.014;-4728.1
47(2Q)
0.018;-4521.9
(28)(48)
0.038;-3481.3
4(28J)
0.013;-4521.9
4K(28)
0.021;-4315.6
(48)(2J)
0.021;-3846.9
2K(48)
0.020;-4315.6
24(8T)
0.014;-4625.0
24(8Q)
0.022;-4418.8
4(29T)
0.014;-4521.9
4Q(29)
0.017;-4315.6
(49)(2J)
0.027;-3743.8
2K(49)
0.018;-4212.5
24(9J)
0.016;-4418.8
24(9K)
0.017;-4212.5
(2T)(4Q)
0.030;-3537.5
2J(4T)
0.015;-4315.6
4T(2J)
0.017;-4315.6
4T(2K)
0.020;-4109.4
4Q(2J)
0.017;-4109.4
(4J)(2K)
0.035;-3331.3
4J(2K)
0.027;-4006.3
4K(2Q)
0.027;-3903.1
24(QK)
0.023;-3903.1
(25)(56)
0.029;-3893.8
5(259)
0.021;-4259.4
5J(25)
0.024;-4053.1
(2567)
0.007;-5037.5
(256J)
0.012;-4625.0
(25)(67)
0.015;-4362.5
6(25T)
0.011;-4728.1
6Q(25)
0.017;-4521.9
9(257)
0.010;-4728.1
K(257)
0.016;-4315.6
7(25T)
0.018;-4625.0
7Q(25)
0.015;-4418.8
T(258)
0.015;-4521.9
8(259)
0.012;-4625.0
8J(25)
0.016;-4418.8
(259T)
0.023;-4418.8
99(25)
0.033;-3846.9
(25)(9Q)
0.025;-3537.5
(25TQ)
0.026;-4109.4
T(25Q)
0.016;-4109.4
Q(25J)
0.023;-4006.3
(25)(JK)
0.036;-3228.1
QK(25)
0.037;-3800.0
25(57)
0.020;-4465.6
55(2T)
0.019;-4156.2
255Q
0.011;-4625.0
57(26)
0.007;-5037.5
(26)(5T)
0.029;-4053.1
5(26K)
0.020;-4418.8
2(568)
0.008;-4934.4
(56)(2J)
0.019;-3950.0
2K(56)
0.017;-4418.8
25(68)
0.008;-4934.4
25(6T)
0.010;-4728.1
25(6Q)
0.013;-4521.9
5(278)
0.010;-4831.3
5T(27)
0.015;-4625.0
(27)(5K)
0.022;-3640.6
29(57)
0.011;-4728.1
2(57Q)
0.020;-4418.8
25(78)
0.012;-4831.3
25(7T)
0.015;-4625.0
25(7Q)
0.016;-4418.8
5(289)
0.017;-4625.0
5J(28)
0.016;-4418.8
(58)(29)
0.022;-3950.0
2J(58)
0.021;-4418.8
58(29)
0.017;-4625.0
58(2J)
0.019;-4418.8
58(2K)
0.023;-4212.5
5T(29)
0.020;-4418.8
(29)(5K)
0.036;-3434.4
2J(59)
0.019;-4315.6
59(2T)
0.014;-4418.8
59(2Q)
0.021;-4212.5
(2T)(5T)
0.051;-2965.6
5(2TK)
0.028;-4006.3
2(5TQ)
0.025;-4109.4
25(TJ)
0.019;-4212.5
25(TK)
0.025;-4006.3
(2J)(5K)
0.043;-3228.1
2K(5J)
0.022;-3903.1
25(JK)
0.021;-3903.1
(5Q)(2K)
0.042;-3125.0
(2K)(5K)
0.073;-2346.9
6(268)
0.022;-4156.2
6T(26)
0.022;-3950.0
(26)(6K)
0.040;-2965.6
T(267)
0.015;-4521.9
7(268)
0.010;-4728.1
7T(26)
0.017;-4521.9
(26)(7K)
0.023;-3537.5
J(268)
0.020;-4315.6
89(26)
0.016;-4521.9
(26)(8Q)
0.040;-3537.5
(269J)
0.017;-4212.5
(26)(9T)
0.036;-3640.6
9(26K)
0.024;-4006.3
(26TK)
0.021;-3903.1
TQ(26)
0.031;-4006.3
K(26J)
0.030;-3800.0
Q(26Q)
0.048;-3125.0
KK(26)
0.046;-2918.8
66(29)
0.021;-4053.1
266J
0.020;-4521.9
67(27)
0.022;-4156.2
(27)(6T)
0.024;-3846.9
6(27K)
0.024;-4212.5
2(679)
0.013;-4625.0
(67)(2Q)
0.039;-3640.6
27(68)
0.016;-4728.1
27(6T)
0.013;-4521.9
27(6Q)
0.024;-4315.6
68(28)
0.032;-3950.0
(28)(6J)
0.029;-3640.6
28(68)
0.019;-3950.0
2(68J)
0.022;-4315.6
2688
0.017;-4625.0
268T
0.007;-5093.8
268Q
0.012;-4887.5
(29)(6T)
0.029;-3640.6
6(29K)
0.028;-4006.3
2(69J)
0.019;-4212.5
2699
0.017;-4418.8
269J
0.011;-4887.5
269K
0.011;-4681.2
6Q(2T)
0.033;-4006.3
(6T)(2Q)
0.046;-3331.3
2T(6J)
0.021;-4109.4
2T(6K)
0.026;-3903.1
6(2JK)
0.031;-3800.0
2(6JK)
0.024;-3800.0
2J(6K)
0.031;-3800.0
2Q(6Q)
0.044;-3125.0
26QK
0.018;-4371.9
78(27)
0.028;-3950.0
(27)(7J)
0.048;-2965.6
8(278)
0.026;-3846.9
Q(278)
0.028;-4109.4
(27)(8T)
0.036;-3640.6
8(27K)
0.027;-4006.3
(279Q)
0.026;-4006.3
9(27J)
0.021;-4109.4
9K(27)
0.024;-3903.1
TT(27)
0.039;-3434.4
(27)(TK)
0.042;-3125.0
J(27Q)
0.030;-3800.0
K(27Q)
0.035;-3593.8
77(28)
0.022;-3950.0
277T
0.013;-4418.8
27(7K)
0.028;-3434.4
(28)(7T)
0.033;-3640.6
7(28K)
0.023;-4006.3
2(78T)
0.018;-4315.6
(78)(2K)
0.042;-3331.3
78(2T)
0.021;-4315.6
78(2Q)
0.024;-4109.4
(29)(79)
0.040;-2965.6
7(29Q)
0.025;-4006.3
2(79T)
0.023;-4212.5
(79)(2K)
0.036;-3228.1
79(2J)
0.023;-4109.4
79(2K)
0.026;-3903.1
7J(2T)
0.020;-4006.3
(7T)(2J)
0.032;-3331.3
2K(7T)
0.030;-3800.0
27(TQ)
0.022;-3903.1
7(2JQ)
0.029;-3800.0
2(7JQ)
0.026;-3800.0
27(JQ)
0.033;-3800.0
7(2QK)
0.034;-3593.8
7Q(2K)
0.032;-3593.8
88(28)
0.045;-3068.8
(28)(8J)
0.057;-2759.4
9(289)
0.030;-3537.5
K(289)
0.027;-3800.0
9(28Q)
0.024;-3903.1
J(28T)
0.026;-3903.1
TJ(28)
0.027;-3903.1
(28JQ)
0.038;-3696.9
J(28K)
0.024;-3593.8
(28)(QK)
0.050;-2815.6
88(2T)
0.027;-3537.5
288Q
0.026;-4006.3
8T(29)
0.020;-4109.4
(29)(8K)
0.032;-3125.0
2J(89)
0.026;-4006.3
89(2T)
0.026;-4109.4
89(2Q)
0.028;-3903.1
(2T)(8T)
0.056;-2656.3
8(2TK)
0.034;-3696.9
2(8TQ)
0.027;-3800.0
28(TJ)
0.028;-3903.1
28(TK)
0.030;-3696.9
(2J)(8K)
0.066;-2918.8
2K(8J)
0.027;-3593.8
28(JK)
0.025;-3593.8
(8Q)(2K)
0.050;-2815.6
(2K)(8K)
0.067;-2037.5
9(29J)
0.033;-3228.1
9K(29)
0.043;-3021.9
TT(29)
0.040;-3228.1
(29)(TK)
0.043;-2918.8
J(29Q)
0.026;-3593.8
K(29Q)
0.049;-3387.5
99(2T)
0.039;-3331.3
299Q
0.019;-3800.0
9J(2T)
0.028;-3800.0
(9T)(2J)
0.030;-3125.0
2K(9T)
0.035;-3593.8
29(TQ)
0.039;-3696.9
9(2JQ)
0.024;-3593.8
2(9JQ)
0.031;-3593.8
29(JQ)
0.034;-3593.8
9(2QK)
0.035;-3387.5
9Q(2K)
0.036;-3387.5
TT(2T)
0.055;-2450.0
(2T)(TK)
0.088;-2140.6
J(2TQ)
0.033;-3490.6
K(2TQ)
0.033;-3284.4
TT(2J)
0.045;-3021.9
2TTK
0.031;-3490.6
TK(2J)
0.039;-3387.5
2TJJ
0.031;-3593.8
2TJK
0.030;-4062.5
2(TQK)
0.035;-3284.4
TK(2K)
0.062;-2506.2
(2J)(JK)
0.079;-1934.4
QK(2J)
0.041;-3181.3
2J(JK)
0.055;-2609.4
(JQ)(2K)
0.053;-2506.2
(2K)(JK)
0.088;-1728.1
K(2QK)
0.065;-2300.0
2K(QK)
0.061;-2300.0
3335
0.010;-4981.3
3339
0.020;-4568.8
333K
0.022;-4156.2
36(34)
0.013;-4775.0
(34)(39)
0.023;-3790.6
3(34Q)
0.025;-4156.2
33(45)
0.009;-4878.1
34(38)
0.017;-4568.8
334T
0.011;-5037.5
33(4K)
0.025;-4053.1
(35)(37)
0.026;-3893.8
3(35T)
0.017;-4259.4
3Q(35)
0.023;-4053.1
35(37)
0.016;-4568.8
3359
0.010;-5037.5
33(5Q)
0.029;-4053.1
(36)(37)
0.029;-3790.6
3(36T)
0.023;-4156.2
3Q(36)
0.026;-3950.0
36(38)
0.018;-4362.5
336T
0.009;-4831.3
33(6K)
0.026;-3846.9
(37)(39)
0.040;-3481.3
3(37Q)
0.024;-3846.9
33(78)
0.017;-4259.4
37(3J)
0.027;-3950.0
337K
0.019;-4418.8
3T(38)
0.028;-3950.0
(38)(3K)
0.046;-2965.6
338T
0.014;-4625.0
33(8K)
0.036;-3640.6
(39)(3J)
0.035;-3068.8
3399
0.022;-3950.0
33(9Q)
0.033;-3640.6
(3T)(3J)
0.046;-2965.6
33TT
0.037;-3743.8
33(TK)
0.036;-3434.4
(3J)(3K)
0.052;-2656.3
33JK
0.025;-4006.3
33(QK)
0.032;-3228.1
45(34)
0.014;-4775.0
(34)(48)
0.032;-3790.6
4(34J)
0.022;-4156.2
4K(34)
0.028;-3950.0
(3459)
0.011;-4934.4
(345K)
0.013;-4521.9
57(34)
0.010;-5140.6
(34)(5T)
0.016;-4156.2
5(34K)
0.017;-4521.9
(3469)
0.009;-4831.3
(346K)
0.021;-4418.8
68(34)
0.010;-4934.4
(34)(6J)
0.024;-3950.0
7(347)
0.017;-4259.4
J(347)
0.019;-4521.9
78(34)
0.012;-4831.3
(34)(7J)
0.033;-3846.9
8(348)
0.026;-4053.1
Q(348)
0.020;-4315.6
(34)(8T)
0.025;-3846.9
8(34K)
0.018;-4212.5
(349Q)
0.017;-4212.5
9(34J)
0.019;-4315.6
9K(34)
0.022;-4109.4
TT(34)
0.032;-3640.6
(34)(TK)
0.033;-3331.3
J(34Q)
0.017;-4006.3
K(34Q)
0.019;-3800.0
44(35)
0.012;-4775.0
3447
0.006;-5243.8
34(4T)
0.016;-4259.4
44(3K)
0.023;-3950.0
4(357)
0.012;-5140.6
49(35)
0.011;-4934.4
(35)(4Q)
0.026;-3950.0
36(45)
0.006;-5243.8
3(459)
0.012;-4934.4
(45)(3Q)
0.023;-3950.0
35(46)
0.010;-5243.8
35(48)
0.009;-5037.5
35(4T)
0.009;-4831.3
35(4Q)
0.015;-4625.0
46(36)
0.017;-4465.6
(36)(49)
0.017;-4156.2
4(36Q)
0.012;-4521.9
3(467)
0.010;-5037.5
(46)(3T)
0.025;-4053.1
3Q(46)
0.014;-4521.9
3467
0.004;-5712.5
3469
0.004;-5506.3
346J
0.007;-5300.0
346K
0.008;-5093.8
49(37)
0.015;-4728.1
(37)(4Q)
0.038;-3743.8
38(47)
0.014;-4831.3
3(47J)
0.019;-4521.9
3477
0.010;-4934.4
3479
0.007;-5403.1
347J
0.010;-5196.9
347K
0.009;-4990.6
4T(38)
0.020;-4521.9
(38)(4K)
0.026;-3537.5
3T(48)
0.017;-4521.9
3(48K)
0.022;-4212.5
38(4T)
0.018;-4521.9
38(4Q)
0.021;-4315.6
49(39)
0.031;-3846.9
(39)(4Q)
0.032;-3537.5
3T(49)
0.020;-4418.8
3(49K)
0.027;-4109.4
39(4J)
0.020;-4315.6
39(4K)
0.023;-4109.4
4(3TQ)
0.017;-4109.4
3(4TJ)
0.019;-4212.5
34TT
0.020;-4315.6
34TQ
0.012;-4784.4
(3J)(4Q)
0.041;-3331.3
3Q(4J)
0.027;-4006.3
34JQ
0.013;-4681.2
(3Q)(4K)
0.035;-3125.0
3Q(4K)
0.026;-3800.0
5(356)
0.012;-4465.6
58(35)
0.024;-4259.4
(35)(5J)
0.045;-3275.0
6(356)
0.016;-4362.5
T(356)
0.018;-4625.0
6(357)
0.009;-4934.4
69(35)
0.010;-4728.1
(35)(6Q)
0.030;-3743.8
(3579)
0.017;-4625.0
(357K)
0.025;-4212.5
79(35)
0.016;-4625.0
(35)(7Q)
0.025;-3640.6
(358T)
0.016;-4418.8
88(35)
0.030;-3950.0
(35)(8J)
0.026;-3640.6
9(359)
0.027;-3743.8
K(359)
0.025;-4006.3
9(35Q)
0.022;-4109.4
J(35T)
0.019;-4109.4
TJ(35)
0.024;-4109.4
(35JQ)
0.023;-3903.1
J(35K)
0.030;-3800.0
(35)(QK)
0.041;-3021.9
55(37)
0.020;-4362.5
3559
0.010;-4831.3
35(5Q)
0.019;-3846.9
(36)(57)
0.021;-4259.4
5(36T)
0.017;-4625.0
5Q(36)
0.016;-4418.8
(56)(38)
0.019;-4156.2
3T(56)
0.014;-4625.0
3(56K)
0.020;-4315.6
36(58)
0.013;-4831.3
36(5T)
0.013;-4625.0
36(5Q)
0.016;-4418.8
57(37)
0.020;-4156.2
(37)(5T)
0.025;-3846.9
5(37K)
0.017;-4212.5
3(579)
0.015;-4625.0
(57)(3Q)
0.035;-3640.6
37(58)
0.012;-4728.1
37(5T)
0.016;-4521.9
37(5Q)
0.017;-4315.6
58(38)
0.024;-3950.0
(38)(5J)
0.031;-3640.6
38(58)
0.021;-3950.0
3(58J)
0.020;-4315.6
3588
0.019;-4625.0
358T
0.010;-5093.8
358Q
0.008;-4887.5
(39)(5T)
0.037;-3640.6
5(39K)
0.024;-4006.3
3(59J)
0.021;-4212.5
3599
0.021;-4418.8
359J
0.011;-4887.5
359K
0.015;-4681.2
5Q(3T)
0.022;-4006.3
(5T)(3Q)
0.033;-3331.3
3T(5J)
0.026;-4109.4
3T(5K)
0.021;-3903.1
5(3JK)
0.024;-3800.0
3(5JK)
0.028;-3800.0
3J(5K)
0.029;-3800.0
3Q(5Q)
0.046;-3125.0
35QK
0.019;-4371.9
67(36)
0.024;-4156.2
(36)(6T)
0.050;-3171.9
6(36K)
0.028;-3537.5
(367T)
0.015;-4418.8
77(36)
0.025;-4053.1
(36)(7T)
0.027;-3743.8
7(36K)
0.016;-4109.4
(368J)
0.016;-4212.5
(36)(89)
0.024;-3743.8
8(36Q)
0.019;-4109.4
T(369)
0.022;-4212.5
9(36T)
0.019;-4212.5
9Q(36)
0.022;-4006.3
Q(36T)
0.026;-3903.1
(36)(TQ)
0.036;-3228.1
(36JK)
0.023;-3696.9
JK(36)
0.030;-3696.9
K(36K)
0.047;-2815.6
3668
0.016;-4728.1
36(6J)
0.023;-3743.8
(37)(67)
0.039;-3378.1
6(37T)
0.017;-4418.8
6Q(37)
0.024;-4212.5
(67)(39)
0.023;-3846.9
3J(67)
0.016;-4315.6
67(38)
0.019;-4625.0
67(3T)
0.023;-4418.8
67(3Q)
0.027;-4212.5
(38)(68)
0.035;-3171.9
6(38J)
0.020;-4212.5
6K(38)
0.022;-4006.3
(68)(3J)
0.034;-3537.5
3K(68)
0.024;-4006.3
36(8T)
0.014;-4315.6
36(8Q)
0.023;-4109.4
6(39T)
0.021;-4212.5
6Q(39)
0.019;-4006.3
(69)(3J)
0.036;-3434.4
3K(69)
0.025;-3903.1
36(9J)
0.020;-4109.4
36(9K)
0.029;-3903.1
(3T)(6Q)
0.038;-3228.1
3J(6T)
0.019;-4006.3
6T(3J)
0.028;-4006.3
6T(3K)
0.022;-3800.0
6Q(3J)
0.033;-3800.0
(6J)(3K)
0.043;-3021.9
6J(3K)
0.028;-3696.9
6K(3Q)
0.037;-3593.8
36(QK)
0.037;-3593.8
(37)(78)
0.040;-3171.9
7(37J)
0.028;-3537.5
7K(37)
0.039;-3331.3
(378Q)
0.018;-4006.3
8(37T)
0.024;-4212.5
8Q(37)
0.026;-4006.3
J(379)
0.032;-4006.3
9T(37)
0.028;-4109.4
(37)(9K)
0.033;-3125.0
K(37T)
0.028;-3696.9
T(37K)
0.029;-3696.9
JJ(37)
0.043;-3125.0
(37QK)
0.036;-3490.6
3777
0.030;-3950.0
37(7T)
0.023;-3640.6
77(3K)
0.036;-3331.3
7(38T)
0.016;-4212.5
7Q(38)
0.024;-4006.3
(78)(3T)
0.037;-3537.5
3Q(78)
0.020;-4006.3
3789
0.010;-4990.6
378J
0.012;-4784.4
378K
0.018;-4578.1
7J(39)
0.018;-4006.3
(79)(3T)
0.037;-3434.4
3Q(79)
0.027;-3903.1
379T
0.014;-4784.4
379Q
0.016;-4578.1
(3T)(7J)
0.040;-3228.1
3T(7T)
0.040;-3331.3
3(7TK)
0.039;-3696.9
3T(7Q)
0.032;-3800.0
7J(3J)
0.046;-3125.0
(7J)(3Q)
0.040;-3021.9
3J(7Q)
0.030;-3696.9
7Q(3Q)
0.046;-2918.8
37QQ
0.027;-3593.8
37KK
0.037;-3387.5
8(38J)
0.038;-3331.3
8K(38)
0.036;-3125.0
(389K)
0.029;-3696.9
9J(38)
0.027;-3903.1
(38TJ)
0.030;-3800.0
(38)(TJ)
0.045;-3125.0
J(38J)
0.047;-3021.9
JQ(38)
0.040;-3593.8
Q(38K)
0.038;-3387.5
3889
0.026;-4212.5
38(8Q)
0.039;-3228.1
(39)(8T)
0.052;-3331.3
8(39K)
0.025;-3696.9
3(89J)
0.025;-3903.1
3899
0.022;-4109.4
389J
0.016;-4578.1
389K
0.016;-4371.9
8Q(3T)
0.021;-3696.9
(8T)(3Q)
0.049;-3021.9
3T(8J)
0.025;-3800.0
3T(8K)
0.029;-3593.8
8(3JK)
0.035;-3490.6
3(8JK)
0.030;-3490.6
3J(8K)
0.034;-3490.6
3Q(8Q)
0.043;-2815.6
38QK
0.024;-4062.5
9T(39)
0.036;-3228.1
(39)(9K)
0.092;-2243.8
K(39T)
0.031;-3490.6
T(39K)
0.042;-3490.6
JJ(39)
0.053;-2918.8
(39QK)
0.047;-3284.4
3999
0.046;-3331.3
39(9Q)
0.038;-3021.9
(3T)(9J)
0.041;-3021.9
3T(9T)
0.046;-3125.0
3(9TK)
0.025;-3490.6
3T(9Q)
0.032;-3593.8
9J(3J)
0.044;-2918.8
(9J)(3Q)
0.049;-2815.6
3J(9Q)
0.031;-3490.6
9Q(3Q)
0.057;-2712.5
39QQ
0.040;-3387.5
39KK
0.045;-3181.3
T(3TK)
0.041;-2712.5
JJ(3T)
0.046;-2815.6
(3TQK)
0.039;-3181.3
3TTT
0.052;-3021.9
3T(TK)
0.051;-2712.5
(3J)(TK)
0.052;-2609.4
3K(TJ)
0.036;-3284.4
3T(JK)
0.036;-3284.4
(TQ)(3K)
0.065;-2506.2
(3K)(TK)
0.075;-1728.1
J(3JK)
0.046;-2506.2
(3J)(QK)
0.068;-2403.1
JJ(3K)
0.053;-2506.2
3Q(JQ)
0.067;-2506.2
3JQK
0.024;-3753.1
QK(3Q)
0.080;-2300.0
QK(3K)
0.077;-2196.9
44(46)
0.033;-3893.8
44(4T)
0.030;-3481.2
(45)(45)
0.036;-3218.8
4(458)
0.021;-4259.4
4T(45)
0.019;-4053.1
(45)(4K)
0.052;-3068.8
4457
0.010;-5037.5
44(5T)
0.026;-4053.1
45(4K)
0.029;-3743.8
4(468)
0.020;-4156.2
4T(46)
0.021;-3950.0
(46)(4K)
0.048;-2965.6
4468
0.014;-4831.3
44(6J)
0.020;-3846.9
(47)(47)
0.051;-2806.3
4(47T)
0.024;-3846.9
4Q(47)
0.037;-3640.6
47(49)
0.022;-3950.0
447J
0.018;-4418.8
48(48)
0.044;-3275.0
(48)(4J)
0.053;-2965.6
4488
0.026;-3950.0
44(8J)
0.038;-3640.6
(49)(49)
0.053;-2393.8
4(49Q)
0.029;-3434.4
44(9T)
0.027;-3640.6
49(4K)
0.038;-3331.3
4(4TQ)
0.046;-3331.3
44(TJ)
0.046;-3434.4
(4J)(4J)
0.061;-1981.3
44JJ
0.041;-3331.3
4Q(4Q)
0.054;-2450.0
(4K)(4K)
0.093;-1568.8
(45)(57)
0.037;-3584.4
5(45T)
0.027;-3950.0
5Q(45)
0.026;-3743.8
8(456)
0.013;-4728.1
Q(456)
0.014;-4315.6
(45)(68)
0.026;-4053.1
6(45J)
0.018;-4418.8
6K(45)
0.017;-4212.5
(457J)
0.021;-4315.6
(45)(78)
0.030;-3950.0
7(45J)
0.019;-4315.6
7K(45)
0.022;-4109.4
(458Q)
0.023;-4109.4
8(45T)
0.017;-4315.6
8Q(45)
0.020;-4109.4
J(459)
0.023;-4109.4
9T(45)
0.017;-4212.5
(45)(9K)
0.039;-3228.1
K(45T)
0.030;-3800.0
T(45K)
0.024;-3800.0
JJ(45)
0.037;-3228.1
(45QK)
0.036;-3593.8
4555
0.015;-4465.6
45(58)
0.021;-4156.2
55(4J)
0.021;-3846.9
455K
0.019;-4315.6
58(46)
0.013;-4728.1
(46)(5J)
0.024;-3743.8
46(56)
0.017;-4259.4
4(569)
0.015;-4625.0
(56)(4Q)
0.028;-3640.6
46(57)
0.013;-4831.3
46(59)
0.013;-4625.0
46(5J)
0.014;-4418.8
46(5K)
0.024;-4212.5
5(479)
0.018;-4521.9
5J(47)
0.021;-4315.6
(57)(48)
0.030;-3950.0
4T(57)
0.020;-4418.8
4(57K)
0.019;-4109.4
47(59)
0.019;-4521.9
47(5J)
0.019;-4315.6
47(5K)
0.028;-4109.4
5(48T)
0.023;-4315.6
5Q(48)
0.022;-4109.4
(58)(4T)
0.033;-3640.6
4Q(58)
0.027;-4109.4
4589
0.009;-5093.8
458J
0.010;-4887.5
458K
0.015;-4681.2
5J(49)
0.020;-4109.4
(59)(4T)
0.035;-3537.5
4Q(59)
0.018;-4006.3
459T
0.013;-4887.5
459Q
0.015;-4681.2
(4T)(5J)
0.029;-3331.3
4T(5T)
0.048;-3434.4
4(5TK)
0.035;-3800.0
4T(5Q)
0.026;-3903.1
5J(4J)
0.041;-3228.1
(5J)(4Q)
0.036;-3125.0
4J(5Q)
0.028;-3800.0
5Q(4Q)
0.058;-3021.9
45QQ
0.031;-3696.9
45KK
0.030;-3490.6
6(469)
0.029;-3846.9
6J(46)
0.029;-3640.6
(4678)
0.014;-4521.9
(467Q)
0.021;-4109.4
7(469)
0.016;-4418.8
7J(46)
0.017;-4212.5
(4689)
0.016;-4315.6
(468K)
0.025;-3903.1
8T(46)
0.022;-4212.5
(46)(8K)
0.043;-3228.1
Q(469)
0.021;-3903.1
(46)(9J)
0.039;-3331.3
T(46T)
0.045;-3331.3
T(46J)
0.024;-3903.1
TK(46)
0.038;-3696.9
(46)(JQ)
0.045;-3021.9
QQ(46)
0.055;-2918.8
46(67)
0.019;-4053.1
66(4T)
0.028;-3743.8
466Q
0.015;-4212.5
68(47)
0.015;-4521.9
(47)(6J)
0.033;-3537.5
47(67)
0.031;-3950.0
4(67T)
0.016;-4315.6
(67)(4K)
0.036;-3331.3
67(49)
0.021;-4418.8
67(4J)
0.020;-4212.5
67(4K)
0.023;-4006.3
69(48)
0.020;-4315.6
(48)(6Q)
0.030;-3331.3
49(68)
0.019;-4315.6
4(68Q)
0.028;-4006.3
46(89)
0.017;-4315.6
46(8J)
0.023;-4109.4
46(8K)
0.025;-3903.1
(49)(6J)
0.038;-3331.3
49(69)
0.032;-3537.5
4(69Q)
0.024;-3903.1
46(9T)
0.022;-4109.4
46(9Q)
0.022;-3903.1
6(4TJ)
0.024;-3903.1
6K(4T)
0.026;-3696.9
(6T)(4K)
0.046;-3021.9
6T(4Q)
0.038;-3800.0
(4J)(6J)
0.069;-2450.0
4J(6J)
0.045;-3125.0
6J(4Q)
0.034;-3696.9
(4Q)(6Q)
0.070;-2243.8
4K(6Q)
0.029;-3490.6
4K(6K)
0.061;-2712.5
79(47)
0.025;-3640.6
(47)(7Q)
0.073;-2656.3
(478T)
0.022;-4109.4
88(47)
0.026;-3640.6
(47)(8J)
0.040;-3331.3
9(479)
0.040;-3434.4
K(479)
0.032;-3696.9
9(47Q)
0.024;-3800.0
J(47T)
0.031;-3800.0
TJ(47)
0.029;-3800.0
(47JQ)
0.031;-3593.8
J(47K)
0.038;-3490.6
(47)(QK)
0.047;-2712.5
77(49)
0.025;-3640.6
477J
0.018;-4109.4
78(48)
0.027;-3640.6
(48)(7J)
0.039;-3331.3
48(78)
0.030;-3640.6
4(78J)
0.024;-4006.3
4788
0.015;-4315.6
478T
0.013;-4784.4
478Q
0.014;-4578.1
(49)(7T)
0.049;-3331.3
7(49K)
0.026;-3696.9
4(79J)
0.020;-3903.1
4799
0.023;-4109.4
479J
0.014;-4578.1
479K
0.017;-4371.9
7Q(4T)
0.030;-3696.9
(7T)(4Q)
0.046;-3021.9
4T(7J)
0.033;-3800.0
4T(7K)
0.031;-3593.8
7(4JK)
0.044;-3490.6
4(7JK)
0.030;-3490.6
4J(7K)
0.030;-3490.6
4Q(7Q)
0.054;-2815.6
47QK
0.023;-4062.5
89(48)
0.028;-3434.4
(48)(8Q)
0.068;-2450.0
(489J)
0.027;-3800.0
(48)(9T)
0.044;-3228.1
9(48K)
0.041;-3593.8
(48TK)
0.036;-3490.6
TQ(48)
0.027;-3593.8
K(48J)
0.036;-3387.5
Q(48Q)
0.049;-2712.5
KK(48)
0.061;-2506.2
88(4J)
0.045;-3228.1
488K
0.029;-3696.9
8J(49)
0.034;-3800.0
(89)(4T)
0.050;-3228.1
4Q(89)
0.031;-3696.9
489T
0.017;-4578.1
489Q
0.022;-4371.9
(4T)(8J)
0.033;-3021.9
4T(8T)
0.035;-3125.0
4(8TK)
0.030;-3490.6
4T(8Q)
0.030;-3593.8
8J(4J)
0.044;-2918.8
(8J)(4Q)
0.038;-2815.6
4J(8Q)
0.038;-3490.6
8Q(4Q)
0.054;-2712.5
48QQ
0.037;-3387.5
48KK
0.046;-3181.3
9(49Q)
0.058;-2918.8
J(49T)
0.031;-3593.8
TJ(49)
0.032;-3593.8
(49JQ)
0.034;-3387.5
J(49K)
0.047;-3284.4
(49)(QK)
0.053;-2506.2
99(4J)
0.037;-3021.9
499K
0.032;-3490.6
9Q(4T)
0.033;-3490.6
(9T)(4Q)
0.047;-2815.6
4T(9J)
0.031;-3593.8
4T(9K)
0.041;-3387.5
9(4JK)
0.034;-3284.4
4(9JK)
0.047;-3284.4
4J(9K)
0.040;-3284.4
4Q(9Q)
0.079;-2609.4
49QK
0.029;-3856.2
TJ(4T)
0.040;-2815.6
(4TJQ)
0.042;-3284.4
J(4TK)
0.036;-3181.3
(4T)(QK)
0.057;-2403.1
TT(4Q)
0.047;-2712.5
T(4JQ)
0.038;-3284.4
4(TJQ)
0.039;-3284.4
4T(JQ)
0.040;-3284.4
T(4QK)
0.042;-3078.1
TQ(4K)
0.042;-3078.1
JJ(4J)
0.081;-1934.4
(4JQK)
0.038;-2975.0
4JJJ
0.070;-2609.4
JQ(4Q)
0.057;-2403.1
4JQQ
0.046;-3078.1
4JKK
0.042;-2871.9
QQ(4K)
0.090;-2196.9
4KKK
0.084;-1990.6
55(59)
0.046;-3275.0
55(5K)
0.044;-2862.5
(56)(58)
0.047;-3275.0
5(56J)
0.027;-3640.6
5K(56)
0.045;-3434.4
56(59)
0.028;-3846.9
556J
0.017;-4315.6
57(57)
0.030;-3275.0
(57)(5T)
0.060;-2965.6
5(57K)
0.043;-3331.3
55(79)
0.028;-3743.8
57(5Q)
0.033;-3434.4
5(589)
0.028;-3640.6
5J(58)
0.035;-3434.4
58(59)
0.031;-3640.6
558J
0.017;-4109.4
59(59)
0.057;-2862.5
(59)(5Q)
0.058;-2553.1
559T
0.028;-4109.4
55(9K)
0.042;-3125.0
(5T)(5Q)
0.055;-2450.0
55TJ
0.022;-3903.1
5J(5J)
0.068;-2450.0
5J(5Q)
0.045;-3021.9
5(5QK)
0.059;-2815.6
5K(5K)
0.081;-2037.5
68(56)
0.022;-3846.9
(56)(6J)
0.050;-2862.5
7(567)
0.023;-3846.9
J(567)
0.018;-4109.4
78(56)
0.015;-4418.8
(56)(7J)
0.038;-3434.4
8(568)
0.028;-3640.6
Q(568)
0.029;-3903.1
(56)(8T)
0.030;-3434.4
8(56K)
0.032;-3800.0
(569Q)
0.024;-3800.0
9(56J)
0.024;-3903.1
9K(56)
0.026;-3696.9
TT(56)
0.034;-3228.1
(56)(TK)
0.047;-2918.8
J(56Q)
0.028;-3593.8
K(56Q)
0.028;-3387.5
66(57)
0.022;-3950.0
5669
0.013;-4418.8
56(6Q)
0.035;-3434.4
(57)(68)
0.027;-3743.8
6(57J)
0.020;-4109.4
6K(57)
0.026;-3903.1
(67)(5T)
0.026;-3537.5
5Q(67)
0.021;-4006.3
5678
0.011;-5093.8
567T
0.013;-4887.5
567Q
0.015;-4681.2
(58)(69)
0.038;-3537.5
6(58Q)
0.024;-3903.1
5(689)
0.018;-4212.5
(68)(5Q)
0.041;-3228.1
58(69)
0.021;-4212.5
58(6J)
0.026;-4006.3
58(6K)
0.027;-3800.0
6(59J)
0.033;-3903.1
6K(59)
0.023;-3696.9
(69)(5Q)
0.037;-3125.0
59(6T)
0.023;-4006.3
59(6Q)
0.027;-3800.0
6T(5T)
0.043;-3228.1
(5T)(6K)
0.061;-2918.8
5Q(6T)
0.023;-3696.9
56TJ
0.019;-4475.0
56TK
0.019;-4268.8
6K(5J)
0.036;-3490.6
56JJ
0.031;-3696.9
56JK
0.018;-4165.6
5(6QK)
0.039;-3387.5
6K(5K)
0.051;-2609.4
(57)(79)
0.046;-2862.5
7(57Q)
0.048;-3228.1
9(578)
0.020;-4109.4
K(578)
0.028;-3696.9
8(57J)
0.028;-3903.1
8K(57)
0.028;-3696.9
(579K)
0.036;-3593.8
9J(57)
0.027;-3800.0
(57TJ)
0.031;-3696.9
(57)(TJ)
0.039;-3021.9
J(57J)
0.050;-2918.8
JQ(57)
0.036;-3490.6
Q(57K)
0.047;-3284.4
5778
0.019;-4315.6
57(7J)
0.034;-3331.3
(58)(78)
0.053;-2862.5
7(58J)
0.025;-3903.1
7K(58)
0.033;-3696.9
(78)(5J)
0.034;-3228.1
5K(78)
0.032;-3696.9
57(8T)
0.023;-4006.3
57(8Q)
0.028;-3800.0
7(59T)
0.024;-3903.1
7Q(59)
0.033;-3696.9
(79)(5J)
0.052;-3125.0
5K(79)
0.030;-3593.8
57(9J)
0.030;-3800.0
57(9K)
0.033;-3593.8
(5T)(7Q)
0.044;-2918.8
5J(7T)
0.032;-3696.9
7T(5J)
0.031;-3696.9
7T(5K)
0.029;-3490.6
7Q(5J)
0.041;-3490.6
(7J)(5K)
0.049;-2712.5
7J(5K)
0.040;-3387.5
7K(5Q)
0.048;-3284.4
57(QK)
0.039;-3284.4
(58)(89)
0.057;-2656.3
8(58Q)
0.047;-3021.9
T(589)
0.024;-3800.0
9(58T)
0.026;-3800.0
9Q(58)
0.030;-3593.8
Q(58T)
0.043;-3490.6
(58)(TQ)
0.064;-2815.6
(58JK)
0.034;-3284.4
JK(58)
0.046;-3284.4
K(58K)
0.057;-2403.1
588T
0.028;-3903.1
58(8K)
0.050;-2918.8
(59)(8J)
0.035;-3021.9
59(89)
0.049;-3228.1
5(89Q)
0.030;-3593.8
58(9T)
0.025;-3800.0
58(9Q)
0.032;-3593.8
8(5TJ)
0.033;-3593.8
8K(5T)
0.042;-3387.5
(8T)(5K)
0.055;-2712.5
8T(5Q)
0.035;-3490.6
(5J)(8J)
0.081;-2140.6
5J(8J)
0.045;-2815.6
8J(5Q)
0.028;-3387.5
(5Q)(8Q)
0.071;-1934.4
5K(8Q)
0.050;-3181.3
5K(8K)
0.057;-2403.1
9J(59)
0.058;-2918.8
(59TJ)
0.026;-3490.6
(59)(TJ)
0.047;-2815.6
J(59J)
0.047;-2712.5
JQ(59)
0.042;-3284.4
Q(59K)
0.055;-3078.1
599T
0.029;-3696.9
59(9K)
0.049;-2712.5
(5T)(9Q)
0.045;-2712.5
5J(9T)
0.031;-3490.6
9T(5J)
0.032;-3490.6
9T(5K)
0.041;-3284.4
9Q(5J)
0.042;-3284.4
(9J)(5K)
0.051;-2506.2
9J(5K)
0.040;-3181.3
9K(5Q)
0.053;-3078.1
59(QK)
0.055;-3078.1
(5T)(TJ)
0.074;-2037.5
J(5TJ)
0.050;-2609.4
JQ(5T)
0.050;-3181.3
Q(5TK)
0.036;-2975.0
5TTJ
0.043;-3387.5
TJ(5J)
0.043;-2609.4
(TJ)(5Q)
0.061;-2506.2
5J(TQ)
0.043;-3181.3
TQ(5Q)
0.071;-2403.1
5TQQ
0.041;-3078.1
5TKK
0.057;-2871.9
Q(5JQ)
0.076;-2300.0
KK(5J)
0.066;-2093.7
(5Q)(JQ)
0.065;-1625.0
5K(JQ)
0.042;-2871.9
5K(JK)
0.076;-2093.7
5QQQ
0.060;-2196.9
KK(5K)
0.090;-1212.5
6669
0.034;-3640.6
666K
0.043;-3228.1
69(67)
0.029;-3537.5
(67)(6Q)
0.054;-2553.1
6678
0.024;-4315.6
66(7J)
0.037;-3331.3
(68)(68)
0.075;-2187.5
6(68J)
0.052;-3228.1
6K(68)
0.048;-3021.9
68(6J)
0.041;-3228.1
668K
0.030;-3696.9
6J(69)
0.046;-3125.0
69(6T)
0.038;-3228.1
669Q
0.023;-3696.9
6J(6T)
0.048;-3021.9
6T(6J)
0.052;-3021.9
66TK
0.034;-3490.6
6K(6J)
0.055;-2712.5
(6Q)(6Q)
0.095;-1362.5
66QK
0.036;-3284.4
7(679)
0.038;-3434.4
7J(67)
0.030;-3228.1
(6789)
0.026;-4006.3
(678K)
0.028;-3593.8
8T(67)
0.021;-3903.1
(67)(8K)
0.041;-2918.8
Q(679)
0.034;-3593.8
(67)(9J)
0.039;-3021.9
T(67T)
0.037;-3021.9
T(67J)
0.033;-3593.8
TK(67)
0.041;-3387.5
(67)(JQ)
0.044;-2712.5
QQ(67)
0.061;-2609.4
67(78)
0.039;-3537.5
77(6J)
0.038;-3228.1
677K
0.027;-3696.9
7T(68)
0.019;-3903.1
(68)(7K)
0.049;-2918.8
6T(78)
0.022;-3903.1
6(78K)
0.028;-3593.8
68(7T)
0.029;-3903.1
68(7Q)
0.033;-3696.9
79(69)
0.042;-3228.1
(69)(7Q)
0.045;-2918.8
6T(79)
0.037;-3800.0
6(79K)
0.043;-3490.6
69(7J)
0.036;-3696.9
69(7K)
0.041;-3490.6
7(6TQ)
0.034;-3490.6
6(7TJ)
0.035;-3593.8
67TT
0.029;-3696.9
67TQ
0.015;-4165.6
(6J)(7Q)
0.054;-2712.5
6Q(7J)
0.033;-3387.5
67JQ
0.023;-4062.5
(6Q)(7K)
0.064;-2506.2
6Q(7K)
0.044;-3181.3
8(689)
0.044;-3228.1
8J(68)
0.046;-3021.9
(689T)
0.026;-3696.9
99(68)
0.034;-3125.0
(68)(9Q)
0.060;-2815.6
(68TQ)
0.045;-3387.5
T(68Q)
0.037;-3387.5
Q(68J)
0.035;-3284.4
(68)(JK)
0.055;-2506.2
QK(68)
0.036;-3078.1
68(8T)
0.043;-3125.0
88(6K)
0.055;-2815.6
8(69J)
0.037;-3593.8
8K(69)
0.032;-3387.5
(89)(6Q)
0.056;-2815.6
69(8T)
0.035;-3696.9
69(8Q)
0.036;-3490.6
8T(6T)
0.060;-2918.8
(6T)(8K)
0.053;-2609.4
6Q(8T)
0.041;-3387.5
68TJ
0.023;-4165.6
68TK
0.020;-3959.4
8K(6J)
0.038;-3181.3
68JJ
0.043;-3387.5
68JK
0.022;-3856.2
6(8QK)
0.043;-3078.1
8K(6K)
0.068;-2300.0
(69)(9J)
0.081;-2140.6
T(69T)
0.050;-2815.6
T(69J)
0.034;-3387.5
TK(69)
0.038;-3181.3
(69)(JQ)
0.059;-2506.2
QQ(69)
0.059;-2403.1
69(9T)
0.041;-2918.8
99(6K)
0.057;-2609.4
9(6TQ)
0.044;-3284.4
6(9TJ)
0.041;-3387.5
69TT
0.040;-3490.6
69TQ
0.025;-3959.4
(6J)(9Q)
0.053;-2506.2
6Q(9J)
0.041;-3181.3
69JQ
0.030;-3856.2
(6Q)(9K)
0.070;-2300.0
6Q(9K)
0.045;-2975.0
T(6TJ)
0.051;-2609.4
TK(6T)
0.062;-2403.1
(6T)(JQ)
0.066;-2403.1
QQ(6T)
0.083;-2300.0
6T(TJ)
0.072;-2609.4
(6J)(TJ)
0.092;-1831.3
6J(TJ)
0.058;-2506.2
TJ(6Q)
0.038;-3078.1
(6Q)(TQ)
0.099;-1625.0
6K(TQ)
0.037;-2871.9
6K(TK)
0.072;-2093.7
JK(6J)
0.068;-2196.9
K(6JK)
0.093;-1990.6
6JJK
0.041;-2871.9
6(JQK)
0.048;-2768.8
JK(6K)
0.092;-1990.6
KK(6Q)
0.070;-1887.5
6QKK
0.057;-2562.5
77(7T)
0.069;-2553.1
(78)(78)
0.090;-1981.3
7(78J)
0.035;-3021.9
7K(78)
0.045;-2815.6
78(7J)
0.038;-3021.9
778K
0.043;-3490.6
7J(79)
0.051;-2918.8
79(7T)
0.039;-3021.9
779Q
0.025;-3490.6
7J(7T)
0.039;-2815.6
7T(7J)
0.042;-2815.6
77TK
0.043;-3284.4
7K(7J)
0.060;-2506.2
(7Q)(7Q)
0.092;-1156.2
77QK
0.040;-3078.1
8(78T)
0.041;-3021.9
8Q(78)
0.054;-2815.6
J(789)
0.034;-3490.6
9T(78)
0.036;-3593.8
(78)(9K)
0.067;-2609.4
K(78T)
0.037;-3181.3
T(78K)
0.050;-3181.3
JJ(78)
0.057;-2609.4
(78QK)
0.054;-2975.0
7888
0.041;-3228.1
78(8J)
0.063;-2918.8
(79)(89)
0.060;-2346.9
8(79Q)
0.037;-3387.5
7(89T)
0.030;-3593.8
(89)(7K)
0.054;-2609.4
89(7J)
0.037;-3490.6
89(7K)
0.031;-3284.4
8J(7T)
0.034;-3387.5
(8T)(7J)
0.067;-2712.5
7K(8T)
0.038;-3181.3
78(TQ)
0.044;-3284.4
8(7JQ)
0.045;-3181.3
7(8JQ)
0.039;-3181.3
78(JQ)
0.041;-3181.3
8(7QK)
0.042;-2975.0
8Q(7K)
0.054;-2975.0
99(79)
0.075;-2243.8
(79)(9Q)
0.080;-1934.4
(79TQ)
0.038;-3181.3
T(79Q)
0.032;-3181.3
Q(79J)
0.038;-3078.1
(79)(JK)
0.085;-2300.0
QK(79)
0.046;-2871.9
79(9J)
0.041;-2712.5
(7T)(9T)
0.073;-2037.5
9(7TK)
0.045;-3078.1
7(9TQ)
0.042;-3181.3
79(TJ)
0.031;-3284.4
79(TK)
0.055;-3078.1
(7J)(9K)
0.064;-2300.0
7K(9J)
0.048;-2975.0
79(JK)
0.053;-2975.0
(9Q)(7K)
0.086;-2196.9
(7K)(9K)
0.104;-1418.8
T(7TQ)
0.064;-2403.1
Q(7TJ)
0.047;-2975.0
(7T)(JK)
0.078;-2196.9
QK(7T)
0.049;-2768.8
7T(TQ)
0.070;-2403.1
(7J)(TQ)
0.062;-2300.0
7Q(TJ)
0.049;-2975.0
7TJQ
0.038;-3650.0
(7Q)(TK)
0.063;-2093.7
7Q(TK)
0.058;-2768.8
J(7JQ)
0.068;-2196.9
K(7JQ)
0.061;-2665.6
JJ(7Q)
0.074;-2196.9
J(7QK)
0.061;-2665.6
JQ(7K)
0.046;-2665.6
QQ(7Q)
0.116;-1315.6
7Q(QK)
0.095;-1887.5
8888
0.054;-2450.0
888Q
0.062;-2712.5
8(89J)
0.059;-2712.5
8K(89)
0.046;-2506.2
89(8Q)
0.048;-2609.4
8(8TJ)
0.046;-2609.4
8K(8T)
0.063;-2403.1
8T(8K)
0.079;-2403.1
8(8JK)
0.052;-2300.0
88(JK)
0.078;-2300.0
8Q(8K)
0.064;-2196.9
(89)(9T)
0.073;-2037.5
9(89K)
0.058;-2403.1
(89TK)
0.051;-2975.0
TQ(89)
0.045;-3078.1
K(89J)
0.049;-2871.9
Q(89Q)
0.083;-2196.9
KK(89)
0.099;-1990.6
99(8Q)
0.047;-2506.2
9(8TJ)
0.032;-3181.3
9K(8T)
0.046;-2975.0
(9T)(8K)
0.053;-2300.0
9T(8Q)
0.046;-3078.1
(8J)(9J)
0.086;-1728.1
8J(9J)
0.065;-2403.1
9J(8Q)
0.049;-2975.0
(8Q)(9Q)
0.094;-1521.9
8K(9Q)
0.058;-2768.8
8K(9K)
0.084;-1990.6
TQ(8T)
0.073;-2300.0
K(8TJ)
0.060;-2768.8
Q(8TQ)
0.075;-2093.7
KK(8T)
0.079;-1887.5
