AAAA
0.124;-915.0
5AAA
0.073;-19190.6
9AAA
0.080;-14488.1
KAAA
0.107;-9785.6
4A(2A)
0.036;-34473.8
(2A)(7A)
0.066;-23251.9
A(2TA)
0.047;-27420.0
QA(2A)
0.061;-25068.7
2A(4A)
0.038;-34473.8
26AA
0.024;-39817.5
AA(29)
0.037;-28595.6
2A(QA)
0.046;-25068.7
A(34A)
0.033;-33298.1
6A(3A)
0.040;-30946.9
(3A)(9A)
0.072;-19725.0
A(3QA)
0.071;-23893.1
AA(34)
0.034;-33298.1
3A(7A)
0.047;-29771.3
39AA
0.035;-35115.0
AA(3Q)
0.050;-23893.1
(4A)(5A)
0.052;-23251.9
A(48A)
0.039;-27420.0
TA(4A)
0.038;-25068.7
(4A)(KA)
0.078;-13846.9
46AA
0.029;-37466.2
AA(49)
0.039;-26244.4
4A(QA)
0.057;-22717.5
A(56A)
0.049;-28595.6
8A(5A)
0.041;-26244.4
(5A)(JA)
0.089;-15022.5
55AA
0.051;-29771.3
AA(58)
0.040;-26244.4
5A(JA)
0.060;-22717.5
5KAA
0.042;-28061.3
8A(6A)
0.056;-25068.7
(6A)(JA)
0.066;-13846.9
66AA
0.056;-27420.0
AA(69)
0.047;-23893.1
6A(QA)
0.056;-20366.3
A(78A)
0.052;-23893.1
TA(7A)
0.049;-21541.9
(7A)(KA)
0.083;-10320.0
79AA
0.030;-30412.5
AA(7Q)
0.070;-19190.6
(8A)(9A)
0.094;-13846.9
A(8QA)
0.054;-18015.0
AA(89)
0.050;-21541.9
8A(QA)
0.072;-18015.0
A(9TA)
0.051;-19190.6
QA(9A)
0.061;-16839.4
9A(JA)
0.060;-18015.0
9KAA
0.050;-23358.8
QA(TA)
0.090;-15663.8
TA(QA)
0.066;-15663.8
A(JQA)
0.065;-14488.1
AA(JQ)
0.085;-14488.1
(QA)(KA)
0.111;-4441.9
KKAA
0.101;-10961.3
2(25A)
0.017;-47405.6
27(2A)
0.020;-45054.4
(2T)(2A)
0.041;-33832.5
2(2KA)
0.022;-38000.6
(236A)
0.009;-52749.4
(23TA)
0.013;-48046.9
33(2A)
0.016;-48581.3
(36)(2A)
0.019;-45054.4
3(29A)
0.016;-49222.5
3J(2A)
0.015;-46871.2
(245A)
0.009;-52749.4
(249A)
0.016;-48046.9
(24KA)
0.022;-43344.4
46(2A)
0.016;-51573.8
(49)(2A)
0.026;-40351.9
4(2QA)
0.013;-44520.0
6(25A)
0.016;-50398.1
T(25A)
0.017;-45695.6
5(26A)
0.014;-50398.1
58(2A)
0.013;-48046.9
(5J)(2A)
0.025;-36825.0
6(26A)
0.026;-41527.5
T(26A)
0.022;-44520.0
6(27A)
0.012;-48046.9
69(2A)
0.021;-45695.6
(6Q)(2A)
0.040;-34473.8
(279A)
0.024;-44520.0
(27KA)
0.026;-39817.5
79(2A)
0.017;-44520.0
(7Q)(2A)
0.032;-33298.1
(28TA)
0.027;-42168.8
88(2A)
0.030;-36825.0
(8J)(2A)
0.033;-33298.1
9(29A)
0.033;-34473.8
K(29A)
0.030;-37466.2
9(2QA)
0.025;-38641.9
J(2TA)
0.020;-38641.9
TJ(2A)
0.030;-38641.9
(2JQA)
0.035;-36290.6
J(2KA)
0.036;-35115.0
(QK)(2A)
0.040;-26244.4
22(4A)
0.013;-48581.3
226A
0.011;-53925.0
2A(29)
0.021;-42703.1
22(QA)
0.033;-39176.2
2(34A)
0.008;-55100.6
26(3A)
0.008;-52749.4
(29)(3A)
0.018;-41527.5
2(3QA)
0.022;-45695.6
A(234)
0.009;-55100.6
(23)(7A)
0.020;-43878.8
9A(23)
0.012;-49222.5
A(23Q)
0.016;-45695.6
2A(34)
0.010;-55100.6
2A(36)
0.010;-52749.4
2A(38)
0.013;-50398.1
2A(3T)
0.013;-48046.9
2A(3Q)
0.017;-45695.6
2(45A)
0.011;-52749.4
27(4A)
0.011;-50398.1
(2T)(4A)
0.023;-39176.2
2(4KA)
0.017;-43344.4
A(246)
0.008;-51573.8
(24)(9A)
0.017;-40351.9
JA(24)
0.022;-45695.6
24(5A)
0.010;-52749.4
24(7A)
0.013;-50398.1
24(9A)
0.015;-48046.9
24(JA)
0.017;-45695.6
24(KA)
0.019;-43344.4
26(5A)
0.012;-50398.1
(29)(5A)
0.024;-39176.2
2(5QA)
0.021;-43344.4
A(256)
0.014;-50398.1
(25)(9A)
0.026;-39176.2
JA(25)
0.015;-44520.0
25(6A)
0.014;-50398.1
25(8A)
0.018;-48046.9
25(TA)
0.020;-45695.6
25(QA)
0.020;-43344.4
(26)(6A)
0.028;-33832.5
2(69A)
0.017;-45695.6
2J(6A)
0.020;-43344.4
(26)(7A)
0.026;-40351.9
9A(26)
0.017;-45695.6
A(26Q)
0.018;-42168.8
2A(67)
0.017;-48046.9
2A(69)
0.016;-45695.6
2A(6J)
0.016;-43344.4
2A(6K)
0.026;-40993.1
(29)(7A)
0.027;-36825.0
2(7QA)
0.019;-40993.1
A(278)
0.015;-45695.6
(27)(JA)
0.035;-34473.8
KA(27)
0.030;-39817.5
2A(79)
0.024;-44520.0
2A(7J)
0.020;-42168.8
2A(7K)
0.024;-39817.5
(2T)(8A)
0.029;-34473.8
2(8KA)
0.025;-38641.9
A(28T)
0.020;-42168.8
(28)(KA)
0.040;-30946.9
28(TA)
0.024;-42168.8
28(QA)
0.028;-39817.5
(29)(9A)
0.044;-26778.8
2(9QA)
0.032;-38641.9
A(29T)
0.023;-40993.1
(29)(KA)
0.043;-29771.3
29(JA)
0.023;-39817.5
29(KA)
0.020;-37466.2
2J(TA)
0.020;-38641.9
(2T)(JA)
0.037;-30946.9
KA(2T)
0.029;-36290.6
2A(TQ)
0.020;-37466.2
2(JQA)
0.037;-36290.6
A(2JQ)
0.026;-36290.6
2A(JQ)
0.035;-36290.6
2(QKA)
0.044;-33939.4
2Q(KA)
0.036;-33939.4
33(3A)
0.023;-39710.6
(36)(3A)
0.025;-36183.8
3(39A)
0.023;-40351.9
3J(3A)
0.030;-38000.6
(345A)
0.012;-51573.8
(349A)
0.013;-46871.2
(34KA)
0.022;-42168.8
46(3A)
0.011;-50398.1
(49)(3A)
0.027;-39176.2
4(3QA)
0.020;-43344.4
6(35A)
0.012;-49222.5
T(35A)
0.016;-44520.0
5(36A)
0.012;-49222.5
58(3A)
0.018;-46871.2
(5J)(3A)
0.029;-35649.4
6(36A)
0.030;-40351.9
T(36A)
0.022;-43344.4
6(37A)
0.020;-46871.2
69(3A)
0.018;-44520.0
(6Q)(3A)
0.030;-33298.1
(379A)
0.021;-43344.4
(37KA)
0.026;-38641.9
79(3A)
0.024;-43344.4
(7Q)(3A)
0.027;-32122.5
(38TA)
0.026;-40993.1
88(3A)
0.025;-35649.4
(8J)(3A)
0.031;-32122.5
9(39A)
0.046;-33298.1
K(39A)
0.033;-36290.6
9(3QA)
0.022;-37466.2
J(3TA)
0.023;-37466.2
TJ(3A)
0.023;-37466.2
(3JQA)
0.030;-35115.0
J(3KA)
0.041;-33939.4
(QK)(3A)
0.045;-25068.7
33(5A)
0.022;-45054.4
337A
0.012;-50398.1
3A(3T)
0.028;-39176.2
33(KA)
0.030;-35649.4
3(46A)
0.012;-50398.1
38(4A)
0.012;-48046.9
(3J)(4A)
0.031;-36825.0
4A(34)
0.014;-45054.4
A(347)
0.011;-49222.5
(34)(TA)
0.024;-38000.6
QA(34)
0.017;-43344.4
345A
0.005;-59268.8
347A
0.007;-56917.5
349A
0.009;-54566.3
34JA
0.011;-52215.0
34KA
0.012;-49863.8
37(5A)
0.016;-48046.9
(3T)(5A)
0.030;-36825.0
3(5KA)
0.020;-40993.1
A(357)
0.016;-48046.9
(35)(TA)
0.025;-36825.0
QA(35)
0.021;-42168.8
356A
0.005;-56917.5
358A
0.008;-54566.3
35TA
0.014;-52215.0
35QA
0.012;-49863.8
(37)(6A)
0.027;-39176.2
3(6TA)
0.016;-43344.4
3Q(6A)
0.019;-40993.1
(36)(8A)
0.020;-38000.6
TA(36)
0.020;-43344.4
A(36K)
0.021;-39817.5
6A(38)
0.017;-45695.6
6A(3T)
0.022;-43344.4
6A(3Q)
0.019;-40993.1
37(7A)
0.029;-38000.6
(3T)(7A)
0.026;-34473.8
3(7KA)
0.027;-38641.9
A(379)
0.020;-43344.4
(37)(QA)
0.039;-32122.5
7A(38)
0.014;-44520.0
7A(3T)
0.020;-42168.8
7A(3Q)
0.033;-39817.5
38(8A)
0.032;-35649.4
(3J)(8A)
0.036;-32122.5
8A(38)
0.027;-35649.4
A(38J)
0.019;-39817.5
388A
0.016;-43344.4
38TA
0.019;-48688.1
38QA
0.017;-46336.9
(3T)(9A)
0.033;-32122.5
3(9KA)
0.023;-36290.6
A(39J)
0.025;-38641.9
399A
0.019;-40993.1
39JA
0.016;-46336.9
39KA
0.020;-43985.6
3Q(TA)
0.028;-36290.6
(3T)(QA)
0.043;-28595.6
TA(3J)
0.023;-37466.2
TA(3K)
0.032;-35115.0
3(JKA)
0.033;-33939.4
A(3JK)
0.029;-33939.4
JA(3K)
0.029;-33939.4
QA(3Q)
0.051;-26244.4
3QKA
0.025;-40458.7
45(4A)
0.017;-42703.1
(48)(4A)
0.038;-31481.3
4(4JA)
0.040;-35649.4
4K(4A)
0.042;-33298.1
(459A)
0.019;-44520.0
(45KA)
0.021;-39817.5
57(4A)
0.016;-46871.2
(5T)(4A)
0.032;-35649.4
5(4KA)
0.020;-39817.5
(469A)
0.020;-43344.4
(46KA)
0.024;-38641.9
68(4A)
0.020;-44520.0
(6J)(4A)
0.038;-33298.1
7(47A)
0.030;-36825.0
J(47A)
0.021;-39817.5
78(4A)
0.018;-43344.4
(7J)(4A)
0.033;-32122.5
8(48A)
0.031;-34473.8
Q(48A)
0.035;-37466.2
(8T)(4A)
0.039;-32122.5
8(4KA)
0.026;-36290.6
(49QA)
0.029;-36290.6
9(4JA)
0.026;-37466.2
9K(4A)
0.031;-35115.0
TT(4A)
0.046;-29771.3
(TK)(4A)
0.053;-26244.4
J(4QA)
0.026;-33939.4
K(4QA)
0.038;-31588.1
44(5A)
0.020;-42703.1
447A
0.012;-48046.9
4A(4T)
0.028;-36825.0
44(KA)
0.030;-33298.1
4(57A)
0.012;-46871.2
49(5A)
0.017;-44520.0
(4Q)(5A)
0.030;-33298.1
6A(45)
0.017;-48046.9
A(459)
0.019;-44520.0
(45)(QA)
0.036;-33298.1
5A(46)
0.017;-48046.9
5A(48)
0.017;-45695.6
5A(4T)
0.024;-43344.4
5A(4Q)
0.023;-40993.1
46(6A)
0.030;-39176.2
(49)(6A)
0.027;-35649.4
4(6QA)
0.027;-39817.5
A(467)
0.019;-45695.6
(46)(TA)
0.030;-34473.8
QA(46)
0.019;-39817.5
467A
0.010;-53390.6
469A
0.013;-51039.4
46JA
0.014;-48688.1
46KA
0.017;-46336.9
49(7A)
0.020;-42168.8
(4Q)(7A)
0.041;-30946.9
8A(47)
0.022;-43344.4
A(47J)
0.030;-39817.5
477A
0.016;-44520.0
479A
0.014;-49863.8
47JA
0.014;-47512.5
47KA
0.017;-45161.3
4T(8A)
0.022;-39817.5
(4K)(8A)
0.036;-28595.6
TA(48)
0.026;-39817.5
A(48K)
0.027;-36290.6
8A(4T)
0.023;-39817.5
8A(4Q)
0.032;-37466.2
49(9A)
0.048;-32122.5
(4Q)(9A)
0.040;-28595.6
TA(49)
0.025;-38641.9
A(49K)
0.029;-35115.0
9A(4J)
0.025;-37466.2
9A(4K)
0.035;-35115.0
4(TQA)
0.038;-35115.0
A(4TJ)
0.030;-36290.6
4TTA
0.027;-37466.2
4TQA
0.024;-42810.0
(4Q)(JA)
0.049;-26244.4
QA(4J)
0.033;-33939.4
4JQA
0.029;-41634.4
(4K)(QA)
0.055;-23893.1
QA(4K)
0.044;-31588.1
5(56A)
0.032;-39176.2
58(5A)
0.024;-36825.0
(5J)(5A)
0.041;-25603.1
6(56A)
0.028;-38000.6
T(56A)
0.019;-40993.1
6(57A)
0.016;-44520.0
69(5A)
0.017;-42168.8
(6Q)(5A)
0.049;-30946.9
(579A)
0.021;-40993.1
(57KA)
0.025;-36290.6
79(5A)
0.025;-40993.1
(7Q)(5A)
0.035;-29771.3
(58TA)
0.029;-38641.9
88(5A)
0.029;-33298.1
(8J)(5A)
0.034;-29771.3
9(59A)
0.034;-30946.9
K(59A)
0.040;-33939.4
9(5QA)
0.030;-35115.0
J(5TA)
0.032;-35115.0
TJ(5A)
0.026;-35115.0
(5JQA)
0.032;-32763.8
J(5KA)
0.033;-31588.1
(QK)(5A)
0.052;-22717.5
55(7A)
0.029;-38000.6
559A
0.018;-43344.4
5A(5Q)
0.036;-32122.5
(57)(6A)
0.033;-36825.0
5(6TA)
0.024;-40993.1
5Q(6A)
0.035;-38641.9
(56)(8A)
0.039;-35649.4
TA(56)
0.032;-40993.1
A(56K)
0.027;-37466.2
6A(58)
0.022;-43344.4
6A(5T)
0.020;-40993.1
6A(5Q)
0.021;-38641.9
57(7A)
0.034;-35649.4
(5T)(7A)
0.032;-32122.5
5(7KA)
0.032;-36290.6
A(579)
0.027;-40993.1
(57)(QA)
0.041;-29771.3
7A(58)
0.020;-42168.8
7A(5T)
0.026;-39817.5
7A(5Q)
0.031;-37466.2
58(8A)
0.031;-33298.1
(5J)(8A)
0.043;-29771.3
8A(58)
0.042;-33298.1
A(58J)
0.031;-37466.2
588A
0.026;-40993.1
58TA
0.018;-46336.9
58QA
0.015;-43985.6
(5T)(9A)
0.042;-29771.3
5(9KA)
0.032;-33939.4
A(59J)
0.034;-36290.6
599A
0.032;-38641.9
59JA
0.014;-43985.6
59KA
0.018;-41634.4
5Q(TA)
0.037;-33939.4
(5T)(QA)
0.057;-26244.4
TA(5J)
0.031;-35115.0
TA(5K)
0.039;-32763.8
5(JKA)
0.039;-31588.1
A(5JK)
0.031;-31588.1
JA(5K)
0.028;-31588.1
QA(5Q)
0.039;-23893.1
5QKA
0.028;-38107.5
67(6A)
0.029;-35649.4
(6T)(6A)
0.045;-24427.5
6(6KA)
0.052;-28595.6
(67TA)
0.029;-38641.9
77(6A)
0.029;-34473.8
(7T)(6A)
0.030;-30946.9
7(6KA)
0.038;-35115.0
(68JA)
0.034;-36290.6
(89)(6A)
0.039;-30946.9
8(6QA)
0.036;-35115.0
T(69A)
0.037;-36290.6
9(6TA)
0.025;-36290.6
9Q(6A)
0.025;-33939.4
Q(6TA)
0.035;-32763.8
(TQ)(6A)
0.045;-25068.7
(6JKA)
0.040;-30412.5
JK(6A)
0.034;-30412.5
K(6KA)
0.060;-20366.3
668A
0.026;-42168.8
6A(6J)
0.041;-30946.9
(67)(7A)
0.063;-26778.8
6(7TA)
0.023;-38641.9
6Q(7A)
0.034;-36290.6
(67)(9A)
0.034;-32122.5
JA(67)
0.032;-37466.2
67(8A)
0.026;-40993.1
67(TA)
0.032;-38641.9
67(QA)
0.024;-36290.6
(68)(8A)
0.047;-24427.5
6(8JA)
0.029;-36290.6
6K(8A)
0.027;-33939.4
(68)(JA)
0.043;-28595.6
KA(68)
0.028;-33939.4
6A(8T)
0.024;-37466.2
6A(8Q)
0.030;-35115.0
6(9TA)
0.026;-36290.6
6Q(9A)
0.030;-33939.4
(69)(JA)
0.043;-27420.0
KA(69)
0.037;-32763.8
6A(9J)
0.027;-35115.0
6A(9K)
0.028;-32763.8
(6Q)(TA)
0.040;-25068.7
JA(6T)
0.027;-33939.4
6T(JA)
0.036;-33939.4
6T(KA)
0.042;-31588.1
6Q(JA)
0.038;-31588.1
(6J)(KA)
0.052;-22717.5
6J(KA)
0.031;-30412.5
6K(QA)
0.035;-29236.9
6A(QK)
0.037;-29236.9
(78)(7A)
0.054;-24427.5
7(7JA)
0.045;-28595.6
7K(7A)
0.045;-26244.4
(78QA)
0.024;-33939.4
8(7TA)
0.033;-36290.6
8Q(7A)
0.032;-33939.4
J(79A)
0.035;-33939.4
9T(7A)
0.034;-35115.0
(9K)(7A)
0.039;-23893.1
K(7TA)
0.050;-30412.5
T(7KA)
0.029;-30412.5
JJ(7A)
0.050;-23893.1
(7QKA)
0.050;-28061.3
777A
0.039;-33298.1
7A(7T)
0.050;-29771.3
77(KA)
0.047;-26244.4
7(8TA)
0.027;-36290.6
7Q(8A)
0.029;-33939.4
(78)(TA)
0.040;-28595.6
QA(78)
0.037;-33939.4
789A
0.016;-45161.3
78JA
0.017;-42810.0
78KA
0.025;-40458.7
7J(9A)
0.040;-33939.4
(79)(TA)
0.050;-27420.0
QA(79)
0.029;-32763.8
79TA
0.026;-42810.0
79QA
0.020;-40458.7
(7J)(TA)
0.057;-25068.7
TA(7T)
0.065;-26244.4
A(7TK)
0.035;-30412.5
TA(7Q)
0.035;-31588.1
7J(JA)
0.044;-23893.1
(7J)(QA)
0.052;-22717.5
JA(7Q)
0.048;-30412.5
7Q(QA)
0.059;-21541.9
7QQA
0.036;-29236.9
7KKA
0.063;-26885.6
8(8JA)
0.049;-26244.4
8K(8A)
0.052;-23893.1
(89KA)
0.045;-30412.5
9J(8A)
0.041;-32763.8
(8TJA)
0.034;-31588.1
(TJ)(8A)
0.043;-23893.1
J(8JA)
0.065;-22717.5
JQ(8A)
0.041;-29236.9
Q(8KA)
0.045;-26885.6
889A
0.039;-36290.6
8A(8Q)
0.050;-25068.7
(8T)(9A)
0.060;-26244.4
8(9KA)
0.039;-30412.5
A(89J)
0.041;-32763.8
899A
0.038;-35115.0
89JA
0.028;-40458.7
89KA
0.023;-38107.5
8Q(TA)
0.032;-30412.5
(8T)(QA)
0.048;-22717.5
TA(8J)
0.035;-31588.1
TA(8K)
0.042;-29236.9
8(JKA)
0.045;-28061.3
A(8JK)
0.042;-28061.3
JA(8K)
0.040;-28061.3
QA(8Q)
0.059;-20366.3
8QKA
0.038;-34580.6
9T(9A)
0.057;-25068.7
(9K)(9A)
0.101;-13846.9
K(9TA)
0.052;-28061.3
T(9KA)
0.054;-28061.3
JJ(9A)
0.060;-21541.9
(9QKA)
0.059;-25710.0
999A
0.050;-26244.4
9A(9Q)
0.054;-22717.5
(9J)(TA)
0.069;-22717.5
TA(9T)
0.050;-23893.1
A(9TK)
0.037;-28061.3
TA(9Q)
0.042;-29236.9
9J(JA)
0.055;-21541.9
(9J)(QA)
0.082;-20366.2
JA(9Q)
0.035;-28061.3
9Q(QA)
0.062;-19190.6
9QQA
0.053;-26885.6
9KKA
0.045;-24534.4
T(TKA)
0.066;-19190.6
JJ(TA)
0.063;-20366.3
(TQKA)
0.047;-24534.4
TTTA
0.063;-22717.5
TA(TK)
0.070;-19190.6
(TK)(JA)
0.087;-18015.0
KA(TJ)
0.040;-25710.0
TA(JK)
0.061;-25710.0
(TQ)(KA)
0.079;-16839.4
(TK)(KA)
0.125;-7968.8
J(JKA)
0.067;-16839.4
(QK)(JA)
0.073;-15663.7
JJ(KA)
0.076;-16839.4
QA(JQ)
0.071;-16839.4
JQKA
0.035;-31053.7
QK(QA)
0.072;-14488.1
QK(KA)
0.077;-13312.5
22(24)
0.009;-54993.8
22(28)
0.010;-50291.3
22(2Q)
0.017;-45588.8
24(23)
0.005;-61513.1
(23)(27)
0.010;-50291.3
2(23T)
0.009;-54459.4
2Q(23)
0.012;-52108.1
23(25)
0.005;-60337.5
2237
0.003;-65681.2
22(3T)
0.008;-54459.4
23(2K)
0.010;-50932.5
2(246)
0.007;-57986.3
28(24)
0.010;-55635.0
(24)(2J)
0.020;-44413.1
2244
0.006;-60337.5
22(47)
0.006;-56810.6
24(2T)
0.009;-53283.8
224Q
0.005;-58627.5
26(25)
0.007;-56810.6
(25)(29)
0.015;-45588.8
2(25Q)
0.012;-49756.9
22(56)
0.007;-56810.6
25(29)
0.010;-53283.8
225J
0.007;-58627.5
26(26)
0.020;-47940.0
(26)(29)
0.017;-44413.1
2(26Q)
0.011;-48581.3
22(67)
0.010;-54459.4
26(2T)
0.014;-50932.5
226Q
0.009;-56276.3
28(27)
0.010;-52108.1
(27)(2J)
0.023;-40886.3
2277
0.008;-53283.8
22(7T)
0.011;-49756.9
27(2K)
0.013;-46230.0
2(28T)
0.017;-48581.3
2Q(28)
0.013;-46230.0
28(2T)
0.015;-48581.3
228Q
0.010;-53925.0
2T(29)
0.014;-47405.6
(29)(2K)
0.036;-36183.8
229J
0.010;-53925.0
2T(2T)
0.029;-38535.0
(2T)(2K)
0.042;-35008.1
22TQ
0.012;-51573.8
2Q(2J)
0.023;-42703.1
2J(2K)
0.023;-41527.5
22QQ
0.018;-41527.5
3(234)
0.005;-60337.5
36(23)
0.005;-57986.3
(23)(39)
0.020;-46764.4
3(23Q)
0.016;-50932.5
5(234)
0.003;-65681.2
9(234)
0.003;-60978.8
K(234)
0.009;-56276.3
4(237)
0.004;-63330.0
49(23)
0.005;-60978.8
(23)(4Q)
0.013;-49756.9
(2357)
0.005;-62154.4
(235J)
0.007;-57451.9
(23)(56)
0.006;-55635.0
5(239)
0.005;-59803.1
5J(23)
0.006;-57451.9
(2367)
0.004;-60978.8
(236J)
0.008;-56276.3
(23)(67)
0.010;-53283.8
6(23T)
0.006;-57451.9
6Q(23)
0.010;-55100.6
9(237)
0.007;-57451.9
K(237)
0.009;-52749.4
7(23T)
0.007;-56276.3
7Q(23)
0.010;-53925.0
T(238)
0.010;-55100.6
8(239)
0.007;-56276.3
8J(23)
0.008;-53925.0
(239T)
0.009;-53925.0
99(23)
0.013;-47405.6
(23)(9Q)
0.020;-43878.8
(23TQ)
0.012;-50398.1
T(23Q)
0.010;-50398.1
Q(23J)
0.014;-49222.5
(23)(JK)
0.022;-40351.9
QK(23)
0.017;-46871.2
23(35)
0.006;-59161.9
33(28)
0.007;-55635.0
233T
0.005;-60978.8
23(3K)
0.012;-49756.9
(24)(36)
0.005;-56810.6
3(249)
0.006;-60978.8
3J(24)
0.007;-58627.5
(34)(25)
0.007;-57986.3
27(34)
0.005;-63330.0
2(34T)
0.005;-59803.1
(34)(2K)
0.014;-48581.3
34(26)
0.003;-64505.6
34(28)
0.004;-62154.4
34(2T)
0.007;-59803.1
34(2Q)
0.009;-57451.9
(25)(35)
0.011;-49115.6
3(258)
0.006;-60978.8
3T(25)
0.005;-58627.5
(25)(3K)
0.017;-47405.6
27(35)
0.003;-62154.4
2(35T)
0.006;-58627.5
(35)(2K)
0.015;-47405.6
35(27)
0.004;-62154.4
35(29)
0.005;-59803.1
35(2J)
0.007;-57451.9
35(2K)
0.008;-55100.6
37(26)
0.004;-60978.8
(26)(3T)
0.017;-49756.9
3(26K)
0.011;-53925.0
2(368)
0.004;-59803.1
(36)(2J)
0.014;-48581.3
2K(36)
0.009;-53925.0
23(68)
0.006;-59803.1
23(6T)
0.008;-57451.9
23(6Q)
0.011;-55100.6
3(278)
0.006;-58627.5
3T(27)
0.006;-56276.3
(27)(3K)
0.017;-45054.4
29(37)
0.006;-57451.9
2(37Q)
0.009;-53925.0
23(78)
0.006;-58627.5
23(7T)
0.007;-56276.3
23(7Q)
0.008;-53925.0
3(289)
0.009;-56276.3
3J(28)
0.011;-53925.0
(38)(29)
0.015;-48581.3
2J(38)
0.010;-53925.0
38(29)
0.007;-56276.3
38(2J)
0.007;-53925.0
38(2K)
0.010;-51573.8
3T(29)
0.012;-53925.0
(29)(3K)
0.019;-42703.1
2J(39)
0.010;-52749.4
39(2T)
0.013;-53925.0
39(2Q)
0.012;-51573.8
(2T)(3T)
0.029;-37359.4
3(2TK)
0.015;-49222.5
2(3TQ)
0.010;-50398.1
23(TJ)
0.014;-51573.8
23(TK)
0.016;-49222.5
(2J)(3K)
0.027;-40351.9
2K(3J)
0.017;-48046.9
23(JK)
0.015;-48046.9
(3Q)(2K)
0.023;-39176.2
(2K)(3K)
0.035;-30305.6
4(246)
0.006;-55635.0
48(24)
0.009;-53283.8
(24)(4J)
0.019;-42061.9
5(245)
0.010;-55635.0
9(245)
0.005;-58627.5
K(245)
0.010;-53925.0
5(248)
0.006;-59803.1
5T(24)
0.007;-57451.9
(24)(5K)
0.015;-46230.0
9(246)
0.007;-57451.9
K(246)
0.012;-52749.4
6(249)
0.008;-57451.9
6J(24)
0.006;-55100.6
(2478)
0.008;-57451.9
(247Q)
0.010;-52749.4
7(249)
0.008;-56276.3
7J(24)
0.009;-53925.0
(2489)
0.011;-55100.6
(248K)
0.012;-50398.1
8T(24)
0.009;-53925.0
(24)(8K)
0.025;-42703.1
Q(249)
0.014;-50398.1
(24)(9J)
0.022;-43878.8
T(24T)
0.020;-43878.8
T(24J)
0.011;-50398.1
TK(24)
0.016;-48046.9
(24)(JQ)
0.033;-40351.9
QQ(24)
0.021;-39176.2
24(45)
0.007;-56810.6
44(28)
0.009;-53283.8
244T
0.009;-58627.5
24(4K)
0.013;-47405.6
(25)(47)
0.011;-53283.8
4(25T)
0.007;-57451.9
4Q(25)
0.007;-55100.6
(45)(27)
0.011;-53283.8
29(45)
0.006;-58627.5
2(45Q)
0.009;-55100.6
24(56)
0.004;-62154.4
24(58)
0.005;-59803.1
24(5T)
0.009;-57451.9
24(5Q)
0.008;-55100.6
4(267)
0.006;-59803.1
49(26)
0.006;-57451.9
(26)(4Q)
0.017;-46230.0
27(46)
0.006;-59803.1
2(46T)
0.007;-56276.3
(46)(2K)
0.013;-45054.4
46(28)
0.005;-58627.5
46(2T)
0.008;-56276.3
46(2Q)
0.010;-53925.0
(27)(47)
0.027;-43237.5
4(27T)
0.008;-55100.6
4Q(27)
0.010;-52749.4
(47)(29)
0.010;-48581.3
2J(47)
0.008;-53925.0
47(28)
0.009;-57451.9
47(2T)
0.008;-55100.6
47(2Q)
0.010;-52749.4
(28)(48)
0.016;-40886.3
4(28J)
0.011;-52749.4
4K(28)
0.012;-50398.1
(48)(2J)
0.024;-45054.4
2K(48)
0.015;-50398.1
24(8T)
0.009;-53925.0
24(8Q)
0.009;-51573.8
4(29T)
0.010;-52749.4
4Q(29)
0.014;-50398.1
(49)(2J)
0.019;-43878.8
2K(49)
0.015;-49222.5
24(9J)
0.012;-51573.8
24(9K)
0.011;-49222.5
(2T)(4Q)
0.024;-41527.5
2J(4T)
0.014;-50398.1
4T(2J)
0.013;-50398.1
4T(2K)
0.013;-48046.9
4Q(2J)
0.015;-48046.9
(4J)(2K)
0.027;-39176.2
4J(2K)
0.019;-46871.2
4K(2Q)
0.022;-45695.6
24(QK)
0.019;-45695.6
(25)(56)
0.019;-45588.8
5(259)
0.011;-49756.9
5J(25)
0.015;-47405.6
(2567)
0.009;-58627.5
(256J)
0.010;-53925.0
(25)(67)
0.011;-50932.5
6(25T)
0.009;-55100.6
6Q(25)
0.010;-52749.4
9(257)
0.007;-55100.6
K(257)
0.013;-50398.1
7(25T)
0.010;-53925.0
7Q(25)
0.010;-51573.8
T(258)
0.010;-52749.4
8(259)
0.010;-53925.0
8J(25)
0.011;-51573.8
(259T)
0.012;-51573.8
99(25)
0.024;-45054.4
(25)(9Q)
0.017;-41527.5
(25TQ)
0.012;-48046.9
T(25Q)
0.013;-48046.9
Q(25J)
0.016;-46871.2
(25)(JK)
0.027;-38000.6
QK(25)
0.020;-44520.0
25(57)
0.010;-52108.1
55(2T)
0.013;-48581.3
255Q
0.010;-53925.0
57(26)
0.006;-58627.5
(26)(5T)
0.016;-47405.6
5(26K)
0.014;-51573.8
2(568)
0.005;-57451.9
(56)(2J)
0.022;-46230.0
2K(56)
0.012;-51573.8
25(68)
0.009;-57451.9
25(6T)
0.007;-55100.6
25(6Q)
0.010;-52749.4
5(278)
0.008;-56276.3
5T(27)
0.010;-53925.0
(27)(5K)
0.021;-42703.1
29(57)
0.010;-55100.6
2(57Q)
0.009;-51573.8
25(78)
0.010;-56276.3
25(7T)
0.009;-53925.0
25(7Q)
0.008;-51573.8
5(289)
0.010;-53925.0
5J(28)
0.010;-51573.8
(58)(29)
0.014;-46230.0
2J(58)
0.011;-51573.8
58(29)
0.013;-53925.0
58(2J)
0.013;-51573.8
58(2K)
0.011;-49222.5
5T(29)
0.012;-51573.8
(29)(5K)
0.026;-40351.9
2J(59)
0.010;-50398.1
59(2T)
0.010;-51573.8
59(2Q)
0.018;-49222.5
(2T)(5T)
0.036;-35008.1
5(2TK)
0.015;-46871.2
2(5TQ)
0.018;-48046.9
25(TJ)
0.011;-49222.5
25(TK)
0.013;-46871.2
(2J)(5K)
0.025;-38000.6
2K(5J)
0.014;-45695.6
25(JK)
0.016;-45695.6
(5Q)(2K)
0.036;-36825.0
(2K)(5K)
0.048;-27954.4
6(268)
0.010;-48581.3
6T(26)
0.016;-46230.0
(26)(6K)
0.029;-35008.1
T(267)
0.013;-52749.4
7(268)
0.010;-55100.6
7T(26)
0.014;-52749.4
(26)(7K)
0.017;-41527.5
J(268)
0.014;-50398.1
89(26)
0.010;-52749.4
(26)(8Q)
0.019;-41527.5
(269J)
0.017;-49222.5
(26)(9T)
0.023;-42703.1
9(26K)
0.016;-46871.2
(26TK)
0.015;-45695.6
TQ(26)
0.017;-46871.2
K(26J)
0.017;-44520.0
Q(26Q)
0.033;-36825.0
KK(26)
0.044;-34473.8
66(29)
0.020;-47405.6
266J
0.011;-52749.4
67(27)
0.013;-48581.3
(27)(6T)
0.014;-45054.4
6(27K)
0.012;-49222.5
2(679)
0.011;-53925.0
(67)(2Q)
0.016;-42703.1
27(68)
0.010;-55100.6
27(6T)
0.012;-52749.4
27(6Q)
0.012;-50398.1
68(28)
0.017;-46230.0
(28)(6J)
0.018;-42703.1
28(68)
0.020;-46230.0
2(68J)
0.012;-50398.1
2688
0.010;-53925.0
268T
0.005;-59268.8
268Q
0.006;-56917.5
(29)(6T)
0.024;-42703.1
6(29K)
0.017;-46871.2
2(69J)
0.014;-49222.5
2699
0.011;-51573.8
269J
0.007;-56917.5
269K
0.008;-54566.3
6Q(2T)
0.016;-46871.2
(6T)(2Q)
0.020;-39176.2
2T(6J)
0.014;-48046.9
2T(6K)
0.015;-45695.6
6(2JK)
0.021;-44520.0
2(6JK)
0.020;-44520.0
2J(6K)
0.018;-44520.0
2Q(6Q)
0.029;-36825.0
26QK
0.012;-51039.4
78(27)
0.016;-46230.0
(27)(7J)
0.022;-35008.1
8(278)
0.014;-45054.4
Q(278)
0.014;-48046.9
(27)(8T)
0.020;-42703.1
8(27K)
0.018;-46871.2
(279Q)
0.016;-46871.2
9(27J)
0.016;-48046.9
9K(27)
0.018;-45695.6
TT(27)
0.018;-40351.9
(27)(TK)
0.026;-36825.0
J(27Q)
0.019;-44520.0
K(27Q)
0.021;-42168.8
77(28)
0.015;-46230.0
277T
0.011;-51573.8
27(7K)
0.026;-40351.9
(28)(7T)
0.018;-42703.1
7(28K)
0.018;-46871.2
2(78T)
0.009;-50398.1
(78)(2K)
0.021;-39176.2
78(2T)
0.010;-50398.1
78(2Q)
0.017;-48046.9
(29)(79)
0.039;-35008.1
7(29Q)
0.014;-46871.2
2(79T)
0.012;-49222.5
(79)(2K)
0.032;-38000.6
79(2J)
0.014;-48046.9
79(2K)
0.016;-45695.6
7J(2T)
0.012;-46871.2
(7T)(2J)
0.023;-39176.2
2K(7T)
0.024;-44520.0
27(TQ)
0.017;-45695.6
7(2JQ)
0.019;-44520.0
2(7JQ)
0.020;-44520.0
27(JQ)
0.014;-44520.0
7(2QK)
0.022;-42168.8
7Q(2K)
0.018;-42168.8
88(28)
0.030;-36183.8
(28)(8J)
0.045;-32656.9
9(289)
0.019;-41527.5
K(289)
0.017;-44520.0
9(28Q)
0.023;-45695.6
J(28T)
0.014;-45695.6
TJ(28)
0.020;-45695.6
(28JQ)
0.021;-43344.4
J(28K)
0.016;-42168.8
(28)(QK)
0.034;-33298.1
88(2T)
0.027;-41527.5
288Q
0.014;-46871.2
8T(29)
0.016;-48046.9
(29)(8K)
0.031;-36825.0
2J(89)
0.020;-46871.2
89(2T)
0.014;-48046.9
89(2Q)
0.016;-45695.6
(2T)(8T)
0.032;-31481.3
8(2TK)
0.024;-43344.4
2(8TQ)
0.025;-44520.0
28(TJ)
0.017;-45695.6
28(TK)
0.025;-43344.4
(2J)(8K)
0.030;-34473.8
2K(8J)
0.018;-42168.8
28(JK)
0.016;-42168.8
(8Q)(2K)
0.043;-33298.1
(2K)(8K)
0.051;-24427.5
9(29J)
0.025;-38000.6
9K(29)
0.039;-35649.4
TT(29)
0.024;-38000.6
(29)(TK)
0.039;-34473.8
J(29Q)
0.016;-42168.8
K(29Q)
0.026;-39817.5
99(2T)
0.028;-39176.2
299Q
0.023;-44520.0
9J(2T)
0.017;-44520.0
(9T)(2J)
0.034;-36825.0
2K(9T)
0.023;-42168.8
29(TQ)
0.023;-43344.4
9(2JQ)
0.021;-42168.8
2(9JQ)
0.026;-42168.8
29(JQ)
0.021;-42168.8
9(2QK)
0.020;-39817.5
9Q(2K)
0.021;-39817.5
TT(2T)
0.046;-29130.0
(2T)(TK)
0.061;-25603.1
J(2TQ)
0.025;-40993.1
K(2TQ)
0.034;-38641.9
TT(2J)
0.037;-35649.4
2TTK
0.028;-40993.1
TK(2J)
0.024;-39817.5
2TJJ
0.016;-42168.8
2TJK
0.016;-47512.5
2(TQK)
0.028;-38641.9
TK(2K)
0.041;-29771.3
(2J)(JK)
0.048;-23251.9
QK(2J)
0.032;-37466.2
2J(JK)
0.033;-30946.9
(JQ)(2K)
0.036;-29771.3
(2K)(JK)
0.067;-20900.6
K(2QK)
0.045;-27420.0
2K(QK)
0.052;-27420.0
3335
0.007;-57986.3
3339
0.009;-53283.8
333K
0.014;-48581.3
36(34)
0.009;-55635.0
(34)(39)
0.021;-44413.1
3(34Q)
0.012;-48581.3
33(45)
0.007;-56810.6
34(38)
0.012;-53283.8
334T
0.005;-58627.5
33(4K)
0.016;-47405.6
(35)(37)
0.016;-45588.8
3(35T)
0.014;-49756.9
3Q(35)
0.014;-47405.6
35(37)
0.009;-53283.8
3359
0.006;-58627.5
33(5Q)
0.014;-47405.6
(36)(37)
0.024;-44413.1
3(36T)
0.012;-48581.3
3Q(36)
0.015;-46230.0
36(38)
0.010;-50932.5
336T
0.007;-56276.3
33(6K)
0.016;-45054.4
(37)(39)
0.019;-40886.3
3(37Q)
0.022;-45054.4
33(78)
0.013;-49756.9
37(3J)
0.016;-46230.0
337K
0.012;-51573.8
3T(38)
0.016;-46230.0
(38)(3K)
0.037;-35008.1
338T
0.009;-53925.0
33(8K)
0.024;-42703.1
(39)(3J)
0.031;-36183.8
3399
0.019;-46230.0
33(9Q)
0.027;-42703.1
(3T)(3J)
0.032;-35008.1
33TT
0.018;-43878.8
33(TK)
0.025;-40351.9
(3J)(3K)
0.041;-31481.3
33JK
0.015;-46871.2
33(QK)
0.024;-38000.6
45(34)
0.009;-55635.0
(34)(48)
0.021;-44413.1
4(34J)
0.019;-48581.3
4K(34)
0.016;-46230.0
(3459)
0.006;-57451.9
(345K)
0.011;-52749.4
57(34)
0.007;-59803.1
(34)(5T)
0.013;-48581.3
5(34K)
0.008;-52749.4
(3469)
0.007;-56276.3
(346K)
0.012;-51573.8
68(34)
0.006;-57451.9
(34)(6J)
0.016;-46230.0
7(347)
0.014;-49756.9
J(347)
0.010;-52749.4
78(34)
0.007;-56276.3
(34)(7J)
0.020;-45054.4
8(348)
0.019;-47405.6
Q(348)
0.012;-50398.1
(34)(8T)
0.017;-45054.4
8(34K)
0.013;-49222.5
(349Q)
0.013;-49222.5
9(34J)
0.015;-50398.1
9K(34)
0.019;-48046.9
TT(34)
0.019;-42703.1
(34)(TK)
0.021;-39176.2
J(34Q)
0.019;-46871.2
K(34Q)
0.023;-44520.0
44(35)
0.007;-55635.0
3447
0.005;-60978.8
34(4T)
0.017;-49756.9
44(3K)
0.014;-46230.0
4(357)
0.005;-59803.1
49(35)
0.006;-57451.9
(35)(4Q)
0.017;-46230.0
36(45)
0.005;-60978.8
3(459)
0.010;-57451.9
(45)(3Q)
0.018;-46230.0
35(46)
0.006;-60978.8
35(48)
0.005;-58627.5
35(4T)
0.007;-56276.3
35(4Q)
0.009;-53925.0
46(36)
0.011;-52108.1
(36)(49)
0.014;-48581.3
4(36Q)
0.011;-52749.4
3(467)
0.006;-58627.5
(46)(3T)
0.019;-47405.6
3Q(46)
0.009;-52749.4
3467
0.002;-66322.5
3469
0.003;-63971.3
346J
0.005;-61620.0
346K
0.004;-59268.8
49(37)
0.007;-55100.6
(37)(4Q)
0.021;-43878.8
38(47)
0.006;-56276.3
3(47J)
0.008;-52749.4
3477
0.008;-57451.9
3479
0.004;-62795.6
347J
0.005;-60444.4
347K
0.006;-58093.1
4T(38)
0.013;-52749.4
(38)(4K)
0.025;-41527.5
3T(48)
0.008;-52749.4
3(48K)
0.014;-49222.5
38(4T)
0.010;-52749.4
38(4Q)
0.012;-50398.1
49(39)
0.016;-45054.4
(39)(4Q)
0.017;-41527.5
3T(49)
0.009;-51573.8
3(49K)
0.015;-48046.9
39(4J)
0.013;-50398.1
39(4K)
0.017;-48046.9
4(3TQ)
0.014;-48046.9
3(4TJ)
0.013;-49222.5
34TT
0.013;-50398.1
34TQ
0.009;-55741.9
(3J)(4Q)
0.032;-39176.2
3Q(4J)
0.015;-46871.2
34JQ
0.008;-54566.3
(3Q)(4K)
0.025;-36825.0
3Q(4K)
0.018;-44520.0
5(356)
0.010;-52108.1
58(35)
0.014;-49756.9
(35)(5J)
0.029;-38535.0
6(356)
0.012;-50932.5
T(356)
0.013;-53925.0
6(357)
0.007;-57451.9
69(35)
0.009;-55100.6
(35)(6Q)
0.021;-43878.8
(3579)
0.007;-53925.0
(357K)
0.012;-49222.5
79(35)
0.010;-53925.0
(35)(7Q)
0.024;-42703.1
(358T)
0.010;-51573.8
88(35)
0.016;-46230.0
(35)(8J)
0.028;-42703.1
9(359)
0.021;-43878.8
K(359)
0.016;-46871.2
9(35Q)
0.018;-48046.9
J(35T)
0.014;-48046.9
TJ(35)
0.014;-48046.9
(35JQ)
0.022;-45695.6
J(35K)
0.018;-44520.0
(35)(QK)
0.025;-35649.4
55(37)
0.014;-50932.5
3559
0.008;-56276.3
35(5Q)
0.017;-45054.4
(36)(57)
0.013;-49756.9
5(36T)
0.011;-53925.0
5Q(36)
0.010;-51573.8
(56)(38)
0.016;-48581.3
3T(56)
0.009;-53925.0
3(56K)
0.014;-50398.1
36(58)
0.008;-56276.3
36(5T)
0.010;-53925.0
36(5Q)
0.008;-51573.8
57(37)
0.014;-48581.3
(37)(5T)
0.015;-45054.4
5(37K)
0.017;-49222.5
3(579)
0.009;-53925.0
(57)(3Q)
0.027;-42703.1
37(58)
0.006;-55100.6
37(5T)
0.009;-52749.4
37(5Q)
0.015;-50398.1
58(38)
0.012;-46230.0
(38)(5J)
0.017;-42703.1
38(58)
0.015;-46230.0
3(58J)
0.015;-50398.1
3588
0.010;-53925.0
358T
0.005;-59268.8
358Q
0.005;-56917.5
(39)(5T)
0.020;-42703.1
5(39K)
0.021;-46871.2
3(59J)
0.014;-49222.5
3599
0.010;-51573.8
359J
0.007;-56917.5
359K
0.011;-54566.3
5Q(3T)
0.021;-46871.2
(5T)(3Q)
0.022;-39176.2
3T(5J)
0.014;-48046.9
3T(5K)
0.020;-45695.6
5(3JK)
0.018;-44520.0
3(5JK)
0.020;-44520.0
3J(5K)
0.015;-44520.0
3Q(5Q)
0.033;-36825.0
35QK
0.011;-51039.4
67(36)
0.013;-48581.3
(36)(6T)
0.031;-37359.4
6(36K)
0.029;-41527.5
(367T)
0.009;-51573.8
77(36)
0.018;-47405.6
(36)(7T)
0.020;-43878.8
7(36K)
0.014;-48046.9
(368J)
0.016;-49222.5
(36)(89)
0.019;-43878.8
8(36Q)
0.020;-48046.9
T(369)
0.012;-49222.5
9(36T)
0.014;-49222.5
9Q(36)
0.013;-46871.2
Q(36T)
0.015;-45695.6
(36)(TQ)
0.029;-38000.6
(36JK)
0.020;-43344.4
JK(36)
0.016;-43344.4
K(36K)
0.039;-33298.1
3668
0.008;-55100.6
36(6J)
0.024;-43878.8
(37)(67)
0.029;-39710.6
6(37T)
0.010;-51573.8
6Q(37)
0.015;-49222.5
(67)(39)
0.019;-45054.4
3J(67)
0.012;-50398.1
67(38)
0.009;-53925.0
67(3T)
0.012;-51573.8
67(3Q)
0.014;-49222.5
(38)(68)
0.030;-37359.4
6(38J)
0.012;-49222.5
6K(38)
0.019;-46871.2
(68)(3J)
0.023;-41527.5
3K(68)
0.016;-46871.2
36(8T)
0.011;-50398.1
36(8Q)
0.014;-48046.9
6(39T)
0.016;-49222.5
6Q(39)
0.021;-46871.2
(69)(3J)
0.024;-40351.9
3K(69)
0.015;-45695.6
36(9J)
0.015;-48046.9
36(9K)
0.017;-45695.6
(3T)(6Q)
0.024;-38000.6
3J(6T)
0.017;-46871.2
6T(3J)
0.013;-46871.2
6T(3K)
0.014;-44520.0
6Q(3J)
0.024;-44520.0
(6J)(3K)
0.036;-35649.4
6J(3K)
0.020;-43344.4
6K(3Q)
0.020;-42168.8
36(QK)
0.026;-42168.8
(37)(78)
0.025;-37359.4
7(37J)
0.022;-41527.5
7K(37)
0.020;-39176.2
(378Q)
0.018;-46871.2
8(37T)
0.014;-49222.5
8Q(37)
0.017;-46871.2
J(379)
0.018;-46871.2
9T(37)
0.013;-48046.9
(37)(9K)
0.030;-36825.0
K(37T)
0.020;-43344.4
T(37K)
0.024;-43344.4
JJ(37)
0.028;-36825.0
(37QK)
0.024;-40993.1
3777
0.017;-46230.0
37(7T)
0.024;-42703.1
77(3K)
0.026;-39176.2
7(38T)
0.013;-49222.5
7Q(38)
0.016;-46871.2
(78)(3T)
0.017;-41527.5
3Q(78)
0.014;-46871.2
3789
0.006;-58093.1
378J
0.010;-55741.9
378K
0.012;-53390.6
7J(39)
0.017;-46871.2
(79)(3T)
0.028;-40351.9
3Q(79)
0.019;-45695.6
379T
0.009;-55741.9
379Q
0.010;-53390.6
(3T)(7J)
0.025;-38000.6
3T(7T)
0.027;-39176.2
3(7TK)
0.020;-43344.4
3T(7Q)
0.020;-44520.0
7J(3J)
0.025;-36825.0
(7J)(3Q)
0.031;-35649.4
3J(7Q)
0.025;-43344.4
7Q(3Q)
0.033;-34473.8
37QQ
0.022;-42168.8
37KK
0.022;-39817.5
8(38J)
0.031;-39176.2
8K(38)
0.032;-36825.0
(389K)
0.019;-43344.4
9J(38)
0.015;-45695.6
(38TJ)
0.014;-44520.0
(38)(TJ)
0.025;-36825.0
J(38J)
0.026;-35649.4
JQ(38)
0.020;-42168.8
Q(38K)
0.027;-39817.5
3889
0.014;-49222.5
38(8Q)
0.032;-38000.6
(39)(8T)
0.026;-39176.2
8(39K)
0.016;-43344.4
3(89J)
0.019;-45695.6
3899
0.014;-48046.9
389J
0.008;-53390.6
389K
0.010;-51039.4
8Q(3T)
0.017;-43344.4
(8T)(3Q)
0.032;-35649.4
3T(8J)
0.021;-44520.0
3T(8K)
0.022;-42168.8
8(3JK)
0.025;-40993.1
3(8JK)
0.023;-40993.1
3J(8K)
0.021;-40993.1
3Q(8Q)
0.041;-33298.1
38QK
0.015;-47512.5
9T(39)
0.026;-38000.6
(39)(9K)
0.041;-26778.8
K(39T)
0.019;-40993.1
T(39K)
0.023;-40993.1
JJ(39)
0.038;-34473.8
(39QK)
0.027;-38641.9
3999
0.024;-39176.2
39(9Q)
0.028;-35649.4
(3T)(9J)
0.025;-35649.4
3T(9T)
0.023;-36825.0
3(9TK)
0.019;-40993.1
3T(9Q)
0.018;-42168.8
9J(3J)
0.039;-34473.8
(9J)(3Q)
0.036;-33298.1
3J(9Q)
0.023;-40993.1
9Q(3Q)
0.032;-32122.5
39QQ
0.025;-39817.5
39KK
0.022;-37466.2
T(3TK)
0.049;-32122.5
JJ(3T)
0.035;-33298.1
(3TQK)
0.030;-37466.2
3TTT
0.030;-35649.4
3T(TK)
0.037;-32122.5
(3J)(TK)
0.035;-30946.9
3K(TJ)
0.021;-38641.9
3T(JK)
0.027;-38641.9
(TQ)(3K)
0.036;-29771.3
(3K)(TK)
0.072;-20900.6
J(3JK)
0.048;-29771.3
(3J)(QK)
0.048;-28595.6
JJ(3K)
0.049;-29771.3
3Q(JQ)
0.039;-29771.3
3JQK
0.017;-43985.6
QK(3Q)
0.047;-27420.0
QK(3K)
0.058;-26244.4
44(46)
0.015;-45588.8
44(4T)
0.021;-40886.3
(45)(45)
0.032;-37893.8
4(458)
0.010;-49756.9
4T(45)
0.012;-47405.6
(45)(4K)
0.026;-36183.8
4457
0.006;-58627.5
44(5T)
0.017;-47405.6
45(4K)
0.018;-43878.8
4(468)
0.016;-48581.3
4T(46)
0.022;-46230.0
(46)(4K)
0.031;-35008.1
4468
0.007;-56276.3
44(6J)
0.020;-45054.4
(47)(47)
0.032;-33191.3
4(47T)
0.020;-45054.4
4Q(47)
0.018;-42703.1
47(49)
0.022;-46230.0
447J
0.009;-51573.8
48(48)
0.031;-38535.0
(48)(4J)
0.034;-35008.1
4488
0.013;-46230.0
44(8J)
0.020;-42703.1
(49)(49)
0.037;-28488.8
4(49Q)
0.029;-40351.9
44(9T)
0.017;-42703.1
49(4K)
0.033;-39176.2
4(4TQ)
0.023;-39176.2
44(TJ)
0.019;-40351.9
(4J)(4J)
0.054;-23786.2
44JJ
0.028;-39176.2
4Q(4Q)
0.053;-29130.0
(4K)(4K)
0.063;-19083.8
(45)(57)
0.021;-42061.9
5(45T)
0.014;-46230.0
5Q(45)
0.015;-43878.8
8(456)
0.008;-55100.6
Q(456)
0.014;-50398.1
(45)(68)
0.016;-47405.6
6(45J)
0.011;-51573.8
6K(45)
0.018;-49222.5
(457J)
0.012;-50398.1
(45)(78)
0.013;-46230.0
7(45J)
0.010;-50398.1
7K(45)
0.018;-48046.9
(458Q)
0.011;-48046.9
8(45T)
0.015;-50398.1
8Q(45)
0.014;-48046.9
J(459)
0.015;-48046.9
9T(45)
0.016;-49222.5
(45)(9K)
0.024;-38000.6
K(45T)
0.017;-44520.0
T(45K)
0.022;-44520.0
JJ(45)
0.023;-38000.6
(45QK)
0.020;-42168.8
4555
0.011;-52108.1
45(58)
0.016;-48581.3
55(4J)
0.016;-45054.4
455K
0.012;-50398.1
58(46)
0.010;-55100.6
(46)(5J)
0.024;-43878.8
46(56)
0.014;-49756.9
4(569)
0.013;-53925.0
(56)(4Q)
0.024;-42703.1
46(57)
0.008;-56276.3
46(59)
0.011;-53925.0
46(5J)
0.010;-51573.8
46(5K)
0.010;-49222.5
5(479)
0.010;-52749.4
5J(47)
0.011;-50398.1
(57)(48)
0.016;-46230.0
4T(57)
0.012;-51573.8
4(57K)
0.016;-48046.9
47(59)
0.009;-52749.4
47(5J)
0.010;-50398.1
47(5K)
0.016;-48046.9
5(48T)
0.013;-50398.1
5Q(48)
0.015;-48046.9
(58)(4T)
0.023;-42703.1
4Q(58)
0.014;-48046.9
4589
0.006;-59268.8
458J
0.007;-56917.5
458K
0.009;-54566.3
5J(49)
0.014;-48046.9
(59)(4T)
0.021;-41527.5
4Q(59)
0.019;-46871.2
459T
0.007;-56917.5
459Q
0.010;-54566.3
(4T)(5J)
0.022;-39176.2
4T(5T)
0.024;-40351.9
4(5TK)
0.019;-44520.0
4T(5Q)
0.016;-45695.6
5J(4J)
0.025;-38000.6
(5J)(4Q)
0.022;-36825.0
4J(5Q)
0.019;-44520.0
5Q(4Q)
0.031;-35649.4
45QQ
0.023;-43344.4
45KK
0.024;-40993.1
6(469)
0.020;-45054.4
6J(46)
0.020;-42703.1
(4678)
0.012;-52749.4
(467Q)
0.017;-48046.9
7(469)
0.012;-51573.8
7J(46)
0.017;-49222.5
(4689)
0.011;-50398.1
(468K)
0.016;-45695.6
8T(46)
0.013;-49222.5
(46)(8K)
0.027;-38000.6
Q(469)
0.019;-45695.6
(46)(9J)
0.026;-39176.2
T(46T)
0.020;-39176.2
T(46J)
0.017;-45695.6
TK(46)
0.026;-43344.4
(46)(JQ)
0.036;-35649.4
QQ(46)
0.029;-34473.8
46(67)
0.014;-47405.6
66(4T)
0.024;-43878.8
466Q
0.013;-49222.5
68(47)
0.012;-52749.4
(47)(6J)
0.021;-41527.5
47(67)
0.014;-46230.0
4(67T)
0.012;-50398.1
(67)(4K)
0.022;-39176.2
67(49)
0.010;-51573.8
67(4J)
0.011;-49222.5
67(4K)
0.014;-46871.2
69(48)
0.010;-50398.1
(48)(6Q)
0.031;-39176.2
49(68)
0.013;-50398.1
4(68Q)
0.019;-46871.2
46(89)
0.011;-50398.1
46(8J)
0.019;-48046.9
46(8K)
0.017;-45695.6
(49)(6J)
0.024;-39176.2
49(69)
0.020;-41527.5
4(69Q)
0.014;-45695.6
46(9T)
0.017;-48046.9
46(9Q)
0.017;-45695.6
6(4TJ)
0.017;-45695.6
6K(4T)
0.023;-43344.4
(6T)(4K)
0.029;-35649.4
6T(4Q)
0.019;-44520.0
(4J)(6J)
0.035;-29130.0
4J(6J)
0.031;-36825.0
6J(4Q)
0.015;-43344.4
(4Q)(6Q)
0.040;-26778.8
4K(6Q)
0.019;-40993.1
4K(6K)
0.035;-32122.5
79(47)
0.023;-42703.1
(47)(7Q)
0.047;-31481.3
(478T)
0.016;-48046.9
88(47)
0.017;-42703.1
(47)(8J)
0.032;-39176.2
9(479)
0.025;-40351.9
K(479)
0.022;-43344.4
9(47Q)
0.021;-44520.0
J(47T)
0.020;-44520.0
TJ(47)
0.015;-44520.0
(47JQ)
0.027;-42168.8
J(47K)
0.025;-40993.1
(47)(QK)
0.027;-32122.5
77(49)
0.025;-42703.1
477J
0.013;-48046.9
78(48)
0.026;-42703.1
(48)(7J)
0.029;-39176.2
48(78)
0.016;-42703.1
4(78J)
0.017;-46871.2
4788
0.014;-50398.1
478T
0.010;-55741.9
478Q
0.010;-53390.6
(49)(7T)
0.026;-39176.2
7(49K)
0.017;-43344.4
4(79J)
0.013;-45695.6
4799
0.012;-48046.9
479J
0.010;-53390.6
479K
0.011;-51039.4
7Q(4T)
0.021;-43344.4
(7T)(4Q)
0.023;-35649.4
4T(7J)
0.015;-44520.0
4T(7K)
0.024;-42168.8
7(4JK)
0.021;-40993.1
4(7JK)
0.026;-40993.1
4J(7K)
0.027;-40993.1
4Q(7Q)
0.027;-33298.1
47QK
0.012;-47512.5
89(48)
0.023;-40351.9
(48)(8Q)
0.033;-29130.0
(489J)
0.020;-44520.0
(48)(9T)
0.030;-38000.6
9(48K)
0.021;-42168.8
(48TK)
0.024;-40993.1
TQ(48)
0.022;-42168.8
K(48J)
0.030;-39817.5
Q(48Q)
0.045;-32122.5
KK(48)
0.042;-29771.3
88(4J)
0.022;-38000.6
488K
0.025;-43344.4
8J(49)
0.026;-44520.0
(89)(4T)
0.027;-38000.6
4Q(89)
0.022;-43344.4
489T
0.010;-53390.6
489Q
0.012;-51039.4
(4T)(8J)
0.031;-35649.4
4T(8T)
0.032;-36825.0
4(8TK)
0.022;-40993.1
4T(8Q)
0.025;-42168.8
8J(4J)
0.025;-34473.8
(8J)(4Q)
0.034;-33298.1
4J(8Q)
0.029;-40993.1
8Q(4Q)
0.040;-32122.5
48QQ
0.023;-39817.5
48KK
0.029;-37466.2
9(49Q)
0.025;-34473.8
J(49T)
0.019;-42168.8
TJ(49)
0.021;-42168.8
(49JQ)
0.019;-39817.5
J(49K)
0.019;-38641.9
(49)(QK)
0.038;-29771.3
99(4J)
0.036;-35649.4
499K
0.020;-40993.1
9Q(4T)
0.026;-40993.1
(9T)(4Q)
0.039;-33298.1
4T(9J)
0.029;-42168.8
4T(9K)
0.026;-39817.5
9(4JK)
0.024;-38641.9
4(9JK)
0.030;-38641.9
4J(9K)
0.034;-38641.9
4Q(9Q)
0.049;-30946.9
49QK
0.024;-45161.3
TJ(4T)
0.035;-33298.1
(4TJQ)
0.028;-38641.9
J(4TK)
0.024;-37466.2
(4T)(QK)
0.044;-28595.6
TT(4Q)
0.030;-32122.5
T(4JQ)
0.025;-38641.9
4(TJQ)
0.031;-38641.9
4T(JQ)
0.026;-38641.9
T(4QK)
0.027;-36290.6
TQ(4K)
0.031;-36290.6
JJ(4J)
0.054;-23251.9
(4JQK)
0.042;-35115.0
4JJJ
0.035;-30946.9
JQ(4Q)
0.036;-28595.6
4JQQ
0.034;-36290.6
4JKK
0.030;-33939.4
QQ(4K)
0.046;-26244.4
4KKK
0.047;-23893.1
55(59)
0.027;-38535.0
55(5K)
0.041;-33832.5
(56)(58)
0.026;-38535.0
5(56J)
0.019;-42703.1
5K(56)
0.024;-40351.9
56(59)
0.016;-45054.4
556J
0.009;-50398.1
57(57)
0.025;-38535.0
(57)(5T)
0.030;-35008.1
5(57K)
0.031;-39176.2
55(79)
0.021;-43878.8
57(5Q)
0.019;-40351.9
5(589)
0.016;-42703.1
5J(58)
0.026;-40351.9
58(59)
0.022;-42703.1
558J
0.017;-48046.9
59(59)
0.030;-33832.5
(59)(5Q)
0.034;-30305.6
559T
0.016;-48046.9
55(9K)
0.025;-36825.0
(5T)(5Q)
0.057;-29130.0
55TJ
0.016;-45695.6
5J(5J)
0.053;-29130.0
5J(5Q)
0.028;-35649.4
5(5QK)
0.035;-33298.1
5K(5K)
0.055;-24427.5
68(56)
0.016;-45054.4
(56)(6J)
0.039;-33832.5
7(567)
0.014;-45054.4
J(567)
0.016;-48046.9
78(56)
0.012;-51573.8
(56)(7J)
0.023;-40351.9
8(568)
0.020;-42703.1
Q(568)
0.017;-45695.6
(56)(8T)
0.025;-40351.9
8(56K)
0.022;-44520.0
(569Q)
0.015;-44520.0
9(56J)
0.016;-45695.6
9K(56)
0.019;-43344.4
TT(56)
0.023;-38000.6
(56)(TK)
0.041;-34473.8
J(56Q)
0.018;-42168.8
K(56Q)
0.026;-39817.5
66(57)
0.017;-46230.0
5669
0.010;-51573.8
56(6Q)
0.025;-40351.9
(57)(68)
0.016;-43878.8
6(57J)
0.015;-48046.9
6K(57)
0.013;-45695.6
(67)(5T)
0.027;-41527.5
5Q(67)
0.017;-46871.2
5678
0.008;-59268.8
567T
0.007;-56917.5
567Q
0.010;-54566.3
(58)(69)
0.026;-41527.5
6(58Q)
0.020;-45695.6
5(689)
0.015;-49222.5
(68)(5Q)
0.031;-38000.6
58(69)
0.018;-49222.5
58(6J)
0.014;-46871.2
58(6K)
0.015;-44520.0
6(59J)
0.017;-45695.6
6K(59)
0.020;-43344.4
(69)(5Q)
0.027;-36825.0
59(6T)
0.020;-46871.2
59(6Q)
0.020;-44520.0
6T(5T)
0.035;-38000.6
(5T)(6K)
0.037;-34473.8
5Q(6T)
0.016;-43344.4
56TJ
0.008;-52215.0
56TK
0.014;-49863.8
6K(5J)
0.024;-40993.1
56JJ
0.026;-43344.4
56JK
0.012;-48688.1
5(6QK)
0.023;-39817.5
6K(5K)
0.040;-30946.9
(57)(79)
0.029;-33832.5
7(57Q)
0.024;-38000.6
9(578)
0.012;-48046.9
K(578)
0.017;-43344.4
8(57J)
0.014;-45695.6
8K(57)
0.021;-43344.4
(579K)
0.022;-42168.8
9J(57)
0.016;-44520.0
(57TJ)
0.021;-43344.4
(57)(TJ)
0.030;-35649.4
J(57J)
0.039;-34473.8
JQ(57)
0.024;-40993.1
Q(57K)
0.026;-38641.9
5778
0.014;-50398.1
57(7J)
0.022;-39176.2
(58)(78)
0.030;-33832.5
7(58J)
0.021;-45695.6
7K(58)
0.022;-43344.4
(78)(5J)
0.029;-38000.6
5K(78)
0.020;-43344.4
57(8T)
0.018;-46871.2
57(8Q)
0.023;-44520.0
7(59T)
0.018;-45695.6
7Q(59)
0.024;-43344.4
(79)(5J)
0.025;-36825.0
5K(79)
0.021;-42168.8
57(9J)
0.017;-44520.0
57(9K)
0.021;-42168.8
(5T)(7Q)
0.036;-34473.8
5J(7T)
0.019;-43344.4
7T(5J)
0.018;-43344.4
7T(5K)
0.029;-40993.1
7Q(5J)
0.021;-40993.1
(7J)(5K)
0.034;-32122.5
7J(5K)
0.020;-39817.5
7K(5Q)
0.027;-38641.9
57(QK)
0.027;-38641.9
(58)(89)
0.048;-31481.3
8(58Q)
0.034;-35649.4
T(589)
0.020;-44520.0
9(58T)
0.020;-44520.0
9Q(58)
0.028;-42168.8
Q(58T)
0.023;-40993.1
(58)(TQ)
0.033;-33298.1
(58JK)
0.027;-38641.9
JK(58)
0.026;-38641.9
K(58K)
0.035;-28595.6
588T
0.014;-45695.6
58(8K)
0.038;-34473.8
(59)(8J)
0.030;-35649.4
59(89)
0.022;-38000.6
5(89Q)
0.020;-42168.8
58(9T)
0.020;-44520.0
58(9Q)
0.026;-42168.8
8(5TJ)
0.024;-42168.8
8K(5T)
0.027;-39817.5
(8T)(5K)
0.038;-32122.5
8T(5Q)
0.020;-40993.1
(5J)(8J)
0.063;-25603.1
5J(8J)
0.039;-33298.1
8J(5Q)
0.026;-39817.5
(5Q)(8Q)
0.047;-23251.9
5K(8Q)
0.021;-37466.2
5K(8K)
0.043;-28595.6
9J(59)
0.034;-34473.8
(59TJ)
0.022;-40993.1
(59)(TJ)
0.036;-33298.1
J(59J)
0.034;-32122.5
JQ(59)
0.027;-38641.9
Q(59K)
0.028;-36290.6
599T
0.019;-43344.4
59(9K)
0.031;-32122.5
(5T)(9Q)
0.036;-32122.5
5J(9T)
0.029;-40993.1
9T(5J)
0.023;-40993.1
9T(5K)
0.025;-38641.9
9Q(5J)
0.034;-38641.9
(9J)(5K)
0.043;-29771.3
9J(5K)
0.029;-37466.2
9K(5Q)
0.035;-36290.6
59(QK)
0.027;-36290.6
(5T)(TJ)
0.054;-24427.5
J(5TJ)
0.047;-30946.9
JQ(5T)
0.036;-37466.2
Q(5TK)
0.033;-35115.0
5TTJ
0.021;-39817.5
TJ(5J)
0.039;-30946.9
(TJ)(5Q)
0.038;-29771.3
5J(TQ)
0.028;-37466.2
TQ(5Q)
0.037;-28595.6
5TQQ
0.023;-36290.6
5TKK
0.036;-33939.4
Q(5JQ)
0.053;-27420.0
KK(5J)
0.040;-25068.7
(5Q)(JQ)
0.058;-19725.0
5K(JQ)
0.027;-33939.4
5K(JK)
0.047;-25068.7
5QQQ
0.037;-26244.4
KK(5K)
0.069;-15022.5
6669
0.028;-42703.1
666K
0.027;-38000.6
69(67)
0.025;-41527.5
(67)(6Q)
0.043;-30305.6
6678
0.011;-50398.1
66(7J)
0.030;-39176.2
(68)(68)
0.043;-26137.5
6(68J)
0.028;-38000.6
6K(68)
0.033;-35649.4
68(6J)
0.030;-38000.6
668K
0.021;-43344.4
6J(69)
0.029;-36825.0
69(6T)
0.027;-38000.6
669Q
0.017;-43344.4
6J(6T)
0.027;-35649.4
6T(6J)
0.026;-35649.4
66TK
0.020;-40993.1
6K(6J)
0.042;-32122.5
(6Q)(6Q)
0.087;-16732.5
66QK
0.027;-38641.9
7(679)
0.024;-40351.9
7J(67)
0.031;-38000.6
(6789)
0.016;-46871.2
(678K)
0.029;-42168.8
8T(67)
0.018;-45695.6
(67)(8K)
0.027;-34473.8
Q(679)
0.021;-42168.8
(67)(9J)
0.038;-35649.4
T(67T)
0.036;-35649.4
T(67J)
0.019;-42168.8
TK(67)
0.022;-39817.5
(67)(JQ)
0.050;-32122.5
QQ(67)
0.035;-30946.9
67(78)
0.020;-41527.5
77(6J)
0.024;-38000.6
677K
0.021;-43344.4
7T(68)
0.020;-45695.6
(68)(7K)
0.031;-34473.8
6T(78)
0.017;-45695.6
6(78K)
0.021;-42168.8
68(7T)
0.018;-45695.6
68(7Q)
0.020;-43344.4
79(69)
0.037;-38000.6
(69)(7Q)
0.035;-34473.8
6T(79)
0.013;-44520.0
6(79K)
0.023;-40993.1
69(7J)
0.015;-43344.4
69(7K)
0.019;-40993.1
7(6TQ)
0.028;-40993.1
6(7TJ)
0.020;-42168.8
67TT
0.022;-43344.4
67TQ
0.012;-48688.1
(6J)(7Q)
0.042;-32122.5
6Q(7J)
0.028;-39817.5
67JQ
0.013;-47512.5
(6Q)(7K)
0.052;-29771.3
6Q(7K)
0.029;-37466.2
8(689)
0.032;-38000.6
8J(68)
0.034;-35649.4
(689T)
0.016;-43344.4
99(68)
0.028;-36825.0
(68)(9Q)
0.042;-33298.1
(68TQ)
0.025;-39817.5
T(68Q)
0.024;-39817.5
Q(68J)
0.029;-38641.9
(68)(JK)
0.041;-29771.3
QK(68)
0.029;-36290.6
68(8T)
0.031;-36825.0
88(6K)
0.043;-33298.1
8(69J)
0.018;-42168.8
8K(69)
0.023;-39817.5
(89)(6Q)
0.035;-33298.1
69(8T)
0.020;-43344.4
69(8Q)
0.020;-40993.1
8T(6T)
0.030;-34473.8
(6T)(8K)
0.040;-30946.9
6Q(8T)
0.030;-39817.5
68TJ
0.011;-48688.1
68TK
0.016;-46336.9
8K(6J)
0.032;-37466.2
68JJ
0.024;-39817.5
68JK
0.021;-45161.3
6(8QK)
0.032;-36290.6
8K(6K)
0.037;-27420.0
(69)(9J)
0.046;-25603.1
T(69T)
0.037;-33298.1
T(69J)
0.022;-39817.5
TK(69)
0.020;-37466.2
(69)(JQ)
0.039;-29771.3
QQ(69)
0.041;-28595.6
69(9T)
0.026;-34473.8
99(6K)
0.038;-30946.9
9(6TQ)
0.030;-38641.9
6(9TJ)
0.034;-39817.5
69TT
0.018;-40993.1
69TQ
0.014;-46336.9
(6J)(9Q)
0.041;-29771.3
6Q(9J)
0.026;-37466.2
69JQ
0.020;-45161.3
(6Q)(9K)
0.046;-27420.0
6Q(9K)
0.029;-35115.0
T(6TJ)
0.046;-30946.9
TK(6T)
0.037;-28595.6
(6T)(JQ)
0.043;-28595.6
QQ(6T)
0.045;-27420.0
6T(TJ)
0.046;-30946.9
(6J)(TJ)
0.056;-22076.3
6J(TJ)
0.041;-29771.3
TJ(6Q)
0.035;-36290.6
(6Q)(TQ)
0.071;-19725.0
6K(TQ)
0.035;-33939.4
6K(TK)
0.055;-25068.7
JK(6J)
0.044;-26244.4
K(6JK)
0.045;-23893.1
6JJK
0.035;-33939.4
6(JQK)
0.032;-32763.8
JK(6K)
0.039;-23893.1
KK(6Q)
0.066;-22717.5
6QKK
0.044;-30412.5
77(7T)
0.042;-30305.6
(78)(78)
0.055;-23786.2
7(78J)
0.032;-35649.4
7K(78)
0.043;-33298.1
78(7J)
0.030;-35649.4
778K
0.026;-40993.1
7J(79)
0.035;-34473.8
79(7T)
0.027;-35649.4
779Q
0.030;-40993.1
7J(7T)
0.040;-33298.1
7T(7J)
0.035;-33298.1
77TK
0.032;-38641.9
7K(7J)
0.038;-29771.3
(7Q)(7Q)
0.090;-14381.2
77QK
0.036;-36290.6
8(78T)
0.026;-35649.4
8Q(78)
0.026;-33298.1
J(789)
0.024;-40993.1
9T(78)
0.018;-42168.8
(78)(9K)
0.040;-30946.9
K(78T)
0.023;-37466.2
T(78K)
0.030;-37466.2
JJ(78)
0.039;-30946.9
(78QK)
0.031;-35115.0
7888
0.026;-38000.6
78(8J)
0.037;-34473.8
(79)(89)
0.050;-27954.4
8(79Q)
0.025;-39817.5
7(89T)
0.025;-42168.8
(89)(7K)
0.034;-30946.9
89(7J)
0.025;-40993.1
89(7K)
0.024;-38641.9
8J(7T)
0.030;-39817.5
(8T)(7J)
0.033;-32122.5
7K(8T)
0.032;-37466.2
78(TQ)
0.027;-38641.9
8(7JQ)
0.030;-37466.2
7(8JQ)
0.029;-37466.2
78(JQ)
0.022;-37466.2
8(7QK)
0.030;-35115.0
8Q(7K)
0.044;-35115.0
99(79)
0.043;-26778.8
(79)(9Q)
0.060;-23251.9
(79TQ)
0.025;-37466.2
T(79Q)
0.026;-37466.2
Q(79J)
0.025;-36290.6
(79)(JK)
0.055;-27420.0
QK(79)
0.039;-33939.4
79(9J)
0.028;-32122.5
(7T)(9T)
0.039;-24427.5
9(7TK)
0.035;-36290.6
7(9TQ)
0.023;-37466.2
79(TJ)
0.024;-38641.9
79(TK)
0.032;-36290.6
(7J)(9K)
0.048;-27420.0
7K(9J)
0.035;-35115.0
79(JK)
0.026;-35115.0
(9Q)(7K)
0.050;-26244.4
(7K)(9K)
0.065;-17373.8
T(7TQ)
0.047;-28595.6
Q(7TJ)
0.035;-35115.0
(7T)(JK)
0.053;-26244.4
QK(7T)
0.027;-32763.8
7T(TQ)
0.058;-28595.6
(7J)(TQ)
0.052;-27420.0
7Q(TJ)
0.025;-35115.0
7TJQ
0.022;-42810.0
(7Q)(TK)
0.063;-25068.7
7Q(TK)
0.043;-32763.8
J(7JQ)
0.054;-26244.4
K(7JQ)
0.038;-31588.1
JJ(7Q)
0.053;-26244.4
J(7QK)
0.048;-31588.1
JQ(7K)
0.043;-31588.1
QQ(7Q)
0.061;-16198.1
7Q(QK)
0.079;-22717.5
8888
0.039;-29130.0
888Q
0.046;-32122.5
8(89J)
0.043;-32122.5
8K(89)
0.049;-29771.3
89(8Q)
0.040;-30946.9
8(8TJ)
0.039;-30946.9
8K(8T)
0.051;-28595.6
8T(8K)
0.047;-28595.6
8(8JK)
0.045;-27420.0
88(JK)
0.052;-27420.0
8Q(8K)
0.046;-26244.4
(89)(9T)
0.068;-24427.5
9(89K)
0.031;-28595.6
(89TK)
0.030;-35115.0
TQ(89)
0.030;-36290.6
K(89J)
0.035;-33939.4
Q(89Q)
0.047;-26244.4
KK(89)
0.051;-23893.1
99(8Q)
0.040;-29771.3
9(8TJ)
0.032;-37466.2
9K(8T)
0.030;-35115.0
(9T)(8K)
0.034;-27420.0
9T(8Q)
0.034;-36290.6
(8J)(9J)
0.049;-20900.6
8J(9J)
0.055;-28595.6
9J(8Q)
0.037;-35115.0
(8Q)(9Q)
0.071;-18549.4
8K(9Q)
0.032;-32763.8
8K(9K)
0.052;-23893.1
TQ(8T)
0.043;-27420.0
K(8TJ)
0.049;-32763.8
Q(8TQ)
0.051;-25068.7
KK(8T)
0.061;-22717.5
