AAAA
0.328;260.0
5AAA
0.283;-4442.5
9AAA
0.276;-3232.5
KAAA
0.340;-2022.5
4A(2A)
0.218;-8375.0
(2A)(7A)
0.253;-5487.5
A(2TA)
0.243;-6560.0
QA(2A)
0.293;-5955.0
2A(4A)
0.207;-8375.0
26AA
0.195;-9750.0
AA(29)
0.239;-6862.5
2A(QA)
0.262;-5955.0
A(34A)
0.194;-8072.5
6A(3A)
0.250;-7467.5
(3A)(9A)
0.292;-4580.0
A(3QA)
0.248;-5652.5
AA(34)
0.207;-8072.5
3A(7A)
0.224;-7165.0
39AA
0.272;-8540.0
AA(3Q)
0.243;-5652.5
(4A)(5A)
0.317;-5487.5
A(48A)
0.246;-6560.0
TA(4A)
0.261;-5955.0
(4A)(KA)
0.318;-3067.5
46AA
0.223;-9145.0
AA(49)
0.258;-6257.5
4A(QA)
0.285;-5350.0
A(56A)
0.203;-6862.5
8A(5A)
0.268;-6257.5
(5A)(JA)
0.348;-3370.0
55AA
0.248;-7165.0
AA(58)
0.244;-6257.5
5A(JA)
0.253;-5350.0
5KAA
0.267;-6725.0
8A(6A)
0.239;-5955.0
(6A)(JA)
0.263;-3067.5
66AA
0.235;-6560.0
AA(69)
0.270;-5652.5
6A(QA)
0.305;-4745.0
A(78A)
0.262;-5652.5
TA(7A)
0.290;-5047.5
(7A)(KA)
0.332;-2160.0
79AA
0.247;-7330.0
AA(7Q)
0.245;-4442.5
(8A)(9A)
0.243;-3067.5
A(8QA)
0.275;-4140.0
AA(89)
0.225;-5047.5
8A(QA)
0.310;-4140.0
A(9TA)
0.286;-4442.5
QA(9A)
0.323;-3837.5
9A(JA)
0.303;-4140.0
9KAA
0.203;-5515.0
QA(TA)
0.252;-3535.0
TA(QA)
0.255;-3535.0
A(JQA)
0.284;-3232.5
AA(JQ)
0.302;-3232.5
(QA)(KA)
0.351;-647.5
KKAA
0.281;-2325.0
2(25A)
0.167;-11702.5
27(2A)
0.228;-11097.5
(2T)(2A)
0.288;-8210.0
2(2KA)
0.239;-9282.5
(236A)
0.200;-13077.5
(23TA)
0.175;-11867.5
33(2A)
0.184;-12005.0
(36)(2A)
0.205;-11097.5
3(29A)
0.177;-12170.0
3J(2A)
0.223;-11565.0
(245A)
0.156;-13077.5
(249A)
0.186;-11867.5
(24KA)
0.191;-10657.5
46(2A)
0.155;-12775.0
(49)(2A)
0.240;-9887.5
4(2QA)
0.223;-10960.0
6(25A)
0.230;-12472.5
T(25A)
0.164;-11262.5
5(26A)
0.208;-12472.5
58(2A)
0.228;-11867.5
(5J)(2A)
0.176;-8980.0
6(26A)
0.175;-10190.0
T(26A)
0.149;-10960.0
6(27A)
0.150;-11867.5
69(2A)
0.169;-11262.5
(6Q)(2A)
0.201;-8375.0
(279A)
0.165;-10960.0
(27KA)
0.212;-9750.0
79(2A)
0.197;-10960.0
(7Q)(2A)
0.226;-8072.5
(28TA)
0.180;-10355.0
88(2A)
0.277;-8980.0
(8J)(2A)
0.201;-8072.5
9(29A)
0.177;-8375.0
K(29A)
0.225;-9145.0
9(2QA)
0.243;-9447.5
J(2TA)
0.197;-9447.5
TJ(2A)
0.249;-9447.5
(2JQA)
0.184;-8842.5
J(2KA)
0.225;-8540.0
(QK)(2A)
0.213;-6257.5
22(4A)
0.144;-12005.0
226A
0.213;-13380.0
2A(29)
0.245;-10492.5
22(QA)
0.239;-9585.0
2(34A)
0.169;-13682.5
26(3A)
0.197;-13077.5
(29)(3A)
0.214;-10190.0
2(3QA)
0.195;-11262.5
A(234)
0.154;-13682.5
(23)(7A)
0.203;-10795.0
9A(23)
0.215;-12170.0
A(23Q)
0.162;-11262.5
2A(34)
0.182;-13682.5
2A(36)
0.210;-13077.5
2A(38)
0.195;-12472.5
2A(3T)
0.168;-11867.5
2A(3Q)
0.257;-11262.5
2(45A)
0.157;-13077.5
27(4A)
0.204;-12472.5
(2T)(4A)
0.215;-9585.0
2(4KA)
0.215;-10657.5
A(246)
0.148;-12775.0
(24)(9A)
0.227;-9887.5
JA(24)
0.217;-11262.5
24(5A)
0.137;-13077.5
24(7A)
0.167;-12472.5
24(9A)
0.163;-11867.5
24(JA)
0.167;-11262.5
24(KA)
0.207;-10657.5
26(5A)
0.216;-12472.5
(29)(5A)
0.220;-9585.0
2(5QA)
0.261;-10657.5
A(256)
0.198;-12472.5
(25)(9A)
0.265;-9585.0
JA(25)
0.163;-10960.0
25(6A)
0.177;-12472.5
25(8A)
0.166;-11867.5
25(TA)
0.201;-11262.5
25(QA)
0.243;-10657.5
(26)(6A)
0.214;-8210.0
2(69A)
0.258;-11262.5
2J(6A)
0.169;-10657.5
(26)(7A)
0.197;-9887.5
9A(26)
0.188;-11262.5
A(26Q)
0.213;-10355.0
2A(67)
0.184;-11867.5
2A(69)
0.165;-11262.5
2A(6J)
0.180;-10657.5
2A(6K)
0.179;-10052.5
(29)(7A)
0.193;-8980.0
2(7QA)
0.233;-10052.5
A(278)
0.199;-11262.5
(27)(JA)
0.189;-8375.0
KA(27)
0.192;-9750.0
2A(79)
0.206;-10960.0
2A(7J)
0.242;-10355.0
2A(7K)
0.216;-9750.0
(2T)(8A)
0.259;-8375.0
2(8KA)
0.240;-9447.5
A(28T)
0.206;-10355.0
(28)(KA)
0.191;-7467.5
28(TA)
0.220;-10355.0
28(QA)
0.170;-9750.0
(29)(9A)
0.274;-6395.0
2(9QA)
0.184;-9447.5
A(29T)
0.238;-10052.5
(29)(KA)
0.237;-7165.0
29(JA)
0.264;-9750.0
29(KA)
0.232;-9145.0
2J(TA)
0.223;-9447.5
(2T)(JA)
0.205;-7467.5
KA(2T)
0.179;-8842.5
2A(TQ)
0.197;-9145.0
2(JQA)
0.249;-8842.5
A(2JQ)
0.212;-8842.5
2A(JQ)
0.205;-8842.5
2(QKA)
0.243;-8237.5
2Q(KA)
0.243;-8237.5
33(3A)
0.227;-9722.5
(36)(3A)
0.240;-8815.0
3(39A)
0.219;-9887.5
3J(3A)
0.245;-9282.5
(345A)
0.187;-12775.0
(349A)
0.193;-11565.0
(34KA)
0.255;-10355.0
46(3A)
0.169;-12472.5
(49)(3A)
0.169;-9585.0
4(3QA)
0.181;-10657.5
6(35A)
0.146;-12170.0
T(35A)
0.228;-10960.0
5(36A)
0.205;-12170.0
58(3A)
0.217;-11565.0
(5J)(3A)
0.263;-8677.5
6(36A)
0.165;-9887.5
T(36A)
0.242;-10657.5
6(37A)
0.188;-11565.0
69(3A)
0.160;-10960.0
(6Q)(3A)
0.237;-8072.5
(379A)
0.254;-10657.5
(37KA)
0.222;-9447.5
79(3A)
0.179;-10657.5
(7Q)(3A)
0.240;-7770.0
(38TA)
0.235;-10052.5
88(3A)
0.213;-8677.5
(8J)(3A)
0.177;-7770.0
9(39A)
0.170;-8072.5
K(39A)
0.251;-8842.5
9(3QA)
0.269;-9145.0
J(3TA)
0.288;-9145.0
TJ(3A)
0.225;-9145.0
(3JQA)
0.250;-8540.0
J(3KA)
0.193;-8237.5
(QK)(3A)
0.263;-5955.0
33(5A)
0.157;-11097.5
337A
0.160;-12472.5
3A(3T)
0.174;-9585.0
33(KA)
0.267;-8677.5
3(46A)
0.163;-12472.5
38(4A)
0.216;-11867.5
(3J)(4A)
0.259;-8980.0
4A(34)
0.196;-11097.5
A(347)
0.174;-12170.0
(34)(TA)
0.186;-9282.5
QA(34)
0.205;-10657.5
345A
0.147;-14755.0
347A
0.164;-14150.0
349A
0.204;-13545.0
34JA
0.167;-12940.0
34KA
0.193;-12335.0
37(5A)
0.234;-11867.5
(3T)(5A)
0.195;-8980.0
3(5KA)
0.241;-10052.5
A(357)
0.219;-11867.5
(35)(TA)
0.215;-8980.0
QA(35)
0.242;-10355.0
356A
0.177;-14150.0
358A
0.184;-13545.0
35TA
0.218;-12940.0
35QA
0.169;-12335.0
(37)(6A)
0.240;-9585.0
3(6TA)
0.193;-10657.5
3Q(6A)
0.228;-10052.5
(36)(8A)
0.227;-9282.5
TA(36)
0.168;-10657.5
A(36K)
0.187;-9750.0
6A(38)
0.225;-11262.5
6A(3T)
0.195;-10657.5
6A(3Q)
0.198;-10052.5
37(7A)
0.173;-9282.5
(3T)(7A)
0.211;-8375.0
3(7KA)
0.215;-9447.5
A(379)
0.213;-10657.5
(37)(QA)
0.252;-7770.0
7A(38)
0.207;-10960.0
7A(3T)
0.152;-10355.0
7A(3Q)
0.184;-9750.0
38(8A)
0.289;-8677.5
(3J)(8A)
0.202;-7770.0
8A(38)
0.200;-8677.5
A(38J)
0.163;-9750.0
388A
0.164;-10657.5
38TA
0.173;-12032.5
38QA
0.207;-11427.5
(3T)(9A)
0.252;-7770.0
3(9KA)
0.196;-8842.5
A(39J)
0.163;-9447.5
399A
0.189;-10052.5
39JA
0.203;-11427.5
39KA
0.171;-10822.5
3Q(TA)
0.224;-8842.5
(3T)(QA)
0.213;-6862.5
TA(3J)
0.177;-9145.0
TA(3K)
0.256;-8540.0
3(JKA)
0.226;-8237.5
A(3JK)
0.218;-8237.5
JA(3K)
0.245;-8237.5
QA(3Q)
0.242;-6257.5
3QKA
0.248;-9915.0
45(4A)
0.214;-10492.5
(48)(4A)
0.186;-7605.0
4(4JA)
0.246;-8677.5
4K(4A)
0.197;-8072.5
(459A)
0.194;-10960.0
(45KA)
0.182;-9750.0
57(4A)
0.145;-11565.0
(5T)(4A)
0.236;-8677.5
5(4KA)
0.247;-9750.0
(469A)
0.171;-10657.5
(46KA)
0.211;-9447.5
68(4A)
0.153;-10960.0
(6J)(4A)
0.260;-8072.5
7(47A)
0.197;-8980.0
J(47A)
0.208;-9750.0
78(4A)
0.203;-10657.5
(7J)(4A)
0.227;-7770.0
8(48A)
0.172;-8375.0
Q(48A)
0.248;-9145.0
(8T)(4A)
0.203;-7770.0
8(4KA)
0.265;-8842.5
(49QA)
0.229;-8842.5
9(4JA)
0.287;-9145.0
9K(4A)
0.244;-8540.0
TT(4A)
0.215;-7165.0
(TK)(4A)
0.281;-6257.5
J(4QA)
0.235;-8237.5
K(4QA)
0.260;-7632.5
44(5A)
0.200;-10492.5
447A
0.205;-11867.5
4A(4T)
0.277;-8980.0
44(KA)
0.196;-8072.5
4(57A)
0.188;-11565.0
49(5A)
0.209;-10960.0
(4Q)(5A)
0.225;-8072.5
6A(45)
0.221;-11867.5
A(459)
0.245;-10960.0
(45)(QA)
0.227;-8072.5
5A(46)
0.197;-11867.5
5A(48)
0.224;-11262.5
5A(4T)
0.249;-10657.5
5A(4Q)
0.237;-10052.5
46(6A)
0.185;-9585.0
(49)(6A)
0.197;-8677.5
4(6QA)
0.210;-9750.0
A(467)
0.185;-11262.5
(46)(TA)
0.174;-8375.0
QA(46)
0.207;-9750.0
467A
0.151;-13242.5
469A
0.189;-12637.5
46JA
0.155;-12032.5
46KA
0.145;-11427.5
49(7A)
0.209;-10355.0
(4Q)(7A)
0.211;-7467.5
8A(47)
0.172;-10657.5
A(47J)
0.248;-9750.0
477A
0.197;-10960.0
479A
0.143;-12335.0
47JA
0.183;-11730.0
47KA
0.171;-11125.0
4T(8A)
0.185;-9750.0
(4K)(8A)
0.254;-6862.5
TA(48)
0.164;-9750.0
A(48K)
0.199;-8842.5
8A(4T)
0.185;-9750.0
8A(4Q)
0.178;-9145.0
49(9A)
0.296;-7770.0
(4Q)(9A)
0.286;-6862.5
TA(49)
0.212;-9447.5
A(49K)
0.183;-8540.0
9A(4J)
0.232;-9145.0
9A(4K)
0.195;-8540.0
4(TQA)
0.201;-8540.0
A(4TJ)
0.219;-8842.5
4TTA
0.228;-9145.0
4TQA
0.233;-10520.0
(4Q)(JA)
0.210;-6257.5
QA(4J)
0.230;-8237.5
4JQA
0.202;-10217.5
(4K)(QA)
0.274;-5652.5
QA(4K)
0.210;-7632.5
5(56A)
0.209;-9585.0
58(5A)
0.260;-8980.0
(5J)(5A)
0.262;-6092.5
6(56A)
0.199;-9282.5
T(56A)
0.176;-10052.5
6(57A)
0.178;-10960.0
69(5A)
0.212;-10355.0
(6Q)(5A)
0.247;-7467.5
(579A)
0.202;-10052.5
(57KA)
0.228;-8842.5
79(5A)
0.215;-10052.5
(7Q)(5A)
0.213;-7165.0
(58TA)
0.195;-9447.5
88(5A)
0.291;-8072.5
(8J)(5A)
0.243;-7165.0
9(59A)
0.241;-7467.5
K(59A)
0.210;-8237.5
9(5QA)
0.223;-8540.0
J(5TA)
0.177;-8540.0
TJ(5A)
0.235;-8540.0
(5JQA)
0.260;-7935.0
J(5KA)
0.248;-7632.5
(QK)(5A)
0.258;-5350.0
55(7A)
0.198;-9282.5
559A
0.200;-10657.5
5A(5Q)
0.220;-7770.0
(57)(6A)
0.232;-8980.0
5(6TA)
0.178;-10052.5
5Q(6A)
0.190;-9447.5
(56)(8A)
0.278;-8677.5
TA(56)
0.247;-10052.5
A(56K)
0.243;-9145.0
6A(58)
0.181;-10657.5
6A(5T)
0.212;-10052.5
6A(5Q)
0.208;-9447.5
57(7A)
0.193;-8677.5
(5T)(7A)
0.219;-7770.0
5(7KA)
0.218;-8842.5
A(579)
0.222;-10052.5
(57)(QA)
0.259;-7165.0
7A(58)
0.188;-10355.0
7A(5T)
0.203;-9750.0
7A(5Q)
0.187;-9145.0
58(8A)
0.208;-8072.5
(5J)(8A)
0.290;-7165.0
8A(58)
0.188;-8072.5
A(58J)
0.241;-9145.0
588A
0.196;-10052.5
58TA
0.187;-11427.5
58QA
0.226;-10822.5
(5T)(9A)
0.191;-7165.0
5(9KA)
0.231;-8237.5
A(59J)
0.195;-8842.5
599A
0.235;-9447.5
59JA
0.230;-10822.5
59KA
0.241;-10217.5
5Q(TA)
0.268;-8237.5
(5T)(QA)
0.310;-6257.5
TA(5J)
0.225;-8540.0
TA(5K)
0.269;-7935.0
5(JKA)
0.212;-7632.5
A(5JK)
0.188;-7632.5
JA(5K)
0.201;-7632.5
QA(5Q)
0.250;-5652.5
5QKA
0.242;-9310.0
67(6A)
0.202;-8677.5
(6T)(6A)
0.340;-5790.0
6(6KA)
0.235;-6862.5
(67TA)
0.190;-9447.5
77(6A)
0.221;-8375.0
(7T)(6A)
0.265;-7467.5
7(6KA)
0.198;-8540.0
(68JA)
0.211;-8842.5
(89)(6A)
0.275;-7467.5
8(6QA)
0.218;-8540.0
T(69A)
0.183;-8842.5
9(6TA)
0.205;-8842.5
9Q(6A)
0.222;-8237.5
Q(6TA)
0.244;-7935.0
(TQ)(6A)
0.316;-5955.0
(6JKA)
0.248;-7330.0
JK(6A)
0.307;-7330.0
K(6KA)
0.258;-4745.0
668A
0.226;-10355.0
6A(6J)
0.252;-7467.5
(67)(7A)
0.252;-6395.0
6(7TA)
0.194;-9447.5
6Q(7A)
0.184;-8842.5
(67)(9A)
0.238;-7770.0
JA(67)
0.213;-9145.0
67(8A)
0.253;-10052.5
67(TA)
0.200;-9447.5
67(QA)
0.228;-8842.5
(68)(8A)
0.299;-5790.0
6(8JA)
0.226;-8842.5
6K(8A)
0.233;-8237.5
(68)(JA)
0.207;-6862.5
KA(68)
0.224;-8237.5
6A(8T)
0.253;-9145.0
6A(8Q)
0.222;-8540.0
6(9TA)
0.235;-8842.5
6Q(9A)
0.211;-8237.5
(69)(JA)
0.214;-6560.0
KA(69)
0.302;-7935.0
6A(9J)
0.206;-8540.0
6A(9K)
0.266;-7935.0
(6Q)(TA)
0.252;-5955.0
JA(6T)
0.248;-8237.5
6T(JA)
0.259;-8237.5
6T(KA)
0.248;-7632.5
6Q(JA)
0.240;-7632.5
(6J)(KA)
0.247;-5350.0
6J(KA)
0.232;-7330.0
6K(QA)
0.198;-7027.5
6A(QK)
0.242;-7027.5
(78)(7A)
0.268;-5790.0
7(7JA)
0.245;-6862.5
7K(7A)
0.275;-6257.5
(78QA)
0.204;-8237.5
8(7TA)
0.196;-8842.5
8Q(7A)
0.285;-8237.5
J(79A)
0.262;-8237.5
9T(7A)
0.237;-8540.0
(9K)(7A)
0.251;-5652.5
K(7TA)
0.231;-7330.0
T(7KA)
0.279;-7330.0
JJ(7A)
0.273;-5652.5
(7QKA)
0.256;-6725.0
777A
0.256;-8072.5
7A(7T)
0.206;-7165.0
77(KA)
0.233;-6257.5
7(8TA)
0.235;-8842.5
7Q(8A)
0.282;-8237.5
(78)(TA)
0.243;-6862.5
QA(78)
0.198;-8237.5
789A
0.235;-11125.0
78JA
0.197;-10520.0
78KA
0.222;-9915.0
7J(9A)
0.249;-8237.5
(79)(TA)
0.240;-6560.0
QA(79)
0.202;-7935.0
79TA
0.195;-10520.0
79QA
0.214;-9915.0
(7J)(TA)
0.273;-5955.0
TA(7T)
0.260;-6257.5
A(7TK)
0.198;-7330.0
TA(7Q)
0.223;-7632.5
7J(JA)
0.220;-5652.5
(7J)(QA)
0.306;-5350.0
JA(7Q)
0.216;-7330.0
7Q(QA)
0.275;-5047.5
7QQA
0.312;-7027.5
7KKA
0.251;-6422.5
8(8JA)
0.276;-6257.5
8K(8A)
0.218;-5652.5
(89KA)
0.228;-7330.0
9J(8A)
0.190;-7935.0
(8TJA)
0.274;-7632.5
(TJ)(8A)
0.267;-5652.5
J(8JA)
0.269;-5350.0
JQ(8A)
0.294;-7027.5
Q(8KA)
0.228;-6422.5
889A
0.236;-8842.5
8A(8Q)
0.247;-5955.0
(8T)(9A)
0.284;-6257.5
8(9KA)
0.263;-7330.0
A(89J)
0.215;-7935.0
899A
0.180;-8540.0
89JA
0.192;-9915.0
89KA
0.209;-9310.0
8Q(TA)
0.238;-7330.0
(8T)(QA)
0.292;-5350.0
TA(8J)
0.201;-7632.5
TA(8K)
0.279;-7027.5
8(JKA)
0.224;-6725.0
A(8JK)
0.285;-6725.0
JA(8K)
0.231;-6725.0
QA(8Q)
0.299;-4745.0
8QKA
0.220;-8402.5
9T(9A)
0.242;-5955.0
(9K)(9A)
0.266;-3067.5
K(9TA)
0.269;-6725.0
T(9KA)
0.249;-6725.0
JJ(9A)
0.277;-5047.5
(9QKA)
0.323;-6120.0
999A
0.230;-6257.5
9A(9Q)
0.269;-5350.0
(9J)(TA)
0.339;-5350.0
TA(9T)
0.283;-5652.5
A(9TK)
0.223;-6725.0
TA(9Q)
0.268;-7027.5
9J(JA)
0.248;-5047.5
(9J)(QA)
0.293;-4745.0
JA(9Q)
0.316;-6725.0
9Q(QA)
0.275;-4442.5
9QQA
0.316;-6422.5
9KKA
0.265;-5817.5
T(TKA)
0.334;-4442.5
JJ(TA)
0.255;-4745.0
(TQKA)
0.249;-5817.5
TTTA
0.232;-5350.0
TA(TK)
0.351;-4442.5
(TK)(JA)
0.237;-4140.0
KA(TJ)
0.272;-6120.0
TA(JK)
0.259;-6120.0
(TQ)(KA)
0.297;-3837.5
(TK)(KA)
0.363;-1555.0
J(JKA)
0.314;-3837.5
(QK)(JA)
0.242;-3535.0
JJ(KA)
0.276;-3837.5
QA(JQ)
0.355;-3837.5
JQKA
0.244;-7495.0
QK(QA)
0.278;-3232.5
QK(KA)
0.299;-2930.0
22(24)
0.179;-13655.0
22(28)
0.177;-12445.0
22(2Q)
0.238;-11235.0
24(23)
0.140;-15332.5
(23)(27)
0.188;-12445.0
2(23T)
0.181;-13517.5
2Q(23)
0.202;-12912.5
23(25)
0.172;-15030.0
2237
0.163;-16405.0
22(3T)
0.171;-13517.5
23(2K)
0.186;-12610.0
2(246)
0.152;-14425.0
28(24)
0.177;-13820.0
(24)(2J)
0.218;-10932.5
2244
0.175;-15030.0
22(47)
0.141;-14122.5
24(2T)
0.152;-13215.0
224Q
0.144;-14590.0
26(25)
0.151;-14122.5
(25)(29)
0.205;-11235.0
2(25Q)
0.185;-12307.5
22(56)
0.135;-14122.5
25(29)
0.142;-13215.0
225J
0.162;-14590.0
26(26)
0.225;-11840.0
(26)(29)
0.197;-10932.5
2(26Q)
0.209;-12005.0
22(67)
0.169;-13517.5
26(2T)
0.178;-12610.0
226Q
0.169;-13985.0
28(27)
0.163;-12912.5
(27)(2J)
0.177;-10025.0
2277
0.188;-13215.0
22(7T)
0.171;-12307.5
27(2K)
0.218;-11400.0
2(28T)
0.188;-12005.0
2Q(28)
0.176;-11400.0
28(2T)
0.165;-12005.0
228Q
0.204;-13380.0
2T(29)
0.190;-11702.5
(29)(2K)
0.209;-8815.0
229J
0.147;-13380.0
2T(2T)
0.184;-9420.0
(2T)(2K)
0.263;-8512.5
22TQ
0.201;-12775.0
2Q(2J)
0.182;-10492.5
2J(2K)
0.167;-10190.0
22QQ
0.189;-10190.0
3(234)
0.137;-15030.0
36(23)
0.175;-14425.0
(23)(39)
0.166;-11537.5
3(23Q)
0.171;-12610.0
5(234)
0.154;-16405.0
9(234)
0.153;-15195.0
K(234)
0.194;-13985.0
4(237)
0.127;-15800.0
49(23)
0.161;-15195.0
(23)(4Q)
0.169;-12307.5
(2357)
0.178;-15497.5
(235J)
0.203;-14287.5
(23)(56)
0.198;-13820.0
5(239)
0.180;-14892.5
5J(23)
0.159;-14287.5
(2367)
0.165;-15195.0
(236J)
0.167;-13985.0
(23)(67)
0.213;-13215.0
6(23T)
0.192;-14287.5
6Q(23)
0.154;-13682.5
9(237)
0.183;-14287.5
K(237)
0.198;-13077.5
7(23T)
0.178;-13985.0
7Q(23)
0.133;-13380.0
T(238)
0.197;-13682.5
8(239)
0.178;-13985.0
8J(23)
0.154;-13380.0
(239T)
0.204;-13380.0
99(23)
0.190;-11702.5
(23)(9Q)
0.222;-10795.0
(23TQ)
0.153;-12472.5
T(23Q)
0.153;-12472.5
Q(23J)
0.196;-12170.0
(23)(JK)
0.193;-9887.5
QK(23)
0.157;-11565.0
23(35)
0.118;-14727.5
33(28)
0.162;-13820.0
233T
0.149;-15195.0
23(3K)
0.219;-12307.5
(24)(36)
0.168;-14122.5
3(249)
0.167;-15195.0
3J(24)
0.144;-14590.0
(34)(25)
0.129;-14425.0
27(34)
0.123;-15800.0
2(34T)
0.137;-14892.5
(34)(2K)
0.198;-12005.0
34(26)
0.195;-16102.5
34(28)
0.166;-15497.5
34(2T)
0.151;-14892.5
34(2Q)
0.119;-14287.5
(25)(35)
0.197;-12142.5
3(258)
0.177;-15195.0
3T(25)
0.166;-14590.0
(25)(3K)
0.176;-11702.5
27(35)
0.142;-15497.5
2(35T)
0.178;-14590.0
(35)(2K)
0.177;-11702.5
35(27)
0.160;-15497.5
35(29)
0.149;-14892.5
35(2J)
0.211;-14287.5
35(2K)
0.172;-13682.5
37(26)
0.145;-15195.0
(26)(3T)
0.176;-12307.5
3(26K)
0.178;-13380.0
2(368)
0.127;-14892.5
(36)(2J)
0.166;-12005.0
2K(36)
0.161;-13380.0
23(68)
0.142;-14892.5
23(6T)
0.173;-14287.5
23(6Q)
0.165;-13682.5
3(278)
0.186;-14590.0
3T(27)
0.169;-13985.0
(27)(3K)
0.179;-11097.5
29(37)
0.146;-14287.5
2(37Q)
0.157;-13380.0
23(78)
0.181;-14590.0
23(7T)
0.184;-13985.0
23(7Q)
0.187;-13380.0
3(289)
0.159;-13985.0
3J(28)
0.184;-13380.0
(38)(29)
0.165;-12005.0
2J(38)
0.158;-13380.0
38(29)
0.176;-13985.0
38(2J)
0.194;-13380.0
38(2K)
0.176;-12775.0
3T(29)
0.174;-13380.0
(29)(3K)
0.212;-10492.5
2J(39)
0.196;-13077.5
39(2T)
0.224;-13380.0
39(2Q)
0.209;-12775.0
(2T)(3T)
0.178;-9117.5
3(2TK)
0.202;-12170.0
2(3TQ)
0.163;-12472.5
23(TJ)
0.148;-12775.0
23(TK)
0.216;-12170.0
(2J)(3K)
0.243;-9887.5
2K(3J)
0.161;-11867.5
23(JK)
0.195;-11867.5
(3Q)(2K)
0.203;-9585.0
(2K)(3K)
0.231;-7302.5
4(246)
0.191;-13820.0
48(24)
0.152;-13215.0
(24)(4J)
0.221;-10327.5
5(245)
0.190;-13820.0
9(245)
0.168;-14590.0
K(245)
0.183;-13380.0
5(248)
0.151;-14892.5
5T(24)
0.162;-14287.5
(24)(5K)
0.198;-11400.0
9(246)
0.149;-14287.5
K(246)
0.231;-13077.5
6(249)
0.169;-14287.5
6J(24)
0.169;-13682.5
(2478)
0.157;-14287.5
(247Q)
0.209;-13077.5
7(249)
0.163;-13985.0
7J(24)
0.165;-13380.0
(2489)
0.185;-13682.5
(248K)
0.169;-12472.5
8T(24)
0.209;-13380.0
(24)(8K)
0.207;-10492.5
Q(249)
0.175;-12472.5
(24)(9J)
0.169;-10795.0
T(24T)
0.238;-10795.0
T(24J)
0.160;-12472.5
TK(24)
0.183;-11867.5
(24)(JQ)
0.217;-9887.5
QQ(24)
0.195;-9585.0
24(45)
0.175;-14122.5
44(28)
0.192;-13215.0
244T
0.187;-14590.0
24(4K)
0.233;-11702.5
(25)(47)
0.169;-13215.0
4(25T)
0.173;-14287.5
4Q(25)
0.176;-13682.5
(45)(27)
0.191;-13215.0
29(45)
0.164;-14590.0
2(45Q)
0.170;-13682.5
24(56)
0.122;-15497.5
24(58)
0.196;-14892.5
24(5T)
0.174;-14287.5
24(5Q)
0.183;-13682.5
4(267)
0.188;-14892.5
49(26)
0.155;-14287.5
(26)(4Q)
0.160;-11400.0
27(46)
0.168;-14892.5
2(46T)
0.199;-13985.0
(46)(2K)
0.203;-11097.5
46(28)
0.174;-14590.0
46(2T)
0.172;-13985.0
46(2Q)
0.173;-13380.0
(27)(47)
0.198;-10630.0
4(27T)
0.174;-13682.5
4Q(27)
0.201;-13077.5
(47)(29)
0.235;-12005.0
2J(47)
0.181;-13380.0
47(28)
0.154;-14287.5
47(2T)
0.214;-13682.5
47(2Q)
0.234;-13077.5
(28)(48)
0.228;-10025.0
4(28J)
0.190;-13077.5
4K(28)
0.154;-12472.5
(48)(2J)
0.178;-11097.5
2K(48)
0.200;-12472.5
24(8T)
0.176;-13380.0
24(8Q)
0.174;-12775.0
4(29T)
0.180;-13077.5
4Q(29)
0.166;-12472.5
(49)(2J)
0.196;-10795.0
2K(49)
0.206;-12170.0
24(9J)
0.166;-12775.0
24(9K)
0.207;-12170.0
(2T)(4Q)
0.243;-10190.0
2J(4T)
0.176;-12472.5
4T(2J)
0.231;-12472.5
4T(2K)
0.195;-11867.5
4Q(2J)
0.163;-11867.5
(4J)(2K)
0.209;-9585.0
4J(2K)
0.204;-11565.0
4K(2Q)
0.214;-11262.5
24(QK)
0.225;-11262.5
(25)(56)
0.192;-11235.0
5(259)
0.180;-12307.5
5J(25)
0.194;-11702.5
(2567)
0.165;-14590.0
(256J)
0.191;-13380.0
(25)(67)
0.153;-12610.0
6(25T)
0.181;-13682.5
6Q(25)
0.201;-13077.5
9(257)
0.178;-13682.5
K(257)
0.219;-12472.5
7(25T)
0.178;-13380.0
7Q(25)
0.170;-12775.0
T(258)
0.169;-13077.5
8(259)
0.214;-13380.0
8J(25)
0.144;-12775.0
(259T)
0.140;-12775.0
99(25)
0.171;-11097.5
(25)(9Q)
0.231;-10190.0
(25TQ)
0.223;-11867.5
T(25Q)
0.162;-11867.5
Q(25J)
0.192;-11565.0
(25)(JK)
0.233;-9282.5
QK(25)
0.216;-10960.0
25(57)
0.136;-12912.5
55(2T)
0.193;-12005.0
255Q
0.180;-13380.0
57(26)
0.178;-14590.0
(26)(5T)
0.185;-11702.5
5(26K)
0.197;-12775.0
2(568)
0.171;-14287.5
(56)(2J)
0.155;-11400.0
2K(56)
0.162;-12775.0
25(68)
0.183;-14287.5
25(6T)
0.182;-13682.5
25(6Q)
0.186;-13077.5
5(278)
0.136;-13985.0
5T(27)
0.186;-13380.0
(27)(5K)
0.249;-10492.5
29(57)
0.175;-13682.5
2(57Q)
0.173;-12775.0
25(78)
0.149;-13985.0
25(7T)
0.178;-13380.0
25(7Q)
0.213;-12775.0
5(289)
0.176;-13380.0
5J(28)
0.211;-12775.0
(58)(29)
0.162;-11400.0
2J(58)
0.195;-12775.0
58(29)
0.208;-13380.0
58(2J)
0.147;-12775.0
58(2K)
0.156;-12170.0
5T(29)
0.194;-12775.0
(29)(5K)
0.197;-9887.5
2J(59)
0.161;-12472.5
59(2T)
0.195;-12775.0
59(2Q)
0.221;-12170.0
(2T)(5T)
0.254;-8512.5
5(2TK)
0.191;-11565.0
2(5TQ)
0.148;-11867.5
25(TJ)
0.149;-12170.0
25(TK)
0.200;-11565.0
(2J)(5K)
0.181;-9282.5
2K(5J)
0.216;-11262.5
25(JK)
0.196;-11262.5
(5Q)(2K)
0.171;-8980.0
(2K)(5K)
0.219;-6697.5
6(268)
0.153;-12005.0
6T(26)
0.192;-11400.0
(26)(6K)
0.204;-8512.5
T(267)
0.168;-13077.5
7(268)
0.160;-13682.5
7T(26)
0.144;-13077.5
(26)(7K)
0.196;-10190.0
J(268)
0.229;-12472.5
89(26)
0.152;-13077.5
(26)(8Q)
0.177;-10190.0
(269J)
0.179;-12170.0
(26)(9T)
0.210;-10492.5
9(26K)
0.194;-11565.0
(26TK)
0.168;-11262.5
TQ(26)
0.205;-11565.0
K(26J)
0.163;-10960.0
Q(26Q)
0.222;-8980.0
KK(26)
0.244;-8375.0
66(29)
0.186;-11702.5
266J
0.152;-13077.5
67(27)
0.163;-12005.0
(27)(6T)
0.180;-11097.5
6(27K)
0.203;-12170.0
2(679)
0.206;-13380.0
(67)(2Q)
0.198;-10492.5
27(68)
0.161;-13682.5
27(6T)
0.162;-13077.5
27(6Q)
0.223;-12472.5
68(28)
0.145;-11400.0
(28)(6J)
0.203;-10492.5
28(68)
0.148;-11400.0
2(68J)
0.173;-12472.5
2688
0.167;-13380.0
268T
0.132;-14755.0
268Q
0.161;-14150.0
(29)(6T)
0.187;-10492.5
6(29K)
0.177;-11565.0
2(69J)
0.178;-12170.0
2699
0.158;-12775.0
269J
0.167;-14150.0
269K
0.155;-13545.0
6Q(2T)
0.169;-11565.0
(6T)(2Q)
0.194;-9585.0
2T(6J)
0.196;-11867.5
2T(6K)
0.215;-11262.5
6(2JK)
0.220;-10960.0
2(6JK)
0.219;-10960.0
2J(6K)
0.172;-10960.0
2Q(6Q)
0.224;-8980.0
26QK
0.150;-12637.5
78(27)
0.176;-11400.0
(27)(7J)
0.251;-8512.5
8(278)
0.215;-11097.5
Q(278)
0.247;-11867.5
(27)(8T)
0.263;-10492.5
8(27K)
0.241;-11565.0
(279Q)
0.207;-11565.0
9(27J)
0.184;-11867.5
9K(27)
0.159;-11262.5
TT(27)
0.253;-9887.5
(27)(TK)
0.216;-8980.0
J(27Q)
0.238;-10960.0
K(27Q)
0.244;-10355.0
77(28)
0.178;-11400.0
277T
0.152;-12775.0
27(7K)
0.230;-9887.5
(28)(7T)
0.254;-10492.5
7(28K)
0.167;-11565.0
2(78T)
0.195;-12472.5
(78)(2K)
0.213;-9585.0
78(2T)
0.195;-12472.5
78(2Q)
0.172;-11867.5
(29)(79)
0.214;-8512.5
7(29Q)
0.203;-11565.0
2(79T)
0.189;-12170.0
(79)(2K)
0.210;-9282.5
79(2J)
0.175;-11867.5
79(2K)
0.186;-11262.5
7J(2T)
0.216;-11565.0
(7T)(2J)
0.198;-9585.0
2K(7T)
0.167;-10960.0
27(TQ)
0.202;-11262.5
7(2JQ)
0.174;-10960.0
2(7JQ)
0.264;-10960.0
27(JQ)
0.229;-10960.0
7(2QK)
0.225;-10355.0
7Q(2K)
0.197;-10355.0
88(28)
0.251;-8815.0
(28)(8J)
0.215;-7907.5
9(289)
0.266;-10190.0
K(289)
0.192;-10960.0
9(28Q)
0.231;-11262.5
J(28T)
0.150;-11262.5
TJ(28)
0.186;-11262.5
(28JQ)
0.167;-10657.5
J(28K)
0.153;-10355.0
(28)(QK)
0.181;-8072.5
88(2T)
0.211;-10190.0
288Q
0.190;-11565.0
8T(29)
0.190;-11867.5
(29)(8K)
0.186;-8980.0
2J(89)
0.192;-11565.0
89(2T)
0.200;-11867.5
89(2Q)
0.191;-11262.5
(2T)(8T)
0.296;-7605.0
8(2TK)
0.183;-10657.5
2(8TQ)
0.203;-10960.0
28(TJ)
0.229;-11262.5
28(TK)
0.203;-10657.5
(2J)(8K)
0.226;-8375.0
2K(8J)
0.211;-10355.0
28(JK)
0.203;-10355.0
(8Q)(2K)
0.210;-8072.5
(2K)(8K)
0.256;-5790.0
9(29J)
0.208;-9282.5
9K(29)
0.208;-8677.5
TT(29)
0.195;-9282.5
(29)(TK)
0.204;-8375.0
J(29Q)
0.219;-10355.0
K(29Q)
0.259;-9750.0
99(2T)
0.195;-9585.0
299Q
0.166;-10960.0
9J(2T)
0.214;-10960.0
(9T)(2J)
0.223;-8980.0
2K(9T)
0.169;-10355.0
29(TQ)
0.228;-10657.5
9(2JQ)
0.197;-10355.0
2(9JQ)
0.242;-10355.0
29(JQ)
0.176;-10355.0
9(2QK)
0.167;-9750.0
9Q(2K)
0.203;-9750.0
TT(2T)
0.255;-7000.0
(2T)(TK)
0.313;-6092.5
J(2TQ)
0.228;-10052.5
K(2TQ)
0.228;-9447.5
TT(2J)
0.192;-8677.5
2TTK
0.179;-10052.5
TK(2J)
0.204;-9750.0
2TJJ
0.212;-10355.0
2TJK
0.197;-11730.0
2(TQK)
0.234;-9447.5
TK(2K)
0.294;-7165.0
(2J)(JK)
0.287;-5487.5
QK(2J)
0.193;-9145.0
2J(JK)
0.284;-7467.5
(JQ)(2K)
0.211;-7165.0
(2K)(JK)
0.251;-4882.5
K(2QK)
0.275;-6560.0
2K(QK)
0.235;-6560.0
3335
0.160;-14425.0
3339
0.174;-13215.0
333K
0.159;-12005.0
36(34)
0.153;-13820.0
(34)(39)
0.208;-10932.5
3(34Q)
0.197;-12005.0
33(45)
0.157;-14122.5
34(38)
0.195;-13215.0
334T
0.174;-14590.0
33(4K)
0.153;-11702.5
(35)(37)
0.189;-11235.0
3(35T)
0.157;-12307.5
3Q(35)
0.187;-11702.5
35(37)
0.179;-13215.0
3359
0.131;-14590.0
33(5Q)
0.193;-11702.5
(36)(37)
0.196;-10932.5
3(36T)
0.186;-12005.0
3Q(36)
0.164;-11400.0
36(38)
0.205;-12610.0
336T
0.185;-13985.0
33(6K)
0.202;-11097.5
(37)(39)
0.230;-10025.0
3(37Q)
0.198;-11097.5
33(78)
0.197;-12307.5
37(3J)
0.192;-11400.0
337K
0.229;-12775.0
3T(38)
0.210;-11400.0
(38)(3K)
0.195;-8512.5
338T
0.166;-13380.0
33(8K)
0.193;-10492.5
(39)(3J)
0.179;-8815.0
3399
0.186;-11400.0
33(9Q)
0.235;-10492.5
(3T)(3J)
0.207;-8512.5
33TT
0.209;-10795.0
33(TK)
0.195;-9887.5
(3J)(3K)
0.220;-7605.0
33JK
0.190;-11565.0
33(QK)
0.203;-9282.5
45(34)
0.162;-13820.0
(34)(48)
0.216;-10932.5
4(34J)
0.170;-12005.0
4K(34)
0.203;-11400.0
(3459)
0.191;-14287.5
(345K)
0.175;-13077.5
57(34)
0.140;-14892.5
(34)(5T)
0.181;-12005.0
5(34K)
0.188;-13077.5
(3469)
0.147;-13985.0
(346K)
0.206;-12775.0
68(34)
0.148;-14287.5
(34)(6J)
0.196;-11400.0
7(347)
0.171;-12307.5
J(347)
0.169;-13077.5
78(34)
0.144;-13985.0
(34)(7J)
0.194;-11097.5
8(348)
0.189;-11702.5
Q(348)
0.174;-12472.5
(34)(8T)
0.213;-11097.5
8(34K)
0.177;-12170.0
(349Q)
0.189;-12170.0
9(34J)
0.193;-12472.5
9K(34)
0.164;-11867.5
TT(34)
0.164;-10492.5
(34)(TK)
0.254;-9585.0
J(34Q)
0.185;-11565.0
K(34Q)
0.161;-10960.0
44(35)
0.159;-13820.0
3447
0.152;-15195.0
34(4T)
0.217;-12307.5
44(3K)
0.230;-11400.0
4(357)
0.153;-14892.5
49(35)
0.154;-14287.5
(35)(4Q)
0.189;-11400.0
36(45)
0.159;-15195.0
3(459)
0.176;-14287.5
(45)(3Q)
0.216;-11400.0
35(46)
0.148;-15195.0
35(48)
0.184;-14590.0
35(4T)
0.135;-13985.0
35(4Q)
0.167;-13380.0
46(36)
0.179;-12912.5
(36)(49)
0.155;-12005.0
4(36Q)
0.202;-13077.5
3(467)
0.130;-14590.0
(46)(3T)
0.175;-11702.5
3Q(46)
0.221;-13077.5
3467
0.129;-16570.0
3469
0.129;-15965.0
346J
0.141;-15360.0
346K
0.175;-14755.0
49(37)
0.130;-13682.5
(37)(4Q)
0.181;-10795.0
38(47)
0.169;-13985.0
3(47J)
0.207;-13077.5
3477
0.137;-14287.5
3479
0.112;-15662.5
347J
0.168;-15057.5
347K
0.163;-14452.5
4T(38)
0.164;-13077.5
(38)(4K)
0.186;-10190.0
3T(48)
0.182;-13077.5
3(48K)
0.144;-12170.0
38(4T)
0.186;-13077.5
38(4Q)
0.194;-12472.5
49(39)
0.221;-11097.5
(39)(4Q)
0.200;-10190.0
3T(49)
0.199;-12775.0
3(49K)
0.218;-11867.5
39(4J)
0.154;-12472.5
39(4K)
0.146;-11867.5
4(3TQ)
0.179;-11867.5
3(4TJ)
0.178;-12170.0
34TT
0.178;-12472.5
34TQ
0.184;-13847.5
(3J)(4Q)
0.276;-9585.0
3Q(4J)
0.205;-11565.0
34JQ
0.186;-13545.0
(3Q)(4K)
0.222;-8980.0
3Q(4K)
0.180;-10960.0
5(356)
0.166;-12912.5
58(35)
0.155;-12307.5
(35)(5J)
0.261;-9420.0
6(356)
0.218;-12610.0
T(356)
0.140;-13380.0
6(357)
0.140;-14287.5
69(35)
0.203;-13682.5
(35)(6Q)
0.200;-10795.0
(3579)
0.145;-13380.0
(357K)
0.190;-12170.0
79(35)
0.139;-13380.0
(35)(7Q)
0.194;-10492.5
(358T)
0.166;-12775.0
88(35)
0.226;-11400.0
(35)(8J)
0.248;-10492.5
9(359)
0.247;-10795.0
K(359)
0.189;-11565.0
9(35Q)
0.202;-11867.5
J(35T)
0.202;-11867.5
TJ(35)
0.245;-11867.5
(35JQ)
0.189;-11262.5
J(35K)
0.226;-10960.0
(35)(QK)
0.237;-8677.5
55(37)
0.203;-12610.0
3559
0.148;-13985.0
35(5Q)
0.151;-11097.5
(36)(57)
0.190;-12307.5
5(36T)
0.164;-13380.0
5Q(36)
0.186;-12775.0
(56)(38)
0.231;-12005.0
3T(56)
0.189;-13380.0
3(56K)
0.182;-12472.5
36(58)
0.160;-13985.0
36(5T)
0.182;-13380.0
36(5Q)
0.167;-12775.0
57(37)
0.205;-12005.0
(37)(5T)
0.235;-11097.5
5(37K)
0.172;-12170.0
3(579)
0.145;-13380.0
(57)(3Q)
0.207;-10492.5
37(58)
0.168;-13682.5
37(5T)
0.173;-13077.5
37(5Q)
0.179;-12472.5
58(38)
0.240;-11400.0
(38)(5J)
0.262;-10492.5
38(58)
0.191;-11400.0
3(58J)
0.153;-12472.5
3588
0.182;-13380.0
358T
0.176;-14755.0
358Q
0.175;-14150.0
(39)(5T)
0.235;-10492.5
5(39K)
0.177;-11565.0
3(59J)
0.155;-12170.0
3599
0.184;-12775.0
359J
0.198;-14150.0
359K
0.165;-13545.0
5Q(3T)
0.200;-11565.0
(5T)(3Q)
0.191;-9585.0
3T(5J)
0.159;-11867.5
3T(5K)
0.194;-11262.5
5(3JK)
0.177;-10960.0
3(5JK)
0.257;-10960.0
3J(5K)
0.149;-10960.0
3Q(5Q)
0.227;-8980.0
35QK
0.210;-12637.5
67(36)
0.164;-12005.0
(36)(6T)
0.175;-9117.5
6(36K)
0.206;-10190.0
(367T)
0.179;-12775.0
77(36)
0.198;-11702.5
(36)(7T)
0.174;-10795.0
7(36K)
0.210;-11867.5
(368J)
0.149;-12170.0
(36)(89)
0.229;-10795.0
8(36Q)
0.252;-11867.5
T(369)
0.184;-12170.0
9(36T)
0.154;-12170.0
9Q(36)
0.170;-11565.0
Q(36T)
0.193;-11262.5
(36)(TQ)
0.191;-9282.5
(36JK)
0.219;-10657.5
JK(36)
0.182;-10657.5
K(36K)
0.210;-8072.5
3668
0.192;-13682.5
36(6J)
0.214;-10795.0
(37)(67)
0.210;-9722.5
6(37T)
0.161;-12775.0
6Q(37)
0.140;-12170.0
(67)(39)
0.198;-11097.5
3J(67)
0.202;-12472.5
67(38)
0.164;-13380.0
67(3T)
0.202;-12775.0
67(3Q)
0.174;-12170.0
(38)(68)
0.191;-9117.5
6(38J)
0.199;-12170.0
6K(38)
0.168;-11565.0
(68)(3J)
0.233;-10190.0
3K(68)
0.245;-11565.0
36(8T)
0.202;-12472.5
36(8Q)
0.199;-11867.5
6(39T)
0.198;-12170.0
6Q(39)
0.202;-11565.0
(69)(3J)
0.185;-9887.5
3K(69)
0.183;-11262.5
36(9J)
0.230;-11867.5
36(9K)
0.167;-11262.5
(3T)(6Q)
0.185;-9282.5
3J(6T)
0.193;-11565.0
6T(3J)
0.192;-11565.0
6T(3K)
0.236;-10960.0
6Q(3J)
0.193;-10960.0
(6J)(3K)
0.266;-8677.5
6J(3K)
0.220;-10657.5
6K(3Q)
0.187;-10355.0
36(QK)
0.196;-10355.0
(37)(78)
0.232;-9117.5
7(37J)
0.192;-10190.0
7K(37)
0.221;-9585.0
(378Q)
0.229;-11565.0
8(37T)
0.236;-12170.0
8Q(37)
0.190;-11565.0
J(379)
0.194;-11565.0
9T(37)
0.186;-11867.5
(37)(9K)
0.235;-8980.0
K(37T)
0.221;-10657.5
T(37K)
0.247;-10657.5
JJ(37)
0.242;-8980.0
(37QK)
0.170;-10052.5
3777
0.163;-11400.0
37(7T)
0.190;-10492.5
77(3K)
0.225;-9585.0
7(38T)
0.158;-12170.0
7Q(38)
0.197;-11565.0
(78)(3T)
0.163;-10190.0
3Q(78)
0.157;-11565.0
3789
0.167;-14452.5
378J
0.169;-13847.5
378K
0.180;-13242.5
7J(39)
0.164;-11565.0
(79)(3T)
0.223;-9887.5
3Q(79)
0.177;-11262.5
379T
0.174;-13847.5
379Q
0.186;-13242.5
(3T)(7J)
0.214;-9282.5
3T(7T)
0.186;-9585.0
3(7TK)
0.207;-10657.5
3T(7Q)
0.209;-10960.0
7J(3J)
0.250;-8980.0
(7J)(3Q)
0.242;-8677.5
3J(7Q)
0.216;-10657.5
7Q(3Q)
0.178;-8375.0
37QQ
0.214;-10355.0
37KK
0.214;-9750.0
8(38J)
0.210;-9585.0
8K(38)
0.190;-8980.0
(389K)
0.212;-10657.5
9J(38)
0.174;-11262.5
(38TJ)
0.182;-10960.0
(38)(TJ)
0.172;-8980.0
J(38J)
0.264;-8677.5
JQ(38)
0.191;-10355.0
Q(38K)
0.257;-9750.0
3889
0.170;-12170.0
38(8Q)
0.220;-9282.5
(39)(8T)
0.200;-9585.0
8(39K)
0.205;-10657.5
3(89J)
0.207;-11262.5
3899
0.218;-11867.5
389J
0.123;-13242.5
389K
0.160;-12637.5
8Q(3T)
0.215;-10657.5
(8T)(3Q)
0.209;-8677.5
3T(8J)
0.226;-10960.0
3T(8K)
0.218;-10355.0
8(3JK)
0.193;-10052.5
3(8JK)
0.205;-10052.5
3J(8K)
0.189;-10052.5
3Q(8Q)
0.260;-8072.5
38QK
0.193;-11730.0
9T(39)
0.207;-9282.5
(39)(9K)
0.330;-6395.0
K(39T)
0.245;-10052.5
T(39K)
0.224;-10052.5
JJ(39)
0.226;-8375.0
(39QK)
0.239;-9447.5
3999
0.236;-9585.0
39(9Q)
0.266;-8677.5
(3T)(9J)
0.252;-8677.5
3T(9T)
0.239;-8980.0
3(9TK)
0.214;-10052.5
3T(9Q)
0.221;-10355.0
9J(3J)
0.192;-8375.0
(9J)(3Q)
0.252;-8072.5
3J(9Q)
0.175;-10052.5
9Q(3Q)
0.223;-7770.0
39QQ
0.264;-9750.0
39KK
0.167;-9145.0
T(3TK)
0.172;-7770.0
JJ(3T)
0.176;-8072.5
(3TQK)
0.277;-9145.0
3TTT
0.230;-8677.5
3T(TK)
0.205;-7770.0
(3J)(TK)
0.235;-7467.5
3K(TJ)
0.186;-9447.5
3T(JK)
0.181;-9447.5
(TQ)(3K)
0.216;-7165.0
(3K)(TK)
0.256;-4882.5
J(3JK)
0.257;-7165.0
(3J)(QK)
0.233;-6862.5
JJ(3K)
0.219;-7165.0
3Q(JQ)
0.252;-7165.0
3JQK
0.164;-10822.5
QK(3Q)
0.298;-6560.0
QK(3K)
0.258;-6257.5
44(46)
0.195;-11235.0
44(4T)
0.217;-10025.0
(45)(45)
0.198;-9255.0
4(458)
0.147;-12307.5
4T(45)
0.168;-11702.5
(45)(4K)
0.225;-8815.0
4457
0.145;-14590.0
44(5T)
0.157;-11702.5
45(4K)
0.177;-10795.0
4(468)
0.176;-12005.0
4T(46)
0.183;-11400.0
(46)(4K)
0.234;-8512.5
4468
0.146;-13985.0
44(6J)
0.206;-11097.5
(47)(47)
0.234;-8045.0
4(47T)
0.199;-11097.5
4Q(47)
0.237;-10492.5
47(49)
0.211;-11400.0
447J
0.147;-12775.0
48(48)
0.250;-9420.0
(48)(4J)
0.229;-8512.5
4488
0.215;-11400.0
44(8J)
0.214;-10492.5
(49)(49)
0.222;-6835.0
4(49Q)
0.213;-9887.5
44(9T)
0.179;-10492.5
49(4K)
0.191;-9585.0
4(4TQ)
0.224;-9585.0
44(TJ)
0.182;-9887.5
(4J)(4J)
0.225;-5625.0
44JJ
0.205;-9585.0
4Q(4Q)
0.214;-7000.0
(4K)(4K)
0.311;-4415.0
(45)(57)
0.202;-10327.5
5(45T)
0.202;-11400.0
5Q(45)
0.165;-10795.0
8(456)
0.156;-13682.5
Q(456)
0.212;-12472.5
(45)(68)
0.205;-11702.5
6(45J)
0.165;-12775.0
6K(45)
0.189;-12170.0
(457J)
0.170;-12472.5
(45)(78)
0.180;-11400.0
7(45J)
0.139;-12472.5
7K(45)
0.203;-11867.5
(458Q)
0.136;-11867.5
8(45T)
0.183;-12472.5
8Q(45)
0.183;-11867.5
J(459)
0.213;-11867.5
9T(45)
0.221;-12170.0
(45)(9K)
0.275;-9282.5
K(45T)
0.173;-10960.0
T(45K)
0.162;-10960.0
JJ(45)
0.160;-9282.5
(45QK)
0.267;-10355.0
4555
0.156;-12912.5
45(58)
0.188;-12005.0
55(4J)
0.144;-11097.5
455K
0.196;-12472.5
58(46)
0.203;-13682.5
(46)(5J)
0.162;-10795.0
46(56)
0.239;-12307.5
4(569)
0.132;-13380.0
(56)(4Q)
0.159;-10492.5
46(57)
0.139;-13985.0
46(59)
0.189;-13380.0
46(5J)
0.220;-12775.0
46(5K)
0.171;-12170.0
5(479)
0.233;-13077.5
5J(47)
0.184;-12472.5
(57)(48)
0.170;-11400.0
4T(57)
0.139;-12775.0
4(57K)
0.204;-11867.5
47(59)
0.139;-13077.5
47(5J)
0.157;-12472.5
47(5K)
0.144;-11867.5
5(48T)
0.196;-12472.5
5Q(48)
0.208;-11867.5
(58)(4T)
0.215;-10492.5
4Q(58)
0.168;-11867.5
4589
0.148;-14755.0
458J
0.132;-14150.0
458K
0.157;-13545.0
5J(49)
0.182;-11867.5
(59)(4T)
0.214;-10190.0
4Q(59)
0.168;-11565.0
459T
0.167;-14150.0
459Q
0.182;-13545.0
(4T)(5J)
0.228;-9585.0
4T(5T)
0.206;-9887.5
4(5TK)
0.191;-10960.0
4T(5Q)
0.214;-11262.5
5J(4J)
0.170;-9282.5
(5J)(4Q)
0.288;-8980.0
4J(5Q)
0.234;-10960.0
5Q(4Q)
0.216;-8677.5
45QQ
0.196;-10657.5
45KK
0.217;-10052.5
6(469)
0.231;-11097.5
6J(46)
0.197;-10492.5
(4678)
0.176;-13077.5
(467Q)
0.190;-11867.5
7(469)
0.173;-12775.0
7J(46)
0.173;-12170.0
(4689)
0.190;-12472.5
(468K)
0.215;-11262.5
8T(46)
0.228;-12170.0
(46)(8K)
0.247;-9282.5
Q(469)
0.199;-11262.5
(46)(9J)
0.198;-9585.0
T(46T)
0.220;-9585.0
T(46J)
0.150;-11262.5
TK(46)
0.168;-10657.5
(46)(JQ)
0.234;-8677.5
QQ(46)
0.231;-8375.0
46(67)
0.202;-11702.5
66(4T)
0.181;-10795.0
466Q
0.183;-12170.0
68(47)
0.187;-13077.5
(47)(6J)
0.171;-10190.0
47(67)
0.212;-11400.0
4(67T)
0.180;-12472.5
(67)(4K)
0.188;-9585.0
67(49)
0.141;-12775.0
67(4J)
0.156;-12170.0
67(4K)
0.206;-11565.0
69(48)
0.174;-12472.5
(48)(6Q)
0.182;-9585.0
49(68)
0.164;-12472.5
4(68Q)
0.206;-11565.0
46(89)
0.194;-12472.5
46(8J)
0.154;-11867.5
46(8K)
0.168;-11262.5
(49)(6J)
0.198;-9585.0
49(69)
0.178;-10190.0
4(69Q)
0.151;-11262.5
46(9T)
0.175;-11867.5
46(9Q)
0.180;-11262.5
6(4TJ)
0.221;-11262.5
6K(4T)
0.170;-10657.5
(6T)(4K)
0.233;-8677.5
6T(4Q)
0.187;-10960.0
(4J)(6J)
0.309;-7000.0
4J(6J)
0.213;-8980.0
6J(4Q)
0.156;-10657.5
(4Q)(6Q)
0.216;-6395.0
4K(6Q)
0.182;-10052.5
4K(6K)
0.253;-7770.0
79(47)
0.224;-10492.5
(47)(7Q)
0.236;-7605.0
(478T)
0.187;-11867.5
88(47)
0.160;-10492.5
(47)(8J)
0.204;-9585.0
9(479)
0.162;-9887.5
K(479)
0.148;-10657.5
9(47Q)
0.226;-10960.0
J(47T)
0.207;-10960.0
TJ(47)
0.172;-10960.0
(47JQ)
0.166;-10355.0
J(47K)
0.184;-10052.5
(47)(QK)
0.289;-7770.0
77(49)
0.176;-10492.5
477J
0.220;-11867.5
78(48)
0.176;-10492.5
(48)(7J)
0.182;-9585.0
48(78)
0.158;-10492.5
4(78J)
0.207;-11565.0
4788
0.187;-12472.5
478T
0.149;-13847.5
478Q
0.133;-13242.5
(49)(7T)
0.201;-9585.0
7(49K)
0.176;-10657.5
4(79J)
0.190;-11262.5
4799
0.195;-11867.5
479J
0.162;-13242.5
479K
0.204;-12637.5
7Q(4T)
0.181;-10657.5
(7T)(4Q)
0.221;-8677.5
4T(7J)
0.175;-10960.0
4T(7K)
0.225;-10355.0
7(4JK)
0.205;-10052.5
4(7JK)
0.184;-10052.5
4J(7K)
0.191;-10052.5
4Q(7Q)
0.276;-8072.5
47QK
0.235;-11730.0
89(48)
0.205;-9887.5
(48)(8Q)
0.281;-7000.0
(489J)
0.249;-10960.0
(48)(9T)
0.225;-9282.5
9(48K)
0.232;-10355.0
(48TK)
0.236;-10052.5
TQ(48)
0.192;-10355.0
K(48J)
0.225;-9750.0
Q(48Q)
0.216;-7770.0
KK(48)
0.221;-7165.0
88(4J)
0.182;-9282.5
488K
0.210;-10657.5
8J(49)
0.257;-10960.0
(89)(4T)
0.267;-9282.5
4Q(89)
0.216;-10657.5
489T
0.186;-13242.5
489Q
0.173;-12637.5
(4T)(8J)
0.221;-8677.5
4T(8T)
0.243;-8980.0
4(8TK)
0.204;-10052.5
4T(8Q)
0.231;-10355.0
8J(4J)
0.216;-8375.0
(8J)(4Q)
0.177;-8072.5
4J(8Q)
0.238;-10052.5
8Q(4Q)
0.276;-7770.0
48QQ
0.211;-9750.0
48KK
0.195;-9145.0
9(49Q)
0.232;-8375.0
J(49T)
0.213;-10355.0
TJ(49)
0.176;-10355.0
(49JQ)
0.243;-9750.0
J(49K)
0.215;-9447.5
(49)(QK)
0.246;-7165.0
99(4J)
0.214;-8677.5
499K
0.219;-10052.5
9Q(4T)
0.199;-10052.5
(9T)(4Q)
0.191;-8072.5
4T(9J)
0.202;-10355.0
4T(9K)
0.212;-9750.0
9(4JK)
0.187;-9447.5
4(9JK)
0.161;-9447.5
4J(9K)
0.236;-9447.5
4Q(9Q)
0.237;-7467.5
49QK
0.217;-11125.0
TJ(4T)
0.212;-8072.5
(4TJQ)
0.226;-9447.5
J(4TK)
0.253;-9145.0
(4T)(QK)
0.229;-6862.5
TT(4Q)
0.250;-7770.0
T(4JQ)
0.277;-9447.5
4(TJQ)
0.220;-9447.5
4T(JQ)
0.235;-9447.5
T(4QK)
0.234;-8842.5
TQ(4K)
0.170;-8842.5
JJ(4J)
0.265;-5487.5
(4JQK)
0.223;-8540.0
4JJJ
0.228;-7467.5
JQ(4Q)
0.230;-6862.5
4JQQ
0.287;-8842.5
4JKK
0.225;-8237.5
QQ(4K)
0.257;-6257.5
4KKK
0.270;-5652.5
55(59)
0.224;-9420.0
55(5K)
0.233;-8210.0
(56)(58)
0.172;-9420.0
5(56J)
0.194;-10492.5
5K(56)
0.237;-9887.5
56(59)
0.251;-11097.5
556J
0.176;-12472.5
57(57)
0.256;-9420.0
(57)(5T)
0.250;-8512.5
5(57K)
0.260;-9585.0
55(79)
0.171;-10795.0
57(5Q)
0.219;-9887.5
5(589)
0.214;-10492.5
5J(58)
0.231;-9887.5
58(59)
0.219;-10492.5
558J
0.181;-11867.5
59(59)
0.284;-8210.0
(59)(5Q)
0.291;-7302.5
559T
0.188;-11867.5
55(9K)
0.200;-8980.0
(5T)(5Q)
0.236;-7000.0
55TJ
0.207;-11262.5
5J(5J)
0.256;-7000.0
5J(5Q)
0.253;-8677.5
5(5QK)
0.248;-8072.5
5K(5K)
0.250;-5790.0
68(56)
0.168;-11097.5
(56)(6J)
0.215;-8210.0
7(567)
0.205;-11097.5
J(567)
0.231;-11867.5
78(56)
0.198;-12775.0
(56)(7J)
0.208;-9887.5
8(568)
0.204;-10492.5
Q(568)
0.171;-11262.5
(56)(8T)
0.226;-9887.5
8(56K)
0.239;-10960.0
(569Q)
0.215;-10960.0
9(56J)
0.181;-11262.5
9K(56)
0.161;-10657.5
TT(56)
0.227;-9282.5
(56)(TK)
0.225;-8375.0
J(56Q)
0.203;-10355.0
K(56Q)
0.239;-9750.0
66(57)
0.171;-11400.0
5669
0.144;-12775.0
56(6Q)
0.205;-9887.5
(57)(68)
0.149;-10795.0
6(57J)
0.195;-11867.5
6K(57)
0.190;-11262.5
(67)(5T)
0.259;-10190.0
5Q(67)
0.182;-11565.0
5678
0.148;-14755.0
567T
0.172;-14150.0
567Q
0.162;-13545.0
(58)(69)
0.176;-10190.0
6(58Q)
0.169;-11262.5
5(689)
0.204;-12170.0
(68)(5Q)
0.215;-9282.5
58(69)
0.224;-12170.0
58(6J)
0.199;-11565.0
58(6K)
0.195;-10960.0
6(59J)
0.210;-11262.5
6K(59)
0.215;-10657.5
(69)(5Q)
0.240;-8980.0
59(6T)
0.201;-11565.0
59(6Q)
0.197;-10960.0
6T(5T)
0.230;-9282.5
(5T)(6K)
0.240;-8375.0
5Q(6T)
0.211;-10657.5
56TJ
0.151;-12940.0
56TK
0.199;-12335.0
6K(5J)
0.271;-10052.5
56JJ
0.184;-10657.5
56JK
0.184;-12032.5
5(6QK)
0.254;-9750.0
6K(5K)
0.219;-7467.5
(57)(79)
0.237;-8210.0
7(57Q)
0.217;-9282.5
9(578)
0.183;-11867.5
K(578)
0.231;-10657.5
8(57J)
0.188;-11262.5
8K(57)
0.203;-10657.5
(579K)
0.206;-10355.0
9J(57)
0.181;-10960.0
(57TJ)
0.193;-10657.5
(57)(TJ)
0.216;-8677.5
J(57J)
0.250;-8375.0
JQ(57)
0.171;-10052.5
Q(57K)
0.213;-9447.5
5778
0.145;-12472.5
57(7J)
0.211;-9585.0
(58)(78)
0.218;-8210.0
7(58J)
0.170;-11262.5
7K(58)
0.224;-10657.5
(78)(5J)
0.205;-9282.5
5K(78)
0.204;-10657.5
57(8T)
0.149;-11565.0
57(8Q)
0.178;-10960.0
7(59T)
0.182;-11262.5
7Q(59)
0.169;-10657.5
(79)(5J)
0.217;-8980.0
5K(79)
0.260;-10355.0
57(9J)
0.208;-10960.0
57(9K)
0.205;-10355.0
(5T)(7Q)
0.241;-8375.0
5J(7T)
0.225;-10657.5
7T(5J)
0.182;-10657.5
7T(5K)
0.221;-10052.5
7Q(5J)
0.165;-10052.5
(7J)(5K)
0.267;-7770.0
7J(5K)
0.207;-9750.0
7K(5Q)
0.263;-9447.5
57(QK)
0.202;-9447.5
(58)(89)
0.206;-7605.0
8(58Q)
0.195;-8677.5
T(589)
0.221;-10960.0
9(58T)
0.195;-10960.0
9Q(58)
0.203;-10355.0
Q(58T)
0.254;-10052.5
(58)(TQ)
0.261;-8072.5
(58JK)
0.214;-9447.5
JK(58)
0.222;-9447.5
K(58K)
0.251;-6862.5
588T
0.211;-11262.5
58(8K)
0.248;-8375.0
(59)(8J)
0.219;-8677.5
59(89)
0.183;-9282.5
5(89Q)
0.220;-10355.0
58(9T)
0.184;-10960.0
58(9Q)
0.188;-10355.0
8(5TJ)
0.183;-10355.0
8K(5T)
0.217;-9750.0
(8T)(5K)
0.219;-7770.0
8T(5Q)
0.183;-10052.5
(5J)(8J)
0.229;-6092.5
5J(8J)
0.280;-8072.5
8J(5Q)
0.216;-9750.0
(5Q)(8Q)
0.207;-5487.5
5K(8Q)
0.189;-9145.0
5K(8K)
0.247;-6862.5
9J(59)
0.224;-8375.0
(59TJ)
0.227;-10052.5
(59)(TJ)
0.251;-8072.5
J(59J)
0.271;-7770.0
JQ(59)
0.181;-9447.5
Q(59K)
0.252;-8842.5
599T
0.258;-10657.5
59(9K)
0.237;-7770.0
(5T)(9Q)
0.200;-7770.0
5J(9T)
0.199;-10052.5
9T(5J)
0.227;-10052.5
9T(5K)
0.179;-9447.5
9Q(5J)
0.207;-9447.5
(9J)(5K)
0.197;-7165.0
9J(5K)
0.217;-9145.0
9K(5Q)
0.211;-8842.5
59(QK)
0.245;-8842.5
(5T)(TJ)
0.262;-5790.0
J(5TJ)
0.236;-7467.5
JQ(5T)
0.178;-9145.0
Q(5TK)
0.228;-8540.0
5TTJ
0.245;-9750.0
TJ(5J)
0.249;-7467.5
(TJ)(5Q)
0.240;-7165.0
5J(TQ)
0.204;-9145.0
TQ(5Q)
0.257;-6862.5
5TQQ
0.177;-8842.5
5TKK
0.202;-8237.5
Q(5JQ)
0.238;-6560.0
KK(5J)
0.235;-5955.0
(5Q)(JQ)
0.266;-4580.0
5K(JQ)
0.194;-8237.5
5K(JK)
0.218;-5955.0
5QQQ
0.228;-6257.5
KK(5K)
0.272;-3370.0
6669
0.185;-10492.5
666K
0.201;-9282.5
69(67)
0.174;-10190.0
(67)(6Q)
0.204;-7302.5
6678
0.207;-12472.5
66(7J)
0.204;-9585.0
(68)(68)
0.267;-6230.0
6(68J)
0.196;-9282.5
6K(68)
0.190;-8677.5
68(6J)
0.280;-9282.5
668K
0.163;-10657.5
6J(69)
0.231;-8980.0
69(6T)
0.237;-9282.5
669Q
0.201;-10657.5
6J(6T)
0.249;-8677.5
6T(6J)
0.194;-8677.5
66TK
0.207;-10052.5
6K(6J)
0.232;-7770.0
(6Q)(6Q)
0.239;-3810.0
66QK
0.216;-9447.5
7(679)
0.210;-9887.5
7J(67)
0.232;-9282.5
(6789)
0.238;-11565.0
(678K)
0.187;-10355.0
8T(67)
0.190;-11262.5
(67)(8K)
0.202;-8375.0
Q(679)
0.168;-10355.0
(67)(9J)
0.249;-8677.5
T(67T)
0.238;-8677.5
T(67J)
0.157;-10355.0
TK(67)
0.227;-9750.0
(67)(JQ)
0.220;-7770.0
QQ(67)
0.233;-7467.5
67(78)
0.170;-10190.0
77(6J)
0.187;-9282.5
677K
0.204;-10657.5
7T(68)
0.247;-11262.5
(68)(7K)
0.211;-8375.0
6T(78)
0.187;-11262.5
6(78K)
0.177;-10355.0
68(7T)
0.153;-11262.5
68(7Q)
0.178;-10657.5
79(69)
0.202;-9282.5
(69)(7Q)
0.198;-8375.0
6T(79)
0.193;-10960.0
6(79K)
0.192;-10052.5
69(7J)
0.192;-10657.5
69(7K)
0.228;-10052.5
7(6TQ)
0.169;-10052.5
6(7TJ)
0.200;-10355.0
67TT
0.263;-10657.5
67TQ
0.206;-12032.5
(6J)(7Q)
0.253;-7770.0
6Q(7J)
0.242;-9750.0
67JQ
0.164;-11730.0
(6Q)(7K)
0.219;-7165.0
6Q(7K)
0.167;-9145.0
8(689)
0.179;-9282.5
8J(68)
0.260;-8677.5
(689T)
0.223;-10657.5
99(68)
0.244;-8980.0
(68)(9Q)
0.276;-8072.5
(68TQ)
0.186;-9750.0
T(68Q)
0.185;-9750.0
Q(68J)
0.195;-9447.5
(68)(JK)
0.192;-7165.0
QK(68)
0.267;-8842.5
68(8T)
0.225;-8980.0
88(6K)
0.231;-8072.5
8(69J)
0.244;-10355.0
8K(69)
0.195;-9750.0
(89)(6Q)
0.225;-8072.5
69(8T)
0.180;-10657.5
69(8Q)
0.220;-10052.5
8T(6T)
0.212;-8375.0
(6T)(8K)
0.192;-7467.5
6Q(8T)
0.179;-9750.0
68TJ
0.198;-12032.5
68TK
0.174;-11427.5
8K(6J)
0.202;-9145.0
68JJ
0.215;-9750.0
68JK
0.200;-11125.0
6(8QK)
0.195;-8842.5
8K(6K)
0.205;-6560.0
(69)(9J)
0.281;-6092.5
T(69T)
0.257;-8072.5
T(69J)
0.190;-9750.0
TK(69)
0.264;-9145.0
(69)(JQ)
0.257;-7165.0
QQ(69)
0.249;-6862.5
69(9T)
0.224;-8375.0
99(6K)
0.288;-7467.5
9(6TQ)
0.234;-9447.5
6(9TJ)
0.235;-9750.0
69TT
0.203;-10052.5
69TQ
0.196;-11427.5
(6J)(9Q)
0.221;-7165.0
6Q(9J)
0.171;-9145.0
69JQ
0.208;-11125.0
(6Q)(9K)
0.246;-6560.0
6Q(9K)
0.229;-8540.0
T(6TJ)
0.188;-7467.5
TK(6T)
0.259;-6862.5
(6T)(JQ)
0.262;-6862.5
QQ(6T)
0.232;-6560.0
6T(TJ)
0.304;-7467.5
(6J)(TJ)
0.309;-5185.0
6J(TJ)
0.249;-7165.0
TJ(6Q)
0.213;-8842.5
(6Q)(TQ)
0.307;-4580.0
6K(TQ)
0.191;-8237.5
6K(TK)
0.271;-5955.0
JK(6J)
0.302;-6257.5
K(6JK)
0.271;-5652.5
6JJK
0.219;-8237.5
6(JQK)
0.279;-7935.0
JK(6K)
0.283;-5652.5
KK(6Q)
0.222;-5350.0
6QKK
0.247;-7330.0
77(7T)
0.200;-7302.5
(78)(78)
0.302;-5625.0
7(78J)
0.206;-8677.5
7K(78)
0.273;-8072.5
78(7J)
0.224;-8677.5
778K
0.182;-10052.5
7J(79)
0.238;-8375.0
79(7T)
0.215;-8677.5
779Q
0.195;-10052.5
7J(7T)
0.244;-8072.5
7T(7J)
0.280;-8072.5
77TK
0.198;-9447.5
7K(7J)
0.198;-7165.0
(7Q)(7Q)
0.313;-3205.0
77QK
0.229;-8842.5
8(78T)
0.195;-8677.5
8Q(78)
0.218;-8072.5
J(789)
0.191;-10052.5
9T(78)
0.227;-10355.0
(78)(9K)
0.235;-7467.5
K(78T)
0.233;-9145.0
T(78K)
0.188;-9145.0
JJ(78)
0.198;-7467.5
(78QK)
0.243;-8540.0
7888
0.214;-9282.5
78(8J)
0.303;-8375.0
(79)(89)
0.242;-6697.5
8(79Q)
0.226;-9750.0
7(89T)
0.187;-10355.0
(89)(7K)
0.227;-7467.5
89(7J)
0.241;-10052.5
89(7K)
0.230;-9447.5
8J(7T)
0.232;-9750.0
(8T)(7J)
0.234;-7770.0
7K(8T)
0.247;-9145.0
78(TQ)
0.217;-9447.5
8(7JQ)
0.249;-9145.0
7(8JQ)
0.188;-9145.0
78(JQ)
0.217;-9145.0
8(7QK)
0.215;-8540.0
8Q(7K)
0.262;-8540.0
99(79)
0.292;-6395.0
(79)(9Q)
0.217;-5487.5
(79TQ)
0.208;-9145.0
T(79Q)
0.179;-9145.0
Q(79J)
0.212;-8842.5
(79)(JK)
0.213;-6560.0
QK(79)
0.201;-8237.5
79(9J)
0.259;-7770.0
(7T)(9T)
0.267;-5790.0
9(7TK)
0.242;-8842.5
7(9TQ)
0.181;-9145.0
79(TJ)
0.233;-9447.5
79(TK)
0.260;-8842.5
(7J)(9K)
0.277;-6560.0
7K(9J)
0.221;-8540.0
79(JK)
0.214;-8540.0
(9Q)(7K)
0.286;-6257.5
(7K)(9K)
0.285;-3975.0
T(7TQ)
0.276;-6862.5
Q(7TJ)
0.177;-8540.0
(7T)(JK)
0.300;-6257.5
QK(7T)
0.218;-7935.0
7T(TQ)
0.267;-6862.5
(7J)(TQ)
0.214;-6560.0
7Q(TJ)
0.258;-8540.0
7TJQ
0.202;-10520.0
(7Q)(TK)
0.243;-5955.0
7Q(TK)
0.221;-7935.0
J(7JQ)
0.222;-6257.5
K(7JQ)
0.252;-7632.5
JJ(7Q)
0.235;-6257.5
J(7QK)
0.235;-7632.5
JQ(7K)
0.296;-7632.5
QQ(7Q)
0.282;-3672.5
7Q(QK)
0.314;-5350.0
8888
0.200;-7000.0
888Q
0.243;-7770.0
8(89J)
0.281;-7770.0
8K(89)
0.238;-7165.0
89(8Q)
0.250;-7467.5
8(8TJ)
0.289;-7467.5
8K(8T)
0.294;-6862.5
8T(8K)
0.281;-6862.5
8(8JK)
0.242;-6560.0
88(JK)
0.231;-6560.0
8Q(8K)
0.302;-6257.5
(89)(9T)
0.258;-5790.0
9(89K)
0.251;-6862.5
(89TK)
0.215;-8540.0
TQ(89)
0.187;-8842.5
K(89J)
0.221;-8237.5
Q(89Q)
0.262;-6257.5
KK(89)
0.275;-5652.5
99(8Q)
0.232;-7165.0
9(8TJ)
0.198;-9145.0
9K(8T)
0.289;-8540.0
(9T)(8K)
0.287;-6560.0
9T(8Q)
0.221;-8842.5
(8J)(9J)
0.335;-4882.5
8J(9J)
0.249;-6862.5
9J(8Q)
0.280;-8540.0
(8Q)(9Q)
0.308;-4277.5
8K(9Q)
0.230;-7935.0
8K(9K)
0.313;-5652.5
TQ(8T)
0.197;-6560.0
K(8TJ)
0.245;-7935.0
Q(8TQ)
0.277;-5955.0
KK(8T)
0.301;-5350.0
