AAAA
0.394;3280.0
5AAA
0.348;-140.0
9AAA
0.349;740.0
KAAA
0.388;1620.0
4A(2A)
0.281;-3000.0
(2A)(7A)
0.343;-900.0
A(2TA)
0.319;-1680.0
QA(2A)
0.336;-1240.0
2A(4A)
0.336;-3000.0
26AA
0.310;-4000.0
AA(29)
0.302;-1900.0
2A(QA)
0.345;-1240.0
A(34A)
0.250;-2780.0
6A(3A)
0.296;-2340.0
(3A)(9A)
0.325;-240.0
A(3QA)
0.360;-1020.0
AA(34)
0.267;-2780.0
3A(7A)
0.266;-2120.0
39AA
0.330;-3120.0
AA(3Q)
0.357;-1020.0
(4A)(5A)
0.357;-900.0
A(48A)
0.332;-1680.0
TA(4A)
0.309;-1240.0
(4A)(KA)
0.348;860.0
46AA
0.318;-3560.0
AA(49)
0.323;-1460.0
4A(QA)
0.343;-800.0
A(56A)
0.274;-1900.0
8A(5A)
0.320;-1460.0
(5A)(JA)
0.359;640.0
55AA
0.279;-2120.0
AA(58)
0.281;-1460.0
5A(JA)
0.351;-800.0
5KAA
0.361;-1800.0
8A(6A)
0.324;-1240.0
(6A)(JA)
0.327;860.0
66AA
0.343;-1680.0
AA(69)
0.361;-1020.0
6A(QA)
0.358;-360.0
A(78A)
0.397;-1020.0
TA(7A)
0.350;-580.0
(7A)(KA)
0.352;1520.0
79AA
0.245;-2240.0
AA(7Q)
0.370;-140.0
(8A)(9A)
0.384;860.0
A(8QA)
0.347;80.0
AA(89)
0.351;-580.0
8A(QA)
0.346;80.0
A(9TA)
0.276;-140.0
QA(9A)
0.369;300.0
9A(JA)
0.345;80.0
9KAA
0.314;-920.0
QA(TA)
0.306;520.0
TA(QA)
0.350;520.0
A(JQA)
0.339;740.0
AA(JQ)
0.391;740.0
(QA)(KA)
0.395;2620.0
KKAA
0.379;1400.0
2(25A)
0.297;-5420.0
27(2A)
0.257;-4980.0
(2T)(2A)
0.304;-2880.0
2(2KA)
0.296;-3660.0
(236A)
0.258;-6420.0
(23TA)
0.255;-5540.0
33(2A)
0.208;-5640.0
(36)(2A)
0.242;-4980.0
3(29A)
0.255;-5760.0
3J(2A)
0.252;-5320.0
(245A)
0.235;-6420.0
(249A)
0.237;-5540.0
(24KA)
0.228;-4660.0
46(2A)
0.231;-6200.0
(49)(2A)
0.283;-4100.0
4(2QA)
0.258;-4880.0
6(25A)
0.261;-5980.0
T(25A)
0.224;-5100.0
5(26A)
0.286;-5980.0
58(2A)
0.251;-5540.0
(5J)(2A)
0.334;-3440.0
6(26A)
0.261;-4320.0
T(26A)
0.224;-4880.0
6(27A)
0.280;-5540.0
69(2A)
0.269;-5100.0
(6Q)(2A)
0.317;-3000.0
(279A)
0.272;-4880.0
(27KA)
0.289;-4000.0
79(2A)
0.236;-4880.0
(7Q)(2A)
0.245;-2780.0
(28TA)
0.253;-4440.0
88(2A)
0.263;-3440.0
(8J)(2A)
0.262;-2780.0
9(29A)
0.294;-3000.0
K(29A)
0.257;-3560.0
9(2QA)
0.216;-3780.0
J(2TA)
0.305;-3780.0
TJ(2A)
0.328;-3780.0
(2JQA)
0.282;-3340.0
J(2KA)
0.327;-3120.0
(QK)(2A)
0.340;-1460.0
22(4A)
0.262;-5640.0
226A
0.245;-6640.0
2A(29)
0.316;-4540.0
22(QA)
0.266;-3880.0
2(34A)
0.243;-6860.0
26(3A)
0.177;-6420.0
(29)(3A)
0.319;-4320.0
2(3QA)
0.267;-5100.0
A(234)
0.197;-6860.0
(23)(7A)
0.260;-4760.0
9A(23)
0.268;-5760.0
A(23Q)
0.214;-5100.0
2A(34)
0.193;-6860.0
2A(36)
0.233;-6420.0
2A(38)
0.252;-5980.0
2A(3T)
0.195;-5540.0
2A(3Q)
0.257;-5100.0
2(45A)
0.238;-6420.0
27(4A)
0.274;-5980.0
(2T)(4A)
0.299;-3880.0
2(4KA)
0.251;-4660.0
A(246)
0.229;-6200.0
(24)(9A)
0.312;-4100.0
JA(24)
0.244;-5100.0
24(5A)
0.216;-6420.0
24(7A)
0.276;-5980.0
24(9A)
0.238;-5540.0
24(JA)
0.209;-5100.0
24(KA)
0.212;-4660.0
26(5A)
0.218;-5980.0
(29)(5A)
0.237;-3880.0
2(5QA)
0.319;-4660.0
A(256)
0.263;-5980.0
(25)(9A)
0.264;-3880.0
JA(25)
0.290;-4880.0
25(6A)
0.243;-5980.0
25(8A)
0.259;-5540.0
25(TA)
0.249;-5100.0
25(QA)
0.300;-4660.0
(26)(6A)
0.269;-2880.0
2(69A)
0.309;-5100.0
2J(6A)
0.259;-4660.0
(26)(7A)
0.317;-4100.0
9A(26)
0.261;-5100.0
A(26Q)
0.263;-4440.0
2A(67)
0.282;-5540.0
2A(69)
0.204;-5100.0
2A(6J)
0.247;-4660.0
2A(6K)
0.300;-4220.0
(29)(7A)
0.253;-3440.0
2(7QA)
0.278;-4220.0
A(278)
0.252;-5100.0
(27)(JA)
0.258;-3000.0
KA(27)
0.266;-4000.0
2A(79)
0.248;-4880.0
2A(7J)
0.284;-4440.0
2A(7K)
0.272;-4000.0
(2T)(8A)
0.294;-3000.0
2(8KA)
0.288;-3780.0
A(28T)
0.260;-4440.0
(28)(KA)
0.288;-2340.0
28(TA)
0.245;-4440.0
28(QA)
0.240;-4000.0
(29)(9A)
0.313;-1560.0
2(9QA)
0.245;-3780.0
A(29T)
0.277;-4220.0
(29)(KA)
0.340;-2120.0
29(JA)
0.279;-4000.0
29(KA)
0.273;-3560.0
2J(TA)
0.257;-3780.0
(2T)(JA)
0.362;-2340.0
KA(2T)
0.232;-3340.0
2A(TQ)
0.338;-3560.0
2(JQA)
0.263;-3340.0
A(2JQ)
0.341;-3340.0
2A(JQ)
0.294;-3340.0
2(QKA)
0.289;-2900.0
2Q(KA)
0.281;-2900.0
33(3A)
0.277;-3980.0
(36)(3A)
0.329;-3320.0
3(39A)
0.250;-4100.0
3J(3A)
0.294;-3660.0
(345A)
0.232;-6200.0
(349A)
0.264;-5320.0
(34KA)
0.283;-4440.0
46(3A)
0.215;-5980.0
(49)(3A)
0.306;-3880.0
4(3QA)
0.271;-4660.0
6(35A)
0.300;-5760.0
T(35A)
0.252;-4880.0
5(36A)
0.236;-5760.0
58(3A)
0.286;-5320.0
(5J)(3A)
0.262;-3220.0
6(36A)
0.289;-4100.0
T(36A)
0.281;-4660.0
6(37A)
0.227;-5320.0
69(3A)
0.245;-4880.0
(6Q)(3A)
0.293;-2780.0
(379A)
0.245;-4660.0
(37KA)
0.310;-3780.0
79(3A)
0.308;-4660.0
(7Q)(3A)
0.337;-2560.0
(38TA)
0.310;-4220.0
88(3A)
0.286;-3220.0
(8J)(3A)
0.340;-2560.0
9(39A)
0.279;-2780.0
K(39A)
0.280;-3340.0
9(3QA)
0.225;-3560.0
J(3TA)
0.313;-3560.0
TJ(3A)
0.317;-3560.0
(3JQA)
0.280;-3120.0
J(3KA)
0.355;-2900.0
(QK)(3A)
0.280;-1240.0
33(5A)
0.234;-4980.0
337A
0.245;-5980.0
3A(3T)
0.289;-3880.0
33(KA)
0.252;-3220.0
3(46A)
0.260;-5980.0
38(4A)
0.257;-5540.0
(3J)(4A)
0.280;-3440.0
4A(34)
0.271;-4980.0
A(347)
0.298;-5760.0
(34)(TA)
0.290;-3660.0
QA(34)
0.225;-4660.0
345A
0.226;-7640.0
347A
0.210;-7200.0
349A
0.186;-6760.0
34JA
0.258;-6320.0
34KA
0.273;-5880.0
37(5A)
0.270;-5540.0
(3T)(5A)
0.233;-3440.0
3(5KA)
0.278;-4220.0
A(357)
0.246;-5540.0
(35)(TA)
0.320;-3440.0
QA(35)
0.288;-4440.0
356A
0.283;-7200.0
358A
0.193;-6760.0
35TA
0.272;-6320.0
35QA
0.290;-5880.0
(37)(6A)
0.265;-3880.0
3(6TA)
0.262;-4660.0
3Q(6A)
0.301;-4220.0
(36)(8A)
0.283;-3660.0
TA(36)
0.280;-4660.0
A(36K)
0.337;-4000.0
6A(38)
0.326;-5100.0
6A(3T)
0.296;-4660.0
6A(3Q)
0.247;-4220.0
37(7A)
0.261;-3660.0
(3T)(7A)
0.328;-3000.0
3(7KA)
0.295;-3780.0
A(379)
0.259;-4660.0
(37)(QA)
0.335;-2560.0
7A(38)
0.321;-4880.0
7A(3T)
0.221;-4440.0
7A(3Q)
0.300;-4000.0
38(8A)
0.323;-3220.0
(3J)(8A)
0.300;-2560.0
8A(38)
0.249;-3220.0
A(38J)
0.254;-4000.0
388A
0.259;-4660.0
38TA
0.258;-5660.0
38QA
0.244;-5220.0
(3T)(9A)
0.328;-2560.0
3(9KA)
0.243;-3340.0
A(39J)
0.285;-3780.0
399A
0.307;-4220.0
39JA
0.276;-5220.0
39KA
0.235;-4780.0
3Q(TA)
0.277;-3340.0
(3T)(QA)
0.320;-1900.0
TA(3J)
0.292;-3560.0
TA(3K)
0.298;-3120.0
3(JKA)
0.323;-2900.0
A(3JK)
0.323;-2900.0
JA(3K)
0.323;-2900.0
QA(3Q)
0.355;-1460.0
3QKA
0.266;-4120.0
45(4A)
0.223;-4540.0
(48)(4A)
0.355;-2440.0
4(4JA)
0.236;-3220.0
4K(4A)
0.311;-2780.0
(459A)
0.221;-4880.0
(45KA)
0.302;-4000.0
57(4A)
0.214;-5320.0
(5T)(4A)
0.282;-3220.0
5(4KA)
0.249;-4000.0
(469A)
0.312;-4660.0
(46KA)
0.283;-3780.0
68(4A)
0.274;-4880.0
(6J)(4A)
0.276;-2780.0
7(47A)
0.351;-3440.0
J(47A)
0.246;-4000.0
78(4A)
0.212;-4660.0
(7J)(4A)
0.323;-2560.0
8(48A)
0.256;-3000.0
Q(48A)
0.249;-3560.0
(8T)(4A)
0.331;-2560.0
8(4KA)
0.252;-3340.0
(49QA)
0.287;-3340.0
9(4JA)
0.292;-3560.0
9K(4A)
0.325;-3120.0
TT(4A)
0.249;-2120.0
(TK)(4A)
0.331;-1460.0
J(4QA)
0.343;-2900.0
K(4QA)
0.303;-2460.0
44(5A)
0.331;-4540.0
447A
0.223;-5540.0
4A(4T)
0.300;-3440.0
44(KA)
0.350;-2780.0
4(57A)
0.196;-5320.0
49(5A)
0.217;-4880.0
(4Q)(5A)
0.286;-2780.0
6A(45)
0.255;-5540.0
A(459)
0.251;-4880.0
(45)(QA)
0.295;-2780.0
5A(46)
0.282;-5540.0
5A(48)
0.247;-5100.0
5A(4T)
0.274;-4660.0
5A(4Q)
0.288;-4220.0
46(6A)
0.237;-3880.0
(49)(6A)
0.231;-3220.0
4(6QA)
0.290;-4000.0
A(467)
0.245;-5100.0
(46)(TA)
0.310;-3000.0
QA(46)
0.261;-4000.0
467A
0.228;-6540.0
469A
0.258;-6100.0
46JA
0.241;-5660.0
46KA
0.236;-5220.0
49(7A)
0.292;-4440.0
(4Q)(7A)
0.302;-2340.0
8A(47)
0.269;-4660.0
A(47J)
0.276;-4000.0
477A
0.308;-4880.0
479A
0.287;-5880.0
47JA
0.299;-5440.0
47KA
0.265;-5000.0
4T(8A)
0.283;-4000.0
(4K)(8A)
0.381;-1900.0
TA(48)
0.307;-4000.0
A(48K)
0.291;-3340.0
8A(4T)
0.283;-4000.0
8A(4Q)
0.357;-3560.0
49(9A)
0.313;-2560.0
(4Q)(9A)
0.333;-1900.0
TA(49)
0.321;-3780.0
A(49K)
0.276;-3120.0
9A(4J)
0.312;-3560.0
9A(4K)
0.247;-3120.0
4(TQA)
0.292;-3120.0
A(4TJ)
0.276;-3340.0
4TTA
0.270;-3560.0
4TQA
0.217;-4560.0
(4Q)(JA)
0.318;-1460.0
QA(4J)
0.265;-2900.0
4JQA
0.235;-4340.0
(4K)(QA)
0.328;-1020.0
QA(4K)
0.253;-2460.0
5(56A)
0.271;-3880.0
58(5A)
0.259;-3440.0
(5J)(5A)
0.318;-1340.0
6(56A)
0.299;-3660.0
T(56A)
0.259;-4220.0
6(57A)
0.264;-4880.0
69(5A)
0.304;-4440.0
(6Q)(5A)
0.302;-2340.0
(579A)
0.331;-4220.0
(57KA)
0.329;-3340.0
79(5A)
0.283;-4220.0
(7Q)(5A)
0.315;-2120.0
(58TA)
0.290;-3780.0
88(5A)
0.356;-2780.0
(8J)(5A)
0.304;-2120.0
9(59A)
0.309;-2340.0
K(59A)
0.289;-2900.0
9(5QA)
0.259;-3120.0
J(5TA)
0.304;-3120.0
TJ(5A)
0.293;-3120.0
(5JQA)
0.293;-2680.0
J(5KA)
0.320;-2460.0
(QK)(5A)
0.357;-800.0
55(7A)
0.225;-3660.0
559A
0.347;-4660.0
5A(5Q)
0.326;-2560.0
(57)(6A)
0.230;-3440.0
5(6TA)
0.229;-4220.0
5Q(6A)
0.295;-3780.0
(56)(8A)
0.285;-3220.0
TA(56)
0.271;-4220.0
A(56K)
0.332;-3560.0
6A(58)
0.234;-4660.0
6A(5T)
0.319;-4220.0
6A(5Q)
0.274;-3780.0
57(7A)
0.263;-3220.0
(5T)(7A)
0.299;-2560.0
5(7KA)
0.264;-3340.0
A(579)
0.251;-4220.0
(57)(QA)
0.294;-2120.0
7A(58)
0.320;-4440.0
7A(5T)
0.265;-4000.0
7A(5Q)
0.275;-3560.0
58(8A)
0.305;-2780.0
(5J)(8A)
0.307;-2120.0
8A(58)
0.319;-2780.0
A(58J)
0.365;-3560.0
588A
0.319;-4220.0
58TA
0.261;-5220.0
58QA
0.296;-4780.0
(5T)(9A)
0.321;-2120.0
5(9KA)
0.243;-2900.0
A(59J)
0.275;-3340.0
599A
0.277;-3780.0
59JA
0.282;-4780.0
59KA
0.307;-4340.0
5Q(TA)
0.315;-2900.0
(5T)(QA)
0.280;-1460.0
TA(5J)
0.315;-3120.0
TA(5K)
0.295;-2680.0
5(JKA)
0.292;-2460.0
A(5JK)
0.350;-2460.0
JA(5K)
0.365;-2460.0
QA(5Q)
0.386;-1020.0
5QKA
0.250;-3680.0
67(6A)
0.226;-3220.0
(6T)(6A)
0.322;-1120.0
6(6KA)
0.295;-1900.0
(67TA)
0.318;-3780.0
77(6A)
0.262;-3000.0
(7T)(6A)
0.287;-2340.0
7(6KA)
0.293;-3120.0
(68JA)
0.310;-3340.0
(89)(6A)
0.316;-2340.0
8(6QA)
0.306;-3120.0
T(69A)
0.270;-3340.0
9(6TA)
0.362;-3340.0
9Q(6A)
0.259;-2900.0
Q(6TA)
0.347;-2680.0
(TQ)(6A)
0.330;-1240.0
(6JKA)
0.257;-2240.0
JK(6A)
0.306;-2240.0
K(6KA)
0.317;-360.0
668A
0.269;-4440.0
6A(6J)
0.330;-2340.0
(67)(7A)
0.287;-1560.0
6(7TA)
0.266;-3780.0
6Q(7A)
0.269;-3340.0
(67)(9A)
0.297;-2560.0
JA(67)
0.255;-3560.0
67(8A)
0.322;-4220.0
67(TA)
0.231;-3780.0
67(QA)
0.245;-3340.0
(68)(8A)
0.317;-1120.0
6(8JA)
0.268;-3340.0
6K(8A)
0.298;-2900.0
(68)(JA)
0.275;-1900.0
KA(68)
0.316;-2900.0
6A(8T)
0.246;-3560.0
6A(8Q)
0.351;-3120.0
6(9TA)
0.263;-3340.0
6Q(9A)
0.355;-2900.0
(69)(JA)
0.271;-1680.0
KA(69)
0.359;-2680.0
6A(9J)
0.297;-3120.0
6A(9K)
0.295;-2680.0
(6Q)(TA)
0.313;-1240.0
JA(6T)
0.291;-2900.0
6T(JA)
0.279;-2900.0
6T(KA)
0.311;-2460.0
6Q(JA)
0.333;-2460.0
(6J)(KA)
0.353;-800.0
6J(KA)
0.355;-2240.0
6K(QA)
0.244;-2020.0
6A(QK)
0.331;-2020.0
(78)(7A)
0.345;-1120.0
7(7JA)
0.262;-1900.0
7K(7A)
0.376;-1460.0
(78QA)
0.299;-2900.0
8(7TA)
0.287;-3340.0
8Q(7A)
0.234;-2900.0
J(79A)
0.275;-2900.0
9T(7A)
0.308;-3120.0
(9K)(7A)
0.374;-1020.0
K(7TA)
0.320;-2240.0
T(7KA)
0.335;-2240.0
JJ(7A)
0.295;-1020.0
(7QKA)
0.322;-1800.0
777A
0.337;-2780.0
7A(7T)
0.334;-2120.0
77(KA)
0.270;-1460.0
7(8TA)
0.289;-3340.0
7Q(8A)
0.284;-2900.0
(78)(TA)
0.340;-1900.0
QA(78)
0.331;-2900.0
789A
0.255;-5000.0
78JA
0.254;-4560.0
78KA
0.334;-4120.0
7J(9A)
0.328;-2900.0
(79)(TA)
0.320;-1680.0
QA(79)
0.331;-2680.0
79TA
0.297;-4560.0
79QA
0.230;-4120.0
(7J)(TA)
0.342;-1240.0
TA(7T)
0.358;-1460.0
A(7TK)
0.289;-2240.0
TA(7Q)
0.257;-2460.0
7J(JA)
0.374;-1020.0
(7J)(QA)
0.283;-800.0
JA(7Q)
0.285;-2240.0
7Q(QA)
0.364;-580.0
7QQA
0.349;-2020.0
7KKA
0.269;-1580.0
8(8JA)
0.283;-1460.0
8K(8A)
0.364;-1020.0
(89KA)
0.343;-2240.0
9J(8A)
0.279;-2680.0
(8TJA)
0.273;-2460.0
(TJ)(8A)
0.328;-1020.0
J(8JA)
0.312;-800.0
JQ(8A)
0.254;-2020.0
Q(8KA)
0.277;-1580.0
889A
0.295;-3340.0
8A(8Q)
0.315;-1240.0
(8T)(9A)
0.335;-1460.0
8(9KA)
0.362;-2240.0
A(89J)
0.313;-2680.0
899A
0.288;-3120.0
89JA
0.220;-4120.0
89KA
0.245;-3680.0
8Q(TA)
0.284;-2240.0
(8T)(QA)
0.373;-800.0
TA(8J)
0.348;-2460.0
TA(8K)
0.315;-2020.0
8(JKA)
0.310;-1800.0
A(8JK)
0.326;-1800.0
JA(8K)
0.300;-1800.0
QA(8Q)
0.357;-360.0
8QKA
0.259;-3020.0
9T(9A)
0.326;-1240.0
(9K)(9A)
0.381;860.0
K(9TA)
0.260;-1800.0
T(9KA)
0.255;-1800.0
JJ(9A)
0.284;-580.0
(9QKA)
0.324;-1360.0
999A
0.261;-1460.0
9A(9Q)
0.353;-800.0
(9J)(TA)
0.367;-800.0
TA(9T)
0.325;-1020.0
A(9TK)
0.279;-1800.0
TA(9Q)
0.311;-2020.0
9J(JA)
0.296;-580.0
(9J)(QA)
0.356;-360.0
JA(9Q)
0.364;-1800.0
9Q(QA)
0.319;-140.0
9QQA
0.365;-1580.0
9KKA
0.338;-1140.0
T(TKA)
0.360;-140.0
JJ(TA)
0.328;-360.0
(TQKA)
0.372;-1140.0
TTTA
0.409;-800.0
TA(TK)
0.318;-140.0
(TK)(JA)
0.308;80.0
KA(TJ)
0.389;-1360.0
TA(JK)
0.289;-1360.0
(TQ)(KA)
0.353;300.0
(TK)(KA)
0.330;1960.0
J(JKA)
0.418;300.0
(QK)(JA)
0.314;520.0
JJ(KA)
0.372;300.0
QA(JQ)
0.339;300.0
JQKA
0.259;-2360.0
QK(QA)
0.321;740.0
QK(KA)
0.370;960.0
22(24)
0.253;-6840.0
22(28)
0.283;-5960.0
22(2Q)
0.297;-5080.0
24(23)
0.244;-8060.0
(23)(27)
0.289;-5960.0
2(23T)
0.270;-6740.0
2Q(23)
0.239;-6300.0
23(25)
0.259;-7840.0
2237
0.210;-8840.0
22(3T)
0.223;-6740.0
23(2K)
0.236;-6080.0
2(246)
0.181;-7400.0
28(24)
0.227;-6960.0
(24)(2J)
0.295;-4860.0
2244
0.240;-7840.0
22(47)
0.213;-7180.0
24(2T)
0.191;-6520.0
224Q
0.240;-7520.0
26(25)
0.293;-7180.0
(25)(29)
0.267;-5080.0
2(25Q)
0.214;-5860.0
22(56)
0.236;-7180.0
25(29)
0.275;-6520.0
225J
0.194;-7520.0
26(26)
0.253;-5520.0
(26)(29)
0.299;-4860.0
2(26Q)
0.263;-5640.0
22(67)
0.306;-6740.0
26(2T)
0.259;-6080.0
226Q
0.221;-7080.0
28(27)
0.228;-6300.0
(27)(2J)
0.255;-4200.0
2277
0.242;-6520.0
22(7T)
0.234;-5860.0
27(2K)
0.291;-5200.0
2(28T)
0.214;-5640.0
2Q(28)
0.265;-5200.0
28(2T)
0.322;-5640.0
228Q
0.183;-6640.0
2T(29)
0.247;-5420.0
(29)(2K)
0.310;-3320.0
229J
0.241;-6640.0
2T(2T)
0.266;-3760.0
(2T)(2K)
0.295;-3100.0
22TQ
0.257;-6200.0
2Q(2J)
0.274;-4540.0
2J(2K)
0.259;-4320.0
22QQ
0.291;-4320.0
3(234)
0.175;-7840.0
36(23)
0.201;-7400.0
(23)(39)
0.244;-5300.0
3(23Q)
0.271;-6080.0
5(234)
0.178;-8840.0
9(234)
0.197;-7960.0
K(234)
0.174;-7080.0
4(237)
0.218;-8400.0
49(23)
0.169;-7960.0
(23)(4Q)
0.234;-5860.0
(2357)
0.181;-8180.0
(235J)
0.201;-7300.0
(23)(56)
0.192;-6960.0
5(239)
0.214;-7740.0
5J(23)
0.212;-7300.0
(2367)
0.255;-7960.0
(236J)
0.193;-7080.0
(23)(67)
0.284;-6520.0
6(23T)
0.293;-7300.0
6Q(23)
0.262;-6860.0
9(237)
0.199;-7300.0
K(237)
0.201;-6420.0
7(23T)
0.199;-7080.0
7Q(23)
0.250;-6640.0
T(238)
0.242;-6860.0
8(239)
0.213;-7080.0
8J(23)
0.244;-6640.0
(239T)
0.264;-6640.0
99(23)
0.290;-5420.0
(23)(9Q)
0.281;-4760.0
(23TQ)
0.287;-5980.0
T(23Q)
0.260;-5980.0
Q(23J)
0.216;-5760.0
(23)(JK)
0.279;-4100.0
QK(23)
0.323;-5320.0
23(35)
0.259;-7620.0
33(28)
0.246;-6960.0
233T
0.221;-7960.0
23(3K)
0.209;-5860.0
(24)(36)
0.241;-7180.0
3(249)
0.240;-7960.0
3J(24)
0.236;-7520.0
(34)(25)
0.260;-7400.0
27(34)
0.168;-8400.0
2(34T)
0.221;-7740.0
(34)(2K)
0.259;-5640.0
34(26)
0.192;-8620.0
34(28)
0.198;-8180.0
34(2T)
0.238;-7740.0
34(2Q)
0.228;-7300.0
(25)(35)
0.255;-5740.0
3(258)
0.204;-7960.0
3T(25)
0.256;-7520.0
(25)(3K)
0.295;-5420.0
27(35)
0.238;-8180.0
2(35T)
0.233;-7520.0
(35)(2K)
0.236;-5420.0
35(27)
0.206;-8180.0
35(29)
0.224;-7740.0
35(2J)
0.267;-7300.0
35(2K)
0.233;-6860.0
37(26)
0.229;-7960.0
(26)(3T)
0.310;-5860.0
3(26K)
0.209;-6640.0
2(368)
0.199;-7740.0
(36)(2J)
0.287;-5640.0
2K(36)
0.246;-6640.0
23(68)
0.180;-7740.0
23(6T)
0.201;-7300.0
23(6Q)
0.240;-6860.0
3(278)
0.232;-7520.0
3T(27)
0.208;-7080.0
(27)(3K)
0.213;-4980.0
29(37)
0.232;-7300.0
2(37Q)
0.237;-6640.0
23(78)
0.230;-7520.0
23(7T)
0.216;-7080.0
23(7Q)
0.247;-6640.0
3(289)
0.249;-7080.0
3J(28)
0.181;-6640.0
(38)(29)
0.279;-5640.0
2J(38)
0.295;-6640.0
38(29)
0.268;-7080.0
38(2J)
0.281;-6640.0
38(2K)
0.230;-6200.0
3T(29)
0.255;-6640.0
(29)(3K)
0.301;-4540.0
2J(39)
0.228;-6420.0
39(2T)
0.245;-6640.0
39(2Q)
0.240;-6200.0
(2T)(3T)
0.295;-3540.0
3(2TK)
0.297;-5760.0
2(3TQ)
0.289;-5980.0
23(TJ)
0.280;-6200.0
23(TK)
0.301;-5760.0
(2J)(3K)
0.273;-4100.0
2K(3J)
0.225;-5540.0
23(JK)
0.221;-5540.0
(3Q)(2K)
0.263;-3880.0
(2K)(3K)
0.320;-2220.0
4(246)
0.226;-6960.0
48(24)
0.235;-6520.0
(24)(4J)
0.261;-4420.0
5(245)
0.221;-6960.0
9(245)
0.212;-7520.0
K(245)
0.259;-6640.0
5(248)
0.225;-7740.0
5T(24)
0.224;-7300.0
(24)(5K)
0.266;-5200.0
9(246)
0.238;-7300.0
K(246)
0.244;-6420.0
6(249)
0.218;-7300.0
6J(24)
0.201;-6860.0
(2478)
0.245;-7300.0
(247Q)
0.253;-6420.0
7(249)
0.283;-7080.0
7J(24)
0.253;-6640.0
(2489)
0.303;-6860.0
(248K)
0.230;-5980.0
8T(24)
0.227;-6640.0
(24)(8K)
0.328;-4540.0
Q(249)
0.254;-5980.0
(24)(9J)
0.263;-4760.0
T(24T)
0.232;-4760.0
T(24J)
0.256;-5980.0
TK(24)
0.209;-5540.0
(24)(JQ)
0.236;-4100.0
QQ(24)
0.241;-3880.0
24(45)
0.265;-7180.0
44(28)
0.231;-6520.0
244T
0.216;-7520.0
24(4K)
0.244;-5420.0
(25)(47)
0.258;-6520.0
4(25T)
0.205;-7300.0
4Q(25)
0.206;-6860.0
(45)(27)
0.280;-6520.0
29(45)
0.199;-7520.0
2(45Q)
0.178;-6860.0
24(56)
0.197;-8180.0
24(58)
0.216;-7740.0
24(5T)
0.264;-7300.0
24(5Q)
0.223;-6860.0
4(267)
0.205;-7740.0
49(26)
0.233;-7300.0
(26)(4Q)
0.264;-5200.0
27(46)
0.210;-7740.0
2(46T)
0.207;-7080.0
(46)(2K)
0.215;-4980.0
46(28)
0.230;-7520.0
46(2T)
0.213;-7080.0
46(2Q)
0.228;-6640.0
(27)(47)
0.269;-4640.0
4(27T)
0.229;-6860.0
4Q(27)
0.243;-6420.0
(47)(29)
0.237;-5640.0
2J(47)
0.241;-6640.0
47(28)
0.220;-7300.0
47(2T)
0.208;-6860.0
47(2Q)
0.278;-6420.0
(28)(48)
0.334;-4200.0
4(28J)
0.259;-6420.0
4K(28)
0.266;-5980.0
(48)(2J)
0.235;-4980.0
2K(48)
0.224;-5980.0
24(8T)
0.288;-6640.0
24(8Q)
0.278;-6200.0
4(29T)
0.270;-6420.0
4Q(29)
0.231;-5980.0
(49)(2J)
0.224;-4760.0
2K(49)
0.243;-5760.0
24(9J)
0.263;-6200.0
24(9K)
0.292;-5760.0
(2T)(4Q)
0.250;-4320.0
2J(4T)
0.268;-5980.0
4T(2J)
0.226;-5980.0
4T(2K)
0.243;-5540.0
4Q(2J)
0.272;-5540.0
(4J)(2K)
0.307;-3880.0
4J(2K)
0.297;-5320.0
4K(2Q)
0.316;-5100.0
24(QK)
0.238;-5100.0
(25)(56)
0.258;-5080.0
5(259)
0.266;-5860.0
5J(25)
0.266;-5420.0
(2567)
0.217;-7520.0
(256J)
0.221;-6640.0
(25)(67)
0.260;-6080.0
6(25T)
0.220;-6860.0
6Q(25)
0.225;-6420.0
9(257)
0.234;-6860.0
K(257)
0.277;-5980.0
7(25T)
0.210;-6640.0
7Q(25)
0.238;-6200.0
T(258)
0.251;-6420.0
8(259)
0.273;-6640.0
8J(25)
0.211;-6200.0
(259T)
0.230;-6200.0
99(25)
0.228;-4980.0
(25)(9Q)
0.234;-4320.0
(25TQ)
0.327;-5540.0
T(25Q)
0.229;-5540.0
Q(25J)
0.266;-5320.0
(25)(JK)
0.357;-3660.0
QK(25)
0.249;-4880.0
25(57)
0.264;-6300.0
55(2T)
0.260;-5640.0
255Q
0.190;-6640.0
57(26)
0.207;-7520.0
(26)(5T)
0.249;-5420.0
5(26K)
0.234;-6200.0
2(568)
0.217;-7300.0
(56)(2J)
0.292;-5200.0
2K(56)
0.255;-6200.0
25(68)
0.213;-7300.0
25(6T)
0.241;-6860.0
25(6Q)
0.245;-6420.0
5(278)
0.180;-7080.0
5T(27)
0.230;-6640.0
(27)(5K)
0.237;-4540.0
29(57)
0.244;-6860.0
2(57Q)
0.215;-6200.0
25(78)
0.210;-7080.0
25(7T)
0.277;-6640.0
25(7Q)
0.293;-6200.0
5(289)
0.288;-6640.0
5J(28)
0.249;-6200.0
(58)(29)
0.253;-5200.0
2J(58)
0.229;-6200.0
58(29)
0.247;-6640.0
58(2J)
0.271;-6200.0
58(2K)
0.252;-5760.0
5T(29)
0.240;-6200.0
(29)(5K)
0.224;-4100.0
2J(59)
0.244;-5980.0
59(2T)
0.279;-6200.0
59(2Q)
0.233;-5760.0
(2T)(5T)
0.298;-3100.0
5(2TK)
0.255;-5320.0
2(5TQ)
0.242;-5540.0
25(TJ)
0.234;-5760.0
25(TK)
0.272;-5320.0
(2J)(5K)
0.262;-3660.0
2K(5J)
0.295;-5100.0
25(JK)
0.259;-5100.0
(5Q)(2K)
0.292;-3440.0
(2K)(5K)
0.260;-1780.0
6(268)
0.280;-5640.0
6T(26)
0.294;-5200.0
(26)(6K)
0.315;-3100.0
T(267)
0.252;-6420.0
7(268)
0.184;-6860.0
7T(26)
0.208;-6420.0
(26)(7K)
0.284;-4320.0
J(268)
0.282;-5980.0
89(26)
0.263;-6420.0
(26)(8Q)
0.316;-4320.0
(269J)
0.293;-5760.0
(26)(9T)
0.273;-4540.0
9(26K)
0.228;-5320.0
(26TK)
0.261;-5100.0
TQ(26)
0.300;-5320.0
K(26J)
0.240;-4880.0
Q(26Q)
0.330;-3440.0
KK(26)
0.255;-3000.0
66(29)
0.247;-5420.0
266J
0.225;-6420.0
67(27)
0.228;-5640.0
(27)(6T)
0.265;-4980.0
6(27K)
0.264;-5760.0
2(679)
0.254;-6640.0
(67)(2Q)
0.274;-4540.0
27(68)
0.269;-6860.0
27(6T)
0.233;-6420.0
27(6Q)
0.287;-5980.0
68(28)
0.268;-5200.0
(28)(6J)
0.268;-4540.0
28(68)
0.247;-5200.0
2(68J)
0.238;-5980.0
2688
0.251;-6640.0
268T
0.175;-7640.0
268Q
0.224;-7200.0
(29)(6T)
0.231;-4540.0
6(29K)
0.224;-5320.0
2(69J)
0.224;-5760.0
2699
0.227;-6200.0
269J
0.255;-7200.0
269K
0.233;-6760.0
6Q(2T)
0.261;-5320.0
(6T)(2Q)
0.309;-3880.0
2T(6J)
0.220;-5540.0
2T(6K)
0.287;-5100.0
6(2JK)
0.286;-4880.0
2(6JK)
0.279;-4880.0
2J(6K)
0.207;-4880.0
2Q(6Q)
0.357;-3440.0
26QK
0.248;-6100.0
78(27)
0.277;-5200.0
(27)(7J)
0.252;-3100.0
8(278)
0.225;-4980.0
Q(278)
0.313;-5540.0
(27)(8T)
0.319;-4540.0
8(27K)
0.224;-5320.0
(279Q)
0.264;-5320.0
9(27J)
0.237;-5540.0
9K(27)
0.243;-5100.0
TT(27)
0.234;-4100.0
(27)(TK)
0.283;-3440.0
J(27Q)
0.219;-4880.0
K(27Q)
0.281;-4440.0
77(28)
0.208;-5200.0
277T
0.232;-6200.0
27(7K)
0.215;-4100.0
(28)(7T)
0.237;-4540.0
7(28K)
0.282;-5320.0
2(78T)
0.266;-5980.0
(78)(2K)
0.227;-3880.0
78(2T)
0.229;-5980.0
78(2Q)
0.256;-5540.0
(29)(79)
0.345;-3100.0
7(29Q)
0.261;-5320.0
2(79T)
0.269;-5760.0
(79)(2K)
0.284;-3660.0
79(2J)
0.299;-5540.0
79(2K)
0.237;-5100.0
7J(2T)
0.301;-5320.0
(7T)(2J)
0.331;-3880.0
2K(7T)
0.261;-4880.0
27(TQ)
0.270;-5100.0
7(2JQ)
0.299;-4880.0
2(7JQ)
0.270;-4880.0
27(JQ)
0.202;-4880.0
7(2QK)
0.242;-4440.0
7Q(2K)
0.307;-4440.0
88(28)
0.344;-3320.0
(28)(8J)
0.384;-2660.0
9(289)
0.232;-4320.0
K(289)
0.267;-4880.0
9(28Q)
0.258;-5100.0
J(28T)
0.235;-5100.0
TJ(28)
0.258;-5100.0
(28JQ)
0.251;-4660.0
J(28K)
0.330;-4440.0
(28)(QK)
0.252;-2780.0
88(2T)
0.267;-4320.0
288Q
0.248;-5320.0
8T(29)
0.224;-5540.0
(29)(8K)
0.300;-3440.0
2J(89)
0.222;-5320.0
89(2T)
0.232;-5540.0
89(2Q)
0.289;-5100.0
(2T)(8T)
0.314;-2440.0
8(2TK)
0.287;-4660.0
2(8TQ)
0.264;-4880.0
28(TJ)
0.259;-5100.0
28(TK)
0.296;-4660.0
(2J)(8K)
0.362;-3000.0
2K(8J)
0.306;-4440.0
28(JK)
0.343;-4440.0
(8Q)(2K)
0.279;-2780.0
(2K)(8K)
0.349;-1120.0
9(29J)
0.266;-3660.0
9K(29)
0.335;-3220.0
TT(29)
0.332;-3660.0
(29)(TK)
0.268;-3000.0
J(29Q)
0.279;-4440.0
K(29Q)
0.270;-4000.0
99(2T)
0.310;-3880.0
299Q
0.219;-4880.0
9J(2T)
0.326;-4880.0
(9T)(2J)
0.267;-3440.0
2K(9T)
0.272;-4440.0
29(TQ)
0.339;-4660.0
9(2JQ)
0.236;-4440.0
2(9JQ)
0.305;-4440.0
29(JQ)
0.253;-4440.0
9(2QK)
0.254;-4000.0
9Q(2K)
0.287;-4000.0
TT(2T)
0.347;-2000.0
(2T)(TK)
0.309;-1340.0
J(2TQ)
0.226;-4220.0
K(2TQ)
0.304;-3780.0
TT(2J)
0.239;-3220.0
2TTK
0.289;-4220.0
TK(2J)
0.269;-4000.0
2TJJ
0.288;-4440.0
2TJK
0.277;-5440.0
2(TQK)
0.354;-3780.0
TK(2K)
0.281;-2120.0
(2J)(JK)
0.337;-900.0
QK(2J)
0.281;-3560.0
2J(JK)
0.308;-2340.0
(JQ)(2K)
0.315;-2120.0
(2K)(JK)
0.358;-460.0
K(2QK)
0.303;-1680.0
2K(QK)
0.319;-1680.0
3335
0.209;-7400.0
3339
0.278;-6520.0
333K
0.261;-5640.0
36(34)
0.291;-6960.0
(34)(39)
0.274;-4860.0
3(34Q)
0.227;-5640.0
33(45)
0.263;-7180.0
34(38)
0.240;-6520.0
334T
0.195;-7520.0
33(4K)
0.234;-5420.0
(35)(37)
0.242;-5080.0
3(35T)
0.255;-5860.0
3Q(35)
0.283;-5420.0
35(37)
0.222;-6520.0
3359
0.202;-7520.0
33(5Q)
0.235;-5420.0
(36)(37)
0.283;-4860.0
3(36T)
0.313;-5640.0
3Q(36)
0.212;-5200.0
36(38)
0.257;-6080.0
336T
0.235;-7080.0
33(6K)
0.310;-4980.0
(37)(39)
0.293;-4200.0
3(37Q)
0.321;-4980.0
33(78)
0.221;-5860.0
37(3J)
0.255;-5200.0
337K
0.275;-6200.0
3T(38)
0.209;-5200.0
(38)(3K)
0.276;-3100.0
338T
0.241;-6640.0
33(8K)
0.261;-4540.0
(39)(3J)
0.285;-3320.0
3399
0.233;-5200.0
33(9Q)
0.288;-4540.0
(3T)(3J)
0.268;-3100.0
33TT
0.251;-4760.0
33(TK)
0.290;-4100.0
(3J)(3K)
0.285;-2440.0
33JK
0.214;-5320.0
33(QK)
0.257;-3660.0
45(34)
0.259;-6960.0
(34)(48)
0.218;-4860.0
4(34J)
0.209;-5640.0
4K(34)
0.242;-5200.0
(3459)
0.198;-7300.0
(345K)
0.211;-6420.0
57(34)
0.252;-7740.0
(34)(5T)
0.243;-5640.0
5(34K)
0.189;-6420.0
(3469)
0.243;-7080.0
(346K)
0.211;-6200.0
68(34)
0.192;-7300.0
(34)(6J)
0.248;-5200.0
7(347)
0.287;-5860.0
J(347)
0.302;-6420.0
78(34)
0.253;-7080.0
(34)(7J)
0.284;-4980.0
8(348)
0.243;-5420.0
Q(348)
0.216;-5980.0
(34)(8T)
0.270;-4980.0
8(34K)
0.206;-5760.0
(349Q)
0.292;-5760.0
9(34J)
0.260;-5980.0
9K(34)
0.242;-5540.0
TT(34)
0.259;-4540.0
(34)(TK)
0.321;-3880.0
J(34Q)
0.266;-5320.0
K(34Q)
0.268;-4880.0
44(35)
0.226;-6960.0
3447
0.222;-7960.0
34(4T)
0.254;-5860.0
44(3K)
0.250;-5200.0
4(357)
0.189;-7740.0
49(35)
0.229;-7300.0
(35)(4Q)
0.224;-5200.0
36(45)
0.193;-7960.0
3(459)
0.236;-7300.0
(45)(3Q)
0.298;-5200.0
35(46)
0.199;-7960.0
35(48)
0.228;-7520.0
35(4T)
0.236;-7080.0
35(4Q)
0.213;-6640.0
46(36)
0.252;-6300.0
(36)(49)
0.243;-5640.0
4(36Q)
0.255;-6420.0
3(467)
0.217;-7520.0
(46)(3T)
0.284;-5420.0
3Q(46)
0.206;-6420.0
3467
0.210;-8960.0
3469
0.213;-8520.0
346J
0.193;-8080.0
346K
0.189;-7640.0
49(37)
0.205;-6860.0
(37)(4Q)
0.271;-4760.0
38(47)
0.200;-7080.0
3(47J)
0.235;-6420.0
3477
0.248;-7300.0
3479
0.245;-8300.0
347J
0.207;-7860.0
347K
0.260;-7420.0
4T(38)
0.205;-6420.0
(38)(4K)
0.268;-4320.0
3T(48)
0.268;-6420.0
3(48K)
0.262;-5760.0
38(4T)
0.235;-6420.0
38(4Q)
0.205;-5980.0
49(39)
0.288;-4980.0
(39)(4Q)
0.315;-4320.0
3T(49)
0.280;-6200.0
3(49K)
0.207;-5540.0
39(4J)
0.244;-5980.0
39(4K)
0.271;-5540.0
4(3TQ)
0.321;-5540.0
3(4TJ)
0.240;-5760.0
34TT
0.270;-5980.0
34TQ
0.178;-6980.0
(3J)(4Q)
0.314;-3880.0
3Q(4J)
0.231;-5320.0
34JQ
0.275;-6760.0
(3Q)(4K)
0.356;-3440.0
3Q(4K)
0.262;-4880.0
5(356)
0.229;-6300.0
58(35)
0.236;-5860.0
(35)(5J)
0.293;-3760.0
6(356)
0.225;-6080.0
T(356)
0.204;-6640.0
6(357)
0.169;-7300.0
69(35)
0.230;-6860.0
(35)(6Q)
0.231;-4760.0
(3579)
0.224;-6640.0
(357K)
0.256;-5760.0
79(35)
0.273;-6640.0
(35)(7Q)
0.230;-4540.0
(358T)
0.262;-6200.0
88(35)
0.239;-5200.0
(35)(8J)
0.288;-4540.0
9(359)
0.280;-4760.0
K(359)
0.316;-5320.0
9(35Q)
0.219;-5540.0
J(35T)
0.222;-5540.0
TJ(35)
0.266;-5540.0
(35JQ)
0.311;-5100.0
J(35K)
0.244;-4880.0
(35)(QK)
0.269;-3220.0
55(37)
0.252;-6080.0
3559
0.206;-7080.0
35(5Q)
0.294;-4980.0
(36)(57)
0.240;-5860.0
5(36T)
0.201;-6640.0
5Q(36)
0.239;-6200.0
(56)(38)
0.216;-5640.0
3T(56)
0.269;-6640.0
3(56K)
0.254;-5980.0
36(58)
0.266;-7080.0
36(5T)
0.276;-6640.0
36(5Q)
0.227;-6200.0
57(37)
0.272;-5640.0
(37)(5T)
0.264;-4980.0
5(37K)
0.299;-5760.0
3(579)
0.198;-6640.0
(57)(3Q)
0.303;-4540.0
37(58)
0.222;-6860.0
37(5T)
0.258;-6420.0
37(5Q)
0.247;-5980.0
58(38)
0.212;-5200.0
(38)(5J)
0.203;-4540.0
38(58)
0.244;-5200.0
3(58J)
0.283;-5980.0
3588
0.272;-6640.0
358T
0.232;-7640.0
358Q
0.256;-7200.0
(39)(5T)
0.268;-4540.0
5(39K)
0.273;-5320.0
3(59J)
0.262;-5760.0
3599
0.267;-6200.0
359J
0.217;-7200.0
359K
0.248;-6760.0
5Q(3T)
0.308;-5320.0
(5T)(3Q)
0.268;-3880.0
3T(5J)
0.234;-5540.0
3T(5K)
0.258;-5100.0
5(3JK)
0.221;-4880.0
3(5JK)
0.254;-4880.0
3J(5K)
0.211;-4880.0
3Q(5Q)
0.306;-3440.0
35QK
0.234;-6100.0
67(36)
0.316;-5640.0
(36)(6T)
0.215;-3540.0
6(36K)
0.286;-4320.0
(367T)
0.213;-6200.0
77(36)
0.228;-5420.0
(36)(7T)
0.293;-4760.0
7(36K)
0.236;-5540.0
(368J)
0.251;-5760.0
(36)(89)
0.261;-4760.0
8(36Q)
0.215;-5540.0
T(369)
0.284;-5760.0
9(36T)
0.259;-5760.0
9Q(36)
0.238;-5320.0
Q(36T)
0.302;-5100.0
(36)(TQ)
0.264;-3660.0
(36JK)
0.289;-4660.0
JK(36)
0.297;-4660.0
K(36K)
0.330;-2780.0
3668
0.245;-6860.0
36(6J)
0.274;-4760.0
(37)(67)
0.301;-3980.0
6(37T)
0.284;-6200.0
6Q(37)
0.289;-5760.0
(67)(39)
0.255;-4980.0
3J(67)
0.269;-5980.0
67(38)
0.237;-6640.0
67(3T)
0.191;-6200.0
67(3Q)
0.219;-5760.0
(38)(68)
0.271;-3540.0
6(38J)
0.231;-5760.0
6K(38)
0.305;-5320.0
(68)(3J)
0.276;-4320.0
3K(68)
0.294;-5320.0
36(8T)
0.230;-5980.0
36(8Q)
0.201;-5540.0
6(39T)
0.284;-5760.0
6Q(39)
0.273;-5320.0
(69)(3J)
0.246;-4100.0
3K(69)
0.237;-5100.0
36(9J)
0.304;-5540.0
36(9K)
0.246;-5100.0
(3T)(6Q)
0.256;-3660.0
3J(6T)
0.250;-5320.0
6T(3J)
0.249;-5320.0
6T(3K)
0.284;-4880.0
6Q(3J)
0.273;-4880.0
(6J)(3K)
0.292;-3220.0
6J(3K)
0.298;-4660.0
6K(3Q)
0.216;-4440.0
36(QK)
0.257;-4440.0
(37)(78)
0.297;-3540.0
7(37J)
0.326;-4320.0
7K(37)
0.236;-3880.0
(378Q)
0.306;-5320.0
8(37T)
0.185;-5760.0
8Q(37)
0.259;-5320.0
J(379)
0.243;-5320.0
9T(37)
0.232;-5540.0
(37)(9K)
0.291;-3440.0
K(37T)
0.275;-4660.0
T(37K)
0.261;-4660.0
JJ(37)
0.296;-3440.0
(37QK)
0.232;-4220.0
3777
0.272;-5200.0
37(7T)
0.303;-4540.0
77(3K)
0.307;-3880.0
7(38T)
0.244;-5760.0
7Q(38)
0.312;-5320.0
(78)(3T)
0.328;-4320.0
3Q(78)
0.284;-5320.0
3789
0.218;-7420.0
378J
0.222;-6980.0
378K
0.255;-6540.0
7J(39)
0.217;-5320.0
(79)(3T)
0.211;-4100.0
3Q(79)
0.278;-5100.0
379T
0.217;-6980.0
379Q
0.220;-6540.0
(3T)(7J)
0.280;-3660.0
3T(7T)
0.310;-3880.0
3(7TK)
0.247;-4660.0
3T(7Q)
0.270;-4880.0
7J(3J)
0.273;-3440.0
(7J)(3Q)
0.270;-3220.0
3J(7Q)
0.252;-4660.0
7Q(3Q)
0.292;-3000.0
37QQ
0.222;-4440.0
37KK
0.283;-4000.0
8(38J)
0.332;-3880.0
8K(38)
0.301;-3440.0
(389K)
0.301;-4660.0
9J(38)
0.315;-5100.0
(38TJ)
0.272;-4880.0
(38)(TJ)
0.303;-3440.0
J(38J)
0.302;-3220.0
JQ(38)
0.253;-4440.0
Q(38K)
0.300;-4000.0
3889
0.230;-5760.0
38(8Q)
0.282;-3660.0
(39)(8T)
0.332;-3880.0
8(39K)
0.269;-4660.0
3(89J)
0.235;-5100.0
3899
0.220;-5540.0
389J
0.282;-6540.0
389K
0.278;-6100.0
8Q(3T)
0.231;-4660.0
(8T)(3Q)
0.305;-3220.0
3T(8J)
0.235;-4880.0
3T(8K)
0.301;-4440.0
8(3JK)
0.291;-4220.0
3(8JK)
0.269;-4220.0
3J(8K)
0.296;-4220.0
3Q(8Q)
0.277;-2780.0
38QK
0.222;-5440.0
9T(39)
0.293;-3660.0
(39)(9K)
0.325;-1560.0
K(39T)
0.262;-4220.0
T(39K)
0.282;-4220.0
JJ(39)
0.280;-3000.0
(39QK)
0.302;-3780.0
3999
0.317;-3880.0
39(9Q)
0.290;-3220.0
(3T)(9J)
0.246;-3220.0
3T(9T)
0.306;-3440.0
3(9TK)
0.306;-4220.0
3T(9Q)
0.249;-4440.0
9J(3J)
0.306;-3000.0
(9J)(3Q)
0.257;-2780.0
3J(9Q)
0.268;-4220.0
9Q(3Q)
0.269;-2560.0
39QQ
0.277;-4000.0
39KK
0.282;-3560.0
T(3TK)
0.295;-2560.0
JJ(3T)
0.288;-2780.0
(3TQK)
0.305;-3560.0
3TTT
0.341;-3220.0
3T(TK)
0.317;-2560.0
(3J)(TK)
0.290;-2340.0
3K(TJ)
0.285;-3780.0
3T(JK)
0.288;-3780.0
(TQ)(3K)
0.334;-2120.0
(3K)(TK)
0.367;-460.0
J(3JK)
0.324;-2120.0
(3J)(QK)
0.306;-1900.0
JJ(3K)
0.320;-2120.0
3Q(JQ)
0.320;-2120.0
3JQK
0.310;-4780.0
QK(3Q)
0.297;-1680.0
QK(3K)
0.287;-1460.0
44(46)
0.267;-5080.0
44(4T)
0.223;-4200.0
(45)(45)
0.240;-3640.0
4(458)
0.244;-5860.0
4T(45)
0.258;-5420.0
(45)(4K)
0.280;-3320.0
4457
0.190;-7520.0
44(5T)
0.266;-5420.0
45(4K)
0.298;-4760.0
4(468)
0.199;-5640.0
4T(46)
0.285;-5200.0
(46)(4K)
0.305;-3100.0
4468
0.219;-7080.0
44(6J)
0.314;-4980.0
(47)(47)
0.298;-2760.0
4(47T)
0.274;-4980.0
4Q(47)
0.272;-4540.0
47(49)
0.255;-5200.0
447J
0.231;-6200.0
48(48)
0.345;-3760.0
(48)(4J)
0.289;-3100.0
4488
0.302;-5200.0
44(8J)
0.328;-4540.0
(49)(49)
0.297;-1880.0
4(49Q)
0.256;-4100.0
44(9T)
0.274;-4540.0
49(4K)
0.229;-3880.0
4(4TQ)
0.300;-3880.0
44(TJ)
0.252;-4100.0
(4J)(4J)
0.309;-1000.0
44JJ
0.274;-3880.0
4Q(4Q)
0.298;-2000.0
(4K)(4K)
0.326;-120.0
(45)(57)
0.279;-4420.0
5(45T)
0.271;-5200.0
5Q(45)
0.264;-4760.0
8(456)
0.272;-6860.0
Q(456)
0.216;-5980.0
(45)(68)
0.194;-5420.0
6(45J)
0.218;-6200.0
6K(45)
0.219;-5760.0
(457J)
0.309;-5980.0
(45)(78)
0.277;-5200.0
7(45J)
0.275;-5980.0
7K(45)
0.263;-5540.0
(458Q)
0.280;-5540.0
8(45T)
0.232;-5980.0
8Q(45)
0.300;-5540.0
J(459)
0.293;-5540.0
9T(45)
0.278;-5760.0
(45)(9K)
0.285;-3660.0
K(45T)
0.248;-4880.0
T(45K)
0.229;-4880.0
JJ(45)
0.275;-3660.0
(45QK)
0.291;-4440.0
4555
0.220;-6300.0
45(58)
0.199;-5640.0
55(4J)
0.258;-4980.0
455K
0.237;-5980.0
58(46)
0.263;-6860.0
(46)(5J)
0.323;-4760.0
46(56)
0.277;-5860.0
4(569)
0.201;-6640.0
(56)(4Q)
0.283;-4540.0
46(57)
0.299;-7080.0
46(59)
0.188;-6640.0
46(5J)
0.279;-6200.0
46(5K)
0.282;-5760.0
5(479)
0.244;-6420.0
5J(47)
0.201;-5980.0
(57)(48)
0.265;-5200.0
4T(57)
0.210;-6200.0
4(57K)
0.239;-5540.0
47(59)
0.225;-6420.0
47(5J)
0.269;-5980.0
47(5K)
0.268;-5540.0
5(48T)
0.264;-5980.0
5Q(48)
0.305;-5540.0
(58)(4T)
0.277;-4540.0
4Q(58)
0.294;-5540.0
4589
0.224;-7640.0
458J
0.177;-7200.0
458K
0.266;-6760.0
5J(49)
0.216;-5540.0
(59)(4T)
0.290;-4320.0
4Q(59)
0.300;-5320.0
459T
0.220;-7200.0
459Q
0.242;-6760.0
(4T)(5J)
0.344;-3880.0
4T(5T)
0.310;-4100.0
4(5TK)
0.292;-4880.0
4T(5Q)
0.301;-5100.0
5J(4J)
0.255;-3660.0
(5J)(4Q)
0.244;-3440.0
4J(5Q)
0.302;-4880.0
5Q(4Q)
0.299;-3220.0
45QQ
0.252;-4660.0
45KK
0.304;-4220.0
6(469)
0.230;-4980.0
6J(46)
0.243;-4540.0
(4678)
0.256;-6420.0
(467Q)
0.212;-5540.0
7(469)
0.224;-6200.0
7J(46)
0.215;-5760.0
(4689)
0.219;-5980.0
(468K)
0.270;-5100.0
8T(46)
0.281;-5760.0
(46)(8K)
0.272;-3660.0
Q(469)
0.234;-5100.0
(46)(9J)
0.248;-3880.0
T(46T)
0.306;-3880.0
T(46J)
0.260;-5100.0
TK(46)
0.304;-4660.0
(46)(JQ)
0.305;-3220.0
QQ(46)
0.276;-3000.0
46(67)
0.231;-5420.0
66(4T)
0.260;-4760.0
466Q
0.258;-5760.0
68(47)
0.251;-6420.0
(47)(6J)
0.237;-4320.0
47(67)
0.275;-5200.0
4(67T)
0.220;-5980.0
(67)(4K)
0.266;-3880.0
67(49)
0.234;-6200.0
67(4J)
0.294;-5760.0
67(4K)
0.259;-5320.0
69(48)
0.216;-5980.0
(48)(6Q)
0.256;-3880.0
49(68)
0.283;-5980.0
4(68Q)
0.267;-5320.0
46(89)
0.218;-5980.0
46(8J)
0.260;-5540.0
46(8K)
0.307;-5100.0
(49)(6J)
0.274;-3880.0
49(69)
0.339;-4320.0
4(69Q)
0.301;-5100.0
46(9T)
0.298;-5540.0
46(9Q)
0.236;-5100.0
6(4TJ)
0.225;-5100.0
6K(4T)
0.274;-4660.0
(6T)(4K)
0.268;-3220.0
6T(4Q)
0.311;-4880.0
(4J)(6J)
0.322;-2000.0
4J(6J)
0.240;-3440.0
6J(4Q)
0.325;-4660.0
(4Q)(6Q)
0.295;-1560.0
4K(6Q)
0.344;-4220.0
4K(6K)
0.250;-2560.0
79(47)
0.222;-4540.0
(47)(7Q)
0.300;-2440.0
(478T)
0.218;-5540.0
88(47)
0.309;-4540.0
(47)(8J)
0.244;-3880.0
9(479)
0.304;-4100.0
K(479)
0.326;-4660.0
9(47Q)
0.260;-4880.0
J(47T)
0.244;-4880.0
TJ(47)
0.224;-4880.0
(47JQ)
0.286;-4440.0
J(47K)
0.268;-4220.0
(47)(QK)
0.339;-2560.0
77(49)
0.233;-4540.0
477J
0.291;-5540.0
78(48)
0.241;-4540.0
(48)(7J)
0.328;-3880.0
48(78)
0.302;-4540.0
4(78J)
0.297;-5320.0
4788
0.190;-5980.0
478T
0.274;-6980.0
478Q
0.211;-6540.0
(49)(7T)
0.276;-3880.0
7(49K)
0.232;-4660.0
4(79J)
0.263;-5100.0
4799
0.313;-5540.0
479J
0.223;-6540.0
479K
0.245;-6100.0
7Q(4T)
0.267;-4660.0
(7T)(4Q)
0.293;-3220.0
4T(7J)
0.226;-4880.0
4T(7K)
0.228;-4440.0
7(4JK)
0.238;-4220.0
4(7JK)
0.281;-4220.0
4J(7K)
0.262;-4220.0
4Q(7Q)
0.324;-2780.0
47QK
0.305;-5440.0
89(48)
0.267;-4100.0
(48)(8Q)
0.309;-2000.0
(489J)
0.321;-4880.0
(48)(9T)
0.281;-3660.0
9(48K)
0.307;-4440.0
(48TK)
0.277;-4220.0
TQ(48)
0.304;-4440.0
K(48J)
0.310;-4000.0
Q(48Q)
0.317;-2560.0
KK(48)
0.291;-2120.0
88(4J)
0.229;-3660.0
488K
0.280;-4660.0
8J(49)
0.299;-4880.0
(89)(4T)
0.344;-3660.0
4Q(89)
0.260;-4660.0
489T
0.277;-6540.0
489Q
0.315;-6100.0
(4T)(8J)
0.304;-3220.0
4T(8T)
0.283;-3440.0
4(8TK)
0.275;-4220.0
4T(8Q)
0.283;-4440.0
8J(4J)
0.307;-3000.0
(8J)(4Q)
0.290;-2780.0
4J(8Q)
0.274;-4220.0
8Q(4Q)
0.281;-2560.0
48QQ
0.260;-4000.0
48KK
0.249;-3560.0
9(49Q)
0.329;-3000.0
J(49T)
0.235;-4440.0
TJ(49)
0.236;-4440.0
(49JQ)
0.283;-4000.0
J(49K)
0.315;-3780.0
(49)(QK)
0.316;-2120.0
99(4J)
0.258;-3220.0
499K
0.295;-4220.0
9Q(4T)
0.274;-4220.0
(9T)(4Q)
0.289;-2780.0
4T(9J)
0.225;-4440.0
4T(9K)
0.349;-4000.0
9(4JK)
0.262;-3780.0
4(9JK)
0.276;-3780.0
4J(9K)
0.322;-3780.0
4Q(9Q)
0.256;-2340.0
49QK
0.271;-5000.0
TJ(4T)
0.346;-2780.0
(4TJQ)
0.311;-3780.0
J(4TK)
0.308;-3560.0
(4T)(QK)
0.355;-1900.0
TT(4Q)
0.287;-2560.0
T(4JQ)
0.247;-3780.0
4(TJQ)
0.304;-3780.0
4T(JQ)
0.277;-3780.0
T(4QK)
0.263;-3340.0
TQ(4K)
0.290;-3340.0
JJ(4J)
0.312;-900.0
(4JQK)
0.331;-3120.0
4JJJ
0.267;-2340.0
JQ(4Q)
0.345;-1900.0
4JQQ
0.238;-3340.0
4JKK
0.264;-2900.0
QQ(4K)
0.311;-1460.0
4KKK
0.309;-1020.0
55(59)
0.304;-3760.0
55(5K)
0.298;-2880.0
(56)(58)
0.358;-3760.0
5(56J)
0.282;-4540.0
5K(56)
0.263;-4100.0
56(59)
0.236;-4980.0
556J
0.235;-5980.0
57(57)
0.222;-3760.0
(57)(5T)
0.285;-3100.0
5(57K)
0.311;-3880.0
55(79)
0.311;-4760.0
57(5Q)
0.270;-4100.0
5(589)
0.254;-4540.0
5J(58)
0.264;-4100.0
58(59)
0.291;-4540.0
558J
0.282;-5540.0
59(59)
0.286;-2880.0
(59)(5Q)
0.308;-2220.0
559T
0.282;-5540.0
55(9K)
0.285;-3440.0
(5T)(5Q)
0.375;-2000.0
55TJ
0.235;-5100.0
5J(5J)
0.282;-2000.0
5J(5Q)
0.345;-3220.0
5(5QK)
0.267;-2780.0
5K(5K)
0.351;-1120.0
68(56)
0.243;-4980.0
(56)(6J)
0.314;-2880.0
7(567)
0.305;-4980.0
J(567)
0.213;-5540.0
78(56)
0.308;-6200.0
(56)(7J)
0.301;-4100.0
8(568)
0.275;-4540.0
Q(568)
0.261;-5100.0
(56)(8T)
0.289;-4100.0
8(56K)
0.201;-4880.0
(569Q)
0.260;-4880.0
9(56J)
0.270;-5100.0
9K(56)
0.333;-4660.0
TT(56)
0.262;-3660.0
(56)(TK)
0.261;-3000.0
J(56Q)
0.274;-4440.0
K(56Q)
0.303;-4000.0
66(57)
0.286;-5200.0
5669
0.253;-6200.0
56(6Q)
0.272;-4100.0
(57)(68)
0.242;-4760.0
6(57J)
0.241;-5540.0
6K(57)
0.281;-5100.0
(67)(5T)
0.281;-4320.0
5Q(67)
0.248;-5320.0
5678
0.261;-7640.0
567T
0.238;-7200.0
567Q
0.222;-6760.0
(58)(69)
0.287;-4320.0
6(58Q)
0.230;-5100.0
5(689)
0.253;-5760.0
(68)(5Q)
0.276;-3660.0
58(69)
0.199;-5760.0
58(6J)
0.225;-5320.0
58(6K)
0.266;-4880.0
6(59J)
0.280;-5100.0
6K(59)
0.270;-4660.0
(69)(5Q)
0.351;-3440.0
59(6T)
0.269;-5320.0
59(6Q)
0.313;-4880.0
6T(5T)
0.262;-3660.0
(5T)(6K)
0.319;-3000.0
5Q(6T)
0.264;-4660.0
56TJ
0.260;-6320.0
56TK
0.262;-5880.0
6K(5J)
0.256;-4220.0
56JJ
0.320;-4660.0
56JK
0.269;-5660.0
5(6QK)
0.302;-4000.0
6K(5K)
0.315;-2340.0
(57)(79)
0.225;-2880.0
7(57Q)
0.241;-3660.0
9(578)
0.254;-5540.0
K(578)
0.295;-4660.0
8(57J)
0.266;-5100.0
8K(57)
0.277;-4660.0
(579K)
0.263;-4440.0
9J(57)
0.318;-4880.0
(57TJ)
0.265;-4660.0
(57)(TJ)
0.309;-3220.0
J(57J)
0.336;-3000.0
JQ(57)
0.275;-4220.0
Q(57K)
0.226;-3780.0
5778
0.224;-5980.0
57(7J)
0.256;-3880.0
(58)(78)
0.298;-2880.0
7(58J)
0.227;-5100.0
7K(58)
0.293;-4660.0
(78)(5J)
0.296;-3660.0
5K(78)
0.295;-4660.0
57(8T)
0.252;-5320.0
57(8Q)
0.277;-4880.0
7(59T)
0.248;-5100.0
7Q(59)
0.240;-4660.0
(79)(5J)
0.348;-3440.0
5K(79)
0.289;-4440.0
57(9J)
0.301;-4880.0
57(9K)
0.257;-4440.0
(5T)(7Q)
0.283;-3000.0
5J(7T)
0.255;-4660.0
7T(5J)
0.261;-4660.0
7T(5K)
0.222;-4220.0
7Q(5J)
0.255;-4220.0
(7J)(5K)
0.300;-2560.0
7J(5K)
0.296;-4000.0
7K(5Q)
0.242;-3780.0
57(QK)
0.224;-3780.0
(58)(89)
0.276;-2440.0
8(58Q)
0.319;-3220.0
T(589)
0.258;-4880.0
9(58T)
0.253;-4880.0
9Q(58)
0.287;-4440.0
Q(58T)
0.288;-4220.0
(58)(TQ)
0.264;-2780.0
(58JK)
0.307;-3780.0
JK(58)
0.236;-3780.0
K(58K)
0.256;-1900.0
588T
0.239;-5100.0
58(8K)
0.274;-3000.0
(59)(8J)
0.277;-3220.0
59(89)
0.280;-3660.0
5(89Q)
0.261;-4440.0
58(9T)
0.293;-4880.0
58(9Q)
0.308;-4440.0
8(5TJ)
0.239;-4440.0
8K(5T)
0.290;-4000.0
(8T)(5K)
0.242;-2560.0
8T(5Q)
0.272;-4220.0
(5J)(8J)
0.320;-1340.0
5J(8J)
0.317;-2780.0
8J(5Q)
0.232;-4000.0
(5Q)(8Q)
0.331;-900.0
5K(8Q)
0.289;-3560.0
5K(8K)
0.274;-1900.0
9J(59)
0.296;-3000.0
(59TJ)
0.306;-4220.0
(59)(TJ)
0.308;-2780.0
J(59J)
0.267;-2560.0
JQ(59)
0.317;-3780.0
Q(59K)
0.289;-3340.0
599T
0.219;-4660.0
59(9K)
0.259;-2560.0
(5T)(9Q)
0.291;-2560.0
5J(9T)
0.209;-4220.0
9T(5J)
0.276;-4220.0
9T(5K)
0.252;-3780.0
9Q(5J)
0.264;-3780.0
(9J)(5K)
0.301;-2120.0
9J(5K)
0.287;-3560.0
9K(5Q)
0.278;-3340.0
59(QK)
0.299;-3340.0
(5T)(TJ)
0.303;-1120.0
J(5TJ)
0.361;-2340.0
JQ(5T)
0.294;-3560.0
Q(5TK)
0.239;-3120.0
5TTJ
0.280;-4000.0
TJ(5J)
0.319;-2340.0
(TJ)(5Q)
0.291;-2120.0
5J(TQ)
0.298;-3560.0
TQ(5Q)
0.309;-1900.0
5TQQ
0.327;-3340.0
5TKK
0.300;-2900.0
Q(5JQ)
0.329;-1680.0
KK(5J)
0.308;-1240.0
(5Q)(JQ)
0.313;-240.0
5K(JQ)
0.296;-2900.0
5K(JK)
0.287;-1240.0
5QQQ
0.352;-1460.0
KK(5K)
0.359;640.0
6669
0.280;-4540.0
666K
0.271;-3660.0
69(67)
0.309;-4320.0
(67)(6Q)
0.374;-2220.0
6678
0.270;-5980.0
66(7J)
0.303;-3880.0
(68)(68)
0.374;-1440.0
6(68J)
0.254;-3660.0
6K(68)
0.307;-3220.0
68(6J)
0.278;-3660.0
668K
0.289;-4660.0
6J(69)
0.297;-3440.0
69(6T)
0.275;-3660.0
669Q
0.248;-4660.0
6J(6T)
0.348;-3220.0
6T(6J)
0.356;-3220.0
66TK
0.248;-4220.0
6K(6J)
0.312;-2560.0
(6Q)(6Q)
0.339;320.0
66QK
0.308;-3780.0
7(679)
0.280;-4100.0
7J(67)
0.332;-3660.0
(6789)
0.243;-5320.0
(678K)
0.255;-4440.0
8T(67)
0.238;-5100.0
(67)(8K)
0.288;-3000.0
Q(679)
0.230;-4440.0
(67)(9J)
0.322;-3220.0
T(67T)
0.309;-3220.0
T(67J)
0.296;-4440.0
TK(67)
0.327;-4000.0
(67)(JQ)
0.294;-2560.0
QQ(67)
0.374;-2340.0
67(78)
0.345;-4320.0
77(6J)
0.235;-3660.0
677K
0.330;-4660.0
7T(68)
0.196;-5100.0
(68)(7K)
0.355;-3000.0
6T(78)
0.234;-5100.0
6(78K)
0.282;-4440.0
68(7T)
0.238;-5100.0
68(7Q)
0.270;-4660.0
79(69)
0.284;-3660.0
(69)(7Q)
0.297;-3000.0
6T(79)
0.205;-4880.0
6(79K)
0.282;-4220.0
69(7J)
0.330;-4660.0
69(7K)
0.291;-4220.0
7(6TQ)
0.255;-4220.0
6(7TJ)
0.330;-4440.0
67TT
0.285;-4660.0
67TQ
0.291;-5660.0
(6J)(7Q)
0.301;-2560.0
6Q(7J)
0.280;-4000.0
67JQ
0.317;-5440.0
(6Q)(7K)
0.319;-2120.0
6Q(7K)
0.279;-3560.0
8(689)
0.268;-3660.0
8J(68)
0.307;-3220.0
(689T)
0.265;-4660.0
99(68)
0.237;-3440.0
(68)(9Q)
0.281;-2780.0
(68TQ)
0.231;-4000.0
T(68Q)
0.275;-4000.0
Q(68J)
0.299;-3780.0
(68)(JK)
0.285;-2120.0
QK(68)
0.360;-3340.0
68(8T)
0.227;-3440.0
88(6K)
0.290;-2780.0
8(69J)
0.314;-4440.0
8K(69)
0.329;-4000.0
(89)(6Q)
0.342;-2780.0
69(8T)
0.224;-4660.0
69(8Q)
0.217;-4220.0
8T(6T)
0.327;-3000.0
(6T)(8K)
0.336;-2340.0
6Q(8T)
0.326;-4000.0
68TJ
0.289;-5660.0
68TK
0.235;-5220.0
8K(6J)
0.259;-3560.0
68JJ
0.331;-4000.0
68JK
0.277;-5000.0
6(8QK)
0.295;-3340.0
8K(6K)
0.327;-1680.0
(69)(9J)
0.330;-1340.0
T(69T)
0.292;-2780.0
T(69J)
0.332;-4000.0
TK(69)
0.247;-3560.0
(69)(JQ)
0.302;-2120.0
QQ(69)
0.297;-1900.0
69(9T)
0.307;-3000.0
99(6K)
0.293;-2340.0
9(6TQ)
0.240;-3780.0
6(9TJ)
0.279;-4000.0
69TT
0.247;-4220.0
69TQ
0.224;-5220.0
(6J)(9Q)
0.291;-2120.0
6Q(9J)
0.337;-3560.0
69JQ
0.222;-5000.0
(6Q)(9K)
0.262;-1680.0
6Q(9K)
0.349;-3120.0
T(6TJ)
0.255;-2340.0
TK(6T)
0.298;-1900.0
(6T)(JQ)
0.309;-1900.0
QQ(6T)
0.266;-1680.0
6T(TJ)
0.378;-2340.0
(6J)(TJ)
0.395;-680.0
6J(TJ)
0.300;-2120.0
TJ(6Q)
0.269;-3340.0
(6Q)(TQ)
0.325;-240.0
6K(TQ)
0.271;-2900.0
6K(TK)
0.328;-1240.0
JK(6J)
0.368;-1460.0
K(6JK)
0.329;-1020.0
6JJK
0.279;-2900.0
6(JQK)
0.315;-2680.0
JK(6K)
0.373;-1020.0
KK(6Q)
0.280;-800.0
6QKK
0.332;-2240.0
77(7T)
0.307;-2220.0
(78)(78)
0.315;-1000.0
7(78J)
0.346;-3220.0
7K(78)
0.311;-2780.0
78(7J)
0.274;-3220.0
778K
0.282;-4220.0
7J(79)
0.268;-3000.0
79(7T)
0.317;-3220.0
779Q
0.235;-4220.0
7J(7T)
0.313;-2780.0
7T(7J)
0.340;-2780.0
77TK
0.251;-3780.0
7K(7J)
0.318;-2120.0
(7Q)(7Q)
0.381;760.0
77QK
0.279;-3340.0
8(78T)
0.301;-3220.0
8Q(78)
0.317;-2780.0
J(789)
0.250;-4220.0
9T(78)
0.260;-4440.0
(78)(9K)
0.349;-2340.0
K(78T)
0.342;-3560.0
T(78K)
0.321;-3560.0
JJ(78)
0.354;-2340.0
(78QK)
0.287;-3120.0
7888
0.327;-3660.0
78(8J)
0.263;-3000.0
(79)(89)
0.311;-1780.0
8(79Q)
0.288;-4000.0
7(89T)
0.307;-4440.0
(89)(7K)
0.332;-2340.0
89(7J)
0.210;-4220.0
89(7K)
0.239;-3780.0
8J(7T)
0.271;-4000.0
(8T)(7J)
0.267;-2560.0
7K(8T)
0.271;-3560.0
78(TQ)
0.356;-3780.0
8(7JQ)
0.344;-3560.0
7(8JQ)
0.249;-3560.0
78(JQ)
0.274;-3560.0
8(7QK)
0.294;-3120.0
8Q(7K)
0.286;-3120.0
99(79)
0.339;-1560.0
(79)(9Q)
0.261;-900.0
(79TQ)
0.312;-3560.0
T(79Q)
0.312;-3560.0
Q(79J)
0.335;-3340.0
(79)(JK)
0.282;-1680.0
QK(79)
0.306;-2900.0
79(9J)
0.274;-2560.0
(7T)(9T)
0.272;-1120.0
9(7TK)
0.345;-3340.0
7(9TQ)
0.318;-3560.0
79(TJ)
0.320;-3780.0
79(TK)
0.309;-3340.0
(7J)(9K)
0.310;-1680.0
7K(9J)
0.270;-3120.0
79(JK)
0.361;-3120.0
(9Q)(7K)
0.290;-1460.0
(7K)(9K)
0.369;200.0
T(7TQ)
0.296;-1900.0
Q(7TJ)
0.321;-3120.0
(7T)(JK)
0.367;-1460.0
QK(7T)
0.293;-2680.0
7T(TQ)
0.285;-1900.0
(7J)(TQ)
0.352;-1680.0
7Q(TJ)
0.287;-3120.0
7TJQ
0.310;-4560.0
(7Q)(TK)
0.328;-1240.0
7Q(TK)
0.270;-2680.0
J(7JQ)
0.315;-1460.0
K(7JQ)
0.267;-2460.0
JJ(7Q)
0.291;-1460.0
J(7QK)
0.256;-2460.0
JQ(7K)
0.269;-2460.0
QQ(7Q)
0.317;420.0
7Q(QK)
0.398;-800.0
8888
0.311;-2000.0
888Q
0.373;-2560.0
8(89J)
0.245;-2560.0
8K(89)
0.328;-2120.0
89(8Q)
0.297;-2340.0
8(8TJ)
0.354;-2340.0
8K(8T)
0.270;-1900.0
8T(8K)
0.311;-1900.0
8(8JK)
0.329;-1680.0
88(JK)
0.303;-1680.0
8Q(8K)
0.336;-1460.0
(89)(9T)
0.307;-1120.0
9(89K)
0.292;-1900.0
(89TK)
0.249;-3120.0
TQ(89)
0.227;-3340.0
K(89J)
0.344;-2900.0
Q(89Q)
0.366;-1460.0
KK(89)
0.366;-1020.0
99(8Q)
0.303;-2120.0
9(8TJ)
0.324;-3560.0
9K(8T)
0.353;-3120.0
(9T)(8K)
0.303;-1680.0
9T(8Q)
0.302;-3340.0
(8J)(9J)
0.318;-460.0
8J(9J)
0.284;-1900.0
9J(8Q)
0.252;-3120.0
(8Q)(9Q)
0.394;-20.0
8K(9Q)
0.314;-2680.0
8K(9K)
0.327;-1020.0
TQ(8T)
0.325;-1680.0
K(8TJ)
0.267;-2680.0
Q(8TQ)
0.308;-1240.0
KK(8T)
0.305;-800.0
