AAAA
0.318;-7150.0
5AAA
0.299;-16768.7
9AAA
0.377;-14293.7
KAAA
0.293;-11818.7
4A(2A)
0.248;-24812.5
(2A)(7A)
0.289;-18906.3
A(2TA)
0.296;-21100.0
QA(2A)
0.312;-19862.5
2A(4A)
0.286;-24812.5
26AA
0.207;-27625.0
AA(29)
0.239;-21718.7
2A(QA)
0.236;-19862.5
A(34A)
0.238;-24193.7
6A(3A)
0.275;-22956.2
(3A)(9A)
0.304;-17050.0
A(3QA)
0.245;-19243.8
AA(34)
0.249;-24193.7
3A(7A)
0.219;-22337.5
39AA
0.246;-25150.0
AA(3Q)
0.315;-19243.8
(4A)(5A)
0.301;-18906.3
A(48A)
0.265;-21100.0
TA(4A)
0.262;-19862.5
(4A)(KA)
0.323;-13956.2
46AA
0.232;-26387.5
AA(49)
0.241;-20481.2
4A(QA)
0.274;-18625.0
A(56A)
0.260;-21718.7
8A(5A)
0.271;-20481.2
(5A)(JA)
0.286;-14575.0
55AA
0.248;-22337.5
AA(58)
0.272;-20481.2
5A(JA)
0.261;-18625.0
5KAA
0.262;-21437.5
8A(6A)
0.274;-19862.5
(6A)(JA)
0.333;-13956.2
66AA
0.283;-21100.0
AA(69)
0.237;-19243.8
6A(QA)
0.340;-17387.5
A(78A)
0.255;-19243.8
TA(7A)
0.342;-18006.2
(7A)(KA)
0.321;-12100.0
79AA
0.213;-22675.0
AA(7Q)
0.366;-16768.8
(8A)(9A)
0.344;-13956.2
A(8QA)
0.367;-16150.0
AA(89)
0.283;-18006.2
8A(QA)
0.361;-16150.0
A(9TA)
0.257;-16768.8
QA(9A)
0.260;-15531.3
9A(JA)
0.281;-16150.0
9KAA
0.237;-18962.5
QA(TA)
0.262;-14912.5
TA(QA)
0.300;-14912.5
A(JQA)
0.302;-14293.8
AA(JQ)
0.312;-14293.8
(QA)(KA)
0.333;-9006.3
KKAA
0.383;-12437.5
2(25A)
0.241;-31618.8
27(2A)
0.222;-30381.2
(2T)(2A)
0.281;-24475.0
2(2KA)
0.242;-26668.8
(236A)
0.183;-34431.2
(23TA)
0.238;-31956.2
33(2A)
0.197;-32237.5
(36)(2A)
0.230;-30381.2
3(29A)
0.186;-32575.0
3J(2A)
0.208;-31337.5
(245A)
0.184;-34431.2
(249A)
0.229;-31956.2
(24KA)
0.267;-29481.2
46(2A)
0.182;-33812.5
(49)(2A)
0.184;-27906.2
4(2QA)
0.215;-30100.0
6(25A)
0.248;-33193.8
T(25A)
0.209;-30718.8
5(26A)
0.169;-33193.8
58(2A)
0.254;-31956.2
(5J)(2A)
0.270;-26050.0
6(26A)
0.213;-28525.0
T(26A)
0.195;-30100.0
6(27A)
0.160;-31956.2
69(2A)
0.205;-30718.8
(6Q)(2A)
0.241;-24812.5
(279A)
0.236;-30100.0
(27KA)
0.222;-27625.0
79(2A)
0.164;-30100.0
(7Q)(2A)
0.278;-24193.8
(28TA)
0.215;-28862.5
88(2A)
0.282;-26050.0
(8J)(2A)
0.193;-24193.8
9(29A)
0.249;-24812.5
K(29A)
0.235;-26387.5
9(2QA)
0.259;-27006.2
J(2TA)
0.226;-27006.2
TJ(2A)
0.267;-27006.2
(2JQA)
0.259;-25768.7
J(2KA)
0.232;-25150.0
(QK)(2A)
0.245;-20481.2
22(4A)
0.227;-32237.5
226A
0.195;-35050.0
2A(29)
0.228;-29143.7
22(QA)
0.215;-27287.5
2(34A)
0.147;-35668.8
26(3A)
0.212;-34431.2
(29)(3A)
0.229;-28525.0
2(3QA)
0.240;-30718.8
A(234)
0.214;-35668.8
(23)(7A)
0.167;-29762.5
9A(23)
0.227;-32575.0
A(23Q)
0.231;-30718.8
2A(34)
0.187;-35668.8
2A(36)
0.220;-34431.2
2A(38)
0.217;-33193.8
2A(3T)
0.205;-31956.2
2A(3Q)
0.224;-30718.8
2(45A)
0.183;-34431.2
27(4A)
0.211;-33193.8
(2T)(4A)
0.283;-27287.5
2(4KA)
0.196;-29481.2
A(246)
0.228;-33812.5
(24)(9A)
0.176;-27906.2
JA(24)
0.205;-30718.8
24(5A)
0.236;-34431.2
24(7A)
0.219;-33193.8
24(9A)
0.228;-31956.2
24(JA)
0.178;-30718.8
24(KA)
0.223;-29481.2
26(5A)
0.171;-33193.8
(29)(5A)
0.258;-27287.5
2(5QA)
0.186;-29481.2
A(256)
0.186;-33193.8
(25)(9A)
0.285;-27287.5
JA(25)
0.239;-30100.0
25(6A)
0.208;-33193.8
25(8A)
0.176;-31956.2
25(TA)
0.242;-30718.8
25(QA)
0.264;-29481.2
(26)(6A)
0.223;-24475.0
2(69A)
0.246;-30718.8
2J(6A)
0.246;-29481.2
(26)(7A)
0.245;-27906.2
9A(26)
0.230;-30718.8
A(26Q)
0.214;-28862.5
2A(67)
0.224;-31956.2
2A(69)
0.167;-30718.8
2A(6J)
0.245;-29481.2
2A(6K)
0.185;-28243.8
(29)(7A)
0.194;-26050.0
2(7QA)
0.182;-28243.8
A(278)
0.198;-30718.8
(27)(JA)
0.285;-24812.5
KA(27)
0.225;-27625.0
2A(79)
0.193;-30100.0
2A(7J)
0.187;-28862.5
2A(7K)
0.218;-27625.0
(2T)(8A)
0.268;-24812.5
2(8KA)
0.197;-27006.2
A(28T)
0.201;-28862.5
(28)(KA)
0.241;-22956.2
28(TA)
0.226;-28862.5
28(QA)
0.234;-27625.0
(29)(9A)
0.252;-20762.5
2(9QA)
0.182;-27006.2
A(29T)
0.222;-28243.8
(29)(KA)
0.274;-22337.5
29(JA)
0.263;-27625.0
29(KA)
0.253;-26387.5
2J(TA)
0.259;-27006.2
(2T)(JA)
0.268;-22956.2
KA(2T)
0.249;-25768.7
2A(TQ)
0.242;-26387.5
2(JQA)
0.257;-25768.7
A(2JQ)
0.206;-25768.7
2A(JQ)
0.239;-25768.7
2(QKA)
0.208;-24531.2
2Q(KA)
0.273;-24531.2
33(3A)
0.295;-27568.7
(36)(3A)
0.207;-25712.5
3(39A)
0.227;-27906.2
3J(3A)
0.208;-26668.8
(345A)
0.167;-33812.5
(349A)
0.240;-31337.5
(34KA)
0.207;-28862.5
46(3A)
0.223;-33193.8
(49)(3A)
0.243;-27287.5
4(3QA)
0.245;-29481.2
6(35A)
0.214;-32575.0
T(35A)
0.228;-30100.0
5(36A)
0.244;-32575.0
58(3A)
0.236;-31337.5
(5J)(3A)
0.287;-25431.2
6(36A)
0.284;-27906.2
T(36A)
0.177;-29481.2
6(37A)
0.244;-31337.5
69(3A)
0.198;-30100.0
(6Q)(3A)
0.221;-24193.8
(379A)
0.171;-29481.2
(37KA)
0.201;-27006.2
79(3A)
0.218;-29481.2
(7Q)(3A)
0.242;-23575.0
(38TA)
0.235;-28243.8
88(3A)
0.201;-25431.2
(8J)(3A)
0.326;-23575.0
9(39A)
0.232;-24193.7
K(39A)
0.206;-25768.7
9(3QA)
0.240;-26387.5
J(3TA)
0.252;-26387.5
TJ(3A)
0.256;-26387.5
(3JQA)
0.245;-25150.0
J(3KA)
0.252;-24531.2
(QK)(3A)
0.294;-19862.5
33(5A)
0.202;-30381.2
337A
0.154;-33193.8
3A(3T)
0.205;-27287.5
33(KA)
0.243;-25431.2
3(46A)
0.158;-33193.8
38(4A)
0.226;-31956.2
(3J)(4A)
0.243;-26050.0
4A(34)
0.256;-30381.2
A(347)
0.165;-32575.0
(34)(TA)
0.213;-26668.8
QA(34)
0.207;-29481.2
345A
0.164;-37862.5
347A
0.157;-36625.0
349A
0.179;-35387.5
34JA
0.155;-34150.0
34KA
0.246;-32912.5
37(5A)
0.234;-31956.2
(3T)(5A)
0.241;-26050.0
3(5KA)
0.230;-28243.8
A(357)
0.245;-31956.2
(35)(TA)
0.195;-26050.0
QA(35)
0.184;-28862.5
356A
0.153;-36625.0
358A
0.173;-35387.5
35TA
0.174;-34150.0
35QA
0.176;-32912.5
(37)(6A)
0.196;-27287.5
3(6TA)
0.218;-29481.2
3Q(6A)
0.231;-28243.8
(36)(8A)
0.236;-26668.8
TA(36)
0.239;-29481.2
A(36K)
0.245;-27625.0
6A(38)
0.246;-30718.8
6A(3T)
0.215;-29481.2
6A(3Q)
0.236;-28243.8
37(7A)
0.273;-26668.8
(3T)(7A)
0.290;-24812.5
3(7KA)
0.244;-27006.2
A(379)
0.249;-29481.2
(37)(QA)
0.294;-23575.0
7A(38)
0.204;-30100.0
7A(3T)
0.195;-28862.5
7A(3Q)
0.249;-27625.0
38(8A)
0.260;-25431.2
(3J)(8A)
0.228;-23575.0
8A(38)
0.273;-25431.2
A(38J)
0.230;-27625.0
388A
0.219;-29481.2
38TA
0.217;-32293.8
38QA
0.190;-31056.2
(3T)(9A)
0.247;-23575.0
3(9KA)
0.276;-25768.7
A(39J)
0.247;-27006.2
399A
0.243;-28243.8
39JA
0.224;-31056.2
39KA
0.210;-29818.7
3Q(TA)
0.216;-25768.7
(3T)(QA)
0.220;-21718.7
TA(3J)
0.236;-26387.5
TA(3K)
0.261;-25150.0
3(JKA)
0.234;-24531.2
A(3JK)
0.211;-24531.2
JA(3K)
0.215;-24531.2
QA(3Q)
0.313;-20481.2
3QKA
0.183;-27962.5
45(4A)
0.263;-29143.7
(48)(4A)
0.299;-23237.5
4(4JA)
0.212;-25431.2
4K(4A)
0.224;-24193.7
(459A)
0.232;-30100.0
(45KA)
0.174;-27625.0
57(4A)
0.245;-31337.5
(5T)(4A)
0.262;-25431.2
5(4KA)
0.285;-27625.0
(469A)
0.283;-29481.2
(46KA)
0.202;-27006.2
68(4A)
0.258;-30100.0
(6J)(4A)
0.196;-24193.8
7(47A)
0.229;-26050.0
J(47A)
0.260;-27625.0
78(4A)
0.180;-29481.2
(7J)(4A)
0.306;-23575.0
8(48A)
0.237;-24812.5
Q(48A)
0.251;-26387.5
(8T)(4A)
0.223;-23575.0
8(4KA)
0.275;-25768.7
(49QA)
0.241;-25768.7
9(4JA)
0.217;-26387.5
9K(4A)
0.249;-25150.0
TT(4A)
0.255;-22337.5
(TK)(4A)
0.288;-20481.2
J(4QA)
0.254;-24531.2
K(4QA)
0.251;-23293.8
44(5A)
0.222;-29143.7
447A
0.222;-31956.2
4A(4T)
0.224;-26050.0
44(KA)
0.272;-24193.7
4(57A)
0.208;-31337.5
49(5A)
0.190;-30100.0
(4Q)(5A)
0.264;-24193.8
6A(45)
0.179;-31956.2
A(459)
0.182;-30100.0
(45)(QA)
0.316;-24193.8
5A(46)
0.220;-31956.2
5A(48)
0.212;-30718.8
5A(4T)
0.234;-29481.2
5A(4Q)
0.280;-28243.8
46(6A)
0.241;-27287.5
(49)(6A)
0.233;-25431.2
4(6QA)
0.290;-27625.0
A(467)
0.192;-30718.8
(46)(TA)
0.222;-24812.5
QA(46)
0.227;-27625.0
467A
0.144;-34768.8
469A
0.203;-33531.2
46JA
0.185;-32293.8
46KA
0.192;-31056.2
49(7A)
0.244;-28862.5
(4Q)(7A)
0.291;-22956.2
8A(47)
0.207;-29481.2
A(47J)
0.180;-27625.0
477A
0.264;-30100.0
479A
0.160;-32912.5
47JA
0.248;-31675.0
47KA
0.211;-30437.5
4T(8A)
0.290;-27625.0
(4K)(8A)
0.262;-21718.7
TA(48)
0.200;-27625.0
A(48K)
0.206;-25768.7
8A(4T)
0.251;-27625.0
8A(4Q)
0.238;-26387.5
49(9A)
0.248;-23575.0
(4Q)(9A)
0.241;-21718.7
TA(49)
0.206;-27006.2
A(49K)
0.240;-25150.0
9A(4J)
0.220;-26387.5
9A(4K)
0.314;-25150.0
4(TQA)
0.259;-25150.0
A(4TJ)
0.219;-25768.7
4TTA
0.256;-26387.5
4TQA
0.265;-29200.0
(4Q)(JA)
0.276;-20481.2
QA(4J)
0.236;-24531.2
4JQA
0.253;-28581.2
(4K)(QA)
0.238;-19243.8
QA(4K)
0.280;-23293.8
5(56A)
0.221;-27287.5
58(5A)
0.182;-26050.0
(5J)(5A)
0.331;-20143.7
6(56A)
0.186;-26668.8
T(56A)
0.236;-28243.8
6(57A)
0.221;-30100.0
69(5A)
0.252;-28862.5
(6Q)(5A)
0.300;-22956.2
(579A)
0.230;-28243.8
(57KA)
0.185;-25768.7
79(5A)
0.196;-28243.8
(7Q)(5A)
0.226;-22337.5
(58TA)
0.239;-27006.2
88(5A)
0.266;-24193.7
(8J)(5A)
0.316;-22337.5
9(59A)
0.287;-22956.2
K(59A)
0.197;-24531.2
9(5QA)
0.203;-25150.0
J(5TA)
0.215;-25150.0
TJ(5A)
0.203;-25150.0
(5JQA)
0.227;-23912.5
J(5KA)
0.296;-23293.8
(QK)(5A)
0.286;-18625.0
55(7A)
0.251;-26668.8
559A
0.243;-29481.2
5A(5Q)
0.262;-23575.0
(57)(6A)
0.210;-26050.0
5(6TA)
0.234;-28243.8
5Q(6A)
0.278;-27006.2
(56)(8A)
0.235;-25431.2
TA(56)
0.248;-28243.8
A(56K)
0.193;-26387.5
6A(58)
0.238;-29481.2
6A(5T)
0.181;-28243.8
6A(5Q)
0.236;-27006.2
57(7A)
0.243;-25431.2
(5T)(7A)
0.273;-23575.0
5(7KA)
0.276;-25768.7
A(579)
0.222;-28243.8
(57)(QA)
0.319;-22337.5
7A(58)
0.218;-28862.5
7A(5T)
0.280;-27625.0
7A(5Q)
0.221;-26387.5
58(8A)
0.304;-24193.7
(5J)(8A)
0.295;-22337.5
8A(58)
0.230;-24193.7
A(58J)
0.247;-26387.5
588A
0.273;-28243.8
58TA
0.248;-31056.2
58QA
0.245;-29818.7
(5T)(9A)
0.270;-22337.5
5(9KA)
0.228;-24531.2
A(59J)
0.254;-25768.7
599A
0.191;-27006.2
59JA
0.205;-29818.7
59KA
0.258;-28581.2
5Q(TA)
0.270;-24531.2
(5T)(QA)
0.276;-20481.2
TA(5J)
0.254;-25150.0
TA(5K)
0.308;-23912.5
5(JKA)
0.205;-23293.8
A(5JK)
0.275;-23293.8
JA(5K)
0.255;-23293.8
QA(5Q)
0.318;-19243.8
5QKA
0.236;-26725.0
67(6A)
0.219;-25431.2
(6T)(6A)
0.322;-19525.0
6(6KA)
0.259;-21718.7
(67TA)
0.213;-27006.2
77(6A)
0.264;-24812.5
(7T)(6A)
0.310;-22956.2
7(6KA)
0.265;-25150.0
(68JA)
0.262;-25768.7
(89)(6A)
0.223;-22956.2
8(6QA)
0.221;-25150.0
T(69A)
0.205;-25768.7
9(6TA)
0.265;-25768.7
9Q(6A)
0.222;-24531.2
Q(6TA)
0.203;-23912.5
(TQ)(6A)
0.285;-19862.5
(6JKA)
0.224;-22675.0
JK(6A)
0.254;-22675.0
K(6KA)
0.271;-17387.5
668A
0.217;-28862.5
6A(6J)
0.225;-22956.2
(67)(7A)
0.220;-20762.5
6(7TA)
0.234;-27006.2
6Q(7A)
0.247;-25768.7
(67)(9A)
0.258;-23575.0
JA(67)
0.259;-26387.5
67(8A)
0.213;-28243.8
67(TA)
0.233;-27006.2
67(QA)
0.225;-25768.7
(68)(8A)
0.298;-19525.0
6(8JA)
0.207;-25768.7
6K(8A)
0.245;-24531.2
(68)(JA)
0.237;-21718.7
KA(68)
0.240;-24531.2
6A(8T)
0.238;-26387.5
6A(8Q)
0.247;-25150.0
6(9TA)
0.207;-25768.7
6Q(9A)
0.288;-24531.2
(69)(JA)
0.254;-21100.0
KA(69)
0.197;-23912.5
6A(9J)
0.225;-25150.0
6A(9K)
0.286;-23912.5
(6Q)(TA)
0.251;-19862.5
JA(6T)
0.251;-24531.2
6T(JA)
0.212;-24531.2
6T(KA)
0.220;-23293.8
6Q(JA)
0.303;-23293.8
(6J)(KA)
0.244;-18625.0
6J(KA)
0.233;-22675.0
6K(QA)
0.230;-22056.2
6A(QK)
0.225;-22056.2
(78)(7A)
0.268;-19525.0
7(7JA)
0.264;-21718.7
7K(7A)
0.271;-20481.2
(78QA)
0.283;-24531.2
8(7TA)
0.269;-25768.7
8Q(7A)
0.191;-24531.2
J(79A)
0.297;-24531.2
9T(7A)
0.228;-25150.0
(9K)(7A)
0.297;-19243.8
K(7TA)
0.215;-22675.0
T(7KA)
0.253;-22675.0
JJ(7A)
0.284;-19243.8
(7QKA)
0.275;-21437.5
777A
0.256;-24193.8
7A(7T)
0.288;-22337.5
77(KA)
0.244;-20481.2
7(8TA)
0.252;-25768.7
7Q(8A)
0.252;-24531.2
(78)(TA)
0.263;-21718.7
QA(78)
0.256;-24531.2
789A
0.197;-30437.5
78JA
0.273;-29200.0
78KA
0.269;-27962.5
7J(9A)
0.270;-24531.2
(79)(TA)
0.250;-21100.0
QA(79)
0.283;-23912.5
79TA
0.184;-29200.0
79QA
0.240;-27962.5
(7J)(TA)
0.328;-19862.5
TA(7T)
0.261;-20481.2
A(7TK)
0.283;-22675.0
TA(7Q)
0.243;-23293.8
7J(JA)
0.256;-19243.8
(7J)(QA)
0.259;-18625.0
JA(7Q)
0.218;-22675.0
7Q(QA)
0.289;-18006.2
7QQA
0.285;-22056.2
7KKA
0.242;-20818.8
8(8JA)
0.252;-20481.2
8K(8A)
0.339;-19243.8
(89KA)
0.304;-22675.0
9J(8A)
0.280;-23912.5
(8TJA)
0.248;-23293.8
(TJ)(8A)
0.317;-19243.8
J(8JA)
0.323;-18625.0
JQ(8A)
0.252;-22056.2
Q(8KA)
0.339;-20818.8
889A
0.198;-25768.7
8A(8Q)
0.283;-19862.5
(8T)(9A)
0.305;-20481.2
8(9KA)
0.305;-22675.0
A(89J)
0.232;-23912.5
899A
0.251;-25150.0
89JA
0.247;-27962.5
89KA
0.257;-26725.0
8Q(TA)
0.289;-22675.0
(8T)(QA)
0.305;-18625.0
TA(8J)
0.245;-23293.8
TA(8K)
0.242;-22056.2
8(JKA)
0.267;-21437.5
A(8JK)
0.234;-21437.5
JA(8K)
0.314;-21437.5
QA(8Q)
0.290;-17387.5
8QKA
0.283;-24868.8
9T(9A)
0.303;-19862.5
(9K)(9A)
0.339;-13956.2
K(9TA)
0.276;-21437.5
T(9KA)
0.276;-21437.5
JJ(9A)
0.326;-18006.2
(9QKA)
0.263;-20200.0
999A
0.284;-20481.2
9A(9Q)
0.311;-18625.0
(9J)(TA)
0.292;-18625.0
TA(9T)
0.316;-19243.8
A(9TK)
0.303;-21437.5
TA(9Q)
0.237;-22056.2
9J(JA)
0.246;-18006.2
(9J)(QA)
0.297;-17387.5
JA(9Q)
0.239;-21437.5
9Q(QA)
0.316;-16768.8
9QQA
0.289;-20818.8
9KKA
0.286;-19581.2
T(TKA)
0.312;-16768.8
JJ(TA)
0.344;-17387.5
(TQKA)
0.304;-19581.2
TTTA
0.320;-18625.0
TA(TK)
0.308;-16768.8
(TK)(JA)
0.367;-16150.0
KA(TJ)
0.342;-20200.0
TA(JK)
0.279;-20200.0
(TQ)(KA)
0.286;-15531.3
(TK)(KA)
0.414;-10862.5
J(JKA)
0.333;-15531.3
(QK)(JA)
0.325;-14912.5
JJ(KA)
0.331;-15531.3
QA(JQ)
0.311;-15531.3
JQKA
0.279;-23012.5
QK(QA)
0.252;-14293.8
QK(KA)
0.320;-13675.0
22(24)
0.162;-35612.5
22(28)
0.213;-33137.5
22(2Q)
0.222;-30662.5
24(23)
0.141;-39043.8
(23)(27)
0.198;-33137.5
2(23T)
0.166;-35331.2
2Q(23)
0.161;-34093.8
23(25)
0.127;-38425.0
2237
0.136;-41237.5
22(3T)
0.177;-35331.2
23(2K)
0.188;-33475.0
2(246)
0.209;-37187.5
28(24)
0.221;-35950.0
(24)(2J)
0.217;-30043.7
2244
0.149;-38425.0
22(47)
0.200;-36568.8
24(2T)
0.184;-34712.5
224Q
0.219;-37525.0
26(25)
0.204;-36568.8
(25)(29)
0.199;-30662.5
2(25Q)
0.207;-32856.2
22(56)
0.227;-36568.8
25(29)
0.172;-34712.5
225J
0.177;-37525.0
26(26)
0.155;-31900.0
(26)(29)
0.178;-30043.7
2(26Q)
0.183;-32237.5
22(67)
0.154;-35331.2
26(2T)
0.239;-33475.0
226Q
0.164;-36287.5
28(27)
0.199;-34093.8
(27)(2J)
0.229;-28187.5
2277
0.202;-34712.5
22(7T)
0.215;-32856.2
27(2K)
0.251;-31000.0
2(28T)
0.261;-32237.5
2Q(28)
0.211;-31000.0
28(2T)
0.242;-32237.5
228Q
0.169;-35050.0
2T(29)
0.254;-31618.8
(29)(2K)
0.267;-25712.5
229J
0.225;-35050.0
2T(2T)
0.244;-26950.0
(2T)(2K)
0.251;-25093.7
22TQ
0.173;-33812.5
2Q(2J)
0.248;-29143.7
2J(2K)
0.272;-28525.0
22QQ
0.237;-28525.0
3(234)
0.167;-38425.0
36(23)
0.131;-37187.5
(23)(39)
0.270;-31281.2
3(23Q)
0.160;-33475.0
5(234)
0.157;-41237.5
9(234)
0.199;-38762.5
K(234)
0.176;-36287.5
4(237)
0.174;-40000.0
49(23)
0.134;-38762.5
(23)(4Q)
0.216;-32856.2
(2357)
0.148;-39381.2
(235J)
0.153;-36906.2
(23)(56)
0.204;-35950.0
5(239)
0.149;-38143.8
5J(23)
0.164;-36906.2
(2367)
0.195;-38762.5
(236J)
0.203;-36287.5
(23)(67)
0.181;-34712.5
6(23T)
0.217;-36906.2
6Q(23)
0.187;-35668.8
9(237)
0.184;-36906.2
K(237)
0.190;-34431.2
7(23T)
0.174;-36287.5
7Q(23)
0.189;-35050.0
T(238)
0.189;-35668.8
8(239)
0.160;-36287.5
8J(23)
0.188;-35050.0
(239T)
0.195;-35050.0
99(23)
0.170;-31618.8
(23)(9Q)
0.208;-29762.5
(23TQ)
0.231;-33193.8
T(23Q)
0.182;-33193.8
Q(23J)
0.229;-32575.0
(23)(JK)
0.230;-27906.2
QK(23)
0.216;-31337.5
23(35)
0.173;-37806.2
33(28)
0.217;-35950.0
233T
0.214;-38762.5
23(3K)
0.203;-32856.2
(24)(36)
0.145;-36568.8
3(249)
0.179;-38762.5
3J(24)
0.172;-37525.0
(34)(25)
0.166;-37187.5
27(34)
0.206;-40000.0
2(34T)
0.191;-38143.8
(34)(2K)
0.171;-32237.5
34(26)
0.154;-40618.8
34(28)
0.173;-39381.2
34(2T)
0.185;-38143.8
34(2Q)
0.228;-36906.2
(25)(35)
0.175;-32518.8
3(258)
0.139;-38762.5
3T(25)
0.134;-37525.0
(25)(3K)
0.247;-31618.8
27(35)
0.186;-39381.2
2(35T)
0.159;-37525.0
(35)(2K)
0.260;-31618.8
35(27)
0.157;-39381.2
35(29)
0.209;-38143.8
35(2J)
0.187;-36906.2
35(2K)
0.178;-35668.8
37(26)
0.156;-38762.5
(26)(3T)
0.203;-32856.2
3(26K)
0.184;-35050.0
2(368)
0.179;-38143.8
(36)(2J)
0.202;-32237.5
2K(36)
0.212;-35050.0
23(68)
0.202;-38143.8
23(6T)
0.137;-36906.2
23(6Q)
0.177;-35668.8
3(278)
0.174;-37525.0
3T(27)
0.215;-36287.5
(27)(3K)
0.222;-30381.2
29(37)
0.151;-36906.2
2(37Q)
0.156;-35050.0
23(78)
0.166;-37525.0
23(7T)
0.222;-36287.5
23(7Q)
0.151;-35050.0
3(289)
0.214;-36287.5
3J(28)
0.203;-35050.0
(38)(29)
0.236;-32237.5
2J(38)
0.200;-35050.0
38(29)
0.165;-36287.5
38(2J)
0.193;-35050.0
38(2K)
0.218;-33812.5
3T(29)
0.181;-35050.0
(29)(3K)
0.243;-29143.8
2J(39)
0.157;-34431.2
39(2T)
0.238;-35050.0
39(2Q)
0.209;-33812.5
(2T)(3T)
0.211;-26331.2
3(2TK)
0.184;-32575.0
2(3TQ)
0.199;-33193.8
23(TJ)
0.179;-33812.5
23(TK)
0.212;-32575.0
(2J)(3K)
0.204;-27906.2
2K(3J)
0.189;-31956.2
23(JK)
0.215;-31956.2
(3Q)(2K)
0.244;-27287.5
(2K)(3K)
0.234;-22618.8
4(246)
0.151;-35950.0
48(24)
0.205;-34712.5
(24)(4J)
0.268;-28806.3
5(245)
0.182;-35950.0
9(245)
0.216;-37525.0
K(245)
0.193;-35050.0
5(248)
0.147;-38143.8
5T(24)
0.191;-36906.2
(24)(5K)
0.217;-31000.0
9(246)
0.197;-36906.2
K(246)
0.185;-34431.2
6(249)
0.181;-36906.2
6J(24)
0.215;-35668.8
(2478)
0.208;-36906.2
(247Q)
0.170;-34431.2
7(249)
0.219;-36287.5
7J(24)
0.211;-35050.0
(2489)
0.190;-35668.8
(248K)
0.202;-33193.8
8T(24)
0.210;-35050.0
(24)(8K)
0.223;-29143.8
Q(249)
0.210;-33193.8
(24)(9J)
0.218;-29762.5
T(24T)
0.225;-29762.5
T(24J)
0.199;-33193.8
TK(24)
0.187;-31956.2
(24)(JQ)
0.210;-27906.2
QQ(24)
0.270;-27287.5
24(45)
0.197;-36568.8
44(28)
0.196;-34712.5
244T
0.158;-37525.0
24(4K)
0.225;-31618.8
(25)(47)
0.197;-34712.5
4(25T)
0.187;-36906.2
4Q(25)
0.176;-35668.8
(45)(27)
0.210;-34712.5
29(45)
0.225;-37525.0
2(45Q)
0.176;-35668.8
24(56)
0.167;-39381.2
24(58)
0.141;-38143.8
24(5T)
0.166;-36906.2
24(5Q)
0.198;-35668.8
4(267)
0.170;-38143.8
49(26)
0.204;-36906.2
(26)(4Q)
0.194;-31000.0
27(46)
0.203;-38143.8
2(46T)
0.194;-36287.5
(46)(2K)
0.234;-30381.2
46(28)
0.143;-37525.0
46(2T)
0.187;-36287.5
46(2Q)
0.188;-35050.0
(27)(47)
0.211;-29425.0
4(27T)
0.183;-35668.8
4Q(27)
0.156;-34431.2
(47)(29)
0.235;-32237.5
2J(47)
0.181;-35050.0
47(28)
0.131;-36906.2
47(2T)
0.212;-35668.8
47(2Q)
0.191;-34431.2
(28)(48)
0.282;-28187.5
4(28J)
0.199;-34431.2
4K(28)
0.219;-33193.8
(48)(2J)
0.212;-30381.2
2K(48)
0.173;-33193.8
24(8T)
0.228;-35050.0
24(8Q)
0.196;-33812.5
4(29T)
0.190;-34431.2
4Q(29)
0.196;-33193.8
(49)(2J)
0.235;-29762.5
2K(49)
0.213;-32575.0
24(9J)
0.188;-33812.5
24(9K)
0.199;-32575.0
(2T)(4Q)
0.189;-28525.0
2J(4T)
0.234;-33193.8
4T(2J)
0.183;-33193.8
4T(2K)
0.254;-31956.2
4Q(2J)
0.220;-31956.2
(4J)(2K)
0.220;-27287.5
4J(2K)
0.274;-31337.5
4K(2Q)
0.235;-30718.8
24(QK)
0.199;-30718.8
(25)(56)
0.188;-30662.5
5(259)
0.233;-32856.2
5J(25)
0.201;-31618.8
(2567)
0.176;-37525.0
(256J)
0.175;-35050.0
(25)(67)
0.207;-33475.0
6(25T)
0.163;-35668.8
6Q(25)
0.195;-34431.2
9(257)
0.204;-35668.8
K(257)
0.207;-33193.8
7(25T)
0.200;-35050.0
7Q(25)
0.177;-33812.5
T(258)
0.214;-34431.2
8(259)
0.198;-35050.0
8J(25)
0.174;-33812.5
(259T)
0.181;-33812.5
99(25)
0.222;-30381.2
(25)(9Q)
0.239;-28525.0
(25TQ)
0.198;-31956.2
T(25Q)
0.230;-31956.2
Q(25J)
0.205;-31337.5
(25)(JK)
0.269;-26668.8
QK(25)
0.206;-30100.0
25(57)
0.193;-34093.8
55(2T)
0.207;-32237.5
255Q
0.182;-35050.0
57(26)
0.163;-37525.0
(26)(5T)
0.161;-31618.8
5(26K)
0.194;-33812.5
2(568)
0.205;-36906.2
(56)(2J)
0.183;-31000.0
2K(56)
0.190;-33812.5
25(68)
0.185;-36906.2
25(6T)
0.233;-35668.8
25(6Q)
0.256;-34431.2
5(278)
0.162;-36287.5
5T(27)
0.226;-35050.0
(27)(5K)
0.178;-29143.8
29(57)
0.167;-35668.8
2(57Q)
0.149;-33812.5
25(78)
0.175;-36287.5
25(7T)
0.163;-35050.0
25(7Q)
0.175;-33812.5
5(289)
0.198;-35050.0
5J(28)
0.191;-33812.5
(58)(29)
0.215;-31000.0
2J(58)
0.177;-33812.5
58(29)
0.248;-35050.0
58(2J)
0.173;-33812.5
58(2K)
0.242;-32575.0
5T(29)
0.182;-33812.5
(29)(5K)
0.275;-27906.2
2J(59)
0.182;-33193.8
59(2T)
0.176;-33812.5
59(2Q)
0.159;-32575.0
(2T)(5T)
0.278;-25093.7
5(2TK)
0.224;-31337.5
2(5TQ)
0.159;-31956.2
25(TJ)
0.194;-32575.0
25(TK)
0.166;-31337.5
(2J)(5K)
0.215;-26668.8
2K(5J)
0.239;-30718.8
25(JK)
0.184;-30718.8
(5Q)(2K)
0.225;-26050.0
(2K)(5K)
0.316;-21381.2
6(268)
0.245;-32237.5
6T(26)
0.159;-31000.0
(26)(6K)
0.273;-25093.7
T(267)
0.170;-34431.2
7(268)
0.184;-35668.8
7T(26)
0.223;-34431.2
(26)(7K)
0.202;-28525.0
J(268)
0.232;-33193.8
89(26)
0.172;-34431.2
(26)(8Q)
0.170;-28525.0
(269J)
0.188;-32575.0
(26)(9T)
0.215;-29143.8
9(26K)
0.202;-31337.5
(26TK)
0.189;-30718.8
TQ(26)
0.195;-31337.5
K(26J)
0.205;-30100.0
Q(26Q)
0.266;-26050.0
KK(26)
0.279;-24812.5
66(29)
0.201;-31618.8
266J
0.183;-34431.2
67(27)
0.174;-32237.5
(27)(6T)
0.168;-30381.2
6(27K)
0.227;-32575.0
2(679)
0.195;-35050.0
(67)(2Q)
0.216;-29143.8
27(68)
0.179;-35668.8
27(6T)
0.187;-34431.2
27(6Q)
0.206;-33193.8
68(28)
0.181;-31000.0
(28)(6J)
0.174;-29143.8
28(68)
0.246;-31000.0
2(68J)
0.192;-33193.8
2688
0.157;-35050.0
268T
0.202;-37862.5
268Q
0.153;-36625.0
(29)(6T)
0.253;-29143.8
6(29K)
0.252;-31337.5
2(69J)
0.148;-32575.0
2699
0.250;-33812.5
269J
0.181;-36625.0
269K
0.160;-35387.5
6Q(2T)
0.195;-31337.5
(6T)(2Q)
0.205;-27287.5
2T(6J)
0.187;-31956.2
2T(6K)
0.273;-30718.8
6(2JK)
0.172;-30100.0
2(6JK)
0.199;-30100.0
2J(6K)
0.217;-30100.0
2Q(6Q)
0.204;-26050.0
26QK
0.190;-33531.2
78(27)
0.230;-31000.0
(27)(7J)
0.242;-25093.7
8(278)
0.186;-30381.2
Q(278)
0.197;-31956.2
(27)(8T)
0.191;-29143.8
8(27K)
0.235;-31337.5
(279Q)
0.152;-31337.5
9(27J)
0.217;-31956.2
9K(27)
0.186;-30718.8
TT(27)
0.230;-27906.2
(27)(TK)
0.232;-26050.0
J(27Q)
0.220;-30100.0
K(27Q)
0.193;-28862.5
77(28)
0.165;-31000.0
277T
0.200;-33812.5
27(7K)
0.199;-27906.2
(28)(7T)
0.238;-29143.8
7(28K)
0.258;-31337.5
2(78T)
0.173;-33193.8
(78)(2K)
0.274;-27287.5
78(2T)
0.178;-33193.8
78(2Q)
0.179;-31956.2
(29)(79)
0.239;-25093.7
7(29Q)
0.222;-31337.5
2(79T)
0.198;-32575.0
(79)(2K)
0.229;-26668.8
79(2J)
0.244;-31956.2
79(2K)
0.246;-30718.8
7J(2T)
0.262;-31337.5
(7T)(2J)
0.235;-27287.5
2K(7T)
0.244;-30100.0
27(TQ)
0.197;-30718.8
7(2JQ)
0.220;-30100.0
2(7JQ)
0.190;-30100.0
27(JQ)
0.169;-30100.0
7(2QK)
0.211;-28862.5
7Q(2K)
0.231;-28862.5
88(28)
0.261;-25712.5
(28)(8J)
0.274;-23856.2
9(289)
0.221;-28525.0
K(289)
0.225;-30100.0
9(28Q)
0.223;-30718.8
J(28T)
0.172;-30718.8
TJ(28)
0.241;-30718.8
(28JQ)
0.215;-29481.2
J(28K)
0.217;-28862.5
(28)(QK)
0.213;-24193.8
88(2T)
0.179;-28525.0
288Q
0.222;-31337.5
8T(29)
0.228;-31956.2
(29)(8K)
0.258;-26050.0
2J(89)
0.184;-31337.5
89(2T)
0.227;-31956.2
89(2Q)
0.203;-30718.8
(2T)(8T)
0.250;-23237.5
8(2TK)
0.211;-29481.2
2(8TQ)
0.196;-30100.0
28(TJ)
0.194;-30718.8
28(TK)
0.205;-29481.2
(2J)(8K)
0.279;-24812.5
2K(8J)
0.224;-28862.5
28(JK)
0.242;-28862.5
(8Q)(2K)
0.189;-24193.8
(2K)(8K)
0.274;-19525.0
9(29J)
0.222;-26668.8
9K(29)
0.215;-25431.2
TT(29)
0.231;-26668.8
(29)(TK)
0.231;-24812.5
J(29Q)
0.240;-28862.5
K(29Q)
0.252;-27625.0
99(2T)
0.231;-27287.5
299Q
0.232;-30100.0
9J(2T)
0.237;-30100.0
(9T)(2J)
0.234;-26050.0
2K(9T)
0.241;-28862.5
29(TQ)
0.218;-29481.2
9(2JQ)
0.250;-28862.5
2(9JQ)
0.221;-28862.5
29(JQ)
0.262;-28862.5
9(2QK)
0.201;-27625.0
9Q(2K)
0.211;-27625.0
TT(2T)
0.276;-22000.0
(2T)(TK)
0.232;-20143.7
J(2TQ)
0.260;-28243.8
K(2TQ)
0.260;-27006.2
TT(2J)
0.269;-25431.2
2TTK
0.276;-28243.8
TK(2J)
0.226;-27625.0
2TJJ
0.249;-28862.5
2TJK
0.219;-31675.0
2(TQK)
0.204;-27006.2
TK(2K)
0.212;-22337.5
(2J)(JK)
0.272;-18906.3
QK(2J)
0.265;-26387.5
2J(JK)
0.205;-22956.2
(JQ)(2K)
0.258;-22337.5
(2K)(JK)
0.266;-17668.7
K(2QK)
0.219;-21100.0
2K(QK)
0.270;-21100.0
3335
0.167;-37187.5
3339
0.237;-34712.5
333K
0.196;-32237.5
36(34)
0.189;-35950.0
(34)(39)
0.275;-30043.7
3(34Q)
0.269;-32237.5
33(45)
0.161;-36568.8
34(38)
0.232;-34712.5
334T
0.171;-37525.0
33(4K)
0.216;-31618.8
(35)(37)
0.232;-30662.5
3(35T)
0.224;-32856.2
3Q(35)
0.213;-31618.8
35(37)
0.174;-34712.5
3359
0.178;-37525.0
33(5Q)
0.204;-31618.8
(36)(37)
0.216;-30043.7
3(36T)
0.185;-32237.5
3Q(36)
0.240;-31000.0
36(38)
0.176;-33475.0
336T
0.167;-36287.5
33(6K)
0.223;-30381.2
(37)(39)
0.243;-28187.5
3(37Q)
0.270;-30381.2
33(78)
0.178;-32856.2
37(3J)
0.214;-31000.0
337K
0.193;-33812.5
3T(38)
0.194;-31000.0
(38)(3K)
0.221;-25093.7
338T
0.177;-35050.0
33(8K)
0.248;-29143.7
(39)(3J)
0.229;-25712.5
3399
0.185;-31000.0
33(9Q)
0.225;-29143.7
(3T)(3J)
0.281;-25093.7
33TT
0.195;-29762.5
33(TK)
0.241;-27906.2
(3J)(3K)
0.259;-23237.5
33JK
0.233;-31337.5
33(QK)
0.224;-26668.8
45(34)
0.218;-35950.0
(34)(48)
0.237;-30043.7
4(34J)
0.219;-32237.5
4K(34)
0.217;-31000.0
(3459)
0.151;-36906.2
(345K)
0.236;-34431.2
57(34)
0.138;-38143.8
(34)(5T)
0.241;-32237.5
5(34K)
0.223;-34431.2
(3469)
0.202;-36287.5
(346K)
0.160;-33812.5
68(34)
0.167;-36906.2
(34)(6J)
0.211;-31000.0
7(347)
0.246;-32856.2
J(347)
0.185;-34431.2
78(34)
0.167;-36287.5
(34)(7J)
0.212;-30381.2
8(348)
0.173;-31618.8
Q(348)
0.174;-33193.8
(34)(8T)
0.197;-30381.2
8(34K)
0.180;-32575.0
(349Q)
0.256;-32575.0
9(34J)
0.192;-33193.8
9K(34)
0.240;-31956.2
TT(34)
0.170;-29143.7
(34)(TK)
0.205;-27287.5
J(34Q)
0.209;-31337.5
K(34Q)
0.187;-30100.0
44(35)
0.186;-35950.0
3447
0.165;-38762.5
34(4T)
0.236;-32856.2
44(3K)
0.193;-31000.0
4(357)
0.224;-38143.8
49(35)
0.190;-36906.2
(35)(4Q)
0.258;-31000.0
36(45)
0.186;-38762.5
3(459)
0.177;-36906.2
(45)(3Q)
0.241;-31000.0
35(46)
0.170;-38762.5
35(48)
0.218;-37525.0
35(4T)
0.169;-36287.5
35(4Q)
0.235;-35050.0
46(36)
0.197;-34093.8
(36)(49)
0.222;-32237.5
4(36Q)
0.233;-34431.2
3(467)
0.173;-37525.0
(46)(3T)
0.204;-31618.8
3Q(46)
0.175;-34431.2
3467
0.118;-41575.0
3469
0.136;-40337.5
346J
0.154;-39100.0
346K
0.140;-37862.5
49(37)
0.208;-35668.8
(37)(4Q)
0.245;-29762.5
38(47)
0.187;-36287.5
3(47J)
0.245;-34431.2
3477
0.175;-36906.2
3479
0.149;-39718.8
347J
0.201;-38481.2
347K
0.139;-37243.8
4T(38)
0.192;-34431.2
(38)(4K)
0.175;-28525.0
3T(48)
0.196;-34431.2
3(48K)
0.181;-32575.0
38(4T)
0.168;-34431.2
38(4Q)
0.191;-33193.8
49(39)
0.221;-30381.2
(39)(4Q)
0.221;-28525.0
3T(49)
0.215;-33812.5
3(49K)
0.172;-31956.2
39(4J)
0.255;-33193.8
39(4K)
0.174;-31956.2
4(3TQ)
0.220;-31956.2
3(4TJ)
0.206;-32575.0
34TT
0.214;-33193.8
34TQ
0.150;-36006.2
(3J)(4Q)
0.250;-27287.5
3Q(4J)
0.203;-31337.5
34JQ
0.186;-35387.5
(3Q)(4K)
0.203;-26050.0
3Q(4K)
0.182;-30100.0
5(356)
0.198;-34093.8
58(35)
0.162;-32856.2
(35)(5J)
0.190;-26950.0
6(356)
0.197;-33475.0
T(356)
0.234;-35050.0
6(357)
0.175;-36906.2
69(35)
0.179;-35668.8
(35)(6Q)
0.192;-29762.5
(3579)
0.188;-35050.0
(357K)
0.164;-32575.0
79(35)
0.202;-35050.0
(35)(7Q)
0.203;-29143.8
(358T)
0.192;-33812.5
88(35)
0.211;-31000.0
(35)(8J)
0.207;-29143.8
9(359)
0.214;-29762.5
K(359)
0.202;-31337.5
9(35Q)
0.212;-31956.2
J(35T)
0.197;-31956.2
TJ(35)
0.186;-31956.2
(35JQ)
0.194;-30718.8
J(35K)
0.275;-30100.0
(35)(QK)
0.283;-25431.2
55(37)
0.146;-33475.0
3559
0.228;-36287.5
35(5Q)
0.209;-30381.2
(36)(57)
0.181;-32856.2
5(36T)
0.245;-35050.0
5Q(36)
0.158;-33812.5
(56)(38)
0.232;-32237.5
3T(56)
0.198;-35050.0
3(56K)
0.208;-33193.8
36(58)
0.197;-36287.5
36(5T)
0.181;-35050.0
36(5Q)
0.197;-33812.5
57(37)
0.201;-32237.5
(37)(5T)
0.204;-30381.2
5(37K)
0.203;-32575.0
3(579)
0.190;-35050.0
(57)(3Q)
0.260;-29143.8
37(58)
0.145;-35668.8
37(5T)
0.230;-34431.2
37(5Q)
0.157;-33193.8
58(38)
0.206;-31000.0
(38)(5J)
0.210;-29143.8
38(58)
0.205;-31000.0
3(58J)
0.224;-33193.8
3588
0.191;-35050.0
358T
0.138;-37862.5
358Q
0.151;-36625.0
(39)(5T)
0.206;-29143.8
5(39K)
0.197;-31337.5
3(59J)
0.163;-32575.0
3599
0.195;-33812.5
359J
0.172;-36625.0
359K
0.155;-35387.5
5Q(3T)
0.253;-31337.5
(5T)(3Q)
0.260;-27287.5
3T(5J)
0.167;-31956.2
3T(5K)
0.236;-30718.8
5(3JK)
0.200;-30100.0
3(5JK)
0.199;-30100.0
3J(5K)
0.212;-30100.0
3Q(5Q)
0.227;-26050.0
35QK
0.185;-33531.2
67(36)
0.188;-32237.5
(36)(6T)
0.263;-26331.2
6(36K)
0.268;-28525.0
(367T)
0.182;-33812.5
77(36)
0.250;-31618.8
(36)(7T)
0.179;-29762.5
7(36K)
0.161;-31956.2
(368J)
0.210;-32575.0
(36)(89)
0.176;-29762.5
8(36Q)
0.163;-31956.2
T(369)
0.216;-32575.0
9(36T)
0.180;-32575.0
9Q(36)
0.190;-31337.5
Q(36T)
0.255;-30718.8
(36)(TQ)
0.238;-26668.8
(36JK)
0.174;-29481.2
JK(36)
0.269;-29481.2
K(36K)
0.246;-24193.7
3668
0.161;-35668.8
36(6J)
0.176;-29762.5
(37)(67)
0.245;-27568.8
6(37T)
0.179;-33812.5
6Q(37)
0.225;-32575.0
(67)(39)
0.206;-30381.2
3J(67)
0.253;-33193.8
67(38)
0.181;-35050.0
67(3T)
0.201;-33812.5
67(3Q)
0.217;-32575.0
(38)(68)
0.193;-26331.2
6(38J)
0.191;-32575.0
6K(38)
0.212;-31337.5
(68)(3J)
0.208;-28525.0
3K(68)
0.195;-31337.5
36(8T)
0.254;-33193.8
36(8Q)
0.238;-31956.2
6(39T)
0.201;-32575.0
6Q(39)
0.230;-31337.5
(69)(3J)
0.174;-27906.2
3K(69)
0.270;-30718.8
36(9J)
0.186;-31956.2
36(9K)
0.179;-30718.8
(3T)(6Q)
0.274;-26668.8
3J(6T)
0.197;-31337.5
6T(3J)
0.243;-31337.5
6T(3K)
0.197;-30100.0
6Q(3J)
0.210;-30100.0
(6J)(3K)
0.315;-25431.2
6J(3K)
0.235;-29481.2
6K(3Q)
0.195;-28862.5
36(QK)
0.171;-28862.5
(37)(78)
0.193;-26331.2
7(37J)
0.230;-28525.0
7K(37)
0.189;-27287.5
(378Q)
0.187;-31337.5
8(37T)
0.222;-32575.0
8Q(37)
0.209;-31337.5
J(379)
0.164;-31337.5
9T(37)
0.211;-31956.2
(37)(9K)
0.242;-26050.0
K(37T)
0.215;-29481.2
T(37K)
0.191;-29481.2
JJ(37)
0.259;-26050.0
(37QK)
0.215;-28243.8
3777
0.258;-31000.0
37(7T)
0.213;-29143.7
77(3K)
0.218;-27287.5
7(38T)
0.198;-32575.0
7Q(38)
0.199;-31337.5
(78)(3T)
0.221;-28525.0
3Q(78)
0.168;-31337.5
3789
0.167;-37243.8
378J
0.201;-36006.2
378K
0.198;-34768.8
7J(39)
0.184;-31337.5
(79)(3T)
0.226;-27906.2
3Q(79)
0.235;-30718.8
379T
0.178;-36006.2
379Q
0.181;-34768.8
(3T)(7J)
0.216;-26668.8
3T(7T)
0.209;-27287.5
3(7TK)
0.196;-29481.2
3T(7Q)
0.201;-30100.0
7J(3J)
0.222;-26050.0
(7J)(3Q)
0.250;-25431.2
3J(7Q)
0.199;-29481.2
7Q(3Q)
0.241;-24812.5
37QQ
0.248;-28862.5
37KK
0.198;-27625.0
8(38J)
0.278;-27287.5
8K(38)
0.257;-26050.0
(389K)
0.193;-29481.2
9J(38)
0.220;-30718.8
(38TJ)
0.187;-30100.0
(38)(TJ)
0.219;-26050.0
J(38J)
0.297;-25431.2
JQ(38)
0.224;-28862.5
Q(38K)
0.302;-27625.0
3889
0.172;-32575.0
38(8Q)
0.269;-26668.8
(39)(8T)
0.215;-27287.5
8(39K)
0.204;-29481.2
3(89J)
0.230;-30718.8
3899
0.206;-31956.2
389J
0.197;-34768.8
389K
0.186;-33531.2
8Q(3T)
0.255;-29481.2
(8T)(3Q)
0.216;-25431.2
3T(8J)
0.200;-30100.0
3T(8K)
0.189;-28862.5
8(3JK)
0.225;-28243.8
3(8JK)
0.224;-28243.8
3J(8K)
0.225;-28243.8
3Q(8Q)
0.237;-24193.7
38QK
0.215;-31675.0
9T(39)
0.230;-26668.8
(39)(9K)
0.261;-20762.5
K(39T)
0.222;-28243.8
T(39K)
0.280;-28243.8
JJ(39)
0.220;-24812.5
(39QK)
0.186;-27006.2
3999
0.237;-27287.5
39(9Q)
0.218;-25431.2
(3T)(9J)
0.262;-25431.2
3T(9T)
0.246;-26050.0
3(9TK)
0.187;-28243.8
3T(9Q)
0.192;-28862.5
9J(3J)
0.257;-24812.5
(9J)(3Q)
0.217;-24193.8
3J(9Q)
0.203;-28243.8
9Q(3Q)
0.295;-23575.0
39QQ
0.240;-27625.0
39KK
0.189;-26387.5
T(3TK)
0.284;-23575.0
JJ(3T)
0.232;-24193.7
(3TQK)
0.228;-26387.5
3TTT
0.223;-25431.2
3T(TK)
0.323;-23575.0
(3J)(TK)
0.240;-22956.2
3K(TJ)
0.252;-27006.2
3T(JK)
0.296;-27006.2
(TQ)(3K)
0.281;-22337.5
(3K)(TK)
0.308;-17668.7
J(3JK)
0.225;-22337.5
(3J)(QK)
0.280;-21718.7
JJ(3K)
0.263;-22337.5
3Q(JQ)
0.261;-22337.5
3JQK
0.232;-29818.7
QK(3Q)
0.252;-21100.0
QK(3K)
0.275;-20481.2
44(46)
0.254;-30662.5
44(4T)
0.240;-28187.5
(45)(45)
0.232;-26612.5
4(458)
0.174;-32856.2
4T(45)
0.180;-31618.8
(45)(4K)
0.245;-25712.5
4457
0.147;-37525.0
44(5T)
0.216;-31618.8
45(4K)
0.208;-29762.5
4(468)
0.185;-32237.5
4T(46)
0.169;-31000.0
(46)(4K)
0.245;-25093.7
4468
0.188;-36287.5
44(6J)
0.174;-30381.2
(47)(47)
0.214;-24137.5
4(47T)
0.252;-30381.2
4Q(47)
0.199;-29143.7
47(49)
0.206;-31000.0
447J
0.223;-33812.5
48(48)
0.279;-26950.0
(48)(4J)
0.279;-25093.7
4488
0.236;-31000.0
44(8J)
0.272;-29143.7
(49)(49)
0.267;-21662.5
4(49Q)
0.260;-27906.2
44(9T)
0.229;-29143.7
49(4K)
0.269;-27287.5
4(4TQ)
0.235;-27287.5
44(TJ)
0.216;-27906.2
(4J)(4J)
0.259;-19187.5
44JJ
0.195;-27287.5
4Q(4Q)
0.249;-22000.0
(4K)(4K)
0.285;-16712.5
(45)(57)
0.222;-28806.3
5(45T)
0.177;-31000.0
5Q(45)
0.213;-29762.5
8(456)
0.160;-35668.8
Q(456)
0.160;-33193.8
(45)(68)
0.232;-31618.8
6(45J)
0.219;-33812.5
6K(45)
0.239;-32575.0
(457J)
0.168;-33193.8
(45)(78)
0.267;-31000.0
7(45J)
0.198;-33193.8
7K(45)
0.161;-31956.2
(458Q)
0.210;-31956.2
8(45T)
0.184;-33193.8
8Q(45)
0.168;-31956.2
J(459)
0.229;-31956.2
9T(45)
0.193;-32575.0
(45)(9K)
0.228;-26668.8
K(45T)
0.278;-30100.0
T(45K)
0.225;-30100.0
JJ(45)
0.240;-26668.8
(45QK)
0.172;-28862.5
4555
0.160;-34093.8
45(58)
0.179;-32237.5
55(4J)
0.221;-30381.2
455K
0.200;-33193.8
58(46)
0.199;-35668.8
(46)(5J)
0.210;-29762.5
46(56)
0.225;-32856.2
4(569)
0.218;-35050.0
(56)(4Q)
0.197;-29143.8
46(57)
0.205;-36287.5
46(59)
0.225;-35050.0
46(5J)
0.177;-33812.5
46(5K)
0.193;-32575.0
5(479)
0.195;-34431.2
5J(47)
0.204;-33193.8
(57)(48)
0.186;-31000.0
4T(57)
0.182;-33812.5
4(57K)
0.155;-31956.2
47(59)
0.200;-34431.2
47(5J)
0.208;-33193.8
47(5K)
0.244;-31956.2
5(48T)
0.215;-33193.8
5Q(48)
0.196;-31956.2
(58)(4T)
0.220;-29143.8
4Q(58)
0.196;-31956.2
4589
0.227;-37862.5
458J
0.176;-36625.0
458K
0.188;-35387.5
5J(49)
0.190;-31956.2
(59)(4T)
0.180;-28525.0
4Q(59)
0.214;-31337.5
459T
0.158;-36625.0
459Q
0.165;-35387.5
(4T)(5J)
0.204;-27287.5
4T(5T)
0.213;-27906.2
4(5TK)
0.219;-30100.0
4T(5Q)
0.217;-30718.8
5J(4J)
0.179;-26668.8
(5J)(4Q)
0.274;-26050.0
4J(5Q)
0.168;-30100.0
5Q(4Q)
0.179;-25431.2
45QQ
0.223;-29481.2
45KK
0.178;-28243.8
6(469)
0.157;-30381.2
6J(46)
0.231;-29143.7
(4678)
0.168;-34431.2
(467Q)
0.216;-31956.2
7(469)
0.176;-33812.5
7J(46)
0.189;-32575.0
(4689)
0.199;-33193.8
(468K)
0.221;-30718.8
8T(46)
0.220;-32575.0
(46)(8K)
0.251;-26668.8
Q(469)
0.242;-30718.8
(46)(9J)
0.224;-27287.5
T(46T)
0.246;-27287.5
T(46J)
0.204;-30718.8
TK(46)
0.272;-29481.2
(46)(JQ)
0.297;-25431.2
QQ(46)
0.264;-24812.5
46(67)
0.221;-31618.8
66(4T)
0.233;-29762.5
466Q
0.180;-32575.0
68(47)
0.159;-34431.2
(47)(6J)
0.208;-28525.0
47(67)
0.161;-31000.0
4(67T)
0.161;-33193.8
(67)(4K)
0.262;-27287.5
67(49)
0.189;-33812.5
67(4J)
0.200;-32575.0
67(4K)
0.177;-31337.5
69(48)
0.158;-33193.8
(48)(6Q)
0.197;-27287.5
49(68)
0.190;-33193.8
4(68Q)
0.241;-31337.5
46(89)
0.218;-33193.8
46(8J)
0.177;-31956.2
46(8K)
0.194;-30718.8
(49)(6J)
0.233;-27287.5
49(69)
0.205;-28525.0
4(69Q)
0.207;-30718.8
46(9T)
0.197;-31956.2
46(9Q)
0.235;-30718.8
6(4TJ)
0.194;-30718.8
6K(4T)
0.199;-29481.2
(6T)(4K)
0.258;-25431.2
6T(4Q)
0.199;-30100.0
(4J)(6J)
0.277;-22000.0
4J(6J)
0.300;-26050.0
6J(4Q)
0.275;-29481.2
(4Q)(6Q)
0.318;-20762.5
4K(6Q)
0.228;-28243.8
4K(6K)
0.294;-23575.0
79(47)
0.223;-29143.7
(47)(7Q)
0.289;-23237.5
(478T)
0.211;-31956.2
88(47)
0.233;-29143.7
(47)(8J)
0.261;-27287.5
9(479)
0.187;-27906.2
K(479)
0.202;-29481.2
9(47Q)
0.213;-30100.0
J(47T)
0.238;-30100.0
TJ(47)
0.244;-30100.0
(47JQ)
0.192;-28862.5
J(47K)
0.248;-28243.8
(47)(QK)
0.263;-23575.0
77(49)
0.249;-29143.7
477J
0.236;-31956.2
78(48)
0.244;-29143.7
(48)(7J)
0.252;-27287.5
48(78)
0.169;-29143.7
4(78J)
0.162;-31337.5
4788
0.204;-33193.8
478T
0.186;-36006.2
478Q
0.173;-34768.8
(49)(7T)
0.254;-27287.5
7(49K)
0.255;-29481.2
4(79J)
0.203;-30718.8
4799
0.206;-31956.2
479J
0.167;-34768.8
479K
0.217;-33531.2
7Q(4T)
0.192;-29481.2
(7T)(4Q)
0.183;-25431.2
4T(7J)
0.214;-30100.0
4T(7K)
0.212;-28862.5
7(4JK)
0.230;-28243.8
4(7JK)
0.192;-28243.8
4J(7K)
0.245;-28243.8
4Q(7Q)
0.236;-24193.7
47QK
0.183;-31675.0
89(48)
0.206;-27906.2
(48)(8Q)
0.264;-22000.0
(489J)
0.197;-30100.0
(48)(9T)
0.276;-26668.8
9(48K)
0.196;-28862.5
(48TK)
0.221;-28243.8
TQ(48)
0.244;-28862.5
K(48J)
0.249;-27625.0
Q(48Q)
0.305;-23575.0
KK(48)
0.259;-22337.5
88(4J)
0.242;-26668.8
488K
0.215;-29481.2
8J(49)
0.176;-30100.0
(89)(4T)
0.252;-26668.8
4Q(89)
0.220;-29481.2
489T
0.177;-34768.8
489Q
0.169;-33531.2
(4T)(8J)
0.300;-25431.2
4T(8T)
0.247;-26050.0
4(8TK)
0.235;-28243.8
4T(8Q)
0.259;-28862.5
8J(4J)
0.235;-24812.5
(8J)(4Q)
0.312;-24193.8
4J(8Q)
0.256;-28243.8
8Q(4Q)
0.211;-23575.0
48QQ
0.221;-27625.0
48KK
0.274;-26387.5
9(49Q)
0.266;-24812.5
J(49T)
0.226;-28862.5
TJ(49)
0.226;-28862.5
(49JQ)
0.206;-27625.0
J(49K)
0.243;-27006.2
(49)(QK)
0.237;-22337.5
99(4J)
0.232;-25431.2
499K
0.236;-28243.8
9Q(4T)
0.212;-28243.8
(9T)(4Q)
0.260;-24193.8
4T(9J)
0.208;-28862.5
4T(9K)
0.208;-27625.0
9(4JK)
0.270;-27006.2
4(9JK)
0.198;-27006.2
4J(9K)
0.230;-27006.2
4Q(9Q)
0.249;-22956.2
49QK
0.247;-30437.5
TJ(4T)
0.204;-24193.7
(4TJQ)
0.223;-27006.2
J(4TK)
0.241;-26387.5
(4T)(QK)
0.247;-21718.7
TT(4Q)
0.257;-23575.0
T(4JQ)
0.226;-27006.2
4(TJQ)
0.198;-27006.2
4T(JQ)
0.260;-27006.2
T(4QK)
0.230;-25768.7
TQ(4K)
0.213;-25768.7
JJ(4J)
0.269;-18906.3
(4JQK)
0.233;-25150.0
4JJJ
0.264;-22956.2
JQ(4Q)
0.246;-21718.7
4JQQ
0.210;-25768.7
4JKK
0.254;-24531.2
QQ(4K)
0.246;-20481.2
4KKK
0.261;-19243.8
55(59)
0.228;-26950.0
55(5K)
0.186;-24475.0
(56)(58)
0.254;-26950.0
5(56J)
0.184;-29143.7
5K(56)
0.203;-27906.2
56(59)
0.237;-30381.2
556J
0.177;-33193.8
57(57)
0.235;-26950.0
(57)(5T)
0.248;-25093.7
5(57K)
0.218;-27287.5
55(79)
0.200;-29762.5
57(5Q)
0.187;-27906.2
5(589)
0.216;-29143.7
5J(58)
0.189;-27906.2
58(59)
0.206;-29143.7
558J
0.216;-31956.2
59(59)
0.272;-24475.0
(59)(5Q)
0.267;-22618.8
559T
0.238;-31956.2
55(9K)
0.185;-26050.0
(5T)(5Q)
0.245;-22000.0
55TJ
0.261;-30718.8
5J(5J)
0.245;-22000.0
5J(5Q)
0.273;-25431.2
5(5QK)
0.245;-24193.7
5K(5K)
0.272;-19525.0
68(56)
0.233;-30381.2
(56)(6J)
0.268;-24475.0
7(567)
0.216;-30381.2
J(567)
0.182;-31956.2
78(56)
0.170;-33812.5
(56)(7J)
0.255;-27906.2
8(568)
0.164;-29143.7
Q(568)
0.196;-30718.8
(56)(8T)
0.226;-27906.2
8(56K)
0.250;-30100.0
(569Q)
0.243;-30100.0
9(56J)
0.215;-30718.8
9K(56)
0.200;-29481.2
TT(56)
0.280;-26668.8
(56)(TK)
0.217;-24812.5
J(56Q)
0.231;-28862.5
K(56Q)
0.255;-27625.0
66(57)
0.224;-31000.0
5669
0.212;-33812.5
56(6Q)
0.217;-27906.2
(57)(68)
0.233;-29762.5
6(57J)
0.218;-31956.2
6K(57)
0.190;-30718.8
(67)(5T)
0.201;-28525.0
5Q(67)
0.217;-31337.5
5678
0.219;-37862.5
567T
0.178;-36625.0
567Q
0.163;-35387.5
(58)(69)
0.228;-28525.0
6(58Q)
0.234;-30718.8
5(689)
0.218;-32575.0
(68)(5Q)
0.208;-26668.8
58(69)
0.224;-32575.0
58(6J)
0.228;-31337.5
58(6K)
0.168;-30100.0
6(59J)
0.244;-30718.8
6K(59)
0.211;-29481.2
(69)(5Q)
0.272;-26050.0
59(6T)
0.189;-31337.5
59(6Q)
0.267;-30100.0
6T(5T)
0.209;-26668.8
(5T)(6K)
0.311;-24812.5
5Q(6T)
0.225;-29481.2
56TJ
0.183;-34150.0
56TK
0.191;-32912.5
6K(5J)
0.249;-28243.8
56JJ
0.218;-29481.2
56JK
0.184;-32293.8
5(6QK)
0.205;-27625.0
6K(5K)
0.230;-22956.2
(57)(79)
0.235;-24475.0
7(57Q)
0.234;-26668.8
9(578)
0.168;-31956.2
K(578)
0.215;-29481.2
8(57J)
0.281;-30718.8
8K(57)
0.248;-29481.2
(579K)
0.227;-28862.5
9J(57)
0.244;-30100.0
(57TJ)
0.207;-29481.2
(57)(TJ)
0.281;-25431.2
J(57J)
0.230;-24812.5
JQ(57)
0.222;-28243.8
Q(57K)
0.192;-27006.2
5778
0.202;-33193.8
57(7J)
0.216;-27287.5
(58)(78)
0.283;-24475.0
7(58J)
0.177;-30718.8
7K(58)
0.261;-29481.2
(78)(5J)
0.309;-26668.8
5K(78)
0.182;-29481.2
57(8T)
0.179;-31337.5
57(8Q)
0.207;-30100.0
7(59T)
0.219;-30718.8
7Q(59)
0.259;-29481.2
(79)(5J)
0.279;-26050.0
5K(79)
0.279;-28862.5
57(9J)
0.226;-30100.0
57(9K)
0.213;-28862.5
(5T)(7Q)
0.196;-24812.5
5J(7T)
0.221;-29481.2
7T(5J)
0.273;-29481.2
7T(5K)
0.207;-28243.8
7Q(5J)
0.173;-28243.8
(7J)(5K)
0.262;-23575.0
7J(5K)
0.233;-27625.0
7K(5Q)
0.297;-27006.2
57(QK)
0.228;-27006.2
(58)(89)
0.311;-23237.5
8(58Q)
0.179;-25431.2
T(589)
0.245;-30100.0
9(58T)
0.236;-30100.0
9Q(58)
0.224;-28862.5
Q(58T)
0.235;-28243.8
(58)(TQ)
0.266;-24193.8
(58JK)
0.234;-27006.2
JK(58)
0.250;-27006.2
K(58K)
0.221;-21718.7
588T
0.253;-30718.8
58(8K)
0.247;-24812.5
(59)(8J)
0.224;-25431.2
59(89)
0.217;-26668.8
5(89Q)
0.244;-28862.5
58(9T)
0.183;-30100.0
58(9Q)
0.202;-28862.5
8(5TJ)
0.250;-28862.5
8K(5T)
0.183;-27625.0
(8T)(5K)
0.255;-23575.0
8T(5Q)
0.207;-28243.8
(5J)(8J)
0.354;-20143.7
5J(8J)
0.245;-24193.7
8J(5Q)
0.171;-27625.0
(5Q)(8Q)
0.243;-18906.3
5K(8Q)
0.238;-26387.5
5K(8K)
0.255;-21718.7
9J(59)
0.261;-24812.5
(59TJ)
0.267;-28243.8
(59)(TJ)
0.281;-24193.8
J(59J)
0.279;-23575.0
JQ(59)
0.209;-27006.2
Q(59K)
0.252;-25768.7
599T
0.202;-29481.2
59(9K)
0.291;-23575.0
(5T)(9Q)
0.212;-23575.0
5J(9T)
0.220;-28243.8
9T(5J)
0.218;-28243.8
9T(5K)
0.280;-27006.2
9Q(5J)
0.274;-27006.2
(9J)(5K)
0.292;-22337.5
9J(5K)
0.280;-26387.5
9K(5Q)
0.223;-25768.7
59(QK)
0.238;-25768.7
(5T)(TJ)
0.280;-19525.0
J(5TJ)
0.217;-22956.2
JQ(5T)
0.238;-26387.5
Q(5TK)
0.232;-25150.0
5TTJ
0.238;-27625.0
TJ(5J)
0.257;-22956.2
(TJ)(5Q)
0.242;-22337.5
5J(TQ)
0.247;-26387.5
TQ(5Q)
0.290;-21718.7
5TQQ
0.199;-25768.7
5TKK
0.281;-24531.2
Q(5JQ)
0.308;-21100.0
KK(5J)
0.280;-19862.5
(5Q)(JQ)
0.271;-17050.0
5K(JQ)
0.190;-24531.2
5K(JK)
0.273;-19862.5
5QQQ
0.225;-20481.2
KK(5K)
0.337;-14575.0
6669
0.212;-29143.8
666K
0.247;-26668.8
69(67)
0.224;-28525.0
(67)(6Q)
0.275;-22618.8
6678
0.198;-33193.8
66(7J)
0.228;-27287.5
(68)(68)
0.222;-20425.0
6(68J)
0.251;-26668.8
6K(68)
0.311;-25431.2
68(6J)
0.216;-26668.8
668K
0.220;-29481.2
6J(69)
0.219;-26050.0
69(6T)
0.231;-26668.8
669Q
0.228;-29481.2
6J(6T)
0.235;-25431.2
6T(6J)
0.235;-25431.2
66TK
0.218;-28243.8
6K(6J)
0.319;-23575.0
(6Q)(6Q)
0.273;-15475.0
66QK
0.241;-27006.2
7(679)
0.267;-27906.2
7J(67)
0.285;-26668.8
(6789)
0.234;-31337.5
(678K)
0.228;-28862.5
8T(67)
0.194;-30718.8
(67)(8K)
0.215;-24812.5
Q(679)
0.254;-28862.5
(67)(9J)
0.266;-25431.2
T(67T)
0.245;-25431.2
T(67J)
0.202;-28862.5
TK(67)
0.201;-27625.0
(67)(JQ)
0.249;-23575.0
QQ(67)
0.251;-22956.2
67(78)
0.199;-28525.0
77(6J)
0.232;-26668.8
677K
0.251;-29481.2
7T(68)
0.215;-30718.8
(68)(7K)
0.223;-24812.5
6T(78)
0.215;-30718.8
6(78K)
0.226;-28862.5
68(7T)
0.226;-30718.8
68(7Q)
0.193;-29481.2
79(69)
0.290;-26668.8
(69)(7Q)
0.234;-24812.5
6T(79)
0.167;-30100.0
6(79K)
0.265;-28243.8
69(7J)
0.231;-29481.2
69(7K)
0.188;-28243.8
7(6TQ)
0.250;-28243.8
6(7TJ)
0.229;-28862.5
67TT
0.225;-29481.2
67TQ
0.157;-32293.8
(6J)(7Q)
0.247;-23575.0
6Q(7J)
0.232;-27625.0
67JQ
0.219;-31675.0
(6Q)(7K)
0.320;-22337.5
6Q(7K)
0.224;-26387.5
8(689)
0.215;-26668.8
8J(68)
0.263;-25431.2
(689T)
0.250;-29481.2
99(68)
0.207;-26050.0
(68)(9Q)
0.255;-24193.8
(68TQ)
0.221;-27625.0
T(68Q)
0.203;-27625.0
Q(68J)
0.214;-27006.2
(68)(JK)
0.266;-22337.5
QK(68)
0.267;-25768.7
68(8T)
0.242;-26050.0
88(6K)
0.301;-24193.7
8(69J)
0.210;-28862.5
8K(69)
0.226;-27625.0
(89)(6Q)
0.250;-24193.8
69(8T)
0.253;-29481.2
69(8Q)
0.218;-28243.8
8T(6T)
0.241;-24812.5
(6T)(8K)
0.293;-22956.2
6Q(8T)
0.231;-27625.0
68TJ
0.223;-32293.8
68TK
0.207;-31056.2
8K(6J)
0.223;-26387.5
68JJ
0.235;-27625.0
68JK
0.214;-30437.5
6(8QK)
0.312;-25768.7
8K(6K)
0.273;-21100.0
(69)(9J)
0.313;-20143.7
T(69T)
0.272;-24193.7
T(69J)
0.203;-27625.0
TK(69)
0.177;-26387.5
(69)(JQ)
0.257;-22337.5
QQ(69)
0.303;-21718.7
69(9T)
0.229;-24812.5
99(6K)
0.264;-22956.2
9(6TQ)
0.254;-27006.2
6(9TJ)
0.205;-27625.0
69TT
0.213;-28243.8
69TQ
0.217;-31056.2
(6J)(9Q)
0.260;-22337.5
6Q(9J)
0.244;-26387.5
69JQ
0.187;-30437.5
(6Q)(9K)
0.240;-21100.0
6Q(9K)
0.279;-25150.0
T(6TJ)
0.313;-22956.2
TK(6T)
0.322;-21718.7
(6T)(JQ)
0.270;-21718.7
QQ(6T)
0.334;-21100.0
6T(TJ)
0.225;-22956.2
(6J)(TJ)
0.290;-18287.5
6J(TJ)
0.332;-22337.5
TJ(6Q)
0.214;-25768.7
(6Q)(TQ)
0.320;-17050.0
6K(TQ)
0.249;-24531.2
6K(TK)
0.287;-19862.5
JK(6J)
0.252;-20481.2
K(6JK)
0.289;-19243.8
6JJK
0.232;-24531.2
6(JQK)
0.195;-23912.5
JK(6K)
0.241;-19243.8
KK(6Q)
0.276;-18625.0
6QKK
0.294;-22675.0
77(7T)
0.312;-22618.8
(78)(78)
0.298;-19187.5
7(78J)
0.278;-25431.2
7K(78)
0.253;-24193.7
78(7J)
0.266;-25431.2
778K
0.205;-28243.8
7J(79)
0.278;-24812.5
79(7T)
0.304;-25431.2
779Q
0.240;-28243.8
7J(7T)
0.281;-24193.7
7T(7J)
0.307;-24193.7
77TK
0.208;-27006.2
7K(7J)
0.254;-22337.5
(7Q)(7Q)
0.359;-14237.5
77QK
0.214;-25768.7
8(78T)
0.240;-25431.2
8Q(78)
0.298;-24193.7
J(789)
0.205;-28243.8
9T(78)
0.246;-28862.5
(78)(9K)
0.276;-22956.2
K(78T)
0.182;-26387.5
T(78K)
0.202;-26387.5
JJ(78)
0.229;-22956.2
(78QK)
0.247;-25150.0
7888
0.230;-26668.8
78(8J)
0.218;-24812.5
(79)(89)
0.274;-21381.2
8(79Q)
0.217;-27625.0
7(89T)
0.217;-28862.5
(89)(7K)
0.248;-22956.2
89(7J)
0.213;-28243.8
89(7K)
0.220;-27006.2
8J(7T)
0.188;-27625.0
(8T)(7J)
0.281;-23575.0
7K(8T)
0.253;-26387.5
78(TQ)
0.242;-27006.2
8(7JQ)
0.186;-26387.5
7(8JQ)
0.215;-26387.5
78(JQ)
0.292;-26387.5
8(7QK)
0.243;-25150.0
8Q(7K)
0.251;-25150.0
99(79)
0.274;-20762.5
(79)(9Q)
0.266;-18906.3
(79TQ)
0.218;-26387.5
T(79Q)
0.236;-26387.5
Q(79J)
0.248;-25768.7
(79)(JK)
0.317;-21100.0
QK(79)
0.231;-24531.2
79(9J)
0.254;-23575.0
(7T)(9T)
0.289;-19525.0
9(7TK)
0.285;-25768.7
7(9TQ)
0.236;-26387.5
79(TJ)
0.259;-27006.2
79(TK)
0.186;-25768.7
(7J)(9K)
0.294;-21100.0
7K(9J)
0.262;-25150.0
79(JK)
0.246;-25150.0
(9Q)(7K)
0.345;-20481.2
(7K)(9K)
0.316;-15812.5
T(7TQ)
0.222;-21718.7
Q(7TJ)
0.301;-25150.0
(7T)(JK)
0.293;-20481.2
QK(7T)
0.241;-23912.5
7T(TQ)
0.303;-21718.7
(7J)(TQ)
0.260;-21100.0
7Q(TJ)
0.221;-25150.0
7TJQ
0.191;-29200.0
(7Q)(TK)
0.302;-19862.5
7Q(TK)
0.237;-23912.5
J(7JQ)
0.288;-20481.2
K(7JQ)
0.270;-23293.8
JJ(7Q)
0.305;-20481.2
J(7QK)
0.245;-23293.8
JQ(7K)
0.266;-23293.8
QQ(7Q)
0.274;-15193.8
7Q(QK)
0.244;-18625.0
8888
0.273;-22000.0
888Q
0.242;-23575.0
8(89J)
0.292;-23575.0
8K(89)
0.261;-22337.5
89(8Q)
0.252;-22956.2
8(8TJ)
0.303;-22956.2
8K(8T)
0.247;-21718.7
8T(8K)
0.239;-21718.7
8(8JK)
0.250;-21100.0
88(JK)
0.310;-21100.0
8Q(8K)
0.274;-20481.2
(89)(9T)
0.271;-19525.0
9(89K)
0.239;-21718.7
(89TK)
0.256;-25150.0
TQ(89)
0.270;-25768.7
K(89J)
0.218;-24531.2
Q(89Q)
0.323;-20481.2
KK(89)
0.276;-19243.8
99(8Q)
0.247;-22337.5
9(8TJ)
0.292;-26387.5
9K(8T)
0.221;-25150.0
(9T)(8K)
0.258;-21100.0
9T(8Q)
0.191;-25768.7
(8J)(9J)
0.302;-17668.7
8J(9J)
0.261;-21718.7
9J(8Q)
0.204;-25150.0
(8Q)(9Q)
0.317;-16431.2
8K(9Q)
0.284;-23912.5
8K(9K)
0.333;-19243.8
TQ(8T)
0.305;-21100.0
K(8TJ)
0.251;-23912.5
Q(8TQ)
0.243;-19862.5
KK(8T)
0.257;-18625.0
