AAAA
0.277;2442.5
5AAA
0.166;-282.8
9AAA
0.212;418.4
KAAA
0.186;1119.7
4A(2A)
0.100;-2561.9
(2A)(7A)
0.170;-888.4
A(2TA)
0.146;-1510.0
QA(2A)
0.165;-1159.4
2A(4A)
0.082;-2561.9
26AA
0.087;-3358.8
AA(29)
0.126;-1685.3
2A(QA)
0.182;-1159.4
A(34A)
0.118;-2386.6
6A(3A)
0.138;-2035.9
(3A)(9A)
0.203;-362.5
A(3QA)
0.189;-984.1
AA(34)
0.105;-2386.6
3A(7A)
0.117;-1860.6
39AA
0.095;-2657.5
AA(3Q)
0.142;-984.1
(4A)(5A)
0.134;-888.4
A(48A)
0.123;-1510.0
TA(4A)
0.140;-1159.4
(4A)(KA)
0.233;514.1
46AA
0.085;-3008.1
AA(49)
0.152;-1334.7
4A(QA)
0.193;-808.8
A(56A)
0.115;-1685.3
8A(5A)
0.142;-1334.7
(5A)(JA)
0.228;338.8
55AA
0.118;-1860.6
AA(58)
0.134;-1334.7
5A(JA)
0.158;-808.8
5KAA
0.110;-1605.6
8A(6A)
0.157;-1159.4
(6A)(JA)
0.217;514.1
66AA
0.156;-1510.0
AA(69)
0.143;-984.1
6A(QA)
0.180;-458.1
A(78A)
0.177;-984.1
TA(7A)
0.165;-633.4
(7A)(KA)
0.275;1040.0
79AA
0.120;-1956.2
AA(7Q)
0.203;-282.8
(8A)(9A)
0.196;514.1
A(8QA)
0.179;-107.5
AA(89)
0.186;-633.4
8A(QA)
0.238;-107.5
A(9TA)
0.177;-282.8
QA(9A)
0.242;67.8
9A(JA)
0.175;-107.5
9KAA
0.163;-904.4
QA(TA)
0.202;243.1
TA(QA)
0.210;243.1
A(JQA)
0.234;418.4
AA(JQ)
0.186;418.4
(QA)(KA)
0.246;1916.6
KKAA
0.226;944.4
2(25A)
0.055;-4490.3
27(2A)
0.074;-4139.7
(2T)(2A)
0.090;-2466.2
2(2KA)
0.089;-3087.8
(236A)
0.026;-5287.2
(23TA)
0.048;-4585.9
33(2A)
0.043;-4665.6
(36)(2A)
0.074;-4139.7
3(29A)
0.052;-4761.2
3J(2A)
0.042;-4410.6
(245A)
0.032;-5287.2
(249A)
0.054;-4585.9
(24KA)
0.060;-3884.7
46(2A)
0.043;-5111.9
(49)(2A)
0.091;-3438.4
4(2QA)
0.053;-4060.0
6(25A)
0.046;-4936.6
T(25A)
0.049;-4235.3
5(26A)
0.035;-4936.6
58(2A)
0.049;-4585.9
(5J)(2A)
0.094;-2912.5
6(26A)
0.066;-3613.8
T(26A)
0.067;-4060.0
6(27A)
0.058;-4585.9
69(2A)
0.044;-4235.3
(6Q)(2A)
0.094;-2561.9
(279A)
0.059;-4060.0
(27KA)
0.087;-3358.8
79(2A)
0.060;-4060.0
(7Q)(2A)
0.093;-2386.6
(28TA)
0.095;-3709.4
88(2A)
0.098;-2912.5
(8J)(2A)
0.094;-2386.6
9(29A)
0.086;-2561.9
K(29A)
0.107;-3008.1
9(2QA)
0.077;-3183.4
J(2TA)
0.076;-3183.4
TJ(2A)
0.111;-3183.4
(2JQA)
0.121;-2832.8
J(2KA)
0.079;-2657.5
(QK)(2A)
0.145;-1334.7
22(4A)
0.043;-4665.6
226A
0.036;-5462.5
2A(29)
0.054;-3789.1
22(QA)
0.078;-3263.1
2(34A)
0.029;-5637.8
26(3A)
0.038;-5287.2
(29)(3A)
0.070;-3613.8
2(3QA)
0.052;-4235.3
A(234)
0.030;-5637.8
(23)(7A)
0.081;-3964.4
9A(23)
0.053;-4761.2
A(23Q)
0.056;-4235.3
2A(34)
0.035;-5637.8
2A(36)
0.045;-5287.2
2A(38)
0.043;-4936.6
2A(3T)
0.048;-4585.9
2A(3Q)
0.050;-4235.3
2(45A)
0.047;-5287.2
27(4A)
0.043;-4936.6
(2T)(4A)
0.095;-3263.1
2(4KA)
0.067;-3884.7
A(246)
0.046;-5111.9
(24)(9A)
0.076;-3438.4
JA(24)
0.073;-4235.3
24(5A)
0.028;-5287.2
24(7A)
0.043;-4936.6
24(9A)
0.055;-4585.9
24(JA)
0.042;-4235.3
24(KA)
0.058;-3884.7
26(5A)
0.051;-4936.6
(29)(5A)
0.088;-3263.1
2(5QA)
0.069;-3884.7
A(256)
0.037;-4936.6
(25)(9A)
0.080;-3263.1
JA(25)
0.057;-4060.0
25(6A)
0.037;-4936.6
25(8A)
0.039;-4585.9
25(TA)
0.063;-4235.3
25(QA)
0.052;-3884.7
(26)(6A)
0.115;-2466.2
2(69A)
0.074;-4235.3
2J(6A)
0.072;-3884.7
(26)(7A)
0.095;-3438.4
9A(26)
0.057;-4235.3
A(26Q)
0.073;-3709.4
2A(67)
0.054;-4585.9
2A(69)
0.050;-4235.3
2A(6J)
0.064;-3884.7
2A(6K)
0.059;-3534.1
(29)(7A)
0.083;-2912.5
2(7QA)
0.094;-3534.1
A(278)
0.068;-4235.3
(27)(JA)
0.088;-2561.9
KA(27)
0.084;-3358.8
2A(79)
0.056;-4060.0
2A(7J)
0.071;-3709.4
2A(7K)
0.085;-3358.8
(2T)(8A)
0.116;-2561.9
2(8KA)
0.076;-3183.4
A(28T)
0.072;-3709.4
(28)(KA)
0.109;-2035.9
28(TA)
0.060;-3709.4
28(QA)
0.073;-3358.8
(29)(9A)
0.146;-1414.4
2(9QA)
0.072;-3183.4
A(29T)
0.081;-3534.1
(29)(KA)
0.111;-1860.6
29(JA)
0.072;-3358.8
29(KA)
0.097;-3008.1
2J(TA)
0.090;-3183.4
(2T)(JA)
0.148;-2035.9
KA(2T)
0.087;-2832.8
2A(TQ)
0.077;-3008.1
2(JQA)
0.071;-2832.8
A(2JQ)
0.102;-2832.8
2A(JQ)
0.083;-2832.8
2(QKA)
0.118;-2482.2
2Q(KA)
0.113;-2482.2
33(3A)
0.072;-3342.8
(36)(3A)
0.117;-2816.9
3(39A)
0.063;-3438.4
3J(3A)
0.092;-3087.8
(345A)
0.041;-5111.9
(349A)
0.051;-4410.6
(34KA)
0.081;-3709.4
46(3A)
0.041;-4936.6
(49)(3A)
0.087;-3263.1
4(3QA)
0.083;-3884.7
6(35A)
0.045;-4761.2
T(35A)
0.071;-4060.0
5(36A)
0.047;-4761.2
58(3A)
0.063;-4410.6
(5J)(3A)
0.102;-2737.2
6(36A)
0.084;-3438.4
T(36A)
0.070;-3884.7
6(37A)
0.055;-4410.6
69(3A)
0.060;-4060.0
(6Q)(3A)
0.105;-2386.6
(379A)
0.062;-3884.7
(37KA)
0.103;-3183.4
79(3A)
0.070;-3884.7
(7Q)(3A)
0.114;-2211.3
(38TA)
0.069;-3534.1
88(3A)
0.110;-2737.2
(8J)(3A)
0.115;-2211.3
9(39A)
0.111;-2386.6
K(39A)
0.084;-2832.8
9(3QA)
0.090;-3008.1
J(3TA)
0.102;-3008.1
TJ(3A)
0.083;-3008.1
(3JQA)
0.086;-2657.5
J(3KA)
0.107;-2482.2
(QK)(3A)
0.167;-1159.4
33(5A)
0.070;-4139.7
337A
0.046;-4936.6
3A(3T)
0.064;-3263.1
33(KA)
0.105;-2737.2
3(46A)
0.044;-4936.6
38(4A)
0.061;-4585.9
(3J)(4A)
0.092;-2912.5
4A(34)
0.056;-4139.7
A(347)
0.041;-4761.2
(34)(TA)
0.105;-3087.8
QA(34)
0.069;-3884.7
345A
0.019;-6259.4
347A
0.022;-5908.8
349A
0.030;-5558.1
34JA
0.039;-5207.5
34KA
0.046;-4856.9
37(5A)
0.051;-4585.9
(3T)(5A)
0.091;-2912.5
3(5KA)
0.071;-3534.1
A(357)
0.062;-4585.9
(35)(TA)
0.073;-2912.5
QA(35)
0.072;-3709.4
356A
0.028;-5908.8
358A
0.033;-5558.1
35TA
0.046;-5207.5
35QA
0.042;-4856.9
(37)(6A)
0.080;-3263.1
3(6TA)
0.059;-3884.7
3Q(6A)
0.078;-3534.1
(36)(8A)
0.105;-3087.8
TA(36)
0.068;-3884.7
A(36K)
0.097;-3358.8
6A(38)
0.045;-4235.3
6A(3T)
0.056;-3884.7
6A(3Q)
0.058;-3534.1
37(7A)
0.083;-3087.8
(3T)(7A)
0.103;-2561.9
3(7KA)
0.089;-3183.4
A(379)
0.065;-3884.7
(37)(QA)
0.117;-2211.3
7A(38)
0.070;-4060.0
7A(3T)
0.072;-3709.4
7A(3Q)
0.097;-3358.8
38(8A)
0.088;-2737.2
(3J)(8A)
0.129;-2211.3
8A(38)
0.113;-2737.2
A(38J)
0.082;-3358.8
388A
0.066;-3884.7
38TA
0.044;-4681.6
38QA
0.058;-4330.9
(3T)(9A)
0.100;-2211.3
3(9KA)
0.109;-2832.8
A(39J)
0.073;-3183.4
399A
0.070;-3534.1
39JA
0.067;-4330.9
39KA
0.058;-3980.3
3Q(TA)
0.085;-2832.8
(3T)(QA)
0.142;-1685.3
TA(3J)
0.082;-3008.1
TA(3K)
0.116;-2657.5
3(JKA)
0.091;-2482.2
A(3JK)
0.094;-2482.2
JA(3K)
0.081;-2482.2
QA(3Q)
0.125;-1334.7
3QKA
0.088;-3454.4
45(4A)
0.078;-3789.1
(48)(4A)
0.122;-2115.6
4(4JA)
0.092;-2737.2
4K(4A)
0.112;-2386.6
(459A)
0.063;-4060.0
(45KA)
0.085;-3358.8
57(4A)
0.055;-4410.6
(5T)(4A)
0.101;-2737.2
5(4KA)
0.085;-3358.8
(469A)
0.063;-3884.7
(46KA)
0.078;-3183.4
68(4A)
0.079;-4060.0
(6J)(4A)
0.091;-2386.6
7(47A)
0.104;-2912.5
J(47A)
0.078;-3358.8
78(4A)
0.076;-3884.7
(7J)(4A)
0.101;-2211.3
8(48A)
0.091;-2561.9
Q(48A)
0.089;-3008.1
(8T)(4A)
0.098;-2211.3
8(4KA)
0.076;-2832.8
(49QA)
0.113;-2832.8
9(4JA)
0.100;-3008.1
9K(4A)
0.085;-2657.5
TT(4A)
0.133;-1860.6
(TK)(4A)
0.147;-1334.7
J(4QA)
0.102;-2482.2
K(4QA)
0.103;-2131.6
44(5A)
0.070;-3789.1
447A
0.043;-4585.9
4A(4T)
0.105;-2912.5
44(KA)
0.105;-2386.6
4(57A)
0.041;-4410.6
49(5A)
0.060;-4060.0
(4Q)(5A)
0.114;-2386.6
6A(45)
0.053;-4585.9
A(459)
0.074;-4060.0
(45)(QA)
0.083;-2386.6
5A(46)
0.054;-4585.9
5A(48)
0.054;-4235.3
5A(4T)
0.053;-3884.7
5A(4Q)
0.070;-3534.1
46(6A)
0.091;-3263.1
(49)(6A)
0.121;-2737.2
4(6QA)
0.081;-3358.8
A(467)
0.045;-4235.3
(46)(TA)
0.105;-2561.9
QA(46)
0.080;-3358.8
467A
0.034;-5382.8
469A
0.046;-5032.2
46JA
0.051;-4681.6
46KA
0.056;-4330.9
49(7A)
0.089;-3709.4
(4Q)(7A)
0.148;-2035.9
8A(47)
0.056;-3884.7
A(47J)
0.090;-3358.8
477A
0.048;-4060.0
479A
0.043;-4856.9
47JA
0.044;-4506.2
47KA
0.066;-4155.6
4T(8A)
0.091;-3358.8
(4K)(8A)
0.122;-1685.3
TA(48)
0.067;-3358.8
A(48K)
0.074;-2832.8
8A(4T)
0.066;-3358.8
8A(4Q)
0.080;-3008.1
49(9A)
0.121;-2211.2
(4Q)(9A)
0.148;-1685.3
TA(49)
0.086;-3183.4
A(49K)
0.115;-2657.5
9A(4J)
0.107;-3008.1
9A(4K)
0.095;-2657.5
4(TQA)
0.103;-2657.5
A(4TJ)
0.097;-2832.8
4TTA
0.100;-3008.1
4TQA
0.056;-3805.0
(4Q)(JA)
0.167;-1334.7
QA(4J)
0.109;-2482.2
4JQA
0.060;-3629.7
(4K)(QA)
0.138;-984.1
QA(4K)
0.133;-2131.6
5(56A)
0.066;-3263.1
58(5A)
0.074;-2912.5
(5J)(5A)
0.158;-1239.1
6(56A)
0.099;-3087.8
T(56A)
0.076;-3534.1
6(57A)
0.068;-4060.0
69(5A)
0.070;-3709.4
(6Q)(5A)
0.119;-2035.9
(579A)
0.056;-3534.1
(57KA)
0.106;-2832.8
79(5A)
0.083;-3534.1
(7Q)(5A)
0.118;-1860.6
(58TA)
0.071;-3183.4
88(5A)
0.108;-2386.6
(8J)(5A)
0.115;-1860.6
9(59A)
0.146;-2035.9
K(59A)
0.125;-2482.2
9(5QA)
0.075;-2657.5
J(5TA)
0.108;-2657.5
TJ(5A)
0.089;-2657.5
(5JQA)
0.124;-2306.9
J(5KA)
0.107;-2131.6
(QK)(5A)
0.204;-808.8
55(7A)
0.085;-3087.8
559A
0.064;-3884.7
5A(5Q)
0.093;-2211.2
(57)(6A)
0.094;-2912.5
5(6TA)
0.075;-3534.1
5Q(6A)
0.092;-3183.4
(56)(8A)
0.074;-2737.2
TA(56)
0.061;-3534.1
A(56K)
0.084;-3008.1
6A(58)
0.059;-3884.7
6A(5T)
0.086;-3534.1
6A(5Q)
0.098;-3183.4
57(7A)
0.099;-2737.2
(5T)(7A)
0.094;-2211.3
5(7KA)
0.094;-2832.8
A(579)
0.087;-3534.1
(57)(QA)
0.101;-1860.6
7A(58)
0.093;-3709.4
7A(5T)
0.078;-3358.8
7A(5Q)
0.081;-3008.1
58(8A)
0.089;-2386.6
(5J)(8A)
0.133;-1860.6
8A(58)
0.115;-2386.6
A(58J)
0.083;-3008.1
588A
0.071;-3534.1
58TA
0.044;-4330.9
58QA
0.075;-3980.3
(5T)(9A)
0.108;-1860.6
5(9KA)
0.106;-2482.2
A(59J)
0.084;-2832.8
599A
0.086;-3183.4
59JA
0.052;-3980.3
59KA
0.069;-3629.7
5Q(TA)
0.119;-2482.2
(5T)(QA)
0.132;-1334.7
TA(5J)
0.083;-2657.5
TA(5K)
0.113;-2306.9
5(JKA)
0.098;-2131.6
A(5JK)
0.105;-2131.6
JA(5K)
0.116;-2131.6
QA(5Q)
0.118;-984.1
5QKA
0.101;-3103.8
67(6A)
0.081;-2737.2
(6T)(6A)
0.158;-1063.7
6(6KA)
0.119;-1685.3
(67TA)
0.088;-3183.4
77(6A)
0.108;-2561.9
(7T)(6A)
0.119;-2035.9
7(6KA)
0.107;-2657.5
(68JA)
0.096;-2832.8
(89)(6A)
0.115;-2035.9
8(6QA)
0.100;-2657.5
T(69A)
0.096;-2832.8
9(6TA)
0.128;-2832.8
9Q(6A)
0.094;-2482.2
Q(6TA)
0.104;-2306.9
(TQ)(6A)
0.164;-1159.4
(6JKA)
0.135;-1956.2
JK(6A)
0.127;-1956.2
K(6KA)
0.176;-458.1
668A
0.057;-3709.4
6A(6J)
0.133;-2035.9
(67)(7A)
0.114;-1414.4
6(7TA)
0.091;-3183.4
6Q(7A)
0.104;-2832.8
(67)(9A)
0.124;-2211.3
JA(67)
0.100;-3008.1
67(8A)
0.088;-3534.1
67(TA)
0.081;-3183.4
67(QA)
0.111;-2832.8
(68)(8A)
0.186;-1063.7
6(8JA)
0.081;-2832.8
6K(8A)
0.091;-2482.2
(68)(JA)
0.120;-1685.3
KA(68)
0.097;-2482.2
6A(8T)
0.112;-3008.1
6A(8Q)
0.090;-2657.5
6(9TA)
0.094;-2832.8
6Q(9A)
0.102;-2482.2
(69)(JA)
0.171;-1510.0
KA(69)
0.107;-2306.9
6A(9J)
0.086;-2657.5
6A(9K)
0.114;-2306.9
(6Q)(TA)
0.155;-1159.4
JA(6T)
0.143;-2482.2
6T(JA)
0.118;-2482.2
6T(KA)
0.144;-2131.6
6Q(JA)
0.118;-2131.6
(6J)(KA)
0.161;-808.8
6J(KA)
0.105;-1956.2
6K(QA)
0.120;-1780.9
6A(QK)
0.145;-1780.9
(78)(7A)
0.131;-1063.7
7(7JA)
0.110;-1685.3
7K(7A)
0.107;-1334.7
(78QA)
0.117;-2482.2
8(7TA)
0.081;-2832.8
8Q(7A)
0.111;-2482.2
J(79A)
0.093;-2482.2
9T(7A)
0.097;-2657.5
(9K)(7A)
0.163;-984.1
K(7TA)
0.112;-1956.2
T(7KA)
0.118;-1956.2
JJ(7A)
0.131;-984.1
(7QKA)
0.115;-1605.6
777A
0.130;-2386.6
7A(7T)
0.128;-1860.6
77(KA)
0.150;-1334.7
7(8TA)
0.075;-2832.8
7Q(8A)
0.092;-2482.2
(78)(TA)
0.136;-1685.3
QA(78)
0.100;-2482.2
789A
0.063;-4155.6
78JA
0.071;-3805.0
78KA
0.088;-3454.4
7J(9A)
0.091;-2482.2
(79)(TA)
0.155;-1510.0
QA(79)
0.122;-2306.9
79TA
0.082;-3805.0
79QA
0.089;-3454.4
(7J)(TA)
0.144;-1159.4
TA(7T)
0.177;-1334.7
A(7TK)
0.106;-1956.2
TA(7Q)
0.139;-2131.6
7J(JA)
0.150;-984.1
(7J)(QA)
0.161;-808.8
JA(7Q)
0.124;-1956.2
7Q(QA)
0.183;-633.4
7QQA
0.109;-1780.9
7KKA
0.159;-1430.3
8(8JA)
0.157;-1334.7
8K(8A)
0.143;-984.1
(89KA)
0.106;-1956.2
9J(8A)
0.106;-2306.9
(8TJA)
0.138;-2131.6
(TJ)(8A)
0.159;-984.1
J(8JA)
0.152;-808.8
JQ(8A)
0.136;-1780.9
Q(8KA)
0.164;-1430.3
889A
0.078;-2832.8
8A(8Q)
0.169;-1159.4
(8T)(9A)
0.158;-1334.7
8(9KA)
0.132;-1956.2
A(89J)
0.119;-2306.9
899A
0.126;-2657.5
89JA
0.071;-3454.4
89KA
0.072;-3103.8
8Q(TA)
0.112;-1956.2
(8T)(QA)
0.181;-808.8
TA(8J)
0.108;-2131.6
TA(8K)
0.119;-1780.9
8(JKA)
0.133;-1605.6
A(8JK)
0.128;-1605.6
JA(8K)
0.147;-1605.6
QA(8Q)
0.184;-458.1
8QKA
0.092;-2577.8
9T(9A)
0.171;-1159.4
(9K)(9A)
0.195;514.1
K(9TA)
0.143;-1605.6
T(9KA)
0.167;-1605.6
JJ(9A)
0.142;-633.4
(9QKA)
0.147;-1255.0
999A
0.162;-1334.7
9A(9Q)
0.138;-808.8
(9J)(TA)
0.144;-808.8
TA(9T)
0.151;-984.1
A(9TK)
0.134;-1605.6
TA(9Q)
0.101;-1780.9
9J(JA)
0.159;-633.4
(9J)(QA)
0.135;-458.1
JA(9Q)
0.104;-1605.6
9Q(QA)
0.184;-282.8
9QQA
0.121;-1430.3
9KKA
0.150;-1079.7
T(TKA)
0.166;-282.8
JJ(TA)
0.202;-458.1
(TQKA)
0.171;-1079.7
TTTA
0.178;-808.8
TA(TK)
0.143;-282.8
(TK)(JA)
0.214;-107.5
KA(TJ)
0.139;-1255.0
TA(JK)
0.128;-1255.0
(TQ)(KA)
0.186;67.8
(TK)(KA)
0.235;1390.6
J(JKA)
0.168;67.8
(QK)(JA)
0.195;243.1
JJ(KA)
0.173;67.8
QA(JQ)
0.200;67.8
JQKA
0.114;-2051.9
QK(QA)
0.220;418.4
QK(KA)
0.223;593.7
22(24)
0.037;-5621.9
22(28)
0.035;-4920.6
22(2Q)
0.054;-4219.4
24(23)
0.017;-6594.1
(23)(27)
0.044;-4920.6
2(23T)
0.042;-5542.2
2Q(23)
0.033;-5191.6
23(25)
0.022;-6418.8
2237
0.009;-7215.6
22(3T)
0.033;-5542.2
23(2K)
0.052;-5016.2
2(246)
0.020;-6068.1
28(24)
0.026;-5717.5
(24)(2J)
0.068;-4044.1
2244
0.018;-6418.8
22(47)
0.019;-5892.8
24(2T)
0.028;-5366.9
224Q
0.019;-6163.8
26(25)
0.023;-5892.8
(25)(29)
0.071;-4219.4
2(25Q)
0.047;-4840.9
22(56)
0.026;-5892.8
25(29)
0.028;-5366.9
225J
0.021;-6163.8
26(26)
0.045;-4570.0
(26)(29)
0.065;-4044.1
2(26Q)
0.049;-4665.6
22(67)
0.038;-5542.2
26(2T)
0.042;-5016.2
226Q
0.026;-5813.1
28(27)
0.038;-5191.6
(27)(2J)
0.062;-3518.1
2277
0.041;-5366.9
22(7T)
0.043;-4840.9
27(2K)
0.043;-4315.0
2(28T)
0.051;-4665.6
2Q(28)
0.056;-4315.0
28(2T)
0.052;-4665.6
228Q
0.031;-5462.5
2T(29)
0.041;-4490.3
(29)(2K)
0.090;-2816.9
229J
0.032;-5462.5
2T(2T)
0.102;-3167.5
(2T)(2K)
0.111;-2641.6
22TQ
0.032;-5111.9
2Q(2J)
0.065;-3789.1
2J(2K)
0.054;-3613.8
22QQ
0.083;-3613.8
3(234)
0.016;-6418.8
36(23)
0.023;-6068.1
(23)(39)
0.046;-4394.7
3(23Q)
0.054;-5016.2
5(234)
0.010;-7215.6
9(234)
0.017;-6514.4
K(234)
0.024;-5813.1
4(237)
0.014;-6865.0
49(23)
0.017;-6514.4
(23)(4Q)
0.043;-4840.9
(2357)
0.021;-6689.7
(235J)
0.023;-5988.4
(23)(56)
0.033;-5717.5
5(239)
0.018;-6339.1
5J(23)
0.022;-5988.4
(2367)
0.014;-6514.4
(236J)
0.032;-5813.1
(23)(67)
0.042;-5366.9
6(23T)
0.025;-5988.4
6Q(23)
0.032;-5637.8
9(237)
0.023;-5988.4
K(237)
0.029;-5287.2
7(23T)
0.027;-5813.1
7Q(23)
0.039;-5462.5
T(238)
0.030;-5637.8
8(239)
0.024;-5813.1
8J(23)
0.026;-5462.5
(239T)
0.040;-5462.5
99(23)
0.058;-4490.3
(23)(9Q)
0.060;-3964.4
(23TQ)
0.042;-4936.6
T(23Q)
0.044;-4936.6
Q(23J)
0.049;-4761.2
(23)(JK)
0.087;-3438.4
QK(23)
0.067;-4410.6
23(35)
0.019;-6243.4
33(28)
0.027;-5717.5
233T
0.013;-6514.4
23(3K)
0.042;-4840.9
(24)(36)
0.027;-5892.8
3(249)
0.017;-6514.4
3J(24)
0.021;-6163.8
(34)(25)
0.026;-6068.1
27(34)
0.012;-6865.0
2(34T)
0.020;-6339.1
(34)(2K)
0.041;-4665.6
34(26)
0.014;-7040.3
34(28)
0.013;-6689.7
34(2T)
0.015;-6339.1
34(2Q)
0.021;-5988.4
(25)(35)
0.050;-4745.3
3(258)
0.021;-6514.4
3T(25)
0.017;-6163.8
(25)(3K)
0.055;-4490.3
27(35)
0.017;-6689.7
2(35T)
0.020;-6163.8
(35)(2K)
0.040;-4490.3
35(27)
0.012;-6689.7
35(29)
0.020;-6339.1
35(2J)
0.021;-5988.4
35(2K)
0.036;-5637.8
37(26)
0.020;-6514.4
(26)(3T)
0.050;-4840.9
3(26K)
0.026;-5462.5
2(368)
0.021;-6339.1
(36)(2J)
0.055;-4665.6
2K(36)
0.039;-5462.5
23(68)
0.018;-6339.1
23(6T)
0.026;-5988.4
23(6Q)
0.025;-5637.8
3(278)
0.022;-6163.8
3T(27)
0.024;-5813.1
(27)(3K)
0.060;-4139.7
29(37)
0.021;-5988.4
2(37Q)
0.041;-5462.5
23(78)
0.023;-6163.8
23(7T)
0.030;-5813.1
23(7Q)
0.028;-5462.5
3(289)
0.022;-5813.1
3J(28)
0.038;-5462.5
(38)(29)
0.043;-4665.6
2J(38)
0.029;-5462.5
38(29)
0.028;-5813.1
38(2J)
0.039;-5462.5
38(2K)
0.035;-5111.9
3T(29)
0.027;-5462.5
(29)(3K)
0.085;-3789.1
2J(39)
0.040;-5287.2
39(2T)
0.031;-5462.5
39(2Q)
0.048;-5111.9
(2T)(3T)
0.089;-2992.2
3(2TK)
0.039;-4761.2
2(3TQ)
0.039;-4936.6
23(TJ)
0.033;-5111.9
23(TK)
0.046;-4761.2
(2J)(3K)
0.065;-3438.4
2K(3J)
0.045;-4585.9
23(JK)
0.052;-4585.9
(3Q)(2K)
0.112;-3263.1
(2K)(3K)
0.115;-1940.3
4(246)
0.027;-5717.5
48(24)
0.031;-5366.9
(24)(4J)
0.066;-3693.4
5(245)
0.026;-5717.5
9(245)
0.020;-6163.8
K(245)
0.037;-5462.5
5(248)
0.019;-6339.1
5T(24)
0.021;-5988.4
(24)(5K)
0.059;-4315.0
9(246)
0.029;-5988.4
K(246)
0.031;-5287.2
6(249)
0.021;-5988.4
6J(24)
0.032;-5637.8
(2478)
0.025;-5988.4
(247Q)
0.035;-5287.2
7(249)
0.027;-5813.1
7J(24)
0.040;-5462.5
(2489)
0.034;-5637.8
(248K)
0.042;-4936.6
8T(24)
0.030;-5462.5
(24)(8K)
0.069;-3789.1
Q(249)
0.041;-4936.6
(24)(9J)
0.068;-3964.4
T(24T)
0.068;-3964.4
T(24J)
0.048;-4936.6
TK(24)
0.043;-4585.9
(24)(JQ)
0.086;-3438.4
QQ(24)
0.071;-3263.1
24(45)
0.030;-5892.8
44(28)
0.039;-5366.9
244T
0.025;-6163.8
24(4K)
0.052;-4490.3
(25)(47)
0.032;-5366.9
4(25T)
0.023;-5988.4
4Q(25)
0.025;-5637.8
(45)(27)
0.037;-5366.9
29(45)
0.024;-6163.8
2(45Q)
0.030;-5637.8
24(56)
0.013;-6689.7
24(58)
0.018;-6339.1
24(5T)
0.030;-5988.4
24(5Q)
0.030;-5637.8
4(267)
0.018;-6339.1
49(26)
0.027;-5988.4
(26)(4Q)
0.040;-4315.0
27(46)
0.018;-6339.1
2(46T)
0.032;-5813.1
(46)(2K)
0.049;-4139.7
46(28)
0.019;-6163.8
46(2T)
0.027;-5813.1
46(2Q)
0.034;-5462.5
(27)(47)
0.062;-3868.8
4(27T)
0.030;-5637.8
4Q(27)
0.032;-5287.2
(47)(29)
0.052;-4665.6
2J(47)
0.035;-5462.5
47(28)
0.020;-5988.4
47(2T)
0.027;-5637.8
47(2Q)
0.038;-5287.2
(28)(48)
0.078;-3518.1
4(28J)
0.038;-5287.2
4K(28)
0.054;-4936.6
(48)(2J)
0.056;-4139.7
2K(48)
0.039;-4936.6
24(8T)
0.033;-5462.5
24(8Q)
0.030;-5111.9
4(29T)
0.027;-5287.2
4Q(29)
0.046;-4936.6
(49)(2J)
0.065;-3964.4
2K(49)
0.041;-4761.2
24(9J)
0.042;-5111.9
24(9K)
0.044;-4761.2
(2T)(4Q)
0.074;-3613.8
2J(4T)
0.046;-4936.6
4T(2J)
0.046;-4936.6
4T(2K)
0.060;-4585.9
4Q(2J)
0.046;-4585.9
(4J)(2K)
0.076;-3263.1
4J(2K)
0.054;-4410.6
4K(2Q)
0.053;-4235.3
24(QK)
0.050;-4235.3
(25)(56)
0.047;-4219.4
5(259)
0.051;-4840.9
5J(25)
0.059;-4490.3
(2567)
0.021;-6163.8
(256J)
0.032;-5462.5
(25)(67)
0.051;-5016.3
6(25T)
0.028;-5637.8
6Q(25)
0.041;-5287.2
9(257)
0.032;-5637.8
K(257)
0.035;-4936.6
7(25T)
0.034;-5462.5
7Q(25)
0.038;-5111.9
T(258)
0.039;-5287.2
8(259)
0.039;-5462.5
8J(25)
0.045;-5111.9
(259T)
0.036;-5111.9
99(25)
0.057;-4139.7
(25)(9Q)
0.073;-3613.8
(25TQ)
0.041;-4585.9
T(25Q)
0.051;-4585.9
Q(25J)
0.043;-4410.6
(25)(JK)
0.100;-3087.8
QK(25)
0.072;-4060.0
25(57)
0.040;-5191.6
55(2T)
0.049;-4665.6
255Q
0.031;-5462.5
57(26)
0.022;-6163.8
(26)(5T)
0.055;-4490.3
5(26K)
0.038;-5111.9
2(568)
0.026;-5988.4
(56)(2J)
0.047;-4315.0
2K(56)
0.053;-5111.9
25(68)
0.019;-5988.4
25(6T)
0.032;-5637.8
25(6Q)
0.035;-5287.2
5(278)
0.026;-5813.1
5T(27)
0.029;-5462.5
(27)(5K)
0.065;-3789.1
29(57)
0.031;-5637.8
2(57Q)
0.045;-5111.9
25(78)
0.027;-5813.1
25(7T)
0.037;-5462.5
25(7Q)
0.048;-5111.9
5(289)
0.028;-5462.5
5J(28)
0.047;-5111.9
(58)(29)
0.065;-4315.0
2J(58)
0.041;-5111.9
58(29)
0.042;-5462.5
58(2J)
0.051;-5111.9
58(2K)
0.050;-4761.2
5T(29)
0.037;-5111.9
(29)(5K)
0.078;-3438.4
2J(59)
0.039;-4936.6
59(2T)
0.036;-5111.9
59(2Q)
0.046;-4761.2
(2T)(5T)
0.095;-2641.6
5(2TK)
0.052;-4410.6
2(5TQ)
0.047;-4585.9
25(TJ)
0.045;-4761.2
25(TK)
0.069;-4410.6
(2J)(5K)
0.073;-3087.8
2K(5J)
0.050;-4235.3
25(JK)
0.066;-4235.3
(5Q)(2K)
0.104;-2912.5
(2K)(5K)
0.125;-1589.7
6(268)
0.054;-4665.6
6T(26)
0.054;-4315.0
(26)(6K)
0.095;-2641.6
T(267)
0.026;-5287.2
7(268)
0.039;-5637.8
7T(26)
0.042;-5287.2
(26)(7K)
0.059;-3613.8
J(268)
0.052;-4936.6
89(26)
0.045;-5287.2
(26)(8Q)
0.074;-3613.8
(269J)
0.046;-4761.2
(26)(9T)
0.063;-3789.1
9(26K)
0.042;-4410.6
(26TK)
0.052;-4235.3
TQ(26)
0.066;-4410.6
K(26J)
0.080;-4060.0
Q(26Q)
0.094;-2912.5
KK(26)
0.096;-2561.9
66(29)
0.067;-4490.3
266J
0.045;-5287.2
67(27)
0.037;-4665.6
(27)(6T)
0.048;-4139.7
6(27K)
0.047;-4761.2
2(679)
0.039;-5462.5
(67)(2Q)
0.075;-3789.1
27(68)
0.027;-5637.8
27(6T)
0.039;-5287.2
27(6Q)
0.038;-4936.6
68(28)
0.064;-4315.0
(28)(6J)
0.056;-3789.1
28(68)
0.049;-4315.0
2(68J)
0.037;-4936.6
2688
0.032;-5462.5
268T
0.022;-6259.4
268Q
0.026;-5908.8
(29)(6T)
0.077;-3789.1
6(29K)
0.055;-4410.6
2(69J)
0.047;-4761.2
2699
0.030;-5111.9
269J
0.026;-5908.8
269K
0.026;-5558.1
6Q(2T)
0.059;-4410.6
(6T)(2Q)
0.078;-3263.1
2T(6J)
0.045;-4585.9
2T(6K)
0.051;-4235.3
6(2JK)
0.068;-4060.0
2(6JK)
0.056;-4060.0
2J(6K)
0.054;-4060.0
2Q(6Q)
0.083;-2912.5
26QK
0.045;-5032.2
78(27)
0.058;-4315.0
(27)(7J)
0.093;-2641.6
8(278)
0.066;-4139.7
Q(278)
0.061;-4585.9
(27)(8T)
0.070;-3789.1
8(27K)
0.066;-4410.6
(279Q)
0.055;-4410.6
9(27J)
0.052;-4585.9
9K(27)
0.058;-4235.3
TT(27)
0.086;-3438.4
(27)(TK)
0.094;-2912.5
J(27Q)
0.065;-4060.0
K(27Q)
0.076;-3709.4
77(28)
0.059;-4315.0
277T
0.037;-5111.9
27(7K)
0.067;-3438.4
(28)(7T)
0.063;-3789.1
7(28K)
0.057;-4410.6
2(78T)
0.044;-4936.6
(78)(2K)
0.076;-3263.1
78(2T)
0.034;-4936.6
78(2Q)
0.064;-4585.9
(29)(79)
0.123;-2641.6
7(29Q)
0.051;-4410.6
2(79T)
0.050;-4761.2
(79)(2K)
0.093;-3087.8
79(2J)
0.039;-4585.9
79(2K)
0.060;-4235.3
7J(2T)
0.055;-4410.6
(7T)(2J)
0.079;-3263.1
2K(7T)
0.058;-4060.0
27(TQ)
0.049;-4235.3
7(2JQ)
0.062;-4060.0
2(7JQ)
0.061;-4060.0
27(JQ)
0.049;-4060.0
7(2QK)
0.070;-3709.4
7Q(2K)
0.065;-3709.4
88(28)
0.086;-2816.9
(28)(8J)
0.146;-2290.9
9(289)
0.080;-3613.8
K(289)
0.080;-4060.0
9(28Q)
0.065;-4235.3
J(28T)
0.061;-4235.3
TJ(28)
0.054;-4235.3
(28JQ)
0.058;-3884.7
J(28K)
0.067;-3709.4
(28)(QK)
0.116;-2386.6
88(2T)
0.055;-3613.8
288Q
0.049;-4410.6
8T(29)
0.039;-4585.9
(29)(8K)
0.117;-2912.5
2J(89)
0.059;-4410.6
89(2T)
0.047;-4585.9
89(2Q)
0.055;-4235.3
(2T)(8T)
0.124;-2115.6
8(2TK)
0.053;-3884.7
2(8TQ)
0.074;-4060.0
28(TJ)
0.078;-4235.3
28(TK)
0.065;-3884.7
(2J)(8K)
0.101;-2561.9
2K(8J)
0.067;-3709.4
28(JK)
0.056;-3709.4
(8Q)(2K)
0.132;-2386.6
(2K)(8K)
0.175;-1063.7
9(29J)
0.081;-3087.8
9K(29)
0.105;-2737.2
TT(29)
0.102;-3087.8
(29)(TK)
0.081;-2561.9
J(29Q)
0.073;-3709.4
K(29Q)
0.084;-3358.8
99(2T)
0.079;-3263.1
299Q
0.065;-4060.0
9J(2T)
0.047;-4060.0
(9T)(2J)
0.085;-2912.5
2K(9T)
0.082;-3709.4
29(TQ)
0.058;-3884.7
9(2JQ)
0.080;-3709.4
2(9JQ)
0.070;-3709.4
29(JQ)
0.083;-3709.4
9(2QK)
0.074;-3358.8
9Q(2K)
0.071;-3358.8
TT(2T)
0.121;-1765.0
(2T)(TK)
0.129;-1239.1
J(2TQ)
0.082;-3534.1
K(2TQ)
0.106;-3183.4
TT(2J)
0.095;-2737.2
2TTK
0.095;-3534.1
TK(2J)
0.089;-3358.8
2TJJ
0.062;-3709.4
2TJK
0.038;-4506.2
2(TQK)
0.077;-3183.4
TK(2K)
0.117;-1860.6
(2J)(JK)
0.158;-888.4
QK(2J)
0.098;-3008.1
2J(JK)
0.149;-2035.9
(JQ)(2K)
0.095;-1860.6
(2K)(JK)
0.172;-537.8
K(2QK)
0.146;-1510.0
2K(QK)
0.139;-1510.0
3335
0.022;-6068.1
3339
0.031;-5366.9
333K
0.034;-4665.6
36(34)
0.025;-5717.5
(34)(39)
0.061;-4044.1
3(34Q)
0.048;-4665.6
33(45)
0.028;-5892.8
34(38)
0.045;-5366.9
334T
0.023;-6163.8
33(4K)
0.053;-4490.3
(35)(37)
0.055;-4219.4
3(35T)
0.043;-4840.9
3Q(35)
0.052;-4490.3
35(37)
0.032;-5366.9
3359
0.018;-6163.8
33(5Q)
0.063;-4490.3
(36)(37)
0.069;-4044.1
3(36T)
0.038;-4665.6
3Q(36)
0.043;-4315.0
36(38)
0.039;-5016.2
336T
0.029;-5813.1
33(6K)
0.057;-4139.7
(37)(39)
0.068;-3518.1
3(37Q)
0.071;-4139.7
33(78)
0.055;-4840.9
37(3J)
0.061;-4315.0
337K
0.034;-5111.9
3T(38)
0.058;-4315.0
(38)(3K)
0.074;-2641.6
338T
0.038;-5462.5
33(8K)
0.066;-3789.1
(39)(3J)
0.098;-2816.9
3399
0.054;-4315.0
33(9Q)
0.060;-3789.1
(3T)(3J)
0.119;-2641.6
33TT
0.057;-3964.4
33(TK)
0.063;-3438.4
(3J)(3K)
0.121;-2115.6
33JK
0.049;-4410.6
33(QK)
0.112;-3087.8
45(34)
0.029;-5717.5
(34)(48)
0.053;-4044.1
4(34J)
0.050;-4665.6
4K(34)
0.063;-4315.0
(3459)
0.032;-5988.4
(345K)
0.039;-5287.2
57(34)
0.016;-6339.1
(34)(5T)
0.064;-4665.6
5(34K)
0.030;-5287.2
(3469)
0.034;-5813.1
(346K)
0.045;-5111.9
68(34)
0.025;-5988.4
(34)(6J)
0.052;-4315.0
7(347)
0.038;-4840.9
J(347)
0.037;-5287.2
78(34)
0.028;-5813.1
(34)(7J)
0.055;-4139.7
8(348)
0.041;-4490.3
Q(348)
0.041;-4936.6
(34)(8T)
0.052;-4139.7
8(34K)
0.054;-4761.2
(349Q)
0.061;-4761.2
9(34J)
0.036;-4936.6
9K(34)
0.044;-4585.9
TT(34)
0.061;-3789.1
(34)(TK)
0.103;-3263.1
J(34Q)
0.070;-4410.6
K(34Q)
0.068;-4060.0
44(35)
0.028;-5717.5
3447
0.020;-6514.4
34(4T)
0.049;-4840.9
44(3K)
0.058;-4315.0
4(357)
0.022;-6339.1
49(35)
0.026;-5988.4
(35)(4Q)
0.049;-4315.0
36(45)
0.017;-6514.4
3(459)
0.028;-5988.4
(45)(3Q)
0.056;-4315.0
35(46)
0.022;-6514.4
35(48)
0.028;-6163.8
35(4T)
0.029;-5813.1
35(4Q)
0.032;-5462.5
46(36)
0.036;-5191.6
(36)(49)
0.050;-4665.6
4(36Q)
0.045;-5287.2
3(467)
0.020;-6163.8
(46)(3T)
0.054;-4490.3
3Q(46)
0.032;-5287.2
3467
0.008;-7311.2
3469
0.010;-6960.6
346J
0.016;-6610.0
346K
0.022;-6259.4
49(37)
0.024;-5637.8
(37)(4Q)
0.055;-3964.4
38(47)
0.034;-5813.1
3(47J)
0.030;-5287.2
3477
0.022;-5988.4
3479
0.014;-6785.3
347J
0.017;-6434.7
347K
0.025;-6084.1
4T(38)
0.043;-5287.2
(38)(4K)
0.068;-3613.8
3T(48)
0.036;-5287.2
3(48K)
0.042;-4761.2
38(4T)
0.035;-5287.2
38(4Q)
0.042;-4936.6
49(39)
0.057;-4139.7
(39)(4Q)
0.057;-3613.8
3T(49)
0.044;-5111.9
3(49K)
0.045;-4585.9
39(4J)
0.036;-4936.6
39(4K)
0.037;-4585.9
4(3TQ)
0.052;-4585.9
3(4TJ)
0.046;-4761.2
34TT
0.042;-4936.6
34TQ
0.029;-5733.4
(3J)(4Q)
0.093;-3263.1
3Q(4J)
0.052;-4410.6
34JQ
0.024;-5558.1
(3Q)(4K)
0.073;-2912.5
3Q(4K)
0.053;-4060.0
5(356)
0.039;-5191.6
58(35)
0.048;-4840.9
(35)(5J)
0.097;-3167.5
6(356)
0.031;-5016.2
T(356)
0.046;-5462.5
6(357)
0.018;-5988.4
69(35)
0.031;-5637.8
(35)(6Q)
0.068;-3964.4
(3579)
0.041;-5462.5
(357K)
0.053;-4761.2
79(35)
0.032;-5462.5
(35)(7Q)
0.065;-3789.1
(358T)
0.039;-5111.9
88(35)
0.065;-4315.0
(35)(8J)
0.077;-3789.1
9(359)
0.072;-3964.4
K(359)
0.068;-4410.6
9(35Q)
0.048;-4585.9
J(35T)
0.061;-4585.9
TJ(35)
0.048;-4585.9
(35JQ)
0.073;-4235.3
J(35K)
0.069;-4060.0
(35)(QK)
0.111;-2737.2
55(37)
0.038;-5016.2
3559
0.023;-5813.1
35(5Q)
0.056;-4139.7
(36)(57)
0.044;-4840.9
5(36T)
0.026;-5462.5
5Q(36)
0.045;-5111.9
(56)(38)
0.046;-4665.6
3T(56)
0.036;-5462.5
3(56K)
0.049;-4936.6
36(58)
0.034;-5813.1
36(5T)
0.035;-5462.5
36(5Q)
0.039;-5111.9
57(37)
0.049;-4665.6
(37)(5T)
0.050;-4139.7
5(37K)
0.034;-4761.2
3(579)
0.028;-5462.5
(57)(3Q)
0.072;-3789.1
37(58)
0.030;-5637.8
37(5T)
0.028;-5287.2
37(5Q)
0.048;-4936.6
58(38)
0.066;-4315.0
(38)(5J)
0.069;-3789.1
38(58)
0.063;-4315.0
3(58J)
0.042;-4936.6
3588
0.034;-5462.5
358T
0.017;-6259.4
358Q
0.022;-5908.8
(39)(5T)
0.078;-3789.1
5(39K)
0.046;-4410.6
3(59J)
0.042;-4761.2
3599
0.034;-5111.9
359J
0.023;-5908.8
359K
0.038;-5558.1
5Q(3T)
0.053;-4410.6
(5T)(3Q)
0.070;-3263.1
3T(5J)
0.062;-4585.9
3T(5K)
0.058;-4235.3
5(3JK)
0.056;-4060.0
3(5JK)
0.050;-4060.0
3J(5K)
0.062;-4060.0
3Q(5Q)
0.097;-2912.5
35QK
0.043;-5032.2
67(36)
0.041;-4665.6
(36)(6T)
0.082;-2992.2
6(36K)
0.089;-3613.8
(367T)
0.044;-5111.9
77(36)
0.058;-4490.3
(36)(7T)
0.061;-3964.4
7(36K)
0.050;-4585.9
(368J)
0.034;-4761.2
(36)(89)
0.054;-3964.4
8(36Q)
0.052;-4585.9
T(369)
0.035;-4761.2
9(36T)
0.051;-4761.2
9Q(36)
0.050;-4410.6
Q(36T)
0.045;-4235.3
(36)(TQ)
0.064;-3087.8
(36JK)
0.072;-3884.7
JK(36)
0.068;-3884.7
K(36K)
0.097;-2386.6
3668
0.034;-5637.8
36(6J)
0.055;-3964.4
(37)(67)
0.064;-3342.8
6(37T)
0.045;-5111.9
6Q(37)
0.053;-4761.2
(67)(39)
0.050;-4139.7
3J(67)
0.038;-4936.6
67(38)
0.037;-5462.5
67(3T)
0.040;-5111.9
67(3Q)
0.043;-4761.2
(38)(68)
0.082;-2992.2
6(38J)
0.047;-4761.2
6K(38)
0.071;-4410.6
(68)(3J)
0.076;-3613.8
3K(68)
0.058;-4410.6
36(8T)
0.041;-4936.6
36(8Q)
0.063;-4585.9
6(39T)
0.054;-4761.2
6Q(39)
0.042;-4410.6
(69)(3J)
0.087;-3438.4
3K(69)
0.055;-4235.3
36(9J)
0.055;-4585.9
36(9K)
0.051;-4235.3
(3T)(6Q)
0.080;-3087.8
3J(6T)
0.059;-4410.6
6T(3J)
0.057;-4410.6
6T(3K)
0.062;-4060.0
6Q(3J)
0.045;-4060.0
(6J)(3K)
0.116;-2737.2
6J(3K)
0.060;-3884.7
6K(3Q)
0.059;-3709.4
36(QK)
0.070;-3709.4
(37)(78)
0.080;-2992.2
7(37J)
0.060;-3613.8
7K(37)
0.067;-3263.1
(378Q)
0.052;-4410.6
8(37T)
0.049;-4761.2
8Q(37)
0.069;-4410.6
J(379)
0.061;-4410.6
9T(37)
0.052;-4585.9
(37)(9K)
0.076;-2912.5
K(37T)
0.066;-3884.7
T(37K)
0.060;-3884.7
JJ(37)
0.077;-2912.5
(37QK)
0.098;-3534.1
3777
0.055;-4315.0
37(7T)
0.071;-3789.1
77(3K)
0.103;-3263.1
7(38T)
0.053;-4761.2
7Q(38)
0.056;-4410.6
(78)(3T)
0.073;-3613.8
3Q(78)
0.057;-4410.6
3789
0.029;-6084.1
378J
0.030;-5733.4
378K
0.031;-5382.8
7J(39)
0.054;-4410.6
(79)(3T)
0.079;-3438.4
3Q(79)
0.044;-4235.3
379T
0.026;-5733.4
379Q
0.029;-5382.8
(3T)(7J)
0.083;-3087.8
3T(7T)
0.079;-3263.1
3(7TK)
0.067;-3884.7
3T(7Q)
0.063;-4060.0
7J(3J)
0.118;-2912.5
(7J)(3Q)
0.096;-2737.2
3J(7Q)
0.054;-3884.7
7Q(3Q)
0.108;-2561.9
37QQ
0.062;-3709.4
37KK
0.084;-3358.8
8(38J)
0.070;-3263.1
8K(38)
0.101;-2912.5
(389K)
0.052;-3884.7
9J(38)
0.057;-4235.3
(38TJ)
0.047;-4060.0
(38)(TJ)
0.087;-2912.5
J(38J)
0.095;-2737.2
JQ(38)
0.070;-3709.4
Q(38K)
0.084;-3358.8
3889
0.046;-4761.2
38(8Q)
0.074;-3087.8
(39)(8T)
0.087;-3263.1
8(39K)
0.064;-3884.7
3(89J)
0.050;-4235.3
3899
0.052;-4585.9
389J
0.028;-5382.8
389K
0.031;-5032.2
8Q(3T)
0.081;-3884.7
(8T)(3Q)
0.100;-2737.2
3T(8J)
0.054;-4060.0
3T(8K)
0.064;-3709.4
8(3JK)
0.079;-3534.1
3(8JK)
0.090;-3534.1
3J(8K)
0.067;-3534.1
3Q(8Q)
0.112;-2386.6
38QK
0.050;-4506.2
9T(39)
0.113;-3087.8
(39)(9K)
0.129;-1414.4
K(39T)
0.080;-3534.1
T(39K)
0.071;-3534.1
JJ(39)
0.123;-2561.9
(39QK)
0.077;-3183.4
3999
0.074;-3263.1
39(9Q)
0.085;-2737.2
(3T)(9J)
0.082;-2737.2
3T(9T)
0.096;-2912.5
3(9TK)
0.073;-3534.1
3T(9Q)
0.082;-3709.4
9J(3J)
0.094;-2561.9
(9J)(3Q)
0.087;-2386.6
3J(9Q)
0.088;-3534.1
9Q(3Q)
0.124;-2211.2
39QQ
0.067;-3358.8
39KK
0.070;-3008.1
T(3TK)
0.115;-2211.2
JJ(3T)
0.098;-2386.6
(3TQK)
0.091;-3008.1
3TTT
0.110;-2737.2
3T(TK)
0.105;-2211.2
(3J)(TK)
0.120;-2035.9
3K(TJ)
0.101;-3183.4
3T(JK)
0.107;-3183.4
(TQ)(3K)
0.151;-1860.6
(3K)(TK)
0.170;-537.8
J(3JK)
0.116;-1860.6
(3J)(QK)
0.141;-1685.3
JJ(3K)
0.124;-1860.6
3Q(JQ)
0.147;-1860.6
3JQK
0.054;-3980.3
QK(3Q)
0.144;-1510.0
QK(3K)
0.185;-1334.7
44(46)
0.062;-4219.4
44(4T)
0.083;-3518.1
(45)(45)
0.104;-3071.9
4(458)
0.040;-4840.9
4T(45)
0.048;-4490.3
(45)(4K)
0.099;-2816.9
4457
0.019;-6163.8
44(5T)
0.055;-4490.3
45(4K)
0.076;-3964.4
4(468)
0.046;-4665.6
4T(46)
0.048;-4315.0
(46)(4K)
0.090;-2641.6
4468
0.023;-5813.1
44(6J)
0.072;-4139.7
(47)(47)
0.115;-2370.6
4(47T)
0.056;-4139.7
4Q(47)
0.076;-3789.1
47(49)
0.051;-4315.0
447J
0.036;-5111.9
48(48)
0.096;-3167.5
(48)(4J)
0.105;-2641.6
4488
0.071;-4315.0
44(8J)
0.063;-3789.1
(49)(49)
0.131;-1669.4
4(49Q)
0.074;-3438.4
44(9T)
0.064;-3789.1
49(4K)
0.083;-3263.1
4(4TQ)
0.072;-3263.1
44(TJ)
0.083;-3438.4
(4J)(4J)
0.188;-968.1
44JJ
0.083;-3263.1
4Q(4Q)
0.098;-1765.0
(4K)(4K)
0.203;-266.9
(45)(57)
0.087;-3693.4
5(45T)
0.057;-4315.0
5Q(45)
0.076;-3964.4
8(456)
0.033;-5637.8
Q(456)
0.035;-4936.6
(45)(68)
0.044;-4490.3
6(45J)
0.037;-5111.9
6K(45)
0.044;-4761.2
(457J)
0.039;-4936.6
(45)(78)
0.058;-4315.0
7(45J)
0.033;-4936.6
7K(45)
0.042;-4585.9
(458Q)
0.055;-4585.9
8(45T)
0.049;-4936.6
8Q(45)
0.058;-4585.9
J(459)
0.049;-4585.9
9T(45)
0.048;-4761.2
(45)(9K)
0.084;-3087.8
K(45T)
0.060;-4060.0
T(45K)
0.050;-4060.0
JJ(45)
0.070;-3087.8
(45QK)
0.061;-3709.4
4555
0.031;-5191.6
45(58)
0.044;-4665.6
55(4J)
0.050;-4139.7
455K
0.048;-4936.6
58(46)
0.029;-5637.8
(46)(5J)
0.066;-3964.4
46(56)
0.043;-4840.9
4(569)
0.027;-5462.5
(56)(4Q)
0.077;-3789.1
46(57)
0.023;-5813.1
46(59)
0.037;-5462.5
46(5J)
0.041;-5111.9
46(5K)
0.038;-4761.2
5(479)
0.030;-5287.2
5J(47)
0.039;-4936.6
(57)(48)
0.071;-4315.0
4T(57)
0.044;-5111.9
4(57K)
0.051;-4585.9
47(59)
0.040;-5287.2
47(5J)
0.039;-4936.6
47(5K)
0.053;-4585.9
5(48T)
0.042;-4936.6
5Q(48)
0.055;-4585.9
(58)(4T)
0.062;-3789.1
4Q(58)
0.047;-4585.9
4589
0.022;-6259.4
458J
0.020;-5908.8
458K
0.026;-5558.1
5J(49)
0.040;-4585.9
(59)(4T)
0.072;-3613.8
4Q(59)
0.052;-4410.6
459T
0.024;-5908.8
459Q
0.030;-5558.1
(4T)(5J)
0.084;-3263.1
4T(5T)
0.071;-3438.4
4(5TK)
0.055;-4060.0
4T(5Q)
0.054;-4235.3
5J(4J)
0.096;-3087.8
(5J)(4Q)
0.071;-2912.5
4J(5Q)
0.067;-4060.0
5Q(4Q)
0.080;-2737.2
45QQ
0.080;-3884.7
45KK
0.074;-3534.1
6(469)
0.070;-4139.7
6J(46)
0.063;-3789.1
(4678)
0.031;-5287.2
(467Q)
0.053;-4585.9
7(469)
0.032;-5111.9
7J(46)
0.044;-4761.2
(4689)
0.031;-4936.6
(468K)
0.062;-4235.3
8T(46)
0.051;-4761.2
(46)(8K)
0.069;-3087.8
Q(469)
0.054;-4235.3
(46)(9J)
0.062;-3263.1
T(46T)
0.081;-3263.1
T(46J)
0.061;-4235.3
TK(46)
0.065;-3884.7
(46)(JQ)
0.107;-2737.2
QQ(46)
0.100;-2561.9
46(67)
0.051;-4490.3
66(4T)
0.084;-3964.4
466Q
0.048;-4761.2
68(47)
0.032;-5287.2
(47)(6J)
0.074;-3613.8
47(67)
0.063;-4315.0
4(67T)
0.050;-4936.6
(67)(4K)
0.075;-3263.1
67(49)
0.031;-5111.9
67(4J)
0.052;-4761.2
67(4K)
0.052;-4410.6
69(48)
0.045;-4936.6
(48)(6Q)
0.074;-3263.1
49(68)
0.050;-4936.6
4(68Q)
0.041;-4410.6
46(89)
0.037;-4936.6
46(8J)
0.064;-4585.9
46(8K)
0.050;-4235.3
(49)(6J)
0.079;-3263.1
49(69)
0.059;-3613.8
4(69Q)
0.052;-4235.3
46(9T)
0.046;-4585.9
46(9Q)
0.057;-4235.3
6(4TJ)
0.065;-4235.3
6K(4T)
0.061;-3884.7
(6T)(4K)
0.085;-2737.2
6T(4Q)
0.075;-4060.0
(4J)(6J)
0.141;-1765.0
4J(6J)
0.096;-2912.5
6J(4Q)
0.054;-3884.7
(4Q)(6Q)
0.127;-1414.4
4K(6Q)
0.078;-3534.1
4K(6K)
0.099;-2211.2
79(47)
0.076;-3789.1
(47)(7Q)
0.103;-2115.6
(478T)
0.044;-4585.9
88(47)
0.060;-3789.1
(47)(8J)
0.078;-3263.1
9(479)
0.069;-3438.4
K(479)
0.069;-3884.7
9(47Q)
0.055;-4060.0
J(47T)
0.051;-4060.0
TJ(47)
0.058;-4060.0
(47JQ)
0.061;-3709.4
J(47K)
0.067;-3534.1
(47)(QK)
0.123;-2211.3
77(49)
0.069;-3789.1
477J
0.058;-4585.9
78(48)
0.053;-3789.1
(48)(7J)
0.065;-3263.1
48(78)
0.064;-3789.1
4(78J)
0.060;-4410.6
4788
0.041;-4936.6
478T
0.031;-5733.4
478Q
0.030;-5382.8
(49)(7T)
0.079;-3263.1
7(49K)
0.077;-3884.7
4(79J)
0.081;-4235.3
4799
0.055;-4585.9
479J
0.036;-5382.8
479K
0.052;-5032.2
7Q(4T)
0.061;-3884.7
(7T)(4Q)
0.080;-2737.2
4T(7J)
0.059;-4060.0
4T(7K)
0.067;-3709.4
7(4JK)
0.067;-3534.1
4(7JK)
0.094;-3534.1
4J(7K)
0.080;-3534.1
4Q(7Q)
0.086;-2386.6
47QK
0.046;-4506.2
89(48)
0.075;-3438.4
(48)(8Q)
0.140;-1765.0
(489J)
0.060;-4060.0
(48)(9T)
0.101;-3087.8
9(48K)
0.065;-3709.4
(48TK)
0.085;-3534.1
TQ(48)
0.079;-3709.4
K(48J)
0.064;-3358.8
Q(48Q)
0.120;-2211.2
KK(48)
0.139;-1860.6
88(4J)
0.093;-3087.8
488K
0.075;-3884.7
8J(49)
0.050;-4060.0
(89)(4T)
0.106;-3087.8
4Q(89)
0.063;-3884.7
489T
0.041;-5382.8
489Q
0.042;-5032.2
(4T)(8J)
0.107;-2737.2
4T(8T)
0.070;-2912.5
4(8TK)
0.078;-3534.1
4T(8Q)
0.084;-3709.4
8J(4J)
0.096;-2561.9
(8J)(4Q)
0.085;-2386.6
4J(8Q)
0.071;-3534.1
8Q(4Q)
0.110;-2211.2
48QQ
0.084;-3358.8
48KK
0.114;-3008.1
9(49Q)
0.105;-2561.9
J(49T)
0.064;-3709.4
TJ(49)
0.088;-3709.4
(49JQ)
0.075;-3358.8
J(49K)
0.085;-3183.4
(49)(QK)
0.137;-1860.6
99(4J)
0.095;-2737.2
499K
0.080;-3534.1
9Q(4T)
0.069;-3534.1
(9T)(4Q)
0.094;-2386.6
4T(9J)
0.080;-3709.4
4T(9K)
0.072;-3358.8
9(4JK)
0.073;-3183.4
4(9JK)
0.070;-3183.4
4J(9K)
0.071;-3183.4
4Q(9Q)
0.130;-2035.9
49QK
0.069;-4155.6
TJ(4T)
0.111;-2386.6
(4TJQ)
0.093;-3183.4
J(4TK)
0.096;-3008.1
(4T)(QK)
0.119;-1685.3
TT(4Q)
0.126;-2211.2
T(4JQ)
0.067;-3183.4
4(TJQ)
0.061;-3183.4
4T(JQ)
0.081;-3183.4
T(4QK)
0.108;-2832.8
TQ(4K)
0.091;-2832.8
JJ(4J)
0.157;-888.4
(4JQK)
0.097;-2657.5
4JJJ
0.112;-2035.9
JQ(4Q)
0.117;-1685.3
4JQQ
0.116;-2832.8
4JKK
0.123;-2482.2
QQ(4K)
0.124;-1334.7
4KKK
0.133;-984.1
55(59)
0.098;-3167.5
55(5K)
0.121;-2466.3
(56)(58)
0.071;-3167.5
5(56J)
0.051;-3789.1
5K(56)
0.093;-3438.4
56(59)
0.058;-4139.7
556J
0.035;-4936.6
57(57)
0.071;-3167.5
(57)(5T)
0.086;-2641.6
5(57K)
0.100;-3263.1
55(79)
0.085;-3964.4
57(5Q)
0.080;-3438.4
5(589)
0.067;-3789.1
5J(58)
0.077;-3438.4
58(59)
0.070;-3789.1
558J
0.050;-4585.9
59(59)
0.116;-2466.3
(59)(5Q)
0.107;-1940.3
559T
0.052;-4585.9
55(9K)
0.076;-2912.5
(5T)(5Q)
0.116;-1765.0
55TJ
0.064;-4235.3
5J(5J)
0.137;-1765.0
5J(5Q)
0.088;-2737.2
5(5QK)
0.106;-2386.6
5K(5K)
0.177;-1063.8
68(56)
0.073;-4139.7
(56)(6J)
0.112;-2466.2
7(567)
0.058;-4139.7
J(567)
0.070;-4585.9
78(56)
0.035;-5111.9
(56)(7J)
0.062;-3438.4
8(568)
0.063;-3789.1
Q(568)
0.067;-4235.3
(56)(8T)
0.072;-3438.4
8(56K)
0.059;-4060.0
(569Q)
0.068;-4060.0
9(56J)
0.057;-4235.3
9K(56)
0.065;-3884.7
TT(56)
0.071;-3087.8
(56)(TK)
0.079;-2561.9
J(56Q)
0.056;-3709.4
K(56Q)
0.069;-3358.8
66(57)
0.056;-4315.0
5669
0.050;-5111.9
56(6Q)
0.068;-3438.4
(57)(68)
0.078;-3964.4
6(57J)
0.046;-4585.9
6K(57)
0.049;-4235.3
(67)(5T)
0.073;-3613.8
5Q(67)
0.064;-4410.6
5678
0.025;-6259.4
567T
0.023;-5908.8
567Q
0.029;-5558.1
(58)(69)
0.090;-3613.8
6(58Q)
0.052;-4235.3
5(689)
0.050;-4761.2
(68)(5Q)
0.088;-3087.8
58(69)
0.053;-4761.2
58(6J)
0.053;-4410.6
58(6K)
0.052;-4060.0
6(59J)
0.051;-4235.3
6K(59)
0.062;-3884.7
(69)(5Q)
0.071;-2912.5
59(6T)
0.054;-4410.6
59(6Q)
0.076;-4060.0
6T(5T)
0.102;-3087.8
(5T)(6K)
0.109;-2561.9
5Q(6T)
0.054;-3884.7
56TJ
0.034;-5207.5
56TK
0.043;-4856.9
6K(5J)
0.080;-3534.1
56JJ
0.053;-3884.7
56JK
0.040;-4681.6
5(6QK)
0.081;-3358.8
6K(5K)
0.094;-2035.9
(57)(79)
0.099;-2466.2
7(57Q)
0.076;-3087.8
9(578)
0.055;-4585.9
K(578)
0.058;-3884.7
8(57J)
0.066;-4235.3
8K(57)
0.066;-3884.7
(579K)
0.073;-3709.4
9J(57)
0.073;-4060.0
(57TJ)
0.054;-3884.7
(57)(TJ)
0.103;-2737.2
J(57J)
0.097;-2561.9
JQ(57)
0.076;-3534.1
Q(57K)
0.087;-3183.4
5778
0.052;-4936.6
57(7J)
0.068;-3263.1
(58)(78)
0.132;-2466.2
7(58J)
0.046;-4235.3
7K(58)
0.053;-3884.7
(78)(5J)
0.089;-3087.8
5K(78)
0.071;-3884.7
57(8T)
0.066;-4410.6
57(8Q)
0.062;-4060.0
7(59T)
0.052;-4235.3
7Q(59)
0.068;-3884.7
(79)(5J)
0.084;-2912.5
5K(79)
0.062;-3709.4
57(9J)
0.066;-4060.0
57(9K)
0.056;-3709.4
(5T)(7Q)
0.087;-2561.9
5J(7T)
0.078;-3884.7
7T(5J)
0.061;-3884.7
7T(5K)
0.057;-3534.1
7Q(5J)
0.078;-3534.1
(7J)(5K)
0.133;-2211.3
7J(5K)
0.081;-3358.8
7K(5Q)
0.101;-3183.4
57(QK)
0.090;-3183.4
(58)(89)
0.113;-2115.6
8(58Q)
0.105;-2737.2
T(589)
0.063;-4060.0
9(58T)
0.064;-4060.0
9Q(58)
0.075;-3709.4
Q(58T)
0.088;-3534.1
(58)(TQ)
0.093;-2386.6
(58JK)
0.093;-3183.4
JK(58)
0.070;-3183.4
K(58K)
0.125;-1685.3
588T
0.059;-4235.3
58(8K)
0.087;-2561.9
(59)(8J)
0.083;-2737.2
59(89)
0.079;-3087.8
5(89Q)
0.069;-3709.4
58(9T)
0.055;-4060.0
58(9Q)
0.073;-3709.4
8(5TJ)
0.056;-3709.4
8K(5T)
0.066;-3358.8
(8T)(5K)
0.136;-2211.3
8T(5Q)
0.062;-3534.1
(5J)(8J)
0.167;-1239.1
5J(8J)
0.128;-2386.6
8J(5Q)
0.083;-3358.8
(5Q)(8Q)
0.153;-888.4
5K(8Q)
0.084;-3008.1
5K(8K)
0.127;-1685.3
9J(59)
0.127;-2561.9
(59TJ)
0.064;-3534.1
(59)(TJ)
0.105;-2386.6
J(59J)
0.101;-2211.2
JQ(59)
0.088;-3183.4
Q(59K)
0.107;-2832.8
599T
0.084;-3884.7
59(9K)
0.089;-2211.2
(5T)(9Q)
0.144;-2211.3
5J(9T)
0.069;-3534.1
9T(5J)
0.067;-3534.1
9T(5K)
0.093;-3183.4
9Q(5J)
0.080;-3183.4
(9J)(5K)
0.126;-1860.6
9J(5K)
0.113;-3008.1
9K(5Q)
0.111;-2832.8
59(QK)
0.086;-2832.8
(5T)(TJ)
0.134;-1063.7
J(5TJ)
0.117;-2035.9
JQ(5T)
0.088;-3008.1
Q(5TK)
0.088;-2657.5
5TTJ
0.065;-3358.8
TJ(5J)
0.149;-2035.9
(TJ)(5Q)
0.143;-1860.6
5J(TQ)
0.098;-3008.1
TQ(5Q)
0.112;-1685.3
5TQQ
0.105;-2832.8
5TKK
0.127;-2482.2
Q(5JQ)
0.152;-1510.0
KK(5J)
0.165;-1159.4
(5Q)(JQ)
0.206;-362.5
5K(JQ)
0.098;-2482.2
5K(JK)
0.132;-1159.4
5QQQ
0.116;-1334.7
KK(5K)
0.161;338.7
6669
0.073;-3789.1
666K
0.068;-3087.8
69(67)
0.091;-3613.8
(67)(6Q)
0.138;-1940.3
6678
0.042;-4936.6
66(7J)
0.085;-3263.1
(68)(68)
0.121;-1318.8
6(68J)
0.081;-3087.8
6K(68)
0.085;-2737.2
68(6J)
0.096;-3087.8
668K
0.082;-3884.7
6J(69)
0.072;-2912.5
69(6T)
0.090;-3087.8
669Q
0.074;-3884.7
6J(6T)
0.106;-2737.2
6T(6J)
0.092;-2737.2
66TK
0.082;-3534.1
6K(6J)
0.145;-2211.2
(6Q)(6Q)
0.181;83.7
66QK
0.082;-3183.4
7(679)
0.070;-3438.4
7J(67)
0.086;-3087.8
(6789)
0.060;-4410.6
(678K)
0.084;-3709.4
8T(67)
0.054;-4235.3
(67)(8K)
0.120;-2561.9
Q(679)
0.058;-3709.4
(67)(9J)
0.113;-2737.2
T(67T)
0.100;-2737.2
T(67J)
0.068;-3709.4
TK(67)
0.075;-3358.8
(67)(JQ)
0.123;-2211.3
QQ(67)
0.144;-2035.9
67(78)
0.067;-3613.8
77(6J)
0.097;-3087.8
677K
0.060;-3884.7
7T(68)
0.051;-4235.3
(68)(7K)
0.085;-2561.9
6T(78)
0.054;-4235.3
6(78K)
0.066;-3709.4
68(7T)
0.058;-4235.3
68(7Q)
0.063;-3884.7
79(69)
0.098;-3087.8
(69)(7Q)
0.096;-2561.9
6T(79)
0.049;-4060.0
6(79K)
0.092;-3534.1
69(7J)
0.062;-3884.7
69(7K)
0.084;-3534.1
7(6TQ)
0.072;-3534.1
6(7TJ)
0.093;-3709.4
67TT
0.052;-3884.7
67TQ
0.050;-4681.6
(6J)(7Q)
0.132;-2211.3
6Q(7J)
0.086;-3358.8
67JQ
0.041;-4506.2
(6Q)(7K)
0.126;-1860.6
6Q(7K)
0.075;-3008.1
8(689)
0.102;-3087.8
8J(68)
0.076;-2737.2
(689T)
0.057;-3884.7
99(68)
0.086;-2912.5
(68)(9Q)
0.087;-2386.6
(68TQ)
0.065;-3358.8
T(68Q)
0.093;-3358.8
Q(68J)
0.092;-3183.4
(68)(JK)
0.148;-1860.6
QK(68)
0.087;-2832.8
68(8T)
0.105;-2912.5
88(6K)
0.081;-2386.6
8(69J)
0.074;-3709.4
8K(69)
0.078;-3358.8
(89)(6Q)
0.101;-2386.6
69(8T)
0.073;-3884.7
69(8Q)
0.072;-3534.1
8T(6T)
0.079;-2561.9
(6T)(8K)
0.150;-2035.9
6Q(8T)
0.086;-3358.8
68TJ
0.039;-4681.6
68TK
0.056;-4330.9
8K(6J)
0.096;-3008.1
68JJ
0.072;-3358.8
68JK
0.056;-4155.6
6(8QK)
0.084;-2832.8
8K(6K)
0.135;-1510.0
(69)(9J)
0.132;-1239.1
T(69T)
0.124;-2386.6
T(69J)
0.068;-3358.8
TK(69)
0.085;-3008.1
(69)(JQ)
0.113;-1860.6
QQ(69)
0.157;-1685.3
69(9T)
0.083;-2561.9
99(6K)
0.129;-2035.9
9(6TQ)
0.089;-3183.4
6(9TJ)
0.066;-3358.8
69TT
0.095;-3534.1
69TQ
0.052;-4330.9
(6J)(9Q)
0.132;-1860.6
6Q(9J)
0.082;-3008.1
69JQ
0.050;-4155.6
(6Q)(9K)
0.138;-1510.0
6Q(9K)
0.119;-2657.5
T(6TJ)
0.130;-2035.9
TK(6T)
0.155;-1685.3
(6T)(JQ)
0.146;-1685.3
QQ(6T)
0.116;-1510.0
6T(TJ)
0.108;-2035.9
(6J)(TJ)
0.194;-713.1
6J(TJ)
0.117;-1860.6
TJ(6Q)
0.084;-2832.8
(6Q)(TQ)
0.187;-362.5
6K(TQ)
0.113;-2482.2
6K(TK)
0.175;-1159.4
JK(6J)
0.122;-1334.7
K(6JK)
0.144;-984.1
6JJK
0.086;-2482.2
6(JQK)
0.113;-2306.9
JK(6K)
0.164;-984.1
KK(6Q)
0.149;-808.8
6QKK
0.102;-1956.2
77(7T)
0.142;-1940.3
(78)(78)
0.161;-968.1
7(78J)
0.122;-2737.2
7K(78)
0.122;-2386.6
78(7J)
0.093;-2737.2
778K
0.078;-3534.1
7J(79)
0.105;-2561.9
79(7T)
0.097;-2737.2
779Q
0.077;-3534.1
7J(7T)
0.099;-2386.6
7T(7J)
0.132;-2386.6
77TK
0.076;-3183.4
7K(7J)
0.119;-1860.6
(7Q)(7Q)
0.218;434.4
77QK
0.105;-2832.8
8(78T)
0.091;-2737.2
8Q(78)
0.117;-2386.6
J(789)
0.095;-3534.1
9T(78)
0.074;-3709.4
(78)(9K)
0.137;-2035.9
K(78T)
0.094;-3008.1
T(78K)
0.096;-3008.1
JJ(78)
0.127;-2035.9
(78QK)
0.087;-2657.5
7888
0.082;-3087.8
78(8J)
0.131;-2561.9
(79)(89)
0.151;-1589.7
8(79Q)
0.095;-3358.8
7(89T)
0.059;-3709.4
(89)(7K)
0.104;-2035.9
89(7J)
0.082;-3534.1
89(7K)
0.075;-3183.4
8J(7T)
0.079;-3358.8
(8T)(7J)
0.128;-2211.3
7K(8T)
0.102;-3008.1
78(TQ)
0.085;-3183.4
8(7JQ)
0.076;-3008.1
7(8JQ)
0.074;-3008.1
78(JQ)
0.081;-3008.1
8(7QK)
0.104;-2657.5
8Q(7K)
0.087;-2657.5
99(79)
0.146;-1414.4
(79)(9Q)
0.157;-888.4
(79TQ)
0.105;-3008.1
T(79Q)
0.079;-3008.1
Q(79J)
0.111;-2832.8
(79)(JK)
0.119;-1510.0
QK(79)
0.115;-2482.2
79(9J)
0.107;-2211.2
(7T)(9T)
0.135;-1063.7
9(7TK)
0.110;-2832.8
7(9TQ)
0.088;-3008.1
79(TJ)
0.085;-3183.4
79(TK)
0.083;-2832.8
(7J)(9K)
0.154;-1510.0
7K(9J)
0.108;-2657.5
79(JK)
0.110;-2657.5
(9Q)(7K)
0.162;-1334.7
(7K)(9K)
0.204;-11.9
T(7TQ)
0.143;-1685.3
Q(7TJ)
0.109;-2657.5
(7T)(JK)
0.137;-1334.7
QK(7T)
0.120;-2306.9
7T(TQ)
0.145;-1685.3
(7J)(TQ)
0.116;-1510.0
7Q(TJ)
0.107;-2657.5
7TJQ
0.073;-3805.0
(7Q)(TK)
0.140;-1159.4
7Q(TK)
0.139;-2306.9
J(7JQ)
0.149;-1334.7
K(7JQ)
0.103;-2131.6
JJ(7Q)
0.163;-1334.7
J(7QK)
0.133;-2131.6
JQ(7K)
0.118;-2131.6
QQ(7Q)
0.199;163.4
7Q(QK)
0.153;-808.8
8888
0.100;-1765.0
888Q
0.112;-2211.3
8(89J)
0.092;-2211.2
8K(89)
0.129;-1860.6
89(8Q)
0.125;-2035.9
8(8TJ)
0.151;-2035.9
8K(8T)
0.140;-1685.3
8T(8K)
0.125;-1685.3
8(8JK)
0.119;-1510.0
88(JK)
0.163;-1510.0
8Q(8K)
0.175;-1334.7
(89)(9T)
0.121;-1063.7
9(89K)
0.147;-1685.3
(89TK)
0.112;-2657.5
TQ(89)
0.077;-2832.8
K(89J)
0.095;-2482.2
Q(89Q)
0.131;-1334.7
KK(89)
0.154;-984.1
99(8Q)
0.127;-1860.6
9(8TJ)
0.110;-3008.1
9K(8T)
0.099;-2657.5
(9T)(8K)
0.124;-1510.0
9T(8Q)
0.094;-2832.8
(8J)(9J)
0.217;-537.8
8J(9J)
0.133;-1685.3
9J(8Q)
0.111;-2657.5
(8Q)(9Q)
0.180;-187.2
8K(9Q)
0.103;-2306.9
8K(9K)
0.155;-984.1
TQ(8T)
0.150;-1510.0
K(8TJ)
0.103;-2306.9
Q(8TQ)
0.168;-1159.4
KK(8T)
0.181;-808.8
