AAAA
0.341;-5190.0
5AAA
0.354;-17373.7
9AAA
0.335;-14238.7
KAAA
0.382;-11103.7
4A(2A)
0.269;-27562.5
(2A)(7A)
0.308;-20081.3
A(2TA)
0.242;-22860.0
QA(2A)
0.297;-21292.5
2A(4A)
0.250;-27562.5
26AA
0.228;-31125.0
AA(29)
0.258;-23643.7
2A(QA)
0.295;-21292.5
A(34A)
0.271;-26778.8
6A(3A)
0.277;-25211.2
(3A)(9A)
0.263;-17730.0
A(3QA)
0.279;-20508.8
AA(34)
0.205;-26778.8
3A(7A)
0.261;-24427.5
39AA
0.241;-27990.0
AA(3Q)
0.280;-20508.8
(4A)(5A)
0.340;-20081.3
A(48A)
0.249;-22860.0
TA(4A)
0.261;-21292.5
(4A)(KA)
0.254;-13811.2
46AA
0.246;-29557.5
AA(49)
0.217;-22076.2
4A(QA)
0.256;-19725.0
A(56A)
0.252;-23643.7
8A(5A)
0.263;-22076.2
(5A)(JA)
0.302;-14595.0
55AA
0.301;-24427.5
AA(58)
0.260;-22076.2
5A(JA)
0.254;-19725.0
5KAA
0.270;-23287.5
8A(6A)
0.230;-21292.5
(6A)(JA)
0.285;-13811.2
66AA
0.234;-22860.0
AA(69)
0.281;-20508.8
6A(QA)
0.351;-18157.5
A(78A)
0.319;-20508.8
TA(7A)
0.331;-18941.2
(7A)(KA)
0.282;-11460.0
79AA
0.272;-24855.0
AA(7Q)
0.286;-17373.8
(8A)(9A)
0.341;-13811.2
A(8QA)
0.306;-16590.0
AA(89)
0.316;-18941.2
8A(QA)
0.274;-16590.0
A(9TA)
0.294;-17373.8
QA(9A)
0.309;-15806.3
9A(JA)
0.273;-16590.0
9KAA
0.310;-20152.5
QA(TA)
0.278;-15022.5
TA(QA)
0.323;-15022.5
A(JQA)
0.296;-14238.8
AA(JQ)
0.303;-14238.8
(QA)(KA)
0.355;-7541.3
KKAA
0.395;-11887.5
2(25A)
0.183;-36183.7
27(2A)
0.207;-34616.2
(2T)(2A)
0.212;-27135.0
2(2KA)
0.233;-29913.7
(236A)
0.206;-39746.2
(23TA)
0.235;-36611.2
33(2A)
0.216;-36967.5
(36)(2A)
0.190;-34616.2
3(29A)
0.232;-37395.0
3J(2A)
0.203;-35827.5
(245A)
0.204;-39746.2
(249A)
0.228;-36611.2
(24KA)
0.250;-33476.2
46(2A)
0.147;-38962.5
(49)(2A)
0.243;-31481.2
4(2QA)
0.231;-34260.0
6(25A)
0.186;-38178.8
T(25A)
0.186;-35043.7
5(26A)
0.242;-38178.8
58(2A)
0.184;-36611.2
(5J)(2A)
0.237;-29130.0
6(26A)
0.205;-32265.0
T(26A)
0.193;-34260.0
6(27A)
0.203;-36611.2
69(2A)
0.168;-35043.7
(6Q)(2A)
0.220;-27562.5
(279A)
0.207;-34260.0
(27KA)
0.203;-31125.0
79(2A)
0.187;-34260.0
(7Q)(2A)
0.241;-26778.8
(28TA)
0.263;-32692.5
88(2A)
0.216;-29130.0
(8J)(2A)
0.255;-26778.8
9(29A)
0.227;-27562.5
K(29A)
0.194;-29557.5
9(2QA)
0.182;-30341.2
J(2TA)
0.243;-30341.2
TJ(2A)
0.227;-30341.2
(2JQA)
0.239;-28773.7
J(2KA)
0.204;-27990.0
(QK)(2A)
0.246;-22076.2
22(4A)
0.262;-36967.5
226A
0.164;-40530.0
2A(29)
0.213;-33048.8
22(QA)
0.210;-30697.5
2(34A)
0.207;-41313.8
26(3A)
0.194;-39746.2
(29)(3A)
0.219;-32265.0
2(3QA)
0.198;-35043.7
A(234)
0.221;-41313.8
(23)(7A)
0.217;-33832.5
9A(23)
0.187;-37395.0
A(23Q)
0.186;-35043.7
2A(34)
0.180;-41313.8
2A(36)
0.169;-39746.2
2A(38)
0.250;-38178.8
2A(3T)
0.171;-36611.2
2A(3Q)
0.237;-35043.7
2(45A)
0.192;-39746.2
27(4A)
0.246;-38178.8
(2T)(4A)
0.229;-30697.5
2(4KA)
0.211;-33476.2
A(246)
0.183;-38962.5
(24)(9A)
0.261;-31481.2
JA(24)
0.167;-35043.7
24(5A)
0.181;-39746.2
24(7A)
0.190;-38178.8
24(9A)
0.190;-36611.2
24(JA)
0.208;-35043.7
24(KA)
0.201;-33476.2
26(5A)
0.145;-38178.8
(29)(5A)
0.273;-30697.5
2(5QA)
0.188;-33476.2
A(256)
0.227;-38178.8
(25)(9A)
0.204;-30697.5
JA(25)
0.204;-34260.0
25(6A)
0.203;-38178.8
25(8A)
0.211;-36611.2
25(TA)
0.214;-35043.7
25(QA)
0.203;-33476.2
(26)(6A)
0.279;-27135.0
2(69A)
0.203;-35043.7
2J(6A)
0.249;-33476.2
(26)(7A)
0.222;-31481.2
9A(26)
0.159;-35043.7
A(26Q)
0.193;-32692.5
2A(67)
0.156;-36611.2
2A(69)
0.193;-35043.7
2A(6J)
0.232;-33476.2
2A(6K)
0.225;-31908.7
(29)(7A)
0.207;-29130.0
2(7QA)
0.211;-31908.7
A(278)
0.247;-35043.7
(27)(JA)
0.253;-27562.5
KA(27)
0.226;-31125.0
2A(79)
0.213;-34260.0
2A(7J)
0.209;-32692.5
2A(7K)
0.201;-31125.0
(2T)(8A)
0.215;-27562.5
2(8KA)
0.226;-30341.2
A(28T)
0.198;-32692.5
(28)(KA)
0.220;-25211.2
28(TA)
0.223;-32692.5
28(QA)
0.274;-31125.0
(29)(9A)
0.353;-22432.5
2(9QA)
0.252;-30341.2
A(29T)
0.183;-31908.7
(29)(KA)
0.262;-24427.5
29(JA)
0.254;-31125.0
29(KA)
0.227;-29557.5
2J(TA)
0.179;-30341.2
(2T)(JA)
0.297;-25211.2
KA(2T)
0.214;-28773.7
2A(TQ)
0.279;-29557.5
2(JQA)
0.221;-28773.7
A(2JQ)
0.262;-28773.7
2A(JQ)
0.225;-28773.7
2(QKA)
0.240;-27206.2
2Q(KA)
0.205;-27206.2
33(3A)
0.298;-31053.7
(36)(3A)
0.272;-28702.5
3(39A)
0.238;-31481.2
3J(3A)
0.270;-29913.7
(345A)
0.188;-38962.5
(349A)
0.192;-35827.5
(34KA)
0.181;-32692.5
46(3A)
0.182;-38178.8
(49)(3A)
0.274;-30697.5
4(3QA)
0.260;-33476.2
6(35A)
0.201;-37395.0
T(35A)
0.195;-34260.0
5(36A)
0.226;-37395.0
58(3A)
0.226;-35827.5
(5J)(3A)
0.217;-28346.2
6(36A)
0.253;-31481.2
T(36A)
0.233;-33476.2
6(37A)
0.221;-35827.5
69(3A)
0.258;-34260.0
(6Q)(3A)
0.270;-26778.8
(379A)
0.277;-33476.2
(37KA)
0.211;-30341.2
79(3A)
0.238;-33476.2
(7Q)(3A)
0.283;-25995.0
(38TA)
0.244;-31908.7
88(3A)
0.234;-28346.2
(8J)(3A)
0.322;-25995.0
9(39A)
0.225;-26778.8
K(39A)
0.263;-28773.7
9(3QA)
0.222;-29557.5
J(3TA)
0.252;-29557.5
TJ(3A)
0.218;-29557.5
(3JQA)
0.260;-27990.0
J(3KA)
0.226;-27206.2
(QK)(3A)
0.304;-21292.5
33(5A)
0.189;-34616.2
337A
0.258;-38178.8
3A(3T)
0.279;-30697.5
33(KA)
0.297;-28346.2
3(46A)
0.224;-38178.8
38(4A)
0.165;-36611.2
(3J)(4A)
0.228;-29130.0
4A(34)
0.212;-34616.2
A(347)
0.245;-37395.0
(34)(TA)
0.279;-29913.7
QA(34)
0.216;-33476.2
345A
0.164;-44092.5
347A
0.172;-42525.0
349A
0.172;-40957.5
34JA
0.160;-39390.0
34KA
0.195;-37822.5
37(5A)
0.193;-36611.2
(3T)(5A)
0.230;-29130.0
3(5KA)
0.223;-31908.7
A(357)
0.194;-36611.2
(35)(TA)
0.200;-29130.0
QA(35)
0.267;-32692.5
356A
0.199;-42525.0
358A
0.178;-40957.5
35TA
0.219;-39390.0
35QA
0.167;-37822.5
(37)(6A)
0.270;-30697.5
3(6TA)
0.234;-33476.2
3Q(6A)
0.186;-31908.7
(36)(8A)
0.186;-29913.7
TA(36)
0.227;-33476.2
A(36K)
0.234;-31125.0
6A(38)
0.168;-35043.7
6A(3T)
0.246;-33476.2
6A(3Q)
0.228;-31908.7
37(7A)
0.234;-29913.7
(3T)(7A)
0.205;-27562.5
3(7KA)
0.204;-30341.2
A(379)
0.212;-33476.2
(37)(QA)
0.295;-25995.0
7A(38)
0.192;-34260.0
7A(3T)
0.174;-32692.5
7A(3Q)
0.276;-31125.0
38(8A)
0.229;-28346.2
(3J)(8A)
0.280;-25995.0
8A(38)
0.233;-28346.2
A(38J)
0.238;-31125.0
388A
0.241;-33476.2
38TA
0.201;-37038.8
38QA
0.207;-35471.2
(3T)(9A)
0.241;-25995.0
3(9KA)
0.290;-28773.7
A(39J)
0.274;-30341.2
399A
0.221;-31908.7
39JA
0.239;-35471.2
39KA
0.251;-33903.7
3Q(TA)
0.248;-28773.7
(3T)(QA)
0.287;-23643.7
TA(3J)
0.224;-29557.5
TA(3K)
0.199;-27990.0
3(JKA)
0.218;-27206.2
A(3JK)
0.278;-27206.2
JA(3K)
0.321;-27206.2
QA(3Q)
0.256;-22076.2
3QKA
0.204;-31552.5
45(4A)
0.193;-33048.8
(48)(4A)
0.268;-25567.5
4(4JA)
0.313;-28346.2
4K(4A)
0.262;-26778.8
(459A)
0.226;-34260.0
(45KA)
0.235;-31125.0
57(4A)
0.168;-35827.5
(5T)(4A)
0.252;-28346.2
5(4KA)
0.242;-31125.0
(469A)
0.184;-33476.2
(46KA)
0.258;-30341.2
68(4A)
0.195;-34260.0
(6J)(4A)
0.275;-26778.8
7(47A)
0.249;-29130.0
J(47A)
0.243;-31125.0
78(4A)
0.227;-33476.2
(7J)(4A)
0.232;-25995.0
8(48A)
0.220;-27562.5
Q(48A)
0.232;-29557.5
(8T)(4A)
0.228;-25995.0
8(4KA)
0.259;-28773.7
(49QA)
0.284;-28773.7
9(4JA)
0.243;-29557.5
9K(4A)
0.251;-27990.0
TT(4A)
0.234;-24427.5
(TK)(4A)
0.293;-22076.2
J(4QA)
0.235;-27206.2
K(4QA)
0.253;-25638.7
44(5A)
0.226;-33048.8
447A
0.205;-36611.2
4A(4T)
0.282;-29130.0
44(KA)
0.235;-26778.8
4(57A)
0.201;-35827.5
49(5A)
0.196;-34260.0
(4Q)(5A)
0.185;-26778.8
6A(45)
0.195;-36611.2
A(459)
0.218;-34260.0
(45)(QA)
0.244;-26778.8
5A(46)
0.245;-36611.2
5A(48)
0.224;-35043.7
5A(4T)
0.183;-33476.2
5A(4Q)
0.246;-31908.7
46(6A)
0.260;-30697.5
(49)(6A)
0.252;-28346.2
4(6QA)
0.233;-31125.0
A(467)
0.218;-35043.7
(46)(TA)
0.214;-27562.5
QA(46)
0.209;-31125.0
467A
0.237;-40173.8
469A
0.184;-38606.2
46JA
0.247;-37038.8
46KA
0.176;-35471.2
49(7A)
0.220;-32692.5
(4Q)(7A)
0.262;-25211.2
8A(47)
0.285;-33476.2
A(47J)
0.209;-31125.0
477A
0.224;-34260.0
479A
0.173;-37822.5
47JA
0.200;-36255.0
47KA
0.199;-34687.5
4T(8A)
0.261;-31125.0
(4K)(8A)
0.306;-23643.7
TA(48)
0.174;-31125.0
A(48K)
0.250;-28773.7
8A(4T)
0.306;-31125.0
8A(4Q)
0.234;-29557.5
49(9A)
0.268;-25995.0
(4Q)(9A)
0.299;-23643.7
TA(49)
0.208;-30341.2
A(49K)
0.256;-27990.0
9A(4J)
0.228;-29557.5
9A(4K)
0.233;-27990.0
4(TQA)
0.238;-27990.0
A(4TJ)
0.240;-28773.7
4TTA
0.236;-29557.5
4TQA
0.216;-33120.0
(4Q)(JA)
0.254;-22076.2
QA(4J)
0.286;-27206.2
4JQA
0.282;-32336.2
(4K)(QA)
0.295;-20508.8
QA(4K)
0.262;-25638.7
5(56A)
0.205;-30697.5
58(5A)
0.196;-29130.0
(5J)(5A)
0.312;-21648.7
6(56A)
0.203;-29913.7
T(56A)
0.280;-31908.7
6(57A)
0.185;-34260.0
69(5A)
0.187;-32692.5
(6Q)(5A)
0.284;-25211.2
(579A)
0.228;-31908.7
(57KA)
0.239;-28773.7
79(5A)
0.244;-31908.7
(7Q)(5A)
0.274;-24427.5
(58TA)
0.290;-30341.2
88(5A)
0.234;-26778.8
(8J)(5A)
0.281;-24427.5
9(59A)
0.264;-25211.2
K(59A)
0.292;-27206.2
9(5QA)
0.251;-27990.0
J(5TA)
0.219;-27990.0
TJ(5A)
0.238;-27990.0
(5JQA)
0.309;-26422.5
J(5KA)
0.196;-25638.7
(QK)(5A)
0.301;-19725.0
55(7A)
0.236;-29913.7
559A
0.262;-33476.2
5A(5Q)
0.213;-25995.0
(57)(6A)
0.201;-29130.0
5(6TA)
0.198;-31908.7
5Q(6A)
0.247;-30341.2
(56)(8A)
0.207;-28346.2
TA(56)
0.226;-31908.7
A(56K)
0.255;-29557.5
6A(58)
0.271;-33476.2
6A(5T)
0.212;-31908.7
6A(5Q)
0.248;-30341.2
57(7A)
0.227;-28346.2
(5T)(7A)
0.255;-25995.0
5(7KA)
0.239;-28773.7
A(579)
0.212;-31908.7
(57)(QA)
0.255;-24427.5
7A(58)
0.237;-32692.5
7A(5T)
0.261;-31125.0
7A(5Q)
0.195;-29557.5
58(8A)
0.266;-26778.8
(5J)(8A)
0.292;-24427.5
8A(58)
0.294;-26778.8
A(58J)
0.229;-29557.5
588A
0.263;-31908.7
58TA
0.235;-35471.2
58QA
0.260;-33903.7
(5T)(9A)
0.291;-24427.5
5(9KA)
0.260;-27206.2
A(59J)
0.273;-28773.7
599A
0.209;-30341.2
59JA
0.252;-33903.7
59KA
0.230;-32336.2
5Q(TA)
0.290;-27206.2
(5T)(QA)
0.250;-22076.2
TA(5J)
0.194;-27990.0
TA(5K)
0.292;-26422.5
5(JKA)
0.268;-25638.7
A(5JK)
0.244;-25638.7
JA(5K)
0.242;-25638.7
QA(5Q)
0.314;-20508.8
5QKA
0.275;-29985.0
67(6A)
0.214;-28346.2
(6T)(6A)
0.296;-20865.0
6(6KA)
0.228;-23643.7
(67TA)
0.252;-30341.2
77(6A)
0.196;-27562.5
(7T)(6A)
0.238;-25211.2
7(6KA)
0.248;-27990.0
(68JA)
0.257;-28773.7
(89)(6A)
0.216;-25211.2
8(6QA)
0.223;-27990.0
T(69A)
0.245;-28773.7
9(6TA)
0.251;-28773.7
9Q(6A)
0.249;-27206.2
Q(6TA)
0.223;-26422.5
(TQ)(6A)
0.307;-21292.5
(6JKA)
0.282;-24855.0
JK(6A)
0.271;-24855.0
K(6KA)
0.301;-18157.5
668A
0.200;-32692.5
6A(6J)
0.292;-25211.2
(67)(7A)
0.272;-22432.5
6(7TA)
0.275;-30341.2
6Q(7A)
0.212;-28773.7
(67)(9A)
0.218;-25995.0
JA(67)
0.266;-29557.5
67(8A)
0.194;-31908.7
67(TA)
0.225;-30341.2
67(QA)
0.290;-28773.7
(68)(8A)
0.333;-20865.0
6(8JA)
0.272;-28773.7
6K(8A)
0.235;-27206.2
(68)(JA)
0.252;-23643.7
KA(68)
0.248;-27206.2
6A(8T)
0.284;-29557.5
6A(8Q)
0.208;-27990.0
6(9TA)
0.197;-28773.7
6Q(9A)
0.237;-27206.2
(69)(JA)
0.264;-22860.0
KA(69)
0.238;-26422.5
6A(9J)
0.232;-27990.0
6A(9K)
0.253;-26422.5
(6Q)(TA)
0.246;-21292.5
JA(6T)
0.282;-27206.2
6T(JA)
0.253;-27206.2
6T(KA)
0.267;-25638.7
6Q(JA)
0.224;-25638.7
(6J)(KA)
0.258;-19725.0
6J(KA)
0.322;-24855.0
6K(QA)
0.239;-24071.2
6A(QK)
0.270;-24071.2
(78)(7A)
0.289;-20865.0
7(7JA)
0.275;-23643.7
7K(7A)
0.285;-22076.2
(78QA)
0.257;-27206.2
8(7TA)
0.183;-28773.7
8Q(7A)
0.260;-27206.2
J(79A)
0.267;-27206.2
9T(7A)
0.250;-27990.0
(9K)(7A)
0.296;-20508.8
K(7TA)
0.212;-24855.0
T(7KA)
0.258;-24855.0
JJ(7A)
0.262;-20508.8
(7QKA)
0.305;-23287.5
777A
0.284;-26778.8
7A(7T)
0.333;-24427.5
77(KA)
0.291;-22076.2
7(8TA)
0.257;-28773.7
7Q(8A)
0.267;-27206.2
(78)(TA)
0.265;-23643.7
QA(78)
0.239;-27206.2
789A
0.192;-34687.5
78JA
0.261;-33120.0
78KA
0.279;-31552.5
7J(9A)
0.250;-27206.2
(79)(TA)
0.314;-22860.0
QA(79)
0.256;-26422.5
79TA
0.195;-33120.0
79QA
0.199;-31552.5
(7J)(TA)
0.226;-21292.5
TA(7T)
0.310;-22076.2
A(7TK)
0.234;-24855.0
TA(7Q)
0.260;-25638.7
7J(JA)
0.250;-20508.8
(7J)(QA)
0.352;-19725.0
JA(7Q)
0.291;-24855.0
7Q(QA)
0.254;-18941.2
7QQA
0.197;-24071.2
7KKA
0.232;-22503.8
8(8JA)
0.310;-22076.2
8K(8A)
0.278;-20508.8
(89KA)
0.287;-24855.0
9J(8A)
0.282;-26422.5
(8TJA)
0.252;-25638.7
(TJ)(8A)
0.348;-20508.8
J(8JA)
0.336;-19725.0
JQ(8A)
0.215;-24071.2
Q(8KA)
0.323;-22503.8
889A
0.224;-28773.7
8A(8Q)
0.305;-21292.5
(8T)(9A)
0.230;-22076.2
8(9KA)
0.220;-24855.0
A(89J)
0.287;-26422.5
899A
0.253;-27990.0
89JA
0.197;-31552.5
89KA
0.224;-29985.0
8Q(TA)
0.321;-24855.0
(8T)(QA)
0.295;-19725.0
TA(8J)
0.222;-25638.7
TA(8K)
0.261;-24071.2
8(JKA)
0.292;-23287.5
A(8JK)
0.298;-23287.5
JA(8K)
0.257;-23287.5
QA(8Q)
0.298;-18157.5
8QKA
0.245;-27633.8
9T(9A)
0.319;-21292.5
(9K)(9A)
0.280;-13811.2
K(9TA)
0.290;-23287.5
T(9KA)
0.307;-23287.5
JJ(9A)
0.303;-18941.2
(9QKA)
0.273;-21720.0
999A
0.287;-22076.2
9A(9Q)
0.297;-19725.0
(9J)(TA)
0.278;-19725.0
TA(9T)
0.323;-20508.8
A(9TK)
0.223;-23287.5
TA(9Q)
0.255;-24071.2
9J(JA)
0.284;-18941.2
(9J)(QA)
0.291;-18157.5
JA(9Q)
0.319;-23287.5
9Q(QA)
0.313;-17373.8
9QQA
0.212;-22503.8
9KKA
0.325;-20936.2
T(TKA)
0.252;-17373.8
JJ(TA)
0.282;-18157.5
(TQKA)
0.280;-20936.2
TTTA
0.219;-19725.0
TA(TK)
0.276;-17373.8
(TK)(JA)
0.354;-16590.0
KA(TJ)
0.320;-21720.0
TA(JK)
0.272;-21720.0
(TQ)(KA)
0.250;-15806.3
(TK)(KA)
0.329;-9892.5
J(JKA)
0.371;-15806.3
(QK)(JA)
0.288;-15022.5
JJ(KA)
0.329;-15806.3
QA(JQ)
0.284;-15806.3
JQKA
0.270;-25282.5
QK(QA)
0.290;-14238.8
QK(KA)
0.264;-13455.0
22(24)
0.194;-41242.5
22(28)
0.223;-38107.5
22(2Q)
0.211;-34972.5
24(23)
0.159;-45588.8
(23)(27)
0.194;-38107.5
2(23T)
0.218;-40886.3
2Q(23)
0.157;-39318.7
23(25)
0.178;-44805.0
2237
0.197;-48367.5
22(3T)
0.250;-40886.3
23(2K)
0.213;-38535.0
2(246)
0.222;-43237.5
28(24)
0.155;-41670.0
(24)(2J)
0.218;-34188.8
2244
0.185;-44805.0
22(47)
0.199;-42453.8
24(2T)
0.187;-40102.5
224Q
0.222;-43665.0
26(25)
0.193;-42453.8
(25)(29)
0.220;-34972.5
2(25Q)
0.208;-37751.2
22(56)
0.188;-42453.8
25(29)
0.207;-40102.5
225J
0.195;-43665.0
26(26)
0.183;-36540.0
(26)(29)
0.195;-34188.8
2(26Q)
0.202;-36967.5
22(67)
0.200;-40886.3
26(2T)
0.224;-38535.0
226Q
0.178;-42097.5
28(27)
0.239;-39318.7
(27)(2J)
0.176;-31837.5
2277
0.175;-40102.5
22(7T)
0.206;-37751.2
27(2K)
0.201;-35400.0
2(28T)
0.209;-36967.5
2Q(28)
0.252;-35400.0
28(2T)
0.193;-36967.5
228Q
0.214;-40530.0
2T(29)
0.154;-36183.7
(29)(2K)
0.286;-28702.5
229J
0.166;-40530.0
2T(2T)
0.221;-30270.0
(2T)(2K)
0.238;-27918.7
22TQ
0.164;-38962.5
2Q(2J)
0.218;-33048.8
2J(2K)
0.203;-32265.0
22QQ
0.196;-32265.0
3(234)
0.205;-44805.0
36(23)
0.221;-43237.5
(23)(39)
0.205;-35756.2
3(23Q)
0.175;-38535.0
5(234)
0.130;-48367.5
9(234)
0.169;-45232.5
K(234)
0.164;-42097.5
4(237)
0.161;-46800.0
49(23)
0.187;-45232.5
(23)(4Q)
0.222;-37751.2
(2357)
0.159;-46016.2
(235J)
0.153;-42881.2
(23)(56)
0.182;-41670.0
5(239)
0.157;-44448.8
5J(23)
0.142;-42881.2
(2367)
0.199;-45232.5
(236J)
0.180;-42097.5
(23)(67)
0.215;-40102.5
6(23T)
0.164;-42881.2
6Q(23)
0.235;-41313.8
9(237)
0.156;-42881.2
K(237)
0.194;-39746.2
7(23T)
0.152;-42097.5
7Q(23)
0.152;-40530.0
T(238)
0.232;-41313.8
8(239)
0.167;-42097.5
8J(23)
0.211;-40530.0
(239T)
0.193;-40530.0
99(23)
0.236;-36183.7
(23)(9Q)
0.226;-33832.5
(23TQ)
0.185;-38178.8
T(23Q)
0.217;-38178.8
Q(23J)
0.194;-37395.0
(23)(JK)
0.199;-31481.2
QK(23)
0.263;-35827.5
23(35)
0.170;-44021.2
33(28)
0.191;-41670.0
233T
0.168;-45232.5
23(3K)
0.196;-37751.2
(24)(36)
0.212;-42453.8
3(249)
0.197;-45232.5
3J(24)
0.219;-43665.0
(34)(25)
0.140;-43237.5
27(34)
0.151;-46800.0
2(34T)
0.202;-44448.8
(34)(2K)
0.201;-36967.5
34(26)
0.150;-47583.7
34(28)
0.203;-46016.2
34(2T)
0.154;-44448.8
34(2Q)
0.216;-42881.2
(25)(35)
0.175;-37323.8
3(258)
0.155;-45232.5
3T(25)
0.204;-43665.0
(25)(3K)
0.172;-36183.7
27(35)
0.151;-46016.2
2(35T)
0.148;-43665.0
(35)(2K)
0.204;-36183.7
35(27)
0.146;-46016.2
35(29)
0.145;-44448.8
35(2J)
0.181;-42881.2
35(2K)
0.169;-41313.8
37(26)
0.155;-45232.5
(26)(3T)
0.238;-37751.2
3(26K)
0.203;-40530.0
2(368)
0.170;-44448.8
(36)(2J)
0.208;-36967.5
2K(36)
0.192;-40530.0
23(68)
0.196;-44448.8
23(6T)
0.178;-42881.2
23(6Q)
0.194;-41313.8
3(278)
0.195;-43665.0
3T(27)
0.140;-42097.5
(27)(3K)
0.216;-34616.2
29(37)
0.168;-42881.2
2(37Q)
0.148;-40530.0
23(78)
0.135;-43665.0
23(7T)
0.218;-42097.5
23(7Q)
0.237;-40530.0
3(289)
0.200;-42097.5
3J(28)
0.175;-40530.0
(38)(29)
0.226;-36967.5
2J(38)
0.174;-40530.0
38(29)
0.149;-42097.5
38(2J)
0.181;-40530.0
38(2K)
0.229;-38962.5
3T(29)
0.241;-40530.0
(29)(3K)
0.240;-33048.8
2J(39)
0.191;-39746.2
39(2T)
0.234;-40530.0
39(2Q)
0.146;-38962.5
(2T)(3T)
0.208;-29486.2
3(2TK)
0.210;-37395.0
2(3TQ)
0.195;-38178.8
23(TJ)
0.189;-38962.5
23(TK)
0.175;-37395.0
(2J)(3K)
0.219;-31481.2
2K(3J)
0.187;-36611.2
23(JK)
0.239;-36611.2
(3Q)(2K)
0.213;-30697.5
(2K)(3K)
0.291;-24783.8
4(246)
0.165;-41670.0
48(24)
0.168;-40102.5
(24)(4J)
0.221;-32621.3
5(245)
0.186;-41670.0
9(245)
0.140;-43665.0
K(245)
0.161;-40530.0
5(248)
0.187;-44448.8
5T(24)
0.223;-42881.2
(24)(5K)
0.168;-35400.0
9(246)
0.187;-42881.2
K(246)
0.211;-39746.2
6(249)
0.195;-42881.2
6J(24)
0.188;-41313.8
(2478)
0.191;-42881.2
(247Q)
0.234;-39746.2
7(249)
0.193;-42097.5
7J(24)
0.184;-40530.0
(2489)
0.212;-41313.8
(248K)
0.239;-38178.8
8T(24)
0.194;-40530.0
(24)(8K)
0.208;-33048.8
Q(249)
0.157;-38178.8
(24)(9J)
0.249;-33832.5
T(24T)
0.220;-33832.5
T(24J)
0.173;-38178.8
TK(24)
0.211;-36611.2
(24)(JQ)
0.226;-31481.2
QQ(24)
0.259;-30697.5
24(45)
0.175;-42453.8
44(28)
0.204;-40102.5
244T
0.228;-43665.0
24(4K)
0.196;-36183.7
(25)(47)
0.188;-40102.5
4(25T)
0.169;-42881.2
4Q(25)
0.143;-41313.8
(45)(27)
0.182;-40102.5
29(45)
0.138;-43665.0
2(45Q)
0.205;-41313.8
24(56)
0.184;-46016.2
24(58)
0.137;-44448.8
24(5T)
0.184;-42881.2
24(5Q)
0.186;-41313.8
4(267)
0.136;-44448.8
49(26)
0.175;-42881.2
(26)(4Q)
0.204;-35400.0
27(46)
0.139;-44448.8
2(46T)
0.206;-42097.5
(46)(2K)
0.247;-34616.2
46(28)
0.137;-43665.0
46(2T)
0.202;-42097.5
46(2Q)
0.218;-40530.0
(27)(47)
0.249;-33405.0
4(27T)
0.185;-41313.8
4Q(27)
0.164;-39746.2
(47)(29)
0.240;-36967.5
2J(47)
0.187;-40530.0
47(28)
0.200;-42881.2
47(2T)
0.239;-41313.8
47(2Q)
0.154;-39746.2
(28)(48)
0.232;-31837.5
4(28J)
0.176;-39746.2
4K(28)
0.216;-38178.8
(48)(2J)
0.212;-34616.2
2K(48)
0.198;-38178.8
24(8T)
0.182;-40530.0
24(8Q)
0.211;-38962.5
4(29T)
0.219;-39746.2
4Q(29)
0.228;-38178.8
(49)(2J)
0.226;-33832.5
2K(49)
0.202;-37395.0
24(9J)
0.178;-38962.5
24(9K)
0.202;-37395.0
(2T)(4Q)
0.200;-32265.0
2J(4T)
0.228;-38178.8
4T(2J)
0.194;-38178.8
4T(2K)
0.168;-36611.2
4Q(2J)
0.178;-36611.2
(4J)(2K)
0.175;-30697.5
4J(2K)
0.215;-35827.5
4K(2Q)
0.267;-35043.7
24(QK)
0.220;-35043.7
(25)(56)
0.190;-34972.5
5(259)
0.181;-37751.2
5J(25)
0.241;-36183.7
(2567)
0.141;-43665.0
(256J)
0.194;-40530.0
(25)(67)
0.237;-38535.0
6(25T)
0.189;-41313.8
6Q(25)
0.203;-39746.2
9(257)
0.151;-41313.8
K(257)
0.189;-38178.8
7(25T)
0.183;-40530.0
7Q(25)
0.144;-38962.5
T(258)
0.193;-39746.2
8(259)
0.191;-40530.0
8J(25)
0.207;-38962.5
(259T)
0.204;-38962.5
99(25)
0.217;-34616.2
(25)(9Q)
0.193;-32265.0
(25TQ)
0.214;-36611.2
T(25Q)
0.215;-36611.2
Q(25J)
0.243;-35827.5
(25)(JK)
0.246;-29913.7
QK(25)
0.254;-34260.0
25(57)
0.259;-39318.7
55(2T)
0.171;-36967.5
255Q
0.153;-40530.0
57(26)
0.151;-43665.0
(26)(5T)
0.260;-36183.7
5(26K)
0.240;-38962.5
2(568)
0.204;-42881.2
(56)(2J)
0.251;-35400.0
2K(56)
0.211;-38962.5
25(68)
0.174;-42881.2
25(6T)
0.154;-41313.8
25(6Q)
0.169;-39746.2
5(278)
0.175;-42097.5
5T(27)
0.165;-40530.0
(27)(5K)
0.230;-33048.8
29(57)
0.166;-41313.8
2(57Q)
0.172;-38962.5
25(78)
0.148;-42097.5
25(7T)
0.208;-40530.0
25(7Q)
0.238;-38962.5
5(289)
0.230;-40530.0
5J(28)
0.176;-38962.5
(58)(29)
0.225;-35400.0
2J(58)
0.192;-38962.5
58(29)
0.199;-40530.0
58(2J)
0.215;-38962.5
58(2K)
0.173;-37395.0
5T(29)
0.140;-38962.5
(29)(5K)
0.207;-31481.2
2J(59)
0.189;-38178.8
59(2T)
0.180;-38962.5
59(2Q)
0.208;-37395.0
(2T)(5T)
0.258;-27918.7
5(2TK)
0.202;-35827.5
2(5TQ)
0.231;-36611.2
25(TJ)
0.205;-37395.0
25(TK)
0.232;-35827.5
(2J)(5K)
0.242;-29913.7
2K(5J)
0.211;-35043.7
25(JK)
0.272;-35043.7
(5Q)(2K)
0.202;-29130.0
(2K)(5K)
0.269;-23216.2
6(268)
0.224;-36967.5
6T(26)
0.177;-35400.0
(26)(6K)
0.211;-27918.7
T(267)
0.183;-39746.2
7(268)
0.165;-41313.8
7T(26)
0.167;-39746.2
(26)(7K)
0.239;-32265.0
J(268)
0.176;-38178.8
89(26)
0.199;-39746.2
(26)(8Q)
0.207;-32265.0
(269J)
0.223;-37395.0
(26)(9T)
0.217;-33048.8
9(26K)
0.156;-35827.5
(26TK)
0.215;-35043.7
TQ(26)
0.196;-35827.5
K(26J)
0.193;-34260.0
Q(26Q)
0.188;-29130.0
KK(26)
0.218;-27562.5
66(29)
0.251;-36183.7
266J
0.240;-39746.2
67(27)
0.201;-36967.5
(27)(6T)
0.207;-34616.2
6(27K)
0.184;-37395.0
2(679)
0.229;-40530.0
(67)(2Q)
0.180;-33048.8
27(68)
0.156;-41313.8
27(6T)
0.180;-39746.2
27(6Q)
0.219;-38178.8
68(28)
0.193;-35400.0
(28)(6J)
0.220;-33048.8
28(68)
0.192;-35400.0
2(68J)
0.172;-38178.8
2688
0.217;-40530.0
268T
0.180;-44092.5
268Q
0.193;-42525.0
(29)(6T)
0.257;-33048.8
6(29K)
0.237;-35827.5
2(69J)
0.186;-37395.0
2699
0.164;-38962.5
269J
0.182;-42525.0
269K
0.199;-40957.5
6Q(2T)
0.167;-35827.5
(6T)(2Q)
0.263;-30697.5
2T(6J)
0.187;-36611.2
2T(6K)
0.204;-35043.7
6(2JK)
0.204;-34260.0
2(6JK)
0.233;-34260.0
2J(6K)
0.186;-34260.0
2Q(6Q)
0.238;-29130.0
26QK
0.198;-38606.2
78(27)
0.268;-35400.0
(27)(7J)
0.228;-27918.7
8(278)
0.231;-34616.2
Q(278)
0.233;-36611.2
(27)(8T)
0.229;-33048.8
8(27K)
0.260;-35827.5
(279Q)
0.190;-35827.5
9(27J)
0.241;-36611.2
9K(27)
0.205;-35043.7
TT(27)
0.269;-31481.2
(27)(TK)
0.228;-29130.0
J(27Q)
0.195;-34260.0
K(27Q)
0.175;-32692.5
77(28)
0.238;-35400.0
277T
0.159;-38962.5
27(7K)
0.237;-31481.2
(28)(7T)
0.223;-33048.8
7(28K)
0.188;-35827.5
2(78T)
0.217;-38178.8
(78)(2K)
0.256;-30697.5
78(2T)
0.222;-38178.8
78(2Q)
0.249;-36611.2
(29)(79)
0.222;-27918.7
7(29Q)
0.262;-35827.5
2(79T)
0.202;-37395.0
(79)(2K)
0.299;-29913.7
79(2J)
0.185;-36611.2
79(2K)
0.212;-35043.7
7J(2T)
0.211;-35827.5
(7T)(2J)
0.218;-30697.5
2K(7T)
0.178;-34260.0
27(TQ)
0.269;-35043.7
7(2JQ)
0.260;-34260.0
2(7JQ)
0.240;-34260.0
27(JQ)
0.206;-34260.0
7(2QK)
0.262;-32692.5
7Q(2K)
0.170;-32692.5
88(28)
0.251;-28702.5
(28)(8J)
0.241;-26351.2
9(289)
0.245;-32265.0
K(289)
0.226;-34260.0
9(28Q)
0.193;-35043.7
J(28T)
0.213;-35043.7
TJ(28)
0.213;-35043.7
(28JQ)
0.208;-33476.2
J(28K)
0.197;-32692.5
(28)(QK)
0.259;-26778.8
88(2T)
0.186;-32265.0
288Q
0.248;-35827.5
8T(29)
0.210;-36611.2
(29)(8K)
0.301;-29130.0
2J(89)
0.210;-35827.5
89(2T)
0.191;-36611.2
89(2Q)
0.174;-35043.7
(2T)(8T)
0.236;-25567.5
8(2TK)
0.216;-33476.2
2(8TQ)
0.231;-34260.0
28(TJ)
0.205;-35043.7
28(TK)
0.208;-33476.2
(2J)(8K)
0.227;-27562.5
2K(8J)
0.269;-32692.5
28(JK)
0.253;-32692.5
(8Q)(2K)
0.275;-26778.8
(2K)(8K)
0.271;-20865.0
9(29J)
0.189;-29913.7
9K(29)
0.246;-28346.2
TT(29)
0.231;-29913.7
(29)(TK)
0.190;-27562.5
J(29Q)
0.197;-32692.5
K(29Q)
0.174;-31125.0
99(2T)
0.227;-30697.5
299Q
0.214;-34260.0
9J(2T)
0.209;-34260.0
(9T)(2J)
0.205;-29130.0
2K(9T)
0.239;-32692.5
29(TQ)
0.240;-33476.2
9(2JQ)
0.205;-32692.5
2(9JQ)
0.241;-32692.5
29(JQ)
0.212;-32692.5
9(2QK)
0.233;-31125.0
9Q(2K)
0.196;-31125.0
TT(2T)
0.282;-24000.0
(2T)(TK)
0.303;-21648.7
J(2TQ)
0.175;-31908.7
K(2TQ)
0.247;-30341.2
TT(2J)
0.245;-28346.2
2TTK
0.264;-31908.7
TK(2J)
0.252;-31125.0
2TJJ
0.265;-32692.5
2TJK
0.163;-36255.0
2(TQK)
0.240;-30341.2
TK(2K)
0.245;-24427.5
(2J)(JK)
0.278;-20081.3
QK(2J)
0.270;-29557.5
2J(JK)
0.237;-25211.2
(JQ)(2K)
0.260;-24427.5
(2K)(JK)
0.235;-18513.7
K(2QK)
0.261;-22860.0
2K(QK)
0.254;-22860.0
3335
0.189;-43237.5
3339
0.210;-40102.5
333K
0.183;-36967.5
36(34)
0.209;-41670.0
(34)(39)
0.194;-34188.8
3(34Q)
0.233;-36967.5
33(45)
0.170;-42453.8
34(38)
0.235;-40102.5
334T
0.192;-43665.0
33(4K)
0.155;-36183.7
(35)(37)
0.219;-34972.5
3(35T)
0.197;-37751.2
3Q(35)
0.171;-36183.7
35(37)
0.199;-40102.5
3359
0.177;-43665.0
33(5Q)
0.214;-36183.7
(36)(37)
0.166;-34188.8
3(36T)
0.178;-36967.5
3Q(36)
0.204;-35400.0
36(38)
0.241;-38535.0
336T
0.187;-42097.5
33(6K)
0.190;-34616.2
(37)(39)
0.210;-31837.5
3(37Q)
0.243;-34616.2
33(78)
0.162;-37751.2
37(3J)
0.200;-35400.0
337K
0.208;-38962.5
3T(38)
0.180;-35400.0
(38)(3K)
0.230;-27918.7
338T
0.184;-40530.0
33(8K)
0.217;-33048.8
(39)(3J)
0.229;-28702.5
3399
0.179;-35400.0
33(9Q)
0.239;-33048.8
(3T)(3J)
0.291;-27918.7
33TT
0.229;-33832.5
33(TK)
0.213;-31481.2
(3J)(3K)
0.310;-25567.5
33JK
0.221;-35827.5
33(QK)
0.244;-29913.7
45(34)
0.162;-41670.0
(34)(48)
0.236;-34188.8
4(34J)
0.191;-36967.5
4K(34)
0.205;-35400.0
(3459)
0.149;-42881.2
(345K)
0.196;-39746.2
57(34)
0.172;-44448.8
(34)(5T)
0.199;-36967.5
5(34K)
0.195;-39746.2
(3469)
0.221;-42097.5
(346K)
0.240;-38962.5
68(34)
0.149;-42881.2
(34)(6J)
0.208;-35400.0
7(347)
0.184;-37751.2
J(347)
0.223;-39746.2
78(34)
0.211;-42097.5
(34)(7J)
0.229;-34616.2
8(348)
0.195;-36183.7
Q(348)
0.154;-38178.8
(34)(8T)
0.196;-34616.2
8(34K)
0.173;-37395.0
(349Q)
0.209;-37395.0
9(34J)
0.219;-38178.8
9K(34)
0.174;-36611.2
TT(34)
0.226;-33048.8
(34)(TK)
0.251;-30697.5
J(34Q)
0.219;-35827.5
K(34Q)
0.233;-34260.0
44(35)
0.204;-41670.0
3447
0.152;-45232.5
34(4T)
0.214;-37751.2
44(3K)
0.193;-35400.0
4(357)
0.134;-44448.8
49(35)
0.183;-42881.2
(35)(4Q)
0.172;-35400.0
36(45)
0.134;-45232.5
3(459)
0.212;-42881.2
(45)(3Q)
0.183;-35400.0
35(46)
0.156;-45232.5
35(48)
0.187;-43665.0
35(4T)
0.188;-42097.5
35(4Q)
0.206;-40530.0
46(36)
0.176;-39318.7
(36)(49)
0.189;-36967.5
4(36Q)
0.193;-39746.2
3(467)
0.235;-43665.0
(46)(3T)
0.203;-36183.7
3Q(46)
0.239;-39746.2
3467
0.128;-48795.0
3469
0.161;-47227.5
346J
0.123;-45660.0
346K
0.209;-44092.5
49(37)
0.154;-41313.8
(37)(4Q)
0.221;-33832.5
38(47)
0.187;-42097.5
3(47J)
0.204;-39746.2
3477
0.168;-42881.2
3479
0.212;-46443.7
347J
0.153;-44876.2
347K
0.204;-43308.8
4T(38)
0.234;-39746.2
(38)(4K)
0.238;-32265.0
3T(48)
0.144;-39746.2
3(48K)
0.191;-37395.0
38(4T)
0.220;-39746.2
38(4Q)
0.220;-38178.8
49(39)
0.268;-34616.2
(39)(4Q)
0.255;-32265.0
3T(49)
0.183;-38962.5
3(49K)
0.182;-36611.2
39(4J)
0.185;-38178.8
39(4K)
0.201;-36611.2
4(3TQ)
0.223;-36611.2
3(4TJ)
0.192;-37395.0
34TT
0.228;-38178.8
34TQ
0.194;-41741.2
(3J)(4Q)
0.238;-30697.5
3Q(4J)
0.231;-35827.5
34JQ
0.186;-40957.5
(3Q)(4K)
0.246;-29130.0
3Q(4K)
0.216;-34260.0
5(356)
0.191;-39318.7
58(35)
0.176;-37751.2
(35)(5J)
0.203;-30270.0
6(356)
0.226;-38535.0
T(356)
0.173;-40530.0
6(357)
0.217;-42881.2
69(35)
0.236;-41313.8
(35)(6Q)
0.208;-33832.5
(3579)
0.213;-40530.0
(357K)
0.246;-37395.0
79(35)
0.194;-40530.0
(35)(7Q)
0.261;-33048.8
(358T)
0.217;-38962.5
88(35)
0.175;-35400.0
(35)(8J)
0.185;-33048.8
9(359)
0.235;-33832.5
K(359)
0.191;-35827.5
9(35Q)
0.195;-36611.2
J(35T)
0.167;-36611.2
TJ(35)
0.199;-36611.2
(35JQ)
0.190;-35043.7
J(35K)
0.224;-34260.0
(35)(QK)
0.227;-28346.2
55(37)
0.203;-38535.0
3559
0.195;-42097.5
35(5Q)
0.171;-34616.2
(36)(57)
0.252;-37751.2
5(36T)
0.186;-40530.0
5Q(36)
0.193;-38962.5
(56)(38)
0.167;-36967.5
3T(56)
0.196;-40530.0
3(56K)
0.209;-38178.8
36(58)
0.185;-42097.5
36(5T)
0.203;-40530.0
36(5Q)
0.163;-38962.5
57(37)
0.182;-36967.5
(37)(5T)
0.203;-34616.2
5(37K)
0.199;-37395.0
3(579)
0.226;-40530.0
(57)(3Q)
0.199;-33048.8
37(58)
0.185;-41313.8
37(5T)
0.202;-39746.2
37(5Q)
0.161;-38178.8
58(38)
0.203;-35400.0
(38)(5J)
0.222;-33048.8
38(58)
0.259;-35400.0
3(58J)
0.179;-38178.8
3588
0.231;-40530.0
358T
0.191;-44092.5
358Q
0.166;-42525.0
(39)(5T)
0.203;-33048.8
5(39K)
0.158;-35827.5
3(59J)
0.185;-37395.0
3599
0.148;-38962.5
359J
0.175;-42525.0
359K
0.199;-40957.5
5Q(3T)
0.253;-35827.5
(5T)(3Q)
0.255;-30697.5
3T(5J)
0.253;-36611.2
3T(5K)
0.215;-35043.7
5(3JK)
0.241;-34260.0
3(5JK)
0.219;-34260.0
3J(5K)
0.235;-34260.0
3Q(5Q)
0.230;-29130.0
35QK
0.239;-38606.2
67(36)
0.241;-36967.5
(36)(6T)
0.267;-29486.2
6(36K)
0.221;-32265.0
(367T)
0.226;-38962.5
77(36)
0.195;-36183.7
(36)(7T)
0.228;-33832.5
7(36K)
0.225;-36611.2
(368J)
0.212;-37395.0
(36)(89)
0.189;-33832.5
8(36Q)
0.180;-36611.2
T(369)
0.238;-37395.0
9(36T)
0.210;-37395.0
9Q(36)
0.178;-35827.5
Q(36T)
0.167;-35043.7
(36)(TQ)
0.235;-29913.7
(36JK)
0.244;-33476.2
JK(36)
0.170;-33476.2
K(36K)
0.282;-26778.8
3668
0.186;-41313.8
36(6J)
0.185;-33832.5
(37)(67)
0.225;-31053.8
6(37T)
0.174;-38962.5
6Q(37)
0.210;-37395.0
(67)(39)
0.221;-34616.2
3J(67)
0.203;-38178.8
67(38)
0.198;-40530.0
67(3T)
0.171;-38962.5
67(3Q)
0.201;-37395.0
(38)(68)
0.246;-29486.2
6(38J)
0.209;-37395.0
6K(38)
0.268;-35827.5
(68)(3J)
0.192;-32265.0
3K(68)
0.249;-35827.5
36(8T)
0.163;-38178.8
36(8Q)
0.183;-36611.2
6(39T)
0.206;-37395.0
6Q(39)
0.177;-35827.5
(69)(3J)
0.217;-31481.2
3K(69)
0.244;-35043.7
36(9J)
0.174;-36611.2
36(9K)
0.180;-35043.7
(3T)(6Q)
0.223;-29913.7
3J(6T)
0.185;-35827.5
6T(3J)
0.223;-35827.5
6T(3K)
0.197;-34260.0
6Q(3J)
0.259;-34260.0
(6J)(3K)
0.256;-28346.2
6J(3K)
0.228;-33476.2
6K(3Q)
0.241;-32692.5
36(QK)
0.219;-32692.5
(37)(78)
0.189;-29486.2
7(37J)
0.249;-32265.0
7K(37)
0.206;-30697.5
(378Q)
0.210;-35827.5
8(37T)
0.182;-37395.0
8Q(37)
0.238;-35827.5
J(379)
0.193;-35827.5
9T(37)
0.162;-36611.2
(37)(9K)
0.199;-29130.0
K(37T)
0.209;-33476.2
T(37K)
0.197;-33476.2
JJ(37)
0.232;-29130.0
(37QK)
0.262;-31908.7
3777
0.212;-35400.0
37(7T)
0.258;-33048.8
77(3K)
0.221;-30697.5
7(38T)
0.223;-37395.0
7Q(38)
0.213;-35827.5
(78)(3T)
0.205;-32265.0
3Q(78)
0.237;-35827.5
3789
0.162;-43308.8
378J
0.166;-41741.2
378K
0.206;-40173.8
7J(39)
0.194;-35827.5
(79)(3T)
0.239;-31481.2
3Q(79)
0.179;-35043.7
379T
0.194;-41741.2
379Q
0.245;-40173.8
(3T)(7J)
0.297;-29913.7
3T(7T)
0.273;-30697.5
3(7TK)
0.220;-33476.2
3T(7Q)
0.176;-34260.0
7J(3J)
0.267;-29130.0
(7J)(3Q)
0.235;-28346.2
3J(7Q)
0.224;-33476.2
7Q(3Q)
0.298;-27562.5
37QQ
0.256;-32692.5
37KK
0.220;-31125.0
8(38J)
0.222;-30697.5
8K(38)
0.277;-29130.0
(389K)
0.178;-33476.2
9J(38)
0.217;-35043.7
(38TJ)
0.194;-34260.0
(38)(TJ)
0.248;-29130.0
J(38J)
0.220;-28346.2
JQ(38)
0.221;-32692.5
Q(38K)
0.236;-31125.0
3889
0.212;-37395.0
38(8Q)
0.230;-29913.7
(39)(8T)
0.202;-30697.5
8(39K)
0.216;-33476.2
3(89J)
0.204;-35043.7
3899
0.197;-36611.2
389J
0.217;-40173.8
389K
0.227;-38606.2
8Q(3T)
0.222;-33476.2
(8T)(3Q)
0.255;-28346.2
3T(8J)
0.224;-34260.0
3T(8K)
0.215;-32692.5
8(3JK)
0.252;-31908.7
3(8JK)
0.231;-31908.7
3J(8K)
0.247;-31908.7
3Q(8Q)
0.274;-26778.8
38QK
0.224;-36255.0
9T(39)
0.234;-29913.7
(39)(9K)
0.256;-22432.5
K(39T)
0.195;-31908.7
T(39K)
0.260;-31908.7
JJ(39)
0.282;-27562.5
(39QK)
0.262;-30341.2
3999
0.239;-30697.5
39(9Q)
0.294;-28346.2
(3T)(9J)
0.210;-28346.2
3T(9T)
0.245;-29130.0
3(9TK)
0.210;-31908.7
3T(9Q)
0.208;-32692.5
9J(3J)
0.252;-27562.5
(9J)(3Q)
0.209;-26778.8
3J(9Q)
0.183;-31908.7
9Q(3Q)
0.247;-25995.0
39QQ
0.232;-31125.0
39KK
0.227;-29557.5
T(3TK)
0.220;-25995.0
JJ(3T)
0.278;-26778.8
(3TQK)
0.174;-29557.5
3TTT
0.236;-28346.2
3T(TK)
0.226;-25995.0
(3J)(TK)
0.207;-25211.2
3K(TJ)
0.291;-30341.2
3T(JK)
0.208;-30341.2
(TQ)(3K)
0.227;-24427.5
(3K)(TK)
0.340;-18513.7
J(3JK)
0.257;-24427.5
(3J)(QK)
0.235;-23643.7
JJ(3K)
0.250;-24427.5
3Q(JQ)
0.311;-24427.5
3JQK
0.203;-33903.7
QK(3Q)
0.232;-22860.0
QK(3K)
0.241;-22076.2
44(46)
0.233;-34972.5
44(4T)
0.214;-31837.5
(45)(45)
0.217;-29842.5
4(458)
0.158;-37751.2
4T(45)
0.177;-36183.7
(45)(4K)
0.230;-28702.5
4457
0.170;-43665.0
44(5T)
0.185;-36183.7
45(4K)
0.231;-33832.5
4(468)
0.199;-36967.5
4T(46)
0.208;-35400.0
(46)(4K)
0.237;-27918.7
4468
0.219;-42097.5
44(6J)
0.273;-34616.2
(47)(47)
0.260;-26707.5
4(47T)
0.197;-34616.2
4Q(47)
0.227;-33048.8
47(49)
0.240;-35400.0
447J
0.157;-38962.5
48(48)
0.278;-30270.0
(48)(4J)
0.241;-27918.7
4488
0.186;-35400.0
44(8J)
0.249;-33048.8
(49)(49)
0.233;-23572.5
4(49Q)
0.259;-31481.2
44(9T)
0.228;-33048.8
49(4K)
0.278;-30697.5
4(4TQ)
0.277;-30697.5
44(TJ)
0.199;-31481.2
(4J)(4J)
0.267;-20437.5
44JJ
0.209;-30697.5
4Q(4Q)
0.245;-24000.0
(4K)(4K)
0.279;-17302.5
(45)(57)
0.177;-32621.3
5(45T)
0.244;-35400.0
5Q(45)
0.279;-33832.5
8(456)
0.171;-41313.8
Q(456)
0.209;-38178.8
(45)(68)
0.234;-36183.7
6(45J)
0.213;-38962.5
6K(45)
0.201;-37395.0
(457J)
0.167;-38178.8
(45)(78)
0.235;-35400.0
7(45J)
0.203;-38178.8
7K(45)
0.233;-36611.2
(458Q)
0.229;-36611.2
8(45T)
0.198;-38178.8
8Q(45)
0.217;-36611.2
J(459)
0.178;-36611.2
9T(45)
0.155;-37395.0
(45)(9K)
0.206;-29913.7
K(45T)
0.209;-34260.0
T(45K)
0.219;-34260.0
JJ(45)
0.227;-29913.7
(45QK)
0.275;-32692.5
4555
0.200;-39318.8
45(58)
0.160;-36967.5
55(4J)
0.205;-34616.2
455K
0.226;-38178.8
58(46)
0.212;-41313.8
(46)(5J)
0.218;-33832.5
46(56)
0.171;-37751.2
4(569)
0.188;-40530.0
(56)(4Q)
0.214;-33048.8
46(57)
0.163;-42097.5
46(59)
0.180;-40530.0
46(5J)
0.192;-38962.5
46(5K)
0.170;-37395.0
5(479)
0.241;-39746.2
5J(47)
0.225;-38178.8
(57)(48)
0.172;-35400.0
4T(57)
0.234;-38962.5
4(57K)
0.160;-36611.2
47(59)
0.174;-39746.2
47(5J)
0.169;-38178.8
47(5K)
0.179;-36611.2
5(48T)
0.255;-38178.8
5Q(48)
0.202;-36611.2
(58)(4T)
0.173;-33048.8
4Q(58)
0.204;-36611.2
4589
0.158;-44092.5
458J
0.230;-42525.0
458K
0.211;-40957.5
5J(49)
0.220;-36611.2
(59)(4T)
0.170;-32265.0
4Q(59)
0.205;-35827.5
459T
0.186;-42525.0
459Q
0.241;-40957.5
(4T)(5J)
0.259;-30697.5
4T(5T)
0.223;-31481.2
4(5TK)
0.169;-34260.0
4T(5Q)
0.250;-35043.7
5J(4J)
0.226;-29913.7
(5J)(4Q)
0.285;-29130.0
4J(5Q)
0.205;-34260.0
5Q(4Q)
0.237;-28346.2
45QQ
0.183;-33476.2
45KK
0.242;-31908.7
6(469)
0.178;-34616.2
6J(46)
0.219;-33048.8
(4678)
0.193;-39746.2
(467Q)
0.242;-36611.2
7(469)
0.189;-38962.5
7J(46)
0.223;-37395.0
(4689)
0.196;-38178.8
(468K)
0.173;-35043.7
8T(46)
0.217;-37395.0
(46)(8K)
0.222;-29913.7
Q(469)
0.256;-35043.7
(46)(9J)
0.259;-30697.5
T(46T)
0.251;-30697.5
T(46J)
0.221;-35043.7
TK(46)
0.176;-33476.2
(46)(JQ)
0.251;-28346.2
QQ(46)
0.205;-27562.5
46(67)
0.213;-36183.7
66(4T)
0.243;-33832.5
466Q
0.210;-37395.0
68(47)
0.199;-39746.2
(47)(6J)
0.251;-32265.0
47(67)
0.203;-35400.0
4(67T)
0.161;-38178.8
(67)(4K)
0.193;-30697.5
67(49)
0.166;-38962.5
67(4J)
0.175;-37395.0
67(4K)
0.203;-35827.5
69(48)
0.174;-38178.8
(48)(6Q)
0.280;-30697.5
49(68)
0.194;-38178.8
4(68Q)
0.258;-35827.5
46(89)
0.210;-38178.8
46(8J)
0.194;-36611.2
46(8K)
0.184;-35043.7
(49)(6J)
0.179;-30697.5
49(69)
0.214;-32265.0
4(69Q)
0.249;-35043.7
46(9T)
0.184;-36611.2
46(9Q)
0.207;-35043.7
6(4TJ)
0.212;-35043.7
6K(4T)
0.179;-33476.2
(6T)(4K)
0.280;-28346.2
6T(4Q)
0.194;-34260.0
(4J)(6J)
0.289;-24000.0
4J(6J)
0.257;-29130.0
6J(4Q)
0.201;-33476.2
(4Q)(6Q)
0.242;-22432.5
4K(6Q)
0.236;-31908.7
4K(6K)
0.265;-25995.0
79(47)
0.279;-33048.8
(47)(7Q)
0.249;-25567.5
(478T)
0.252;-36611.2
88(47)
0.229;-33048.8
(47)(8J)
0.249;-30697.5
9(479)
0.230;-31481.2
K(479)
0.251;-33476.2
9(47Q)
0.179;-34260.0
J(47T)
0.223;-34260.0
TJ(47)
0.215;-34260.0
(47JQ)
0.207;-32692.5
J(47K)
0.262;-31908.7
(47)(QK)
0.228;-25995.0
77(49)
0.190;-33048.8
477J
0.187;-36611.2
78(48)
0.201;-33048.8
(48)(7J)
0.208;-30697.5
48(78)
0.240;-33048.8
4(78J)
0.191;-35827.5
4788
0.193;-38178.8
478T
0.159;-41741.2
478Q
0.178;-40173.8
(49)(7T)
0.269;-30697.5
7(49K)
0.262;-33476.2
4(79J)
0.235;-35043.7
4799
0.240;-36611.2
479J
0.199;-40173.8
479K
0.222;-38606.2
7Q(4T)
0.248;-33476.2
(7T)(4Q)
0.316;-28346.2
4T(7J)
0.199;-34260.0
4T(7K)
0.224;-32692.5
7(4JK)
0.208;-31908.7
4(7JK)
0.208;-31908.7
4J(7K)
0.244;-31908.7
4Q(7Q)
0.206;-26778.8
47QK
0.224;-36255.0
89(48)
0.184;-31481.2
(48)(8Q)
0.248;-24000.0
(489J)
0.213;-34260.0
(48)(9T)
0.293;-29913.7
9(48K)
0.221;-32692.5
(48TK)
0.220;-31908.7
TQ(48)
0.273;-32692.5
K(48J)
0.264;-31125.0
Q(48Q)
0.195;-25995.0
KK(48)
0.313;-24427.5
88(4J)
0.256;-29913.7
488K
0.171;-33476.2
8J(49)
0.199;-34260.0
(89)(4T)
0.272;-29913.7
4Q(89)
0.174;-33476.2
489T
0.166;-40173.8
489Q
0.232;-38606.2
(4T)(8J)
0.243;-28346.2
4T(8T)
0.195;-29130.0
4(8TK)
0.266;-31908.7
4T(8Q)
0.220;-32692.5
8J(4J)
0.309;-27562.5
(8J)(4Q)
0.233;-26778.8
4J(8Q)
0.231;-31908.7
8Q(4Q)
0.297;-25995.0
48QQ
0.245;-31125.0
48KK
0.211;-29557.5
9(49Q)
0.213;-27562.5
J(49T)
0.237;-32692.5
TJ(49)
0.222;-32692.5
(49JQ)
0.242;-31125.0
J(49K)
0.217;-30341.2
(49)(QK)
0.240;-24427.5
99(4J)
0.263;-28346.2
499K
0.211;-31908.7
9Q(4T)
0.188;-31908.7
(9T)(4Q)
0.245;-26778.8
4T(9J)
0.203;-32692.5
4T(9K)
0.198;-31125.0
9(4JK)
0.276;-30341.2
4(9JK)
0.250;-30341.2
4J(9K)
0.201;-30341.2
4Q(9Q)
0.234;-25211.2
49QK
0.203;-34687.5
TJ(4T)
0.272;-26778.8
(4TJQ)
0.216;-30341.2
J(4TK)
0.226;-29557.5
(4T)(QK)
0.331;-23643.7
TT(4Q)
0.228;-25995.0
T(4JQ)
0.238;-30341.2
4(TJQ)
0.258;-30341.2
4T(JQ)
0.225;-30341.2
T(4QK)
0.259;-28773.7
TQ(4K)
0.191;-28773.7
JJ(4J)
0.273;-20081.3
(4JQK)
0.198;-27990.0
4JJJ
0.281;-25211.2
JQ(4Q)
0.319;-23643.7
4JQQ
0.267;-28773.7
4JKK
0.315;-27206.2
QQ(4K)
0.307;-22076.2
4KKK
0.285;-20508.8
55(59)
0.227;-30270.0
55(5K)
0.297;-27135.0
(56)(58)
0.242;-30270.0
5(56J)
0.204;-33048.8
5K(56)
0.229;-31481.2
56(59)
0.214;-34616.2
556J
0.222;-38178.8
57(57)
0.266;-30270.0
(57)(5T)
0.252;-27918.7
5(57K)
0.181;-30697.5
55(79)
0.233;-33832.5
57(5Q)
0.259;-31481.2
5(589)
0.210;-33048.8
5J(58)
0.199;-31481.2
58(59)
0.248;-33048.8
558J
0.167;-36611.2
59(59)
0.293;-27135.0
(59)(5Q)
0.241;-24783.8
559T
0.170;-36611.2
55(9K)
0.238;-29130.0
(5T)(5Q)
0.267;-24000.0
55TJ
0.244;-35043.7
5J(5J)
0.218;-24000.0
5J(5Q)
0.235;-28346.2
5(5QK)
0.276;-26778.8
5K(5K)
0.320;-20865.0
68(56)
0.171;-34616.2
(56)(6J)
0.297;-27135.0
7(567)
0.216;-34616.2
J(567)
0.192;-36611.2
78(56)
0.219;-38962.5
(56)(7J)
0.188;-31481.2
8(568)
0.227;-33048.8
Q(568)
0.268;-35043.7
(56)(8T)
0.279;-31481.2
8(56K)
0.213;-34260.0
(569Q)
0.264;-34260.0
9(56J)
0.221;-35043.7
9K(56)
0.217;-33476.2
TT(56)
0.209;-29913.7
(56)(TK)
0.223;-27562.5
J(56Q)
0.225;-32692.5
K(56Q)
0.227;-31125.0
66(57)
0.193;-35400.0
5669
0.225;-38962.5
56(6Q)
0.215;-31481.2
(57)(68)
0.176;-33832.5
6(57J)
0.187;-36611.2
6K(57)
0.202;-35043.7
(67)(5T)
0.259;-32265.0
5Q(67)
0.222;-35827.5
5678
0.188;-44092.5
567T
0.193;-42525.0
567Q
0.202;-40957.5
(58)(69)
0.216;-32265.0
6(58Q)
0.219;-35043.7
5(689)
0.228;-37395.0
(68)(5Q)
0.254;-29913.7
58(69)
0.177;-37395.0
58(6J)
0.180;-35827.5
58(6K)
0.259;-34260.0
6(59J)
0.257;-35043.7
6K(59)
0.243;-33476.2
(69)(5Q)
0.225;-29130.0
59(6T)
0.205;-35827.5
59(6Q)
0.212;-34260.0
6T(5T)
0.184;-29913.7
(5T)(6K)
0.231;-27562.5
5Q(6T)
0.189;-33476.2
56TJ
0.182;-39390.0
56TK
0.153;-37822.5
6K(5J)
0.193;-31908.7
56JJ
0.227;-33476.2
56JK
0.217;-37038.8
5(6QK)
0.210;-31125.0
6K(5K)
0.214;-25211.2
(57)(79)
0.277;-27135.0
7(57Q)
0.210;-29913.7
9(578)
0.218;-36611.2
K(578)
0.225;-33476.2
8(57J)
0.187;-35043.7
8K(57)
0.169;-33476.2
(579K)
0.164;-32692.5
9J(57)
0.182;-34260.0
(57TJ)
0.233;-33476.2
(57)(TJ)
0.235;-28346.2
J(57J)
0.261;-27562.5
JQ(57)
0.185;-31908.7
Q(57K)
0.211;-30341.2
5778
0.236;-38178.8
57(7J)
0.265;-30697.5
(58)(78)
0.276;-27135.0
7(58J)
0.279;-35043.7
7K(58)
0.209;-33476.2
(78)(5J)
0.250;-29913.7
5K(78)
0.192;-33476.2
57(8T)
0.217;-35827.5
57(8Q)
0.211;-34260.0
7(59T)
0.205;-35043.7
7Q(59)
0.224;-33476.2
(79)(5J)
0.214;-29130.0
5K(79)
0.215;-32692.5
57(9J)
0.241;-34260.0
57(9K)
0.260;-32692.5
(5T)(7Q)
0.217;-27562.5
5J(7T)
0.202;-33476.2
7T(5J)
0.246;-33476.2
7T(5K)
0.182;-31908.7
7Q(5J)
0.232;-31908.7
(7J)(5K)
0.240;-25995.0
7J(5K)
0.193;-31125.0
7K(5Q)
0.229;-30341.2
57(QK)
0.234;-30341.2
(58)(89)
0.230;-25567.5
8(58Q)
0.244;-28346.2
T(589)
0.191;-34260.0
9(58T)
0.241;-34260.0
9Q(58)
0.236;-32692.5
Q(58T)
0.228;-31908.7
(58)(TQ)
0.194;-26778.8
(58JK)
0.251;-30341.2
JK(58)
0.251;-30341.2
K(58K)
0.274;-23643.7
588T
0.217;-35043.7
58(8K)
0.240;-27562.5
(59)(8J)
0.294;-28346.2
59(89)
0.257;-29913.7
5(89Q)
0.245;-32692.5
58(9T)
0.214;-34260.0
58(9Q)
0.216;-32692.5
8(5TJ)
0.180;-32692.5
8K(5T)
0.240;-31125.0
(8T)(5K)
0.286;-25995.0
8T(5Q)
0.231;-31908.7
(5J)(8J)
0.331;-21648.7
5J(8J)
0.248;-26778.8
8J(5Q)
0.290;-31125.0
(5Q)(8Q)
0.264;-20081.3
5K(8Q)
0.238;-29557.5
5K(8K)
0.268;-23643.7
9J(59)
0.248;-27562.5
(59TJ)
0.211;-31908.7
(59)(TJ)
0.227;-26778.8
J(59J)
0.201;-25995.0
JQ(59)
0.227;-30341.2
Q(59K)
0.219;-28773.7
599T
0.199;-33476.2
59(9K)
0.303;-25995.0
(5T)(9Q)
0.253;-25995.0
5J(9T)
0.250;-31908.7
9T(5J)
0.193;-31908.7
9T(5K)
0.242;-30341.2
9Q(5J)
0.298;-30341.2
(9J)(5K)
0.229;-24427.5
9J(5K)
0.252;-29557.5
9K(5Q)
0.223;-28773.7
59(QK)
0.220;-28773.7
(5T)(TJ)
0.276;-20865.0
J(5TJ)
0.226;-25211.2
JQ(5T)
0.278;-29557.5
Q(5TK)
0.239;-27990.0
5TTJ
0.234;-31125.0
TJ(5J)
0.292;-25211.2
(TJ)(5Q)
0.257;-24427.5
5J(TQ)
0.272;-29557.5
TQ(5Q)
0.275;-23643.7
5TQQ
0.252;-28773.7
5TKK
0.228;-27206.2
Q(5JQ)
0.255;-22860.0
KK(5J)
0.279;-21292.5
(5Q)(JQ)
0.311;-17730.0
5K(JQ)
0.236;-27206.2
5K(JK)
0.226;-21292.5
5QQQ
0.235;-22076.2
KK(5K)
0.253;-14595.0
6669
0.182;-33048.8
666K
0.239;-29913.7
69(67)
0.246;-32265.0
(67)(6Q)
0.253;-24783.8
6678
0.166;-38178.8
66(7J)
0.227;-30697.5
(68)(68)
0.234;-22005.0
6(68J)
0.244;-29913.7
6K(68)
0.235;-28346.2
68(6J)
0.189;-29913.7
668K
0.215;-33476.2
6J(69)
0.230;-29130.0
69(6T)
0.181;-29913.7
669Q
0.231;-33476.2
6J(6T)
0.263;-28346.2
6T(6J)
0.211;-28346.2
66TK
0.222;-31908.7
6K(6J)
0.217;-25995.0
(6Q)(6Q)
0.289;-15735.0
66QK
0.295;-30341.2
7(679)
0.177;-31481.2
7J(67)
0.233;-29913.7
(6789)
0.229;-35827.5
(678K)
0.186;-32692.5
8T(67)
0.191;-35043.7
(67)(8K)
0.219;-27562.5
Q(679)
0.228;-32692.5
(67)(9J)
0.315;-28346.2
T(67T)
0.232;-28346.2
T(67J)
0.195;-32692.5
TK(67)
0.261;-31125.0
(67)(JQ)
0.263;-25995.0
QQ(67)
0.273;-25211.2
67(78)
0.173;-32265.0
77(6J)
0.278;-29913.7
677K
0.249;-33476.2
7T(68)
0.199;-35043.7
(68)(7K)
0.239;-27562.5
6T(78)
0.185;-35043.7
6(78K)
0.231;-32692.5
68(7T)
0.248;-35043.7
68(7Q)
0.213;-33476.2
79(69)
0.244;-29913.7
(69)(7Q)
0.256;-27562.5
6T(79)
0.229;-34260.0
6(79K)
0.209;-31908.7
69(7J)
0.189;-33476.2
69(7K)
0.263;-31908.7
7(6TQ)
0.261;-31908.7
6(7TJ)
0.238;-32692.5
67TT
0.193;-33476.2
67TQ
0.206;-37038.8
(6J)(7Q)
0.258;-25995.0
6Q(7J)
0.183;-31125.0
67JQ
0.185;-36255.0
(6Q)(7K)
0.288;-24427.5
6Q(7K)
0.299;-29557.5
8(689)
0.224;-29913.7
8J(68)
0.210;-28346.2
(689T)
0.203;-33476.2
99(68)
0.189;-29130.0
(68)(9Q)
0.271;-26778.8
(68TQ)
0.185;-31125.0
T(68Q)
0.249;-31125.0
Q(68J)
0.266;-30341.2
(68)(JK)
0.212;-24427.5
QK(68)
0.237;-28773.7
68(8T)
0.253;-29130.0
88(6K)
0.257;-26778.8
8(69J)
0.184;-32692.5
8K(69)
0.214;-31125.0
(89)(6Q)
0.258;-26778.8
69(8T)
0.192;-33476.2
69(8Q)
0.247;-31908.7
8T(6T)
0.266;-27562.5
(6T)(8K)
0.293;-25211.2
6Q(8T)
0.263;-31125.0
68TJ
0.203;-37038.8
68TK
0.218;-35471.2
8K(6J)
0.243;-29557.5
68JJ
0.231;-31125.0
68JK
0.217;-34687.5
6(8QK)
0.245;-28773.7
8K(6K)
0.260;-22860.0
(69)(9J)
0.305;-21648.7
T(69T)
0.228;-26778.8
T(69J)
0.205;-31125.0
TK(69)
0.214;-29557.5
(69)(JQ)
0.272;-24427.5
QQ(69)
0.246;-23643.7
69(9T)
0.244;-27562.5
99(6K)
0.266;-25211.2
9(6TQ)
0.219;-30341.2
6(9TJ)
0.230;-31125.0
69TT
0.232;-31908.7
69TQ
0.167;-35471.2
(6J)(9Q)
0.288;-24427.5
6Q(9J)
0.197;-29557.5
69JQ
0.210;-34687.5
(6Q)(9K)
0.257;-22860.0
6Q(9K)
0.232;-27990.0
T(6TJ)
0.250;-25211.2
TK(6T)
0.296;-23643.7
(6T)(JQ)
0.207;-23643.7
QQ(6T)
0.301;-22860.0
6T(TJ)
0.243;-25211.2
(6J)(TJ)
0.260;-19297.5
6J(TJ)
0.288;-24427.5
TJ(6Q)
0.277;-28773.7
(6Q)(TQ)
0.325;-17730.0
6K(TQ)
0.270;-27206.2
6K(TK)
0.229;-21292.5
JK(6J)
0.294;-22076.2
K(6JK)
0.268;-20508.8
6JJK
0.260;-27206.2
6(JQK)
0.264;-26422.5
JK(6K)
0.311;-20508.8
KK(6Q)
0.274;-19725.0
6QKK
0.211;-24855.0
77(7T)
0.304;-24783.7
(78)(78)
0.301;-20437.5
7(78J)
0.265;-28346.2
7K(78)
0.201;-26778.8
78(7J)
0.262;-28346.2
778K
0.258;-31908.7
7J(79)
0.217;-27562.5
79(7T)
0.211;-28346.2
779Q
0.266;-31908.7
7J(7T)
0.272;-26778.8
7T(7J)
0.262;-26778.8
77TK
0.185;-30341.2
7K(7J)
0.234;-24427.5
(7Q)(7Q)
0.293;-14167.5
77QK
0.191;-28773.7
8(78T)
0.207;-28346.2
8Q(78)
0.220;-26778.8
J(789)
0.166;-31908.7
9T(78)
0.240;-32692.5
(78)(9K)
0.256;-25211.2
K(78T)
0.244;-29557.5
T(78K)
0.259;-29557.5
JJ(78)
0.254;-25211.2
(78QK)
0.289;-27990.0
7888
0.223;-29913.7
78(8J)
0.197;-27562.5
(79)(89)
0.253;-23216.2
8(79Q)
0.272;-31125.0
7(89T)
0.268;-32692.5
(89)(7K)
0.224;-25211.2
89(7J)
0.210;-31908.7
89(7K)
0.197;-30341.2
8J(7T)
0.192;-31125.0
(8T)(7J)
0.292;-25995.0
7K(8T)
0.228;-29557.5
78(TQ)
0.203;-30341.2
8(7JQ)
0.244;-29557.5
7(8JQ)
0.237;-29557.5
78(JQ)
0.197;-29557.5
8(7QK)
0.296;-27990.0
8Q(7K)
0.285;-27990.0
99(79)
0.271;-22432.5
(79)(9Q)
0.288;-20081.3
(79TQ)
0.193;-29557.5
T(79Q)
0.213;-29557.5
Q(79J)
0.243;-28773.7
(79)(JK)
0.261;-22860.0
QK(79)
0.290;-27206.2
79(9J)
0.232;-25995.0
(7T)(9T)
0.281;-20865.0
9(7TK)
0.211;-28773.7
7(9TQ)
0.272;-29557.5
79(TJ)
0.219;-30341.2
79(TK)
0.276;-28773.7
(7J)(9K)
0.324;-22860.0
7K(9J)
0.249;-27990.0
79(JK)
0.254;-27990.0
(9Q)(7K)
0.316;-22076.2
(7K)(9K)
0.283;-16162.5
T(7TQ)
0.218;-23643.7
Q(7TJ)
0.233;-27990.0
(7T)(JK)
0.225;-22076.2
QK(7T)
0.235;-26422.5
7T(TQ)
0.271;-23643.7
(7J)(TQ)
0.227;-22860.0
7Q(TJ)
0.244;-27990.0
7TJQ
0.253;-33120.0
(7Q)(TK)
0.249;-21292.5
7Q(TK)
0.284;-26422.5
J(7JQ)
0.341;-22076.2
K(7JQ)
0.238;-25638.7
JJ(7Q)
0.233;-22076.2
J(7QK)
0.239;-25638.7
JQ(7K)
0.315;-25638.7
QQ(7Q)
0.363;-15378.8
7Q(QK)
0.302;-19725.0
8888
0.245;-24000.0
888Q
0.286;-25995.0
8(89J)
0.297;-25995.0
8K(89)
0.252;-24427.5
89(8Q)
0.210;-25211.2
8(8TJ)
0.285;-25211.2
8K(8T)
0.263;-23643.7
8T(8K)
0.247;-23643.7
8(8JK)
0.261;-22860.0
88(JK)
0.297;-22860.0
8Q(8K)
0.262;-22076.2
(89)(9T)
0.318;-20865.0
9(89K)
0.289;-23643.7
(89TK)
0.257;-27990.0
TQ(89)
0.197;-28773.7
K(89J)
0.278;-27206.2
Q(89Q)
0.329;-22076.2
KK(89)
0.340;-20508.8
99(8Q)
0.217;-24427.5
9(8TJ)
0.203;-29557.5
9K(8T)
0.258;-27990.0
(9T)(8K)
0.254;-22860.0
9T(8Q)
0.195;-28773.7
(8J)(9J)
0.311;-18513.7
8J(9J)
0.299;-23643.7
9J(8Q)
0.232;-27990.0
(8Q)(9Q)
0.259;-16946.2
8K(9Q)
0.256;-26422.5
8K(9K)
0.299;-20508.8
TQ(8T)
0.237;-22860.0
K(8TJ)
0.256;-26422.5
Q(8TQ)
0.229;-21292.5
KK(8T)
0.263;-19725.0
