AAAA
0.376;-680.0
5AAA
0.265;-1535.0
9AAA
0.290;-1315.0
KAAA
0.306;-1095.0
4A(2A)
0.210;-2250.0
(2A)(7A)
0.298;-1725.0
A(2TA)
0.258;-1920.0
QA(2A)
0.250;-1810.0
2A(4A)
0.225;-2250.0
26AA
0.239;-2500.0
AA(29)
0.263;-1975.0
2A(QA)
0.275;-1810.0
A(34A)
0.245;-2195.0
6A(3A)
0.210;-2085.0
(3A)(9A)
0.217;-1560.0
A(3QA)
0.253;-1755.0
AA(34)
0.247;-2195.0
3A(7A)
0.288;-2030.0
39AA
0.189;-2280.0
AA(3Q)
0.272;-1755.0
(4A)(5A)
0.287;-1725.0
A(48A)
0.277;-1920.0
TA(4A)
0.235;-1810.0
(4A)(KA)
0.283;-1285.0
46AA
0.222;-2390.0
AA(49)
0.272;-1865.0
4A(QA)
0.274;-1700.0
A(56A)
0.247;-1975.0
8A(5A)
0.300;-1865.0
(5A)(JA)
0.286;-1340.0
55AA
0.252;-2030.0
AA(58)
0.260;-1865.0
5A(JA)
0.271;-1700.0
5KAA
0.234;-1950.0
8A(6A)
0.265;-1810.0
(6A)(JA)
0.275;-1285.0
66AA
0.250;-1920.0
AA(69)
0.293;-1755.0
6A(QA)
0.276;-1590.0
A(78A)
0.255;-1755.0
TA(7A)
0.280;-1645.0
(7A)(KA)
0.331;-1120.0
79AA
0.199;-2060.0
AA(7Q)
0.249;-1535.0
(8A)(9A)
0.308;-1285.0
A(8QA)
0.270;-1480.0
AA(89)
0.291;-1645.0
8A(QA)
0.275;-1480.0
A(9TA)
0.305;-1535.0
QA(9A)
0.274;-1425.0
9A(JA)
0.265;-1480.0
9KAA
0.223;-1730.0
QA(TA)
0.307;-1370.0
TA(QA)
0.311;-1370.0
A(JQA)
0.316;-1315.0
AA(JQ)
0.332;-1315.0
(QA)(KA)
0.375;-845.0
KKAA
0.307;-1150.0
2(25A)
0.213;-2855.0
27(2A)
0.157;-2745.0
(2T)(2A)
0.210;-2220.0
2(2KA)
0.199;-2415.0
(236A)
0.165;-3105.0
(23TA)
0.184;-2885.0
33(2A)
0.199;-2910.0
(36)(2A)
0.232;-2745.0
3(29A)
0.188;-2940.0
3J(2A)
0.217;-2830.0
(245A)
0.198;-3105.0
(249A)
0.217;-2885.0
(24KA)
0.193;-2665.0
46(2A)
0.178;-3050.0
(49)(2A)
0.196;-2525.0
4(2QA)
0.163;-2720.0
6(25A)
0.176;-2995.0
T(25A)
0.204;-2775.0
5(26A)
0.157;-2995.0
58(2A)
0.143;-2885.0
(5J)(2A)
0.229;-2360.0
6(26A)
0.164;-2580.0
T(26A)
0.149;-2720.0
6(27A)
0.225;-2885.0
69(2A)
0.164;-2775.0
(6Q)(2A)
0.210;-2250.0
(279A)
0.169;-2720.0
(27KA)
0.230;-2500.0
79(2A)
0.190;-2720.0
(7Q)(2A)
0.231;-2195.0
(28TA)
0.202;-2610.0
88(2A)
0.179;-2360.0
(8J)(2A)
0.214;-2195.0
9(29A)
0.234;-2250.0
K(29A)
0.211;-2390.0
9(2QA)
0.267;-2445.0
J(2TA)
0.238;-2445.0
TJ(2A)
0.188;-2445.0
(2JQA)
0.225;-2335.0
J(2KA)
0.182;-2280.0
(QK)(2A)
0.236;-1865.0
22(4A)
0.172;-2910.0
226A
0.163;-3160.0
2A(29)
0.221;-2635.0
22(QA)
0.253;-2470.0
2(34A)
0.152;-3215.0
26(3A)
0.192;-3105.0
(29)(3A)
0.170;-2580.0
2(3QA)
0.189;-2775.0
A(234)
0.183;-3215.0
(23)(7A)
0.255;-2690.0
9A(23)
0.230;-2940.0
A(23Q)
0.177;-2775.0
2A(34)
0.185;-3215.0
2A(36)
0.147;-3105.0
2A(38)
0.203;-2995.0
2A(3T)
0.163;-2885.0
2A(3Q)
0.173;-2775.0
2(45A)
0.149;-3105.0
27(4A)
0.169;-2995.0
(2T)(4A)
0.235;-2470.0
2(4KA)
0.193;-2665.0
A(246)
0.213;-3050.0
(24)(9A)
0.222;-2525.0
JA(24)
0.183;-2775.0
24(5A)
0.165;-3105.0
24(7A)
0.183;-2995.0
24(9A)
0.188;-2885.0
24(JA)
0.209;-2775.0
24(KA)
0.243;-2665.0
26(5A)
0.151;-2995.0
(29)(5A)
0.230;-2470.0
2(5QA)
0.188;-2665.0
A(256)
0.162;-2995.0
(25)(9A)
0.190;-2470.0
JA(25)
0.217;-2720.0
25(6A)
0.167;-2995.0
25(8A)
0.170;-2885.0
25(TA)
0.199;-2775.0
25(QA)
0.174;-2665.0
(26)(6A)
0.225;-2220.0
2(69A)
0.167;-2775.0
2J(6A)
0.236;-2665.0
(26)(7A)
0.218;-2525.0
9A(26)
0.175;-2775.0
A(26Q)
0.208;-2610.0
2A(67)
0.215;-2885.0
2A(69)
0.193;-2775.0
2A(6J)
0.209;-2665.0
2A(6K)
0.201;-2555.0
(29)(7A)
0.231;-2360.0
2(7QA)
0.185;-2555.0
A(278)
0.215;-2775.0
(27)(JA)
0.263;-2250.0
KA(27)
0.231;-2500.0
2A(79)
0.233;-2720.0
2A(7J)
0.210;-2610.0
2A(7K)
0.260;-2500.0
(2T)(8A)
0.240;-2250.0
2(8KA)
0.210;-2445.0
A(28T)
0.207;-2610.0
(28)(KA)
0.232;-2085.0
28(TA)
0.169;-2610.0
28(QA)
0.209;-2500.0
(29)(9A)
0.208;-1890.0
2(9QA)
0.219;-2445.0
A(29T)
0.159;-2555.0
(29)(KA)
0.214;-2030.0
29(JA)
0.208;-2500.0
29(KA)
0.186;-2390.0
2J(TA)
0.165;-2445.0
(2T)(JA)
0.199;-2085.0
KA(2T)
0.183;-2335.0
2A(TQ)
0.198;-2390.0
2(JQA)
0.233;-2335.0
A(2JQ)
0.219;-2335.0
2A(JQ)
0.221;-2335.0
2(QKA)
0.216;-2225.0
2Q(KA)
0.200;-2225.0
33(3A)
0.200;-2495.0
(36)(3A)
0.210;-2330.0
3(39A)
0.190;-2525.0
3J(3A)
0.217;-2415.0
(345A)
0.193;-3050.0
(349A)
0.200;-2830.0
(34KA)
0.219;-2610.0
46(3A)
0.217;-2995.0
(49)(3A)
0.211;-2470.0
4(3QA)
0.207;-2665.0
6(35A)
0.183;-2940.0
T(35A)
0.218;-2720.0
5(36A)
0.191;-2940.0
58(3A)
0.191;-2830.0
(5J)(3A)
0.184;-2305.0
6(36A)
0.267;-2525.0
T(36A)
0.193;-2665.0
6(37A)
0.200;-2830.0
69(3A)
0.188;-2720.0
(6Q)(3A)
0.241;-2195.0
(379A)
0.199;-2665.0
(37KA)
0.217;-2445.0
79(3A)
0.189;-2665.0
(7Q)(3A)
0.184;-2140.0
(38TA)
0.191;-2555.0
88(3A)
0.246;-2305.0
(8J)(3A)
0.213;-2140.0
9(39A)
0.198;-2195.0
K(39A)
0.194;-2335.0
9(3QA)
0.270;-2390.0
J(3TA)
0.246;-2390.0
TJ(3A)
0.209;-2390.0
(3JQA)
0.226;-2280.0
J(3KA)
0.251;-2225.0
(QK)(3A)
0.216;-1810.0
33(5A)
0.204;-2745.0
337A
0.184;-2995.0
3A(3T)
0.215;-2470.0
33(KA)
0.261;-2305.0
3(46A)
0.237;-2995.0
38(4A)
0.176;-2885.0
(3J)(4A)
0.256;-2360.0
4A(34)
0.241;-2745.0
A(347)
0.162;-2940.0
(34)(TA)
0.211;-2415.0
QA(34)
0.267;-2665.0
345A
0.151;-3410.0
347A
0.158;-3300.0
349A
0.191;-3190.0
34JA
0.194;-3080.0
34KA
0.213;-2970.0
37(5A)
0.214;-2885.0
(3T)(5A)
0.201;-2360.0
3(5KA)
0.185;-2555.0
A(357)
0.141;-2885.0
(35)(TA)
0.271;-2360.0
QA(35)
0.246;-2610.0
356A
0.149;-3300.0
358A
0.188;-3190.0
35TA
0.184;-3080.0
35QA
0.199;-2970.0
(37)(6A)
0.254;-2470.0
3(6TA)
0.194;-2665.0
3Q(6A)
0.209;-2555.0
(36)(8A)
0.263;-2415.0
TA(36)
0.233;-2665.0
A(36K)
0.215;-2500.0
6A(38)
0.179;-2775.0
6A(3T)
0.249;-2665.0
6A(3Q)
0.255;-2555.0
37(7A)
0.223;-2415.0
(3T)(7A)
0.259;-2250.0
3(7KA)
0.195;-2445.0
A(379)
0.207;-2665.0
(37)(QA)
0.246;-2140.0
7A(38)
0.200;-2720.0
7A(3T)
0.175;-2610.0
7A(3Q)
0.184;-2500.0
38(8A)
0.218;-2305.0
(3J)(8A)
0.259;-2140.0
8A(38)
0.216;-2305.0
A(38J)
0.244;-2500.0
388A
0.197;-2665.0
38TA
0.158;-2915.0
38QA
0.151;-2805.0
(3T)(9A)
0.204;-2140.0
3(9KA)
0.218;-2335.0
A(39J)
0.239;-2445.0
399A
0.190;-2555.0
39JA
0.179;-2805.0
39KA
0.194;-2695.0
3Q(TA)
0.188;-2335.0
(3T)(QA)
0.239;-1975.0
TA(3J)
0.179;-2390.0
TA(3K)
0.243;-2280.0
3(JKA)
0.266;-2225.0
A(3JK)
0.218;-2225.0
JA(3K)
0.280;-2225.0
QA(3Q)
0.211;-1865.0
3QKA
0.250;-2530.0
45(4A)
0.196;-2635.0
(48)(4A)
0.210;-2110.0
4(4JA)
0.229;-2305.0
4K(4A)
0.246;-2195.0
(459A)
0.205;-2720.0
(45KA)
0.231;-2500.0
57(4A)
0.186;-2830.0
(5T)(4A)
0.274;-2305.0
5(4KA)
0.211;-2500.0
(469A)
0.216;-2665.0
(46KA)
0.203;-2445.0
68(4A)
0.201;-2720.0
(6J)(4A)
0.215;-2195.0
7(47A)
0.195;-2360.0
J(47A)
0.265;-2500.0
78(4A)
0.239;-2665.0
(7J)(4A)
0.185;-2140.0
8(48A)
0.231;-2250.0
Q(48A)
0.224;-2390.0
(8T)(4A)
0.220;-2140.0
8(4KA)
0.230;-2335.0
(49QA)
0.191;-2335.0
9(4JA)
0.214;-2390.0
9K(4A)
0.251;-2280.0
TT(4A)
0.290;-2030.0
(TK)(4A)
0.274;-1865.0
J(4QA)
0.247;-2225.0
K(4QA)
0.212;-2115.0
44(5A)
0.187;-2635.0
447A
0.163;-2885.0
4A(4T)
0.226;-2360.0
44(KA)
0.227;-2195.0
4(57A)
0.234;-2830.0
49(5A)
0.219;-2720.0
(4Q)(5A)
0.261;-2195.0
6A(45)
0.190;-2885.0
A(459)
0.228;-2720.0
(45)(QA)
0.225;-2195.0
5A(46)
0.208;-2885.0
5A(48)
0.213;-2775.0
5A(4T)
0.190;-2665.0
5A(4Q)
0.197;-2555.0
46(6A)
0.189;-2470.0
(49)(6A)
0.243;-2305.0
4(6QA)
0.181;-2500.0
A(467)
0.216;-2775.0
(46)(TA)
0.247;-2250.0
QA(46)
0.210;-2500.0
467A
0.180;-3135.0
469A
0.150;-3025.0
46JA
0.196;-2915.0
46KA
0.214;-2805.0
49(7A)
0.206;-2610.0
(4Q)(7A)
0.246;-2085.0
8A(47)
0.168;-2665.0
A(47J)
0.281;-2500.0
477A
0.172;-2720.0
479A
0.196;-2970.0
47JA
0.190;-2860.0
47KA
0.182;-2750.0
4T(8A)
0.203;-2500.0
(4K)(8A)
0.229;-1975.0
TA(48)
0.234;-2500.0
A(48K)
0.254;-2335.0
8A(4T)
0.211;-2500.0
8A(4Q)
0.223;-2390.0
49(9A)
0.248;-2140.0
(4Q)(9A)
0.288;-1975.0
TA(49)
0.208;-2445.0
A(49K)
0.206;-2280.0
9A(4J)
0.243;-2390.0
9A(4K)
0.223;-2280.0
4(TQA)
0.183;-2280.0
A(4TJ)
0.189;-2335.0
4TTA
0.176;-2390.0
4TQA
0.158;-2640.0
(4Q)(JA)
0.281;-1865.0
QA(4J)
0.282;-2225.0
4JQA
0.186;-2585.0
(4K)(QA)
0.231;-1755.0
QA(4K)
0.288;-2115.0
5(56A)
0.210;-2470.0
58(5A)
0.229;-2360.0
(5J)(5A)
0.204;-1835.0
6(56A)
0.242;-2415.0
T(56A)
0.176;-2555.0
6(57A)
0.202;-2720.0
69(5A)
0.206;-2610.0
(6Q)(5A)
0.185;-2085.0
(579A)
0.238;-2555.0
(57KA)
0.196;-2335.0
79(5A)
0.182;-2555.0
(7Q)(5A)
0.244;-2030.0
(58TA)
0.216;-2445.0
88(5A)
0.214;-2195.0
(8J)(5A)
0.198;-2030.0
9(59A)
0.288;-2085.0
K(59A)
0.196;-2225.0
9(5QA)
0.215;-2280.0
J(5TA)
0.218;-2280.0
TJ(5A)
0.206;-2280.0
(5JQA)
0.208;-2170.0
J(5KA)
0.257;-2115.0
(QK)(5A)
0.258;-1700.0
55(7A)
0.176;-2415.0
559A
0.204;-2665.0
5A(5Q)
0.236;-2140.0
(57)(6A)
0.214;-2360.0
5(6TA)
0.210;-2555.0
5Q(6A)
0.206;-2445.0
(56)(8A)
0.234;-2305.0
TA(56)
0.228;-2555.0
A(56K)
0.221;-2390.0
6A(58)
0.224;-2665.0
6A(5T)
0.188;-2555.0
6A(5Q)
0.175;-2445.0
57(7A)
0.177;-2305.0
(5T)(7A)
0.229;-2140.0
5(7KA)
0.216;-2335.0
A(579)
0.193;-2555.0
(57)(QA)
0.209;-2030.0
7A(58)
0.225;-2610.0
7A(5T)
0.215;-2500.0
7A(5Q)
0.230;-2390.0
58(8A)
0.250;-2195.0
(5J)(8A)
0.220;-2030.0
8A(58)
0.272;-2195.0
A(58J)
0.208;-2390.0
588A
0.189;-2555.0
58TA
0.235;-2805.0
58QA
0.171;-2695.0
(5T)(9A)
0.273;-2030.0
5(9KA)
0.239;-2225.0
A(59J)
0.271;-2335.0
599A
0.272;-2445.0
59JA
0.187;-2695.0
59KA
0.227;-2585.0
5Q(TA)
0.206;-2225.0
(5T)(QA)
0.197;-1865.0
TA(5J)
0.253;-2280.0
TA(5K)
0.238;-2170.0
5(JKA)
0.249;-2115.0
A(5JK)
0.290;-2115.0
JA(5K)
0.265;-2115.0
QA(5Q)
0.230;-1755.0
5QKA
0.195;-2420.0
67(6A)
0.209;-2305.0
(6T)(6A)
0.265;-1780.0
6(6KA)
0.216;-1975.0
(67TA)
0.198;-2445.0
77(6A)
0.287;-2250.0
(7T)(6A)
0.266;-2085.0
7(6KA)
0.225;-2280.0
(68JA)
0.245;-2335.0
(89)(6A)
0.250;-2085.0
8(6QA)
0.221;-2280.0
T(69A)
0.214;-2335.0
9(6TA)
0.221;-2335.0
9Q(6A)
0.230;-2225.0
Q(6TA)
0.217;-2170.0
(TQ)(6A)
0.272;-1810.0
(6JKA)
0.243;-2060.0
JK(6A)
0.282;-2060.0
K(6KA)
0.301;-1590.0
668A
0.218;-2610.0
6A(6J)
0.307;-2085.0
(67)(7A)
0.210;-1890.0
6(7TA)
0.208;-2445.0
6Q(7A)
0.242;-2335.0
(67)(9A)
0.225;-2140.0
JA(67)
0.235;-2390.0
67(8A)
0.205;-2555.0
67(TA)
0.206;-2445.0
67(QA)
0.269;-2335.0
(68)(8A)
0.232;-1780.0
6(8JA)
0.210;-2335.0
6K(8A)
0.214;-2225.0
(68)(JA)
0.276;-1975.0
KA(68)
0.234;-2225.0
6A(8T)
0.204;-2390.0
6A(8Q)
0.236;-2280.0
6(9TA)
0.221;-2335.0
6Q(9A)
0.227;-2225.0
(69)(JA)
0.272;-1920.0
KA(69)
0.238;-2170.0
6A(9J)
0.218;-2280.0
6A(9K)
0.256;-2170.0
(6Q)(TA)
0.257;-1810.0
JA(6T)
0.197;-2225.0
6T(JA)
0.216;-2225.0
6T(KA)
0.221;-2115.0
6Q(JA)
0.240;-2115.0
(6J)(KA)
0.253;-1700.0
6J(KA)
0.299;-2060.0
6K(QA)
0.213;-2005.0
6A(QK)
0.241;-2005.0
(78)(7A)
0.256;-1780.0
7(7JA)
0.252;-1975.0
7K(7A)
0.211;-1865.0
(78QA)
0.220;-2225.0
8(7TA)
0.222;-2335.0
8Q(7A)
0.242;-2225.0
J(79A)
0.179;-2225.0
9T(7A)
0.249;-2280.0
(9K)(7A)
0.291;-1755.0
K(7TA)
0.238;-2060.0
T(7KA)
0.213;-2060.0
JJ(7A)
0.292;-1755.0
(7QKA)
0.200;-1950.0
777A
0.292;-2195.0
7A(7T)
0.265;-2030.0
77(KA)
0.278;-1865.0
7(8TA)
0.290;-2335.0
7Q(8A)
0.233;-2225.0
(78)(TA)
0.267;-1975.0
QA(78)
0.222;-2225.0
789A
0.185;-2750.0
78JA
0.217;-2640.0
78KA
0.247;-2530.0
7J(9A)
0.191;-2225.0
(79)(TA)
0.240;-1920.0
QA(79)
0.284;-2170.0
79TA
0.172;-2640.0
79QA
0.223;-2530.0
(7J)(TA)
0.293;-1810.0
TA(7T)
0.251;-1865.0
A(7TK)
0.217;-2060.0
TA(7Q)
0.190;-2115.0
7J(JA)
0.270;-1755.0
(7J)(QA)
0.225;-1700.0
JA(7Q)
0.247;-2060.0
7Q(QA)
0.259;-1645.0
7QQA
0.195;-2005.0
7KKA
0.291;-1895.0
8(8JA)
0.261;-1865.0
8K(8A)
0.287;-1755.0
(89KA)
0.225;-2060.0
9J(8A)
0.190;-2170.0
(8TJA)
0.229;-2115.0
(TJ)(8A)
0.257;-1755.0
J(8JA)
0.287;-1700.0
JQ(8A)
0.239;-2005.0
Q(8KA)
0.306;-1895.0
889A
0.183;-2335.0
8A(8Q)
0.242;-1810.0
(8T)(9A)
0.237;-1865.0
8(9KA)
0.261;-2060.0
A(89J)
0.208;-2170.0
899A
0.211;-2280.0
89JA
0.216;-2530.0
89KA
0.219;-2420.0
8Q(TA)
0.195;-2060.0
(8T)(QA)
0.277;-1700.0
TA(8J)
0.244;-2115.0
TA(8K)
0.278;-2005.0
8(JKA)
0.221;-1950.0
A(8JK)
0.198;-1950.0
JA(8K)
0.208;-1950.0
QA(8Q)
0.263;-1590.0
8QKA
0.208;-2255.0
9T(9A)
0.204;-1810.0
(9K)(9A)
0.292;-1285.0
K(9TA)
0.274;-1950.0
T(9KA)
0.247;-1950.0
JJ(9A)
0.260;-1645.0
(9QKA)
0.212;-1840.0
999A
0.331;-1865.0
9A(9Q)
0.295;-1700.0
(9J)(TA)
0.270;-1700.0
TA(9T)
0.287;-1755.0
A(9TK)
0.272;-1950.0
TA(9Q)
0.231;-2005.0
9J(JA)
0.274;-1645.0
(9J)(QA)
0.263;-1590.0
JA(9Q)
0.236;-1950.0
9Q(QA)
0.270;-1535.0
9QQA
0.208;-1895.0
9KKA
0.298;-1785.0
T(TKA)
0.284;-1535.0
JJ(TA)
0.270;-1590.0
(TQKA)
0.278;-1785.0
TTTA
0.275;-1700.0
TA(TK)
0.301;-1535.0
(TK)(JA)
0.342;-1480.0
KA(TJ)
0.229;-1840.0
TA(JK)
0.286;-1840.0
(TQ)(KA)
0.298;-1425.0
(TK)(KA)
0.312;-1010.0
J(JKA)
0.283;-1425.0
(QK)(JA)
0.330;-1370.0
JJ(KA)
0.320;-1425.0
QA(JQ)
0.262;-1425.0
JQKA
0.190;-2090.0
QK(QA)
0.317;-1315.0
QK(KA)
0.311;-1260.0
22(24)
0.149;-3210.0
22(28)
0.138;-2990.0
22(2Q)
0.195;-2770.0
24(23)
0.177;-3515.0
(23)(27)
0.180;-2990.0
2(23T)
0.168;-3185.0
2Q(23)
0.180;-3075.0
23(25)
0.137;-3460.0
2237
0.136;-3710.0
22(3T)
0.224;-3185.0
23(2K)
0.217;-3020.0
2(246)
0.122;-3350.0
28(24)
0.146;-3240.0
(24)(2J)
0.240;-2715.0
2244
0.161;-3460.0
22(47)
0.148;-3295.0
24(2T)
0.178;-3130.0
224Q
0.133;-3380.0
26(25)
0.127;-3295.0
(25)(29)
0.201;-2770.0
2(25Q)
0.200;-2965.0
22(56)
0.174;-3295.0
25(29)
0.195;-3130.0
225J
0.160;-3380.0
26(26)
0.199;-2880.0
(26)(29)
0.168;-2715.0
2(26Q)
0.214;-2910.0
22(67)
0.199;-3185.0
26(2T)
0.175;-3020.0
226Q
0.141;-3270.0
28(27)
0.179;-3075.0
(27)(2J)
0.200;-2550.0
2277
0.183;-3130.0
22(7T)
0.217;-2965.0
27(2K)
0.204;-2800.0
2(28T)
0.182;-2910.0
2Q(28)
0.191;-2800.0
28(2T)
0.207;-2910.0
228Q
0.154;-3160.0
2T(29)
0.157;-2855.0
(29)(2K)
0.262;-2330.0
229J
0.199;-3160.0
2T(2T)
0.247;-2440.0
(2T)(2K)
0.226;-2275.0
22TQ
0.160;-3050.0
2Q(2J)
0.212;-2635.0
2J(2K)
0.243;-2580.0
22QQ
0.218;-2580.0
3(234)
0.121;-3460.0
36(23)
0.155;-3350.0
(23)(39)
0.203;-2825.0
3(23Q)
0.213;-3020.0
5(234)
0.110;-3710.0
9(234)
0.131;-3490.0
K(234)
0.130;-3270.0
4(237)
0.168;-3600.0
49(23)
0.174;-3490.0
(23)(4Q)
0.178;-2965.0
(2357)
0.183;-3545.0
(235J)
0.153;-3325.0
(23)(56)
0.171;-3240.0
5(239)
0.128;-3435.0
5J(23)
0.170;-3325.0
(2367)
0.166;-3490.0
(236J)
0.187;-3270.0
(23)(67)
0.161;-3130.0
6(23T)
0.130;-3325.0
6Q(23)
0.140;-3215.0
9(237)
0.197;-3325.0
K(237)
0.171;-3105.0
7(23T)
0.169;-3270.0
7Q(23)
0.141;-3160.0
T(238)
0.143;-3215.0
8(239)
0.193;-3270.0
8J(23)
0.188;-3160.0
(239T)
0.205;-3160.0
99(23)
0.183;-2855.0
(23)(9Q)
0.231;-2690.0
(23TQ)
0.187;-2995.0
T(23Q)
0.218;-2995.0
Q(23J)
0.164;-2940.0
(23)(JK)
0.217;-2525.0
QK(23)
0.184;-2830.0
23(35)
0.171;-3405.0
33(28)
0.175;-3240.0
233T
0.153;-3490.0
23(3K)
0.207;-2965.0
(24)(36)
0.176;-3295.0
3(249)
0.155;-3490.0
3J(24)
0.190;-3380.0
(34)(25)
0.167;-3350.0
27(34)
0.151;-3600.0
2(34T)
0.157;-3435.0
(34)(2K)
0.209;-2910.0
34(26)
0.154;-3655.0
34(28)
0.165;-3545.0
34(2T)
0.160;-3435.0
34(2Q)
0.164;-3325.0
(25)(35)
0.156;-2935.0
3(258)
0.153;-3490.0
3T(25)
0.144;-3380.0
(25)(3K)
0.243;-2855.0
27(35)
0.166;-3545.0
2(35T)
0.124;-3380.0
(35)(2K)
0.175;-2855.0
35(27)
0.130;-3545.0
35(29)
0.187;-3435.0
35(2J)
0.129;-3325.0
35(2K)
0.190;-3215.0
37(26)
0.155;-3490.0
(26)(3T)
0.197;-2965.0
3(26K)
0.207;-3160.0
2(368)
0.159;-3435.0
(36)(2J)
0.179;-2910.0
2K(36)
0.196;-3160.0
23(68)
0.133;-3435.0
23(6T)
0.135;-3325.0
23(6Q)
0.172;-3215.0
3(278)
0.183;-3380.0
3T(27)
0.186;-3270.0
(27)(3K)
0.220;-2745.0
29(37)
0.211;-3325.0
2(37Q)
0.178;-3160.0
23(78)
0.159;-3380.0
23(7T)
0.157;-3270.0
23(7Q)
0.161;-3160.0
3(289)
0.120;-3270.0
3J(28)
0.157;-3160.0
(38)(29)
0.193;-2910.0
2J(38)
0.157;-3160.0
38(29)
0.136;-3270.0
38(2J)
0.173;-3160.0
38(2K)
0.179;-3050.0
3T(29)
0.134;-3160.0
(29)(3K)
0.243;-2635.0
2J(39)
0.197;-3105.0
39(2T)
0.175;-3160.0
39(2Q)
0.149;-3050.0
(2T)(3T)
0.239;-2385.0
3(2TK)
0.213;-2940.0
2(3TQ)
0.190;-2995.0
23(TJ)
0.190;-3050.0
23(TK)
0.157;-2940.0
(2J)(3K)
0.184;-2525.0
2K(3J)
0.159;-2885.0
23(JK)
0.228;-2885.0
(3Q)(2K)
0.235;-2470.0
(2K)(3K)
0.268;-2055.0
4(246)
0.155;-3240.0
48(24)
0.133;-3130.0
(24)(4J)
0.149;-2605.0
5(245)
0.151;-3240.0
9(245)
0.150;-3380.0
K(245)
0.172;-3160.0
5(248)
0.135;-3435.0
5T(24)
0.174;-3325.0
(24)(5K)
0.233;-2800.0
9(246)
0.178;-3325.0
K(246)
0.163;-3105.0
6(249)
0.147;-3325.0
6J(24)
0.183;-3215.0
(2478)
0.140;-3325.0
(247Q)
0.158;-3105.0
7(249)
0.142;-3270.0
7J(24)
0.183;-3160.0
(2489)
0.137;-3215.0
(248K)
0.153;-2995.0
8T(24)
0.171;-3160.0
(24)(8K)
0.166;-2635.0
Q(249)
0.167;-2995.0
(24)(9J)
0.240;-2690.0
T(24T)
0.182;-2690.0
T(24J)
0.175;-2995.0
TK(24)
0.194;-2885.0
(24)(JQ)
0.186;-2525.0
QQ(24)
0.201;-2470.0
24(45)
0.142;-3295.0
44(28)
0.150;-3130.0
244T
0.166;-3380.0
24(4K)
0.216;-2855.0
(25)(47)
0.159;-3130.0
4(25T)
0.129;-3325.0
4Q(25)
0.166;-3215.0
(45)(27)
0.181;-3130.0
29(45)
0.156;-3380.0
2(45Q)
0.220;-3215.0
24(56)
0.137;-3545.0
24(58)
0.113;-3435.0
24(5T)
0.140;-3325.0
24(5Q)
0.171;-3215.0
4(267)
0.180;-3435.0
49(26)
0.145;-3325.0
(26)(4Q)
0.153;-2800.0
27(46)
0.164;-3435.0
2(46T)
0.179;-3270.0
(46)(2K)
0.196;-2745.0
46(28)
0.156;-3380.0
46(2T)
0.143;-3270.0
46(2Q)
0.144;-3160.0
(27)(47)
0.209;-2660.0
4(27T)
0.195;-3215.0
4Q(27)
0.170;-3105.0
(47)(29)
0.184;-2910.0
2J(47)
0.195;-3160.0
47(28)
0.130;-3325.0
47(2T)
0.186;-3215.0
47(2Q)
0.184;-3105.0
(28)(48)
0.205;-2550.0
4(28J)
0.185;-3105.0
4K(28)
0.162;-2995.0
(48)(2J)
0.183;-2745.0
2K(48)
0.183;-2995.0
24(8T)
0.168;-3160.0
24(8Q)
0.169;-3050.0
4(29T)
0.180;-3105.0
4Q(29)
0.176;-2995.0
(49)(2J)
0.195;-2690.0
2K(49)
0.192;-2940.0
24(9J)
0.157;-3050.0
24(9K)
0.169;-2940.0
(2T)(4Q)
0.190;-2580.0
2J(4T)
0.174;-2995.0
4T(2J)
0.177;-2995.0
4T(2K)
0.191;-2885.0
4Q(2J)
0.204;-2885.0
(4J)(2K)
0.235;-2470.0
4J(2K)
0.153;-2830.0
4K(2Q)
0.232;-2775.0
24(QK)
0.193;-2775.0
(25)(56)
0.183;-2770.0
5(259)
0.138;-2965.0
5J(25)
0.206;-2855.0
(2567)
0.159;-3380.0
(256J)
0.211;-3160.0
(25)(67)
0.185;-3020.0
6(25T)
0.177;-3215.0
6Q(25)
0.154;-3105.0
9(257)
0.123;-3215.0
K(257)
0.209;-2995.0
7(25T)
0.148;-3160.0
7Q(25)
0.178;-3050.0
T(258)
0.188;-3105.0
8(259)
0.141;-3160.0
8J(25)
0.147;-3050.0
(259T)
0.151;-3050.0
99(25)
0.221;-2745.0
(25)(9Q)
0.241;-2580.0
(25TQ)
0.179;-2885.0
T(25Q)
0.209;-2885.0
Q(25J)
0.186;-2830.0
(25)(JK)
0.257;-2415.0
QK(25)
0.160;-2720.0
25(57)
0.192;-3075.0
55(2T)
0.180;-2910.0
255Q
0.142;-3160.0
57(26)
0.115;-3380.0
(26)(5T)
0.184;-2855.0
5(26K)
0.217;-3050.0
2(568)
0.156;-3325.0
(56)(2J)
0.146;-2800.0
2K(56)
0.148;-3050.0
25(68)
0.176;-3325.0
25(6T)
0.173;-3215.0
25(6Q)
0.196;-3105.0
5(278)
0.128;-3270.0
5T(27)
0.138;-3160.0
(27)(5K)
0.192;-2635.0
29(57)
0.148;-3215.0
2(57Q)
0.154;-3050.0
25(78)
0.145;-3270.0
25(7T)
0.182;-3160.0
25(7Q)
0.167;-3050.0
5(289)
0.163;-3160.0
5J(28)
0.176;-3050.0
(58)(29)
0.213;-2800.0
2J(58)
0.173;-3050.0
58(29)
0.207;-3160.0
58(2J)
0.173;-3050.0
58(2K)
0.169;-2940.0
5T(29)
0.168;-3050.0
(29)(5K)
0.201;-2525.0
2J(59)
0.162;-2995.0
59(2T)
0.199;-3050.0
59(2Q)
0.144;-2940.0
(2T)(5T)
0.250;-2275.0
5(2TK)
0.168;-2830.0
2(5TQ)
0.170;-2885.0
25(TJ)
0.167;-2940.0
25(TK)
0.229;-2830.0
(2J)(5K)
0.224;-2415.0
2K(5J)
0.163;-2775.0
25(JK)
0.205;-2775.0
(5Q)(2K)
0.209;-2360.0
(2K)(5K)
0.223;-1945.0
6(268)
0.200;-2910.0
6T(26)
0.198;-2800.0
(26)(6K)
0.240;-2275.0
T(267)
0.156;-3105.0
7(268)
0.156;-3215.0
7T(26)
0.167;-3105.0
(26)(7K)
0.205;-2580.0
J(268)
0.164;-2995.0
89(26)
0.158;-3105.0
(26)(8Q)
0.220;-2580.0
(269J)
0.188;-2940.0
(26)(9T)
0.171;-2635.0
9(26K)
0.193;-2830.0
(26TK)
0.188;-2775.0
TQ(26)
0.222;-2830.0
K(26J)
0.198;-2720.0
Q(26Q)
0.192;-2360.0
KK(26)
0.219;-2250.0
66(29)
0.179;-2855.0
266J
0.206;-3105.0
67(27)
0.177;-2910.0
(27)(6T)
0.186;-2745.0
6(27K)
0.175;-2940.0
2(679)
0.155;-3160.0
(67)(2Q)
0.188;-2635.0
27(68)
0.157;-3215.0
27(6T)
0.146;-3105.0
27(6Q)
0.159;-2995.0
68(28)
0.201;-2800.0
(28)(6J)
0.208;-2635.0
28(68)
0.177;-2800.0
2(68J)
0.185;-2995.0
2688
0.191;-3160.0
268T
0.140;-3410.0
268Q
0.150;-3300.0
(29)(6T)
0.205;-2635.0
6(29K)
0.184;-2830.0
2(69J)
0.211;-2940.0
2699
0.215;-3050.0
269J
0.160;-3300.0
269K
0.170;-3190.0
6Q(2T)
0.174;-2830.0
(6T)(2Q)
0.250;-2470.0
2T(6J)
0.223;-2885.0
2T(6K)
0.195;-2775.0
6(2JK)
0.170;-2720.0
2(6JK)
0.180;-2720.0
2J(6K)
0.198;-2720.0
2Q(6Q)
0.210;-2360.0
26QK
0.179;-3025.0
78(27)
0.187;-2800.0
(27)(7J)
0.224;-2275.0
8(278)
0.206;-2745.0
Q(278)
0.233;-2885.0
(27)(8T)
0.170;-2635.0
8(27K)
0.162;-2830.0
(279Q)
0.200;-2830.0
9(27J)
0.230;-2885.0
9K(27)
0.173;-2775.0
TT(27)
0.174;-2525.0
(27)(TK)
0.210;-2360.0
J(27Q)
0.168;-2720.0
K(27Q)
0.257;-2610.0
77(28)
0.219;-2800.0
277T
0.189;-3050.0
27(7K)
0.256;-2525.0
(28)(7T)
0.205;-2635.0
7(28K)
0.149;-2830.0
2(78T)
0.135;-2995.0
(78)(2K)
0.189;-2470.0
78(2T)
0.204;-2995.0
78(2Q)
0.249;-2885.0
(29)(79)
0.257;-2275.0
7(29Q)
0.182;-2830.0
2(79T)
0.179;-2940.0
(79)(2K)
0.215;-2415.0
79(2J)
0.158;-2885.0
79(2K)
0.194;-2775.0
7J(2T)
0.211;-2830.0
(7T)(2J)
0.235;-2470.0
2K(7T)
0.218;-2720.0
27(TQ)
0.251;-2775.0
7(2JQ)
0.244;-2720.0
2(7JQ)
0.173;-2720.0
27(JQ)
0.175;-2720.0
7(2QK)
0.159;-2610.0
7Q(2K)
0.168;-2610.0
88(28)
0.232;-2330.0
(28)(8J)
0.291;-2165.0
9(289)
0.189;-2580.0
K(289)
0.153;-2720.0
9(28Q)
0.213;-2775.0
J(28T)
0.180;-2775.0
TJ(28)
0.196;-2775.0
(28JQ)
0.180;-2665.0
J(28K)
0.215;-2610.0
(28)(QK)
0.234;-2195.0
88(2T)
0.223;-2580.0
288Q
0.191;-2830.0
8T(29)
0.169;-2885.0
(29)(8K)
0.169;-2360.0
2J(89)
0.200;-2830.0
89(2T)
0.183;-2885.0
89(2Q)
0.222;-2775.0
(2T)(8T)
0.247;-2110.0
8(2TK)
0.151;-2665.0
2(8TQ)
0.161;-2720.0
28(TJ)
0.180;-2775.0
28(TK)
0.210;-2665.0
(2J)(8K)
0.234;-2250.0
2K(8J)
0.214;-2610.0
28(JK)
0.173;-2610.0
(8Q)(2K)
0.212;-2195.0
(2K)(8K)
0.298;-1780.0
9(29J)
0.268;-2415.0
9K(29)
0.212;-2305.0
TT(29)
0.214;-2415.0
(29)(TK)
0.220;-2250.0
J(29Q)
0.188;-2610.0
K(29Q)
0.215;-2500.0
99(2T)
0.204;-2470.0
299Q
0.217;-2720.0
9J(2T)
0.188;-2720.0
(9T)(2J)
0.250;-2360.0
2K(9T)
0.183;-2610.0
29(TQ)
0.188;-2665.0
9(2JQ)
0.205;-2610.0
2(9JQ)
0.170;-2610.0
29(JQ)
0.186;-2610.0
9(2QK)
0.190;-2500.0
9Q(2K)
0.211;-2500.0
TT(2T)
0.216;-2000.0
(2T)(TK)
0.258;-1835.0
J(2TQ)
0.188;-2555.0
K(2TQ)
0.174;-2445.0
TT(2J)
0.219;-2305.0
2TTK
0.204;-2555.0
TK(2J)
0.174;-2500.0
2TJJ
0.194;-2610.0
2TJK
0.228;-2860.0
2(TQK)
0.220;-2445.0
TK(2K)
0.266;-2030.0
(2J)(JK)
0.252;-1725.0
QK(2J)
0.227;-2390.0
2J(JK)
0.211;-2085.0
(JQ)(2K)
0.259;-2030.0
(2K)(JK)
0.266;-1615.0
K(2QK)
0.295;-1920.0
2K(QK)
0.216;-1920.0
3335
0.174;-3350.0
3339
0.185;-3130.0
333K
0.198;-2910.0
36(34)
0.162;-3240.0
(34)(39)
0.173;-2715.0
3(34Q)
0.199;-2910.0
33(45)
0.147;-3295.0
34(38)
0.184;-3130.0
334T
0.154;-3380.0
33(4K)
0.193;-2855.0
(35)(37)
0.151;-2770.0
3(35T)
0.196;-2965.0
3Q(35)
0.178;-2855.0
35(37)
0.206;-3130.0
3359
0.173;-3380.0
33(5Q)
0.188;-2855.0
(36)(37)
0.227;-2715.0
3(36T)
0.205;-2910.0
3Q(36)
0.183;-2800.0
36(38)
0.184;-3020.0
336T
0.184;-3270.0
33(6K)
0.206;-2745.0
(37)(39)
0.248;-2550.0
3(37Q)
0.187;-2745.0
33(78)
0.198;-2965.0
37(3J)
0.231;-2800.0
337K
0.149;-3050.0
3T(38)
0.157;-2800.0
(38)(3K)
0.253;-2275.0
338T
0.195;-3160.0
33(8K)
0.212;-2635.0
(39)(3J)
0.249;-2330.0
3399
0.215;-2800.0
33(9Q)
0.196;-2635.0
(3T)(3J)
0.248;-2275.0
33TT
0.195;-2690.0
33(TK)
0.191;-2525.0
(3J)(3K)
0.261;-2110.0
33JK
0.177;-2830.0
33(QK)
0.169;-2415.0
45(34)
0.166;-3240.0
(34)(48)
0.194;-2715.0
4(34J)
0.172;-2910.0
4K(34)
0.194;-2800.0
(3459)
0.133;-3325.0
(345K)
0.142;-3105.0
57(34)
0.166;-3435.0
(34)(5T)
0.186;-2910.0
5(34K)
0.214;-3105.0
(3469)
0.150;-3270.0
(346K)
0.185;-3050.0
68(34)
0.182;-3325.0
(34)(6J)
0.236;-2800.0
7(347)
0.179;-2965.0
J(347)
0.180;-3105.0
78(34)
0.158;-3270.0
(34)(7J)
0.160;-2745.0
8(348)
0.174;-2855.0
Q(348)
0.189;-2995.0
(34)(8T)
0.196;-2745.0
8(34K)
0.193;-2940.0
(349Q)
0.186;-2940.0
9(34J)
0.185;-2995.0
9K(34)
0.194;-2885.0
TT(34)
0.196;-2635.0
(34)(TK)
0.161;-2470.0
J(34Q)
0.220;-2830.0
K(34Q)
0.202;-2720.0
44(35)
0.173;-3240.0
3447
0.160;-3490.0
34(4T)
0.157;-2965.0
44(3K)
0.216;-2800.0
4(357)
0.126;-3435.0
49(35)
0.199;-3325.0
(35)(4Q)
0.203;-2800.0
36(45)
0.141;-3490.0
3(459)
0.168;-3325.0
(45)(3Q)
0.180;-2800.0
35(46)
0.136;-3490.0
35(48)
0.163;-3380.0
35(4T)
0.126;-3270.0
35(4Q)
0.134;-3160.0
46(36)
0.201;-3075.0
(36)(49)
0.166;-2910.0
4(36Q)
0.177;-3105.0
3(467)
0.156;-3380.0
(46)(3T)
0.191;-2855.0
3Q(46)
0.182;-3105.0
3467
0.126;-3740.0
3469
0.175;-3630.0
346J
0.169;-3520.0
346K
0.131;-3410.0
49(37)
0.170;-3215.0
(37)(4Q)
0.217;-2690.0
38(47)
0.184;-3270.0
3(47J)
0.174;-3105.0
3477
0.164;-3325.0
3479
0.153;-3575.0
347J
0.180;-3465.0
347K
0.138;-3355.0
4T(38)
0.188;-3105.0
(38)(4K)
0.168;-2580.0
3T(48)
0.195;-3105.0
3(48K)
0.182;-2940.0
38(4T)
0.153;-3105.0
38(4Q)
0.193;-2995.0
49(39)
0.179;-2745.0
(39)(4Q)
0.181;-2580.0
3T(49)
0.217;-3050.0
3(49K)
0.146;-2885.0
39(4J)
0.172;-2995.0
39(4K)
0.139;-2885.0
4(3TQ)
0.151;-2885.0
3(4TJ)
0.196;-2940.0
34TT
0.142;-2995.0
34TQ
0.162;-3245.0
(3J)(4Q)
0.215;-2470.0
3Q(4J)
0.140;-2830.0
34JQ
0.181;-3190.0
(3Q)(4K)
0.286;-2360.0
3Q(4K)
0.221;-2720.0
5(356)
0.155;-3075.0
58(35)
0.194;-2965.0
(35)(5J)
0.217;-2440.0
6(356)
0.155;-3020.0
T(356)
0.174;-3160.0
6(357)
0.175;-3325.0
69(35)
0.186;-3215.0
(35)(6Q)
0.191;-2690.0
(3579)
0.162;-3160.0
(357K)
0.149;-2940.0
79(35)
0.178;-3160.0
(35)(7Q)
0.218;-2635.0
(358T)
0.187;-3050.0
88(35)
0.195;-2800.0
(35)(8J)
0.167;-2635.0
9(359)
0.184;-2690.0
K(359)
0.175;-2830.0
9(35Q)
0.200;-2885.0
J(35T)
0.212;-2885.0
TJ(35)
0.210;-2885.0
(35JQ)
0.206;-2775.0
J(35K)
0.175;-2720.0
(35)(QK)
0.187;-2305.0
55(37)
0.174;-3020.0
3559
0.147;-3270.0
35(5Q)
0.181;-2745.0
(36)(57)
0.176;-2965.0
5(36T)
0.175;-3160.0
5Q(36)
0.152;-3050.0
(56)(38)
0.200;-2910.0
3T(56)
0.190;-3160.0
3(56K)
0.193;-2995.0
36(58)
0.183;-3270.0
36(5T)
0.183;-3160.0
36(5Q)
0.153;-3050.0
57(37)
0.164;-2910.0
(37)(5T)
0.188;-2745.0
5(37K)
0.204;-2940.0
3(579)
0.202;-3160.0
(57)(3Q)
0.220;-2635.0
37(58)
0.142;-3215.0
37(5T)
0.176;-3105.0
37(5Q)
0.214;-2995.0
58(38)
0.201;-2800.0
(38)(5J)
0.163;-2635.0
38(58)
0.183;-2800.0
3(58J)
0.192;-2995.0
3588
0.162;-3160.0
358T
0.188;-3410.0
358Q
0.179;-3300.0
(39)(5T)
0.158;-2635.0
5(39K)
0.230;-2830.0
3(59J)
0.138;-2940.0
3599
0.159;-3050.0
359J
0.129;-3300.0
359K
0.149;-3190.0
5Q(3T)
0.224;-2830.0
(5T)(3Q)
0.231;-2470.0
3T(5J)
0.209;-2885.0
3T(5K)
0.182;-2775.0
5(3JK)
0.216;-2720.0
3(5JK)
0.220;-2720.0
3J(5K)
0.157;-2720.0
3Q(5Q)
0.238;-2360.0
35QK
0.200;-3025.0
67(36)
0.160;-2910.0
(36)(6T)
0.228;-2385.0
6(36K)
0.276;-2580.0
(367T)
0.185;-3050.0
77(36)
0.219;-2855.0
(36)(7T)
0.167;-2690.0
7(36K)
0.231;-2885.0
(368J)
0.171;-2940.0
(36)(89)
0.189;-2690.0
8(36Q)
0.162;-2885.0
T(369)
0.182;-2940.0
9(36T)
0.216;-2940.0
9Q(36)
0.183;-2830.0
Q(36T)
0.200;-2775.0
(36)(TQ)
0.189;-2415.0
(36JK)
0.214;-2665.0
JK(36)
0.240;-2665.0
K(36K)
0.244;-2195.0
3668
0.161;-3215.0
36(6J)
0.209;-2690.0
(37)(67)
0.252;-2495.0
6(37T)
0.153;-3050.0
6Q(37)
0.158;-2940.0
(67)(39)
0.210;-2745.0
3J(67)
0.211;-2995.0
67(38)
0.183;-3160.0
67(3T)
0.198;-3050.0
67(3Q)
0.184;-2940.0
(38)(68)
0.193;-2385.0
6(38J)
0.194;-2940.0
6K(38)
0.169;-2830.0
(68)(3J)
0.165;-2580.0
3K(68)
0.178;-2830.0
36(8T)
0.149;-2995.0
36(8Q)
0.238;-2885.0
6(39T)
0.246;-2940.0
6Q(39)
0.177;-2830.0
(69)(3J)
0.198;-2525.0
3K(69)
0.179;-2775.0
36(9J)
0.192;-2885.0
36(9K)
0.195;-2775.0
(3T)(6Q)
0.273;-2415.0
3J(6T)
0.174;-2830.0
6T(3J)
0.166;-2830.0
6T(3K)
0.164;-2720.0
6Q(3J)
0.189;-2720.0
(6J)(3K)
0.285;-2305.0
6J(3K)
0.236;-2665.0
6K(3Q)
0.180;-2610.0
36(QK)
0.214;-2610.0
(37)(78)
0.230;-2385.0
7(37J)
0.183;-2580.0
7K(37)
0.239;-2470.0
(378Q)
0.180;-2830.0
8(37T)
0.168;-2940.0
8Q(37)
0.234;-2830.0
J(379)
0.180;-2830.0
9T(37)
0.148;-2885.0
(37)(9K)
0.208;-2360.0
K(37T)
0.239;-2665.0
T(37K)
0.195;-2665.0
JJ(37)
0.202;-2360.0
(37QK)
0.174;-2555.0
3777
0.202;-2800.0
37(7T)
0.180;-2635.0
77(3K)
0.212;-2470.0
7(38T)
0.195;-2940.0
7Q(38)
0.159;-2830.0
(78)(3T)
0.161;-2580.0
3Q(78)
0.156;-2830.0
3789
0.142;-3355.0
378J
0.150;-3245.0
378K
0.180;-3135.0
7J(39)
0.172;-2830.0
(79)(3T)
0.191;-2525.0
3Q(79)
0.218;-2775.0
379T
0.125;-3245.0
379Q
0.195;-3135.0
(3T)(7J)
0.166;-2415.0
3T(7T)
0.199;-2470.0
3(7TK)
0.168;-2665.0
3T(7Q)
0.177;-2720.0
7J(3J)
0.244;-2360.0
(7J)(3Q)
0.212;-2305.0
3J(7Q)
0.163;-2665.0
7Q(3Q)
0.220;-2250.0
37QQ
0.171;-2610.0
37KK
0.185;-2500.0
8(38J)
0.267;-2470.0
8K(38)
0.232;-2360.0
(389K)
0.222;-2665.0
9J(38)
0.242;-2775.0
(38TJ)
0.163;-2720.0
(38)(TJ)
0.228;-2360.0
J(38J)
0.262;-2305.0
JQ(38)
0.190;-2610.0
Q(38K)
0.213;-2500.0
3889
0.196;-2940.0
38(8Q)
0.216;-2415.0
(39)(8T)
0.212;-2470.0
8(39K)
0.208;-2665.0
3(89J)
0.152;-2775.0
3899
0.200;-2885.0
389J
0.216;-3135.0
389K
0.165;-3025.0
8Q(3T)
0.187;-2665.0
(8T)(3Q)
0.277;-2305.0
3T(8J)
0.250;-2720.0
3T(8K)
0.207;-2610.0
8(3JK)
0.234;-2555.0
3(8JK)
0.167;-2555.0
3J(8K)
0.249;-2555.0
3Q(8Q)
0.205;-2195.0
38QK
0.193;-2860.0
9T(39)
0.190;-2415.0
(39)(9K)
0.234;-1890.0
K(39T)
0.217;-2555.0
T(39K)
0.194;-2555.0
JJ(39)
0.204;-2250.0
(39QK)
0.224;-2445.0
3999
0.257;-2470.0
39(9Q)
0.214;-2305.0
(3T)(9J)
0.248;-2305.0
3T(9T)
0.200;-2360.0
3(9TK)
0.237;-2555.0
3T(9Q)
0.195;-2610.0
9J(3J)
0.202;-2250.0
(9J)(3Q)
0.215;-2195.0
3J(9Q)
0.191;-2555.0
9Q(3Q)
0.236;-2140.0
39QQ
0.258;-2500.0
39KK
0.228;-2390.0
T(3TK)
0.229;-2140.0
JJ(3T)
0.230;-2195.0
(3TQK)
0.232;-2390.0
3TTT
0.197;-2305.0
3T(TK)
0.196;-2140.0
(3J)(TK)
0.225;-2085.0
3K(TJ)
0.238;-2445.0
3T(JK)
0.179;-2445.0
(TQ)(3K)
0.245;-2030.0
(3K)(TK)
0.274;-1615.0
J(3JK)
0.222;-2030.0
(3J)(QK)
0.277;-1975.0
JJ(3K)
0.246;-2030.0
3Q(JQ)
0.287;-2030.0
3JQK
0.181;-2695.0
QK(3Q)
0.218;-1920.0
QK(3K)
0.257;-1865.0
44(46)
0.179;-2770.0
44(4T)
0.243;-2550.0
(45)(45)
0.231;-2410.0
4(458)
0.235;-2965.0
4T(45)
0.227;-2855.0
(45)(4K)
0.251;-2330.0
4457
0.163;-3380.0
44(5T)
0.184;-2855.0
45(4K)
0.155;-2690.0
4(468)
0.169;-2910.0
4T(46)
0.197;-2800.0
(46)(4K)
0.215;-2275.0
4468
0.139;-3270.0
44(6J)
0.232;-2745.0
(47)(47)
0.210;-2190.0
4(47T)
0.187;-2745.0
4Q(47)
0.205;-2635.0
47(49)
0.189;-2800.0
447J
0.184;-3050.0
48(48)
0.264;-2440.0
(48)(4J)
0.224;-2275.0
4488
0.195;-2800.0
44(8J)
0.186;-2635.0
(49)(49)
0.284;-1970.0
4(49Q)
0.229;-2525.0
44(9T)
0.167;-2635.0
49(4K)
0.171;-2470.0
4(4TQ)
0.191;-2470.0
44(TJ)
0.198;-2525.0
(4J)(4J)
0.268;-1750.0
44JJ
0.203;-2470.0
4Q(4Q)
0.217;-2000.0
(4K)(4K)
0.268;-1530.0
(45)(57)
0.208;-2605.0
5(45T)
0.220;-2800.0
5Q(45)
0.246;-2690.0
8(456)
0.142;-3215.0
Q(456)
0.175;-2995.0
(45)(68)
0.189;-2855.0
6(45J)
0.182;-3050.0
6K(45)
0.174;-2940.0
(457J)
0.147;-2995.0
(45)(78)
0.212;-2800.0
7(45J)
0.150;-2995.0
7K(45)
0.186;-2885.0
(458Q)
0.165;-2885.0
8(45T)
0.220;-2995.0
8Q(45)
0.171;-2885.0
J(459)
0.169;-2885.0
9T(45)
0.212;-2940.0
(45)(9K)
0.207;-2415.0
K(45T)
0.165;-2720.0
T(45K)
0.166;-2720.0
JJ(45)
0.217;-2415.0
(45QK)
0.204;-2610.0
4555
0.199;-3075.0
45(58)
0.200;-2910.0
55(4J)
0.237;-2745.0
455K
0.170;-2995.0
58(46)
0.157;-3215.0
(46)(5J)
0.164;-2690.0
46(56)
0.209;-2965.0
4(569)
0.223;-3160.0
(56)(4Q)
0.203;-2635.0
46(57)
0.165;-3270.0
46(59)
0.198;-3160.0
46(5J)
0.170;-3050.0
46(5K)
0.152;-2940.0
5(479)
0.183;-3105.0
5J(47)
0.189;-2995.0
(57)(48)
0.208;-2800.0
4T(57)
0.189;-3050.0
4(57K)
0.178;-2885.0
47(59)
0.148;-3105.0
47(5J)
0.172;-2995.0
47(5K)
0.229;-2885.0
5(48T)
0.142;-2995.0
5Q(48)
0.200;-2885.0
(58)(4T)
0.179;-2635.0
4Q(58)
0.210;-2885.0
4589
0.143;-3410.0
458J
0.178;-3300.0
458K
0.161;-3190.0
5J(49)
0.188;-2885.0
(59)(4T)
0.218;-2580.0
4Q(59)
0.193;-2830.0
459T
0.177;-3300.0
459Q
0.167;-3190.0
(4T)(5J)
0.254;-2470.0
4T(5T)
0.208;-2525.0
4(5TK)
0.231;-2720.0
4T(5Q)
0.213;-2775.0
5J(4J)
0.235;-2415.0
(5J)(4Q)
0.173;-2360.0
4J(5Q)
0.250;-2720.0
5Q(4Q)
0.206;-2305.0
45QQ
0.145;-2665.0
45KK
0.176;-2555.0
6(469)
0.260;-2745.0
6J(46)
0.174;-2635.0
(4678)
0.187;-3105.0
(467Q)
0.173;-2885.0
7(469)
0.223;-3050.0
7J(46)
0.209;-2940.0
(4689)
0.233;-2995.0
(468K)
0.180;-2775.0
8T(46)
0.219;-2940.0
(46)(8K)
0.237;-2415.0
Q(469)
0.228;-2775.0
(46)(9J)
0.253;-2470.0
T(46T)
0.184;-2470.0
T(46J)
0.193;-2775.0
TK(46)
0.202;-2665.0
(46)(JQ)
0.172;-2305.0
QQ(46)
0.222;-2250.0
46(67)
0.140;-2855.0
66(4T)
0.148;-2690.0
466Q
0.216;-2940.0
68(47)
0.163;-3105.0
(47)(6J)
0.241;-2580.0
47(67)
0.217;-2800.0
4(67T)
0.192;-2995.0
(67)(4K)
0.215;-2470.0
67(49)
0.200;-3050.0
67(4J)
0.188;-2940.0
67(4K)
0.220;-2830.0
69(48)
0.174;-2995.0
(48)(6Q)
0.234;-2470.0
49(68)
0.166;-2995.0
4(68Q)
0.222;-2830.0
46(89)
0.208;-2995.0
46(8J)
0.188;-2885.0
46(8K)
0.143;-2775.0
(49)(6J)
0.211;-2470.0
49(69)
0.209;-2580.0
4(69Q)
0.199;-2775.0
46(9T)
0.161;-2885.0
46(9Q)
0.166;-2775.0
6(4TJ)
0.191;-2775.0
6K(4T)
0.229;-2665.0
(6T)(4K)
0.178;-2305.0
6T(4Q)
0.217;-2720.0
(4J)(6J)
0.251;-2000.0
4J(6J)
0.264;-2360.0
6J(4Q)
0.248;-2665.0
(4Q)(6Q)
0.260;-1890.0
4K(6Q)
0.210;-2555.0
4K(6K)
0.267;-2140.0
79(47)
0.201;-2635.0
(47)(7Q)
0.219;-2110.0
(478T)
0.180;-2885.0
88(47)
0.184;-2635.0
(47)(8J)
0.222;-2470.0
9(479)
0.204;-2525.0
K(479)
0.189;-2665.0
9(47Q)
0.215;-2720.0
J(47T)
0.188;-2720.0
TJ(47)
0.222;-2720.0
(47JQ)
0.214;-2610.0
J(47K)
0.172;-2555.0
(47)(QK)
0.238;-2140.0
77(49)
0.240;-2635.0
477J
0.181;-2885.0
78(48)
0.263;-2635.0
(48)(7J)
0.224;-2470.0
48(78)
0.184;-2635.0
4(78J)
0.186;-2830.0
4788
0.193;-2995.0
478T
0.194;-3245.0
478Q
0.198;-3135.0
(49)(7T)
0.253;-2470.0
7(49K)
0.244;-2665.0
4(79J)
0.236;-2775.0
4799
0.178;-2885.0
479J
0.166;-3135.0
479K
0.178;-3025.0
7Q(4T)
0.198;-2665.0
(7T)(4Q)
0.211;-2305.0
4T(7J)
0.211;-2720.0
4T(7K)
0.267;-2610.0
7(4JK)
0.174;-2555.0
4(7JK)
0.179;-2555.0
4J(7K)
0.216;-2555.0
4Q(7Q)
0.242;-2195.0
47QK
0.176;-2860.0
89(48)
0.258;-2525.0
(48)(8Q)
0.220;-2000.0
(489J)
0.218;-2720.0
(48)(9T)
0.194;-2415.0
9(48K)
0.174;-2610.0
(48TK)
0.226;-2555.0
TQ(48)
0.224;-2610.0
K(48J)
0.195;-2500.0
Q(48Q)
0.234;-2140.0
KK(48)
0.204;-2030.0
88(4J)
0.224;-2415.0
488K
0.151;-2665.0
8J(49)
0.212;-2720.0
(89)(4T)
0.219;-2415.0
4Q(89)
0.187;-2665.0
489T
0.147;-3135.0
489Q
0.218;-3025.0
(4T)(8J)
0.212;-2305.0
4T(8T)
0.204;-2360.0
4(8TK)
0.226;-2555.0
4T(8Q)
0.191;-2610.0
8J(4J)
0.257;-2250.0
(8J)(4Q)
0.235;-2195.0
4J(8Q)
0.210;-2555.0
8Q(4Q)
0.259;-2140.0
48QQ
0.238;-2500.0
48KK
0.218;-2390.0
9(49Q)
0.267;-2250.0
J(49T)
0.156;-2610.0
TJ(49)
0.251;-2610.0
(49JQ)
0.240;-2500.0
J(49K)
0.209;-2445.0
(49)(QK)
0.289;-2030.0
99(4J)
0.220;-2305.0
499K
0.198;-2555.0
9Q(4T)
0.210;-2555.0
(9T)(4Q)
0.216;-2195.0
4T(9J)
0.207;-2610.0
4T(9K)
0.210;-2500.0
9(4JK)
0.187;-2445.0
4(9JK)
0.201;-2445.0
4J(9K)
0.240;-2445.0
4Q(9Q)
0.262;-2085.0
49QK
0.249;-2750.0
TJ(4T)
0.240;-2195.0
(4TJQ)
0.238;-2445.0
J(4TK)
0.165;-2390.0
(4T)(QK)
0.263;-1975.0
TT(4Q)
0.242;-2140.0
T(4JQ)
0.163;-2445.0
4(TJQ)
0.251;-2445.0
4T(JQ)
0.210;-2445.0
T(4QK)
0.172;-2335.0
TQ(4K)
0.219;-2335.0
JJ(4J)
0.260;-1725.0
(4JQK)
0.200;-2280.0
4JJJ
0.249;-2085.0
JQ(4Q)
0.316;-1975.0
4JQQ
0.211;-2335.0
4JKK
0.264;-2225.0
QQ(4K)
0.314;-1865.0
4KKK
0.275;-1755.0
55(59)
0.224;-2440.0
55(5K)
0.176;-2220.0
(56)(58)
0.232;-2440.0
5(56J)
0.195;-2635.0
5K(56)
0.180;-2525.0
56(59)
0.182;-2745.0
556J
0.187;-2995.0
57(57)
0.213;-2440.0
(57)(5T)
0.202;-2275.0
5(57K)
0.216;-2470.0
55(79)
0.195;-2690.0
57(5Q)
0.193;-2525.0
5(589)
0.197;-2635.0
5J(58)
0.207;-2525.0
58(59)
0.246;-2635.0
558J
0.200;-2885.0
59(59)
0.236;-2220.0
(59)(5Q)
0.208;-2055.0
559T
0.175;-2885.0
55(9K)
0.221;-2360.0
(5T)(5Q)
0.225;-2000.0
55TJ
0.169;-2775.0
5J(5J)
0.235;-2000.0
5J(5Q)
0.191;-2305.0
5(5QK)
0.201;-2195.0
5K(5K)
0.256;-1780.0
68(56)
0.226;-2745.0
(56)(6J)
0.254;-2220.0
7(567)
0.172;-2745.0
J(567)
0.163;-2885.0
78(56)
0.214;-3050.0
(56)(7J)
0.241;-2525.0
8(568)
0.262;-2635.0
Q(568)
0.208;-2775.0
(56)(8T)
0.223;-2525.0
8(56K)
0.208;-2720.0
(569Q)
0.154;-2720.0
9(56J)
0.163;-2775.0
9K(56)
0.183;-2665.0
TT(56)
0.223;-2415.0
(56)(TK)
0.229;-2250.0
J(56Q)
0.188;-2610.0
K(56Q)
0.242;-2500.0
66(57)
0.178;-2800.0
5669
0.219;-3050.0
56(6Q)
0.227;-2525.0
(57)(68)
0.200;-2690.0
6(57J)
0.176;-2885.0
6K(57)
0.192;-2775.0
(67)(5T)
0.183;-2580.0
5Q(67)
0.204;-2830.0
5678
0.148;-3410.0
567T
0.137;-3300.0
567Q
0.189;-3190.0
(58)(69)
0.236;-2580.0
6(58Q)
0.168;-2775.0
5(689)
0.181;-2940.0
(68)(5Q)
0.216;-2415.0
58(69)
0.221;-2940.0
58(6J)
0.159;-2830.0
58(6K)
0.231;-2720.0
6(59J)
0.198;-2775.0
6K(59)
0.193;-2665.0
(69)(5Q)
0.236;-2360.0
59(6T)
0.183;-2830.0
59(6Q)
0.183;-2720.0
6T(5T)
0.227;-2415.0
(5T)(6K)
0.238;-2250.0
5Q(6T)
0.183;-2665.0
56TJ
0.197;-3080.0
56TK
0.204;-2970.0
6K(5J)
0.252;-2555.0
56JJ
0.220;-2665.0
56JK
0.197;-2915.0
5(6QK)
0.217;-2500.0
6K(5K)
0.271;-2085.0
(57)(79)
0.278;-2220.0
7(57Q)
0.208;-2415.0
9(578)
0.193;-2885.0
K(578)
0.177;-2665.0
8(57J)
0.234;-2775.0
8K(57)
0.206;-2665.0
(579K)
0.203;-2610.0
9J(57)
0.156;-2720.0
(57TJ)
0.248;-2665.0
(57)(TJ)
0.176;-2305.0
J(57J)
0.251;-2250.0
JQ(57)
0.206;-2555.0
Q(57K)
0.229;-2445.0
5778
0.166;-2995.0
57(7J)
0.209;-2470.0
(58)(78)
0.259;-2220.0
7(58J)
0.227;-2775.0
7K(58)
0.219;-2665.0
(78)(5J)
0.197;-2415.0
5K(78)
0.230;-2665.0
57(8T)
0.181;-2830.0
57(8Q)
0.249;-2720.0
7(59T)
0.214;-2775.0
7Q(59)
0.189;-2665.0
(79)(5J)
0.205;-2360.0
5K(79)
0.186;-2610.0
57(9J)
0.246;-2720.0
57(9K)
0.178;-2610.0
(5T)(7Q)
0.252;-2250.0
5J(7T)
0.158;-2665.0
7T(5J)
0.178;-2665.0
7T(5K)
0.232;-2555.0
7Q(5J)
0.209;-2555.0
(7J)(5K)
0.250;-2140.0
7J(5K)
0.223;-2500.0
7K(5Q)
0.180;-2445.0
57(QK)
0.195;-2445.0
(58)(89)
0.245;-2110.0
8(58Q)
0.261;-2305.0
T(589)
0.186;-2720.0
9(58T)
0.157;-2720.0
9Q(58)
0.212;-2610.0
Q(58T)
0.224;-2555.0
(58)(TQ)
0.193;-2195.0
(58JK)
0.218;-2445.0
JK(58)
0.222;-2445.0
K(58K)
0.235;-1975.0
588T
0.163;-2775.0
58(8K)
0.221;-2250.0
(59)(8J)
0.211;-2305.0
59(89)
0.183;-2415.0
5(89Q)
0.218;-2610.0
58(9T)
0.202;-2720.0
58(9Q)
0.198;-2610.0
8(5TJ)
0.212;-2610.0
8K(5T)
0.258;-2500.0
(8T)(5K)
0.246;-2140.0
8T(5Q)
0.249;-2555.0
(5J)(8J)
0.243;-1835.0
5J(8J)
0.229;-2195.0
8J(5Q)
0.164;-2500.0
(5Q)(8Q)
0.268;-1725.0
5K(8Q)
0.199;-2390.0
5K(8K)
0.255;-1975.0
9J(59)
0.217;-2250.0
(59TJ)
0.179;-2555.0
(59)(TJ)
0.238;-2195.0
J(59J)
0.249;-2140.0
JQ(59)
0.205;-2445.0
Q(59K)
0.232;-2335.0
599T
0.206;-2665.0
59(9K)
0.196;-2140.0
(5T)(9Q)
0.212;-2140.0
5J(9T)
0.229;-2555.0
9T(5J)
0.211;-2555.0
9T(5K)
0.229;-2445.0
9Q(5J)
0.268;-2445.0
(9J)(5K)
0.296;-2030.0
9J(5K)
0.260;-2390.0
9K(5Q)
0.215;-2335.0
59(QK)
0.234;-2335.0
(5T)(TJ)
0.261;-1780.0
J(5TJ)
0.298;-2085.0
JQ(5T)
0.215;-2390.0
Q(5TK)
0.193;-2280.0
5TTJ
0.241;-2500.0
TJ(5J)
0.237;-2085.0
(TJ)(5Q)
0.239;-2030.0
5J(TQ)
0.178;-2390.0
TQ(5Q)
0.258;-1975.0
5TQQ
0.246;-2335.0
5TKK
0.220;-2225.0
Q(5JQ)
0.284;-1920.0
KK(5J)
0.241;-1810.0
(5Q)(JQ)
0.275;-1560.0
5K(JQ)
0.210;-2225.0
5K(JK)
0.283;-1810.0
5QQQ
0.256;-1865.0
KK(5K)
0.311;-1340.0
6669
0.180;-2635.0
666K
0.195;-2415.0
69(67)
0.188;-2580.0
(67)(6Q)
0.242;-2055.0
6678
0.142;-2995.0
66(7J)
0.185;-2470.0
(68)(68)
0.295;-1860.0
6(68J)
0.170;-2415.0
6K(68)
0.209;-2305.0
68(6J)
0.205;-2415.0
668K
0.207;-2665.0
6J(69)
0.264;-2360.0
69(6T)
0.162;-2415.0
669Q
0.241;-2665.0
6J(6T)
0.291;-2305.0
6T(6J)
0.231;-2305.0
66TK
0.160;-2555.0
6K(6J)
0.209;-2140.0
(6Q)(6Q)
0.245;-1420.0
66QK
0.214;-2445.0
7(679)
0.182;-2525.0
7J(67)
0.195;-2415.0
(6789)
0.201;-2830.0
(678K)
0.222;-2610.0
8T(67)
0.165;-2775.0
(67)(8K)
0.208;-2250.0
Q(679)
0.213;-2610.0
(67)(9J)
0.230;-2305.0
T(67T)
0.181;-2305.0
T(67J)
0.202;-2610.0
TK(67)
0.212;-2500.0
(67)(JQ)
0.228;-2140.0
QQ(67)
0.227;-2085.0
67(78)
0.219;-2580.0
77(6J)
0.237;-2415.0
677K
0.177;-2665.0
7T(68)
0.201;-2775.0
(68)(7K)
0.270;-2250.0
6T(78)
0.230;-2775.0
6(78K)
0.207;-2610.0
68(7T)
0.191;-2775.0
68(7Q)
0.218;-2665.0
79(69)
0.205;-2415.0
(69)(7Q)
0.237;-2250.0
6T(79)
0.154;-2720.0
6(79K)
0.188;-2555.0
69(7J)
0.196;-2665.0
69(7K)
0.263;-2555.0
7(6TQ)
0.173;-2555.0
6(7TJ)
0.187;-2610.0
67TT
0.208;-2665.0
67TQ
0.202;-2915.0
(6J)(7Q)
0.255;-2140.0
6Q(7J)
0.175;-2500.0
67JQ
0.184;-2860.0
(6Q)(7K)
0.191;-2030.0
6Q(7K)
0.242;-2390.0
8(689)
0.274;-2415.0
8J(68)
0.218;-2305.0
(689T)
0.183;-2665.0
99(68)
0.231;-2360.0
(68)(9Q)
0.261;-2195.0
(68TQ)
0.238;-2500.0
T(68Q)
0.220;-2500.0
Q(68J)
0.267;-2445.0
(68)(JK)
0.254;-2030.0
QK(68)
0.224;-2335.0
68(8T)
0.192;-2360.0
88(6K)
0.201;-2195.0
8(69J)
0.170;-2610.0
8K(69)
0.169;-2500.0
(89)(6Q)
0.237;-2195.0
69(8T)
0.159;-2665.0
69(8Q)
0.222;-2555.0
8T(6T)
0.259;-2250.0
(6T)(8K)
0.236;-2085.0
6Q(8T)
0.219;-2500.0
68TJ
0.229;-2915.0
68TK
0.165;-2805.0
8K(6J)
0.227;-2390.0
68JJ
0.210;-2500.0
68JK
0.188;-2750.0
6(8QK)
0.260;-2335.0
8K(6K)
0.228;-1920.0
(69)(9J)
0.312;-1835.0
T(69T)
0.185;-2195.0
T(69J)
0.210;-2500.0
TK(69)
0.266;-2390.0
(69)(JQ)
0.212;-2030.0
QQ(69)
0.256;-1975.0
69(9T)
0.203;-2250.0
99(6K)
0.183;-2085.0
9(6TQ)
0.256;-2445.0
6(9TJ)
0.198;-2500.0
69TT
0.230;-2555.0
69TQ
0.228;-2805.0
(6J)(9Q)
0.297;-2030.0
6Q(9J)
0.200;-2390.0
69JQ
0.228;-2750.0
(6Q)(9K)
0.245;-1920.0
6Q(9K)
0.237;-2280.0
T(6TJ)
0.254;-2085.0
TK(6T)
0.265;-1975.0
(6T)(JQ)
0.296;-1975.0
QQ(6T)
0.257;-1920.0
6T(TJ)
0.223;-2085.0
(6J)(TJ)
0.221;-1670.0
6J(TJ)
0.262;-2030.0
TJ(6Q)
0.201;-2335.0
(6Q)(TQ)
0.251;-1560.0
6K(TQ)
0.209;-2225.0
6K(TK)
0.260;-1810.0
JK(6J)
0.269;-1865.0
K(6JK)
0.220;-1755.0
6JJK
0.224;-2225.0
6(JQK)
0.219;-2170.0
JK(6K)
0.283;-1755.0
KK(6Q)
0.287;-1700.0
6QKK
0.275;-2060.0
77(7T)
0.248;-2055.0
(78)(78)
0.299;-1750.0
7(78J)
0.279;-2305.0
7K(78)
0.226;-2195.0
78(7J)
0.296;-2305.0
778K
0.174;-2555.0
7J(79)
0.220;-2250.0
79(7T)
0.213;-2305.0
779Q
0.174;-2555.0
7J(7T)
0.240;-2195.0
7T(7J)
0.205;-2195.0
77TK
0.249;-2445.0
7K(7J)
0.223;-2030.0
(7Q)(7Q)
0.297;-1310.0
77QK
0.224;-2335.0
8(78T)
0.225;-2305.0
8Q(78)
0.181;-2195.0
J(789)
0.217;-2555.0
9T(78)
0.190;-2610.0
(78)(9K)
0.229;-2085.0
K(78T)
0.236;-2390.0
T(78K)
0.255;-2390.0
JJ(78)
0.283;-2085.0
(78QK)
0.246;-2280.0
7888
0.199;-2415.0
78(8J)
0.194;-2250.0
(79)(89)
0.265;-1945.0
8(79Q)
0.235;-2500.0
7(89T)
0.215;-2610.0
(89)(7K)
0.192;-2085.0
89(7J)
0.215;-2555.0
89(7K)
0.190;-2445.0
8J(7T)
0.193;-2500.0
(8T)(7J)
0.233;-2140.0
7K(8T)
0.205;-2390.0
78(TQ)
0.196;-2445.0
8(7JQ)
0.198;-2390.0
7(8JQ)
0.217;-2390.0
78(JQ)
0.242;-2390.0
8(7QK)
0.217;-2280.0
8Q(7K)
0.258;-2280.0
99(79)
0.247;-1890.0
(79)(9Q)
0.248;-1725.0
(79TQ)
0.230;-2390.0
T(79Q)
0.214;-2390.0
Q(79J)
0.236;-2335.0
(79)(JK)
0.214;-1920.0
QK(79)
0.231;-2225.0
79(9J)
0.238;-2140.0
(7T)(9T)
0.237;-1780.0
9(7TK)
0.203;-2335.0
7(9TQ)
0.206;-2390.0
79(TJ)
0.258;-2445.0
79(TK)
0.293;-2335.0
(7J)(9K)
0.227;-1920.0
7K(9J)
0.205;-2280.0
79(JK)
0.198;-2280.0
(9Q)(7K)
0.231;-1865.0
(7K)(9K)
0.227;-1450.0
T(7TQ)
0.226;-1975.0
Q(7TJ)
0.199;-2280.0
(7T)(JK)
0.261;-1865.0
QK(7T)
0.270;-2170.0
7T(TQ)
0.256;-1975.0
(7J)(TQ)
0.214;-1920.0
7Q(TJ)
0.209;-2280.0
7TJQ
0.185;-2640.0
(7Q)(TK)
0.320;-1810.0
7Q(TK)
0.306;-2170.0
J(7JQ)
0.276;-1865.0
K(7JQ)
0.242;-2115.0
JJ(7Q)
0.211;-1865.0
J(7QK)
0.252;-2115.0
JQ(7K)
0.214;-2115.0
QQ(7Q)
0.319;-1395.0
7Q(QK)
0.278;-1700.0
8888
0.249;-2000.0
888Q
0.220;-2140.0
8(89J)
0.238;-2140.0
8K(89)
0.214;-2030.0
89(8Q)
0.246;-2085.0
8(8TJ)
0.244;-2085.0
8K(8T)
0.268;-1975.0
8T(8K)
0.219;-1975.0
8(8JK)
0.235;-1920.0
88(JK)
0.288;-1920.0
8Q(8K)
0.264;-1865.0
(89)(9T)
0.288;-1780.0
9(89K)
0.204;-1975.0
(89TK)
0.200;-2280.0
TQ(89)
0.232;-2335.0
K(89J)
0.244;-2225.0
Q(89Q)
0.298;-1865.0
KK(89)
0.234;-1755.0
99(8Q)
0.226;-2030.0
9(8TJ)
0.213;-2390.0
9K(8T)
0.220;-2280.0
(9T)(8K)
0.268;-1920.0
9T(8Q)
0.211;-2335.0
(8J)(9J)
0.275;-1615.0
8J(9J)
0.238;-1975.0
9J(8Q)
0.272;-2280.0
(8Q)(9Q)
0.282;-1505.0
8K(9Q)
0.304;-2170.0
8K(9K)
0.205;-1755.0
TQ(8T)
0.232;-1920.0
K(8TJ)
0.270;-2170.0
Q(8TQ)
0.267;-1810.0
KK(8T)
0.247;-1700.0
