AAAA
0.359;495.0
5AAA
0.314;174.4
9AAA
0.334;256.9
KAAA
0.375;339.4
4A(2A)
0.308;-93.7
(2A)(7A)
0.346;103.1
A(2TA)
0.295;30.0
QA(2A)
0.334;71.3
2A(4A)
0.303;-93.7
26AA
0.252;-187.5
AA(29)
0.310;9.4
2A(QA)
0.338;71.3
A(34A)
0.286;-73.1
6A(3A)
0.273;-31.9
(3A)(9A)
0.344;165.0
A(3QA)
0.273;91.9
AA(34)
0.240;-73.1
3A(7A)
0.293;-11.2
39AA
0.298;-105.0
AA(3Q)
0.297;91.9
(4A)(5A)
0.310;103.1
A(48A)
0.315;30.0
TA(4A)
0.313;71.3
(4A)(KA)
0.285;268.1
46AA
0.290;-146.2
AA(49)
0.316;50.6
4A(QA)
0.255;112.5
A(56A)
0.291;9.4
8A(5A)
0.255;50.6
(5A)(JA)
0.323;247.5
55AA
0.280;-11.2
AA(58)
0.350;50.6
5A(JA)
0.259;112.5
5KAA
0.339;18.7
8A(6A)
0.314;71.3
(6A)(JA)
0.374;268.1
66AA
0.264;30.0
AA(69)
0.244;91.9
6A(QA)
0.357;153.7
A(78A)
0.257;91.9
TA(7A)
0.262;133.1
(7A)(KA)
0.316;330.0
79AA
0.297;-22.5
AA(7Q)
0.331;174.4
(8A)(9A)
0.302;268.1
A(8QA)
0.331;195.0
AA(89)
0.322;133.1
8A(QA)
0.289;195.0
A(9TA)
0.308;174.4
QA(9A)
0.351;215.6
9A(JA)
0.332;195.0
9KAA
0.276;101.3
QA(TA)
0.341;236.2
TA(QA)
0.318;236.2
A(JQA)
0.358;256.9
AA(JQ)
0.326;256.9
(QA)(KA)
0.386;433.1
KKAA
0.320;318.8
2(25A)
0.243;-320.6
27(2A)
0.223;-279.4
(2T)(2A)
0.319;-82.5
2(2KA)
0.233;-155.6
(236A)
0.168;-414.4
(23TA)
0.191;-331.9
33(2A)
0.181;-341.2
(36)(2A)
0.243;-279.4
3(29A)
0.195;-352.5
3J(2A)
0.253;-311.2
(245A)
0.210;-414.4
(249A)
0.235;-331.9
(24KA)
0.205;-249.4
46(2A)
0.222;-393.8
(49)(2A)
0.292;-196.9
4(2QA)
0.201;-270.0
6(25A)
0.237;-373.1
T(25A)
0.210;-290.6
5(26A)
0.173;-373.1
58(2A)
0.209;-331.9
(5J)(2A)
0.253;-135.0
6(26A)
0.311;-217.5
T(26A)
0.230;-270.0
6(27A)
0.233;-331.9
69(2A)
0.189;-290.6
(6Q)(2A)
0.318;-93.8
(279A)
0.300;-270.0
(27KA)
0.264;-187.5
79(2A)
0.232;-270.0
(7Q)(2A)
0.294;-73.1
(28TA)
0.246;-228.7
88(2A)
0.248;-135.0
(8J)(2A)
0.290;-73.1
9(29A)
0.320;-93.7
K(29A)
0.256;-146.2
9(2QA)
0.218;-166.9
J(2TA)
0.291;-166.9
TJ(2A)
0.256;-166.9
(2JQA)
0.320;-125.6
J(2KA)
0.252;-105.0
(QK)(2A)
0.283;50.6
22(4A)
0.250;-341.2
226A
0.190;-435.0
2A(29)
0.293;-238.1
22(QA)
0.321;-176.2
2(34A)
0.204;-455.6
26(3A)
0.167;-414.4
(29)(3A)
0.214;-217.5
2(3QA)
0.194;-290.6
A(234)
0.192;-455.6
(23)(7A)
0.272;-258.8
9A(23)
0.225;-352.5
A(23Q)
0.216;-290.6
2A(34)
0.201;-455.6
2A(36)
0.199;-414.4
2A(38)
0.236;-373.1
2A(3T)
0.225;-331.9
2A(3Q)
0.230;-290.6
2(45A)
0.207;-414.4
27(4A)
0.232;-373.1
(2T)(4A)
0.260;-176.2
2(4KA)
0.299;-249.4
A(246)
0.214;-393.8
(24)(9A)
0.249;-196.9
JA(24)
0.279;-290.6
24(5A)
0.247;-414.4
24(7A)
0.229;-373.1
24(9A)
0.181;-331.9
24(JA)
0.208;-290.6
24(KA)
0.242;-249.4
26(5A)
0.185;-373.1
(29)(5A)
0.235;-176.2
2(5QA)
0.246;-249.4
A(256)
0.178;-373.1
(25)(9A)
0.259;-176.2
JA(25)
0.309;-270.0
25(6A)
0.177;-373.1
25(8A)
0.268;-331.9
25(TA)
0.270;-290.6
25(QA)
0.293;-249.4
(26)(6A)
0.263;-82.5
2(69A)
0.244;-290.6
2J(6A)
0.246;-249.4
(26)(7A)
0.281;-196.9
9A(26)
0.238;-290.6
A(26Q)
0.204;-228.7
2A(67)
0.180;-331.9
2A(69)
0.223;-290.6
2A(6J)
0.231;-249.4
2A(6K)
0.289;-208.1
(29)(7A)
0.227;-135.0
2(7QA)
0.269;-208.1
A(278)
0.231;-290.6
(27)(JA)
0.233;-93.8
KA(27)
0.201;-187.5
2A(79)
0.266;-270.0
2A(7J)
0.225;-228.7
2A(7K)
0.227;-187.5
(2T)(8A)
0.274;-93.8
2(8KA)
0.302;-166.9
A(28T)
0.225;-228.7
(28)(KA)
0.312;-31.9
28(TA)
0.225;-228.7
28(QA)
0.269;-187.5
(29)(9A)
0.312;41.3
2(9QA)
0.245;-166.9
A(29T)
0.241;-208.1
(29)(KA)
0.273;-11.2
29(JA)
0.293;-187.5
29(KA)
0.292;-146.2
2J(TA)
0.292;-166.9
(2T)(JA)
0.298;-31.9
KA(2T)
0.260;-125.6
2A(TQ)
0.246;-146.2
2(JQA)
0.278;-125.6
A(2JQ)
0.267;-125.6
2A(JQ)
0.258;-125.6
2(QKA)
0.241;-84.4
2Q(KA)
0.310;-84.4
33(3A)
0.280;-185.6
(36)(3A)
0.303;-123.7
3(39A)
0.250;-196.9
3J(3A)
0.226;-155.6
(345A)
0.223;-393.8
(349A)
0.172;-311.2
(34KA)
0.260;-228.7
46(3A)
0.209;-373.1
(49)(3A)
0.281;-176.2
4(3QA)
0.272;-249.4
6(35A)
0.219;-352.5
T(35A)
0.224;-270.0
5(36A)
0.289;-352.5
58(3A)
0.264;-311.2
(5J)(3A)
0.280;-114.4
6(36A)
0.248;-196.9
T(36A)
0.252;-249.4
6(37A)
0.259;-311.2
69(3A)
0.283;-270.0
(6Q)(3A)
0.252;-73.1
(379A)
0.277;-249.4
(37KA)
0.293;-166.9
79(3A)
0.262;-249.4
(7Q)(3A)
0.277;-52.5
(38TA)
0.221;-208.1
88(3A)
0.210;-114.4
(8J)(3A)
0.235;-52.5
9(39A)
0.298;-73.1
K(39A)
0.261;-125.6
9(3QA)
0.277;-146.2
J(3TA)
0.323;-146.2
TJ(3A)
0.239;-146.2
(3JQA)
0.244;-105.0
J(3KA)
0.263;-84.4
(QK)(3A)
0.256;71.3
33(5A)
0.223;-279.4
337A
0.226;-373.1
3A(3T)
0.268;-176.2
33(KA)
0.239;-114.4
3(46A)
0.279;-373.1
38(4A)
0.187;-331.9
(3J)(4A)
0.228;-135.0
4A(34)
0.213;-279.4
A(347)
0.254;-352.5
(34)(TA)
0.249;-155.6
QA(34)
0.248;-249.4
345A
0.152;-528.7
347A
0.192;-487.5
349A
0.193;-446.2
34JA
0.179;-405.0
34KA
0.240;-363.7
37(5A)
0.223;-331.9
(3T)(5A)
0.261;-135.0
3(5KA)
0.294;-208.1
A(357)
0.225;-331.9
(35)(TA)
0.271;-135.0
QA(35)
0.212;-228.7
356A
0.204;-487.5
358A
0.190;-446.2
35TA
0.217;-405.0
35QA
0.244;-363.7
(37)(6A)
0.250;-176.2
3(6TA)
0.279;-249.4
3Q(6A)
0.246;-208.1
(36)(8A)
0.276;-155.6
TA(36)
0.249;-249.4
A(36K)
0.212;-187.5
6A(38)
0.252;-290.6
6A(3T)
0.222;-249.4
6A(3Q)
0.255;-208.1
37(7A)
0.236;-155.6
(3T)(7A)
0.262;-93.8
3(7KA)
0.288;-166.9
A(379)
0.302;-249.4
(37)(QA)
0.255;-52.5
7A(38)
0.259;-270.0
7A(3T)
0.266;-228.7
7A(3Q)
0.271;-187.5
38(8A)
0.273;-114.4
(3J)(8A)
0.289;-52.5
8A(38)
0.234;-114.4
A(38J)
0.251;-187.5
388A
0.297;-249.4
38TA
0.247;-343.1
38QA
0.280;-301.9
(3T)(9A)
0.312;-52.5
3(9KA)
0.247;-125.6
A(39J)
0.313;-166.9
399A
0.278;-208.1
39JA
0.293;-301.9
39KA
0.305;-260.6
3Q(TA)
0.298;-125.6
(3T)(QA)
0.257;9.4
TA(3J)
0.206;-146.2
TA(3K)
0.270;-105.0
3(JKA)
0.247;-84.4
A(3JK)
0.314;-84.4
JA(3K)
0.233;-84.4
QA(3Q)
0.300;50.6
3QKA
0.254;-198.7
45(4A)
0.259;-238.1
(48)(4A)
0.277;-41.3
4(4JA)
0.245;-114.4
4K(4A)
0.260;-73.1
(459A)
0.285;-270.0
(45KA)
0.223;-187.5
57(4A)
0.208;-311.2
(5T)(4A)
0.255;-114.4
5(4KA)
0.272;-187.5
(469A)
0.227;-249.4
(46KA)
0.281;-166.9
68(4A)
0.198;-270.0
(6J)(4A)
0.285;-73.1
7(47A)
0.270;-135.0
J(47A)
0.266;-187.5
78(4A)
0.190;-249.4
(7J)(4A)
0.259;-52.5
8(48A)
0.270;-93.7
Q(48A)
0.252;-146.2
(8T)(4A)
0.324;-52.5
8(4KA)
0.306;-125.6
(49QA)
0.234;-125.6
9(4JA)
0.218;-146.2
9K(4A)
0.214;-105.0
TT(4A)
0.268;-11.2
(TK)(4A)
0.246;50.6
J(4QA)
0.247;-84.4
K(4QA)
0.239;-43.1
44(5A)
0.245;-238.1
447A
0.207;-331.9
4A(4T)
0.276;-135.0
44(KA)
0.286;-73.1
4(57A)
0.238;-311.2
49(5A)
0.205;-270.0
(4Q)(5A)
0.340;-73.1
6A(45)
0.277;-331.9
A(459)
0.224;-270.0
(45)(QA)
0.289;-73.1
5A(46)
0.228;-331.9
5A(48)
0.192;-290.6
5A(4T)
0.280;-249.4
5A(4Q)
0.233;-208.1
46(6A)
0.259;-176.2
(49)(6A)
0.265;-114.4
4(6QA)
0.254;-187.5
A(467)
0.239;-290.6
(46)(TA)
0.298;-93.8
QA(46)
0.256;-187.5
467A
0.199;-425.6
469A
0.191;-384.4
46JA
0.232;-343.1
46KA
0.282;-301.9
49(7A)
0.253;-228.7
(4Q)(7A)
0.339;-31.9
8A(47)
0.198;-249.4
A(47J)
0.219;-187.5
477A
0.284;-270.0
479A
0.184;-363.7
47JA
0.218;-322.5
47KA
0.217;-281.2
4T(8A)
0.221;-187.5
(4K)(8A)
0.266;9.4
TA(48)
0.286;-187.5
A(48K)
0.275;-125.6
8A(4T)
0.262;-187.5
8A(4Q)
0.209;-146.2
49(9A)
0.286;-52.5
(4Q)(9A)
0.257;9.4
TA(49)
0.262;-166.9
A(49K)
0.280;-105.0
9A(4J)
0.261;-146.2
9A(4K)
0.235;-105.0
4(TQA)
0.319;-105.0
A(4TJ)
0.262;-125.6
4TTA
0.197;-146.2
4TQA
0.281;-240.0
(4Q)(JA)
0.278;50.6
QA(4J)
0.280;-84.4
4JQA
0.225;-219.4
(4K)(QA)
0.349;91.9
QA(4K)
0.285;-43.1
5(56A)
0.258;-176.2
58(5A)
0.242;-135.0
(5J)(5A)
0.353;61.9
6(56A)
0.260;-155.6
T(56A)
0.287;-208.1
6(57A)
0.240;-270.0
69(5A)
0.244;-228.7
(6Q)(5A)
0.285;-31.9
(579A)
0.220;-208.1
(57KA)
0.269;-125.6
79(5A)
0.228;-208.1
(7Q)(5A)
0.256;-11.2
(58TA)
0.239;-166.9
88(5A)
0.282;-73.1
(8J)(5A)
0.294;-11.2
9(59A)
0.346;-31.9
K(59A)
0.296;-84.4
9(5QA)
0.273;-105.0
J(5TA)
0.215;-105.0
TJ(5A)
0.295;-105.0
(5JQA)
0.265;-63.7
J(5KA)
0.275;-43.1
(QK)(5A)
0.320;112.5
55(7A)
0.299;-155.6
559A
0.230;-249.4
5A(5Q)
0.213;-52.5
(57)(6A)
0.255;-135.0
5(6TA)
0.278;-208.1
5Q(6A)
0.258;-166.9
(56)(8A)
0.231;-114.4
TA(56)
0.257;-208.1
A(56K)
0.229;-146.2
6A(58)
0.288;-249.4
6A(5T)
0.242;-208.1
6A(5Q)
0.267;-166.9
57(7A)
0.303;-114.4
(5T)(7A)
0.253;-52.5
5(7KA)
0.230;-125.6
A(579)
0.197;-208.1
(57)(QA)
0.268;-11.2
7A(58)
0.234;-228.7
7A(5T)
0.225;-187.5
7A(5Q)
0.224;-146.2
58(8A)
0.240;-73.1
(5J)(8A)
0.278;-11.2
8A(58)
0.272;-73.1
A(58J)
0.269;-146.2
588A
0.288;-208.1
58TA
0.233;-301.9
58QA
0.255;-260.6
(5T)(9A)
0.240;-11.2
5(9KA)
0.306;-84.4
A(59J)
0.308;-125.6
599A
0.289;-166.9
59JA
0.217;-260.6
59KA
0.217;-219.4
5Q(TA)
0.249;-84.4
(5T)(QA)
0.256;50.6
TA(5J)
0.323;-105.0
TA(5K)
0.285;-63.7
5(JKA)
0.284;-43.1
A(5JK)
0.245;-43.1
JA(5K)
0.292;-43.1
QA(5Q)
0.332;91.9
5QKA
0.223;-157.5
67(6A)
0.212;-114.4
(6T)(6A)
0.251;82.5
6(6KA)
0.257;9.4
(67TA)
0.272;-166.9
77(6A)
0.273;-93.7
(7T)(6A)
0.337;-31.9
7(6KA)
0.218;-105.0
(68JA)
0.299;-125.6
(89)(6A)
0.263;-31.9
8(6QA)
0.261;-105.0
T(69A)
0.258;-125.6
9(6TA)
0.247;-125.6
9Q(6A)
0.270;-84.4
Q(6TA)
0.309;-63.7
(TQ)(6A)
0.300;71.3
(6JKA)
0.310;-22.5
JK(6A)
0.254;-22.5
K(6KA)
0.317;153.7
668A
0.283;-228.7
6A(6J)
0.297;-31.9
(67)(7A)
0.316;41.3
6(7TA)
0.222;-166.9
6Q(7A)
0.269;-125.6
(67)(9A)
0.217;-52.5
JA(67)
0.293;-146.2
67(8A)
0.261;-208.1
67(TA)
0.221;-166.9
67(QA)
0.282;-125.6
(68)(8A)
0.278;82.5
6(8JA)
0.312;-125.6
6K(8A)
0.258;-84.4
(68)(JA)
0.307;9.4
KA(68)
0.236;-84.4
6A(8T)
0.293;-146.2
6A(8Q)
0.212;-105.0
6(9TA)
0.247;-125.6
6Q(9A)
0.261;-84.4
(69)(JA)
0.312;30.0
KA(69)
0.281;-63.7
6A(9J)
0.256;-105.0
6A(9K)
0.280;-63.7
(6Q)(TA)
0.277;71.3
JA(6T)
0.285;-84.4
6T(JA)
0.306;-84.4
6T(KA)
0.240;-43.1
6Q(JA)
0.307;-43.1
(6J)(KA)
0.284;112.5
6J(KA)
0.265;-22.5
6K(QA)
0.253;-1.9
6A(QK)
0.232;-1.9
(78)(7A)
0.336;82.5
7(7JA)
0.277;9.4
7K(7A)
0.276;50.6
(78QA)
0.245;-84.4
8(7TA)
0.270;-125.6
8Q(7A)
0.221;-84.4
J(79A)
0.255;-84.4
9T(7A)
0.277;-105.0
(9K)(7A)
0.285;91.9
K(7TA)
0.290;-22.5
T(7KA)
0.310;-22.5
JJ(7A)
0.277;91.9
(7QKA)
0.361;18.7
777A
0.287;-73.1
7A(7T)
0.279;-11.2
77(KA)
0.304;50.6
7(8TA)
0.222;-125.6
7Q(8A)
0.257;-84.4
(78)(TA)
0.328;9.4
QA(78)
0.253;-84.4
789A
0.243;-281.2
78JA
0.243;-240.0
78KA
0.231;-198.7
7J(9A)
0.308;-84.4
(79)(TA)
0.317;30.0
QA(79)
0.301;-63.7
79TA
0.281;-240.0
79QA
0.197;-198.7
(7J)(TA)
0.282;71.3
TA(7T)
0.290;50.6
A(7TK)
0.311;-22.5
TA(7Q)
0.280;-43.1
7J(JA)
0.248;91.9
(7J)(QA)
0.255;112.5
JA(7Q)
0.245;-22.5
7Q(QA)
0.357;133.1
7QQA
0.253;-1.9
7KKA
0.298;39.4
8(8JA)
0.289;50.6
8K(8A)
0.286;91.9
(89KA)
0.348;-22.5
9J(8A)
0.259;-63.7
(8TJA)
0.255;-43.1
(TJ)(8A)
0.303;91.9
J(8JA)
0.311;112.5
JQ(8A)
0.270;-1.9
Q(8KA)
0.270;39.4
889A
0.247;-125.6
8A(8Q)
0.273;71.3
(8T)(9A)
0.280;50.6
8(9KA)
0.260;-22.5
A(89J)
0.292;-63.7
899A
0.334;-105.0
89JA
0.310;-198.7
89KA
0.279;-157.5
8Q(TA)
0.266;-22.5
(8T)(QA)
0.281;112.5
TA(8J)
0.301;-43.1
TA(8K)
0.262;-1.9
8(JKA)
0.296;18.7
A(8JK)
0.267;18.7
JA(8K)
0.363;18.7
QA(8Q)
0.305;153.7
8QKA
0.286;-95.6
9T(9A)
0.269;71.3
(9K)(9A)
0.346;268.1
K(9TA)
0.302;18.7
T(9KA)
0.306;18.7
JJ(9A)
0.301;133.1
(9QKA)
0.337;60.0
999A
0.271;50.6
9A(9Q)
0.271;112.5
(9J)(TA)
0.251;112.5
TA(9T)
0.277;91.9
A(9TK)
0.282;18.7
TA(9Q)
0.248;-1.9
9J(JA)
0.349;133.1
(9J)(QA)
0.309;153.8
JA(9Q)
0.254;18.7
9Q(QA)
0.335;174.4
9QQA
0.276;39.4
9KKA
0.354;80.6
T(TKA)
0.303;174.4
JJ(TA)
0.293;153.7
(TQKA)
0.246;80.6
TTTA
0.347;112.5
TA(TK)
0.341;174.4
(TK)(JA)
0.292;195.0
KA(TJ)
0.294;60.0
TA(JK)
0.347;60.0
(TQ)(KA)
0.295;215.6
(TK)(KA)
0.392;371.3
J(JKA)
0.376;215.6
(QK)(JA)
0.311;236.3
JJ(KA)
0.319;215.6
QA(JQ)
0.329;215.6
JQKA
0.327;-33.7
QK(QA)
0.340;256.9
QK(KA)
0.378;277.5
22(24)
0.195;-453.8
22(28)
0.277;-371.2
22(2Q)
0.199;-288.7
24(23)
0.209;-568.1
(23)(27)
0.216;-371.3
2(23T)
0.182;-444.4
2Q(23)
0.213;-403.1
23(25)
0.158;-547.5
2237
0.170;-641.2
22(3T)
0.198;-444.4
23(2K)
0.196;-382.5
2(246)
0.158;-506.2
28(24)
0.200;-465.0
(24)(2J)
0.232;-268.1
2244
0.170;-547.5
22(47)
0.158;-485.6
24(2T)
0.242;-423.8
224Q
0.189;-517.5
26(25)
0.180;-485.6
(25)(29)
0.204;-288.7
2(25Q)
0.276;-361.9
22(56)
0.185;-485.6
25(29)
0.160;-423.8
225J
0.178;-517.5
26(26)
0.216;-330.0
(26)(29)
0.277;-268.1
2(26Q)
0.194;-341.2
22(67)
0.178;-444.4
26(2T)
0.243;-382.5
226Q
0.159;-476.2
28(27)
0.219;-403.1
(27)(2J)
0.255;-206.3
2277
0.208;-423.8
22(7T)
0.212;-361.9
27(2K)
0.223;-300.0
2(28T)
0.218;-341.2
2Q(28)
0.249;-300.0
28(2T)
0.191;-341.2
228Q
0.235;-435.0
2T(29)
0.229;-320.6
(29)(2K)
0.290;-123.7
229J
0.232;-435.0
2T(2T)
0.301;-165.0
(2T)(2K)
0.247;-103.1
22TQ
0.209;-393.8
2Q(2J)
0.207;-238.1
2J(2K)
0.285;-217.5
22QQ
0.258;-217.5
3(234)
0.156;-547.5
36(23)
0.240;-506.2
(23)(39)
0.188;-309.4
3(23Q)
0.229;-382.5
5(234)
0.184;-641.2
9(234)
0.178;-558.8
K(234)
0.161;-476.2
4(237)
0.213;-600.0
49(23)
0.233;-558.8
(23)(4Q)
0.232;-361.9
(2357)
0.212;-579.4
(235J)
0.209;-496.9
(23)(56)
0.238;-465.0
5(239)
0.227;-538.1
5J(23)
0.184;-496.9
(2367)
0.146;-558.8
(236J)
0.167;-476.2
(23)(67)
0.253;-423.8
6(23T)
0.203;-496.9
6Q(23)
0.209;-455.6
9(237)
0.201;-496.9
K(237)
0.231;-414.4
7(23T)
0.257;-476.2
7Q(23)
0.196;-435.0
T(238)
0.174;-455.6
8(239)
0.230;-476.2
8J(23)
0.212;-435.0
(239T)
0.243;-435.0
99(23)
0.203;-320.6
(23)(9Q)
0.286;-258.8
(23TQ)
0.188;-373.1
T(23Q)
0.267;-373.1
Q(23J)
0.219;-352.5
(23)(JK)
0.246;-196.9
QK(23)
0.252;-311.2
23(35)
0.220;-526.9
33(28)
0.228;-465.0
233T
0.201;-558.8
23(3K)
0.266;-361.9
(24)(36)
0.228;-485.6
3(249)
0.170;-558.8
3J(24)
0.214;-517.5
(34)(25)
0.167;-506.2
27(34)
0.182;-600.0
2(34T)
0.188;-538.1
(34)(2K)
0.209;-341.2
34(26)
0.201;-620.6
34(28)
0.179;-579.4
34(2T)
0.217;-538.1
34(2Q)
0.232;-496.9
(25)(35)
0.242;-350.6
3(258)
0.215;-558.8
3T(25)
0.203;-517.5
(25)(3K)
0.229;-320.6
27(35)
0.226;-579.4
2(35T)
0.223;-517.5
(35)(2K)
0.283;-320.6
35(27)
0.225;-579.4
35(29)
0.189;-538.1
35(2J)
0.204;-496.9
35(2K)
0.193;-455.6
37(26)
0.215;-558.8
(26)(3T)
0.247;-361.9
3(26K)
0.250;-435.0
2(368)
0.212;-538.1
(36)(2J)
0.214;-341.2
2K(36)
0.204;-435.0
23(68)
0.233;-538.1
23(6T)
0.162;-496.9
23(6Q)
0.265;-455.6
3(278)
0.203;-517.5
3T(27)
0.210;-476.2
(27)(3K)
0.238;-279.4
29(37)
0.199;-496.9
2(37Q)
0.268;-435.0
23(78)
0.180;-517.5
23(7T)
0.232;-476.2
23(7Q)
0.232;-435.0
3(289)
0.208;-476.2
3J(28)
0.187;-435.0
(38)(29)
0.249;-341.2
2J(38)
0.207;-435.0
38(29)
0.230;-476.2
38(2J)
0.219;-435.0
38(2K)
0.226;-393.8
3T(29)
0.240;-435.0
(29)(3K)
0.257;-238.1
2J(39)
0.204;-414.4
39(2T)
0.205;-435.0
39(2Q)
0.209;-393.8
(2T)(3T)
0.265;-144.4
3(2TK)
0.236;-352.5
2(3TQ)
0.246;-373.1
23(TJ)
0.220;-393.8
23(TK)
0.253;-352.5
(2J)(3K)
0.244;-196.9
2K(3J)
0.186;-331.9
23(JK)
0.217;-331.9
(3Q)(2K)
0.247;-176.2
(2K)(3K)
0.236;-20.6
4(246)
0.189;-465.0
48(24)
0.258;-423.8
(24)(4J)
0.243;-226.9
5(245)
0.168;-465.0
9(245)
0.209;-517.5
K(245)
0.230;-435.0
5(248)
0.259;-538.1
5T(24)
0.225;-496.9
(24)(5K)
0.229;-300.0
9(246)
0.253;-496.9
K(246)
0.215;-414.4
6(249)
0.204;-496.9
6J(24)
0.168;-455.6
(2478)
0.179;-496.9
(247Q)
0.204;-414.4
7(249)
0.203;-476.2
7J(24)
0.216;-435.0
(2489)
0.233;-455.6
(248K)
0.281;-373.1
8T(24)
0.228;-435.0
(24)(8K)
0.234;-238.1
Q(249)
0.233;-373.1
(24)(9J)
0.234;-258.8
T(24T)
0.216;-258.8
T(24J)
0.271;-373.1
TK(24)
0.230;-331.9
(24)(JQ)
0.221;-196.9
QQ(24)
0.275;-176.2
24(45)
0.217;-485.6
44(28)
0.232;-423.8
244T
0.170;-517.5
24(4K)
0.231;-320.6
(25)(47)
0.192;-423.8
4(25T)
0.208;-496.9
4Q(25)
0.192;-455.6
(45)(27)
0.218;-423.8
29(45)
0.208;-517.5
2(45Q)
0.159;-455.6
24(56)
0.233;-579.4
24(58)
0.186;-538.1
24(5T)
0.187;-496.9
24(5Q)
0.245;-455.6
4(267)
0.178;-538.1
49(26)
0.174;-496.9
(26)(4Q)
0.227;-300.0
27(46)
0.192;-538.1
2(46T)
0.192;-476.2
(46)(2K)
0.198;-279.4
46(28)
0.227;-517.5
46(2T)
0.242;-476.2
46(2Q)
0.198;-435.0
(27)(47)
0.236;-247.5
4(27T)
0.208;-455.6
4Q(27)
0.223;-414.4
(47)(29)
0.232;-341.2
2J(47)
0.180;-435.0
47(28)
0.166;-496.9
47(2T)
0.200;-455.6
47(2Q)
0.175;-414.4
(28)(48)
0.247;-206.3
4(28J)
0.180;-414.4
4K(28)
0.200;-373.1
(48)(2J)
0.231;-279.4
2K(48)
0.207;-373.1
24(8T)
0.214;-435.0
24(8Q)
0.270;-393.8
4(29T)
0.170;-414.4
4Q(29)
0.250;-373.1
(49)(2J)
0.305;-258.8
2K(49)
0.191;-352.5
24(9J)
0.262;-393.8
24(9K)
0.236;-352.5
(2T)(4Q)
0.301;-217.5
2J(4T)
0.226;-373.1
4T(2J)
0.233;-373.1
4T(2K)
0.236;-331.9
4Q(2J)
0.192;-331.9
(4J)(2K)
0.233;-176.2
4J(2K)
0.246;-311.2
4K(2Q)
0.256;-290.6
24(QK)
0.194;-290.6
(25)(56)
0.221;-288.7
5(259)
0.171;-361.9
5J(25)
0.253;-320.6
(2567)
0.198;-517.5
(256J)
0.209;-435.0
(25)(67)
0.209;-382.5
6(25T)
0.179;-455.6
6Q(25)
0.193;-414.4
9(257)
0.169;-455.6
K(257)
0.227;-373.1
7(25T)
0.193;-435.0
7Q(25)
0.274;-393.8
T(258)
0.204;-414.4
8(259)
0.241;-435.0
8J(25)
0.241;-393.8
(259T)
0.272;-393.8
99(25)
0.198;-279.4
(25)(9Q)
0.252;-217.5
(25TQ)
0.235;-331.9
T(25Q)
0.247;-331.9
Q(25J)
0.218;-311.2
(25)(JK)
0.232;-155.6
QK(25)
0.202;-270.0
25(57)
0.173;-403.1
55(2T)
0.218;-341.2
255Q
0.213;-435.0
57(26)
0.160;-517.5
(26)(5T)
0.200;-320.6
5(26K)
0.219;-393.8
2(568)
0.194;-496.9
(56)(2J)
0.270;-300.0
2K(56)
0.229;-393.8
25(68)
0.201;-496.9
25(6T)
0.197;-455.6
25(6Q)
0.190;-414.4
5(278)
0.194;-476.2
5T(27)
0.216;-435.0
(27)(5K)
0.202;-238.1
29(57)
0.182;-455.6
2(57Q)
0.239;-393.8
25(78)
0.253;-476.2
25(7T)
0.270;-435.0
25(7Q)
0.239;-393.8
5(289)
0.177;-435.0
5J(28)
0.202;-393.8
(58)(29)
0.222;-300.0
2J(58)
0.191;-393.8
58(29)
0.206;-435.0
58(2J)
0.222;-393.8
58(2K)
0.243;-352.5
5T(29)
0.185;-393.8
(29)(5K)
0.264;-196.9
2J(59)
0.229;-373.1
59(2T)
0.231;-393.8
59(2Q)
0.171;-352.5
(2T)(5T)
0.298;-103.1
5(2TK)
0.254;-311.2
2(5TQ)
0.191;-331.9
25(TJ)
0.204;-352.5
25(TK)
0.214;-311.2
(2J)(5K)
0.238;-155.6
2K(5J)
0.212;-290.6
25(JK)
0.276;-290.6
(5Q)(2K)
0.274;-135.0
(2K)(5K)
0.249;20.6
6(268)
0.258;-341.2
6T(26)
0.223;-300.0
(26)(6K)
0.293;-103.1
T(267)
0.217;-414.4
7(268)
0.204;-455.6
7T(26)
0.203;-414.4
(26)(7K)
0.204;-217.5
J(268)
0.238;-373.1
89(26)
0.194;-414.4
(26)(8Q)
0.245;-217.5
(269J)
0.241;-352.5
(26)(9T)
0.251;-238.1
9(26K)
0.179;-311.2
(26TK)
0.233;-290.6
TQ(26)
0.188;-311.2
K(26J)
0.225;-270.0
Q(26Q)
0.256;-135.0
KK(26)
0.234;-93.7
66(29)
0.248;-320.6
266J
0.200;-414.4
67(27)
0.166;-341.2
(27)(6T)
0.257;-279.4
6(27K)
0.248;-352.5
2(679)
0.189;-435.0
(67)(2Q)
0.215;-238.1
27(68)
0.163;-455.6
27(6T)
0.186;-414.4
27(6Q)
0.250;-373.1
68(28)
0.197;-300.0
(28)(6J)
0.204;-238.1
28(68)
0.234;-300.0
2(68J)
0.240;-373.1
2688
0.201;-435.0
268T
0.180;-528.7
268Q
0.196;-487.5
(29)(6T)
0.235;-238.1
6(29K)
0.253;-311.2
2(69J)
0.215;-352.5
2699
0.234;-393.8
269J
0.205;-487.5
269K
0.207;-446.2
6Q(2T)
0.234;-311.2
(6T)(2Q)
0.237;-176.2
2T(6J)
0.236;-331.9
2T(6K)
0.179;-290.6
6(2JK)
0.178;-270.0
2(6JK)
0.235;-270.0
2J(6K)
0.294;-270.0
2Q(6Q)
0.279;-135.0
26QK
0.216;-384.4
78(27)
0.189;-300.0
(27)(7J)
0.261;-103.1
8(278)
0.241;-279.4
Q(278)
0.220;-331.9
(27)(8T)
0.189;-238.1
8(27K)
0.232;-311.2
(279Q)
0.212;-311.2
9(27J)
0.192;-331.9
9K(27)
0.216;-290.6
TT(27)
0.320;-196.9
(27)(TK)
0.263;-135.0
J(27Q)
0.241;-270.0
K(27Q)
0.283;-228.7
77(28)
0.271;-300.0
277T
0.227;-393.8
27(7K)
0.209;-196.9
(28)(7T)
0.249;-238.1
7(28K)
0.255;-311.2
2(78T)
0.222;-373.1
(78)(2K)
0.223;-176.2
78(2T)
0.266;-373.1
78(2Q)
0.228;-331.9
(29)(79)
0.261;-103.1
7(29Q)
0.256;-311.2
2(79T)
0.238;-352.5
(79)(2K)
0.240;-155.6
79(2J)
0.281;-331.9
79(2K)
0.208;-290.6
7J(2T)
0.226;-311.2
(7T)(2J)
0.270;-176.2
2K(7T)
0.254;-270.0
27(TQ)
0.204;-290.6
7(2JQ)
0.209;-270.0
2(7JQ)
0.249;-270.0
27(JQ)
0.231;-270.0
7(2QK)
0.237;-228.7
7Q(2K)
0.247;-228.7
88(28)
0.339;-123.7
(28)(8J)
0.288;-61.9
9(289)
0.188;-217.5
K(289)
0.185;-270.0
9(28Q)
0.241;-290.6
J(28T)
0.237;-290.6
TJ(28)
0.216;-290.6
(28JQ)
0.255;-249.4
J(28K)
0.230;-228.7
(28)(QK)
0.293;-73.1
88(2T)
0.267;-217.5
288Q
0.206;-311.2
8T(29)
0.209;-331.9
(29)(8K)
0.267;-135.0
2J(89)
0.179;-311.2
89(2T)
0.178;-331.9
89(2Q)
0.297;-290.6
(2T)(8T)
0.233;-41.3
8(2TK)
0.205;-249.4
2(8TQ)
0.250;-270.0
28(TJ)
0.248;-290.6
28(TK)
0.280;-249.4
(2J)(8K)
0.331;-93.8
2K(8J)
0.265;-228.7
28(JK)
0.221;-228.7
(8Q)(2K)
0.208;-73.1
(2K)(8K)
0.285;82.5
9(29J)
0.289;-155.6
9K(29)
0.298;-114.4
TT(29)
0.321;-155.6
(29)(TK)
0.263;-93.8
J(29Q)
0.227;-228.7
K(29Q)
0.243;-187.5
99(2T)
0.243;-176.2
299Q
0.275;-270.0
9J(2T)
0.265;-270.0
(9T)(2J)
0.250;-135.0
2K(9T)
0.217;-228.7
29(TQ)
0.219;-249.4
9(2JQ)
0.221;-228.7
2(9JQ)
0.248;-228.7
29(JQ)
0.303;-228.7
9(2QK)
0.231;-187.5
9Q(2K)
0.252;-187.5
TT(2T)
0.320;0.0
(2T)(TK)
0.243;61.9
J(2TQ)
0.305;-208.1
K(2TQ)
0.323;-166.9
TT(2J)
0.265;-114.4
2TTK
0.222;-208.1
TK(2J)
0.256;-187.5
2TJJ
0.239;-228.7
2TJK
0.249;-322.5
2(TQK)
0.242;-166.9
TK(2K)
0.330;-11.2
(2J)(JK)
0.312;103.1
QK(2J)
0.286;-146.2
2J(JK)
0.279;-31.9
(JQ)(2K)
0.292;-11.2
(2K)(JK)
0.269;144.4
K(2QK)
0.283;30.0
2K(QK)
0.273;30.0
3335
0.224;-506.2
3339
0.191;-423.8
333K
0.233;-341.2
36(34)
0.229;-465.0
(34)(39)
0.197;-268.1
3(34Q)
0.237;-341.2
33(45)
0.190;-485.6
34(38)
0.214;-423.8
334T
0.176;-517.5
33(4K)
0.231;-320.6
(35)(37)
0.232;-288.7
3(35T)
0.236;-361.9
3Q(35)
0.204;-320.6
35(37)
0.242;-423.8
3359
0.154;-517.5
33(5Q)
0.241;-320.6
(36)(37)
0.200;-268.1
3(36T)
0.237;-341.2
3Q(36)
0.230;-300.0
36(38)
0.244;-382.5
336T
0.188;-476.2
33(6K)
0.224;-279.4
(37)(39)
0.277;-206.3
3(37Q)
0.197;-279.4
33(78)
0.240;-361.9
37(3J)
0.245;-300.0
337K
0.271;-393.8
3T(38)
0.215;-300.0
(38)(3K)
0.315;-103.1
338T
0.218;-435.0
33(8K)
0.279;-238.1
(39)(3J)
0.250;-123.7
3399
0.225;-300.0
33(9Q)
0.221;-238.1
(3T)(3J)
0.234;-103.1
33TT
0.201;-258.8
33(TK)
0.221;-196.9
(3J)(3K)
0.267;-41.3
33JK
0.248;-311.2
33(QK)
0.239;-155.6
45(34)
0.195;-465.0
(34)(48)
0.183;-268.1
4(34J)
0.273;-341.2
4K(34)
0.267;-300.0
(3459)
0.241;-496.9
(345K)
0.195;-414.4
57(34)
0.179;-538.1
(34)(5T)
0.245;-341.2
5(34K)
0.251;-414.4
(3469)
0.222;-476.2
(346K)
0.169;-393.8
68(34)
0.204;-496.9
(34)(6J)
0.213;-300.0
7(347)
0.176;-361.9
J(347)
0.219;-414.4
78(34)
0.215;-476.2
(34)(7J)
0.227;-279.4
8(348)
0.226;-320.6
Q(348)
0.214;-373.1
(34)(8T)
0.251;-279.4
8(34K)
0.214;-352.5
(349Q)
0.247;-352.5
9(34J)
0.192;-373.1
9K(34)
0.178;-331.9
TT(34)
0.241;-238.1
(34)(TK)
0.266;-176.2
J(34Q)
0.232;-311.2
K(34Q)
0.255;-270.0
44(35)
0.266;-465.0
3447
0.210;-558.8
34(4T)
0.209;-361.9
44(3K)
0.248;-300.0
4(357)
0.211;-538.1
49(35)
0.168;-496.9
(35)(4Q)
0.215;-300.0
36(45)
0.169;-558.8
3(459)
0.177;-496.9
(45)(3Q)
0.239;-300.0
35(46)
0.214;-558.8
35(48)
0.189;-517.5
35(4T)
0.193;-476.2
35(4Q)
0.241;-435.0
46(36)
0.241;-403.1
(36)(49)
0.182;-341.2
4(36Q)
0.230;-414.4
3(467)
0.194;-517.5
(46)(3T)
0.232;-320.6
3Q(46)
0.209;-414.4
3467
0.220;-652.5
3469
0.191;-611.2
346J
0.215;-570.0
346K
0.183;-528.7
49(37)
0.203;-455.6
(37)(4Q)
0.218;-258.8
38(47)
0.176;-476.2
3(47J)
0.172;-414.4
3477
0.210;-496.9
3479
0.210;-590.6
347J
0.234;-549.4
347K
0.176;-508.1
4T(38)
0.207;-414.4
(38)(4K)
0.252;-217.5
3T(48)
0.229;-414.4
3(48K)
0.239;-352.5
38(4T)
0.196;-414.4
38(4Q)
0.232;-373.1
49(39)
0.244;-279.4
(39)(4Q)
0.253;-217.5
3T(49)
0.219;-393.8
3(49K)
0.279;-331.9
39(4J)
0.202;-373.1
39(4K)
0.187;-331.9
4(3TQ)
0.179;-331.9
3(4TJ)
0.216;-352.5
34TT
0.208;-373.1
34TQ
0.265;-466.9
(3J)(4Q)
0.266;-176.2
3Q(4J)
0.199;-311.2
34JQ
0.225;-446.2
(3Q)(4K)
0.239;-135.0
3Q(4K)
0.258;-270.0
5(356)
0.234;-403.1
58(35)
0.258;-361.9
(35)(5J)
0.279;-165.0
6(356)
0.227;-382.5
T(356)
0.201;-435.0
6(357)
0.179;-496.9
69(35)
0.192;-455.6
(35)(6Q)
0.195;-258.8
(3579)
0.214;-435.0
(357K)
0.197;-352.5
79(35)
0.205;-435.0
(35)(7Q)
0.222;-238.1
(358T)
0.244;-393.8
88(35)
0.235;-300.0
(35)(8J)
0.211;-238.1
9(359)
0.207;-258.8
K(359)
0.220;-311.2
9(35Q)
0.224;-331.9
J(35T)
0.280;-331.9
TJ(35)
0.214;-331.9
(35JQ)
0.224;-290.6
J(35K)
0.247;-270.0
(35)(QK)
0.319;-114.4
55(37)
0.202;-382.5
3559
0.214;-476.2
35(5Q)
0.200;-279.4
(36)(57)
0.218;-361.9
5(36T)
0.204;-435.0
5Q(36)
0.212;-393.8
(56)(38)
0.246;-341.2
3T(56)
0.272;-435.0
3(56K)
0.240;-373.1
36(58)
0.158;-476.2
36(5T)
0.210;-435.0
36(5Q)
0.217;-393.8
57(37)
0.218;-341.2
(37)(5T)
0.261;-279.4
5(37K)
0.232;-352.5
3(579)
0.218;-435.0
(57)(3Q)
0.219;-238.1
37(58)
0.218;-455.6
37(5T)
0.205;-414.4
37(5Q)
0.180;-373.1
58(38)
0.231;-300.0
(38)(5J)
0.206;-238.1
38(58)
0.231;-300.0
3(58J)
0.232;-373.1
3588
0.226;-435.0
358T
0.164;-528.7
358Q
0.155;-487.5
(39)(5T)
0.260;-238.1
5(39K)
0.255;-311.2
3(59J)
0.233;-352.5
3599
0.182;-393.8
359J
0.245;-487.5
359K
0.248;-446.2
5Q(3T)
0.206;-311.2
(5T)(3Q)
0.222;-176.2
3T(5J)
0.255;-331.9
3T(5K)
0.266;-290.6
5(3JK)
0.198;-270.0
3(5JK)
0.237;-270.0
3J(5K)
0.250;-270.0
3Q(5Q)
0.292;-135.0
35QK
0.260;-384.4
67(36)
0.216;-341.2
(36)(6T)
0.261;-144.4
6(36K)
0.206;-217.5
(367T)
0.218;-393.8
77(36)
0.250;-320.6
(36)(7T)
0.302;-258.8
7(36K)
0.249;-331.9
(368J)
0.175;-352.5
(36)(89)
0.250;-258.8
8(36Q)
0.269;-331.9
T(369)
0.190;-352.5
9(36T)
0.202;-352.5
9Q(36)
0.216;-311.2
Q(36T)
0.254;-290.6
(36)(TQ)
0.306;-155.6
(36JK)
0.219;-249.4
JK(36)
0.293;-249.4
K(36K)
0.275;-73.1
3668
0.185;-455.6
36(6J)
0.241;-258.8
(37)(67)
0.238;-185.6
6(37T)
0.234;-393.8
6Q(37)
0.273;-352.5
(67)(39)
0.225;-279.4
3J(67)
0.178;-373.1
67(38)
0.226;-435.0
67(3T)
0.222;-393.8
67(3Q)
0.197;-352.5
(38)(68)
0.291;-144.4
6(38J)
0.243;-352.5
6K(38)
0.257;-311.2
(68)(3J)
0.270;-217.5
3K(68)
0.244;-311.2
36(8T)
0.204;-373.1
36(8Q)
0.263;-331.9
6(39T)
0.210;-352.5
6Q(39)
0.237;-311.2
(69)(3J)
0.305;-196.9
3K(69)
0.231;-290.6
36(9J)
0.211;-331.9
36(9K)
0.268;-290.6
(3T)(6Q)
0.276;-155.6
3J(6T)
0.204;-311.2
6T(3J)
0.182;-311.2
6T(3K)
0.276;-270.0
6Q(3J)
0.222;-270.0
(6J)(3K)
0.286;-114.4
6J(3K)
0.245;-249.4
6K(3Q)
0.207;-228.7
36(QK)
0.249;-228.7
(37)(78)
0.272;-144.4
7(37J)
0.284;-217.5
7K(37)
0.209;-176.2
(378Q)
0.196;-311.2
8(37T)
0.257;-352.5
8Q(37)
0.194;-311.2
J(379)
0.198;-311.2
9T(37)
0.249;-331.9
(37)(9K)
0.284;-135.0
K(37T)
0.201;-249.4
T(37K)
0.277;-249.4
JJ(37)
0.276;-135.0
(37QK)
0.274;-208.1
3777
0.267;-300.0
37(7T)
0.256;-238.1
77(3K)
0.288;-176.2
7(38T)
0.245;-352.5
7Q(38)
0.241;-311.2
(78)(3T)
0.200;-217.5
3Q(78)
0.264;-311.2
3789
0.177;-508.1
378J
0.217;-466.9
378K
0.211;-425.6
7J(39)
0.247;-311.2
(79)(3T)
0.232;-196.9
3Q(79)
0.221;-290.6
379T
0.223;-466.9
379Q
0.251;-425.6
(3T)(7J)
0.222;-155.6
3T(7T)
0.246;-176.2
3(7TK)
0.249;-249.4
3T(7Q)
0.226;-270.0
7J(3J)
0.229;-135.0
(7J)(3Q)
0.237;-114.4
3J(7Q)
0.208;-249.4
7Q(3Q)
0.316;-93.7
37QQ
0.226;-228.7
37KK
0.292;-187.5
8(38J)
0.283;-176.2
8K(38)
0.271;-135.0
(389K)
0.260;-249.4
9J(38)
0.277;-290.6
(38TJ)
0.228;-270.0
(38)(TJ)
0.285;-135.0
J(38J)
0.231;-114.4
JQ(38)
0.212;-228.7
Q(38K)
0.197;-187.5
3889
0.255;-352.5
38(8Q)
0.297;-155.6
(39)(8T)
0.276;-176.2
8(39K)
0.231;-249.4
3(89J)
0.187;-290.6
3899
0.185;-331.9
389J
0.199;-425.6
389K
0.205;-384.4
8Q(3T)
0.292;-249.4
(8T)(3Q)
0.330;-114.4
3T(8J)
0.246;-270.0
3T(8K)
0.208;-228.7
8(3JK)
0.250;-208.1
3(8JK)
0.213;-208.1
3J(8K)
0.308;-208.1
3Q(8Q)
0.244;-73.1
38QK
0.277;-322.5
9T(39)
0.306;-155.6
(39)(9K)
0.325;41.3
K(39T)
0.207;-208.1
T(39K)
0.196;-208.1
JJ(39)
0.270;-93.7
(39QK)
0.223;-166.9
3999
0.230;-176.2
39(9Q)
0.293;-114.4
(3T)(9J)
0.259;-114.4
3T(9T)
0.279;-135.0
3(9TK)
0.230;-208.1
3T(9Q)
0.217;-228.7
9J(3J)
0.321;-93.7
(9J)(3Q)
0.260;-73.1
3J(9Q)
0.258;-208.1
9Q(3Q)
0.304;-52.5
39QQ
0.309;-187.5
39KK
0.275;-146.2
T(3TK)
0.276;-52.5
JJ(3T)
0.248;-73.1
(3TQK)
0.240;-146.2
3TTT
0.282;-114.4
3T(TK)
0.287;-52.5
(3J)(TK)
0.291;-31.9
3K(TJ)
0.211;-166.9
3T(JK)
0.265;-166.9
(TQ)(3K)
0.224;-11.2
(3K)(TK)
0.354;144.4
J(3JK)
0.264;-11.2
(3J)(QK)
0.277;9.4
JJ(3K)
0.268;-11.2
3Q(JQ)
0.288;-11.2
3JQK
0.257;-260.6
QK(3Q)
0.244;30.0
QK(3K)
0.286;50.6
44(46)
0.250;-288.7
44(4T)
0.247;-206.2
(45)(45)
0.310;-153.8
4(458)
0.242;-361.9
4T(45)
0.256;-320.6
(45)(4K)
0.301;-123.7
4457
0.240;-517.5
44(5T)
0.231;-320.6
45(4K)
0.249;-258.8
4(468)
0.243;-341.2
4T(46)
0.254;-300.0
(46)(4K)
0.262;-103.1
4468
0.207;-476.2
44(6J)
0.233;-279.4
(47)(47)
0.325;-71.2
4(47T)
0.249;-279.4
4Q(47)
0.265;-238.1
47(49)
0.204;-300.0
447J
0.253;-393.8
48(48)
0.269;-165.0
(48)(4J)
0.288;-103.1
4488
0.222;-300.0
44(8J)
0.239;-238.1
(49)(49)
0.252;11.2
4(49Q)
0.267;-196.9
44(9T)
0.246;-238.1
49(4K)
0.263;-176.2
4(4TQ)
0.265;-176.2
44(TJ)
0.268;-196.9
(4J)(4J)
0.316;93.8
44JJ
0.238;-176.2
4Q(4Q)
0.325;0.0
(4K)(4K)
0.337;176.2
(45)(57)
0.243;-226.9
5(45T)
0.249;-300.0
5Q(45)
0.272;-258.8
8(456)
0.229;-455.6
Q(456)
0.254;-373.1
(45)(68)
0.224;-320.6
6(45J)
0.251;-393.8
6K(45)
0.222;-352.5
(457J)
0.179;-373.1
(45)(78)
0.227;-300.0
7(45J)
0.215;-373.1
7K(45)
0.198;-331.9
(458Q)
0.199;-331.9
8(45T)
0.258;-373.1
8Q(45)
0.217;-331.9
J(459)
0.231;-331.9
9T(45)
0.246;-352.5
(45)(9K)
0.209;-155.6
K(45T)
0.183;-270.0
T(45K)
0.233;-270.0
JJ(45)
0.330;-155.6
(45QK)
0.270;-228.7
4555
0.160;-403.1
45(58)
0.233;-341.2
55(4J)
0.237;-279.4
455K
0.204;-373.1
58(46)
0.186;-455.6
(46)(5J)
0.220;-258.8
46(56)
0.244;-361.9
4(569)
0.213;-435.0
(56)(4Q)
0.223;-238.1
46(57)
0.231;-476.2
46(59)
0.191;-435.0
46(5J)
0.195;-393.8
46(5K)
0.239;-352.5
5(479)
0.177;-414.4
5J(47)
0.243;-373.1
(57)(48)
0.198;-300.0
4T(57)
0.211;-393.8
4(57K)
0.243;-331.9
47(59)
0.201;-414.4
47(5J)
0.206;-373.1
47(5K)
0.280;-331.9
5(48T)
0.206;-373.1
5Q(48)
0.224;-331.9
(58)(4T)
0.250;-238.1
4Q(58)
0.210;-331.9
4589
0.166;-528.7
458J
0.203;-487.5
458K
0.219;-446.2
5J(49)
0.269;-331.9
(59)(4T)
0.210;-217.5
4Q(59)
0.233;-311.2
459T
0.218;-487.5
459Q
0.220;-446.2
(4T)(5J)
0.252;-176.2
4T(5T)
0.231;-196.9
4(5TK)
0.209;-270.0
4T(5Q)
0.198;-290.6
5J(4J)
0.251;-155.6
(5J)(4Q)
0.284;-135.0
4J(5Q)
0.269;-270.0
5Q(4Q)
0.266;-114.4
45QQ
0.233;-249.4
45KK
0.226;-208.1
6(469)
0.242;-279.4
6J(46)
0.291;-238.1
(4678)
0.231;-414.4
(467Q)
0.203;-331.9
7(469)
0.193;-393.8
7J(46)
0.241;-352.5
(4689)
0.223;-373.1
(468K)
0.259;-290.6
8T(46)
0.215;-352.5
(46)(8K)
0.245;-155.6
Q(469)
0.218;-290.6
(46)(9J)
0.209;-176.2
T(46T)
0.238;-176.2
T(46J)
0.229;-290.6
TK(46)
0.254;-249.4
(46)(JQ)
0.261;-114.4
QQ(46)
0.266;-93.7
46(67)
0.235;-320.6
66(4T)
0.241;-258.8
466Q
0.285;-352.5
68(47)
0.248;-414.4
(47)(6J)
0.197;-217.5
47(67)
0.223;-300.0
4(67T)
0.165;-373.1
(67)(4K)
0.199;-176.2
67(49)
0.206;-393.8
67(4J)
0.252;-352.5
67(4K)
0.226;-311.2
69(48)
0.247;-373.1
(48)(6Q)
0.252;-176.2
49(68)
0.249;-373.1
4(68Q)
0.252;-311.2
46(89)
0.181;-373.1
46(8J)
0.260;-331.9
46(8K)
0.250;-290.6
(49)(6J)
0.243;-176.2
49(69)
0.245;-217.5
4(69Q)
0.193;-290.6
46(9T)
0.219;-331.9
46(9Q)
0.215;-290.6
6(4TJ)
0.219;-290.6
6K(4T)
0.243;-249.4
(6T)(4K)
0.239;-114.4
6T(4Q)
0.198;-270.0
(4J)(6J)
0.276;0.0
4J(6J)
0.237;-135.0
6J(4Q)
0.214;-249.4
(4Q)(6Q)
0.324;41.3
4K(6Q)
0.191;-208.1
4K(6K)
0.273;-52.5
79(47)
0.253;-238.1
(47)(7Q)
0.273;-41.3
(478T)
0.225;-331.9
88(47)
0.181;-238.1
(47)(8J)
0.217;-176.2
9(479)
0.260;-196.9
K(479)
0.271;-249.4
9(47Q)
0.210;-270.0
J(47T)
0.256;-270.0
TJ(47)
0.197;-270.0
(47JQ)
0.260;-228.7
J(47K)
0.215;-208.1
(47)(QK)
0.262;-52.5
77(49)
0.205;-238.1
477J
0.182;-331.9
78(48)
0.215;-238.1
(48)(7J)
0.236;-176.2
48(78)
0.286;-238.1
4(78J)
0.255;-311.2
4788
0.256;-373.1
478T
0.203;-466.9
478Q
0.226;-425.6
(49)(7T)
0.231;-176.2
7(49K)
0.231;-249.4
4(79J)
0.217;-290.6
4799
0.219;-331.9
479J
0.210;-425.6
479K
0.267;-384.4
7Q(4T)
0.294;-249.4
(7T)(4Q)
0.239;-114.4
4T(7J)
0.265;-270.0
4T(7K)
0.301;-228.7
7(4JK)
0.238;-208.1
4(7JK)
0.263;-208.1
4J(7K)
0.258;-208.1
4Q(7Q)
0.312;-73.1
47QK
0.247;-322.5
89(48)
0.260;-196.9
(48)(8Q)
0.295;0.0
(489J)
0.241;-270.0
(48)(9T)
0.212;-155.6
9(48K)
0.230;-228.7
(48TK)
0.277;-208.1
TQ(48)
0.193;-228.7
K(48J)
0.245;-187.5
Q(48Q)
0.269;-52.5
KK(48)
0.308;-11.2
88(4J)
0.278;-155.6
488K
0.228;-249.4
8J(49)
0.280;-270.0
(89)(4T)
0.310;-155.6
4Q(89)
0.213;-249.4
489T
0.194;-425.6
489Q
0.198;-384.4
(4T)(8J)
0.293;-114.4
4T(8T)
0.247;-135.0
4(8TK)
0.215;-208.1
4T(8Q)
0.255;-228.7
8J(4J)
0.273;-93.7
(8J)(4Q)
0.248;-73.1
4J(8Q)
0.241;-208.1
8Q(4Q)
0.255;-52.5
48QQ
0.214;-187.5
48KK
0.239;-146.2
9(49Q)
0.249;-93.7
J(49T)
0.265;-228.7
TJ(49)
0.233;-228.7
(49JQ)
0.284;-187.5
J(49K)
0.229;-166.9
(49)(QK)
0.234;-11.2
99(4J)
0.226;-114.4
499K
0.251;-208.1
9Q(4T)
0.299;-208.1
(9T)(4Q)
0.237;-73.1
4T(9J)
0.241;-228.7
4T(9K)
0.269;-187.5
9(4JK)
0.261;-166.9
4(9JK)
0.257;-166.9
4J(9K)
0.254;-166.9
4Q(9Q)
0.299;-31.9
49QK
0.229;-281.2
TJ(4T)
0.220;-73.1
(4TJQ)
0.244;-166.9
J(4TK)
0.279;-146.2
(4T)(QK)
0.288;9.4
TT(4Q)
0.260;-52.5
T(4JQ)
0.208;-166.9
4(TJQ)
0.233;-166.9
4T(JQ)
0.233;-166.9
T(4QK)
0.319;-125.6
TQ(4K)
0.248;-125.6
JJ(4J)
0.308;103.1
(4JQK)
0.235;-105.0
4JJJ
0.279;-31.9
JQ(4Q)
0.306;9.4
4JQQ
0.262;-125.6
4JKK
0.252;-84.4
QQ(4K)
0.253;50.6
4KKK
0.300;91.9
55(59)
0.219;-165.0
55(5K)
0.244;-82.5
(56)(58)
0.268;-165.0
5(56J)
0.236;-238.1
5K(56)
0.251;-196.9
56(59)
0.183;-279.4
556J
0.187;-373.1
57(57)
0.309;-165.0
(57)(5T)
0.299;-103.1
5(57K)
0.206;-176.2
55(79)
0.264;-258.8
57(5Q)
0.202;-196.9
5(589)
0.284;-238.1
5J(58)
0.282;-196.9
58(59)
0.199;-238.1
558J
0.264;-331.9
59(59)
0.251;-82.5
(59)(5Q)
0.273;-20.6
559T
0.235;-331.9
55(9K)
0.266;-135.0
(5T)(5Q)
0.313;0.0
55TJ
0.267;-290.6
5J(5J)
0.290;0.0
5J(5Q)
0.232;-114.4
5(5QK)
0.250;-73.1
5K(5K)
0.281;82.5
68(56)
0.226;-279.4
(56)(6J)
0.228;-82.5
7(567)
0.279;-279.4
J(567)
0.249;-331.9
78(56)
0.204;-393.8
(56)(7J)
0.235;-196.9
8(568)
0.257;-238.1
Q(568)
0.239;-290.6
(56)(8T)
0.249;-196.9
8(56K)
0.244;-270.0
(569Q)
0.279;-270.0
9(56J)
0.253;-290.6
9K(56)
0.275;-249.4
TT(56)
0.249;-155.6
(56)(TK)
0.328;-93.8
J(56Q)
0.278;-228.7
K(56Q)
0.259;-187.5
66(57)
0.250;-300.0
5669
0.213;-393.8
56(6Q)
0.199;-196.9
(57)(68)
0.297;-258.8
6(57J)
0.251;-331.9
6K(57)
0.230;-290.6
(67)(5T)
0.301;-217.5
5Q(67)
0.230;-311.2
5678
0.170;-528.7
567T
0.206;-487.5
567Q
0.158;-446.2
(58)(69)
0.223;-217.5
6(58Q)
0.270;-290.6
5(689)
0.215;-352.5
(68)(5Q)
0.259;-155.6
58(69)
0.247;-352.5
58(6J)
0.244;-311.2
58(6K)
0.275;-270.0
6(59J)
0.245;-290.6
6K(59)
0.211;-249.4
(69)(5Q)
0.279;-135.0
59(6T)
0.191;-311.2
59(6Q)
0.210;-270.0
6T(5T)
0.250;-155.6
(5T)(6K)
0.272;-93.8
5Q(6T)
0.210;-249.4
56TJ
0.211;-405.0
56TK
0.219;-363.7
6K(5J)
0.235;-208.1
56JJ
0.300;-249.4
56JK
0.182;-343.1
5(6QK)
0.189;-187.5
6K(5K)
0.308;-31.9
(57)(79)
0.234;-82.5
7(57Q)
0.301;-155.6
9(578)
0.217;-331.9
K(578)
0.245;-249.4
8(57J)
0.276;-290.6
8K(57)
0.234;-249.4
(579K)
0.218;-228.7
9J(57)
0.291;-270.0
(57TJ)
0.230;-249.4
(57)(TJ)
0.218;-114.4
J(57J)
0.326;-93.7
JQ(57)
0.273;-208.1
Q(57K)
0.273;-166.9
5778
0.250;-373.1
57(7J)
0.252;-176.2
(58)(78)
0.221;-82.5
7(58J)
0.280;-290.6
7K(58)
0.251;-249.4
(78)(5J)
0.312;-155.6
5K(78)
0.261;-249.4
57(8T)
0.223;-311.2
57(8Q)
0.194;-270.0
7(59T)
0.225;-290.6
7Q(59)
0.235;-249.4
(79)(5J)
0.313;-135.0
5K(79)
0.186;-228.7
57(9J)
0.252;-270.0
57(9K)
0.200;-228.7
(5T)(7Q)
0.293;-93.8
5J(7T)
0.246;-249.4
7T(5J)
0.293;-249.4
7T(5K)
0.214;-208.1
7Q(5J)
0.210;-208.1
(7J)(5K)
0.216;-52.5
7J(5K)
0.250;-187.5
7K(5Q)
0.274;-166.9
57(QK)
0.278;-166.9
(58)(89)
0.290;-41.3
8(58Q)
0.299;-114.4
T(589)
0.289;-270.0
9(58T)
0.256;-270.0
9Q(58)
0.259;-228.7
Q(58T)
0.287;-208.1
(58)(TQ)
0.322;-73.1
(58JK)
0.252;-166.9
JK(58)
0.315;-166.9
K(58K)
0.311;9.4
588T
0.239;-290.6
58(8K)
0.258;-93.7
(59)(8J)
0.278;-114.4
59(89)
0.259;-155.6
5(89Q)
0.320;-228.7
58(9T)
0.265;-270.0
58(9Q)
0.274;-228.7
8(5TJ)
0.229;-228.7
8K(5T)
0.225;-187.5
(8T)(5K)
0.264;-52.5
8T(5Q)
0.242;-208.1
(5J)(8J)
0.259;61.9
5J(8J)
0.289;-73.1
8J(5Q)
0.219;-187.5
(5Q)(8Q)
0.335;103.1
5K(8Q)
0.235;-146.2
5K(8K)
0.325;9.4
9J(59)
0.288;-93.7
(59TJ)
0.265;-208.1
(59)(TJ)
0.271;-73.1
J(59J)
0.258;-52.5
JQ(59)
0.261;-166.9
Q(59K)
0.287;-125.6
599T
0.234;-249.4
59(9K)
0.301;-52.5
(5T)(9Q)
0.249;-52.5
5J(9T)
0.288;-208.1
9T(5J)
0.257;-208.1
9T(5K)
0.224;-166.9
9Q(5J)
0.265;-166.9
(9J)(5K)
0.281;-11.2
9J(5K)
0.226;-146.2
9K(5Q)
0.256;-125.6
59(QK)
0.254;-125.6
(5T)(TJ)
0.272;82.5
J(5TJ)
0.264;-31.9
JQ(5T)
0.240;-146.2
Q(5TK)
0.221;-105.0
5TTJ
0.242;-187.5
TJ(5J)
0.313;-31.9
(TJ)(5Q)
0.287;-11.2
5J(TQ)
0.257;-146.2
TQ(5Q)
0.251;9.4
5TQQ
0.199;-125.6
5TKK
0.299;-84.4
Q(5JQ)
0.273;30.0
KK(5J)
0.299;71.3
(5Q)(JQ)
0.299;165.0
5K(JQ)
0.275;-84.4
5K(JK)
0.258;71.3
5QQQ
0.294;50.6
KK(5K)
0.308;247.5
6669
0.265;-238.1
666K
0.234;-155.6
69(67)
0.270;-217.5
(67)(6Q)
0.322;-20.6
6678
0.175;-373.1
66(7J)
0.197;-176.2
(68)(68)
0.295;52.5
6(68J)
0.245;-155.6
6K(68)
0.300;-114.4
68(6J)
0.205;-155.6
668K
0.211;-249.4
6J(69)
0.307;-135.0
69(6T)
0.259;-155.6
669Q
0.274;-249.4
6J(6T)
0.242;-114.4
6T(6J)
0.235;-114.4
66TK
0.271;-208.1
6K(6J)
0.246;-52.5
(6Q)(6Q)
0.273;217.5
66QK
0.242;-166.9
7(679)
0.265;-196.9
7J(67)
0.280;-155.6
(6789)
0.229;-311.2
(678K)
0.299;-228.7
8T(67)
0.204;-290.6
(67)(8K)
0.229;-93.8
Q(679)
0.257;-228.7
(67)(9J)
0.258;-114.4
T(67T)
0.238;-114.4
T(67J)
0.251;-228.7
TK(67)
0.225;-187.5
(67)(JQ)
0.227;-52.5
QQ(67)
0.296;-31.9
67(78)
0.205;-217.5
77(6J)
0.266;-155.6
677K
0.231;-249.4
7T(68)
0.189;-290.6
(68)(7K)
0.223;-93.8
6T(78)
0.229;-290.6
6(78K)
0.244;-228.7
68(7T)
0.252;-290.6
68(7Q)
0.225;-249.4
79(69)
0.273;-155.6
(69)(7Q)
0.239;-93.8
6T(79)
0.240;-270.0
6(79K)
0.284;-208.1
69(7J)
0.186;-249.4
69(7K)
0.278;-208.1
7(6TQ)
0.237;-208.1
6(7TJ)
0.263;-228.7
67TT
0.267;-249.4
67TQ
0.267;-343.1
(6J)(7Q)
0.272;-52.5
6Q(7J)
0.220;-187.5
67JQ
0.265;-322.5
(6Q)(7K)
0.329;-11.2
6Q(7K)
0.257;-146.2
8(689)
0.294;-155.6
8J(68)
0.278;-114.4
(689T)
0.281;-249.4
99(68)
0.256;-135.0
(68)(9Q)
0.269;-73.1
(68TQ)
0.239;-187.5
T(68Q)
0.195;-187.5
Q(68J)
0.281;-166.9
(68)(JK)
0.291;-11.2
QK(68)
0.252;-125.6
68(8T)
0.258;-135.0
88(6K)
0.247;-73.1
8(69J)
0.272;-228.7
8K(69)
0.281;-187.5
(89)(6Q)
0.241;-73.1
69(8T)
0.274;-249.4
69(8Q)
0.225;-208.1
8T(6T)
0.263;-93.7
(6T)(8K)
0.221;-31.9
6Q(8T)
0.258;-187.5
68TJ
0.226;-343.1
68TK
0.234;-301.9
8K(6J)
0.222;-146.2
68JJ
0.267;-187.5
68JK
0.264;-281.2
6(8QK)
0.299;-125.6
8K(6K)
0.347;30.0
(69)(9J)
0.282;61.9
T(69T)
0.250;-73.1
T(69J)
0.269;-187.5
TK(69)
0.234;-146.2
(69)(JQ)
0.302;-11.2
QQ(69)
0.288;9.4
69(9T)
0.283;-93.7
99(6K)
0.286;-31.9
9(6TQ)
0.267;-166.9
6(9TJ)
0.218;-187.5
69TT
0.220;-208.1
69TQ
0.226;-301.9
(6J)(9Q)
0.309;-11.2
6Q(9J)
0.245;-146.2
69JQ
0.266;-281.2
(6Q)(9K)
0.229;30.0
6Q(9K)
0.240;-105.0
T(6TJ)
0.325;-31.9
TK(6T)
0.332;9.4
(6T)(JQ)
0.265;9.4
QQ(6T)
0.246;30.0
6T(TJ)
0.274;-31.9
(6J)(TJ)
0.308;123.7
6J(TJ)
0.244;-11.2
TJ(6Q)
0.316;-125.6
(6Q)(TQ)
0.358;165.0
6K(TQ)
0.261;-84.4
6K(TK)
0.290;71.3
JK(6J)
0.315;50.6
K(6JK)
0.330;91.9
6JJK
0.288;-84.4
6(JQK)
0.294;-63.7
JK(6K)
0.286;91.9
KK(6Q)
0.337;112.5
6QKK
0.282;-22.5
77(7T)
0.261;-20.6
(78)(78)
0.286;93.8
7(78J)
0.246;-114.4
7K(78)
0.276;-73.1
78(7J)
0.238;-114.4
778K
0.242;-208.1
7J(79)
0.261;-93.7
79(7T)
0.275;-114.4
779Q
0.250;-208.1
7J(7T)
0.292;-73.1
7T(7J)
0.247;-73.1
77TK
0.236;-166.9
7K(7J)
0.274;-11.2
(7Q)(7Q)
0.320;258.8
77QK
0.235;-125.6
8(78T)
0.324;-114.4
8Q(78)
0.276;-73.1
J(789)
0.261;-208.1
9T(78)
0.277;-228.7
(78)(9K)
0.263;-31.9
K(78T)
0.233;-146.2
T(78K)
0.243;-146.2
JJ(78)
0.251;-31.9
(78QK)
0.259;-105.0
7888
0.237;-155.6
78(8J)
0.228;-93.7
(79)(89)
0.353;20.6
8(79Q)
0.224;-187.5
7(89T)
0.229;-228.7
(89)(7K)
0.282;-31.9
89(7J)
0.255;-208.1
89(7K)
0.256;-166.9
8J(7T)
0.304;-187.5
(8T)(7J)
0.295;-52.5
7K(8T)
0.269;-146.2
78(TQ)
0.231;-166.9
8(7JQ)
0.301;-146.2
7(8JQ)
0.236;-146.2
78(JQ)
0.259;-146.2
8(7QK)
0.278;-105.0
8Q(7K)
0.222;-105.0
99(79)
0.288;41.2
(79)(9Q)
0.328;103.1
(79TQ)
0.257;-146.2
T(79Q)
0.261;-146.2
Q(79J)
0.240;-125.6
(79)(JK)
0.276;30.0
QK(79)
0.243;-84.4
79(9J)
0.232;-52.5
(7T)(9T)
0.268;82.5
9(7TK)
0.306;-125.6
7(9TQ)
0.313;-146.2
79(TJ)
0.270;-166.9
79(TK)
0.268;-125.6
(7J)(9K)
0.353;30.0
7K(9J)
0.285;-105.0
79(JK)
0.286;-105.0
(9Q)(7K)
0.281;50.6
(7K)(9K)
0.363;206.3
T(7TQ)
0.330;9.4
Q(7TJ)
0.247;-105.0
(7T)(JK)
0.313;50.6
QK(7T)
0.334;-63.7
7T(TQ)
0.273;9.4
(7J)(TQ)
0.224;30.0
7Q(TJ)
0.306;-105.0
7TJQ
0.219;-240.0
(7Q)(TK)
0.330;71.3
7Q(TK)
0.261;-63.7
J(7JQ)
0.317;50.6
K(7JQ)
0.295;-43.1
JJ(7Q)
0.333;50.6
J(7QK)
0.268;-43.1
JQ(7K)
0.293;-43.1
QQ(7Q)
0.409;226.9
7Q(QK)
0.264;112.5
8888
0.319;0.0
888Q
0.301;-52.5
8(89J)
0.284;-52.5
8K(89)
0.289;-11.2
89(8Q)
0.291;-31.9
8(8TJ)
0.302;-31.9
8K(8T)
0.341;9.4
8T(8K)
0.277;9.4
8(8JK)
0.330;30.0
88(JK)
0.318;30.0
8Q(8K)
0.265;50.6
(89)(9T)
0.311;82.5
9(89K)
0.302;9.4
(89TK)
0.232;-105.0
TQ(89)
0.281;-125.6
K(89J)
0.299;-84.4
Q(89Q)
0.347;50.6
KK(89)
0.338;91.9
99(8Q)
0.220;-11.2
9(8TJ)
0.230;-146.2
9K(8T)
0.275;-105.0
(9T)(8K)
0.300;30.0
9T(8Q)
0.241;-125.6
(8J)(9J)
0.279;144.4
8J(9J)
0.341;9.4
9J(8Q)
0.251;-105.0
(8Q)(9Q)
0.321;185.6
8K(9Q)
0.273;-63.7
8K(9K)
0.372;91.9
TQ(8T)
0.285;30.0
K(8TJ)
0.218;-63.7
Q(8TQ)
0.299;71.3
KK(8T)
0.355;112.5
