AAAA
0.278;-7160.0
5AAA
0.253;-17420.0
9AAA
0.282;-14780.0
KAAA
0.310;-12140.0
4A(2A)
0.224;-26000.0
(2A)(7A)
0.250;-19700.0
A(2TA)
0.222;-22040.0
QA(2A)
0.207;-20720.0
2A(4A)
0.193;-26000.0
26AA
0.171;-29000.0
AA(29)
0.198;-22700.0
2A(QA)
0.227;-20720.0
A(34A)
0.201;-25340.0
6A(3A)
0.196;-24020.0
(3A)(9A)
0.307;-17720.0
A(3QA)
0.204;-20060.0
AA(34)
0.210;-25340.0
3A(7A)
0.232;-23360.0
39AA
0.183;-26360.0
AA(3Q)
0.239;-20060.0
(4A)(5A)
0.217;-19700.0
A(48A)
0.207;-22040.0
TA(4A)
0.236;-20720.0
(4A)(KA)
0.278;-14420.0
46AA
0.145;-27680.0
AA(49)
0.266;-21380.0
4A(QA)
0.205;-19400.0
A(56A)
0.197;-22700.0
8A(5A)
0.207;-21380.0
(5A)(JA)
0.261;-15080.0
55AA
0.235;-23360.0
AA(58)
0.231;-21380.0
5A(JA)
0.274;-19400.0
5KAA
0.202;-22400.0
8A(6A)
0.201;-20720.0
(6A)(JA)
0.256;-14420.0
66AA
0.203;-22040.0
AA(69)
0.230;-20060.0
6A(QA)
0.230;-18080.0
A(78A)
0.260;-20060.0
TA(7A)
0.250;-18740.0
(7A)(KA)
0.300;-12440.0
79AA
0.203;-23720.0
AA(7Q)
0.260;-17420.0
(8A)(9A)
0.310;-14420.0
A(8QA)
0.233;-16760.0
AA(89)
0.278;-18740.0
8A(QA)
0.240;-16760.0
A(9TA)
0.188;-17420.0
QA(9A)
0.251;-16100.0
9A(JA)
0.295;-16760.0
9KAA
0.214;-19760.0
QA(TA)
0.251;-15440.0
TA(QA)
0.301;-15440.0
A(JQA)
0.232;-14780.0
AA(JQ)
0.257;-14780.0
(QA)(KA)
0.312;-9140.0
KKAA
0.240;-12800.0
2(25A)
0.165;-33260.0
27(2A)
0.169;-31940.0
(2T)(2A)
0.171;-25640.0
2(2KA)
0.154;-27980.0
(236A)
0.177;-36260.0
(23TA)
0.126;-33620.0
33(2A)
0.161;-33920.0
(36)(2A)
0.187;-31940.0
3(29A)
0.132;-34280.0
3J(2A)
0.140;-32960.0
(245A)
0.164;-36260.0
(249A)
0.151;-33620.0
(24KA)
0.211;-30980.0
46(2A)
0.130;-35600.0
(49)(2A)
0.190;-29300.0
4(2QA)
0.168;-31640.0
6(25A)
0.170;-34940.0
T(25A)
0.180;-32300.0
5(26A)
0.161;-34940.0
58(2A)
0.185;-33620.0
(5J)(2A)
0.191;-27320.0
6(26A)
0.205;-29960.0
T(26A)
0.167;-31640.0
6(27A)
0.179;-33620.0
69(2A)
0.181;-32300.0
(6Q)(2A)
0.241;-26000.0
(279A)
0.181;-31640.0
(27KA)
0.218;-29000.0
79(2A)
0.157;-31640.0
(7Q)(2A)
0.199;-25340.0
(28TA)
0.219;-30320.0
88(2A)
0.172;-27320.0
(8J)(2A)
0.168;-25340.0
9(29A)
0.244;-26000.0
K(29A)
0.219;-27680.0
9(2QA)
0.190;-28340.0
J(2TA)
0.166;-28340.0
TJ(2A)
0.183;-28340.0
(2JQA)
0.169;-27020.0
J(2KA)
0.170;-26360.0
(QK)(2A)
0.227;-21380.0
22(4A)
0.136;-33920.0
226A
0.148;-36920.0
2A(29)
0.187;-30620.0
22(QA)
0.231;-28640.0
2(34A)
0.123;-37580.0
26(3A)
0.178;-36260.0
(29)(3A)
0.151;-29960.0
2(3QA)
0.173;-32300.0
A(234)
0.145;-37580.0
(23)(7A)
0.191;-31280.0
9A(23)
0.165;-34280.0
A(23Q)
0.181;-32300.0
2A(34)
0.146;-37580.0
2A(36)
0.192;-36260.0
2A(38)
0.145;-34940.0
2A(3T)
0.159;-33620.0
2A(3Q)
0.160;-32300.0
2(45A)
0.161;-36260.0
27(4A)
0.120;-34940.0
(2T)(4A)
0.200;-28640.0
2(4KA)
0.197;-30980.0
A(246)
0.118;-35600.0
(24)(9A)
0.219;-29300.0
JA(24)
0.179;-32300.0
24(5A)
0.124;-36260.0
24(7A)
0.145;-34940.0
24(9A)
0.166;-33620.0
24(JA)
0.188;-32300.0
24(KA)
0.179;-30980.0
26(5A)
0.158;-34940.0
(29)(5A)
0.195;-28640.0
2(5QA)
0.135;-30980.0
A(256)
0.141;-34940.0
(25)(9A)
0.191;-28640.0
JA(25)
0.147;-31640.0
25(6A)
0.160;-34940.0
25(8A)
0.152;-33620.0
25(TA)
0.196;-32300.0
25(QA)
0.154;-30980.0
(26)(6A)
0.229;-25640.0
2(69A)
0.171;-32300.0
2J(6A)
0.192;-30980.0
(26)(7A)
0.141;-29300.0
9A(26)
0.129;-32300.0
A(26Q)
0.197;-30320.0
2A(67)
0.137;-33620.0
2A(69)
0.150;-32300.0
2A(6J)
0.155;-30980.0
2A(6K)
0.176;-29660.0
(29)(7A)
0.213;-27320.0
2(7QA)
0.213;-29660.0
A(278)
0.157;-32300.0
(27)(JA)
0.193;-26000.0
KA(27)
0.165;-29000.0
2A(79)
0.147;-31640.0
2A(7J)
0.151;-30320.0
2A(7K)
0.173;-29000.0
(2T)(8A)
0.162;-26000.0
2(8KA)
0.170;-28340.0
A(28T)
0.230;-30320.0
(28)(KA)
0.227;-24020.0
28(TA)
0.164;-30320.0
28(QA)
0.183;-29000.0
(29)(9A)
0.190;-21680.0
2(9QA)
0.226;-28340.0
A(29T)
0.149;-29660.0
(29)(KA)
0.180;-23360.0
29(JA)
0.159;-29000.0
29(KA)
0.169;-27680.0
2J(TA)
0.162;-28340.0
(2T)(JA)
0.218;-24020.0
KA(2T)
0.235;-27020.0
2A(TQ)
0.216;-27680.0
2(JQA)
0.185;-27020.0
A(2JQ)
0.225;-27020.0
2A(JQ)
0.180;-27020.0
2(QKA)
0.240;-25700.0
2Q(KA)
0.212;-25700.0
33(3A)
0.150;-28940.0
(36)(3A)
0.170;-26960.0
3(39A)
0.202;-29300.0
3J(3A)
0.220;-27980.0
(345A)
0.177;-35600.0
(349A)
0.174;-32960.0
(34KA)
0.194;-30320.0
46(3A)
0.154;-34940.0
(49)(3A)
0.232;-28640.0
4(3QA)
0.160;-30980.0
6(35A)
0.152;-34280.0
T(35A)
0.176;-31640.0
5(36A)
0.146;-34280.0
58(3A)
0.119;-32960.0
(5J)(3A)
0.162;-26660.0
6(36A)
0.223;-29300.0
T(36A)
0.202;-30980.0
6(37A)
0.167;-32960.0
69(3A)
0.172;-31640.0
(6Q)(3A)
0.208;-25340.0
(379A)
0.192;-30980.0
(37KA)
0.220;-28340.0
79(3A)
0.205;-30980.0
(7Q)(3A)
0.204;-24680.0
(38TA)
0.200;-29660.0
88(3A)
0.194;-26660.0
(8J)(3A)
0.195;-24680.0
9(39A)
0.197;-25340.0
K(39A)
0.176;-27020.0
9(3QA)
0.213;-27680.0
J(3TA)
0.183;-27680.0
TJ(3A)
0.230;-27680.0
(3JQA)
0.199;-26360.0
J(3KA)
0.160;-25700.0
(QK)(3A)
0.262;-20720.0
33(5A)
0.142;-31940.0
337A
0.176;-34940.0
3A(3T)
0.164;-28640.0
33(KA)
0.197;-26660.0
3(46A)
0.140;-34940.0
38(4A)
0.144;-33620.0
(3J)(4A)
0.230;-27320.0
4A(34)
0.192;-31940.0
A(347)
0.200;-34280.0
(34)(TA)
0.222;-27980.0
QA(34)
0.204;-30980.0
345A
0.119;-39920.0
347A
0.165;-38600.0
349A
0.137;-37280.0
34JA
0.156;-35960.0
34KA
0.126;-34640.0
37(5A)
0.154;-33620.0
(3T)(5A)
0.227;-27320.0
3(5KA)
0.204;-29660.0
A(357)
0.125;-33620.0
(35)(TA)
0.222;-27320.0
QA(35)
0.165;-30320.0
356A
0.119;-38600.0
358A
0.130;-37280.0
35TA
0.203;-35960.0
35QA
0.153;-34640.0
(37)(6A)
0.162;-28640.0
3(6TA)
0.162;-30980.0
3Q(6A)
0.176;-29660.0
(36)(8A)
0.187;-27980.0
TA(36)
0.148;-30980.0
A(36K)
0.233;-29000.0
6A(38)
0.179;-32300.0
6A(3T)
0.186;-30980.0
6A(3Q)
0.196;-29660.0
37(7A)
0.169;-27980.0
(3T)(7A)
0.178;-26000.0
3(7KA)
0.140;-28340.0
A(379)
0.213;-30980.0
(37)(QA)
0.194;-24680.0
7A(38)
0.186;-31640.0
7A(3T)
0.161;-30320.0
7A(3Q)
0.235;-29000.0
38(8A)
0.189;-26660.0
(3J)(8A)
0.185;-24680.0
8A(38)
0.226;-26660.0
A(38J)
0.229;-29000.0
388A
0.148;-30980.0
38TA
0.147;-33980.0
38QA
0.200;-32660.0
(3T)(9A)
0.173;-24680.0
3(9KA)
0.175;-27020.0
A(39J)
0.180;-28340.0
399A
0.217;-29660.0
39JA
0.185;-32660.0
39KA
0.178;-31340.0
3Q(TA)
0.218;-27020.0
(3T)(QA)
0.197;-22700.0
TA(3J)
0.207;-27680.0
TA(3K)
0.226;-26360.0
3(JKA)
0.200;-25700.0
A(3JK)
0.179;-25700.0
JA(3K)
0.183;-25700.0
QA(3Q)
0.281;-21380.0
3QKA
0.208;-29360.0
45(4A)
0.144;-30620.0
(48)(4A)
0.224;-24320.0
4(4JA)
0.160;-26660.0
4K(4A)
0.176;-25340.0
(459A)
0.224;-31640.0
(45KA)
0.194;-29000.0
57(4A)
0.147;-32960.0
(5T)(4A)
0.188;-26660.0
5(4KA)
0.165;-29000.0
(469A)
0.168;-30980.0
(46KA)
0.179;-28340.0
68(4A)
0.185;-31640.0
(6J)(4A)
0.205;-25340.0
7(47A)
0.182;-27320.0
J(47A)
0.222;-29000.0
78(4A)
0.191;-30980.0
(7J)(4A)
0.174;-24680.0
8(48A)
0.205;-26000.0
Q(48A)
0.228;-27680.0
(8T)(4A)
0.213;-24680.0
8(4KA)
0.179;-27020.0
(49QA)
0.193;-27020.0
9(4JA)
0.184;-27680.0
9K(4A)
0.180;-26360.0
TT(4A)
0.209;-23360.0
(TK)(4A)
0.185;-21380.0
J(4QA)
0.187;-25700.0
K(4QA)
0.217;-24380.0
44(5A)
0.168;-30620.0
447A
0.143;-33620.0
4A(4T)
0.187;-27320.0
44(KA)
0.202;-25340.0
4(57A)
0.173;-32960.0
49(5A)
0.196;-31640.0
(4Q)(5A)
0.249;-25340.0
6A(45)
0.168;-33620.0
A(459)
0.184;-31640.0
(45)(QA)
0.185;-25340.0
5A(46)
0.172;-33620.0
5A(48)
0.206;-32300.0
5A(4T)
0.166;-30980.0
5A(4Q)
0.169;-29660.0
46(6A)
0.161;-28640.0
(49)(6A)
0.148;-26660.0
4(6QA)
0.189;-29000.0
A(467)
0.158;-32300.0
(46)(TA)
0.167;-26000.0
QA(46)
0.207;-29000.0
467A
0.174;-36620.0
469A
0.121;-35300.0
46JA
0.180;-33980.0
46KA
0.171;-32660.0
49(7A)
0.202;-30320.0
(4Q)(7A)
0.203;-24020.0
8A(47)
0.139;-30980.0
A(47J)
0.163;-29000.0
477A
0.157;-31640.0
479A
0.116;-34640.0
47JA
0.193;-33320.0
47KA
0.155;-32000.0
4T(8A)
0.178;-29000.0
(4K)(8A)
0.209;-22700.0
TA(48)
0.136;-29000.0
A(48K)
0.189;-27020.0
8A(4T)
0.214;-29000.0
8A(4Q)
0.199;-27680.0
49(9A)
0.178;-24680.0
(4Q)(9A)
0.217;-22700.0
TA(49)
0.163;-28340.0
A(49K)
0.237;-26360.0
9A(4J)
0.228;-27680.0
9A(4K)
0.199;-26360.0
4(TQA)
0.159;-26360.0
A(4TJ)
0.160;-27020.0
4TTA
0.213;-27680.0
4TQA
0.173;-30680.0
(4Q)(JA)
0.171;-21380.0
QA(4J)
0.229;-25700.0
4JQA
0.146;-30020.0
(4K)(QA)
0.197;-20060.0
QA(4K)
0.182;-24380.0
5(56A)
0.192;-28640.0
58(5A)
0.190;-27320.0
(5J)(5A)
0.267;-21020.0
6(56A)
0.187;-27980.0
T(56A)
0.165;-29660.0
6(57A)
0.168;-31640.0
69(5A)
0.157;-30320.0
(6Q)(5A)
0.245;-24020.0
(579A)
0.203;-29660.0
(57KA)
0.187;-27020.0
79(5A)
0.220;-29660.0
(7Q)(5A)
0.209;-23360.0
(58TA)
0.173;-28340.0
88(5A)
0.177;-25340.0
(8J)(5A)
0.227;-23360.0
9(59A)
0.235;-24020.0
K(59A)
0.191;-25700.0
9(5QA)
0.202;-26360.0
J(5TA)
0.211;-26360.0
TJ(5A)
0.191;-26360.0
(5JQA)
0.195;-25040.0
J(5KA)
0.199;-24380.0
(QK)(5A)
0.286;-19400.0
55(7A)
0.148;-27980.0
559A
0.194;-30980.0
5A(5Q)
0.198;-24680.0
(57)(6A)
0.186;-27320.0
5(6TA)
0.167;-29660.0
5Q(6A)
0.211;-28340.0
(56)(8A)
0.150;-26660.0
TA(56)
0.158;-29660.0
A(56K)
0.181;-27680.0
6A(58)
0.205;-30980.0
6A(5T)
0.222;-29660.0
6A(5Q)
0.206;-28340.0
57(7A)
0.175;-26660.0
(5T)(7A)
0.205;-24680.0
5(7KA)
0.219;-27020.0
A(579)
0.156;-29660.0
(57)(QA)
0.225;-23360.0
7A(58)
0.148;-30320.0
7A(5T)
0.215;-29000.0
7A(5Q)
0.229;-27680.0
58(8A)
0.229;-25340.0
(5J)(8A)
0.199;-23360.0
8A(58)
0.171;-25340.0
A(58J)
0.175;-27680.0
588A
0.159;-29660.0
58TA
0.143;-32660.0
58QA
0.197;-31340.0
(5T)(9A)
0.230;-23360.0
5(9KA)
0.246;-25700.0
A(59J)
0.158;-27020.0
599A
0.163;-28340.0
59JA
0.187;-31340.0
59KA
0.187;-30020.0
5Q(TA)
0.202;-25700.0
(5T)(QA)
0.198;-21380.0
TA(5J)
0.229;-26360.0
TA(5K)
0.175;-25040.0
5(JKA)
0.182;-24380.0
A(5JK)
0.274;-24380.0
JA(5K)
0.168;-24380.0
QA(5Q)
0.219;-20060.0
5QKA
0.180;-28040.0
67(6A)
0.205;-26660.0
(6T)(6A)
0.258;-20360.0
6(6KA)
0.196;-22700.0
(67TA)
0.194;-28340.0
77(6A)
0.193;-26000.0
(7T)(6A)
0.233;-24020.0
7(6KA)
0.164;-26360.0
(68JA)
0.185;-27020.0
(89)(6A)
0.222;-24020.0
8(6QA)
0.150;-26360.0
T(69A)
0.243;-27020.0
9(6TA)
0.143;-27020.0
9Q(6A)
0.206;-25700.0
Q(6TA)
0.216;-25040.0
(TQ)(6A)
0.217;-20720.0
(6JKA)
0.226;-23720.0
JK(6A)
0.242;-23720.0
K(6KA)
0.198;-18080.0
668A
0.179;-30320.0
6A(6J)
0.169;-24020.0
(67)(7A)
0.210;-21680.0
6(7TA)
0.189;-28340.0
6Q(7A)
0.183;-27020.0
(67)(9A)
0.162;-24680.0
JA(67)
0.167;-27680.0
67(8A)
0.166;-29660.0
67(TA)
0.141;-28340.0
67(QA)
0.215;-27020.0
(68)(8A)
0.293;-20360.0
6(8JA)
0.222;-27020.0
6K(8A)
0.172;-25700.0
(68)(JA)
0.218;-22700.0
KA(68)
0.219;-25700.0
6A(8T)
0.189;-27680.0
6A(8Q)
0.190;-26360.0
6(9TA)
0.144;-27020.0
6Q(9A)
0.183;-25700.0
(69)(JA)
0.201;-22040.0
KA(69)
0.220;-25040.0
6A(9J)
0.201;-26360.0
6A(9K)
0.198;-25040.0
(6Q)(TA)
0.194;-20720.0
JA(6T)
0.201;-25700.0
6T(JA)
0.232;-25700.0
6T(KA)
0.219;-24380.0
6Q(JA)
0.212;-24380.0
(6J)(KA)
0.264;-19400.0
6J(KA)
0.193;-23720.0
6K(QA)
0.214;-23060.0
6A(QK)
0.212;-23060.0
(78)(7A)
0.245;-20360.0
7(7JA)
0.192;-22700.0
7K(7A)
0.236;-21380.0
(78QA)
0.184;-25700.0
8(7TA)
0.225;-27020.0
8Q(7A)
0.164;-25700.0
J(79A)
0.222;-25700.0
9T(7A)
0.193;-26360.0
(9K)(7A)
0.221;-20060.0
K(7TA)
0.234;-23720.0
T(7KA)
0.264;-23720.0
JJ(7A)
0.238;-20060.0
(7QKA)
0.163;-22400.0
777A
0.186;-25340.0
7A(7T)
0.212;-23360.0
77(KA)
0.176;-21380.0
7(8TA)
0.237;-27020.0
7Q(8A)
0.208;-25700.0
(78)(TA)
0.236;-22700.0
QA(78)
0.221;-25700.0
789A
0.177;-32000.0
78JA
0.139;-30680.0
78KA
0.150;-29360.0
7J(9A)
0.203;-25700.0
(79)(TA)
0.282;-22040.0
QA(79)
0.208;-25040.0
79TA
0.222;-30680.0
79QA
0.179;-29360.0
(7J)(TA)
0.255;-20720.0
TA(7T)
0.279;-21380.0
A(7TK)
0.221;-23720.0
TA(7Q)
0.161;-24380.0
7J(JA)
0.214;-20060.0
(7J)(QA)
0.180;-19400.0
JA(7Q)
0.227;-23720.0
7Q(QA)
0.203;-18740.0
7QQA
0.249;-23060.0
7KKA
0.257;-21740.0
8(8JA)
0.193;-21380.0
8K(8A)
0.237;-20060.0
(89KA)
0.233;-23720.0
9J(8A)
0.169;-25040.0
(8TJA)
0.197;-24380.0
(TJ)(8A)
0.199;-20060.0
J(8JA)
0.239;-19400.0
JQ(8A)
0.226;-23060.0
Q(8KA)
0.243;-21740.0
889A
0.181;-27020.0
8A(8Q)
0.252;-20720.0
(8T)(9A)
0.252;-21380.0
8(9KA)
0.206;-23720.0
A(89J)
0.192;-25040.0
899A
0.156;-26360.0
89JA
0.204;-29360.0
89KA
0.183;-28040.0
8Q(TA)
0.217;-23720.0
(8T)(QA)
0.247;-19400.0
TA(8J)
0.236;-24380.0
TA(8K)
0.241;-23060.0
8(JKA)
0.218;-22400.0
A(8JK)
0.268;-22400.0
JA(8K)
0.172;-22400.0
QA(8Q)
0.304;-18080.0
8QKA
0.257;-26060.0
9T(9A)
0.201;-20720.0
(9K)(9A)
0.258;-14420.0
K(9TA)
0.205;-22400.0
T(9KA)
0.242;-22400.0
JJ(9A)
0.227;-18740.0
(9QKA)
0.180;-21080.0
999A
0.210;-21380.0
9A(9Q)
0.214;-19400.0
(9J)(TA)
0.218;-19400.0
TA(9T)
0.214;-20060.0
A(9TK)
0.196;-22400.0
TA(9Q)
0.279;-23060.0
9J(JA)
0.314;-18740.0
(9J)(QA)
0.234;-18080.0
JA(9Q)
0.228;-22400.0
9Q(QA)
0.289;-17420.0
9QQA
0.250;-21740.0
9KKA
0.220;-20420.0
T(TKA)
0.238;-17420.0
JJ(TA)
0.217;-18080.0
(TQKA)
0.192;-20420.0
TTTA
0.248;-19400.0
TA(TK)
0.257;-17420.0
(TK)(JA)
0.253;-16760.0
KA(TJ)
0.189;-21080.0
TA(JK)
0.213;-21080.0
(TQ)(KA)
0.277;-16100.0
(TK)(KA)
0.267;-11120.0
J(JKA)
0.301;-16100.0
(QK)(JA)
0.243;-15440.0
JJ(KA)
0.291;-16100.0
QA(JQ)
0.277;-16100.0
JQKA
0.214;-24080.0
QK(QA)
0.316;-14780.0
QK(KA)
0.338;-14120.0
22(24)
0.193;-37520.0
22(28)
0.158;-34880.0
22(2Q)
0.164;-32240.0
24(23)
0.115;-41180.0
(23)(27)
0.144;-34880.0
2(23T)
0.150;-37220.0
2Q(23)
0.190;-35900.0
23(25)
0.132;-40520.0
2237
0.110;-43520.0
22(3T)
0.189;-37220.0
23(2K)
0.188;-35240.0
2(246)
0.164;-39200.0
28(24)
0.177;-37880.0
(24)(2J)
0.159;-31580.0
2244
0.117;-40520.0
22(47)
0.124;-38540.0
24(2T)
0.157;-36560.0
224Q
0.119;-39560.0
26(25)
0.133;-38540.0
(25)(29)
0.145;-32240.0
2(25Q)
0.161;-34580.0
22(56)
0.160;-38540.0
25(29)
0.132;-36560.0
225J
0.133;-39560.0
26(26)
0.182;-33560.0
(26)(29)
0.221;-31580.0
2(26Q)
0.158;-33920.0
22(67)
0.160;-37220.0
26(2T)
0.113;-35240.0
226Q
0.116;-38240.0
28(27)
0.122;-35900.0
(27)(2J)
0.193;-29600.0
2277
0.174;-36560.0
22(7T)
0.180;-34580.0
27(2K)
0.180;-32600.0
2(28T)
0.194;-33920.0
2Q(28)
0.183;-32600.0
28(2T)
0.127;-33920.0
228Q
0.160;-36920.0
2T(29)
0.122;-33260.0
(29)(2K)
0.193;-26960.0
229J
0.135;-36920.0
2T(2T)
0.181;-28280.0
(2T)(2K)
0.186;-26300.0
22TQ
0.126;-35600.0
2Q(2J)
0.164;-30620.0
2J(2K)
0.224;-29960.0
22QQ
0.191;-29960.0
3(234)
0.142;-40520.0
36(23)
0.163;-39200.0
(23)(39)
0.206;-32900.0
3(23Q)
0.150;-35240.0
5(234)
0.095;-43520.0
9(234)
0.123;-40880.0
K(234)
0.126;-38240.0
4(237)
0.114;-42200.0
49(23)
0.129;-40880.0
(23)(4Q)
0.134;-34580.0
(2357)
0.125;-41540.0
(235J)
0.165;-38900.0
(23)(56)
0.144;-37880.0
5(239)
0.125;-40220.0
5J(23)
0.134;-38900.0
(2367)
0.161;-40880.0
(236J)
0.136;-38240.0
(23)(67)
0.162;-36560.0
6(23T)
0.113;-38900.0
6Q(23)
0.151;-37580.0
9(237)
0.146;-38900.0
K(237)
0.129;-36260.0
7(23T)
0.159;-38240.0
7Q(23)
0.121;-36920.0
T(238)
0.124;-37580.0
8(239)
0.152;-38240.0
8J(23)
0.187;-36920.0
(239T)
0.124;-36920.0
99(23)
0.184;-33260.0
(23)(9Q)
0.166;-31280.0
(23TQ)
0.151;-34940.0
T(23Q)
0.143;-34940.0
Q(23J)
0.156;-34280.0
(23)(JK)
0.175;-29300.0
QK(23)
0.167;-32960.0
23(35)
0.126;-39860.0
33(28)
0.154;-37880.0
233T
0.136;-40880.0
23(3K)
0.146;-34580.0
(24)(36)
0.103;-38540.0
3(249)
0.125;-40880.0
3J(24)
0.139;-39560.0
(34)(25)
0.128;-39200.0
27(34)
0.129;-42200.0
2(34T)
0.138;-40220.0
(34)(2K)
0.188;-33920.0
34(26)
0.112;-42860.0
34(28)
0.119;-41540.0
34(2T)
0.106;-40220.0
34(2Q)
0.132;-38900.0
(25)(35)
0.174;-34220.0
3(258)
0.172;-40880.0
3T(25)
0.166;-39560.0
(25)(3K)
0.184;-33260.0
27(35)
0.155;-41540.0
2(35T)
0.097;-39560.0
(35)(2K)
0.159;-33260.0
35(27)
0.120;-41540.0
35(29)
0.122;-40220.0
35(2J)
0.169;-38900.0
35(2K)
0.102;-37580.0
37(26)
0.142;-40880.0
(26)(3T)
0.198;-34580.0
3(26K)
0.129;-36920.0
2(368)
0.126;-40220.0
(36)(2J)
0.150;-33920.0
2K(36)
0.123;-36920.0
23(68)
0.117;-40220.0
23(6T)
0.116;-38900.0
23(6Q)
0.111;-37580.0
3(278)
0.134;-39560.0
3T(27)
0.134;-38240.0
(27)(3K)
0.192;-31940.0
29(37)
0.137;-38900.0
2(37Q)
0.129;-36920.0
23(78)
0.153;-39560.0
23(7T)
0.165;-38240.0
23(7Q)
0.135;-36920.0
3(289)
0.103;-38240.0
3J(28)
0.107;-36920.0
(38)(29)
0.175;-33920.0
2J(38)
0.124;-36920.0
38(29)
0.167;-38240.0
38(2J)
0.179;-36920.0
38(2K)
0.110;-35600.0
3T(29)
0.153;-36920.0
(29)(3K)
0.189;-30620.0
2J(39)
0.144;-36260.0
39(2T)
0.117;-36920.0
39(2Q)
0.180;-35600.0
(2T)(3T)
0.159;-27620.0
3(2TK)
0.158;-34280.0
2(3TQ)
0.163;-34940.0
23(TJ)
0.167;-35600.0
23(TK)
0.167;-34280.0
(2J)(3K)
0.160;-29300.0
2K(3J)
0.148;-33620.0
23(JK)
0.172;-33620.0
(3Q)(2K)
0.154;-28640.0
(2K)(3K)
0.162;-23660.0
4(246)
0.130;-37880.0
48(24)
0.127;-36560.0
(24)(4J)
0.165;-30260.0
5(245)
0.159;-37880.0
9(245)
0.132;-39560.0
K(245)
0.146;-36920.0
5(248)
0.125;-40220.0
5T(24)
0.143;-38900.0
(24)(5K)
0.175;-32600.0
9(246)
0.170;-38900.0
K(246)
0.118;-36260.0
6(249)
0.164;-38900.0
6J(24)
0.119;-37580.0
(2478)
0.104;-38900.0
(247Q)
0.160;-36260.0
7(249)
0.153;-38240.0
7J(24)
0.168;-36920.0
(2489)
0.135;-37580.0
(248K)
0.126;-34940.0
8T(24)
0.124;-36920.0
(24)(8K)
0.186;-30620.0
Q(249)
0.171;-34940.0
(24)(9J)
0.165;-31280.0
T(24T)
0.183;-31280.0
T(24J)
0.190;-34940.0
TK(24)
0.131;-33620.0
(24)(JQ)
0.160;-29300.0
QQ(24)
0.160;-28640.0
24(45)
0.169;-38540.0
44(28)
0.172;-36560.0
244T
0.129;-39560.0
24(4K)
0.148;-33260.0
(25)(47)
0.148;-36560.0
4(25T)
0.123;-38900.0
4Q(25)
0.138;-37580.0
(45)(27)
0.144;-36560.0
29(45)
0.130;-39560.0
2(45Q)
0.144;-37580.0
24(56)
0.112;-41540.0
24(58)
0.132;-40220.0
24(5T)
0.142;-38900.0
24(5Q)
0.145;-37580.0
4(267)
0.152;-40220.0
49(26)
0.140;-38900.0
(26)(4Q)
0.162;-32600.0
27(46)
0.134;-40220.0
2(46T)
0.182;-38240.0
(46)(2K)
0.153;-31940.0
46(28)
0.128;-39560.0
46(2T)
0.162;-38240.0
46(2Q)
0.129;-36920.0
(27)(47)
0.171;-30920.0
4(27T)
0.133;-37580.0
4Q(27)
0.130;-36260.0
(47)(29)
0.167;-33920.0
2J(47)
0.144;-36920.0
47(28)
0.141;-38900.0
47(2T)
0.124;-37580.0
47(2Q)
0.160;-36260.0
(28)(48)
0.166;-29600.0
4(28J)
0.164;-36260.0
4K(28)
0.144;-34940.0
(48)(2J)
0.160;-31940.0
2K(48)
0.138;-34940.0
24(8T)
0.142;-36920.0
24(8Q)
0.123;-35600.0
4(29T)
0.198;-36260.0
4Q(29)
0.136;-34940.0
(49)(2J)
0.207;-31280.0
2K(49)
0.120;-34280.0
24(9J)
0.139;-35600.0
24(9K)
0.170;-34280.0
(2T)(4Q)
0.209;-29960.0
2J(4T)
0.120;-34940.0
4T(2J)
0.132;-34940.0
4T(2K)
0.182;-33620.0
4Q(2J)
0.174;-33620.0
(4J)(2K)
0.233;-28640.0
4J(2K)
0.162;-32960.0
4K(2Q)
0.148;-32300.0
24(QK)
0.161;-32300.0
(25)(56)
0.162;-32240.0
5(259)
0.186;-34580.0
5J(25)
0.181;-33260.0
(2567)
0.142;-39560.0
(256J)
0.126;-36920.0
(25)(67)
0.137;-35240.0
6(25T)
0.150;-37580.0
6Q(25)
0.119;-36260.0
9(257)
0.141;-37580.0
K(257)
0.148;-34940.0
7(25T)
0.109;-36920.0
7Q(25)
0.149;-35600.0
T(258)
0.154;-36260.0
8(259)
0.132;-36920.0
8J(25)
0.135;-35600.0
(259T)
0.134;-35600.0
99(25)
0.193;-31940.0
(25)(9Q)
0.174;-29960.0
(25TQ)
0.151;-33620.0
T(25Q)
0.180;-33620.0
Q(25J)
0.152;-32960.0
(25)(JK)
0.180;-27980.0
QK(25)
0.148;-31640.0
25(57)
0.121;-35900.0
55(2T)
0.150;-33920.0
255Q
0.177;-36920.0
57(26)
0.140;-39560.0
(26)(5T)
0.123;-33260.0
5(26K)
0.149;-35600.0
2(568)
0.126;-38900.0
(56)(2J)
0.183;-32600.0
2K(56)
0.141;-35600.0
25(68)
0.146;-38900.0
25(6T)
0.169;-37580.0
25(6Q)
0.149;-36260.0
5(278)
0.144;-38240.0
5T(27)
0.191;-36920.0
(27)(5K)
0.149;-30620.0
29(57)
0.172;-37580.0
2(57Q)
0.155;-35600.0
25(78)
0.150;-38240.0
25(7T)
0.161;-36920.0
25(7Q)
0.139;-35600.0
5(289)
0.158;-36920.0
5J(28)
0.151;-35600.0
(58)(29)
0.133;-32600.0
2J(58)
0.163;-35600.0
58(29)
0.123;-36920.0
58(2J)
0.124;-35600.0
58(2K)
0.170;-34280.0
5T(29)
0.171;-35600.0
(29)(5K)
0.175;-29300.0
2J(59)
0.155;-34940.0
59(2T)
0.166;-35600.0
59(2Q)
0.160;-34280.0
(2T)(5T)
0.149;-26300.0
5(2TK)
0.131;-32960.0
2(5TQ)
0.159;-33620.0
25(TJ)
0.147;-34280.0
25(TK)
0.151;-32960.0
(2J)(5K)
0.156;-27980.0
2K(5J)
0.173;-32300.0
25(JK)
0.170;-32300.0
(5Q)(2K)
0.207;-27320.0
(2K)(5K)
0.223;-22340.0
6(268)
0.197;-33920.0
6T(26)
0.210;-32600.0
(26)(6K)
0.243;-26300.0
T(267)
0.131;-36260.0
7(268)
0.170;-37580.0
7T(26)
0.169;-36260.0
(26)(7K)
0.162;-29960.0
J(268)
0.183;-34940.0
89(26)
0.136;-36260.0
(26)(8Q)
0.177;-29960.0
(269J)
0.154;-34280.0
(26)(9T)
0.184;-30620.0
9(26K)
0.172;-32960.0
(26TK)
0.145;-32300.0
TQ(26)
0.139;-32960.0
K(26J)
0.155;-31640.0
Q(26Q)
0.167;-27320.0
KK(26)
0.164;-26000.0
66(29)
0.180;-33260.0
266J
0.161;-36260.0
67(27)
0.212;-33920.0
(27)(6T)
0.216;-31940.0
6(27K)
0.137;-34280.0
2(679)
0.121;-36920.0
(67)(2Q)
0.227;-30620.0
27(68)
0.143;-37580.0
27(6T)
0.148;-36260.0
27(6Q)
0.141;-34940.0
68(28)
0.190;-32600.0
(28)(6J)
0.173;-30620.0
28(68)
0.213;-32600.0
2(68J)
0.140;-34940.0
2688
0.182;-36920.0
268T
0.132;-39920.0
268Q
0.160;-38600.0
(29)(6T)
0.184;-30620.0
6(29K)
0.149;-32960.0
2(69J)
0.158;-34280.0
2699
0.161;-35600.0
269J
0.147;-38600.0
269K
0.131;-37280.0
6Q(2T)
0.201;-32960.0
(6T)(2Q)
0.147;-28640.0
2T(6J)
0.166;-33620.0
2T(6K)
0.205;-32300.0
6(2JK)
0.152;-31640.0
2(6JK)
0.184;-31640.0
2J(6K)
0.139;-31640.0
2Q(6Q)
0.163;-27320.0
26QK
0.172;-35300.0
78(27)
0.131;-32600.0
(27)(7J)
0.221;-26300.0
8(278)
0.157;-31940.0
Q(278)
0.155;-33620.0
(27)(8T)
0.232;-30620.0
8(27K)
0.158;-32960.0
(279Q)
0.168;-32960.0
9(27J)
0.177;-33620.0
9K(27)
0.143;-32300.0
TT(27)
0.162;-29300.0
(27)(TK)
0.172;-27320.0
J(27Q)
0.176;-31640.0
K(27Q)
0.187;-30320.0
77(28)
0.173;-32600.0
277T
0.162;-35600.0
27(7K)
0.198;-29300.0
(28)(7T)
0.161;-30620.0
7(28K)
0.188;-32960.0
2(78T)
0.140;-34940.0
(78)(2K)
0.189;-28640.0
78(2T)
0.124;-34940.0
78(2Q)
0.163;-33620.0
(29)(79)
0.173;-26300.0
7(29Q)
0.152;-32960.0
2(79T)
0.139;-34280.0
(79)(2K)
0.213;-27980.0
79(2J)
0.184;-33620.0
79(2K)
0.142;-32300.0
7J(2T)
0.192;-32960.0
(7T)(2J)
0.170;-28640.0
2K(7T)
0.165;-31640.0
27(TQ)
0.193;-32300.0
7(2JQ)
0.203;-31640.0
2(7JQ)
0.141;-31640.0
27(JQ)
0.172;-31640.0
7(2QK)
0.182;-30320.0
7Q(2K)
0.184;-30320.0
88(28)
0.197;-26960.0
(28)(8J)
0.164;-24980.0
9(289)
0.188;-29960.0
K(289)
0.130;-31640.0
9(28Q)
0.200;-32300.0
J(28T)
0.138;-32300.0
TJ(28)
0.207;-32300.0
(28JQ)
0.191;-30980.0
J(28K)
0.209;-30320.0
(28)(QK)
0.173;-25340.0
88(2T)
0.133;-29960.0
288Q
0.164;-32960.0
8T(29)
0.162;-33620.0
(29)(8K)
0.210;-27320.0
2J(89)
0.153;-32960.0
89(2T)
0.154;-33620.0
89(2Q)
0.186;-32300.0
(2T)(8T)
0.203;-24320.0
8(2TK)
0.172;-30980.0
2(8TQ)
0.203;-31640.0
28(TJ)
0.210;-32300.0
28(TK)
0.161;-30980.0
(2J)(8K)
0.161;-26000.0
2K(8J)
0.169;-30320.0
28(JK)
0.204;-30320.0
(8Q)(2K)
0.162;-25340.0
(2K)(8K)
0.232;-20360.0
9(29J)
0.174;-27980.0
9K(29)
0.236;-26660.0
TT(29)
0.165;-27980.0
(29)(TK)
0.157;-26000.0
J(29Q)
0.155;-30320.0
K(29Q)
0.158;-29000.0
99(2T)
0.149;-28640.0
299Q
0.146;-31640.0
9J(2T)
0.130;-31640.0
(9T)(2J)
0.191;-27320.0
2K(9T)
0.187;-30320.0
29(TQ)
0.147;-30980.0
9(2JQ)
0.149;-30320.0
2(9JQ)
0.169;-30320.0
29(JQ)
0.163;-30320.0
9(2QK)
0.170;-29000.0
9Q(2K)
0.181;-29000.0
TT(2T)
0.173;-23000.0
(2T)(TK)
0.213;-21020.0
J(2TQ)
0.157;-29660.0
K(2TQ)
0.180;-28340.0
TT(2J)
0.185;-26660.0
2TTK
0.160;-29660.0
TK(2J)
0.156;-29000.0
2TJJ
0.154;-30320.0
2TJK
0.147;-33320.0
2(TQK)
0.187;-28340.0
TK(2K)
0.193;-23360.0
(2J)(JK)
0.198;-19700.0
QK(2J)
0.200;-27680.0
2J(JK)
0.207;-24020.0
(JQ)(2K)
0.217;-23360.0
(2K)(JK)
0.305;-18380.0
K(2QK)
0.238;-22040.0
2K(QK)
0.214;-22040.0
3335
0.139;-39200.0
3339
0.137;-36560.0
333K
0.146;-33920.0
36(34)
0.173;-37880.0
(34)(39)
0.165;-31580.0
3(34Q)
0.173;-33920.0
33(45)
0.141;-38540.0
34(38)
0.160;-36560.0
334T
0.133;-39560.0
33(4K)
0.136;-33260.0
(35)(37)
0.141;-32240.0
3(35T)
0.201;-34580.0
3Q(35)
0.145;-33260.0
35(37)
0.123;-36560.0
3359
0.098;-39560.0
33(5Q)
0.171;-33260.0
(36)(37)
0.189;-31580.0
3(36T)
0.136;-33920.0
3Q(36)
0.175;-32600.0
36(38)
0.141;-35240.0
336T
0.137;-38240.0
33(6K)
0.165;-31940.0
(37)(39)
0.170;-29600.0
3(37Q)
0.217;-31940.0
33(78)
0.160;-34580.0
37(3J)
0.156;-32600.0
337K
0.143;-35600.0
3T(38)
0.201;-32600.0
(38)(3K)
0.226;-26300.0
338T
0.156;-36920.0
33(8K)
0.207;-30620.0
(39)(3J)
0.231;-26960.0
3399
0.193;-32600.0
33(9Q)
0.183;-30620.0
(3T)(3J)
0.193;-26300.0
33TT
0.217;-31280.0
33(TK)
0.175;-29300.0
(3J)(3K)
0.189;-24320.0
33JK
0.136;-32960.0
33(QK)
0.202;-27980.0
45(34)
0.148;-37880.0
(34)(48)
0.161;-31580.0
4(34J)
0.177;-33920.0
4K(34)
0.169;-32600.0
(3459)
0.149;-38900.0
(345K)
0.152;-36260.0
57(34)
0.146;-40220.0
(34)(5T)
0.152;-33920.0
5(34K)
0.164;-36260.0
(3469)
0.166;-38240.0
(346K)
0.145;-35600.0
68(34)
0.101;-38900.0
(34)(6J)
0.173;-32600.0
7(347)
0.124;-34580.0
J(347)
0.167;-36260.0
78(34)
0.107;-38240.0
(34)(7J)
0.148;-31940.0
8(348)
0.195;-33260.0
Q(348)
0.173;-34940.0
(34)(8T)
0.172;-31940.0
8(34K)
0.143;-34280.0
(349Q)
0.134;-34280.0
9(34J)
0.185;-34940.0
9K(34)
0.166;-33620.0
TT(34)
0.146;-30620.0
(34)(TK)
0.183;-28640.0
J(34Q)
0.178;-32960.0
K(34Q)
0.178;-31640.0
44(35)
0.139;-37880.0
3447
0.139;-40880.0
34(4T)
0.147;-34580.0
44(3K)
0.142;-32600.0
4(357)
0.110;-40220.0
49(35)
0.124;-38900.0
(35)(4Q)
0.218;-32600.0
36(45)
0.125;-40880.0
3(459)
0.145;-38900.0
(45)(3Q)
0.169;-32600.0
35(46)
0.134;-40880.0
35(48)
0.120;-39560.0
35(4T)
0.137;-38240.0
35(4Q)
0.155;-36920.0
46(36)
0.174;-35900.0
(36)(49)
0.175;-33920.0
4(36Q)
0.171;-36260.0
3(467)
0.118;-39560.0
(46)(3T)
0.130;-33260.0
3Q(46)
0.123;-36260.0
3467
0.099;-43880.0
3469
0.132;-42560.0
346J
0.121;-41240.0
346K
0.144;-39920.0
49(37)
0.150;-37580.0
(37)(4Q)
0.169;-31280.0
38(47)
0.139;-38240.0
3(47J)
0.151;-36260.0
3477
0.114;-38900.0
3479
0.119;-41900.0
347J
0.094;-40580.0
347K
0.159;-39260.0
4T(38)
0.147;-36260.0
(38)(4K)
0.180;-29960.0
3T(48)
0.157;-36260.0
3(48K)
0.211;-34280.0
38(4T)
0.193;-36260.0
38(4Q)
0.176;-34940.0
49(39)
0.197;-31940.0
(39)(4Q)
0.177;-29960.0
3T(49)
0.153;-35600.0
3(49K)
0.148;-33620.0
39(4J)
0.149;-34940.0
39(4K)
0.172;-33620.0
4(3TQ)
0.197;-33620.0
3(4TJ)
0.150;-34280.0
34TT
0.135;-34940.0
34TQ
0.123;-37940.0
(3J)(4Q)
0.171;-28640.0
3Q(4J)
0.136;-32960.0
34JQ
0.147;-37280.0
(3Q)(4K)
0.185;-27320.0
3Q(4K)
0.168;-31640.0
5(356)
0.140;-35900.0
58(35)
0.129;-34580.0
(35)(5J)
0.139;-28280.0
6(356)
0.124;-35240.0
T(356)
0.121;-36920.0
6(357)
0.159;-38900.0
69(35)
0.149;-37580.0
(35)(6Q)
0.158;-31280.0
(3579)
0.130;-36920.0
(357K)
0.164;-34280.0
79(35)
0.143;-36920.0
(35)(7Q)
0.173;-30620.0
(358T)
0.119;-35600.0
88(35)
0.180;-32600.0
(35)(8J)
0.186;-30620.0
9(359)
0.161;-31280.0
K(359)
0.159;-32960.0
9(35Q)
0.168;-33620.0
J(35T)
0.186;-33620.0
TJ(35)
0.144;-33620.0
(35JQ)
0.196;-32300.0
J(35K)
0.191;-31640.0
(35)(QK)
0.184;-26660.0
55(37)
0.120;-35240.0
3559
0.158;-38240.0
35(5Q)
0.201;-31940.0
(36)(57)
0.157;-34580.0
5(36T)
0.113;-36920.0
5Q(36)
0.138;-35600.0
(56)(38)
0.145;-33920.0
3T(56)
0.126;-36920.0
3(56K)
0.182;-34940.0
36(58)
0.149;-38240.0
36(5T)
0.149;-36920.0
36(5Q)
0.132;-35600.0
57(37)
0.197;-33920.0
(37)(5T)
0.139;-31940.0
5(37K)
0.209;-34280.0
3(579)
0.117;-36920.0
(57)(3Q)
0.175;-30620.0
37(58)
0.125;-37580.0
37(5T)
0.138;-36260.0
37(5Q)
0.172;-34940.0
58(38)
0.166;-32600.0
(38)(5J)
0.192;-30620.0
38(58)
0.140;-32600.0
3(58J)
0.170;-34940.0
3588
0.130;-36920.0
358T
0.142;-39920.0
358Q
0.150;-38600.0
(39)(5T)
0.157;-30620.0
5(39K)
0.191;-32960.0
3(59J)
0.147;-34280.0
3599
0.159;-35600.0
359J
0.147;-38600.0
359K
0.167;-37280.0
5Q(3T)
0.157;-32960.0
(5T)(3Q)
0.224;-28640.0
3T(5J)
0.131;-33620.0
3T(5K)
0.139;-32300.0
5(3JK)
0.199;-31640.0
3(5JK)
0.153;-31640.0
3J(5K)
0.196;-31640.0
3Q(5Q)
0.203;-27320.0
35QK
0.142;-35300.0
67(36)
0.196;-33920.0
(36)(6T)
0.205;-27620.0
6(36K)
0.151;-29960.0
(367T)
0.151;-35600.0
77(36)
0.164;-33260.0
(36)(7T)
0.205;-31280.0
7(36K)
0.153;-33620.0
(368J)
0.149;-34280.0
(36)(89)
0.157;-31280.0
8(36Q)
0.145;-33620.0
T(369)
0.123;-34280.0
9(36T)
0.132;-34280.0
9Q(36)
0.168;-32960.0
Q(36T)
0.167;-32300.0
(36)(TQ)
0.157;-27980.0
(36JK)
0.180;-30980.0
JK(36)
0.215;-30980.0
K(36K)
0.182;-25340.0
3668
0.133;-37580.0
36(6J)
0.203;-31280.0
(37)(67)
0.149;-28940.0
6(37T)
0.142;-35600.0
6Q(37)
0.146;-34280.0
(67)(39)
0.199;-31940.0
3J(67)
0.159;-34940.0
67(38)
0.132;-36920.0
67(3T)
0.156;-35600.0
67(3Q)
0.154;-34280.0
(38)(68)
0.189;-27620.0
6(38J)
0.157;-34280.0
6K(38)
0.139;-32960.0
(68)(3J)
0.149;-29960.0
3K(68)
0.162;-32960.0
36(8T)
0.175;-34940.0
36(8Q)
0.169;-33620.0
6(39T)
0.116;-34280.0
6Q(39)
0.151;-32960.0
(69)(3J)
0.189;-29300.0
3K(69)
0.167;-32300.0
36(9J)
0.130;-33620.0
36(9K)
0.201;-32300.0
(3T)(6Q)
0.159;-27980.0
3J(6T)
0.171;-32960.0
6T(3J)
0.162;-32960.0
6T(3K)
0.201;-31640.0
6Q(3J)
0.167;-31640.0
(6J)(3K)
0.160;-26660.0
6J(3K)
0.167;-30980.0
6K(3Q)
0.192;-30320.0
36(QK)
0.191;-30320.0
(37)(78)
0.196;-27620.0
7(37J)
0.192;-29960.0
7K(37)
0.183;-28640.0
(378Q)
0.190;-32960.0
8(37T)
0.153;-34280.0
8Q(37)
0.144;-32960.0
J(379)
0.191;-32960.0
9T(37)
0.167;-33620.0
(37)(9K)
0.217;-27320.0
K(37T)
0.160;-30980.0
T(37K)
0.136;-30980.0
JJ(37)
0.180;-27320.0
(37QK)
0.140;-29660.0
3777
0.158;-32600.0
37(7T)
0.174;-30620.0
77(3K)
0.193;-28640.0
7(38T)
0.166;-34280.0
7Q(38)
0.146;-32960.0
(78)(3T)
0.165;-29960.0
3Q(78)
0.188;-32960.0
3789
0.140;-39260.0
378J
0.166;-37940.0
378K
0.154;-36620.0
7J(39)
0.184;-32960.0
(79)(3T)
0.187;-29300.0
3Q(79)
0.183;-32300.0
379T
0.167;-37940.0
379Q
0.155;-36620.0
(3T)(7J)
0.195;-27980.0
3T(7T)
0.166;-28640.0
3(7TK)
0.197;-30980.0
3T(7Q)
0.184;-31640.0
7J(3J)
0.173;-27320.0
(7J)(3Q)
0.167;-26660.0
3J(7Q)
0.179;-30980.0
7Q(3Q)
0.218;-26000.0
37QQ
0.190;-30320.0
37KK
0.167;-29000.0
8(38J)
0.188;-28640.0
8K(38)
0.181;-27320.0
(389K)
0.165;-30980.0
9J(38)
0.135;-32300.0
(38TJ)
0.166;-31640.0
(38)(TJ)
0.146;-27320.0
J(38J)
0.190;-26660.0
JQ(38)
0.171;-30320.0
Q(38K)
0.211;-29000.0
3889
0.146;-34280.0
38(8Q)
0.158;-27980.0
(39)(8T)
0.200;-28640.0
8(39K)
0.159;-30980.0
3(89J)
0.150;-32300.0
3899
0.153;-33620.0
389J
0.130;-36620.0
389K
0.152;-35300.0
8Q(3T)
0.154;-30980.0
(8T)(3Q)
0.140;-26660.0
3T(8J)
0.123;-31640.0
3T(8K)
0.155;-30320.0
8(3JK)
0.176;-29660.0
3(8JK)
0.199;-29660.0
3J(8K)
0.198;-29660.0
3Q(8Q)
0.237;-25340.0
38QK
0.176;-33320.0
9T(39)
0.193;-27980.0
(39)(9K)
0.228;-21680.0
K(39T)
0.149;-29660.0
T(39K)
0.203;-29660.0
JJ(39)
0.210;-26000.0
(39QK)
0.242;-28340.0
3999
0.179;-28640.0
39(9Q)
0.246;-26660.0
(3T)(9J)
0.167;-26660.0
3T(9T)
0.185;-27320.0
3(9TK)
0.177;-29660.0
3T(9Q)
0.163;-30320.0
9J(3J)
0.257;-26000.0
(9J)(3Q)
0.192;-25340.0
3J(9Q)
0.166;-29660.0
9Q(3Q)
0.194;-24680.0
39QQ
0.205;-29000.0
39KK
0.181;-27680.0
T(3TK)
0.162;-24680.0
JJ(3T)
0.181;-25340.0
(3TQK)
0.223;-27680.0
3TTT
0.234;-26660.0
3T(TK)
0.190;-24680.0
(3J)(TK)
0.196;-24020.0
3K(TJ)
0.169;-28340.0
3T(JK)
0.150;-28340.0
(TQ)(3K)
0.248;-23360.0
(3K)(TK)
0.204;-18380.0
J(3JK)
0.199;-23360.0
(3J)(QK)
0.207;-22700.0
JJ(3K)
0.214;-23360.0
3Q(JQ)
0.212;-23360.0
3JQK
0.165;-31340.0
QK(3Q)
0.252;-22040.0
QK(3K)
0.231;-21380.0
44(46)
0.155;-32240.0
44(4T)
0.134;-29600.0
(45)(45)
0.183;-27920.0
4(458)
0.147;-34580.0
4T(45)
0.159;-33260.0
(45)(4K)
0.148;-26960.0
4457
0.130;-39560.0
44(5T)
0.184;-33260.0
45(4K)
0.184;-31280.0
4(468)
0.183;-33920.0
4T(46)
0.169;-32600.0
(46)(4K)
0.188;-26300.0
4468
0.112;-38240.0
44(6J)
0.180;-31940.0
(47)(47)
0.206;-25280.0
4(47T)
0.143;-31940.0
4Q(47)
0.200;-30620.0
47(49)
0.143;-32600.0
447J
0.184;-35600.0
48(48)
0.196;-28280.0
(48)(4J)
0.189;-26300.0
4488
0.165;-32600.0
44(8J)
0.183;-30620.0
(49)(49)
0.204;-22640.0
4(49Q)
0.195;-29300.0
44(9T)
0.185;-30620.0
49(4K)
0.197;-28640.0
4(4TQ)
0.181;-28640.0
44(TJ)
0.198;-29300.0
(4J)(4J)
0.253;-20000.0
44JJ
0.190;-28640.0
4Q(4Q)
0.221;-23000.0
(4K)(4K)
0.262;-17360.0
(45)(57)
0.169;-30260.0
5(45T)
0.198;-32600.0
5Q(45)
0.165;-31280.0
8(456)
0.144;-37580.0
Q(456)
0.148;-34940.0
(45)(68)
0.189;-33260.0
6(45J)
0.150;-35600.0
6K(45)
0.138;-34280.0
(457J)
0.165;-34940.0
(45)(78)
0.176;-32600.0
7(45J)
0.156;-34940.0
7K(45)
0.132;-33620.0
(458Q)
0.133;-33620.0
8(45T)
0.185;-34940.0
8Q(45)
0.147;-33620.0
J(459)
0.169;-33620.0
9T(45)
0.180;-34280.0
(45)(9K)
0.172;-27980.0
K(45T)
0.158;-31640.0
T(45K)
0.135;-31640.0
JJ(45)
0.205;-27980.0
(45QK)
0.167;-30320.0
4555
0.142;-35900.0
45(58)
0.151;-33920.0
55(4J)
0.146;-31940.0
455K
0.138;-34940.0
58(46)
0.153;-37580.0
(46)(5J)
0.169;-31280.0
46(56)
0.133;-34580.0
4(569)
0.153;-36920.0
(56)(4Q)
0.203;-30620.0
46(57)
0.124;-38240.0
46(59)
0.148;-36920.0
46(5J)
0.158;-35600.0
46(5K)
0.124;-34280.0
5(479)
0.157;-36260.0
5J(47)
0.184;-34940.0
(57)(48)
0.181;-32600.0
4T(57)
0.180;-35600.0
4(57K)
0.162;-33620.0
47(59)
0.170;-36260.0
47(5J)
0.167;-34940.0
47(5K)
0.167;-33620.0
5(48T)
0.143;-34940.0
5Q(48)
0.144;-33620.0
(58)(4T)
0.196;-30620.0
4Q(58)
0.130;-33620.0
4589
0.108;-39920.0
458J
0.127;-38600.0
458K
0.108;-37280.0
5J(49)
0.185;-33620.0
(59)(4T)
0.167;-29960.0
4Q(59)
0.202;-32960.0
459T
0.125;-38600.0
459Q
0.177;-37280.0
(4T)(5J)
0.160;-28640.0
4T(5T)
0.142;-29300.0
4(5TK)
0.176;-31640.0
4T(5Q)
0.152;-32300.0
5J(4J)
0.222;-27980.0
(5J)(4Q)
0.220;-27320.0
4J(5Q)
0.137;-31640.0
5Q(4Q)
0.175;-26660.0
45QQ
0.133;-30980.0
45KK
0.211;-29660.0
6(469)
0.183;-31940.0
6J(46)
0.174;-30620.0
(4678)
0.118;-36260.0
(467Q)
0.137;-33620.0
7(469)
0.194;-35600.0
7J(46)
0.141;-34280.0
(4689)
0.114;-34940.0
(468K)
0.143;-32300.0
8T(46)
0.134;-34280.0
(46)(8K)
0.200;-27980.0
Q(469)
0.199;-32300.0
(46)(9J)
0.248;-28640.0
T(46T)
0.148;-28640.0
T(46J)
0.146;-32300.0
TK(46)
0.174;-30980.0
(46)(JQ)
0.178;-26660.0
QQ(46)
0.162;-26000.0
46(67)
0.179;-33260.0
66(4T)
0.154;-31280.0
466Q
0.159;-34280.0
68(47)
0.159;-36260.0
(47)(6J)
0.209;-29960.0
47(67)
0.176;-32600.0
4(67T)
0.120;-34940.0
(67)(4K)
0.178;-28640.0
67(49)
0.157;-35600.0
67(4J)
0.162;-34280.0
67(4K)
0.198;-32960.0
69(48)
0.174;-34940.0
(48)(6Q)
0.231;-28640.0
49(68)
0.144;-34940.0
4(68Q)
0.159;-32960.0
46(89)
0.152;-34940.0
46(8J)
0.169;-33620.0
46(8K)
0.194;-32300.0
(49)(6J)
0.214;-28640.0
49(69)
0.188;-29960.0
4(69Q)
0.192;-32300.0
46(9T)
0.168;-33620.0
46(9Q)
0.166;-32300.0
6(4TJ)
0.177;-32300.0
6K(4T)
0.160;-30980.0
(6T)(4K)
0.179;-26660.0
6T(4Q)
0.185;-31640.0
(4J)(6J)
0.218;-23000.0
4J(6J)
0.143;-27320.0
6J(4Q)
0.143;-30980.0
(4Q)(6Q)
0.269;-21680.0
4K(6Q)
0.153;-29660.0
4K(6K)
0.229;-24680.0
79(47)
0.167;-30620.0
(47)(7Q)
0.208;-24320.0
(478T)
0.127;-33620.0
88(47)
0.167;-30620.0
(47)(8J)
0.153;-28640.0
9(479)
0.217;-29300.0
K(479)
0.197;-30980.0
9(47Q)
0.165;-31640.0
J(47T)
0.136;-31640.0
TJ(47)
0.147;-31640.0
(47JQ)
0.195;-30320.0
J(47K)
0.152;-29660.0
(47)(QK)
0.151;-24680.0
77(49)
0.164;-30620.0
477J
0.131;-33620.0
78(48)
0.185;-30620.0
(48)(7J)
0.187;-28640.0
48(78)
0.211;-30620.0
4(78J)
0.135;-32960.0
4788
0.152;-34940.0
478T
0.167;-37940.0
478Q
0.135;-36620.0
(49)(7T)
0.159;-28640.0
7(49K)
0.189;-30980.0
4(79J)
0.177;-32300.0
4799
0.127;-33620.0
479J
0.195;-36620.0
479K
0.181;-35300.0
7Q(4T)
0.158;-30980.0
(7T)(4Q)
0.215;-26660.0
4T(7J)
0.160;-31640.0
4T(7K)
0.144;-30320.0
7(4JK)
0.153;-29660.0
4(7JK)
0.180;-29660.0
4J(7K)
0.168;-29660.0
4Q(7Q)
0.201;-25340.0
47QK
0.116;-33320.0
89(48)
0.209;-29300.0
(48)(8Q)
0.235;-23000.0
(489J)
0.214;-31640.0
(48)(9T)
0.215;-27980.0
9(48K)
0.211;-30320.0
(48TK)
0.173;-29660.0
TQ(48)
0.173;-30320.0
K(48J)
0.149;-29000.0
Q(48Q)
0.202;-24680.0
KK(48)
0.199;-23360.0
88(4J)
0.219;-27980.0
488K
0.172;-30980.0
8J(49)
0.148;-31640.0
(89)(4T)
0.177;-27980.0
4Q(89)
0.147;-30980.0
489T
0.135;-36620.0
489Q
0.167;-35300.0
(4T)(8J)
0.248;-26660.0
4T(8T)
0.234;-27320.0
4(8TK)
0.226;-29660.0
4T(8Q)
0.166;-30320.0
8J(4J)
0.238;-26000.0
(8J)(4Q)
0.187;-25340.0
4J(8Q)
0.150;-29660.0
8Q(4Q)
0.198;-24680.0
48QQ
0.206;-29000.0
48KK
0.192;-27680.0
9(49Q)
0.163;-26000.0
J(49T)
0.172;-30320.0
TJ(49)
0.134;-30320.0
(49JQ)
0.217;-29000.0
J(49K)
0.163;-28340.0
(49)(QK)
0.197;-23360.0
99(4J)
0.238;-26660.0
499K
0.188;-29660.0
9Q(4T)
0.218;-29660.0
(9T)(4Q)
0.194;-25340.0
4T(9J)
0.223;-30320.0
4T(9K)
0.237;-29000.0
9(4JK)
0.159;-28340.0
4(9JK)
0.161;-28340.0
4J(9K)
0.182;-28340.0
4Q(9Q)
0.166;-24020.0
49QK
0.203;-32000.0
TJ(4T)
0.181;-25340.0
(4TJQ)
0.161;-28340.0
J(4TK)
0.164;-27680.0
(4T)(QK)
0.245;-22700.0
TT(4Q)
0.158;-24680.0
T(4JQ)
0.140;-28340.0
4(TJQ)
0.188;-28340.0
4T(JQ)
0.175;-28340.0
T(4QK)
0.226;-27020.0
TQ(4K)
0.210;-27020.0
JJ(4J)
0.230;-19700.0
(4JQK)
0.215;-26360.0
4JJJ
0.212;-24020.0
JQ(4Q)
0.209;-22700.0
4JQQ
0.180;-27020.0
4JKK
0.224;-25700.0
QQ(4K)
0.230;-21380.0
4KKK
0.214;-20060.0
55(59)
0.181;-28280.0
55(5K)
0.170;-25640.0
(56)(58)
0.216;-28280.0
5(56J)
0.202;-30620.0
5K(56)
0.217;-29300.0
56(59)
0.152;-31940.0
556J
0.160;-34940.0
57(57)
0.194;-28280.0
(57)(5T)
0.198;-26300.0
5(57K)
0.199;-28640.0
55(79)
0.196;-31280.0
57(5Q)
0.195;-29300.0
5(589)
0.156;-30620.0
5J(58)
0.179;-29300.0
58(59)
0.223;-30620.0
558J
0.128;-33620.0
59(59)
0.238;-25640.0
(59)(5Q)
0.232;-23660.0
559T
0.191;-33620.0
55(9K)
0.231;-27320.0
(5T)(5Q)
0.225;-23000.0
55TJ
0.156;-32300.0
5J(5J)
0.250;-23000.0
5J(5Q)
0.239;-26660.0
5(5QK)
0.183;-25340.0
5K(5K)
0.218;-20360.0
68(56)
0.173;-31940.0
(56)(6J)
0.199;-25640.0
7(567)
0.195;-31940.0
J(567)
0.180;-33620.0
78(56)
0.143;-35600.0
(56)(7J)
0.159;-29300.0
8(568)
0.188;-30620.0
Q(568)
0.132;-32300.0
(56)(8T)
0.160;-29300.0
8(56K)
0.153;-31640.0
(569Q)
0.138;-31640.0
9(56J)
0.161;-32300.0
9K(56)
0.180;-30980.0
TT(56)
0.177;-27980.0
(56)(TK)
0.176;-26000.0
J(56Q)
0.211;-30320.0
K(56Q)
0.204;-29000.0
66(57)
0.193;-32600.0
5669
0.142;-35600.0
56(6Q)
0.174;-29300.0
(57)(68)
0.196;-31280.0
6(57J)
0.195;-33620.0
6K(57)
0.125;-32300.0
(67)(5T)
0.185;-29960.0
5Q(67)
0.145;-32960.0
5678
0.119;-39920.0
567T
0.151;-38600.0
567Q
0.136;-37280.0
(58)(69)
0.165;-29960.0
6(58Q)
0.160;-32300.0
5(689)
0.167;-34280.0
(68)(5Q)
0.235;-27980.0
58(69)
0.174;-34280.0
58(6J)
0.125;-32960.0
58(6K)
0.157;-31640.0
6(59J)
0.164;-32300.0
6K(59)
0.182;-30980.0
(69)(5Q)
0.202;-27320.0
59(6T)
0.220;-32960.0
59(6Q)
0.160;-31640.0
6T(5T)
0.175;-27980.0
(5T)(6K)
0.228;-26000.0
5Q(6T)
0.187;-30980.0
56TJ
0.147;-35960.0
56TK
0.181;-34640.0
6K(5J)
0.181;-29660.0
56JJ
0.195;-30980.0
56JK
0.155;-33980.0
5(6QK)
0.219;-29000.0
6K(5K)
0.247;-24020.0
(57)(79)
0.191;-25640.0
7(57Q)
0.192;-27980.0
9(578)
0.178;-33620.0
K(578)
0.189;-30980.0
8(57J)
0.190;-32300.0
8K(57)
0.196;-30980.0
(579K)
0.191;-30320.0
9J(57)
0.192;-31640.0
(57TJ)
0.155;-30980.0
(57)(TJ)
0.144;-26660.0
J(57J)
0.226;-26000.0
JQ(57)
0.186;-29660.0
Q(57K)
0.187;-28340.0
5778
0.128;-34940.0
57(7J)
0.179;-28640.0
(58)(78)
0.223;-25640.0
7(58J)
0.161;-32300.0
7K(58)
0.220;-30980.0
(78)(5J)
0.147;-27980.0
5K(78)
0.176;-30980.0
57(8T)
0.175;-32960.0
57(8Q)
0.192;-31640.0
7(59T)
0.177;-32300.0
7Q(59)
0.141;-30980.0
(79)(5J)
0.232;-27320.0
5K(79)
0.181;-30320.0
57(9J)
0.162;-31640.0
57(9K)
0.186;-30320.0
(5T)(7Q)
0.192;-26000.0
5J(7T)
0.183;-30980.0
7T(5J)
0.197;-30980.0
7T(5K)
0.150;-29660.0
7Q(5J)
0.146;-29660.0
(7J)(5K)
0.211;-24680.0
7J(5K)
0.187;-29000.0
7K(5Q)
0.202;-28340.0
57(QK)
0.196;-28340.0
(58)(89)
0.191;-24320.0
8(58Q)
0.241;-26660.0
T(589)
0.156;-31640.0
9(58T)
0.165;-31640.0
9Q(58)
0.165;-30320.0
Q(58T)
0.155;-29660.0
(58)(TQ)
0.198;-25340.0
(58JK)
0.203;-28340.0
JK(58)
0.138;-28340.0
K(58K)
0.272;-22700.0
588T
0.190;-32300.0
58(8K)
0.199;-26000.0
(59)(8J)
0.177;-26660.0
59(89)
0.180;-27980.0
5(89Q)
0.163;-30320.0
58(9T)
0.140;-31640.0
58(9Q)
0.182;-30320.0
8(5TJ)
0.183;-30320.0
8K(5T)
0.176;-29000.0
(8T)(5K)
0.230;-24680.0
8T(5Q)
0.173;-29660.0
(5J)(8J)
0.225;-21020.0
5J(8J)
0.194;-25340.0
8J(5Q)
0.178;-29000.0
(5Q)(8Q)
0.278;-19700.0
5K(8Q)
0.170;-27680.0
5K(8K)
0.182;-22700.0
9J(59)
0.213;-26000.0
(59TJ)
0.199;-29660.0
(59)(TJ)
0.235;-25340.0
J(59J)
0.225;-24680.0
JQ(59)
0.182;-28340.0
Q(59K)
0.183;-27020.0
599T
0.182;-30980.0
59(9K)
0.162;-24680.0
(5T)(9Q)
0.248;-24680.0
5J(9T)
0.211;-29660.0
9T(5J)
0.207;-29660.0
9T(5K)
0.183;-28340.0
9Q(5J)
0.211;-28340.0
(9J)(5K)
0.274;-23360.0
9J(5K)
0.214;-27680.0
9K(5Q)
0.223;-27020.0
59(QK)
0.182;-27020.0
(5T)(TJ)
0.258;-20360.0
J(5TJ)
0.224;-24020.0
JQ(5T)
0.238;-27680.0
Q(5TK)
0.200;-26360.0
5TTJ
0.180;-29000.0
TJ(5J)
0.180;-24020.0
(TJ)(5Q)
0.158;-23360.0
5J(TQ)
0.212;-27680.0
TQ(5Q)
0.262;-22700.0
5TQQ
0.185;-27020.0
5TKK
0.204;-25700.0
Q(5JQ)
0.247;-22040.0
KK(5J)
0.238;-20720.0
(5Q)(JQ)
0.267;-17720.0
5K(JQ)
0.170;-25700.0
5K(JK)
0.199;-20720.0
5QQQ
0.210;-21380.0
KK(5K)
0.287;-15080.0
6669
0.134;-30620.0
666K
0.185;-27980.0
69(67)
0.200;-29960.0
(67)(6Q)
0.255;-23660.0
6678
0.150;-34940.0
66(7J)
0.205;-28640.0
(68)(68)
0.271;-21320.0
6(68J)
0.209;-27980.0
6K(68)
0.201;-26660.0
68(6J)
0.181;-27980.0
668K
0.153;-30980.0
6J(69)
0.169;-27320.0
69(6T)
0.229;-27980.0
669Q
0.155;-30980.0
6J(6T)
0.196;-26660.0
6T(6J)
0.217;-26660.0
66TK
0.157;-29660.0
6K(6J)
0.207;-24680.0
(6Q)(6Q)
0.243;-16040.0
66QK
0.206;-28340.0
7(679)
0.230;-29300.0
7J(67)
0.173;-27980.0
(6789)
0.182;-32960.0
(678K)
0.138;-30320.0
8T(67)
0.194;-32300.0
(67)(8K)
0.180;-26000.0
Q(679)
0.128;-30320.0
(67)(9J)
0.198;-26660.0
T(67T)
0.248;-26660.0
T(67J)
0.139;-30320.0
TK(67)
0.148;-29000.0
(67)(JQ)
0.204;-24680.0
QQ(67)
0.186;-24020.0
67(78)
0.182;-29960.0
77(6J)
0.166;-27980.0
677K
0.168;-30980.0
7T(68)
0.169;-32300.0
(68)(7K)
0.186;-26000.0
6T(78)
0.149;-32300.0
6(78K)
0.207;-30320.0
68(7T)
0.189;-32300.0
68(7Q)
0.182;-30980.0
79(69)
0.138;-27980.0
(69)(7Q)
0.199;-26000.0
6T(79)
0.210;-31640.0
6(79K)
0.185;-29660.0
69(7J)
0.169;-30980.0
69(7K)
0.141;-29660.0
7(6TQ)
0.142;-29660.0
6(7TJ)
0.180;-30320.0
67TT
0.161;-30980.0
67TQ
0.138;-33980.0
(6J)(7Q)
0.198;-24680.0
6Q(7J)
0.153;-29000.0
67JQ
0.153;-33320.0
(6Q)(7K)
0.210;-23360.0
6Q(7K)
0.148;-27680.0
8(689)
0.189;-27980.0
8J(68)
0.222;-26660.0
(689T)
0.223;-30980.0
99(68)
0.207;-27320.0
(68)(9Q)
0.251;-25340.0
(68TQ)
0.172;-29000.0
T(68Q)
0.183;-29000.0
Q(68J)
0.176;-28340.0
(68)(JK)
0.200;-23360.0
QK(68)
0.160;-27020.0
68(8T)
0.194;-27320.0
88(6K)
0.184;-25340.0
8(69J)
0.139;-30320.0
8K(69)
0.165;-29000.0
(89)(6Q)
0.185;-25340.0
69(8T)
0.146;-30980.0
69(8Q)
0.159;-29660.0
8T(6T)
0.234;-26000.0
(6T)(8K)
0.189;-24020.0
6Q(8T)
0.191;-29000.0
68TJ
0.135;-33980.0
68TK
0.139;-32660.0
8K(6J)
0.176;-27680.0
68JJ
0.221;-29000.0
68JK
0.145;-32000.0
6(8QK)
0.218;-27020.0
8K(6K)
0.277;-22040.0
(69)(9J)
0.243;-21020.0
T(69T)
0.220;-25340.0
T(69J)
0.168;-29000.0
TK(69)
0.190;-27680.0
(69)(JQ)
0.197;-23360.0
QQ(69)
0.230;-22700.0
69(9T)
0.185;-26000.0
99(6K)
0.204;-24020.0
9(6TQ)
0.237;-28340.0
6(9TJ)
0.223;-29000.0
69TT
0.158;-29660.0
69TQ
0.146;-32660.0
(6J)(9Q)
0.232;-23360.0
6Q(9J)
0.203;-27680.0
69JQ
0.190;-32000.0
(6Q)(9K)
0.214;-22040.0
6Q(9K)
0.228;-26360.0
T(6TJ)
0.200;-24020.0
TK(6T)
0.220;-22700.0
(6T)(JQ)
0.206;-22700.0
QQ(6T)
0.226;-22040.0
6T(TJ)
0.185;-24020.0
(6J)(TJ)
0.200;-19040.0
6J(TJ)
0.182;-23360.0
TJ(6Q)
0.207;-27020.0
(6Q)(TQ)
0.276;-17720.0
6K(TQ)
0.237;-25700.0
6K(TK)
0.209;-20720.0
JK(6J)
0.202;-21380.0
K(6JK)
0.258;-20060.0
6JJK
0.204;-25700.0
6(JQK)
0.201;-25040.0
JK(6K)
0.198;-20060.0
KK(6Q)
0.298;-19400.0
6QKK
0.209;-23720.0
77(7T)
0.198;-23660.0
(78)(78)
0.199;-20000.0
7(78J)
0.174;-26660.0
7K(78)
0.161;-25340.0
78(7J)
0.178;-26660.0
778K
0.169;-29660.0
7J(79)
0.204;-26000.0
79(7T)
0.185;-26660.0
779Q
0.215;-29660.0
7J(7T)
0.185;-25340.0
7T(7J)
0.208;-25340.0
77TK
0.216;-28340.0
7K(7J)
0.209;-23360.0
(7Q)(7Q)
0.240;-14720.0
77QK
0.222;-27020.0
8(78T)
0.142;-26660.0
8Q(78)
0.201;-25340.0
J(789)
0.171;-29660.0
9T(78)
0.178;-30320.0
(78)(9K)
0.173;-24020.0
K(78T)
0.175;-27680.0
T(78K)
0.218;-27680.0
JJ(78)
0.181;-24020.0
(78QK)
0.220;-26360.0
7888
0.159;-27980.0
78(8J)
0.204;-26000.0
(79)(89)
0.206;-22340.0
8(79Q)
0.171;-29000.0
7(89T)
0.197;-30320.0
(89)(7K)
0.212;-24020.0
89(7J)
0.204;-29660.0
89(7K)
0.193;-28340.0
8J(7T)
0.215;-29000.0
(8T)(7J)
0.190;-24680.0
7K(8T)
0.208;-27680.0
78(TQ)
0.166;-28340.0
8(7JQ)
0.181;-27680.0
7(8JQ)
0.176;-27680.0
78(JQ)
0.238;-27680.0
8(7QK)
0.204;-26360.0
8Q(7K)
0.177;-26360.0
99(79)
0.280;-21680.0
(79)(9Q)
0.290;-19700.0
(79TQ)
0.247;-27680.0
T(79Q)
0.189;-27680.0
Q(79J)
0.190;-27020.0
(79)(JK)
0.200;-22040.0
QK(79)
0.231;-25700.0
79(9J)
0.186;-24680.0
(7T)(9T)
0.259;-20360.0
9(7TK)
0.172;-27020.0
7(9TQ)
0.207;-27680.0
79(TJ)
0.190;-28340.0
79(TK)
0.171;-27020.0
(7J)(9K)
0.213;-22040.0
7K(9J)
0.199;-26360.0
79(JK)
0.159;-26360.0
(9Q)(7K)
0.222;-21380.0
(7K)(9K)
0.286;-16400.0
T(7TQ)
0.262;-22700.0
Q(7TJ)
0.153;-26360.0
(7T)(JK)
0.233;-21380.0
QK(7T)
0.187;-25040.0
7T(TQ)
0.223;-22700.0
(7J)(TQ)
0.218;-22040.0
7Q(TJ)
0.182;-26360.0
7TJQ
0.153;-30680.0
(7Q)(TK)
0.237;-20720.0
7Q(TK)
0.199;-25040.0
J(7JQ)
0.215;-21380.0
K(7JQ)
0.212;-24380.0
JJ(7Q)
0.223;-21380.0
J(7QK)
0.157;-24380.0
JQ(7K)
0.191;-24380.0
QQ(7Q)
0.301;-15740.0
7Q(QK)
0.238;-19400.0
8888
0.180;-23000.0
888Q
0.222;-24680.0
8(89J)
0.208;-24680.0
8K(89)
0.215;-23360.0
89(8Q)
0.237;-24020.0
8(8TJ)
0.182;-24020.0
8K(8T)
0.202;-22700.0
8T(8K)
0.166;-22700.0
8(8JK)
0.232;-22040.0
88(JK)
0.196;-22040.0
8Q(8K)
0.214;-21380.0
(89)(9T)
0.182;-20360.0
9(89K)
0.163;-22700.0
(89TK)
0.225;-26360.0
TQ(89)
0.224;-27020.0
K(89J)
0.194;-25700.0
Q(89Q)
0.225;-21380.0
KK(89)
0.220;-20060.0
99(8Q)
0.207;-23360.0
9(8TJ)
0.176;-27680.0
9K(8T)
0.174;-26360.0
(9T)(8K)
0.210;-22040.0
9T(8Q)
0.235;-27020.0
(8J)(9J)
0.221;-18380.0
8J(9J)
0.195;-22700.0
9J(8Q)
0.179;-26360.0
(8Q)(9Q)
0.274;-17060.0
8K(9Q)
0.160;-25040.0
8K(9K)
0.221;-20060.0
TQ(8T)
0.200;-22040.0
K(8TJ)
0.207;-25040.0
Q(8TQ)
0.259;-20720.0
KK(8T)
0.293;-19400.0
