AAAA
0.462;495.0
5AAA
0.286;174.4
9AAA
0.398;256.9
KAAA
0.388;339.4
4A(2A)
0.283;-93.7
(2A)(7A)
0.311;103.1
A(2TA)
0.321;30.0
QA(2A)
0.306;71.3
2A(4A)
0.262;-93.7
26AA
0.312;-187.5
AA(29)
0.255;9.4
2A(QA)
0.341;71.3
A(34A)
0.283;-73.1
6A(3A)
0.285;-31.9
(3A)(9A)
0.285;165.0
A(3QA)
0.296;91.9
AA(34)
0.261;-73.1
3A(7A)
0.329;-11.2
39AA
0.244;-105.0
AA(3Q)
0.369;91.9
(4A)(5A)
0.354;103.1
A(48A)
0.342;30.0
TA(4A)
0.315;71.3
(4A)(KA)
0.306;268.1
46AA
0.309;-146.2
AA(49)
0.284;50.6
4A(QA)
0.356;112.5
A(56A)
0.326;9.4
8A(5A)
0.316;50.6
(5A)(JA)
0.321;247.5
55AA
0.334;-11.2
AA(58)
0.336;50.6
5A(JA)
0.270;112.5
5KAA
0.359;18.7
8A(6A)
0.361;71.3
(6A)(JA)
0.356;268.1
66AA
0.300;30.0
AA(69)
0.281;91.9
6A(QA)
0.358;153.7
A(78A)
0.305;91.9
TA(7A)
0.354;133.1
(7A)(KA)
0.384;330.0
79AA
0.294;-22.5
AA(7Q)
0.385;174.4
(8A)(9A)
0.351;268.1
A(8QA)
0.331;195.0
AA(89)
0.344;133.1
8A(QA)
0.295;195.0
A(9TA)
0.375;174.4
QA(9A)
0.328;215.6
9A(JA)
0.326;195.0
9KAA
0.299;101.3
QA(TA)
0.315;236.2
TA(QA)
0.359;236.2
A(JQA)
0.360;256.9
AA(JQ)
0.375;256.9
(QA)(KA)
0.403;433.1
KKAA
0.410;318.8
2(25A)
0.241;-320.6
27(2A)
0.265;-279.4
(2T)(2A)
0.309;-82.5
2(2KA)
0.292;-155.6
(236A)
0.228;-414.4
(23TA)
0.254;-331.9
33(2A)
0.266;-341.2
(36)(2A)
0.303;-279.4
3(29A)
0.264;-352.5
3J(2A)
0.309;-311.2
(245A)
0.300;-414.4
(249A)
0.232;-331.9
(24KA)
0.249;-249.4
46(2A)
0.230;-393.8
(49)(2A)
0.253;-196.9
4(2QA)
0.240;-270.0
6(25A)
0.233;-373.1
T(25A)
0.230;-290.6
5(26A)
0.231;-373.1
58(2A)
0.251;-331.9
(5J)(2A)
0.290;-135.0
6(26A)
0.269;-217.5
T(26A)
0.262;-270.0
6(27A)
0.303;-331.9
69(2A)
0.285;-290.6
(6Q)(2A)
0.292;-93.8
(279A)
0.207;-270.0
(27KA)
0.299;-187.5
79(2A)
0.262;-270.0
(7Q)(2A)
0.319;-73.1
(28TA)
0.283;-228.7
88(2A)
0.236;-135.0
(8J)(2A)
0.314;-73.1
9(29A)
0.308;-93.7
K(29A)
0.272;-146.2
9(2QA)
0.226;-166.9
J(2TA)
0.303;-166.9
TJ(2A)
0.247;-166.9
(2JQA)
0.257;-125.6
J(2KA)
0.228;-105.0
(QK)(2A)
0.367;50.6
22(4A)
0.263;-341.2
226A
0.215;-435.0
2A(29)
0.286;-238.1
22(QA)
0.275;-176.2
2(34A)
0.211;-455.6
26(3A)
0.290;-414.4
(29)(3A)
0.218;-217.5
2(3QA)
0.270;-290.6
A(234)
0.187;-455.6
(23)(7A)
0.225;-258.8
9A(23)
0.275;-352.5
A(23Q)
0.266;-290.6
2A(34)
0.286;-455.6
2A(36)
0.244;-414.4
2A(38)
0.213;-373.1
2A(3T)
0.253;-331.9
2A(3Q)
0.304;-290.6
2(45A)
0.259;-414.4
27(4A)
0.229;-373.1
(2T)(4A)
0.263;-176.2
2(4KA)
0.252;-249.4
A(246)
0.290;-393.8
(24)(9A)
0.297;-196.9
JA(24)
0.294;-290.6
24(5A)
0.247;-414.4
24(7A)
0.223;-373.1
24(9A)
0.299;-331.9
24(JA)
0.285;-290.6
24(KA)
0.236;-249.4
26(5A)
0.246;-373.1
(29)(5A)
0.247;-176.2
2(5QA)
0.274;-249.4
A(256)
0.209;-373.1
(25)(9A)
0.344;-176.2
JA(25)
0.249;-270.0
25(6A)
0.294;-373.1
25(8A)
0.274;-331.9
25(TA)
0.250;-290.6
25(QA)
0.257;-249.4
(26)(6A)
0.233;-82.5
2(69A)
0.270;-290.6
2J(6A)
0.294;-249.4
(26)(7A)
0.243;-196.9
9A(26)
0.258;-290.6
A(26Q)
0.262;-228.7
2A(67)
0.197;-331.9
2A(69)
0.287;-290.6
2A(6J)
0.321;-249.4
2A(6K)
0.294;-208.1
(29)(7A)
0.304;-135.0
2(7QA)
0.331;-208.1
A(278)
0.220;-290.6
(27)(JA)
0.319;-93.8
KA(27)
0.266;-187.5
2A(79)
0.328;-270.0
2A(7J)
0.316;-228.7
2A(7K)
0.292;-187.5
(2T)(8A)
0.290;-93.8
2(8KA)
0.243;-166.9
A(28T)
0.280;-228.7
(28)(KA)
0.314;-31.9
28(TA)
0.332;-228.7
28(QA)
0.278;-187.5
(29)(9A)
0.317;41.3
2(9QA)
0.235;-166.9
A(29T)
0.214;-208.1
(29)(KA)
0.311;-11.2
29(JA)
0.236;-187.5
29(KA)
0.342;-146.2
2J(TA)
0.278;-166.9
(2T)(JA)
0.264;-31.9
KA(2T)
0.296;-125.6
2A(TQ)
0.255;-146.2
2(JQA)
0.282;-125.6
A(2JQ)
0.272;-125.6
2A(JQ)
0.241;-125.6
2(QKA)
0.273;-84.4
2Q(KA)
0.302;-84.4
33(3A)
0.279;-185.6
(36)(3A)
0.237;-123.7
3(39A)
0.281;-196.9
3J(3A)
0.256;-155.6
(345A)
0.213;-393.8
(349A)
0.299;-311.2
(34KA)
0.265;-228.7
46(3A)
0.268;-373.1
(49)(3A)
0.253;-176.2
4(3QA)
0.290;-249.4
6(35A)
0.245;-352.5
T(35A)
0.223;-270.0
5(36A)
0.228;-352.5
58(3A)
0.241;-311.2
(5J)(3A)
0.335;-114.4
6(36A)
0.323;-196.9
T(36A)
0.258;-249.4
6(37A)
0.261;-311.2
69(3A)
0.269;-270.0
(6Q)(3A)
0.284;-73.1
(379A)
0.274;-249.4
(37KA)
0.235;-166.9
79(3A)
0.242;-249.4
(7Q)(3A)
0.306;-52.5
(38TA)
0.304;-208.1
88(3A)
0.331;-114.4
(8J)(3A)
0.285;-52.5
9(39A)
0.339;-73.1
K(39A)
0.321;-125.6
9(3QA)
0.310;-146.2
J(3TA)
0.228;-146.2
TJ(3A)
0.281;-146.2
(3JQA)
0.234;-105.0
J(3KA)
0.298;-84.4
(QK)(3A)
0.302;71.3
33(5A)
0.268;-279.4
337A
0.311;-373.1
3A(3T)
0.309;-176.2
33(KA)
0.281;-114.4
3(46A)
0.223;-373.1
38(4A)
0.221;-331.9
(3J)(4A)
0.306;-135.0
4A(34)
0.280;-279.4
A(347)
0.252;-352.5
(34)(TA)
0.319;-155.6
QA(34)
0.287;-249.4
345A
0.255;-528.7
347A
0.254;-487.5
349A
0.185;-446.2
34JA
0.204;-405.0
34KA
0.239;-363.7
37(5A)
0.222;-331.9
(3T)(5A)
0.305;-135.0
3(5KA)
0.232;-208.1
A(357)
0.204;-331.9
(35)(TA)
0.283;-135.0
QA(35)
0.218;-228.7
356A
0.192;-487.5
358A
0.217;-446.2
35TA
0.222;-405.0
35QA
0.273;-363.7
(37)(6A)
0.287;-176.2
3(6TA)
0.236;-249.4
3Q(6A)
0.249;-208.1
(36)(8A)
0.331;-155.6
TA(36)
0.220;-249.4
A(36K)
0.278;-187.5
6A(38)
0.254;-290.6
6A(3T)
0.212;-249.4
6A(3Q)
0.294;-208.1
37(7A)
0.287;-155.6
(3T)(7A)
0.324;-93.8
3(7KA)
0.264;-166.9
A(379)
0.212;-249.4
(37)(QA)
0.296;-52.5
7A(38)
0.318;-270.0
7A(3T)
0.233;-228.7
7A(3Q)
0.283;-187.5
38(8A)
0.296;-114.4
(3J)(8A)
0.323;-52.5
8A(38)
0.304;-114.4
A(38J)
0.298;-187.5
388A
0.275;-249.4
38TA
0.215;-343.1
38QA
0.213;-301.9
(3T)(9A)
0.386;-52.5
3(9KA)
0.285;-125.6
A(39J)
0.298;-166.9
399A
0.259;-208.1
39JA
0.250;-301.9
39KA
0.260;-260.6
3Q(TA)
0.283;-125.6
(3T)(QA)
0.326;9.4
TA(3J)
0.269;-146.2
TA(3K)
0.281;-105.0
3(JKA)
0.293;-84.4
A(3JK)
0.289;-84.4
JA(3K)
0.252;-84.4
QA(3Q)
0.283;50.6
3QKA
0.285;-198.7
45(4A)
0.304;-238.1
(48)(4A)
0.289;-41.3
4(4JA)
0.270;-114.4
4K(4A)
0.341;-73.1
(459A)
0.265;-270.0
(45KA)
0.316;-187.5
57(4A)
0.273;-311.2
(5T)(4A)
0.282;-114.4
5(4KA)
0.261;-187.5
(469A)
0.246;-249.4
(46KA)
0.297;-166.9
68(4A)
0.252;-270.0
(6J)(4A)
0.289;-73.1
7(47A)
0.292;-135.0
J(47A)
0.288;-187.5
78(4A)
0.268;-249.4
(7J)(4A)
0.281;-52.5
8(48A)
0.257;-93.7
Q(48A)
0.287;-146.2
(8T)(4A)
0.229;-52.5
8(4KA)
0.315;-125.6
(49QA)
0.301;-125.6
9(4JA)
0.264;-146.2
9K(4A)
0.323;-105.0
TT(4A)
0.310;-11.2
(TK)(4A)
0.277;50.6
J(4QA)
0.341;-84.4
K(4QA)
0.276;-43.1
44(5A)
0.250;-238.1
447A
0.302;-331.9
4A(4T)
0.291;-135.0
44(KA)
0.275;-73.1
4(57A)
0.278;-311.2
49(5A)
0.212;-270.0
(4Q)(5A)
0.267;-73.1
6A(45)
0.240;-331.9
A(459)
0.297;-270.0
(45)(QA)
0.273;-73.1
5A(46)
0.238;-331.9
5A(48)
0.207;-290.6
5A(4T)
0.339;-249.4
5A(4Q)
0.221;-208.1
46(6A)
0.276;-176.2
(49)(6A)
0.328;-114.4
4(6QA)
0.341;-187.5
A(467)
0.220;-290.6
(46)(TA)
0.228;-93.8
QA(46)
0.259;-187.5
467A
0.260;-425.6
469A
0.307;-384.4
46JA
0.231;-343.1
46KA
0.284;-301.9
49(7A)
0.260;-228.7
(4Q)(7A)
0.324;-31.9
8A(47)
0.264;-249.4
A(47J)
0.236;-187.5
477A
0.303;-270.0
479A
0.242;-363.7
47JA
0.265;-322.5
47KA
0.310;-281.2
4T(8A)
0.335;-187.5
(4K)(8A)
0.253;9.4
TA(48)
0.278;-187.5
A(48K)
0.288;-125.6
8A(4T)
0.236;-187.5
8A(4Q)
0.288;-146.2
49(9A)
0.257;-52.5
(4Q)(9A)
0.270;9.4
TA(49)
0.338;-166.9
A(49K)
0.274;-105.0
9A(4J)
0.279;-146.2
9A(4K)
0.319;-105.0
4(TQA)
0.284;-105.0
A(4TJ)
0.302;-125.6
4TTA
0.298;-146.2
4TQA
0.272;-240.0
(4Q)(JA)
0.343;50.6
QA(4J)
0.246;-84.4
4JQA
0.239;-219.4
(4K)(QA)
0.325;91.9
QA(4K)
0.316;-43.1
5(56A)
0.251;-176.2
58(5A)
0.326;-135.0
(5J)(5A)
0.268;61.9
6(56A)
0.280;-155.6
T(56A)
0.309;-208.1
6(57A)
0.221;-270.0
69(5A)
0.228;-228.7
(6Q)(5A)
0.365;-31.9
(579A)
0.316;-208.1
(57KA)
0.311;-125.6
79(5A)
0.325;-208.1
(7Q)(5A)
0.350;-11.2
(58TA)
0.287;-166.9
88(5A)
0.272;-73.1
(8J)(5A)
0.273;-11.2
9(59A)
0.276;-31.9
K(59A)
0.291;-84.4
9(5QA)
0.295;-105.0
J(5TA)
0.269;-105.0
TJ(5A)
0.254;-105.0
(5JQA)
0.302;-63.7
J(5KA)
0.319;-43.1
(QK)(5A)
0.343;112.5
55(7A)
0.360;-155.6
559A
0.284;-249.4
5A(5Q)
0.353;-52.5
(57)(6A)
0.248;-135.0
5(6TA)
0.268;-208.1
5Q(6A)
0.319;-166.9
(56)(8A)
0.283;-114.4
TA(56)
0.306;-208.1
A(56K)
0.285;-146.2
6A(58)
0.238;-249.4
6A(5T)
0.311;-208.1
6A(5Q)
0.263;-166.9
57(7A)
0.284;-114.4
(5T)(7A)
0.285;-52.5
5(7KA)
0.255;-125.6
A(579)
0.240;-208.1
(57)(QA)
0.296;-11.2
7A(58)
0.249;-228.7
7A(5T)
0.307;-187.5
7A(5Q)
0.244;-146.2
58(8A)
0.349;-73.1
(5J)(8A)
0.305;-11.2
8A(58)
0.290;-73.1
A(58J)
0.328;-146.2
588A
0.252;-208.1
58TA
0.244;-301.9
58QA
0.269;-260.6
(5T)(9A)
0.251;-11.2
5(9KA)
0.302;-84.4
A(59J)
0.262;-125.6
599A
0.254;-166.9
59JA
0.207;-260.6
59KA
0.287;-219.4
5Q(TA)
0.346;-84.4
(5T)(QA)
0.343;50.6
TA(5J)
0.362;-105.0
TA(5K)
0.277;-63.7
5(JKA)
0.289;-43.1
A(5JK)
0.298;-43.1
JA(5K)
0.379;-43.1
QA(5Q)
0.368;91.9
5QKA
0.274;-157.5
67(6A)
0.292;-114.4
(6T)(6A)
0.338;82.5
6(6KA)
0.328;9.4
(67TA)
0.258;-166.9
77(6A)
0.322;-93.7
(7T)(6A)
0.257;-31.9
7(6KA)
0.286;-105.0
(68JA)
0.301;-125.6
(89)(6A)
0.298;-31.9
8(6QA)
0.246;-105.0
T(69A)
0.281;-125.6
9(6TA)
0.293;-125.6
9Q(6A)
0.318;-84.4
Q(6TA)
0.300;-63.7
(TQ)(6A)
0.308;71.3
(6JKA)
0.317;-22.5
JK(6A)
0.362;-22.5
K(6KA)
0.278;153.7
668A
0.319;-228.7
6A(6J)
0.329;-31.9
(67)(7A)
0.262;41.3
6(7TA)
0.334;-166.9
6Q(7A)
0.295;-125.6
(67)(9A)
0.347;-52.5
JA(67)
0.276;-146.2
67(8A)
0.276;-208.1
67(TA)
0.293;-166.9
67(QA)
0.294;-125.6
(68)(8A)
0.305;82.5
6(8JA)
0.257;-125.6
6K(8A)
0.270;-84.4
(68)(JA)
0.260;9.4
KA(68)
0.307;-84.4
6A(8T)
0.270;-146.2
6A(8Q)
0.307;-105.0
6(9TA)
0.321;-125.6
6Q(9A)
0.278;-84.4
(69)(JA)
0.327;30.0
KA(69)
0.309;-63.7
6A(9J)
0.291;-105.0
6A(9K)
0.282;-63.7
(6Q)(TA)
0.265;71.3
JA(6T)
0.250;-84.4
6T(JA)
0.257;-84.4
6T(KA)
0.293;-43.1
6Q(JA)
0.330;-43.1
(6J)(KA)
0.355;112.5
6J(KA)
0.332;-22.5
6K(QA)
0.344;-1.9
6A(QK)
0.354;-1.9
(78)(7A)
0.368;82.5
7(7JA)
0.293;9.4
7K(7A)
0.270;50.6
(78QA)
0.340;-84.4
8(7TA)
0.267;-125.6
8Q(7A)
0.273;-84.4
J(79A)
0.281;-84.4
9T(7A)
0.333;-105.0
(9K)(7A)
0.281;91.9
K(7TA)
0.270;-22.5
T(7KA)
0.351;-22.5
JJ(7A)
0.388;91.9
(7QKA)
0.341;18.7
777A
0.234;-73.1
7A(7T)
0.312;-11.2
77(KA)
0.332;50.6
7(8TA)
0.257;-125.6
7Q(8A)
0.267;-84.4
(78)(TA)
0.246;9.4
QA(78)
0.312;-84.4
789A
0.238;-281.2
78JA
0.299;-240.0
78KA
0.310;-198.7
7J(9A)
0.291;-84.4
(79)(TA)
0.308;30.0
QA(79)
0.330;-63.7
79TA
0.256;-240.0
79QA
0.254;-198.7
(7J)(TA)
0.333;71.3
TA(7T)
0.311;50.6
A(7TK)
0.284;-22.5
TA(7Q)
0.304;-43.1
7J(JA)
0.259;91.9
(7J)(QA)
0.287;112.5
JA(7Q)
0.289;-22.5
7Q(QA)
0.360;133.1
7QQA
0.296;-1.9
7KKA
0.254;39.4
8(8JA)
0.365;50.6
8K(8A)
0.318;91.9
(89KA)
0.263;-22.5
9J(8A)
0.301;-63.7
(8TJA)
0.341;-43.1
(TJ)(8A)
0.356;91.9
J(8JA)
0.348;112.5
JQ(8A)
0.309;-1.9
Q(8KA)
0.368;39.4
889A
0.249;-125.6
8A(8Q)
0.398;71.3
(8T)(9A)
0.337;50.6
8(9KA)
0.283;-22.5
A(89J)
0.316;-63.7
899A
0.232;-105.0
89JA
0.263;-198.7
89KA
0.310;-157.5
8Q(TA)
0.338;-22.5
(8T)(QA)
0.331;112.5
TA(8J)
0.272;-43.1
TA(8K)
0.285;-1.9
8(JKA)
0.338;18.7
A(8JK)
0.334;18.7
JA(8K)
0.336;18.7
QA(8Q)
0.335;153.7
8QKA
0.313;-95.6
9T(9A)
0.390;71.3
(9K)(9A)
0.282;268.1
K(9TA)
0.271;18.7
T(9KA)
0.312;18.7
JJ(9A)
0.353;133.1
(9QKA)
0.342;60.0
999A
0.327;50.6
9A(9Q)
0.311;112.5
(9J)(TA)
0.360;112.5
TA(9T)
0.270;91.9
A(9TK)
0.283;18.7
TA(9Q)
0.347;-1.9
9J(JA)
0.321;133.1
(9J)(QA)
0.378;153.8
JA(9Q)
0.323;18.7
9Q(QA)
0.371;174.4
9QQA
0.340;39.4
9KKA
0.292;80.6
T(TKA)
0.358;174.4
JJ(TA)
0.405;153.7
(TQKA)
0.310;80.6
TTTA
0.301;112.5
TA(TK)
0.340;174.4
(TK)(JA)
0.411;195.0
KA(TJ)
0.278;60.0
TA(JK)
0.336;60.0
(TQ)(KA)
0.332;215.6
(TK)(KA)
0.345;371.3
J(JKA)
0.378;215.6
(QK)(JA)
0.349;236.3
JJ(KA)
0.339;215.6
QA(JQ)
0.417;215.6
JQKA
0.253;-33.7
QK(QA)
0.369;256.9
QK(KA)
0.421;277.5
22(24)
0.246;-453.8
22(28)
0.254;-371.2
22(2Q)
0.290;-288.7
24(23)
0.207;-568.1
(23)(27)
0.252;-371.3
2(23T)
0.228;-444.4
2Q(23)
0.298;-403.1
23(25)
0.191;-547.5
2237
0.251;-641.2
22(3T)
0.263;-444.4
23(2K)
0.278;-382.5
2(246)
0.221;-506.2
28(24)
0.196;-465.0
(24)(2J)
0.263;-268.1
2244
0.278;-547.5
22(47)
0.199;-485.6
24(2T)
0.267;-423.8
224Q
0.231;-517.5
26(25)
0.184;-485.6
(25)(29)
0.241;-288.7
2(25Q)
0.305;-361.9
22(56)
0.251;-485.6
25(29)
0.256;-423.8
225J
0.186;-517.5
26(26)
0.257;-330.0
(26)(29)
0.256;-268.1
2(26Q)
0.248;-341.2
22(67)
0.194;-444.4
26(2T)
0.261;-382.5
226Q
0.185;-476.2
28(27)
0.261;-403.1
(27)(2J)
0.301;-206.3
2277
0.249;-423.8
22(7T)
0.229;-361.9
27(2K)
0.240;-300.0
2(28T)
0.239;-341.2
2Q(28)
0.209;-300.0
28(2T)
0.195;-341.2
228Q
0.228;-435.0
2T(29)
0.250;-320.6
(29)(2K)
0.270;-123.7
229J
0.233;-435.0
2T(2T)
0.303;-165.0
(2T)(2K)
0.293;-103.1
22TQ
0.235;-393.8
2Q(2J)
0.290;-238.1
2J(2K)
0.242;-217.5
22QQ
0.324;-217.5
3(234)
0.215;-547.5
36(23)
0.224;-506.2
(23)(39)
0.271;-309.4
3(23Q)
0.195;-382.5
5(234)
0.169;-641.2
9(234)
0.204;-558.8
K(234)
0.267;-476.2
4(237)
0.188;-600.0
49(23)
0.194;-558.8
(23)(4Q)
0.213;-361.9
(2357)
0.212;-579.4
(235J)
0.210;-496.9
(23)(56)
0.239;-465.0
5(239)
0.181;-538.1
5J(23)
0.186;-496.9
(2367)
0.190;-558.8
(236J)
0.172;-476.2
(23)(67)
0.183;-423.8
6(23T)
0.188;-496.9
6Q(23)
0.175;-455.6
9(237)
0.256;-496.9
K(237)
0.266;-414.4
7(23T)
0.285;-476.2
7Q(23)
0.197;-435.0
T(238)
0.260;-455.6
8(239)
0.275;-476.2
8J(23)
0.212;-435.0
(239T)
0.219;-435.0
99(23)
0.277;-320.6
(23)(9Q)
0.257;-258.8
(23TQ)
0.268;-373.1
T(23Q)
0.213;-373.1
Q(23J)
0.227;-352.5
(23)(JK)
0.262;-196.9
QK(23)
0.225;-311.2
23(35)
0.200;-526.9
33(28)
0.231;-465.0
233T
0.207;-558.8
23(3K)
0.214;-361.9
(24)(36)
0.177;-485.6
3(249)
0.189;-558.8
3J(24)
0.243;-517.5
(34)(25)
0.188;-506.2
27(34)
0.224;-600.0
2(34T)
0.249;-538.1
(34)(2K)
0.266;-341.2
34(26)
0.192;-620.6
34(28)
0.192;-579.4
34(2T)
0.275;-538.1
34(2Q)
0.224;-496.9
(25)(35)
0.298;-350.6
3(258)
0.223;-558.8
3T(25)
0.196;-517.5
(25)(3K)
0.311;-320.6
27(35)
0.178;-579.4
2(35T)
0.239;-517.5
(35)(2K)
0.228;-320.6
35(27)
0.174;-579.4
35(29)
0.251;-538.1
35(2J)
0.203;-496.9
35(2K)
0.291;-455.6
37(26)
0.222;-558.8
(26)(3T)
0.218;-361.9
3(26K)
0.263;-435.0
2(368)
0.238;-538.1
(36)(2J)
0.224;-341.2
2K(36)
0.273;-435.0
23(68)
0.185;-538.1
23(6T)
0.268;-496.9
23(6Q)
0.279;-455.6
3(278)
0.253;-517.5
3T(27)
0.246;-476.2
(27)(3K)
0.235;-279.4
29(37)
0.212;-496.9
2(37Q)
0.272;-435.0
23(78)
0.229;-517.5
23(7T)
0.251;-476.2
23(7Q)
0.239;-435.0
3(289)
0.247;-476.2
3J(28)
0.190;-435.0
(38)(29)
0.239;-341.2
2J(38)
0.195;-435.0
38(29)
0.191;-476.2
38(2J)
0.201;-435.0
38(2K)
0.252;-393.8
3T(29)
0.287;-435.0
(29)(3K)
0.293;-238.1
2J(39)
0.271;-414.4
39(2T)
0.271;-435.0
39(2Q)
0.278;-393.8
(2T)(3T)
0.264;-144.4
3(2TK)
0.238;-352.5
2(3TQ)
0.224;-373.1
23(TJ)
0.248;-393.8
23(TK)
0.303;-352.5
(2J)(3K)
0.247;-196.9
2K(3J)
0.259;-331.9
23(JK)
0.252;-331.9
(3Q)(2K)
0.319;-176.2
(2K)(3K)
0.360;-20.6
4(246)
0.217;-465.0
48(24)
0.262;-423.8
(24)(4J)
0.289;-226.9
5(245)
0.197;-465.0
9(245)
0.232;-517.5
K(245)
0.199;-435.0
5(248)
0.260;-538.1
5T(24)
0.215;-496.9
(24)(5K)
0.303;-300.0
9(246)
0.206;-496.9
K(246)
0.262;-414.4
6(249)
0.258;-496.9
6J(24)
0.222;-455.6
(2478)
0.225;-496.9
(247Q)
0.248;-414.4
7(249)
0.174;-476.2
7J(24)
0.263;-435.0
(2489)
0.222;-455.6
(248K)
0.242;-373.1
8T(24)
0.213;-435.0
(24)(8K)
0.323;-238.1
Q(249)
0.233;-373.1
(24)(9J)
0.256;-258.8
T(24T)
0.230;-258.8
T(24J)
0.243;-373.1
TK(24)
0.231;-331.9
(24)(JQ)
0.301;-196.9
QQ(24)
0.310;-176.2
24(45)
0.208;-485.6
44(28)
0.218;-423.8
244T
0.184;-517.5
24(4K)
0.250;-320.6
(25)(47)
0.225;-423.8
4(25T)
0.181;-496.9
4Q(25)
0.263;-455.6
(45)(27)
0.230;-423.8
29(45)
0.179;-517.5
2(45Q)
0.236;-455.6
24(56)
0.220;-579.4
24(58)
0.163;-538.1
24(5T)
0.240;-496.9
24(5Q)
0.282;-455.6
4(267)
0.229;-538.1
49(26)
0.220;-496.9
(26)(4Q)
0.246;-300.0
27(46)
0.203;-538.1
2(46T)
0.191;-476.2
(46)(2K)
0.239;-279.4
46(28)
0.197;-517.5
46(2T)
0.218;-476.2
46(2Q)
0.228;-435.0
(27)(47)
0.282;-247.5
4(27T)
0.222;-455.6
4Q(27)
0.237;-414.4
(47)(29)
0.258;-341.2
2J(47)
0.233;-435.0
47(28)
0.288;-496.9
47(2T)
0.190;-455.6
47(2Q)
0.254;-414.4
(28)(48)
0.247;-206.3
4(28J)
0.215;-414.4
4K(28)
0.254;-373.1
(48)(2J)
0.241;-279.4
2K(48)
0.201;-373.1
24(8T)
0.202;-435.0
24(8Q)
0.248;-393.8
4(29T)
0.242;-414.4
4Q(29)
0.206;-373.1
(49)(2J)
0.246;-258.8
2K(49)
0.252;-352.5
24(9J)
0.252;-393.8
24(9K)
0.230;-352.5
(2T)(4Q)
0.271;-217.5
2J(4T)
0.204;-373.1
4T(2J)
0.253;-373.1
4T(2K)
0.231;-331.9
4Q(2J)
0.223;-331.9
(4J)(2K)
0.222;-176.2
4J(2K)
0.259;-311.2
4K(2Q)
0.241;-290.6
24(QK)
0.286;-290.6
(25)(56)
0.307;-288.7
5(259)
0.248;-361.9
5J(25)
0.251;-320.6
(2567)
0.236;-517.5
(256J)
0.233;-435.0
(25)(67)
0.222;-382.5
6(25T)
0.230;-455.6
6Q(25)
0.224;-414.4
9(257)
0.233;-455.6
K(257)
0.262;-373.1
7(25T)
0.224;-435.0
7Q(25)
0.214;-393.8
T(258)
0.253;-414.4
8(259)
0.276;-435.0
8J(25)
0.281;-393.8
(259T)
0.209;-393.8
99(25)
0.287;-279.4
(25)(9Q)
0.310;-217.5
(25TQ)
0.238;-331.9
T(25Q)
0.200;-331.9
Q(25J)
0.204;-311.2
(25)(JK)
0.250;-155.6
QK(25)
0.216;-270.0
25(57)
0.312;-403.1
55(2T)
0.234;-341.2
255Q
0.196;-435.0
57(26)
0.257;-517.5
(26)(5T)
0.247;-320.6
5(26K)
0.286;-393.8
2(568)
0.242;-496.9
(56)(2J)
0.253;-300.0
2K(56)
0.235;-393.8
25(68)
0.212;-496.9
25(6T)
0.220;-455.6
25(6Q)
0.241;-414.4
5(278)
0.205;-476.2
5T(27)
0.262;-435.0
(27)(5K)
0.293;-238.1
29(57)
0.241;-455.6
2(57Q)
0.260;-393.8
25(78)
0.226;-476.2
25(7T)
0.244;-435.0
25(7Q)
0.257;-393.8
5(289)
0.287;-435.0
5J(28)
0.247;-393.8
(58)(29)
0.282;-300.0
2J(58)
0.206;-393.8
58(29)
0.260;-435.0
58(2J)
0.190;-393.8
58(2K)
0.251;-352.5
5T(29)
0.238;-393.8
(29)(5K)
0.230;-196.9
2J(59)
0.308;-373.1
59(2T)
0.301;-393.8
59(2Q)
0.262;-352.5
(2T)(5T)
0.252;-103.1
5(2TK)
0.204;-311.2
2(5TQ)
0.325;-331.9
25(TJ)
0.217;-352.5
25(TK)
0.328;-311.2
(2J)(5K)
0.305;-155.6
2K(5J)
0.285;-290.6
25(JK)
0.252;-290.6
(5Q)(2K)
0.265;-135.0
(2K)(5K)
0.281;20.6
6(268)
0.225;-341.2
6T(26)
0.272;-300.0
(26)(6K)
0.270;-103.1
T(267)
0.239;-414.4
7(268)
0.190;-455.6
7T(26)
0.231;-414.4
(26)(7K)
0.223;-217.5
J(268)
0.263;-373.1
89(26)
0.233;-414.4
(26)(8Q)
0.269;-217.5
(269J)
0.235;-352.5
(26)(9T)
0.271;-238.1
9(26K)
0.269;-311.2
(26TK)
0.318;-290.6
TQ(26)
0.306;-311.2
K(26J)
0.295;-270.0
Q(26Q)
0.261;-135.0
KK(26)
0.309;-93.7
66(29)
0.208;-320.6
266J
0.266;-414.4
67(27)
0.253;-341.2
(27)(6T)
0.275;-279.4
6(27K)
0.242;-352.5
2(679)
0.211;-435.0
(67)(2Q)
0.299;-238.1
27(68)
0.240;-455.6
27(6T)
0.225;-414.4
27(6Q)
0.246;-373.1
68(28)
0.319;-300.0
(28)(6J)
0.257;-238.1
28(68)
0.231;-300.0
2(68J)
0.289;-373.1
2688
0.235;-435.0
268T
0.225;-528.7
268Q
0.290;-487.5
(29)(6T)
0.291;-238.1
6(29K)
0.261;-311.2
2(69J)
0.229;-352.5
2699
0.214;-393.8
269J
0.241;-487.5
269K
0.225;-446.2
6Q(2T)
0.269;-311.2
(6T)(2Q)
0.235;-176.2
2T(6J)
0.277;-331.9
2T(6K)
0.238;-290.6
6(2JK)
0.234;-270.0
2(6JK)
0.271;-270.0
2J(6K)
0.324;-270.0
2Q(6Q)
0.315;-135.0
26QK
0.207;-384.4
78(27)
0.296;-300.0
(27)(7J)
0.272;-103.1
8(278)
0.268;-279.4
Q(278)
0.315;-331.9
(27)(8T)
0.226;-238.1
8(27K)
0.332;-311.2
(279Q)
0.248;-311.2
9(27J)
0.254;-331.9
9K(27)
0.292;-290.6
TT(27)
0.289;-196.9
(27)(TK)
0.311;-135.0
J(27Q)
0.268;-270.0
K(27Q)
0.277;-228.7
77(28)
0.262;-300.0
277T
0.260;-393.8
27(7K)
0.232;-196.9
(28)(7T)
0.265;-238.1
7(28K)
0.285;-311.2
2(78T)
0.236;-373.1
(78)(2K)
0.347;-176.2
78(2T)
0.246;-373.1
78(2Q)
0.276;-331.9
(29)(79)
0.336;-103.1
7(29Q)
0.322;-311.2
2(79T)
0.225;-352.5
(79)(2K)
0.290;-155.6
79(2J)
0.267;-331.9
79(2K)
0.289;-290.6
7J(2T)
0.236;-311.2
(7T)(2J)
0.282;-176.2
2K(7T)
0.248;-270.0
27(TQ)
0.230;-290.6
7(2JQ)
0.271;-270.0
2(7JQ)
0.267;-270.0
27(JQ)
0.254;-270.0
7(2QK)
0.318;-228.7
7Q(2K)
0.261;-228.7
88(28)
0.310;-123.7
(28)(8J)
0.336;-61.9
9(289)
0.262;-217.5
K(289)
0.300;-270.0
9(28Q)
0.236;-290.6
J(28T)
0.233;-290.6
TJ(28)
0.263;-290.6
(28JQ)
0.270;-249.4
J(28K)
0.314;-228.7
(28)(QK)
0.272;-73.1
88(2T)
0.304;-217.5
288Q
0.230;-311.2
8T(29)
0.285;-331.9
(29)(8K)
0.295;-135.0
2J(89)
0.252;-311.2
89(2T)
0.324;-331.9
89(2Q)
0.241;-290.6
(2T)(8T)
0.313;-41.3
8(2TK)
0.262;-249.4
2(8TQ)
0.286;-270.0
28(TJ)
0.256;-290.6
28(TK)
0.270;-249.4
(2J)(8K)
0.258;-93.8
2K(8J)
0.283;-228.7
28(JK)
0.274;-228.7
(8Q)(2K)
0.289;-73.1
(2K)(8K)
0.340;82.5
9(29J)
0.260;-155.6
9K(29)
0.237;-114.4
TT(29)
0.275;-155.6
(29)(TK)
0.299;-93.8
J(29Q)
0.327;-228.7
K(29Q)
0.269;-187.5
99(2T)
0.240;-176.2
299Q
0.209;-270.0
9J(2T)
0.274;-270.0
(9T)(2J)
0.289;-135.0
2K(9T)
0.338;-228.7
29(TQ)
0.301;-249.4
9(2JQ)
0.256;-228.7
2(9JQ)
0.305;-228.7
29(JQ)
0.284;-228.7
9(2QK)
0.288;-187.5
9Q(2K)
0.253;-187.5
TT(2T)
0.381;0.0
(2T)(TK)
0.367;61.9
J(2TQ)
0.282;-208.1
K(2TQ)
0.238;-166.9
TT(2J)
0.252;-114.4
2TTK
0.256;-208.1
TK(2J)
0.307;-187.5
2TJJ
0.290;-228.7
2TJK
0.261;-322.5
2(TQK)
0.236;-166.9
TK(2K)
0.287;-11.2
(2J)(JK)
0.334;103.1
QK(2J)
0.343;-146.2
2J(JK)
0.308;-31.9
(JQ)(2K)
0.278;-11.2
(2K)(JK)
0.306;144.4
K(2QK)
0.310;30.0
2K(QK)
0.333;30.0
3335
0.207;-506.2
3339
0.183;-423.8
333K
0.233;-341.2
36(34)
0.207;-465.0
(34)(39)
0.254;-268.1
3(34Q)
0.322;-341.2
33(45)
0.236;-485.6
34(38)
0.198;-423.8
334T
0.192;-517.5
33(4K)
0.318;-320.6
(35)(37)
0.229;-288.7
3(35T)
0.269;-361.9
3Q(35)
0.290;-320.6
35(37)
0.236;-423.8
3359
0.180;-517.5
33(5Q)
0.232;-320.6
(36)(37)
0.237;-268.1
3(36T)
0.310;-341.2
3Q(36)
0.232;-300.0
36(38)
0.217;-382.5
336T
0.182;-476.2
33(6K)
0.253;-279.4
(37)(39)
0.264;-206.3
3(37Q)
0.284;-279.4
33(78)
0.220;-361.9
37(3J)
0.250;-300.0
337K
0.184;-393.8
3T(38)
0.243;-300.0
(38)(3K)
0.253;-103.1
338T
0.274;-435.0
33(8K)
0.271;-238.1
(39)(3J)
0.296;-123.7
3399
0.232;-300.0
33(9Q)
0.290;-238.1
(3T)(3J)
0.294;-103.1
33TT
0.279;-258.8
33(TK)
0.275;-196.9
(3J)(3K)
0.293;-41.3
33JK
0.267;-311.2
33(QK)
0.228;-155.6
45(34)
0.247;-465.0
(34)(48)
0.265;-268.1
4(34J)
0.236;-341.2
4K(34)
0.294;-300.0
(3459)
0.288;-496.9
(345K)
0.224;-414.4
57(34)
0.218;-538.1
(34)(5T)
0.207;-341.2
5(34K)
0.252;-414.4
(3469)
0.236;-476.2
(346K)
0.255;-393.8
68(34)
0.253;-496.9
(34)(6J)
0.277;-300.0
7(347)
0.203;-361.9
J(347)
0.226;-414.4
78(34)
0.244;-476.2
(34)(7J)
0.281;-279.4
8(348)
0.243;-320.6
Q(348)
0.231;-373.1
(34)(8T)
0.243;-279.4
8(34K)
0.223;-352.5
(349Q)
0.309;-352.5
9(34J)
0.282;-373.1
9K(34)
0.266;-331.9
TT(34)
0.223;-238.1
(34)(TK)
0.305;-176.2
J(34Q)
0.256;-311.2
K(34Q)
0.323;-270.0
44(35)
0.267;-465.0
3447
0.250;-558.8
34(4T)
0.279;-361.9
44(3K)
0.265;-300.0
4(357)
0.216;-538.1
49(35)
0.213;-496.9
(35)(4Q)
0.291;-300.0
36(45)
0.196;-558.8
3(459)
0.254;-496.9
(45)(3Q)
0.226;-300.0
35(46)
0.280;-558.8
35(48)
0.212;-517.5
35(4T)
0.248;-476.2
35(4Q)
0.231;-435.0
46(36)
0.244;-403.1
(36)(49)
0.251;-341.2
4(36Q)
0.230;-414.4
3(467)
0.245;-517.5
(46)(3T)
0.247;-320.6
3Q(46)
0.212;-414.4
3467
0.204;-652.5
3469
0.203;-611.2
346J
0.197;-570.0
346K
0.220;-528.7
49(37)
0.238;-455.6
(37)(4Q)
0.276;-258.8
38(47)
0.239;-476.2
3(47J)
0.222;-414.4
3477
0.228;-496.9
3479
0.214;-590.6
347J
0.241;-549.4
347K
0.204;-508.1
4T(38)
0.233;-414.4
(38)(4K)
0.226;-217.5
3T(48)
0.276;-414.4
3(48K)
0.218;-352.5
38(4T)
0.206;-414.4
38(4Q)
0.206;-373.1
49(39)
0.250;-279.4
(39)(4Q)
0.273;-217.5
3T(49)
0.213;-393.8
3(49K)
0.220;-331.9
39(4J)
0.241;-373.1
39(4K)
0.284;-331.9
4(3TQ)
0.260;-331.9
3(4TJ)
0.224;-352.5
34TT
0.239;-373.1
34TQ
0.230;-466.9
(3J)(4Q)
0.301;-176.2
3Q(4J)
0.263;-311.2
34JQ
0.267;-446.2
(3Q)(4K)
0.274;-135.0
3Q(4K)
0.290;-270.0
5(356)
0.227;-403.1
58(35)
0.219;-361.9
(35)(5J)
0.269;-165.0
6(356)
0.206;-382.5
T(356)
0.279;-435.0
6(357)
0.233;-496.9
69(35)
0.233;-455.6
(35)(6Q)
0.298;-258.8
(3579)
0.252;-435.0
(357K)
0.240;-352.5
79(35)
0.239;-435.0
(35)(7Q)
0.293;-238.1
(358T)
0.280;-393.8
88(35)
0.287;-300.0
(35)(8J)
0.235;-238.1
9(359)
0.289;-258.8
K(359)
0.257;-311.2
9(35Q)
0.271;-331.9
J(35T)
0.291;-331.9
TJ(35)
0.232;-331.9
(35JQ)
0.314;-290.6
J(35K)
0.250;-270.0
(35)(QK)
0.337;-114.4
55(37)
0.279;-382.5
3559
0.224;-476.2
35(5Q)
0.240;-279.4
(36)(57)
0.294;-361.9
5(36T)
0.259;-435.0
5Q(36)
0.226;-393.8
(56)(38)
0.245;-341.2
3T(56)
0.215;-435.0
3(56K)
0.243;-373.1
36(58)
0.207;-476.2
36(5T)
0.233;-435.0
36(5Q)
0.232;-393.8
57(37)
0.285;-341.2
(37)(5T)
0.258;-279.4
5(37K)
0.270;-352.5
3(579)
0.223;-435.0
(57)(3Q)
0.281;-238.1
37(58)
0.220;-455.6
37(5T)
0.184;-414.4
37(5Q)
0.227;-373.1
58(38)
0.253;-300.0
(38)(5J)
0.307;-238.1
38(58)
0.278;-300.0
3(58J)
0.238;-373.1
3588
0.214;-435.0
358T
0.231;-528.7
358Q
0.199;-487.5
(39)(5T)
0.335;-238.1
5(39K)
0.233;-311.2
3(59J)
0.187;-352.5
3599
0.180;-393.8
359J
0.206;-487.5
359K
0.222;-446.2
5Q(3T)
0.236;-311.2
(5T)(3Q)
0.360;-176.2
3T(5J)
0.205;-331.9
3T(5K)
0.236;-290.6
5(3JK)
0.274;-270.0
3(5JK)
0.294;-270.0
3J(5K)
0.280;-270.0
3Q(5Q)
0.273;-135.0
35QK
0.295;-384.4
67(36)
0.302;-341.2
(36)(6T)
0.260;-144.4
6(36K)
0.275;-217.5
(367T)
0.252;-393.8
77(36)
0.237;-320.6
(36)(7T)
0.277;-258.8
7(36K)
0.196;-331.9
(368J)
0.209;-352.5
(36)(89)
0.299;-258.8
8(36Q)
0.282;-331.9
T(369)
0.323;-352.5
9(36T)
0.270;-352.5
9Q(36)
0.196;-311.2
Q(36T)
0.234;-290.6
(36)(TQ)
0.246;-155.6
(36JK)
0.252;-249.4
JK(36)
0.252;-249.4
K(36K)
0.290;-73.1
3668
0.229;-455.6
36(6J)
0.281;-258.8
(37)(67)
0.296;-185.6
6(37T)
0.190;-393.8
6Q(37)
0.302;-352.5
(67)(39)
0.223;-279.4
3J(67)
0.220;-373.1
67(38)
0.222;-435.0
67(3T)
0.271;-393.8
67(3Q)
0.192;-352.5
(38)(68)
0.317;-144.4
6(38J)
0.273;-352.5
6K(38)
0.284;-311.2
(68)(3J)
0.277;-217.5
3K(68)
0.286;-311.2
36(8T)
0.244;-373.1
36(8Q)
0.224;-331.9
6(39T)
0.229;-352.5
6Q(39)
0.270;-311.2
(69)(3J)
0.261;-196.9
3K(69)
0.277;-290.6
36(9J)
0.273;-331.9
36(9K)
0.244;-290.6
(3T)(6Q)
0.334;-155.6
3J(6T)
0.234;-311.2
6T(3J)
0.279;-311.2
6T(3K)
0.300;-270.0
6Q(3J)
0.201;-270.0
(6J)(3K)
0.251;-114.4
6J(3K)
0.244;-249.4
6K(3Q)
0.251;-228.7
36(QK)
0.225;-228.7
(37)(78)
0.288;-144.4
7(37J)
0.298;-217.5
7K(37)
0.323;-176.2
(378Q)
0.252;-311.2
8(37T)
0.235;-352.5
8Q(37)
0.259;-311.2
J(379)
0.268;-311.2
9T(37)
0.259;-331.9
(37)(9K)
0.279;-135.0
K(37T)
0.247;-249.4
T(37K)
0.250;-249.4
JJ(37)
0.290;-135.0
(37QK)
0.285;-208.1
3777
0.268;-300.0
37(7T)
0.336;-238.1
77(3K)
0.328;-176.2
7(38T)
0.249;-352.5
7Q(38)
0.249;-311.2
(78)(3T)
0.342;-217.5
3Q(78)
0.303;-311.2
3789
0.199;-508.1
378J
0.229;-466.9
378K
0.293;-425.6
7J(39)
0.293;-311.2
(79)(3T)
0.247;-196.9
3Q(79)
0.297;-290.6
379T
0.253;-466.9
379Q
0.255;-425.6
(3T)(7J)
0.352;-155.6
3T(7T)
0.264;-176.2
3(7TK)
0.292;-249.4
3T(7Q)
0.288;-270.0
7J(3J)
0.304;-135.0
(7J)(3Q)
0.284;-114.4
3J(7Q)
0.229;-249.4
7Q(3Q)
0.351;-93.7
37QQ
0.219;-228.7
37KK
0.252;-187.5
8(38J)
0.294;-176.2
8K(38)
0.279;-135.0
(389K)
0.239;-249.4
9J(38)
0.289;-290.6
(38TJ)
0.266;-270.0
(38)(TJ)
0.307;-135.0
J(38J)
0.281;-114.4
JQ(38)
0.290;-228.7
Q(38K)
0.261;-187.5
3889
0.192;-352.5
38(8Q)
0.283;-155.6
(39)(8T)
0.299;-176.2
8(39K)
0.340;-249.4
3(89J)
0.208;-290.6
3899
0.271;-331.9
389J
0.269;-425.6
389K
0.185;-384.4
8Q(3T)
0.236;-249.4
(8T)(3Q)
0.277;-114.4
3T(8J)
0.281;-270.0
3T(8K)
0.305;-228.7
8(3JK)
0.277;-208.1
3(8JK)
0.223;-208.1
3J(8K)
0.239;-208.1
3Q(8Q)
0.281;-73.1
38QK
0.288;-322.5
9T(39)
0.223;-155.6
(39)(9K)
0.267;41.3
K(39T)
0.268;-208.1
T(39K)
0.245;-208.1
JJ(39)
0.265;-93.7
(39QK)
0.301;-166.9
3999
0.247;-176.2
39(9Q)
0.311;-114.4
(3T)(9J)
0.266;-114.4
3T(9T)
0.276;-135.0
3(9TK)
0.228;-208.1
3T(9Q)
0.287;-228.7
9J(3J)
0.274;-93.7
(9J)(3Q)
0.323;-73.1
3J(9Q)
0.250;-208.1
9Q(3Q)
0.244;-52.5
39QQ
0.243;-187.5
39KK
0.276;-146.2
T(3TK)
0.320;-52.5
JJ(3T)
0.317;-73.1
(3TQK)
0.280;-146.2
3TTT
0.289;-114.4
3T(TK)
0.294;-52.5
(3J)(TK)
0.309;-31.9
3K(TJ)
0.309;-166.9
3T(JK)
0.269;-166.9
(TQ)(3K)
0.279;-11.2
(3K)(TK)
0.368;144.4
J(3JK)
0.317;-11.2
(3J)(QK)
0.340;9.4
JJ(3K)
0.338;-11.2
3Q(JQ)
0.306;-11.2
3JQK
0.251;-260.6
QK(3Q)
0.369;30.0
QK(3K)
0.254;50.6
44(46)
0.333;-288.7
44(4T)
0.314;-206.2
(45)(45)
0.310;-153.8
4(458)
0.247;-361.9
4T(45)
0.203;-320.6
(45)(4K)
0.284;-123.7
4457
0.182;-517.5
44(5T)
0.227;-320.6
45(4K)
0.261;-258.8
4(468)
0.278;-341.2
4T(46)
0.248;-300.0
(46)(4K)
0.292;-103.1
4468
0.209;-476.2
44(6J)
0.258;-279.4
(47)(47)
0.309;-71.2
4(47T)
0.296;-279.4
4Q(47)
0.263;-238.1
47(49)
0.264;-300.0
447J
0.235;-393.8
48(48)
0.334;-165.0
(48)(4J)
0.288;-103.1
4488
0.267;-300.0
44(8J)
0.317;-238.1
(49)(49)
0.351;11.2
4(49Q)
0.245;-196.9
44(9T)
0.246;-238.1
49(4K)
0.300;-176.2
4(4TQ)
0.270;-176.2
44(TJ)
0.334;-196.9
(4J)(4J)
0.301;93.8
44JJ
0.286;-176.2
4Q(4Q)
0.318;0.0
(4K)(4K)
0.378;176.2
(45)(57)
0.217;-226.9
5(45T)
0.239;-300.0
5Q(45)
0.276;-258.8
8(456)
0.216;-455.6
Q(456)
0.278;-373.1
(45)(68)
0.257;-320.6
6(45J)
0.237;-393.8
6K(45)
0.253;-352.5
(457J)
0.247;-373.1
(45)(78)
0.243;-300.0
7(45J)
0.241;-373.1
7K(45)
0.249;-331.9
(458Q)
0.257;-331.9
8(45T)
0.293;-373.1
8Q(45)
0.260;-331.9
J(459)
0.290;-331.9
9T(45)
0.256;-352.5
(45)(9K)
0.288;-155.6
K(45T)
0.286;-270.0
T(45K)
0.265;-270.0
JJ(45)
0.303;-155.6
(45QK)
0.267;-228.7
4555
0.272;-403.1
45(58)
0.273;-341.2
55(4J)
0.241;-279.4
455K
0.257;-373.1
58(46)
0.208;-455.6
(46)(5J)
0.273;-258.8
46(56)
0.258;-361.9
4(569)
0.198;-435.0
(56)(4Q)
0.285;-238.1
46(57)
0.203;-476.2
46(59)
0.191;-435.0
46(5J)
0.259;-393.8
46(5K)
0.269;-352.5
5(479)
0.206;-414.4
5J(47)
0.273;-373.1
(57)(48)
0.258;-300.0
4T(57)
0.237;-393.8
4(57K)
0.196;-331.9
47(59)
0.209;-414.4
47(5J)
0.217;-373.1
47(5K)
0.289;-331.9
5(48T)
0.245;-373.1
5Q(48)
0.226;-331.9
(58)(4T)
0.259;-238.1
4Q(58)
0.248;-331.9
4589
0.233;-528.7
458J
0.275;-487.5
458K
0.204;-446.2
5J(49)
0.261;-331.9
(59)(4T)
0.257;-217.5
4Q(59)
0.268;-311.2
459T
0.231;-487.5
459Q
0.270;-446.2
(4T)(5J)
0.271;-176.2
4T(5T)
0.328;-196.9
4(5TK)
0.220;-270.0
4T(5Q)
0.216;-290.6
5J(4J)
0.312;-155.6
(5J)(4Q)
0.325;-135.0
4J(5Q)
0.232;-270.0
5Q(4Q)
0.353;-114.4
45QQ
0.330;-249.4
45KK
0.300;-208.1
6(469)
0.277;-279.4
6J(46)
0.250;-238.1
(4678)
0.300;-414.4
(467Q)
0.230;-331.9
7(469)
0.288;-393.8
7J(46)
0.273;-352.5
(4689)
0.234;-373.1
(468K)
0.211;-290.6
8T(46)
0.207;-352.5
(46)(8K)
0.281;-155.6
Q(469)
0.234;-290.6
(46)(9J)
0.288;-176.2
T(46T)
0.271;-176.2
T(46J)
0.247;-290.6
TK(46)
0.266;-249.4
(46)(JQ)
0.268;-114.4
QQ(46)
0.268;-93.7
46(67)
0.245;-320.6
66(4T)
0.280;-258.8
466Q
0.218;-352.5
68(47)
0.254;-414.4
(47)(6J)
0.294;-217.5
47(67)
0.233;-300.0
4(67T)
0.239;-373.1
(67)(4K)
0.297;-176.2
67(49)
0.194;-393.8
67(4J)
0.289;-352.5
67(4K)
0.293;-311.2
69(48)
0.248;-373.1
(48)(6Q)
0.271;-176.2
49(68)
0.294;-373.1
4(68Q)
0.231;-311.2
46(89)
0.272;-373.1
46(8J)
0.267;-331.9
46(8K)
0.279;-290.6
(49)(6J)
0.220;-176.2
49(69)
0.285;-217.5
4(69Q)
0.271;-290.6
46(9T)
0.274;-331.9
46(9Q)
0.202;-290.6
6(4TJ)
0.234;-290.6
6K(4T)
0.257;-249.4
(6T)(4K)
0.243;-114.4
6T(4Q)
0.222;-270.0
(4J)(6J)
0.293;0.0
4J(6J)
0.332;-135.0
6J(4Q)
0.213;-249.4
(4Q)(6Q)
0.342;41.3
4K(6Q)
0.284;-208.1
4K(6K)
0.302;-52.5
79(47)
0.321;-238.1
(47)(7Q)
0.281;-41.3
(478T)
0.315;-331.9
88(47)
0.261;-238.1
(47)(8J)
0.280;-176.2
9(479)
0.249;-196.9
K(479)
0.301;-249.4
9(47Q)
0.273;-270.0
J(47T)
0.229;-270.0
TJ(47)
0.262;-270.0
(47JQ)
0.218;-228.7
J(47K)
0.243;-208.1
(47)(QK)
0.260;-52.5
77(49)
0.257;-238.1
477J
0.293;-331.9
78(48)
0.248;-238.1
(48)(7J)
0.288;-176.2
48(78)
0.244;-238.1
4(78J)
0.209;-311.2
4788
0.230;-373.1
478T
0.250;-466.9
478Q
0.245;-425.6
(49)(7T)
0.266;-176.2
7(49K)
0.295;-249.4
4(79J)
0.216;-290.6
4799
0.250;-331.9
479J
0.212;-425.6
479K
0.207;-384.4
7Q(4T)
0.308;-249.4
(7T)(4Q)
0.296;-114.4
4T(7J)
0.250;-270.0
4T(7K)
0.271;-228.7
7(4JK)
0.270;-208.1
4(7JK)
0.286;-208.1
4J(7K)
0.275;-208.1
4Q(7Q)
0.310;-73.1
47QK
0.250;-322.5
89(48)
0.280;-196.9
(48)(8Q)
0.330;0.0
(489J)
0.304;-270.0
(48)(9T)
0.251;-155.6
9(48K)
0.225;-228.7
(48TK)
0.251;-208.1
TQ(48)
0.261;-228.7
K(48J)
0.252;-187.5
Q(48Q)
0.308;-52.5
KK(48)
0.299;-11.2
88(4J)
0.287;-155.6
488K
0.288;-249.4
8J(49)
0.270;-270.0
(89)(4T)
0.271;-155.6
4Q(89)
0.319;-249.4
489T
0.255;-425.6
489Q
0.303;-384.4
(4T)(8J)
0.362;-114.4
4T(8T)
0.300;-135.0
4(8TK)
0.266;-208.1
4T(8Q)
0.341;-228.7
8J(4J)
0.272;-93.7
(8J)(4Q)
0.347;-73.1
4J(8Q)
0.272;-208.1
8Q(4Q)
0.345;-52.5
48QQ
0.332;-187.5
48KK
0.306;-146.2
9(49Q)
0.271;-93.7
J(49T)
0.281;-228.7
TJ(49)
0.213;-228.7
(49JQ)
0.286;-187.5
J(49K)
0.291;-166.9
(49)(QK)
0.302;-11.2
99(4J)
0.315;-114.4
499K
0.283;-208.1
9Q(4T)
0.289;-208.1
(9T)(4Q)
0.287;-73.1
4T(9J)
0.263;-228.7
4T(9K)
0.304;-187.5
9(4JK)
0.320;-166.9
4(9JK)
0.336;-166.9
4J(9K)
0.249;-166.9
4Q(9Q)
0.345;-31.9
49QK
0.282;-281.2
TJ(4T)
0.302;-73.1
(4TJQ)
0.306;-166.9
J(4TK)
0.337;-146.2
(4T)(QK)
0.325;9.4
TT(4Q)
0.271;-52.5
T(4JQ)
0.255;-166.9
4(TJQ)
0.320;-166.9
4T(JQ)
0.278;-166.9
T(4QK)
0.314;-125.6
TQ(4K)
0.289;-125.6
JJ(4J)
0.318;103.1
(4JQK)
0.277;-105.0
4JJJ
0.303;-31.9
JQ(4Q)
0.288;9.4
4JQQ
0.315;-125.6
4JKK
0.268;-84.4
QQ(4K)
0.366;50.6
4KKK
0.368;91.9
55(59)
0.282;-165.0
55(5K)
0.319;-82.5
(56)(58)
0.272;-165.0
5(56J)
0.229;-238.1
5K(56)
0.320;-196.9
56(59)
0.310;-279.4
556J
0.219;-373.1
57(57)
0.271;-165.0
(57)(5T)
0.274;-103.1
5(57K)
0.280;-176.2
55(79)
0.290;-258.8
57(5Q)
0.217;-196.9
5(589)
0.268;-238.1
5J(58)
0.300;-196.9
58(59)
0.302;-238.1
558J
0.282;-331.9
59(59)
0.269;-82.5
(59)(5Q)
0.253;-20.6
559T
0.242;-331.9
55(9K)
0.264;-135.0
(5T)(5Q)
0.373;0.0
55TJ
0.241;-290.6
5J(5J)
0.314;0.0
5J(5Q)
0.289;-114.4
5(5QK)
0.256;-73.1
5K(5K)
0.317;82.5
68(56)
0.292;-279.4
(56)(6J)
0.327;-82.5
7(567)
0.318;-279.4
J(567)
0.246;-331.9
78(56)
0.239;-393.8
(56)(7J)
0.342;-196.9
8(568)
0.247;-238.1
Q(568)
0.312;-290.6
(56)(8T)
0.261;-196.9
8(56K)
0.286;-270.0
(569Q)
0.201;-270.0
9(56J)
0.263;-290.6
9K(56)
0.293;-249.4
TT(56)
0.324;-155.6
(56)(TK)
0.282;-93.8
J(56Q)
0.212;-228.7
K(56Q)
0.233;-187.5
66(57)
0.263;-300.0
5669
0.247;-393.8
56(6Q)
0.306;-196.9
(57)(68)
0.243;-258.8
6(57J)
0.281;-331.9
6K(57)
0.251;-290.6
(67)(5T)
0.295;-217.5
5Q(67)
0.265;-311.2
5678
0.191;-528.7
567T
0.232;-487.5
567Q
0.226;-446.2
(58)(69)
0.247;-217.5
6(58Q)
0.285;-290.6
5(689)
0.229;-352.5
(68)(5Q)
0.270;-155.6
58(69)
0.308;-352.5
58(6J)
0.213;-311.2
58(6K)
0.223;-270.0
6(59J)
0.240;-290.6
6K(59)
0.266;-249.4
(69)(5Q)
0.298;-135.0
59(6T)
0.222;-311.2
59(6Q)
0.231;-270.0
6T(5T)
0.273;-155.6
(5T)(6K)
0.302;-93.8
5Q(6T)
0.280;-249.4
56TJ
0.305;-405.0
56TK
0.232;-363.7
6K(5J)
0.269;-208.1
56JJ
0.265;-249.4
56JK
0.231;-343.1
5(6QK)
0.254;-187.5
6K(5K)
0.247;-31.9
(57)(79)
0.285;-82.5
7(57Q)
0.256;-155.6
9(578)
0.238;-331.9
K(578)
0.225;-249.4
8(57J)
0.290;-290.6
8K(57)
0.272;-249.4
(579K)
0.276;-228.7
9J(57)
0.235;-270.0
(57TJ)
0.273;-249.4
(57)(TJ)
0.329;-114.4
J(57J)
0.279;-93.7
JQ(57)
0.229;-208.1
Q(57K)
0.300;-166.9
5778
0.223;-373.1
57(7J)
0.229;-176.2
(58)(78)
0.354;-82.5
7(58J)
0.236;-290.6
7K(58)
0.242;-249.4
(78)(5J)
0.326;-155.6
5K(78)
0.265;-249.4
57(8T)
0.241;-311.2
57(8Q)
0.279;-270.0
7(59T)
0.309;-290.6
7Q(59)
0.273;-249.4
(79)(5J)
0.290;-135.0
5K(79)
0.300;-228.7
57(9J)
0.284;-270.0
57(9K)
0.338;-228.7
(5T)(7Q)
0.290;-93.8
5J(7T)
0.254;-249.4
7T(5J)
0.293;-249.4
7T(5K)
0.338;-208.1
7Q(5J)
0.320;-208.1
(7J)(5K)
0.281;-52.5
7J(5K)
0.340;-187.5
7K(5Q)
0.311;-166.9
57(QK)
0.313;-166.9
(58)(89)
0.288;-41.3
8(58Q)
0.282;-114.4
T(589)
0.277;-270.0
9(58T)
0.246;-270.0
9Q(58)
0.263;-228.7
Q(58T)
0.309;-208.1
(58)(TQ)
0.298;-73.1
(58JK)
0.314;-166.9
JK(58)
0.259;-166.9
K(58K)
0.246;9.4
588T
0.271;-290.6
58(8K)
0.277;-93.7
(59)(8J)
0.275;-114.4
59(89)
0.267;-155.6
5(89Q)
0.258;-228.7
58(9T)
0.322;-270.0
58(9Q)
0.234;-228.7
8(5TJ)
0.323;-228.7
8K(5T)
0.251;-187.5
(8T)(5K)
0.255;-52.5
8T(5Q)
0.286;-208.1
(5J)(8J)
0.361;61.9
5J(8J)
0.257;-73.1
8J(5Q)
0.274;-187.5
(5Q)(8Q)
0.311;103.1
5K(8Q)
0.328;-146.2
5K(8K)
0.353;9.4
9J(59)
0.282;-93.7
(59TJ)
0.254;-208.1
(59)(TJ)
0.300;-73.1
J(59J)
0.338;-52.5
JQ(59)
0.319;-166.9
Q(59K)
0.226;-125.6
599T
0.265;-249.4
59(9K)
0.292;-52.5
(5T)(9Q)
0.265;-52.5
5J(9T)
0.232;-208.1
9T(5J)
0.263;-208.1
9T(5K)
0.280;-166.9
9Q(5J)
0.250;-166.9
(9J)(5K)
0.289;-11.2
9J(5K)
0.355;-146.2
9K(5Q)
0.289;-125.6
59(QK)
0.264;-125.6
(5T)(TJ)
0.316;82.5
J(5TJ)
0.313;-31.9
JQ(5T)
0.247;-146.2
Q(5TK)
0.309;-105.0
5TTJ
0.319;-187.5
TJ(5J)
0.322;-31.9
(TJ)(5Q)
0.262;-11.2
5J(TQ)
0.325;-146.2
TQ(5Q)
0.264;9.4
5TQQ
0.234;-125.6
5TKK
0.356;-84.4
Q(5JQ)
0.285;30.0
KK(5J)
0.296;71.3
(5Q)(JQ)
0.343;165.0
5K(JQ)
0.249;-84.4
5K(JK)
0.370;71.3
5QQQ
0.272;50.6
KK(5K)
0.291;247.5
6669
0.230;-238.1
666K
0.223;-155.6
69(67)
0.268;-217.5
(67)(6Q)
0.333;-20.6
6678
0.201;-373.1
66(7J)
0.282;-176.2
(68)(68)
0.350;52.5
6(68J)
0.266;-155.6
6K(68)
0.284;-114.4
68(6J)
0.262;-155.6
668K
0.283;-249.4
6J(69)
0.286;-135.0
69(6T)
0.318;-155.6
669Q
0.234;-249.4
6J(6T)
0.318;-114.4
6T(6J)
0.276;-114.4
66TK
0.220;-208.1
6K(6J)
0.308;-52.5
(6Q)(6Q)
0.299;217.5
66QK
0.304;-166.9
7(679)
0.264;-196.9
7J(67)
0.237;-155.6
(6789)
0.282;-311.2
(678K)
0.262;-228.7
8T(67)
0.264;-290.6
(67)(8K)
0.300;-93.8
Q(679)
0.259;-228.7
(67)(9J)
0.221;-114.4
T(67T)
0.263;-114.4
T(67J)
0.267;-228.7
TK(67)
0.304;-187.5
(67)(JQ)
0.245;-52.5
QQ(67)
0.297;-31.9
67(78)
0.277;-217.5
77(6J)
0.291;-155.6
677K
0.263;-249.4
7T(68)
0.301;-290.6
(68)(7K)
0.268;-93.8
6T(78)
0.254;-290.6
6(78K)
0.231;-228.7
68(7T)
0.230;-290.6
68(7Q)
0.248;-249.4
79(69)
0.261;-155.6
(69)(7Q)
0.308;-93.8
6T(79)
0.252;-270.0
6(79K)
0.283;-208.1
69(7J)
0.283;-249.4
69(7K)
0.287;-208.1
7(6TQ)
0.260;-208.1
6(7TJ)
0.306;-228.7
67TT
0.281;-249.4
67TQ
0.281;-343.1
(6J)(7Q)
0.282;-52.5
6Q(7J)
0.215;-187.5
67JQ
0.254;-322.5
(6Q)(7K)
0.329;-11.2
6Q(7K)
0.279;-146.2
8(689)
0.261;-155.6
8J(68)
0.291;-114.4
(689T)
0.300;-249.4
99(68)
0.299;-135.0
(68)(9Q)
0.272;-73.1
(68TQ)
0.325;-187.5
T(68Q)
0.286;-187.5
Q(68J)
0.328;-166.9
(68)(JK)
0.330;-11.2
QK(68)
0.356;-125.6
68(8T)
0.319;-135.0
88(6K)
0.304;-73.1
8(69J)
0.255;-228.7
8K(69)
0.313;-187.5
(89)(6Q)
0.348;-73.1
69(8T)
0.259;-249.4
69(8Q)
0.280;-208.1
8T(6T)
0.352;-93.7
(6T)(8K)
0.247;-31.9
6Q(8T)
0.243;-187.5
68TJ
0.275;-343.1
68TK
0.215;-301.9
8K(6J)
0.280;-146.2
68JJ
0.249;-187.5
68JK
0.251;-281.2
6(8QK)
0.244;-125.6
8K(6K)
0.365;30.0
(69)(9J)
0.348;61.9
T(69T)
0.286;-73.1
T(69J)
0.279;-187.5
TK(69)
0.264;-146.2
(69)(JQ)
0.343;-11.2
QQ(69)
0.343;9.4
69(9T)
0.280;-93.7
99(6K)
0.279;-31.9
9(6TQ)
0.300;-166.9
6(9TJ)
0.241;-187.5
69TT
0.274;-208.1
69TQ
0.217;-301.9
(6J)(9Q)
0.327;-11.2
6Q(9J)
0.280;-146.2
69JQ
0.273;-281.2
(6Q)(9K)
0.277;30.0
6Q(9K)
0.259;-105.0
T(6TJ)
0.296;-31.9
TK(6T)
0.336;9.4
(6T)(JQ)
0.273;9.4
QQ(6T)
0.266;30.0
6T(TJ)
0.281;-31.9
(6J)(TJ)
0.353;123.7
6J(TJ)
0.325;-11.2
TJ(6Q)
0.272;-125.6
(6Q)(TQ)
0.343;165.0
6K(TQ)
0.282;-84.4
6K(TK)
0.329;71.3
JK(6J)
0.325;50.6
K(6JK)
0.335;91.9
6JJK
0.341;-84.4
6(JQK)
0.312;-63.7
JK(6K)
0.326;91.9
KK(6Q)
0.314;112.5
6QKK
0.288;-22.5
77(7T)
0.321;-20.6
(78)(78)
0.328;93.8
7(78J)
0.254;-114.4
7K(78)
0.294;-73.1
78(7J)
0.250;-114.4
778K
0.292;-208.1
7J(79)
0.338;-93.7
79(7T)
0.292;-114.4
779Q
0.295;-208.1
7J(7T)
0.309;-73.1
7T(7J)
0.264;-73.1
77TK
0.281;-166.9
7K(7J)
0.316;-11.2
(7Q)(7Q)
0.383;258.8
77QK
0.313;-125.6
8(78T)
0.313;-114.4
8Q(78)
0.309;-73.1
J(789)
0.258;-208.1
9T(78)
0.258;-228.7
(78)(9K)
0.300;-31.9
K(78T)
0.273;-146.2
T(78K)
0.276;-146.2
JJ(78)
0.343;-31.9
(78QK)
0.280;-105.0
7888
0.307;-155.6
78(8J)
0.226;-93.7
(79)(89)
0.343;20.6
8(79Q)
0.272;-187.5
7(89T)
0.277;-228.7
(89)(7K)
0.328;-31.9
89(7J)
0.239;-208.1
89(7K)
0.307;-166.9
8J(7T)
0.246;-187.5
(8T)(7J)
0.350;-52.5
7K(8T)
0.296;-146.2
78(TQ)
0.264;-166.9
8(7JQ)
0.248;-146.2
7(8JQ)
0.259;-146.2
78(JQ)
0.255;-146.2
8(7QK)
0.297;-105.0
8Q(7K)
0.311;-105.0
99(79)
0.317;41.2
(79)(9Q)
0.312;103.1
(79TQ)
0.302;-146.2
T(79Q)
0.322;-146.2
Q(79J)
0.276;-125.6
(79)(JK)
0.321;30.0
QK(79)
0.295;-84.4
79(9J)
0.341;-52.5
(7T)(9T)
0.321;82.5
9(7TK)
0.283;-125.6
7(9TQ)
0.284;-146.2
79(TJ)
0.293;-166.9
79(TK)
0.332;-125.6
(7J)(9K)
0.305;30.0
7K(9J)
0.302;-105.0
79(JK)
0.315;-105.0
(9Q)(7K)
0.363;50.6
(7K)(9K)
0.350;206.3
T(7TQ)
0.249;9.4
Q(7TJ)
0.258;-105.0
(7T)(JK)
0.327;50.6
QK(7T)
0.302;-63.7
7T(TQ)
0.321;9.4
(7J)(TQ)
0.362;30.0
7Q(TJ)
0.322;-105.0
7TJQ
0.259;-240.0
(7Q)(TK)
0.290;71.3
7Q(TK)
0.343;-63.7
J(7JQ)
0.304;50.6
K(7JQ)
0.331;-43.1
JJ(7Q)
0.400;50.6
J(7QK)
0.265;-43.1
JQ(7K)
0.295;-43.1
QQ(7Q)
0.317;226.9
7Q(QK)
0.404;112.5
8888
0.329;0.0
888Q
0.298;-52.5
8(89J)
0.344;-52.5
8K(89)
0.330;-11.2
89(8Q)
0.297;-31.9
8(8TJ)
0.359;-31.9
8K(8T)
0.377;9.4
8T(8K)
0.301;9.4
8(8JK)
0.330;30.0
88(JK)
0.333;30.0
8Q(8K)
0.322;50.6
(89)(9T)
0.299;82.5
9(89K)
0.324;9.4
(89TK)
0.278;-105.0
TQ(89)
0.301;-125.6
K(89J)
0.277;-84.4
Q(89Q)
0.345;50.6
KK(89)
0.314;91.9
99(8Q)
0.330;-11.2
9(8TJ)
0.264;-146.2
9K(8T)
0.302;-105.0
(9T)(8K)
0.332;30.0
9T(8Q)
0.292;-125.6
(8J)(9J)
0.311;144.4
8J(9J)
0.262;9.4
9J(8Q)
0.347;-105.0
(8Q)(9Q)
0.321;185.6
8K(9Q)
0.331;-63.7
8K(9K)
0.322;91.9
TQ(8T)
0.266;30.0
K(8TJ)
0.287;-63.7
Q(8TQ)
0.391;71.3
KK(8T)
0.350;112.5
