AAAA
0.114;-3775.0
5AAA
0.048;-18203.1
9AAA
0.075;-14490.6
KAAA
0.096;-10778.1
4A(2A)
0.026;-30268.8
(2A)(7A)
0.049;-21409.4
A(2TA)
0.033;-24700.0
QA(2A)
0.035;-22843.7
2A(4A)
0.032;-30268.8
26AA
0.020;-34487.5
AA(29)
0.034;-25628.1
2A(QA)
0.037;-22843.7
A(34A)
0.028;-29340.6
6A(3A)
0.030;-27484.4
(3A)(9A)
0.048;-18625.0
A(3QA)
0.045;-21915.6
AA(34)
0.028;-29340.6
3A(7A)
0.033;-26556.3
39AA
0.019;-30775.0
AA(3Q)
0.046;-21915.6
(4A)(5A)
0.047;-21409.4
A(48A)
0.048;-24700.0
TA(4A)
0.041;-22843.7
(4A)(KA)
0.073;-13984.4
46AA
0.021;-32631.2
AA(49)
0.038;-23771.9
4A(QA)
0.039;-20987.5
A(56A)
0.043;-25628.1
8A(5A)
0.049;-23771.9
(5A)(JA)
0.072;-14912.5
55AA
0.036;-26556.3
AA(58)
0.041;-23771.9
5A(JA)
0.043;-20987.5
5KAA
0.034;-25206.3
8A(6A)
0.048;-22843.7
(6A)(JA)
0.083;-13984.4
66AA
0.044;-24700.0
AA(69)
0.052;-21915.6
6A(QA)
0.048;-19131.3
A(78A)
0.043;-21915.6
TA(7A)
0.055;-20059.4
(7A)(KA)
0.089;-11200.0
79AA
0.041;-27062.5
AA(7Q)
0.054;-18203.1
(8A)(9A)
0.071;-13984.4
A(8QA)
0.069;-17275.0
AA(89)
0.038;-20059.4
8A(QA)
0.065;-17275.0
A(9TA)
0.057;-18203.1
QA(9A)
0.061;-16346.9
9A(JA)
0.052;-17275.0
9KAA
0.042;-21493.8
QA(TA)
0.055;-15418.8
TA(QA)
0.076;-15418.8
A(JQA)
0.082;-14490.6
AA(JQ)
0.062;-14490.6
(QA)(KA)
0.092;-6559.4
KKAA
0.061;-11706.2
2(25A)
0.012;-40478.1
27(2A)
0.016;-38621.9
(2T)(2A)
0.032;-29762.5
2(2KA)
0.021;-33053.1
(236A)
0.007;-44696.9
(23TA)
0.010;-40984.4
33(2A)
0.012;-41406.2
(36)(2A)
0.015;-38621.9
3(29A)
0.012;-41912.5
3J(2A)
0.012;-40056.3
(245A)
0.009;-44696.9
(249A)
0.013;-40984.4
(24KA)
0.015;-37271.9
46(2A)
0.010;-43768.8
(49)(2A)
0.019;-34909.4
4(2QA)
0.019;-38200.0
6(25A)
0.012;-42840.6
T(25A)
0.018;-39128.1
5(26A)
0.011;-42840.6
58(2A)
0.011;-40984.4
(5J)(2A)
0.024;-32125.0
6(26A)
0.024;-35837.5
T(26A)
0.014;-38200.0
6(27A)
0.013;-40984.4
69(2A)
0.014;-39128.1
(6Q)(2A)
0.029;-30268.8
(279A)
0.018;-38200.0
(27KA)
0.019;-34487.5
79(2A)
0.018;-38200.0
(7Q)(2A)
0.032;-29340.6
(28TA)
0.018;-36343.8
88(2A)
0.026;-32125.0
(8J)(2A)
0.024;-29340.6
9(29A)
0.023;-30268.8
K(29A)
0.020;-32631.2
9(2QA)
0.024;-33559.4
J(2TA)
0.026;-33559.4
TJ(2A)
0.018;-33559.4
(2JQA)
0.025;-31703.1
J(2KA)
0.024;-30775.0
(QK)(2A)
0.040;-23771.9
22(4A)
0.013;-41406.2
226A
0.008;-45625.0
2A(29)
0.014;-36765.6
22(QA)
0.019;-33981.2
2(34A)
0.008;-46553.1
26(3A)
0.008;-44696.9
(29)(3A)
0.021;-35837.5
2(3QA)
0.011;-39128.1
A(234)
0.007;-46553.1
(23)(7A)
0.017;-37693.8
9A(23)
0.011;-41912.5
A(23Q)
0.014;-39128.1
2A(34)
0.008;-46553.1
2A(36)
0.009;-44696.9
2A(38)
0.012;-42840.6
2A(3T)
0.011;-40984.4
2A(3Q)
0.016;-39128.1
2(45A)
0.009;-44696.9
27(4A)
0.012;-42840.6
(2T)(4A)
0.016;-33981.2
2(4KA)
0.016;-37271.9
A(246)
0.011;-43768.8
(24)(9A)
0.026;-34909.4
JA(24)
0.013;-39128.1
24(5A)
0.011;-44696.9
24(7A)
0.011;-42840.6
24(9A)
0.014;-40984.4
24(JA)
0.016;-39128.1
24(KA)
0.016;-37271.9
26(5A)
0.012;-42840.6
(29)(5A)
0.025;-33981.2
2(5QA)
0.018;-37271.9
A(256)
0.013;-42840.6
(25)(9A)
0.021;-33981.2
JA(25)
0.018;-38200.0
25(6A)
0.009;-42840.6
25(8A)
0.011;-40984.4
25(TA)
0.013;-39128.1
25(QA)
0.017;-37271.9
(26)(6A)
0.033;-29762.5
2(69A)
0.016;-39128.1
2J(6A)
0.016;-37271.9
(26)(7A)
0.017;-34909.4
9A(26)
0.015;-39128.1
A(26Q)
0.020;-36343.8
2A(67)
0.013;-40984.4
2A(69)
0.015;-39128.1
2A(6J)
0.017;-37271.9
2A(6K)
0.019;-35415.6
(29)(7A)
0.034;-32125.0
2(7QA)
0.016;-35415.6
A(278)
0.019;-39128.1
(27)(JA)
0.024;-30268.8
KA(27)
0.021;-34487.5
2A(79)
0.018;-38200.0
2A(7J)
0.018;-36343.8
2A(7K)
0.022;-34487.5
(2T)(8A)
0.032;-30268.8
2(8KA)
0.022;-33559.4
A(28T)
0.022;-36343.8
(28)(KA)
0.039;-27484.4
28(TA)
0.020;-36343.8
28(QA)
0.023;-34487.5
(29)(9A)
0.032;-24193.8
2(9QA)
0.020;-33559.4
A(29T)
0.019;-35415.6
(29)(KA)
0.029;-26556.3
29(JA)
0.019;-34487.5
29(KA)
0.027;-32631.2
2J(TA)
0.017;-33559.4
(2T)(JA)
0.034;-27484.4
KA(2T)
0.024;-31703.1
2A(TQ)
0.023;-32631.2
2(JQA)
0.025;-31703.1
A(2JQ)
0.029;-31703.1
2A(JQ)
0.023;-31703.1
2(QKA)
0.024;-29846.9
2Q(KA)
0.026;-29846.9
33(3A)
0.022;-34403.1
(36)(3A)
0.026;-31618.8
3(39A)
0.018;-34909.4
3J(3A)
0.029;-33053.1
(345A)
0.011;-43768.8
(349A)
0.011;-40056.3
(34KA)
0.017;-36343.8
46(3A)
0.012;-42840.6
(49)(3A)
0.024;-33981.2
4(3QA)
0.018;-37271.9
6(35A)
0.010;-41912.5
T(35A)
0.017;-38200.0
5(36A)
0.009;-41912.5
58(3A)
0.013;-40056.3
(5J)(3A)
0.036;-31196.9
6(36A)
0.021;-34909.4
T(36A)
0.024;-37271.9
6(37A)
0.015;-40056.3
69(3A)
0.019;-38200.0
(6Q)(3A)
0.030;-29340.6
(379A)
0.015;-37271.9
(37KA)
0.028;-33559.4
79(3A)
0.018;-37271.9
(7Q)(3A)
0.035;-28412.5
(38TA)
0.021;-35415.6
88(3A)
0.035;-31196.9
(8J)(3A)
0.028;-28412.5
9(39A)
0.023;-29340.6
K(39A)
0.020;-31703.1
9(3QA)
0.024;-32631.2
J(3TA)
0.024;-32631.2
TJ(3A)
0.026;-32631.2
(3JQA)
0.026;-30775.0
J(3KA)
0.032;-29846.9
(QK)(3A)
0.055;-22843.7
33(5A)
0.017;-38621.9
337A
0.013;-42840.6
3A(3T)
0.022;-33981.2
33(KA)
0.025;-31196.9
3(46A)
0.012;-42840.6
38(4A)
0.014;-40984.4
(3J)(4A)
0.031;-32125.0
4A(34)
0.016;-38621.9
A(347)
0.012;-41912.5
(34)(TA)
0.024;-33053.1
QA(34)
0.015;-37271.9
345A
0.005;-49843.8
347A
0.007;-47987.5
349A
0.007;-46131.3
34JA
0.009;-44275.0
34KA
0.011;-42418.8
37(5A)
0.010;-40984.4
(3T)(5A)
0.024;-32125.0
3(5KA)
0.017;-35415.6
A(357)
0.015;-40984.4
(35)(TA)
0.026;-32125.0
QA(35)
0.014;-36343.8
356A
0.007;-47987.5
358A
0.009;-46131.3
35TA
0.009;-44275.0
35QA
0.010;-42418.8
(37)(6A)
0.019;-33981.2
3(6TA)
0.014;-37271.9
3Q(6A)
0.015;-35415.6
(36)(8A)
0.020;-33053.1
TA(36)
0.015;-37271.9
A(36K)
0.022;-34487.5
6A(38)
0.014;-39128.1
6A(3T)
0.013;-37271.9
6A(3Q)
0.018;-35415.6
37(7A)
0.023;-33053.1
(3T)(7A)
0.034;-30268.8
3(7KA)
0.022;-33559.4
A(379)
0.017;-37271.9
(37)(QA)
0.031;-28412.5
7A(38)
0.017;-38200.0
7A(3T)
0.020;-36343.8
7A(3Q)
0.020;-34487.5
38(8A)
0.029;-31196.9
(3J)(8A)
0.025;-28412.5
8A(38)
0.030;-31196.9
A(38J)
0.021;-34487.5
388A
0.017;-37271.9
38TA
0.013;-41490.6
38QA
0.016;-39634.4
(3T)(9A)
0.036;-28412.5
3(9KA)
0.023;-31703.1
A(39J)
0.022;-33559.4
399A
0.017;-35415.6
39JA
0.013;-39634.4
39KA
0.016;-37778.1
3Q(TA)
0.030;-31703.1
(3T)(QA)
0.037;-25628.1
TA(3J)
0.020;-32631.2
TA(3K)
0.024;-30775.0
3(JKA)
0.027;-29846.9
A(3JK)
0.026;-29846.9
JA(3K)
0.031;-29846.9
QA(3Q)
0.041;-23771.9
3QKA
0.025;-34993.8
45(4A)
0.020;-36765.6
(48)(4A)
0.030;-27906.3
4(4JA)
0.030;-31196.9
4K(4A)
0.031;-29340.6
(459A)
0.015;-38200.0
(45KA)
0.021;-34487.5
57(4A)
0.012;-40056.3
(5T)(4A)
0.024;-31196.9
5(4KA)
0.024;-34487.5
(469A)
0.021;-37271.9
(46KA)
0.025;-33559.4
68(4A)
0.014;-38200.0
(6J)(4A)
0.036;-29340.6
7(47A)
0.026;-32125.0
J(47A)
0.026;-34487.5
78(4A)
0.019;-37271.9
(7J)(4A)
0.036;-28412.5
8(48A)
0.035;-30268.8
Q(48A)
0.025;-32631.2
(8T)(4A)
0.030;-28412.5
8(4KA)
0.020;-31703.1
(49QA)
0.022;-31703.1
9(4JA)
0.031;-32631.2
9K(4A)
0.021;-30775.0
TT(4A)
0.043;-26556.3
(TK)(4A)
0.034;-23771.9
J(4QA)
0.028;-29846.9
K(4QA)
0.029;-27990.6
44(5A)
0.018;-36765.6
447A
0.011;-40984.4
4A(4T)
0.028;-32125.0
44(KA)
0.026;-29340.6
4(57A)
0.012;-40056.3
49(5A)
0.019;-38200.0
(4Q)(5A)
0.027;-29340.6
6A(45)
0.014;-40984.4
A(459)
0.015;-38200.0
(45)(QA)
0.032;-29340.6
5A(46)
0.012;-40984.4
5A(48)
0.017;-39128.1
5A(4T)
0.013;-37271.9
5A(4Q)
0.020;-35415.6
46(6A)
0.018;-33981.2
(49)(6A)
0.023;-31196.9
4(6QA)
0.016;-34487.5
A(467)
0.012;-39128.1
(46)(TA)
0.028;-30268.8
QA(46)
0.018;-34487.5
467A
0.011;-45203.1
469A
0.010;-43346.9
46JA
0.012;-41490.6
46KA
0.012;-39634.4
49(7A)
0.014;-36343.8
(4Q)(7A)
0.033;-27484.4
8A(47)
0.016;-37271.9
A(47J)
0.020;-34487.5
477A
0.017;-38200.0
479A
0.013;-42418.8
47JA
0.015;-40562.5
47KA
0.015;-38706.3
4T(8A)
0.021;-34487.5
(4K)(8A)
0.051;-25628.1
TA(48)
0.025;-34487.5
A(48K)
0.025;-31703.1
8A(4T)
0.019;-34487.5
8A(4Q)
0.028;-32631.2
49(9A)
0.029;-28412.5
(4Q)(9A)
0.036;-25628.1
TA(49)
0.025;-33559.4
A(49K)
0.024;-30775.0
9A(4J)
0.028;-32631.2
9A(4K)
0.020;-30775.0
4(TQA)
0.033;-30775.0
A(4TJ)
0.022;-31703.1
4TTA
0.021;-32631.2
4TQA
0.019;-36850.0
(4Q)(JA)
0.032;-23771.9
QA(4J)
0.022;-29846.9
4JQA
0.020;-35921.9
(4K)(QA)
0.058;-21915.6
QA(4K)
0.030;-27990.6
5(56A)
0.024;-33981.2
58(5A)
0.027;-32125.0
(5J)(5A)
0.042;-23265.6
6(56A)
0.021;-33053.1
T(56A)
0.022;-35415.6
6(57A)
0.020;-38200.0
69(5A)
0.017;-36343.8
(6Q)(5A)
0.032;-27484.4
(579A)
0.021;-35415.6
(57KA)
0.027;-31703.1
79(5A)
0.020;-35415.6
(7Q)(5A)
0.041;-26556.3
(58TA)
0.024;-33559.4
88(5A)
0.032;-29340.6
(8J)(5A)
0.044;-26556.3
9(59A)
0.034;-27484.4
K(59A)
0.022;-29846.9
9(5QA)
0.022;-30775.0
J(5TA)
0.025;-30775.0
TJ(5A)
0.031;-30775.0
(5JQA)
0.029;-28918.7
J(5KA)
0.025;-27990.6
(QK)(5A)
0.053;-20987.5
55(7A)
0.019;-33053.1
559A
0.018;-37271.9
5A(5Q)
0.024;-28412.5
(57)(6A)
0.030;-32125.0
5(6TA)
0.016;-35415.6
5Q(6A)
0.023;-33559.4
(56)(8A)
0.032;-31196.9
TA(56)
0.023;-35415.6
A(56K)
0.025;-32631.2
6A(58)
0.022;-37271.9
6A(5T)
0.018;-35415.6
6A(5Q)
0.020;-33559.4
57(7A)
0.025;-31196.9
(5T)(7A)
0.030;-28412.5
5(7KA)
0.026;-31703.1
A(579)
0.018;-35415.6
(57)(QA)
0.038;-26556.3
7A(58)
0.018;-36343.8
7A(5T)
0.021;-34487.5
7A(5Q)
0.018;-32631.2
58(8A)
0.029;-29340.6
(5J)(8A)
0.031;-26556.3
8A(58)
0.029;-29340.6
A(58J)
0.028;-32631.2
588A
0.019;-35415.6
58TA
0.016;-39634.4
58QA
0.019;-37778.1
(5T)(9A)
0.035;-26556.3
5(9KA)
0.026;-29846.9
A(59J)
0.033;-31703.1
599A
0.027;-33559.4
59JA
0.016;-37778.1
59KA
0.017;-35921.9
5Q(TA)
0.026;-29846.9
(5T)(QA)
0.042;-23771.9
TA(5J)
0.032;-30775.0
TA(5K)
0.032;-28918.7
5(JKA)
0.032;-27990.6
A(5JK)
0.022;-27990.6
JA(5K)
0.033;-27990.6
QA(5Q)
0.051;-21915.6
5QKA
0.024;-33137.5
67(6A)
0.031;-31196.9
(6T)(6A)
0.040;-22337.5
6(6KA)
0.031;-25628.1
(67TA)
0.022;-33559.4
77(6A)
0.026;-30268.8
(7T)(6A)
0.040;-27484.4
7(6KA)
0.024;-30775.0
(68JA)
0.027;-31703.1
(89)(6A)
0.038;-27484.4
8(6QA)
0.027;-30775.0
T(69A)
0.025;-31703.1
9(6TA)
0.022;-31703.1
9Q(6A)
0.024;-29846.9
Q(6TA)
0.037;-28918.7
(TQ)(6A)
0.045;-22843.7
(6JKA)
0.033;-27062.5
JK(6A)
0.033;-27062.5
K(6KA)
0.051;-19131.3
668A
0.014;-36343.8
6A(6J)
0.036;-27484.4
(67)(7A)
0.046;-24193.8
6(7TA)
0.023;-33559.4
6Q(7A)
0.025;-31703.1
(67)(9A)
0.036;-28412.5
JA(67)
0.021;-32631.2
67(8A)
0.015;-35415.6
67(TA)
0.024;-33559.4
67(QA)
0.022;-31703.1
(68)(8A)
0.045;-22337.5
6(8JA)
0.029;-31703.1
6K(8A)
0.022;-29846.9
(68)(JA)
0.040;-25628.1
KA(68)
0.023;-29846.9
6A(8T)
0.024;-32631.2
6A(8Q)
0.025;-30775.0
6(9TA)
0.034;-31703.1
6Q(9A)
0.030;-29846.9
(69)(JA)
0.039;-24700.0
KA(69)
0.026;-28918.7
6A(9J)
0.029;-30775.0
6A(9K)
0.026;-28918.7
(6Q)(TA)
0.041;-22843.7
JA(6T)
0.028;-29846.9
6T(JA)
0.029;-29846.9
6T(KA)
0.025;-27990.6
6Q(JA)
0.037;-27990.6
(6J)(KA)
0.062;-20987.5
6J(KA)
0.030;-27062.5
6K(QA)
0.029;-26134.4
6A(QK)
0.031;-26134.4
(78)(7A)
0.048;-22337.5
7(7JA)
0.029;-25628.1
7K(7A)
0.043;-23771.9
(78QA)
0.023;-29846.9
8(7TA)
0.030;-31703.1
8Q(7A)
0.032;-29846.9
J(79A)
0.028;-29846.9
9T(7A)
0.020;-30775.0
(9K)(7A)
0.042;-21915.6
K(7TA)
0.031;-27062.5
T(7KA)
0.039;-27062.5
JJ(7A)
0.053;-21915.6
(7QKA)
0.041;-25206.3
777A
0.040;-29340.6
7A(7T)
0.031;-26556.3
77(KA)
0.044;-23771.9
7(8TA)
0.029;-31703.1
7Q(8A)
0.029;-29846.9
(78)(TA)
0.042;-25628.1
QA(78)
0.029;-29846.9
789A
0.018;-38706.3
78JA
0.018;-36850.0
78KA
0.020;-34993.8
7J(9A)
0.027;-29846.9
(79)(TA)
0.031;-24700.0
QA(79)
0.027;-28918.7
79TA
0.015;-36850.0
79QA
0.021;-34993.8
(7J)(TA)
0.039;-22843.7
TA(7T)
0.048;-23771.9
A(7TK)
0.027;-27062.5
TA(7Q)
0.024;-27990.6
7J(JA)
0.057;-21915.6
(7J)(QA)
0.048;-20987.5
JA(7Q)
0.036;-27062.5
7Q(QA)
0.054;-20059.4
7QQA
0.031;-26134.4
7KKA
0.041;-24278.1
8(8JA)
0.036;-23771.9
8K(8A)
0.037;-21915.6
(89KA)
0.034;-27062.5
9J(8A)
0.035;-28918.7
(8TJA)
0.039;-27990.6
(TJ)(8A)
0.038;-21915.6
J(8JA)
0.042;-20987.5
JQ(8A)
0.034;-26134.4
Q(8KA)
0.035;-24278.1
889A
0.023;-31703.1
8A(8Q)
0.045;-22843.7
(8T)(9A)
0.043;-23771.9
8(9KA)
0.033;-27062.5
A(89J)
0.036;-28918.7
899A
0.026;-30775.0
89JA
0.016;-34993.8
89KA
0.028;-33137.5
8Q(TA)
0.035;-27062.5
(8T)(QA)
0.041;-20987.5
TA(8J)
0.033;-27990.6
TA(8K)
0.036;-26134.4
8(JKA)
0.031;-25206.3
A(8JK)
0.030;-25206.3
JA(8K)
0.047;-25206.3
QA(8Q)
0.070;-19131.3
8QKA
0.023;-30353.1
9T(9A)
0.037;-22843.7
(9K)(9A)
0.072;-13984.4
K(9TA)
0.033;-25206.3
T(9KA)
0.038;-25206.3
JJ(9A)
0.048;-20059.4
(9QKA)
0.036;-23350.0
999A
0.041;-23771.9
9A(9Q)
0.048;-20987.5
(9J)(TA)
0.063;-20987.5
TA(9T)
0.043;-21915.6
A(9TK)
0.040;-25206.3
TA(9Q)
0.043;-26134.4
9J(JA)
0.051;-20059.4
(9J)(QA)
0.057;-19131.2
JA(9Q)
0.032;-25206.3
9Q(QA)
0.059;-18203.1
9QQA
0.048;-24278.1
9KKA
0.039;-22421.9
T(TKA)
0.054;-18203.1
JJ(TA)
0.062;-19131.3
(TQKA)
0.041;-22421.9
TTTA
0.043;-20987.5
TA(TK)
0.047;-18203.1
(TK)(JA)
0.052;-17275.0
KA(TJ)
0.053;-23350.0
TA(JK)
0.039;-23350.0
(TQ)(KA)
0.048;-16346.9
(TK)(KA)
0.077;-9343.8
J(JKA)
0.049;-16346.9
(QK)(JA)
0.064;-15418.7
JJ(KA)
0.051;-16346.9
QA(JQ)
0.046;-16346.9
JQKA
0.037;-27568.7
QK(QA)
0.085;-14490.6
QK(KA)
0.073;-13562.5
22(24)
0.007;-46468.8
22(28)
0.010;-42756.3
22(2Q)
0.014;-39043.8
24(23)
0.004;-51615.6
(23)(27)
0.010;-42756.3
2(23T)
0.006;-46046.9
2Q(23)
0.010;-44190.6
23(25)
0.004;-50687.5
2237
0.002;-54906.3
22(3T)
0.006;-46046.9
23(2K)
0.011;-43262.5
2(246)
0.005;-48831.3
28(24)
0.007;-46975.0
(24)(2J)
0.021;-38115.6
2244
0.004;-50687.5
22(47)
0.005;-47903.1
24(2T)
0.010;-45118.8
224Q
0.007;-49337.5
26(25)
0.005;-47903.1
(25)(29)
0.018;-39043.8
2(25Q)
0.012;-42334.4
22(56)
0.007;-47903.1
25(29)
0.010;-45118.8
225J
0.006;-49337.5
26(26)
0.010;-40900.0
(26)(29)
0.015;-38115.6
2(26Q)
0.011;-41406.2
22(67)
0.008;-46046.9
26(2T)
0.011;-43262.5
226Q
0.006;-47481.2
28(27)
0.010;-44190.6
(27)(2J)
0.023;-35331.3
2277
0.008;-45118.8
22(7T)
0.010;-42334.4
27(2K)
0.017;-39550.0
2(28T)
0.012;-41406.2
2Q(28)
0.013;-39550.0
28(2T)
0.015;-41406.2
228Q
0.008;-45625.0
2T(29)
0.012;-40478.1
(29)(2K)
0.021;-31618.8
229J
0.007;-45625.0
2T(2T)
0.025;-33475.0
(2T)(2K)
0.032;-30690.6
22TQ
0.011;-43768.8
2Q(2J)
0.016;-36765.6
2J(2K)
0.016;-35837.5
22QQ
0.014;-35837.5
3(234)
0.005;-50687.5
36(23)
0.006;-48831.3
(23)(39)
0.012;-39971.9
3(23Q)
0.013;-43262.5
5(234)
0.003;-54906.3
9(234)
0.004;-51193.8
K(234)
0.007;-47481.2
4(237)
0.003;-53050.0
49(23)
0.004;-51193.8
(23)(4Q)
0.011;-42334.4
(2357)
0.003;-52121.9
(235J)
0.006;-48409.4
(23)(56)
0.006;-46975.0
5(239)
0.004;-50265.6
5J(23)
0.007;-48409.4
(2367)
0.005;-51193.8
(236J)
0.006;-47481.2
(23)(67)
0.010;-45118.8
6(23T)
0.007;-48409.4
6Q(23)
0.006;-46553.1
9(237)
0.005;-48409.4
K(237)
0.008;-44696.9
7(23T)
0.006;-47481.2
7Q(23)
0.008;-45625.0
T(238)
0.007;-46553.1
8(239)
0.006;-47481.2
8J(23)
0.008;-45625.0
(239T)
0.008;-45625.0
99(23)
0.011;-40478.1
(23)(9Q)
0.019;-37693.8
(23TQ)
0.009;-42840.6
T(23Q)
0.010;-42840.6
Q(23J)
0.015;-41912.5
(23)(JK)
0.017;-34909.4
QK(23)
0.013;-40056.3
23(35)
0.004;-49759.4
33(28)
0.006;-46975.0
233T
0.005;-51193.8
23(3K)
0.014;-42334.4
(24)(36)
0.006;-47903.1
3(249)
0.004;-51193.8
3J(24)
0.004;-49337.5
(34)(25)
0.007;-48831.3
27(34)
0.004;-53050.0
2(34T)
0.004;-50265.6
(34)(2K)
0.012;-41406.2
34(26)
0.002;-53978.1
34(28)
0.003;-52121.9
34(2T)
0.005;-50265.6
34(2Q)
0.006;-48409.4
(25)(35)
0.009;-41828.1
3(258)
0.004;-51193.8
3T(25)
0.005;-49337.5
(25)(3K)
0.014;-40478.1
27(35)
0.005;-52121.9
2(35T)
0.005;-49337.5
(35)(2K)
0.013;-40478.1
35(27)
0.003;-52121.9
35(29)
0.006;-50265.6
35(2J)
0.006;-48409.4
35(2K)
0.007;-46553.1
37(26)
0.004;-51193.8
(26)(3T)
0.011;-42334.4
3(26K)
0.008;-45625.0
2(368)
0.004;-50265.6
(36)(2J)
0.010;-41406.2
2K(36)
0.009;-45625.0
23(68)
0.005;-50265.6
23(6T)
0.005;-48409.4
23(6Q)
0.005;-46553.1
3(278)
0.004;-49337.5
3T(27)
0.006;-47481.2
(27)(3K)
0.016;-38621.9
29(37)
0.006;-48409.4
2(37Q)
0.007;-45625.0
23(78)
0.005;-49337.5
23(7T)
0.006;-47481.2
23(7Q)
0.007;-45625.0
3(289)
0.005;-47481.2
3J(28)
0.007;-45625.0
(38)(29)
0.015;-41406.2
2J(38)
0.007;-45625.0
38(29)
0.007;-47481.2
38(2J)
0.009;-45625.0
38(2K)
0.010;-43768.8
3T(29)
0.007;-45625.0
(29)(3K)
0.014;-36765.6
2J(39)
0.009;-44696.9
39(2T)
0.008;-45625.0
39(2Q)
0.010;-43768.8
(2T)(3T)
0.022;-32546.9
3(2TK)
0.011;-41912.5
2(3TQ)
0.009;-42840.6
23(TJ)
0.011;-43768.8
23(TK)
0.012;-41912.5
(2J)(3K)
0.017;-34909.4
2K(3J)
0.011;-40984.4
23(JK)
0.013;-40984.4
(3Q)(2K)
0.023;-33981.2
(2K)(3K)
0.047;-26978.1
4(246)
0.009;-46975.0
48(24)
0.008;-45118.8
(24)(4J)
0.020;-36259.4
5(245)
0.007;-46975.0
9(245)
0.005;-49337.5
K(245)
0.010;-45625.0
5(248)
0.005;-50265.6
5T(24)
0.005;-48409.4
(24)(5K)
0.017;-39550.0
9(246)
0.005;-48409.4
K(246)
0.010;-44696.9
6(249)
0.006;-48409.4
6J(24)
0.009;-46553.1
(2478)
0.005;-48409.4
(247Q)
0.008;-44696.9
7(249)
0.007;-47481.2
7J(24)
0.009;-45625.0
(2489)
0.007;-46553.1
(248K)
0.007;-42840.6
8T(24)
0.007;-45625.0
(24)(8K)
0.018;-36765.6
Q(249)
0.010;-42840.6
(24)(9J)
0.014;-37693.8
T(24T)
0.019;-37693.8
T(24J)
0.010;-42840.6
TK(24)
0.012;-40984.4
(24)(JQ)
0.021;-34909.4
QQ(24)
0.026;-33981.2
24(45)
0.007;-47903.1
44(28)
0.008;-45118.8
244T
0.006;-49337.5
24(4K)
0.015;-40478.1
(25)(47)
0.011;-45118.8
4(25T)
0.007;-48409.4
4Q(25)
0.006;-46553.1
(45)(27)
0.009;-45118.8
29(45)
0.006;-49337.5
2(45Q)
0.007;-46553.1
24(56)
0.004;-52121.9
24(58)
0.004;-50265.6
24(5T)
0.005;-48409.4
24(5Q)
0.006;-46553.1
4(267)
0.006;-50265.6
49(26)
0.006;-48409.4
(26)(4Q)
0.013;-39550.0
27(46)
0.004;-50265.6
2(46T)
0.006;-47481.2
(46)(2K)
0.018;-38621.9
46(28)
0.005;-49337.5
46(2T)
0.007;-47481.2
46(2Q)
0.007;-45625.0
(27)(47)
0.014;-37187.5
4(27T)
0.009;-46553.1
4Q(27)
0.009;-44696.9
(47)(29)
0.010;-41406.2
2J(47)
0.008;-45625.0
47(28)
0.007;-48409.4
47(2T)
0.006;-46553.1
47(2Q)
0.012;-44696.9
(28)(48)
0.018;-35331.3
4(28J)
0.010;-44696.9
4K(28)
0.010;-42840.6
(48)(2J)
0.013;-38621.9
2K(48)
0.011;-42840.6
24(8T)
0.009;-45625.0
24(8Q)
0.008;-43768.8
4(29T)
0.007;-44696.9
4Q(29)
0.010;-42840.6
(49)(2J)
0.015;-37693.8
2K(49)
0.011;-41912.5
24(9J)
0.014;-43768.8
24(9K)
0.012;-41912.5
(2T)(4Q)
0.020;-35837.5
2J(4T)
0.013;-42840.6
4T(2J)
0.011;-42840.6
4T(2K)
0.011;-40984.4
4Q(2J)
0.010;-40984.4
(4J)(2K)
0.028;-33981.2
4J(2K)
0.015;-40056.3
4K(2Q)
0.015;-39128.1
24(QK)
0.015;-39128.1
(25)(56)
0.017;-39043.8
5(259)
0.008;-42334.4
5J(25)
0.017;-40478.1
(2567)
0.005;-49337.5
(256J)
0.009;-45625.0
(25)(67)
0.013;-43262.5
6(25T)
0.007;-46553.1
6Q(25)
0.008;-44696.9
9(257)
0.009;-46553.1
K(257)
0.009;-42840.6
7(25T)
0.008;-45625.0
7Q(25)
0.008;-43768.8
T(258)
0.010;-44696.9
8(259)
0.007;-45625.0
8J(25)
0.007;-43768.8
(259T)
0.011;-43768.8
99(25)
0.014;-38621.9
(25)(9Q)
0.015;-35837.5
(25TQ)
0.013;-40984.4
T(25Q)
0.011;-40984.4
Q(25J)
0.016;-40056.3
(25)(JK)
0.020;-33053.1
QK(25)
0.018;-38200.0
25(57)
0.010;-44190.6
55(2T)
0.012;-41406.2
255Q
0.010;-45625.0
57(26)
0.006;-49337.5
(26)(5T)
0.014;-40478.1
5(26K)
0.009;-43768.8
2(568)
0.006;-48409.4
(56)(2J)
0.012;-39550.0
2K(56)
0.009;-43768.8
25(68)
0.005;-48409.4
25(6T)
0.010;-46553.1
25(6Q)
0.010;-44696.9
5(278)
0.006;-47481.2
5T(27)
0.009;-45625.0
(27)(5K)
0.016;-36765.6
29(57)
0.007;-46553.1
2(57Q)
0.010;-43768.8
25(78)
0.008;-47481.2
25(7T)
0.008;-45625.0
25(7Q)
0.009;-43768.8
5(289)
0.007;-45625.0
5J(28)
0.010;-43768.8
(58)(29)
0.014;-39550.0
2J(58)
0.011;-43768.8
58(29)
0.008;-45625.0
58(2J)
0.011;-43768.8
58(2K)
0.015;-41912.5
5T(29)
0.010;-43768.8
(29)(5K)
0.019;-34909.4
2J(59)
0.013;-42840.6
59(2T)
0.008;-43768.8
59(2Q)
0.011;-41912.5
(2T)(5T)
0.026;-30690.6
5(2TK)
0.012;-40056.3
2(5TQ)
0.011;-40984.4
25(TJ)
0.013;-41912.5
25(TK)
0.016;-40056.3
(2J)(5K)
0.025;-33053.1
2K(5J)
0.011;-39128.1
25(JK)
0.017;-39128.1
(5Q)(2K)
0.021;-32125.0
(2K)(5K)
0.046;-25121.9
6(268)
0.014;-41406.2
6T(26)
0.014;-39550.0
(26)(6K)
0.028;-30690.6
T(267)
0.011;-44696.9
7(268)
0.005;-46553.1
7T(26)
0.012;-44696.9
(26)(7K)
0.018;-35837.5
J(268)
0.009;-42840.6
89(26)
0.008;-44696.9
(26)(8Q)
0.024;-35837.5
(269J)
0.014;-41912.5
(26)(9T)
0.020;-36765.6
9(26K)
0.015;-40056.3
(26TK)
0.015;-39128.1
TQ(26)
0.010;-40056.3
K(26J)
0.017;-38200.0
Q(26Q)
0.022;-32125.0
KK(26)
0.025;-30268.8
66(29)
0.014;-40478.1
266J
0.010;-44696.9
67(27)
0.010;-41406.2
(27)(6T)
0.015;-38621.9
6(27K)
0.013;-41912.5
2(679)
0.007;-45625.0
(67)(2Q)
0.016;-36765.6
27(68)
0.006;-46553.1
27(6T)
0.008;-44696.9
27(6Q)
0.011;-42840.6
68(28)
0.018;-39550.0
(28)(6J)
0.016;-36765.6
28(68)
0.013;-39550.0
2(68J)
0.012;-42840.6
2688
0.009;-45625.0
268T
0.006;-49843.8
268Q
0.005;-47987.5
(29)(6T)
0.022;-36765.6
6(29K)
0.014;-40056.3
2(69J)
0.008;-41912.5
2699
0.008;-43768.8
269J
0.006;-47987.5
269K
0.008;-46131.3
6Q(2T)
0.017;-40056.3
(6T)(2Q)
0.026;-33981.2
2T(6J)
0.015;-40984.4
2T(6K)
0.016;-39128.1
6(2JK)
0.019;-38200.0
2(6JK)
0.012;-38200.0
2J(6K)
0.017;-38200.0
2Q(6Q)
0.020;-32125.0
26QK
0.011;-43346.9
78(27)
0.017;-39550.0
(27)(7J)
0.031;-30690.6
8(278)
0.014;-38621.9
Q(278)
0.009;-40984.4
(27)(8T)
0.019;-36765.6
8(27K)
0.015;-40056.3
(279Q)
0.015;-40056.3
9(27J)
0.014;-40984.4
9K(27)
0.017;-39128.1
TT(27)
0.023;-34909.4
(27)(TK)
0.020;-32125.0
J(27Q)
0.012;-38200.0
K(27Q)
0.018;-36343.8
77(28)
0.013;-39550.0
277T
0.009;-43768.8
27(7K)
0.015;-34909.4
(28)(7T)
0.017;-36765.6
7(28K)
0.014;-40056.3
2(78T)
0.009;-42840.6
(78)(2K)
0.019;-33981.2
78(2T)
0.012;-42840.6
78(2Q)
0.015;-40984.4
(29)(79)
0.030;-30690.6
7(29Q)
0.013;-40056.3
2(79T)
0.013;-41912.5
(79)(2K)
0.022;-33053.1
79(2J)
0.011;-40984.4
79(2K)
0.018;-39128.1
7J(2T)
0.014;-40056.3
(7T)(2J)
0.026;-33981.2
2K(7T)
0.015;-38200.0
27(TQ)
0.013;-39128.1
7(2JQ)
0.017;-38200.0
2(7JQ)
0.013;-38200.0
27(JQ)
0.014;-38200.0
7(2QK)
0.021;-36343.8
7Q(2K)
0.015;-36343.8
88(28)
0.020;-31618.8
(28)(8J)
0.037;-28834.4
9(289)
0.022;-35837.5
K(289)
0.018;-38200.0
9(28Q)
0.015;-39128.1
J(28T)
0.016;-39128.1
TJ(28)
0.012;-39128.1
(28JQ)
0.015;-37271.9
J(28K)
0.017;-36343.8
(28)(QK)
0.032;-29340.6
88(2T)
0.021;-35837.5
288Q
0.014;-40056.3
8T(29)
0.012;-40984.4
(29)(8K)
0.029;-32125.0
2J(89)
0.011;-40056.3
89(2T)
0.010;-40984.4
89(2Q)
0.018;-39128.1
(2T)(8T)
0.035;-27906.3
8(2TK)
0.019;-37271.9
2(8TQ)
0.014;-38200.0
28(TJ)
0.012;-39128.1
28(TK)
0.013;-37271.9
(2J)(8K)
0.031;-30268.8
2K(8J)
0.013;-36343.8
28(JK)
0.023;-36343.8
(8Q)(2K)
0.026;-29340.6
(2K)(8K)
0.033;-22337.5
9(29J)
0.029;-33053.1
9K(29)
0.035;-31196.9
TT(29)
0.017;-33053.1
(29)(TK)
0.021;-30268.8
J(29Q)
0.024;-36343.8
K(29Q)
0.024;-34487.5
99(2T)
0.022;-33981.2
299Q
0.015;-38200.0
9J(2T)
0.014;-38200.0
(9T)(2J)
0.019;-32125.0
2K(9T)
0.016;-36343.8
29(TQ)
0.020;-37271.9
9(2JQ)
0.021;-36343.8
2(9JQ)
0.016;-36343.8
29(JQ)
0.023;-36343.8
9(2QK)
0.020;-34487.5
9Q(2K)
0.024;-34487.5
TT(2T)
0.036;-26050.0
(2T)(TK)
0.044;-23265.6
J(2TQ)
0.022;-35415.6
K(2TQ)
0.019;-33559.4
TT(2J)
0.023;-31196.9
2TTK
0.016;-35415.6
TK(2J)
0.026;-34487.5
2TJJ
0.020;-36343.8
2TJK
0.017;-40562.5
2(TQK)
0.024;-33559.4
TK(2K)
0.036;-26556.3
(2J)(JK)
0.044;-21409.4
QK(2J)
0.023;-32631.2
2J(JK)
0.040;-27484.4
(JQ)(2K)
0.040;-26556.3
(2K)(JK)
0.050;-19553.1
K(2QK)
0.030;-24700.0
2K(QK)
0.040;-24700.0
3335
0.006;-48831.3
3339
0.007;-45118.8
333K
0.011;-41406.2
36(34)
0.008;-46975.0
(34)(39)
0.015;-38115.6
3(34Q)
0.013;-41406.2
33(45)
0.005;-47903.1
34(38)
0.010;-45118.8
334T
0.005;-49337.5
33(4K)
0.015;-40478.1
(35)(37)
0.011;-39043.8
3(35T)
0.014;-42334.4
3Q(35)
0.013;-40478.1
35(37)
0.010;-45118.8
3359
0.005;-49337.5
33(5Q)
0.014;-40478.1
(36)(37)
0.015;-38115.6
3(36T)
0.013;-41406.2
3Q(36)
0.014;-39550.0
36(38)
0.008;-43262.5
336T
0.007;-47481.2
33(6K)
0.019;-38621.9
(37)(39)
0.021;-35331.3
3(37Q)
0.016;-38621.9
33(78)
0.009;-42334.4
37(3J)
0.018;-39550.0
337K
0.009;-43768.8
3T(38)
0.015;-39550.0
(38)(3K)
0.022;-30690.6
338T
0.007;-45625.0
33(8K)
0.021;-36765.6
(39)(3J)
0.023;-31618.8
3399
0.015;-39550.0
33(9Q)
0.013;-36765.6
(3T)(3J)
0.034;-30690.6
33TT
0.016;-37693.8
33(TK)
0.018;-34909.4
(3J)(3K)
0.027;-27906.3
33JK
0.012;-40056.3
33(QK)
0.019;-33053.1
45(34)
0.007;-46975.0
(34)(48)
0.017;-38115.6
4(34J)
0.009;-41406.2
4K(34)
0.016;-39550.0
(3459)
0.005;-48409.4
(345K)
0.010;-44696.9
57(34)
0.005;-50265.6
(34)(5T)
0.014;-41406.2
5(34K)
0.009;-44696.9
(3469)
0.006;-47481.2
(346K)
0.008;-43768.8
68(34)
0.004;-48409.4
(34)(6J)
0.012;-39550.0
7(347)
0.012;-42334.4
J(347)
0.007;-44696.9
78(34)
0.007;-47481.2
(34)(7J)
0.018;-38621.9
8(348)
0.016;-40478.1
Q(348)
0.013;-42840.6
(34)(8T)
0.016;-38621.9
8(34K)
0.012;-41912.5
(349Q)
0.009;-41912.5
9(34J)
0.011;-42840.6
9K(34)
0.011;-40984.4
TT(34)
0.015;-36765.6
(34)(TK)
0.017;-33981.2
J(34Q)
0.015;-40056.3
K(34Q)
0.015;-38200.0
44(35)
0.005;-46975.0
3447
0.004;-51193.8
34(4T)
0.010;-42334.4
44(3K)
0.013;-39550.0
4(357)
0.005;-50265.6
49(35)
0.005;-48409.4
(35)(4Q)
0.013;-39550.0
36(45)
0.004;-51193.8
3(459)
0.007;-48409.4
(45)(3Q)
0.012;-39550.0
35(46)
0.004;-51193.8
35(48)
0.005;-49337.5
35(4T)
0.008;-47481.2
35(4Q)
0.008;-45625.0
46(36)
0.009;-44190.6
(36)(49)
0.015;-41406.2
4(36Q)
0.007;-44696.9
3(467)
0.004;-49337.5
(46)(3T)
0.012;-40478.1
3Q(46)
0.012;-44696.9
3467
0.002;-55412.5
3469
0.002;-53556.3
346J
0.004;-51700.0
346K
0.005;-49843.8
49(37)
0.006;-46553.1
(37)(4Q)
0.018;-37693.8
38(47)
0.007;-47481.2
3(47J)
0.009;-44696.9
3477
0.008;-48409.4
3479
0.003;-52628.1
347J
0.006;-50771.9
347K
0.006;-48915.6
4T(38)
0.007;-44696.9
(38)(4K)
0.020;-35837.5
3T(48)
0.012;-44696.9
3(48K)
0.010;-41912.5
38(4T)
0.007;-44696.9
38(4Q)
0.010;-42840.6
49(39)
0.015;-38621.9
(39)(4Q)
0.016;-35837.5
3T(49)
0.013;-43768.8
3(49K)
0.013;-40984.4
39(4J)
0.008;-42840.6
39(4K)
0.014;-40984.4
4(3TQ)
0.011;-40984.4
3(4TJ)
0.013;-41912.5
34TT
0.012;-42840.6
34TQ
0.005;-47059.4
(3J)(4Q)
0.022;-33981.2
3Q(4J)
0.014;-40056.3
34JQ
0.006;-46131.3
(3Q)(4K)
0.022;-32125.0
3Q(4K)
0.018;-38200.0
5(356)
0.011;-44190.6
58(35)
0.013;-42334.4
(35)(5J)
0.025;-33475.0
6(356)
0.008;-43262.5
T(356)
0.010;-45625.0
6(357)
0.005;-48409.4
69(35)
0.008;-46553.1
(35)(6Q)
0.013;-37693.8
(3579)
0.008;-45625.0
(357K)
0.013;-41912.5
79(35)
0.008;-45625.0
(35)(7Q)
0.018;-36765.6
(358T)
0.009;-43768.8
88(35)
0.011;-39550.0
(35)(8J)
0.019;-36765.6
9(359)
0.014;-37693.8
K(359)
0.014;-40056.3
9(35Q)
0.009;-40984.4
J(35T)
0.009;-40984.4
TJ(35)
0.012;-40984.4
(35JQ)
0.013;-39128.1
J(35K)
0.020;-38200.0
(35)(QK)
0.028;-31196.9
55(37)
0.011;-43262.5
3559
0.009;-47481.2
35(5Q)
0.017;-38621.9
(36)(57)
0.011;-42334.4
5(36T)
0.007;-45625.0
5Q(36)
0.009;-43768.8
(56)(38)
0.011;-41406.2
3T(56)
0.009;-45625.0
3(56K)
0.012;-42840.6
36(58)
0.006;-47481.2
36(5T)
0.007;-45625.0
36(5Q)
0.011;-43768.8
57(37)
0.011;-41406.2
(37)(5T)
0.013;-38621.9
5(37K)
0.012;-41912.5
3(579)
0.008;-45625.0
(57)(3Q)
0.016;-36765.6
37(58)
0.007;-46553.1
37(5T)
0.008;-44696.9
37(5Q)
0.011;-42840.6
58(38)
0.015;-39550.0
(38)(5J)
0.016;-36765.6
38(58)
0.012;-39550.0
3(58J)
0.012;-42840.6
3588
0.007;-45625.0
358T
0.005;-49843.8
358Q
0.007;-47987.5
(39)(5T)
0.017;-36765.6
5(39K)
0.017;-40056.3
3(59J)
0.014;-41912.5
3599
0.010;-43768.8
359J
0.005;-47987.5
359K
0.008;-46131.3
5Q(3T)
0.011;-40056.3
(5T)(3Q)
0.019;-33981.2
3T(5J)
0.014;-40984.4
3T(5K)
0.012;-39128.1
5(3JK)
0.013;-38200.0
3(5JK)
0.016;-38200.0
3J(5K)
0.013;-38200.0
3Q(5Q)
0.022;-32125.0
35QK
0.010;-43346.9
67(36)
0.010;-41406.2
(36)(6T)
0.025;-32546.9
6(36K)
0.018;-35837.5
(367T)
0.012;-43768.8
77(36)
0.010;-40478.1
(36)(7T)
0.020;-37693.8
7(36K)
0.012;-40984.4
(368J)
0.014;-41912.5
(36)(89)
0.012;-37693.8
8(36Q)
0.015;-40984.4
T(369)
0.011;-41912.5
9(36T)
0.012;-41912.5
9Q(36)
0.015;-40056.3
Q(36T)
0.013;-39128.1
(36)(TQ)
0.023;-33053.1
(36JK)
0.013;-37271.9
JK(36)
0.019;-37271.9
K(36K)
0.036;-29340.6
3668
0.008;-46553.1
36(6J)
0.014;-37693.8
(37)(67)
0.018;-34403.1
6(37T)
0.010;-43768.8
6Q(37)
0.012;-41912.5
(67)(39)
0.021;-38621.9
3J(67)
0.010;-42840.6
67(38)
0.007;-45625.0
67(3T)
0.012;-43768.8
67(3Q)
0.010;-41912.5
(38)(68)
0.022;-32546.9
6(38J)
0.010;-41912.5
6K(38)
0.012;-40056.3
(68)(3J)
0.022;-35837.5
3K(68)
0.015;-40056.3
36(8T)
0.011;-42840.6
36(8Q)
0.012;-40984.4
6(39T)
0.009;-41912.5
6Q(39)
0.013;-40056.3
(69)(3J)
0.020;-34909.4
3K(69)
0.016;-39128.1
36(9J)
0.012;-40984.4
36(9K)
0.016;-39128.1
(3T)(6Q)
0.026;-33053.1
3J(6T)
0.013;-40056.3
6T(3J)
0.015;-40056.3
6T(3K)
0.013;-38200.0
6Q(3J)
0.014;-38200.0
(6J)(3K)
0.033;-31196.9
6J(3K)
0.014;-37271.9
6K(3Q)
0.020;-36343.8
36(QK)
0.020;-36343.8
(37)(78)
0.020;-32546.9
7(37J)
0.017;-35837.5
7K(37)
0.017;-33981.2
(378Q)
0.013;-40056.3
8(37T)
0.015;-41912.5
8Q(37)
0.012;-40056.3
J(379)
0.018;-40056.3
9T(37)
0.013;-40984.4
(37)(9K)
0.025;-32125.0
K(37T)
0.020;-37271.9
T(37K)
0.017;-37271.9
JJ(37)
0.026;-32125.0
(37QK)
0.021;-35415.6
3777
0.012;-39550.0
37(7T)
0.020;-36765.6
77(3K)
0.021;-33981.2
7(38T)
0.010;-41912.5
7Q(38)
0.012;-40056.3
(78)(3T)
0.027;-35837.5
3Q(78)
0.014;-40056.3
3789
0.005;-48915.6
378J
0.005;-47059.4
378K
0.010;-45203.1
7J(39)
0.015;-40056.3
(79)(3T)
0.020;-34909.4
3Q(79)
0.016;-39128.1
379T
0.006;-47059.4
379Q
0.008;-45203.1
(3T)(7J)
0.021;-33053.1
3T(7T)
0.019;-33981.2
3(7TK)
0.023;-37271.9
3T(7Q)
0.016;-38200.0
7J(3J)
0.019;-32125.0
(7J)(3Q)
0.036;-31196.9
3J(7Q)
0.014;-37271.9
7Q(3Q)
0.022;-30268.8
37QQ
0.015;-36343.8
37KK
0.025;-34487.5
8(38J)
0.024;-33981.2
8K(38)
0.023;-32125.0
(389K)
0.018;-37271.9
9J(38)
0.015;-39128.1
(38TJ)
0.013;-38200.0
(38)(TJ)
0.020;-32125.0
J(38J)
0.031;-31196.9
JQ(38)
0.018;-36343.8
Q(38K)
0.021;-34487.5
3889
0.015;-41912.5
38(8Q)
0.026;-33053.1
(39)(8T)
0.019;-33981.2
8(39K)
0.016;-37271.9
3(89J)
0.014;-39128.1
3899
0.016;-40984.4
389J
0.006;-45203.1
389K
0.009;-43346.9
8Q(3T)
0.016;-37271.9
(8T)(3Q)
0.026;-31196.9
3T(8J)
0.013;-38200.0
3T(8K)
0.020;-36343.8
8(3JK)
0.017;-35415.6
3(8JK)
0.018;-35415.6
3J(8K)
0.018;-35415.6
3Q(8Q)
0.023;-29340.6
38QK
0.017;-40562.5
9T(39)
0.027;-33053.1
(39)(9K)
0.037;-24193.8
K(39T)
0.023;-35415.6
T(39K)
0.024;-35415.6
JJ(39)
0.021;-30268.8
(39QK)
0.018;-33559.4
3999
0.020;-33981.2
39(9Q)
0.033;-31196.9
(3T)(9J)
0.024;-31196.9
3T(9T)
0.023;-32125.0
3(9TK)
0.014;-35415.6
3T(9Q)
0.015;-36343.8
9J(3J)
0.037;-30268.8
(9J)(3Q)
0.028;-29340.6
3J(9Q)
0.021;-35415.6
9Q(3Q)
0.026;-28412.5
39QQ
0.020;-34487.5
39KK
0.020;-32631.2
T(3TK)
0.037;-28412.5
JJ(3T)
0.024;-29340.6
(3TQK)
0.021;-32631.2
3TTT
0.021;-31196.9
3T(TK)
0.035;-28412.5
(3J)(TK)
0.034;-27484.4
3K(TJ)
0.020;-33559.4
3T(JK)
0.020;-33559.4
(TQ)(3K)
0.033;-26556.3
(3K)(TK)
0.053;-19553.1
J(3JK)
0.047;-26556.3
(3J)(QK)
0.031;-25628.1
JJ(3K)
0.037;-26556.3
3Q(JQ)
0.034;-26556.3
3JQK
0.015;-37778.1
QK(3Q)
0.036;-24700.0
QK(3K)
0.048;-23771.9
44(46)
0.016;-39043.8
44(4T)
0.024;-35331.3
(45)(45)
0.022;-32968.8
4(458)
0.009;-42334.4
4T(45)
0.014;-40478.1
(45)(4K)
0.029;-31618.8
4457
0.006;-49337.5
44(5T)
0.012;-40478.1
45(4K)
0.018;-37693.8
4(468)
0.015;-41406.2
4T(46)
0.018;-39550.0
(46)(4K)
0.031;-30690.6
4468
0.006;-47481.2
44(6J)
0.015;-38621.9
(47)(47)
0.035;-29256.2
4(47T)
0.014;-38621.9
4Q(47)
0.016;-36765.6
47(49)
0.014;-39550.0
447J
0.008;-43768.8
48(48)
0.021;-33475.0
(48)(4J)
0.029;-30690.6
4488
0.015;-39550.0
44(8J)
0.021;-36765.6
(49)(49)
0.044;-25543.8
4(49Q)
0.021;-34909.4
44(9T)
0.015;-36765.6
49(4K)
0.026;-33981.2
4(4TQ)
0.018;-33981.2
44(TJ)
0.022;-34909.4
(4J)(4J)
0.040;-21831.2
44JJ
0.018;-33981.2
4Q(4Q)
0.036;-26050.0
(4K)(4K)
0.066;-18118.8
(45)(57)
0.021;-36259.4
5(45T)
0.014;-39550.0
5Q(45)
0.020;-37693.8
8(456)
0.007;-46553.1
Q(456)
0.010;-42840.6
(45)(68)
0.011;-40478.1
6(45J)
0.009;-43768.8
6K(45)
0.011;-41912.5
(457J)
0.012;-42840.6
(45)(78)
0.012;-39550.0
7(45J)
0.013;-42840.6
7K(45)
0.012;-40984.4
(458Q)
0.012;-40984.4
8(45T)
0.009;-42840.6
8Q(45)
0.010;-40984.4
J(459)
0.013;-40984.4
9T(45)
0.013;-41912.5
(45)(9K)
0.021;-33053.1
K(45T)
0.014;-38200.0
T(45K)
0.020;-38200.0
JJ(45)
0.021;-33053.1
(45QK)
0.013;-36343.8
4555
0.011;-44190.6
45(58)
0.013;-41406.2
55(4J)
0.015;-38621.9
455K
0.011;-42840.6
58(46)
0.009;-46553.1
(46)(5J)
0.013;-37693.8
46(56)
0.009;-42334.4
4(569)
0.009;-45625.0
(56)(4Q)
0.015;-36765.6
46(57)
0.005;-47481.2
46(59)
0.008;-45625.0
46(5J)
0.009;-43768.8
46(5K)
0.013;-41912.5
5(479)
0.009;-44696.9
5J(47)
0.010;-42840.6
(57)(48)
0.010;-39550.0
4T(57)
0.010;-43768.8
4(57K)
0.011;-40984.4
47(59)
0.009;-44696.9
47(5J)
0.009;-42840.6
47(5K)
0.010;-40984.4
5(48T)
0.010;-42840.6
5Q(48)
0.012;-40984.4
(58)(4T)
0.019;-36765.6
4Q(58)
0.014;-40984.4
4589
0.005;-49843.8
458J
0.007;-47987.5
458K
0.008;-46131.3
5J(49)
0.013;-40984.4
(59)(4T)
0.014;-35837.5
4Q(59)
0.015;-40056.3
459T
0.005;-47987.5
459Q
0.010;-46131.3
(4T)(5J)
0.019;-33981.2
4T(5T)
0.020;-34909.4
4(5TK)
0.014;-38200.0
4T(5Q)
0.017;-39128.1
5J(4J)
0.021;-33053.1
(5J)(4Q)
0.026;-32125.0
4J(5Q)
0.019;-38200.0
5Q(4Q)
0.028;-31196.9
45QQ
0.020;-37271.9
45KK
0.017;-35415.6
6(469)
0.011;-38621.9
6J(46)
0.019;-36765.6
(4678)
0.011;-44696.9
(467Q)
0.014;-40984.4
7(469)
0.008;-43768.8
7J(46)
0.012;-41912.5
(4689)
0.008;-42840.6
(468K)
0.013;-39128.1
8T(46)
0.011;-41912.5
(46)(8K)
0.021;-33053.1
Q(469)
0.019;-39128.1
(46)(9J)
0.025;-33981.2
T(46T)
0.020;-33981.2
T(46J)
0.013;-39128.1
TK(46)
0.012;-37271.9
(46)(JQ)
0.027;-31196.9
QQ(46)
0.028;-30268.8
46(67)
0.012;-40478.1
66(4T)
0.018;-37693.8
466Q
0.014;-41912.5
68(47)
0.007;-44696.9
(47)(6J)
0.020;-35837.5
47(67)
0.014;-39550.0
4(67T)
0.012;-42840.6
(67)(4K)
0.021;-33981.2
67(49)
0.009;-43768.8
67(4J)
0.012;-41912.5
67(4K)
0.013;-40056.3
69(48)
0.010;-42840.6
(48)(6Q)
0.023;-33981.2
49(68)
0.010;-42840.6
4(68Q)
0.015;-40056.3
46(89)
0.010;-42840.6
46(8J)
0.012;-40984.4
46(8K)
0.013;-39128.1
(49)(6J)
0.029;-33981.2
49(69)
0.020;-35837.5
4(69Q)
0.016;-39128.1
46(9T)
0.015;-40984.4
46(9Q)
0.013;-39128.1
6(4TJ)
0.018;-39128.1
6K(4T)
0.015;-37271.9
(6T)(4K)
0.021;-31196.9
6T(4Q)
0.013;-38200.0
(4J)(6J)
0.041;-26050.0
4J(6J)
0.027;-32125.0
6J(4Q)
0.015;-37271.9
(4Q)(6Q)
0.048;-24193.8
4K(6Q)
0.022;-35415.6
4K(6K)
0.031;-28412.5
79(47)
0.017;-36765.6
(47)(7Q)
0.032;-27906.3
(478T)
0.009;-40984.4
88(47)
0.021;-36765.6
(47)(8J)
0.026;-33981.2
9(479)
0.018;-34909.4
K(479)
0.016;-37271.9
9(47Q)
0.013;-38200.0
J(47T)
0.013;-38200.0
TJ(47)
0.018;-38200.0
(47JQ)
0.015;-36343.8
J(47K)
0.022;-35415.6
(47)(QK)
0.030;-28412.5
77(49)
0.017;-36765.6
477J
0.011;-40984.4
78(48)
0.018;-36765.6
(48)(7J)
0.024;-33981.2
48(78)
0.015;-36765.6
4(78J)
0.013;-40056.3
4788
0.011;-42840.6
478T
0.007;-47059.4
478Q
0.007;-45203.1
(49)(7T)
0.022;-33981.2
7(49K)
0.018;-37271.9
4(79J)
0.014;-39128.1
4799
0.010;-40984.4
479J
0.010;-45203.1
479K
0.008;-43346.9
7Q(4T)
0.014;-37271.9
(7T)(4Q)
0.023;-31196.9
4T(7J)
0.013;-38200.0
4T(7K)
0.021;-36343.8
7(4JK)
0.017;-35415.6
4(7JK)
0.018;-35415.6
4J(7K)
0.018;-35415.6
4Q(7Q)
0.038;-29340.6
47QK
0.017;-40562.5
89(48)
0.017;-34909.4
(48)(8Q)
0.033;-26050.0
(489J)
0.015;-38200.0
(48)(9T)
0.023;-33053.1
9(48K)
0.017;-36343.8
(48TK)
0.016;-35415.6
TQ(48)
0.019;-36343.8
K(48J)
0.022;-34487.5
Q(48Q)
0.040;-28412.5
KK(48)
0.026;-26556.3
88(4J)
0.021;-33053.1
488K
0.017;-37271.9
8J(49)
0.021;-38200.0
(89)(4T)
0.023;-33053.1
4Q(89)
0.015;-37271.9
489T
0.009;-45203.1
489Q
0.010;-43346.9
(4T)(8J)
0.024;-31196.9
4T(8T)
0.025;-32125.0
4(8TK)
0.021;-35415.6
4T(8Q)
0.015;-36343.8
8J(4J)
0.027;-30268.8
(8J)(4Q)
0.034;-29340.6
4J(8Q)
0.016;-35415.6
8Q(4Q)
0.029;-28412.5
48QQ
0.022;-34487.5
48KK
0.029;-32631.2
9(49Q)
0.025;-30268.8
J(49T)
0.016;-36343.8
TJ(49)
0.023;-36343.8
(49JQ)
0.024;-34487.5
J(49K)
0.024;-33559.4
(49)(QK)
0.032;-26556.3
99(4J)
0.033;-31196.9
499K
0.024;-35415.6
9Q(4T)
0.024;-35415.6
(9T)(4Q)
0.025;-29340.6
4T(9J)
0.018;-36343.8
4T(9K)
0.018;-34487.5
9(4JK)
0.020;-33559.4
4(9JK)
0.019;-33559.4
4J(9K)
0.025;-33559.4
4Q(9Q)
0.026;-27484.4
49QK
0.012;-38706.3
TJ(4T)
0.037;-29340.6
(4TJQ)
0.023;-33559.4
J(4TK)
0.022;-32631.2
(4T)(QK)
0.035;-25628.1
TT(4Q)
0.038;-28412.5
T(4JQ)
0.019;-33559.4
4(TJQ)
0.021;-33559.4
4T(JQ)
0.025;-33559.4
T(4QK)
0.032;-31703.1
TQ(4K)
0.022;-31703.1
JJ(4J)
0.042;-21409.4
(4JQK)
0.024;-30775.0
4JJJ
0.034;-27484.4
JQ(4Q)
0.037;-25628.1
4JQQ
0.020;-31703.1
4JKK
0.036;-29846.9
QQ(4K)
0.059;-23771.9
4KKK
0.046;-21915.6
55(59)
0.026;-33475.0
55(5K)
0.030;-29762.5
(56)(58)
0.031;-33475.0
5(56J)
0.014;-36765.6
5K(56)
0.017;-34909.4
56(59)
0.016;-38621.9
556J
0.012;-42840.6
57(57)
0.024;-33475.0
(57)(5T)
0.021;-30690.6
5(57K)
0.021;-33981.2
55(79)
0.012;-37693.8
57(5Q)
0.023;-34909.4
5(589)
0.021;-36765.6
5J(58)
0.025;-34909.4
58(59)
0.014;-36765.6
558J
0.016;-40984.4
59(59)
0.023;-29762.5
(59)(5Q)
0.031;-26978.1
559T
0.012;-40984.4
55(9K)
0.024;-32125.0
(5T)(5Q)
0.032;-26050.0
55TJ
0.019;-39128.1
5J(5J)
0.042;-26050.0
5J(5Q)
0.026;-31196.9
5(5QK)
0.037;-29340.6
5K(5K)
0.033;-22337.5
68(56)
0.015;-38621.9
(56)(6J)
0.027;-29762.5
7(567)
0.012;-38621.9
J(567)
0.011;-40984.4
78(56)
0.007;-43768.8
(56)(7J)
0.027;-34909.4
8(568)
0.021;-36765.6
Q(568)
0.015;-39128.1
(56)(8T)
0.023;-34909.4
8(56K)
0.013;-38200.0
(569Q)
0.016;-38200.0
9(56J)
0.013;-39128.1
9K(56)
0.022;-37271.9
TT(56)
0.022;-33053.1
(56)(TK)
0.029;-30268.8
J(56Q)
0.017;-36343.8
K(56Q)
0.017;-34487.5
66(57)
0.012;-39550.0
5669
0.009;-43768.8
56(6Q)
0.020;-34909.4
(57)(68)
0.018;-37693.8
6(57J)
0.015;-40984.4
6K(57)
0.016;-39128.1
(67)(5T)
0.019;-35837.5
5Q(67)
0.018;-40056.3
5678
0.005;-49843.8
567T
0.007;-47987.5
567Q
0.011;-46131.3
(58)(69)
0.017;-35837.5
6(58Q)
0.015;-39128.1
5(689)
0.011;-41912.5
(68)(5Q)
0.019;-33053.1
58(69)
0.013;-41912.5
58(6J)
0.010;-40056.3
58(6K)
0.013;-38200.0
6(59J)
0.013;-39128.1
6K(59)
0.020;-37271.9
(69)(5Q)
0.028;-32125.0
59(6T)
0.014;-40056.3
59(6Q)
0.018;-38200.0
6T(5T)
0.030;-33053.1
(5T)(6K)
0.035;-30268.8
5Q(6T)
0.013;-37271.9
56TJ
0.009;-44275.0
56TK
0.009;-42418.8
6K(5J)
0.018;-35415.6
56JJ
0.017;-37271.9
56JK
0.012;-41490.6
5(6QK)
0.019;-34487.5
6K(5K)
0.034;-27484.4
(57)(79)
0.025;-29762.5
7(57Q)
0.021;-33053.1
9(578)
0.013;-40984.4
K(578)
0.019;-37271.9
8(57J)
0.013;-39128.1
8K(57)
0.023;-37271.9
(579K)
0.017;-36343.8
9J(57)
0.016;-38200.0
(57TJ)
0.015;-37271.9
(57)(TJ)
0.024;-31196.9
J(57J)
0.035;-30268.8
JQ(57)
0.018;-35415.6
Q(57K)
0.018;-33559.4
5778
0.011;-42840.6
57(7J)
0.020;-33981.2
(58)(78)
0.024;-29762.5
7(58J)
0.014;-39128.1
7K(58)
0.014;-37271.9
(78)(5J)
0.024;-33053.1
5K(78)
0.013;-37271.9
57(8T)
0.013;-40056.3
57(8Q)
0.018;-38200.0
7(59T)
0.015;-39128.1
7Q(59)
0.018;-37271.9
(79)(5J)
0.020;-32125.0
5K(79)
0.021;-36343.8
57(9J)
0.013;-38200.0
57(9K)
0.020;-36343.8
(5T)(7Q)
0.024;-30268.8
5J(7T)
0.016;-37271.9
7T(5J)
0.016;-37271.9
7T(5K)
0.020;-35415.6
7Q(5J)
0.019;-35415.6
(7J)(5K)
0.030;-28412.5
7J(5K)
0.015;-34487.5
7K(5Q)
0.018;-33559.4
57(QK)
0.024;-33559.4
(58)(89)
0.038;-27906.3
8(58Q)
0.035;-31196.9
T(589)
0.015;-38200.0
9(58T)
0.018;-38200.0
9Q(58)
0.022;-36343.8
Q(58T)
0.023;-35415.6
(58)(TQ)
0.023;-29340.6
(58JK)
0.019;-33559.4
JK(58)
0.027;-33559.4
K(58K)
0.032;-25628.1
588T
0.015;-39128.1
58(8K)
0.028;-30268.8
(59)(8J)
0.021;-31196.9
59(89)
0.020;-33053.1
5(89Q)
0.015;-36343.8
58(9T)
0.013;-38200.0
58(9Q)
0.017;-36343.8
8(5TJ)
0.023;-36343.8
8K(5T)
0.025;-34487.5
(8T)(5K)
0.034;-28412.5
8T(5Q)
0.015;-35415.6
(5J)(8J)
0.036;-23265.6
5J(8J)
0.027;-29340.6
8J(5Q)
0.020;-34487.5
(5Q)(8Q)
0.039;-21409.4
5K(8Q)
0.023;-32631.2
5K(8K)
0.047;-25628.1
9J(59)
0.020;-30268.8
(59TJ)
0.025;-35415.6
(59)(TJ)
0.031;-29340.6
J(59J)
0.027;-28412.5
JQ(59)
0.019;-33559.4
Q(59K)
0.027;-31703.1
599T
0.018;-37271.9
59(9K)
0.030;-28412.5
(5T)(9Q)
0.027;-28412.5
5J(9T)
0.018;-35415.6
9T(5J)
0.016;-35415.6
9T(5K)
0.021;-33559.4
9Q(5J)
0.016;-33559.4
(9J)(5K)
0.044;-26556.3
9J(5K)
0.025;-32631.2
9K(5Q)
0.022;-31703.1
59(QK)
0.027;-31703.1
(5T)(TJ)
0.045;-22337.5
J(5TJ)
0.028;-27484.4
JQ(5T)
0.025;-32631.2
Q(5TK)
0.024;-30775.0
5TTJ
0.028;-34487.5
TJ(5J)
0.033;-27484.4
(TJ)(5Q)
0.028;-26556.3
5J(TQ)
0.021;-32631.2
TQ(5Q)
0.043;-25628.1
5TQQ
0.024;-31703.1
5TKK
0.028;-29846.9
Q(5JQ)
0.051;-24700.0
KK(5J)
0.041;-22843.7
(5Q)(JQ)
0.074;-18625.0
5K(JQ)
0.025;-29846.9
5K(JK)
0.034;-22843.7
5QQQ
0.046;-23771.9
KK(5K)
0.055;-14912.5
6669
0.016;-36765.6
666K
0.017;-33053.1
69(67)
0.020;-35837.5
(67)(6Q)
0.037;-26978.1
6678
0.011;-42840.6
66(7J)
0.030;-33981.2
(68)(68)
0.035;-23687.5
6(68J)
0.024;-33053.1
6K(68)
0.025;-31196.9
68(6J)
0.022;-33053.1
668K
0.015;-37271.9
6J(69)
0.020;-32125.0
69(6T)
0.023;-33053.1
669Q
0.017;-37271.9
6J(6T)
0.024;-31196.9
6T(6J)
0.021;-31196.9
66TK
0.022;-35415.6
6K(6J)
0.028;-28412.5
(6Q)(6Q)
0.051;-16262.5
66QK
0.024;-33559.4
7(679)
0.020;-34909.4
7J(67)
0.023;-33053.1
(6789)
0.011;-40056.3
(678K)
0.018;-36343.8
8T(67)
0.020;-39128.1
(67)(8K)
0.024;-30268.8
Q(679)
0.022;-36343.8
(67)(9J)
0.025;-31196.9
T(67T)
0.029;-31196.9
T(67J)
0.021;-36343.8
TK(67)
0.023;-34487.5
(67)(JQ)
0.038;-28412.5
QQ(67)
0.030;-27484.4
67(78)
0.017;-35837.5
77(6J)
0.028;-33053.1
677K
0.022;-37271.9
7T(68)
0.012;-39128.1
(68)(7K)
0.022;-30268.8
6T(78)
0.014;-39128.1
6(78K)
0.015;-36343.8
68(7T)
0.013;-39128.1
68(7Q)
0.018;-37271.9
79(69)
0.029;-33053.1
(69)(7Q)
0.023;-30268.8
6T(79)
0.015;-38200.0
6(79K)
0.021;-35415.6
69(7J)
0.021;-37271.9
69(7K)
0.015;-35415.6
7(6TQ)
0.021;-35415.6
6(7TJ)
0.016;-36343.8
67TT
0.017;-37271.9
67TQ
0.011;-41490.6
(6J)(7Q)
0.035;-28412.5
6Q(7J)
0.015;-34487.5
67JQ
0.017;-40562.5
(6Q)(7K)
0.027;-26556.3
6Q(7K)
0.030;-32631.2
8(689)
0.020;-33053.1
8J(68)
0.027;-31196.9
(689T)
0.018;-37271.9
99(68)
0.025;-32125.0
(68)(9Q)
0.027;-29340.6
(68TQ)
0.028;-34487.5
T(68Q)
0.015;-34487.5
Q(68J)
0.023;-33559.4
(68)(JK)
0.034;-26556.3
QK(68)
0.028;-31703.1
68(8T)
0.021;-32125.0
88(6K)
0.027;-29340.6
8(69J)
0.019;-36343.8
8K(69)
0.022;-34487.5
(89)(6Q)
0.026;-29340.6
69(8T)
0.018;-37271.9
69(8Q)
0.016;-35415.6
8T(6T)
0.033;-30268.8
(6T)(8K)
0.032;-27484.4
6Q(8T)
0.023;-34487.5
68TJ
0.011;-41490.6
68TK
0.013;-39634.4
8K(6J)
0.020;-32631.2
68JJ
0.023;-34487.5
68JK
0.015;-38706.3
6(8QK)
0.025;-31703.1
8K(6K)
0.039;-24700.0
(69)(9J)
0.038;-23265.6
T(69T)
0.030;-29340.6
T(69J)
0.024;-34487.5
TK(69)
0.033;-32631.2
(69)(JQ)
0.028;-26556.3
QQ(69)
0.049;-25628.1
69(9T)
0.029;-30268.8
99(6K)
0.041;-27484.4
9(6TQ)
0.016;-33559.4
6(9TJ)
0.023;-34487.5
69TT
0.020;-35415.6
69TQ
0.012;-39634.4
(6J)(9Q)
0.039;-26556.3
6Q(9J)
0.027;-32631.2
69JQ
0.012;-38706.3
(6Q)(9K)
0.050;-24700.0
6Q(9K)
0.024;-30775.0
T(6TJ)
0.030;-27484.4
TK(6T)
0.040;-25628.1
(6T)(JQ)
0.030;-25628.1
QQ(6T)
0.043;-24700.0
6T(TJ)
0.033;-27484.4
(6J)(TJ)
0.041;-20481.3
6J(TJ)
0.039;-26556.3
TJ(6Q)
0.026;-31703.1
(6Q)(TQ)
0.060;-18625.0
6K(TQ)
0.024;-29846.9
6K(TK)
0.050;-22843.7
JK(6J)
0.044;-23771.9
K(6JK)
0.050;-21915.6
6JJK
0.026;-29846.9
6(JQK)
0.034;-28918.7
JK(6K)
0.043;-21915.6
KK(6Q)
0.040;-20987.5
6QKK
0.035;-27062.5
77(7T)
0.028;-26978.1
(78)(78)
0.036;-21831.2
7(78J)
0.029;-31196.9
7K(78)
0.038;-29340.6
78(7J)
0.022;-31196.9
778K
0.021;-35415.6
7J(79)
0.036;-30268.8
79(7T)
0.023;-31196.9
779Q
0.021;-35415.6
7J(7T)
0.027;-29340.6
7T(7J)
0.027;-29340.6
77TK
0.024;-33559.4
7K(7J)
0.044;-26556.3
(7Q)(7Q)
0.075;-14406.2
77QK
0.029;-31703.1
8(78T)
0.021;-31196.9
8Q(78)
0.028;-29340.6
J(789)
0.024;-35415.6
9T(78)
0.021;-36343.8
(78)(9K)
0.027;-27484.4
K(78T)
0.019;-32631.2
T(78K)
0.017;-32631.2
JJ(78)
0.030;-27484.4
(78QK)
0.033;-30775.0
7888
0.025;-33053.1
78(8J)
0.028;-30268.8
(79)(89)
0.043;-25121.9
8(79Q)
0.017;-34487.5
7(89T)
0.014;-36343.8
(89)(7K)
0.034;-27484.4
89(7J)
0.021;-35415.6
89(7K)
0.016;-33559.4
8J(7T)
0.023;-34487.5
(8T)(7J)
0.028;-28412.5
7K(8T)
0.019;-32631.2
78(TQ)
0.020;-33559.4
8(7JQ)
0.025;-32631.2
7(8JQ)
0.025;-32631.2
78(JQ)
0.018;-32631.2
8(7QK)
0.026;-30775.0
8Q(7K)
0.019;-30775.0
99(79)
0.033;-24193.8
(79)(9Q)
0.052;-21409.4
(79TQ)
0.017;-32631.2
T(79Q)
0.032;-32631.2
Q(79J)
0.023;-31703.1
(79)(JK)
0.039;-24700.0
QK(79)
0.029;-29846.9
79(9J)
0.027;-28412.5
(7T)(9T)
0.039;-22337.5
9(7TK)
0.018;-31703.1
7(9TQ)
0.023;-32631.2
79(TJ)
0.022;-33559.4
79(TK)
0.032;-31703.1
(7J)(9K)
0.037;-24700.0
7K(9J)
0.028;-30775.0
79(JK)
0.028;-30775.0
(9Q)(7K)
0.048;-23771.9
(7K)(9K)
0.058;-16768.8
T(7TQ)
0.029;-25628.1
Q(7TJ)
0.030;-30775.0
(7T)(JK)
0.037;-23771.9
QK(7T)
0.040;-28918.7
7T(TQ)
0.039;-25628.1
(7J)(TQ)
0.052;-24700.0
7Q(TJ)
0.035;-30775.0
7TJQ
0.016;-36850.0
(7Q)(TK)
0.048;-22843.7
7Q(TK)
0.034;-28918.7
J(7JQ)
0.032;-23771.9
K(7JQ)
0.037;-27990.6
JJ(7Q)
0.034;-23771.9
J(7QK)
0.030;-27990.6
JQ(7K)
0.037;-27990.6
QQ(7Q)
0.059;-15840.6
7Q(QK)
0.045;-20987.5
8888
0.034;-26050.0
888Q
0.037;-28412.5
8(89J)
0.027;-28412.5
8K(89)
0.046;-26556.3
89(8Q)
0.031;-27484.4
8(8TJ)
0.029;-27484.4
8K(8T)
0.031;-25628.1
8T(8K)
0.044;-25628.1
8(8JK)
0.039;-24700.0
88(JK)
0.042;-24700.0
8Q(8K)
0.034;-23771.9
(89)(9T)
0.047;-22337.5
9(89K)
0.031;-25628.1
(89TK)
0.023;-30775.0
TQ(89)
0.027;-31703.1
K(89J)
0.032;-29846.9
Q(89Q)
0.039;-23771.9
KK(89)
0.033;-21915.6
99(8Q)
0.028;-26556.3
9(8TJ)
0.019;-32631.2
9K(8T)
0.023;-30775.0
(9T)(8K)
0.028;-24700.0
9T(8Q)
0.029;-31703.1
(8J)(9J)
0.063;-19553.1
8J(9J)
0.033;-25628.1
9J(8Q)
0.032;-30775.0
(8Q)(9Q)
0.049;-17696.9
8K(9Q)
0.026;-28918.7
8K(9K)
0.041;-21915.6
TQ(8T)
0.041;-24700.0
K(8TJ)
0.031;-28918.7
Q(8TQ)
0.038;-22843.7
KK(8T)
0.047;-20987.5
