AAAA
0.389;-70.0
5AAA
0.249;-4558.8
9AAA
0.262;-3403.7
KAAA
0.307;-2248.7
4A(2A)
0.242;-8312.5
(2A)(7A)
0.217;-5556.3
A(2TA)
0.245;-6580.0
QA(2A)
0.294;-6002.5
2A(4A)
0.231;-8312.5
26AA
0.219;-9625.0
AA(29)
0.225;-6868.7
2A(QA)
0.295;-6002.5
A(34A)
0.236;-8023.8
6A(3A)
0.201;-7446.2
(3A)(9A)
0.232;-4690.0
A(3QA)
0.257;-5713.8
AA(34)
0.214;-8023.8
3A(7A)
0.268;-7157.5
39AA
0.204;-8470.0
AA(3Q)
0.244;-5713.8
(4A)(5A)
0.219;-5556.3
A(48A)
0.212;-6580.0
TA(4A)
0.240;-6002.5
(4A)(KA)
0.277;-3246.2
46AA
0.214;-9047.5
AA(49)
0.188;-6291.2
4A(QA)
0.274;-5425.0
A(56A)
0.231;-6868.7
8A(5A)
0.214;-6291.2
(5A)(JA)
0.270;-3535.0
55AA
0.251;-7157.5
AA(58)
0.276;-6291.2
5A(JA)
0.235;-5425.0
5KAA
0.253;-6737.5
8A(6A)
0.248;-6002.5
(6A)(JA)
0.354;-3246.2
66AA
0.260;-6580.0
AA(69)
0.227;-5713.8
6A(QA)
0.243;-4847.5
A(78A)
0.256;-5713.8
TA(7A)
0.286;-5136.2
(7A)(KA)
0.265;-2380.0
79AA
0.195;-7315.0
AA(7Q)
0.306;-4558.8
(8A)(9A)
0.292;-3246.2
A(8QA)
0.245;-4270.0
AA(89)
0.273;-5136.2
8A(QA)
0.298;-4270.0
A(9TA)
0.237;-4558.8
QA(9A)
0.287;-3981.3
9A(JA)
0.324;-4270.0
9KAA
0.245;-5582.5
QA(TA)
0.280;-3692.5
TA(QA)
0.272;-3692.5
A(JQA)
0.325;-3403.8
AA(JQ)
0.332;-3403.8
(QA)(KA)
0.322;-936.3
KKAA
0.335;-2537.5
2(25A)
0.184;-11488.8
27(2A)
0.195;-10911.2
(2T)(2A)
0.252;-8155.0
2(2KA)
0.211;-9178.7
(236A)
0.157;-12801.2
(23TA)
0.156;-11646.2
33(2A)
0.208;-11777.5
(36)(2A)
0.242;-10911.2
3(29A)
0.159;-11935.0
3J(2A)
0.188;-11357.5
(245A)
0.158;-12801.2
(249A)
0.164;-11646.2
(24KA)
0.173;-10491.2
46(2A)
0.164;-12512.5
(49)(2A)
0.212;-9756.2
4(2QA)
0.211;-10780.0
6(25A)
0.121;-12223.7
T(25A)
0.182;-11068.8
5(26A)
0.179;-12223.7
58(2A)
0.180;-11646.2
(5J)(2A)
0.195;-8890.0
6(26A)
0.182;-10045.0
T(26A)
0.151;-10780.0
6(27A)
0.187;-11646.2
69(2A)
0.193;-11068.8
(6Q)(2A)
0.226;-8312.5
(279A)
0.180;-10780.0
(27KA)
0.164;-9625.0
79(2A)
0.232;-10780.0
(7Q)(2A)
0.241;-8023.8
(28TA)
0.168;-10202.5
88(2A)
0.185;-8890.0
(8J)(2A)
0.218;-8023.8
9(29A)
0.184;-8312.5
K(29A)
0.226;-9047.5
9(2QA)
0.202;-9336.2
J(2TA)
0.240;-9336.2
TJ(2A)
0.230;-9336.2
(2JQA)
0.239;-8758.7
J(2KA)
0.202;-8470.0
(QK)(2A)
0.224;-6291.2
22(4A)
0.176;-11777.5
226A
0.173;-13090.0
2A(29)
0.193;-10333.7
22(QA)
0.150;-9467.5
2(34A)
0.158;-13378.8
26(3A)
0.191;-12801.2
(29)(3A)
0.154;-10045.0
2(3QA)
0.193;-11068.8
A(234)
0.147;-13378.8
(23)(7A)
0.221;-10622.5
9A(23)
0.168;-11935.0
A(23Q)
0.157;-11068.8
2A(34)
0.155;-13378.8
2A(36)
0.159;-12801.2
2A(38)
0.161;-12223.7
2A(3T)
0.165;-11646.2
2A(3Q)
0.172;-11068.8
2(45A)
0.129;-12801.2
27(4A)
0.145;-12223.7
(2T)(4A)
0.173;-9467.5
2(4KA)
0.196;-10491.2
A(246)
0.186;-12512.5
(24)(9A)
0.183;-9756.2
JA(24)
0.193;-11068.8
24(5A)
0.150;-12801.2
24(7A)
0.146;-12223.7
24(9A)
0.188;-11646.2
24(JA)
0.193;-11068.8
24(KA)
0.183;-10491.2
26(5A)
0.186;-12223.7
(29)(5A)
0.167;-9467.5
2(5QA)
0.215;-10491.2
A(256)
0.172;-12223.7
(25)(9A)
0.159;-9467.5
JA(25)
0.181;-10780.0
25(6A)
0.148;-12223.7
25(8A)
0.158;-11646.2
25(TA)
0.170;-11068.8
25(QA)
0.207;-10491.2
(26)(6A)
0.199;-8155.0
2(69A)
0.197;-11068.8
2J(6A)
0.188;-10491.2
(26)(7A)
0.224;-9756.2
9A(26)
0.145;-11068.8
A(26Q)
0.195;-10202.5
2A(67)
0.201;-11646.2
2A(69)
0.205;-11068.8
2A(6J)
0.183;-10491.2
2A(6K)
0.193;-9913.8
(29)(7A)
0.229;-8890.0
2(7QA)
0.180;-9913.8
A(278)
0.179;-11068.8
(27)(JA)
0.230;-8312.5
KA(27)
0.196;-9625.0
2A(79)
0.188;-10780.0
2A(7J)
0.227;-10202.5
2A(7K)
0.170;-9625.0
(2T)(8A)
0.236;-8312.5
2(8KA)
0.209;-9336.2
A(28T)
0.142;-10202.5
(28)(KA)
0.200;-7446.2
28(TA)
0.174;-10202.5
28(QA)
0.185;-9625.0
(29)(9A)
0.193;-6422.5
2(9QA)
0.248;-9336.2
A(29T)
0.201;-9913.8
(29)(KA)
0.206;-7157.5
29(JA)
0.200;-9625.0
29(KA)
0.218;-9047.5
2J(TA)
0.231;-9336.2
(2T)(JA)
0.191;-7446.2
KA(2T)
0.211;-8758.7
2A(TQ)
0.207;-9047.5
2(JQA)
0.219;-8758.7
A(2JQ)
0.185;-8758.7
2A(JQ)
0.191;-8758.7
2(QKA)
0.232;-8181.2
2Q(KA)
0.223;-8181.2
33(3A)
0.233;-9598.7
(36)(3A)
0.179;-8732.5
3(39A)
0.232;-9756.2
3J(3A)
0.186;-9178.7
(345A)
0.116;-12512.5
(349A)
0.178;-11357.5
(34KA)
0.216;-10202.5
46(3A)
0.167;-12223.7
(49)(3A)
0.174;-9467.5
4(3QA)
0.172;-10491.2
6(35A)
0.135;-11935.0
T(35A)
0.193;-10780.0
5(36A)
0.192;-11935.0
58(3A)
0.230;-11357.5
(5J)(3A)
0.160;-8601.2
6(36A)
0.206;-9756.2
T(36A)
0.204;-10491.2
6(37A)
0.143;-11357.5
69(3A)
0.241;-10780.0
(6Q)(3A)
0.193;-8023.8
(379A)
0.182;-10491.2
(37KA)
0.205;-9336.2
79(3A)
0.184;-10491.2
(7Q)(3A)
0.211;-7735.0
(38TA)
0.169;-9913.8
88(3A)
0.222;-8601.2
(8J)(3A)
0.181;-7735.0
9(39A)
0.224;-8023.8
K(39A)
0.197;-8758.7
9(3QA)
0.223;-9047.5
J(3TA)
0.156;-9047.5
TJ(3A)
0.159;-9047.5
(3JQA)
0.209;-8470.0
J(3KA)
0.190;-8181.2
(QK)(3A)
0.285;-6002.5
33(5A)
0.199;-10911.2
337A
0.164;-12223.7
3A(3T)
0.243;-9467.5
33(KA)
0.172;-8601.2
3(46A)
0.155;-12223.7
38(4A)
0.175;-11646.2
(3J)(4A)
0.209;-8890.0
4A(34)
0.142;-10911.2
A(347)
0.136;-11935.0
(34)(TA)
0.161;-9178.7
QA(34)
0.177;-10491.2
345A
0.120;-14402.5
347A
0.124;-13825.0
349A
0.151;-13247.5
34JA
0.158;-12670.0
34KA
0.197;-12092.5
37(5A)
0.160;-11646.2
(3T)(5A)
0.169;-8890.0
3(5KA)
0.193;-9913.8
A(357)
0.199;-11646.2
(35)(TA)
0.178;-8890.0
QA(35)
0.171;-10202.5
356A
0.143;-13825.0
358A
0.189;-13247.5
35TA
0.158;-12670.0
35QA
0.146;-12092.5
(37)(6A)
0.220;-9467.5
3(6TA)
0.170;-10491.2
3Q(6A)
0.152;-9913.8
(36)(8A)
0.236;-9178.7
TA(36)
0.181;-10491.2
A(36K)
0.236;-9625.0
6A(38)
0.208;-11068.8
6A(3T)
0.187;-10491.2
6A(3Q)
0.201;-9913.8
37(7A)
0.191;-9178.7
(3T)(7A)
0.204;-8312.5
3(7KA)
0.248;-9336.2
A(379)
0.181;-10491.2
(37)(QA)
0.232;-7735.0
7A(38)
0.158;-10780.0
7A(3T)
0.194;-10202.5
7A(3Q)
0.203;-9625.0
38(8A)
0.208;-8601.2
(3J)(8A)
0.228;-7735.0
8A(38)
0.246;-8601.2
A(38J)
0.161;-9625.0
388A
0.227;-10491.2
38TA
0.176;-11803.8
38QA
0.155;-11226.2
(3T)(9A)
0.201;-7735.0
3(9KA)
0.215;-8758.7
A(39J)
0.176;-9336.2
399A
0.152;-9913.8
39JA
0.138;-11226.2
39KA
0.168;-10648.7
3Q(TA)
0.199;-8758.7
(3T)(QA)
0.261;-6868.7
TA(3J)
0.168;-9047.5
TA(3K)
0.243;-8470.0
3(JKA)
0.247;-8181.2
A(3JK)
0.216;-8181.2
JA(3K)
0.206;-8181.2
QA(3Q)
0.226;-6291.2
3QKA
0.260;-9782.5
45(4A)
0.135;-10333.7
(48)(4A)
0.226;-7577.5
4(4JA)
0.233;-8601.2
4K(4A)
0.201;-8023.8
(459A)
0.172;-10780.0
(45KA)
0.186;-9625.0
57(4A)
0.159;-11357.5
(5T)(4A)
0.180;-8601.2
5(4KA)
0.165;-9625.0
(469A)
0.236;-10491.2
(46KA)
0.169;-9336.2
68(4A)
0.176;-10780.0
(6J)(4A)
0.215;-8023.8
7(47A)
0.243;-8890.0
J(47A)
0.164;-9625.0
78(4A)
0.170;-10491.2
(7J)(4A)
0.175;-7735.0
8(48A)
0.172;-8312.5
Q(48A)
0.201;-9047.5
(8T)(4A)
0.213;-7735.0
8(4KA)
0.223;-8758.7
(49QA)
0.210;-8758.7
9(4JA)
0.233;-9047.5
9K(4A)
0.227;-8470.0
TT(4A)
0.246;-7157.5
(TK)(4A)
0.228;-6291.2
J(4QA)
0.249;-8181.2
K(4QA)
0.243;-7603.7
44(5A)
0.208;-10333.7
447A
0.165;-11646.2
4A(4T)
0.150;-8890.0
44(KA)
0.198;-8023.8
4(57A)
0.138;-11357.5
49(5A)
0.142;-10780.0
(4Q)(5A)
0.202;-8023.8
6A(45)
0.154;-11646.2
A(459)
0.197;-10780.0
(45)(QA)
0.249;-8023.8
5A(46)
0.163;-11646.2
5A(48)
0.131;-11068.8
5A(4T)
0.221;-10491.2
5A(4Q)
0.202;-9913.8
46(6A)
0.175;-9467.5
(49)(6A)
0.265;-8601.2
4(6QA)
0.206;-9625.0
A(467)
0.171;-11068.8
(46)(TA)
0.191;-8312.5
QA(46)
0.200;-9625.0
467A
0.127;-12958.8
469A
0.138;-12381.2
46JA
0.124;-11803.8
46KA
0.203;-11226.2
49(7A)
0.151;-10202.5
(4Q)(7A)
0.227;-7446.2
8A(47)
0.187;-10491.2
A(47J)
0.189;-9625.0
477A
0.197;-10780.0
479A
0.207;-12092.5
47JA
0.191;-11515.0
47KA
0.208;-10937.5
4T(8A)
0.178;-9625.0
(4K)(8A)
0.189;-6868.7
TA(48)
0.157;-9625.0
A(48K)
0.201;-8758.7
8A(4T)
0.206;-9625.0
8A(4Q)
0.218;-9047.5
49(9A)
0.210;-7735.0
(4Q)(9A)
0.274;-6868.7
TA(49)
0.233;-9336.2
A(49K)
0.238;-8470.0
9A(4J)
0.197;-9047.5
9A(4K)
0.210;-8470.0
4(TQA)
0.222;-8470.0
A(4TJ)
0.172;-8758.7
4TTA
0.171;-9047.5
4TQA
0.233;-10360.0
(4Q)(JA)
0.255;-6291.2
QA(4J)
0.207;-8181.2
4JQA
0.195;-10071.2
(4K)(QA)
0.308;-5713.8
QA(4K)
0.180;-7603.7
5(56A)
0.229;-9467.5
58(5A)
0.179;-8890.0
(5J)(5A)
0.309;-6133.7
6(56A)
0.214;-9178.7
T(56A)
0.183;-9913.8
6(57A)
0.199;-10780.0
69(5A)
0.151;-10202.5
(6Q)(5A)
0.230;-7446.2
(579A)
0.158;-9913.8
(57KA)
0.212;-8758.7
79(5A)
0.188;-9913.8
(7Q)(5A)
0.230;-7157.5
(58TA)
0.216;-9336.2
88(5A)
0.203;-8023.8
(8J)(5A)
0.243;-7157.5
9(59A)
0.234;-7446.2
K(59A)
0.210;-8181.2
9(5QA)
0.191;-8470.0
J(5TA)
0.205;-8470.0
TJ(5A)
0.188;-8470.0
(5JQA)
0.192;-7892.5
J(5KA)
0.251;-7603.7
(QK)(5A)
0.244;-5425.0
55(7A)
0.155;-9178.7
559A
0.181;-10491.2
5A(5Q)
0.240;-7735.0
(57)(6A)
0.165;-8890.0
5(6TA)
0.165;-9913.8
5Q(6A)
0.171;-9336.2
(56)(8A)
0.239;-8601.2
TA(56)
0.190;-9913.8
A(56K)
0.165;-9047.5
6A(58)
0.134;-10491.2
6A(5T)
0.206;-9913.8
6A(5Q)
0.228;-9336.2
57(7A)
0.207;-8601.2
(5T)(7A)
0.241;-7735.0
5(7KA)
0.208;-8758.7
A(579)
0.177;-9913.8
(57)(QA)
0.219;-7157.5
7A(58)
0.173;-10202.5
7A(5T)
0.182;-9625.0
7A(5Q)
0.217;-9047.5
58(8A)
0.238;-8023.8
(5J)(8A)
0.206;-7157.5
8A(58)
0.214;-8023.8
A(58J)
0.213;-9047.5
588A
0.169;-9913.8
58TA
0.139;-11226.2
58QA
0.206;-10648.7
(5T)(9A)
0.229;-7157.5
5(9KA)
0.263;-8181.2
A(59J)
0.217;-8758.7
599A
0.197;-9336.2
59JA
0.176;-10648.7
59KA
0.194;-10071.2
5Q(TA)
0.193;-8181.2
(5T)(QA)
0.220;-6291.2
TA(5J)
0.216;-8470.0
TA(5K)
0.279;-7892.5
5(JKA)
0.237;-7603.7
A(5JK)
0.204;-7603.7
JA(5K)
0.233;-7603.7
QA(5Q)
0.266;-5713.8
5QKA
0.236;-9205.0
67(6A)
0.185;-8601.2
(6T)(6A)
0.265;-5845.0
6(6KA)
0.228;-6868.7
(67TA)
0.184;-9336.2
77(6A)
0.207;-8312.5
(7T)(6A)
0.245;-7446.2
7(6KA)
0.213;-8470.0
(68JA)
0.196;-8758.7
(89)(6A)
0.234;-7446.2
8(6QA)
0.220;-8470.0
T(69A)
0.171;-8758.7
9(6TA)
0.238;-8758.7
9Q(6A)
0.223;-8181.2
Q(6TA)
0.211;-7892.5
(TQ)(6A)
0.235;-6002.5
(6JKA)
0.251;-7315.0
JK(6A)
0.187;-7315.0
K(6KA)
0.239;-4847.5
668A
0.187;-10202.5
6A(6J)
0.249;-7446.2
(67)(7A)
0.232;-6422.5
6(7TA)
0.191;-9336.2
6Q(7A)
0.216;-8758.7
(67)(9A)
0.202;-7735.0
JA(67)
0.191;-9047.5
67(8A)
0.150;-9913.8
67(TA)
0.198;-9336.2
67(QA)
0.241;-8758.7
(68)(8A)
0.185;-5845.0
6(8JA)
0.237;-8758.7
6K(8A)
0.169;-8181.2
(68)(JA)
0.249;-6868.7
KA(68)
0.165;-8181.2
6A(8T)
0.235;-9047.5
6A(8Q)
0.265;-8470.0
6(9TA)
0.252;-8758.7
6Q(9A)
0.251;-8181.2
(69)(JA)
0.223;-6580.0
KA(69)
0.253;-7892.5
6A(9J)
0.155;-8470.0
6A(9K)
0.185;-7892.5
(6Q)(TA)
0.245;-6002.5
JA(6T)
0.208;-8181.2
6T(JA)
0.187;-8181.2
6T(KA)
0.234;-7603.7
6Q(JA)
0.237;-7603.7
(6J)(KA)
0.285;-5425.0
6J(KA)
0.236;-7315.0
6K(QA)
0.258;-7026.2
6A(QK)
0.248;-7026.2
(78)(7A)
0.251;-5845.0
7(7JA)
0.206;-6868.7
7K(7A)
0.228;-6291.2
(78QA)
0.195;-8181.2
8(7TA)
0.228;-8758.7
8Q(7A)
0.275;-8181.2
J(79A)
0.178;-8181.2
9T(7A)
0.232;-8470.0
(9K)(7A)
0.230;-5713.8
K(7TA)
0.227;-7315.0
T(7KA)
0.232;-7315.0
JJ(7A)
0.280;-5713.8
(7QKA)
0.185;-6737.5
777A
0.163;-8023.8
7A(7T)
0.181;-7157.5
77(KA)
0.208;-6291.2
7(8TA)
0.209;-8758.7
7Q(8A)
0.215;-8181.2
(78)(TA)
0.241;-6868.7
QA(78)
0.197;-8181.2
789A
0.192;-10937.5
78JA
0.207;-10360.0
78KA
0.231;-9782.5
7J(9A)
0.226;-8181.2
(79)(TA)
0.235;-6580.0
QA(79)
0.265;-7892.5
79TA
0.205;-10360.0
79QA
0.168;-9782.5
(7J)(TA)
0.222;-6002.5
TA(7T)
0.205;-6291.2
A(7TK)
0.220;-7315.0
TA(7Q)
0.227;-7603.7
7J(JA)
0.236;-5713.8
(7J)(QA)
0.252;-5425.0
JA(7Q)
0.237;-7315.0
7Q(QA)
0.244;-5136.2
7QQA
0.249;-7026.2
7KKA
0.220;-6448.8
8(8JA)
0.258;-6291.2
8K(8A)
0.256;-5713.8
(89KA)
0.263;-7315.0
9J(8A)
0.215;-7892.5
(8TJA)
0.181;-7603.7
(TJ)(8A)
0.212;-5713.8
J(8JA)
0.290;-5425.0
JQ(8A)
0.218;-7026.2
Q(8KA)
0.254;-6448.8
889A
0.249;-8758.7
8A(8Q)
0.208;-6002.5
(8T)(9A)
0.229;-6291.2
8(9KA)
0.217;-7315.0
A(89J)
0.254;-7892.5
899A
0.214;-8470.0
89JA
0.191;-9782.5
89KA
0.227;-9205.0
8Q(TA)
0.213;-7315.0
(8T)(QA)
0.275;-5425.0
TA(8J)
0.226;-7603.7
TA(8K)
0.186;-7026.2
8(JKA)
0.274;-6737.5
A(8JK)
0.231;-6737.5
JA(8K)
0.286;-6737.5
QA(8Q)
0.215;-4847.5
8QKA
0.175;-8338.8
9T(9A)
0.200;-6002.5
(9K)(9A)
0.291;-3246.2
K(9TA)
0.267;-6737.5
T(9KA)
0.221;-6737.5
JJ(9A)
0.268;-5136.2
(9QKA)
0.218;-6160.0
999A
0.215;-6291.2
9A(9Q)
0.197;-5425.0
(9J)(TA)
0.253;-5425.0
TA(9T)
0.206;-5713.8
A(9TK)
0.235;-6737.5
TA(9Q)
0.191;-7026.2
9J(JA)
0.258;-5136.2
(9J)(QA)
0.307;-4847.5
JA(9Q)
0.256;-6737.5
9Q(QA)
0.259;-4558.8
9QQA
0.218;-6448.8
9KKA
0.197;-5871.2
T(TKA)
0.311;-4558.8
JJ(TA)
0.251;-4847.5
(TQKA)
0.274;-5871.2
TTTA
0.277;-5425.0
TA(TK)
0.268;-4558.8
(TK)(JA)
0.225;-4270.0
KA(TJ)
0.238;-6160.0
TA(JK)
0.244;-6160.0
(TQ)(KA)
0.264;-3981.3
(TK)(KA)
0.302;-1802.5
J(JKA)
0.276;-3981.3
(QK)(JA)
0.226;-3692.5
JJ(KA)
0.312;-3981.3
QA(JQ)
0.292;-3981.3
JQKA
0.266;-7472.5
QK(QA)
0.266;-3403.8
QK(KA)
0.252;-3115.0
22(24)
0.127;-13352.5
22(28)
0.171;-12197.5
22(2Q)
0.168;-11042.5
24(23)
0.131;-14953.8
(23)(27)
0.186;-12197.5
2(23T)
0.210;-13221.3
2Q(23)
0.186;-12643.8
23(25)
0.116;-14665.0
2237
0.136;-15977.5
22(3T)
0.174;-13221.3
23(2K)
0.132;-12355.0
2(246)
0.169;-14087.5
28(24)
0.164;-13510.0
(24)(2J)
0.188;-10753.8
2244
0.108;-14665.0
22(47)
0.127;-13798.7
24(2T)
0.143;-12932.5
224Q
0.120;-14245.0
26(25)
0.164;-13798.7
(25)(29)
0.170;-11042.5
2(25Q)
0.171;-12066.2
22(56)
0.129;-13798.7
25(29)
0.158;-12932.5
225J
0.126;-14245.0
26(26)
0.185;-11620.0
(26)(29)
0.216;-10753.8
2(26Q)
0.193;-11777.5
22(67)
0.150;-13221.3
26(2T)
0.225;-12355.0
226Q
0.130;-13667.5
28(27)
0.151;-12643.8
(27)(2J)
0.238;-9887.5
2277
0.158;-12932.5
22(7T)
0.191;-12066.2
27(2K)
0.216;-11200.0
2(28T)
0.124;-11777.5
2Q(28)
0.191;-11200.0
28(2T)
0.153;-11777.5
228Q
0.153;-13090.0
2T(29)
0.179;-11488.8
(29)(2K)
0.192;-8732.5
229J
0.139;-13090.0
2T(2T)
0.204;-9310.0
(2T)(2K)
0.186;-8443.8
22TQ
0.160;-12512.5
2Q(2J)
0.196;-10333.7
2J(2K)
0.193;-10045.0
22QQ
0.195;-10045.0
3(234)
0.176;-14665.0
36(23)
0.139;-14087.5
(23)(39)
0.196;-11331.2
3(23Q)
0.163;-12355.0
5(234)
0.140;-15977.5
9(234)
0.151;-14822.5
K(234)
0.173;-13667.5
4(237)
0.117;-15400.0
49(23)
0.153;-14822.5
(23)(4Q)
0.190;-12066.2
(2357)
0.145;-15111.2
(235J)
0.153;-13956.2
(23)(56)
0.179;-13510.0
5(239)
0.133;-14533.8
5J(23)
0.167;-13956.2
(2367)
0.178;-14822.5
(236J)
0.128;-13667.5
(23)(67)
0.162;-12932.5
6(23T)
0.150;-13956.2
6Q(23)
0.148;-13378.8
9(237)
0.175;-13956.2
K(237)
0.153;-12801.2
7(23T)
0.128;-13667.5
7Q(23)
0.164;-13090.0
T(238)
0.158;-13378.8
8(239)
0.143;-13667.5
8J(23)
0.154;-13090.0
(239T)
0.167;-13090.0
99(23)
0.136;-11488.8
(23)(9Q)
0.150;-10622.5
(23TQ)
0.171;-12223.7
T(23Q)
0.160;-12223.7
Q(23J)
0.166;-11935.0
(23)(JK)
0.249;-9756.2
QK(23)
0.177;-11357.5
23(35)
0.148;-14376.2
33(28)
0.116;-13510.0
233T
0.111;-14822.5
23(3K)
0.205;-12066.2
(24)(36)
0.151;-13798.7
3(249)
0.119;-14822.5
3J(24)
0.169;-14245.0
(34)(25)
0.173;-14087.5
27(34)
0.133;-15400.0
2(34T)
0.180;-14533.8
(34)(2K)
0.151;-11777.5
34(26)
0.173;-15688.7
34(28)
0.162;-15111.2
34(2T)
0.125;-14533.8
34(2Q)
0.164;-13956.2
(25)(35)
0.167;-11908.8
3(258)
0.116;-14822.5
3T(25)
0.169;-14245.0
(25)(3K)
0.208;-11488.8
27(35)
0.134;-15111.2
2(35T)
0.180;-14245.0
(35)(2K)
0.168;-11488.8
35(27)
0.159;-15111.2
35(29)
0.161;-14533.8
35(2J)
0.117;-13956.2
35(2K)
0.145;-13378.8
37(26)
0.163;-14822.5
(26)(3T)
0.156;-12066.2
3(26K)
0.159;-13090.0
2(368)
0.118;-14533.8
(36)(2J)
0.179;-11777.5
2K(36)
0.175;-13090.0
23(68)
0.143;-14533.8
23(6T)
0.143;-13956.2
23(6Q)
0.170;-13378.8
3(278)
0.123;-14245.0
3T(27)
0.126;-13667.5
(27)(3K)
0.202;-10911.2
29(37)
0.138;-13956.2
2(37Q)
0.167;-13090.0
23(78)
0.130;-14245.0
23(7T)
0.133;-13667.5
23(7Q)
0.139;-13090.0
3(289)
0.162;-13667.5
3J(28)
0.134;-13090.0
(38)(29)
0.184;-11777.5
2J(38)
0.131;-13090.0
38(29)
0.129;-13667.5
38(2J)
0.165;-13090.0
38(2K)
0.136;-12512.5
3T(29)
0.151;-13090.0
(29)(3K)
0.180;-10333.8
2J(39)
0.136;-12801.2
39(2T)
0.174;-13090.0
39(2Q)
0.171;-12512.5
(2T)(3T)
0.176;-9021.2
3(2TK)
0.171;-11935.0
2(3TQ)
0.149;-12223.7
23(TJ)
0.136;-12512.5
23(TK)
0.212;-11935.0
(2J)(3K)
0.164;-9756.2
2K(3J)
0.172;-11646.2
23(JK)
0.204;-11646.2
(3Q)(2K)
0.228;-9467.5
(2K)(3K)
0.212;-7288.8
4(246)
0.154;-13510.0
48(24)
0.143;-12932.5
(24)(4J)
0.181;-10176.3
5(245)
0.133;-13510.0
9(245)
0.154;-14245.0
K(245)
0.158;-13090.0
5(248)
0.188;-14533.8
5T(24)
0.145;-13956.2
(24)(5K)
0.189;-11200.0
9(246)
0.167;-13956.2
K(246)
0.190;-12801.2
6(249)
0.114;-13956.2
6J(24)
0.119;-13378.8
(2478)
0.122;-13956.2
(247Q)
0.177;-12801.2
7(249)
0.144;-13667.5
7J(24)
0.152;-13090.0
(2489)
0.182;-13378.8
(248K)
0.159;-12223.7
8T(24)
0.114;-13090.0
(24)(8K)
0.168;-10333.8
Q(249)
0.138;-12223.7
(24)(9J)
0.202;-10622.5
T(24T)
0.219;-10622.5
T(24J)
0.174;-12223.7
TK(24)
0.178;-11646.2
(24)(JQ)
0.210;-9756.2
QQ(24)
0.206;-9467.5
24(45)
0.156;-13798.7
44(28)
0.172;-12932.5
244T
0.140;-14245.0
24(4K)
0.158;-11488.8
(25)(47)
0.173;-12932.5
4(25T)
0.121;-13956.2
4Q(25)
0.129;-13378.8
(45)(27)
0.135;-12932.5
29(45)
0.130;-14245.0
2(45Q)
0.140;-13378.8
24(56)
0.115;-15111.2
24(58)
0.131;-14533.8
24(5T)
0.127;-13956.2
24(5Q)
0.165;-13378.8
4(267)
0.151;-14533.8
49(26)
0.114;-13956.2
(26)(4Q)
0.185;-11200.0
27(46)
0.156;-14533.8
2(46T)
0.184;-13667.5
(46)(2K)
0.175;-10911.2
46(28)
0.195;-14245.0
46(2T)
0.152;-13667.5
46(2Q)
0.177;-13090.0
(27)(47)
0.158;-10465.0
4(27T)
0.162;-13378.8
4Q(27)
0.125;-12801.2
(47)(29)
0.172;-11777.5
2J(47)
0.173;-13090.0
47(28)
0.146;-13956.2
47(2T)
0.124;-13378.8
47(2Q)
0.149;-12801.2
(28)(48)
0.168;-9887.5
4(28J)
0.168;-12801.2
4K(28)
0.220;-12223.7
(48)(2J)
0.205;-10911.2
2K(48)
0.208;-12223.7
24(8T)
0.123;-13090.0
24(8Q)
0.164;-12512.5
4(29T)
0.156;-12801.2
4Q(29)
0.162;-12223.7
(49)(2J)
0.164;-10622.5
2K(49)
0.143;-11935.0
24(9J)
0.211;-12512.5
24(9K)
0.204;-11935.0
(2T)(4Q)
0.200;-10045.0
2J(4T)
0.158;-12223.7
4T(2J)
0.206;-12223.7
4T(2K)
0.165;-11646.2
4Q(2J)
0.157;-11646.2
(4J)(2K)
0.193;-9467.5
4J(2K)
0.153;-11357.5
4K(2Q)
0.196;-11068.8
24(QK)
0.174;-11068.8
(25)(56)
0.135;-11042.5
5(259)
0.194;-12066.2
5J(25)
0.213;-11488.8
(2567)
0.163;-14245.0
(256J)
0.153;-13090.0
(25)(67)
0.172;-12355.0
6(25T)
0.159;-13378.8
6Q(25)
0.181;-12801.2
9(257)
0.165;-13378.8
K(257)
0.193;-12223.7
7(25T)
0.144;-13090.0
7Q(25)
0.177;-12512.5
T(258)
0.163;-12801.2
8(259)
0.160;-13090.0
8J(25)
0.141;-12512.5
(259T)
0.166;-12512.5
99(25)
0.195;-10911.2
(25)(9Q)
0.178;-10045.0
(25TQ)
0.180;-11646.2
T(25Q)
0.137;-11646.2
Q(25J)
0.127;-11357.5
(25)(JK)
0.232;-9178.7
QK(25)
0.188;-10780.0
25(57)
0.157;-12643.8
55(2T)
0.126;-11777.5
255Q
0.171;-13090.0
57(26)
0.135;-14245.0
(26)(5T)
0.146;-11488.8
5(26K)
0.191;-12512.5
2(568)
0.118;-13956.2
(56)(2J)
0.165;-11200.0
2K(56)
0.147;-12512.5
25(68)
0.186;-13956.2
25(6T)
0.137;-13378.8
25(6Q)
0.145;-12801.2
5(278)
0.147;-13667.5
5T(27)
0.170;-13090.0
(27)(5K)
0.182;-10333.8
29(57)
0.145;-13378.8
2(57Q)
0.145;-12512.5
25(78)
0.136;-13667.5
25(7T)
0.152;-13090.0
25(7Q)
0.143;-12512.5
5(289)
0.175;-13090.0
5J(28)
0.154;-12512.5
(58)(29)
0.196;-11200.0
2J(58)
0.194;-12512.5
58(29)
0.159;-13090.0
58(2J)
0.157;-12512.5
58(2K)
0.158;-11935.0
5T(29)
0.145;-12512.5
(29)(5K)
0.196;-9756.2
2J(59)
0.150;-12223.7
59(2T)
0.166;-12512.5
59(2Q)
0.191;-11935.0
(2T)(5T)
0.226;-8443.8
5(2TK)
0.163;-11357.5
2(5TQ)
0.207;-11646.2
25(TJ)
0.146;-11935.0
25(TK)
0.203;-11357.5
(2J)(5K)
0.260;-9178.7
2K(5J)
0.190;-11068.8
25(JK)
0.189;-11068.8
(5Q)(2K)
0.193;-8890.0
(2K)(5K)
0.245;-6711.2
6(268)
0.174;-11777.5
6T(26)
0.188;-11200.0
(26)(6K)
0.200;-8443.8
T(267)
0.152;-12801.2
7(268)
0.178;-13378.8
7T(26)
0.128;-12801.2
(26)(7K)
0.193;-10045.0
J(268)
0.189;-12223.7
89(26)
0.161;-12801.2
(26)(8Q)
0.225;-10045.0
(269J)
0.173;-11935.0
(26)(9T)
0.185;-10333.8
9(26K)
0.188;-11357.5
(26TK)
0.180;-11068.8
TQ(26)
0.151;-11357.5
K(26J)
0.154;-10780.0
Q(26Q)
0.252;-8890.0
KK(26)
0.233;-8312.5
66(29)
0.177;-11488.8
266J
0.123;-12801.2
67(27)
0.165;-11777.5
(27)(6T)
0.184;-10911.2
6(27K)
0.130;-11935.0
2(679)
0.164;-13090.0
(67)(2Q)
0.183;-10333.8
27(68)
0.150;-13378.8
27(6T)
0.167;-12801.2
27(6Q)
0.174;-12223.7
68(28)
0.156;-11200.0
(28)(6J)
0.220;-10333.8
28(68)
0.183;-11200.0
2(68J)
0.200;-12223.7
2688
0.135;-13090.0
268T
0.129;-14402.5
268Q
0.164;-13825.0
(29)(6T)
0.163;-10333.8
6(29K)
0.175;-11357.5
2(69J)
0.124;-11935.0
2699
0.158;-12512.5
269J
0.140;-13825.0
269K
0.127;-13247.5
6Q(2T)
0.194;-11357.5
(6T)(2Q)
0.158;-9467.5
2T(6J)
0.208;-11646.2
2T(6K)
0.174;-11068.8
6(2JK)
0.232;-10780.0
2(6JK)
0.177;-10780.0
2J(6K)
0.198;-10780.0
2Q(6Q)
0.201;-8890.0
26QK
0.148;-12381.2
78(27)
0.142;-11200.0
(27)(7J)
0.216;-8443.8
8(278)
0.160;-10911.2
Q(278)
0.174;-11646.2
(27)(8T)
0.230;-10333.8
8(27K)
0.196;-11357.5
(279Q)
0.158;-11357.5
9(27J)
0.179;-11646.2
9K(27)
0.214;-11068.8
TT(27)
0.230;-9756.2
(27)(TK)
0.245;-8890.0
J(27Q)
0.161;-10780.0
K(27Q)
0.177;-10202.5
77(28)
0.192;-11200.0
277T
0.183;-12512.5
27(7K)
0.171;-9756.2
(28)(7T)
0.176;-10333.8
7(28K)
0.190;-11357.5
2(78T)
0.209;-12223.7
(78)(2K)
0.249;-9467.5
78(2T)
0.174;-12223.7
78(2Q)
0.180;-11646.2
(29)(79)
0.253;-8443.8
7(29Q)
0.195;-11357.5
2(79T)
0.207;-11935.0
(79)(2K)
0.170;-9178.7
79(2J)
0.137;-11646.2
79(2K)
0.181;-11068.8
7J(2T)
0.170;-11357.5
(7T)(2J)
0.202;-9467.5
2K(7T)
0.210;-10780.0
27(TQ)
0.180;-11068.8
7(2JQ)
0.233;-10780.0
2(7JQ)
0.152;-10780.0
27(JQ)
0.216;-10780.0
7(2QK)
0.188;-10202.5
7Q(2K)
0.157;-10202.5
88(28)
0.266;-8732.5
(28)(8J)
0.212;-7866.2
9(289)
0.253;-10045.0
K(289)
0.164;-10780.0
9(28Q)
0.147;-11068.8
J(28T)
0.186;-11068.8
TJ(28)
0.190;-11068.8
(28JQ)
0.176;-10491.2
J(28K)
0.188;-10202.5
(28)(QK)
0.218;-8023.8
88(2T)
0.211;-10045.0
288Q
0.170;-11357.5
8T(29)
0.179;-11646.2
(29)(8K)
0.179;-8890.0
2J(89)
0.205;-11357.5
89(2T)
0.162;-11646.2
89(2Q)
0.146;-11068.8
(2T)(8T)
0.221;-7577.5
8(2TK)
0.168;-10491.2
2(8TQ)
0.224;-10780.0
28(TJ)
0.162;-11068.8
28(TK)
0.193;-10491.2
(2J)(8K)
0.188;-8312.5
2K(8J)
0.220;-10202.5
28(JK)
0.181;-10202.5
(8Q)(2K)
0.225;-8023.8
(2K)(8K)
0.303;-5845.0
9(29J)
0.218;-9178.7
9K(29)
0.229;-8601.2
TT(29)
0.244;-9178.7
(29)(TK)
0.190;-8312.5
J(29Q)
0.177;-10202.5
K(29Q)
0.159;-9625.0
99(2T)
0.204;-9467.5
299Q
0.179;-10780.0
9J(2T)
0.201;-10780.0
(9T)(2J)
0.218;-8890.0
2K(9T)
0.189;-10202.5
29(TQ)
0.201;-10491.2
9(2JQ)
0.194;-10202.5
2(9JQ)
0.183;-10202.5
29(JQ)
0.180;-10202.5
9(2QK)
0.198;-9625.0
9Q(2K)
0.180;-9625.0
TT(2T)
0.248;-7000.0
(2T)(TK)
0.249;-6133.7
J(2TQ)
0.194;-9913.8
K(2TQ)
0.176;-9336.2
TT(2J)
0.215;-8601.2
2TTK
0.197;-9913.8
TK(2J)
0.199;-9625.0
2TJJ
0.145;-10202.5
2TJK
0.177;-11515.0
2(TQK)
0.201;-9336.2
TK(2K)
0.224;-7157.5
(2J)(JK)
0.274;-5556.3
QK(2J)
0.201;-9047.5
2J(JK)
0.202;-7446.2
(JQ)(2K)
0.226;-7157.5
(2K)(JK)
0.240;-4978.7
K(2QK)
0.286;-6580.0
2K(QK)
0.198;-6580.0
3335
0.112;-14087.5
3339
0.128;-12932.5
333K
0.198;-11777.5
36(34)
0.139;-13510.0
(34)(39)
0.144;-10753.8
3(34Q)
0.155;-11777.5
33(45)
0.186;-13798.7
34(38)
0.171;-12932.5
334T
0.116;-14245.0
33(4K)
0.152;-11488.8
(35)(37)
0.191;-11042.5
3(35T)
0.161;-12066.2
3Q(35)
0.217;-11488.8
35(37)
0.146;-12932.5
3359
0.123;-14245.0
33(5Q)
0.170;-11488.8
(36)(37)
0.179;-10753.8
3(36T)
0.185;-11777.5
3Q(36)
0.154;-11200.0
36(38)
0.157;-12355.0
336T
0.153;-13667.5
33(6K)
0.157;-10911.2
(37)(39)
0.244;-9887.5
3(37Q)
0.191;-10911.2
33(78)
0.172;-12066.2
37(3J)
0.170;-11200.0
337K
0.145;-12512.5
3T(38)
0.149;-11200.0
(38)(3K)
0.165;-8443.8
338T
0.140;-13090.0
33(8K)
0.196;-10333.7
(39)(3J)
0.222;-8732.5
3399
0.175;-11200.0
33(9Q)
0.220;-10333.7
(3T)(3J)
0.156;-8443.8
33TT
0.175;-10622.5
33(TK)
0.166;-9756.2
(3J)(3K)
0.193;-7577.5
33JK
0.168;-11357.5
33(QK)
0.199;-9178.7
45(34)
0.183;-13510.0
(34)(48)
0.181;-10753.8
4(34J)
0.143;-11777.5
4K(34)
0.137;-11200.0
(3459)
0.135;-13956.2
(345K)
0.179;-12801.2
57(34)
0.139;-14533.8
(34)(5T)
0.208;-11777.5
5(34K)
0.154;-12801.2
(3469)
0.125;-13667.5
(346K)
0.181;-12512.5
68(34)
0.183;-13956.2
(34)(6J)
0.155;-11200.0
7(347)
0.133;-12066.2
J(347)
0.149;-12801.2
78(34)
0.194;-13667.5
(34)(7J)
0.178;-10911.2
8(348)
0.129;-11488.8
Q(348)
0.160;-12223.7
(34)(8T)
0.166;-10911.2
8(34K)
0.174;-11935.0
(349Q)
0.132;-11935.0
9(34J)
0.171;-12223.7
9K(34)
0.132;-11646.2
TT(34)
0.192;-10333.7
(34)(TK)
0.198;-9467.5
J(34Q)
0.196;-11357.5
K(34Q)
0.161;-10780.0
44(35)
0.155;-13510.0
3447
0.116;-14822.5
34(4T)
0.147;-12066.2
44(3K)
0.220;-11200.0
4(357)
0.127;-14533.8
49(35)
0.122;-13956.2
(35)(4Q)
0.165;-11200.0
36(45)
0.137;-14822.5
3(459)
0.144;-13956.2
(45)(3Q)
0.126;-11200.0
35(46)
0.145;-14822.5
35(48)
0.137;-14245.0
35(4T)
0.130;-13667.5
35(4Q)
0.180;-13090.0
46(36)
0.140;-12643.8
(36)(49)
0.187;-11777.5
4(36Q)
0.184;-12801.2
3(467)
0.129;-14245.0
(46)(3T)
0.158;-11488.8
3Q(46)
0.172;-12801.2
3467
0.161;-16135.0
3469
0.116;-15557.5
346J
0.177;-14980.0
346K
0.166;-14402.5
49(37)
0.132;-13378.8
(37)(4Q)
0.163;-10622.5
38(47)
0.122;-13667.5
3(47J)
0.153;-12801.2
3477
0.143;-13956.2
3479
0.130;-15268.7
347J
0.169;-14691.2
347K
0.143;-14113.8
4T(38)
0.195;-12801.2
(38)(4K)
0.190;-10045.0
3T(48)
0.158;-12801.2
3(48K)
0.157;-11935.0
38(4T)
0.194;-12801.2
38(4Q)
0.136;-12223.7
49(39)
0.164;-10911.2
(39)(4Q)
0.203;-10045.0
3T(49)
0.188;-12512.5
3(49K)
0.215;-11646.2
39(4J)
0.156;-12223.7
39(4K)
0.190;-11646.2
4(3TQ)
0.198;-11646.2
3(4TJ)
0.192;-11935.0
34TT
0.153;-12223.7
34TQ
0.123;-13536.2
(3J)(4Q)
0.190;-9467.5
3Q(4J)
0.189;-11357.5
34JQ
0.166;-13247.5
(3Q)(4K)
0.197;-8890.0
3Q(4K)
0.157;-10780.0
5(356)
0.150;-12643.8
58(35)
0.140;-12066.2
(35)(5J)
0.196;-9310.0
6(356)
0.167;-12355.0
T(356)
0.114;-13090.0
6(357)
0.118;-13956.2
69(35)
0.183;-13378.8
(35)(6Q)
0.188;-10622.5
(3579)
0.145;-13090.0
(357K)
0.174;-11935.0
79(35)
0.180;-13090.0
(35)(7Q)
0.150;-10333.8
(358T)
0.210;-12512.5
88(35)
0.156;-11200.0
(35)(8J)
0.192;-10333.8
9(359)
0.152;-10622.5
K(359)
0.205;-11357.5
9(35Q)
0.177;-11646.2
J(35T)
0.194;-11646.2
TJ(35)
0.205;-11646.2
(35JQ)
0.164;-11068.8
J(35K)
0.142;-10780.0
(35)(QK)
0.204;-8601.2
55(37)
0.155;-12355.0
3559
0.156;-13667.5
35(5Q)
0.163;-10911.2
(36)(57)
0.202;-12066.2
5(36T)
0.170;-13090.0
5Q(36)
0.144;-12512.5
(56)(38)
0.150;-11777.5
3T(56)
0.197;-13090.0
3(56K)
0.175;-12223.7
36(58)
0.188;-13667.5
36(5T)
0.160;-13090.0
36(5Q)
0.156;-12512.5
57(37)
0.123;-11777.5
(37)(5T)
0.147;-10911.2
5(37K)
0.174;-11935.0
3(579)
0.146;-13090.0
(57)(3Q)
0.183;-10333.8
37(58)
0.164;-13378.8
37(5T)
0.151;-12801.2
37(5Q)
0.146;-12223.7
58(38)
0.168;-11200.0
(38)(5J)
0.172;-10333.8
38(58)
0.136;-11200.0
3(58J)
0.190;-12223.7
3588
0.163;-13090.0
358T
0.147;-14402.5
358Q
0.143;-13825.0
(39)(5T)
0.198;-10333.8
5(39K)
0.144;-11357.5
3(59J)
0.177;-11935.0
3599
0.132;-12512.5
359J
0.147;-13825.0
359K
0.132;-13247.5
5Q(3T)
0.182;-11357.5
(5T)(3Q)
0.180;-9467.5
3T(5J)
0.151;-11646.2
3T(5K)
0.172;-11068.8
5(3JK)
0.139;-10780.0
3(5JK)
0.184;-10780.0
3J(5K)
0.200;-10780.0
3Q(5Q)
0.183;-8890.0
35QK
0.147;-12381.2
67(36)
0.182;-11777.5
(36)(6T)
0.213;-9021.2
6(36K)
0.180;-10045.0
(367T)
0.156;-12512.5
77(36)
0.134;-11488.8
(36)(7T)
0.197;-10622.5
7(36K)
0.193;-11646.2
(368J)
0.205;-11935.0
(36)(89)
0.208;-10622.5
8(36Q)
0.230;-11646.2
T(369)
0.167;-11935.0
9(36T)
0.164;-11935.0
9Q(36)
0.172;-11357.5
Q(36T)
0.164;-11068.8
(36)(TQ)
0.171;-9178.7
(36JK)
0.160;-10491.2
JK(36)
0.158;-10491.2
K(36K)
0.166;-8023.8
3668
0.137;-13378.8
36(6J)
0.179;-10622.5
(37)(67)
0.173;-9598.8
6(37T)
0.126;-12512.5
6Q(37)
0.185;-11935.0
(67)(39)
0.148;-10911.2
3J(67)
0.213;-12223.7
67(38)
0.138;-13090.0
67(3T)
0.151;-12512.5
67(3Q)
0.160;-11935.0
(38)(68)
0.202;-9021.2
6(38J)
0.185;-11935.0
6K(38)
0.196;-11357.5
(68)(3J)
0.194;-10045.0
3K(68)
0.187;-11357.5
36(8T)
0.151;-12223.7
36(8Q)
0.148;-11646.2
6(39T)
0.165;-11935.0
6Q(39)
0.152;-11357.5
(69)(3J)
0.192;-9756.2
3K(69)
0.170;-11068.8
36(9J)
0.147;-11646.2
36(9K)
0.236;-11068.8
(3T)(6Q)
0.245;-9178.7
3J(6T)
0.187;-11357.5
6T(3J)
0.222;-11357.5
6T(3K)
0.167;-10780.0
6Q(3J)
0.207;-10780.0
(6J)(3K)
0.171;-8601.2
6J(3K)
0.184;-10491.2
6K(3Q)
0.153;-10202.5
36(QK)
0.179;-10202.5
(37)(78)
0.183;-9021.2
7(37J)
0.187;-10045.0
7K(37)
0.222;-9467.5
(378Q)
0.226;-11357.5
8(37T)
0.146;-11935.0
8Q(37)
0.211;-11357.5
J(379)
0.164;-11357.5
9T(37)
0.143;-11646.2
(37)(9K)
0.164;-8890.0
K(37T)
0.196;-10491.2
T(37K)
0.202;-10491.2
JJ(37)
0.199;-8890.0
(37QK)
0.217;-9913.8
3777
0.175;-11200.0
37(7T)
0.223;-10333.7
77(3K)
0.198;-9467.5
7(38T)
0.176;-11935.0
7Q(38)
0.173;-11357.5
(78)(3T)
0.192;-10045.0
3Q(78)
0.137;-11357.5
3789
0.130;-14113.8
378J
0.168;-13536.2
378K
0.124;-12958.8
7J(39)
0.139;-11357.5
(79)(3T)
0.205;-9756.2
3Q(79)
0.206;-11068.8
379T
0.168;-13536.2
379Q
0.168;-12958.8
(3T)(7J)
0.180;-9178.7
3T(7T)
0.199;-9467.5
3(7TK)
0.146;-10491.2
3T(7Q)
0.199;-10780.0
7J(3J)
0.168;-8890.0
(7J)(3Q)
0.194;-8601.2
3J(7Q)
0.150;-10491.2
7Q(3Q)
0.247;-8312.5
37QQ
0.228;-10202.5
37KK
0.205;-9625.0
8(38J)
0.259;-9467.5
8K(38)
0.164;-8890.0
(389K)
0.154;-10491.2
9J(38)
0.183;-11068.8
(38TJ)
0.181;-10780.0
(38)(TJ)
0.218;-8890.0
J(38J)
0.211;-8601.2
JQ(38)
0.220;-10202.5
Q(38K)
0.205;-9625.0
3889
0.140;-11935.0
38(8Q)
0.195;-9178.7
(39)(8T)
0.202;-9467.5
8(39K)
0.172;-10491.2
3(89J)
0.168;-11068.8
3899
0.207;-11646.2
389J
0.159;-12958.8
389K
0.156;-12381.2
8Q(3T)
0.219;-10491.2
(8T)(3Q)
0.177;-8601.2
3T(8J)
0.170;-10780.0
3T(8K)
0.230;-10202.5
8(3JK)
0.190;-9913.8
3(8JK)
0.212;-9913.8
3J(8K)
0.150;-9913.8
3Q(8Q)
0.220;-8023.8
38QK
0.192;-11515.0
9T(39)
0.172;-9178.7
(39)(9K)
0.212;-6422.5
K(39T)
0.173;-9913.8
T(39K)
0.209;-9913.8
JJ(39)
0.233;-8312.5
(39QK)
0.158;-9336.2
3999
0.202;-9467.5
39(9Q)
0.225;-8601.2
(3T)(9J)
0.168;-8601.2
3T(9T)
0.202;-8890.0
3(9TK)
0.168;-9913.8
3T(9Q)
0.198;-10202.5
9J(3J)
0.182;-8312.5
(9J)(3Q)
0.213;-8023.8
3J(9Q)
0.192;-9913.8
9Q(3Q)
0.211;-7735.0
39QQ
0.224;-9625.0
39KK
0.163;-9047.5
T(3TK)
0.221;-7735.0
JJ(3T)
0.198;-8023.8
(3TQK)
0.176;-9047.5
3TTT
0.177;-8601.2
3T(TK)
0.213;-7735.0
(3J)(TK)
0.185;-7446.2
3K(TJ)
0.228;-9336.2
3T(JK)
0.178;-9336.2
(TQ)(3K)
0.222;-7157.5
(3K)(TK)
0.238;-4978.7
J(3JK)
0.244;-7157.5
(3J)(QK)
0.207;-6868.7
JJ(3K)
0.221;-7157.5
3Q(JQ)
0.206;-7157.5
3JQK
0.162;-10648.7
QK(3Q)
0.274;-6580.0
QK(3K)
0.276;-6291.2
44(46)
0.197;-11042.5
44(4T)
0.186;-9887.5
(45)(45)
0.176;-9152.5
4(458)
0.192;-12066.2
4T(45)
0.206;-11488.8
(45)(4K)
0.223;-8732.5
4457
0.126;-14245.0
44(5T)
0.136;-11488.8
45(4K)
0.169;-10622.5
4(468)
0.173;-11777.5
4T(46)
0.169;-11200.0
(46)(4K)
0.205;-8443.8
4468
0.133;-13667.5
44(6J)
0.192;-10911.2
(47)(47)
0.203;-7997.5
4(47T)
0.154;-10911.2
4Q(47)
0.169;-10333.7
47(49)
0.160;-11200.0
447J
0.170;-12512.5
48(48)
0.217;-9310.0
(48)(4J)
0.208;-8443.8
4488
0.189;-11200.0
44(8J)
0.183;-10333.7
(49)(49)
0.288;-6842.5
4(49Q)
0.174;-9756.2
44(9T)
0.228;-10333.7
49(4K)
0.207;-9467.5
4(4TQ)
0.213;-9467.5
44(TJ)
0.192;-9756.2
(4J)(4J)
0.272;-5687.5
44JJ
0.180;-9467.5
4Q(4Q)
0.215;-7000.0
(4K)(4K)
0.294;-4532.5
(45)(57)
0.151;-10176.3
5(45T)
0.168;-11200.0
5Q(45)
0.223;-10622.5
8(456)
0.127;-13378.8
Q(456)
0.138;-12223.7
(45)(68)
0.197;-11488.8
6(45J)
0.158;-12512.5
6K(45)
0.142;-11935.0
(457J)
0.126;-12223.7
(45)(78)
0.167;-11200.0
7(45J)
0.166;-12223.7
7K(45)
0.179;-11646.2
(458Q)
0.213;-11646.2
8(45T)
0.163;-12223.7
8Q(45)
0.182;-11646.2
J(459)
0.192;-11646.2
9T(45)
0.151;-11935.0
(45)(9K)
0.205;-9178.7
K(45T)
0.206;-10780.0
T(45K)
0.173;-10780.0
JJ(45)
0.166;-9178.7
(45QK)
0.203;-10202.5
4555
0.138;-12643.8
45(58)
0.161;-11777.5
55(4J)
0.201;-10911.2
455K
0.214;-12223.7
58(46)
0.164;-13378.8
(46)(5J)
0.173;-10622.5
46(56)
0.156;-12066.2
4(569)
0.166;-13090.0
(56)(4Q)
0.207;-10333.8
46(57)
0.149;-13667.5
46(59)
0.153;-13090.0
46(5J)
0.146;-12512.5
46(5K)
0.176;-11935.0
5(479)
0.166;-12801.2
5J(47)
0.141;-12223.7
(57)(48)
0.200;-11200.0
4T(57)
0.123;-12512.5
4(57K)
0.209;-11646.2
47(59)
0.157;-12801.2
47(5J)
0.144;-12223.7
47(5K)
0.216;-11646.2
5(48T)
0.145;-12223.7
5Q(48)
0.218;-11646.2
(58)(4T)
0.171;-10333.8
4Q(58)
0.193;-11646.2
4589
0.178;-14402.5
458J
0.157;-13825.0
458K
0.126;-13247.5
5J(49)
0.169;-11646.2
(59)(4T)
0.155;-10045.0
4Q(59)
0.214;-11357.5
459T
0.135;-13825.0
459Q
0.170;-13247.5
(4T)(5J)
0.218;-9467.5
4T(5T)
0.213;-9756.2
4(5TK)
0.185;-10780.0
4T(5Q)
0.173;-11068.8
5J(4J)
0.225;-9178.7
(5J)(4Q)
0.189;-8890.0
4J(5Q)
0.236;-10780.0
5Q(4Q)
0.206;-8601.2
45QQ
0.213;-10491.2
45KK
0.206;-9913.8
6(469)
0.196;-10911.2
6J(46)
0.183;-10333.7
(4678)
0.166;-12801.2
(467Q)
0.179;-11646.2
7(469)
0.194;-12512.5
7J(46)
0.134;-11935.0
(4689)
0.176;-12223.7
(468K)
0.167;-11068.8
8T(46)
0.154;-11935.0
(46)(8K)
0.231;-9178.7
Q(469)
0.148;-11068.8
(46)(9J)
0.191;-9467.5
T(46T)
0.200;-9467.5
T(46J)
0.176;-11068.8
TK(46)
0.225;-10491.2
(46)(JQ)
0.236;-8601.2
QQ(46)
0.210;-8312.5
46(67)
0.172;-11488.8
66(4T)
0.198;-10622.5
466Q
0.150;-11935.0
68(47)
0.161;-12801.2
(47)(6J)
0.185;-10045.0
47(67)
0.176;-11200.0
4(67T)
0.184;-12223.7
(67)(4K)
0.204;-9467.5
67(49)
0.179;-12512.5
67(4J)
0.190;-11935.0
67(4K)
0.197;-11357.5
69(48)
0.139;-12223.7
(48)(6Q)
0.210;-9467.5
49(68)
0.168;-12223.7
4(68Q)
0.210;-11357.5
46(89)
0.185;-12223.7
46(8J)
0.168;-11646.2
46(8K)
0.174;-11068.8
(49)(6J)
0.213;-9467.5
49(69)
0.230;-10045.0
4(69Q)
0.168;-11068.8
46(9T)
0.188;-11646.2
46(9Q)
0.171;-11068.8
6(4TJ)
0.153;-11068.8
6K(4T)
0.166;-10491.2
(6T)(4K)
0.270;-8601.2
6T(4Q)
0.180;-10780.0
(4J)(6J)
0.225;-7000.0
4J(6J)
0.197;-8890.0
6J(4Q)
0.161;-10491.2
(4Q)(6Q)
0.196;-6422.5
4K(6Q)
0.251;-9913.8
4K(6K)
0.248;-7735.0
79(47)
0.228;-10333.7
(47)(7Q)
0.195;-7577.5
(478T)
0.185;-11646.2
88(47)
0.165;-10333.7
(47)(8J)
0.195;-9467.5
9(479)
0.250;-9756.2
K(479)
0.197;-10491.2
9(47Q)
0.160;-10780.0
J(47T)
0.201;-10780.0
TJ(47)
0.148;-10780.0
(47JQ)
0.164;-10202.5
J(47K)
0.164;-9913.8
(47)(QK)
0.259;-7735.0
77(49)
0.188;-10333.7
477J
0.166;-11646.2
78(48)
0.211;-10333.7
(48)(7J)
0.173;-9467.5
48(78)
0.249;-10333.7
4(78J)
0.204;-11357.5
4788
0.186;-12223.7
478T
0.167;-13536.2
478Q
0.126;-12958.8
(49)(7T)
0.161;-9467.5
7(49K)
0.166;-10491.2
4(79J)
0.173;-11068.8
4799
0.169;-11646.2
479J
0.201;-12958.8
479K
0.178;-12381.2
7Q(4T)
0.202;-10491.2
(7T)(4Q)
0.209;-8601.2
4T(7J)
0.139;-10780.0
4T(7K)
0.191;-10202.5
7(4JK)
0.196;-9913.8
4(7JK)
0.171;-9913.8
4J(7K)
0.200;-9913.8
4Q(7Q)
0.260;-8023.8
47QK
0.188;-11515.0
89(48)
0.166;-9756.2
(48)(8Q)
0.202;-7000.0
(489J)
0.167;-10780.0
(48)(9T)
0.189;-9178.7
9(48K)
0.200;-10202.5
(48TK)
0.188;-9913.8
TQ(48)
0.204;-10202.5
K(48J)
0.200;-9625.0
Q(48Q)
0.188;-7735.0
KK(48)
0.222;-7157.5
88(4J)
0.206;-9178.7
488K
0.197;-10491.2
8J(49)
0.160;-10780.0
(89)(4T)
0.173;-9178.7
4Q(89)
0.156;-10491.2
489T
0.125;-12958.8
489Q
0.177;-12381.2
(4T)(8J)
0.239;-8601.2
4T(8T)
0.197;-8890.0
4(8TK)
0.173;-9913.8
4T(8Q)
0.230;-10202.5
8J(4J)
0.207;-8312.5
(8J)(4Q)
0.226;-8023.8
4J(8Q)
0.212;-9913.8
8Q(4Q)
0.193;-7735.0
48QQ
0.160;-9625.0
48KK
0.189;-9047.5
9(49Q)
0.259;-8312.5
J(49T)
0.230;-10202.5
TJ(49)
0.197;-10202.5
(49JQ)
0.239;-9625.0
J(49K)
0.160;-9336.2
(49)(QK)
0.233;-7157.5
99(4J)
0.211;-8601.2
499K
0.147;-9913.8
9Q(4T)
0.168;-9913.8
(9T)(4Q)
0.195;-8023.8
4T(9J)
0.197;-10202.5
4T(9K)
0.150;-9625.0
9(4JK)
0.238;-9336.2
4(9JK)
0.209;-9336.2
4J(9K)
0.189;-9336.2
4Q(9Q)
0.268;-7446.2
49QK
0.199;-10937.5
TJ(4T)
0.185;-8023.8
(4TJQ)
0.235;-9336.2
J(4TK)
0.211;-9047.5
(4T)(QK)
0.299;-6868.7
TT(4Q)
0.231;-7735.0
T(4JQ)
0.224;-9336.2
4(TJQ)
0.193;-9336.2
4T(JQ)
0.178;-9336.2
T(4QK)
0.172;-8758.7
TQ(4K)
0.201;-8758.7
JJ(4J)
0.250;-5556.3
(4JQK)
0.211;-8470.0
4JJJ
0.231;-7446.2
JQ(4Q)
0.301;-6868.7
4JQQ
0.197;-8758.7
4JKK
0.249;-8181.2
QQ(4K)
0.210;-6291.2
4KKK
0.308;-5713.8
55(59)
0.198;-9310.0
55(5K)
0.217;-8155.0
(56)(58)
0.202;-9310.0
5(56J)
0.190;-10333.7
5K(56)
0.215;-9756.2
56(59)
0.190;-10911.2
556J
0.163;-12223.7
57(57)
0.196;-9310.0
(57)(5T)
0.212;-8443.8
5(57K)
0.207;-9467.5
55(79)
0.182;-10622.5
57(5Q)
0.184;-9756.2
5(589)
0.206;-10333.7
5J(58)
0.167;-9756.2
58(59)
0.164;-10333.7
558J
0.165;-11646.2
59(59)
0.256;-8155.0
(59)(5Q)
0.220;-7288.8
559T
0.149;-11646.2
55(9K)
0.155;-8890.0
(5T)(5Q)
0.289;-7000.0
55TJ
0.151;-11068.8
5J(5J)
0.218;-7000.0
5J(5Q)
0.233;-8601.2
5(5QK)
0.210;-8023.8
5K(5K)
0.265;-5845.0
68(56)
0.169;-10911.2
(56)(6J)
0.227;-8155.0
7(567)
0.187;-10911.2
J(567)
0.148;-11646.2
78(56)
0.165;-12512.5
(56)(7J)
0.223;-9756.2
8(568)
0.164;-10333.7
Q(568)
0.182;-11068.8
(56)(8T)
0.207;-9756.2
8(56K)
0.150;-10780.0
(569Q)
0.216;-10780.0
9(56J)
0.173;-11068.8
9K(56)
0.161;-10491.2
TT(56)
0.196;-9178.7
(56)(TK)
0.205;-8312.5
J(56Q)
0.184;-10202.5
K(56Q)
0.209;-9625.0
66(57)
0.180;-11200.0
5669
0.129;-12512.5
56(6Q)
0.164;-9756.2
(57)(68)
0.191;-10622.5
6(57J)
0.173;-11646.2
6K(57)
0.185;-11068.8
(67)(5T)
0.206;-10045.0
5Q(67)
0.164;-11357.5
5678
0.171;-14402.5
567T
0.122;-13825.0
567Q
0.151;-13247.5
(58)(69)
0.202;-10045.0
6(58Q)
0.162;-11068.8
5(689)
0.156;-11935.0
(68)(5Q)
0.222;-9178.7
58(69)
0.201;-11935.0
58(6J)
0.226;-11357.5
58(6K)
0.175;-10780.0
6(59J)
0.206;-11068.8
6K(59)
0.148;-10491.2
(69)(5Q)
0.210;-8890.0
59(6T)
0.189;-11357.5
59(6Q)
0.233;-10780.0
6T(5T)
0.254;-9178.7
(5T)(6K)
0.180;-8312.5
5Q(6T)
0.170;-10491.2
56TJ
0.118;-12670.0
56TK
0.130;-12092.5
6K(5J)
0.189;-9913.8
56JJ
0.157;-10491.2
56JK
0.165;-11803.8
5(6QK)
0.206;-9625.0
6K(5K)
0.254;-7446.2
(57)(79)
0.253;-8155.0
7(57Q)
0.208;-9178.7
9(578)
0.157;-11646.2
K(578)
0.218;-10491.2
8(57J)
0.172;-11068.8
8K(57)
0.178;-10491.2
(579K)
0.167;-10202.5
9J(57)
0.159;-10780.0
(57TJ)
0.188;-10491.2
(57)(TJ)
0.217;-8601.2
J(57J)
0.227;-8312.5
JQ(57)
0.163;-9913.8
Q(57K)
0.209;-9336.2
5778
0.182;-12223.7
57(7J)
0.209;-9467.5
(58)(78)
0.238;-8155.0
7(58J)
0.170;-11068.8
7K(58)
0.220;-10491.2
(78)(5J)
0.217;-9178.7
5K(78)
0.139;-10491.2
57(8T)
0.160;-11357.5
57(8Q)
0.204;-10780.0
7(59T)
0.168;-11068.8
7Q(59)
0.175;-10491.2
(79)(5J)
0.206;-8890.0
5K(79)
0.149;-10202.5
57(9J)
0.203;-10780.0
57(9K)
0.185;-10202.5
(5T)(7Q)
0.185;-8312.5
5J(7T)
0.215;-10491.2
7T(5J)
0.159;-10491.2
7T(5K)
0.148;-9913.8
7Q(5J)
0.249;-9913.8
(7J)(5K)
0.250;-7735.0
7J(5K)
0.188;-9625.0
7K(5Q)
0.241;-9336.2
57(QK)
0.248;-9336.2
(58)(89)
0.233;-7577.5
8(58Q)
0.194;-8601.2
T(589)
0.218;-10780.0
9(58T)
0.146;-10780.0
9Q(58)
0.152;-10202.5
Q(58T)
0.202;-9913.8
(58)(TQ)
0.270;-8023.8
(58JK)
0.234;-9336.2
JK(58)
0.229;-9336.2
K(58K)
0.288;-6868.7
588T
0.164;-11068.8
58(8K)
0.209;-8312.5
(59)(8J)
0.203;-8601.2
59(89)
0.227;-9178.7
5(89Q)
0.205;-10202.5
58(9T)
0.174;-10780.0
58(9Q)
0.229;-10202.5
8(5TJ)
0.208;-10202.5
8K(5T)
0.178;-9625.0
(8T)(5K)
0.248;-7735.0
8T(5Q)
0.175;-9913.8
(5J)(8J)
0.300;-6133.7
5J(8J)
0.191;-8023.8
8J(5Q)
0.178;-9625.0
(5Q)(8Q)
0.274;-5556.3
5K(8Q)
0.195;-9047.5
5K(8K)
0.247;-6868.7
9J(59)
0.175;-8312.5
(59TJ)
0.184;-9913.8
(59)(TJ)
0.210;-8023.8
J(59J)
0.237;-7735.0
JQ(59)
0.255;-9336.2
Q(59K)
0.224;-8758.7
599T
0.168;-10491.2
59(9K)
0.191;-7735.0
(5T)(9Q)
0.212;-7735.0
5J(9T)
0.218;-9913.8
9T(5J)
0.181;-9913.8
9T(5K)
0.187;-9336.2
9Q(5J)
0.210;-9336.2
(9J)(5K)
0.291;-7157.5
9J(5K)
0.256;-9047.5
9K(5Q)
0.210;-8758.7
59(QK)
0.248;-8758.7
(5T)(TJ)
0.239;-5845.0
J(5TJ)
0.228;-7446.2
JQ(5T)
0.206;-9047.5
Q(5TK)
0.196;-8470.0
5TTJ
0.172;-9625.0
TJ(5J)
0.222;-7446.2
(TJ)(5Q)
0.226;-7157.5
5J(TQ)
0.154;-9047.5
TQ(5Q)
0.250;-6868.7
5TQQ
0.193;-8758.7
5TKK
0.227;-8181.2
Q(5JQ)
0.232;-6580.0
KK(5J)
0.224;-6002.5
(5Q)(JQ)
0.217;-4690.0
5K(JQ)
0.161;-8181.2
5K(JK)
0.290;-6002.5
5QQQ
0.223;-6291.2
KK(5K)
0.252;-3535.0
6669
0.182;-10333.8
666K
0.222;-9178.7
69(67)
0.186;-10045.0
(67)(6Q)
0.217;-7288.8
6678
0.198;-12223.7
66(7J)
0.216;-9467.5
(68)(68)
0.270;-6265.0
6(68J)
0.166;-9178.7
6K(68)
0.187;-8601.2
68(6J)
0.192;-9178.7
668K
0.163;-10491.2
6J(69)
0.155;-8890.0
69(6T)
0.170;-9178.7
669Q
0.214;-10491.2
6J(6T)
0.163;-8601.2
6T(6J)
0.235;-8601.2
66TK
0.244;-9913.8
6K(6J)
0.261;-7735.0
(6Q)(6Q)
0.249;-3955.0
66QK
0.153;-9336.2
7(679)
0.170;-9756.2
7J(67)
0.150;-9178.7
(6789)
0.149;-11357.5
(678K)
0.158;-10202.5
8T(67)
0.187;-11068.8
(67)(8K)
0.196;-8312.5
Q(679)
0.189;-10202.5
(67)(9J)
0.196;-8601.2
T(67T)
0.208;-8601.2
T(67J)
0.179;-10202.5
TK(67)
0.163;-9625.0
(67)(JQ)
0.235;-7735.0
QQ(67)
0.263;-7446.2
67(78)
0.141;-10045.0
77(6J)
0.214;-9178.7
677K
0.223;-10491.2
7T(68)
0.150;-11068.8
(68)(7K)
0.253;-8312.5
6T(78)
0.172;-11068.8
6(78K)
0.174;-10202.5
68(7T)
0.172;-11068.8
68(7Q)
0.179;-10491.2
79(69)
0.193;-9178.7
(69)(7Q)
0.257;-8312.5
6T(79)
0.177;-10780.0
6(79K)
0.173;-9913.8
69(7J)
0.209;-10491.2
69(7K)
0.194;-9913.8
7(6TQ)
0.201;-9913.8
6(7TJ)
0.155;-10202.5
67TT
0.164;-10491.2
67TQ
0.150;-11803.8
(6J)(7Q)
0.204;-7735.0
6Q(7J)
0.240;-9625.0
67JQ
0.159;-11515.0
(6Q)(7K)
0.218;-7157.5
6Q(7K)
0.206;-9047.5
8(689)
0.267;-9178.7
8J(68)
0.219;-8601.2
(689T)
0.167;-10491.2
99(68)
0.203;-8890.0
(68)(9Q)
0.219;-8023.8
(68TQ)
0.230;-9625.0
T(68Q)
0.170;-9625.0
Q(68J)
0.158;-9336.2
(68)(JK)
0.227;-7157.5
QK(68)
0.241;-8758.7
68(8T)
0.199;-8890.0
88(6K)
0.231;-8023.8
8(69J)
0.180;-10202.5
8K(69)
0.198;-9625.0
(89)(6Q)
0.240;-8023.8
69(8T)
0.204;-10491.2
69(8Q)
0.164;-9913.8
8T(6T)
0.220;-8312.5
(6T)(8K)
0.185;-7446.2
6Q(8T)
0.194;-9625.0
68TJ
0.206;-11803.8
68TK
0.171;-11226.2
8K(6J)
0.219;-9047.5
68JJ
0.150;-9625.0
68JK
0.219;-10937.5
6(8QK)
0.198;-8758.7
8K(6K)
0.185;-6580.0
(69)(9J)
0.242;-6133.7
T(69T)
0.191;-8023.8
T(69J)
0.191;-9625.0
TK(69)
0.203;-9047.5
(69)(JQ)
0.254;-7157.5
QQ(69)
0.202;-6868.7
69(9T)
0.172;-8312.5
99(6K)
0.197;-7446.2
9(6TQ)
0.183;-9336.2
6(9TJ)
0.246;-9625.0
69TT
0.160;-9913.8
69TQ
0.186;-11226.2
(6J)(9Q)
0.217;-7157.5
6Q(9J)
0.199;-9047.5
69JQ
0.155;-10937.5
(6Q)(9K)
0.211;-6580.0
6Q(9K)
0.189;-8470.0
T(6TJ)
0.207;-7446.2
TK(6T)
0.281;-6868.7
(6T)(JQ)
0.199;-6868.7
QQ(6T)
0.237;-6580.0
6T(TJ)
0.195;-7446.2
(6J)(TJ)
0.219;-5267.5
6J(TJ)
0.215;-7157.5
TJ(6Q)
0.261;-8758.7
(6Q)(TQ)
0.267;-4690.0
6K(TQ)
0.204;-8181.2
6K(TK)
0.242;-6002.5
JK(6J)
0.217;-6291.2
K(6JK)
0.228;-5713.8
6JJK
0.219;-8181.2
6(JQK)
0.205;-7892.5
JK(6K)
0.261;-5713.8
KK(6Q)
0.256;-5425.0
6QKK
0.230;-7315.0
77(7T)
0.246;-7288.7
(78)(78)
0.248;-5687.5
7(78J)
0.232;-8601.2
7K(78)
0.218;-8023.8
78(7J)
0.215;-8601.2
778K
0.176;-9913.8
7J(79)
0.197;-8312.5
79(7T)
0.230;-8601.2
779Q
0.171;-9913.8
7J(7T)
0.197;-8023.8
7T(7J)
0.222;-8023.8
77TK
0.223;-9336.2
7K(7J)
0.220;-7157.5
(7Q)(7Q)
0.259;-3377.5
77QK
0.234;-8758.7
8(78T)
0.167;-8601.2
8Q(78)
0.211;-8023.8
J(789)
0.178;-9913.8
9T(78)
0.201;-10202.5
(78)(9K)
0.236;-7446.2
K(78T)
0.208;-9047.5
T(78K)
0.205;-9047.5
JJ(78)
0.198;-7446.2
(78QK)
0.210;-8470.0
7888
0.246;-9178.7
78(8J)
0.236;-8312.5
(79)(89)
0.238;-6711.2
8(79Q)
0.201;-9625.0
7(89T)
0.153;-10202.5
(89)(7K)
0.261;-7446.2
89(7J)
0.196;-9913.8
89(7K)
0.251;-9336.2
8J(7T)
0.211;-9625.0
(8T)(7J)
0.190;-7735.0
7K(8T)
0.256;-9047.5
78(TQ)
0.164;-9336.2
8(7JQ)
0.182;-9047.5
7(8JQ)
0.191;-9047.5
78(JQ)
0.223;-9047.5
8(7QK)
0.194;-8470.0
8Q(7K)
0.180;-8470.0
99(79)
0.256;-6422.5
(79)(9Q)
0.252;-5556.3
(79TQ)
0.152;-9047.5
T(79Q)
0.197;-9047.5
Q(79J)
0.165;-8758.7
(79)(JK)
0.220;-6580.0
QK(79)
0.192;-8181.2
79(9J)
0.229;-7735.0
(7T)(9T)
0.248;-5845.0
9(7TK)
0.186;-8758.7
7(9TQ)
0.162;-9047.5
79(TJ)
0.199;-9336.2
79(TK)
0.255;-8758.7
(7J)(9K)
0.186;-6580.0
7K(9J)
0.198;-8470.0
79(JK)
0.210;-8470.0
(9Q)(7K)
0.209;-6291.2
(7K)(9K)
0.234;-4112.5
T(7TQ)
0.263;-6868.7
Q(7TJ)
0.261;-8470.0
(7T)(JK)
0.287;-6291.2
QK(7T)
0.237;-7892.5
7T(TQ)
0.185;-6868.7
(7J)(TQ)
0.216;-6580.0
7Q(TJ)
0.187;-8470.0
7TJQ
0.157;-10360.0
(7Q)(TK)
0.187;-6002.5
7Q(TK)
0.246;-7892.5
J(7JQ)
0.295;-6291.2
K(7JQ)
0.234;-7603.7
JJ(7Q)
0.280;-6291.2
J(7QK)
0.206;-7603.7
JQ(7K)
0.233;-7603.7
QQ(7Q)
0.241;-3823.8
7Q(QK)
0.215;-5425.0
8888
0.252;-7000.0
888Q
0.254;-7735.0
8(89J)
0.188;-7735.0
8K(89)
0.215;-7157.5
89(8Q)
0.263;-7446.2
8(8TJ)
0.201;-7446.2
8K(8T)
0.188;-6868.7
8T(8K)
0.282;-6868.7
8(8JK)
0.250;-6580.0
88(JK)
0.199;-6580.0
8Q(8K)
0.229;-6291.2
(89)(9T)
0.237;-5845.0
9(89K)
0.223;-6868.7
(89TK)
0.176;-8470.0
TQ(89)
0.250;-8758.7
K(89J)
0.236;-8181.2
Q(89Q)
0.266;-6291.2
KK(89)
0.242;-5713.8
99(8Q)
0.201;-7157.5
9(8TJ)
0.250;-9047.5
9K(8T)
0.221;-8470.0
(9T)(8K)
0.260;-6580.0
9T(8Q)
0.196;-8758.7
(8J)(9J)
0.253;-4978.7
8J(9J)
0.209;-6868.7
9J(8Q)
0.246;-8470.0
(8Q)(9Q)
0.279;-4401.2
8K(9Q)
0.237;-7892.5
8K(9K)
0.210;-5713.8
TQ(8T)
0.242;-6580.0
K(8TJ)
0.212;-7892.5
Q(8TQ)
0.225;-6002.5
KK(8T)
0.246;-5425.0
