AAAA
0.335;-1390.0
5AAA
0.231;-5023.8
9AAA
0.300;-4088.7
KAAA
0.268;-3153.7
4A(2A)
0.203;-8062.5
(2A)(7A)
0.257;-5831.3
A(2TA)
0.214;-6660.0
QA(2A)
0.203;-6192.5
2A(4A)
0.218;-8062.5
26AA
0.171;-9125.0
AA(29)
0.301;-6893.7
2A(QA)
0.256;-6192.5
A(34A)
0.256;-7828.7
6A(3A)
0.254;-7361.2
(3A)(9A)
0.233;-5130.0
A(3QA)
0.254;-5958.8
AA(34)
0.206;-7828.7
3A(7A)
0.263;-7127.5
39AA
0.192;-8190.0
AA(3Q)
0.292;-5958.8
(4A)(5A)
0.229;-5831.3
A(48A)
0.222;-6660.0
TA(4A)
0.213;-6192.5
(4A)(KA)
0.290;-3961.2
46AA
0.203;-8657.5
AA(49)
0.264;-6426.2
4A(QA)
0.249;-5725.0
A(56A)
0.238;-6893.7
8A(5A)
0.259;-6426.2
(5A)(JA)
0.265;-4195.0
55AA
0.202;-7127.5
AA(58)
0.209;-6426.2
5A(JA)
0.237;-5725.0
5KAA
0.252;-6787.5
8A(6A)
0.227;-6192.5
(6A)(JA)
0.329;-3961.2
66AA
0.198;-6660.0
AA(69)
0.227;-5958.8
6A(QA)
0.259;-5257.5
A(78A)
0.238;-5958.8
TA(7A)
0.227;-5491.2
(7A)(KA)
0.290;-3260.0
79AA
0.229;-7255.0
AA(7Q)
0.263;-5023.8
(8A)(9A)
0.296;-3961.2
A(8QA)
0.227;-4790.0
AA(89)
0.242;-5491.2
8A(QA)
0.231;-4790.0
A(9TA)
0.298;-5023.8
QA(9A)
0.288;-4556.2
9A(JA)
0.245;-4790.0
9KAA
0.238;-5852.5
QA(TA)
0.252;-4322.5
TA(QA)
0.261;-4322.5
A(JQA)
0.323;-4088.8
AA(JQ)
0.263;-4088.8
(QA)(KA)
0.313;-2091.3
KKAA
0.304;-3387.5
2(25A)
0.183;-10633.8
27(2A)
0.153;-10166.2
(2T)(2A)
0.252;-7935.0
2(2KA)
0.215;-8763.8
(236A)
0.139;-11696.2
(23TA)
0.167;-10761.2
33(2A)
0.178;-10867.5
(36)(2A)
0.198;-10166.2
3(29A)
0.173;-10995.0
3J(2A)
0.206;-10527.5
(245A)
0.205;-11696.2
(249A)
0.175;-10761.2
(24KA)
0.200;-9826.2
46(2A)
0.135;-11462.5
(49)(2A)
0.214;-9231.2
4(2QA)
0.138;-10060.0
6(25A)
0.156;-11228.7
T(25A)
0.144;-10293.8
5(26A)
0.174;-11228.7
58(2A)
0.170;-10761.2
(5J)(2A)
0.159;-8530.0
6(26A)
0.199;-9465.0
T(26A)
0.218;-10060.0
6(27A)
0.181;-10761.2
69(2A)
0.220;-10293.8
(6Q)(2A)
0.219;-8062.5
(279A)
0.211;-10060.0
(27KA)
0.234;-9125.0
79(2A)
0.156;-10060.0
(7Q)(2A)
0.217;-7828.8
(28TA)
0.227;-9592.5
88(2A)
0.177;-8530.0
(8J)(2A)
0.278;-7828.8
9(29A)
0.187;-8062.5
K(29A)
0.225;-8657.5
9(2QA)
0.237;-8891.2
J(2TA)
0.256;-8891.2
TJ(2A)
0.185;-8891.2
(2JQA)
0.191;-8423.7
J(2KA)
0.251;-8190.0
(QK)(2A)
0.253;-6426.2
22(4A)
0.153;-10867.5
226A
0.141;-11930.0
2A(29)
0.158;-9698.8
22(QA)
0.156;-8997.5
2(34A)
0.181;-12163.8
26(3A)
0.146;-11696.2
(29)(3A)
0.151;-9465.0
2(3QA)
0.220;-10293.8
A(234)
0.136;-12163.8
(23)(7A)
0.179;-9932.5
9A(23)
0.185;-10995.0
A(23Q)
0.182;-10293.8
2A(34)
0.126;-12163.8
2A(36)
0.176;-11696.2
2A(38)
0.184;-11228.7
2A(3T)
0.193;-10761.2
2A(3Q)
0.169;-10293.8
2(45A)
0.148;-11696.2
27(4A)
0.169;-11228.7
(2T)(4A)
0.240;-8997.5
2(4KA)
0.155;-9826.2
A(246)
0.154;-11462.5
(24)(9A)
0.156;-9231.2
JA(24)
0.170;-10293.8
24(5A)
0.162;-11696.2
24(7A)
0.177;-11228.7
24(9A)
0.145;-10761.2
24(JA)
0.152;-10293.8
24(KA)
0.165;-9826.2
26(5A)
0.151;-11228.7
(29)(5A)
0.245;-8997.5
2(5QA)
0.231;-9826.2
A(256)
0.226;-11228.7
(25)(9A)
0.161;-8997.5
JA(25)
0.236;-10060.0
25(6A)
0.129;-11228.7
25(8A)
0.139;-10761.2
25(TA)
0.190;-10293.8
25(QA)
0.215;-9826.2
(26)(6A)
0.239;-7935.0
2(69A)
0.159;-10293.8
2J(6A)
0.173;-9826.2
(26)(7A)
0.203;-9231.2
9A(26)
0.179;-10293.8
A(26Q)
0.239;-9592.5
2A(67)
0.202;-10761.2
2A(69)
0.175;-10293.8
2A(6J)
0.181;-9826.2
2A(6K)
0.193;-9358.8
(29)(7A)
0.179;-8530.0
2(7QA)
0.147;-9358.8
A(278)
0.182;-10293.8
(27)(JA)
0.174;-8062.5
KA(27)
0.227;-9125.0
2A(79)
0.226;-10060.0
2A(7J)
0.187;-9592.5
2A(7K)
0.238;-9125.0
(2T)(8A)
0.275;-8062.5
2(8KA)
0.235;-8891.2
A(28T)
0.210;-9592.5
(28)(KA)
0.225;-7361.2
28(TA)
0.193;-9592.5
28(QA)
0.192;-9125.0
(29)(9A)
0.207;-6532.5
2(9QA)
0.194;-8891.2
A(29T)
0.193;-9358.8
(29)(KA)
0.261;-7127.5
29(JA)
0.203;-9125.0
29(KA)
0.195;-8657.5
2J(TA)
0.155;-8891.2
(2T)(JA)
0.229;-7361.2
KA(2T)
0.214;-8423.7
2A(TQ)
0.167;-8657.5
2(JQA)
0.216;-8423.7
A(2JQ)
0.218;-8423.7
2A(JQ)
0.166;-8423.7
2(QKA)
0.274;-7956.2
2Q(KA)
0.185;-7956.2
33(3A)
0.188;-9103.8
(36)(3A)
0.181;-8402.5
3(39A)
0.244;-9231.2
3J(3A)
0.226;-8763.8
(345A)
0.183;-11462.5
(349A)
0.170;-10527.5
(34KA)
0.250;-9592.5
46(3A)
0.166;-11228.7
(49)(3A)
0.206;-8997.5
4(3QA)
0.205;-9826.2
6(35A)
0.154;-10995.0
T(35A)
0.211;-10060.0
5(36A)
0.163;-10995.0
58(3A)
0.185;-10527.5
(5J)(3A)
0.217;-8296.2
6(36A)
0.182;-9231.2
T(36A)
0.190;-9826.2
6(37A)
0.156;-10527.5
69(3A)
0.163;-10060.0
(6Q)(3A)
0.252;-7828.8
(379A)
0.221;-9826.2
(37KA)
0.196;-8891.2
79(3A)
0.145;-9826.2
(7Q)(3A)
0.252;-7595.0
(38TA)
0.151;-9358.8
88(3A)
0.228;-8296.2
(8J)(3A)
0.192;-7595.0
9(39A)
0.174;-7828.7
K(39A)
0.185;-8423.7
9(3QA)
0.183;-8657.5
J(3TA)
0.197;-8657.5
TJ(3A)
0.191;-8657.5
(3JQA)
0.193;-8190.0
J(3KA)
0.207;-7956.2
(QK)(3A)
0.273;-6192.5
33(5A)
0.135;-10166.2
337A
0.186;-11228.7
3A(3T)
0.224;-8997.5
33(KA)
0.179;-8296.2
3(46A)
0.206;-11228.7
38(4A)
0.162;-10761.2
(3J)(4A)
0.236;-8530.0
4A(34)
0.168;-10166.2
A(347)
0.147;-10995.0
(34)(TA)
0.210;-8763.8
QA(34)
0.171;-9826.2
345A
0.183;-12992.5
347A
0.136;-12525.0
349A
0.133;-12057.5
34JA
0.154;-11590.0
34KA
0.203;-11122.5
37(5A)
0.223;-10761.2
(3T)(5A)
0.221;-8530.0
3(5KA)
0.168;-9358.8
A(357)
0.179;-10761.2
(35)(TA)
0.215;-8530.0
QA(35)
0.155;-9592.5
356A
0.135;-12525.0
358A
0.160;-12057.5
35TA
0.155;-11590.0
35QA
0.170;-11122.5
(37)(6A)
0.233;-8997.5
3(6TA)
0.186;-9826.2
3Q(6A)
0.198;-9358.8
(36)(8A)
0.230;-8763.8
TA(36)
0.208;-9826.2
A(36K)
0.178;-9125.0
6A(38)
0.179;-10293.8
6A(3T)
0.188;-9826.2
6A(3Q)
0.242;-9358.8
37(7A)
0.205;-8763.8
(3T)(7A)
0.194;-8062.5
3(7KA)
0.208;-8891.2
A(379)
0.172;-9826.2
(37)(QA)
0.206;-7595.0
7A(38)
0.154;-10060.0
7A(3T)
0.169;-9592.5
7A(3Q)
0.172;-9125.0
38(8A)
0.193;-8296.2
(3J)(8A)
0.195;-7595.0
8A(38)
0.185;-8296.2
A(38J)
0.254;-9125.0
388A
0.209;-9826.2
38TA
0.144;-10888.8
38QA
0.199;-10421.2
(3T)(9A)
0.240;-7595.0
3(9KA)
0.264;-8423.7
A(39J)
0.186;-8891.2
399A
0.186;-9358.8
39JA
0.196;-10421.2
39KA
0.190;-9953.7
3Q(TA)
0.221;-8423.7
(3T)(QA)
0.250;-6893.7
TA(3J)
0.178;-8657.5
TA(3K)
0.237;-8190.0
3(JKA)
0.173;-7956.2
A(3JK)
0.198;-7956.2
JA(3K)
0.201;-7956.2
QA(3Q)
0.241;-6426.2
3QKA
0.222;-9252.5
45(4A)
0.147;-9698.8
(48)(4A)
0.212;-7467.5
4(4JA)
0.187;-8296.2
4K(4A)
0.194;-7828.7
(459A)
0.181;-10060.0
(45KA)
0.205;-9125.0
57(4A)
0.170;-10527.5
(5T)(4A)
0.179;-8296.2
5(4KA)
0.199;-9125.0
(469A)
0.169;-9826.2
(46KA)
0.191;-8891.2
68(4A)
0.146;-10060.0
(6J)(4A)
0.225;-7828.8
7(47A)
0.197;-8530.0
J(47A)
0.231;-9125.0
78(4A)
0.169;-9826.2
(7J)(4A)
0.227;-7595.0
8(48A)
0.193;-8062.5
Q(48A)
0.227;-8657.5
(8T)(4A)
0.223;-7595.0
8(4KA)
0.201;-8423.7
(49QA)
0.254;-8423.7
9(4JA)
0.195;-8657.5
9K(4A)
0.196;-8190.0
TT(4A)
0.277;-7127.5
(TK)(4A)
0.255;-6426.2
J(4QA)
0.234;-7956.2
K(4QA)
0.230;-7488.8
44(5A)
0.169;-9698.8
447A
0.178;-10761.2
4A(4T)
0.177;-8530.0
44(KA)
0.264;-7828.7
4(57A)
0.223;-10527.5
49(5A)
0.189;-10060.0
(4Q)(5A)
0.248;-7828.8
6A(45)
0.183;-10761.2
A(459)
0.152;-10060.0
(45)(QA)
0.231;-7828.8
5A(46)
0.132;-10761.2
5A(48)
0.192;-10293.8
5A(4T)
0.188;-9826.2
5A(4Q)
0.184;-9358.8
46(6A)
0.193;-8997.5
(49)(6A)
0.206;-8296.2
4(6QA)
0.183;-9125.0
A(467)
0.178;-10293.8
(46)(TA)
0.168;-8062.5
QA(46)
0.215;-9125.0
467A
0.194;-11823.8
469A
0.150;-11356.2
46JA
0.217;-10888.8
46KA
0.156;-10421.2
49(7A)
0.187;-9592.5
(4Q)(7A)
0.181;-7361.2
8A(47)
0.174;-9826.2
A(47J)
0.166;-9125.0
477A
0.161;-10060.0
479A
0.159;-11122.5
47JA
0.181;-10655.0
47KA
0.152;-10187.5
4T(8A)
0.193;-9125.0
(4K)(8A)
0.225;-6893.7
TA(48)
0.190;-9125.0
A(48K)
0.258;-8423.7
8A(4T)
0.248;-9125.0
8A(4Q)
0.176;-8657.5
49(9A)
0.231;-7595.0
(4Q)(9A)
0.278;-6893.7
TA(49)
0.201;-8891.2
A(49K)
0.171;-8190.0
9A(4J)
0.208;-8657.5
9A(4K)
0.162;-8190.0
4(TQA)
0.204;-8190.0
A(4TJ)
0.191;-8423.7
4TTA
0.223;-8657.5
4TQA
0.243;-9720.0
(4Q)(JA)
0.188;-6426.2
QA(4J)
0.185;-7956.2
4JQA
0.182;-9486.2
(4K)(QA)
0.243;-5958.8
QA(4K)
0.228;-7488.8
5(56A)
0.198;-8997.5
58(5A)
0.206;-8530.0
(5J)(5A)
0.266;-6298.7
6(56A)
0.190;-8763.8
T(56A)
0.174;-9358.8
6(57A)
0.164;-10060.0
69(5A)
0.204;-9592.5
(6Q)(5A)
0.231;-7361.2
(579A)
0.156;-9358.8
(57KA)
0.172;-8423.7
79(5A)
0.195;-9358.8
(7Q)(5A)
0.229;-7127.5
(58TA)
0.222;-8891.2
88(5A)
0.245;-7828.7
(8J)(5A)
0.224;-7127.5
9(59A)
0.234;-7361.2
K(59A)
0.191;-7956.2
9(5QA)
0.197;-8190.0
J(5TA)
0.232;-8190.0
TJ(5A)
0.202;-8190.0
(5JQA)
0.175;-7722.5
J(5KA)
0.241;-7488.8
(QK)(5A)
0.236;-5725.0
55(7A)
0.179;-8763.8
559A
0.192;-9826.2
5A(5Q)
0.252;-7595.0
(57)(6A)
0.219;-8530.0
5(6TA)
0.206;-9358.8
5Q(6A)
0.175;-8891.2
(56)(8A)
0.204;-8296.2
TA(56)
0.191;-9358.8
A(56K)
0.245;-8657.5
6A(58)
0.207;-9826.2
6A(5T)
0.214;-9358.8
6A(5Q)
0.186;-8891.2
57(7A)
0.209;-8296.2
(5T)(7A)
0.200;-7595.0
5(7KA)
0.235;-8423.7
A(579)
0.151;-9358.8
(57)(QA)
0.225;-7127.5
7A(58)
0.219;-9592.5
7A(5T)
0.173;-9125.0
7A(5Q)
0.185;-8657.5
58(8A)
0.194;-7828.7
(5J)(8A)
0.234;-7127.5
8A(58)
0.192;-7828.7
A(58J)
0.228;-8657.5
588A
0.221;-9358.8
58TA
0.184;-10421.2
58QA
0.184;-9953.7
(5T)(9A)
0.236;-7127.5
5(9KA)
0.264;-7956.2
A(59J)
0.154;-8423.7
599A
0.165;-8891.2
59JA
0.206;-9953.7
59KA
0.193;-9486.2
5Q(TA)
0.176;-7956.2
(5T)(QA)
0.217;-6426.2
TA(5J)
0.243;-8190.0
TA(5K)
0.246;-7722.5
5(JKA)
0.247;-7488.8
A(5JK)
0.173;-7488.8
JA(5K)
0.258;-7488.8
QA(5Q)
0.236;-5958.8
5QKA
0.249;-8785.0
67(6A)
0.180;-8296.2
(6T)(6A)
0.276;-6065.0
6(6KA)
0.301;-6893.7
(67TA)
0.163;-8891.2
77(6A)
0.199;-8062.5
(7T)(6A)
0.277;-7361.2
7(6KA)
0.197;-8190.0
(68JA)
0.253;-8423.7
(89)(6A)
0.239;-7361.2
8(6QA)
0.199;-8190.0
T(69A)
0.249;-8423.7
9(6TA)
0.213;-8423.7
9Q(6A)
0.228;-7956.2
Q(6TA)
0.224;-7722.5
(TQ)(6A)
0.261;-6192.5
(6JKA)
0.198;-7255.0
JK(6A)
0.204;-7255.0
K(6KA)
0.289;-5257.5
668A
0.194;-9592.5
6A(6J)
0.212;-7361.2
(67)(7A)
0.241;-6532.5
6(7TA)
0.158;-8891.2
6Q(7A)
0.224;-8423.7
(67)(9A)
0.243;-7595.0
JA(67)
0.211;-8657.5
67(8A)
0.147;-9358.8
67(TA)
0.190;-8891.2
67(QA)
0.209;-8423.7
(68)(8A)
0.298;-6065.0
6(8JA)
0.209;-8423.7
6K(8A)
0.179;-7956.2
(68)(JA)
0.265;-6893.7
KA(68)
0.250;-7956.2
6A(8T)
0.221;-8657.5
6A(8Q)
0.230;-8190.0
6(9TA)
0.204;-8423.7
6Q(9A)
0.221;-7956.2
(69)(JA)
0.188;-6660.0
KA(69)
0.174;-7722.5
6A(9J)
0.213;-8190.0
6A(9K)
0.236;-7722.5
(6Q)(TA)
0.243;-6192.5
JA(6T)
0.180;-7956.2
6T(JA)
0.200;-7956.2
6T(KA)
0.240;-7488.8
6Q(JA)
0.190;-7488.8
(6J)(KA)
0.316;-5725.0
6J(KA)
0.268;-7255.0
6K(QA)
0.216;-7021.2
6A(QK)
0.277;-7021.2
(78)(7A)
0.217;-6065.0
7(7JA)
0.183;-6893.7
7K(7A)
0.193;-6426.2
(78QA)
0.195;-7956.2
8(7TA)
0.199;-8423.7
8Q(7A)
0.212;-7956.2
J(79A)
0.231;-7956.2
9T(7A)
0.237;-8190.0
(9K)(7A)
0.286;-5958.8
K(7TA)
0.240;-7255.0
T(7KA)
0.296;-7255.0
JJ(7A)
0.194;-5958.8
(7QKA)
0.216;-6787.5
777A
0.205;-7828.8
7A(7T)
0.212;-7127.5
77(KA)
0.255;-6426.2
7(8TA)
0.215;-8423.7
7Q(8A)
0.214;-7956.2
(78)(TA)
0.196;-6893.7
QA(78)
0.199;-7956.2
789A
0.143;-10187.5
78JA
0.216;-9720.0
78KA
0.196;-9252.5
7J(9A)
0.210;-7956.2
(79)(TA)
0.244;-6660.0
QA(79)
0.231;-7722.5
79TA
0.214;-9720.0
79QA
0.188;-9252.5
(7J)(TA)
0.245;-6192.5
TA(7T)
0.212;-6426.2
A(7TK)
0.228;-7255.0
TA(7Q)
0.187;-7488.8
7J(JA)
0.268;-5958.8
(7J)(QA)
0.198;-5725.0
JA(7Q)
0.188;-7255.0
7Q(QA)
0.231;-5491.2
7QQA
0.206;-7021.2
7KKA
0.230;-6553.8
8(8JA)
0.271;-6426.2
8K(8A)
0.206;-5958.8
(89KA)
0.216;-7255.0
9J(8A)
0.255;-7722.5
(8TJA)
0.249;-7488.8
(TJ)(8A)
0.217;-5958.8
J(8JA)
0.239;-5725.0
JQ(8A)
0.203;-7021.2
Q(8KA)
0.202;-6553.8
889A
0.243;-8423.7
8A(8Q)
0.277;-6192.5
(8T)(9A)
0.270;-6426.2
8(9KA)
0.197;-7255.0
A(89J)
0.237;-7722.5
899A
0.219;-8190.0
89JA
0.189;-9252.5
89KA
0.197;-8785.0
8Q(TA)
0.207;-7255.0
(8T)(QA)
0.218;-5725.0
TA(8J)
0.233;-7488.8
TA(8K)
0.214;-7021.2
8(JKA)
0.248;-6787.5
A(8JK)
0.218;-6787.5
JA(8K)
0.208;-6787.5
QA(8Q)
0.208;-5257.5
8QKA
0.251;-8083.8
9T(9A)
0.223;-6192.5
(9K)(9A)
0.249;-3961.2
K(9TA)
0.219;-6787.5
T(9KA)
0.261;-6787.5
JJ(9A)
0.232;-5491.2
(9QKA)
0.241;-6320.0
999A
0.294;-6426.2
9A(9Q)
0.218;-5725.0
(9J)(TA)
0.220;-5725.0
TA(9T)
0.240;-5958.8
A(9TK)
0.226;-6787.5
TA(9Q)
0.197;-7021.2
9J(JA)
0.283;-5491.2
(9J)(QA)
0.306;-5257.5
JA(9Q)
0.263;-6787.5
9Q(QA)
0.220;-5023.8
9QQA
0.231;-6553.8
9KKA
0.280;-6086.2
T(TKA)
0.220;-5023.8
JJ(TA)
0.286;-5257.5
(TQKA)
0.241;-6086.2
TTTA
0.202;-5725.0
TA(TK)
0.214;-5023.8
(TK)(JA)
0.285;-4790.0
KA(TJ)
0.219;-6320.0
TA(JK)
0.247;-6320.0
(TQ)(KA)
0.338;-4556.2
(TK)(KA)
0.269;-2792.5
J(JKA)
0.212;-4556.2
(QK)(JA)
0.292;-4322.5
JJ(KA)
0.280;-4556.2
QA(JQ)
0.238;-4556.2
JQKA
0.207;-7382.5
QK(QA)
0.249;-4088.8
QK(KA)
0.263;-3855.0
22(24)
0.153;-12142.5
22(28)
0.161;-11207.5
22(2Q)
0.155;-10272.5
24(23)
0.150;-13438.7
(23)(27)
0.159;-11207.5
2(23T)
0.158;-12036.2
2Q(23)
0.204;-11568.8
23(25)
0.118;-13205.0
2237
0.120;-14267.5
22(3T)
0.163;-12036.2
23(2K)
0.148;-11335.0
2(246)
0.182;-12737.5
28(24)
0.206;-12270.0
(24)(2J)
0.227;-10038.8
2244
0.136;-13205.0
22(47)
0.172;-12503.8
24(2T)
0.149;-11802.5
224Q
0.143;-12865.0
26(25)
0.122;-12503.8
(25)(29)
0.209;-10272.5
2(25Q)
0.196;-11101.2
22(56)
0.185;-12503.8
25(29)
0.133;-11802.5
225J
0.130;-12865.0
26(26)
0.129;-10740.0
(26)(29)
0.176;-10038.8
2(26Q)
0.190;-10867.5
22(67)
0.202;-12036.2
26(2T)
0.135;-11335.0
226Q
0.155;-12397.5
28(27)
0.171;-11568.8
(27)(2J)
0.193;-9337.5
2277
0.184;-11802.5
22(7T)
0.183;-11101.2
27(2K)
0.174;-10400.0
2(28T)
0.206;-10867.5
2Q(28)
0.175;-10400.0
28(2T)
0.193;-10867.5
228Q
0.161;-11930.0
2T(29)
0.186;-10633.8
(29)(2K)
0.185;-8402.5
229J
0.146;-11930.0
2T(2T)
0.170;-8870.0
(2T)(2K)
0.190;-8168.7
22TQ
0.149;-11462.5
2Q(2J)
0.180;-9698.8
2J(2K)
0.163;-9465.0
22QQ
0.176;-9465.0
3(234)
0.146;-13205.0
36(23)
0.142;-12737.5
(23)(39)
0.141;-10506.2
3(23Q)
0.165;-11335.0
5(234)
0.134;-14267.5
9(234)
0.124;-13332.5
K(234)
0.167;-12397.5
4(237)
0.141;-13800.0
49(23)
0.148;-13332.5
(23)(4Q)
0.140;-11101.2
(2357)
0.148;-13566.2
(235J)
0.115;-12631.3
(23)(56)
0.161;-12270.0
5(239)
0.132;-13098.7
5J(23)
0.114;-12631.3
(2367)
0.191;-13332.5
(236J)
0.170;-12397.5
(23)(67)
0.142;-11802.5
6(23T)
0.160;-12631.3
6Q(23)
0.151;-12163.8
9(237)
0.127;-12631.3
K(237)
0.172;-11696.2
7(23T)
0.159;-12397.5
7Q(23)
0.161;-11930.0
T(238)
0.165;-12163.8
8(239)
0.133;-12397.5
8J(23)
0.117;-11930.0
(239T)
0.189;-11930.0
99(23)
0.205;-10633.8
(23)(9Q)
0.185;-9932.5
(23TQ)
0.161;-11228.7
T(23Q)
0.142;-11228.7
Q(23J)
0.172;-10995.0
(23)(JK)
0.229;-9231.2
QK(23)
0.134;-10527.5
23(35)
0.177;-12971.3
33(28)
0.124;-12270.0
233T
0.143;-13332.5
23(3K)
0.153;-11101.2
(24)(36)
0.140;-12503.8
3(249)
0.125;-13332.5
3J(24)
0.137;-12865.0
(34)(25)
0.129;-12737.5
27(34)
0.143;-13800.0
2(34T)
0.142;-13098.7
(34)(2K)
0.155;-10867.5
34(26)
0.136;-14033.8
34(28)
0.175;-13566.2
34(2T)
0.141;-13098.7
34(2Q)
0.146;-12631.3
(25)(35)
0.130;-10973.8
3(258)
0.166;-13332.5
3T(25)
0.114;-12865.0
(25)(3K)
0.145;-10633.8
27(35)
0.137;-13566.2
2(35T)
0.169;-12865.0
(35)(2K)
0.167;-10633.8
35(27)
0.147;-13566.2
35(29)
0.186;-13098.7
35(2J)
0.126;-12631.3
35(2K)
0.142;-12163.8
37(26)
0.165;-13332.5
(26)(3T)
0.180;-11101.2
3(26K)
0.213;-11930.0
2(368)
0.119;-13098.7
(36)(2J)
0.181;-10867.5
2K(36)
0.147;-11930.0
23(68)
0.144;-13098.7
23(6T)
0.143;-12631.3
23(6Q)
0.118;-12163.8
3(278)
0.137;-12865.0
3T(27)
0.152;-12397.5
(27)(3K)
0.162;-10166.2
29(37)
0.151;-12631.3
2(37Q)
0.147;-11930.0
23(78)
0.143;-12865.0
23(7T)
0.158;-12397.5
23(7Q)
0.189;-11930.0
3(289)
0.156;-12397.5
3J(28)
0.192;-11930.0
(38)(29)
0.148;-10867.5
2J(38)
0.203;-11930.0
38(29)
0.156;-12397.5
38(2J)
0.131;-11930.0
38(2K)
0.166;-11462.5
3T(29)
0.197;-11930.0
(29)(3K)
0.139;-9698.8
2J(39)
0.170;-11696.2
39(2T)
0.166;-11930.0
39(2Q)
0.143;-11462.5
(2T)(3T)
0.189;-8636.2
3(2TK)
0.203;-10995.0
2(3TQ)
0.175;-11228.7
23(TJ)
0.186;-11462.5
23(TK)
0.199;-10995.0
(2J)(3K)
0.213;-9231.2
2K(3J)
0.195;-10761.2
23(JK)
0.193;-10761.2
(3Q)(2K)
0.165;-8997.5
(2K)(3K)
0.195;-7233.8
4(246)
0.151;-12270.0
48(24)
0.145;-11802.5
(24)(4J)
0.158;-9571.3
5(245)
0.174;-12270.0
9(245)
0.161;-12865.0
K(245)
0.141;-11930.0
5(248)
0.145;-13098.7
5T(24)
0.169;-12631.3
(24)(5K)
0.169;-10400.0
9(246)
0.163;-12631.3
K(246)
0.137;-11696.2
6(249)
0.151;-12631.3
6J(24)
0.170;-12163.8
(2478)
0.142;-12631.3
(247Q)
0.143;-11696.2
7(249)
0.142;-12397.5
7J(24)
0.144;-11930.0
(2489)
0.136;-12163.8
(248K)
0.128;-11228.7
8T(24)
0.139;-11930.0
(24)(8K)
0.214;-9698.8
Q(249)
0.138;-11228.7
(24)(9J)
0.173;-9932.5
T(24T)
0.208;-9932.5
T(24J)
0.160;-11228.7
TK(24)
0.140;-10761.2
(24)(JQ)
0.219;-9231.2
QQ(24)
0.146;-8997.5
24(45)
0.150;-12503.8
44(28)
0.134;-11802.5
244T
0.146;-12865.0
24(4K)
0.194;-10633.8
(25)(47)
0.161;-11802.5
4(25T)
0.169;-12631.3
4Q(25)
0.136;-12163.8
(45)(27)
0.161;-11802.5
29(45)
0.172;-12865.0
2(45Q)
0.170;-12163.8
24(56)
0.150;-13566.2
24(58)
0.144;-13098.7
24(5T)
0.154;-12631.3
24(5Q)
0.193;-12163.8
4(267)
0.126;-13098.7
49(26)
0.161;-12631.3
(26)(4Q)
0.166;-10400.0
27(46)
0.142;-13098.7
2(46T)
0.126;-12397.5
(46)(2K)
0.173;-10166.2
46(28)
0.164;-12865.0
46(2T)
0.142;-12397.5
46(2Q)
0.157;-11930.0
(27)(47)
0.182;-9805.0
4(27T)
0.142;-12163.8
4Q(27)
0.154;-11696.2
(47)(29)
0.218;-10867.5
2J(47)
0.139;-11930.0
47(28)
0.191;-12631.3
47(2T)
0.164;-12163.8
47(2Q)
0.209;-11696.2
(28)(48)
0.204;-9337.5
4(28J)
0.191;-11696.2
4K(28)
0.163;-11228.7
(48)(2J)
0.164;-10166.2
2K(48)
0.167;-11228.7
24(8T)
0.129;-11930.0
24(8Q)
0.157;-11462.5
4(29T)
0.151;-11696.2
4Q(29)
0.148;-11228.7
(49)(2J)
0.155;-9932.5
2K(49)
0.166;-10995.0
24(9J)
0.190;-11462.5
24(9K)
0.187;-10995.0
(2T)(4Q)
0.174;-9465.0
2J(4T)
0.187;-11228.7
4T(2J)
0.144;-11228.7
4T(2K)
0.177;-10761.2
4Q(2J)
0.215;-10761.2
(4J)(2K)
0.195;-8997.5
4J(2K)
0.202;-10527.5
4K(2Q)
0.132;-10293.8
24(QK)
0.138;-10293.8
(25)(56)
0.197;-10272.5
5(259)
0.201;-11101.2
5J(25)
0.165;-10633.8
(2567)
0.125;-12865.0
(256J)
0.159;-11930.0
(25)(67)
0.136;-11335.0
6(25T)
0.130;-12163.8
6Q(25)
0.154;-11696.2
9(257)
0.154;-12163.8
K(257)
0.177;-11228.7
7(25T)
0.161;-11930.0
7Q(25)
0.194;-11462.5
T(258)
0.146;-11696.2
8(259)
0.156;-11930.0
8J(25)
0.130;-11462.5
(259T)
0.165;-11462.5
99(25)
0.161;-10166.2
(25)(9Q)
0.205;-9465.0
(25TQ)
0.158;-10761.2
T(25Q)
0.127;-10761.2
Q(25J)
0.162;-10527.5
(25)(JK)
0.158;-8763.8
QK(25)
0.190;-10060.0
25(57)
0.172;-11568.8
55(2T)
0.181;-10867.5
255Q
0.201;-11930.0
57(26)
0.122;-12865.0
(26)(5T)
0.198;-10633.8
5(26K)
0.159;-11462.5
2(568)
0.159;-12631.3
(56)(2J)
0.189;-10400.0
2K(56)
0.156;-11462.5
25(68)
0.149;-12631.3
25(6T)
0.154;-12163.8
25(6Q)
0.139;-11696.2
5(278)
0.156;-12397.5
5T(27)
0.141;-11930.0
(27)(5K)
0.156;-9698.8
29(57)
0.155;-12163.8
2(57Q)
0.162;-11462.5
25(78)
0.177;-12397.5
25(7T)
0.195;-11930.0
25(7Q)
0.139;-11462.5
5(289)
0.203;-11930.0
5J(28)
0.179;-11462.5
(58)(29)
0.191;-10400.0
2J(58)
0.193;-11462.5
58(29)
0.127;-11930.0
58(2J)
0.194;-11462.5
58(2K)
0.172;-10995.0
5T(29)
0.193;-11462.5
(29)(5K)
0.173;-9231.2
2J(59)
0.147;-11228.7
59(2T)
0.190;-11462.5
59(2Q)
0.150;-10995.0
(2T)(5T)
0.225;-8168.7
5(2TK)
0.169;-10527.5
2(5TQ)
0.164;-10761.2
25(TJ)
0.159;-10995.0
25(TK)
0.193;-10527.5
(2J)(5K)
0.189;-8763.8
2K(5J)
0.154;-10293.8
25(JK)
0.192;-10293.8
(5Q)(2K)
0.197;-8530.0
(2K)(5K)
0.255;-6766.2
6(268)
0.208;-10867.5
6T(26)
0.135;-10400.0
(26)(6K)
0.214;-8168.7
T(267)
0.176;-11696.2
7(268)
0.180;-12163.8
7T(26)
0.193;-11696.2
(26)(7K)
0.191;-9465.0
J(268)
0.148;-11228.7
89(26)
0.137;-11696.2
(26)(8Q)
0.174;-9465.0
(269J)
0.148;-10995.0
(26)(9T)
0.185;-9698.8
9(26K)
0.149;-10527.5
(26TK)
0.151;-10293.8
TQ(26)
0.176;-10527.5
K(26J)
0.179;-10060.0
Q(26Q)
0.198;-8530.0
KK(26)
0.219;-8062.5
66(29)
0.161;-10633.8
266J
0.139;-11696.2
67(27)
0.154;-10867.5
(27)(6T)
0.166;-10166.2
6(27K)
0.225;-10995.0
2(679)
0.156;-11930.0
(67)(2Q)
0.177;-9698.8
27(68)
0.152;-12163.8
27(6T)
0.115;-11696.2
27(6Q)
0.147;-11228.7
68(28)
0.175;-10400.0
(28)(6J)
0.140;-9698.8
28(68)
0.194;-10400.0
2(68J)
0.177;-11228.7
2688
0.153;-11930.0
268T
0.132;-12992.5
268Q
0.133;-12525.0
(29)(6T)
0.192;-9698.8
6(29K)
0.167;-10527.5
2(69J)
0.166;-10995.0
2699
0.150;-11462.5
269J
0.178;-12525.0
269K
0.138;-12057.5
6Q(2T)
0.225;-10527.5
(6T)(2Q)
0.174;-8997.5
2T(6J)
0.135;-10761.2
2T(6K)
0.186;-10293.8
6(2JK)
0.186;-10060.0
2(6JK)
0.223;-10060.0
2J(6K)
0.230;-10060.0
2Q(6Q)
0.259;-8530.0
26QK
0.133;-11356.2
78(27)
0.163;-10400.0
(27)(7J)
0.186;-8168.7
8(278)
0.173;-10166.2
Q(278)
0.193;-10761.2
(27)(8T)
0.148;-9698.8
8(27K)
0.151;-10527.5
(279Q)
0.150;-10527.5
9(27J)
0.172;-10761.2
9K(27)
0.140;-10293.8
TT(27)
0.159;-9231.2
(27)(TK)
0.217;-8530.0
J(27Q)
0.142;-10060.0
K(27Q)
0.193;-9592.5
77(28)
0.168;-10400.0
277T
0.153;-11462.5
27(7K)
0.228;-9231.2
(28)(7T)
0.172;-9698.8
7(28K)
0.144;-10527.5
2(78T)
0.181;-11228.7
(78)(2K)
0.226;-8997.5
78(2T)
0.227;-11228.7
78(2Q)
0.154;-10761.2
(29)(79)
0.197;-8168.7
7(29Q)
0.163;-10527.5
2(79T)
0.179;-10995.0
(79)(2K)
0.250;-8763.8
79(2J)
0.180;-10761.2
79(2K)
0.168;-10293.8
7J(2T)
0.167;-10527.5
(7T)(2J)
0.163;-8997.5
2K(7T)
0.206;-10060.0
27(TQ)
0.176;-10293.8
7(2JQ)
0.190;-10060.0
2(7JQ)
0.189;-10060.0
27(JQ)
0.146;-10060.0
7(2QK)
0.182;-9592.5
7Q(2K)
0.174;-9592.5
88(28)
0.211;-8402.5
(28)(8J)
0.199;-7701.2
9(289)
0.199;-9465.0
K(289)
0.239;-10060.0
9(28Q)
0.174;-10293.8
J(28T)
0.213;-10293.8
TJ(28)
0.171;-10293.8
(28JQ)
0.182;-9826.2
J(28K)
0.156;-9592.5
(28)(QK)
0.170;-7828.8
88(2T)
0.167;-9465.0
288Q
0.168;-10527.5
8T(29)
0.148;-10761.2
(29)(8K)
0.182;-8530.0
2J(89)
0.180;-10527.5
89(2T)
0.185;-10761.2
89(2Q)
0.180;-10293.8
(2T)(8T)
0.203;-7467.5
8(2TK)
0.176;-9826.2
2(8TQ)
0.151;-10060.0
28(TJ)
0.181;-10293.8
28(TK)
0.181;-9826.2
(2J)(8K)
0.198;-8062.5
2K(8J)
0.178;-9592.5
28(JK)
0.180;-9592.5
(8Q)(2K)
0.217;-7828.8
(2K)(8K)
0.250;-6065.0
9(29J)
0.195;-8763.8
9K(29)
0.202;-8296.2
TT(29)
0.216;-8763.8
(29)(TK)
0.219;-8062.5
J(29Q)
0.186;-9592.5
K(29Q)
0.182;-9125.0
99(2T)
0.205;-8997.5
299Q
0.171;-10060.0
9J(2T)
0.188;-10060.0
(9T)(2J)
0.197;-8530.0
2K(9T)
0.169;-9592.5
29(TQ)
0.215;-9826.2
9(2JQ)
0.151;-9592.5
2(9JQ)
0.193;-9592.5
29(JQ)
0.196;-9592.5
9(2QK)
0.213;-9125.0
9Q(2K)
0.204;-9125.0
TT(2T)
0.280;-7000.0
(2T)(TK)
0.216;-6298.7
J(2TQ)
0.195;-9358.8
K(2TQ)
0.201;-8891.2
TT(2J)
0.195;-8296.2
2TTK
0.193;-9358.8
TK(2J)
0.182;-9125.0
2TJJ
0.191;-9592.5
2TJK
0.188;-10655.0
2(TQK)
0.198;-8891.2
TK(2K)
0.185;-7127.5
(2J)(JK)
0.281;-5831.3
QK(2J)
0.225;-8657.5
2J(JK)
0.202;-7361.2
(JQ)(2K)
0.238;-7127.5
(2K)(JK)
0.272;-5363.7
K(2QK)
0.200;-6660.0
2K(QK)
0.212;-6660.0
3335
0.167;-12737.5
3339
0.146;-11802.5
333K
0.227;-10867.5
36(34)
0.191;-12270.0
(34)(39)
0.154;-10038.8
3(34Q)
0.175;-10867.5
33(45)
0.142;-12503.8
34(38)
0.188;-11802.5
334T
0.148;-12865.0
33(4K)
0.200;-10633.8
(35)(37)
0.141;-10272.5
3(35T)
0.167;-11101.2
3Q(35)
0.146;-10633.8
35(37)
0.146;-11802.5
3359
0.129;-12865.0
33(5Q)
0.151;-10633.8
(36)(37)
0.149;-10038.8
3(36T)
0.160;-10867.5
3Q(36)
0.165;-10400.0
36(38)
0.210;-11335.0
336T
0.144;-12397.5
33(6K)
0.189;-10166.2
(37)(39)
0.228;-9337.5
3(37Q)
0.172;-10166.2
33(78)
0.155;-11101.2
37(3J)
0.240;-10400.0
337K
0.201;-11462.5
3T(38)
0.175;-10400.0
(38)(3K)
0.243;-8168.7
338T
0.150;-11930.0
33(8K)
0.188;-9698.8
(39)(3J)
0.270;-8402.5
3399
0.202;-10400.0
33(9Q)
0.197;-9698.8
(3T)(3J)
0.193;-8168.7
33TT
0.164;-9932.5
33(TK)
0.200;-9231.2
(3J)(3K)
0.217;-7467.5
33JK
0.177;-10527.5
33(QK)
0.154;-8763.8
45(34)
0.176;-12270.0
(34)(48)
0.154;-10038.8
4(34J)
0.201;-10867.5
4K(34)
0.177;-10400.0
(3459)
0.129;-12631.3
(345K)
0.184;-11696.2
57(34)
0.138;-13098.7
(34)(5T)
0.183;-10867.5
5(34K)
0.175;-11696.2
(3469)
0.146;-12397.5
(346K)
0.166;-11462.5
68(34)
0.150;-12631.3
(34)(6J)
0.140;-10400.0
7(347)
0.194;-11101.2
J(347)
0.180;-11696.2
78(34)
0.174;-12397.5
(34)(7J)
0.172;-10166.2
8(348)
0.190;-10633.8
Q(348)
0.166;-11228.7
(34)(8T)
0.152;-10166.2
8(34K)
0.171;-10995.0
(349Q)
0.219;-10995.0
9(34J)
0.199;-11228.7
9K(34)
0.168;-10761.2
TT(34)
0.196;-9698.8
(34)(TK)
0.176;-8997.5
J(34Q)
0.172;-10527.5
K(34Q)
0.175;-10060.0
44(35)
0.145;-12270.0
3447
0.159;-13332.5
34(4T)
0.211;-11101.2
44(3K)
0.181;-10400.0
4(357)
0.136;-13098.7
49(35)
0.131;-12631.3
(35)(4Q)
0.167;-10400.0
36(45)
0.141;-13332.5
3(459)
0.160;-12631.3
(45)(3Q)
0.162;-10400.0
35(46)
0.111;-13332.5
35(48)
0.150;-12865.0
35(4T)
0.141;-12397.5
35(4Q)
0.191;-11930.0
46(36)
0.188;-11568.8
(36)(49)
0.170;-10867.5
4(36Q)
0.148;-11696.2
3(467)
0.143;-12865.0
(46)(3T)
0.171;-10633.8
3Q(46)
0.148;-11696.2
3467
0.129;-14395.0
3469
0.144;-13927.5
346J
0.125;-13460.0
346K
0.144;-12992.5
49(37)
0.181;-12163.8
(37)(4Q)
0.220;-9932.5
38(47)
0.123;-12397.5
3(47J)
0.147;-11696.2
3477
0.124;-12631.3
3479
0.166;-13693.8
347J
0.172;-13226.2
347K
0.155;-12758.8
4T(38)
0.184;-11696.2
(38)(4K)
0.169;-9465.0
3T(48)
0.144;-11696.2
3(48K)
0.175;-10995.0
38(4T)
0.148;-11696.2
38(4Q)
0.168;-11228.7
49(39)
0.172;-10166.2
(39)(4Q)
0.189;-9465.0
3T(49)
0.183;-11462.5
3(49K)
0.183;-10761.2
39(4J)
0.163;-11228.7
39(4K)
0.156;-10761.2
4(3TQ)
0.187;-10761.2
3(4TJ)
0.175;-10995.0
34TT
0.196;-11228.7
34TQ
0.194;-12291.2
(3J)(4Q)
0.168;-8997.5
3Q(4J)
0.190;-10527.5
34JQ
0.145;-12057.5
(3Q)(4K)
0.221;-8530.0
3Q(4K)
0.229;-10060.0
5(356)
0.140;-11568.8
58(35)
0.138;-11101.2
(35)(5J)
0.176;-8870.0
6(356)
0.154;-11335.0
T(356)
0.162;-11930.0
6(357)
0.133;-12631.3
69(35)
0.145;-12163.8
(35)(6Q)
0.169;-9932.5
(3579)
0.133;-11930.0
(357K)
0.157;-10995.0
79(35)
0.176;-11930.0
(35)(7Q)
0.235;-9698.8
(358T)
0.127;-11462.5
88(35)
0.178;-10400.0
(35)(8J)
0.217;-9698.8
9(359)
0.197;-9932.5
K(359)
0.214;-10527.5
9(35Q)
0.169;-10761.2
J(35T)
0.148;-10761.2
TJ(35)
0.184;-10761.2
(35JQ)
0.181;-10293.8
J(35K)
0.183;-10060.0
(35)(QK)
0.235;-8296.2
55(37)
0.178;-11335.0
3559
0.179;-12397.5
35(5Q)
0.227;-10166.2
(36)(57)
0.159;-11101.2
5(36T)
0.134;-11930.0
5Q(36)
0.158;-11462.5
(56)(38)
0.157;-10867.5
3T(56)
0.160;-11930.0
3(56K)
0.128;-11228.7
36(58)
0.161;-12397.5
36(5T)
0.158;-11930.0
36(5Q)
0.168;-11462.5
57(37)
0.160;-10867.5
(37)(5T)
0.167;-10166.2
5(37K)
0.165;-10995.0
3(579)
0.156;-11930.0
(57)(3Q)
0.165;-9698.8
37(58)
0.143;-12163.8
37(5T)
0.145;-11696.2
37(5Q)
0.134;-11228.7
58(38)
0.214;-10400.0
(38)(5J)
0.197;-9698.8
38(58)
0.166;-10400.0
3(58J)
0.141;-11228.7
3588
0.131;-11930.0
358T
0.139;-12992.5
358Q
0.120;-12525.0
(39)(5T)
0.208;-9698.8
5(39K)
0.193;-10527.5
3(59J)
0.172;-10995.0
3599
0.124;-11462.5
359J
0.140;-12525.0
359K
0.183;-12057.5
5Q(3T)
0.146;-10527.5
(5T)(3Q)
0.168;-8997.5
3T(5J)
0.146;-10761.2
3T(5K)
0.169;-10293.8
5(3JK)
0.145;-10060.0
3(5JK)
0.227;-10060.0
3J(5K)
0.134;-10060.0
3Q(5Q)
0.183;-8530.0
35QK
0.155;-11356.2
67(36)
0.176;-10867.5
(36)(6T)
0.181;-8636.2
6(36K)
0.175;-9465.0
(367T)
0.209;-11462.5
77(36)
0.142;-10633.8
(36)(7T)
0.227;-9932.5
7(36K)
0.190;-10761.2
(368J)
0.150;-10995.0
(36)(89)
0.164;-9932.5
8(36Q)
0.161;-10761.2
T(369)
0.220;-10995.0
9(36T)
0.191;-10995.0
9Q(36)
0.175;-10527.5
Q(36T)
0.158;-10293.8
(36)(TQ)
0.211;-8763.8
(36JK)
0.170;-9826.2
JK(36)
0.229;-9826.2
K(36K)
0.210;-7828.7
3668
0.191;-12163.8
36(6J)
0.149;-9932.5
(37)(67)
0.201;-9103.8
6(37T)
0.166;-11462.5
6Q(37)
0.180;-10995.0
(67)(39)
0.171;-10166.2
3J(67)
0.177;-11228.7
67(38)
0.135;-11930.0
67(3T)
0.154;-11462.5
67(3Q)
0.170;-10995.0
(38)(68)
0.166;-8636.2
6(38J)
0.174;-10995.0
6K(38)
0.159;-10527.5
(68)(3J)
0.223;-9465.0
3K(68)
0.193;-10527.5
36(8T)
0.182;-11228.7
36(8Q)
0.173;-10761.2
6(39T)
0.171;-10995.0
6Q(39)
0.174;-10527.5
(69)(3J)
0.199;-9231.2
3K(69)
0.157;-10293.8
36(9J)
0.213;-10761.2
36(9K)
0.180;-10293.8
(3T)(6Q)
0.243;-8763.8
3J(6T)
0.140;-10527.5
6T(3J)
0.188;-10527.5
6T(3K)
0.148;-10060.0
6Q(3J)
0.181;-10060.0
(6J)(3K)
0.177;-8296.2
6J(3K)
0.141;-9826.2
6K(3Q)
0.235;-9592.5
36(QK)
0.240;-9592.5
(37)(78)
0.180;-8636.2
7(37J)
0.205;-9465.0
7K(37)
0.190;-8997.5
(378Q)
0.151;-10527.5
8(37T)
0.223;-10995.0
8Q(37)
0.153;-10527.5
J(379)
0.186;-10527.5
9T(37)
0.184;-10761.2
(37)(9K)
0.169;-8530.0
K(37T)
0.208;-9826.2
T(37K)
0.201;-9826.2
JJ(37)
0.230;-8530.0
(37QK)
0.186;-9358.8
3777
0.157;-10400.0
37(7T)
0.151;-9698.8
77(3K)
0.198;-8997.5
7(38T)
0.155;-10995.0
7Q(38)
0.184;-10527.5
(78)(3T)
0.235;-9465.0
3Q(78)
0.169;-10527.5
3789
0.170;-12758.8
378J
0.119;-12291.2
378K
0.168;-11823.8
7J(39)
0.127;-10527.5
(79)(3T)
0.179;-9231.2
3Q(79)
0.151;-10293.8
379T
0.139;-12291.2
379Q
0.170;-11823.8
(3T)(7J)
0.244;-8763.8
3T(7T)
0.188;-8997.5
3(7TK)
0.165;-9826.2
3T(7Q)
0.231;-10060.0
7J(3J)
0.177;-8530.0
(7J)(3Q)
0.226;-8296.2
3J(7Q)
0.202;-9826.2
7Q(3Q)
0.177;-8062.5
37QQ
0.218;-9592.5
37KK
0.228;-9125.0
8(38J)
0.212;-8997.5
8K(38)
0.159;-8530.0
(389K)
0.175;-9826.2
9J(38)
0.211;-10293.8
(38TJ)
0.186;-10060.0
(38)(TJ)
0.162;-8530.0
J(38J)
0.199;-8296.2
JQ(38)
0.216;-9592.5
Q(38K)
0.242;-9125.0
3889
0.177;-10995.0
38(8Q)
0.166;-8763.8
(39)(8T)
0.151;-8997.5
8(39K)
0.178;-9826.2
3(89J)
0.178;-10293.8
3899
0.210;-10761.2
389J
0.144;-11823.8
389K
0.160;-11356.2
8Q(3T)
0.184;-9826.2
(8T)(3Q)
0.262;-8296.2
3T(8J)
0.170;-10060.0
3T(8K)
0.149;-9592.5
8(3JK)
0.230;-9358.8
3(8JK)
0.200;-9358.8
3J(8K)
0.160;-9358.8
3Q(8Q)
0.277;-7828.7
38QK
0.222;-10655.0
9T(39)
0.198;-8763.8
(39)(9K)
0.230;-6532.5
K(39T)
0.158;-9358.8
T(39K)
0.219;-9358.8
JJ(39)
0.233;-8062.5
(39QK)
0.213;-8891.2
3999
0.221;-8997.5
39(9Q)
0.229;-8296.2
(3T)(9J)
0.168;-8296.2
3T(9T)
0.224;-8530.0
3(9TK)
0.175;-9358.8
3T(9Q)
0.236;-9592.5
9J(3J)
0.258;-8062.5
(9J)(3Q)
0.222;-7828.8
3J(9Q)
0.222;-9358.8
9Q(3Q)
0.266;-7595.0
39QQ
0.228;-9125.0
39KK
0.203;-8657.5
T(3TK)
0.217;-7595.0
JJ(3T)
0.223;-7828.7
(3TQK)
0.186;-8657.5
3TTT
0.200;-8296.2
3T(TK)
0.223;-7595.0
(3J)(TK)
0.222;-7361.2
3K(TJ)
0.190;-8891.2
3T(JK)
0.224;-8891.2
(TQ)(3K)
0.251;-7127.5
(3K)(TK)
0.214;-5363.7
J(3JK)
0.198;-7127.5
(3J)(QK)
0.287;-6893.7
JJ(3K)
0.242;-7127.5
3Q(JQ)
0.243;-7127.5
3JQK
0.173;-9953.7
QK(3Q)
0.232;-6660.0
QK(3K)
0.215;-6426.2
44(46)
0.173;-10272.5
44(4T)
0.223;-9337.5
(45)(45)
0.194;-8742.5
4(458)
0.208;-11101.2
4T(45)
0.185;-10633.8
(45)(4K)
0.191;-8402.5
4457
0.133;-12865.0
44(5T)
0.210;-10633.8
45(4K)
0.182;-9932.5
4(468)
0.140;-10867.5
4T(46)
0.166;-10400.0
(46)(4K)
0.188;-8168.7
4468
0.123;-12397.5
44(6J)
0.185;-10166.2
(47)(47)
0.230;-7807.5
4(47T)
0.184;-10166.2
4Q(47)
0.212;-9698.8
47(49)
0.176;-10400.0
447J
0.171;-11462.5
48(48)
0.174;-8870.0
(48)(4J)
0.213;-8168.7
4488
0.153;-10400.0
44(8J)
0.161;-9698.8
(49)(49)
0.212;-6872.5
4(49Q)
0.152;-9231.2
44(9T)
0.153;-9698.8
49(4K)
0.226;-8997.5
4(4TQ)
0.206;-8997.5
44(TJ)
0.191;-9231.2
(4J)(4J)
0.228;-5937.5
44JJ
0.210;-8997.5
4Q(4Q)
0.266;-7000.0
(4K)(4K)
0.286;-5002.5
(45)(57)
0.166;-9571.3
5(45T)
0.152;-10400.0
5Q(45)
0.201;-9932.5
8(456)
0.157;-12163.8
Q(456)
0.163;-11228.7
(45)(68)
0.171;-10633.8
6(45J)
0.207;-11462.5
6K(45)
0.131;-10995.0
(457J)
0.157;-11228.7
(45)(78)
0.192;-10400.0
7(45J)
0.149;-11228.7
7K(45)
0.169;-10761.2
(458Q)
0.155;-10761.2
8(45T)
0.174;-11228.7
8Q(45)
0.180;-10761.2
J(459)
0.161;-10761.2
9T(45)
0.208;-10995.0
(45)(9K)
0.198;-8763.8
K(45T)
0.176;-10060.0
T(45K)
0.162;-10060.0
JJ(45)
0.191;-8763.8
(45QK)
0.227;-9592.5
4555
0.202;-11568.8
45(58)
0.190;-10867.5
55(4J)
0.191;-10166.2
455K
0.169;-11228.7
58(46)
0.203;-12163.8
(46)(5J)
0.205;-9932.5
46(56)
0.136;-11101.2
4(569)
0.151;-11930.0
(56)(4Q)
0.223;-9698.8
46(57)
0.173;-12397.5
46(59)
0.127;-11930.0
46(5J)
0.170;-11462.5
46(5K)
0.145;-10995.0
5(479)
0.143;-11696.2
5J(47)
0.198;-11228.7
(57)(48)
0.152;-10400.0
4T(57)
0.157;-11462.5
4(57K)
0.150;-10761.2
47(59)
0.141;-11696.2
47(5J)
0.129;-11228.7
47(5K)
0.142;-10761.2
5(48T)
0.174;-11228.7
5Q(48)
0.181;-10761.2
(58)(4T)
0.213;-9698.8
4Q(58)
0.205;-10761.2
4589
0.173;-12992.5
458J
0.113;-12525.0
458K
0.146;-12057.5
5J(49)
0.196;-10761.2
(59)(4T)
0.177;-9465.0
4Q(59)
0.177;-10527.5
459T
0.201;-12525.0
459Q
0.198;-12057.5
(4T)(5J)
0.237;-8997.5
4T(5T)
0.179;-9231.2
4(5TK)
0.223;-10060.0
4T(5Q)
0.165;-10293.8
5J(4J)
0.218;-8763.8
(5J)(4Q)
0.258;-8530.0
4J(5Q)
0.216;-10060.0
5Q(4Q)
0.229;-8296.2
45QQ
0.164;-9826.2
45KK
0.169;-9358.8
6(469)
0.167;-10166.2
6J(46)
0.199;-9698.8
(4678)
0.148;-11696.2
(467Q)
0.162;-10761.2
7(469)
0.174;-11462.5
7J(46)
0.197;-10995.0
(4689)
0.137;-11228.7
(468K)
0.137;-10293.8
8T(46)
0.206;-10995.0
(46)(8K)
0.227;-8763.8
Q(469)
0.138;-10293.8
(46)(9J)
0.167;-8997.5
T(46T)
0.199;-8997.5
T(46J)
0.164;-10293.8
TK(46)
0.156;-9826.2
(46)(JQ)
0.177;-8296.2
QQ(46)
0.209;-8062.5
46(67)
0.185;-10633.8
66(4T)
0.198;-9932.5
466Q
0.170;-10995.0
68(47)
0.169;-11696.2
(47)(6J)
0.205;-9465.0
47(67)
0.174;-10400.0
4(67T)
0.187;-11228.7
(67)(4K)
0.193;-8997.5
67(49)
0.189;-11462.5
67(4J)
0.149;-10995.0
67(4K)
0.174;-10527.5
69(48)
0.161;-11228.7
(48)(6Q)
0.188;-8997.5
49(68)
0.138;-11228.7
4(68Q)
0.211;-10527.5
46(89)
0.133;-11228.7
46(8J)
0.227;-10761.2
46(8K)
0.184;-10293.8
(49)(6J)
0.194;-8997.5
49(69)
0.204;-9465.0
4(69Q)
0.178;-10293.8
46(9T)
0.154;-10761.2
46(9Q)
0.173;-10293.8
6(4TJ)
0.200;-10293.8
6K(4T)
0.199;-9826.2
(6T)(4K)
0.239;-8296.2
6T(4Q)
0.196;-10060.0
(4J)(6J)
0.195;-7000.0
4J(6J)
0.193;-8530.0
6J(4Q)
0.173;-9826.2
(4Q)(6Q)
0.272;-6532.5
4K(6Q)
0.183;-9358.8
4K(6K)
0.273;-7595.0
79(47)
0.158;-9698.8
(47)(7Q)
0.248;-7467.5
(478T)
0.199;-10761.2
88(47)
0.186;-9698.8
(47)(8J)
0.151;-8997.5
9(479)
0.204;-9231.2
K(479)
0.209;-9826.2
9(47Q)
0.206;-10060.0
J(47T)
0.166;-10060.0
TJ(47)
0.177;-10060.0
(47JQ)
0.199;-9592.5
J(47K)
0.256;-9358.8
(47)(QK)
0.294;-7595.0
77(49)
0.197;-9698.8
477J
0.169;-10761.2
78(48)
0.186;-9698.8
(48)(7J)
0.177;-8997.5
48(78)
0.169;-9698.8
4(78J)
0.187;-10527.5
4788
0.164;-11228.7
478T
0.125;-12291.2
478Q
0.167;-11823.8
(49)(7T)
0.160;-8997.5
7(49K)
0.225;-9826.2
4(79J)
0.170;-10293.8
4799
0.175;-10761.2
479J
0.194;-11823.8
479K
0.160;-11356.2
7Q(4T)
0.175;-9826.2
(7T)(4Q)
0.211;-8296.2
4T(7J)
0.229;-10060.0
4T(7K)
0.216;-9592.5
7(4JK)
0.188;-9358.8
4(7JK)
0.194;-9358.8
4J(7K)
0.240;-9358.8
4Q(7Q)
0.271;-7828.7
47QK
0.152;-10655.0
89(48)
0.230;-9231.2
(48)(8Q)
0.220;-7000.0
(489J)
0.159;-10060.0
(48)(9T)
0.194;-8763.8
9(48K)
0.169;-9592.5
(48TK)
0.196;-9358.8
TQ(48)
0.179;-9592.5
K(48J)
0.204;-9125.0
Q(48Q)
0.224;-7595.0
KK(48)
0.245;-7127.5
88(4J)
0.172;-8763.8
488K
0.205;-9826.2
8J(49)
0.158;-10060.0
(89)(4T)
0.187;-8763.8
4Q(89)
0.195;-9826.2
489T
0.196;-11823.8
489Q
0.180;-11356.2
(4T)(8J)
0.213;-8296.2
4T(8T)
0.202;-8530.0
4(8TK)
0.195;-9358.8
4T(8Q)
0.146;-9592.5
8J(4J)
0.207;-8062.5
(8J)(4Q)
0.265;-7828.8
4J(8Q)
0.194;-9358.8
8Q(4Q)
0.178;-7595.0
48QQ
0.200;-9125.0
48KK
0.231;-8657.5
9(49Q)
0.205;-8062.5
J(49T)
0.161;-9592.5
TJ(49)
0.192;-9592.5
(49JQ)
0.159;-9125.0
J(49K)
0.196;-8891.2
(49)(QK)
0.196;-7127.5
99(4J)
0.169;-8296.2
499K
0.217;-9358.8
9Q(4T)
0.150;-9358.8
(9T)(4Q)
0.228;-7828.8
4T(9J)
0.159;-9592.5
4T(9K)
0.170;-9125.0
9(4JK)
0.206;-8891.2
4(9JK)
0.153;-8891.2
4J(9K)
0.187;-8891.2
4Q(9Q)
0.225;-7361.2
49QK
0.180;-10187.5
TJ(4T)
0.205;-7828.7
(4TJQ)
0.237;-8891.2
J(4TK)
0.201;-8657.5
(4T)(QK)
0.263;-6893.7
TT(4Q)
0.232;-7595.0
T(4JQ)
0.219;-8891.2
4(TJQ)
0.153;-8891.2
4T(JQ)
0.208;-8891.2
T(4QK)
0.186;-8423.7
TQ(4K)
0.196;-8423.7
JJ(4J)
0.301;-5831.3
(4JQK)
0.204;-8190.0
4JJJ
0.259;-7361.2
JQ(4Q)
0.229;-6893.7
4JQQ
0.225;-8423.7
4JKK
0.198;-7956.2
QQ(4K)
0.226;-6426.2
4KKK
0.241;-5958.8
55(59)
0.198;-8870.0
55(5K)
0.180;-7935.0
(56)(58)
0.186;-8870.0
5(56J)
0.232;-9698.8
5K(56)
0.202;-9231.2
56(59)
0.146;-10166.2
556J
0.164;-11228.7
57(57)
0.167;-8870.0
(57)(5T)
0.187;-8168.7
5(57K)
0.251;-8997.5
55(79)
0.209;-9932.5
57(5Q)
0.170;-9231.2
5(589)
0.194;-9698.8
5J(58)
0.196;-9231.2
58(59)
0.178;-9698.8
558J
0.163;-10761.2
59(59)
0.204;-7935.0
(59)(5Q)
0.181;-7233.8
559T
0.147;-10761.2
55(9K)
0.190;-8530.0
(5T)(5Q)
0.211;-7000.0
55TJ
0.193;-10293.8
5J(5J)
0.289;-7000.0
5J(5Q)
0.222;-8296.2
5(5QK)
0.175;-7828.7
5K(5K)
0.240;-6065.0
68(56)
0.206;-10166.2
(56)(6J)
0.224;-7935.0
7(567)
0.195;-10166.2
J(567)
0.161;-10761.2
78(56)
0.188;-11462.5
(56)(7J)
0.159;-9231.2
8(568)
0.220;-9698.8
Q(568)
0.137;-10293.8
(56)(8T)
0.143;-9231.2
8(56K)
0.208;-10060.0
(569Q)
0.218;-10060.0
9(56J)
0.178;-10293.8
9K(56)
0.160;-9826.2
TT(56)
0.215;-8763.8
(56)(TK)
0.222;-8062.5
J(56Q)
0.146;-9592.5
K(56Q)
0.202;-9125.0
66(57)
0.221;-10400.0
5669
0.152;-11462.5
56(6Q)
0.186;-9231.2
(57)(68)
0.156;-9932.5
6(57J)
0.190;-10761.2
6K(57)
0.149;-10293.8
(67)(5T)
0.198;-9465.0
5Q(67)
0.191;-10527.5
5678
0.130;-12992.5
567T
0.158;-12525.0
567Q
0.149;-12057.5
(58)(69)
0.235;-9465.0
6(58Q)
0.159;-10293.8
5(689)
0.125;-10995.0
(68)(5Q)
0.239;-8763.8
58(69)
0.149;-10995.0
58(6J)
0.201;-10527.5
58(6K)
0.183;-10060.0
6(59J)
0.183;-10293.8
6K(59)
0.171;-9826.2
(69)(5Q)
0.167;-8530.0
59(6T)
0.203;-10527.5
59(6Q)
0.164;-10060.0
6T(5T)
0.197;-8763.8
(5T)(6K)
0.223;-8062.5
5Q(6T)
0.200;-9826.2
56TJ
0.204;-11590.0
56TK
0.130;-11122.5
6K(5J)
0.209;-9358.8
56JJ
0.238;-9826.2
56JK
0.190;-10888.8
5(6QK)
0.262;-9125.0
6K(5K)
0.248;-7361.2
(57)(79)
0.197;-7935.0
7(57Q)
0.232;-8763.8
9(578)
0.186;-10761.2
K(578)
0.219;-9826.2
8(57J)
0.204;-10293.8
8K(57)
0.167;-9826.2
(579K)
0.161;-9592.5
9J(57)
0.216;-10060.0
(57TJ)
0.148;-9826.2
(57)(TJ)
0.187;-8296.2
J(57J)
0.180;-8062.5
JQ(57)
0.192;-9358.8
Q(57K)
0.201;-8891.2
5778
0.206;-11228.7
57(7J)
0.214;-8997.5
(58)(78)
0.174;-7935.0
7(58J)
0.205;-10293.8
7K(58)
0.219;-9826.2
(78)(5J)
0.201;-8763.8
5K(78)
0.175;-9826.2
57(8T)
0.184;-10527.5
57(8Q)
0.179;-10060.0
7(59T)
0.177;-10293.8
7Q(59)
0.171;-9826.2
(79)(5J)
0.213;-8530.0
5K(79)
0.182;-9592.5
57(9J)
0.183;-10060.0
57(9K)
0.191;-9592.5
(5T)(7Q)
0.194;-8062.5
5J(7T)
0.180;-9826.2
7T(5J)
0.206;-9826.2
7T(5K)
0.163;-9358.8
7Q(5J)
0.238;-9358.8
(7J)(5K)
0.162;-7595.0
7J(5K)
0.236;-9125.0
7K(5Q)
0.229;-8891.2
57(QK)
0.192;-8891.2
(58)(89)
0.193;-7467.5
8(58Q)
0.206;-8296.2
T(589)
0.165;-10060.0
9(58T)
0.180;-10060.0
9Q(58)
0.225;-9592.5
Q(58T)
0.217;-9358.8
(58)(TQ)
0.230;-7828.8
(58JK)
0.175;-8891.2
JK(58)
0.175;-8891.2
K(58K)
0.229;-6893.7
588T
0.177;-10293.8
58(8K)
0.198;-8062.5
(59)(8J)
0.195;-8296.2
59(89)
0.171;-8763.8
5(89Q)
0.206;-9592.5
58(9T)
0.184;-10060.0
58(9Q)
0.182;-9592.5
8(5TJ)
0.171;-9592.5
8K(5T)
0.218;-9125.0
(8T)(5K)
0.213;-7595.0
8T(5Q)
0.228;-9358.8
(5J)(8J)
0.223;-6298.7
5J(8J)
0.258;-7828.7
8J(5Q)
0.217;-9125.0
(5Q)(8Q)
0.252;-5831.3
5K(8Q)
0.186;-8657.5
5K(8K)
0.272;-6893.7
9J(59)
0.187;-8062.5
(59TJ)
0.253;-9358.8
(59)(TJ)
0.285;-7828.8
J(59J)
0.227;-7595.0
JQ(59)
0.154;-8891.2
Q(59K)
0.208;-8423.7
599T
0.180;-9826.2
59(9K)
0.234;-7595.0
(5T)(9Q)
0.175;-7595.0
5J(9T)
0.200;-9358.8
9T(5J)
0.212;-9358.8
9T(5K)
0.228;-8891.2
9Q(5J)
0.166;-8891.2
(9J)(5K)
0.236;-7127.5
9J(5K)
0.196;-8657.5
9K(5Q)
0.197;-8423.7
59(QK)
0.213;-8423.7
(5T)(TJ)
0.216;-6065.0
J(5TJ)
0.192;-7361.2
JQ(5T)
0.241;-8657.5
Q(5TK)
0.193;-8190.0
5TTJ
0.201;-9125.0
TJ(5J)
0.234;-7361.2
(TJ)(5Q)
0.212;-7127.5
5J(TQ)
0.215;-8657.5
TQ(5Q)
0.241;-6893.7
5TQQ
0.233;-8423.7
5TKK
0.195;-7956.2
Q(5JQ)
0.227;-6660.0
KK(5J)
0.252;-6192.5
(5Q)(JQ)
0.261;-5130.0
5K(JQ)
0.233;-7956.2
5K(JK)
0.253;-6192.5
5QQQ
0.251;-6426.2
KK(5K)
0.268;-4195.0
6669
0.163;-9698.8
666K
0.208;-8763.8
69(67)
0.208;-9465.0
(67)(6Q)
0.204;-7233.8
6678
0.172;-11228.7
66(7J)
0.179;-8997.5
(68)(68)
0.260;-6405.0
6(68J)
0.171;-8763.8
6K(68)
0.241;-8296.2
68(6J)
0.215;-8763.8
668K
0.162;-9826.2
6J(69)
0.175;-8530.0
69(6T)
0.157;-8763.8
669Q
0.161;-9826.2
6J(6T)
0.260;-8296.2
6T(6J)
0.228;-8296.2
66TK
0.207;-9358.8
6K(6J)
0.199;-7595.0
(6Q)(6Q)
0.273;-4535.0
66QK
0.226;-8891.2
7(679)
0.191;-9231.2
7J(67)
0.168;-8763.8
(6789)
0.147;-10527.5
(678K)
0.197;-9592.5
8T(67)
0.208;-10293.8
(67)(8K)
0.227;-8062.5
Q(679)
0.222;-9592.5
(67)(9J)
0.213;-8296.2
T(67T)
0.174;-8296.2
T(67J)
0.161;-9592.5
TK(67)
0.209;-9125.0
(67)(JQ)
0.182;-7595.0
QQ(67)
0.206;-7361.2
67(78)
0.192;-9465.0
77(6J)
0.223;-8763.8
677K
0.218;-9826.2
7T(68)
0.165;-10293.8
(68)(7K)
0.228;-8062.5
6T(78)
0.197;-10293.8
6(78K)
0.188;-9592.5
68(7T)
0.146;-10293.8
68(7Q)
0.140;-9826.2
79(69)
0.203;-8763.8
(69)(7Q)
0.218;-8062.5
6T(79)
0.196;-10060.0
6(79K)
0.204;-9358.8
69(7J)
0.155;-9826.2
69(7K)
0.212;-9358.8
7(6TQ)
0.143;-9358.8
6(7TJ)
0.227;-9592.5
67TT
0.190;-9826.2
67TQ
0.175;-10888.8
(6J)(7Q)
0.222;-7595.0
6Q(7J)
0.180;-9125.0
67JQ
0.144;-10655.0
(6Q)(7K)
0.199;-7127.5
6Q(7K)
0.218;-8657.5
8(689)
0.219;-8763.8
8J(68)
0.214;-8296.2
(689T)
0.198;-9826.2
99(68)
0.171;-8530.0
(68)(9Q)
0.243;-7828.8
(68TQ)
0.167;-9125.0
T(68Q)
0.167;-9125.0
Q(68J)
0.183;-8891.2
(68)(JK)
0.236;-7127.5
QK(68)
0.177;-8423.7
68(8T)
0.198;-8530.0
88(6K)
0.224;-7828.7
8(69J)
0.187;-9592.5
8K(69)
0.145;-9125.0
(89)(6Q)
0.214;-7828.8
69(8T)
0.212;-9826.2
69(8Q)
0.198;-9358.8
8T(6T)
0.186;-8062.5
(6T)(8K)
0.233;-7361.2
6Q(8T)
0.189;-9125.0
68TJ
0.167;-10888.8
68TK
0.176;-10421.2
8K(6J)
0.212;-8657.5
68JJ
0.174;-9125.0
68JK
0.155;-10187.5
6(8QK)
0.163;-8423.7
8K(6K)
0.214;-6660.0
(69)(9J)
0.218;-6298.7
T(69T)
0.208;-7828.7
T(69J)
0.212;-9125.0
TK(69)
0.209;-8657.5
(69)(JQ)
0.224;-7127.5
QQ(69)
0.253;-6893.7
69(9T)
0.256;-8062.5
99(6K)
0.202;-7361.2
9(6TQ)
0.188;-8891.2
6(9TJ)
0.183;-9125.0
69TT
0.205;-9358.8
69TQ
0.175;-10421.2
(6J)(9Q)
0.272;-7127.5
6Q(9J)
0.163;-8657.5
69JQ
0.159;-10187.5
(6Q)(9K)
0.235;-6660.0
6Q(9K)
0.204;-8190.0
T(6TJ)
0.196;-7361.2
TK(6T)
0.177;-6893.7
(6T)(JQ)
0.235;-6893.7
QQ(6T)
0.241;-6660.0
6T(TJ)
0.206;-7361.2
(6J)(TJ)
0.256;-5597.5
6J(TJ)
0.234;-7127.5
TJ(6Q)
0.211;-8423.7
(6Q)(TQ)
0.249;-5130.0
6K(TQ)
0.191;-7956.2
6K(TK)
0.217;-6192.5
JK(6J)
0.274;-6426.2
K(6JK)
0.262;-5958.8
6JJK
0.220;-7956.2
6(JQK)
0.214;-7722.5
JK(6K)
0.266;-5958.8
KK(6Q)
0.276;-5725.0
6QKK
0.186;-7255.0
77(7T)
0.180;-7233.7
(78)(78)
0.228;-5937.5
7(78J)
0.259;-8296.2
7K(78)
0.189;-7828.7
78(7J)
0.215;-8296.2
778K
0.201;-9358.8
7J(79)
0.219;-8062.5
79(7T)
0.187;-8296.2
779Q
0.170;-9358.8
7J(7T)
0.228;-7828.7
7T(7J)
0.273;-7828.7
77TK
0.246;-8891.2
7K(7J)
0.177;-7127.5
(7Q)(7Q)
0.305;-4067.5
77QK
0.194;-8423.7
8(78T)
0.219;-8296.2
8Q(78)
0.249;-7828.7
J(789)
0.186;-9358.8
9T(78)
0.204;-9592.5
(78)(9K)
0.191;-7361.2
K(78T)
0.210;-8657.5
T(78K)
0.179;-8657.5
JJ(78)
0.265;-7361.2
(78QK)
0.205;-8190.0
7888
0.188;-8763.8
78(8J)
0.181;-8062.5
(79)(89)
0.283;-6766.2
8(79Q)
0.190;-9125.0
7(89T)
0.158;-9592.5
(89)(7K)
0.266;-7361.2
89(7J)
0.182;-9358.8
89(7K)
0.189;-8891.2
8J(7T)
0.153;-9125.0
(8T)(7J)
0.193;-7595.0
7K(8T)
0.189;-8657.5
78(TQ)
0.221;-8891.2
8(7JQ)
0.234;-8657.5
7(8JQ)
0.169;-8657.5
78(JQ)
0.212;-8657.5
8(7QK)
0.211;-8190.0
8Q(7K)
0.193;-8190.0
99(79)
0.208;-6532.5
(79)(9Q)
0.232;-5831.3
(79TQ)
0.214;-8657.5
T(79Q)
0.180;-8657.5
Q(79J)
0.180;-8423.7
(79)(JK)
0.269;-6660.0
QK(79)
0.198;-7956.2
79(9J)
0.205;-7595.0
(7T)(9T)
0.259;-6065.0
9(7TK)
0.204;-8423.7
7(9TQ)
0.168;-8657.5
79(TJ)
0.170;-8891.2
79(TK)
0.190;-8423.7
(7J)(9K)
0.256;-6660.0
7K(9J)
0.211;-8190.0
79(JK)
0.254;-8190.0
(9Q)(7K)
0.264;-6426.2
(7K)(9K)
0.237;-4662.5
T(7TQ)
0.268;-6893.7
Q(7TJ)
0.218;-8190.0
(7T)(JK)
0.215;-6426.2
QK(7T)
0.252;-7722.5
7T(TQ)
0.233;-6893.7
(7J)(TQ)
0.203;-6660.0
7Q(TJ)
0.240;-8190.0
7TJQ
0.195;-9720.0
(7Q)(TK)
0.190;-6192.5
7Q(TK)
0.215;-7722.5
J(7JQ)
0.231;-6426.2
K(7JQ)
0.194;-7488.8
JJ(7Q)
0.273;-6426.2
J(7QK)
0.203;-7488.8
JQ(7K)
0.250;-7488.8
QQ(7Q)
0.309;-4428.8
7Q(QK)
0.261;-5725.0
8888
0.207;-7000.0
888Q
0.227;-7595.0
8(89J)
0.179;-7595.0
8K(89)
0.239;-7127.5
89(8Q)
0.239;-7361.2
8(8TJ)
0.238;-7361.2
8K(8T)
0.228;-6893.7
8T(8K)
0.215;-6893.7
8(8JK)
0.299;-6660.0
88(JK)
0.266;-6660.0
8Q(8K)
0.246;-6426.2
(89)(9T)
0.203;-6065.0
9(89K)
0.225;-6893.7
(89TK)
0.209;-8190.0
TQ(89)
0.212;-8423.7
K(89J)
0.220;-7956.2
Q(89Q)
0.217;-6426.2
KK(89)
0.237;-5958.8
99(8Q)
0.236;-7127.5
9(8TJ)
0.179;-8657.5
9K(8T)
0.165;-8190.0
(9T)(8K)
0.246;-6660.0
9T(8Q)
0.200;-8423.7
(8J)(9J)
0.194;-5363.7
8J(9J)
0.212;-6893.7
9J(8Q)
0.188;-8190.0
(8Q)(9Q)
0.238;-4896.2
8K(9Q)
0.229;-7722.5
8K(9K)
0.203;-5958.8
TQ(8T)
0.184;-6660.0
K(8TJ)
0.198;-7722.5
Q(8TQ)
0.239;-6192.5
KK(8T)
0.297;-5725.0
