AAAA
0.103;-3560.0
5AAA
0.053;-18950.0
9AAA
0.060;-14990.0
KAAA
0.067;-11030.0
4A(2A)
0.029;-31820.0
(2A)(7A)
0.049;-22370.0
A(2TA)
0.044;-25880.0
QA(2A)
0.043;-23900.0
2A(4A)
0.028;-31820.0
26AA
0.023;-36320.0
AA(29)
0.033;-26870.0
2A(QA)
0.041;-23900.0
A(34A)
0.034;-30830.0
6A(3A)
0.033;-28850.0
(3A)(9A)
0.067;-19400.0
A(3QA)
0.039;-22910.0
AA(34)
0.027;-30830.0
3A(7A)
0.035;-27860.0
39AA
0.024;-32360.0
AA(3Q)
0.041;-22910.0
(4A)(5A)
0.057;-22370.0
A(48A)
0.029;-25880.0
TA(4A)
0.047;-23900.0
(4A)(KA)
0.083;-14450.0
46AA
0.027;-34340.0
AA(49)
0.042;-24890.0
4A(QA)
0.041;-21920.0
A(56A)
0.032;-26870.0
8A(5A)
0.041;-24890.0
(5A)(JA)
0.066;-15440.0
55AA
0.041;-27860.0
AA(58)
0.040;-24890.0
5A(JA)
0.059;-21920.0
5KAA
0.036;-26420.0
8A(6A)
0.033;-23900.0
(6A)(JA)
0.067;-14450.0
66AA
0.037;-25880.0
AA(69)
0.049;-22910.0
6A(QA)
0.061;-19940.0
A(78A)
0.035;-22910.0
TA(7A)
0.041;-20930.0
(7A)(KA)
0.096;-11480.0
79AA
0.032;-28400.0
AA(7Q)
0.061;-18950.0
(8A)(9A)
0.067;-14450.0
A(8QA)
0.066;-17960.0
AA(89)
0.054;-20930.0
8A(QA)
0.065;-17960.0
A(9TA)
0.068;-18950.0
QA(9A)
0.052;-16970.0
9A(JA)
0.057;-17960.0
9KAA
0.050;-22460.0
QA(TA)
0.080;-15980.0
TA(QA)
0.064;-15980.0
A(JQA)
0.054;-14990.0
AA(JQ)
0.058;-14990.0
(QA)(KA)
0.092;-6530.0
KKAA
0.066;-12020.0
2(25A)
0.011;-42710.0
27(2A)
0.017;-40730.0
(2T)(2A)
0.031;-31280.0
2(2KA)
0.019;-34790.0
(236A)
0.009;-47210.0
(23TA)
0.011;-43250.0
33(2A)
0.010;-43700.0
(36)(2A)
0.014;-40730.0
3(29A)
0.011;-44240.0
3J(2A)
0.017;-42260.0
(245A)
0.010;-47210.0
(249A)
0.013;-43250.0
(24KA)
0.020;-39290.0
46(2A)
0.009;-46220.0
(49)(2A)
0.022;-36770.0
4(2QA)
0.012;-40280.0
6(25A)
0.012;-45230.0
T(25A)
0.015;-41270.0
5(26A)
0.009;-45230.0
58(2A)
0.016;-43250.0
(5J)(2A)
0.020;-33800.0
6(26A)
0.018;-37760.0
T(26A)
0.015;-40280.0
6(27A)
0.014;-43250.0
69(2A)
0.015;-41270.0
(6Q)(2A)
0.028;-31820.0
(279A)
0.016;-40280.0
(27KA)
0.016;-36320.0
79(2A)
0.014;-40280.0
(7Q)(2A)
0.032;-30830.0
(28TA)
0.023;-38300.0
88(2A)
0.030;-33800.0
(8J)(2A)
0.027;-30830.0
9(29A)
0.032;-31820.0
K(29A)
0.022;-34340.0
9(2QA)
0.026;-35330.0
J(2TA)
0.021;-35330.0
TJ(2A)
0.022;-35330.0
(2JQA)
0.028;-33350.0
J(2KA)
0.030;-32360.0
(QK)(2A)
0.045;-24890.0
22(4A)
0.012;-43700.0
226A
0.010;-48200.0
2A(29)
0.018;-38750.0
22(QA)
0.023;-35780.0
2(34A)
0.009;-49190.0
26(3A)
0.007;-47210.0
(29)(3A)
0.019;-37760.0
2(3QA)
0.013;-41270.0
A(234)
0.006;-49190.0
(23)(7A)
0.016;-39740.0
9A(23)
0.012;-44240.0
A(23Q)
0.018;-41270.0
2A(34)
0.009;-49190.0
2A(36)
0.007;-47210.0
2A(38)
0.010;-45230.0
2A(3T)
0.011;-43250.0
2A(3Q)
0.018;-41270.0
2(45A)
0.008;-47210.0
27(4A)
0.011;-45230.0
(2T)(4A)
0.022;-35780.0
2(4KA)
0.017;-39290.0
A(246)
0.010;-46220.0
(24)(9A)
0.026;-36770.0
JA(24)
0.017;-41270.0
24(5A)
0.009;-47210.0
24(7A)
0.009;-45230.0
24(9A)
0.011;-43250.0
24(JA)
0.016;-41270.0
24(KA)
0.017;-39290.0
26(5A)
0.012;-45230.0
(29)(5A)
0.020;-35780.0
2(5QA)
0.013;-39290.0
A(256)
0.010;-45230.0
(25)(9A)
0.024;-35780.0
JA(25)
0.017;-40280.0
25(6A)
0.011;-45230.0
25(8A)
0.017;-43250.0
25(TA)
0.015;-41270.0
25(QA)
0.017;-39290.0
(26)(6A)
0.026;-31280.0
2(69A)
0.018;-41270.0
2J(6A)
0.012;-39290.0
(26)(7A)
0.024;-36770.0
9A(26)
0.010;-41270.0
A(26Q)
0.024;-38300.0
2A(67)
0.011;-43250.0
2A(69)
0.014;-41270.0
2A(6J)
0.016;-39290.0
2A(6K)
0.018;-37310.0
(29)(7A)
0.027;-33800.0
2(7QA)
0.022;-37310.0
A(278)
0.014;-41270.0
(27)(JA)
0.037;-31820.0
KA(27)
0.025;-36320.0
2A(79)
0.015;-40280.0
2A(7J)
0.017;-38300.0
2A(7K)
0.015;-36320.0
(2T)(8A)
0.033;-31820.0
2(8KA)
0.021;-35330.0
A(28T)
0.021;-38300.0
(28)(KA)
0.034;-28850.0
28(TA)
0.019;-38300.0
28(QA)
0.017;-36320.0
(29)(9A)
0.043;-25340.0
2(9QA)
0.023;-35330.0
A(29T)
0.023;-37310.0
(29)(KA)
0.037;-27860.0
29(JA)
0.023;-36320.0
29(KA)
0.028;-34340.0
2J(TA)
0.020;-35330.0
(2T)(JA)
0.029;-28850.0
KA(2T)
0.031;-33350.0
2A(TQ)
0.025;-34340.0
2(JQA)
0.031;-33350.0
A(2JQ)
0.024;-33350.0
2A(JQ)
0.031;-33350.0
2(QKA)
0.028;-31370.0
2Q(KA)
0.025;-31370.0
33(3A)
0.021;-36230.0
(36)(3A)
0.027;-33260.0
3(39A)
0.018;-36770.0
3J(3A)
0.023;-34790.0
(345A)
0.011;-46220.0
(349A)
0.016;-42260.0
(34KA)
0.019;-38300.0
46(3A)
0.010;-45230.0
(49)(3A)
0.023;-35780.0
4(3QA)
0.020;-39290.0
6(35A)
0.011;-44240.0
T(35A)
0.016;-40280.0
5(36A)
0.015;-44240.0
58(3A)
0.015;-42260.0
(5J)(3A)
0.022;-32810.0
6(36A)
0.021;-36770.0
T(36A)
0.017;-39290.0
6(37A)
0.011;-42260.0
69(3A)
0.014;-40280.0
(6Q)(3A)
0.028;-30830.0
(379A)
0.023;-39290.0
(37KA)
0.021;-35330.0
79(3A)
0.020;-39290.0
(7Q)(3A)
0.041;-29840.0
(38TA)
0.021;-37310.0
88(3A)
0.030;-32810.0
(8J)(3A)
0.030;-29840.0
9(39A)
0.028;-30830.0
K(39A)
0.028;-33350.0
9(3QA)
0.021;-34340.0
J(3TA)
0.027;-34340.0
TJ(3A)
0.029;-34340.0
(3JQA)
0.024;-32360.0
J(3KA)
0.031;-31370.0
(QK)(3A)
0.046;-23900.0
33(5A)
0.017;-40730.0
337A
0.011;-45230.0
3A(3T)
0.020;-35780.0
33(KA)
0.023;-32810.0
3(46A)
0.010;-45230.0
38(4A)
0.016;-43250.0
(3J)(4A)
0.020;-33800.0
4A(34)
0.015;-40730.0
A(347)
0.014;-44240.0
(34)(TA)
0.021;-34790.0
QA(34)
0.021;-39290.0
345A
0.005;-52700.0
347A
0.005;-50720.0
349A
0.008;-48740.0
34JA
0.009;-46760.0
34KA
0.011;-44780.0
37(5A)
0.011;-43250.0
(3T)(5A)
0.020;-33800.0
3(5KA)
0.018;-37310.0
A(357)
0.013;-43250.0
(35)(TA)
0.035;-33800.0
QA(35)
0.015;-38300.0
356A
0.006;-50720.0
358A
0.006;-48740.0
35TA
0.010;-46760.0
35QA
0.009;-44780.0
(37)(6A)
0.023;-35780.0
3(6TA)
0.018;-39290.0
3Q(6A)
0.016;-37310.0
(36)(8A)
0.022;-34790.0
TA(36)
0.017;-39290.0
A(36K)
0.020;-36320.0
6A(38)
0.018;-41270.0
6A(3T)
0.014;-39290.0
6A(3Q)
0.022;-37310.0
37(7A)
0.019;-34790.0
(3T)(7A)
0.031;-31820.0
3(7KA)
0.020;-35330.0
A(379)
0.017;-39290.0
(37)(QA)
0.024;-29840.0
7A(38)
0.015;-40280.0
7A(3T)
0.021;-38300.0
7A(3Q)
0.020;-36320.0
38(8A)
0.026;-32810.0
(3J)(8A)
0.024;-29840.0
8A(38)
0.020;-32810.0
A(38J)
0.016;-36320.0
388A
0.015;-39290.0
38TA
0.010;-43790.0
38QA
0.011;-41810.0
(3T)(9A)
0.024;-29840.0
3(9KA)
0.035;-33350.0
A(39J)
0.025;-35330.0
399A
0.022;-37310.0
39JA
0.013;-41810.0
39KA
0.020;-39830.0
3Q(TA)
0.026;-33350.0
(3T)(QA)
0.038;-26870.0
TA(3J)
0.022;-34340.0
TA(3K)
0.025;-32360.0
3(JKA)
0.030;-31370.0
A(3JK)
0.029;-31370.0
JA(3K)
0.023;-31370.0
QA(3Q)
0.054;-24890.0
3QKA
0.026;-36860.0
45(4A)
0.016;-38750.0
(48)(4A)
0.022;-29300.0
4(4JA)
0.029;-32810.0
4K(4A)
0.026;-30830.0
(459A)
0.018;-40280.0
(45KA)
0.019;-36320.0
57(4A)
0.012;-42260.0
(5T)(4A)
0.028;-32810.0
5(4KA)
0.024;-36320.0
(469A)
0.014;-39290.0
(46KA)
0.018;-35330.0
68(4A)
0.011;-40280.0
(6J)(4A)
0.027;-30830.0
7(47A)
0.030;-33800.0
J(47A)
0.027;-36320.0
78(4A)
0.021;-39290.0
(7J)(4A)
0.028;-29840.0
8(48A)
0.031;-31820.0
Q(48A)
0.019;-34340.0
(8T)(4A)
0.030;-29840.0
8(4KA)
0.024;-33350.0
(49QA)
0.023;-33350.0
9(4JA)
0.023;-34340.0
9K(4A)
0.032;-32360.0
TT(4A)
0.037;-27860.0
(TK)(4A)
0.053;-24890.0
J(4QA)
0.029;-31370.0
K(4QA)
0.035;-29390.0
44(5A)
0.018;-38750.0
447A
0.011;-43250.0
4A(4T)
0.022;-33800.0
44(KA)
0.029;-30830.0
4(57A)
0.014;-42260.0
49(5A)
0.014;-40280.0
(4Q)(5A)
0.029;-30830.0
6A(45)
0.016;-43250.0
A(459)
0.020;-40280.0
(45)(QA)
0.029;-30830.0
5A(46)
0.012;-43250.0
5A(48)
0.014;-41270.0
5A(4T)
0.013;-39290.0
5A(4Q)
0.021;-37310.0
46(6A)
0.022;-35780.0
(49)(6A)
0.027;-32810.0
4(6QA)
0.017;-36320.0
A(467)
0.017;-41270.0
(46)(TA)
0.026;-31820.0
QA(46)
0.025;-36320.0
467A
0.010;-47750.0
469A
0.011;-45770.0
46JA
0.011;-43790.0
46KA
0.015;-41810.0
49(7A)
0.021;-38300.0
(4Q)(7A)
0.033;-28850.0
8A(47)
0.019;-39290.0
A(47J)
0.017;-36320.0
477A
0.016;-40280.0
479A
0.012;-44780.0
47JA
0.014;-42800.0
47KA
0.012;-40820.0
4T(8A)
0.023;-36320.0
(4K)(8A)
0.038;-26870.0
TA(48)
0.016;-36320.0
A(48K)
0.021;-33350.0
8A(4T)
0.023;-36320.0
8A(4Q)
0.017;-34340.0
49(9A)
0.033;-29840.0
(4Q)(9A)
0.042;-26870.0
TA(49)
0.019;-35330.0
A(49K)
0.023;-32360.0
9A(4J)
0.022;-34340.0
9A(4K)
0.028;-32360.0
4(TQA)
0.033;-32360.0
A(4TJ)
0.027;-33350.0
4TTA
0.020;-34340.0
4TQA
0.020;-38840.0
(4Q)(JA)
0.046;-24890.0
QA(4J)
0.036;-31370.0
4JQA
0.020;-37850.0
(4K)(QA)
0.046;-22910.0
QA(4K)
0.033;-29390.0
5(56A)
0.019;-35780.0
58(5A)
0.022;-33800.0
(5J)(5A)
0.043;-24350.0
6(56A)
0.020;-34790.0
T(56A)
0.015;-37310.0
6(57A)
0.015;-40280.0
69(5A)
0.018;-38300.0
(6Q)(5A)
0.026;-28850.0
(579A)
0.019;-37310.0
(57KA)
0.034;-33350.0
79(5A)
0.023;-37310.0
(7Q)(5A)
0.036;-27860.0
(58TA)
0.022;-35330.0
88(5A)
0.023;-30830.0
(8J)(5A)
0.039;-27860.0
9(59A)
0.028;-28850.0
K(59A)
0.022;-31370.0
9(5QA)
0.024;-32360.0
J(5TA)
0.032;-32360.0
TJ(5A)
0.019;-32360.0
(5JQA)
0.033;-30380.0
J(5KA)
0.029;-29390.0
(QK)(5A)
0.046;-21920.0
55(7A)
0.028;-34790.0
559A
0.014;-39290.0
5A(5Q)
0.039;-29840.0
(57)(6A)
0.023;-33800.0
5(6TA)
0.022;-37310.0
5Q(6A)
0.023;-35330.0
(56)(8A)
0.026;-32810.0
TA(56)
0.025;-37310.0
A(56K)
0.024;-34340.0
6A(58)
0.020;-39290.0
6A(5T)
0.020;-37310.0
6A(5Q)
0.026;-35330.0
57(7A)
0.025;-32810.0
(5T)(7A)
0.033;-29840.0
5(7KA)
0.026;-33350.0
A(579)
0.017;-37310.0
(57)(QA)
0.038;-27860.0
7A(58)
0.022;-38300.0
7A(5T)
0.022;-36320.0
7A(5Q)
0.018;-34340.0
58(8A)
0.027;-30830.0
(5J)(8A)
0.031;-27860.0
8A(58)
0.021;-30830.0
A(58J)
0.021;-34340.0
588A
0.024;-37310.0
58TA
0.010;-41810.0
58QA
0.017;-39830.0
(5T)(9A)
0.037;-27860.0
5(9KA)
0.028;-31370.0
A(59J)
0.031;-33350.0
599A
0.022;-35330.0
59JA
0.021;-39830.0
59KA
0.016;-37850.0
5Q(TA)
0.023;-31370.0
(5T)(QA)
0.034;-24890.0
TA(5J)
0.034;-32360.0
TA(5K)
0.041;-30380.0
5(JKA)
0.026;-29390.0
A(5JK)
0.028;-29390.0
JA(5K)
0.029;-29390.0
QA(5Q)
0.053;-22910.0
5QKA
0.024;-34880.0
67(6A)
0.022;-32810.0
(6T)(6A)
0.050;-23360.0
6(6KA)
0.041;-26870.0
(67TA)
0.024;-35330.0
77(6A)
0.022;-31820.0
(7T)(6A)
0.029;-28850.0
7(6KA)
0.025;-32360.0
(68JA)
0.028;-33350.0
(89)(6A)
0.030;-28850.0
8(6QA)
0.030;-32360.0
T(69A)
0.023;-33350.0
9(6TA)
0.020;-33350.0
9Q(6A)
0.030;-31370.0
Q(6TA)
0.026;-30380.0
(TQ)(6A)
0.049;-23900.0
(6JKA)
0.033;-28400.0
JK(6A)
0.035;-28400.0
K(6KA)
0.055;-19940.0
668A
0.018;-38300.0
6A(6J)
0.032;-28850.0
(67)(7A)
0.043;-25340.0
6(7TA)
0.020;-35330.0
6Q(7A)
0.019;-33350.0
(67)(9A)
0.024;-29840.0
JA(67)
0.026;-34340.0
67(8A)
0.018;-37310.0
67(TA)
0.020;-35330.0
67(QA)
0.032;-33350.0
(68)(8A)
0.049;-23360.0
6(8JA)
0.024;-33350.0
6K(8A)
0.034;-31370.0
(68)(JA)
0.048;-26870.0
KA(68)
0.032;-31370.0
6A(8T)
0.025;-34340.0
6A(8Q)
0.029;-32360.0
6(9TA)
0.026;-33350.0
6Q(9A)
0.026;-31370.0
(69)(JA)
0.038;-25880.0
KA(69)
0.027;-30380.0
6A(9J)
0.027;-32360.0
6A(9K)
0.033;-30380.0
(6Q)(TA)
0.038;-23900.0
JA(6T)
0.034;-31370.0
6T(JA)
0.033;-31370.0
6T(KA)
0.032;-29390.0
6Q(JA)
0.033;-29390.0
(6J)(KA)
0.054;-21920.0
6J(KA)
0.027;-28400.0
6K(QA)
0.037;-27410.0
6A(QK)
0.037;-27410.0
(78)(7A)
0.036;-23360.0
7(7JA)
0.034;-26870.0
7K(7A)
0.045;-24890.0
(78QA)
0.021;-31370.0
8(7TA)
0.025;-33350.0
8Q(7A)
0.027;-31370.0
J(79A)
0.035;-31370.0
9T(7A)
0.027;-32360.0
(9K)(7A)
0.047;-22910.0
K(7TA)
0.032;-28400.0
T(7KA)
0.041;-28400.0
JJ(7A)
0.054;-22910.0
(7QKA)
0.032;-26420.0
777A
0.027;-30830.0
7A(7T)
0.038;-27860.0
77(KA)
0.038;-24890.0
7(8TA)
0.026;-33350.0
7Q(8A)
0.026;-31370.0
(78)(TA)
0.048;-26870.0
QA(78)
0.026;-31370.0
789A
0.012;-40820.0
78JA
0.018;-38840.0
78KA
0.016;-36860.0
7J(9A)
0.022;-31370.0
(79)(TA)
0.036;-25880.0
QA(79)
0.026;-30380.0
79TA
0.015;-38840.0
79QA
0.015;-36860.0
(7J)(TA)
0.051;-23900.0
TA(7T)
0.040;-24890.0
A(7TK)
0.038;-28400.0
TA(7Q)
0.030;-29390.0
7J(JA)
0.040;-22910.0
(7J)(QA)
0.040;-21920.0
JA(7Q)
0.024;-28400.0
7Q(QA)
0.048;-20930.0
7QQA
0.031;-27410.0
7KKA
0.040;-25430.0
8(8JA)
0.034;-24890.0
8K(8A)
0.049;-22910.0
(89KA)
0.031;-28400.0
9J(8A)
0.042;-30380.0
(8TJA)
0.039;-29390.0
(TJ)(8A)
0.061;-22910.0
J(8JA)
0.061;-21920.0
JQ(8A)
0.039;-27410.0
Q(8KA)
0.032;-25430.0
889A
0.023;-33350.0
8A(8Q)
0.061;-23900.0
(8T)(9A)
0.045;-24890.0
8(9KA)
0.042;-28400.0
A(89J)
0.025;-30380.0
899A
0.025;-32360.0
89JA
0.025;-36860.0
89KA
0.021;-34880.0
8Q(TA)
0.035;-28400.0
(8T)(QA)
0.042;-21920.0
TA(8J)
0.038;-29390.0
TA(8K)
0.032;-27410.0
8(JKA)
0.044;-26420.0
A(8JK)
0.043;-26420.0
JA(8K)
0.037;-26420.0
QA(8Q)
0.059;-19940.0
8QKA
0.023;-31910.0
9T(9A)
0.046;-23900.0
(9K)(9A)
0.079;-14450.0
K(9TA)
0.035;-26420.0
T(9KA)
0.045;-26420.0
JJ(9A)
0.063;-20930.0
(9QKA)
0.034;-24440.0
999A
0.047;-24890.0
9A(9Q)
0.044;-21920.0
(9J)(TA)
0.061;-21920.0
TA(9T)
0.049;-22910.0
A(9TK)
0.047;-26420.0
TA(9Q)
0.045;-27410.0
9J(JA)
0.051;-20930.0
(9J)(QA)
0.055;-19940.0
JA(9Q)
0.031;-26420.0
9Q(QA)
0.045;-18950.0
9QQA
0.034;-25430.0
9KKA
0.038;-23450.0
T(TKA)
0.062;-18950.0
JJ(TA)
0.041;-19940.0
(TQKA)
0.043;-23450.0
TTTA
0.051;-21920.0
TA(TK)
0.055;-18950.0
(TK)(JA)
0.056;-17960.0
KA(TJ)
0.054;-24440.0
TA(JK)
0.046;-24440.0
(TQ)(KA)
0.060;-16970.0
(TK)(KA)
0.068;-9500.0
J(JKA)
0.049;-16970.0
(QK)(JA)
0.060;-15980.0
JJ(KA)
0.071;-16970.0
QA(JQ)
0.068;-16970.0
JQKA
0.033;-28940.0
QK(QA)
0.079;-14990.0
QK(KA)
0.082;-14000.0
22(24)
0.005;-49100.0
22(28)
0.008;-45140.0
22(2Q)
0.017;-41180.0
24(23)
0.005;-54590.0
(23)(27)
0.010;-45140.0
2(23T)
0.007;-48650.0
2Q(23)
0.007;-46670.0
23(25)
0.005;-53600.0
2237
0.002;-58100.0
22(3T)
0.008;-48650.0
23(2K)
0.011;-45680.0
2(246)
0.005;-51620.0
28(24)
0.006;-49640.0
(24)(2J)
0.015;-40190.0
2244
0.004;-53600.0
22(47)
0.006;-50630.0
24(2T)
0.008;-47660.0
224Q
0.005;-52160.0
26(25)
0.006;-50630.0
(25)(29)
0.017;-41180.0
2(25Q)
0.012;-44690.0
22(56)
0.006;-50630.0
25(29)
0.006;-47660.0
225J
0.006;-52160.0
26(26)
0.012;-43160.0
(26)(29)
0.015;-40190.0
2(26Q)
0.010;-43700.0
22(67)
0.008;-48650.0
26(2T)
0.010;-45680.0
226Q
0.008;-50180.0
28(27)
0.009;-46670.0
(27)(2J)
0.019;-37220.0
2277
0.008;-47660.0
22(7T)
0.010;-44690.0
27(2K)
0.015;-41720.0
2(28T)
0.011;-43700.0
2Q(28)
0.017;-41720.0
28(2T)
0.014;-43700.0
228Q
0.007;-48200.0
2T(29)
0.010;-42710.0
(29)(2K)
0.026;-33260.0
229J
0.008;-48200.0
2T(2T)
0.023;-35240.0
(2T)(2K)
0.030;-32270.0
22TQ
0.008;-46220.0
2Q(2J)
0.018;-38750.0
2J(2K)
0.022;-37760.0
22QQ
0.025;-37760.0
3(234)
0.004;-53600.0
36(23)
0.005;-51620.0
(23)(39)
0.013;-42170.0
3(23Q)
0.009;-45680.0
5(234)
0.003;-58100.0
9(234)
0.003;-54140.0
K(234)
0.006;-50180.0
4(237)
0.004;-56120.0
49(23)
0.004;-54140.0
(23)(4Q)
0.009;-44690.0
(2357)
0.004;-55130.0
(235J)
0.005;-51170.0
(23)(56)
0.008;-49640.0
5(239)
0.003;-53150.0
5J(23)
0.007;-51170.0
(2367)
0.003;-54140.0
(236J)
0.005;-50180.0
(23)(67)
0.008;-47660.0
6(23T)
0.006;-51170.0
6Q(23)
0.008;-49190.0
9(237)
0.008;-51170.0
K(237)
0.008;-47210.0
7(23T)
0.006;-50180.0
7Q(23)
0.008;-48200.0
T(238)
0.007;-49190.0
8(239)
0.006;-50180.0
8J(23)
0.006;-48200.0
(239T)
0.009;-48200.0
99(23)
0.012;-42710.0
(23)(9Q)
0.018;-39740.0
(23TQ)
0.010;-45230.0
T(23Q)
0.011;-45230.0
Q(23J)
0.013;-44240.0
(23)(JK)
0.016;-36770.0
QK(23)
0.011;-42260.0
23(35)
0.005;-52610.0
33(28)
0.006;-49640.0
233T
0.004;-54140.0
23(3K)
0.012;-44690.0
(24)(36)
0.006;-50630.0
3(249)
0.003;-54140.0
3J(24)
0.005;-52160.0
(34)(25)
0.005;-51620.0
27(34)
0.003;-56120.0
2(34T)
0.004;-53150.0
(34)(2K)
0.012;-43700.0
34(26)
0.003;-57110.0
34(28)
0.004;-55130.0
34(2T)
0.005;-53150.0
34(2Q)
0.006;-51170.0
(25)(35)
0.015;-44150.0
3(258)
0.004;-54140.0
3T(25)
0.005;-52160.0
(25)(3K)
0.014;-42710.0
27(35)
0.004;-55130.0
2(35T)
0.005;-52160.0
(35)(2K)
0.010;-42710.0
35(27)
0.004;-55130.0
35(29)
0.005;-53150.0
35(2J)
0.008;-51170.0
35(2K)
0.010;-49190.0
37(26)
0.004;-54140.0
(26)(3T)
0.010;-44690.0
3(26K)
0.007;-48200.0
2(368)
0.005;-53150.0
(36)(2J)
0.010;-43700.0
2K(36)
0.008;-48200.0
23(68)
0.004;-53150.0
23(6T)
0.007;-51170.0
23(6Q)
0.007;-49190.0
3(278)
0.005;-52160.0
3T(27)
0.007;-50180.0
(27)(3K)
0.012;-40730.0
29(37)
0.006;-51170.0
2(37Q)
0.006;-48200.0
23(78)
0.006;-52160.0
23(7T)
0.007;-50180.0
23(7Q)
0.008;-48200.0
3(289)
0.006;-50180.0
3J(28)
0.008;-48200.0
(38)(29)
0.014;-43700.0
2J(38)
0.008;-48200.0
38(29)
0.007;-50180.0
38(2J)
0.008;-48200.0
38(2K)
0.010;-46220.0
3T(29)
0.007;-48200.0
(29)(3K)
0.022;-38750.0
2J(39)
0.010;-47210.0
39(2T)
0.006;-48200.0
39(2Q)
0.008;-46220.0
(2T)(3T)
0.026;-34250.0
3(2TK)
0.011;-44240.0
2(3TQ)
0.012;-45230.0
23(TJ)
0.010;-46220.0
23(TK)
0.010;-44240.0
(2J)(3K)
0.020;-36770.0
2K(3J)
0.013;-43250.0
23(JK)
0.014;-43250.0
(3Q)(2K)
0.021;-35780.0
(2K)(3K)
0.036;-28310.0
4(246)
0.007;-49640.0
48(24)
0.007;-47660.0
(24)(4J)
0.023;-38210.0
5(245)
0.006;-49640.0
9(245)
0.005;-52160.0
K(245)
0.008;-48200.0
5(248)
0.005;-53150.0
5T(24)
0.005;-51170.0
(24)(5K)
0.013;-41720.0
9(246)
0.006;-51170.0
K(246)
0.007;-47210.0
6(249)
0.006;-51170.0
6J(24)
0.006;-49190.0
(2478)
0.007;-51170.0
(247Q)
0.009;-47210.0
7(249)
0.005;-50180.0
7J(24)
0.008;-48200.0
(2489)
0.006;-49190.0
(248K)
0.009;-45230.0
8T(24)
0.008;-48200.0
(24)(8K)
0.020;-38750.0
Q(249)
0.010;-45230.0
(24)(9J)
0.013;-39740.0
T(24T)
0.012;-39740.0
T(24J)
0.011;-45230.0
TK(24)
0.016;-43250.0
(24)(JQ)
0.018;-36770.0
QQ(24)
0.022;-35780.0
24(45)
0.007;-50630.0
44(28)
0.008;-47660.0
244T
0.006;-52160.0
24(4K)
0.012;-42710.0
(25)(47)
0.006;-47660.0
4(25T)
0.005;-51170.0
4Q(25)
0.006;-49190.0
(45)(27)
0.009;-47660.0
29(45)
0.005;-52160.0
2(45Q)
0.007;-49190.0
24(56)
0.004;-55130.0
24(58)
0.005;-53150.0
24(5T)
0.006;-51170.0
24(5Q)
0.006;-49190.0
4(267)
0.004;-53150.0
49(26)
0.006;-51170.0
(26)(4Q)
0.016;-41720.0
27(46)
0.006;-53150.0
2(46T)
0.007;-50180.0
(46)(2K)
0.017;-40730.0
46(28)
0.006;-52160.0
46(2T)
0.005;-50180.0
46(2Q)
0.007;-48200.0
(27)(47)
0.013;-39200.0
4(27T)
0.006;-49190.0
4Q(27)
0.007;-47210.0
(47)(29)
0.012;-43700.0
2J(47)
0.008;-48200.0
47(28)
0.006;-51170.0
47(2T)
0.007;-49190.0
47(2Q)
0.007;-47210.0
(28)(48)
0.020;-37220.0
4(28J)
0.009;-47210.0
4K(28)
0.013;-45230.0
(48)(2J)
0.018;-40730.0
2K(48)
0.008;-45230.0
24(8T)
0.008;-48200.0
24(8Q)
0.010;-46220.0
4(29T)
0.009;-47210.0
4Q(29)
0.010;-45230.0
(49)(2J)
0.017;-39740.0
2K(49)
0.014;-44240.0
24(9J)
0.009;-46220.0
24(9K)
0.011;-44240.0
(2T)(4Q)
0.022;-37760.0
2J(4T)
0.012;-45230.0
4T(2J)
0.011;-45230.0
4T(2K)
0.011;-43250.0
4Q(2J)
0.013;-43250.0
(4J)(2K)
0.018;-35780.0
4J(2K)
0.012;-42260.0
4K(2Q)
0.014;-41270.0
24(QK)
0.013;-41270.0
(25)(56)
0.013;-41180.0
5(259)
0.009;-44690.0
5J(25)
0.011;-42710.0
(2567)
0.005;-52160.0
(256J)
0.010;-48200.0
(25)(67)
0.010;-45680.0
6(25T)
0.005;-49190.0
6Q(25)
0.008;-47210.0
9(257)
0.007;-49190.0
K(257)
0.013;-45230.0
7(25T)
0.007;-48200.0
7Q(25)
0.011;-46220.0
T(258)
0.009;-47210.0
8(259)
0.006;-48200.0
8J(25)
0.009;-46220.0
(259T)
0.009;-46220.0
99(25)
0.017;-40730.0
(25)(9Q)
0.016;-37760.0
(25TQ)
0.011;-43250.0
T(25Q)
0.012;-43250.0
Q(25J)
0.013;-42260.0
(25)(JK)
0.023;-34790.0
QK(25)
0.015;-40280.0
25(57)
0.010;-46670.0
55(2T)
0.013;-43700.0
255Q
0.009;-48200.0
57(26)
0.007;-52160.0
(26)(5T)
0.015;-42710.0
5(26K)
0.009;-46220.0
2(568)
0.005;-51170.0
(56)(2J)
0.012;-41720.0
2K(56)
0.010;-46220.0
25(68)
0.006;-51170.0
25(6T)
0.008;-49190.0
25(6Q)
0.010;-47210.0
5(278)
0.006;-50180.0
5T(27)
0.009;-48200.0
(27)(5K)
0.014;-38750.0
29(57)
0.006;-49190.0
2(57Q)
0.010;-46220.0
25(78)
0.007;-50180.0
25(7T)
0.008;-48200.0
25(7Q)
0.009;-46220.0
5(289)
0.008;-48200.0
5J(28)
0.008;-46220.0
(58)(29)
0.010;-41720.0
2J(58)
0.007;-46220.0
58(29)
0.006;-48200.0
58(2J)
0.008;-46220.0
58(2K)
0.008;-44240.0
5T(29)
0.009;-46220.0
(29)(5K)
0.019;-36770.0
2J(59)
0.010;-45230.0
59(2T)
0.007;-46220.0
59(2Q)
0.013;-44240.0
(2T)(5T)
0.022;-32270.0
5(2TK)
0.011;-42260.0
2(5TQ)
0.011;-43250.0
25(TJ)
0.014;-44240.0
25(TK)
0.011;-42260.0
(2J)(5K)
0.028;-34790.0
2K(5J)
0.013;-41270.0
25(JK)
0.014;-41270.0
(5Q)(2K)
0.028;-33800.0
(2K)(5K)
0.038;-26330.0
6(268)
0.013;-43700.0
6T(26)
0.012;-41720.0
(26)(6K)
0.033;-32270.0
T(267)
0.011;-47210.0
7(268)
0.006;-49190.0
7T(26)
0.009;-47210.0
(26)(7K)
0.022;-37760.0
J(268)
0.010;-45230.0
89(26)
0.006;-47210.0
(26)(8Q)
0.017;-37760.0
(269J)
0.014;-44240.0
(26)(9T)
0.012;-38750.0
9(26K)
0.012;-42260.0
(26TK)
0.018;-41270.0
TQ(26)
0.015;-42260.0
K(26J)
0.017;-40280.0
Q(26Q)
0.029;-33800.0
KK(26)
0.029;-31820.0
66(29)
0.014;-42710.0
266J
0.009;-47210.0
67(27)
0.011;-43700.0
(27)(6T)
0.016;-40730.0
6(27K)
0.010;-44240.0
2(679)
0.006;-48200.0
(67)(2Q)
0.015;-38750.0
27(68)
0.006;-49190.0
27(6T)
0.007;-47210.0
27(6Q)
0.010;-45230.0
68(28)
0.012;-41720.0
(28)(6J)
0.015;-38750.0
28(68)
0.014;-41720.0
2(68J)
0.011;-45230.0
2688
0.008;-48200.0
268T
0.005;-52700.0
268Q
0.006;-50720.0
(29)(6T)
0.017;-38750.0
6(29K)
0.016;-42260.0
2(69J)
0.011;-44240.0
2699
0.008;-46220.0
269J
0.006;-50720.0
269K
0.007;-48740.0
6Q(2T)
0.010;-42260.0
(6T)(2Q)
0.022;-35780.0
2T(6J)
0.013;-43250.0
2T(6K)
0.012;-41270.0
6(2JK)
0.014;-40280.0
2(6JK)
0.015;-40280.0
2J(6K)
0.015;-40280.0
2Q(6Q)
0.025;-33800.0
26QK
0.009;-45770.0
78(27)
0.014;-41720.0
(27)(7J)
0.020;-32270.0
8(278)
0.014;-40730.0
Q(278)
0.013;-43250.0
(27)(8T)
0.015;-38750.0
8(27K)
0.014;-42260.0
(279Q)
0.011;-42260.0
9(27J)
0.016;-43250.0
9K(27)
0.014;-41270.0
TT(27)
0.020;-36770.0
(27)(TK)
0.020;-33800.0
J(27Q)
0.016;-40280.0
K(27Q)
0.022;-38300.0
77(28)
0.015;-41720.0
277T
0.007;-46220.0
27(7K)
0.022;-36770.0
(28)(7T)
0.019;-38750.0
7(28K)
0.013;-42260.0
2(78T)
0.011;-45230.0
(78)(2K)
0.022;-35780.0
78(2T)
0.013;-45230.0
78(2Q)
0.009;-43250.0
(29)(79)
0.028;-32270.0
7(29Q)
0.013;-42260.0
2(79T)
0.013;-44240.0
(79)(2K)
0.021;-34790.0
79(2J)
0.014;-43250.0
79(2K)
0.012;-41270.0
7J(2T)
0.014;-42260.0
(7T)(2J)
0.019;-35780.0
2K(7T)
0.016;-40280.0
27(TQ)
0.014;-41270.0
7(2JQ)
0.011;-40280.0
2(7JQ)
0.011;-40280.0
27(JQ)
0.012;-40280.0
7(2QK)
0.016;-38300.0
7Q(2K)
0.022;-38300.0
88(28)
0.020;-33260.0
(28)(8J)
0.035;-30290.0
9(289)
0.022;-37760.0
K(289)
0.019;-40280.0
9(28Q)
0.014;-41270.0
J(28T)
0.016;-41270.0
TJ(28)
0.013;-41270.0
(28JQ)
0.022;-39290.0
J(28K)
0.019;-38300.0
(28)(QK)
0.024;-30830.0
88(2T)
0.017;-37760.0
288Q
0.014;-42260.0
8T(29)
0.013;-43250.0
(29)(8K)
0.028;-33800.0
2J(89)
0.013;-42260.0
89(2T)
0.011;-43250.0
89(2Q)
0.015;-41270.0
(2T)(8T)
0.038;-29300.0
8(2TK)
0.014;-39290.0
2(8TQ)
0.016;-40280.0
28(TJ)
0.013;-41270.0
28(TK)
0.019;-39290.0
(2J)(8K)
0.028;-31820.0
2K(8J)
0.017;-38300.0
28(JK)
0.019;-38300.0
(8Q)(2K)
0.029;-30830.0
(2K)(8K)
0.035;-23360.0
9(29J)
0.025;-34790.0
9K(29)
0.025;-32810.0
TT(29)
0.022;-34790.0
(29)(TK)
0.028;-31820.0
J(29Q)
0.014;-38300.0
K(29Q)
0.023;-36320.0
99(2T)
0.022;-35780.0
299Q
0.016;-40280.0
9J(2T)
0.014;-40280.0
(9T)(2J)
0.026;-33800.0
2K(9T)
0.019;-38300.0
29(TQ)
0.017;-39290.0
9(2JQ)
0.016;-38300.0
2(9JQ)
0.020;-38300.0
29(JQ)
0.020;-38300.0
9(2QK)
0.018;-36320.0
9Q(2K)
0.017;-36320.0
TT(2T)
0.039;-27320.0
(2T)(TK)
0.038;-24350.0
J(2TQ)
0.019;-37310.0
K(2TQ)
0.024;-35330.0
TT(2J)
0.022;-32810.0
2TTK
0.019;-37310.0
TK(2J)
0.016;-36320.0
2TJJ
0.021;-38300.0
2TJK
0.016;-42800.0
2(TQK)
0.021;-35330.0
TK(2K)
0.038;-27860.0
(2J)(JK)
0.043;-22370.0
QK(2J)
0.019;-34340.0
2J(JK)
0.034;-28850.0
(JQ)(2K)
0.033;-27860.0
(2K)(JK)
0.049;-20390.0
K(2QK)
0.038;-25880.0
2K(QK)
0.035;-25880.0
3335
0.005;-51620.0
3339
0.007;-47660.0
333K
0.011;-43700.0
36(34)
0.007;-49640.0
(34)(39)
0.015;-40190.0
3(34Q)
0.015;-43700.0
33(45)
0.006;-50630.0
34(38)
0.010;-47660.0
334T
0.005;-52160.0
33(4K)
0.012;-42710.0
(35)(37)
0.017;-41180.0
3(35T)
0.012;-44690.0
3Q(35)
0.013;-42710.0
35(37)
0.009;-47660.0
3359
0.005;-52160.0
33(5Q)
0.013;-42710.0
(36)(37)
0.018;-40190.0
3(36T)
0.013;-43700.0
3Q(36)
0.014;-41720.0
36(38)
0.009;-45680.0
336T
0.008;-50180.0
33(6K)
0.014;-40730.0
(37)(39)
0.019;-37220.0
3(37Q)
0.016;-40730.0
33(78)
0.015;-44690.0
37(3J)
0.013;-41720.0
337K
0.010;-46220.0
3T(38)
0.011;-41720.0
(38)(3K)
0.022;-32270.0
338T
0.009;-48200.0
33(8K)
0.023;-38750.0
(39)(3J)
0.025;-33260.0
3399
0.012;-41720.0
33(9Q)
0.016;-38750.0
(3T)(3J)
0.024;-32270.0
33TT
0.015;-39740.0
33(TK)
0.019;-36770.0
(3J)(3K)
0.028;-29300.0
33JK
0.017;-42260.0
33(QK)
0.018;-34790.0
45(34)
0.007;-49640.0
(34)(48)
0.016;-40190.0
4(34J)
0.011;-43700.0
4K(34)
0.013;-41720.0
(3459)
0.006;-51170.0
(345K)
0.009;-47210.0
57(34)
0.005;-53150.0
(34)(5T)
0.011;-43700.0
5(34K)
0.011;-47210.0
(3469)
0.008;-50180.0
(346K)
0.009;-46220.0
68(34)
0.006;-51170.0
(34)(6J)
0.013;-41720.0
7(347)
0.010;-44690.0
J(347)
0.009;-47210.0
78(34)
0.009;-50180.0
(34)(7J)
0.018;-40730.0
8(348)
0.013;-42710.0
Q(348)
0.008;-45230.0
(34)(8T)
0.012;-40730.0
8(34K)
0.009;-44240.0
(349Q)
0.011;-44240.0
9(34J)
0.008;-45230.0
9K(34)
0.013;-43250.0
TT(34)
0.019;-38750.0
(34)(TK)
0.022;-35780.0
J(34Q)
0.013;-42260.0
K(34Q)
0.011;-40280.0
44(35)
0.006;-49640.0
3447
0.004;-54140.0
34(4T)
0.011;-44690.0
44(3K)
0.012;-41720.0
4(357)
0.004;-53150.0
49(35)
0.006;-51170.0
(35)(4Q)
0.016;-41720.0
36(45)
0.005;-54140.0
3(459)
0.006;-51170.0
(45)(3Q)
0.012;-41720.0
35(46)
0.004;-54140.0
35(48)
0.005;-52160.0
35(4T)
0.006;-50180.0
35(4Q)
0.007;-48200.0
46(36)
0.007;-46670.0
(36)(49)
0.012;-43700.0
4(36Q)
0.008;-47210.0
3(467)
0.004;-52160.0
(46)(3T)
0.009;-42710.0
3Q(46)
0.006;-47210.0
3467
0.002;-58640.0
3469
0.002;-56660.0
346J
0.004;-54680.0
346K
0.005;-52700.0
49(37)
0.007;-49190.0
(37)(4Q)
0.013;-39740.0
38(47)
0.007;-50180.0
3(47J)
0.012;-47210.0
3477
0.006;-51170.0
3479
0.004;-55670.0
347J
0.003;-53690.0
347K
0.006;-51710.0
4T(38)
0.008;-47210.0
(38)(4K)
0.019;-37760.0
3T(48)
0.008;-47210.0
3(48K)
0.015;-44240.0
38(4T)
0.009;-47210.0
38(4Q)
0.012;-45230.0
49(39)
0.015;-40730.0
(39)(4Q)
0.017;-37760.0
3T(49)
0.010;-46220.0
3(49K)
0.014;-43250.0
39(4J)
0.011;-45230.0
39(4K)
0.016;-43250.0
4(3TQ)
0.014;-43250.0
3(4TJ)
0.012;-44240.0
34TT
0.010;-45230.0
34TQ
0.005;-49730.0
(3J)(4Q)
0.018;-35780.0
3Q(4J)
0.011;-42260.0
34JQ
0.008;-48740.0
(3Q)(4K)
0.022;-33800.0
3Q(4K)
0.017;-40280.0
5(356)
0.008;-46670.0
58(35)
0.012;-44690.0
(35)(5J)
0.020;-35240.0
6(356)
0.010;-45680.0
T(356)
0.008;-48200.0
6(357)
0.005;-51170.0
69(35)
0.009;-49190.0
(35)(6Q)
0.016;-39740.0
(3579)
0.009;-48200.0
(357K)
0.011;-44240.0
79(35)
0.009;-48200.0
(35)(7Q)
0.015;-38750.0
(358T)
0.011;-46220.0
88(35)
0.012;-41720.0
(35)(8J)
0.014;-38750.0
9(359)
0.012;-39740.0
K(359)
0.013;-42260.0
9(35Q)
0.011;-43250.0
J(35T)
0.010;-43250.0
TJ(35)
0.010;-43250.0
(35JQ)
0.014;-41270.0
J(35K)
0.016;-40280.0
(35)(QK)
0.032;-32810.0
55(37)
0.010;-45680.0
3559
0.006;-50180.0
35(5Q)
0.017;-40730.0
(36)(57)
0.015;-44690.0
5(36T)
0.008;-48200.0
5Q(36)
0.007;-46220.0
(56)(38)
0.016;-43700.0
3T(56)
0.009;-48200.0
3(56K)
0.009;-45230.0
36(58)
0.006;-50180.0
36(5T)
0.009;-48200.0
36(5Q)
0.009;-46220.0
57(37)
0.015;-43700.0
(37)(5T)
0.017;-40730.0
5(37K)
0.010;-44240.0
3(579)
0.008;-48200.0
(57)(3Q)
0.017;-38750.0
37(58)
0.007;-49190.0
37(5T)
0.010;-47210.0
37(5Q)
0.014;-45230.0
58(38)
0.013;-41720.0
(38)(5J)
0.015;-38750.0
38(58)
0.014;-41720.0
3(58J)
0.008;-45230.0
3588
0.007;-48200.0
358T
0.005;-52700.0
358Q
0.007;-50720.0
(39)(5T)
0.021;-38750.0
5(39K)
0.013;-42260.0
3(59J)
0.011;-44240.0
3599
0.012;-46220.0
359J
0.006;-50720.0
359K
0.007;-48740.0
5Q(3T)
0.013;-42260.0
(5T)(3Q)
0.024;-35780.0
3T(5J)
0.011;-43250.0
3T(5K)
0.013;-41270.0
5(3JK)
0.012;-40280.0
3(5JK)
0.016;-40280.0
3J(5K)
0.018;-40280.0
3Q(5Q)
0.028;-33800.0
35QK
0.008;-45770.0
67(36)
0.011;-43700.0
(36)(6T)
0.021;-34250.0
6(36K)
0.018;-37760.0
(367T)
0.009;-46220.0
77(36)
0.015;-42710.0
(36)(7T)
0.015;-39740.0
7(36K)
0.010;-43250.0
(368J)
0.013;-44240.0
(36)(89)
0.013;-39740.0
8(36Q)
0.015;-43250.0
T(369)
0.009;-44240.0
9(36T)
0.011;-44240.0
9Q(36)
0.017;-42260.0
Q(36T)
0.015;-41270.0
(36)(TQ)
0.019;-34790.0
(36JK)
0.020;-39290.0
JK(36)
0.013;-39290.0
K(36K)
0.030;-30830.0
3668
0.007;-49190.0
36(6J)
0.015;-39740.0
(37)(67)
0.024;-36230.0
6(37T)
0.009;-46220.0
6Q(37)
0.009;-44240.0
(67)(39)
0.018;-40730.0
3J(67)
0.008;-45230.0
67(38)
0.008;-48200.0
67(3T)
0.007;-46220.0
67(3Q)
0.014;-44240.0
(38)(68)
0.027;-34250.0
6(38J)
0.012;-44240.0
6K(38)
0.011;-42260.0
(68)(3J)
0.021;-37760.0
3K(68)
0.017;-42260.0
36(8T)
0.014;-45230.0
36(8Q)
0.010;-43250.0
6(39T)
0.012;-44240.0
6Q(39)
0.018;-42260.0
(69)(3J)
0.020;-36770.0
3K(69)
0.015;-41270.0
36(9J)
0.013;-43250.0
36(9K)
0.013;-41270.0
(3T)(6Q)
0.024;-34790.0
3J(6T)
0.012;-42260.0
6T(3J)
0.012;-42260.0
6T(3K)
0.016;-40280.0
6Q(3J)
0.014;-40280.0
(6J)(3K)
0.029;-32810.0
6J(3K)
0.019;-39290.0
6K(3Q)
0.013;-38300.0
36(QK)
0.018;-38300.0
(37)(78)
0.023;-34250.0
7(37J)
0.019;-37760.0
7K(37)
0.020;-35780.0
(378Q)
0.013;-42260.0
8(37T)
0.009;-44240.0
8Q(37)
0.015;-42260.0
J(379)
0.019;-42260.0
9T(37)
0.014;-43250.0
(37)(9K)
0.023;-33800.0
K(37T)
0.016;-39290.0
T(37K)
0.016;-39290.0
JJ(37)
0.031;-33800.0
(37QK)
0.019;-37310.0
3777
0.013;-41720.0
37(7T)
0.022;-38750.0
77(3K)
0.019;-35780.0
7(38T)
0.010;-44240.0
7Q(38)
0.011;-42260.0
(78)(3T)
0.016;-37760.0
3Q(78)
0.010;-42260.0
3789
0.005;-51710.0
378J
0.006;-49730.0
378K
0.010;-47750.0
7J(39)
0.013;-42260.0
(79)(3T)
0.019;-36770.0
3Q(79)
0.014;-41270.0
379T
0.006;-49730.0
379Q
0.009;-47750.0
(3T)(7J)
0.030;-34790.0
3T(7T)
0.019;-35780.0
3(7TK)
0.018;-39290.0
3T(7Q)
0.015;-40280.0
7J(3J)
0.032;-33800.0
(7J)(3Q)
0.024;-32810.0
3J(7Q)
0.013;-39290.0
7Q(3Q)
0.023;-31820.0
37QQ
0.016;-38300.0
37KK
0.025;-36320.0
8(38J)
0.021;-35780.0
8K(38)
0.019;-33800.0
(389K)
0.014;-39290.0
9J(38)
0.019;-41270.0
(38TJ)
0.018;-40280.0
(38)(TJ)
0.023;-33800.0
J(38J)
0.020;-32810.0
JQ(38)
0.013;-38300.0
Q(38K)
0.020;-36320.0
3889
0.011;-44240.0
38(8Q)
0.027;-34790.0
(39)(8T)
0.021;-35780.0
8(39K)
0.022;-39290.0
3(89J)
0.015;-41270.0
3899
0.014;-43250.0
389J
0.010;-47750.0
389K
0.010;-45770.0
8Q(3T)
0.018;-39290.0
(8T)(3Q)
0.027;-32810.0
3T(8J)
0.014;-40280.0
3T(8K)
0.023;-38300.0
8(3JK)
0.021;-37310.0
3(8JK)
0.024;-37310.0
3J(8K)
0.014;-37310.0
3Q(8Q)
0.031;-30830.0
38QK
0.012;-42800.0
9T(39)
0.020;-34790.0
(39)(9K)
0.029;-25340.0
K(39T)
0.017;-37310.0
T(39K)
0.023;-37310.0
JJ(39)
0.034;-31820.0
(39QK)
0.023;-35330.0
3999
0.026;-35780.0
39(9Q)
0.026;-32810.0
(3T)(9J)
0.028;-32810.0
3T(9T)
0.028;-33800.0
3(9TK)
0.019;-37310.0
3T(9Q)
0.020;-38300.0
9J(3J)
0.028;-31820.0
(9J)(3Q)
0.026;-30830.0
3J(9Q)
0.026;-37310.0
9Q(3Q)
0.023;-29840.0
39QQ
0.025;-36320.0
39KK
0.022;-34340.0
T(3TK)
0.031;-29840.0
JJ(3T)
0.028;-30830.0
(3TQK)
0.029;-34340.0
3TTT
0.030;-32810.0
3T(TK)
0.028;-29840.0
(3J)(TK)
0.042;-28850.0
3K(TJ)
0.021;-35330.0
3T(JK)
0.025;-35330.0
(TQ)(3K)
0.046;-27860.0
(3K)(TK)
0.064;-20390.0
J(3JK)
0.030;-27860.0
(3J)(QK)
0.034;-26870.0
JJ(3K)
0.027;-27860.0
3Q(JQ)
0.033;-27860.0
3JQK
0.016;-39830.0
QK(3Q)
0.045;-25880.0
QK(3K)
0.042;-24890.0
44(46)
0.012;-41180.0
44(4T)
0.020;-37220.0
(45)(45)
0.020;-34700.0
4(458)
0.008;-44690.0
4T(45)
0.012;-42710.0
(45)(4K)
0.027;-33260.0
4457
0.005;-52160.0
44(5T)
0.012;-42710.0
45(4K)
0.017;-39740.0
4(468)
0.017;-43700.0
4T(46)
0.013;-41720.0
(46)(4K)
0.024;-32270.0
4468
0.005;-50180.0
44(6J)
0.011;-40730.0
(47)(47)
0.031;-30740.0
4(47T)
0.019;-40730.0
4Q(47)
0.019;-38750.0
47(49)
0.013;-41720.0
447J
0.007;-46220.0
48(48)
0.022;-35240.0
(48)(4J)
0.021;-32270.0
4488
0.014;-41720.0
44(8J)
0.017;-38750.0
(49)(49)
0.036;-26780.0
4(49Q)
0.023;-36770.0
44(9T)
0.017;-38750.0
49(4K)
0.023;-35780.0
4(4TQ)
0.026;-35780.0
44(TJ)
0.019;-36770.0
(4J)(4J)
0.038;-22820.0
44JJ
0.022;-35780.0
4Q(4Q)
0.027;-27320.0
(4K)(4K)
0.053;-18860.0
(45)(57)
0.022;-38210.0
5(45T)
0.016;-41720.0
5Q(45)
0.015;-39740.0
8(456)
0.008;-49190.0
Q(456)
0.008;-45230.0
(45)(68)
0.013;-42710.0
6(45J)
0.009;-46220.0
6K(45)
0.012;-44240.0
(457J)
0.013;-45230.0
(45)(78)
0.012;-41720.0
7(45J)
0.010;-45230.0
7K(45)
0.015;-43250.0
(458Q)
0.011;-43250.0
8(45T)
0.009;-45230.0
8Q(45)
0.011;-43250.0
J(459)
0.011;-43250.0
9T(45)
0.013;-44240.0
(45)(9K)
0.030;-34790.0
K(45T)
0.013;-40280.0
T(45K)
0.012;-40280.0
JJ(45)
0.029;-34790.0
(45QK)
0.018;-38300.0
4555
0.009;-46670.0
45(58)
0.012;-43700.0
55(4J)
0.016;-40730.0
455K
0.008;-45230.0
58(46)
0.010;-49190.0
(46)(5J)
0.017;-39740.0
46(56)
0.013;-44690.0
4(569)
0.008;-48200.0
(56)(4Q)
0.017;-38750.0
46(57)
0.007;-50180.0
46(59)
0.006;-48200.0
46(5J)
0.009;-46220.0
46(5K)
0.012;-44240.0
5(479)
0.011;-47210.0
5J(47)
0.014;-45230.0
(57)(48)
0.015;-41720.0
4T(57)
0.008;-46220.0
4(57K)
0.014;-43250.0
47(59)
0.008;-47210.0
47(5J)
0.011;-45230.0
47(5K)
0.013;-43250.0
5(48T)
0.011;-45230.0
5Q(48)
0.013;-43250.0
(58)(4T)
0.017;-38750.0
4Q(58)
0.010;-43250.0
4589
0.004;-52700.0
458J
0.005;-50720.0
458K
0.009;-48740.0
5J(49)
0.010;-43250.0
(59)(4T)
0.018;-37760.0
4Q(59)
0.016;-42260.0
459T
0.007;-50720.0
459Q
0.008;-48740.0
(4T)(5J)
0.019;-35780.0
4T(5T)
0.016;-36770.0
4(5TK)
0.015;-40280.0
4T(5Q)
0.015;-41270.0
5J(4J)
0.021;-34790.0
(5J)(4Q)
0.033;-33800.0
4J(5Q)
0.018;-40280.0
5Q(4Q)
0.023;-32810.0
45QQ
0.019;-39290.0
45KK
0.024;-37310.0
6(469)
0.011;-40730.0
6J(46)
0.020;-38750.0
(4678)
0.010;-47210.0
(467Q)
0.013;-43250.0
7(469)
0.008;-46220.0
7J(46)
0.012;-44240.0
(4689)
0.013;-45230.0
(468K)
0.011;-41270.0
8T(46)
0.011;-44240.0
(46)(8K)
0.018;-34790.0
Q(469)
0.015;-41270.0
(46)(9J)
0.024;-35780.0
T(46T)
0.017;-35780.0
T(46J)
0.017;-41270.0
TK(46)
0.015;-39290.0
(46)(JQ)
0.026;-32810.0
QQ(46)
0.026;-31820.0
46(67)
0.014;-42710.0
66(4T)
0.015;-39740.0
466Q
0.008;-44240.0
68(47)
0.011;-47210.0
(47)(6J)
0.017;-37760.0
47(67)
0.010;-41720.0
4(67T)
0.011;-45230.0
(67)(4K)
0.022;-35780.0
67(49)
0.011;-46220.0
67(4J)
0.012;-44240.0
67(4K)
0.013;-42260.0
69(48)
0.013;-45230.0
(48)(6Q)
0.021;-35780.0
49(68)
0.011;-45230.0
4(68Q)
0.010;-42260.0
46(89)
0.010;-45230.0
46(8J)
0.016;-43250.0
46(8K)
0.014;-41270.0
(49)(6J)
0.021;-35780.0
49(69)
0.019;-37760.0
4(69Q)
0.013;-41270.0
46(9T)
0.013;-43250.0
46(9Q)
0.013;-41270.0
6(4TJ)
0.012;-41270.0
6K(4T)
0.020;-39290.0
(6T)(4K)
0.026;-32810.0
6T(4Q)
0.019;-40280.0
(4J)(6J)
0.028;-27320.0
4J(6J)
0.024;-33800.0
6J(4Q)
0.016;-39290.0
(4Q)(6Q)
0.039;-25340.0
4K(6Q)
0.022;-37310.0
4K(6K)
0.024;-29840.0
79(47)
0.017;-38750.0
(47)(7Q)
0.037;-29300.0
(478T)
0.010;-43250.0
88(47)
0.020;-38750.0
(47)(8J)
0.022;-35780.0
9(479)
0.026;-36770.0
K(479)
0.017;-39290.0
9(47Q)
0.017;-40280.0
J(47T)
0.019;-40280.0
TJ(47)
0.016;-40280.0
(47JQ)
0.024;-38300.0
J(47K)
0.017;-37310.0
(47)(QK)
0.036;-29840.0
77(49)
0.018;-38750.0
477J
0.011;-43250.0
78(48)
0.019;-38750.0
(48)(7J)
0.025;-35780.0
48(78)
0.022;-38750.0
4(78J)
0.013;-42260.0
4788
0.012;-45230.0
478T
0.006;-49730.0
478Q
0.007;-47750.0
(49)(7T)
0.019;-35780.0
7(49K)
0.018;-39290.0
4(79J)
0.014;-41270.0
4799
0.018;-43250.0
479J
0.007;-47750.0
479K
0.010;-45770.0
7Q(4T)
0.019;-39290.0
(7T)(4Q)
0.031;-32810.0
4T(7J)
0.021;-40280.0
4T(7K)
0.024;-38300.0
7(4JK)
0.023;-37310.0
4(7JK)
0.021;-37310.0
4J(7K)
0.019;-37310.0
4Q(7Q)
0.033;-30830.0
47QK
0.011;-42800.0
89(48)
0.017;-36770.0
(48)(8Q)
0.026;-27320.0
(489J)
0.018;-40280.0
(48)(9T)
0.021;-34790.0
9(48K)
0.019;-38300.0
(48TK)
0.021;-37310.0
TQ(48)
0.021;-38300.0
K(48J)
0.020;-36320.0
Q(48Q)
0.026;-29840.0
KK(48)
0.039;-27860.0
88(4J)
0.017;-34790.0
488K
0.017;-39290.0
8J(49)
0.016;-40280.0
(89)(4T)
0.021;-34790.0
4Q(89)
0.014;-39290.0
489T
0.008;-47750.0
489Q
0.011;-45770.0
(4T)(8J)
0.026;-32810.0
4T(8T)
0.021;-33800.0
4(8TK)
0.022;-37310.0
4T(8Q)
0.017;-38300.0
8J(4J)
0.027;-31820.0
(8J)(4Q)
0.026;-30830.0
4J(8Q)
0.018;-37310.0
8Q(4Q)
0.034;-29840.0
48QQ
0.016;-36320.0
48KK
0.022;-34340.0
9(49Q)
0.037;-31820.0
J(49T)
0.016;-38300.0
TJ(49)
0.021;-38300.0
(49JQ)
0.022;-36320.0
J(49K)
0.024;-35330.0
(49)(QK)
0.037;-27860.0
99(4J)
0.034;-32810.0
499K
0.020;-37310.0
9Q(4T)
0.016;-37310.0
(9T)(4Q)
0.028;-30830.0
4T(9J)
0.019;-38300.0
4T(9K)
0.015;-36320.0
9(4JK)
0.021;-35330.0
4(9JK)
0.022;-35330.0
4J(9K)
0.025;-35330.0
4Q(9Q)
0.038;-28850.0
49QK
0.021;-40820.0
TJ(4T)
0.035;-30830.0
(4TJQ)
0.025;-35330.0
J(4TK)
0.021;-34340.0
(4T)(QK)
0.032;-26870.0
TT(4Q)
0.030;-29840.0
T(4JQ)
0.020;-35330.0
4(TJQ)
0.020;-35330.0
4T(JQ)
0.024;-35330.0
T(4QK)
0.020;-33350.0
TQ(4K)
0.030;-33350.0
JJ(4J)
0.048;-22370.0
(4JQK)
0.031;-32360.0
4JJJ
0.038;-28850.0
JQ(4Q)
0.041;-26870.0
4JQQ
0.028;-33350.0
4JKK
0.023;-31370.0
QQ(4K)
0.039;-24890.0
4KKK
0.050;-22910.0
55(59)
0.028;-35240.0
55(5K)
0.024;-31280.0
(56)(58)
0.023;-35240.0
5(56J)
0.020;-38750.0
5K(56)
0.014;-36770.0
56(59)
0.014;-40730.0
556J
0.013;-45230.0
57(57)
0.023;-35240.0
(57)(5T)
0.021;-32270.0
5(57K)
0.022;-35780.0
55(79)
0.017;-39740.0
57(5Q)
0.020;-36770.0
5(589)
0.017;-38750.0
5J(58)
0.023;-36770.0
58(59)
0.017;-38750.0
558J
0.017;-43250.0
59(59)
0.031;-31280.0
(59)(5Q)
0.040;-28310.0
559T
0.014;-43250.0
55(9K)
0.030;-33800.0
(5T)(5Q)
0.043;-27320.0
55TJ
0.014;-41270.0
5J(5J)
0.031;-27320.0
5J(5Q)
0.030;-32810.0
5(5QK)
0.029;-30830.0
5K(5K)
0.037;-23360.0
68(56)
0.012;-40730.0
(56)(6J)
0.028;-31280.0
7(567)
0.014;-40730.0
J(567)
0.009;-43250.0
78(56)
0.009;-46220.0
(56)(7J)
0.019;-36770.0
8(568)
0.016;-38750.0
Q(568)
0.017;-41270.0
(56)(8T)
0.021;-36770.0
8(56K)
0.019;-40280.0
(569Q)
0.015;-40280.0
9(56J)
0.016;-41270.0
9K(56)
0.017;-39290.0
TT(56)
0.026;-34790.0
(56)(TK)
0.031;-31820.0
J(56Q)
0.020;-38300.0
K(56Q)
0.023;-36320.0
66(57)
0.016;-41720.0
5669
0.011;-46220.0
56(6Q)
0.020;-36770.0
(57)(68)
0.015;-39740.0
6(57J)
0.010;-43250.0
6K(57)
0.014;-41270.0
(67)(5T)
0.019;-37760.0
5Q(67)
0.014;-42260.0
5678
0.005;-52700.0
567T
0.008;-50720.0
567Q
0.009;-48740.0
(58)(69)
0.018;-37760.0
6(58Q)
0.017;-41270.0
5(689)
0.010;-44240.0
(68)(5Q)
0.024;-34790.0
58(69)
0.011;-44240.0
58(6J)
0.009;-42260.0
58(6K)
0.016;-40280.0
6(59J)
0.018;-41270.0
6K(59)
0.018;-39290.0
(69)(5Q)
0.028;-33800.0
59(6T)
0.014;-42260.0
59(6Q)
0.015;-40280.0
6T(5T)
0.020;-34790.0
(5T)(6K)
0.022;-31820.0
5Q(6T)
0.018;-39290.0
56TJ
0.012;-46760.0
56TK
0.009;-44780.0
6K(5J)
0.019;-37310.0
56JJ
0.021;-39290.0
56JK
0.010;-43790.0
5(6QK)
0.025;-36320.0
6K(5K)
0.027;-28850.0
(57)(79)
0.026;-31280.0
7(57Q)
0.021;-34790.0
9(578)
0.011;-43250.0
K(578)
0.015;-39290.0
8(57J)
0.013;-41270.0
8K(57)
0.020;-39290.0
(579K)
0.014;-38300.0
9J(57)
0.016;-40280.0
(57TJ)
0.017;-39290.0
(57)(TJ)
0.022;-32810.0
J(57J)
0.021;-31820.0
JQ(57)
0.019;-37310.0
Q(57K)
0.019;-35330.0
5778
0.013;-45230.0
57(7J)
0.020;-35780.0
(58)(78)
0.029;-31280.0
7(58J)
0.014;-41270.0
7K(58)
0.017;-39290.0
(78)(5J)
0.025;-34790.0
5K(78)
0.019;-39290.0
57(8T)
0.018;-42260.0
57(8Q)
0.019;-40280.0
7(59T)
0.019;-41270.0
7Q(59)
0.016;-39290.0
(79)(5J)
0.024;-33800.0
5K(79)
0.014;-38300.0
57(9J)
0.014;-40280.0
57(9K)
0.014;-38300.0
(5T)(7Q)
0.034;-31820.0
5J(7T)
0.018;-39290.0
7T(5J)
0.018;-39290.0
7T(5K)
0.015;-37310.0
7Q(5J)
0.026;-37310.0
(7J)(5K)
0.029;-29840.0
7J(5K)
0.018;-36320.0
7K(5Q)
0.025;-35330.0
57(QK)
0.023;-35330.0
(58)(89)
0.034;-29300.0
8(58Q)
0.025;-32810.0
T(589)
0.018;-40280.0
9(58T)
0.014;-40280.0
9Q(58)
0.022;-38300.0
Q(58T)
0.019;-37310.0
(58)(TQ)
0.036;-30830.0
(58JK)
0.022;-35330.0
JK(58)
0.025;-35330.0
K(58K)
0.040;-26870.0
588T
0.013;-41270.0
58(8K)
0.032;-31820.0
(59)(8J)
0.023;-32810.0
59(89)
0.027;-34790.0
5(89Q)
0.017;-38300.0
58(9T)
0.016;-40280.0
58(9Q)
0.017;-38300.0
8(5TJ)
0.020;-38300.0
8K(5T)
0.025;-36320.0
(8T)(5K)
0.026;-29840.0
8T(5Q)
0.022;-37310.0
(5J)(8J)
0.040;-24350.0
5J(8J)
0.031;-30830.0
8J(5Q)
0.020;-36320.0
(5Q)(8Q)
0.050;-22370.0
5K(8Q)
0.018;-34340.0
5K(8K)
0.042;-26870.0
9J(59)
0.029;-31820.0
(59TJ)
0.015;-37310.0
(59)(TJ)
0.030;-30830.0
J(59J)
0.025;-29840.0
JQ(59)
0.023;-35330.0
Q(59K)
0.021;-33350.0
599T
0.017;-39290.0
59(9K)
0.029;-29840.0
(5T)(9Q)
0.039;-29840.0
5J(9T)
0.017;-37310.0
9T(5J)
0.016;-37310.0
9T(5K)
0.017;-35330.0
9Q(5J)
0.021;-35330.0
(9J)(5K)
0.037;-27860.0
9J(5K)
0.023;-34340.0
9K(5Q)
0.030;-33350.0
59(QK)
0.024;-33350.0
(5T)(TJ)
0.052;-23360.0
J(5TJ)
0.024;-28850.0
JQ(5T)
0.024;-34340.0
Q(5TK)
0.021;-32360.0
5TTJ
0.018;-36320.0
TJ(5J)
0.042;-28850.0
(TJ)(5Q)
0.030;-27860.0
5J(TQ)
0.025;-34340.0
TQ(5Q)
0.035;-26870.0
5TQQ
0.022;-33350.0
5TKK
0.038;-31370.0
Q(5JQ)
0.040;-25880.0
KK(5J)
0.040;-23900.0
(5Q)(JQ)
0.054;-19400.0
5K(JQ)
0.024;-31370.0
5K(JK)
0.056;-23900.0
5QQQ
0.042;-24890.0
KK(5K)
0.076;-15440.0
6669
0.013;-38750.0
666K
0.023;-34790.0
69(67)
0.017;-37760.0
(67)(6Q)
0.031;-28310.0
6678
0.010;-45230.0
66(7J)
0.025;-35780.0
(68)(68)
0.049;-24800.0
6(68J)
0.025;-34790.0
6K(68)
0.030;-32810.0
68(6J)
0.027;-34790.0
668K
0.015;-39290.0
6J(69)
0.028;-33800.0
69(6T)
0.031;-34790.0
669Q
0.015;-39290.0
6J(6T)
0.030;-32810.0
6T(6J)
0.030;-32810.0
66TK
0.019;-37310.0
6K(6J)
0.033;-29840.0
(6Q)(6Q)
0.057;-16880.0
66QK
0.024;-35330.0
7(679)
0.019;-36770.0
7J(67)
0.021;-34790.0
(6789)
0.013;-42260.0
(678K)
0.019;-38300.0
8T(67)
0.014;-41270.0
(67)(8K)
0.022;-31820.0
Q(679)
0.019;-38300.0
(67)(9J)
0.029;-32810.0
T(67T)
0.032;-32810.0
T(67J)
0.023;-38300.0
TK(67)
0.024;-36320.0
(67)(JQ)
0.031;-29840.0
QQ(67)
0.036;-28850.0
67(78)
0.021;-37760.0
77(6J)
0.022;-34790.0
677K
0.017;-39290.0
7T(68)
0.014;-41270.0
(68)(7K)
0.027;-31820.0
6T(78)
0.018;-41270.0
6(78K)
0.022;-38300.0
68(7T)
0.016;-41270.0
68(7Q)
0.012;-39290.0
79(69)
0.024;-34790.0
(69)(7Q)
0.028;-31820.0
6T(79)
0.016;-40280.0
6(79K)
0.017;-37310.0
69(7J)
0.016;-39290.0
69(7K)
0.023;-37310.0
7(6TQ)
0.019;-37310.0
6(7TJ)
0.014;-38300.0
67TT
0.018;-39290.0
67TQ
0.014;-43790.0
(6J)(7Q)
0.028;-29840.0
6Q(7J)
0.026;-36320.0
67JQ
0.012;-42800.0
(6Q)(7K)
0.031;-27860.0
6Q(7K)
0.029;-34340.0
8(689)
0.025;-34790.0
8J(68)
0.028;-32810.0
(689T)
0.016;-39290.0
99(68)
0.023;-33800.0
(68)(9Q)
0.034;-30830.0
(68TQ)
0.025;-36320.0
T(68Q)
0.018;-36320.0
Q(68J)
0.028;-35330.0
(68)(JK)
0.034;-27860.0
QK(68)
0.027;-33350.0
68(8T)
0.020;-33800.0
88(6K)
0.027;-30830.0
8(69J)
0.017;-38300.0
8K(69)
0.017;-36320.0
(89)(6Q)
0.030;-30830.0
69(8T)
0.017;-39290.0
69(8Q)
0.020;-37310.0
8T(6T)
0.025;-31820.0
(6T)(8K)
0.038;-28850.0
6Q(8T)
0.019;-36320.0
68TJ
0.010;-43790.0
68TK
0.013;-41810.0
8K(6J)
0.025;-34340.0
68JJ
0.021;-36320.0
68JK
0.013;-40820.0
6(8QK)
0.025;-33350.0
8K(6K)
0.031;-25880.0
(69)(9J)
0.042;-24350.0
T(69T)
0.033;-30830.0
T(69J)
0.028;-36320.0
TK(69)
0.027;-34340.0
(69)(JQ)
0.034;-27860.0
QQ(69)
0.037;-26870.0
69(9T)
0.030;-31820.0
99(6K)
0.032;-28850.0
9(6TQ)
0.019;-35330.0
6(9TJ)
0.023;-36320.0
69TT
0.018;-37310.0
69TQ
0.010;-41810.0
(6J)(9Q)
0.036;-27860.0
6Q(9J)
0.025;-34340.0
69JQ
0.015;-40820.0
(6Q)(9K)
0.040;-25880.0
6Q(9K)
0.025;-32360.0
T(6TJ)
0.030;-28850.0
TK(6T)
0.036;-26870.0
(6T)(JQ)
0.036;-26870.0
QQ(6T)
0.041;-25880.0
6T(TJ)
0.036;-28850.0
(6J)(TJ)
0.054;-21380.0
6J(TJ)
0.048;-27860.0
TJ(6Q)
0.035;-33350.0
(6Q)(TQ)
0.063;-19400.0
6K(TQ)
0.027;-31370.0
6K(TK)
0.047;-23900.0
JK(6J)
0.044;-24890.0
K(6JK)
0.049;-22910.0
6JJK
0.032;-31370.0
6(JQK)
0.026;-30380.0
JK(6K)
0.039;-22910.0
KK(6Q)
0.057;-21920.0
6QKK
0.026;-28400.0
77(7T)
0.035;-28310.0
(78)(78)
0.043;-22820.0
7(78J)
0.032;-32810.0
7K(78)
0.027;-30830.0
78(7J)
0.026;-32810.0
778K
0.019;-37310.0
7J(79)
0.024;-31820.0
79(7T)
0.029;-32810.0
779Q
0.023;-37310.0
7J(7T)
0.029;-30830.0
7T(7J)
0.029;-30830.0
77TK
0.018;-35330.0
7K(7J)
0.032;-27860.0
(7Q)(7Q)
0.072;-14900.0
77QK
0.021;-33350.0
8(78T)
0.028;-32810.0
8Q(78)
0.027;-30830.0
J(789)
0.019;-37310.0
9T(78)
0.015;-38300.0
(78)(9K)
0.040;-28850.0
K(78T)
0.023;-34340.0
T(78K)
0.019;-34340.0
JJ(78)
0.037;-28850.0
(78QK)
0.028;-32360.0
7888
0.022;-34790.0
78(8J)
0.024;-31820.0
(79)(89)
0.037;-26330.0
8(79Q)
0.020;-36320.0
7(89T)
0.018;-38300.0
(89)(7K)
0.032;-28850.0
89(7J)
0.019;-37310.0
89(7K)
0.023;-35330.0
8J(7T)
0.017;-36320.0
(8T)(7J)
0.038;-29840.0
7K(8T)
0.026;-34340.0
78(TQ)
0.023;-35330.0
8(7JQ)
0.022;-34340.0
7(8JQ)
0.023;-34340.0
78(JQ)
0.022;-34340.0
8(7QK)
0.037;-32360.0
8Q(7K)
0.025;-32360.0
99(79)
0.035;-25340.0
(79)(9Q)
0.059;-22370.0
(79TQ)
0.025;-34340.0
T(79Q)
0.030;-34340.0
Q(79J)
0.022;-33350.0
(79)(JK)
0.037;-25880.0
QK(79)
0.035;-31370.0
79(9J)
0.025;-29840.0
(7T)(9T)
0.039;-23360.0
9(7TK)
0.022;-33350.0
7(9TQ)
0.031;-34340.0
79(TJ)
0.018;-35330.0
79(TK)
0.024;-33350.0
(7J)(9K)
0.043;-25880.0
7K(9J)
0.025;-32360.0
79(JK)
0.023;-32360.0
(9Q)(7K)
0.043;-24890.0
(7K)(9K)
0.051;-17420.0
T(7TQ)
0.036;-26870.0
Q(7TJ)
0.020;-32360.0
(7T)(JK)
0.048;-24890.0
QK(7T)
0.035;-30380.0
7T(TQ)
0.032;-26870.0
(7J)(TQ)
0.032;-25880.0
7Q(TJ)
0.029;-32360.0
7TJQ
0.019;-38840.0
(7Q)(TK)
0.045;-23900.0
7Q(TK)
0.034;-30380.0
J(7JQ)
0.043;-24890.0
K(7JQ)
0.034;-29390.0
JJ(7Q)
0.048;-24890.0
J(7QK)
0.036;-29390.0
JQ(7K)
0.026;-29390.0
QQ(7Q)
0.053;-16430.0
7Q(QK)
0.060;-21920.0
8888
0.041;-27320.0
888Q
0.031;-29840.0
8(89J)
0.024;-29840.0
8K(89)
0.032;-27860.0
89(8Q)
0.029;-28850.0
8(8TJ)
0.034;-28850.0
8K(8T)
0.032;-26870.0
8T(8K)
0.042;-26870.0
8(8JK)
0.032;-25880.0
88(JK)
0.034;-25880.0
8Q(8K)
0.041;-24890.0
(89)(9T)
0.036;-23360.0
9(89K)
0.032;-26870.0
(89TK)
0.024;-32360.0
TQ(89)
0.021;-33350.0
K(89J)
0.025;-31370.0
Q(89Q)
0.034;-24890.0
KK(89)
0.043;-22910.0
99(8Q)
0.035;-27860.0
9(8TJ)
0.021;-34340.0
9K(8T)
0.023;-32360.0
(9T)(8K)
0.041;-25880.0
9T(8Q)
0.025;-33350.0
(8J)(9J)
0.058;-20390.0
8J(9J)
0.037;-26870.0
9J(8Q)
0.025;-32360.0
(8Q)(9Q)
0.053;-18410.0
8K(9Q)
0.026;-30380.0
8K(9K)
0.042;-22910.0
TQ(8T)
0.038;-25880.0
K(8TJ)
0.023;-30380.0
Q(8TQ)
0.043;-23900.0
KK(8T)
0.046;-21920.0
