AAAA
0.094;-510.0
5AAA
0.069;-19106.2
9AAA
0.054;-14321.2
KAAA
0.082;-9536.2
4A(2A)
0.025;-34657.5
(2A)(7A)
0.047;-23238.8
A(2TA)
0.034;-27480.0
QA(2A)
0.044;-25087.5
2A(4A)
0.028;-34657.5
26AA
0.016;-40095.0
AA(29)
0.033;-28676.3
2A(QA)
0.041;-25087.5
A(34A)
0.026;-33461.2
6A(3A)
0.030;-31068.8
(3A)(9A)
0.052;-19650.0
A(3QA)
0.044;-23891.3
AA(34)
0.028;-33461.2
3A(7A)
0.024;-29872.5
39AA
0.030;-35310.0
AA(3Q)
0.033;-23891.3
(4A)(5A)
0.048;-23238.8
A(48A)
0.039;-27480.0
TA(4A)
0.038;-25087.5
(4A)(KA)
0.070;-13668.7
46AA
0.030;-37702.5
AA(49)
0.041;-26283.7
4A(QA)
0.055;-22695.0
A(56A)
0.044;-28676.3
8A(5A)
0.055;-26283.7
(5A)(JA)
0.076;-14865.0
55AA
0.034;-29872.5
AA(58)
0.045;-26283.7
5A(JA)
0.046;-22695.0
5KAA
0.048;-28132.5
8A(6A)
0.052;-25087.5
(6A)(JA)
0.068;-13668.7
66AA
0.037;-27480.0
AA(69)
0.040;-23891.3
6A(QA)
0.063;-20302.5
A(78A)
0.051;-23891.3
TA(7A)
0.055;-21498.8
(7A)(KA)
0.075;-10080.0
79AA
0.034;-30525.0
AA(7Q)
0.069;-19106.3
(8A)(9A)
0.051;-13668.7
A(8QA)
0.054;-17910.0
AA(89)
0.049;-21498.8
8A(QA)
0.055;-17910.0
A(9TA)
0.064;-19106.3
QA(9A)
0.076;-16713.8
9A(JA)
0.061;-17910.0
9KAA
0.047;-23347.5
QA(TA)
0.073;-15517.5
TA(QA)
0.070;-15517.5
A(JQA)
0.067;-14321.3
AA(JQ)
0.071;-14321.3
(QA)(KA)
0.103;-4098.8
KKAA
0.079;-10732.5
2(25A)
0.015;-47816.3
27(2A)
0.016;-45423.8
(2T)(2A)
0.026;-34005.0
2(2KA)
0.020;-38246.2
(236A)
0.009;-53253.8
(23TA)
0.012;-48468.8
33(2A)
0.011;-49012.5
(36)(2A)
0.013;-45423.8
3(29A)
0.011;-49665.0
3J(2A)
0.014;-47272.5
(245A)
0.009;-53253.8
(249A)
0.012;-48468.8
(24KA)
0.016;-43683.8
46(2A)
0.011;-52057.5
(49)(2A)
0.015;-40638.8
4(2QA)
0.013;-44880.0
6(25A)
0.010;-50861.3
T(25A)
0.012;-46076.2
5(26A)
0.009;-50861.3
58(2A)
0.017;-48468.8
(5J)(2A)
0.024;-37050.0
6(26A)
0.021;-41835.0
T(26A)
0.014;-44880.0
6(27A)
0.013;-48468.8
69(2A)
0.015;-46076.2
(6Q)(2A)
0.029;-34657.5
(279A)
0.019;-44880.0
(27KA)
0.015;-40095.0
79(2A)
0.015;-44880.0
(7Q)(2A)
0.026;-33461.3
(28TA)
0.018;-42487.5
88(2A)
0.028;-37050.0
(8J)(2A)
0.030;-33461.3
9(29A)
0.023;-34657.5
K(29A)
0.022;-37702.5
9(2QA)
0.026;-38898.8
J(2TA)
0.026;-38898.8
TJ(2A)
0.021;-38898.8
(2JQA)
0.028;-36506.2
J(2KA)
0.028;-35310.0
(QK)(2A)
0.041;-26283.7
22(4A)
0.012;-49012.5
226A
0.007;-54450.0
2A(29)
0.018;-43031.2
22(QA)
0.017;-39442.5
2(34A)
0.009;-55646.2
26(3A)
0.008;-53253.8
(29)(3A)
0.022;-41835.0
2(3QA)
0.014;-46076.2
A(234)
0.006;-55646.2
(23)(7A)
0.018;-44227.5
9A(23)
0.009;-49665.0
A(23Q)
0.012;-46076.2
2A(34)
0.008;-55646.2
2A(36)
0.007;-53253.8
2A(38)
0.011;-50861.3
2A(3T)
0.015;-48468.8
2A(3Q)
0.015;-46076.2
2(45A)
0.009;-53253.8
27(4A)
0.009;-50861.3
(2T)(4A)
0.027;-39442.5
2(4KA)
0.018;-43683.8
A(246)
0.010;-52057.5
(24)(9A)
0.014;-40638.8
JA(24)
0.013;-46076.2
24(5A)
0.008;-53253.8
24(7A)
0.009;-50861.3
24(9A)
0.016;-48468.8
24(JA)
0.012;-46076.2
24(KA)
0.015;-43683.8
26(5A)
0.014;-50861.3
(29)(5A)
0.028;-39442.5
2(5QA)
0.014;-43683.8
A(256)
0.010;-50861.3
(25)(9A)
0.021;-39442.5
JA(25)
0.017;-44880.0
25(6A)
0.011;-50861.3
25(8A)
0.016;-48468.8
25(TA)
0.014;-46076.2
25(QA)
0.013;-43683.8
(26)(6A)
0.023;-34005.0
2(69A)
0.015;-46076.2
2J(6A)
0.013;-43683.8
(26)(7A)
0.014;-40638.8
9A(26)
0.014;-46076.2
A(26Q)
0.020;-42487.5
2A(67)
0.012;-48468.8
2A(69)
0.018;-46076.2
2A(6J)
0.017;-43683.8
2A(6K)
0.021;-41291.3
(29)(7A)
0.026;-37050.0
2(7QA)
0.018;-41291.3
A(278)
0.012;-46076.2
(27)(JA)
0.026;-34657.5
KA(27)
0.028;-40095.0
2A(79)
0.015;-44880.0
2A(7J)
0.015;-42487.5
2A(7K)
0.018;-40095.0
(2T)(8A)
0.021;-34657.5
2(8KA)
0.020;-38898.8
A(28T)
0.014;-42487.5
(28)(KA)
0.033;-31068.8
28(TA)
0.020;-42487.5
28(QA)
0.022;-40095.0
(29)(9A)
0.040;-26827.5
2(9QA)
0.026;-38898.8
A(29T)
0.015;-41291.3
(29)(KA)
0.034;-29872.5
29(JA)
0.017;-40095.0
29(KA)
0.023;-37702.5
2J(TA)
0.021;-38898.8
(2T)(JA)
0.032;-31068.8
KA(2T)
0.023;-36506.2
2A(TQ)
0.025;-37702.5
2(JQA)
0.026;-36506.2
A(2JQ)
0.032;-36506.2
2A(JQ)
0.024;-36506.2
2(QKA)
0.027;-34113.7
2Q(KA)
0.037;-34113.7
33(3A)
0.024;-39986.3
(36)(3A)
0.022;-36397.5
3(39A)
0.021;-40638.8
3J(3A)
0.020;-38246.2
(345A)
0.009;-52057.5
(349A)
0.009;-47272.5
(34KA)
0.023;-42487.5
46(3A)
0.012;-50861.3
(49)(3A)
0.020;-39442.5
4(3QA)
0.017;-43683.8
6(35A)
0.012;-49665.0
T(35A)
0.020;-44880.0
5(36A)
0.012;-49665.0
58(3A)
0.016;-47272.5
(5J)(3A)
0.030;-35853.8
6(36A)
0.020;-40638.8
T(36A)
0.020;-43683.8
6(37A)
0.013;-47272.5
69(3A)
0.015;-44880.0
(6Q)(3A)
0.033;-33461.3
(379A)
0.015;-43683.8
(37KA)
0.019;-38898.8
79(3A)
0.016;-43683.8
(7Q)(3A)
0.027;-32265.0
(38TA)
0.014;-41291.3
88(3A)
0.021;-35853.8
(8J)(3A)
0.029;-32265.0
9(39A)
0.031;-33461.2
K(39A)
0.020;-36506.2
9(3QA)
0.020;-37702.5
J(3TA)
0.022;-37702.5
TJ(3A)
0.024;-37702.5
(3JQA)
0.033;-35310.0
J(3KA)
0.031;-34113.7
(QK)(3A)
0.041;-25087.5
33(5A)
0.014;-45423.8
337A
0.009;-50861.3
3A(3T)
0.027;-39442.5
33(KA)
0.024;-35853.8
3(46A)
0.011;-50861.3
38(4A)
0.011;-48468.8
(3J)(4A)
0.028;-37050.0
4A(34)
0.017;-45423.8
A(347)
0.011;-49665.0
(34)(TA)
0.021;-38246.2
QA(34)
0.021;-43683.8
345A
0.007;-59887.5
347A
0.005;-57495.0
349A
0.008;-55102.5
34JA
0.007;-52710.0
34KA
0.012;-50317.5
37(5A)
0.013;-48468.8
(3T)(5A)
0.019;-37050.0
3(5KA)
0.023;-41291.3
A(357)
0.013;-48468.8
(35)(TA)
0.027;-37050.0
QA(35)
0.017;-42487.5
356A
0.006;-57495.0
358A
0.009;-55102.5
35TA
0.009;-52710.0
35QA
0.011;-50317.5
(37)(6A)
0.019;-39442.5
3(6TA)
0.012;-43683.8
3Q(6A)
0.016;-41291.3
(36)(8A)
0.022;-38246.2
TA(36)
0.018;-43683.8
A(36K)
0.019;-40095.0
6A(38)
0.012;-46076.2
6A(3T)
0.018;-43683.8
6A(3Q)
0.020;-41291.3
37(7A)
0.027;-38246.2
(3T)(7A)
0.024;-34657.5
3(7KA)
0.021;-38898.8
A(379)
0.020;-43683.8
(37)(QA)
0.027;-32265.0
7A(38)
0.014;-44880.0
7A(3T)
0.017;-42487.5
7A(3Q)
0.024;-40095.0
38(8A)
0.022;-35853.8
(3J)(8A)
0.031;-32265.0
8A(38)
0.028;-35853.8
A(38J)
0.016;-40095.0
388A
0.021;-43683.8
38TA
0.012;-49121.2
38QA
0.014;-46728.8
(3T)(9A)
0.033;-32265.0
3(9KA)
0.025;-36506.2
A(39J)
0.024;-38898.8
399A
0.019;-41291.3
39JA
0.010;-46728.8
39KA
0.016;-44336.2
3Q(TA)
0.031;-36506.2
(3T)(QA)
0.032;-28676.3
TA(3J)
0.018;-37702.5
TA(3K)
0.025;-35310.0
3(JKA)
0.027;-34113.7
A(3JK)
0.029;-34113.7
JA(3K)
0.021;-34113.7
QA(3Q)
0.043;-26283.7
3QKA
0.020;-40747.5
45(4A)
0.015;-43031.2
(48)(4A)
0.032;-31612.5
4(4JA)
0.021;-35853.8
4K(4A)
0.025;-33461.2
(459A)
0.016;-44880.0
(45KA)
0.018;-40095.0
57(4A)
0.015;-47272.5
(5T)(4A)
0.031;-35853.8
5(4KA)
0.022;-40095.0
(469A)
0.019;-43683.8
(46KA)
0.020;-38898.8
68(4A)
0.014;-44880.0
(6J)(4A)
0.035;-33461.3
7(47A)
0.020;-37050.0
J(47A)
0.026;-40095.0
78(4A)
0.019;-43683.8
(7J)(4A)
0.022;-32265.0
8(48A)
0.031;-34657.5
Q(48A)
0.022;-37702.5
(8T)(4A)
0.029;-32265.0
8(4KA)
0.027;-36506.2
(49QA)
0.036;-36506.2
9(4JA)
0.025;-37702.5
9K(4A)
0.028;-35310.0
TT(4A)
0.035;-29872.5
(TK)(4A)
0.040;-26283.7
J(4QA)
0.023;-34113.7
K(4QA)
0.028;-31721.2
44(5A)
0.014;-43031.2
447A
0.010;-48468.8
4A(4T)
0.019;-37050.0
44(KA)
0.034;-33461.2
4(57A)
0.014;-47272.5
49(5A)
0.018;-44880.0
(4Q)(5A)
0.030;-33461.3
6A(45)
0.012;-48468.8
A(459)
0.013;-44880.0
(45)(QA)
0.029;-33461.3
5A(46)
0.013;-48468.8
5A(48)
0.016;-46076.2
5A(4T)
0.015;-43683.8
5A(4Q)
0.024;-41291.3
46(6A)
0.018;-39442.5
(49)(6A)
0.028;-35853.8
4(6QA)
0.022;-40095.0
A(467)
0.014;-46076.2
(46)(TA)
0.026;-34657.5
QA(46)
0.025;-40095.0
467A
0.008;-53906.2
469A
0.009;-51513.8
46JA
0.014;-49121.2
46KA
0.013;-46728.8
49(7A)
0.016;-42487.5
(4Q)(7A)
0.038;-31068.8
8A(47)
0.016;-43683.8
A(47J)
0.020;-40095.0
477A
0.012;-44880.0
479A
0.011;-50317.5
47JA
0.011;-47925.0
47KA
0.016;-45532.5
4T(8A)
0.026;-40095.0
(4K)(8A)
0.028;-28676.3
TA(48)
0.024;-40095.0
A(48K)
0.028;-36506.2
8A(4T)
0.026;-40095.0
8A(4Q)
0.027;-37702.5
49(9A)
0.034;-32265.0
(4Q)(9A)
0.032;-28676.3
TA(49)
0.023;-38898.8
A(49K)
0.026;-35310.0
9A(4J)
0.023;-37702.5
9A(4K)
0.032;-35310.0
4(TQA)
0.023;-35310.0
A(4TJ)
0.022;-36506.2
4TTA
0.026;-37702.5
4TQA
0.018;-43140.0
(4Q)(JA)
0.038;-26283.7
QA(4J)
0.026;-34113.7
4JQA
0.025;-41943.8
(4K)(QA)
0.055;-23891.3
QA(4K)
0.034;-31721.2
5(56A)
0.028;-39442.5
58(5A)
0.028;-37050.0
(5J)(5A)
0.041;-25631.2
6(56A)
0.018;-38246.2
T(56A)
0.021;-41291.3
6(57A)
0.018;-44880.0
69(5A)
0.021;-42487.5
(6Q)(5A)
0.032;-31068.8
(579A)
0.019;-41291.3
(57KA)
0.021;-36506.2
79(5A)
0.019;-41291.3
(7Q)(5A)
0.043;-29872.5
(58TA)
0.019;-38898.8
88(5A)
0.033;-33461.2
(8J)(5A)
0.033;-29872.5
9(59A)
0.031;-31068.8
K(59A)
0.033;-34113.7
9(5QA)
0.034;-35310.0
J(5TA)
0.031;-35310.0
TJ(5A)
0.033;-35310.0
(5JQA)
0.038;-32917.5
J(5KA)
0.028;-31721.2
(QK)(5A)
0.039;-22695.0
55(7A)
0.018;-38246.2
559A
0.014;-43683.8
5A(5Q)
0.033;-32265.0
(57)(6A)
0.026;-37050.0
5(6TA)
0.017;-41291.3
5Q(6A)
0.025;-38898.8
(56)(8A)
0.028;-35853.8
TA(56)
0.018;-41291.3
A(56K)
0.019;-37702.5
6A(58)
0.019;-43683.8
6A(5T)
0.015;-41291.3
6A(5Q)
0.019;-38898.8
57(7A)
0.022;-35853.8
(5T)(7A)
0.031;-32265.0
5(7KA)
0.024;-36506.2
A(579)
0.017;-41291.3
(57)(QA)
0.036;-29872.5
7A(58)
0.020;-42487.5
7A(5T)
0.021;-40095.0
7A(5Q)
0.019;-37702.5
58(8A)
0.024;-33461.2
(5J)(8A)
0.038;-29872.5
8A(58)
0.028;-33461.2
A(58J)
0.020;-37702.5
588A
0.018;-41291.3
58TA
0.012;-46728.8
58QA
0.017;-44336.2
(5T)(9A)
0.032;-29872.5
5(9KA)
0.029;-34113.7
A(59J)
0.026;-36506.2
599A
0.024;-38898.8
59JA
0.013;-44336.2
59KA
0.023;-41943.8
5Q(TA)
0.030;-34113.7
(5T)(QA)
0.043;-26283.7
TA(5J)
0.031;-35310.0
TA(5K)
0.025;-32917.5
5(JKA)
0.031;-31721.2
A(5JK)
0.028;-31721.2
JA(5K)
0.030;-31721.2
QA(5Q)
0.032;-23891.3
5QKA
0.025;-38355.0
67(6A)
0.027;-35853.8
(6T)(6A)
0.040;-24435.0
6(6KA)
0.043;-28676.3
(67TA)
0.027;-38898.8
77(6A)
0.032;-34657.5
(7T)(6A)
0.028;-31068.8
7(6KA)
0.028;-35310.0
(68JA)
0.024;-36506.2
(89)(6A)
0.034;-31068.8
8(6QA)
0.035;-35310.0
T(69A)
0.022;-36506.2
9(6TA)
0.022;-36506.2
9Q(6A)
0.024;-34113.7
Q(6TA)
0.030;-32917.5
(TQ)(6A)
0.038;-25087.5
(6JKA)
0.028;-30525.0
JK(6A)
0.035;-30525.0
K(6KA)
0.057;-20302.5
668A
0.021;-42487.5
6A(6J)
0.040;-31068.8
(67)(7A)
0.041;-26827.5
6(7TA)
0.025;-38898.8
6Q(7A)
0.026;-36506.2
(67)(9A)
0.024;-32265.0
JA(67)
0.022;-37702.5
67(8A)
0.019;-41291.3
67(TA)
0.023;-38898.8
67(QA)
0.024;-36506.2
(68)(8A)
0.037;-24435.0
6(8JA)
0.022;-36506.2
6K(8A)
0.030;-34113.7
(68)(JA)
0.032;-28676.3
KA(68)
0.023;-34113.7
6A(8T)
0.021;-37702.5
6A(8Q)
0.029;-35310.0
6(9TA)
0.024;-36506.2
6Q(9A)
0.028;-34113.7
(69)(JA)
0.030;-27480.0
KA(69)
0.035;-32917.5
6A(9J)
0.033;-35310.0
6A(9K)
0.033;-32917.5
(6Q)(TA)
0.045;-25087.5
JA(6T)
0.022;-34113.7
6T(JA)
0.027;-34113.7
6T(KA)
0.035;-31721.2
6Q(JA)
0.027;-31721.2
(6J)(KA)
0.052;-22695.0
6J(KA)
0.027;-30525.0
6K(QA)
0.030;-29328.8
6A(QK)
0.037;-29328.8
(78)(7A)
0.042;-24435.0
7(7JA)
0.029;-28676.3
7K(7A)
0.047;-26283.7
(78QA)
0.029;-34113.7
8(7TA)
0.034;-36506.2
8Q(7A)
0.022;-34113.7
J(79A)
0.033;-34113.7
9T(7A)
0.027;-35310.0
(9K)(7A)
0.043;-23891.3
K(7TA)
0.038;-30525.0
T(7KA)
0.039;-30525.0
JJ(7A)
0.042;-23891.3
(7QKA)
0.029;-28132.5
777A
0.028;-33461.3
7A(7T)
0.039;-29872.5
77(KA)
0.046;-26283.7
7(8TA)
0.022;-36506.2
7Q(8A)
0.028;-34113.7
(78)(TA)
0.032;-28676.3
QA(78)
0.027;-34113.7
789A
0.018;-45532.5
78JA
0.016;-43140.0
78KA
0.016;-40747.5
7J(9A)
0.032;-34113.7
(79)(TA)
0.041;-27480.0
QA(79)
0.035;-32917.5
79TA
0.018;-43140.0
79QA
0.018;-40747.5
(7J)(TA)
0.054;-25087.5
TA(7T)
0.050;-26283.7
A(7TK)
0.042;-30525.0
TA(7Q)
0.042;-31721.2
7J(JA)
0.038;-23891.3
(7J)(QA)
0.046;-22695.0
JA(7Q)
0.045;-30525.0
7Q(QA)
0.056;-21498.8
7QQA
0.031;-29328.8
7KKA
0.048;-26936.3
8(8JA)
0.048;-26283.7
8K(8A)
0.051;-23891.3
(89KA)
0.032;-30525.0
9J(8A)
0.029;-32917.5
(8TJA)
0.031;-31721.2
(TJ)(8A)
0.043;-23891.3
J(8JA)
0.051;-22695.0
JQ(8A)
0.039;-29328.8
Q(8KA)
0.036;-26936.3
889A
0.029;-36506.2
8A(8Q)
0.042;-25087.5
(8T)(9A)
0.034;-26283.7
8(9KA)
0.032;-30525.0
A(89J)
0.026;-32917.5
899A
0.021;-35310.0
89JA
0.022;-40747.5
89KA
0.023;-38355.0
8Q(TA)
0.034;-30525.0
(8T)(QA)
0.046;-22695.0
TA(8J)
0.030;-31721.2
TA(8K)
0.045;-29328.8
8(JKA)
0.043;-28132.5
A(8JK)
0.035;-28132.5
JA(8K)
0.042;-28132.5
QA(8Q)
0.067;-20302.5
8QKA
0.024;-34766.2
9T(9A)
0.055;-25087.5
(9K)(9A)
0.071;-13668.7
K(9TA)
0.039;-28132.5
T(9KA)
0.042;-28132.5
JJ(9A)
0.042;-21498.8
(9QKA)
0.036;-25740.0
999A
0.030;-26283.7
9A(9Q)
0.062;-22695.0
(9J)(TA)
0.051;-22695.0
TA(9T)
0.036;-23891.3
A(9TK)
0.034;-28132.5
TA(9Q)
0.048;-29328.8
9J(JA)
0.050;-21498.8
(9J)(QA)
0.066;-20302.5
JA(9Q)
0.041;-28132.5
9Q(QA)
0.073;-19106.3
9QQA
0.048;-26936.3
9KKA
0.041;-24543.8
T(TKA)
0.055;-19106.3
JJ(TA)
0.053;-20302.5
(TQKA)
0.043;-24543.8
TTTA
0.047;-22695.0
TA(TK)
0.049;-19106.3
(TK)(JA)
0.069;-17910.0
KA(TJ)
0.040;-25740.0
TA(JK)
0.041;-25740.0
(TQ)(KA)
0.062;-16713.8
(TK)(KA)
0.088;-7687.5
J(JKA)
0.062;-16713.8
(QK)(JA)
0.064;-15517.5
JJ(KA)
0.045;-16713.8
QA(JQ)
0.058;-16713.8
JQKA
0.029;-31177.5
QK(QA)
0.087;-14321.3
QK(KA)
0.069;-13125.0
22(24)
0.010;-55537.5
22(28)
0.010;-50752.5
22(2Q)
0.013;-45967.5
24(23)
0.003;-62171.2
(23)(27)
0.014;-50752.5
2(23T)
0.009;-54993.8
2Q(23)
0.010;-52601.3
23(25)
0.005;-60975.0
2237
0.003;-66412.5
22(3T)
0.008;-54993.8
23(2K)
0.010;-51405.0
2(246)
0.004;-58582.5
28(24)
0.007;-56190.0
(24)(2J)
0.016;-44771.2
2244
0.005;-60975.0
22(47)
0.006;-57386.3
24(2T)
0.008;-53797.5
224Q
0.006;-59235.0
26(25)
0.006;-57386.3
(25)(29)
0.018;-45967.5
2(25Q)
0.009;-50208.8
22(56)
0.007;-57386.3
25(29)
0.007;-53797.5
225J
0.006;-59235.0
26(26)
0.013;-48360.0
(26)(29)
0.018;-44771.2
2(26Q)
0.015;-49012.5
22(67)
0.008;-54993.8
26(2T)
0.011;-51405.0
226Q
0.006;-56842.5
28(27)
0.012;-52601.3
(27)(2J)
0.016;-41182.5
2277
0.008;-53797.5
22(7T)
0.011;-50208.8
27(2K)
0.014;-46620.0
2(28T)
0.011;-49012.5
2Q(28)
0.014;-46620.0
28(2T)
0.011;-49012.5
228Q
0.009;-54450.0
2T(29)
0.012;-47816.3
(29)(2K)
0.024;-36397.5
229J
0.008;-54450.0
2T(2T)
0.022;-38790.0
(2T)(2K)
0.027;-35201.2
22TQ
0.010;-52057.5
2Q(2J)
0.016;-43031.2
2J(2K)
0.020;-41835.0
22QQ
0.024;-41835.0
3(234)
0.005;-60975.0
36(23)
0.006;-58582.5
(23)(39)
0.012;-47163.8
3(23Q)
0.013;-51405.0
5(234)
0.002;-66412.5
9(234)
0.004;-61627.5
K(234)
0.006;-56842.5
4(237)
0.004;-64020.0
49(23)
0.005;-61627.5
(23)(4Q)
0.012;-50208.8
(2357)
0.005;-62823.8
(235J)
0.007;-58038.8
(23)(56)
0.006;-56190.0
5(239)
0.005;-60431.3
5J(23)
0.008;-58038.8
(2367)
0.003;-61627.5
(236J)
0.006;-56842.5
(23)(67)
0.010;-53797.5
6(23T)
0.005;-58038.8
6Q(23)
0.007;-55646.2
9(237)
0.005;-58038.8
K(237)
0.010;-53253.8
7(23T)
0.007;-56842.5
7Q(23)
0.007;-54450.0
T(238)
0.007;-55646.2
8(239)
0.007;-56842.5
8J(23)
0.008;-54450.0
(239T)
0.009;-54450.0
99(23)
0.015;-47816.3
(23)(9Q)
0.017;-44227.5
(23TQ)
0.011;-50861.3
T(23Q)
0.011;-50861.3
Q(23J)
0.012;-49665.0
(23)(JK)
0.022;-40638.8
QK(23)
0.016;-47272.5
23(35)
0.004;-59778.8
33(28)
0.007;-56190.0
233T
0.003;-61627.5
23(3K)
0.011;-50208.8
(24)(36)
0.005;-57386.3
3(249)
0.003;-61627.5
3J(24)
0.005;-59235.0
(34)(25)
0.005;-58582.5
27(34)
0.002;-64020.0
2(34T)
0.005;-60431.3
(34)(2K)
0.010;-49012.5
34(26)
0.002;-65216.2
34(28)
0.004;-62823.8
34(2T)
0.005;-60431.3
34(2Q)
0.006;-58038.8
(25)(35)
0.013;-49556.3
3(258)
0.005;-61627.5
3T(25)
0.006;-59235.0
(25)(3K)
0.010;-47816.3
27(35)
0.004;-62823.8
2(35T)
0.005;-59235.0
(35)(2K)
0.012;-47816.3
35(27)
0.004;-62823.8
35(29)
0.005;-60431.3
35(2J)
0.005;-58038.8
35(2K)
0.008;-55646.2
37(26)
0.003;-61627.5
(26)(3T)
0.010;-50208.8
3(26K)
0.008;-54450.0
2(368)
0.005;-60431.3
(36)(2J)
0.010;-49012.5
2K(36)
0.008;-54450.0
23(68)
0.006;-60431.3
23(6T)
0.005;-58038.8
23(6Q)
0.005;-55646.2
3(278)
0.006;-59235.0
3T(27)
0.007;-56842.5
(27)(3K)
0.015;-45423.8
29(37)
0.005;-58038.8
2(37Q)
0.008;-54450.0
23(78)
0.005;-59235.0
23(7T)
0.006;-56842.5
23(7Q)
0.008;-54450.0
3(289)
0.008;-56842.5
3J(28)
0.007;-54450.0
(38)(29)
0.013;-49012.5
2J(38)
0.009;-54450.0
38(29)
0.006;-56842.5
38(2J)
0.009;-54450.0
38(2K)
0.009;-52057.5
3T(29)
0.007;-54450.0
(29)(3K)
0.018;-43031.3
2J(39)
0.007;-53253.8
39(2T)
0.010;-54450.0
39(2Q)
0.009;-52057.5
(2T)(3T)
0.020;-37593.8
3(2TK)
0.011;-49665.0
2(3TQ)
0.009;-50861.3
23(TJ)
0.012;-52057.5
23(TK)
0.010;-49665.0
(2J)(3K)
0.023;-40638.8
2K(3J)
0.014;-48468.8
23(JK)
0.013;-48468.8
(3Q)(2K)
0.027;-39442.5
(2K)(3K)
0.027;-30416.3
4(246)
0.007;-56190.0
48(24)
0.008;-53797.5
(24)(4J)
0.019;-42378.8
5(245)
0.009;-56190.0
9(245)
0.006;-59235.0
K(245)
0.009;-54450.0
5(248)
0.003;-60431.3
5T(24)
0.006;-58038.8
(24)(5K)
0.017;-46620.0
9(246)
0.005;-58038.8
K(246)
0.010;-53253.8
6(249)
0.005;-58038.8
6J(24)
0.008;-55646.2
(2478)
0.006;-58038.8
(247Q)
0.011;-53253.8
7(249)
0.005;-56842.5
7J(24)
0.007;-54450.0
(2489)
0.007;-55646.2
(248K)
0.009;-50861.3
8T(24)
0.008;-54450.0
(24)(8K)
0.018;-43031.3
Q(249)
0.011;-50861.3
(24)(9J)
0.018;-44227.5
T(24T)
0.019;-44227.5
T(24J)
0.008;-50861.3
TK(24)
0.011;-48468.8
(24)(JQ)
0.022;-40638.8
QQ(24)
0.021;-39442.5
24(45)
0.006;-57386.3
44(28)
0.007;-53797.5
244T
0.006;-59235.0
24(4K)
0.016;-47816.3
(25)(47)
0.007;-53797.5
4(25T)
0.006;-58038.8
4Q(25)
0.006;-55646.2
(45)(27)
0.011;-53797.5
29(45)
0.005;-59235.0
2(45Q)
0.009;-55646.2
24(56)
0.005;-62823.8
24(58)
0.006;-60431.3
24(5T)
0.007;-58038.8
24(5Q)
0.007;-55646.2
4(267)
0.004;-60431.3
49(26)
0.006;-58038.8
(26)(4Q)
0.012;-46620.0
27(46)
0.004;-60431.3
2(46T)
0.008;-56842.5
(46)(2K)
0.016;-45423.8
46(28)
0.007;-59235.0
46(2T)
0.007;-56842.5
46(2Q)
0.006;-54450.0
(27)(47)
0.018;-43575.0
4(27T)
0.006;-55646.2
4Q(27)
0.007;-53253.8
(47)(29)
0.012;-49012.5
2J(47)
0.009;-54450.0
47(28)
0.005;-58038.8
47(2T)
0.006;-55646.2
47(2Q)
0.009;-53253.8
(28)(48)
0.019;-41182.5
4(28J)
0.008;-53253.8
4K(28)
0.008;-50861.3
(48)(2J)
0.014;-45423.8
2K(48)
0.010;-50861.3
24(8T)
0.008;-54450.0
24(8Q)
0.007;-52057.5
4(29T)
0.009;-53253.8
4Q(29)
0.011;-50861.3
(49)(2J)
0.013;-44227.5
2K(49)
0.013;-49665.0
24(9J)
0.009;-52057.5
24(9K)
0.011;-49665.0
(2T)(4Q)
0.017;-41835.0
2J(4T)
0.012;-50861.3
4T(2J)
0.010;-50861.3
4T(2K)
0.012;-48468.8
4Q(2J)
0.011;-48468.8
(4J)(2K)
0.018;-39442.5
4J(2K)
0.014;-47272.5
4K(2Q)
0.016;-46076.2
24(QK)
0.014;-46076.2
(25)(56)
0.013;-45967.5
5(259)
0.011;-50208.8
5J(25)
0.013;-47816.3
(2567)
0.007;-59235.0
(256J)
0.009;-54450.0
(25)(67)
0.008;-51405.0
6(25T)
0.009;-55646.2
6Q(25)
0.009;-53253.8
9(257)
0.008;-55646.2
K(257)
0.011;-50861.3
7(25T)
0.009;-54450.0
7Q(25)
0.009;-52057.5
T(258)
0.006;-53253.8
8(259)
0.008;-54450.0
8J(25)
0.010;-52057.5
(259T)
0.009;-52057.5
99(25)
0.017;-45423.8
(25)(9Q)
0.016;-41835.0
(25TQ)
0.013;-48468.8
T(25Q)
0.011;-48468.8
Q(25J)
0.012;-47272.5
(25)(JK)
0.023;-38246.2
QK(25)
0.016;-44880.0
25(57)
0.011;-52601.3
55(2T)
0.009;-49012.5
255Q
0.008;-54450.0
57(26)
0.005;-59235.0
(26)(5T)
0.013;-47816.3
5(26K)
0.007;-52057.5
2(568)
0.006;-58038.8
(56)(2J)
0.014;-46620.0
2K(56)
0.009;-52057.5
25(68)
0.006;-58038.8
25(6T)
0.008;-55646.2
25(6Q)
0.009;-53253.8
5(278)
0.006;-56842.5
5T(27)
0.007;-54450.0
(27)(5K)
0.017;-43031.3
29(57)
0.009;-55646.2
2(57Q)
0.008;-52057.5
25(78)
0.006;-56842.5
25(7T)
0.009;-54450.0
25(7Q)
0.009;-52057.5
5(289)
0.007;-54450.0
5J(28)
0.007;-52057.5
(58)(29)
0.014;-46620.0
2J(58)
0.010;-52057.5
58(29)
0.008;-54450.0
58(2J)
0.009;-52057.5
58(2K)
0.011;-49665.0
5T(29)
0.010;-52057.5
(29)(5K)
0.020;-40638.8
2J(59)
0.011;-50861.3
59(2T)
0.012;-52057.5
59(2Q)
0.011;-49665.0
(2T)(5T)
0.025;-35201.2
5(2TK)
0.012;-47272.5
2(5TQ)
0.012;-48468.8
25(TJ)
0.011;-49665.0
25(TK)
0.013;-47272.5
(2J)(5K)
0.021;-38246.2
2K(5J)
0.014;-46076.2
25(JK)
0.012;-46076.2
(5Q)(2K)
0.021;-37050.0
(2K)(5K)
0.042;-28023.8
6(268)
0.011;-49012.5
6T(26)
0.014;-46620.0
(26)(6K)
0.026;-35201.2
T(267)
0.009;-53253.8
7(268)
0.008;-55646.2
7T(26)
0.009;-53253.8
(26)(7K)
0.020;-41835.0
J(268)
0.009;-50861.3
89(26)
0.009;-53253.8
(26)(8Q)
0.021;-41835.0
(269J)
0.010;-49665.0
(26)(9T)
0.016;-43031.3
9(26K)
0.014;-47272.5
(26TK)
0.010;-46076.2
TQ(26)
0.015;-47272.5
K(26J)
0.019;-44880.0
Q(26Q)
0.028;-37050.0
KK(26)
0.031;-34657.5
66(29)
0.010;-47816.3
266J
0.011;-53253.8
67(27)
0.015;-49012.5
(27)(6T)
0.012;-45423.8
6(27K)
0.011;-49665.0
2(679)
0.009;-54450.0
(67)(2Q)
0.019;-43031.3
27(68)
0.007;-55646.2
27(6T)
0.007;-53253.8
27(6Q)
0.011;-50861.3
68(28)
0.014;-46620.0
(28)(6J)
0.016;-43031.3
28(68)
0.013;-46620.0
2(68J)
0.008;-50861.3
2688
0.008;-54450.0
268T
0.004;-59887.5
268Q
0.007;-57495.0
(29)(6T)
0.017;-43031.3
6(29K)
0.016;-47272.5
2(69J)
0.012;-49665.0
2699
0.008;-52057.5
269J
0.006;-57495.0
269K
0.007;-55102.5
6Q(2T)
0.016;-47272.5
(6T)(2Q)
0.021;-39442.5
2T(6J)
0.012;-48468.8
2T(6K)
0.014;-46076.2
6(2JK)
0.017;-44880.0
2(6JK)
0.013;-44880.0
2J(6K)
0.019;-44880.0
2Q(6Q)
0.031;-37050.0
26QK
0.009;-51513.8
78(27)
0.014;-46620.0
(27)(7J)
0.023;-35201.2
8(278)
0.015;-45423.8
Q(278)
0.012;-48468.8
(27)(8T)
0.016;-43031.3
8(27K)
0.014;-47272.5
(279Q)
0.013;-47272.5
9(27J)
0.009;-48468.8
9K(27)
0.016;-46076.2
TT(27)
0.016;-40638.8
(27)(TK)
0.024;-37050.0
J(27Q)
0.021;-44880.0
K(27Q)
0.015;-42487.5
77(28)
0.015;-46620.0
277T
0.009;-52057.5
27(7K)
0.022;-40638.8
(28)(7T)
0.018;-43031.3
7(28K)
0.015;-47272.5
2(78T)
0.013;-50861.3
(78)(2K)
0.022;-39442.5
78(2T)
0.011;-50861.3
78(2Q)
0.010;-48468.8
(29)(79)
0.037;-35201.2
7(29Q)
0.015;-47272.5
2(79T)
0.010;-49665.0
(79)(2K)
0.020;-38246.2
79(2J)
0.014;-48468.8
79(2K)
0.013;-46076.2
7J(2T)
0.015;-47272.5
(7T)(2J)
0.023;-39442.5
2K(7T)
0.015;-44880.0
27(TQ)
0.014;-46076.2
7(2JQ)
0.017;-44880.0
2(7JQ)
0.017;-44880.0
27(JQ)
0.014;-44880.0
7(2QK)
0.019;-42487.5
7Q(2K)
0.016;-42487.5
88(28)
0.033;-36397.5
(28)(8J)
0.030;-32808.7
9(289)
0.018;-41835.0
K(289)
0.016;-44880.0
9(28Q)
0.012;-46076.2
J(28T)
0.016;-46076.2
TJ(28)
0.017;-46076.2
(28JQ)
0.017;-43683.8
J(28K)
0.017;-42487.5
(28)(QK)
0.026;-33461.3
88(2T)
0.019;-41835.0
288Q
0.012;-47272.5
8T(29)
0.014;-48468.8
(29)(8K)
0.023;-37050.0
2J(89)
0.015;-47272.5
89(2T)
0.014;-48468.8
89(2Q)
0.017;-46076.2
(2T)(8T)
0.026;-31612.5
8(2TK)
0.017;-43683.8
2(8TQ)
0.014;-44880.0
28(TJ)
0.013;-46076.2
28(TK)
0.020;-43683.8
(2J)(8K)
0.020;-34657.5
2K(8J)
0.014;-42487.5
28(JK)
0.016;-42487.5
(8Q)(2K)
0.031;-33461.3
(2K)(8K)
0.054;-24435.0
9(29J)
0.024;-38246.2
9K(29)
0.025;-35853.8
TT(29)
0.022;-38246.2
(29)(TK)
0.034;-34657.5
J(29Q)
0.016;-42487.5
K(29Q)
0.017;-40095.0
99(2T)
0.019;-39442.5
299Q
0.019;-44880.0
9J(2T)
0.013;-44880.0
(9T)(2J)
0.022;-37050.0
2K(9T)
0.025;-42487.5
29(TQ)
0.014;-43683.8
9(2JQ)
0.020;-42487.5
2(9JQ)
0.019;-42487.5
29(JQ)
0.015;-42487.5
9(2QK)
0.017;-40095.0
9Q(2K)
0.017;-40095.0
TT(2T)
0.034;-29220.0
(2T)(TK)
0.038;-25631.2
J(2TQ)
0.023;-41291.3
K(2TQ)
0.021;-38898.8
TT(2J)
0.025;-35853.8
2TTK
0.022;-41291.3
TK(2J)
0.017;-40095.0
2TJJ
0.019;-42487.5
2TJK
0.012;-47925.0
2(TQK)
0.020;-38898.8
TK(2K)
0.030;-29872.5
(2J)(JK)
0.042;-23238.8
QK(2J)
0.028;-37702.5
2J(JK)
0.036;-31068.8
(JQ)(2K)
0.036;-29872.5
(2K)(JK)
0.051;-20846.2
K(2QK)
0.040;-27480.0
2K(QK)
0.032;-27480.0
3335
0.006;-58582.5
3339
0.011;-53797.5
333K
0.013;-49012.5
36(34)
0.006;-56190.0
(34)(39)
0.016;-44771.2
3(34Q)
0.010;-49012.5
33(45)
0.007;-57386.3
34(38)
0.007;-53797.5
334T
0.004;-59235.0
33(4K)
0.009;-47816.3
(35)(37)
0.016;-45967.5
3(35T)
0.011;-50208.8
3Q(35)
0.017;-47816.3
35(37)
0.009;-53797.5
3359
0.006;-59235.0
33(5Q)
0.013;-47816.3
(36)(37)
0.018;-44771.2
3(36T)
0.013;-49012.5
3Q(36)
0.013;-46620.0
36(38)
0.010;-51405.0
336T
0.007;-56842.5
33(6K)
0.016;-45423.8
(37)(39)
0.020;-41182.5
3(37Q)
0.018;-45423.8
33(78)
0.014;-50208.8
37(3J)
0.018;-46620.0
337K
0.007;-52057.5
3T(38)
0.013;-46620.0
(38)(3K)
0.035;-35201.2
338T
0.007;-54450.0
33(8K)
0.023;-43031.2
(39)(3J)
0.033;-36397.5
3399
0.012;-46620.0
33(9Q)
0.015;-43031.2
(3T)(3J)
0.021;-35201.2
33TT
0.015;-44227.5
33(TK)
0.021;-40638.8
(3J)(3K)
0.033;-31612.5
33JK
0.018;-47272.5
33(QK)
0.032;-38246.2
45(34)
0.008;-56190.0
(34)(48)
0.016;-44771.2
4(34J)
0.013;-49012.5
4K(34)
0.010;-46620.0
(3459)
0.007;-58038.8
(345K)
0.008;-53253.8
57(34)
0.005;-60431.3
(34)(5T)
0.015;-49012.5
5(34K)
0.009;-53253.8
(3469)
0.008;-56842.5
(346K)
0.010;-52057.5
68(34)
0.005;-58038.8
(34)(6J)
0.015;-46620.0
7(347)
0.009;-50208.8
J(347)
0.007;-53253.8
78(34)
0.007;-56842.5
(34)(7J)
0.015;-45423.8
8(348)
0.013;-47816.3
Q(348)
0.009;-50861.3
(34)(8T)
0.017;-45423.8
8(34K)
0.012;-49665.0
(349Q)
0.010;-49665.0
9(34J)
0.010;-50861.3
9K(34)
0.010;-48468.8
TT(34)
0.018;-43031.2
(34)(TK)
0.024;-39442.5
J(34Q)
0.009;-47272.5
K(34Q)
0.017;-44880.0
44(35)
0.007;-56190.0
3447
0.005;-61627.5
34(4T)
0.010;-50208.8
44(3K)
0.017;-46620.0
4(357)
0.004;-60431.3
49(35)
0.006;-58038.8
(35)(4Q)
0.010;-46620.0
36(45)
0.005;-61627.5
3(459)
0.006;-58038.8
(45)(3Q)
0.014;-46620.0
35(46)
0.004;-61627.5
35(48)
0.005;-59235.0
35(4T)
0.006;-56842.5
35(4Q)
0.008;-54450.0
46(36)
0.011;-52601.3
(36)(49)
0.010;-49012.5
4(36Q)
0.007;-53253.8
3(467)
0.005;-59235.0
(46)(3T)
0.012;-47816.3
3Q(46)
0.009;-53253.8
3467
0.003;-67065.0
3469
0.003;-64672.5
346J
0.005;-62280.0
346K
0.005;-59887.5
49(37)
0.006;-55646.2
(37)(4Q)
0.016;-44227.5
38(47)
0.007;-56842.5
3(47J)
0.010;-53253.8
3477
0.005;-58038.8
3479
0.003;-63476.3
347J
0.004;-61083.8
347K
0.007;-58691.3
4T(38)
0.008;-53253.8
(38)(4K)
0.019;-41835.0
3T(48)
0.007;-53253.8
3(48K)
0.013;-49665.0
38(4T)
0.012;-53253.8
38(4Q)
0.010;-50861.3
49(39)
0.019;-45423.8
(39)(4Q)
0.019;-41835.0
3T(49)
0.011;-52057.5
3(49K)
0.017;-48468.8
39(4J)
0.010;-50861.3
39(4K)
0.014;-48468.8
4(3TQ)
0.010;-48468.8
3(4TJ)
0.011;-49665.0
34TT
0.012;-50861.3
34TQ
0.005;-56298.8
(3J)(4Q)
0.021;-39442.5
3Q(4J)
0.015;-47272.5
34JQ
0.006;-55102.5
(3Q)(4K)
0.021;-37050.0
3Q(4K)
0.016;-44880.0
5(356)
0.010;-52601.3
58(35)
0.011;-50208.8
(35)(5J)
0.018;-38790.0
6(356)
0.011;-51405.0
T(356)
0.009;-54450.0
6(357)
0.004;-58038.8
69(35)
0.005;-55646.2
(35)(6Q)
0.015;-44227.5
(3579)
0.009;-54450.0
(357K)
0.008;-49665.0
79(35)
0.009;-54450.0
(35)(7Q)
0.021;-43031.3
(358T)
0.013;-52057.5
88(35)
0.017;-46620.0
(35)(8J)
0.017;-43031.3
9(359)
0.016;-44227.5
K(359)
0.014;-47272.5
9(35Q)
0.011;-48468.8
J(35T)
0.014;-48468.8
TJ(35)
0.015;-48468.8
(35JQ)
0.014;-46076.2
J(35K)
0.014;-44880.0
(35)(QK)
0.032;-35853.8
55(37)
0.010;-51405.0
3559
0.007;-56842.5
35(5Q)
0.017;-45423.8
(36)(57)
0.012;-50208.8
5(36T)
0.007;-54450.0
5Q(36)
0.010;-52057.5
(56)(38)
0.011;-49012.5
3T(56)
0.008;-54450.0
3(56K)
0.009;-50861.3
36(58)
0.005;-56842.5
36(5T)
0.006;-54450.0
36(5Q)
0.008;-52057.5
57(37)
0.013;-49012.5
(37)(5T)
0.011;-45423.8
5(37K)
0.010;-49665.0
3(579)
0.007;-54450.0
(57)(3Q)
0.016;-43031.3
37(58)
0.007;-55646.2
37(5T)
0.008;-53253.8
37(5Q)
0.011;-50861.3
58(38)
0.014;-46620.0
(38)(5J)
0.016;-43031.3
38(58)
0.019;-46620.0
3(58J)
0.011;-50861.3
3588
0.009;-54450.0
358T
0.005;-59887.5
358Q
0.005;-57495.0
(39)(5T)
0.017;-43031.3
5(39K)
0.017;-47272.5
3(59J)
0.011;-49665.0
3599
0.012;-52057.5
359J
0.005;-57495.0
359K
0.007;-55102.5
5Q(3T)
0.014;-47272.5
(5T)(3Q)
0.021;-39442.5
3T(5J)
0.010;-48468.8
3T(5K)
0.010;-46076.2
5(3JK)
0.018;-44880.0
3(5JK)
0.014;-44880.0
3J(5K)
0.015;-44880.0
3Q(5Q)
0.029;-37050.0
35QK
0.013;-51513.8
67(36)
0.014;-49012.5
(36)(6T)
0.020;-37593.8
6(36K)
0.021;-41835.0
(367T)
0.009;-52057.5
77(36)
0.009;-47816.3
(36)(7T)
0.015;-44227.5
7(36K)
0.016;-48468.8
(368J)
0.008;-49665.0
(36)(89)
0.017;-44227.5
8(36Q)
0.013;-48468.8
T(369)
0.012;-49665.0
9(36T)
0.010;-49665.0
9Q(36)
0.014;-47272.5
Q(36T)
0.014;-46076.2
(36)(TQ)
0.021;-38246.2
(36JK)
0.020;-43683.8
JK(36)
0.014;-43683.8
K(36K)
0.031;-33461.2
3668
0.007;-55646.2
36(6J)
0.015;-44227.5
(37)(67)
0.017;-39986.3
6(37T)
0.010;-52057.5
6Q(37)
0.011;-49665.0
(67)(39)
0.011;-45423.8
3J(67)
0.011;-50861.3
67(38)
0.007;-54450.0
67(3T)
0.010;-52057.5
67(3Q)
0.011;-49665.0
(38)(68)
0.026;-37593.8
6(38J)
0.010;-49665.0
6K(38)
0.014;-47272.5
(68)(3J)
0.014;-41835.0
3K(68)
0.012;-47272.5
36(8T)
0.014;-50861.3
36(8Q)
0.015;-48468.8
6(39T)
0.012;-49665.0
6Q(39)
0.011;-47272.5
(69)(3J)
0.019;-40638.8
3K(69)
0.013;-46076.2
36(9J)
0.013;-48468.8
36(9K)
0.011;-46076.2
(3T)(6Q)
0.023;-38246.2
3J(6T)
0.011;-47272.5
6T(3J)
0.015;-47272.5
6T(3K)
0.014;-44880.0
6Q(3J)
0.014;-44880.0
(6J)(3K)
0.022;-35853.8
6J(3K)
0.012;-43683.8
6K(3Q)
0.017;-42487.5
36(QK)
0.017;-42487.5
(37)(78)
0.020;-37593.8
7(37J)
0.018;-41835.0
7K(37)
0.020;-39442.5
(378Q)
0.016;-47272.5
8(37T)
0.013;-49665.0
8Q(37)
0.010;-47272.5
J(379)
0.014;-47272.5
9T(37)
0.011;-48468.8
(37)(9K)
0.022;-37050.0
K(37T)
0.018;-43683.8
T(37K)
0.023;-43683.8
JJ(37)
0.025;-37050.0
(37QK)
0.017;-41291.3
3777
0.013;-46620.0
37(7T)
0.018;-43031.2
77(3K)
0.026;-39442.5
7(38T)
0.011;-49665.0
7Q(38)
0.015;-47272.5
(78)(3T)
0.016;-41835.0
3Q(78)
0.014;-47272.5
3789
0.007;-58691.3
378J
0.006;-56298.8
378K
0.007;-53906.2
7J(39)
0.013;-47272.5
(79)(3T)
0.027;-40638.8
3Q(79)
0.018;-46076.2
379T
0.005;-56298.8
379Q
0.010;-53906.2
(3T)(7J)
0.020;-38246.2
3T(7T)
0.019;-39442.5
3(7TK)
0.016;-43683.8
3T(7Q)
0.017;-44880.0
7J(3J)
0.024;-37050.0
(7J)(3Q)
0.019;-35853.8
3J(7Q)
0.019;-43683.8
7Q(3Q)
0.026;-34657.5
37QQ
0.016;-42487.5
37KK
0.020;-40095.0
8(38J)
0.022;-39442.5
8K(38)
0.024;-37050.0
(389K)
0.021;-43683.8
9J(38)
0.019;-46076.2
(38TJ)
0.021;-44880.0
(38)(TJ)
0.028;-37050.0
J(38J)
0.023;-35853.8
JQ(38)
0.017;-42487.5
Q(38K)
0.021;-40095.0
3889
0.009;-49665.0
38(8Q)
0.024;-38246.2
(39)(8T)
0.024;-39442.5
8(39K)
0.017;-43683.8
3(89J)
0.018;-46076.2
3899
0.014;-48468.8
389J
0.006;-53906.2
389K
0.008;-51513.8
8Q(3T)
0.019;-43683.8
(8T)(3Q)
0.026;-35853.8
3T(8J)
0.020;-44880.0
3T(8K)
0.020;-42487.5
8(3JK)
0.019;-41291.3
3(8JK)
0.017;-41291.3
3J(8K)
0.024;-41291.3
3Q(8Q)
0.027;-33461.2
38QK
0.017;-47925.0
9T(39)
0.030;-38246.2
(39)(9K)
0.046;-26827.5
K(39T)
0.015;-41291.3
T(39K)
0.018;-41291.3
JJ(39)
0.030;-34657.5
(39QK)
0.024;-38898.8
3999
0.022;-39442.5
39(9Q)
0.028;-35853.8
(3T)(9J)
0.025;-35853.8
3T(9T)
0.027;-37050.0
3(9TK)
0.017;-41291.3
3T(9Q)
0.018;-42487.5
9J(3J)
0.027;-34657.5
(9J)(3Q)
0.035;-33461.3
3J(9Q)
0.018;-41291.3
9Q(3Q)
0.028;-32265.0
39QQ
0.022;-40095.0
39KK
0.022;-37702.5
T(3TK)
0.034;-32265.0
JJ(3T)
0.021;-33461.2
(3TQK)
0.022;-37702.5
3TTT
0.030;-35853.8
3T(TK)
0.035;-32265.0
(3J)(TK)
0.026;-31068.8
3K(TJ)
0.025;-38898.8
3T(JK)
0.027;-38898.8
(TQ)(3K)
0.035;-29872.5
(3K)(TK)
0.050;-20846.2
J(3JK)
0.027;-29872.5
(3J)(QK)
0.046;-28676.3
JJ(3K)
0.037;-29872.5
3Q(JQ)
0.036;-29872.5
3JQK
0.018;-44336.2
QK(3Q)
0.042;-27480.0
QK(3K)
0.032;-26283.7
44(46)
0.013;-45967.5
44(4T)
0.016;-41182.5
(45)(45)
0.025;-38137.5
4(458)
0.012;-50208.8
4T(45)
0.012;-47816.3
(45)(4K)
0.032;-36397.5
4457
0.004;-59235.0
44(5T)
0.014;-47816.3
45(4K)
0.014;-44227.5
4(468)
0.013;-49012.5
4T(46)
0.012;-46620.0
(46)(4K)
0.027;-35201.2
4468
0.007;-56842.5
44(6J)
0.014;-45423.8
(47)(47)
0.038;-33352.5
4(47T)
0.011;-45423.8
4Q(47)
0.021;-43031.2
47(49)
0.014;-46620.0
447J
0.009;-52057.5
48(48)
0.020;-38790.0
(48)(4J)
0.030;-35201.2
4488
0.014;-46620.0
44(8J)
0.016;-43031.2
(49)(49)
0.032;-28567.5
4(49Q)
0.018;-40638.8
44(9T)
0.017;-43031.2
49(4K)
0.020;-39442.5
4(4TQ)
0.028;-39442.5
44(TJ)
0.015;-40638.8
(4J)(4J)
0.056;-23782.5
44JJ
0.026;-39442.5
4Q(4Q)
0.040;-29220.0
(4K)(4K)
0.052;-18997.5
(45)(57)
0.022;-42378.8
5(45T)
0.010;-46620.0
5Q(45)
0.014;-44227.5
8(456)
0.006;-55646.2
Q(456)
0.014;-50861.3
(45)(68)
0.010;-47816.3
6(45J)
0.011;-52057.5
6K(45)
0.009;-49665.0
(457J)
0.009;-50861.3
(45)(78)
0.015;-46620.0
7(45J)
0.014;-50861.3
7K(45)
0.012;-48468.8
(458Q)
0.012;-48468.8
8(45T)
0.009;-50861.3
8Q(45)
0.016;-48468.8
J(459)
0.012;-48468.8
9T(45)
0.009;-49665.0
(45)(9K)
0.025;-38246.2
K(45T)
0.021;-44880.0
T(45K)
0.015;-44880.0
JJ(45)
0.024;-38246.2
(45QK)
0.019;-42487.5
4555
0.010;-52601.3
45(58)
0.010;-49012.5
55(4J)
0.016;-45423.8
455K
0.011;-50861.3
58(46)
0.005;-55646.2
(46)(5J)
0.012;-44227.5
46(56)
0.011;-50208.8
4(569)
0.008;-54450.0
(56)(4Q)
0.015;-43031.3
46(57)
0.005;-56842.5
46(59)
0.010;-54450.0
46(5J)
0.009;-52057.5
46(5K)
0.010;-49665.0
5(479)
0.011;-53253.8
5J(47)
0.009;-50861.3
(57)(48)
0.015;-46620.0
4T(57)
0.009;-52057.5
4(57K)
0.011;-48468.8
47(59)
0.011;-53253.8
47(5J)
0.008;-50861.3
47(5K)
0.013;-48468.8
5(48T)
0.011;-50861.3
5Q(48)
0.011;-48468.8
(58)(4T)
0.020;-43031.3
4Q(58)
0.011;-48468.8
4589
0.004;-59887.5
458J
0.004;-57495.0
458K
0.008;-55102.5
5J(49)
0.011;-48468.8
(59)(4T)
0.019;-41835.0
4Q(59)
0.013;-47272.5
459T
0.006;-57495.0
459Q
0.007;-55102.5
(4T)(5J)
0.019;-39442.5
4T(5T)
0.024;-40638.8
4(5TK)
0.016;-44880.0
4T(5Q)
0.015;-46076.2
5J(4J)
0.020;-38246.2
(5J)(4Q)
0.030;-37050.0
4J(5Q)
0.015;-44880.0
5Q(4Q)
0.027;-35853.8
45QQ
0.020;-43683.8
45KK
0.015;-41291.3
6(469)
0.017;-45423.8
6J(46)
0.021;-43031.2
(4678)
0.010;-53253.8
(467Q)
0.013;-48468.8
7(469)
0.009;-52057.5
7J(46)
0.014;-49665.0
(4689)
0.012;-50861.3
(468K)
0.014;-46076.2
8T(46)
0.013;-49665.0
(46)(8K)
0.028;-38246.2
Q(469)
0.015;-46076.2
(46)(9J)
0.023;-39442.5
T(46T)
0.018;-39442.5
T(46J)
0.011;-46076.2
TK(46)
0.013;-43683.8
(46)(JQ)
0.029;-35853.8
QQ(46)
0.026;-34657.5
46(67)
0.010;-47816.3
66(4T)
0.018;-44227.5
466Q
0.015;-49665.0
68(47)
0.008;-53253.8
(47)(6J)
0.020;-41835.0
47(67)
0.011;-46620.0
4(67T)
0.011;-50861.3
(67)(4K)
0.021;-39442.5
67(49)
0.008;-52057.5
67(4J)
0.014;-49665.0
67(4K)
0.015;-47272.5
69(48)
0.012;-50861.3
(48)(6Q)
0.021;-39442.5
49(68)
0.013;-50861.3
4(68Q)
0.018;-47272.5
46(89)
0.010;-50861.3
46(8J)
0.013;-48468.8
46(8K)
0.012;-46076.2
(49)(6J)
0.025;-39442.5
49(69)
0.016;-41835.0
4(69Q)
0.016;-46076.2
46(9T)
0.012;-48468.8
46(9Q)
0.014;-46076.2
6(4TJ)
0.016;-46076.2
6K(4T)
0.016;-43683.8
(6T)(4K)
0.021;-35853.8
6T(4Q)
0.013;-44880.0
(4J)(6J)
0.032;-29220.0
4J(6J)
0.027;-37050.0
6J(4Q)
0.021;-43683.8
(4Q)(6Q)
0.045;-26827.5
4K(6Q)
0.024;-41291.3
4K(6K)
0.030;-32265.0
79(47)
0.018;-43031.2
(47)(7Q)
0.043;-31612.5
(478T)
0.014;-48468.8
88(47)
0.021;-43031.2
(47)(8J)
0.021;-39442.5
9(479)
0.015;-40638.8
K(479)
0.013;-43683.8
9(47Q)
0.013;-44880.0
J(47T)
0.012;-44880.0
TJ(47)
0.019;-44880.0
(47JQ)
0.014;-42487.5
J(47K)
0.020;-41291.3
(47)(QK)
0.029;-32265.0
77(49)
0.018;-43031.2
477J
0.014;-48468.8
78(48)
0.016;-43031.2
(48)(7J)
0.024;-39442.5
48(78)
0.014;-43031.2
4(78J)
0.011;-47272.5
4788
0.009;-50861.3
478T
0.007;-56298.8
478Q
0.010;-53906.2
(49)(7T)
0.024;-39442.5
7(49K)
0.015;-43683.8
4(79J)
0.013;-46076.2
4799
0.010;-48468.8
479J
0.007;-53906.2
479K
0.008;-51513.8
7Q(4T)
0.020;-43683.8
(7T)(4Q)
0.029;-35853.8
4T(7J)
0.016;-44880.0
4T(7K)
0.019;-42487.5
7(4JK)
0.019;-41291.3
4(7JK)
0.019;-41291.3
4J(7K)
0.021;-41291.3
4Q(7Q)
0.031;-33461.2
47QK
0.014;-47925.0
89(48)
0.020;-40638.8
(48)(8Q)
0.027;-29220.0
(489J)
0.012;-44880.0
(48)(9T)
0.027;-38246.2
9(48K)
0.019;-42487.5
(48TK)
0.019;-41291.3
TQ(48)
0.019;-42487.5
K(48J)
0.028;-40095.0
Q(48Q)
0.031;-32265.0
KK(48)
0.038;-29872.5
88(4J)
0.019;-38246.2
488K
0.019;-43683.8
8J(49)
0.016;-44880.0
(89)(4T)
0.021;-38246.2
4Q(89)
0.019;-43683.8
489T
0.008;-53906.2
489Q
0.012;-51513.8
(4T)(8J)
0.021;-35853.8
4T(8T)
0.027;-37050.0
4(8TK)
0.014;-41291.3
4T(8Q)
0.014;-42487.5
8J(4J)
0.034;-34657.5
(8J)(4Q)
0.026;-33461.3
4J(8Q)
0.019;-41291.3
8Q(4Q)
0.031;-32265.0
48QQ
0.021;-40095.0
48KK
0.024;-37702.5
9(49Q)
0.025;-34657.5
J(49T)
0.019;-42487.5
TJ(49)
0.019;-42487.5
(49JQ)
0.020;-40095.0
J(49K)
0.019;-38898.8
(49)(QK)
0.027;-29872.5
99(4J)
0.026;-35853.8
499K
0.018;-41291.3
9Q(4T)
0.020;-41291.3
(9T)(4Q)
0.031;-33461.3
4T(9J)
0.023;-42487.5
4T(9K)
0.017;-40095.0
9(4JK)
0.019;-38898.8
4(9JK)
0.021;-38898.8
4J(9K)
0.024;-38898.8
4Q(9Q)
0.035;-31068.8
49QK
0.019;-45532.5
TJ(4T)
0.029;-33461.2
(4TJQ)
0.027;-38898.8
J(4TK)
0.019;-37702.5
(4T)(QK)
0.033;-28676.3
TT(4Q)
0.030;-32265.0
T(4JQ)
0.016;-38898.8
4(TJQ)
0.023;-38898.8
4T(JQ)
0.022;-38898.8
T(4QK)
0.026;-36506.2
TQ(4K)
0.023;-36506.2
JJ(4J)
0.046;-23238.8
(4JQK)
0.022;-35310.0
4JJJ
0.025;-31068.8
JQ(4Q)
0.031;-28676.3
4JQQ
0.025;-36506.2
4JKK
0.026;-34113.7
QQ(4K)
0.038;-26283.7
4KKK
0.051;-23891.3
55(59)
0.021;-38790.0
55(5K)
0.024;-34005.0
(56)(58)
0.022;-38790.0
5(56J)
0.018;-43031.2
5K(56)
0.024;-40638.8
56(59)
0.014;-45423.8
556J
0.012;-50861.3
57(57)
0.020;-38790.0
(57)(5T)
0.027;-35201.2
5(57K)
0.027;-39442.5
55(79)
0.019;-44227.5
57(5Q)
0.020;-40638.8
5(589)
0.016;-43031.2
5J(58)
0.019;-40638.8
58(59)
0.013;-43031.2
558J
0.009;-48468.8
59(59)
0.027;-34005.0
(59)(5Q)
0.030;-30416.3
559T
0.011;-48468.8
55(9K)
0.029;-37050.0
(5T)(5Q)
0.041;-29220.0
55TJ
0.015;-46076.2
5J(5J)
0.034;-29220.0
5J(5Q)
0.022;-35853.8
5(5QK)
0.037;-33461.2
5K(5K)
0.059;-24435.0
68(56)
0.013;-45423.8
(56)(6J)
0.029;-34005.0
7(567)
0.018;-45423.8
J(567)
0.013;-48468.8
78(56)
0.007;-52057.5
(56)(7J)
0.018;-40638.8
8(568)
0.018;-43031.2
Q(568)
0.017;-46076.2
(56)(8T)
0.020;-40638.8
8(56K)
0.014;-44880.0
(569Q)
0.018;-44880.0
9(56J)
0.013;-46076.2
9K(56)
0.017;-43683.8
TT(56)
0.022;-38246.2
(56)(TK)
0.032;-34657.5
J(56Q)
0.013;-42487.5
K(56Q)
0.023;-40095.0
66(57)
0.013;-46620.0
5669
0.008;-52057.5
56(6Q)
0.022;-40638.8
(57)(68)
0.013;-44227.5
6(57J)
0.009;-48468.8
6K(57)
0.014;-46076.2
(67)(5T)
0.023;-41835.0
5Q(67)
0.015;-47272.5
5678
0.005;-59887.5
567T
0.006;-57495.0
567Q
0.006;-55102.5
(58)(69)
0.015;-41835.0
6(58Q)
0.014;-46076.2
5(689)
0.008;-49665.0
(68)(5Q)
0.021;-38246.2
58(69)
0.010;-49665.0
58(6J)
0.011;-47272.5
58(6K)
0.012;-44880.0
6(59J)
0.017;-46076.2
6K(59)
0.019;-43683.8
(69)(5Q)
0.025;-37050.0
59(6T)
0.012;-47272.5
59(6Q)
0.017;-44880.0
6T(5T)
0.021;-38246.2
(5T)(6K)
0.032;-34657.5
5Q(6T)
0.017;-43683.8
56TJ
0.010;-52710.0
56TK
0.011;-50317.5
6K(5J)
0.020;-41291.3
56JJ
0.023;-43683.8
56JK
0.012;-49121.2
5(6QK)
0.020;-40095.0
6K(5K)
0.032;-31068.8
(57)(79)
0.030;-34005.0
7(57Q)
0.021;-38246.2
9(578)
0.009;-48468.8
K(578)
0.021;-43683.8
8(57J)
0.014;-46076.2
8K(57)
0.016;-43683.8
(579K)
0.016;-42487.5
9J(57)
0.016;-44880.0
(57TJ)
0.016;-43683.8
(57)(TJ)
0.028;-35853.8
J(57J)
0.034;-34657.5
JQ(57)
0.023;-41291.3
Q(57K)
0.022;-38898.8
5778
0.010;-50861.3
57(7J)
0.022;-39442.5
(58)(78)
0.031;-34005.0
7(58J)
0.012;-46076.2
7K(58)
0.017;-43683.8
(78)(5J)
0.020;-38246.2
5K(78)
0.019;-43683.8
57(8T)
0.013;-47272.5
57(8Q)
0.014;-44880.0
7(59T)
0.015;-46076.2
7Q(59)
0.017;-43683.8
(79)(5J)
0.024;-37050.0
5K(79)
0.020;-42487.5
57(9J)
0.011;-44880.0
57(9K)
0.023;-42487.5
(5T)(7Q)
0.022;-34657.5
5J(7T)
0.018;-43683.8
7T(5J)
0.015;-43683.8
7T(5K)
0.016;-41291.3
7Q(5J)
0.025;-41291.3
(7J)(5K)
0.028;-32265.0
7J(5K)
0.022;-40095.0
7K(5Q)
0.019;-38898.8
57(QK)
0.025;-38898.8
(58)(89)
0.034;-31612.5
8(58Q)
0.025;-35853.8
T(589)
0.014;-44880.0
9(58T)
0.016;-44880.0
9Q(58)
0.017;-42487.5
Q(58T)
0.019;-41291.3
(58)(TQ)
0.028;-33461.3
(58JK)
0.018;-38898.8
JK(58)
0.020;-38898.8
K(58K)
0.032;-28676.3
588T
0.014;-46076.2
58(8K)
0.032;-34657.5
(59)(8J)
0.026;-35853.8
59(89)
0.025;-38246.2
5(89Q)
0.020;-42487.5
58(9T)
0.016;-44880.0
58(9Q)
0.016;-42487.5
8(5TJ)
0.022;-42487.5
8K(5T)
0.019;-40095.0
(8T)(5K)
0.033;-32265.0
8T(5Q)
0.022;-41291.3
(5J)(8J)
0.041;-25631.2
5J(8J)
0.025;-33461.2
8J(5Q)
0.020;-40095.0
(5Q)(8Q)
0.049;-23238.8
5K(8Q)
0.019;-37702.5
5K(8K)
0.037;-28676.3
9J(59)
0.027;-34657.5
(59TJ)
0.014;-41291.3
(59)(TJ)
0.025;-33461.3
J(59J)
0.025;-32265.0
JQ(59)
0.021;-38898.8
Q(59K)
0.030;-36506.2
599T
0.019;-43683.8
59(9K)
0.034;-32265.0
(5T)(9Q)
0.026;-32265.0
5J(9T)
0.024;-41291.3
9T(5J)
0.020;-41291.3
9T(5K)
0.025;-38898.8
9Q(5J)
0.022;-38898.8
(9J)(5K)
0.041;-29872.5
9J(5K)
0.018;-37702.5
9K(5Q)
0.028;-36506.2
59(QK)
0.031;-36506.2
(5T)(TJ)
0.048;-24435.0
J(5TJ)
0.044;-31068.8
JQ(5T)
0.031;-37702.5
Q(5TK)
0.030;-35310.0
5TTJ
0.022;-40095.0
TJ(5J)
0.041;-31068.8
(TJ)(5Q)
0.038;-29872.5
5J(TQ)
0.024;-37702.5
TQ(5Q)
0.042;-28676.3
5TQQ
0.022;-36506.2
5TKK
0.029;-34113.7
Q(5JQ)
0.050;-27480.0
KK(5J)
0.056;-25087.5
(5Q)(JQ)
0.049;-19650.0
5K(JQ)
0.036;-34113.7
5K(JK)
0.040;-25087.5
5QQQ
0.041;-26283.7
KK(5K)
0.066;-14865.0
6669
0.016;-43031.3
666K
0.020;-38246.2
69(67)
0.014;-41835.0
(67)(6Q)
0.038;-30416.3
6678
0.010;-50861.3
66(7J)
0.022;-39442.5
(68)(68)
0.038;-26175.0
6(68J)
0.021;-38246.2
6K(68)
0.029;-35853.8
68(6J)
0.023;-38246.2
668K
0.016;-43683.8
6J(69)
0.020;-37050.0
69(6T)
0.019;-38246.2
669Q
0.016;-43683.8
6J(6T)
0.028;-35853.8
6T(6J)
0.020;-35853.8
66TK
0.016;-41291.3
6K(6J)
0.038;-32265.0
(6Q)(6Q)
0.085;-16605.0
66QK
0.021;-38898.8
7(679)
0.019;-40638.8
7J(67)
0.024;-38246.2
(6789)
0.010;-47272.5
(678K)
0.019;-42487.5
8T(67)
0.015;-46076.2
(67)(8K)
0.030;-34657.5
Q(679)
0.016;-42487.5
(67)(9J)
0.026;-35853.8
T(67T)
0.026;-35853.8
T(67J)
0.013;-42487.5
TK(67)
0.026;-40095.0
(67)(JQ)
0.023;-32265.0
QQ(67)
0.032;-31068.8
67(78)
0.020;-41835.0
77(6J)
0.020;-38246.2
677K
0.022;-43683.8
7T(68)
0.016;-46076.2
(68)(7K)
0.030;-34657.5
6T(78)
0.013;-46076.2
6(78K)
0.022;-42487.5
68(7T)
0.018;-46076.2
68(7Q)
0.014;-43683.8
79(69)
0.024;-38246.2
(69)(7Q)
0.026;-34657.5
6T(79)
0.015;-44880.0
6(79K)
0.014;-41291.3
69(7J)
0.014;-43683.8
69(7K)
0.023;-41291.3
7(6TQ)
0.025;-41291.3
6(7TJ)
0.018;-42487.5
67TT
0.014;-43683.8
67TQ
0.010;-49121.2
(6J)(7Q)
0.030;-32265.0
6Q(7J)
0.026;-40095.0
67JQ
0.015;-47925.0
(6Q)(7K)
0.042;-29872.5
6Q(7K)
0.030;-37702.5
8(689)
0.028;-38246.2
8J(68)
0.027;-35853.8
(689T)
0.014;-43683.8
99(68)
0.026;-37050.0
(68)(9Q)
0.033;-33461.3
(68TQ)
0.017;-40095.0
T(68Q)
0.023;-40095.0
Q(68J)
0.024;-38898.8
(68)(JK)
0.035;-29872.5
QK(68)
0.024;-36506.2
68(8T)
0.031;-37050.0
88(6K)
0.025;-33461.2
8(69J)
0.022;-42487.5
8K(69)
0.019;-40095.0
(89)(6Q)
0.035;-33461.3
69(8T)
0.015;-43683.8
69(8Q)
0.019;-41291.3
8T(6T)
0.021;-34657.5
(6T)(8K)
0.037;-31068.8
6Q(8T)
0.023;-40095.0
68TJ
0.014;-49121.2
68TK
0.018;-46728.8
8K(6J)
0.023;-37702.5
68JJ
0.018;-40095.0
68JK
0.016;-45532.5
6(8QK)
0.029;-36506.2
8K(6K)
0.031;-27480.0
(69)(9J)
0.046;-25631.2
T(69T)
0.031;-33461.2
T(69J)
0.016;-40095.0
TK(69)
0.022;-37702.5
(69)(JQ)
0.029;-29872.5
QQ(69)
0.043;-28676.3
69(9T)
0.020;-34657.5
99(6K)
0.028;-31068.8
9(6TQ)
0.026;-38898.8
6(9TJ)
0.018;-40095.0
69TT
0.021;-41291.3
69TQ
0.018;-46728.8
(6J)(9Q)
0.033;-29872.5
6Q(9J)
0.020;-37702.5
69JQ
0.017;-45532.5
(6Q)(9K)
0.038;-27480.0
6Q(9K)
0.035;-35310.0
T(6TJ)
0.034;-31068.8
TK(6T)
0.034;-28676.3
(6T)(JQ)
0.046;-28676.3
QQ(6T)
0.040;-27480.0
6T(TJ)
0.029;-31068.8
(6J)(TJ)
0.054;-22042.5
6J(TJ)
0.034;-29872.5
TJ(6Q)
0.021;-36506.2
(6Q)(TQ)
0.057;-19650.0
6K(TQ)
0.024;-34113.7
6K(TK)
0.055;-25087.5
JK(6J)
0.032;-26283.7
K(6JK)
0.048;-23891.3
6JJK
0.022;-34113.7
6(JQK)
0.034;-32917.5
JK(6K)
0.053;-23891.3
KK(6Q)
0.051;-22695.0
6QKK
0.040;-30525.0
77(7T)
0.038;-30416.2
(78)(78)
0.036;-23782.5
7(78J)
0.025;-35853.8
7K(78)
0.031;-33461.2
78(7J)
0.027;-35853.8
778K
0.016;-41291.3
7J(79)
0.026;-34657.5
79(7T)
0.032;-35853.8
779Q
0.017;-41291.3
7J(7T)
0.032;-33461.2
7T(7J)
0.028;-33461.2
77TK
0.020;-38898.8
7K(7J)
0.034;-29872.5
(7Q)(7Q)
0.062;-14212.5
77QK
0.022;-36506.2
8(78T)
0.020;-35853.8
8Q(78)
0.034;-33461.2
J(789)
0.019;-41291.3
9T(78)
0.015;-42487.5
(78)(9K)
0.032;-31068.8
K(78T)
0.023;-37702.5
T(78K)
0.024;-37702.5
JJ(78)
0.044;-31068.8
(78QK)
0.028;-35310.0
7888
0.025;-38246.2
78(8J)
0.023;-34657.5
(79)(89)
0.041;-28023.8
8(79Q)
0.022;-40095.0
7(89T)
0.016;-42487.5
(89)(7K)
0.031;-31068.8
89(7J)
0.020;-41291.3
89(7K)
0.026;-38898.8
8J(7T)
0.018;-40095.0
(8T)(7J)
0.030;-32265.0
7K(8T)
0.022;-37702.5
78(TQ)
0.024;-38898.8
8(7JQ)
0.024;-37702.5
7(8JQ)
0.025;-37702.5
78(JQ)
0.025;-37702.5
8(7QK)
0.024;-35310.0
8Q(7K)
0.031;-35310.0
99(79)
0.037;-26827.5
(79)(9Q)
0.046;-23238.8
(79TQ)
0.021;-37702.5
T(79Q)
0.026;-37702.5
Q(79J)
0.024;-36506.2
(79)(JK)
0.040;-27480.0
QK(79)
0.021;-34113.7
79(9J)
0.038;-32265.0
(7T)(9T)
0.050;-24435.0
9(7TK)
0.025;-36506.2
7(9TQ)
0.025;-37702.5
79(TJ)
0.021;-38898.8
79(TK)
0.019;-36506.2
(7J)(9K)
0.034;-27480.0
7K(9J)
0.024;-35310.0
79(JK)
0.025;-35310.0
(9Q)(7K)
0.046;-26283.7
(7K)(9K)
0.050;-17257.5
T(7TQ)
0.039;-28676.3
Q(7TJ)
0.031;-35310.0
(7T)(JK)
0.040;-26283.7
QK(7T)
0.033;-32917.5
7T(TQ)
0.033;-28676.3
(7J)(TQ)
0.041;-27480.0
7Q(TJ)
0.032;-35310.0
7TJQ
0.017;-43140.0
(7Q)(TK)
0.036;-25087.5
7Q(TK)
0.036;-32917.5
J(7JQ)
0.047;-26283.7
K(7JQ)
0.031;-31721.2
JJ(7Q)
0.041;-26283.7
J(7QK)
0.034;-31721.2
JQ(7K)
0.025;-31721.2
QQ(7Q)
0.060;-16061.3
7Q(QK)
0.057;-22695.0
8888
0.042;-29220.0
888Q
0.030;-32265.0
8(89J)
0.035;-32265.0
8K(89)
0.029;-29872.5
89(8Q)
0.036;-31068.8
8(8TJ)
0.034;-31068.8
8K(8T)
0.047;-28676.3
8T(8K)
0.029;-28676.3
8(8JK)
0.047;-27480.0
88(JK)
0.048;-27480.0
8Q(8K)
0.040;-26283.7
(89)(9T)
0.048;-24435.0
9(89K)
0.037;-28676.3
(89TK)
0.022;-35310.0
TQ(89)
0.032;-36506.2
K(89J)
0.028;-34113.7
Q(89Q)
0.041;-26283.7
KK(89)
0.046;-23891.3
99(8Q)
0.044;-29872.5
9(8TJ)
0.020;-37702.5
9K(8T)
0.032;-35310.0
(9T)(8K)
0.031;-27480.0
9T(8Q)
0.027;-36506.2
(8J)(9J)
0.054;-20846.2
8J(9J)
0.039;-28676.3
9J(8Q)
0.021;-35310.0
(8Q)(9Q)
0.048;-18453.8
8K(9Q)
0.029;-32917.5
8K(9K)
0.048;-23891.3
TQ(8T)
0.052;-27480.0
K(8TJ)
0.026;-32917.5
Q(8TQ)
0.032;-25087.5
KK(8T)
0.062;-22695.0
