AAAA
0.302;-1390.0
5AAA
0.256;-5023.8
9AAA
0.234;-4088.7
KAAA
0.325;-3153.7
4A(2A)
0.210;-8062.5
(2A)(7A)
0.210;-5831.3
A(2TA)
0.220;-6660.0
QA(2A)
0.228;-6192.5
2A(4A)
0.254;-8062.5
26AA
0.192;-9125.0
AA(29)
0.219;-6893.7
2A(QA)
0.203;-6192.5
A(34A)
0.191;-7828.7
6A(3A)
0.251;-7361.2
(3A)(9A)
0.302;-5130.0
A(3QA)
0.279;-5958.8
AA(34)
0.236;-7828.7
3A(7A)
0.211;-7127.5
39AA
0.201;-8190.0
AA(3Q)
0.262;-5958.8
(4A)(5A)
0.294;-5831.3
A(48A)
0.247;-6660.0
TA(4A)
0.256;-6192.5
(4A)(KA)
0.316;-3961.2
46AA
0.194;-8657.5
AA(49)
0.212;-6426.2
4A(QA)
0.231;-5725.0
A(56A)
0.231;-6893.7
8A(5A)
0.281;-6426.2
(5A)(JA)
0.306;-4195.0
55AA
0.244;-7127.5
AA(58)
0.201;-6426.2
5A(JA)
0.287;-5725.0
5KAA
0.196;-6787.5
8A(6A)
0.201;-6192.5
(6A)(JA)
0.277;-3961.2
66AA
0.223;-6660.0
AA(69)
0.247;-5958.8
6A(QA)
0.279;-5257.5
A(78A)
0.238;-5958.8
TA(7A)
0.269;-5491.2
(7A)(KA)
0.258;-3260.0
79AA
0.227;-7255.0
AA(7Q)
0.252;-5023.8
(8A)(9A)
0.292;-3961.2
A(8QA)
0.240;-4790.0
AA(89)
0.230;-5491.2
8A(QA)
0.240;-4790.0
A(9TA)
0.224;-5023.8
QA(9A)
0.286;-4556.2
9A(JA)
0.292;-4790.0
9KAA
0.185;-5852.5
QA(TA)
0.308;-4322.5
TA(QA)
0.297;-4322.5
A(JQA)
0.264;-4088.8
AA(JQ)
0.272;-4088.8
(QA)(KA)
0.365;-2091.3
KKAA
0.301;-3387.5
2(25A)
0.153;-10633.8
27(2A)
0.206;-10166.2
(2T)(2A)
0.173;-7935.0
2(2KA)
0.190;-8763.8
(236A)
0.144;-11696.2
(23TA)
0.199;-10761.2
33(2A)
0.161;-10867.5
(36)(2A)
0.191;-10166.2
3(29A)
0.189;-10995.0
3J(2A)
0.167;-10527.5
(245A)
0.135;-11696.2
(249A)
0.156;-10761.2
(24KA)
0.162;-9826.2
46(2A)
0.161;-11462.5
(49)(2A)
0.208;-9231.2
4(2QA)
0.186;-10060.0
6(25A)
0.194;-11228.7
T(25A)
0.163;-10293.8
5(26A)
0.194;-11228.7
58(2A)
0.183;-10761.2
(5J)(2A)
0.175;-8530.0
6(26A)
0.151;-9465.0
T(26A)
0.199;-10060.0
6(27A)
0.172;-10761.2
69(2A)
0.168;-10293.8
(6Q)(2A)
0.186;-8062.5
(279A)
0.191;-10060.0
(27KA)
0.163;-9125.0
79(2A)
0.143;-10060.0
(7Q)(2A)
0.231;-7828.8
(28TA)
0.214;-9592.5
88(2A)
0.213;-8530.0
(8J)(2A)
0.226;-7828.8
9(29A)
0.223;-8062.5
K(29A)
0.211;-8657.5
9(2QA)
0.191;-8891.2
J(2TA)
0.195;-8891.2
TJ(2A)
0.177;-8891.2
(2JQA)
0.198;-8423.7
J(2KA)
0.228;-8190.0
(QK)(2A)
0.185;-6426.2
22(4A)
0.153;-10867.5
226A
0.165;-11930.0
2A(29)
0.157;-9698.8
22(QA)
0.220;-8997.5
2(34A)
0.116;-12163.8
26(3A)
0.132;-11696.2
(29)(3A)
0.230;-9465.0
2(3QA)
0.191;-10293.8
A(234)
0.163;-12163.8
(23)(7A)
0.173;-9932.5
9A(23)
0.170;-10995.0
A(23Q)
0.171;-10293.8
2A(34)
0.170;-12163.8
2A(36)
0.171;-11696.2
2A(38)
0.166;-11228.7
2A(3T)
0.171;-10761.2
2A(3Q)
0.177;-10293.8
2(45A)
0.186;-11696.2
27(4A)
0.158;-11228.7
(2T)(4A)
0.177;-8997.5
2(4KA)
0.173;-9826.2
A(246)
0.168;-11462.5
(24)(9A)
0.167;-9231.2
JA(24)
0.200;-10293.8
24(5A)
0.159;-11696.2
24(7A)
0.151;-11228.7
24(9A)
0.213;-10761.2
24(JA)
0.140;-10293.8
24(KA)
0.168;-9826.2
26(5A)
0.136;-11228.7
(29)(5A)
0.228;-8997.5
2(5QA)
0.171;-9826.2
A(256)
0.133;-11228.7
(25)(9A)
0.179;-8997.5
JA(25)
0.196;-10060.0
25(6A)
0.197;-11228.7
25(8A)
0.232;-10761.2
25(TA)
0.143;-10293.8
25(QA)
0.214;-9826.2
(26)(6A)
0.222;-7935.0
2(69A)
0.209;-10293.8
2J(6A)
0.188;-9826.2
(26)(7A)
0.147;-9231.2
9A(26)
0.168;-10293.8
A(26Q)
0.229;-9592.5
2A(67)
0.172;-10761.2
2A(69)
0.189;-10293.8
2A(6J)
0.150;-9826.2
2A(6K)
0.166;-9358.8
(29)(7A)
0.201;-8530.0
2(7QA)
0.179;-9358.8
A(278)
0.236;-10293.8
(27)(JA)
0.224;-8062.5
KA(27)
0.174;-9125.0
2A(79)
0.182;-10060.0
2A(7J)
0.182;-9592.5
2A(7K)
0.207;-9125.0
(2T)(8A)
0.240;-8062.5
2(8KA)
0.188;-8891.2
A(28T)
0.202;-9592.5
(28)(KA)
0.229;-7361.2
28(TA)
0.208;-9592.5
28(QA)
0.202;-9125.0
(29)(9A)
0.208;-6532.5
2(9QA)
0.198;-8891.2
A(29T)
0.221;-9358.8
(29)(KA)
0.288;-7127.5
29(JA)
0.213;-9125.0
29(KA)
0.223;-8657.5
2J(TA)
0.189;-8891.2
(2T)(JA)
0.175;-7361.2
KA(2T)
0.242;-8423.7
2A(TQ)
0.204;-8657.5
2(JQA)
0.214;-8423.7
A(2JQ)
0.175;-8423.7
2A(JQ)
0.234;-8423.7
2(QKA)
0.224;-7956.2
2Q(KA)
0.209;-7956.2
33(3A)
0.213;-9103.8
(36)(3A)
0.201;-8402.5
3(39A)
0.172;-9231.2
3J(3A)
0.162;-8763.8
(345A)
0.135;-11462.5
(349A)
0.180;-10527.5
(34KA)
0.184;-9592.5
46(3A)
0.119;-11228.7
(49)(3A)
0.170;-8997.5
4(3QA)
0.144;-9826.2
6(35A)
0.213;-10995.0
T(35A)
0.149;-10060.0
5(36A)
0.191;-10995.0
58(3A)
0.179;-10527.5
(5J)(3A)
0.200;-8296.2
6(36A)
0.202;-9231.2
T(36A)
0.161;-9826.2
6(37A)
0.169;-10527.5
69(3A)
0.240;-10060.0
(6Q)(3A)
0.172;-7828.8
(379A)
0.156;-9826.2
(37KA)
0.204;-8891.2
79(3A)
0.187;-9826.2
(7Q)(3A)
0.187;-7595.0
(38TA)
0.237;-9358.8
88(3A)
0.225;-8296.2
(8J)(3A)
0.198;-7595.0
9(39A)
0.218;-7828.7
K(39A)
0.210;-8423.7
9(3QA)
0.208;-8657.5
J(3TA)
0.234;-8657.5
TJ(3A)
0.183;-8657.5
(3JQA)
0.172;-8190.0
J(3KA)
0.273;-7956.2
(QK)(3A)
0.205;-6192.5
33(5A)
0.187;-10166.2
337A
0.215;-11228.7
3A(3T)
0.205;-8997.5
33(KA)
0.213;-8296.2
3(46A)
0.173;-11228.7
38(4A)
0.227;-10761.2
(3J)(4A)
0.207;-8530.0
4A(34)
0.222;-10166.2
A(347)
0.188;-10995.0
(34)(TA)
0.207;-8763.8
QA(34)
0.150;-9826.2
345A
0.167;-12992.5
347A
0.174;-12525.0
349A
0.153;-12057.5
34JA
0.143;-11590.0
34KA
0.190;-11122.5
37(5A)
0.148;-10761.2
(3T)(5A)
0.237;-8530.0
3(5KA)
0.164;-9358.8
A(357)
0.164;-10761.2
(35)(TA)
0.183;-8530.0
QA(35)
0.227;-9592.5
356A
0.183;-12525.0
358A
0.185;-12057.5
35TA
0.125;-11590.0
35QA
0.161;-11122.5
(37)(6A)
0.187;-8997.5
3(6TA)
0.239;-9826.2
3Q(6A)
0.146;-9358.8
(36)(8A)
0.165;-8763.8
TA(36)
0.161;-9826.2
A(36K)
0.200;-9125.0
6A(38)
0.216;-10293.8
6A(3T)
0.221;-9826.2
6A(3Q)
0.181;-9358.8
37(7A)
0.235;-8763.8
(3T)(7A)
0.208;-8062.5
3(7KA)
0.165;-8891.2
A(379)
0.150;-9826.2
(37)(QA)
0.241;-7595.0
7A(38)
0.228;-10060.0
7A(3T)
0.199;-9592.5
7A(3Q)
0.246;-9125.0
38(8A)
0.270;-8296.2
(3J)(8A)
0.266;-7595.0
8A(38)
0.213;-8296.2
A(38J)
0.245;-9125.0
388A
0.198;-9826.2
38TA
0.138;-10888.8
38QA
0.223;-10421.2
(3T)(9A)
0.217;-7595.0
3(9KA)
0.221;-8423.7
A(39J)
0.235;-8891.2
399A
0.178;-9358.8
39JA
0.169;-10421.2
39KA
0.188;-9953.7
3Q(TA)
0.174;-8423.7
(3T)(QA)
0.237;-6893.7
TA(3J)
0.199;-8657.5
TA(3K)
0.210;-8190.0
3(JKA)
0.220;-7956.2
A(3JK)
0.247;-7956.2
JA(3K)
0.225;-7956.2
QA(3Q)
0.256;-6426.2
3QKA
0.194;-9252.5
45(4A)
0.214;-9698.8
(48)(4A)
0.205;-7467.5
4(4JA)
0.201;-8296.2
4K(4A)
0.216;-7828.7
(459A)
0.229;-10060.0
(45KA)
0.169;-9125.0
57(4A)
0.167;-10527.5
(5T)(4A)
0.217;-8296.2
5(4KA)
0.205;-9125.0
(469A)
0.172;-9826.2
(46KA)
0.208;-8891.2
68(4A)
0.144;-10060.0
(6J)(4A)
0.180;-7828.8
7(47A)
0.175;-8530.0
J(47A)
0.210;-9125.0
78(4A)
0.171;-9826.2
(7J)(4A)
0.202;-7595.0
8(48A)
0.198;-8062.5
Q(48A)
0.239;-8657.5
(8T)(4A)
0.199;-7595.0
8(4KA)
0.170;-8423.7
(49QA)
0.177;-8423.7
9(4JA)
0.240;-8657.5
9K(4A)
0.239;-8190.0
TT(4A)
0.193;-7127.5
(TK)(4A)
0.242;-6426.2
J(4QA)
0.224;-7956.2
K(4QA)
0.212;-7488.8
44(5A)
0.150;-9698.8
447A
0.184;-10761.2
4A(4T)
0.210;-8530.0
44(KA)
0.169;-7828.7
4(57A)
0.181;-10527.5
49(5A)
0.163;-10060.0
(4Q)(5A)
0.189;-7828.8
6A(45)
0.207;-10761.2
A(459)
0.143;-10060.0
(45)(QA)
0.233;-7828.8
5A(46)
0.184;-10761.2
5A(48)
0.164;-10293.8
5A(4T)
0.223;-9826.2
5A(4Q)
0.203;-9358.8
46(6A)
0.248;-8997.5
(49)(6A)
0.181;-8296.2
4(6QA)
0.193;-9125.0
A(467)
0.165;-10293.8
(46)(TA)
0.189;-8062.5
QA(46)
0.181;-9125.0
467A
0.167;-11823.8
469A
0.143;-11356.2
46JA
0.205;-10888.8
46KA
0.191;-10421.2
49(7A)
0.186;-9592.5
(4Q)(7A)
0.273;-7361.2
8A(47)
0.205;-9826.2
A(47J)
0.161;-9125.0
477A
0.169;-10060.0
479A
0.225;-11122.5
47JA
0.192;-10655.0
47KA
0.164;-10187.5
4T(8A)
0.223;-9125.0
(4K)(8A)
0.215;-6893.7
TA(48)
0.194;-9125.0
A(48K)
0.189;-8423.7
8A(4T)
0.181;-9125.0
8A(4Q)
0.211;-8657.5
49(9A)
0.214;-7595.0
(4Q)(9A)
0.194;-6893.7
TA(49)
0.247;-8891.2
A(49K)
0.211;-8190.0
9A(4J)
0.224;-8657.5
9A(4K)
0.222;-8190.0
4(TQA)
0.224;-8190.0
A(4TJ)
0.221;-8423.7
4TTA
0.197;-8657.5
4TQA
0.170;-9720.0
(4Q)(JA)
0.272;-6426.2
QA(4J)
0.204;-7956.2
4JQA
0.146;-9486.2
(4K)(QA)
0.249;-5958.8
QA(4K)
0.214;-7488.8
5(56A)
0.149;-8997.5
58(5A)
0.205;-8530.0
(5J)(5A)
0.290;-6298.7
6(56A)
0.172;-8763.8
T(56A)
0.196;-9358.8
6(57A)
0.186;-10060.0
69(5A)
0.221;-9592.5
(6Q)(5A)
0.246;-7361.2
(579A)
0.196;-9358.8
(57KA)
0.167;-8423.7
79(5A)
0.240;-9358.8
(7Q)(5A)
0.198;-7127.5
(58TA)
0.159;-8891.2
88(5A)
0.235;-7828.7
(8J)(5A)
0.214;-7127.5
9(59A)
0.220;-7361.2
K(59A)
0.224;-7956.2
9(5QA)
0.178;-8190.0
J(5TA)
0.180;-8190.0
TJ(5A)
0.215;-8190.0
(5JQA)
0.215;-7722.5
J(5KA)
0.211;-7488.8
(QK)(5A)
0.244;-5725.0
55(7A)
0.228;-8763.8
559A
0.221;-9826.2
5A(5Q)
0.205;-7595.0
(57)(6A)
0.198;-8530.0
5(6TA)
0.183;-9358.8
5Q(6A)
0.206;-8891.2
(56)(8A)
0.218;-8296.2
TA(56)
0.187;-9358.8
A(56K)
0.183;-8657.5
6A(58)
0.212;-9826.2
6A(5T)
0.236;-9358.8
6A(5Q)
0.172;-8891.2
57(7A)
0.194;-8296.2
(5T)(7A)
0.190;-7595.0
5(7KA)
0.196;-8423.7
A(579)
0.195;-9358.8
(57)(QA)
0.245;-7127.5
7A(58)
0.200;-9592.5
7A(5T)
0.224;-9125.0
7A(5Q)
0.176;-8657.5
58(8A)
0.215;-7828.7
(5J)(8A)
0.249;-7127.5
8A(58)
0.223;-7828.7
A(58J)
0.179;-8657.5
588A
0.206;-9358.8
58TA
0.208;-10421.2
58QA
0.181;-9953.7
(5T)(9A)
0.209;-7127.5
5(9KA)
0.215;-7956.2
A(59J)
0.189;-8423.7
599A
0.241;-8891.2
59JA
0.213;-9953.7
59KA
0.211;-9486.2
5Q(TA)
0.204;-7956.2
(5T)(QA)
0.194;-6426.2
TA(5J)
0.244;-8190.0
TA(5K)
0.173;-7722.5
5(JKA)
0.244;-7488.8
A(5JK)
0.224;-7488.8
JA(5K)
0.180;-7488.8
QA(5Q)
0.228;-5958.8
5QKA
0.172;-8785.0
67(6A)
0.192;-8296.2
(6T)(6A)
0.248;-6065.0
6(6KA)
0.213;-6893.7
(67TA)
0.159;-8891.2
77(6A)
0.201;-8062.5
(7T)(6A)
0.263;-7361.2
7(6KA)
0.232;-8190.0
(68JA)
0.226;-8423.7
(89)(6A)
0.173;-7361.2
8(6QA)
0.210;-8190.0
T(69A)
0.229;-8423.7
9(6TA)
0.190;-8423.7
9Q(6A)
0.194;-7956.2
Q(6TA)
0.235;-7722.5
(TQ)(6A)
0.219;-6192.5
(6JKA)
0.274;-7255.0
JK(6A)
0.229;-7255.0
K(6KA)
0.244;-5257.5
668A
0.158;-9592.5
6A(6J)
0.218;-7361.2
(67)(7A)
0.252;-6532.5
6(7TA)
0.208;-8891.2
6Q(7A)
0.201;-8423.7
(67)(9A)
0.233;-7595.0
JA(67)
0.229;-8657.5
67(8A)
0.196;-9358.8
67(TA)
0.187;-8891.2
67(QA)
0.190;-8423.7
(68)(8A)
0.215;-6065.0
6(8JA)
0.212;-8423.7
6K(8A)
0.187;-7956.2
(68)(JA)
0.202;-6893.7
KA(68)
0.249;-7956.2
6A(8T)
0.192;-8657.5
6A(8Q)
0.212;-8190.0
6(9TA)
0.265;-8423.7
6Q(9A)
0.175;-7956.2
(69)(JA)
0.246;-6660.0
KA(69)
0.206;-7722.5
6A(9J)
0.195;-8190.0
6A(9K)
0.198;-7722.5
(6Q)(TA)
0.227;-6192.5
JA(6T)
0.170;-7956.2
6T(JA)
0.236;-7956.2
6T(KA)
0.282;-7488.8
6Q(JA)
0.209;-7488.8
(6J)(KA)
0.286;-5725.0
6J(KA)
0.218;-7255.0
6K(QA)
0.238;-7021.2
6A(QK)
0.205;-7021.2
(78)(7A)
0.228;-6065.0
7(7JA)
0.245;-6893.7
7K(7A)
0.274;-6426.2
(78QA)
0.194;-7956.2
8(7TA)
0.196;-8423.7
8Q(7A)
0.211;-7956.2
J(79A)
0.256;-7956.2
9T(7A)
0.205;-8190.0
(9K)(7A)
0.259;-5958.8
K(7TA)
0.217;-7255.0
T(7KA)
0.192;-7255.0
JJ(7A)
0.216;-5958.8
(7QKA)
0.273;-6787.5
777A
0.242;-7828.8
7A(7T)
0.225;-7127.5
77(KA)
0.297;-6426.2
7(8TA)
0.177;-8423.7
7Q(8A)
0.214;-7956.2
(78)(TA)
0.275;-6893.7
QA(78)
0.202;-7956.2
789A
0.190;-10187.5
78JA
0.207;-9720.0
78KA
0.159;-9252.5
7J(9A)
0.199;-7956.2
(79)(TA)
0.260;-6660.0
QA(79)
0.279;-7722.5
79TA
0.191;-9720.0
79QA
0.207;-9252.5
(7J)(TA)
0.304;-6192.5
TA(7T)
0.245;-6426.2
A(7TK)
0.189;-7255.0
TA(7Q)
0.187;-7488.8
7J(JA)
0.240;-5958.8
(7J)(QA)
0.214;-5725.0
JA(7Q)
0.213;-7255.0
7Q(QA)
0.240;-5491.2
7QQA
0.199;-7021.2
7KKA
0.228;-6553.8
8(8JA)
0.232;-6426.2
8K(8A)
0.259;-5958.8
(89KA)
0.232;-7255.0
9J(8A)
0.204;-7722.5
(8TJA)
0.206;-7488.8
(TJ)(8A)
0.296;-5958.8
J(8JA)
0.226;-5725.0
JQ(8A)
0.174;-7021.2
Q(8KA)
0.253;-6553.8
889A
0.172;-8423.7
8A(8Q)
0.241;-6192.5
(8T)(9A)
0.211;-6426.2
8(9KA)
0.191;-7255.0
A(89J)
0.236;-7722.5
899A
0.203;-8190.0
89JA
0.178;-9252.5
89KA
0.190;-8785.0
8Q(TA)
0.235;-7255.0
(8T)(QA)
0.231;-5725.0
TA(8J)
0.259;-7488.8
TA(8K)
0.237;-7021.2
8(JKA)
0.256;-6787.5
A(8JK)
0.242;-6787.5
JA(8K)
0.244;-6787.5
QA(8Q)
0.227;-5257.5
8QKA
0.167;-8083.8
9T(9A)
0.210;-6192.5
(9K)(9A)
0.274;-3961.2
K(9TA)
0.210;-6787.5
T(9KA)
0.231;-6787.5
JJ(9A)
0.263;-5491.2
(9QKA)
0.216;-6320.0
999A
0.261;-6426.2
9A(9Q)
0.240;-5725.0
(9J)(TA)
0.291;-5725.0
TA(9T)
0.221;-5958.8
A(9TK)
0.238;-6787.5
TA(9Q)
0.217;-7021.2
9J(JA)
0.281;-5491.2
(9J)(QA)
0.212;-5257.5
JA(9Q)
0.251;-6787.5
9Q(QA)
0.237;-5023.8
9QQA
0.211;-6553.8
9KKA
0.311;-6086.2
T(TKA)
0.206;-5023.8
JJ(TA)
0.230;-5257.5
(TQKA)
0.245;-6086.2
TTTA
0.195;-5725.0
TA(TK)
0.267;-5023.8
(TK)(JA)
0.271;-4790.0
KA(TJ)
0.239;-6320.0
TA(JK)
0.225;-6320.0
(TQ)(KA)
0.315;-4556.2
(TK)(KA)
0.339;-2792.5
J(JKA)
0.303;-4556.2
(QK)(JA)
0.274;-4322.5
JJ(KA)
0.293;-4556.2
QA(JQ)
0.232;-4556.2
JQKA
0.216;-7382.5
QK(QA)
0.299;-4088.8
QK(KA)
0.277;-3855.0
22(24)
0.155;-12142.5
22(28)
0.153;-11207.5
22(2Q)
0.176;-10272.5
24(23)
0.122;-13438.7
(23)(27)
0.199;-11207.5
2(23T)
0.142;-12036.2
2Q(23)
0.201;-11568.8
23(25)
0.140;-13205.0
2237
0.110;-14267.5
22(3T)
0.151;-12036.2
23(2K)
0.147;-11335.0
2(246)
0.133;-12737.5
28(24)
0.182;-12270.0
(24)(2J)
0.170;-10038.8
2244
0.139;-13205.0
22(47)
0.177;-12503.8
24(2T)
0.192;-11802.5
224Q
0.169;-12865.0
26(25)
0.165;-12503.8
(25)(29)
0.175;-10272.5
2(25Q)
0.180;-11101.2
22(56)
0.137;-12503.8
25(29)
0.171;-11802.5
225J
0.146;-12865.0
26(26)
0.189;-10740.0
(26)(29)
0.173;-10038.8
2(26Q)
0.215;-10867.5
22(67)
0.116;-12036.2
26(2T)
0.164;-11335.0
226Q
0.153;-12397.5
28(27)
0.145;-11568.8
(27)(2J)
0.197;-9337.5
2277
0.137;-11802.5
22(7T)
0.145;-11101.2
27(2K)
0.175;-10400.0
2(28T)
0.130;-10867.5
2Q(28)
0.127;-10400.0
28(2T)
0.179;-10867.5
228Q
0.121;-11930.0
2T(29)
0.189;-10633.8
(29)(2K)
0.160;-8402.5
229J
0.175;-11930.0
2T(2T)
0.225;-8870.0
(2T)(2K)
0.166;-8168.7
22TQ
0.127;-11462.5
2Q(2J)
0.204;-9698.8
2J(2K)
0.192;-9465.0
22QQ
0.169;-9465.0
3(234)
0.120;-13205.0
36(23)
0.128;-12737.5
(23)(39)
0.172;-10506.2
3(23Q)
0.149;-11335.0
5(234)
0.137;-14267.5
9(234)
0.111;-13332.5
K(234)
0.139;-12397.5
4(237)
0.112;-13800.0
49(23)
0.131;-13332.5
(23)(4Q)
0.181;-11101.2
(2357)
0.161;-13566.2
(235J)
0.183;-12631.3
(23)(56)
0.127;-12270.0
5(239)
0.146;-13098.7
5J(23)
0.138;-12631.3
(2367)
0.148;-13332.5
(236J)
0.134;-12397.5
(23)(67)
0.151;-11802.5
6(23T)
0.169;-12631.3
6Q(23)
0.163;-12163.8
9(237)
0.155;-12631.3
K(237)
0.140;-11696.2
7(23T)
0.135;-12397.5
7Q(23)
0.135;-11930.0
T(238)
0.154;-12163.8
8(239)
0.140;-12397.5
8J(23)
0.163;-11930.0
(239T)
0.174;-11930.0
99(23)
0.200;-10633.8
(23)(9Q)
0.207;-9932.5
(23TQ)
0.177;-11228.7
T(23Q)
0.178;-11228.7
Q(23J)
0.178;-10995.0
(23)(JK)
0.151;-9231.2
QK(23)
0.151;-10527.5
23(35)
0.139;-12971.3
33(28)
0.174;-12270.0
233T
0.115;-13332.5
23(3K)
0.189;-11101.2
(24)(36)
0.170;-12503.8
3(249)
0.137;-13332.5
3J(24)
0.166;-12865.0
(34)(25)
0.134;-12737.5
27(34)
0.176;-13800.0
2(34T)
0.131;-13098.7
(34)(2K)
0.194;-10867.5
34(26)
0.111;-14033.8
34(28)
0.107;-13566.2
34(2T)
0.144;-13098.7
34(2Q)
0.125;-12631.3
(25)(35)
0.141;-10973.8
3(258)
0.150;-13332.5
3T(25)
0.179;-12865.0
(25)(3K)
0.151;-10633.8
27(35)
0.110;-13566.2
2(35T)
0.162;-12865.0
(35)(2K)
0.156;-10633.8
35(27)
0.190;-13566.2
35(29)
0.130;-13098.7
35(2J)
0.126;-12631.3
35(2K)
0.161;-12163.8
37(26)
0.117;-13332.5
(26)(3T)
0.183;-11101.2
3(26K)
0.141;-11930.0
2(368)
0.185;-13098.7
(36)(2J)
0.192;-10867.5
2K(36)
0.172;-11930.0
23(68)
0.120;-13098.7
23(6T)
0.153;-12631.3
23(6Q)
0.148;-12163.8
3(278)
0.131;-12865.0
3T(27)
0.138;-12397.5
(27)(3K)
0.188;-10166.2
29(37)
0.200;-12631.3
2(37Q)
0.168;-11930.0
23(78)
0.173;-12865.0
23(7T)
0.157;-12397.5
23(7Q)
0.145;-11930.0
3(289)
0.157;-12397.5
3J(28)
0.151;-11930.0
(38)(29)
0.142;-10867.5
2J(38)
0.151;-11930.0
38(29)
0.147;-12397.5
38(2J)
0.135;-11930.0
38(2K)
0.159;-11462.5
3T(29)
0.147;-11930.0
(29)(3K)
0.150;-9698.8
2J(39)
0.140;-11696.2
39(2T)
0.180;-11930.0
39(2Q)
0.138;-11462.5
(2T)(3T)
0.223;-8636.2
3(2TK)
0.122;-10995.0
2(3TQ)
0.183;-11228.7
23(TJ)
0.157;-11462.5
23(TK)
0.150;-10995.0
(2J)(3K)
0.200;-9231.2
2K(3J)
0.153;-10761.2
23(JK)
0.191;-10761.2
(3Q)(2K)
0.215;-8997.5
(2K)(3K)
0.229;-7233.8
4(246)
0.174;-12270.0
48(24)
0.152;-11802.5
(24)(4J)
0.169;-9571.3
5(245)
0.144;-12270.0
9(245)
0.138;-12865.0
K(245)
0.140;-11930.0
5(248)
0.157;-13098.7
5T(24)
0.148;-12631.3
(24)(5K)
0.153;-10400.0
9(246)
0.151;-12631.3
K(246)
0.166;-11696.2
6(249)
0.142;-12631.3
6J(24)
0.150;-12163.8
(2478)
0.157;-12631.3
(247Q)
0.194;-11696.2
7(249)
0.182;-12397.5
7J(24)
0.125;-11930.0
(2489)
0.188;-12163.8
(248K)
0.129;-11228.7
8T(24)
0.145;-11930.0
(24)(8K)
0.164;-9698.8
Q(249)
0.179;-11228.7
(24)(9J)
0.207;-9932.5
T(24T)
0.172;-9932.5
T(24J)
0.174;-11228.7
TK(24)
0.148;-10761.2
(24)(JQ)
0.208;-9231.2
QQ(24)
0.189;-8997.5
24(45)
0.174;-12503.8
44(28)
0.198;-11802.5
244T
0.118;-12865.0
24(4K)
0.234;-10633.8
(25)(47)
0.155;-11802.5
4(25T)
0.162;-12631.3
4Q(25)
0.126;-12163.8
(45)(27)
0.170;-11802.5
29(45)
0.121;-12865.0
2(45Q)
0.170;-12163.8
24(56)
0.114;-13566.2
24(58)
0.132;-13098.7
24(5T)
0.140;-12631.3
24(5Q)
0.144;-12163.8
4(267)
0.142;-13098.7
49(26)
0.126;-12631.3
(26)(4Q)
0.177;-10400.0
27(46)
0.137;-13098.7
2(46T)
0.131;-12397.5
(46)(2K)
0.204;-10166.2
46(28)
0.145;-12865.0
46(2T)
0.150;-12397.5
46(2Q)
0.200;-11930.0
(27)(47)
0.191;-9805.0
4(27T)
0.164;-12163.8
4Q(27)
0.153;-11696.2
(47)(29)
0.167;-10867.5
2J(47)
0.156;-11930.0
47(28)
0.123;-12631.3
47(2T)
0.149;-12163.8
47(2Q)
0.169;-11696.2
(28)(48)
0.205;-9337.5
4(28J)
0.177;-11696.2
4K(28)
0.182;-11228.7
(48)(2J)
0.138;-10166.2
2K(48)
0.187;-11228.7
24(8T)
0.122;-11930.0
24(8Q)
0.162;-11462.5
4(29T)
0.210;-11696.2
4Q(29)
0.138;-11228.7
(49)(2J)
0.142;-9932.5
2K(49)
0.174;-10995.0
24(9J)
0.217;-11462.5
24(9K)
0.218;-10995.0
(2T)(4Q)
0.249;-9465.0
2J(4T)
0.165;-11228.7
4T(2J)
0.187;-11228.7
4T(2K)
0.154;-10761.2
4Q(2J)
0.207;-10761.2
(4J)(2K)
0.202;-8997.5
4J(2K)
0.193;-10527.5
4K(2Q)
0.174;-10293.8
24(QK)
0.165;-10293.8
(25)(56)
0.153;-10272.5
5(259)
0.170;-11101.2
5J(25)
0.188;-10633.8
(2567)
0.151;-12865.0
(256J)
0.167;-11930.0
(25)(67)
0.154;-11335.0
6(25T)
0.158;-12163.8
6Q(25)
0.153;-11696.2
9(257)
0.153;-12163.8
K(257)
0.222;-11228.7
7(25T)
0.168;-11930.0
7Q(25)
0.192;-11462.5
T(258)
0.165;-11696.2
8(259)
0.179;-11930.0
8J(25)
0.167;-11462.5
(259T)
0.150;-11462.5
99(25)
0.143;-10166.2
(25)(9Q)
0.177;-9465.0
(25TQ)
0.172;-10761.2
T(25Q)
0.172;-10761.2
Q(25J)
0.186;-10527.5
(25)(JK)
0.230;-8763.8
QK(25)
0.153;-10060.0
25(57)
0.180;-11568.8
55(2T)
0.137;-10867.5
255Q
0.152;-11930.0
57(26)
0.185;-12865.0
(26)(5T)
0.186;-10633.8
5(26K)
0.130;-11462.5
2(568)
0.130;-12631.3
(56)(2J)
0.198;-10400.0
2K(56)
0.143;-11462.5
25(68)
0.186;-12631.3
25(6T)
0.158;-12163.8
25(6Q)
0.175;-11696.2
5(278)
0.196;-12397.5
5T(27)
0.172;-11930.0
(27)(5K)
0.173;-9698.8
29(57)
0.164;-12163.8
2(57Q)
0.194;-11462.5
25(78)
0.195;-12397.5
25(7T)
0.200;-11930.0
25(7Q)
0.146;-11462.5
5(289)
0.158;-11930.0
5J(28)
0.163;-11462.5
(58)(29)
0.196;-10400.0
2J(58)
0.133;-11462.5
58(29)
0.141;-11930.0
58(2J)
0.171;-11462.5
58(2K)
0.135;-10995.0
5T(29)
0.164;-11462.5
(29)(5K)
0.182;-9231.2
2J(59)
0.173;-11228.7
59(2T)
0.189;-11462.5
59(2Q)
0.209;-10995.0
(2T)(5T)
0.212;-8168.7
5(2TK)
0.205;-10527.5
2(5TQ)
0.179;-10761.2
25(TJ)
0.164;-10995.0
25(TK)
0.139;-10527.5
(2J)(5K)
0.199;-8763.8
2K(5J)
0.162;-10293.8
25(JK)
0.191;-10293.8
(5Q)(2K)
0.236;-8530.0
(2K)(5K)
0.226;-6766.2
6(268)
0.156;-10867.5
6T(26)
0.183;-10400.0
(26)(6K)
0.193;-8168.7
T(267)
0.164;-11696.2
7(268)
0.160;-12163.8
7T(26)
0.164;-11696.2
(26)(7K)
0.151;-9465.0
J(268)
0.166;-11228.7
89(26)
0.146;-11696.2
(26)(8Q)
0.199;-9465.0
(269J)
0.156;-10995.0
(26)(9T)
0.224;-9698.8
9(26K)
0.134;-10527.5
(26TK)
0.176;-10293.8
TQ(26)
0.188;-10527.5
K(26J)
0.152;-10060.0
Q(26Q)
0.213;-8530.0
KK(26)
0.173;-8062.5
66(29)
0.223;-10633.8
266J
0.177;-11696.2
67(27)
0.194;-10867.5
(27)(6T)
0.160;-10166.2
6(27K)
0.217;-10995.0
2(679)
0.161;-11930.0
(67)(2Q)
0.165;-9698.8
27(68)
0.135;-12163.8
27(6T)
0.139;-11696.2
27(6Q)
0.162;-11228.7
68(28)
0.212;-10400.0
(28)(6J)
0.186;-9698.8
28(68)
0.150;-10400.0
2(68J)
0.154;-11228.7
2688
0.186;-11930.0
268T
0.157;-12992.5
268Q
0.157;-12525.0
(29)(6T)
0.210;-9698.8
6(29K)
0.219;-10527.5
2(69J)
0.145;-10995.0
2699
0.160;-11462.5
269J
0.187;-12525.0
269K
0.152;-12057.5
6Q(2T)
0.188;-10527.5
(6T)(2Q)
0.202;-8997.5
2T(6J)
0.124;-10761.2
2T(6K)
0.202;-10293.8
6(2JK)
0.152;-10060.0
2(6JK)
0.232;-10060.0
2J(6K)
0.177;-10060.0
2Q(6Q)
0.214;-8530.0
26QK
0.211;-11356.2
78(27)
0.135;-10400.0
(27)(7J)
0.160;-8168.7
8(278)
0.187;-10166.2
Q(278)
0.187;-10761.2
(27)(8T)
0.169;-9698.8
8(27K)
0.137;-10527.5
(279Q)
0.203;-10527.5
9(27J)
0.207;-10761.2
9K(27)
0.208;-10293.8
TT(27)
0.170;-9231.2
(27)(TK)
0.202;-8530.0
J(27Q)
0.176;-10060.0
K(27Q)
0.173;-9592.5
77(28)
0.136;-10400.0
277T
0.208;-11462.5
27(7K)
0.181;-9231.2
(28)(7T)
0.175;-9698.8
7(28K)
0.203;-10527.5
2(78T)
0.168;-11228.7
(78)(2K)
0.178;-8997.5
78(2T)
0.177;-11228.7
78(2Q)
0.223;-10761.2
(29)(79)
0.199;-8168.7
7(29Q)
0.169;-10527.5
2(79T)
0.186;-10995.0
(79)(2K)
0.211;-8763.8
79(2J)
0.161;-10761.2
79(2K)
0.173;-10293.8
7J(2T)
0.162;-10527.5
(7T)(2J)
0.211;-8997.5
2K(7T)
0.185;-10060.0
27(TQ)
0.215;-10293.8
7(2JQ)
0.237;-10060.0
2(7JQ)
0.176;-10060.0
27(JQ)
0.192;-10060.0
7(2QK)
0.193;-9592.5
7Q(2K)
0.181;-9592.5
88(28)
0.203;-8402.5
(28)(8J)
0.219;-7701.2
9(289)
0.215;-9465.0
K(289)
0.177;-10060.0
9(28Q)
0.169;-10293.8
J(28T)
0.206;-10293.8
TJ(28)
0.178;-10293.8
(28JQ)
0.190;-9826.2
J(28K)
0.144;-9592.5
(28)(QK)
0.165;-7828.8
88(2T)
0.177;-9465.0
288Q
0.207;-10527.5
8T(29)
0.151;-10761.2
(29)(8K)
0.234;-8530.0
2J(89)
0.167;-10527.5
89(2T)
0.220;-10761.2
89(2Q)
0.148;-10293.8
(2T)(8T)
0.226;-7467.5
8(2TK)
0.157;-9826.2
2(8TQ)
0.185;-10060.0
28(TJ)
0.163;-10293.8
28(TK)
0.231;-9826.2
(2J)(8K)
0.199;-8062.5
2K(8J)
0.204;-9592.5
28(JK)
0.158;-9592.5
(8Q)(2K)
0.213;-7828.8
(2K)(8K)
0.207;-6065.0
9(29J)
0.201;-8763.8
9K(29)
0.226;-8296.2
TT(29)
0.224;-8763.8
(29)(TK)
0.211;-8062.5
J(29Q)
0.221;-9592.5
K(29Q)
0.219;-9125.0
99(2T)
0.166;-8997.5
299Q
0.149;-10060.0
9J(2T)
0.211;-10060.0
(9T)(2J)
0.224;-8530.0
2K(9T)
0.167;-9592.5
29(TQ)
0.176;-9826.2
9(2JQ)
0.179;-9592.5
2(9JQ)
0.229;-9592.5
29(JQ)
0.192;-9592.5
9(2QK)
0.166;-9125.0
9Q(2K)
0.161;-9125.0
TT(2T)
0.241;-7000.0
(2T)(TK)
0.252;-6298.7
J(2TQ)
0.193;-9358.8
K(2TQ)
0.162;-8891.2
TT(2J)
0.213;-8296.2
2TTK
0.238;-9358.8
TK(2J)
0.178;-9125.0
2TJJ
0.199;-9592.5
2TJK
0.179;-10655.0
2(TQK)
0.198;-8891.2
TK(2K)
0.245;-7127.5
(2J)(JK)
0.253;-5831.3
QK(2J)
0.194;-8657.5
2J(JK)
0.221;-7361.2
(JQ)(2K)
0.227;-7127.5
(2K)(JK)
0.272;-5363.7
K(2QK)
0.273;-6660.0
2K(QK)
0.230;-6660.0
3335
0.152;-12737.5
3339
0.120;-11802.5
333K
0.150;-10867.5
36(34)
0.140;-12270.0
(34)(39)
0.140;-10038.8
3(34Q)
0.166;-10867.5
33(45)
0.137;-12503.8
34(38)
0.176;-11802.5
334T
0.162;-12865.0
33(4K)
0.172;-10633.8
(35)(37)
0.198;-10272.5
3(35T)
0.205;-11101.2
3Q(35)
0.166;-10633.8
35(37)
0.135;-11802.5
3359
0.136;-12865.0
33(5Q)
0.190;-10633.8
(36)(37)
0.230;-10038.8
3(36T)
0.159;-10867.5
3Q(36)
0.203;-10400.0
36(38)
0.188;-11335.0
336T
0.132;-12397.5
33(6K)
0.169;-10166.2
(37)(39)
0.192;-9337.5
3(37Q)
0.188;-10166.2
33(78)
0.189;-11101.2
37(3J)
0.191;-10400.0
337K
0.149;-11462.5
3T(38)
0.136;-10400.0
(38)(3K)
0.214;-8168.7
338T
0.148;-11930.0
33(8K)
0.219;-9698.8
(39)(3J)
0.255;-8402.5
3399
0.170;-10400.0
33(9Q)
0.168;-9698.8
(3T)(3J)
0.203;-8168.7
33TT
0.234;-9932.5
33(TK)
0.225;-9231.2
(3J)(3K)
0.212;-7467.5
33JK
0.203;-10527.5
33(QK)
0.174;-8763.8
45(34)
0.138;-12270.0
(34)(48)
0.223;-10038.8
4(34J)
0.156;-10867.5
4K(34)
0.177;-10400.0
(3459)
0.156;-12631.3
(345K)
0.191;-11696.2
57(34)
0.159;-13098.7
(34)(5T)
0.191;-10867.5
5(34K)
0.182;-11696.2
(3469)
0.137;-12397.5
(346K)
0.175;-11462.5
68(34)
0.113;-12631.3
(34)(6J)
0.185;-10400.0
7(347)
0.164;-11101.2
J(347)
0.190;-11696.2
78(34)
0.137;-12397.5
(34)(7J)
0.174;-10166.2
8(348)
0.212;-10633.8
Q(348)
0.192;-11228.7
(34)(8T)
0.152;-10166.2
8(34K)
0.165;-10995.0
(349Q)
0.196;-10995.0
9(34J)
0.211;-11228.7
9K(34)
0.163;-10761.2
TT(34)
0.193;-9698.8
(34)(TK)
0.148;-8997.5
J(34Q)
0.153;-10527.5
K(34Q)
0.194;-10060.0
44(35)
0.158;-12270.0
3447
0.178;-13332.5
34(4T)
0.165;-11101.2
44(3K)
0.130;-10400.0
4(357)
0.154;-13098.7
49(35)
0.150;-12631.3
(35)(4Q)
0.219;-10400.0
36(45)
0.136;-13332.5
3(459)
0.164;-12631.3
(45)(3Q)
0.153;-10400.0
35(46)
0.131;-13332.5
35(48)
0.160;-12865.0
35(4T)
0.164;-12397.5
35(4Q)
0.174;-11930.0
46(36)
0.169;-11568.8
(36)(49)
0.169;-10867.5
4(36Q)
0.149;-11696.2
3(467)
0.186;-12865.0
(46)(3T)
0.171;-10633.8
3Q(46)
0.148;-11696.2
3467
0.119;-14395.0
3469
0.144;-13927.5
346J
0.130;-13460.0
346K
0.120;-12992.5
49(37)
0.171;-12163.8
(37)(4Q)
0.175;-9932.5
38(47)
0.166;-12397.5
3(47J)
0.176;-11696.2
3477
0.151;-12631.3
3479
0.127;-13693.8
347J
0.144;-13226.2
347K
0.157;-12758.8
4T(38)
0.145;-11696.2
(38)(4K)
0.138;-9465.0
3T(48)
0.174;-11696.2
3(48K)
0.174;-10995.0
38(4T)
0.180;-11696.2
38(4Q)
0.165;-11228.7
49(39)
0.187;-10166.2
(39)(4Q)
0.214;-9465.0
3T(49)
0.142;-11462.5
3(49K)
0.199;-10761.2
39(4J)
0.134;-11228.7
39(4K)
0.171;-10761.2
4(3TQ)
0.166;-10761.2
3(4TJ)
0.187;-10995.0
34TT
0.153;-11228.7
34TQ
0.165;-12291.2
(3J)(4Q)
0.159;-8997.5
3Q(4J)
0.178;-10527.5
34JQ
0.129;-12057.5
(3Q)(4K)
0.248;-8530.0
3Q(4K)
0.166;-10060.0
5(356)
0.171;-11568.8
58(35)
0.211;-11101.2
(35)(5J)
0.184;-8870.0
6(356)
0.203;-11335.0
T(356)
0.158;-11930.0
6(357)
0.190;-12631.3
69(35)
0.165;-12163.8
(35)(6Q)
0.211;-9932.5
(3579)
0.198;-11930.0
(357K)
0.200;-10995.0
79(35)
0.129;-11930.0
(35)(7Q)
0.221;-9698.8
(358T)
0.156;-11462.5
88(35)
0.161;-10400.0
(35)(8J)
0.200;-9698.8
9(359)
0.161;-9932.5
K(359)
0.133;-10527.5
9(35Q)
0.210;-10761.2
J(35T)
0.169;-10761.2
TJ(35)
0.158;-10761.2
(35JQ)
0.164;-10293.8
J(35K)
0.150;-10060.0
(35)(QK)
0.208;-8296.2
55(37)
0.189;-11335.0
3559
0.174;-12397.5
35(5Q)
0.140;-10166.2
(36)(57)
0.176;-11101.2
5(36T)
0.159;-11930.0
5Q(36)
0.183;-11462.5
(56)(38)
0.149;-10867.5
3T(56)
0.141;-11930.0
3(56K)
0.192;-11228.7
36(58)
0.125;-12397.5
36(5T)
0.142;-11930.0
36(5Q)
0.178;-11462.5
57(37)
0.133;-10867.5
(37)(5T)
0.192;-10166.2
5(37K)
0.216;-10995.0
3(579)
0.159;-11930.0
(57)(3Q)
0.176;-9698.8
37(58)
0.160;-12163.8
37(5T)
0.166;-11696.2
37(5Q)
0.177;-11228.7
58(38)
0.232;-10400.0
(38)(5J)
0.157;-9698.8
38(58)
0.194;-10400.0
3(58J)
0.161;-11228.7
3588
0.160;-11930.0
358T
0.143;-12992.5
358Q
0.131;-12525.0
(39)(5T)
0.181;-9698.8
5(39K)
0.147;-10527.5
3(59J)
0.191;-10995.0
3599
0.137;-11462.5
359J
0.154;-12525.0
359K
0.157;-12057.5
5Q(3T)
0.180;-10527.5
(5T)(3Q)
0.227;-8997.5
3T(5J)
0.138;-10761.2
3T(5K)
0.167;-10293.8
5(3JK)
0.202;-10060.0
3(5JK)
0.169;-10060.0
3J(5K)
0.206;-10060.0
3Q(5Q)
0.155;-8530.0
35QK
0.158;-11356.2
67(36)
0.157;-10867.5
(36)(6T)
0.244;-8636.2
6(36K)
0.218;-9465.0
(367T)
0.155;-11462.5
77(36)
0.181;-10633.8
(36)(7T)
0.181;-9932.5
7(36K)
0.199;-10761.2
(368J)
0.185;-10995.0
(36)(89)
0.164;-9932.5
8(36Q)
0.144;-10761.2
T(369)
0.170;-10995.0
9(36T)
0.136;-10995.0
9Q(36)
0.154;-10527.5
Q(36T)
0.176;-10293.8
(36)(TQ)
0.197;-8763.8
(36JK)
0.168;-9826.2
JK(36)
0.161;-9826.2
K(36K)
0.245;-7828.7
3668
0.134;-12163.8
36(6J)
0.168;-9932.5
(37)(67)
0.226;-9103.8
6(37T)
0.153;-11462.5
6Q(37)
0.169;-10995.0
(67)(39)
0.170;-10166.2
3J(67)
0.165;-11228.7
67(38)
0.150;-11930.0
67(3T)
0.151;-11462.5
67(3Q)
0.206;-10995.0
(38)(68)
0.259;-8636.2
6(38J)
0.157;-10995.0
6K(38)
0.183;-10527.5
(68)(3J)
0.227;-9465.0
3K(68)
0.160;-10527.5
36(8T)
0.149;-11228.7
36(8Q)
0.188;-10761.2
6(39T)
0.178;-10995.0
6Q(39)
0.149;-10527.5
(69)(3J)
0.167;-9231.2
3K(69)
0.162;-10293.8
36(9J)
0.138;-10761.2
36(9K)
0.172;-10293.8
(3T)(6Q)
0.218;-8763.8
3J(6T)
0.176;-10527.5
6T(3J)
0.150;-10527.5
6T(3K)
0.138;-10060.0
6Q(3J)
0.196;-10060.0
(6J)(3K)
0.227;-8296.2
6J(3K)
0.136;-9826.2
6K(3Q)
0.196;-9592.5
36(QK)
0.228;-9592.5
(37)(78)
0.201;-8636.2
7(37J)
0.178;-9465.0
7K(37)
0.148;-8997.5
(378Q)
0.190;-10527.5
8(37T)
0.211;-10995.0
8Q(37)
0.202;-10527.5
J(379)
0.161;-10527.5
9T(37)
0.180;-10761.2
(37)(9K)
0.186;-8530.0
K(37T)
0.153;-9826.2
T(37K)
0.161;-9826.2
JJ(37)
0.191;-8530.0
(37QK)
0.223;-9358.8
3777
0.222;-10400.0
37(7T)
0.188;-9698.8
77(3K)
0.171;-8997.5
7(38T)
0.141;-10995.0
7Q(38)
0.188;-10527.5
(78)(3T)
0.196;-9465.0
3Q(78)
0.194;-10527.5
3789
0.175;-12758.8
378J
0.153;-12291.2
378K
0.140;-11823.8
7J(39)
0.164;-10527.5
(79)(3T)
0.154;-9231.2
3Q(79)
0.169;-10293.8
379T
0.180;-12291.2
379Q
0.170;-11823.8
(3T)(7J)
0.169;-8763.8
3T(7T)
0.215;-8997.5
3(7TK)
0.194;-9826.2
3T(7Q)
0.193;-10060.0
7J(3J)
0.192;-8530.0
(7J)(3Q)
0.151;-8296.2
3J(7Q)
0.163;-9826.2
7Q(3Q)
0.185;-8062.5
37QQ
0.184;-9592.5
37KK
0.234;-9125.0
8(38J)
0.187;-8997.5
8K(38)
0.229;-8530.0
(389K)
0.224;-9826.2
9J(38)
0.222;-10293.8
(38TJ)
0.187;-10060.0
(38)(TJ)
0.234;-8530.0
J(38J)
0.219;-8296.2
JQ(38)
0.212;-9592.5
Q(38K)
0.196;-9125.0
3889
0.141;-10995.0
38(8Q)
0.197;-8763.8
(39)(8T)
0.235;-8997.5
8(39K)
0.168;-9826.2
3(89J)
0.150;-10293.8
3899
0.219;-10761.2
389J
0.154;-11823.8
389K
0.186;-11356.2
8Q(3T)
0.176;-9826.2
(8T)(3Q)
0.165;-8296.2
3T(8J)
0.137;-10060.0
3T(8K)
0.187;-9592.5
8(3JK)
0.214;-9358.8
3(8JK)
0.226;-9358.8
3J(8K)
0.188;-9358.8
3Q(8Q)
0.212;-7828.7
38QK
0.200;-10655.0
9T(39)
0.218;-8763.8
(39)(9K)
0.215;-6532.5
K(39T)
0.193;-9358.8
T(39K)
0.177;-9358.8
JJ(39)
0.249;-8062.5
(39QK)
0.219;-8891.2
3999
0.238;-8997.5
39(9Q)
0.183;-8296.2
(3T)(9J)
0.152;-8296.2
3T(9T)
0.187;-8530.0
3(9TK)
0.205;-9358.8
3T(9Q)
0.244;-9592.5
9J(3J)
0.203;-8062.5
(9J)(3Q)
0.205;-7828.8
3J(9Q)
0.215;-9358.8
9Q(3Q)
0.168;-7595.0
39QQ
0.202;-9125.0
39KK
0.200;-8657.5
T(3TK)
0.272;-7595.0
JJ(3T)
0.247;-7828.7
(3TQK)
0.207;-8657.5
3TTT
0.225;-8296.2
3T(TK)
0.212;-7595.0
(3J)(TK)
0.199;-7361.2
3K(TJ)
0.177;-8891.2
3T(JK)
0.209;-8891.2
(TQ)(3K)
0.237;-7127.5
(3K)(TK)
0.265;-5363.7
J(3JK)
0.249;-7127.5
(3J)(QK)
0.208;-6893.7
JJ(3K)
0.187;-7127.5
3Q(JQ)
0.266;-7127.5
3JQK
0.195;-9953.7
QK(3Q)
0.267;-6660.0
QK(3K)
0.283;-6426.2
44(46)
0.163;-10272.5
44(4T)
0.190;-9337.5
(45)(45)
0.200;-8742.5
4(458)
0.148;-11101.2
4T(45)
0.172;-10633.8
(45)(4K)
0.251;-8402.5
4457
0.155;-12865.0
44(5T)
0.128;-10633.8
45(4K)
0.216;-9932.5
4(468)
0.200;-10867.5
4T(46)
0.166;-10400.0
(46)(4K)
0.198;-8168.7
4468
0.123;-12397.5
44(6J)
0.154;-10166.2
(47)(47)
0.274;-7807.5
4(47T)
0.210;-10166.2
4Q(47)
0.173;-9698.8
47(49)
0.147;-10400.0
447J
0.156;-11462.5
48(48)
0.177;-8870.0
(48)(4J)
0.180;-8168.7
4488
0.153;-10400.0
44(8J)
0.200;-9698.8
(49)(49)
0.246;-6872.5
4(49Q)
0.194;-9231.2
44(9T)
0.198;-9698.8
49(4K)
0.187;-8997.5
4(4TQ)
0.201;-8997.5
44(TJ)
0.154;-9231.2
(4J)(4J)
0.250;-5937.5
44JJ
0.167;-8997.5
4Q(4Q)
0.222;-7000.0
(4K)(4K)
0.312;-5002.5
(45)(57)
0.152;-9571.3
5(45T)
0.209;-10400.0
5Q(45)
0.226;-9932.5
8(456)
0.131;-12163.8
Q(456)
0.172;-11228.7
(45)(68)
0.186;-10633.8
6(45J)
0.137;-11462.5
6K(45)
0.170;-10995.0
(457J)
0.127;-11228.7
(45)(78)
0.141;-10400.0
7(45J)
0.194;-11228.7
7K(45)
0.162;-10761.2
(458Q)
0.172;-10761.2
8(45T)
0.172;-11228.7
8Q(45)
0.158;-10761.2
J(459)
0.132;-10761.2
9T(45)
0.148;-10995.0
(45)(9K)
0.178;-8763.8
K(45T)
0.222;-10060.0
T(45K)
0.166;-10060.0
JJ(45)
0.219;-8763.8
(45QK)
0.199;-9592.5
4555
0.134;-11568.8
45(58)
0.174;-10867.5
55(4J)
0.230;-10166.2
455K
0.163;-11228.7
58(46)
0.151;-12163.8
(46)(5J)
0.203;-9932.5
46(56)
0.161;-11101.2
4(569)
0.168;-11930.0
(56)(4Q)
0.200;-9698.8
46(57)
0.159;-12397.5
46(59)
0.164;-11930.0
46(5J)
0.131;-11462.5
46(5K)
0.187;-10995.0
5(479)
0.157;-11696.2
5J(47)
0.223;-11228.7
(57)(48)
0.160;-10400.0
4T(57)
0.123;-11462.5
4(57K)
0.161;-10761.2
47(59)
0.151;-11696.2
47(5J)
0.138;-11228.7
47(5K)
0.228;-10761.2
5(48T)
0.179;-11228.7
5Q(48)
0.148;-10761.2
(58)(4T)
0.219;-9698.8
4Q(58)
0.193;-10761.2
4589
0.187;-12992.5
458J
0.137;-12525.0
458K
0.172;-12057.5
5J(49)
0.163;-10761.2
(59)(4T)
0.151;-9465.0
4Q(59)
0.194;-10527.5
459T
0.140;-12525.0
459Q
0.173;-12057.5
(4T)(5J)
0.199;-8997.5
4T(5T)
0.212;-9231.2
4(5TK)
0.203;-10060.0
4T(5Q)
0.187;-10293.8
5J(4J)
0.209;-8763.8
(5J)(4Q)
0.234;-8530.0
4J(5Q)
0.157;-10060.0
5Q(4Q)
0.262;-8296.2
45QQ
0.189;-9826.2
45KK
0.204;-9358.8
6(469)
0.183;-10166.2
6J(46)
0.221;-9698.8
(4678)
0.127;-11696.2
(467Q)
0.183;-10761.2
7(469)
0.194;-11462.5
7J(46)
0.155;-10995.0
(4689)
0.174;-11228.7
(468K)
0.185;-10293.8
8T(46)
0.168;-10995.0
(46)(8K)
0.172;-8763.8
Q(469)
0.178;-10293.8
(46)(9J)
0.238;-8997.5
T(46T)
0.175;-8997.5
T(46J)
0.204;-10293.8
TK(46)
0.193;-9826.2
(46)(JQ)
0.183;-8296.2
QQ(46)
0.243;-8062.5
46(67)
0.141;-10633.8
66(4T)
0.176;-9932.5
466Q
0.155;-10995.0
68(47)
0.148;-11696.2
(47)(6J)
0.183;-9465.0
47(67)
0.205;-10400.0
4(67T)
0.182;-11228.7
(67)(4K)
0.183;-8997.5
67(49)
0.191;-11462.5
67(4J)
0.149;-10995.0
67(4K)
0.192;-10527.5
69(48)
0.162;-11228.7
(48)(6Q)
0.163;-8997.5
49(68)
0.149;-11228.7
4(68Q)
0.203;-10527.5
46(89)
0.210;-11228.7
46(8J)
0.151;-10761.2
46(8K)
0.203;-10293.8
(49)(6J)
0.209;-8997.5
49(69)
0.212;-9465.0
4(69Q)
0.183;-10293.8
46(9T)
0.151;-10761.2
46(9Q)
0.152;-10293.8
6(4TJ)
0.169;-10293.8
6K(4T)
0.186;-9826.2
(6T)(4K)
0.183;-8296.2
6T(4Q)
0.171;-10060.0
(4J)(6J)
0.205;-7000.0
4J(6J)
0.157;-8530.0
6J(4Q)
0.200;-9826.2
(4Q)(6Q)
0.236;-6532.5
4K(6Q)
0.193;-9358.8
4K(6K)
0.213;-7595.0
79(47)
0.164;-9698.8
(47)(7Q)
0.171;-7467.5
(478T)
0.153;-10761.2
88(47)
0.191;-9698.8
(47)(8J)
0.197;-8997.5
9(479)
0.185;-9231.2
K(479)
0.231;-9826.2
9(47Q)
0.194;-10060.0
J(47T)
0.178;-10060.0
TJ(47)
0.147;-10060.0
(47JQ)
0.179;-9592.5
J(47K)
0.196;-9358.8
(47)(QK)
0.193;-7595.0
77(49)
0.211;-9698.8
477J
0.168;-10761.2
78(48)
0.182;-9698.8
(48)(7J)
0.194;-8997.5
48(78)
0.146;-9698.8
4(78J)
0.191;-10527.5
4788
0.181;-11228.7
478T
0.161;-12291.2
478Q
0.184;-11823.8
(49)(7T)
0.187;-8997.5
7(49K)
0.203;-9826.2
4(79J)
0.171;-10293.8
4799
0.220;-10761.2
479J
0.165;-11823.8
479K
0.149;-11356.2
7Q(4T)
0.193;-9826.2
(7T)(4Q)
0.198;-8296.2
4T(7J)
0.220;-10060.0
4T(7K)
0.217;-9592.5
7(4JK)
0.184;-9358.8
4(7JK)
0.208;-9358.8
4J(7K)
0.211;-9358.8
4Q(7Q)
0.242;-7828.7
47QK
0.163;-10655.0
89(48)
0.168;-9231.2
(48)(8Q)
0.247;-7000.0
(489J)
0.152;-10060.0
(48)(9T)
0.194;-8763.8
9(48K)
0.219;-9592.5
(48TK)
0.210;-9358.8
TQ(48)
0.185;-9592.5
K(48J)
0.211;-9125.0
Q(48Q)
0.190;-7595.0
KK(48)
0.265;-7127.5
88(4J)
0.200;-8763.8
488K
0.191;-9826.2
8J(49)
0.200;-10060.0
(89)(4T)
0.232;-8763.8
4Q(89)
0.201;-9826.2
489T
0.156;-11823.8
489Q
0.183;-11356.2
(4T)(8J)
0.192;-8296.2
4T(8T)
0.205;-8530.0
4(8TK)
0.181;-9358.8
4T(8Q)
0.222;-9592.5
8J(4J)
0.187;-8062.5
(8J)(4Q)
0.226;-7828.8
4J(8Q)
0.149;-9358.8
8Q(4Q)
0.211;-7595.0
48QQ
0.209;-9125.0
48KK
0.202;-8657.5
9(49Q)
0.187;-8062.5
J(49T)
0.169;-9592.5
TJ(49)
0.183;-9592.5
(49JQ)
0.193;-9125.0
J(49K)
0.228;-8891.2
(49)(QK)
0.205;-7127.5
99(4J)
0.223;-8296.2
499K
0.192;-9358.8
9Q(4T)
0.199;-9358.8
(9T)(4Q)
0.191;-7828.8
4T(9J)
0.203;-9592.5
4T(9K)
0.170;-9125.0
9(4JK)
0.217;-8891.2
4(9JK)
0.221;-8891.2
4J(9K)
0.166;-8891.2
4Q(9Q)
0.267;-7361.2
49QK
0.190;-10187.5
TJ(4T)
0.268;-7828.7
(4TJQ)
0.229;-8891.2
J(4TK)
0.205;-8657.5
(4T)(QK)
0.204;-6893.7
TT(4Q)
0.241;-7595.0
T(4JQ)
0.164;-8891.2
4(TJQ)
0.214;-8891.2
4T(JQ)
0.188;-8891.2
T(4QK)
0.246;-8423.7
TQ(4K)
0.199;-8423.7
JJ(4J)
0.279;-5831.3
(4JQK)
0.197;-8190.0
4JJJ
0.233;-7361.2
JQ(4Q)
0.208;-6893.7
4JQQ
0.235;-8423.7
4JKK
0.266;-7956.2
QQ(4K)
0.240;-6426.2
4KKK
0.232;-5958.8
55(59)
0.177;-8870.0
55(5K)
0.213;-7935.0
(56)(58)
0.197;-8870.0
5(56J)
0.159;-9698.8
5K(56)
0.234;-9231.2
56(59)
0.218;-10166.2
556J
0.155;-11228.7
57(57)
0.225;-8870.0
(57)(5T)
0.232;-8168.7
5(57K)
0.227;-8997.5
55(79)
0.181;-9932.5
57(5Q)
0.184;-9231.2
5(589)
0.239;-9698.8
5J(58)
0.236;-9231.2
58(59)
0.200;-9698.8
558J
0.189;-10761.2
59(59)
0.192;-7935.0
(59)(5Q)
0.216;-7233.8
559T
0.194;-10761.2
55(9K)
0.186;-8530.0
(5T)(5Q)
0.215;-7000.0
55TJ
0.143;-10293.8
5J(5J)
0.268;-7000.0
5J(5Q)
0.234;-8296.2
5(5QK)
0.227;-7828.7
5K(5K)
0.249;-6065.0
68(56)
0.159;-10166.2
(56)(6J)
0.227;-7935.0
7(567)
0.209;-10166.2
J(567)
0.208;-10761.2
78(56)
0.185;-11462.5
(56)(7J)
0.197;-9231.2
8(568)
0.227;-9698.8
Q(568)
0.164;-10293.8
(56)(8T)
0.228;-9231.2
8(56K)
0.155;-10060.0
(569Q)
0.221;-10060.0
9(56J)
0.218;-10293.8
9K(56)
0.198;-9826.2
TT(56)
0.186;-8763.8
(56)(TK)
0.254;-8062.5
J(56Q)
0.218;-9592.5
K(56Q)
0.203;-9125.0
66(57)
0.191;-10400.0
5669
0.155;-11462.5
56(6Q)
0.228;-9231.2
(57)(68)
0.185;-9932.5
6(57J)
0.172;-10761.2
6K(57)
0.190;-10293.8
(67)(5T)
0.218;-9465.0
5Q(67)
0.155;-10527.5
5678
0.142;-12992.5
567T
0.123;-12525.0
567Q
0.140;-12057.5
(58)(69)
0.162;-9465.0
6(58Q)
0.194;-10293.8
5(689)
0.178;-10995.0
(68)(5Q)
0.257;-8763.8
58(69)
0.185;-10995.0
58(6J)
0.194;-10527.5
58(6K)
0.218;-10060.0
6(59J)
0.207;-10293.8
6K(59)
0.166;-9826.2
(69)(5Q)
0.226;-8530.0
59(6T)
0.163;-10527.5
59(6Q)
0.179;-10060.0
6T(5T)
0.176;-8763.8
(5T)(6K)
0.186;-8062.5
5Q(6T)
0.188;-9826.2
56TJ
0.155;-11590.0
56TK
0.199;-11122.5
6K(5J)
0.237;-9358.8
56JJ
0.188;-9826.2
56JK
0.189;-10888.8
5(6QK)
0.215;-9125.0
6K(5K)
0.222;-7361.2
(57)(79)
0.199;-7935.0
7(57Q)
0.174;-8763.8
9(578)
0.175;-10761.2
K(578)
0.199;-9826.2
8(57J)
0.163;-10293.8
8K(57)
0.193;-9826.2
(579K)
0.237;-9592.5
9J(57)
0.215;-10060.0
(57TJ)
0.185;-9826.2
(57)(TJ)
0.177;-8296.2
J(57J)
0.220;-8062.5
JQ(57)
0.197;-9358.8
Q(57K)
0.157;-8891.2
5778
0.133;-11228.7
57(7J)
0.195;-8997.5
(58)(78)
0.219;-7935.0
7(58J)
0.232;-10293.8
7K(58)
0.188;-9826.2
(78)(5J)
0.205;-8763.8
5K(78)
0.210;-9826.2
57(8T)
0.175;-10527.5
57(8Q)
0.174;-10060.0
7(59T)
0.134;-10293.8
7Q(59)
0.168;-9826.2
(79)(5J)
0.176;-8530.0
5K(79)
0.194;-9592.5
57(9J)
0.144;-10060.0
57(9K)
0.219;-9592.5
(5T)(7Q)
0.176;-8062.5
5J(7T)
0.153;-9826.2
7T(5J)
0.183;-9826.2
7T(5K)
0.195;-9358.8
7Q(5J)
0.183;-9358.8
(7J)(5K)
0.196;-7595.0
7J(5K)
0.235;-9125.0
7K(5Q)
0.194;-8891.2
57(QK)
0.242;-8891.2
(58)(89)
0.176;-7467.5
8(58Q)
0.193;-8296.2
T(589)
0.175;-10060.0
9(58T)
0.189;-10060.0
9Q(58)
0.171;-9592.5
Q(58T)
0.184;-9358.8
(58)(TQ)
0.189;-7828.8
(58JK)
0.249;-8891.2
JK(58)
0.254;-8891.2
K(58K)
0.189;-6893.7
588T
0.189;-10293.8
58(8K)
0.264;-8062.5
(59)(8J)
0.169;-8296.2
59(89)
0.201;-8763.8
5(89Q)
0.220;-9592.5
58(9T)
0.182;-10060.0
58(9Q)
0.175;-9592.5
8(5TJ)
0.168;-9592.5
8K(5T)
0.174;-9125.0
(8T)(5K)
0.219;-7595.0
8T(5Q)
0.193;-9358.8
(5J)(8J)
0.262;-6298.7
5J(8J)
0.259;-7828.7
8J(5Q)
0.189;-9125.0
(5Q)(8Q)
0.280;-5831.3
5K(8Q)
0.191;-8657.5
5K(8K)
0.206;-6893.7
9J(59)
0.195;-8062.5
(59TJ)
0.223;-9358.8
(59)(TJ)
0.279;-7828.8
J(59J)
0.251;-7595.0
JQ(59)
0.227;-8891.2
Q(59K)
0.198;-8423.7
599T
0.193;-9826.2
59(9K)
0.210;-7595.0
(5T)(9Q)
0.167;-7595.0
5J(9T)
0.211;-9358.8
9T(5J)
0.219;-9358.8
9T(5K)
0.210;-8891.2
9Q(5J)
0.192;-8891.2
(9J)(5K)
0.225;-7127.5
9J(5K)
0.217;-8657.5
9K(5Q)
0.217;-8423.7
59(QK)
0.246;-8423.7
(5T)(TJ)
0.195;-6065.0
J(5TJ)
0.178;-7361.2
JQ(5T)
0.209;-8657.5
Q(5TK)
0.234;-8190.0
5TTJ
0.227;-9125.0
TJ(5J)
0.210;-7361.2
(TJ)(5Q)
0.232;-7127.5
5J(TQ)
0.230;-8657.5
TQ(5Q)
0.220;-6893.7
5TQQ
0.223;-8423.7
5TKK
0.233;-7956.2
Q(5JQ)
0.187;-6660.0
KK(5J)
0.229;-6192.5
(5Q)(JQ)
0.279;-5130.0
5K(JQ)
0.229;-7956.2
5K(JK)
0.298;-6192.5
5QQQ
0.280;-6426.2
KK(5K)
0.353;-4195.0
6669
0.186;-9698.8
666K
0.163;-8763.8
69(67)
0.196;-9465.0
(67)(6Q)
0.201;-7233.8
6678
0.193;-11228.7
66(7J)
0.193;-8997.5
(68)(68)
0.257;-6405.0
6(68J)
0.186;-8763.8
6K(68)
0.208;-8296.2
68(6J)
0.218;-8763.8
668K
0.228;-9826.2
6J(69)
0.206;-8530.0
69(6T)
0.204;-8763.8
669Q
0.211;-9826.2
6J(6T)
0.184;-8296.2
6T(6J)
0.215;-8296.2
66TK
0.185;-9358.8
6K(6J)
0.212;-7595.0
(6Q)(6Q)
0.258;-4535.0
66QK
0.184;-8891.2
7(679)
0.172;-9231.2
7J(67)
0.196;-8763.8
(6789)
0.202;-10527.5
(678K)
0.167;-9592.5
8T(67)
0.181;-10293.8
(67)(8K)
0.251;-8062.5
Q(679)
0.231;-9592.5
(67)(9J)
0.254;-8296.2
T(67T)
0.229;-8296.2
T(67J)
0.183;-9592.5
TK(67)
0.226;-9125.0
(67)(JQ)
0.266;-7595.0
QQ(67)
0.227;-7361.2
67(78)
0.196;-9465.0
77(6J)
0.202;-8763.8
677K
0.243;-9826.2
7T(68)
0.182;-10293.8
(68)(7K)
0.232;-8062.5
6T(78)
0.158;-10293.8
6(78K)
0.169;-9592.5
68(7T)
0.169;-10293.8
68(7Q)
0.214;-9826.2
79(69)
0.153;-8763.8
(69)(7Q)
0.192;-8062.5
6T(79)
0.198;-10060.0
6(79K)
0.175;-9358.8
69(7J)
0.145;-9826.2
69(7K)
0.155;-9358.8
7(6TQ)
0.239;-9358.8
6(7TJ)
0.188;-9592.5
67TT
0.206;-9826.2
67TQ
0.140;-10888.8
(6J)(7Q)
0.265;-7595.0
6Q(7J)
0.158;-9125.0
67JQ
0.159;-10655.0
(6Q)(7K)
0.206;-7127.5
6Q(7K)
0.202;-8657.5
8(689)
0.194;-8763.8
8J(68)
0.226;-8296.2
(689T)
0.152;-9826.2
99(68)
0.259;-8530.0
(68)(9Q)
0.217;-7828.8
(68TQ)
0.180;-9125.0
T(68Q)
0.183;-9125.0
Q(68J)
0.164;-8891.2
(68)(JK)
0.271;-7127.5
QK(68)
0.210;-8423.7
68(8T)
0.204;-8530.0
88(6K)
0.218;-7828.7
8(69J)
0.156;-9592.5
8K(69)
0.183;-9125.0
(89)(6Q)
0.251;-7828.8
69(8T)
0.205;-9826.2
69(8Q)
0.187;-9358.8
8T(6T)
0.205;-8062.5
(6T)(8K)
0.213;-7361.2
6Q(8T)
0.179;-9125.0
68TJ
0.142;-10888.8
68TK
0.146;-10421.2
8K(6J)
0.187;-8657.5
68JJ
0.171;-9125.0
68JK
0.178;-10187.5
6(8QK)
0.184;-8423.7
8K(6K)
0.203;-6660.0
(69)(9J)
0.292;-6298.7
T(69T)
0.169;-7828.7
T(69J)
0.237;-9125.0
TK(69)
0.227;-8657.5
(69)(JQ)
0.195;-7127.5
QQ(69)
0.237;-6893.7
69(9T)
0.215;-8062.5
99(6K)
0.259;-7361.2
9(6TQ)
0.170;-8891.2
6(9TJ)
0.186;-9125.0
69TT
0.157;-9358.8
69TQ
0.180;-10421.2
(6J)(9Q)
0.223;-7127.5
6Q(9J)
0.211;-8657.5
69JQ
0.187;-10187.5
(6Q)(9K)
0.240;-6660.0
6Q(9K)
0.199;-8190.0
T(6TJ)
0.175;-7361.2
TK(6T)
0.297;-6893.7
(6T)(JQ)
0.229;-6893.7
QQ(6T)
0.247;-6660.0
6T(TJ)
0.180;-7361.2
(6J)(TJ)
0.316;-5597.5
6J(TJ)
0.201;-7127.5
TJ(6Q)
0.165;-8423.7
(6Q)(TQ)
0.231;-5130.0
6K(TQ)
0.253;-7956.2
6K(TK)
0.250;-6192.5
JK(6J)
0.222;-6426.2
K(6JK)
0.255;-5958.8
6JJK
0.248;-7956.2
6(JQK)
0.200;-7722.5
JK(6K)
0.245;-5958.8
KK(6Q)
0.225;-5725.0
6QKK
0.217;-7255.0
77(7T)
0.233;-7233.7
(78)(78)
0.221;-5937.5
7(78J)
0.239;-8296.2
7K(78)
0.213;-7828.7
78(7J)
0.255;-8296.2
778K
0.148;-9358.8
7J(79)
0.244;-8062.5
79(7T)
0.246;-8296.2
779Q
0.170;-9358.8
7J(7T)
0.253;-7828.7
7T(7J)
0.244;-7828.7
77TK
0.246;-8891.2
7K(7J)
0.284;-7127.5
(7Q)(7Q)
0.298;-4067.5
77QK
0.195;-8423.7
8(78T)
0.226;-8296.2
8Q(78)
0.214;-7828.7
J(789)
0.186;-9358.8
9T(78)
0.212;-9592.5
(78)(9K)
0.235;-7361.2
K(78T)
0.213;-8657.5
T(78K)
0.195;-8657.5
JJ(78)
0.209;-7361.2
(78QK)
0.228;-8190.0
7888
0.236;-8763.8
78(8J)
0.272;-8062.5
(79)(89)
0.284;-6766.2
8(79Q)
0.171;-9125.0
7(89T)
0.197;-9592.5
(89)(7K)
0.295;-7361.2
89(7J)
0.162;-9358.8
89(7K)
0.184;-8891.2
8J(7T)
0.230;-9125.0
(8T)(7J)
0.188;-7595.0
7K(8T)
0.206;-8657.5
78(TQ)
0.174;-8891.2
8(7JQ)
0.253;-8657.5
7(8JQ)
0.180;-8657.5
78(JQ)
0.222;-8657.5
8(7QK)
0.187;-8190.0
8Q(7K)
0.230;-8190.0
99(79)
0.294;-6532.5
(79)(9Q)
0.285;-5831.3
(79TQ)
0.152;-8657.5
T(79Q)
0.218;-8657.5
Q(79J)
0.189;-8423.7
(79)(JK)
0.238;-6660.0
QK(79)
0.208;-7956.2
79(9J)
0.225;-7595.0
(7T)(9T)
0.246;-6065.0
9(7TK)
0.206;-8423.7
7(9TQ)
0.169;-8657.5
79(TJ)
0.169;-8891.2
79(TK)
0.176;-8423.7
(7J)(9K)
0.244;-6660.0
7K(9J)
0.190;-8190.0
79(JK)
0.159;-8190.0
(9Q)(7K)
0.243;-6426.2
(7K)(9K)
0.257;-4662.5
T(7TQ)
0.257;-6893.7
Q(7TJ)
0.208;-8190.0
(7T)(JK)
0.248;-6426.2
QK(7T)
0.227;-7722.5
7T(TQ)
0.218;-6893.7
(7J)(TQ)
0.257;-6660.0
7Q(TJ)
0.178;-8190.0
7TJQ
0.191;-9720.0
(7Q)(TK)
0.263;-6192.5
7Q(TK)
0.229;-7722.5
J(7JQ)
0.187;-6426.2
K(7JQ)
0.220;-7488.8
JJ(7Q)
0.290;-6426.2
J(7QK)
0.246;-7488.8
JQ(7K)
0.189;-7488.8
QQ(7Q)
0.220;-4428.8
7Q(QK)
0.250;-5725.0
8888
0.227;-7000.0
888Q
0.183;-7595.0
8(89J)
0.196;-7595.0
8K(89)
0.250;-7127.5
89(8Q)
0.181;-7361.2
8(8TJ)
0.252;-7361.2
8K(8T)
0.273;-6893.7
8T(8K)
0.232;-6893.7
8(8JK)
0.283;-6660.0
88(JK)
0.271;-6660.0
8Q(8K)
0.262;-6426.2
(89)(9T)
0.247;-6065.0
9(89K)
0.220;-6893.7
(89TK)
0.244;-8190.0
TQ(89)
0.216;-8423.7
K(89J)
0.184;-7956.2
Q(89Q)
0.232;-6426.2
KK(89)
0.209;-5958.8
99(8Q)
0.200;-7127.5
9(8TJ)
0.209;-8657.5
9K(8T)
0.182;-8190.0
(9T)(8K)
0.219;-6660.0
9T(8Q)
0.170;-8423.7
(8J)(9J)
0.327;-5363.7
8J(9J)
0.262;-6893.7
9J(8Q)
0.242;-8190.0
(8Q)(9Q)
0.257;-4896.2
8K(9Q)
0.234;-7722.5
8K(9K)
0.237;-5958.8
TQ(8T)
0.219;-6660.0
K(8TJ)
0.210;-7722.5
Q(8TQ)
0.252;-6192.5
KK(8T)
0.220;-5725.0
