AAAA
0.403;2805.0
5AAA
0.322;988.1
9AAA
0.416;1455.6
KAAA
0.414;1923.1
4A(2A)
0.273;-531.2
(2A)(7A)
0.312;584.4
A(2TA)
0.362;170.0
QA(2A)
0.369;403.8
2A(4A)
0.313;-531.2
26AA
0.313;-1062.5
AA(29)
0.319;53.1
2A(QA)
0.368;403.8
A(34A)
0.326;-414.4
6A(3A)
0.283;-180.6
(3A)(9A)
0.378;935.0
A(3QA)
0.351;520.6
AA(34)
0.268;-414.4
3A(7A)
0.366;-63.7
39AA
0.302;-595.0
AA(3Q)
0.328;520.6
(4A)(5A)
0.387;584.4
A(48A)
0.312;170.0
TA(4A)
0.327;403.8
(4A)(KA)
0.376;1519.4
46AA
0.343;-828.7
AA(49)
0.370;286.9
4A(QA)
0.319;637.5
A(56A)
0.414;53.1
8A(5A)
0.306;286.9
(5A)(JA)
0.348;1402.5
55AA
0.357;-63.7
AA(58)
0.325;286.9
5A(JA)
0.395;637.5
5KAA
0.366;106.2
8A(6A)
0.380;403.8
(6A)(JA)
0.375;1519.4
66AA
0.279;170.0
AA(69)
0.313;520.6
6A(QA)
0.367;871.2
A(78A)
0.365;520.6
TA(7A)
0.359;754.4
(7A)(KA)
0.308;1870.0
79AA
0.387;-127.5
AA(7Q)
0.301;988.1
(8A)(9A)
0.428;1519.4
A(8QA)
0.383;1105.0
AA(89)
0.397;754.4
8A(QA)
0.379;1105.0
A(9TA)
0.378;988.1
QA(9A)
0.341;1221.9
9A(JA)
0.413;1105.0
9KAA
0.348;573.8
QA(TA)
0.353;1338.7
TA(QA)
0.317;1338.7
A(JQA)
0.413;1455.6
AA(JQ)
0.328;1455.6
(QA)(KA)
0.457;2454.4
KKAA
0.350;1806.3
2(25A)
0.285;-1816.9
27(2A)
0.303;-1583.1
(2T)(2A)
0.359;-467.5
2(2KA)
0.349;-881.9
(236A)
0.269;-2348.1
(23TA)
0.302;-1880.6
33(2A)
0.295;-1933.7
(36)(2A)
0.302;-1583.1
3(29A)
0.355;-1997.5
3J(2A)
0.319;-1763.8
(245A)
0.342;-2348.1
(249A)
0.236;-1880.6
(24KA)
0.261;-1413.1
46(2A)
0.344;-2231.2
(49)(2A)
0.314;-1115.6
4(2QA)
0.278;-1530.0
6(25A)
0.262;-2114.4
T(25A)
0.302;-1646.9
5(26A)
0.313;-2114.4
58(2A)
0.239;-1880.6
(5J)(2A)
0.336;-765.0
6(26A)
0.277;-1232.5
T(26A)
0.280;-1530.0
6(27A)
0.250;-1880.6
69(2A)
0.270;-1646.9
(6Q)(2A)
0.364;-531.3
(279A)
0.302;-1530.0
(27KA)
0.357;-1062.5
79(2A)
0.253;-1530.0
(7Q)(2A)
0.281;-414.4
(28TA)
0.312;-1296.2
88(2A)
0.296;-765.0
(8J)(2A)
0.275;-414.4
9(29A)
0.315;-531.2
K(29A)
0.298;-828.7
9(2QA)
0.329;-945.6
J(2TA)
0.306;-945.6
TJ(2A)
0.328;-945.6
(2JQA)
0.324;-711.9
J(2KA)
0.370;-595.0
(QK)(2A)
0.355;286.9
22(4A)
0.363;-1933.7
226A
0.252;-2465.0
2A(29)
0.342;-1349.4
22(QA)
0.349;-998.7
2(34A)
0.299;-2581.9
26(3A)
0.286;-2348.1
(29)(3A)
0.326;-1232.5
2(3QA)
0.262;-1646.9
A(234)
0.298;-2581.9
(23)(7A)
0.276;-1466.2
9A(23)
0.255;-1997.5
A(23Q)
0.349;-1646.9
2A(34)
0.288;-2581.9
2A(36)
0.268;-2348.1
2A(38)
0.222;-2114.4
2A(3T)
0.271;-1880.6
2A(3Q)
0.274;-1646.9
2(45A)
0.277;-2348.1
27(4A)
0.290;-2114.4
(2T)(4A)
0.267;-998.7
2(4KA)
0.279;-1413.1
A(246)
0.290;-2231.2
(24)(9A)
0.293;-1115.6
JA(24)
0.328;-1646.9
24(5A)
0.246;-2348.1
24(7A)
0.279;-2114.4
24(9A)
0.323;-1880.6
24(JA)
0.287;-1646.9
24(KA)
0.290;-1413.1
26(5A)
0.284;-2114.4
(29)(5A)
0.322;-998.7
2(5QA)
0.276;-1413.1
A(256)
0.260;-2114.4
(25)(9A)
0.279;-998.7
JA(25)
0.296;-1530.0
25(6A)
0.247;-2114.4
25(8A)
0.312;-1880.6
25(TA)
0.247;-1646.9
25(QA)
0.312;-1413.1
(26)(6A)
0.304;-467.5
2(69A)
0.305;-1646.9
2J(6A)
0.281;-1413.1
(26)(7A)
0.325;-1115.6
9A(26)
0.330;-1646.9
A(26Q)
0.305;-1296.2
2A(67)
0.327;-1880.6
2A(69)
0.241;-1646.9
2A(6J)
0.281;-1413.1
2A(6K)
0.309;-1179.4
(29)(7A)
0.279;-765.0
2(7QA)
0.281;-1179.4
A(278)
0.355;-1646.9
(27)(JA)
0.292;-531.3
KA(27)
0.316;-1062.5
2A(79)
0.298;-1530.0
2A(7J)
0.337;-1296.2
2A(7K)
0.346;-1062.5
(2T)(8A)
0.341;-531.3
2(8KA)
0.327;-945.6
A(28T)
0.300;-1296.2
(28)(KA)
0.362;-180.6
28(TA)
0.330;-1296.2
28(QA)
0.268;-1062.5
(29)(9A)
0.274;233.8
2(9QA)
0.325;-945.6
A(29T)
0.275;-1179.4
(29)(KA)
0.348;-63.7
29(JA)
0.375;-1062.5
29(KA)
0.271;-828.7
2J(TA)
0.314;-945.6
(2T)(JA)
0.337;-180.6
KA(2T)
0.371;-711.9
2A(TQ)
0.282;-828.7
2(JQA)
0.330;-711.9
A(2JQ)
0.306;-711.9
2A(JQ)
0.349;-711.9
2(QKA)
0.319;-478.1
2Q(KA)
0.290;-478.1
33(3A)
0.275;-1051.9
(36)(3A)
0.281;-701.2
3(39A)
0.312;-1115.6
3J(3A)
0.381;-881.9
(345A)
0.295;-2231.2
(349A)
0.242;-1763.8
(34KA)
0.288;-1296.2
46(3A)
0.237;-2114.4
(49)(3A)
0.292;-998.7
4(3QA)
0.321;-1413.1
6(35A)
0.246;-1997.5
T(35A)
0.246;-1530.0
5(36A)
0.350;-1997.5
58(3A)
0.300;-1763.8
(5J)(3A)
0.330;-648.1
6(36A)
0.266;-1115.6
T(36A)
0.352;-1413.1
6(37A)
0.253;-1763.8
69(3A)
0.271;-1530.0
(6Q)(3A)
0.299;-414.4
(379A)
0.320;-1413.1
(37KA)
0.360;-945.6
79(3A)
0.241;-1413.1
(7Q)(3A)
0.352;-297.5
(38TA)
0.314;-1179.4
88(3A)
0.304;-648.1
(8J)(3A)
0.289;-297.5
9(39A)
0.365;-414.4
K(39A)
0.354;-711.9
9(3QA)
0.266;-828.7
J(3TA)
0.287;-828.7
TJ(3A)
0.283;-828.7
(3JQA)
0.336;-595.0
J(3KA)
0.388;-478.1
(QK)(3A)
0.300;403.8
33(5A)
0.254;-1583.1
337A
0.307;-2114.4
3A(3T)
0.300;-998.7
33(KA)
0.355;-648.1
3(46A)
0.234;-2114.4
38(4A)
0.328;-1880.6
(3J)(4A)
0.379;-765.0
4A(34)
0.283;-1583.1
A(347)
0.291;-1997.5
(34)(TA)
0.292;-881.9
QA(34)
0.279;-1413.1
345A
0.283;-2996.2
347A
0.202;-2762.5
349A
0.262;-2528.8
34JA
0.294;-2295.0
34KA
0.277;-2061.2
37(5A)
0.295;-1880.6
(3T)(5A)
0.327;-765.0
3(5KA)
0.343;-1179.4
A(357)
0.344;-1880.6
(35)(TA)
0.263;-765.0
QA(35)
0.350;-1296.2
356A
0.242;-2762.5
358A
0.264;-2528.8
35TA
0.274;-2295.0
35QA
0.315;-2061.2
(37)(6A)
0.274;-998.7
3(6TA)
0.284;-1413.1
3Q(6A)
0.373;-1179.4
(36)(8A)
0.344;-881.9
TA(36)
0.234;-1413.1
A(36K)
0.290;-1062.5
6A(38)
0.234;-1646.9
6A(3T)
0.296;-1413.1
6A(3Q)
0.272;-1179.4
37(7A)
0.327;-881.9
(3T)(7A)
0.302;-531.3
3(7KA)
0.280;-945.6
A(379)
0.243;-1413.1
(37)(QA)
0.366;-297.5
7A(38)
0.273;-1530.0
7A(3T)
0.287;-1296.2
7A(3Q)
0.310;-1062.5
38(8A)
0.308;-648.1
(3J)(8A)
0.309;-297.5
8A(38)
0.310;-648.1
A(38J)
0.356;-1062.5
388A
0.261;-1413.1
38TA
0.306;-1944.4
38QA
0.309;-1710.6
(3T)(9A)
0.334;-297.5
3(9KA)
0.300;-711.9
A(39J)
0.328;-945.6
399A
0.347;-1179.4
39JA
0.290;-1710.6
39KA
0.312;-1476.9
3Q(TA)
0.366;-711.9
(3T)(QA)
0.347;53.1
TA(3J)
0.305;-828.7
TA(3K)
0.318;-595.0
3(JKA)
0.365;-478.1
A(3JK)
0.302;-478.1
JA(3K)
0.344;-478.1
QA(3Q)
0.286;286.9
3QKA
0.341;-1126.2
45(4A)
0.354;-1349.4
(48)(4A)
0.361;-233.8
4(4JA)
0.377;-648.1
4K(4A)
0.385;-414.4
(459A)
0.309;-1530.0
(45KA)
0.329;-1062.5
57(4A)
0.279;-1763.8
(5T)(4A)
0.272;-648.1
5(4KA)
0.281;-1062.5
(469A)
0.296;-1413.1
(46KA)
0.330;-945.6
68(4A)
0.332;-1530.0
(6J)(4A)
0.374;-414.4
7(47A)
0.358;-765.0
J(47A)
0.290;-1062.5
78(4A)
0.315;-1413.1
(7J)(4A)
0.326;-297.5
8(48A)
0.299;-531.2
Q(48A)
0.289;-828.7
(8T)(4A)
0.288;-297.5
8(4KA)
0.278;-711.9
(49QA)
0.389;-711.9
9(4JA)
0.384;-828.7
9K(4A)
0.332;-595.0
TT(4A)
0.326;-63.7
(TK)(4A)
0.339;286.9
J(4QA)
0.327;-478.1
K(4QA)
0.297;-244.4
44(5A)
0.313;-1349.4
447A
0.249;-1880.6
4A(4T)
0.293;-765.0
44(KA)
0.323;-414.4
4(57A)
0.289;-1763.8
49(5A)
0.274;-1530.0
(4Q)(5A)
0.359;-414.4
6A(45)
0.235;-1880.6
A(459)
0.299;-1530.0
(45)(QA)
0.346;-414.4
5A(46)
0.264;-1880.6
5A(48)
0.320;-1646.9
5A(4T)
0.266;-1413.1
5A(4Q)
0.339;-1179.4
46(6A)
0.282;-998.7
(49)(6A)
0.312;-648.1
4(6QA)
0.330;-1062.5
A(467)
0.264;-1646.9
(46)(TA)
0.343;-531.3
QA(46)
0.323;-1062.5
467A
0.332;-2411.9
469A
0.309;-2178.1
46JA
0.268;-1944.4
46KA
0.310;-1710.6
49(7A)
0.305;-1296.2
(4Q)(7A)
0.345;-180.6
8A(47)
0.265;-1413.1
A(47J)
0.241;-1062.5
477A
0.320;-1530.0
479A
0.230;-2061.2
47JA
0.292;-1827.5
47KA
0.257;-1593.8
4T(8A)
0.281;-1062.5
(4K)(8A)
0.320;53.1
TA(48)
0.322;-1062.5
A(48K)
0.333;-711.9
8A(4T)
0.319;-1062.5
8A(4Q)
0.279;-828.7
49(9A)
0.381;-297.5
(4Q)(9A)
0.298;53.1
TA(49)
0.320;-945.6
A(49K)
0.291;-595.0
9A(4J)
0.331;-828.7
9A(4K)
0.348;-595.0
4(TQA)
0.362;-595.0
A(4TJ)
0.360;-711.9
4TTA
0.293;-828.7
4TQA
0.268;-1360.0
(4Q)(JA)
0.353;286.9
QA(4J)
0.316;-478.1
4JQA
0.336;-1243.1
(4K)(QA)
0.403;520.6
QA(4K)
0.305;-244.4
5(56A)
0.308;-998.7
58(5A)
0.347;-765.0
(5J)(5A)
0.339;350.6
6(56A)
0.347;-881.9
T(56A)
0.321;-1179.4
6(57A)
0.289;-1530.0
69(5A)
0.281;-1296.2
(6Q)(5A)
0.327;-180.6
(579A)
0.316;-1179.4
(57KA)
0.366;-711.9
79(5A)
0.303;-1179.4
(7Q)(5A)
0.294;-63.7
(58TA)
0.391;-945.6
88(5A)
0.334;-414.4
(8J)(5A)
0.381;-63.7
9(59A)
0.336;-180.6
K(59A)
0.343;-478.1
9(5QA)
0.297;-595.0
J(5TA)
0.276;-595.0
TJ(5A)
0.360;-595.0
(5JQA)
0.368;-361.2
J(5KA)
0.292;-244.4
(QK)(5A)
0.302;637.5
55(7A)
0.352;-881.9
559A
0.227;-1413.1
5A(5Q)
0.326;-297.5
(57)(6A)
0.272;-765.0
5(6TA)
0.386;-1179.4
5Q(6A)
0.337;-945.6
(56)(8A)
0.343;-648.1
TA(56)
0.346;-1179.4
A(56K)
0.297;-828.7
6A(58)
0.332;-1413.1
6A(5T)
0.309;-1179.4
6A(5Q)
0.370;-945.6
57(7A)
0.270;-648.1
(5T)(7A)
0.340;-297.5
5(7KA)
0.367;-711.9
A(579)
0.323;-1179.4
(57)(QA)
0.295;-63.7
7A(58)
0.294;-1296.2
7A(5T)
0.289;-1062.5
7A(5Q)
0.316;-828.7
58(8A)
0.266;-414.4
(5J)(8A)
0.371;-63.7
8A(58)
0.333;-414.4
A(58J)
0.318;-828.7
588A
0.327;-1179.4
58TA
0.309;-1710.6
58QA
0.282;-1476.9
(5T)(9A)
0.278;-63.7
5(9KA)
0.277;-478.1
A(59J)
0.314;-711.9
599A
0.280;-945.6
59JA
0.241;-1476.9
59KA
0.305;-1243.1
5Q(TA)
0.350;-478.1
(5T)(QA)
0.296;286.9
TA(5J)
0.322;-595.0
TA(5K)
0.295;-361.2
5(JKA)
0.305;-244.4
A(5JK)
0.302;-244.4
JA(5K)
0.325;-244.4
QA(5Q)
0.367;520.6
5QKA
0.374;-892.5
67(6A)
0.292;-648.1
(6T)(6A)
0.322;467.5
6(6KA)
0.396;53.1
(67TA)
0.275;-945.6
77(6A)
0.346;-531.2
(7T)(6A)
0.346;-180.6
7(6KA)
0.358;-595.0
(68JA)
0.397;-711.9
(89)(6A)
0.324;-180.6
8(6QA)
0.402;-595.0
T(69A)
0.367;-711.9
9(6TA)
0.311;-711.9
9Q(6A)
0.348;-478.1
Q(6TA)
0.258;-361.2
(TQ)(6A)
0.303;403.8
(6JKA)
0.311;-127.5
JK(6A)
0.268;-127.5
K(6KA)
0.319;871.2
668A
0.315;-1296.2
6A(6J)
0.286;-180.6
(67)(7A)
0.352;233.8
6(7TA)
0.286;-945.6
6Q(7A)
0.302;-711.9
(67)(9A)
0.326;-297.5
JA(67)
0.322;-828.7
67(8A)
0.315;-1179.4
67(TA)
0.337;-945.6
67(QA)
0.334;-711.9
(68)(8A)
0.402;467.5
6(8JA)
0.266;-711.9
6K(8A)
0.277;-478.1
(68)(JA)
0.337;53.1
KA(68)
0.336;-478.1
6A(8T)
0.332;-828.7
6A(8Q)
0.325;-595.0
6(9TA)
0.322;-711.9
6Q(9A)
0.348;-478.1
(69)(JA)
0.382;170.0
KA(69)
0.360;-361.2
6A(9J)
0.346;-595.0
6A(9K)
0.306;-361.2
(6Q)(TA)
0.368;403.8
JA(6T)
0.320;-478.1
6T(JA)
0.297;-478.1
6T(KA)
0.346;-244.4
6Q(JA)
0.321;-244.4
(6J)(KA)
0.328;637.5
6J(KA)
0.357;-127.5
6K(QA)
0.378;-10.6
6A(QK)
0.341;-10.6
(78)(7A)
0.298;467.5
7(7JA)
0.356;53.1
7K(7A)
0.376;286.9
(78QA)
0.339;-478.1
8(7TA)
0.248;-711.9
8Q(7A)
0.297;-478.1
J(79A)
0.381;-478.1
9T(7A)
0.290;-595.0
(9K)(7A)
0.334;520.6
K(7TA)
0.326;-127.5
T(7KA)
0.342;-127.5
JJ(7A)
0.404;520.6
(7QKA)
0.406;106.2
777A
0.337;-414.4
7A(7T)
0.352;-63.7
77(KA)
0.404;286.9
7(8TA)
0.352;-711.9
7Q(8A)
0.356;-478.1
(78)(TA)
0.354;53.1
QA(78)
0.321;-478.1
789A
0.244;-1593.8
78JA
0.307;-1360.0
78KA
0.296;-1126.2
7J(9A)
0.349;-478.1
(79)(TA)
0.329;170.0
QA(79)
0.296;-361.2
79TA
0.319;-1360.0
79QA
0.329;-1126.2
(7J)(TA)
0.370;403.8
TA(7T)
0.330;286.9
A(7TK)
0.280;-127.5
TA(7Q)
0.348;-244.4
7J(JA)
0.365;520.6
(7J)(QA)
0.363;637.5
JA(7Q)
0.359;-127.5
7Q(QA)
0.318;754.4
7QQA
0.344;-10.6
7KKA
0.370;223.1
8(8JA)
0.385;286.9
8K(8A)
0.344;520.6
(89KA)
0.335;-127.5
9J(8A)
0.304;-361.2
(8TJA)
0.302;-244.4
(TJ)(8A)
0.286;520.6
J(8JA)
0.392;637.5
JQ(8A)
0.352;-10.6
Q(8KA)
0.338;223.1
889A
0.266;-711.9
8A(8Q)
0.345;403.8
(8T)(9A)
0.268;286.9
8(9KA)
0.378;-127.5
A(89J)
0.353;-361.2
899A
0.351;-595.0
89JA
0.311;-1126.2
89KA
0.309;-892.5
8Q(TA)
0.350;-127.5
(8T)(QA)
0.285;637.5
TA(8J)
0.298;-244.4
TA(8K)
0.307;-10.6
8(JKA)
0.332;106.2
A(8JK)
0.294;106.2
JA(8K)
0.364;106.2
QA(8Q)
0.393;871.2
8QKA
0.322;-541.9
9T(9A)
0.369;403.8
(9K)(9A)
0.417;1519.4
K(9TA)
0.341;106.2
T(9KA)
0.359;106.2
JJ(9A)
0.368;754.4
(9QKA)
0.359;340.0
999A
0.362;286.9
9A(9Q)
0.406;637.5
(9J)(TA)
0.325;637.5
TA(9T)
0.316;520.6
A(9TK)
0.352;106.2
TA(9Q)
0.348;-10.6
9J(JA)
0.370;754.4
(9J)(QA)
0.387;871.3
JA(9Q)
0.321;106.2
9Q(QA)
0.411;988.1
9QQA
0.280;223.1
9KKA
0.320;456.9
T(TKA)
0.370;988.1
JJ(TA)
0.298;871.2
(TQKA)
0.373;456.9
TTTA
0.348;637.5
TA(TK)
0.376;988.1
(TK)(JA)
0.388;1105.0
KA(TJ)
0.388;340.0
TA(JK)
0.353;340.0
(TQ)(KA)
0.407;1221.9
(TK)(KA)
0.445;2103.8
J(JKA)
0.416;1221.9
(QK)(JA)
0.351;1338.8
JJ(KA)
0.418;1221.9
QA(JQ)
0.311;1221.9
JQKA
0.355;-191.2
QK(QA)
0.388;1455.6
QK(KA)
0.387;1572.5
22(24)
0.245;-2571.2
22(28)
0.299;-2103.8
22(2Q)
0.316;-1636.2
24(23)
0.196;-3219.4
(23)(27)
0.314;-2103.8
2(23T)
0.308;-2518.1
2Q(23)
0.221;-2284.4
23(25)
0.230;-3102.5
2237
0.203;-3633.8
22(3T)
0.267;-2518.1
23(2K)
0.344;-2167.5
2(246)
0.235;-2868.8
28(24)
0.298;-2635.0
(24)(2J)
0.292;-1519.4
2244
0.211;-3102.5
22(47)
0.257;-2751.9
24(2T)
0.232;-2401.2
224Q
0.245;-2932.5
26(25)
0.300;-2751.9
(25)(29)
0.334;-1636.2
2(25Q)
0.235;-2050.6
22(56)
0.265;-2751.9
25(29)
0.257;-2401.2
225J
0.235;-2932.5
26(26)
0.227;-1870.0
(26)(29)
0.281;-1519.4
2(26Q)
0.325;-1933.7
22(67)
0.279;-2518.1
26(2T)
0.310;-2167.5
226Q
0.262;-2698.8
28(27)
0.307;-2284.4
(27)(2J)
0.299;-1168.8
2277
0.258;-2401.2
22(7T)
0.274;-2050.6
27(2K)
0.306;-1700.0
2(28T)
0.274;-1933.7
2Q(28)
0.284;-1700.0
28(2T)
0.302;-1933.7
228Q
0.251;-2465.0
2T(29)
0.227;-1816.9
(29)(2K)
0.304;-701.2
229J
0.313;-2465.0
2T(2T)
0.332;-935.0
(2T)(2K)
0.262;-584.4
22TQ
0.251;-2231.2
2Q(2J)
0.294;-1349.4
2J(2K)
0.320;-1232.5
22QQ
0.255;-1232.5
3(234)
0.229;-3102.5
36(23)
0.247;-2868.8
(23)(39)
0.280;-1753.1
3(23Q)
0.318;-2167.5
5(234)
0.246;-3633.8
9(234)
0.189;-3166.3
K(234)
0.281;-2698.8
4(237)
0.207;-3400.0
49(23)
0.266;-3166.3
(23)(4Q)
0.335;-2050.6
(2357)
0.242;-3283.1
(235J)
0.213;-2815.6
(23)(56)
0.211;-2635.0
5(239)
0.246;-3049.4
5J(23)
0.301;-2815.6
(2367)
0.240;-3166.3
(236J)
0.267;-2698.8
(23)(67)
0.254;-2401.2
6(23T)
0.279;-2815.6
6Q(23)
0.271;-2581.9
9(237)
0.235;-2815.6
K(237)
0.275;-2348.1
7(23T)
0.289;-2698.8
7Q(23)
0.322;-2465.0
T(238)
0.299;-2581.9
8(239)
0.225;-2698.8
8J(23)
0.267;-2465.0
(239T)
0.305;-2465.0
99(23)
0.249;-1816.9
(23)(9Q)
0.331;-1466.2
(23TQ)
0.249;-2114.4
T(23Q)
0.294;-2114.4
Q(23J)
0.215;-1997.5
(23)(JK)
0.344;-1115.6
QK(23)
0.276;-1763.8
23(35)
0.267;-2985.6
33(28)
0.321;-2635.0
233T
0.243;-3166.3
23(3K)
0.282;-2050.6
(24)(36)
0.214;-2751.9
3(249)
0.231;-3166.3
3J(24)
0.263;-2932.5
(34)(25)
0.225;-2868.8
27(34)
0.234;-3400.0
2(34T)
0.276;-3049.4
(34)(2K)
0.273;-1933.7
34(26)
0.280;-3516.9
34(28)
0.274;-3283.1
34(2T)
0.275;-3049.4
34(2Q)
0.227;-2815.6
(25)(35)
0.285;-1986.9
3(258)
0.315;-3166.3
3T(25)
0.199;-2932.5
(25)(3K)
0.344;-1816.9
27(35)
0.234;-3283.1
2(35T)
0.320;-2932.5
(35)(2K)
0.291;-1816.9
35(27)
0.187;-3283.1
35(29)
0.288;-3049.4
35(2J)
0.246;-2815.6
35(2K)
0.334;-2581.9
37(26)
0.228;-3166.3
(26)(3T)
0.295;-2050.6
3(26K)
0.301;-2465.0
2(368)
0.248;-3049.4
(36)(2J)
0.285;-1933.7
2K(36)
0.235;-2465.0
23(68)
0.243;-3049.4
23(6T)
0.193;-2815.6
23(6Q)
0.267;-2581.9
3(278)
0.222;-2932.5
3T(27)
0.254;-2698.8
(27)(3K)
0.302;-1583.1
29(37)
0.300;-2815.6
2(37Q)
0.325;-2465.0
23(78)
0.277;-2932.5
23(7T)
0.270;-2698.8
23(7Q)
0.252;-2465.0
3(289)
0.281;-2698.8
3J(28)
0.237;-2465.0
(38)(29)
0.321;-1933.7
2J(38)
0.246;-2465.0
38(29)
0.265;-2698.8
38(2J)
0.265;-2465.0
38(2K)
0.352;-2231.2
3T(29)
0.294;-2465.0
(29)(3K)
0.299;-1349.4
2J(39)
0.255;-2348.1
39(2T)
0.269;-2465.0
39(2Q)
0.257;-2231.2
(2T)(3T)
0.284;-818.1
3(2TK)
0.239;-1997.5
2(3TQ)
0.247;-2114.4
23(TJ)
0.282;-2231.2
23(TK)
0.303;-1997.5
(2J)(3K)
0.329;-1115.6
2K(3J)
0.281;-1880.6
23(JK)
0.357;-1880.6
(3Q)(2K)
0.294;-998.7
(2K)(3K)
0.366;-116.9
4(246)
0.241;-2635.0
48(24)
0.296;-2401.2
(24)(4J)
0.270;-1285.6
5(245)
0.283;-2635.0
9(245)
0.209;-2932.5
K(245)
0.329;-2465.0
5(248)
0.241;-3049.4
5T(24)
0.230;-2815.6
(24)(5K)
0.290;-1700.0
9(246)
0.220;-2815.6
K(246)
0.295;-2348.1
6(249)
0.272;-2815.6
6J(24)
0.244;-2581.9
(2478)
0.224;-2815.6
(247Q)
0.274;-2348.1
7(249)
0.240;-2698.8
7J(24)
0.338;-2465.0
(2489)
0.299;-2581.9
(248K)
0.288;-2114.4
8T(24)
0.258;-2465.0
(24)(8K)
0.244;-1349.4
Q(249)
0.276;-2114.4
(24)(9J)
0.319;-1466.2
T(24T)
0.340;-1466.2
T(24J)
0.311;-2114.4
TK(24)
0.333;-1880.6
(24)(JQ)
0.336;-1115.6
QQ(24)
0.294;-998.7
24(45)
0.290;-2751.9
44(28)
0.322;-2401.2
244T
0.308;-2932.5
24(4K)
0.268;-1816.9
(25)(47)
0.245;-2401.2
4(25T)
0.253;-2815.6
4Q(25)
0.242;-2581.9
(45)(27)
0.279;-2401.2
29(45)
0.210;-2932.5
2(45Q)
0.247;-2581.9
24(56)
0.269;-3283.1
24(58)
0.253;-3049.4
24(5T)
0.238;-2815.6
24(5Q)
0.278;-2581.9
4(267)
0.257;-3049.4
49(26)
0.285;-2815.6
(26)(4Q)
0.290;-1700.0
27(46)
0.209;-3049.4
2(46T)
0.300;-2698.8
(46)(2K)
0.236;-1583.1
46(28)
0.244;-2932.5
46(2T)
0.264;-2698.8
46(2Q)
0.265;-2465.0
(27)(47)
0.303;-1402.5
4(27T)
0.285;-2581.9
4Q(27)
0.330;-2348.1
(47)(29)
0.320;-1933.7
2J(47)
0.241;-2465.0
47(28)
0.225;-2815.6
47(2T)
0.248;-2581.9
47(2Q)
0.261;-2348.1
(28)(48)
0.336;-1168.8
4(28J)
0.267;-2348.1
4K(28)
0.332;-2114.4
(48)(2J)
0.312;-1583.1
2K(48)
0.297;-2114.4
24(8T)
0.240;-2465.0
24(8Q)
0.288;-2231.2
4(29T)
0.286;-2348.1
4Q(29)
0.294;-2114.4
(49)(2J)
0.344;-1466.2
2K(49)
0.319;-1997.5
24(9J)
0.261;-2231.2
24(9K)
0.228;-1997.5
(2T)(4Q)
0.347;-1232.5
2J(4T)
0.269;-2114.4
4T(2J)
0.260;-2114.4
4T(2K)
0.286;-1880.6
4Q(2J)
0.351;-1880.6
(4J)(2K)
0.366;-998.7
4J(2K)
0.328;-1763.8
4K(2Q)
0.299;-1646.9
24(QK)
0.339;-1646.9
(25)(56)
0.337;-1636.2
5(259)
0.247;-2050.6
5J(25)
0.271;-1816.9
(2567)
0.286;-2932.5
(256J)
0.249;-2465.0
(25)(67)
0.340;-2167.5
6(25T)
0.325;-2581.9
6Q(25)
0.306;-2348.1
9(257)
0.248;-2581.9
K(257)
0.296;-2114.4
7(25T)
0.250;-2465.0
7Q(25)
0.219;-2231.2
T(258)
0.262;-2348.1
8(259)
0.294;-2465.0
8J(25)
0.297;-2231.2
(259T)
0.258;-2231.2
99(25)
0.285;-1583.1
(25)(9Q)
0.282;-1232.5
(25TQ)
0.321;-1880.6
T(25Q)
0.264;-1880.6
Q(25J)
0.276;-1763.8
(25)(JK)
0.381;-881.9
QK(25)
0.315;-1530.0
25(57)
0.297;-2284.4
55(2T)
0.304;-1933.7
255Q
0.261;-2465.0
57(26)
0.217;-2932.5
(26)(5T)
0.249;-1816.9
5(26K)
0.299;-2231.2
2(568)
0.228;-2815.6
(56)(2J)
0.360;-1700.0
2K(56)
0.280;-2231.2
25(68)
0.270;-2815.6
25(6T)
0.288;-2581.9
25(6Q)
0.273;-2348.1
5(278)
0.275;-2698.8
5T(27)
0.238;-2465.0
(27)(5K)
0.282;-1349.4
29(57)
0.226;-2581.9
2(57Q)
0.305;-2231.2
25(78)
0.303;-2698.8
25(7T)
0.269;-2465.0
25(7Q)
0.286;-2231.2
5(289)
0.260;-2465.0
5J(28)
0.254;-2231.2
(58)(29)
0.304;-1700.0
2J(58)
0.316;-2231.2
58(29)
0.262;-2465.0
58(2J)
0.268;-2231.2
58(2K)
0.304;-1997.5
5T(29)
0.244;-2231.2
(29)(5K)
0.381;-1115.6
2J(59)
0.248;-2114.4
59(2T)
0.246;-2231.2
59(2Q)
0.307;-1997.5
(2T)(5T)
0.290;-584.4
5(2TK)
0.296;-1763.8
2(5TQ)
0.268;-1880.6
25(TJ)
0.257;-1997.5
25(TK)
0.263;-1763.8
(2J)(5K)
0.270;-881.9
2K(5J)
0.235;-1646.9
25(JK)
0.244;-1646.9
(5Q)(2K)
0.282;-765.0
(2K)(5K)
0.332;116.9
6(268)
0.236;-1933.7
6T(26)
0.263;-1700.0
(26)(6K)
0.317;-584.4
T(267)
0.276;-2348.1
7(268)
0.311;-2581.9
7T(26)
0.306;-2348.1
(26)(7K)
0.288;-1232.5
J(268)
0.321;-2114.4
89(26)
0.253;-2348.1
(26)(8Q)
0.321;-1232.5
(269J)
0.295;-1997.5
(26)(9T)
0.307;-1349.4
9(26K)
0.274;-1763.8
(26TK)
0.305;-1646.9
TQ(26)
0.303;-1763.8
K(26J)
0.309;-1530.0
Q(26Q)
0.277;-765.0
KK(26)
0.389;-531.2
66(29)
0.301;-1816.9
266J
0.318;-2348.1
67(27)
0.234;-1933.7
(27)(6T)
0.292;-1583.1
6(27K)
0.290;-1997.5
2(679)
0.310;-2465.0
(67)(2Q)
0.338;-1349.4
27(68)
0.291;-2581.9
27(6T)
0.272;-2348.1
27(6Q)
0.262;-2114.4
68(28)
0.275;-1700.0
(28)(6J)
0.305;-1349.4
28(68)
0.316;-1700.0
2(68J)
0.311;-2114.4
2688
0.250;-2465.0
268T
0.310;-2996.2
268Q
0.224;-2762.5
(29)(6T)
0.244;-1349.4
6(29K)
0.329;-1763.8
2(69J)
0.332;-1997.5
2699
0.229;-2231.2
269J
0.240;-2762.5
269K
0.299;-2528.8
6Q(2T)
0.284;-1763.8
(6T)(2Q)
0.320;-998.7
2T(6J)
0.251;-1880.6
2T(6K)
0.291;-1646.9
6(2JK)
0.346;-1530.0
2(6JK)
0.333;-1530.0
2J(6K)
0.334;-1530.0
2Q(6Q)
0.334;-765.0
26QK
0.235;-2178.1
78(27)
0.314;-1700.0
(27)(7J)
0.380;-584.4
8(278)
0.296;-1583.1
Q(278)
0.302;-1880.6
(27)(8T)
0.299;-1349.4
8(27K)
0.293;-1763.8
(279Q)
0.247;-1763.8
9(27J)
0.281;-1880.6
9K(27)
0.339;-1646.9
TT(27)
0.247;-1115.6
(27)(TK)
0.298;-765.0
J(27Q)
0.332;-1530.0
K(27Q)
0.291;-1296.2
77(28)
0.312;-1700.0
277T
0.240;-2231.2
27(7K)
0.310;-1115.6
(28)(7T)
0.361;-1349.4
7(28K)
0.306;-1763.8
2(78T)
0.277;-2114.4
(78)(2K)
0.346;-998.7
78(2T)
0.237;-2114.4
78(2Q)
0.261;-1880.6
(29)(79)
0.385;-584.4
7(29Q)
0.270;-1763.8
2(79T)
0.349;-1997.5
(79)(2K)
0.363;-881.9
79(2J)
0.250;-1880.6
79(2K)
0.339;-1646.9
7J(2T)
0.277;-1763.8
(7T)(2J)
0.279;-998.7
2K(7T)
0.317;-1530.0
27(TQ)
0.277;-1646.9
7(2JQ)
0.300;-1530.0
2(7JQ)
0.287;-1530.0
27(JQ)
0.289;-1530.0
7(2QK)
0.263;-1296.2
7Q(2K)
0.354;-1296.2
88(28)
0.256;-701.2
(28)(8J)
0.321;-350.6
9(289)
0.298;-1232.5
K(289)
0.329;-1530.0
9(28Q)
0.307;-1646.9
J(28T)
0.281;-1646.9
TJ(28)
0.274;-1646.9
(28JQ)
0.302;-1413.1
J(28K)
0.260;-1296.2
(28)(QK)
0.300;-414.4
88(2T)
0.296;-1232.5
288Q
0.316;-1763.8
8T(29)
0.292;-1880.6
(29)(8K)
0.343;-765.0
2J(89)
0.297;-1763.8
89(2T)
0.264;-1880.6
89(2Q)
0.269;-1646.9
(2T)(8T)
0.311;-233.8
8(2TK)
0.316;-1413.1
2(8TQ)
0.361;-1530.0
28(TJ)
0.289;-1646.9
28(TK)
0.334;-1413.1
(2J)(8K)
0.272;-531.3
2K(8J)
0.349;-1296.2
28(JK)
0.272;-1296.2
(8Q)(2K)
0.314;-414.4
(2K)(8K)
0.363;467.5
9(29J)
0.263;-881.9
9K(29)
0.331;-648.1
TT(29)
0.349;-881.9
(29)(TK)
0.260;-531.3
J(29Q)
0.237;-1296.2
K(29Q)
0.295;-1062.5
99(2T)
0.341;-998.7
299Q
0.353;-1530.0
9J(2T)
0.267;-1530.0
(9T)(2J)
0.310;-765.0
2K(9T)
0.333;-1296.2
29(TQ)
0.296;-1413.1
9(2JQ)
0.343;-1296.2
2(9JQ)
0.315;-1296.2
29(JQ)
0.353;-1296.2
9(2QK)
0.332;-1062.5
9Q(2K)
0.317;-1062.5
TT(2T)
0.310;0.0
(2T)(TK)
0.373;350.6
J(2TQ)
0.270;-1179.4
K(2TQ)
0.304;-945.6
TT(2J)
0.343;-648.1
2TTK
0.293;-1179.4
TK(2J)
0.318;-1062.5
2TJJ
0.302;-1296.2
2TJK
0.267;-1827.5
2(TQK)
0.273;-945.6
TK(2K)
0.339;-63.7
(2J)(JK)
0.371;584.4
QK(2J)
0.360;-828.7
2J(JK)
0.301;-180.6
(JQ)(2K)
0.337;-63.7
(2K)(JK)
0.368;818.1
K(2QK)
0.269;170.0
2K(QK)
0.279;170.0
3335
0.260;-2868.8
3339
0.338;-2401.2
333K
0.297;-1933.7
36(34)
0.240;-2635.0
(34)(39)
0.258;-1519.4
3(34Q)
0.357;-1933.7
33(45)
0.244;-2751.9
34(38)
0.291;-2401.2
334T
0.292;-2932.5
33(4K)
0.301;-1816.9
(35)(37)
0.282;-1636.2
3(35T)
0.270;-2050.6
3Q(35)
0.323;-1816.9
35(37)
0.276;-2401.2
3359
0.220;-2932.5
33(5Q)
0.362;-1816.9
(36)(37)
0.276;-1519.4
3(36T)
0.326;-1933.7
3Q(36)
0.298;-1700.0
36(38)
0.291;-2167.5
336T
0.295;-2698.8
33(6K)
0.313;-1583.1
(37)(39)
0.317;-1168.8
3(37Q)
0.354;-1583.1
33(78)
0.305;-2050.6
37(3J)
0.294;-1700.0
337K
0.326;-2231.2
3T(38)
0.313;-1700.0
(38)(3K)
0.327;-584.4
338T
0.216;-2465.0
33(8K)
0.255;-1349.4
(39)(3J)
0.319;-701.2
3399
0.283;-1700.0
33(9Q)
0.335;-1349.4
(3T)(3J)
0.361;-584.4
33TT
0.349;-1466.2
33(TK)
0.292;-1115.6
(3J)(3K)
0.322;-233.8
33JK
0.328;-1763.8
33(QK)
0.314;-881.9
45(34)
0.254;-2635.0
(34)(48)
0.281;-1519.4
4(34J)
0.230;-1933.7
4K(34)
0.238;-1700.0
(3459)
0.254;-2815.6
(345K)
0.254;-2348.1
57(34)
0.258;-3049.4
(34)(5T)
0.309;-1933.7
5(34K)
0.239;-2348.1
(3469)
0.337;-2698.8
(346K)
0.345;-2231.2
68(34)
0.233;-2815.6
(34)(6J)
0.264;-1700.0
7(347)
0.288;-2050.6
J(347)
0.273;-2348.1
78(34)
0.304;-2698.8
(34)(7J)
0.299;-1583.1
8(348)
0.285;-1816.9
Q(348)
0.273;-2114.4
(34)(8T)
0.343;-1583.1
8(34K)
0.308;-1997.5
(349Q)
0.273;-1997.5
9(34J)
0.304;-2114.4
9K(34)
0.277;-1880.6
TT(34)
0.378;-1349.4
(34)(TK)
0.301;-998.7
J(34Q)
0.318;-1763.8
K(34Q)
0.245;-1530.0
44(35)
0.219;-2635.0
3447
0.238;-3166.3
34(4T)
0.342;-2050.6
44(3K)
0.300;-1700.0
4(357)
0.246;-3049.4
49(35)
0.275;-2815.6
(35)(4Q)
0.262;-1700.0
36(45)
0.311;-3166.3
3(459)
0.262;-2815.6
(45)(3Q)
0.292;-1700.0
35(46)
0.261;-3166.3
35(48)
0.252;-2932.5
35(4T)
0.197;-2698.8
35(4Q)
0.213;-2465.0
46(36)
0.237;-2284.4
(36)(49)
0.333;-1933.7
4(36Q)
0.291;-2348.1
3(467)
0.248;-2932.5
(46)(3T)
0.298;-1816.9
3Q(46)
0.300;-2348.1
3467
0.266;-3697.5
3469
0.191;-3463.8
346J
0.202;-3230.0
346K
0.242;-2996.2
49(37)
0.220;-2581.9
(37)(4Q)
0.300;-1466.2
38(47)
0.237;-2698.8
3(47J)
0.221;-2348.1
3477
0.253;-2815.6
3479
0.256;-3346.9
347J
0.258;-3113.1
347K
0.287;-2879.4
4T(38)
0.321;-2348.1
(38)(4K)
0.309;-1232.5
3T(48)
0.290;-2348.1
3(48K)
0.318;-1997.5
38(4T)
0.276;-2348.1
38(4Q)
0.292;-2114.4
49(39)
0.318;-1583.1
(39)(4Q)
0.307;-1232.5
3T(49)
0.279;-2231.2
3(49K)
0.299;-1880.6
39(4J)
0.288;-2114.4
39(4K)
0.270;-1880.6
4(3TQ)
0.311;-1880.6
3(4TJ)
0.264;-1997.5
34TT
0.283;-2114.4
34TQ
0.269;-2645.6
(3J)(4Q)
0.347;-998.7
3Q(4J)
0.299;-1763.8
34JQ
0.228;-2528.8
(3Q)(4K)
0.289;-765.0
3Q(4K)
0.296;-1530.0
5(356)
0.255;-2284.4
58(35)
0.284;-2050.6
(35)(5J)
0.300;-935.0
6(356)
0.258;-2167.5
T(356)
0.281;-2465.0
6(357)
0.242;-2815.6
69(35)
0.289;-2581.9
(35)(6Q)
0.293;-1466.2
(3579)
0.231;-2465.0
(357K)
0.271;-1997.5
79(35)
0.262;-2465.0
(35)(7Q)
0.302;-1349.4
(358T)
0.269;-2231.2
88(35)
0.267;-1700.0
(35)(8J)
0.285;-1349.4
9(359)
0.317;-1466.2
K(359)
0.264;-1763.8
9(35Q)
0.304;-1880.6
J(35T)
0.316;-1880.6
TJ(35)
0.308;-1880.6
(35JQ)
0.273;-1646.9
J(35K)
0.275;-1530.0
(35)(QK)
0.363;-648.1
55(37)
0.305;-2167.5
3559
0.244;-2698.8
35(5Q)
0.307;-1583.1
(36)(57)
0.288;-2050.6
5(36T)
0.310;-2465.0
5Q(36)
0.341;-2231.2
(56)(38)
0.310;-1933.7
3T(56)
0.221;-2465.0
3(56K)
0.347;-2114.4
36(58)
0.289;-2698.8
36(5T)
0.289;-2465.0
36(5Q)
0.250;-2231.2
57(37)
0.280;-1933.7
(37)(5T)
0.304;-1583.1
5(37K)
0.280;-1997.5
3(579)
0.271;-2465.0
(57)(3Q)
0.362;-1349.4
37(58)
0.235;-2581.9
37(5T)
0.279;-2348.1
37(5Q)
0.286;-2114.4
58(38)
0.313;-1700.0
(38)(5J)
0.338;-1349.4
38(58)
0.268;-1700.0
3(58J)
0.321;-2114.4
3588
0.214;-2465.0
358T
0.193;-2996.2
358Q
0.274;-2762.5
(39)(5T)
0.288;-1349.4
5(39K)
0.289;-1763.8
3(59J)
0.257;-1997.5
3599
0.248;-2231.2
359J
0.208;-2762.5
359K
0.250;-2528.8
5Q(3T)
0.276;-1763.8
(5T)(3Q)
0.268;-998.7
3T(5J)
0.280;-1880.6
3T(5K)
0.314;-1646.9
5(3JK)
0.339;-1530.0
3(5JK)
0.341;-1530.0
3J(5K)
0.334;-1530.0
3Q(5Q)
0.319;-765.0
35QK
0.286;-2178.1
67(36)
0.263;-1933.7
(36)(6T)
0.332;-818.1
6(36K)
0.296;-1232.5
(367T)
0.300;-2231.2
77(36)
0.271;-1816.9
(36)(7T)
0.321;-1466.2
7(36K)
0.306;-1880.6
(368J)
0.283;-1997.5
(36)(89)
0.315;-1466.2
8(36Q)
0.271;-1880.6
T(369)
0.287;-1997.5
9(36T)
0.276;-1997.5
9Q(36)
0.294;-1763.8
Q(36T)
0.297;-1646.9
(36)(TQ)
0.324;-881.9
(36JK)
0.271;-1413.1
JK(36)
0.326;-1413.1
K(36K)
0.379;-414.4
3668
0.305;-2581.9
36(6J)
0.301;-1466.2
(37)(67)
0.271;-1051.9
6(37T)
0.234;-2231.2
6Q(37)
0.297;-1997.5
(67)(39)
0.340;-1583.1
3J(67)
0.235;-2114.4
67(38)
0.325;-2465.0
67(3T)
0.218;-2231.2
67(3Q)
0.324;-1997.5
(38)(68)
0.310;-818.1
6(38J)
0.277;-1997.5
6K(38)
0.284;-1763.8
(68)(3J)
0.302;-1232.5
3K(68)
0.317;-1763.8
36(8T)
0.308;-2114.4
36(8Q)
0.346;-1880.6
6(39T)
0.320;-1997.5
6Q(39)
0.303;-1763.8
(69)(3J)
0.312;-1115.6
3K(69)
0.289;-1646.9
36(9J)
0.251;-1880.6
36(9K)
0.264;-1646.9
(3T)(6Q)
0.316;-881.9
3J(6T)
0.264;-1763.8
6T(3J)
0.234;-1763.8
6T(3K)
0.343;-1530.0
6Q(3J)
0.306;-1530.0
(6J)(3K)
0.344;-648.1
6J(3K)
0.302;-1413.1
6K(3Q)
0.315;-1296.2
36(QK)
0.311;-1296.2
(37)(78)
0.327;-818.1
7(37J)
0.298;-1232.5
7K(37)
0.337;-998.7
(378Q)
0.288;-1763.8
8(37T)
0.211;-1997.5
8Q(37)
0.356;-1763.8
J(379)
0.356;-1763.8
9T(37)
0.288;-1880.6
(37)(9K)
0.294;-765.0
K(37T)
0.347;-1413.1
T(37K)
0.304;-1413.1
JJ(37)
0.316;-765.0
(37QK)
0.270;-1179.4
3777
0.254;-1700.0
37(7T)
0.375;-1349.4
77(3K)
0.330;-998.7
7(38T)
0.282;-1997.5
7Q(38)
0.261;-1763.8
(78)(3T)
0.359;-1232.5
3Q(78)
0.308;-1763.8
3789
0.309;-2879.4
378J
0.308;-2645.6
378K
0.310;-2411.9
7J(39)
0.311;-1763.8
(79)(3T)
0.307;-1115.6
3Q(79)
0.276;-1646.9
379T
0.279;-2645.6
379Q
0.217;-2411.9
(3T)(7J)
0.308;-881.9
3T(7T)
0.319;-998.7
3(7TK)
0.274;-1413.1
3T(7Q)
0.304;-1530.0
7J(3J)
0.307;-765.0
(7J)(3Q)
0.344;-648.1
3J(7Q)
0.265;-1413.1
7Q(3Q)
0.319;-531.2
37QQ
0.344;-1296.2
37KK
0.373;-1062.5
8(38J)
0.270;-998.7
8K(38)
0.365;-765.0
(389K)
0.297;-1413.1
9J(38)
0.269;-1646.9
(38TJ)
0.257;-1530.0
(38)(TJ)
0.334;-765.0
J(38J)
0.348;-648.1
JQ(38)
0.279;-1296.2
Q(38K)
0.264;-1062.5
3889
0.226;-1997.5
38(8Q)
0.264;-881.9
(39)(8T)
0.340;-998.7
8(39K)
0.245;-1413.1
3(89J)
0.310;-1646.9
3899
0.304;-1880.6
389J
0.282;-2411.9
389K
0.260;-2178.1
8Q(3T)
0.328;-1413.1
(8T)(3Q)
0.307;-648.1
3T(8J)
0.329;-1530.0
3T(8K)
0.333;-1296.2
8(3JK)
0.310;-1179.4
3(8JK)
0.282;-1179.4
3J(8K)
0.328;-1179.4
3Q(8Q)
0.297;-414.4
38QK
0.272;-1827.5
9T(39)
0.282;-881.9
(39)(9K)
0.328;233.8
K(39T)
0.286;-1179.4
T(39K)
0.279;-1179.4
JJ(39)
0.306;-531.2
(39QK)
0.296;-945.6
3999
0.369;-998.7
39(9Q)
0.314;-648.1
(3T)(9J)
0.293;-648.1
3T(9T)
0.279;-765.0
3(9TK)
0.349;-1179.4
3T(9Q)
0.335;-1296.2
9J(3J)
0.327;-531.2
(9J)(3Q)
0.309;-414.4
3J(9Q)
0.374;-1179.4
9Q(3Q)
0.315;-297.5
39QQ
0.305;-1062.5
39KK
0.321;-828.7
T(3TK)
0.312;-297.5
JJ(3T)
0.317;-414.4
(3TQK)
0.311;-828.7
3TTT
0.350;-648.1
3T(TK)
0.328;-297.5
(3J)(TK)
0.308;-180.6
3K(TJ)
0.269;-945.6
3T(JK)
0.290;-945.6
(TQ)(3K)
0.338;-63.7
(3K)(TK)
0.339;818.1
J(3JK)
0.425;-63.7
(3J)(QK)
0.344;53.1
JJ(3K)
0.340;-63.7
3Q(JQ)
0.394;-63.7
3JQK
0.253;-1476.9
QK(3Q)
0.385;170.0
QK(3K)
0.327;286.9
44(46)
0.317;-1636.2
44(4T)
0.341;-1168.7
(45)(45)
0.317;-871.3
4(458)
0.251;-2050.6
4T(45)
0.223;-1816.9
(45)(4K)
0.313;-701.2
4457
0.288;-2932.5
44(5T)
0.332;-1816.9
45(4K)
0.369;-1466.2
4(468)
0.316;-1933.7
4T(46)
0.291;-1700.0
(46)(4K)
0.299;-584.4
4468
0.223;-2698.8
44(6J)
0.315;-1583.1
(47)(47)
0.305;-403.7
4(47T)
0.336;-1583.1
4Q(47)
0.346;-1349.4
47(49)
0.271;-1700.0
447J
0.263;-2231.2
48(48)
0.298;-935.0
(48)(4J)
0.286;-584.4
4488
0.280;-1700.0
44(8J)
0.369;-1349.4
(49)(49)
0.288;63.7
4(49Q)
0.320;-1115.6
44(9T)
0.327;-1349.4
49(4K)
0.328;-998.7
4(4TQ)
0.328;-998.7
44(TJ)
0.302;-1115.6
(4J)(4J)
0.344;531.3
44JJ
0.385;-998.7
4Q(4Q)
0.340;0.0
(4K)(4K)
0.310;998.7
(45)(57)
0.270;-1285.6
5(45T)
0.303;-1700.0
5Q(45)
0.322;-1466.2
8(456)
0.230;-2581.9
Q(456)
0.261;-2114.4
(45)(68)
0.283;-1816.9
6(45J)
0.268;-2231.2
6K(45)
0.337;-1997.5
(457J)
0.346;-2114.4
(45)(78)
0.261;-1700.0
7(45J)
0.238;-2114.4
7K(45)
0.237;-1880.6
(458Q)
0.258;-1880.6
8(45T)
0.319;-2114.4
8Q(45)
0.302;-1880.6
J(459)
0.261;-1880.6
9T(45)
0.255;-1997.5
(45)(9K)
0.282;-881.9
K(45T)
0.266;-1530.0
T(45K)
0.328;-1530.0
JJ(45)
0.310;-881.9
(45QK)
0.284;-1296.2
4555
0.312;-2284.4
45(58)
0.297;-1933.7
55(4J)
0.320;-1583.1
455K
0.320;-2114.4
58(46)
0.250;-2581.9
(46)(5J)
0.274;-1466.2
46(56)
0.239;-2050.6
4(569)
0.307;-2465.0
(56)(4Q)
0.363;-1349.4
46(57)
0.232;-2698.8
46(59)
0.251;-2465.0
46(5J)
0.307;-2231.2
46(5K)
0.239;-1997.5
5(479)
0.234;-2348.1
5J(47)
0.251;-2114.4
(57)(48)
0.252;-1700.0
4T(57)
0.284;-2231.2
4(57K)
0.322;-1880.6
47(59)
0.292;-2348.1
47(5J)
0.238;-2114.4
47(5K)
0.277;-1880.6
5(48T)
0.214;-2114.4
5Q(48)
0.355;-1880.6
(58)(4T)
0.331;-1349.4
4Q(58)
0.305;-1880.6
4589
0.304;-2996.2
458J
0.208;-2762.5
458K
0.258;-2528.8
5J(49)
0.306;-1880.6
(59)(4T)
0.300;-1232.5
4Q(59)
0.340;-1763.8
459T
0.315;-2762.5
459Q
0.281;-2528.8
(4T)(5J)
0.349;-998.7
4T(5T)
0.302;-1115.6
4(5TK)
0.325;-1530.0
4T(5Q)
0.307;-1646.9
5J(4J)
0.368;-881.9
(5J)(4Q)
0.295;-765.0
4J(5Q)
0.267;-1530.0
5Q(4Q)
0.332;-648.1
45QQ
0.310;-1413.1
45KK
0.260;-1179.4
6(469)
0.257;-1583.1
6J(46)
0.240;-1349.4
(4678)
0.296;-2348.1
(467Q)
0.306;-1880.6
7(469)
0.256;-2231.2
7J(46)
0.291;-1997.5
(4689)
0.285;-2114.4
(468K)
0.255;-1646.9
8T(46)
0.313;-1997.5
(46)(8K)
0.322;-881.9
Q(469)
0.293;-1646.9
(46)(9J)
0.311;-998.7
T(46T)
0.357;-998.7
T(46J)
0.324;-1646.9
TK(46)
0.359;-1413.1
(46)(JQ)
0.332;-648.1
QQ(46)
0.386;-531.2
46(67)
0.261;-1816.9
66(4T)
0.309;-1466.2
466Q
0.249;-1997.5
68(47)
0.223;-2348.1
(47)(6J)
0.307;-1232.5
47(67)
0.309;-1700.0
4(67T)
0.269;-2114.4
(67)(4K)
0.295;-998.7
67(49)
0.274;-2231.2
67(4J)
0.254;-1997.5
67(4K)
0.307;-1763.8
69(48)
0.288;-2114.4
(48)(6Q)
0.393;-998.7
49(68)
0.289;-2114.4
4(68Q)
0.300;-1763.8
46(89)
0.270;-2114.4
46(8J)
0.263;-1880.6
46(8K)
0.221;-1646.9
(49)(6J)
0.314;-998.7
49(69)
0.310;-1232.5
4(69Q)
0.301;-1646.9
46(9T)
0.280;-1880.6
46(9Q)
0.267;-1646.9
6(4TJ)
0.307;-1646.9
6K(4T)
0.304;-1413.1
(6T)(4K)
0.272;-648.1
6T(4Q)
0.315;-1530.0
(4J)(6J)
0.337;0.0
4J(6J)
0.296;-765.0
6J(4Q)
0.294;-1413.1
(4Q)(6Q)
0.353;233.8
4K(6Q)
0.314;-1179.4
4K(6K)
0.293;-297.5
79(47)
0.280;-1349.4
(47)(7Q)
0.343;-233.8
(478T)
0.303;-1880.6
88(47)
0.309;-1349.4
(47)(8J)
0.265;-998.7
9(479)
0.308;-1115.6
K(479)
0.329;-1413.1
9(47Q)
0.340;-1530.0
J(47T)
0.292;-1530.0
TJ(47)
0.317;-1530.0
(47JQ)
0.321;-1296.2
J(47K)
0.373;-1179.4
(47)(QK)
0.328;-297.5
77(49)
0.289;-1349.4
477J
0.283;-1880.6
78(48)
0.282;-1349.4
(48)(7J)
0.300;-998.7
48(78)
0.270;-1349.4
4(78J)
0.232;-1763.8
4788
0.341;-2114.4
478T
0.219;-2645.6
478Q
0.263;-2411.9
(49)(7T)
0.274;-998.7
7(49K)
0.297;-1413.1
4(79J)
0.287;-1646.9
4799
0.335;-1880.6
479J
0.219;-2411.9
479K
0.349;-2178.1
7Q(4T)
0.362;-1413.1
(7T)(4Q)
0.340;-648.1
4T(7J)
0.362;-1530.0
4T(7K)
0.281;-1296.2
7(4JK)
0.319;-1179.4
4(7JK)
0.277;-1179.4
4J(7K)
0.257;-1179.4
4Q(7Q)
0.296;-414.4
47QK
0.290;-1827.5
89(48)
0.324;-1115.6
(48)(8Q)
0.309;0.0
(489J)
0.320;-1530.0
(48)(9T)
0.319;-881.9
9(48K)
0.326;-1296.2
(48TK)
0.290;-1179.4
TQ(48)
0.291;-1296.2
K(48J)
0.267;-1062.5
Q(48Q)
0.286;-297.5
KK(48)
0.388;-63.7
88(4J)
0.359;-881.9
488K
0.311;-1413.1
8J(49)
0.299;-1530.0
(89)(4T)
0.336;-881.9
4Q(89)
0.278;-1413.1
489T
0.301;-2411.9
489Q
0.261;-2178.1
(4T)(8J)
0.279;-648.1
4T(8T)
0.286;-765.0
4(8TK)
0.338;-1179.4
4T(8Q)
0.312;-1296.2
8J(4J)
0.302;-531.2
(8J)(4Q)
0.313;-414.4
4J(8Q)
0.302;-1179.4
8Q(4Q)
0.352;-297.5
48QQ
0.240;-1062.5
48KK
0.372;-828.7
9(49Q)
0.266;-531.2
J(49T)
0.253;-1296.2
TJ(49)
0.374;-1296.2
(49JQ)
0.295;-1062.5
J(49K)
0.337;-945.6
(49)(QK)
0.365;-63.7
99(4J)
0.319;-648.1
499K
0.343;-1179.4
9Q(4T)
0.249;-1179.4
(9T)(4Q)
0.351;-414.4
4T(9J)
0.288;-1296.2
4T(9K)
0.285;-1062.5
9(4JK)
0.318;-945.6
4(9JK)
0.290;-945.6
4J(9K)
0.375;-945.6
4Q(9Q)
0.277;-180.6
49QK
0.307;-1593.8
TJ(4T)
0.380;-414.4
(4TJQ)
0.245;-945.6
J(4TK)
0.261;-828.7
(4T)(QK)
0.345;53.1
TT(4Q)
0.336;-297.5
T(4JQ)
0.343;-945.6
4(TJQ)
0.292;-945.6
4T(JQ)
0.307;-945.6
T(4QK)
0.377;-711.9
TQ(4K)
0.331;-711.9
JJ(4J)
0.396;584.4
(4JQK)
0.302;-595.0
4JJJ
0.327;-180.6
JQ(4Q)
0.295;53.1
4JQQ
0.323;-711.9
4JKK
0.322;-478.1
QQ(4K)
0.373;286.9
4KKK
0.372;520.6
55(59)
0.312;-935.0
55(5K)
0.328;-467.5
(56)(58)
0.347;-935.0
5(56J)
0.323;-1349.4
5K(56)
0.333;-1115.6
56(59)
0.338;-1583.1
556J
0.328;-2114.4
57(57)
0.347;-935.0
(57)(5T)
0.324;-584.4
5(57K)
0.317;-998.7
55(79)
0.291;-1466.2
57(5Q)
0.263;-1115.6
5(589)
0.304;-1349.4
5J(58)
0.294;-1115.6
58(59)
0.337;-1349.4
558J
0.245;-1880.6
59(59)
0.320;-467.5
(59)(5Q)
0.372;-116.9
559T
0.327;-1880.6
55(9K)
0.310;-765.0
(5T)(5Q)
0.356;0.0
55TJ
0.306;-1646.9
5J(5J)
0.370;0.0
5J(5Q)
0.344;-648.1
5(5QK)
0.349;-414.4
5K(5K)
0.357;467.5
68(56)
0.306;-1583.1
(56)(6J)
0.351;-467.5
7(567)
0.259;-1583.1
J(567)
0.280;-1880.6
78(56)
0.243;-2231.2
(56)(7J)
0.282;-1115.6
8(568)
0.292;-1349.4
Q(568)
0.275;-1646.9
(56)(8T)
0.290;-1115.6
8(56K)
0.302;-1530.0
(569Q)
0.366;-1530.0
9(56J)
0.315;-1646.9
9K(56)
0.277;-1413.1
TT(56)
0.266;-881.9
(56)(TK)
0.310;-531.3
J(56Q)
0.249;-1296.2
K(56Q)
0.383;-1062.5
66(57)
0.284;-1700.0
5669
0.335;-2231.2
56(6Q)
0.353;-1115.6
(57)(68)
0.313;-1466.2
6(57J)
0.319;-1880.6
6K(57)
0.288;-1646.9
(67)(5T)
0.307;-1232.5
5Q(67)
0.301;-1763.8
5678
0.259;-2996.2
567T
0.229;-2762.5
567Q
0.259;-2528.8
(58)(69)
0.360;-1232.5
6(58Q)
0.247;-1646.9
5(689)
0.256;-1997.5
(68)(5Q)
0.324;-881.9
58(69)
0.261;-1997.5
58(6J)
0.305;-1763.8
58(6K)
0.312;-1530.0
6(59J)
0.259;-1646.9
6K(59)
0.310;-1413.1
(69)(5Q)
0.317;-765.0
59(6T)
0.270;-1763.8
59(6Q)
0.300;-1530.0
6T(5T)
0.289;-881.9
(5T)(6K)
0.272;-531.3
5Q(6T)
0.305;-1413.1
56TJ
0.329;-2295.0
56TK
0.250;-2061.2
6K(5J)
0.334;-1179.4
56JJ
0.272;-1413.1
56JK
0.282;-1944.4
5(6QK)
0.256;-1062.5
6K(5K)
0.354;-180.6
(57)(79)
0.326;-467.5
7(57Q)
0.273;-881.9
9(578)
0.305;-1880.6
K(578)
0.273;-1413.1
8(57J)
0.341;-1646.9
8K(57)
0.241;-1413.1
(579K)
0.360;-1296.2
9J(57)
0.345;-1530.0
(57TJ)
0.299;-1413.1
(57)(TJ)
0.321;-648.1
J(57J)
0.304;-531.2
JQ(57)
0.325;-1179.4
Q(57K)
0.286;-945.6
5778
0.277;-2114.4
57(7J)
0.295;-998.7
(58)(78)
0.328;-467.5
7(58J)
0.268;-1646.9
7K(58)
0.324;-1413.1
(78)(5J)
0.265;-881.9
5K(78)
0.299;-1413.1
57(8T)
0.354;-1763.8
57(8Q)
0.267;-1530.0
7(59T)
0.305;-1646.9
7Q(59)
0.341;-1413.1
(79)(5J)
0.281;-765.0
5K(79)
0.315;-1296.2
57(9J)
0.348;-1530.0
57(9K)
0.286;-1296.2
(5T)(7Q)
0.329;-531.3
5J(7T)
0.275;-1413.1
7T(5J)
0.328;-1413.1
7T(5K)
0.280;-1179.4
7Q(5J)
0.336;-1179.4
(7J)(5K)
0.312;-297.5
7J(5K)
0.238;-1062.5
7K(5Q)
0.317;-945.6
57(QK)
0.302;-945.6
(58)(89)
0.317;-233.8
8(58Q)
0.367;-648.1
T(589)
0.306;-1530.0
9(58T)
0.313;-1530.0
9Q(58)
0.266;-1296.2
Q(58T)
0.368;-1179.4
(58)(TQ)
0.329;-414.4
(58JK)
0.316;-945.6
JK(58)
0.279;-945.6
K(58K)
0.347;53.1
588T
0.304;-1646.9
58(8K)
0.255;-531.2
(59)(8J)
0.348;-648.1
59(89)
0.369;-881.9
5(89Q)
0.296;-1296.2
58(9T)
0.313;-1530.0
58(9Q)
0.275;-1296.2
8(5TJ)
0.262;-1296.2
8K(5T)
0.268;-1062.5
(8T)(5K)
0.293;-297.5
8T(5Q)
0.310;-1179.4
(5J)(8J)
0.294;350.6
5J(8J)
0.380;-414.4
8J(5Q)
0.286;-1062.5
(5Q)(8Q)
0.300;584.4
5K(8Q)
0.381;-828.7
5K(8K)
0.398;53.1
9J(59)
0.362;-531.2
(59TJ)
0.326;-1179.4
(59)(TJ)
0.258;-414.4
J(59J)
0.344;-297.5
JQ(59)
0.353;-945.6
Q(59K)
0.293;-711.9
599T
0.306;-1413.1
59(9K)
0.328;-297.5
(5T)(9Q)
0.367;-297.5
5J(9T)
0.323;-1179.4
9T(5J)
0.312;-1179.4
9T(5K)
0.279;-945.6
9Q(5J)
0.321;-945.6
(9J)(5K)
0.339;-63.7
9J(5K)
0.308;-828.7
9K(5Q)
0.393;-711.9
59(QK)
0.324;-711.9
(5T)(TJ)
0.342;467.5
J(5TJ)
0.299;-180.6
JQ(5T)
0.300;-828.7
Q(5TK)
0.340;-595.0
5TTJ
0.317;-1062.5
TJ(5J)
0.329;-180.6
(TJ)(5Q)
0.335;-63.7
5J(TQ)
0.300;-828.7
TQ(5Q)
0.336;53.1
5TQQ
0.271;-711.9
5TKK
0.394;-478.1
Q(5JQ)
0.341;170.0
KK(5J)
0.332;403.8
(5Q)(JQ)
0.339;935.0
5K(JQ)
0.291;-478.1
5K(JK)
0.314;403.8
5QQQ
0.376;286.9
KK(5K)
0.404;1402.5
6669
0.328;-1349.4
666K
0.268;-881.9
69(67)
0.334;-1232.5
(67)(6Q)
0.286;-116.9
6678
0.257;-2114.4
66(7J)
0.288;-998.7
(68)(68)
0.323;297.5
6(68J)
0.328;-881.9
6K(68)
0.285;-648.1
68(6J)
0.290;-881.9
668K
0.339;-1413.1
6J(69)
0.353;-765.0
69(6T)
0.263;-881.9
669Q
0.333;-1413.1
6J(6T)
0.373;-648.1
6T(6J)
0.335;-648.1
66TK
0.346;-1179.4
6K(6J)
0.326;-297.5
(6Q)(6Q)
0.372;1232.5
66QK
0.286;-945.6
7(679)
0.274;-1115.6
7J(67)
0.349;-881.9
(6789)
0.249;-1763.8
(678K)
0.319;-1296.2
8T(67)
0.324;-1646.9
(67)(8K)
0.314;-531.3
Q(679)
0.321;-1296.2
(67)(9J)
0.321;-648.1
T(67T)
0.347;-648.1
T(67J)
0.263;-1296.2
TK(67)
0.289;-1062.5
(67)(JQ)
0.375;-297.5
QQ(67)
0.361;-180.6
67(78)
0.280;-1232.5
77(6J)
0.320;-881.9
677K
0.302;-1413.1
7T(68)
0.260;-1646.9
(68)(7K)
0.384;-531.3
6T(78)
0.234;-1646.9
6(78K)
0.284;-1296.2
68(7T)
0.353;-1646.9
68(7Q)
0.303;-1413.1
79(69)
0.269;-881.9
(69)(7Q)
0.343;-531.3
6T(79)
0.307;-1530.0
6(79K)
0.262;-1179.4
69(7J)
0.332;-1413.1
69(7K)
0.372;-1179.4
7(6TQ)
0.238;-1179.4
6(7TJ)
0.284;-1296.2
67TT
0.313;-1413.1
67TQ
0.301;-1944.4
(6J)(7Q)
0.340;-297.5
6Q(7J)
0.283;-1062.5
67JQ
0.286;-1827.5
(6Q)(7K)
0.261;-63.7
6Q(7K)
0.327;-828.7
8(689)
0.274;-881.9
8J(68)
0.350;-648.1
(689T)
0.309;-1413.1
99(68)
0.271;-765.0
(68)(9Q)
0.351;-414.4
(68TQ)
0.304;-1062.5
T(68Q)
0.336;-1062.5
Q(68J)
0.301;-945.6
(68)(JK)
0.386;-63.7
QK(68)
0.338;-711.9
68(8T)
0.275;-765.0
88(6K)
0.338;-414.4
8(69J)
0.259;-1296.2
8K(69)
0.331;-1062.5
(89)(6Q)
0.286;-414.4
69(8T)
0.270;-1413.1
69(8Q)
0.280;-1179.4
8T(6T)
0.338;-531.2
(6T)(8K)
0.349;-180.6
6Q(8T)
0.345;-1062.5
68TJ
0.306;-1944.4
68TK
0.314;-1710.6
8K(6J)
0.363;-828.7
68JJ
0.307;-1062.5
68JK
0.334;-1593.8
6(8QK)
0.270;-711.9
8K(6K)
0.317;170.0
(69)(9J)
0.349;350.6
T(69T)
0.309;-414.4
T(69J)
0.323;-1062.5
TK(69)
0.362;-828.7
(69)(JQ)
0.364;-63.7
QQ(69)
0.310;53.1
69(9T)
0.275;-531.2
99(6K)
0.298;-180.6
9(6TQ)
0.285;-945.6
6(9TJ)
0.331;-1062.5
69TT
0.364;-1179.4
69TQ
0.239;-1710.6
(6J)(9Q)
0.365;-63.7
6Q(9J)
0.339;-828.7
69JQ
0.355;-1593.8
(6Q)(9K)
0.368;170.0
6Q(9K)
0.331;-595.0
T(6TJ)
0.327;-180.6
TK(6T)
0.331;53.1
(6T)(JQ)
0.321;53.1
QQ(6T)
0.423;170.0
6T(TJ)
0.336;-180.6
(6J)(TJ)
0.288;701.2
6J(TJ)
0.356;-63.7
TJ(6Q)
0.366;-711.9
(6Q)(TQ)
0.337;935.0
6K(TQ)
0.326;-478.1
6K(TK)
0.306;403.8
JK(6J)
0.368;286.9
K(6JK)
0.397;520.6
6JJK
0.292;-478.1
6(JQK)
0.345;-361.2
JK(6K)
0.288;520.6
KK(6Q)
0.315;637.5
6QKK
0.359;-127.5
77(7T)
0.387;-116.9
(78)(78)
0.378;531.3
7(78J)
0.328;-648.1
7K(78)
0.400;-414.4
78(7J)
0.319;-648.1
778K
0.285;-1179.4
7J(79)
0.275;-531.2
79(7T)
0.358;-648.1
779Q
0.278;-1179.4
7J(7T)
0.345;-414.4
7T(7J)
0.286;-414.4
77TK
0.271;-945.6
7K(7J)
0.329;-63.7
(7Q)(7Q)
0.353;1466.3
77QK
0.305;-711.9
8(78T)
0.322;-648.1
8Q(78)
0.350;-414.4
J(789)
0.345;-1179.4
9T(78)
0.324;-1296.2
(78)(9K)
0.340;-180.6
K(78T)
0.357;-828.7
T(78K)
0.343;-828.7
JJ(78)
0.401;-180.6
(78QK)
0.372;-595.0
7888
0.320;-881.9
78(8J)
0.331;-531.2
(79)(89)
0.363;116.9
8(79Q)
0.311;-1062.5
7(89T)
0.333;-1296.2
(89)(7K)
0.399;-180.6
89(7J)
0.283;-1179.4
89(7K)
0.316;-945.6
8J(7T)
0.288;-1062.5
(8T)(7J)
0.347;-297.5
7K(8T)
0.260;-828.7
78(TQ)
0.292;-945.6
8(7JQ)
0.321;-828.7
7(8JQ)
0.312;-828.7
78(JQ)
0.329;-828.7
8(7QK)
0.290;-595.0
8Q(7K)
0.275;-595.0
99(79)
0.327;233.7
(79)(9Q)
0.318;584.4
(79TQ)
0.341;-828.7
T(79Q)
0.277;-828.7
Q(79J)
0.320;-711.9
(79)(JK)
0.341;170.0
QK(79)
0.374;-478.1
79(9J)
0.366;-297.5
(7T)(9T)
0.321;467.5
9(7TK)
0.317;-711.9
7(9TQ)
0.373;-828.7
79(TJ)
0.360;-945.6
79(TK)
0.269;-711.9
(7J)(9K)
0.341;170.0
7K(9J)
0.362;-595.0
79(JK)
0.345;-595.0
(9Q)(7K)
0.313;286.9
(7K)(9K)
0.364;1168.8
T(7TQ)
0.338;53.1
Q(7TJ)
0.352;-595.0
(7T)(JK)
0.307;286.9
QK(7T)
0.321;-361.2
7T(TQ)
0.355;53.1
(7J)(TQ)
0.271;170.0
7Q(TJ)
0.368;-595.0
7TJQ
0.314;-1360.0
(7Q)(TK)
0.292;403.8
7Q(TK)
0.282;-361.2
J(7JQ)
0.322;286.9
K(7JQ)
0.360;-244.4
JJ(7Q)
0.312;286.9
J(7QK)
0.326;-244.4
JQ(7K)
0.315;-244.4
QQ(7Q)
0.334;1285.6
7Q(QK)
0.367;637.5
8888
0.367;0.0
888Q
0.306;-297.5
8(89J)
0.357;-297.5
8K(89)
0.319;-63.7
89(8Q)
0.289;-180.6
8(8TJ)
0.292;-180.6
8K(8T)
0.311;53.1
8T(8K)
0.340;53.1
8(8JK)
0.360;170.0
88(JK)
0.347;170.0
8Q(8K)
0.377;286.9
(89)(9T)
0.319;467.5
9(89K)
0.346;53.1
(89TK)
0.369;-595.0
TQ(89)
0.331;-711.9
K(89J)
0.308;-478.1
Q(89Q)
0.309;286.9
KK(89)
0.349;520.6
99(8Q)
0.301;-63.7
9(8TJ)
0.325;-828.7
9K(8T)
0.319;-595.0
(9T)(8K)
0.369;170.0
9T(8Q)
0.252;-711.9
(8J)(9J)
0.340;818.1
8J(9J)
0.300;53.1
9J(8Q)
0.379;-595.0
(8Q)(9Q)
0.370;1051.9
8K(9Q)
0.326;-361.2
8K(9K)
0.336;520.6
TQ(8T)
0.325;170.0
K(8TJ)
0.325;-361.2
Q(8TQ)
0.401;403.8
KK(8T)
0.329;637.5
