AAAA
0.462;-505.0
5AAA
0.286;-825.6
9AAA
0.398;-743.1
KAAA
0.388;-660.6
4A(2A)
0.283;-1093.8
(2A)(7A)
0.311;-896.9
A(2TA)
0.321;-970.0
QA(2A)
0.306;-928.7
2A(4A)
0.262;-1093.8
26AA
0.312;-1187.5
AA(29)
0.255;-990.6
2A(QA)
0.341;-928.7
A(34A)
0.283;-1073.1
6A(3A)
0.285;-1031.9
(3A)(9A)
0.285;-835.0
A(3QA)
0.296;-908.1
AA(34)
0.261;-1073.1
3A(7A)
0.329;-1011.2
39AA
0.244;-1105.0
AA(3Q)
0.369;-908.1
(4A)(5A)
0.354;-896.9
A(48A)
0.342;-970.0
TA(4A)
0.315;-928.7
(4A)(KA)
0.306;-731.9
46AA
0.309;-1146.2
AA(49)
0.284;-949.4
4A(QA)
0.356;-887.5
A(56A)
0.326;-990.6
8A(5A)
0.316;-949.4
(5A)(JA)
0.321;-752.5
55AA
0.334;-1011.2
AA(58)
0.336;-949.4
5A(JA)
0.270;-887.5
5KAA
0.359;-981.3
8A(6A)
0.361;-928.7
(6A)(JA)
0.356;-731.9
66AA
0.300;-970.0
AA(69)
0.281;-908.1
6A(QA)
0.358;-846.3
A(78A)
0.305;-908.1
TA(7A)
0.354;-866.9
(7A)(KA)
0.384;-670.0
79AA
0.294;-1022.5
AA(7Q)
0.385;-825.6
(8A)(9A)
0.351;-731.9
A(8QA)
0.331;-805.0
AA(89)
0.344;-866.9
8A(QA)
0.295;-805.0
A(9TA)
0.375;-825.6
QA(9A)
0.328;-784.4
9A(JA)
0.326;-805.0
9KAA
0.299;-898.7
QA(TA)
0.315;-763.8
TA(QA)
0.359;-763.8
A(JQA)
0.360;-743.1
AA(JQ)
0.375;-743.1
(QA)(KA)
0.403;-566.9
KKAA
0.410;-681.2
2(25A)
0.241;-1320.6
27(2A)
0.265;-1279.4
(2T)(2A)
0.309;-1082.5
2(2KA)
0.292;-1155.6
(236A)
0.228;-1414.4
(23TA)
0.254;-1331.9
33(2A)
0.266;-1341.2
(36)(2A)
0.303;-1279.4
3(29A)
0.264;-1352.5
3J(2A)
0.309;-1311.2
(245A)
0.300;-1414.4
(249A)
0.232;-1331.9
(24KA)
0.249;-1249.4
46(2A)
0.230;-1393.8
(49)(2A)
0.253;-1196.9
4(2QA)
0.240;-1270.0
6(25A)
0.233;-1373.1
T(25A)
0.230;-1290.6
5(26A)
0.231;-1373.1
58(2A)
0.251;-1331.9
(5J)(2A)
0.290;-1135.0
6(26A)
0.269;-1217.5
T(26A)
0.262;-1270.0
6(27A)
0.303;-1331.9
69(2A)
0.285;-1290.6
(6Q)(2A)
0.292;-1093.8
(279A)
0.207;-1270.0
(27KA)
0.299;-1187.5
79(2A)
0.262;-1270.0
(7Q)(2A)
0.319;-1073.1
(28TA)
0.283;-1228.8
88(2A)
0.236;-1135.0
(8J)(2A)
0.314;-1073.1
9(29A)
0.308;-1093.8
K(29A)
0.272;-1146.2
9(2QA)
0.226;-1166.9
J(2TA)
0.303;-1166.9
TJ(2A)
0.247;-1166.9
(2JQA)
0.257;-1125.6
J(2KA)
0.228;-1105.0
(QK)(2A)
0.367;-949.4
22(4A)
0.263;-1341.2
226A
0.215;-1435.0
2A(29)
0.286;-1238.1
22(QA)
0.275;-1176.2
2(34A)
0.211;-1455.6
26(3A)
0.290;-1414.4
(29)(3A)
0.218;-1217.5
2(3QA)
0.270;-1290.6
A(234)
0.187;-1455.6
(23)(7A)
0.225;-1258.8
9A(23)
0.275;-1352.5
A(23Q)
0.266;-1290.6
2A(34)
0.286;-1455.6
2A(36)
0.244;-1414.4
2A(38)
0.213;-1373.1
2A(3T)
0.253;-1331.9
2A(3Q)
0.304;-1290.6
2(45A)
0.259;-1414.4
27(4A)
0.229;-1373.1
(2T)(4A)
0.263;-1176.2
2(4KA)
0.252;-1249.4
A(246)
0.290;-1393.8
(24)(9A)
0.297;-1196.9
JA(24)
0.294;-1290.6
24(5A)
0.247;-1414.4
24(7A)
0.223;-1373.1
24(9A)
0.299;-1331.9
24(JA)
0.285;-1290.6
24(KA)
0.236;-1249.4
26(5A)
0.246;-1373.1
(29)(5A)
0.247;-1176.2
2(5QA)
0.274;-1249.4
A(256)
0.209;-1373.1
(25)(9A)
0.344;-1176.2
JA(25)
0.249;-1270.0
25(6A)
0.294;-1373.1
25(8A)
0.274;-1331.9
25(TA)
0.250;-1290.6
25(QA)
0.257;-1249.4
(26)(6A)
0.233;-1082.5
2(69A)
0.270;-1290.6
2J(6A)
0.294;-1249.4
(26)(7A)
0.243;-1196.9
9A(26)
0.258;-1290.6
A(26Q)
0.262;-1228.8
2A(67)
0.197;-1331.9
2A(69)
0.287;-1290.6
2A(6J)
0.321;-1249.4
2A(6K)
0.294;-1208.1
(29)(7A)
0.304;-1135.0
2(7QA)
0.331;-1208.1
A(278)
0.220;-1290.6
(27)(JA)
0.319;-1093.8
KA(27)
0.266;-1187.5
2A(79)
0.328;-1270.0
2A(7J)
0.316;-1228.8
2A(7K)
0.292;-1187.5
(2T)(8A)
0.290;-1093.8
2(8KA)
0.243;-1166.9
A(28T)
0.280;-1228.8
(28)(KA)
0.314;-1031.9
28(TA)
0.332;-1228.8
28(QA)
0.278;-1187.5
(29)(9A)
0.317;-958.8
2(9QA)
0.235;-1166.9
A(29T)
0.214;-1208.1
(29)(KA)
0.311;-1011.2
29(JA)
0.236;-1187.5
29(KA)
0.342;-1146.2
2J(TA)
0.278;-1166.9
(2T)(JA)
0.264;-1031.9
KA(2T)
0.296;-1125.6
2A(TQ)
0.255;-1146.2
2(JQA)
0.282;-1125.6
A(2JQ)
0.272;-1125.6
2A(JQ)
0.241;-1125.6
2(QKA)
0.273;-1084.4
2Q(KA)
0.302;-1084.4
33(3A)
0.279;-1185.6
(36)(3A)
0.237;-1123.8
3(39A)
0.281;-1196.9
3J(3A)
0.256;-1155.6
(345A)
0.213;-1393.8
(349A)
0.299;-1311.2
(34KA)
0.265;-1228.8
46(3A)
0.268;-1373.1
(49)(3A)
0.253;-1176.2
4(3QA)
0.290;-1249.4
6(35A)
0.245;-1352.5
T(35A)
0.223;-1270.0
5(36A)
0.228;-1352.5
58(3A)
0.241;-1311.2
(5J)(3A)
0.335;-1114.4
6(36A)
0.323;-1196.9
T(36A)
0.258;-1249.4
6(37A)
0.261;-1311.2
69(3A)
0.269;-1270.0
(6Q)(3A)
0.284;-1073.1
(379A)
0.274;-1249.4
(37KA)
0.235;-1166.9
79(3A)
0.242;-1249.4
(7Q)(3A)
0.306;-1052.5
(38TA)
0.304;-1208.1
88(3A)
0.331;-1114.4
(8J)(3A)
0.285;-1052.5
9(39A)
0.339;-1073.1
K(39A)
0.321;-1125.6
9(3QA)
0.310;-1146.2
J(3TA)
0.228;-1146.2
TJ(3A)
0.281;-1146.2
(3JQA)
0.234;-1105.0
J(3KA)
0.298;-1084.4
(QK)(3A)
0.302;-928.7
33(5A)
0.268;-1279.4
337A
0.311;-1373.1
3A(3T)
0.309;-1176.2
33(KA)
0.281;-1114.4
3(46A)
0.223;-1373.1
38(4A)
0.221;-1331.9
(3J)(4A)
0.306;-1135.0
4A(34)
0.280;-1279.4
A(347)
0.252;-1352.5
(34)(TA)
0.319;-1155.6
QA(34)
0.287;-1249.4
345A
0.255;-1528.8
347A
0.254;-1487.5
349A
0.185;-1446.2
34JA
0.204;-1405.0
34KA
0.239;-1363.8
37(5A)
0.222;-1331.9
(3T)(5A)
0.305;-1135.0
3(5KA)
0.232;-1208.1
A(357)
0.204;-1331.9
(35)(TA)
0.283;-1135.0
QA(35)
0.218;-1228.8
356A
0.192;-1487.5
358A
0.217;-1446.2
35TA
0.222;-1405.0
35QA
0.273;-1363.8
(37)(6A)
0.287;-1176.2
3(6TA)
0.236;-1249.4
3Q(6A)
0.249;-1208.1
(36)(8A)
0.331;-1155.6
TA(36)
0.220;-1249.4
A(36K)
0.278;-1187.5
6A(38)
0.254;-1290.6
6A(3T)
0.212;-1249.4
6A(3Q)
0.294;-1208.1
37(7A)
0.287;-1155.6
(3T)(7A)
0.324;-1093.8
3(7KA)
0.264;-1166.9
A(379)
0.212;-1249.4
(37)(QA)
0.296;-1052.5
7A(38)
0.318;-1270.0
7A(3T)
0.233;-1228.8
7A(3Q)
0.283;-1187.5
38(8A)
0.296;-1114.4
(3J)(8A)
0.323;-1052.5
8A(38)
0.304;-1114.4
A(38J)
0.298;-1187.5
388A
0.275;-1249.4
38TA
0.215;-1343.1
38QA
0.213;-1301.9
(3T)(9A)
0.386;-1052.5
3(9KA)
0.285;-1125.6
A(39J)
0.298;-1166.9
399A
0.259;-1208.1
39JA
0.250;-1301.9
39KA
0.260;-1260.6
3Q(TA)
0.283;-1125.6
(3T)(QA)
0.326;-990.6
TA(3J)
0.269;-1146.2
TA(3K)
0.281;-1105.0
3(JKA)
0.293;-1084.4
A(3JK)
0.289;-1084.4
JA(3K)
0.252;-1084.4
QA(3Q)
0.283;-949.4
3QKA
0.285;-1198.8
45(4A)
0.304;-1238.1
(48)(4A)
0.289;-1041.2
4(4JA)
0.270;-1114.4
4K(4A)
0.341;-1073.1
(459A)
0.265;-1270.0
(45KA)
0.316;-1187.5
57(4A)
0.273;-1311.2
(5T)(4A)
0.282;-1114.4
5(4KA)
0.261;-1187.5
(469A)
0.246;-1249.4
(46KA)
0.297;-1166.9
68(4A)
0.252;-1270.0
(6J)(4A)
0.289;-1073.1
7(47A)
0.292;-1135.0
J(47A)
0.288;-1187.5
78(4A)
0.268;-1249.4
(7J)(4A)
0.281;-1052.5
8(48A)
0.257;-1093.8
Q(48A)
0.287;-1146.2
(8T)(4A)
0.229;-1052.5
8(4KA)
0.315;-1125.6
(49QA)
0.301;-1125.6
9(4JA)
0.264;-1146.2
9K(4A)
0.323;-1105.0
TT(4A)
0.310;-1011.2
(TK)(4A)
0.277;-949.4
J(4QA)
0.341;-1084.4
K(4QA)
0.276;-1043.1
44(5A)
0.250;-1238.1
447A
0.302;-1331.9
4A(4T)
0.291;-1135.0
44(KA)
0.275;-1073.1
4(57A)
0.278;-1311.2
49(5A)
0.212;-1270.0
(4Q)(5A)
0.267;-1073.1
6A(45)
0.240;-1331.9
A(459)
0.297;-1270.0
(45)(QA)
0.273;-1073.1
5A(46)
0.238;-1331.9
5A(48)
0.207;-1290.6
5A(4T)
0.339;-1249.4
5A(4Q)
0.221;-1208.1
46(6A)
0.276;-1176.2
(49)(6A)
0.328;-1114.4
4(6QA)
0.341;-1187.5
A(467)
0.220;-1290.6
(46)(TA)
0.228;-1093.8
QA(46)
0.259;-1187.5
467A
0.260;-1425.6
469A
0.307;-1384.4
46JA
0.231;-1343.1
46KA
0.284;-1301.9
49(7A)
0.260;-1228.8
(4Q)(7A)
0.324;-1031.9
8A(47)
0.264;-1249.4
A(47J)
0.236;-1187.5
477A
0.303;-1270.0
479A
0.242;-1363.8
47JA
0.265;-1322.5
47KA
0.310;-1281.2
4T(8A)
0.335;-1187.5
(4K)(8A)
0.253;-990.6
TA(48)
0.278;-1187.5
A(48K)
0.288;-1125.6
8A(4T)
0.236;-1187.5
8A(4Q)
0.288;-1146.2
49(9A)
0.257;-1052.5
(4Q)(9A)
0.270;-990.6
TA(49)
0.338;-1166.9
A(49K)
0.274;-1105.0
9A(4J)
0.279;-1146.2
9A(4K)
0.319;-1105.0
4(TQA)
0.284;-1105.0
A(4TJ)
0.302;-1125.6
4TTA
0.298;-1146.2
4TQA
0.272;-1240.0
(4Q)(JA)
0.343;-949.4
QA(4J)
0.246;-1084.4
4JQA
0.239;-1219.4
(4K)(QA)
0.325;-908.1
QA(4K)
0.316;-1043.1
5(56A)
0.251;-1176.2
58(5A)
0.326;-1135.0
(5J)(5A)
0.268;-938.1
6(56A)
0.280;-1155.6
T(56A)
0.309;-1208.1
6(57A)
0.221;-1270.0
69(5A)
0.228;-1228.8
(6Q)(5A)
0.365;-1031.9
(579A)
0.316;-1208.1
(57KA)
0.311;-1125.6
79(5A)
0.325;-1208.1
(7Q)(5A)
0.350;-1011.2
(58TA)
0.287;-1166.9
88(5A)
0.272;-1073.1
(8J)(5A)
0.273;-1011.2
9(59A)
0.276;-1031.9
K(59A)
0.291;-1084.4
9(5QA)
0.295;-1105.0
J(5TA)
0.269;-1105.0
TJ(5A)
0.254;-1105.0
(5JQA)
0.302;-1063.8
J(5KA)
0.319;-1043.1
(QK)(5A)
0.343;-887.5
55(7A)
0.360;-1155.6
559A
0.284;-1249.4
5A(5Q)
0.353;-1052.5
(57)(6A)
0.248;-1135.0
5(6TA)
0.268;-1208.1
5Q(6A)
0.319;-1166.9
(56)(8A)
0.283;-1114.4
TA(56)
0.306;-1208.1
A(56K)
0.285;-1146.2
6A(58)
0.238;-1249.4
6A(5T)
0.311;-1208.1
6A(5Q)
0.263;-1166.9
57(7A)
0.284;-1114.4
(5T)(7A)
0.285;-1052.5
5(7KA)
0.255;-1125.6
A(579)
0.240;-1208.1
(57)(QA)
0.296;-1011.2
7A(58)
0.249;-1228.8
7A(5T)
0.307;-1187.5
7A(5Q)
0.244;-1146.2
58(8A)
0.349;-1073.1
(5J)(8A)
0.305;-1011.2
8A(58)
0.290;-1073.1
A(58J)
0.328;-1146.2
588A
0.252;-1208.1
58TA
0.244;-1301.9
58QA
0.269;-1260.6
(5T)(9A)
0.251;-1011.2
5(9KA)
0.302;-1084.4
A(59J)
0.262;-1125.6
599A
0.254;-1166.9
59JA
0.207;-1260.6
59KA
0.287;-1219.4
5Q(TA)
0.346;-1084.4
(5T)(QA)
0.343;-949.4
TA(5J)
0.362;-1105.0
TA(5K)
0.277;-1063.8
5(JKA)
0.289;-1043.1
A(5JK)
0.298;-1043.1
JA(5K)
0.379;-1043.1
QA(5Q)
0.368;-908.1
5QKA
0.274;-1157.5
67(6A)
0.292;-1114.4
(6T)(6A)
0.338;-917.5
6(6KA)
0.328;-990.6
(67TA)
0.258;-1166.9
77(6A)
0.322;-1093.8
(7T)(6A)
0.257;-1031.9
7(6KA)
0.286;-1105.0
(68JA)
0.301;-1125.6
(89)(6A)
0.298;-1031.9
8(6QA)
0.246;-1105.0
T(69A)
0.281;-1125.6
9(6TA)
0.293;-1125.6
9Q(6A)
0.318;-1084.4
Q(6TA)
0.300;-1063.8
(TQ)(6A)
0.308;-928.7
(6JKA)
0.317;-1022.5
JK(6A)
0.362;-1022.5
K(6KA)
0.278;-846.3
668A
0.319;-1228.8
6A(6J)
0.329;-1031.9
(67)(7A)
0.262;-958.8
6(7TA)
0.334;-1166.9
6Q(7A)
0.295;-1125.6
(67)(9A)
0.347;-1052.5
JA(67)
0.276;-1146.2
67(8A)
0.276;-1208.1
67(TA)
0.293;-1166.9
67(QA)
0.294;-1125.6
(68)(8A)
0.305;-917.5
6(8JA)
0.257;-1125.6
6K(8A)
0.270;-1084.4
(68)(JA)
0.260;-990.6
KA(68)
0.307;-1084.4
6A(8T)
0.270;-1146.2
6A(8Q)
0.307;-1105.0
6(9TA)
0.321;-1125.6
6Q(9A)
0.278;-1084.4
(69)(JA)
0.327;-970.0
KA(69)
0.309;-1063.8
6A(9J)
0.291;-1105.0
6A(9K)
0.282;-1063.8
(6Q)(TA)
0.265;-928.7
JA(6T)
0.250;-1084.4
6T(JA)
0.257;-1084.4
6T(KA)
0.293;-1043.1
6Q(JA)
0.330;-1043.1
(6J)(KA)
0.355;-887.5
6J(KA)
0.332;-1022.5
6K(QA)
0.344;-1001.9
6A(QK)
0.354;-1001.9
(78)(7A)
0.368;-917.5
7(7JA)
0.293;-990.6
7K(7A)
0.270;-949.4
(78QA)
0.340;-1084.4
8(7TA)
0.267;-1125.6
8Q(7A)
0.273;-1084.4
J(79A)
0.281;-1084.4
9T(7A)
0.333;-1105.0
(9K)(7A)
0.281;-908.1
K(7TA)
0.270;-1022.5
T(7KA)
0.351;-1022.5
JJ(7A)
0.388;-908.1
(7QKA)
0.341;-981.3
777A
0.234;-1073.1
7A(7T)
0.312;-1011.2
77(KA)
0.332;-949.4
7(8TA)
0.257;-1125.6
7Q(8A)
0.267;-1084.4
(78)(TA)
0.246;-990.6
QA(78)
0.312;-1084.4
789A
0.238;-1281.2
78JA
0.299;-1240.0
78KA
0.310;-1198.8
7J(9A)
0.291;-1084.4
(79)(TA)
0.308;-970.0
QA(79)
0.330;-1063.8
79TA
0.256;-1240.0
79QA
0.254;-1198.8
(7J)(TA)
0.333;-928.7
TA(7T)
0.311;-949.4
A(7TK)
0.284;-1022.5
TA(7Q)
0.304;-1043.1
7J(JA)
0.259;-908.1
(7J)(QA)
0.287;-887.5
JA(7Q)
0.289;-1022.5
7Q(QA)
0.360;-866.9
7QQA
0.296;-1001.9
7KKA
0.254;-960.6
8(8JA)
0.365;-949.4
8K(8A)
0.318;-908.1
(89KA)
0.263;-1022.5
9J(8A)
0.301;-1063.8
(8TJA)
0.341;-1043.1
(TJ)(8A)
0.356;-908.1
J(8JA)
0.348;-887.5
JQ(8A)
0.309;-1001.9
Q(8KA)
0.368;-960.6
889A
0.249;-1125.6
8A(8Q)
0.398;-928.7
(8T)(9A)
0.337;-949.4
8(9KA)
0.283;-1022.5
A(89J)
0.316;-1063.8
899A
0.232;-1105.0
89JA
0.263;-1198.8
89KA
0.310;-1157.5
8Q(TA)
0.338;-1022.5
(8T)(QA)
0.331;-887.5
TA(8J)
0.272;-1043.1
TA(8K)
0.285;-1001.9
8(JKA)
0.338;-981.3
A(8JK)
0.334;-981.3
JA(8K)
0.336;-981.3
QA(8Q)
0.335;-846.3
8QKA
0.313;-1095.6
9T(9A)
0.390;-928.7
(9K)(9A)
0.282;-731.9
K(9TA)
0.271;-981.3
T(9KA)
0.312;-981.3
JJ(9A)
0.353;-866.9
(9QKA)
0.342;-940.0
999A
0.327;-949.4
9A(9Q)
0.311;-887.5
(9J)(TA)
0.360;-887.5
TA(9T)
0.270;-908.1
A(9TK)
0.283;-981.3
TA(9Q)
0.347;-1001.9
9J(JA)
0.321;-866.9
(9J)(QA)
0.378;-846.2
JA(9Q)
0.323;-981.3
9Q(QA)
0.371;-825.6
9QQA
0.340;-960.6
9KKA
0.292;-919.4
T(TKA)
0.358;-825.6
JJ(TA)
0.405;-846.3
(TQKA)
0.310;-919.4
TTTA
0.301;-887.5
TA(TK)
0.340;-825.6
(TK)(JA)
0.411;-805.0
KA(TJ)
0.278;-940.0
TA(JK)
0.336;-940.0
(TQ)(KA)
0.332;-784.4
(TK)(KA)
0.345;-628.7
J(JKA)
0.378;-784.4
(QK)(JA)
0.349;-763.7
JJ(KA)
0.339;-784.4
QA(JQ)
0.417;-784.4
JQKA
0.253;-1033.8
QK(QA)
0.369;-743.1
QK(KA)
0.421;-722.5
22(24)
0.246;-1453.7
22(28)
0.254;-1371.2
22(2Q)
0.290;-1288.7
24(23)
0.207;-1568.1
(23)(27)
0.252;-1371.2
2(23T)
0.228;-1444.4
2Q(23)
0.298;-1403.1
23(25)
0.191;-1547.5
2237
0.251;-1641.2
22(3T)
0.263;-1444.4
23(2K)
0.278;-1382.5
2(246)
0.221;-1506.2
28(24)
0.196;-1465.0
(24)(2J)
0.263;-1268.1
2244
0.278;-1547.5
22(47)
0.199;-1485.6
24(2T)
0.267;-1423.8
224Q
0.231;-1517.5
26(25)
0.184;-1485.6
(25)(29)
0.241;-1288.7
2(25Q)
0.305;-1361.9
22(56)
0.251;-1485.6
25(29)
0.256;-1423.8
225J
0.186;-1517.5
26(26)
0.257;-1330.0
(26)(29)
0.256;-1268.1
2(26Q)
0.248;-1341.2
22(67)
0.194;-1444.4
26(2T)
0.261;-1382.5
226Q
0.185;-1476.2
28(27)
0.261;-1403.1
(27)(2J)
0.301;-1206.2
2277
0.249;-1423.8
22(7T)
0.229;-1361.9
27(2K)
0.240;-1300.0
2(28T)
0.239;-1341.2
2Q(28)
0.209;-1300.0
28(2T)
0.195;-1341.2
228Q
0.228;-1435.0
2T(29)
0.250;-1320.6
(29)(2K)
0.270;-1123.8
229J
0.233;-1435.0
2T(2T)
0.303;-1165.0
(2T)(2K)
0.293;-1103.1
22TQ
0.235;-1393.8
2Q(2J)
0.290;-1238.1
2J(2K)
0.242;-1217.5
22QQ
0.324;-1217.5
3(234)
0.215;-1547.5
36(23)
0.224;-1506.2
(23)(39)
0.271;-1309.4
3(23Q)
0.195;-1382.5
5(234)
0.169;-1641.2
9(234)
0.204;-1558.7
K(234)
0.267;-1476.2
4(237)
0.188;-1600.0
49(23)
0.194;-1558.7
(23)(4Q)
0.213;-1361.9
(2357)
0.212;-1579.4
(235J)
0.210;-1496.9
(23)(56)
0.239;-1465.0
5(239)
0.181;-1538.1
5J(23)
0.186;-1496.9
(2367)
0.190;-1558.7
(236J)
0.172;-1476.2
(23)(67)
0.183;-1423.8
6(23T)
0.188;-1496.9
6Q(23)
0.175;-1455.6
9(237)
0.256;-1496.9
K(237)
0.266;-1414.4
7(23T)
0.285;-1476.2
7Q(23)
0.197;-1435.0
T(238)
0.260;-1455.6
8(239)
0.275;-1476.2
8J(23)
0.212;-1435.0
(239T)
0.219;-1435.0
99(23)
0.277;-1320.6
(23)(9Q)
0.257;-1258.8
(23TQ)
0.268;-1373.1
T(23Q)
0.213;-1373.1
Q(23J)
0.227;-1352.5
(23)(JK)
0.262;-1196.9
QK(23)
0.225;-1311.2
23(35)
0.200;-1526.9
33(28)
0.231;-1465.0
233T
0.207;-1558.7
23(3K)
0.214;-1361.9
(24)(36)
0.177;-1485.6
3(249)
0.189;-1558.7
3J(24)
0.243;-1517.5
(34)(25)
0.188;-1506.2
27(34)
0.224;-1600.0
2(34T)
0.249;-1538.1
(34)(2K)
0.266;-1341.2
34(26)
0.192;-1620.6
34(28)
0.192;-1579.4
34(2T)
0.275;-1538.1
34(2Q)
0.224;-1496.9
(25)(35)
0.298;-1350.6
3(258)
0.223;-1558.7
3T(25)
0.196;-1517.5
(25)(3K)
0.311;-1320.6
27(35)
0.178;-1579.4
2(35T)
0.239;-1517.5
(35)(2K)
0.228;-1320.6
35(27)
0.174;-1579.4
35(29)
0.251;-1538.1
35(2J)
0.203;-1496.9
35(2K)
0.291;-1455.6
37(26)
0.222;-1558.7
(26)(3T)
0.218;-1361.9
3(26K)
0.263;-1435.0
2(368)
0.238;-1538.1
(36)(2J)
0.224;-1341.2
2K(36)
0.273;-1435.0
23(68)
0.185;-1538.1
23(6T)
0.268;-1496.9
23(6Q)
0.279;-1455.6
3(278)
0.253;-1517.5
3T(27)
0.246;-1476.2
(27)(3K)
0.235;-1279.4
29(37)
0.212;-1496.9
2(37Q)
0.272;-1435.0
23(78)
0.229;-1517.5
23(7T)
0.251;-1476.2
23(7Q)
0.239;-1435.0
3(289)
0.247;-1476.2
3J(28)
0.190;-1435.0
(38)(29)
0.239;-1341.2
2J(38)
0.195;-1435.0
38(29)
0.191;-1476.2
38(2J)
0.201;-1435.0
38(2K)
0.252;-1393.8
3T(29)
0.287;-1435.0
(29)(3K)
0.293;-1238.1
2J(39)
0.271;-1414.4
39(2T)
0.271;-1435.0
39(2Q)
0.278;-1393.8
(2T)(3T)
0.264;-1144.4
3(2TK)
0.238;-1352.5
2(3TQ)
0.224;-1373.1
23(TJ)
0.248;-1393.8
23(TK)
0.303;-1352.5
(2J)(3K)
0.247;-1196.9
2K(3J)
0.259;-1331.9
23(JK)
0.252;-1331.9
(3Q)(2K)
0.319;-1176.2
(2K)(3K)
0.360;-1020.6
4(246)
0.217;-1465.0
48(24)
0.262;-1423.8
(24)(4J)
0.289;-1226.9
5(245)
0.197;-1465.0
9(245)
0.232;-1517.5
K(245)
0.199;-1435.0
5(248)
0.260;-1538.1
5T(24)
0.215;-1496.9
(24)(5K)
0.303;-1300.0
9(246)
0.206;-1496.9
K(246)
0.262;-1414.4
6(249)
0.258;-1496.9
6J(24)
0.222;-1455.6
(2478)
0.225;-1496.9
(247Q)
0.248;-1414.4
7(249)
0.174;-1476.2
7J(24)
0.263;-1435.0
(2489)
0.222;-1455.6
(248K)
0.242;-1373.1
8T(24)
0.213;-1435.0
(24)(8K)
0.323;-1238.1
Q(249)
0.233;-1373.1
(24)(9J)
0.256;-1258.8
T(24T)
0.230;-1258.8
T(24J)
0.243;-1373.1
TK(24)
0.231;-1331.9
(24)(JQ)
0.301;-1196.9
QQ(24)
0.310;-1176.2
24(45)
0.208;-1485.6
44(28)
0.218;-1423.8
244T
0.184;-1517.5
24(4K)
0.250;-1320.6
(25)(47)
0.225;-1423.8
4(25T)
0.181;-1496.9
4Q(25)
0.263;-1455.6
(45)(27)
0.230;-1423.8
29(45)
0.179;-1517.5
2(45Q)
0.236;-1455.6
24(56)
0.220;-1579.4
24(58)
0.163;-1538.1
24(5T)
0.240;-1496.9
24(5Q)
0.282;-1455.6
4(267)
0.229;-1538.1
49(26)
0.220;-1496.9
(26)(4Q)
0.246;-1300.0
27(46)
0.203;-1538.1
2(46T)
0.191;-1476.2
(46)(2K)
0.239;-1279.4
46(28)
0.197;-1517.5
46(2T)
0.218;-1476.2
46(2Q)
0.228;-1435.0
(27)(47)
0.282;-1247.5
4(27T)
0.222;-1455.6
4Q(27)
0.237;-1414.4
(47)(29)
0.258;-1341.2
2J(47)
0.233;-1435.0
47(28)
0.288;-1496.9
47(2T)
0.190;-1455.6
47(2Q)
0.254;-1414.4
(28)(48)
0.247;-1206.2
4(28J)
0.215;-1414.4
4K(28)
0.254;-1373.1
(48)(2J)
0.241;-1279.4
2K(48)
0.201;-1373.1
24(8T)
0.202;-1435.0
24(8Q)
0.248;-1393.8
4(29T)
0.242;-1414.4
4Q(29)
0.206;-1373.1
(49)(2J)
0.246;-1258.8
2K(49)
0.252;-1352.5
24(9J)
0.252;-1393.8
24(9K)
0.230;-1352.5
(2T)(4Q)
0.271;-1217.5
2J(4T)
0.204;-1373.1
4T(2J)
0.253;-1373.1
4T(2K)
0.231;-1331.9
4Q(2J)
0.223;-1331.9
(4J)(2K)
0.222;-1176.2
4J(2K)
0.259;-1311.2
4K(2Q)
0.241;-1290.6
24(QK)
0.286;-1290.6
(25)(56)
0.307;-1288.7
5(259)
0.248;-1361.9
5J(25)
0.251;-1320.6
(2567)
0.236;-1517.5
(256J)
0.233;-1435.0
(25)(67)
0.222;-1382.5
6(25T)
0.230;-1455.6
6Q(25)
0.224;-1414.4
9(257)
0.233;-1455.6
K(257)
0.262;-1373.1
7(25T)
0.224;-1435.0
7Q(25)
0.214;-1393.8
T(258)
0.253;-1414.4
8(259)
0.276;-1435.0
8J(25)
0.281;-1393.8
(259T)
0.209;-1393.8
99(25)
0.287;-1279.4
(25)(9Q)
0.310;-1217.5
(25TQ)
0.238;-1331.9
T(25Q)
0.200;-1331.9
Q(25J)
0.204;-1311.2
(25)(JK)
0.250;-1155.6
QK(25)
0.216;-1270.0
25(57)
0.312;-1403.1
55(2T)
0.234;-1341.2
255Q
0.196;-1435.0
57(26)
0.257;-1517.5
(26)(5T)
0.247;-1320.6
5(26K)
0.286;-1393.8
2(568)
0.242;-1496.9
(56)(2J)
0.253;-1300.0
2K(56)
0.235;-1393.8
25(68)
0.212;-1496.9
25(6T)
0.220;-1455.6
25(6Q)
0.241;-1414.4
5(278)
0.205;-1476.2
5T(27)
0.262;-1435.0
(27)(5K)
0.293;-1238.1
29(57)
0.241;-1455.6
2(57Q)
0.260;-1393.8
25(78)
0.226;-1476.2
25(7T)
0.244;-1435.0
25(7Q)
0.257;-1393.8
5(289)
0.287;-1435.0
5J(28)
0.247;-1393.8
(58)(29)
0.282;-1300.0
2J(58)
0.206;-1393.8
58(29)
0.260;-1435.0
58(2J)
0.190;-1393.8
58(2K)
0.251;-1352.5
5T(29)
0.238;-1393.8
(29)(5K)
0.230;-1196.9
2J(59)
0.308;-1373.1
59(2T)
0.301;-1393.8
59(2Q)
0.262;-1352.5
(2T)(5T)
0.252;-1103.1
5(2TK)
0.204;-1311.2
2(5TQ)
0.325;-1331.9
25(TJ)
0.217;-1352.5
25(TK)
0.328;-1311.2
(2J)(5K)
0.305;-1155.6
2K(5J)
0.285;-1290.6
25(JK)
0.252;-1290.6
(5Q)(2K)
0.265;-1135.0
(2K)(5K)
0.281;-979.4
6(268)
0.225;-1341.2
6T(26)
0.272;-1300.0
(26)(6K)
0.270;-1103.1
T(267)
0.239;-1414.4
7(268)
0.190;-1455.6
7T(26)
0.231;-1414.4
(26)(7K)
0.223;-1217.5
J(268)
0.263;-1373.1
89(26)
0.233;-1414.4
(26)(8Q)
0.269;-1217.5
(269J)
0.235;-1352.5
(26)(9T)
0.271;-1238.1
9(26K)
0.269;-1311.2
(26TK)
0.318;-1290.6
TQ(26)
0.306;-1311.2
K(26J)
0.295;-1270.0
Q(26Q)
0.261;-1135.0
KK(26)
0.309;-1093.8
66(29)
0.208;-1320.6
266J
0.266;-1414.4
67(27)
0.253;-1341.2
(27)(6T)
0.275;-1279.4
6(27K)
0.242;-1352.5
2(679)
0.211;-1435.0
(67)(2Q)
0.299;-1238.1
27(68)
0.240;-1455.6
27(6T)
0.225;-1414.4
27(6Q)
0.246;-1373.1
68(28)
0.319;-1300.0
(28)(6J)
0.257;-1238.1
28(68)
0.231;-1300.0
2(68J)
0.289;-1373.1
2688
0.235;-1435.0
268T
0.225;-1528.8
268Q
0.290;-1487.5
(29)(6T)
0.291;-1238.1
6(29K)
0.261;-1311.2
2(69J)
0.229;-1352.5
2699
0.214;-1393.8
269J
0.241;-1487.5
269K
0.225;-1446.2
6Q(2T)
0.269;-1311.2
(6T)(2Q)
0.235;-1176.2
2T(6J)
0.277;-1331.9
2T(6K)
0.238;-1290.6
6(2JK)
0.234;-1270.0
2(6JK)
0.271;-1270.0
2J(6K)
0.324;-1270.0
2Q(6Q)
0.315;-1135.0
26QK
0.207;-1384.4
78(27)
0.296;-1300.0
(27)(7J)
0.272;-1103.1
8(278)
0.268;-1279.4
Q(278)
0.315;-1331.9
(27)(8T)
0.226;-1238.1
8(27K)
0.332;-1311.2
(279Q)
0.248;-1311.2
9(27J)
0.254;-1331.9
9K(27)
0.292;-1290.6
TT(27)
0.289;-1196.9
(27)(TK)
0.311;-1135.0
J(27Q)
0.268;-1270.0
K(27Q)
0.277;-1228.8
77(28)
0.262;-1300.0
277T
0.260;-1393.8
27(7K)
0.232;-1196.9
(28)(7T)
0.265;-1238.1
7(28K)
0.285;-1311.2
2(78T)
0.236;-1373.1
(78)(2K)
0.347;-1176.2
78(2T)
0.246;-1373.1
78(2Q)
0.276;-1331.9
(29)(79)
0.336;-1103.1
7(29Q)
0.322;-1311.2
2(79T)
0.225;-1352.5
(79)(2K)
0.290;-1155.6
79(2J)
0.267;-1331.9
79(2K)
0.289;-1290.6
7J(2T)
0.236;-1311.2
(7T)(2J)
0.282;-1176.2
2K(7T)
0.248;-1270.0
27(TQ)
0.230;-1290.6
7(2JQ)
0.271;-1270.0
2(7JQ)
0.267;-1270.0
27(JQ)
0.254;-1270.0
7(2QK)
0.318;-1228.8
7Q(2K)
0.261;-1228.8
88(28)
0.310;-1123.8
(28)(8J)
0.336;-1061.9
9(289)
0.262;-1217.5
K(289)
0.300;-1270.0
9(28Q)
0.236;-1290.6
J(28T)
0.233;-1290.6
TJ(28)
0.263;-1290.6
(28JQ)
0.270;-1249.4
J(28K)
0.314;-1228.8
(28)(QK)
0.272;-1073.1
88(2T)
0.304;-1217.5
288Q
0.230;-1311.2
8T(29)
0.285;-1331.9
(29)(8K)
0.295;-1135.0
2J(89)
0.252;-1311.2
89(2T)
0.324;-1331.9
89(2Q)
0.241;-1290.6
(2T)(8T)
0.313;-1041.2
8(2TK)
0.262;-1249.4
2(8TQ)
0.286;-1270.0
28(TJ)
0.256;-1290.6
28(TK)
0.270;-1249.4
(2J)(8K)
0.258;-1093.8
2K(8J)
0.283;-1228.8
28(JK)
0.274;-1228.8
(8Q)(2K)
0.289;-1073.1
(2K)(8K)
0.340;-917.5
9(29J)
0.260;-1155.6
9K(29)
0.237;-1114.4
TT(29)
0.275;-1155.6
(29)(TK)
0.299;-1093.8
J(29Q)
0.327;-1228.8
K(29Q)
0.269;-1187.5
99(2T)
0.240;-1176.2
299Q
0.209;-1270.0
9J(2T)
0.274;-1270.0
(9T)(2J)
0.289;-1135.0
2K(9T)
0.338;-1228.8
29(TQ)
0.301;-1249.4
9(2JQ)
0.256;-1228.8
2(9JQ)
0.305;-1228.8
29(JQ)
0.284;-1228.8
9(2QK)
0.288;-1187.5
9Q(2K)
0.253;-1187.5
TT(2T)
0.381;-1000.0
(2T)(TK)
0.367;-938.1
J(2TQ)
0.282;-1208.1
K(2TQ)
0.238;-1166.9
TT(2J)
0.252;-1114.4
2TTK
0.256;-1208.1
TK(2J)
0.307;-1187.5
2TJJ
0.290;-1228.8
2TJK
0.261;-1322.5
2(TQK)
0.236;-1166.9
TK(2K)
0.287;-1011.2
(2J)(JK)
0.334;-896.9
QK(2J)
0.343;-1146.2
2J(JK)
0.308;-1031.9
(JQ)(2K)
0.278;-1011.2
(2K)(JK)
0.306;-855.6
K(2QK)
0.310;-970.0
2K(QK)
0.333;-970.0
3335
0.207;-1506.2
3339
0.183;-1423.8
333K
0.233;-1341.2
36(34)
0.207;-1465.0
(34)(39)
0.254;-1268.1
3(34Q)
0.322;-1341.2
33(45)
0.236;-1485.6
34(38)
0.198;-1423.8
334T
0.192;-1517.5
33(4K)
0.318;-1320.6
(35)(37)
0.229;-1288.7
3(35T)
0.269;-1361.9
3Q(35)
0.290;-1320.6
35(37)
0.236;-1423.8
3359
0.180;-1517.5
33(5Q)
0.232;-1320.6
(36)(37)
0.237;-1268.1
3(36T)
0.310;-1341.2
3Q(36)
0.232;-1300.0
36(38)
0.217;-1382.5
336T
0.182;-1476.2
33(6K)
0.253;-1279.4
(37)(39)
0.264;-1206.2
3(37Q)
0.284;-1279.4
33(78)
0.220;-1361.9
37(3J)
0.250;-1300.0
337K
0.184;-1393.8
3T(38)
0.243;-1300.0
(38)(3K)
0.253;-1103.1
338T
0.274;-1435.0
33(8K)
0.271;-1238.1
(39)(3J)
0.296;-1123.8
3399
0.232;-1300.0
33(9Q)
0.290;-1238.1
(3T)(3J)
0.294;-1103.1
33TT
0.279;-1258.8
33(TK)
0.275;-1196.9
(3J)(3K)
0.293;-1041.2
33JK
0.267;-1311.2
33(QK)
0.228;-1155.6
45(34)
0.247;-1465.0
(34)(48)
0.265;-1268.1
4(34J)
0.236;-1341.2
4K(34)
0.294;-1300.0
(3459)
0.288;-1496.9
(345K)
0.224;-1414.4
57(34)
0.218;-1538.1
(34)(5T)
0.207;-1341.2
5(34K)
0.252;-1414.4
(3469)
0.236;-1476.2
(346K)
0.255;-1393.8
68(34)
0.253;-1496.9
(34)(6J)
0.277;-1300.0
7(347)
0.203;-1361.9
J(347)
0.226;-1414.4
78(34)
0.244;-1476.2
(34)(7J)
0.281;-1279.4
8(348)
0.243;-1320.6
Q(348)
0.231;-1373.1
(34)(8T)
0.243;-1279.4
8(34K)
0.223;-1352.5
(349Q)
0.309;-1352.5
9(34J)
0.282;-1373.1
9K(34)
0.266;-1331.9
TT(34)
0.223;-1238.1
(34)(TK)
0.305;-1176.2
J(34Q)
0.256;-1311.2
K(34Q)
0.323;-1270.0
44(35)
0.267;-1465.0
3447
0.250;-1558.7
34(4T)
0.279;-1361.9
44(3K)
0.265;-1300.0
4(357)
0.216;-1538.1
49(35)
0.213;-1496.9
(35)(4Q)
0.291;-1300.0
36(45)
0.196;-1558.7
3(459)
0.254;-1496.9
(45)(3Q)
0.226;-1300.0
35(46)
0.280;-1558.7
35(48)
0.212;-1517.5
35(4T)
0.248;-1476.2
35(4Q)
0.231;-1435.0
46(36)
0.244;-1403.1
(36)(49)
0.251;-1341.2
4(36Q)
0.230;-1414.4
3(467)
0.245;-1517.5
(46)(3T)
0.247;-1320.6
3Q(46)
0.212;-1414.4
3467
0.204;-1652.5
3469
0.203;-1611.2
346J
0.197;-1570.0
346K
0.220;-1528.8
49(37)
0.238;-1455.6
(37)(4Q)
0.276;-1258.8
38(47)
0.239;-1476.2
3(47J)
0.222;-1414.4
3477
0.228;-1496.9
3479
0.214;-1590.6
347J
0.241;-1549.4
347K
0.204;-1508.1
4T(38)
0.233;-1414.4
(38)(4K)
0.226;-1217.5
3T(48)
0.276;-1414.4
3(48K)
0.218;-1352.5
38(4T)
0.206;-1414.4
38(4Q)
0.206;-1373.1
49(39)
0.250;-1279.4
(39)(4Q)
0.273;-1217.5
3T(49)
0.213;-1393.8
3(49K)
0.220;-1331.9
39(4J)
0.241;-1373.1
39(4K)
0.284;-1331.9
4(3TQ)
0.260;-1331.9
3(4TJ)
0.224;-1352.5
34TT
0.239;-1373.1
34TQ
0.230;-1466.9
(3J)(4Q)
0.301;-1176.2
3Q(4J)
0.263;-1311.2
34JQ
0.267;-1446.2
(3Q)(4K)
0.274;-1135.0
3Q(4K)
0.290;-1270.0
5(356)
0.227;-1403.1
58(35)
0.219;-1361.9
(35)(5J)
0.269;-1165.0
6(356)
0.206;-1382.5
T(356)
0.279;-1435.0
6(357)
0.233;-1496.9
69(35)
0.233;-1455.6
(35)(6Q)
0.298;-1258.8
(3579)
0.252;-1435.0
(357K)
0.240;-1352.5
79(35)
0.239;-1435.0
(35)(7Q)
0.293;-1238.1
(358T)
0.280;-1393.8
88(35)
0.287;-1300.0
(35)(8J)
0.235;-1238.1
9(359)
0.289;-1258.8
K(359)
0.257;-1311.2
9(35Q)
0.271;-1331.9
J(35T)
0.291;-1331.9
TJ(35)
0.232;-1331.9
(35JQ)
0.314;-1290.6
J(35K)
0.250;-1270.0
(35)(QK)
0.337;-1114.4
55(37)
0.279;-1382.5
3559
0.224;-1476.2
35(5Q)
0.240;-1279.4
(36)(57)
0.294;-1361.9
5(36T)
0.259;-1435.0
5Q(36)
0.226;-1393.8
(56)(38)
0.245;-1341.2
3T(56)
0.215;-1435.0
3(56K)
0.243;-1373.1
36(58)
0.207;-1476.2
36(5T)
0.233;-1435.0
36(5Q)
0.232;-1393.8
57(37)
0.285;-1341.2
(37)(5T)
0.258;-1279.4
5(37K)
0.270;-1352.5
3(579)
0.223;-1435.0
(57)(3Q)
0.281;-1238.1
37(58)
0.220;-1455.6
37(5T)
0.184;-1414.4
37(5Q)
0.227;-1373.1
58(38)
0.253;-1300.0
(38)(5J)
0.307;-1238.1
38(58)
0.278;-1300.0
3(58J)
0.238;-1373.1
3588
0.214;-1435.0
358T
0.231;-1528.8
358Q
0.199;-1487.5
(39)(5T)
0.335;-1238.1
5(39K)
0.233;-1311.2
3(59J)
0.187;-1352.5
3599
0.180;-1393.8
359J
0.206;-1487.5
359K
0.222;-1446.2
5Q(3T)
0.236;-1311.2
(5T)(3Q)
0.360;-1176.2
3T(5J)
0.205;-1331.9
3T(5K)
0.236;-1290.6
5(3JK)
0.274;-1270.0
3(5JK)
0.294;-1270.0
3J(5K)
0.280;-1270.0
3Q(5Q)
0.273;-1135.0
35QK
0.295;-1384.4
67(36)
0.302;-1341.2
(36)(6T)
0.260;-1144.4
6(36K)
0.275;-1217.5
(367T)
0.252;-1393.8
77(36)
0.237;-1320.6
(36)(7T)
0.277;-1258.8
7(36K)
0.196;-1331.9
(368J)
0.209;-1352.5
(36)(89)
0.299;-1258.8
8(36Q)
0.282;-1331.9
T(369)
0.323;-1352.5
9(36T)
0.270;-1352.5
9Q(36)
0.196;-1311.2
Q(36T)
0.234;-1290.6
(36)(TQ)
0.246;-1155.6
(36JK)
0.252;-1249.4
JK(36)
0.252;-1249.4
K(36K)
0.290;-1073.1
3668
0.229;-1455.6
36(6J)
0.281;-1258.8
(37)(67)
0.296;-1185.6
6(37T)
0.190;-1393.8
6Q(37)
0.302;-1352.5
(67)(39)
0.223;-1279.4
3J(67)
0.220;-1373.1
67(38)
0.222;-1435.0
67(3T)
0.271;-1393.8
67(3Q)
0.192;-1352.5
(38)(68)
0.317;-1144.4
6(38J)
0.273;-1352.5
6K(38)
0.284;-1311.2
(68)(3J)
0.277;-1217.5
3K(68)
0.286;-1311.2
36(8T)
0.244;-1373.1
36(8Q)
0.224;-1331.9
6(39T)
0.229;-1352.5
6Q(39)
0.270;-1311.2
(69)(3J)
0.261;-1196.9
3K(69)
0.277;-1290.6
36(9J)
0.273;-1331.9
36(9K)
0.244;-1290.6
(3T)(6Q)
0.334;-1155.6
3J(6T)
0.234;-1311.2
6T(3J)
0.279;-1311.2
6T(3K)
0.300;-1270.0
6Q(3J)
0.201;-1270.0
(6J)(3K)
0.251;-1114.4
6J(3K)
0.244;-1249.4
6K(3Q)
0.251;-1228.8
36(QK)
0.225;-1228.8
(37)(78)
0.288;-1144.4
7(37J)
0.298;-1217.5
7K(37)
0.323;-1176.2
(378Q)
0.252;-1311.2
8(37T)
0.235;-1352.5
8Q(37)
0.259;-1311.2
J(379)
0.268;-1311.2
9T(37)
0.259;-1331.9
(37)(9K)
0.279;-1135.0
K(37T)
0.247;-1249.4
T(37K)
0.250;-1249.4
JJ(37)
0.290;-1135.0
(37QK)
0.285;-1208.1
3777
0.268;-1300.0
37(7T)
0.336;-1238.1
77(3K)
0.328;-1176.2
7(38T)
0.249;-1352.5
7Q(38)
0.249;-1311.2
(78)(3T)
0.342;-1217.5
3Q(78)
0.303;-1311.2
3789
0.199;-1508.1
378J
0.229;-1466.9
378K
0.293;-1425.6
7J(39)
0.293;-1311.2
(79)(3T)
0.247;-1196.9
3Q(79)
0.297;-1290.6
379T
0.253;-1466.9
379Q
0.255;-1425.6
(3T)(7J)
0.352;-1155.6
3T(7T)
0.264;-1176.2
3(7TK)
0.292;-1249.4
3T(7Q)
0.288;-1270.0
7J(3J)
0.304;-1135.0
(7J)(3Q)
0.284;-1114.4
3J(7Q)
0.229;-1249.4
7Q(3Q)
0.351;-1093.8
37QQ
0.219;-1228.8
37KK
0.252;-1187.5
8(38J)
0.294;-1176.2
8K(38)
0.279;-1135.0
(389K)
0.239;-1249.4
9J(38)
0.289;-1290.6
(38TJ)
0.266;-1270.0
(38)(TJ)
0.307;-1135.0
J(38J)
0.281;-1114.4
JQ(38)
0.290;-1228.8
Q(38K)
0.261;-1187.5
3889
0.192;-1352.5
38(8Q)
0.283;-1155.6
(39)(8T)
0.299;-1176.2
8(39K)
0.340;-1249.4
3(89J)
0.208;-1290.6
3899
0.271;-1331.9
389J
0.269;-1425.6
389K
0.185;-1384.4
8Q(3T)
0.236;-1249.4
(8T)(3Q)
0.277;-1114.4
3T(8J)
0.281;-1270.0
3T(8K)
0.305;-1228.8
8(3JK)
0.277;-1208.1
3(8JK)
0.223;-1208.1
3J(8K)
0.239;-1208.1
3Q(8Q)
0.281;-1073.1
38QK
0.288;-1322.5
9T(39)
0.223;-1155.6
(39)(9K)
0.267;-958.8
K(39T)
0.268;-1208.1
T(39K)
0.245;-1208.1
JJ(39)
0.265;-1093.8
(39QK)
0.301;-1166.9
3999
0.247;-1176.2
39(9Q)
0.311;-1114.4
(3T)(9J)
0.266;-1114.4
3T(9T)
0.276;-1135.0
3(9TK)
0.228;-1208.1
3T(9Q)
0.287;-1228.8
9J(3J)
0.274;-1093.8
(9J)(3Q)
0.323;-1073.1
3J(9Q)
0.250;-1208.1
9Q(3Q)
0.244;-1052.5
39QQ
0.243;-1187.5
39KK
0.276;-1146.2
T(3TK)
0.320;-1052.5
JJ(3T)
0.317;-1073.1
(3TQK)
0.280;-1146.2
3TTT
0.289;-1114.4
3T(TK)
0.294;-1052.5
(3J)(TK)
0.309;-1031.9
3K(TJ)
0.309;-1166.9
3T(JK)
0.269;-1166.9
(TQ)(3K)
0.279;-1011.2
(3K)(TK)
0.368;-855.6
J(3JK)
0.317;-1011.2
(3J)(QK)
0.340;-990.6
JJ(3K)
0.338;-1011.2
3Q(JQ)
0.306;-1011.2
3JQK
0.251;-1260.6
QK(3Q)
0.369;-970.0
QK(3K)
0.254;-949.4
44(46)
0.333;-1288.7
44(4T)
0.314;-1206.2
(45)(45)
0.310;-1153.8
4(458)
0.247;-1361.9
4T(45)
0.203;-1320.6
(45)(4K)
0.284;-1123.8
4457
0.182;-1517.5
44(5T)
0.227;-1320.6
45(4K)
0.261;-1258.8
4(468)
0.278;-1341.2
4T(46)
0.248;-1300.0
(46)(4K)
0.292;-1103.1
4468
0.209;-1476.2
44(6J)
0.258;-1279.4
(47)(47)
0.309;-1071.2
4(47T)
0.296;-1279.4
4Q(47)
0.263;-1238.1
47(49)
0.264;-1300.0
447J
0.235;-1393.8
48(48)
0.334;-1165.0
(48)(4J)
0.288;-1103.1
4488
0.267;-1300.0
44(8J)
0.317;-1238.1
(49)(49)
0.351;-988.8
4(49Q)
0.245;-1196.9
44(9T)
0.246;-1238.1
49(4K)
0.300;-1176.2
4(4TQ)
0.270;-1176.2
44(TJ)
0.334;-1196.9
(4J)(4J)
0.301;-906.2
44JJ
0.286;-1176.2
4Q(4Q)
0.318;-1000.0
(4K)(4K)
0.378;-823.8
(45)(57)
0.217;-1226.9
5(45T)
0.239;-1300.0
5Q(45)
0.276;-1258.8
8(456)
0.216;-1455.6
Q(456)
0.278;-1373.1
(45)(68)
0.257;-1320.6
6(45J)
0.237;-1393.8
6K(45)
0.253;-1352.5
(457J)
0.247;-1373.1
(45)(78)
0.243;-1300.0
7(45J)
0.241;-1373.1
7K(45)
0.249;-1331.9
(458Q)
0.257;-1331.9
8(45T)
0.293;-1373.1
8Q(45)
0.260;-1331.9
J(459)
0.290;-1331.9
9T(45)
0.256;-1352.5
(45)(9K)
0.288;-1155.6
K(45T)
0.286;-1270.0
T(45K)
0.265;-1270.0
JJ(45)
0.303;-1155.6
(45QK)
0.267;-1228.8
4555
0.272;-1403.1
45(58)
0.273;-1341.2
55(4J)
0.241;-1279.4
455K
0.257;-1373.1
58(46)
0.208;-1455.6
(46)(5J)
0.273;-1258.8
46(56)
0.258;-1361.9
4(569)
0.198;-1435.0
(56)(4Q)
0.285;-1238.1
46(57)
0.203;-1476.2
46(59)
0.191;-1435.0
46(5J)
0.259;-1393.8
46(5K)
0.269;-1352.5
5(479)
0.206;-1414.4
5J(47)
0.273;-1373.1
(57)(48)
0.258;-1300.0
4T(57)
0.237;-1393.8
4(57K)
0.196;-1331.9
47(59)
0.209;-1414.4
47(5J)
0.217;-1373.1
47(5K)
0.289;-1331.9
5(48T)
0.245;-1373.1
5Q(48)
0.226;-1331.9
(58)(4T)
0.259;-1238.1
4Q(58)
0.248;-1331.9
4589
0.233;-1528.8
458J
0.275;-1487.5
458K
0.204;-1446.2
5J(49)
0.261;-1331.9
(59)(4T)
0.257;-1217.5
4Q(59)
0.268;-1311.2
459T
0.231;-1487.5
459Q
0.270;-1446.2
(4T)(5J)
0.271;-1176.2
4T(5T)
0.328;-1196.9
4(5TK)
0.220;-1270.0
4T(5Q)
0.216;-1290.6
5J(4J)
0.312;-1155.6
(5J)(4Q)
0.325;-1135.0
4J(5Q)
0.232;-1270.0
5Q(4Q)
0.353;-1114.4
45QQ
0.330;-1249.4
45KK
0.300;-1208.1
6(469)
0.277;-1279.4
6J(46)
0.250;-1238.1
(4678)
0.300;-1414.4
(467Q)
0.230;-1331.9
7(469)
0.288;-1393.8
7J(46)
0.273;-1352.5
(4689)
0.234;-1373.1
(468K)
0.211;-1290.6
8T(46)
0.207;-1352.5
(46)(8K)
0.281;-1155.6
Q(469)
0.234;-1290.6
(46)(9J)
0.288;-1176.2
T(46T)
0.271;-1176.2
T(46J)
0.247;-1290.6
TK(46)
0.266;-1249.4
(46)(JQ)
0.268;-1114.4
QQ(46)
0.268;-1093.8
46(67)
0.245;-1320.6
66(4T)
0.280;-1258.8
466Q
0.218;-1352.5
68(47)
0.254;-1414.4
(47)(6J)
0.294;-1217.5
47(67)
0.233;-1300.0
4(67T)
0.239;-1373.1
(67)(4K)
0.297;-1176.2
67(49)
0.194;-1393.8
67(4J)
0.289;-1352.5
67(4K)
0.293;-1311.2
69(48)
0.248;-1373.1
(48)(6Q)
0.271;-1176.2
49(68)
0.294;-1373.1
4(68Q)
0.231;-1311.2
46(89)
0.272;-1373.1
46(8J)
0.267;-1331.9
46(8K)
0.279;-1290.6
(49)(6J)
0.220;-1176.2
49(69)
0.285;-1217.5
4(69Q)
0.271;-1290.6
46(9T)
0.274;-1331.9
46(9Q)
0.202;-1290.6
6(4TJ)
0.234;-1290.6
6K(4T)
0.257;-1249.4
(6T)(4K)
0.243;-1114.4
6T(4Q)
0.222;-1270.0
(4J)(6J)
0.293;-1000.0
4J(6J)
0.332;-1135.0
6J(4Q)
0.213;-1249.4
(4Q)(6Q)
0.342;-958.8
4K(6Q)
0.284;-1208.1
4K(6K)
0.302;-1052.5
79(47)
0.321;-1238.1
(47)(7Q)
0.281;-1041.2
(478T)
0.315;-1331.9
88(47)
0.261;-1238.1
(47)(8J)
0.280;-1176.2
9(479)
0.249;-1196.9
K(479)
0.301;-1249.4
9(47Q)
0.273;-1270.0
J(47T)
0.229;-1270.0
TJ(47)
0.262;-1270.0
(47JQ)
0.218;-1228.8
J(47K)
0.243;-1208.1
(47)(QK)
0.260;-1052.5
77(49)
0.257;-1238.1
477J
0.293;-1331.9
78(48)
0.248;-1238.1
(48)(7J)
0.288;-1176.2
48(78)
0.244;-1238.1
4(78J)
0.209;-1311.2
4788
0.230;-1373.1
478T
0.250;-1466.9
478Q
0.245;-1425.6
(49)(7T)
0.266;-1176.2
7(49K)
0.295;-1249.4
4(79J)
0.216;-1290.6
4799
0.250;-1331.9
479J
0.212;-1425.6
479K
0.207;-1384.4
7Q(4T)
0.308;-1249.4
(7T)(4Q)
0.296;-1114.4
4T(7J)
0.250;-1270.0
4T(7K)
0.271;-1228.8
7(4JK)
0.270;-1208.1
4(7JK)
0.286;-1208.1
4J(7K)
0.275;-1208.1
4Q(7Q)
0.310;-1073.1
47QK
0.250;-1322.5
89(48)
0.280;-1196.9
(48)(8Q)
0.330;-1000.0
(489J)
0.304;-1270.0
(48)(9T)
0.251;-1155.6
9(48K)
0.225;-1228.8
(48TK)
0.251;-1208.1
TQ(48)
0.261;-1228.8
K(48J)
0.252;-1187.5
Q(48Q)
0.308;-1052.5
KK(48)
0.299;-1011.2
88(4J)
0.287;-1155.6
488K
0.288;-1249.4
8J(49)
0.270;-1270.0
(89)(4T)
0.271;-1155.6
4Q(89)
0.319;-1249.4
489T
0.255;-1425.6
489Q
0.303;-1384.4
(4T)(8J)
0.362;-1114.4
4T(8T)
0.300;-1135.0
4(8TK)
0.266;-1208.1
4T(8Q)
0.341;-1228.8
8J(4J)
0.272;-1093.8
(8J)(4Q)
0.347;-1073.1
4J(8Q)
0.272;-1208.1
8Q(4Q)
0.345;-1052.5
48QQ
0.332;-1187.5
48KK
0.306;-1146.2
9(49Q)
0.271;-1093.8
J(49T)
0.281;-1228.8
TJ(49)
0.213;-1228.8
(49JQ)
0.286;-1187.5
J(49K)
0.291;-1166.9
(49)(QK)
0.302;-1011.2
99(4J)
0.315;-1114.4
499K
0.283;-1208.1
9Q(4T)
0.289;-1208.1
(9T)(4Q)
0.287;-1073.1
4T(9J)
0.263;-1228.8
4T(9K)
0.304;-1187.5
9(4JK)
0.320;-1166.9
4(9JK)
0.336;-1166.9
4J(9K)
0.249;-1166.9
4Q(9Q)
0.345;-1031.9
49QK
0.282;-1281.2
TJ(4T)
0.302;-1073.1
(4TJQ)
0.306;-1166.9
J(4TK)
0.337;-1146.2
(4T)(QK)
0.325;-990.6
TT(4Q)
0.271;-1052.5
T(4JQ)
0.255;-1166.9
4(TJQ)
0.320;-1166.9
4T(JQ)
0.278;-1166.9
T(4QK)
0.314;-1125.6
TQ(4K)
0.289;-1125.6
JJ(4J)
0.318;-896.9
(4JQK)
0.277;-1105.0
4JJJ
0.303;-1031.9
JQ(4Q)
0.288;-990.6
4JQQ
0.315;-1125.6
4JKK
0.268;-1084.4
QQ(4K)
0.366;-949.4
4KKK
0.368;-908.1
55(59)
0.282;-1165.0
55(5K)
0.319;-1082.5
(56)(58)
0.272;-1165.0
5(56J)
0.229;-1238.1
5K(56)
0.320;-1196.9
56(59)
0.310;-1279.4
556J
0.219;-1373.1
57(57)
0.271;-1165.0
(57)(5T)
0.274;-1103.1
5(57K)
0.280;-1176.2
55(79)
0.290;-1258.8
57(5Q)
0.217;-1196.9
5(589)
0.268;-1238.1
5J(58)
0.300;-1196.9
58(59)
0.302;-1238.1
558J
0.282;-1331.9
59(59)
0.269;-1082.5
(59)(5Q)
0.253;-1020.6
559T
0.242;-1331.9
55(9K)
0.264;-1135.0
(5T)(5Q)
0.373;-1000.0
55TJ
0.241;-1290.6
5J(5J)
0.314;-1000.0
5J(5Q)
0.289;-1114.4
5(5QK)
0.256;-1073.1
5K(5K)
0.317;-917.5
68(56)
0.292;-1279.4
(56)(6J)
0.327;-1082.5
7(567)
0.318;-1279.4
J(567)
0.246;-1331.9
78(56)
0.239;-1393.8
(56)(7J)
0.342;-1196.9
8(568)
0.247;-1238.1
Q(568)
0.312;-1290.6
(56)(8T)
0.261;-1196.9
8(56K)
0.286;-1270.0
(569Q)
0.201;-1270.0
9(56J)
0.263;-1290.6
9K(56)
0.293;-1249.4
TT(56)
0.324;-1155.6
(56)(TK)
0.282;-1093.8
J(56Q)
0.212;-1228.8
K(56Q)
0.233;-1187.5
66(57)
0.263;-1300.0
5669
0.247;-1393.8
56(6Q)
0.306;-1196.9
(57)(68)
0.243;-1258.8
6(57J)
0.281;-1331.9
6K(57)
0.251;-1290.6
(67)(5T)
0.295;-1217.5
5Q(67)
0.265;-1311.2
5678
0.191;-1528.8
567T
0.232;-1487.5
567Q
0.226;-1446.2
(58)(69)
0.247;-1217.5
6(58Q)
0.285;-1290.6
5(689)
0.229;-1352.5
(68)(5Q)
0.270;-1155.6
58(69)
0.308;-1352.5
58(6J)
0.213;-1311.2
58(6K)
0.223;-1270.0
6(59J)
0.240;-1290.6
6K(59)
0.266;-1249.4
(69)(5Q)
0.298;-1135.0
59(6T)
0.222;-1311.2
59(6Q)
0.231;-1270.0
6T(5T)
0.273;-1155.6
(5T)(6K)
0.302;-1093.8
5Q(6T)
0.280;-1249.4
56TJ
0.305;-1405.0
56TK
0.232;-1363.8
6K(5J)
0.269;-1208.1
56JJ
0.265;-1249.4
56JK
0.231;-1343.1
5(6QK)
0.254;-1187.5
6K(5K)
0.247;-1031.9
(57)(79)
0.285;-1082.5
7(57Q)
0.256;-1155.6
9(578)
0.238;-1331.9
K(578)
0.225;-1249.4
8(57J)
0.290;-1290.6
8K(57)
0.272;-1249.4
(579K)
0.276;-1228.8
9J(57)
0.235;-1270.0
(57TJ)
0.273;-1249.4
(57)(TJ)
0.329;-1114.4
J(57J)
0.279;-1093.8
JQ(57)
0.229;-1208.1
Q(57K)
0.300;-1166.9
5778
0.223;-1373.1
57(7J)
0.229;-1176.2
(58)(78)
0.354;-1082.5
7(58J)
0.236;-1290.6
7K(58)
0.242;-1249.4
(78)(5J)
0.326;-1155.6
5K(78)
0.265;-1249.4
57(8T)
0.241;-1311.2
57(8Q)
0.279;-1270.0
7(59T)
0.309;-1290.6
7Q(59)
0.273;-1249.4
(79)(5J)
0.290;-1135.0
5K(79)
0.300;-1228.8
57(9J)
0.284;-1270.0
57(9K)
0.338;-1228.8
(5T)(7Q)
0.290;-1093.8
5J(7T)
0.254;-1249.4
7T(5J)
0.293;-1249.4
7T(5K)
0.338;-1208.1
7Q(5J)
0.320;-1208.1
(7J)(5K)
0.281;-1052.5
7J(5K)
0.340;-1187.5
7K(5Q)
0.311;-1166.9
57(QK)
0.313;-1166.9
(58)(89)
0.288;-1041.2
8(58Q)
0.282;-1114.4
T(589)
0.277;-1270.0
9(58T)
0.246;-1270.0
9Q(58)
0.263;-1228.8
Q(58T)
0.309;-1208.1
(58)(TQ)
0.298;-1073.1
(58JK)
0.314;-1166.9
JK(58)
0.259;-1166.9
K(58K)
0.246;-990.6
588T
0.271;-1290.6
58(8K)
0.277;-1093.8
(59)(8J)
0.275;-1114.4
59(89)
0.267;-1155.6
5(89Q)
0.258;-1228.8
58(9T)
0.322;-1270.0
58(9Q)
0.234;-1228.8
8(5TJ)
0.323;-1228.8
8K(5T)
0.251;-1187.5
(8T)(5K)
0.255;-1052.5
8T(5Q)
0.286;-1208.1
(5J)(8J)
0.361;-938.1
5J(8J)
0.257;-1073.1
8J(5Q)
0.274;-1187.5
(5Q)(8Q)
0.311;-896.9
5K(8Q)
0.328;-1146.2
5K(8K)
0.353;-990.6
9J(59)
0.282;-1093.8
(59TJ)
0.254;-1208.1
(59)(TJ)
0.300;-1073.1
J(59J)
0.338;-1052.5
JQ(59)
0.319;-1166.9
Q(59K)
0.226;-1125.6
599T
0.265;-1249.4
59(9K)
0.292;-1052.5
(5T)(9Q)
0.265;-1052.5
5J(9T)
0.232;-1208.1
9T(5J)
0.263;-1208.1
9T(5K)
0.280;-1166.9
9Q(5J)
0.250;-1166.9
(9J)(5K)
0.289;-1011.2
9J(5K)
0.355;-1146.2
9K(5Q)
0.289;-1125.6
59(QK)
0.264;-1125.6
(5T)(TJ)
0.316;-917.5
J(5TJ)
0.313;-1031.9
JQ(5T)
0.247;-1146.2
Q(5TK)
0.309;-1105.0
5TTJ
0.319;-1187.5
TJ(5J)
0.322;-1031.9
(TJ)(5Q)
0.262;-1011.2
5J(TQ)
0.325;-1146.2
TQ(5Q)
0.264;-990.6
5TQQ
0.234;-1125.6
5TKK
0.356;-1084.4
Q(5JQ)
0.285;-970.0
KK(5J)
0.296;-928.7
(5Q)(JQ)
0.343;-835.0
5K(JQ)
0.249;-1084.4
5K(JK)
0.370;-928.7
5QQQ
0.272;-949.4
KK(5K)
0.291;-752.5
6669
0.230;-1238.1
666K
0.223;-1155.6
69(67)
0.268;-1217.5
(67)(6Q)
0.333;-1020.6
6678
0.201;-1373.1
66(7J)
0.282;-1176.2
(68)(68)
0.350;-947.5
6(68J)
0.266;-1155.6
6K(68)
0.284;-1114.4
68(6J)
0.262;-1155.6
668K
0.283;-1249.4
6J(69)
0.286;-1135.0
69(6T)
0.318;-1155.6
669Q
0.234;-1249.4
6J(6T)
0.318;-1114.4
6T(6J)
0.276;-1114.4
66TK
0.220;-1208.1
6K(6J)
0.308;-1052.5
(6Q)(6Q)
0.299;-782.5
66QK
0.304;-1166.9
7(679)
0.264;-1196.9
7J(67)
0.237;-1155.6
(6789)
0.282;-1311.2
(678K)
0.262;-1228.8
8T(67)
0.264;-1290.6
(67)(8K)
0.300;-1093.8
Q(679)
0.259;-1228.8
(67)(9J)
0.221;-1114.4
T(67T)
0.263;-1114.4
T(67J)
0.267;-1228.8
TK(67)
0.304;-1187.5
(67)(JQ)
0.245;-1052.5
QQ(67)
0.297;-1031.9
67(78)
0.277;-1217.5
77(6J)
0.291;-1155.6
677K
0.263;-1249.4
7T(68)
0.301;-1290.6
(68)(7K)
0.268;-1093.8
6T(78)
0.254;-1290.6
6(78K)
0.231;-1228.8
68(7T)
0.230;-1290.6
68(7Q)
0.248;-1249.4
79(69)
0.261;-1155.6
(69)(7Q)
0.308;-1093.8
6T(79)
0.252;-1270.0
6(79K)
0.283;-1208.1
69(7J)
0.283;-1249.4
69(7K)
0.287;-1208.1
7(6TQ)
0.260;-1208.1
6(7TJ)
0.306;-1228.8
67TT
0.281;-1249.4
67TQ
0.281;-1343.1
(6J)(7Q)
0.282;-1052.5
6Q(7J)
0.215;-1187.5
67JQ
0.254;-1322.5
(6Q)(7K)
0.329;-1011.2
6Q(7K)
0.279;-1146.2
8(689)
0.261;-1155.6
8J(68)
0.291;-1114.4
(689T)
0.300;-1249.4
99(68)
0.299;-1135.0
(68)(9Q)
0.272;-1073.1
(68TQ)
0.325;-1187.5
T(68Q)
0.286;-1187.5
Q(68J)
0.328;-1166.9
(68)(JK)
0.330;-1011.2
QK(68)
0.356;-1125.6
68(8T)
0.319;-1135.0
88(6K)
0.304;-1073.1
8(69J)
0.255;-1228.8
8K(69)
0.313;-1187.5
(89)(6Q)
0.348;-1073.1
69(8T)
0.259;-1249.4
69(8Q)
0.280;-1208.1
8T(6T)
0.352;-1093.8
(6T)(8K)
0.247;-1031.9
6Q(8T)
0.243;-1187.5
68TJ
0.275;-1343.1
68TK
0.215;-1301.9
8K(6J)
0.280;-1146.2
68JJ
0.249;-1187.5
68JK
0.251;-1281.2
6(8QK)
0.244;-1125.6
8K(6K)
0.365;-970.0
(69)(9J)
0.348;-938.1
T(69T)
0.286;-1073.1
T(69J)
0.279;-1187.5
TK(69)
0.264;-1146.2
(69)(JQ)
0.343;-1011.2
QQ(69)
0.343;-990.6
69(9T)
0.280;-1093.8
99(6K)
0.279;-1031.9
9(6TQ)
0.300;-1166.9
6(9TJ)
0.241;-1187.5
69TT
0.274;-1208.1
69TQ
0.217;-1301.9
(6J)(9Q)
0.327;-1011.2
6Q(9J)
0.280;-1146.2
69JQ
0.273;-1281.2
(6Q)(9K)
0.277;-970.0
6Q(9K)
0.259;-1105.0
T(6TJ)
0.296;-1031.9
TK(6T)
0.336;-990.6
(6T)(JQ)
0.273;-990.6
QQ(6T)
0.266;-970.0
6T(TJ)
0.281;-1031.9
(6J)(TJ)
0.353;-876.3
6J(TJ)
0.325;-1011.2
TJ(6Q)
0.272;-1125.6
(6Q)(TQ)
0.343;-835.0
6K(TQ)
0.282;-1084.4
6K(TK)
0.329;-928.7
JK(6J)
0.325;-949.4
K(6JK)
0.335;-908.1
6JJK
0.341;-1084.4
6(JQK)
0.312;-1063.8
JK(6K)
0.326;-908.1
KK(6Q)
0.314;-887.5
6QKK
0.288;-1022.5
77(7T)
0.321;-1020.6
(78)(78)
0.328;-906.2
7(78J)
0.254;-1114.4
7K(78)
0.294;-1073.1
78(7J)
0.250;-1114.4
778K
0.292;-1208.1
7J(79)
0.338;-1093.8
79(7T)
0.292;-1114.4
779Q
0.295;-1208.1
7J(7T)
0.309;-1073.1
7T(7J)
0.264;-1073.1
77TK
0.281;-1166.9
7K(7J)
0.316;-1011.2
(7Q)(7Q)
0.383;-741.2
77QK
0.313;-1125.6
8(78T)
0.313;-1114.4
8Q(78)
0.309;-1073.1
J(789)
0.258;-1208.1
9T(78)
0.258;-1228.8
(78)(9K)
0.300;-1031.9
K(78T)
0.273;-1146.2
T(78K)
0.276;-1146.2
JJ(78)
0.343;-1031.9
(78QK)
0.280;-1105.0
7888
0.307;-1155.6
78(8J)
0.226;-1093.8
(79)(89)
0.343;-979.4
8(79Q)
0.272;-1187.5
7(89T)
0.277;-1228.8
(89)(7K)
0.328;-1031.9
89(7J)
0.239;-1208.1
89(7K)
0.307;-1166.9
8J(7T)
0.246;-1187.5
(8T)(7J)
0.350;-1052.5
7K(8T)
0.296;-1146.2
78(TQ)
0.264;-1166.9
8(7JQ)
0.248;-1146.2
7(8JQ)
0.259;-1146.2
78(JQ)
0.255;-1146.2
8(7QK)
0.297;-1105.0
8Q(7K)
0.311;-1105.0
99(79)
0.317;-958.8
(79)(9Q)
0.312;-896.9
(79TQ)
0.302;-1146.2
T(79Q)
0.322;-1146.2
Q(79J)
0.276;-1125.6
(79)(JK)
0.321;-970.0
QK(79)
0.295;-1084.4
79(9J)
0.341;-1052.5
(7T)(9T)
0.321;-917.5
9(7TK)
0.283;-1125.6
7(9TQ)
0.284;-1146.2
79(TJ)
0.293;-1166.9
79(TK)
0.332;-1125.6
(7J)(9K)
0.305;-970.0
7K(9J)
0.302;-1105.0
79(JK)
0.315;-1105.0
(9Q)(7K)
0.363;-949.4
(7K)(9K)
0.350;-793.8
T(7TQ)
0.249;-990.6
Q(7TJ)
0.258;-1105.0
(7T)(JK)
0.327;-949.4
QK(7T)
0.302;-1063.8
7T(TQ)
0.321;-990.6
(7J)(TQ)
0.362;-970.0
7Q(TJ)
0.322;-1105.0
7TJQ
0.259;-1240.0
(7Q)(TK)
0.290;-928.7
7Q(TK)
0.343;-1063.8
J(7JQ)
0.304;-949.4
K(7JQ)
0.331;-1043.1
JJ(7Q)
0.400;-949.4
J(7QK)
0.265;-1043.1
JQ(7K)
0.295;-1043.1
QQ(7Q)
0.317;-773.1
7Q(QK)
0.404;-887.5
8888
0.329;-1000.0
888Q
0.298;-1052.5
8(89J)
0.344;-1052.5
8K(89)
0.330;-1011.2
89(8Q)
0.297;-1031.9
8(8TJ)
0.359;-1031.9
8K(8T)
0.377;-990.6
8T(8K)
0.301;-990.6
8(8JK)
0.330;-970.0
88(JK)
0.333;-970.0
8Q(8K)
0.322;-949.4
(89)(9T)
0.299;-917.5
9(89K)
0.324;-990.6
(89TK)
0.278;-1105.0
TQ(89)
0.301;-1125.6
K(89J)
0.277;-1084.4
Q(89Q)
0.345;-949.4
KK(89)
0.314;-908.1
99(8Q)
0.330;-1011.2
9(8TJ)
0.264;-1146.2
9K(8T)
0.302;-1105.0
(9T)(8K)
0.332;-970.0
9T(8Q)
0.292;-1125.6
(8J)(9J)
0.311;-855.6
8J(9J)
0.262;-990.6
9J(8Q)
0.347;-1105.0
(8Q)(9Q)
0.321;-814.4
8K(9Q)
0.331;-1063.8
8K(9K)
0.322;-908.1
TQ(8T)
0.266;-970.0
K(8TJ)
0.287;-1063.8
Q(8TQ)
0.391;-928.7
KK(8T)
0.350;-887.5
