AAAA
0.216;1910.0
5AAA
0.126;-5143.8
9AAA
0.090;-3328.7
KAAA
0.148;-1513.8
4A(2A)
0.055;-11042.5
(2A)(7A)
0.071;-6711.3
A(2TA)
0.057;-8320.0
QA(2A)
0.062;-7412.5
2A(4A)
0.063;-11042.5
26AA
0.033;-13105.0
AA(29)
0.061;-8773.8
2A(QA)
0.074;-7412.5
A(34A)
0.039;-10588.8
6A(3A)
0.069;-9681.3
(3A)(9A)
0.081;-5350.0
A(3QA)
0.093;-6958.8
AA(34)
0.056;-10588.8
3A(7A)
0.065;-9227.5
39AA
0.034;-11290.0
AA(3Q)
0.066;-6958.8
(4A)(5A)
0.076;-6711.3
A(48A)
0.052;-8320.0
TA(4A)
0.088;-7412.5
(4A)(KA)
0.130;-3081.2
46AA
0.033;-12197.5
AA(49)
0.067;-7866.2
4A(QA)
0.075;-6505.0
A(56A)
0.070;-8773.8
8A(5A)
0.074;-7866.2
(5A)(JA)
0.124;-3535.0
55AA
0.057;-9227.5
AA(58)
0.082;-7866.2
5A(JA)
0.090;-6505.0
5KAA
0.079;-8567.5
8A(6A)
0.087;-7412.5
(6A)(JA)
0.099;-3081.2
66AA
0.050;-8320.0
AA(69)
0.076;-6958.8
6A(QA)
0.073;-5597.5
A(78A)
0.094;-6958.8
TA(7A)
0.080;-6051.3
(7A)(KA)
0.108;-1720.0
79AA
0.062;-9475.0
AA(7Q)
0.109;-5143.8
(8A)(9A)
0.112;-3081.2
A(8QA)
0.104;-4690.0
AA(89)
0.101;-6051.3
8A(QA)
0.114;-4690.0
A(9TA)
0.090;-5143.8
QA(9A)
0.101;-4236.3
9A(JA)
0.095;-4690.0
9KAA
0.075;-6752.5
QA(TA)
0.098;-3782.5
TA(QA)
0.097;-3782.5
A(JQA)
0.098;-3328.8
AA(JQ)
0.101;-3328.8
(QA)(KA)
0.133;548.7
KKAA
0.122;-1967.5
2(25A)
0.024;-16033.8
27(2A)
0.023;-15126.2
(2T)(2A)
0.055;-10795.0
2(2KA)
0.037;-12403.8
(236A)
0.013;-18096.2
(23TA)
0.016;-16281.2
33(2A)
0.025;-16487.5
(36)(2A)
0.023;-15126.2
3(29A)
0.020;-16735.0
3J(2A)
0.024;-15827.5
(245A)
0.018;-18096.2
(249A)
0.027;-16281.2
(24KA)
0.039;-14466.2
46(2A)
0.016;-17642.5
(49)(2A)
0.034;-13311.3
4(2QA)
0.031;-14920.0
6(25A)
0.015;-17188.8
T(25A)
0.027;-15373.8
5(26A)
0.014;-17188.8
58(2A)
0.024;-16281.2
(5J)(2A)
0.032;-11950.0
6(26A)
0.038;-13765.0
T(26A)
0.027;-14920.0
6(27A)
0.026;-16281.2
69(2A)
0.021;-15373.8
(6Q)(2A)
0.051;-11042.5
(279A)
0.026;-14920.0
(27KA)
0.035;-13105.0
79(2A)
0.034;-14920.0
(7Q)(2A)
0.051;-10588.8
(28TA)
0.035;-14012.5
88(2A)
0.039;-11950.0
(8J)(2A)
0.046;-10588.8
9(29A)
0.061;-11042.5
K(29A)
0.036;-12197.5
9(2QA)
0.032;-12651.3
J(2TA)
0.043;-12651.3
TJ(2A)
0.041;-12651.3
(2JQA)
0.037;-11743.7
J(2KA)
0.058;-11290.0
(QK)(2A)
0.064;-7866.2
22(4A)
0.022;-16487.5
226A
0.015;-18550.0
2A(29)
0.038;-14218.8
22(QA)
0.042;-12857.5
2(34A)
0.012;-19003.8
26(3A)
0.017;-18096.2
(29)(3A)
0.032;-13765.0
2(3QA)
0.022;-15373.8
A(234)
0.014;-19003.8
(23)(7A)
0.026;-14672.5
9A(23)
0.020;-16735.0
A(23Q)
0.033;-15373.8
2A(34)
0.010;-19003.8
2A(36)
0.016;-18096.2
2A(38)
0.016;-17188.8
2A(3T)
0.024;-16281.2
2A(3Q)
0.031;-15373.8
2(45A)
0.013;-18096.2
27(4A)
0.020;-17188.8
(2T)(4A)
0.039;-12857.5
2(4KA)
0.031;-14466.2
A(246)
0.020;-17642.5
(24)(9A)
0.027;-13311.3
JA(24)
0.023;-15373.8
24(5A)
0.020;-18096.2
24(7A)
0.020;-17188.8
24(9A)
0.024;-16281.2
24(JA)
0.027;-15373.8
24(KA)
0.028;-14466.2
26(5A)
0.015;-17188.8
(29)(5A)
0.037;-12857.5
2(5QA)
0.031;-14466.2
A(256)
0.019;-17188.8
(25)(9A)
0.035;-12857.5
JA(25)
0.030;-14920.0
25(6A)
0.025;-17188.8
25(8A)
0.023;-16281.2
25(TA)
0.021;-15373.8
25(QA)
0.028;-14466.2
(26)(6A)
0.063;-10795.0
2(69A)
0.029;-15373.8
2J(6A)
0.028;-14466.2
(26)(7A)
0.025;-13311.3
9A(26)
0.028;-15373.8
A(26Q)
0.029;-14012.5
2A(67)
0.019;-16281.2
2A(69)
0.031;-15373.8
2A(6J)
0.025;-14466.2
2A(6K)
0.031;-13558.8
(29)(7A)
0.035;-11950.0
2(7QA)
0.032;-13558.8
A(278)
0.026;-15373.8
(27)(JA)
0.055;-11042.5
KA(27)
0.048;-13105.0
2A(79)
0.030;-14920.0
2A(7J)
0.031;-14012.5
2A(7K)
0.046;-13105.0
(2T)(8A)
0.061;-11042.5
2(8KA)
0.032;-12651.3
A(28T)
0.028;-14012.5
(28)(KA)
0.064;-9681.3
28(TA)
0.033;-14012.5
28(QA)
0.029;-13105.0
(29)(9A)
0.053;-8072.5
2(9QA)
0.047;-12651.3
A(29T)
0.034;-13558.8
(29)(KA)
0.066;-9227.5
29(JA)
0.031;-13105.0
29(KA)
0.031;-12197.5
2J(TA)
0.041;-12651.3
(2T)(JA)
0.055;-9681.3
KA(2T)
0.043;-11743.7
2A(TQ)
0.039;-12197.5
2(JQA)
0.046;-11743.7
A(2JQ)
0.038;-11743.7
2A(JQ)
0.052;-11743.7
2(QKA)
0.050;-10836.2
2Q(KA)
0.054;-10836.2
33(3A)
0.041;-13063.8
(36)(3A)
0.038;-11702.5
3(39A)
0.033;-13311.2
3J(3A)
0.034;-12403.8
(345A)
0.020;-17642.5
(349A)
0.020;-15827.5
(34KA)
0.024;-14012.5
46(3A)
0.021;-17188.8
(49)(3A)
0.029;-12857.5
4(3QA)
0.034;-14466.2
6(35A)
0.018;-16735.0
T(35A)
0.023;-14920.0
5(36A)
0.026;-16735.0
58(3A)
0.027;-15827.5
(5J)(3A)
0.040;-11496.2
6(36A)
0.029;-13311.2
T(36A)
0.037;-14466.2
6(37A)
0.031;-15827.5
69(3A)
0.032;-14920.0
(6Q)(3A)
0.049;-10588.8
(379A)
0.023;-14466.2
(37KA)
0.046;-12651.3
79(3A)
0.030;-14466.2
(7Q)(3A)
0.048;-10135.0
(38TA)
0.032;-13558.8
88(3A)
0.041;-11496.2
(8J)(3A)
0.047;-10135.0
9(39A)
0.038;-10588.8
K(39A)
0.043;-11743.7
9(3QA)
0.037;-12197.5
J(3TA)
0.035;-12197.5
TJ(3A)
0.039;-12197.5
(3JQA)
0.037;-11290.0
J(3KA)
0.042;-10836.2
(QK)(3A)
0.078;-7412.5
33(5A)
0.028;-15126.2
337A
0.016;-17188.8
3A(3T)
0.036;-12857.5
33(KA)
0.057;-11496.2
3(46A)
0.021;-17188.8
38(4A)
0.024;-16281.2
(3J)(4A)
0.052;-11950.0
4A(34)
0.028;-15126.2
A(347)
0.022;-16735.0
(34)(TA)
0.044;-12403.8
QA(34)
0.028;-14466.2
345A
0.007;-20612.5
347A
0.013;-19705.0
349A
0.014;-18797.5
34JA
0.017;-17890.0
34KA
0.025;-16982.5
37(5A)
0.016;-16281.2
(3T)(5A)
0.050;-11950.0
3(5KA)
0.028;-13558.8
A(357)
0.024;-16281.2
(35)(TA)
0.043;-11950.0
QA(35)
0.033;-14012.5
356A
0.008;-19705.0
358A
0.016;-18797.5
35TA
0.018;-17890.0
35QA
0.018;-16982.5
(37)(6A)
0.032;-12857.5
3(6TA)
0.024;-14466.2
3Q(6A)
0.033;-13558.8
(36)(8A)
0.037;-12403.8
TA(36)
0.032;-14466.2
A(36K)
0.047;-13105.0
6A(38)
0.026;-15373.8
6A(3T)
0.024;-14466.2
6A(3Q)
0.043;-13558.8
37(7A)
0.046;-12403.8
(3T)(7A)
0.049;-11042.5
3(7KA)
0.032;-12651.3
A(379)
0.028;-14466.2
(37)(QA)
0.052;-10135.0
7A(38)
0.022;-14920.0
7A(3T)
0.036;-14012.5
7A(3Q)
0.039;-13105.0
38(8A)
0.043;-11496.2
(3J)(8A)
0.057;-10135.0
8A(38)
0.040;-11496.2
A(38J)
0.040;-13105.0
388A
0.040;-14466.2
38TA
0.022;-16528.8
38QA
0.022;-15621.3
(3T)(9A)
0.048;-10135.0
3(9KA)
0.046;-11743.7
A(39J)
0.048;-12651.3
399A
0.025;-13558.8
39JA
0.020;-15621.3
39KA
0.025;-14713.8
3Q(TA)
0.049;-11743.7
(3T)(QA)
0.061;-8773.8
TA(3J)
0.048;-12197.5
TA(3K)
0.041;-11290.0
3(JKA)
0.039;-10836.2
A(3JK)
0.049;-10836.2
JA(3K)
0.044;-10836.2
QA(3Q)
0.068;-7866.2
3QKA
0.039;-13352.5
45(4A)
0.032;-14218.8
(48)(4A)
0.050;-9887.5
4(4JA)
0.034;-11496.2
4K(4A)
0.047;-10588.8
(459A)
0.025;-14920.0
(45KA)
0.033;-13105.0
57(4A)
0.028;-15827.5
(5T)(4A)
0.036;-11496.2
5(4KA)
0.031;-13105.0
(469A)
0.032;-14466.2
(46KA)
0.043;-12651.3
68(4A)
0.029;-14920.0
(6J)(4A)
0.039;-10588.8
7(47A)
0.049;-11950.0
J(47A)
0.033;-13105.0
78(4A)
0.027;-14466.2
(7J)(4A)
0.062;-10135.0
8(48A)
0.060;-11042.5
Q(48A)
0.041;-12197.5
(8T)(4A)
0.042;-10135.0
8(4KA)
0.052;-11743.7
(49QA)
0.042;-11743.7
9(4JA)
0.045;-12197.5
9K(4A)
0.046;-11290.0
TT(4A)
0.047;-9227.5
(TK)(4A)
0.072;-7866.2
J(4QA)
0.058;-10836.2
K(4QA)
0.061;-9928.8
44(5A)
0.027;-14218.8
447A
0.017;-16281.2
4A(4T)
0.051;-11950.0
44(KA)
0.049;-10588.8
4(57A)
0.018;-15827.5
49(5A)
0.025;-14920.0
(4Q)(5A)
0.057;-10588.8
6A(45)
0.023;-16281.2
A(459)
0.037;-14920.0
(45)(QA)
0.056;-10588.8
5A(46)
0.028;-16281.2
5A(48)
0.024;-15373.8
5A(4T)
0.030;-14466.2
5A(4Q)
0.031;-13558.8
46(6A)
0.045;-12857.5
(49)(6A)
0.041;-11496.2
4(6QA)
0.047;-13105.0
A(467)
0.027;-15373.8
(46)(TA)
0.052;-11042.5
QA(46)
0.039;-13105.0
467A
0.013;-18343.8
469A
0.016;-17436.2
46JA
0.022;-16528.8
46KA
0.020;-15621.3
49(7A)
0.029;-14012.5
(4Q)(7A)
0.061;-9681.3
8A(47)
0.027;-14466.2
A(47J)
0.034;-13105.0
477A
0.036;-14920.0
479A
0.021;-16982.5
47JA
0.019;-16075.0
47KA
0.026;-15167.5
4T(8A)
0.042;-13105.0
(4K)(8A)
0.054;-8773.8
TA(48)
0.038;-13105.0
A(48K)
0.048;-11743.7
8A(4T)
0.038;-13105.0
8A(4Q)
0.033;-12197.5
49(9A)
0.054;-10135.0
(4Q)(9A)
0.058;-8773.8
TA(49)
0.039;-12651.3
A(49K)
0.045;-11290.0
9A(4J)
0.045;-12197.5
9A(4K)
0.047;-11290.0
4(TQA)
0.042;-11290.0
A(4TJ)
0.048;-11743.7
4TTA
0.040;-12197.5
4TQA
0.034;-14260.0
(4Q)(JA)
0.072;-7866.2
QA(4J)
0.052;-10836.2
4JQA
0.030;-13806.2
(4K)(QA)
0.092;-6958.8
QA(4K)
0.065;-9928.8
5(56A)
0.039;-12857.5
58(5A)
0.051;-11950.0
(5J)(5A)
0.068;-7618.8
6(56A)
0.047;-12403.8
T(56A)
0.029;-13558.8
6(57A)
0.025;-14920.0
69(5A)
0.039;-14012.5
(6Q)(5A)
0.063;-9681.3
(579A)
0.032;-13558.8
(57KA)
0.050;-11743.7
79(5A)
0.028;-13558.8
(7Q)(5A)
0.084;-9227.5
(58TA)
0.033;-12651.3
88(5A)
0.056;-10588.8
(8J)(5A)
0.050;-9227.5
9(59A)
0.045;-9681.3
K(59A)
0.046;-10836.2
9(5QA)
0.055;-11290.0
J(5TA)
0.047;-11290.0
TJ(5A)
0.043;-11290.0
(5JQA)
0.054;-10382.5
J(5KA)
0.064;-9928.8
(QK)(5A)
0.067;-6505.0
55(7A)
0.036;-12403.8
559A
0.025;-14466.2
5A(5Q)
0.057;-10135.0
(57)(6A)
0.044;-11950.0
5(6TA)
0.039;-13558.8
5Q(6A)
0.037;-12651.3
(56)(8A)
0.054;-11496.2
TA(56)
0.046;-13558.8
A(56K)
0.039;-12197.5
6A(58)
0.025;-14466.2
6A(5T)
0.030;-13558.8
6A(5Q)
0.039;-12651.3
57(7A)
0.048;-11496.2
(5T)(7A)
0.042;-10135.0
5(7KA)
0.045;-11743.7
A(579)
0.037;-13558.8
(57)(QA)
0.061;-9227.5
7A(58)
0.035;-14012.5
7A(5T)
0.034;-13105.0
7A(5Q)
0.032;-12197.5
58(8A)
0.058;-10588.8
(5J)(8A)
0.073;-9227.5
8A(58)
0.050;-10588.8
A(58J)
0.037;-12197.5
588A
0.034;-13558.8
58TA
0.030;-15621.3
58QA
0.026;-14713.8
(5T)(9A)
0.061;-9227.5
5(9KA)
0.053;-10836.2
A(59J)
0.047;-11743.7
599A
0.036;-12651.3
59JA
0.025;-14713.8
59KA
0.027;-13806.2
5Q(TA)
0.055;-10836.2
(5T)(QA)
0.072;-7866.2
TA(5J)
0.053;-11290.0
TA(5K)
0.044;-10382.5
5(JKA)
0.047;-9928.8
A(5JK)
0.063;-9928.8
JA(5K)
0.054;-9928.8
QA(5Q)
0.072;-6958.8
5QKA
0.035;-12445.0
67(6A)
0.053;-11496.2
(6T)(6A)
0.075;-7165.0
6(6KA)
0.078;-8773.8
(67TA)
0.042;-12651.3
77(6A)
0.048;-11042.5
(7T)(6A)
0.043;-9681.3
7(6KA)
0.045;-11290.0
(68JA)
0.039;-11743.7
(89)(6A)
0.050;-9681.3
8(6QA)
0.051;-11290.0
T(69A)
0.045;-11743.7
9(6TA)
0.039;-11743.7
9Q(6A)
0.054;-10836.2
Q(6TA)
0.060;-10382.5
(TQ)(6A)
0.075;-7412.5
(6JKA)
0.051;-9475.0
JK(6A)
0.057;-9475.0
K(6KA)
0.064;-5597.5
668A
0.029;-14012.5
6A(6J)
0.049;-9681.3
(67)(7A)
0.072;-8072.5
6(7TA)
0.042;-12651.3
6Q(7A)
0.040;-11743.7
(67)(9A)
0.043;-10135.0
JA(67)
0.032;-12197.5
67(8A)
0.028;-13558.8
67(TA)
0.039;-12651.3
67(QA)
0.038;-11743.7
(68)(8A)
0.055;-7165.0
6(8JA)
0.040;-11743.7
6K(8A)
0.045;-10836.2
(68)(JA)
0.061;-8773.8
KA(68)
0.061;-10836.2
6A(8T)
0.048;-12197.5
6A(8Q)
0.049;-11290.0
6(9TA)
0.033;-11743.7
6Q(9A)
0.044;-10836.2
(69)(JA)
0.074;-8320.0
KA(69)
0.048;-10382.5
6A(9J)
0.055;-11290.0
6A(9K)
0.049;-10382.5
(6Q)(TA)
0.063;-7412.5
JA(6T)
0.047;-10836.2
6T(JA)
0.037;-10836.2
6T(KA)
0.064;-9928.8
6Q(JA)
0.057;-9928.8
(6J)(KA)
0.093;-6505.0
6J(KA)
0.059;-9475.0
6K(QA)
0.066;-9021.2
6A(QK)
0.074;-9021.2
(78)(7A)
0.089;-7165.0
7(7JA)
0.063;-8773.8
7K(7A)
0.089;-7866.2
(78QA)
0.041;-10836.2
8(7TA)
0.046;-11743.7
8Q(7A)
0.057;-10836.2
J(79A)
0.050;-10836.2
9T(7A)
0.034;-11290.0
(9K)(7A)
0.081;-6958.8
K(7TA)
0.046;-9475.0
T(7KA)
0.056;-9475.0
JJ(7A)
0.076;-6958.8
(7QKA)
0.075;-8567.5
777A
0.058;-10588.8
7A(7T)
0.049;-9227.5
77(KA)
0.074;-7866.2
7(8TA)
0.034;-11743.7
7Q(8A)
0.058;-10836.2
(78)(TA)
0.054;-8773.8
QA(78)
0.046;-10836.2
789A
0.025;-15167.5
78JA
0.028;-14260.0
78KA
0.035;-13352.5
7J(9A)
0.046;-10836.2
(79)(TA)
0.064;-8320.0
QA(79)
0.055;-10382.5
79TA
0.033;-14260.0
79QA
0.032;-13352.5
(7J)(TA)
0.083;-7412.5
TA(7T)
0.065;-7866.2
A(7TK)
0.062;-9475.0
TA(7Q)
0.046;-9928.8
7J(JA)
0.086;-6958.8
(7J)(QA)
0.089;-6505.0
JA(7Q)
0.060;-9475.0
7Q(QA)
0.087;-6051.3
7QQA
0.061;-9021.2
7KKA
0.072;-8113.8
8(8JA)
0.066;-7866.2
8K(8A)
0.085;-6958.8
(89KA)
0.068;-9475.0
9J(8A)
0.047;-10382.5
(8TJA)
0.072;-9928.8
(TJ)(8A)
0.081;-6958.8
J(8JA)
0.088;-6505.0
JQ(8A)
0.058;-9021.2
Q(8KA)
0.064;-8113.8
889A
0.057;-11743.7
8A(8Q)
0.065;-7412.5
(8T)(9A)
0.081;-7866.2
8(9KA)
0.072;-9475.0
A(89J)
0.061;-10382.5
899A
0.044;-11290.0
89JA
0.037;-13352.5
89KA
0.042;-12445.0
8Q(TA)
0.052;-9475.0
(8T)(QA)
0.103;-6505.0
TA(8J)
0.078;-9928.8
TA(8K)
0.077;-9021.2
8(JKA)
0.050;-8567.5
A(8JK)
0.051;-8567.5
JA(8K)
0.086;-8567.5
QA(8Q)
0.116;-5597.5
8QKA
0.044;-11083.8
9T(9A)
0.081;-7412.5
(9K)(9A)
0.095;-3081.2
K(9TA)
0.053;-8567.5
T(9KA)
0.050;-8567.5
JJ(9A)
0.088;-6051.3
(9QKA)
0.072;-7660.0
999A
0.067;-7866.2
9A(9Q)
0.070;-6505.0
(9J)(TA)
0.069;-6505.0
TA(9T)
0.098;-6958.8
A(9TK)
0.058;-8567.5
TA(9Q)
0.051;-9021.2
9J(JA)
0.097;-6051.3
(9J)(QA)
0.088;-5597.5
JA(9Q)
0.062;-8567.5
9Q(QA)
0.098;-5143.8
9QQA
0.082;-8113.8
9KKA
0.062;-7206.3
T(TKA)
0.076;-5143.8
JJ(TA)
0.083;-5597.5
(TQKA)
0.064;-7206.3
TTTA
0.077;-6505.0
TA(TK)
0.104;-5143.8
(TK)(JA)
0.095;-4690.0
KA(TJ)
0.059;-7660.0
TA(JK)
0.062;-7660.0
(TQ)(KA)
0.104;-4236.3
(TK)(KA)
0.146;-812.5
J(JKA)
0.091;-4236.3
(QK)(JA)
0.116;-3782.5
JJ(KA)
0.093;-4236.3
QA(JQ)
0.107;-4236.3
JQKA
0.066;-9722.5
QK(QA)
0.133;-3328.8
QK(KA)
0.122;-2875.0
22(24)
0.012;-18962.5
22(28)
0.018;-17147.5
22(2Q)
0.030;-15332.5
24(23)
0.009;-21478.8
(23)(27)
0.020;-17147.5
2(23T)
0.014;-18756.2
2Q(23)
0.014;-17848.8
23(25)
0.008;-21025.0
2237
0.004;-23087.5
22(3T)
0.015;-18756.2
23(2K)
0.020;-17395.0
2(246)
0.012;-20117.5
28(24)
0.013;-19210.0
(24)(2J)
0.029;-14878.8
2244
0.008;-21025.0
22(47)
0.009;-19663.8
24(2T)
0.016;-18302.5
224Q
0.008;-20365.0
26(25)
0.013;-19663.8
(25)(29)
0.026;-15332.5
2(25Q)
0.018;-16941.3
22(56)
0.012;-19663.8
25(29)
0.015;-18302.5
225J
0.011;-20365.0
26(26)
0.024;-16240.0
(26)(29)
0.026;-14878.8
2(26Q)
0.021;-16487.5
22(67)
0.014;-18756.2
26(2T)
0.017;-17395.0
226Q
0.011;-19457.5
28(27)
0.020;-17848.8
(27)(2J)
0.039;-13517.5
2277
0.016;-18302.5
22(7T)
0.019;-16941.3
27(2K)
0.032;-15580.0
2(28T)
0.028;-16487.5
2Q(28)
0.025;-15580.0
28(2T)
0.018;-16487.5
228Q
0.015;-18550.0
2T(29)
0.021;-16033.8
(29)(2K)
0.034;-11702.5
229J
0.012;-18550.0
2T(2T)
0.038;-12610.0
(2T)(2K)
0.059;-11248.8
22TQ
0.016;-17642.5
2Q(2J)
0.031;-14218.8
2J(2K)
0.027;-13765.0
22QQ
0.032;-13765.0
3(234)
0.007;-21025.0
36(23)
0.009;-20117.5
(23)(39)
0.026;-15786.3
3(23Q)
0.023;-17395.0
5(234)
0.003;-23087.5
9(234)
0.009;-21272.5
K(234)
0.013;-19457.5
4(237)
0.006;-22180.0
49(23)
0.007;-21272.5
(23)(4Q)
0.024;-16941.3
(2357)
0.006;-21726.3
(235J)
0.009;-19911.3
(23)(56)
0.011;-19210.0
5(239)
0.009;-20818.8
5J(23)
0.010;-19911.3
(2367)
0.005;-21272.5
(236J)
0.013;-19457.5
(23)(67)
0.018;-18302.5
6(23T)
0.008;-19911.3
6Q(23)
0.013;-19003.8
9(237)
0.011;-19911.3
K(237)
0.014;-18096.2
7(23T)
0.010;-19457.5
7Q(23)
0.015;-18550.0
T(238)
0.012;-19003.8
8(239)
0.009;-19457.5
8J(23)
0.012;-18550.0
(239T)
0.013;-18550.0
99(23)
0.023;-16033.8
(23)(9Q)
0.032;-14672.5
(23TQ)
0.018;-17188.8
T(23Q)
0.017;-17188.8
Q(23J)
0.021;-16735.0
(23)(JK)
0.046;-13311.3
QK(23)
0.029;-15827.5
23(35)
0.009;-20571.3
33(28)
0.014;-19210.0
233T
0.009;-21272.5
23(3K)
0.020;-16941.3
(24)(36)
0.013;-19663.8
3(249)
0.005;-21272.5
3J(24)
0.007;-20365.0
(34)(25)
0.012;-20117.5
27(34)
0.004;-22180.0
2(34T)
0.007;-20818.8
(34)(2K)
0.027;-16487.5
34(26)
0.005;-22633.8
34(28)
0.006;-21726.3
34(2T)
0.010;-20818.8
34(2Q)
0.012;-19911.3
(25)(35)
0.016;-16693.8
3(258)
0.007;-21272.5
3T(25)
0.009;-20365.0
(25)(3K)
0.025;-16033.8
27(35)
0.006;-21726.3
2(35T)
0.009;-20365.0
(35)(2K)
0.023;-16033.8
35(27)
0.008;-21726.3
35(29)
0.010;-20818.8
35(2J)
0.012;-19911.3
35(2K)
0.012;-19003.8
37(26)
0.008;-21272.5
(26)(3T)
0.024;-16941.3
3(26K)
0.015;-18550.0
2(368)
0.008;-20818.8
(36)(2J)
0.026;-16487.5
2K(36)
0.015;-18550.0
23(68)
0.008;-20818.8
23(6T)
0.012;-19911.3
23(6Q)
0.014;-19003.8
3(278)
0.010;-20365.0
3T(27)
0.010;-19457.5
(27)(3K)
0.035;-15126.2
29(37)
0.009;-19911.3
2(37Q)
0.014;-18550.0
23(78)
0.013;-20365.0
23(7T)
0.013;-19457.5
23(7Q)
0.015;-18550.0
3(289)
0.012;-19457.5
3J(28)
0.013;-18550.0
(38)(29)
0.024;-16487.5
2J(38)
0.015;-18550.0
38(29)
0.011;-19457.5
38(2J)
0.010;-18550.0
38(2K)
0.014;-17642.5
3T(29)
0.014;-18550.0
(29)(3K)
0.025;-14218.8
2J(39)
0.015;-18096.2
39(2T)
0.012;-18550.0
39(2Q)
0.014;-17642.5
(2T)(3T)
0.038;-12156.2
3(2TK)
0.025;-16735.0
2(3TQ)
0.021;-17188.8
23(TJ)
0.015;-17642.5
23(TK)
0.021;-16735.0
(2J)(3K)
0.041;-13311.3
2K(3J)
0.020;-16281.2
23(JK)
0.024;-16281.2
(3Q)(2K)
0.030;-12857.5
(2K)(3K)
0.042;-9433.8
4(246)
0.011;-19210.0
48(24)
0.014;-18302.5
(24)(4J)
0.031;-13971.3
5(245)
0.017;-19210.0
9(245)
0.010;-20365.0
K(245)
0.017;-18550.0
5(248)
0.009;-20818.8
5T(24)
0.013;-19911.3
(24)(5K)
0.025;-15580.0
9(246)
0.011;-19911.3
K(246)
0.014;-18096.2
6(249)
0.009;-19911.3
6J(24)
0.011;-19003.8
(2478)
0.011;-19911.3
(247Q)
0.014;-18096.2
7(249)
0.011;-19457.5
7J(24)
0.016;-18550.0
(2489)
0.013;-19003.8
(248K)
0.017;-17188.8
8T(24)
0.013;-18550.0
(24)(8K)
0.027;-14218.8
Q(249)
0.021;-17188.8
(24)(9J)
0.037;-14672.5
T(24T)
0.027;-14672.5
T(24J)
0.018;-17188.8
TK(24)
0.021;-16281.2
(24)(JQ)
0.032;-13311.3
QQ(24)
0.031;-12857.5
24(45)
0.010;-19663.8
44(28)
0.019;-18302.5
244T
0.009;-20365.0
24(4K)
0.024;-16033.8
(25)(47)
0.014;-18302.5
4(25T)
0.009;-19911.3
4Q(25)
0.013;-19003.8
(45)(27)
0.020;-18302.5
29(45)
0.009;-20365.0
2(45Q)
0.012;-19003.8
24(56)
0.006;-21726.3
24(58)
0.006;-20818.8
24(5T)
0.008;-19911.3
24(5Q)
0.017;-19003.8
4(267)
0.011;-20818.8
49(26)
0.009;-19911.3
(26)(4Q)
0.022;-15580.0
27(46)
0.009;-20818.8
2(46T)
0.014;-19457.5
(46)(2K)
0.028;-15126.2
46(28)
0.009;-20365.0
46(2T)
0.015;-19457.5
46(2Q)
0.013;-18550.0
(27)(47)
0.030;-14425.0
4(27T)
0.012;-19003.8
4Q(27)
0.014;-18096.2
(47)(29)
0.019;-16487.5
2J(47)
0.014;-18550.0
47(28)
0.009;-19911.3
47(2T)
0.013;-19003.8
47(2Q)
0.016;-18096.2
(28)(48)
0.032;-13517.5
4(28J)
0.015;-18096.2
4K(28)
0.018;-17188.8
(48)(2J)
0.029;-15126.2
2K(48)
0.023;-17188.8
24(8T)
0.013;-18550.0
24(8Q)
0.016;-17642.5
4(29T)
0.013;-18096.2
4Q(29)
0.025;-17188.8
(49)(2J)
0.029;-14672.5
2K(49)
0.022;-16735.0
24(9J)
0.017;-17642.5
24(9K)
0.020;-16735.0
(2T)(4Q)
0.031;-13765.0
2J(4T)
0.016;-17188.8
4T(2J)
0.024;-17188.8
4T(2K)
0.020;-16281.2
4Q(2J)
0.023;-16281.2
(4J)(2K)
0.034;-12857.5
4J(2K)
0.027;-15827.5
4K(2Q)
0.031;-15373.8
24(QK)
0.025;-15373.8
(25)(56)
0.034;-15332.5
5(259)
0.015;-16941.3
5J(25)
0.030;-16033.8
(2567)
0.009;-20365.0
(256J)
0.014;-18550.0
(25)(67)
0.018;-17395.0
6(25T)
0.015;-19003.8
6Q(25)
0.020;-18096.2
9(257)
0.016;-19003.8
K(257)
0.015;-17188.8
7(25T)
0.016;-18550.0
7Q(25)
0.015;-17642.5
T(258)
0.017;-18096.2
8(259)
0.017;-18550.0
8J(25)
0.018;-17642.5
(259T)
0.015;-17642.5
99(25)
0.033;-15126.2
(25)(9Q)
0.034;-13765.0
(25TQ)
0.025;-16281.2
T(25Q)
0.026;-16281.2
Q(25J)
0.028;-15827.5
(25)(JK)
0.042;-12403.8
QK(25)
0.027;-14920.0
25(57)
0.013;-17848.8
55(2T)
0.021;-16487.5
255Q
0.014;-18550.0
57(26)
0.009;-20365.0
(26)(5T)
0.023;-16033.8
5(26K)
0.019;-17642.5
2(568)
0.009;-19911.3
(56)(2J)
0.032;-15580.0
2K(56)
0.021;-17642.5
25(68)
0.009;-19911.3
25(6T)
0.011;-19003.8
25(6Q)
0.014;-18096.2
5(278)
0.011;-19457.5
5T(27)
0.012;-18550.0
(27)(5K)
0.032;-14218.8
29(57)
0.009;-19003.8
2(57Q)
0.019;-17642.5
25(78)
0.015;-19457.5
25(7T)
0.019;-18550.0
25(7Q)
0.013;-17642.5
5(289)
0.014;-18550.0
5J(28)
0.014;-17642.5
(58)(29)
0.033;-15580.0
2J(58)
0.020;-17642.5
58(29)
0.014;-18550.0
58(2J)
0.022;-17642.5
58(2K)
0.021;-16735.0
5T(29)
0.020;-17642.5
(29)(5K)
0.039;-13311.3
2J(59)
0.017;-17188.8
59(2T)
0.022;-17642.5
59(2Q)
0.025;-16735.0
(2T)(5T)
0.048;-11248.8
5(2TK)
0.019;-15827.5
2(5TQ)
0.029;-16281.2
25(TJ)
0.024;-16735.0
25(TK)
0.026;-15827.5
(2J)(5K)
0.050;-12403.8
2K(5J)
0.021;-15373.8
25(JK)
0.033;-15373.8
(5Q)(2K)
0.039;-11950.0
(2K)(5K)
0.074;-8526.3
6(268)
0.018;-16487.5
6T(26)
0.021;-15580.0
(26)(6K)
0.044;-11248.8
T(267)
0.016;-18096.2
7(268)
0.014;-19003.8
7T(26)
0.016;-18096.2
(26)(7K)
0.024;-13765.0
J(268)
0.023;-17188.8
89(26)
0.016;-18096.2
(26)(8Q)
0.040;-13765.0
(269J)
0.019;-16735.0
(26)(9T)
0.034;-14218.8
9(26K)
0.026;-15827.5
(26TK)
0.027;-15373.8
TQ(26)
0.027;-15827.5
K(26J)
0.030;-14920.0
Q(26Q)
0.044;-11950.0
KK(26)
0.034;-11042.5
66(29)
0.021;-16033.8
266J
0.014;-18096.2
67(27)
0.020;-16487.5
(27)(6T)
0.027;-15126.2
6(27K)
0.020;-16735.0
2(679)
0.015;-18550.0
(67)(2Q)
0.024;-14218.8
27(68)
0.011;-19003.8
27(6T)
0.015;-18096.2
27(6Q)
0.020;-17188.8
68(28)
0.031;-15580.0
(28)(6J)
0.031;-14218.8
28(68)
0.029;-15580.0
2(68J)
0.014;-17188.8
2688
0.015;-18550.0
268T
0.009;-20612.5
268Q
0.011;-19705.0
(29)(6T)
0.029;-14218.8
6(29K)
0.029;-15827.5
2(69J)
0.024;-16735.0
2699
0.015;-17642.5
269J
0.013;-19705.0
269K
0.012;-18797.5
6Q(2T)
0.020;-15827.5
(6T)(2Q)
0.041;-12857.5
2T(6J)
0.023;-16281.2
2T(6K)
0.026;-15373.8
6(2JK)
0.031;-14920.0
2(6JK)
0.025;-14920.0
2J(6K)
0.023;-14920.0
2Q(6Q)
0.045;-11950.0
26QK
0.013;-17436.2
78(27)
0.032;-15580.0
(27)(7J)
0.048;-11248.8
8(278)
0.032;-15126.2
Q(278)
0.019;-16281.2
(27)(8T)
0.025;-14218.8
8(27K)
0.024;-15827.5
(279Q)
0.029;-15827.5
9(27J)
0.030;-16281.2
9K(27)
0.028;-15373.8
TT(27)
0.030;-13311.2
(27)(TK)
0.041;-11950.0
J(27Q)
0.026;-14920.0
K(27Q)
0.025;-14012.5
77(28)
0.029;-15580.0
277T
0.019;-17642.5
27(7K)
0.034;-13311.2
(28)(7T)
0.024;-14218.8
7(28K)
0.028;-15827.5
2(78T)
0.023;-17188.8
(78)(2K)
0.036;-12857.5
78(2T)
0.018;-17188.8
78(2Q)
0.024;-16281.2
(29)(79)
0.046;-11248.8
7(29Q)
0.026;-15827.5
2(79T)
0.021;-16735.0
(79)(2K)
0.039;-12403.8
79(2J)
0.021;-16281.2
79(2K)
0.021;-15373.8
7J(2T)
0.019;-15827.5
(7T)(2J)
0.043;-12857.5
2K(7T)
0.032;-14920.0
27(TQ)
0.027;-15373.8
7(2JQ)
0.032;-14920.0
2(7JQ)
0.032;-14920.0
27(JQ)
0.028;-14920.0
7(2QK)
0.033;-14012.5
7Q(2K)
0.028;-14012.5
88(28)
0.049;-11702.5
(28)(8J)
0.053;-10341.2
9(289)
0.035;-13765.0
K(289)
0.021;-14920.0
9(28Q)
0.027;-15373.8
J(28T)
0.031;-15373.8
TJ(28)
0.030;-15373.8
(28JQ)
0.026;-14466.2
J(28K)
0.036;-14012.5
(28)(QK)
0.046;-10588.8
88(2T)
0.031;-13765.0
288Q
0.025;-15827.5
8T(29)
0.025;-16281.2
(29)(8K)
0.038;-11950.0
2J(89)
0.029;-15827.5
89(2T)
0.024;-16281.2
89(2Q)
0.030;-15373.8
(2T)(8T)
0.050;-9887.5
8(2TK)
0.027;-14466.2
2(8TQ)
0.028;-14920.0
28(TJ)
0.034;-15373.8
28(TK)
0.033;-14466.2
(2J)(8K)
0.042;-11042.5
2K(8J)
0.027;-14012.5
28(JK)
0.030;-14012.5
(8Q)(2K)
0.052;-10588.8
(2K)(8K)
0.087;-7165.0
9(29J)
0.037;-12403.8
9K(29)
0.038;-11496.2
TT(29)
0.052;-12403.8
(29)(TK)
0.054;-11042.5
J(29Q)
0.035;-14012.5
K(29Q)
0.037;-13105.0
99(2T)
0.029;-12857.5
299Q
0.032;-14920.0
9J(2T)
0.036;-14920.0
(9T)(2J)
0.045;-11950.0
2K(9T)
0.027;-14012.5
29(TQ)
0.032;-14466.2
9(2JQ)
0.028;-14012.5
2(9JQ)
0.029;-14012.5
29(JQ)
0.030;-14012.5
9(2QK)
0.034;-13105.0
9Q(2K)
0.033;-13105.0
TT(2T)
0.076;-8980.0
(2T)(TK)
0.073;-7618.8
J(2TQ)
0.029;-13558.8
K(2TQ)
0.047;-12651.3
TT(2J)
0.056;-11496.2
2TTK
0.040;-13558.8
TK(2J)
0.042;-13105.0
2TJJ
0.027;-14012.5
2TJK
0.020;-16075.0
2(TQK)
0.036;-12651.3
TK(2K)
0.049;-9227.5
(2J)(JK)
0.078;-6711.3
QK(2J)
0.049;-12197.5
2J(JK)
0.060;-9681.3
(JQ)(2K)
0.060;-9227.5
(2K)(JK)
0.086;-5803.7
K(2QK)
0.070;-8320.0
2K(QK)
0.059;-8320.0
3335
0.012;-20117.5
3339
0.015;-18302.5
333K
0.022;-16487.5
36(34)
0.013;-19210.0
(34)(39)
0.028;-14878.8
3(34Q)
0.019;-16487.5
33(45)
0.011;-19663.8
34(38)
0.018;-18302.5
334T
0.008;-20365.0
33(4K)
0.021;-16033.8
(35)(37)
0.027;-15332.5
3(35T)
0.023;-16941.3
3Q(35)
0.022;-16033.8
35(37)
0.014;-18302.5
3359
0.007;-20365.0
33(5Q)
0.024;-16033.8
(36)(37)
0.031;-14878.8
3(36T)
0.026;-16487.5
3Q(36)
0.020;-15580.0
36(38)
0.019;-17395.0
336T
0.009;-19457.5
33(6K)
0.029;-15126.2
(37)(39)
0.032;-13517.5
3(37Q)
0.027;-15126.2
33(78)
0.023;-16941.3
37(3J)
0.024;-15580.0
337K
0.016;-17642.5
3T(38)
0.028;-15580.0
(38)(3K)
0.035;-11248.8
338T
0.018;-18550.0
33(8K)
0.042;-14218.8
(39)(3J)
0.048;-11702.5
3399
0.026;-15580.0
33(9Q)
0.037;-14218.8
(3T)(3J)
0.047;-11248.8
33TT
0.022;-14672.5
33(TK)
0.035;-13311.2
(3J)(3K)
0.058;-9887.5
33JK
0.023;-15827.5
33(QK)
0.039;-12403.8
45(34)
0.013;-19210.0
(34)(48)
0.028;-14878.8
4(34J)
0.020;-16487.5
4K(34)
0.027;-15580.0
(3459)
0.010;-19911.3
(345K)
0.016;-18096.2
57(34)
0.012;-20818.8
(34)(5T)
0.021;-16487.5
5(34K)
0.018;-18096.2
(3469)
0.013;-19457.5
(346K)
0.016;-17642.5
68(34)
0.010;-19911.3
(34)(6J)
0.021;-15580.0
7(347)
0.016;-16941.3
J(347)
0.019;-18096.2
78(34)
0.011;-19457.5
(34)(7J)
0.029;-15126.2
8(348)
0.023;-16033.8
Q(348)
0.025;-17188.8
(34)(8T)
0.022;-15126.2
8(34K)
0.026;-16735.0
(349Q)
0.026;-16735.0
9(34J)
0.018;-17188.8
9K(34)
0.022;-16281.2
TT(34)
0.031;-14218.8
(34)(TK)
0.033;-12857.5
J(34Q)
0.023;-15827.5
K(34Q)
0.027;-14920.0
44(35)
0.010;-19210.0
3447
0.009;-21272.5
34(4T)
0.016;-16941.3
44(3K)
0.020;-15580.0
4(357)
0.009;-20818.8
49(35)
0.014;-19911.3
(35)(4Q)
0.028;-15580.0
36(45)
0.007;-21272.5
3(459)
0.014;-19911.3
(45)(3Q)
0.022;-15580.0
35(46)
0.010;-21272.5
35(48)
0.007;-20365.0
35(4T)
0.013;-19457.5
35(4Q)
0.015;-18550.0
46(36)
0.018;-17848.8
(36)(49)
0.027;-16487.5
4(36Q)
0.021;-18096.2
3(467)
0.011;-20365.0
(46)(3T)
0.021;-16033.8
3Q(46)
0.015;-18096.2
3467
0.003;-23335.0
3469
0.006;-22427.5
346J
0.006;-21520.0
346K
0.010;-20612.5
49(37)
0.016;-19003.8
(37)(4Q)
0.035;-14672.5
38(47)
0.013;-19457.5
3(47J)
0.014;-18096.2
3477
0.009;-19911.3
3479
0.005;-21973.8
347J
0.007;-21066.2
347K
0.008;-20158.8
4T(38)
0.015;-18096.2
(38)(4K)
0.031;-13765.0
3T(48)
0.012;-18096.2
3(48K)
0.018;-16735.0
38(4T)
0.014;-18096.2
38(4Q)
0.020;-17188.8
49(39)
0.024;-15126.2
(39)(4Q)
0.031;-13765.0
3T(49)
0.014;-17642.5
3(49K)
0.020;-16281.2
39(4J)
0.020;-17188.8
39(4K)
0.023;-16281.2
4(3TQ)
0.017;-16281.2
3(4TJ)
0.023;-16735.0
34TT
0.019;-17188.8
34TQ
0.014;-19251.2
(3J)(4Q)
0.035;-12857.5
3Q(4J)
0.021;-15827.5
34JQ
0.013;-18797.5
(3Q)(4K)
0.038;-11950.0
3Q(4K)
0.031;-14920.0
5(356)
0.016;-17848.8
58(35)
0.019;-16941.3
(35)(5J)
0.039;-12610.0
6(356)
0.016;-17395.0
T(356)
0.016;-18550.0
6(357)
0.012;-19911.3
69(35)
0.011;-19003.8
(35)(6Q)
0.032;-14672.5
(3579)
0.015;-18550.0
(357K)
0.026;-16735.0
79(35)
0.015;-18550.0
(35)(7Q)
0.037;-14218.8
(358T)
0.017;-17642.5
88(35)
0.021;-15580.0
(35)(8J)
0.026;-14218.8
9(359)
0.024;-14672.5
K(359)
0.030;-15827.5
9(35Q)
0.020;-16281.2
J(35T)
0.027;-16281.2
TJ(35)
0.020;-16281.2
(35JQ)
0.024;-15373.8
J(35K)
0.032;-14920.0
(35)(QK)
0.042;-11496.2
55(37)
0.021;-17395.0
3559
0.010;-19457.5
35(5Q)
0.028;-15126.2
(36)(57)
0.024;-16941.3
5(36T)
0.013;-18550.0
5Q(36)
0.016;-17642.5
(56)(38)
0.022;-16487.5
3T(56)
0.013;-18550.0
3(56K)
0.025;-17188.8
36(58)
0.015;-19457.5
36(5T)
0.014;-18550.0
36(5Q)
0.016;-17642.5
57(37)
0.022;-16487.5
(37)(5T)
0.026;-15126.2
5(37K)
0.023;-16735.0
3(579)
0.012;-18550.0
(57)(3Q)
0.029;-14218.8
37(58)
0.010;-19003.8
37(5T)
0.013;-18096.2
37(5Q)
0.021;-17188.8
58(38)
0.027;-15580.0
(38)(5J)
0.026;-14218.8
38(58)
0.025;-15580.0
3(58J)
0.026;-17188.8
3588
0.017;-18550.0
358T
0.010;-20612.5
358Q
0.008;-19705.0
(39)(5T)
0.025;-14218.8
5(39K)
0.026;-15827.5
3(59J)
0.024;-16735.0
3599
0.022;-17642.5
359J
0.010;-19705.0
359K
0.017;-18797.5
5Q(3T)
0.025;-15827.5
(5T)(3Q)
0.037;-12857.5
3T(5J)
0.017;-16281.2
3T(5K)
0.030;-15373.8
5(3JK)
0.025;-14920.0
3(5JK)
0.031;-14920.0
3J(5K)
0.033;-14920.0
3Q(5Q)
0.036;-11950.0
35QK
0.024;-17436.2
67(36)
0.022;-16487.5
(36)(6T)
0.033;-12156.2
6(36K)
0.040;-13765.0
(367T)
0.021;-17642.5
77(36)
0.031;-16033.8
(36)(7T)
0.037;-14672.5
7(36K)
0.021;-16281.2
(368J)
0.019;-16735.0
(36)(89)
0.031;-14672.5
8(36Q)
0.029;-16281.2
T(369)
0.019;-16735.0
9(36T)
0.027;-16735.0
9Q(36)
0.026;-15827.5
Q(36T)
0.029;-15373.8
(36)(TQ)
0.039;-12403.8
(36JK)
0.028;-14466.2
JK(36)
0.026;-14466.2
K(36K)
0.063;-10588.8
3668
0.012;-19003.8
36(6J)
0.026;-14672.5
(37)(67)
0.037;-13063.8
6(37T)
0.019;-17642.5
6Q(37)
0.025;-16735.0
(67)(39)
0.030;-15126.2
3J(67)
0.015;-17188.8
67(38)
0.015;-18550.0
67(3T)
0.019;-17642.5
67(3Q)
0.017;-16735.0
(38)(68)
0.052;-12156.2
6(38J)
0.023;-16735.0
6K(38)
0.025;-15827.5
(68)(3J)
0.031;-13765.0
3K(68)
0.024;-15827.5
36(8T)
0.020;-17188.8
36(8Q)
0.023;-16281.2
6(39T)
0.017;-16735.0
6Q(39)
0.018;-15827.5
(69)(3J)
0.037;-13311.3
3K(69)
0.028;-15373.8
36(9J)
0.024;-16281.2
36(9K)
0.026;-15373.8
(3T)(6Q)
0.040;-12403.8
3J(6T)
0.027;-15827.5
6T(3J)
0.027;-15827.5
6T(3K)
0.026;-14920.0
6Q(3J)
0.025;-14920.0
(6J)(3K)
0.051;-11496.2
6J(3K)
0.022;-14466.2
6K(3Q)
0.026;-14012.5
36(QK)
0.031;-14012.5
(37)(78)
0.040;-12156.2
7(37J)
0.032;-13765.0
7K(37)
0.032;-12857.5
(378Q)
0.022;-15827.5
8(37T)
0.026;-16735.0
8Q(37)
0.023;-15827.5
J(379)
0.026;-15827.5
9T(37)
0.024;-16281.2
(37)(9K)
0.047;-11950.0
K(37T)
0.029;-14466.2
T(37K)
0.029;-14466.2
JJ(37)
0.034;-11950.0
(37QK)
0.029;-13558.8
3777
0.024;-15580.0
37(7T)
0.025;-14218.8
77(3K)
0.029;-12857.5
7(38T)
0.022;-16735.0
7Q(38)
0.025;-15827.5
(78)(3T)
0.039;-13765.0
3Q(78)
0.017;-15827.5
3789
0.011;-20158.8
378J
0.010;-19251.2
378K
0.014;-18343.8
7J(39)
0.021;-15827.5
(79)(3T)
0.037;-13311.3
3Q(79)
0.029;-15373.8
379T
0.010;-19251.2
379Q
0.014;-18343.8
(3T)(7J)
0.050;-12403.8
3T(7T)
0.031;-12857.5
3(7TK)
0.029;-14466.2
3T(7Q)
0.028;-14920.0
7J(3J)
0.039;-11950.0
(7J)(3Q)
0.042;-11496.2
3J(7Q)
0.029;-14466.2
7Q(3Q)
0.047;-11042.5
37QQ
0.039;-14012.5
37KK
0.035;-13105.0
8(38J)
0.034;-12857.5
8K(38)
0.036;-11950.0
(389K)
0.025;-14466.2
9J(38)
0.027;-15373.8
(38TJ)
0.028;-14920.0
(38)(TJ)
0.036;-11950.0
J(38J)
0.037;-11496.2
JQ(38)
0.023;-14012.5
Q(38K)
0.029;-13105.0
3889
0.019;-16735.0
38(8Q)
0.040;-12403.8
(39)(8T)
0.044;-12857.5
8(39K)
0.028;-14466.2
3(89J)
0.019;-15373.8
3899
0.023;-16281.2
389J
0.012;-18343.8
389K
0.018;-17436.2
8Q(3T)
0.033;-14466.2
(8T)(3Q)
0.036;-11496.2
3T(8J)
0.025;-14920.0
3T(8K)
0.043;-14012.5
8(3JK)
0.034;-13558.8
3(8JK)
0.031;-13558.8
3J(8K)
0.028;-13558.8
3Q(8Q)
0.057;-10588.8
38QK
0.022;-16075.0
9T(39)
0.040;-12403.8
(39)(9K)
0.073;-8072.5
K(39T)
0.033;-13558.8
T(39K)
0.045;-13558.8
JJ(39)
0.052;-11042.5
(39QK)
0.049;-12651.3
3999
0.032;-12857.5
39(9Q)
0.047;-11496.2
(3T)(9J)
0.062;-11496.2
3T(9T)
0.053;-11950.0
3(9TK)
0.039;-13558.8
3T(9Q)
0.038;-14012.5
9J(3J)
0.039;-11042.5
(9J)(3Q)
0.063;-10588.8
3J(9Q)
0.032;-13558.8
9Q(3Q)
0.039;-10135.0
39QQ
0.036;-13105.0
39KK
0.044;-12197.5
T(3TK)
0.065;-10135.0
JJ(3T)
0.065;-10588.8
(3TQK)
0.037;-12197.5
3TTT
0.051;-11496.2
3T(TK)
0.061;-10135.0
(3J)(TK)
0.064;-9681.3
3K(TJ)
0.039;-12651.3
3T(JK)
0.042;-12651.3
(TQ)(3K)
0.057;-9227.5
(3K)(TK)
0.088;-5803.7
J(3JK)
0.076;-9227.5
(3J)(QK)
0.072;-8773.8
JJ(3K)
0.053;-9227.5
3Q(JQ)
0.052;-9227.5
3JQK
0.035;-14713.8
QK(3Q)
0.054;-8320.0
QK(3K)
0.076;-7866.2
44(46)
0.027;-15332.5
44(4T)
0.035;-13517.5
(45)(45)
0.037;-12362.5
4(458)
0.021;-16941.3
4T(45)
0.021;-16033.8
(45)(4K)
0.041;-11702.5
4457
0.011;-20365.0
44(5T)
0.025;-16033.8
45(4K)
0.031;-14672.5
4(468)
0.019;-16487.5
4T(46)
0.026;-15580.0
(46)(4K)
0.064;-11248.8
4468
0.011;-19457.5
44(6J)
0.031;-15126.2
(47)(47)
0.052;-10547.5
4(47T)
0.030;-15126.2
4Q(47)
0.026;-14218.8
47(49)
0.030;-15580.0
447J
0.020;-17642.5
48(48)
0.034;-12610.0
(48)(4J)
0.053;-11248.8
4488
0.023;-15580.0
44(8J)
0.031;-14218.8
(49)(49)
0.083;-8732.5
4(49Q)
0.037;-13311.2
44(9T)
0.027;-14218.8
49(4K)
0.031;-12857.5
4(4TQ)
0.032;-12857.5
44(TJ)
0.041;-13311.2
(4J)(4J)
0.074;-6917.5
44JJ
0.041;-12857.5
4Q(4Q)
0.066;-8980.0
(4K)(4K)
0.108;-5102.5
(45)(57)
0.026;-13971.3
5(45T)
0.020;-15580.0
5Q(45)
0.033;-14672.5
8(456)
0.014;-19003.8
Q(456)
0.022;-17188.8
(45)(68)
0.027;-16033.8
6(45J)
0.017;-17642.5
6K(45)
0.024;-16735.0
(457J)
0.015;-17188.8
(45)(78)
0.033;-15580.0
7(45J)
0.020;-17188.8
7K(45)
0.017;-16281.2
(458Q)
0.026;-16281.2
8(45T)
0.017;-17188.8
8Q(45)
0.025;-16281.2
J(459)
0.025;-16281.2
9T(45)
0.022;-16735.0
(45)(9K)
0.036;-12403.8
K(45T)
0.030;-14920.0
T(45K)
0.034;-14920.0
JJ(45)
0.033;-12403.8
(45QK)
0.033;-14012.5
4555
0.016;-17848.8
45(58)
0.022;-16487.5
55(4J)
0.028;-15126.2
455K
0.020;-17188.8
58(46)
0.010;-19003.8
(46)(5J)
0.039;-14672.5
46(56)
0.022;-16941.3
4(569)
0.014;-18550.0
(56)(4Q)
0.027;-14218.8
46(57)
0.011;-19457.5
46(59)
0.014;-18550.0
46(5J)
0.017;-17642.5
46(5K)
0.019;-16735.0
5(479)
0.012;-18096.2
5J(47)
0.023;-17188.8
(57)(48)
0.026;-15580.0
4T(57)
0.020;-17642.5
4(57K)
0.027;-16281.2
47(59)
0.014;-18096.2
47(5J)
0.025;-17188.8
47(5K)
0.023;-16281.2
5(48T)
0.017;-17188.8
5Q(48)
0.025;-16281.2
(58)(4T)
0.031;-14218.8
4Q(58)
0.018;-16281.2
4589
0.010;-20612.5
458J
0.014;-19705.0
458K
0.014;-18797.5
5J(49)
0.022;-16281.2
(59)(4T)
0.027;-13765.0
4Q(59)
0.024;-15827.5
459T
0.011;-19705.0
459Q
0.011;-18797.5
(4T)(5J)
0.045;-12857.5
4T(5T)
0.037;-13311.2
4(5TK)
0.026;-14920.0
4T(5Q)
0.023;-15373.8
5J(4J)
0.040;-12403.8
(5J)(4Q)
0.042;-11950.0
4J(5Q)
0.025;-14920.0
5Q(4Q)
0.042;-11496.2
45QQ
0.039;-14466.2
45KK
0.037;-13558.8
6(469)
0.020;-15126.2
6J(46)
0.025;-14218.8
(4678)
0.012;-18096.2
(467Q)
0.029;-16281.2
7(469)
0.022;-17642.5
7J(46)
0.020;-16735.0
(4689)
0.023;-17188.8
(468K)
0.025;-15373.8
8T(46)
0.018;-16735.0
(46)(8K)
0.044;-12403.8
Q(469)
0.020;-15373.8
(46)(9J)
0.051;-12857.5
T(46T)
0.053;-12857.5
T(46J)
0.027;-15373.8
TK(46)
0.033;-14466.2
(46)(JQ)
0.054;-11496.2
QQ(46)
0.045;-11042.5
46(67)
0.024;-16033.8
66(4T)
0.024;-14672.5
466Q
0.018;-16735.0
68(47)
0.020;-18096.2
(47)(6J)
0.033;-13765.0
47(67)
0.027;-15580.0
4(67T)
0.021;-17188.8
(67)(4K)
0.038;-12857.5
67(49)
0.014;-17642.5
67(4J)
0.021;-16735.0
67(4K)
0.028;-15827.5
69(48)
0.017;-17188.8
(48)(6Q)
0.032;-12857.5
49(68)
0.019;-17188.8
4(68Q)
0.021;-15827.5
46(89)
0.022;-17188.8
46(8J)
0.018;-16281.2
46(8K)
0.028;-15373.8
(49)(6J)
0.032;-12857.5
49(69)
0.026;-13765.0
4(69Q)
0.025;-15373.8
46(9T)
0.023;-16281.2
46(9Q)
0.026;-15373.8
6(4TJ)
0.023;-15373.8
6K(4T)
0.029;-14466.2
(6T)(4K)
0.042;-11496.2
6T(4Q)
0.029;-14920.0
(4J)(6J)
0.061;-8980.0
4J(6J)
0.047;-11950.0
6J(4Q)
0.030;-14466.2
(4Q)(6Q)
0.078;-8072.5
4K(6Q)
0.035;-13558.8
4K(6K)
0.053;-10135.0
79(47)
0.030;-14218.8
(47)(7Q)
0.060;-9887.5
(478T)
0.020;-16281.2
88(47)
0.034;-14218.8
(47)(8J)
0.044;-12857.5
9(479)
0.035;-13311.2
K(479)
0.030;-14466.2
9(47Q)
0.029;-14920.0
J(47T)
0.027;-14920.0
TJ(47)
0.024;-14920.0
(47JQ)
0.030;-14012.5
J(47K)
0.027;-13558.8
(47)(QK)
0.066;-10135.0
77(49)
0.037;-14218.8
477J
0.020;-16281.2
78(48)
0.024;-14218.8
(48)(7J)
0.036;-12857.5
48(78)
0.029;-14218.8
4(78J)
0.017;-15827.5
4788
0.017;-17188.8
478T
0.015;-19251.2
478Q
0.015;-18343.8
(49)(7T)
0.037;-12857.5
7(49K)
0.032;-14466.2
4(79J)
0.031;-15373.8
4799
0.023;-16281.2
479J
0.017;-18343.8
479K
0.014;-17436.2
7Q(4T)
0.030;-14466.2
(7T)(4Q)
0.042;-11496.2
4T(7J)
0.027;-14920.0
4T(7K)
0.028;-14012.5
7(4JK)
0.032;-13558.8
4(7JK)
0.034;-13558.8
4J(7K)
0.034;-13558.8
4Q(7Q)
0.051;-10588.8
47QK
0.022;-16075.0
89(48)
0.030;-13311.2
(48)(8Q)
0.066;-8980.0
(489J)
0.034;-14920.0
(48)(9T)
0.044;-12403.8
9(48K)
0.026;-14012.5
(48TK)
0.031;-13558.8
TQ(48)
0.039;-14012.5
K(48J)
0.041;-13105.0
Q(48Q)
0.045;-10135.0
KK(48)
0.055;-9227.5
88(4J)
0.029;-12403.8
488K
0.028;-14466.2
8J(49)
0.022;-14920.0
(89)(4T)
0.045;-12403.8
4Q(89)
0.026;-14466.2
489T
0.017;-18343.8
489Q
0.020;-17436.2
(4T)(8J)
0.054;-11496.2
4T(8T)
0.046;-11950.0
4(8TK)
0.030;-13558.8
4T(8Q)
0.031;-14012.5
8J(4J)
0.048;-11042.5
(8J)(4Q)
0.051;-10588.8
4J(8Q)
0.038;-13558.8
8Q(4Q)
0.049;-10135.0
48QQ
0.032;-13105.0
48KK
0.037;-12197.5
9(49Q)
0.051;-11042.5
J(49T)
0.039;-14012.5
TJ(49)
0.023;-14012.5
(49JQ)
0.043;-13105.0
J(49K)
0.035;-12651.3
(49)(QK)
0.076;-9227.5
99(4J)
0.055;-11496.2
499K
0.035;-13558.8
9Q(4T)
0.038;-13558.8
(9T)(4Q)
0.048;-10588.8
4T(9J)
0.024;-14012.5
4T(9K)
0.047;-13105.0
9(4JK)
0.044;-12651.3
4(9JK)
0.034;-12651.3
4J(9K)
0.033;-12651.3
4Q(9Q)
0.045;-9681.3
49QK
0.032;-15167.5
TJ(4T)
0.042;-10588.8
(4TJQ)
0.039;-12651.3
J(4TK)
0.043;-12197.5
(4T)(QK)
0.071;-8773.8
TT(4Q)
0.049;-10135.0
T(4JQ)
0.041;-12651.3
4(TJQ)
0.044;-12651.3
4T(JQ)
0.041;-12651.3
T(4QK)
0.057;-11743.7
TQ(4K)
0.046;-11743.7
JJ(4J)
0.090;-6711.3
(4JQK)
0.050;-11290.0
4JJJ
0.056;-9681.3
JQ(4Q)
0.068;-8773.8
4JQQ
0.033;-11743.7
4JKK
0.042;-10836.2
QQ(4K)
0.065;-7866.2
4KKK
0.075;-6958.8
55(59)
0.047;-12610.0
55(5K)
0.050;-10795.0
(56)(58)
0.045;-12610.0
5(56J)
0.036;-14218.8
5K(56)
0.038;-13311.2
56(59)
0.032;-15126.2
556J
0.023;-17188.8
57(57)
0.041;-12610.0
(57)(5T)
0.051;-11248.8
5(57K)
0.035;-12857.5
55(79)
0.029;-14672.5
57(5Q)
0.031;-13311.2
5(589)
0.029;-14218.8
5J(58)
0.032;-13311.2
58(59)
0.032;-14218.8
558J
0.027;-16281.2
59(59)
0.044;-10795.0
(59)(5Q)
0.060;-9433.8
559T
0.029;-16281.2
55(9K)
0.045;-11950.0
(5T)(5Q)
0.074;-8980.0
55TJ
0.025;-15373.8
5J(5J)
0.078;-8980.0
5J(5Q)
0.037;-11496.2
5(5QK)
0.056;-10588.8
5K(5K)
0.092;-7165.0
68(56)
0.023;-15126.2
(56)(6J)
0.042;-10795.0
7(567)
0.025;-15126.2
J(567)
0.023;-16281.2
78(56)
0.018;-17642.5
(56)(7J)
0.037;-13311.3
8(568)
0.036;-14218.8
Q(568)
0.026;-15373.8
(56)(8T)
0.035;-13311.3
8(56K)
0.027;-14920.0
(569Q)
0.023;-14920.0
9(56J)
0.028;-15373.8
9K(56)
0.039;-14466.2
TT(56)
0.043;-12403.8
(56)(TK)
0.061;-11042.5
J(56Q)
0.028;-14012.5
K(56Q)
0.030;-13105.0
66(57)
0.028;-15580.0
5669
0.014;-17642.5
56(6Q)
0.034;-13311.2
(57)(68)
0.022;-14672.5
6(57J)
0.017;-16281.2
6K(57)
0.030;-15373.8
(67)(5T)
0.030;-13765.0
5Q(67)
0.026;-15827.5
5678
0.007;-20612.5
567T
0.012;-19705.0
567Q
0.014;-18797.5
(58)(69)
0.031;-13765.0
6(58Q)
0.024;-15373.8
5(689)
0.024;-16735.0
(68)(5Q)
0.036;-12403.8
58(69)
0.021;-16735.0
58(6J)
0.027;-15827.5
58(6K)
0.028;-14920.0
6(59J)
0.027;-15373.8
6K(59)
0.026;-14466.2
(69)(5Q)
0.041;-11950.0
59(6T)
0.028;-15827.5
59(6Q)
0.028;-14920.0
6T(5T)
0.047;-12403.8
(5T)(6K)
0.038;-11042.5
5Q(6T)
0.026;-14466.2
56TJ
0.016;-17890.0
56TK
0.017;-16982.5
6K(5J)
0.029;-13558.8
56JJ
0.033;-14466.2
56JK
0.019;-16528.8
5(6QK)
0.029;-13105.0
6K(5K)
0.058;-9681.3
(57)(79)
0.044;-10795.0
7(57Q)
0.031;-12403.8
9(578)
0.021;-16281.2
K(578)
0.026;-14466.2
8(57J)
0.022;-15373.8
8K(57)
0.028;-14466.2
(579K)
0.029;-14012.5
9J(57)
0.032;-14920.0
(57TJ)
0.026;-14466.2
(57)(TJ)
0.045;-11496.2
J(57J)
0.041;-11042.5
JQ(57)
0.048;-13558.8
Q(57K)
0.028;-12651.3
5778
0.017;-17188.8
57(7J)
0.037;-12857.5
(58)(78)
0.040;-10795.0
7(58J)
0.023;-15373.8
7K(58)
0.036;-14466.2
(78)(5J)
0.033;-12403.8
5K(78)
0.041;-14466.2
57(8T)
0.023;-15827.5
57(8Q)
0.033;-14920.0
7(59T)
0.031;-15373.8
7Q(59)
0.025;-14466.2
(79)(5J)
0.053;-11950.0
5K(79)
0.031;-14012.5
57(9J)
0.026;-14920.0
57(9K)
0.030;-14012.5
(5T)(7Q)
0.043;-11042.5
5J(7T)
0.028;-14466.2
7T(5J)
0.024;-14466.2
7T(5K)
0.043;-13558.8
7Q(5J)
0.029;-13558.8
(7J)(5K)
0.048;-10135.0
7J(5K)
0.050;-13105.0
7K(5Q)
0.042;-12651.3
57(QK)
0.033;-12651.3
(58)(89)
0.055;-9887.5
8(58Q)
0.037;-11496.2
T(589)
0.029;-14920.0
9(58T)
0.025;-14920.0
9Q(58)
0.027;-14012.5
Q(58T)
0.037;-13558.8
(58)(TQ)
0.056;-10588.8
(58JK)
0.039;-12651.3
JK(58)
0.047;-12651.3
K(58K)
0.052;-8773.8
588T
0.026;-15373.8
58(8K)
0.049;-11042.5
(59)(8J)
0.044;-11496.2
59(89)
0.047;-12403.8
5(89Q)
0.032;-14012.5
58(9T)
0.025;-14920.0
58(9Q)
0.031;-14012.5
8(5TJ)
0.037;-14012.5
8K(5T)
0.031;-13105.0
(8T)(5K)
0.068;-10135.0
8T(5Q)
0.039;-13558.8
(5J)(8J)
0.059;-7618.8
5J(8J)
0.040;-10588.8
8J(5Q)
0.039;-13105.0
(5Q)(8Q)
0.080;-6711.3
5K(8Q)
0.041;-12197.5
5K(8K)
0.071;-8773.8
9J(59)
0.050;-11042.5
(59TJ)
0.041;-13558.8
(59)(TJ)
0.054;-10588.8
J(59J)
0.054;-10135.0
JQ(59)
0.042;-12651.3
Q(59K)
0.046;-11743.7
599T
0.034;-14466.2
59(9K)
0.052;-10135.0
(5T)(9Q)
0.048;-10135.0
5J(9T)
0.032;-13558.8
9T(5J)
0.036;-13558.8
9T(5K)
0.047;-12651.3
9Q(5J)
0.032;-12651.3
(9J)(5K)
0.055;-9227.5
9J(5K)
0.044;-12197.5
9K(5Q)
0.049;-11743.7
59(QK)
0.036;-11743.7
(5T)(TJ)
0.074;-7165.0
J(5TJ)
0.060;-9681.3
JQ(5T)
0.047;-12197.5
Q(5TK)
0.057;-11290.0
5TTJ
0.046;-13105.0
TJ(5J)
0.043;-9681.3
(TJ)(5Q)
0.059;-9227.5
5J(TQ)
0.034;-12197.5
TQ(5Q)
0.071;-8773.8
5TQQ
0.037;-11743.7
5TKK
0.040;-10836.2
Q(5JQ)
0.067;-8320.0
KK(5J)
0.059;-7412.5
(5Q)(JQ)
0.123;-5350.0
5K(JQ)
0.042;-10836.2
5K(JK)
0.064;-7412.5
5QQQ
0.078;-7866.2
KK(5K)
0.110;-3535.0
6669
0.033;-14218.8
666K
0.036;-12403.8
69(67)
0.028;-13765.0
(67)(6Q)
0.066;-9433.8
6678
0.018;-17188.8
66(7J)
0.030;-12857.5
(68)(68)
0.066;-7825.0
6(68J)
0.039;-12403.8
6K(68)
0.050;-11496.2
68(6J)
0.042;-12403.8
668K
0.033;-14466.2
6J(69)
0.057;-11950.0
69(6T)
0.041;-12403.8
669Q
0.034;-14466.2
6J(6T)
0.043;-11496.2
6T(6J)
0.050;-11496.2
66TK
0.032;-13558.8
6K(6J)
0.055;-10135.0
(6Q)(6Q)
0.074;-4195.0
66QK
0.048;-12651.3
7(679)
0.038;-13311.2
7J(67)
0.039;-12403.8
(6789)
0.026;-15827.5
(678K)
0.035;-14012.5
8T(67)
0.023;-15373.8
(67)(8K)
0.045;-11042.5
Q(679)
0.038;-14012.5
(67)(9J)
0.044;-11496.2
T(67T)
0.042;-11496.2
T(67J)
0.033;-14012.5
TK(67)
0.035;-13105.0
(67)(JQ)
0.057;-10135.0
QQ(67)
0.064;-9681.3
67(78)
0.025;-13765.0
77(6J)
0.043;-12403.8
677K
0.036;-14466.2
7T(68)
0.034;-15373.8
(68)(7K)
0.055;-11042.5
6T(78)
0.025;-15373.8
6(78K)
0.028;-14012.5
68(7T)
0.022;-15373.8
68(7Q)
0.037;-14466.2
79(69)
0.033;-12403.8
(69)(7Q)
0.065;-11042.5
6T(79)
0.027;-14920.0
6(79K)
0.036;-13558.8
69(7J)
0.037;-14466.2
69(7K)
0.038;-13558.8
7(6TQ)
0.034;-13558.8
6(7TJ)
0.040;-14012.5
67TT
0.031;-14466.2
67TQ
0.021;-16528.8
(6J)(7Q)
0.053;-10135.0
6Q(7J)
0.040;-13105.0
67JQ
0.028;-16075.0
(6Q)(7K)
0.061;-9227.5
6Q(7K)
0.042;-12197.5
8(689)
0.051;-12403.8
8J(68)
0.045;-11496.2
(689T)
0.031;-14466.2
99(68)
0.043;-11950.0
(68)(9Q)
0.066;-10588.8
(68TQ)
0.038;-13105.0
T(68Q)
0.041;-13105.0
Q(68J)
0.047;-12651.3
(68)(JK)
0.068;-9227.5
QK(68)
0.048;-11743.7
68(8T)
0.042;-11950.0
88(6K)
0.046;-10588.8
8(69J)
0.027;-14012.5
8K(69)
0.030;-13105.0
(89)(6Q)
0.049;-10588.8
69(8T)
0.027;-14466.2
69(8Q)
0.034;-13558.8
8T(6T)
0.060;-11042.5
(6T)(8K)
0.059;-9681.3
6Q(8T)
0.035;-13105.0
68TJ
0.018;-16528.8
68TK
0.024;-15621.3
8K(6J)
0.053;-12197.5
68JJ
0.031;-13105.0
68JK
0.024;-15167.5
6(8QK)
0.047;-11743.7
8K(6K)
0.063;-8320.0
(69)(9J)
0.055;-7618.8
T(69T)
0.057;-10588.8
T(69J)
0.031;-13105.0
TK(69)
0.040;-12197.5
(69)(JQ)
0.052;-9227.5
QQ(69)
0.067;-8773.8
69(9T)
0.046;-11042.5
99(6K)
0.052;-9681.3
9(6TQ)
0.040;-12651.3
6(9TJ)
0.033;-13105.0
69TT
0.028;-13558.8
69TQ
0.019;-15621.3
(6J)(9Q)
0.050;-9227.5
6Q(9J)
0.038;-12197.5
69JQ
0.036;-15167.5
(6Q)(9K)
0.058;-8320.0
6Q(9K)
0.041;-11290.0
T(6TJ)
0.076;-9681.3
TK(6T)
0.055;-8773.8
(6T)(JQ)
0.080;-8773.8
QQ(6T)
0.072;-8320.0
6T(TJ)
0.054;-9681.3
(6J)(TJ)
0.072;-6257.5
6J(TJ)
0.062;-9227.5
TJ(6Q)
0.039;-11743.7
(6Q)(TQ)
0.077;-5350.0
6K(TQ)
0.049;-10836.2
6K(TK)
0.078;-7412.5
JK(6J)
0.052;-7866.2
K(6JK)
0.084;-6958.8
6JJK
0.060;-10836.2
6(JQK)
0.048;-10382.5
JK(6K)
0.082;-6958.8
KK(6Q)
0.089;-6505.0
6QKK
0.062;-9475.0
77(7T)
0.048;-9433.8
(78)(78)
0.066;-6917.5
7(78J)
0.050;-11496.2
7K(78)
0.059;-10588.8
78(7J)
0.045;-11496.2
778K
0.042;-13558.8
7J(79)
0.053;-11042.5
79(7T)
0.051;-11496.2
779Q
0.035;-13558.8
7J(7T)
0.048;-10588.8
7T(7J)
0.042;-10588.8
77TK
0.043;-12651.3
7K(7J)
0.056;-9227.5
(7Q)(7Q)
0.096;-3287.5
77QK
0.046;-11743.7
8(78T)
0.037;-11496.2
8Q(78)
0.059;-10588.8
J(789)
0.044;-13558.8
9T(78)
0.031;-14012.5
(78)(9K)
0.048;-9681.3
K(78T)
0.039;-12197.5
T(78K)
0.054;-12197.5
JJ(78)
0.046;-9681.3
(78QK)
0.059;-11290.0
7888
0.033;-12403.8
78(8J)
0.054;-11042.5
(79)(89)
0.065;-8526.3
8(79Q)
0.027;-13105.0
7(89T)
0.028;-14012.5
(89)(7K)
0.057;-9681.3
89(7J)
0.032;-13558.8
89(7K)
0.035;-12651.3
8J(7T)
0.031;-13105.0
(8T)(7J)
0.067;-10135.0
7K(8T)
0.036;-12197.5
78(TQ)
0.037;-12651.3
8(7JQ)
0.037;-12197.5
7(8JQ)
0.031;-12197.5
78(JQ)
0.044;-12197.5
8(7QK)
0.046;-11290.0
8Q(7K)
0.048;-11290.0
99(79)
0.068;-8072.5
(79)(9Q)
0.074;-6711.3
(79TQ)
0.049;-12197.5
T(79Q)
0.036;-12197.5
Q(79J)
0.041;-11743.7
(79)(JK)
0.070;-8320.0
QK(79)
0.048;-10836.2
79(9J)
0.055;-10135.0
(7T)(9T)
0.082;-7165.0
9(7TK)
0.039;-11743.7
7(9TQ)
0.035;-12197.5
79(TJ)
0.045;-12651.3
79(TK)
0.051;-11743.7
(7J)(9K)
0.062;-8320.0
7K(9J)
0.047;-11290.0
79(JK)
0.041;-11290.0
(9Q)(7K)
0.081;-7866.2
(7K)(9K)
0.113;-4442.5
T(7TQ)
0.052;-8773.8
Q(7TJ)
0.037;-11290.0
(7T)(JK)
0.076;-7866.2
QK(7T)
0.038;-10382.5
7T(TQ)
0.057;-8773.8
(7J)(TQ)
0.057;-8320.0
7Q(TJ)
0.052;-11290.0
7TJQ
0.024;-14260.0
(7Q)(TK)
0.074;-7412.5
7Q(TK)
0.056;-10382.5
J(7JQ)
0.075;-7866.2
K(7JQ)
0.065;-9928.8
JJ(7Q)
0.062;-7866.2
J(7QK)
0.068;-9928.8
JQ(7K)
0.049;-9928.8
QQ(7Q)
0.102;-3988.8
7Q(QK)
0.100;-6505.0
8888
0.087;-8980.0
888Q
0.050;-10135.0
8(89J)
0.055;-10135.0
8K(89)
0.057;-9227.5
89(8Q)
0.065;-9681.3
8(8TJ)
0.056;-9681.3
8K(8T)
0.064;-8773.8
8T(8K)
0.048;-8773.8
8(8JK)
0.070;-8320.0
88(JK)
0.073;-8320.0
8Q(8K)
0.062;-7866.2
(89)(9T)
0.072;-7165.0
9(89K)
0.075;-8773.8
(89TK)
0.044;-11290.0
TQ(89)
0.042;-11743.7
K(89J)
0.042;-10836.2
Q(89Q)
0.057;-7866.2
KK(89)
0.087;-6958.8
99(8Q)
0.056;-9227.5
9(8TJ)
0.040;-12197.5
9K(8T)
0.052;-11290.0
(9T)(8K)
0.062;-8320.0
9T(8Q)
0.044;-11743.7
(8J)(9J)
0.076;-5803.7
8J(9J)
0.076;-8773.8
9J(8Q)
0.047;-11290.0
(8Q)(9Q)
0.082;-4896.2
8K(9Q)
0.053;-10382.5
8K(9K)
0.068;-6958.8
TQ(8T)
0.057;-8320.0
K(8TJ)
0.057;-10382.5
Q(8TQ)
0.068;-7412.5
KK(8T)
0.065;-6505.0
