AAAA
0.431;-1390.0
5AAA
0.305;-5023.8
9AAA
0.344;-4088.7
KAAA
0.351;-3153.7
4A(2A)
0.241;-8062.5
(2A)(7A)
0.276;-5831.3
A(2TA)
0.219;-6660.0
QA(2A)
0.317;-6192.5
2A(4A)
0.279;-8062.5
26AA
0.223;-9125.0
AA(29)
0.282;-6893.7
2A(QA)
0.264;-6192.5
A(34A)
0.208;-7828.7
6A(3A)
0.283;-7361.2
(3A)(9A)
0.292;-5130.0
A(3QA)
0.269;-5958.8
AA(34)
0.228;-7828.7
3A(7A)
0.237;-7127.5
39AA
0.210;-8190.0
AA(3Q)
0.255;-5958.8
(4A)(5A)
0.240;-5831.3
A(48A)
0.243;-6660.0
TA(4A)
0.278;-6192.5
(4A)(KA)
0.327;-3961.2
46AA
0.227;-8657.5
AA(49)
0.226;-6426.2
4A(QA)
0.332;-5725.0
A(56A)
0.246;-6893.7
8A(5A)
0.306;-6426.2
(5A)(JA)
0.254;-4195.0
55AA
0.251;-7127.5
AA(58)
0.285;-6426.2
5A(JA)
0.294;-5725.0
5KAA
0.280;-6787.5
8A(6A)
0.272;-6192.5
(6A)(JA)
0.330;-3961.2
66AA
0.302;-6660.0
AA(69)
0.311;-5958.8
6A(QA)
0.295;-5257.5
A(78A)
0.291;-5958.8
TA(7A)
0.318;-5491.2
(7A)(KA)
0.327;-3260.0
79AA
0.292;-7255.0
AA(7Q)
0.326;-5023.8
(8A)(9A)
0.316;-3961.2
A(8QA)
0.261;-4790.0
AA(89)
0.306;-5491.2
8A(QA)
0.323;-4790.0
A(9TA)
0.323;-5023.8
QA(9A)
0.328;-4556.2
9A(JA)
0.319;-4790.0
9KAA
0.304;-5852.5
QA(TA)
0.273;-4322.5
TA(QA)
0.330;-4322.5
A(JQA)
0.343;-4088.8
AA(JQ)
0.383;-4088.8
(QA)(KA)
0.407;-2091.3
KKAA
0.302;-3387.5
2(25A)
0.188;-10633.8
27(2A)
0.232;-10166.2
(2T)(2A)
0.194;-7935.0
2(2KA)
0.275;-8763.8
(236A)
0.163;-11696.2
(23TA)
0.216;-10761.2
33(2A)
0.191;-10867.5
(36)(2A)
0.208;-10166.2
3(29A)
0.191;-10995.0
3J(2A)
0.171;-10527.5
(245A)
0.176;-11696.2
(249A)
0.221;-10761.2
(24KA)
0.211;-9826.2
46(2A)
0.216;-11462.5
(49)(2A)
0.266;-9231.2
4(2QA)
0.214;-10060.0
6(25A)
0.213;-11228.7
T(25A)
0.238;-10293.8
5(26A)
0.194;-11228.7
58(2A)
0.170;-10761.2
(5J)(2A)
0.238;-8530.0
6(26A)
0.251;-9465.0
T(26A)
0.245;-10060.0
6(27A)
0.182;-10761.2
69(2A)
0.275;-10293.8
(6Q)(2A)
0.243;-8062.5
(279A)
0.212;-10060.0
(27KA)
0.241;-9125.0
79(2A)
0.200;-10060.0
(7Q)(2A)
0.262;-7828.8
(28TA)
0.242;-9592.5
88(2A)
0.263;-8530.0
(8J)(2A)
0.262;-7828.8
9(29A)
0.262;-8062.5
K(29A)
0.223;-8657.5
9(2QA)
0.202;-8891.2
J(2TA)
0.214;-8891.2
TJ(2A)
0.265;-8891.2
(2JQA)
0.229;-8423.7
J(2KA)
0.277;-8190.0
(QK)(2A)
0.241;-6426.2
22(4A)
0.243;-10867.5
226A
0.184;-11930.0
2A(29)
0.219;-9698.8
22(QA)
0.228;-8997.5
2(34A)
0.190;-12163.8
26(3A)
0.241;-11696.2
(29)(3A)
0.197;-9465.0
2(3QA)
0.202;-10293.8
A(234)
0.202;-12163.8
(23)(7A)
0.215;-9932.5
9A(23)
0.207;-10995.0
A(23Q)
0.224;-10293.8
2A(34)
0.200;-12163.8
2A(36)
0.179;-11696.2
2A(38)
0.204;-11228.7
2A(3T)
0.198;-10761.2
2A(3Q)
0.172;-10293.8
2(45A)
0.178;-11696.2
27(4A)
0.191;-11228.7
(2T)(4A)
0.180;-8997.5
2(4KA)
0.175;-9826.2
A(246)
0.226;-11462.5
(24)(9A)
0.230;-9231.2
JA(24)
0.248;-10293.8
24(5A)
0.168;-11696.2
24(7A)
0.243;-11228.7
24(9A)
0.235;-10761.2
24(JA)
0.155;-10293.8
24(KA)
0.248;-9826.2
26(5A)
0.206;-11228.7
(29)(5A)
0.234;-8997.5
2(5QA)
0.234;-9826.2
A(256)
0.169;-11228.7
(25)(9A)
0.203;-8997.5
JA(25)
0.247;-10060.0
25(6A)
0.239;-11228.7
25(8A)
0.193;-10761.2
25(TA)
0.170;-10293.8
25(QA)
0.195;-9826.2
(26)(6A)
0.225;-7935.0
2(69A)
0.198;-10293.8
2J(6A)
0.196;-9826.2
(26)(7A)
0.222;-9231.2
9A(26)
0.183;-10293.8
A(26Q)
0.225;-9592.5
2A(67)
0.194;-10761.2
2A(69)
0.177;-10293.8
2A(6J)
0.195;-9826.2
2A(6K)
0.268;-9358.8
(29)(7A)
0.221;-8530.0
2(7QA)
0.219;-9358.8
A(278)
0.168;-10293.8
(27)(JA)
0.237;-8062.5
KA(27)
0.189;-9125.0
2A(79)
0.196;-10060.0
2A(7J)
0.218;-9592.5
2A(7K)
0.210;-9125.0
(2T)(8A)
0.211;-8062.5
2(8KA)
0.243;-8891.2
A(28T)
0.211;-9592.5
(28)(KA)
0.314;-7361.2
28(TA)
0.267;-9592.5
28(QA)
0.258;-9125.0
(29)(9A)
0.294;-6532.5
2(9QA)
0.204;-8891.2
A(29T)
0.191;-9358.8
(29)(KA)
0.274;-7127.5
29(JA)
0.200;-9125.0
29(KA)
0.278;-8657.5
2J(TA)
0.291;-8891.2
(2T)(JA)
0.263;-7361.2
KA(2T)
0.228;-8423.7
2A(TQ)
0.237;-8657.5
2(JQA)
0.205;-8423.7
A(2JQ)
0.218;-8423.7
2A(JQ)
0.257;-8423.7
2(QKA)
0.212;-7956.2
2Q(KA)
0.249;-7956.2
33(3A)
0.270;-9103.8
(36)(3A)
0.223;-8402.5
3(39A)
0.220;-9231.2
3J(3A)
0.237;-8763.8
(345A)
0.222;-11462.5
(349A)
0.217;-10527.5
(34KA)
0.224;-9592.5
46(3A)
0.235;-11228.7
(49)(3A)
0.256;-8997.5
4(3QA)
0.218;-9826.2
6(35A)
0.152;-10995.0
T(35A)
0.201;-10060.0
5(36A)
0.200;-10995.0
58(3A)
0.243;-10527.5
(5J)(3A)
0.242;-8296.2
6(36A)
0.288;-9231.2
T(36A)
0.281;-9826.2
6(37A)
0.184;-10527.5
69(3A)
0.235;-10060.0
(6Q)(3A)
0.246;-7828.8
(379A)
0.187;-9826.2
(37KA)
0.228;-8891.2
79(3A)
0.233;-9826.2
(7Q)(3A)
0.264;-7595.0
(38TA)
0.233;-9358.8
88(3A)
0.265;-8296.2
(8J)(3A)
0.238;-7595.0
9(39A)
0.218;-7828.7
K(39A)
0.198;-8423.7
9(3QA)
0.231;-8657.5
J(3TA)
0.239;-8657.5
TJ(3A)
0.256;-8657.5
(3JQA)
0.289;-8190.0
J(3KA)
0.220;-7956.2
(QK)(3A)
0.261;-6192.5
33(5A)
0.196;-10166.2
337A
0.221;-11228.7
3A(3T)
0.236;-8997.5
33(KA)
0.220;-8296.2
3(46A)
0.166;-11228.7
38(4A)
0.212;-10761.2
(3J)(4A)
0.257;-8530.0
4A(34)
0.201;-10166.2
A(347)
0.156;-10995.0
(34)(TA)
0.258;-8763.8
QA(34)
0.195;-9826.2
345A
0.130;-12992.5
347A
0.181;-12525.0
349A
0.180;-12057.5
34JA
0.200;-11590.0
34KA
0.187;-11122.5
37(5A)
0.176;-10761.2
(3T)(5A)
0.226;-8530.0
3(5KA)
0.269;-9358.8
A(357)
0.214;-10761.2
(35)(TA)
0.200;-8530.0
QA(35)
0.258;-9592.5
356A
0.153;-12525.0
358A
0.175;-12057.5
35TA
0.227;-11590.0
35QA
0.227;-11122.5
(37)(6A)
0.241;-8997.5
3(6TA)
0.171;-9826.2
3Q(6A)
0.232;-9358.8
(36)(8A)
0.243;-8763.8
TA(36)
0.235;-9826.2
A(36K)
0.199;-9125.0
6A(38)
0.175;-10293.8
6A(3T)
0.199;-9826.2
6A(3Q)
0.240;-9358.8
37(7A)
0.257;-8763.8
(3T)(7A)
0.194;-8062.5
3(7KA)
0.186;-8891.2
A(379)
0.210;-9826.2
(37)(QA)
0.314;-7595.0
7A(38)
0.241;-10060.0
7A(3T)
0.213;-9592.5
7A(3Q)
0.268;-9125.0
38(8A)
0.231;-8296.2
(3J)(8A)
0.239;-7595.0
8A(38)
0.286;-8296.2
A(38J)
0.199;-9125.0
388A
0.226;-9826.2
38TA
0.242;-10888.8
38QA
0.237;-10421.2
(3T)(9A)
0.272;-7595.0
3(9KA)
0.272;-8423.7
A(39J)
0.250;-8891.2
399A
0.258;-9358.8
39JA
0.217;-10421.2
39KA
0.218;-9953.7
3Q(TA)
0.285;-8423.7
(3T)(QA)
0.332;-6893.7
TA(3J)
0.257;-8657.5
TA(3K)
0.220;-8190.0
3(JKA)
0.243;-7956.2
A(3JK)
0.232;-7956.2
JA(3K)
0.230;-7956.2
QA(3Q)
0.230;-6426.2
3QKA
0.281;-9252.5
45(4A)
0.224;-9698.8
(48)(4A)
0.246;-7467.5
4(4JA)
0.191;-8296.2
4K(4A)
0.249;-7828.7
(459A)
0.201;-10060.0
(45KA)
0.241;-9125.0
57(4A)
0.213;-10527.5
(5T)(4A)
0.257;-8296.2
5(4KA)
0.240;-9125.0
(469A)
0.230;-9826.2
(46KA)
0.209;-8891.2
68(4A)
0.240;-10060.0
(6J)(4A)
0.230;-7828.8
7(47A)
0.282;-8530.0
J(47A)
0.233;-9125.0
78(4A)
0.217;-9826.2
(7J)(4A)
0.265;-7595.0
8(48A)
0.210;-8062.5
Q(48A)
0.243;-8657.5
(8T)(4A)
0.246;-7595.0
8(4KA)
0.273;-8423.7
(49QA)
0.244;-8423.7
9(4JA)
0.225;-8657.5
9K(4A)
0.211;-8190.0
TT(4A)
0.290;-7127.5
(TK)(4A)
0.257;-6426.2
J(4QA)
0.299;-7956.2
K(4QA)
0.257;-7488.8
44(5A)
0.196;-9698.8
447A
0.192;-10761.2
4A(4T)
0.249;-8530.0
44(KA)
0.220;-7828.7
4(57A)
0.162;-10527.5
49(5A)
0.252;-10060.0
(4Q)(5A)
0.320;-7828.8
6A(45)
0.212;-10761.2
A(459)
0.215;-10060.0
(45)(QA)
0.279;-7828.8
5A(46)
0.250;-10761.2
5A(48)
0.195;-10293.8
5A(4T)
0.233;-9826.2
5A(4Q)
0.178;-9358.8
46(6A)
0.201;-8997.5
(49)(6A)
0.181;-8296.2
4(6QA)
0.179;-9125.0
A(467)
0.238;-10293.8
(46)(TA)
0.201;-8062.5
QA(46)
0.220;-9125.0
467A
0.201;-11823.8
469A
0.165;-11356.2
46JA
0.190;-10888.8
46KA
0.156;-10421.2
49(7A)
0.207;-9592.5
(4Q)(7A)
0.265;-7361.2
8A(47)
0.210;-9826.2
A(47J)
0.215;-9125.0
477A
0.186;-10060.0
479A
0.212;-11122.5
47JA
0.241;-10655.0
47KA
0.192;-10187.5
4T(8A)
0.187;-9125.0
(4K)(8A)
0.271;-6893.7
TA(48)
0.217;-9125.0
A(48K)
0.209;-8423.7
8A(4T)
0.232;-9125.0
8A(4Q)
0.209;-8657.5
49(9A)
0.240;-7595.0
(4Q)(9A)
0.271;-6893.7
TA(49)
0.221;-8891.2
A(49K)
0.209;-8190.0
9A(4J)
0.201;-8657.5
9A(4K)
0.257;-8190.0
4(TQA)
0.246;-8190.0
A(4TJ)
0.292;-8423.7
4TTA
0.223;-8657.5
4TQA
0.209;-9720.0
(4Q)(JA)
0.228;-6426.2
QA(4J)
0.246;-7956.2
4JQA
0.181;-9486.2
(4K)(QA)
0.267;-5958.8
QA(4K)
0.248;-7488.8
5(56A)
0.223;-8997.5
58(5A)
0.204;-8530.0
(5J)(5A)
0.336;-6298.7
6(56A)
0.283;-8763.8
T(56A)
0.197;-9358.8
6(57A)
0.175;-10060.0
69(5A)
0.270;-9592.5
(6Q)(5A)
0.225;-7361.2
(579A)
0.276;-9358.8
(57KA)
0.254;-8423.7
79(5A)
0.198;-9358.8
(7Q)(5A)
0.246;-7127.5
(58TA)
0.213;-8891.2
88(5A)
0.256;-7828.7
(8J)(5A)
0.239;-7127.5
9(59A)
0.242;-7361.2
K(59A)
0.314;-7956.2
9(5QA)
0.234;-8190.0
J(5TA)
0.309;-8190.0
TJ(5A)
0.244;-8190.0
(5JQA)
0.247;-7722.5
J(5KA)
0.269;-7488.8
(QK)(5A)
0.301;-5725.0
55(7A)
0.238;-8763.8
559A
0.203;-9826.2
5A(5Q)
0.262;-7595.0
(57)(6A)
0.264;-8530.0
5(6TA)
0.222;-9358.8
5Q(6A)
0.235;-8891.2
(56)(8A)
0.222;-8296.2
TA(56)
0.191;-9358.8
A(56K)
0.227;-8657.5
6A(58)
0.210;-9826.2
6A(5T)
0.228;-9358.8
6A(5Q)
0.242;-8891.2
57(7A)
0.262;-8296.2
(5T)(7A)
0.257;-7595.0
5(7KA)
0.179;-8423.7
A(579)
0.214;-9358.8
(57)(QA)
0.256;-7127.5
7A(58)
0.195;-9592.5
7A(5T)
0.236;-9125.0
7A(5Q)
0.245;-8657.5
58(8A)
0.216;-7828.7
(5J)(8A)
0.308;-7127.5
8A(58)
0.205;-7828.7
A(58J)
0.232;-8657.5
588A
0.198;-9358.8
58TA
0.206;-10421.2
58QA
0.210;-9953.7
(5T)(9A)
0.228;-7127.5
5(9KA)
0.274;-7956.2
A(59J)
0.256;-8423.7
599A
0.200;-8891.2
59JA
0.177;-9953.7
59KA
0.196;-9486.2
5Q(TA)
0.220;-7956.2
(5T)(QA)
0.220;-6426.2
TA(5J)
0.302;-8190.0
TA(5K)
0.298;-7722.5
5(JKA)
0.230;-7488.8
A(5JK)
0.237;-7488.8
JA(5K)
0.229;-7488.8
QA(5Q)
0.257;-5958.8
5QKA
0.257;-8785.0
67(6A)
0.224;-8296.2
(6T)(6A)
0.318;-6065.0
6(6KA)
0.298;-6893.7
(67TA)
0.225;-8891.2
77(6A)
0.248;-8062.5
(7T)(6A)
0.222;-7361.2
7(6KA)
0.231;-8190.0
(68JA)
0.206;-8423.7
(89)(6A)
0.307;-7361.2
8(6QA)
0.222;-8190.0
T(69A)
0.273;-8423.7
9(6TA)
0.207;-8423.7
9Q(6A)
0.191;-7956.2
Q(6TA)
0.278;-7722.5
(TQ)(6A)
0.289;-6192.5
(6JKA)
0.279;-7255.0
JK(6A)
0.221;-7255.0
K(6KA)
0.266;-5257.5
668A
0.214;-9592.5
6A(6J)
0.271;-7361.2
(67)(7A)
0.259;-6532.5
6(7TA)
0.233;-8891.2
6Q(7A)
0.252;-8423.7
(67)(9A)
0.300;-7595.0
JA(67)
0.214;-8657.5
67(8A)
0.189;-9358.8
67(TA)
0.244;-8891.2
67(QA)
0.222;-8423.7
(68)(8A)
0.267;-6065.0
6(8JA)
0.274;-8423.7
6K(8A)
0.235;-7956.2
(68)(JA)
0.240;-6893.7
KA(68)
0.216;-7956.2
6A(8T)
0.297;-8657.5
6A(8Q)
0.228;-8190.0
6(9TA)
0.259;-8423.7
6Q(9A)
0.215;-7956.2
(69)(JA)
0.237;-6660.0
KA(69)
0.253;-7722.5
6A(9J)
0.239;-8190.0
6A(9K)
0.226;-7722.5
(6Q)(TA)
0.289;-6192.5
JA(6T)
0.206;-7956.2
6T(JA)
0.295;-7956.2
6T(KA)
0.219;-7488.8
6Q(JA)
0.285;-7488.8
(6J)(KA)
0.255;-5725.0
6J(KA)
0.295;-7255.0
6K(QA)
0.279;-7021.2
6A(QK)
0.266;-7021.2
(78)(7A)
0.316;-6065.0
7(7JA)
0.264;-6893.7
7K(7A)
0.285;-6426.2
(78QA)
0.228;-7956.2
8(7TA)
0.277;-8423.7
8Q(7A)
0.301;-7956.2
J(79A)
0.229;-7956.2
9T(7A)
0.283;-8190.0
(9K)(7A)
0.269;-5958.8
K(7TA)
0.306;-7255.0
T(7KA)
0.270;-7255.0
JJ(7A)
0.265;-5958.8
(7QKA)
0.297;-6787.5
777A
0.291;-7828.8
7A(7T)
0.257;-7127.5
77(KA)
0.310;-6426.2
7(8TA)
0.281;-8423.7
7Q(8A)
0.313;-7956.2
(78)(TA)
0.250;-6893.7
QA(78)
0.217;-7956.2
789A
0.186;-10187.5
78JA
0.250;-9720.0
78KA
0.196;-9252.5
7J(9A)
0.294;-7956.2
(79)(TA)
0.276;-6660.0
QA(79)
0.311;-7722.5
79TA
0.215;-9720.0
79QA
0.225;-9252.5
(7J)(TA)
0.290;-6192.5
TA(7T)
0.309;-6426.2
A(7TK)
0.236;-7255.0
TA(7Q)
0.268;-7488.8
7J(JA)
0.267;-5958.8
(7J)(QA)
0.295;-5725.0
JA(7Q)
0.273;-7255.0
7Q(QA)
0.345;-5491.2
7QQA
0.236;-7021.2
7KKA
0.278;-6553.8
8(8JA)
0.345;-6426.2
8K(8A)
0.257;-5958.8
(89KA)
0.282;-7255.0
9J(8A)
0.267;-7722.5
(8TJA)
0.245;-7488.8
(TJ)(8A)
0.273;-5958.8
J(8JA)
0.288;-5725.0
JQ(8A)
0.266;-7021.2
Q(8KA)
0.306;-6553.8
889A
0.215;-8423.7
8A(8Q)
0.291;-6192.5
(8T)(9A)
0.271;-6426.2
8(9KA)
0.221;-7255.0
A(89J)
0.204;-7722.5
899A
0.281;-8190.0
89JA
0.261;-9252.5
89KA
0.237;-8785.0
8Q(TA)
0.266;-7255.0
(8T)(QA)
0.273;-5725.0
TA(8J)
0.291;-7488.8
TA(8K)
0.282;-7021.2
8(JKA)
0.243;-6787.5
A(8JK)
0.293;-6787.5
JA(8K)
0.261;-6787.5
QA(8Q)
0.277;-5257.5
8QKA
0.255;-8083.8
9T(9A)
0.267;-6192.5
(9K)(9A)
0.280;-3961.2
K(9TA)
0.321;-6787.5
T(9KA)
0.295;-6787.5
JJ(9A)
0.299;-5491.2
(9QKA)
0.274;-6320.0
999A
0.267;-6426.2
9A(9Q)
0.254;-5725.0
(9J)(TA)
0.256;-5725.0
TA(9T)
0.247;-5958.8
A(9TK)
0.235;-6787.5
TA(9Q)
0.302;-7021.2
9J(JA)
0.265;-5491.2
(9J)(QA)
0.296;-5257.5
JA(9Q)
0.227;-6787.5
9Q(QA)
0.327;-5023.8
9QQA
0.266;-6553.8
9KKA
0.238;-6086.2
T(TKA)
0.360;-5023.8
JJ(TA)
0.313;-5257.5
(TQKA)
0.331;-6086.2
TTTA
0.310;-5725.0
TA(TK)
0.335;-5023.8
(TK)(JA)
0.320;-4790.0
KA(TJ)
0.282;-6320.0
TA(JK)
0.262;-6320.0
(TQ)(KA)
0.275;-4556.2
(TK)(KA)
0.312;-2792.5
J(JKA)
0.303;-4556.2
(QK)(JA)
0.363;-4322.5
JJ(KA)
0.269;-4556.2
QA(JQ)
0.262;-4556.2
JQKA
0.285;-7382.5
QK(QA)
0.321;-4088.8
QK(KA)
0.315;-3855.0
22(24)
0.196;-12142.5
22(28)
0.233;-11207.5
22(2Q)
0.235;-10272.5
24(23)
0.159;-13438.7
(23)(27)
0.188;-11207.5
2(23T)
0.182;-12036.2
2Q(23)
0.191;-11568.8
23(25)
0.170;-13205.0
2237
0.155;-14267.5
22(3T)
0.172;-12036.2
23(2K)
0.195;-11335.0
2(246)
0.141;-12737.5
28(24)
0.178;-12270.0
(24)(2J)
0.167;-10038.8
2244
0.192;-13205.0
22(47)
0.136;-12503.8
24(2T)
0.166;-11802.5
224Q
0.216;-12865.0
26(25)
0.185;-12503.8
(25)(29)
0.189;-10272.5
2(25Q)
0.202;-11101.2
22(56)
0.210;-12503.8
25(29)
0.175;-11802.5
225J
0.167;-12865.0
26(26)
0.191;-10740.0
(26)(29)
0.202;-10038.8
2(26Q)
0.231;-10867.5
22(67)
0.179;-12036.2
26(2T)
0.150;-11335.0
226Q
0.206;-12397.5
28(27)
0.219;-11568.8
(27)(2J)
0.212;-9337.5
2277
0.230;-11802.5
22(7T)
0.218;-11101.2
27(2K)
0.219;-10400.0
2(28T)
0.166;-10867.5
2Q(28)
0.234;-10400.0
28(2T)
0.173;-10867.5
228Q
0.198;-11930.0
2T(29)
0.217;-10633.8
(29)(2K)
0.261;-8402.5
229J
0.163;-11930.0
2T(2T)
0.225;-8870.0
(2T)(2K)
0.206;-8168.7
22TQ
0.168;-11462.5
2Q(2J)
0.230;-9698.8
2J(2K)
0.260;-9465.0
22QQ
0.230;-9465.0
3(234)
0.145;-13205.0
36(23)
0.150;-12737.5
(23)(39)
0.184;-10506.2
3(23Q)
0.243;-11335.0
5(234)
0.151;-14267.5
9(234)
0.180;-13332.5
K(234)
0.185;-12397.5
4(237)
0.152;-13800.0
49(23)
0.163;-13332.5
(23)(4Q)
0.160;-11101.2
(2357)
0.135;-13566.2
(235J)
0.185;-12631.3
(23)(56)
0.182;-12270.0
5(239)
0.173;-13098.7
5J(23)
0.172;-12631.3
(2367)
0.146;-13332.5
(236J)
0.204;-12397.5
(23)(67)
0.159;-11802.5
6(23T)
0.175;-12631.3
6Q(23)
0.178;-12163.8
9(237)
0.175;-12631.3
K(237)
0.176;-11696.2
7(23T)
0.165;-12397.5
7Q(23)
0.155;-11930.0
T(238)
0.159;-12163.8
8(239)
0.195;-12397.5
8J(23)
0.200;-11930.0
(239T)
0.221;-11930.0
99(23)
0.224;-10633.8
(23)(9Q)
0.190;-9932.5
(23TQ)
0.156;-11228.7
T(23Q)
0.180;-11228.7
Q(23J)
0.209;-10995.0
(23)(JK)
0.199;-9231.2
QK(23)
0.228;-10527.5
23(35)
0.188;-12971.3
33(28)
0.181;-12270.0
233T
0.136;-13332.5
23(3K)
0.242;-11101.2
(24)(36)
0.202;-12503.8
3(249)
0.174;-13332.5
3J(24)
0.192;-12865.0
(34)(25)
0.212;-12737.5
27(34)
0.201;-13800.0
2(34T)
0.184;-13098.7
(34)(2K)
0.186;-10867.5
34(26)
0.171;-14033.8
34(28)
0.187;-13566.2
34(2T)
0.128;-13098.7
34(2Q)
0.188;-12631.3
(25)(35)
0.185;-10973.8
3(258)
0.149;-13332.5
3T(25)
0.199;-12865.0
(25)(3K)
0.253;-10633.8
27(35)
0.163;-13566.2
2(35T)
0.200;-12865.0
(35)(2K)
0.211;-10633.8
35(27)
0.177;-13566.2
35(29)
0.175;-13098.7
35(2J)
0.168;-12631.3
35(2K)
0.199;-12163.8
37(26)
0.132;-13332.5
(26)(3T)
0.232;-11101.2
3(26K)
0.231;-11930.0
2(368)
0.178;-13098.7
(36)(2J)
0.185;-10867.5
2K(36)
0.215;-11930.0
23(68)
0.177;-13098.7
23(6T)
0.174;-12631.3
23(6Q)
0.182;-12163.8
3(278)
0.157;-12865.0
3T(27)
0.199;-12397.5
(27)(3K)
0.174;-10166.2
29(37)
0.191;-12631.3
2(37Q)
0.216;-11930.0
23(78)
0.180;-12865.0
23(7T)
0.152;-12397.5
23(7Q)
0.164;-11930.0
3(289)
0.138;-12397.5
3J(28)
0.234;-11930.0
(38)(29)
0.165;-10867.5
2J(38)
0.160;-11930.0
38(29)
0.195;-12397.5
38(2J)
0.183;-11930.0
38(2K)
0.215;-11462.5
3T(29)
0.208;-11930.0
(29)(3K)
0.232;-9698.8
2J(39)
0.203;-11696.2
39(2T)
0.189;-11930.0
39(2Q)
0.184;-11462.5
(2T)(3T)
0.237;-8636.2
3(2TK)
0.239;-10995.0
2(3TQ)
0.207;-11228.7
23(TJ)
0.192;-11462.5
23(TK)
0.200;-10995.0
(2J)(3K)
0.277;-9231.2
2K(3J)
0.210;-10761.2
23(JK)
0.184;-10761.2
(3Q)(2K)
0.264;-8997.5
(2K)(3K)
0.233;-7233.8
4(246)
0.190;-12270.0
48(24)
0.181;-11802.5
(24)(4J)
0.228;-9571.3
5(245)
0.199;-12270.0
9(245)
0.183;-12865.0
K(245)
0.193;-11930.0
5(248)
0.172;-13098.7
5T(24)
0.156;-12631.3
(24)(5K)
0.186;-10400.0
9(246)
0.179;-12631.3
K(246)
0.183;-11696.2
6(249)
0.209;-12631.3
6J(24)
0.214;-12163.8
(2478)
0.146;-12631.3
(247Q)
0.223;-11696.2
7(249)
0.163;-12397.5
7J(24)
0.203;-11930.0
(2489)
0.225;-12163.8
(248K)
0.206;-11228.7
8T(24)
0.226;-11930.0
(24)(8K)
0.185;-9698.8
Q(249)
0.244;-11228.7
(24)(9J)
0.225;-9932.5
T(24T)
0.196;-9932.5
T(24J)
0.191;-11228.7
TK(24)
0.176;-10761.2
(24)(JQ)
0.242;-9231.2
QQ(24)
0.250;-8997.5
24(45)
0.168;-12503.8
44(28)
0.192;-11802.5
244T
0.151;-12865.0
24(4K)
0.215;-10633.8
(25)(47)
0.160;-11802.5
4(25T)
0.198;-12631.3
4Q(25)
0.195;-12163.8
(45)(27)
0.152;-11802.5
29(45)
0.140;-12865.0
2(45Q)
0.230;-12163.8
24(56)
0.172;-13566.2
24(58)
0.140;-13098.7
24(5T)
0.174;-12631.3
24(5Q)
0.155;-12163.8
4(267)
0.184;-13098.7
49(26)
0.193;-12631.3
(26)(4Q)
0.181;-10400.0
27(46)
0.199;-13098.7
2(46T)
0.196;-12397.5
(46)(2K)
0.267;-10166.2
46(28)
0.164;-12865.0
46(2T)
0.236;-12397.5
46(2Q)
0.179;-11930.0
(27)(47)
0.249;-9805.0
4(27T)
0.139;-12163.8
4Q(27)
0.185;-11696.2
(47)(29)
0.216;-10867.5
2J(47)
0.181;-11930.0
47(28)
0.165;-12631.3
47(2T)
0.208;-12163.8
47(2Q)
0.144;-11696.2
(28)(48)
0.273;-9337.5
4(28J)
0.171;-11696.2
4K(28)
0.222;-11228.7
(48)(2J)
0.198;-10166.2
2K(48)
0.163;-11228.7
24(8T)
0.201;-11930.0
24(8Q)
0.160;-11462.5
4(29T)
0.145;-11696.2
4Q(29)
0.182;-11228.7
(49)(2J)
0.235;-9932.5
2K(49)
0.218;-10995.0
24(9J)
0.227;-11462.5
24(9K)
0.206;-10995.0
(2T)(4Q)
0.234;-9465.0
2J(4T)
0.245;-11228.7
4T(2J)
0.191;-11228.7
4T(2K)
0.238;-10761.2
4Q(2J)
0.166;-10761.2
(4J)(2K)
0.251;-8997.5
4J(2K)
0.192;-10527.5
4K(2Q)
0.215;-10293.8
24(QK)
0.184;-10293.8
(25)(56)
0.264;-10272.5
5(259)
0.220;-11101.2
5J(25)
0.193;-10633.8
(2567)
0.163;-12865.0
(256J)
0.167;-11930.0
(25)(67)
0.230;-11335.0
6(25T)
0.164;-12163.8
6Q(25)
0.175;-11696.2
9(257)
0.227;-12163.8
K(257)
0.190;-11228.7
7(25T)
0.224;-11930.0
7Q(25)
0.180;-11462.5
T(258)
0.182;-11696.2
8(259)
0.145;-11930.0
8J(25)
0.218;-11462.5
(259T)
0.166;-11462.5
99(25)
0.178;-10166.2
(25)(9Q)
0.262;-9465.0
(25TQ)
0.180;-10761.2
T(25Q)
0.217;-10761.2
Q(25J)
0.204;-10527.5
(25)(JK)
0.240;-8763.8
QK(25)
0.230;-10060.0
25(57)
0.199;-11568.8
55(2T)
0.169;-10867.5
255Q
0.233;-11930.0
57(26)
0.155;-12865.0
(26)(5T)
0.193;-10633.8
5(26K)
0.187;-11462.5
2(568)
0.195;-12631.3
(56)(2J)
0.169;-10400.0
2K(56)
0.217;-11462.5
25(68)
0.196;-12631.3
25(6T)
0.160;-12163.8
25(6Q)
0.186;-11696.2
5(278)
0.137;-12397.5
5T(27)
0.209;-11930.0
(27)(5K)
0.199;-9698.8
29(57)
0.153;-12163.8
2(57Q)
0.195;-11462.5
25(78)
0.159;-12397.5
25(7T)
0.211;-11930.0
25(7Q)
0.208;-11462.5
5(289)
0.177;-11930.0
5J(28)
0.160;-11462.5
(58)(29)
0.270;-10400.0
2J(58)
0.204;-11462.5
58(29)
0.201;-11930.0
58(2J)
0.163;-11462.5
58(2K)
0.237;-10995.0
5T(29)
0.237;-11462.5
(29)(5K)
0.242;-9231.2
2J(59)
0.205;-11228.7
59(2T)
0.190;-11462.5
59(2Q)
0.174;-10995.0
(2T)(5T)
0.237;-8168.7
5(2TK)
0.212;-10527.5
2(5TQ)
0.150;-10761.2
25(TJ)
0.193;-10995.0
25(TK)
0.237;-10527.5
(2J)(5K)
0.255;-8763.8
2K(5J)
0.234;-10293.8
25(JK)
0.195;-10293.8
(5Q)(2K)
0.294;-8530.0
(2K)(5K)
0.243;-6766.2
6(268)
0.160;-10867.5
6T(26)
0.210;-10400.0
(26)(6K)
0.233;-8168.7
T(267)
0.193;-11696.2
7(268)
0.204;-12163.8
7T(26)
0.177;-11696.2
(26)(7K)
0.270;-9465.0
J(268)
0.170;-11228.7
89(26)
0.193;-11696.2
(26)(8Q)
0.247;-9465.0
(269J)
0.192;-10995.0
(26)(9T)
0.196;-9698.8
9(26K)
0.188;-10527.5
(26TK)
0.217;-10293.8
TQ(26)
0.212;-10527.5
K(26J)
0.223;-10060.0
Q(26Q)
0.215;-8530.0
KK(26)
0.254;-8062.5
66(29)
0.212;-10633.8
266J
0.231;-11696.2
67(27)
0.202;-10867.5
(27)(6T)
0.198;-10166.2
6(27K)
0.185;-10995.0
2(679)
0.197;-11930.0
(67)(2Q)
0.237;-9698.8
27(68)
0.185;-12163.8
27(6T)
0.195;-11696.2
27(6Q)
0.197;-11228.7
68(28)
0.240;-10400.0
(28)(6J)
0.213;-9698.8
28(68)
0.173;-10400.0
2(68J)
0.187;-11228.7
2688
0.235;-11930.0
268T
0.189;-12992.5
268Q
0.173;-12525.0
(29)(6T)
0.259;-9698.8
6(29K)
0.234;-10527.5
2(69J)
0.211;-10995.0
2699
0.195;-11462.5
269J
0.185;-12525.0
269K
0.163;-12057.5
6Q(2T)
0.221;-10527.5
(6T)(2Q)
0.208;-8997.5
2T(6J)
0.204;-10761.2
2T(6K)
0.187;-10293.8
6(2JK)
0.208;-10060.0
2(6JK)
0.195;-10060.0
2J(6K)
0.212;-10060.0
2Q(6Q)
0.275;-8530.0
26QK
0.200;-11356.2
78(27)
0.222;-10400.0
(27)(7J)
0.261;-8168.7
8(278)
0.234;-10166.2
Q(278)
0.186;-10761.2
(27)(8T)
0.223;-9698.8
8(27K)
0.175;-10527.5
(279Q)
0.221;-10527.5
9(27J)
0.220;-10761.2
9K(27)
0.188;-10293.8
TT(27)
0.287;-9231.2
(27)(TK)
0.279;-8530.0
J(27Q)
0.200;-10060.0
K(27Q)
0.277;-9592.5
77(28)
0.181;-10400.0
277T
0.160;-11462.5
27(7K)
0.254;-9231.2
(28)(7T)
0.241;-9698.8
7(28K)
0.219;-10527.5
2(78T)
0.228;-11228.7
(78)(2K)
0.252;-8997.5
78(2T)
0.212;-11228.7
78(2Q)
0.215;-10761.2
(29)(79)
0.294;-8168.7
7(29Q)
0.226;-10527.5
2(79T)
0.172;-10995.0
(79)(2K)
0.235;-8763.8
79(2J)
0.180;-10761.2
79(2K)
0.184;-10293.8
7J(2T)
0.222;-10527.5
(7T)(2J)
0.191;-8997.5
2K(7T)
0.210;-10060.0
27(TQ)
0.228;-10293.8
7(2JQ)
0.220;-10060.0
2(7JQ)
0.169;-10060.0
27(JQ)
0.256;-10060.0
7(2QK)
0.271;-9592.5
7Q(2K)
0.213;-9592.5
88(28)
0.249;-8402.5
(28)(8J)
0.206;-7701.2
9(289)
0.226;-9465.0
K(289)
0.185;-10060.0
9(28Q)
0.236;-10293.8
J(28T)
0.217;-10293.8
TJ(28)
0.204;-10293.8
(28JQ)
0.206;-9826.2
J(28K)
0.222;-9592.5
(28)(QK)
0.256;-7828.8
88(2T)
0.228;-9465.0
288Q
0.163;-10527.5
8T(29)
0.253;-10761.2
(29)(8K)
0.216;-8530.0
2J(89)
0.170;-10527.5
89(2T)
0.239;-10761.2
89(2Q)
0.224;-10293.8
(2T)(8T)
0.254;-7467.5
8(2TK)
0.278;-9826.2
2(8TQ)
0.230;-10060.0
28(TJ)
0.248;-10293.8
28(TK)
0.213;-9826.2
(2J)(8K)
0.219;-8062.5
2K(8J)
0.206;-9592.5
28(JK)
0.204;-9592.5
(8Q)(2K)
0.245;-7828.8
(2K)(8K)
0.227;-6065.0
9(29J)
0.261;-8763.8
9K(29)
0.219;-8296.2
TT(29)
0.301;-8763.8
(29)(TK)
0.229;-8062.5
J(29Q)
0.219;-9592.5
K(29Q)
0.266;-9125.0
99(2T)
0.235;-8997.5
299Q
0.193;-10060.0
9J(2T)
0.191;-10060.0
(9T)(2J)
0.243;-8530.0
2K(9T)
0.258;-9592.5
29(TQ)
0.180;-9826.2
9(2JQ)
0.225;-9592.5
2(9JQ)
0.230;-9592.5
29(JQ)
0.177;-9592.5
9(2QK)
0.257;-9125.0
9Q(2K)
0.224;-9125.0
TT(2T)
0.198;-7000.0
(2T)(TK)
0.235;-6298.7
J(2TQ)
0.219;-9358.8
K(2TQ)
0.265;-8891.2
TT(2J)
0.272;-8296.2
2TTK
0.228;-9358.8
TK(2J)
0.234;-9125.0
2TJJ
0.197;-9592.5
2TJK
0.181;-10655.0
2(TQK)
0.209;-8891.2
TK(2K)
0.238;-7127.5
(2J)(JK)
0.268;-5831.3
QK(2J)
0.246;-8657.5
2J(JK)
0.255;-7361.2
(JQ)(2K)
0.239;-7127.5
(2K)(JK)
0.296;-5363.7
K(2QK)
0.267;-6660.0
2K(QK)
0.248;-6660.0
3335
0.148;-12737.5
3339
0.205;-11802.5
333K
0.166;-10867.5
36(34)
0.188;-12270.0
(34)(39)
0.241;-10038.8
3(34Q)
0.211;-10867.5
33(45)
0.187;-12503.8
34(38)
0.184;-11802.5
334T
0.186;-12865.0
33(4K)
0.274;-10633.8
(35)(37)
0.255;-10272.5
3(35T)
0.207;-11101.2
3Q(35)
0.241;-10633.8
35(37)
0.148;-11802.5
3359
0.190;-12865.0
33(5Q)
0.202;-10633.8
(36)(37)
0.223;-10038.8
3(36T)
0.221;-10867.5
3Q(36)
0.272;-10400.0
36(38)
0.203;-11335.0
336T
0.183;-12397.5
33(6K)
0.215;-10166.2
(37)(39)
0.231;-9337.5
3(37Q)
0.214;-10166.2
33(78)
0.255;-11101.2
37(3J)
0.160;-10400.0
337K
0.252;-11462.5
3T(38)
0.233;-10400.0
(38)(3K)
0.260;-8168.7
338T
0.188;-11930.0
33(8K)
0.249;-9698.8
(39)(3J)
0.232;-8402.5
3399
0.211;-10400.0
33(9Q)
0.235;-9698.8
(3T)(3J)
0.253;-8168.7
33TT
0.231;-9932.5
33(TK)
0.202;-9231.2
(3J)(3K)
0.246;-7467.5
33JK
0.233;-10527.5
33(QK)
0.250;-8763.8
45(34)
0.169;-12270.0
(34)(48)
0.192;-10038.8
4(34J)
0.191;-10867.5
4K(34)
0.248;-10400.0
(3459)
0.225;-12631.3
(345K)
0.237;-11696.2
57(34)
0.169;-13098.7
(34)(5T)
0.209;-10867.5
5(34K)
0.150;-11696.2
(3469)
0.154;-12397.5
(346K)
0.209;-11462.5
68(34)
0.168;-12631.3
(34)(6J)
0.210;-10400.0
7(347)
0.158;-11101.2
J(347)
0.184;-11696.2
78(34)
0.168;-12397.5
(34)(7J)
0.245;-10166.2
8(348)
0.182;-10633.8
Q(348)
0.224;-11228.7
(34)(8T)
0.271;-10166.2
8(34K)
0.172;-10995.0
(349Q)
0.235;-10995.0
9(34J)
0.207;-11228.7
9K(34)
0.203;-10761.2
TT(34)
0.207;-9698.8
(34)(TK)
0.230;-8997.5
J(34Q)
0.216;-10527.5
K(34Q)
0.240;-10060.0
44(35)
0.172;-12270.0
3447
0.141;-13332.5
34(4T)
0.202;-11101.2
44(3K)
0.202;-10400.0
4(357)
0.167;-13098.7
49(35)
0.172;-12631.3
(35)(4Q)
0.246;-10400.0
36(45)
0.139;-13332.5
3(459)
0.217;-12631.3
(45)(3Q)
0.224;-10400.0
35(46)
0.168;-13332.5
35(48)
0.168;-12865.0
35(4T)
0.186;-12397.5
35(4Q)
0.229;-11930.0
46(36)
0.224;-11568.8
(36)(49)
0.243;-10867.5
4(36Q)
0.233;-11696.2
3(467)
0.193;-12865.0
(46)(3T)
0.254;-10633.8
3Q(46)
0.176;-11696.2
3467
0.146;-14395.0
3469
0.144;-13927.5
346J
0.155;-13460.0
346K
0.157;-12992.5
49(37)
0.228;-12163.8
(37)(4Q)
0.202;-9932.5
38(47)
0.186;-12397.5
3(47J)
0.184;-11696.2
3477
0.198;-12631.3
3479
0.164;-13693.8
347J
0.169;-13226.2
347K
0.191;-12758.8
4T(38)
0.245;-11696.2
(38)(4K)
0.264;-9465.0
3T(48)
0.167;-11696.2
3(48K)
0.190;-10995.0
38(4T)
0.219;-11696.2
38(4Q)
0.169;-11228.7
49(39)
0.173;-10166.2
(39)(4Q)
0.217;-9465.0
3T(49)
0.206;-11462.5
3(49K)
0.226;-10761.2
39(4J)
0.186;-11228.7
39(4K)
0.191;-10761.2
4(3TQ)
0.181;-10761.2
3(4TJ)
0.213;-10995.0
34TT
0.188;-11228.7
34TQ
0.223;-12291.2
(3J)(4Q)
0.247;-8997.5
3Q(4J)
0.202;-10527.5
34JQ
0.155;-12057.5
(3Q)(4K)
0.198;-8530.0
3Q(4K)
0.208;-10060.0
5(356)
0.222;-11568.8
58(35)
0.216;-11101.2
(35)(5J)
0.189;-8870.0
6(356)
0.222;-11335.0
T(356)
0.194;-11930.0
6(357)
0.203;-12631.3
69(35)
0.234;-12163.8
(35)(6Q)
0.168;-9932.5
(3579)
0.195;-11930.0
(357K)
0.203;-10995.0
79(35)
0.236;-11930.0
(35)(7Q)
0.237;-9698.8
(358T)
0.180;-11462.5
88(35)
0.220;-10400.0
(35)(8J)
0.206;-9698.8
9(359)
0.207;-9932.5
K(359)
0.208;-10527.5
9(35Q)
0.173;-10761.2
J(35T)
0.197;-10761.2
TJ(35)
0.170;-10761.2
(35JQ)
0.234;-10293.8
J(35K)
0.228;-10060.0
(35)(QK)
0.266;-8296.2
55(37)
0.151;-11335.0
3559
0.174;-12397.5
35(5Q)
0.228;-10166.2
(36)(57)
0.201;-11101.2
5(36T)
0.200;-11930.0
5Q(36)
0.198;-11462.5
(56)(38)
0.180;-10867.5
3T(56)
0.165;-11930.0
3(56K)
0.186;-11228.7
36(58)
0.165;-12397.5
36(5T)
0.174;-11930.0
36(5Q)
0.169;-11462.5
57(37)
0.202;-10867.5
(37)(5T)
0.221;-10166.2
5(37K)
0.216;-10995.0
3(579)
0.183;-11930.0
(57)(3Q)
0.248;-9698.8
37(58)
0.208;-12163.8
37(5T)
0.187;-11696.2
37(5Q)
0.208;-11228.7
58(38)
0.252;-10400.0
(38)(5J)
0.263;-9698.8
38(58)
0.215;-10400.0
3(58J)
0.170;-11228.7
3588
0.173;-11930.0
358T
0.159;-12992.5
358Q
0.189;-12525.0
(39)(5T)
0.196;-9698.8
5(39K)
0.191;-10527.5
3(59J)
0.175;-10995.0
3599
0.209;-11462.5
359J
0.133;-12525.0
359K
0.167;-12057.5
5Q(3T)
0.186;-10527.5
(5T)(3Q)
0.215;-8997.5
3T(5J)
0.259;-10761.2
3T(5K)
0.223;-10293.8
5(3JK)
0.193;-10060.0
3(5JK)
0.228;-10060.0
3J(5K)
0.214;-10060.0
3Q(5Q)
0.286;-8530.0
35QK
0.230;-11356.2
67(36)
0.218;-10867.5
(36)(6T)
0.205;-8636.2
6(36K)
0.194;-9465.0
(367T)
0.191;-11462.5
77(36)
0.197;-10633.8
(36)(7T)
0.265;-9932.5
7(36K)
0.211;-10761.2
(368J)
0.261;-10995.0
(36)(89)
0.196;-9932.5
8(36Q)
0.170;-10761.2
T(369)
0.200;-10995.0
9(36T)
0.194;-10995.0
9Q(36)
0.209;-10527.5
Q(36T)
0.245;-10293.8
(36)(TQ)
0.235;-8763.8
(36JK)
0.218;-9826.2
JK(36)
0.218;-9826.2
K(36K)
0.284;-7828.7
3668
0.195;-12163.8
36(6J)
0.206;-9932.5
(37)(67)
0.224;-9103.8
6(37T)
0.255;-11462.5
6Q(37)
0.214;-10995.0
(67)(39)
0.179;-10166.2
3J(67)
0.173;-11228.7
67(38)
0.154;-11930.0
67(3T)
0.211;-11462.5
67(3Q)
0.226;-10995.0
(38)(68)
0.187;-8636.2
6(38J)
0.220;-10995.0
6K(38)
0.176;-10527.5
(68)(3J)
0.210;-9465.0
3K(68)
0.176;-10527.5
36(8T)
0.204;-11228.7
36(8Q)
0.191;-10761.2
6(39T)
0.240;-10995.0
6Q(39)
0.241;-10527.5
(69)(3J)
0.221;-9231.2
3K(69)
0.221;-10293.8
36(9J)
0.187;-10761.2
36(9K)
0.272;-10293.8
(3T)(6Q)
0.233;-8763.8
3J(6T)
0.223;-10527.5
6T(3J)
0.172;-10527.5
6T(3K)
0.220;-10060.0
6Q(3J)
0.244;-10060.0
(6J)(3K)
0.199;-8296.2
6J(3K)
0.248;-9826.2
6K(3Q)
0.226;-9592.5
36(QK)
0.201;-9592.5
(37)(78)
0.285;-8636.2
7(37J)
0.225;-9465.0
7K(37)
0.239;-8997.5
(378Q)
0.211;-10527.5
8(37T)
0.192;-10995.0
8Q(37)
0.239;-10527.5
J(379)
0.196;-10527.5
9T(37)
0.230;-10761.2
(37)(9K)
0.280;-8530.0
K(37T)
0.190;-9826.2
T(37K)
0.201;-9826.2
JJ(37)
0.201;-8530.0
(37QK)
0.212;-9358.8
3777
0.211;-10400.0
37(7T)
0.188;-9698.8
77(3K)
0.231;-8997.5
7(38T)
0.199;-10995.0
7Q(38)
0.228;-10527.5
(78)(3T)
0.216;-9465.0
3Q(78)
0.223;-10527.5
3789
0.182;-12758.8
378J
0.176;-12291.2
378K
0.173;-11823.8
7J(39)
0.186;-10527.5
(79)(3T)
0.226;-9231.2
3Q(79)
0.230;-10293.8
379T
0.191;-12291.2
379Q
0.209;-11823.8
(3T)(7J)
0.236;-8763.8
3T(7T)
0.256;-8997.5
3(7TK)
0.247;-9826.2
3T(7Q)
0.171;-10060.0
7J(3J)
0.241;-8530.0
(7J)(3Q)
0.299;-8296.2
3J(7Q)
0.199;-9826.2
7Q(3Q)
0.199;-8062.5
37QQ
0.208;-9592.5
37KK
0.298;-9125.0
8(38J)
0.225;-8997.5
8K(38)
0.226;-8530.0
(389K)
0.275;-9826.2
9J(38)
0.226;-10293.8
(38TJ)
0.254;-10060.0
(38)(TJ)
0.261;-8530.0
J(38J)
0.241;-8296.2
JQ(38)
0.211;-9592.5
Q(38K)
0.238;-9125.0
3889
0.225;-10995.0
38(8Q)
0.263;-8763.8
(39)(8T)
0.216;-8997.5
8(39K)
0.228;-9826.2
3(89J)
0.205;-10293.8
3899
0.199;-10761.2
389J
0.144;-11823.8
389K
0.211;-11356.2
8Q(3T)
0.272;-9826.2
(8T)(3Q)
0.225;-8296.2
3T(8J)
0.209;-10060.0
3T(8K)
0.253;-9592.5
8(3JK)
0.229;-9358.8
3(8JK)
0.190;-9358.8
3J(8K)
0.188;-9358.8
3Q(8Q)
0.272;-7828.7
38QK
0.209;-10655.0
9T(39)
0.249;-8763.8
(39)(9K)
0.246;-6532.5
K(39T)
0.250;-9358.8
T(39K)
0.199;-9358.8
JJ(39)
0.275;-8062.5
(39QK)
0.253;-8891.2
3999
0.203;-8997.5
39(9Q)
0.262;-8296.2
(3T)(9J)
0.225;-8296.2
3T(9T)
0.225;-8530.0
3(9TK)
0.248;-9358.8
3T(9Q)
0.223;-9592.5
9J(3J)
0.271;-8062.5
(9J)(3Q)
0.240;-7828.8
3J(9Q)
0.239;-9358.8
9Q(3Q)
0.252;-7595.0
39QQ
0.258;-9125.0
39KK
0.234;-8657.5
T(3TK)
0.300;-7595.0
JJ(3T)
0.273;-7828.7
(3TQK)
0.231;-8657.5
3TTT
0.260;-8296.2
3T(TK)
0.245;-7595.0
(3J)(TK)
0.202;-7361.2
3K(TJ)
0.198;-8891.2
3T(JK)
0.255;-8891.2
(TQ)(3K)
0.231;-7127.5
(3K)(TK)
0.283;-5363.7
J(3JK)
0.303;-7127.5
(3J)(QK)
0.317;-6893.7
JJ(3K)
0.311;-7127.5
3Q(JQ)
0.207;-7127.5
3JQK
0.176;-9953.7
QK(3Q)
0.276;-6660.0
QK(3K)
0.235;-6426.2
44(46)
0.173;-10272.5
44(4T)
0.268;-9337.5
(45)(45)
0.258;-8742.5
4(458)
0.210;-11101.2
4T(45)
0.189;-10633.8
(45)(4K)
0.267;-8402.5
4457
0.165;-12865.0
44(5T)
0.186;-10633.8
45(4K)
0.221;-9932.5
4(468)
0.189;-10867.5
4T(46)
0.202;-10400.0
(46)(4K)
0.237;-8168.7
4468
0.175;-12397.5
44(6J)
0.227;-10166.2
(47)(47)
0.241;-7807.5
4(47T)
0.200;-10166.2
4Q(47)
0.237;-9698.8
47(49)
0.219;-10400.0
447J
0.180;-11462.5
48(48)
0.193;-8870.0
(48)(4J)
0.226;-8168.7
4488
0.273;-10400.0
44(8J)
0.215;-9698.8
(49)(49)
0.247;-6872.5
4(49Q)
0.232;-9231.2
44(9T)
0.210;-9698.8
49(4K)
0.259;-8997.5
4(4TQ)
0.212;-8997.5
44(TJ)
0.209;-9231.2
(4J)(4J)
0.237;-5937.5
44JJ
0.246;-8997.5
4Q(4Q)
0.259;-7000.0
(4K)(4K)
0.272;-5002.5
(45)(57)
0.211;-9571.3
5(45T)
0.189;-10400.0
5Q(45)
0.211;-9932.5
8(456)
0.203;-12163.8
Q(456)
0.201;-11228.7
(45)(68)
0.201;-10633.8
6(45J)
0.237;-11462.5
6K(45)
0.234;-10995.0
(457J)
0.222;-11228.7
(45)(78)
0.211;-10400.0
7(45J)
0.229;-11228.7
7K(45)
0.238;-10761.2
(458Q)
0.198;-10761.2
8(45T)
0.148;-11228.7
8Q(45)
0.192;-10761.2
J(459)
0.220;-10761.2
9T(45)
0.244;-10995.0
(45)(9K)
0.234;-8763.8
K(45T)
0.218;-10060.0
T(45K)
0.224;-10060.0
JJ(45)
0.201;-8763.8
(45QK)
0.217;-9592.5
4555
0.226;-11568.8
45(58)
0.255;-10867.5
55(4J)
0.192;-10166.2
455K
0.171;-11228.7
58(46)
0.144;-12163.8
(46)(5J)
0.216;-9932.5
46(56)
0.179;-11101.2
4(569)
0.213;-11930.0
(56)(4Q)
0.259;-9698.8
46(57)
0.181;-12397.5
46(59)
0.215;-11930.0
46(5J)
0.204;-11462.5
46(5K)
0.248;-10995.0
5(479)
0.184;-11696.2
5J(47)
0.175;-11228.7
(57)(48)
0.203;-10400.0
4T(57)
0.166;-11462.5
4(57K)
0.161;-10761.2
47(59)
0.224;-11696.2
47(5J)
0.172;-11228.7
47(5K)
0.229;-10761.2
5(48T)
0.229;-11228.7
5Q(48)
0.176;-10761.2
(58)(4T)
0.197;-9698.8
4Q(58)
0.201;-10761.2
4589
0.140;-12992.5
458J
0.148;-12525.0
458K
0.190;-12057.5
5J(49)
0.178;-10761.2
(59)(4T)
0.213;-9465.0
4Q(59)
0.180;-10527.5
459T
0.177;-12525.0
459Q
0.185;-12057.5
(4T)(5J)
0.258;-8997.5
4T(5T)
0.223;-9231.2
4(5TK)
0.271;-10060.0
4T(5Q)
0.164;-10293.8
5J(4J)
0.245;-8763.8
(5J)(4Q)
0.235;-8530.0
4J(5Q)
0.201;-10060.0
5Q(4Q)
0.233;-8296.2
45QQ
0.177;-9826.2
45KK
0.236;-9358.8
6(469)
0.211;-10166.2
6J(46)
0.222;-9698.8
(4678)
0.176;-11696.2
(467Q)
0.274;-10761.2
7(469)
0.147;-11462.5
7J(46)
0.190;-10995.0
(4689)
0.180;-11228.7
(468K)
0.172;-10293.8
8T(46)
0.209;-10995.0
(46)(8K)
0.198;-8763.8
Q(469)
0.178;-10293.8
(46)(9J)
0.285;-8997.5
T(46T)
0.180;-8997.5
T(46J)
0.231;-10293.8
TK(46)
0.273;-9826.2
(46)(JQ)
0.231;-8296.2
QQ(46)
0.210;-8062.5
46(67)
0.225;-10633.8
66(4T)
0.186;-9932.5
466Q
0.209;-10995.0
68(47)
0.211;-11696.2
(47)(6J)
0.240;-9465.0
47(67)
0.274;-10400.0
4(67T)
0.175;-11228.7
(67)(4K)
0.235;-8997.5
67(49)
0.212;-11462.5
67(4J)
0.208;-10995.0
67(4K)
0.157;-10527.5
69(48)
0.236;-11228.7
(48)(6Q)
0.261;-8997.5
49(68)
0.209;-11228.7
4(68Q)
0.190;-10527.5
46(89)
0.188;-11228.7
46(8J)
0.218;-10761.2
46(8K)
0.210;-10293.8
(49)(6J)
0.218;-8997.5
49(69)
0.176;-9465.0
4(69Q)
0.197;-10293.8
46(9T)
0.149;-10761.2
46(9Q)
0.197;-10293.8
6(4TJ)
0.253;-10293.8
6K(4T)
0.284;-9826.2
(6T)(4K)
0.232;-8296.2
6T(4Q)
0.190;-10060.0
(4J)(6J)
0.255;-7000.0
4J(6J)
0.208;-8530.0
6J(4Q)
0.199;-9826.2
(4Q)(6Q)
0.275;-6532.5
4K(6Q)
0.241;-9358.8
4K(6K)
0.273;-7595.0
79(47)
0.269;-9698.8
(47)(7Q)
0.263;-7467.5
(478T)
0.260;-10761.2
88(47)
0.234;-9698.8
(47)(8J)
0.219;-8997.5
9(479)
0.251;-9231.2
K(479)
0.211;-9826.2
9(47Q)
0.187;-10060.0
J(47T)
0.186;-10060.0
TJ(47)
0.229;-10060.0
(47JQ)
0.207;-9592.5
J(47K)
0.286;-9358.8
(47)(QK)
0.290;-7595.0
77(49)
0.235;-9698.8
477J
0.180;-10761.2
78(48)
0.222;-9698.8
(48)(7J)
0.238;-8997.5
48(78)
0.245;-9698.8
4(78J)
0.165;-10527.5
4788
0.207;-11228.7
478T
0.139;-12291.2
478Q
0.185;-11823.8
(49)(7T)
0.275;-8997.5
7(49K)
0.176;-9826.2
4(79J)
0.225;-10293.8
4799
0.192;-10761.2
479J
0.199;-11823.8
479K
0.232;-11356.2
7Q(4T)
0.203;-9826.2
(7T)(4Q)
0.266;-8296.2
4T(7J)
0.278;-10060.0
4T(7K)
0.281;-9592.5
7(4JK)
0.201;-9358.8
4(7JK)
0.217;-9358.8
4J(7K)
0.218;-9358.8
4Q(7Q)
0.289;-7828.7
47QK
0.209;-10655.0
89(48)
0.231;-9231.2
(48)(8Q)
0.254;-7000.0
(489J)
0.195;-10060.0
(48)(9T)
0.222;-8763.8
9(48K)
0.258;-9592.5
(48TK)
0.215;-9358.8
TQ(48)
0.189;-9592.5
K(48J)
0.216;-9125.0
Q(48Q)
0.212;-7595.0
KK(48)
0.249;-7127.5
88(4J)
0.249;-8763.8
488K
0.233;-9826.2
8J(49)
0.249;-10060.0
(89)(4T)
0.222;-8763.8
4Q(89)
0.217;-9826.2
489T
0.175;-11823.8
489Q
0.188;-11356.2
(4T)(8J)
0.259;-8296.2
4T(8T)
0.243;-8530.0
4(8TK)
0.220;-9358.8
4T(8Q)
0.198;-9592.5
8J(4J)
0.299;-8062.5
(8J)(4Q)
0.242;-7828.8
4J(8Q)
0.212;-9358.8
8Q(4Q)
0.292;-7595.0
48QQ
0.253;-9125.0
48KK
0.255;-8657.5
9(49Q)
0.221;-8062.5
J(49T)
0.200;-9592.5
TJ(49)
0.212;-9592.5
(49JQ)
0.239;-9125.0
J(49K)
0.224;-8891.2
(49)(QK)
0.306;-7127.5
99(4J)
0.235;-8296.2
499K
0.214;-9358.8
9Q(4T)
0.223;-9358.8
(9T)(4Q)
0.282;-7828.8
4T(9J)
0.254;-9592.5
4T(9K)
0.245;-9125.0
9(4JK)
0.183;-8891.2
4(9JK)
0.181;-8891.2
4J(9K)
0.215;-8891.2
4Q(9Q)
0.238;-7361.2
49QK
0.262;-10187.5
TJ(4T)
0.208;-7828.7
(4TJQ)
0.239;-8891.2
J(4TK)
0.211;-8657.5
(4T)(QK)
0.286;-6893.7
TT(4Q)
0.257;-7595.0
T(4JQ)
0.240;-8891.2
4(TJQ)
0.241;-8891.2
4T(JQ)
0.227;-8891.2
T(4QK)
0.211;-8423.7
TQ(4K)
0.198;-8423.7
JJ(4J)
0.321;-5831.3
(4JQK)
0.284;-8190.0
4JJJ
0.251;-7361.2
JQ(4Q)
0.250;-6893.7
4JQQ
0.229;-8423.7
4JKK
0.216;-7956.2
QQ(4K)
0.261;-6426.2
4KKK
0.256;-5958.8
55(59)
0.200;-8870.0
55(5K)
0.233;-7935.0
(56)(58)
0.226;-8870.0
5(56J)
0.228;-9698.8
5K(56)
0.217;-9231.2
56(59)
0.244;-10166.2
556J
0.245;-11228.7
57(57)
0.212;-8870.0
(57)(5T)
0.207;-8168.7
5(57K)
0.250;-8997.5
55(79)
0.177;-9932.5
57(5Q)
0.240;-9231.2
5(589)
0.249;-9698.8
5J(58)
0.249;-9231.2
58(59)
0.231;-9698.8
558J
0.182;-10761.2
59(59)
0.294;-7935.0
(59)(5Q)
0.215;-7233.8
559T
0.252;-10761.2
55(9K)
0.257;-8530.0
(5T)(5Q)
0.282;-7000.0
55TJ
0.274;-10293.8
5J(5J)
0.261;-7000.0
5J(5Q)
0.265;-8296.2
5(5QK)
0.230;-7828.7
5K(5K)
0.241;-6065.0
68(56)
0.177;-10166.2
(56)(6J)
0.285;-7935.0
7(567)
0.212;-10166.2
J(567)
0.221;-10761.2
78(56)
0.226;-11462.5
(56)(7J)
0.236;-9231.2
8(568)
0.273;-9698.8
Q(568)
0.196;-10293.8
(56)(8T)
0.275;-9231.2
8(56K)
0.216;-10060.0
(569Q)
0.192;-10060.0
9(56J)
0.214;-10293.8
9K(56)
0.243;-9826.2
TT(56)
0.261;-8763.8
(56)(TK)
0.296;-8062.5
J(56Q)
0.190;-9592.5
K(56Q)
0.270;-9125.0
66(57)
0.204;-10400.0
5669
0.161;-11462.5
56(6Q)
0.286;-9231.2
(57)(68)
0.184;-9932.5
6(57J)
0.197;-10761.2
6K(57)
0.209;-10293.8
(67)(5T)
0.198;-9465.0
5Q(67)
0.181;-10527.5
5678
0.155;-12992.5
567T
0.175;-12525.0
567Q
0.202;-12057.5
(58)(69)
0.203;-9465.0
6(58Q)
0.186;-10293.8
5(689)
0.161;-10995.0
(68)(5Q)
0.226;-8763.8
58(69)
0.168;-10995.0
58(6J)
0.232;-10527.5
58(6K)
0.222;-10060.0
6(59J)
0.197;-10293.8
6K(59)
0.242;-9826.2
(69)(5Q)
0.261;-8530.0
59(6T)
0.222;-10527.5
59(6Q)
0.205;-10060.0
6T(5T)
0.245;-8763.8
(5T)(6K)
0.265;-8062.5
5Q(6T)
0.190;-9826.2
56TJ
0.190;-11590.0
56TK
0.219;-11122.5
6K(5J)
0.279;-9358.8
56JJ
0.198;-9826.2
56JK
0.239;-10888.8
5(6QK)
0.204;-9125.0
6K(5K)
0.254;-7361.2
(57)(79)
0.240;-7935.0
7(57Q)
0.197;-8763.8
9(578)
0.183;-10761.2
K(578)
0.212;-9826.2
8(57J)
0.211;-10293.8
8K(57)
0.235;-9826.2
(579K)
0.186;-9592.5
9J(57)
0.235;-10060.0
(57TJ)
0.204;-9826.2
(57)(TJ)
0.276;-8296.2
J(57J)
0.284;-8062.5
JQ(57)
0.238;-9358.8
Q(57K)
0.221;-8891.2
5778
0.246;-11228.7
57(7J)
0.215;-8997.5
(58)(78)
0.301;-7935.0
7(58J)
0.172;-10293.8
7K(58)
0.207;-9826.2
(78)(5J)
0.207;-8763.8
5K(78)
0.166;-9826.2
57(8T)
0.182;-10527.5
57(8Q)
0.236;-10060.0
7(59T)
0.218;-10293.8
7Q(59)
0.246;-9826.2
(79)(5J)
0.226;-8530.0
5K(79)
0.265;-9592.5
57(9J)
0.259;-10060.0
57(9K)
0.228;-9592.5
(5T)(7Q)
0.234;-8062.5
5J(7T)
0.246;-9826.2
7T(5J)
0.226;-9826.2
7T(5K)
0.217;-9358.8
7Q(5J)
0.238;-9358.8
(7J)(5K)
0.214;-7595.0
7J(5K)
0.226;-9125.0
7K(5Q)
0.238;-8891.2
57(QK)
0.252;-8891.2
(58)(89)
0.246;-7467.5
8(58Q)
0.269;-8296.2
T(589)
0.211;-10060.0
9(58T)
0.270;-10060.0
9Q(58)
0.226;-9592.5
Q(58T)
0.234;-9358.8
(58)(TQ)
0.263;-7828.8
(58JK)
0.225;-8891.2
JK(58)
0.284;-8891.2
K(58K)
0.263;-6893.7
588T
0.229;-10293.8
58(8K)
0.214;-8062.5
(59)(8J)
0.284;-8296.2
59(89)
0.252;-8763.8
5(89Q)
0.261;-9592.5
58(9T)
0.217;-10060.0
58(9Q)
0.246;-9592.5
8(5TJ)
0.243;-9592.5
8K(5T)
0.197;-9125.0
(8T)(5K)
0.279;-7595.0
8T(5Q)
0.230;-9358.8
(5J)(8J)
0.214;-6298.7
5J(8J)
0.313;-7828.7
8J(5Q)
0.185;-9125.0
(5Q)(8Q)
0.328;-5831.3
5K(8Q)
0.218;-8657.5
5K(8K)
0.270;-6893.7
9J(59)
0.218;-8062.5
(59TJ)
0.281;-9358.8
(59)(TJ)
0.270;-7828.8
J(59J)
0.302;-7595.0
JQ(59)
0.237;-8891.2
Q(59K)
0.237;-8423.7
599T
0.229;-9826.2
59(9K)
0.241;-7595.0
(5T)(9Q)
0.204;-7595.0
5J(9T)
0.227;-9358.8
9T(5J)
0.228;-9358.8
9T(5K)
0.193;-8891.2
9Q(5J)
0.178;-8891.2
(9J)(5K)
0.290;-7127.5
9J(5K)
0.193;-8657.5
9K(5Q)
0.264;-8423.7
59(QK)
0.256;-8423.7
(5T)(TJ)
0.263;-6065.0
J(5TJ)
0.299;-7361.2
JQ(5T)
0.259;-8657.5
Q(5TK)
0.257;-8190.0
5TTJ
0.224;-9125.0
TJ(5J)
0.298;-7361.2
(TJ)(5Q)
0.214;-7127.5
5J(TQ)
0.275;-8657.5
TQ(5Q)
0.243;-6893.7
5TQQ
0.246;-8423.7
5TKK
0.238;-7956.2
Q(5JQ)
0.272;-6660.0
KK(5J)
0.219;-6192.5
(5Q)(JQ)
0.325;-5130.0
5K(JQ)
0.264;-7956.2
5K(JK)
0.284;-6192.5
5QQQ
0.257;-6426.2
KK(5K)
0.348;-4195.0
6669
0.178;-9698.8
666K
0.229;-8763.8
69(67)
0.238;-9465.0
(67)(6Q)
0.241;-7233.8
6678
0.171;-11228.7
66(7J)
0.235;-8997.5
(68)(68)
0.258;-6405.0
6(68J)
0.205;-8763.8
6K(68)
0.204;-8296.2
68(6J)
0.230;-8763.8
668K
0.201;-9826.2
6J(69)
0.231;-8530.0
69(6T)
0.180;-8763.8
669Q
0.222;-9826.2
6J(6T)
0.209;-8296.2
6T(6J)
0.241;-8296.2
66TK
0.266;-9358.8
6K(6J)
0.319;-7595.0
(6Q)(6Q)
0.314;-4535.0
66QK
0.198;-8891.2
7(679)
0.277;-9231.2
7J(67)
0.212;-8763.8
(6789)
0.232;-10527.5
(678K)
0.191;-9592.5
8T(67)
0.222;-10293.8
(67)(8K)
0.244;-8062.5
Q(679)
0.220;-9592.5
(67)(9J)
0.291;-8296.2
T(67T)
0.256;-8296.2
T(67J)
0.181;-9592.5
TK(67)
0.263;-9125.0
(67)(JQ)
0.246;-7595.0
QQ(67)
0.287;-7361.2
67(78)
0.187;-9465.0
77(6J)
0.266;-8763.8
677K
0.171;-9826.2
7T(68)
0.203;-10293.8
(68)(7K)
0.300;-8062.5
6T(78)
0.195;-10293.8
6(78K)
0.189;-9592.5
68(7T)
0.232;-10293.8
68(7Q)
0.195;-9826.2
79(69)
0.246;-8763.8
(69)(7Q)
0.264;-8062.5
6T(79)
0.170;-10060.0
6(79K)
0.204;-9358.8
69(7J)
0.209;-9826.2
69(7K)
0.212;-9358.8
7(6TQ)
0.237;-9358.8
6(7TJ)
0.204;-9592.5
67TT
0.202;-9826.2
67TQ
0.194;-10888.8
(6J)(7Q)
0.239;-7595.0
6Q(7J)
0.223;-9125.0
67JQ
0.218;-10655.0
(6Q)(7K)
0.254;-7127.5
6Q(7K)
0.237;-8657.5
8(689)
0.237;-8763.8
8J(68)
0.245;-8296.2
(689T)
0.224;-9826.2
99(68)
0.252;-8530.0
(68)(9Q)
0.290;-7828.8
(68TQ)
0.189;-9125.0
T(68Q)
0.215;-9125.0
Q(68J)
0.216;-8891.2
(68)(JK)
0.274;-7127.5
QK(68)
0.238;-8423.7
68(8T)
0.282;-8530.0
88(6K)
0.214;-7828.7
8(69J)
0.208;-9592.5
8K(69)
0.177;-9125.0
(89)(6Q)
0.296;-7828.8
69(8T)
0.287;-9826.2
69(8Q)
0.240;-9358.8
8T(6T)
0.246;-8062.5
(6T)(8K)
0.279;-7361.2
6Q(8T)
0.175;-9125.0
68TJ
0.181;-10888.8
68TK
0.177;-10421.2
8K(6J)
0.230;-8657.5
68JJ
0.230;-9125.0
68JK
0.223;-10187.5
6(8QK)
0.266;-8423.7
8K(6K)
0.310;-6660.0
(69)(9J)
0.246;-6298.7
T(69T)
0.236;-7828.7
T(69J)
0.217;-9125.0
TK(69)
0.250;-8657.5
(69)(JQ)
0.240;-7127.5
QQ(69)
0.266;-6893.7
69(9T)
0.270;-8062.5
99(6K)
0.230;-7361.2
9(6TQ)
0.185;-8891.2
6(9TJ)
0.219;-9125.0
69TT
0.228;-9358.8
69TQ
0.215;-10421.2
(6J)(9Q)
0.267;-7127.5
6Q(9J)
0.272;-8657.5
69JQ
0.213;-10187.5
(6Q)(9K)
0.291;-6660.0
6Q(9K)
0.224;-8190.0
T(6TJ)
0.222;-7361.2
TK(6T)
0.323;-6893.7
(6T)(JQ)
0.326;-6893.7
QQ(6T)
0.216;-6660.0
6T(TJ)
0.234;-7361.2
(6J)(TJ)
0.307;-5597.5
6J(TJ)
0.259;-7127.5
TJ(6Q)
0.241;-8423.7
(6Q)(TQ)
0.346;-5130.0
6K(TQ)
0.268;-7956.2
6K(TK)
0.243;-6192.5
JK(6J)
0.296;-6426.2
K(6JK)
0.294;-5958.8
6JJK
0.234;-7956.2
6(JQK)
0.294;-7722.5
JK(6K)
0.270;-5958.8
KK(6Q)
0.234;-5725.0
6QKK
0.254;-7255.0
77(7T)
0.259;-7233.7
(78)(78)
0.261;-5937.5
7(78J)
0.299;-8296.2
7K(78)
0.264;-7828.7
78(7J)
0.222;-8296.2
778K
0.216;-9358.8
7J(79)
0.298;-8062.5
79(7T)
0.219;-8296.2
779Q
0.211;-9358.8
7J(7T)
0.199;-7828.7
7T(7J)
0.244;-7828.7
77TK
0.224;-8891.2
7K(7J)
0.280;-7127.5
(7Q)(7Q)
0.371;-4067.5
77QK
0.232;-8423.7
8(78T)
0.315;-8296.2
8Q(78)
0.292;-7828.7
J(789)
0.197;-9358.8
9T(78)
0.220;-9592.5
(78)(9K)
0.293;-7361.2
K(78T)
0.177;-8657.5
T(78K)
0.257;-8657.5
JJ(78)
0.322;-7361.2
(78QK)
0.235;-8190.0
7888
0.216;-8763.8
78(8J)
0.291;-8062.5
(79)(89)
0.254;-6766.2
8(79Q)
0.186;-9125.0
7(89T)
0.213;-9592.5
(89)(7K)
0.299;-7361.2
89(7J)
0.208;-9358.8
89(7K)
0.266;-8891.2
8J(7T)
0.300;-9125.0
(8T)(7J)
0.240;-7595.0
7K(8T)
0.211;-8657.5
78(TQ)
0.224;-8891.2
8(7JQ)
0.257;-8657.5
7(8JQ)
0.232;-8657.5
78(JQ)
0.280;-8657.5
8(7QK)
0.199;-8190.0
8Q(7K)
0.236;-8190.0
99(79)
0.271;-6532.5
(79)(9Q)
0.331;-5831.3
(79TQ)
0.246;-8657.5
T(79Q)
0.214;-8657.5
Q(79J)
0.217;-8423.7
(79)(JK)
0.282;-6660.0
QK(79)
0.290;-7956.2
79(9J)
0.250;-7595.0
(7T)(9T)
0.244;-6065.0
9(7TK)
0.242;-8423.7
7(9TQ)
0.269;-8657.5
79(TJ)
0.223;-8891.2
79(TK)
0.270;-8423.7
(7J)(9K)
0.257;-6660.0
7K(9J)
0.238;-8190.0
79(JK)
0.289;-8190.0
(9Q)(7K)
0.313;-6426.2
(7K)(9K)
0.312;-4662.5
T(7TQ)
0.225;-6893.7
Q(7TJ)
0.277;-8190.0
(7T)(JK)
0.278;-6426.2
QK(7T)
0.243;-7722.5
7T(TQ)
0.263;-6893.7
(7J)(TQ)
0.250;-6660.0
7Q(TJ)
0.228;-8190.0
7TJQ
0.227;-9720.0
(7Q)(TK)
0.276;-6192.5
7Q(TK)
0.292;-7722.5
J(7JQ)
0.314;-6426.2
K(7JQ)
0.227;-7488.8
JJ(7Q)
0.301;-6426.2
J(7QK)
0.210;-7488.8
JQ(7K)
0.234;-7488.8
QQ(7Q)
0.292;-4428.8
7Q(QK)
0.287;-5725.0
8888
0.262;-7000.0
888Q
0.324;-7595.0
8(89J)
0.232;-7595.0
8K(89)
0.271;-7127.5
89(8Q)
0.235;-7361.2
8(8TJ)
0.230;-7361.2
8K(8T)
0.271;-6893.7
8T(8K)
0.290;-6893.7
8(8JK)
0.279;-6660.0
88(JK)
0.257;-6660.0
8Q(8K)
0.322;-6426.2
(89)(9T)
0.295;-6065.0
9(89K)
0.286;-6893.7
(89TK)
0.253;-8190.0
TQ(89)
0.251;-8423.7
K(89J)
0.263;-7956.2
Q(89Q)
0.256;-6426.2
KK(89)
0.302;-5958.8
99(8Q)
0.279;-7127.5
9(8TJ)
0.235;-8657.5
9K(8T)
0.229;-8190.0
(9T)(8K)
0.281;-6660.0
9T(8Q)
0.218;-8423.7
(8J)(9J)
0.297;-5363.7
8J(9J)
0.211;-6893.7
9J(8Q)
0.223;-8190.0
(8Q)(9Q)
0.252;-4896.2
8K(9Q)
0.265;-7722.5
8K(9K)
0.238;-5958.8
TQ(8T)
0.293;-6660.0
K(8TJ)
0.288;-7722.5
Q(8TQ)
0.320;-6192.5
KK(8T)
0.324;-5725.0
