AAAA
0.448;1805.0
5AAA
0.360;-11.9
9AAA
0.359;455.6
KAAA
0.359;923.1
4A(2A)
0.342;-1531.2
(2A)(7A)
0.389;-415.6
A(2TA)
0.254;-830.0
QA(2A)
0.326;-596.2
2A(4A)
0.280;-1531.2
26AA
0.300;-2062.5
AA(29)
0.296;-946.9
2A(QA)
0.300;-596.2
A(34A)
0.272;-1414.4
6A(3A)
0.308;-1180.6
(3A)(9A)
0.311;-65.0
A(3QA)
0.346;-479.4
AA(34)
0.366;-1414.4
3A(7A)
0.342;-1063.7
39AA
0.269;-1595.0
AA(3Q)
0.402;-479.4
(4A)(5A)
0.299;-415.6
A(48A)
0.277;-830.0
TA(4A)
0.386;-596.2
(4A)(KA)
0.306;519.4
46AA
0.339;-1828.7
AA(49)
0.280;-713.1
4A(QA)
0.338;-362.5
A(56A)
0.286;-946.9
8A(5A)
0.355;-713.1
(5A)(JA)
0.302;402.5
55AA
0.279;-1063.7
AA(58)
0.336;-713.1
5A(JA)
0.331;-362.5
5KAA
0.287;-893.8
8A(6A)
0.401;-596.2
(6A)(JA)
0.338;519.4
66AA
0.338;-830.0
AA(69)
0.270;-479.4
6A(QA)
0.354;-128.8
A(78A)
0.389;-479.4
TA(7A)
0.386;-245.6
(7A)(KA)
0.427;870.0
79AA
0.333;-1127.5
AA(7Q)
0.309;-11.9
(8A)(9A)
0.384;519.4
A(8QA)
0.415;105.0
AA(89)
0.310;-245.6
8A(QA)
0.320;105.0
A(9TA)
0.375;-11.9
QA(9A)
0.379;221.9
9A(JA)
0.296;105.0
9KAA
0.345;-426.2
QA(TA)
0.317;338.7
TA(QA)
0.395;338.7
A(JQA)
0.335;455.6
AA(JQ)
0.321;455.6
(QA)(KA)
0.455;1454.4
KKAA
0.361;806.3
2(25A)
0.196;-2816.9
27(2A)
0.283;-2583.1
(2T)(2A)
0.242;-1467.5
2(2KA)
0.273;-1881.9
(236A)
0.264;-3348.1
(23TA)
0.256;-2880.6
33(2A)
0.210;-2933.8
(36)(2A)
0.269;-2583.1
3(29A)
0.222;-2997.5
3J(2A)
0.278;-2763.8
(245A)
0.213;-3348.1
(249A)
0.246;-2880.6
(24KA)
0.258;-2413.1
46(2A)
0.311;-3231.2
(49)(2A)
0.244;-2115.6
4(2QA)
0.289;-2530.0
6(25A)
0.278;-3114.4
T(25A)
0.200;-2646.9
5(26A)
0.249;-3114.4
58(2A)
0.261;-2880.6
(5J)(2A)
0.319;-1765.0
6(26A)
0.269;-2232.5
T(26A)
0.261;-2530.0
6(27A)
0.237;-2880.6
69(2A)
0.246;-2646.9
(6Q)(2A)
0.365;-1531.3
(279A)
0.207;-2530.0
(27KA)
0.285;-2062.5
79(2A)
0.215;-2530.0
(7Q)(2A)
0.367;-1414.4
(28TA)
0.298;-2296.2
88(2A)
0.279;-1765.0
(8J)(2A)
0.292;-1414.4
9(29A)
0.332;-1531.2
K(29A)
0.269;-1828.7
9(2QA)
0.347;-1945.6
J(2TA)
0.253;-1945.6
TJ(2A)
0.260;-1945.6
(2JQA)
0.268;-1711.9
J(2KA)
0.349;-1595.0
(QK)(2A)
0.327;-713.1
22(4A)
0.241;-2933.8
226A
0.224;-3465.0
2A(29)
0.279;-2349.4
22(QA)
0.330;-1998.7
2(34A)
0.227;-3581.9
26(3A)
0.257;-3348.1
(29)(3A)
0.257;-2232.5
2(3QA)
0.270;-2646.9
A(234)
0.226;-3581.9
(23)(7A)
0.215;-2466.2
9A(23)
0.213;-2997.5
A(23Q)
0.256;-2646.9
2A(34)
0.244;-3581.9
2A(36)
0.251;-3348.1
2A(38)
0.251;-3114.4
2A(3T)
0.257;-2880.6
2A(3Q)
0.215;-2646.9
2(45A)
0.211;-3348.1
27(4A)
0.229;-3114.4
(2T)(4A)
0.273;-1998.7
2(4KA)
0.263;-2413.1
A(246)
0.282;-3231.2
(24)(9A)
0.296;-2115.6
JA(24)
0.250;-2646.9
24(5A)
0.212;-3348.1
24(7A)
0.236;-3114.4
24(9A)
0.215;-2880.6
24(JA)
0.286;-2646.9
24(KA)
0.274;-2413.1
26(5A)
0.221;-3114.4
(29)(5A)
0.313;-1998.7
2(5QA)
0.274;-2413.1
A(256)
0.231;-3114.4
(25)(9A)
0.272;-1998.7
JA(25)
0.331;-2530.0
25(6A)
0.209;-3114.4
25(8A)
0.256;-2880.6
25(TA)
0.290;-2646.9
25(QA)
0.284;-2413.1
(26)(6A)
0.310;-1467.5
2(69A)
0.201;-2646.9
2J(6A)
0.256;-2413.1
(26)(7A)
0.246;-2115.6
9A(26)
0.254;-2646.9
A(26Q)
0.258;-2296.2
2A(67)
0.239;-2880.6
2A(69)
0.250;-2646.9
2A(6J)
0.227;-2413.1
2A(6K)
0.268;-2179.4
(29)(7A)
0.331;-1765.0
2(7QA)
0.237;-2179.4
A(278)
0.233;-2646.9
(27)(JA)
0.337;-1531.3
KA(27)
0.254;-2062.5
2A(79)
0.206;-2530.0
2A(7J)
0.204;-2296.2
2A(7K)
0.299;-2062.5
(2T)(8A)
0.348;-1531.3
2(8KA)
0.271;-1945.6
A(28T)
0.340;-2296.2
(28)(KA)
0.288;-1180.6
28(TA)
0.281;-2296.2
28(QA)
0.276;-2062.5
(29)(9A)
0.328;-766.2
2(9QA)
0.288;-1945.6
A(29T)
0.311;-2179.4
(29)(KA)
0.278;-1063.7
29(JA)
0.285;-2062.5
29(KA)
0.276;-1828.7
2J(TA)
0.266;-1945.6
(2T)(JA)
0.306;-1180.6
KA(2T)
0.291;-1711.9
2A(TQ)
0.356;-1828.7
2(JQA)
0.284;-1711.9
A(2JQ)
0.338;-1711.9
2A(JQ)
0.267;-1711.9
2(QKA)
0.331;-1478.1
2Q(KA)
0.274;-1478.1
33(3A)
0.313;-2051.9
(36)(3A)
0.288;-1701.2
3(39A)
0.319;-2115.6
3J(3A)
0.250;-1881.9
(345A)
0.205;-3231.2
(349A)
0.255;-2763.8
(34KA)
0.234;-2296.2
46(3A)
0.250;-3114.4
(49)(3A)
0.306;-1998.7
4(3QA)
0.213;-2413.1
6(35A)
0.278;-2997.5
T(35A)
0.325;-2530.0
5(36A)
0.230;-2997.5
58(3A)
0.288;-2763.8
(5J)(3A)
0.277;-1648.1
6(36A)
0.228;-2115.6
T(36A)
0.233;-2413.1
6(37A)
0.234;-2763.8
69(3A)
0.298;-2530.0
(6Q)(3A)
0.352;-1414.4
(379A)
0.257;-2413.1
(37KA)
0.321;-1945.6
79(3A)
0.216;-2413.1
(7Q)(3A)
0.288;-1297.5
(38TA)
0.280;-2179.4
88(3A)
0.366;-1648.1
(8J)(3A)
0.322;-1297.5
9(39A)
0.314;-1414.4
K(39A)
0.301;-1711.9
9(3QA)
0.305;-1828.7
J(3TA)
0.236;-1828.7
TJ(3A)
0.265;-1828.7
(3JQA)
0.281;-1595.0
J(3KA)
0.296;-1478.1
(QK)(3A)
0.283;-596.2
33(5A)
0.270;-2583.1
337A
0.253;-3114.4
3A(3T)
0.237;-1998.7
33(KA)
0.244;-1648.1
3(46A)
0.255;-3114.4
38(4A)
0.243;-2880.6
(3J)(4A)
0.297;-1765.0
4A(34)
0.243;-2583.1
A(347)
0.266;-2997.5
(34)(TA)
0.236;-1881.9
QA(34)
0.238;-2413.1
345A
0.235;-3996.2
347A
0.231;-3762.5
349A
0.250;-3528.8
34JA
0.247;-3295.0
34KA
0.215;-3061.2
37(5A)
0.247;-2880.6
(3T)(5A)
0.340;-1765.0
3(5KA)
0.257;-2179.4
A(357)
0.288;-2880.6
(35)(TA)
0.322;-1765.0
QA(35)
0.343;-2296.2
356A
0.243;-3762.5
358A
0.241;-3528.8
35TA
0.252;-3295.0
35QA
0.298;-3061.2
(37)(6A)
0.261;-1998.7
3(6TA)
0.225;-2413.1
3Q(6A)
0.279;-2179.4
(36)(8A)
0.279;-1881.9
TA(36)
0.269;-2413.1
A(36K)
0.273;-2062.5
6A(38)
0.251;-2646.9
6A(3T)
0.259;-2413.1
6A(3Q)
0.238;-2179.4
37(7A)
0.250;-1881.9
(3T)(7A)
0.331;-1531.3
3(7KA)
0.298;-1945.6
A(379)
0.233;-2413.1
(37)(QA)
0.266;-1297.5
7A(38)
0.263;-2530.0
7A(3T)
0.293;-2296.2
7A(3Q)
0.272;-2062.5
38(8A)
0.311;-1648.1
(3J)(8A)
0.300;-1297.5
8A(38)
0.270;-1648.1
A(38J)
0.295;-2062.5
388A
0.305;-2413.1
38TA
0.249;-2944.4
38QA
0.231;-2710.6
(3T)(9A)
0.249;-1297.5
3(9KA)
0.265;-1711.9
A(39J)
0.312;-1945.6
399A
0.299;-2179.4
39JA
0.253;-2710.6
39KA
0.330;-2476.9
3Q(TA)
0.323;-1711.9
(3T)(QA)
0.267;-946.9
TA(3J)
0.227;-1828.7
TA(3K)
0.312;-1595.0
3(JKA)
0.286;-1478.1
A(3JK)
0.321;-1478.1
JA(3K)
0.248;-1478.1
QA(3Q)
0.326;-713.1
3QKA
0.295;-2126.2
45(4A)
0.316;-2349.4
(48)(4A)
0.271;-1233.8
4(4JA)
0.286;-1648.1
4K(4A)
0.304;-1414.4
(459A)
0.325;-2530.0
(45KA)
0.251;-2062.5
57(4A)
0.241;-2763.8
(5T)(4A)
0.288;-1648.1
5(4KA)
0.261;-2062.5
(469A)
0.313;-2413.1
(46KA)
0.275;-1945.6
68(4A)
0.268;-2530.0
(6J)(4A)
0.291;-1414.4
7(47A)
0.287;-1765.0
J(47A)
0.257;-2062.5
78(4A)
0.271;-2413.1
(7J)(4A)
0.355;-1297.5
8(48A)
0.310;-1531.2
Q(48A)
0.278;-1828.7
(8T)(4A)
0.330;-1297.5
8(4KA)
0.282;-1711.9
(49QA)
0.310;-1711.9
9(4JA)
0.272;-1828.7
9K(4A)
0.254;-1595.0
TT(4A)
0.333;-1063.7
(TK)(4A)
0.362;-713.1
J(4QA)
0.372;-1478.1
K(4QA)
0.298;-1244.4
44(5A)
0.312;-2349.4
447A
0.252;-2880.6
4A(4T)
0.344;-1765.0
44(KA)
0.361;-1414.4
4(57A)
0.270;-2763.8
49(5A)
0.214;-2530.0
(4Q)(5A)
0.305;-1414.4
6A(45)
0.210;-2880.6
A(459)
0.224;-2530.0
(45)(QA)
0.314;-1414.4
5A(46)
0.254;-2880.6
5A(48)
0.258;-2646.9
5A(4T)
0.315;-2413.1
5A(4Q)
0.278;-2179.4
46(6A)
0.285;-1998.7
(49)(6A)
0.322;-1648.1
4(6QA)
0.301;-2062.5
A(467)
0.282;-2646.9
(46)(TA)
0.308;-1531.3
QA(46)
0.289;-2062.5
467A
0.186;-3411.9
469A
0.239;-3178.1
46JA
0.246;-2944.4
46KA
0.243;-2710.6
49(7A)
0.284;-2296.2
(4Q)(7A)
0.278;-1180.6
8A(47)
0.249;-2413.1
A(47J)
0.299;-2062.5
477A
0.263;-2530.0
479A
0.217;-3061.2
47JA
0.221;-2827.5
47KA
0.202;-2593.8
4T(8A)
0.301;-2062.5
(4K)(8A)
0.321;-946.9
TA(48)
0.285;-2062.5
A(48K)
0.254;-1711.9
8A(4T)
0.270;-2062.5
8A(4Q)
0.246;-1828.7
49(9A)
0.315;-1297.5
(4Q)(9A)
0.358;-946.9
TA(49)
0.212;-1945.6
A(49K)
0.251;-1595.0
9A(4J)
0.294;-1828.7
9A(4K)
0.285;-1595.0
4(TQA)
0.314;-1595.0
A(4TJ)
0.259;-1711.9
4TTA
0.275;-1828.7
4TQA
0.214;-2360.0
(4Q)(JA)
0.346;-713.1
QA(4J)
0.296;-1478.1
4JQA
0.277;-2243.1
(4K)(QA)
0.270;-479.4
QA(4K)
0.267;-1244.4
5(56A)
0.249;-1998.7
58(5A)
0.235;-1765.0
(5J)(5A)
0.341;-649.4
6(56A)
0.261;-1881.9
T(56A)
0.294;-2179.4
6(57A)
0.239;-2530.0
69(5A)
0.239;-2296.2
(6Q)(5A)
0.307;-1180.6
(579A)
0.240;-2179.4
(57KA)
0.270;-1711.9
79(5A)
0.227;-2179.4
(7Q)(5A)
0.295;-1063.7
(58TA)
0.231;-1945.6
88(5A)
0.232;-1414.4
(8J)(5A)
0.266;-1063.7
9(59A)
0.345;-1180.6
K(59A)
0.290;-1478.1
9(5QA)
0.312;-1595.0
J(5TA)
0.280;-1595.0
TJ(5A)
0.312;-1595.0
(5JQA)
0.317;-1361.2
J(5KA)
0.302;-1244.4
(QK)(5A)
0.400;-362.5
55(7A)
0.290;-1881.9
559A
0.298;-2413.1
5A(5Q)
0.278;-1297.5
(57)(6A)
0.258;-1765.0
5(6TA)
0.253;-2179.4
5Q(6A)
0.247;-1945.6
(56)(8A)
0.301;-1648.1
TA(56)
0.320;-2179.4
A(56K)
0.277;-1828.7
6A(58)
0.211;-2413.1
6A(5T)
0.285;-2179.4
6A(5Q)
0.327;-1945.6
57(7A)
0.232;-1648.1
(5T)(7A)
0.304;-1297.5
5(7KA)
0.273;-1711.9
A(579)
0.274;-2179.4
(57)(QA)
0.268;-1063.7
7A(58)
0.252;-2296.2
7A(5T)
0.235;-2062.5
7A(5Q)
0.273;-1828.7
58(8A)
0.361;-1414.4
(5J)(8A)
0.294;-1063.7
8A(58)
0.300;-1414.4
A(58J)
0.303;-1828.7
588A
0.236;-2179.4
58TA
0.210;-2710.6
58QA
0.208;-2476.9
(5T)(9A)
0.360;-1063.7
5(9KA)
0.304;-1478.1
A(59J)
0.294;-1711.9
599A
0.289;-1945.6
59JA
0.261;-2476.9
59KA
0.261;-2243.1
5Q(TA)
0.313;-1478.1
(5T)(QA)
0.322;-713.1
TA(5J)
0.314;-1595.0
TA(5K)
0.366;-1361.2
5(JKA)
0.318;-1244.4
A(5JK)
0.290;-1244.4
JA(5K)
0.293;-1244.4
QA(5Q)
0.340;-479.4
5QKA
0.341;-1892.5
67(6A)
0.263;-1648.1
(6T)(6A)
0.365;-532.5
6(6KA)
0.271;-946.9
(67TA)
0.217;-1945.6
77(6A)
0.261;-1531.2
(7T)(6A)
0.305;-1180.6
7(6KA)
0.336;-1595.0
(68JA)
0.276;-1711.9
(89)(6A)
0.260;-1180.6
8(6QA)
0.280;-1595.0
T(69A)
0.287;-1711.9
9(6TA)
0.324;-1711.9
9Q(6A)
0.305;-1478.1
Q(6TA)
0.370;-1361.2
(TQ)(6A)
0.340;-596.2
(6JKA)
0.340;-1127.5
JK(6A)
0.328;-1127.5
K(6KA)
0.316;-128.8
668A
0.218;-2296.2
6A(6J)
0.339;-1180.6
(67)(7A)
0.343;-766.2
6(7TA)
0.265;-1945.6
6Q(7A)
0.306;-1711.9
(67)(9A)
0.365;-1297.5
JA(67)
0.287;-1828.7
67(8A)
0.282;-2179.4
67(TA)
0.226;-1945.6
67(QA)
0.342;-1711.9
(68)(8A)
0.277;-532.5
6(8JA)
0.265;-1711.9
6K(8A)
0.324;-1478.1
(68)(JA)
0.353;-946.9
KA(68)
0.284;-1478.1
6A(8T)
0.311;-1828.7
6A(8Q)
0.275;-1595.0
6(9TA)
0.289;-1711.9
6Q(9A)
0.306;-1478.1
(69)(JA)
0.312;-830.0
KA(69)
0.319;-1361.2
6A(9J)
0.312;-1595.0
6A(9K)
0.326;-1361.2
(6Q)(TA)
0.339;-596.2
JA(6T)
0.333;-1478.1
6T(JA)
0.290;-1478.1
6T(KA)
0.327;-1244.4
6Q(JA)
0.291;-1244.4
(6J)(KA)
0.311;-362.5
6J(KA)
0.298;-1127.5
6K(QA)
0.280;-1010.6
6A(QK)
0.253;-1010.6
(78)(7A)
0.363;-532.5
7(7JA)
0.293;-946.9
7K(7A)
0.317;-713.1
(78QA)
0.274;-1478.1
8(7TA)
0.304;-1711.9
8Q(7A)
0.276;-1478.1
J(79A)
0.272;-1478.1
9T(7A)
0.296;-1595.0
(9K)(7A)
0.287;-479.4
K(7TA)
0.316;-1127.5
T(7KA)
0.303;-1127.5
JJ(7A)
0.295;-479.4
(7QKA)
0.297;-893.8
777A
0.279;-1414.4
7A(7T)
0.260;-1063.7
77(KA)
0.311;-713.1
7(8TA)
0.305;-1711.9
7Q(8A)
0.327;-1478.1
(78)(TA)
0.372;-946.9
QA(78)
0.314;-1478.1
789A
0.234;-2593.8
78JA
0.253;-2360.0
78KA
0.236;-2126.2
7J(9A)
0.283;-1478.1
(79)(TA)
0.330;-830.0
QA(79)
0.297;-1361.2
79TA
0.283;-2360.0
79QA
0.264;-2126.2
(7J)(TA)
0.335;-596.2
TA(7T)
0.317;-713.1
A(7TK)
0.274;-1127.5
TA(7Q)
0.324;-1244.4
7J(JA)
0.355;-479.4
(7J)(QA)
0.274;-362.5
JA(7Q)
0.320;-1127.5
7Q(QA)
0.338;-245.6
7QQA
0.261;-1010.6
7KKA
0.353;-776.9
8(8JA)
0.371;-713.1
8K(8A)
0.280;-479.4
(89KA)
0.260;-1127.5
9J(8A)
0.317;-1361.2
(8TJA)
0.338;-1244.4
(TJ)(8A)
0.259;-479.4
J(8JA)
0.292;-362.5
JQ(8A)
0.264;-1010.6
Q(8KA)
0.344;-776.9
889A
0.256;-1711.9
8A(8Q)
0.348;-596.2
(8T)(9A)
0.323;-713.1
8(9KA)
0.334;-1127.5
A(89J)
0.321;-1361.2
899A
0.301;-1595.0
89JA
0.266;-2126.2
89KA
0.273;-1892.5
8Q(TA)
0.340;-1127.5
(8T)(QA)
0.324;-362.5
TA(8J)
0.277;-1244.4
TA(8K)
0.290;-1010.6
8(JKA)
0.265;-893.8
A(8JK)
0.291;-893.8
JA(8K)
0.323;-893.8
QA(8Q)
0.373;-128.8
8QKA
0.282;-1541.9
9T(9A)
0.312;-596.2
(9K)(9A)
0.348;519.4
K(9TA)
0.287;-893.8
T(9KA)
0.344;-893.8
JJ(9A)
0.343;-245.6
(9QKA)
0.311;-660.0
999A
0.281;-713.1
9A(9Q)
0.295;-362.5
(9J)(TA)
0.270;-362.5
TA(9T)
0.331;-479.4
A(9TK)
0.248;-893.8
TA(9Q)
0.294;-1010.6
9J(JA)
0.373;-245.6
(9J)(QA)
0.383;-128.7
JA(9Q)
0.315;-893.8
9Q(QA)
0.351;-11.9
9QQA
0.357;-776.9
9KKA
0.310;-543.1
T(TKA)
0.403;-11.9
JJ(TA)
0.307;-128.8
(TQKA)
0.356;-543.1
TTTA
0.314;-362.5
TA(TK)
0.366;-11.9
(TK)(JA)
0.325;105.0
KA(TJ)
0.394;-660.0
TA(JK)
0.296;-660.0
(TQ)(KA)
0.346;221.9
(TK)(KA)
0.349;1103.8
J(JKA)
0.356;221.9
(QK)(JA)
0.332;338.8
JJ(KA)
0.382;221.9
QA(JQ)
0.285;221.9
JQKA
0.284;-1191.2
QK(QA)
0.366;455.6
QK(KA)
0.322;572.5
22(24)
0.207;-3571.2
22(28)
0.236;-3103.8
22(2Q)
0.260;-2636.2
24(23)
0.260;-4219.4
(23)(27)
0.283;-3103.8
2(23T)
0.279;-3518.1
2Q(23)
0.224;-3284.4
23(25)
0.209;-4102.5
2237
0.240;-4633.8
22(3T)
0.271;-3518.1
23(2K)
0.200;-3167.5
2(246)
0.212;-3868.8
28(24)
0.225;-3635.0
(24)(2J)
0.267;-2519.4
2244
0.221;-4102.5
22(47)
0.219;-3751.9
24(2T)
0.279;-3401.2
224Q
0.193;-3932.5
26(25)
0.220;-3751.9
(25)(29)
0.217;-2636.2
2(25Q)
0.243;-3050.6
22(56)
0.243;-3751.9
25(29)
0.300;-3401.2
225J
0.211;-3932.5
26(26)
0.216;-2870.0
(26)(29)
0.253;-2519.4
2(26Q)
0.289;-2933.8
22(67)
0.236;-3518.1
26(2T)
0.192;-3167.5
226Q
0.211;-3698.8
28(27)
0.289;-3284.4
(27)(2J)
0.297;-2168.8
2277
0.276;-3401.2
22(7T)
0.240;-3050.6
27(2K)
0.267;-2700.0
2(28T)
0.289;-2933.8
2Q(28)
0.247;-2700.0
28(2T)
0.249;-2933.8
228Q
0.204;-3465.0
2T(29)
0.249;-2816.9
(29)(2K)
0.273;-1701.2
229J
0.219;-3465.0
2T(2T)
0.314;-1935.0
(2T)(2K)
0.311;-1584.4
22TQ
0.238;-3231.2
2Q(2J)
0.269;-2349.4
2J(2K)
0.269;-2232.5
22QQ
0.273;-2232.5
3(234)
0.163;-4102.5
36(23)
0.268;-3868.8
(23)(39)
0.284;-2753.1
3(23Q)
0.246;-3167.5
5(234)
0.218;-4633.8
9(234)
0.239;-4166.2
K(234)
0.243;-3698.8
4(237)
0.261;-4400.0
49(23)
0.289;-4166.2
(23)(4Q)
0.233;-3050.6
(2357)
0.271;-4283.1
(235J)
0.230;-3815.6
(23)(56)
0.257;-3635.0
5(239)
0.287;-4049.4
5J(23)
0.267;-3815.6
(2367)
0.206;-4166.2
(236J)
0.245;-3698.8
(23)(67)
0.270;-3401.2
6(23T)
0.247;-3815.6
6Q(23)
0.233;-3581.9
9(237)
0.164;-3815.6
K(237)
0.199;-3348.1
7(23T)
0.254;-3698.8
7Q(23)
0.267;-3465.0
T(238)
0.265;-3581.9
8(239)
0.205;-3698.8
8J(23)
0.215;-3465.0
(239T)
0.241;-3465.0
99(23)
0.269;-2816.9
(23)(9Q)
0.267;-2466.2
(23TQ)
0.206;-3114.4
T(23Q)
0.250;-3114.4
Q(23J)
0.263;-2997.5
(23)(JK)
0.295;-2115.6
QK(23)
0.228;-2763.8
23(35)
0.216;-3985.6
33(28)
0.242;-3635.0
233T
0.258;-4166.2
23(3K)
0.262;-3050.6
(24)(36)
0.222;-3751.9
3(249)
0.178;-4166.2
3J(24)
0.181;-3932.5
(34)(25)
0.164;-3868.8
27(34)
0.190;-4400.0
2(34T)
0.207;-4049.4
(34)(2K)
0.254;-2933.8
34(26)
0.189;-4516.9
34(28)
0.187;-4283.1
34(2T)
0.194;-4049.4
34(2Q)
0.203;-3815.6
(25)(35)
0.257;-2986.9
3(258)
0.236;-4166.2
3T(25)
0.209;-3932.5
(25)(3K)
0.200;-2816.9
27(35)
0.207;-4283.1
2(35T)
0.259;-3932.5
(35)(2K)
0.265;-2816.9
35(27)
0.203;-4283.1
35(29)
0.226;-4049.4
35(2J)
0.221;-3815.6
35(2K)
0.178;-3581.9
37(26)
0.222;-4166.2
(26)(3T)
0.231;-3050.6
3(26K)
0.253;-3465.0
2(368)
0.176;-4049.4
(36)(2J)
0.286;-2933.8
2K(36)
0.237;-3465.0
23(68)
0.217;-4049.4
23(6T)
0.264;-3815.6
23(6Q)
0.283;-3581.9
3(278)
0.279;-3932.5
3T(27)
0.265;-3698.8
(27)(3K)
0.260;-2583.1
29(37)
0.215;-3815.6
2(37Q)
0.226;-3465.0
23(78)
0.244;-3932.5
23(7T)
0.219;-3698.8
23(7Q)
0.199;-3465.0
3(289)
0.244;-3698.8
3J(28)
0.299;-3465.0
(38)(29)
0.241;-2933.8
2J(38)
0.248;-3465.0
38(29)
0.231;-3698.8
38(2J)
0.252;-3465.0
38(2K)
0.278;-3231.2
3T(29)
0.220;-3465.0
(29)(3K)
0.245;-2349.4
2J(39)
0.221;-3348.1
39(2T)
0.275;-3465.0
39(2Q)
0.259;-3231.2
(2T)(3T)
0.340;-1818.1
3(2TK)
0.283;-2997.5
2(3TQ)
0.185;-3114.4
23(TJ)
0.205;-3231.2
23(TK)
0.310;-2997.5
(2J)(3K)
0.231;-2115.6
2K(3J)
0.264;-2880.6
23(JK)
0.212;-2880.6
(3Q)(2K)
0.272;-1998.7
(2K)(3K)
0.317;-1116.9
4(246)
0.232;-3635.0
48(24)
0.236;-3401.2
(24)(4J)
0.297;-2285.6
5(245)
0.199;-3635.0
9(245)
0.216;-3932.5
K(245)
0.259;-3465.0
5(248)
0.210;-4049.4
5T(24)
0.262;-3815.6
(24)(5K)
0.269;-2700.0
9(246)
0.219;-3815.6
K(246)
0.225;-3348.1
6(249)
0.233;-3815.6
6J(24)
0.237;-3581.9
(2478)
0.252;-3815.6
(247Q)
0.229;-3348.1
7(249)
0.211;-3698.8
7J(24)
0.224;-3465.0
(2489)
0.236;-3581.9
(248K)
0.219;-3114.4
8T(24)
0.269;-3465.0
(24)(8K)
0.264;-2349.4
Q(249)
0.208;-3114.4
(24)(9J)
0.285;-2466.2
T(24T)
0.240;-2466.2
T(24J)
0.298;-3114.4
TK(24)
0.272;-2880.6
(24)(JQ)
0.244;-2115.6
QQ(24)
0.310;-1998.7
24(45)
0.262;-3751.9
44(28)
0.237;-3401.2
244T
0.198;-3932.5
24(4K)
0.267;-2816.9
(25)(47)
0.224;-3401.2
4(25T)
0.241;-3815.6
4Q(25)
0.236;-3581.9
(45)(27)
0.215;-3401.2
29(45)
0.183;-3932.5
2(45Q)
0.210;-3581.9
24(56)
0.196;-4283.1
24(58)
0.233;-4049.4
24(5T)
0.196;-3815.6
24(5Q)
0.251;-3581.9
4(267)
0.209;-4049.4
49(26)
0.266;-3815.6
(26)(4Q)
0.216;-2700.0
27(46)
0.238;-4049.4
2(46T)
0.208;-3698.8
(46)(2K)
0.251;-2583.1
46(28)
0.243;-3932.5
46(2T)
0.217;-3698.8
46(2Q)
0.204;-3465.0
(27)(47)
0.317;-2402.5
4(27T)
0.247;-3581.9
4Q(27)
0.234;-3348.1
(47)(29)
0.281;-2933.8
2J(47)
0.254;-3465.0
47(28)
0.238;-3815.6
47(2T)
0.235;-3581.9
47(2Q)
0.230;-3348.1
(28)(48)
0.288;-2168.8
4(28J)
0.290;-3348.1
4K(28)
0.235;-3114.4
(48)(2J)
0.232;-2583.1
2K(48)
0.258;-3114.4
24(8T)
0.269;-3465.0
24(8Q)
0.263;-3231.2
4(29T)
0.197;-3348.1
4Q(29)
0.226;-3114.4
(49)(2J)
0.265;-2466.2
2K(49)
0.246;-2997.5
24(9J)
0.318;-3231.2
24(9K)
0.288;-2997.5
(2T)(4Q)
0.220;-2232.5
2J(4T)
0.271;-3114.4
4T(2J)
0.226;-3114.4
4T(2K)
0.212;-2880.6
4Q(2J)
0.268;-2880.6
(4J)(2K)
0.279;-1998.7
4J(2K)
0.280;-2763.8
4K(2Q)
0.273;-2646.9
24(QK)
0.278;-2646.9
(25)(56)
0.224;-2636.2
5(259)
0.240;-3050.6
5J(25)
0.313;-2816.9
(2567)
0.262;-3932.5
(256J)
0.195;-3465.0
(25)(67)
0.250;-3167.5
6(25T)
0.282;-3581.9
6Q(25)
0.279;-3348.1
9(257)
0.226;-3581.9
K(257)
0.296;-3114.4
7(25T)
0.214;-3465.0
7Q(25)
0.258;-3231.2
T(258)
0.193;-3348.1
8(259)
0.250;-3465.0
8J(25)
0.267;-3231.2
(259T)
0.259;-3231.2
99(25)
0.224;-2583.1
(25)(9Q)
0.270;-2232.5
(25TQ)
0.232;-2880.6
T(25Q)
0.220;-2880.6
Q(25J)
0.252;-2763.8
(25)(JK)
0.314;-1881.9
QK(25)
0.277;-2530.0
25(57)
0.297;-3284.4
55(2T)
0.215;-2933.8
255Q
0.253;-3465.0
57(26)
0.227;-3932.5
(26)(5T)
0.230;-2816.9
5(26K)
0.203;-3231.2
2(568)
0.262;-3815.6
(56)(2J)
0.279;-2700.0
2K(56)
0.253;-3231.2
25(68)
0.226;-3815.6
25(6T)
0.236;-3581.9
25(6Q)
0.184;-3348.1
5(278)
0.237;-3698.8
5T(27)
0.250;-3465.0
(27)(5K)
0.245;-2349.4
29(57)
0.294;-3581.9
2(57Q)
0.233;-3231.2
25(78)
0.211;-3698.8
25(7T)
0.256;-3465.0
25(7Q)
0.301;-3231.2
5(289)
0.278;-3465.0
5J(28)
0.229;-3231.2
(58)(29)
0.265;-2700.0
2J(58)
0.274;-3231.2
58(29)
0.191;-3465.0
58(2J)
0.223;-3231.2
58(2K)
0.271;-2997.5
5T(29)
0.196;-3231.2
(29)(5K)
0.220;-2115.6
2J(59)
0.316;-3114.4
59(2T)
0.224;-3231.2
59(2Q)
0.255;-2997.5
(2T)(5T)
0.320;-1584.4
5(2TK)
0.281;-2763.8
2(5TQ)
0.271;-2880.6
25(TJ)
0.252;-2997.5
25(TK)
0.264;-2763.8
(2J)(5K)
0.288;-1881.9
2K(5J)
0.253;-2646.9
25(JK)
0.286;-2646.9
(5Q)(2K)
0.290;-1765.0
(2K)(5K)
0.265;-883.1
6(268)
0.317;-2933.8
6T(26)
0.314;-2700.0
(26)(6K)
0.338;-1584.4
T(267)
0.243;-3348.1
7(268)
0.226;-3581.9
7T(26)
0.287;-3348.1
(26)(7K)
0.233;-2232.5
J(268)
0.295;-3114.4
89(26)
0.278;-3348.1
(26)(8Q)
0.208;-2232.5
(269J)
0.268;-2997.5
(26)(9T)
0.230;-2349.4
9(26K)
0.250;-2763.8
(26TK)
0.272;-2646.9
TQ(26)
0.235;-2763.8
K(26J)
0.257;-2530.0
Q(26Q)
0.323;-1765.0
KK(26)
0.354;-1531.2
66(29)
0.256;-2816.9
266J
0.238;-3348.1
67(27)
0.186;-2933.8
(27)(6T)
0.254;-2583.1
6(27K)
0.287;-2997.5
2(679)
0.182;-3465.0
(67)(2Q)
0.281;-2349.4
27(68)
0.195;-3581.9
27(6T)
0.229;-3348.1
27(6Q)
0.283;-3114.4
68(28)
0.244;-2700.0
(28)(6J)
0.320;-2349.4
28(68)
0.222;-2700.0
2(68J)
0.257;-3114.4
2688
0.298;-3465.0
268T
0.230;-3996.2
268Q
0.275;-3762.5
(29)(6T)
0.286;-2349.4
6(29K)
0.248;-2763.8
2(69J)
0.276;-2997.5
2699
0.243;-3231.2
269J
0.217;-3762.5
269K
0.194;-3528.8
6Q(2T)
0.233;-2763.8
(6T)(2Q)
0.267;-1998.7
2T(6J)
0.301;-2880.6
2T(6K)
0.309;-2646.9
6(2JK)
0.296;-2530.0
2(6JK)
0.278;-2530.0
2J(6K)
0.280;-2530.0
2Q(6Q)
0.288;-1765.0
26QK
0.202;-3178.1
78(27)
0.290;-2700.0
(27)(7J)
0.302;-1584.4
8(278)
0.293;-2583.1
Q(278)
0.325;-2880.6
(27)(8T)
0.205;-2349.4
8(27K)
0.227;-2763.8
(279Q)
0.191;-2763.8
9(27J)
0.227;-2880.6
9K(27)
0.272;-2646.9
TT(27)
0.303;-2115.6
(27)(TK)
0.265;-1765.0
J(27Q)
0.216;-2530.0
K(27Q)
0.252;-2296.2
77(28)
0.213;-2700.0
277T
0.218;-3231.2
27(7K)
0.287;-2115.6
(28)(7T)
0.297;-2349.4
7(28K)
0.254;-2763.8
2(78T)
0.243;-3114.4
(78)(2K)
0.316;-1998.7
78(2T)
0.201;-3114.4
78(2Q)
0.226;-2880.6
(29)(79)
0.230;-1584.4
7(29Q)
0.224;-2763.8
2(79T)
0.208;-2997.5
(79)(2K)
0.278;-1881.9
79(2J)
0.286;-2880.6
79(2K)
0.203;-2646.9
7J(2T)
0.274;-2763.8
(7T)(2J)
0.239;-1998.7
2K(7T)
0.292;-2530.0
27(TQ)
0.238;-2646.9
7(2JQ)
0.291;-2530.0
2(7JQ)
0.230;-2530.0
27(JQ)
0.292;-2530.0
7(2QK)
0.287;-2296.2
7Q(2K)
0.243;-2296.2
88(28)
0.283;-1701.2
(28)(8J)
0.301;-1350.6
9(289)
0.248;-2232.5
K(289)
0.254;-2530.0
9(28Q)
0.248;-2646.9
J(28T)
0.243;-2646.9
TJ(28)
0.255;-2646.9
(28JQ)
0.251;-2413.1
J(28K)
0.298;-2296.2
(28)(QK)
0.288;-1414.4
88(2T)
0.280;-2232.5
288Q
0.278;-2763.8
8T(29)
0.255;-2880.6
(29)(8K)
0.281;-1765.0
2J(89)
0.238;-2763.8
89(2T)
0.196;-2880.6
89(2Q)
0.255;-2646.9
(2T)(8T)
0.289;-1233.8
8(2TK)
0.228;-2413.1
2(8TQ)
0.245;-2530.0
28(TJ)
0.286;-2646.9
28(TK)
0.272;-2413.1
(2J)(8K)
0.347;-1531.3
2K(8J)
0.251;-2296.2
28(JK)
0.240;-2296.2
(8Q)(2K)
0.285;-1414.4
(2K)(8K)
0.333;-532.5
9(29J)
0.307;-1881.9
9K(29)
0.254;-1648.1
TT(29)
0.316;-1881.9
(29)(TK)
0.352;-1531.3
J(29Q)
0.287;-2296.2
K(29Q)
0.347;-2062.5
99(2T)
0.248;-1998.7
299Q
0.257;-2530.0
9J(2T)
0.263;-2530.0
(9T)(2J)
0.301;-1765.0
2K(9T)
0.275;-2296.2
29(TQ)
0.296;-2413.1
9(2JQ)
0.294;-2296.2
2(9JQ)
0.292;-2296.2
29(JQ)
0.296;-2296.2
9(2QK)
0.244;-2062.5
9Q(2K)
0.310;-2062.5
TT(2T)
0.282;-1000.0
(2T)(TK)
0.307;-649.4
J(2TQ)
0.307;-2179.4
K(2TQ)
0.267;-1945.6
TT(2J)
0.299;-1648.1
2TTK
0.248;-2179.4
TK(2J)
0.258;-2062.5
2TJJ
0.272;-2296.2
2TJK
0.269;-2827.5
2(TQK)
0.291;-1945.6
TK(2K)
0.300;-1063.7
(2J)(JK)
0.308;-415.6
QK(2J)
0.215;-1828.7
2J(JK)
0.305;-1180.6
(JQ)(2K)
0.260;-1063.7
(2K)(JK)
0.390;-181.9
K(2QK)
0.299;-830.0
2K(QK)
0.297;-830.0
3335
0.228;-3868.8
3339
0.212;-3401.2
333K
0.240;-2933.8
36(34)
0.196;-3635.0
(34)(39)
0.263;-2519.4
3(34Q)
0.330;-2933.8
33(45)
0.232;-3751.9
34(38)
0.267;-3401.2
334T
0.205;-3932.5
33(4K)
0.243;-2816.9
(35)(37)
0.261;-2636.2
3(35T)
0.311;-3050.6
3Q(35)
0.283;-2816.9
35(37)
0.242;-3401.2
3359
0.222;-3932.5
33(5Q)
0.221;-2816.9
(36)(37)
0.260;-2519.4
3(36T)
0.280;-2933.8
3Q(36)
0.257;-2700.0
36(38)
0.219;-3167.5
336T
0.190;-3698.8
33(6K)
0.207;-2583.1
(37)(39)
0.274;-2168.8
3(37Q)
0.320;-2583.1
33(78)
0.211;-3050.6
37(3J)
0.310;-2700.0
337K
0.209;-3231.2
3T(38)
0.311;-2700.0
(38)(3K)
0.302;-1584.4
338T
0.238;-3465.0
33(8K)
0.289;-2349.4
(39)(3J)
0.281;-1701.2
3399
0.281;-2700.0
33(9Q)
0.247;-2349.4
(3T)(3J)
0.285;-1584.4
33TT
0.249;-2466.2
33(TK)
0.251;-2115.6
(3J)(3K)
0.304;-1233.8
33JK
0.332;-2763.8
33(QK)
0.264;-1881.9
45(34)
0.185;-3635.0
(34)(48)
0.251;-2519.4
4(34J)
0.272;-2933.8
4K(34)
0.327;-2700.0
(3459)
0.239;-3815.6
(345K)
0.250;-3348.1
57(34)
0.177;-4049.4
(34)(5T)
0.236;-2933.8
5(34K)
0.232;-3348.1
(3469)
0.215;-3698.8
(346K)
0.296;-3231.2
68(34)
0.219;-3815.6
(34)(6J)
0.222;-2700.0
7(347)
0.246;-3050.6
J(347)
0.228;-3348.1
78(34)
0.212;-3698.8
(34)(7J)
0.222;-2583.1
8(348)
0.203;-2816.9
Q(348)
0.248;-3114.4
(34)(8T)
0.225;-2583.1
8(34K)
0.245;-2997.5
(349Q)
0.271;-2997.5
9(34J)
0.249;-3114.4
9K(34)
0.243;-2880.6
TT(34)
0.269;-2349.4
(34)(TK)
0.340;-1998.7
J(34Q)
0.288;-2763.8
K(34Q)
0.278;-2530.0
44(35)
0.272;-3635.0
3447
0.227;-4166.2
34(4T)
0.247;-3050.6
44(3K)
0.279;-2700.0
4(357)
0.241;-4049.4
49(35)
0.217;-3815.6
(35)(4Q)
0.247;-2700.0
36(45)
0.216;-4166.2
3(459)
0.262;-3815.6
(45)(3Q)
0.295;-2700.0
35(46)
0.206;-4166.2
35(48)
0.227;-3932.5
35(4T)
0.271;-3698.8
35(4Q)
0.293;-3465.0
46(36)
0.209;-3284.4
(36)(49)
0.257;-2933.8
4(36Q)
0.226;-3348.1
3(467)
0.215;-3932.5
(46)(3T)
0.221;-2816.9
3Q(46)
0.195;-3348.1
3467
0.216;-4697.5
3469
0.154;-4463.8
346J
0.183;-4230.0
346K
0.251;-3996.2
49(37)
0.214;-3581.9
(37)(4Q)
0.264;-2466.2
38(47)
0.250;-3698.8
3(47J)
0.208;-3348.1
3477
0.267;-3815.6
3479
0.218;-4346.9
347J
0.240;-4113.1
347K
0.163;-3879.4
4T(38)
0.255;-3348.1
(38)(4K)
0.233;-2232.5
3T(48)
0.263;-3348.1
3(48K)
0.232;-2997.5
38(4T)
0.179;-3348.1
38(4Q)
0.212;-3114.4
49(39)
0.257;-2583.1
(39)(4Q)
0.286;-2232.5
3T(49)
0.237;-3231.2
3(49K)
0.258;-2880.6
39(4J)
0.282;-3114.4
39(4K)
0.223;-2880.6
4(3TQ)
0.257;-2880.6
3(4TJ)
0.226;-2997.5
34TT
0.226;-3114.4
34TQ
0.198;-3645.6
(3J)(4Q)
0.238;-1998.7
3Q(4J)
0.232;-2763.8
34JQ
0.222;-3528.8
(3Q)(4K)
0.323;-1765.0
3Q(4K)
0.239;-2530.0
5(356)
0.245;-3284.4
58(35)
0.218;-3050.6
(35)(5J)
0.346;-1935.0
6(356)
0.232;-3167.5
T(356)
0.243;-3465.0
6(357)
0.224;-3815.6
69(35)
0.249;-3581.9
(35)(6Q)
0.297;-2466.2
(3579)
0.224;-3465.0
(357K)
0.269;-2997.5
79(35)
0.288;-3465.0
(35)(7Q)
0.255;-2349.4
(358T)
0.240;-3231.2
88(35)
0.309;-2700.0
(35)(8J)
0.248;-2349.4
9(359)
0.315;-2466.2
K(359)
0.267;-2763.8
9(35Q)
0.263;-2880.6
J(35T)
0.324;-2880.6
TJ(35)
0.309;-2880.6
(35JQ)
0.287;-2646.9
J(35K)
0.275;-2530.0
(35)(QK)
0.304;-1648.1
55(37)
0.235;-3167.5
3559
0.231;-3698.8
35(5Q)
0.221;-2583.1
(36)(57)
0.264;-3050.6
5(36T)
0.187;-3465.0
5Q(36)
0.240;-3231.2
(56)(38)
0.308;-2933.8
3T(56)
0.227;-3465.0
3(56K)
0.306;-3114.4
36(58)
0.195;-3698.8
36(5T)
0.258;-3465.0
36(5Q)
0.245;-3231.2
57(37)
0.252;-2933.8
(37)(5T)
0.246;-2583.1
5(37K)
0.235;-2997.5
3(579)
0.191;-3465.0
(57)(3Q)
0.233;-2349.4
37(58)
0.282;-3581.9
37(5T)
0.236;-3348.1
37(5Q)
0.246;-3114.4
58(38)
0.244;-2700.0
(38)(5J)
0.228;-2349.4
38(58)
0.240;-2700.0
3(58J)
0.246;-3114.4
3588
0.296;-3465.0
358T
0.178;-3996.2
358Q
0.225;-3762.5
(39)(5T)
0.252;-2349.4
5(39K)
0.309;-2763.8
3(59J)
0.229;-2997.5
3599
0.276;-3231.2
359J
0.246;-3762.5
359K
0.215;-3528.8
5Q(3T)
0.257;-2763.8
(5T)(3Q)
0.344;-1998.7
3T(5J)
0.231;-2880.6
3T(5K)
0.210;-2646.9
5(3JK)
0.223;-2530.0
3(5JK)
0.305;-2530.0
3J(5K)
0.239;-2530.0
3Q(5Q)
0.324;-1765.0
35QK
0.279;-3178.1
67(36)
0.239;-2933.8
(36)(6T)
0.234;-1818.1
6(36K)
0.231;-2232.5
(367T)
0.233;-3231.2
77(36)
0.295;-2816.9
(36)(7T)
0.288;-2466.2
7(36K)
0.244;-2880.6
(368J)
0.275;-2997.5
(36)(89)
0.277;-2466.2
8(36Q)
0.232;-2880.6
T(369)
0.206;-2997.5
9(36T)
0.255;-2997.5
9Q(36)
0.256;-2763.8
Q(36T)
0.250;-2646.9
(36)(TQ)
0.241;-1881.9
(36JK)
0.291;-2413.1
JK(36)
0.284;-2413.1
K(36K)
0.283;-1414.4
3668
0.215;-3581.9
36(6J)
0.243;-2466.2
(37)(67)
0.231;-2051.9
6(37T)
0.240;-3231.2
6Q(37)
0.228;-2997.5
(67)(39)
0.289;-2583.1
3J(67)
0.241;-3114.4
67(38)
0.266;-3465.0
67(3T)
0.192;-3231.2
67(3Q)
0.217;-2997.5
(38)(68)
0.325;-1818.1
6(38J)
0.227;-2997.5
6K(38)
0.281;-2763.8
(68)(3J)
0.211;-2232.5
3K(68)
0.192;-2763.8
36(8T)
0.257;-3114.4
36(8Q)
0.267;-2880.6
6(39T)
0.293;-2997.5
6Q(39)
0.261;-2763.8
(69)(3J)
0.280;-2115.6
3K(69)
0.282;-2646.9
36(9J)
0.203;-2880.6
36(9K)
0.230;-2646.9
(3T)(6Q)
0.279;-1881.9
3J(6T)
0.261;-2763.8
6T(3J)
0.301;-2763.8
6T(3K)
0.218;-2530.0
6Q(3J)
0.203;-2530.0
(6J)(3K)
0.309;-1648.1
6J(3K)
0.274;-2413.1
6K(3Q)
0.280;-2296.2
36(QK)
0.226;-2296.2
(37)(78)
0.274;-1818.1
7(37J)
0.247;-2232.5
7K(37)
0.309;-1998.7
(378Q)
0.260;-2763.8
8(37T)
0.276;-2997.5
8Q(37)
0.268;-2763.8
J(379)
0.265;-2763.8
9T(37)
0.225;-2880.6
(37)(9K)
0.304;-1765.0
K(37T)
0.224;-2413.1
T(37K)
0.320;-2413.1
JJ(37)
0.271;-1765.0
(37QK)
0.292;-2179.4
3777
0.223;-2700.0
37(7T)
0.269;-2349.4
77(3K)
0.305;-1998.7
7(38T)
0.251;-2997.5
7Q(38)
0.274;-2763.8
(78)(3T)
0.254;-2232.5
3Q(78)
0.267;-2763.8
3789
0.259;-3879.4
378J
0.241;-3645.6
378K
0.244;-3411.9
7J(39)
0.268;-2763.8
(79)(3T)
0.314;-2115.6
3Q(79)
0.215;-2646.9
379T
0.201;-3645.6
379Q
0.230;-3411.9
(3T)(7J)
0.301;-1881.9
3T(7T)
0.259;-1998.7
3(7TK)
0.260;-2413.1
3T(7Q)
0.212;-2530.0
7J(3J)
0.324;-1765.0
(7J)(3Q)
0.312;-1648.1
3J(7Q)
0.312;-2413.1
7Q(3Q)
0.291;-1531.2
37QQ
0.241;-2296.2
37KK
0.259;-2062.5
8(38J)
0.330;-1998.7
8K(38)
0.333;-1765.0
(389K)
0.300;-2413.1
9J(38)
0.256;-2646.9
(38TJ)
0.271;-2530.0
(38)(TJ)
0.295;-1765.0
J(38J)
0.349;-1648.1
JQ(38)
0.251;-2296.2
Q(38K)
0.295;-2062.5
3889
0.278;-2997.5
38(8Q)
0.287;-1881.9
(39)(8T)
0.291;-1998.7
8(39K)
0.290;-2413.1
3(89J)
0.280;-2646.9
3899
0.261;-2880.6
389J
0.181;-3411.9
389K
0.303;-3178.1
8Q(3T)
0.264;-2413.1
(8T)(3Q)
0.283;-1648.1
3T(8J)
0.259;-2530.0
3T(8K)
0.217;-2296.2
8(3JK)
0.249;-2179.4
3(8JK)
0.273;-2179.4
3J(8K)
0.234;-2179.4
3Q(8Q)
0.358;-1414.4
38QK
0.292;-2827.5
9T(39)
0.285;-1881.9
(39)(9K)
0.355;-766.2
K(39T)
0.299;-2179.4
T(39K)
0.228;-2179.4
JJ(39)
0.331;-1531.2
(39QK)
0.316;-1945.6
3999
0.310;-1998.7
39(9Q)
0.245;-1648.1
(3T)(9J)
0.289;-1648.1
3T(9T)
0.254;-1765.0
3(9TK)
0.323;-2179.4
3T(9Q)
0.239;-2296.2
9J(3J)
0.284;-1531.2
(9J)(3Q)
0.299;-1414.4
3J(9Q)
0.305;-2179.4
9Q(3Q)
0.360;-1297.5
39QQ
0.275;-2062.5
39KK
0.234;-1828.7
T(3TK)
0.327;-1297.5
JJ(3T)
0.362;-1414.4
(3TQK)
0.323;-1828.7
3TTT
0.361;-1648.1
3T(TK)
0.363;-1297.5
(3J)(TK)
0.341;-1180.6
3K(TJ)
0.222;-1945.6
3T(JK)
0.299;-1945.6
(TQ)(3K)
0.294;-1063.7
(3K)(TK)
0.338;-181.9
J(3JK)
0.345;-1063.7
(3J)(QK)
0.304;-946.9
JJ(3K)
0.312;-1063.7
3Q(JQ)
0.361;-1063.7
3JQK
0.240;-2476.9
QK(3Q)
0.282;-830.0
QK(3K)
0.352;-713.1
44(46)
0.301;-2636.2
44(4T)
0.310;-2168.7
(45)(45)
0.289;-1871.3
4(458)
0.190;-3050.6
4T(45)
0.275;-2816.9
(45)(4K)
0.274;-1701.2
4457
0.217;-3932.5
44(5T)
0.232;-2816.9
45(4K)
0.256;-2466.2
4(468)
0.213;-2933.8
4T(46)
0.256;-2700.0
(46)(4K)
0.293;-1584.4
4468
0.192;-3698.8
44(6J)
0.264;-2583.1
(47)(47)
0.323;-1403.7
4(47T)
0.270;-2583.1
4Q(47)
0.277;-2349.4
47(49)
0.230;-2700.0
447J
0.251;-3231.2
48(48)
0.224;-1935.0
(48)(4J)
0.268;-1584.4
4488
0.282;-2700.0
44(8J)
0.223;-2349.4
(49)(49)
0.353;-936.3
4(49Q)
0.302;-2115.6
44(9T)
0.254;-2349.4
49(4K)
0.297;-1998.7
4(4TQ)
0.320;-1998.7
44(TJ)
0.244;-2115.6
(4J)(4J)
0.300;-468.7
44JJ
0.226;-1998.7
4Q(4Q)
0.257;-1000.0
(4K)(4K)
0.366;-1.3
(45)(57)
0.266;-2285.6
5(45T)
0.215;-2700.0
5Q(45)
0.254;-2466.2
8(456)
0.249;-3581.9
Q(456)
0.248;-3114.4
(45)(68)
0.300;-2816.9
6(45J)
0.203;-3231.2
6K(45)
0.286;-2997.5
(457J)
0.209;-3114.4
(45)(78)
0.254;-2700.0
7(45J)
0.230;-3114.4
7K(45)
0.224;-2880.6
(458Q)
0.245;-2880.6
8(45T)
0.279;-3114.4
8Q(45)
0.280;-2880.6
J(459)
0.272;-2880.6
9T(45)
0.286;-2997.5
(45)(9K)
0.343;-1881.9
K(45T)
0.242;-2530.0
T(45K)
0.259;-2530.0
JJ(45)
0.303;-1881.9
(45QK)
0.289;-2296.2
4555
0.202;-3284.4
45(58)
0.218;-2933.8
55(4J)
0.278;-2583.1
455K
0.250;-3114.4
58(46)
0.280;-3581.9
(46)(5J)
0.302;-2466.2
46(56)
0.202;-3050.6
4(569)
0.275;-3465.0
(56)(4Q)
0.281;-2349.4
46(57)
0.270;-3698.8
46(59)
0.211;-3465.0
46(5J)
0.246;-3231.2
46(5K)
0.263;-2997.5
5(479)
0.260;-3348.1
5J(47)
0.281;-3114.4
(57)(48)
0.302;-2700.0
4T(57)
0.261;-3231.2
4(57K)
0.205;-2880.6
47(59)
0.260;-3348.1
47(5J)
0.259;-3114.4
47(5K)
0.271;-2880.6
5(48T)
0.216;-3114.4
5Q(48)
0.267;-2880.6
(58)(4T)
0.278;-2349.4
4Q(58)
0.251;-2880.6
4589
0.210;-3996.2
458J
0.242;-3762.5
458K
0.281;-3528.8
5J(49)
0.292;-2880.6
(59)(4T)
0.264;-2232.5
4Q(59)
0.270;-2763.8
459T
0.194;-3762.5
459Q
0.287;-3528.8
(4T)(5J)
0.239;-1998.7
4T(5T)
0.261;-2115.6
4(5TK)
0.293;-2530.0
4T(5Q)
0.218;-2646.9
5J(4J)
0.326;-1881.9
(5J)(4Q)
0.271;-1765.0
4J(5Q)
0.210;-2530.0
5Q(4Q)
0.325;-1648.1
45QQ
0.278;-2413.1
45KK
0.270;-2179.4
6(469)
0.251;-2583.1
6J(46)
0.262;-2349.4
(4678)
0.263;-3348.1
(467Q)
0.217;-2880.6
7(469)
0.224;-3231.2
7J(46)
0.244;-2997.5
(4689)
0.215;-3114.4
(468K)
0.211;-2646.9
8T(46)
0.227;-2997.5
(46)(8K)
0.346;-1881.9
Q(469)
0.217;-2646.9
(46)(9J)
0.341;-1998.7
T(46T)
0.255;-1998.7
T(46J)
0.266;-2646.9
TK(46)
0.239;-2413.1
(46)(JQ)
0.262;-1648.1
QQ(46)
0.340;-1531.2
46(67)
0.236;-2816.9
66(4T)
0.243;-2466.2
466Q
0.223;-2997.5
68(47)
0.257;-3348.1
(47)(6J)
0.211;-2232.5
47(67)
0.311;-2700.0
4(67T)
0.200;-3114.4
(67)(4K)
0.322;-1998.7
67(49)
0.276;-3231.2
67(4J)
0.274;-2997.5
67(4K)
0.252;-2763.8
69(48)
0.283;-3114.4
(48)(6Q)
0.258;-1998.7
49(68)
0.226;-3114.4
4(68Q)
0.207;-2763.8
46(89)
0.275;-3114.4
46(8J)
0.290;-2880.6
46(8K)
0.256;-2646.9
(49)(6J)
0.270;-1998.7
49(69)
0.242;-2232.5
4(69Q)
0.291;-2646.9
46(9T)
0.224;-2880.6
46(9Q)
0.222;-2646.9
6(4TJ)
0.260;-2646.9
6K(4T)
0.307;-2413.1
(6T)(4K)
0.281;-1648.1
6T(4Q)
0.257;-2530.0
(4J)(6J)
0.304;-1000.0
4J(6J)
0.296;-1765.0
6J(4Q)
0.232;-2413.1
(4Q)(6Q)
0.360;-766.2
4K(6Q)
0.304;-2179.4
4K(6K)
0.291;-1297.5
79(47)
0.271;-2349.4
(47)(7Q)
0.303;-1233.8
(478T)
0.230;-2880.6
88(47)
0.282;-2349.4
(47)(8J)
0.285;-1998.7
9(479)
0.233;-2115.6
K(479)
0.303;-2413.1
9(47Q)
0.264;-2530.0
J(47T)
0.288;-2530.0
TJ(47)
0.269;-2530.0
(47JQ)
0.237;-2296.2
J(47K)
0.243;-2179.4
(47)(QK)
0.354;-1297.5
77(49)
0.242;-2349.4
477J
0.221;-2880.6
78(48)
0.243;-2349.4
(48)(7J)
0.288;-1998.7
48(78)
0.273;-2349.4
4(78J)
0.220;-2763.8
4788
0.284;-3114.4
478T
0.235;-3645.6
478Q
0.207;-3411.9
(49)(7T)
0.265;-1998.7
7(49K)
0.231;-2413.1
4(79J)
0.249;-2646.9
4799
0.273;-2880.6
479J
0.248;-3411.9
479K
0.259;-3178.1
7Q(4T)
0.245;-2413.1
(7T)(4Q)
0.258;-1648.1
4T(7J)
0.228;-2530.0
4T(7K)
0.328;-2296.2
7(4JK)
0.251;-2179.4
4(7JK)
0.300;-2179.4
4J(7K)
0.256;-2179.4
4Q(7Q)
0.261;-1414.4
47QK
0.234;-2827.5
89(48)
0.297;-2115.6
(48)(8Q)
0.281;-1000.0
(489J)
0.224;-2530.0
(48)(9T)
0.241;-1881.9
9(48K)
0.298;-2296.2
(48TK)
0.311;-2179.4
TQ(48)
0.246;-2296.2
K(48J)
0.308;-2062.5
Q(48Q)
0.331;-1297.5
KK(48)
0.290;-1063.7
88(4J)
0.326;-1881.9
488K
0.239;-2413.1
8J(49)
0.242;-2530.0
(89)(4T)
0.253;-1881.9
4Q(89)
0.320;-2413.1
489T
0.225;-3411.9
489Q
0.250;-3178.1
(4T)(8J)
0.322;-1648.1
4T(8T)
0.334;-1765.0
4(8TK)
0.320;-2179.4
4T(8Q)
0.248;-2296.2
8J(4J)
0.366;-1531.2
(8J)(4Q)
0.310;-1414.4
4J(8Q)
0.348;-2179.4
8Q(4Q)
0.293;-1297.5
48QQ
0.284;-2062.5
48KK
0.289;-1828.7
9(49Q)
0.292;-1531.2
J(49T)
0.306;-2296.2
TJ(49)
0.233;-2296.2
(49JQ)
0.218;-2062.5
J(49K)
0.301;-1945.6
(49)(QK)
0.306;-1063.7
99(4J)
0.301;-1648.1
499K
0.249;-2179.4
9Q(4T)
0.308;-2179.4
(9T)(4Q)
0.256;-1414.4
4T(9J)
0.251;-2296.2
4T(9K)
0.233;-2062.5
9(4JK)
0.294;-1945.6
4(9JK)
0.302;-1945.6
4J(9K)
0.273;-1945.6
4Q(9Q)
0.273;-1180.6
49QK
0.257;-2593.8
TJ(4T)
0.326;-1414.4
(4TJQ)
0.341;-1945.6
J(4TK)
0.242;-1828.7
(4T)(QK)
0.369;-946.9
TT(4Q)
0.357;-1297.5
T(4JQ)
0.263;-1945.6
4(TJQ)
0.323;-1945.6
4T(JQ)
0.251;-1945.6
T(4QK)
0.228;-1711.9
TQ(4K)
0.292;-1711.9
JJ(4J)
0.335;-415.6
(4JQK)
0.347;-1595.0
4JJJ
0.295;-1180.6
JQ(4Q)
0.315;-946.9
4JQQ
0.311;-1711.9
4JKK
0.324;-1478.1
QQ(4K)
0.275;-713.1
4KKK
0.298;-479.4
55(59)
0.331;-1935.0
55(5K)
0.236;-1467.5
(56)(58)
0.325;-1935.0
5(56J)
0.282;-2349.4
5K(56)
0.226;-2115.6
56(59)
0.260;-2583.1
556J
0.219;-3114.4
57(57)
0.334;-1935.0
(57)(5T)
0.250;-1584.4
5(57K)
0.291;-1998.7
55(79)
0.295;-2466.2
57(5Q)
0.283;-2115.6
5(589)
0.266;-2349.4
5J(58)
0.239;-2115.6
58(59)
0.244;-2349.4
558J
0.264;-2880.6
59(59)
0.300;-1467.5
(59)(5Q)
0.308;-1116.9
559T
0.246;-2880.6
55(9K)
0.275;-1765.0
(5T)(5Q)
0.244;-1000.0
55TJ
0.272;-2646.9
5J(5J)
0.356;-1000.0
5J(5Q)
0.363;-1648.1
5(5QK)
0.249;-1414.4
5K(5K)
0.380;-532.5
68(56)
0.280;-2583.1
(56)(6J)
0.298;-1467.5
7(567)
0.255;-2583.1
J(567)
0.234;-2880.6
78(56)
0.271;-3231.2
(56)(7J)
0.311;-2115.6
8(568)
0.216;-2349.4
Q(568)
0.307;-2646.9
(56)(8T)
0.264;-2115.6
8(56K)
0.313;-2530.0
(569Q)
0.263;-2530.0
9(56J)
0.311;-2646.9
9K(56)
0.254;-2413.1
TT(56)
0.295;-1881.9
(56)(TK)
0.336;-1531.3
J(56Q)
0.310;-2296.2
K(56Q)
0.314;-2062.5
66(57)
0.230;-2700.0
5669
0.219;-3231.2
56(6Q)
0.229;-2115.6
(57)(68)
0.318;-2466.2
6(57J)
0.288;-2880.6
6K(57)
0.259;-2646.9
(67)(5T)
0.272;-2232.5
5Q(67)
0.238;-2763.8
5678
0.266;-3996.2
567T
0.226;-3762.5
567Q
0.247;-3528.8
(58)(69)
0.242;-2232.5
6(58Q)
0.266;-2646.9
5(689)
0.227;-2997.5
(68)(5Q)
0.307;-1881.9
58(69)
0.321;-2997.5
58(6J)
0.226;-2763.8
58(6K)
0.283;-2530.0
6(59J)
0.208;-2646.9
6K(59)
0.276;-2413.1
(69)(5Q)
0.270;-1765.0
59(6T)
0.272;-2763.8
59(6Q)
0.252;-2530.0
6T(5T)
0.327;-1881.9
(5T)(6K)
0.286;-1531.3
5Q(6T)
0.304;-2413.1
56TJ
0.223;-3295.0
56TK
0.273;-3061.2
6K(5J)
0.253;-2179.4
56JJ
0.292;-2413.1
56JK
0.272;-2944.4
5(6QK)
0.223;-2062.5
6K(5K)
0.271;-1180.6
(57)(79)
0.302;-1467.5
7(57Q)
0.293;-1881.9
9(578)
0.210;-2880.6
K(578)
0.221;-2413.1
8(57J)
0.233;-2646.9
8K(57)
0.254;-2413.1
(579K)
0.334;-2296.2
9J(57)
0.253;-2530.0
(57TJ)
0.243;-2413.1
(57)(TJ)
0.267;-1648.1
J(57J)
0.264;-1531.2
JQ(57)
0.293;-2179.4
Q(57K)
0.266;-1945.6
5778
0.243;-3114.4
57(7J)
0.292;-1998.7
(58)(78)
0.240;-1467.5
7(58J)
0.288;-2646.9
7K(58)
0.265;-2413.1
(78)(5J)
0.261;-1881.9
5K(78)
0.230;-2413.1
57(8T)
0.264;-2763.8
57(8Q)
0.280;-2530.0
7(59T)
0.212;-2646.9
7Q(59)
0.247;-2413.1
(79)(5J)
0.290;-1765.0
5K(79)
0.232;-2296.2
57(9J)
0.254;-2530.0
57(9K)
0.276;-2296.2
(5T)(7Q)
0.274;-1531.3
5J(7T)
0.307;-2413.1
7T(5J)
0.230;-2413.1
7T(5K)
0.217;-2179.4
7Q(5J)
0.332;-2179.4
(7J)(5K)
0.355;-1297.5
7J(5K)
0.329;-2062.5
7K(5Q)
0.243;-1945.6
57(QK)
0.326;-1945.6
(58)(89)
0.317;-1233.8
8(58Q)
0.248;-1648.1
T(589)
0.242;-2530.0
9(58T)
0.239;-2530.0
9Q(58)
0.295;-2296.2
Q(58T)
0.243;-2179.4
(58)(TQ)
0.347;-1414.4
(58JK)
0.248;-1945.6
JK(58)
0.263;-1945.6
K(58K)
0.321;-946.9
588T
0.278;-2646.9
58(8K)
0.246;-1531.2
(59)(8J)
0.330;-1648.1
59(89)
0.288;-1881.9
5(89Q)
0.322;-2296.2
58(9T)
0.292;-2530.0
58(9Q)
0.267;-2296.2
8(5TJ)
0.282;-2296.2
8K(5T)
0.243;-2062.5
(8T)(5K)
0.296;-1297.5
8T(5Q)
0.337;-2179.4
(5J)(8J)
0.324;-649.4
5J(8J)
0.302;-1414.4
8J(5Q)
0.273;-2062.5
(5Q)(8Q)
0.332;-415.6
5K(8Q)
0.304;-1828.7
5K(8K)
0.294;-946.9
9J(59)
0.289;-1531.2
(59TJ)
0.291;-2179.4
(59)(TJ)
0.271;-1414.4
J(59J)
0.276;-1297.5
JQ(59)
0.302;-1945.6
Q(59K)
0.312;-1711.9
599T
0.221;-2413.1
59(9K)
0.294;-1297.5
(5T)(9Q)
0.278;-1297.5
5J(9T)
0.283;-2179.4
9T(5J)
0.271;-2179.4
9T(5K)
0.286;-1945.6
9Q(5J)
0.313;-1945.6
(9J)(5K)
0.282;-1063.7
9J(5K)
0.295;-1828.7
9K(5Q)
0.315;-1711.9
59(QK)
0.296;-1711.9
(5T)(TJ)
0.355;-532.5
J(5TJ)
0.238;-1180.6
JQ(5T)
0.280;-1828.7
Q(5TK)
0.360;-1595.0
5TTJ
0.301;-2062.5
TJ(5J)
0.286;-1180.6
(TJ)(5Q)
0.282;-1063.7
5J(TQ)
0.301;-1828.7
TQ(5Q)
0.279;-946.9
5TQQ
0.247;-1711.9
5TKK
0.311;-1478.1
Q(5JQ)
0.300;-830.0
KK(5J)
0.360;-596.2
(5Q)(JQ)
0.330;-65.0
5K(JQ)
0.278;-1478.1
5K(JK)
0.327;-596.2
5QQQ
0.289;-713.1
KK(5K)
0.377;402.5
6669
0.290;-2349.4
666K
0.258;-1881.9
69(67)
0.235;-2232.5
(67)(6Q)
0.326;-1116.9
6678
0.301;-3114.4
66(7J)
0.243;-1998.7
(68)(68)
0.311;-702.5
6(68J)
0.215;-1881.9
6K(68)
0.239;-1648.1
68(6J)
0.256;-1881.9
668K
0.298;-2413.1
6J(69)
0.322;-1765.0
69(6T)
0.319;-1881.9
669Q
0.244;-2413.1
6J(6T)
0.281;-1648.1
6T(6J)
0.364;-1648.1
66TK
0.293;-2179.4
6K(6J)
0.319;-1297.5
(6Q)(6Q)
0.352;232.5
66QK
0.288;-1945.6
7(679)
0.271;-2115.6
7J(67)
0.235;-1881.9
(6789)
0.217;-2763.8
(678K)
0.278;-2296.2
8T(67)
0.283;-2646.9
(67)(8K)
0.288;-1531.3
Q(679)
0.277;-2296.2
(67)(9J)
0.353;-1648.1
T(67T)
0.337;-1648.1
T(67J)
0.275;-2296.2
TK(67)
0.235;-2062.5
(67)(JQ)
0.310;-1297.5
QQ(67)
0.259;-1180.6
67(78)
0.211;-2232.5
77(6J)
0.239;-1881.9
677K
0.280;-2413.1
7T(68)
0.262;-2646.9
(68)(7K)
0.262;-1531.3
6T(78)
0.242;-2646.9
6(78K)
0.299;-2296.2
68(7T)
0.236;-2646.9
68(7Q)
0.241;-2413.1
79(69)
0.276;-1881.9
(69)(7Q)
0.267;-1531.3
6T(79)
0.332;-2530.0
6(79K)
0.305;-2179.4
69(7J)
0.230;-2413.1
69(7K)
0.301;-2179.4
7(6TQ)
0.295;-2179.4
6(7TJ)
0.320;-2296.2
67TT
0.225;-2413.1
67TQ
0.263;-2944.4
(6J)(7Q)
0.320;-1297.5
6Q(7J)
0.249;-2062.5
67JQ
0.241;-2827.5
(6Q)(7K)
0.328;-1063.7
6Q(7K)
0.242;-1828.7
8(689)
0.222;-1881.9
8J(68)
0.272;-1648.1
(689T)
0.244;-2413.1
99(68)
0.273;-1765.0
(68)(9Q)
0.323;-1414.4
(68TQ)
0.226;-2062.5
T(68Q)
0.287;-2062.5
Q(68J)
0.255;-1945.6
(68)(JK)
0.300;-1063.7
QK(68)
0.300;-1711.9
68(8T)
0.346;-1765.0
88(6K)
0.306;-1414.4
8(69J)
0.239;-2296.2
8K(69)
0.280;-2062.5
(89)(6Q)
0.270;-1414.4
69(8T)
0.265;-2413.1
69(8Q)
0.296;-2179.4
8T(6T)
0.315;-1531.2
(6T)(8K)
0.288;-1180.6
6Q(8T)
0.282;-2062.5
68TJ
0.254;-2944.4
68TK
0.246;-2710.6
8K(6J)
0.321;-1828.7
68JJ
0.314;-2062.5
68JK
0.247;-2593.8
6(8QK)
0.272;-1711.9
8K(6K)
0.337;-830.0
(69)(9J)
0.404;-649.4
T(69T)
0.308;-1414.4
T(69J)
0.244;-2062.5
TK(69)
0.330;-1828.7
(69)(JQ)
0.254;-1063.7
QQ(69)
0.311;-946.9
69(9T)
0.291;-1531.2
99(6K)
0.376;-1180.6
9(6TQ)
0.254;-1945.6
6(9TJ)
0.222;-2062.5
69TT
0.271;-2179.4
69TQ
0.267;-2710.6
(6J)(9Q)
0.308;-1063.7
6Q(9J)
0.318;-1828.7
69JQ
0.259;-2593.8
(6Q)(9K)
0.322;-830.0
6Q(9K)
0.286;-1595.0
T(6TJ)
0.269;-1180.6
TK(6T)
0.333;-946.9
(6T)(JQ)
0.329;-946.9
QQ(6T)
0.327;-830.0
6T(TJ)
0.309;-1180.6
(6J)(TJ)
0.373;-298.8
6J(TJ)
0.300;-1063.7
TJ(6Q)
0.297;-1711.9
(6Q)(TQ)
0.316;-65.0
6K(TQ)
0.266;-1478.1
6K(TK)
0.285;-596.2
JK(6J)
0.299;-713.1
K(6JK)
0.364;-479.4
6JJK
0.321;-1478.1
6(JQK)
0.289;-1361.2
JK(6K)
0.317;-479.4
KK(6Q)
0.306;-362.5
6QKK
0.345;-1127.5
77(7T)
0.259;-1116.9
(78)(78)
0.345;-468.7
7(78J)
0.280;-1648.1
7K(78)
0.296;-1414.4
78(7J)
0.252;-1648.1
778K
0.298;-2179.4
7J(79)
0.254;-1531.2
79(7T)
0.257;-1648.1
779Q
0.244;-2179.4
7J(7T)
0.271;-1414.4
7T(7J)
0.291;-1414.4
77TK
0.263;-1945.6
7K(7J)
0.338;-1063.7
(7Q)(7Q)
0.404;466.3
77QK
0.325;-1711.9
8(78T)
0.332;-1648.1
8Q(78)
0.264;-1414.4
J(789)
0.265;-2179.4
9T(78)
0.241;-2296.2
(78)(9K)
0.301;-1180.6
K(78T)
0.266;-1828.7
T(78K)
0.258;-1828.7
JJ(78)
0.294;-1180.6
(78QK)
0.346;-1595.0
7888
0.264;-1881.9
78(8J)
0.313;-1531.2
(79)(89)
0.308;-883.1
8(79Q)
0.301;-2062.5
7(89T)
0.246;-2296.2
(89)(7K)
0.368;-1180.6
89(7J)
0.269;-2179.4
89(7K)
0.305;-1945.6
8J(7T)
0.298;-2062.5
(8T)(7J)
0.281;-1297.5
7K(8T)
0.319;-1828.7
78(TQ)
0.261;-1945.6
8(7JQ)
0.257;-1828.7
7(8JQ)
0.331;-1828.7
78(JQ)
0.315;-1828.7
8(7QK)
0.321;-1595.0
8Q(7K)
0.287;-1595.0
99(79)
0.358;-766.3
(79)(9Q)
0.366;-415.6
(79TQ)
0.305;-1828.7
T(79Q)
0.312;-1828.7
Q(79J)
0.274;-1711.9
(79)(JK)
0.257;-830.0
QK(79)
0.319;-1478.1
79(9J)
0.295;-1297.5
(7T)(9T)
0.340;-532.5
9(7TK)
0.292;-1711.9
7(9TQ)
0.284;-1828.7
79(TJ)
0.305;-1945.6
79(TK)
0.240;-1711.9
(7J)(9K)
0.328;-830.0
7K(9J)
0.274;-1595.0
79(JK)
0.269;-1595.0
(9Q)(7K)
0.349;-713.1
(7K)(9K)
0.346;168.8
T(7TQ)
0.287;-946.9
Q(7TJ)
0.322;-1595.0
(7T)(JK)
0.312;-713.1
QK(7T)
0.315;-1361.2
7T(TQ)
0.331;-946.9
(7J)(TQ)
0.334;-830.0
7Q(TJ)
0.317;-1595.0
7TJQ
0.239;-2360.0
(7Q)(TK)
0.321;-596.2
7Q(TK)
0.310;-1361.2
J(7JQ)
0.317;-713.1
K(7JQ)
0.307;-1244.4
JJ(7Q)
0.305;-713.1
J(7QK)
0.320;-1244.4
JQ(7K)
0.354;-1244.4
QQ(7Q)
0.321;285.6
7Q(QK)
0.343;-362.5
8888
0.282;-1000.0
888Q
0.290;-1297.5
8(89J)
0.241;-1297.5
8K(89)
0.333;-1063.7
89(8Q)
0.259;-1180.6
8(8TJ)
0.253;-1180.6
8K(8T)
0.274;-946.9
8T(8K)
0.347;-946.9
8(8JK)
0.329;-830.0
88(JK)
0.343;-830.0
8Q(8K)
0.369;-713.1
(89)(9T)
0.375;-532.5
9(89K)
0.312;-946.9
(89TK)
0.299;-1595.0
TQ(89)
0.248;-1711.9
K(89J)
0.336;-1478.1
Q(89Q)
0.291;-713.1
KK(89)
0.295;-479.4
99(8Q)
0.317;-1063.7
9(8TJ)
0.244;-1828.7
9K(8T)
0.341;-1595.0
(9T)(8K)
0.311;-830.0
9T(8Q)
0.300;-1711.9
(8J)(9J)
0.319;-181.9
8J(9J)
0.302;-946.9
9J(8Q)
0.342;-1595.0
(8Q)(9Q)
0.375;51.9
8K(9Q)
0.293;-1361.2
8K(9K)
0.319;-479.4
TQ(8T)
0.329;-830.0
K(8TJ)
0.279;-1361.2
Q(8TQ)
0.351;-596.2
KK(8T)
0.317;-362.5
