AAAA
0.410;-505.0
5AAA
0.319;-825.6
9AAA
0.401;-743.1
KAAA
0.366;-660.6
4A(2A)
0.382;-1093.8
(2A)(7A)
0.392;-896.9
A(2TA)
0.376;-970.0
QA(2A)
0.370;-928.7
2A(4A)
0.324;-1093.8
26AA
0.376;-1187.5
AA(29)
0.415;-990.6
2A(QA)
0.415;-928.7
A(34A)
0.360;-1073.1
6A(3A)
0.337;-1031.9
(3A)(9A)
0.333;-835.0
A(3QA)
0.333;-908.1
AA(34)
0.322;-1073.1
3A(7A)
0.344;-1011.2
39AA
0.354;-1105.0
AA(3Q)
0.420;-908.1
(4A)(5A)
0.358;-896.9
A(48A)
0.384;-970.0
TA(4A)
0.381;-928.7
(4A)(KA)
0.378;-731.9
46AA
0.355;-1146.2
AA(49)
0.387;-949.4
4A(QA)
0.344;-887.5
A(56A)
0.326;-990.6
8A(5A)
0.336;-949.4
(5A)(JA)
0.381;-752.5
55AA
0.411;-1011.2
AA(58)
0.368;-949.4
5A(JA)
0.418;-887.5
5KAA
0.443;-981.3
8A(6A)
0.322;-928.7
(6A)(JA)
0.361;-731.9
66AA
0.433;-970.0
AA(69)
0.335;-908.1
6A(QA)
0.433;-846.3
A(78A)
0.341;-908.1
TA(7A)
0.375;-866.9
(7A)(KA)
0.394;-670.0
79AA
0.355;-1022.5
AA(7Q)
0.354;-825.6
(8A)(9A)
0.315;-731.9
A(8QA)
0.427;-805.0
AA(89)
0.333;-866.9
8A(QA)
0.471;-805.0
A(9TA)
0.365;-825.6
QA(9A)
0.411;-784.4
9A(JA)
0.391;-805.0
9KAA
0.344;-898.7
QA(TA)
0.397;-763.8
TA(QA)
0.339;-763.8
A(JQA)
0.376;-743.1
AA(JQ)
0.381;-743.1
(QA)(KA)
0.342;-566.9
KKAA
0.405;-681.2
2(25A)
0.361;-1320.6
27(2A)
0.302;-1279.4
(2T)(2A)
0.412;-1082.5
2(2KA)
0.335;-1155.6
(236A)
0.288;-1414.4
(23TA)
0.313;-1331.9
33(2A)
0.322;-1341.2
(36)(2A)
0.378;-1279.4
3(29A)
0.322;-1352.5
3J(2A)
0.329;-1311.2
(245A)
0.258;-1414.4
(249A)
0.335;-1331.9
(24KA)
0.344;-1249.4
46(2A)
0.362;-1393.8
(49)(2A)
0.399;-1196.9
4(2QA)
0.324;-1270.0
6(25A)
0.278;-1373.1
T(25A)
0.262;-1290.6
5(26A)
0.373;-1373.1
58(2A)
0.341;-1331.9
(5J)(2A)
0.306;-1135.0
6(26A)
0.343;-1217.5
T(26A)
0.357;-1270.0
6(27A)
0.272;-1331.9
69(2A)
0.358;-1290.6
(6Q)(2A)
0.372;-1093.8
(279A)
0.327;-1270.0
(27KA)
0.361;-1187.5
79(2A)
0.348;-1270.0
(7Q)(2A)
0.414;-1073.1
(28TA)
0.339;-1228.8
88(2A)
0.334;-1135.0
(8J)(2A)
0.412;-1073.1
9(29A)
0.384;-1093.8
K(29A)
0.342;-1146.2
9(2QA)
0.331;-1166.9
J(2TA)
0.305;-1166.9
TJ(2A)
0.345;-1166.9
(2JQA)
0.398;-1125.6
J(2KA)
0.361;-1105.0
(QK)(2A)
0.334;-949.4
22(4A)
0.314;-1341.2
226A
0.331;-1435.0
2A(29)
0.305;-1238.1
22(QA)
0.296;-1176.2
2(34A)
0.320;-1455.6
26(3A)
0.352;-1414.4
(29)(3A)
0.305;-1217.5
2(3QA)
0.372;-1290.6
A(234)
0.299;-1455.6
(23)(7A)
0.296;-1258.8
9A(23)
0.362;-1352.5
A(23Q)
0.332;-1290.6
2A(34)
0.335;-1455.6
2A(36)
0.269;-1414.4
2A(38)
0.332;-1373.1
2A(3T)
0.343;-1331.9
2A(3Q)
0.318;-1290.6
2(45A)
0.325;-1414.4
27(4A)
0.384;-1373.1
(2T)(4A)
0.320;-1176.2
2(4KA)
0.368;-1249.4
A(246)
0.313;-1393.8
(24)(9A)
0.335;-1196.9
JA(24)
0.359;-1290.6
24(5A)
0.317;-1414.4
24(7A)
0.294;-1373.1
24(9A)
0.314;-1331.9
24(JA)
0.304;-1290.6
24(KA)
0.341;-1249.4
26(5A)
0.314;-1373.1
(29)(5A)
0.362;-1176.2
2(5QA)
0.326;-1249.4
A(256)
0.352;-1373.1
(25)(9A)
0.398;-1176.2
JA(25)
0.297;-1270.0
25(6A)
0.318;-1373.1
25(8A)
0.364;-1331.9
25(TA)
0.268;-1290.6
25(QA)
0.326;-1249.4
(26)(6A)
0.425;-1082.5
2(69A)
0.350;-1290.6
2J(6A)
0.281;-1249.4
(26)(7A)
0.345;-1196.9
9A(26)
0.315;-1290.6
A(26Q)
0.348;-1228.8
2A(67)
0.259;-1331.9
2A(69)
0.328;-1290.6
2A(6J)
0.343;-1249.4
2A(6K)
0.367;-1208.1
(29)(7A)
0.331;-1135.0
2(7QA)
0.289;-1208.1
A(278)
0.303;-1290.6
(27)(JA)
0.367;-1093.8
KA(27)
0.322;-1187.5
2A(79)
0.314;-1270.0
2A(7J)
0.292;-1228.8
2A(7K)
0.301;-1187.5
(2T)(8A)
0.339;-1093.8
2(8KA)
0.354;-1166.9
A(28T)
0.400;-1228.8
(28)(KA)
0.384;-1031.9
28(TA)
0.373;-1228.8
28(QA)
0.362;-1187.5
(29)(9A)
0.346;-958.8
2(9QA)
0.296;-1166.9
A(29T)
0.350;-1208.1
(29)(KA)
0.387;-1011.2
29(JA)
0.419;-1187.5
29(KA)
0.338;-1146.2
2J(TA)
0.346;-1166.9
(2T)(JA)
0.404;-1031.9
KA(2T)
0.294;-1125.6
2A(TQ)
0.326;-1146.2
2(JQA)
0.349;-1125.6
A(2JQ)
0.368;-1125.6
2A(JQ)
0.363;-1125.6
2(QKA)
0.302;-1084.4
2Q(KA)
0.316;-1084.4
33(3A)
0.319;-1185.6
(36)(3A)
0.337;-1123.8
3(39A)
0.297;-1196.9
3J(3A)
0.374;-1155.6
(345A)
0.365;-1393.8
(349A)
0.309;-1311.2
(34KA)
0.356;-1228.8
46(3A)
0.309;-1373.1
(49)(3A)
0.307;-1176.2
4(3QA)
0.369;-1249.4
6(35A)
0.326;-1352.5
T(35A)
0.350;-1270.0
5(36A)
0.314;-1352.5
58(3A)
0.398;-1311.2
(5J)(3A)
0.308;-1114.4
6(36A)
0.407;-1196.9
T(36A)
0.357;-1249.4
6(37A)
0.289;-1311.2
69(3A)
0.305;-1270.0
(6Q)(3A)
0.343;-1073.1
(379A)
0.373;-1249.4
(37KA)
0.312;-1166.9
79(3A)
0.377;-1249.4
(7Q)(3A)
0.336;-1052.5
(38TA)
0.385;-1208.1
88(3A)
0.338;-1114.4
(8J)(3A)
0.377;-1052.5
9(39A)
0.364;-1073.1
K(39A)
0.339;-1125.6
9(3QA)
0.329;-1146.2
J(3TA)
0.326;-1146.2
TJ(3A)
0.394;-1146.2
(3JQA)
0.397;-1105.0
J(3KA)
0.404;-1084.4
(QK)(3A)
0.377;-928.7
33(5A)
0.339;-1279.4
337A
0.328;-1373.1
3A(3T)
0.370;-1176.2
33(KA)
0.320;-1114.4
3(46A)
0.259;-1373.1
38(4A)
0.353;-1331.9
(3J)(4A)
0.409;-1135.0
4A(34)
0.379;-1279.4
A(347)
0.312;-1352.5
(34)(TA)
0.295;-1155.6
QA(34)
0.317;-1249.4
345A
0.245;-1528.8
347A
0.290;-1487.5
349A
0.342;-1446.2
34JA
0.310;-1405.0
34KA
0.353;-1363.8
37(5A)
0.373;-1331.9
(3T)(5A)
0.394;-1135.0
3(5KA)
0.302;-1208.1
A(357)
0.376;-1331.9
(35)(TA)
0.322;-1135.0
QA(35)
0.361;-1228.8
356A
0.328;-1487.5
358A
0.315;-1446.2
35TA
0.394;-1405.0
35QA
0.284;-1363.8
(37)(6A)
0.355;-1176.2
3(6TA)
0.352;-1249.4
3Q(6A)
0.288;-1208.1
(36)(8A)
0.318;-1155.6
TA(36)
0.321;-1249.4
A(36K)
0.321;-1187.5
6A(38)
0.374;-1290.6
6A(3T)
0.350;-1249.4
6A(3Q)
0.319;-1208.1
37(7A)
0.284;-1155.6
(3T)(7A)
0.321;-1093.8
3(7KA)
0.353;-1166.9
A(379)
0.348;-1249.4
(37)(QA)
0.312;-1052.5
7A(38)
0.366;-1270.0
7A(3T)
0.346;-1228.8
7A(3Q)
0.346;-1187.5
38(8A)
0.313;-1114.4
(3J)(8A)
0.384;-1052.5
8A(38)
0.366;-1114.4
A(38J)
0.367;-1187.5
388A
0.334;-1249.4
38TA
0.318;-1343.1
38QA
0.365;-1301.9
(3T)(9A)
0.430;-1052.5
3(9KA)
0.299;-1125.6
A(39J)
0.364;-1166.9
399A
0.299;-1208.1
39JA
0.383;-1301.9
39KA
0.347;-1260.6
3Q(TA)
0.308;-1125.6
(3T)(QA)
0.306;-990.6
TA(3J)
0.313;-1146.2
TA(3K)
0.303;-1105.0
3(JKA)
0.380;-1084.4
A(3JK)
0.363;-1084.4
JA(3K)
0.307;-1084.4
QA(3Q)
0.393;-949.4
3QKA
0.350;-1198.8
45(4A)
0.364;-1238.1
(48)(4A)
0.378;-1041.2
4(4JA)
0.324;-1114.4
4K(4A)
0.276;-1073.1
(459A)
0.378;-1270.0
(45KA)
0.327;-1187.5
57(4A)
0.334;-1311.2
(5T)(4A)
0.297;-1114.4
5(4KA)
0.319;-1187.5
(469A)
0.359;-1249.4
(46KA)
0.324;-1166.9
68(4A)
0.359;-1270.0
(6J)(4A)
0.332;-1073.1
7(47A)
0.352;-1135.0
J(47A)
0.377;-1187.5
78(4A)
0.338;-1249.4
(7J)(4A)
0.337;-1052.5
8(48A)
0.357;-1093.8
Q(48A)
0.369;-1146.2
(8T)(4A)
0.397;-1052.5
8(4KA)
0.375;-1125.6
(49QA)
0.357;-1125.6
9(4JA)
0.331;-1146.2
9K(4A)
0.291;-1105.0
TT(4A)
0.337;-1011.2
(TK)(4A)
0.320;-949.4
J(4QA)
0.365;-1084.4
K(4QA)
0.324;-1043.1
44(5A)
0.280;-1238.1
447A
0.360;-1331.9
4A(4T)
0.384;-1135.0
44(KA)
0.281;-1073.1
4(57A)
0.330;-1311.2
49(5A)
0.321;-1270.0
(4Q)(5A)
0.403;-1073.1
6A(45)
0.356;-1331.9
A(459)
0.325;-1270.0
(45)(QA)
0.415;-1073.1
5A(46)
0.343;-1331.9
5A(48)
0.353;-1290.6
5A(4T)
0.305;-1249.4
5A(4Q)
0.295;-1208.1
46(6A)
0.321;-1176.2
(49)(6A)
0.317;-1114.4
4(6QA)
0.326;-1187.5
A(467)
0.334;-1290.6
(46)(TA)
0.363;-1093.8
QA(46)
0.358;-1187.5
467A
0.267;-1425.6
469A
0.328;-1384.4
46JA
0.340;-1343.1
46KA
0.330;-1301.9
49(7A)
0.296;-1228.8
(4Q)(7A)
0.339;-1031.9
8A(47)
0.392;-1249.4
A(47J)
0.303;-1187.5
477A
0.358;-1270.0
479A
0.377;-1363.8
47JA
0.275;-1322.5
47KA
0.381;-1281.2
4T(8A)
0.367;-1187.5
(4K)(8A)
0.390;-990.6
TA(48)
0.363;-1187.5
A(48K)
0.333;-1125.6
8A(4T)
0.281;-1187.5
8A(4Q)
0.342;-1146.2
49(9A)
0.429;-1052.5
(4Q)(9A)
0.346;-990.6
TA(49)
0.325;-1166.9
A(49K)
0.344;-1105.0
9A(4J)
0.366;-1146.2
9A(4K)
0.343;-1105.0
4(TQA)
0.301;-1105.0
A(4TJ)
0.376;-1125.6
4TTA
0.291;-1146.2
4TQA
0.298;-1240.0
(4Q)(JA)
0.363;-949.4
QA(4J)
0.359;-1084.4
4JQA
0.377;-1219.4
(4K)(QA)
0.355;-908.1
QA(4K)
0.346;-1043.1
5(56A)
0.325;-1176.2
58(5A)
0.314;-1135.0
(5J)(5A)
0.376;-938.1
6(56A)
0.399;-1155.6
T(56A)
0.331;-1208.1
6(57A)
0.395;-1270.0
69(5A)
0.301;-1228.8
(6Q)(5A)
0.432;-1031.9
(579A)
0.364;-1208.1
(57KA)
0.373;-1125.6
79(5A)
0.315;-1208.1
(7Q)(5A)
0.386;-1011.2
(58TA)
0.354;-1166.9
88(5A)
0.358;-1073.1
(8J)(5A)
0.318;-1011.2
9(59A)
0.370;-1031.9
K(59A)
0.318;-1084.4
9(5QA)
0.362;-1105.0
J(5TA)
0.376;-1105.0
TJ(5A)
0.363;-1105.0
(5JQA)
0.409;-1063.8
J(5KA)
0.330;-1043.1
(QK)(5A)
0.420;-887.5
55(7A)
0.367;-1155.6
559A
0.377;-1249.4
5A(5Q)
0.419;-1052.5
(57)(6A)
0.325;-1135.0
5(6TA)
0.304;-1208.1
5Q(6A)
0.398;-1166.9
(56)(8A)
0.375;-1114.4
TA(56)
0.427;-1208.1
A(56K)
0.358;-1146.2
6A(58)
0.354;-1249.4
6A(5T)
0.323;-1208.1
6A(5Q)
0.357;-1166.9
57(7A)
0.357;-1114.4
(5T)(7A)
0.405;-1052.5
5(7KA)
0.431;-1125.6
A(579)
0.365;-1208.1
(57)(QA)
0.371;-1011.2
7A(58)
0.323;-1228.8
7A(5T)
0.305;-1187.5
7A(5Q)
0.369;-1146.2
58(8A)
0.342;-1073.1
(5J)(8A)
0.377;-1011.2
8A(58)
0.339;-1073.1
A(58J)
0.359;-1146.2
588A
0.284;-1208.1
58TA
0.352;-1301.9
58QA
0.387;-1260.6
(5T)(9A)
0.390;-1011.2
5(9KA)
0.403;-1084.4
A(59J)
0.382;-1125.6
599A
0.338;-1166.9
59JA
0.327;-1260.6
59KA
0.382;-1219.4
5Q(TA)
0.368;-1084.4
(5T)(QA)
0.329;-949.4
TA(5J)
0.387;-1105.0
TA(5K)
0.365;-1063.8
5(JKA)
0.400;-1043.1
A(5JK)
0.323;-1043.1
JA(5K)
0.301;-1043.1
QA(5Q)
0.363;-908.1
5QKA
0.356;-1157.5
67(6A)
0.304;-1114.4
(6T)(6A)
0.348;-917.5
6(6KA)
0.369;-990.6
(67TA)
0.367;-1166.9
77(6A)
0.339;-1093.8
(7T)(6A)
0.374;-1031.9
7(6KA)
0.390;-1105.0
(68JA)
0.342;-1125.6
(89)(6A)
0.331;-1031.9
8(6QA)
0.308;-1105.0
T(69A)
0.405;-1125.6
9(6TA)
0.373;-1125.6
9Q(6A)
0.326;-1084.4
Q(6TA)
0.386;-1063.8
(TQ)(6A)
0.361;-928.7
(6JKA)
0.349;-1022.5
JK(6A)
0.438;-1022.5
K(6KA)
0.392;-846.3
668A
0.334;-1228.8
6A(6J)
0.422;-1031.9
(67)(7A)
0.359;-958.8
6(7TA)
0.416;-1166.9
6Q(7A)
0.428;-1125.6
(67)(9A)
0.333;-1052.5
JA(67)
0.353;-1146.2
67(8A)
0.354;-1208.1
67(TA)
0.325;-1166.9
67(QA)
0.410;-1125.6
(68)(8A)
0.412;-917.5
6(8JA)
0.419;-1125.6
6K(8A)
0.373;-1084.4
(68)(JA)
0.360;-990.6
KA(68)
0.341;-1084.4
6A(8T)
0.333;-1146.2
6A(8Q)
0.356;-1105.0
6(9TA)
0.436;-1125.6
6Q(9A)
0.306;-1084.4
(69)(JA)
0.370;-970.0
KA(69)
0.325;-1063.8
6A(9J)
0.342;-1105.0
6A(9K)
0.367;-1063.8
(6Q)(TA)
0.425;-928.7
JA(6T)
0.368;-1084.4
6T(JA)
0.339;-1084.4
6T(KA)
0.366;-1043.1
6Q(JA)
0.348;-1043.1
(6J)(KA)
0.402;-887.5
6J(KA)
0.342;-1022.5
6K(QA)
0.403;-1001.9
6A(QK)
0.374;-1001.9
(78)(7A)
0.377;-917.5
7(7JA)
0.322;-990.6
7K(7A)
0.382;-949.4
(78QA)
0.348;-1084.4
8(7TA)
0.409;-1125.6
8Q(7A)
0.402;-1084.4
J(79A)
0.333;-1084.4
9T(7A)
0.301;-1105.0
(9K)(7A)
0.330;-908.1
K(7TA)
0.319;-1022.5
T(7KA)
0.360;-1022.5
JJ(7A)
0.422;-908.1
(7QKA)
0.381;-981.3
777A
0.366;-1073.1
7A(7T)
0.364;-1011.2
77(KA)
0.429;-949.4
7(8TA)
0.364;-1125.6
7Q(8A)
0.413;-1084.4
(78)(TA)
0.361;-990.6
QA(78)
0.360;-1084.4
789A
0.379;-1281.2
78JA
0.273;-1240.0
78KA
0.362;-1198.8
7J(9A)
0.354;-1084.4
(79)(TA)
0.384;-970.0
QA(79)
0.385;-1063.8
79TA
0.363;-1240.0
79QA
0.357;-1198.8
(7J)(TA)
0.358;-928.7
TA(7T)
0.369;-949.4
A(7TK)
0.367;-1022.5
TA(7Q)
0.388;-1043.1
7J(JA)
0.368;-908.1
(7J)(QA)
0.415;-887.5
JA(7Q)
0.359;-1022.5
7Q(QA)
0.383;-866.9
7QQA
0.410;-1001.9
7KKA
0.328;-960.6
8(8JA)
0.383;-949.4
8K(8A)
0.375;-908.1
(89KA)
0.393;-1022.5
9J(8A)
0.349;-1063.8
(8TJA)
0.419;-1043.1
(TJ)(8A)
0.405;-908.1
J(8JA)
0.356;-887.5
JQ(8A)
0.360;-1001.9
Q(8KA)
0.345;-960.6
889A
0.378;-1125.6
8A(8Q)
0.343;-928.7
(8T)(9A)
0.387;-949.4
8(9KA)
0.317;-1022.5
A(89J)
0.333;-1063.8
899A
0.361;-1105.0
89JA
0.345;-1198.8
89KA
0.385;-1157.5
8Q(TA)
0.379;-1022.5
(8T)(QA)
0.360;-887.5
TA(8J)
0.437;-1043.1
TA(8K)
0.332;-1001.9
8(JKA)
0.407;-981.3
A(8JK)
0.320;-981.3
JA(8K)
0.391;-981.3
QA(8Q)
0.353;-846.3
8QKA
0.301;-1095.6
9T(9A)
0.401;-928.7
(9K)(9A)
0.426;-731.9
K(9TA)
0.343;-981.3
T(9KA)
0.443;-981.3
JJ(9A)
0.385;-866.9
(9QKA)
0.396;-940.0
999A
0.361;-949.4
9A(9Q)
0.341;-887.5
(9J)(TA)
0.346;-887.5
TA(9T)
0.341;-908.1
A(9TK)
0.380;-981.3
TA(9Q)
0.318;-1001.9
9J(JA)
0.382;-866.9
(9J)(QA)
0.407;-846.2
JA(9Q)
0.376;-981.3
9Q(QA)
0.445;-825.6
9QQA
0.319;-960.6
9KKA
0.309;-919.4
T(TKA)
0.381;-825.6
JJ(TA)
0.323;-846.3
(TQKA)
0.336;-919.4
TTTA
0.426;-887.5
TA(TK)
0.435;-825.6
(TK)(JA)
0.447;-805.0
KA(TJ)
0.368;-940.0
TA(JK)
0.441;-940.0
(TQ)(KA)
0.370;-784.4
(TK)(KA)
0.360;-628.7
J(JKA)
0.360;-784.4
(QK)(JA)
0.385;-763.7
JJ(KA)
0.399;-784.4
QA(JQ)
0.360;-784.4
JQKA
0.365;-1033.8
QK(QA)
0.404;-743.1
QK(KA)
0.457;-722.5
22(24)
0.353;-1453.7
22(28)
0.348;-1371.2
22(2Q)
0.330;-1288.7
24(23)
0.269;-1568.1
(23)(27)
0.336;-1371.2
2(23T)
0.324;-1444.4
2Q(23)
0.325;-1403.1
23(25)
0.307;-1547.5
2237
0.251;-1641.2
22(3T)
0.329;-1444.4
23(2K)
0.317;-1382.5
2(246)
0.269;-1506.2
28(24)
0.258;-1465.0
(24)(2J)
0.341;-1268.1
2244
0.283;-1547.5
22(47)
0.238;-1485.6
24(2T)
0.306;-1423.8
224Q
0.227;-1517.5
26(25)
0.326;-1485.6
(25)(29)
0.344;-1288.7
2(25Q)
0.350;-1361.9
22(56)
0.373;-1485.6
25(29)
0.309;-1423.8
225J
0.295;-1517.5
26(26)
0.299;-1330.0
(26)(29)
0.340;-1268.1
2(26Q)
0.362;-1341.2
22(67)
0.302;-1444.4
26(2T)
0.382;-1382.5
226Q
0.327;-1476.2
28(27)
0.359;-1403.1
(27)(2J)
0.347;-1206.2
2277
0.324;-1423.8
22(7T)
0.329;-1361.9
27(2K)
0.324;-1300.0
2(28T)
0.385;-1341.2
2Q(28)
0.396;-1300.0
28(2T)
0.320;-1341.2
228Q
0.282;-1435.0
2T(29)
0.277;-1320.6
(29)(2K)
0.350;-1123.8
229J
0.310;-1435.0
2T(2T)
0.338;-1165.0
(2T)(2K)
0.322;-1103.1
22TQ
0.294;-1393.8
2Q(2J)
0.368;-1238.1
2J(2K)
0.300;-1217.5
22QQ
0.351;-1217.5
3(234)
0.321;-1547.5
36(23)
0.305;-1506.2
(23)(39)
0.308;-1309.4
3(23Q)
0.282;-1382.5
5(234)
0.306;-1641.2
9(234)
0.241;-1558.7
K(234)
0.259;-1476.2
4(237)
0.273;-1600.0
49(23)
0.296;-1558.7
(23)(4Q)
0.272;-1361.9
(2357)
0.267;-1579.4
(235J)
0.270;-1496.9
(23)(56)
0.287;-1465.0
5(239)
0.254;-1538.1
5J(23)
0.313;-1496.9
(2367)
0.240;-1558.7
(236J)
0.350;-1476.2
(23)(67)
0.268;-1423.8
6(23T)
0.312;-1496.9
6Q(23)
0.333;-1455.6
9(237)
0.312;-1496.9
K(237)
0.334;-1414.4
7(23T)
0.300;-1476.2
7Q(23)
0.297;-1435.0
T(238)
0.320;-1455.6
8(239)
0.345;-1476.2
8J(23)
0.343;-1435.0
(239T)
0.284;-1435.0
99(23)
0.283;-1320.6
(23)(9Q)
0.284;-1258.8
(23TQ)
0.282;-1373.1
T(23Q)
0.332;-1373.1
Q(23J)
0.351;-1352.5
(23)(JK)
0.280;-1196.9
QK(23)
0.281;-1311.2
23(35)
0.304;-1526.9
33(28)
0.306;-1465.0
233T
0.290;-1558.7
23(3K)
0.325;-1361.9
(24)(36)
0.316;-1485.6
3(249)
0.281;-1558.7
3J(24)
0.296;-1517.5
(34)(25)
0.318;-1506.2
27(34)
0.322;-1600.0
2(34T)
0.329;-1538.1
(34)(2K)
0.285;-1341.2
34(26)
0.258;-1620.6
34(28)
0.314;-1579.4
34(2T)
0.295;-1538.1
34(2Q)
0.311;-1496.9
(25)(35)
0.398;-1350.6
3(258)
0.289;-1558.7
3T(25)
0.361;-1517.5
(25)(3K)
0.291;-1320.6
27(35)
0.290;-1579.4
2(35T)
0.287;-1517.5
(35)(2K)
0.324;-1320.6
35(27)
0.262;-1579.4
35(29)
0.315;-1538.1
35(2J)
0.312;-1496.9
35(2K)
0.272;-1455.6
37(26)
0.342;-1558.7
(26)(3T)
0.352;-1361.9
3(26K)
0.332;-1435.0
2(368)
0.331;-1538.1
(36)(2J)
0.349;-1341.2
2K(36)
0.326;-1435.0
23(68)
0.229;-1538.1
23(6T)
0.271;-1496.9
23(6Q)
0.320;-1455.6
3(278)
0.358;-1517.5
3T(27)
0.327;-1476.2
(27)(3K)
0.397;-1279.4
29(37)
0.320;-1496.9
2(37Q)
0.309;-1435.0
23(78)
0.308;-1517.5
23(7T)
0.348;-1476.2
23(7Q)
0.336;-1435.0
3(289)
0.306;-1476.2
3J(28)
0.342;-1435.0
(38)(29)
0.402;-1341.2
2J(38)
0.281;-1435.0
38(29)
0.323;-1476.2
38(2J)
0.322;-1435.0
38(2K)
0.320;-1393.8
3T(29)
0.318;-1435.0
(29)(3K)
0.310;-1238.1
2J(39)
0.293;-1414.4
39(2T)
0.298;-1435.0
39(2Q)
0.311;-1393.8
(2T)(3T)
0.344;-1144.4
3(2TK)
0.287;-1352.5
2(3TQ)
0.309;-1373.1
23(TJ)
0.361;-1393.8
23(TK)
0.397;-1352.5
(2J)(3K)
0.317;-1196.9
2K(3J)
0.345;-1331.9
23(JK)
0.307;-1331.9
(3Q)(2K)
0.336;-1176.2
(2K)(3K)
0.369;-1020.6
4(246)
0.284;-1465.0
48(24)
0.339;-1423.8
(24)(4J)
0.318;-1226.9
5(245)
0.344;-1465.0
9(245)
0.278;-1517.5
K(245)
0.326;-1435.0
5(248)
0.288;-1538.1
5T(24)
0.307;-1496.9
(24)(5K)
0.375;-1300.0
9(246)
0.278;-1496.9
K(246)
0.288;-1414.4
6(249)
0.310;-1496.9
6J(24)
0.333;-1455.6
(2478)
0.303;-1496.9
(247Q)
0.283;-1414.4
7(249)
0.271;-1476.2
7J(24)
0.383;-1435.0
(2489)
0.280;-1455.6
(248K)
0.331;-1373.1
8T(24)
0.304;-1435.0
(24)(8K)
0.343;-1238.1
Q(249)
0.339;-1373.1
(24)(9J)
0.309;-1258.8
T(24T)
0.336;-1258.8
T(24J)
0.317;-1373.1
TK(24)
0.256;-1331.9
(24)(JQ)
0.364;-1196.9
QQ(24)
0.326;-1176.2
24(45)
0.294;-1485.6
44(28)
0.286;-1423.8
244T
0.345;-1517.5
24(4K)
0.315;-1320.6
(25)(47)
0.287;-1423.8
4(25T)
0.309;-1496.9
4Q(25)
0.319;-1455.6
(45)(27)
0.319;-1423.8
29(45)
0.373;-1517.5
2(45Q)
0.341;-1455.6
24(56)
0.259;-1579.4
24(58)
0.258;-1538.1
24(5T)
0.292;-1496.9
24(5Q)
0.372;-1455.6
4(267)
0.253;-1538.1
49(26)
0.306;-1496.9
(26)(4Q)
0.308;-1300.0
27(46)
0.276;-1538.1
2(46T)
0.255;-1476.2
(46)(2K)
0.390;-1279.4
46(28)
0.357;-1517.5
46(2T)
0.333;-1476.2
46(2Q)
0.308;-1435.0
(27)(47)
0.354;-1247.5
4(27T)
0.292;-1455.6
4Q(27)
0.363;-1414.4
(47)(29)
0.334;-1341.2
2J(47)
0.352;-1435.0
47(28)
0.340;-1496.9
47(2T)
0.345;-1455.6
47(2Q)
0.281;-1414.4
(28)(48)
0.311;-1206.2
4(28J)
0.291;-1414.4
4K(28)
0.367;-1373.1
(48)(2J)
0.349;-1279.4
2K(48)
0.368;-1373.1
24(8T)
0.280;-1435.0
24(8Q)
0.303;-1393.8
4(29T)
0.369;-1414.4
4Q(29)
0.338;-1373.1
(49)(2J)
0.307;-1258.8
2K(49)
0.279;-1352.5
24(9J)
0.327;-1393.8
24(9K)
0.385;-1352.5
(2T)(4Q)
0.306;-1217.5
2J(4T)
0.319;-1373.1
4T(2J)
0.331;-1373.1
4T(2K)
0.304;-1331.9
4Q(2J)
0.386;-1331.9
(4J)(2K)
0.321;-1176.2
4J(2K)
0.264;-1311.2
4K(2Q)
0.314;-1290.6
24(QK)
0.380;-1290.6
(25)(56)
0.413;-1288.7
5(259)
0.288;-1361.9
5J(25)
0.352;-1320.6
(2567)
0.350;-1517.5
(256J)
0.286;-1435.0
(25)(67)
0.248;-1382.5
6(25T)
0.320;-1455.6
6Q(25)
0.384;-1414.4
9(257)
0.265;-1455.6
K(257)
0.351;-1373.1
7(25T)
0.287;-1435.0
7Q(25)
0.257;-1393.8
T(258)
0.296;-1414.4
8(259)
0.292;-1435.0
8J(25)
0.314;-1393.8
(259T)
0.317;-1393.8
99(25)
0.339;-1279.4
(25)(9Q)
0.340;-1217.5
(25TQ)
0.345;-1331.9
T(25Q)
0.367;-1331.9
Q(25J)
0.364;-1311.2
(25)(JK)
0.356;-1155.6
QK(25)
0.341;-1270.0
25(57)
0.349;-1403.1
55(2T)
0.337;-1341.2
255Q
0.340;-1435.0
57(26)
0.359;-1517.5
(26)(5T)
0.329;-1320.6
5(26K)
0.279;-1393.8
2(568)
0.282;-1496.9
(56)(2J)
0.386;-1300.0
2K(56)
0.306;-1393.8
25(68)
0.360;-1496.9
25(6T)
0.260;-1455.6
25(6Q)
0.294;-1414.4
5(278)
0.366;-1476.2
5T(27)
0.290;-1435.0
(27)(5K)
0.375;-1238.1
29(57)
0.275;-1455.6
2(57Q)
0.333;-1393.8
25(78)
0.284;-1476.2
25(7T)
0.313;-1435.0
25(7Q)
0.329;-1393.8
5(289)
0.373;-1435.0
5J(28)
0.299;-1393.8
(58)(29)
0.302;-1300.0
2J(58)
0.341;-1393.8
58(29)
0.330;-1435.0
58(2J)
0.315;-1393.8
58(2K)
0.354;-1352.5
5T(29)
0.304;-1393.8
(29)(5K)
0.339;-1196.9
2J(59)
0.288;-1373.1
59(2T)
0.330;-1393.8
59(2Q)
0.359;-1352.5
(2T)(5T)
0.355;-1103.1
5(2TK)
0.282;-1311.2
2(5TQ)
0.382;-1331.9
25(TJ)
0.315;-1352.5
25(TK)
0.279;-1311.2
(2J)(5K)
0.325;-1155.6
2K(5J)
0.284;-1290.6
25(JK)
0.378;-1290.6
(5Q)(2K)
0.289;-1135.0
(2K)(5K)
0.369;-979.4
6(268)
0.366;-1341.2
6T(26)
0.365;-1300.0
(26)(6K)
0.338;-1103.1
T(267)
0.318;-1414.4
7(268)
0.345;-1455.6
7T(26)
0.246;-1414.4
(26)(7K)
0.360;-1217.5
J(268)
0.320;-1373.1
89(26)
0.336;-1414.4
(26)(8Q)
0.330;-1217.5
(269J)
0.353;-1352.5
(26)(9T)
0.329;-1238.1
9(26K)
0.279;-1311.2
(26TK)
0.291;-1290.6
TQ(26)
0.328;-1311.2
K(26J)
0.347;-1270.0
Q(26Q)
0.343;-1135.0
KK(26)
0.358;-1093.8
66(29)
0.338;-1320.6
266J
0.255;-1414.4
67(27)
0.343;-1341.2
(27)(6T)
0.334;-1279.4
6(27K)
0.340;-1352.5
2(679)
0.306;-1435.0
(67)(2Q)
0.366;-1238.1
27(68)
0.347;-1455.6
27(6T)
0.277;-1414.4
27(6Q)
0.253;-1373.1
68(28)
0.331;-1300.0
(28)(6J)
0.317;-1238.1
28(68)
0.313;-1300.0
2(68J)
0.345;-1373.1
2688
0.279;-1435.0
268T
0.258;-1528.8
268Q
0.281;-1487.5
(29)(6T)
0.386;-1238.1
6(29K)
0.342;-1311.2
2(69J)
0.321;-1352.5
2699
0.349;-1393.8
269J
0.246;-1487.5
269K
0.286;-1446.2
6Q(2T)
0.348;-1311.2
(6T)(2Q)
0.334;-1176.2
2T(6J)
0.318;-1331.9
2T(6K)
0.340;-1290.6
6(2JK)
0.364;-1270.0
2(6JK)
0.363;-1270.0
2J(6K)
0.358;-1270.0
2Q(6Q)
0.294;-1135.0
26QK
0.273;-1384.4
78(27)
0.335;-1300.0
(27)(7J)
0.397;-1103.1
8(278)
0.367;-1279.4
Q(278)
0.296;-1331.9
(27)(8T)
0.340;-1238.1
8(27K)
0.345;-1311.2
(279Q)
0.353;-1311.2
9(27J)
0.273;-1331.9
9K(27)
0.338;-1290.6
TT(27)
0.325;-1196.9
(27)(TK)
0.354;-1135.0
J(27Q)
0.299;-1270.0
K(27Q)
0.322;-1228.8
77(28)
0.354;-1300.0
277T
0.305;-1393.8
27(7K)
0.327;-1196.9
(28)(7T)
0.360;-1238.1
7(28K)
0.322;-1311.2
2(78T)
0.366;-1373.1
(78)(2K)
0.367;-1176.2
78(2T)
0.331;-1373.1
78(2Q)
0.305;-1331.9
(29)(79)
0.349;-1103.1
7(29Q)
0.327;-1311.2
2(79T)
0.291;-1352.5
(79)(2K)
0.332;-1155.6
79(2J)
0.311;-1331.9
79(2K)
0.335;-1290.6
7J(2T)
0.299;-1311.2
(7T)(2J)
0.348;-1176.2
2K(7T)
0.288;-1270.0
27(TQ)
0.281;-1290.6
7(2JQ)
0.346;-1270.0
2(7JQ)
0.363;-1270.0
27(JQ)
0.353;-1270.0
7(2QK)
0.346;-1228.8
7Q(2K)
0.357;-1228.8
88(28)
0.356;-1123.8
(28)(8J)
0.384;-1061.9
9(289)
0.370;-1217.5
K(289)
0.330;-1270.0
9(28Q)
0.397;-1290.6
J(28T)
0.348;-1290.6
TJ(28)
0.326;-1290.6
(28JQ)
0.342;-1249.4
J(28K)
0.399;-1228.8
(28)(QK)
0.342;-1073.1
88(2T)
0.340;-1217.5
288Q
0.341;-1311.2
8T(29)
0.274;-1331.9
(29)(8K)
0.296;-1135.0
2J(89)
0.316;-1311.2
89(2T)
0.284;-1331.9
89(2Q)
0.317;-1290.6
(2T)(8T)
0.350;-1041.2
8(2TK)
0.384;-1249.4
2(8TQ)
0.311;-1270.0
28(TJ)
0.320;-1290.6
28(TK)
0.361;-1249.4
(2J)(8K)
0.364;-1093.8
2K(8J)
0.355;-1228.8
28(JK)
0.358;-1228.8
(8Q)(2K)
0.371;-1073.1
(2K)(8K)
0.376;-917.5
9(29J)
0.349;-1155.6
9K(29)
0.295;-1114.4
TT(29)
0.357;-1155.6
(29)(TK)
0.316;-1093.8
J(29Q)
0.311;-1228.8
K(29Q)
0.337;-1187.5
99(2T)
0.390;-1176.2
299Q
0.327;-1270.0
9J(2T)
0.409;-1270.0
(9T)(2J)
0.374;-1135.0
2K(9T)
0.340;-1228.8
29(TQ)
0.376;-1249.4
9(2JQ)
0.328;-1228.8
2(9JQ)
0.330;-1228.8
29(JQ)
0.303;-1228.8
9(2QK)
0.306;-1187.5
9Q(2K)
0.312;-1187.5
TT(2T)
0.365;-1000.0
(2T)(TK)
0.364;-938.1
J(2TQ)
0.380;-1208.1
K(2TQ)
0.322;-1166.9
TT(2J)
0.337;-1114.4
2TTK
0.312;-1208.1
TK(2J)
0.376;-1187.5
2TJJ
0.326;-1228.8
2TJK
0.289;-1322.5
2(TQK)
0.308;-1166.9
TK(2K)
0.391;-1011.2
(2J)(JK)
0.379;-896.9
QK(2J)
0.355;-1146.2
2J(JK)
0.361;-1031.9
(JQ)(2K)
0.383;-1011.2
(2K)(JK)
0.359;-855.6
K(2QK)
0.372;-970.0
2K(QK)
0.366;-970.0
3335
0.309;-1506.2
3339
0.328;-1423.8
333K
0.261;-1341.2
36(34)
0.337;-1465.0
(34)(39)
0.348;-1268.1
3(34Q)
0.301;-1341.2
33(45)
0.277;-1485.6
34(38)
0.352;-1423.8
334T
0.259;-1517.5
33(4K)
0.345;-1320.6
(35)(37)
0.310;-1288.7
3(35T)
0.298;-1361.9
3Q(35)
0.320;-1320.6
35(37)
0.311;-1423.8
3359
0.264;-1517.5
33(5Q)
0.312;-1320.6
(36)(37)
0.333;-1268.1
3(36T)
0.380;-1341.2
3Q(36)
0.316;-1300.0
36(38)
0.375;-1382.5
336T
0.347;-1476.2
33(6K)
0.375;-1279.4
(37)(39)
0.348;-1206.2
3(37Q)
0.334;-1279.4
33(78)
0.380;-1361.9
37(3J)
0.319;-1300.0
337K
0.350;-1393.8
3T(38)
0.333;-1300.0
(38)(3K)
0.352;-1103.1
338T
0.330;-1435.0
33(8K)
0.323;-1238.1
(39)(3J)
0.300;-1123.8
3399
0.332;-1300.0
33(9Q)
0.364;-1238.1
(3T)(3J)
0.340;-1103.1
33TT
0.278;-1258.8
33(TK)
0.408;-1196.9
(3J)(3K)
0.400;-1041.2
33JK
0.333;-1311.2
33(QK)
0.399;-1155.6
45(34)
0.282;-1465.0
(34)(48)
0.383;-1268.1
4(34J)
0.271;-1341.2
4K(34)
0.282;-1300.0
(3459)
0.277;-1496.9
(345K)
0.273;-1414.4
57(34)
0.281;-1538.1
(34)(5T)
0.283;-1341.2
5(34K)
0.284;-1414.4
(3469)
0.300;-1476.2
(346K)
0.321;-1393.8
68(34)
0.320;-1496.9
(34)(6J)
0.402;-1300.0
7(347)
0.269;-1361.9
J(347)
0.300;-1414.4
78(34)
0.298;-1476.2
(34)(7J)
0.338;-1279.4
8(348)
0.270;-1320.6
Q(348)
0.361;-1373.1
(34)(8T)
0.305;-1279.4
8(34K)
0.360;-1352.5
(349Q)
0.278;-1352.5
9(34J)
0.247;-1373.1
9K(34)
0.375;-1331.9
TT(34)
0.425;-1238.1
(34)(TK)
0.370;-1176.2
J(34Q)
0.313;-1311.2
K(34Q)
0.370;-1270.0
44(35)
0.351;-1465.0
3447
0.324;-1558.7
34(4T)
0.325;-1361.9
44(3K)
0.332;-1300.0
4(357)
0.264;-1538.1
49(35)
0.282;-1496.9
(35)(4Q)
0.358;-1300.0
36(45)
0.265;-1558.7
3(459)
0.340;-1496.9
(45)(3Q)
0.383;-1300.0
35(46)
0.266;-1558.7
35(48)
0.329;-1517.5
35(4T)
0.247;-1476.2
35(4Q)
0.325;-1435.0
46(36)
0.267;-1403.1
(36)(49)
0.360;-1341.2
4(36Q)
0.350;-1414.4
3(467)
0.318;-1517.5
(46)(3T)
0.361;-1320.6
3Q(46)
0.375;-1414.4
3467
0.313;-1652.5
3469
0.236;-1611.2
346J
0.276;-1570.0
346K
0.293;-1528.8
49(37)
0.319;-1455.6
(37)(4Q)
0.348;-1258.8
38(47)
0.316;-1476.2
3(47J)
0.326;-1414.4
3477
0.312;-1496.9
3479
0.303;-1590.6
347J
0.309;-1549.4
347K
0.375;-1508.1
4T(38)
0.320;-1414.4
(38)(4K)
0.384;-1217.5
3T(48)
0.261;-1414.4
3(48K)
0.358;-1352.5
38(4T)
0.269;-1414.4
38(4Q)
0.348;-1373.1
49(39)
0.342;-1279.4
(39)(4Q)
0.341;-1217.5
3T(49)
0.328;-1393.8
3(49K)
0.313;-1331.9
39(4J)
0.294;-1373.1
39(4K)
0.280;-1331.9
4(3TQ)
0.289;-1331.9
3(4TJ)
0.371;-1352.5
34TT
0.322;-1373.1
34TQ
0.304;-1466.9
(3J)(4Q)
0.318;-1176.2
3Q(4J)
0.376;-1311.2
34JQ
0.293;-1446.2
(3Q)(4K)
0.404;-1135.0
3Q(4K)
0.338;-1270.0
5(356)
0.330;-1403.1
58(35)
0.392;-1361.9
(35)(5J)
0.406;-1165.0
6(356)
0.310;-1382.5
T(356)
0.285;-1435.0
6(357)
0.311;-1496.9
69(35)
0.348;-1455.6
(35)(6Q)
0.334;-1258.8
(3579)
0.282;-1435.0
(357K)
0.367;-1352.5
79(35)
0.313;-1435.0
(35)(7Q)
0.380;-1238.1
(358T)
0.336;-1393.8
88(35)
0.392;-1300.0
(35)(8J)
0.355;-1238.1
9(359)
0.311;-1258.8
K(359)
0.264;-1311.2
9(35Q)
0.277;-1331.9
J(35T)
0.349;-1331.9
TJ(35)
0.321;-1331.9
(35JQ)
0.347;-1290.6
J(35K)
0.370;-1270.0
(35)(QK)
0.343;-1114.4
55(37)
0.394;-1382.5
3559
0.275;-1476.2
35(5Q)
0.308;-1279.4
(36)(57)
0.308;-1361.9
5(36T)
0.254;-1435.0
5Q(36)
0.285;-1393.8
(56)(38)
0.310;-1341.2
3T(56)
0.293;-1435.0
3(56K)
0.296;-1373.1
36(58)
0.274;-1476.2
36(5T)
0.325;-1435.0
36(5Q)
0.329;-1393.8
57(37)
0.299;-1341.2
(37)(5T)
0.364;-1279.4
5(37K)
0.292;-1352.5
3(579)
0.290;-1435.0
(57)(3Q)
0.342;-1238.1
37(58)
0.287;-1455.6
37(5T)
0.284;-1414.4
37(5Q)
0.279;-1373.1
58(38)
0.324;-1300.0
(38)(5J)
0.340;-1238.1
38(58)
0.301;-1300.0
3(58J)
0.307;-1373.1
3588
0.296;-1435.0
358T
0.321;-1528.8
358Q
0.274;-1487.5
(39)(5T)
0.310;-1238.1
5(39K)
0.361;-1311.2
3(59J)
0.382;-1352.5
3599
0.334;-1393.8
359J
0.262;-1487.5
359K
0.254;-1446.2
5Q(3T)
0.393;-1311.2
(5T)(3Q)
0.380;-1176.2
3T(5J)
0.314;-1331.9
3T(5K)
0.340;-1290.6
5(3JK)
0.388;-1270.0
3(5JK)
0.325;-1270.0
3J(5K)
0.362;-1270.0
3Q(5Q)
0.313;-1135.0
35QK
0.324;-1384.4
67(36)
0.368;-1341.2
(36)(6T)
0.310;-1144.4
6(36K)
0.276;-1217.5
(367T)
0.295;-1393.8
77(36)
0.330;-1320.6
(36)(7T)
0.289;-1258.8
7(36K)
0.399;-1331.9
(368J)
0.257;-1352.5
(36)(89)
0.299;-1258.8
8(36Q)
0.367;-1331.9
T(369)
0.329;-1352.5
9(36T)
0.356;-1352.5
9Q(36)
0.321;-1311.2
Q(36T)
0.359;-1290.6
(36)(TQ)
0.420;-1155.6
(36JK)
0.308;-1249.4
JK(36)
0.295;-1249.4
K(36K)
0.355;-1073.1
3668
0.312;-1455.6
36(6J)
0.387;-1258.8
(37)(67)
0.421;-1185.6
6(37T)
0.301;-1393.8
6Q(37)
0.319;-1352.5
(67)(39)
0.311;-1279.4
3J(67)
0.350;-1373.1
67(38)
0.305;-1435.0
67(3T)
0.301;-1393.8
67(3Q)
0.259;-1352.5
(38)(68)
0.324;-1144.4
6(38J)
0.300;-1352.5
6K(38)
0.334;-1311.2
(68)(3J)
0.328;-1217.5
3K(68)
0.304;-1311.2
36(8T)
0.311;-1373.1
36(8Q)
0.292;-1331.9
6(39T)
0.291;-1352.5
6Q(39)
0.290;-1311.2
(69)(3J)
0.362;-1196.9
3K(69)
0.262;-1290.6
36(9J)
0.276;-1331.9
36(9K)
0.305;-1290.6
(3T)(6Q)
0.362;-1155.6
3J(6T)
0.290;-1311.2
6T(3J)
0.363;-1311.2
6T(3K)
0.390;-1270.0
6Q(3J)
0.381;-1270.0
(6J)(3K)
0.375;-1114.4
6J(3K)
0.287;-1249.4
6K(3Q)
0.311;-1228.8
36(QK)
0.346;-1228.8
(37)(78)
0.376;-1144.4
7(37J)
0.297;-1217.5
7K(37)
0.340;-1176.2
(378Q)
0.287;-1311.2
8(37T)
0.307;-1352.5
8Q(37)
0.337;-1311.2
J(379)
0.281;-1311.2
9T(37)
0.276;-1331.9
(37)(9K)
0.374;-1135.0
K(37T)
0.290;-1249.4
T(37K)
0.346;-1249.4
JJ(37)
0.338;-1135.0
(37QK)
0.345;-1208.1
3777
0.333;-1300.0
37(7T)
0.338;-1238.1
77(3K)
0.357;-1176.2
7(38T)
0.329;-1352.5
7Q(38)
0.321;-1311.2
(78)(3T)
0.358;-1217.5
3Q(78)
0.313;-1311.2
3789
0.321;-1508.1
378J
0.353;-1466.9
378K
0.338;-1425.6
7J(39)
0.315;-1311.2
(79)(3T)
0.364;-1196.9
3Q(79)
0.291;-1290.6
379T
0.344;-1466.9
379Q
0.377;-1425.6
(3T)(7J)
0.313;-1155.6
3T(7T)
0.337;-1176.2
3(7TK)
0.326;-1249.4
3T(7Q)
0.276;-1270.0
7J(3J)
0.333;-1135.0
(7J)(3Q)
0.381;-1114.4
3J(7Q)
0.287;-1249.4
7Q(3Q)
0.351;-1093.8
37QQ
0.413;-1228.8
37KK
0.352;-1187.5
8(38J)
0.399;-1176.2
8K(38)
0.405;-1135.0
(389K)
0.382;-1249.4
9J(38)
0.284;-1290.6
(38TJ)
0.321;-1270.0
(38)(TJ)
0.387;-1135.0
J(38J)
0.384;-1114.4
JQ(38)
0.393;-1228.8
Q(38K)
0.374;-1187.5
3889
0.281;-1352.5
38(8Q)
0.339;-1155.6
(39)(8T)
0.391;-1176.2
8(39K)
0.408;-1249.4
3(89J)
0.280;-1290.6
3899
0.315;-1331.9
389J
0.267;-1425.6
389K
0.343;-1384.4
8Q(3T)
0.343;-1249.4
(8T)(3Q)
0.275;-1114.4
3T(8J)
0.271;-1270.0
3T(8K)
0.275;-1228.8
8(3JK)
0.304;-1208.1
3(8JK)
0.312;-1208.1
3J(8K)
0.330;-1208.1
3Q(8Q)
0.383;-1073.1
38QK
0.324;-1322.5
9T(39)
0.341;-1155.6
(39)(9K)
0.351;-958.8
K(39T)
0.401;-1208.1
T(39K)
0.279;-1208.1
JJ(39)
0.347;-1093.8
(39QK)
0.371;-1166.9
3999
0.279;-1176.2
39(9Q)
0.347;-1114.4
(3T)(9J)
0.372;-1114.4
3T(9T)
0.393;-1135.0
3(9TK)
0.313;-1208.1
3T(9Q)
0.334;-1228.8
9J(3J)
0.344;-1093.8
(9J)(3Q)
0.331;-1073.1
3J(9Q)
0.341;-1208.1
9Q(3Q)
0.331;-1052.5
39QQ
0.332;-1187.5
39KK
0.364;-1146.2
T(3TK)
0.306;-1052.5
JJ(3T)
0.362;-1073.1
(3TQK)
0.354;-1146.2
3TTT
0.280;-1114.4
3T(TK)
0.356;-1052.5
(3J)(TK)
0.418;-1031.9
3K(TJ)
0.284;-1166.9
3T(JK)
0.355;-1166.9
(TQ)(3K)
0.340;-1011.2
(3K)(TK)
0.366;-855.6
J(3JK)
0.329;-1011.2
(3J)(QK)
0.401;-990.6
JJ(3K)
0.385;-1011.2
3Q(JQ)
0.335;-1011.2
3JQK
0.276;-1260.6
QK(3Q)
0.324;-970.0
QK(3K)
0.404;-949.4
44(46)
0.358;-1288.7
44(4T)
0.409;-1206.2
(45)(45)
0.355;-1153.8
4(458)
0.292;-1361.9
4T(45)
0.277;-1320.6
(45)(4K)
0.379;-1123.8
4457
0.309;-1517.5
44(5T)
0.292;-1320.6
45(4K)
0.308;-1258.8
4(468)
0.351;-1341.2
4T(46)
0.296;-1300.0
(46)(4K)
0.353;-1103.1
4468
0.268;-1476.2
44(6J)
0.259;-1279.4
(47)(47)
0.370;-1071.2
4(47T)
0.342;-1279.4
4Q(47)
0.328;-1238.1
47(49)
0.372;-1300.0
447J
0.291;-1393.8
48(48)
0.331;-1165.0
(48)(4J)
0.357;-1103.1
4488
0.345;-1300.0
44(8J)
0.390;-1238.1
(49)(49)
0.396;-988.8
4(49Q)
0.306;-1196.9
44(9T)
0.299;-1238.1
49(4K)
0.394;-1176.2
4(4TQ)
0.337;-1176.2
44(TJ)
0.370;-1196.9
(4J)(4J)
0.348;-906.2
44JJ
0.411;-1176.2
4Q(4Q)
0.321;-1000.0
(4K)(4K)
0.322;-823.8
(45)(57)
0.305;-1226.9
5(45T)
0.296;-1300.0
5Q(45)
0.362;-1258.8
8(456)
0.333;-1455.6
Q(456)
0.270;-1373.1
(45)(68)
0.317;-1320.6
6(45J)
0.362;-1393.8
6K(45)
0.317;-1352.5
(457J)
0.376;-1373.1
(45)(78)
0.296;-1300.0
7(45J)
0.347;-1373.1
7K(45)
0.304;-1331.9
(458Q)
0.337;-1331.9
8(45T)
0.293;-1373.1
8Q(45)
0.281;-1331.9
J(459)
0.337;-1331.9
9T(45)
0.285;-1352.5
(45)(9K)
0.367;-1155.6
K(45T)
0.267;-1270.0
T(45K)
0.385;-1270.0
JJ(45)
0.313;-1155.6
(45QK)
0.262;-1228.8
4555
0.311;-1403.1
45(58)
0.347;-1341.2
55(4J)
0.305;-1279.4
455K
0.382;-1373.1
58(46)
0.305;-1455.6
(46)(5J)
0.346;-1258.8
46(56)
0.272;-1361.9
4(569)
0.259;-1435.0
(56)(4Q)
0.356;-1238.1
46(57)
0.265;-1476.2
46(59)
0.301;-1435.0
46(5J)
0.285;-1393.8
46(5K)
0.383;-1352.5
5(479)
0.294;-1414.4
5J(47)
0.295;-1373.1
(57)(48)
0.404;-1300.0
4T(57)
0.369;-1393.8
4(57K)
0.324;-1331.9
47(59)
0.339;-1414.4
47(5J)
0.285;-1373.1
47(5K)
0.392;-1331.9
5(48T)
0.286;-1373.1
5Q(48)
0.398;-1331.9
(58)(4T)
0.319;-1238.1
4Q(58)
0.342;-1331.9
4589
0.324;-1528.8
458J
0.287;-1487.5
458K
0.313;-1446.2
5J(49)
0.291;-1331.9
(59)(4T)
0.413;-1217.5
4Q(59)
0.256;-1311.2
459T
0.275;-1487.5
459Q
0.241;-1446.2
(4T)(5J)
0.353;-1176.2
4T(5T)
0.392;-1196.9
4(5TK)
0.312;-1270.0
4T(5Q)
0.407;-1290.6
5J(4J)
0.350;-1155.6
(5J)(4Q)
0.398;-1135.0
4J(5Q)
0.328;-1270.0
5Q(4Q)
0.314;-1114.4
45QQ
0.357;-1249.4
45KK
0.332;-1208.1
6(469)
0.364;-1279.4
6J(46)
0.301;-1238.1
(4678)
0.321;-1414.4
(467Q)
0.307;-1331.9
7(469)
0.344;-1393.8
7J(46)
0.335;-1352.5
(4689)
0.341;-1373.1
(468K)
0.300;-1290.6
8T(46)
0.297;-1352.5
(46)(8K)
0.388;-1155.6
Q(469)
0.327;-1290.6
(46)(9J)
0.365;-1176.2
T(46T)
0.395;-1176.2
T(46J)
0.344;-1290.6
TK(46)
0.328;-1249.4
(46)(JQ)
0.345;-1114.4
QQ(46)
0.344;-1093.8
46(67)
0.305;-1320.6
66(4T)
0.278;-1258.8
466Q
0.313;-1352.5
68(47)
0.296;-1414.4
(47)(6J)
0.398;-1217.5
47(67)
0.385;-1300.0
4(67T)
0.327;-1373.1
(67)(4K)
0.385;-1176.2
67(49)
0.336;-1393.8
67(4J)
0.373;-1352.5
67(4K)
0.325;-1311.2
69(48)
0.353;-1373.1
(48)(6Q)
0.371;-1176.2
49(68)
0.321;-1373.1
4(68Q)
0.347;-1311.2
46(89)
0.335;-1373.1
46(8J)
0.298;-1331.9
46(8K)
0.347;-1290.6
(49)(6J)
0.287;-1176.2
49(69)
0.358;-1217.5
4(69Q)
0.293;-1290.6
46(9T)
0.361;-1331.9
46(9Q)
0.292;-1290.6
6(4TJ)
0.369;-1290.6
6K(4T)
0.370;-1249.4
(6T)(4K)
0.392;-1114.4
6T(4Q)
0.277;-1270.0
(4J)(6J)
0.420;-1000.0
4J(6J)
0.302;-1135.0
6J(4Q)
0.338;-1249.4
(4Q)(6Q)
0.349;-958.8
4K(6Q)
0.344;-1208.1
4K(6K)
0.388;-1052.5
79(47)
0.327;-1238.1
(47)(7Q)
0.375;-1041.2
(478T)
0.275;-1331.9
88(47)
0.408;-1238.1
(47)(8J)
0.320;-1176.2
9(479)
0.296;-1196.9
K(479)
0.383;-1249.4
9(47Q)
0.364;-1270.0
J(47T)
0.320;-1270.0
TJ(47)
0.356;-1270.0
(47JQ)
0.324;-1228.8
J(47K)
0.407;-1208.1
(47)(QK)
0.293;-1052.5
77(49)
0.403;-1238.1
477J
0.340;-1331.9
78(48)
0.326;-1238.1
(48)(7J)
0.339;-1176.2
48(78)
0.379;-1238.1
4(78J)
0.395;-1311.2
4788
0.315;-1373.1
478T
0.245;-1466.9
478Q
0.344;-1425.6
(49)(7T)
0.304;-1176.2
7(49K)
0.338;-1249.4
4(79J)
0.351;-1290.6
4799
0.360;-1331.9
479J
0.278;-1425.6
479K
0.283;-1384.4
7Q(4T)
0.332;-1249.4
(7T)(4Q)
0.394;-1114.4
4T(7J)
0.298;-1270.0
4T(7K)
0.345;-1228.8
7(4JK)
0.366;-1208.1
4(7JK)
0.302;-1208.1
4J(7K)
0.346;-1208.1
4Q(7Q)
0.350;-1073.1
47QK
0.306;-1322.5
89(48)
0.307;-1196.9
(48)(8Q)
0.369;-1000.0
(489J)
0.369;-1270.0
(48)(9T)
0.387;-1155.6
9(48K)
0.329;-1228.8
(48TK)
0.300;-1208.1
TQ(48)
0.321;-1228.8
K(48J)
0.327;-1187.5
Q(48Q)
0.355;-1052.5
KK(48)
0.405;-1011.2
88(4J)
0.393;-1155.6
488K
0.388;-1249.4
8J(49)
0.391;-1270.0
(89)(4T)
0.341;-1155.6
4Q(89)
0.399;-1249.4
489T
0.268;-1425.6
489Q
0.356;-1384.4
(4T)(8J)
0.349;-1114.4
4T(8T)
0.338;-1135.0
4(8TK)
0.370;-1208.1
4T(8Q)
0.282;-1228.8
8J(4J)
0.363;-1093.8
(8J)(4Q)
0.361;-1073.1
4J(8Q)
0.344;-1208.1
8Q(4Q)
0.397;-1052.5
48QQ
0.359;-1187.5
48KK
0.376;-1146.2
9(49Q)
0.400;-1093.8
J(49T)
0.369;-1228.8
TJ(49)
0.368;-1228.8
(49JQ)
0.352;-1187.5
J(49K)
0.387;-1166.9
(49)(QK)
0.400;-1011.2
99(4J)
0.377;-1114.4
499K
0.355;-1208.1
9Q(4T)
0.400;-1208.1
(9T)(4Q)
0.372;-1073.1
4T(9J)
0.349;-1228.8
4T(9K)
0.377;-1187.5
9(4JK)
0.312;-1166.9
4(9JK)
0.394;-1166.9
4J(9K)
0.348;-1166.9
4Q(9Q)
0.365;-1031.9
49QK
0.295;-1281.2
TJ(4T)
0.405;-1073.1
(4TJQ)
0.322;-1166.9
J(4TK)
0.353;-1146.2
(4T)(QK)
0.422;-990.6
TT(4Q)
0.300;-1052.5
T(4JQ)
0.403;-1166.9
4(TJQ)
0.387;-1166.9
4T(JQ)
0.356;-1166.9
T(4QK)
0.390;-1125.6
TQ(4K)
0.336;-1125.6
JJ(4J)
0.343;-896.9
(4JQK)
0.350;-1105.0
4JJJ
0.384;-1031.9
JQ(4Q)
0.400;-990.6
4JQQ
0.335;-1125.6
4JKK
0.415;-1084.4
QQ(4K)
0.422;-949.4
4KKK
0.389;-908.1
55(59)
0.345;-1165.0
55(5K)
0.291;-1082.5
(56)(58)
0.313;-1165.0
5(56J)
0.291;-1238.1
5K(56)
0.332;-1196.9
56(59)
0.301;-1279.4
556J
0.279;-1373.1
57(57)
0.371;-1165.0
(57)(5T)
0.415;-1103.1
5(57K)
0.418;-1176.2
55(79)
0.315;-1258.8
57(5Q)
0.332;-1196.9
5(589)
0.325;-1238.1
5J(58)
0.362;-1196.9
58(59)
0.324;-1238.1
558J
0.353;-1331.9
59(59)
0.383;-1082.5
(59)(5Q)
0.327;-1020.6
559T
0.261;-1331.9
55(9K)
0.303;-1135.0
(5T)(5Q)
0.433;-1000.0
55TJ
0.339;-1290.6
5J(5J)
0.359;-1000.0
5J(5Q)
0.360;-1114.4
5(5QK)
0.327;-1073.1
5K(5K)
0.356;-917.5
68(56)
0.303;-1279.4
(56)(6J)
0.420;-1082.5
7(567)
0.339;-1279.4
J(567)
0.373;-1331.9
78(56)
0.345;-1393.8
(56)(7J)
0.369;-1196.9
8(568)
0.378;-1238.1
Q(568)
0.312;-1290.6
(56)(8T)
0.351;-1196.9
8(56K)
0.287;-1270.0
(569Q)
0.288;-1270.0
9(56J)
0.362;-1290.6
9K(56)
0.342;-1249.4
TT(56)
0.360;-1155.6
(56)(TK)
0.346;-1093.8
J(56Q)
0.340;-1228.8
K(56Q)
0.364;-1187.5
66(57)
0.314;-1300.0
5669
0.307;-1393.8
56(6Q)
0.285;-1196.9
(57)(68)
0.372;-1258.8
6(57J)
0.292;-1331.9
6K(57)
0.345;-1290.6
(67)(5T)
0.297;-1217.5
5Q(67)
0.372;-1311.2
5678
0.294;-1528.8
567T
0.259;-1487.5
567Q
0.389;-1446.2
(58)(69)
0.404;-1217.5
6(58Q)
0.338;-1290.6
5(689)
0.283;-1352.5
(68)(5Q)
0.303;-1155.6
58(69)
0.365;-1352.5
58(6J)
0.321;-1311.2
58(6K)
0.277;-1270.0
6(59J)
0.323;-1290.6
6K(59)
0.343;-1249.4
(69)(5Q)
0.352;-1135.0
59(6T)
0.332;-1311.2
59(6Q)
0.263;-1270.0
6T(5T)
0.276;-1155.6
(5T)(6K)
0.438;-1093.8
5Q(6T)
0.339;-1249.4
56TJ
0.272;-1405.0
56TK
0.269;-1363.8
6K(5J)
0.295;-1208.1
56JJ
0.336;-1249.4
56JK
0.332;-1343.1
5(6QK)
0.347;-1187.5
6K(5K)
0.401;-1031.9
(57)(79)
0.334;-1082.5
7(57Q)
0.379;-1155.6
9(578)
0.371;-1331.9
K(578)
0.379;-1249.4
8(57J)
0.345;-1290.6
8K(57)
0.413;-1249.4
(579K)
0.299;-1228.8
9J(57)
0.318;-1270.0
(57TJ)
0.327;-1249.4
(57)(TJ)
0.382;-1114.4
J(57J)
0.329;-1093.8
JQ(57)
0.339;-1208.1
Q(57K)
0.297;-1166.9
5778
0.258;-1373.1
57(7J)
0.394;-1176.2
(58)(78)
0.388;-1082.5
7(58J)
0.331;-1290.6
7K(58)
0.301;-1249.4
(78)(5J)
0.413;-1155.6
5K(78)
0.283;-1249.4
57(8T)
0.270;-1311.2
57(8Q)
0.300;-1270.0
7(59T)
0.327;-1290.6
7Q(59)
0.291;-1249.4
(79)(5J)
0.284;-1135.0
5K(79)
0.343;-1228.8
57(9J)
0.320;-1270.0
57(9K)
0.310;-1228.8
(5T)(7Q)
0.441;-1093.8
5J(7T)
0.306;-1249.4
7T(5J)
0.321;-1249.4
7T(5K)
0.317;-1208.1
7Q(5J)
0.367;-1208.1
(7J)(5K)
0.402;-1052.5
7J(5K)
0.413;-1187.5
7K(5Q)
0.367;-1166.9
57(QK)
0.380;-1166.9
(58)(89)
0.333;-1041.2
8(58Q)
0.282;-1114.4
T(589)
0.348;-1270.0
9(58T)
0.320;-1270.0
9Q(58)
0.349;-1228.8
Q(58T)
0.377;-1208.1
(58)(TQ)
0.344;-1073.1
(58JK)
0.331;-1166.9
JK(58)
0.321;-1166.9
K(58K)
0.349;-990.6
588T
0.291;-1290.6
58(8K)
0.348;-1093.8
(59)(8J)
0.399;-1114.4
59(89)
0.348;-1155.6
5(89Q)
0.363;-1228.8
58(9T)
0.381;-1270.0
58(9Q)
0.320;-1228.8
8(5TJ)
0.356;-1228.8
8K(5T)
0.354;-1187.5
(8T)(5K)
0.393;-1052.5
8T(5Q)
0.310;-1208.1
(5J)(8J)
0.405;-938.1
5J(8J)
0.338;-1073.1
8J(5Q)
0.346;-1187.5
(5Q)(8Q)
0.342;-896.9
5K(8Q)
0.361;-1146.2
5K(8K)
0.340;-990.6
9J(59)
0.358;-1093.8
(59TJ)
0.386;-1208.1
(59)(TJ)
0.425;-1073.1
J(59J)
0.402;-1052.5
JQ(59)
0.417;-1166.9
Q(59K)
0.338;-1125.6
599T
0.321;-1249.4
59(9K)
0.339;-1052.5
(5T)(9Q)
0.363;-1052.5
5J(9T)
0.391;-1208.1
9T(5J)
0.362;-1208.1
9T(5K)
0.355;-1166.9
9Q(5J)
0.327;-1166.9
(9J)(5K)
0.349;-1011.2
9J(5K)
0.405;-1146.2
9K(5Q)
0.338;-1125.6
59(QK)
0.326;-1125.6
(5T)(TJ)
0.413;-917.5
J(5TJ)
0.323;-1031.9
JQ(5T)
0.343;-1146.2
Q(5TK)
0.374;-1105.0
5TTJ
0.382;-1187.5
TJ(5J)
0.305;-1031.9
(TJ)(5Q)
0.361;-1011.2
5J(TQ)
0.359;-1146.2
TQ(5Q)
0.373;-990.6
5TQQ
0.407;-1125.6
5TKK
0.327;-1084.4
Q(5JQ)
0.378;-970.0
KK(5J)
0.400;-928.7
(5Q)(JQ)
0.356;-835.0
5K(JQ)
0.369;-1084.4
5K(JK)
0.337;-928.7
5QQQ
0.350;-949.4
KK(5K)
0.380;-752.5
6669
0.333;-1238.1
666K
0.379;-1155.6
69(67)
0.342;-1217.5
(67)(6Q)
0.347;-1020.6
6678
0.391;-1373.1
66(7J)
0.334;-1176.2
(68)(68)
0.385;-947.5
6(68J)
0.350;-1155.6
6K(68)
0.318;-1114.4
68(6J)
0.396;-1155.6
668K
0.365;-1249.4
6J(69)
0.389;-1135.0
69(6T)
0.417;-1155.6
669Q
0.288;-1249.4
6J(6T)
0.372;-1114.4
6T(6J)
0.393;-1114.4
66TK
0.342;-1208.1
6K(6J)
0.352;-1052.5
(6Q)(6Q)
0.365;-782.5
66QK
0.392;-1166.9
7(679)
0.322;-1196.9
7J(67)
0.342;-1155.6
(6789)
0.275;-1311.2
(678K)
0.327;-1228.8
8T(67)
0.336;-1290.6
(67)(8K)
0.293;-1093.8
Q(679)
0.375;-1228.8
(67)(9J)
0.383;-1114.4
T(67T)
0.308;-1114.4
T(67J)
0.366;-1228.8
TK(67)
0.312;-1187.5
(67)(JQ)
0.393;-1052.5
QQ(67)
0.324;-1031.9
67(78)
0.377;-1217.5
77(6J)
0.377;-1155.6
677K
0.368;-1249.4
7T(68)
0.289;-1290.6
(68)(7K)
0.288;-1093.8
6T(78)
0.277;-1290.6
6(78K)
0.368;-1228.8
68(7T)
0.309;-1290.6
68(7Q)
0.343;-1249.4
79(69)
0.288;-1155.6
(69)(7Q)
0.313;-1093.8
6T(79)
0.303;-1270.0
6(79K)
0.348;-1208.1
69(7J)
0.384;-1249.4
69(7K)
0.356;-1208.1
7(6TQ)
0.343;-1208.1
6(7TJ)
0.314;-1228.8
67TT
0.293;-1249.4
67TQ
0.296;-1343.1
(6J)(7Q)
0.335;-1052.5
6Q(7J)
0.362;-1187.5
67JQ
0.280;-1322.5
(6Q)(7K)
0.323;-1011.2
6Q(7K)
0.414;-1146.2
8(689)
0.333;-1155.6
8J(68)
0.327;-1114.4
(689T)
0.307;-1249.4
99(68)
0.357;-1135.0
(68)(9Q)
0.379;-1073.1
(68TQ)
0.380;-1187.5
T(68Q)
0.313;-1187.5
Q(68J)
0.326;-1166.9
(68)(JK)
0.324;-1011.2
QK(68)
0.332;-1125.6
68(8T)
0.369;-1135.0
88(6K)
0.368;-1073.1
8(69J)
0.365;-1228.8
8K(69)
0.380;-1187.5
(89)(6Q)
0.402;-1073.1
69(8T)
0.365;-1249.4
69(8Q)
0.316;-1208.1
8T(6T)
0.426;-1093.8
(6T)(8K)
0.363;-1031.9
6Q(8T)
0.363;-1187.5
68TJ
0.355;-1343.1
68TK
0.345;-1301.9
8K(6J)
0.365;-1146.2
68JJ
0.323;-1187.5
68JK
0.389;-1281.2
6(8QK)
0.320;-1125.6
8K(6K)
0.375;-970.0
(69)(9J)
0.362;-938.1
T(69T)
0.364;-1073.1
T(69J)
0.329;-1187.5
TK(69)
0.351;-1146.2
(69)(JQ)
0.322;-1011.2
QQ(69)
0.394;-990.6
69(9T)
0.319;-1093.8
99(6K)
0.346;-1031.9
9(6TQ)
0.365;-1166.9
6(9TJ)
0.368;-1187.5
69TT
0.335;-1208.1
69TQ
0.298;-1301.9
(6J)(9Q)
0.399;-1011.2
6Q(9J)
0.311;-1146.2
69JQ
0.315;-1281.2
(6Q)(9K)
0.387;-970.0
6Q(9K)
0.355;-1105.0
T(6TJ)
0.371;-1031.9
TK(6T)
0.343;-990.6
(6T)(JQ)
0.342;-990.6
QQ(6T)
0.314;-970.0
6T(TJ)
0.419;-1031.9
(6J)(TJ)
0.401;-876.3
6J(TJ)
0.338;-1011.2
TJ(6Q)
0.407;-1125.6
(6Q)(TQ)
0.346;-835.0
6K(TQ)
0.388;-1084.4
6K(TK)
0.350;-928.7
JK(6J)
0.303;-949.4
K(6JK)
0.401;-908.1
6JJK
0.372;-1084.4
6(JQK)
0.365;-1063.8
JK(6K)
0.330;-908.1
KK(6Q)
0.323;-887.5
6QKK
0.390;-1022.5
77(7T)
0.382;-1020.6
(78)(78)
0.441;-906.2
7(78J)
0.365;-1114.4
7K(78)
0.431;-1073.1
78(7J)
0.381;-1114.4
778K
0.371;-1208.1
7J(79)
0.368;-1093.8
79(7T)
0.381;-1114.4
779Q
0.332;-1208.1
7J(7T)
0.351;-1073.1
7T(7J)
0.360;-1073.1
77TK
0.312;-1166.9
7K(7J)
0.385;-1011.2
(7Q)(7Q)
0.420;-741.2
77QK
0.345;-1125.6
8(78T)
0.353;-1114.4
8Q(78)
0.360;-1073.1
J(789)
0.336;-1208.1
9T(78)
0.390;-1228.8
(78)(9K)
0.308;-1031.9
K(78T)
0.331;-1146.2
T(78K)
0.304;-1146.2
JJ(78)
0.326;-1031.9
(78QK)
0.320;-1105.0
7888
0.331;-1155.6
78(8J)
0.312;-1093.8
(79)(89)
0.326;-979.4
8(79Q)
0.352;-1187.5
7(89T)
0.345;-1228.8
(89)(7K)
0.331;-1031.9
89(7J)
0.328;-1208.1
89(7K)
0.298;-1166.9
8J(7T)
0.378;-1187.5
(8T)(7J)
0.306;-1052.5
7K(8T)
0.303;-1146.2
78(TQ)
0.341;-1166.9
8(7JQ)
0.329;-1146.2
7(8JQ)
0.285;-1146.2
78(JQ)
0.319;-1146.2
8(7QK)
0.361;-1105.0
8Q(7K)
0.283;-1105.0
99(79)
0.373;-958.8
(79)(9Q)
0.329;-896.9
(79TQ)
0.360;-1146.2
T(79Q)
0.344;-1146.2
Q(79J)
0.300;-1125.6
(79)(JK)
0.345;-970.0
QK(79)
0.356;-1084.4
79(9J)
0.334;-1052.5
(7T)(9T)
0.363;-917.5
9(7TK)
0.398;-1125.6
7(9TQ)
0.397;-1146.2
79(TJ)
0.356;-1166.9
79(TK)
0.365;-1125.6
(7J)(9K)
0.371;-970.0
7K(9J)
0.349;-1105.0
79(JK)
0.374;-1105.0
(9Q)(7K)
0.364;-949.4
(7K)(9K)
0.356;-793.8
T(7TQ)
0.371;-990.6
Q(7TJ)
0.319;-1105.0
(7T)(JK)
0.375;-949.4
QK(7T)
0.369;-1063.8
7T(TQ)
0.371;-990.6
(7J)(TQ)
0.363;-970.0
7Q(TJ)
0.297;-1105.0
7TJQ
0.370;-1240.0
(7Q)(TK)
0.311;-928.7
7Q(TK)
0.353;-1063.8
J(7JQ)
0.392;-949.4
K(7JQ)
0.385;-1043.1
JJ(7Q)
0.414;-949.4
J(7QK)
0.383;-1043.1
JQ(7K)
0.365;-1043.1
QQ(7Q)
0.331;-773.1
7Q(QK)
0.326;-887.5
8888
0.316;-1000.0
888Q
0.401;-1052.5
8(89J)
0.332;-1052.5
8K(89)
0.316;-1011.2
89(8Q)
0.387;-1031.9
8(8TJ)
0.305;-1031.9
8K(8T)
0.342;-990.6
8T(8K)
0.441;-990.6
8(8JK)
0.430;-970.0
88(JK)
0.389;-970.0
8Q(8K)
0.365;-949.4
(89)(9T)
0.365;-917.5
9(89K)
0.303;-990.6
(89TK)
0.313;-1105.0
TQ(89)
0.348;-1125.6
K(89J)
0.306;-1084.4
Q(89Q)
0.319;-949.4
KK(89)
0.357;-908.1
99(8Q)
0.341;-1011.2
9(8TJ)
0.383;-1146.2
9K(8T)
0.299;-1105.0
(9T)(8K)
0.381;-970.0
9T(8Q)
0.419;-1125.6
(8J)(9J)
0.391;-855.6
8J(9J)
0.391;-990.6
9J(8Q)
0.329;-1105.0
(8Q)(9Q)
0.385;-814.4
8K(9Q)
0.388;-1063.8
8K(9K)
0.356;-908.1
TQ(8T)
0.421;-970.0
K(8TJ)
0.367;-1063.8
Q(8TQ)
0.373;-928.7
KK(8T)
0.330;-887.5
