AAAA
0.399;-6120.0
5AAA
0.256;-13815.0
9AAA
0.382;-11835.0
KAAA
0.389;-9855.0
4A(2A)
0.296;-20250.0
(2A)(7A)
0.340;-15525.0
A(2TA)
0.227;-17280.0
QA(2A)
0.318;-16290.0
2A(4A)
0.262;-20250.0
26AA
0.280;-22500.0
AA(29)
0.234;-17775.0
2A(QA)
0.301;-16290.0
A(34A)
0.264;-19755.0
6A(3A)
0.305;-18765.0
(3A)(9A)
0.340;-14040.0
A(3QA)
0.360;-15795.0
AA(34)
0.321;-19755.0
3A(7A)
0.293;-18270.0
39AA
0.237;-20520.0
AA(3Q)
0.279;-15795.0
(4A)(5A)
0.328;-15525.0
A(48A)
0.302;-17280.0
TA(4A)
0.322;-16290.0
(4A)(KA)
0.379;-11565.0
46AA
0.256;-21510.0
AA(49)
0.296;-16785.0
4A(QA)
0.328;-15300.0
A(56A)
0.274;-17775.0
8A(5A)
0.282;-16785.0
(5A)(JA)
0.280;-12060.0
55AA
0.251;-18270.0
AA(58)
0.356;-16785.0
5A(JA)
0.339;-15300.0
5KAA
0.224;-17550.0
8A(6A)
0.321;-16290.0
(6A)(JA)
0.310;-11565.0
66AA
0.265;-17280.0
AA(69)
0.271;-15795.0
6A(QA)
0.345;-14310.0
A(78A)
0.384;-15795.0
TA(7A)
0.322;-14805.0
(7A)(KA)
0.421;-10080.0
79AA
0.308;-18540.0
AA(7Q)
0.287;-13815.0
(8A)(9A)
0.289;-11565.0
A(8QA)
0.334;-13320.0
AA(89)
0.338;-14805.0
8A(QA)
0.330;-13320.0
A(9TA)
0.289;-13815.0
QA(9A)
0.322;-12825.0
9A(JA)
0.377;-13320.0
9KAA
0.324;-15570.0
QA(TA)
0.403;-12330.0
TA(QA)
0.367;-12330.0
A(JQA)
0.329;-11835.0
AA(JQ)
0.287;-11835.0
(QA)(KA)
0.346;-7605.0
KKAA
0.358;-10350.0
2(25A)
0.225;-25695.0
27(2A)
0.236;-24705.0
(2T)(2A)
0.230;-19980.0
2(2KA)
0.284;-21735.0
(236A)
0.209;-27945.0
(23TA)
0.191;-25965.0
33(2A)
0.262;-26190.0
(36)(2A)
0.285;-24705.0
3(29A)
0.221;-26460.0
3J(2A)
0.191;-25470.0
(245A)
0.213;-27945.0
(249A)
0.219;-25965.0
(24KA)
0.214;-23985.0
46(2A)
0.216;-27450.0
(49)(2A)
0.211;-22725.0
4(2QA)
0.200;-24480.0
6(25A)
0.179;-26955.0
T(25A)
0.205;-24975.0
5(26A)
0.272;-26955.0
58(2A)
0.179;-25965.0
(5J)(2A)
0.295;-21240.0
6(26A)
0.290;-23220.0
T(26A)
0.246;-24480.0
6(27A)
0.233;-25965.0
69(2A)
0.242;-24975.0
(6Q)(2A)
0.258;-20250.0
(279A)
0.233;-24480.0
(27KA)
0.207;-22500.0
79(2A)
0.214;-24480.0
(7Q)(2A)
0.288;-19755.0
(28TA)
0.195;-23490.0
88(2A)
0.259;-21240.0
(8J)(2A)
0.259;-19755.0
9(29A)
0.215;-20250.0
K(29A)
0.265;-21510.0
9(2QA)
0.280;-22005.0
J(2TA)
0.306;-22005.0
TJ(2A)
0.260;-22005.0
(2JQA)
0.261;-21015.0
J(2KA)
0.288;-20520.0
(QK)(2A)
0.264;-16785.0
22(4A)
0.205;-26190.0
226A
0.203;-28440.0
2A(29)
0.295;-23715.0
22(QA)
0.283;-22230.0
2(34A)
0.203;-28935.0
26(3A)
0.257;-27945.0
(29)(3A)
0.223;-23220.0
2(3QA)
0.230;-24975.0
A(234)
0.225;-28935.0
(23)(7A)
0.185;-24210.0
9A(23)
0.219;-26460.0
A(23Q)
0.240;-24975.0
2A(34)
0.195;-28935.0
2A(36)
0.224;-27945.0
2A(38)
0.167;-26955.0
2A(3T)
0.229;-25965.0
2A(3Q)
0.221;-24975.0
2(45A)
0.218;-27945.0
27(4A)
0.235;-26955.0
(2T)(4A)
0.262;-22230.0
2(4KA)
0.274;-23985.0
A(246)
0.212;-27450.0
(24)(9A)
0.249;-22725.0
JA(24)
0.206;-24975.0
24(5A)
0.221;-27945.0
24(7A)
0.197;-26955.0
24(9A)
0.200;-25965.0
24(JA)
0.241;-24975.0
24(KA)
0.287;-23985.0
26(5A)
0.204;-26955.0
(29)(5A)
0.224;-22230.0
2(5QA)
0.218;-23985.0
A(256)
0.243;-26955.0
(25)(9A)
0.265;-22230.0
JA(25)
0.223;-24480.0
25(6A)
0.180;-26955.0
25(8A)
0.249;-25965.0
25(TA)
0.285;-24975.0
25(QA)
0.250;-23985.0
(26)(6A)
0.300;-19980.0
2(69A)
0.272;-24975.0
2J(6A)
0.280;-23985.0
(26)(7A)
0.209;-22725.0
9A(26)
0.220;-24975.0
A(26Q)
0.243;-23490.0
2A(67)
0.250;-25965.0
2A(69)
0.201;-24975.0
2A(6J)
0.223;-23985.0
2A(6K)
0.287;-22995.0
(29)(7A)
0.247;-21240.0
2(7QA)
0.266;-22995.0
A(278)
0.257;-24975.0
(27)(JA)
0.288;-20250.0
KA(27)
0.263;-22500.0
2A(79)
0.240;-24480.0
2A(7J)
0.312;-23490.0
2A(7K)
0.295;-22500.0
(2T)(8A)
0.254;-20250.0
2(8KA)
0.212;-22005.0
A(28T)
0.265;-23490.0
(28)(KA)
0.293;-18765.0
28(TA)
0.272;-23490.0
28(QA)
0.252;-22500.0
(29)(9A)
0.289;-17010.0
2(9QA)
0.280;-22005.0
A(29T)
0.239;-22995.0
(29)(KA)
0.287;-18270.0
29(JA)
0.289;-22500.0
29(KA)
0.266;-21510.0
2J(TA)
0.309;-22005.0
(2T)(JA)
0.280;-18765.0
KA(2T)
0.301;-21015.0
2A(TQ)
0.271;-21510.0
2(JQA)
0.220;-21015.0
A(2JQ)
0.311;-21015.0
2A(JQ)
0.244;-21015.0
2(QKA)
0.321;-20025.0
2Q(KA)
0.242;-20025.0
33(3A)
0.267;-22455.0
(36)(3A)
0.257;-20970.0
3(39A)
0.220;-22725.0
3J(3A)
0.261;-21735.0
(345A)
0.216;-27450.0
(349A)
0.199;-25470.0
(34KA)
0.241;-23490.0
46(3A)
0.204;-26955.0
(49)(3A)
0.260;-22230.0
4(3QA)
0.214;-23985.0
6(35A)
0.212;-26460.0
T(35A)
0.214;-24480.0
5(36A)
0.196;-26460.0
58(3A)
0.185;-25470.0
(5J)(3A)
0.291;-20745.0
6(36A)
0.248;-22725.0
T(36A)
0.287;-23985.0
6(37A)
0.203;-25470.0
69(3A)
0.234;-24480.0
(6Q)(3A)
0.252;-19755.0
(379A)
0.224;-23985.0
(37KA)
0.203;-22005.0
79(3A)
0.250;-23985.0
(7Q)(3A)
0.257;-19260.0
(38TA)
0.223;-22995.0
88(3A)
0.289;-20745.0
(8J)(3A)
0.265;-19260.0
9(39A)
0.248;-19755.0
K(39A)
0.217;-21015.0
9(3QA)
0.284;-21510.0
J(3TA)
0.275;-21510.0
TJ(3A)
0.208;-21510.0
(3JQA)
0.266;-20520.0
J(3KA)
0.206;-20025.0
(QK)(3A)
0.260;-16290.0
33(5A)
0.182;-24705.0
337A
0.225;-26955.0
3A(3T)
0.248;-22230.0
33(KA)
0.209;-20745.0
3(46A)
0.218;-26955.0
38(4A)
0.245;-25965.0
(3J)(4A)
0.308;-21240.0
4A(34)
0.261;-24705.0
A(347)
0.278;-26460.0
(34)(TA)
0.266;-21735.0
QA(34)
0.250;-23985.0
345A
0.193;-30690.0
347A
0.194;-29700.0
349A
0.187;-28710.0
34JA
0.250;-27720.0
34KA
0.219;-26730.0
37(5A)
0.199;-25965.0
(3T)(5A)
0.228;-21240.0
3(5KA)
0.271;-22995.0
A(357)
0.215;-25965.0
(35)(TA)
0.283;-21240.0
QA(35)
0.293;-23490.0
356A
0.209;-29700.0
358A
0.186;-28710.0
35TA
0.201;-27720.0
35QA
0.245;-26730.0
(37)(6A)
0.306;-22230.0
3(6TA)
0.220;-23985.0
3Q(6A)
0.196;-22995.0
(36)(8A)
0.234;-21735.0
TA(36)
0.201;-23985.0
A(36K)
0.224;-22500.0
6A(38)
0.216;-24975.0
6A(3T)
0.229;-23985.0
6A(3Q)
0.244;-22995.0
37(7A)
0.200;-21735.0
(3T)(7A)
0.324;-20250.0
3(7KA)
0.272;-22005.0
A(379)
0.241;-23985.0
(37)(QA)
0.335;-19260.0
7A(38)
0.291;-24480.0
7A(3T)
0.252;-23490.0
7A(3Q)
0.239;-22500.0
38(8A)
0.287;-20745.0
(3J)(8A)
0.287;-19260.0
8A(38)
0.302;-20745.0
A(38J)
0.216;-22500.0
388A
0.233;-23985.0
38TA
0.218;-26235.0
38QA
0.235;-25245.0
(3T)(9A)
0.280;-19260.0
3(9KA)
0.255;-21015.0
A(39J)
0.248;-22005.0
399A
0.230;-22995.0
39JA
0.252;-25245.0
39KA
0.240;-24255.0
3Q(TA)
0.275;-21015.0
(3T)(QA)
0.311;-17775.0
TA(3J)
0.261;-21510.0
TA(3K)
0.265;-20520.0
3(JKA)
0.258;-20025.0
A(3JK)
0.287;-20025.0
JA(3K)
0.279;-20025.0
QA(3Q)
0.366;-16785.0
3QKA
0.246;-22770.0
45(4A)
0.212;-23715.0
(48)(4A)
0.322;-18990.0
4(4JA)
0.287;-20745.0
4K(4A)
0.305;-19755.0
(459A)
0.244;-24480.0
(45KA)
0.256;-22500.0
57(4A)
0.259;-25470.0
(5T)(4A)
0.253;-20745.0
5(4KA)
0.257;-22500.0
(469A)
0.259;-23985.0
(46KA)
0.290;-22005.0
68(4A)
0.253;-24480.0
(6J)(4A)
0.266;-19755.0
7(47A)
0.245;-21240.0
J(47A)
0.229;-22500.0
78(4A)
0.216;-23985.0
(7J)(4A)
0.294;-19260.0
8(48A)
0.290;-20250.0
Q(48A)
0.279;-21510.0
(8T)(4A)
0.277;-19260.0
8(4KA)
0.263;-21015.0
(49QA)
0.266;-21015.0
9(4JA)
0.218;-21510.0
9K(4A)
0.248;-20520.0
TT(4A)
0.294;-18270.0
(TK)(4A)
0.235;-16785.0
J(4QA)
0.259;-20025.0
K(4QA)
0.283;-19035.0
44(5A)
0.181;-23715.0
447A
0.225;-25965.0
4A(4T)
0.224;-21240.0
44(KA)
0.290;-19755.0
4(57A)
0.260;-25470.0
49(5A)
0.180;-24480.0
(4Q)(5A)
0.316;-19755.0
6A(45)
0.254;-25965.0
A(459)
0.235;-24480.0
(45)(QA)
0.268;-19755.0
5A(46)
0.218;-25965.0
5A(48)
0.240;-24975.0
5A(4T)
0.195;-23985.0
5A(4Q)
0.253;-22995.0
46(6A)
0.273;-22230.0
(49)(6A)
0.306;-20745.0
4(6QA)
0.238;-22500.0
A(467)
0.227;-24975.0
(46)(TA)
0.302;-20250.0
QA(46)
0.269;-22500.0
467A
0.190;-28215.0
469A
0.211;-27225.0
46JA
0.237;-26235.0
46KA
0.173;-25245.0
49(7A)
0.300;-23490.0
(4Q)(7A)
0.279;-18765.0
8A(47)
0.202;-23985.0
A(47J)
0.300;-22500.0
477A
0.273;-24480.0
479A
0.182;-26730.0
47JA
0.228;-25740.0
47KA
0.279;-24750.0
4T(8A)
0.232;-22500.0
(4K)(8A)
0.301;-17775.0
TA(48)
0.248;-22500.0
A(48K)
0.298;-21015.0
8A(4T)
0.205;-22500.0
8A(4Q)
0.245;-21510.0
49(9A)
0.257;-19260.0
(4Q)(9A)
0.325;-17775.0
TA(49)
0.267;-22005.0
A(49K)
0.233;-20520.0
9A(4J)
0.254;-21510.0
9A(4K)
0.323;-20520.0
4(TQA)
0.235;-20520.0
A(4TJ)
0.250;-21015.0
4TTA
0.299;-21510.0
4TQA
0.244;-23760.0
(4Q)(JA)
0.285;-16785.0
QA(4J)
0.299;-20025.0
4JQA
0.270;-23265.0
(4K)(QA)
0.352;-15795.0
QA(4K)
0.230;-19035.0
5(56A)
0.269;-22230.0
58(5A)
0.287;-21240.0
(5J)(5A)
0.277;-16515.0
6(56A)
0.278;-21735.0
T(56A)
0.285;-22995.0
6(57A)
0.212;-24480.0
69(5A)
0.206;-23490.0
(6Q)(5A)
0.283;-18765.0
(579A)
0.261;-22995.0
(57KA)
0.215;-21015.0
79(5A)
0.304;-22995.0
(7Q)(5A)
0.251;-18270.0
(58TA)
0.278;-22005.0
88(5A)
0.299;-19755.0
(8J)(5A)
0.305;-18270.0
9(59A)
0.259;-18765.0
K(59A)
0.290;-20025.0
9(5QA)
0.274;-20520.0
J(5TA)
0.329;-20520.0
TJ(5A)
0.273;-20520.0
(5JQA)
0.262;-19530.0
J(5KA)
0.270;-19035.0
(QK)(5A)
0.324;-15300.0
55(7A)
0.254;-21735.0
559A
0.196;-23985.0
5A(5Q)
0.308;-19260.0
(57)(6A)
0.274;-21240.0
5(6TA)
0.227;-22995.0
5Q(6A)
0.261;-22005.0
(56)(8A)
0.216;-20745.0
TA(56)
0.249;-22995.0
A(56K)
0.296;-21510.0
6A(58)
0.250;-23985.0
6A(5T)
0.201;-22995.0
6A(5Q)
0.293;-22005.0
57(7A)
0.203;-20745.0
(5T)(7A)
0.306;-19260.0
5(7KA)
0.260;-21015.0
A(579)
0.252;-22995.0
(57)(QA)
0.251;-18270.0
7A(58)
0.248;-23490.0
7A(5T)
0.208;-22500.0
7A(5Q)
0.220;-21510.0
58(8A)
0.254;-19755.0
(5J)(8A)
0.309;-18270.0
8A(58)
0.325;-19755.0
A(58J)
0.272;-21510.0
588A
0.256;-22995.0
58TA
0.214;-25245.0
58QA
0.223;-24255.0
(5T)(9A)
0.268;-18270.0
5(9KA)
0.288;-20025.0
A(59J)
0.215;-21015.0
599A
0.308;-22005.0
59JA
0.280;-24255.0
59KA
0.270;-23265.0
5Q(TA)
0.241;-20025.0
(5T)(QA)
0.276;-16785.0
TA(5J)
0.286;-20520.0
TA(5K)
0.222;-19530.0
5(JKA)
0.332;-19035.0
A(5JK)
0.270;-19035.0
JA(5K)
0.296;-19035.0
QA(5Q)
0.284;-15795.0
5QKA
0.224;-21780.0
67(6A)
0.297;-20745.0
(6T)(6A)
0.273;-16020.0
6(6KA)
0.310;-17775.0
(67TA)
0.280;-22005.0
77(6A)
0.271;-20250.0
(7T)(6A)
0.291;-18765.0
7(6KA)
0.271;-20520.0
(68JA)
0.314;-21015.0
(89)(6A)
0.223;-18765.0
8(6QA)
0.345;-20520.0
T(69A)
0.257;-21015.0
9(6TA)
0.274;-21015.0
9Q(6A)
0.296;-20025.0
Q(6TA)
0.232;-19530.0
(TQ)(6A)
0.362;-16290.0
(6JKA)
0.254;-18540.0
JK(6A)
0.250;-18540.0
K(6KA)
0.344;-14310.0
668A
0.236;-23490.0
6A(6J)
0.275;-18765.0
(67)(7A)
0.265;-17010.0
6(7TA)
0.276;-22005.0
6Q(7A)
0.278;-21015.0
(67)(9A)
0.233;-19260.0
JA(67)
0.244;-21510.0
67(8A)
0.216;-22995.0
67(TA)
0.254;-22005.0
67(QA)
0.299;-21015.0
(68)(8A)
0.287;-16020.0
6(8JA)
0.299;-21015.0
6K(8A)
0.298;-20025.0
(68)(JA)
0.310;-17775.0
KA(68)
0.248;-20025.0
6A(8T)
0.287;-21510.0
6A(8Q)
0.226;-20520.0
6(9TA)
0.288;-21015.0
6Q(9A)
0.278;-20025.0
(69)(JA)
0.341;-17280.0
KA(69)
0.245;-19530.0
6A(9J)
0.261;-20520.0
6A(9K)
0.295;-19530.0
(6Q)(TA)
0.266;-16290.0
JA(6T)
0.301;-20025.0
6T(JA)
0.250;-20025.0
6T(KA)
0.275;-19035.0
6Q(JA)
0.255;-19035.0
(6J)(KA)
0.330;-15300.0
6J(KA)
0.230;-18540.0
6K(QA)
0.245;-18045.0
6A(QK)
0.252;-18045.0
(78)(7A)
0.312;-16020.0
7(7JA)
0.254;-17775.0
7K(7A)
0.365;-16785.0
(78QA)
0.300;-20025.0
8(7TA)
0.298;-21015.0
8Q(7A)
0.239;-20025.0
J(79A)
0.255;-20025.0
9T(7A)
0.299;-20520.0
(9K)(7A)
0.318;-15795.0
K(7TA)
0.288;-18540.0
T(7KA)
0.279;-18540.0
JJ(7A)
0.294;-15795.0
(7QKA)
0.251;-17550.0
777A
0.341;-19755.0
7A(7T)
0.283;-18270.0
77(KA)
0.340;-16785.0
7(8TA)
0.208;-21015.0
7Q(8A)
0.290;-20025.0
(78)(TA)
0.276;-17775.0
QA(78)
0.312;-20025.0
789A
0.225;-24750.0
78JA
0.196;-23760.0
78KA
0.205;-22770.0
7J(9A)
0.261;-20025.0
(79)(TA)
0.279;-17280.0
QA(79)
0.307;-19530.0
79TA
0.206;-23760.0
79QA
0.254;-22770.0
(7J)(TA)
0.263;-16290.0
TA(7T)
0.319;-16785.0
A(7TK)
0.247;-18540.0
TA(7Q)
0.282;-19035.0
7J(JA)
0.275;-15795.0
(7J)(QA)
0.338;-15300.0
JA(7Q)
0.259;-18540.0
7Q(QA)
0.374;-14805.0
7QQA
0.250;-18045.0
7KKA
0.267;-17055.0
8(8JA)
0.351;-16785.0
8K(8A)
0.247;-15795.0
(89KA)
0.274;-18540.0
9J(8A)
0.286;-19530.0
(8TJA)
0.238;-19035.0
(TJ)(8A)
0.324;-15795.0
J(8JA)
0.352;-15300.0
JQ(8A)
0.338;-18045.0
Q(8KA)
0.238;-17055.0
889A
0.257;-21015.0
8A(8Q)
0.291;-16290.0
(8T)(9A)
0.324;-16785.0
8(9KA)
0.221;-18540.0
A(89J)
0.237;-19530.0
899A
0.204;-20520.0
89JA
0.215;-22770.0
89KA
0.236;-21780.0
8Q(TA)
0.328;-18540.0
(8T)(QA)
0.296;-15300.0
TA(8J)
0.259;-19035.0
TA(8K)
0.243;-18045.0
8(JKA)
0.330;-17550.0
A(8JK)
0.299;-17550.0
JA(8K)
0.269;-17550.0
QA(8Q)
0.320;-14310.0
8QKA
0.318;-20295.0
9T(9A)
0.304;-16290.0
(9K)(9A)
0.309;-11565.0
K(9TA)
0.302;-17550.0
T(9KA)
0.295;-17550.0
JJ(9A)
0.295;-14805.0
(9QKA)
0.347;-16560.0
999A
0.371;-16785.0
9A(9Q)
0.292;-15300.0
(9J)(TA)
0.290;-15300.0
TA(9T)
0.281;-15795.0
A(9TK)
0.360;-17550.0
TA(9Q)
0.337;-18045.0
9J(JA)
0.335;-14805.0
(9J)(QA)
0.317;-14310.0
JA(9Q)
0.293;-17550.0
9Q(QA)
0.326;-13815.0
9QQA
0.328;-17055.0
9KKA
0.302;-16065.0
T(TKA)
0.291;-13815.0
JJ(TA)
0.353;-14310.0
(TQKA)
0.323;-16065.0
TTTA
0.296;-15300.0
TA(TK)
0.295;-13815.0
(TK)(JA)
0.347;-13320.0
KA(TJ)
0.345;-16560.0
TA(JK)
0.278;-16560.0
(TQ)(KA)
0.362;-12825.0
(TK)(KA)
0.425;-9090.0
J(JKA)
0.329;-12825.0
(QK)(JA)
0.307;-12330.0
JJ(KA)
0.297;-12825.0
QA(JQ)
0.364;-12825.0
JQKA
0.249;-18810.0
QK(QA)
0.373;-11835.0
QK(KA)
0.304;-11340.0
22(24)
0.173;-28890.0
22(28)
0.234;-26910.0
22(2Q)
0.213;-24930.0
24(23)
0.165;-31635.0
(23)(27)
0.178;-26910.0
2(23T)
0.209;-28665.0
2Q(23)
0.236;-27675.0
23(25)
0.183;-31140.0
2237
0.184;-33390.0
22(3T)
0.179;-28665.0
23(2K)
0.253;-27180.0
2(246)
0.188;-30150.0
28(24)
0.192;-29160.0
(24)(2J)
0.240;-24435.0
2244
0.214;-31140.0
22(47)
0.195;-29655.0
24(2T)
0.197;-28170.0
224Q
0.189;-30420.0
26(25)
0.168;-29655.0
(25)(29)
0.255;-24930.0
2(25Q)
0.172;-26685.0
22(56)
0.202;-29655.0
25(29)
0.172;-28170.0
225J
0.200;-30420.0
26(26)
0.263;-25920.0
(26)(29)
0.232;-24435.0
2(26Q)
0.201;-26190.0
22(67)
0.183;-28665.0
26(2T)
0.205;-27180.0
226Q
0.207;-29430.0
28(27)
0.246;-27675.0
(27)(2J)
0.267;-22950.0
2277
0.256;-28170.0
22(7T)
0.170;-26685.0
27(2K)
0.184;-25200.0
2(28T)
0.229;-26190.0
2Q(28)
0.209;-25200.0
28(2T)
0.223;-26190.0
228Q
0.262;-28440.0
2T(29)
0.260;-25695.0
(29)(2K)
0.287;-20970.0
229J
0.221;-28440.0
2T(2T)
0.273;-21960.0
(2T)(2K)
0.248;-20475.0
22TQ
0.209;-27450.0
2Q(2J)
0.257;-23715.0
2J(2K)
0.252;-23220.0
22QQ
0.205;-23220.0
3(234)
0.153;-31140.0
36(23)
0.202;-30150.0
(23)(39)
0.258;-25425.0
3(23Q)
0.182;-27180.0
5(234)
0.205;-33390.0
9(234)
0.150;-31410.0
K(234)
0.207;-29430.0
4(237)
0.207;-32400.0
49(23)
0.173;-31410.0
(23)(4Q)
0.210;-26685.0
(2357)
0.166;-31905.0
(235J)
0.199;-29925.0
(23)(56)
0.172;-29160.0
5(239)
0.176;-30915.0
5J(23)
0.224;-29925.0
(2367)
0.201;-31410.0
(236J)
0.181;-29430.0
(23)(67)
0.262;-28170.0
6(23T)
0.198;-29925.0
6Q(23)
0.168;-28935.0
9(237)
0.181;-29925.0
K(237)
0.229;-27945.0
7(23T)
0.208;-29430.0
7Q(23)
0.175;-28440.0
T(238)
0.243;-28935.0
8(239)
0.186;-29430.0
8J(23)
0.201;-28440.0
(239T)
0.232;-28440.0
99(23)
0.202;-25695.0
(23)(9Q)
0.281;-24210.0
(23TQ)
0.254;-26955.0
T(23Q)
0.179;-26955.0
Q(23J)
0.248;-26460.0
(23)(JK)
0.186;-22725.0
QK(23)
0.230;-25470.0
23(35)
0.222;-30645.0
33(28)
0.203;-29160.0
233T
0.195;-31410.0
23(3K)
0.194;-26685.0
(24)(36)
0.219;-29655.0
3(249)
0.190;-31410.0
3J(24)
0.174;-30420.0
(34)(25)
0.235;-30150.0
27(34)
0.177;-32400.0
2(34T)
0.195;-30915.0
(34)(2K)
0.217;-26190.0
34(26)
0.220;-32895.0
34(28)
0.169;-31905.0
34(2T)
0.207;-30915.0
34(2Q)
0.191;-29925.0
(25)(35)
0.195;-26415.0
3(258)
0.181;-31410.0
3T(25)
0.158;-30420.0
(25)(3K)
0.232;-25695.0
27(35)
0.152;-31905.0
2(35T)
0.215;-30420.0
(35)(2K)
0.223;-25695.0
35(27)
0.236;-31905.0
35(29)
0.223;-30915.0
35(2J)
0.208;-29925.0
35(2K)
0.203;-28935.0
37(26)
0.171;-31410.0
(26)(3T)
0.192;-26685.0
3(26K)
0.220;-28440.0
2(368)
0.177;-30915.0
(36)(2J)
0.280;-26190.0
2K(36)
0.219;-28440.0
23(68)
0.247;-30915.0
23(6T)
0.160;-29925.0
23(6Q)
0.220;-28935.0
3(278)
0.169;-30420.0
3T(27)
0.181;-29430.0
(27)(3K)
0.231;-24705.0
29(37)
0.174;-29925.0
2(37Q)
0.261;-28440.0
23(78)
0.216;-30420.0
23(7T)
0.161;-29430.0
23(7Q)
0.169;-28440.0
3(289)
0.191;-29430.0
3J(28)
0.196;-28440.0
(38)(29)
0.201;-26190.0
2J(38)
0.214;-28440.0
38(29)
0.172;-29430.0
38(2J)
0.207;-28440.0
38(2K)
0.188;-27450.0
3T(29)
0.156;-28440.0
(29)(3K)
0.204;-23715.0
2J(39)
0.194;-27945.0
39(2T)
0.204;-28440.0
39(2Q)
0.230;-27450.0
(2T)(3T)
0.237;-21465.0
3(2TK)
0.221;-26460.0
2(3TQ)
0.202;-26955.0
23(TJ)
0.238;-27450.0
23(TK)
0.224;-26460.0
(2J)(3K)
0.241;-22725.0
2K(3J)
0.219;-25965.0
23(JK)
0.240;-25965.0
(3Q)(2K)
0.203;-22230.0
(2K)(3K)
0.273;-18495.0
4(246)
0.223;-29160.0
48(24)
0.268;-28170.0
(24)(4J)
0.251;-23445.0
5(245)
0.227;-29160.0
9(245)
0.264;-30420.0
K(245)
0.215;-28440.0
5(248)
0.229;-30915.0
5T(24)
0.233;-29925.0
(24)(5K)
0.219;-25200.0
9(246)
0.223;-29925.0
K(246)
0.171;-27945.0
6(249)
0.211;-29925.0
6J(24)
0.216;-28935.0
(2478)
0.188;-29925.0
(247Q)
0.186;-27945.0
7(249)
0.232;-29430.0
7J(24)
0.212;-28440.0
(2489)
0.199;-28935.0
(248K)
0.198;-26955.0
8T(24)
0.224;-28440.0
(24)(8K)
0.272;-23715.0
Q(249)
0.191;-26955.0
(24)(9J)
0.257;-24210.0
T(24T)
0.266;-24210.0
T(24J)
0.195;-26955.0
TK(24)
0.217;-25965.0
(24)(JQ)
0.287;-22725.0
QQ(24)
0.299;-22230.0
24(45)
0.168;-29655.0
44(28)
0.207;-28170.0
244T
0.163;-30420.0
24(4K)
0.243;-25695.0
(25)(47)
0.232;-28170.0
4(25T)
0.184;-29925.0
4Q(25)
0.161;-28935.0
(45)(27)
0.209;-28170.0
29(45)
0.180;-30420.0
2(45Q)
0.187;-28935.0
24(56)
0.184;-31905.0
24(58)
0.165;-30915.0
24(5T)
0.216;-29925.0
24(5Q)
0.175;-28935.0
4(267)
0.219;-30915.0
49(26)
0.199;-29925.0
(26)(4Q)
0.189;-25200.0
27(46)
0.215;-30915.0
2(46T)
0.202;-29430.0
(46)(2K)
0.245;-24705.0
46(28)
0.252;-30420.0
46(2T)
0.203;-29430.0
46(2Q)
0.207;-28440.0
(27)(47)
0.229;-23940.0
4(27T)
0.183;-28935.0
4Q(27)
0.225;-27945.0
(47)(29)
0.234;-26190.0
2J(47)
0.219;-28440.0
47(28)
0.204;-29925.0
47(2T)
0.220;-28935.0
47(2Q)
0.223;-27945.0
(28)(48)
0.256;-22950.0
4(28J)
0.281;-27945.0
4K(28)
0.227;-26955.0
(48)(2J)
0.225;-24705.0
2K(48)
0.224;-26955.0
24(8T)
0.235;-28440.0
24(8Q)
0.262;-27450.0
4(29T)
0.188;-27945.0
4Q(29)
0.247;-26955.0
(49)(2J)
0.287;-24210.0
2K(49)
0.184;-26460.0
24(9J)
0.179;-27450.0
24(9K)
0.208;-26460.0
(2T)(4Q)
0.294;-23220.0
2J(4T)
0.167;-26955.0
4T(2J)
0.218;-26955.0
4T(2K)
0.245;-25965.0
4Q(2J)
0.218;-25965.0
(4J)(2K)
0.246;-22230.0
4J(2K)
0.238;-25470.0
4K(2Q)
0.262;-24975.0
24(QK)
0.209;-24975.0
(25)(56)
0.300;-24930.0
5(259)
0.229;-26685.0
5J(25)
0.229;-25695.0
(2567)
0.179;-30420.0
(256J)
0.198;-28440.0
(25)(67)
0.205;-27180.0
6(25T)
0.212;-28935.0
6Q(25)
0.194;-27945.0
9(257)
0.214;-28935.0
K(257)
0.228;-26955.0
7(25T)
0.181;-28440.0
7Q(25)
0.201;-27450.0
T(258)
0.233;-27945.0
8(259)
0.240;-28440.0
8J(25)
0.195;-27450.0
(259T)
0.256;-27450.0
99(25)
0.193;-24705.0
(25)(9Q)
0.222;-23220.0
(25TQ)
0.260;-25965.0
T(25Q)
0.242;-25965.0
Q(25J)
0.204;-25470.0
(25)(JK)
0.252;-21735.0
QK(25)
0.253;-24480.0
25(57)
0.216;-27675.0
55(2T)
0.222;-26190.0
255Q
0.243;-28440.0
57(26)
0.170;-30420.0
(26)(5T)
0.228;-25695.0
5(26K)
0.246;-27450.0
2(568)
0.157;-29925.0
(56)(2J)
0.231;-25200.0
2K(56)
0.254;-27450.0
25(68)
0.227;-29925.0
25(6T)
0.239;-28935.0
25(6Q)
0.162;-27945.0
5(278)
0.204;-29430.0
5T(27)
0.233;-28440.0
(27)(5K)
0.265;-23715.0
29(57)
0.218;-28935.0
2(57Q)
0.208;-27450.0
25(78)
0.197;-29430.0
25(7T)
0.211;-28440.0
25(7Q)
0.267;-27450.0
5(289)
0.209;-28440.0
5J(28)
0.220;-27450.0
(58)(29)
0.270;-25200.0
2J(58)
0.233;-27450.0
58(29)
0.191;-28440.0
58(2J)
0.188;-27450.0
58(2K)
0.223;-26460.0
5T(29)
0.222;-27450.0
(29)(5K)
0.235;-22725.0
2J(59)
0.214;-26955.0
59(2T)
0.201;-27450.0
59(2Q)
0.239;-26460.0
(2T)(5T)
0.218;-20475.0
5(2TK)
0.268;-25470.0
2(5TQ)
0.212;-25965.0
25(TJ)
0.292;-26460.0
25(TK)
0.262;-25470.0
(2J)(5K)
0.248;-21735.0
2K(5J)
0.247;-24975.0
25(JK)
0.213;-24975.0
(5Q)(2K)
0.237;-21240.0
(2K)(5K)
0.325;-17505.0
6(268)
0.188;-26190.0
6T(26)
0.244;-25200.0
(26)(6K)
0.249;-20475.0
T(267)
0.246;-27945.0
7(268)
0.198;-28935.0
7T(26)
0.234;-27945.0
(26)(7K)
0.218;-23220.0
J(268)
0.211;-26955.0
89(26)
0.244;-27945.0
(26)(8Q)
0.245;-23220.0
(269J)
0.212;-26460.0
(26)(9T)
0.233;-23715.0
9(26K)
0.212;-25470.0
(26TK)
0.223;-24975.0
TQ(26)
0.253;-25470.0
K(26J)
0.290;-24480.0
Q(26Q)
0.273;-21240.0
KK(26)
0.293;-20250.0
66(29)
0.184;-25695.0
266J
0.170;-27945.0
67(27)
0.226;-26190.0
(27)(6T)
0.267;-24705.0
6(27K)
0.274;-26460.0
2(679)
0.171;-28440.0
(67)(2Q)
0.223;-23715.0
27(68)
0.195;-28935.0
27(6T)
0.278;-27945.0
27(6Q)
0.242;-26955.0
68(28)
0.174;-25200.0
(28)(6J)
0.226;-23715.0
28(68)
0.278;-25200.0
2(68J)
0.197;-26955.0
2688
0.233;-28440.0
268T
0.175;-30690.0
268Q
0.213;-29700.0
(29)(6T)
0.192;-23715.0
6(29K)
0.266;-25470.0
2(69J)
0.260;-26460.0
2699
0.221;-27450.0
269J
0.207;-29700.0
269K
0.189;-28710.0
6Q(2T)
0.213;-25470.0
(6T)(2Q)
0.247;-22230.0
2T(6J)
0.218;-25965.0
2T(6K)
0.211;-24975.0
6(2JK)
0.239;-24480.0
2(6JK)
0.177;-24480.0
2J(6K)
0.258;-24480.0
2Q(6Q)
0.306;-21240.0
26QK
0.262;-27225.0
78(27)
0.207;-25200.0
(27)(7J)
0.314;-20475.0
8(278)
0.277;-24705.0
Q(278)
0.264;-25965.0
(27)(8T)
0.221;-23715.0
8(27K)
0.250;-25470.0
(279Q)
0.202;-25470.0
9(27J)
0.201;-25965.0
9K(27)
0.200;-24975.0
TT(27)
0.245;-22725.0
(27)(TK)
0.240;-21240.0
J(27Q)
0.226;-24480.0
K(27Q)
0.248;-23490.0
77(28)
0.259;-25200.0
277T
0.226;-27450.0
27(7K)
0.310;-22725.0
(28)(7T)
0.218;-23715.0
7(28K)
0.215;-25470.0
2(78T)
0.181;-26955.0
(78)(2K)
0.247;-22230.0
78(2T)
0.233;-26955.0
78(2Q)
0.241;-25965.0
(29)(79)
0.261;-20475.0
7(29Q)
0.177;-25470.0
2(79T)
0.233;-26460.0
(79)(2K)
0.254;-21735.0
79(2J)
0.213;-25965.0
79(2K)
0.253;-24975.0
7J(2T)
0.277;-25470.0
(7T)(2J)
0.292;-22230.0
2K(7T)
0.205;-24480.0
27(TQ)
0.218;-24975.0
7(2JQ)
0.283;-24480.0
2(7JQ)
0.243;-24480.0
27(JQ)
0.271;-24480.0
7(2QK)
0.282;-23490.0
7Q(2K)
0.252;-23490.0
88(28)
0.257;-20970.0
(28)(8J)
0.254;-19485.0
9(289)
0.286;-23220.0
K(289)
0.238;-24480.0
9(28Q)
0.233;-24975.0
J(28T)
0.225;-24975.0
TJ(28)
0.205;-24975.0
(28JQ)
0.234;-23985.0
J(28K)
0.236;-23490.0
(28)(QK)
0.284;-19755.0
88(2T)
0.240;-23220.0
288Q
0.195;-25470.0
8T(29)
0.265;-25965.0
(29)(8K)
0.274;-21240.0
2J(89)
0.194;-25470.0
89(2T)
0.235;-25965.0
89(2Q)
0.225;-24975.0
(2T)(8T)
0.265;-18990.0
8(2TK)
0.265;-23985.0
2(8TQ)
0.227;-24480.0
28(TJ)
0.215;-24975.0
28(TK)
0.209;-23985.0
(2J)(8K)
0.302;-20250.0
2K(8J)
0.279;-23490.0
28(JK)
0.209;-23490.0
(8Q)(2K)
0.231;-19755.0
(2K)(8K)
0.308;-16020.0
9(29J)
0.315;-21735.0
9K(29)
0.276;-20745.0
TT(29)
0.214;-21735.0
(29)(TK)
0.243;-20250.0
J(29Q)
0.227;-23490.0
K(29Q)
0.298;-22500.0
99(2T)
0.239;-22230.0
299Q
0.256;-24480.0
9J(2T)
0.177;-24480.0
(9T)(2J)
0.249;-21240.0
2K(9T)
0.280;-23490.0
29(TQ)
0.266;-23985.0
9(2JQ)
0.287;-23490.0
2(9JQ)
0.276;-23490.0
29(JQ)
0.230;-23490.0
9(2QK)
0.239;-22500.0
9Q(2K)
0.261;-22500.0
TT(2T)
0.308;-18000.0
(2T)(TK)
0.297;-16515.0
J(2TQ)
0.259;-22995.0
K(2TQ)
0.307;-22005.0
TT(2J)
0.311;-20745.0
2TTK
0.245;-22995.0
TK(2J)
0.244;-22500.0
2TJJ
0.220;-23490.0
2TJK
0.197;-25740.0
2(TQK)
0.260;-22005.0
TK(2K)
0.259;-18270.0
(2J)(JK)
0.285;-15525.0
QK(2J)
0.224;-21510.0
2J(JK)
0.309;-18765.0
(JQ)(2K)
0.260;-18270.0
(2K)(JK)
0.386;-14535.0
K(2QK)
0.286;-17280.0
2K(QK)
0.289;-17280.0
3335
0.176;-30150.0
3339
0.197;-28170.0
333K
0.235;-26190.0
36(34)
0.206;-29160.0
(34)(39)
0.259;-24435.0
3(34Q)
0.220;-26190.0
33(45)
0.221;-29655.0
34(38)
0.201;-28170.0
334T
0.186;-30420.0
33(4K)
0.241;-25695.0
(35)(37)
0.221;-24930.0
3(35T)
0.248;-26685.0
3Q(35)
0.199;-25695.0
35(37)
0.212;-28170.0
3359
0.203;-30420.0
33(5Q)
0.233;-25695.0
(36)(37)
0.283;-24435.0
3(36T)
0.204;-26190.0
3Q(36)
0.188;-25200.0
36(38)
0.167;-27180.0
336T
0.190;-29430.0
33(6K)
0.241;-24705.0
(37)(39)
0.209;-22950.0
3(37Q)
0.237;-24705.0
33(78)
0.188;-26685.0
37(3J)
0.208;-25200.0
337K
0.220;-27450.0
3T(38)
0.199;-25200.0
(38)(3K)
0.317;-20475.0
338T
0.233;-28440.0
33(8K)
0.250;-23715.0
(39)(3J)
0.271;-20970.0
3399
0.273;-25200.0
33(9Q)
0.191;-23715.0
(3T)(3J)
0.285;-20475.0
33TT
0.217;-24210.0
33(TK)
0.213;-22725.0
(3J)(3K)
0.272;-18990.0
33JK
0.221;-25470.0
33(QK)
0.317;-21735.0
45(34)
0.185;-29160.0
(34)(48)
0.230;-24435.0
4(34J)
0.229;-26190.0
4K(34)
0.202;-25200.0
(3459)
0.229;-29925.0
(345K)
0.261;-27945.0
57(34)
0.178;-30915.0
(34)(5T)
0.238;-26190.0
5(34K)
0.244;-27945.0
(3469)
0.199;-29430.0
(346K)
0.216;-27450.0
68(34)
0.177;-29925.0
(34)(6J)
0.188;-25200.0
7(347)
0.190;-26685.0
J(347)
0.187;-27945.0
78(34)
0.179;-29430.0
(34)(7J)
0.232;-24705.0
8(348)
0.242;-25695.0
Q(348)
0.208;-26955.0
(34)(8T)
0.259;-24705.0
8(34K)
0.249;-26460.0
(349Q)
0.240;-26460.0
9(34J)
0.242;-26955.0
9K(34)
0.221;-25965.0
TT(34)
0.279;-23715.0
(34)(TK)
0.284;-22230.0
J(34Q)
0.248;-25470.0
K(34Q)
0.280;-24480.0
44(35)
0.222;-29160.0
3447
0.191;-31410.0
34(4T)
0.270;-26685.0
44(3K)
0.263;-25200.0
4(357)
0.179;-30915.0
49(35)
0.190;-29925.0
(35)(4Q)
0.241;-25200.0
36(45)
0.234;-31410.0
3(459)
0.154;-29925.0
(45)(3Q)
0.242;-25200.0
35(46)
0.181;-31410.0
35(48)
0.194;-30420.0
35(4T)
0.229;-29430.0
35(4Q)
0.180;-28440.0
46(36)
0.183;-27675.0
(36)(49)
0.192;-26190.0
4(36Q)
0.278;-27945.0
3(467)
0.179;-30420.0
(46)(3T)
0.263;-25695.0
3Q(46)
0.212;-27945.0
3467
0.183;-33660.0
3469
0.197;-32670.0
346J
0.190;-31680.0
346K
0.187;-30690.0
49(37)
0.246;-28935.0
(37)(4Q)
0.249;-24210.0
38(47)
0.191;-29430.0
3(47J)
0.236;-27945.0
3477
0.203;-29925.0
3479
0.198;-32175.0
347J
0.167;-31185.0
347K
0.186;-30195.0
4T(38)
0.228;-27945.0
(38)(4K)
0.270;-23220.0
3T(48)
0.227;-27945.0
3(48K)
0.166;-26460.0
38(4T)
0.233;-27945.0
38(4Q)
0.169;-26955.0
49(39)
0.257;-24705.0
(39)(4Q)
0.289;-23220.0
3T(49)
0.216;-27450.0
3(49K)
0.257;-25965.0
39(4J)
0.202;-26955.0
39(4K)
0.176;-25965.0
4(3TQ)
0.269;-25965.0
3(4TJ)
0.235;-26460.0
34TT
0.220;-26955.0
34TQ
0.191;-29205.0
(3J)(4Q)
0.203;-22230.0
3Q(4J)
0.241;-25470.0
34JQ
0.214;-28710.0
(3Q)(4K)
0.317;-21240.0
3Q(4K)
0.226;-24480.0
5(356)
0.207;-27675.0
58(35)
0.228;-26685.0
(35)(5J)
0.194;-21960.0
6(356)
0.212;-27180.0
T(356)
0.262;-28440.0
6(357)
0.192;-29925.0
69(35)
0.201;-28935.0
(35)(6Q)
0.266;-24210.0
(3579)
0.200;-28440.0
(357K)
0.286;-26460.0
79(35)
0.240;-28440.0
(35)(7Q)
0.240;-23715.0
(358T)
0.208;-27450.0
88(35)
0.285;-25200.0
(35)(8J)
0.299;-23715.0
9(359)
0.261;-24210.0
K(359)
0.227;-25470.0
9(35Q)
0.186;-25965.0
J(35T)
0.219;-25965.0
TJ(35)
0.190;-25965.0
(35JQ)
0.255;-24975.0
J(35K)
0.219;-24480.0
(35)(QK)
0.312;-20745.0
55(37)
0.252;-27180.0
3559
0.184;-29430.0
35(5Q)
0.190;-24705.0
(36)(57)
0.290;-26685.0
5(36T)
0.176;-28440.0
5Q(36)
0.210;-27450.0
(56)(38)
0.204;-26190.0
3T(56)
0.226;-28440.0
3(56K)
0.223;-26955.0
36(58)
0.164;-29430.0
36(5T)
0.214;-28440.0
36(5Q)
0.197;-27450.0
57(37)
0.206;-26190.0
(37)(5T)
0.216;-24705.0
5(37K)
0.223;-26460.0
3(579)
0.181;-28440.0
(57)(3Q)
0.249;-23715.0
37(58)
0.168;-28935.0
37(5T)
0.244;-27945.0
37(5Q)
0.176;-26955.0
58(38)
0.252;-25200.0
(38)(5J)
0.246;-23715.0
38(58)
0.256;-25200.0
3(58J)
0.274;-26955.0
3588
0.192;-28440.0
358T
0.232;-30690.0
358Q
0.156;-29700.0
(39)(5T)
0.281;-23715.0
5(39K)
0.184;-25470.0
3(59J)
0.244;-26460.0
3599
0.208;-27450.0
359J
0.209;-29700.0
359K
0.206;-28710.0
5Q(3T)
0.216;-25470.0
(5T)(3Q)
0.199;-22230.0
3T(5J)
0.235;-25965.0
3T(5K)
0.241;-24975.0
5(3JK)
0.194;-24480.0
3(5JK)
0.208;-24480.0
3J(5K)
0.231;-24480.0
3Q(5Q)
0.291;-21240.0
35QK
0.231;-27225.0
67(36)
0.221;-26190.0
(36)(6T)
0.256;-21465.0
6(36K)
0.221;-23220.0
(367T)
0.250;-27450.0
77(36)
0.235;-25695.0
(36)(7T)
0.211;-24210.0
7(36K)
0.194;-25965.0
(368J)
0.191;-26460.0
(36)(89)
0.214;-24210.0
8(36Q)
0.237;-25965.0
T(369)
0.166;-26460.0
9(36T)
0.194;-26460.0
9Q(36)
0.272;-25470.0
Q(36T)
0.249;-24975.0
(36)(TQ)
0.262;-21735.0
(36JK)
0.273;-23985.0
JK(36)
0.225;-23985.0
K(36K)
0.224;-19755.0
3668
0.185;-28935.0
36(6J)
0.187;-24210.0
(37)(67)
0.288;-22455.0
6(37T)
0.236;-27450.0
6Q(37)
0.244;-26460.0
(67)(39)
0.266;-24705.0
3J(67)
0.236;-26955.0
67(38)
0.167;-28440.0
67(3T)
0.185;-27450.0
67(3Q)
0.201;-26460.0
(38)(68)
0.250;-21465.0
6(38J)
0.171;-26460.0
6K(38)
0.216;-25470.0
(68)(3J)
0.267;-23220.0
3K(68)
0.189;-25470.0
36(8T)
0.195;-26955.0
36(8Q)
0.255;-25965.0
6(39T)
0.212;-26460.0
6Q(39)
0.222;-25470.0
(69)(3J)
0.241;-22725.0
3K(69)
0.217;-24975.0
36(9J)
0.178;-25965.0
36(9K)
0.213;-24975.0
(3T)(6Q)
0.231;-21735.0
3J(6T)
0.191;-25470.0
6T(3J)
0.209;-25470.0
6T(3K)
0.251;-24480.0
6Q(3J)
0.229;-24480.0
(6J)(3K)
0.304;-20745.0
6J(3K)
0.260;-23985.0
6K(3Q)
0.271;-23490.0
36(QK)
0.239;-23490.0
(37)(78)
0.195;-21465.0
7(37J)
0.231;-23220.0
7K(37)
0.191;-22230.0
(378Q)
0.288;-25470.0
8(37T)
0.205;-26460.0
8Q(37)
0.178;-25470.0
J(379)
0.264;-25470.0
9T(37)
0.218;-25965.0
(37)(9K)
0.309;-21240.0
K(37T)
0.267;-23985.0
T(37K)
0.206;-23985.0
JJ(37)
0.264;-21240.0
(37QK)
0.247;-22995.0
3777
0.244;-25200.0
37(7T)
0.298;-23715.0
77(3K)
0.277;-22230.0
7(38T)
0.234;-26460.0
7Q(38)
0.256;-25470.0
(78)(3T)
0.249;-23220.0
3Q(78)
0.219;-25470.0
3789
0.193;-30195.0
378J
0.221;-29205.0
378K
0.167;-28215.0
7J(39)
0.243;-25470.0
(79)(3T)
0.247;-22725.0
3Q(79)
0.193;-24975.0
379T
0.210;-29205.0
379Q
0.242;-28215.0
(3T)(7J)
0.285;-21735.0
3T(7T)
0.264;-22230.0
3(7TK)
0.247;-23985.0
3T(7Q)
0.249;-24480.0
7J(3J)
0.222;-21240.0
(7J)(3Q)
0.217;-20745.0
3J(7Q)
0.235;-23985.0
7Q(3Q)
0.270;-20250.0
37QQ
0.267;-23490.0
37KK
0.274;-22500.0
8(38J)
0.252;-22230.0
8K(38)
0.290;-21240.0
(389K)
0.262;-23985.0
9J(38)
0.239;-24975.0
(38TJ)
0.228;-24480.0
(38)(TJ)
0.229;-21240.0
J(38J)
0.259;-20745.0
JQ(38)
0.270;-23490.0
Q(38K)
0.255;-22500.0
3889
0.199;-26460.0
38(8Q)
0.269;-21735.0
(39)(8T)
0.250;-22230.0
8(39K)
0.195;-23985.0
3(89J)
0.273;-24975.0
3899
0.269;-25965.0
389J
0.214;-28215.0
389K
0.213;-27225.0
8Q(3T)
0.190;-23985.0
(8T)(3Q)
0.305;-20745.0
3T(8J)
0.220;-24480.0
3T(8K)
0.252;-23490.0
8(3JK)
0.270;-22995.0
3(8JK)
0.280;-22995.0
3J(8K)
0.205;-22995.0
3Q(8Q)
0.302;-19755.0
38QK
0.221;-25740.0
9T(39)
0.275;-21735.0
(39)(9K)
0.288;-17010.0
K(39T)
0.259;-22995.0
T(39K)
0.211;-22995.0
JJ(39)
0.281;-20250.0
(39QK)
0.273;-22005.0
3999
0.242;-22230.0
39(9Q)
0.276;-20745.0
(3T)(9J)
0.224;-20745.0
3T(9T)
0.250;-21240.0
3(9TK)
0.217;-22995.0
3T(9Q)
0.243;-23490.0
9J(3J)
0.273;-20250.0
(9J)(3Q)
0.286;-19755.0
3J(9Q)
0.260;-22995.0
9Q(3Q)
0.232;-19260.0
39QQ
0.291;-22500.0
39KK
0.272;-21510.0
T(3TK)
0.230;-19260.0
JJ(3T)
0.218;-19755.0
(3TQK)
0.247;-21510.0
3TTT
0.269;-20745.0
3T(TK)
0.250;-19260.0
(3J)(TK)
0.306;-18765.0
3K(TJ)
0.247;-22005.0
3T(JK)
0.278;-22005.0
(TQ)(3K)
0.281;-18270.0
(3K)(TK)
0.354;-14535.0
J(3JK)
0.360;-18270.0
(3J)(QK)
0.276;-17775.0
JJ(3K)
0.323;-18270.0
3Q(JQ)
0.248;-18270.0
3JQK
0.217;-24255.0
QK(3Q)
0.324;-17280.0
QK(3K)
0.317;-16785.0
44(46)
0.247;-24930.0
44(4T)
0.265;-22950.0
(45)(45)
0.327;-21690.0
4(458)
0.273;-26685.0
4T(45)
0.223;-25695.0
(45)(4K)
0.269;-20970.0
4457
0.170;-30420.0
44(5T)
0.212;-25695.0
45(4K)
0.186;-24210.0
4(468)
0.183;-26190.0
4T(46)
0.239;-25200.0
(46)(4K)
0.259;-20475.0
4468
0.179;-29430.0
44(6J)
0.225;-24705.0
(47)(47)
0.292;-19710.0
4(47T)
0.255;-24705.0
4Q(47)
0.264;-23715.0
47(49)
0.244;-25200.0
447J
0.235;-27450.0
48(48)
0.242;-21960.0
(48)(4J)
0.231;-20475.0
4488
0.188;-25200.0
44(8J)
0.252;-23715.0
(49)(49)
0.298;-17730.0
4(49Q)
0.279;-22725.0
44(9T)
0.277;-23715.0
49(4K)
0.289;-22230.0
4(4TQ)
0.247;-22230.0
44(TJ)
0.209;-22725.0
(4J)(4J)
0.347;-15750.0
44JJ
0.273;-22230.0
4Q(4Q)
0.321;-18000.0
(4K)(4K)
0.372;-13770.0
(45)(57)
0.265;-23445.0
5(45T)
0.175;-25200.0
5Q(45)
0.195;-24210.0
8(456)
0.220;-28935.0
Q(456)
0.226;-26955.0
(45)(68)
0.242;-25695.0
6(45J)
0.259;-27450.0
6K(45)
0.234;-26460.0
(457J)
0.181;-26955.0
(45)(78)
0.238;-25200.0
7(45J)
0.220;-26955.0
7K(45)
0.231;-25965.0
(458Q)
0.255;-25965.0
8(45T)
0.234;-26955.0
8Q(45)
0.211;-25965.0
J(459)
0.216;-25965.0
9T(45)
0.229;-26460.0
(45)(9K)
0.288;-21735.0
K(45T)
0.302;-24480.0
T(45K)
0.236;-24480.0
JJ(45)
0.304;-21735.0
(45QK)
0.282;-23490.0
4555
0.190;-27675.0
45(58)
0.209;-26190.0
55(4J)
0.211;-24705.0
455K
0.248;-26955.0
58(46)
0.190;-28935.0
(46)(5J)
0.221;-24210.0
46(56)
0.251;-26685.0
4(569)
0.228;-28440.0
(56)(4Q)
0.230;-23715.0
46(57)
0.210;-29430.0
46(59)
0.174;-28440.0
46(5J)
0.222;-27450.0
46(5K)
0.280;-26460.0
5(479)
0.214;-27945.0
5J(47)
0.220;-26955.0
(57)(48)
0.197;-25200.0
4T(57)
0.250;-27450.0
4(57K)
0.287;-25965.0
47(59)
0.212;-27945.0
47(5J)
0.232;-26955.0
47(5K)
0.202;-25965.0
5(48T)
0.230;-26955.0
5Q(48)
0.245;-25965.0
(58)(4T)
0.265;-23715.0
4Q(58)
0.201;-25965.0
4589
0.239;-30690.0
458J
0.192;-29700.0
458K
0.195;-28710.0
5J(49)
0.238;-25965.0
(59)(4T)
0.308;-23220.0
4Q(59)
0.218;-25470.0
459T
0.252;-29700.0
459Q
0.173;-28710.0
(4T)(5J)
0.225;-22230.0
4T(5T)
0.220;-22725.0
4(5TK)
0.270;-24480.0
4T(5Q)
0.184;-24975.0
5J(4J)
0.239;-21735.0
(5J)(4Q)
0.296;-21240.0
4J(5Q)
0.248;-24480.0
5Q(4Q)
0.255;-20745.0
45QQ
0.249;-23985.0
45KK
0.238;-22995.0
6(469)
0.205;-24705.0
6J(46)
0.255;-23715.0
(4678)
0.197;-27945.0
(467Q)
0.296;-25965.0
7(469)
0.266;-27450.0
7J(46)
0.242;-26460.0
(4689)
0.214;-26955.0
(468K)
0.221;-24975.0
8T(46)
0.229;-26460.0
(46)(8K)
0.285;-21735.0
Q(469)
0.237;-24975.0
(46)(9J)
0.254;-22230.0
T(46T)
0.277;-22230.0
T(46J)
0.215;-24975.0
TK(46)
0.212;-23985.0
(46)(JQ)
0.250;-20745.0
QQ(46)
0.302;-20250.0
46(67)
0.210;-25695.0
66(4T)
0.209;-24210.0
466Q
0.205;-26460.0
68(47)
0.190;-27945.0
(47)(6J)
0.266;-23220.0
47(67)
0.258;-25200.0
4(67T)
0.177;-26955.0
(67)(4K)
0.192;-22230.0
67(49)
0.220;-27450.0
67(4J)
0.209;-26460.0
67(4K)
0.230;-25470.0
69(48)
0.248;-26955.0
(48)(6Q)
0.255;-22230.0
49(68)
0.276;-26955.0
4(68Q)
0.225;-25470.0
46(89)
0.198;-26955.0
46(8J)
0.253;-25965.0
46(8K)
0.258;-24975.0
(49)(6J)
0.246;-22230.0
49(69)
0.272;-23220.0
4(69Q)
0.255;-24975.0
46(9T)
0.264;-25965.0
46(9Q)
0.244;-24975.0
6(4TJ)
0.188;-24975.0
6K(4T)
0.255;-23985.0
(6T)(4K)
0.265;-20745.0
6T(4Q)
0.223;-24480.0
(4J)(6J)
0.272;-18000.0
4J(6J)
0.285;-21240.0
6J(4Q)
0.209;-23985.0
(4Q)(6Q)
0.229;-17010.0
4K(6Q)
0.278;-22995.0
4K(6K)
0.299;-19260.0
79(47)
0.248;-23715.0
(47)(7Q)
0.331;-18990.0
(478T)
0.260;-25965.0
88(47)
0.240;-23715.0
(47)(8J)
0.237;-22230.0
9(479)
0.251;-22725.0
K(479)
0.294;-23985.0
9(47Q)
0.245;-24480.0
J(47T)
0.241;-24480.0
TJ(47)
0.261;-24480.0
(47JQ)
0.250;-23490.0
J(47K)
0.280;-22995.0
(47)(QK)
0.229;-19260.0
77(49)
0.207;-23715.0
477J
0.212;-25965.0
78(48)
0.252;-23715.0
(48)(7J)
0.229;-22230.0
48(78)
0.232;-23715.0
4(78J)
0.232;-25470.0
4788
0.266;-26955.0
478T
0.196;-29205.0
478Q
0.220;-28215.0
(49)(7T)
0.271;-22230.0
7(49K)
0.206;-23985.0
4(79J)
0.213;-24975.0
4799
0.236;-25965.0
479J
0.209;-28215.0
479K
0.219;-27225.0
7Q(4T)
0.198;-23985.0
(7T)(4Q)
0.287;-20745.0
4T(7J)
0.246;-24480.0
4T(7K)
0.234;-23490.0
7(4JK)
0.195;-22995.0
4(7JK)
0.226;-22995.0
4J(7K)
0.224;-22995.0
4Q(7Q)
0.262;-19755.0
47QK
0.238;-25740.0
89(48)
0.214;-22725.0
(48)(8Q)
0.248;-18000.0
(489J)
0.210;-24480.0
(48)(9T)
0.254;-21735.0
9(48K)
0.239;-23490.0
(48TK)
0.226;-22995.0
TQ(48)
0.230;-23490.0
K(48J)
0.295;-22500.0
Q(48Q)
0.280;-19260.0
KK(48)
0.347;-18270.0
88(4J)
0.264;-21735.0
488K
0.253;-23985.0
8J(49)
0.192;-24480.0
(89)(4T)
0.241;-21735.0
4Q(89)
0.270;-23985.0
489T
0.239;-28215.0
489Q
0.230;-27225.0
(4T)(8J)
0.260;-20745.0
4T(8T)
0.264;-21240.0
4(8TK)
0.282;-22995.0
4T(8Q)
0.229;-23490.0
8J(4J)
0.257;-20250.0
(8J)(4Q)
0.280;-19755.0
4J(8Q)
0.268;-22995.0
8Q(4Q)
0.293;-19260.0
48QQ
0.240;-22500.0
48KK
0.289;-21510.0
9(49Q)
0.301;-20250.0
J(49T)
0.259;-23490.0
TJ(49)
0.235;-23490.0
(49JQ)
0.190;-22500.0
J(49K)
0.244;-22005.0
(49)(QK)
0.285;-18270.0
99(4J)
0.256;-20745.0
499K
0.246;-22995.0
9Q(4T)
0.186;-22995.0
(9T)(4Q)
0.256;-19755.0
4T(9J)
0.218;-23490.0
4T(9K)
0.221;-22500.0
9(4JK)
0.233;-22005.0
4(9JK)
0.225;-22005.0
4J(9K)
0.230;-22005.0
4Q(9Q)
0.267;-18765.0
49QK
0.298;-24750.0
TJ(4T)
0.257;-19755.0
(4TJQ)
0.297;-22005.0
J(4TK)
0.312;-21510.0
(4T)(QK)
0.235;-17775.0
TT(4Q)
0.292;-19260.0
T(4JQ)
0.255;-22005.0
4(TJQ)
0.233;-22005.0
4T(JQ)
0.211;-22005.0
T(4QK)
0.224;-21015.0
TQ(4K)
0.255;-21015.0
JJ(4J)
0.337;-15525.0
(4JQK)
0.276;-20520.0
4JJJ
0.324;-18765.0
JQ(4Q)
0.304;-17775.0
4JQQ
0.335;-21015.0
4JKK
0.302;-20025.0
QQ(4K)
0.315;-16785.0
4KKK
0.274;-15795.0
55(59)
0.237;-21960.0
55(5K)
0.294;-19980.0
(56)(58)
0.273;-21960.0
5(56J)
0.256;-23715.0
5K(56)
0.226;-22725.0
56(59)
0.217;-24705.0
556J
0.200;-26955.0
57(57)
0.250;-21960.0
(57)(5T)
0.243;-20475.0
5(57K)
0.231;-22230.0
55(79)
0.263;-24210.0
57(5Q)
0.255;-22725.0
5(589)
0.258;-23715.0
5J(58)
0.319;-22725.0
58(59)
0.254;-23715.0
558J
0.231;-25965.0
59(59)
0.297;-19980.0
(59)(5Q)
0.323;-18495.0
559T
0.254;-25965.0
55(9K)
0.227;-21240.0
(5T)(5Q)
0.298;-18000.0
55TJ
0.235;-24975.0
5J(5J)
0.342;-18000.0
5J(5Q)
0.251;-20745.0
5(5QK)
0.256;-19755.0
5K(5K)
0.303;-16020.0
68(56)
0.228;-24705.0
(56)(6J)
0.246;-19980.0
7(567)
0.216;-24705.0
J(567)
0.196;-25965.0
78(56)
0.210;-27450.0
(56)(7J)
0.264;-22725.0
8(568)
0.293;-23715.0
Q(568)
0.270;-24975.0
(56)(8T)
0.241;-22725.0
8(56K)
0.252;-24480.0
(569Q)
0.205;-24480.0
9(56J)
0.220;-24975.0
9K(56)
0.260;-23985.0
TT(56)
0.263;-21735.0
(56)(TK)
0.275;-20250.0
J(56Q)
0.279;-23490.0
K(56Q)
0.239;-22500.0
66(57)
0.217;-25200.0
5669
0.223;-27450.0
56(6Q)
0.296;-22725.0
(57)(68)
0.254;-24210.0
6(57J)
0.182;-25965.0
6K(57)
0.238;-24975.0
(67)(5T)
0.202;-23220.0
5Q(67)
0.221;-25470.0
5678
0.244;-30690.0
567T
0.211;-29700.0
567Q
0.216;-28710.0
(58)(69)
0.240;-23220.0
6(58Q)
0.259;-24975.0
5(689)
0.210;-26460.0
(68)(5Q)
0.277;-21735.0
58(69)
0.237;-26460.0
58(6J)
0.211;-25470.0
58(6K)
0.234;-24480.0
6(59J)
0.226;-24975.0
6K(59)
0.253;-23985.0
(69)(5Q)
0.244;-21240.0
59(6T)
0.215;-25470.0
59(6Q)
0.218;-24480.0
6T(5T)
0.286;-21735.0
(5T)(6K)
0.232;-20250.0
5Q(6T)
0.229;-23985.0
56TJ
0.210;-27720.0
56TK
0.188;-26730.0
6K(5J)
0.248;-22995.0
56JJ
0.194;-23985.0
56JK
0.237;-26235.0
5(6QK)
0.243;-22500.0
6K(5K)
0.279;-18765.0
(57)(79)
0.282;-19980.0
7(57Q)
0.226;-21735.0
9(578)
0.215;-25965.0
K(578)
0.216;-23985.0
8(57J)
0.235;-24975.0
8K(57)
0.198;-23985.0
(579K)
0.205;-23490.0
9J(57)
0.205;-24480.0
(57TJ)
0.272;-23985.0
(57)(TJ)
0.267;-20745.0
J(57J)
0.315;-20250.0
JQ(57)
0.257;-22995.0
Q(57K)
0.214;-22005.0
5778
0.216;-26955.0
57(7J)
0.216;-22230.0
(58)(78)
0.225;-19980.0
7(58J)
0.238;-24975.0
7K(58)
0.258;-23985.0
(78)(5J)
0.234;-21735.0
5K(78)
0.225;-23985.0
57(8T)
0.276;-25470.0
57(8Q)
0.227;-24480.0
7(59T)
0.235;-24975.0
7Q(59)
0.281;-23985.0
(79)(5J)
0.267;-21240.0
5K(79)
0.259;-23490.0
57(9J)
0.245;-24480.0
57(9K)
0.245;-23490.0
(5T)(7Q)
0.275;-20250.0
5J(7T)
0.202;-23985.0
7T(5J)
0.222;-23985.0
7T(5K)
0.192;-22995.0
7Q(5J)
0.305;-22995.0
(7J)(5K)
0.356;-19260.0
7J(5K)
0.293;-22500.0
7K(5Q)
0.269;-22005.0
57(QK)
0.280;-22005.0
(58)(89)
0.353;-18990.0
8(58Q)
0.278;-20745.0
T(589)
0.238;-24480.0
9(58T)
0.286;-24480.0
9Q(58)
0.258;-23490.0
Q(58T)
0.238;-22995.0
(58)(TQ)
0.295;-19755.0
(58JK)
0.265;-22005.0
JK(58)
0.256;-22005.0
K(58K)
0.310;-17775.0
588T
0.216;-24975.0
58(8K)
0.254;-20250.0
(59)(8J)
0.316;-20745.0
59(89)
0.297;-21735.0
5(89Q)
0.259;-23490.0
58(9T)
0.201;-24480.0
58(9Q)
0.299;-23490.0
8(5TJ)
0.299;-23490.0
8K(5T)
0.202;-22500.0
(8T)(5K)
0.219;-19260.0
8T(5Q)
0.211;-22995.0
(5J)(8J)
0.256;-16515.0
5J(8J)
0.280;-19755.0
8J(5Q)
0.254;-22500.0
(5Q)(8Q)
0.304;-15525.0
5K(8Q)
0.285;-21510.0
5K(8K)
0.316;-17775.0
9J(59)
0.312;-20250.0
(59TJ)
0.213;-22995.0
(59)(TJ)
0.270;-19755.0
J(59J)
0.221;-19260.0
JQ(59)
0.262;-22005.0
Q(59K)
0.285;-21015.0
599T
0.210;-23985.0
59(9K)
0.242;-19260.0
(5T)(9Q)
0.270;-19260.0
5J(9T)
0.249;-22995.0
9T(5J)
0.230;-22995.0
9T(5K)
0.225;-22005.0
9Q(5J)
0.253;-22005.0
(9J)(5K)
0.271;-18270.0
9J(5K)
0.294;-21510.0
9K(5Q)
0.201;-21015.0
59(QK)
0.334;-21015.0
(5T)(TJ)
0.305;-16020.0
J(5TJ)
0.225;-18765.0
JQ(5T)
0.267;-21510.0
Q(5TK)
0.275;-20520.0
5TTJ
0.239;-22500.0
TJ(5J)
0.328;-18765.0
(TJ)(5Q)
0.274;-18270.0
5J(TQ)
0.245;-21510.0
TQ(5Q)
0.254;-17775.0
5TQQ
0.302;-21015.0
5TKK
0.293;-20025.0
Q(5JQ)
0.368;-17280.0
KK(5J)
0.334;-16290.0
(5Q)(JQ)
0.290;-14040.0
5K(JQ)
0.262;-20025.0
5K(JK)
0.368;-16290.0
5QQQ
0.307;-16785.0
KK(5K)
0.347;-12060.0
6669
0.252;-23715.0
666K
0.247;-21735.0
69(67)
0.254;-23220.0
(67)(6Q)
0.279;-18495.0
6678
0.232;-26955.0
66(7J)
0.257;-22230.0
(68)(68)
0.300;-16740.0
6(68J)
0.270;-21735.0
6K(68)
0.301;-20745.0
68(6J)
0.237;-21735.0
668K
0.182;-23985.0
6J(69)
0.241;-21240.0
69(6T)
0.233;-21735.0
669Q
0.231;-23985.0
6J(6T)
0.312;-20745.0
6T(6J)
0.294;-20745.0
66TK
0.232;-22995.0
6K(6J)
0.314;-19260.0
(6Q)(6Q)
0.355;-12780.0
66QK
0.319;-22005.0
7(679)
0.214;-22725.0
7J(67)
0.261;-21735.0
(6789)
0.201;-25470.0
(678K)
0.231;-23490.0
8T(67)
0.227;-24975.0
(67)(8K)
0.283;-20250.0
Q(679)
0.245;-23490.0
(67)(9J)
0.221;-20745.0
T(67T)
0.235;-20745.0
T(67J)
0.194;-23490.0
TK(67)
0.246;-22500.0
(67)(JQ)
0.260;-19260.0
QQ(67)
0.278;-18765.0
67(78)
0.208;-23220.0
77(6J)
0.299;-21735.0
677K
0.200;-23985.0
7T(68)
0.225;-24975.0
(68)(7K)
0.285;-20250.0
6T(78)
0.188;-24975.0
6(78K)
0.260;-23490.0
68(7T)
0.274;-24975.0
68(7Q)
0.219;-23985.0
79(69)
0.233;-21735.0
(69)(7Q)
0.340;-20250.0
6T(79)
0.214;-24480.0
6(79K)
0.248;-22995.0
69(7J)
0.242;-23985.0
69(7K)
0.316;-22995.0
7(6TQ)
0.282;-22995.0
6(7TJ)
0.233;-23490.0
67TT
0.259;-23985.0
67TQ
0.277;-26235.0
(6J)(7Q)
0.318;-19260.0
6Q(7J)
0.296;-22500.0
67JQ
0.256;-25740.0
(6Q)(7K)
0.263;-18270.0
6Q(7K)
0.282;-21510.0
8(689)
0.244;-21735.0
8J(68)
0.262;-20745.0
(689T)
0.251;-23985.0
99(68)
0.222;-21240.0
(68)(9Q)
0.291;-19755.0
(68TQ)
0.225;-22500.0
T(68Q)
0.262;-22500.0
Q(68J)
0.250;-22005.0
(68)(JK)
0.229;-18270.0
QK(68)
0.218;-21015.0
68(8T)
0.232;-21240.0
88(6K)
0.260;-19755.0
8(69J)
0.295;-23490.0
8K(69)
0.261;-22500.0
(89)(6Q)
0.252;-19755.0
69(8T)
0.203;-23985.0
69(8Q)
0.236;-22995.0
8T(6T)
0.223;-20250.0
(6T)(8K)
0.246;-18765.0
6Q(8T)
0.281;-22500.0
68TJ
0.195;-26235.0
68TK
0.213;-25245.0
8K(6J)
0.208;-21510.0
68JJ
0.269;-22500.0
68JK
0.230;-24750.0
6(8QK)
0.282;-21015.0
8K(6K)
0.268;-17280.0
(69)(9J)
0.264;-16515.0
T(69T)
0.320;-19755.0
T(69J)
0.262;-22500.0
TK(69)
0.293;-21510.0
(69)(JQ)
0.260;-18270.0
QQ(69)
0.291;-17775.0
69(9T)
0.237;-20250.0
99(6K)
0.286;-18765.0
9(6TQ)
0.280;-22005.0
6(9TJ)
0.222;-22500.0
69TT
0.250;-22995.0
69TQ
0.208;-25245.0
(6J)(9Q)
0.298;-18270.0
6Q(9J)
0.293;-21510.0
69JQ
0.214;-24750.0
(6Q)(9K)
0.258;-17280.0
6Q(9K)
0.326;-20520.0
T(6TJ)
0.225;-18765.0
TK(6T)
0.305;-17775.0
(6T)(JQ)
0.227;-17775.0
QQ(6T)
0.284;-17280.0
6T(TJ)
0.309;-18765.0
(6J)(TJ)
0.334;-15030.0
6J(TJ)
0.291;-18270.0
TJ(6Q)
0.249;-21015.0
(6Q)(TQ)
0.378;-14040.0
6K(TQ)
0.278;-20025.0
6K(TK)
0.332;-16290.0
JK(6J)
0.295;-16785.0
K(6JK)
0.292;-15795.0
6JJK
0.214;-20025.0
6(JQK)
0.224;-19530.0
JK(6K)
0.248;-15795.0
KK(6Q)
0.326;-15300.0
6QKK
0.254;-18540.0
77(7T)
0.316;-18495.0
(78)(78)
0.315;-15750.0
7(78J)
0.228;-20745.0
7K(78)
0.299;-19755.0
78(7J)
0.271;-20745.0
778K
0.289;-22995.0
7J(79)
0.286;-20250.0
79(7T)
0.285;-20745.0
779Q
0.320;-22995.0
7J(7T)
0.224;-19755.0
7T(7J)
0.313;-19755.0
77TK
0.238;-22005.0
7K(7J)
0.331;-18270.0
(7Q)(7Q)
0.311;-11790.0
77QK
0.312;-21015.0
8(78T)
0.235;-20745.0
8Q(78)
0.314;-19755.0
J(789)
0.222;-22995.0
9T(78)
0.284;-23490.0
(78)(9K)
0.282;-18765.0
K(78T)
0.279;-21510.0
T(78K)
0.287;-21510.0
JJ(78)
0.282;-18765.0
(78QK)
0.267;-20520.0
7888
0.233;-21735.0
78(8J)
0.254;-20250.0
(79)(89)
0.319;-17505.0
8(79Q)
0.220;-22500.0
7(89T)
0.248;-23490.0
(89)(7K)
0.256;-18765.0
89(7J)
0.319;-22995.0
89(7K)
0.292;-22005.0
8J(7T)
0.224;-22500.0
(8T)(7J)
0.233;-19260.0
7K(8T)
0.255;-21510.0
78(TQ)
0.203;-22005.0
8(7JQ)
0.259;-21510.0
7(8JQ)
0.298;-21510.0
78(JQ)
0.201;-21510.0
8(7QK)
0.316;-20520.0
8Q(7K)
0.303;-20520.0
99(79)
0.305;-17010.0
(79)(9Q)
0.287;-15525.0
(79TQ)
0.252;-21510.0
T(79Q)
0.304;-21510.0
Q(79J)
0.250;-21015.0
(79)(JK)
0.294;-17280.0
QK(79)
0.322;-20025.0
79(9J)
0.286;-19260.0
(7T)(9T)
0.318;-16020.0
9(7TK)
0.237;-21015.0
7(9TQ)
0.273;-21510.0
79(TJ)
0.241;-22005.0
79(TK)
0.298;-21015.0
(7J)(9K)
0.303;-17280.0
7K(9J)
0.255;-20520.0
79(JK)
0.251;-20520.0
(9Q)(7K)
0.338;-16785.0
(7K)(9K)
0.332;-13050.0
T(7TQ)
0.231;-17775.0
Q(7TJ)
0.248;-20520.0
(7T)(JK)
0.228;-16785.0
QK(7T)
0.249;-19530.0
7T(TQ)
0.283;-17775.0
(7J)(TQ)
0.253;-17280.0
7Q(TJ)
0.279;-20520.0
7TJQ
0.215;-23760.0
(7Q)(TK)
0.243;-16290.0
7Q(TK)
0.328;-19530.0
J(7JQ)
0.283;-16785.0
K(7JQ)
0.302;-19035.0
JJ(7Q)
0.351;-16785.0
J(7QK)
0.278;-19035.0
JQ(7K)
0.334;-19035.0
QQ(7Q)
0.355;-12555.0
7Q(QK)
0.346;-15300.0
8888
0.318;-18000.0
888Q
0.291;-19260.0
8(89J)
0.243;-19260.0
8K(89)
0.309;-18270.0
89(8Q)
0.324;-18765.0
8(8TJ)
0.303;-18765.0
8K(8T)
0.289;-17775.0
8T(8K)
0.270;-17775.0
8(8JK)
0.355;-17280.0
88(JK)
0.277;-17280.0
8Q(8K)
0.348;-16785.0
(89)(9T)
0.300;-16020.0
9(89K)
0.319;-17775.0
(89TK)
0.236;-20520.0
TQ(89)
0.270;-21015.0
K(89J)
0.246;-20025.0
Q(89Q)
0.245;-16785.0
KK(89)
0.374;-15795.0
99(8Q)
0.313;-18270.0
9(8TJ)
0.276;-21510.0
9K(8T)
0.214;-20520.0
(9T)(8K)
0.263;-17280.0
9T(8Q)
0.221;-21015.0
(8J)(9J)
0.265;-14535.0
8J(9J)
0.321;-17775.0
9J(8Q)
0.273;-20520.0
(8Q)(9Q)
0.304;-13545.0
8K(9Q)
0.310;-19530.0
8K(9K)
0.257;-15795.0
TQ(8T)
0.338;-17280.0
K(8TJ)
0.269;-19530.0
Q(8TQ)
0.333;-16290.0
KK(8T)
0.362;-15300.0
