AAAA
0.390;650.0
5AAA
0.345;-418.7
9AAA
0.371;-143.7
KAAA
0.357;131.3
4A(2A)
0.391;-1312.5
(2A)(7A)
0.364;-656.3
A(2TA)
0.365;-900.0
QA(2A)
0.336;-762.5
2A(4A)
0.284;-1312.5
26AA
0.326;-1625.0
AA(29)
0.329;-968.7
2A(QA)
0.412;-762.5
A(34A)
0.356;-1243.8
6A(3A)
0.443;-1106.2
(3A)(9A)
0.341;-450.0
A(3QA)
0.360;-693.8
AA(34)
0.403;-1243.8
3A(7A)
0.371;-1037.5
39AA
0.366;-1350.0
AA(3Q)
0.358;-693.8
(4A)(5A)
0.406;-656.3
A(48A)
0.428;-900.0
TA(4A)
0.410;-762.5
(4A)(KA)
0.458;-106.2
46AA
0.404;-1487.5
AA(49)
0.395;-831.2
4A(QA)
0.319;-625.0
A(56A)
0.418;-968.7
8A(5A)
0.411;-831.2
(5A)(JA)
0.387;-175.0
55AA
0.342;-1037.5
AA(58)
0.415;-831.2
5A(JA)
0.419;-625.0
5KAA
0.362;-937.5
8A(6A)
0.405;-762.5
(6A)(JA)
0.397;-106.2
66AA
0.396;-900.0
AA(69)
0.308;-693.8
6A(QA)
0.390;-487.5
A(78A)
0.355;-693.8
TA(7A)
0.415;-556.2
(7A)(KA)
0.438;100.0
79AA
0.403;-1075.0
AA(7Q)
0.324;-418.8
(8A)(9A)
0.442;-106.2
A(8QA)
0.401;-350.0
AA(89)
0.379;-556.2
8A(QA)
0.415;-350.0
A(9TA)
0.396;-418.8
QA(9A)
0.379;-281.3
9A(JA)
0.314;-350.0
9KAA
0.406;-662.5
QA(TA)
0.397;-212.5
TA(QA)
0.335;-212.5
A(JQA)
0.366;-143.8
AA(JQ)
0.411;-143.8
(QA)(KA)
0.380;443.7
KKAA
0.402;62.5
2(25A)
0.308;-2068.7
27(2A)
0.305;-1931.2
(2T)(2A)
0.430;-1275.0
2(2KA)
0.401;-1518.7
(236A)
0.341;-2381.2
(23TA)
0.315;-2106.2
33(2A)
0.365;-2137.5
(36)(2A)
0.287;-1931.2
3(29A)
0.363;-2175.0
3J(2A)
0.346;-2037.5
(245A)
0.337;-2381.2
(249A)
0.265;-2106.2
(24KA)
0.354;-1831.2
46(2A)
0.258;-2312.5
(49)(2A)
0.297;-1656.2
4(2QA)
0.328;-1900.0
6(25A)
0.313;-2243.8
T(25A)
0.273;-1968.7
5(26A)
0.353;-2243.8
58(2A)
0.277;-2106.2
(5J)(2A)
0.347;-1450.0
6(26A)
0.366;-1725.0
T(26A)
0.339;-1900.0
6(27A)
0.293;-2106.2
69(2A)
0.310;-1968.7
(6Q)(2A)
0.383;-1312.5
(279A)
0.339;-1900.0
(27KA)
0.299;-1625.0
79(2A)
0.327;-1900.0
(7Q)(2A)
0.345;-1243.8
(28TA)
0.284;-1762.5
88(2A)
0.309;-1450.0
(8J)(2A)
0.385;-1243.8
9(29A)
0.409;-1312.5
K(29A)
0.341;-1487.5
9(2QA)
0.392;-1556.2
J(2TA)
0.351;-1556.2
TJ(2A)
0.378;-1556.2
(2JQA)
0.340;-1418.7
J(2KA)
0.316;-1350.0
(QK)(2A)
0.434;-831.2
22(4A)
0.328;-2137.5
226A
0.317;-2450.0
2A(29)
0.354;-1793.7
22(QA)
0.394;-1587.5
2(34A)
0.289;-2518.8
26(3A)
0.355;-2381.2
(29)(3A)
0.335;-1725.0
2(3QA)
0.334;-1968.7
A(234)
0.258;-2518.8
(23)(7A)
0.397;-1862.5
9A(23)
0.331;-2175.0
A(23Q)
0.303;-1968.7
2A(34)
0.265;-2518.8
2A(36)
0.300;-2381.2
2A(38)
0.330;-2243.8
2A(3T)
0.296;-2106.2
2A(3Q)
0.289;-1968.7
2(45A)
0.278;-2381.2
27(4A)
0.333;-2243.8
(2T)(4A)
0.372;-1587.5
2(4KA)
0.337;-1831.2
A(246)
0.366;-2312.5
(24)(9A)
0.342;-1656.2
JA(24)
0.288;-1968.7
24(5A)
0.292;-2381.2
24(7A)
0.265;-2243.8
24(9A)
0.367;-2106.2
24(JA)
0.356;-1968.7
24(KA)
0.347;-1831.2
26(5A)
0.346;-2243.8
(29)(5A)
0.327;-1587.5
2(5QA)
0.327;-1831.2
A(256)
0.347;-2243.8
(25)(9A)
0.390;-1587.5
JA(25)
0.337;-1900.0
25(6A)
0.261;-2243.8
25(8A)
0.289;-2106.2
25(TA)
0.326;-1968.7
25(QA)
0.353;-1831.2
(26)(6A)
0.354;-1275.0
2(69A)
0.369;-1968.7
2J(6A)
0.407;-1831.2
(26)(7A)
0.299;-1656.2
9A(26)
0.317;-1968.7
A(26Q)
0.366;-1762.5
2A(67)
0.368;-2106.2
2A(69)
0.335;-1968.7
2A(6J)
0.360;-1831.2
2A(6K)
0.314;-1693.7
(29)(7A)
0.325;-1450.0
2(7QA)
0.374;-1693.7
A(278)
0.283;-1968.7
(27)(JA)
0.356;-1312.5
KA(27)
0.315;-1625.0
2A(79)
0.318;-1900.0
2A(7J)
0.345;-1762.5
2A(7K)
0.315;-1625.0
(2T)(8A)
0.388;-1312.5
2(8KA)
0.379;-1556.2
A(28T)
0.342;-1762.5
(28)(KA)
0.429;-1106.2
28(TA)
0.322;-1762.5
28(QA)
0.313;-1625.0
(29)(9A)
0.442;-862.5
2(9QA)
0.287;-1556.2
A(29T)
0.285;-1693.7
(29)(KA)
0.347;-1037.5
29(JA)
0.371;-1625.0
29(KA)
0.381;-1487.5
2J(TA)
0.409;-1556.2
(2T)(JA)
0.420;-1106.2
KA(2T)
0.412;-1418.7
2A(TQ)
0.308;-1487.5
2(JQA)
0.314;-1418.7
A(2JQ)
0.313;-1418.7
2A(JQ)
0.357;-1418.7
2(QKA)
0.304;-1281.2
2Q(KA)
0.327;-1281.2
33(3A)
0.346;-1618.7
(36)(3A)
0.416;-1412.5
3(39A)
0.356;-1656.2
3J(3A)
0.315;-1518.7
(345A)
0.349;-2312.5
(349A)
0.263;-2037.5
(34KA)
0.349;-1762.5
46(3A)
0.270;-2243.8
(49)(3A)
0.321;-1587.5
4(3QA)
0.327;-1831.2
6(35A)
0.317;-2175.0
T(35A)
0.366;-1900.0
5(36A)
0.351;-2175.0
58(3A)
0.300;-2037.5
(5J)(3A)
0.337;-1381.2
6(36A)
0.371;-1656.2
T(36A)
0.351;-1831.2
6(37A)
0.364;-2037.5
69(3A)
0.387;-1900.0
(6Q)(3A)
0.287;-1243.8
(379A)
0.375;-1831.2
(37KA)
0.338;-1556.2
79(3A)
0.274;-1831.2
(7Q)(3A)
0.338;-1175.0
(38TA)
0.302;-1693.7
88(3A)
0.356;-1381.2
(8J)(3A)
0.368;-1175.0
9(39A)
0.411;-1243.8
K(39A)
0.389;-1418.7
9(3QA)
0.408;-1487.5
J(3TA)
0.325;-1487.5
TJ(3A)
0.386;-1487.5
(3JQA)
0.361;-1350.0
J(3KA)
0.408;-1281.2
(QK)(3A)
0.372;-762.5
33(5A)
0.321;-1931.2
337A
0.385;-2243.8
3A(3T)
0.368;-1587.5
33(KA)
0.317;-1381.2
3(46A)
0.351;-2243.8
38(4A)
0.313;-2106.2
(3J)(4A)
0.320;-1450.0
4A(34)
0.330;-1931.2
A(347)
0.381;-2175.0
(34)(TA)
0.346;-1518.7
QA(34)
0.354;-1831.2
345A
0.302;-2762.5
347A
0.315;-2625.0
349A
0.346;-2487.5
34JA
0.335;-2350.0
34KA
0.367;-2212.5
37(5A)
0.282;-2106.2
(3T)(5A)
0.403;-1450.0
3(5KA)
0.313;-1693.7
A(357)
0.337;-2106.2
(35)(TA)
0.357;-1450.0
QA(35)
0.329;-1762.5
356A
0.300;-2625.0
358A
0.334;-2487.5
35TA
0.318;-2350.0
35QA
0.268;-2212.5
(37)(6A)
0.357;-1587.5
3(6TA)
0.360;-1831.2
3Q(6A)
0.333;-1693.7
(36)(8A)
0.340;-1518.7
TA(36)
0.287;-1831.2
A(36K)
0.360;-1625.0
6A(38)
0.421;-1968.7
6A(3T)
0.371;-1831.2
6A(3Q)
0.333;-1693.7
37(7A)
0.340;-1518.7
(3T)(7A)
0.347;-1312.5
3(7KA)
0.346;-1556.2
A(379)
0.338;-1831.2
(37)(QA)
0.388;-1175.0
7A(38)
0.348;-1900.0
7A(3T)
0.353;-1762.5
7A(3Q)
0.372;-1625.0
38(8A)
0.424;-1381.2
(3J)(8A)
0.330;-1175.0
8A(38)
0.376;-1381.2
A(38J)
0.350;-1625.0
388A
0.333;-1831.2
38TA
0.352;-2143.8
38QA
0.385;-2006.2
(3T)(9A)
0.351;-1175.0
3(9KA)
0.321;-1418.7
A(39J)
0.375;-1556.2
399A
0.390;-1693.7
39JA
0.321;-2006.2
39KA
0.338;-1868.7
3Q(TA)
0.389;-1418.7
(3T)(QA)
0.340;-968.7
TA(3J)
0.338;-1487.5
TA(3K)
0.400;-1350.0
3(JKA)
0.414;-1281.2
A(3JK)
0.313;-1281.2
JA(3K)
0.309;-1281.2
QA(3Q)
0.395;-831.2
3QKA
0.362;-1662.5
45(4A)
0.349;-1793.7
(48)(4A)
0.363;-1137.5
4(4JA)
0.300;-1381.2
4K(4A)
0.360;-1243.8
(459A)
0.347;-1900.0
(45KA)
0.367;-1625.0
57(4A)
0.261;-2037.5
(5T)(4A)
0.307;-1381.2
5(4KA)
0.361;-1625.0
(469A)
0.376;-1831.2
(46KA)
0.347;-1556.2
68(4A)
0.343;-1900.0
(6J)(4A)
0.360;-1243.8
7(47A)
0.363;-1450.0
J(47A)
0.350;-1625.0
78(4A)
0.387;-1831.2
(7J)(4A)
0.388;-1175.0
8(48A)
0.310;-1312.5
Q(48A)
0.328;-1487.5
(8T)(4A)
0.347;-1175.0
8(4KA)
0.376;-1418.7
(49QA)
0.378;-1418.7
9(4JA)
0.385;-1487.5
9K(4A)
0.329;-1350.0
TT(4A)
0.382;-1037.5
(TK)(4A)
0.380;-831.2
J(4QA)
0.304;-1281.2
K(4QA)
0.358;-1143.7
44(5A)
0.411;-1793.7
447A
0.332;-2106.2
4A(4T)
0.339;-1450.0
44(KA)
0.297;-1243.8
4(57A)
0.318;-2037.5
49(5A)
0.345;-1900.0
(4Q)(5A)
0.340;-1243.8
6A(45)
0.309;-2106.2
A(459)
0.344;-1900.0
(45)(QA)
0.288;-1243.8
5A(46)
0.328;-2106.2
5A(48)
0.281;-1968.7
5A(4T)
0.341;-1831.2
5A(4Q)
0.324;-1693.7
46(6A)
0.314;-1587.5
(49)(6A)
0.319;-1381.2
4(6QA)
0.370;-1625.0
A(467)
0.325;-1968.7
(46)(TA)
0.374;-1312.5
QA(46)
0.359;-1625.0
467A
0.256;-2418.7
469A
0.336;-2281.2
46JA
0.332;-2143.8
46KA
0.339;-2006.2
49(7A)
0.343;-1762.5
(4Q)(7A)
0.366;-1106.2
8A(47)
0.343;-1831.2
A(47J)
0.303;-1625.0
477A
0.338;-1900.0
479A
0.307;-2212.5
47JA
0.304;-2075.0
47KA
0.285;-1937.5
4T(8A)
0.372;-1625.0
(4K)(8A)
0.365;-968.7
TA(48)
0.281;-1625.0
A(48K)
0.334;-1418.7
8A(4T)
0.275;-1625.0
8A(4Q)
0.342;-1487.5
49(9A)
0.300;-1175.0
(4Q)(9A)
0.364;-968.7
TA(49)
0.359;-1556.2
A(49K)
0.389;-1350.0
9A(4J)
0.379;-1487.5
9A(4K)
0.316;-1350.0
4(TQA)
0.409;-1350.0
A(4TJ)
0.310;-1418.7
4TTA
0.413;-1487.5
4TQA
0.336;-1800.0
(4Q)(JA)
0.365;-831.2
QA(4J)
0.367;-1281.2
4JQA
0.291;-1731.2
(4K)(QA)
0.358;-693.8
QA(4K)
0.424;-1143.7
5(56A)
0.343;-1587.5
58(5A)
0.341;-1450.0
(5J)(5A)
0.417;-793.7
6(56A)
0.419;-1518.7
T(56A)
0.350;-1693.7
6(57A)
0.363;-1900.0
69(5A)
0.335;-1762.5
(6Q)(5A)
0.337;-1106.2
(579A)
0.334;-1693.7
(57KA)
0.354;-1418.7
79(5A)
0.270;-1693.7
(7Q)(5A)
0.352;-1037.5
(58TA)
0.324;-1556.2
88(5A)
0.302;-1243.8
(8J)(5A)
0.392;-1037.5
9(59A)
0.304;-1106.2
K(59A)
0.341;-1281.2
9(5QA)
0.313;-1350.0
J(5TA)
0.383;-1350.0
TJ(5A)
0.390;-1350.0
(5JQA)
0.388;-1212.5
J(5KA)
0.396;-1143.7
(QK)(5A)
0.349;-625.0
55(7A)
0.347;-1518.7
559A
0.293;-1831.2
5A(5Q)
0.355;-1175.0
(57)(6A)
0.360;-1450.0
5(6TA)
0.362;-1693.7
5Q(6A)
0.316;-1556.2
(56)(8A)
0.393;-1381.2
TA(56)
0.283;-1693.7
A(56K)
0.383;-1487.5
6A(58)
0.367;-1831.2
6A(5T)
0.351;-1693.7
6A(5Q)
0.372;-1556.2
57(7A)
0.298;-1381.2
(5T)(7A)
0.421;-1175.0
5(7KA)
0.369;-1418.7
A(579)
0.307;-1693.7
(57)(QA)
0.355;-1037.5
7A(58)
0.324;-1762.5
7A(5T)
0.331;-1625.0
7A(5Q)
0.377;-1487.5
58(8A)
0.311;-1243.8
(5J)(8A)
0.341;-1037.5
8A(58)
0.336;-1243.8
A(58J)
0.385;-1487.5
588A
0.305;-1693.7
58TA
0.287;-2006.2
58QA
0.344;-1868.7
(5T)(9A)
0.347;-1037.5
5(9KA)
0.301;-1281.2
A(59J)
0.333;-1418.7
599A
0.287;-1556.2
59JA
0.342;-1868.7
59KA
0.336;-1731.2
5Q(TA)
0.353;-1281.2
(5T)(QA)
0.300;-831.2
TA(5J)
0.325;-1350.0
TA(5K)
0.319;-1212.5
5(JKA)
0.377;-1143.7
A(5JK)
0.303;-1143.7
JA(5K)
0.340;-1143.7
QA(5Q)
0.352;-693.8
5QKA
0.348;-1525.0
67(6A)
0.410;-1381.2
(6T)(6A)
0.355;-725.0
6(6KA)
0.336;-968.7
(67TA)
0.401;-1556.2
77(6A)
0.436;-1312.5
(7T)(6A)
0.338;-1106.2
7(6KA)
0.413;-1350.0
(68JA)
0.369;-1418.7
(89)(6A)
0.346;-1106.2
8(6QA)
0.341;-1350.0
T(69A)
0.303;-1418.7
9(6TA)
0.304;-1418.7
9Q(6A)
0.307;-1281.2
Q(6TA)
0.351;-1212.5
(TQ)(6A)
0.364;-762.5
(6JKA)
0.395;-1075.0
JK(6A)
0.348;-1075.0
K(6KA)
0.345;-487.5
668A
0.329;-1762.5
6A(6J)
0.354;-1106.2
(67)(7A)
0.397;-862.5
6(7TA)
0.394;-1556.2
6Q(7A)
0.304;-1418.7
(67)(9A)
0.375;-1175.0
JA(67)
0.335;-1487.5
67(8A)
0.369;-1693.7
67(TA)
0.307;-1556.2
67(QA)
0.368;-1418.7
(68)(8A)
0.324;-725.0
6(8JA)
0.396;-1418.7
6K(8A)
0.309;-1281.2
(68)(JA)
0.332;-968.7
KA(68)
0.397;-1281.2
6A(8T)
0.370;-1487.5
6A(8Q)
0.365;-1350.0
6(9TA)
0.347;-1418.7
6Q(9A)
0.347;-1281.2
(69)(JA)
0.338;-900.0
KA(69)
0.376;-1212.5
6A(9J)
0.311;-1350.0
6A(9K)
0.333;-1212.5
(6Q)(TA)
0.452;-762.5
JA(6T)
0.418;-1281.2
6T(JA)
0.315;-1281.2
6T(KA)
0.390;-1143.7
6Q(JA)
0.414;-1143.7
(6J)(KA)
0.368;-625.0
6J(KA)
0.360;-1075.0
6K(QA)
0.377;-1006.2
6A(QK)
0.378;-1006.2
(78)(7A)
0.407;-725.0
7(7JA)
0.334;-968.7
7K(7A)
0.320;-831.2
(78QA)
0.305;-1281.2
8(7TA)
0.355;-1418.7
8Q(7A)
0.335;-1281.2
J(79A)
0.314;-1281.2
9T(7A)
0.376;-1350.0
(9K)(7A)
0.371;-693.8
K(7TA)
0.412;-1075.0
T(7KA)
0.401;-1075.0
JJ(7A)
0.395;-693.8
(7QKA)
0.374;-937.5
777A
0.370;-1243.8
7A(7T)
0.399;-1037.5
77(KA)
0.349;-831.2
7(8TA)
0.407;-1418.7
7Q(8A)
0.338;-1281.2
(78)(TA)
0.426;-968.7
QA(78)
0.343;-1281.2
789A
0.337;-1937.5
78JA
0.279;-1800.0
78KA
0.355;-1662.5
7J(9A)
0.361;-1281.2
(79)(TA)
0.372;-900.0
QA(79)
0.357;-1212.5
79TA
0.321;-1800.0
79QA
0.358;-1662.5
(7J)(TA)
0.400;-762.5
TA(7T)
0.364;-831.2
A(7TK)
0.334;-1075.0
TA(7Q)
0.345;-1143.7
7J(JA)
0.391;-693.8
(7J)(QA)
0.407;-625.0
JA(7Q)
0.409;-1075.0
7Q(QA)
0.410;-556.2
7QQA
0.346;-1006.2
7KKA
0.363;-868.8
8(8JA)
0.393;-831.2
8K(8A)
0.447;-693.8
(89KA)
0.345;-1075.0
9J(8A)
0.412;-1212.5
(8TJA)
0.380;-1143.7
(TJ)(8A)
0.358;-693.8
J(8JA)
0.353;-625.0
JQ(8A)
0.332;-1006.2
Q(8KA)
0.372;-868.8
889A
0.340;-1418.7
8A(8Q)
0.348;-762.5
(8T)(9A)
0.348;-831.2
8(9KA)
0.384;-1075.0
A(89J)
0.374;-1212.5
899A
0.375;-1350.0
89JA
0.394;-1662.5
89KA
0.323;-1525.0
8Q(TA)
0.334;-1075.0
(8T)(QA)
0.320;-625.0
TA(8J)
0.376;-1143.7
TA(8K)
0.367;-1006.2
8(JKA)
0.335;-937.5
A(8JK)
0.342;-937.5
JA(8K)
0.297;-937.5
QA(8Q)
0.336;-487.5
8QKA
0.322;-1318.7
9T(9A)
0.320;-762.5
(9K)(9A)
0.393;-106.2
K(9TA)
0.345;-937.5
T(9KA)
0.423;-937.5
JJ(9A)
0.380;-556.2
(9QKA)
0.384;-800.0
999A
0.355;-831.2
9A(9Q)
0.324;-625.0
(9J)(TA)
0.335;-625.0
TA(9T)
0.387;-693.8
A(9TK)
0.377;-937.5
TA(9Q)
0.417;-1006.2
9J(JA)
0.376;-556.2
(9J)(QA)
0.397;-487.5
JA(9Q)
0.345;-937.5
9Q(QA)
0.416;-418.8
9QQA
0.358;-868.8
9KKA
0.363;-731.2
T(TKA)
0.445;-418.8
JJ(TA)
0.397;-487.5
(TQKA)
0.384;-731.2
TTTA
0.412;-625.0
TA(TK)
0.349;-418.8
(TK)(JA)
0.376;-350.0
KA(TJ)
0.370;-800.0
TA(JK)
0.334;-800.0
(TQ)(KA)
0.417;-281.3
(TK)(KA)
0.402;237.5
J(JKA)
0.396;-281.3
(QK)(JA)
0.402;-212.5
JJ(KA)
0.369;-281.3
QA(JQ)
0.411;-281.3
JQKA
0.379;-1112.5
QK(QA)
0.422;-143.8
QK(KA)
0.391;-75.0
22(24)
0.282;-2512.5
22(28)
0.341;-2237.5
22(2Q)
0.289;-1962.5
24(23)
0.295;-2893.8
(23)(27)
0.328;-2237.5
2(23T)
0.329;-2481.2
2Q(23)
0.300;-2343.8
23(25)
0.250;-2825.0
2237
0.227;-3137.5
22(3T)
0.299;-2481.2
23(2K)
0.250;-2275.0
2(246)
0.243;-2687.5
28(24)
0.298;-2550.0
(24)(2J)
0.373;-1893.7
2244
0.243;-2825.0
22(47)
0.283;-2618.8
24(2T)
0.353;-2412.5
224Q
0.289;-2725.0
26(25)
0.276;-2618.8
(25)(29)
0.301;-1962.5
2(25Q)
0.342;-2206.2
22(56)
0.339;-2618.8
25(29)
0.290;-2412.5
225J
0.288;-2725.0
26(26)
0.358;-2100.0
(26)(29)
0.304;-1893.7
2(26Q)
0.301;-2137.5
22(67)
0.243;-2481.2
26(2T)
0.296;-2275.0
226Q
0.298;-2587.5
28(27)
0.345;-2343.8
(27)(2J)
0.345;-1687.5
2277
0.348;-2412.5
22(7T)
0.281;-2206.2
27(2K)
0.378;-2000.0
2(28T)
0.334;-2137.5
2Q(28)
0.322;-2000.0
28(2T)
0.298;-2137.5
228Q
0.286;-2450.0
2T(29)
0.349;-2068.7
(29)(2K)
0.311;-1412.5
229J
0.333;-2450.0
2T(2T)
0.407;-1550.0
(2T)(2K)
0.365;-1343.7
22TQ
0.272;-2312.5
2Q(2J)
0.343;-1793.7
2J(2K)
0.389;-1725.0
22QQ
0.342;-1725.0
3(234)
0.284;-2825.0
36(23)
0.320;-2687.5
(23)(39)
0.348;-2031.2
3(23Q)
0.267;-2275.0
5(234)
0.232;-3137.5
9(234)
0.259;-2862.5
K(234)
0.356;-2587.5
4(237)
0.309;-3000.0
49(23)
0.276;-2862.5
(23)(4Q)
0.339;-2206.2
(2357)
0.269;-2931.2
(235J)
0.226;-2656.2
(23)(56)
0.350;-2550.0
5(239)
0.267;-2793.7
5J(23)
0.253;-2656.2
(2367)
0.250;-2862.5
(236J)
0.294;-2587.5
(23)(67)
0.296;-2412.5
6(23T)
0.294;-2656.2
6Q(23)
0.245;-2518.8
9(237)
0.258;-2656.2
K(237)
0.321;-2381.2
7(23T)
0.283;-2587.5
7Q(23)
0.284;-2450.0
T(238)
0.293;-2518.8
8(239)
0.367;-2587.5
8J(23)
0.376;-2450.0
(239T)
0.352;-2450.0
99(23)
0.381;-2068.7
(23)(9Q)
0.337;-1862.5
(23TQ)
0.319;-2243.8
T(23Q)
0.357;-2243.8
Q(23J)
0.359;-2175.0
(23)(JK)
0.405;-1656.2
QK(23)
0.335;-2037.5
23(35)
0.304;-2756.2
33(28)
0.320;-2550.0
233T
0.236;-2862.5
23(3K)
0.378;-2206.2
(24)(36)
0.280;-2618.8
3(249)
0.227;-2862.5
3J(24)
0.348;-2725.0
(34)(25)
0.314;-2687.5
27(34)
0.337;-3000.0
2(34T)
0.260;-2793.7
(34)(2K)
0.327;-2137.5
34(26)
0.249;-3068.7
34(28)
0.273;-2931.2
34(2T)
0.318;-2793.7
34(2Q)
0.312;-2656.2
(25)(35)
0.381;-2168.8
3(258)
0.288;-2862.5
3T(25)
0.296;-2725.0
(25)(3K)
0.302;-2068.7
27(35)
0.363;-2931.2
2(35T)
0.316;-2725.0
(35)(2K)
0.279;-2068.7
35(27)
0.226;-2931.2
35(29)
0.343;-2793.7
35(2J)
0.244;-2656.2
35(2K)
0.290;-2518.8
37(26)
0.342;-2862.5
(26)(3T)
0.352;-2206.2
3(26K)
0.343;-2450.0
2(368)
0.300;-2793.7
(36)(2J)
0.292;-2137.5
2K(36)
0.301;-2450.0
23(68)
0.244;-2793.7
23(6T)
0.359;-2656.2
23(6Q)
0.257;-2518.8
3(278)
0.289;-2725.0
3T(27)
0.336;-2587.5
(27)(3K)
0.320;-1931.2
29(37)
0.325;-2656.2
2(37Q)
0.293;-2450.0
23(78)
0.265;-2725.0
23(7T)
0.262;-2587.5
23(7Q)
0.297;-2450.0
3(289)
0.307;-2587.5
3J(28)
0.296;-2450.0
(38)(29)
0.281;-2137.5
2J(38)
0.293;-2450.0
38(29)
0.248;-2587.5
38(2J)
0.294;-2450.0
38(2K)
0.356;-2312.5
3T(29)
0.261;-2450.0
(29)(3K)
0.361;-1793.8
2J(39)
0.257;-2381.2
39(2T)
0.340;-2450.0
39(2Q)
0.394;-2312.5
(2T)(3T)
0.365;-1481.2
3(2TK)
0.356;-2175.0
2(3TQ)
0.347;-2243.8
23(TJ)
0.383;-2312.5
23(TK)
0.361;-2175.0
(2J)(3K)
0.310;-1656.2
2K(3J)
0.329;-2106.2
23(JK)
0.355;-2106.2
(3Q)(2K)
0.415;-1587.5
(2K)(3K)
0.431;-1068.8
4(246)
0.323;-2550.0
48(24)
0.333;-2412.5
(24)(4J)
0.388;-1756.3
5(245)
0.292;-2550.0
9(245)
0.273;-2725.0
K(245)
0.335;-2450.0
5(248)
0.228;-2793.7
5T(24)
0.333;-2656.2
(24)(5K)
0.393;-2000.0
9(246)
0.338;-2656.2
K(246)
0.372;-2381.2
6(249)
0.274;-2656.2
6J(24)
0.360;-2518.8
(2478)
0.271;-2656.2
(247Q)
0.284;-2381.2
7(249)
0.265;-2587.5
7J(24)
0.251;-2450.0
(2489)
0.288;-2518.8
(248K)
0.330;-2243.8
8T(24)
0.291;-2450.0
(24)(8K)
0.317;-1793.8
Q(249)
0.284;-2243.8
(24)(9J)
0.322;-1862.5
T(24T)
0.335;-1862.5
T(24J)
0.299;-2243.8
TK(24)
0.316;-2106.2
(24)(JQ)
0.352;-1656.2
QQ(24)
0.314;-1587.5
24(45)
0.298;-2618.8
44(28)
0.284;-2412.5
244T
0.312;-2725.0
24(4K)
0.304;-2068.7
(25)(47)
0.281;-2412.5
4(25T)
0.262;-2656.2
4Q(25)
0.318;-2518.8
(45)(27)
0.349;-2412.5
29(45)
0.301;-2725.0
2(45Q)
0.326;-2518.8
24(56)
0.269;-2931.2
24(58)
0.282;-2793.7
24(5T)
0.247;-2656.2
24(5Q)
0.355;-2518.8
4(267)
0.272;-2793.7
49(26)
0.324;-2656.2
(26)(4Q)
0.319;-2000.0
27(46)
0.280;-2793.7
2(46T)
0.296;-2587.5
(46)(2K)
0.319;-1931.2
46(28)
0.253;-2725.0
46(2T)
0.247;-2587.5
46(2Q)
0.269;-2450.0
(27)(47)
0.285;-1825.0
4(27T)
0.328;-2518.8
4Q(27)
0.373;-2381.2
(47)(29)
0.283;-2137.5
2J(47)
0.290;-2450.0
47(28)
0.280;-2656.2
47(2T)
0.256;-2518.8
47(2Q)
0.372;-2381.2
(28)(48)
0.368;-1687.5
4(28J)
0.267;-2381.2
4K(28)
0.323;-2243.8
(48)(2J)
0.347;-1931.2
2K(48)
0.335;-2243.8
24(8T)
0.286;-2450.0
24(8Q)
0.284;-2312.5
4(29T)
0.349;-2381.2
4Q(29)
0.306;-2243.8
(49)(2J)
0.298;-1862.5
2K(49)
0.289;-2175.0
24(9J)
0.327;-2312.5
24(9K)
0.376;-2175.0
(2T)(4Q)
0.302;-1725.0
2J(4T)
0.282;-2243.8
4T(2J)
0.289;-2243.8
4T(2K)
0.357;-2106.2
4Q(2J)
0.368;-2106.2
(4J)(2K)
0.382;-1587.5
4J(2K)
0.348;-2037.5
4K(2Q)
0.332;-1968.7
24(QK)
0.319;-1968.7
(25)(56)
0.375;-1962.5
5(259)
0.318;-2206.2
5J(25)
0.342;-2068.7
(2567)
0.317;-2725.0
(256J)
0.262;-2450.0
(25)(67)
0.314;-2275.0
6(25T)
0.312;-2518.8
6Q(25)
0.256;-2381.2
9(257)
0.309;-2518.8
K(257)
0.286;-2243.8
7(25T)
0.298;-2450.0
7Q(25)
0.259;-2312.5
T(258)
0.351;-2381.2
8(259)
0.381;-2450.0
8J(25)
0.355;-2312.5
(259T)
0.344;-2312.5
99(25)
0.343;-1931.2
(25)(9Q)
0.289;-1725.0
(25TQ)
0.264;-2106.2
T(25Q)
0.289;-2106.2
Q(25J)
0.367;-2037.5
(25)(JK)
0.325;-1518.7
QK(25)
0.323;-1900.0
25(57)
0.269;-2343.8
55(2T)
0.385;-2137.5
255Q
0.305;-2450.0
57(26)
0.301;-2725.0
(26)(5T)
0.334;-2068.7
5(26K)
0.327;-2312.5
2(568)
0.323;-2656.2
(56)(2J)
0.362;-2000.0
2K(56)
0.389;-2312.5
25(68)
0.315;-2656.2
25(6T)
0.338;-2518.8
25(6Q)
0.378;-2381.2
5(278)
0.300;-2587.5
5T(27)
0.237;-2450.0
(27)(5K)
0.372;-1793.8
29(57)
0.274;-2518.8
2(57Q)
0.311;-2312.5
25(78)
0.331;-2587.5
25(7T)
0.313;-2450.0
25(7Q)
0.296;-2312.5
5(289)
0.247;-2450.0
5J(28)
0.320;-2312.5
(58)(29)
0.371;-2000.0
2J(58)
0.300;-2312.5
58(29)
0.351;-2450.0
58(2J)
0.320;-2312.5
58(2K)
0.341;-2175.0
5T(29)
0.338;-2312.5
(29)(5K)
0.345;-1656.2
2J(59)
0.268;-2243.8
59(2T)
0.306;-2312.5
59(2Q)
0.354;-2175.0
(2T)(5T)
0.338;-1343.7
5(2TK)
0.365;-2037.5
2(5TQ)
0.318;-2106.2
25(TJ)
0.311;-2175.0
25(TK)
0.389;-2037.5
(2J)(5K)
0.349;-1518.7
2K(5J)
0.309;-1968.7
25(JK)
0.330;-1968.7
(5Q)(2K)
0.382;-1450.0
(2K)(5K)
0.373;-931.2
6(268)
0.336;-2137.5
6T(26)
0.322;-2000.0
(26)(6K)
0.298;-1343.7
T(267)
0.348;-2381.2
7(268)
0.339;-2518.8
7T(26)
0.290;-2381.2
(26)(7K)
0.335;-1725.0
J(268)
0.278;-2243.8
89(26)
0.364;-2381.2
(26)(8Q)
0.323;-1725.0
(269J)
0.327;-2175.0
(26)(9T)
0.364;-1793.8
9(26K)
0.381;-2037.5
(26TK)
0.314;-1968.7
TQ(26)
0.348;-2037.5
K(26J)
0.334;-1900.0
Q(26Q)
0.355;-1450.0
KK(26)
0.379;-1312.5
66(29)
0.329;-2068.7
266J
0.373;-2381.2
67(27)
0.348;-2137.5
(27)(6T)
0.410;-1931.2
6(27K)
0.329;-2175.0
2(679)
0.302;-2450.0
(67)(2Q)
0.332;-1793.8
27(68)
0.322;-2518.8
27(6T)
0.331;-2381.2
27(6Q)
0.281;-2243.8
68(28)
0.283;-2000.0
(28)(6J)
0.358;-1793.8
28(68)
0.291;-2000.0
2(68J)
0.337;-2243.8
2688
0.347;-2450.0
268T
0.354;-2762.5
268Q
0.326;-2625.0
(29)(6T)
0.322;-1793.8
6(29K)
0.341;-2037.5
2(69J)
0.328;-2175.0
2699
0.321;-2312.5
269J
0.317;-2625.0
269K
0.314;-2487.5
6Q(2T)
0.331;-2037.5
(6T)(2Q)
0.377;-1587.5
2T(6J)
0.286;-2106.2
2T(6K)
0.350;-1968.7
6(2JK)
0.319;-1900.0
2(6JK)
0.344;-1900.0
2J(6K)
0.324;-1900.0
2Q(6Q)
0.369;-1450.0
26QK
0.308;-2281.2
78(27)
0.337;-2000.0
(27)(7J)
0.287;-1343.7
8(278)
0.338;-1931.2
Q(278)
0.339;-2106.2
(27)(8T)
0.391;-1793.8
8(27K)
0.270;-2037.5
(279Q)
0.319;-2037.5
9(27J)
0.382;-2106.2
9K(27)
0.279;-1968.7
TT(27)
0.347;-1656.2
(27)(TK)
0.389;-1450.0
J(27Q)
0.393;-1900.0
K(27Q)
0.405;-1762.5
77(28)
0.291;-2000.0
277T
0.399;-2312.5
27(7K)
0.314;-1656.2
(28)(7T)
0.361;-1793.8
7(28K)
0.359;-2037.5
2(78T)
0.294;-2243.8
(78)(2K)
0.418;-1587.5
78(2T)
0.382;-2243.8
78(2Q)
0.380;-2106.2
(29)(79)
0.361;-1343.7
7(29Q)
0.326;-2037.5
2(79T)
0.304;-2175.0
(79)(2K)
0.362;-1518.7
79(2J)
0.347;-2106.2
79(2K)
0.336;-1968.7
7J(2T)
0.334;-2037.5
(7T)(2J)
0.354;-1587.5
2K(7T)
0.346;-1900.0
27(TQ)
0.258;-1968.7
7(2JQ)
0.329;-1900.0
2(7JQ)
0.358;-1900.0
27(JQ)
0.391;-1900.0
7(2QK)
0.330;-1762.5
7Q(2K)
0.331;-1762.5
88(28)
0.310;-1412.5
(28)(8J)
0.318;-1206.2
9(289)
0.347;-1725.0
K(289)
0.314;-1900.0
9(28Q)
0.325;-1968.7
J(28T)
0.367;-1968.7
TJ(28)
0.329;-1968.7
(28JQ)
0.339;-1831.2
J(28K)
0.363;-1762.5
(28)(QK)
0.382;-1243.8
88(2T)
0.359;-1725.0
288Q
0.334;-2037.5
8T(29)
0.277;-2106.2
(29)(8K)
0.342;-1450.0
2J(89)
0.315;-2037.5
89(2T)
0.353;-2106.2
89(2Q)
0.419;-1968.7
(2T)(8T)
0.372;-1137.5
8(2TK)
0.311;-1831.2
2(8TQ)
0.361;-1900.0
28(TJ)
0.305;-1968.7
28(TK)
0.343;-1831.2
(2J)(8K)
0.326;-1312.5
2K(8J)
0.397;-1762.5
28(JK)
0.311;-1762.5
(8Q)(2K)
0.400;-1243.8
(2K)(8K)
0.401;-725.0
9(29J)
0.355;-1518.7
9K(29)
0.358;-1381.2
TT(29)
0.333;-1518.7
(29)(TK)
0.330;-1312.5
J(29Q)
0.311;-1762.5
K(29Q)
0.345;-1625.0
99(2T)
0.348;-1587.5
299Q
0.378;-1900.0
9J(2T)
0.365;-1900.0
(9T)(2J)
0.309;-1450.0
2K(9T)
0.346;-1762.5
29(TQ)
0.332;-1831.2
9(2JQ)
0.361;-1762.5
2(9JQ)
0.294;-1762.5
29(JQ)
0.287;-1762.5
9(2QK)
0.352;-1625.0
9Q(2K)
0.292;-1625.0
TT(2T)
0.378;-1000.0
(2T)(TK)
0.437;-793.7
J(2TQ)
0.342;-1693.7
K(2TQ)
0.340;-1556.2
TT(2J)
0.323;-1381.2
2TTK
0.399;-1693.7
TK(2J)
0.333;-1625.0
2TJJ
0.316;-1762.5
2TJK
0.341;-2075.0
2(TQK)
0.366;-1556.2
TK(2K)
0.302;-1037.5
(2J)(JK)
0.368;-656.3
QK(2J)
0.352;-1487.5
2J(JK)
0.316;-1106.2
(JQ)(2K)
0.350;-1037.5
(2K)(JK)
0.430;-518.7
K(2QK)
0.414;-900.0
2K(QK)
0.332;-900.0
3335
0.323;-2687.5
3339
0.293;-2412.5
333K
0.318;-2137.5
36(34)
0.333;-2550.0
(34)(39)
0.308;-1893.7
3(34Q)
0.281;-2137.5
33(45)
0.249;-2618.8
34(38)
0.297;-2412.5
334T
0.320;-2725.0
33(4K)
0.339;-2068.7
(35)(37)
0.402;-1962.5
3(35T)
0.290;-2206.2
3Q(35)
0.336;-2068.7
35(37)
0.314;-2412.5
3359
0.339;-2725.0
33(5Q)
0.318;-2068.7
(36)(37)
0.295;-1893.7
3(36T)
0.285;-2137.5
3Q(36)
0.313;-2000.0
36(38)
0.330;-2275.0
336T
0.289;-2587.5
33(6K)
0.312;-1931.2
(37)(39)
0.299;-1687.5
3(37Q)
0.287;-1931.2
33(78)
0.312;-2206.2
37(3J)
0.291;-2000.0
337K
0.331;-2312.5
3T(38)
0.312;-2000.0
(38)(3K)
0.407;-1343.7
338T
0.291;-2450.0
33(8K)
0.329;-1793.7
(39)(3J)
0.388;-1412.5
3399
0.271;-2000.0
33(9Q)
0.317;-1793.7
(3T)(3J)
0.370;-1343.7
33TT
0.408;-1862.5
33(TK)
0.326;-1656.2
(3J)(3K)
0.338;-1137.5
33JK
0.301;-2037.5
33(QK)
0.377;-1518.7
45(34)
0.311;-2550.0
(34)(48)
0.277;-1893.7
4(34J)
0.323;-2137.5
4K(34)
0.321;-2000.0
(3459)
0.282;-2656.2
(345K)
0.316;-2381.2
57(34)
0.268;-2793.7
(34)(5T)
0.269;-2137.5
5(34K)
0.309;-2381.2
(3469)
0.265;-2587.5
(346K)
0.276;-2312.5
68(34)
0.267;-2656.2
(34)(6J)
0.269;-2000.0
7(347)
0.296;-2206.2
J(347)
0.355;-2381.2
78(34)
0.297;-2587.5
(34)(7J)
0.320;-1931.2
8(348)
0.339;-2068.7
Q(348)
0.365;-2243.8
(34)(8T)
0.376;-1931.2
8(34K)
0.329;-2175.0
(349Q)
0.281;-2175.0
9(34J)
0.330;-2243.8
9K(34)
0.304;-2106.2
TT(34)
0.349;-1793.7
(34)(TK)
0.377;-1587.5
J(34Q)
0.376;-2037.5
K(34Q)
0.376;-1900.0
44(35)
0.298;-2550.0
3447
0.255;-2862.5
34(4T)
0.323;-2206.2
44(3K)
0.348;-2000.0
4(357)
0.232;-2793.7
49(35)
0.293;-2656.2
(35)(4Q)
0.379;-2000.0
36(45)
0.239;-2862.5
3(459)
0.271;-2656.2
(45)(3Q)
0.334;-2000.0
35(46)
0.251;-2862.5
35(48)
0.356;-2725.0
35(4T)
0.316;-2587.5
35(4Q)
0.336;-2450.0
46(36)
0.291;-2343.8
(36)(49)
0.295;-2137.5
4(36Q)
0.346;-2381.2
3(467)
0.310;-2725.0
(46)(3T)
0.316;-2068.7
3Q(46)
0.291;-2381.2
3467
0.220;-3175.0
3469
0.239;-3037.5
346J
0.287;-2900.0
346K
0.318;-2762.5
49(37)
0.287;-2518.8
(37)(4Q)
0.378;-1862.5
38(47)
0.339;-2587.5
3(47J)
0.301;-2381.2
3477
0.313;-2656.2
3479
0.324;-2968.8
347J
0.343;-2831.2
347K
0.357;-2693.7
4T(38)
0.313;-2381.2
(38)(4K)
0.350;-1725.0
3T(48)
0.302;-2381.2
3(48K)
0.369;-2175.0
38(4T)
0.354;-2381.2
38(4Q)
0.294;-2243.8
49(39)
0.383;-1931.2
(39)(4Q)
0.289;-1725.0
3T(49)
0.313;-2312.5
3(49K)
0.349;-2106.2
39(4J)
0.334;-2243.8
39(4K)
0.318;-2106.2
4(3TQ)
0.381;-2106.2
3(4TJ)
0.322;-2175.0
34TT
0.349;-2243.8
34TQ
0.285;-2556.2
(3J)(4Q)
0.381;-1587.5
3Q(4J)
0.286;-2037.5
34JQ
0.366;-2487.5
(3Q)(4K)
0.372;-1450.0
3Q(4K)
0.311;-1900.0
5(356)
0.285;-2343.8
58(35)
0.368;-2206.2
(35)(5J)
0.347;-1550.0
6(356)
0.371;-2275.0
T(356)
0.349;-2450.0
6(357)
0.257;-2656.2
69(35)
0.325;-2518.8
(35)(6Q)
0.300;-1862.5
(3579)
0.252;-2450.0
(357K)
0.287;-2175.0
79(35)
0.310;-2450.0
(35)(7Q)
0.353;-1793.8
(358T)
0.309;-2312.5
88(35)
0.359;-2000.0
(35)(8J)
0.361;-1793.8
9(359)
0.323;-1862.5
K(359)
0.348;-2037.5
9(35Q)
0.336;-2106.2
J(35T)
0.314;-2106.2
TJ(35)
0.266;-2106.2
(35JQ)
0.330;-1968.7
J(35K)
0.342;-1900.0
(35)(QK)
0.325;-1381.2
55(37)
0.298;-2275.0
3559
0.287;-2587.5
35(5Q)
0.330;-1931.2
(36)(57)
0.315;-2206.2
5(36T)
0.295;-2450.0
5Q(36)
0.257;-2312.5
(56)(38)
0.327;-2137.5
3T(56)
0.322;-2450.0
3(56K)
0.386;-2243.8
36(58)
0.241;-2587.5
36(5T)
0.307;-2450.0
36(5Q)
0.350;-2312.5
57(37)
0.338;-2137.5
(37)(5T)
0.355;-1931.2
5(37K)
0.316;-2175.0
3(579)
0.317;-2450.0
(57)(3Q)
0.307;-1793.8
37(58)
0.302;-2518.8
37(5T)
0.349;-2381.2
37(5Q)
0.315;-2243.8
58(38)
0.361;-2000.0
(38)(5J)
0.308;-1793.8
38(58)
0.302;-2000.0
3(58J)
0.370;-2243.8
3588
0.287;-2450.0
358T
0.262;-2762.5
358Q
0.286;-2625.0
(39)(5T)
0.304;-1793.8
5(39K)
0.313;-2037.5
3(59J)
0.355;-2175.0
3599
0.279;-2312.5
359J
0.352;-2625.0
359K
0.279;-2487.5
5Q(3T)
0.338;-2037.5
(5T)(3Q)
0.349;-1587.5
3T(5J)
0.276;-2106.2
3T(5K)
0.276;-1968.7
5(3JK)
0.396;-1900.0
3(5JK)
0.340;-1900.0
3J(5K)
0.357;-1900.0
3Q(5Q)
0.374;-1450.0
35QK
0.305;-2281.2
67(36)
0.329;-2137.5
(36)(6T)
0.422;-1481.2
6(36K)
0.304;-1725.0
(367T)
0.297;-2312.5
77(36)
0.307;-2068.7
(36)(7T)
0.334;-1862.5
7(36K)
0.344;-2106.2
(368J)
0.298;-2175.0
(36)(89)
0.352;-1862.5
8(36Q)
0.390;-2106.2
T(369)
0.372;-2175.0
9(36T)
0.267;-2175.0
9Q(36)
0.308;-2037.5
Q(36T)
0.318;-1968.7
(36)(TQ)
0.297;-1518.7
(36JK)
0.360;-1831.2
JK(36)
0.352;-1831.2
K(36K)
0.419;-1243.8
3668
0.332;-2518.8
36(6J)
0.319;-1862.5
(37)(67)
0.297;-1618.8
6(37T)
0.255;-2312.5
6Q(37)
0.299;-2175.0
(67)(39)
0.406;-1931.2
3J(67)
0.265;-2243.8
67(38)
0.286;-2450.0
67(3T)
0.385;-2312.5
67(3Q)
0.316;-2175.0
(38)(68)
0.324;-1481.2
6(38J)
0.306;-2175.0
6K(38)
0.384;-2037.5
(68)(3J)
0.295;-1725.0
3K(68)
0.286;-2037.5
36(8T)
0.262;-2243.8
36(8Q)
0.283;-2106.2
6(39T)
0.285;-2175.0
6Q(39)
0.337;-2037.5
(69)(3J)
0.346;-1656.2
3K(69)
0.336;-1968.7
36(9J)
0.287;-2106.2
36(9K)
0.334;-1968.7
(3T)(6Q)
0.320;-1518.7
3J(6T)
0.309;-2037.5
6T(3J)
0.406;-2037.5
6T(3K)
0.336;-1900.0
6Q(3J)
0.387;-1900.0
(6J)(3K)
0.356;-1381.2
6J(3K)
0.287;-1831.2
6K(3Q)
0.337;-1762.5
36(QK)
0.348;-1762.5
(37)(78)
0.295;-1481.2
7(37J)
0.338;-1725.0
7K(37)
0.329;-1587.5
(378Q)
0.341;-2037.5
8(37T)
0.340;-2175.0
8Q(37)
0.335;-2037.5
J(379)
0.384;-2037.5
9T(37)
0.374;-2106.2
(37)(9K)
0.360;-1450.0
K(37T)
0.317;-1831.2
T(37K)
0.387;-1831.2
JJ(37)
0.340;-1450.0
(37QK)
0.344;-1693.7
3777
0.363;-2000.0
37(7T)
0.360;-1793.7
77(3K)
0.373;-1587.5
7(38T)
0.303;-2175.0
7Q(38)
0.331;-2037.5
(78)(3T)
0.403;-1725.0
3Q(78)
0.302;-2037.5
3789
0.284;-2693.7
378J
0.330;-2556.2
378K
0.293;-2418.7
7J(39)
0.350;-2037.5
(79)(3T)
0.311;-1656.2
3Q(79)
0.283;-1968.7
379T
0.277;-2556.2
379Q
0.311;-2418.7
(3T)(7J)
0.295;-1518.7
3T(7T)
0.356;-1587.5
3(7TK)
0.287;-1831.2
3T(7Q)
0.292;-1900.0
7J(3J)
0.315;-1450.0
(7J)(3Q)
0.385;-1381.2
3J(7Q)
0.347;-1831.2
7Q(3Q)
0.360;-1312.5
37QQ
0.357;-1762.5
37KK
0.308;-1625.0
8(38J)
0.321;-1587.5
8K(38)
0.355;-1450.0
(389K)
0.330;-1831.2
9J(38)
0.384;-1968.7
(38TJ)
0.345;-1900.0
(38)(TJ)
0.348;-1450.0
J(38J)
0.348;-1381.2
JQ(38)
0.326;-1762.5
Q(38K)
0.335;-1625.0
3889
0.295;-2175.0
38(8Q)
0.292;-1518.7
(39)(8T)
0.393;-1587.5
8(39K)
0.389;-1831.2
3(89J)
0.418;-1968.7
3899
0.334;-2106.2
389J
0.268;-2418.7
389K
0.306;-2281.2
8Q(3T)
0.350;-1831.2
(8T)(3Q)
0.366;-1381.2
3T(8J)
0.406;-1900.0
3T(8K)
0.338;-1762.5
8(3JK)
0.323;-1693.7
3(8JK)
0.341;-1693.7
3J(8K)
0.275;-1693.7
3Q(8Q)
0.372;-1243.8
38QK
0.322;-2075.0
9T(39)
0.347;-1518.7
(39)(9K)
0.355;-862.5
K(39T)
0.346;-1693.7
T(39K)
0.319;-1693.7
JJ(39)
0.309;-1312.5
(39QK)
0.389;-1556.2
3999
0.294;-1587.5
39(9Q)
0.380;-1381.2
(3T)(9J)
0.333;-1381.2
3T(9T)
0.377;-1450.0
3(9TK)
0.359;-1693.7
3T(9Q)
0.301;-1762.5
9J(3J)
0.371;-1312.5
(9J)(3Q)
0.374;-1243.8
3J(9Q)
0.363;-1693.7
9Q(3Q)
0.405;-1175.0
39QQ
0.336;-1625.0
39KK
0.385;-1487.5
T(3TK)
0.374;-1175.0
JJ(3T)
0.372;-1243.8
(3TQK)
0.391;-1487.5
3TTT
0.409;-1381.2
3T(TK)
0.303;-1175.0
(3J)(TK)
0.311;-1106.2
3K(TJ)
0.356;-1556.2
3T(JK)
0.353;-1556.2
(TQ)(3K)
0.389;-1037.5
(3K)(TK)
0.345;-518.7
J(3JK)
0.357;-1037.5
(3J)(QK)
0.349;-968.7
JJ(3K)
0.336;-1037.5
3Q(JQ)
0.329;-1037.5
3JQK
0.371;-1868.7
QK(3Q)
0.431;-900.0
QK(3K)
0.350;-831.2
44(46)
0.399;-1962.5
44(4T)
0.363;-1687.5
(45)(45)
0.309;-1512.5
4(458)
0.384;-2206.2
4T(45)
0.340;-2068.7
(45)(4K)
0.336;-1412.5
4457
0.346;-2725.0
44(5T)
0.319;-2068.7
45(4K)
0.338;-1862.5
4(468)
0.349;-2137.5
4T(46)
0.324;-2000.0
(46)(4K)
0.369;-1343.7
4468
0.301;-2587.5
44(6J)
0.339;-1931.2
(47)(47)
0.353;-1237.5
4(47T)
0.372;-1931.2
4Q(47)
0.366;-1793.7
47(49)
0.332;-2000.0
447J
0.298;-2312.5
48(48)
0.374;-1550.0
(48)(4J)
0.374;-1343.7
4488
0.312;-2000.0
44(8J)
0.365;-1793.7
(49)(49)
0.376;-962.5
4(49Q)
0.289;-1656.2
44(9T)
0.295;-1793.7
49(4K)
0.420;-1587.5
4(4TQ)
0.308;-1587.5
44(TJ)
0.400;-1656.2
(4J)(4J)
0.392;-687.5
44JJ
0.339;-1587.5
4Q(4Q)
0.328;-1000.0
(4K)(4K)
0.376;-412.5
(45)(57)
0.299;-1756.3
5(45T)
0.290;-2000.0
5Q(45)
0.354;-1862.5
8(456)
0.374;-2518.8
Q(456)
0.276;-2243.8
(45)(68)
0.358;-2068.7
6(45J)
0.339;-2312.5
6K(45)
0.343;-2175.0
(457J)
0.268;-2243.8
(45)(78)
0.313;-2000.0
7(45J)
0.293;-2243.8
7K(45)
0.320;-2106.2
(458Q)
0.390;-2106.2
8(45T)
0.285;-2243.8
8Q(45)
0.309;-2106.2
J(459)
0.365;-2106.2
9T(45)
0.335;-2175.0
(45)(9K)
0.329;-1518.7
K(45T)
0.316;-1900.0
T(45K)
0.334;-1900.0
JJ(45)
0.289;-1518.7
(45QK)
0.337;-1762.5
4555
0.339;-2343.8
45(58)
0.320;-2137.5
55(4J)
0.398;-1931.2
455K
0.303;-2243.8
58(46)
0.341;-2518.8
(46)(5J)
0.328;-1862.5
46(56)
0.293;-2206.2
4(569)
0.322;-2450.0
(56)(4Q)
0.370;-1793.8
46(57)
0.343;-2587.5
46(59)
0.331;-2450.0
46(5J)
0.330;-2312.5
46(5K)
0.385;-2175.0
5(479)
0.309;-2381.2
5J(47)
0.372;-2243.8
(57)(48)
0.401;-2000.0
4T(57)
0.247;-2312.5
4(57K)
0.305;-2106.2
47(59)
0.277;-2381.2
47(5J)
0.363;-2243.8
47(5K)
0.283;-2106.2
5(48T)
0.285;-2243.8
5Q(48)
0.351;-2106.2
(58)(4T)
0.377;-1793.8
4Q(58)
0.374;-2106.2
4589
0.252;-2762.5
458J
0.251;-2625.0
458K
0.278;-2487.5
5J(49)
0.269;-2106.2
(59)(4T)
0.301;-1725.0
4Q(59)
0.327;-2037.5
459T
0.272;-2625.0
459Q
0.313;-2487.5
(4T)(5J)
0.339;-1587.5
4T(5T)
0.289;-1656.2
4(5TK)
0.346;-1900.0
4T(5Q)
0.279;-1968.7
5J(4J)
0.324;-1518.7
(5J)(4Q)
0.326;-1450.0
4J(5Q)
0.299;-1900.0
5Q(4Q)
0.377;-1381.2
45QQ
0.290;-1831.2
45KK
0.387;-1693.7
6(469)
0.388;-1931.2
6J(46)
0.317;-1793.7
(4678)
0.365;-2381.2
(467Q)
0.305;-2106.2
7(469)
0.266;-2312.5
7J(46)
0.290;-2175.0
(4689)
0.309;-2243.8
(468K)
0.269;-1968.7
8T(46)
0.337;-2175.0
(46)(8K)
0.340;-1518.7
Q(469)
0.385;-1968.7
(46)(9J)
0.351;-1587.5
T(46T)
0.365;-1587.5
T(46J)
0.364;-1968.7
TK(46)
0.397;-1831.2
(46)(JQ)
0.391;-1381.2
QQ(46)
0.336;-1312.5
46(67)
0.294;-2068.7
66(4T)
0.325;-1862.5
466Q
0.366;-2175.0
68(47)
0.309;-2381.2
(47)(6J)
0.337;-1725.0
47(67)
0.348;-2000.0
4(67T)
0.323;-2243.8
(67)(4K)
0.318;-1587.5
67(49)
0.320;-2312.5
67(4J)
0.359;-2175.0
67(4K)
0.291;-2037.5
69(48)
0.400;-2243.8
(48)(6Q)
0.366;-1587.5
49(68)
0.356;-2243.8
4(68Q)
0.379;-2037.5
46(89)
0.332;-2243.8
46(8J)
0.317;-2106.2
46(8K)
0.275;-1968.7
(49)(6J)
0.281;-1587.5
49(69)
0.345;-1725.0
4(69Q)
0.292;-1968.7
46(9T)
0.321;-2106.2
46(9Q)
0.335;-1968.7
6(4TJ)
0.360;-1968.7
6K(4T)
0.407;-1831.2
(6T)(4K)
0.350;-1381.2
6T(4Q)
0.294;-1900.0
(4J)(6J)
0.390;-1000.0
4J(6J)
0.357;-1450.0
6J(4Q)
0.317;-1831.2
(4Q)(6Q)
0.304;-862.5
4K(6Q)
0.330;-1693.7
4K(6K)
0.362;-1175.0
79(47)
0.358;-1793.7
(47)(7Q)
0.378;-1137.5
(478T)
0.306;-2106.2
88(47)
0.390;-1793.7
(47)(8J)
0.374;-1587.5
9(479)
0.349;-1656.2
K(479)
0.298;-1831.2
9(47Q)
0.301;-1900.0
J(47T)
0.348;-1900.0
TJ(47)
0.319;-1900.0
(47JQ)
0.361;-1762.5
J(47K)
0.300;-1693.7
(47)(QK)
0.370;-1175.0
77(49)
0.306;-1793.7
477J
0.282;-2106.2
78(48)
0.368;-1793.7
(48)(7J)
0.356;-1587.5
48(78)
0.331;-1793.7
4(78J)
0.294;-2037.5
4788
0.321;-2243.8
478T
0.350;-2556.2
478Q
0.349;-2418.7
(49)(7T)
0.363;-1587.5
7(49K)
0.343;-1831.2
4(79J)
0.313;-1968.7
4799
0.385;-2106.2
479J
0.275;-2418.7
479K
0.309;-2281.2
7Q(4T)
0.410;-1831.2
(7T)(4Q)
0.318;-1381.2
4T(7J)
0.346;-1900.0
4T(7K)
0.295;-1762.5
7(4JK)
0.301;-1693.7
4(7JK)
0.376;-1693.7
4J(7K)
0.396;-1693.7
4Q(7Q)
0.416;-1243.8
47QK
0.345;-2075.0
89(48)
0.326;-1656.2
(48)(8Q)
0.381;-1000.0
(489J)
0.348;-1900.0
(48)(9T)
0.350;-1518.7
9(48K)
0.298;-1762.5
(48TK)
0.299;-1693.7
TQ(48)
0.356;-1762.5
K(48J)
0.358;-1625.0
Q(48Q)
0.383;-1175.0
KK(48)
0.375;-1037.5
88(4J)
0.308;-1518.7
488K
0.347;-1831.2
8J(49)
0.307;-1900.0
(89)(4T)
0.382;-1518.7
4Q(89)
0.360;-1831.2
489T
0.263;-2418.7
489Q
0.252;-2281.2
(4T)(8J)
0.344;-1381.2
4T(8T)
0.347;-1450.0
4(8TK)
0.323;-1693.7
4T(8Q)
0.336;-1762.5
8J(4J)
0.307;-1312.5
(8J)(4Q)
0.321;-1243.8
4J(8Q)
0.384;-1693.7
8Q(4Q)
0.383;-1175.0
48QQ
0.360;-1625.0
48KK
0.341;-1487.5
9(49Q)
0.344;-1312.5
J(49T)
0.278;-1762.5
TJ(49)
0.342;-1762.5
(49JQ)
0.331;-1625.0
J(49K)
0.337;-1556.2
(49)(QK)
0.356;-1037.5
99(4J)
0.371;-1381.2
499K
0.345;-1693.7
9Q(4T)
0.350;-1693.7
(9T)(4Q)
0.310;-1243.8
4T(9J)
0.297;-1762.5
4T(9K)
0.302;-1625.0
9(4JK)
0.353;-1556.2
4(9JK)
0.388;-1556.2
4J(9K)
0.323;-1556.2
4Q(9Q)
0.372;-1106.2
49QK
0.386;-1937.5
TJ(4T)
0.359;-1243.8
(4TJQ)
0.288;-1556.2
J(4TK)
0.359;-1487.5
(4T)(QK)
0.381;-968.7
TT(4Q)
0.332;-1175.0
T(4JQ)
0.360;-1556.2
4(TJQ)
0.389;-1556.2
4T(JQ)
0.364;-1556.2
T(4QK)
0.341;-1418.7
TQ(4K)
0.428;-1418.7
JJ(4J)
0.356;-656.3
(4JQK)
0.349;-1350.0
4JJJ
0.394;-1106.2
JQ(4Q)
0.362;-968.7
4JQQ
0.425;-1418.7
4JKK
0.412;-1281.2
QQ(4K)
0.373;-831.2
4KKK
0.306;-693.8
55(59)
0.337;-1550.0
55(5K)
0.356;-1275.0
(56)(58)
0.354;-1550.0
5(56J)
0.309;-1793.7
5K(56)
0.368;-1656.2
56(59)
0.311;-1931.2
556J
0.320;-2243.8
57(57)
0.379;-1550.0
(57)(5T)
0.302;-1343.7
5(57K)
0.390;-1587.5
55(79)
0.347;-1862.5
57(5Q)
0.377;-1656.2
5(589)
0.331;-1793.7
5J(58)
0.363;-1656.2
58(59)
0.359;-1793.7
558J
0.342;-2106.2
59(59)
0.335;-1275.0
(59)(5Q)
0.374;-1068.8
559T
0.364;-2106.2
55(9K)
0.353;-1450.0
(5T)(5Q)
0.383;-1000.0
55TJ
0.317;-1968.7
5J(5J)
0.409;-1000.0
5J(5Q)
0.339;-1381.2
5(5QK)
0.365;-1243.8
5K(5K)
0.418;-725.0
68(56)
0.354;-1931.2
(56)(6J)
0.344;-1275.0
7(567)
0.293;-1931.2
J(567)
0.382;-2106.2
78(56)
0.318;-2312.5
(56)(7J)
0.343;-1656.2
8(568)
0.330;-1793.7
Q(568)
0.397;-1968.7
(56)(8T)
0.332;-1656.2
8(56K)
0.297;-1900.0
(569Q)
0.351;-1900.0
9(56J)
0.309;-1968.7
9K(56)
0.313;-1831.2
TT(56)
0.343;-1518.7
(56)(TK)
0.372;-1312.5
J(56Q)
0.371;-1762.5
K(56Q)
0.353;-1625.0
66(57)
0.419;-2000.0
5669
0.308;-2312.5
56(6Q)
0.365;-1656.2
(57)(68)
0.315;-1862.5
6(57J)
0.342;-2106.2
6K(57)
0.362;-1968.7
(67)(5T)
0.305;-1725.0
5Q(67)
0.330;-2037.5
5678
0.295;-2762.5
567T
0.305;-2625.0
567Q
0.364;-2487.5
(58)(69)
0.408;-1725.0
6(58Q)
0.373;-1968.7
5(689)
0.334;-2175.0
(68)(5Q)
0.358;-1518.7
58(69)
0.351;-2175.0
58(6J)
0.360;-2037.5
58(6K)
0.352;-1900.0
6(59J)
0.321;-1968.7
6K(59)
0.340;-1831.2
(69)(5Q)
0.408;-1450.0
59(6T)
0.340;-2037.5
59(6Q)
0.315;-1900.0
6T(5T)
0.333;-1518.7
(5T)(6K)
0.356;-1312.5
5Q(6T)
0.313;-1831.2
56TJ
0.362;-2350.0
56TK
0.323;-2212.5
6K(5J)
0.313;-1693.7
56JJ
0.356;-1831.2
56JK
0.252;-2143.8
5(6QK)
0.311;-1625.0
6K(5K)
0.327;-1106.2
(57)(79)
0.381;-1275.0
7(57Q)
0.348;-1518.7
9(578)
0.354;-2106.2
K(578)
0.317;-1831.2
8(57J)
0.302;-1968.7
8K(57)
0.349;-1831.2
(579K)
0.337;-1762.5
9J(57)
0.294;-1900.0
(57TJ)
0.365;-1831.2
(57)(TJ)
0.401;-1381.2
J(57J)
0.325;-1312.5
JQ(57)
0.332;-1693.7
Q(57K)
0.366;-1556.2
5778
0.348;-2243.8
57(7J)
0.356;-1587.5
(58)(78)
0.321;-1275.0
7(58J)
0.320;-1968.7
7K(58)
0.324;-1831.2
(78)(5J)
0.336;-1518.7
5K(78)
0.354;-1831.2
57(8T)
0.402;-2037.5
57(8Q)
0.318;-1900.0
7(59T)
0.278;-1968.7
7Q(59)
0.331;-1831.2
(79)(5J)
0.396;-1450.0
5K(79)
0.338;-1762.5
57(9J)
0.328;-1900.0
57(9K)
0.339;-1762.5
(5T)(7Q)
0.388;-1312.5
5J(7T)
0.374;-1831.2
7T(5J)
0.308;-1831.2
7T(5K)
0.336;-1693.7
7Q(5J)
0.305;-1693.7
(7J)(5K)
0.321;-1175.0
7J(5K)
0.359;-1625.0
7K(5Q)
0.361;-1556.2
57(QK)
0.347;-1556.2
(58)(89)
0.344;-1137.5
8(58Q)
0.393;-1381.2
T(589)
0.297;-1900.0
9(58T)
0.328;-1900.0
9Q(58)
0.376;-1762.5
Q(58T)
0.328;-1693.7
(58)(TQ)
0.375;-1243.8
(58JK)
0.402;-1556.2
JK(58)
0.389;-1556.2
K(58K)
0.393;-968.7
588T
0.394;-1968.7
58(8K)
0.345;-1312.5
(59)(8J)
0.394;-1381.2
59(89)
0.330;-1518.7
5(89Q)
0.308;-1762.5
58(9T)
0.290;-1900.0
58(9Q)
0.330;-1762.5
8(5TJ)
0.374;-1762.5
8K(5T)
0.271;-1625.0
(8T)(5K)
0.421;-1175.0
8T(5Q)
0.334;-1693.7
(5J)(8J)
0.341;-793.7
5J(8J)
0.348;-1243.8
8J(5Q)
0.346;-1625.0
(5Q)(8Q)
0.379;-656.3
5K(8Q)
0.349;-1487.5
5K(8K)
0.333;-968.7
9J(59)
0.433;-1312.5
(59TJ)
0.418;-1693.7
(59)(TJ)
0.415;-1243.8
J(59J)
0.411;-1175.0
JQ(59)
0.278;-1556.2
Q(59K)
0.343;-1418.7
599T
0.356;-1831.2
59(9K)
0.377;-1175.0
(5T)(9Q)
0.368;-1175.0
5J(9T)
0.286;-1693.7
9T(5J)
0.300;-1693.7
9T(5K)
0.339;-1556.2
9Q(5J)
0.354;-1556.2
(9J)(5K)
0.411;-1037.5
9J(5K)
0.299;-1487.5
9K(5Q)
0.318;-1418.7
59(QK)
0.291;-1418.7
(5T)(TJ)
0.353;-725.0
J(5TJ)
0.423;-1106.2
JQ(5T)
0.394;-1487.5
Q(5TK)
0.370;-1350.0
5TTJ
0.317;-1625.0
TJ(5J)
0.303;-1106.2
(TJ)(5Q)
0.296;-1037.5
5J(TQ)
0.336;-1487.5
TQ(5Q)
0.425;-968.7
5TQQ
0.350;-1418.7
5TKK
0.395;-1281.2
Q(5JQ)
0.346;-900.0
KK(5J)
0.401;-762.5
(5Q)(JQ)
0.355;-450.0
5K(JQ)
0.367;-1281.2
5K(JK)
0.360;-762.5
5QQQ
0.325;-831.2
KK(5K)
0.375;-175.0
6669
0.346;-1793.8
666K
0.306;-1518.7
69(67)
0.351;-1725.0
(67)(6Q)
0.403;-1068.8
6678
0.250;-2243.8
66(7J)
0.301;-1587.5
(68)(68)
0.370;-825.0
6(68J)
0.389;-1518.7
6K(68)
0.362;-1381.2
68(6J)
0.417;-1518.7
668K
0.272;-1831.2
6J(69)
0.402;-1450.0
69(6T)
0.306;-1518.7
669Q
0.300;-1831.2
6J(6T)
0.365;-1381.2
6T(6J)
0.388;-1381.2
66TK
0.334;-1693.7
6K(6J)
0.318;-1175.0
(6Q)(6Q)
0.374;-275.0
66QK
0.386;-1556.2
7(679)
0.315;-1656.2
7J(67)
0.321;-1518.7
(6789)
0.334;-2037.5
(678K)
0.354;-1762.5
8T(67)
0.341;-1968.7
(67)(8K)
0.347;-1312.5
Q(679)
0.321;-1762.5
(67)(9J)
0.378;-1381.2
T(67T)
0.354;-1381.2
T(67J)
0.341;-1762.5
TK(67)
0.331;-1625.0
(67)(JQ)
0.383;-1175.0
QQ(67)
0.363;-1106.2
67(78)
0.354;-1725.0
77(6J)
0.321;-1518.7
677K
0.379;-1831.2
7T(68)
0.327;-1968.7
(68)(7K)
0.303;-1312.5
6T(78)
0.380;-1968.7
6(78K)
0.297;-1762.5
68(7T)
0.270;-1968.7
68(7Q)
0.353;-1831.2
79(69)
0.319;-1518.7
(69)(7Q)
0.342;-1312.5
6T(79)
0.377;-1900.0
6(79K)
0.326;-1693.7
69(7J)
0.336;-1831.2
69(7K)
0.412;-1693.7
7(6TQ)
0.365;-1693.7
6(7TJ)
0.276;-1762.5
67TT
0.390;-1831.2
67TQ
0.313;-2143.8
(6J)(7Q)
0.361;-1175.0
6Q(7J)
0.393;-1625.0
67JQ
0.285;-2075.0
(6Q)(7K)
0.364;-1037.5
6Q(7K)
0.377;-1487.5
8(689)
0.328;-1518.7
8J(68)
0.338;-1381.2
(689T)
0.338;-1831.2
99(68)
0.360;-1450.0
(68)(9Q)
0.382;-1243.8
(68TQ)
0.353;-1625.0
T(68Q)
0.368;-1625.0
Q(68J)
0.312;-1556.2
(68)(JK)
0.297;-1037.5
QK(68)
0.337;-1418.7
68(8T)
0.356;-1450.0
88(6K)
0.387;-1243.8
8(69J)
0.314;-1762.5
8K(69)
0.316;-1625.0
(89)(6Q)
0.357;-1243.8
69(8T)
0.298;-1831.2
69(8Q)
0.378;-1693.7
8T(6T)
0.319;-1312.5
(6T)(8K)
0.348;-1106.2
6Q(8T)
0.378;-1625.0
68TJ
0.345;-2143.8
68TK
0.324;-2006.2
8K(6J)
0.289;-1487.5
68JJ
0.387;-1625.0
68JK
0.280;-1937.5
6(8QK)
0.332;-1418.7
8K(6K)
0.364;-900.0
(69)(9J)
0.360;-793.7
T(69T)
0.350;-1243.8
T(69J)
0.373;-1625.0
TK(69)
0.367;-1487.5
(69)(JQ)
0.321;-1037.5
QQ(69)
0.366;-968.7
69(9T)
0.351;-1312.5
99(6K)
0.370;-1106.2
9(6TQ)
0.343;-1556.2
6(9TJ)
0.340;-1625.0
69TT
0.304;-1693.7
69TQ
0.280;-2006.2
(6J)(9Q)
0.385;-1037.5
6Q(9J)
0.348;-1487.5
69JQ
0.288;-1937.5
(6Q)(9K)
0.340;-900.0
6Q(9K)
0.365;-1350.0
T(6TJ)
0.431;-1106.2
TK(6T)
0.414;-968.7
(6T)(JQ)
0.370;-968.7
QQ(6T)
0.388;-900.0
6T(TJ)
0.324;-1106.2
(6J)(TJ)
0.383;-587.5
6J(TJ)
0.385;-1037.5
TJ(6Q)
0.393;-1418.7
(6Q)(TQ)
0.420;-450.0
6K(TQ)
0.384;-1281.2
6K(TK)
0.322;-762.5
JK(6J)
0.340;-831.2
K(6JK)
0.393;-693.8
6JJK
0.426;-1281.2
6(JQK)
0.359;-1212.5
JK(6K)
0.386;-693.8
KK(6Q)
0.323;-625.0
6QKK
0.380;-1075.0
77(7T)
0.406;-1068.7
(78)(78)
0.386;-687.5
7(78J)
0.316;-1381.2
7K(78)
0.356;-1243.8
78(7J)
0.363;-1381.2
778K
0.335;-1693.7
7J(79)
0.379;-1312.5
79(7T)
0.336;-1381.2
779Q
0.339;-1693.7
7J(7T)
0.295;-1243.8
7T(7J)
0.375;-1243.8
77TK
0.373;-1556.2
7K(7J)
0.366;-1037.5
(7Q)(7Q)
0.408;-137.5
77QK
0.345;-1418.7
8(78T)
0.339;-1381.2
8Q(78)
0.357;-1243.8
J(789)
0.341;-1693.7
9T(78)
0.314;-1762.5
(78)(9K)
0.374;-1106.2
K(78T)
0.313;-1487.5
T(78K)
0.401;-1487.5
JJ(78)
0.408;-1106.2
(78QK)
0.370;-1350.0
7888
0.330;-1518.7
78(8J)
0.357;-1312.5
(79)(89)
0.332;-931.2
8(79Q)
0.351;-1625.0
7(89T)
0.338;-1762.5
(89)(7K)
0.356;-1106.2
89(7J)
0.347;-1693.7
89(7K)
0.364;-1556.2
8J(7T)
0.378;-1625.0
(8T)(7J)
0.432;-1175.0
7K(8T)
0.330;-1487.5
78(TQ)
0.385;-1556.2
8(7JQ)
0.341;-1487.5
7(8JQ)
0.324;-1487.5
78(JQ)
0.342;-1487.5
8(7QK)
0.353;-1350.0
8Q(7K)
0.384;-1350.0
99(79)
0.386;-862.5
(79)(9Q)
0.328;-656.3
(79TQ)
0.320;-1487.5
T(79Q)
0.385;-1487.5
Q(79J)
0.373;-1418.7
(79)(JK)
0.324;-900.0
QK(79)
0.323;-1281.2
79(9J)
0.307;-1175.0
(7T)(9T)
0.326;-725.0
9(7TK)
0.386;-1418.7
7(9TQ)
0.404;-1487.5
79(TJ)
0.323;-1556.2
79(TK)
0.335;-1418.7
(7J)(9K)
0.374;-900.0
7K(9J)
0.303;-1350.0
79(JK)
0.309;-1350.0
(9Q)(7K)
0.321;-831.2
(7K)(9K)
0.339;-312.5
T(7TQ)
0.306;-968.7
Q(7TJ)
0.333;-1350.0
(7T)(JK)
0.332;-831.2
QK(7T)
0.333;-1212.5
7T(TQ)
0.364;-968.7
(7J)(TQ)
0.399;-900.0
7Q(TJ)
0.418;-1350.0
7TJQ
0.284;-1800.0
(7Q)(TK)
0.407;-762.5
7Q(TK)
0.385;-1212.5
J(7JQ)
0.371;-831.2
K(7JQ)
0.377;-1143.7
JJ(7Q)
0.401;-831.2
J(7QK)
0.376;-1143.7
JQ(7K)
0.326;-1143.7
QQ(7Q)
0.407;-243.8
7Q(QK)
0.391;-625.0
8888
0.409;-1000.0
888Q
0.345;-1175.0
8(89J)
0.375;-1175.0
8K(89)
0.396;-1037.5
89(8Q)
0.327;-1106.2
8(8TJ)
0.336;-1106.2
8K(8T)
0.298;-968.7
8T(8K)
0.389;-968.7
8(8JK)
0.312;-900.0
88(JK)
0.340;-900.0
8Q(8K)
0.369;-831.2
(89)(9T)
0.359;-725.0
9(89K)
0.396;-968.7
(89TK)
0.381;-1350.0
TQ(89)
0.338;-1418.7
K(89J)
0.340;-1281.2
Q(89Q)
0.335;-831.2
KK(89)
0.392;-693.8
99(8Q)
0.368;-1037.5
9(8TJ)
0.389;-1487.5
9K(8T)
0.355;-1350.0
(9T)(8K)
0.339;-900.0
9T(8Q)
0.343;-1418.7
(8J)(9J)
0.390;-518.7
8J(9J)
0.376;-968.7
9J(8Q)
0.410;-1350.0
(8Q)(9Q)
0.395;-381.2
8K(9Q)
0.359;-1212.5
8K(9K)
0.354;-693.8
TQ(8T)
0.345;-900.0
K(8TJ)
0.320;-1212.5
Q(8TQ)
0.415;-762.5
KK(8T)
0.345;-625.0
