AAAA
0.193;-1535.0
5AAA
0.087;-18528.1
9AAA
0.155;-14155.6
KAAA
0.136;-9783.1
4A(2A)
0.050;-32738.8
(2A)(7A)
0.091;-22304.4
A(2TA)
0.080;-26180.0
QA(2A)
0.078;-23993.7
2A(4A)
0.052;-32738.8
26AA
0.038;-37707.5
AA(29)
0.095;-27273.1
2A(QA)
0.092;-23993.7
A(34A)
0.072;-31645.6
6A(3A)
0.077;-29459.4
(3A)(9A)
0.126;-19025.0
A(3QA)
0.076;-22900.6
AA(34)
0.072;-31645.6
3A(7A)
0.058;-28366.2
39AA
0.054;-33335.0
AA(3Q)
0.119;-22900.6
(4A)(5A)
0.089;-22304.4
A(48A)
0.084;-26180.0
TA(4A)
0.096;-23993.7
(4A)(KA)
0.143;-13559.4
46AA
0.044;-35521.2
AA(49)
0.088;-25086.9
4A(QA)
0.111;-21807.5
A(56A)
0.081;-27273.1
8A(5A)
0.101;-25086.9
(5A)(JA)
0.114;-14652.5
55AA
0.061;-28366.2
AA(58)
0.080;-25086.9
5A(JA)
0.099;-21807.5
5KAA
0.072;-26776.3
8A(6A)
0.074;-23993.7
(6A)(JA)
0.105;-13559.4
66AA
0.071;-26180.0
AA(69)
0.102;-22900.6
6A(QA)
0.139;-19621.3
A(78A)
0.083;-22900.6
TA(7A)
0.125;-20714.4
(7A)(KA)
0.167;-10280.0
79AA
0.070;-28962.5
AA(7Q)
0.117;-18528.1
(8A)(9A)
0.166;-13559.4
A(8QA)
0.137;-17435.0
AA(89)
0.132;-20714.4
8A(QA)
0.121;-17435.0
A(9TA)
0.143;-18528.1
QA(9A)
0.146;-16341.9
9A(JA)
0.142;-17435.0
9KAA
0.110;-22403.8
QA(TA)
0.156;-15248.8
TA(QA)
0.127;-15248.8
A(JQA)
0.115;-14155.6
AA(JQ)
0.132;-14155.6
(QA)(KA)
0.195;-4814.4
KKAA
0.150;-10876.2
2(25A)
0.029;-44763.1
27(2A)
0.033;-42576.9
(2T)(2A)
0.062;-32142.5
2(2KA)
0.039;-36018.1
(236A)
0.025;-49731.9
(23TA)
0.021;-45359.4
33(2A)
0.021;-45856.2
(36)(2A)
0.038;-42576.9
3(29A)
0.022;-46452.5
3J(2A)
0.035;-44266.2
(245A)
0.019;-49731.9
(249A)
0.025;-45359.4
(24KA)
0.047;-40986.9
46(2A)
0.021;-48638.8
(49)(2A)
0.042;-38204.4
4(2QA)
0.037;-42080.0
6(25A)
0.027;-47545.6
T(25A)
0.031;-43173.1
5(26A)
0.029;-47545.6
58(2A)
0.030;-45359.4
(5J)(2A)
0.061;-34925.0
6(26A)
0.036;-39297.5
T(26A)
0.043;-42080.0
6(27A)
0.023;-45359.4
69(2A)
0.032;-43173.1
(6Q)(2A)
0.051;-32738.8
(279A)
0.037;-42080.0
(27KA)
0.048;-37707.5
79(2A)
0.030;-42080.0
(7Q)(2A)
0.066;-31645.6
(28TA)
0.048;-39893.8
88(2A)
0.053;-34925.0
(8J)(2A)
0.078;-31645.6
9(29A)
0.054;-32738.8
K(29A)
0.050;-35521.2
9(2QA)
0.060;-36614.4
J(2TA)
0.039;-36614.4
TJ(2A)
0.048;-36614.4
(2JQA)
0.054;-34428.1
J(2KA)
0.054;-33335.0
(QK)(2A)
0.081;-25086.9
22(4A)
0.026;-45856.2
226A
0.023;-50825.0
2A(29)
0.035;-40390.6
22(QA)
0.037;-37111.3
2(34A)
0.015;-51918.1
26(3A)
0.020;-49731.9
(29)(3A)
0.057;-39297.5
2(3QA)
0.037;-43173.1
A(234)
0.019;-51918.1
(23)(7A)
0.033;-41483.8
9A(23)
0.024;-46452.5
A(23Q)
0.026;-43173.1
2A(34)
0.015;-51918.1
2A(36)
0.016;-49731.9
2A(38)
0.034;-47545.6
2A(3T)
0.025;-45359.4
2A(3Q)
0.034;-43173.1
2(45A)
0.016;-49731.9
27(4A)
0.030;-47545.6
(2T)(4A)
0.053;-37111.3
2(4KA)
0.049;-40986.9
A(246)
0.028;-48638.8
(24)(9A)
0.044;-38204.4
JA(24)
0.039;-43173.1
24(5A)
0.025;-49731.9
24(7A)
0.025;-47545.6
24(9A)
0.025;-45359.4
24(JA)
0.037;-43173.1
24(KA)
0.038;-40986.9
26(5A)
0.024;-47545.6
(29)(5A)
0.057;-37111.3
2(5QA)
0.040;-40986.9
A(256)
0.029;-47545.6
(25)(9A)
0.048;-37111.3
JA(25)
0.032;-42080.0
25(6A)
0.019;-47545.6
25(8A)
0.035;-45359.4
25(TA)
0.026;-43173.1
25(QA)
0.032;-40986.9
(26)(6A)
0.056;-32142.5
2(69A)
0.032;-43173.1
2J(6A)
0.032;-40986.9
(26)(7A)
0.044;-38204.4
9A(26)
0.037;-43173.1
A(26Q)
0.036;-39893.8
2A(67)
0.023;-45359.4
2A(69)
0.040;-43173.1
2A(6J)
0.040;-40986.9
2A(6K)
0.047;-38800.6
(29)(7A)
0.052;-34925.0
2(7QA)
0.050;-38800.6
A(278)
0.036;-43173.1
(27)(JA)
0.067;-32738.8
KA(27)
0.052;-37707.5
2A(79)
0.039;-42080.0
2A(7J)
0.034;-39893.8
2A(7K)
0.041;-37707.5
(2T)(8A)
0.063;-32738.8
2(8KA)
0.044;-36614.4
A(28T)
0.053;-39893.8
(28)(KA)
0.068;-29459.4
28(TA)
0.050;-39893.8
28(QA)
0.046;-37707.5
(29)(9A)
0.092;-25583.8
2(9QA)
0.053;-36614.4
A(29T)
0.042;-38800.6
(29)(KA)
0.082;-28366.2
29(JA)
0.042;-37707.5
29(KA)
0.052;-35521.2
2J(TA)
0.047;-36614.4
(2T)(JA)
0.075;-29459.4
KA(2T)
0.053;-34428.1
2A(TQ)
0.073;-35521.2
2(JQA)
0.053;-34428.1
A(2JQ)
0.044;-34428.1
2A(JQ)
0.055;-34428.1
2(QKA)
0.058;-32241.9
2Q(KA)
0.050;-32241.9
33(3A)
0.037;-37608.1
(36)(3A)
0.053;-34328.8
3(39A)
0.054;-38204.4
3J(3A)
0.070;-36018.1
(345A)
0.026;-48638.8
(349A)
0.030;-44266.2
(34KA)
0.038;-39893.8
46(3A)
0.019;-47545.6
(49)(3A)
0.053;-37111.3
4(3QA)
0.036;-40986.9
6(35A)
0.021;-46452.5
T(35A)
0.044;-42080.0
5(36A)
0.024;-46452.5
58(3A)
0.038;-44266.2
(5J)(3A)
0.061;-33831.9
6(36A)
0.036;-38204.4
T(36A)
0.049;-40986.9
6(37A)
0.029;-44266.2
69(3A)
0.038;-42080.0
(6Q)(3A)
0.058;-31645.6
(379A)
0.044;-40986.9
(37KA)
0.044;-36614.4
79(3A)
0.038;-40986.9
(7Q)(3A)
0.080;-30552.5
(38TA)
0.045;-38800.6
88(3A)
0.060;-33831.9
(8J)(3A)
0.065;-30552.5
9(39A)
0.075;-31645.6
K(39A)
0.043;-34428.1
9(3QA)
0.055;-35521.2
J(3TA)
0.063;-35521.2
TJ(3A)
0.058;-35521.2
(3JQA)
0.079;-33335.0
J(3KA)
0.056;-32241.9
(QK)(3A)
0.106;-23993.7
33(5A)
0.035;-42576.9
337A
0.026;-47545.6
3A(3T)
0.054;-37111.3
33(KA)
0.047;-33831.9
3(46A)
0.023;-47545.6
38(4A)
0.030;-45359.4
(3J)(4A)
0.055;-34925.0
4A(34)
0.031;-42576.9
A(347)
0.026;-46452.5
(34)(TA)
0.046;-36018.1
QA(34)
0.028;-40986.9
345A
0.013;-55793.8
347A
0.012;-53607.5
349A
0.016;-51421.3
34JA
0.020;-49235.0
34KA
0.031;-47048.8
37(5A)
0.028;-45359.4
(3T)(5A)
0.045;-34925.0
3(5KA)
0.048;-38800.6
A(357)
0.030;-45359.4
(35)(TA)
0.053;-34925.0
QA(35)
0.037;-39893.8
356A
0.014;-53607.5
358A
0.015;-51421.3
35TA
0.021;-49235.0
35QA
0.027;-47048.8
(37)(6A)
0.043;-37111.3
3(6TA)
0.031;-40986.9
3Q(6A)
0.042;-38800.6
(36)(8A)
0.049;-36018.1
TA(36)
0.037;-40986.9
A(36K)
0.037;-37707.5
6A(38)
0.025;-43173.1
6A(3T)
0.038;-40986.9
6A(3Q)
0.038;-38800.6
37(7A)
0.040;-36018.1
(3T)(7A)
0.054;-32738.8
3(7KA)
0.053;-36614.4
A(379)
0.037;-40986.9
(37)(QA)
0.077;-30552.5
7A(38)
0.041;-42080.0
7A(3T)
0.048;-39893.8
7A(3Q)
0.057;-37707.5
38(8A)
0.045;-33831.9
(3J)(8A)
0.059;-30552.5
8A(38)
0.062;-33831.9
A(38J)
0.035;-37707.5
388A
0.039;-40986.9
38TA
0.023;-45955.6
38QA
0.031;-43769.4
(3T)(9A)
0.057;-30552.5
3(9KA)
0.058;-34428.1
A(39J)
0.055;-36614.4
399A
0.036;-38800.6
39JA
0.033;-43769.4
39KA
0.032;-41583.1
3Q(TA)
0.055;-34428.1
(3T)(QA)
0.066;-27273.1
TA(3J)
0.045;-35521.2
TA(3K)
0.066;-33335.0
3(JKA)
0.055;-32241.9
A(3JK)
0.057;-32241.9
JA(3K)
0.050;-32241.9
QA(3Q)
0.096;-25086.9
3QKA
0.041;-38303.8
45(4A)
0.031;-40390.6
(48)(4A)
0.063;-29956.3
4(4JA)
0.069;-33831.9
4K(4A)
0.080;-31645.6
(459A)
0.036;-42080.0
(45KA)
0.049;-37707.5
57(4A)
0.038;-44266.2
(5T)(4A)
0.070;-33831.9
5(4KA)
0.040;-37707.5
(469A)
0.031;-40986.9
(46KA)
0.053;-36614.4
68(4A)
0.032;-42080.0
(6J)(4A)
0.081;-31645.6
7(47A)
0.050;-34925.0
J(47A)
0.038;-37707.5
78(4A)
0.037;-40986.9
(7J)(4A)
0.056;-30552.5
8(48A)
0.060;-32738.8
Q(48A)
0.052;-35521.2
(8T)(4A)
0.074;-30552.5
8(4KA)
0.043;-34428.1
(49QA)
0.056;-34428.1
9(4JA)
0.043;-35521.2
9K(4A)
0.062;-33335.0
TT(4A)
0.092;-28366.2
(TK)(4A)
0.072;-25086.9
J(4QA)
0.050;-32241.9
K(4QA)
0.084;-30055.6
44(5A)
0.052;-40390.6
447A
0.026;-45359.4
4A(4T)
0.049;-34925.0
44(KA)
0.073;-31645.6
4(57A)
0.033;-44266.2
49(5A)
0.030;-42080.0
(4Q)(5A)
0.071;-31645.6
6A(45)
0.022;-45359.4
A(459)
0.031;-42080.0
(45)(QA)
0.059;-31645.6
5A(46)
0.025;-45359.4
5A(48)
0.030;-43173.1
5A(4T)
0.042;-40986.9
5A(4Q)
0.048;-38800.6
46(6A)
0.038;-37111.3
(49)(6A)
0.059;-33831.9
4(6QA)
0.057;-37707.5
A(467)
0.025;-43173.1
(46)(TA)
0.060;-32738.8
QA(46)
0.048;-37707.5
467A
0.017;-50328.1
469A
0.022;-48141.9
46JA
0.029;-45955.6
46KA
0.033;-43769.4
49(7A)
0.033;-39893.8
(4Q)(7A)
0.079;-29459.4
8A(47)
0.037;-40986.9
A(47J)
0.041;-37707.5
477A
0.030;-42080.0
479A
0.028;-47048.8
47JA
0.033;-44862.5
47KA
0.039;-42676.2
4T(8A)
0.041;-37707.5
(4K)(8A)
0.083;-27273.1
TA(48)
0.044;-37707.5
A(48K)
0.049;-34428.1
8A(4T)
0.040;-37707.5
8A(4Q)
0.047;-35521.2
49(9A)
0.051;-30552.5
(4Q)(9A)
0.069;-27273.1
TA(49)
0.051;-36614.4
A(49K)
0.078;-33335.0
9A(4J)
0.054;-35521.2
9A(4K)
0.051;-33335.0
4(TQA)
0.068;-33335.0
A(4TJ)
0.075;-34428.1
4TTA
0.044;-35521.2
4TQA
0.041;-40490.0
(4Q)(JA)
0.070;-25086.9
QA(4J)
0.084;-32241.9
4JQA
0.038;-39396.9
(4K)(QA)
0.089;-22900.6
QA(4K)
0.068;-30055.6
5(56A)
0.042;-37111.3
58(5A)
0.045;-34925.0
(5J)(5A)
0.082;-24490.6
6(56A)
0.042;-36018.1
T(56A)
0.054;-38800.6
6(57A)
0.033;-42080.0
69(5A)
0.042;-39893.8
(6Q)(5A)
0.069;-29459.4
(579A)
0.034;-38800.6
(57KA)
0.044;-34428.1
79(5A)
0.059;-38800.6
(7Q)(5A)
0.070;-28366.2
(58TA)
0.046;-36614.4
88(5A)
0.056;-31645.6
(8J)(5A)
0.060;-28366.2
9(59A)
0.081;-29459.4
K(59A)
0.051;-32241.9
9(5QA)
0.050;-33335.0
J(5TA)
0.061;-33335.0
TJ(5A)
0.060;-33335.0
(5JQA)
0.087;-31148.8
J(5KA)
0.079;-30055.6
(QK)(5A)
0.111;-21807.5
55(7A)
0.039;-36018.1
559A
0.038;-40986.9
5A(5Q)
0.066;-30552.5
(57)(6A)
0.041;-34925.0
5(6TA)
0.034;-38800.6
5Q(6A)
0.058;-36614.4
(56)(8A)
0.070;-33831.9
TA(56)
0.047;-38800.6
A(56K)
0.043;-35521.2
6A(58)
0.053;-40986.9
6A(5T)
0.044;-38800.6
6A(5Q)
0.044;-36614.4
57(7A)
0.057;-33831.9
(5T)(7A)
0.056;-30552.5
5(7KA)
0.054;-34428.1
A(579)
0.048;-38800.6
(57)(QA)
0.069;-28366.2
7A(58)
0.045;-39893.8
7A(5T)
0.055;-37707.5
7A(5Q)
0.052;-35521.2
58(8A)
0.076;-31645.6
(5J)(8A)
0.077;-28366.2
8A(58)
0.057;-31645.6
A(58J)
0.067;-35521.2
588A
0.045;-38800.6
58TA
0.030;-43769.4
58QA
0.043;-41583.1
(5T)(9A)
0.084;-28366.2
5(9KA)
0.053;-32241.9
A(59J)
0.056;-34428.1
599A
0.055;-36614.4
59JA
0.032;-41583.1
59KA
0.044;-39396.9
5Q(TA)
0.062;-32241.9
(5T)(QA)
0.072;-25086.9
TA(5J)
0.051;-33335.0
TA(5K)
0.063;-31148.8
5(JKA)
0.082;-30055.6
A(5JK)
0.089;-30055.6
JA(5K)
0.063;-30055.6
QA(5Q)
0.078;-22900.6
5QKA
0.045;-36117.5
67(6A)
0.058;-33831.9
(6T)(6A)
0.113;-23397.5
6(6KA)
0.100;-27273.1
(67TA)
0.049;-36614.4
77(6A)
0.060;-32738.8
(7T)(6A)
0.071;-29459.4
7(6KA)
0.057;-33335.0
(68JA)
0.053;-34428.1
(89)(6A)
0.063;-29459.4
8(6QA)
0.056;-33335.0
T(69A)
0.050;-34428.1
9(6TA)
0.060;-34428.1
9Q(6A)
0.051;-32241.9
Q(6TA)
0.061;-31148.8
(TQ)(6A)
0.088;-23993.7
(6JKA)
0.084;-28962.5
JK(6A)
0.065;-28962.5
K(6KA)
0.138;-19621.3
668A
0.039;-39893.8
6A(6J)
0.084;-29459.4
(67)(7A)
0.091;-25583.8
6(7TA)
0.051;-36614.4
6Q(7A)
0.051;-34428.1
(67)(9A)
0.074;-30552.5
JA(67)
0.047;-35521.2
67(8A)
0.035;-38800.6
67(TA)
0.046;-36614.4
67(QA)
0.066;-34428.1
(68)(8A)
0.115;-23397.5
6(8JA)
0.053;-34428.1
6K(8A)
0.074;-32241.9
(68)(JA)
0.067;-27273.1
KA(68)
0.073;-32241.9
6A(8T)
0.053;-35521.2
6A(8Q)
0.071;-33335.0
6(9TA)
0.050;-34428.1
6Q(9A)
0.058;-32241.9
(69)(JA)
0.075;-26180.0
KA(69)
0.067;-31148.8
6A(9J)
0.057;-33335.0
6A(9K)
0.061;-31148.8
(6Q)(TA)
0.100;-23993.7
JA(6T)
0.051;-32241.9
6T(JA)
0.067;-32241.9
6T(KA)
0.077;-30055.6
6Q(JA)
0.054;-30055.6
(6J)(KA)
0.084;-21807.5
6J(KA)
0.083;-28962.5
6K(QA)
0.091;-27869.4
6A(QK)
0.059;-27869.4
(78)(7A)
0.082;-23397.5
7(7JA)
0.062;-27273.1
7K(7A)
0.103;-25086.9
(78QA)
0.051;-32241.9
8(7TA)
0.056;-34428.1
8Q(7A)
0.079;-32241.9
J(79A)
0.058;-32241.9
9T(7A)
0.077;-33335.0
(9K)(7A)
0.094;-22900.6
K(7TA)
0.058;-28962.5
T(7KA)
0.062;-28962.5
JJ(7A)
0.106;-22900.6
(7QKA)
0.086;-26776.3
777A
0.068;-31645.6
7A(7T)
0.065;-28366.2
77(KA)
0.088;-25086.9
7(8TA)
0.057;-34428.1
7Q(8A)
0.056;-32241.9
(78)(TA)
0.063;-27273.1
QA(78)
0.050;-32241.9
789A
0.026;-42676.2
78JA
0.041;-40490.0
78KA
0.040;-38303.8
7J(9A)
0.055;-32241.9
(79)(TA)
0.068;-26180.0
QA(79)
0.065;-31148.8
79TA
0.029;-40490.0
79QA
0.044;-38303.8
(7J)(TA)
0.093;-23993.7
TA(7T)
0.079;-25086.9
A(7TK)
0.060;-28962.5
TA(7Q)
0.065;-30055.6
7J(JA)
0.078;-22900.6
(7J)(QA)
0.105;-21807.5
JA(7Q)
0.087;-28962.5
7Q(QA)
0.117;-20714.4
7QQA
0.074;-27869.4
7KKA
0.100;-25683.1
8(8JA)
0.095;-25086.9
8K(8A)
0.084;-22900.6
(89KA)
0.092;-28962.5
9J(8A)
0.073;-31148.8
(8TJA)
0.095;-30055.6
(TJ)(8A)
0.093;-22900.6
J(8JA)
0.111;-21807.5
JQ(8A)
0.106;-27869.4
Q(8KA)
0.090;-25683.1
889A
0.066;-34428.1
8A(8Q)
0.106;-23993.7
(8T)(9A)
0.110;-25086.9
8(9KA)
0.057;-28962.5
A(89J)
0.054;-31148.8
899A
0.060;-33335.0
89JA
0.045;-38303.8
89KA
0.044;-36117.5
8Q(TA)
0.084;-28962.5
(8T)(QA)
0.077;-21807.5
TA(8J)
0.077;-30055.6
TA(8K)
0.068;-27869.4
8(JKA)
0.071;-26776.3
A(8JK)
0.089;-26776.3
JA(8K)
0.092;-26776.3
QA(8Q)
0.100;-19621.3
8QKA
0.059;-32838.1
9T(9A)
0.098;-23993.7
(9K)(9A)
0.146;-13559.4
K(9TA)
0.067;-26776.3
T(9KA)
0.099;-26776.3
JJ(9A)
0.129;-20714.4
(9QKA)
0.074;-24590.0
999A
0.092;-25086.9
9A(9Q)
0.086;-21807.5
(9J)(TA)
0.125;-21807.5
TA(9T)
0.096;-22900.6
A(9TK)
0.100;-26776.3
TA(9Q)
0.071;-27869.4
9J(JA)
0.100;-20714.4
(9J)(QA)
0.133;-19621.2
JA(9Q)
0.074;-26776.3
9Q(QA)
0.130;-18528.1
9QQA
0.090;-25683.1
9KKA
0.094;-23496.9
T(TKA)
0.117;-18528.1
JJ(TA)
0.109;-19621.3
(TQKA)
0.096;-23496.9
TTTA
0.105;-21807.5
TA(TK)
0.106;-18528.1
(TK)(JA)
0.106;-17435.0
KA(TJ)
0.087;-24590.0
TA(JK)
0.093;-24590.0
(TQ)(KA)
0.124;-16341.9
(TK)(KA)
0.166;-8093.8
J(JKA)
0.142;-16341.9
(QK)(JA)
0.117;-15248.7
JJ(KA)
0.136;-16341.9
QA(JQ)
0.137;-16341.9
JQKA
0.060;-29558.7
QK(QA)
0.116;-14155.6
QK(KA)
0.169;-13062.5
22(24)
0.016;-51818.8
22(28)
0.023;-47446.3
22(2Q)
0.035;-43073.8
24(23)
0.009;-57880.6
(23)(27)
0.023;-47446.3
2(23T)
0.017;-51321.9
2Q(23)
0.019;-49135.6
23(25)
0.011;-56787.5
2237
0.005;-61756.3
22(3T)
0.016;-51321.9
23(2K)
0.026;-48042.5
2(246)
0.014;-54601.3
28(24)
0.014;-52415.0
(24)(2J)
0.029;-41980.6
2244
0.013;-56787.5
22(47)
0.013;-53508.1
24(2T)
0.021;-50228.8
224Q
0.011;-55197.5
26(25)
0.012;-53508.1
(25)(29)
0.035;-43073.8
2(25Q)
0.032;-46949.4
22(56)
0.016;-53508.1
25(29)
0.022;-50228.8
225J
0.014;-55197.5
26(26)
0.026;-45260.0
(26)(29)
0.032;-41980.6
2(26Q)
0.022;-45856.2
22(67)
0.023;-51321.9
26(2T)
0.020;-48042.5
226Q
0.015;-53011.3
28(27)
0.020;-49135.6
(27)(2J)
0.041;-38701.3
2277
0.017;-50228.8
22(7T)
0.026;-46949.4
27(2K)
0.033;-43670.0
2(28T)
0.034;-45856.2
2Q(28)
0.029;-43670.0
28(2T)
0.028;-45856.2
228Q
0.023;-50825.0
2T(29)
0.023;-44763.1
(29)(2K)
0.060;-34328.8
229J
0.019;-50825.0
2T(2T)
0.049;-36515.0
(2T)(2K)
0.056;-33235.6
22TQ
0.023;-48638.8
2Q(2J)
0.044;-40390.6
2J(2K)
0.055;-39297.5
22QQ
0.046;-39297.5
3(234)
0.011;-56787.5
36(23)
0.010;-54601.3
(23)(39)
0.025;-44166.9
3(23Q)
0.026;-48042.5
5(234)
0.005;-61756.3
9(234)
0.008;-57383.8
K(234)
0.013;-53011.3
4(237)
0.006;-59570.0
49(23)
0.011;-57383.8
(23)(4Q)
0.020;-46949.4
(2357)
0.008;-58476.9
(235J)
0.011;-54104.4
(23)(56)
0.016;-52415.0
5(239)
0.010;-56290.6
5J(23)
0.016;-54104.4
(2367)
0.010;-57383.8
(236J)
0.021;-53011.3
(23)(67)
0.016;-50228.8
6(23T)
0.015;-54104.4
6Q(23)
0.015;-51918.1
9(237)
0.013;-54104.4
K(237)
0.017;-49731.9
7(23T)
0.017;-53011.3
7Q(23)
0.023;-50825.0
T(238)
0.020;-51918.1
8(239)
0.015;-53011.3
8J(23)
0.023;-50825.0
(239T)
0.014;-50825.0
99(23)
0.026;-44763.1
(23)(9Q)
0.047;-41483.8
(23TQ)
0.027;-47545.6
T(23Q)
0.022;-47545.6
Q(23J)
0.028;-46452.5
(23)(JK)
0.047;-38204.4
QK(23)
0.038;-44266.2
23(35)
0.014;-55694.4
33(28)
0.017;-52415.0
233T
0.009;-57383.8
23(3K)
0.026;-46949.4
(24)(36)
0.017;-53508.1
3(249)
0.011;-57383.8
3J(24)
0.013;-55197.5
(34)(25)
0.013;-54601.3
27(34)
0.008;-59570.0
2(34T)
0.011;-56290.6
(34)(2K)
0.021;-45856.2
34(26)
0.008;-60663.1
34(28)
0.008;-58476.9
34(2T)
0.011;-56290.6
34(2Q)
0.012;-54104.4
(25)(35)
0.024;-46353.1
3(258)
0.011;-57383.8
3T(25)
0.012;-55197.5
(25)(3K)
0.027;-44763.1
27(35)
0.009;-58476.9
2(35T)
0.012;-55197.5
(35)(2K)
0.024;-44763.1
35(27)
0.009;-58476.9
35(29)
0.014;-56290.6
35(2J)
0.012;-54104.4
35(2K)
0.016;-51918.1
37(26)
0.008;-57383.8
(26)(3T)
0.024;-46949.4
3(26K)
0.020;-50825.0
2(368)
0.011;-56290.6
(36)(2J)
0.021;-45856.2
2K(36)
0.020;-50825.0
23(68)
0.012;-56290.6
23(6T)
0.012;-54104.4
23(6Q)
0.016;-51918.1
3(278)
0.010;-55197.5
3T(27)
0.016;-53011.3
(27)(3K)
0.032;-42576.9
29(37)
0.013;-54104.4
2(37Q)
0.019;-50825.0
23(78)
0.015;-55197.5
23(7T)
0.016;-53011.3
23(7Q)
0.018;-50825.0
3(289)
0.017;-53011.3
3J(28)
0.015;-50825.0
(38)(29)
0.032;-45856.2
2J(38)
0.014;-50825.0
38(29)
0.014;-53011.3
38(2J)
0.017;-50825.0
38(2K)
0.023;-48638.8
3T(29)
0.020;-50825.0
(29)(3K)
0.040;-40390.6
2J(39)
0.021;-49731.9
39(2T)
0.020;-50825.0
39(2Q)
0.028;-48638.8
(2T)(3T)
0.045;-35421.9
3(2TK)
0.027;-46452.5
2(3TQ)
0.023;-47545.6
23(TJ)
0.023;-48638.8
23(TK)
0.030;-46452.5
(2J)(3K)
0.049;-38204.4
2K(3J)
0.039;-45359.4
23(JK)
0.032;-45359.4
(3Q)(2K)
0.053;-37111.3
(2K)(3K)
0.064;-28863.1
4(246)
0.016;-52415.0
48(24)
0.018;-50228.8
(24)(4J)
0.036;-39794.4
5(245)
0.015;-52415.0
9(245)
0.015;-55197.5
K(245)
0.018;-50825.0
5(248)
0.012;-56290.6
5T(24)
0.015;-54104.4
(24)(5K)
0.030;-43670.0
9(246)
0.013;-54104.4
K(246)
0.021;-49731.9
6(249)
0.012;-54104.4
6J(24)
0.012;-51918.1
(2478)
0.011;-54104.4
(247Q)
0.021;-49731.9
7(249)
0.015;-53011.3
7J(24)
0.016;-50825.0
(2489)
0.016;-51918.1
(248K)
0.026;-47545.6
8T(24)
0.016;-50825.0
(24)(8K)
0.048;-40390.6
Q(249)
0.021;-47545.6
(24)(9J)
0.036;-41483.8
T(24T)
0.033;-41483.8
T(24J)
0.029;-47545.6
TK(24)
0.025;-45359.4
(24)(JQ)
0.047;-38204.4
QQ(24)
0.054;-37111.3
24(45)
0.014;-53508.1
44(28)
0.022;-50228.8
244T
0.013;-55197.5
24(4K)
0.028;-44763.1
(25)(47)
0.019;-50228.8
4(25T)
0.010;-54104.4
4Q(25)
0.019;-51918.1
(45)(27)
0.016;-50228.8
29(45)
0.010;-55197.5
2(45Q)
0.017;-51918.1
24(56)
0.007;-58476.9
24(58)
0.010;-56290.6
24(5T)
0.012;-54104.4
24(5Q)
0.016;-51918.1
4(267)
0.012;-56290.6
49(26)
0.012;-54104.4
(26)(4Q)
0.026;-43670.0
27(46)
0.012;-56290.6
2(46T)
0.014;-53011.3
(46)(2K)
0.042;-42576.9
46(28)
0.010;-55197.5
46(2T)
0.014;-53011.3
46(2Q)
0.018;-50825.0
(27)(47)
0.034;-40887.5
4(27T)
0.018;-51918.1
4Q(27)
0.016;-49731.9
(47)(29)
0.025;-45856.2
2J(47)
0.017;-50825.0
47(28)
0.014;-54104.4
47(2T)
0.016;-51918.1
47(2Q)
0.021;-49731.9
(28)(48)
0.051;-38701.3
4(28J)
0.023;-49731.9
4K(28)
0.018;-47545.6
(48)(2J)
0.025;-42576.9
2K(48)
0.021;-47545.6
24(8T)
0.019;-50825.0
24(8Q)
0.027;-48638.8
4(29T)
0.017;-49731.9
4Q(29)
0.020;-47545.6
(49)(2J)
0.048;-41483.8
2K(49)
0.026;-46452.5
24(9J)
0.021;-48638.8
24(9K)
0.021;-46452.5
(2T)(4Q)
0.047;-39297.5
2J(4T)
0.024;-47545.6
4T(2J)
0.026;-47545.6
4T(2K)
0.031;-45359.4
4Q(2J)
0.031;-45359.4
(4J)(2K)
0.050;-37111.3
4J(2K)
0.035;-44266.2
4K(2Q)
0.028;-43173.1
24(QK)
0.033;-43173.1
(25)(56)
0.030;-43073.8
5(259)
0.026;-46949.4
5J(25)
0.034;-44763.1
(2567)
0.011;-55197.5
(256J)
0.019;-50825.0
(25)(67)
0.025;-48042.5
6(25T)
0.018;-51918.1
6Q(25)
0.017;-49731.9
9(257)
0.018;-51918.1
K(257)
0.021;-47545.6
7(25T)
0.017;-50825.0
7Q(25)
0.024;-48638.8
T(258)
0.022;-49731.9
8(259)
0.022;-50825.0
8J(25)
0.022;-48638.8
(259T)
0.022;-48638.8
99(25)
0.031;-42576.9
(25)(9Q)
0.038;-39297.5
(25TQ)
0.030;-45359.4
T(25Q)
0.032;-45359.4
Q(25J)
0.026;-44266.2
(25)(JK)
0.051;-36018.1
QK(25)
0.037;-42080.0
25(57)
0.016;-49135.6
55(2T)
0.033;-45856.2
255Q
0.021;-50825.0
57(26)
0.016;-55197.5
(26)(5T)
0.024;-44763.1
5(26K)
0.015;-48638.8
2(568)
0.014;-54104.4
(56)(2J)
0.026;-43670.0
2K(56)
0.023;-48638.8
25(68)
0.012;-54104.4
25(6T)
0.016;-51918.1
25(6Q)
0.021;-49731.9
5(278)
0.017;-53011.3
5T(27)
0.024;-50825.0
(27)(5K)
0.043;-40390.6
29(57)
0.019;-51918.1
2(57Q)
0.027;-48638.8
25(78)
0.019;-53011.3
25(7T)
0.017;-50825.0
25(7Q)
0.020;-48638.8
5(289)
0.019;-50825.0
5J(28)
0.019;-48638.8
(58)(29)
0.038;-43670.0
2J(58)
0.024;-48638.8
58(29)
0.016;-50825.0
58(2J)
0.023;-48638.8
58(2K)
0.020;-46452.5
5T(29)
0.021;-48638.8
(29)(5K)
0.044;-38204.4
2J(59)
0.027;-47545.6
59(2T)
0.019;-48638.8
59(2Q)
0.032;-46452.5
(2T)(5T)
0.069;-33235.6
5(2TK)
0.035;-44266.2
2(5TQ)
0.030;-45359.4
25(TJ)
0.023;-46452.5
25(TK)
0.029;-44266.2
(2J)(5K)
0.054;-36018.1
2K(5J)
0.034;-43173.1
25(JK)
0.038;-43173.1
(5Q)(2K)
0.054;-34925.0
(2K)(5K)
0.073;-26676.9
6(268)
0.033;-45856.2
6T(26)
0.029;-43670.0
(26)(6K)
0.048;-33235.6
T(267)
0.025;-49731.9
7(268)
0.015;-51918.1
7T(26)
0.020;-49731.9
(26)(7K)
0.044;-39297.5
J(268)
0.026;-47545.6
89(26)
0.024;-49731.9
(26)(8Q)
0.034;-39297.5
(269J)
0.020;-46452.5
(26)(9T)
0.045;-40390.6
9(26K)
0.034;-44266.2
(26TK)
0.034;-43173.1
TQ(26)
0.030;-44266.2
K(26J)
0.028;-42080.0
Q(26Q)
0.065;-34925.0
KK(26)
0.063;-32738.8
66(29)
0.034;-44763.1
266J
0.021;-49731.9
67(27)
0.024;-45856.2
(27)(6T)
0.037;-42576.9
6(27K)
0.025;-46452.5
2(679)
0.022;-50825.0
(67)(2Q)
0.037;-40390.6
27(68)
0.017;-51918.1
27(6T)
0.019;-49731.9
27(6Q)
0.022;-47545.6
68(28)
0.027;-43670.0
(28)(6J)
0.034;-40390.6
28(68)
0.042;-43670.0
2(68J)
0.025;-47545.6
2688
0.014;-50825.0
268T
0.010;-55793.8
268Q
0.018;-53607.5
(29)(6T)
0.041;-40390.6
6(29K)
0.034;-44266.2
2(69J)
0.028;-46452.5
2699
0.025;-48638.8
269J
0.015;-53607.5
269K
0.015;-51421.3
6Q(2T)
0.032;-44266.2
(6T)(2Q)
0.051;-37111.3
2T(6J)
0.024;-45359.4
2T(6K)
0.038;-43173.1
6(2JK)
0.041;-42080.0
2(6JK)
0.032;-42080.0
2J(6K)
0.034;-42080.0
2Q(6Q)
0.056;-34925.0
26QK
0.025;-48141.9
78(27)
0.026;-43670.0
(27)(7J)
0.064;-33235.6
8(278)
0.040;-42576.9
Q(278)
0.034;-45359.4
(27)(8T)
0.041;-40390.6
8(27K)
0.030;-44266.2
(279Q)
0.028;-44266.2
9(27J)
0.027;-45359.4
9K(27)
0.030;-43173.1
TT(27)
0.039;-38204.4
(27)(TK)
0.048;-34925.0
J(27Q)
0.031;-42080.0
K(27Q)
0.042;-39893.8
77(28)
0.027;-43670.0
277T
0.023;-48638.8
27(7K)
0.041;-38204.4
(28)(7T)
0.036;-40390.6
7(28K)
0.027;-44266.2
2(78T)
0.025;-47545.6
(78)(2K)
0.064;-37111.3
78(2T)
0.021;-47545.6
78(2Q)
0.021;-45359.4
(29)(79)
0.047;-33235.6
7(29Q)
0.033;-44266.2
2(79T)
0.029;-46452.5
(79)(2K)
0.038;-36018.1
79(2J)
0.024;-45359.4
79(2K)
0.034;-43173.1
7J(2T)
0.026;-44266.2
(7T)(2J)
0.051;-37111.3
2K(7T)
0.029;-42080.0
27(TQ)
0.032;-43173.1
7(2JQ)
0.029;-42080.0
2(7JQ)
0.039;-42080.0
27(JQ)
0.036;-42080.0
7(2QK)
0.033;-39893.8
7Q(2K)
0.039;-39893.8
88(28)
0.055;-34328.8
(28)(8J)
0.054;-31049.4
9(289)
0.052;-39297.5
K(289)
0.032;-42080.0
9(28Q)
0.033;-43173.1
J(28T)
0.043;-43173.1
TJ(28)
0.029;-43173.1
(28JQ)
0.037;-40986.9
J(28K)
0.039;-39893.8
(28)(QK)
0.059;-31645.6
88(2T)
0.043;-39297.5
288Q
0.034;-44266.2
8T(29)
0.029;-45359.4
(29)(8K)
0.060;-34925.0
2J(89)
0.033;-44266.2
89(2T)
0.035;-45359.4
89(2Q)
0.027;-43173.1
(2T)(8T)
0.058;-29956.3
8(2TK)
0.050;-40986.9
2(8TQ)
0.039;-42080.0
28(TJ)
0.024;-43173.1
28(TK)
0.030;-40986.9
(2J)(8K)
0.055;-32738.8
2K(8J)
0.041;-39893.8
28(JK)
0.047;-39893.8
(8Q)(2K)
0.069;-31645.6
(2K)(8K)
0.117;-23397.5
9(29J)
0.067;-36018.1
9K(29)
0.062;-33831.9
TT(29)
0.057;-36018.1
(29)(TK)
0.056;-32738.8
J(29Q)
0.040;-39893.8
K(29Q)
0.058;-37707.5
99(2T)
0.048;-37111.3
299Q
0.034;-42080.0
9J(2T)
0.032;-42080.0
(9T)(2J)
0.060;-34925.0
2K(9T)
0.043;-39893.8
29(TQ)
0.038;-40986.9
9(2JQ)
0.045;-39893.8
2(9JQ)
0.033;-39893.8
29(JQ)
0.041;-39893.8
9(2QK)
0.048;-37707.5
9Q(2K)
0.035;-37707.5
TT(2T)
0.100;-27770.0
(2T)(TK)
0.076;-24490.6
J(2TQ)
0.037;-38800.6
K(2TQ)
0.057;-36614.4
TT(2J)
0.055;-33831.9
2TTK
0.049;-38800.6
TK(2J)
0.053;-37707.5
2TJJ
0.040;-39893.8
2TJK
0.034;-44862.5
2(TQK)
0.062;-36614.4
TK(2K)
0.087;-28366.2
(2J)(JK)
0.087;-22304.4
QK(2J)
0.051;-35521.2
2J(JK)
0.065;-29459.4
(JQ)(2K)
0.094;-28366.2
(2K)(JK)
0.114;-20118.1
K(2QK)
0.068;-26180.0
2K(QK)
0.087;-26180.0
3335
0.015;-54601.3
3339
0.019;-50228.8
333K
0.032;-45856.2
36(34)
0.012;-52415.0
(34)(39)
0.032;-41980.6
3(34Q)
0.027;-45856.2
33(45)
0.012;-53508.1
34(38)
0.017;-50228.8
334T
0.014;-55197.5
33(4K)
0.032;-44763.1
(35)(37)
0.029;-43073.8
3(35T)
0.027;-46949.4
3Q(35)
0.031;-44763.1
35(37)
0.020;-50228.8
3359
0.014;-55197.5
33(5Q)
0.027;-44763.1
(36)(37)
0.042;-41980.6
3(36T)
0.026;-45856.2
3Q(36)
0.034;-43670.0
36(38)
0.021;-48042.5
336T
0.012;-53011.3
33(6K)
0.040;-42576.9
(37)(39)
0.045;-38701.3
3(37Q)
0.039;-42576.9
33(78)
0.025;-46949.4
37(3J)
0.039;-43670.0
337K
0.024;-48638.8
3T(38)
0.032;-43670.0
(38)(3K)
0.064;-33235.6
338T
0.019;-50825.0
33(8K)
0.049;-40390.6
(39)(3J)
0.050;-34328.8
3399
0.028;-43670.0
33(9Q)
0.043;-40390.6
(3T)(3J)
0.064;-33235.6
33TT
0.031;-41483.8
33(TK)
0.043;-38204.4
(3J)(3K)
0.080;-29956.3
33JK
0.024;-44266.2
33(QK)
0.052;-36018.1
45(34)
0.015;-52415.0
(34)(48)
0.042;-41980.6
4(34J)
0.021;-45856.2
4K(34)
0.033;-43670.0
(3459)
0.013;-54104.4
(345K)
0.020;-49731.9
57(34)
0.011;-56290.6
(34)(5T)
0.026;-45856.2
5(34K)
0.019;-49731.9
(3469)
0.017;-53011.3
(346K)
0.019;-48638.8
68(34)
0.014;-54104.4
(34)(6J)
0.031;-43670.0
7(347)
0.028;-46949.4
J(347)
0.019;-49731.9
78(34)
0.016;-53011.3
(34)(7J)
0.032;-42576.9
8(348)
0.027;-44763.1
Q(348)
0.021;-47545.6
(34)(8T)
0.029;-42576.9
8(34K)
0.020;-46452.5
(349Q)
0.026;-46452.5
9(34J)
0.021;-47545.6
9K(34)
0.026;-45359.4
TT(34)
0.032;-40390.6
(34)(TK)
0.039;-37111.3
J(34Q)
0.024;-44266.2
K(34Q)
0.026;-42080.0
44(35)
0.020;-52415.0
3447
0.010;-57383.8
34(4T)
0.025;-46949.4
44(3K)
0.024;-43670.0
4(357)
0.012;-56290.6
49(35)
0.013;-54104.4
(35)(4Q)
0.037;-43670.0
36(45)
0.008;-57383.8
3(459)
0.011;-54104.4
(45)(3Q)
0.024;-43670.0
35(46)
0.007;-57383.8
35(48)
0.013;-55197.5
35(4T)
0.018;-53011.3
35(4Q)
0.017;-50825.0
46(36)
0.016;-49135.6
(36)(49)
0.021;-45856.2
4(36Q)
0.018;-49731.9
3(467)
0.012;-55197.5
(46)(3T)
0.033;-44763.1
3Q(46)
0.021;-49731.9
3467
0.004;-62352.5
3469
0.009;-60166.3
346J
0.010;-57980.0
346K
0.012;-55793.8
49(37)
0.014;-51918.1
(37)(4Q)
0.027;-41483.8
38(47)
0.012;-53011.3
3(47J)
0.023;-49731.9
3477
0.013;-54104.4
3479
0.008;-59073.1
347J
0.008;-56886.9
347K
0.016;-54700.6
4T(38)
0.025;-49731.9
(38)(4K)
0.040;-39297.5
3T(48)
0.018;-49731.9
3(48K)
0.030;-46452.5
38(4T)
0.021;-49731.9
38(4Q)
0.019;-47545.6
49(39)
0.030;-42576.9
(39)(4Q)
0.041;-39297.5
3T(49)
0.024;-48638.8
3(49K)
0.032;-45359.4
39(4J)
0.017;-47545.6
39(4K)
0.032;-45359.4
4(3TQ)
0.024;-45359.4
3(4TJ)
0.023;-46452.5
34TT
0.023;-47545.6
34TQ
0.020;-52514.4
(3J)(4Q)
0.043;-37111.3
3Q(4J)
0.024;-44266.2
34JQ
0.017;-51421.3
(3Q)(4K)
0.055;-34925.0
3Q(4K)
0.041;-42080.0
5(356)
0.021;-49135.6
58(35)
0.028;-46949.4
(35)(5J)
0.054;-36515.0
6(356)
0.026;-48042.5
T(356)
0.017;-50825.0
6(357)
0.015;-54104.4
69(35)
0.015;-51918.1
(35)(6Q)
0.048;-41483.8
(3579)
0.018;-50825.0
(357K)
0.025;-46452.5
79(35)
0.021;-50825.0
(35)(7Q)
0.036;-40390.6
(358T)
0.022;-48638.8
88(35)
0.039;-43670.0
(35)(8J)
0.030;-40390.6
9(359)
0.038;-41483.8
K(359)
0.030;-44266.2
9(35Q)
0.024;-45359.4
J(35T)
0.028;-45359.4
TJ(35)
0.023;-45359.4
(35JQ)
0.029;-43173.1
J(35K)
0.034;-42080.0
(35)(QK)
0.057;-33831.9
55(37)
0.024;-48042.5
3559
0.013;-53011.3
35(5Q)
0.035;-42576.9
(36)(57)
0.020;-46949.4
5(36T)
0.016;-50825.0
5Q(36)
0.024;-48638.8
(56)(38)
0.033;-45856.2
3T(56)
0.017;-50825.0
3(56K)
0.021;-47545.6
36(58)
0.014;-53011.3
36(5T)
0.020;-50825.0
36(5Q)
0.026;-48638.8
57(37)
0.028;-45856.2
(37)(5T)
0.036;-42576.9
5(37K)
0.021;-46452.5
3(579)
0.014;-50825.0
(57)(3Q)
0.038;-40390.6
37(58)
0.017;-51918.1
37(5T)
0.024;-49731.9
37(5Q)
0.027;-47545.6
58(38)
0.028;-43670.0
(38)(5J)
0.045;-40390.6
38(58)
0.028;-43670.0
3(58J)
0.032;-47545.6
3588
0.017;-50825.0
358T
0.008;-55793.8
358Q
0.014;-53607.5
(39)(5T)
0.034;-40390.6
5(39K)
0.037;-44266.2
3(59J)
0.033;-46452.5
3599
0.018;-48638.8
359J
0.015;-53607.5
359K
0.017;-51421.3
5Q(3T)
0.035;-44266.2
(5T)(3Q)
0.051;-37111.3
3T(5J)
0.034;-45359.4
3T(5K)
0.030;-43173.1
5(3JK)
0.033;-42080.0
3(5JK)
0.040;-42080.0
3J(5K)
0.043;-42080.0
3Q(5Q)
0.046;-34925.0
35QK
0.030;-48141.9
67(36)
0.032;-45856.2
(36)(6T)
0.054;-35421.9
6(36K)
0.040;-39297.5
(367T)
0.025;-48638.8
77(36)
0.029;-44763.1
(36)(7T)
0.046;-41483.8
7(36K)
0.025;-45359.4
(368J)
0.032;-46452.5
(36)(89)
0.035;-41483.8
8(36Q)
0.034;-45359.4
T(369)
0.033;-46452.5
9(36T)
0.024;-46452.5
9Q(36)
0.033;-44266.2
Q(36T)
0.028;-43173.1
(36)(TQ)
0.042;-36018.1
(36JK)
0.032;-40986.9
JK(36)
0.034;-40986.9
K(36K)
0.053;-31645.6
3668
0.020;-51918.1
36(6J)
0.032;-41483.8
(37)(67)
0.038;-37608.1
6(37T)
0.023;-48638.8
6Q(37)
0.026;-46452.5
(67)(39)
0.029;-42576.9
3J(67)
0.026;-47545.6
67(38)
0.019;-50825.0
67(3T)
0.024;-48638.8
67(3Q)
0.028;-46452.5
(38)(68)
0.067;-35421.9
6(38J)
0.023;-46452.5
6K(38)
0.041;-44266.2
(68)(3J)
0.048;-39297.5
3K(68)
0.033;-44266.2
36(8T)
0.028;-47545.6
36(8Q)
0.032;-45359.4
6(39T)
0.024;-46452.5
6Q(39)
0.033;-44266.2
(69)(3J)
0.038;-38204.4
3K(69)
0.040;-43173.1
36(9J)
0.026;-45359.4
36(9K)
0.043;-43173.1
(3T)(6Q)
0.060;-36018.1
3J(6T)
0.032;-44266.2
6T(3J)
0.030;-44266.2
6T(3K)
0.029;-42080.0
6Q(3J)
0.028;-42080.0
(6J)(3K)
0.052;-33831.9
6J(3K)
0.035;-40986.9
6K(3Q)
0.044;-39893.8
36(QK)
0.030;-39893.8
(37)(78)
0.051;-35421.9
7(37J)
0.049;-39297.5
7K(37)
0.040;-37111.3
(378Q)
0.032;-44266.2
8(37T)
0.023;-46452.5
8Q(37)
0.028;-44266.2
J(379)
0.025;-44266.2
9T(37)
0.033;-45359.4
(37)(9K)
0.067;-34925.0
K(37T)
0.029;-40986.9
T(37K)
0.033;-40986.9
JJ(37)
0.045;-34925.0
(37QK)
0.039;-38800.6
3777
0.035;-43670.0
37(7T)
0.031;-40390.6
77(3K)
0.054;-37111.3
7(38T)
0.030;-46452.5
7Q(38)
0.032;-44266.2
(78)(3T)
0.036;-39297.5
3Q(78)
0.029;-44266.2
3789
0.014;-54700.6
378J
0.014;-52514.4
378K
0.021;-50328.1
7J(39)
0.035;-44266.2
(79)(3T)
0.044;-38204.4
3Q(79)
0.030;-43173.1
379T
0.015;-52514.4
379Q
0.015;-50328.1
(3T)(7J)
0.060;-36018.1
3T(7T)
0.046;-37111.3
3(7TK)
0.035;-40986.9
3T(7Q)
0.030;-42080.0
7J(3J)
0.054;-34925.0
(7J)(3Q)
0.049;-33831.9
3J(7Q)
0.042;-40986.9
7Q(3Q)
0.080;-32738.8
37QQ
0.046;-39893.8
37KK
0.039;-37707.5
8(38J)
0.045;-37111.3
8K(38)
0.073;-34925.0
(389K)
0.027;-40986.9
9J(38)
0.037;-43173.1
(38TJ)
0.031;-42080.0
(38)(TJ)
0.055;-34925.0
J(38J)
0.045;-33831.9
JQ(38)
0.048;-39893.8
Q(38K)
0.049;-37707.5
3889
0.028;-46452.5
38(8Q)
0.059;-36018.1
(39)(8T)
0.042;-37111.3
8(39K)
0.033;-40986.9
3(89J)
0.031;-43173.1
3899
0.025;-45359.4
389J
0.022;-50328.1
389K
0.019;-48141.9
8Q(3T)
0.040;-40986.9
(8T)(3Q)
0.055;-33831.9
3T(8J)
0.033;-42080.0
3T(8K)
0.036;-39893.8
8(3JK)
0.042;-38800.6
3(8JK)
0.035;-38800.6
3J(8K)
0.051;-38800.6
3Q(8Q)
0.080;-31645.6
38QK
0.034;-44862.5
9T(39)
0.042;-36018.1
(39)(9K)
0.102;-25583.8
K(39T)
0.044;-38800.6
T(39K)
0.041;-38800.6
JJ(39)
0.058;-32738.8
(39QK)
0.043;-36614.4
3999
0.056;-37111.3
39(9Q)
0.060;-33831.9
(3T)(9J)
0.058;-33831.9
3T(9T)
0.046;-34925.0
3(9TK)
0.044;-38800.6
3T(9Q)
0.047;-39893.8
9J(3J)
0.046;-32738.8
(9J)(3Q)
0.066;-31645.6
3J(9Q)
0.041;-38800.6
9Q(3Q)
0.083;-30552.5
39QQ
0.042;-37707.5
39KK
0.069;-35521.2
T(3TK)
0.068;-30552.5
JJ(3T)
0.079;-31645.6
(3TQK)
0.042;-35521.2
3TTT
0.075;-33831.9
3T(TK)
0.063;-30552.5
(3J)(TK)
0.086;-29459.4
3K(TJ)
0.054;-36614.4
3T(JK)
0.058;-36614.4
(TQ)(3K)
0.068;-28366.2
(3K)(TK)
0.088;-20118.1
J(3JK)
0.077;-28366.2
(3J)(QK)
0.082;-27273.1
JJ(3K)
0.066;-28366.2
3Q(JQ)
0.068;-28366.2
3JQK
0.029;-41583.1
QK(3Q)
0.099;-26180.0
QK(3K)
0.073;-25086.9
44(46)
0.037;-43073.8
44(4T)
0.043;-38701.2
(45)(45)
0.067;-35918.8
4(458)
0.019;-46949.4
4T(45)
0.028;-44763.1
(45)(4K)
0.065;-34328.8
4457
0.012;-55197.5
44(5T)
0.033;-44763.1
45(4K)
0.037;-41483.8
4(468)
0.025;-45856.2
4T(46)
0.033;-43670.0
(46)(4K)
0.046;-33235.6
4468
0.013;-53011.3
44(6J)
0.032;-42576.9
(47)(47)
0.067;-31546.2
4(47T)
0.033;-42576.9
4Q(47)
0.041;-40390.6
47(49)
0.027;-43670.0
447J
0.021;-48638.8
48(48)
0.045;-36515.0
(48)(4J)
0.056;-33235.6
4488
0.030;-43670.0
44(8J)
0.041;-40390.6
(49)(49)
0.077;-27173.8
4(49Q)
0.049;-38204.4
44(9T)
0.042;-40390.6
49(4K)
0.043;-37111.3
4(4TQ)
0.051;-37111.3
44(TJ)
0.046;-38204.4
(4J)(4J)
0.099;-22801.2
44JJ
0.045;-37111.3
4Q(4Q)
0.078;-27770.0
(4K)(4K)
0.120;-18428.8
(45)(57)
0.050;-39794.4
5(45T)
0.035;-43670.0
5Q(45)
0.043;-41483.8
8(456)
0.019;-51918.1
Q(456)
0.028;-47545.6
(45)(68)
0.027;-44763.1
6(45J)
0.026;-48638.8
6K(45)
0.027;-46452.5
(457J)
0.026;-47545.6
(45)(78)
0.034;-43670.0
7(45J)
0.022;-47545.6
7K(45)
0.025;-45359.4
(458Q)
0.037;-45359.4
8(45T)
0.028;-47545.6
8Q(45)
0.033;-45359.4
J(459)
0.025;-45359.4
9T(45)
0.032;-46452.5
(45)(9K)
0.057;-36018.1
K(45T)
0.038;-42080.0
T(45K)
0.033;-42080.0
JJ(45)
0.049;-36018.1
(45QK)
0.033;-39893.8
4555
0.022;-49135.6
45(58)
0.023;-45856.2
55(4J)
0.041;-42576.9
455K
0.026;-47545.6
58(46)
0.020;-51918.1
(46)(5J)
0.036;-41483.8
46(56)
0.021;-46949.4
4(569)
0.023;-50825.0
(56)(4Q)
0.031;-40390.6
46(57)
0.013;-53011.3
46(59)
0.019;-50825.0
46(5J)
0.019;-48638.8
46(5K)
0.023;-46452.5
5(479)
0.019;-49731.9
5J(47)
0.027;-47545.6
(57)(48)
0.032;-43670.0
4T(57)
0.028;-48638.8
4(57K)
0.032;-45359.4
47(59)
0.026;-49731.9
47(5J)
0.023;-47545.6
47(5K)
0.027;-45359.4
5(48T)
0.023;-47545.6
5Q(48)
0.024;-45359.4
(58)(4T)
0.031;-40390.6
4Q(58)
0.028;-45359.4
4589
0.010;-55793.8
458J
0.014;-53607.5
458K
0.019;-51421.3
5J(49)
0.028;-45359.4
(59)(4T)
0.050;-39297.5
4Q(59)
0.025;-44266.2
459T
0.016;-53607.5
459Q
0.017;-51421.3
(4T)(5J)
0.054;-37111.3
4T(5T)
0.042;-38204.4
4(5TK)
0.033;-42080.0
4T(5Q)
0.029;-43173.1
5J(4J)
0.046;-36018.1
(5J)(4Q)
0.049;-34925.0
4J(5Q)
0.035;-42080.0
5Q(4Q)
0.068;-33831.9
45QQ
0.045;-40986.9
45KK
0.037;-38800.6
6(469)
0.036;-42576.9
6J(46)
0.047;-40390.6
(4678)
0.022;-49731.9
(467Q)
0.029;-45359.4
7(469)
0.018;-48638.8
7J(46)
0.030;-46452.5
(4689)
0.022;-47545.6
(468K)
0.028;-43173.1
8T(46)
0.024;-46452.5
(46)(8K)
0.056;-36018.1
Q(469)
0.038;-43173.1
(46)(9J)
0.053;-37111.3
T(46T)
0.045;-37111.3
T(46J)
0.046;-43173.1
TK(46)
0.049;-40986.9
(46)(JQ)
0.064;-33831.9
QQ(46)
0.048;-32738.8
46(67)
0.026;-44763.1
66(4T)
0.041;-41483.8
466Q
0.027;-46452.5
68(47)
0.024;-49731.9
(47)(6J)
0.042;-39297.5
47(67)
0.038;-43670.0
4(67T)
0.024;-47545.6
(67)(4K)
0.050;-37111.3
67(49)
0.024;-48638.8
67(4J)
0.021;-46452.5
67(4K)
0.028;-44266.2
69(48)
0.026;-47545.6
(48)(6Q)
0.048;-37111.3
49(68)
0.026;-47545.6
4(68Q)
0.027;-44266.2
46(89)
0.023;-47545.6
46(8J)
0.032;-45359.4
46(8K)
0.028;-43173.1
(49)(6J)
0.049;-37111.3
49(69)
0.039;-39297.5
4(69Q)
0.033;-43173.1
46(9T)
0.028;-45359.4
46(9Q)
0.025;-43173.1
6(4TJ)
0.032;-43173.1
6K(4T)
0.040;-40986.9
(6T)(4K)
0.059;-33831.9
6T(4Q)
0.043;-42080.0
(4J)(6J)
0.090;-27770.0
4J(6J)
0.051;-34925.0
6J(4Q)
0.039;-40986.9
(4Q)(6Q)
0.097;-25583.8
4K(6Q)
0.048;-38800.6
4K(6K)
0.071;-30552.5
79(47)
0.047;-40390.6
(47)(7Q)
0.067;-29956.3
(478T)
0.029;-45359.4
88(47)
0.038;-40390.6
(47)(8J)
0.044;-37111.3
9(479)
0.048;-38204.4
K(479)
0.041;-40986.9
9(47Q)
0.032;-42080.0
J(47T)
0.036;-42080.0
TJ(47)
0.049;-42080.0
(47JQ)
0.036;-39893.8
J(47K)
0.048;-38800.6
(47)(QK)
0.062;-30552.5
77(49)
0.030;-40390.6
477J
0.028;-45359.4
78(48)
0.032;-40390.6
(48)(7J)
0.038;-37111.3
48(78)
0.028;-40390.6
4(78J)
0.029;-44266.2
4788
0.024;-47545.6
478T
0.013;-52514.4
478Q
0.017;-50328.1
(49)(7T)
0.042;-37111.3
7(49K)
0.032;-40986.9
4(79J)
0.037;-43173.1
4799
0.031;-45359.4
479J
0.021;-50328.1
479K
0.020;-48141.9
7Q(4T)
0.036;-40986.9
(7T)(4Q)
0.059;-33831.9
4T(7J)
0.035;-42080.0
4T(7K)
0.042;-39893.8
7(4JK)
0.040;-38800.6
4(7JK)
0.041;-38800.6
4J(7K)
0.039;-38800.6
4Q(7Q)
0.059;-31645.6
47QK
0.025;-44862.5
89(48)
0.045;-38204.4
(48)(8Q)
0.076;-27770.0
(489J)
0.031;-42080.0
(48)(9T)
0.048;-36018.1
9(48K)
0.035;-39893.8
(48TK)
0.043;-38800.6
TQ(48)
0.050;-39893.8
K(48J)
0.036;-37707.5
Q(48Q)
0.064;-30552.5
KK(48)
0.078;-28366.2
88(4J)
0.044;-36018.1
488K
0.028;-40986.9
8J(49)
0.027;-42080.0
(89)(4T)
0.046;-36018.1
4Q(89)
0.031;-40986.9
489T
0.019;-50328.1
489Q
0.022;-48141.9
(4T)(8J)
0.053;-33831.9
4T(8T)
0.061;-34925.0
4(8TK)
0.038;-38800.6
4T(8Q)
0.037;-39893.8
8J(4J)
0.054;-32738.8
(8J)(4Q)
0.054;-31645.6
4J(8Q)
0.034;-38800.6
8Q(4Q)
0.084;-30552.5
48QQ
0.037;-37707.5
48KK
0.045;-35521.2
9(49Q)
0.051;-32738.8
J(49T)
0.042;-39893.8
TJ(49)
0.032;-39893.8
(49JQ)
0.040;-37707.5
J(49K)
0.041;-36614.4
(49)(QK)
0.090;-28366.2
99(4J)
0.058;-33831.9
499K
0.037;-38800.6
9Q(4T)
0.035;-38800.6
(9T)(4Q)
0.060;-31645.6
4T(9J)
0.036;-39893.8
4T(9K)
0.048;-37707.5
9(4JK)
0.045;-36614.4
4(9JK)
0.052;-36614.4
4J(9K)
0.037;-36614.4
4Q(9Q)
0.067;-29459.4
49QK
0.035;-42676.2
TJ(4T)
0.057;-31645.6
(4TJQ)
0.051;-36614.4
J(4TK)
0.040;-35521.2
(4T)(QK)
0.070;-27273.1
TT(4Q)
0.072;-30552.5
T(4JQ)
0.039;-36614.4
4(TJQ)
0.053;-36614.4
4T(JQ)
0.060;-36614.4
T(4QK)
0.062;-34428.1
TQ(4K)
0.053;-34428.1
JJ(4J)
0.105;-22304.4
(4JQK)
0.062;-33335.0
4JJJ
0.078;-29459.4
JQ(4Q)
0.073;-27273.1
4JQQ
0.064;-34428.1
4JKK
0.061;-32241.9
QQ(4K)
0.088;-25086.9
4KKK
0.096;-22900.6
55(59)
0.053;-36515.0
55(5K)
0.061;-32142.5
(56)(58)
0.054;-36515.0
5(56J)
0.040;-40390.6
5K(56)
0.057;-38204.4
56(59)
0.033;-42576.9
556J
0.019;-47545.6
57(57)
0.048;-36515.0
(57)(5T)
0.063;-33235.6
5(57K)
0.062;-37111.3
55(79)
0.028;-41483.8
57(5Q)
0.049;-38204.4
5(589)
0.048;-40390.6
5J(58)
0.040;-38204.4
58(59)
0.030;-40390.6
558J
0.025;-45359.4
59(59)
0.056;-32142.5
(59)(5Q)
0.074;-28863.1
559T
0.023;-45359.4
55(9K)
0.058;-34925.0
(5T)(5Q)
0.106;-27770.0
55TJ
0.032;-43173.1
5J(5J)
0.069;-27770.0
5J(5Q)
0.047;-33831.9
5(5QK)
0.058;-31645.6
5K(5K)
0.085;-23397.5
68(56)
0.032;-42576.9
(56)(6J)
0.066;-32142.5
7(567)
0.038;-42576.9
J(567)
0.024;-45359.4
78(56)
0.022;-48638.8
(56)(7J)
0.035;-38204.4
8(568)
0.029;-40390.6
Q(568)
0.043;-43173.1
(56)(8T)
0.046;-38204.4
8(56K)
0.040;-42080.0
(569Q)
0.042;-42080.0
9(56J)
0.032;-43173.1
9K(56)
0.044;-40986.9
TT(56)
0.057;-36018.1
(56)(TK)
0.048;-32738.8
J(56Q)
0.035;-39893.8
K(56Q)
0.040;-37707.5
66(57)
0.032;-43670.0
5669
0.016;-48638.8
56(6Q)
0.049;-38204.4
(57)(68)
0.036;-41483.8
6(57J)
0.023;-45359.4
6K(57)
0.033;-43173.1
(67)(5T)
0.045;-39297.5
5Q(67)
0.031;-44266.2
5678
0.010;-55793.8
567T
0.014;-53607.5
567Q
0.012;-51421.3
(58)(69)
0.046;-39297.5
6(58Q)
0.029;-43173.1
5(689)
0.025;-46452.5
(68)(5Q)
0.040;-36018.1
58(69)
0.026;-46452.5
58(6J)
0.027;-44266.2
58(6K)
0.040;-42080.0
6(59J)
0.032;-43173.1
6K(59)
0.040;-40986.9
(69)(5Q)
0.045;-34925.0
59(6T)
0.031;-44266.2
59(6Q)
0.040;-42080.0
6T(5T)
0.065;-36018.1
(5T)(6K)
0.067;-32738.8
5Q(6T)
0.037;-40986.9
56TJ
0.023;-49235.0
56TK
0.024;-47048.8
6K(5J)
0.040;-38800.6
56JJ
0.035;-40986.9
56JK
0.029;-45955.6
5(6QK)
0.058;-37707.5
6K(5K)
0.067;-29459.4
(57)(79)
0.060;-32142.5
7(57Q)
0.046;-36018.1
9(578)
0.023;-45359.4
K(578)
0.035;-40986.9
8(57J)
0.034;-43173.1
8K(57)
0.039;-40986.9
(579K)
0.050;-39893.8
9J(57)
0.029;-42080.0
(57TJ)
0.034;-40986.9
(57)(TJ)
0.061;-33831.9
J(57J)
0.055;-32738.8
JQ(57)
0.054;-38800.6
Q(57K)
0.052;-36614.4
5778
0.019;-47545.6
57(7J)
0.050;-37111.3
(58)(78)
0.061;-32142.5
7(58J)
0.029;-43173.1
7K(58)
0.041;-40986.9
(78)(5J)
0.045;-36018.1
5K(78)
0.033;-40986.9
57(8T)
0.024;-44266.2
57(8Q)
0.030;-42080.0
7(59T)
0.029;-43173.1
7Q(59)
0.028;-40986.9
(79)(5J)
0.048;-34925.0
5K(79)
0.042;-39893.8
57(9J)
0.035;-42080.0
57(9K)
0.042;-39893.8
(5T)(7Q)
0.086;-32738.8
5J(7T)
0.035;-40986.9
7T(5J)
0.034;-40986.9
7T(5K)
0.034;-38800.6
7Q(5J)
0.046;-38800.6
(7J)(5K)
0.064;-30552.5
7J(5K)
0.041;-37707.5
7K(5Q)
0.060;-36614.4
57(QK)
0.047;-36614.4
(58)(89)
0.063;-29956.3
8(58Q)
0.049;-33831.9
T(589)
0.026;-42080.0
9(58T)
0.031;-42080.0
9Q(58)
0.046;-39893.8
Q(58T)
0.039;-38800.6
(58)(TQ)
0.068;-31645.6
(58JK)
0.048;-36614.4
JK(58)
0.053;-36614.4
K(58K)
0.065;-27273.1
588T
0.035;-43173.1
58(8K)
0.062;-32738.8
(59)(8J)
0.065;-33831.9
59(89)
0.046;-36018.1
5(89Q)
0.041;-39893.8
58(9T)
0.041;-42080.0
58(9Q)
0.029;-39893.8
8(5TJ)
0.036;-39893.8
8K(5T)
0.042;-37707.5
(8T)(5K)
0.063;-30552.5
8T(5Q)
0.045;-38800.6
(5J)(8J)
0.099;-24490.6
5J(8J)
0.056;-31645.6
8J(5Q)
0.054;-37707.5
(5Q)(8Q)
0.095;-22304.4
5K(8Q)
0.057;-35521.2
5K(8K)
0.068;-27273.1
9J(59)
0.062;-32738.8
(59TJ)
0.050;-38800.6
(59)(TJ)
0.063;-31645.6
J(59J)
0.059;-30552.5
JQ(59)
0.052;-36614.4
Q(59K)
0.046;-34428.1
599T
0.034;-40986.9
59(9K)
0.070;-30552.5
(5T)(9Q)
0.068;-30552.5
5J(9T)
0.038;-38800.6
9T(5J)
0.045;-38800.6
9T(5K)
0.043;-36614.4
9Q(5J)
0.063;-36614.4
(9J)(5K)
0.061;-28366.2
9J(5K)
0.058;-35521.2
9K(5Q)
0.067;-34428.1
59(QK)
0.063;-34428.1
(5T)(TJ)
0.094;-23397.5
J(5TJ)
0.074;-29459.4
JQ(5T)
0.064;-35521.2
Q(5TK)
0.070;-33335.0
5TTJ
0.042;-37707.5
TJ(5J)
0.076;-29459.4
(TJ)(5Q)
0.063;-28366.2
5J(TQ)
0.053;-35521.2
TQ(5Q)
0.075;-27273.1
5TQQ
0.057;-34428.1
5TKK
0.066;-32241.9
Q(5JQ)
0.064;-26180.0
KK(5J)
0.082;-23993.7
(5Q)(JQ)
0.104;-19025.0
5K(JQ)
0.053;-32241.9
5K(JK)
0.090;-23993.7
5QQQ
0.073;-25086.9
KK(5K)
0.124;-14652.5
6669
0.044;-40390.6
666K
0.045;-36018.1
69(67)
0.044;-39297.5
(67)(6Q)
0.092;-28863.1
6678
0.021;-47545.6
66(7J)
0.040;-37111.3
(68)(68)
0.078;-24987.5
6(68J)
0.046;-36018.1
6K(68)
0.061;-33831.9
68(6J)
0.049;-36018.1
668K
0.045;-40986.9
6J(69)
0.051;-34925.0
69(6T)
0.059;-36018.1
669Q
0.036;-40986.9
6J(6T)
0.046;-33831.9
6T(6J)
0.058;-33831.9
66TK
0.045;-38800.6
6K(6J)
0.058;-30552.5
(6Q)(6Q)
0.131;-16242.5
66QK
0.047;-36614.4
7(679)
0.049;-38204.4
7J(67)
0.057;-36018.1
(6789)
0.036;-44266.2
(678K)
0.040;-39893.8
8T(67)
0.040;-43173.1
(67)(8K)
0.060;-32738.8
Q(679)
0.045;-39893.8
(67)(9J)
0.057;-33831.9
T(67T)
0.063;-33831.9
T(67J)
0.047;-39893.8
TK(67)
0.059;-37707.5
(67)(JQ)
0.080;-30552.5
QQ(67)
0.061;-29459.4
67(78)
0.039;-39297.5
77(6J)
0.049;-36018.1
677K
0.028;-40986.9
7T(68)
0.027;-43173.1
(68)(7K)
0.068;-32738.8
6T(78)
0.034;-43173.1
6(78K)
0.035;-39893.8
68(7T)
0.033;-43173.1
68(7Q)
0.028;-40986.9
79(69)
0.043;-36018.1
(69)(7Q)
0.063;-32738.8
6T(79)
0.044;-42080.0
6(79K)
0.036;-38800.6
69(7J)
0.044;-40986.9
69(7K)
0.042;-38800.6
7(6TQ)
0.036;-38800.6
6(7TJ)
0.044;-39893.8
67TT
0.030;-40986.9
67TQ
0.026;-45955.6
(6J)(7Q)
0.070;-30552.5
6Q(7J)
0.039;-37707.5
67JQ
0.027;-44862.5
(6Q)(7K)
0.073;-28366.2
6Q(7K)
0.043;-35521.2
8(689)
0.046;-36018.1
8J(68)
0.052;-33831.9
(689T)
0.027;-40986.9
99(68)
0.067;-34925.0
(68)(9Q)
0.053;-31645.6
(68TQ)
0.054;-37707.5
T(68Q)
0.043;-37707.5
Q(68J)
0.049;-36614.4
(68)(JK)
0.086;-28366.2
QK(68)
0.064;-34428.1
68(8T)
0.044;-34925.0
88(6K)
0.063;-31645.6
8(69J)
0.043;-39893.8
8K(69)
0.049;-37707.5
(89)(6Q)
0.080;-31645.6
69(8T)
0.029;-40986.9
69(8Q)
0.050;-38800.6
8T(6T)
0.069;-32738.8
(6T)(8K)
0.063;-29459.4
6Q(8T)
0.057;-37707.5
68TJ
0.031;-45955.6
68TK
0.026;-43769.4
8K(6J)
0.053;-35521.2
68JJ
0.058;-37707.5
68JK
0.035;-42676.2
6(8QK)
0.068;-34428.1
8K(6K)
0.102;-26180.0
(69)(9J)
0.084;-24490.6
T(69T)
0.070;-31645.6
T(69J)
0.057;-37707.5
TK(69)
0.046;-35521.2
(69)(JQ)
0.099;-28366.2
QQ(69)
0.072;-27273.1
69(9T)
0.050;-32738.8
99(6K)
0.077;-29459.4
9(6TQ)
0.055;-36614.4
6(9TJ)
0.049;-37707.5
69TT
0.051;-38800.6
69TQ
0.034;-43769.4
(6J)(9Q)
0.083;-28366.2
6Q(9J)
0.051;-35521.2
69JQ
0.036;-42676.2
(6Q)(9K)
0.090;-26180.0
6Q(9K)
0.070;-33335.0
T(6TJ)
0.081;-29459.4
TK(6T)
0.080;-27273.1
(6T)(JQ)
0.080;-27273.1
QQ(6T)
0.086;-26180.0
6T(TJ)
0.063;-29459.4
(6J)(TJ)
0.110;-21211.3
6J(TJ)
0.076;-28366.2
TJ(6Q)
0.062;-34428.1
(6Q)(TQ)
0.129;-19025.0
6K(TQ)
0.066;-32241.9
6K(TK)
0.077;-23993.7
JK(6J)
0.087;-25086.9
K(6JK)
0.094;-22900.6
6JJK
0.058;-32241.9
6(JQK)
0.074;-31148.8
JK(6K)
0.096;-22900.6
KK(6Q)
0.092;-21807.5
6QKK
0.080;-28962.5
77(7T)
0.068;-28863.1
(78)(78)
0.122;-22801.2
7(78J)
0.065;-33831.9
7K(78)
0.062;-31645.6
78(7J)
0.061;-33831.9
778K
0.046;-38800.6
7J(79)
0.051;-32738.8
79(7T)
0.063;-33831.9
779Q
0.039;-38800.6
7J(7T)
0.064;-31645.6
7T(7J)
0.060;-31645.6
77TK
0.040;-36614.4
7K(7J)
0.057;-28366.2
(7Q)(7Q)
0.141;-14056.2
77QK
0.041;-34428.1
8(78T)
0.053;-33831.9
8Q(78)
0.064;-31645.6
J(789)
0.052;-38800.6
9T(78)
0.035;-39893.8
(78)(9K)
0.075;-29459.4
K(78T)
0.059;-35521.2
T(78K)
0.064;-35521.2
JJ(78)
0.059;-29459.4
(78QK)
0.044;-33335.0
7888
0.044;-36018.1
78(8J)
0.073;-32738.8
(79)(89)
0.090;-26676.9
8(79Q)
0.055;-37707.5
7(89T)
0.045;-39893.8
(89)(7K)
0.062;-29459.4
89(7J)
0.041;-38800.6
89(7K)
0.040;-36614.4
8J(7T)
0.037;-37707.5
(8T)(7J)
0.075;-30552.5
7K(8T)
0.051;-35521.2
78(TQ)
0.046;-36614.4
8(7JQ)
0.062;-35521.2
7(8JQ)
0.040;-35521.2
78(JQ)
0.052;-35521.2
8(7QK)
0.067;-33335.0
8Q(7K)
0.051;-33335.0
99(79)
0.079;-25583.8
(79)(9Q)
0.100;-22304.4
(79TQ)
0.046;-35521.2
T(79Q)
0.047;-35521.2
Q(79J)
0.047;-34428.1
(79)(JK)
0.092;-26180.0
QK(79)
0.079;-32241.9
79(9J)
0.067;-30552.5
(7T)(9T)
0.077;-23397.5
9(7TK)
0.057;-34428.1
7(9TQ)
0.043;-35521.2
79(TJ)
0.056;-36614.4
79(TK)
0.043;-34428.1
(7J)(9K)
0.087;-26180.0
7K(9J)
0.059;-33335.0
79(JK)
0.056;-33335.0
(9Q)(7K)
0.091;-25086.9
(7K)(9K)
0.093;-16838.8
T(7TQ)
0.072;-27273.1
Q(7TJ)
0.048;-33335.0
(7T)(JK)
0.106;-25086.9
QK(7T)
0.055;-31148.8
7T(TQ)
0.094;-27273.1
(7J)(TQ)
0.069;-26180.0
7Q(TJ)
0.047;-33335.0
7TJQ
0.036;-40490.0
(7Q)(TK)
0.082;-23993.7
7Q(TK)
0.074;-31148.8
J(7JQ)
0.083;-25086.9
K(7JQ)
0.077;-30055.6
JJ(7Q)
0.072;-25086.9
J(7QK)
0.061;-30055.6
JQ(7K)
0.056;-30055.6
QQ(7Q)
0.131;-15745.6
7Q(QK)
0.093;-21807.5
8888
0.099;-27770.0
888Q
0.066;-30552.5
8(89J)
0.061;-30552.5
8K(89)
0.082;-28366.2
89(8Q)
0.055;-29459.4
8(8TJ)
0.064;-29459.4
8K(8T)
0.076;-27273.1
8T(8K)
0.070;-27273.1
8(8JK)
0.081;-26180.0
88(JK)
0.076;-26180.0
8Q(8K)
0.093;-25086.9
(89)(9T)
0.090;-23397.5
9(89K)
0.089;-27273.1
(89TK)
0.061;-33335.0
TQ(89)
0.051;-34428.1
K(89J)
0.054;-32241.9
Q(89Q)
0.090;-25086.9
KK(89)
0.087;-22900.6
99(8Q)
0.079;-28366.2
9(8TJ)
0.049;-35521.2
9K(8T)
0.059;-33335.0
(9T)(8K)
0.090;-26180.0
9T(8Q)
0.053;-34428.1
(8J)(9J)
0.091;-20118.1
8J(9J)
0.081;-27273.1
9J(8Q)
0.058;-33335.0
(8Q)(9Q)
0.159;-17931.9
8K(9Q)
0.048;-31148.8
8K(9K)
0.105;-22900.6
TQ(8T)
0.104;-26180.0
K(8TJ)
0.052;-31148.8
Q(8TQ)
0.106;-23993.7
KK(8T)
0.108;-21807.5
