AAAA
0.367;3610.0
5AAA
0.255;-23.7
9AAA
0.278;911.3
KAAA
0.265;1846.3
4A(2A)
0.223;-3062.5
(2A)(7A)
0.209;-831.3
A(2TA)
0.248;-1660.0
QA(2A)
0.197;-1192.5
2A(4A)
0.249;-3062.5
26AA
0.227;-4125.0
AA(29)
0.187;-1893.7
2A(QA)
0.193;-1192.5
A(34A)
0.226;-2828.7
6A(3A)
0.275;-2361.2
(3A)(9A)
0.277;-130.0
A(3QA)
0.301;-958.8
AA(34)
0.194;-2828.7
3A(7A)
0.248;-2127.5
39AA
0.238;-3190.0
AA(3Q)
0.242;-958.8
(4A)(5A)
0.238;-831.3
A(48A)
0.263;-1660.0
TA(4A)
0.223;-1192.5
(4A)(KA)
0.293;1038.8
46AA
0.182;-3657.5
AA(49)
0.289;-1426.2
4A(QA)
0.287;-725.0
A(56A)
0.213;-1893.7
8A(5A)
0.205;-1426.2
(5A)(JA)
0.300;805.0
55AA
0.178;-2127.5
AA(58)
0.250;-1426.2
5A(JA)
0.254;-725.0
5KAA
0.213;-1787.5
8A(6A)
0.223;-1192.5
(6A)(JA)
0.276;1038.8
66AA
0.257;-1660.0
AA(69)
0.236;-958.8
6A(QA)
0.213;-257.5
A(78A)
0.201;-958.8
TA(7A)
0.270;-491.2
(7A)(KA)
0.287;1740.0
79AA
0.213;-2255.0
AA(7Q)
0.253;-23.8
(8A)(9A)
0.295;1038.8
A(8QA)
0.269;210.0
AA(89)
0.286;-491.2
8A(QA)
0.304;210.0
A(9TA)
0.290;-23.8
QA(9A)
0.341;443.7
9A(JA)
0.216;210.0
9KAA
0.221;-852.5
QA(TA)
0.289;677.5
TA(QA)
0.307;677.5
A(JQA)
0.338;911.2
AA(JQ)
0.296;911.2
(QA)(KA)
0.296;2908.7
KKAA
0.282;1612.5
2(25A)
0.163;-5633.7
27(2A)
0.175;-5166.2
(2T)(2A)
0.228;-2935.0
2(2KA)
0.180;-3763.7
(236A)
0.160;-6696.2
(23TA)
0.146;-5761.2
33(2A)
0.144;-5867.5
(36)(2A)
0.161;-5166.2
3(29A)
0.217;-5995.0
3J(2A)
0.186;-5527.5
(245A)
0.179;-6696.2
(249A)
0.161;-5761.2
(24KA)
0.212;-4826.2
46(2A)
0.165;-6462.5
(49)(2A)
0.259;-4231.2
4(2QA)
0.187;-5060.0
6(25A)
0.189;-6228.7
T(25A)
0.211;-5293.7
5(26A)
0.154;-6228.7
58(2A)
0.146;-5761.2
(5J)(2A)
0.247;-3530.0
6(26A)
0.188;-4465.0
T(26A)
0.156;-5060.0
6(27A)
0.153;-5761.2
69(2A)
0.206;-5293.7
(6Q)(2A)
0.181;-3062.5
(279A)
0.171;-5060.0
(27KA)
0.226;-4125.0
79(2A)
0.169;-5060.0
(7Q)(2A)
0.237;-2828.8
(28TA)
0.190;-4592.5
88(2A)
0.197;-3530.0
(8J)(2A)
0.224;-2828.8
9(29A)
0.237;-3062.5
K(29A)
0.212;-3657.5
9(2QA)
0.166;-3891.3
J(2TA)
0.147;-3891.3
TJ(2A)
0.181;-3891.3
(2JQA)
0.232;-3423.7
J(2KA)
0.191;-3190.0
(QK)(2A)
0.221;-1426.2
22(4A)
0.157;-5867.5
226A
0.156;-6930.0
2A(29)
0.195;-4698.7
22(QA)
0.167;-3997.5
2(34A)
0.153;-7163.7
26(3A)
0.126;-6696.2
(29)(3A)
0.171;-4465.0
2(3QA)
0.171;-5293.7
A(234)
0.138;-7163.7
(23)(7A)
0.175;-4932.5
9A(23)
0.174;-5995.0
A(23Q)
0.219;-5293.7
2A(34)
0.153;-7163.7
2A(36)
0.172;-6696.2
2A(38)
0.162;-6228.7
2A(3T)
0.189;-5761.2
2A(3Q)
0.158;-5293.7
2(45A)
0.149;-6696.2
27(4A)
0.192;-6228.7
(2T)(4A)
0.211;-3997.5
2(4KA)
0.177;-4826.2
A(246)
0.198;-6462.5
(24)(9A)
0.182;-4231.2
JA(24)
0.182;-5293.7
24(5A)
0.146;-6696.2
24(7A)
0.217;-6228.7
24(9A)
0.198;-5761.2
24(JA)
0.188;-5293.7
24(KA)
0.188;-4826.2
26(5A)
0.205;-6228.7
(29)(5A)
0.250;-3997.5
2(5QA)
0.220;-4826.2
A(256)
0.165;-6228.7
(25)(9A)
0.178;-3997.5
JA(25)
0.160;-5060.0
25(6A)
0.184;-6228.7
25(8A)
0.216;-5761.2
25(TA)
0.196;-5293.7
25(QA)
0.150;-4826.2
(26)(6A)
0.197;-2935.0
2(69A)
0.151;-5293.7
2J(6A)
0.196;-4826.2
(26)(7A)
0.220;-4231.2
9A(26)
0.186;-5293.7
A(26Q)
0.180;-4592.5
2A(67)
0.170;-5761.2
2A(69)
0.196;-5293.7
2A(6J)
0.205;-4826.2
2A(6K)
0.175;-4358.8
(29)(7A)
0.202;-3530.0
2(7QA)
0.183;-4358.8
A(278)
0.198;-5293.7
(27)(JA)
0.210;-3062.5
KA(27)
0.163;-4125.0
2A(79)
0.144;-5060.0
2A(7J)
0.219;-4592.5
2A(7K)
0.206;-4125.0
(2T)(8A)
0.153;-3062.5
2(8KA)
0.245;-3891.3
A(28T)
0.139;-4592.5
(28)(KA)
0.224;-2361.2
28(TA)
0.214;-4592.5
28(QA)
0.190;-4125.0
(29)(9A)
0.191;-1532.5
2(9QA)
0.195;-3891.3
A(29T)
0.161;-4358.8
(29)(KA)
0.198;-2127.5
29(JA)
0.227;-4125.0
29(KA)
0.190;-3657.5
2J(TA)
0.220;-3891.3
(2T)(JA)
0.200;-2361.2
KA(2T)
0.189;-3423.7
2A(TQ)
0.192;-3657.5
2(JQA)
0.196;-3423.7
A(2JQ)
0.205;-3423.7
2A(JQ)
0.170;-3423.7
2(QKA)
0.165;-2956.2
2Q(KA)
0.157;-2956.2
33(3A)
0.206;-4103.8
(36)(3A)
0.193;-3402.5
3(39A)
0.214;-4231.2
3J(3A)
0.241;-3763.7
(345A)
0.174;-6462.5
(349A)
0.180;-5527.5
(34KA)
0.145;-4592.5
46(3A)
0.152;-6228.7
(49)(3A)
0.191;-3997.5
4(3QA)
0.188;-4826.2
6(35A)
0.139;-5995.0
T(35A)
0.194;-5060.0
5(36A)
0.207;-5995.0
58(3A)
0.185;-5527.5
(5J)(3A)
0.179;-3296.2
6(36A)
0.193;-4231.2
T(36A)
0.167;-4826.2
6(37A)
0.195;-5527.5
69(3A)
0.158;-5060.0
(6Q)(3A)
0.192;-2828.8
(379A)
0.183;-4826.2
(37KA)
0.180;-3891.3
79(3A)
0.150;-4826.2
(7Q)(3A)
0.254;-2595.0
(38TA)
0.202;-4358.8
88(3A)
0.211;-3296.2
(8J)(3A)
0.279;-2595.0
9(39A)
0.173;-2828.7
K(39A)
0.233;-3423.7
9(3QA)
0.157;-3657.5
J(3TA)
0.253;-3657.5
TJ(3A)
0.160;-3657.5
(3JQA)
0.262;-3190.0
J(3KA)
0.216;-2956.2
(QK)(3A)
0.227;-1192.5
33(5A)
0.174;-5166.2
337A
0.164;-6228.7
3A(3T)
0.152;-3997.5
33(KA)
0.196;-3296.2
3(46A)
0.164;-6228.7
38(4A)
0.209;-5761.2
(3J)(4A)
0.211;-3530.0
4A(34)
0.165;-5166.2
A(347)
0.161;-5995.0
(34)(TA)
0.195;-3763.7
QA(34)
0.180;-4826.2
345A
0.136;-7992.5
347A
0.165;-7525.0
349A
0.168;-7057.5
34JA
0.171;-6590.0
34KA
0.146;-6122.5
37(5A)
0.188;-5761.2
(3T)(5A)
0.192;-3530.0
3(5KA)
0.170;-4358.8
A(357)
0.215;-5761.2
(35)(TA)
0.197;-3530.0
QA(35)
0.167;-4592.5
356A
0.173;-7525.0
358A
0.133;-7057.5
35TA
0.203;-6590.0
35QA
0.162;-6122.5
(37)(6A)
0.222;-3997.5
3(6TA)
0.208;-4826.2
3Q(6A)
0.144;-4358.8
(36)(8A)
0.173;-3763.7
TA(36)
0.193;-4826.2
A(36K)
0.189;-4125.0
6A(38)
0.185;-5293.7
6A(3T)
0.203;-4826.2
6A(3Q)
0.236;-4358.8
37(7A)
0.213;-3763.7
(3T)(7A)
0.277;-3062.5
3(7KA)
0.192;-3891.3
A(379)
0.177;-4826.2
(37)(QA)
0.238;-2595.0
7A(38)
0.211;-5060.0
7A(3T)
0.171;-4592.5
7A(3Q)
0.158;-4125.0
38(8A)
0.212;-3296.2
(3J)(8A)
0.223;-2595.0
8A(38)
0.199;-3296.2
A(38J)
0.211;-4125.0
388A
0.183;-4826.2
38TA
0.198;-5888.8
38QA
0.178;-5421.3
(3T)(9A)
0.232;-2595.0
3(9KA)
0.220;-3423.7
A(39J)
0.222;-3891.3
399A
0.223;-4358.8
39JA
0.136;-5421.3
39KA
0.153;-4953.7
3Q(TA)
0.220;-3423.7
(3T)(QA)
0.285;-1893.7
TA(3J)
0.258;-3657.5
TA(3K)
0.202;-3190.0
3(JKA)
0.208;-2956.2
A(3JK)
0.181;-2956.2
JA(3K)
0.174;-2956.2
QA(3Q)
0.266;-1426.2
3QKA
0.182;-4252.5
45(4A)
0.188;-4698.7
(48)(4A)
0.211;-2467.5
4(4JA)
0.217;-3296.2
4K(4A)
0.191;-2828.7
(459A)
0.178;-5060.0
(45KA)
0.182;-4125.0
57(4A)
0.180;-5527.5
(5T)(4A)
0.175;-3296.2
5(4KA)
0.213;-4125.0
(469A)
0.174;-4826.2
(46KA)
0.217;-3891.3
68(4A)
0.166;-5060.0
(6J)(4A)
0.206;-2828.8
7(47A)
0.230;-3530.0
J(47A)
0.156;-4125.0
78(4A)
0.215;-4826.2
(7J)(4A)
0.230;-2595.0
8(48A)
0.203;-3062.5
Q(48A)
0.188;-3657.5
(8T)(4A)
0.199;-2595.0
8(4KA)
0.237;-3423.7
(49QA)
0.165;-3423.7
9(4JA)
0.159;-3657.5
9K(4A)
0.274;-3190.0
TT(4A)
0.180;-2127.5
(TK)(4A)
0.221;-1426.2
J(4QA)
0.205;-2956.2
K(4QA)
0.198;-2488.7
44(5A)
0.142;-4698.7
447A
0.148;-5761.2
4A(4T)
0.190;-3530.0
44(KA)
0.187;-2828.7
4(57A)
0.163;-5527.5
49(5A)
0.163;-5060.0
(4Q)(5A)
0.208;-2828.8
6A(45)
0.181;-5761.2
A(459)
0.196;-5060.0
(45)(QA)
0.175;-2828.8
5A(46)
0.147;-5761.2
5A(48)
0.178;-5293.7
5A(4T)
0.173;-4826.2
5A(4Q)
0.196;-4358.8
46(6A)
0.205;-3997.5
(49)(6A)
0.213;-3296.2
4(6QA)
0.207;-4125.0
A(467)
0.214;-5293.7
(46)(TA)
0.172;-3062.5
QA(46)
0.158;-4125.0
467A
0.168;-6823.7
469A
0.161;-6356.2
46JA
0.159;-5888.8
46KA
0.161;-5421.3
49(7A)
0.227;-4592.5
(4Q)(7A)
0.227;-2361.2
8A(47)
0.229;-4826.2
A(47J)
0.210;-4125.0
477A
0.164;-5060.0
479A
0.134;-6122.5
47JA
0.150;-5655.0
47KA
0.215;-5187.5
4T(8A)
0.190;-4125.0
(4K)(8A)
0.203;-1893.7
TA(48)
0.177;-4125.0
A(48K)
0.193;-3423.7
8A(4T)
0.188;-4125.0
8A(4Q)
0.245;-3657.5
49(9A)
0.201;-2595.0
(4Q)(9A)
0.230;-1893.7
TA(49)
0.224;-3891.3
A(49K)
0.171;-3190.0
9A(4J)
0.201;-3657.5
9A(4K)
0.233;-3190.0
4(TQA)
0.203;-3190.0
A(4TJ)
0.207;-3423.7
4TTA
0.213;-3657.5
4TQA
0.165;-4720.0
(4Q)(JA)
0.244;-1426.2
QA(4J)
0.215;-2956.2
4JQA
0.164;-4486.2
(4K)(QA)
0.219;-958.8
QA(4K)
0.240;-2488.7
5(56A)
0.210;-3997.5
58(5A)
0.207;-3530.0
(5J)(5A)
0.262;-1298.7
6(56A)
0.212;-3763.7
T(56A)
0.220;-4358.8
6(57A)
0.143;-5060.0
69(5A)
0.208;-4592.5
(6Q)(5A)
0.213;-2361.2
(579A)
0.185;-4358.8
(57KA)
0.231;-3423.7
79(5A)
0.229;-4358.8
(7Q)(5A)
0.235;-2127.5
(58TA)
0.190;-3891.3
88(5A)
0.205;-2828.7
(8J)(5A)
0.267;-2127.5
9(59A)
0.182;-2361.2
K(59A)
0.216;-2956.2
9(5QA)
0.231;-3190.0
J(5TA)
0.235;-3190.0
TJ(5A)
0.237;-3190.0
(5JQA)
0.215;-2722.5
J(5KA)
0.204;-2488.7
(QK)(5A)
0.254;-725.0
55(7A)
0.206;-3763.7
559A
0.176;-4826.2
5A(5Q)
0.178;-2595.0
(57)(6A)
0.224;-3530.0
5(6TA)
0.241;-4358.8
5Q(6A)
0.208;-3891.3
(56)(8A)
0.229;-3296.2
TA(56)
0.229;-4358.8
A(56K)
0.175;-3657.5
6A(58)
0.176;-4826.2
6A(5T)
0.167;-4358.8
6A(5Q)
0.243;-3891.3
57(7A)
0.223;-3296.2
(5T)(7A)
0.211;-2595.0
5(7KA)
0.207;-3423.7
A(579)
0.199;-4358.8
(57)(QA)
0.218;-2127.5
7A(58)
0.166;-4592.5
7A(5T)
0.201;-4125.0
7A(5Q)
0.232;-3657.5
58(8A)
0.217;-2828.7
(5J)(8A)
0.204;-2127.5
8A(58)
0.180;-2828.7
A(58J)
0.233;-3657.5
588A
0.170;-4358.8
58TA
0.192;-5421.3
58QA
0.191;-4953.7
(5T)(9A)
0.292;-2127.5
5(9KA)
0.281;-2956.2
A(59J)
0.222;-3423.7
599A
0.147;-3891.3
59JA
0.190;-4953.7
59KA
0.197;-4486.2
5Q(TA)
0.235;-2956.2
(5T)(QA)
0.256;-1426.2
TA(5J)
0.211;-3190.0
TA(5K)
0.162;-2722.5
5(JKA)
0.175;-2488.7
A(5JK)
0.187;-2488.7
JA(5K)
0.287;-2488.7
QA(5Q)
0.286;-958.8
5QKA
0.202;-3785.0
67(6A)
0.198;-3296.2
(6T)(6A)
0.248;-1065.0
6(6KA)
0.250;-1893.7
(67TA)
0.176;-3891.3
77(6A)
0.186;-3062.5
(7T)(6A)
0.223;-2361.2
7(6KA)
0.202;-3190.0
(68JA)
0.209;-3423.7
(89)(6A)
0.227;-2361.2
8(6QA)
0.207;-3190.0
T(69A)
0.217;-3423.7
9(6TA)
0.211;-3423.7
9Q(6A)
0.246;-2956.2
Q(6TA)
0.231;-2722.5
(TQ)(6A)
0.227;-1192.5
(6JKA)
0.225;-2255.0
JK(6A)
0.267;-2255.0
K(6KA)
0.284;-257.5
668A
0.214;-4592.5
6A(6J)
0.211;-2361.2
(67)(7A)
0.190;-1532.5
6(7TA)
0.221;-3891.3
6Q(7A)
0.224;-3423.7
(67)(9A)
0.164;-2595.0
JA(67)
0.190;-3657.5
67(8A)
0.181;-4358.8
67(TA)
0.218;-3891.3
67(QA)
0.202;-3423.7
(68)(8A)
0.260;-1065.0
6(8JA)
0.223;-3423.7
6K(8A)
0.242;-2956.2
(68)(JA)
0.220;-1893.7
KA(68)
0.233;-2956.2
6A(8T)
0.201;-3657.5
6A(8Q)
0.266;-3190.0
6(9TA)
0.197;-3423.7
6Q(9A)
0.210;-2956.2
(69)(JA)
0.212;-1660.0
KA(69)
0.262;-2722.5
6A(9J)
0.215;-3190.0
6A(9K)
0.195;-2722.5
(6Q)(TA)
0.247;-1192.5
JA(6T)
0.261;-2956.2
6T(JA)
0.156;-2956.2
6T(KA)
0.226;-2488.7
6Q(JA)
0.198;-2488.7
(6J)(KA)
0.261;-725.0
6J(KA)
0.241;-2255.0
6K(QA)
0.239;-2021.2
6A(QK)
0.198;-2021.2
(78)(7A)
0.293;-1065.0
7(7JA)
0.231;-1893.7
7K(7A)
0.272;-1426.2
(78QA)
0.261;-2956.2
8(7TA)
0.198;-3423.7
8Q(7A)
0.244;-2956.2
J(79A)
0.171;-2956.2
9T(7A)
0.182;-3190.0
(9K)(7A)
0.315;-958.8
K(7TA)
0.215;-2255.0
T(7KA)
0.249;-2255.0
JJ(7A)
0.265;-958.8
(7QKA)
0.253;-1787.5
777A
0.257;-2828.8
7A(7T)
0.222;-2127.5
77(KA)
0.217;-1426.2
7(8TA)
0.207;-3423.7
7Q(8A)
0.250;-2956.2
(78)(TA)
0.216;-1893.7
QA(78)
0.216;-2956.2
789A
0.165;-5187.5
78JA
0.201;-4720.0
78KA
0.244;-4252.5
7J(9A)
0.233;-2956.2
(79)(TA)
0.200;-1660.0
QA(79)
0.269;-2722.5
79TA
0.168;-4720.0
79QA
0.189;-4252.5
(7J)(TA)
0.277;-1192.5
TA(7T)
0.233;-1426.2
A(7TK)
0.249;-2255.0
TA(7Q)
0.169;-2488.7
7J(JA)
0.268;-958.8
(7J)(QA)
0.294;-725.0
JA(7Q)
0.191;-2255.0
7Q(QA)
0.309;-491.2
7QQA
0.204;-2021.2
7KKA
0.233;-1553.8
8(8JA)
0.216;-1426.2
8K(8A)
0.234;-958.8
(89KA)
0.177;-2255.0
9J(8A)
0.214;-2722.5
(8TJA)
0.234;-2488.7
(TJ)(8A)
0.213;-958.8
J(8JA)
0.288;-725.0
JQ(8A)
0.280;-2021.2
Q(8KA)
0.198;-1553.8
889A
0.158;-3423.7
8A(8Q)
0.257;-1192.5
(8T)(9A)
0.254;-1426.2
8(9KA)
0.235;-2255.0
A(89J)
0.194;-2722.5
899A
0.262;-3190.0
89JA
0.236;-4252.5
89KA
0.253;-3785.0
8Q(TA)
0.180;-2255.0
(8T)(QA)
0.295;-725.0
TA(8J)
0.249;-2488.7
TA(8K)
0.285;-2021.2
8(JKA)
0.222;-1787.5
A(8JK)
0.243;-1787.5
JA(8K)
0.254;-1787.5
QA(8Q)
0.258;-257.5
8QKA
0.217;-3083.7
9T(9A)
0.242;-1192.5
(9K)(9A)
0.274;1038.8
K(9TA)
0.235;-1787.5
T(9KA)
0.284;-1787.5
JJ(9A)
0.215;-491.2
(9QKA)
0.302;-1320.0
999A
0.223;-1426.2
9A(9Q)
0.304;-725.0
(9J)(TA)
0.212;-725.0
TA(9T)
0.285;-958.8
A(9TK)
0.246;-1787.5
TA(9Q)
0.261;-2021.2
9J(JA)
0.257;-491.2
(9J)(QA)
0.263;-257.5
JA(9Q)
0.265;-1787.5
9Q(QA)
0.260;-23.8
9QQA
0.280;-1553.8
9KKA
0.278;-1086.2
T(TKA)
0.260;-23.8
JJ(TA)
0.298;-257.5
(TQKA)
0.234;-1086.2
TTTA
0.291;-725.0
TA(TK)
0.308;-23.8
(TK)(JA)
0.260;210.0
KA(TJ)
0.218;-1320.0
TA(JK)
0.251;-1320.0
(TQ)(KA)
0.278;443.7
(TK)(KA)
0.325;2207.5
J(JKA)
0.304;443.7
(QK)(JA)
0.230;677.5
JJ(KA)
0.304;443.7
QA(JQ)
0.307;443.7
JQKA
0.191;-2382.5
QK(QA)
0.280;911.2
QK(KA)
0.274;1145.0
22(24)
0.201;-7142.5
22(28)
0.139;-6207.5
22(2Q)
0.205;-5272.5
24(23)
0.103;-8438.7
(23)(27)
0.166;-6207.5
2(23T)
0.150;-7036.2
2Q(23)
0.175;-6568.8
23(25)
0.186;-8205.0
2237
0.163;-9267.5
22(3T)
0.137;-7036.2
23(2K)
0.193;-6335.0
2(246)
0.135;-7737.5
28(24)
0.156;-7270.0
(24)(2J)
0.165;-5038.7
2244
0.138;-8205.0
22(47)
0.166;-7503.7
24(2T)
0.148;-6802.5
224Q
0.136;-7865.0
26(25)
0.139;-7503.7
(25)(29)
0.200;-5272.5
2(25Q)
0.209;-6101.2
22(56)
0.125;-7503.7
25(29)
0.164;-6802.5
225J
0.162;-7865.0
26(26)
0.178;-5740.0
(26)(29)
0.187;-5038.7
2(26Q)
0.178;-5867.5
22(67)
0.158;-7036.2
26(2T)
0.177;-6335.0
226Q
0.157;-7397.5
28(27)
0.194;-6568.8
(27)(2J)
0.197;-4337.5
2277
0.188;-6802.5
22(7T)
0.163;-6101.2
27(2K)
0.160;-5400.0
2(28T)
0.170;-5867.5
2Q(28)
0.191;-5400.0
28(2T)
0.141;-5867.5
228Q
0.116;-6930.0
2T(29)
0.171;-5633.7
(29)(2K)
0.250;-3402.5
229J
0.185;-6930.0
2T(2T)
0.186;-3870.0
(2T)(2K)
0.185;-3168.7
22TQ
0.181;-6462.5
2Q(2J)
0.213;-4698.7
2J(2K)
0.203;-4465.0
22QQ
0.167;-4465.0
3(234)
0.154;-8205.0
36(23)
0.140;-7737.5
(23)(39)
0.178;-5506.2
3(23Q)
0.148;-6335.0
5(234)
0.147;-9267.5
9(234)
0.161;-8332.5
K(234)
0.137;-7397.5
4(237)
0.106;-8800.0
49(23)
0.128;-8332.5
(23)(4Q)
0.125;-6101.2
(2357)
0.163;-8566.2
(235J)
0.115;-7631.3
(23)(56)
0.160;-7270.0
5(239)
0.157;-8098.7
5J(23)
0.123;-7631.3
(2367)
0.166;-8332.5
(236J)
0.144;-7397.5
(23)(67)
0.162;-6802.5
6(23T)
0.154;-7631.3
6Q(23)
0.128;-7163.7
9(237)
0.123;-7631.3
K(237)
0.162;-6696.2
7(23T)
0.190;-7397.5
7Q(23)
0.195;-6930.0
T(238)
0.147;-7163.7
8(239)
0.186;-7397.5
8J(23)
0.175;-6930.0
(239T)
0.146;-6930.0
99(23)
0.150;-5633.7
(23)(9Q)
0.196;-4932.5
(23TQ)
0.175;-6228.7
T(23Q)
0.163;-6228.7
Q(23J)
0.152;-5995.0
(23)(JK)
0.166;-4231.2
QK(23)
0.146;-5527.5
23(35)
0.136;-7971.2
33(28)
0.154;-7270.0
233T
0.167;-8332.5
23(3K)
0.161;-6101.2
(24)(36)
0.158;-7503.7
3(249)
0.132;-8332.5
3J(24)
0.162;-7865.0
(34)(25)
0.124;-7737.5
27(34)
0.114;-8800.0
2(34T)
0.151;-8098.7
(34)(2K)
0.170;-5867.5
34(26)
0.155;-9033.8
34(28)
0.148;-8566.2
34(2T)
0.129;-8098.7
34(2Q)
0.158;-7631.3
(25)(35)
0.191;-5973.8
3(258)
0.165;-8332.5
3T(25)
0.136;-7865.0
(25)(3K)
0.187;-5633.7
27(35)
0.160;-8566.2
2(35T)
0.147;-7865.0
(35)(2K)
0.230;-5633.7
35(27)
0.147;-8566.2
35(29)
0.150;-8098.7
35(2J)
0.150;-7631.3
35(2K)
0.205;-7163.7
37(26)
0.120;-8332.5
(26)(3T)
0.143;-6101.2
3(26K)
0.128;-6930.0
2(368)
0.142;-8098.7
(36)(2J)
0.137;-5867.5
2K(36)
0.179;-6930.0
23(68)
0.117;-8098.7
23(6T)
0.173;-7631.3
23(6Q)
0.168;-7163.7
3(278)
0.149;-7865.0
3T(27)
0.171;-7397.5
(27)(3K)
0.189;-5166.2
29(37)
0.164;-7631.3
2(37Q)
0.158;-6930.0
23(78)
0.162;-7865.0
23(7T)
0.169;-7397.5
23(7Q)
0.194;-6930.0
3(289)
0.153;-7397.5
3J(28)
0.168;-6930.0
(38)(29)
0.173;-5867.5
2J(38)
0.127;-6930.0
38(29)
0.128;-7397.5
38(2J)
0.196;-6930.0
38(2K)
0.156;-6462.5
3T(29)
0.181;-6930.0
(29)(3K)
0.242;-4698.8
2J(39)
0.167;-6696.2
39(2T)
0.150;-6930.0
39(2Q)
0.168;-6462.5
(2T)(3T)
0.227;-3636.2
3(2TK)
0.188;-5995.0
2(3TQ)
0.159;-6228.7
23(TJ)
0.160;-6462.5
23(TK)
0.187;-5995.0
(2J)(3K)
0.194;-4231.2
2K(3J)
0.169;-5761.2
23(JK)
0.130;-5761.2
(3Q)(2K)
0.190;-3997.5
(2K)(3K)
0.214;-2233.8
4(246)
0.168;-7270.0
48(24)
0.154;-6802.5
(24)(4J)
0.210;-4571.3
5(245)
0.147;-7270.0
9(245)
0.162;-7865.0
K(245)
0.159;-6930.0
5(248)
0.144;-8098.7
5T(24)
0.151;-7631.3
(24)(5K)
0.177;-5400.0
9(246)
0.160;-7631.3
K(246)
0.147;-6696.2
6(249)
0.164;-7631.3
6J(24)
0.145;-7163.7
(2478)
0.171;-7631.3
(247Q)
0.184;-6696.2
7(249)
0.152;-7397.5
7J(24)
0.194;-6930.0
(2489)
0.138;-7163.7
(248K)
0.138;-6228.7
8T(24)
0.166;-6930.0
(24)(8K)
0.160;-4698.8
Q(249)
0.142;-6228.7
(24)(9J)
0.190;-4932.5
T(24T)
0.208;-4932.5
T(24J)
0.166;-6228.7
TK(24)
0.171;-5761.2
(24)(JQ)
0.219;-4231.2
QQ(24)
0.188;-3997.5
24(45)
0.152;-7503.7
44(28)
0.187;-6802.5
244T
0.131;-7865.0
24(4K)
0.189;-5633.7
(25)(47)
0.160;-6802.5
4(25T)
0.155;-7631.3
4Q(25)
0.184;-7163.7
(45)(27)
0.151;-6802.5
29(45)
0.143;-7865.0
2(45Q)
0.169;-7163.7
24(56)
0.111;-8566.2
24(58)
0.151;-8098.7
24(5T)
0.176;-7631.3
24(5Q)
0.142;-7163.7
4(267)
0.133;-8098.7
49(26)
0.185;-7631.3
(26)(4Q)
0.182;-5400.0
27(46)
0.188;-8098.7
2(46T)
0.167;-7397.5
(46)(2K)
0.190;-5166.2
46(28)
0.125;-7865.0
46(2T)
0.134;-7397.5
46(2Q)
0.159;-6930.0
(27)(47)
0.224;-4805.0
4(27T)
0.167;-7163.7
4Q(27)
0.195;-6696.2
(47)(29)
0.202;-5867.5
2J(47)
0.143;-6930.0
47(28)
0.139;-7631.3
47(2T)
0.202;-7163.7
47(2Q)
0.184;-6696.2
(28)(48)
0.191;-4337.5
4(28J)
0.159;-6696.2
4K(28)
0.204;-6228.7
(48)(2J)
0.187;-5166.2
2K(48)
0.177;-6228.7
24(8T)
0.154;-6930.0
24(8Q)
0.184;-6462.5
4(29T)
0.155;-6696.2
4Q(29)
0.164;-6228.7
(49)(2J)
0.194;-4932.5
2K(49)
0.140;-5995.0
24(9J)
0.160;-6462.5
24(9K)
0.144;-5995.0
(2T)(4Q)
0.190;-4465.0
2J(4T)
0.186;-6228.7
4T(2J)
0.147;-6228.7
4T(2K)
0.154;-5761.2
4Q(2J)
0.173;-5761.2
(4J)(2K)
0.162;-3997.5
4J(2K)
0.175;-5527.5
4K(2Q)
0.213;-5293.7
24(QK)
0.173;-5293.7
(25)(56)
0.176;-5272.5
5(259)
0.188;-6101.2
5J(25)
0.137;-5633.7
(2567)
0.151;-7865.0
(256J)
0.176;-6930.0
(25)(67)
0.148;-6335.0
6(25T)
0.152;-7163.7
6Q(25)
0.134;-6696.2
9(257)
0.160;-7163.7
K(257)
0.185;-6228.7
7(25T)
0.144;-6930.0
7Q(25)
0.137;-6462.5
T(258)
0.177;-6696.2
8(259)
0.170;-6930.0
8J(25)
0.133;-6462.5
(259T)
0.119;-6462.5
99(25)
0.201;-5166.2
(25)(9Q)
0.198;-4465.0
(25TQ)
0.163;-5761.2
T(25Q)
0.184;-5761.2
Q(25J)
0.186;-5527.5
(25)(JK)
0.194;-3763.7
QK(25)
0.170;-5060.0
25(57)
0.168;-6568.8
55(2T)
0.165;-5867.5
255Q
0.136;-6930.0
57(26)
0.122;-7865.0
(26)(5T)
0.176;-5633.7
5(26K)
0.176;-6462.5
2(568)
0.148;-7631.3
(56)(2J)
0.227;-5400.0
2K(56)
0.155;-6462.5
25(68)
0.113;-7631.3
25(6T)
0.116;-7163.7
25(6Q)
0.157;-6696.2
5(278)
0.164;-7397.5
5T(27)
0.138;-6930.0
(27)(5K)
0.158;-4698.8
29(57)
0.137;-7163.7
2(57Q)
0.163;-6462.5
25(78)
0.139;-7397.5
25(7T)
0.190;-6930.0
25(7Q)
0.170;-6462.5
5(289)
0.134;-6930.0
5J(28)
0.163;-6462.5
(58)(29)
0.152;-5400.0
2J(58)
0.157;-6462.5
58(29)
0.155;-6930.0
58(2J)
0.151;-6462.5
58(2K)
0.174;-5995.0
5T(29)
0.139;-6462.5
(29)(5K)
0.179;-4231.2
2J(59)
0.189;-6228.7
59(2T)
0.175;-6462.5
59(2Q)
0.184;-5995.0
(2T)(5T)
0.222;-3168.7
5(2TK)
0.179;-5527.5
2(5TQ)
0.177;-5761.2
25(TJ)
0.146;-5995.0
25(TK)
0.189;-5527.5
(2J)(5K)
0.201;-3763.7
2K(5J)
0.183;-5293.7
25(JK)
0.133;-5293.7
(5Q)(2K)
0.181;-3530.0
(2K)(5K)
0.266;-1766.2
6(268)
0.207;-5867.5
6T(26)
0.182;-5400.0
(26)(6K)
0.179;-3168.7
T(267)
0.156;-6696.2
7(268)
0.155;-7163.7
7T(26)
0.170;-6696.2
(26)(7K)
0.191;-4465.0
J(268)
0.201;-6228.7
89(26)
0.180;-6696.2
(26)(8Q)
0.195;-4465.0
(269J)
0.156;-5995.0
(26)(9T)
0.168;-4698.8
9(26K)
0.171;-5527.5
(26TK)
0.210;-5293.7
TQ(26)
0.215;-5527.5
K(26J)
0.193;-5060.0
Q(26Q)
0.235;-3530.0
KK(26)
0.232;-3062.5
66(29)
0.191;-5633.7
266J
0.133;-6696.2
67(27)
0.148;-5867.5
(27)(6T)
0.172;-5166.2
6(27K)
0.178;-5995.0
2(679)
0.143;-6930.0
(67)(2Q)
0.165;-4698.8
27(68)
0.140;-7163.7
27(6T)
0.174;-6696.2
27(6Q)
0.147;-6228.7
68(28)
0.191;-5400.0
(28)(6J)
0.209;-4698.8
28(68)
0.172;-5400.0
2(68J)
0.187;-6228.7
2688
0.158;-6930.0
268T
0.159;-7992.5
268Q
0.124;-7525.0
(29)(6T)
0.184;-4698.8
6(29K)
0.226;-5527.5
2(69J)
0.166;-5995.0
2699
0.166;-6462.5
269J
0.163;-7525.0
269K
0.190;-7057.5
6Q(2T)
0.128;-5527.5
(6T)(2Q)
0.240;-3997.5
2T(6J)
0.189;-5761.2
2T(6K)
0.157;-5293.7
6(2JK)
0.140;-5060.0
2(6JK)
0.184;-5060.0
2J(6K)
0.226;-5060.0
2Q(6Q)
0.173;-3530.0
26QK
0.146;-6356.2
78(27)
0.211;-5400.0
(27)(7J)
0.217;-3168.7
8(278)
0.153;-5166.2
Q(278)
0.149;-5761.2
(27)(8T)
0.203;-4698.8
8(27K)
0.184;-5527.5
(279Q)
0.185;-5527.5
9(27J)
0.172;-5761.2
9K(27)
0.211;-5293.7
TT(27)
0.183;-4231.2
(27)(TK)
0.238;-3530.0
J(27Q)
0.186;-5060.0
K(27Q)
0.243;-4592.5
77(28)
0.159;-5400.0
277T
0.183;-6462.5
27(7K)
0.234;-4231.2
(28)(7T)
0.182;-4698.8
7(28K)
0.148;-5527.5
2(78T)
0.138;-6228.7
(78)(2K)
0.225;-3997.5
78(2T)
0.179;-6228.7
78(2Q)
0.162;-5761.2
(29)(79)
0.180;-3168.7
7(29Q)
0.198;-5527.5
2(79T)
0.186;-5995.0
(79)(2K)
0.199;-3763.7
79(2J)
0.149;-5761.2
79(2K)
0.178;-5293.7
7J(2T)
0.179;-5527.5
(7T)(2J)
0.164;-3997.5
2K(7T)
0.162;-5060.0
27(TQ)
0.190;-5293.7
7(2JQ)
0.226;-5060.0
2(7JQ)
0.218;-5060.0
27(JQ)
0.160;-5060.0
7(2QK)
0.159;-4592.5
7Q(2K)
0.245;-4592.5
88(28)
0.175;-3402.5
(28)(8J)
0.252;-2701.2
9(289)
0.249;-4465.0
K(289)
0.184;-5060.0
9(28Q)
0.175;-5293.7
J(28T)
0.135;-5293.7
TJ(28)
0.213;-5293.7
(28JQ)
0.180;-4826.2
J(28K)
0.231;-4592.5
(28)(QK)
0.228;-2828.8
88(2T)
0.192;-4465.0
288Q
0.181;-5527.5
8T(29)
0.167;-5761.2
(29)(8K)
0.172;-3530.0
2J(89)
0.225;-5527.5
89(2T)
0.143;-5761.2
89(2Q)
0.218;-5293.7
(2T)(8T)
0.230;-2467.5
8(2TK)
0.162;-4826.2
2(8TQ)
0.192;-5060.0
28(TJ)
0.134;-5293.7
28(TK)
0.168;-4826.2
(2J)(8K)
0.197;-3062.5
2K(8J)
0.201;-4592.5
28(JK)
0.199;-4592.5
(8Q)(2K)
0.266;-2828.8
(2K)(8K)
0.204;-1065.0
9(29J)
0.193;-3763.7
9K(29)
0.195;-3296.2
TT(29)
0.192;-3763.7
(29)(TK)
0.199;-3062.5
J(29Q)
0.167;-4592.5
K(29Q)
0.219;-4125.0
99(2T)
0.168;-3997.5
299Q
0.166;-5060.0
9J(2T)
0.207;-5060.0
(9T)(2J)
0.169;-3530.0
2K(9T)
0.139;-4592.5
29(TQ)
0.182;-4826.2
9(2JQ)
0.192;-4592.5
2(9JQ)
0.147;-4592.5
29(JQ)
0.227;-4592.5
9(2QK)
0.146;-4125.0
9Q(2K)
0.231;-4125.0
TT(2T)
0.250;-2000.0
(2T)(TK)
0.265;-1298.7
J(2TQ)
0.212;-4358.8
K(2TQ)
0.197;-3891.3
TT(2J)
0.200;-3296.2
2TTK
0.183;-4358.8
TK(2J)
0.195;-4125.0
2TJJ
0.143;-4592.5
2TJK
0.227;-5655.0
2(TQK)
0.202;-3891.3
TK(2K)
0.231;-2127.5
(2J)(JK)
0.281;-831.3
QK(2J)
0.188;-3657.5
2J(JK)
0.215;-2361.2
(JQ)(2K)
0.258;-2127.5
(2K)(JK)
0.290;-363.7
K(2QK)
0.243;-1660.0
2K(QK)
0.228;-1660.0
3335
0.150;-7737.5
3339
0.154;-6802.5
333K
0.222;-5867.5
36(34)
0.124;-7270.0
(34)(39)
0.187;-5038.7
3(34Q)
0.189;-5867.5
33(45)
0.143;-7503.7
34(38)
0.152;-6802.5
334T
0.140;-7865.0
33(4K)
0.192;-5633.7
(35)(37)
0.157;-5272.5
3(35T)
0.180;-6101.2
3Q(35)
0.184;-5633.7
35(37)
0.163;-6802.5
3359
0.115;-7865.0
33(5Q)
0.215;-5633.7
(36)(37)
0.181;-5038.7
3(36T)
0.163;-5867.5
3Q(36)
0.185;-5400.0
36(38)
0.215;-6335.0
336T
0.142;-7397.5
33(6K)
0.201;-5166.2
(37)(39)
0.209;-4337.5
3(37Q)
0.153;-5166.2
33(78)
0.210;-6101.2
37(3J)
0.198;-5400.0
337K
0.137;-6462.5
3T(38)
0.161;-5400.0
(38)(3K)
0.212;-3168.7
338T
0.124;-6930.0
33(8K)
0.151;-4698.7
(39)(3J)
0.198;-3402.5
3399
0.184;-5400.0
33(9Q)
0.223;-4698.7
(3T)(3J)
0.165;-3168.7
33TT
0.148;-4932.5
33(TK)
0.196;-4231.2
(3J)(3K)
0.260;-2467.5
33JK
0.156;-5527.5
33(QK)
0.180;-3763.7
45(34)
0.134;-7270.0
(34)(48)
0.218;-5038.7
4(34J)
0.178;-5867.5
4K(34)
0.220;-5400.0
(3459)
0.155;-7631.3
(345K)
0.185;-6696.2
57(34)
0.168;-8098.7
(34)(5T)
0.166;-5867.5
5(34K)
0.186;-6696.2
(3469)
0.146;-7397.5
(346K)
0.161;-6462.5
68(34)
0.158;-7631.3
(34)(6J)
0.164;-5400.0
7(347)
0.183;-6101.2
J(347)
0.156;-6696.2
78(34)
0.127;-7397.5
(34)(7J)
0.157;-5166.2
8(348)
0.175;-5633.7
Q(348)
0.148;-6228.7
(34)(8T)
0.175;-5166.2
8(34K)
0.152;-5995.0
(349Q)
0.144;-5995.0
9(34J)
0.132;-6228.7
9K(34)
0.149;-5761.2
TT(34)
0.181;-4698.7
(34)(TK)
0.176;-3997.5
J(34Q)
0.130;-5527.5
K(34Q)
0.187;-5060.0
44(35)
0.120;-7270.0
3447
0.155;-8332.5
34(4T)
0.176;-6101.2
44(3K)
0.200;-5400.0
4(357)
0.137;-8098.7
49(35)
0.143;-7631.3
(35)(4Q)
0.220;-5400.0
36(45)
0.149;-8332.5
3(459)
0.160;-7631.3
(45)(3Q)
0.138;-5400.0
35(46)
0.143;-8332.5
35(48)
0.195;-7865.0
35(4T)
0.131;-7397.5
35(4Q)
0.150;-6930.0
46(36)
0.146;-6568.8
(36)(49)
0.167;-5867.5
4(36Q)
0.154;-6696.2
3(467)
0.135;-7865.0
(46)(3T)
0.133;-5633.7
3Q(46)
0.217;-6696.2
3467
0.118;-9395.0
3469
0.127;-8927.5
346J
0.141;-8460.0
346K
0.155;-7992.5
49(37)
0.152;-7163.7
(37)(4Q)
0.210;-4932.5
38(47)
0.161;-7397.5
3(47J)
0.181;-6696.2
3477
0.157;-7631.3
3479
0.117;-8693.8
347J
0.161;-8226.2
347K
0.148;-7758.8
4T(38)
0.154;-6696.2
(38)(4K)
0.157;-4465.0
3T(48)
0.148;-6696.2
3(48K)
0.188;-5995.0
38(4T)
0.153;-6696.2
38(4Q)
0.147;-6228.7
49(39)
0.210;-5166.2
(39)(4Q)
0.164;-4465.0
3T(49)
0.170;-6462.5
3(49K)
0.136;-5761.2
39(4J)
0.177;-6228.7
39(4K)
0.195;-5761.2
4(3TQ)
0.171;-5761.2
3(4TJ)
0.169;-5995.0
34TT
0.144;-6228.7
34TQ
0.167;-7291.2
(3J)(4Q)
0.161;-3997.5
3Q(4J)
0.183;-5527.5
34JQ
0.140;-7057.5
(3Q)(4K)
0.191;-3530.0
3Q(4K)
0.173;-5060.0
5(356)
0.217;-6568.8
58(35)
0.161;-6101.2
(35)(5J)
0.228;-3870.0
6(356)
0.163;-6335.0
T(356)
0.145;-6930.0
6(357)
0.189;-7631.3
69(35)
0.154;-7163.7
(35)(6Q)
0.156;-4932.5
(3579)
0.139;-6930.0
(357K)
0.167;-5995.0
79(35)
0.166;-6930.0
(35)(7Q)
0.166;-4698.8
(358T)
0.118;-6462.5
88(35)
0.185;-5400.0
(35)(8J)
0.224;-4698.8
9(359)
0.162;-4932.5
K(359)
0.191;-5527.5
9(35Q)
0.168;-5761.2
J(35T)
0.155;-5761.2
TJ(35)
0.161;-5761.2
(35JQ)
0.215;-5293.7
J(35K)
0.144;-5060.0
(35)(QK)
0.218;-3296.2
55(37)
0.133;-6335.0
3559
0.147;-7397.5
35(5Q)
0.182;-5166.2
(36)(57)
0.171;-6101.2
5(36T)
0.184;-6930.0
5Q(36)
0.141;-6462.5
(56)(38)
0.169;-5867.5
3T(56)
0.170;-6930.0
3(56K)
0.148;-6228.7
36(58)
0.156;-7397.5
36(5T)
0.122;-6930.0
36(5Q)
0.150;-6462.5
57(37)
0.211;-5867.5
(37)(5T)
0.178;-5166.2
5(37K)
0.148;-5995.0
3(579)
0.211;-6930.0
(57)(3Q)
0.206;-4698.8
37(58)
0.131;-7163.7
37(5T)
0.217;-6696.2
37(5Q)
0.172;-6228.7
58(38)
0.170;-5400.0
(38)(5J)
0.188;-4698.8
38(58)
0.163;-5400.0
3(58J)
0.183;-6228.7
3588
0.160;-6930.0
358T
0.138;-7992.5
358Q
0.119;-7525.0
(39)(5T)
0.150;-4698.8
5(39K)
0.140;-5527.5
3(59J)
0.165;-5995.0
3599
0.163;-6462.5
359J
0.166;-7525.0
359K
0.154;-7057.5
5Q(3T)
0.144;-5527.5
(5T)(3Q)
0.156;-3997.5
3T(5J)
0.147;-5761.2
3T(5K)
0.145;-5293.7
5(3JK)
0.161;-5060.0
3(5JK)
0.166;-5060.0
3J(5K)
0.148;-5060.0
3Q(5Q)
0.179;-3530.0
35QK
0.159;-6356.2
67(36)
0.137;-5867.5
(36)(6T)
0.264;-3636.2
6(36K)
0.210;-4465.0
(367T)
0.206;-6462.5
77(36)
0.181;-5633.7
(36)(7T)
0.149;-4932.5
7(36K)
0.172;-5761.2
(368J)
0.204;-5995.0
(36)(89)
0.191;-4932.5
8(36Q)
0.157;-5761.2
T(369)
0.137;-5995.0
9(36T)
0.147;-5995.0
9Q(36)
0.194;-5527.5
Q(36T)
0.139;-5293.7
(36)(TQ)
0.229;-3763.7
(36JK)
0.234;-4826.2
JK(36)
0.185;-4826.2
K(36K)
0.177;-2828.7
3668
0.162;-7163.7
36(6J)
0.168;-4932.5
(37)(67)
0.208;-4103.8
6(37T)
0.145;-6462.5
6Q(37)
0.131;-5995.0
(67)(39)
0.144;-5166.2
3J(67)
0.169;-6228.7
67(38)
0.148;-6930.0
67(3T)
0.166;-6462.5
67(3Q)
0.159;-5995.0
(38)(68)
0.202;-3636.2
6(38J)
0.170;-5995.0
6K(38)
0.164;-5527.5
(68)(3J)
0.224;-4465.0
3K(68)
0.199;-5527.5
36(8T)
0.132;-6228.7
36(8Q)
0.166;-5761.2
6(39T)
0.141;-5995.0
6Q(39)
0.144;-5527.5
(69)(3J)
0.244;-4231.2
3K(69)
0.146;-5293.7
36(9J)
0.154;-5761.2
36(9K)
0.189;-5293.7
(3T)(6Q)
0.234;-3763.7
3J(6T)
0.144;-5527.5
6T(3J)
0.199;-5527.5
6T(3K)
0.160;-5060.0
6Q(3J)
0.219;-5060.0
(6J)(3K)
0.207;-3296.2
6J(3K)
0.195;-4826.2
6K(3Q)
0.187;-4592.5
36(QK)
0.173;-4592.5
(37)(78)
0.201;-3636.2
7(37J)
0.181;-4465.0
7K(37)
0.190;-3997.5
(378Q)
0.199;-5527.5
8(37T)
0.213;-5995.0
8Q(37)
0.193;-5527.5
J(379)
0.142;-5527.5
9T(37)
0.189;-5761.2
(37)(9K)
0.199;-3530.0
K(37T)
0.198;-4826.2
T(37K)
0.232;-4826.2
JJ(37)
0.196;-3530.0
(37QK)
0.190;-4358.8
3777
0.154;-5400.0
37(7T)
0.176;-4698.7
77(3K)
0.252;-3997.5
7(38T)
0.171;-5995.0
7Q(38)
0.189;-5527.5
(78)(3T)
0.208;-4465.0
3Q(78)
0.205;-5527.5
3789
0.149;-7758.8
378J
0.132;-7291.2
378K
0.121;-6823.7
7J(39)
0.209;-5527.5
(79)(3T)
0.177;-4231.2
3Q(79)
0.161;-5293.7
379T
0.148;-7291.2
379Q
0.158;-6823.7
(3T)(7J)
0.205;-3763.7
3T(7T)
0.170;-3997.5
3(7TK)
0.189;-4826.2
3T(7Q)
0.172;-5060.0
7J(3J)
0.169;-3530.0
(7J)(3Q)
0.228;-3296.2
3J(7Q)
0.209;-4826.2
7Q(3Q)
0.233;-3062.5
37QQ
0.188;-4592.5
37KK
0.210;-4125.0
8(38J)
0.193;-3997.5
8K(38)
0.263;-3530.0
(389K)
0.171;-4826.2
9J(38)
0.143;-5293.7
(38TJ)
0.214;-5060.0
(38)(TJ)
0.255;-3530.0
J(38J)
0.152;-3296.2
JQ(38)
0.180;-4592.5
Q(38K)
0.212;-4125.0
3889
0.164;-5995.0
38(8Q)
0.177;-3763.7
(39)(8T)
0.157;-3997.5
8(39K)
0.184;-4826.2
3(89J)
0.190;-5293.7
3899
0.178;-5761.2
389J
0.152;-6823.7
389K
0.138;-6356.2
8Q(3T)
0.190;-4826.2
(8T)(3Q)
0.219;-3296.2
3T(8J)
0.184;-5060.0
3T(8K)
0.174;-4592.5
8(3JK)
0.240;-4358.8
3(8JK)
0.191;-4358.8
3J(8K)
0.174;-4358.8
3Q(8Q)
0.207;-2828.7
38QK
0.212;-5655.0
9T(39)
0.230;-3763.7
(39)(9K)
0.258;-1532.5
K(39T)
0.190;-4358.8
T(39K)
0.170;-4358.8
JJ(39)
0.201;-3062.5
(39QK)
0.172;-3891.3
3999
0.247;-3997.5
39(9Q)
0.229;-3296.2
(3T)(9J)
0.189;-3296.2
3T(9T)
0.248;-3530.0
3(9TK)
0.185;-4358.8
3T(9Q)
0.188;-4592.5
9J(3J)
0.205;-3062.5
(9J)(3Q)
0.206;-2828.8
3J(9Q)
0.198;-4358.8
9Q(3Q)
0.199;-2595.0
39QQ
0.207;-4125.0
39KK
0.207;-3657.5
T(3TK)
0.201;-2595.0
JJ(3T)
0.181;-2828.7
(3TQK)
0.195;-3657.5
3TTT
0.206;-3296.2
3T(TK)
0.197;-2595.0
(3J)(TK)
0.232;-2361.2
3K(TJ)
0.254;-3891.3
3T(JK)
0.217;-3891.3
(TQ)(3K)
0.266;-2127.5
(3K)(TK)
0.244;-363.7
J(3JK)
0.246;-2127.5
(3J)(QK)
0.246;-1893.7
JJ(3K)
0.225;-2127.5
3Q(JQ)
0.222;-2127.5
3JQK
0.191;-4953.7
QK(3Q)
0.207;-1660.0
QK(3K)
0.210;-1426.2
44(46)
0.202;-5272.5
44(4T)
0.172;-4337.5
(45)(45)
0.186;-3742.5
4(458)
0.148;-6101.2
4T(45)
0.219;-5633.7
(45)(4K)
0.224;-3402.5
4457
0.116;-7865.0
44(5T)
0.137;-5633.7
45(4K)
0.143;-4932.5
4(468)
0.164;-5867.5
4T(46)
0.179;-5400.0
(46)(4K)
0.195;-3168.7
4468
0.129;-7397.5
44(6J)
0.226;-5166.2
(47)(47)
0.238;-2807.5
4(47T)
0.168;-5166.2
4Q(47)
0.202;-4698.7
47(49)
0.181;-5400.0
447J
0.157;-6462.5
48(48)
0.157;-3870.0
(48)(4J)
0.194;-3168.7
4488
0.194;-5400.0
44(8J)
0.204;-4698.7
(49)(49)
0.244;-1872.5
4(49Q)
0.172;-4231.2
44(9T)
0.146;-4698.7
49(4K)
0.250;-3997.5
4(4TQ)
0.210;-3997.5
44(TJ)
0.165;-4231.2
(4J)(4J)
0.275;-937.5
44JJ
0.256;-3997.5
4Q(4Q)
0.234;-2000.0
(4K)(4K)
0.272;-2.5
(45)(57)
0.194;-4571.3
5(45T)
0.200;-5400.0
5Q(45)
0.159;-4932.5
8(456)
0.113;-7163.7
Q(456)
0.142;-6228.7
(45)(68)
0.144;-5633.7
6(45J)
0.163;-6462.5
6K(45)
0.206;-5995.0
(457J)
0.197;-6228.7
(45)(78)
0.168;-5400.0
7(45J)
0.199;-6228.7
7K(45)
0.161;-5761.2
(458Q)
0.155;-5761.2
8(45T)
0.189;-6228.7
8Q(45)
0.187;-5761.2
J(459)
0.161;-5761.2
9T(45)
0.171;-5995.0
(45)(9K)
0.242;-3763.7
K(45T)
0.140;-5060.0
T(45K)
0.172;-5060.0
JJ(45)
0.169;-3763.7
(45QK)
0.194;-4592.5
4555
0.137;-6568.8
45(58)
0.201;-5867.5
55(4J)
0.176;-5166.2
455K
0.180;-6228.7
58(46)
0.147;-7163.7
(46)(5J)
0.161;-4932.5
46(56)
0.139;-6101.2
4(569)
0.157;-6930.0
(56)(4Q)
0.219;-4698.8
46(57)
0.185;-7397.5
46(59)
0.153;-6930.0
46(5J)
0.202;-6462.5
46(5K)
0.189;-5995.0
5(479)
0.198;-6696.2
5J(47)
0.149;-6228.7
(57)(48)
0.192;-5400.0
4T(57)
0.157;-6462.5
4(57K)
0.166;-5761.2
47(59)
0.136;-6696.2
47(5J)
0.153;-6228.7
47(5K)
0.211;-5761.2
5(48T)
0.148;-6228.7
5Q(48)
0.169;-5761.2
(58)(4T)
0.232;-4698.8
4Q(58)
0.189;-5761.2
4589
0.146;-7992.5
458J
0.136;-7525.0
458K
0.123;-7057.5
5J(49)
0.139;-5761.2
(59)(4T)
0.188;-4465.0
4Q(59)
0.174;-5527.5
459T
0.127;-7525.0
459Q
0.157;-7057.5
(4T)(5J)
0.233;-3997.5
4T(5T)
0.198;-4231.2
4(5TK)
0.162;-5060.0
4T(5Q)
0.167;-5293.7
5J(4J)
0.252;-3763.7
(5J)(4Q)
0.180;-3530.0
4J(5Q)
0.153;-5060.0
5Q(4Q)
0.219;-3296.2
45QQ
0.200;-4826.2
45KK
0.239;-4358.8
6(469)
0.190;-5166.2
6J(46)
0.204;-4698.7
(4678)
0.168;-6696.2
(467Q)
0.163;-5761.2
7(469)
0.144;-6462.5
7J(46)
0.148;-5995.0
(4689)
0.172;-6228.7
(468K)
0.210;-5293.7
8T(46)
0.150;-5995.0
(46)(8K)
0.173;-3763.7
Q(469)
0.169;-5293.7
(46)(9J)
0.194;-3997.5
T(46T)
0.233;-3997.5
T(46J)
0.171;-5293.7
TK(46)
0.153;-4826.2
(46)(JQ)
0.214;-3296.2
QQ(46)
0.210;-3062.5
46(67)
0.157;-5633.7
66(4T)
0.198;-4932.5
466Q
0.142;-5995.0
68(47)
0.157;-6696.2
(47)(6J)
0.218;-4465.0
47(67)
0.162;-5400.0
4(67T)
0.154;-6228.7
(67)(4K)
0.174;-3997.5
67(49)
0.125;-6462.5
67(4J)
0.170;-5995.0
67(4K)
0.211;-5527.5
69(48)
0.169;-6228.7
(48)(6Q)
0.166;-3997.5
49(68)
0.156;-6228.7
4(68Q)
0.227;-5527.5
46(89)
0.133;-6228.7
46(8J)
0.219;-5761.2
46(8K)
0.192;-5293.7
(49)(6J)
0.221;-3997.5
49(69)
0.172;-4465.0
4(69Q)
0.179;-5293.7
46(9T)
0.150;-5761.2
46(9Q)
0.147;-5293.7
6(4TJ)
0.194;-5293.7
6K(4T)
0.186;-4826.2
(6T)(4K)
0.216;-3296.2
6T(4Q)
0.206;-5060.0
(4J)(6J)
0.188;-2000.0
4J(6J)
0.188;-3530.0
6J(4Q)
0.202;-4826.2
(4Q)(6Q)
0.285;-1532.5
4K(6Q)
0.185;-4358.8
4K(6K)
0.234;-2595.0
79(47)
0.188;-4698.7
(47)(7Q)
0.222;-2467.5
(478T)
0.201;-5761.2
88(47)
0.191;-4698.7
(47)(8J)
0.181;-3997.5
9(479)
0.237;-4231.2
K(479)
0.210;-4826.2
9(47Q)
0.191;-5060.0
J(47T)
0.170;-5060.0
TJ(47)
0.171;-5060.0
(47JQ)
0.195;-4592.5
J(47K)
0.149;-4358.8
(47)(QK)
0.202;-2595.0
77(49)
0.161;-4698.7
477J
0.195;-5761.2
78(48)
0.144;-4698.7
(48)(7J)
0.194;-3997.5
48(78)
0.235;-4698.7
4(78J)
0.188;-5527.5
4788
0.166;-6228.7
478T
0.179;-7291.2
478Q
0.164;-6823.7
(49)(7T)
0.200;-3997.5
7(49K)
0.233;-4826.2
4(79J)
0.152;-5293.7
4799
0.178;-5761.2
479J
0.179;-6823.7
479K
0.174;-6356.2
7Q(4T)
0.168;-4826.2
(7T)(4Q)
0.163;-3296.2
4T(7J)
0.184;-5060.0
4T(7K)
0.154;-4592.5
7(4JK)
0.239;-4358.8
4(7JK)
0.171;-4358.8
4J(7K)
0.209;-4358.8
4Q(7Q)
0.245;-2828.7
47QK
0.192;-5655.0
89(48)
0.245;-4231.2
(48)(8Q)
0.265;-2000.0
(489J)
0.178;-5060.0
(48)(9T)
0.206;-3763.7
9(48K)
0.192;-4592.5
(48TK)
0.192;-4358.8
TQ(48)
0.172;-4592.5
K(48J)
0.224;-4125.0
Q(48Q)
0.214;-2595.0
KK(48)
0.259;-2127.5
88(4J)
0.214;-3763.7
488K
0.144;-4826.2
8J(49)
0.169;-5060.0
(89)(4T)
0.174;-3763.7
4Q(89)
0.244;-4826.2
489T
0.127;-6823.7
489Q
0.179;-6356.2
(4T)(8J)
0.261;-3296.2
4T(8T)
0.212;-3530.0
4(8TK)
0.168;-4358.8
4T(8Q)
0.172;-4592.5
8J(4J)
0.195;-3062.5
(8J)(4Q)
0.200;-2828.8
4J(8Q)
0.161;-4358.8
8Q(4Q)
0.232;-2595.0
48QQ
0.170;-4125.0
48KK
0.180;-3657.5
9(49Q)
0.207;-3062.5
J(49T)
0.212;-4592.5
TJ(49)
0.219;-4592.5
(49JQ)
0.192;-4125.0
J(49K)
0.202;-3891.3
(49)(QK)
0.199;-2127.5
99(4J)
0.178;-3296.2
499K
0.195;-4358.8
9Q(4T)
0.206;-4358.8
(9T)(4Q)
0.184;-2828.8
4T(9J)
0.177;-4592.5
4T(9K)
0.164;-4125.0
9(4JK)
0.217;-3891.3
4(9JK)
0.240;-3891.3
4J(9K)
0.158;-3891.3
4Q(9Q)
0.219;-2361.2
49QK
0.204;-5187.5
TJ(4T)
0.252;-2828.7
(4TJQ)
0.197;-3891.3
J(4TK)
0.172;-3657.5
(4T)(QK)
0.228;-1893.7
TT(4Q)
0.225;-2595.0
T(4JQ)
0.229;-3891.3
4(TJQ)
0.215;-3891.3
4T(JQ)
0.202;-3891.3
T(4QK)
0.185;-3423.7
TQ(4K)
0.224;-3423.7
JJ(4J)
0.286;-831.3
(4JQK)
0.239;-3190.0
4JJJ
0.245;-2361.2
JQ(4Q)
0.265;-1893.7
4JQQ
0.204;-3423.7
4JKK
0.189;-2956.2
QQ(4K)
0.274;-1426.2
4KKK
0.247;-958.8
55(59)
0.187;-3870.0
55(5K)
0.237;-2935.0
(56)(58)
0.224;-3870.0
5(56J)
0.140;-4698.7
5K(56)
0.159;-4231.2
56(59)
0.197;-5166.2
556J
0.146;-6228.7
57(57)
0.152;-3870.0
(57)(5T)
0.189;-3168.7
5(57K)
0.194;-3997.5
55(79)
0.186;-4932.5
57(5Q)
0.212;-4231.2
5(589)
0.169;-4698.7
5J(58)
0.195;-4231.2
58(59)
0.139;-4698.7
558J
0.149;-5761.2
59(59)
0.233;-2935.0
(59)(5Q)
0.267;-2233.8
559T
0.150;-5761.2
55(9K)
0.197;-3530.0
(5T)(5Q)
0.225;-2000.0
55TJ
0.157;-5293.7
5J(5J)
0.250;-2000.0
5J(5Q)
0.206;-3296.2
5(5QK)
0.243;-2828.7
5K(5K)
0.243;-1065.0
68(56)
0.170;-5166.2
(56)(6J)
0.229;-2935.0
7(567)
0.182;-5166.2
J(567)
0.189;-5761.2
78(56)
0.154;-6462.5
(56)(7J)
0.217;-4231.2
8(568)
0.243;-4698.7
Q(568)
0.200;-5293.7
(56)(8T)
0.154;-4231.2
8(56K)
0.182;-5060.0
(569Q)
0.168;-5060.0
9(56J)
0.144;-5293.7
9K(56)
0.194;-4826.2
TT(56)
0.195;-3763.7
(56)(TK)
0.214;-3062.5
J(56Q)
0.196;-4592.5
K(56Q)
0.181;-4125.0
66(57)
0.213;-5400.0
5669
0.131;-6462.5
56(6Q)
0.202;-4231.2
(57)(68)
0.166;-4932.5
6(57J)
0.180;-5761.2
6K(57)
0.196;-5293.7
(67)(5T)
0.190;-4465.0
5Q(67)
0.183;-5527.5
5678
0.121;-7992.5
567T
0.150;-7525.0
567Q
0.148;-7057.5
(58)(69)
0.183;-4465.0
6(58Q)
0.182;-5293.7
5(689)
0.189;-5995.0
(68)(5Q)
0.226;-3763.7
58(69)
0.175;-5995.0
58(6J)
0.175;-5527.5
58(6K)
0.197;-5060.0
6(59J)
0.175;-5293.7
6K(59)
0.185;-4826.2
(69)(5Q)
0.173;-3530.0
59(6T)
0.153;-5527.5
59(6Q)
0.203;-5060.0
6T(5T)
0.228;-3763.7
(5T)(6K)
0.244;-3062.5
5Q(6T)
0.196;-4826.2
56TJ
0.166;-6590.0
56TK
0.162;-6122.5
6K(5J)
0.173;-4358.8
56JJ
0.180;-4826.2
56JK
0.160;-5888.8
5(6QK)
0.182;-4125.0
6K(5K)
0.228;-2361.2
(57)(79)
0.170;-2935.0
7(57Q)
0.217;-3763.7
9(578)
0.148;-5761.2
K(578)
0.188;-4826.2
8(57J)
0.201;-5293.7
8K(57)
0.199;-4826.2
(579K)
0.188;-4592.5
9J(57)
0.170;-5060.0
(57TJ)
0.156;-4826.2
(57)(TJ)
0.239;-3296.2
J(57J)
0.203;-3062.5
JQ(57)
0.204;-4358.8
Q(57K)
0.146;-3891.3
5778
0.171;-6228.7
57(7J)
0.215;-3997.5
(58)(78)
0.199;-2935.0
7(58J)
0.151;-5293.7
7K(58)
0.182;-4826.2
(78)(5J)
0.209;-3763.7
5K(78)
0.232;-4826.2
57(8T)
0.147;-5527.5
57(8Q)
0.221;-5060.0
7(59T)
0.194;-5293.7
7Q(59)
0.174;-4826.2
(79)(5J)
0.255;-3530.0
5K(79)
0.204;-4592.5
57(9J)
0.206;-5060.0
57(9K)
0.185;-4592.5
(5T)(7Q)
0.235;-3062.5
5J(7T)
0.154;-4826.2
7T(5J)
0.188;-4826.2
7T(5K)
0.173;-4358.8
7Q(5J)
0.213;-4358.8
(7J)(5K)
0.258;-2595.0
7J(5K)
0.193;-4125.0
7K(5Q)
0.231;-3891.3
57(QK)
0.175;-3891.3
(58)(89)
0.213;-2467.5
8(58Q)
0.248;-3296.2
T(589)
0.209;-5060.0
9(58T)
0.158;-5060.0
9Q(58)
0.148;-4592.5
Q(58T)
0.192;-4358.8
(58)(TQ)
0.234;-2828.8
(58JK)
0.183;-3891.3
JK(58)
0.169;-3891.3
K(58K)
0.210;-1893.7
588T
0.212;-5293.7
58(8K)
0.204;-3062.5
(59)(8J)
0.220;-3296.2
59(89)
0.206;-3763.7
5(89Q)
0.202;-4592.5
58(9T)
0.133;-5060.0
58(9Q)
0.156;-4592.5
8(5TJ)
0.189;-4592.5
8K(5T)
0.210;-4125.0
(8T)(5K)
0.212;-2595.0
8T(5Q)
0.155;-4358.8
(5J)(8J)
0.241;-1298.7
5J(8J)
0.197;-2828.7
8J(5Q)
0.213;-4125.0
(5Q)(8Q)
0.269;-831.3
5K(8Q)
0.214;-3657.5
5K(8K)
0.291;-1893.7
9J(59)
0.237;-3062.5
(59TJ)
0.212;-4358.8
(59)(TJ)
0.173;-2828.8
J(59J)
0.222;-2595.0
JQ(59)
0.182;-3891.3
Q(59K)
0.237;-3423.7
599T
0.191;-4826.2
59(9K)
0.198;-2595.0
(5T)(9Q)
0.220;-2595.0
5J(9T)
0.149;-4358.8
9T(5J)
0.220;-4358.8
9T(5K)
0.185;-3891.3
9Q(5J)
0.179;-3891.3
(9J)(5K)
0.230;-2127.5
9J(5K)
0.199;-3657.5
9K(5Q)
0.228;-3423.7
59(QK)
0.250;-3423.7
(5T)(TJ)
0.239;-1065.0
J(5TJ)
0.203;-2361.2
JQ(5T)
0.193;-3657.5
Q(5TK)
0.224;-3190.0
5TTJ
0.198;-4125.0
TJ(5J)
0.193;-2361.2
(TJ)(5Q)
0.227;-2127.5
5J(TQ)
0.238;-3657.5
TQ(5Q)
0.191;-1893.7
5TQQ
0.182;-3423.7
5TKK
0.262;-2956.2
Q(5JQ)
0.209;-1660.0
KK(5J)
0.221;-1192.5
(5Q)(JQ)
0.328;-130.0
5K(JQ)
0.192;-2956.2
5K(JK)
0.262;-1192.5
5QQQ
0.305;-1426.2
KK(5K)
0.284;805.0
6669
0.201;-4698.8
666K
0.201;-3763.7
69(67)
0.169;-4465.0
(67)(6Q)
0.234;-2233.8
6678
0.176;-6228.7
66(7J)
0.235;-3997.5
(68)(68)
0.236;-1405.0
6(68J)
0.178;-3763.7
6K(68)
0.197;-3296.2
68(6J)
0.168;-3763.7
668K
0.168;-4826.2
6J(69)
0.220;-3530.0
69(6T)
0.171;-3763.7
669Q
0.177;-4826.2
6J(6T)
0.204;-3296.2
6T(6J)
0.205;-3296.2
66TK
0.208;-4358.8
6K(6J)
0.237;-2595.0
(6Q)(6Q)
0.268;465.0
66QK
0.184;-3891.3
7(679)
0.194;-4231.2
7J(67)
0.195;-3763.7
(6789)
0.127;-5527.5
(678K)
0.139;-4592.5
8T(67)
0.188;-5293.7
(67)(8K)
0.248;-3062.5
Q(679)
0.205;-4592.5
(67)(9J)
0.196;-3296.2
T(67T)
0.159;-3296.2
T(67J)
0.225;-4592.5
TK(67)
0.227;-4125.0
(67)(JQ)
0.243;-2595.0
QQ(67)
0.238;-2361.2
67(78)
0.219;-4465.0
77(6J)
0.187;-3763.7
677K
0.140;-4826.2
7T(68)
0.192;-5293.7
(68)(7K)
0.199;-3062.5
6T(78)
0.175;-5293.7
6(78K)
0.165;-4592.5
68(7T)
0.195;-5293.7
68(7Q)
0.159;-4826.2
79(69)
0.222;-3763.7
(69)(7Q)
0.213;-3062.5
6T(79)
0.181;-5060.0
6(79K)
0.211;-4358.8
69(7J)
0.184;-4826.2
69(7K)
0.200;-4358.8
7(6TQ)
0.169;-4358.8
6(7TJ)
0.209;-4592.5
67TT
0.173;-4826.2
67TQ
0.149;-5888.8
(6J)(7Q)
0.217;-2595.0
6Q(7J)
0.215;-4125.0
67JQ
0.184;-5655.0
(6Q)(7K)
0.194;-2127.5
6Q(7K)
0.216;-3657.5
8(689)
0.167;-3763.7
8J(68)
0.252;-3296.2
(689T)
0.246;-4826.2
99(68)
0.170;-3530.0
(68)(9Q)
0.185;-2828.8
(68TQ)
0.213;-4125.0
T(68Q)
0.164;-4125.0
Q(68J)
0.223;-3891.3
(68)(JK)
0.220;-2127.5
QK(68)
0.195;-3423.7
68(8T)
0.238;-3530.0
88(6K)
0.236;-2828.7
8(69J)
0.182;-4592.5
8K(69)
0.223;-4125.0
(89)(6Q)
0.209;-2828.8
69(8T)
0.242;-4826.2
69(8Q)
0.196;-4358.8
8T(6T)
0.182;-3062.5
(6T)(8K)
0.191;-2361.2
6Q(8T)
0.169;-4125.0
68TJ
0.150;-5888.8
68TK
0.157;-5421.3
8K(6J)
0.156;-3657.5
68JJ
0.212;-4125.0
68JK
0.184;-5187.5
6(8QK)
0.217;-3423.7
8K(6K)
0.229;-1660.0
(69)(9J)
0.195;-1298.7
T(69T)
0.200;-2828.7
T(69J)
0.179;-4125.0
TK(69)
0.198;-3657.5
(69)(JQ)
0.270;-2127.5
QQ(69)
0.232;-1893.7
69(9T)
0.180;-3062.5
99(6K)
0.207;-2361.2
9(6TQ)
0.180;-3891.3
6(9TJ)
0.190;-4125.0
69TT
0.225;-4358.8
69TQ
0.173;-5421.3
(6J)(9Q)
0.204;-2127.5
6Q(9J)
0.156;-3657.5
69JQ
0.189;-5187.5
(6Q)(9K)
0.226;-1660.0
6Q(9K)
0.206;-3190.0
T(6TJ)
0.200;-2361.2
TK(6T)
0.268;-1893.7
(6T)(JQ)
0.224;-1893.7
QQ(6T)
0.204;-1660.0
6T(TJ)
0.224;-2361.2
(6J)(TJ)
0.186;-597.5
6J(TJ)
0.212;-2127.5
TJ(6Q)
0.225;-3423.7
(6Q)(TQ)
0.268;-130.0
6K(TQ)
0.246;-2956.2
6K(TK)
0.203;-1192.5
JK(6J)
0.235;-1426.2
K(6JK)
0.206;-958.8
6JJK
0.224;-2956.2
6(JQK)
0.224;-2722.5
JK(6K)
0.265;-958.8
KK(6Q)
0.229;-725.0
6QKK
0.185;-2255.0
77(7T)
0.201;-2233.7
(78)(78)
0.279;-937.5
7(78J)
0.162;-3296.2
7K(78)
0.189;-2828.7
78(7J)
0.220;-3296.2
778K
0.184;-4358.8
7J(79)
0.212;-3062.5
79(7T)
0.224;-3296.2
779Q
0.157;-4358.8
7J(7T)
0.174;-2828.7
7T(7J)
0.212;-2828.7
77TK
0.231;-3891.3
7K(7J)
0.277;-2127.5
(7Q)(7Q)
0.325;932.5
77QK
0.163;-3423.7
8(78T)
0.195;-3296.2
8Q(78)
0.221;-2828.7
J(789)
0.184;-4358.8
9T(78)
0.205;-4592.5
(78)(9K)
0.180;-2361.2
K(78T)
0.157;-3657.5
T(78K)
0.192;-3657.5
JJ(78)
0.255;-2361.2
(78QK)
0.199;-3190.0
7888
0.249;-3763.7
78(8J)
0.270;-3062.5
(79)(89)
0.223;-1766.2
8(79Q)
0.215;-4125.0
7(89T)
0.192;-4592.5
(89)(7K)
0.183;-2361.2
89(7J)
0.220;-4358.8
89(7K)
0.163;-3891.3
8J(7T)
0.197;-4125.0
(8T)(7J)
0.234;-2595.0
7K(8T)
0.165;-3657.5
78(TQ)
0.223;-3891.3
8(7JQ)
0.190;-3657.5
7(8JQ)
0.200;-3657.5
78(JQ)
0.197;-3657.5
8(7QK)
0.199;-3190.0
8Q(7K)
0.243;-3190.0
99(79)
0.257;-1532.5
(79)(9Q)
0.289;-831.3
(79TQ)
0.194;-3657.5
T(79Q)
0.226;-3657.5
Q(79J)
0.149;-3423.7
(79)(JK)
0.276;-1660.0
QK(79)
0.199;-2956.2
79(9J)
0.219;-2595.0
(7T)(9T)
0.240;-1065.0
9(7TK)
0.197;-3423.7
7(9TQ)
0.217;-3657.5
79(TJ)
0.204;-3891.3
79(TK)
0.204;-3423.7
(7J)(9K)
0.224;-1660.0
7K(9J)
0.196;-3190.0
79(JK)
0.224;-3190.0
(9Q)(7K)
0.247;-1426.2
(7K)(9K)
0.297;337.5
T(7TQ)
0.218;-1893.7
Q(7TJ)
0.224;-3190.0
(7T)(JK)
0.219;-1426.2
QK(7T)
0.223;-2722.5
7T(TQ)
0.217;-1893.7
(7J)(TQ)
0.208;-1660.0
7Q(TJ)
0.195;-3190.0
7TJQ
0.174;-4720.0
(7Q)(TK)
0.297;-1192.5
7Q(TK)
0.213;-2722.5
J(7JQ)
0.200;-1426.2
K(7JQ)
0.192;-2488.7
JJ(7Q)
0.246;-1426.2
J(7QK)
0.230;-2488.7
JQ(7K)
0.173;-2488.7
QQ(7Q)
0.251;571.2
7Q(QK)
0.270;-725.0
8888
0.224;-2000.0
888Q
0.230;-2595.0
8(89J)
0.178;-2595.0
8K(89)
0.214;-2127.5
89(8Q)
0.191;-2361.2
8(8TJ)
0.251;-2361.2
8K(8T)
0.258;-1893.7
8T(8K)
0.227;-1893.7
8(8JK)
0.226;-1660.0
88(JK)
0.196;-1660.0
8Q(8K)
0.271;-1426.2
(89)(9T)
0.244;-1065.0
9(89K)
0.252;-1893.7
(89TK)
0.194;-3190.0
TQ(89)
0.178;-3423.7
K(89J)
0.194;-2956.2
Q(89Q)
0.211;-1426.2
KK(89)
0.295;-958.8
99(8Q)
0.230;-2127.5
9(8TJ)
0.192;-3657.5
9K(8T)
0.205;-3190.0
(9T)(8K)
0.249;-1660.0
9T(8Q)
0.163;-3423.7
(8J)(9J)
0.305;-363.7
8J(9J)
0.228;-1893.7
9J(8Q)
0.184;-3190.0
(8Q)(9Q)
0.231;103.8
8K(9Q)
0.181;-2722.5
8K(9K)
0.218;-958.8
TQ(8T)
0.291;-1660.0
K(8TJ)
0.244;-2722.5
Q(8TQ)
0.243;-1192.5
KK(8T)
0.295;-725.0
