AAAA
0.374;-2040.0
5AAA
0.274;-4605.0
9AAA
0.301;-3945.0
KAAA
0.257;-3285.0
4A(2A)
0.190;-6750.0
(2A)(7A)
0.199;-5175.0
A(2TA)
0.182;-5760.0
QA(2A)
0.205;-5430.0
2A(4A)
0.198;-6750.0
26AA
0.220;-7500.0
AA(29)
0.269;-5925.0
2A(QA)
0.269;-5430.0
A(34A)
0.164;-6585.0
6A(3A)
0.211;-6255.0
(3A)(9A)
0.199;-4680.0
A(3QA)
0.179;-5265.0
AA(34)
0.209;-6585.0
3A(7A)
0.216;-6090.0
39AA
0.181;-6840.0
AA(3Q)
0.244;-5265.0
(4A)(5A)
0.257;-5175.0
A(48A)
0.186;-5760.0
TA(4A)
0.237;-5430.0
(4A)(KA)
0.274;-3855.0
46AA
0.199;-7170.0
AA(49)
0.245;-5595.0
4A(QA)
0.255;-5100.0
A(56A)
0.181;-5925.0
8A(5A)
0.180;-5595.0
(5A)(JA)
0.244;-4020.0
55AA
0.258;-6090.0
AA(58)
0.198;-5595.0
5A(JA)
0.197;-5100.0
5KAA
0.244;-5850.0
8A(6A)
0.261;-5430.0
(6A)(JA)
0.223;-3855.0
66AA
0.264;-5760.0
AA(69)
0.201;-5265.0
6A(QA)
0.250;-4770.0
A(78A)
0.264;-5265.0
TA(7A)
0.198;-4935.0
(7A)(KA)
0.288;-3360.0
79AA
0.168;-6180.0
AA(7Q)
0.230;-4605.0
(8A)(9A)
0.261;-3855.0
A(8QA)
0.198;-4440.0
AA(89)
0.267;-4935.0
8A(QA)
0.253;-4440.0
A(9TA)
0.256;-4605.0
QA(9A)
0.286;-4275.0
9A(JA)
0.270;-4440.0
9KAA
0.282;-5190.0
QA(TA)
0.301;-4110.0
TA(QA)
0.242;-4110.0
A(JQA)
0.212;-3945.0
AA(JQ)
0.220;-3945.0
(QA)(KA)
0.318;-2535.0
KKAA
0.340;-3450.0
2(25A)
0.203;-8565.0
27(2A)
0.150;-8235.0
(2T)(2A)
0.173;-6660.0
2(2KA)
0.183;-7245.0
(236A)
0.120;-9315.0
(23TA)
0.207;-8655.0
33(2A)
0.174;-8730.0
(36)(2A)
0.204;-8235.0
3(29A)
0.178;-8820.0
3J(2A)
0.160;-8490.0
(245A)
0.131;-9315.0
(249A)
0.176;-8655.0
(24KA)
0.195;-7995.0
46(2A)
0.125;-9150.0
(49)(2A)
0.144;-7575.0
4(2QA)
0.203;-8160.0
6(25A)
0.155;-8985.0
T(25A)
0.198;-8325.0
5(26A)
0.151;-8985.0
58(2A)
0.193;-8655.0
(5J)(2A)
0.142;-7080.0
6(26A)
0.204;-7740.0
T(26A)
0.175;-8160.0
6(27A)
0.150;-8655.0
69(2A)
0.145;-8325.0
(6Q)(2A)
0.200;-6750.0
(279A)
0.172;-8160.0
(27KA)
0.169;-7500.0
79(2A)
0.147;-8160.0
(7Q)(2A)
0.193;-6585.0
(28TA)
0.134;-7830.0
88(2A)
0.228;-7080.0
(8J)(2A)
0.218;-6585.0
9(29A)
0.182;-6750.0
K(29A)
0.149;-7170.0
9(2QA)
0.140;-7335.0
J(2TA)
0.175;-7335.0
TJ(2A)
0.184;-7335.0
(2JQA)
0.186;-7005.0
J(2KA)
0.180;-6840.0
(QK)(2A)
0.185;-5595.0
22(4A)
0.116;-8730.0
226A
0.180;-9480.0
2A(29)
0.179;-7905.0
22(QA)
0.217;-7410.0
2(34A)
0.134;-9645.0
26(3A)
0.147;-9315.0
(29)(3A)
0.175;-7740.0
2(3QA)
0.160;-8325.0
A(234)
0.120;-9645.0
(23)(7A)
0.173;-8070.0
9A(23)
0.126;-8820.0
A(23Q)
0.171;-8325.0
2A(34)
0.152;-9645.0
2A(36)
0.132;-9315.0
2A(38)
0.148;-8985.0
2A(3T)
0.145;-8655.0
2A(3Q)
0.159;-8325.0
2(45A)
0.148;-9315.0
27(4A)
0.160;-8985.0
(2T)(4A)
0.157;-7410.0
2(4KA)
0.187;-7995.0
A(246)
0.183;-9150.0
(24)(9A)
0.177;-7575.0
JA(24)
0.143;-8325.0
24(5A)
0.189;-9315.0
24(7A)
0.144;-8985.0
24(9A)
0.162;-8655.0
24(JA)
0.176;-8325.0
24(KA)
0.151;-7995.0
26(5A)
0.165;-8985.0
(29)(5A)
0.161;-7410.0
2(5QA)
0.193;-7995.0
A(256)
0.200;-8985.0
(25)(9A)
0.169;-7410.0
JA(25)
0.138;-8160.0
25(6A)
0.190;-8985.0
25(8A)
0.127;-8655.0
25(TA)
0.169;-8325.0
25(QA)
0.173;-7995.0
(26)(6A)
0.186;-6660.0
2(69A)
0.175;-8325.0
2J(6A)
0.186;-7995.0
(26)(7A)
0.137;-7575.0
9A(26)
0.147;-8325.0
A(26Q)
0.142;-7830.0
2A(67)
0.156;-8655.0
2A(69)
0.187;-8325.0
2A(6J)
0.205;-7995.0
2A(6K)
0.217;-7665.0
(29)(7A)
0.157;-7080.0
2(7QA)
0.159;-7665.0
A(278)
0.133;-8325.0
(27)(JA)
0.215;-6750.0
KA(27)
0.173;-7500.0
2A(79)
0.196;-8160.0
2A(7J)
0.171;-7830.0
2A(7K)
0.193;-7500.0
(2T)(8A)
0.178;-6750.0
2(8KA)
0.152;-7335.0
A(28T)
0.172;-7830.0
(28)(KA)
0.187;-6255.0
28(TA)
0.167;-7830.0
28(QA)
0.217;-7500.0
(29)(9A)
0.243;-5670.0
2(9QA)
0.155;-7335.0
A(29T)
0.166;-7665.0
(29)(KA)
0.234;-6090.0
29(JA)
0.237;-7500.0
29(KA)
0.161;-7170.0
2J(TA)
0.144;-7335.0
(2T)(JA)
0.200;-6255.0
KA(2T)
0.189;-7005.0
2A(TQ)
0.195;-7170.0
2(JQA)
0.173;-7005.0
A(2JQ)
0.188;-7005.0
2A(JQ)
0.221;-7005.0
2(QKA)
0.191;-6675.0
2Q(KA)
0.213;-6675.0
33(3A)
0.199;-7485.0
(36)(3A)
0.172;-6990.0
3(39A)
0.179;-7575.0
3J(3A)
0.165;-7245.0
(345A)
0.159;-9150.0
(349A)
0.201;-8490.0
(34KA)
0.172;-7830.0
46(3A)
0.153;-8985.0
(49)(3A)
0.175;-7410.0
4(3QA)
0.172;-7995.0
6(35A)
0.156;-8820.0
T(35A)
0.170;-8160.0
5(36A)
0.128;-8820.0
58(3A)
0.201;-8490.0
(5J)(3A)
0.179;-6915.0
6(36A)
0.215;-7575.0
T(36A)
0.159;-7995.0
6(37A)
0.134;-8490.0
69(3A)
0.126;-8160.0
(6Q)(3A)
0.185;-6585.0
(379A)
0.153;-7995.0
(37KA)
0.156;-7335.0
79(3A)
0.177;-7995.0
(7Q)(3A)
0.209;-6420.0
(38TA)
0.172;-7665.0
88(3A)
0.184;-6915.0
(8J)(3A)
0.231;-6420.0
9(39A)
0.220;-6585.0
K(39A)
0.188;-7005.0
9(3QA)
0.212;-7170.0
J(3TA)
0.164;-7170.0
TJ(3A)
0.217;-7170.0
(3JQA)
0.187;-6840.0
J(3KA)
0.162;-6675.0
(QK)(3A)
0.237;-5430.0
33(5A)
0.152;-8235.0
337A
0.191;-8985.0
3A(3T)
0.190;-7410.0
33(KA)
0.190;-6915.0
3(46A)
0.120;-8985.0
38(4A)
0.121;-8655.0
(3J)(4A)
0.234;-7080.0
4A(34)
0.170;-8235.0
A(347)
0.203;-8820.0
(34)(TA)
0.184;-7245.0
QA(34)
0.209;-7995.0
345A
0.116;-10230.0
347A
0.132;-9900.0
349A
0.161;-9570.0
34JA
0.149;-9240.0
34KA
0.150;-8910.0
37(5A)
0.166;-8655.0
(3T)(5A)
0.186;-7080.0
3(5KA)
0.155;-7665.0
A(357)
0.162;-8655.0
(35)(TA)
0.252;-7080.0
QA(35)
0.170;-7830.0
356A
0.121;-9900.0
358A
0.161;-9570.0
35TA
0.121;-9240.0
35QA
0.178;-8910.0
(37)(6A)
0.223;-7410.0
3(6TA)
0.164;-7995.0
3Q(6A)
0.166;-7665.0
(36)(8A)
0.184;-7245.0
TA(36)
0.201;-7995.0
A(36K)
0.193;-7500.0
6A(38)
0.147;-8325.0
6A(3T)
0.182;-7995.0
6A(3Q)
0.177;-7665.0
37(7A)
0.209;-7245.0
(3T)(7A)
0.195;-6750.0
3(7KA)
0.161;-7335.0
A(379)
0.136;-7995.0
(37)(QA)
0.172;-6420.0
7A(38)
0.173;-8160.0
7A(3T)
0.217;-7830.0
7A(3Q)
0.198;-7500.0
38(8A)
0.223;-6915.0
(3J)(8A)
0.251;-6420.0
8A(38)
0.221;-6915.0
A(38J)
0.162;-7500.0
388A
0.131;-7995.0
38TA
0.172;-8745.0
38QA
0.133;-8415.0
(3T)(9A)
0.174;-6420.0
3(9KA)
0.172;-7005.0
A(39J)
0.216;-7335.0
399A
0.185;-7665.0
39JA
0.160;-8415.0
39KA
0.168;-8085.0
3Q(TA)
0.218;-7005.0
(3T)(QA)
0.233;-5925.0
TA(3J)
0.177;-7170.0
TA(3K)
0.178;-6840.0
3(JKA)
0.172;-6675.0
A(3JK)
0.206;-6675.0
JA(3K)
0.255;-6675.0
QA(3Q)
0.221;-5595.0
3QKA
0.184;-7590.0
45(4A)
0.153;-7905.0
(48)(4A)
0.209;-6330.0
4(4JA)
0.180;-6915.0
4K(4A)
0.197;-6585.0
(459A)
0.209;-8160.0
(45KA)
0.195;-7500.0
57(4A)
0.178;-8490.0
(5T)(4A)
0.180;-6915.0
5(4KA)
0.206;-7500.0
(469A)
0.148;-7995.0
(46KA)
0.155;-7335.0
68(4A)
0.202;-8160.0
(6J)(4A)
0.188;-6585.0
7(47A)
0.179;-7080.0
J(47A)
0.187;-7500.0
78(4A)
0.216;-7995.0
(7J)(4A)
0.216;-6420.0
8(48A)
0.197;-6750.0
Q(48A)
0.239;-7170.0
(8T)(4A)
0.225;-6420.0
8(4KA)
0.149;-7005.0
(49QA)
0.202;-7005.0
9(4JA)
0.157;-7170.0
9K(4A)
0.202;-6840.0
TT(4A)
0.169;-6090.0
(TK)(4A)
0.224;-5595.0
J(4QA)
0.192;-6675.0
K(4QA)
0.268;-6345.0
44(5A)
0.164;-7905.0
447A
0.149;-8655.0
4A(4T)
0.195;-7080.0
44(KA)
0.251;-6585.0
4(57A)
0.145;-8490.0
49(5A)
0.202;-8160.0
(4Q)(5A)
0.209;-6585.0
6A(45)
0.135;-8655.0
A(459)
0.171;-8160.0
(45)(QA)
0.207;-6585.0
5A(46)
0.144;-8655.0
5A(48)
0.155;-8325.0
5A(4T)
0.186;-7995.0
5A(4Q)
0.180;-7665.0
46(6A)
0.137;-7410.0
(49)(6A)
0.235;-6915.0
4(6QA)
0.206;-7500.0
A(467)
0.125;-8325.0
(46)(TA)
0.175;-6750.0
QA(46)
0.160;-7500.0
467A
0.191;-9405.0
469A
0.164;-9075.0
46JA
0.168;-8745.0
46KA
0.199;-8415.0
49(7A)
0.153;-7830.0
(4Q)(7A)
0.206;-6255.0
8A(47)
0.146;-7995.0
A(47J)
0.219;-7500.0
477A
0.153;-8160.0
479A
0.137;-8910.0
47JA
0.125;-8580.0
47KA
0.162;-8250.0
4T(8A)
0.171;-7500.0
(4K)(8A)
0.169;-5925.0
TA(48)
0.167;-7500.0
A(48K)
0.212;-7005.0
8A(4T)
0.192;-7500.0
8A(4Q)
0.236;-7170.0
49(9A)
0.184;-6420.0
(4Q)(9A)
0.239;-5925.0
TA(49)
0.174;-7335.0
A(49K)
0.198;-6840.0
9A(4J)
0.231;-7170.0
9A(4K)
0.191;-6840.0
4(TQA)
0.187;-6840.0
A(4TJ)
0.173;-7005.0
4TTA
0.199;-7170.0
4TQA
0.167;-7920.0
(4Q)(JA)
0.186;-5595.0
QA(4J)
0.153;-6675.0
4JQA
0.166;-7755.0
(4K)(QA)
0.276;-5265.0
QA(4K)
0.210;-6345.0
5(56A)
0.177;-7410.0
58(5A)
0.172;-7080.0
(5J)(5A)
0.260;-5505.0
6(56A)
0.179;-7245.0
T(56A)
0.213;-7665.0
6(57A)
0.177;-8160.0
69(5A)
0.212;-7830.0
(6Q)(5A)
0.175;-6255.0
(579A)
0.179;-7665.0
(57KA)
0.199;-7005.0
79(5A)
0.180;-7665.0
(7Q)(5A)
0.189;-6090.0
(58TA)
0.195;-7335.0
88(5A)
0.206;-6585.0
(8J)(5A)
0.229;-6090.0
9(59A)
0.165;-6255.0
K(59A)
0.213;-6675.0
9(5QA)
0.246;-6840.0
J(5TA)
0.156;-6840.0
TJ(5A)
0.188;-6840.0
(5JQA)
0.222;-6510.0
J(5KA)
0.187;-6345.0
(QK)(5A)
0.234;-5100.0
55(7A)
0.167;-7245.0
559A
0.178;-7995.0
5A(5Q)
0.201;-6420.0
(57)(6A)
0.215;-7080.0
5(6TA)
0.174;-7665.0
5Q(6A)
0.195;-7335.0
(56)(8A)
0.193;-6915.0
TA(56)
0.148;-7665.0
A(56K)
0.207;-7170.0
6A(58)
0.172;-7995.0
6A(5T)
0.162;-7665.0
6A(5Q)
0.175;-7335.0
57(7A)
0.206;-6915.0
(5T)(7A)
0.222;-6420.0
5(7KA)
0.175;-7005.0
A(579)
0.208;-7665.0
(57)(QA)
0.204;-6090.0
7A(58)
0.166;-7830.0
7A(5T)
0.236;-7500.0
7A(5Q)
0.182;-7170.0
58(8A)
0.233;-6585.0
(5J)(8A)
0.195;-6090.0
8A(58)
0.165;-6585.0
A(58J)
0.153;-7170.0
588A
0.197;-7665.0
58TA
0.195;-8415.0
58QA
0.164;-8085.0
(5T)(9A)
0.217;-6090.0
5(9KA)
0.230;-6675.0
A(59J)
0.215;-7005.0
599A
0.145;-7335.0
59JA
0.139;-8085.0
59KA
0.215;-7755.0
5Q(TA)
0.182;-6675.0
(5T)(QA)
0.208;-5595.0
TA(5J)
0.195;-6840.0
TA(5K)
0.212;-6510.0
5(JKA)
0.222;-6345.0
A(5JK)
0.196;-6345.0
JA(5K)
0.169;-6345.0
QA(5Q)
0.233;-5265.0
5QKA
0.221;-7260.0
67(6A)
0.190;-6915.0
(6T)(6A)
0.221;-5340.0
6(6KA)
0.243;-5925.0
(67TA)
0.218;-7335.0
77(6A)
0.188;-6750.0
(7T)(6A)
0.196;-6255.0
7(6KA)
0.170;-6840.0
(68JA)
0.216;-7005.0
(89)(6A)
0.225;-6255.0
8(6QA)
0.212;-6840.0
T(69A)
0.143;-7005.0
9(6TA)
0.189;-7005.0
9Q(6A)
0.196;-6675.0
Q(6TA)
0.255;-6510.0
(TQ)(6A)
0.244;-5430.0
(6JKA)
0.172;-6180.0
JK(6A)
0.204;-6180.0
K(6KA)
0.227;-4770.0
668A
0.210;-7830.0
6A(6J)
0.195;-6255.0
(67)(7A)
0.222;-5670.0
6(7TA)
0.165;-7335.0
6Q(7A)
0.234;-7005.0
(67)(9A)
0.161;-6420.0
JA(67)
0.175;-7170.0
67(8A)
0.188;-7665.0
67(TA)
0.185;-7335.0
67(QA)
0.174;-7005.0
(68)(8A)
0.231;-5340.0
6(8JA)
0.205;-7005.0
6K(8A)
0.246;-6675.0
(68)(JA)
0.206;-5925.0
KA(68)
0.214;-6675.0
6A(8T)
0.194;-7170.0
6A(8Q)
0.217;-6840.0
6(9TA)
0.166;-7005.0
6Q(9A)
0.168;-6675.0
(69)(JA)
0.212;-5760.0
KA(69)
0.200;-6510.0
6A(9J)
0.222;-6840.0
6A(9K)
0.229;-6510.0
(6Q)(TA)
0.230;-5430.0
JA(6T)
0.208;-6675.0
6T(JA)
0.185;-6675.0
6T(KA)
0.217;-6345.0
6Q(JA)
0.213;-6345.0
(6J)(KA)
0.211;-5100.0
6J(KA)
0.191;-6180.0
6K(QA)
0.216;-6015.0
6A(QK)
0.224;-6015.0
(78)(7A)
0.186;-5340.0
7(7JA)
0.225;-5925.0
7K(7A)
0.196;-5595.0
(78QA)
0.199;-6675.0
8(7TA)
0.237;-7005.0
8Q(7A)
0.192;-6675.0
J(79A)
0.214;-6675.0
9T(7A)
0.208;-6840.0
(9K)(7A)
0.206;-5265.0
K(7TA)
0.274;-6180.0
T(7KA)
0.184;-6180.0
JJ(7A)
0.290;-5265.0
(7QKA)
0.203;-5850.0
777A
0.189;-6585.0
7A(7T)
0.176;-6090.0
77(KA)
0.173;-5595.0
7(8TA)
0.157;-7005.0
7Q(8A)
0.179;-6675.0
(78)(TA)
0.225;-5925.0
QA(78)
0.202;-6675.0
789A
0.169;-8250.0
78JA
0.158;-7920.0
78KA
0.137;-7590.0
7J(9A)
0.240;-6675.0
(79)(TA)
0.219;-5760.0
QA(79)
0.207;-6510.0
79TA
0.139;-7920.0
79QA
0.186;-7590.0
(7J)(TA)
0.257;-5430.0
TA(7T)
0.227;-5595.0
A(7TK)
0.213;-6180.0
TA(7Q)
0.237;-6345.0
7J(JA)
0.215;-5265.0
(7J)(QA)
0.290;-5100.0
JA(7Q)
0.193;-6180.0
7Q(QA)
0.223;-4935.0
7QQA
0.229;-6015.0
7KKA
0.234;-5685.0
8(8JA)
0.214;-5595.0
8K(8A)
0.249;-5265.0
(89KA)
0.226;-6180.0
9J(8A)
0.203;-6510.0
(8TJA)
0.180;-6345.0
(TJ)(8A)
0.220;-5265.0
J(8JA)
0.263;-5100.0
JQ(8A)
0.201;-6015.0
Q(8KA)
0.245;-5685.0
889A
0.208;-7005.0
8A(8Q)
0.191;-5430.0
(8T)(9A)
0.185;-5595.0
8(9KA)
0.231;-6180.0
A(89J)
0.184;-6510.0
899A
0.204;-6840.0
89JA
0.216;-7590.0
89KA
0.229;-7260.0
8Q(TA)
0.173;-6180.0
(8T)(QA)
0.257;-5100.0
TA(8J)
0.211;-6345.0
TA(8K)
0.201;-6015.0
8(JKA)
0.193;-5850.0
A(8JK)
0.197;-5850.0
JA(8K)
0.220;-5850.0
QA(8Q)
0.275;-4770.0
8QKA
0.169;-6765.0
9T(9A)
0.224;-5430.0
(9K)(9A)
0.273;-3855.0
K(9TA)
0.278;-5850.0
T(9KA)
0.265;-5850.0
JJ(9A)
0.213;-4935.0
(9QKA)
0.208;-5520.0
999A
0.216;-5595.0
9A(9Q)
0.232;-5100.0
(9J)(TA)
0.234;-5100.0
TA(9T)
0.182;-5265.0
A(9TK)
0.192;-5850.0
TA(9Q)
0.259;-6015.0
9J(JA)
0.265;-4935.0
(9J)(QA)
0.256;-4770.0
JA(9Q)
0.221;-5850.0
9Q(QA)
0.271;-4605.0
9QQA
0.169;-5685.0
9KKA
0.210;-5355.0
T(TKA)
0.256;-4605.0
JJ(TA)
0.225;-4770.0
(TQKA)
0.202;-5355.0
TTTA
0.236;-5100.0
TA(TK)
0.250;-4605.0
(TK)(JA)
0.217;-4440.0
KA(TJ)
0.180;-5520.0
TA(JK)
0.191;-5520.0
(TQ)(KA)
0.227;-4275.0
(TK)(KA)
0.312;-3030.0
J(JKA)
0.207;-4275.0
(QK)(JA)
0.238;-4110.0
JJ(KA)
0.249;-4275.0
QA(JQ)
0.204;-4275.0
JQKA
0.266;-6270.0
QK(QA)
0.283;-3945.0
QK(KA)
0.275;-3780.0
22(24)
0.143;-9630.0
22(28)
0.149;-8970.0
22(2Q)
0.182;-8310.0
24(23)
0.137;-10545.0
(23)(27)
0.171;-8970.0
2(23T)
0.110;-9555.0
2Q(23)
0.136;-9225.0
23(25)
0.134;-10380.0
2237
0.120;-11130.0
22(3T)
0.144;-9555.0
23(2K)
0.141;-9060.0
2(246)
0.150;-10050.0
28(24)
0.160;-9720.0
(24)(2J)
0.181;-8145.0
2244
0.125;-10380.0
22(47)
0.169;-9885.0
24(2T)
0.164;-9390.0
224Q
0.139;-10140.0
26(25)
0.158;-9885.0
(25)(29)
0.132;-8310.0
2(25Q)
0.144;-8895.0
22(56)
0.106;-9885.0
25(29)
0.148;-9390.0
225J
0.124;-10140.0
26(26)
0.159;-8640.0
(26)(29)
0.178;-8145.0
2(26Q)
0.167;-8730.0
22(67)
0.146;-9555.0
26(2T)
0.167;-9060.0
226Q
0.142;-9810.0
28(27)
0.143;-9225.0
(27)(2J)
0.182;-7650.0
2277
0.150;-9390.0
22(7T)
0.146;-8895.0
27(2K)
0.126;-8400.0
2(28T)
0.163;-8730.0
2Q(28)
0.120;-8400.0
28(2T)
0.203;-8730.0
228Q
0.134;-9480.0
2T(29)
0.157;-8565.0
(29)(2K)
0.153;-6990.0
229J
0.172;-9480.0
2T(2T)
0.224;-7320.0
(2T)(2K)
0.206;-6825.0
22TQ
0.144;-9150.0
2Q(2J)
0.158;-7905.0
2J(2K)
0.160;-7740.0
22QQ
0.179;-7740.0
3(234)
0.141;-10380.0
36(23)
0.157;-10050.0
(23)(39)
0.215;-8475.0
3(23Q)
0.127;-9060.0
5(234)
0.131;-11130.0
9(234)
0.148;-10470.0
K(234)
0.141;-9810.0
4(237)
0.110;-10800.0
49(23)
0.119;-10470.0
(23)(4Q)
0.131;-8895.0
(2357)
0.153;-10635.0
(235J)
0.141;-9975.0
(23)(56)
0.120;-9720.0
5(239)
0.112;-10305.0
5J(23)
0.174;-9975.0
(2367)
0.150;-10470.0
(236J)
0.159;-9810.0
(23)(67)
0.145;-9390.0
6(23T)
0.139;-9975.0
6Q(23)
0.143;-9645.0
9(237)
0.109;-9975.0
K(237)
0.155;-9315.0
7(23T)
0.110;-9810.0
7Q(23)
0.131;-9480.0
T(238)
0.148;-9645.0
8(239)
0.149;-9810.0
8J(23)
0.153;-9480.0
(239T)
0.147;-9480.0
99(23)
0.155;-8565.0
(23)(9Q)
0.128;-8070.0
(23TQ)
0.129;-8985.0
T(23Q)
0.114;-8985.0
Q(23J)
0.191;-8820.0
(23)(JK)
0.178;-7575.0
QK(23)
0.148;-8490.0
23(35)
0.143;-10215.0
33(28)
0.121;-9720.0
233T
0.116;-10470.0
23(3K)
0.159;-8895.0
(24)(36)
0.123;-9885.0
3(249)
0.115;-10470.0
3J(24)
0.139;-10140.0
(34)(25)
0.182;-10050.0
27(34)
0.116;-10800.0
2(34T)
0.139;-10305.0
(34)(2K)
0.169;-8730.0
34(26)
0.114;-10965.0
34(28)
0.091;-10635.0
34(2T)
0.116;-10305.0
34(2Q)
0.164;-9975.0
(25)(35)
0.145;-8805.0
3(258)
0.144;-10470.0
3T(25)
0.114;-10140.0
(25)(3K)
0.167;-8565.0
27(35)
0.110;-10635.0
2(35T)
0.176;-10140.0
(35)(2K)
0.194;-8565.0
35(27)
0.154;-10635.0
35(29)
0.128;-10305.0
35(2J)
0.112;-9975.0
35(2K)
0.102;-9645.0
37(26)
0.132;-10470.0
(26)(3T)
0.155;-8895.0
3(26K)
0.147;-9480.0
2(368)
0.132;-10305.0
(36)(2J)
0.154;-8730.0
2K(36)
0.154;-9480.0
23(68)
0.122;-10305.0
23(6T)
0.130;-9975.0
23(6Q)
0.155;-9645.0
3(278)
0.176;-10140.0
3T(27)
0.153;-9810.0
(27)(3K)
0.133;-8235.0
29(37)
0.171;-9975.0
2(37Q)
0.161;-9480.0
23(78)
0.148;-10140.0
23(7T)
0.126;-9810.0
23(7Q)
0.167;-9480.0
3(289)
0.176;-9810.0
3J(28)
0.154;-9480.0
(38)(29)
0.129;-8730.0
2J(38)
0.184;-9480.0
38(29)
0.144;-9810.0
38(2J)
0.160;-9480.0
38(2K)
0.176;-9150.0
3T(29)
0.120;-9480.0
(29)(3K)
0.134;-7905.0
2J(39)
0.130;-9315.0
39(2T)
0.130;-9480.0
39(2Q)
0.130;-9150.0
(2T)(3T)
0.228;-7155.0
3(2TK)
0.139;-8820.0
2(3TQ)
0.163;-8985.0
23(TJ)
0.178;-9150.0
23(TK)
0.138;-8820.0
(2J)(3K)
0.204;-7575.0
2K(3J)
0.167;-8655.0
23(JK)
0.150;-8655.0
(3Q)(2K)
0.221;-7410.0
(2K)(3K)
0.202;-6165.0
4(246)
0.141;-9720.0
48(24)
0.164;-9390.0
(24)(4J)
0.162;-7815.0
5(245)
0.160;-9720.0
9(245)
0.123;-10140.0
K(245)
0.159;-9480.0
5(248)
0.141;-10305.0
5T(24)
0.136;-9975.0
(24)(5K)
0.152;-8400.0
9(246)
0.133;-9975.0
K(246)
0.116;-9315.0
6(249)
0.141;-9975.0
6J(24)
0.142;-9645.0
(2478)
0.145;-9975.0
(247Q)
0.164;-9315.0
7(249)
0.131;-9810.0
7J(24)
0.152;-9480.0
(2489)
0.136;-9645.0
(248K)
0.169;-8985.0
8T(24)
0.117;-9480.0
(24)(8K)
0.132;-7905.0
Q(249)
0.188;-8985.0
(24)(9J)
0.160;-8070.0
T(24T)
0.156;-8070.0
T(24J)
0.109;-8985.0
TK(24)
0.128;-8655.0
(24)(JQ)
0.217;-7575.0
QQ(24)
0.178;-7410.0
24(45)
0.103;-9885.0
44(28)
0.148;-9390.0
244T
0.119;-10140.0
24(4K)
0.157;-8565.0
(25)(47)
0.153;-9390.0
4(25T)
0.145;-9975.0
4Q(25)
0.168;-9645.0
(45)(27)
0.169;-9390.0
29(45)
0.161;-10140.0
2(45Q)
0.136;-9645.0
24(56)
0.097;-10635.0
24(58)
0.151;-10305.0
24(5T)
0.119;-9975.0
24(5Q)
0.160;-9645.0
4(267)
0.132;-10305.0
49(26)
0.164;-9975.0
(26)(4Q)
0.136;-8400.0
27(46)
0.130;-10305.0
2(46T)
0.150;-9810.0
(46)(2K)
0.177;-8235.0
46(28)
0.133;-10140.0
46(2T)
0.149;-9810.0
46(2Q)
0.134;-9480.0
(27)(47)
0.174;-7980.0
4(27T)
0.154;-9645.0
4Q(27)
0.146;-9315.0
(47)(29)
0.178;-8730.0
2J(47)
0.179;-9480.0
47(28)
0.146;-9975.0
47(2T)
0.116;-9645.0
47(2Q)
0.175;-9315.0
(28)(48)
0.186;-7650.0
4(28J)
0.127;-9315.0
4K(28)
0.175;-8985.0
(48)(2J)
0.201;-8235.0
2K(48)
0.140;-8985.0
24(8T)
0.123;-9480.0
24(8Q)
0.179;-9150.0
4(29T)
0.131;-9315.0
4Q(29)
0.146;-8985.0
(49)(2J)
0.182;-8070.0
2K(49)
0.147;-8820.0
24(9J)
0.169;-9150.0
24(9K)
0.155;-8820.0
(2T)(4Q)
0.220;-7740.0
2J(4T)
0.132;-8985.0
4T(2J)
0.128;-8985.0
4T(2K)
0.172;-8655.0
4Q(2J)
0.169;-8655.0
(4J)(2K)
0.187;-7410.0
4J(2K)
0.169;-8490.0
4K(2Q)
0.139;-8325.0
24(QK)
0.130;-8325.0
(25)(56)
0.207;-8310.0
5(259)
0.117;-8895.0
5J(25)
0.158;-8565.0
(2567)
0.126;-10140.0
(256J)
0.147;-9480.0
(25)(67)
0.155;-9060.0
6(25T)
0.114;-9645.0
6Q(25)
0.143;-9315.0
9(257)
0.145;-9645.0
K(257)
0.182;-8985.0
7(25T)
0.138;-9480.0
7Q(25)
0.163;-9150.0
T(258)
0.112;-9315.0
8(259)
0.149;-9480.0
8J(25)
0.185;-9150.0
(259T)
0.146;-9150.0
99(25)
0.161;-8235.0
(25)(9Q)
0.137;-7740.0
(25TQ)
0.137;-8655.0
T(25Q)
0.212;-8655.0
Q(25J)
0.202;-8490.0
(25)(JK)
0.193;-7245.0
QK(25)
0.168;-8160.0
25(57)
0.140;-9225.0
55(2T)
0.140;-8730.0
255Q
0.163;-9480.0
57(26)
0.143;-10140.0
(26)(5T)
0.125;-8565.0
5(26K)
0.155;-9150.0
2(568)
0.157;-9975.0
(56)(2J)
0.164;-8400.0
2K(56)
0.169;-9150.0
25(68)
0.152;-9975.0
25(6T)
0.152;-9645.0
25(6Q)
0.157;-9315.0
5(278)
0.127;-9810.0
5T(27)
0.135;-9480.0
(27)(5K)
0.165;-7905.0
29(57)
0.162;-9645.0
2(57Q)
0.151;-9150.0
25(78)
0.124;-9810.0
25(7T)
0.135;-9480.0
25(7Q)
0.152;-9150.0
5(289)
0.195;-9480.0
5J(28)
0.134;-9150.0
(58)(29)
0.132;-8400.0
2J(58)
0.155;-9150.0
58(29)
0.177;-9480.0
58(2J)
0.123;-9150.0
58(2K)
0.152;-8820.0
5T(29)
0.151;-9150.0
(29)(5K)
0.145;-7575.0
2J(59)
0.129;-8985.0
59(2T)
0.121;-9150.0
59(2Q)
0.157;-8820.0
(2T)(5T)
0.186;-6825.0
5(2TK)
0.154;-8490.0
2(5TQ)
0.161;-8655.0
25(TJ)
0.173;-8820.0
25(TK)
0.143;-8490.0
(2J)(5K)
0.204;-7245.0
2K(5J)
0.148;-8325.0
25(JK)
0.169;-8325.0
(5Q)(2K)
0.218;-7080.0
(2K)(5K)
0.189;-5835.0
6(268)
0.150;-8730.0
6T(26)
0.131;-8400.0
(26)(6K)
0.154;-6825.0
T(267)
0.174;-9315.0
7(268)
0.180;-9645.0
7T(26)
0.159;-9315.0
(26)(7K)
0.200;-7740.0
J(268)
0.124;-8985.0
89(26)
0.121;-9315.0
(26)(8Q)
0.134;-7740.0
(269J)
0.131;-8820.0
(26)(9T)
0.136;-7905.0
9(26K)
0.187;-8490.0
(26TK)
0.157;-8325.0
TQ(26)
0.166;-8490.0
K(26J)
0.192;-8160.0
Q(26Q)
0.186;-7080.0
KK(26)
0.230;-6750.0
66(29)
0.194;-8565.0
266J
0.155;-9315.0
67(27)
0.127;-8730.0
(27)(6T)
0.199;-8235.0
6(27K)
0.134;-8820.0
2(679)
0.190;-9480.0
(67)(2Q)
0.179;-7905.0
27(68)
0.150;-9645.0
27(6T)
0.162;-9315.0
27(6Q)
0.158;-8985.0
68(28)
0.173;-8400.0
(28)(6J)
0.176;-7905.0
28(68)
0.198;-8400.0
2(68J)
0.132;-8985.0
2688
0.136;-9480.0
268T
0.134;-10230.0
268Q
0.170;-9900.0
(29)(6T)
0.176;-7905.0
6(29K)
0.155;-8490.0
2(69J)
0.124;-8820.0
2699
0.150;-9150.0
269J
0.155;-9900.0
269K
0.137;-9570.0
6Q(2T)
0.183;-8490.0
(6T)(2Q)
0.198;-7410.0
2T(6J)
0.170;-8655.0
2T(6K)
0.186;-8325.0
6(2JK)
0.198;-8160.0
2(6JK)
0.160;-8160.0
2J(6K)
0.186;-8160.0
2Q(6Q)
0.183;-7080.0
26QK
0.159;-9075.0
78(27)
0.167;-8400.0
(27)(7J)
0.157;-6825.0
8(278)
0.166;-8235.0
Q(278)
0.169;-8655.0
(27)(8T)
0.151;-7905.0
8(27K)
0.150;-8490.0
(279Q)
0.195;-8490.0
9(27J)
0.155;-8655.0
9K(27)
0.159;-8325.0
TT(27)
0.164;-7575.0
(27)(TK)
0.180;-7080.0
J(27Q)
0.166;-8160.0
K(27Q)
0.182;-7830.0
77(28)
0.177;-8400.0
277T
0.135;-9150.0
27(7K)
0.206;-7575.0
(28)(7T)
0.187;-7905.0
7(28K)
0.168;-8490.0
2(78T)
0.139;-8985.0
(78)(2K)
0.146;-7410.0
78(2T)
0.135;-8985.0
78(2Q)
0.140;-8655.0
(29)(79)
0.207;-6825.0
7(29Q)
0.165;-8490.0
2(79T)
0.146;-8820.0
(79)(2K)
0.244;-7245.0
79(2J)
0.169;-8655.0
79(2K)
0.147;-8325.0
7J(2T)
0.162;-8490.0
(7T)(2J)
0.181;-7410.0
2K(7T)
0.220;-8160.0
27(TQ)
0.152;-8325.0
7(2JQ)
0.191;-8160.0
2(7JQ)
0.162;-8160.0
27(JQ)
0.189;-8160.0
7(2QK)
0.127;-7830.0
7Q(2K)
0.164;-7830.0
88(28)
0.169;-6990.0
(28)(8J)
0.196;-6495.0
9(289)
0.135;-7740.0
K(289)
0.162;-8160.0
9(28Q)
0.156;-8325.0
J(28T)
0.183;-8325.0
TJ(28)
0.172;-8325.0
(28JQ)
0.179;-7995.0
J(28K)
0.188;-7830.0
(28)(QK)
0.231;-6585.0
88(2T)
0.166;-7740.0
288Q
0.169;-8490.0
8T(29)
0.147;-8655.0
(29)(8K)
0.194;-7080.0
2J(89)
0.156;-8490.0
89(2T)
0.142;-8655.0
89(2Q)
0.190;-8325.0
(2T)(8T)
0.224;-6330.0
8(2TK)
0.165;-7995.0
2(8TQ)
0.125;-8160.0
28(TJ)
0.184;-8325.0
28(TK)
0.140;-7995.0
(2J)(8K)
0.155;-6750.0
2K(8J)
0.192;-7830.0
28(JK)
0.136;-7830.0
(8Q)(2K)
0.215;-6585.0
(2K)(8K)
0.217;-5340.0
9(29J)
0.230;-7245.0
9K(29)
0.193;-6915.0
TT(29)
0.143;-7245.0
(29)(TK)
0.189;-6750.0
J(29Q)
0.175;-7830.0
K(29Q)
0.169;-7500.0
99(2T)
0.204;-7410.0
299Q
0.154;-8160.0
9J(2T)
0.209;-8160.0
(9T)(2J)
0.159;-7080.0
2K(9T)
0.202;-7830.0
29(TQ)
0.154;-7995.0
9(2JQ)
0.181;-7830.0
2(9JQ)
0.146;-7830.0
29(JQ)
0.188;-7830.0
9(2QK)
0.168;-7500.0
9Q(2K)
0.199;-7500.0
TT(2T)
0.212;-6000.0
(2T)(TK)
0.255;-5505.0
J(2TQ)
0.185;-7665.0
K(2TQ)
0.158;-7335.0
TT(2J)
0.252;-6915.0
2TTK
0.193;-7665.0
TK(2J)
0.172;-7500.0
2TJJ
0.162;-7830.0
2TJK
0.160;-8580.0
2(TQK)
0.222;-7335.0
TK(2K)
0.193;-6090.0
(2J)(JK)
0.240;-5175.0
QK(2J)
0.198;-7170.0
2J(JK)
0.189;-6255.0
(JQ)(2K)
0.208;-6090.0
(2K)(JK)
0.226;-4845.0
K(2QK)
0.268;-5760.0
2K(QK)
0.241;-5760.0
3335
0.156;-10050.0
3339
0.140;-9390.0
333K
0.186;-8730.0
36(34)
0.167;-9720.0
(34)(39)
0.153;-8145.0
3(34Q)
0.202;-8730.0
33(45)
0.139;-9885.0
34(38)
0.159;-9390.0
334T
0.154;-10140.0
33(4K)
0.121;-8565.0
(35)(37)
0.181;-8310.0
3(35T)
0.131;-8895.0
3Q(35)
0.153;-8565.0
35(37)
0.122;-9390.0
3359
0.171;-10140.0
33(5Q)
0.119;-8565.0
(36)(37)
0.162;-8145.0
3(36T)
0.141;-8730.0
3Q(36)
0.172;-8400.0
36(38)
0.153;-9060.0
336T
0.126;-9810.0
33(6K)
0.204;-8235.0
(37)(39)
0.196;-7650.0
3(37Q)
0.137;-8235.0
33(78)
0.175;-8895.0
37(3J)
0.158;-8400.0
337K
0.131;-9150.0
3T(38)
0.189;-8400.0
(38)(3K)
0.159;-6825.0
338T
0.141;-9480.0
33(8K)
0.129;-7905.0
(39)(3J)
0.228;-6990.0
3399
0.164;-8400.0
33(9Q)
0.148;-7905.0
(3T)(3J)
0.230;-6825.0
33TT
0.172;-8070.0
33(TK)
0.221;-7575.0
(3J)(3K)
0.204;-6330.0
33JK
0.176;-8490.0
33(QK)
0.155;-7245.0
45(34)
0.127;-9720.0
(34)(48)
0.173;-8145.0
4(34J)
0.195;-8730.0
4K(34)
0.203;-8400.0
(3459)
0.118;-9975.0
(345K)
0.161;-9315.0
57(34)
0.129;-10305.0
(34)(5T)
0.132;-8730.0
5(34K)
0.151;-9315.0
(3469)
0.132;-9810.0
(346K)
0.193;-9150.0
68(34)
0.153;-9975.0
(34)(6J)
0.120;-8400.0
7(347)
0.189;-8895.0
J(347)
0.191;-9315.0
78(34)
0.114;-9810.0
(34)(7J)
0.156;-8235.0
8(348)
0.169;-8565.0
Q(348)
0.179;-8985.0
(34)(8T)
0.168;-8235.0
8(34K)
0.178;-8820.0
(349Q)
0.118;-8820.0
9(34J)
0.137;-8985.0
9K(34)
0.140;-8655.0
TT(34)
0.184;-7905.0
(34)(TK)
0.199;-7410.0
J(34Q)
0.141;-8490.0
K(34Q)
0.187;-8160.0
44(35)
0.167;-9720.0
3447
0.103;-10470.0
34(4T)
0.157;-8895.0
44(3K)
0.172;-8400.0
4(357)
0.156;-10305.0
49(35)
0.121;-9975.0
(35)(4Q)
0.174;-8400.0
36(45)
0.122;-10470.0
3(459)
0.108;-9975.0
(45)(3Q)
0.130;-8400.0
35(46)
0.147;-10470.0
35(48)
0.164;-10140.0
35(4T)
0.114;-9810.0
35(4Q)
0.168;-9480.0
46(36)
0.140;-9225.0
(36)(49)
0.175;-8730.0
4(36Q)
0.129;-9315.0
3(467)
0.116;-10140.0
(46)(3T)
0.180;-8565.0
3Q(46)
0.170;-9315.0
3467
0.099;-11220.0
3469
0.163;-10890.0
346J
0.105;-10560.0
346K
0.127;-10230.0
49(37)
0.140;-9645.0
(37)(4Q)
0.178;-8070.0
38(47)
0.123;-9810.0
3(47J)
0.155;-9315.0
3477
0.120;-9975.0
3479
0.112;-10725.0
347J
0.101;-10395.0
347K
0.169;-10065.0
4T(38)
0.113;-9315.0
(38)(4K)
0.179;-7740.0
3T(48)
0.124;-9315.0
3(48K)
0.157;-8820.0
38(4T)
0.151;-9315.0
38(4Q)
0.174;-8985.0
49(39)
0.179;-8235.0
(39)(4Q)
0.147;-7740.0
3T(49)
0.133;-9150.0
3(49K)
0.187;-8655.0
39(4J)
0.121;-8985.0
39(4K)
0.197;-8655.0
4(3TQ)
0.135;-8655.0
3(4TJ)
0.165;-8820.0
34TT
0.146;-8985.0
34TQ
0.124;-9735.0
(3J)(4Q)
0.224;-7410.0
3Q(4J)
0.181;-8490.0
34JQ
0.129;-9570.0
(3Q)(4K)
0.239;-7080.0
3Q(4K)
0.182;-8160.0
5(356)
0.136;-9225.0
58(35)
0.134;-8895.0
(35)(5J)
0.194;-7320.0
6(356)
0.142;-9060.0
T(356)
0.150;-9480.0
6(357)
0.110;-9975.0
69(35)
0.170;-9645.0
(35)(6Q)
0.174;-8070.0
(3579)
0.144;-9480.0
(357K)
0.174;-8820.0
79(35)
0.148;-9480.0
(35)(7Q)
0.174;-7905.0
(358T)
0.152;-9150.0
88(35)
0.157;-8400.0
(35)(8J)
0.181;-7905.0
9(359)
0.154;-8070.0
K(359)
0.164;-8490.0
9(35Q)
0.162;-8655.0
J(35T)
0.118;-8655.0
TJ(35)
0.153;-8655.0
(35JQ)
0.159;-8325.0
J(35K)
0.202;-8160.0
(35)(QK)
0.197;-6915.0
55(37)
0.133;-9060.0
3559
0.151;-9810.0
35(5Q)
0.151;-8235.0
(36)(57)
0.176;-8895.0
5(36T)
0.103;-9480.0
5Q(36)
0.156;-9150.0
(56)(38)
0.195;-8730.0
3T(56)
0.150;-9480.0
3(56K)
0.173;-8985.0
36(58)
0.116;-9810.0
36(5T)
0.141;-9480.0
36(5Q)
0.178;-9150.0
57(37)
0.163;-8730.0
(37)(5T)
0.153;-8235.0
5(37K)
0.166;-8820.0
3(579)
0.137;-9480.0
(57)(3Q)
0.168;-7905.0
37(58)
0.189;-9645.0
37(5T)
0.146;-9315.0
37(5Q)
0.143;-8985.0
58(38)
0.175;-8400.0
(38)(5J)
0.170;-7905.0
38(58)
0.164;-8400.0
3(58J)
0.151;-8985.0
3588
0.133;-9480.0
358T
0.127;-10230.0
358Q
0.174;-9900.0
(39)(5T)
0.152;-7905.0
5(39K)
0.166;-8490.0
3(59J)
0.170;-8820.0
3599
0.161;-9150.0
359J
0.163;-9900.0
359K
0.137;-9570.0
5Q(3T)
0.135;-8490.0
(5T)(3Q)
0.189;-7410.0
3T(5J)
0.193;-8655.0
3T(5K)
0.163;-8325.0
5(3JK)
0.134;-8160.0
3(5JK)
0.139;-8160.0
3J(5K)
0.161;-8160.0
3Q(5Q)
0.246;-7080.0
35QK
0.136;-9075.0
67(36)
0.168;-8730.0
(36)(6T)
0.173;-7155.0
6(36K)
0.197;-7740.0
(367T)
0.156;-9150.0
77(36)
0.158;-8565.0
(36)(7T)
0.202;-8070.0
7(36K)
0.131;-8655.0
(368J)
0.130;-8820.0
(36)(89)
0.148;-8070.0
8(36Q)
0.153;-8655.0
T(369)
0.119;-8820.0
9(36T)
0.144;-8820.0
9Q(36)
0.218;-8490.0
Q(36T)
0.142;-8325.0
(36)(TQ)
0.186;-7245.0
(36JK)
0.142;-7995.0
JK(36)
0.184;-7995.0
K(36K)
0.195;-6585.0
3668
0.107;-9645.0
36(6J)
0.148;-8070.0
(37)(67)
0.144;-7485.0
6(37T)
0.141;-9150.0
6Q(37)
0.160;-8820.0
(67)(39)
0.178;-8235.0
3J(67)
0.157;-8985.0
67(38)
0.142;-9480.0
67(3T)
0.184;-9150.0
67(3Q)
0.155;-8820.0
(38)(68)
0.166;-7155.0
6(38J)
0.147;-8820.0
6K(38)
0.131;-8490.0
(68)(3J)
0.174;-7740.0
3K(68)
0.145;-8490.0
36(8T)
0.152;-8985.0
36(8Q)
0.194;-8655.0
6(39T)
0.116;-8820.0
6Q(39)
0.128;-8490.0
(69)(3J)
0.175;-7575.0
3K(69)
0.221;-8325.0
36(9J)
0.120;-8655.0
36(9K)
0.149;-8325.0
(3T)(6Q)
0.191;-7245.0
3J(6T)
0.160;-8490.0
6T(3J)
0.151;-8490.0
6T(3K)
0.137;-8160.0
6Q(3J)
0.182;-8160.0
(6J)(3K)
0.177;-6915.0
6J(3K)
0.166;-7995.0
6K(3Q)
0.212;-7830.0
36(QK)
0.200;-7830.0
(37)(78)
0.182;-7155.0
7(37J)
0.165;-7740.0
7K(37)
0.215;-7410.0
(378Q)
0.172;-8490.0
8(37T)
0.162;-8820.0
8Q(37)
0.151;-8490.0
J(379)
0.163;-8490.0
9T(37)
0.160;-8655.0
(37)(9K)
0.196;-7080.0
K(37T)
0.193;-7995.0
T(37K)
0.171;-7995.0
JJ(37)
0.162;-7080.0
(37QK)
0.194;-7665.0
3777
0.146;-8400.0
37(7T)
0.154;-7905.0
77(3K)
0.153;-7410.0
7(38T)
0.157;-8820.0
7Q(38)
0.145;-8490.0
(78)(3T)
0.193;-7740.0
3Q(78)
0.176;-8490.0
3789
0.176;-10065.0
378J
0.142;-9735.0
378K
0.148;-9405.0
7J(39)
0.176;-8490.0
(79)(3T)
0.204;-7575.0
3Q(79)
0.156;-8325.0
379T
0.114;-9735.0
379Q
0.149;-9405.0
(3T)(7J)
0.222;-7245.0
3T(7T)
0.169;-7410.0
3(7TK)
0.131;-7995.0
3T(7Q)
0.211;-8160.0
7J(3J)
0.204;-7080.0
(7J)(3Q)
0.167;-6915.0
3J(7Q)
0.184;-7995.0
7Q(3Q)
0.214;-6750.0
37QQ
0.214;-7830.0
37KK
0.193;-7500.0
8(38J)
0.223;-7410.0
8K(38)
0.229;-7080.0
(389K)
0.149;-7995.0
9J(38)
0.186;-8325.0
(38TJ)
0.157;-8160.0
(38)(TJ)
0.215;-7080.0
J(38J)
0.179;-6915.0
JQ(38)
0.162;-7830.0
Q(38K)
0.152;-7500.0
3889
0.175;-8820.0
38(8Q)
0.245;-7245.0
(39)(8T)
0.214;-7410.0
8(39K)
0.183;-7995.0
3(89J)
0.181;-8325.0
3899
0.136;-8655.0
389J
0.126;-9405.0
389K
0.134;-9075.0
8Q(3T)
0.163;-7995.0
(8T)(3Q)
0.198;-6915.0
3T(8J)
0.183;-8160.0
3T(8K)
0.183;-7830.0
8(3JK)
0.174;-7665.0
3(8JK)
0.140;-7665.0
3J(8K)
0.131;-7665.0
3Q(8Q)
0.181;-6585.0
38QK
0.171;-8580.0
9T(39)
0.211;-7245.0
(39)(9K)
0.222;-5670.0
K(39T)
0.223;-7665.0
T(39K)
0.202;-7665.0
JJ(39)
0.186;-6750.0
(39QK)
0.179;-7335.0
3999
0.184;-7410.0
39(9Q)
0.198;-6915.0
(3T)(9J)
0.170;-6915.0
3T(9T)
0.147;-7080.0
3(9TK)
0.169;-7665.0
3T(9Q)
0.170;-7830.0
9J(3J)
0.215;-6750.0
(9J)(3Q)
0.224;-6585.0
3J(9Q)
0.142;-7665.0
9Q(3Q)
0.209;-6420.0
39QQ
0.214;-7500.0
39KK
0.181;-7170.0
T(3TK)
0.154;-6420.0
JJ(3T)
0.243;-6585.0
(3TQK)
0.169;-7170.0
3TTT
0.212;-6915.0
3T(TK)
0.190;-6420.0
(3J)(TK)
0.234;-6255.0
3K(TJ)
0.197;-7335.0
3T(JK)
0.192;-7335.0
(TQ)(3K)
0.183;-6090.0
(3K)(TK)
0.279;-4845.0
J(3JK)
0.225;-6090.0
(3J)(QK)
0.211;-5925.0
JJ(3K)
0.228;-6090.0
3Q(JQ)
0.203;-6090.0
3JQK
0.150;-8085.0
QK(3Q)
0.176;-5760.0
QK(3K)
0.195;-5595.0
44(46)
0.149;-8310.0
44(4T)
0.173;-7650.0
(45)(45)
0.165;-7230.0
4(458)
0.143;-8895.0
4T(45)
0.189;-8565.0
(45)(4K)
0.139;-6990.0
4457
0.162;-10140.0
44(5T)
0.156;-8565.0
45(4K)
0.215;-8070.0
4(468)
0.207;-8730.0
4T(46)
0.144;-8400.0
(46)(4K)
0.226;-6825.0
4468
0.169;-9810.0
44(6J)
0.177;-8235.0
(47)(47)
0.180;-6570.0
4(47T)
0.210;-8235.0
4Q(47)
0.182;-7905.0
47(49)
0.215;-8400.0
447J
0.123;-9150.0
48(48)
0.141;-7320.0
(48)(4J)
0.234;-6825.0
4488
0.131;-8400.0
44(8J)
0.192;-7905.0
(49)(49)
0.193;-5910.0
4(49Q)
0.207;-7575.0
44(9T)
0.168;-7905.0
49(4K)
0.189;-7410.0
4(4TQ)
0.173;-7410.0
44(TJ)
0.161;-7575.0
(4J)(4J)
0.265;-5250.0
44JJ
0.163;-7410.0
4Q(4Q)
0.216;-6000.0
(4K)(4K)
0.302;-4590.0
(45)(57)
0.168;-7815.0
5(45T)
0.123;-8400.0
5Q(45)
0.149;-8070.0
8(456)
0.124;-9645.0
Q(456)
0.121;-8985.0
(45)(68)
0.143;-8565.0
6(45J)
0.200;-9150.0
6K(45)
0.135;-8820.0
(457J)
0.159;-8985.0
(45)(78)
0.165;-8400.0
7(45J)
0.120;-8985.0
7K(45)
0.134;-8655.0
(458Q)
0.174;-8655.0
8(45T)
0.187;-8985.0
8Q(45)
0.140;-8655.0
J(459)
0.200;-8655.0
9T(45)
0.160;-8820.0
(45)(9K)
0.215;-7245.0
K(45T)
0.135;-8160.0
T(45K)
0.167;-8160.0
JJ(45)
0.242;-7245.0
(45QK)
0.157;-7830.0
4555
0.149;-9225.0
45(58)
0.155;-8730.0
55(4J)
0.181;-8235.0
455K
0.173;-8985.0
58(46)
0.143;-9645.0
(46)(5J)
0.178;-8070.0
46(56)
0.155;-8895.0
4(569)
0.162;-9480.0
(56)(4Q)
0.192;-7905.0
46(57)
0.147;-9810.0
46(59)
0.159;-9480.0
46(5J)
0.144;-9150.0
46(5K)
0.170;-8820.0
5(479)
0.178;-9315.0
5J(47)
0.157;-8985.0
(57)(48)
0.154;-8400.0
4T(57)
0.185;-9150.0
4(57K)
0.147;-8655.0
47(59)
0.190;-9315.0
47(5J)
0.163;-8985.0
47(5K)
0.122;-8655.0
5(48T)
0.158;-8985.0
5Q(48)
0.142;-8655.0
(58)(4T)
0.171;-7905.0
4Q(58)
0.179;-8655.0
4589
0.144;-10230.0
458J
0.143;-9900.0
458K
0.124;-9570.0
5J(49)
0.161;-8655.0
(59)(4T)
0.163;-7740.0
4Q(59)
0.187;-8490.0
459T
0.132;-9900.0
459Q
0.179;-9570.0
(4T)(5J)
0.178;-7410.0
4T(5T)
0.219;-7575.0
4(5TK)
0.160;-8160.0
4T(5Q)
0.157;-8325.0
5J(4J)
0.195;-7245.0
(5J)(4Q)
0.164;-7080.0
4J(5Q)
0.159;-8160.0
5Q(4Q)
0.159;-6915.0
45QQ
0.172;-7995.0
45KK
0.163;-7665.0
6(469)
0.191;-8235.0
6J(46)
0.180;-7905.0
(4678)
0.183;-9315.0
(467Q)
0.136;-8655.0
7(469)
0.201;-9150.0
7J(46)
0.187;-8820.0
(4689)
0.165;-8985.0
(468K)
0.165;-8325.0
8T(46)
0.170;-8820.0
(46)(8K)
0.197;-7245.0
Q(469)
0.164;-8325.0
(46)(9J)
0.215;-7410.0
T(46T)
0.215;-7410.0
T(46J)
0.147;-8325.0
TK(46)
0.157;-7995.0
(46)(JQ)
0.212;-6915.0
QQ(46)
0.162;-6750.0
46(67)
0.137;-8565.0
66(4T)
0.167;-8070.0
466Q
0.187;-8820.0
68(47)
0.136;-9315.0
(47)(6J)
0.175;-7740.0
47(67)
0.125;-8400.0
4(67T)
0.169;-8985.0
(67)(4K)
0.171;-7410.0
67(49)
0.137;-9150.0
67(4J)
0.147;-8820.0
67(4K)
0.185;-8490.0
69(48)
0.152;-8985.0
(48)(6Q)
0.157;-7410.0
49(68)
0.136;-8985.0
4(68Q)
0.163;-8490.0
46(89)
0.173;-8985.0
46(8J)
0.171;-8655.0
46(8K)
0.184;-8325.0
(49)(6J)
0.204;-7410.0
49(69)
0.217;-7740.0
4(69Q)
0.151;-8325.0
46(9T)
0.173;-8655.0
46(9Q)
0.155;-8325.0
6(4TJ)
0.154;-8325.0
6K(4T)
0.174;-7995.0
(6T)(4K)
0.220;-6915.0
6T(4Q)
0.154;-8160.0
(4J)(6J)
0.195;-6000.0
4J(6J)
0.173;-7080.0
6J(4Q)
0.200;-7995.0
(4Q)(6Q)
0.230;-5670.0
4K(6Q)
0.141;-7665.0
4K(6K)
0.199;-6420.0
79(47)
0.138;-7905.0
(47)(7Q)
0.189;-6330.0
(478T)
0.117;-8655.0
88(47)
0.144;-7905.0
(47)(8J)
0.146;-7410.0
9(479)
0.144;-7575.0
K(479)
0.177;-7995.0
9(47Q)
0.144;-8160.0
J(47T)
0.226;-8160.0
TJ(47)
0.165;-8160.0
(47JQ)
0.172;-7830.0
J(47K)
0.170;-7665.0
(47)(QK)
0.243;-6420.0
77(49)
0.149;-7905.0
477J
0.136;-8655.0
78(48)
0.149;-7905.0
(48)(7J)
0.140;-7410.0
48(78)
0.155;-7905.0
4(78J)
0.166;-8490.0
4788
0.123;-8985.0
478T
0.179;-9735.0
478Q
0.141;-9405.0
(49)(7T)
0.204;-7410.0
7(49K)
0.165;-7995.0
4(79J)
0.162;-8325.0
4799
0.122;-8655.0
479J
0.140;-9405.0
479K
0.147;-9075.0
7Q(4T)
0.144;-7995.0
(7T)(4Q)
0.233;-6915.0
4T(7J)
0.140;-8160.0
4T(7K)
0.176;-7830.0
7(4JK)
0.223;-7665.0
4(7JK)
0.172;-7665.0
4J(7K)
0.160;-7665.0
4Q(7Q)
0.253;-6585.0
47QK
0.161;-8580.0
89(48)
0.178;-7575.0
(48)(8Q)
0.159;-6000.0
(489J)
0.208;-8160.0
(48)(9T)
0.172;-7245.0
9(48K)
0.180;-7830.0
(48TK)
0.198;-7665.0
TQ(48)
0.144;-7830.0
K(48J)
0.213;-7500.0
Q(48Q)
0.192;-6420.0
KK(48)
0.178;-6090.0
88(4J)
0.195;-7245.0
488K
0.204;-7995.0
8J(49)
0.182;-8160.0
(89)(4T)
0.192;-7245.0
4Q(89)
0.172;-7995.0
489T
0.118;-9405.0
489Q
0.134;-9075.0
(4T)(8J)
0.229;-6915.0
4T(8T)
0.203;-7080.0
4(8TK)
0.151;-7665.0
4T(8Q)
0.150;-7830.0
8J(4J)
0.168;-6750.0
(8J)(4Q)
0.227;-6585.0
4J(8Q)
0.166;-7665.0
8Q(4Q)
0.209;-6420.0
48QQ
0.179;-7500.0
48KK
0.182;-7170.0
9(49Q)
0.193;-6750.0
J(49T)
0.179;-7830.0
TJ(49)
0.166;-7830.0
(49JQ)
0.163;-7500.0
J(49K)
0.207;-7335.0
(49)(QK)
0.220;-6090.0
99(4J)
0.234;-6915.0
499K
0.208;-7665.0
9Q(4T)
0.189;-7665.0
(9T)(4Q)
0.206;-6585.0
4T(9J)
0.185;-7830.0
4T(9K)
0.184;-7500.0
9(4JK)
0.236;-7335.0
4(9JK)
0.157;-7335.0
4J(9K)
0.244;-7335.0
4Q(9Q)
0.204;-6255.0
49QK
0.176;-8250.0
TJ(4T)
0.195;-6585.0
(4TJQ)
0.168;-7335.0
J(4TK)
0.184;-7170.0
(4T)(QK)
0.209;-5925.0
TT(4Q)
0.226;-6420.0
T(4JQ)
0.181;-7335.0
4(TJQ)
0.182;-7335.0
4T(JQ)
0.178;-7335.0
T(4QK)
0.204;-7005.0
TQ(4K)
0.225;-7005.0
JJ(4J)
0.206;-5175.0
(4JQK)
0.177;-6840.0
4JJJ
0.164;-6255.0
JQ(4Q)
0.213;-5925.0
4JQQ
0.225;-7005.0
4JKK
0.182;-6675.0
QQ(4K)
0.250;-5595.0
4KKK
0.213;-5265.0
55(59)
0.188;-7320.0
55(5K)
0.200;-6660.0
(56)(58)
0.162;-7320.0
5(56J)
0.170;-7905.0
5K(56)
0.204;-7575.0
56(59)
0.189;-8235.0
556J
0.116;-8985.0
57(57)
0.226;-7320.0
(57)(5T)
0.196;-6825.0
5(57K)
0.192;-7410.0
55(79)
0.173;-8070.0
57(5Q)
0.190;-7575.0
5(589)
0.196;-7905.0
5J(58)
0.181;-7575.0
58(59)
0.141;-7905.0
558J
0.154;-8655.0
59(59)
0.205;-6660.0
(59)(5Q)
0.189;-6165.0
559T
0.115;-8655.0
55(9K)
0.196;-7080.0
(5T)(5Q)
0.252;-6000.0
55TJ
0.141;-8325.0
5J(5J)
0.198;-6000.0
5J(5Q)
0.149;-6915.0
5(5QK)
0.190;-6585.0
5K(5K)
0.267;-5340.0
68(56)
0.156;-8235.0
(56)(6J)
0.176;-6660.0
7(567)
0.195;-8235.0
J(567)
0.205;-8655.0
78(56)
0.130;-9150.0
(56)(7J)
0.183;-7575.0
8(568)
0.157;-7905.0
Q(568)
0.171;-8325.0
(56)(8T)
0.156;-7575.0
8(56K)
0.160;-8160.0
(569Q)
0.173;-8160.0
9(56J)
0.193;-8325.0
9K(56)
0.153;-7995.0
TT(56)
0.185;-7245.0
(56)(TK)
0.157;-6750.0
J(56Q)
0.177;-7830.0
K(56Q)
0.180;-7500.0
66(57)
0.147;-8400.0
5669
0.132;-9150.0
56(6Q)
0.175;-7575.0
(57)(68)
0.183;-8070.0
6(57J)
0.163;-8655.0
6K(57)
0.197;-8325.0
(67)(5T)
0.164;-7740.0
5Q(67)
0.200;-8490.0
5678
0.129;-10230.0
567T
0.162;-9900.0
567Q
0.131;-9570.0
(58)(69)
0.150;-7740.0
6(58Q)
0.143;-8325.0
5(689)
0.148;-8820.0
(68)(5Q)
0.240;-7245.0
58(69)
0.174;-8820.0
58(6J)
0.172;-8490.0
58(6K)
0.139;-8160.0
6(59J)
0.176;-8325.0
6K(59)
0.160;-7995.0
(69)(5Q)
0.186;-7080.0
59(6T)
0.130;-8490.0
59(6Q)
0.178;-8160.0
6T(5T)
0.170;-7245.0
(5T)(6K)
0.150;-6750.0
5Q(6T)
0.217;-7995.0
56TJ
0.112;-9240.0
56TK
0.159;-8910.0
6K(5J)
0.175;-7665.0
56JJ
0.163;-7995.0
56JK
0.132;-8745.0
5(6QK)
0.147;-7500.0
6K(5K)
0.196;-6255.0
(57)(79)
0.229;-6660.0
7(57Q)
0.174;-7245.0
9(578)
0.158;-8655.0
K(578)
0.197;-7995.0
8(57J)
0.132;-8325.0
8K(57)
0.145;-7995.0
(579K)
0.197;-7830.0
9J(57)
0.190;-8160.0
(57TJ)
0.159;-7995.0
(57)(TJ)
0.251;-6915.0
J(57J)
0.190;-6750.0
JQ(57)
0.191;-7665.0
Q(57K)
0.151;-7335.0
5778
0.156;-8985.0
57(7J)
0.208;-7410.0
(58)(78)
0.170;-6660.0
7(58J)
0.160;-8325.0
7K(58)
0.173;-7995.0
(78)(5J)
0.185;-7245.0
5K(78)
0.154;-7995.0
57(8T)
0.169;-8490.0
57(8Q)
0.159;-8160.0
7(59T)
0.142;-8325.0
7Q(59)
0.167;-7995.0
(79)(5J)
0.252;-7080.0
5K(79)
0.216;-7830.0
57(9J)
0.168;-8160.0
57(9K)
0.149;-7830.0
(5T)(7Q)
0.175;-6750.0
5J(7T)
0.166;-7995.0
7T(5J)
0.162;-7995.0
7T(5K)
0.207;-7665.0
7Q(5J)
0.168;-7665.0
(7J)(5K)
0.178;-6420.0
7J(5K)
0.192;-7500.0
7K(5Q)
0.182;-7335.0
57(QK)
0.156;-7335.0
(58)(89)
0.202;-6330.0
8(58Q)
0.175;-6915.0
T(589)
0.160;-8160.0
9(58T)
0.151;-8160.0
9Q(58)
0.199;-7830.0
Q(58T)
0.172;-7665.0
(58)(TQ)
0.208;-6585.0
(58JK)
0.175;-7335.0
JK(58)
0.189;-7335.0
K(58K)
0.251;-5925.0
588T
0.157;-8325.0
58(8K)
0.183;-6750.0
(59)(8J)
0.165;-6915.0
59(89)
0.226;-7245.0
5(89Q)
0.203;-7830.0
58(9T)
0.174;-8160.0
58(9Q)
0.180;-7830.0
8(5TJ)
0.163;-7830.0
8K(5T)
0.151;-7500.0
(8T)(5K)
0.182;-6420.0
8T(5Q)
0.172;-7665.0
(5J)(8J)
0.204;-5505.0
5J(8J)
0.222;-6585.0
8J(5Q)
0.177;-7500.0
(5Q)(8Q)
0.220;-5175.0
5K(8Q)
0.198;-7170.0
5K(8K)
0.161;-5925.0
9J(59)
0.219;-6750.0
(59TJ)
0.139;-7665.0
(59)(TJ)
0.216;-6585.0
J(59J)
0.208;-6420.0
JQ(59)
0.148;-7335.0
Q(59K)
0.209;-7005.0
599T
0.124;-7995.0
59(9K)
0.193;-6420.0
(5T)(9Q)
0.184;-6420.0
5J(9T)
0.173;-7665.0
9T(5J)
0.165;-7665.0
9T(5K)
0.159;-7335.0
9Q(5J)
0.191;-7335.0
(9J)(5K)
0.197;-6090.0
9J(5K)
0.189;-7170.0
9K(5Q)
0.207;-7005.0
59(QK)
0.151;-7005.0
(5T)(TJ)
0.187;-5340.0
J(5TJ)
0.194;-6255.0
JQ(5T)
0.165;-7170.0
Q(5TK)
0.206;-6840.0
5TTJ
0.135;-7500.0
TJ(5J)
0.259;-6255.0
(TJ)(5Q)
0.214;-6090.0
5J(TQ)
0.175;-7170.0
TQ(5Q)
0.278;-5925.0
5TQQ
0.193;-7005.0
5TKK
0.225;-6675.0
Q(5JQ)
0.185;-5760.0
KK(5J)
0.264;-5430.0
(5Q)(JQ)
0.294;-4680.0
5K(JQ)
0.210;-6675.0
5K(JK)
0.232;-5430.0
5QQQ
0.175;-5595.0
KK(5K)
0.235;-4020.0
6669
0.154;-7905.0
666K
0.174;-7245.0
69(67)
0.200;-7740.0
(67)(6Q)
0.175;-6165.0
6678
0.147;-8985.0
66(7J)
0.214;-7410.0
(68)(68)
0.258;-5580.0
6(68J)
0.164;-7245.0
6K(68)
0.186;-6915.0
68(6J)
0.201;-7245.0
668K
0.169;-7995.0
6J(69)
0.143;-7080.0
69(6T)
0.162;-7245.0
669Q
0.171;-7995.0
6J(6T)
0.227;-6915.0
6T(6J)
0.161;-6915.0
66TK
0.178;-7665.0
6K(6J)
0.212;-6420.0
(6Q)(6Q)
0.283;-4260.0
66QK
0.138;-7335.0
7(679)
0.151;-7575.0
7J(67)
0.198;-7245.0
(6789)
0.167;-8490.0
(678K)
0.191;-7830.0
8T(67)
0.219;-8325.0
(67)(8K)
0.196;-6750.0
Q(679)
0.157;-7830.0
(67)(9J)
0.201;-6915.0
T(67T)
0.229;-6915.0
T(67J)
0.149;-7830.0
TK(67)
0.152;-7500.0
(67)(JQ)
0.225;-6420.0
QQ(67)
0.176;-6255.0
67(78)
0.234;-7740.0
77(6J)
0.200;-7245.0
677K
0.175;-7995.0
7T(68)
0.185;-8325.0
(68)(7K)
0.243;-6750.0
6T(78)
0.199;-8325.0
6(78K)
0.187;-7830.0
68(7T)
0.201;-8325.0
68(7Q)
0.165;-7995.0
79(69)
0.223;-7245.0
(69)(7Q)
0.247;-6750.0
6T(79)
0.194;-8160.0
6(79K)
0.182;-7665.0
69(7J)
0.172;-7995.0
69(7K)
0.209;-7665.0
7(6TQ)
0.181;-7665.0
6(7TJ)
0.191;-7830.0
67TT
0.193;-7995.0
67TQ
0.199;-8745.0
(6J)(7Q)
0.195;-6420.0
6Q(7J)
0.159;-7500.0
67JQ
0.206;-8580.0
(6Q)(7K)
0.194;-6090.0
6Q(7K)
0.201;-7170.0
8(689)
0.199;-7245.0
8J(68)
0.178;-6915.0
(689T)
0.217;-7995.0
99(68)
0.248;-7080.0
(68)(9Q)
0.180;-6585.0
(68TQ)
0.203;-7500.0
T(68Q)
0.191;-7500.0
Q(68J)
0.173;-7335.0
(68)(JK)
0.262;-6090.0
QK(68)
0.218;-7005.0
68(8T)
0.190;-7080.0
88(6K)
0.200;-6585.0
8(69J)
0.191;-7830.0
8K(69)
0.188;-7500.0
(89)(6Q)
0.212;-6585.0
69(8T)
0.175;-7995.0
69(8Q)
0.202;-7665.0
8T(6T)
0.208;-6750.0
(6T)(8K)
0.236;-6255.0
6Q(8T)
0.155;-7500.0
68TJ
0.145;-8745.0
68TK
0.204;-8415.0
8K(6J)
0.167;-7170.0
68JJ
0.176;-7500.0
68JK
0.179;-8250.0
6(8QK)
0.184;-7005.0
8K(6K)
0.248;-5760.0
(69)(9J)
0.205;-5505.0
T(69T)
0.224;-6585.0
T(69J)
0.143;-7500.0
TK(69)
0.197;-7170.0
(69)(JQ)
0.239;-6090.0
QQ(69)
0.223;-5925.0
69(9T)
0.203;-6750.0
99(6K)
0.237;-6255.0
9(6TQ)
0.225;-7335.0
6(9TJ)
0.195;-7500.0
69TT
0.179;-7665.0
69TQ
0.207;-8415.0
(6J)(9Q)
0.187;-6090.0
6Q(9J)
0.143;-7170.0
69JQ
0.173;-8250.0
(6Q)(9K)
0.219;-5760.0
6Q(9K)
0.211;-6840.0
T(6TJ)
0.244;-6255.0
TK(6T)
0.210;-5925.0
(6T)(JQ)
0.190;-5925.0
QQ(6T)
0.255;-5760.0
6T(TJ)
0.219;-6255.0
(6J)(TJ)
0.233;-5010.0
6J(TJ)
0.222;-6090.0
TJ(6Q)
0.200;-7005.0
(6Q)(TQ)
0.227;-4680.0
6K(TQ)
0.190;-6675.0
6K(TK)
0.233;-5430.0
JK(6J)
0.281;-5595.0
K(6JK)
0.219;-5265.0
6JJK
0.200;-6675.0
6(JQK)
0.235;-6510.0
JK(6K)
0.264;-5265.0
KK(6Q)
0.201;-5100.0
6QKK
0.174;-6180.0
77(7T)
0.218;-6165.0
(78)(78)
0.194;-5250.0
7(78J)
0.215;-6915.0
7K(78)
0.199;-6585.0
78(7J)
0.192;-6915.0
778K
0.221;-7665.0
7J(79)
0.192;-6750.0
79(7T)
0.159;-6915.0
779Q
0.167;-7665.0
7J(7T)
0.174;-6585.0
7T(7J)
0.205;-6585.0
77TK
0.182;-7335.0
7K(7J)
0.236;-6090.0
(7Q)(7Q)
0.215;-3930.0
77QK
0.205;-7005.0
8(78T)
0.214;-6915.0
8Q(78)
0.213;-6585.0
J(789)
0.226;-7665.0
9T(78)
0.168;-7830.0
(78)(9K)
0.188;-6255.0
K(78T)
0.214;-7170.0
T(78K)
0.204;-7170.0
JJ(78)
0.221;-6255.0
(78QK)
0.204;-6840.0
7888
0.171;-7245.0
78(8J)
0.224;-6750.0
(79)(89)
0.233;-5835.0
8(79Q)
0.158;-7500.0
7(89T)
0.173;-7830.0
(89)(7K)
0.221;-6255.0
89(7J)
0.192;-7665.0
89(7K)
0.164;-7335.0
8J(7T)
0.181;-7500.0
(8T)(7J)
0.224;-6420.0
7K(8T)
0.174;-7170.0
78(TQ)
0.206;-7335.0
8(7JQ)
0.163;-7170.0
7(8JQ)
0.187;-7170.0
78(JQ)
0.183;-7170.0
8(7QK)
0.160;-6840.0
8Q(7K)
0.179;-6840.0
99(79)
0.177;-5670.0
(79)(9Q)
0.223;-5175.0
(79TQ)
0.171;-7170.0
T(79Q)
0.185;-7170.0
Q(79J)
0.223;-7005.0
(79)(JK)
0.262;-5760.0
QK(79)
0.174;-6675.0
79(9J)
0.184;-6420.0
(7T)(9T)
0.211;-5340.0
9(7TK)
0.162;-7005.0
7(9TQ)
0.203;-7170.0
79(TJ)
0.158;-7335.0
79(TK)
0.153;-7005.0
(7J)(9K)
0.214;-5760.0
7K(9J)
0.202;-6840.0
79(JK)
0.239;-6840.0
(9Q)(7K)
0.223;-5595.0
(7K)(9K)
0.294;-4350.0
T(7TQ)
0.231;-5925.0
Q(7TJ)
0.213;-6840.0
(7T)(JK)
0.227;-5595.0
QK(7T)
0.271;-6510.0
7T(TQ)
0.184;-5925.0
(7J)(TQ)
0.211;-5760.0
7Q(TJ)
0.200;-6840.0
7TJQ
0.172;-7920.0
(7Q)(TK)
0.240;-5430.0
7Q(TK)
0.228;-6510.0
J(7JQ)
0.250;-5595.0
K(7JQ)
0.231;-6345.0
JJ(7Q)
0.221;-5595.0
J(7QK)
0.191;-6345.0
JQ(7K)
0.203;-6345.0
QQ(7Q)
0.235;-4185.0
7Q(QK)
0.254;-5100.0
8888
0.250;-6000.0
888Q
0.189;-6420.0
8(89J)
0.173;-6420.0
8K(89)
0.193;-6090.0
89(8Q)
0.212;-6255.0
8(8TJ)
0.195;-6255.0
8K(8T)
0.251;-5925.0
8T(8K)
0.194;-5925.0
8(8JK)
0.223;-5760.0
88(JK)
0.206;-5760.0
8Q(8K)
0.222;-5595.0
(89)(9T)
0.242;-5340.0
9(89K)
0.244;-5925.0
(89TK)
0.194;-6840.0
TQ(89)
0.173;-7005.0
K(89J)
0.183;-6675.0
Q(89Q)
0.184;-5595.0
KK(89)
0.186;-5265.0
99(8Q)
0.189;-6090.0
9(8TJ)
0.209;-7170.0
9K(8T)
0.201;-6840.0
(9T)(8K)
0.229;-5760.0
9T(8Q)
0.191;-7005.0
(8J)(9J)
0.238;-4845.0
8J(9J)
0.202;-5925.0
9J(8Q)
0.257;-6840.0
(8Q)(9Q)
0.292;-4515.0
8K(9Q)
0.191;-6510.0
8K(9K)
0.213;-5265.0
TQ(8T)
0.231;-5760.0
K(8TJ)
0.209;-6510.0
Q(8TQ)
0.263;-5430.0
KK(8T)
0.217;-5100.0
