AAAA
0.329;-4860.0
5AAA
0.235;-17257.5
9AAA
0.294;-14067.5
KAAA
0.287;-10877.5
4A(2A)
0.141;-27625.0
(2A)(7A)
0.272;-20012.5
A(2TA)
0.264;-22840.0
QA(2A)
0.201;-21245.0
2A(4A)
0.165;-27625.0
26AA
0.162;-31250.0
AA(29)
0.198;-23637.5
2A(QA)
0.245;-21245.0
A(34A)
0.174;-26827.5
6A(3A)
0.187;-25232.5
(3A)(9A)
0.206;-17620.0
A(3QA)
0.193;-20447.5
AA(34)
0.199;-26827.5
3A(7A)
0.193;-24435.0
39AA
0.193;-28060.0
AA(3Q)
0.197;-20447.5
(4A)(5A)
0.202;-20012.5
A(48A)
0.208;-22840.0
TA(4A)
0.244;-21245.0
(4A)(KA)
0.206;-13632.5
46AA
0.162;-29655.0
AA(49)
0.208;-22042.5
4A(QA)
0.252;-19650.0
A(56A)
0.158;-23637.5
8A(5A)
0.199;-22042.5
(5A)(JA)
0.260;-14430.0
55AA
0.222;-24435.0
AA(58)
0.216;-22042.5
5A(JA)
0.204;-19650.0
5KAA
0.243;-23275.0
8A(6A)
0.200;-21245.0
(6A)(JA)
0.206;-13632.5
66AA
0.223;-22840.0
AA(69)
0.183;-20447.5
6A(QA)
0.255;-18055.0
A(78A)
0.282;-20447.5
TA(7A)
0.278;-18852.5
(7A)(KA)
0.260;-11240.0
79AA
0.147;-24870.0
AA(7Q)
0.297;-17257.5
(8A)(9A)
0.202;-13632.5
A(8QA)
0.285;-16460.0
AA(89)
0.275;-18852.5
8A(QA)
0.264;-16460.0
A(9TA)
0.224;-17257.5
QA(9A)
0.239;-15662.5
9A(JA)
0.236;-16460.0
9KAA
0.238;-20085.0
QA(TA)
0.187;-14865.0
TA(QA)
0.255;-14865.0
A(JQA)
0.268;-14067.5
AA(JQ)
0.272;-14067.5
(QA)(KA)
0.242;-7252.5
KKAA
0.270;-11675.0
2(25A)
0.164;-36397.5
27(2A)
0.154;-34802.5
(2T)(2A)
0.195;-27190.0
2(2KA)
0.224;-30017.5
(236A)
0.125;-40022.5
(23TA)
0.136;-36832.5
33(2A)
0.148;-37195.0
(36)(2A)
0.170;-34802.5
3(29A)
0.124;-37630.0
3J(2A)
0.129;-36035.0
(245A)
0.153;-40022.5
(249A)
0.163;-36832.5
(24KA)
0.144;-33642.5
46(2A)
0.176;-39225.0
(49)(2A)
0.204;-31612.5
4(2QA)
0.150;-34440.0
6(25A)
0.121;-38427.5
T(25A)
0.153;-35237.5
5(26A)
0.115;-38427.5
58(2A)
0.194;-36832.5
(5J)(2A)
0.198;-29220.0
6(26A)
0.154;-32410.0
T(26A)
0.157;-34440.0
6(27A)
0.143;-36832.5
69(2A)
0.140;-35237.5
(6Q)(2A)
0.202;-27625.0
(279A)
0.120;-34440.0
(27KA)
0.186;-31250.0
79(2A)
0.133;-34440.0
(7Q)(2A)
0.166;-26827.5
(28TA)
0.162;-32845.0
88(2A)
0.184;-29220.0
(8J)(2A)
0.207;-26827.5
9(29A)
0.199;-27625.0
K(29A)
0.193;-29655.0
9(2QA)
0.168;-30452.5
J(2TA)
0.195;-30452.5
TJ(2A)
0.163;-30452.5
(2JQA)
0.176;-28857.5
J(2KA)
0.201;-28060.0
(QK)(2A)
0.201;-22042.5
22(4A)
0.177;-37195.0
226A
0.143;-40820.0
2A(29)
0.155;-33207.5
22(QA)
0.131;-30815.0
2(34A)
0.126;-41617.5
26(3A)
0.164;-40022.5
(29)(3A)
0.175;-32410.0
2(3QA)
0.182;-35237.5
A(234)
0.119;-41617.5
(23)(7A)
0.158;-34005.0
9A(23)
0.196;-37630.0
A(23Q)
0.129;-35237.5
2A(34)
0.129;-41617.5
2A(36)
0.140;-40022.5
2A(38)
0.138;-38427.5
2A(3T)
0.146;-36832.5
2A(3Q)
0.162;-35237.5
2(45A)
0.142;-40022.5
27(4A)
0.129;-38427.5
(2T)(4A)
0.140;-30815.0
2(4KA)
0.171;-33642.5
A(246)
0.138;-39225.0
(24)(9A)
0.194;-31612.5
JA(24)
0.146;-35237.5
24(5A)
0.126;-40022.5
24(7A)
0.157;-38427.5
24(9A)
0.133;-36832.5
24(JA)
0.142;-35237.5
24(KA)
0.168;-33642.5
26(5A)
0.142;-38427.5
(29)(5A)
0.171;-30815.0
2(5QA)
0.170;-33642.5
A(256)
0.120;-38427.5
(25)(9A)
0.163;-30815.0
JA(25)
0.156;-34440.0
25(6A)
0.125;-38427.5
25(8A)
0.154;-36832.5
25(TA)
0.158;-35237.5
25(QA)
0.171;-33642.5
(26)(6A)
0.173;-27190.0
2(69A)
0.161;-35237.5
2J(6A)
0.186;-33642.5
(26)(7A)
0.170;-31612.5
9A(26)
0.158;-35237.5
A(26Q)
0.163;-32845.0
2A(67)
0.186;-36832.5
2A(69)
0.120;-35237.5
2A(6J)
0.149;-33642.5
2A(6K)
0.184;-32047.5
(29)(7A)
0.175;-29220.0
2(7QA)
0.208;-32047.5
A(278)
0.191;-35237.5
(27)(JA)
0.165;-27625.0
KA(27)
0.183;-31250.0
2A(79)
0.136;-34440.0
2A(7J)
0.156;-32845.0
2A(7K)
0.133;-31250.0
(2T)(8A)
0.157;-27625.0
2(8KA)
0.172;-30452.5
A(28T)
0.138;-32845.0
(28)(KA)
0.171;-25232.5
28(TA)
0.131;-32845.0
28(QA)
0.126;-31250.0
(29)(9A)
0.219;-22405.0
2(9QA)
0.147;-30452.5
A(29T)
0.196;-32047.5
(29)(KA)
0.200;-24435.0
29(JA)
0.138;-31250.0
29(KA)
0.201;-29655.0
2J(TA)
0.145;-30452.5
(2T)(JA)
0.161;-25232.5
KA(2T)
0.206;-28857.5
2A(TQ)
0.207;-29655.0
2(JQA)
0.198;-28857.5
A(2JQ)
0.199;-28857.5
2A(JQ)
0.214;-28857.5
2(QKA)
0.198;-27262.5
2Q(KA)
0.152;-27262.5
33(3A)
0.180;-31177.5
(36)(3A)
0.229;-28785.0
3(39A)
0.200;-31612.5
3J(3A)
0.182;-30017.5
(345A)
0.173;-39225.0
(349A)
0.146;-36035.0
(34KA)
0.160;-32845.0
46(3A)
0.130;-38427.5
(49)(3A)
0.133;-30815.0
4(3QA)
0.169;-33642.5
6(35A)
0.174;-37630.0
T(35A)
0.195;-34440.0
5(36A)
0.150;-37630.0
58(3A)
0.118;-36035.0
(5J)(3A)
0.152;-28422.5
6(36A)
0.164;-31612.5
T(36A)
0.157;-33642.5
6(37A)
0.119;-36035.0
69(3A)
0.155;-34440.0
(6Q)(3A)
0.236;-26827.5
(379A)
0.143;-33642.5
(37KA)
0.169;-30452.5
79(3A)
0.168;-33642.5
(7Q)(3A)
0.168;-26030.0
(38TA)
0.215;-32047.5
88(3A)
0.201;-28422.5
(8J)(3A)
0.181;-26030.0
9(39A)
0.214;-26827.5
K(39A)
0.180;-28857.5
9(3QA)
0.175;-29655.0
J(3TA)
0.170;-29655.0
TJ(3A)
0.182;-29655.0
(3JQA)
0.176;-28060.0
J(3KA)
0.182;-27262.5
(QK)(3A)
0.220;-21245.0
33(5A)
0.152;-34802.5
337A
0.183;-38427.5
3A(3T)
0.165;-30815.0
33(KA)
0.202;-28422.5
3(46A)
0.160;-38427.5
38(4A)
0.188;-36832.5
(3J)(4A)
0.211;-29220.0
4A(34)
0.137;-34802.5
A(347)
0.108;-37630.0
(34)(TA)
0.229;-30017.5
QA(34)
0.137;-33642.5
345A
0.122;-44445.0
347A
0.126;-42850.0
349A
0.104;-41255.0
34JA
0.121;-39660.0
34KA
0.125;-38065.0
37(5A)
0.138;-36832.5
(3T)(5A)
0.211;-29220.0
3(5KA)
0.191;-32047.5
A(357)
0.132;-36832.5
(35)(TA)
0.211;-29220.0
QA(35)
0.167;-32845.0
356A
0.123;-42850.0
358A
0.142;-41255.0
35TA
0.160;-39660.0
35QA
0.142;-38065.0
(37)(6A)
0.218;-30815.0
3(6TA)
0.192;-33642.5
3Q(6A)
0.161;-32047.5
(36)(8A)
0.139;-30017.5
TA(36)
0.170;-33642.5
A(36K)
0.137;-31250.0
6A(38)
0.167;-35237.5
6A(3T)
0.201;-33642.5
6A(3Q)
0.204;-32047.5
37(7A)
0.228;-30017.5
(3T)(7A)
0.208;-27625.0
3(7KA)
0.214;-30452.5
A(379)
0.194;-33642.5
(37)(QA)
0.246;-26030.0
7A(38)
0.149;-34440.0
7A(3T)
0.134;-32845.0
7A(3Q)
0.126;-31250.0
38(8A)
0.181;-28422.5
(3J)(8A)
0.225;-26030.0
8A(38)
0.181;-28422.5
A(38J)
0.154;-31250.0
388A
0.130;-33642.5
38TA
0.112;-37267.5
38QA
0.132;-35672.5
(3T)(9A)
0.167;-26030.0
3(9KA)
0.198;-28857.5
A(39J)
0.178;-30452.5
399A
0.143;-32047.5
39JA
0.170;-35672.5
39KA
0.184;-34077.5
3Q(TA)
0.156;-28857.5
(3T)(QA)
0.242;-23637.5
TA(3J)
0.203;-29655.0
TA(3K)
0.177;-28060.0
3(JKA)
0.217;-27262.5
A(3JK)
0.185;-27262.5
JA(3K)
0.186;-27262.5
QA(3Q)
0.220;-22042.5
3QKA
0.159;-31685.0
45(4A)
0.174;-33207.5
(48)(4A)
0.151;-25595.0
4(4JA)
0.195;-28422.5
4K(4A)
0.162;-26827.5
(459A)
0.151;-34440.0
(45KA)
0.160;-31250.0
57(4A)
0.163;-36035.0
(5T)(4A)
0.145;-28422.5
5(4KA)
0.164;-31250.0
(469A)
0.171;-33642.5
(46KA)
0.181;-30452.5
68(4A)
0.190;-34440.0
(6J)(4A)
0.181;-26827.5
7(47A)
0.211;-29220.0
J(47A)
0.197;-31250.0
78(4A)
0.154;-33642.5
(7J)(4A)
0.206;-26030.0
8(48A)
0.159;-27625.0
Q(48A)
0.177;-29655.0
(8T)(4A)
0.198;-26030.0
8(4KA)
0.202;-28857.5
(49QA)
0.146;-28857.5
9(4JA)
0.187;-29655.0
9K(4A)
0.192;-28060.0
TT(4A)
0.182;-24435.0
(TK)(4A)
0.242;-22042.5
J(4QA)
0.137;-27262.5
K(4QA)
0.215;-25667.5
44(5A)
0.158;-33207.5
447A
0.136;-36832.5
4A(4T)
0.161;-29220.0
44(KA)
0.163;-26827.5
4(57A)
0.139;-36035.0
49(5A)
0.195;-34440.0
(4Q)(5A)
0.206;-26827.5
6A(45)
0.187;-36832.5
A(459)
0.145;-34440.0
(45)(QA)
0.160;-26827.5
5A(46)
0.170;-36832.5
5A(48)
0.147;-35237.5
5A(4T)
0.135;-33642.5
5A(4Q)
0.169;-32047.5
46(6A)
0.208;-30815.0
(49)(6A)
0.155;-28422.5
4(6QA)
0.135;-31250.0
A(467)
0.121;-35237.5
(46)(TA)
0.179;-27625.0
QA(46)
0.176;-31250.0
467A
0.159;-40457.5
469A
0.139;-38862.5
46JA
0.181;-37267.5
46KA
0.153;-35672.5
49(7A)
0.162;-32845.0
(4Q)(7A)
0.173;-25232.5
8A(47)
0.144;-33642.5
A(47J)
0.160;-31250.0
477A
0.119;-34440.0
479A
0.127;-38065.0
47JA
0.148;-36470.0
47KA
0.193;-34875.0
4T(8A)
0.218;-31250.0
(4K)(8A)
0.207;-23637.5
TA(48)
0.174;-31250.0
A(48K)
0.174;-28857.5
8A(4T)
0.221;-31250.0
8A(4Q)
0.186;-29655.0
49(9A)
0.192;-26030.0
(4Q)(9A)
0.226;-23637.5
TA(49)
0.177;-30452.5
A(49K)
0.181;-28060.0
9A(4J)
0.181;-29655.0
9A(4K)
0.199;-28060.0
4(TQA)
0.182;-28060.0
A(4TJ)
0.165;-28857.5
4TTA
0.178;-29655.0
4TQA
0.182;-33280.0
(4Q)(JA)
0.221;-22042.5
QA(4J)
0.150;-27262.5
4JQA
0.135;-32482.5
(4K)(QA)
0.260;-20447.5
QA(4K)
0.206;-25667.5
5(56A)
0.156;-30815.0
58(5A)
0.191;-29220.0
(5J)(5A)
0.172;-21607.5
6(56A)
0.159;-30017.5
T(56A)
0.139;-32047.5
6(57A)
0.156;-34440.0
69(5A)
0.167;-32845.0
(6Q)(5A)
0.161;-25232.5
(579A)
0.178;-32047.5
(57KA)
0.145;-28857.5
79(5A)
0.143;-32047.5
(7Q)(5A)
0.178;-24435.0
(58TA)
0.138;-30452.5
88(5A)
0.233;-26827.5
(8J)(5A)
0.262;-24435.0
9(59A)
0.214;-25232.5
K(59A)
0.165;-27262.5
9(5QA)
0.195;-28060.0
J(5TA)
0.160;-28060.0
TJ(5A)
0.142;-28060.0
(5JQA)
0.196;-26465.0
J(5KA)
0.233;-25667.5
(QK)(5A)
0.218;-19650.0
55(7A)
0.177;-30017.5
559A
0.145;-33642.5
5A(5Q)
0.175;-26030.0
(57)(6A)
0.178;-29220.0
5(6TA)
0.181;-32047.5
5Q(6A)
0.154;-30452.5
(56)(8A)
0.186;-28422.5
TA(56)
0.195;-32047.5
A(56K)
0.150;-29655.0
6A(58)
0.152;-33642.5
6A(5T)
0.129;-32047.5
6A(5Q)
0.208;-30452.5
57(7A)
0.166;-28422.5
(5T)(7A)
0.242;-26030.0
5(7KA)
0.168;-28857.5
A(579)
0.196;-32047.5
(57)(QA)
0.167;-24435.0
7A(58)
0.178;-32845.0
7A(5T)
0.144;-31250.0
7A(5Q)
0.188;-29655.0
58(8A)
0.209;-26827.5
(5J)(8A)
0.204;-24435.0
8A(58)
0.173;-26827.5
A(58J)
0.178;-29655.0
588A
0.180;-32047.5
58TA
0.191;-35672.5
58QA
0.160;-34077.5
(5T)(9A)
0.244;-24435.0
5(9KA)
0.166;-27262.5
A(59J)
0.173;-28857.5
599A
0.152;-30452.5
59JA
0.142;-34077.5
59KA
0.202;-32482.5
5Q(TA)
0.202;-27262.5
(5T)(QA)
0.219;-22042.5
TA(5J)
0.150;-28060.0
TA(5K)
0.169;-26465.0
5(JKA)
0.189;-25667.5
A(5JK)
0.194;-25667.5
JA(5K)
0.205;-25667.5
QA(5Q)
0.261;-20447.5
5QKA
0.145;-30090.0
67(6A)
0.170;-28422.5
(6T)(6A)
0.237;-20810.0
6(6KA)
0.191;-23637.5
(67TA)
0.143;-30452.5
77(6A)
0.183;-27625.0
(7T)(6A)
0.215;-25232.5
7(6KA)
0.164;-28060.0
(68JA)
0.162;-28857.5
(89)(6A)
0.215;-25232.5
8(6QA)
0.177;-28060.0
T(69A)
0.148;-28857.5
9(6TA)
0.181;-28857.5
9Q(6A)
0.238;-27262.5
Q(6TA)
0.168;-26465.0
(TQ)(6A)
0.211;-21245.0
(6JKA)
0.181;-24870.0
JK(6A)
0.182;-24870.0
K(6KA)
0.186;-18055.0
668A
0.208;-32845.0
6A(6J)
0.245;-25232.5
(67)(7A)
0.201;-22405.0
6(7TA)
0.130;-30452.5
6Q(7A)
0.172;-28857.5
(67)(9A)
0.155;-26030.0
JA(67)
0.209;-29655.0
67(8A)
0.162;-32047.5
67(TA)
0.149;-30452.5
67(QA)
0.152;-28857.5
(68)(8A)
0.228;-20810.0
6(8JA)
0.167;-28857.5
6K(8A)
0.206;-27262.5
(68)(JA)
0.154;-23637.5
KA(68)
0.158;-27262.5
6A(8T)
0.175;-29655.0
6A(8Q)
0.195;-28060.0
6(9TA)
0.197;-28857.5
6Q(9A)
0.150;-27262.5
(69)(JA)
0.215;-22840.0
KA(69)
0.143;-26465.0
6A(9J)
0.160;-28060.0
6A(9K)
0.181;-26465.0
(6Q)(TA)
0.239;-21245.0
JA(6T)
0.209;-27262.5
6T(JA)
0.183;-27262.5
6T(KA)
0.168;-25667.5
6Q(JA)
0.239;-25667.5
(6J)(KA)
0.167;-19650.0
6J(KA)
0.237;-24870.0
6K(QA)
0.217;-24072.5
6A(QK)
0.191;-24072.5
(78)(7A)
0.196;-20810.0
7(7JA)
0.234;-23637.5
7K(7A)
0.270;-22042.5
(78QA)
0.153;-27262.5
8(7TA)
0.180;-28857.5
8Q(7A)
0.195;-27262.5
J(79A)
0.133;-27262.5
9T(7A)
0.185;-28060.0
(9K)(7A)
0.212;-20447.5
K(7TA)
0.231;-24870.0
T(7KA)
0.218;-24870.0
JJ(7A)
0.221;-20447.5
(7QKA)
0.185;-23275.0
777A
0.189;-26827.5
7A(7T)
0.203;-24435.0
77(KA)
0.190;-22042.5
7(8TA)
0.170;-28857.5
7Q(8A)
0.194;-27262.5
(78)(TA)
0.151;-23637.5
QA(78)
0.207;-27262.5
789A
0.162;-34875.0
78JA
0.188;-33280.0
78KA
0.163;-31685.0
7J(9A)
0.224;-27262.5
(79)(TA)
0.216;-22840.0
QA(79)
0.186;-26465.0
79TA
0.171;-33280.0
79QA
0.130;-31685.0
(7J)(TA)
0.253;-21245.0
TA(7T)
0.207;-22042.5
A(7TK)
0.211;-24870.0
TA(7Q)
0.185;-25667.5
7J(JA)
0.268;-20447.5
(7J)(QA)
0.222;-19650.0
JA(7Q)
0.249;-24870.0
7Q(QA)
0.187;-18852.5
7QQA
0.194;-24072.5
7KKA
0.159;-22477.5
8(8JA)
0.183;-22042.5
8K(8A)
0.200;-20447.5
(89KA)
0.190;-24870.0
9J(8A)
0.223;-26465.0
(8TJA)
0.196;-25667.5
(TJ)(8A)
0.227;-20447.5
J(8JA)
0.209;-19650.0
JQ(8A)
0.213;-24072.5
Q(8KA)
0.243;-22477.5
889A
0.167;-28857.5
8A(8Q)
0.183;-21245.0
(8T)(9A)
0.177;-22042.5
8(9KA)
0.216;-24870.0
A(89J)
0.209;-26465.0
899A
0.202;-28060.0
89JA
0.192;-31685.0
89KA
0.190;-30090.0
8Q(TA)
0.227;-24870.0
(8T)(QA)
0.211;-19650.0
TA(8J)
0.251;-25667.5
TA(8K)
0.205;-24072.5
8(JKA)
0.229;-23275.0
A(8JK)
0.214;-23275.0
JA(8K)
0.215;-23275.0
QA(8Q)
0.232;-18055.0
8QKA
0.179;-27697.5
9T(9A)
0.218;-21245.0
(9K)(9A)
0.293;-13632.5
K(9TA)
0.179;-23275.0
T(9KA)
0.164;-23275.0
JJ(9A)
0.284;-18852.5
(9QKA)
0.193;-21680.0
999A
0.234;-22042.5
9A(9Q)
0.208;-19650.0
(9J)(TA)
0.219;-19650.0
TA(9T)
0.247;-20447.5
A(9TK)
0.214;-23275.0
TA(9Q)
0.195;-24072.5
9J(JA)
0.216;-18852.5
(9J)(QA)
0.229;-18055.0
JA(9Q)
0.245;-23275.0
9Q(QA)
0.188;-17257.5
9QQA
0.213;-22477.5
9KKA
0.223;-20882.5
T(TKA)
0.211;-17257.5
JJ(TA)
0.288;-18055.0
(TQKA)
0.235;-20882.5
TTTA
0.256;-19650.0
TA(TK)
0.221;-17257.5
(TK)(JA)
0.269;-16460.0
KA(TJ)
0.207;-21680.0
TA(JK)
0.225;-21680.0
(TQ)(KA)
0.274;-15662.5
(TK)(KA)
0.308;-9645.0
J(JKA)
0.276;-15662.5
(QK)(JA)
0.246;-14865.0
JJ(KA)
0.257;-15662.5
QA(JQ)
0.222;-15662.5
JQKA
0.150;-25305.0
QK(QA)
0.293;-14067.5
QK(KA)
0.237;-13270.0
22(24)
0.149;-41545.0
22(28)
0.106;-38355.0
22(2Q)
0.153;-35165.0
24(23)
0.119;-45967.5
(23)(27)
0.142;-38355.0
2(23T)
0.107;-41182.5
2Q(23)
0.133;-39587.5
23(25)
0.119;-45170.0
2237
0.131;-48795.0
22(3T)
0.124;-41182.5
23(2K)
0.126;-38790.0
2(246)
0.149;-43575.0
28(24)
0.168;-41980.0
(24)(2J)
0.184;-34367.5
2244
0.138;-45170.0
22(47)
0.111;-42777.5
24(2T)
0.123;-40385.0
224Q
0.116;-44010.0
26(25)
0.135;-42777.5
(25)(29)
0.146;-35165.0
2(25Q)
0.129;-37992.5
22(56)
0.117;-42777.5
25(29)
0.128;-40385.0
225J
0.164;-44010.0
26(26)
0.133;-36760.0
(26)(29)
0.140;-34367.5
2(26Q)
0.192;-37195.0
22(67)
0.131;-41182.5
26(2T)
0.124;-38790.0
226Q
0.103;-42415.0
28(27)
0.140;-39587.5
(27)(2J)
0.152;-31975.0
2277
0.138;-40385.0
22(7T)
0.106;-37992.5
27(2K)
0.130;-35600.0
2(28T)
0.173;-37195.0
2Q(28)
0.160;-35600.0
28(2T)
0.125;-37195.0
228Q
0.128;-40820.0
2T(29)
0.183;-36397.5
(29)(2K)
0.202;-28785.0
229J
0.125;-40820.0
2T(2T)
0.152;-30380.0
(2T)(2K)
0.167;-27987.5
22TQ
0.130;-39225.0
2Q(2J)
0.146;-33207.5
2J(2K)
0.181;-32410.0
22QQ
0.210;-32410.0
3(234)
0.139;-45170.0
36(23)
0.116;-43575.0
(23)(39)
0.143;-35962.5
3(23Q)
0.133;-38790.0
5(234)
0.107;-48795.0
9(234)
0.121;-45605.0
K(234)
0.165;-42415.0
4(237)
0.111;-47200.0
49(23)
0.147;-45605.0
(23)(4Q)
0.124;-37992.5
(2357)
0.129;-46402.5
(235J)
0.126;-43212.5
(23)(56)
0.129;-41980.0
5(239)
0.119;-44807.5
5J(23)
0.117;-43212.5
(2367)
0.132;-45605.0
(236J)
0.125;-42415.0
(23)(67)
0.160;-40385.0
6(23T)
0.116;-43212.5
6Q(23)
0.108;-41617.5
9(237)
0.155;-43212.5
K(237)
0.122;-40022.5
7(23T)
0.108;-42415.0
7Q(23)
0.119;-40820.0
T(238)
0.131;-41617.5
8(239)
0.125;-42415.0
8J(23)
0.131;-40820.0
(239T)
0.150;-40820.0
99(23)
0.131;-36397.5
(23)(9Q)
0.190;-34005.0
(23TQ)
0.142;-38427.5
T(23Q)
0.167;-38427.5
Q(23J)
0.120;-37630.0
(23)(JK)
0.183;-31612.5
QK(23)
0.175;-36035.0
23(35)
0.118;-44372.5
33(28)
0.177;-41980.0
233T
0.126;-45605.0
23(3K)
0.160;-37992.5
(24)(36)
0.138;-42777.5
3(249)
0.108;-45605.0
3J(24)
0.121;-44010.0
(34)(25)
0.164;-43575.0
27(34)
0.113;-47200.0
2(34T)
0.127;-44807.5
(34)(2K)
0.135;-37195.0
34(26)
0.113;-47997.5
34(28)
0.155;-46402.5
34(2T)
0.109;-44807.5
34(2Q)
0.111;-43212.5
(25)(35)
0.185;-37557.5
3(258)
0.102;-45605.0
3T(25)
0.103;-44010.0
(25)(3K)
0.188;-36397.5
27(35)
0.147;-46402.5
2(35T)
0.121;-44010.0
(35)(2K)
0.183;-36397.5
35(27)
0.133;-46402.5
35(29)
0.122;-44807.5
35(2J)
0.119;-43212.5
35(2K)
0.132;-41617.5
37(26)
0.140;-45605.0
(26)(3T)
0.147;-37992.5
3(26K)
0.150;-40820.0
2(368)
0.103;-44807.5
(36)(2J)
0.146;-37195.0
2K(36)
0.123;-40820.0
23(68)
0.128;-44807.5
23(6T)
0.127;-43212.5
23(6Q)
0.116;-41617.5
3(278)
0.134;-44010.0
3T(27)
0.108;-42415.0
(27)(3K)
0.163;-34802.5
29(37)
0.101;-43212.5
2(37Q)
0.164;-40820.0
23(78)
0.117;-44010.0
23(7T)
0.104;-42415.0
23(7Q)
0.146;-40820.0
3(289)
0.148;-42415.0
3J(28)
0.113;-40820.0
(38)(29)
0.165;-37195.0
2J(38)
0.131;-40820.0
38(29)
0.112;-42415.0
38(2J)
0.113;-40820.0
38(2K)
0.139;-39225.0
3T(29)
0.162;-40820.0
(29)(3K)
0.186;-33207.5
2J(39)
0.149;-40022.5
39(2T)
0.162;-40820.0
39(2Q)
0.165;-39225.0
(2T)(3T)
0.190;-29582.5
3(2TK)
0.151;-37630.0
2(3TQ)
0.128;-38427.5
23(TJ)
0.151;-39225.0
23(TK)
0.121;-37630.0
(2J)(3K)
0.150;-31612.5
2K(3J)
0.143;-36832.5
23(JK)
0.140;-36832.5
(3Q)(2K)
0.156;-30815.0
(2K)(3K)
0.213;-24797.5
4(246)
0.143;-41980.0
48(24)
0.114;-40385.0
(24)(4J)
0.218;-32772.5
5(245)
0.148;-41980.0
9(245)
0.128;-44010.0
K(245)
0.162;-40820.0
5(248)
0.167;-44807.5
5T(24)
0.112;-43212.5
(24)(5K)
0.128;-35600.0
9(246)
0.114;-43212.5
K(246)
0.154;-40022.5
6(249)
0.149;-43212.5
6J(24)
0.113;-41617.5
(2478)
0.116;-43212.5
(247Q)
0.156;-40022.5
7(249)
0.129;-42415.0
7J(24)
0.119;-40820.0
(2489)
0.120;-41617.5
(248K)
0.123;-38427.5
8T(24)
0.136;-40820.0
(24)(8K)
0.173;-33207.5
Q(249)
0.121;-38427.5
(24)(9J)
0.172;-34005.0
T(24T)
0.163;-34005.0
T(24J)
0.138;-38427.5
TK(24)
0.129;-36832.5
(24)(JQ)
0.181;-31612.5
QQ(24)
0.175;-30815.0
24(45)
0.177;-42777.5
44(28)
0.156;-40385.0
244T
0.098;-44010.0
24(4K)
0.180;-36397.5
(25)(47)
0.143;-40385.0
4(25T)
0.133;-43212.5
4Q(25)
0.118;-41617.5
(45)(27)
0.111;-40385.0
29(45)
0.110;-44010.0
2(45Q)
0.120;-41617.5
24(56)
0.119;-46402.5
24(58)
0.131;-44807.5
24(5T)
0.141;-43212.5
24(5Q)
0.099;-41617.5
4(267)
0.110;-44807.5
49(26)
0.141;-43212.5
(26)(4Q)
0.192;-35600.0
27(46)
0.092;-44807.5
2(46T)
0.151;-42415.0
(46)(2K)
0.153;-34802.5
46(28)
0.138;-44010.0
46(2T)
0.137;-42415.0
46(2Q)
0.121;-40820.0
(27)(47)
0.145;-33570.0
4(27T)
0.118;-41617.5
4Q(27)
0.141;-40022.5
(47)(29)
0.137;-37195.0
2J(47)
0.170;-40820.0
47(28)
0.169;-43212.5
47(2T)
0.133;-41617.5
47(2Q)
0.140;-40022.5
(28)(48)
0.167;-31975.0
4(28J)
0.134;-40022.5
4K(28)
0.137;-38427.5
(48)(2J)
0.123;-34802.5
2K(48)
0.122;-38427.5
24(8T)
0.134;-40820.0
24(8Q)
0.138;-39225.0
4(29T)
0.112;-40022.5
4Q(29)
0.143;-38427.5
(49)(2J)
0.158;-34005.0
2K(49)
0.191;-37630.0
24(9J)
0.167;-39225.0
24(9K)
0.149;-37630.0
(2T)(4Q)
0.129;-32410.0
2J(4T)
0.152;-38427.5
4T(2J)
0.152;-38427.5
4T(2K)
0.137;-36832.5
4Q(2J)
0.161;-36832.5
(4J)(2K)
0.156;-30815.0
4J(2K)
0.149;-36035.0
4K(2Q)
0.180;-35237.5
24(QK)
0.166;-35237.5
(25)(56)
0.153;-35165.0
5(259)
0.146;-37992.5
5J(25)
0.149;-36397.5
(2567)
0.165;-44010.0
(256J)
0.132;-40820.0
(25)(67)
0.159;-38790.0
6(25T)
0.144;-41617.5
6Q(25)
0.129;-40022.5
9(257)
0.103;-41617.5
K(257)
0.164;-38427.5
7(25T)
0.131;-40820.0
7Q(25)
0.136;-39225.0
T(258)
0.128;-40022.5
8(259)
0.135;-40820.0
8J(25)
0.174;-39225.0
(259T)
0.118;-39225.0
99(25)
0.168;-34802.5
(25)(9Q)
0.183;-32410.0
(25TQ)
0.126;-36832.5
T(25Q)
0.179;-36832.5
Q(25J)
0.138;-36035.0
(25)(JK)
0.156;-30017.5
QK(25)
0.144;-34440.0
25(57)
0.171;-39587.5
55(2T)
0.136;-37195.0
255Q
0.187;-40820.0
57(26)
0.145;-44010.0
(26)(5T)
0.137;-36397.5
5(26K)
0.166;-39225.0
2(568)
0.132;-43212.5
(56)(2J)
0.135;-35600.0
2K(56)
0.159;-39225.0
25(68)
0.120;-43212.5
25(6T)
0.121;-41617.5
25(6Q)
0.150;-40022.5
5(278)
0.146;-42415.0
5T(27)
0.151;-40820.0
(27)(5K)
0.175;-33207.5
29(57)
0.108;-41617.5
2(57Q)
0.126;-39225.0
25(78)
0.137;-42415.0
25(7T)
0.118;-40820.0
25(7Q)
0.148;-39225.0
5(289)
0.126;-40820.0
5J(28)
0.147;-39225.0
(58)(29)
0.152;-35600.0
2J(58)
0.103;-39225.0
58(29)
0.151;-40820.0
58(2J)
0.143;-39225.0
58(2K)
0.138;-37630.0
5T(29)
0.126;-39225.0
(29)(5K)
0.165;-31612.5
2J(59)
0.157;-38427.5
59(2T)
0.140;-39225.0
59(2Q)
0.129;-37630.0
(2T)(5T)
0.195;-27987.5
5(2TK)
0.154;-36035.0
2(5TQ)
0.127;-36832.5
25(TJ)
0.160;-37630.0
25(TK)
0.126;-36035.0
(2J)(5K)
0.182;-30017.5
2K(5J)
0.128;-35237.5
25(JK)
0.174;-35237.5
(5Q)(2K)
0.219;-29220.0
(2K)(5K)
0.161;-23202.5
6(268)
0.139;-37195.0
6T(26)
0.134;-35600.0
(26)(6K)
0.211;-27987.5
T(267)
0.143;-40022.5
7(268)
0.129;-41617.5
7T(26)
0.170;-40022.5
(26)(7K)
0.138;-32410.0
J(268)
0.127;-38427.5
89(26)
0.115;-40022.5
(26)(8Q)
0.164;-32410.0
(269J)
0.165;-37630.0
(26)(9T)
0.169;-33207.5
9(26K)
0.138;-36035.0
(26TK)
0.124;-35237.5
TQ(26)
0.147;-36035.0
K(26J)
0.166;-34440.0
Q(26Q)
0.170;-29220.0
KK(26)
0.157;-27625.0
66(29)
0.130;-36397.5
266J
0.144;-40022.5
67(27)
0.124;-37195.0
(27)(6T)
0.175;-34802.5
6(27K)
0.124;-37630.0
2(679)
0.120;-40820.0
(67)(2Q)
0.152;-33207.5
27(68)
0.141;-41617.5
27(6T)
0.145;-40022.5
27(6Q)
0.153;-38427.5
68(28)
0.152;-35600.0
(28)(6J)
0.179;-33207.5
28(68)
0.163;-35600.0
2(68J)
0.187;-38427.5
2688
0.110;-40820.0
268T
0.112;-44445.0
268Q
0.134;-42850.0
(29)(6T)
0.149;-33207.5
6(29K)
0.151;-36035.0
2(69J)
0.201;-37630.0
2699
0.150;-39225.0
269J
0.094;-42850.0
269K
0.168;-41255.0
6Q(2T)
0.194;-36035.0
(6T)(2Q)
0.172;-30815.0
2T(6J)
0.186;-36832.5
2T(6K)
0.172;-35237.5
6(2JK)
0.145;-34440.0
2(6JK)
0.169;-34440.0
2J(6K)
0.139;-34440.0
2Q(6Q)
0.157;-29220.0
26QK
0.126;-38862.5
78(27)
0.142;-35600.0
(27)(7J)
0.219;-27987.5
8(278)
0.173;-34802.5
Q(278)
0.113;-36832.5
(27)(8T)
0.164;-33207.5
8(27K)
0.204;-36035.0
(279Q)
0.153;-36035.0
9(27J)
0.172;-36832.5
9K(27)
0.187;-35237.5
TT(27)
0.161;-31612.5
(27)(TK)
0.171;-29220.0
J(27Q)
0.162;-34440.0
K(27Q)
0.202;-32845.0
77(28)
0.148;-35600.0
277T
0.136;-39225.0
27(7K)
0.150;-31612.5
(28)(7T)
0.194;-33207.5
7(28K)
0.150;-36035.0
2(78T)
0.135;-38427.5
(78)(2K)
0.136;-30815.0
78(2T)
0.154;-38427.5
78(2Q)
0.170;-36832.5
(29)(79)
0.167;-27987.5
7(29Q)
0.167;-36035.0
2(79T)
0.131;-37630.0
(79)(2K)
0.183;-30017.5
79(2J)
0.134;-36832.5
79(2K)
0.171;-35237.5
7J(2T)
0.170;-36035.0
(7T)(2J)
0.154;-30815.0
2K(7T)
0.166;-34440.0
27(TQ)
0.125;-35237.5
7(2JQ)
0.113;-34440.0
2(7JQ)
0.152;-34440.0
27(JQ)
0.172;-34440.0
7(2QK)
0.149;-32845.0
7Q(2K)
0.136;-32845.0
88(28)
0.152;-28785.0
(28)(8J)
0.171;-26392.5
9(289)
0.140;-32410.0
K(289)
0.186;-34440.0
9(28Q)
0.147;-35237.5
J(28T)
0.117;-35237.5
TJ(28)
0.155;-35237.5
(28JQ)
0.146;-33642.5
J(28K)
0.181;-32845.0
(28)(QK)
0.159;-26827.5
88(2T)
0.166;-32410.0
288Q
0.192;-36035.0
8T(29)
0.144;-36832.5
(29)(8K)
0.190;-29220.0
2J(89)
0.159;-36035.0
89(2T)
0.182;-36832.5
89(2Q)
0.156;-35237.5
(2T)(8T)
0.245;-25595.0
8(2TK)
0.182;-33642.5
2(8TQ)
0.153;-34440.0
28(TJ)
0.182;-35237.5
28(TK)
0.140;-33642.5
(2J)(8K)
0.169;-27625.0
2K(8J)
0.129;-32845.0
28(JK)
0.205;-32845.0
(8Q)(2K)
0.189;-26827.5
(2K)(8K)
0.211;-20810.0
9(29J)
0.181;-30017.5
9K(29)
0.179;-28422.5
TT(29)
0.163;-30017.5
(29)(TK)
0.158;-27625.0
J(29Q)
0.159;-32845.0
K(29Q)
0.185;-31250.0
99(2T)
0.190;-30815.0
299Q
0.131;-34440.0
9J(2T)
0.170;-34440.0
(9T)(2J)
0.148;-29220.0
2K(9T)
0.143;-32845.0
29(TQ)
0.177;-33642.5
9(2JQ)
0.171;-32845.0
2(9JQ)
0.149;-32845.0
29(JQ)
0.169;-32845.0
9(2QK)
0.128;-31250.0
9Q(2K)
0.186;-31250.0
TT(2T)
0.173;-24000.0
(2T)(TK)
0.224;-21607.5
J(2TQ)
0.190;-32047.5
K(2TQ)
0.165;-30452.5
TT(2J)
0.161;-28422.5
2TTK
0.165;-32047.5
TK(2J)
0.165;-31250.0
2TJJ
0.147;-32845.0
2TJK
0.167;-36470.0
2(TQK)
0.166;-30452.5
TK(2K)
0.187;-24435.0
(2J)(JK)
0.263;-20012.5
QK(2J)
0.196;-29655.0
2J(JK)
0.159;-25232.5
(JQ)(2K)
0.222;-24435.0
(2K)(JK)
0.247;-18417.5
K(2QK)
0.213;-22840.0
2K(QK)
0.242;-22840.0
3335
0.118;-43575.0
3339
0.099;-40385.0
333K
0.200;-37195.0
36(34)
0.170;-41980.0
(34)(39)
0.148;-34367.5
3(34Q)
0.123;-37195.0
33(45)
0.111;-42777.5
34(38)
0.149;-40385.0
334T
0.127;-44010.0
33(4K)
0.187;-36397.5
(35)(37)
0.139;-35165.0
3(35T)
0.161;-37992.5
3Q(35)
0.116;-36397.5
35(37)
0.127;-40385.0
3359
0.123;-44010.0
33(5Q)
0.129;-36397.5
(36)(37)
0.143;-34367.5
3(36T)
0.159;-37195.0
3Q(36)
0.151;-35600.0
36(38)
0.171;-38790.0
336T
0.142;-42415.0
33(6K)
0.160;-34802.5
(37)(39)
0.197;-31975.0
3(37Q)
0.139;-34802.5
33(78)
0.118;-37992.5
37(3J)
0.156;-35600.0
337K
0.125;-39225.0
3T(38)
0.182;-35600.0
(38)(3K)
0.140;-27987.5
338T
0.144;-40820.0
33(8K)
0.139;-33207.5
(39)(3J)
0.161;-28785.0
3399
0.159;-35600.0
33(9Q)
0.164;-33207.5
(3T)(3J)
0.178;-27987.5
33TT
0.145;-34005.0
33(TK)
0.203;-31612.5
(3J)(3K)
0.177;-25595.0
33JK
0.172;-36035.0
33(QK)
0.172;-30017.5
45(34)
0.144;-41980.0
(34)(48)
0.139;-34367.5
4(34J)
0.202;-37195.0
4K(34)
0.173;-35600.0
(3459)
0.124;-43212.5
(345K)
0.142;-40022.5
57(34)
0.156;-44807.5
(34)(5T)
0.171;-37195.0
5(34K)
0.142;-40022.5
(3469)
0.138;-42415.0
(346K)
0.177;-39225.0
68(34)
0.141;-43212.5
(34)(6J)
0.159;-35600.0
7(347)
0.128;-37992.5
J(347)
0.114;-40022.5
78(34)
0.132;-42415.0
(34)(7J)
0.145;-34802.5
8(348)
0.169;-36397.5
Q(348)
0.151;-38427.5
(34)(8T)
0.194;-34802.5
8(34K)
0.142;-37630.0
(349Q)
0.160;-37630.0
9(34J)
0.140;-38427.5
9K(34)
0.116;-36832.5
TT(34)
0.130;-33207.5
(34)(TK)
0.180;-30815.0
J(34Q)
0.163;-36035.0
K(34Q)
0.148;-34440.0
44(35)
0.107;-41980.0
3447
0.142;-45605.0
34(4T)
0.182;-37992.5
44(3K)
0.132;-35600.0
4(357)
0.133;-44807.5
49(35)
0.120;-43212.5
(35)(4Q)
0.139;-35600.0
36(45)
0.109;-45605.0
3(459)
0.131;-43212.5
(45)(3Q)
0.144;-35600.0
35(46)
0.130;-45605.0
35(48)
0.112;-44010.0
35(4T)
0.116;-42415.0
35(4Q)
0.105;-40820.0
46(36)
0.122;-39587.5
(36)(49)
0.112;-37195.0
4(36Q)
0.154;-40022.5
3(467)
0.147;-44010.0
(46)(3T)
0.135;-36397.5
3Q(46)
0.166;-40022.5
3467
0.113;-49230.0
3469
0.137;-47635.0
346J
0.114;-46040.0
346K
0.130;-44445.0
49(37)
0.131;-41617.5
(37)(4Q)
0.201;-34005.0
38(47)
0.140;-42415.0
3(47J)
0.170;-40022.5
3477
0.129;-43212.5
3479
0.128;-46837.5
347J
0.122;-45242.5
347K
0.117;-43647.5
4T(38)
0.149;-40022.5
(38)(4K)
0.164;-32410.0
3T(48)
0.151;-40022.5
3(48K)
0.133;-37630.0
38(4T)
0.161;-40022.5
38(4Q)
0.148;-38427.5
49(39)
0.159;-34802.5
(39)(4Q)
0.177;-32410.0
3T(49)
0.139;-39225.0
3(49K)
0.176;-36832.5
39(4J)
0.144;-38427.5
39(4K)
0.150;-36832.5
4(3TQ)
0.171;-36832.5
3(4TJ)
0.135;-37630.0
34TT
0.178;-38427.5
34TQ
0.124;-42052.5
(3J)(4Q)
0.165;-30815.0
3Q(4J)
0.184;-36035.0
34JQ
0.168;-41255.0
(3Q)(4K)
0.173;-29220.0
3Q(4K)
0.151;-34440.0
5(356)
0.116;-39587.5
58(35)
0.159;-37992.5
(35)(5J)
0.167;-30380.0
6(356)
0.141;-38790.0
T(356)
0.182;-40820.0
6(357)
0.148;-43212.5
69(35)
0.122;-41617.5
(35)(6Q)
0.148;-34005.0
(3579)
0.148;-40820.0
(357K)
0.143;-37630.0
79(35)
0.149;-40820.0
(35)(7Q)
0.164;-33207.5
(358T)
0.141;-39225.0
88(35)
0.118;-35600.0
(35)(8J)
0.125;-33207.5
9(359)
0.125;-34005.0
K(359)
0.177;-36035.0
9(35Q)
0.178;-36832.5
J(35T)
0.142;-36832.5
TJ(35)
0.123;-36832.5
(35JQ)
0.157;-35237.5
J(35K)
0.176;-34440.0
(35)(QK)
0.141;-28422.5
55(37)
0.152;-38790.0
3559
0.159;-42415.0
35(5Q)
0.148;-34802.5
(36)(57)
0.123;-37992.5
5(36T)
0.128;-40820.0
5Q(36)
0.119;-39225.0
(56)(38)
0.149;-37195.0
3T(56)
0.115;-40820.0
3(56K)
0.147;-38427.5
36(58)
0.106;-42415.0
36(5T)
0.147;-40820.0
36(5Q)
0.134;-39225.0
57(37)
0.141;-37195.0
(37)(5T)
0.147;-34802.5
5(37K)
0.130;-37630.0
3(579)
0.142;-40820.0
(57)(3Q)
0.197;-33207.5
37(58)
0.155;-41617.5
37(5T)
0.149;-40022.5
37(5Q)
0.160;-38427.5
58(38)
0.172;-35600.0
(38)(5J)
0.158;-33207.5
38(58)
0.136;-35600.0
3(58J)
0.141;-38427.5
3588
0.163;-40820.0
358T
0.112;-44445.0
358Q
0.130;-42850.0
(39)(5T)
0.126;-33207.5
5(39K)
0.152;-36035.0
3(59J)
0.168;-37630.0
3599
0.137;-39225.0
359J
0.113;-42850.0
359K
0.139;-41255.0
5Q(3T)
0.124;-36035.0
(5T)(3Q)
0.156;-30815.0
3T(5J)
0.135;-36832.5
3T(5K)
0.178;-35237.5
5(3JK)
0.152;-34440.0
3(5JK)
0.151;-34440.0
3J(5K)
0.174;-34440.0
3Q(5Q)
0.219;-29220.0
35QK
0.128;-38862.5
67(36)
0.117;-37195.0
(36)(6T)
0.191;-29582.5
6(36K)
0.186;-32410.0
(367T)
0.125;-39225.0
77(36)
0.163;-36397.5
(36)(7T)
0.208;-34005.0
7(36K)
0.129;-36832.5
(368J)
0.122;-37630.0
(36)(89)
0.157;-34005.0
8(36Q)
0.153;-36832.5
T(369)
0.172;-37630.0
9(36T)
0.117;-37630.0
9Q(36)
0.197;-36035.0
Q(36T)
0.126;-35237.5
(36)(TQ)
0.164;-30017.5
(36JK)
0.162;-33642.5
JK(36)
0.141;-33642.5
K(36K)
0.196;-26827.5
3668
0.126;-41617.5
36(6J)
0.195;-34005.0
(37)(67)
0.175;-31177.5
6(37T)
0.146;-39225.0
6Q(37)
0.143;-37630.0
(67)(39)
0.166;-34802.5
3J(67)
0.136;-38427.5
67(38)
0.102;-40820.0
67(3T)
0.152;-39225.0
67(3Q)
0.141;-37630.0
(38)(68)
0.173;-29582.5
6(38J)
0.115;-37630.0
6K(38)
0.119;-36035.0
(68)(3J)
0.176;-32410.0
3K(68)
0.168;-36035.0
36(8T)
0.175;-38427.5
36(8Q)
0.133;-36832.5
6(39T)
0.146;-37630.0
6Q(39)
0.166;-36035.0
(69)(3J)
0.137;-31612.5
3K(69)
0.206;-35237.5
36(9J)
0.148;-36832.5
36(9K)
0.154;-35237.5
(3T)(6Q)
0.174;-30017.5
3J(6T)
0.145;-36035.0
6T(3J)
0.186;-36035.0
6T(3K)
0.138;-34440.0
6Q(3J)
0.142;-34440.0
(6J)(3K)
0.184;-28422.5
6J(3K)
0.127;-33642.5
6K(3Q)
0.164;-32845.0
36(QK)
0.211;-32845.0
(37)(78)
0.213;-29582.5
7(37J)
0.151;-32410.0
7K(37)
0.181;-30815.0
(378Q)
0.115;-36035.0
8(37T)
0.190;-37630.0
8Q(37)
0.132;-36035.0
J(379)
0.140;-36035.0
9T(37)
0.122;-36832.5
(37)(9K)
0.150;-29220.0
K(37T)
0.220;-33642.5
T(37K)
0.205;-33642.5
JJ(37)
0.153;-29220.0
(37QK)
0.180;-32047.5
3777
0.173;-35600.0
37(7T)
0.162;-33207.5
77(3K)
0.176;-30815.0
7(38T)
0.137;-37630.0
7Q(38)
0.146;-36035.0
(78)(3T)
0.164;-32410.0
3Q(78)
0.208;-36035.0
3789
0.129;-43647.5
378J
0.147;-42052.5
378K
0.155;-40457.5
7J(39)
0.158;-36035.0
(79)(3T)
0.140;-31612.5
3Q(79)
0.138;-35237.5
379T
0.134;-42052.5
379Q
0.141;-40457.5
(3T)(7J)
0.145;-30017.5
3T(7T)
0.166;-30815.0
3(7TK)
0.199;-33642.5
3T(7Q)
0.141;-34440.0
7J(3J)
0.169;-29220.0
(7J)(3Q)
0.199;-28422.5
3J(7Q)
0.161;-33642.5
7Q(3Q)
0.173;-27625.0
37QQ
0.140;-32845.0
37KK
0.151;-31250.0
8(38J)
0.176;-30815.0
8K(38)
0.132;-29220.0
(389K)
0.188;-33642.5
9J(38)
0.162;-35237.5
(38TJ)
0.140;-34440.0
(38)(TJ)
0.170;-29220.0
J(38J)
0.190;-28422.5
JQ(38)
0.203;-32845.0
Q(38K)
0.162;-31250.0
3889
0.146;-37630.0
38(8Q)
0.196;-30017.5
(39)(8T)
0.153;-30815.0
8(39K)
0.131;-33642.5
3(89J)
0.136;-35237.5
3899
0.121;-36832.5
389J
0.129;-40457.5
389K
0.154;-38862.5
8Q(3T)
0.169;-33642.5
(8T)(3Q)
0.180;-28422.5
3T(8J)
0.138;-34440.0
3T(8K)
0.144;-32845.0
8(3JK)
0.170;-32047.5
3(8JK)
0.148;-32047.5
3J(8K)
0.158;-32047.5
3Q(8Q)
0.182;-26827.5
38QK
0.125;-36470.0
9T(39)
0.182;-30017.5
(39)(9K)
0.239;-22405.0
K(39T)
0.152;-32047.5
T(39K)
0.155;-32047.5
JJ(39)
0.174;-27625.0
(39QK)
0.194;-30452.5
3999
0.193;-30815.0
39(9Q)
0.198;-28422.5
(3T)(9J)
0.173;-28422.5
3T(9T)
0.192;-29220.0
3(9TK)
0.162;-32047.5
3T(9Q)
0.162;-32845.0
9J(3J)
0.155;-27625.0
(9J)(3Q)
0.174;-26827.5
3J(9Q)
0.207;-32047.5
9Q(3Q)
0.218;-26030.0
39QQ
0.193;-31250.0
39KK
0.178;-29655.0
T(3TK)
0.189;-26030.0
JJ(3T)
0.205;-26827.5
(3TQK)
0.194;-29655.0
3TTT
0.213;-28422.5
3T(TK)
0.254;-26030.0
(3J)(TK)
0.191;-25232.5
3K(TJ)
0.219;-30452.5
3T(JK)
0.185;-30452.5
(TQ)(3K)
0.216;-24435.0
(3K)(TK)
0.222;-18417.5
J(3JK)
0.219;-24435.0
(3J)(QK)
0.218;-23637.5
JJ(3K)
0.164;-24435.0
3Q(JQ)
0.190;-24435.0
3JQK
0.174;-34077.5
QK(3Q)
0.244;-22840.0
QK(3K)
0.193;-22042.5
44(46)
0.186;-35165.0
44(4T)
0.157;-31975.0
(45)(45)
0.155;-29945.0
4(458)
0.165;-37992.5
4T(45)
0.108;-36397.5
(45)(4K)
0.159;-28785.0
4457
0.138;-44010.0
44(5T)
0.181;-36397.5
45(4K)
0.158;-34005.0
4(468)
0.190;-37195.0
4T(46)
0.141;-35600.0
(46)(4K)
0.194;-27987.5
4468
0.125;-42415.0
44(6J)
0.158;-34802.5
(47)(47)
0.158;-26755.0
4(47T)
0.163;-34802.5
4Q(47)
0.143;-33207.5
47(49)
0.127;-35600.0
447J
0.137;-39225.0
48(48)
0.190;-30380.0
(48)(4J)
0.162;-27987.5
4488
0.185;-35600.0
44(8J)
0.152;-33207.5
(49)(49)
0.175;-23565.0
4(49Q)
0.161;-31612.5
44(9T)
0.139;-33207.5
49(4K)
0.188;-30815.0
4(4TQ)
0.172;-30815.0
44(TJ)
0.174;-31612.5
(4J)(4J)
0.187;-20375.0
44JJ
0.162;-30815.0
4Q(4Q)
0.223;-24000.0
(4K)(4K)
0.224;-17185.0
(45)(57)
0.146;-32772.5
5(45T)
0.147;-35600.0
5Q(45)
0.176;-34005.0
8(456)
0.170;-41617.5
Q(456)
0.150;-38427.5
(45)(68)
0.149;-36397.5
6(45J)
0.112;-39225.0
6K(45)
0.105;-37630.0
(457J)
0.196;-38427.5
(45)(78)
0.165;-35600.0
7(45J)
0.154;-38427.5
7K(45)
0.135;-36832.5
(458Q)
0.140;-36832.5
8(45T)
0.138;-38427.5
8Q(45)
0.167;-36832.5
J(459)
0.164;-36832.5
9T(45)
0.156;-37630.0
(45)(9K)
0.184;-30017.5
K(45T)
0.154;-34440.0
T(45K)
0.124;-34440.0
JJ(45)
0.180;-30017.5
(45QK)
0.153;-32845.0
4555
0.153;-39587.5
45(58)
0.171;-37195.0
55(4J)
0.116;-34802.5
455K
0.157;-38427.5
58(46)
0.117;-41617.5
(46)(5J)
0.128;-34005.0
46(56)
0.181;-37992.5
4(569)
0.108;-40820.0
(56)(4Q)
0.172;-33207.5
46(57)
0.112;-42415.0
46(59)
0.145;-40820.0
46(5J)
0.179;-39225.0
46(5K)
0.156;-37630.0
5(479)
0.118;-40022.5
5J(47)
0.151;-38427.5
(57)(48)
0.153;-35600.0
4T(57)
0.169;-39225.0
4(57K)
0.148;-36832.5
47(59)
0.118;-40022.5
47(5J)
0.180;-38427.5
47(5K)
0.146;-36832.5
5(48T)
0.138;-38427.5
5Q(48)
0.144;-36832.5
(58)(4T)
0.181;-33207.5
4Q(58)
0.150;-36832.5
4589
0.111;-44445.0
458J
0.142;-42850.0
458K
0.156;-41255.0
5J(49)
0.121;-36832.5
(59)(4T)
0.185;-32410.0
4Q(59)
0.134;-36035.0
459T
0.127;-42850.0
459Q
0.148;-41255.0
(4T)(5J)
0.156;-30815.0
4T(5T)
0.193;-31612.5
4(5TK)
0.127;-34440.0
4T(5Q)
0.164;-35237.5
5J(4J)
0.232;-30017.5
(5J)(4Q)
0.206;-29220.0
4J(5Q)
0.140;-34440.0
5Q(4Q)
0.176;-28422.5
45QQ
0.161;-33642.5
45KK
0.156;-32047.5
6(469)
0.162;-34802.5
6J(46)
0.169;-33207.5
(4678)
0.121;-40022.5
(467Q)
0.141;-36832.5
7(469)
0.173;-39225.0
7J(46)
0.142;-37630.0
(4689)
0.134;-38427.5
(468K)
0.184;-35237.5
8T(46)
0.147;-37630.0
(46)(8K)
0.195;-30017.5
Q(469)
0.154;-35237.5
(46)(9J)
0.158;-30815.0
T(46T)
0.144;-30815.0
T(46J)
0.173;-35237.5
TK(46)
0.191;-33642.5
(46)(JQ)
0.159;-28422.5
QQ(46)
0.174;-27625.0
46(67)
0.123;-36397.5
66(4T)
0.182;-34005.0
466Q
0.147;-37630.0
68(47)
0.183;-40022.5
(47)(6J)
0.163;-32410.0
47(67)
0.127;-35600.0
4(67T)
0.139;-38427.5
(67)(4K)
0.158;-30815.0
67(49)
0.183;-39225.0
67(4J)
0.140;-37630.0
67(4K)
0.132;-36035.0
69(48)
0.176;-38427.5
(48)(6Q)
0.153;-30815.0
49(68)
0.144;-38427.5
4(68Q)
0.145;-36035.0
46(89)
0.117;-38427.5
46(8J)
0.147;-36832.5
46(8K)
0.149;-35237.5
(49)(6J)
0.206;-30815.0
49(69)
0.152;-32410.0
4(69Q)
0.158;-35237.5
46(9T)
0.133;-36832.5
46(9Q)
0.148;-35237.5
6(4TJ)
0.119;-35237.5
6K(4T)
0.123;-33642.5
(6T)(4K)
0.193;-28422.5
6T(4Q)
0.167;-34440.0
(4J)(6J)
0.173;-24000.0
4J(6J)
0.200;-29220.0
6J(4Q)
0.156;-33642.5
(4Q)(6Q)
0.184;-22405.0
4K(6Q)
0.145;-32047.5
4K(6K)
0.166;-26030.0
79(47)
0.148;-33207.5
(47)(7Q)
0.186;-25595.0
(478T)
0.154;-36832.5
88(47)
0.151;-33207.5
(47)(8J)
0.196;-30815.0
9(479)
0.182;-31612.5
K(479)
0.140;-33642.5
9(47Q)
0.139;-34440.0
J(47T)
0.137;-34440.0
TJ(47)
0.141;-34440.0
(47JQ)
0.166;-32845.0
J(47K)
0.145;-32047.5
(47)(QK)
0.169;-26030.0
77(49)
0.167;-33207.5
477J
0.134;-36832.5
78(48)
0.142;-33207.5
(48)(7J)
0.141;-30815.0
48(78)
0.141;-33207.5
4(78J)
0.166;-36035.0
4788
0.140;-38427.5
478T
0.138;-42052.5
478Q
0.147;-40457.5
(49)(7T)
0.131;-30815.0
7(49K)
0.113;-33642.5
4(79J)
0.120;-35237.5
4799
0.146;-36832.5
479J
0.118;-40457.5
479K
0.149;-38862.5
7Q(4T)
0.196;-33642.5
(7T)(4Q)
0.183;-28422.5
4T(7J)
0.171;-34440.0
4T(7K)
0.143;-32845.0
7(4JK)
0.154;-32047.5
4(7JK)
0.152;-32047.5
4J(7K)
0.178;-32047.5
4Q(7Q)
0.158;-26827.5
47QK
0.178;-36470.0
89(48)
0.166;-31612.5
(48)(8Q)
0.214;-24000.0
(489J)
0.126;-34440.0
(48)(9T)
0.168;-30017.5
9(48K)
0.127;-32845.0
(48TK)
0.145;-32047.5
TQ(48)
0.144;-32845.0
K(48J)
0.157;-31250.0
Q(48Q)
0.212;-26030.0
KK(48)
0.197;-24435.0
88(4J)
0.137;-30017.5
488K
0.125;-33642.5
8J(49)
0.179;-34440.0
(89)(4T)
0.179;-30017.5
4Q(89)
0.153;-33642.5
489T
0.136;-40457.5
489Q
0.184;-38862.5
(4T)(8J)
0.202;-28422.5
4T(8T)
0.191;-29220.0
4(8TK)
0.162;-32047.5
4T(8Q)
0.131;-32845.0
8J(4J)
0.189;-27625.0
(8J)(4Q)
0.189;-26827.5
4J(8Q)
0.147;-32047.5
8Q(4Q)
0.200;-26030.0
48QQ
0.158;-31250.0
48KK
0.230;-29655.0
9(49Q)
0.205;-27625.0
J(49T)
0.184;-32845.0
TJ(49)
0.179;-32845.0
(49JQ)
0.211;-31250.0
J(49K)
0.207;-30452.5
(49)(QK)
0.245;-24435.0
99(4J)
0.167;-28422.5
499K
0.163;-32047.5
9Q(4T)
0.136;-32047.5
(9T)(4Q)
0.209;-26827.5
4T(9J)
0.185;-32845.0
4T(9K)
0.157;-31250.0
9(4JK)
0.179;-30452.5
4(9JK)
0.181;-30452.5
4J(9K)
0.167;-30452.5
4Q(9Q)
0.214;-25232.5
49QK
0.158;-34875.0
TJ(4T)
0.179;-26827.5
(4TJQ)
0.199;-30452.5
J(4TK)
0.167;-29655.0
(4T)(QK)
0.213;-23637.5
TT(4Q)
0.215;-26030.0
T(4JQ)
0.202;-30452.5
4(TJQ)
0.175;-30452.5
4T(JQ)
0.183;-30452.5
T(4QK)
0.189;-28857.5
TQ(4K)
0.178;-28857.5
JJ(4J)
0.244;-20012.5
(4JQK)
0.148;-28060.0
4JJJ
0.216;-25232.5
JQ(4Q)
0.159;-23637.5
4JQQ
0.171;-28857.5
4JKK
0.188;-27262.5
QQ(4K)
0.174;-22042.5
4KKK
0.271;-20447.5
55(59)
0.145;-30380.0
55(5K)
0.218;-27190.0
(56)(58)
0.136;-30380.0
5(56J)
0.179;-33207.5
5K(56)
0.190;-31612.5
56(59)
0.137;-34802.5
556J
0.139;-38427.5
57(57)
0.169;-30380.0
(57)(5T)
0.194;-27987.5
5(57K)
0.185;-30815.0
55(79)
0.167;-34005.0
57(5Q)
0.134;-31612.5
5(589)
0.157;-33207.5
5J(58)
0.151;-31612.5
58(59)
0.154;-33207.5
558J
0.142;-36832.5
59(59)
0.186;-27190.0
(59)(5Q)
0.201;-24797.5
559T
0.156;-36832.5
55(9K)
0.183;-29220.0
(5T)(5Q)
0.173;-24000.0
55TJ
0.141;-35237.5
5J(5J)
0.223;-24000.0
5J(5Q)
0.156;-28422.5
5(5QK)
0.203;-26827.5
5K(5K)
0.214;-20810.0
68(56)
0.161;-34802.5
(56)(6J)
0.171;-27190.0
7(567)
0.191;-34802.5
J(567)
0.141;-36832.5
78(56)
0.140;-39225.0
(56)(7J)
0.171;-31612.5
8(568)
0.193;-33207.5
Q(568)
0.178;-35237.5
(56)(8T)
0.173;-31612.5
8(56K)
0.179;-34440.0
(569Q)
0.154;-34440.0
9(56J)
0.146;-35237.5
9K(56)
0.135;-33642.5
TT(56)
0.205;-30017.5
(56)(TK)
0.143;-27625.0
J(56Q)
0.154;-32845.0
K(56Q)
0.174;-31250.0
66(57)
0.155;-35600.0
5669
0.139;-39225.0
56(6Q)
0.210;-31612.5
(57)(68)
0.181;-34005.0
6(57J)
0.147;-36832.5
6K(57)
0.186;-35237.5
(67)(5T)
0.145;-32410.0
5Q(67)
0.118;-36035.0
5678
0.141;-44445.0
567T
0.121;-42850.0
567Q
0.130;-41255.0
(58)(69)
0.150;-32410.0
6(58Q)
0.136;-35237.5
5(689)
0.159;-37630.0
(68)(5Q)
0.178;-30017.5
58(69)
0.159;-37630.0
58(6J)
0.166;-36035.0
58(6K)
0.149;-34440.0
6(59J)
0.137;-35237.5
6K(59)
0.159;-33642.5
(69)(5Q)
0.191;-29220.0
59(6T)
0.183;-36035.0
59(6Q)
0.183;-34440.0
6T(5T)
0.160;-30017.5
(5T)(6K)
0.161;-27625.0
5Q(6T)
0.162;-33642.5
56TJ
0.171;-39660.0
56TK
0.176;-38065.0
6K(5J)
0.191;-32047.5
56JJ
0.149;-33642.5
56JK
0.117;-37267.5
5(6QK)
0.178;-31250.0
6K(5K)
0.209;-25232.5
(57)(79)
0.212;-27190.0
7(57Q)
0.153;-30017.5
9(578)
0.140;-36832.5
K(578)
0.139;-33642.5
8(57J)
0.137;-35237.5
8K(57)
0.164;-33642.5
(579K)
0.173;-32845.0
9J(57)
0.198;-34440.0
(57TJ)
0.166;-33642.5
(57)(TJ)
0.136;-28422.5
J(57J)
0.170;-27625.0
JQ(57)
0.224;-32047.5
Q(57K)
0.156;-30452.5
5778
0.138;-38427.5
57(7J)
0.182;-30815.0
(58)(78)
0.210;-27190.0
7(58J)
0.138;-35237.5
7K(58)
0.152;-33642.5
(78)(5J)
0.165;-30017.5
5K(78)
0.165;-33642.5
57(8T)
0.129;-36035.0
57(8Q)
0.150;-34440.0
7(59T)
0.148;-35237.5
7Q(59)
0.160;-33642.5
(79)(5J)
0.204;-29220.0
5K(79)
0.154;-32845.0
57(9J)
0.157;-34440.0
57(9K)
0.159;-32845.0
(5T)(7Q)
0.237;-27625.0
5J(7T)
0.177;-33642.5
7T(5J)
0.155;-33642.5
7T(5K)
0.201;-32047.5
7Q(5J)
0.169;-32047.5
(7J)(5K)
0.165;-26030.0
7J(5K)
0.182;-31250.0
7K(5Q)
0.172;-30452.5
57(QK)
0.177;-30452.5
(58)(89)
0.185;-25595.0
8(58Q)
0.234;-28422.5
T(589)
0.179;-34440.0
9(58T)
0.185;-34440.0
9Q(58)
0.151;-32845.0
Q(58T)
0.189;-32047.5
(58)(TQ)
0.188;-26827.5
(58JK)
0.172;-30452.5
JK(58)
0.160;-30452.5
K(58K)
0.258;-23637.5
588T
0.167;-35237.5
58(8K)
0.190;-27625.0
(59)(8J)
0.154;-28422.5
59(89)
0.171;-30017.5
5(89Q)
0.171;-32845.0
58(9T)
0.206;-34440.0
58(9Q)
0.190;-32845.0
8(5TJ)
0.144;-32845.0
8K(5T)
0.131;-31250.0
(8T)(5K)
0.162;-26030.0
8T(5Q)
0.182;-32047.5
(5J)(8J)
0.174;-21607.5
5J(8J)
0.164;-26827.5
8J(5Q)
0.160;-31250.0
(5Q)(8Q)
0.197;-20012.5
5K(8Q)
0.170;-29655.0
5K(8K)
0.205;-23637.5
9J(59)
0.141;-27625.0
(59TJ)
0.138;-32047.5
(59)(TJ)
0.227;-26827.5
J(59J)
0.212;-26030.0
JQ(59)
0.199;-30452.5
Q(59K)
0.171;-28857.5
599T
0.134;-33642.5
59(9K)
0.194;-26030.0
(5T)(9Q)
0.225;-26030.0
5J(9T)
0.164;-32047.5
9T(5J)
0.138;-32047.5
9T(5K)
0.175;-30452.5
9Q(5J)
0.158;-30452.5
(9J)(5K)
0.162;-24435.0
9J(5K)
0.172;-29655.0
9K(5Q)
0.132;-28857.5
59(QK)
0.237;-28857.5
(5T)(TJ)
0.205;-20810.0
J(5TJ)
0.184;-25232.5
JQ(5T)
0.168;-29655.0
Q(5TK)
0.182;-28060.0
5TTJ
0.187;-31250.0
TJ(5J)
0.200;-25232.5
(TJ)(5Q)
0.181;-24435.0
5J(TQ)
0.163;-29655.0
TQ(5Q)
0.175;-23637.5
5TQQ
0.217;-28857.5
5TKK
0.203;-27262.5
Q(5JQ)
0.180;-22840.0
KK(5J)
0.216;-21245.0
(5Q)(JQ)
0.280;-17620.0
5K(JQ)
0.175;-27262.5
5K(JK)
0.199;-21245.0
5QQQ
0.262;-22042.5
KK(5K)
0.291;-14430.0
6669
0.132;-33207.5
666K
0.173;-30017.5
69(67)
0.174;-32410.0
(67)(6Q)
0.196;-24797.5
6678
0.176;-38427.5
66(7J)
0.171;-30815.0
(68)(68)
0.202;-21970.0
6(68J)
0.169;-30017.5
6K(68)
0.170;-28422.5
68(6J)
0.156;-30017.5
668K
0.142;-33642.5
6J(69)
0.210;-29220.0
69(6T)
0.146;-30017.5
669Q
0.178;-33642.5
6J(6T)
0.193;-28422.5
6T(6J)
0.171;-28422.5
66TK
0.183;-32047.5
6K(6J)
0.161;-26030.0
(6Q)(6Q)
0.206;-15590.0
66QK
0.200;-30452.5
7(679)
0.160;-31612.5
7J(67)
0.188;-30017.5
(6789)
0.172;-36035.0
(678K)
0.179;-32845.0
8T(67)
0.180;-35237.5
(67)(8K)
0.239;-27625.0
Q(679)
0.167;-32845.0
(67)(9J)
0.191;-28422.5
T(67T)
0.229;-28422.5
T(67J)
0.172;-32845.0
TK(67)
0.166;-31250.0
(67)(JQ)
0.236;-26030.0
QQ(67)
0.220;-25232.5
67(78)
0.188;-32410.0
77(6J)
0.166;-30017.5
677K
0.160;-33642.5
7T(68)
0.156;-35237.5
(68)(7K)
0.195;-27625.0
6T(78)
0.176;-35237.5
6(78K)
0.164;-32845.0
68(7T)
0.162;-35237.5
68(7Q)
0.139;-33642.5
79(69)
0.177;-30017.5
(69)(7Q)
0.197;-27625.0
6T(79)
0.133;-34440.0
6(79K)
0.145;-32047.5
69(7J)
0.167;-33642.5
69(7K)
0.202;-32047.5
7(6TQ)
0.181;-32047.5
6(7TJ)
0.143;-32845.0
67TT
0.137;-33642.5
67TQ
0.162;-37267.5
(6J)(7Q)
0.210;-26030.0
6Q(7J)
0.163;-31250.0
67JQ
0.193;-36470.0
(6Q)(7K)
0.222;-24435.0
6Q(7K)
0.197;-29655.0
8(689)
0.159;-30017.5
8J(68)
0.169;-28422.5
(689T)
0.156;-33642.5
99(68)
0.221;-29220.0
(68)(9Q)
0.163;-26827.5
(68TQ)
0.207;-31250.0
T(68Q)
0.206;-31250.0
Q(68J)
0.203;-30452.5
(68)(JK)
0.168;-24435.0
QK(68)
0.190;-28857.5
68(8T)
0.168;-29220.0
88(6K)
0.203;-26827.5
8(69J)
0.145;-32845.0
8K(69)
0.161;-31250.0
(89)(6Q)
0.234;-26827.5
69(8T)
0.172;-33642.5
69(8Q)
0.195;-32047.5
8T(6T)
0.205;-27625.0
(6T)(8K)
0.190;-25232.5
6Q(8T)
0.170;-31250.0
68TJ
0.122;-37267.5
68TK
0.171;-35672.5
8K(6J)
0.159;-29655.0
68JJ
0.211;-31250.0
68JK
0.135;-34875.0
6(8QK)
0.161;-28857.5
8K(6K)
0.196;-22840.0
(69)(9J)
0.231;-21607.5
T(69T)
0.141;-26827.5
T(69J)
0.180;-31250.0
TK(69)
0.177;-29655.0
(69)(JQ)
0.228;-24435.0
QQ(69)
0.149;-23637.5
69(9T)
0.239;-27625.0
99(6K)
0.193;-25232.5
9(6TQ)
0.189;-30452.5
6(9TJ)
0.171;-31250.0
69TT
0.154;-32047.5
69TQ
0.153;-35672.5
(6J)(9Q)
0.162;-24435.0
6Q(9J)
0.167;-29655.0
69JQ
0.173;-34875.0
(6Q)(9K)
0.207;-22840.0
6Q(9K)
0.143;-28060.0
T(6TJ)
0.164;-25232.5
TK(6T)
0.214;-23637.5
(6T)(JQ)
0.188;-23637.5
QQ(6T)
0.215;-22840.0
6T(TJ)
0.156;-25232.5
(6J)(TJ)
0.177;-19215.0
6J(TJ)
0.211;-24435.0
TJ(6Q)
0.162;-28857.5
(6Q)(TQ)
0.185;-17620.0
6K(TQ)
0.200;-27262.5
6K(TK)
0.164;-21245.0
JK(6J)
0.223;-22042.5
K(6JK)
0.194;-20447.5
6JJK
0.151;-27262.5
6(JQK)
0.220;-26465.0
JK(6K)
0.223;-20447.5
KK(6Q)
0.179;-19650.0
6QKK
0.218;-24870.0
77(7T)
0.169;-24797.5
(78)(78)
0.177;-20375.0
7(78J)
0.141;-28422.5
7K(78)
0.139;-26827.5
78(7J)
0.230;-28422.5
778K
0.133;-32047.5
7J(79)
0.202;-27625.0
79(7T)
0.168;-28422.5
779Q
0.176;-32047.5
7J(7T)
0.174;-26827.5
7T(7J)
0.209;-26827.5
77TK
0.161;-30452.5
7K(7J)
0.257;-24435.0
(7Q)(7Q)
0.280;-13995.0
77QK
0.202;-28857.5
8(78T)
0.164;-28422.5
8Q(78)
0.198;-26827.5
J(789)
0.156;-32047.5
9T(78)
0.168;-32845.0
(78)(9K)
0.212;-25232.5
K(78T)
0.163;-29655.0
T(78K)
0.171;-29655.0
JJ(78)
0.228;-25232.5
(78QK)
0.156;-28060.0
7888
0.168;-30017.5
78(8J)
0.225;-27625.0
(79)(89)
0.174;-23202.5
8(79Q)
0.184;-31250.0
7(89T)
0.160;-32845.0
(89)(7K)
0.194;-25232.5
89(7J)
0.179;-32047.5
89(7K)
0.192;-30452.5
8J(7T)
0.176;-31250.0
(8T)(7J)
0.198;-26030.0
7K(8T)
0.191;-29655.0
78(TQ)
0.162;-30452.5
8(7JQ)
0.168;-29655.0
7(8JQ)
0.165;-29655.0
78(JQ)
0.228;-29655.0
8(7QK)
0.238;-28060.0
8Q(7K)
0.165;-28060.0
99(79)
0.180;-22405.0
(79)(9Q)
0.211;-20012.5
(79TQ)
0.194;-29655.0
T(79Q)
0.175;-29655.0
Q(79J)
0.183;-28857.5
(79)(JK)
0.223;-22840.0
QK(79)
0.183;-27262.5
79(9J)
0.205;-26030.0
(7T)(9T)
0.212;-20810.0
9(7TK)
0.185;-28857.5
7(9TQ)
0.194;-29655.0
79(TJ)
0.178;-30452.5
79(TK)
0.175;-28857.5
(7J)(9K)
0.242;-22840.0
7K(9J)
0.224;-28060.0
79(JK)
0.158;-28060.0
(9Q)(7K)
0.158;-22042.5
(7K)(9K)
0.289;-16025.0
T(7TQ)
0.240;-23637.5
Q(7TJ)
0.141;-28060.0
(7T)(JK)
0.243;-22042.5
QK(7T)
0.202;-26465.0
7T(TQ)
0.197;-23637.5
(7J)(TQ)
0.195;-22840.0
7Q(TJ)
0.201;-28060.0
7TJQ
0.161;-33280.0
(7Q)(TK)
0.192;-21245.0
7Q(TK)
0.197;-26465.0
J(7JQ)
0.249;-22042.5
K(7JQ)
0.216;-25667.5
JJ(7Q)
0.233;-22042.5
J(7QK)
0.171;-25667.5
JQ(7K)
0.183;-25667.5
QQ(7Q)
0.270;-15227.5
7Q(QK)
0.177;-19650.0
8888
0.227;-24000.0
888Q
0.149;-26030.0
8(89J)
0.198;-26030.0
8K(89)
0.193;-24435.0
89(8Q)
0.191;-25232.5
8(8TJ)
0.155;-25232.5
8K(8T)
0.160;-23637.5
8T(8K)
0.188;-23637.5
8(8JK)
0.246;-22840.0
88(JK)
0.221;-22840.0
8Q(8K)
0.195;-22042.5
(89)(9T)
0.190;-20810.0
9(89K)
0.203;-23637.5
(89TK)
0.191;-28060.0
TQ(89)
0.147;-28857.5
K(89J)
0.226;-27262.5
Q(89Q)
0.243;-22042.5
KK(89)
0.240;-20447.5
99(8Q)
0.234;-24435.0
9(8TJ)
0.198;-29655.0
9K(8T)
0.188;-28060.0
(9T)(8K)
0.235;-22840.0
9T(8Q)
0.162;-28857.5
(8J)(9J)
0.215;-18417.5
8J(9J)
0.250;-23637.5
9J(8Q)
0.238;-28060.0
(8Q)(9Q)
0.203;-16822.5
8K(9Q)
0.166;-26465.0
8K(9K)
0.201;-20447.5
TQ(8T)
0.195;-22840.0
K(8TJ)
0.196;-26465.0
Q(8TQ)
0.251;-21245.0
KK(8T)
0.234;-19650.0
