AAAA
0.101;4885.0
5AAA
0.072;-565.6
9AAA
0.078;836.9
KAAA
0.090;2239.4
4A(2A)
0.035;-5123.8
(2A)(7A)
0.060;-1776.9
A(2TA)
0.046;-3020.0
QA(2A)
0.043;-2318.7
2A(4A)
0.040;-5123.8
26AA
0.027;-6717.5
AA(29)
0.049;-3370.6
2A(QA)
0.054;-2318.7
A(34A)
0.038;-4773.1
6A(3A)
0.043;-4071.9
(3A)(9A)
0.057;-725.0
A(3QA)
0.052;-1968.1
AA(34)
0.030;-4773.1
3A(7A)
0.036;-3721.3
39AA
0.035;-5315.0
AA(3Q)
0.067;-1968.1
(4A)(5A)
0.055;-1776.9
A(48A)
0.051;-3020.0
TA(4A)
0.068;-2318.7
(4A)(KA)
0.071;1028.1
46AA
0.020;-6016.3
AA(49)
0.049;-2669.4
4A(QA)
0.047;-1617.5
A(56A)
0.045;-3370.6
8A(5A)
0.042;-2669.4
(5A)(JA)
0.086;677.5
55AA
0.045;-3721.3
AA(58)
0.051;-2669.4
5A(JA)
0.052;-1617.5
5KAA
0.051;-3211.3
8A(6A)
0.055;-2318.7
(6A)(JA)
0.095;1028.1
66AA
0.047;-3020.0
AA(69)
0.041;-1968.1
6A(QA)
0.073;-916.3
A(78A)
0.055;-1968.1
TA(7A)
0.049;-1266.9
(7A)(KA)
0.084;2080.0
79AA
0.037;-3912.5
AA(7Q)
0.076;-565.6
(8A)(9A)
0.092;1028.1
A(8QA)
0.066;-215.0
AA(89)
0.069;-1266.9
8A(QA)
0.059;-215.0
A(9TA)
0.060;-565.6
QA(9A)
0.082;135.6
9A(JA)
0.054;-215.0
9KAA
0.065;-1808.8
QA(TA)
0.060;486.2
TA(QA)
0.068;486.2
A(JQA)
0.079;836.9
AA(JQ)
0.086;836.9
(QA)(KA)
0.109;3833.1
KKAA
0.082;1888.7
2(25A)
0.015;-8980.6
27(2A)
0.016;-8279.4
(2T)(2A)
0.033;-4932.5
2(2KA)
0.034;-6175.6
(236A)
0.009;-10574.4
(23TA)
0.012;-9171.9
33(2A)
0.013;-9331.2
(36)(2A)
0.014;-8279.4
3(29A)
0.015;-9522.5
3J(2A)
0.014;-8821.3
(245A)
0.009;-10574.4
(249A)
0.016;-9171.9
(24KA)
0.018;-7769.4
46(2A)
0.015;-10223.8
(49)(2A)
0.023;-6876.9
4(2QA)
0.013;-8120.0
6(25A)
0.013;-9873.1
T(25A)
0.019;-8470.6
5(26A)
0.009;-9873.1
58(2A)
0.012;-9171.9
(5J)(2A)
0.035;-5825.0
6(26A)
0.029;-7227.5
T(26A)
0.020;-8120.0
6(27A)
0.013;-9171.9
69(2A)
0.021;-8470.6
(6Q)(2A)
0.030;-5123.8
(279A)
0.018;-8120.0
(27KA)
0.026;-6717.5
79(2A)
0.023;-8120.0
(7Q)(2A)
0.048;-4773.1
(28TA)
0.015;-7418.8
88(2A)
0.025;-5825.0
(8J)(2A)
0.035;-4773.1
9(29A)
0.039;-5123.8
K(29A)
0.027;-6016.3
9(2QA)
0.029;-6366.9
J(2TA)
0.025;-6366.9
TJ(2A)
0.022;-6366.9
(2JQA)
0.040;-5665.6
J(2KA)
0.030;-5315.0
(QK)(2A)
0.052;-2669.4
22(4A)
0.012;-9331.2
226A
0.008;-10925.0
2A(29)
0.028;-7578.1
22(QA)
0.022;-6526.3
2(34A)
0.007;-11275.6
26(3A)
0.008;-10574.4
(29)(3A)
0.021;-7227.5
2(3QA)
0.018;-8470.6
A(234)
0.007;-11275.6
(23)(7A)
0.019;-7928.8
9A(23)
0.013;-9522.5
A(23Q)
0.019;-8470.6
2A(34)
0.012;-11275.6
2A(36)
0.009;-10574.4
2A(38)
0.014;-9873.1
2A(3T)
0.011;-9171.9
2A(3Q)
0.017;-8470.6
2(45A)
0.011;-10574.4
27(4A)
0.011;-9873.1
(2T)(4A)
0.023;-6526.3
2(4KA)
0.017;-7769.4
A(246)
0.011;-10223.8
(24)(9A)
0.022;-6876.9
JA(24)
0.016;-8470.6
24(5A)
0.009;-10574.4
24(7A)
0.015;-9873.1
24(9A)
0.016;-9171.9
24(JA)
0.020;-8470.6
24(KA)
0.021;-7769.4
26(5A)
0.016;-9873.1
(29)(5A)
0.024;-6526.3
2(5QA)
0.021;-7769.4
A(256)
0.010;-9873.1
(25)(9A)
0.021;-6526.3
JA(25)
0.015;-8120.0
25(6A)
0.011;-9873.1
25(8A)
0.020;-9171.9
25(TA)
0.016;-8470.6
25(QA)
0.017;-7769.4
(26)(6A)
0.034;-4932.5
2(69A)
0.016;-8470.6
2J(6A)
0.018;-7769.4
(26)(7A)
0.026;-6876.9
9A(26)
0.015;-8470.6
A(26Q)
0.024;-7418.8
2A(67)
0.018;-9171.9
2A(69)
0.018;-8470.6
2A(6J)
0.023;-7769.4
2A(6K)
0.023;-7068.1
(29)(7A)
0.026;-5825.0
2(7QA)
0.026;-7068.1
A(278)
0.020;-8470.6
(27)(JA)
0.040;-5123.8
KA(27)
0.026;-6717.5
2A(79)
0.021;-8120.0
2A(7J)
0.020;-7418.8
2A(7K)
0.031;-6717.5
(2T)(8A)
0.029;-5123.8
2(8KA)
0.029;-6366.9
A(28T)
0.017;-7418.8
(28)(KA)
0.039;-4071.9
28(TA)
0.027;-7418.8
28(QA)
0.021;-6717.5
(29)(9A)
0.047;-2828.8
2(9QA)
0.028;-6366.9
A(29T)
0.023;-7068.1
(29)(KA)
0.049;-3721.3
29(JA)
0.026;-6717.5
29(KA)
0.029;-6016.3
2J(TA)
0.027;-6366.9
(2T)(JA)
0.038;-4071.9
KA(2T)
0.022;-5665.6
2A(TQ)
0.026;-6016.3
2(JQA)
0.035;-5665.6
A(2JQ)
0.030;-5665.6
2A(JQ)
0.028;-5665.6
2(QKA)
0.029;-4964.4
2Q(KA)
0.032;-4964.4
33(3A)
0.025;-6685.6
(36)(3A)
0.035;-5633.8
3(39A)
0.032;-6876.9
3J(3A)
0.027;-6175.6
(345A)
0.011;-10223.8
(349A)
0.013;-8821.3
(34KA)
0.021;-7418.8
46(3A)
0.012;-9873.1
(49)(3A)
0.025;-6526.3
4(3QA)
0.023;-7769.4
6(35A)
0.011;-9522.5
T(35A)
0.024;-8120.0
5(36A)
0.014;-9522.5
58(3A)
0.015;-8821.3
(5J)(3A)
0.032;-5474.4
6(36A)
0.020;-6876.9
T(36A)
0.021;-7769.4
6(37A)
0.017;-8821.3
69(3A)
0.014;-8120.0
(6Q)(3A)
0.033;-4773.1
(379A)
0.017;-7769.4
(37KA)
0.026;-6366.9
79(3A)
0.016;-7769.4
(7Q)(3A)
0.045;-4422.5
(38TA)
0.024;-7068.1
88(3A)
0.026;-5474.4
(8J)(3A)
0.047;-4422.5
9(39A)
0.030;-4773.1
K(39A)
0.031;-5665.6
9(3QA)
0.028;-6016.3
J(3TA)
0.029;-6016.3
TJ(3A)
0.023;-6016.3
(3JQA)
0.041;-5315.0
J(3KA)
0.029;-4964.4
(QK)(3A)
0.041;-2318.7
33(5A)
0.022;-8279.4
337A
0.011;-9873.1
3A(3T)
0.020;-6526.3
33(KA)
0.036;-5474.4
3(46A)
0.014;-9873.1
38(4A)
0.017;-9171.9
(3J)(4A)
0.028;-5825.0
4A(34)
0.016;-8279.4
A(347)
0.012;-9522.5
(34)(TA)
0.028;-6175.6
QA(34)
0.016;-7769.4
345A
0.005;-12518.8
347A
0.008;-11817.5
349A
0.009;-11116.2
34JA
0.010;-10415.0
34KA
0.014;-9713.8
37(5A)
0.018;-9171.9
(3T)(5A)
0.023;-5825.0
3(5KA)
0.018;-7068.1
A(357)
0.016;-9171.9
(35)(TA)
0.029;-5825.0
QA(35)
0.022;-7418.8
356A
0.006;-11817.5
358A
0.007;-11116.2
35TA
0.011;-10415.0
35QA
0.015;-9713.8
(37)(6A)
0.026;-6526.3
3(6TA)
0.024;-7769.4
3Q(6A)
0.023;-7068.1
(36)(8A)
0.029;-6175.6
TA(36)
0.018;-7769.4
A(36K)
0.021;-6717.5
6A(38)
0.021;-8470.6
6A(3T)
0.019;-7769.4
6A(3Q)
0.025;-7068.1
37(7A)
0.025;-6175.6
(3T)(7A)
0.032;-5123.8
3(7KA)
0.029;-6366.9
A(379)
0.019;-7769.4
(37)(QA)
0.037;-4422.5
7A(38)
0.018;-8120.0
7A(3T)
0.018;-7418.8
7A(3Q)
0.019;-6717.5
38(8A)
0.025;-5474.4
(3J)(8A)
0.035;-4422.5
8A(38)
0.036;-5474.4
A(38J)
0.026;-6717.5
388A
0.025;-7769.4
38TA
0.017;-9363.1
38QA
0.018;-8661.9
(3T)(9A)
0.035;-4422.5
3(9KA)
0.023;-5665.6
A(39J)
0.030;-6366.9
399A
0.020;-7068.1
39JA
0.015;-8661.9
39KA
0.019;-7960.6
3Q(TA)
0.035;-5665.6
(3T)(QA)
0.045;-3370.6
TA(3J)
0.026;-6016.3
TA(3K)
0.031;-5315.0
3(JKA)
0.047;-4964.4
A(3JK)
0.032;-4964.4
JA(3K)
0.036;-4964.4
QA(3Q)
0.045;-2669.4
3QKA
0.024;-6908.7
45(4A)
0.018;-7578.1
(48)(4A)
0.035;-4231.3
4(4JA)
0.027;-5474.4
4K(4A)
0.027;-4773.1
(459A)
0.025;-8120.0
(45KA)
0.019;-6717.5
57(4A)
0.019;-8821.3
(5T)(4A)
0.031;-5474.4
5(4KA)
0.027;-6717.5
(469A)
0.024;-7769.4
(46KA)
0.021;-6366.9
68(4A)
0.018;-8120.0
(6J)(4A)
0.035;-4773.1
7(47A)
0.030;-5825.0
J(47A)
0.020;-6717.5
78(4A)
0.021;-7769.4
(7J)(4A)
0.036;-4422.5
8(48A)
0.034;-5123.8
Q(48A)
0.033;-6016.3
(8T)(4A)
0.040;-4422.5
8(4KA)
0.039;-5665.6
(49QA)
0.031;-5665.6
9(4JA)
0.021;-6016.3
9K(4A)
0.036;-5315.0
TT(4A)
0.037;-3721.3
(TK)(4A)
0.052;-2669.4
J(4QA)
0.029;-4964.4
K(4QA)
0.033;-4263.1
44(5A)
0.022;-7578.1
447A
0.015;-9171.9
4A(4T)
0.024;-5825.0
44(KA)
0.032;-4773.1
4(57A)
0.015;-8821.3
49(5A)
0.019;-8120.0
(4Q)(5A)
0.030;-4773.1
6A(45)
0.016;-9171.9
A(459)
0.018;-8120.0
(45)(QA)
0.036;-4773.1
5A(46)
0.012;-9171.9
5A(48)
0.018;-8470.6
5A(4T)
0.017;-7769.4
5A(4Q)
0.018;-7068.1
46(6A)
0.020;-6526.3
(49)(6A)
0.033;-5474.4
4(6QA)
0.018;-6717.5
A(467)
0.016;-8470.6
(46)(TA)
0.035;-5123.8
QA(46)
0.019;-6717.5
467A
0.009;-10765.6
469A
0.010;-10064.4
46JA
0.013;-9363.1
46KA
0.019;-8661.9
49(7A)
0.025;-7418.8
(4Q)(7A)
0.044;-4071.9
8A(47)
0.017;-7769.4
A(47J)
0.020;-6717.5
477A
0.017;-8120.0
479A
0.012;-9713.8
47JA
0.012;-9012.5
47KA
0.022;-8311.3
4T(8A)
0.023;-6717.5
(4K)(8A)
0.034;-3370.6
TA(48)
0.026;-6717.5
A(48K)
0.022;-5665.6
8A(4T)
0.017;-6717.5
8A(4Q)
0.029;-6016.3
49(9A)
0.037;-4422.5
(4Q)(9A)
0.057;-3370.6
TA(49)
0.032;-6366.9
A(49K)
0.032;-5315.0
9A(4J)
0.022;-6016.3
9A(4K)
0.034;-5315.0
4(TQA)
0.042;-5315.0
A(4TJ)
0.034;-5665.6
4TTA
0.026;-6016.3
4TQA
0.022;-7610.0
(4Q)(JA)
0.046;-2669.4
QA(4J)
0.035;-4964.4
4JQA
0.018;-7259.4
(4K)(QA)
0.042;-1968.1
QA(4K)
0.034;-4263.1
5(56A)
0.022;-6526.3
58(5A)
0.030;-5825.0
(5J)(5A)
0.061;-2478.1
6(56A)
0.034;-6175.6
T(56A)
0.023;-7068.1
6(57A)
0.016;-8120.0
69(5A)
0.024;-7418.8
(6Q)(5A)
0.045;-4071.9
(579A)
0.027;-7068.1
(57KA)
0.036;-5665.6
79(5A)
0.022;-7068.1
(7Q)(5A)
0.037;-3721.3
(58TA)
0.025;-6366.9
88(5A)
0.041;-4773.1
(8J)(5A)
0.041;-3721.3
9(59A)
0.034;-4071.9
K(59A)
0.031;-4964.4
9(5QA)
0.027;-5315.0
J(5TA)
0.028;-5315.0
TJ(5A)
0.035;-5315.0
(5JQA)
0.026;-4613.8
J(5KA)
0.031;-4263.1
(QK)(5A)
0.051;-1617.5
55(7A)
0.019;-6175.6
559A
0.026;-7769.4
5A(5Q)
0.028;-4422.5
(57)(6A)
0.036;-5825.0
5(6TA)
0.023;-7068.1
5Q(6A)
0.027;-6366.9
(56)(8A)
0.035;-5474.4
TA(56)
0.027;-7068.1
A(56K)
0.026;-6016.3
6A(58)
0.019;-7769.4
6A(5T)
0.019;-7068.1
6A(5Q)
0.031;-6366.9
57(7A)
0.035;-5474.4
(5T)(7A)
0.038;-4422.5
5(7KA)
0.033;-5665.6
A(579)
0.027;-7068.1
(57)(QA)
0.044;-3721.3
7A(58)
0.016;-7418.8
7A(5T)
0.023;-6717.5
7A(5Q)
0.024;-6016.3
58(8A)
0.034;-4773.1
(5J)(8A)
0.037;-3721.3
8A(58)
0.031;-4773.1
A(58J)
0.032;-6016.3
588A
0.020;-7068.1
58TA
0.016;-8661.9
58QA
0.026;-7960.6
(5T)(9A)
0.037;-3721.3
5(9KA)
0.042;-4964.4
A(59J)
0.032;-5665.6
599A
0.028;-6366.9
59JA
0.024;-7960.6
59KA
0.020;-7259.4
5Q(TA)
0.031;-4964.4
(5T)(QA)
0.048;-2669.4
TA(5J)
0.025;-5315.0
TA(5K)
0.029;-4613.8
5(JKA)
0.040;-4263.1
A(5JK)
0.034;-4263.1
JA(5K)
0.038;-4263.1
QA(5Q)
0.056;-1968.1
5QKA
0.028;-6207.5
67(6A)
0.031;-5474.4
(6T)(6A)
0.062;-2127.5
6(6KA)
0.039;-3370.6
(67TA)
0.026;-6366.9
77(6A)
0.030;-5123.8
(7T)(6A)
0.040;-4071.9
7(6KA)
0.043;-5315.0
(68JA)
0.027;-5665.6
(89)(6A)
0.043;-4071.9
8(6QA)
0.034;-5315.0
T(69A)
0.034;-5665.6
9(6TA)
0.025;-5665.6
9Q(6A)
0.035;-4964.4
Q(6TA)
0.035;-4613.8
(TQ)(6A)
0.057;-2318.7
(6JKA)
0.058;-3912.5
JK(6A)
0.039;-3912.5
K(6KA)
0.067;-916.3
668A
0.025;-7418.8
6A(6J)
0.030;-4071.9
(67)(7A)
0.038;-2828.8
6(7TA)
0.023;-6366.9
6Q(7A)
0.035;-5665.6
(67)(9A)
0.032;-4422.5
JA(67)
0.032;-6016.3
67(8A)
0.027;-7068.1
67(TA)
0.032;-6366.9
67(QA)
0.031;-5665.6
(68)(8A)
0.053;-2127.5
6(8JA)
0.030;-5665.6
6K(8A)
0.040;-4964.4
(68)(JA)
0.041;-3370.6
KA(68)
0.044;-4964.4
6A(8T)
0.040;-6016.3
6A(8Q)
0.031;-5315.0
6(9TA)
0.038;-5665.6
6Q(9A)
0.037;-4964.4
(69)(JA)
0.050;-3020.0
KA(69)
0.039;-4613.8
6A(9J)
0.033;-5315.0
6A(9K)
0.041;-4613.8
(6Q)(TA)
0.057;-2318.7
JA(6T)
0.037;-4964.4
6T(JA)
0.031;-4964.4
6T(KA)
0.037;-4263.1
6Q(JA)
0.034;-4263.1
(6J)(KA)
0.050;-1617.5
6J(KA)
0.039;-3912.5
6K(QA)
0.050;-3561.9
6A(QK)
0.044;-3561.9
(78)(7A)
0.043;-2127.5
7(7JA)
0.038;-3370.6
7K(7A)
0.050;-2669.4
(78QA)
0.043;-4964.4
8(7TA)
0.028;-5665.6
8Q(7A)
0.033;-4964.4
J(79A)
0.031;-4964.4
9T(7A)
0.025;-5315.0
(9K)(7A)
0.057;-1968.1
K(7TA)
0.039;-3912.5
T(7KA)
0.037;-3912.5
JJ(7A)
0.042;-1968.1
(7QKA)
0.038;-3211.3
777A
0.045;-4773.1
7A(7T)
0.056;-3721.3
77(KA)
0.057;-2669.4
7(8TA)
0.024;-5665.6
7Q(8A)
0.036;-4964.4
(78)(TA)
0.038;-3370.6
QA(78)
0.036;-4964.4
789A
0.018;-8311.3
78JA
0.021;-7610.0
78KA
0.027;-6908.7
7J(9A)
0.045;-4964.4
(79)(TA)
0.046;-3020.0
QA(79)
0.034;-4613.8
79TA
0.023;-7610.0
79QA
0.029;-6908.7
(7J)(TA)
0.059;-2318.7
TA(7T)
0.053;-2669.4
A(7TK)
0.041;-3912.5
TA(7Q)
0.033;-4263.1
7J(JA)
0.052;-1968.1
(7J)(QA)
0.055;-1617.5
JA(7Q)
0.037;-3912.5
7Q(QA)
0.056;-1266.9
7QQA
0.038;-3561.9
7KKA
0.044;-2860.6
8(8JA)
0.044;-2669.4
8K(8A)
0.058;-1968.1
(89KA)
0.035;-3912.5
9J(8A)
0.035;-4613.8
(8TJA)
0.033;-4263.1
(TJ)(8A)
0.049;-1968.1
J(8JA)
0.053;-1617.5
JQ(8A)
0.046;-3561.9
Q(8KA)
0.036;-2860.6
889A
0.028;-5665.6
8A(8Q)
0.050;-2318.7
(8T)(9A)
0.047;-2669.4
8(9KA)
0.048;-3912.5
A(89J)
0.034;-4613.8
899A
0.028;-5315.0
89JA
0.027;-6908.7
89KA
0.026;-6207.5
8Q(TA)
0.036;-3912.5
(8T)(QA)
0.065;-1617.5
TA(8J)
0.033;-4263.1
TA(8K)
0.044;-3561.9
8(JKA)
0.045;-3211.3
A(8JK)
0.051;-3211.3
JA(8K)
0.041;-3211.3
QA(8Q)
0.053;-916.3
8QKA
0.037;-5155.6
9T(9A)
0.063;-2318.7
(9K)(9A)
0.076;1028.1
K(9TA)
0.053;-3211.3
T(9KA)
0.041;-3211.3
JJ(9A)
0.059;-1266.9
(9QKA)
0.049;-2510.0
999A
0.050;-2669.4
9A(9Q)
0.068;-1617.5
(9J)(TA)
0.061;-1617.5
TA(9T)
0.061;-1968.1
A(9TK)
0.044;-3211.3
TA(9Q)
0.050;-3561.9
9J(JA)
0.066;-1266.9
(9J)(QA)
0.080;-916.3
JA(9Q)
0.041;-3211.3
9Q(QA)
0.068;-565.6
9QQA
0.054;-2860.6
9KKA
0.052;-2159.4
T(TKA)
0.052;-565.6
JJ(TA)
0.069;-916.3
(TQKA)
0.072;-2159.4
TTTA
0.045;-1617.5
TA(TK)
0.066;-565.6
(TK)(JA)
0.055;-215.0
KA(TJ)
0.046;-2510.0
TA(JK)
0.039;-2510.0
(TQ)(KA)
0.075;135.6
(TK)(KA)
0.119;2781.2
J(JKA)
0.087;135.6
(QK)(JA)
0.064;486.3
JJ(KA)
0.068;135.6
QA(JQ)
0.066;135.6
JQKA
0.035;-4103.8
QK(QA)
0.059;836.9
QK(KA)
0.077;1187.5
22(24)
0.009;-11243.8
22(28)
0.014;-9841.2
22(2Q)
0.020;-8438.8
24(23)
0.004;-13188.1
(23)(27)
0.009;-9841.3
2(23T)
0.009;-11084.4
2Q(23)
0.012;-10383.1
23(25)
0.005;-12837.5
2237
0.003;-14431.3
22(3T)
0.011;-11084.4
23(2K)
0.010;-10032.5
2(246)
0.005;-12136.2
28(24)
0.006;-11435.0
(24)(2J)
0.018;-8088.1
2244
0.005;-12837.5
22(47)
0.008;-11785.6
24(2T)
0.008;-10733.8
224Q
0.006;-12327.5
26(25)
0.007;-11785.6
(25)(29)
0.015;-8438.8
2(25Q)
0.012;-9681.9
22(56)
0.007;-11785.6
25(29)
0.008;-10733.8
225J
0.006;-12327.5
26(26)
0.015;-9140.0
(26)(29)
0.014;-8088.1
2(26Q)
0.012;-9331.2
22(67)
0.009;-11084.4
26(2T)
0.012;-10032.5
226Q
0.008;-11626.2
28(27)
0.012;-10383.1
(27)(2J)
0.022;-7036.3
2277
0.011;-10733.8
22(7T)
0.013;-9681.9
27(2K)
0.018;-8630.0
2(28T)
0.017;-9331.2
2Q(28)
0.017;-8630.0
28(2T)
0.013;-9331.2
228Q
0.007;-10925.0
2T(29)
0.011;-8980.6
(29)(2K)
0.030;-5633.8
229J
0.012;-10925.0
2T(2T)
0.028;-6335.0
(2T)(2K)
0.032;-5283.1
22TQ
0.013;-10223.8
2Q(2J)
0.019;-7578.1
2J(2K)
0.023;-7227.5
22QQ
0.020;-7227.5
3(234)
0.005;-12837.5
36(23)
0.005;-12136.2
(23)(39)
0.019;-8789.4
3(23Q)
0.010;-10032.5
5(234)
0.003;-14431.3
9(234)
0.005;-13028.8
K(234)
0.008;-11626.2
4(237)
0.003;-13730.0
49(23)
0.003;-13028.8
(23)(4Q)
0.012;-9681.9
(2357)
0.006;-13379.4
(235J)
0.007;-11976.9
(23)(56)
0.008;-11435.0
5(239)
0.005;-12678.1
5J(23)
0.006;-11976.9
(2367)
0.006;-13028.8
(236J)
0.008;-11626.2
(23)(67)
0.011;-10733.8
6(23T)
0.007;-11976.9
6Q(23)
0.008;-11275.6
9(237)
0.006;-11976.9
K(237)
0.008;-10574.4
7(23T)
0.009;-11626.2
7Q(23)
0.010;-10925.0
T(238)
0.007;-11275.6
8(239)
0.010;-11626.2
8J(23)
0.011;-10925.0
(239T)
0.010;-10925.0
99(23)
0.015;-8980.6
(23)(9Q)
0.021;-7928.8
(23TQ)
0.010;-9873.1
T(23Q)
0.010;-9873.1
Q(23J)
0.012;-9522.5
(23)(JK)
0.028;-6876.9
QK(23)
0.016;-8821.3
23(35)
0.008;-12486.9
33(28)
0.009;-11435.0
233T
0.005;-13028.8
23(3K)
0.012;-9681.9
(24)(36)
0.008;-11785.6
3(249)
0.004;-13028.8
3J(24)
0.005;-12327.5
(34)(25)
0.006;-12136.2
27(34)
0.003;-13730.0
2(34T)
0.004;-12678.1
(34)(2K)
0.014;-9331.2
34(26)
0.003;-14080.6
34(28)
0.004;-13379.4
34(2T)
0.005;-12678.1
34(2Q)
0.009;-11976.9
(25)(35)
0.011;-9490.6
3(258)
0.006;-13028.8
3T(25)
0.007;-12327.5
(25)(3K)
0.017;-8980.6
27(35)
0.005;-13379.4
2(35T)
0.006;-12327.5
(35)(2K)
0.018;-8980.6
35(27)
0.005;-13379.4
35(29)
0.005;-12678.1
35(2J)
0.006;-11976.9
35(2K)
0.009;-11275.6
37(26)
0.005;-13028.8
(26)(3T)
0.014;-9681.9
3(26K)
0.009;-10925.0
2(368)
0.005;-12678.1
(36)(2J)
0.016;-9331.2
2K(36)
0.009;-10925.0
23(68)
0.005;-12678.1
23(6T)
0.008;-11976.9
23(6Q)
0.008;-11275.6
3(278)
0.006;-12327.5
3T(27)
0.008;-11626.2
(27)(3K)
0.021;-8279.4
29(37)
0.008;-11976.9
2(37Q)
0.008;-10925.0
23(78)
0.006;-12327.5
23(7T)
0.007;-11626.2
23(7Q)
0.008;-10925.0
3(289)
0.010;-11626.2
3J(28)
0.009;-10925.0
(38)(29)
0.012;-9331.2
2J(38)
0.010;-10925.0
38(29)
0.007;-11626.2
38(2J)
0.010;-10925.0
38(2K)
0.013;-10223.8
3T(29)
0.011;-10925.0
(29)(3K)
0.026;-7578.1
2J(39)
0.009;-10574.4
39(2T)
0.011;-10925.0
39(2Q)
0.016;-10223.8
(2T)(3T)
0.025;-5984.4
3(2TK)
0.016;-9522.5
2(3TQ)
0.009;-9873.1
23(TJ)
0.015;-10223.8
23(TK)
0.012;-9522.5
(2J)(3K)
0.018;-6876.9
2K(3J)
0.011;-9171.9
23(JK)
0.014;-9171.9
(3Q)(2K)
0.026;-6526.3
(2K)(3K)
0.034;-3880.6
4(246)
0.011;-11435.0
48(24)
0.008;-10733.8
(24)(4J)
0.020;-7386.9
5(245)
0.006;-11435.0
9(245)
0.006;-12327.5
K(245)
0.010;-10925.0
5(248)
0.006;-12678.1
5T(24)
0.009;-11976.9
(24)(5K)
0.020;-8630.0
9(246)
0.007;-11976.9
K(246)
0.012;-10574.4
6(249)
0.006;-11976.9
6J(24)
0.007;-11275.6
(2478)
0.007;-11976.9
(247Q)
0.010;-10574.4
7(249)
0.007;-11626.2
7J(24)
0.011;-10925.0
(2489)
0.008;-11275.6
(248K)
0.009;-9873.1
8T(24)
0.010;-10925.0
(24)(8K)
0.026;-7578.1
Q(249)
0.012;-9873.1
(24)(9J)
0.016;-7928.8
T(24T)
0.018;-7928.8
T(24J)
0.013;-9873.1
TK(24)
0.015;-9171.9
(24)(JQ)
0.025;-6876.9
QQ(24)
0.023;-6526.3
24(45)
0.007;-11785.6
44(28)
0.013;-10733.8
244T
0.004;-12327.5
24(4K)
0.017;-8980.6
(25)(47)
0.009;-10733.8
4(25T)
0.006;-11976.9
4Q(25)
0.008;-11275.6
(45)(27)
0.007;-10733.8
29(45)
0.005;-12327.5
2(45Q)
0.008;-11275.6
24(56)
0.003;-13379.4
24(58)
0.006;-12678.1
24(5T)
0.008;-11976.9
24(5Q)
0.008;-11275.6
4(267)
0.007;-12678.1
49(26)
0.008;-11976.9
(26)(4Q)
0.018;-8630.0
27(46)
0.006;-12678.1
2(46T)
0.010;-11626.2
(46)(2K)
0.019;-8279.4
46(28)
0.005;-12327.5
46(2T)
0.006;-11626.2
46(2Q)
0.012;-10925.0
(27)(47)
0.017;-7737.5
4(27T)
0.007;-11275.6
4Q(27)
0.013;-10574.4
(47)(29)
0.016;-9331.2
2J(47)
0.007;-10925.0
47(28)
0.006;-11976.9
47(2T)
0.009;-11275.6
47(2Q)
0.012;-10574.4
(28)(48)
0.026;-7036.3
4(28J)
0.011;-10574.4
4K(28)
0.013;-9873.1
(48)(2J)
0.014;-8279.4
2K(48)
0.013;-9873.1
24(8T)
0.013;-10925.0
24(8Q)
0.013;-10223.8
4(29T)
0.010;-10574.4
4Q(29)
0.014;-9873.1
(49)(2J)
0.018;-7928.8
2K(49)
0.016;-9522.5
24(9J)
0.014;-10223.8
24(9K)
0.012;-9522.5
(2T)(4Q)
0.023;-7227.5
2J(4T)
0.014;-9873.1
4T(2J)
0.015;-9873.1
4T(2K)
0.011;-9171.9
4Q(2J)
0.013;-9171.9
(4J)(2K)
0.025;-6526.3
4J(2K)
0.013;-8821.3
4K(2Q)
0.019;-8470.6
24(QK)
0.018;-8470.6
(25)(56)
0.017;-8438.8
5(259)
0.016;-9681.9
5J(25)
0.014;-8980.6
(2567)
0.005;-12327.5
(256J)
0.008;-10925.0
(25)(67)
0.010;-10032.5
6(25T)
0.007;-11275.6
6Q(25)
0.011;-10574.4
9(257)
0.009;-11275.6
K(257)
0.012;-9873.1
7(25T)
0.009;-10925.0
7Q(25)
0.012;-10223.8
T(258)
0.015;-10574.4
8(259)
0.007;-10925.0
8J(25)
0.009;-10223.8
(259T)
0.011;-10223.8
99(25)
0.022;-8279.4
(25)(9Q)
0.024;-7227.5
(25TQ)
0.017;-9171.9
T(25Q)
0.015;-9171.9
Q(25J)
0.022;-8821.3
(25)(JK)
0.036;-6175.6
QK(25)
0.018;-8120.0
25(57)
0.009;-10383.1
55(2T)
0.012;-9331.2
255Q
0.011;-10925.0
57(26)
0.006;-12327.5
(26)(5T)
0.017;-8980.6
5(26K)
0.014;-10223.8
2(568)
0.006;-11976.9
(56)(2J)
0.020;-8630.0
2K(56)
0.012;-10223.8
25(68)
0.005;-11976.9
25(6T)
0.006;-11275.6
25(6Q)
0.009;-10574.4
5(278)
0.008;-11626.2
5T(27)
0.009;-10925.0
(27)(5K)
0.020;-7578.1
29(57)
0.009;-11275.6
2(57Q)
0.012;-10223.8
25(78)
0.006;-11626.2
25(7T)
0.012;-10925.0
25(7Q)
0.010;-10223.8
5(289)
0.008;-10925.0
5J(28)
0.013;-10223.8
(58)(29)
0.012;-8630.0
2J(58)
0.013;-10223.8
58(29)
0.010;-10925.0
58(2J)
0.012;-10223.8
58(2K)
0.013;-9522.5
5T(29)
0.010;-10223.8
(29)(5K)
0.027;-6876.9
2J(59)
0.015;-9873.1
59(2T)
0.013;-10223.8
59(2Q)
0.017;-9522.5
(2T)(5T)
0.033;-5283.1
5(2TK)
0.014;-8821.3
2(5TQ)
0.015;-9171.9
25(TJ)
0.016;-9522.5
25(TK)
0.019;-8821.3
(2J)(5K)
0.027;-6175.6
2K(5J)
0.020;-8470.6
25(JK)
0.016;-8470.6
(5Q)(2K)
0.027;-5825.0
(2K)(5K)
0.048;-3179.4
6(268)
0.015;-9331.2
6T(26)
0.013;-8630.0
(26)(6K)
0.028;-5283.1
T(267)
0.011;-10574.4
7(268)
0.008;-11275.6
7T(26)
0.010;-10574.4
(26)(7K)
0.025;-7227.5
J(268)
0.012;-9873.1
89(26)
0.011;-10574.4
(26)(8Q)
0.023;-7227.5
(269J)
0.014;-9522.5
(26)(9T)
0.021;-7578.1
9(26K)
0.016;-8821.3
(26TK)
0.021;-8470.6
TQ(26)
0.017;-8821.3
K(26J)
0.014;-8120.0
Q(26Q)
0.028;-5825.0
KK(26)
0.037;-5123.8
66(29)
0.014;-8980.6
266J
0.011;-10574.4
67(27)
0.015;-9331.2
(27)(6T)
0.022;-8279.4
6(27K)
0.013;-9522.5
2(679)
0.012;-10925.0
(67)(2Q)
0.015;-7578.1
27(68)
0.007;-11275.6
27(6T)
0.009;-10574.4
27(6Q)
0.009;-9873.1
68(28)
0.016;-8630.0
(28)(6J)
0.021;-7578.1
28(68)
0.019;-8630.0
2(68J)
0.011;-9873.1
2688
0.013;-10925.0
268T
0.005;-12518.8
268Q
0.007;-11817.5
(29)(6T)
0.019;-7578.1
6(29K)
0.016;-8821.3
2(69J)
0.016;-9522.5
2699
0.010;-10223.8
269J
0.005;-11817.5
269K
0.009;-11116.2
6Q(2T)
0.013;-8821.3
(6T)(2Q)
0.029;-6526.3
2T(6J)
0.018;-9171.9
2T(6K)
0.021;-8470.6
6(2JK)
0.019;-8120.0
2(6JK)
0.022;-8120.0
2J(6K)
0.018;-8120.0
2Q(6Q)
0.023;-5825.0
26QK
0.013;-10064.4
78(27)
0.018;-8630.0
(27)(7J)
0.028;-5283.1
8(278)
0.019;-8279.4
Q(278)
0.013;-9171.9
(27)(8T)
0.024;-7578.1
8(27K)
0.015;-8821.3
(279Q)
0.015;-8821.3
9(27J)
0.015;-9171.9
9K(27)
0.021;-8470.6
TT(27)
0.020;-6876.9
(27)(TK)
0.038;-5825.0
J(27Q)
0.020;-8120.0
K(27Q)
0.023;-7418.8
77(28)
0.020;-8630.0
277T
0.016;-10223.8
27(7K)
0.026;-6876.9
(28)(7T)
0.021;-7578.1
7(28K)
0.018;-8821.3
2(78T)
0.013;-9873.1
(78)(2K)
0.027;-6526.3
78(2T)
0.014;-9873.1
78(2Q)
0.012;-9171.9
(29)(79)
0.033;-5283.1
7(29Q)
0.012;-8821.3
2(79T)
0.017;-9522.5
(79)(2K)
0.028;-6175.6
79(2J)
0.013;-9171.9
79(2K)
0.019;-8470.6
7J(2T)
0.022;-8821.3
(7T)(2J)
0.023;-6526.3
2K(7T)
0.021;-8120.0
27(TQ)
0.016;-8470.6
7(2JQ)
0.016;-8120.0
2(7JQ)
0.025;-8120.0
27(JQ)
0.020;-8120.0
7(2QK)
0.026;-7418.8
7Q(2K)
0.025;-7418.8
88(28)
0.024;-5633.8
(28)(8J)
0.044;-4581.9
9(289)
0.030;-7227.5
K(289)
0.022;-8120.0
9(28Q)
0.015;-8470.6
J(28T)
0.014;-8470.6
TJ(28)
0.023;-8470.6
(28JQ)
0.021;-7769.4
J(28K)
0.025;-7418.8
(28)(QK)
0.035;-4773.1
88(2T)
0.022;-7227.5
288Q
0.013;-8821.3
8T(29)
0.014;-9171.9
(29)(8K)
0.029;-5825.0
2J(89)
0.019;-8821.3
89(2T)
0.015;-9171.9
89(2Q)
0.017;-8470.6
(2T)(8T)
0.038;-4231.3
8(2TK)
0.017;-7769.4
2(8TQ)
0.014;-8120.0
28(TJ)
0.015;-8470.6
28(TK)
0.017;-7769.4
(2J)(8K)
0.028;-5123.8
2K(8J)
0.027;-7418.8
28(JK)
0.017;-7418.8
(8Q)(2K)
0.043;-4773.1
(2K)(8K)
0.050;-2127.5
9(29J)
0.032;-6175.6
9K(29)
0.031;-5474.4
TT(29)
0.023;-6175.6
(29)(TK)
0.027;-5123.8
J(29Q)
0.023;-7418.8
K(29Q)
0.024;-6717.5
99(2T)
0.021;-6526.3
299Q
0.019;-8120.0
9J(2T)
0.020;-8120.0
(9T)(2J)
0.025;-5825.0
2K(9T)
0.017;-7418.8
29(TQ)
0.022;-7769.4
9(2JQ)
0.025;-7418.8
2(9JQ)
0.023;-7418.8
29(JQ)
0.020;-7418.8
9(2QK)
0.025;-6717.5
9Q(2K)
0.027;-6717.5
TT(2T)
0.038;-3530.0
(2T)(TK)
0.053;-2478.1
J(2TQ)
0.021;-7068.1
K(2TQ)
0.023;-6366.9
TT(2J)
0.033;-5474.4
2TTK
0.018;-7068.1
TK(2J)
0.021;-6717.5
2TJJ
0.016;-7418.8
2TJK
0.015;-9012.5
2(TQK)
0.019;-6366.9
TK(2K)
0.032;-3721.3
(2J)(JK)
0.060;-1776.9
QK(2J)
0.025;-6016.3
2J(JK)
0.048;-4071.9
(JQ)(2K)
0.048;-3721.3
(2K)(JK)
0.061;-1075.6
K(2QK)
0.046;-3020.0
2K(QK)
0.048;-3020.0
3335
0.008;-12136.2
3339
0.012;-10733.8
333K
0.015;-9331.2
36(34)
0.006;-11435.0
(34)(39)
0.025;-8088.1
3(34Q)
0.013;-9331.2
33(45)
0.006;-11785.6
34(38)
0.008;-10733.8
334T
0.005;-12327.5
33(4K)
0.017;-8980.6
(35)(37)
0.018;-8438.8
3(35T)
0.011;-9681.9
3Q(35)
0.016;-8980.6
35(37)
0.008;-10733.8
3359
0.006;-12327.5
33(5Q)
0.017;-8980.6
(36)(37)
0.021;-8088.1
3(36T)
0.011;-9331.2
3Q(36)
0.018;-8630.0
36(38)
0.015;-10032.5
336T
0.007;-11626.2
33(6K)
0.020;-8279.4
(37)(39)
0.024;-7036.3
3(37Q)
0.015;-8279.4
33(78)
0.012;-9681.9
37(3J)
0.013;-8630.0
337K
0.012;-10223.8
3T(38)
0.014;-8630.0
(38)(3K)
0.028;-5283.1
338T
0.010;-10925.0
33(8K)
0.017;-7578.1
(39)(3J)
0.028;-5633.8
3399
0.014;-8630.0
33(9Q)
0.022;-7578.1
(3T)(3J)
0.031;-5283.1
33TT
0.017;-7928.8
33(TK)
0.022;-6876.9
(3J)(3K)
0.040;-4231.3
33JK
0.016;-8821.3
33(QK)
0.026;-6175.6
45(34)
0.008;-11435.0
(34)(48)
0.024;-8088.1
4(34J)
0.013;-9331.2
4K(34)
0.019;-8630.0
(3459)
0.008;-11976.9
(345K)
0.011;-10574.4
57(34)
0.006;-12678.1
(34)(5T)
0.014;-9331.2
5(34K)
0.011;-10574.4
(3469)
0.006;-11626.2
(346K)
0.011;-10223.8
68(34)
0.008;-11976.9
(34)(6J)
0.017;-8630.0
7(347)
0.014;-9681.9
J(347)
0.013;-10574.4
78(34)
0.009;-11626.2
(34)(7J)
0.016;-8279.4
8(348)
0.022;-8980.6
Q(348)
0.010;-9873.1
(34)(8T)
0.019;-8279.4
8(34K)
0.016;-9522.5
(349Q)
0.010;-9522.5
9(34J)
0.013;-9873.1
9K(34)
0.017;-9171.9
TT(34)
0.017;-7578.1
(34)(TK)
0.022;-6526.3
J(34Q)
0.014;-8821.3
K(34Q)
0.017;-8120.0
44(35)
0.007;-11435.0
3447
0.004;-13028.8
34(4T)
0.012;-9681.9
44(3K)
0.022;-8630.0
4(357)
0.005;-12678.1
49(35)
0.006;-11976.9
(35)(4Q)
0.020;-8630.0
36(45)
0.004;-13028.8
3(459)
0.008;-11976.9
(45)(3Q)
0.015;-8630.0
35(46)
0.005;-13028.8
35(48)
0.008;-12327.5
35(4T)
0.008;-11626.2
35(4Q)
0.010;-10925.0
46(36)
0.009;-10383.1
(36)(49)
0.013;-9331.2
4(36Q)
0.012;-10574.4
3(467)
0.007;-12327.5
(46)(3T)
0.013;-8980.6
3Q(46)
0.014;-10574.4
3467
0.003;-14622.5
3469
0.003;-13921.3
346J
0.005;-13220.0
346K
0.007;-12518.8
49(37)
0.007;-11275.6
(37)(4Q)
0.026;-7928.8
38(47)
0.009;-11626.2
3(47J)
0.012;-10574.4
3477
0.006;-11976.9
3479
0.005;-13570.6
347J
0.006;-12869.4
347K
0.009;-12168.1
4T(38)
0.007;-10574.4
(38)(4K)
0.019;-7227.5
3T(48)
0.010;-10574.4
3(48K)
0.013;-9522.5
38(4T)
0.010;-10574.4
38(4Q)
0.012;-9873.1
49(39)
0.022;-8279.4
(39)(4Q)
0.022;-7227.5
3T(49)
0.010;-10223.8
3(49K)
0.017;-9171.9
39(4J)
0.013;-9873.1
39(4K)
0.020;-9171.9
4(3TQ)
0.012;-9171.9
3(4TJ)
0.015;-9522.5
34TT
0.013;-9873.1
34TQ
0.009;-11466.9
(3J)(4Q)
0.027;-6526.3
3Q(4J)
0.016;-8821.3
34JQ
0.010;-11116.2
(3Q)(4K)
0.022;-5825.0
3Q(4K)
0.023;-8120.0
5(356)
0.015;-10383.1
58(35)
0.012;-9681.9
(35)(5J)
0.022;-6335.0
6(356)
0.009;-10032.5
T(356)
0.008;-10925.0
6(357)
0.007;-11976.9
69(35)
0.009;-11275.6
(35)(6Q)
0.017;-7928.8
(3579)
0.008;-10925.0
(357K)
0.016;-9522.5
79(35)
0.010;-10925.0
(35)(7Q)
0.017;-7578.1
(358T)
0.011;-10223.8
88(35)
0.020;-8630.0
(35)(8J)
0.021;-7578.1
9(359)
0.015;-7928.8
K(359)
0.018;-8821.3
9(35Q)
0.016;-9171.9
J(35T)
0.017;-9171.9
TJ(35)
0.015;-9171.9
(35JQ)
0.018;-8470.6
J(35K)
0.020;-8120.0
(35)(QK)
0.024;-5474.4
55(37)
0.012;-10032.5
3559
0.006;-11626.2
35(5Q)
0.017;-8279.4
(36)(57)
0.017;-9681.9
5(36T)
0.011;-10925.0
5Q(36)
0.011;-10223.8
(56)(38)
0.011;-9331.2
3T(56)
0.009;-10925.0
3(56K)
0.012;-9873.1
36(58)
0.008;-11626.2
36(5T)
0.010;-10925.0
36(5Q)
0.010;-10223.8
57(37)
0.014;-9331.2
(37)(5T)
0.017;-8279.4
5(37K)
0.012;-9522.5
3(579)
0.010;-10925.0
(57)(3Q)
0.021;-7578.1
37(58)
0.009;-11275.6
37(5T)
0.011;-10574.4
37(5Q)
0.011;-9873.1
58(38)
0.014;-8630.0
(38)(5J)
0.023;-7578.1
38(58)
0.018;-8630.0
3(58J)
0.010;-9873.1
3588
0.010;-10925.0
358T
0.008;-12518.8
358Q
0.007;-11817.5
(39)(5T)
0.017;-7578.1
5(39K)
0.013;-8821.3
3(59J)
0.013;-9522.5
3599
0.010;-10223.8
359J
0.008;-11817.5
359K
0.008;-11116.2
5Q(3T)
0.018;-8821.3
(5T)(3Q)
0.020;-6526.3
3T(5J)
0.015;-9171.9
3T(5K)
0.019;-8470.6
5(3JK)
0.021;-8120.0
3(5JK)
0.018;-8120.0
3J(5K)
0.014;-8120.0
3Q(5Q)
0.027;-5825.0
35QK
0.013;-10064.4
67(36)
0.014;-9331.2
(36)(6T)
0.035;-5984.4
6(36K)
0.021;-7227.5
(367T)
0.014;-10223.8
77(36)
0.019;-8980.6
(36)(7T)
0.021;-7928.8
7(36K)
0.013;-9171.9
(368J)
0.013;-9522.5
(36)(89)
0.020;-7928.8
8(36Q)
0.017;-9171.9
T(369)
0.015;-9522.5
9(36T)
0.012;-9522.5
9Q(36)
0.016;-8821.3
Q(36T)
0.019;-8470.6
(36)(TQ)
0.030;-6175.6
(36JK)
0.020;-7769.4
JK(36)
0.021;-7769.4
K(36K)
0.035;-4773.1
3668
0.007;-11275.6
36(6J)
0.019;-7928.8
(37)(67)
0.030;-6685.6
6(37T)
0.011;-10223.8
6Q(37)
0.013;-9522.5
(67)(39)
0.020;-8279.4
3J(67)
0.011;-9873.1
67(38)
0.007;-10925.0
67(3T)
0.012;-10223.8
67(3Q)
0.012;-9522.5
(38)(68)
0.038;-5984.4
6(38J)
0.012;-9522.5
6K(38)
0.011;-8821.3
(68)(3J)
0.019;-7227.5
3K(68)
0.021;-8821.3
36(8T)
0.010;-9873.1
36(8Q)
0.013;-9171.9
6(39T)
0.012;-9522.5
6Q(39)
0.018;-8821.3
(69)(3J)
0.027;-6876.9
3K(69)
0.018;-8470.6
36(9J)
0.017;-9171.9
36(9K)
0.012;-8470.6
(3T)(6Q)
0.033;-6175.6
3J(6T)
0.018;-8821.3
6T(3J)
0.016;-8821.3
6T(3K)
0.015;-8120.0
6Q(3J)
0.023;-8120.0
(6J)(3K)
0.030;-5474.4
6J(3K)
0.022;-7769.4
6K(3Q)
0.020;-7418.8
36(QK)
0.020;-7418.8
(37)(78)
0.026;-5984.4
7(37J)
0.026;-7227.5
7K(37)
0.025;-6526.3
(378Q)
0.020;-8821.3
8(37T)
0.016;-9522.5
8Q(37)
0.015;-8821.3
J(379)
0.016;-8821.3
9T(37)
0.012;-9171.9
(37)(9K)
0.026;-5825.0
K(37T)
0.020;-7769.4
T(37K)
0.021;-7769.4
JJ(37)
0.021;-5825.0
(37QK)
0.017;-7068.1
3777
0.012;-8630.0
37(7T)
0.014;-7578.1
77(3K)
0.031;-6526.3
7(38T)
0.011;-9522.5
7Q(38)
0.016;-8821.3
(78)(3T)
0.025;-7227.5
3Q(78)
0.021;-8821.3
3789
0.005;-12168.1
378J
0.008;-11466.9
378K
0.010;-10765.6
7J(39)
0.014;-8821.3
(79)(3T)
0.023;-6876.9
3Q(79)
0.018;-8470.6
379T
0.007;-11466.9
379Q
0.009;-10765.6
(3T)(7J)
0.027;-6175.6
3T(7T)
0.020;-6526.3
3(7TK)
0.016;-7769.4
3T(7Q)
0.024;-8120.0
7J(3J)
0.028;-5825.0
(7J)(3Q)
0.028;-5474.4
3J(7Q)
0.017;-7769.4
7Q(3Q)
0.033;-5123.8
37QQ
0.017;-7418.8
37KK
0.024;-6717.5
8(38J)
0.025;-6526.3
8K(38)
0.039;-5825.0
(389K)
0.020;-7769.4
9J(38)
0.016;-8470.6
(38TJ)
0.016;-8120.0
(38)(TJ)
0.030;-5825.0
J(38J)
0.024;-5474.4
JQ(38)
0.024;-7418.8
Q(38K)
0.022;-6717.5
3889
0.016;-9522.5
38(8Q)
0.029;-6175.6
(39)(8T)
0.027;-6526.3
8(39K)
0.016;-7769.4
3(89J)
0.017;-8470.6
3899
0.012;-9171.9
389J
0.011;-10765.6
389K
0.013;-10064.4
8Q(3T)
0.020;-7769.4
(8T)(3Q)
0.035;-5474.4
3T(8J)
0.025;-8120.0
3T(8K)
0.019;-7418.8
8(3JK)
0.029;-7068.1
3(8JK)
0.023;-7068.1
3J(8K)
0.028;-7068.1
3Q(8Q)
0.026;-4773.1
38QK
0.017;-9012.5
9T(39)
0.033;-6175.6
(39)(9K)
0.049;-2828.8
K(39T)
0.031;-7068.1
T(39K)
0.022;-7068.1
JJ(39)
0.042;-5123.8
(39QK)
0.023;-6366.9
3999
0.031;-6526.3
39(9Q)
0.039;-5474.4
(3T)(9J)
0.030;-5474.4
3T(9T)
0.030;-5825.0
3(9TK)
0.027;-7068.1
3T(9Q)
0.021;-7418.8
9J(3J)
0.028;-5123.8
(9J)(3Q)
0.028;-4773.1
3J(9Q)
0.020;-7068.1
9Q(3Q)
0.039;-4422.5
39QQ
0.027;-6717.5
39KK
0.033;-6016.3
T(3TK)
0.034;-4422.5
JJ(3T)
0.037;-4773.1
(3TQK)
0.030;-6016.3
3TTT
0.032;-5474.4
3T(TK)
0.039;-4422.5
(3J)(TK)
0.036;-4071.9
3K(TJ)
0.034;-6366.9
3T(JK)
0.024;-6366.9
(TQ)(3K)
0.044;-3721.3
(3K)(TK)
0.056;-1075.6
J(3JK)
0.048;-3721.3
(3J)(QK)
0.047;-3370.6
JJ(3K)
0.052;-3721.3
3Q(JQ)
0.031;-3721.3
3JQK
0.024;-7960.6
QK(3Q)
0.043;-3020.0
QK(3K)
0.044;-2669.4
44(46)
0.020;-8438.8
44(4T)
0.025;-7036.3
(45)(45)
0.027;-6143.8
4(458)
0.012;-9681.9
4T(45)
0.019;-8980.6
(45)(4K)
0.032;-5633.8
4457
0.006;-12327.5
44(5T)
0.015;-8980.6
45(4K)
0.018;-7928.8
4(468)
0.016;-9331.2
4T(46)
0.017;-8630.0
(46)(4K)
0.029;-5283.1
4468
0.009;-11626.2
44(6J)
0.020;-8279.4
(47)(47)
0.032;-4741.3
4(47T)
0.019;-8279.4
4Q(47)
0.024;-7578.1
47(49)
0.019;-8630.0
447J
0.011;-10223.8
48(48)
0.024;-6335.0
(48)(4J)
0.038;-5283.1
4488
0.019;-8630.0
44(8J)
0.020;-7578.1
(49)(49)
0.042;-3338.8
4(49Q)
0.023;-6876.9
44(9T)
0.018;-7578.1
49(4K)
0.025;-6526.3
4(4TQ)
0.020;-6526.3
44(TJ)
0.021;-6876.9
(4J)(4J)
0.046;-1936.3
44JJ
0.025;-6526.3
4Q(4Q)
0.043;-3530.0
(4K)(4K)
0.070;-533.8
(45)(57)
0.023;-7386.9
5(45T)
0.016;-8630.0
5Q(45)
0.017;-7928.8
8(456)
0.009;-11275.6
Q(456)
0.013;-9873.1
(45)(68)
0.013;-8980.6
6(45J)
0.012;-10223.8
6K(45)
0.015;-9522.5
(457J)
0.016;-9873.1
(45)(78)
0.020;-8630.0
7(45J)
0.012;-9873.1
7K(45)
0.016;-9171.9
(458Q)
0.011;-9171.9
8(45T)
0.014;-9873.1
8Q(45)
0.019;-9171.9
J(459)
0.012;-9171.9
9T(45)
0.014;-9522.5
(45)(9K)
0.033;-6175.6
K(45T)
0.015;-8120.0
T(45K)
0.020;-8120.0
JJ(45)
0.026;-6175.6
(45QK)
0.028;-7418.8
4555
0.011;-10383.1
45(58)
0.013;-9331.2
55(4J)
0.015;-8279.4
455K
0.014;-9873.1
58(46)
0.007;-11275.6
(46)(5J)
0.014;-7928.8
46(56)
0.012;-9681.9
4(569)
0.010;-10925.0
(56)(4Q)
0.024;-7578.1
46(57)
0.010;-11626.2
46(59)
0.009;-10925.0
46(5J)
0.013;-10223.8
46(5K)
0.017;-9522.5
5(479)
0.009;-10574.4
5J(47)
0.014;-9873.1
(57)(48)
0.017;-8630.0
4T(57)
0.012;-10223.8
4(57K)
0.018;-9171.9
47(59)
0.010;-10574.4
47(5J)
0.011;-9873.1
47(5K)
0.016;-9171.9
5(48T)
0.013;-9873.1
5Q(48)
0.012;-9171.9
(58)(4T)
0.019;-7578.1
4Q(58)
0.016;-9171.9
4589
0.008;-12518.8
458J
0.009;-11817.5
458K
0.008;-11116.2
5J(49)
0.013;-9171.9
(59)(4T)
0.023;-7227.5
4Q(59)
0.014;-8821.3
459T
0.006;-11817.5
459Q
0.009;-11116.2
(4T)(5J)
0.024;-6526.3
4T(5T)
0.022;-6876.9
4(5TK)
0.015;-8120.0
4T(5Q)
0.019;-8470.6
5J(4J)
0.032;-6175.6
(5J)(4Q)
0.028;-5825.0
4J(5Q)
0.013;-8120.0
5Q(4Q)
0.026;-5474.4
45QQ
0.020;-7769.4
45KK
0.029;-7068.1
6(469)
0.020;-8279.4
6J(46)
0.022;-7578.1
(4678)
0.011;-10574.4
(467Q)
0.012;-9171.9
7(469)
0.011;-10223.8
7J(46)
0.011;-9522.5
(4689)
0.013;-9873.1
(468K)
0.016;-8470.6
8T(46)
0.013;-9522.5
(46)(8K)
0.023;-6175.6
Q(469)
0.017;-8470.6
(46)(9J)
0.027;-6526.3
T(46T)
0.030;-6526.3
T(46J)
0.019;-8470.6
TK(46)
0.016;-7769.4
(46)(JQ)
0.030;-5474.4
QQ(46)
0.032;-5123.8
46(67)
0.016;-8980.6
66(4T)
0.015;-7928.8
466Q
0.015;-9522.5
68(47)
0.011;-10574.4
(47)(6J)
0.020;-7227.5
47(67)
0.014;-8630.0
4(67T)
0.009;-9873.1
(67)(4K)
0.023;-6526.3
67(49)
0.012;-10223.8
67(4J)
0.015;-9522.5
67(4K)
0.019;-8821.3
69(48)
0.011;-9873.1
(48)(6Q)
0.029;-6526.3
49(68)
0.011;-9873.1
4(68Q)
0.017;-8821.3
46(89)
0.010;-9873.1
46(8J)
0.013;-9171.9
46(8K)
0.017;-8470.6
(49)(6J)
0.029;-6526.3
49(69)
0.026;-7227.5
4(69Q)
0.015;-8470.6
46(9T)
0.012;-9171.9
46(9Q)
0.013;-8470.6
6(4TJ)
0.021;-8470.6
6K(4T)
0.019;-7769.4
(6T)(4K)
0.025;-5474.4
6T(4Q)
0.026;-8120.0
(4J)(6J)
0.039;-3530.0
4J(6J)
0.038;-5825.0
6J(4Q)
0.019;-7769.4
(4Q)(6Q)
0.061;-2828.8
4K(6Q)
0.024;-7068.1
4K(6K)
0.039;-4422.5
79(47)
0.019;-7578.1
(47)(7Q)
0.048;-4231.3
(478T)
0.012;-9171.9
88(47)
0.026;-7578.1
(47)(8J)
0.026;-6526.3
9(479)
0.024;-6876.9
K(479)
0.025;-7769.4
9(47Q)
0.016;-8120.0
J(47T)
0.021;-8120.0
TJ(47)
0.016;-8120.0
(47JQ)
0.022;-7418.8
J(47K)
0.023;-7068.1
(47)(QK)
0.039;-4422.5
77(49)
0.016;-7578.1
477J
0.013;-9171.9
78(48)
0.020;-7578.1
(48)(7J)
0.032;-6526.3
48(78)
0.022;-7578.1
4(78J)
0.018;-8821.3
4788
0.015;-9873.1
478T
0.008;-11466.9
478Q
0.010;-10765.6
(49)(7T)
0.019;-6526.3
7(49K)
0.022;-7769.4
4(79J)
0.013;-8470.6
4799
0.016;-9171.9
479J
0.011;-10765.6
479K
0.009;-10064.4
7Q(4T)
0.019;-7769.4
(7T)(4Q)
0.031;-5474.4
4T(7J)
0.018;-8120.0
4T(7K)
0.022;-7418.8
7(4JK)
0.020;-7068.1
4(7JK)
0.017;-7068.1
4J(7K)
0.027;-7068.1
4Q(7Q)
0.030;-4773.1
47QK
0.021;-9012.5
89(48)
0.029;-6876.9
(48)(8Q)
0.042;-3530.0
(489J)
0.021;-8120.0
(48)(9T)
0.027;-6175.6
9(48K)
0.016;-7418.8
(48TK)
0.018;-7068.1
TQ(48)
0.018;-7418.8
K(48J)
0.020;-6717.5
Q(48Q)
0.040;-4422.5
KK(48)
0.047;-3721.3
88(4J)
0.025;-6175.6
488K
0.022;-7769.4
8J(49)
0.016;-8120.0
(89)(4T)
0.031;-6175.6
4Q(89)
0.025;-7769.4
489T
0.008;-10765.6
489Q
0.014;-10064.4
(4T)(8J)
0.035;-5474.4
4T(8T)
0.026;-5825.0
4(8TK)
0.021;-7068.1
4T(8Q)
0.024;-7418.8
8J(4J)
0.026;-5123.8
(8J)(4Q)
0.044;-4773.1
4J(8Q)
0.022;-7068.1
8Q(4Q)
0.043;-4422.5
48QQ
0.021;-6717.5
48KK
0.026;-6016.3
9(49Q)
0.033;-5123.8
J(49T)
0.019;-7418.8
TJ(49)
0.025;-7418.8
(49JQ)
0.022;-6717.5
J(49K)
0.031;-6366.9
(49)(QK)
0.034;-3721.3
99(4J)
0.025;-5474.4
499K
0.026;-7068.1
9Q(4T)
0.029;-7068.1
(9T)(4Q)
0.027;-4773.1
4T(9J)
0.025;-7418.8
4T(9K)
0.024;-6717.5
9(4JK)
0.025;-6366.9
4(9JK)
0.024;-6366.9
4J(9K)
0.024;-6366.9
4Q(9Q)
0.044;-4071.9
49QK
0.019;-8311.3
TJ(4T)
0.031;-4773.1
(4TJQ)
0.033;-6366.9
J(4TK)
0.033;-6016.3
(4T)(QK)
0.047;-3370.6
TT(4Q)
0.028;-4422.5
T(4JQ)
0.024;-6366.9
4(TJQ)
0.025;-6366.9
4T(JQ)
0.024;-6366.9
T(4QK)
0.029;-5665.6
TQ(4K)
0.033;-5665.6
JJ(4J)
0.059;-1776.9
(4JQK)
0.031;-5315.0
4JJJ
0.037;-4071.9
JQ(4Q)
0.050;-3370.6
4JQQ
0.033;-5665.6
4JKK
0.032;-4964.4
QQ(4K)
0.063;-2669.4
4KKK
0.057;-1968.1
55(59)
0.026;-6335.0
55(5K)
0.046;-4932.5
(56)(58)
0.023;-6335.0
5(56J)
0.019;-7578.1
5K(56)
0.019;-6876.9
56(59)
0.023;-8279.4
556J
0.011;-9873.1
57(57)
0.021;-6335.0
(57)(5T)
0.033;-5283.1
5(57K)
0.025;-6526.3
55(79)
0.016;-7928.8
57(5Q)
0.021;-6876.9
5(589)
0.023;-7578.1
5J(58)
0.021;-6876.9
58(59)
0.022;-7578.1
558J
0.017;-9171.9
59(59)
0.036;-4932.5
(59)(5Q)
0.037;-3880.6
559T
0.013;-9171.9
55(9K)
0.029;-5825.0
(5T)(5Q)
0.046;-3530.0
55TJ
0.014;-8470.6
5J(5J)
0.059;-3530.0
5J(5Q)
0.025;-5474.4
5(5QK)
0.029;-4773.1
5K(5K)
0.042;-2127.5
68(56)
0.016;-8279.4
(56)(6J)
0.044;-4932.5
7(567)
0.019;-8279.4
J(567)
0.013;-9171.9
78(56)
0.010;-10223.8
(56)(7J)
0.023;-6876.9
8(568)
0.021;-7578.1
Q(568)
0.018;-8470.6
(56)(8T)
0.022;-6876.9
8(56K)
0.018;-8120.0
(569Q)
0.019;-8120.0
9(56J)
0.018;-8470.6
9K(56)
0.024;-7769.4
TT(56)
0.028;-6175.6
(56)(TK)
0.025;-5123.8
J(56Q)
0.023;-7418.8
K(56Q)
0.022;-6717.5
66(57)
0.023;-8630.0
5669
0.010;-10223.8
56(6Q)
0.030;-6876.9
(57)(68)
0.015;-7928.8
6(57J)
0.011;-9171.9
6K(57)
0.021;-8470.6
(67)(5T)
0.016;-7227.5
5Q(67)
0.021;-8821.3
5678
0.005;-12518.8
567T
0.008;-11817.5
567Q
0.009;-11116.2
(58)(69)
0.026;-7227.5
6(58Q)
0.017;-8470.6
5(689)
0.013;-9522.5
(68)(5Q)
0.032;-6175.6
58(69)
0.015;-9522.5
58(6J)
0.015;-8821.3
58(6K)
0.018;-8120.0
6(59J)
0.013;-8470.6
6K(59)
0.020;-7769.4
(69)(5Q)
0.028;-5825.0
59(6T)
0.015;-8821.3
59(6Q)
0.017;-8120.0
6T(5T)
0.026;-6175.6
(5T)(6K)
0.032;-5123.8
5Q(6T)
0.025;-7769.4
56TJ
0.009;-10415.0
56TK
0.013;-9713.8
6K(5J)
0.023;-7068.1
56JJ
0.016;-7769.4
56JK
0.016;-9363.1
5(6QK)
0.028;-6717.5
6K(5K)
0.050;-4071.9
(57)(79)
0.035;-4932.5
7(57Q)
0.027;-6175.6
9(578)
0.012;-9171.9
K(578)
0.019;-7769.4
8(57J)
0.021;-8470.6
8K(57)
0.021;-7769.4
(579K)
0.022;-7418.8
9J(57)
0.014;-8120.0
(57TJ)
0.022;-7769.4
(57)(TJ)
0.033;-5474.4
J(57J)
0.028;-5123.8
JQ(57)
0.022;-7068.1
Q(57K)
0.020;-6366.9
5778
0.013;-9873.1
57(7J)
0.024;-6526.3
(58)(78)
0.034;-4932.5
7(58J)
0.017;-8470.6
7K(58)
0.020;-7769.4
(78)(5J)
0.027;-6175.6
5K(78)
0.021;-7769.4
57(8T)
0.018;-8821.3
57(8Q)
0.019;-8120.0
7(59T)
0.019;-8470.6
7Q(59)
0.021;-7769.4
(79)(5J)
0.035;-5825.0
5K(79)
0.024;-7418.8
57(9J)
0.024;-8120.0
57(9K)
0.017;-7418.8
(5T)(7Q)
0.036;-5123.8
5J(7T)
0.015;-7769.4
7T(5J)
0.015;-7769.4
7T(5K)
0.017;-7068.1
7Q(5J)
0.025;-7068.1
(7J)(5K)
0.033;-4422.5
7J(5K)
0.028;-6717.5
7K(5Q)
0.029;-6366.9
57(QK)
0.026;-6366.9
(58)(89)
0.031;-4231.3
8(58Q)
0.025;-5474.4
T(589)
0.017;-8120.0
9(58T)
0.015;-8120.0
9Q(58)
0.017;-7418.8
Q(58T)
0.024;-7068.1
(58)(TQ)
0.044;-4773.1
(58JK)
0.021;-6366.9
JK(58)
0.019;-6366.9
K(58K)
0.045;-3370.6
588T
0.023;-8470.6
58(8K)
0.038;-5123.8
(59)(8J)
0.031;-5474.4
59(89)
0.022;-6175.6
5(89Q)
0.030;-7418.8
58(9T)
0.014;-8120.0
58(9Q)
0.017;-7418.8
8(5TJ)
0.024;-7418.8
8K(5T)
0.027;-6717.5
(8T)(5K)
0.031;-4422.5
8T(5Q)
0.022;-7068.1
(5J)(8J)
0.043;-2478.1
5J(8J)
0.028;-4773.1
8J(5Q)
0.029;-6717.5
(5Q)(8Q)
0.061;-1776.9
5K(8Q)
0.030;-6016.3
5K(8K)
0.042;-3370.6
9J(59)
0.031;-5123.8
(59TJ)
0.029;-7068.1
(59)(TJ)
0.027;-4773.1
J(59J)
0.031;-4422.5
JQ(59)
0.024;-6366.9
Q(59K)
0.038;-5665.6
599T
0.025;-7769.4
59(9K)
0.044;-4422.5
(5T)(9Q)
0.044;-4422.5
5J(9T)
0.019;-7068.1
9T(5J)
0.021;-7068.1
9T(5K)
0.031;-6366.9
9Q(5J)
0.029;-6366.9
(9J)(5K)
0.050;-3721.3
9J(5K)
0.024;-6016.3
9K(5Q)
0.026;-5665.6
59(QK)
0.034;-5665.6
(5T)(TJ)
0.050;-2127.5
J(5TJ)
0.046;-4071.9
JQ(5T)
0.030;-6016.3
Q(5TK)
0.037;-5315.0
5TTJ
0.023;-6717.5
TJ(5J)
0.048;-4071.9
(TJ)(5Q)
0.041;-3721.3
5J(TQ)
0.023;-6016.3
TQ(5Q)
0.038;-3370.6
5TQQ
0.036;-5665.6
5TKK
0.034;-4964.4
Q(5JQ)
0.036;-3020.0
KK(5J)
0.051;-2318.7
(5Q)(JQ)
0.075;-725.0
5K(JQ)
0.028;-4964.4
5K(JK)
0.063;-2318.7
5QQQ
0.060;-2669.4
KK(5K)
0.086;677.5
6669
0.021;-7578.1
666K
0.029;-6175.6
69(67)
0.023;-7227.5
(67)(6Q)
0.043;-3880.6
6678
0.013;-9873.1
66(7J)
0.025;-6526.3
(68)(68)
0.045;-2637.5
6(68J)
0.024;-6175.6
6K(68)
0.033;-5474.4
68(6J)
0.027;-6175.6
668K
0.022;-7769.4
6J(69)
0.026;-5825.0
69(6T)
0.034;-6175.6
669Q
0.017;-7769.4
6J(6T)
0.026;-5474.4
6T(6J)
0.029;-5474.4
66TK
0.022;-7068.1
6K(6J)
0.043;-4422.5
(6Q)(6Q)
0.068;167.5
66QK
0.021;-6366.9
7(679)
0.032;-6876.9
7J(67)
0.021;-6175.6
(6789)
0.014;-8821.3
(678K)
0.022;-7418.8
8T(67)
0.021;-8470.6
(67)(8K)
0.035;-5123.8
Q(679)
0.024;-7418.8
(67)(9J)
0.029;-5474.4
T(67T)
0.034;-5474.4
T(67J)
0.020;-7418.8
TK(67)
0.024;-6717.5
(67)(JQ)
0.032;-4422.5
QQ(67)
0.043;-4071.9
67(78)
0.021;-7227.5
77(6J)
0.027;-6175.6
677K
0.017;-7769.4
7T(68)
0.016;-8470.6
(68)(7K)
0.032;-5123.8
6T(78)
0.018;-8470.6
6(78K)
0.023;-7418.8
68(7T)
0.021;-8470.6
68(7Q)
0.018;-7769.4
79(69)
0.027;-6175.6
(69)(7Q)
0.032;-5123.8
6T(79)
0.014;-8120.0
6(79K)
0.020;-7068.1
69(7J)
0.015;-7769.4
69(7K)
0.021;-7068.1
7(6TQ)
0.021;-7068.1
6(7TJ)
0.022;-7418.8
67TT
0.018;-7769.4
67TQ
0.012;-9363.1
(6J)(7Q)
0.032;-4422.5
6Q(7J)
0.030;-6717.5
67JQ
0.012;-9012.5
(6Q)(7K)
0.032;-3721.3
6Q(7K)
0.028;-6016.3
8(689)
0.029;-6175.6
8J(68)
0.034;-5474.4
(689T)
0.023;-7769.4
99(68)
0.021;-5825.0
(68)(9Q)
0.030;-4773.1
(68TQ)
0.023;-6717.5
T(68Q)
0.028;-6717.5
Q(68J)
0.026;-6366.9
(68)(JK)
0.045;-3721.3
QK(68)
0.030;-5665.6
68(8T)
0.027;-5825.0
88(6K)
0.031;-4773.1
8(69J)
0.028;-7418.8
8K(69)
0.032;-6717.5
(89)(6Q)
0.038;-4773.1
69(8T)
0.022;-7769.4
69(8Q)
0.023;-7068.1
8T(6T)
0.032;-5123.8
(6T)(8K)
0.035;-4071.9
6Q(8T)
0.023;-6717.5
68TJ
0.012;-9363.1
68TK
0.012;-8661.9
8K(6J)
0.029;-6016.3
68JJ
0.026;-6717.5
68JK
0.013;-8311.3
6(8QK)
0.033;-5665.6
8K(6K)
0.056;-3020.0
(69)(9J)
0.052;-2478.1
T(69T)
0.042;-4773.1
T(69J)
0.022;-6717.5
TK(69)
0.031;-6016.3
(69)(JQ)
0.036;-3721.3
QQ(69)
0.041;-3370.6
69(9T)
0.035;-5123.8
99(6K)
0.033;-4071.9
9(6TQ)
0.021;-6366.9
6(9TJ)
0.034;-6717.5
69TT
0.030;-7068.1
69TQ
0.012;-8661.9
(6J)(9Q)
0.045;-3721.3
6Q(9J)
0.027;-6016.3
69JQ
0.019;-8311.3
(6Q)(9K)
0.045;-3020.0
6Q(9K)
0.039;-5315.0
T(6TJ)
0.033;-4071.9
TK(6T)
0.051;-3370.6
(6T)(JQ)
0.049;-3370.6
QQ(6T)
0.050;-3020.0
6T(TJ)
0.047;-4071.9
(6J)(TJ)
0.061;-1426.3
6J(TJ)
0.032;-3721.3
TJ(6Q)
0.025;-5665.6
(6Q)(TQ)
0.062;-725.0
6K(TQ)
0.032;-4964.4
6K(TK)
0.052;-2318.7
JK(6J)
0.050;-2669.4
K(6JK)
0.056;-1968.1
6JJK
0.034;-4964.4
6(JQK)
0.048;-4613.8
JK(6K)
0.051;-1968.1
KK(6Q)
0.064;-1617.5
6QKK
0.034;-3912.5
77(7T)
0.042;-3880.6
(78)(78)
0.070;-1936.3
7(78J)
0.029;-5474.4
7K(78)
0.034;-4773.1
78(7J)
0.040;-5474.4
778K
0.024;-7068.1
7J(79)
0.040;-5123.8
79(7T)
0.031;-5474.4
779Q
0.027;-7068.1
7J(7T)
0.031;-4773.1
7T(7J)
0.042;-4773.1
77TK
0.025;-6366.9
7K(7J)
0.044;-3721.3
(7Q)(7Q)
0.081;868.7
77QK
0.027;-5665.6
8(78T)
0.022;-5474.4
8Q(78)
0.033;-4773.1
J(789)
0.021;-7068.1
9T(78)
0.028;-7418.8
(78)(9K)
0.037;-4071.9
K(78T)
0.027;-6016.3
T(78K)
0.023;-6016.3
JJ(78)
0.042;-4071.9
(78QK)
0.039;-5315.0
7888
0.031;-6175.6
78(8J)
0.038;-5123.8
(79)(89)
0.038;-3179.4
8(79Q)
0.019;-6717.5
7(89T)
0.019;-7418.8
(89)(7K)
0.042;-4071.9
89(7J)
0.031;-7068.1
89(7K)
0.030;-6366.9
8J(7T)
0.026;-6717.5
(8T)(7J)
0.032;-4422.5
7K(8T)
0.021;-6016.3
78(TQ)
0.029;-6366.9
8(7JQ)
0.030;-6016.3
7(8JQ)
0.023;-6016.3
78(JQ)
0.026;-6016.3
8(7QK)
0.028;-5315.0
8Q(7K)
0.036;-5315.0
99(79)
0.050;-2828.8
(79)(9Q)
0.053;-1776.9
(79TQ)
0.025;-6016.3
T(79Q)
0.026;-6016.3
Q(79J)
0.031;-5665.6
(79)(JK)
0.050;-3020.0
QK(79)
0.031;-4964.4
79(9J)
0.037;-4422.5
(7T)(9T)
0.054;-2127.5
9(7TK)
0.038;-5665.6
7(9TQ)
0.028;-6016.3
79(TJ)
0.025;-6366.9
79(TK)
0.025;-5665.6
(7J)(9K)
0.058;-3020.0
7K(9J)
0.028;-5315.0
79(JK)
0.025;-5315.0
(9Q)(7K)
0.055;-2669.4
(7K)(9K)
0.068;-23.8
T(7TQ)
0.032;-3370.6
Q(7TJ)
0.036;-5315.0
(7T)(JK)
0.050;-2669.4
QK(7T)
0.031;-4613.8
7T(TQ)
0.048;-3370.6
(7J)(TQ)
0.038;-3020.0
7Q(TJ)
0.030;-5315.0
7TJQ
0.017;-7610.0
(7Q)(TK)
0.050;-2318.7
7Q(TK)
0.036;-4613.8
J(7JQ)
0.051;-2669.4
K(7JQ)
0.038;-4263.1
JJ(7Q)
0.064;-2669.4
J(7QK)
0.042;-4263.1
JQ(7K)
0.036;-4263.1
QQ(7Q)
0.078;326.9
7Q(QK)
0.066;-1617.5
8888
0.042;-3530.0
888Q
0.034;-4422.5
8(89J)
0.028;-4422.5
8K(89)
0.044;-3721.3
89(8Q)
0.046;-4071.9
8(8TJ)
0.036;-4071.9
8K(8T)
0.040;-3370.6
8T(8K)
0.037;-3370.6
8(8JK)
0.039;-3020.0
88(JK)
0.046;-3020.0
8Q(8K)
0.042;-2669.4
(89)(9T)
0.063;-2127.5
9(89K)
0.046;-3370.6
(89TK)
0.028;-5315.0
TQ(89)
0.030;-5665.6
K(89J)
0.036;-4964.4
Q(89Q)
0.043;-2669.4
KK(89)
0.055;-1968.1
99(8Q)
0.052;-3721.3
9(8TJ)
0.023;-6016.3
9K(8T)
0.031;-5315.0
(9T)(8K)
0.042;-3020.0
9T(8Q)
0.023;-5665.6
(8J)(9J)
0.079;-1075.6
8J(9J)
0.038;-3370.6
9J(8Q)
0.031;-5315.0
(8Q)(9Q)
0.066;-374.4
8K(9Q)
0.033;-4613.8
8K(9K)
0.045;-1968.1
TQ(8T)
0.055;-3020.0
K(8TJ)
0.036;-4613.8
Q(8TQ)
0.051;-2318.7
KK(8T)
0.065;-1617.5
