AAAA
0.212;607.5
5AAA
0.155;126.6
9AAA
0.131;250.3
KAAA
0.191;374.1
4A(2A)
0.085;-275.6
(2A)(7A)
0.149;19.7
A(2TA)
0.092;-90.0
QA(2A)
0.115;-28.1
2A(4A)
0.077;-275.6
26AA
0.052;-416.2
AA(29)
0.099;-120.9
2A(QA)
0.120;-28.1
A(34A)
0.088;-244.7
6A(3A)
0.095;-182.8
(3A)(9A)
0.144;112.5
A(3QA)
0.110;2.8
AA(34)
0.081;-244.7
3A(7A)
0.087;-151.9
39AA
0.072;-292.5
AA(3Q)
0.132;2.8
(4A)(5A)
0.150;19.7
A(48A)
0.110;-90.0
TA(4A)
0.112;-28.1
(4A)(KA)
0.206;267.2
46AA
0.071;-354.4
AA(49)
0.121;-59.1
4A(QA)
0.148;33.7
A(56A)
0.085;-120.9
8A(5A)
0.122;-59.1
(5A)(JA)
0.183;236.3
55AA
0.120;-151.9
AA(58)
0.111;-59.1
5A(JA)
0.120;33.7
5KAA
0.115;-106.9
8A(6A)
0.108;-28.1
(6A)(JA)
0.204;267.2
66AA
0.120;-90.0
AA(69)
0.139;2.8
6A(QA)
0.151;95.6
A(78A)
0.100;2.8
TA(7A)
0.125;64.7
(7A)(KA)
0.165;360.0
79AA
0.099;-168.8
AA(7Q)
0.138;126.6
(8A)(9A)
0.194;267.2
A(8QA)
0.193;157.5
AA(89)
0.129;64.7
8A(QA)
0.159;157.5
A(9TA)
0.141;126.6
QA(9A)
0.137;188.4
9A(JA)
0.180;157.5
9KAA
0.138;16.9
QA(TA)
0.143;219.4
TA(QA)
0.124;219.4
A(JQA)
0.130;250.3
AA(JQ)
0.161;250.3
(QA)(KA)
0.206;514.7
KKAA
0.205;343.1
2(25A)
0.044;-615.9
27(2A)
0.042;-554.1
(2T)(2A)
0.071;-258.8
2(2KA)
0.078;-368.4
(236A)
0.026;-756.6
(23TA)
0.035;-632.8
33(2A)
0.035;-646.9
(36)(2A)
0.045;-554.1
3(29A)
0.032;-663.8
3J(2A)
0.037;-601.9
(245A)
0.026;-756.6
(249A)
0.046;-632.8
(24KA)
0.048;-509.1
46(2A)
0.031;-725.6
(49)(2A)
0.042;-430.3
4(2QA)
0.042;-540.0
6(25A)
0.029;-694.7
T(25A)
0.036;-570.9
5(26A)
0.034;-694.7
58(2A)
0.037;-632.8
(5J)(2A)
0.073;-337.5
6(26A)
0.047;-461.2
T(26A)
0.051;-540.0
6(27A)
0.040;-632.8
69(2A)
0.045;-570.9
(6Q)(2A)
0.074;-275.6
(279A)
0.039;-540.0
(27KA)
0.051;-416.2
79(2A)
0.050;-540.0
(7Q)(2A)
0.091;-244.7
(28TA)
0.056;-478.1
88(2A)
0.078;-337.5
(8J)(2A)
0.078;-244.7
9(29A)
0.081;-275.6
K(29A)
0.068;-354.4
9(2QA)
0.048;-385.3
J(2TA)
0.063;-385.3
TJ(2A)
0.070;-385.3
(2JQA)
0.065;-323.4
J(2KA)
0.063;-292.5
(QK)(2A)
0.112;-59.1
22(4A)
0.040;-646.9
226A
0.022;-787.5
2A(29)
0.047;-492.2
22(QA)
0.067;-399.4
2(34A)
0.023;-818.4
26(3A)
0.026;-756.6
(29)(3A)
0.049;-461.3
2(3QA)
0.050;-570.9
A(234)
0.024;-818.4
(23)(7A)
0.045;-523.1
9A(23)
0.034;-663.8
A(23Q)
0.047;-570.9
2A(34)
0.022;-818.4
2A(36)
0.028;-756.6
2A(38)
0.029;-694.7
2A(3T)
0.040;-632.8
2A(3Q)
0.054;-570.9
2(45A)
0.026;-756.6
27(4A)
0.028;-694.7
(2T)(4A)
0.064;-399.4
2(4KA)
0.049;-509.1
A(246)
0.026;-725.6
(24)(9A)
0.048;-430.3
JA(24)
0.047;-570.9
24(5A)
0.027;-756.6
24(7A)
0.027;-694.7
24(9A)
0.038;-632.8
24(JA)
0.045;-570.9
24(KA)
0.047;-509.1
26(5A)
0.031;-694.7
(29)(5A)
0.063;-399.4
2(5QA)
0.055;-509.1
A(256)
0.027;-694.7
(25)(9A)
0.054;-399.4
JA(25)
0.044;-540.0
25(6A)
0.035;-694.7
25(8A)
0.042;-632.8
25(TA)
0.043;-570.9
25(QA)
0.043;-509.1
(26)(6A)
0.084;-258.8
2(69A)
0.044;-570.9
2J(6A)
0.047;-509.1
(26)(7A)
0.054;-430.3
9A(26)
0.043;-570.9
A(26Q)
0.050;-478.1
2A(67)
0.030;-632.8
2A(69)
0.037;-570.9
2A(6J)
0.058;-509.1
2A(6K)
0.057;-447.2
(29)(7A)
0.076;-337.5
2(7QA)
0.068;-447.2
A(278)
0.036;-570.9
(27)(JA)
0.078;-275.6
KA(27)
0.059;-416.2
2A(79)
0.042;-540.0
2A(7J)
0.050;-478.1
2A(7K)
0.044;-416.2
(2T)(8A)
0.082;-275.6
2(8KA)
0.065;-385.3
A(28T)
0.041;-478.1
(28)(KA)
0.094;-182.8
28(TA)
0.060;-478.1
28(QA)
0.059;-416.2
(29)(9A)
0.081;-73.1
2(9QA)
0.059;-385.3
A(29T)
0.050;-447.2
(29)(KA)
0.085;-151.9
29(JA)
0.057;-416.2
29(KA)
0.073;-354.4
2J(TA)
0.060;-385.3
(2T)(JA)
0.099;-182.8
KA(2T)
0.071;-323.4
2A(TQ)
0.055;-354.4
2(JQA)
0.063;-323.4
A(2JQ)
0.068;-323.4
2A(JQ)
0.065;-323.4
2(QKA)
0.072;-261.6
2Q(KA)
0.091;-261.6
33(3A)
0.073;-413.4
(36)(3A)
0.066;-320.6
3(39A)
0.073;-430.3
3J(3A)
0.073;-368.4
(345A)
0.028;-725.6
(349A)
0.044;-601.9
(34KA)
0.057;-478.1
46(3A)
0.029;-694.7
(49)(3A)
0.071;-399.4
4(3QA)
0.051;-509.1
6(35A)
0.028;-663.8
T(35A)
0.041;-540.0
5(36A)
0.030;-663.8
58(3A)
0.035;-601.9
(5J)(3A)
0.079;-306.6
6(36A)
0.053;-430.3
T(36A)
0.047;-509.1
6(37A)
0.029;-601.9
69(3A)
0.036;-540.0
(6Q)(3A)
0.085;-244.7
(379A)
0.043;-509.1
(37KA)
0.054;-385.3
79(3A)
0.041;-509.1
(7Q)(3A)
0.109;-213.8
(38TA)
0.053;-447.2
88(3A)
0.067;-306.6
(8J)(3A)
0.077;-213.8
9(39A)
0.073;-244.7
K(39A)
0.059;-323.4
9(3QA)
0.073;-354.4
J(3TA)
0.071;-354.4
TJ(3A)
0.067;-354.4
(3JQA)
0.072;-292.5
J(3KA)
0.094;-261.6
(QK)(3A)
0.130;-28.1
33(5A)
0.039;-554.1
337A
0.041;-694.7
3A(3T)
0.058;-399.4
33(KA)
0.073;-306.6
3(46A)
0.028;-694.7
38(4A)
0.033;-632.8
(3J)(4A)
0.058;-337.5
4A(34)
0.044;-554.1
A(347)
0.038;-663.8
(34)(TA)
0.059;-368.4
QA(34)
0.054;-509.1
345A
0.016;-928.1
347A
0.016;-866.3
349A
0.024;-804.4
34JA
0.028;-742.5
34KA
0.034;-680.6
37(5A)
0.029;-632.8
(3T)(5A)
0.061;-337.5
3(5KA)
0.048;-447.2
A(357)
0.042;-632.8
(35)(TA)
0.087;-337.5
QA(35)
0.055;-478.1
356A
0.020;-866.3
358A
0.023;-804.4
35TA
0.029;-742.5
35QA
0.028;-680.6
(37)(6A)
0.067;-399.4
3(6TA)
0.044;-509.1
3Q(6A)
0.065;-447.2
(36)(8A)
0.061;-368.4
TA(36)
0.057;-509.1
A(36K)
0.055;-416.2
6A(38)
0.055;-570.9
6A(3T)
0.041;-509.1
6A(3Q)
0.052;-447.2
37(7A)
0.070;-368.4
(3T)(7A)
0.077;-275.6
3(7KA)
0.056;-385.3
A(379)
0.049;-509.1
(37)(QA)
0.095;-213.8
7A(38)
0.052;-540.0
7A(3T)
0.046;-478.1
7A(3Q)
0.053;-416.2
38(8A)
0.077;-306.6
(3J)(8A)
0.093;-213.8
8A(38)
0.071;-306.6
A(38J)
0.065;-416.2
388A
0.038;-509.1
38TA
0.030;-649.7
38QA
0.031;-587.8
(3T)(9A)
0.089;-213.8
3(9KA)
0.063;-323.4
A(39J)
0.086;-385.3
399A
0.045;-447.2
39JA
0.035;-587.8
39KA
0.039;-525.9
3Q(TA)
0.067;-323.4
(3T)(QA)
0.082;-120.9
TA(3J)
0.064;-354.4
TA(3K)
0.067;-292.5
3(JKA)
0.102;-261.6
A(3JK)
0.103;-261.6
JA(3K)
0.095;-261.6
QA(3Q)
0.108;-59.1
3QKA
0.057;-433.1
45(4A)
0.059;-492.2
(48)(4A)
0.087;-196.9
4(4JA)
0.063;-306.6
4K(4A)
0.081;-244.7
(459A)
0.049;-540.0
(45KA)
0.054;-416.2
57(4A)
0.037;-601.9
(5T)(4A)
0.075;-306.6
5(4KA)
0.067;-416.2
(469A)
0.038;-509.1
(46KA)
0.058;-385.3
68(4A)
0.035;-540.0
(6J)(4A)
0.107;-244.7
7(47A)
0.073;-337.5
J(47A)
0.054;-416.2
78(4A)
0.043;-509.1
(7J)(4A)
0.090;-213.8
8(48A)
0.069;-275.6
Q(48A)
0.072;-354.4
(8T)(4A)
0.086;-213.8
8(4KA)
0.056;-323.4
(49QA)
0.081;-323.4
9(4JA)
0.077;-354.4
9K(4A)
0.069;-292.5
TT(4A)
0.083;-151.9
(TK)(4A)
0.114;-59.1
J(4QA)
0.077;-261.6
K(4QA)
0.084;-199.7
44(5A)
0.058;-492.2
447A
0.041;-632.8
4A(4T)
0.090;-337.5
44(KA)
0.088;-244.7
4(57A)
0.039;-601.9
49(5A)
0.044;-540.0
(4Q)(5A)
0.092;-244.7
6A(45)
0.034;-632.8
A(459)
0.041;-540.0
(45)(QA)
0.083;-244.7
5A(46)
0.031;-632.8
5A(48)
0.044;-570.9
5A(4T)
0.044;-509.1
5A(4Q)
0.062;-447.2
46(6A)
0.061;-399.4
(49)(6A)
0.066;-306.6
4(6QA)
0.063;-416.2
A(467)
0.037;-570.9
(46)(TA)
0.081;-275.6
QA(46)
0.054;-416.2
467A
0.033;-773.4
469A
0.036;-711.6
46JA
0.033;-649.7
46KA
0.044;-587.8
49(7A)
0.055;-478.1
(4Q)(7A)
0.078;-182.8
8A(47)
0.044;-509.1
A(47J)
0.058;-416.2
477A
0.039;-540.0
479A
0.031;-680.6
47JA
0.033;-618.8
47KA
0.043;-556.9
4T(8A)
0.061;-416.2
(4K)(8A)
0.102;-120.9
TA(48)
0.057;-416.2
A(48K)
0.077;-323.4
8A(4T)
0.054;-416.2
8A(4Q)
0.080;-354.4
49(9A)
0.085;-213.8
(4Q)(9A)
0.091;-120.9
TA(49)
0.063;-385.3
A(49K)
0.061;-292.5
9A(4J)
0.071;-354.4
9A(4K)
0.092;-292.5
4(TQA)
0.078;-292.5
A(4TJ)
0.074;-323.4
4TTA
0.082;-354.4
4TQA
0.044;-495.0
(4Q)(JA)
0.098;-59.1
QA(4J)
0.073;-261.6
4JQA
0.063;-464.1
(4K)(QA)
0.129;2.8
QA(4K)
0.081;-199.7
5(56A)
0.066;-399.4
58(5A)
0.064;-337.5
(5J)(5A)
0.137;-42.2
6(56A)
0.071;-368.4
T(56A)
0.051;-447.2
6(57A)
0.051;-540.0
69(5A)
0.057;-478.1
(6Q)(5A)
0.098;-182.8
(579A)
0.053;-447.2
(57KA)
0.058;-323.4
79(5A)
0.059;-447.2
(7Q)(5A)
0.107;-151.9
(58TA)
0.068;-385.3
88(5A)
0.067;-244.7
(8J)(5A)
0.102;-151.9
9(59A)
0.087;-182.8
K(59A)
0.091;-261.6
9(5QA)
0.079;-292.5
J(5TA)
0.094;-292.5
TJ(5A)
0.074;-292.5
(5JQA)
0.079;-230.6
J(5KA)
0.080;-199.7
(QK)(5A)
0.124;33.7
55(7A)
0.065;-368.4
559A
0.061;-509.1
5A(5Q)
0.094;-213.8
(57)(6A)
0.065;-337.5
5(6TA)
0.072;-447.2
5Q(6A)
0.056;-385.3
(56)(8A)
0.082;-306.6
TA(56)
0.074;-447.2
A(56K)
0.051;-354.4
6A(58)
0.056;-509.1
6A(5T)
0.054;-447.2
6A(5Q)
0.063;-385.3
57(7A)
0.080;-306.6
(5T)(7A)
0.116;-213.8
5(7KA)
0.058;-323.4
A(579)
0.054;-447.2
(57)(QA)
0.101;-151.9
7A(58)
0.041;-478.1
7A(5T)
0.073;-416.2
7A(5Q)
0.063;-354.4
58(8A)
0.073;-244.7
(5J)(8A)
0.096;-151.9
8A(58)
0.061;-244.7
A(58J)
0.059;-354.4
588A
0.060;-447.2
58TA
0.037;-587.8
58QA
0.051;-525.9
(5T)(9A)
0.077;-151.9
5(9KA)
0.080;-261.6
A(59J)
0.051;-323.4
599A
0.054;-385.3
59JA
0.039;-525.9
59KA
0.070;-464.1
5Q(TA)
0.097;-261.6
(5T)(QA)
0.111;-59.1
TA(5J)
0.078;-292.5
TA(5K)
0.080;-230.6
5(JKA)
0.083;-199.7
A(5JK)
0.076;-199.7
JA(5K)
0.101;-199.7
QA(5Q)
0.124;2.8
5QKA
0.060;-371.2
67(6A)
0.068;-306.6
(6T)(6A)
0.086;-11.2
6(6KA)
0.120;-120.9
(67TA)
0.061;-385.3
77(6A)
0.075;-275.6
(7T)(6A)
0.087;-182.8
7(6KA)
0.101;-292.5
(68JA)
0.057;-323.4
(89)(6A)
0.117;-182.8
8(6QA)
0.072;-292.5
T(69A)
0.055;-323.4
9(6TA)
0.071;-323.4
9Q(6A)
0.092;-261.6
Q(6TA)
0.082;-230.6
(TQ)(6A)
0.108;-28.1
(6JKA)
0.073;-168.8
JK(6A)
0.099;-168.8
K(6KA)
0.163;95.6
668A
0.065;-478.1
6A(6J)
0.101;-182.8
(67)(7A)
0.108;-73.1
6(7TA)
0.065;-385.3
6Q(7A)
0.069;-323.4
(67)(9A)
0.088;-213.8
JA(67)
0.054;-354.4
67(8A)
0.049;-447.2
67(TA)
0.048;-385.3
67(QA)
0.058;-323.4
(68)(8A)
0.127;-11.2
6(8JA)
0.073;-323.4
6K(8A)
0.073;-261.6
(68)(JA)
0.107;-120.9
KA(68)
0.076;-261.6
6A(8T)
0.061;-354.4
6A(8Q)
0.067;-292.5
6(9TA)
0.074;-323.4
6Q(9A)
0.078;-261.6
(69)(JA)
0.115;-90.0
KA(69)
0.085;-230.6
6A(9J)
0.072;-292.5
6A(9K)
0.086;-230.6
(6Q)(TA)
0.116;-28.1
JA(6T)
0.076;-261.6
6T(JA)
0.083;-261.6
6T(KA)
0.107;-199.7
6Q(JA)
0.110;-199.7
(6J)(KA)
0.126;33.7
6J(KA)
0.085;-168.8
6K(QA)
0.077;-137.8
6A(QK)
0.112;-137.8
(78)(7A)
0.107;-11.2
7(7JA)
0.091;-120.9
7K(7A)
0.107;-59.1
(78QA)
0.089;-261.6
8(7TA)
0.060;-323.4
8Q(7A)
0.071;-261.6
J(79A)
0.076;-261.6
9T(7A)
0.083;-292.5
(9K)(7A)
0.138;2.8
K(7TA)
0.088;-168.8
T(7KA)
0.093;-168.8
JJ(7A)
0.143;2.8
(7QKA)
0.083;-106.9
777A
0.081;-244.7
7A(7T)
0.112;-151.9
77(KA)
0.108;-59.1
7(8TA)
0.083;-323.4
7Q(8A)
0.090;-261.6
(78)(TA)
0.108;-120.9
QA(78)
0.094;-261.6
789A
0.041;-556.9
78JA
0.060;-495.0
78KA
0.068;-433.1
7J(9A)
0.095;-261.6
(79)(TA)
0.108;-90.0
QA(79)
0.103;-230.6
79TA
0.040;-495.0
79QA
0.060;-433.1
(7J)(TA)
0.127;-28.1
TA(7T)
0.116;-59.1
A(7TK)
0.094;-168.8
TA(7Q)
0.115;-199.7
7J(JA)
0.138;2.8
(7J)(QA)
0.104;33.7
JA(7Q)
0.093;-168.8
7Q(QA)
0.105;64.7
7QQA
0.121;-137.8
7KKA
0.107;-75.9
8(8JA)
0.104;-59.1
8K(8A)
0.116;2.8
(89KA)
0.086;-168.8
9J(8A)
0.081;-230.6
(8TJA)
0.088;-199.7
(TJ)(8A)
0.110;2.8
J(8JA)
0.111;33.7
JQ(8A)
0.096;-137.8
Q(8KA)
0.115;-75.9
889A
0.069;-323.4
8A(8Q)
0.108;-28.1
(8T)(9A)
0.090;-59.1
8(9KA)
0.078;-168.8
A(89J)
0.100;-230.6
899A
0.077;-292.5
89JA
0.048;-433.1
89KA
0.075;-371.2
8Q(TA)
0.083;-168.8
(8T)(QA)
0.112;33.7
TA(8J)
0.084;-199.7
TA(8K)
0.072;-137.8
8(JKA)
0.119;-106.9
A(8JK)
0.113;-106.9
JA(8K)
0.107;-106.9
QA(8Q)
0.126;95.6
8QKA
0.064;-278.4
9T(9A)
0.127;-28.1
(9K)(9A)
0.183;267.2
K(9TA)
0.084;-106.9
T(9KA)
0.083;-106.9
JJ(9A)
0.115;64.7
(9QKA)
0.118;-45.0
999A
0.111;-59.1
9A(9Q)
0.117;33.7
(9J)(TA)
0.124;33.7
TA(9T)
0.125;2.8
A(9TK)
0.098;-106.9
TA(9Q)
0.099;-137.8
9J(JA)
0.137;64.7
(9J)(QA)
0.141;95.6
JA(9Q)
0.101;-106.9
9Q(QA)
0.165;126.6
9QQA
0.090;-75.9
9KKA
0.129;-14.1
T(TKA)
0.128;126.6
JJ(TA)
0.141;95.6
(TQKA)
0.108;-14.1
TTTA
0.153;33.7
TA(TK)
0.159;126.6
(TK)(JA)
0.142;157.5
KA(TJ)
0.118;-45.0
TA(JK)
0.100;-45.0
(TQ)(KA)
0.203;188.4
(TK)(KA)
0.243;421.9
J(JKA)
0.141;188.4
(QK)(JA)
0.152;219.4
JJ(KA)
0.145;188.4
QA(JQ)
0.141;188.4
JQKA
0.095;-185.6
QK(QA)
0.173;250.3
QK(KA)
0.181;281.2
22(24)
0.018;-815.6
22(28)
0.025;-691.9
22(2Q)
0.052;-568.1
24(23)
0.012;-987.2
(23)(27)
0.029;-691.9
2(23T)
0.025;-801.6
2Q(23)
0.030;-739.7
23(25)
0.011;-956.3
2237
0.008;-1096.9
22(3T)
0.025;-801.6
23(2K)
0.029;-708.8
2(246)
0.015;-894.4
28(24)
0.016;-832.5
(24)(2J)
0.042;-537.2
2244
0.016;-956.3
22(47)
0.020;-863.4
24(2T)
0.026;-770.6
224Q
0.018;-911.3
26(25)
0.019;-863.4
(25)(29)
0.043;-568.1
2(25Q)
0.039;-677.8
22(56)
0.020;-863.4
25(29)
0.029;-770.6
225J
0.017;-911.3
26(26)
0.032;-630.0
(26)(29)
0.050;-537.2
2(26Q)
0.030;-646.9
22(67)
0.017;-801.6
26(2T)
0.028;-708.8
226Q
0.019;-849.4
28(27)
0.026;-739.7
(27)(2J)
0.045;-444.4
2277
0.028;-770.6
22(7T)
0.035;-677.8
27(2K)
0.044;-585.0
2(28T)
0.034;-646.9
2Q(28)
0.038;-585.0
28(2T)
0.030;-646.9
228Q
0.019;-787.5
2T(29)
0.037;-615.9
(29)(2K)
0.075;-320.6
229J
0.025;-787.5
2T(2T)
0.062;-382.5
(2T)(2K)
0.067;-289.7
22TQ
0.027;-725.6
2Q(2J)
0.055;-492.2
2J(2K)
0.066;-461.2
22QQ
0.048;-461.3
3(234)
0.012;-956.3
36(23)
0.017;-894.4
(23)(39)
0.034;-599.1
3(23Q)
0.031;-708.8
5(234)
0.006;-1096.9
9(234)
0.011;-973.1
K(234)
0.020;-849.4
4(237)
0.010;-1035.0
49(23)
0.013;-973.1
(23)(4Q)
0.026;-677.8
(2357)
0.009;-1004.1
(235J)
0.017;-880.3
(23)(56)
0.022;-832.5
5(239)
0.012;-942.2
5J(23)
0.016;-880.3
(2367)
0.013;-973.1
(236J)
0.020;-849.4
(23)(67)
0.020;-770.6
6(23T)
0.020;-880.3
6Q(23)
0.017;-818.4
9(237)
0.018;-880.3
K(237)
0.026;-756.6
7(23T)
0.022;-849.4
7Q(23)
0.024;-787.5
T(238)
0.024;-818.4
8(239)
0.025;-849.4
8J(23)
0.030;-787.5
(239T)
0.019;-787.5
99(23)
0.034;-615.9
(23)(9Q)
0.041;-523.1
(23TQ)
0.039;-694.7
T(23Q)
0.032;-694.7
Q(23J)
0.033;-663.8
(23)(JK)
0.053;-430.3
QK(23)
0.044;-601.9
23(35)
0.012;-925.3
33(28)
0.017;-832.5
233T
0.016;-973.1
23(3K)
0.038;-677.8
(24)(36)
0.016;-863.4
3(249)
0.013;-973.1
3J(24)
0.016;-911.3
(34)(25)
0.019;-894.4
27(34)
0.009;-1035.0
2(34T)
0.016;-942.2
(34)(2K)
0.032;-646.9
34(26)
0.007;-1065.9
34(28)
0.011;-1004.1
34(2T)
0.018;-942.2
34(2Q)
0.019;-880.3
(25)(35)
0.032;-660.9
3(258)
0.011;-973.1
3T(25)
0.017;-911.3
(25)(3K)
0.035;-615.9
27(35)
0.010;-1004.1
2(35T)
0.019;-911.3
(35)(2K)
0.041;-615.9
35(27)
0.012;-1004.1
35(29)
0.014;-942.2
35(2J)
0.013;-880.3
35(2K)
0.022;-818.4
37(26)
0.011;-973.1
(26)(3T)
0.027;-677.8
3(26K)
0.028;-787.5
2(368)
0.013;-942.2
(36)(2J)
0.040;-646.9
2K(36)
0.027;-787.5
23(68)
0.014;-942.2
23(6T)
0.022;-880.3
23(6Q)
0.020;-818.4
3(278)
0.019;-911.3
3T(27)
0.023;-849.4
(27)(3K)
0.034;-554.1
29(37)
0.019;-880.3
2(37Q)
0.024;-787.5
23(78)
0.019;-911.3
23(7T)
0.024;-849.4
23(7Q)
0.019;-787.5
3(289)
0.020;-849.4
3J(28)
0.024;-787.5
(38)(29)
0.034;-646.9
2J(38)
0.024;-787.5
38(29)
0.017;-849.4
38(2J)
0.022;-787.5
38(2K)
0.025;-725.6
3T(29)
0.025;-787.5
(29)(3K)
0.052;-492.2
2J(39)
0.033;-756.6
39(2T)
0.031;-787.5
39(2Q)
0.032;-725.6
(2T)(3T)
0.088;-351.6
3(2TK)
0.029;-663.8
2(3TQ)
0.032;-694.7
23(TJ)
0.028;-725.6
23(TK)
0.033;-663.8
(2J)(3K)
0.058;-430.3
2K(3J)
0.039;-632.8
23(JK)
0.046;-632.8
(3Q)(2K)
0.068;-399.4
(2K)(3K)
0.078;-165.9
4(246)
0.025;-832.5
48(24)
0.027;-770.6
(24)(4J)
0.052;-475.3
5(245)
0.019;-832.5
9(245)
0.019;-911.3
K(245)
0.018;-787.5
5(248)
0.014;-942.2
5T(24)
0.016;-880.3
(24)(5K)
0.041;-585.0
9(246)
0.014;-880.3
K(246)
0.024;-756.6
6(249)
0.014;-880.3
6J(24)
0.017;-818.4
(2478)
0.018;-880.3
(247Q)
0.029;-756.6
7(249)
0.022;-849.4
7J(24)
0.026;-787.5
(2489)
0.019;-818.4
(248K)
0.039;-694.7
8T(24)
0.021;-787.5
(24)(8K)
0.056;-492.2
Q(249)
0.032;-694.7
(24)(9J)
0.038;-523.1
T(24T)
0.050;-523.1
T(24J)
0.028;-694.7
TK(24)
0.034;-632.8
(24)(JQ)
0.060;-430.3
QQ(24)
0.064;-399.4
24(45)
0.022;-863.4
44(28)
0.025;-770.6
244T
0.014;-911.3
24(4K)
0.030;-615.9
(25)(47)
0.029;-770.6
4(25T)
0.018;-880.3
4Q(25)
0.025;-818.4
(45)(27)
0.022;-770.6
29(45)
0.016;-911.3
2(45Q)
0.018;-818.4
24(56)
0.010;-1004.1
24(58)
0.012;-942.2
24(5T)
0.020;-880.3
24(5Q)
0.026;-818.4
4(267)
0.014;-942.2
49(26)
0.020;-880.3
(26)(4Q)
0.037;-585.0
27(46)
0.014;-942.2
2(46T)
0.022;-849.4
(46)(2K)
0.049;-554.1
46(28)
0.014;-911.3
46(2T)
0.019;-849.4
46(2Q)
0.022;-787.5
(27)(47)
0.042;-506.2
4(27T)
0.016;-818.4
4Q(27)
0.020;-756.6
(47)(29)
0.041;-646.9
2J(47)
0.025;-787.5
47(28)
0.016;-880.3
47(2T)
0.021;-818.4
47(2Q)
0.032;-756.6
(28)(48)
0.061;-444.4
4(28J)
0.023;-756.6
4K(28)
0.027;-694.7
(48)(2J)
0.035;-554.1
2K(48)
0.029;-694.7
24(8T)
0.030;-787.5
24(8Q)
0.026;-725.6
4(29T)
0.025;-756.6
4Q(29)
0.023;-694.7
(49)(2J)
0.059;-523.1
2K(49)
0.044;-663.8
24(9J)
0.027;-725.6
24(9K)
0.034;-663.8
(2T)(4Q)
0.045;-461.3
2J(4T)
0.025;-694.7
4T(2J)
0.037;-694.7
4T(2K)
0.033;-632.8
4Q(2J)
0.032;-632.8
(4J)(2K)
0.071;-399.4
4J(2K)
0.042;-601.9
4K(2Q)
0.041;-570.9
24(QK)
0.049;-570.9
(25)(56)
0.042;-568.1
5(259)
0.032;-677.8
5J(25)
0.046;-615.9
(2567)
0.014;-911.3
(256J)
0.022;-787.5
(25)(67)
0.035;-708.8
6(25T)
0.019;-818.4
6Q(25)
0.030;-756.6
9(257)
0.020;-818.4
K(257)
0.030;-694.7
7(25T)
0.022;-787.5
7Q(25)
0.026;-725.6
T(258)
0.024;-756.6
8(259)
0.023;-787.5
8J(25)
0.031;-725.6
(259T)
0.027;-725.6
99(25)
0.043;-554.1
(25)(9Q)
0.069;-461.3
(25TQ)
0.040;-632.8
T(25Q)
0.036;-632.8
Q(25J)
0.045;-601.9
(25)(JK)
0.058;-368.4
QK(25)
0.044;-540.0
25(57)
0.028;-739.7
55(2T)
0.034;-646.9
255Q
0.022;-787.5
57(26)
0.017;-911.3
(26)(5T)
0.029;-615.9
5(26K)
0.034;-725.6
2(568)
0.017;-880.3
(56)(2J)
0.045;-585.0
2K(56)
0.022;-725.6
25(68)
0.016;-880.3
25(6T)
0.019;-818.4
25(6Q)
0.019;-756.6
5(278)
0.017;-849.4
5T(27)
0.023;-787.5
(27)(5K)
0.052;-492.2
29(57)
0.023;-818.4
2(57Q)
0.033;-725.6
25(78)
0.022;-849.4
25(7T)
0.025;-787.5
25(7Q)
0.031;-725.6
5(289)
0.025;-787.5
5J(28)
0.030;-725.6
(58)(29)
0.043;-585.0
2J(58)
0.027;-725.6
58(29)
0.028;-787.5
58(2J)
0.029;-725.6
58(2K)
0.038;-663.8
5T(29)
0.029;-725.6
(29)(5K)
0.050;-430.3
2J(59)
0.027;-694.7
59(2T)
0.034;-725.6
59(2Q)
0.036;-663.8
(2T)(5T)
0.077;-289.7
5(2TK)
0.042;-601.9
2(5TQ)
0.032;-632.8
25(TJ)
0.034;-663.8
25(TK)
0.052;-601.9
(2J)(5K)
0.062;-368.4
2K(5J)
0.049;-570.9
25(JK)
0.035;-570.9
(5Q)(2K)
0.065;-337.5
(2K)(5K)
0.100;-104.1
6(268)
0.034;-646.9
6T(26)
0.047;-585.0
(26)(6K)
0.063;-289.7
T(267)
0.025;-756.6
7(268)
0.018;-818.4
7T(26)
0.019;-756.6
(26)(7K)
0.060;-461.3
J(268)
0.026;-694.7
89(26)
0.024;-756.6
(26)(8Q)
0.064;-461.3
(269J)
0.031;-663.8
(26)(9T)
0.045;-492.2
9(26K)
0.039;-601.9
(26TK)
0.040;-570.9
TQ(26)
0.045;-601.9
K(26J)
0.048;-540.0
Q(26Q)
0.082;-337.5
KK(26)
0.100;-275.6
66(29)
0.037;-615.9
266J
0.033;-756.6
67(27)
0.032;-646.9
(27)(6T)
0.052;-554.1
6(27K)
0.035;-663.8
2(679)
0.024;-787.5
(67)(2Q)
0.040;-492.2
27(68)
0.023;-818.4
27(6T)
0.027;-756.6
27(6Q)
0.032;-694.7
68(28)
0.045;-585.0
(28)(6J)
0.052;-492.2
28(68)
0.034;-585.0
2(68J)
0.034;-694.7
2688
0.031;-787.5
268T
0.013;-928.1
268Q
0.022;-866.3
(29)(6T)
0.049;-492.2
6(29K)
0.037;-601.9
2(69J)
0.032;-663.8
2699
0.028;-725.6
269J
0.019;-866.3
269K
0.028;-804.4
6Q(2T)
0.041;-601.9
(6T)(2Q)
0.060;-399.4
2T(6J)
0.034;-632.8
2T(6K)
0.042;-570.9
6(2JK)
0.049;-540.0
2(6JK)
0.045;-540.0
2J(6K)
0.051;-540.0
2Q(6Q)
0.061;-337.5
26QK
0.024;-711.6
78(27)
0.044;-585.0
(27)(7J)
0.097;-289.7
8(278)
0.048;-554.1
Q(278)
0.039;-632.8
(27)(8T)
0.054;-492.2
8(27K)
0.036;-601.9
(279Q)
0.048;-601.9
9(27J)
0.028;-632.8
9K(27)
0.052;-570.9
TT(27)
0.054;-430.3
(27)(TK)
0.072;-337.5
J(27Q)
0.053;-540.0
K(27Q)
0.051;-478.1
77(28)
0.032;-585.0
277T
0.025;-725.6
27(7K)
0.057;-430.3
(28)(7T)
0.051;-492.2
7(28K)
0.034;-601.9
2(78T)
0.032;-694.7
(78)(2K)
0.052;-399.4
78(2T)
0.039;-694.7
78(2Q)
0.036;-632.8
(29)(79)
0.063;-289.7
7(29Q)
0.049;-601.9
2(79T)
0.031;-663.8
(79)(2K)
0.055;-368.4
79(2J)
0.035;-632.8
79(2K)
0.042;-570.9
7J(2T)
0.034;-601.9
(7T)(2J)
0.062;-399.4
2K(7T)
0.039;-540.0
27(TQ)
0.042;-570.9
7(2JQ)
0.044;-540.0
2(7JQ)
0.043;-540.0
27(JQ)
0.038;-540.0
7(2QK)
0.046;-478.1
7Q(2K)
0.051;-478.1
88(28)
0.062;-320.6
(28)(8J)
0.097;-227.8
9(289)
0.049;-461.2
K(289)
0.051;-540.0
9(28Q)
0.044;-570.9
J(28T)
0.044;-570.9
TJ(28)
0.031;-570.9
(28JQ)
0.052;-509.1
J(28K)
0.056;-478.1
(28)(QK)
0.074;-244.7
88(2T)
0.053;-461.2
288Q
0.037;-601.9
8T(29)
0.031;-632.8
(29)(8K)
0.055;-337.5
2J(89)
0.042;-601.9
89(2T)
0.040;-632.8
89(2Q)
0.048;-570.9
(2T)(8T)
0.066;-196.9
8(2TK)
0.048;-509.1
2(8TQ)
0.036;-540.0
28(TJ)
0.052;-570.9
28(TK)
0.040;-509.1
(2J)(8K)
0.086;-275.6
2K(8J)
0.049;-478.1
28(JK)
0.045;-478.1
(8Q)(2K)
0.078;-244.7
(2K)(8K)
0.117;-11.2
9(29J)
0.064;-368.4
9K(29)
0.081;-306.6
TT(29)
0.063;-368.4
(29)(TK)
0.067;-275.6
J(29Q)
0.046;-478.1
K(29Q)
0.065;-416.2
99(2T)
0.048;-399.4
299Q
0.048;-540.0
9J(2T)
0.037;-540.0
(9T)(2J)
0.077;-337.5
2K(9T)
0.050;-478.1
29(TQ)
0.050;-509.1
9(2JQ)
0.053;-478.1
2(9JQ)
0.060;-478.1
29(JQ)
0.066;-478.1
9(2QK)
0.061;-416.2
9Q(2K)
0.068;-416.2
TT(2T)
0.108;-135.0
(2T)(TK)
0.125;-42.2
J(2TQ)
0.067;-447.2
K(2TQ)
0.071;-385.3
TT(2J)
0.066;-306.6
2TTK
0.058;-447.2
TK(2J)
0.056;-416.2
2TJJ
0.059;-478.1
2TJK
0.047;-618.8
2(TQK)
0.050;-385.3
TK(2K)
0.090;-151.9
(2J)(JK)
0.097;19.7
QK(2J)
0.081;-354.4
2J(JK)
0.070;-182.8
(JQ)(2K)
0.095;-151.9
(2K)(JK)
0.141;81.6
K(2QK)
0.117;-90.0
2K(QK)
0.093;-90.0
3335
0.015;-894.4
3339
0.020;-770.6
333K
0.029;-646.9
36(34)
0.019;-832.5
(34)(39)
0.049;-537.2
3(34Q)
0.042;-646.9
33(45)
0.018;-863.4
34(38)
0.025;-770.6
334T
0.012;-911.3
33(4K)
0.039;-615.9
(35)(37)
0.034;-568.1
3(35T)
0.026;-677.8
3Q(35)
0.039;-615.9
35(37)
0.028;-770.6
3359
0.017;-911.3
33(5Q)
0.037;-615.9
(36)(37)
0.043;-537.2
3(36T)
0.034;-646.9
3Q(36)
0.037;-585.0
36(38)
0.031;-708.8
336T
0.016;-849.4
33(6K)
0.045;-554.1
(37)(39)
0.051;-444.4
3(37Q)
0.037;-554.1
33(78)
0.027;-677.8
37(3J)
0.049;-585.0
337K
0.029;-725.6
3T(38)
0.042;-585.0
(38)(3K)
0.079;-289.7
338T
0.027;-787.5
33(8K)
0.041;-492.2
(39)(3J)
0.073;-320.6
3399
0.033;-585.0
33(9Q)
0.055;-492.2
(3T)(3J)
0.070;-289.7
33TT
0.049;-523.1
33(TK)
0.069;-430.3
(3J)(3K)
0.111;-196.9
33JK
0.046;-601.9
33(QK)
0.058;-368.4
45(34)
0.018;-832.5
(34)(48)
0.036;-537.2
4(34J)
0.037;-646.9
4K(34)
0.051;-585.0
(3459)
0.018;-880.3
(345K)
0.023;-756.6
57(34)
0.013;-942.2
(34)(5T)
0.034;-646.9
5(34K)
0.027;-756.6
(3469)
0.022;-849.4
(346K)
0.037;-725.6
68(34)
0.018;-880.3
(34)(6J)
0.041;-585.0
7(347)
0.040;-677.8
J(347)
0.032;-756.6
78(34)
0.017;-849.4
(34)(7J)
0.037;-554.1
8(348)
0.035;-615.9
Q(348)
0.032;-694.7
(34)(8T)
0.048;-554.1
8(34K)
0.032;-663.8
(349Q)
0.036;-663.8
9(34J)
0.030;-694.7
9K(34)
0.032;-632.8
TT(34)
0.048;-492.2
(34)(TK)
0.055;-399.4
J(34Q)
0.038;-601.9
K(34Q)
0.057;-540.0
44(35)
0.025;-832.5
3447
0.012;-973.1
34(4T)
0.029;-677.8
44(3K)
0.034;-585.0
4(357)
0.018;-942.2
49(35)
0.017;-880.3
(35)(4Q)
0.044;-585.0
36(45)
0.010;-973.1
3(459)
0.018;-880.3
(45)(3Q)
0.043;-585.0
35(46)
0.014;-973.1
35(48)
0.017;-911.3
35(4T)
0.015;-849.4
35(4Q)
0.030;-787.5
46(36)
0.033;-739.7
(36)(49)
0.037;-646.9
4(36Q)
0.034;-756.6
3(467)
0.017;-911.3
(46)(3T)
0.036;-615.9
3Q(46)
0.023;-756.6
3467
0.008;-1113.8
3469
0.009;-1051.9
346J
0.012;-990.0
346K
0.020;-928.1
49(37)
0.019;-818.4
(37)(4Q)
0.039;-523.1
38(47)
0.022;-849.4
3(47J)
0.023;-756.6
3477
0.023;-880.3
3479
0.011;-1020.9
347J
0.015;-959.1
347K
0.015;-897.2
4T(38)
0.026;-756.6
(38)(4K)
0.057;-461.3
3T(48)
0.025;-756.6
3(48K)
0.036;-663.8
38(4T)
0.018;-756.6
38(4Q)
0.030;-694.7
49(39)
0.050;-554.1
(39)(4Q)
0.061;-461.3
3T(49)
0.031;-725.6
3(49K)
0.036;-632.8
39(4J)
0.035;-694.7
39(4K)
0.030;-632.8
4(3TQ)
0.030;-632.8
3(4TJ)
0.037;-663.8
34TT
0.028;-694.7
34TQ
0.018;-835.3
(3J)(4Q)
0.054;-399.4
3Q(4J)
0.042;-601.9
34JQ
0.027;-804.4
(3Q)(4K)
0.050;-337.5
3Q(4K)
0.054;-540.0
5(356)
0.026;-739.7
58(35)
0.032;-677.8
(35)(5J)
0.061;-382.5
6(356)
0.027;-708.8
T(356)
0.029;-787.5
6(357)
0.019;-880.3
69(35)
0.023;-818.4
(35)(6Q)
0.042;-523.1
(3579)
0.023;-787.5
(357K)
0.034;-663.8
79(35)
0.025;-787.5
(35)(7Q)
0.062;-492.2
(358T)
0.025;-725.6
88(35)
0.033;-585.0
(35)(8J)
0.054;-492.2
9(359)
0.054;-523.1
K(359)
0.040;-601.9
9(35Q)
0.035;-632.8
J(35T)
0.039;-632.8
TJ(35)
0.029;-632.8
(35JQ)
0.050;-570.9
J(35K)
0.055;-540.0
(35)(QK)
0.068;-306.6
55(37)
0.027;-708.8
3559
0.017;-849.4
35(5Q)
0.051;-554.1
(36)(57)
0.038;-677.8
5(36T)
0.022;-787.5
5Q(36)
0.034;-725.6
(56)(38)
0.031;-646.9
3T(56)
0.027;-787.5
3(56K)
0.034;-694.7
36(58)
0.019;-849.4
36(5T)
0.031;-787.5
36(5Q)
0.031;-725.6
57(37)
0.032;-646.9
(37)(5T)
0.047;-554.1
5(37K)
0.030;-663.8
3(579)
0.018;-787.5
(57)(3Q)
0.062;-492.2
37(58)
0.021;-818.4
37(5T)
0.023;-756.6
37(5Q)
0.042;-694.7
58(38)
0.038;-585.0
(38)(5J)
0.058;-492.2
38(58)
0.043;-585.0
3(58J)
0.035;-694.7
3588
0.027;-787.5
358T
0.018;-928.1
358Q
0.020;-866.3
(39)(5T)
0.053;-492.2
5(39K)
0.038;-601.9
3(59J)
0.028;-663.8
3599
0.026;-725.6
359J
0.021;-866.3
359K
0.024;-804.4
5Q(3T)
0.029;-601.9
(5T)(3Q)
0.067;-399.4
3T(5J)
0.035;-632.8
3T(5K)
0.038;-570.9
5(3JK)
0.036;-540.0
3(5JK)
0.052;-540.0
3J(5K)
0.042;-540.0
3Q(5Q)
0.056;-337.5
35QK
0.038;-711.6
67(36)
0.040;-646.9
(36)(6T)
0.077;-351.6
6(36K)
0.057;-461.2
(367T)
0.024;-725.6
77(36)
0.038;-615.9
(36)(7T)
0.052;-523.1
7(36K)
0.038;-632.8
(368J)
0.037;-663.8
(36)(89)
0.059;-523.1
8(36Q)
0.037;-632.8
T(369)
0.032;-663.8
9(36T)
0.038;-663.8
9Q(36)
0.031;-601.9
Q(36T)
0.042;-570.9
(36)(TQ)
0.064;-368.4
(36JK)
0.049;-509.1
JK(36)
0.037;-509.1
K(36K)
0.067;-244.7
3668
0.021;-818.4
36(6J)
0.048;-523.1
(37)(67)
0.066;-413.4
6(37T)
0.027;-725.6
6Q(37)
0.036;-663.8
(67)(39)
0.043;-554.1
3J(67)
0.031;-694.7
67(38)
0.024;-787.5
67(3T)
0.034;-725.6
67(3Q)
0.032;-663.8
(38)(68)
0.064;-351.6
6(38J)
0.029;-663.8
6K(38)
0.047;-601.9
(68)(3J)
0.059;-461.3
3K(68)
0.038;-601.9
36(8T)
0.031;-694.7
36(8Q)
0.043;-632.8
6(39T)
0.032;-663.8
6Q(39)
0.040;-601.9
(69)(3J)
0.057;-430.3
3K(69)
0.046;-570.9
36(9J)
0.041;-632.8
36(9K)
0.042;-570.9
(3T)(6Q)
0.074;-368.4
3J(6T)
0.047;-601.9
6T(3J)
0.041;-601.9
6T(3K)
0.044;-540.0
6Q(3J)
0.050;-540.0
(6J)(3K)
0.065;-306.6
6J(3K)
0.054;-509.1
6K(3Q)
0.068;-478.1
36(QK)
0.054;-478.1
(37)(78)
0.058;-351.6
7(37J)
0.054;-461.2
7K(37)
0.074;-399.4
(378Q)
0.033;-601.9
8(37T)
0.041;-663.8
8Q(37)
0.036;-601.9
J(379)
0.028;-601.9
9T(37)
0.033;-632.8
(37)(9K)
0.080;-337.5
K(37T)
0.047;-509.1
T(37K)
0.047;-509.1
JJ(37)
0.088;-337.5
(37QK)
0.044;-447.2
3777
0.044;-585.0
37(7T)
0.054;-492.2
77(3K)
0.057;-399.4
7(38T)
0.034;-663.8
7Q(38)
0.037;-601.9
(78)(3T)
0.054;-461.3
3Q(78)
0.046;-601.9
3789
0.015;-897.2
378J
0.016;-835.3
378K
0.026;-773.4
7J(39)
0.035;-601.9
(79)(3T)
0.061;-430.3
3Q(79)
0.051;-570.9
379T
0.018;-835.3
379Q
0.030;-773.4
(3T)(7J)
0.070;-368.4
3T(7T)
0.061;-399.4
3(7TK)
0.049;-509.1
3T(7Q)
0.059;-540.0
7J(3J)
0.067;-337.5
(7J)(3Q)
0.060;-306.6
3J(7Q)
0.038;-509.1
7Q(3Q)
0.092;-275.6
37QQ
0.055;-478.1
37KK
0.051;-416.2
8(38J)
0.049;-399.4
8K(38)
0.068;-337.5
(389K)
0.037;-509.1
9J(38)
0.037;-570.9
(38TJ)
0.059;-540.0
(38)(TJ)
0.071;-337.5
J(38J)
0.081;-306.6
JQ(38)
0.055;-478.1
Q(38K)
0.067;-416.2
3889
0.032;-663.8
38(8Q)
0.076;-368.4
(39)(8T)
0.057;-399.4
8(39K)
0.048;-509.1
3(89J)
0.039;-570.9
3899
0.039;-632.8
389J
0.023;-773.4
389K
0.033;-711.6
8Q(3T)
0.056;-509.1
(8T)(3Q)
0.083;-306.6
3T(8J)
0.037;-540.0
3T(8K)
0.049;-478.1
8(3JK)
0.053;-447.2
3(8JK)
0.059;-447.2
3J(8K)
0.063;-447.2
3Q(8Q)
0.072;-244.7
38QK
0.039;-618.8
9T(39)
0.068;-368.4
(39)(9K)
0.117;-73.1
K(39T)
0.052;-447.2
T(39K)
0.055;-447.2
JJ(39)
0.091;-275.6
(39QK)
0.048;-385.3
3999
0.063;-399.4
39(9Q)
0.061;-306.6
(3T)(9J)
0.076;-306.6
3T(9T)
0.064;-337.5
3(9TK)
0.047;-447.2
3T(9Q)
0.040;-478.1
9J(3J)
0.080;-275.6
(9J)(3Q)
0.086;-244.7
3J(9Q)
0.049;-447.2
9Q(3Q)
0.098;-213.8
39QQ
0.062;-416.2
39KK
0.065;-354.4
T(3TK)
0.079;-213.8
JJ(3T)
0.095;-244.7
(3TQK)
0.081;-354.4
3TTT
0.092;-306.6
3T(TK)
0.071;-213.8
(3J)(TK)
0.069;-182.8
3K(TJ)
0.057;-385.3
3T(JK)
0.062;-385.3
(TQ)(3K)
0.100;-151.9
(3K)(TK)
0.142;81.6
J(3JK)
0.101;-151.9
(3J)(QK)
0.087;-120.9
JJ(3K)
0.101;-151.9
3Q(JQ)
0.103;-151.9
3JQK
0.062;-525.9
QK(3Q)
0.105;-90.0
QK(3K)
0.105;-59.1
44(46)
0.040;-568.1
44(4T)
0.057;-444.4
(45)(45)
0.066;-365.6
4(458)
0.028;-677.8
4T(45)
0.034;-615.9
(45)(4K)
0.064;-320.6
4457
0.016;-911.3
44(5T)
0.039;-615.9
45(4K)
0.046;-523.1
4(468)
0.037;-646.9
4T(46)
0.039;-585.0
(46)(4K)
0.078;-289.7
4468
0.017;-849.4
44(6J)
0.057;-554.1
(47)(47)
0.070;-241.9
4(47T)
0.043;-554.1
4Q(47)
0.038;-492.2
47(49)
0.047;-585.0
447J
0.027;-725.6
48(48)
0.061;-382.5
(48)(4J)
0.083;-289.7
4488
0.035;-585.0
44(8J)
0.056;-492.2
(49)(49)
0.088;-118.1
4(49Q)
0.057;-430.3
44(9T)
0.048;-492.2
49(4K)
0.059;-399.4
4(4TQ)
0.066;-399.4
44(TJ)
0.057;-430.3
(4J)(4J)
0.117;5.6
44JJ
0.068;-399.4
4Q(4Q)
0.100;-135.0
(4K)(4K)
0.109;129.4
(45)(57)
0.059;-475.3
5(45T)
0.035;-585.0
5Q(45)
0.053;-523.1
8(456)
0.024;-818.4
Q(456)
0.033;-694.7
(45)(68)
0.032;-615.9
6(45J)
0.022;-725.6
6K(45)
0.038;-663.8
(457J)
0.028;-694.7
(45)(78)
0.040;-585.0
7(45J)
0.030;-694.7
7K(45)
0.033;-632.8
(458Q)
0.029;-632.8
8(45T)
0.039;-694.7
8Q(45)
0.044;-632.8
J(459)
0.040;-632.8
9T(45)
0.034;-663.8
(45)(9K)
0.063;-368.4
K(45T)
0.052;-540.0
T(45K)
0.051;-540.0
JJ(45)
0.087;-368.4
(45QK)
0.047;-478.1
4555
0.034;-739.7
45(58)
0.041;-646.9
55(4J)
0.047;-554.1
455K
0.037;-694.7
58(46)
0.018;-818.4
(46)(5J)
0.042;-523.1
46(56)
0.028;-677.8
4(569)
0.024;-787.5
(56)(4Q)
0.063;-492.2
46(57)
0.021;-849.4
46(59)
0.022;-787.5
46(5J)
0.029;-725.6
46(5K)
0.034;-663.8
5(479)
0.023;-756.6
5J(47)
0.039;-694.7
(57)(48)
0.033;-585.0
4T(57)
0.032;-725.6
4(57K)
0.041;-632.8
47(59)
0.025;-756.6
47(5J)
0.040;-694.7
47(5K)
0.045;-632.8
5(48T)
0.030;-694.7
5Q(48)
0.029;-632.8
(58)(4T)
0.039;-492.2
4Q(58)
0.034;-632.8
4589
0.017;-928.1
458J
0.019;-866.3
458K
0.028;-804.4
5J(49)
0.038;-632.8
(59)(4T)
0.051;-461.3
4Q(59)
0.044;-601.9
459T
0.018;-866.3
459Q
0.028;-804.4
(4T)(5J)
0.085;-399.4
4T(5T)
0.066;-430.3
4(5TK)
0.055;-540.0
4T(5Q)
0.042;-570.9
5J(4J)
0.071;-368.4
(5J)(4Q)
0.083;-337.5
4J(5Q)
0.050;-540.0
5Q(4Q)
0.072;-306.6
45QQ
0.049;-509.1
45KK
0.071;-447.2
6(469)
0.034;-554.1
6J(46)
0.041;-492.2
(4678)
0.029;-756.6
(467Q)
0.031;-632.8
7(469)
0.035;-725.6
7J(46)
0.032;-663.8
(4689)
0.032;-694.7
(468K)
0.041;-570.9
8T(46)
0.035;-663.8
(46)(8K)
0.072;-368.4
Q(469)
0.050;-570.9
(46)(9J)
0.056;-399.4
T(46T)
0.052;-399.4
T(46J)
0.033;-570.9
TK(46)
0.043;-509.1
(46)(JQ)
0.090;-306.6
QQ(46)
0.073;-275.6
46(67)
0.040;-615.9
66(4T)
0.064;-523.1
466Q
0.028;-663.8
68(47)
0.022;-756.6
(47)(6J)
0.056;-461.3
47(67)
0.044;-585.0
4(67T)
0.034;-694.7
(67)(4K)
0.072;-399.4
67(49)
0.023;-725.6
67(4J)
0.035;-663.8
67(4K)
0.036;-601.9
69(48)
0.025;-694.7
(48)(6Q)
0.077;-399.4
49(68)
0.031;-694.7
4(68Q)
0.036;-601.9
46(89)
0.032;-694.7
46(8J)
0.029;-632.8
46(8K)
0.054;-570.9
(49)(6J)
0.064;-399.4
49(69)
0.053;-461.2
4(69Q)
0.033;-570.9
46(9T)
0.028;-632.8
46(9Q)
0.039;-570.9
6(4TJ)
0.050;-570.9
6K(4T)
0.056;-509.1
(6T)(4K)
0.080;-306.6
6T(4Q)
0.044;-540.0
(4J)(6J)
0.085;-135.0
4J(6J)
0.076;-337.5
6J(4Q)
0.049;-509.1
(4Q)(6Q)
0.092;-73.1
4K(6Q)
0.052;-447.2
4K(6K)
0.071;-213.8
79(47)
0.058;-492.2
(47)(7Q)
0.108;-196.9
(478T)
0.036;-632.8
88(47)
0.043;-492.2
(47)(8J)
0.067;-399.4
9(479)
0.045;-430.3
K(479)
0.049;-509.1
9(47Q)
0.057;-540.0
J(47T)
0.049;-540.0
TJ(47)
0.048;-540.0
(47JQ)
0.053;-478.1
J(47K)
0.048;-447.2
(47)(QK)
0.092;-213.8
77(49)
0.045;-492.2
477J
0.043;-632.8
78(48)
0.055;-492.2
(48)(7J)
0.060;-399.4
48(78)
0.048;-492.2
4(78J)
0.044;-601.9
4788
0.034;-694.7
478T
0.022;-835.3
478Q
0.028;-773.4
(49)(7T)
0.047;-399.4
7(49K)
0.045;-509.1
4(79J)
0.040;-570.9
4799
0.034;-632.8
479J
0.024;-773.4
479K
0.028;-711.6
7Q(4T)
0.049;-509.1
(7T)(4Q)
0.065;-306.6
4T(7J)
0.054;-540.0
4T(7K)
0.059;-478.1
7(4JK)
0.048;-447.2
4(7JK)
0.051;-447.2
4J(7K)
0.049;-447.2
4Q(7Q)
0.095;-244.7
47QK
0.036;-618.8
89(48)
0.044;-430.3
(48)(8Q)
0.094;-135.0
(489J)
0.044;-540.0
(48)(9T)
0.071;-368.4
9(48K)
0.057;-478.1
(48TK)
0.042;-447.2
TQ(48)
0.043;-478.1
K(48J)
0.063;-416.2
Q(48Q)
0.086;-213.8
KK(48)
0.106;-151.9
88(4J)
0.050;-368.4
488K
0.046;-509.1
8J(49)
0.044;-540.0
(89)(4T)
0.068;-368.4
4Q(89)
0.056;-509.1
489T
0.027;-773.4
489Q
0.037;-711.6
(4T)(8J)
0.077;-306.6
4T(8T)
0.071;-337.5
4(8TK)
0.045;-447.2
4T(8Q)
0.048;-478.1
8J(4J)
0.068;-275.6
(8J)(4Q)
0.103;-244.7
4J(8Q)
0.062;-447.2
8Q(4Q)
0.071;-213.8
48QQ
0.056;-416.2
48KK
0.074;-354.4
9(49Q)
0.084;-275.6
J(49T)
0.058;-478.1
TJ(49)
0.039;-478.1
(49JQ)
0.054;-416.2
J(49K)
0.061;-385.3
(49)(QK)
0.121;-151.9
99(4J)
0.082;-306.6
499K
0.057;-447.2
9Q(4T)
0.042;-447.2
(9T)(4Q)
0.072;-244.7
4T(9J)
0.049;-478.1
4T(9K)
0.067;-416.2
9(4JK)
0.064;-385.3
4(9JK)
0.075;-385.3
4J(9K)
0.078;-385.3
4Q(9Q)
0.089;-182.8
49QK
0.045;-556.9
TJ(4T)
0.082;-244.7
(4TJQ)
0.062;-385.3
J(4TK)
0.073;-354.4
(4T)(QK)
0.125;-120.9
TT(4Q)
0.099;-213.8
T(4JQ)
0.055;-385.3
4(TJQ)
0.061;-385.3
4T(JQ)
0.048;-385.3
T(4QK)
0.068;-323.4
TQ(4K)
0.069;-323.4
JJ(4J)
0.155;19.7
(4JQK)
0.074;-292.5
4JJJ
0.095;-182.8
JQ(4Q)
0.116;-120.9
4JQQ
0.066;-323.4
4JKK
0.062;-261.6
QQ(4K)
0.127;-59.1
4KKK
0.136;2.8
55(59)
0.060;-382.5
55(5K)
0.090;-258.8
(56)(58)
0.064;-382.5
5(56J)
0.047;-492.2
5K(56)
0.070;-430.3
56(59)
0.045;-554.1
556J
0.029;-694.7
57(57)
0.067;-382.5
(57)(5T)
0.064;-289.7
5(57K)
0.065;-399.4
55(79)
0.044;-523.1
57(5Q)
0.049;-430.3
5(589)
0.052;-492.2
5J(58)
0.076;-430.3
58(59)
0.047;-492.2
558J
0.042;-632.8
59(59)
0.084;-258.8
(59)(5Q)
0.086;-165.9
559T
0.035;-632.8
55(9K)
0.074;-337.5
(5T)(5Q)
0.110;-135.0
55TJ
0.037;-570.9
5J(5J)
0.086;-135.0
5J(5Q)
0.071;-306.6
5(5QK)
0.085;-244.7
5K(5K)
0.115;-11.3
68(56)
0.046;-554.1
(56)(6J)
0.063;-258.8
7(567)
0.039;-554.1
J(567)
0.033;-632.8
78(56)
0.027;-725.6
(56)(7J)
0.074;-430.3
8(568)
0.049;-492.2
Q(568)
0.046;-570.9
(56)(8T)
0.058;-430.3
8(56K)
0.045;-540.0
(569Q)
0.040;-540.0
9(56J)
0.051;-570.9
9K(56)
0.045;-509.1
TT(56)
0.071;-368.4
(56)(TK)
0.085;-275.6
J(56Q)
0.051;-478.1
K(56Q)
0.052;-416.2
66(57)
0.046;-585.0
5669
0.030;-725.6
56(6Q)
0.048;-430.3
(57)(68)
0.043;-523.1
6(57J)
0.038;-632.8
6K(57)
0.039;-570.9
(67)(5T)
0.055;-461.3
5Q(67)
0.051;-601.9
5678
0.013;-928.1
567T
0.016;-866.3
567Q
0.018;-804.4
(58)(69)
0.057;-461.3
6(58Q)
0.037;-570.9
5(689)
0.032;-663.8
(68)(5Q)
0.063;-368.4
58(69)
0.030;-663.8
58(6J)
0.033;-601.9
58(6K)
0.035;-540.0
6(59J)
0.042;-570.9
6K(59)
0.045;-509.1
(69)(5Q)
0.067;-337.5
59(6T)
0.040;-601.9
59(6Q)
0.048;-540.0
6T(5T)
0.057;-368.4
(5T)(6K)
0.064;-275.6
5Q(6T)
0.045;-509.1
56TJ
0.031;-742.5
56TK
0.028;-680.6
6K(5J)
0.060;-447.2
56JJ
0.051;-509.1
56JK
0.036;-649.7
5(6QK)
0.059;-416.2
6K(5K)
0.100;-182.8
(57)(79)
0.076;-258.8
7(57Q)
0.064;-368.4
9(578)
0.032;-632.8
K(578)
0.046;-509.1
8(57J)
0.054;-570.9
8K(57)
0.042;-509.1
(579K)
0.058;-478.1
9J(57)
0.040;-540.0
(57TJ)
0.057;-509.1
(57)(TJ)
0.082;-306.6
J(57J)
0.064;-275.6
JQ(57)
0.044;-447.2
Q(57K)
0.065;-385.3
5778
0.026;-694.7
57(7J)
0.059;-399.4
(58)(78)
0.074;-258.8
7(58J)
0.045;-570.9
7K(58)
0.060;-509.1
(78)(5J)
0.073;-368.4
5K(78)
0.057;-509.1
57(8T)
0.032;-601.9
57(8Q)
0.036;-540.0
7(59T)
0.037;-570.9
7Q(59)
0.054;-509.1
(79)(5J)
0.067;-337.5
5K(79)
0.064;-478.1
57(9J)
0.050;-540.0
57(9K)
0.066;-478.1
(5T)(7Q)
0.073;-275.6
5J(7T)
0.045;-509.1
7T(5J)
0.038;-509.1
7T(5K)
0.066;-447.2
7Q(5J)
0.047;-447.2
(7J)(5K)
0.075;-213.8
7J(5K)
0.063;-416.2
7K(5Q)
0.066;-385.3
57(QK)
0.063;-385.3
(58)(89)
0.092;-196.9
8(58Q)
0.058;-306.6
T(589)
0.044;-540.0
9(58T)
0.047;-540.0
9Q(58)
0.058;-478.1
Q(58T)
0.052;-447.2
(58)(TQ)
0.085;-244.7
(58JK)
0.065;-385.3
JK(58)
0.055;-385.3
K(58K)
0.079;-120.9
588T
0.046;-570.9
58(8K)
0.068;-275.6
(59)(8J)
0.067;-306.6
59(89)
0.059;-368.4
5(89Q)
0.049;-478.1
58(9T)
0.054;-540.0
58(9Q)
0.054;-478.1
8(5TJ)
0.057;-478.1
8K(5T)
0.055;-416.2
(8T)(5K)
0.096;-213.8
8T(5Q)
0.046;-447.2
(5J)(8J)
0.105;-42.2
5J(8J)
0.072;-244.7
8J(5Q)
0.049;-416.2
(5Q)(8Q)
0.123;19.7
5K(8Q)
0.080;-354.4
5K(8K)
0.097;-120.9
9J(59)
0.068;-275.6
(59TJ)
0.047;-447.2
(59)(TJ)
0.084;-244.7
J(59J)
0.079;-213.8
JQ(59)
0.073;-385.3
Q(59K)
0.074;-323.4
599T
0.041;-509.1
59(9K)
0.066;-213.8
(5T)(9Q)
0.085;-213.8
5J(9T)
0.047;-447.2
9T(5J)
0.050;-447.2
9T(5K)
0.071;-385.3
9Q(5J)
0.065;-385.3
(9J)(5K)
0.097;-151.9
9J(5K)
0.067;-354.4
9K(5Q)
0.077;-323.4
59(QK)
0.077;-323.4
(5T)(TJ)
0.107;-11.2
J(5TJ)
0.082;-182.8
JQ(5T)
0.074;-354.4
Q(5TK)
0.083;-292.5
5TTJ
0.058;-416.2
TJ(5J)
0.085;-182.8
(TJ)(5Q)
0.099;-151.9
5J(TQ)
0.064;-354.4
TQ(5Q)
0.098;-120.9
5TQQ
0.074;-323.4
5TKK
0.070;-261.6
Q(5JQ)
0.125;-90.0
KK(5J)
0.109;-28.1
(5Q)(JQ)
0.147;112.5
5K(JQ)
0.075;-261.6
5K(JK)
0.108;-28.1
5QQQ
0.094;-59.1
KK(5K)
0.189;236.2
6669
0.044;-492.2
666K
0.052;-368.4
69(67)
0.058;-461.2
(67)(6Q)
0.090;-165.9
6678
0.035;-694.7
66(7J)
0.073;-399.4
(68)(68)
0.112;-56.3
6(68J)
0.061;-368.4
6K(68)
0.093;-306.6
68(6J)
0.058;-368.4
668K
0.037;-509.1
6J(69)
0.068;-337.5
69(6T)
0.061;-368.4
669Q
0.045;-509.1
6J(6T)
0.073;-306.6
6T(6J)
0.083;-306.6
66TK
0.050;-447.2
6K(6J)
0.073;-213.8
(6Q)(6Q)
0.186;191.2
66QK
0.062;-385.3
7(679)
0.043;-430.3
7J(67)
0.058;-368.4
(6789)
0.051;-601.9
(678K)
0.062;-478.1
8T(67)
0.041;-570.9
(67)(8K)
0.078;-275.6
Q(679)
0.061;-478.1
(67)(9J)
0.081;-306.6
T(67T)
0.082;-306.6
T(67J)
0.061;-478.1
TK(67)
0.049;-416.2
(67)(JQ)
0.088;-213.8
QQ(67)
0.110;-182.8
67(78)
0.058;-461.2
77(6J)
0.074;-368.4
677K
0.041;-509.1
7T(68)
0.037;-570.9
(68)(7K)
0.065;-275.6
6T(78)
0.035;-570.9
6(78K)
0.046;-478.1
68(7T)
0.050;-570.9
68(7Q)
0.050;-509.1
79(69)
0.055;-368.4
(69)(7Q)
0.074;-275.6
6T(79)
0.036;-540.0
6(79K)
0.067;-447.2
69(7J)
0.040;-509.1
69(7K)
0.057;-447.2
7(6TQ)
0.044;-447.2
6(7TJ)
0.041;-478.1
67TT
0.052;-509.1
67TQ
0.038;-649.7
(6J)(7Q)
0.083;-213.8
6Q(7J)
0.056;-416.2
67JQ
0.030;-618.8
(6Q)(7K)
0.080;-151.9
6Q(7K)
0.089;-354.4
8(689)
0.070;-368.4
8J(68)
0.068;-306.6
(689T)
0.049;-509.1
99(68)
0.088;-337.5
(68)(9Q)
0.067;-244.7
(68TQ)
0.065;-416.2
T(68Q)
0.051;-416.2
Q(68J)
0.068;-385.3
(68)(JK)
0.081;-151.9
QK(68)
0.075;-323.4
68(8T)
0.063;-337.5
88(6K)
0.078;-244.7
8(69J)
0.045;-478.1
8K(69)
0.076;-416.2
(89)(6Q)
0.080;-244.7
69(8T)
0.054;-509.1
69(8Q)
0.071;-447.2
8T(6T)
0.085;-275.6
(6T)(8K)
0.073;-182.8
6Q(8T)
0.044;-416.2
68TJ
0.039;-649.7
68TK
0.042;-587.8
8K(6J)
0.090;-354.4
68JJ
0.048;-416.2
68JK
0.046;-556.9
6(8QK)
0.059;-323.4
8K(6K)
0.094;-90.0
(69)(9J)
0.120;-42.2
T(69T)
0.085;-244.7
T(69J)
0.053;-416.2
TK(69)
0.065;-354.4
(69)(JQ)
0.078;-151.9
QQ(69)
0.104;-120.9
69(9T)
0.071;-275.6
99(6K)
0.119;-182.8
9(6TQ)
0.070;-385.3
6(9TJ)
0.054;-416.2
69TT
0.064;-447.2
69TQ
0.033;-587.8
(6J)(9Q)
0.098;-151.9
6Q(9J)
0.070;-354.4
69JQ
0.040;-556.9
(6Q)(9K)
0.125;-90.0
6Q(9K)
0.073;-292.5
T(6TJ)
0.084;-182.8
TK(6T)
0.113;-120.9
(6T)(JQ)
0.122;-120.9
QQ(6T)
0.093;-90.0
6T(TJ)
0.082;-182.8
(6J)(TJ)
0.134;50.6
6J(TJ)
0.105;-151.9
TJ(6Q)
0.089;-323.4
(6Q)(TQ)
0.155;112.5
6K(TQ)
0.071;-261.6
6K(TK)
0.137;-28.1
JK(6J)
0.111;-59.1
K(6JK)
0.113;2.8
6JJK
0.084;-261.6
6(JQK)
0.073;-230.6
JK(6K)
0.156;2.8
KK(6Q)
0.136;33.7
6QKK
0.087;-168.8
77(7T)
0.083;-165.9
(78)(78)
0.145;5.6
7(78J)
0.076;-306.6
7K(78)
0.086;-244.7
78(7J)
0.072;-306.6
778K
0.064;-447.2
7J(79)
0.077;-275.6
79(7T)
0.066;-306.6
779Q
0.049;-447.2
7J(7T)
0.083;-244.7
7T(7J)
0.075;-244.7
77TK
0.054;-385.3
7K(7J)
0.111;-151.9
(7Q)(7Q)
0.172;253.1
77QK
0.072;-323.4
8(78T)
0.086;-306.6
8Q(78)
0.070;-244.7
J(789)
0.057;-447.2
9T(78)
0.052;-478.1
(78)(9K)
0.072;-182.8
K(78T)
0.069;-354.4
T(78K)
0.060;-354.4
JJ(78)
0.111;-182.8
(78QK)
0.067;-292.5
7888
0.074;-368.4
78(8J)
0.080;-275.6
(79)(89)
0.105;-104.1
8(79Q)
0.053;-416.2
7(89T)
0.040;-478.1
(89)(7K)
0.077;-182.8
89(7J)
0.070;-447.2
89(7K)
0.060;-385.3
8J(7T)
0.060;-416.2
(8T)(7J)
0.089;-213.8
7K(8T)
0.079;-354.4
78(TQ)
0.046;-385.3
8(7JQ)
0.061;-354.4
7(8JQ)
0.061;-354.4
78(JQ)
0.065;-354.4
8(7QK)
0.059;-292.5
8Q(7K)
0.083;-292.5
99(79)
0.114;-73.1
(79)(9Q)
0.118;19.7
(79TQ)
0.068;-354.4
T(79Q)
0.062;-354.4
Q(79J)
0.056;-323.4
(79)(JK)
0.106;-90.0
QK(79)
0.090;-261.6
79(9J)
0.078;-213.8
(7T)(9T)
0.096;-11.2
9(7TK)
0.066;-323.4
7(9TQ)
0.054;-354.4
79(TJ)
0.058;-385.3
79(TK)
0.078;-323.4
(7J)(9K)
0.122;-90.0
7K(9J)
0.070;-292.5
79(JK)
0.080;-292.5
(9Q)(7K)
0.107;-59.1
(7K)(9K)
0.150;174.4
T(7TQ)
0.109;-120.9
Q(7TJ)
0.080;-292.5
(7T)(JK)
0.105;-59.1
QK(7T)
0.096;-230.6
7T(TQ)
0.105;-120.9
(7J)(TQ)
0.097;-90.0
7Q(TJ)
0.068;-292.5
7TJQ
0.049;-495.0
(7Q)(TK)
0.117;-28.1
7Q(TK)
0.084;-230.6
J(7JQ)
0.118;-59.1
K(7JQ)
0.083;-199.7
JJ(7Q)
0.095;-59.1
J(7QK)
0.076;-199.7
JQ(7K)
0.096;-199.7
QQ(7Q)
0.179;205.3
7Q(QK)
0.110;33.7
8888
0.084;-135.0
888Q
0.084;-213.8
8(89J)
0.093;-213.8
8K(89)
0.111;-151.9
89(8Q)
0.082;-182.8
8(8TJ)
0.110;-182.8
8K(8T)
0.093;-120.9
8T(8K)
0.103;-120.9
8(8JK)
0.097;-90.0
88(JK)
0.099;-90.0
8Q(8K)
0.113;-59.1
(89)(9T)
0.107;-11.2
9(89K)
0.110;-120.9
(89TK)
0.086;-292.5
TQ(89)
0.090;-323.4
K(89J)
0.086;-261.6
Q(89Q)
0.105;-59.1
KK(89)
0.093;2.8
99(8Q)
0.101;-151.9
9(8TJ)
0.063;-354.4
9K(8T)
0.064;-292.5
(9T)(8K)
0.113;-90.0
9T(8Q)
0.052;-323.4
(8J)(9J)
0.110;81.6
8J(9J)
0.080;-120.9
9J(8Q)
0.073;-292.5
(8Q)(9Q)
0.181;143.4
8K(9Q)
0.072;-230.6
8K(9K)
0.154;2.8
TQ(8T)
0.092;-90.0
K(8TJ)
0.082;-230.6
Q(8TQ)
0.127;-28.1
KK(8T)
0.113;33.7
