AAAA
0.383;1650.0
5AAA
0.289;581.3
9AAA
0.299;856.3
KAAA
0.345;1131.3
4A(2A)
0.231;-312.5
(2A)(7A)
0.240;343.7
A(2TA)
0.271;100.0
QA(2A)
0.296;237.5
2A(4A)
0.216;-312.5
26AA
0.182;-625.0
AA(29)
0.276;31.3
2A(QA)
0.288;237.5
A(34A)
0.259;-243.7
6A(3A)
0.228;-106.2
(3A)(9A)
0.291;550.0
A(3QA)
0.290;306.2
AA(34)
0.219;-243.7
3A(7A)
0.289;-37.5
39AA
0.240;-350.0
AA(3Q)
0.322;306.2
(4A)(5A)
0.294;343.7
A(48A)
0.283;100.0
TA(4A)
0.318;237.5
(4A)(KA)
0.265;893.8
46AA
0.238;-487.5
AA(49)
0.305;168.8
4A(QA)
0.348;375.0
A(56A)
0.270;31.3
8A(5A)
0.297;168.8
(5A)(JA)
0.323;825.0
55AA
0.305;-37.5
AA(58)
0.277;168.8
5A(JA)
0.286;375.0
5KAA
0.226;62.5
8A(6A)
0.290;237.5
(6A)(JA)
0.308;893.8
66AA
0.293;100.0
AA(69)
0.318;306.2
6A(QA)
0.267;512.5
A(78A)
0.248;306.2
TA(7A)
0.322;443.8
(7A)(KA)
0.330;1100.0
79AA
0.321;-75.0
AA(7Q)
0.338;581.2
(8A)(9A)
0.338;893.8
A(8QA)
0.345;650.0
AA(89)
0.320;443.8
8A(QA)
0.288;650.0
A(9TA)
0.294;581.2
QA(9A)
0.326;718.7
9A(JA)
0.288;650.0
9KAA
0.244;337.5
QA(TA)
0.316;787.5
TA(QA)
0.269;787.5
A(JQA)
0.308;856.2
AA(JQ)
0.294;856.2
(QA)(KA)
0.288;1443.7
KKAA
0.307;1062.5
2(25A)
0.257;-1068.7
27(2A)
0.239;-931.2
(2T)(2A)
0.289;-275.0
2(2KA)
0.220;-518.7
(236A)
0.194;-1381.2
(23TA)
0.215;-1106.2
33(2A)
0.184;-1137.5
(36)(2A)
0.211;-931.2
3(29A)
0.167;-1175.0
3J(2A)
0.216;-1037.5
(245A)
0.196;-1381.2
(249A)
0.218;-1106.2
(24KA)
0.235;-831.2
46(2A)
0.164;-1312.5
(49)(2A)
0.212;-656.2
4(2QA)
0.245;-900.0
6(25A)
0.214;-1243.8
T(25A)
0.205;-968.7
5(26A)
0.202;-1243.8
58(2A)
0.178;-1106.2
(5J)(2A)
0.227;-450.0
6(26A)
0.263;-725.0
T(26A)
0.210;-900.0
6(27A)
0.167;-1106.2
69(2A)
0.225;-968.7
(6Q)(2A)
0.213;-312.5
(279A)
0.205;-900.0
(27KA)
0.226;-625.0
79(2A)
0.228;-900.0
(7Q)(2A)
0.281;-243.8
(28TA)
0.193;-762.5
88(2A)
0.249;-450.0
(8J)(2A)
0.245;-243.8
9(29A)
0.234;-312.5
K(29A)
0.206;-487.5
9(2QA)
0.221;-556.2
J(2TA)
0.227;-556.2
TJ(2A)
0.282;-556.2
(2JQA)
0.250;-418.7
J(2KA)
0.238;-350.0
(QK)(2A)
0.230;168.8
22(4A)
0.205;-1137.5
226A
0.244;-1450.0
2A(29)
0.254;-793.7
22(QA)
0.284;-587.5
2(34A)
0.183;-1518.8
26(3A)
0.206;-1381.2
(29)(3A)
0.234;-725.0
2(3QA)
0.219;-968.7
A(234)
0.183;-1518.8
(23)(7A)
0.175;-862.5
9A(23)
0.206;-1175.0
A(23Q)
0.166;-968.7
2A(34)
0.203;-1518.8
2A(36)
0.239;-1381.2
2A(38)
0.201;-1243.8
2A(3T)
0.212;-1106.2
2A(3Q)
0.159;-968.7
2(45A)
0.141;-1381.2
27(4A)
0.211;-1243.8
(2T)(4A)
0.227;-587.5
2(4KA)
0.219;-831.2
A(246)
0.203;-1312.5
(24)(9A)
0.223;-656.2
JA(24)
0.168;-968.7
24(5A)
0.187;-1381.2
24(7A)
0.208;-1243.8
24(9A)
0.195;-1106.2
24(JA)
0.176;-968.7
24(KA)
0.188;-831.2
26(5A)
0.192;-1243.8
(29)(5A)
0.233;-587.5
2(5QA)
0.210;-831.2
A(256)
0.161;-1243.8
(25)(9A)
0.240;-587.5
JA(25)
0.239;-900.0
25(6A)
0.182;-1243.8
25(8A)
0.194;-1106.2
25(TA)
0.231;-968.7
25(QA)
0.213;-831.2
(26)(6A)
0.250;-275.0
2(69A)
0.206;-968.7
2J(6A)
0.253;-831.2
(26)(7A)
0.206;-656.2
9A(26)
0.179;-968.7
A(26Q)
0.214;-762.5
2A(67)
0.242;-1106.2
2A(69)
0.179;-968.7
2A(6J)
0.216;-831.2
2A(6K)
0.208;-693.7
(29)(7A)
0.228;-450.0
2(7QA)
0.228;-693.7
A(278)
0.214;-968.7
(27)(JA)
0.274;-312.5
KA(27)
0.251;-625.0
2A(79)
0.167;-900.0
2A(7J)
0.236;-762.5
2A(7K)
0.246;-625.0
(2T)(8A)
0.322;-312.5
2(8KA)
0.263;-556.2
A(28T)
0.250;-762.5
(28)(KA)
0.307;-106.2
28(TA)
0.222;-762.5
28(QA)
0.209;-625.0
(29)(9A)
0.245;137.5
2(9QA)
0.230;-556.2
A(29T)
0.176;-693.7
(29)(KA)
0.288;-37.5
29(JA)
0.280;-625.0
29(KA)
0.256;-487.5
2J(TA)
0.249;-556.2
(2T)(JA)
0.233;-106.2
KA(2T)
0.309;-418.7
2A(TQ)
0.222;-487.5
2(JQA)
0.222;-418.7
A(2JQ)
0.268;-418.7
2A(JQ)
0.248;-418.7
2(QKA)
0.215;-281.2
2Q(KA)
0.262;-281.2
33(3A)
0.213;-618.7
(36)(3A)
0.283;-412.5
3(39A)
0.246;-656.2
3J(3A)
0.222;-518.7
(345A)
0.210;-1312.5
(349A)
0.201;-1037.5
(34KA)
0.203;-762.5
46(3A)
0.182;-1243.8
(49)(3A)
0.228;-587.5
4(3QA)
0.257;-831.2
6(35A)
0.216;-1175.0
T(35A)
0.209;-900.0
5(36A)
0.195;-1175.0
58(3A)
0.252;-1037.5
(5J)(3A)
0.278;-381.2
6(36A)
0.197;-656.2
T(36A)
0.199;-831.2
6(37A)
0.207;-1037.5
69(3A)
0.211;-900.0
(6Q)(3A)
0.233;-243.8
(379A)
0.291;-831.2
(37KA)
0.248;-556.2
79(3A)
0.187;-831.2
(7Q)(3A)
0.291;-175.0
(38TA)
0.249;-693.7
88(3A)
0.255;-381.2
(8J)(3A)
0.241;-175.0
9(39A)
0.251;-243.7
K(39A)
0.236;-418.7
9(3QA)
0.207;-487.5
J(3TA)
0.227;-487.5
TJ(3A)
0.216;-487.5
(3JQA)
0.248;-350.0
J(3KA)
0.225;-281.2
(QK)(3A)
0.262;237.5
33(5A)
0.212;-931.2
337A
0.228;-1243.8
3A(3T)
0.194;-587.5
33(KA)
0.235;-381.2
3(46A)
0.254;-1243.8
38(4A)
0.171;-1106.2
(3J)(4A)
0.255;-450.0
4A(34)
0.170;-931.2
A(347)
0.200;-1175.0
(34)(TA)
0.274;-518.7
QA(34)
0.197;-831.2
345A
0.153;-1762.5
347A
0.185;-1625.0
349A
0.166;-1487.5
34JA
0.184;-1350.0
34KA
0.230;-1212.5
37(5A)
0.189;-1106.2
(3T)(5A)
0.275;-450.0
3(5KA)
0.218;-693.7
A(357)
0.163;-1106.2
(35)(TA)
0.287;-450.0
QA(35)
0.257;-762.5
356A
0.187;-1625.0
358A
0.194;-1487.5
35TA
0.248;-1350.0
35QA
0.179;-1212.5
(37)(6A)
0.214;-587.5
3(6TA)
0.217;-831.2
3Q(6A)
0.223;-693.7
(36)(8A)
0.235;-518.7
TA(36)
0.270;-831.2
A(36K)
0.240;-625.0
6A(38)
0.234;-968.7
6A(3T)
0.194;-831.2
6A(3Q)
0.257;-693.7
37(7A)
0.228;-518.7
(3T)(7A)
0.319;-312.5
3(7KA)
0.246;-556.2
A(379)
0.253;-831.2
(37)(QA)
0.293;-175.0
7A(38)
0.247;-900.0
7A(3T)
0.185;-762.5
7A(3Q)
0.224;-625.0
38(8A)
0.264;-381.2
(3J)(8A)
0.236;-175.0
8A(38)
0.225;-381.2
A(38J)
0.210;-625.0
388A
0.242;-831.2
38TA
0.213;-1143.8
38QA
0.219;-1006.3
(3T)(9A)
0.211;-175.0
3(9KA)
0.253;-418.7
A(39J)
0.245;-556.2
399A
0.228;-693.7
39JA
0.193;-1006.3
39KA
0.177;-868.7
3Q(TA)
0.287;-418.7
(3T)(QA)
0.264;31.3
TA(3J)
0.200;-487.5
TA(3K)
0.215;-350.0
3(JKA)
0.220;-281.2
A(3JK)
0.243;-281.2
JA(3K)
0.299;-281.2
QA(3Q)
0.301;168.8
3QKA
0.276;-662.5
45(4A)
0.222;-793.7
(48)(4A)
0.295;-137.5
4(4JA)
0.220;-381.2
4K(4A)
0.262;-243.7
(459A)
0.202;-900.0
(45KA)
0.209;-625.0
57(4A)
0.174;-1037.5
(5T)(4A)
0.251;-381.2
5(4KA)
0.258;-625.0
(469A)
0.243;-831.2
(46KA)
0.259;-556.2
68(4A)
0.222;-900.0
(6J)(4A)
0.256;-243.8
7(47A)
0.218;-450.0
J(47A)
0.260;-625.0
78(4A)
0.233;-831.2
(7J)(4A)
0.231;-175.0
8(48A)
0.243;-312.5
Q(48A)
0.214;-487.5
(8T)(4A)
0.262;-175.0
8(4KA)
0.219;-418.7
(49QA)
0.220;-418.7
9(4JA)
0.178;-487.5
9K(4A)
0.256;-350.0
TT(4A)
0.304;-37.5
(TK)(4A)
0.296;168.8
J(4QA)
0.244;-281.2
K(4QA)
0.290;-143.7
44(5A)
0.248;-793.7
447A
0.205;-1106.2
4A(4T)
0.217;-450.0
44(KA)
0.314;-243.7
4(57A)
0.212;-1037.5
49(5A)
0.253;-900.0
(4Q)(5A)
0.258;-243.8
6A(45)
0.174;-1106.2
A(459)
0.245;-900.0
(45)(QA)
0.207;-243.8
5A(46)
0.215;-1106.2
5A(48)
0.162;-968.7
5A(4T)
0.189;-831.2
5A(4Q)
0.244;-693.7
46(6A)
0.227;-587.5
(49)(6A)
0.246;-381.2
4(6QA)
0.226;-625.0
A(467)
0.228;-968.7
(46)(TA)
0.262;-312.5
QA(46)
0.206;-625.0
467A
0.176;-1418.7
469A
0.230;-1281.2
46JA
0.220;-1143.8
46KA
0.188;-1006.3
49(7A)
0.242;-762.5
(4Q)(7A)
0.265;-106.2
8A(47)
0.251;-831.2
A(47J)
0.236;-625.0
477A
0.209;-900.0
479A
0.205;-1212.5
47JA
0.210;-1075.0
47KA
0.193;-937.5
4T(8A)
0.214;-625.0
(4K)(8A)
0.303;31.3
TA(48)
0.194;-625.0
A(48K)
0.246;-418.7
8A(4T)
0.246;-625.0
8A(4Q)
0.238;-487.5
49(9A)
0.259;-175.0
(4Q)(9A)
0.283;31.3
TA(49)
0.270;-556.2
A(49K)
0.216;-350.0
9A(4J)
0.225;-487.5
9A(4K)
0.206;-350.0
4(TQA)
0.289;-350.0
A(4TJ)
0.187;-418.7
4TTA
0.187;-487.5
4TQA
0.252;-800.0
(4Q)(JA)
0.245;168.8
QA(4J)
0.187;-281.2
4JQA
0.185;-731.2
(4K)(QA)
0.262;306.2
QA(4K)
0.268;-143.7
5(56A)
0.262;-587.5
58(5A)
0.239;-450.0
(5J)(5A)
0.287;206.3
6(56A)
0.254;-518.7
T(56A)
0.244;-693.7
6(57A)
0.203;-900.0
69(5A)
0.192;-762.5
(6Q)(5A)
0.295;-106.2
(579A)
0.216;-693.7
(57KA)
0.243;-418.7
79(5A)
0.203;-693.7
(7Q)(5A)
0.280;-37.5
(58TA)
0.205;-556.2
88(5A)
0.288;-243.7
(8J)(5A)
0.238;-37.5
9(59A)
0.318;-106.2
K(59A)
0.266;-281.2
9(5QA)
0.276;-350.0
J(5TA)
0.219;-350.0
TJ(5A)
0.247;-350.0
(5JQA)
0.266;-212.5
J(5KA)
0.259;-143.7
(QK)(5A)
0.293;375.0
55(7A)
0.208;-518.7
559A
0.201;-831.2
5A(5Q)
0.219;-175.0
(57)(6A)
0.250;-450.0
5(6TA)
0.271;-693.7
5Q(6A)
0.237;-556.2
(56)(8A)
0.247;-381.2
TA(56)
0.187;-693.7
A(56K)
0.219;-487.5
6A(58)
0.190;-831.2
6A(5T)
0.212;-693.7
6A(5Q)
0.222;-556.2
57(7A)
0.235;-381.2
(5T)(7A)
0.217;-175.0
5(7KA)
0.245;-418.7
A(579)
0.168;-693.7
(57)(QA)
0.234;-37.5
7A(58)
0.210;-762.5
7A(5T)
0.185;-625.0
7A(5Q)
0.239;-487.5
58(8A)
0.198;-243.7
(5J)(8A)
0.253;-37.5
8A(58)
0.285;-243.7
A(58J)
0.311;-487.5
588A
0.201;-693.7
58TA
0.216;-1006.3
58QA
0.225;-868.7
(5T)(9A)
0.279;-37.5
5(9KA)
0.230;-281.2
A(59J)
0.234;-418.7
599A
0.221;-556.2
59JA
0.165;-868.7
59KA
0.206;-731.2
5Q(TA)
0.216;-281.2
(5T)(QA)
0.331;168.8
TA(5J)
0.286;-350.0
TA(5K)
0.244;-212.5
5(JKA)
0.224;-143.7
A(5JK)
0.215;-143.7
JA(5K)
0.289;-143.7
QA(5Q)
0.254;306.2
5QKA
0.245;-525.0
67(6A)
0.267;-381.2
(6T)(6A)
0.246;275.0
6(6KA)
0.295;31.3
(67TA)
0.178;-556.2
77(6A)
0.192;-312.5
(7T)(6A)
0.281;-106.2
7(6KA)
0.248;-350.0
(68JA)
0.284;-418.7
(89)(6A)
0.256;-106.2
8(6QA)
0.190;-350.0
T(69A)
0.283;-418.7
9(6TA)
0.229;-418.7
9Q(6A)
0.265;-281.2
Q(6TA)
0.257;-212.5
(TQ)(6A)
0.269;237.5
(6JKA)
0.243;-75.0
JK(6A)
0.222;-75.0
K(6KA)
0.263;512.5
668A
0.254;-762.5
6A(6J)
0.271;-106.2
(67)(7A)
0.287;137.5
6(7TA)
0.183;-556.2
6Q(7A)
0.240;-418.7
(67)(9A)
0.314;-175.0
JA(67)
0.230;-487.5
67(8A)
0.193;-693.7
67(TA)
0.255;-556.2
67(QA)
0.223;-418.7
(68)(8A)
0.304;275.0
6(8JA)
0.255;-418.7
6K(8A)
0.231;-281.2
(68)(JA)
0.258;31.3
KA(68)
0.213;-281.2
6A(8T)
0.229;-487.5
6A(8Q)
0.245;-350.0
6(9TA)
0.227;-418.7
6Q(9A)
0.260;-281.2
(69)(JA)
0.275;100.0
KA(69)
0.281;-212.5
6A(9J)
0.263;-350.0
6A(9K)
0.320;-212.5
(6Q)(TA)
0.234;237.5
JA(6T)
0.302;-281.2
6T(JA)
0.242;-281.2
6T(KA)
0.283;-143.7
6Q(JA)
0.194;-143.7
(6J)(KA)
0.250;375.0
6J(KA)
0.224;-75.0
6K(QA)
0.237;-6.2
6A(QK)
0.287;-6.2
(78)(7A)
0.291;275.0
7(7JA)
0.259;31.3
7K(7A)
0.215;168.8
(78QA)
0.221;-281.2
8(7TA)
0.250;-418.7
8Q(7A)
0.207;-281.2
J(79A)
0.278;-281.2
9T(7A)
0.281;-350.0
(9K)(7A)
0.245;306.2
K(7TA)
0.268;-75.0
T(7KA)
0.316;-75.0
JJ(7A)
0.293;306.2
(7QKA)
0.316;62.5
777A
0.287;-243.8
7A(7T)
0.297;-37.5
77(KA)
0.273;168.8
7(8TA)
0.296;-418.7
7Q(8A)
0.222;-281.2
(78)(TA)
0.228;31.3
QA(78)
0.255;-281.2
789A
0.233;-937.5
78JA
0.191;-800.0
78KA
0.271;-662.5
7J(9A)
0.223;-281.2
(79)(TA)
0.249;100.0
QA(79)
0.294;-212.5
79TA
0.249;-800.0
79QA
0.272;-662.5
(7J)(TA)
0.220;237.5
TA(7T)
0.284;168.8
A(7TK)
0.265;-75.0
TA(7Q)
0.255;-143.7
7J(JA)
0.246;306.2
(7J)(QA)
0.249;375.0
JA(7Q)
0.277;-75.0
7Q(QA)
0.338;443.8
7QQA
0.261;-6.2
7KKA
0.328;131.2
8(8JA)
0.292;168.8
8K(8A)
0.303;306.2
(89KA)
0.267;-75.0
9J(8A)
0.236;-212.5
(8TJA)
0.260;-143.7
(TJ)(8A)
0.260;306.2
J(8JA)
0.293;375.0
JQ(8A)
0.291;-6.2
Q(8KA)
0.280;131.2
889A
0.197;-418.7
8A(8Q)
0.221;237.5
(8T)(9A)
0.336;168.8
8(9KA)
0.260;-75.0
A(89J)
0.220;-212.5
899A
0.192;-350.0
89JA
0.217;-662.5
89KA
0.237;-525.0
8Q(TA)
0.294;-75.0
(8T)(QA)
0.267;375.0
TA(8J)
0.237;-143.7
TA(8K)
0.268;-6.2
8(JKA)
0.303;62.5
A(8JK)
0.239;62.5
JA(8K)
0.262;62.5
QA(8Q)
0.259;512.5
8QKA
0.213;-318.7
9T(9A)
0.292;237.5
(9K)(9A)
0.334;893.8
K(9TA)
0.270;62.5
T(9KA)
0.279;62.5
JJ(9A)
0.254;443.8
(9QKA)
0.289;200.0
999A
0.242;168.8
9A(9Q)
0.276;375.0
(9J)(TA)
0.262;375.0
TA(9T)
0.280;306.2
A(9TK)
0.318;62.5
TA(9Q)
0.271;-6.2
9J(JA)
0.282;443.8
(9J)(QA)
0.300;512.5
JA(9Q)
0.309;62.5
9Q(QA)
0.306;581.2
9QQA
0.228;131.2
9KKA
0.279;268.8
T(TKA)
0.278;581.2
JJ(TA)
0.307;512.5
(TQKA)
0.289;268.8
TTTA
0.302;375.0
TA(TK)
0.362;581.2
(TK)(JA)
0.281;650.0
KA(TJ)
0.297;200.0
TA(JK)
0.221;200.0
(TQ)(KA)
0.339;718.7
(TK)(KA)
0.332;1237.5
J(JKA)
0.299;718.7
(QK)(JA)
0.268;787.5
JJ(KA)
0.256;718.7
QA(JQ)
0.327;718.7
JQKA
0.264;-112.5
QK(QA)
0.297;856.2
QK(KA)
0.319;925.0
22(24)
0.196;-1512.5
22(28)
0.181;-1237.5
22(2Q)
0.277;-962.5
24(23)
0.158;-1893.7
(23)(27)
0.261;-1237.5
2(23T)
0.180;-1481.2
2Q(23)
0.191;-1343.7
23(25)
0.171;-1825.0
2237
0.132;-2137.5
22(3T)
0.210;-1481.2
23(2K)
0.184;-1275.0
2(246)
0.202;-1687.5
28(24)
0.199;-1550.0
(24)(2J)
0.221;-893.7
2244
0.166;-1825.0
22(47)
0.225;-1618.8
24(2T)
0.191;-1412.5
224Q
0.176;-1725.0
26(25)
0.209;-1618.8
(25)(29)
0.235;-962.5
2(25Q)
0.226;-1206.2
22(56)
0.239;-1618.8
25(29)
0.206;-1412.5
225J
0.157;-1725.0
26(26)
0.197;-1100.0
(26)(29)
0.246;-893.7
2(26Q)
0.172;-1137.5
22(67)
0.204;-1481.2
26(2T)
0.194;-1275.0
226Q
0.166;-1587.5
28(27)
0.186;-1343.7
(27)(2J)
0.260;-687.5
2277
0.171;-1412.5
22(7T)
0.159;-1206.2
27(2K)
0.218;-1000.0
2(28T)
0.259;-1137.5
2Q(28)
0.233;-1000.0
28(2T)
0.181;-1137.5
228Q
0.213;-1450.0
2T(29)
0.248;-1068.7
(29)(2K)
0.255;-412.5
229J
0.185;-1450.0
2T(2T)
0.258;-550.0
(2T)(2K)
0.266;-343.7
22TQ
0.176;-1312.5
2Q(2J)
0.210;-793.7
2J(2K)
0.194;-725.0
22QQ
0.215;-725.0
3(234)
0.202;-1825.0
36(23)
0.171;-1687.5
(23)(39)
0.214;-1031.2
3(23Q)
0.184;-1275.0
5(234)
0.185;-2137.5
9(234)
0.162;-1862.5
K(234)
0.150;-1587.5
4(237)
0.164;-2000.0
49(23)
0.148;-1862.5
(23)(4Q)
0.224;-1206.2
(2357)
0.146;-1931.2
(235J)
0.185;-1656.3
(23)(56)
0.156;-1550.0
5(239)
0.182;-1793.7
5J(23)
0.175;-1656.3
(2367)
0.159;-1862.5
(236J)
0.201;-1587.5
(23)(67)
0.212;-1412.5
6(23T)
0.171;-1656.3
6Q(23)
0.195;-1518.8
9(237)
0.210;-1656.3
K(237)
0.228;-1381.2
7(23T)
0.168;-1587.5
7Q(23)
0.190;-1450.0
T(238)
0.150;-1518.8
8(239)
0.184;-1587.5
8J(23)
0.213;-1450.0
(239T)
0.195;-1450.0
99(23)
0.175;-1068.7
(23)(9Q)
0.250;-862.5
(23TQ)
0.180;-1243.8
T(23Q)
0.233;-1243.8
Q(23J)
0.177;-1175.0
(23)(JK)
0.206;-656.2
QK(23)
0.198;-1037.5
23(35)
0.198;-1756.2
33(28)
0.187;-1550.0
233T
0.149;-1862.5
23(3K)
0.198;-1206.2
(24)(36)
0.154;-1618.8
3(249)
0.164;-1862.5
3J(24)
0.161;-1725.0
(34)(25)
0.178;-1687.5
27(34)
0.134;-2000.0
2(34T)
0.195;-1793.7
(34)(2K)
0.217;-1137.5
34(26)
0.162;-2068.7
34(28)
0.171;-1931.2
34(2T)
0.168;-1793.7
34(2Q)
0.174;-1656.3
(25)(35)
0.217;-1168.8
3(258)
0.180;-1862.5
3T(25)
0.153;-1725.0
(25)(3K)
0.205;-1068.7
27(35)
0.183;-1931.2
2(35T)
0.165;-1725.0
(35)(2K)
0.210;-1068.7
35(27)
0.207;-1931.2
35(29)
0.162;-1793.7
35(2J)
0.203;-1656.3
35(2K)
0.190;-1518.8
37(26)
0.175;-1862.5
(26)(3T)
0.201;-1206.2
3(26K)
0.178;-1450.0
2(368)
0.165;-1793.7
(36)(2J)
0.189;-1137.5
2K(36)
0.221;-1450.0
23(68)
0.158;-1793.7
23(6T)
0.190;-1656.3
23(6Q)
0.161;-1518.8
3(278)
0.214;-1725.0
3T(27)
0.203;-1587.5
(27)(3K)
0.226;-931.2
29(37)
0.187;-1656.3
2(37Q)
0.224;-1450.0
23(78)
0.204;-1725.0
23(7T)
0.219;-1587.5
23(7Q)
0.159;-1450.0
3(289)
0.194;-1587.5
3J(28)
0.181;-1450.0
(38)(29)
0.207;-1137.5
2J(38)
0.160;-1450.0
38(29)
0.188;-1587.5
38(2J)
0.196;-1450.0
38(2K)
0.208;-1312.5
3T(29)
0.208;-1450.0
(29)(3K)
0.215;-793.8
2J(39)
0.196;-1381.2
39(2T)
0.199;-1450.0
39(2Q)
0.194;-1312.5
(2T)(3T)
0.298;-481.2
3(2TK)
0.197;-1175.0
2(3TQ)
0.208;-1243.8
23(TJ)
0.190;-1312.5
23(TK)
0.183;-1175.0
(2J)(3K)
0.276;-656.2
2K(3J)
0.191;-1106.2
23(JK)
0.183;-1106.2
(3Q)(2K)
0.179;-587.5
(2K)(3K)
0.201;-68.8
4(246)
0.182;-1550.0
48(24)
0.183;-1412.5
(24)(4J)
0.171;-756.3
5(245)
0.175;-1550.0
9(245)
0.204;-1725.0
K(245)
0.162;-1450.0
5(248)
0.199;-1793.7
5T(24)
0.206;-1656.3
(24)(5K)
0.182;-1000.0
9(246)
0.203;-1656.3
K(246)
0.204;-1381.2
6(249)
0.168;-1656.3
6J(24)
0.215;-1518.8
(2478)
0.176;-1656.3
(247Q)
0.173;-1381.2
7(249)
0.173;-1587.5
7J(24)
0.179;-1450.0
(2489)
0.175;-1518.8
(248K)
0.172;-1243.8
8T(24)
0.201;-1450.0
(24)(8K)
0.211;-793.8
Q(249)
0.214;-1243.8
(24)(9J)
0.257;-862.5
T(24T)
0.225;-862.5
T(24J)
0.211;-1243.8
TK(24)
0.209;-1106.2
(24)(JQ)
0.222;-656.2
QQ(24)
0.235;-587.5
24(45)
0.178;-1618.8
44(28)
0.176;-1412.5
244T
0.170;-1725.0
24(4K)
0.211;-1068.7
(25)(47)
0.184;-1412.5
4(25T)
0.177;-1656.3
4Q(25)
0.172;-1518.8
(45)(27)
0.207;-1412.5
29(45)
0.147;-1725.0
2(45Q)
0.186;-1518.8
24(56)
0.169;-1931.2
24(58)
0.192;-1793.7
24(5T)
0.192;-1656.3
24(5Q)
0.228;-1518.8
4(267)
0.190;-1793.7
49(26)
0.165;-1656.3
(26)(4Q)
0.253;-1000.0
27(46)
0.187;-1793.7
2(46T)
0.181;-1587.5
(46)(2K)
0.168;-931.2
46(28)
0.163;-1725.0
46(2T)
0.154;-1587.5
46(2Q)
0.180;-1450.0
(27)(47)
0.227;-825.0
4(27T)
0.136;-1518.8
4Q(27)
0.185;-1381.2
(47)(29)
0.204;-1137.5
2J(47)
0.170;-1450.0
47(28)
0.180;-1656.3
47(2T)
0.236;-1518.8
47(2Q)
0.179;-1381.2
(28)(48)
0.226;-687.5
4(28J)
0.171;-1381.2
4K(28)
0.196;-1243.8
(48)(2J)
0.273;-931.2
2K(48)
0.204;-1243.8
24(8T)
0.231;-1450.0
24(8Q)
0.183;-1312.5
4(29T)
0.163;-1381.2
4Q(29)
0.176;-1243.8
(49)(2J)
0.253;-862.5
2K(49)
0.215;-1175.0
24(9J)
0.203;-1312.5
24(9K)
0.217;-1175.0
(2T)(4Q)
0.209;-725.0
2J(4T)
0.180;-1243.8
4T(2J)
0.189;-1243.8
4T(2K)
0.237;-1106.2
4Q(2J)
0.210;-1106.2
(4J)(2K)
0.217;-587.5
4J(2K)
0.194;-1037.5
4K(2Q)
0.265;-968.7
24(QK)
0.212;-968.7
(25)(56)
0.189;-962.5
5(259)
0.163;-1206.2
5J(25)
0.220;-1068.7
(2567)
0.164;-1725.0
(256J)
0.217;-1450.0
(25)(67)
0.180;-1275.0
6(25T)
0.212;-1518.8
6Q(25)
0.147;-1381.2
9(257)
0.198;-1518.8
K(257)
0.206;-1243.8
7(25T)
0.164;-1450.0
7Q(25)
0.180;-1312.5
T(258)
0.176;-1381.2
8(259)
0.201;-1450.0
8J(25)
0.209;-1312.5
(259T)
0.152;-1312.5
99(25)
0.191;-931.2
(25)(9Q)
0.226;-725.0
(25TQ)
0.192;-1106.2
T(25Q)
0.263;-1106.2
Q(25J)
0.169;-1037.5
(25)(JK)
0.279;-518.7
QK(25)
0.181;-900.0
25(57)
0.251;-1343.7
55(2T)
0.261;-1137.5
255Q
0.145;-1450.0
57(26)
0.140;-1725.0
(26)(5T)
0.207;-1068.7
5(26K)
0.204;-1312.5
2(568)
0.151;-1656.3
(56)(2J)
0.193;-1000.0
2K(56)
0.169;-1312.5
25(68)
0.168;-1656.3
25(6T)
0.194;-1518.8
25(6Q)
0.162;-1381.2
5(278)
0.155;-1587.5
5T(27)
0.240;-1450.0
(27)(5K)
0.202;-793.8
29(57)
0.193;-1518.8
2(57Q)
0.188;-1312.5
25(78)
0.198;-1587.5
25(7T)
0.228;-1450.0
25(7Q)
0.184;-1312.5
5(289)
0.168;-1450.0
5J(28)
0.206;-1312.5
(58)(29)
0.209;-1000.0
2J(58)
0.179;-1312.5
58(29)
0.199;-1450.0
58(2J)
0.236;-1312.5
58(2K)
0.203;-1175.0
5T(29)
0.226;-1312.5
(29)(5K)
0.218;-656.2
2J(59)
0.187;-1243.8
59(2T)
0.166;-1312.5
59(2Q)
0.197;-1175.0
(2T)(5T)
0.251;-343.7
5(2TK)
0.206;-1037.5
2(5TQ)
0.181;-1106.2
25(TJ)
0.212;-1175.0
25(TK)
0.206;-1037.5
(2J)(5K)
0.219;-518.7
2K(5J)
0.219;-968.7
25(JK)
0.207;-968.7
(5Q)(2K)
0.268;-450.0
(2K)(5K)
0.263;68.8
6(268)
0.191;-1137.5
6T(26)
0.219;-1000.0
(26)(6K)
0.265;-343.7
T(267)
0.192;-1381.2
7(268)
0.202;-1518.8
7T(26)
0.144;-1381.2
(26)(7K)
0.201;-725.0
J(268)
0.210;-1243.8
89(26)
0.193;-1381.2
(26)(8Q)
0.234;-725.0
(269J)
0.248;-1175.0
(26)(9T)
0.218;-793.8
9(26K)
0.206;-1037.5
(26TK)
0.196;-968.7
TQ(26)
0.176;-1037.5
K(26J)
0.184;-900.0
Q(26Q)
0.241;-450.0
KK(26)
0.238;-312.5
66(29)
0.212;-1068.7
266J
0.203;-1381.2
67(27)
0.169;-1137.5
(27)(6T)
0.220;-931.2
6(27K)
0.224;-1175.0
2(679)
0.191;-1450.0
(67)(2Q)
0.224;-793.8
27(68)
0.172;-1518.8
27(6T)
0.191;-1381.2
27(6Q)
0.197;-1243.8
68(28)
0.231;-1000.0
(28)(6J)
0.239;-793.8
28(68)
0.207;-1000.0
2(68J)
0.188;-1243.8
2688
0.185;-1450.0
268T
0.210;-1762.5
268Q
0.174;-1625.0
(29)(6T)
0.208;-793.8
6(29K)
0.233;-1037.5
2(69J)
0.203;-1175.0
2699
0.205;-1312.5
269J
0.229;-1625.0
269K
0.178;-1487.5
6Q(2T)
0.207;-1037.5
(6T)(2Q)
0.253;-587.5
2T(6J)
0.238;-1106.2
2T(6K)
0.273;-968.7
6(2JK)
0.247;-900.0
2(6JK)
0.183;-900.0
2J(6K)
0.251;-900.0
2Q(6Q)
0.253;-450.0
26QK
0.205;-1281.2
78(27)
0.201;-1000.0
(27)(7J)
0.272;-343.7
8(278)
0.212;-931.2
Q(278)
0.224;-1106.2
(27)(8T)
0.235;-793.8
8(27K)
0.186;-1037.5
(279Q)
0.186;-1037.5
9(27J)
0.224;-1106.2
9K(27)
0.256;-968.7
TT(27)
0.198;-656.2
(27)(TK)
0.228;-450.0
J(27Q)
0.232;-900.0
K(27Q)
0.210;-762.5
77(28)
0.173;-1000.0
277T
0.174;-1312.5
27(7K)
0.243;-656.2
(28)(7T)
0.266;-793.8
7(28K)
0.247;-1037.5
2(78T)
0.222;-1243.8
(78)(2K)
0.235;-587.5
78(2T)
0.192;-1243.8
78(2Q)
0.252;-1106.2
(29)(79)
0.239;-343.7
7(29Q)
0.216;-1037.5
2(79T)
0.156;-1175.0
(79)(2K)
0.267;-518.7
79(2J)
0.166;-1106.2
79(2K)
0.165;-968.7
7J(2T)
0.186;-1037.5
(7T)(2J)
0.198;-587.5
2K(7T)
0.235;-900.0
27(TQ)
0.217;-968.7
7(2JQ)
0.267;-900.0
2(7JQ)
0.172;-900.0
27(JQ)
0.237;-900.0
7(2QK)
0.257;-762.5
7Q(2K)
0.239;-762.5
88(28)
0.291;-412.5
(28)(8J)
0.197;-206.2
9(289)
0.261;-725.0
K(289)
0.250;-900.0
9(28Q)
0.194;-968.7
J(28T)
0.201;-968.7
TJ(28)
0.211;-968.7
(28JQ)
0.216;-831.2
J(28K)
0.211;-762.5
(28)(QK)
0.219;-243.8
88(2T)
0.197;-725.0
288Q
0.251;-1037.5
8T(29)
0.169;-1106.2
(29)(8K)
0.183;-450.0
2J(89)
0.227;-1037.5
89(2T)
0.241;-1106.2
89(2Q)
0.216;-968.7
(2T)(8T)
0.279;-137.5
8(2TK)
0.240;-831.2
2(8TQ)
0.193;-900.0
28(TJ)
0.200;-968.7
28(TK)
0.261;-831.2
(2J)(8K)
0.243;-312.5
2K(8J)
0.200;-762.5
28(JK)
0.168;-762.5
(8Q)(2K)
0.212;-243.8
(2K)(8K)
0.338;275.0
9(29J)
0.251;-518.7
9K(29)
0.249;-381.2
TT(29)
0.199;-518.7
(29)(TK)
0.277;-312.5
J(29Q)
0.246;-762.5
K(29Q)
0.215;-625.0
99(2T)
0.227;-587.5
299Q
0.206;-900.0
9J(2T)
0.231;-900.0
(9T)(2J)
0.259;-450.0
2K(9T)
0.221;-762.5
29(TQ)
0.210;-831.2
9(2JQ)
0.201;-762.5
2(9JQ)
0.244;-762.5
29(JQ)
0.223;-762.5
9(2QK)
0.203;-625.0
9Q(2K)
0.206;-625.0
TT(2T)
0.262;0.0
(2T)(TK)
0.310;206.3
J(2TQ)
0.235;-693.7
K(2TQ)
0.220;-556.2
TT(2J)
0.310;-381.2
2TTK
0.217;-693.7
TK(2J)
0.231;-625.0
2TJJ
0.233;-762.5
2TJK
0.187;-1075.0
2(TQK)
0.250;-556.2
TK(2K)
0.238;-37.5
(2J)(JK)
0.317;343.7
QK(2J)
0.237;-487.5
2J(JK)
0.241;-106.2
(JQ)(2K)
0.255;-37.5
(2K)(JK)
0.303;481.3
K(2QK)
0.261;100.0
2K(QK)
0.262;100.0
3335
0.211;-1687.5
3339
0.198;-1412.5
333K
0.178;-1137.5
36(34)
0.143;-1550.0
(34)(39)
0.219;-893.7
3(34Q)
0.184;-1137.5
33(45)
0.182;-1618.8
34(38)
0.196;-1412.5
334T
0.181;-1725.0
33(4K)
0.205;-1068.7
(35)(37)
0.226;-962.5
3(35T)
0.199;-1206.2
3Q(35)
0.225;-1068.7
35(37)
0.181;-1412.5
3359
0.148;-1725.0
33(5Q)
0.174;-1068.7
(36)(37)
0.234;-893.7
3(36T)
0.167;-1137.5
3Q(36)
0.234;-1000.0
36(38)
0.256;-1275.0
336T
0.168;-1587.5
33(6K)
0.259;-931.2
(37)(39)
0.241;-687.5
3(37Q)
0.210;-931.2
33(78)
0.223;-1206.2
37(3J)
0.201;-1000.0
337K
0.200;-1312.5
3T(38)
0.215;-1000.0
(38)(3K)
0.291;-343.7
338T
0.227;-1450.0
33(8K)
0.230;-793.7
(39)(3J)
0.230;-412.5
3399
0.187;-1000.0
33(9Q)
0.200;-793.7
(3T)(3J)
0.212;-343.7
33TT
0.206;-862.5
33(TK)
0.196;-656.2
(3J)(3K)
0.308;-137.5
33JK
0.189;-1037.5
33(QK)
0.224;-518.7
45(34)
0.218;-1550.0
(34)(48)
0.212;-893.7
4(34J)
0.203;-1137.5
4K(34)
0.216;-1000.0
(3459)
0.235;-1656.3
(345K)
0.182;-1381.2
57(34)
0.151;-1793.7
(34)(5T)
0.191;-1137.5
5(34K)
0.207;-1381.2
(3469)
0.212;-1587.5
(346K)
0.197;-1312.5
68(34)
0.206;-1656.3
(34)(6J)
0.241;-1000.0
7(347)
0.196;-1206.2
J(347)
0.151;-1381.2
78(34)
0.172;-1587.5
(34)(7J)
0.233;-931.2
8(348)
0.233;-1068.7
Q(348)
0.161;-1243.8
(34)(8T)
0.262;-931.2
8(34K)
0.264;-1175.0
(349Q)
0.185;-1175.0
9(34J)
0.202;-1243.8
9K(34)
0.208;-1106.2
TT(34)
0.237;-793.7
(34)(TK)
0.281;-587.5
J(34Q)
0.235;-1037.5
K(34Q)
0.229;-900.0
44(35)
0.161;-1550.0
3447
0.167;-1862.5
34(4T)
0.227;-1206.2
44(3K)
0.221;-1000.0
4(357)
0.190;-1793.7
49(35)
0.200;-1656.3
(35)(4Q)
0.232;-1000.0
36(45)
0.138;-1862.5
3(459)
0.172;-1656.3
(45)(3Q)
0.207;-1000.0
35(46)
0.168;-1862.5
35(48)
0.207;-1725.0
35(4T)
0.219;-1587.5
35(4Q)
0.190;-1450.0
46(36)
0.233;-1343.7
(36)(49)
0.187;-1137.5
4(36Q)
0.216;-1381.2
3(467)
0.197;-1725.0
(46)(3T)
0.169;-1068.7
3Q(46)
0.252;-1381.2
3467
0.156;-2175.0
3469
0.200;-2037.5
346J
0.177;-1900.0
346K
0.210;-1762.5
49(37)
0.155;-1518.8
(37)(4Q)
0.196;-862.5
38(47)
0.175;-1587.5
3(47J)
0.193;-1381.2
3477
0.147;-1656.3
3479
0.223;-1968.8
347J
0.199;-1831.2
347K
0.180;-1693.7
4T(38)
0.226;-1381.2
(38)(4K)
0.243;-725.0
3T(48)
0.212;-1381.2
3(48K)
0.266;-1175.0
38(4T)
0.154;-1381.2
38(4Q)
0.191;-1243.8
49(39)
0.236;-931.2
(39)(4Q)
0.259;-725.0
3T(49)
0.234;-1312.5
3(49K)
0.172;-1106.2
39(4J)
0.217;-1243.8
39(4K)
0.221;-1106.2
4(3TQ)
0.212;-1106.2
3(4TJ)
0.197;-1175.0
34TT
0.197;-1243.8
34TQ
0.186;-1556.2
(3J)(4Q)
0.262;-587.5
3Q(4J)
0.190;-1037.5
34JQ
0.169;-1487.5
(3Q)(4K)
0.291;-450.0
3Q(4K)
0.262;-900.0
5(356)
0.217;-1343.7
58(35)
0.254;-1206.2
(35)(5J)
0.194;-550.0
6(356)
0.186;-1275.0
T(356)
0.227;-1450.0
6(357)
0.182;-1656.3
69(35)
0.190;-1518.8
(35)(6Q)
0.166;-862.5
(3579)
0.208;-1450.0
(357K)
0.195;-1175.0
79(35)
0.170;-1450.0
(35)(7Q)
0.173;-793.8
(358T)
0.180;-1312.5
88(35)
0.222;-1000.0
(35)(8J)
0.221;-793.8
9(359)
0.229;-862.5
K(359)
0.168;-1037.5
9(35Q)
0.162;-1106.2
J(35T)
0.205;-1106.2
TJ(35)
0.208;-1106.2
(35JQ)
0.241;-968.7
J(35K)
0.180;-900.0
(35)(QK)
0.266;-381.2
55(37)
0.194;-1275.0
3559
0.240;-1587.5
35(5Q)
0.183;-931.2
(36)(57)
0.160;-1206.2
5(36T)
0.230;-1450.0
5Q(36)
0.203;-1312.5
(56)(38)
0.264;-1137.5
3T(56)
0.243;-1450.0
3(56K)
0.203;-1243.8
36(58)
0.185;-1587.5
36(5T)
0.166;-1450.0
36(5Q)
0.215;-1312.5
57(37)
0.231;-1137.5
(37)(5T)
0.188;-931.2
5(37K)
0.254;-1175.0
3(579)
0.198;-1450.0
(57)(3Q)
0.245;-793.8
37(58)
0.205;-1518.8
37(5T)
0.162;-1381.2
37(5Q)
0.189;-1243.8
58(38)
0.228;-1000.0
(38)(5J)
0.225;-793.8
38(58)
0.158;-1000.0
3(58J)
0.172;-1243.8
3588
0.205;-1450.0
358T
0.167;-1762.5
358Q
0.190;-1625.0
(39)(5T)
0.233;-793.8
5(39K)
0.203;-1037.5
3(59J)
0.241;-1175.0
3599
0.173;-1312.5
359J
0.197;-1625.0
359K
0.173;-1487.5
5Q(3T)
0.215;-1037.5
(5T)(3Q)
0.173;-587.5
3T(5J)
0.169;-1106.2
3T(5K)
0.282;-968.7
5(3JK)
0.240;-900.0
3(5JK)
0.175;-900.0
3J(5K)
0.232;-900.0
3Q(5Q)
0.249;-450.0
35QK
0.175;-1281.2
67(36)
0.211;-1137.5
(36)(6T)
0.292;-481.2
6(36K)
0.227;-725.0
(367T)
0.225;-1312.5
77(36)
0.235;-1068.7
(36)(7T)
0.189;-862.5
7(36K)
0.201;-1106.2
(368J)
0.225;-1175.0
(36)(89)
0.236;-862.5
8(36Q)
0.224;-1106.2
T(369)
0.203;-1175.0
9(36T)
0.244;-1175.0
9Q(36)
0.179;-1037.5
Q(36T)
0.188;-968.7
(36)(TQ)
0.260;-518.7
(36JK)
0.236;-831.2
JK(36)
0.169;-831.2
K(36K)
0.289;-243.7
3668
0.200;-1518.8
36(6J)
0.210;-862.5
(37)(67)
0.248;-618.8
6(37T)
0.169;-1312.5
6Q(37)
0.185;-1175.0
(67)(39)
0.207;-931.2
3J(67)
0.198;-1243.8
67(38)
0.159;-1450.0
67(3T)
0.159;-1312.5
67(3Q)
0.197;-1175.0
(38)(68)
0.247;-481.2
6(38J)
0.163;-1175.0
6K(38)
0.207;-1037.5
(68)(3J)
0.256;-725.0
3K(68)
0.170;-1037.5
36(8T)
0.239;-1243.8
36(8Q)
0.170;-1106.2
6(39T)
0.207;-1175.0
6Q(39)
0.190;-1037.5
(69)(3J)
0.222;-656.2
3K(69)
0.208;-968.7
36(9J)
0.168;-1106.2
36(9K)
0.159;-968.7
(3T)(6Q)
0.200;-518.7
3J(6T)
0.200;-1037.5
6T(3J)
0.215;-1037.5
6T(3K)
0.200;-900.0
6Q(3J)
0.195;-900.0
(6J)(3K)
0.259;-381.2
6J(3K)
0.207;-831.2
6K(3Q)
0.196;-762.5
36(QK)
0.210;-762.5
(37)(78)
0.197;-481.2
7(37J)
0.221;-725.0
7K(37)
0.207;-587.5
(378Q)
0.217;-1037.5
8(37T)
0.175;-1175.0
8Q(37)
0.206;-1037.5
J(379)
0.182;-1037.5
9T(37)
0.231;-1106.2
(37)(9K)
0.271;-450.0
K(37T)
0.173;-831.2
T(37K)
0.204;-831.2
JJ(37)
0.252;-450.0
(37QK)
0.220;-693.7
3777
0.225;-1000.0
37(7T)
0.192;-793.7
77(3K)
0.278;-587.5
7(38T)
0.167;-1175.0
7Q(38)
0.269;-1037.5
(78)(3T)
0.208;-725.0
3Q(78)
0.153;-1037.5
3789
0.180;-1693.7
378J
0.206;-1556.2
378K
0.218;-1418.7
7J(39)
0.179;-1037.5
(79)(3T)
0.212;-656.2
3Q(79)
0.223;-968.7
379T
0.193;-1556.2
379Q
0.203;-1418.7
(3T)(7J)
0.218;-518.7
3T(7T)
0.197;-587.5
3(7TK)
0.262;-831.2
3T(7Q)
0.190;-900.0
7J(3J)
0.222;-450.0
(7J)(3Q)
0.225;-381.2
3J(7Q)
0.222;-831.2
7Q(3Q)
0.262;-312.5
37QQ
0.259;-762.5
37KK
0.246;-625.0
8(38J)
0.278;-587.5
8K(38)
0.270;-450.0
(389K)
0.256;-831.2
9J(38)
0.222;-968.7
(38TJ)
0.202;-900.0
(38)(TJ)
0.230;-450.0
J(38J)
0.260;-381.2
JQ(38)
0.210;-762.5
Q(38K)
0.232;-625.0
3889
0.216;-1175.0
38(8Q)
0.208;-518.7
(39)(8T)
0.267;-587.5
8(39K)
0.213;-831.2
3(89J)
0.178;-968.7
3899
0.195;-1106.2
389J
0.203;-1418.7
389K
0.217;-1281.2
8Q(3T)
0.204;-831.2
(8T)(3Q)
0.232;-381.2
3T(8J)
0.251;-900.0
3T(8K)
0.226;-762.5
8(3JK)
0.215;-693.7
3(8JK)
0.258;-693.7
3J(8K)
0.203;-693.7
3Q(8Q)
0.193;-243.7
38QK
0.170;-1075.0
9T(39)
0.236;-518.7
(39)(9K)
0.287;137.5
K(39T)
0.203;-693.7
T(39K)
0.260;-693.7
JJ(39)
0.270;-312.5
(39QK)
0.187;-556.2
3999
0.245;-587.5
39(9Q)
0.273;-381.2
(3T)(9J)
0.220;-381.2
3T(9T)
0.222;-450.0
3(9TK)
0.253;-693.7
3T(9Q)
0.186;-762.5
9J(3J)
0.258;-312.5
(9J)(3Q)
0.263;-243.8
3J(9Q)
0.227;-693.7
9Q(3Q)
0.204;-175.0
39QQ
0.256;-625.0
39KK
0.263;-487.5
T(3TK)
0.297;-175.0
JJ(3T)
0.296;-243.7
(3TQK)
0.246;-487.5
3TTT
0.281;-381.2
3T(TK)
0.245;-175.0
(3J)(TK)
0.210;-106.2
3K(TJ)
0.268;-556.2
3T(JK)
0.261;-556.2
(TQ)(3K)
0.248;-37.5
(3K)(TK)
0.288;481.3
J(3JK)
0.223;-37.5
(3J)(QK)
0.290;31.3
JJ(3K)
0.280;-37.5
3Q(JQ)
0.281;-37.5
3JQK
0.241;-868.7
QK(3Q)
0.224;100.0
QK(3K)
0.247;168.8
44(46)
0.213;-962.5
44(4T)
0.215;-687.5
(45)(45)
0.267;-512.5
4(458)
0.243;-1206.2
4T(45)
0.196;-1068.7
(45)(4K)
0.246;-412.5
4457
0.162;-1725.0
44(5T)
0.236;-1068.7
45(4K)
0.224;-862.5
4(468)
0.199;-1137.5
4T(46)
0.168;-1000.0
(46)(4K)
0.236;-343.7
4468
0.178;-1587.5
44(6J)
0.248;-931.2
(47)(47)
0.209;-237.5
4(47T)
0.245;-931.2
4Q(47)
0.243;-793.7
47(49)
0.204;-1000.0
447J
0.198;-1312.5
48(48)
0.217;-550.0
(48)(4J)
0.204;-343.7
4488
0.160;-1000.0
44(8J)
0.205;-793.7
(49)(49)
0.268;37.5
4(49Q)
0.282;-656.2
44(9T)
0.222;-793.7
49(4K)
0.248;-587.5
4(4TQ)
0.249;-587.5
44(TJ)
0.234;-656.2
(4J)(4J)
0.293;312.5
44JJ
0.211;-587.5
4Q(4Q)
0.330;0.0
(4K)(4K)
0.285;587.5
(45)(57)
0.272;-756.3
5(45T)
0.230;-1000.0
5Q(45)
0.235;-862.5
8(456)
0.192;-1518.8
Q(456)
0.183;-1243.8
(45)(68)
0.177;-1068.7
6(45J)
0.219;-1312.5
6K(45)
0.173;-1175.0
(457J)
0.219;-1243.8
(45)(78)
0.243;-1000.0
7(45J)
0.223;-1243.8
7K(45)
0.244;-1106.2
(458Q)
0.204;-1106.2
8(45T)
0.180;-1243.8
8Q(45)
0.152;-1106.2
J(459)
0.228;-1106.2
9T(45)
0.207;-1175.0
(45)(9K)
0.293;-518.7
K(45T)
0.262;-900.0
T(45K)
0.244;-900.0
JJ(45)
0.221;-518.7
(45QK)
0.227;-762.5
4555
0.191;-1343.8
45(58)
0.233;-1137.5
55(4J)
0.244;-931.2
455K
0.209;-1243.8
58(46)
0.176;-1518.8
(46)(5J)
0.256;-862.5
46(56)
0.237;-1206.2
4(569)
0.184;-1450.0
(56)(4Q)
0.200;-793.8
46(57)
0.219;-1587.5
46(59)
0.245;-1450.0
46(5J)
0.202;-1312.5
46(5K)
0.185;-1175.0
5(479)
0.213;-1381.2
5J(47)
0.200;-1243.8
(57)(48)
0.193;-1000.0
4T(57)
0.214;-1312.5
4(57K)
0.225;-1106.2
47(59)
0.150;-1381.2
47(5J)
0.188;-1243.8
47(5K)
0.222;-1106.2
5(48T)
0.187;-1243.8
5Q(48)
0.181;-1106.2
(58)(4T)
0.228;-793.8
4Q(58)
0.222;-1106.2
4589
0.185;-1762.5
458J
0.204;-1625.0
458K
0.195;-1487.5
5J(49)
0.176;-1106.2
(59)(4T)
0.245;-725.0
4Q(59)
0.224;-1037.5
459T
0.212;-1625.0
459Q
0.210;-1487.5
(4T)(5J)
0.202;-587.5
4T(5T)
0.191;-656.2
4(5TK)
0.214;-900.0
4T(5Q)
0.226;-968.7
5J(4J)
0.268;-518.7
(5J)(4Q)
0.212;-450.0
4J(5Q)
0.232;-900.0
5Q(4Q)
0.211;-381.2
45QQ
0.223;-831.2
45KK
0.248;-693.7
6(469)
0.172;-931.2
6J(46)
0.204;-793.7
(4678)
0.186;-1381.2
(467Q)
0.217;-1106.2
7(469)
0.191;-1312.5
7J(46)
0.217;-1175.0
(4689)
0.153;-1243.8
(468K)
0.201;-968.7
8T(46)
0.199;-1175.0
(46)(8K)
0.261;-518.7
Q(469)
0.216;-968.7
(46)(9J)
0.246;-587.5
T(46T)
0.219;-587.5
T(46J)
0.275;-968.7
TK(46)
0.205;-831.2
(46)(JQ)
0.251;-381.2
QQ(46)
0.219;-312.5
46(67)
0.199;-1068.7
66(4T)
0.242;-862.5
466Q
0.198;-1175.0
68(47)
0.233;-1381.2
(47)(6J)
0.219;-725.0
47(67)
0.227;-1000.0
4(67T)
0.189;-1243.8
(67)(4K)
0.260;-587.5
67(49)
0.202;-1312.5
67(4J)
0.189;-1175.0
67(4K)
0.197;-1037.5
69(48)
0.181;-1243.8
(48)(6Q)
0.229;-587.5
49(68)
0.217;-1243.8
4(68Q)
0.171;-1037.5
46(89)
0.150;-1243.8
46(8J)
0.196;-1106.2
46(8K)
0.219;-968.7
(49)(6J)
0.189;-587.5
49(69)
0.278;-725.0
4(69Q)
0.186;-968.7
46(9T)
0.183;-1106.2
46(9Q)
0.280;-968.7
6(4TJ)
0.203;-968.7
6K(4T)
0.214;-831.2
(6T)(4K)
0.274;-381.2
6T(4Q)
0.272;-900.0
(4J)(6J)
0.257;0.0
4J(6J)
0.224;-450.0
6J(4Q)
0.224;-831.2
(4Q)(6Q)
0.269;137.5
4K(6Q)
0.223;-693.7
4K(6K)
0.277;-175.0
79(47)
0.188;-793.7
(47)(7Q)
0.241;-137.5
(478T)
0.190;-1106.2
88(47)
0.216;-793.7
(47)(8J)
0.215;-587.5
9(479)
0.259;-656.2
K(479)
0.213;-831.2
9(47Q)
0.211;-900.0
J(47T)
0.227;-900.0
TJ(47)
0.177;-900.0
(47JQ)
0.201;-762.5
J(47K)
0.251;-693.7
(47)(QK)
0.256;-175.0
77(49)
0.218;-793.7
477J
0.211;-1106.2
78(48)
0.268;-793.7
(48)(7J)
0.248;-587.5
48(78)
0.243;-793.7
4(78J)
0.158;-1037.5
4788
0.153;-1243.8
478T
0.178;-1556.2
478Q
0.182;-1418.7
(49)(7T)
0.216;-587.5
7(49K)
0.244;-831.2
4(79J)
0.216;-968.7
4799
0.231;-1106.2
479J
0.183;-1418.7
479K
0.184;-1281.2
7Q(4T)
0.251;-831.2
(7T)(4Q)
0.253;-381.2
4T(7J)
0.211;-900.0
4T(7K)
0.231;-762.5
7(4JK)
0.204;-693.7
4(7JK)
0.189;-693.7
4J(7K)
0.279;-693.7
4Q(7Q)
0.228;-243.7
47QK
0.253;-1075.0
89(48)
0.205;-656.2
(48)(8Q)
0.257;0.0
(489J)
0.231;-900.0
(48)(9T)
0.273;-518.7
9(48K)
0.204;-762.5
(48TK)
0.187;-693.7
TQ(48)
0.208;-762.5
K(48J)
0.241;-625.0
Q(48Q)
0.252;-175.0
KK(48)
0.261;-37.5
88(4J)
0.225;-518.7
488K
0.221;-831.2
8J(49)
0.196;-900.0
(89)(4T)
0.246;-518.7
4Q(89)
0.218;-831.2
489T
0.157;-1418.7
489Q
0.177;-1281.2
(4T)(8J)
0.276;-381.2
4T(8T)
0.240;-450.0
4(8TK)
0.172;-693.7
4T(8Q)
0.185;-762.5
8J(4J)
0.233;-312.5
(8J)(4Q)
0.278;-243.8
4J(8Q)
0.219;-693.7
8Q(4Q)
0.207;-175.0
48QQ
0.224;-625.0
48KK
0.291;-487.5
9(49Q)
0.273;-312.5
J(49T)
0.190;-762.5
TJ(49)
0.237;-762.5
(49JQ)
0.251;-625.0
J(49K)
0.214;-556.2
(49)(QK)
0.285;-37.5
99(4J)
0.284;-381.2
499K
0.257;-693.7
9Q(4T)
0.207;-693.7
(9T)(4Q)
0.251;-243.8
4T(9J)
0.224;-762.5
4T(9K)
0.227;-625.0
9(4JK)
0.238;-556.2
4(9JK)
0.225;-556.2
4J(9K)
0.281;-556.2
4Q(9Q)
0.258;-106.2
49QK
0.217;-937.5
TJ(4T)
0.233;-243.7
(4TJQ)
0.227;-556.2
J(4TK)
0.241;-487.5
(4T)(QK)
0.314;31.3
TT(4Q)
0.274;-175.0
T(4JQ)
0.218;-556.2
4(TJQ)
0.265;-556.2
4T(JQ)
0.214;-556.2
T(4QK)
0.264;-418.7
TQ(4K)
0.222;-418.7
JJ(4J)
0.298;343.7
(4JQK)
0.224;-350.0
4JJJ
0.225;-106.2
JQ(4Q)
0.301;31.3
4JQQ
0.237;-418.7
4JKK
0.229;-281.2
QQ(4K)
0.273;168.8
4KKK
0.249;306.2
55(59)
0.244;-550.0
55(5K)
0.282;-275.0
(56)(58)
0.197;-550.0
5(56J)
0.210;-793.7
5K(56)
0.226;-656.2
56(59)
0.233;-931.2
556J
0.190;-1243.8
57(57)
0.267;-550.0
(57)(5T)
0.211;-343.7
5(57K)
0.244;-587.5
55(79)
0.241;-862.5
57(5Q)
0.234;-656.2
5(589)
0.228;-793.7
5J(58)
0.208;-656.2
58(59)
0.228;-793.7
558J
0.209;-1106.2
59(59)
0.252;-275.0
(59)(5Q)
0.289;-68.8
559T
0.236;-1106.2
55(9K)
0.238;-450.0
(5T)(5Q)
0.214;0.0
55TJ
0.261;-968.7
5J(5J)
0.260;0.0
5J(5Q)
0.217;-381.2
5(5QK)
0.231;-243.7
5K(5K)
0.292;275.0
68(56)
0.234;-931.2
(56)(6J)
0.229;-275.0
7(567)
0.208;-931.2
J(567)
0.195;-1106.2
78(56)
0.161;-1312.5
(56)(7J)
0.183;-656.2
8(568)
0.242;-793.7
Q(568)
0.261;-968.7
(56)(8T)
0.276;-656.2
8(56K)
0.266;-900.0
(569Q)
0.237;-900.0
9(56J)
0.186;-968.7
9K(56)
0.203;-831.2
TT(56)
0.231;-518.7
(56)(TK)
0.195;-312.5
J(56Q)
0.184;-762.5
K(56Q)
0.247;-625.0
66(57)
0.248;-1000.0
5669
0.147;-1312.5
56(6Q)
0.182;-656.2
(57)(68)
0.276;-862.5
6(57J)
0.243;-1106.2
6K(57)
0.256;-968.7
(67)(5T)
0.231;-725.0
5Q(67)
0.211;-1037.5
5678
0.225;-1762.5
567T
0.183;-1625.0
567Q
0.198;-1487.5
(58)(69)
0.232;-725.0
6(58Q)
0.249;-968.7
5(689)
0.256;-1175.0
(68)(5Q)
0.213;-518.7
58(69)
0.205;-1175.0
58(6J)
0.217;-1037.5
58(6K)
0.222;-900.0
6(59J)
0.186;-968.7
6K(59)
0.206;-831.2
(69)(5Q)
0.235;-450.0
59(6T)
0.236;-1037.5
59(6Q)
0.190;-900.0
6T(5T)
0.238;-518.7
(5T)(6K)
0.236;-312.5
5Q(6T)
0.236;-831.2
56TJ
0.177;-1350.0
56TK
0.166;-1212.5
6K(5J)
0.197;-693.7
56JJ
0.188;-831.2
56JK
0.255;-1143.8
5(6QK)
0.244;-625.0
6K(5K)
0.282;-106.2
(57)(79)
0.253;-275.0
7(57Q)
0.285;-518.7
9(578)
0.166;-1106.2
K(578)
0.233;-831.2
8(57J)
0.193;-968.7
8K(57)
0.220;-831.2
(579K)
0.178;-762.5
9J(57)
0.217;-900.0
(57TJ)
0.225;-831.2
(57)(TJ)
0.284;-381.2
J(57J)
0.294;-312.5
JQ(57)
0.276;-693.7
Q(57K)
0.269;-556.2
5778
0.169;-1243.8
57(7J)
0.220;-587.5
(58)(78)
0.225;-275.0
7(58J)
0.223;-968.7
7K(58)
0.251;-831.2
(78)(5J)
0.211;-518.7
5K(78)
0.240;-831.2
57(8T)
0.221;-1037.5
57(8Q)
0.180;-900.0
7(59T)
0.214;-968.7
7Q(59)
0.225;-831.2
(79)(5J)
0.223;-450.0
5K(79)
0.254;-762.5
57(9J)
0.179;-900.0
57(9K)
0.196;-762.5
(5T)(7Q)
0.265;-312.5
5J(7T)
0.209;-831.2
7T(5J)
0.206;-831.2
7T(5K)
0.212;-693.7
7Q(5J)
0.215;-693.7
(7J)(5K)
0.248;-175.0
7J(5K)
0.253;-625.0
7K(5Q)
0.241;-556.2
57(QK)
0.259;-556.2
(58)(89)
0.214;-137.5
8(58Q)
0.213;-381.2
T(589)
0.236;-900.0
9(58T)
0.198;-900.0
9Q(58)
0.248;-762.5
Q(58T)
0.202;-693.7
(58)(TQ)
0.238;-243.8
(58JK)
0.270;-556.2
JK(58)
0.233;-556.2
K(58K)
0.318;31.3
588T
0.236;-968.7
58(8K)
0.223;-312.5
(59)(8J)
0.224;-381.2
59(89)
0.233;-518.7
5(89Q)
0.228;-762.5
58(9T)
0.199;-900.0
58(9Q)
0.261;-762.5
8(5TJ)
0.260;-762.5
8K(5T)
0.185;-625.0
(8T)(5K)
0.259;-175.0
8T(5Q)
0.222;-693.7
(5J)(8J)
0.321;206.3
5J(8J)
0.248;-243.7
8J(5Q)
0.251;-625.0
(5Q)(8Q)
0.262;343.7
5K(8Q)
0.256;-487.5
5K(8K)
0.210;31.3
9J(59)
0.256;-312.5
(59TJ)
0.231;-693.7
(59)(TJ)
0.281;-243.8
J(59J)
0.282;-175.0
JQ(59)
0.230;-556.2
Q(59K)
0.223;-418.7
599T
0.199;-831.2
59(9K)
0.296;-175.0
(5T)(9Q)
0.271;-175.0
5J(9T)
0.241;-693.7
9T(5J)
0.297;-693.7
9T(5K)
0.211;-556.2
9Q(5J)
0.231;-556.2
(9J)(5K)
0.315;-37.5
9J(5K)
0.259;-487.5
9K(5Q)
0.252;-418.7
59(QK)
0.188;-418.7
(5T)(TJ)
0.239;275.0
J(5TJ)
0.238;-106.2
JQ(5T)
0.184;-487.5
Q(5TK)
0.186;-350.0
5TTJ
0.258;-625.0
TJ(5J)
0.228;-106.2
(TJ)(5Q)
0.296;-37.5
5J(TQ)
0.228;-487.5
TQ(5Q)
0.255;31.3
5TQQ
0.272;-418.7
5TKK
0.243;-281.2
Q(5JQ)
0.249;100.0
KK(5J)
0.239;237.5
(5Q)(JQ)
0.234;550.0
5K(JQ)
0.238;-281.2
5K(JK)
0.246;237.5
5QQQ
0.222;168.8
KK(5K)
0.290;825.0
6669
0.200;-793.8
666K
0.234;-518.7
69(67)
0.211;-725.0
(67)(6Q)
0.249;-68.8
6678
0.202;-1243.8
66(7J)
0.219;-587.5
(68)(68)
0.267;175.0
6(68J)
0.214;-518.7
6K(68)
0.239;-381.2
68(6J)
0.296;-518.7
668K
0.228;-831.2
6J(69)
0.300;-450.0
69(6T)
0.213;-518.7
669Q
0.224;-831.2
6J(6T)
0.243;-381.2
6T(6J)
0.260;-381.2
66TK
0.223;-693.7
6K(6J)
0.262;-175.0
(6Q)(6Q)
0.310;725.0
66QK
0.225;-556.2
7(679)
0.254;-656.2
7J(67)
0.233;-518.7
(6789)
0.204;-1037.5
(678K)
0.236;-762.5
8T(67)
0.237;-968.7
(67)(8K)
0.217;-312.5
Q(679)
0.204;-762.5
(67)(9J)
0.216;-381.2
T(67T)
0.213;-381.2
T(67J)
0.257;-762.5
TK(67)
0.210;-625.0
(67)(JQ)
0.273;-175.0
QQ(67)
0.259;-106.2
67(78)
0.179;-725.0
77(6J)
0.264;-518.7
677K
0.235;-831.2
7T(68)
0.235;-968.7
(68)(7K)
0.243;-312.5
6T(78)
0.179;-968.7
6(78K)
0.213;-762.5
68(7T)
0.166;-968.7
68(7Q)
0.215;-831.2
79(69)
0.279;-518.7
(69)(7Q)
0.193;-312.5
6T(79)
0.245;-900.0
6(79K)
0.193;-693.7
69(7J)
0.232;-831.2
69(7K)
0.189;-693.7
7(6TQ)
0.264;-693.7
6(7TJ)
0.262;-762.5
67TT
0.271;-831.2
67TQ
0.182;-1143.8
(6J)(7Q)
0.229;-175.0
6Q(7J)
0.177;-625.0
67JQ
0.216;-1075.0
(6Q)(7K)
0.241;-37.5
6Q(7K)
0.245;-487.5
8(689)
0.267;-518.7
8J(68)
0.221;-381.2
(689T)
0.228;-831.2
99(68)
0.214;-450.0
(68)(9Q)
0.229;-243.8
(68TQ)
0.240;-625.0
T(68Q)
0.183;-625.0
Q(68J)
0.246;-556.2
(68)(JK)
0.208;-37.5
QK(68)
0.236;-418.7
68(8T)
0.205;-450.0
88(6K)
0.297;-243.7
8(69J)
0.207;-762.5
8K(69)
0.229;-625.0
(89)(6Q)
0.211;-243.8
69(8T)
0.235;-831.2
69(8Q)
0.226;-693.7
8T(6T)
0.243;-312.5
(6T)(8K)
0.238;-106.2
6Q(8T)
0.261;-625.0
68TJ
0.234;-1143.8
68TK
0.188;-1006.3
8K(6J)
0.200;-487.5
68JJ
0.182;-625.0
68JK
0.163;-937.5
6(8QK)
0.232;-418.7
8K(6K)
0.302;100.0
(69)(9J)
0.306;206.3
T(69T)
0.225;-243.7
T(69J)
0.264;-625.0
TK(69)
0.227;-487.5
(69)(JQ)
0.273;-37.5
QQ(69)
0.323;31.3
69(9T)
0.219;-312.5
99(6K)
0.321;-106.2
9(6TQ)
0.231;-556.2
6(9TJ)
0.218;-625.0
69TT
0.238;-693.7
69TQ
0.217;-1006.3
(6J)(9Q)
0.276;-37.5
6Q(9J)
0.233;-487.5
69JQ
0.187;-937.5
(6Q)(9K)
0.309;100.0
6Q(9K)
0.216;-350.0
T(6TJ)
0.233;-106.2
TK(6T)
0.228;31.3
(6T)(JQ)
0.237;31.3
QQ(6T)
0.277;100.0
6T(TJ)
0.227;-106.2
(6J)(TJ)
0.323;412.5
6J(TJ)
0.312;-37.5
TJ(6Q)
0.237;-418.7
(6Q)(TQ)
0.298;550.0
6K(TQ)
0.269;-281.2
6K(TK)
0.238;237.5
JK(6J)
0.325;168.8
K(6JK)
0.234;306.2
6JJK
0.262;-281.2
6(JQK)
0.249;-212.5
JK(6K)
0.335;306.2
KK(6Q)
0.272;375.0
6QKK
0.280;-75.0
77(7T)
0.252;-68.7
(78)(78)
0.262;312.5
7(78J)
0.231;-381.2
7K(78)
0.266;-243.7
78(7J)
0.203;-381.2
778K
0.246;-693.7
7J(79)
0.233;-312.5
79(7T)
0.280;-381.2
779Q
0.233;-693.7
7J(7T)
0.212;-243.7
7T(7J)
0.259;-243.7
77TK
0.213;-556.2
7K(7J)
0.219;-37.5
(7Q)(7Q)
0.272;862.5
77QK
0.250;-418.7
8(78T)
0.212;-381.2
8Q(78)
0.295;-243.7
J(789)
0.265;-693.7
9T(78)
0.207;-762.5
(78)(9K)
0.259;-106.2
K(78T)
0.247;-487.5
T(78K)
0.251;-487.5
JJ(78)
0.311;-106.2
(78QK)
0.251;-350.0
7888
0.239;-518.7
78(8J)
0.203;-312.5
(79)(89)
0.274;68.8
8(79Q)
0.294;-625.0
7(89T)
0.256;-762.5
(89)(7K)
0.239;-106.2
89(7J)
0.269;-693.7
89(7K)
0.246;-556.2
8J(7T)
0.290;-625.0
(8T)(7J)
0.273;-175.0
7K(8T)
0.234;-487.5
78(TQ)
0.258;-556.2
8(7JQ)
0.260;-487.5
7(8JQ)
0.243;-487.5
78(JQ)
0.185;-487.5
8(7QK)
0.280;-350.0
8Q(7K)
0.303;-350.0
99(79)
0.265;137.5
(79)(9Q)
0.331;343.7
(79TQ)
0.252;-487.5
T(79Q)
0.264;-487.5
Q(79J)
0.264;-418.7
(79)(JK)
0.270;100.0
QK(79)
0.264;-281.2
79(9J)
0.251;-175.0
(7T)(9T)
0.299;275.0
9(7TK)
0.212;-418.7
7(9TQ)
0.218;-487.5
79(TJ)
0.232;-556.2
79(TK)
0.303;-418.7
(7J)(9K)
0.272;100.0
7K(9J)
0.239;-350.0
79(JK)
0.216;-350.0
(9Q)(7K)
0.214;168.8
(7K)(9K)
0.305;687.5
T(7TQ)
0.243;31.3
Q(7TJ)
0.269;-350.0
(7T)(JK)
0.335;168.8
QK(7T)
0.291;-212.5
7T(TQ)
0.258;31.3
(7J)(TQ)
0.294;100.0
7Q(TJ)
0.274;-350.0
7TJQ
0.200;-800.0
(7Q)(TK)
0.236;237.5
7Q(TK)
0.243;-212.5
J(7JQ)
0.244;168.8
K(7JQ)
0.305;-143.7
JJ(7Q)
0.320;168.8
J(7QK)
0.274;-143.7
JQ(7K)
0.252;-143.7
QQ(7Q)
0.363;756.2
7Q(QK)
0.232;375.0
8888
0.276;0.0
888Q
0.258;-175.0
8(89J)
0.232;-175.0
8K(89)
0.217;-37.5
89(8Q)
0.272;-106.2
8(8TJ)
0.251;-106.2
8K(8T)
0.269;31.3
8T(8K)
0.270;31.3
8(8JK)
0.257;100.0
88(JK)
0.290;100.0
8Q(8K)
0.231;168.8
(89)(9T)
0.269;275.0
9(89K)
0.293;31.3
(89TK)
0.270;-350.0
TQ(89)
0.240;-418.7
K(89J)
0.273;-281.2
Q(89Q)
0.333;168.8
KK(89)
0.238;306.2
99(8Q)
0.266;-37.5
9(8TJ)
0.280;-487.5
9K(8T)
0.276;-350.0
(9T)(8K)
0.277;100.0
9T(8Q)
0.236;-418.7
(8J)(9J)
0.331;481.3
8J(9J)
0.263;31.3
9J(8Q)
0.258;-350.0
(8Q)(9Q)
0.322;618.8
8K(9Q)
0.240;-212.5
8K(9K)
0.283;306.2
TQ(8T)
0.304;100.0
K(8TJ)
0.296;-212.5
Q(8TQ)
0.296;237.5
KK(8T)
0.302;375.0
