AAAA
0.368;590.0
5AAA
0.240;-4326.2
9AAA
0.221;-3061.2
KAAA
0.325;-1796.2
4A(2A)
0.238;-8437.5
(2A)(7A)
0.223;-5418.8
A(2TA)
0.183;-6540.0
QA(2A)
0.231;-5907.5
2A(4A)
0.202;-8437.5
26AA
0.204;-9875.0
AA(29)
0.172;-6856.2
2A(QA)
0.257;-5907.5
A(34A)
0.201;-8121.2
6A(3A)
0.212;-7488.8
(3A)(9A)
0.294;-4470.0
A(3QA)
0.200;-5591.3
AA(34)
0.169;-8121.2
3A(7A)
0.224;-7172.5
39AA
0.209;-8610.0
AA(3Q)
0.274;-5591.3
(4A)(5A)
0.200;-5418.8
A(48A)
0.192;-6540.0
TA(4A)
0.223;-5907.5
(4A)(KA)
0.261;-2888.7
46AA
0.190;-9242.5
AA(49)
0.246;-6223.7
4A(QA)
0.260;-5275.0
A(56A)
0.250;-6856.2
8A(5A)
0.223;-6223.7
(5A)(JA)
0.200;-3205.0
55AA
0.191;-7172.5
AA(58)
0.209;-6223.7
5A(JA)
0.258;-5275.0
5KAA
0.224;-6712.5
8A(6A)
0.238;-5907.5
(6A)(JA)
0.276;-2888.7
66AA
0.208;-6540.0
AA(69)
0.179;-5591.3
6A(QA)
0.211;-4642.5
A(78A)
0.187;-5591.3
TA(7A)
0.256;-4958.8
(7A)(KA)
0.290;-1940.0
79AA
0.235;-7345.0
AA(7Q)
0.303;-4326.3
(8A)(9A)
0.261;-2888.7
A(8QA)
0.254;-4010.0
AA(89)
0.217;-4958.8
8A(QA)
0.231;-4010.0
A(9TA)
0.225;-4326.3
QA(9A)
0.285;-3693.8
9A(JA)
0.293;-4010.0
9KAA
0.243;-5447.5
QA(TA)
0.237;-3377.5
TA(QA)
0.288;-3377.5
A(JQA)
0.243;-3061.3
AA(JQ)
0.296;-3061.3
(QA)(KA)
0.319;-358.8
KKAA
0.289;-2112.5
2(25A)
0.167;-11916.2
27(2A)
0.183;-11283.7
(2T)(2A)
0.206;-8265.0
2(2KA)
0.187;-9386.2
(236A)
0.110;-13353.7
(23TA)
0.162;-12088.7
33(2A)
0.167;-12232.5
(36)(2A)
0.196;-11283.7
3(29A)
0.193;-12405.0
3J(2A)
0.153;-11772.5
(245A)
0.114;-13353.7
(249A)
0.135;-12088.7
(24KA)
0.172;-10823.7
46(2A)
0.151;-13037.5
(49)(2A)
0.226;-10018.8
4(2QA)
0.158;-11140.0
6(25A)
0.142;-12721.2
T(25A)
0.185;-11456.2
5(26A)
0.154;-12721.2
58(2A)
0.170;-12088.7
(5J)(2A)
0.172;-9070.0
6(26A)
0.196;-10335.0
T(26A)
0.178;-11140.0
6(27A)
0.158;-12088.7
69(2A)
0.181;-11456.2
(6Q)(2A)
0.201;-8437.5
(279A)
0.171;-11140.0
(27KA)
0.209;-9875.0
79(2A)
0.215;-11140.0
(7Q)(2A)
0.149;-8121.2
(28TA)
0.157;-10507.5
88(2A)
0.189;-9070.0
(8J)(2A)
0.221;-8121.2
9(29A)
0.190;-8437.5
K(29A)
0.211;-9242.5
9(2QA)
0.234;-9558.8
J(2TA)
0.169;-9558.8
TJ(2A)
0.209;-9558.8
(2JQA)
0.230;-8926.2
J(2KA)
0.171;-8610.0
(QK)(2A)
0.237;-6223.7
22(4A)
0.134;-12232.5
226A
0.142;-13670.0
2A(29)
0.184;-10651.2
22(QA)
0.214;-9702.5
2(34A)
0.165;-13986.2
26(3A)
0.142;-13353.7
(29)(3A)
0.158;-10335.0
2(3QA)
0.184;-11456.2
A(234)
0.122;-13986.2
(23)(7A)
0.122;-10967.5
9A(23)
0.165;-12405.0
A(23Q)
0.168;-11456.2
2A(34)
0.104;-13986.2
2A(36)
0.129;-13353.7
2A(38)
0.132;-12721.2
2A(3T)
0.137;-12088.7
2A(3Q)
0.144;-11456.2
2(45A)
0.140;-13353.7
27(4A)
0.145;-12721.2
(2T)(4A)
0.179;-9702.5
2(4KA)
0.186;-10823.7
A(246)
0.142;-13037.5
(24)(9A)
0.167;-10018.8
JA(24)
0.185;-11456.2
24(5A)
0.141;-13353.7
24(7A)
0.151;-12721.2
24(9A)
0.132;-12088.7
24(JA)
0.173;-11456.2
24(KA)
0.159;-10823.7
26(5A)
0.177;-12721.2
(29)(5A)
0.170;-9702.5
2(5QA)
0.152;-10823.7
A(256)
0.148;-12721.2
(25)(9A)
0.197;-9702.5
JA(25)
0.160;-11140.0
25(6A)
0.123;-12721.2
25(8A)
0.129;-12088.7
25(TA)
0.169;-11456.2
25(QA)
0.171;-10823.7
(26)(6A)
0.220;-8265.0
2(69A)
0.168;-11456.2
2J(6A)
0.192;-10823.7
(26)(7A)
0.197;-10018.8
9A(26)
0.171;-11456.2
A(26Q)
0.190;-10507.5
2A(67)
0.206;-12088.7
2A(69)
0.163;-11456.2
2A(6J)
0.191;-10823.7
2A(6K)
0.205;-10191.2
(29)(7A)
0.168;-9070.0
2(7QA)
0.154;-10191.2
A(278)
0.161;-11456.2
(27)(JA)
0.202;-8437.5
KA(27)
0.176;-9875.0
2A(79)
0.184;-11140.0
2A(7J)
0.178;-10507.5
2A(7K)
0.181;-9875.0
(2T)(8A)
0.170;-8437.5
2(8KA)
0.161;-9558.8
A(28T)
0.181;-10507.5
(28)(KA)
0.162;-7488.8
28(TA)
0.187;-10507.5
28(QA)
0.190;-9875.0
(29)(9A)
0.178;-6367.5
2(9QA)
0.148;-9558.8
A(29T)
0.193;-10191.2
(29)(KA)
0.215;-7172.5
29(JA)
0.192;-9875.0
29(KA)
0.161;-9242.5
2J(TA)
0.221;-9558.8
(2T)(JA)
0.219;-7488.8
KA(2T)
0.202;-8926.2
2A(TQ)
0.182;-9242.5
2(JQA)
0.189;-8926.2
A(2JQ)
0.202;-8926.2
2A(JQ)
0.231;-8926.2
2(QKA)
0.200;-8293.8
2Q(KA)
0.178;-8293.8
33(3A)
0.150;-9846.2
(36)(3A)
0.142;-8897.5
3(39A)
0.215;-10018.7
3J(3A)
0.170;-9386.2
(345A)
0.140;-13037.5
(349A)
0.162;-11772.5
(34KA)
0.176;-10507.5
46(3A)
0.124;-12721.2
(49)(3A)
0.180;-9702.5
4(3QA)
0.180;-10823.7
6(35A)
0.148;-12405.0
T(35A)
0.149;-11140.0
5(36A)
0.159;-12405.0
58(3A)
0.172;-11772.5
(5J)(3A)
0.172;-8753.7
6(36A)
0.184;-10018.7
T(36A)
0.152;-10823.7
6(37A)
0.179;-11772.5
69(3A)
0.167;-11140.0
(6Q)(3A)
0.207;-8121.2
(379A)
0.205;-10823.7
(37KA)
0.226;-9558.8
79(3A)
0.138;-10823.7
(7Q)(3A)
0.160;-7805.0
(38TA)
0.143;-10191.2
88(3A)
0.204;-8753.7
(8J)(3A)
0.169;-7805.0
9(39A)
0.204;-8121.2
K(39A)
0.187;-8926.2
9(3QA)
0.195;-9242.5
J(3TA)
0.193;-9242.5
TJ(3A)
0.185;-9242.5
(3JQA)
0.182;-8610.0
J(3KA)
0.162;-8293.8
(QK)(3A)
0.229;-5907.5
33(5A)
0.163;-11283.7
337A
0.111;-12721.2
3A(3T)
0.199;-9702.5
33(KA)
0.202;-8753.7
3(46A)
0.137;-12721.2
38(4A)
0.167;-12088.7
(3J)(4A)
0.177;-9070.0
4A(34)
0.162;-11283.7
A(347)
0.153;-12405.0
(34)(TA)
0.167;-9386.2
QA(34)
0.192;-10823.7
345A
0.148;-15107.5
347A
0.166;-14475.0
349A
0.174;-13842.5
34JA
0.150;-13210.0
34KA
0.137;-12577.5
37(5A)
0.160;-12088.7
(3T)(5A)
0.178;-9070.0
3(5KA)
0.156;-10191.2
A(357)
0.187;-12088.7
(35)(TA)
0.171;-9070.0
QA(35)
0.231;-10507.5
356A
0.176;-14475.0
358A
0.136;-13842.5
35TA
0.155;-13210.0
35QA
0.180;-12577.5
(37)(6A)
0.189;-9702.5
3(6TA)
0.161;-10823.7
3Q(6A)
0.150;-10191.2
(36)(8A)
0.179;-9386.2
TA(36)
0.188;-10823.7
A(36K)
0.190;-9875.0
6A(38)
0.145;-11456.2
6A(3T)
0.161;-10823.7
6A(3Q)
0.179;-10191.2
37(7A)
0.189;-9386.2
(3T)(7A)
0.161;-8437.5
3(7KA)
0.219;-9558.8
A(379)
0.216;-10823.7
(37)(QA)
0.226;-7805.0
7A(38)
0.168;-11140.0
7A(3T)
0.147;-10507.5
7A(3Q)
0.221;-9875.0
38(8A)
0.200;-8753.7
(3J)(8A)
0.249;-7805.0
8A(38)
0.186;-8753.7
A(38J)
0.165;-9875.0
388A
0.143;-10823.7
38TA
0.147;-12261.2
38QA
0.134;-11628.8
(3T)(9A)
0.202;-7805.0
3(9KA)
0.166;-8926.2
A(39J)
0.210;-9558.8
399A
0.162;-10191.2
39JA
0.185;-11628.8
39KA
0.153;-10996.2
3Q(TA)
0.193;-8926.2
(3T)(QA)
0.250;-6856.2
TA(3J)
0.219;-9242.5
TA(3K)
0.156;-8610.0
3(JKA)
0.217;-8293.8
A(3JK)
0.218;-8293.8
JA(3K)
0.231;-8293.8
QA(3Q)
0.244;-6223.7
3QKA
0.163;-10047.5
45(4A)
0.160;-10651.2
(48)(4A)
0.209;-7632.5
4(4JA)
0.193;-8753.7
4K(4A)
0.162;-8121.2
(459A)
0.146;-11140.0
(45KA)
0.172;-9875.0
57(4A)
0.140;-11772.5
(5T)(4A)
0.214;-8753.7
5(4KA)
0.215;-9875.0
(469A)
0.197;-10823.7
(46KA)
0.148;-9558.8
68(4A)
0.142;-11140.0
(6J)(4A)
0.252;-8121.2
7(47A)
0.200;-9070.0
J(47A)
0.158;-9875.0
78(4A)
0.214;-10823.7
(7J)(4A)
0.214;-7805.0
8(48A)
0.232;-8437.5
Q(48A)
0.193;-9242.5
(8T)(4A)
0.167;-7805.0
8(4KA)
0.220;-8926.2
(49QA)
0.165;-8926.2
9(4JA)
0.159;-9242.5
9K(4A)
0.156;-8610.0
TT(4A)
0.222;-7172.5
(TK)(4A)
0.236;-6223.7
J(4QA)
0.199;-8293.8
K(4QA)
0.189;-7661.2
44(5A)
0.170;-10651.2
447A
0.185;-12088.7
4A(4T)
0.167;-9070.0
44(KA)
0.169;-8121.2
4(57A)
0.172;-11772.5
49(5A)
0.173;-11140.0
(4Q)(5A)
0.182;-8121.2
6A(45)
0.143;-12088.7
A(459)
0.143;-11140.0
(45)(QA)
0.205;-8121.2
5A(46)
0.114;-12088.7
5A(48)
0.160;-11456.2
5A(4T)
0.187;-10823.7
5A(4Q)
0.166;-10191.2
46(6A)
0.171;-9702.5
(49)(6A)
0.255;-8753.7
4(6QA)
0.199;-9875.0
A(467)
0.149;-11456.2
(46)(TA)
0.208;-8437.5
QA(46)
0.198;-9875.0
467A
0.139;-13526.3
469A
0.137;-12893.7
46JA
0.168;-12261.2
46KA
0.136;-11628.8
49(7A)
0.197;-10507.5
(4Q)(7A)
0.215;-7488.8
8A(47)
0.188;-10823.7
A(47J)
0.212;-9875.0
477A
0.126;-11140.0
479A
0.127;-12577.5
47JA
0.151;-11945.0
47KA
0.208;-11312.5
4T(8A)
0.161;-9875.0
(4K)(8A)
0.233;-6856.2
TA(48)
0.150;-9875.0
A(48K)
0.164;-8926.2
8A(4T)
0.192;-9875.0
8A(4Q)
0.146;-9242.5
49(9A)
0.240;-7805.0
(4Q)(9A)
0.175;-6856.2
TA(49)
0.249;-9558.8
A(49K)
0.230;-8610.0
9A(4J)
0.185;-9242.5
9A(4K)
0.218;-8610.0
4(TQA)
0.165;-8610.0
A(4TJ)
0.194;-8926.2
4TTA
0.181;-9242.5
4TQA
0.165;-10680.0
(4Q)(JA)
0.203;-6223.7
QA(4J)
0.203;-8293.8
4JQA
0.148;-10363.7
(4K)(QA)
0.222;-5591.3
QA(4K)
0.251;-7661.2
5(56A)
0.146;-9702.5
58(5A)
0.201;-9070.0
(5J)(5A)
0.224;-6051.2
6(56A)
0.203;-9386.2
T(56A)
0.169;-10191.2
6(57A)
0.153;-11140.0
69(5A)
0.179;-10507.5
(6Q)(5A)
0.248;-7488.8
(579A)
0.171;-10191.2
(57KA)
0.215;-8926.2
79(5A)
0.145;-10191.2
(7Q)(5A)
0.195;-7172.5
(58TA)
0.172;-9558.8
88(5A)
0.168;-8121.2
(8J)(5A)
0.249;-7172.5
9(59A)
0.227;-7488.8
K(59A)
0.243;-8293.8
9(5QA)
0.234;-8610.0
J(5TA)
0.213;-8610.0
TJ(5A)
0.205;-8610.0
(5JQA)
0.224;-7977.5
J(5KA)
0.212;-7661.2
(QK)(5A)
0.240;-5275.0
55(7A)
0.201;-9386.2
559A
0.133;-10823.7
5A(5Q)
0.245;-7805.0
(57)(6A)
0.155;-9070.0
5(6TA)
0.167;-10191.2
5Q(6A)
0.232;-9558.8
(56)(8A)
0.207;-8753.7
TA(56)
0.236;-10191.2
A(56K)
0.171;-9242.5
6A(58)
0.150;-10823.7
6A(5T)
0.189;-10191.2
6A(5Q)
0.186;-9558.8
57(7A)
0.252;-8753.7
(5T)(7A)
0.183;-7805.0
5(7KA)
0.173;-8926.2
A(579)
0.213;-10191.2
(57)(QA)
0.243;-7172.5
7A(58)
0.177;-10507.5
7A(5T)
0.155;-9875.0
7A(5Q)
0.234;-9242.5
58(8A)
0.176;-8121.2
(5J)(8A)
0.216;-7172.5
8A(58)
0.227;-8121.2
A(58J)
0.194;-9242.5
588A
0.176;-10191.2
58TA
0.150;-11628.8
58QA
0.205;-10996.2
(5T)(9A)
0.222;-7172.5
5(9KA)
0.185;-8293.8
A(59J)
0.207;-8926.2
599A
0.204;-9558.8
59JA
0.143;-10996.2
59KA
0.150;-10363.7
5Q(TA)
0.244;-8293.8
(5T)(QA)
0.220;-6223.7
TA(5J)
0.177;-8610.0
TA(5K)
0.226;-7977.5
5(JKA)
0.175;-7661.2
A(5JK)
0.231;-7661.2
JA(5K)
0.226;-7661.2
QA(5Q)
0.291;-5591.3
5QKA
0.218;-9415.0
67(6A)
0.190;-8753.7
(6T)(6A)
0.250;-5735.0
6(6KA)
0.192;-6856.2
(67TA)
0.190;-9558.8
77(6A)
0.184;-8437.5
(7T)(6A)
0.222;-7488.8
7(6KA)
0.209;-8610.0
(68JA)
0.213;-8926.2
(89)(6A)
0.251;-7488.8
8(6QA)
0.170;-8610.0
T(69A)
0.217;-8926.2
9(6TA)
0.209;-8926.2
9Q(6A)
0.165;-8293.8
Q(6TA)
0.159;-7977.5
(TQ)(6A)
0.255;-5907.5
(6JKA)
0.212;-7345.0
JK(6A)
0.251;-7345.0
K(6KA)
0.237;-4642.5
668A
0.165;-10507.5
6A(6J)
0.202;-7488.8
(67)(7A)
0.164;-6367.5
6(7TA)
0.182;-9558.8
6Q(7A)
0.173;-8926.2
(67)(9A)
0.234;-7805.0
JA(67)
0.191;-9242.5
67(8A)
0.188;-10191.2
67(TA)
0.172;-9558.8
67(QA)
0.196;-8926.2
(68)(8A)
0.229;-5735.0
6(8JA)
0.193;-8926.2
6K(8A)
0.208;-8293.8
(68)(JA)
0.216;-6856.2
KA(68)
0.174;-8293.8
6A(8T)
0.197;-9242.5
6A(8Q)
0.202;-8610.0
6(9TA)
0.181;-8926.2
6Q(9A)
0.176;-8293.8
(69)(JA)
0.216;-6540.0
KA(69)
0.240;-7977.5
6A(9J)
0.231;-8610.0
6A(9K)
0.224;-7977.5
(6Q)(TA)
0.231;-5907.5
JA(6T)
0.215;-8293.8
6T(JA)
0.187;-8293.8
6T(KA)
0.179;-7661.2
6Q(JA)
0.201;-7661.2
(6J)(KA)
0.287;-5275.0
6J(KA)
0.230;-7345.0
6K(QA)
0.226;-7028.7
6A(QK)
0.230;-7028.7
(78)(7A)
0.239;-5735.0
7(7JA)
0.209;-6856.2
7K(7A)
0.244;-6223.7
(78QA)
0.183;-8293.8
8(7TA)
0.153;-8926.2
8Q(7A)
0.179;-8293.8
J(79A)
0.220;-8293.8
9T(7A)
0.172;-8610.0
(9K)(7A)
0.217;-5591.3
K(7TA)
0.274;-7345.0
T(7KA)
0.193;-7345.0
JJ(7A)
0.211;-5591.3
(7QKA)
0.207;-6712.5
777A
0.183;-8121.2
7A(7T)
0.240;-7172.5
77(KA)
0.237;-6223.7
7(8TA)
0.210;-8926.2
7Q(8A)
0.212;-8293.8
(78)(TA)
0.219;-6856.2
QA(78)
0.178;-8293.8
789A
0.161;-11312.5
78JA
0.169;-10680.0
78KA
0.224;-10047.5
7J(9A)
0.186;-8293.8
(79)(TA)
0.172;-6540.0
QA(79)
0.176;-7977.5
79TA
0.189;-10680.0
79QA
0.240;-10047.5
(7J)(TA)
0.181;-5907.5
TA(7T)
0.260;-6223.7
A(7TK)
0.202;-7345.0
TA(7Q)
0.181;-7661.2
7J(JA)
0.285;-5591.3
(7J)(QA)
0.254;-5275.0
JA(7Q)
0.191;-7345.0
7Q(QA)
0.244;-4958.8
7QQA
0.205;-7028.7
7KKA
0.214;-6396.2
8(8JA)
0.269;-6223.7
8K(8A)
0.283;-5591.3
(89KA)
0.204;-7345.0
9J(8A)
0.155;-7977.5
(8TJA)
0.163;-7661.2
(TJ)(8A)
0.294;-5591.3
J(8JA)
0.224;-5275.0
JQ(8A)
0.191;-7028.7
Q(8KA)
0.264;-6396.2
889A
0.175;-8926.2
8A(8Q)
0.270;-5907.5
(8T)(9A)
0.270;-6223.7
8(9KA)
0.234;-7345.0
A(89J)
0.209;-7977.5
899A
0.205;-8610.0
89JA
0.143;-10047.5
89KA
0.174;-9415.0
8Q(TA)
0.184;-7345.0
(8T)(QA)
0.208;-5275.0
TA(8J)
0.230;-7661.2
TA(8K)
0.220;-7028.7
8(JKA)
0.261;-6712.5
A(8JK)
0.191;-6712.5
JA(8K)
0.267;-6712.5
QA(8Q)
0.259;-4642.5
8QKA
0.181;-8466.2
9T(9A)
0.212;-5907.5
(9K)(9A)
0.268;-2888.7
K(9TA)
0.234;-6712.5
T(9KA)
0.186;-6712.5
JJ(9A)
0.201;-4958.8
(9QKA)
0.212;-6080.0
999A
0.236;-6223.7
9A(9Q)
0.239;-5275.0
(9J)(TA)
0.258;-5275.0
TA(9T)
0.179;-5591.3
A(9TK)
0.178;-6712.5
TA(9Q)
0.260;-7028.7
9J(JA)
0.265;-4958.8
(9J)(QA)
0.242;-4642.5
JA(9Q)
0.260;-6712.5
9Q(QA)
0.256;-4326.3
9QQA
0.229;-6396.2
9KKA
0.228;-5763.8
T(TKA)
0.229;-4326.3
JJ(TA)
0.239;-4642.5
(TQKA)
0.249;-5763.8
TTTA
0.222;-5275.0
TA(TK)
0.252;-4326.3
(TK)(JA)
0.268;-4010.0
KA(TJ)
0.235;-6080.0
TA(JK)
0.264;-6080.0
(TQ)(KA)
0.257;-3693.8
(TK)(KA)
0.286;-1307.5
J(JKA)
0.222;-3693.8
(QK)(JA)
0.313;-3377.5
JJ(KA)
0.222;-3693.8
QA(JQ)
0.202;-3693.8
JQKA
0.219;-7517.5
QK(QA)
0.222;-3061.3
QK(KA)
0.282;-2745.0
22(24)
0.121;-13957.5
22(28)
0.199;-12692.5
22(2Q)
0.158;-11427.5
24(23)
0.117;-15711.2
(23)(27)
0.155;-12692.5
2(23T)
0.121;-13813.8
2Q(23)
0.148;-13181.2
23(25)
0.116;-15395.0
2237
0.103;-16832.5
22(3T)
0.165;-13813.8
23(2K)
0.128;-12865.0
2(246)
0.173;-14762.5
28(24)
0.108;-14130.0
(24)(2J)
0.197;-11111.2
2244
0.102;-15395.0
22(47)
0.112;-14446.2
24(2T)
0.149;-13497.5
224Q
0.119;-14935.0
26(25)
0.135;-14446.2
(25)(29)
0.209;-11427.5
2(25Q)
0.148;-12548.8
22(56)
0.158;-14446.2
25(29)
0.143;-13497.5
225J
0.102;-14935.0
26(26)
0.176;-12060.0
(26)(29)
0.121;-11111.2
2(26Q)
0.141;-12232.5
22(67)
0.145;-13813.8
26(2T)
0.131;-12865.0
226Q
0.167;-14302.5
28(27)
0.123;-13181.2
(27)(2J)
0.173;-10162.5
2277
0.145;-13497.5
22(7T)
0.146;-12548.8
27(2K)
0.173;-11600.0
2(28T)
0.158;-12232.5
2Q(28)
0.192;-11600.0
28(2T)
0.169;-12232.5
228Q
0.130;-13670.0
2T(29)
0.126;-11916.2
(29)(2K)
0.226;-8897.5
229J
0.142;-13670.0
2T(2T)
0.158;-9530.0
(2T)(2K)
0.226;-8581.2
22TQ
0.192;-13037.5
2Q(2J)
0.160;-10651.2
2J(2K)
0.131;-10335.0
22QQ
0.169;-10335.0
3(234)
0.112;-15395.0
36(23)
0.134;-14762.5
(23)(39)
0.156;-11743.7
3(23Q)
0.189;-12865.0
5(234)
0.092;-16832.5
9(234)
0.122;-15567.5
K(234)
0.160;-14302.5
4(237)
0.140;-16200.0
49(23)
0.139;-15567.5
(23)(4Q)
0.144;-12548.8
(2357)
0.111;-15883.8
(235J)
0.125;-14618.8
(23)(56)
0.120;-14130.0
5(239)
0.158;-15251.2
5J(23)
0.135;-14618.8
(2367)
0.115;-15567.5
(236J)
0.108;-14302.5
(23)(67)
0.143;-13497.5
6(23T)
0.116;-14618.8
6Q(23)
0.137;-13986.2
9(237)
0.158;-14618.8
K(237)
0.172;-13353.7
7(23T)
0.164;-14302.5
7Q(23)
0.184;-13670.0
T(238)
0.145;-13986.2
8(239)
0.125;-14302.5
8J(23)
0.150;-13670.0
(239T)
0.167;-13670.0
99(23)
0.173;-11916.2
(23)(9Q)
0.145;-10967.5
(23TQ)
0.155;-12721.2
T(23Q)
0.149;-12721.2
Q(23J)
0.155;-12405.0
(23)(JK)
0.182;-10018.8
QK(23)
0.146;-11772.5
23(35)
0.129;-15078.8
33(28)
0.144;-14130.0
233T
0.110;-15567.5
23(3K)
0.136;-12548.8
(24)(36)
0.148;-14446.2
3(249)
0.140;-15567.5
3J(24)
0.159;-14935.0
(34)(25)
0.110;-14762.5
27(34)
0.114;-16200.0
2(34T)
0.099;-15251.2
(34)(2K)
0.138;-12232.5
34(26)
0.113;-16516.2
34(28)
0.140;-15883.8
34(2T)
0.116;-15251.2
34(2Q)
0.117;-14618.8
(25)(35)
0.127;-12376.2
3(258)
0.106;-15567.5
3T(25)
0.148;-14935.0
(25)(3K)
0.185;-11916.2
27(35)
0.137;-15883.8
2(35T)
0.157;-14935.0
(35)(2K)
0.159;-11916.2
35(27)
0.143;-15883.8
35(29)
0.107;-15251.2
35(2J)
0.125;-14618.8
35(2K)
0.147;-13986.2
37(26)
0.131;-15567.5
(26)(3T)
0.176;-12548.8
3(26K)
0.135;-13670.0
2(368)
0.125;-15251.2
(36)(2J)
0.141;-12232.5
2K(36)
0.187;-13670.0
23(68)
0.150;-15251.2
23(6T)
0.137;-14618.8
23(6Q)
0.160;-13986.2
3(278)
0.142;-14935.0
3T(27)
0.141;-14302.5
(27)(3K)
0.184;-11283.7
29(37)
0.101;-14618.8
2(37Q)
0.145;-13670.0
23(78)
0.145;-14935.0
23(7T)
0.164;-14302.5
23(7Q)
0.129;-13670.0
3(289)
0.159;-14302.5
3J(28)
0.179;-13670.0
(38)(29)
0.143;-12232.5
2J(38)
0.143;-13670.0
38(29)
0.152;-14302.5
38(2J)
0.142;-13670.0
38(2K)
0.169;-13037.5
3T(29)
0.180;-13670.0
(29)(3K)
0.180;-10651.3
2J(39)
0.192;-13353.7
39(2T)
0.169;-13670.0
39(2Q)
0.162;-13037.5
(2T)(3T)
0.209;-9213.8
3(2TK)
0.137;-12405.0
2(3TQ)
0.171;-12721.2
23(TJ)
0.145;-13037.5
23(TK)
0.144;-12405.0
(2J)(3K)
0.211;-10018.8
2K(3J)
0.163;-12088.7
23(JK)
0.163;-12088.7
(3Q)(2K)
0.146;-9702.5
(2K)(3K)
0.250;-7316.2
4(246)
0.158;-14130.0
48(24)
0.132;-13497.5
(24)(4J)
0.159;-10478.8
5(245)
0.165;-14130.0
9(245)
0.164;-14935.0
K(245)
0.190;-13670.0
5(248)
0.110;-15251.2
5T(24)
0.147;-14618.8
(24)(5K)
0.131;-11600.0
9(246)
0.131;-14618.8
K(246)
0.159;-13353.7
6(249)
0.146;-14618.8
6J(24)
0.114;-13986.2
(2478)
0.114;-14618.8
(247Q)
0.136;-13353.7
7(249)
0.150;-14302.5
7J(24)
0.139;-13670.0
(2489)
0.175;-13986.2
(248K)
0.171;-12721.2
8T(24)
0.150;-13670.0
(24)(8K)
0.174;-10651.3
Q(249)
0.144;-12721.2
(24)(9J)
0.129;-10967.5
T(24T)
0.173;-10967.5
T(24J)
0.184;-12721.2
TK(24)
0.131;-12088.7
(24)(JQ)
0.194;-10018.8
QQ(24)
0.180;-9702.5
24(45)
0.108;-14446.2
44(28)
0.178;-13497.5
244T
0.136;-14935.0
24(4K)
0.145;-11916.2
(25)(47)
0.139;-13497.5
4(25T)
0.128;-14618.8
4Q(25)
0.120;-13986.2
(45)(27)
0.129;-13497.5
29(45)
0.145;-14935.0
2(45Q)
0.169;-13986.2
24(56)
0.133;-15883.8
24(58)
0.145;-15251.2
24(5T)
0.143;-14618.8
24(5Q)
0.144;-13986.2
4(267)
0.095;-15251.2
49(26)
0.154;-14618.8
(26)(4Q)
0.158;-11600.0
27(46)
0.120;-15251.2
2(46T)
0.148;-14302.5
(46)(2K)
0.174;-11283.7
46(28)
0.110;-14935.0
46(2T)
0.129;-14302.5
46(2Q)
0.137;-13670.0
(27)(47)
0.142;-10795.0
4(27T)
0.120;-13986.2
4Q(27)
0.133;-13353.7
(47)(29)
0.172;-12232.5
2J(47)
0.174;-13670.0
47(28)
0.125;-14618.8
47(2T)
0.141;-13986.2
47(2Q)
0.157;-13353.7
(28)(48)
0.157;-10162.5
4(28J)
0.147;-13353.7
4K(28)
0.162;-12721.2
(48)(2J)
0.170;-11283.7
2K(48)
0.170;-12721.2
24(8T)
0.134;-13670.0
24(8Q)
0.171;-13037.5
4(29T)
0.126;-13353.7
4Q(29)
0.140;-12721.2
(49)(2J)
0.195;-10967.5
2K(49)
0.148;-12405.0
24(9J)
0.144;-13037.5
24(9K)
0.160;-12405.0
(2T)(4Q)
0.171;-10335.0
2J(4T)
0.140;-12721.2
4T(2J)
0.137;-12721.2
4T(2K)
0.182;-12088.7
4Q(2J)
0.166;-12088.7
(4J)(2K)
0.232;-9702.5
4J(2K)
0.183;-11772.5
4K(2Q)
0.203;-11456.2
24(QK)
0.140;-11456.2
(25)(56)
0.156;-11427.5
5(259)
0.142;-12548.8
5J(25)
0.166;-11916.2
(2567)
0.119;-14935.0
(256J)
0.141;-13670.0
(25)(67)
0.143;-12865.0
6(25T)
0.131;-13986.2
6Q(25)
0.149;-13353.7
9(257)
0.146;-13986.2
K(257)
0.153;-12721.2
7(25T)
0.113;-13670.0
7Q(25)
0.147;-13037.5
T(258)
0.137;-13353.7
8(259)
0.145;-13670.0
8J(25)
0.162;-13037.5
(259T)
0.196;-13037.5
99(25)
0.134;-11283.7
(25)(9Q)
0.171;-10335.0
(25TQ)
0.181;-12088.7
T(25Q)
0.148;-12088.7
Q(25J)
0.165;-11772.5
(25)(JK)
0.172;-9386.2
QK(25)
0.153;-11140.0
25(57)
0.117;-13181.2
55(2T)
0.169;-12232.5
255Q
0.183;-13670.0
57(26)
0.137;-14935.0
(26)(5T)
0.161;-11916.2
5(26K)
0.142;-13037.5
2(568)
0.136;-14618.8
(56)(2J)
0.158;-11600.0
2K(56)
0.193;-13037.5
25(68)
0.121;-14618.8
25(6T)
0.135;-13986.2
25(6Q)
0.142;-13353.7
5(278)
0.131;-14302.5
5T(27)
0.147;-13670.0
(27)(5K)
0.234;-10651.3
29(57)
0.153;-13986.2
2(57Q)
0.149;-13037.5
25(78)
0.146;-14302.5
25(7T)
0.172;-13670.0
25(7Q)
0.152;-13037.5
5(289)
0.149;-13670.0
5J(28)
0.127;-13037.5
(58)(29)
0.144;-11600.0
2J(58)
0.131;-13037.5
58(29)
0.116;-13670.0
58(2J)
0.174;-13037.5
58(2K)
0.146;-12405.0
5T(29)
0.201;-13037.5
(29)(5K)
0.203;-10018.8
2J(59)
0.190;-12721.2
59(2T)
0.174;-13037.5
59(2Q)
0.120;-12405.0
(2T)(5T)
0.158;-8581.2
5(2TK)
0.153;-11772.5
2(5TQ)
0.143;-12088.7
25(TJ)
0.148;-12405.0
25(TK)
0.186;-11772.5
(2J)(5K)
0.193;-9386.2
2K(5J)
0.161;-11456.2
25(JK)
0.161;-11456.2
(5Q)(2K)
0.172;-9070.0
(2K)(5K)
0.225;-6683.8
6(268)
0.141;-12232.5
6T(26)
0.148;-11600.0
(26)(6K)
0.216;-8581.2
T(267)
0.111;-13353.7
7(268)
0.141;-13986.2
7T(26)
0.135;-13353.7
(26)(7K)
0.181;-10335.0
J(268)
0.153;-12721.2
89(26)
0.178;-13353.7
(26)(8Q)
0.213;-10335.0
(269J)
0.164;-12405.0
(26)(9T)
0.212;-10651.3
9(26K)
0.216;-11772.5
(26TK)
0.131;-11456.2
TQ(26)
0.157;-11772.5
K(26J)
0.189;-11140.0
Q(26Q)
0.200;-9070.0
KK(26)
0.211;-8437.5
66(29)
0.158;-11916.2
266J
0.166;-13353.7
67(27)
0.141;-12232.5
(27)(6T)
0.215;-11283.7
6(27K)
0.131;-12405.0
2(679)
0.147;-13670.0
(67)(2Q)
0.167;-10651.3
27(68)
0.158;-13986.2
27(6T)
0.134;-13353.7
27(6Q)
0.164;-12721.2
68(28)
0.169;-11600.0
(28)(6J)
0.176;-10651.3
28(68)
0.157;-11600.0
2(68J)
0.144;-12721.2
2688
0.178;-13670.0
268T
0.128;-15107.5
268Q
0.165;-14475.0
(29)(6T)
0.170;-10651.3
6(29K)
0.151;-11772.5
2(69J)
0.166;-12405.0
2699
0.132;-13037.5
269J
0.114;-14475.0
269K
0.131;-13842.5
6Q(2T)
0.144;-11772.5
(6T)(2Q)
0.172;-9702.5
2T(6J)
0.163;-12088.7
2T(6K)
0.145;-11456.2
6(2JK)
0.148;-11140.0
2(6JK)
0.132;-11140.0
2J(6K)
0.223;-11140.0
2Q(6Q)
0.191;-9070.0
26QK
0.123;-12893.7
78(27)
0.137;-11600.0
(27)(7J)
0.191;-8581.2
8(278)
0.128;-11283.7
Q(278)
0.140;-12088.7
(27)(8T)
0.152;-10651.3
8(27K)
0.132;-11772.5
(279Q)
0.141;-11772.5
9(27J)
0.162;-12088.7
9K(27)
0.141;-11456.2
TT(27)
0.173;-10018.7
(27)(TK)
0.197;-9070.0
J(27Q)
0.147;-11140.0
K(27Q)
0.205;-10507.5
77(28)
0.162;-11600.0
277T
0.163;-13037.5
27(7K)
0.159;-10018.7
(28)(7T)
0.182;-10651.3
7(28K)
0.160;-11772.5
2(78T)
0.173;-12721.2
(78)(2K)
0.170;-9702.5
78(2T)
0.181;-12721.2
78(2Q)
0.186;-12088.7
(29)(79)
0.171;-8581.2
7(29Q)
0.164;-11772.5
2(79T)
0.158;-12405.0
(79)(2K)
0.194;-9386.2
79(2J)
0.115;-12088.7
79(2K)
0.165;-11456.2
7J(2T)
0.128;-11772.5
(7T)(2J)
0.206;-9702.5
2K(7T)
0.210;-11140.0
27(TQ)
0.134;-11456.2
7(2JQ)
0.165;-11140.0
2(7JQ)
0.186;-11140.0
27(JQ)
0.156;-11140.0
7(2QK)
0.173;-10507.5
7Q(2K)
0.171;-10507.5
88(28)
0.176;-8897.5
(28)(8J)
0.254;-7948.7
9(289)
0.179;-10335.0
K(289)
0.147;-11140.0
9(28Q)
0.170;-11456.2
J(28T)
0.165;-11456.2
TJ(28)
0.165;-11456.2
(28JQ)
0.178;-10823.7
J(28K)
0.206;-10507.5
(28)(QK)
0.226;-8121.2
88(2T)
0.173;-10335.0
288Q
0.161;-11772.5
8T(29)
0.143;-12088.7
(29)(8K)
0.215;-9070.0
2J(89)
0.182;-11772.5
89(2T)
0.152;-12088.7
89(2Q)
0.139;-11456.2
(2T)(8T)
0.209;-7632.5
8(2TK)
0.183;-10823.7
2(8TQ)
0.200;-11140.0
28(TJ)
0.192;-11456.2
28(TK)
0.157;-10823.7
(2J)(8K)
0.197;-8437.5
2K(8J)
0.177;-10507.5
28(JK)
0.194;-10507.5
(8Q)(2K)
0.232;-8121.2
(2K)(8K)
0.266;-5735.0
9(29J)
0.189;-9386.2
9K(29)
0.173;-8753.7
TT(29)
0.189;-9386.2
(29)(TK)
0.179;-8437.5
J(29Q)
0.175;-10507.5
K(29Q)
0.181;-9875.0
99(2T)
0.207;-9702.5
299Q
0.180;-11140.0
9J(2T)
0.155;-11140.0
(9T)(2J)
0.173;-9070.0
2K(9T)
0.160;-10507.5
29(TQ)
0.202;-10823.7
9(2JQ)
0.214;-10507.5
2(9JQ)
0.187;-10507.5
29(JQ)
0.174;-10507.5
9(2QK)
0.182;-9875.0
9Q(2K)
0.136;-9875.0
TT(2T)
0.249;-7000.0
(2T)(TK)
0.247;-6051.2
J(2TQ)
0.159;-10191.2
K(2TQ)
0.216;-9558.8
TT(2J)
0.159;-8753.7
2TTK
0.157;-10191.2
TK(2J)
0.164;-9875.0
2TJJ
0.157;-10507.5
2TJK
0.189;-11945.0
2(TQK)
0.199;-9558.8
TK(2K)
0.225;-7172.5
(2J)(JK)
0.298;-5418.8
QK(2J)
0.177;-9242.5
2J(JK)
0.192;-7488.8
(JQ)(2K)
0.203;-7172.5
(2K)(JK)
0.276;-4786.2
K(2QK)
0.179;-6540.0
2K(QK)
0.217;-6540.0
3335
0.139;-14762.5
3339
0.128;-13497.5
333K
0.134;-12232.5
36(34)
0.141;-14130.0
(34)(39)
0.215;-11111.2
3(34Q)
0.178;-12232.5
33(45)
0.119;-14446.2
34(38)
0.137;-13497.5
334T
0.118;-14935.0
33(4K)
0.128;-11916.2
(35)(37)
0.154;-11427.5
3(35T)
0.155;-12548.8
3Q(35)
0.201;-11916.2
35(37)
0.175;-13497.5
3359
0.119;-14935.0
33(5Q)
0.185;-11916.2
(36)(37)
0.225;-11111.2
3(36T)
0.174;-12232.5
3Q(36)
0.182;-11600.0
36(38)
0.147;-12865.0
336T
0.127;-14302.5
33(6K)
0.140;-11283.7
(37)(39)
0.144;-10162.5
3(37Q)
0.178;-11283.7
33(78)
0.163;-12548.8
37(3J)
0.170;-11600.0
337K
0.160;-13037.5
3T(38)
0.134;-11600.0
(38)(3K)
0.203;-8581.2
338T
0.189;-13670.0
33(8K)
0.166;-10651.2
(39)(3J)
0.181;-8897.5
3399
0.153;-11600.0
33(9Q)
0.164;-10651.2
(3T)(3J)
0.218;-8581.2
33TT
0.149;-10967.5
33(TK)
0.178;-10018.7
(3J)(3K)
0.168;-7632.5
33JK
0.175;-11772.5
33(QK)
0.164;-9386.2
45(34)
0.169;-14130.0
(34)(48)
0.197;-11111.2
4(34J)
0.169;-12232.5
4K(34)
0.191;-11600.0
(3459)
0.147;-14618.8
(345K)
0.135;-13353.7
57(34)
0.142;-15251.2
(34)(5T)
0.164;-12232.5
5(34K)
0.117;-13353.7
(3469)
0.156;-14302.5
(346K)
0.190;-13037.5
68(34)
0.142;-14618.8
(34)(6J)
0.143;-11600.0
7(347)
0.179;-12548.8
J(347)
0.139;-13353.7
78(34)
0.143;-14302.5
(34)(7J)
0.184;-11283.7
8(348)
0.151;-11916.2
Q(348)
0.162;-12721.2
(34)(8T)
0.158;-11283.7
8(34K)
0.155;-12405.0
(349Q)
0.153;-12405.0
9(34J)
0.194;-12721.2
9K(34)
0.175;-12088.7
TT(34)
0.173;-10651.2
(34)(TK)
0.154;-9702.5
J(34Q)
0.178;-11772.5
K(34Q)
0.165;-11140.0
44(35)
0.147;-14130.0
3447
0.120;-15567.5
34(4T)
0.149;-12548.8
44(3K)
0.135;-11600.0
4(357)
0.111;-15251.2
49(35)
0.141;-14618.8
(35)(4Q)
0.168;-11600.0
36(45)
0.125;-15567.5
3(459)
0.137;-14618.8
(45)(3Q)
0.149;-11600.0
35(46)
0.126;-15567.5
35(48)
0.160;-14935.0
35(4T)
0.154;-14302.5
35(4Q)
0.147;-13670.0
46(36)
0.133;-13181.2
(36)(49)
0.157;-12232.5
4(36Q)
0.132;-13353.7
3(467)
0.162;-14935.0
(46)(3T)
0.170;-11916.2
3Q(46)
0.130;-13353.7
3467
0.119;-17005.0
3469
0.135;-16372.5
346J
0.117;-15740.0
346K
0.149;-15107.5
49(37)
0.159;-13986.2
(37)(4Q)
0.150;-10967.5
38(47)
0.110;-14302.5
3(47J)
0.151;-13353.7
3477
0.111;-14618.8
3479
0.135;-16056.2
347J
0.125;-15423.8
347K
0.122;-14791.2
4T(38)
0.129;-13353.7
(38)(4K)
0.194;-10335.0
3T(48)
0.147;-13353.7
3(48K)
0.125;-12405.0
38(4T)
0.177;-13353.7
38(4Q)
0.137;-12721.2
49(39)
0.211;-11283.7
(39)(4Q)
0.187;-10335.0
3T(49)
0.151;-13037.5
3(49K)
0.196;-12088.7
39(4J)
0.159;-12721.2
39(4K)
0.190;-12088.7
4(3TQ)
0.190;-12088.7
3(4TJ)
0.184;-12405.0
34TT
0.155;-12721.2
34TQ
0.119;-14158.7
(3J)(4Q)
0.157;-9702.5
3Q(4J)
0.117;-11772.5
34JQ
0.192;-13842.5
(3Q)(4K)
0.161;-9070.0
3Q(4K)
0.203;-11140.0
5(356)
0.126;-13181.2
58(35)
0.129;-12548.8
(35)(5J)
0.190;-9530.0
6(356)
0.134;-12865.0
T(356)
0.147;-13670.0
6(357)
0.162;-14618.8
69(35)
0.135;-13986.2
(35)(6Q)
0.173;-10967.5
(3579)
0.179;-13670.0
(357K)
0.149;-12405.0
79(35)
0.122;-13670.0
(35)(7Q)
0.205;-10651.3
(358T)
0.123;-13037.5
88(35)
0.181;-11600.0
(35)(8J)
0.174;-10651.3
9(359)
0.187;-10967.5
K(359)
0.171;-11772.5
9(35Q)
0.167;-12088.7
J(35T)
0.148;-12088.7
TJ(35)
0.156;-12088.7
(35JQ)
0.165;-11456.2
J(35K)
0.157;-11140.0
(35)(QK)
0.181;-8753.7
55(37)
0.117;-12865.0
3559
0.158;-14302.5
35(5Q)
0.168;-11283.7
(36)(57)
0.169;-12548.8
5(36T)
0.142;-13670.0
5Q(36)
0.113;-13037.5
(56)(38)
0.161;-12232.5
3T(56)
0.132;-13670.0
3(56K)
0.157;-12721.2
36(58)
0.184;-14302.5
36(5T)
0.124;-13670.0
36(5Q)
0.156;-13037.5
57(37)
0.146;-12232.5
(37)(5T)
0.166;-11283.7
5(37K)
0.140;-12405.0
3(579)
0.128;-13670.0
(57)(3Q)
0.177;-10651.3
37(58)
0.174;-13986.2
37(5T)
0.139;-13353.7
37(5Q)
0.123;-12721.2
58(38)
0.179;-11600.0
(38)(5J)
0.133;-10651.3
38(58)
0.174;-11600.0
3(58J)
0.184;-12721.2
3588
0.182;-13670.0
358T
0.118;-15107.5
358Q
0.156;-14475.0
(39)(5T)
0.218;-10651.3
5(39K)
0.144;-11772.5
3(59J)
0.167;-12405.0
3599
0.149;-13037.5
359J
0.124;-14475.0
359K
0.162;-13842.5
5Q(3T)
0.151;-11772.5
(5T)(3Q)
0.240;-9702.5
3T(5J)
0.149;-12088.7
3T(5K)
0.152;-11456.2
5(3JK)
0.176;-11140.0
3(5JK)
0.215;-11140.0
3J(5K)
0.153;-11140.0
3Q(5Q)
0.185;-9070.0
35QK
0.145;-12893.7
67(36)
0.182;-12232.5
(36)(6T)
0.238;-9213.8
6(36K)
0.235;-10335.0
(367T)
0.182;-13037.5
77(36)
0.200;-11916.2
(36)(7T)
0.158;-10967.5
7(36K)
0.208;-12088.7
(368J)
0.207;-12405.0
(36)(89)
0.149;-10967.5
8(36Q)
0.132;-12088.7
T(369)
0.160;-12405.0
9(36T)
0.152;-12405.0
9Q(36)
0.188;-11772.5
Q(36T)
0.129;-11456.2
(36)(TQ)
0.177;-9386.2
(36JK)
0.147;-10823.7
JK(36)
0.181;-10823.7
K(36K)
0.190;-8121.2
3668
0.155;-13986.2
36(6J)
0.174;-10967.5
(37)(67)
0.180;-9846.3
6(37T)
0.127;-13037.5
6Q(37)
0.170;-12405.0
(67)(39)
0.156;-11283.7
3J(67)
0.131;-12721.2
67(38)
0.142;-13670.0
67(3T)
0.144;-13037.5
67(3Q)
0.144;-12405.0
(38)(68)
0.215;-9213.8
6(38J)
0.183;-12405.0
6K(38)
0.168;-11772.5
(68)(3J)
0.158;-10335.0
3K(68)
0.155;-11772.5
36(8T)
0.139;-12721.2
36(8Q)
0.170;-12088.7
6(39T)
0.157;-12405.0
6Q(39)
0.168;-11772.5
(69)(3J)
0.236;-10018.8
3K(69)
0.167;-11456.2
36(9J)
0.142;-12088.7
36(9K)
0.163;-11456.2
(3T)(6Q)
0.144;-9386.2
3J(6T)
0.154;-11772.5
6T(3J)
0.180;-11772.5
6T(3K)
0.151;-11140.0
6Q(3J)
0.169;-11140.0
(6J)(3K)
0.204;-8753.7
6J(3K)
0.151;-10823.7
6K(3Q)
0.178;-10507.5
36(QK)
0.197;-10507.5
(37)(78)
0.192;-9213.8
7(37J)
0.142;-10335.0
7K(37)
0.163;-9702.5
(378Q)
0.154;-11772.5
8(37T)
0.126;-12405.0
8Q(37)
0.142;-11772.5
J(379)
0.151;-11772.5
9T(37)
0.187;-12088.7
(37)(9K)
0.158;-9070.0
K(37T)
0.203;-10823.7
T(37K)
0.172;-10823.7
JJ(37)
0.215;-9070.0
(37QK)
0.179;-10191.2
3777
0.159;-11600.0
37(7T)
0.161;-10651.2
77(3K)
0.177;-9702.5
7(38T)
0.136;-12405.0
7Q(38)
0.119;-11772.5
(78)(3T)
0.187;-10335.0
3Q(78)
0.158;-11772.5
3789
0.131;-14791.2
378J
0.121;-14158.7
378K
0.161;-13526.3
7J(39)
0.166;-11772.5
(79)(3T)
0.177;-10018.8
3Q(79)
0.170;-11456.2
379T
0.146;-14158.7
379Q
0.149;-13526.3
(3T)(7J)
0.155;-9386.2
3T(7T)
0.147;-9702.5
3(7TK)
0.153;-10823.7
3T(7Q)
0.165;-11140.0
7J(3J)
0.197;-9070.0
(7J)(3Q)
0.221;-8753.7
3J(7Q)
0.175;-10823.7
7Q(3Q)
0.187;-8437.5
37QQ
0.179;-10507.5
37KK
0.201;-9875.0
8(38J)
0.138;-9702.5
8K(38)
0.157;-9070.0
(389K)
0.222;-10823.7
9J(38)
0.158;-11456.2
(38TJ)
0.124;-11140.0
(38)(TJ)
0.214;-9070.0
J(38J)
0.197;-8753.7
JQ(38)
0.136;-10507.5
Q(38K)
0.176;-9875.0
3889
0.158;-12405.0
38(8Q)
0.193;-9386.2
(39)(8T)
0.184;-9702.5
8(39K)
0.144;-10823.7
3(89J)
0.204;-11456.2
3899
0.170;-12088.7
389J
0.188;-13526.3
389K
0.127;-12893.7
8Q(3T)
0.157;-10823.7
(8T)(3Q)
0.170;-8753.7
3T(8J)
0.165;-11140.0
3T(8K)
0.144;-10507.5
8(3JK)
0.145;-10191.2
3(8JK)
0.137;-10191.2
3J(8K)
0.218;-10191.2
3Q(8Q)
0.201;-8121.2
38QK
0.160;-11945.0
9T(39)
0.247;-9386.2
(39)(9K)
0.220;-6367.5
K(39T)
0.136;-10191.2
T(39K)
0.161;-10191.2
JJ(39)
0.203;-8437.5
(39QK)
0.186;-9558.8
3999
0.186;-9702.5
39(9Q)
0.256;-8753.7
(3T)(9J)
0.228;-8753.7
3T(9T)
0.219;-9070.0
3(9TK)
0.146;-10191.2
3T(9Q)
0.211;-10507.5
9J(3J)
0.195;-8437.5
(9J)(3Q)
0.217;-8121.2
3J(9Q)
0.216;-10191.2
9Q(3Q)
0.266;-7805.0
39QQ
0.179;-9875.0
39KK
0.193;-9242.5
T(3TK)
0.215;-7805.0
JJ(3T)
0.210;-8121.2
(3TQK)
0.171;-9242.5
3TTT
0.156;-8753.7
3T(TK)
0.239;-7805.0
(3J)(TK)
0.181;-7488.8
3K(TJ)
0.207;-9558.8
3T(JK)
0.160;-9558.8
(TQ)(3K)
0.224;-7172.5
(3K)(TK)
0.219;-4786.2
J(3JK)
0.204;-7172.5
(3J)(QK)
0.214;-6856.2
JJ(3K)
0.251;-7172.5
3Q(JQ)
0.228;-7172.5
3JQK
0.195;-10996.2
QK(3Q)
0.220;-6540.0
QK(3K)
0.254;-6223.7
44(46)
0.161;-11427.5
44(4T)
0.185;-10162.5
(45)(45)
0.205;-9357.5
4(458)
0.118;-12548.8
4T(45)
0.167;-11916.2
(45)(4K)
0.237;-8897.5
4457
0.112;-14935.0
44(5T)
0.161;-11916.2
45(4K)
0.230;-10967.5
4(468)
0.140;-12232.5
4T(46)
0.183;-11600.0
(46)(4K)
0.200;-8581.2
4468
0.106;-14302.5
44(6J)
0.134;-11283.7
(47)(47)
0.186;-8092.5
4(47T)
0.131;-11283.7
4Q(47)
0.180;-10651.2
47(49)
0.176;-11600.0
447J
0.129;-13037.5
48(48)
0.182;-9530.0
(48)(4J)
0.192;-8581.2
4488
0.193;-11600.0
44(8J)
0.176;-10651.2
(49)(49)
0.236;-6827.5
4(49Q)
0.175;-10018.7
44(9T)
0.155;-10651.2
49(4K)
0.210;-9702.5
4(4TQ)
0.198;-9702.5
44(TJ)
0.234;-10018.7
(4J)(4J)
0.197;-5562.5
44JJ
0.156;-9702.5
4Q(4Q)
0.216;-7000.0
(4K)(4K)
0.269;-4297.5
(45)(57)
0.156;-10478.8
5(45T)
0.189;-11600.0
5Q(45)
0.147;-10967.5
8(456)
0.187;-13986.2
Q(456)
0.126;-12721.2
(45)(68)
0.151;-11916.2
6(45J)
0.154;-13037.5
6K(45)
0.170;-12405.0
(457J)
0.184;-12721.2
(45)(78)
0.187;-11600.0
7(45J)
0.156;-12721.2
7K(45)
0.183;-12088.7
(458Q)
0.162;-12088.7
8(45T)
0.147;-12721.2
8Q(45)
0.152;-12088.7
J(459)
0.150;-12088.7
9T(45)
0.168;-12405.0
(45)(9K)
0.205;-9386.2
K(45T)
0.141;-11140.0
T(45K)
0.140;-11140.0
JJ(45)
0.217;-9386.2
(45QK)
0.175;-10507.5
4555
0.158;-13181.3
45(58)
0.146;-12232.5
55(4J)
0.187;-11283.7
455K
0.146;-12721.2
58(46)
0.119;-13986.2
(46)(5J)
0.153;-10967.5
46(56)
0.163;-12548.8
4(569)
0.134;-13670.0
(56)(4Q)
0.165;-10651.3
46(57)
0.113;-14302.5
46(59)
0.119;-13670.0
46(5J)
0.176;-13037.5
46(5K)
0.158;-12405.0
5(479)
0.150;-13353.7
5J(47)
0.152;-12721.2
(57)(48)
0.166;-11600.0
4T(57)
0.162;-13037.5
4(57K)
0.149;-12088.7
47(59)
0.117;-13353.7
47(5J)
0.151;-12721.2
47(5K)
0.189;-12088.7
5(48T)
0.144;-12721.2
5Q(48)
0.148;-12088.7
(58)(4T)
0.160;-10651.3
4Q(58)
0.124;-12088.7
4589
0.149;-15107.5
458J
0.122;-14475.0
458K
0.171;-13842.5
5J(49)
0.209;-12088.7
(59)(4T)
0.204;-10335.0
4Q(59)
0.210;-11772.5
459T
0.154;-14475.0
459Q
0.164;-13842.5
(4T)(5J)
0.199;-9702.5
4T(5T)
0.161;-10018.7
4(5TK)
0.204;-11140.0
4T(5Q)
0.180;-11456.2
5J(4J)
0.226;-9386.2
(5J)(4Q)
0.236;-9070.0
4J(5Q)
0.154;-11140.0
5Q(4Q)
0.229;-8753.7
45QQ
0.170;-10823.7
45KK
0.171;-10191.2
6(469)
0.171;-11283.7
6J(46)
0.176;-10651.2
(4678)
0.163;-13353.7
(467Q)
0.124;-12088.7
7(469)
0.123;-13037.5
7J(46)
0.201;-12405.0
(4689)
0.137;-12721.2
(468K)
0.195;-11456.2
8T(46)
0.157;-12405.0
(46)(8K)
0.190;-9386.2
Q(469)
0.165;-11456.2
(46)(9J)
0.136;-9702.5
T(46T)
0.201;-9702.5
T(46J)
0.136;-11456.2
TK(46)
0.158;-10823.7
(46)(JQ)
0.145;-8753.7
QQ(46)
0.185;-8437.5
46(67)
0.186;-11916.2
66(4T)
0.193;-10967.5
466Q
0.135;-12405.0
68(47)
0.149;-13353.7
(47)(6J)
0.222;-10335.0
47(67)
0.141;-11600.0
4(67T)
0.139;-12721.2
(67)(4K)
0.140;-9702.5
67(49)
0.161;-13037.5
67(4J)
0.175;-12405.0
67(4K)
0.174;-11772.5
69(48)
0.175;-12721.2
(48)(6Q)
0.220;-9702.5
49(68)
0.169;-12721.2
4(68Q)
0.174;-11772.5
46(89)
0.147;-12721.2
46(8J)
0.164;-12088.7
46(8K)
0.168;-11456.2
(49)(6J)
0.167;-9702.5
49(69)
0.147;-10335.0
4(69Q)
0.126;-11456.2
46(9T)
0.156;-12088.7
46(9Q)
0.173;-11456.2
6(4TJ)
0.132;-11456.2
6K(4T)
0.147;-10823.7
(6T)(4K)
0.172;-8753.7
6T(4Q)
0.164;-11140.0
(4J)(6J)
0.226;-7000.0
4J(6J)
0.186;-9070.0
6J(4Q)
0.147;-10823.7
(4Q)(6Q)
0.175;-6367.5
4K(6Q)
0.172;-10191.2
4K(6K)
0.221;-7805.0
79(47)
0.143;-10651.2
(47)(7Q)
0.183;-7632.5
(478T)
0.177;-12088.7
88(47)
0.189;-10651.2
(47)(8J)
0.163;-9702.5
9(479)
0.212;-10018.7
K(479)
0.156;-10823.7
9(47Q)
0.158;-11140.0
J(47T)
0.181;-11140.0
TJ(47)
0.152;-11140.0
(47JQ)
0.174;-10507.5
J(47K)
0.199;-10191.2
(47)(QK)
0.190;-7805.0
77(49)
0.157;-10651.2
477J
0.194;-12088.7
78(48)
0.149;-10651.2
(48)(7J)
0.243;-9702.5
48(78)
0.136;-10651.2
4(78J)
0.164;-11772.5
4788
0.148;-12721.2
478T
0.122;-14158.7
478Q
0.129;-13526.3
(49)(7T)
0.228;-9702.5
7(49K)
0.175;-10823.7
4(79J)
0.167;-11456.2
4799
0.147;-12088.7
479J
0.149;-13526.3
479K
0.135;-12893.7
7Q(4T)
0.171;-10823.7
(7T)(4Q)
0.174;-8753.7
4T(7J)
0.151;-11140.0
4T(7K)
0.159;-10507.5
7(4JK)
0.193;-10191.2
4(7JK)
0.211;-10191.2
4J(7K)
0.162;-10191.2
4Q(7Q)
0.191;-8121.2
47QK
0.157;-11945.0
89(48)
0.174;-10018.7
(48)(8Q)
0.219;-7000.0
(489J)
0.196;-11140.0
(48)(9T)
0.204;-9386.2
9(48K)
0.161;-10507.5
(48TK)
0.182;-10191.2
TQ(48)
0.152;-10507.5
K(48J)
0.185;-9875.0
Q(48Q)
0.193;-7805.0
KK(48)
0.187;-7172.5
88(4J)
0.142;-9386.2
488K
0.154;-10823.7
8J(49)
0.205;-11140.0
(89)(4T)
0.179;-9386.2
4Q(89)
0.172;-10823.7
489T
0.158;-13526.3
489Q
0.143;-12893.7
(4T)(8J)
0.191;-8753.7
4T(8T)
0.166;-9070.0
4(8TK)
0.160;-10191.2
4T(8Q)
0.166;-10507.5
8J(4J)
0.253;-8437.5
(8J)(4Q)
0.245;-8121.2
4J(8Q)
0.149;-10191.2
8Q(4Q)
0.221;-7805.0
48QQ
0.207;-9875.0
48KK
0.146;-9242.5
9(49Q)
0.162;-8437.5
J(49T)
0.174;-10507.5
TJ(49)
0.200;-10507.5
(49JQ)
0.224;-9875.0
J(49K)
0.234;-9558.8
(49)(QK)
0.198;-7172.5
99(4J)
0.177;-8753.7
499K
0.156;-10191.2
9Q(4T)
0.188;-10191.2
(9T)(4Q)
0.177;-8121.2
4T(9J)
0.154;-10507.5
4T(9K)
0.171;-9875.0
9(4JK)
0.166;-9558.8
4(9JK)
0.201;-9558.8
4J(9K)
0.190;-9558.8
4Q(9Q)
0.207;-7488.8
49QK
0.158;-11312.5
TJ(4T)
0.205;-8121.2
(4TJQ)
0.158;-9558.8
J(4TK)
0.170;-9242.5
(4T)(QK)
0.214;-6856.2
TT(4Q)
0.251;-7805.0
T(4JQ)
0.156;-9558.8
4(TJQ)
0.162;-9558.8
4T(JQ)
0.232;-9558.8
T(4QK)
0.183;-8926.2
TQ(4K)
0.156;-8926.2
JJ(4J)
0.217;-5418.8
(4JQK)
0.180;-8610.0
4JJJ
0.248;-7488.8
JQ(4Q)
0.190;-6856.2
4JQQ
0.199;-8926.2
4JKK
0.199;-8293.8
QQ(4K)
0.212;-6223.7
4KKK
0.291;-5591.3
55(59)
0.180;-9530.0
55(5K)
0.192;-8265.0
(56)(58)
0.168;-9530.0
5(56J)
0.139;-10651.2
5K(56)
0.176;-10018.7
56(59)
0.165;-11283.7
556J
0.139;-12721.2
57(57)
0.218;-9530.0
(57)(5T)
0.181;-8581.2
5(57K)
0.151;-9702.5
55(79)
0.155;-10967.5
57(5Q)
0.183;-10018.7
5(589)
0.146;-10651.2
5J(58)
0.155;-10018.7
58(59)
0.137;-10651.2
558J
0.118;-12088.7
59(59)
0.210;-8265.0
(59)(5Q)
0.253;-7316.2
559T
0.188;-12088.7
55(9K)
0.156;-9070.0
(5T)(5Q)
0.174;-7000.0
55TJ
0.171;-11456.2
5J(5J)
0.262;-7000.0
5J(5Q)
0.219;-8753.7
5(5QK)
0.167;-8121.2
5K(5K)
0.204;-5735.0
68(56)
0.186;-11283.7
(56)(6J)
0.218;-8265.0
7(567)
0.169;-11283.7
J(567)
0.168;-12088.7
78(56)
0.195;-13037.5
(56)(7J)
0.167;-10018.8
8(568)
0.176;-10651.2
Q(568)
0.150;-11456.2
(56)(8T)
0.176;-10018.8
8(56K)
0.194;-11140.0
(569Q)
0.165;-11140.0
9(56J)
0.190;-11456.2
9K(56)
0.223;-10823.7
TT(56)
0.198;-9386.2
(56)(TK)
0.151;-8437.5
J(56Q)
0.183;-10507.5
K(56Q)
0.203;-9875.0
66(57)
0.183;-11600.0
5669
0.169;-13037.5
56(6Q)
0.230;-10018.7
(57)(68)
0.199;-10967.5
6(57J)
0.209;-12088.7
6K(57)
0.155;-11456.2
(67)(5T)
0.194;-10335.0
5Q(67)
0.177;-11772.5
5678
0.157;-15107.5
567T
0.153;-14475.0
567Q
0.121;-13842.5
(58)(69)
0.186;-10335.0
6(58Q)
0.154;-11456.2
5(689)
0.185;-12405.0
(68)(5Q)
0.178;-9386.2
58(69)
0.158;-12405.0
58(6J)
0.161;-11772.5
58(6K)
0.149;-11140.0
6(59J)
0.210;-11456.2
6K(59)
0.178;-10823.7
(69)(5Q)
0.178;-9070.0
59(6T)
0.161;-11772.5
59(6Q)
0.152;-11140.0
6T(5T)
0.155;-9386.2
(5T)(6K)
0.218;-8437.5
5Q(6T)
0.147;-10823.7
56TJ
0.120;-13210.0
56TK
0.155;-12577.5
6K(5J)
0.166;-10191.2
56JJ
0.221;-10823.7
56JK
0.162;-12261.2
5(6QK)
0.176;-9875.0
6K(5K)
0.237;-7488.8
(57)(79)
0.238;-8265.0
7(57Q)
0.221;-9386.2
9(578)
0.158;-12088.7
K(578)
0.150;-10823.7
8(57J)
0.191;-11456.2
8K(57)
0.180;-10823.7
(579K)
0.188;-10507.5
9J(57)
0.153;-11140.0
(57TJ)
0.173;-10823.7
(57)(TJ)
0.159;-8753.7
J(57J)
0.210;-8437.5
JQ(57)
0.174;-10191.2
Q(57K)
0.196;-9558.8
5778
0.147;-12721.2
57(7J)
0.168;-9702.5
(58)(78)
0.182;-8265.0
7(58J)
0.142;-11456.2
7K(58)
0.148;-10823.7
(78)(5J)
0.188;-9386.2
5K(78)
0.146;-10823.7
57(8T)
0.143;-11772.5
57(8Q)
0.143;-11140.0
7(59T)
0.140;-11456.2
7Q(59)
0.188;-10823.7
(79)(5J)
0.164;-9070.0
5K(79)
0.190;-10507.5
57(9J)
0.151;-11140.0
57(9K)
0.145;-10507.5
(5T)(7Q)
0.198;-8437.5
5J(7T)
0.142;-10823.7
7T(5J)
0.129;-10823.7
7T(5K)
0.173;-10191.2
7Q(5J)
0.206;-10191.2
(7J)(5K)
0.241;-7805.0
7J(5K)
0.136;-9875.0
7K(5Q)
0.172;-9558.8
57(QK)
0.189;-9558.8
(58)(89)
0.245;-7632.5
8(58Q)
0.200;-8753.7
T(589)
0.157;-11140.0
9(58T)
0.144;-11140.0
9Q(58)
0.167;-10507.5
Q(58T)
0.190;-10191.2
(58)(TQ)
0.195;-8121.2
(58JK)
0.198;-9558.8
JK(58)
0.178;-9558.8
K(58K)
0.231;-6856.2
588T
0.200;-11456.2
58(8K)
0.212;-8437.5
(59)(8J)
0.163;-8753.7
59(89)
0.178;-9386.2
5(89Q)
0.155;-10507.5
58(9T)
0.154;-11140.0
58(9Q)
0.195;-10507.5
8(5TJ)
0.201;-10507.5
8K(5T)
0.197;-9875.0
(8T)(5K)
0.209;-7805.0
8T(5Q)
0.212;-10191.2
(5J)(8J)
0.229;-6051.2
5J(8J)
0.201;-8121.2
8J(5Q)
0.206;-9875.0
(5Q)(8Q)
0.245;-5418.8
5K(8Q)
0.155;-9242.5
5K(8K)
0.195;-6856.2
9J(59)
0.239;-8437.5
(59TJ)
0.198;-10191.2
(59)(TJ)
0.214;-8121.2
J(59J)
0.155;-7805.0
JQ(59)
0.168;-9558.8
Q(59K)
0.210;-8926.2
599T
0.150;-10823.7
59(9K)
0.207;-7805.0
(5T)(9Q)
0.172;-7805.0
5J(9T)
0.158;-10191.2
9T(5J)
0.165;-10191.2
9T(5K)
0.159;-9558.8
9Q(5J)
0.164;-9558.8
(9J)(5K)
0.204;-7172.5
9J(5K)
0.180;-9242.5
9K(5Q)
0.163;-8926.2
59(QK)
0.157;-8926.2
(5T)(TJ)
0.245;-5735.0
J(5TJ)
0.182;-7488.8
JQ(5T)
0.199;-9242.5
Q(5TK)
0.201;-8610.0
5TTJ
0.196;-9875.0
TJ(5J)
0.233;-7488.8
(TJ)(5Q)
0.199;-7172.5
5J(TQ)
0.166;-9242.5
TQ(5Q)
0.190;-6856.2
5TQQ
0.211;-8926.2
5TKK
0.253;-8293.8
Q(5JQ)
0.205;-6540.0
KK(5J)
0.232;-5907.5
(5Q)(JQ)
0.251;-4470.0
5K(JQ)
0.188;-8293.8
5K(JK)
0.185;-5907.5
5QQQ
0.254;-6223.7
KK(5K)
0.295;-3205.0
6669
0.141;-10651.3
666K
0.176;-9386.2
69(67)
0.182;-10335.0
(67)(6Q)
0.234;-7316.2
6678
0.161;-12721.2
66(7J)
0.149;-9702.5
(68)(68)
0.212;-6195.0
6(68J)
0.246;-9386.2
6K(68)
0.239;-8753.7
68(6J)
0.180;-9386.2
668K
0.147;-10823.7
6J(69)
0.200;-9070.0
69(6T)
0.197;-9386.2
669Q
0.223;-10823.7
6J(6T)
0.161;-8753.7
6T(6J)
0.188;-8753.7
66TK
0.193;-10191.2
6K(6J)
0.163;-7805.0
(6Q)(6Q)
0.235;-3665.0
66QK
0.182;-9558.8
7(679)
0.171;-10018.7
7J(67)
0.179;-9386.2
(6789)
0.182;-11772.5
(678K)
0.184;-10507.5
8T(67)
0.211;-11456.2
(67)(8K)
0.185;-8437.5
Q(679)
0.176;-10507.5
(67)(9J)
0.199;-8753.7
T(67T)
0.173;-8753.7
T(67J)
0.190;-10507.5
TK(67)
0.191;-9875.0
(67)(JQ)
0.204;-7805.0
QQ(67)
0.245;-7488.8
67(78)
0.177;-10335.0
77(6J)
0.189;-9386.2
677K
0.163;-10823.7
7T(68)
0.171;-11456.2
(68)(7K)
0.233;-8437.5
6T(78)
0.191;-11456.2
6(78K)
0.203;-10507.5
68(7T)
0.176;-11456.2
68(7Q)
0.132;-10823.7
79(69)
0.223;-9386.2
(69)(7Q)
0.227;-8437.5
6T(79)
0.164;-11140.0
6(79K)
0.180;-10191.2
69(7J)
0.167;-10823.7
69(7K)
0.161;-10191.2
7(6TQ)
0.189;-10191.2
6(7TJ)
0.171;-10507.5
67TT
0.198;-10823.7
67TQ
0.148;-12261.2
(6J)(7Q)
0.193;-7805.0
6Q(7J)
0.153;-9875.0
67JQ
0.122;-11945.0
(6Q)(7K)
0.195;-7172.5
6Q(7K)
0.144;-9242.5
8(689)
0.225;-9386.2
8J(68)
0.202;-8753.7
(689T)
0.189;-10823.7
99(68)
0.182;-9070.0
(68)(9Q)
0.216;-8121.2
(68TQ)
0.138;-9875.0
T(68Q)
0.190;-9875.0
Q(68J)
0.151;-9558.8
(68)(JK)
0.206;-7172.5
QK(68)
0.166;-8926.2
68(8T)
0.213;-9070.0
88(6K)
0.190;-8121.2
8(69J)
0.163;-10507.5
8K(69)
0.148;-9875.0
(89)(6Q)
0.212;-8121.2
69(8T)
0.192;-10823.7
69(8Q)
0.199;-10191.2
8T(6T)
0.196;-8437.5
(6T)(8K)
0.264;-7488.8
6Q(8T)
0.182;-9875.0
68TJ
0.163;-12261.2
68TK
0.150;-11628.8
8K(6J)
0.183;-9242.5
68JJ
0.145;-9875.0
68JK
0.189;-11312.5
6(8QK)
0.203;-8926.2
8K(6K)
0.182;-6540.0
(69)(9J)
0.217;-6051.2
T(69T)
0.175;-8121.2
T(69J)
0.178;-9875.0
TK(69)
0.217;-9242.5
(69)(JQ)
0.268;-7172.5
QQ(69)
0.195;-6856.2
69(9T)
0.172;-8437.5
99(6K)
0.182;-7488.8
9(6TQ)
0.175;-9558.8
6(9TJ)
0.193;-9875.0
69TT
0.159;-10191.2
69TQ
0.131;-11628.8
(6J)(9Q)
0.250;-7172.5
6Q(9J)
0.166;-9242.5
69JQ
0.197;-11312.5
(6Q)(9K)
0.262;-6540.0
6Q(9K)
0.204;-8610.0
T(6TJ)
0.203;-7488.8
TK(6T)
0.248;-6856.2
(6T)(JQ)
0.252;-6856.2
QQ(6T)
0.230;-6540.0
6T(TJ)
0.234;-7488.8
(6J)(TJ)
0.312;-5102.5
6J(TJ)
0.259;-7172.5
TJ(6Q)
0.166;-8926.2
(6Q)(TQ)
0.284;-4470.0
6K(TQ)
0.224;-8293.8
6K(TK)
0.285;-5907.5
JK(6J)
0.197;-6223.7
K(6JK)
0.212;-5591.3
6JJK
0.161;-8293.8
6(JQK)
0.222;-7977.5
JK(6K)
0.181;-5591.3
KK(6Q)
0.256;-5275.0
6QKK
0.194;-7345.0
77(7T)
0.181;-7316.2
(78)(78)
0.187;-5562.5
7(78J)
0.193;-8753.7
7K(78)
0.221;-8121.2
78(7J)
0.188;-8753.7
778K
0.190;-10191.2
7J(79)
0.235;-8437.5
79(7T)
0.237;-8753.7
779Q
0.207;-10191.2
7J(7T)
0.195;-8121.2
7T(7J)
0.242;-8121.2
77TK
0.216;-9558.8
7K(7J)
0.193;-7172.5
(7Q)(7Q)
0.236;-3032.5
77QK
0.185;-8926.2
8(78T)
0.189;-8753.7
8Q(78)
0.198;-8121.2
J(789)
0.159;-10191.2
9T(78)
0.189;-10507.5
(78)(9K)
0.203;-7488.8
K(78T)
0.172;-9242.5
T(78K)
0.238;-9242.5
JJ(78)
0.254;-7488.8
(78QK)
0.168;-8610.0
7888
0.210;-9386.2
78(8J)
0.169;-8437.5
(79)(89)
0.250;-6683.8
8(79Q)
0.178;-9875.0
7(89T)
0.132;-10507.5
(89)(7K)
0.197;-7488.8
89(7J)
0.183;-10191.2
89(7K)
0.175;-9558.8
8J(7T)
0.202;-9875.0
(8T)(7J)
0.203;-7805.0
7K(8T)
0.197;-9242.5
78(TQ)
0.172;-9558.8
8(7JQ)
0.200;-9242.5
7(8JQ)
0.149;-9242.5
78(JQ)
0.165;-9242.5
8(7QK)
0.153;-8610.0
8Q(7K)
0.161;-8610.0
99(79)
0.217;-6367.5
(79)(9Q)
0.274;-5418.8
(79TQ)
0.157;-9242.5
T(79Q)
0.187;-9242.5
Q(79J)
0.198;-8926.2
(79)(JK)
0.208;-6540.0
QK(79)
0.182;-8293.8
79(9J)
0.191;-7805.0
(7T)(9T)
0.220;-5735.0
9(7TK)
0.187;-8926.2
7(9TQ)
0.224;-9242.5
79(TJ)
0.165;-9558.8
79(TK)
0.191;-8926.2
(7J)(9K)
0.233;-6540.0
7K(9J)
0.213;-8610.0
79(JK)
0.192;-8610.0
(9Q)(7K)
0.197;-6223.7
(7K)(9K)
0.259;-3837.5
T(7TQ)
0.165;-6856.2
Q(7TJ)
0.144;-8610.0
(7T)(JK)
0.201;-6223.7
QK(7T)
0.234;-7977.5
7T(TQ)
0.192;-6856.2
(7J)(TQ)
0.258;-6540.0
7Q(TJ)
0.161;-8610.0
7TJQ
0.148;-10680.0
(7Q)(TK)
0.220;-5907.5
7Q(TK)
0.190;-7977.5
J(7JQ)
0.215;-6223.7
K(7JQ)
0.193;-7661.2
JJ(7Q)
0.195;-6223.7
J(7QK)
0.206;-7661.2
JQ(7K)
0.166;-7661.2
QQ(7Q)
0.249;-3521.3
7Q(QK)
0.254;-5275.0
8888
0.203;-7000.0
888Q
0.206;-7805.0
8(89J)
0.245;-7805.0
8K(89)
0.165;-7172.5
89(8Q)
0.173;-7488.8
8(8TJ)
0.230;-7488.8
8K(8T)
0.198;-6856.2
8T(8K)
0.186;-6856.2
8(8JK)
0.181;-6540.0
88(JK)
0.190;-6540.0
8Q(8K)
0.226;-6223.7
(89)(9T)
0.216;-5735.0
9(89K)
0.200;-6856.2
(89TK)
0.191;-8610.0
TQ(89)
0.183;-8926.2
K(89J)
0.179;-8293.8
Q(89Q)
0.193;-6223.7
KK(89)
0.214;-5591.3
99(8Q)
0.206;-7172.5
9(8TJ)
0.150;-9242.5
9K(8T)
0.191;-8610.0
(9T)(8K)
0.223;-6540.0
9T(8Q)
0.171;-8926.2
(8J)(9J)
0.311;-4786.2
8J(9J)
0.237;-6856.2
9J(8Q)
0.212;-8610.0
(8Q)(9Q)
0.269;-4153.7
8K(9Q)
0.194;-7977.5
8K(9K)
0.248;-5591.3
TQ(8T)
0.268;-6540.0
K(8TJ)
0.262;-7977.5
Q(8TQ)
0.219;-5907.5
KK(8T)
0.273;-5275.0
