AAAA
0.360;2025.0
5AAA
0.211;421.9
9AAA
0.286;834.4
KAAA
0.339;1246.9
4A(2A)
0.124;-918.8
(2A)(7A)
0.216;65.6
A(2TA)
0.160;-300.0
QA(2A)
0.207;-93.7
2A(4A)
0.138;-918.8
26AA
0.094;-1387.5
AA(29)
0.157;-403.1
2A(QA)
0.232;-93.7
A(34A)
0.150;-815.6
6A(3A)
0.147;-609.4
(3A)(9A)
0.234;375.0
A(3QA)
0.215;9.4
AA(34)
0.139;-815.6
3A(7A)
0.159;-506.3
39AA
0.167;-975.0
AA(3Q)
0.205;9.4
(4A)(5A)
0.186;65.6
A(48A)
0.156;-300.0
TA(4A)
0.227;-93.7
(4A)(KA)
0.258;890.6
46AA
0.131;-1181.3
AA(49)
0.189;-196.9
4A(QA)
0.255;112.5
A(56A)
0.177;-403.1
8A(5A)
0.195;-196.9
(5A)(JA)
0.262;787.5
55AA
0.181;-506.3
AA(58)
0.191;-196.9
5A(JA)
0.178;112.5
5KAA
0.187;-356.3
8A(6A)
0.192;-93.7
(6A)(JA)
0.260;890.6
66AA
0.161;-300.0
AA(69)
0.211;9.4
6A(QA)
0.282;318.7
A(78A)
0.192;9.4
TA(7A)
0.178;215.6
(7A)(KA)
0.270;1200.0
79AA
0.154;-562.5
AA(7Q)
0.232;421.9
(8A)(9A)
0.235;890.6
A(8QA)
0.263;525.0
AA(89)
0.219;215.6
8A(QA)
0.214;525.0
A(9TA)
0.244;421.9
QA(9A)
0.214;628.1
9A(JA)
0.252;525.0
9KAA
0.204;56.2
QA(TA)
0.240;731.2
TA(QA)
0.274;731.2
A(JQA)
0.266;834.4
AA(JQ)
0.275;834.4
(QA)(KA)
0.352;1715.6
KKAA
0.262;1143.8
2(25A)
0.076;-2053.1
27(2A)
0.098;-1846.9
(2T)(2A)
0.129;-862.5
2(2KA)
0.112;-1228.1
(236A)
0.064;-2521.9
(23TA)
0.071;-2109.4
33(2A)
0.090;-2156.3
(36)(2A)
0.095;-1846.9
3(29A)
0.066;-2212.5
3J(2A)
0.077;-2006.3
(245A)
0.042;-2521.9
(249A)
0.060;-2109.4
(24KA)
0.091;-1696.9
46(2A)
0.047;-2418.8
(49)(2A)
0.104;-1434.4
4(2QA)
0.089;-1800.0
6(25A)
0.054;-2315.6
T(25A)
0.096;-1903.1
5(26A)
0.072;-2315.6
58(2A)
0.075;-2109.4
(5J)(2A)
0.118;-1125.0
6(26A)
0.108;-1537.5
T(26A)
0.086;-1800.0
6(27A)
0.076;-2109.4
69(2A)
0.080;-1903.1
(6Q)(2A)
0.136;-918.8
(279A)
0.108;-1800.0
(27KA)
0.098;-1387.5
79(2A)
0.103;-1800.0
(7Q)(2A)
0.129;-815.6
(28TA)
0.100;-1593.8
88(2A)
0.156;-1125.0
(8J)(2A)
0.116;-815.6
9(29A)
0.150;-918.8
K(29A)
0.136;-1181.3
9(2QA)
0.109;-1284.4
J(2TA)
0.129;-1284.4
TJ(2A)
0.136;-1284.4
(2JQA)
0.108;-1078.1
J(2KA)
0.115;-975.0
(QK)(2A)
0.180;-196.9
22(4A)
0.064;-2156.3
226A
0.035;-2625.0
2A(29)
0.126;-1640.6
22(QA)
0.136;-1331.3
2(34A)
0.044;-2728.1
26(3A)
0.049;-2521.9
(29)(3A)
0.095;-1537.5
2(3QA)
0.071;-1903.1
A(234)
0.035;-2728.1
(23)(7A)
0.086;-1743.8
9A(23)
0.066;-2212.5
A(23Q)
0.090;-1903.1
2A(34)
0.049;-2728.1
2A(36)
0.048;-2521.9
2A(38)
0.057;-2315.6
2A(3T)
0.059;-2109.4
2A(3Q)
0.096;-1903.1
2(45A)
0.067;-2521.9
27(4A)
0.057;-2315.6
(2T)(4A)
0.091;-1331.3
2(4KA)
0.081;-1696.9
A(246)
0.056;-2418.8
(24)(9A)
0.121;-1434.4
JA(24)
0.063;-1903.1
24(5A)
0.049;-2521.9
24(7A)
0.054;-2315.6
24(9A)
0.076;-2109.4
24(JA)
0.071;-1903.1
24(KA)
0.107;-1696.9
26(5A)
0.068;-2315.6
(29)(5A)
0.106;-1331.3
2(5QA)
0.086;-1696.9
A(256)
0.057;-2315.6
(25)(9A)
0.106;-1331.3
JA(25)
0.104;-1800.0
25(6A)
0.052;-2315.6
25(8A)
0.070;-2109.4
25(TA)
0.068;-1903.1
25(QA)
0.077;-1696.9
(26)(6A)
0.136;-862.5
2(69A)
0.073;-1903.1
2J(6A)
0.093;-1696.9
(26)(7A)
0.123;-1434.4
9A(26)
0.079;-1903.1
A(26Q)
0.105;-1593.8
2A(67)
0.088;-2109.4
2A(69)
0.074;-1903.1
2A(6J)
0.087;-1696.9
2A(6K)
0.113;-1490.6
(29)(7A)
0.106;-1125.0
2(7QA)
0.125;-1490.6
A(278)
0.084;-1903.1
(27)(JA)
0.121;-918.8
KA(27)
0.096;-1387.5
2A(79)
0.091;-1800.0
2A(7J)
0.117;-1593.8
2A(7K)
0.101;-1387.5
(2T)(8A)
0.155;-918.8
2(8KA)
0.121;-1284.4
A(28T)
0.108;-1593.8
(28)(KA)
0.166;-609.4
28(TA)
0.080;-1593.8
28(QA)
0.129;-1387.5
(29)(9A)
0.191;-243.8
2(9QA)
0.134;-1284.4
A(29T)
0.118;-1490.6
(29)(KA)
0.136;-506.3
29(JA)
0.115;-1387.5
29(KA)
0.099;-1181.3
2J(TA)
0.118;-1284.4
(2T)(JA)
0.151;-609.4
KA(2T)
0.129;-1078.1
2A(TQ)
0.122;-1181.3
2(JQA)
0.145;-1078.1
A(2JQ)
0.124;-1078.1
2A(JQ)
0.153;-1078.1
2(QKA)
0.168;-871.9
2Q(KA)
0.126;-871.9
33(3A)
0.130;-1378.1
(36)(3A)
0.111;-1068.8
3(39A)
0.080;-1434.4
3J(3A)
0.132;-1228.1
(345A)
0.075;-2418.8
(349A)
0.068;-2006.3
(34KA)
0.090;-1593.8
46(3A)
0.069;-2315.6
(49)(3A)
0.138;-1331.3
4(3QA)
0.116;-1696.9
6(35A)
0.054;-2212.5
T(35A)
0.105;-1800.0
5(36A)
0.057;-2212.5
58(3A)
0.084;-2006.3
(5J)(3A)
0.148;-1021.9
6(36A)
0.100;-1434.4
T(36A)
0.079;-1696.9
6(37A)
0.060;-2006.3
69(3A)
0.088;-1800.0
(6Q)(3A)
0.149;-815.6
(379A)
0.100;-1696.9
(37KA)
0.127;-1284.4
79(3A)
0.104;-1696.9
(7Q)(3A)
0.156;-712.5
(38TA)
0.111;-1490.6
88(3A)
0.112;-1021.9
(8J)(3A)
0.151;-712.5
9(39A)
0.176;-815.6
K(39A)
0.138;-1078.1
9(3QA)
0.113;-1181.3
J(3TA)
0.110;-1181.3
TJ(3A)
0.141;-1181.3
(3JQA)
0.124;-975.0
J(3KA)
0.123;-871.9
(QK)(3A)
0.194;-93.7
33(5A)
0.082;-1846.9
337A
0.063;-2315.6
3A(3T)
0.115;-1331.3
33(KA)
0.159;-1021.9
3(46A)
0.070;-2315.6
38(4A)
0.085;-2109.4
(3J)(4A)
0.118;-1125.0
4A(34)
0.076;-1846.9
A(347)
0.075;-2212.5
(34)(TA)
0.120;-1228.1
QA(34)
0.111;-1696.9
345A
0.026;-3093.8
347A
0.046;-2887.5
349A
0.048;-2681.3
34JA
0.043;-2475.0
34KA
0.068;-2268.8
37(5A)
0.084;-2109.4
(3T)(5A)
0.134;-1125.0
3(5KA)
0.107;-1490.6
A(357)
0.052;-2109.4
(35)(TA)
0.120;-1125.0
QA(35)
0.087;-1593.8
356A
0.043;-2887.5
358A
0.055;-2681.3
35TA
0.054;-2475.0
35QA
0.073;-2268.8
(37)(6A)
0.117;-1331.3
3(6TA)
0.089;-1696.9
3Q(6A)
0.113;-1490.6
(36)(8A)
0.126;-1228.1
TA(36)
0.082;-1696.9
A(36K)
0.124;-1387.5
6A(38)
0.081;-1903.1
6A(3T)
0.094;-1696.9
6A(3Q)
0.102;-1490.6
37(7A)
0.105;-1228.1
(3T)(7A)
0.150;-918.8
3(7KA)
0.115;-1284.4
A(379)
0.082;-1696.9
(37)(QA)
0.113;-712.5
7A(38)
0.111;-1800.0
7A(3T)
0.112;-1593.8
7A(3Q)
0.101;-1387.5
38(8A)
0.151;-1021.9
(3J)(8A)
0.165;-712.5
8A(38)
0.140;-1021.9
A(38J)
0.112;-1387.5
388A
0.087;-1696.9
38TA
0.062;-2165.6
38QA
0.086;-1959.4
(3T)(9A)
0.166;-712.5
3(9KA)
0.130;-1078.1
A(39J)
0.107;-1284.4
399A
0.126;-1490.6
39JA
0.108;-1959.4
39KA
0.096;-1753.1
3Q(TA)
0.156;-1078.1
(3T)(QA)
0.194;-403.1
TA(3J)
0.110;-1181.3
TA(3K)
0.149;-975.0
3(JKA)
0.127;-871.9
A(3JK)
0.171;-871.9
JA(3K)
0.168;-871.9
QA(3Q)
0.206;-196.9
3QKA
0.116;-1443.7
45(4A)
0.089;-1640.6
(48)(4A)
0.164;-656.3
4(4JA)
0.134;-1021.9
4K(4A)
0.160;-815.6
(459A)
0.110;-1800.0
(45KA)
0.112;-1387.5
57(4A)
0.065;-2006.3
(5T)(4A)
0.129;-1021.9
5(4KA)
0.093;-1387.5
(469A)
0.089;-1696.9
(46KA)
0.118;-1284.4
68(4A)
0.078;-1800.0
(6J)(4A)
0.168;-815.6
7(47A)
0.127;-1125.0
J(47A)
0.128;-1387.5
78(4A)
0.084;-1696.9
(7J)(4A)
0.157;-712.5
8(48A)
0.139;-918.8
Q(48A)
0.119;-1181.3
(8T)(4A)
0.153;-712.5
8(4KA)
0.130;-1078.1
(49QA)
0.139;-1078.1
9(4JA)
0.140;-1181.3
9K(4A)
0.159;-975.0
TT(4A)
0.185;-506.3
(TK)(4A)
0.197;-196.9
J(4QA)
0.129;-871.9
K(4QA)
0.144;-665.6
44(5A)
0.086;-1640.6
447A
0.057;-2109.4
4A(4T)
0.124;-1125.0
44(KA)
0.141;-815.6
4(57A)
0.072;-2006.3
49(5A)
0.106;-1800.0
(4Q)(5A)
0.122;-815.6
6A(45)
0.070;-2109.4
A(459)
0.077;-1800.0
(45)(QA)
0.163;-815.6
5A(46)
0.062;-2109.4
5A(48)
0.100;-1903.1
5A(4T)
0.078;-1696.9
5A(4Q)
0.101;-1490.6
46(6A)
0.099;-1331.3
(49)(6A)
0.164;-1021.9
4(6QA)
0.116;-1387.5
A(467)
0.080;-1903.1
(46)(TA)
0.143;-918.8
QA(46)
0.104;-1387.5
467A
0.040;-2578.1
469A
0.067;-2371.9
46JA
0.069;-2165.6
46KA
0.077;-1959.4
49(7A)
0.096;-1593.8
(4Q)(7A)
0.130;-609.4
8A(47)
0.098;-1696.9
A(47J)
0.134;-1387.5
477A
0.093;-1800.0
479A
0.071;-2268.8
47JA
0.056;-2062.5
47KA
0.069;-1856.3
4T(8A)
0.089;-1387.5
(4K)(8A)
0.137;-403.1
TA(48)
0.106;-1387.5
A(48K)
0.159;-1078.1
8A(4T)
0.115;-1387.5
8A(4Q)
0.119;-1181.3
49(9A)
0.147;-712.5
(4Q)(9A)
0.211;-403.1
TA(49)
0.098;-1284.4
A(49K)
0.149;-975.0
9A(4J)
0.104;-1181.3
9A(4K)
0.107;-975.0
4(TQA)
0.133;-975.0
A(4TJ)
0.136;-1078.1
4TTA
0.144;-1181.3
4TQA
0.094;-1650.0
(4Q)(JA)
0.230;-196.9
QA(4J)
0.129;-871.9
4JQA
0.117;-1546.9
(4K)(QA)
0.260;9.4
QA(4K)
0.134;-665.6
5(56A)
0.120;-1331.3
58(5A)
0.110;-1125.0
(5J)(5A)
0.179;-140.6
6(56A)
0.103;-1228.1
T(56A)
0.109;-1490.6
6(57A)
0.084;-1800.0
69(5A)
0.086;-1593.8
(6Q)(5A)
0.159;-609.4
(579A)
0.116;-1490.6
(57KA)
0.120;-1078.1
79(5A)
0.117;-1490.6
(7Q)(5A)
0.152;-506.3
(58TA)
0.120;-1284.4
88(5A)
0.133;-815.6
(8J)(5A)
0.132;-506.3
9(59A)
0.176;-609.4
K(59A)
0.178;-871.9
9(5QA)
0.164;-975.0
J(5TA)
0.131;-975.0
TJ(5A)
0.163;-975.0
(5JQA)
0.160;-768.7
J(5KA)
0.142;-665.6
(QK)(5A)
0.263;112.5
55(7A)
0.126;-1228.1
559A
0.079;-1696.9
5A(5Q)
0.121;-712.5
(57)(6A)
0.124;-1125.0
5(6TA)
0.115;-1490.6
5Q(6A)
0.100;-1284.4
(56)(8A)
0.110;-1021.9
TA(56)
0.115;-1490.6
A(56K)
0.102;-1181.3
6A(58)
0.092;-1696.9
6A(5T)
0.113;-1490.6
6A(5Q)
0.108;-1284.4
57(7A)
0.119;-1021.9
(5T)(7A)
0.176;-712.5
5(7KA)
0.116;-1078.1
A(579)
0.090;-1490.6
(57)(QA)
0.152;-506.3
7A(58)
0.087;-1593.8
7A(5T)
0.125;-1387.5
7A(5Q)
0.125;-1181.3
58(8A)
0.161;-815.6
(5J)(8A)
0.164;-506.3
8A(58)
0.137;-815.6
A(58J)
0.102;-1181.3
588A
0.092;-1490.6
58TA
0.070;-1959.4
58QA
0.098;-1753.1
(5T)(9A)
0.154;-506.3
5(9KA)
0.157;-871.9
A(59J)
0.167;-1078.1
599A
0.120;-1284.4
59JA
0.072;-1753.1
59KA
0.120;-1546.9
5Q(TA)
0.131;-871.9
(5T)(QA)
0.210;-196.9
TA(5J)
0.144;-975.0
TA(5K)
0.151;-768.7
5(JKA)
0.161;-665.6
A(5JK)
0.160;-665.6
JA(5K)
0.132;-665.6
QA(5Q)
0.259;9.4
5QKA
0.120;-1237.5
67(6A)
0.143;-1021.9
(6T)(6A)
0.178;-37.5
6(6KA)
0.164;-403.1
(67TA)
0.108;-1284.4
77(6A)
0.147;-918.8
(7T)(6A)
0.186;-609.4
7(6KA)
0.161;-975.0
(68JA)
0.128;-1078.1
(89)(6A)
0.154;-609.4
8(6QA)
0.142;-975.0
T(69A)
0.131;-1078.1
9(6TA)
0.144;-1078.1
9Q(6A)
0.157;-871.9
Q(6TA)
0.145;-768.7
(TQ)(6A)
0.221;-93.7
(6JKA)
0.188;-562.5
JK(6A)
0.199;-562.5
K(6KA)
0.260;318.7
668A
0.102;-1593.8
6A(6J)
0.145;-609.4
(67)(7A)
0.198;-243.8
6(7TA)
0.127;-1284.4
6Q(7A)
0.143;-1078.1
(67)(9A)
0.153;-712.5
JA(67)
0.123;-1181.3
67(8A)
0.118;-1490.6
67(TA)
0.104;-1284.4
67(QA)
0.113;-1078.1
(68)(8A)
0.235;-37.5
6(8JA)
0.110;-1078.1
6K(8A)
0.152;-871.9
(68)(JA)
0.196;-403.1
KA(68)
0.151;-871.9
6A(8T)
0.133;-1181.3
6A(8Q)
0.133;-975.0
6(9TA)
0.123;-1078.1
6Q(9A)
0.140;-871.9
(69)(JA)
0.195;-300.0
KA(69)
0.179;-768.7
6A(9J)
0.143;-975.0
6A(9K)
0.139;-768.7
(6Q)(TA)
0.196;-93.7
JA(6T)
0.116;-871.9
6T(JA)
0.144;-871.9
6T(KA)
0.180;-665.6
6Q(JA)
0.185;-665.6
(6J)(KA)
0.249;112.5
6J(KA)
0.187;-562.5
6K(QA)
0.210;-459.4
6A(QK)
0.212;-459.4
(78)(7A)
0.180;-37.5
7(7JA)
0.168;-403.1
7K(7A)
0.173;-196.9
(78QA)
0.140;-871.9
8(7TA)
0.136;-1078.1
8Q(7A)
0.170;-871.9
J(79A)
0.159;-871.9
9T(7A)
0.112;-975.0
(9K)(7A)
0.208;9.4
K(7TA)
0.187;-562.5
T(7KA)
0.180;-562.5
JJ(7A)
0.214;9.4
(7QKA)
0.161;-356.3
777A
0.121;-815.6
7A(7T)
0.153;-506.3
77(KA)
0.182;-196.9
7(8TA)
0.145;-1078.1
7Q(8A)
0.145;-871.9
(78)(TA)
0.207;-403.1
QA(78)
0.176;-871.9
789A
0.078;-1856.3
78JA
0.087;-1650.0
78KA
0.092;-1443.7
7J(9A)
0.142;-871.9
(79)(TA)
0.148;-300.0
QA(79)
0.151;-768.7
79TA
0.093;-1650.0
79QA
0.096;-1443.7
(7J)(TA)
0.223;-93.7
TA(7T)
0.208;-196.9
A(7TK)
0.192;-562.5
TA(7Q)
0.153;-665.6
7J(JA)
0.248;9.4
(7J)(QA)
0.172;112.5
JA(7Q)
0.190;-562.5
7Q(QA)
0.180;215.6
7QQA
0.134;-459.4
7KKA
0.210;-253.1
8(8JA)
0.194;-196.9
8K(8A)
0.185;9.4
(89KA)
0.188;-562.5
9J(8A)
0.170;-768.7
(8TJA)
0.144;-665.6
(TJ)(8A)
0.219;9.4
J(8JA)
0.234;112.5
JQ(8A)
0.214;-459.4
Q(8KA)
0.201;-253.1
889A
0.101;-1078.1
8A(8Q)
0.209;-93.7
(8T)(9A)
0.169;-196.9
8(9KA)
0.191;-562.5
A(89J)
0.128;-768.7
899A
0.153;-975.0
89JA
0.118;-1443.7
89KA
0.110;-1237.5
8Q(TA)
0.177;-562.5
(8T)(QA)
0.196;112.5
TA(8J)
0.175;-665.6
TA(8K)
0.149;-459.4
8(JKA)
0.193;-356.3
A(8JK)
0.174;-356.3
JA(8K)
0.196;-356.3
QA(8Q)
0.251;318.7
8QKA
0.131;-928.1
9T(9A)
0.212;-93.7
(9K)(9A)
0.276;890.6
K(9TA)
0.237;-356.3
T(9KA)
0.171;-356.3
JJ(9A)
0.186;215.6
(9QKA)
0.208;-150.0
999A
0.236;-196.9
9A(9Q)
0.209;112.5
(9J)(TA)
0.240;112.5
TA(9T)
0.198;9.4
A(9TK)
0.191;-356.3
TA(9Q)
0.206;-459.4
9J(JA)
0.213;215.6
(9J)(QA)
0.243;318.7
JA(9Q)
0.196;-356.3
9Q(QA)
0.238;421.9
9QQA
0.213;-253.1
9KKA
0.246;-46.9
T(TKA)
0.206;421.9
JJ(TA)
0.260;318.7
(TQKA)
0.170;-46.9
TTTA
0.187;112.5
TA(TK)
0.240;421.9
(TK)(JA)
0.246;525.0
KA(TJ)
0.204;-150.0
TA(JK)
0.210;-150.0
(TQ)(KA)
0.217;628.1
(TK)(KA)
0.324;1406.2
J(JKA)
0.258;628.1
(QK)(JA)
0.211;731.3
JJ(KA)
0.293;628.1
QA(JQ)
0.249;628.1
JQKA
0.167;-618.7
QK(QA)
0.264;834.4
QK(KA)
0.250;937.5
22(24)
0.034;-2718.8
22(28)
0.060;-2306.3
22(2Q)
0.071;-1893.8
24(23)
0.020;-3290.6
(23)(27)
0.069;-2306.3
2(23T)
0.044;-2671.9
2Q(23)
0.053;-2465.6
23(25)
0.026;-3187.5
2237
0.014;-3656.3
22(3T)
0.036;-2671.9
23(2K)
0.063;-2362.5
2(246)
0.031;-2981.3
28(24)
0.039;-2775.0
(24)(2J)
0.101;-1790.6
2244
0.025;-3187.5
22(47)
0.042;-2878.1
24(2T)
0.048;-2568.8
224Q
0.029;-3037.5
26(25)
0.039;-2878.1
(25)(29)
0.091;-1893.8
2(25Q)
0.065;-2259.4
22(56)
0.045;-2878.1
25(29)
0.041;-2568.8
225J
0.031;-3037.5
26(26)
0.072;-2100.0
(26)(29)
0.076;-1790.6
2(26Q)
0.081;-2156.3
22(67)
0.050;-2671.9
26(2T)
0.063;-2362.5
226Q
0.043;-2831.3
28(27)
0.049;-2465.6
(27)(2J)
0.081;-1481.3
2277
0.052;-2568.8
22(7T)
0.067;-2259.4
27(2K)
0.071;-1950.0
2(28T)
0.081;-2156.3
2Q(28)
0.100;-1950.0
28(2T)
0.070;-2156.3
228Q
0.046;-2625.0
2T(29)
0.062;-2053.1
(29)(2K)
0.143;-1068.8
229J
0.047;-2625.0
2T(2T)
0.146;-1275.0
(2T)(2K)
0.140;-965.6
22TQ
0.057;-2418.8
2Q(2J)
0.114;-1640.6
2J(2K)
0.115;-1537.5
22QQ
0.120;-1537.5
3(234)
0.028;-3187.5
36(23)
0.037;-2981.3
(23)(39)
0.098;-1996.9
3(23Q)
0.055;-2362.5
5(234)
0.013;-3656.3
9(234)
0.021;-3243.8
K(234)
0.042;-2831.3
4(237)
0.019;-3450.0
49(23)
0.023;-3243.8
(23)(4Q)
0.046;-2259.4
(2357)
0.020;-3346.9
(235J)
0.037;-2934.4
(23)(56)
0.034;-2775.0
5(239)
0.034;-3140.6
5J(23)
0.031;-2934.4
(2367)
0.024;-3243.8
(236J)
0.032;-2831.3
(23)(67)
0.049;-2568.8
6(23T)
0.045;-2934.4
6Q(23)
0.047;-2728.1
9(237)
0.040;-2934.4
K(237)
0.045;-2521.9
7(23T)
0.029;-2831.3
7Q(23)
0.046;-2625.0
T(238)
0.039;-2728.1
8(239)
0.044;-2831.3
8J(23)
0.055;-2625.0
(239T)
0.041;-2625.0
99(23)
0.087;-2053.1
(23)(9Q)
0.111;-1743.8
(23TQ)
0.050;-2315.6
T(23Q)
0.051;-2315.6
Q(23J)
0.058;-2212.5
(23)(JK)
0.104;-1434.4
QK(23)
0.058;-2006.3
23(35)
0.035;-3084.4
33(28)
0.040;-2775.0
233T
0.022;-3243.8
23(3K)
0.074;-2259.4
(24)(36)
0.036;-2878.1
3(249)
0.020;-3243.8
3J(24)
0.031;-3037.5
(34)(25)
0.037;-2981.3
27(34)
0.019;-3450.0
2(34T)
0.024;-3140.6
(34)(2K)
0.069;-2156.3
34(26)
0.018;-3553.1
34(28)
0.022;-3346.9
34(2T)
0.028;-3140.6
34(2Q)
0.039;-2934.4
(25)(35)
0.077;-2203.1
3(258)
0.032;-3243.8
3T(25)
0.027;-3037.5
(25)(3K)
0.067;-2053.1
27(35)
0.026;-3346.9
2(35T)
0.033;-3037.5
(35)(2K)
0.071;-2053.1
35(27)
0.024;-3346.9
35(29)
0.032;-3140.6
35(2J)
0.030;-2934.4
35(2K)
0.047;-2728.1
37(26)
0.022;-3243.8
(26)(3T)
0.066;-2259.4
3(26K)
0.046;-2625.0
2(368)
0.028;-3140.6
(36)(2J)
0.058;-2156.3
2K(36)
0.041;-2625.0
23(68)
0.024;-3140.6
23(6T)
0.044;-2934.4
23(6Q)
0.039;-2728.1
3(278)
0.034;-3037.5
3T(27)
0.031;-2831.3
(27)(3K)
0.102;-1846.9
29(37)
0.037;-2934.4
2(37Q)
0.050;-2625.0
23(78)
0.036;-3037.5
23(7T)
0.044;-2831.3
23(7Q)
0.048;-2625.0
3(289)
0.040;-2831.3
3J(28)
0.051;-2625.0
(38)(29)
0.061;-2156.3
2J(38)
0.034;-2625.0
38(29)
0.041;-2831.3
38(2J)
0.046;-2625.0
38(2K)
0.056;-2418.8
3T(29)
0.044;-2625.0
(29)(3K)
0.082;-1640.6
2J(39)
0.060;-2521.9
39(2T)
0.040;-2625.0
39(2Q)
0.066;-2418.8
(2T)(3T)
0.137;-1171.9
3(2TK)
0.056;-2212.5
2(3TQ)
0.068;-2315.6
23(TJ)
0.063;-2418.8
23(TK)
0.069;-2212.5
(2J)(3K)
0.093;-1434.4
2K(3J)
0.073;-2109.4
23(JK)
0.079;-2109.4
(3Q)(2K)
0.102;-1331.3
(2K)(3K)
0.168;-553.1
4(246)
0.031;-2775.0
48(24)
0.053;-2568.8
(24)(4J)
0.095;-1584.4
5(245)
0.042;-2775.0
9(245)
0.039;-3037.5
K(245)
0.058;-2625.0
5(248)
0.023;-3140.6
5T(24)
0.037;-2934.4
(24)(5K)
0.100;-1950.0
9(246)
0.034;-2934.4
K(246)
0.061;-2521.9
6(249)
0.035;-2934.4
6J(24)
0.050;-2728.1
(2478)
0.034;-2934.4
(247Q)
0.056;-2521.9
7(249)
0.041;-2831.3
7J(24)
0.049;-2625.0
(2489)
0.034;-2728.1
(248K)
0.057;-2315.6
8T(24)
0.041;-2625.0
(24)(8K)
0.074;-1640.6
Q(249)
0.069;-2315.6
(24)(9J)
0.093;-1743.8
T(24T)
0.101;-1743.8
T(24J)
0.060;-2315.6
TK(24)
0.068;-2109.4
(24)(JQ)
0.118;-1434.4
QQ(24)
0.101;-1331.3
24(45)
0.038;-2878.1
44(28)
0.045;-2568.8
244T
0.033;-3037.5
24(4K)
0.080;-2053.1
(25)(47)
0.058;-2568.8
4(25T)
0.026;-2934.4
4Q(25)
0.038;-2728.1
(45)(27)
0.045;-2568.8
29(45)
0.032;-3037.5
2(45Q)
0.041;-2728.1
24(56)
0.023;-3346.9
24(58)
0.030;-3140.6
24(5T)
0.035;-2934.4
24(5Q)
0.045;-2728.1
4(267)
0.024;-3140.6
49(26)
0.041;-2934.4
(26)(4Q)
0.075;-1950.0
27(46)
0.030;-3140.6
2(46T)
0.044;-2831.3
(46)(2K)
0.071;-1846.9
46(28)
0.031;-3037.5
46(2T)
0.038;-2831.3
46(2Q)
0.046;-2625.0
(27)(47)
0.087;-1687.5
4(27T)
0.039;-2728.1
4Q(27)
0.055;-2521.9
(47)(29)
0.065;-2156.3
2J(47)
0.038;-2625.0
47(28)
0.032;-2934.4
47(2T)
0.047;-2728.1
47(2Q)
0.058;-2521.9
(28)(48)
0.123;-1481.3
4(28J)
0.050;-2521.9
4K(28)
0.058;-2315.6
(48)(2J)
0.085;-1846.9
2K(48)
0.056;-2315.6
24(8T)
0.044;-2625.0
24(8Q)
0.058;-2418.8
4(29T)
0.048;-2521.9
4Q(29)
0.064;-2315.6
(49)(2J)
0.101;-1743.8
2K(49)
0.057;-2212.5
24(9J)
0.053;-2418.8
24(9K)
0.079;-2212.5
(2T)(4Q)
0.107;-1537.5
2J(4T)
0.050;-2315.6
4T(2J)
0.051;-2315.6
4T(2K)
0.060;-2109.4
4Q(2J)
0.070;-2109.4
(4J)(2K)
0.125;-1331.3
4J(2K)
0.079;-2006.3
4K(2Q)
0.076;-1903.1
24(QK)
0.094;-1903.1
(25)(56)
0.097;-1893.8
5(259)
0.062;-2259.4
5J(25)
0.065;-2053.1
(2567)
0.034;-3037.5
(256J)
0.051;-2625.0
(25)(67)
0.046;-2362.5
6(25T)
0.031;-2728.1
6Q(25)
0.056;-2521.9
9(257)
0.050;-2728.1
K(257)
0.077;-2315.6
7(25T)
0.047;-2625.0
7Q(25)
0.045;-2418.8
T(258)
0.046;-2521.9
8(259)
0.044;-2625.0
8J(25)
0.068;-2418.8
(259T)
0.068;-2418.8
99(25)
0.080;-1846.9
(25)(9Q)
0.092;-1537.5
(25TQ)
0.077;-2109.4
T(25Q)
0.067;-2109.4
Q(25J)
0.071;-2006.3
(25)(JK)
0.114;-1228.1
QK(25)
0.083;-1800.0
25(57)
0.049;-2465.6
55(2T)
0.086;-2156.3
255Q
0.053;-2625.0
57(26)
0.025;-3037.5
(26)(5T)
0.063;-2053.1
5(26K)
0.062;-2418.8
2(568)
0.044;-2934.4
(56)(2J)
0.089;-1950.0
2K(56)
0.063;-2418.8
25(68)
0.047;-2934.4
25(6T)
0.054;-2728.1
25(6Q)
0.065;-2521.9
5(278)
0.036;-2831.3
5T(27)
0.053;-2625.0
(27)(5K)
0.076;-1640.6
29(57)
0.038;-2728.1
2(57Q)
0.055;-2418.8
25(78)
0.049;-2831.3
25(7T)
0.063;-2625.0
25(7Q)
0.062;-2418.8
5(289)
0.051;-2625.0
5J(28)
0.049;-2418.8
(58)(29)
0.075;-1950.0
2J(58)
0.059;-2418.8
58(29)
0.043;-2625.0
58(2J)
0.063;-2418.8
58(2K)
0.070;-2212.5
5T(29)
0.060;-2418.8
(29)(5K)
0.091;-1434.4
2J(59)
0.069;-2315.6
59(2T)
0.055;-2418.8
59(2Q)
0.058;-2212.5
(2T)(5T)
0.141;-965.6
5(2TK)
0.077;-2006.3
2(5TQ)
0.096;-2109.4
25(TJ)
0.062;-2212.5
25(TK)
0.090;-2006.3
(2J)(5K)
0.100;-1228.1
2K(5J)
0.097;-1903.1
25(JK)
0.086;-1903.1
(5Q)(2K)
0.138;-1125.0
(2K)(5K)
0.173;-346.9
6(268)
0.060;-2156.3
6T(26)
0.091;-1950.0
(26)(6K)
0.132;-965.6
T(267)
0.051;-2521.9
7(268)
0.049;-2728.1
7T(26)
0.050;-2521.9
(26)(7K)
0.136;-1537.5
J(268)
0.065;-2315.6
89(26)
0.048;-2521.9
(26)(8Q)
0.094;-1537.5
(269J)
0.079;-2212.5
(26)(9T)
0.086;-1640.6
9(26K)
0.085;-2006.3
(26TK)
0.091;-1903.1
TQ(26)
0.061;-2006.3
K(26J)
0.068;-1800.0
Q(26Q)
0.162;-1125.0
KK(26)
0.135;-918.8
66(29)
0.072;-2053.1
266J
0.054;-2521.9
67(27)
0.059;-2156.3
(27)(6T)
0.074;-1846.9
6(27K)
0.070;-2212.5
2(679)
0.058;-2625.0
(67)(2Q)
0.082;-1640.6
27(68)
0.049;-2728.1
27(6T)
0.052;-2521.9
27(6Q)
0.049;-2315.6
68(28)
0.087;-1950.0
(28)(6J)
0.096;-1640.6
28(68)
0.082;-1950.0
2(68J)
0.058;-2315.6
2688
0.053;-2625.0
268T
0.030;-3093.8
268Q
0.038;-2887.5
(29)(6T)
0.091;-1640.6
6(29K)
0.086;-2006.3
2(69J)
0.064;-2212.5
2699
0.054;-2418.8
269J
0.039;-2887.5
269K
0.035;-2681.3
6Q(2T)
0.075;-2006.3
(6T)(2Q)
0.085;-1331.3
2T(6J)
0.073;-2109.4
2T(6K)
0.074;-1903.1
6(2JK)
0.096;-1800.0
2(6JK)
0.063;-1800.0
2J(6K)
0.111;-1800.0
2Q(6Q)
0.139;-1125.0
26QK
0.059;-2371.9
78(27)
0.092;-1950.0
(27)(7J)
0.120;-965.6
8(278)
0.070;-1846.9
Q(278)
0.086;-2109.4
(27)(8T)
0.084;-1640.6
8(27K)
0.073;-2006.3
(279Q)
0.084;-2006.3
9(27J)
0.077;-2109.4
9K(27)
0.065;-1903.1
TT(27)
0.093;-1434.4
(27)(TK)
0.122;-1125.0
J(27Q)
0.097;-1800.0
K(27Q)
0.120;-1593.8
77(28)
0.081;-1950.0
277T
0.051;-2418.8
27(7K)
0.109;-1434.4
(28)(7T)
0.095;-1640.6
7(28K)
0.087;-2006.3
2(78T)
0.055;-2315.6
(78)(2K)
0.114;-1331.3
78(2T)
0.055;-2315.6
78(2Q)
0.084;-2109.4
(29)(79)
0.129;-965.6
7(29Q)
0.077;-2006.3
2(79T)
0.051;-2212.5
(79)(2K)
0.153;-1228.1
79(2J)
0.072;-2109.4
79(2K)
0.062;-1903.1
7J(2T)
0.076;-2006.3
(7T)(2J)
0.107;-1331.3
2K(7T)
0.085;-1800.0
27(TQ)
0.082;-1903.1
7(2JQ)
0.067;-1800.0
2(7JQ)
0.086;-1800.0
27(JQ)
0.089;-1800.0
7(2QK)
0.092;-1593.8
7Q(2K)
0.105;-1593.8
88(28)
0.153;-1068.8
(28)(8J)
0.153;-759.4
9(289)
0.099;-1537.5
K(289)
0.099;-1800.0
9(28Q)
0.063;-1903.1
J(28T)
0.085;-1903.1
TJ(28)
0.083;-1903.1
(28JQ)
0.090;-1696.9
J(28K)
0.078;-1593.8
(28)(QK)
0.161;-815.6
88(2T)
0.132;-1537.5
288Q
0.066;-2006.3
8T(29)
0.066;-2109.4
(29)(8K)
0.125;-1125.0
2J(89)
0.102;-2006.3
89(2T)
0.059;-2109.4
89(2Q)
0.079;-1903.1
(2T)(8T)
0.164;-656.3
8(2TK)
0.090;-1696.9
2(8TQ)
0.077;-1800.0
28(TJ)
0.068;-1903.1
28(TK)
0.101;-1696.9
(2J)(8K)
0.117;-918.8
2K(8J)
0.093;-1593.8
28(JK)
0.107;-1593.8
(8Q)(2K)
0.156;-815.6
(2K)(8K)
0.197;-37.5
9(29J)
0.120;-1228.1
9K(29)
0.099;-1021.9
TT(29)
0.118;-1228.1
(29)(TK)
0.137;-918.8
J(29Q)
0.106;-1593.8
K(29Q)
0.087;-1387.5
99(2T)
0.103;-1331.3
299Q
0.107;-1800.0
9J(2T)
0.077;-1800.0
(9T)(2J)
0.125;-1125.0
2K(9T)
0.108;-1593.8
29(TQ)
0.091;-1696.9
9(2JQ)
0.095;-1593.8
2(9JQ)
0.096;-1593.8
29(JQ)
0.088;-1593.8
9(2QK)
0.111;-1387.5
9Q(2K)
0.117;-1387.5
TT(2T)
0.156;-450.0
(2T)(TK)
0.194;-140.6
J(2TQ)
0.144;-1490.6
K(2TQ)
0.129;-1284.4
TT(2J)
0.124;-1021.9
2TTK
0.083;-1490.6
TK(2J)
0.108;-1387.5
2TJJ
0.100;-1593.8
2TJK
0.078;-2062.5
2(TQK)
0.104;-1284.4
TK(2K)
0.176;-506.3
(2J)(JK)
0.173;65.6
QK(2J)
0.094;-1181.3
2J(JK)
0.151;-609.4
(JQ)(2K)
0.167;-506.3
(2K)(JK)
0.235;271.9
K(2QK)
0.183;-300.0
2K(QK)
0.225;-300.0
3335
0.031;-2981.3
3339
0.066;-2568.8
333K
0.059;-2156.3
36(34)
0.042;-2775.0
(34)(39)
0.098;-1790.6
3(34Q)
0.062;-2156.3
33(45)
0.034;-2878.1
34(38)
0.050;-2568.8
334T
0.033;-3037.5
33(4K)
0.067;-2053.1
(35)(37)
0.081;-1893.8
3(35T)
0.057;-2259.4
3Q(35)
0.081;-2053.1
35(37)
0.059;-2568.8
3359
0.030;-3037.5
33(5Q)
0.072;-2053.1
(36)(37)
0.105;-1790.6
3(36T)
0.055;-2156.3
3Q(36)
0.070;-1950.0
36(38)
0.075;-2362.5
336T
0.031;-2831.3
33(6K)
0.077;-1846.9
(37)(39)
0.090;-1481.3
3(37Q)
0.090;-1846.9
33(78)
0.055;-2259.4
37(3J)
0.089;-1950.0
337K
0.048;-2418.8
3T(38)
0.084;-1950.0
(38)(3K)
0.128;-965.6
338T
0.050;-2625.0
33(8K)
0.095;-1640.6
(39)(3J)
0.147;-1068.8
3399
0.087;-1950.0
33(9Q)
0.104;-1640.6
(3T)(3J)
0.148;-965.6
33TT
0.098;-1743.8
33(TK)
0.095;-1434.4
(3J)(3K)
0.215;-656.3
33JK
0.086;-2006.3
33(QK)
0.111;-1228.1
45(34)
0.043;-2775.0
(34)(48)
0.078;-1790.6
4(34J)
0.057;-2156.3
4K(34)
0.072;-1950.0
(3459)
0.034;-2934.4
(345K)
0.039;-2521.9
57(34)
0.028;-3140.6
(34)(5T)
0.068;-2156.3
5(34K)
0.046;-2521.9
(3469)
0.040;-2831.3
(346K)
0.050;-2418.8
68(34)
0.029;-2934.4
(34)(6J)
0.087;-1950.0
7(347)
0.079;-2259.4
J(347)
0.066;-2521.9
78(34)
0.054;-2831.3
(34)(7J)
0.094;-1846.9
8(348)
0.063;-2053.1
Q(348)
0.067;-2315.6
(34)(8T)
0.107;-1846.9
8(34K)
0.060;-2212.5
(349Q)
0.071;-2212.5
9(34J)
0.083;-2315.6
9K(34)
0.070;-2109.4
TT(34)
0.090;-1640.6
(34)(TK)
0.129;-1331.3
J(34Q)
0.084;-2006.3
K(34Q)
0.077;-1800.0
44(35)
0.040;-2775.0
3447
0.024;-3243.8
34(4T)
0.069;-2259.4
44(3K)
0.071;-1950.0
4(357)
0.033;-3140.6
49(35)
0.046;-2934.4
(35)(4Q)
0.095;-1950.0
36(45)
0.026;-3243.8
3(459)
0.036;-2934.4
(45)(3Q)
0.075;-1950.0
35(46)
0.021;-3243.8
35(48)
0.033;-3037.5
35(4T)
0.029;-2831.3
35(4Q)
0.037;-2625.0
46(36)
0.044;-2465.6
(36)(49)
0.064;-2156.3
4(36Q)
0.045;-2521.9
3(467)
0.033;-3037.5
(46)(3T)
0.103;-2053.1
3Q(46)
0.043;-2521.9
3467
0.015;-3712.5
3469
0.018;-3506.3
346J
0.026;-3300.0
346K
0.035;-3093.8
49(37)
0.046;-2728.1
(37)(4Q)
0.105;-1743.8
38(47)
0.044;-2831.3
3(47J)
0.060;-2521.9
3477
0.029;-2934.4
3479
0.022;-3403.1
347J
0.024;-3196.9
347K
0.036;-2990.6
4T(38)
0.072;-2521.9
(38)(4K)
0.093;-1537.5
3T(48)
0.042;-2521.9
3(48K)
0.081;-2212.5
38(4T)
0.063;-2521.9
38(4Q)
0.053;-2315.6
49(39)
0.094;-1846.9
(39)(4Q)
0.081;-1537.5
3T(49)
0.056;-2418.8
3(49K)
0.081;-2109.4
39(4J)
0.055;-2315.6
39(4K)
0.068;-2109.4
4(3TQ)
0.082;-2109.4
3(4TJ)
0.054;-2212.5
34TT
0.064;-2315.6
34TQ
0.044;-2784.4
(3J)(4Q)
0.133;-1331.3
3Q(4J)
0.085;-2006.3
34JQ
0.044;-2681.3
(3Q)(4K)
0.155;-1125.0
3Q(4K)
0.100;-1800.0
5(356)
0.050;-2465.6
58(35)
0.071;-2259.4
(35)(5J)
0.142;-1275.0
6(356)
0.063;-2362.5
T(356)
0.050;-2625.0
6(357)
0.037;-2934.4
69(35)
0.035;-2728.1
(35)(6Q)
0.071;-1743.8
(3579)
0.041;-2625.0
(357K)
0.064;-2212.5
79(35)
0.047;-2625.0
(35)(7Q)
0.079;-1640.6
(358T)
0.049;-2418.8
88(35)
0.072;-1950.0
(35)(8J)
0.112;-1640.6
9(359)
0.082;-1743.8
K(359)
0.062;-2006.3
9(35Q)
0.051;-2109.4
J(35T)
0.071;-2109.4
TJ(35)
0.060;-2109.4
(35JQ)
0.093;-1903.1
J(35K)
0.085;-1800.0
(35)(QK)
0.144;-1021.9
55(37)
0.080;-2362.5
3559
0.043;-2831.3
35(5Q)
0.081;-1846.9
(36)(57)
0.050;-2259.4
5(36T)
0.048;-2625.0
5Q(36)
0.058;-2418.8
(56)(38)
0.059;-2156.3
3T(56)
0.035;-2625.0
3(56K)
0.068;-2315.6
36(58)
0.042;-2831.3
36(5T)
0.041;-2625.0
36(5Q)
0.060;-2418.8
57(37)
0.058;-2156.3
(37)(5T)
0.087;-1846.9
5(37K)
0.072;-2212.5
3(579)
0.049;-2625.0
(57)(3Q)
0.097;-1640.6
37(58)
0.034;-2728.1
37(5T)
0.064;-2521.9
37(5Q)
0.076;-2315.6
58(38)
0.085;-1950.0
(38)(5J)
0.109;-1640.6
38(58)
0.095;-1950.0
3(58J)
0.063;-2315.6
3588
0.051;-2625.0
358T
0.029;-3093.8
358Q
0.044;-2887.5
(39)(5T)
0.102;-1640.6
5(39K)
0.080;-2006.3
3(59J)
0.056;-2212.5
3599
0.053;-2418.8
359J
0.042;-2887.5
359K
0.051;-2681.3
5Q(3T)
0.070;-2006.3
(5T)(3Q)
0.135;-1331.3
3T(5J)
0.073;-2109.4
3T(5K)
0.080;-1903.1
5(3JK)
0.089;-1800.0
3(5JK)
0.076;-1800.0
3J(5K)
0.101;-1800.0
3Q(5Q)
0.143;-1125.0
35QK
0.068;-2371.9
67(36)
0.070;-2156.3
(36)(6T)
0.116;-1171.9
6(36K)
0.103;-1537.5
(367T)
0.059;-2418.8
77(36)
0.088;-2053.1
(36)(7T)
0.073;-1743.8
7(36K)
0.081;-2109.4
(368J)
0.082;-2212.5
(36)(89)
0.098;-1743.8
8(36Q)
0.076;-2109.4
T(369)
0.063;-2212.5
9(36T)
0.051;-2212.5
9Q(36)
0.060;-2006.3
Q(36T)
0.076;-1903.1
(36)(TQ)
0.121;-1228.1
(36JK)
0.095;-1696.9
JK(36)
0.069;-1696.9
K(36K)
0.133;-815.6
3668
0.042;-2728.1
36(6J)
0.075;-1743.8
(37)(67)
0.099;-1378.1
6(37T)
0.058;-2418.8
6Q(37)
0.084;-2212.5
(67)(39)
0.073;-1846.9
3J(67)
0.072;-2315.6
67(38)
0.061;-2625.0
67(3T)
0.050;-2418.8
67(3Q)
0.083;-2212.5
(38)(68)
0.114;-1171.9
6(38J)
0.059;-2212.5
6K(38)
0.088;-2006.3
(68)(3J)
0.094;-1537.5
3K(68)
0.061;-2006.3
36(8T)
0.054;-2315.6
36(8Q)
0.058;-2109.4
6(39T)
0.084;-2212.5
6Q(39)
0.070;-2006.3
(69)(3J)
0.116;-1434.4
3K(69)
0.111;-1903.1
36(9J)
0.090;-2109.4
36(9K)
0.086;-1903.1
(3T)(6Q)
0.115;-1228.1
3J(6T)
0.095;-2006.3
6T(3J)
0.067;-2006.3
6T(3K)
0.115;-1800.0
6Q(3J)
0.100;-1800.0
(6J)(3K)
0.160;-1021.9
6J(3K)
0.111;-1696.9
6K(3Q)
0.098;-1593.8
36(QK)
0.102;-1593.8
(37)(78)
0.148;-1171.9
7(37J)
0.091;-1537.5
7K(37)
0.122;-1331.3
(378Q)
0.062;-2006.3
8(37T)
0.062;-2212.5
8Q(37)
0.093;-2006.3
J(379)
0.090;-2006.3
9T(37)
0.071;-2109.4
(37)(9K)
0.113;-1125.0
K(37T)
0.081;-1696.9
T(37K)
0.089;-1696.9
JJ(37)
0.130;-1125.0
(37QK)
0.113;-1490.6
3777
0.072;-1950.0
37(7T)
0.109;-1640.6
77(3K)
0.092;-1331.3
7(38T)
0.070;-2212.5
7Q(38)
0.081;-2006.3
(78)(3T)
0.112;-1537.5
3Q(78)
0.067;-2006.3
3789
0.036;-2990.6
378J
0.043;-2784.4
378K
0.044;-2578.1
7J(39)
0.091;-2006.3
(79)(3T)
0.129;-1434.4
3Q(79)
0.091;-1903.1
379T
0.049;-2784.4
379Q
0.047;-2578.1
(3T)(7J)
0.116;-1228.1
3T(7T)
0.091;-1331.3
3(7TK)
0.089;-1696.9
3T(7Q)
0.096;-1800.0
7J(3J)
0.144;-1125.0
(7J)(3Q)
0.155;-1021.9
3J(7Q)
0.070;-1696.9
7Q(3Q)
0.117;-918.8
37QQ
0.124;-1593.8
37KK
0.106;-1387.5
8(38J)
0.102;-1331.3
8K(38)
0.112;-1125.0
(389K)
0.077;-1696.9
9J(38)
0.085;-1903.1
(38TJ)
0.083;-1800.0
(38)(TJ)
0.137;-1125.0
J(38J)
0.146;-1021.9
JQ(38)
0.110;-1593.8
Q(38K)
0.106;-1387.5
3889
0.080;-2212.5
38(8Q)
0.112;-1228.1
(39)(8T)
0.102;-1331.3
8(39K)
0.084;-1696.9
3(89J)
0.073;-1903.1
3899
0.067;-2109.4
389J
0.041;-2578.1
389K
0.069;-2371.9
8Q(3T)
0.113;-1696.9
(8T)(3Q)
0.137;-1021.9
3T(8J)
0.093;-1800.0
3T(8K)
0.109;-1593.8
8(3JK)
0.122;-1490.6
3(8JK)
0.092;-1490.6
3J(8K)
0.117;-1490.6
3Q(8Q)
0.161;-815.6
38QK
0.067;-2062.5
9T(39)
0.107;-1228.1
(39)(9K)
0.238;-243.8
K(39T)
0.096;-1490.6
T(39K)
0.106;-1490.6
JJ(39)
0.131;-918.8
(39QK)
0.119;-1284.4
3999
0.119;-1331.3
39(9Q)
0.151;-1021.9
(3T)(9J)
0.114;-1021.9
3T(9T)
0.125;-1125.0
3(9TK)
0.079;-1490.6
3T(9Q)
0.113;-1593.8
9J(3J)
0.157;-918.8
(9J)(3Q)
0.149;-815.6
3J(9Q)
0.111;-1490.6
9Q(3Q)
0.152;-712.5
39QQ
0.105;-1387.5
39KK
0.105;-1181.3
T(3TK)
0.148;-712.5
JJ(3T)
0.165;-815.6
(3TQK)
0.123;-1181.3
3TTT
0.153;-1021.9
3T(TK)
0.144;-712.5
(3J)(TK)
0.162;-609.4
3K(TJ)
0.101;-1284.4
3T(JK)
0.125;-1284.4
(TQ)(3K)
0.184;-506.3
(3K)(TK)
0.279;271.9
J(3JK)
0.164;-506.3
(3J)(QK)
0.170;-403.1
JJ(3K)
0.153;-506.3
3Q(JQ)
0.138;-506.3
3JQK
0.100;-1753.1
QK(3Q)
0.168;-300.0
QK(3K)
0.173;-196.9
44(46)
0.071;-1893.8
44(4T)
0.106;-1481.3
(45)(45)
0.119;-1218.8
4(458)
0.066;-2259.4
4T(45)
0.081;-2053.1
(45)(4K)
0.113;-1068.8
4457
0.036;-3037.5
44(5T)
0.057;-2053.1
45(4K)
0.088;-1743.8
4(468)
0.079;-2156.3
4T(46)
0.064;-1950.0
(46)(4K)
0.134;-965.6
4468
0.040;-2831.3
44(6J)
0.080;-1846.9
(47)(47)
0.176;-806.3
4(47T)
0.093;-1846.9
4Q(47)
0.088;-1640.6
47(49)
0.061;-1950.0
447J
0.052;-2418.8
48(48)
0.099;-1275.0
(48)(4J)
0.153;-965.6
4488
0.098;-1950.0
44(8J)
0.096;-1640.6
(49)(49)
0.159;-393.8
4(49Q)
0.116;-1434.4
44(9T)
0.090;-1640.6
49(4K)
0.103;-1331.3
4(4TQ)
0.096;-1331.3
44(TJ)
0.098;-1434.4
(4J)(4J)
0.178;18.7
44JJ
0.113;-1331.3
4Q(4Q)
0.225;-450.0
(4K)(4K)
0.238;431.2
(45)(57)
0.105;-1584.4
5(45T)
0.076;-1950.0
5Q(45)
0.081;-1743.8
8(456)
0.054;-2728.1
Q(456)
0.051;-2315.6
(45)(68)
0.093;-2053.1
6(45J)
0.048;-2418.8
6K(45)
0.070;-2212.5
(457J)
0.050;-2315.6
(45)(78)
0.085;-1950.0
7(45J)
0.056;-2315.6
7K(45)
0.066;-2109.4
(458Q)
0.078;-2109.4
8(45T)
0.071;-2315.6
8Q(45)
0.059;-2109.4
J(459)
0.076;-2109.4
9T(45)
0.067;-2212.5
(45)(9K)
0.130;-1228.1
K(45T)
0.107;-1800.0
T(45K)
0.068;-1800.0
JJ(45)
0.133;-1228.1
(45QK)
0.131;-1593.8
4555
0.057;-2465.6
45(58)
0.077;-2156.3
55(4J)
0.095;-1846.9
455K
0.060;-2315.6
58(46)
0.047;-2728.1
(46)(5J)
0.085;-1743.8
46(56)
0.068;-2259.4
4(569)
0.053;-2625.0
(56)(4Q)
0.103;-1640.6
46(57)
0.043;-2831.3
46(59)
0.046;-2625.0
46(5J)
0.051;-2418.8
46(5K)
0.067;-2212.5
5(479)
0.067;-2521.9
5J(47)
0.057;-2315.6
(57)(48)
0.076;-1950.0
4T(57)
0.061;-2418.8
4(57K)
0.058;-2109.4
47(59)
0.044;-2521.9
47(5J)
0.056;-2315.6
47(5K)
0.073;-2109.4
5(48T)
0.064;-2315.6
5Q(48)
0.066;-2109.4
(58)(4T)
0.085;-1640.6
4Q(58)
0.066;-2109.4
4589
0.027;-3093.8
458J
0.039;-2887.5
458K
0.039;-2681.3
5J(49)
0.087;-2109.4
(59)(4T)
0.096;-1537.5
4Q(59)
0.071;-2006.3
459T
0.037;-2887.5
459Q
0.037;-2681.3
(4T)(5J)
0.142;-1331.3
4T(5T)
0.109;-1434.4
4(5TK)
0.065;-1800.0
4T(5Q)
0.097;-1903.1
5J(4J)
0.130;-1228.1
(5J)(4Q)
0.114;-1125.0
4J(5Q)
0.093;-1800.0
5Q(4Q)
0.128;-1021.9
45QQ
0.084;-1696.9
45KK
0.099;-1490.6
6(469)
0.085;-1846.9
6J(46)
0.132;-1640.6
(4678)
0.047;-2521.9
(467Q)
0.066;-2109.4
7(469)
0.067;-2418.8
7J(46)
0.076;-2212.5
(4689)
0.067;-2315.6
(468K)
0.083;-1903.1
8T(46)
0.082;-2212.5
(46)(8K)
0.131;-1228.1
Q(469)
0.076;-1903.1
(46)(9J)
0.110;-1331.3
T(46T)
0.092;-1331.3
T(46J)
0.082;-1903.1
TK(46)
0.105;-1696.9
(46)(JQ)
0.108;-1021.9
QQ(46)
0.138;-918.8
46(67)
0.074;-2053.1
66(4T)
0.109;-1743.8
466Q
0.058;-2212.5
68(47)
0.052;-2521.9
(47)(6J)
0.113;-1537.5
47(67)
0.094;-1950.0
4(67T)
0.055;-2315.6
(67)(4K)
0.140;-1331.3
67(49)
0.062;-2418.8
67(4J)
0.055;-2212.5
67(4K)
0.068;-2006.3
69(48)
0.060;-2315.6
(48)(6Q)
0.118;-1331.3
49(68)
0.061;-2315.6
4(68Q)
0.068;-2006.3
46(89)
0.061;-2315.6
46(8J)
0.093;-2109.4
46(8K)
0.083;-1903.1
(49)(6J)
0.120;-1331.3
49(69)
0.108;-1537.5
4(69Q)
0.094;-1903.1
46(9T)
0.069;-2109.4
46(9Q)
0.067;-1903.1
6(4TJ)
0.096;-1903.1
6K(4T)
0.107;-1696.9
(6T)(4K)
0.162;-1021.9
6T(4Q)
0.095;-1800.0
(4J)(6J)
0.194;-450.0
4J(6J)
0.121;-1125.0
6J(4Q)
0.077;-1696.9
(4Q)(6Q)
0.203;-243.8
4K(6Q)
0.108;-1490.6
4K(6K)
0.163;-712.5
79(47)
0.088;-1640.6
(47)(7Q)
0.147;-656.3
(478T)
0.083;-2109.4
88(47)
0.102;-1640.6
(47)(8J)
0.110;-1331.3
9(479)
0.113;-1434.4
K(479)
0.102;-1696.9
9(47Q)
0.084;-1800.0
J(47T)
0.077;-1800.0
TJ(47)
0.085;-1800.0
(47JQ)
0.108;-1593.8
J(47K)
0.113;-1490.6
(47)(QK)
0.152;-712.5
77(49)
0.105;-1640.6
477J
0.079;-2109.4
78(48)
0.110;-1640.6
(48)(7J)
0.092;-1331.3
48(78)
0.096;-1640.6
4(78J)
0.082;-2006.3
4788
0.068;-2315.6
478T
0.052;-2784.4
478Q
0.057;-2578.1
(49)(7T)
0.143;-1331.3
7(49K)
0.085;-1696.9
4(79J)
0.107;-1903.1
4799
0.065;-2109.4
479J
0.059;-2578.1
479K
0.048;-2371.9
7Q(4T)
0.104;-1696.9
(7T)(4Q)
0.143;-1021.9
4T(7J)
0.068;-1800.0
4T(7K)
0.107;-1593.8
7(4JK)
0.120;-1490.6
4(7JK)
0.113;-1490.6
4J(7K)
0.117;-1490.6
4Q(7Q)
0.170;-815.6
47QK
0.079;-2062.5
89(48)
0.141;-1434.4
(48)(8Q)
0.177;-450.0
(489J)
0.092;-1800.0
(48)(9T)
0.108;-1228.1
9(48K)
0.088;-1593.8
(48TK)
0.094;-1490.6
TQ(48)
0.103;-1593.8
K(48J)
0.095;-1387.5
Q(48Q)
0.162;-712.5
KK(48)
0.161;-506.3
88(4J)
0.096;-1228.1
488K
0.087;-1696.9
8J(49)
0.076;-1800.0
(89)(4T)
0.094;-1228.1
4Q(89)
0.093;-1696.9
489T
0.044;-2578.1
489Q
0.065;-2371.9
(4T)(8J)
0.167;-1021.9
4T(8T)
0.097;-1125.0
4(8TK)
0.094;-1490.6
4T(8Q)
0.082;-1593.8
8J(4J)
0.121;-918.8
(8J)(4Q)
0.126;-815.6
4J(8Q)
0.111;-1490.6
8Q(4Q)
0.192;-712.5
48QQ
0.124;-1387.5
48KK
0.129;-1181.3
9(49Q)
0.189;-918.8
J(49T)
0.100;-1593.8
TJ(49)
0.086;-1593.8
(49JQ)
0.152;-1387.5
J(49K)
0.124;-1284.4
(49)(QK)
0.139;-506.3
99(4J)
0.141;-1021.9
499K
0.110;-1490.6
9Q(4T)
0.076;-1490.6
(9T)(4Q)
0.161;-815.6
4T(9J)
0.106;-1593.8
4T(9K)
0.111;-1387.5
9(4JK)
0.110;-1284.4
4(9JK)
0.127;-1284.4
4J(9K)
0.105;-1284.4
4Q(9Q)
0.156;-609.4
49QK
0.100;-1856.3
TJ(4T)
0.122;-815.6
(4TJQ)
0.129;-1284.4
J(4TK)
0.142;-1181.3
(4T)(QK)
0.182;-403.1
TT(4Q)
0.210;-712.5
T(4JQ)
0.105;-1284.4
4(TJQ)
0.114;-1284.4
4T(JQ)
0.106;-1284.4
T(4QK)
0.126;-1078.1
TQ(4K)
0.124;-1078.1
JJ(4J)
0.252;65.6
(4JQK)
0.162;-975.0
4JJJ
0.150;-609.4
JQ(4Q)
0.166;-403.1
4JQQ
0.114;-1078.1
4JKK
0.149;-871.9
QQ(4K)
0.207;-196.9
4KKK
0.232;9.4
55(59)
0.155;-1275.0
55(5K)
0.142;-862.5
(56)(58)
0.128;-1275.0
5(56J)
0.092;-1640.6
5K(56)
0.125;-1434.4
56(59)
0.095;-1846.9
556J
0.072;-2315.6
57(57)
0.111;-1275.0
(57)(5T)
0.159;-965.6
5(57K)
0.112;-1331.3
55(79)
0.076;-1743.8
57(5Q)
0.086;-1434.4
5(589)
0.073;-1640.6
5J(58)
0.110;-1434.4
58(59)
0.100;-1640.6
558J
0.060;-2109.4
59(59)
0.130;-862.5
(59)(5Q)
0.197;-553.1
559T
0.078;-2109.4
55(9K)
0.114;-1125.0
(5T)(5Q)
0.153;-450.0
55TJ
0.076;-1903.1
5J(5J)
0.145;-450.0
5J(5Q)
0.163;-1021.9
5(5QK)
0.177;-815.6
5K(5K)
0.236;-37.5
68(56)
0.079;-1846.9
(56)(6J)
0.172;-862.5
7(567)
0.085;-1846.9
J(567)
0.072;-2109.4
78(56)
0.065;-2418.8
(56)(7J)
0.127;-1434.4
8(568)
0.072;-1640.6
Q(568)
0.096;-1903.1
(56)(8T)
0.109;-1434.4
8(56K)
0.084;-1800.0
(569Q)
0.068;-1800.0
9(56J)
0.088;-1903.1
9K(56)
0.123;-1696.9
TT(56)
0.107;-1228.1
(56)(TK)
0.157;-918.8
J(56Q)
0.092;-1593.8
K(56Q)
0.124;-1387.5
66(57)
0.073;-1950.0
5669
0.058;-2418.8
56(6Q)
0.136;-1434.4
(57)(68)
0.095;-1743.8
6(57J)
0.069;-2109.4
6K(57)
0.084;-1903.1
(67)(5T)
0.091;-1537.5
5Q(67)
0.095;-2006.3
5678
0.023;-3093.8
567T
0.029;-2887.5
567Q
0.041;-2681.3
(58)(69)
0.107;-1537.5
6(58Q)
0.079;-1903.1
5(689)
0.075;-2212.5
(68)(5Q)
0.094;-1228.1
58(69)
0.078;-2212.5
58(6J)
0.067;-2006.3
58(6K)
0.094;-1800.0
6(59J)
0.080;-1903.1
6K(59)
0.070;-1696.9
(69)(5Q)
0.109;-1125.0
59(6T)
0.066;-2006.3
59(6Q)
0.073;-1800.0
6T(5T)
0.116;-1228.1
(5T)(6K)
0.150;-918.8
5Q(6T)
0.096;-1696.9
56TJ
0.060;-2475.0
56TK
0.079;-2268.8
6K(5J)
0.102;-1490.6
56JJ
0.112;-1696.9
56JK
0.073;-2165.6
5(6QK)
0.123;-1387.5
6K(5K)
0.175;-609.4
(57)(79)
0.140;-862.5
7(57Q)
0.100;-1228.1
9(578)
0.066;-2109.4
K(578)
0.108;-1696.9
8(57J)
0.074;-1903.1
8K(57)
0.110;-1696.9
(579K)
0.106;-1593.8
9J(57)
0.090;-1800.0
(57TJ)
0.101;-1696.9
(57)(TJ)
0.131;-1021.9
J(57J)
0.167;-918.8
JQ(57)
0.082;-1490.6
Q(57K)
0.124;-1284.4
5778
0.080;-2315.6
57(7J)
0.125;-1331.3
(58)(78)
0.132;-862.5
7(58J)
0.104;-1903.1
7K(58)
0.085;-1696.9
(78)(5J)
0.121;-1228.1
5K(78)
0.097;-1696.9
57(8T)
0.067;-2006.3
57(8Q)
0.091;-1800.0
7(59T)
0.089;-1903.1
7Q(59)
0.092;-1696.9
(79)(5J)
0.142;-1125.0
5K(79)
0.129;-1593.8
57(9J)
0.068;-1800.0
57(9K)
0.095;-1593.8
(5T)(7Q)
0.167;-918.8
5J(7T)
0.119;-1696.9
7T(5J)
0.105;-1696.9
7T(5K)
0.106;-1490.6
7Q(5J)
0.122;-1490.6
(7J)(5K)
0.129;-712.5
7J(5K)
0.127;-1387.5
7K(5Q)
0.127;-1284.4
57(QK)
0.093;-1284.4
(58)(89)
0.171;-656.3
8(58Q)
0.133;-1021.9
T(589)
0.095;-1800.0
9(58T)
0.088;-1800.0
9Q(58)
0.101;-1593.8
Q(58T)
0.108;-1490.6
(58)(TQ)
0.161;-815.6
(58JK)
0.130;-1284.4
JK(58)
0.139;-1284.4
K(58K)
0.150;-403.1
588T
0.083;-1903.1
58(8K)
0.147;-918.8
(59)(8J)
0.120;-1021.9
59(89)
0.124;-1228.1
5(89Q)
0.108;-1593.8
58(9T)
0.089;-1800.0
58(9Q)
0.089;-1593.8
8(5TJ)
0.113;-1593.8
8K(5T)
0.109;-1387.5
(8T)(5K)
0.181;-712.5
8T(5Q)
0.121;-1490.6
(5J)(8J)
0.208;-140.6
5J(8J)
0.148;-815.6
8J(5Q)
0.113;-1387.5
(5Q)(8Q)
0.195;65.6
5K(8Q)
0.120;-1181.3
5K(8K)
0.235;-403.1
9J(59)
0.132;-918.8
(59TJ)
0.119;-1490.6
(59)(TJ)
0.167;-815.6
J(59J)
0.141;-712.5
JQ(59)
0.121;-1284.4
Q(59K)
0.127;-1078.1
599T
0.095;-1696.9
59(9K)
0.182;-712.5
(5T)(9Q)
0.159;-712.5
5J(9T)
0.096;-1490.6
9T(5J)
0.103;-1490.6
9T(5K)
0.134;-1284.4
9Q(5J)
0.123;-1284.4
(9J)(5K)
0.139;-506.3
9J(5K)
0.132;-1181.3
9K(5Q)
0.138;-1078.1
59(QK)
0.152;-1078.1
(5T)(TJ)
0.188;-37.5
J(5TJ)
0.149;-609.4
JQ(5T)
0.119;-1181.3
Q(5TK)
0.150;-975.0
5TTJ
0.114;-1387.5
TJ(5J)
0.152;-609.4
(TJ)(5Q)
0.189;-506.3
5J(TQ)
0.115;-1181.3
TQ(5Q)
0.151;-403.1
5TQQ
0.131;-1078.1
5TKK
0.147;-871.9
Q(5JQ)
0.214;-300.0
KK(5J)
0.189;-93.7
(5Q)(JQ)
0.226;375.0
5K(JQ)
0.120;-871.9
5K(JK)
0.192;-93.7
5QQQ
0.174;-196.9
KK(5K)
0.289;787.5
6669
0.113;-1640.6
666K
0.131;-1228.1
69(67)
0.075;-1537.5
(67)(6Q)
0.139;-553.1
6678
0.058;-2315.6
66(7J)
0.107;-1331.3
(68)(68)
0.169;-187.5
6(68J)
0.091;-1228.1
6K(68)
0.100;-1021.9
68(6J)
0.118;-1228.1
668K
0.076;-1696.9
6J(69)
0.121;-1125.0
69(6T)
0.100;-1228.1
669Q
0.080;-1696.9
6J(6T)
0.133;-1021.9
6T(6J)
0.150;-1021.9
66TK
0.119;-1490.6
6K(6J)
0.143;-712.5
(6Q)(6Q)
0.245;637.5
66QK
0.108;-1284.4
7(679)
0.120;-1434.4
7J(67)
0.116;-1228.1
(6789)
0.078;-2006.3
(678K)
0.110;-1593.8
8T(67)
0.073;-1903.1
(67)(8K)
0.161;-918.8
Q(679)
0.102;-1593.8
(67)(9J)
0.147;-1021.9
T(67T)
0.141;-1021.9
T(67J)
0.098;-1593.8
TK(67)
0.129;-1387.5
(67)(JQ)
0.158;-712.5
QQ(67)
0.211;-609.4
67(78)
0.091;-1537.5
77(6J)
0.115;-1228.1
677K
0.092;-1696.9
7T(68)
0.098;-1903.1
(68)(7K)
0.155;-918.8
6T(78)
0.069;-1903.1
6(78K)
0.095;-1593.8
68(7T)
0.089;-1903.1
68(7Q)
0.099;-1696.9
79(69)
0.115;-1228.1
(69)(7Q)
0.129;-918.8
6T(79)
0.078;-1800.0
6(79K)
0.115;-1490.6
69(7J)
0.079;-1696.9
69(7K)
0.114;-1490.6
7(6TQ)
0.118;-1490.6
6(7TJ)
0.107;-1593.8
67TT
0.097;-1696.9
67TQ
0.078;-2165.6
(6J)(7Q)
0.161;-712.5
6Q(7J)
0.123;-1387.5
67JQ
0.063;-2062.5
(6Q)(7K)
0.183;-506.3
6Q(7K)
0.139;-1181.3
8(689)
0.130;-1228.1
8J(68)
0.123;-1021.9
(689T)
0.083;-1696.9
99(68)
0.119;-1125.0
(68)(9Q)
0.142;-815.6
(68TQ)
0.115;-1387.5
T(68Q)
0.102;-1387.5
Q(68J)
0.120;-1284.4
(68)(JK)
0.165;-506.3
QK(68)
0.122;-1078.1
68(8T)
0.121;-1125.0
88(6K)
0.129;-815.6
8(69J)
0.089;-1593.8
8K(69)
0.100;-1387.5
(89)(6Q)
0.133;-815.6
69(8T)
0.094;-1696.9
69(8Q)
0.110;-1490.6
8T(6T)
0.175;-918.8
(6T)(8K)
0.127;-609.4
6Q(8T)
0.111;-1387.5
68TJ
0.082;-2165.6
68TK
0.066;-1959.4
8K(6J)
0.127;-1181.3
68JJ
0.109;-1387.5
68JK
0.094;-1856.3
6(8QK)
0.115;-1078.1
8K(6K)
0.178;-300.0
(69)(9J)
0.174;-140.6
T(69T)
0.130;-815.6
T(69J)
0.097;-1387.5
TK(69)
0.134;-1181.3
(69)(JQ)
0.187;-506.3
QQ(69)
0.212;-403.1
69(9T)
0.130;-918.8
99(6K)
0.133;-609.4
9(6TQ)
0.115;-1284.4
6(9TJ)
0.111;-1387.5
69TT
0.117;-1490.6
69TQ
0.078;-1959.4
(6J)(9Q)
0.190;-506.3
6Q(9J)
0.111;-1181.3
69JQ
0.073;-1856.3
(6Q)(9K)
0.204;-300.0
6Q(9K)
0.150;-975.0
T(6TJ)
0.147;-609.4
TK(6T)
0.209;-403.1
(6T)(JQ)
0.166;-403.1
QQ(6T)
0.177;-300.0
6T(TJ)
0.192;-609.4
(6J)(TJ)
0.209;168.7
6J(TJ)
0.161;-506.3
TJ(6Q)
0.108;-1078.1
(6Q)(TQ)
0.227;375.0
6K(TQ)
0.130;-871.9
6K(TK)
0.232;-93.7
JK(6J)
0.241;-196.9
K(6JK)
0.181;9.4
6JJK
0.156;-871.9
6(JQK)
0.121;-768.7
JK(6K)
0.222;9.4
KK(6Q)
0.204;112.5
6QKK
0.159;-562.5
77(7T)
0.166;-553.1
(78)(78)
0.214;18.7
7(78J)
0.113;-1021.9
7K(78)
0.173;-815.6
78(7J)
0.166;-1021.9
778K
0.096;-1490.6
7J(79)
0.140;-918.8
79(7T)
0.131;-1021.9
779Q
0.095;-1490.6
7J(7T)
0.160;-815.6
7T(7J)
0.137;-815.6
77TK
0.124;-1284.4
7K(7J)
0.158;-506.3
(7Q)(7Q)
0.253;843.8
77QK
0.107;-1078.1
8(78T)
0.142;-1021.9
8Q(78)
0.157;-815.6
J(789)
0.110;-1490.6
9T(78)
0.127;-1593.8
(78)(9K)
0.185;-609.4
K(78T)
0.120;-1181.3
T(78K)
0.098;-1181.3
JJ(78)
0.147;-609.4
(78QK)
0.146;-975.0
7888
0.101;-1228.1
78(8J)
0.142;-918.8
(79)(89)
0.214;-346.9
8(79Q)
0.101;-1387.5
7(89T)
0.086;-1593.8
(89)(7K)
0.160;-609.4
89(7J)
0.117;-1490.6
89(7K)
0.123;-1284.4
8J(7T)
0.129;-1387.5
(8T)(7J)
0.155;-712.5
7K(8T)
0.136;-1181.3
78(TQ)
0.103;-1284.4
8(7JQ)
0.115;-1181.3
7(8JQ)
0.127;-1181.3
78(JQ)
0.110;-1181.3
8(7QK)
0.159;-975.0
8Q(7K)
0.167;-975.0
99(79)
0.174;-243.8
(79)(9Q)
0.200;65.6
(79TQ)
0.121;-1181.3
T(79Q)
0.116;-1181.3
Q(79J)
0.154;-1078.1
(79)(JK)
0.192;-300.0
QK(79)
0.153;-871.9
79(9J)
0.169;-712.5
(7T)(9T)
0.231;-37.5
9(7TK)
0.126;-1078.1
7(9TQ)
0.126;-1181.3
79(TJ)
0.100;-1284.4
79(TK)
0.165;-1078.1
(7J)(9K)
0.187;-300.0
7K(9J)
0.143;-975.0
79(JK)
0.148;-975.0
(9Q)(7K)
0.210;-196.9
(7K)(9K)
0.282;581.2
T(7TQ)
0.197;-403.1
Q(7TJ)
0.105;-975.0
(7T)(JK)
0.183;-196.9
QK(7T)
0.137;-768.7
7T(TQ)
0.205;-403.1
(7J)(TQ)
0.165;-300.0
7Q(TJ)
0.140;-975.0
7TJQ
0.101;-1650.0
(7Q)(TK)
0.188;-93.7
7Q(TK)
0.151;-768.7
J(7JQ)
0.235;-196.9
K(7JQ)
0.176;-665.6
JJ(7Q)
0.210;-196.9
J(7QK)
0.136;-665.6
JQ(7K)
0.176;-665.6
QQ(7Q)
0.265;684.4
7Q(QK)
0.218;112.5
8888
0.170;-450.0
888Q
0.134;-712.5
8(89J)
0.145;-712.5
8K(89)
0.171;-506.3
89(8Q)
0.164;-609.4
8(8TJ)
0.160;-609.4
8K(8T)
0.200;-403.1
8T(8K)
0.166;-403.1
8(8JK)
0.207;-300.0
88(JK)
0.164;-300.0
8Q(8K)
0.185;-196.9
(89)(9T)
0.203;-37.5
9(89K)
0.181;-403.1
(89TK)
0.104;-975.0
TQ(89)
0.146;-1078.1
K(89J)
0.168;-871.9
Q(89Q)
0.169;-196.9
KK(89)
0.200;9.4
99(8Q)
0.177;-506.3
9(8TJ)
0.124;-1181.3
9K(8T)
0.145;-975.0
(9T)(8K)
0.172;-300.0
9T(8Q)
0.115;-1078.1
(8J)(9J)
0.195;271.9
8J(9J)
0.178;-403.1
9J(8Q)
0.138;-975.0
(8Q)(9Q)
0.193;478.1
8K(9Q)
0.174;-768.7
8K(9K)
0.203;9.4
TQ(8T)
0.178;-300.0
K(8TJ)
0.154;-768.7
Q(8TQ)
0.191;-93.7
KK(8T)
0.199;112.5
