AAAA
0.361;650.0
5AAA
0.320;-418.7
9AAA
0.314;-143.7
KAAA
0.387;131.3
4A(2A)
0.263;-1312.5
(2A)(7A)
0.274;-656.3
A(2TA)
0.285;-900.0
QA(2A)
0.276;-762.5
2A(4A)
0.183;-1312.5
26AA
0.160;-1625.0
AA(29)
0.240;-968.7
2A(QA)
0.263;-762.5
A(34A)
0.225;-1243.8
6A(3A)
0.234;-1106.2
(3A)(9A)
0.316;-450.0
A(3QA)
0.276;-693.8
AA(34)
0.203;-1243.8
3A(7A)
0.263;-1037.5
39AA
0.238;-1350.0
AA(3Q)
0.245;-693.8
(4A)(5A)
0.311;-656.3
A(48A)
0.281;-900.0
TA(4A)
0.233;-762.5
(4A)(KA)
0.342;-106.2
46AA
0.198;-1487.5
AA(49)
0.278;-831.2
4A(QA)
0.300;-625.0
A(56A)
0.273;-968.7
8A(5A)
0.249;-831.2
(5A)(JA)
0.322;-175.0
55AA
0.249;-1037.5
AA(58)
0.270;-831.2
5A(JA)
0.272;-625.0
5KAA
0.250;-937.5
8A(6A)
0.284;-762.5
(6A)(JA)
0.293;-106.2
66AA
0.234;-900.0
AA(69)
0.260;-693.8
6A(QA)
0.304;-487.5
A(78A)
0.273;-693.8
TA(7A)
0.215;-556.2
(7A)(KA)
0.277;100.0
79AA
0.251;-1075.0
AA(7Q)
0.283;-418.8
(8A)(9A)
0.264;-106.2
A(8QA)
0.320;-350.0
AA(89)
0.272;-556.2
8A(QA)
0.327;-350.0
A(9TA)
0.322;-418.8
QA(9A)
0.234;-281.3
9A(JA)
0.301;-350.0
9KAA
0.290;-662.5
QA(TA)
0.294;-212.5
TA(QA)
0.289;-212.5
A(JQA)
0.317;-143.8
AA(JQ)
0.280;-143.8
(QA)(KA)
0.372;443.7
KKAA
0.311;62.5
2(25A)
0.199;-2068.7
27(2A)
0.253;-1931.2
(2T)(2A)
0.256;-1275.0
2(2KA)
0.201;-1518.7
(236A)
0.156;-2381.2
(23TA)
0.229;-2106.2
33(2A)
0.208;-2137.5
(36)(2A)
0.176;-1931.2
3(29A)
0.193;-2175.0
3J(2A)
0.205;-2037.5
(245A)
0.178;-2381.2
(249A)
0.191;-2106.2
(24KA)
0.233;-1831.2
46(2A)
0.179;-2312.5
(49)(2A)
0.218;-1656.2
4(2QA)
0.214;-1900.0
6(25A)
0.193;-2243.8
T(25A)
0.228;-1968.7
5(26A)
0.229;-2243.8
58(2A)
0.197;-2106.2
(5J)(2A)
0.228;-1450.0
6(26A)
0.225;-1725.0
T(26A)
0.224;-1900.0
6(27A)
0.195;-2106.2
69(2A)
0.184;-1968.7
(6Q)(2A)
0.240;-1312.5
(279A)
0.221;-1900.0
(27KA)
0.233;-1625.0
79(2A)
0.183;-1900.0
(7Q)(2A)
0.258;-1243.8
(28TA)
0.182;-1762.5
88(2A)
0.174;-1450.0
(8J)(2A)
0.260;-1243.8
9(29A)
0.239;-1312.5
K(29A)
0.208;-1487.5
9(2QA)
0.203;-1556.2
J(2TA)
0.242;-1556.2
TJ(2A)
0.185;-1556.2
(2JQA)
0.256;-1418.7
J(2KA)
0.251;-1350.0
(QK)(2A)
0.320;-831.2
22(4A)
0.152;-2137.5
226A
0.164;-2450.0
2A(29)
0.238;-1793.7
22(QA)
0.262;-1587.5
2(34A)
0.163;-2518.8
26(3A)
0.159;-2381.2
(29)(3A)
0.158;-1725.0
2(3QA)
0.189;-1968.7
A(234)
0.204;-2518.8
(23)(7A)
0.176;-1862.5
9A(23)
0.143;-2175.0
A(23Q)
0.204;-1968.7
2A(34)
0.172;-2518.8
2A(36)
0.171;-2381.2
2A(38)
0.151;-2243.8
2A(3T)
0.164;-2106.2
2A(3Q)
0.200;-1968.7
2(45A)
0.152;-2381.2
27(4A)
0.169;-2243.8
(2T)(4A)
0.191;-1587.5
2(4KA)
0.174;-1831.2
A(246)
0.168;-2312.5
(24)(9A)
0.217;-1656.2
JA(24)
0.204;-1968.7
24(5A)
0.139;-2381.2
24(7A)
0.134;-2243.8
24(9A)
0.178;-2106.2
24(JA)
0.197;-1968.7
24(KA)
0.211;-1831.2
26(5A)
0.183;-2243.8
(29)(5A)
0.225;-1587.5
2(5QA)
0.215;-1831.2
A(256)
0.208;-2243.8
(25)(9A)
0.183;-1587.5
JA(25)
0.190;-1900.0
25(6A)
0.215;-2243.8
25(8A)
0.202;-2106.2
25(TA)
0.172;-1968.7
25(QA)
0.249;-1831.2
(26)(6A)
0.215;-1275.0
2(69A)
0.249;-1968.7
2J(6A)
0.192;-1831.2
(26)(7A)
0.186;-1656.2
9A(26)
0.148;-1968.7
A(26Q)
0.231;-1762.5
2A(67)
0.168;-2106.2
2A(69)
0.166;-1968.7
2A(6J)
0.193;-1831.2
2A(6K)
0.204;-1693.7
(29)(7A)
0.207;-1450.0
2(7QA)
0.237;-1693.7
A(278)
0.195;-1968.7
(27)(JA)
0.218;-1312.5
KA(27)
0.246;-1625.0
2A(79)
0.207;-1900.0
2A(7J)
0.264;-1762.5
2A(7K)
0.186;-1625.0
(2T)(8A)
0.188;-1312.5
2(8KA)
0.207;-1556.2
A(28T)
0.179;-1762.5
(28)(KA)
0.250;-1106.2
28(TA)
0.182;-1762.5
28(QA)
0.247;-1625.0
(29)(9A)
0.207;-862.5
2(9QA)
0.254;-1556.2
A(29T)
0.192;-1693.7
(29)(KA)
0.294;-1037.5
29(JA)
0.238;-1625.0
29(KA)
0.226;-1487.5
2J(TA)
0.180;-1556.2
(2T)(JA)
0.237;-1106.2
KA(2T)
0.253;-1418.7
2A(TQ)
0.205;-1487.5
2(JQA)
0.169;-1418.7
A(2JQ)
0.238;-1418.7
2A(JQ)
0.215;-1418.7
2(QKA)
0.243;-1281.2
2Q(KA)
0.218;-1281.2
33(3A)
0.220;-1618.7
(36)(3A)
0.237;-1412.5
3(39A)
0.180;-1656.2
3J(3A)
0.263;-1518.7
(345A)
0.216;-2312.5
(349A)
0.206;-2037.5
(34KA)
0.159;-1762.5
46(3A)
0.192;-2243.8
(49)(3A)
0.183;-1587.5
4(3QA)
0.176;-1831.2
6(35A)
0.179;-2175.0
T(35A)
0.200;-1900.0
5(36A)
0.205;-2175.0
58(3A)
0.201;-2037.5
(5J)(3A)
0.224;-1381.2
6(36A)
0.248;-1656.2
T(36A)
0.218;-1831.2
6(37A)
0.178;-2037.5
69(3A)
0.217;-1900.0
(6Q)(3A)
0.250;-1243.8
(379A)
0.176;-1831.2
(37KA)
0.250;-1556.2
79(3A)
0.210;-1831.2
(7Q)(3A)
0.221;-1175.0
(38TA)
0.205;-1693.7
88(3A)
0.181;-1381.2
(8J)(3A)
0.302;-1175.0
9(39A)
0.236;-1243.8
K(39A)
0.287;-1418.7
9(3QA)
0.275;-1487.5
J(3TA)
0.245;-1487.5
TJ(3A)
0.175;-1487.5
(3JQA)
0.186;-1350.0
J(3KA)
0.224;-1281.2
(QK)(3A)
0.213;-762.5
33(5A)
0.197;-1931.2
337A
0.193;-2243.8
3A(3T)
0.273;-1587.5
33(KA)
0.253;-1381.2
3(46A)
0.221;-2243.8
38(4A)
0.183;-2106.2
(3J)(4A)
0.175;-1450.0
4A(34)
0.193;-1931.2
A(347)
0.181;-2175.0
(34)(TA)
0.263;-1518.7
QA(34)
0.190;-1831.2
345A
0.175;-2762.5
347A
0.138;-2625.0
349A
0.196;-2487.5
34JA
0.140;-2350.0
34KA
0.137;-2212.5
37(5A)
0.210;-2106.2
(3T)(5A)
0.261;-1450.0
3(5KA)
0.210;-1693.7
A(357)
0.237;-2106.2
(35)(TA)
0.242;-1450.0
QA(35)
0.150;-1762.5
356A
0.133;-2625.0
358A
0.165;-2487.5
35TA
0.222;-2350.0
35QA
0.185;-2212.5
(37)(6A)
0.240;-1587.5
3(6TA)
0.156;-1831.2
3Q(6A)
0.225;-1693.7
(36)(8A)
0.183;-1518.7
TA(36)
0.167;-1831.2
A(36K)
0.191;-1625.0
6A(38)
0.194;-1968.7
6A(3T)
0.193;-1831.2
6A(3Q)
0.211;-1693.7
37(7A)
0.193;-1518.7
(3T)(7A)
0.242;-1312.5
3(7KA)
0.230;-1556.2
A(379)
0.262;-1831.2
(37)(QA)
0.225;-1175.0
7A(38)
0.185;-1900.0
7A(3T)
0.198;-1762.5
7A(3Q)
0.256;-1625.0
38(8A)
0.182;-1381.2
(3J)(8A)
0.209;-1175.0
8A(38)
0.233;-1381.2
A(38J)
0.216;-1625.0
388A
0.178;-1831.2
38TA
0.188;-2143.8
38QA
0.168;-2006.2
(3T)(9A)
0.224;-1175.0
3(9KA)
0.227;-1418.7
A(39J)
0.249;-1556.2
399A
0.230;-1693.7
39JA
0.152;-2006.2
39KA
0.241;-1868.7
3Q(TA)
0.188;-1418.7
(3T)(QA)
0.272;-968.7
TA(3J)
0.168;-1487.5
TA(3K)
0.259;-1350.0
3(JKA)
0.237;-1281.2
A(3JK)
0.205;-1281.2
JA(3K)
0.221;-1281.2
QA(3Q)
0.278;-831.2
3QKA
0.235;-1662.5
45(4A)
0.207;-1793.7
(48)(4A)
0.204;-1137.5
4(4JA)
0.223;-1381.2
4K(4A)
0.236;-1243.8
(459A)
0.196;-1900.0
(45KA)
0.226;-1625.0
57(4A)
0.208;-2037.5
(5T)(4A)
0.216;-1381.2
5(4KA)
0.220;-1625.0
(469A)
0.166;-1831.2
(46KA)
0.236;-1556.2
68(4A)
0.178;-1900.0
(6J)(4A)
0.183;-1243.8
7(47A)
0.240;-1450.0
J(47A)
0.219;-1625.0
78(4A)
0.162;-1831.2
(7J)(4A)
0.229;-1175.0
8(48A)
0.218;-1312.5
Q(48A)
0.227;-1487.5
(8T)(4A)
0.227;-1175.0
8(4KA)
0.234;-1418.7
(49QA)
0.199;-1418.7
9(4JA)
0.230;-1487.5
9K(4A)
0.229;-1350.0
TT(4A)
0.189;-1037.5
(TK)(4A)
0.272;-831.2
J(4QA)
0.237;-1281.2
K(4QA)
0.212;-1143.7
44(5A)
0.200;-1793.7
447A
0.198;-2106.2
4A(4T)
0.184;-1450.0
44(KA)
0.237;-1243.8
4(57A)
0.228;-2037.5
49(5A)
0.176;-1900.0
(4Q)(5A)
0.190;-1243.8
6A(45)
0.203;-2106.2
A(459)
0.196;-1900.0
(45)(QA)
0.264;-1243.8
5A(46)
0.155;-2106.2
5A(48)
0.197;-1968.7
5A(4T)
0.219;-1831.2
5A(4Q)
0.224;-1693.7
46(6A)
0.236;-1587.5
(49)(6A)
0.215;-1381.2
4(6QA)
0.189;-1625.0
A(467)
0.204;-1968.7
(46)(TA)
0.279;-1312.5
QA(46)
0.218;-1625.0
467A
0.162;-2418.7
469A
0.168;-2281.2
46JA
0.161;-2143.8
46KA
0.218;-2006.2
49(7A)
0.220;-1762.5
(4Q)(7A)
0.243;-1106.2
8A(47)
0.160;-1831.2
A(47J)
0.258;-1625.0
477A
0.173;-1900.0
479A
0.187;-2212.5
47JA
0.169;-2075.0
47KA
0.193;-1937.5
4T(8A)
0.258;-1625.0
(4K)(8A)
0.284;-968.7
TA(48)
0.205;-1625.0
A(48K)
0.244;-1418.7
8A(4T)
0.255;-1625.0
8A(4Q)
0.220;-1487.5
49(9A)
0.226;-1175.0
(4Q)(9A)
0.197;-968.7
TA(49)
0.219;-1556.2
A(49K)
0.195;-1350.0
9A(4J)
0.209;-1487.5
9A(4K)
0.185;-1350.0
4(TQA)
0.202;-1350.0
A(4TJ)
0.233;-1418.7
4TTA
0.230;-1487.5
4TQA
0.219;-1800.0
(4Q)(JA)
0.235;-831.2
QA(4J)
0.198;-1281.2
4JQA
0.177;-1731.2
(4K)(QA)
0.281;-693.8
QA(4K)
0.248;-1143.7
5(56A)
0.235;-1587.5
58(5A)
0.240;-1450.0
(5J)(5A)
0.247;-793.7
6(56A)
0.191;-1518.7
T(56A)
0.261;-1693.7
6(57A)
0.180;-1900.0
69(5A)
0.207;-1762.5
(6Q)(5A)
0.192;-1106.2
(579A)
0.208;-1693.7
(57KA)
0.227;-1418.7
79(5A)
0.204;-1693.7
(7Q)(5A)
0.227;-1037.5
(58TA)
0.216;-1556.2
88(5A)
0.247;-1243.8
(8J)(5A)
0.261;-1037.5
9(59A)
0.225;-1106.2
K(59A)
0.222;-1281.2
9(5QA)
0.212;-1350.0
J(5TA)
0.272;-1350.0
TJ(5A)
0.215;-1350.0
(5JQA)
0.228;-1212.5
J(5KA)
0.248;-1143.7
(QK)(5A)
0.231;-625.0
55(7A)
0.218;-1518.7
559A
0.193;-1831.2
5A(5Q)
0.270;-1175.0
(57)(6A)
0.206;-1450.0
5(6TA)
0.234;-1693.7
5Q(6A)
0.196;-1556.2
(56)(8A)
0.196;-1381.2
TA(56)
0.165;-1693.7
A(56K)
0.260;-1487.5
6A(58)
0.241;-1831.2
6A(5T)
0.207;-1693.7
6A(5Q)
0.161;-1556.2
57(7A)
0.192;-1381.2
(5T)(7A)
0.246;-1175.0
5(7KA)
0.210;-1418.7
A(579)
0.256;-1693.7
(57)(QA)
0.239;-1037.5
7A(58)
0.245;-1762.5
7A(5T)
0.217;-1625.0
7A(5Q)
0.264;-1487.5
58(8A)
0.253;-1243.8
(5J)(8A)
0.254;-1037.5
8A(58)
0.225;-1243.8
A(58J)
0.262;-1487.5
588A
0.253;-1693.7
58TA
0.185;-2006.2
58QA
0.252;-1868.7
(5T)(9A)
0.237;-1037.5
5(9KA)
0.210;-1281.2
A(59J)
0.211;-1418.7
599A
0.209;-1556.2
59JA
0.186;-1868.7
59KA
0.193;-1731.2
5Q(TA)
0.276;-1281.2
(5T)(QA)
0.268;-831.2
TA(5J)
0.247;-1350.0
TA(5K)
0.185;-1212.5
5(JKA)
0.214;-1143.7
A(5JK)
0.279;-1143.7
JA(5K)
0.251;-1143.7
QA(5Q)
0.262;-693.8
5QKA
0.218;-1525.0
67(6A)
0.238;-1381.2
(6T)(6A)
0.252;-725.0
6(6KA)
0.217;-968.7
(67TA)
0.256;-1556.2
77(6A)
0.238;-1312.5
(7T)(6A)
0.183;-1106.2
7(6KA)
0.286;-1350.0
(68JA)
0.192;-1418.7
(89)(6A)
0.227;-1106.2
8(6QA)
0.227;-1350.0
T(69A)
0.195;-1418.7
9(6TA)
0.207;-1418.7
9Q(6A)
0.220;-1281.2
Q(6TA)
0.248;-1212.5
(TQ)(6A)
0.305;-762.5
(6JKA)
0.189;-1075.0
JK(6A)
0.254;-1075.0
K(6KA)
0.207;-487.5
668A
0.194;-1762.5
6A(6J)
0.250;-1106.2
(67)(7A)
0.265;-862.5
6(7TA)
0.187;-1556.2
6Q(7A)
0.220;-1418.7
(67)(9A)
0.283;-1175.0
JA(67)
0.239;-1487.5
67(8A)
0.241;-1693.7
67(TA)
0.196;-1556.2
67(QA)
0.255;-1418.7
(68)(8A)
0.300;-725.0
6(8JA)
0.210;-1418.7
6K(8A)
0.232;-1281.2
(68)(JA)
0.232;-968.7
KA(68)
0.291;-1281.2
6A(8T)
0.227;-1487.5
6A(8Q)
0.221;-1350.0
6(9TA)
0.211;-1418.7
6Q(9A)
0.269;-1281.2
(69)(JA)
0.280;-900.0
KA(69)
0.223;-1212.5
6A(9J)
0.202;-1350.0
6A(9K)
0.206;-1212.5
(6Q)(TA)
0.308;-762.5
JA(6T)
0.226;-1281.2
6T(JA)
0.233;-1281.2
6T(KA)
0.222;-1143.7
6Q(JA)
0.201;-1143.7
(6J)(KA)
0.210;-625.0
6J(KA)
0.245;-1075.0
6K(QA)
0.235;-1006.2
6A(QK)
0.240;-1006.2
(78)(7A)
0.250;-725.0
7(7JA)
0.221;-968.7
7K(7A)
0.229;-831.2
(78QA)
0.254;-1281.2
8(7TA)
0.186;-1418.7
8Q(7A)
0.260;-1281.2
J(79A)
0.219;-1281.2
9T(7A)
0.247;-1350.0
(9K)(7A)
0.240;-693.8
K(7TA)
0.261;-1075.0
T(7KA)
0.253;-1075.0
JJ(7A)
0.236;-693.8
(7QKA)
0.265;-937.5
777A
0.213;-1243.8
7A(7T)
0.203;-1037.5
77(KA)
0.233;-831.2
7(8TA)
0.198;-1418.7
7Q(8A)
0.253;-1281.2
(78)(TA)
0.266;-968.7
QA(78)
0.190;-1281.2
789A
0.192;-1937.5
78JA
0.183;-1800.0
78KA
0.219;-1662.5
7J(9A)
0.254;-1281.2
(79)(TA)
0.279;-900.0
QA(79)
0.188;-1212.5
79TA
0.176;-1800.0
79QA
0.238;-1662.5
(7J)(TA)
0.266;-762.5
TA(7T)
0.219;-831.2
A(7TK)
0.229;-1075.0
TA(7Q)
0.262;-1143.7
7J(JA)
0.275;-693.8
(7J)(QA)
0.249;-625.0
JA(7Q)
0.295;-1075.0
7Q(QA)
0.303;-556.2
7QQA
0.225;-1006.2
7KKA
0.191;-868.8
8(8JA)
0.261;-831.2
8K(8A)
0.238;-693.8
(89KA)
0.209;-1075.0
9J(8A)
0.207;-1212.5
(8TJA)
0.236;-1143.7
(TJ)(8A)
0.313;-693.8
J(8JA)
0.281;-625.0
JQ(8A)
0.264;-1006.2
Q(8KA)
0.254;-868.8
889A
0.266;-1418.7
8A(8Q)
0.309;-762.5
(8T)(9A)
0.214;-831.2
8(9KA)
0.215;-1075.0
A(89J)
0.179;-1212.5
899A
0.214;-1350.0
89JA
0.205;-1662.5
89KA
0.215;-1525.0
8Q(TA)
0.272;-1075.0
(8T)(QA)
0.250;-625.0
TA(8J)
0.242;-1143.7
TA(8K)
0.251;-1006.2
8(JKA)
0.242;-937.5
A(8JK)
0.273;-937.5
JA(8K)
0.220;-937.5
QA(8Q)
0.292;-487.5
8QKA
0.202;-1318.7
9T(9A)
0.290;-762.5
(9K)(9A)
0.319;-106.2
K(9TA)
0.245;-937.5
T(9KA)
0.258;-937.5
JJ(9A)
0.291;-556.2
(9QKA)
0.262;-800.0
999A
0.232;-831.2
9A(9Q)
0.242;-625.0
(9J)(TA)
0.279;-625.0
TA(9T)
0.272;-693.8
A(9TK)
0.202;-937.5
TA(9Q)
0.210;-1006.2
9J(JA)
0.350;-556.2
(9J)(QA)
0.254;-487.5
JA(9Q)
0.249;-937.5
9Q(QA)
0.340;-418.8
9QQA
0.287;-868.8
9KKA
0.258;-731.2
T(TKA)
0.290;-418.8
JJ(TA)
0.252;-487.5
(TQKA)
0.257;-731.2
TTTA
0.294;-625.0
TA(TK)
0.268;-418.8
(TK)(JA)
0.320;-350.0
KA(TJ)
0.256;-800.0
TA(JK)
0.219;-800.0
(TQ)(KA)
0.258;-281.3
(TK)(KA)
0.327;237.5
J(JKA)
0.268;-281.3
(QK)(JA)
0.330;-212.5
JJ(KA)
0.250;-281.3
QA(JQ)
0.262;-281.3
JQKA
0.219;-1112.5
QK(QA)
0.263;-143.8
QK(KA)
0.320;-75.0
22(24)
0.179;-2512.5
22(28)
0.156;-2237.5
22(2Q)
0.186;-1962.5
24(23)
0.170;-2893.8
(23)(27)
0.173;-2237.5
2(23T)
0.202;-2481.2
2Q(23)
0.169;-2343.8
23(25)
0.141;-2825.0
2237
0.109;-3137.5
22(3T)
0.156;-2481.2
23(2K)
0.175;-2275.0
2(246)
0.157;-2687.5
28(24)
0.144;-2550.0
(24)(2J)
0.182;-1893.7
2244
0.122;-2825.0
22(47)
0.175;-2618.8
24(2T)
0.168;-2412.5
224Q
0.186;-2725.0
26(25)
0.150;-2618.8
(25)(29)
0.224;-1962.5
2(25Q)
0.206;-2206.2
22(56)
0.130;-2618.8
25(29)
0.148;-2412.5
225J
0.173;-2725.0
26(26)
0.189;-2100.0
(26)(29)
0.178;-1893.7
2(26Q)
0.233;-2137.5
22(67)
0.133;-2481.2
26(2T)
0.203;-2275.0
226Q
0.153;-2587.5
28(27)
0.209;-2343.8
(27)(2J)
0.223;-1687.5
2277
0.161;-2412.5
22(7T)
0.145;-2206.2
27(2K)
0.175;-2000.0
2(28T)
0.186;-2137.5
2Q(28)
0.188;-2000.0
28(2T)
0.178;-2137.5
228Q
0.166;-2450.0
2T(29)
0.148;-2068.7
(29)(2K)
0.215;-1412.5
229J
0.192;-2450.0
2T(2T)
0.201;-1550.0
(2T)(2K)
0.208;-1343.7
22TQ
0.189;-2312.5
2Q(2J)
0.169;-1793.7
2J(2K)
0.250;-1725.0
22QQ
0.196;-1725.0
3(234)
0.129;-2825.0
36(23)
0.125;-2687.5
(23)(39)
0.217;-2031.2
3(23Q)
0.153;-2275.0
5(234)
0.129;-3137.5
9(234)
0.121;-2862.5
K(234)
0.190;-2587.5
4(237)
0.176;-3000.0
49(23)
0.165;-2862.5
(23)(4Q)
0.190;-2206.2
(2357)
0.151;-2931.2
(235J)
0.176;-2656.2
(23)(56)
0.130;-2550.0
5(239)
0.158;-2793.7
5J(23)
0.175;-2656.2
(2367)
0.175;-2862.5
(236J)
0.177;-2587.5
(23)(67)
0.152;-2412.5
6(23T)
0.208;-2656.2
6Q(23)
0.164;-2518.8
9(237)
0.173;-2656.2
K(237)
0.183;-2381.2
7(23T)
0.176;-2587.5
7Q(23)
0.198;-2450.0
T(238)
0.198;-2518.8
8(239)
0.196;-2587.5
8J(23)
0.157;-2450.0
(239T)
0.188;-2450.0
99(23)
0.166;-2068.7
(23)(9Q)
0.186;-1862.5
(23TQ)
0.185;-2243.8
T(23Q)
0.236;-2243.8
Q(23J)
0.158;-2175.0
(23)(JK)
0.207;-1656.2
QK(23)
0.215;-2037.5
23(35)
0.159;-2756.2
33(28)
0.153;-2550.0
233T
0.144;-2862.5
23(3K)
0.184;-2206.2
(24)(36)
0.161;-2618.8
3(249)
0.156;-2862.5
3J(24)
0.165;-2725.0
(34)(25)
0.183;-2687.5
27(34)
0.134;-3000.0
2(34T)
0.134;-2793.7
(34)(2K)
0.206;-2137.5
34(26)
0.157;-3068.7
34(28)
0.152;-2931.2
34(2T)
0.195;-2793.7
34(2Q)
0.189;-2656.2
(25)(35)
0.191;-2168.8
3(258)
0.134;-2862.5
3T(25)
0.137;-2725.0
(25)(3K)
0.209;-2068.7
27(35)
0.168;-2931.2
2(35T)
0.194;-2725.0
(35)(2K)
0.213;-2068.7
35(27)
0.162;-2931.2
35(29)
0.193;-2793.7
35(2J)
0.144;-2656.2
35(2K)
0.217;-2518.8
37(26)
0.134;-2862.5
(26)(3T)
0.168;-2206.2
3(26K)
0.141;-2450.0
2(368)
0.148;-2793.7
(36)(2J)
0.171;-2137.5
2K(36)
0.167;-2450.0
23(68)
0.119;-2793.7
23(6T)
0.217;-2656.2
23(6Q)
0.180;-2518.8
3(278)
0.168;-2725.0
3T(27)
0.180;-2587.5
(27)(3K)
0.161;-1931.2
29(37)
0.210;-2656.2
2(37Q)
0.206;-2450.0
23(78)
0.167;-2725.0
23(7T)
0.166;-2587.5
23(7Q)
0.172;-2450.0
3(289)
0.152;-2587.5
3J(28)
0.192;-2450.0
(38)(29)
0.191;-2137.5
2J(38)
0.189;-2450.0
38(29)
0.172;-2587.5
38(2J)
0.156;-2450.0
38(2K)
0.165;-2312.5
3T(29)
0.174;-2450.0
(29)(3K)
0.228;-1793.8
2J(39)
0.209;-2381.2
39(2T)
0.202;-2450.0
39(2Q)
0.191;-2312.5
(2T)(3T)
0.172;-1481.2
3(2TK)
0.175;-2175.0
2(3TQ)
0.175;-2243.8
23(TJ)
0.179;-2312.5
23(TK)
0.178;-2175.0
(2J)(3K)
0.172;-1656.2
2K(3J)
0.186;-2106.2
23(JK)
0.229;-2106.2
(3Q)(2K)
0.220;-1587.5
(2K)(3K)
0.304;-1068.8
4(246)
0.127;-2550.0
48(24)
0.137;-2412.5
(24)(4J)
0.220;-1756.3
5(245)
0.184;-2550.0
9(245)
0.206;-2725.0
K(245)
0.132;-2450.0
5(248)
0.141;-2793.7
5T(24)
0.166;-2656.2
(24)(5K)
0.185;-2000.0
9(246)
0.166;-2656.2
K(246)
0.150;-2381.2
6(249)
0.177;-2656.2
6J(24)
0.140;-2518.8
(2478)
0.198;-2656.2
(247Q)
0.142;-2381.2
7(249)
0.153;-2587.5
7J(24)
0.173;-2450.0
(2489)
0.181;-2518.8
(248K)
0.167;-2243.8
8T(24)
0.145;-2450.0
(24)(8K)
0.190;-1793.8
Q(249)
0.184;-2243.8
(24)(9J)
0.210;-1862.5
T(24T)
0.187;-1862.5
T(24J)
0.204;-2243.8
TK(24)
0.197;-2106.2
(24)(JQ)
0.176;-1656.2
QQ(24)
0.229;-1587.5
24(45)
0.168;-2618.8
44(28)
0.170;-2412.5
244T
0.145;-2725.0
24(4K)
0.195;-2068.7
(25)(47)
0.185;-2412.5
4(25T)
0.143;-2656.2
4Q(25)
0.189;-2518.8
(45)(27)
0.130;-2412.5
29(45)
0.136;-2725.0
2(45Q)
0.217;-2518.8
24(56)
0.181;-2931.2
24(58)
0.148;-2793.7
24(5T)
0.161;-2656.2
24(5Q)
0.142;-2518.8
4(267)
0.162;-2793.7
49(26)
0.156;-2656.2
(26)(4Q)
0.229;-2000.0
27(46)
0.194;-2793.7
2(46T)
0.138;-2587.5
(46)(2K)
0.221;-1931.2
46(28)
0.121;-2725.0
46(2T)
0.175;-2587.5
46(2Q)
0.195;-2450.0
(27)(47)
0.239;-1825.0
4(27T)
0.183;-2518.8
4Q(27)
0.209;-2381.2
(47)(29)
0.205;-2137.5
2J(47)
0.180;-2450.0
47(28)
0.170;-2656.2
47(2T)
0.157;-2518.8
47(2Q)
0.230;-2381.2
(28)(48)
0.224;-1687.5
4(28J)
0.168;-2381.2
4K(28)
0.148;-2243.8
(48)(2J)
0.207;-1931.2
2K(48)
0.180;-2243.8
24(8T)
0.220;-2450.0
24(8Q)
0.178;-2312.5
4(29T)
0.202;-2381.2
4Q(29)
0.152;-2243.8
(49)(2J)
0.175;-1862.5
2K(49)
0.136;-2175.0
24(9J)
0.129;-2312.5
24(9K)
0.190;-2175.0
(2T)(4Q)
0.177;-1725.0
2J(4T)
0.233;-2243.8
4T(2J)
0.187;-2243.8
4T(2K)
0.164;-2106.2
4Q(2J)
0.181;-2106.2
(4J)(2K)
0.215;-1587.5
4J(2K)
0.179;-2037.5
4K(2Q)
0.184;-1968.7
24(QK)
0.183;-1968.7
(25)(56)
0.197;-1962.5
5(259)
0.181;-2206.2
5J(25)
0.185;-2068.7
(2567)
0.137;-2725.0
(256J)
0.167;-2450.0
(25)(67)
0.166;-2275.0
6(25T)
0.172;-2518.8
6Q(25)
0.152;-2381.2
9(257)
0.131;-2518.8
K(257)
0.180;-2243.8
7(25T)
0.153;-2450.0
7Q(25)
0.190;-2312.5
T(258)
0.161;-2381.2
8(259)
0.172;-2450.0
8J(25)
0.219;-2312.5
(259T)
0.177;-2312.5
99(25)
0.180;-1931.2
(25)(9Q)
0.260;-1725.0
(25TQ)
0.176;-2106.2
T(25Q)
0.146;-2106.2
Q(25J)
0.202;-2037.5
(25)(JK)
0.222;-1518.7
QK(25)
0.215;-1900.0
25(57)
0.187;-2343.8
55(2T)
0.192;-2137.5
255Q
0.214;-2450.0
57(26)
0.156;-2725.0
(26)(5T)
0.185;-2068.7
5(26K)
0.138;-2312.5
2(568)
0.148;-2656.2
(56)(2J)
0.189;-2000.0
2K(56)
0.208;-2312.5
25(68)
0.142;-2656.2
25(6T)
0.172;-2518.8
25(6Q)
0.201;-2381.2
5(278)
0.196;-2587.5
5T(27)
0.144;-2450.0
(27)(5K)
0.166;-1793.8
29(57)
0.135;-2518.8
2(57Q)
0.208;-2312.5
25(78)
0.174;-2587.5
25(7T)
0.191;-2450.0
25(7Q)
0.196;-2312.5
5(289)
0.168;-2450.0
5J(28)
0.198;-2312.5
(58)(29)
0.218;-2000.0
2J(58)
0.216;-2312.5
58(29)
0.151;-2450.0
58(2J)
0.159;-2312.5
58(2K)
0.231;-2175.0
5T(29)
0.214;-2312.5
(29)(5K)
0.252;-1656.2
2J(59)
0.191;-2243.8
59(2T)
0.146;-2312.5
59(2Q)
0.193;-2175.0
(2T)(5T)
0.221;-1343.7
5(2TK)
0.214;-2037.5
2(5TQ)
0.237;-2106.2
25(TJ)
0.172;-2175.0
25(TK)
0.221;-2037.5
(2J)(5K)
0.233;-1518.7
2K(5J)
0.196;-1968.7
25(JK)
0.233;-1968.7
(5Q)(2K)
0.236;-1450.0
(2K)(5K)
0.219;-931.2
6(268)
0.165;-2137.5
6T(26)
0.223;-2000.0
(26)(6K)
0.239;-1343.7
T(267)
0.216;-2381.2
7(268)
0.170;-2518.8
7T(26)
0.173;-2381.2
(26)(7K)
0.171;-1725.0
J(268)
0.169;-2243.8
89(26)
0.145;-2381.2
(26)(8Q)
0.222;-1725.0
(269J)
0.169;-2175.0
(26)(9T)
0.181;-1793.8
9(26K)
0.211;-2037.5
(26TK)
0.242;-1968.7
TQ(26)
0.187;-2037.5
K(26J)
0.177;-1900.0
Q(26Q)
0.214;-1450.0
KK(26)
0.261;-1312.5
66(29)
0.214;-2068.7
266J
0.175;-2381.2
67(27)
0.192;-2137.5
(27)(6T)
0.241;-1931.2
6(27K)
0.169;-2175.0
2(679)
0.193;-2450.0
(67)(2Q)
0.214;-1793.8
27(68)
0.204;-2518.8
27(6T)
0.167;-2381.2
27(6Q)
0.191;-2243.8
68(28)
0.151;-2000.0
(28)(6J)
0.207;-1793.8
28(68)
0.216;-2000.0
2(68J)
0.178;-2243.8
2688
0.199;-2450.0
268T
0.158;-2762.5
268Q
0.142;-2625.0
(29)(6T)
0.215;-1793.8
6(29K)
0.209;-2037.5
2(69J)
0.229;-2175.0
2699
0.184;-2312.5
269J
0.149;-2625.0
269K
0.160;-2487.5
6Q(2T)
0.186;-2037.5
(6T)(2Q)
0.212;-1587.5
2T(6J)
0.192;-2106.2
2T(6K)
0.219;-1968.7
6(2JK)
0.181;-1900.0
2(6JK)
0.208;-1900.0
2J(6K)
0.193;-1900.0
2Q(6Q)
0.277;-1450.0
26QK
0.161;-2281.2
78(27)
0.165;-2000.0
(27)(7J)
0.243;-1343.7
8(278)
0.169;-1931.2
Q(278)
0.183;-2106.2
(27)(8T)
0.158;-1793.8
8(27K)
0.175;-2037.5
(279Q)
0.188;-2037.5
9(27J)
0.177;-2106.2
9K(27)
0.175;-1968.7
TT(27)
0.205;-1656.2
(27)(TK)
0.207;-1450.0
J(27Q)
0.218;-1900.0
K(27Q)
0.195;-1762.5
77(28)
0.207;-2000.0
277T
0.175;-2312.5
27(7K)
0.253;-1656.2
(28)(7T)
0.167;-1793.8
7(28K)
0.215;-2037.5
2(78T)
0.189;-2243.8
(78)(2K)
0.191;-1587.5
78(2T)
0.187;-2243.8
78(2Q)
0.180;-2106.2
(29)(79)
0.227;-1343.7
7(29Q)
0.226;-2037.5
2(79T)
0.183;-2175.0
(79)(2K)
0.244;-1518.7
79(2J)
0.156;-2106.2
79(2K)
0.179;-1968.7
7J(2T)
0.191;-2037.5
(7T)(2J)
0.274;-1587.5
2K(7T)
0.177;-1900.0
27(TQ)
0.242;-1968.7
7(2JQ)
0.173;-1900.0
2(7JQ)
0.205;-1900.0
27(JQ)
0.175;-1900.0
7(2QK)
0.196;-1762.5
7Q(2K)
0.185;-1762.5
88(28)
0.236;-1412.5
(28)(8J)
0.224;-1206.2
9(289)
0.196;-1725.0
K(289)
0.201;-1900.0
9(28Q)
0.216;-1968.7
J(28T)
0.233;-1968.7
TJ(28)
0.213;-1968.7
(28JQ)
0.209;-1831.2
J(28K)
0.218;-1762.5
(28)(QK)
0.231;-1243.8
88(2T)
0.202;-1725.0
288Q
0.197;-2037.5
8T(29)
0.152;-2106.2
(29)(8K)
0.172;-1450.0
2J(89)
0.228;-2037.5
89(2T)
0.206;-2106.2
89(2Q)
0.146;-1968.7
(2T)(8T)
0.236;-1137.5
8(2TK)
0.207;-1831.2
2(8TQ)
0.178;-1900.0
28(TJ)
0.176;-1968.7
28(TK)
0.154;-1831.2
(2J)(8K)
0.268;-1312.5
2K(8J)
0.233;-1762.5
28(JK)
0.236;-1762.5
(8Q)(2K)
0.194;-1243.8
(2K)(8K)
0.261;-725.0
9(29J)
0.225;-1518.7
9K(29)
0.238;-1381.2
TT(29)
0.210;-1518.7
(29)(TK)
0.234;-1312.5
J(29Q)
0.185;-1762.5
K(29Q)
0.192;-1625.0
99(2T)
0.176;-1587.5
299Q
0.231;-1900.0
9J(2T)
0.171;-1900.0
(9T)(2J)
0.263;-1450.0
2K(9T)
0.190;-1762.5
29(TQ)
0.172;-1831.2
9(2JQ)
0.229;-1762.5
2(9JQ)
0.201;-1762.5
29(JQ)
0.238;-1762.5
9(2QK)
0.193;-1625.0
9Q(2K)
0.218;-1625.0
TT(2T)
0.225;-1000.0
(2T)(TK)
0.232;-793.7
J(2TQ)
0.197;-1693.7
K(2TQ)
0.235;-1556.2
TT(2J)
0.222;-1381.2
2TTK
0.255;-1693.7
TK(2J)
0.232;-1625.0
2TJJ
0.197;-1762.5
2TJK
0.193;-2075.0
2(TQK)
0.215;-1556.2
TK(2K)
0.267;-1037.5
(2J)(JK)
0.277;-656.3
QK(2J)
0.235;-1487.5
2J(JK)
0.294;-1106.2
(JQ)(2K)
0.296;-1037.5
(2K)(JK)
0.311;-518.7
K(2QK)
0.241;-900.0
2K(QK)
0.264;-900.0
3335
0.200;-2687.5
3339
0.131;-2412.5
333K
0.232;-2137.5
36(34)
0.150;-2550.0
(34)(39)
0.180;-1893.7
3(34Q)
0.209;-2137.5
33(45)
0.128;-2618.8
34(38)
0.133;-2412.5
334T
0.151;-2725.0
33(4K)
0.171;-2068.7
(35)(37)
0.222;-1962.5
3(35T)
0.169;-2206.2
3Q(35)
0.220;-2068.7
35(37)
0.224;-2412.5
3359
0.147;-2725.0
33(5Q)
0.201;-2068.7
(36)(37)
0.182;-1893.7
3(36T)
0.151;-2137.5
3Q(36)
0.189;-2000.0
36(38)
0.218;-2275.0
336T
0.172;-2587.5
33(6K)
0.199;-1931.2
(37)(39)
0.211;-1687.5
3(37Q)
0.234;-1931.2
33(78)
0.163;-2206.2
37(3J)
0.180;-2000.0
337K
0.167;-2312.5
3T(38)
0.204;-2000.0
(38)(3K)
0.224;-1343.7
338T
0.134;-2450.0
33(8K)
0.187;-1793.7
(39)(3J)
0.207;-1412.5
3399
0.179;-2000.0
33(9Q)
0.185;-1793.7
(3T)(3J)
0.261;-1343.7
33TT
0.221;-1862.5
33(TK)
0.229;-1656.2
(3J)(3K)
0.277;-1137.5
33JK
0.198;-2037.5
33(QK)
0.197;-1518.7
45(34)
0.157;-2550.0
(34)(48)
0.175;-1893.7
4(34J)
0.244;-2137.5
4K(34)
0.179;-2000.0
(3459)
0.206;-2656.2
(345K)
0.167;-2381.2
57(34)
0.198;-2793.7
(34)(5T)
0.219;-2137.5
5(34K)
0.192;-2381.2
(3469)
0.166;-2587.5
(346K)
0.218;-2312.5
68(34)
0.204;-2656.2
(34)(6J)
0.193;-2000.0
7(347)
0.184;-2206.2
J(347)
0.212;-2381.2
78(34)
0.166;-2587.5
(34)(7J)
0.170;-1931.2
8(348)
0.181;-2068.7
Q(348)
0.160;-2243.8
(34)(8T)
0.194;-1931.2
8(34K)
0.159;-2175.0
(349Q)
0.218;-2175.0
9(34J)
0.231;-2243.8
9K(34)
0.218;-2106.2
TT(34)
0.259;-1793.7
(34)(TK)
0.183;-1587.5
J(34Q)
0.212;-2037.5
K(34Q)
0.197;-1900.0
44(35)
0.141;-2550.0
3447
0.138;-2862.5
34(4T)
0.179;-2206.2
44(3K)
0.187;-2000.0
4(357)
0.187;-2793.7
49(35)
0.174;-2656.2
(35)(4Q)
0.188;-2000.0
36(45)
0.119;-2862.5
3(459)
0.177;-2656.2
(45)(3Q)
0.221;-2000.0
35(46)
0.123;-2862.5
35(48)
0.132;-2725.0
35(4T)
0.210;-2587.5
35(4Q)
0.197;-2450.0
46(36)
0.171;-2343.8
(36)(49)
0.202;-2137.5
4(36Q)
0.221;-2381.2
3(467)
0.152;-2725.0
(46)(3T)
0.175;-2068.7
3Q(46)
0.179;-2381.2
3467
0.162;-3175.0
3469
0.128;-3037.5
346J
0.159;-2900.0
346K
0.173;-2762.5
49(37)
0.222;-2518.8
(37)(4Q)
0.177;-1862.5
38(47)
0.168;-2587.5
3(47J)
0.196;-2381.2
3477
0.204;-2656.2
3479
0.119;-2968.8
347J
0.155;-2831.2
347K
0.188;-2693.7
4T(38)
0.187;-2381.2
(38)(4K)
0.222;-1725.0
3T(48)
0.181;-2381.2
3(48K)
0.199;-2175.0
38(4T)
0.170;-2381.2
38(4Q)
0.156;-2243.8
49(39)
0.174;-1931.2
(39)(4Q)
0.207;-1725.0
3T(49)
0.161;-2312.5
3(49K)
0.225;-2106.2
39(4J)
0.196;-2243.8
39(4K)
0.203;-2106.2
4(3TQ)
0.192;-2106.2
3(4TJ)
0.203;-2175.0
34TT
0.200;-2243.8
34TQ
0.144;-2556.2
(3J)(4Q)
0.239;-1587.5
3Q(4J)
0.165;-2037.5
34JQ
0.207;-2487.5
(3Q)(4K)
0.253;-1450.0
3Q(4K)
0.189;-1900.0
5(356)
0.210;-2343.8
58(35)
0.176;-2206.2
(35)(5J)
0.211;-1550.0
6(356)
0.164;-2275.0
T(356)
0.168;-2450.0
6(357)
0.179;-2656.2
69(35)
0.225;-2518.8
(35)(6Q)
0.246;-1862.5
(3579)
0.141;-2450.0
(357K)
0.169;-2175.0
79(35)
0.182;-2450.0
(35)(7Q)
0.206;-1793.8
(358T)
0.191;-2312.5
88(35)
0.158;-2000.0
(35)(8J)
0.222;-1793.8
9(359)
0.173;-1862.5
K(359)
0.188;-2037.5
9(35Q)
0.192;-2106.2
J(35T)
0.189;-2106.2
TJ(35)
0.193;-2106.2
(35JQ)
0.248;-1968.7
J(35K)
0.208;-1900.0
(35)(QK)
0.284;-1381.2
55(37)
0.209;-2275.0
3559
0.175;-2587.5
35(5Q)
0.181;-1931.2
(36)(57)
0.196;-2206.2
5(36T)
0.176;-2450.0
5Q(36)
0.223;-2312.5
(56)(38)
0.195;-2137.5
3T(56)
0.152;-2450.0
3(56K)
0.160;-2243.8
36(58)
0.141;-2587.5
36(5T)
0.197;-2450.0
36(5Q)
0.162;-2312.5
57(37)
0.179;-2137.5
(37)(5T)
0.199;-1931.2
5(37K)
0.215;-2175.0
3(579)
0.204;-2450.0
(57)(3Q)
0.219;-1793.8
37(58)
0.168;-2518.8
37(5T)
0.173;-2381.2
37(5Q)
0.174;-2243.8
58(38)
0.171;-2000.0
(38)(5J)
0.215;-1793.8
38(58)
0.178;-2000.0
3(58J)
0.175;-2243.8
3588
0.166;-2450.0
358T
0.130;-2762.5
358Q
0.136;-2625.0
(39)(5T)
0.195;-1793.8
5(39K)
0.209;-2037.5
3(59J)
0.205;-2175.0
3599
0.177;-2312.5
359J
0.200;-2625.0
359K
0.200;-2487.5
5Q(3T)
0.228;-2037.5
(5T)(3Q)
0.205;-1587.5
3T(5J)
0.213;-2106.2
3T(5K)
0.185;-1968.7
5(3JK)
0.257;-1900.0
3(5JK)
0.215;-1900.0
3J(5K)
0.177;-1900.0
3Q(5Q)
0.251;-1450.0
35QK
0.139;-2281.2
67(36)
0.190;-2137.5
(36)(6T)
0.221;-1481.2
6(36K)
0.225;-1725.0
(367T)
0.156;-2312.5
77(36)
0.168;-2068.7
(36)(7T)
0.199;-1862.5
7(36K)
0.159;-2106.2
(368J)
0.184;-2175.0
(36)(89)
0.195;-1862.5
8(36Q)
0.205;-2106.2
T(369)
0.168;-2175.0
9(36T)
0.208;-2175.0
9Q(36)
0.185;-2037.5
Q(36T)
0.223;-1968.7
(36)(TQ)
0.192;-1518.7
(36JK)
0.186;-1831.2
JK(36)
0.155;-1831.2
K(36K)
0.227;-1243.8
3668
0.204;-2518.8
36(6J)
0.200;-1862.5
(37)(67)
0.219;-1618.8
6(37T)
0.173;-2312.5
6Q(37)
0.225;-2175.0
(67)(39)
0.205;-1931.2
3J(67)
0.203;-2243.8
67(38)
0.149;-2450.0
67(3T)
0.151;-2312.5
67(3Q)
0.171;-2175.0
(38)(68)
0.190;-1481.2
6(38J)
0.212;-2175.0
6K(38)
0.212;-2037.5
(68)(3J)
0.240;-1725.0
3K(68)
0.154;-2037.5
36(8T)
0.176;-2243.8
36(8Q)
0.177;-2106.2
6(39T)
0.181;-2175.0
6Q(39)
0.153;-2037.5
(69)(3J)
0.230;-1656.2
3K(69)
0.222;-1968.7
36(9J)
0.193;-2106.2
36(9K)
0.170;-1968.7
(3T)(6Q)
0.205;-1518.7
3J(6T)
0.164;-2037.5
6T(3J)
0.211;-2037.5
6T(3K)
0.143;-1900.0
6Q(3J)
0.211;-1900.0
(6J)(3K)
0.262;-1381.2
6J(3K)
0.213;-1831.2
6K(3Q)
0.192;-1762.5
36(QK)
0.174;-1762.5
(37)(78)
0.247;-1481.2
7(37J)
0.197;-1725.0
7K(37)
0.179;-1587.5
(378Q)
0.162;-2037.5
8(37T)
0.177;-2175.0
8Q(37)
0.203;-2037.5
J(379)
0.211;-2037.5
9T(37)
0.198;-2106.2
(37)(9K)
0.221;-1450.0
K(37T)
0.224;-1831.2
T(37K)
0.213;-1831.2
JJ(37)
0.235;-1450.0
(37QK)
0.220;-1693.7
3777
0.206;-2000.0
37(7T)
0.169;-1793.7
77(3K)
0.170;-1587.5
7(38T)
0.180;-2175.0
7Q(38)
0.194;-2037.5
(78)(3T)
0.177;-1725.0
3Q(78)
0.166;-2037.5
3789
0.153;-2693.7
378J
0.170;-2556.2
378K
0.154;-2418.7
7J(39)
0.218;-2037.5
(79)(3T)
0.207;-1656.2
3Q(79)
0.217;-1968.7
379T
0.160;-2556.2
379Q
0.219;-2418.7
(3T)(7J)
0.228;-1518.7
3T(7T)
0.225;-1587.5
3(7TK)
0.206;-1831.2
3T(7Q)
0.197;-1900.0
7J(3J)
0.233;-1450.0
(7J)(3Q)
0.254;-1381.2
3J(7Q)
0.252;-1831.2
7Q(3Q)
0.234;-1312.5
37QQ
0.206;-1762.5
37KK
0.216;-1625.0
8(38J)
0.199;-1587.5
8K(38)
0.239;-1450.0
(389K)
0.193;-1831.2
9J(38)
0.185;-1968.7
(38TJ)
0.158;-1900.0
(38)(TJ)
0.201;-1450.0
J(38J)
0.195;-1381.2
JQ(38)
0.182;-1762.5
Q(38K)
0.199;-1625.0
3889
0.185;-2175.0
38(8Q)
0.206;-1518.7
(39)(8T)
0.239;-1587.5
8(39K)
0.179;-1831.2
3(89J)
0.155;-1968.7
3899
0.198;-2106.2
389J
0.190;-2418.7
389K
0.159;-2281.2
8Q(3T)
0.176;-1831.2
(8T)(3Q)
0.251;-1381.2
3T(8J)
0.200;-1900.0
3T(8K)
0.204;-1762.5
8(3JK)
0.214;-1693.7
3(8JK)
0.205;-1693.7
3J(8K)
0.177;-1693.7
3Q(8Q)
0.268;-1243.8
38QK
0.194;-2075.0
9T(39)
0.210;-1518.7
(39)(9K)
0.247;-862.5
K(39T)
0.207;-1693.7
T(39K)
0.215;-1693.7
JJ(39)
0.215;-1312.5
(39QK)
0.244;-1556.2
3999
0.182;-1587.5
39(9Q)
0.199;-1381.2
(3T)(9J)
0.188;-1381.2
3T(9T)
0.270;-1450.0
3(9TK)
0.192;-1693.7
3T(9Q)
0.215;-1762.5
9J(3J)
0.182;-1312.5
(9J)(3Q)
0.257;-1243.8
3J(9Q)
0.233;-1693.7
9Q(3Q)
0.235;-1175.0
39QQ
0.208;-1625.0
39KK
0.242;-1487.5
T(3TK)
0.271;-1175.0
JJ(3T)
0.214;-1243.8
(3TQK)
0.177;-1487.5
3TTT
0.205;-1381.2
3T(TK)
0.249;-1175.0
(3J)(TK)
0.197;-1106.2
3K(TJ)
0.206;-1556.2
3T(JK)
0.225;-1556.2
(TQ)(3K)
0.223;-1037.5
(3K)(TK)
0.312;-518.7
J(3JK)
0.298;-1037.5
(3J)(QK)
0.254;-968.7
JJ(3K)
0.233;-1037.5
3Q(JQ)
0.224;-1037.5
3JQK
0.199;-1868.7
QK(3Q)
0.285;-900.0
QK(3K)
0.260;-831.2
44(46)
0.149;-1962.5
44(4T)
0.201;-1687.5
(45)(45)
0.259;-1512.5
4(458)
0.238;-2206.2
4T(45)
0.224;-2068.7
(45)(4K)
0.285;-1412.5
4457
0.134;-2725.0
44(5T)
0.191;-2068.7
45(4K)
0.208;-1862.5
4(468)
0.187;-2137.5
4T(46)
0.162;-2000.0
(46)(4K)
0.194;-1343.7
4468
0.162;-2587.5
44(6J)
0.176;-1931.2
(47)(47)
0.232;-1237.5
4(47T)
0.187;-1931.2
4Q(47)
0.155;-1793.7
47(49)
0.171;-2000.0
447J
0.141;-2312.5
48(48)
0.267;-1550.0
(48)(4J)
0.235;-1343.7
4488
0.163;-2000.0
44(8J)
0.232;-1793.7
(49)(49)
0.252;-962.5
4(49Q)
0.255;-1656.2
44(9T)
0.169;-1793.7
49(4K)
0.208;-1587.5
4(4TQ)
0.187;-1587.5
44(TJ)
0.176;-1656.2
(4J)(4J)
0.287;-687.5
44JJ
0.266;-1587.5
4Q(4Q)
0.263;-1000.0
(4K)(4K)
0.259;-412.5
(45)(57)
0.184;-1756.3
5(45T)
0.232;-2000.0
5Q(45)
0.233;-1862.5
8(456)
0.176;-2518.8
Q(456)
0.171;-2243.8
(45)(68)
0.202;-2068.7
6(45J)
0.183;-2312.5
6K(45)
0.160;-2175.0
(457J)
0.237;-2243.8
(45)(78)
0.149;-2000.0
7(45J)
0.214;-2243.8
7K(45)
0.143;-2106.2
(458Q)
0.149;-2106.2
8(45T)
0.172;-2243.8
8Q(45)
0.181;-2106.2
J(459)
0.171;-2106.2
9T(45)
0.150;-2175.0
(45)(9K)
0.250;-1518.7
K(45T)
0.215;-1900.0
T(45K)
0.184;-1900.0
JJ(45)
0.285;-1518.7
(45QK)
0.222;-1762.5
4555
0.147;-2343.8
45(58)
0.149;-2137.5
55(4J)
0.199;-1931.2
455K
0.200;-2243.8
58(46)
0.173;-2518.8
(46)(5J)
0.205;-1862.5
46(56)
0.217;-2206.2
4(569)
0.216;-2450.0
(56)(4Q)
0.197;-1793.8
46(57)
0.151;-2587.5
46(59)
0.162;-2450.0
46(5J)
0.190;-2312.5
46(5K)
0.145;-2175.0
5(479)
0.168;-2381.2
5J(47)
0.184;-2243.8
(57)(48)
0.193;-2000.0
4T(57)
0.179;-2312.5
4(57K)
0.177;-2106.2
47(59)
0.170;-2381.2
47(5J)
0.194;-2243.8
47(5K)
0.218;-2106.2
5(48T)
0.204;-2243.8
5Q(48)
0.200;-2106.2
(58)(4T)
0.247;-1793.8
4Q(58)
0.207;-2106.2
4589
0.138;-2762.5
458J
0.127;-2625.0
458K
0.172;-2487.5
5J(49)
0.226;-2106.2
(59)(4T)
0.165;-1725.0
4Q(59)
0.166;-2037.5
459T
0.154;-2625.0
459Q
0.157;-2487.5
(4T)(5J)
0.194;-1587.5
4T(5T)
0.170;-1656.2
4(5TK)
0.203;-1900.0
4T(5Q)
0.226;-1968.7
5J(4J)
0.231;-1518.7
(5J)(4Q)
0.225;-1450.0
4J(5Q)
0.169;-1900.0
5Q(4Q)
0.205;-1381.2
45QQ
0.172;-1831.2
45KK
0.219;-1693.7
6(469)
0.200;-1931.2
6J(46)
0.200;-1793.7
(4678)
0.191;-2381.2
(467Q)
0.202;-2106.2
7(469)
0.138;-2312.5
7J(46)
0.171;-2175.0
(4689)
0.177;-2243.8
(468K)
0.166;-1968.7
8T(46)
0.223;-2175.0
(46)(8K)
0.263;-1518.7
Q(469)
0.212;-1968.7
(46)(9J)
0.232;-1587.5
T(46T)
0.246;-1587.5
T(46J)
0.206;-1968.7
TK(46)
0.209;-1831.2
(46)(JQ)
0.248;-1381.2
QQ(46)
0.219;-1312.5
46(67)
0.148;-2068.7
66(4T)
0.170;-1862.5
466Q
0.162;-2175.0
68(47)
0.182;-2381.2
(47)(6J)
0.218;-1725.0
47(67)
0.198;-2000.0
4(67T)
0.205;-2243.8
(67)(4K)
0.250;-1587.5
67(49)
0.144;-2312.5
67(4J)
0.204;-2175.0
67(4K)
0.186;-2037.5
69(48)
0.199;-2243.8
(48)(6Q)
0.266;-1587.5
49(68)
0.213;-2243.8
4(68Q)
0.222;-2037.5
46(89)
0.197;-2243.8
46(8J)
0.200;-2106.2
46(8K)
0.201;-1968.7
(49)(6J)
0.242;-1587.5
49(69)
0.157;-1725.0
4(69Q)
0.257;-1968.7
46(9T)
0.201;-2106.2
46(9Q)
0.147;-1968.7
6(4TJ)
0.196;-1968.7
6K(4T)
0.195;-1831.2
(6T)(4K)
0.190;-1381.2
6T(4Q)
0.173;-1900.0
(4J)(6J)
0.235;-1000.0
4J(6J)
0.172;-1450.0
6J(4Q)
0.200;-1831.2
(4Q)(6Q)
0.214;-862.5
4K(6Q)
0.203;-1693.7
4K(6K)
0.244;-1175.0
79(47)
0.167;-1793.7
(47)(7Q)
0.237;-1137.5
(478T)
0.175;-2106.2
88(47)
0.178;-1793.7
(47)(8J)
0.178;-1587.5
9(479)
0.165;-1656.2
K(479)
0.182;-1831.2
9(47Q)
0.164;-1900.0
J(47T)
0.185;-1900.0
TJ(47)
0.160;-1900.0
(47JQ)
0.176;-1762.5
J(47K)
0.178;-1693.7
(47)(QK)
0.217;-1175.0
77(49)
0.180;-1793.7
477J
0.185;-2106.2
78(48)
0.218;-1793.7
(48)(7J)
0.204;-1587.5
48(78)
0.247;-1793.7
4(78J)
0.160;-2037.5
4788
0.202;-2243.8
478T
0.136;-2556.2
478Q
0.164;-2418.7
(49)(7T)
0.217;-1587.5
7(49K)
0.267;-1831.2
4(79J)
0.184;-1968.7
4799
0.200;-2106.2
479J
0.200;-2418.7
479K
0.137;-2281.2
7Q(4T)
0.201;-1831.2
(7T)(4Q)
0.217;-1381.2
4T(7J)
0.144;-1900.0
4T(7K)
0.258;-1762.5
7(4JK)
0.189;-1693.7
4(7JK)
0.223;-1693.7
4J(7K)
0.231;-1693.7
4Q(7Q)
0.219;-1243.8
47QK
0.181;-2075.0
89(48)
0.259;-1656.2
(48)(8Q)
0.285;-1000.0
(489J)
0.202;-1900.0
(48)(9T)
0.207;-1518.7
9(48K)
0.163;-1762.5
(48TK)
0.183;-1693.7
TQ(48)
0.233;-1762.5
K(48J)
0.209;-1625.0
Q(48Q)
0.235;-1175.0
KK(48)
0.230;-1037.5
88(4J)
0.195;-1518.7
488K
0.219;-1831.2
8J(49)
0.203;-1900.0
(89)(4T)
0.203;-1518.7
4Q(89)
0.182;-1831.2
489T
0.158;-2418.7
489Q
0.161;-2281.2
(4T)(8J)
0.274;-1381.2
4T(8T)
0.193;-1450.0
4(8TK)
0.243;-1693.7
4T(8Q)
0.230;-1762.5
8J(4J)
0.201;-1312.5
(8J)(4Q)
0.197;-1243.8
4J(8Q)
0.190;-1693.7
8Q(4Q)
0.214;-1175.0
48QQ
0.233;-1625.0
48KK
0.235;-1487.5
9(49Q)
0.194;-1312.5
J(49T)
0.204;-1762.5
TJ(49)
0.172;-1762.5
(49JQ)
0.277;-1625.0
J(49K)
0.180;-1556.2
(49)(QK)
0.275;-1037.5
99(4J)
0.233;-1381.2
499K
0.259;-1693.7
9Q(4T)
0.164;-1693.7
(9T)(4Q)
0.201;-1243.8
4T(9J)
0.197;-1762.5
4T(9K)
0.155;-1625.0
9(4JK)
0.214;-1556.2
4(9JK)
0.221;-1556.2
4J(9K)
0.171;-1556.2
4Q(9Q)
0.292;-1106.2
49QK
0.149;-1937.5
TJ(4T)
0.199;-1243.8
(4TJQ)
0.245;-1556.2
J(4TK)
0.236;-1487.5
(4T)(QK)
0.215;-968.7
TT(4Q)
0.236;-1175.0
T(4JQ)
0.167;-1556.2
4(TJQ)
0.240;-1556.2
4T(JQ)
0.227;-1556.2
T(4QK)
0.245;-1418.7
TQ(4K)
0.190;-1418.7
JJ(4J)
0.263;-656.3
(4JQK)
0.247;-1350.0
4JJJ
0.257;-1106.2
JQ(4Q)
0.190;-968.7
4JQQ
0.254;-1418.7
4JKK
0.206;-1281.2
QQ(4K)
0.262;-831.2
4KKK
0.279;-693.8
55(59)
0.242;-1550.0
55(5K)
0.223;-1275.0
(56)(58)
0.219;-1550.0
5(56J)
0.223;-1793.7
5K(56)
0.202;-1656.2
56(59)
0.182;-1931.2
556J
0.211;-2243.8
57(57)
0.234;-1550.0
(57)(5T)
0.260;-1343.7
5(57K)
0.182;-1587.5
55(79)
0.218;-1862.5
57(5Q)
0.182;-1656.2
5(589)
0.221;-1793.7
5J(58)
0.162;-1656.2
58(59)
0.158;-1793.7
558J
0.166;-2106.2
59(59)
0.191;-1275.0
(59)(5Q)
0.218;-1068.8
559T
0.186;-2106.2
55(9K)
0.206;-1450.0
(5T)(5Q)
0.242;-1000.0
55TJ
0.212;-1968.7
5J(5J)
0.250;-1000.0
5J(5Q)
0.231;-1381.2
5(5QK)
0.241;-1243.8
5K(5K)
0.242;-725.0
68(56)
0.197;-1931.2
(56)(6J)
0.232;-1275.0
7(567)
0.198;-1931.2
J(567)
0.243;-2106.2
78(56)
0.165;-2312.5
(56)(7J)
0.224;-1656.2
8(568)
0.224;-1793.7
Q(568)
0.213;-1968.7
(56)(8T)
0.199;-1656.2
8(56K)
0.192;-1900.0
(569Q)
0.204;-1900.0
9(56J)
0.200;-1968.7
9K(56)
0.191;-1831.2
TT(56)
0.205;-1518.7
(56)(TK)
0.260;-1312.5
J(56Q)
0.199;-1762.5
K(56Q)
0.163;-1625.0
66(57)
0.215;-2000.0
5669
0.167;-2312.5
56(6Q)
0.198;-1656.2
(57)(68)
0.249;-1862.5
6(57J)
0.177;-2106.2
6K(57)
0.177;-1968.7
(67)(5T)
0.226;-1725.0
5Q(67)
0.215;-2037.5
5678
0.139;-2762.5
567T
0.178;-2625.0
567Q
0.196;-2487.5
(58)(69)
0.225;-1725.0
6(58Q)
0.190;-1968.7
5(689)
0.159;-2175.0
(68)(5Q)
0.202;-1518.7
58(69)
0.209;-2175.0
58(6J)
0.222;-2037.5
58(6K)
0.211;-1900.0
6(59J)
0.153;-1968.7
6K(59)
0.214;-1831.2
(69)(5Q)
0.238;-1450.0
59(6T)
0.170;-2037.5
59(6Q)
0.246;-1900.0
6T(5T)
0.266;-1518.7
(5T)(6K)
0.262;-1312.5
5Q(6T)
0.219;-1831.2
56TJ
0.142;-2350.0
56TK
0.166;-2212.5
6K(5J)
0.205;-1693.7
56JJ
0.186;-1831.2
56JK
0.179;-2143.8
5(6QK)
0.200;-1625.0
6K(5K)
0.177;-1106.2
(57)(79)
0.189;-1275.0
7(57Q)
0.230;-1518.7
9(578)
0.154;-2106.2
K(578)
0.187;-1831.2
8(57J)
0.163;-1968.7
8K(57)
0.208;-1831.2
(579K)
0.159;-1762.5
9J(57)
0.209;-1900.0
(57TJ)
0.219;-1831.2
(57)(TJ)
0.241;-1381.2
J(57J)
0.195;-1312.5
JQ(57)
0.213;-1693.7
Q(57K)
0.212;-1556.2
5778
0.168;-2243.8
57(7J)
0.191;-1587.5
(58)(78)
0.227;-1275.0
7(58J)
0.172;-1968.7
7K(58)
0.196;-1831.2
(78)(5J)
0.189;-1518.7
5K(78)
0.167;-1831.2
57(8T)
0.199;-2037.5
57(8Q)
0.186;-1900.0
7(59T)
0.249;-1968.7
7Q(59)
0.258;-1831.2
(79)(5J)
0.214;-1450.0
5K(79)
0.162;-1762.5
57(9J)
0.171;-1900.0
57(9K)
0.193;-1762.5
(5T)(7Q)
0.196;-1312.5
5J(7T)
0.204;-1831.2
7T(5J)
0.190;-1831.2
7T(5K)
0.243;-1693.7
7Q(5J)
0.232;-1693.7
(7J)(5K)
0.211;-1175.0
7J(5K)
0.219;-1625.0
7K(5Q)
0.224;-1556.2
57(QK)
0.200;-1556.2
(58)(89)
0.187;-1137.5
8(58Q)
0.234;-1381.2
T(589)
0.246;-1900.0
9(58T)
0.211;-1900.0
9Q(58)
0.210;-1762.5
Q(58T)
0.216;-1693.7
(58)(TQ)
0.262;-1243.8
(58JK)
0.206;-1556.2
JK(58)
0.228;-1556.2
K(58K)
0.281;-968.7
588T
0.160;-1968.7
58(8K)
0.216;-1312.5
(59)(8J)
0.264;-1381.2
59(89)
0.212;-1518.7
5(89Q)
0.173;-1762.5
58(9T)
0.172;-1900.0
58(9Q)
0.253;-1762.5
8(5TJ)
0.193;-1762.5
8K(5T)
0.199;-1625.0
(8T)(5K)
0.203;-1175.0
8T(5Q)
0.172;-1693.7
(5J)(8J)
0.278;-793.7
5J(8J)
0.296;-1243.8
8J(5Q)
0.220;-1625.0
(5Q)(8Q)
0.254;-656.3
5K(8Q)
0.238;-1487.5
5K(8K)
0.244;-968.7
9J(59)
0.216;-1312.5
(59TJ)
0.172;-1693.7
(59)(TJ)
0.245;-1243.8
J(59J)
0.279;-1175.0
JQ(59)
0.201;-1556.2
Q(59K)
0.280;-1418.7
599T
0.218;-1831.2
59(9K)
0.238;-1175.0
(5T)(9Q)
0.277;-1175.0
5J(9T)
0.224;-1693.7
9T(5J)
0.214;-1693.7
9T(5K)
0.231;-1556.2
9Q(5J)
0.193;-1556.2
(9J)(5K)
0.204;-1037.5
9J(5K)
0.207;-1487.5
9K(5Q)
0.252;-1418.7
59(QK)
0.243;-1418.7
(5T)(TJ)
0.269;-725.0
J(5TJ)
0.271;-1106.2
JQ(5T)
0.232;-1487.5
Q(5TK)
0.240;-1350.0
5TTJ
0.168;-1625.0
TJ(5J)
0.231;-1106.2
(TJ)(5Q)
0.196;-1037.5
5J(TQ)
0.231;-1487.5
TQ(5Q)
0.240;-968.7
5TQQ
0.230;-1418.7
5TKK
0.244;-1281.2
Q(5JQ)
0.196;-900.0
KK(5J)
0.296;-762.5
(5Q)(JQ)
0.246;-450.0
5K(JQ)
0.204;-1281.2
5K(JK)
0.251;-762.5
5QQQ
0.279;-831.2
KK(5K)
0.340;-175.0
6669
0.164;-1793.8
666K
0.191;-1518.7
69(67)
0.185;-1725.0
(67)(6Q)
0.218;-1068.8
6678
0.183;-2243.8
66(7J)
0.265;-1587.5
(68)(68)
0.197;-825.0
6(68J)
0.248;-1518.7
6K(68)
0.232;-1381.2
68(6J)
0.195;-1518.7
668K
0.167;-1831.2
6J(69)
0.208;-1450.0
69(6T)
0.237;-1518.7
669Q
0.191;-1831.2
6J(6T)
0.233;-1381.2
6T(6J)
0.229;-1381.2
66TK
0.226;-1693.7
6K(6J)
0.230;-1175.0
(6Q)(6Q)
0.314;-275.0
66QK
0.228;-1556.2
7(679)
0.210;-1656.2
7J(67)
0.192;-1518.7
(6789)
0.195;-2037.5
(678K)
0.210;-1762.5
8T(67)
0.172;-1968.7
(67)(8K)
0.227;-1312.5
Q(679)
0.204;-1762.5
(67)(9J)
0.284;-1381.2
T(67T)
0.216;-1381.2
T(67J)
0.182;-1762.5
TK(67)
0.175;-1625.0
(67)(JQ)
0.222;-1175.0
QQ(67)
0.248;-1106.2
67(78)
0.215;-1725.0
77(6J)
0.178;-1518.7
677K
0.194;-1831.2
7T(68)
0.184;-1968.7
(68)(7K)
0.241;-1312.5
6T(78)
0.205;-1968.7
6(78K)
0.266;-1762.5
68(7T)
0.238;-1968.7
68(7Q)
0.196;-1831.2
79(69)
0.195;-1518.7
(69)(7Q)
0.255;-1312.5
6T(79)
0.198;-1900.0
6(79K)
0.259;-1693.7
69(7J)
0.209;-1831.2
69(7K)
0.250;-1693.7
7(6TQ)
0.194;-1693.7
6(7TJ)
0.176;-1762.5
67TT
0.195;-1831.2
67TQ
0.184;-2143.8
(6J)(7Q)
0.224;-1175.0
6Q(7J)
0.194;-1625.0
67JQ
0.196;-2075.0
(6Q)(7K)
0.228;-1037.5
6Q(7K)
0.234;-1487.5
8(689)
0.185;-1518.7
8J(68)
0.211;-1381.2
(689T)
0.209;-1831.2
99(68)
0.207;-1450.0
(68)(9Q)
0.222;-1243.8
(68TQ)
0.173;-1625.0
T(68Q)
0.224;-1625.0
Q(68J)
0.196;-1556.2
(68)(JK)
0.265;-1037.5
QK(68)
0.265;-1418.7
68(8T)
0.288;-1450.0
88(6K)
0.221;-1243.8
8(69J)
0.187;-1762.5
8K(69)
0.267;-1625.0
(89)(6Q)
0.275;-1243.8
69(8T)
0.189;-1831.2
69(8Q)
0.182;-1693.7
8T(6T)
0.210;-1312.5
(6T)(8K)
0.191;-1106.2
6Q(8T)
0.198;-1625.0
68TJ
0.177;-2143.8
68TK
0.225;-2006.2
8K(6J)
0.173;-1487.5
68JJ
0.247;-1625.0
68JK
0.213;-1937.5
6(8QK)
0.224;-1418.7
8K(6K)
0.248;-900.0
(69)(9J)
0.261;-793.7
T(69T)
0.252;-1243.8
T(69J)
0.212;-1625.0
TK(69)
0.208;-1487.5
(69)(JQ)
0.260;-1037.5
QQ(69)
0.205;-968.7
69(9T)
0.198;-1312.5
99(6K)
0.231;-1106.2
9(6TQ)
0.205;-1556.2
6(9TJ)
0.206;-1625.0
69TT
0.187;-1693.7
69TQ
0.152;-2006.2
(6J)(9Q)
0.234;-1037.5
6Q(9J)
0.199;-1487.5
69JQ
0.250;-1937.5
(6Q)(9K)
0.298;-900.0
6Q(9K)
0.197;-1350.0
T(6TJ)
0.243;-1106.2
TK(6T)
0.206;-968.7
(6T)(JQ)
0.227;-968.7
QQ(6T)
0.230;-900.0
6T(TJ)
0.262;-1106.2
(6J)(TJ)
0.252;-587.5
6J(TJ)
0.194;-1037.5
TJ(6Q)
0.194;-1418.7
(6Q)(TQ)
0.348;-450.0
6K(TQ)
0.259;-1281.2
6K(TK)
0.291;-762.5
JK(6J)
0.225;-831.2
K(6JK)
0.269;-693.8
6JJK
0.243;-1281.2
6(JQK)
0.217;-1212.5
JK(6K)
0.231;-693.8
KK(6Q)
0.328;-625.0
6QKK
0.234;-1075.0
77(7T)
0.225;-1068.7
(78)(78)
0.288;-687.5
7(78J)
0.204;-1381.2
7K(78)
0.181;-1243.8
78(7J)
0.220;-1381.2
778K
0.218;-1693.7
7J(79)
0.208;-1312.5
79(7T)
0.219;-1381.2
779Q
0.229;-1693.7
7J(7T)
0.246;-1243.8
7T(7J)
0.226;-1243.8
77TK
0.203;-1556.2
7K(7J)
0.254;-1037.5
(7Q)(7Q)
0.257;-137.5
77QK
0.228;-1418.7
8(78T)
0.230;-1381.2
8Q(78)
0.221;-1243.8
J(789)
0.184;-1693.7
9T(78)
0.214;-1762.5
(78)(9K)
0.193;-1106.2
K(78T)
0.211;-1487.5
T(78K)
0.176;-1487.5
JJ(78)
0.264;-1106.2
(78QK)
0.266;-1350.0
7888
0.219;-1518.7
78(8J)
0.204;-1312.5
(79)(89)
0.231;-931.2
8(79Q)
0.212;-1625.0
7(89T)
0.178;-1762.5
(89)(7K)
0.274;-1106.2
89(7J)
0.228;-1693.7
89(7K)
0.170;-1556.2
8J(7T)
0.177;-1625.0
(8T)(7J)
0.224;-1175.0
7K(8T)
0.190;-1487.5
78(TQ)
0.240;-1556.2
8(7JQ)
0.210;-1487.5
7(8JQ)
0.206;-1487.5
78(JQ)
0.272;-1487.5
8(7QK)
0.288;-1350.0
8Q(7K)
0.210;-1350.0
99(79)
0.225;-862.5
(79)(9Q)
0.287;-656.3
(79TQ)
0.168;-1487.5
T(79Q)
0.224;-1487.5
Q(79J)
0.183;-1418.7
(79)(JK)
0.285;-900.0
QK(79)
0.240;-1281.2
79(9J)
0.237;-1175.0
(7T)(9T)
0.258;-725.0
9(7TK)
0.272;-1418.7
7(9TQ)
0.215;-1487.5
79(TJ)
0.214;-1556.2
79(TK)
0.255;-1418.7
(7J)(9K)
0.255;-900.0
7K(9J)
0.192;-1350.0
79(JK)
0.198;-1350.0
(9Q)(7K)
0.210;-831.2
(7K)(9K)
0.230;-312.5
T(7TQ)
0.193;-968.7
Q(7TJ)
0.233;-1350.0
(7T)(JK)
0.246;-831.2
QK(7T)
0.226;-1212.5
7T(TQ)
0.251;-968.7
(7J)(TQ)
0.243;-900.0
7Q(TJ)
0.265;-1350.0
7TJQ
0.239;-1800.0
(7Q)(TK)
0.298;-762.5
7Q(TK)
0.181;-1212.5
J(7JQ)
0.284;-831.2
K(7JQ)
0.230;-1143.7
JJ(7Q)
0.270;-831.2
J(7QK)
0.184;-1143.7
JQ(7K)
0.219;-1143.7
QQ(7Q)
0.304;-243.8
7Q(QK)
0.216;-625.0
8888
0.298;-1000.0
888Q
0.237;-1175.0
8(89J)
0.290;-1175.0
8K(89)
0.261;-1037.5
89(8Q)
0.205;-1106.2
8(8TJ)
0.210;-1106.2
8K(8T)
0.222;-968.7
8T(8K)
0.226;-968.7
8(8JK)
0.227;-900.0
88(JK)
0.208;-900.0
8Q(8K)
0.302;-831.2
(89)(9T)
0.207;-725.0
9(89K)
0.224;-968.7
(89TK)
0.211;-1350.0
TQ(89)
0.225;-1418.7
K(89J)
0.225;-1281.2
Q(89Q)
0.249;-831.2
KK(89)
0.202;-693.8
99(8Q)
0.264;-1037.5
9(8TJ)
0.231;-1487.5
9K(8T)
0.271;-1350.0
(9T)(8K)
0.250;-900.0
9T(8Q)
0.247;-1418.7
(8J)(9J)
0.244;-518.7
8J(9J)
0.209;-968.7
9J(8Q)
0.239;-1350.0
(8Q)(9Q)
0.308;-381.2
8K(9Q)
0.276;-1212.5
8K(9K)
0.273;-693.8
TQ(8T)
0.277;-900.0
K(8TJ)
0.204;-1212.5
Q(8TQ)
0.289;-762.5
KK(8T)
0.272;-625.0
